### ISSUE TITLE
Remove TypeIdHasher and replace it with StableHasher in debuginfo and symbol hashing

### ISSUE THREAD

**Issue by michaelwoerister** [rust-lang/rust#50424]
At the moment we have two implementations for hashing `Ty` values, the `StableHasher` (which is used for incr. comp. and `TypeId`) and the [TypeIdHasher](https://github.com/rust-lang/rust/blob/d68b0eceaaf719a4702ab13a7ca62dea5d966082/src/librustc/ty/util.rs#L609) which was formerly used for `TypeId` and has some leftover uses in [symbol hash generation](https://github.com/rust-lang/rust/blob/d68b0eceaaf719a4702ab13a7ca62dea5d966082/src/librustc_trans_utils/symbol_names.rs#L147) and [debuginfo](https://github.com/rust-lang/rust/blob/d68b0eceaaf719a4702ab13a7ca62dea5d966082/src/librustc_trans/debuginfo/metadata.rs#L147). 

We should be able to switch the two remaining uses to `StableHasher` quite easily. This might also be a small performance win, since StableHasher is more optimized. 

cc @rust-lang/wg-compiler-performance

**Comment by iancormac84** [comment]
I'd like to work on this one, please.

**Comment by michaelwoerister** [comment]
Sure! The first thing I would do is handling the debuginfo case linked above. Here is an example where you can see how to use the `StableHasher` to hash a type:
https://github.com/rust-lang/rust/blob/d68b0eceaaf719a4702ab13a7ca62dea5d966082/src/librustc/ty/util.rs#L239-L254

Let me know if you need further directions.

**Comment by iancormac84** [comment]
@michaelwoerister how best to show you any progress I've made?

**Comment by michaelwoerister** [comment]
> how best to show you any progress I've made?

You can just post here, as you already did. Alternatively, you can open a work-in-progress PR. Both are fine.

> Do I need to erase regions?

Yes, we want to ignore differences in regions for debuginfo.

> Is the code in TypeIdHasher's implementation of TypeVisitor, in particular visit_ty equivalent to what I have now?

Yes. The `StableHasher` is not based on `TypeVisitor`. Instead it recursively calls `hash_stable()` on components to do the visiting. `StableHasher` is also a bit more general at this point, since it has to handle more cases than `TypeIdHasher`.

**Comment by michaelwoerister** [comment]
> So does the code I wrote also cover the use of hash_discriminant_u8?

Yes, the corresponding code is here:
https://github.com/rust-lang/rust/blob/62889702c9868682a3112a19c75321508d9eb6e6/src/librustc/ich/impls_ty.rs#L860

> How do I write tests for the changes I've made?

The existing tests should cover it. Especially the `src/test/debuginfo` suite.

> Is it now fine to move on to the symbol hash generation code?

Yes. Feel free to open a PR with the changes you did so far, as those should be independent of the symbol hash changes.

**Comment by iancormac84** [comment]
> Yes, the corresponding code is here:
Ah okay, seems as though I missed that implementation for TypeVariants during my searches. Thanks.
