### ISSUE TITLE
rustdoc/stdlib docs: Auto trait implementations are missing reference types.

### ISSUE THREAD

**Issue by alercah** [rust-lang/rust#50431]
The auto traits `Sync` and `RefUnwindSafe` do not indicate anywhere in generated documentation that they are generated for reference types. The [`RefUnwindSafe`](https://doc.rust-lang.org/nightly/std/panic/trait.RefUnwindSafe.html) page appears to not have any auto implementations listed; [`Sync`'s page](https://doc.rust-lang.org/nightly/std/marker/trait.Sync.html) lists auto implementors but does not include references. The [reference](https://doc.rust-lang.org/nightly/std/primitive.reference.html) page covers it in the prose, but neither of the traits appears in the implementation list.

**Comment by ExpHP** [comment]
I think it is not just references, but all builtin types; `u8`, `()`, `[T]`, ...

**Comment by GuillaumeGomez** [comment]
Fixed by #50533.
