### ISSUE TITLE
potentially missing items from rust_2018_edition feature gate

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#50443]
I noticed recently some feature gates that `rust_2018_edition` does not enable that I think it should:

- [ ] `#![feature(catch_expr)]`
- [ ] `#![feature(crate_in_paths)]`
- [ ] `#![feature(crate_visibility_modifier)]`
- [ ] `#![feature(extern_absolute_paths)]`
- [ ] `#![feature(proc_macro)]`
- [ ] `#![feature(in_band_lifetimes)]`
- [ ] `#![feature(termination_trait_test)]`

cc @Manishearth

**Comment by Manishearth** [comment]
Most of these features seem to be enabled already? It's `rust_2018_preview`. It's only catch_expr and proc_macro that aren't.
