### ISSUE TITLE
Implement DerefAsync and DerefMutAsync as Deref and DerefMut in async context

### ISSUE THREAD

**Issue by ijsgaus** [rust-lang/rust#50458]
Introduce traits:
```rust
pub trait DerefAsync {
    type Target: Deref<Target::T>;
    async fn derefAsync(&self) -> Async<T>;
}

impl Deref for T: DerefAsync<Target::TOut> + TOut: Deref<Target :: TOut1>
{
   type Target : Async<TOut1>
   fn deref(&self) {
      self.derefAsync().AndAlso(move |t| t.deref());
   }
}
```
Add support for awaiting derefs. This can be very useful, EG,  in async realization of lazy pattern:
```rust
   let y = 5;
   let lazy = async_lazy!(y, async |a| await!(a + 2));  
   let x : i32 = await!(lazy);
```

**Comment by ijsgaus** [comment]
@ishitatsuyuki Can you give me reference link, i don't know, where it is

**Comment by sfackler** [comment]
https://github.com/rust-lang/rfcs/pull/2394

**Comment by cramertj** [comment]
Closing-- proposals for new features belong on the RFCs repo or in an internals post.

**Comment by nikomatsakis** [comment]
@ijsgaus thanks for the suggestion! I'm going to close this, though, as we don't generally keep have issues in this repo suggested possible future enhancements.
