### ISSUE TITLE
Suggestion for `pub(crate)` not always valid on multiple imports

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#50455]
Given code that looks like:

```rust
mod foo {
    pub struct Bar;
    pub struct Baz;
}

mod bar {
    pub use foo::{Bar, Baz};
}
```

you get:

<details>

```
$ rustc +nightly src/lib.rs --crate-type lib -W rust_2018_idioms
warning: struct is never used: `Bar`
 --> src/lib.rs:2:5
  |
2 |     pub struct Bar;
  |     ^^^^^^^^^^^^^^^
  |
  = note: #[warn(dead_code)] on by default

warning: struct is never used: `Baz`
 --> src/lib.rs:3:5
  |
3 |     pub struct Baz;
  |     ^^^^^^^^^^^^^^^

warning: unreachable `pub` item
 --> src/lib.rs:2:5
  |
2 |     pub struct Bar;
  |     ---^^^^^^^^^^^^
  |     |
  |     help: consider restricting its visibility: `pub(crate)`
  |
  = note: `-W unreachable-pub` implied by `-W rust-2018-idioms`
  = help: or consider exporting it for use by other crates

warning: unreachable `pub` item
 --> src/lib.rs:3:5
  |
3 |     pub struct Baz;
  |     ---^^^^^^^^^^^^
  |     |
  |     help: consider restricting its visibility: `pub(crate)`
  |
  = help: or consider exporting it for use by other crates

warning: unreachable `pub` item
 --> src/lib.rs:7:19
  |
7 |     pub use foo::{Bar, Baz};
  |                   ^^^ help: consider restricting its visibility: `pub(crate)`
  |
  = help: or consider exporting it for use by other crates

warning: unreachable `pub` item
 --> src/lib.rs:7:24
  |
7 |     pub use foo::{Bar, Baz};
  |                        ^^^ help: consider restricting its visibility: `pub(crate)`
  |
= help: or consider exporting it for use by other crates
```

</details>

which when auto-fixed by [`cargo fix`](https://github.com/rust-lang-nursery/rustfix) will produce:

```rust
mod foo {
    pub(crate) struct Bar;
    pub(crate) struct Baz;
}

mod bar {
    pub use foo::{pub(crate), pub(crate)};
}
```

which fails to compile!

cc @Manishearth

**Comment by Manishearth** [comment]
cc @zackmdavis who implemented this


Really, that lint needs to be overhauled, it also manually chops up spans which is _very_ fragile.

**Comment by Manishearth** [comment]
cc @zackmdavis who implemented this

I also wish we had a better answer for this lint than chopping up spans, but the current architecture makes this hard (this has been a problem for clippy forever).


The problem here is that when we do HIR lowering we split apart `use`s, and this totally breaks down.

But we throw away the AST by the time we have access level info.

We can skip this lint for `pub use` for now, but that's not too great.

I don't really have ideas for fixing this.

**Comment by zackmdavis** [comment]
#50476 proposes not making suggestions for `use` items. (The lint itself still fires, of course.)

> I also wish we had a better answer for this lint than chopping up spans, but the current architecture makes this hard (this has been a problem for clippy forever).

We could add spans to [`hir::Visibility`](https://github.com/rust-lang/rust/blob/2c315475eaf22c1e1d1c3e8efc0f9d1c720eb886/src/librustc/hir/mod.rs#L1945-L1950)?
