### ISSUE TITLE
Invalid warning unused_mut

### ISSUE THREAD

**Issue by Boscop** [rust-lang/rust#50463]
I just updated my nightly and now I'm getting this warning:

![image](https://user-images.githubusercontent.com/535593/39662749-18c708b2-5067-11e8-9a34-0bed71161a8c.png)

But it's invalid, the binding has to be mutable, otherwise:

![image](https://user-images.githubusercontent.com/535593/39662756-31cab1e2-5067-11e8-959f-ab0a4acf017f.png)

**Comment by pietroalbini** [comment]
Thanks for reporting this @Boscop! Unfortunately, I can't reproduce this locally, can you give us a reduced snippet that causes the regression?

**Comment by Boscop** [comment]
Hm, this snippet causes the same warning on my machine (nightly 05-04) but not in the playground (nightly 05-07):
https://play.rust-lang.org/?gist=424a607550c14b3cb27ce4994bf9fd6c&version=nightly&mode=debug

I'm updating my nightly now to check with the most recent one..

**Comment by Boscop** [comment]
Hm, even with the most recent nightly 05-07 I get that warning on my machine!

**Comment by Boscop** [comment]
Hm, it's only when it's part of the larger project (where the warning first appeared).
When I extract it into a new project (same code, as in the playground) it doesn't give that warning!
Unfortunately, I don't know how I can go from here, the large project is 20k lines, but this code is literally the same as in the playground example! Just pasted into the project (without the main function).

**Comment by Boscop** [comment]
No, it's closed source (for my job) :/

**Comment by pietroalbini** [comment]
Sure. If you hop into [#rust-release on irc.mozilla.org](https://chat.mibbit.com/?server=irc.mozilla.org&channel=%23rust-release) and ping me I can guide you through bisecting the project yourself.

**Comment by nikomatsakis** [comment]
@Boscop -- is this project by any chance using `#![feature(nll)]`?

**Comment by nikomatsakis** [comment]
Were you ever able to bisect? The https://github.com/rust-lang-nursery/cargo-bisect-rustc tool might be useful to you. =)

**Comment by oli-obk** [comment]
I can confirm that #![feature(nll)] produces said bug https://play.rust-lang.org/?gist=183af0c42d164e5434852c9e6ad81317&version=nightly&mode=debug

**Comment by nikomatsakis** [comment]
cc @KiChjang -- quite likely another regression to track down

**Comment by Boscop** [comment]
@oli-obk Ah thanks! Yes, in the big project where it originally occurred I'm using `#![feature(nll)]`.

**Comment by alexcrichton** [comment]
I think I've encountered this as well at https://play.rust-lang.org/?gist=72cb9080cedd5cced73b23e8454344bd&version=nightly&mode=debug

**Comment by pietroalbini** [comment]
OK, this is not a regression then.

**Comment by alexcrichton** [comment]
I've bisected my comment above to https://github.com/rust-lang/rust/pull/48605 (cc @KiChjang)

**Comment by KiChjang** [comment]
I believe it's the same underlying cause as #50461.
