### ISSUE TITLE
[parallel-queries] Make CrateMetadata::cnum_map immutable

### ISSUE THREAD

**Issue by michaelwoerister** [rust-lang/rust#50502]
The [CrateMetadata::cnum_map](https://github.com/rust-lang/rust/blob/c88992d00169f15d8ff9edac8901245b4d21e1c1/src/librustc_metadata/cstore.rs#L67) field is wrapped in a `Lock` but it does not seem to be mutated anywhere. Less mutable state is always better. To solve this task, remove the `Lock` and make things compile again.

cc @rust-lang/wg-compiler-performance

**Comment by rleungx** [comment]
It seems that `cnum_map` field is mutated [here](https://github.com/rust-lang/rust/blob/master/src/librustc_metadata/creader.rs#L1043), right?

**Comment by michaelwoerister** [comment]
@rleungx Oh, you are right of course. In that case, I'll remove the `E-easy` tag. It's still worth looking into though.

**Comment by michaelwoerister** [comment]
#50532 implements a partial solution. We still have a lock, but its around data that is accessed a lot less.

**Comment by wesleywiser** [comment]
Is this still a partial solution?

**Comment by michaelwoerister** [comment]
It's partial (because it does not reduce the amount of shared mutable state) but it addresses my main concern by not requiring to keep the `cnum_map` in a mutex. So it's fine to close this issue, I think.

Removing more mutable state from `CrateMetadata` would probably require a bigger refactoring.
