### ISSUE TITLE
Tracking issue for Option::xor

### ISSUE THREAD

**Issue by Milack27** [rust-lang/rust#50512]
Today I got myself in a situation in which I had two `Option<T>` values, and I wanted to return the only one that was `Some`. If both of them were `Some`, then I'd rather return `None`. I think it would be perfect to have a `xor` method, very similar to the `or` method:

```Rust
impl<T> Option<T> {

    //...

    fn xor(self, optb: Option<T>) -> Option<T> {
        match (&self, &optb) {
            (&Some(_), &None) => self,
            (&None, &Some(_)) => optb,
            _ => None,
        }
    }
}
```

I think that would solve my problem nicely, and could be useful for a lot of people as well.

**Comment by clarcharr** [comment]
There should also be an `xor_else` method, similar to `or_else`.

**Comment by ollie27** [comment]
There would be no point in a `xor_else` because you always have to evaluate the second argument.

**Comment by clarcharr** [comment]
…good point. Never mind, then.

**Comment by Milack27** [comment]
Implemented on #50553.

**Comment by clarcharr** [comment]
@Milack27 You actually need to keep this issue open as a tracking issue. It hasn't been stabilised yet, so, it can only be used with `#![feature(option_xor)]` at the moment.

If you could rename this issue to "Tracking issue for Option::xor" it would also help make that clear.

**Comment by Milack27** [comment]
@clarcharr Oops, sorry! Just fixed, it.

**Comment by pravic** [comment]
Aren't new methods supposed to be added via RFC?

**Comment by Milack27** [comment]
@pravic I don't know. The same concern was raised in #50553, but it seems the approval of the libs team is sufficient. Initially, I just posted this issue as a feature suggestion, expecting to get the opinions of the community members before going through the RFC process. Nevertheless, I can still write an RFC if it's needed.

**Comment by Centril** [comment]
@sfackler Quite a bit of time has passed since it was first implemented on the 18th of May; How do you feel about stabilizing this?

**Comment by jcotton42** [comment]
Seconding @Centril's question, it's now February 2019

**Comment by sfackler** [comment]
@rfcbot fcp merge

**Comment by withoutboats** [comment]
Seems really nice, I'm not sure if adding another method to option is worth the externalities of that versus people writing match statements

**Comment by Centril** [comment]
Fwiw, I think `opta.xor(optb)` is useful in situations where you e.g. have some optional configuration a, and optional b, and then you only want one of them or it is an error otherwise.

**Comment by Milack27** [comment]
Just for the sake of curiosity, `Option::xor` would have been useful to me when I was solving the Advent of Code 2017. I needed to parse a text file like this:
```
     |          
     |  +--+    
     A  |  C    
 F---|----E|--+ 
     |  |  |  D 
     +B-+  +--+ 
```
Then, I had to follow the path and collect the letters. I could have used `Option::xor` to decide where to go next when I met a corner. Here's a simplified version of the code:

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=cda2bdf9c41964c8aeb01916bd817c2d

**Comment by Amanieu** [comment]
Note that the same thing can also be expressed as `opta.is_some() != optb.is_some()`. Do we really need a separate method just for this?

**Comment by Milack27** [comment]
@Amanieu `opta.is_some() != optb.is_some()` returns a boolean, while `opta.xor(optb)` returns the content.

**Comment by lfairy** [comment]
Does this method exist in other languages? I've never seen such a method in OCaml or Haskell, both languages which make extensive use of option types and have been around much longer than Rust has. That should make us doubt whether this is popular enough to be in the standard library.

**Comment by Milack27** [comment]
@lfairy Your point is reasonable. I'm not familiar with either OCaml or Haskell, but I'd like to point out some possible arguments in favor of Option::xor that could be taken into account when comparing Rust to those languages:

1. Rust already has a stable Option::or method, which works pretty much the same way. When users find it in the documentation, they may expect an Option::xor as well. If OCaml and Haskell also have an equivalent method to Option::or, but not a xor counterpart, it would be interesting to know why.

1. Option::xor is a zero-cost abstraction, which is a valued concept in Rust. It's a tool that allows programmers to do more with less code. But if you don't need to use it, you have no penalties. The footprint of Option::xor in the standard library is also very small. #50553 adds only 36 lines, most of which are documentation comments.

1. Users cannot implement this method in their own crates, as the Option type doesn't belong to them. The alternatives I can think of are a bit cumbersome, or at least not as convenient:
    - Use a match directly
    - Create a function similar to `fn option_xor<T>(opta: Option<T>, optb: Option<T>) -> Option<T>`
    - Create a new trait and implement Option::xor inside it

**Comment by Centril** [comment]
> 1. Rust already has a stable Option::or method, which works pretty much the same way. When users find it in the documentation, they may expect an Option::xor as well. If OCaml and Haskell also have an equivalent method to Option::or, but not a xor counterpart, it would be interesting to know why.

[Haskell's standard library has the more general operation `<|>`:](http://hackage.haskell.org/package/base-4.12.0.0/docs/Control-Applicative.html#t:Alternative)
```haskell
class Applicative f => Alternative f where 
  empty :: f a
  (<|>) :: f a -> f a -> f a
```
and `Maybe` is an instance of `Alternative`.

**Comment by boomshroom** [comment]
> Haskell's standard library has the more general operation <|>:

> ```
 class Applicative f => Alternative f where 
  empty :: f a
  (<|>) :: f a -> f a -> f a
```
> and Maybe is an instance of Alternative

Looking at the implementation, it seems that Haskell's implementation is an inclusive or rather than exclusive and takes the first argument if it's present regardless of the second.

**Comment by Centril** [comment]
@Amanieu & @withoutboats: Since you have expressed doubts, can you confirm that you are OK with moving forward with this?

**Comment by arniu** [comment]
@Milack27 @Centril Isn't it what `Option::or` does?

**Comment by aaditmshah** [comment]
@andre-vm I just wanted to point out that `Option::xor` is not [associative](https://en.wikipedia.org/wiki/Associative_property).

```rust
  lhs
= Some(1).xor(Some(2)).xor(Some(3))
= None.xor(Some(3))
= Some(3)

  rhs
= Some(1).xor(Some(2).xor(Some(3)))
= Some(1).xor(None)
= Some(1)
```

However, boolean xor is associative.

```rust
  lhs
= (true != true) != true
= false != true
= true

  rhs
= true != (true != true)
= true != false
= true
```

Thus, it seems to me that `Option::xor` is not an exclusive or operation (over a functor) in the strictest sense. Nevertheless, it still seems to be a useful operation. Hence, I would suggest adding a remark to the documentation, elucidating that `Option::xor` is not associative.

**Comment by aaditmshah** [comment]
I would also like to point out a simpler operation than `Option::xor`, which can be used to implement `Option::xor`:

```rust
impl<T> Option<T> {
    fn and_not<U>(self, other: Option<U>) -> Option<T> {
        match &other {
            &None => self,
            _ => None,
        }
    }
}
```

The `Option::xor` operation can be implemented using a combination of `Option::and_not` and `Option::or`.

```rust
option_a.xor(option_b) = option_a.and_not(option_b).or(option_b.and_not(option_a))
```

Conversely, we can implement `Option::and_not` using a combination of `Option::xor` and `Option::and`.

```rust
option_a.and_not(option_b) = option_a.xor(option_b).and(option_a)
```

It would be nice to have `Option::and_not` in the core library. However, even if we don't have it, it would be nice to add the previous example to the documentation of `Option::xor`.
