### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by Vm900** [rust-lang/rust#50515]
Hi,folks
Been trying to build but keep getting the following error message:
![rustbuilderror](https://user-images.githubusercontent.com/9399631/39719623-ad7ce15e-5231-11e8-9de1-945325c10407.png)
Please help
Thanks

**Comment by Mark-Simulacrum** [comment]
This looks like you need to install `git` -- could you do so and check whether running `x.py` is successful for you?

**Comment by Aaronepower** [comment]
Triage; Closing this as there hasn't been any response. If you still have this issue feel free to reopen!
