### ISSUE TITLE
rustc panic with "assertion failed: !value.needs_subst()"

### ISSUE THREAD

**Issue by tuxmark5** [rust-lang/rust#50518]
The below example [panics with](https://play.rust-lang.org/?gist=5496fbe42e4a7af39d7260c36dc2150a&version=nightly&mode=debug): `thread 'main' panicked at 'assertion failed: !value.needs_subst()', librustc/traits/query/normalize_erasing_regions.rs:69:9`

I've tried minimizing the example as much as possible and that's the best I can do for now.

Version: rustc 1.27.0-nightly (428ea5f6b 2018-05-06)

```Rust
use std::marker::PhantomData;

struct Meta<A> {
    value: i32,
    type_: PhantomData<A>
}

trait MetaTrait {
    fn get_value(&self) -> i32;
}

impl<A> MetaTrait for Meta<A> {
    fn get_value(&self) -> i32 { self.value }
}

trait Bar {
    fn get_const(&self) -> &dyn MetaTrait;
}

struct Foo<A> {
    value: A
}

impl<A: 'static> Foo<A> {
    const CONST: &'static dyn MetaTrait = &Meta::<Self> {
        value: 10,
        type_: PhantomData
    };
}

impl<A: 'static> Bar for Foo<A> {
    fn get_const(&self) -> &dyn MetaTrait { Self::CONST }
}

fn main() {
    let foo = Foo::<i32> { value: 10 };
    let bar: &dyn Bar = &foo;
    println!("const {}", bar.get_const().get_value());
}
```

**Comment by raidwas** [comment]
I have the same error, interesstingly the error does only happen when using phantom data:
[with phantom data](http://play.rust-lang.org/?gist=fcc0cdd833af5958bbddbfebe24760db&version=stable&mode=debug)
[without phantom data](http://play.rust-lang.org/?gist=4d717f2d77b27b90c0791f26f898deee&version=stable&mode=debug)
(And yes I am writing a Gameboy Emulator)

**Comment by raidwas** [comment]
After some testing i found out it has nothing to do with the PhantomData, since the following code still gives the same error:
```
struct Foo<T>(T);

impl<T> Foo<T>{
  const OP: fn(&T) = |_t| {};
  
  fn foo(&mut self, t: T){
    //does not work
    Self::OP(&t);
  }
}

fn main(){
  Foo(1).foo(1);
}
```

**Comment by tuxmark5** [comment]
I think it's related to promoting references to fat pointers. In your example you promote a closure `|_t| {}` to `dyn FnOnce(T)` (?). In my example, I promote `Meta` to `dyn MetaTrait`.

**Comment by raidwas** [comment]
It seems that the Problem only occurs, when using the associated constant from inside the implementation block:
http://play.rust-lang.org/?gist=e7f9f10cde5ca4b0c52588c26b6388cf&version=stable&mode=debug&edition=2015

**Comment by nikolads** [comment]
I found a different example which gives the same error:

```rust
struct MyBox<T>(*mut T);

impl<T> MyBox<T> {
    fn get(&self) -> Option<&T> {
        match self.0 {
            Self::NULL => None,
            ptr => unsafe { Some(&*ptr) },
        }
    }

    const NULL: *mut T = ::std::ptr::null_mut();
}
```

```
thread 'main' panicked at 'assertion failed: !value.needs_subst()', librustc/traits/query/normalize_erasing_regions.rs:69:9
error: internal compiler error: unexpected panic
note: rustc 1.27.0 (3eda71b00 2018-06-19) running on x86_64-unknown-linux-gnu
```

It only ICEs if I initialize `NULL` with a `const fn`. It compiles after replacing the line with
```rust
    const NULL: *mut T = 0 as *mut T;
```

Moving the function outside the impl block still ICEs, but with a different error:

```rust
struct MyBox<T>(*mut T);

impl<T> MyBox<T> {
    const NULL: *mut T = ::std::ptr::null_mut();
}

fn get<'a, T>(ptr: *mut T) -> Option<&'a T> {
    match ptr {
        MyBox::<T>::NULL => None,
        ptr => unsafe { Some(&*ptr) },
    }
}
```

```
error: internal compiler error: librustc/ty/subst.rs:493: Type parameter `T/#1` (T/1) out of range when substituting (root type=Some(T)) substs=[T]

thread 'main' panicked at 'Box<Any>', librustc_errors/lib.rs:499:9
```

**Comment by matklad** [comment]
Hit this in https://github.com/matklad/once_cell, in stable(1.28.0), beta(1.29.0-beta.1) and nightly ( 2018-08-03). 

Here's the commit which exemplifies the issue: https://github.com/matklad/once_cell/commit/ea1c14b51fb860d23810dc2d9ba3822647ce7288 (run `cargo test --no-default-features` to trigger). Basically, I cant newtype-wrap a struct with `INIT: Self`, which requires me to duplicate doc comments :(

**Comment by matklad** [comment]
Triage: both the original example and the once_cell bug no longer reproduce for me on 1.31.1 (2018 release) and 1.34.1 (stable at the time of writing).

The issue should probably be closed. Or do we want to add run-pass test just in case?

**Comment by estebank** [comment]
Lets add a regression test.
