### ISSUE TITLE
Reference to a static object within const fn leads to compiler panic.

### ISSUE THREAD

**Issue by dark0ne** [rust-lang/rust#50529]
I am initializing a reference to an object with static lifetime within a const function and the compiler panics.
I reduced the code to the following example:

https://play.rust-lang.org/?gist=2581bfb95f9f8e3f306bee0862f9f415&version=nightly&mode=debug

I get the compiler output:

error: internal compiler error: librustc_mir/monomorphize/collector.rs:1162: alloc id without corresponding allocation: 7

thread 'main' panicked at 'Box<Any>', librustc_errors/lib.rs:554:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: aborting due to previous error

note: the compiler unexpectedly panicked. this is a bug.

note: rustc 1.27.0-nightly (565235ee7 2018-05-07) running on x86_64-unknown-linux-gnu

note: compiler flags: -C codegen-units=1 -C debuginfo=2 --crate-type bin

**Comment by oli-obk** [comment]
This is another symptom of https://github.com/rust-lang/rust/issues/49955

You can work around it by using `&(&FOO)[bar]`
