### ISSUE TITLE
tidy script should ignore directories not following the style guide it checks

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/rust#50535]
I get a gazillion error from `rust/src/binaryen` when running the tidy script. If the whole directory does not follow the style guide, it should be ignored.

**Comment by oli-obk** [comment]
I think you're just seeing a submodule that doesn't exist anymore, but your checkout still contains it as a directory?

**Comment by gnzlbg** [comment]
Maybe, so I can just delete it ?

**Comment by oli-obk** [comment]
jup. I've had similar issues before when moving between branches across a submodule deletion

**Comment by kennytm** [comment]
The binaryen folder should be removed. See also the discussion on #50451.

Closing, as this is not a problem of tidy.
