### ISSUE TITLE
Failure to compile cargo - cannot relate bound region

### ISSUE THREAD

**Issue by aenda** [rust-lang/rust#50548]
When running `cargo clippy` on the https://github.com/matthiaskrgr/cargo-rebuild-check repository, I get a failure to compile cargo:
```
error: internal compiler error: librustc/infer/region_constraints/mod.rs:649: cannot relate bound region: ReLateBound(DebruijnIndex { depth: 1 }, BrNamed(crate0:DefIndex(1:886), 'a)) <= ReScope(Remainder(BlockRemainder { block: ItemLocalId(682), first_statement_index: 0 }))

thread 'main' panicked at 'Box<Any>', librustc_errors/lib.rs:499:9
```
I have attached the log and backtrace.
[backtrace.txt](https://github.com/rust-lang/rust/files/1985767/backtrace.txt)

**Comment by phansch** [comment]
This has been reported in clippy some time ago (https://github.com/rust-lang-nursery/rust-clippy/issues/2603) and I will take a look at that crash next.

**Comment by phansch** [comment]
This has been fixed on clippy master and will be in the next clippy release.
