### ISSUE TITLE
Tracking issue for extra floating-point logarithm constants

### ISSUE THREAD

**Issue by clarfon** [rust-lang/rust#50540]
Specifically, `LOG10_2` and `LOG2_10`. PR: #50539

**Comment by clarcharr** [comment]
Has anyone used these constants at all and want to pitch in for stabilisation of these? These have landed for a while and I'm curious how many people are using them.

**Comment by kennytm** [comment]
+1 for stabilization. (Tried to see if log<sub>2</sub>(10) exists and found that it is unstable 🙄.)

**Comment by clarcharr** [comment]
(Mind providing the specific use case? Curious to see if people are using this for anything other than scientific computing.)

**Comment by kennytm** [comment]
@clarcharr to estimate the "&minus;log<sub>2</sub>(probability)" of collision of two values chosen randomly from a set, which will be used to derive the probability of collision of N values (≈ 1 &minus; e<sup>-pN<sup>2</sup>/2</sup>, p &ll; 1, N &gg; 1).

log<sub>2</sub> is chosen instead of natural log because the set size is often 2<sup>n</sup> (e.g. u32), but sometimes it is drawn from a set of n decimal digits which would then involve n·log<sub>2</sub>(10).

**Comment by iliekturtles** [comment]
One [hartley](https://en.wikipedia.org/wiki/Hartley_(unit)) is = `log2(10)` shannons (bits). Currently the constant is duplicated in [uom](https://github.com/iliekturtles/uom).

**Comment by clarfon** [comment]
I can't @ anyone from the libs team but do you think we'd be able to start an FCP for this?

**Comment by varkor** [comment]
cc @rust-lang/libs [for a FCP](https://github.com/rust-lang/rust/issues/50540#issuecomment-518925090).

**Comment by alexcrichton** [comment]
@rfcbot fcp merge

I believe the stabilization includes `core::{f32, f64}::{LOG2_10, LOG10_2}`.

**Comment by LeSeulArtichaut** [comment]
@alexcrichton Does this need a stabilization report/PR?

**Comment by clarfon** [comment]
It needs a PR. Not sure if we should include `TAU` in that though; @m-ou-se, would you be willing to open a separate tracking issue for that, considering how that wasn't included in the FCP for this one?

**Comment by m-ou-se** [comment]
@clarfon There is already #66770.

**Comment by clarfon** [comment]
Oh, my bad. I for some reason noticed that this issue got linked in the PR and thought that there wasn't a separate tracking issue.
