### ISSUE TITLE
Clippy and Miri should not block beta releases

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#50557]
I think this is the fourth beta I'm having to re-figure-out how all this works and figure out how to ignore their failures on beta. @kennytm can we just exclude these tools from toolstate until this is figured out?

**Comment by oli-obk** [comment]
I'm slightly confused, why would these tools need to be disabled/their submodule update if they were building on master? Isn't the beta just the current master branch + some tweaks for --version output and no unstable features?

The release in March actually prevented the merge of any PRs on master that would break a tool. So I thought the idea was to fix all tools in that week.

Or is this about beta backports breaking tools?

**Comment by alexcrichton** [comment]
I don't think we've had a beta yet whether either clippy or miri were passing tests and [checktool.sh on master](https://github.com/rust-lang/rust/blob/8ff4b42064b374bb62043f7729f84b6d979c7667/src/ci/docker/x86_64-gnu-tools/checktools.sh#L89-L91) fails the build if *any* tool fails to build on beta. We also do not want to release either of these tools to stable/beta yet.

**Comment by oli-obk** [comment]
> We also do not want to release either of these tools to stable/beta yet.

neither of these tools has a `Dist` step, so there's no danger in that

> I don't think we've had a beta yet whether either clippy or miri were passing tests

https://github.com/rust-lang/rust/pull/49589/files (the last beta) didn't have clippy issues. Since we have grace period of a week, I can easily get in a working clippy within that week (which then won't be broken until the beta). My issue is mainly that I don't really know when it begins ;)

Maybe we can ping the tool authors once a day that their tool needs to be fixed for the upcoming beta?

**Comment by alexcrichton** [comment]
My point with this issue is that we shouldn't automate ourselves into a hole where tools we do not want to ship block releases. That should not require authors to fix tools, we should simply ignore failures or have an easy way of disabling them. Right now producing a beta is pain as you have to resend it to bors multiple times after re-learning that these are blocking the release.

We do not ship miri/clippy but a successful clippy compilation affects how rls is compiled, which should not be happening on beta/stable.
