### ISSUE TITLE
Rejecting higher-kinded lifetime bounds is a breaking change

### ISSUE THREAD

**Issue by comex** [rust-lang/rust#50555]
```rust
fn foo<'s, F>(s: &'s i32, f: F) where for<'a: 's> F: FnOnce(&'a i32) {
    f(s)
}

fn main() {
    foo(&42, |x| println!("{}", x));
}
```

[Playground Link](https://play.rust-lang.org/?gist=ddbae29bc980ea3f4e6b17aa8d4112ec&version=beta&mode=debug)

This compiles on stable; on beta and above, it produces:

    error: lifetime bounds cannot be used in this context

Apparently this is on purpose:

```
commit 49abd8748357012e5db10bf11077384f727e2177
Author: Ralf Jung <post@ralfj.de>
Date:   Tue Mar 6 11:22:24 2018 +0100

    make bounds on higher-kinded lifetimes a hard error in ast_validation
    
    Also move the check for not having type parameters into ast_validation.
    
    I was not sure what to do with compile-fail/issue-23046.rs: The issue looks like
    maybe the bounds actually played a role in triggering the ICE, but that seems
    unlikely given that the compiler seems to entirely ignore them.  However, I
    couldn't find a testcase without the bounds, so I figured the best I could do is
    to just remove the bounds and make sure at least that keeps working.
```

But it's still a gratuitous breaking change, which seems unfortunate… even if the lifetimes weren't being handled correctly before.

cc @RalfJung

**Comment by RalfJung** [comment]
Yes it is a breaking change indeed. That's why we did a crater run, which came back with a single failure.

However, @comex your code is equivalent to
```rust
fn foo<'s, F>(s: &'s i32, f: F) where for<'a> F: FnOnce(&'a i32) {
...
}
```
That is, the bound you wrote is entirely ignored. So, this only breaks code that already did not do what the author thought it would.

@ExpHP Your `for<'a, 'b: 'a> fn` is equivalent to `for<'a, 'b> fn`. The lifetime bound was completely ignored by the compiler.

**Comment by comex** [comment]
Welp, I didn't realize we were so close to a stable release containing the change in question.  I guess this is now moot.  But I wish the change had gone through a warning cycle.

**Comment by RSSchermer** [comment]
Apologies for resurrecting an old issue; I find myself in need of `for<'a, 'b: 'a> ...` and my google-fu turned up this thread, which makes it seem like it might have been possible at some point.

Is this a false impression, was it just that the syntax didn't trigger an error, but no semantics were attached to it? Or was this indeed a working feature that was removed (presumably for soundness reasons)?

**Comment by RalfJung** [comment]
> was it just that the syntax didn't trigger an error, but no semantics were attached to it? 

That was indeed the case. The bound got parsed, and then ignored.
