### ISSUE TITLE
[QoL] Renaming Generic Types in std to avoid confusion

### ISSUE THREAD

**Issue by shingtaklam1324** [rust-lang/rust#50568]
This is not a functional improvement, but a quality of life and learning curve improvement.

Issue
---

In the type `Result<T, E>`, `unwrap_or_else` has the signature `pub fn unwrap_or_else<F>(self, op: F) -> T`, where `F: FnOnce(E) -> T, `. This has the problem of potentially confusing newcomers (and experienced Rust programmers) as the type `T` in this function doesn't have to be the same type as `Result<T, E>`'s `T`.

Reference
---

https://www.reddit.com/r/rust/comments/8hjwvf/hey_rustaceans_got_an_easy_question_ask_here/dyortmr/

**Comment by Emerentius** [comment]
It actually needs to be exactly that `T` in `Result<T, E>`. I'll try to untangle the confusion over at that reddit thread.

**Comment by shingtaklam1324** [comment]
Yeah, after some experimenting that seems to be the case. However the docs could still be improved in that case. Closed this at the moment as it is not a priority issue at the moment.
