### ISSUE TITLE
Union use unassigned fields

### ISSUE THREAD

**Issue by ZhangHanDong** [rust-lang/rust#50563]
```rust
union U {
    i: i32,
    f: f32,
}
fn main() {
    let mut u1 = U { i: 2 };
    let i  = unsafe { &mut u1.f };
    println!("{:?}", i ); //0.000000000000000000000000000000000000000000003 
}

```

Is this normal output? 

rustc already knows that the type of `i` is `&mut f32`, which should be normally converted to `2.0`.  Can this undefined behavior be avoided？

**Comment by kennytm** [comment]
This behavior is totally defined, and the output is normal. What you are doing here is equivalent to [`f32::from_bits(2)`](https://doc.rust-lang.org/std/primitive.f32.html#method.from_bits). 

If you want 2.0, use `i as f32`.

**Comment by ZhangHanDong** [comment]
@kennytm  I see, thanks

**Comment by kennytm** [comment]
@crlf0710 Ok just changed to say the output is normal 😊. Adding `#[repr(C)]` would still produce 0.00...03 though, as expected.

**Comment by crlf0710** [comment]
@kennytm  right. thanks for the clarification!
