### ISSUE TITLE
LLVM 6 upgrade caused ~25% runtime regression for inflate 0.3.4 decoding

### ISSUE THREAD

**Issue by anp** [rust-lang/rust#50560]
After bisecting, https://github.com/rust-lang/rust/commit/39abcc04139a0fd24422f422271849dc91e39a88 introduced a roughly 25% increase in the runtime of [lolbench's inflate_0_3_4::decode benchmark](https://github.com/anp/lolbench/blob/master/benches/inflate_0_3_4/src/lib.rs#L8-L13).

Summary:

| rust-lang/rust commit                    | est. runtime | 95% ci        |
| ---------------------------------------- | ------------ | ------------- |
| 3bcda48a30b21e46b81a7989deb30a3ba85fb918 | 1.5933 ms    | 1.5778,1.6081 |
| 39abcc04139a0fd24422f422271849dc91e39a88 | 1.9997 ms    | 1.9914,2.0083 |
| change                                   | ~ 25 %       |               |

The regression is (hopefully) reproducible by cloning:

```
$ git clone https://github.com/anp/inflate-regression
$ cd inflate-regression
```

(note: I haven't reduced this beyond the inflate crate's public API -- I need to try to find the actual section of code that's affected)

Here's my output (2016 MBP15). I ran these on my laptop after seeing the change on a x86_64-unknown-linux-gnu machine first.

(rustup targets downloaded by cargo-bisect-rustc)

3bcda48a30b21e46b81a7989deb30a3ba85fb918, bors merge before LLVM 6:

```
$ cargo +ci-3bcda48a30b21e46b81a7989deb30a3ba85fb918-x86_64-apple-darwin run --release
...
decode                  time:   [1.5778 ms 1.5933 ms 1.6081 ms]
...
```

39abcc04139a0fd24422f422271849dc91e39a88:

```
$ cargo +ci-39abcc04139a0fd24422f422271849dc91e39a88-x86_64-apple-darwin run --release
...
decode                  time:   [1.9914 ms 1.9997 ms 2.0083 ms]
```

Current nightly:

```
$ cargo +nightly run --release
...
decode                  time:   [1.9383 ms 1.9466 ms 1.9555 ms]
...
```

**Comment by anp** [comment]
cc @rust-lang/wg-codegen

**Comment by upsuper** [comment]
Might be related to #49873.

**Comment by eddyb** [comment]
Please always compare `inflate` performance changes before and after the debloating https://github.com/PistonDevelopers/inflate/pull/35 (which greatly reduces the code passed to LLVM).

**Comment by anp** [comment]
Haven't had time to reduce this further yet, but a fix for one potential culprit has been backported: https://github.com/rust-lang/llvm/pull/115. Will see what results for this are like when that's in nightly.

**Comment by nikic** [comment]
Current nightly did not improve this, so this is unrelated to #49873.

**Comment by anp** [comment]
@nikic thanks for checking! I'll try to reduce this soon then.

**Comment by steveklabnik** [comment]
Triage: it's been over a year. We're on LLVM... 8? now? Is this ticket still relevant?

**Comment by nox** [comment]
Closing it.
