### ISSUE TITLE
Slice patterns cannot be used in trait methods

### ISSUE THREAD

**Issue by cake4289** [rust-lang/rust#50571]
The following code works on beta:

```rust
fn foo([a, b]: [i32; 2]) {}
```

But when used in a trait like so:

```rust
trait Foo {
    fn foo([a, b]: [i32; 2]) {}
}
```

rustc reports the following error:

```
error: expected one of `!`, `(`, `+`, `::`, `;`, `<`, or `]`, found `,`
 --> src/main.rs:2:14
  |
2 |     fn foo([a, b]: [i32; 2]) {}
  |              ^ expected one of 7 possible tokens here

error: aborting due to previous error
```

**Comment by cake4289** [comment]
Possibly related to rustc expecting possibly a type in this scenario? As you can declare trait methods with no parameter name

**Comment by petrochenkov** [comment]
@cake4289 
>Possibly related to rustc expecting possibly a type in this scenario?

Exactly.
When https://github.com/rust-lang/rust/issues/41686 becomes an error, we'll be able to accept arbitrary patterns in parameters of trait methods, but for now only very limited subset is allowed.

**Comment by varkor** [comment]
The example in the issue now compiles. If we don't have existing tests for this, we ought to add one.
