### ISSUE TITLE
Associated types can be specified multiple times in trait objects

### ISSUE THREAD

**Issue by Marwes** [rust-lang/rust#50589]
```rust
fn test() ->  Box<Iterator<Item = (), Item = ()>> {
    Box::new(None.into_iter())
}
```

It seems rather surprising that the above code actually compiles. Making it an error wouldn't be backwards compatible but a warning would be nice (the same happens with `impl Future<Item = (), Item = ()>` which is where I got burnt, thinking I had specified the `Error` type).

**Comment by abonander** [comment]
Implementing a lint for this would be a good beginner's task I think.

**Comment by gootorov** [comment]
I'd like to work on this starting from Tuesday, if that's ok. Never hacked on a compiler before, anything I need to know besides the [rustc guide](https://rust-lang-nursery.github.io/rustc-guide/about-this-guide.html) for this particular issue? Would appreciate any help!

**Comment by abonander** [comment]
@F001 Hardcoded warnings are strongly discouraged, but it's not that difficult to create a lint anyway. This should get you started; add this to `src/librustc_lint/builtin.rs`:

```rust
declare_lint! {
    // we can bikeshed the lint name
    DUP_ASSOC_TYPE_BINDING,
    Warn,
    "warns about duplicate associated type bindings in generics, e.g. `Iterator<Item = (), Item = ()>`"
}

pub struct DupAssocTypeBinding;

impl LintPass for DupAssocTypeBinding {
    fn get_lints(&self) -> LintArray {
        lint_array!(DUP_ASSOC_TYPE_BINDING)
    }
}

impl EarlyLintPass for DupAssocTypeBinding {
    fn check_generics(&self, ctxt: &EarlyContext, generics: &ast::Generics) {
        // for every param in `generics.params`, if any two `GenericParam::Type(_)` elements have the same `ident` and `default` 
        // but a differing `id`, then emit an error with
        ctxt.span_lint(DUP_ASSOC_TYPE_BINDING, vec![param_span_1, param_span_2], "duplicate associated type binding");
    }
}
```
We can bikeshed the lint message.

This could trigger on something like `struct Foo<A = (), A = ()>(A, A);` but that's hit before lints I believe. If that is a problem we could instead do it in `check_path`.

Also, try to avoid emitting a lint for the same pair twice if you're doing a nested `for` loop; the inner loop should only iterate the elements after the current one. In fact, you should accumulate the duplicated spans inside the inner loop and then emit the lint message in the outer loop, so you lint for all the same duplicated type bindings at once, e.g. `Iterator<Item = (), Item = (), Item = ()>` emits one lint message pointing to them all.

And then in `src/librustc_lint/lib.rs`, in [this macro invocation](https://github.com/rust-lang/rust/blob/master/src/librustc_lint/lib.rs#L115-L140) add `DupAssocTypeBinding` where it fits alphabetically.

Then you'll need to implement a UI test (which you would need to implement if you were emitting the warning in the parser anyway). I can add instructions for that if you need it.

**Comment by F001** [comment]
Wow, what an informative instruction. Thanks very much. I will create a merge request tomorrow.

**Comment by abonander** [comment]
@F001 I had to edit my comment because `check_generics()` was not the right method, just making sure you've seen the latest version.
