### ISSUE TITLE
extract index and bit-set related types into their own crate

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#50592]
Right now they live in rustc_data_structures, but we can rely on crates now. It'd be nicer if they were over in a rust-lang crate, which would let us optimize, test, and otherwise develop them independently from rustc. (It'd also be useful in projects like [borrow-check](https://github.com/rust-lang-nursery/borrow-check)). As you can see in [this comment](https://github.com/rust-lang/rust/issues/50592#issuecomment-510907510), the current plan is to begin doing this "in tree" and only later decide whether to move out of tree.

**Comment by saleemjaffer** [comment]
@nikomatsakis I would like to work on this. I'm new to rust though.

**Comment by saleemjaffer** [comment]
@spastorino I cannot create a crate in rust-lang-nursery. Should I create a new github project and move the bit related types to it?

**Comment by eddyb** [comment]
cc @nnethercote

**Comment by flavius** [comment]
I'm new to the rust compiler, having played on-off with rust for the past two years, and I'd like to get my feet wet with this. Also, what's the go-to communication channel in case I have questions?

**Comment by nnethercote** [comment]
@flavius: Some people are on Discord, see [here](https://www.rust-lang.org/community). Unfortunately, some other people are on Zulip, which isn't mentioned on that page. But Discord is a decent place to start.

**Comment by nikomatsakis** [comment]
We discussed this a bit on [Zulip](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/.2350592.20extract.20bit-related.20types.20to.20crate/near/170720149), and we had the idea that we should start by just creating the crate in tree before we talk about moving it out of tree. 

Here are some mentoring instructions for how we would go about it:

- Create a directory `src/librustc_index` or whatever we decide to call it.
- Copy `src/librustc_data_structures/Cargo.toml` into that directory and adapt it -- probably deleting most all the dependencies and just tweaking the name.
- To start, I would make add `rustc_index` as a dep of `rustc_data_structures` and then `pub use` its API, so that downstream code doesn't have to change.
- Then move over the types one by one -- I'd probably start with the "index" code as all the other types use this `Idx` trait as a kind of common abstraction.
- Once this works, I personally would prefer to remove the `pub use` from librustc_data_structures bit by bit and update the downstream crates. I don't like having multiple paths that lead to the same thing, it's confusing.

I think that should be it!
