### ISSUE TITLE
"cargo build" on nightly rebuilds entire crate after adjacent crate in workplace is built

### ISSUE THREAD

**Issue by tcr** [rust-lang/rust#50596]
First step, I clone the cargo workspace project that had this error: https://github.com/tcr/edit-text/tree/9d2bd2642a0e796d3eb1a7d1cfd333ed4fe43eeb

The `rust-toolchain` version is pegged to `2018-04-08`. With that version of `rustc`, I can do the following:

* `cd mercutio-server; cargo build` — performs a full build of this crate
* `cd ../test; cargo build` — performs a full build of this crate
* `cd ../mercutio-server; cargo build` — Because this is already built, it just outputs the line "Finished ..." indicating the binary does not need recompilation.

But then if I change the `rust-toolchain` version to `2018-05-08`, I see the following:

* `cd mercutio-server; cargo build` — performs a full build of this crate
* `cd ../test; cargo build` — performs a full build of this crate
* `cd ../mercutio-server; cargo build` — A full build of this crate is *again* performed, even though all the result should have been cached.

## Meta

`rustc --version --verbose`:

```
rustc 1.27.0-nightly (056f589fb 2018-04-07)
binary: rustc
commit-hash: 056f589fb8bcd70e7caa2bc7b3ede45624bb8e6d
commit-date: 2018-04-07
host: x86_64-apple-darwin
release: 1.27.0-nightly
LLVM version: 6.0
```

**Comment by alexcrichton** [comment]
@tcr can you check to see if this was fixed? When I try on today's nightly it looks like everything is cached appropriately

**Comment by tcr** [comment]
@alexcrichton Indeed this looks fixed between `2018-05-08` and `2018-05-10`, thank you :)
