### ISSUE TITLE
using extern-prelude does not allow use of std/core

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#50605]
Example ([play](https://play.rust-lang.org/?gist=dd59b53a3b5e7a03573314b919339e89&version=nightly&mode=debug)):

```rust
#![feature(extern_prelude)]

mod foo {
    pub fn test() {
        let x = std::cmp::min(2, 3);
        assert_eq!(x, 2);
    }
}

fn main() {
    foo::test();
}
```

I would expect this to work. (I presume it doesn't because cargo doesn't pass `--extern std`.)

cc @petrochenkov  @Manishearth

**Comment by petrochenkov** [comment]
`std` is not passed via `--extern`, so it can't work through extern prelude.

It needs a separate (library!) addition - `pub use crate as std;` in libstd prelude (which unfortunately doesn't work right now due to some bug I haven't had time to investigate yet).

**Comment by Manishearth** [comment]
We should just insert std in extern-prelude if the crate is not no-std? (and something similar for core)

**Comment by mbrubeck** [comment]
Similarly `core` should work if the crate is `no_std` (unless it is also `no_core`).

CC #44660
