### ISSUE TITLE
extern absolute paths no longer works with new nightly

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#50635]
For example, I believe this used to work on play:

```rust
#![feature(extern_absolute_paths)]
use rayon::join;
fn main() { }
```

The [borrow-check repository](https://github.com/rust-lang-nursery/borrow-check/pull/21) is also hitting this. See for example [this recent travis failure](https://travis-ci.org/rust-lang-nursery/borrow-check/builds/377509266?utm_source=github_status&utm_medium=notification). 

The code in that repository builds with 2018-05-04 nightly, but it won't build now.

cc @petrochenkov 

I'm going to try and bisect with https://github.com/rust-lang-nursery/cargo-bisect-rustc

**Comment by nikomatsakis** [comment]
Ah, @alexcrichton informs me that we must now enable the 2018 edition for this to work.

**Comment by petrochenkov** [comment]
>we must now enable the 2018 edition for this to work.

Is there any document explaining what's going on and how features interact with editions?
Are new unstable features can be enabled and used on both editions, or only 2018, or it depends on specific features?
When unstable features are stabilized, are they stabilized on both editions, or only 2018, or it depends on specific feature?
Obviously and unfortunately some features are breaking, so "both editions" can't always be a correct answer.

**Comment by petrochenkov** [comment]
I'd expect:
- New unstable features can be enabled and used on both editions (e.g. this "must now enable the 2018 edition for this to work" stuff is wrong).
- When unstable features are stabilized they are stabilized on both editions unless they are breaking, then they stabilize only on 2018.

**Comment by alexcrichton** [comment]
@petrochenkov what you'd expect is I believe the current plan. We're in sort of a weird limbo state where we're figuring this out and nothing is stable so it makes for some... interesting bugs.
