### ISSUE TITLE
Turn the overflowing_literals lint from warn to deny for the 2018 edition

### ISSUE THREAD

**Issue by bstrie** [rust-lang/rust#50633]
This code compiles with a warning:
```rust
let x: u8 = 256;  // warning: literal out of range for u8
```
I can think of no use case for allowing overflowing literals. The lint has existed since 2012, back before we had any firm story regarding integer overflow and back when literal underflow was also allowed (in modern Rust, integer literal underflow is a parse error). This is a prime candidate for a lint that advances to deny for the 2018 edition.

**Comment by steveklabnik** [comment]
Changes to lint’s currently require an RFC; this should be pursued over there.

**Comment by bstrie** [comment]
RFC filed: https://github.com/rust-lang/rfcs/pull/2438
