### ISSUE TITLE
Regression in return type error quality with impl trait

### ISSUE THREAD

**Issue by jonathandturner** [rust-lang/rust#50652]
In playing with impl trait this morning, I noticed that if you do the classic "oops, I left a ; after my return value" error, instead of the helpful message asking if you meant to have the semi-colon, you get this:

<img width="650" alt="screen shot 2018-05-11 at 5 20 58 am" src="https://user-images.githubusercontent.com/547158/39924156-96b86d42-54db-11e8-9727-5277334133d5.png">

We should definitely try to cover this case too with the same improved error messages we have for other return types.

**Comment by jonathandturner** [comment]
Test case
```rust
trait Bar {}
impl Bar for bool {}

fn baz() -> impl Bar {
    true;
}

fn main() {
    baz();
}
```

**Comment by larsluthman** [comment]
The same error message appears if your function body consists of 'unimplemented!()' or 'panic!()'. In that case it should probably say something like 'Failed to infer return type' instead.

**Comment by estebank** [comment]
[Current output](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=94b6fa613da5de4c9e25588ea4a9800a):

```
error[E0277]: the trait bound `(): Bar` is not satisfied
 --> src/main.rs:4:13
  |
4 | fn baz() -> impl Bar {
  |             ^^^^^^^^ the trait `Bar` is not implemented for `()`
5 |     true;
  |         - consider removing this semicolon
  |
  = note: the return type of a function must have a statically known size
```

It _does not_ check wether the type actually `impl Bar`.
