### ISSUE TITLE
Compiling ambiguous macro invocation hangs forever

### ISSUE THREAD

**Issue by stevenblenkinsop** [rust-lang/rust#5067]
Trying to compile this code containing an ambiguous macro causes the compiler to hang forever and max out memory:

    macro_rules! make_vec(
    	(a $e1:expr $($(, a $e2:expr)*)*) => ([$e1 $($(, $e2)*)*]);
    )
    
    fn main() {
    	let _ = make_vec!(a 1, a 2, a 3);
    }

rustc 0.5
host: x86_64-apple-darwin

**Comment by mitaa** [comment]
This does not compile anymore (PR #20563)
[playpen](http://is.gd/g3wlXM)

```
<anon>:2:17: 2:36 error: `$e1:expr` is followed by a sequence repetition, which is not allowed for `expr` fragments
<anon>:2     (a $e1:expr $($(, a $e2:expr)*)*) => ([$e1 $($(, $e2)*)*]);
                         ^~~~~~~~~~~~~~~~~~~
```

**Comment by Stebalien** [comment]
triage: still an issue (on nightly).

**Comment by Toby-S** [comment]
Still occurs using this updated code:

```rust
macro_rules! make_vec(
    (a $e1:expr $($(, a $e2:expr)*)*) => ([$e1 $($(, $e2)*)*]);
);

fn main() {
    let _ = make_vec!(a 1, a 2, a 3);
}
```

**Comment by jonas-schievink** [comment]
This code is enough to trigger the bug:

```rust
macro_rules! m {
    ( $()* ) => {}
}

m!();
```

I guess repetitions should check that their innards can not be not empty.

**Comment by dtolnay** [comment]
Still an issue in 1.12.0-nightly using the minimal repro in the previous comment.
