### ISSUE TITLE
Bug: Rust allows redefining an existing variable.

### ISSUE THREAD

**Issue by gilescope** [rust-lang/rust#50677]
I can't honestly call this a feature, no matter how much I squint:

{
    let x = 1;
   <do things with x>
   let x = String::new();
   <do things with different x>
}

Does clippy warn about this? The compiler doesn't even give a warning.

If our goal is a language where we can engineer software that's rock solid then the above really should not be allowed. It's just a footgun waiting to happen. For example in a large function someone accidently redefines x because they didn't realise that name was already in scope.

Please could we consider this a bug for Rust 2018 era, and at least warn now that this was probably not what the developer wanted?

**Comment by sfackler** [comment]
This is not a bug. If you want to propose changing the behavior here, that would need to be an RFC.

**Comment by Arnavion** [comment]
https://rust-lang-nursery.github.io/rust-clippy/v0.0.193/index.html#shadow_unrelated

**Comment by gilescope** [comment]
Perfect!
