### ISSUE TITLE
`Applicability`-ify suggestions

### ISSUE THREAD

**Issue by zackmdavis** [rust-lang/rust#50723]
#50204 introduced an `Applicability` enum that is used to indicate whether a suggestion is suitable for non-interactive application by tools (notably [rustfix](https://github.com/rust-lang-nursery/rustfix/pull/97)), replacing a boolean that was intended for this purpose (#47540, #39254). It looks like [we want to do this everywhere](https://github.com/rust-lang/rust/pull/50476#issuecomment-387114035), but there didn't seem to be an existing issue to track this.

**Comment by estebank** [comment]
I might have since added some span_suggestions since you started this work. We should probably take a week soonish and just plow through all cases in the codebase.

**Comment by zackmdavis** [comment]
> We should probably take a week soonish and just plow through all cases in the codebase.

I'm still hopeful that we can [recruit a reader](https://github.com/cmr/this-week-in-rust/commit/df8e98aed19db6b6db68316e47bc399904ba13e4) of This Week in Rust 246 who's willing to put up with a bit of tedium in exchange for _eternal open-source fame and glory_.

If that's you, dear reader of this comment, here are some mentoring instructions:

 * Use your favorite code-search tool to look through the codebase for calls to `span_suggestion` or `span_suggestion_short`. (I count 79 at time of writing.)

 * For each of these (or at least some of them—this doesn't all have to happen in one pull request):
    * Change the call to [`span_suggestion_with_applicability`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_errors/struct.Diagnostic.html#method.span_suggestion_with_applicability) or `span_suggestion_short_with_applicability` respectively, passing `Applicability::MachineApplicable` as the last argument. (You may need to put a `use::errors::Applicability` import at the top of the file.) That is, unless—
     * Unless you can think of a reason that the suggestion shouldn't be automatically applied by tools such as `cargo fix` or the Rust Language Server. If so, leave a comment and pass `Applicability::MaybeIncorrect`. (Examples: [1](https://github.com/rust-lang/rust/blob/667fdc1ce49aa5be2a11bf565f27f8118bd7c4d3/src/librustc/infer/error_reporting/mod.rs#L1181-L1184) [2](https://github.com/rust-lang/rust/blob/6e63b0dbedd5d4617d95aee1a42b9345b180d27b/src/librustc_lint/builtin.rs#L1253-L1255))

 * Open a pull request including the text "r? @estebank".

 * Bask in your _eternal open-source fame and glory_! :sparkling_heart: :woman_singer:

**Comment by estebank** [comment]
@ekse I believe it is possible, but it is a bad idea because we prefer to keep the diffs as small as possible. Unless you're actively touching the code, style only changes are slightly frowned upon. My personal rule of thumb is that if it's only affecting a few lines it's fine, if it's affecting the entire file it's not. Anything in between is a grey area that will depend on the reviewer. Keep in mind that the more extensive the diffs are, the more likely it is they will have/cause merge conflicts with other PRs.

**Comment by Manishearth** [comment]
Btw, I'm willing to mentor folks in doing this!
