### ISSUE TITLE
Url pointing to invalid methods in documentation of pointer type

### ISSUE THREAD

**Issue by pravic** [rust-lang/rust#50746]
https://doc.rust-lang.org/std/primitive.pointer.html
https://doc.rust-lang.org/nightly/std/primitive.pointer.html

It turns out that the pointer type is implemented twice: for `impl<T> *const T` and `impl<T> *mut T`. However, the index section contains links to the first implementation only, whereas methods from the second implementation have different href anchors:

For example, links from the index:
https://doc.rust-lang.org/nightly/std/primitive.pointer.html#method.is_null
https://doc.rust-lang.org/nightly/std/primitive.pointer.html#method.is_null

And actual anchors:
https://doc.rust-lang.org/nightly/std/primitive.pointer.html#method.is_null
https://doc.rust-lang.org/nightly/std/primitive.pointer.html#method.is_null-1

The same in stable version.

cc @steveklabnik (I don't know the name of the docs team, unfortunately)
cc @GuillaumeGomez probably

Possibly related to #24558.

**Comment by GuillaumeGomez** [comment]
And is it bad?

**Comment by pravic** [comment]
The second `is_null` (and other methods) in index (on the left, below Methods) still points to the first implementation. That's wrong.

**Comment by GuillaumeGomez** [comment]
Oh I see! Yes, it's an issue.
