### ISSUE TITLE
Unused loop (break) name gives no compiler warning

### ISSUE THREAD

**Issue by BartMassey** [rust-lang/rust#50751]
Currently, code like this

```
'unused_name: for i in 0..2 {
    println!("{}", i);
}
```

is silently accepted. As with unused function parameters or variable declarations, this is usually indicative of a mistake. A warning should be issued unless the break name begins with `_`.

Do I need to treat this as a feature request and file an RFC? Please say "no" — the RFC process is heavyweight as hell. I think it's just a bug report :smile:.

**Comment by abonander** [comment]
I can mentor this one, though I'll have to look at how the other unused-* lints work before I can provide instructions. Should be an easy task overall though.

**Comment by abonander** [comment]
### (DRAFT, come back later) Mentoring Instructions

So all the lints that call out unused elements reside in `src/librustc_lint/unused.rs`. We're going to implement another in a very similar vein to [`UnusedImportBraces`](https://github.com/rust-lang/rust/blob/master/src/librustc_lint/unused.rs#L371-L430); early-pass lints are done when no type inference information is necessary, so they're good when you only really need to look at the source tree itself like we're going to do here.

This lint should be pretty easy, we'll start just like with `UnusedImportBraces` and call `declare_lint!` with the lint information:

```rust
declare_lint! {
    UNUSED_LOOP_LABEL,
    Warn,
    "warns on unused labels for loops",
}

#[derive(Copy, Clone)]
pub struct UnusedLoopLabel;

impl LintPass for UnusedLoopLabel {
    fn get_lints(&self) -> LintArray {
        lint_array!(UNUSED_LOOP_LABEL)
    }
}
```

And then we're going to implement `EarlyLintPass`, overriding the `check_expr()` method:

```rust
impl EarlyLintPass for UnusedLoopLabel {
    fn check_expr(&self, ctxt: &mut EarlyContext, expr: &ast::Expr) {
        match expr.kind {
            ast::While(_, ref block, Some(ref label)) |
            ast::WhileLet(_, _, ref block, Some(ref label)) |
            ast::ForLoop(_, _, ref block, Some(ref label)) |
            ast::Loop(ref block, Some(ref label)) => {
                // TODO: iterate `block.stmts`; if a stmt.kind is `ast::StmtKind::Expr(expr)
               //  and that `expr.kind` is `ast::Break` or `ast::Continue`, check if the label matches `label`
               // if so, just return early.
               // Otherwise, if you've gone through all nested loops' statements and haven't found `label`,
               // 
            }
            _ => {}
    }
}
```

You do want to make sure to recurse into nested loops because the major use-case for loop labels is to break or continue an outer loop...

**Comment by abonander** [comment]
@estebank A complicating issue came up. Loop labels don't have their own spans in the AST, so a complete implementation of this lint (for optimal diagnostics) would also add span info to `ast::Label` which would need to touch the parser, and that might be a bit dense for a beginner. I can write the instructions for it but it could be a bit involved.

**Comment by KyleStach1678** [comment]
I'd like to take this issue.

**Comment by BartMassey** [comment]
Speaking just for myself, @KyleStach1678, I'd be happy for you to take this. I was just about to fork and start on it, but honestly I don't really have the time to tackle it right now, so I'm glad to hear I might not have to. :-)

**Comment by BartMassey** [comment]
Thanks huge! That was hilariously fast turnaround. Super-impressive.

**Comment by petrochenkov** [comment]
@BartMassey 
See https://github.com/rust-lang/rust/pull/50763#issuecomment-390171774.
Someone needs to send a PR making the lint warn-by-default and that PR will have to go through some collective approval process from the lang team and possibly crater run.

**Comment by BartMassey** [comment]
Ah, missed that bit, thanks. Who sends that PR?

**Comment by KyleStach1678** [comment]
@BartMassey if no one was planning to, I could open that PR. Not sure if it would be more appropriate for someone on the lang team to open that up instead though?

**Comment by petrochenkov** [comment]
@KyleStach1678 
Please do it, lang team people are mostly busy with their own stuff.

**Comment by BartMassey** [comment]
See Issue #66324 for an attempt to revive the change to have the lint `warn` by default.
