### ISSUE TITLE
Document guarantees around drop and panicing

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#50765]
Currently, when a panic occurs during a regular (i.e., non-unwinding) drop of a local variable, the remaining local variables are still going to have their `drop` called as usual: https://play.rust-lang.org/?gist=1e2b47513bbfebb71cb6d4e05eca822d&version=stable&mode=debug

Furthermore, if a panic occurs during the drop of a struct with members, the member's drop is also still going to be executed: https://play.rust-lang.org/?gist=69c5e0e922f96dbdc939dad6453ecc6c&version=stable&mode=debug

It would be nice to have such guarantees spelled out explicitly somewhere. Given that this is externally visible behavior, it is probably covered by the stability guarantee, but still -- these guarantees will be really important for providing safe stack pinning APIs.

I am not sure what would be a good place for this to be documented, maybe somewhere in https://doc.rust-lang.org/stable/reference/?

Cc @pythonesque

**Comment by petrochenkov** [comment]
IIRC, panics in destructors and double panics were very buggy, so they the precise rules weren't de jure stabilized and were *expected* to change in some ways.
The "language semver" RFC (https://github.com/rust-lang/rfcs/blob/master/text/1122-language-semver.md) even mentions this case specifically.
I don't know what is the status today, perhaps migration to MIR changed something, perhaps not.

**Comment by steveklabnik** [comment]
Yes; this issue should be opened on the reference. Would you mind moving this over there? Thanks! https://github.com/rust-lang-nursery/reference/issues/new

**Comment by RalfJung** [comment]
Done: https://github.com/rust-lang-nursery/reference/issues/348
