### ISSUE TITLE
tidy: Add a check for empty `.stderr` and `.stdout` files in UI test directories

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rust#50785]
Tidy check in https://github.com/rust-lang/rust/blob/master/src/tools/tidy/src/ui_tests.rs makes sure that we don't have stray `testname.stderr`/`testname.stdout` files without a corresponding `testname.rs`.

It would be useful to add one more check into the same file making sure that `testname.stderr`/`testname.stdout` files are not empty.
Such empty files can still pass testing for `compile-pass` tests with no output so they can get into the repo accidentally, but they are not necessary and can be removed.

**Comment by jrlusby** [comment]
I'd like to take this issue.
