### ISSUE TITLE
`fn(u64) -> u64` can be cast as `i64`, resulting in gibberish

### ISSUE THREAD

**Issue by jonathanstrong** [rust-lang/rust#50796]
minimal example: 
```rust
fn f(x: u64) -> u64 { x * 2 }

fn main() {
    let g = f as i64;
    println!("{}", g); // 94295280847184
}
```
[playground](https://play.rust-lang.org/?gist=5278af2507d0536182c7104481e962c7&version=stable&mode=debug)

Ordinarily rust is very strict about casts so I was surprised by this behavior when, because of a typo, I was trying to cast a `fn` as an `i64`. It compiled fine and resulted in garbage numbers that were difficult to track down. I assume this is a bug and not intended behavior.

First encountered the problem on nightly 1.27 2018-05-13 but it is also present in stable 1.26, per the playground example.

**Comment by sfackler** [comment]
The number is the address of the function.

**Comment by jonathanstrong** [comment]
ah. well here is one voice urging to discontinue this shortcut as it is quite a footgun by rust standards.

**Comment by josephlr** [comment]
You're running into one of the [type casts](https://doc.rust-lang.org/reference/expressions/operator-expr.html#type-cast-expressions) that isn't a [coercion](https://doc.rust-lang.org/reference/type-coercions.html).

These exist so pointers (and function pointers) can be converted into `usize` values (for similar use cases to `uintptr_t` in C/C++). The weird thing is that rust allows for casting from pointers to integer types that are not `usize` (like `u8`). It's hard to think of a reasonable use case for turning a pointer into a byte. See [this example](https://play.rust-lang.org/?gist=7fccf5ad53b154938b41b7f645e3f4af) for what I'm talking about.

Regardless, changing this behavior is non backwards-compatible. So the documentation on casts/coercions might need to be updated (it's not in the book's second edition). I also guess restricting what `as` does could be done at an epoch change, but that's a rather significant change.

**Comment by ishitatsuyuki** [comment]
So, what we could do is to issue a warning for casts like this.

The most verbose way would be `f as *const fn(u64) -> u64 as usize as i64`, although I'm not sure what parts should be omitted from this cast.

**Comment by oli-obk** [comment]
There's an open issue in clippy for this issue: https://github.com/rust-lang-nursery/rust-clippy/issues/2588

**Comment by ollie27** [comment]
> The most verbose way would be `f as *const fn(u64) -> u64 as usize as i64`

I hope you meant `f as fn(u64) -> u64 as usize as i64`. Unfortunately `f as *const fn(u64) -> u64` does compile but it's yet another nonsense cast from `fn(u64) -> u64` to `*const fn(u64) -> u64` that we should really lint against.

**Comment by jonathanstrong** [comment]
in the meantime, I saw a post a few weeks ago about custom lints. For those who have some familiarity with this, how difficult would it be (for a knowledgeable rust dev, just no experience writing plugins) to write a plugin that prohibits this specific cast? It never occurred to me this could happen and I'm concerned there could be other places where it did.
