### ISSUE TITLE
rustc: trait-level where clauses are mistakenly imposed when bounding by the trait

### ISSUE THREAD

**Issue by aturon** [rust-lang/rust#50792]
I'm trying to use a `where` clause to define one trait in terms of another, as applied to a wrapper type:

```rust
struct Wrapper<T>(T);

trait Base {}
trait Wrapped: Sized where Wrapper<Self>: Base {}

fn wat<F: Wrapped>() {}
```

But when I try to bound by the new trait, I get a strange error:

```
error[E0277]: the trait bound `Wrapper<F>: Base` is not satisfied
 --> src/main.rs:7:1
  |
7 | fn wat<F: Wrapped>() {}
  | ^^^^^^^^^^^^^^^^^^^^^^^ the trait `Base` is not implemented for `Wrapper<F>`
  |
note: required by `Wrapped`
 --> src/main.rs:5:1
  |
5 | trait Wrapped: Sized where Wrapper<Self>: Base {}
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by aturon** [comment]
cc @nikomatsakis @eddyb @cramertj

**Comment by aturon** [comment]
Note: affects 1.26 and the current nightly.

**Comment by leodasvacas** [comment]
You can get it to work by repeating the where clause:
```rust
struct Wrapper<T>(T);

trait Base {}
trait Wrapped: Sized where Wrapper<Self>: Base {}

fn wat<F: Wrapped>() where Wrapper<F>: Base {}

fn main() {}
```

I think what is desired here is the implied bounds feature.

**Comment by cuviper** [comment]
This seems similar to #20671, though from a slightly different angle.

Rust 1.3 has no complaint with the example.  Rust 1.4 starts E0277 as a warning that "will become a HARD ERROR in the next release. See RFC 1214 for details."  Rust 1.7 is where it actually became an error.

**Comment by jonas-schievink** [comment]
Closing in favor of #20671 / #44491
