### ISSUE TITLE
impl Trait causes "borrowed value does not live long enough"

### ISSUE THREAD

**Issue by cuviper** [rust-lang/rust#50823]
This code:

```rust
fn main() {
    println!("{:?}", max());
}

fn max() -> Option<i32> {
    let v = vec![1, 2, 3];
    iter(&v).max()
}

fn iter(a: &[i32]) -> impl Iterator<Item = i32> + '_ {
    a.iter().cloned()
}
```

gives this error:

```
error[E0597]: `v` does not live long enough
 --> src/main.rs:7:11
  |
7 |     iter(&v).max()
  |           ^ borrowed value does not live long enough
8 | }
  | - `v` dropped here while still borrowed
  |
  = note: values in a scope are dropped in the opposite order they are created
```

But if I change the return type to an explicit `std::iter::Cloned<std::slice::Iter<'_, i32>>`, then it's fine.  It's also fine if I bind that result before returning it, like: `let m = iter(&v).max(); m`

And it works with `#![feature(nll)]`, so maybe I just have to hope for that to stabilize soon... 🙏

**Comment by pnkfelix** [comment]
BTW NLL is turned on as part of the 2018 edition, so if you upgrade to that, this example will start working: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018

**Comment by pnkfelix** [comment]
NLL (migrate mode) is enabled in all editions as of PR #59114. Verified that test case compiled in Nightly 2015 edition; closing as fixed.
