### ISSUE TITLE
Rust doesn't know type is sized

### ISSUE THREAD

**Issue by joshlf** [rust-lang/rust#50824]
`rustc` is telling me that `T` needs to be `Sized` when it is clearly already `Sized`. This code:

```rust
#![feature(const_fn)]

const fn size_of<T: Sized>() -> (usize, T) where T: Sized {
    (::std::mem::size_of::<T>(), ::std::mem::transmute([0u8; ::std::mem::size_of::<T>()]))
}
```
([playground link](http://play.rust-lang.org/?gist=ab6a0326dcb88a53e03e5bbc35974b6f&version=nightly&mode=debug))

Produces this error:

```text
error[E0277]: the trait bound `T: std::marker::Sized` is not satisfied
 --> src/main.rs:4:62
  |
4 |     (::std::mem::size_of::<T>(), ::std::mem::transmute([0u8; ::std::mem::size_of::<T>()]))
  |                                                              ^^^^^^^^^^^^^^^^^^^^^^^^ `T` does not have a constant size known at compile-time
  |
  = help: the trait `std::marker::Sized` is not implemented for `T`
  = help: consider adding a `where T: std::marker::Sized` bound
  = note: required by `std::mem::size_of`
```

Obviously `T: Sized` and `where T: Sized` are redundant, but I did it to demonstrate that neither is sufficient. The same error appears if only one of the bounds is used, or if neither are used.

**Comment by rkruppe** [comment]
This is a known and expected bug but I can never find the canonical issue for it. Maybe #50308 or #43408

**Comment by bgeron** [comment]
The error seems to appear when Rust is forced to compute with values inside types. Further minimised example: ([play](http://play.rust-lang.org/?gist=355853def6986a82d4fb5c18a94c7c2f&version=stable&mode=debug))

```
fn size_of<T>() -> T where T: Sized {
    let v : [u8; ::std::mem::size_of::<T>()] = unimplemented!();
    v
}
```

**Comment by bgeron** [comment]
The error message given for this is:

```
   Compiling playground v0.0.1 (file:///playground)
error[E0277]: the trait bound `T: std::marker::Sized` is not satisfied
 --> src/lib.rs:4:18
  |
4 |     let v : [u8; ::std::mem::size_of::<T>()] = unimplemented!();
  |                  ^^^^^^^^^^^^^^^^^^^^^^^^ `T` does not have a constant size known at compile-time
  |
  = help: the trait `std::marker::Sized` is not implemented for `T`
  = help: consider adding a `where T: std::marker::Sized` bound
  = note: required by `std::mem::size_of`

warning: unreachable expression
 --> src/lib.rs:5:5
  |
5 |     v
  |     ^
  |
  = note: #[warn(unreachable_code)] on by default
```

There is no error about `v` being of the wrong type. Presumably, this is because Rust hasn't yet gotten to the stage where it can compare types for equality.

**Comment by xfix** [comment]
As a workaround, you can do this instead:

```rust
use std::mem;

unsafe fn example<T>() -> (usize, T) {
    (mem::size_of::<T>(), mem::zeroed())
}
```

Still a bug, don't get me wrong.

**Comment by oli-obk** [comment]
This is just another symptom of https://github.com/rust-lang/rust/issues/43408 I believe
