### ISSUE TITLE
core::slice::SliceExt removed in 1.27 beta

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#50834]
The `core::slice::SliceExt` trait was removed from the libcore public API in 1.27 beta, but it contained some stable methods in it, and it was possible to call them on stable. Its removal is breaking some crates.

[Playground example](https://play.rust-lang.org/?gist=293f7ba1202e68b1b77ecd9016633a2a&version=beta&mode=debug)

* [snes-bitplanes](https://crates.io/crates/snes-bitplanes) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.27-1/beta-2018-05-10/reg/snes-bitplanes-0.2.1/log.txt)) cc @TooManyBees

The cause is probably https://github.com/rust-lang/rust/pull/49896, cc @SimonSapin @alexcrichton

**Comment by kennytm** [comment]
This is [expected](https://github.com/rust-lang/rust/pull/49896#issuecomment-383315871): TooManyBees/super-metroid#1

**Comment by SimonSapin** [comment]
As @kennytm said this particular build failure did come up in a pre-landing Crater run but was the only one that seemed "legit", and I submitted PR to make the code compile both before and after the change.

**Comment by pietroalbini** [comment]
Sure. Marking this as "won't fix" then.
