### ISSUE TITLE
Crates using placement syntax behind a cfg broken

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#50832]
Some crates were using `<-` behind a feature flag, so they worked on stable even if the placement syntax was nightly-only. After removing it though they fail to compile even on stable with a syntax error, because `<-` is not recognized anymore.

* [mbox](https://crates.io/crates/mbox) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.27-1/beta-2018-05-10/reg/mbox-0.4.3/log.txt)) cc @kennytm
* [rayon-hash](https://crates.io/crates/rayon-hash) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.27-1/beta-2018-05-10/reg/rayon-hash-0.2.0/log.txt)) cc @cuviper

**Comment by nikomatsakis** [comment]
Oh, that's annoying. We should patch rayon-hash.

**Comment by nikomatsakis** [comment]
Some discussion of the final at or around here in the IRC logs

https://botbot.me/mozilla/rustc/2018-05-17/?msg=100165163&page=3

**Comment by nikomatsakis** [comment]
triage: P-high

**Comment by nikomatsakis** [comment]
Would anyone have time to whip up a change to the parser?

cc @rust-lang/compiler @aidanhs

**Comment by cuviper** [comment]
I am working on rayon-hash.  The quick hack would be to just nuke the placement stuff, but I'm trying to do a proper update to catch up to `std`'s code -- fun with `git subtree`.

But frankly, I don't know of anyone really using rayon-hash anyway.

**Comment by cuviper** [comment]
Fixed in rayon-hash 0.3.0.

**Comment by nikomatsakis** [comment]
I'll handle this.

**Comment by nikomatsakis** [comment]
Restored in #51052

**Comment by leodasvacas** [comment]
We could try calling more attention to lib authors about this through the [API guidelines](https://github.com/rust-lang-nursery/api-guidelines/issues/156).

**Comment by estebank** [comment]
The two regressions where about `<-`, but we also reverted the `in` syntax as well, which has degraded back a couple of errors, like the following:

```
fn main() {
    let i = ();
    for x in in 0..1 {}
    i;
}
```

Would it be ok to create a PR removing the `in` parsing while keeping the current `<-` handling for a while longer?
