### ISSUE TITLE
Cargo is now compiling examples when executing cargo test

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#50833]
**This is probably not going to be reverted, this issue is used to notify crate authors about this.**

In Rust 1.27 cargo will start compiling examples when executing `cargo test`. You (the crates authors) should fix the examples if you want `cargo test` to continue working.

* [mqtt](https://crates.io/crates/mqtt) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.27-1/beta-2018-05-10/reg/mqtt-0.1.4/log.txt)) cc @flier
* [uom](https://crates.io/crates/uom) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.27-1/beta-2018-05-10/reg/uom-0.14.0/log.txt)) cc @iliekturtles

**Comment by alexcrichton** [comment]
cc @ehuss (just FYI)

**Comment by pietroalbini** [comment]
> The error shown in the log is fixed in v0.16.0 and the latest release is v0.18.0. Can future cargobomb runs be updated to use the latest version?

@iliekturtles Crater (cargobomb was the old name) tests multiple versions of some crates, but always the latest one. In the `uom` case, 0.17.0 was the latest when the crater run started (one takes about 5 days to complete), and [it passed](https://cargobomb-reports.s3.amazonaws.com/beta-1.27-1/beta-2018-05-10/reg/uom-0.17). You don't need to worry about that `;)`

**Comment by alexcrichton** [comment]
@ehuss I think given that there's only one regression here and there's no transitive impact I think it's safe to leave as-is.

**Comment by pietroalbini** [comment]
Closing as won't fix.
