### ISSUE TITLE
Rustup doesn't recognize my Microsoft C++ build tools

### ISSUE THREAD

**Issue by nebrelbug** [rust-lang/rust#50857]
I'm a beginner who's just barely started learning Rust online, and I want to now use Rust on my computer. I installed the Rust installer, ran it, and it output this message:
```
Rust requires the Microsoft C++ build tools for Visual Studio 2013 or later, but they don't seem to be installed.
```
I installed the Microsoft C++ 2017 build tools and restarted my computer, but it still outputs this error. I understand that a lot of people have this issue, but I can't find a solution.

How can I set Rust up so it works? (I'm a beginner)

**Comment by retep998** [comment]
Did you remember to make sure when installing the VC++ build tools that you enabled the Windows SDK option?

**Comment by steveklabnik** [comment]
That's not the right thing, you want what's linked to, right above it, "Build Tools for Visual Studio 2017"

**Comment by nebrelbug** [comment]
Oops! Solved the problem. Maybe the documentation could be updated to be a little more clear?

Thanks!

**Comment by nebrelbug** [comment]
One more question: in install, Rustup is stuck on a screen that says:
```info: installing component 'rustc'
info: installing component 'rust-std'
info: installing component 'cargo'
info: installing component 'rust-docs'
```
Should I cancel...?

**Comment by nebrelbug** [comment]
Never mind, it finished literally 5 seconds after I submitted the issue. Thanks again!
