### ISSUE TITLE
ICE with impl trait on stable and nightly

### ISSUE THREAD

**Issue by MaikKlein** [rust-lang/rust#50888]
I have recently encountered an ICE in my project, where I just updated to the newest master (rustc). You can find some notes on my [issue tracker](https://github.com/MaikKlein/rlsl/issues/38).
```
use std::marker::PhantomData;

pub struct Input<'tcx> {
    _m: PhantomData<&'tcx ()>
}
pub struct Test<'a, 'tcx: 'a>{
    _m: &'a PhantomData<&'tcx ()>
}

impl<'a, 'tcx> Test<'a, 'tcx> {
    pub fn new() -> Self {
        unimplemented!()
    }
    pub fn test(&self) -> impl Iterator<Item = Input<'tcx>> + 'a {
        (0..1).map(|_| unimplemented!())
    }
}

fn main() {
    let tests = vec![Test::new()];
    let _: Vec<_> = tests.iter().flat_map(Test::test).collect();
}
```

[playground](https://play.rust-lang.org/?gist=a6d3392ea7bd588599ffb91edc4a2111&version=stable&mode=debug)

I am sure you can reduce it even more. The bug can't be older than 4 months (I think).

Edit:

I forgot to add that this fixes the ICE.

`let _: Vec<_> = tests.iter().flat_map(|test| Test::test(test)).collect();`

**Comment by MaikKlein** [comment]
Seems to be a duplicate of https://github.com/rust-lang/rust/issues/50881

**Comment by pietroalbini** [comment]
Closing as a duplicate.
