### ISSUE TITLE
Wrong bytepos_to_file_charpos?

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rust#50895]
Function:  `std::heap::Layout::from_size_align_unchecked`

Span debug format:

```
/home/bjorn/.rustup/toolchains/nightly-2018-05-17-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore/alloc.rs:134:24: 134:28
```

![priroda_wrong_span_position_screenshot](https://user-images.githubusercontent.com/17426603/40270891-587fe904-5b95-11e8-8365-665df7f3fad1.png)

The marked position is off by two bytes. Stepping to `_4 = _2` and the few instructions after it has the same two byte error.

Note: the code for the source rendering is at https://github.com/bjorn3/priroda/blob/f93aecc6d2294c709535e241501824a415e19ae0/src/render/source.rs This is the only case I found where this is incorrect.

**Comment by Mark-Simulacrum** [comment]
I'm going to close this as it's not really actionable as-is, if we could get a smaller test case then we can reopen.
