### ISSUE TITLE
inconsistent lint flag args between normal and post-rustfix compiles in UI tests

### ISSUE THREAD

**Issue by zackmdavis** [rust-lang/rust#50926]
UI tests [run with`-A unused`](https://github.com/rust-lang/rust/blob/2dca249da08e059adf083171414a24d2c039b8cb/src/tools/compiletest/src/runtest.rs#L1314-L1322), but UI tests with the `run-rustfix` directive go on to apply suggestions and then [check that there are no warnings, without passing any lint flags](https://github.com/rust-lang/rust/blob/2dca249da08e059adf083171414a24d2c039b8cb/src/tools/compiletest/src/runtest.rs#L2644-L2646). The inconsistency is a papercut–footgun for UI test authors. We should do exactly one of—

 * Pass `-A unused` for the rustfix-succeeded check, too; or
 * Stop passing `-A unused` for UI tests.
    * The present author gave an argument for this in #43896, but the reception seemed unfavorable (one :-1: react and one negatively-disposed comment). If it turned out that there was support for this after all, we would want someone to edit existing tests to not produce spurious `unused` warnings, which would be a _very_ large PR.

**Comment by Mark-Simulacrum** [comment]
It does seem like passing -A unused to rustfix would be a good change to make here, and at a cursory look at the code it seems like we do that today? But if I'm wrong then we can, of course, reopen.
