### ISSUE TITLE
Some safe methods in hash/table.rs are not.

### ISSUE THREAD

**Issue by pythonesque** [rust-lang/rust#50936]
This was pointed out on Twitter as an example of the standard library violating the requirement that unsafe code cannot rely on safe code preserving invariants past the module boundary, instead relying on debug assertions that are turned off in production builds: https://twitter.com/jix_/status/998339990923939840.

> For example creating a RawTable with capacity 0 (https://github.com/rust-lang/rust/blob/master/src/libstd/collections/hash/table.rs#L809) and then calling https://github.com/rust-lang/rust/blob/master/src/libstd/collections/hash/table.rs#L344 with an arbitrary offset, which will be dereferenced by https://github.com/rust-lang/rust/blob/master/src/libstd/collections/hash/table.rs#L401. The module calls itself "safe-ish" and is not public.

Besides this being wrong, and bad pedagogy (people will assume that if the standard library does it it's okay), the invariant that capacity can't be zero before these are called also seems fairly subtle and not implied by the name of the function.  So it seems to me that making one or more of the methods here unsafe would be a good idea (possibly that of creating a new bucket?).  If it's a very common function in modules that use the raw table, it can always be pulled out into a local unsafe function per module.  Or, if for some reason this actually *is* safe, there should at least be documentation explaining why.

**Comment by Mark-Simulacrum** [comment]
Closing -- I agree with the reasoning laid out here but this should be refiled on hashbrown if it's an issue there.
