### ISSUE TITLE
Add `.cloned()` method to `Result`?

### ISSUE THREAD

**Issue by novacrazy** [rust-lang/rust#50951]
It caught me off-guard that there isn't a `.cloned()` method for `Result<&T, E>`, yet there is one for `Option<&T>`.

I don't think this is a big enough feature to have a whole RFC for, even though I can do that if necessary, but it would be nice to have a `.cloned()` method like this:

```rust
impl<'a, T, E> Result<&'a T, E>
where
    T: Clone,
{
    #[inline]
    pub fn cloned(self) -> Result<T, E> {
        self.map(Clone::clone)
    }
}
```
and the equivalent mutable reference version.

However, if there is a reason why this is not already in place, I can understand. It simply feels a little awkward having to manually map `Clone::clone` in otherwise idiomatic code.

**Comment by scottmcm** [comment]
A bunch of questions from https://github.com/rust-lang/rust/pull/50267 come up here too, like should `cloned()` clone both T and E, or should there be `cloned_ok()` and `cloned_err()`?

And, in general, if figuring out these answers better than just `.map(Clone::clone)` :rofl:

**Comment by novacrazy** [comment]
I think it would make sense to follow the pattern of `.map` and `.map_err` by having `.cloned()` and `.cloned_err()`, as they would just call `.map` and `.map_err` internally. 

I've seen a few times where functions return references in a `Result`, but I've never seen a `Result` with a reference in the `Err` value. The likelihood of having *both* the `Ok` and `Err` values be references is probably pretty small.

**Comment by novacrazy** [comment]
Added in #63166
