### ISSUE TITLE
Derived traits do not need to depend on phantom type parameters.

### ISSUE THREAD

**Issue by AGausmann** [rust-lang/rust#50980]
Let's say I have the following struct definition:

    #[derive(Debug, Copy, Clone, PartialEq, Eq, Hash)]
    struct Object<T> {
        x: i32,
        _t: PhantomData<T>,
    }

According to the book, the `derive`d implementations of `Debug` etc., all of which can be broken down recursively, would simply check that the members `x` and `_t` implement the respective trait. What I'm seeing is if I provide a type to the "phantom" type parameter `T` which does not implement one of these traits, then `Object<T>` will not be derived an implementation of that trait, though the `PhantomData` type, as a zero-sized and effectively a "dummy" type, implements all of these traits without dependency on its type parameter.

For example: Create an instance of `Object<i32>`. `T=i32` which implements `Copy`, so you can therefore `Copy` the parent object. In contrast, try `Object<String>`. `String` does not implement `Copy`, and this causes `Object<String>` to not receive a `Copy` implementation although it most certainly can.

EDIT: Playground examples - [`Object<i32>` implements `PartialEq`](http://play.rust-lang.org/?gist=435fc900a60bc00117bc2d584a0e562a&version=stable&mode=debug), but [`Object<std::io::Stdin>` does not.](http://play.rust-lang.org/?gist=ce87ca7b818e9ac24bd4af1ec8a1c6e0&version=stable&mode=debug)

My local `rustc` version:
```
rustc 1.22.1 (05e2e1c41 2017-11-22)
binary: rustc
commit-hash: 05e2e1c41414e8fc73d0f267ea8dab1a3eeeaa99
commit-date: 2017-11-22
host: x86_64-unknown-linux-gnu
release: 1.22.1
LLVM version: 4.0
```

**Comment by vitalyd** [comment]
See https://github.com/rust-lang/rust/issues/26925

**Comment by AGausmann** [comment]
Thanks.
