### ISSUE TITLE
Confusing about documentation of std::io::Read::read_exact()

### ISSUE THREAD

**Issue by hkcorac** [rust-lang/rust#50991]
Hello,

This is documentation: <https://doc.rust-lang.org/std/io/trait.Read.html#method.read_exact>

It says that:

> No guarantees are provided about the contents of `buf` when this function is called, implementations cannot rely on any property of the contents of `buf` being true. It is recommended that implementations only write data to `buf` instead of reading its contents.

May I ask why the function exists at all, when -- as far as I understand -- both of these are not guaranteed?

- Reading is not guaranteed.
- The returning value `Ok()` is not guaranteed (as I understand from above paragraph).

If I misunderstood something, would you please point out and consider fixing/updating the documentation?

Thank you,

**Comment by hellow554** [comment]
There are two parts in the documentation. First the caller part:

> Read the exact number of bytes required to fill buf.
> This function reads as many bytes as necessary to completely fill the specified buffer buf.

This is for somebody who calls this function.

The next part you are having trouble with is:

> No guarantees are provided about the contents of buf when this function is called, implementations cannot rely on any property of the contents of buf being true. It is recommended that implementations only write data to buf instead of reading its contents.

This is for somebody who implements `Read` trait for it's own structure and tells you, that you shall not read any data out of the buffer, but only fill the buffer.
Is that clear to you?

**Comment by hkcorac** [comment]
@hellow554,

Thank you very much. I coudln't see that point of view. Now it's totally clear.

And sorry...
