### ISSUE TITLE
Lint for adding `crate::` misses a renamed extern crate:

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#50996]
The following code:

```rust
#![warn(rust_2018_compatibility)]
#![allow(dead_code, unused_imports)]
#![feature(rust_2018_preview)]

extern crate libc as foo;

use foo::getpid;

fn main() {}
```

generates no warnings, but when compiling with `--edition 2018` it will yield an error about no crate `foo`

**Comment by Mark-Simulacrum** [comment]
Is this something we expect `rustfix` to work with? It would have to move the rename into Cargo.toml, right? I don't know if we expect it to make changes there.

**Comment by alexcrichton** [comment]
In the sense that this prevents entering the 2018 edition I think we'll want rustfix to handle this yeah. Although the *ideal* solution here is to add the rename to `Cargo.toml` using `use crate::foo::getpid` will also work in this situation. Editing `Cargo.toml` I think is definitely outside of rustfix's scope, though

**Comment by nikomatsakis** [comment]
Got a fix
