### ISSUE TITLE
kill rustc::cfg consumers

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#51002]
In general, `rustc::cfg` should be considered deprecated, and we ought to work to remove its consumers and rewrite them to operate on MIR:

- [x] `UnconditionalRecursion` lint
- [x] AST-based borrowck (that's what NLL is doing, of course)
- [ ] `librustc_driver::pretty::print_flowgraph()`

**Comment by phungleson** [comment]
Hey @nikomatsakis looks like some thing I can help with as `rustc::cfg` is relatively small.

Do you have any other suggestions for me to look further?

**Comment by rkruppe** [comment]
This is done now: https://github.com/rust-lang/rust/pull/64231 moved rustc::cfg into `rustc_ast_borrowck` which was then deleted wholesale in https://github.com/rust-lang/rust/pull/64790.
