### ISSUE TITLE
`augmented-assignments` test output has poor spans in NLL

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#51000]
The `augmented-assignments` test output looks bad when run in NLL:

https://github.com/rust-lang/rust/blob/1962a70e71e82516a4436e00933654a990203c9e/src/test/ui/augmented-assignments.nll.stderr#L1-L26

compared to the original:

https://github.com/rust-lang/rust/blob/1962a70e71e82516a4436e00933654a990203c9e/src/test/ui/augmented-assignments.stderr#L1-L24

There are two problems, but this issue is focused on the span for the “borrow later used here” message. Currently, we select the entire `x += x` which spans multiple lines; unclear that the original selection is so great either. Maybe the `+=` would be ideal.

**Comment by nikomatsakis** [comment]
The way I would set about fixing this is as follows:

- First, read into the code to figure out where the current span comes from (it is coming from some MIR statement).
- Trace back where that MIR statement gets generated and see if we can improve the span.

That said, *most likely* this has to do with the place that we generate `+=` statements when building MIR:

https://github.com/rust-lang/rust/blob/1962a70e71e82516a4436e00933654a990203c9e/src/librustc_mir/build/expr/stmt.rs#L56-L80

This in turn seems to use `expr_span` from the HAIR:

https://github.com/rust-lang/rust/blob/1962a70e71e82516a4436e00933654a990203c9e/src/librustc_mir/build/expr/stmt.rs#L75-L76

which in turn is ultimately derived from the HIR:

https://github.com/rust-lang/rust/blob/1962a70e71e82516a4436e00933654a990203c9e/src/librustc_mir/hair/cx/expr.rs#L304-L314

So I expect what we have to do is to modify the expression. I'm not sure that we even have the span of the operator available. 

(Cc @estebank here — did we ever make progress on that?)

Another option is to try and match what the existing borrowck is doing. We could probably do that by changing the `expr_span` here to be the span of the LHS:

https://github.com/rust-lang/rust/blob/1962a70e71e82516a4436e00933654a990203c9e/src/librustc_mir/build/expr/stmt.rs#L75

**Comment by estebank** [comment]
> So I expect what we have to do is to modify the expression. I'm not sure that we even have the span of the operator available.
>
> ([...] did we ever make progress on that?)

I don't believe we have. That being said, you can use the span for `lhs` and `rhs` instead for this case. Even better, I would love to see this case handled more gracefully, directly referencing why the `+=` operation can't be performed.

Something along the lines of

```
error[E0XXX]: cannot add-assign `x` to itself because `Int` doesn't implement `Copy`
  --> $DIR/augmented-assignments.rs:26:5
   |
LL |     x 
   |     ^ cannot add-assign here...
LL |     +=
   |     -- add-assign borrows the assign target as mutable # This span is not available now
LL |     x;
   |     - ...because `x` is borrowed here
   = note: you cannot add-assign using the same binding on both side of the operation unless the type implements `Copy`
```

**Comment by nikomatsakis** [comment]
I'm going to mark this as deferred. The only reason the output is so bad is because the test is artifically written.

**Comment by gaurikholkar** [comment]
Hi @nikomatsakis , what's the status of the issue?

**Comment by pnkfelix** [comment]
NLL premeeting triage.  I think the pattern
```rust
LHS
+=
RHS;
```
 is quite  rare. Therefore I think the presentation of the bug in the description is inflating the severity of the problem. Marking P-low.

Orthogonally: @matthewjasper are you still working on this? Or should I unassign?
