### ISSUE TITLE
NLL highlights variable declaration, not its use

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#51012]
As reported in [the NLL error master doc](https://paper.dropbox.com/doc/NLL-stderr-diagnostic-deviations-KzroSvNgQ7lip3WQyiLTa), the errors for the `lifetime-errors/ex2c-push-inference-variable.rs` test significantly degrade in NLL:

https://github.com/rust-lang/rust/blob/27649b70327efd0613c8de01ff0b78205473a253/src/test/ui/lifetime-errors/ex2c-push-inference-variable.nll.stderr#L1-L17

compared to the original:

https://github.com/rust-lang/rust/blob/27649b70327efd0613c8de01ff0b78205473a253/src/test/ui/lifetime-errors/ex2c-push-inference-variable.stderr#L1-L12

I'm not sure the best fix here, but the pattern repeats in many other tests. The most relevant code is probably this function:

https://github.com/rust-lang/rust/blob/27649b70327efd0613c8de01ff0b78205473a253/src/librustc_mir/borrow_check/nll/region_infer/mod.rs#L1061-L1063

which is used to try and pick the "blame" spot. In this case, it's not doing a great job, though not *terrible*. 

---

NB. you can ignore this warning, that is just issued when errors from the AST-based region checker are suppressed:

https://github.com/rust-lang/rust/blob/27649b70327efd0613c8de01ff0b78205473a253/src/test/ui/lifetime-errors/ex2c-push-inference-variable.nll.stderr#L1

**Comment by nikomatsakis** [comment]
How I would start:

- create a graphviz view of the outlives constraints (actually we already dump that with `-Zdump-mir=nll` I believe, look for a `.dot` file)
- try to understand how `blame_span` works and see if there is a better constraint it could be picking
- we might want to supply hints when creating outlives relations 
  - for example, I think we should favor outlives constraints that are created when we type check `a = b` (where we take the type from `b` and compare it to the type of `a`)

**Comment by gaurikholkar** [comment]
I'll have a look at this

**Comment by nikomatsakis** [comment]
Marking for RC: relatively minor diagnostic nit, I think.

**Comment by nikomatsakis** [comment]
This wound up getting largely fixed as part of some other PRs. 

Current output for the test in question:

https://github.com/rust-lang/rust/blob/b2397437530eecef72a1524a7e0a4b42034fa360/src/test/ui/lifetime-errors/ex2c-push-inference-variable.nll.stderr#L7-L16
