### ISSUE TITLE
asm! with u128 fails to compile - invalid memory reference

### ISSUE THREAD

**Issue by Ragnaroek** [rust-lang/rust#51018]
Using the now stable u128 in an asm! macro crashes the compiler.

Code to reproduce:
https://gist.github.com/rust-play/954f1ccc1cd8004df576a43b6514b401

Reproducable on the playground and macOS. On macOS the error message is:

> 
> error: Could not compile `mithril`.
> 
> Caused by:
>   process didn't exit successfully: `rustc --crate-name mithril src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=e7b8648dc96b2094 -C extra-filename=-e7b8648dc96b2094 --out-dir /Users/mb/pprojects/mithril/target/debug/deps -C incremental=/Users/mb/pprojects/mithril/target/debug/incremental -L dependency=/Users/mb/pprojects/mithril/target/debug/deps --extern env_logger=/Users/mb/pprojects/mithril/target/debug/deps/libenv_logger-f4f513ab1223272f.rlib --extern bandit=/Users/mb/pprojects/mithril/target/debug/deps/libbandit-4c1e67613f3f77ac.rlib --extern serde_derive=/Users/mb/pprojects/mithril/target/debug/deps/libserde_derive-be3fca48459907f5.dylib --extern serde_json=/Users/mb/pprojects/mithril/target/debug/deps/libserde_json-711c5ee6a421b953.rlib --extern jhffi=/Users/mb/pprojects/mithril/target/debug/deps/libjhffi-9ed97b90d2952145.rlib --extern config=/Users/mb/pprojects/mithril/target/debug/deps/libconfig-e2e5d7589e9b7f20.rlib --extern blake=/Users/mb/pprojects/mithril/target/debug/deps/libblake-72647039190c341c.rlib --extern skeinffi=/Users/mb/pprojects/mithril/target/debug/deps/libskeinffi-376e1906e19563be.rlib --extern byteorder=/Users/mb/pprojects/mithril/target/debug/deps/libbyteorder-49761a93f2c8b743.rlib --extern tiny_keccak=/Users/mb/pprojects/mithril/target/debug/deps/libtiny_keccak-e51e268bdb8727cc.rlib --extern groestl=/Users/mb/pprojects/mithril/target/debug/deps/libgroestl-6dfc9492e11b0fc4.rlib --extern serde=/Users/mb/pprojects/mithril/target/debug/deps/libserde-4c061d99045b66f7.rlib --extern num_cpus=/Users/mb/pprojects/mithril/target/debug/deps/libnum_cpus-a0f20e1acd1dc757.rlib --extern log=/Users/mb/pprojects/mithril/target/debug/deps/liblog-b7873a215694991b.rlib -L native=/Users/mb/pprojects/mithril/target/debug/build/blake-0629bde5aab754f8/out -L native=/Users/mb/pprojects/mithril/target/debug/build/jh-ffi-a8d639c8dd0be45a/out -L native=/Users/mb/pprojects/mithril/target/debug/build/skein-ffi-c29e2293896d09bc/out` (signal: 11, SIGSEGV: invalid memory reference) 

> rustc --version
> rustc 1.27.0-nightly (2f2a11dfc 2018-05-16)

**Comment by Ragnaroek** [comment]
anything new on this one?

**Comment by Amanieu** [comment]
Try transmuting to [`__m128`](https://doc.rust-lang.org/nightly/core/arch/x86/struct.__m128.html) first.

Generally the problem here is that we don't do any type checking for inline asm, but this is a known problem.

**Comment by levex** [comment]
I am unable to reproduce this on a Linux box: https://gist.github.com/levex/c9f77d7721463ddb26e229ef512037a2

Does this still reproduce on macOS?

**Comment by rossmacarthur** [comment]
I am unable to reproduce on macOS, and get the same error @levex does.

**Comment by Amanieu** [comment]
This issue does not apply to the new `asm!` ([RFC 2850](https://github.com/rust-lang/rfcs/pull/2850)) which has stricter checks on the types that can be used as asm operands.

The legacy `llvm_asm!` is deprecated and is no longer maintained.
