### ISSUE TITLE
E0131 should say lifetime parameters when there's a lifetime

### ISSUE THREAD

**Issue by Havvy** [rust-lang/rust#51022]
```
error[E0131]: main function is not allowed to have type parameters
 --> src/main.rs:1:8
  |
1 | fn main<'a> () {}
  |        ^^^^ main cannot have type parameters
```

The error says **type** parameters when it should say **lifetime** parameters in this case.

This is definitely a low priority issue. Might make a good first issue though?

**Comment by simartin** [comment]
I propose to work on that one.
