### ISSUE TITLE
NLL diagnostics has lost "closure may outlive the current function" notes

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#51026]
The following `ui/` tests have regressed in the quality of their diagnostic output (compared to AST borrowck, at least) due to the loss of notes of the form "closure may outlive the current function"

 * [ ] borrowck/borrowck-escaping-closure-error-1.rs
 * [ ] borrowck/borrowck-escaping-closure-error-2.rs
 * [ ] issue-4335.stderr
 * [ ] region-borrow-params-issue-29793-small.rs
 * [ ] regions-nested-fns-2.rs
 * [x] src/test/ui/issue-40510-3.nll.stderr
 * [x] src/test/ui/issue-49824.nll.stderr

(This list of tests is drawn from an [informal paper](https://paper.dropbox.com/doc/NLL-stderr-diagnostic-deviations-KzroSvNgQ7lip3WQyiLTa) document that I have been using to keep notes for myself as I work on this...)

**Comment by nikomatsakis** [comment]
I'm tagging this as RC though it seems related to the other region error issues described in https://github.com/rust-lang/rust/issues/51027

**Comment by nikomatsakis** [comment]
Some comments on this starting [about here on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/122657-wg-nll/subject/pr-53088/near/131002802) -- [around here I highlighted how we might solve this](https://rust-lang.zulipchat.com/#narrow/stream/122657-wg-nll/subject/pr-53088/near/131003279)

**Comment by matthewjasper** [comment]
Added the two extra cases that that discussion was about
