### ISSUE TITLE
NLL diagnostics lost special notes re: free ("outer") variables in `Fn`/`FnMut`/etc closures

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#51028]
The following tests used to have nice specific reports about the role of `Fn` or `FnMut` in the code (and how it impacts the uses of free variables, aka "outer variables", in the body of the closure), but all of that has been lost in NLL.

 * [x] borrowck/borrowck-in-static.rs
 * [x] issue-21600.rs
 * [x] suggestions/closure-immutable-outer-variable.rs
 * [x] suggestions/fn-closure-mutable-capture.rs
 * [x] borrowck/unboxed-closures-move-upvar-from-non-once-ref-closure.rs

I suspect the following are also fundamentally related, though the particular diagnostics differ. (We may well want to branch them off into their own independent issues.)

 * [ ] closure_context/issue-42065.rs
   *  (here instead of reporting an error about `Fn`/`FnMut`/`FnOnce`, we instead point out that the closure in question cannot be invoked multiple times; i.e. we must have inferred it to be an `FnOnce`, but that isn't part of the presented error message, for better or for worse).

(This list of tests is drawn from an [informal paper](https://paper.dropbox.com/doc/NLL-stderr-diagnostic-deviations-KzroSvNgQ7lip3WQyiLTa) document that I have been using to keep notes for myself as I work on this...)

**Comment by nikomatsakis** [comment]
I don't think `issue-21600.rs` fits with the others here

**Comment by nikomatsakis** [comment]
I categorize this as Release Candidate — doesn't feel like a must have for Edition Preview

**Comment by nikomatsakis** [comment]
Closing, this seems done.
