### ISSUE TITLE
[idea] attr for function prototype assertion

### ISSUE THREAD

**Issue by jnqnfe** [rust-lang/rust#51039]
I have a program with support for plugins. Plugins are dynamically loaded on demand. In C a macro was used for defining the start of the function that is the entry point into the plugin, which guaranteed that this function in all plugins (official and 3rd-party) always had the correct prototype/signature. Trying to hack a similar macro based solution into the new Rust codebase is not exactly ideal, and thus in my new Rust codebase such functions are now written without any such hackish thing. It would be great if there were some neat and simple solution for checking at compile time that these functions match a certain signature. Without such a solution, if the signature changes in the program's core lib, and a plugin is forgotten to be updated, compiling works successfully and you only (possibly) notice the problem later at runtime.

I envision a simple solution like follows, You:
1) define a public type describing the signature
2) against the relevant function, declare a "prototype_match" attribute, pointing it at the signature type.

Alternatively, the signature type could be `use`d and the name only specified in the attr.

Sometimes it may also be important that the function name is something specific, thus an additional attribute for that.

An example:

In the core lib, `::plugins` mod
```rust
pub type DescriptorFnSig = fn(&Foo) -> Result<Bar, ()>;
pub const DescriptorFnName: &str = "foo_plugin_descriptor";
```
In an example plugin, suggested usage # 1
```rust
extern crate foo;
use foo::{Foo, Bar};

#[no_mangle]
#[attr(prototype_match="foo::plugins::DescriptorFnSig")]
#[attr(symbol_name="foo::plugins::DescriptorFnName")]
pub fn foo_plugin_descriptor(foo: &Foo) -> Result<Bar, ()> {
    //whatever
}
```
In an example plugin, suggested usage # 2
```rust
extern crate foo;
use foo::{Foo, Bar};
use foo::plugins::{DescriptorFnSig, DescriptorFnName}

#[no_mangle]
#[attr(prototype_match=DescriptorFnSig)]
#[attr(symbol_name=DescriptorFnName)]
pub fn foo_plugin_descriptor(foo: &Foo) -> Result<Bar, ()> {
    //whatever
}
```
If the function to which these attr are attached is found to not match what is specified, a error should occur at compile time. Also if what is pointed to by the attr is not found, an error (or warning?) occurs.

It may not be enough though for these attributes to only exist against functions, there may be other uses for them. For instance, in the C code for this program, the function names actually have an ABI version embedded in them. In the Rust codebase it would be a major pain to be renaming all such functions in every plugin to do similar (and using macros is as already suggested not ideal - I don't much like the idea of forcing the entire function body through a macro invocation). Alternatively they could have a public no_mangle symbol which declares the ABI version that the plugin was compiled against. These concepts could be applied to such a `const`, thus highlighting at compile time the problem if the expected name or type of this const ever changes.

Example
in the core lib, `::plugins` mod
```rust
pub const ABIVersion = 1; // Current plugin ABI version
pub const ABISymbolName: &str = "FOO_ABI_VERSION";
pub type AbiVersionType = u16;
```
in a plugin:
```rust
extern crate foo;
use foo::plugins::{AbiVersionType, ABIVersion, ABISymbolName};
#[no_mangle]
#[attr(type_match=AbiVersionType)]
#[attr(symbol_name=ABISymbolName)]
pub const FOO_ABI_VERSION: AbiVersionType = ABIVersion;
```

I am aware that the solution for converting C's static_asserts to Rust are to create a small unit test, and I could imagine that to some degree the same could be done here, however that's a rather messy solution in my opinion, and in a large and complex application as I'm working on I'm not convinced by it.

The solution proposed is much cleaner, surely of wide interest to programs with plugin systems, and surely very simple to implement in rustc.

**Comment by Aaronepower** [comment]
Triage; @jnqnfe Hello, can you post your idea on https://users.rust-lang.org/ that is the more appropriate place to post ideas, thank you!
