### ISSUE TITLE
rustbuild: support paths created by tab-completing in Powershell

### ISSUE THREAD

**Issue by QuietMisdreavus** [rust-lang/rust#51071]
Currently, if you give a path to bootstrap to build or test, it works perfectly if you have a Unix-style relative path - no prefix, forward-slashes to separate directories. However, when tab-completing files in Powershell, it currently inserts a `.\` at the front to force parsing as a relative path, and (due to being Windows) uses back-slashes for directory separators. This causes bootstrap to fail parsing the path:

```
> python x.py test .\src\test\run-pass\issue-38226.rs
[...snipping out the "building bootstrap and dependencies" lines...]
Error: thread 'main' panicked at 'No rules matched .\src\test\run-pass\issue-38226.rs'.

> python x.py test src/test/run-pass/issue-38226.rs
[...begins compiling as normal...]
```

**Comment by Mark-Simulacrum** [comment]
This is also a problem for any path prefixed by `./` on Unix I believe so we probably want some general solution. Shouldn't be too difficult of a bug, I'd investigate https://github.com/rust-lang/rust/blob/master/src/bootstrap/builder.rs#L288 (`std::path::Path::new("./src/test/run-pass").starts_with("src/test/run-pass")` evaluates to false), and you might also need to make changes to the test code which dispatches based on the suite path: https://github.com/rust-lang/rust/blob/master/src/bootstrap/test.rs#L1028.

**Comment by SLaabsDev** [comment]
I'd like to take this one up if nobody else is working on it.

**Comment by Mark-Simulacrum** [comment]
Go ahead! Let me know if I can offer any guidance.

**Comment by SLaabsDev** [comment]
@Mark-Simulacrum I've tried adding to the run function some code that strips any current directory prefixes before checking if the given path is a suite path [here](https://github.com/SLaabsDev/rust/blob/master/src/bootstrap/builder.rs#L222). This resolves the matching error but when running `./x.py test ./src/test/run-pass/yield1.rs` it will instead run the entire run-pass suite. I'm a little unsure of where to look for where this command is being sent wrong at this point. Any thoughts on where this may be happening or a better way to handle this issue?
