### ISSUE TITLE
iter::fuse not behaving as expected

### ISSUE THREAD

**Issue by JEphron** [rust-lang/rust#51119]
The [docs](https://doc.rust-lang.org/std/iter/struct.Fuse.html) led me to believe that fuse would yield items until it saw a None, and then yield only Nones. Maybe I'm misunderstanding, but 
```rust
let v = vec!["0", "a", "1", "2"];
let it: Vec<Option<i32>> = v.iter().map(|x| x.parse().ok()).fuse().inspect(|x| println!("inspected {:?}",x)).collect();
println!("it:{:?}", it);
```
outputs
```
inspected Some(0)
inspected None
inspected Some(1)
inspected Some(2)
it:[Some(0), None, Some(1), Some(2)]  
```
whereas I'd expect to see something like `it:[Some(0), None, None, None]`

rustc 1.28.0-nightly (cb20f68d0 2018-05-21)

**Comment by ordovicia** [comment]
The `map()` yields `Some(Some(0)), Some(None), Some(Some(1)), Some(Some(2))`, followed by `None`.
The `fuse()` does not fuse `Some(None)`.

```rust
fn main() {
    let mut iter = ["0", "a", "1", "2"].iter().map(|x| x.parse::<i32>().ok());

    for _ in 0..5 {
        println!("{:?}", iter.next());
    }
    // => Some(Some(0)), Some(None), Some(Some(1)), Some(Some(2)), None
}
```
The `fuse()` method is used for iterator that may return `Some` after it returns `None`, claiming that it has nothing to yield.
E.g. Incoming network buffers.

**Comment by hellow554** [comment]
Somewhat related to https://github.com/rust-lang/rust/issues/50225 ?

**Comment by Manishearth** [comment]
Yeah, this is behaving as expected. fuse is about iterators that may "start" again after finishing, not about iterators over an option.

**Comment by pacman82** [comment]
This is how fused is supposed to behave. `it.next()` in this example is returning `Option<Option<i32>>`. With the outer `Option`indicating if the iterator has reached its end, and the inner `Option` indicating if parsing has been successful. The inner `Option`is part of the element type iterated over and it being `None` should not cause fuse to do anything.
