### ISSUE TITLE
rustdoc: The default style of items inside "Implementations on Foreign Types" is very ugly

### ISSUE THREAD

**Issue by kennytm** [rust-lang/rust#51113]
Demo: https://doc.rust-lang.org/beta/alloc/slice/trait.SliceIndex.html

![screenshot_2018-05-28 03 53 53_nm2wqt-fs8](https://user-images.githubusercontent.com/103023/40590098-ab3f935a-622b-11e8-8294-ad7f35e144d2.png)

There are many unnecessary elements applied to the "Implementations on Foreign Types" which probably should all be removed.

cc @QuietMisdreavus (#43849)

**Comment by GuillaumeGomez** [comment]
Wo, the style is completely broken. I'll fix it.
