### ISSUE TITLE
Binaries compiled on Raspberry Pi with arm-unknown-linux-musleabihf fail on the same device

### ISSUE THREAD

**Issue by michaelherger** [rust-lang/rust#51112]
I've built [librespot](https://github.com/librespot-org/librespot) binaries on my Raspberry Pi running Raspbian. Up until Rust 1.21 I was able to use arm-unknown-linux-musleabihf as a target. Anything after that version would create invalid binaries. The resulting executable is not executable after all. They can't be run on the same Raspbian system.

I tested using versions 1.22.1 and 1.24.0.

**Comment by pnkfelix** [comment]
discussed at compiler meeting. Marking as P-medium. Removing nomination tag.

Would be good if someone with a RaspPi or similar system could look into it.

**Comment by michaelherger** [comment]
Are there any news on this? Testing with 1.31 this still fails.

**Comment by michaelherger** [comment]
Ok, you made me thinking again. Doesn't seem to be a generic issue. "Hello World" would compile and link perfectly well:

```
$ file hello_world
hello_world: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), statically linked, BuildID[sha1]=2c5660ddf95cbe578f3bfcc00b7e8be8ac11bad4, not stripped
```

Where the `librespot` binary would be considered "dynamically linked":

```
$ librespot
librespot: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /usr, BuildID[sha1]=dfa1ae4ddd017f8ad9b084905e2eedad079ecf8d, not stripped
```

I guess it's an issue with some of the crates used. Could the following be pointing at such an issue?

```
warning: dropping unsupported crate type `cdylib` for target `arm-unknown-linux-musleabihf`
```

**Comment by mati865** [comment]
That's probably the issue.
