### ISSUE TITLE
Unsoundness for iterator returning mutable references.

### ISSUE THREAD

**Issue by zpgaal** [rust-lang/rust#51120]
As the lifetime  of an item returned by an iterator is bound to the lifetime of the iterator and not to the call of the next function, it is easy to create code where multiple variable points mutable to the same object. 
To create such iterators either it  requires unsafe codes or the implementation of the Iterator trait have to be given up.

I wanted to create a merge_on_the_fly iterator for from two mut ref iterator where sometimes the same item is returned when calling next. It works fine as long as it is used in a for loop. But user may use the iterator outside a for loop and nothing warns/errors when references are kept between consecutive next calls.

There were some suggestions before how to fix this issue. But it seems as all of them were closed/postponed without a real solution. So i'd like to reraise this issue.

**Comment by ishitatsuyuki** [comment]
What you mentioned is known as [streaming iterators](https://docs.rs/streaming-iterator/).

Also, what you are asking is unclear. There's no known soundness hole regarding `Iterator`s. If you need help on writing idiomatic Rust, please seek help on https://users.rust-lang.org or #rust on IRC.

**Comment by zpgaal** [comment]
OK' i was wrong with respect to the unsoundness.
I was already in unsafe with pointer casts so - Never mind for that part.
(https://play.rust-lang.org/?gist=fd1cd6951145fd7f15bae7fd116d8c21&version=stable&mode=debug)
It is not compiling as expected, and could not create unsound code without unsafe blocks)

The streaming iterator might be an option (I've not checked it)
But I think it's still a language level (API) issue that NO iterators returning mut ref can be implemented that is for loop compatible without unsafe code. (And it's quite easy to overlook the unsafe part as the was my case).

I think it worst some discussion. I've googled a lot but found no satisfying solution. So it'd be good to have some more docs on how-to implement IterMut.
The only detailed docs found was http://smallcultfollowing.com/babysteps/blog/2013/10/24/iterators-yielding-mutable-references but it is quite old without providing a resolution.

**Comment by ishitatsuyuki** [comment]
I read your code, but it's still not clear what you're trying to achieve. Please explain what you're **really** trying to do.

Also, this looks like a general coding question. Please move this question to https://users.rust-lang.org.

**Comment by Mark-Simulacrum** [comment]
> But I think it's still a language level (API) issue that NO iterators returning mut ref can be implemented that is for loop compatible without unsafe code. (And it's quite easy to overlook the unsafe part as the was my case).

Yes, it's a "known problem" that for loops don't currently support streaming iterators. That's not something that can be solved without an RFC, I think, and questions in this regard should be asked elsewhere. As such, closing.
