### ISSUE TITLE
i686 edition for NetBSD

### ISSUE THREAD

**Issue by mcandre** [rust-lang/rust#51137]
So that rustup can offer an i686 edition for FreeBSD and NetBSD.

**Comment by sanxiyn** [comment]
i686-unknown-freebsd is available on rustup now.

**Comment by jbeich** [comment]
> i686-unknown-freebsd is available on rustup now.

Only as a target i.e., not suitable for building complex projects such as Firefox. Cross-compilation story outside of jails/chroot is poor on FreeBSD.
```
$ uname -srp
FreeBSD 11.2-RELEASE i386

$ curl https://sh.rustup.rs -sSf | sh
info: downloading installer
curl: (22) The requested URL returned error: 404
rustup: command failed: downloader https://static.rust-lang.org/rustup/dist/i686-unknown-freebsd/rustup-init /tmp/tmp.Hq3qKomr/rustup-init
```

**Comment by jbeich** [comment]
@sanxiyn, can you restore `O-freebsd` tag and revert subject change? See previous comment for the rationale.

**Comment by sanxiyn** [comment]
I think it's best to have separate issues for FreeBSD and NetBSD. After all, i686/FreeBSD is now available as rustup target, but i686/NetBSD is not.

**Comment by workingjubilee** [comment]
Hello. We have codified our approach to [platform support](https://doc.rust-lang.org/nightly/rustc/platform-support.html), and elevating this target from tier 3 should probably be pursued as a [T-compiler Major Change Proposal](https://forge.rust-lang.org/compiler/mcp.html).
