### ISSUE TITLE
NLL: missing note that "borrowed value needs to live until here" (sometimes?)

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#51168]
Consider: https://github.com/rust-lang/rust/blob/master/src/test/ui/span/issue-11925.nll.stderr

Compare it to: https://github.com/rust-lang/rust/blob/master/src/test/ui/span/issue-11925.stderr

The former is missing a note that "borrowed value needs to live until here"

----

Oftentimes, NLL diagnostics *do* include a note of the form "needs to live until use here." But apparently for this case (due to closures? Or destructors? Or both?) we do not have such a use to point at.

Anyway, this represents a regression in the informativeness of our diagnostics under NLL.

**Comment by nikomatsakis** [comment]
The reason for this is indeed the closure, I think. We detect the error when analyzing the closure body, so it is hard for us to report a span that is outside the closure. I think this will be pretty tricky to fix and is maybe not that important. What we *could* probably do is take a different tactic: we could explain that `x` is owned by the closure and yet we are returning a reference to it (just as we would a top-level function, perhaps).

I'm imagining:

```
error[E0597]: `x` is owned by the closure, so you cannot return a reference to it
  --> $DIR/issue-11925.rs:18:35
   |
LL |         let f = to_fn_once(move|| &x); //~ ERROR does not live long enough
   |                                   ^
   |                                   |
   |                                   |
| cannot return reference to data owned by the closure
```

for bonus points, we can highlight the `move` keyword and/or the use of `x` that caused it to a move in the first place (we have that data available somewhere).

**Comment by nikomatsakis** [comment]
I think that fixing this would also fix the examples here:

https://github.com/rust-lang/rust/issues/51027

**Comment by nikomatsakis** [comment]
Actually I'm marking this as a sub-issue of #51027

**Comment by matthewjasper** [comment]
nominating for discussion on whether this should be kept open

**Comment by nikomatsakis** [comment]
Decided to close. The current output is arguably clearer, and it would be quite challenging to add the "needs to live until here" note, since we don't have that information at the point where we report the error anymore. It's not clear that it adds a lot of information anyway.
