### ISSUE TITLE
Factor out type size and alignment code from C ABI implementations

### ISSUE THREAD

**Issue by sanxiyn** [rust-lang/rust#5116]

**Comment by steveklabnik** [comment]
Triage bump: not totally clear to me.

**Comment by sanxiyn** [comment]
What is proposed here is to remove code duplications from `rustc_trans::trans::cabi_*`. Those modules define `ty_size` and `ty_align` functions, which are mostly but not exactly same as each other.

**Comment by steveklabnik** [comment]
Triage: all of those files are still there.
