### ISSUE TITLE
NLL: diagnostics deviate from source line order for no obvious reason

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#51167]
Consider:

https://github.com/rust-lang/rust/blob/master/src/test/ui/span/send-is-not-static-ensures-scoping.nll.stderr

compare it to the AST borrowck output:

https://github.com/rust-lang/rust/blob/master/src/test/ui/span/send-is-not-static-ensures-scoping.stderr

 1. Why are we inverting the order in which we report these diagnostics?
 2. We may want to consider not doing that. Even if it means e.g. buffering the diangotics and sorting them before emitting them, or some similar hack. (I admit I am loathe to do this since I myself really like when I am able to correlate the `RUST_LOG` output with diagnostic output. But if necessary, we could add a `-Z` flag to turn off the buffer+sorting, in order to bring back such correlation. For end users, buffering+sorting is probably a net win.)

An important reason to prioritize this: Fixing this is likely going to make our *internal* process for comparing the diagnostic output more efficient.

**Comment by nikomatsakis** [comment]
Marking as Edition Preview 2 because .. maybe an easy fix.

**Comment by nikomatsakis** [comment]
I think we should just *try* visiting the basic blocks in reverse-postfix order. The visit occurs here:

https://github.com/rust-lang/rust/blob/860d169474acabdc53b9a698f8ce02eba7e0daeb/src/librustc_mir/dataflow/mod.rs#L334-L340

and in particular the for loop here goes over the basic blocks in an arbitrary order

https://github.com/rust-lang/rust/blob/860d169474acabdc53b9a698f8ce02eba7e0daeb/src/librustc_mir/dataflow/mod.rs#L336

What we want to do is to go over in [reverse post-order](https://stackoverflow.com/questions/36131500/what-is-the-reverse-postorder), which basically maps to execution order as we would normally define it. There is a [function `reverse_postorder` that already exists to compute this ordering](https://doc.rust-lang.org/nightly/nightly-rustc/rustc/mir/traversal/fn.reverse_postorder.html) -- it returns an `Iterator<Item = BasicBlock>` -- and you can see some other random code that uses it here:

https://github.com/rust-lang/rust/blob/860d169474acabdc53b9a698f8ce02eba7e0daeb/src/librustc_mir/transform/qualify_consts.rs#L130

So we basically want to change that code to iterate over the result of `reverse_postorder`.

**Comment by nikomatsakis** [comment]
Assigning to @spastorino as this should get fixed as a side-effect of #46908

**Comment by spastorino** [comment]
Assigning to @pnkfelix as he took over the migrate thing. I can help here if needed at some point.

**Comment by pnkfelix** [comment]
@nikomatsakis do you think this should remain on EP2, or should we move it to RC?

(I'm going to take a shot at resolving it today, or at least doing as much as I can via the buffering we added. But still, time is tight for EP2.)

**Comment by pnkfelix** [comment]
moving this to RC as I think it is sufficiently low priority that it should not block EP2 nor NLL's release in EP2.
