### ISSUE TITLE
Test C ABI implementations

### ISSUE THREAD

**Issue by sanxiyn** [rust-lang/rust#5117]
cf. http://code.google.com/p/quest-tester/

**Comment by steveklabnik** [comment]
Triage: no change.

**Comment by steveklabnik** [comment]
Triage: still no change

**Comment by alexcrichton** [comment]
Got here by looking at A-LLVM bugs and this seems vague enough today that there's not really something actionable here, so closing

**Comment by graydon** [comment]
I'd recommend reconsidering: it's very easy to get the part of the x64 C ABI you have to implement in the rust side wrong -- the parts LLVM doesn't do for you -- and wind up generating subtly-wrong code that breaks in deeply inscrutable ways when a user passes just the wrong combination of arguments.

(Speaking as someone who picked a bug out of the Swift version of this code just last month)

**Comment by graydon** [comment]
(in particular https://github.com/rust-lang/rust/blob/master/src/librustc_trans/cabi_x86_64.rs and its neighbours)

**Comment by alexcrichton** [comment]
AFAIK there's a large suite of run-make/run-pass tests which pass structs to/from C and Rust and ensures that everything looks correct, which I believe is the purpose of this issue?

**Comment by graydon** [comment]
*shrug* ok, thought it was being closed out of "meh" rather than "done".
