### ISSUE TITLE
rand fails to migrate

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#51209]
@teiesti [helpfully reported](https://github.com/rust-lang/rust/issues/51180#issuecomment-392940606) that `rand` fails to migrate successfully:

[branch here](https://github.com/teiesti/rand/tree/rust-2018-migration)

```
$ cargo +nightly build
   Compiling rand v0.5.0 (file:///home/tobias/dev/rand)
error[E0463]: can't find crate for `distributions`
   --> src/distributions/uniform.rs:104:5
    |
104 | use distributions::Distribution;
    |     ^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error
```

**Comment by Mark-Simulacrum** [comment]
I successfully migrated rand after some minor edits to macros (`::core` being replaced with `crate::core`); so I'm going to close this issue.
