### ISSUE TITLE
"path starts with module" lint fails with rustfix when triggered in macro

### ISSUE THREAD

**Issue by killercup** [rust-lang/rust#51205]
Thanks to @AdamNiederer opening <https://github.com/rust-lang-nursery/rustfix/issues/114>, we found that it's not possible to fully upgrade [faster](https://github.com/AdamNiederer/faster) to the 2018 edition with rustfix.

It fails with "Cannot replace slice of data that was already replaced", because we get the exact same suggestion twice -- because it's part of an expanded macro.

It looks to me like in addition to the changes @alexcrichton introduced in https://github.com/rust-lang/rust/pull/50665, we'll also need to add a macro check [here](https://github.com/rust-lang/rust/blob/8372e7b37eb9777edc8f7179fc6cbc39456ce735/src/librustc_resolve/lib.rs#L3473) and [here](https://github.com/rust-lang/rust/blob/8372e7b37eb9777edc8f7179fc6cbc39456ce735/src/librustc_resolve/resolve_imports.rs#L686-L691).

There are three solutions. The easy one is to not mark the suggestions as MachineApplicable when the span they come from is in macro. The hard ones are to only trigger this once (or just once as MachineApplicable), or to omit _exact_ duplicates in rustfix (and hope for the best).

**Comment by alexcrichton** [comment]
Your analysis looks spot on to me, thanks! Cc @nikomatsakis as well

Id probably err on the side of simicity and remove the machine applicable part of the warning when it comes from a macro, rustfix should be totally fine to have an exception or two it can't fix if they aren't super common

**Comment by nikomatsakis** [comment]
cc @Manishearth — we had been talking about basically doing this check automatically as part of the suggestion machinery (https://github.com/rust-lang/rust/issues/48704). I'm not sure what's the status there though, should probably figure that out.

**Comment by Manishearth** [comment]
Er, so there are two different things here and we should be careful not to mix them up.

One is that suggestions should not be marked as machine applicable if they touch macros. The machinery should do this itself, but you still need to handle the macro-ness of `span_to_snippet`s which may not interact. I suspect @zackmdavis may be interested in helping out here.



------

The other is that most lints shouldn't be triggered for macros at all. _However_, edition breakage lints are future incompatibility lints and they do not fall in this category.

The status of "most lints shouldn't be triggered for macros at all" is that a different PR (knowingly) broke the infrastructure that lets us do this check, and we're waiting for a fix on this. See https://github.com/rust-lang/rust/issues/50050#issuecomment-390685906 .

**Comment by Mark-Simulacrum** [comment]
We should fix the failure to migrate due to macros here - rustfix shouldn't abort on it

**Comment by alexcrichton** [comment]
Ok this issue itself is specifically fixed by https://github.com/rust-lang-nursery/rustfix/pull/131 and macros and edition lints are otherwise covered by https://github.com/rust-lang/rust/issues/48855 and https://github.com/rust-lang/rust/issues/48704, so I'm gonna close this in favor of them.
