### ISSUE TITLE
suggestions from other crates only work when an explicit `extern crate` is present

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#51212]
UPDATE: There has been some progress on this issue. `crate::` prefixes now work, but you still don't get suggestions from other crates except when you write an explicit `extern crate`.

When you get name resolution suggestions from resolve after an error, they should use `crate::` prefixes where appropriate. 

Example ([play](https://play.rust-lang.org/?gist=276dace52018d223f51b8c466e10d73f&version=nightly&mode=debug)):

```rust
#![feature(crate_visibility_modifier)]
#![feature(crate_in_paths)]

mod bar {
    crate struct Foo;
}

fn main() {
    Foo;
}
```

gives

```
error[E0425]: cannot find value `Foo` in this scope
 --> src/main.rs:9:5
  |
9 |     Foo;
  |     ^^^ not found in this scope
help: possible candidate is found in another module, you can import it into scope
  |
4 | use bar::Foo;
  |
```

but I want to see `use crate::bar::Foo` suggested.

**Comment by nikomatsakis** [comment]
It looks like the suggestions are issued here:

https://github.com/rust-lang/rust/blob/c131bdcaff68d35f96e954baac4340206779335f/src/librustc_resolve/lib.rs#L4436-L4463

The behavior I think we want is this:

> If the `crate_in_paths` feature is enabled, then we should suggest `use crate::bar::Foo` when `bar` is from a module and not an external crate. 

The function that prepares those suggestions appears to be this one:

https://github.com/rust-lang/rust/blob/c131bdcaff68d35f96e954baac4340206779335f/src/librustc_resolve/lib.rs#L4398-L4402

Here is an example of checking for whether the feature is enabled:

https://github.com/rust-lang/rust/blob/c131bdcaff68d35f96e954baac4340206779335f/src/librustc_resolve/lib.rs#L3493

**Comment by nikomatsakis** [comment]
@qmx expressed some interest in tackling this.

**Comment by nikomatsakis** [comment]
Hmm, now i'm worried that this will apply even when it shouldn't. Consider this testcase:

```rust
fn main() {
    let x: &Debug = &22;
}
```

This currently prints:

```
error[E0412]: cannot find type `Debug` in this scope
 --> src/main.rs:2:13
  |
2 |     let x: &Debug = &22;
  |             ^^^^^ not found in this scope
help: possible candidate is found in another module, you can import it into scope
  |
1 | use std::fmt::Debug;
  |
```

and I think we do *not* want it to print `use crate::std::fmt::Debug`.

I think this suggests an alternative fix to what I recommended before (and what @qmx did in #51456) -- but I'd like to get @petrochenkov's opinion. Before I suggested changing how the `ImportSuggestion` values are printed out, but now I think we should change them at the source:

https://github.com/rust-lang/rust/blob/a32e979ba53af4d4654bfad7babdb9f8c197c3a2/src/librustc_resolve/lib.rs#L4003-L4015

Right now, this works by walking through the crate and finding candidates. I *suspect* (but we should test) that this means it will not work when the `extern_prelude` option is enabled and no explicit `extern crate` exists, because there is nothing to walk over. Therefore, the change I propose is as follows:

1. Modify the function to (if `crate_in_paths` is enabled) to push a `crate` at the front of the import suggestions it is currently creating. This is because all of them are found by trawling the crate source.
2. Then, if `extern_prelude` is enabled, add a loop that executes first. This would go over all of the crates that are available from the command line, load them up, and search for the item within (basically the same as the existing search, but beginning from the crate directly). In this case, we would not prepend `crate::` to the resulting path, but instead the name of the crate we are searching.
  - One flaw I can see here is that it may be that the crate is locally shadowed. I *suspect* we can overlook that possibility for now.

**Comment by nikomatsakis** [comment]
@petrochenkov do the above notes seem ok?

**Comment by petrochenkov** [comment]
Looks reasonable.

**Comment by nikomatsakis** [comment]
To get a bit more detailed in how to make this modification, ultimately I envision we'll have a helper like this:

```rust
fn lookup_import_candidates_from_module(
    &mut self, 
    lookup_name: Name, 
    namespace: Namespace, 
    start_module: Module<'_>,
    filter_fn: impl Fn(Def) -> bool,
) -> Vec<ImportSuggestion> {
    ...
}
```

This will be roughly the same as the existing `lookup_import_candidates`, except that instead of starting from `self.graph_root`, it will seed the worklist with `start_module`:

https://github.com/rust-lang/rust/blob/a32e979ba53af4d4654bfad7babdb9f8c197c3a2/src/librustc_resolve/lib.rs#L4020

Then, later, when it finds a suggestion:

https://github.com/rust-lang/rust/blob/a32e979ba53af4d4654bfad7babdb9f8c197c3a2/src/librustc_resolve/lib.rs#L4053

It will check if `start_module == self.graph_root` and the `crate_in_paths` feature is enabled. In that case, it adds `crate::` to the start of the suggestion.

This is step 1. Step 2 in a second. =)

**Comment by nikomatsakis** [comment]
OK, so step 2... 

The basic idea was to iterate over each of the "available" crates. For each crate, we would load the crate (if not already loaded), and then use the `lookup_import_candidates_with_module` fn to walk and make a suggestion.

So the first question is where we find that list of available crates and how to load it. Here are some pointers. For example, here is where we find the set of things in the prelude:

https://github.com/rust-lang/rust/blob/fefe81605d6111faa8dbb3635ab2c51d59de740a/src/librustc_resolve/lib.rs#L1627-L1628

which ends up in the Resolver struct. And this is where we resolve paths that rely on external prelude:

https://github.com/rust-lang/rust/blob/fefe81605d6111faa8dbb3635ab2c51d59de740a/src/librustc_resolve/lib.rs#L1928-L1929

It seems sort of like this is the snippet of code to "load a crate if needed":

https://github.com/rust-lang/rust/blob/fefe81605d6111faa8dbb3635ab2c51d59de740a/src/librustc_resolve/lib.rs#L1937-L1939

I think the idea would be to refactor that last snippet of code into a helper fn, and then invoke it from `lookup_import_candidates`. So `lookup_import_candidates` would look something like:

```rust
    fn lookup_import_candidates<FilterFn>(&mut self,
                                          lookup_name: Name,
                                          namespace: Namespace,
                                          filter_fn: FilterFn)
                                          -> Vec<ImportSuggestion>
        where FilterFn: Fn(Def) -> bool
    {
        let mut suggestions = vec![];

        suggestions.extend(
            self.lookup_import_candidates_from_module(
                lookup_name, namespace, self.graph_root, keywords::Crate.name(), filter_fn
            )
        );

        if extern_prelude_feature_is_enabled {
            let extern_prelude_names = self.extern_prelude.clone();
            for &krate_name in extern_prelude_names.iter() {
                let extern_prelude_module = self.load_extern_prelude_crate_if_needed(krate_name);
                // ^^ that is the new helper method we added

                suggestions.extend(
                    self.lookup_import_candidates_from_module(
                        lookup_name, namespace, extern_prelude_module, krate_name, filter_fn
                    )
                );
            }
        }
    }
```

OK, there is a slight flaw -- I think that `lookup_import_candidates_from_module` should take not a `bool` ("in root") but rather a `Name` with the crate name to prepend (which would be `crate` in the case of the root module). I've modified the code above accordingly.
