### ISSUE TITLE
"expecting a type here because of type ascription" when forgetting a :

### ISSUE THREAD

**Issue by ProgVal** [rust-lang/rust#51222]
In the following code, I forgot a semicolon:

```
fn main() {
    Box:new("foo".to_string())
}
```

This generates the following error:

```
  |
2 |     Box:new("foo".to_string())
  |             ^^^^^ expecting a type here because of type ascription
```

This may get confusing when nesting multiple calls in the argument of `Box::new`.

ping @GuillaumeGomez

**Comment by estebank** [comment]
cc #34255, #48016.

**Comment by estebank** [comment]
CC #47666
