### ISSUE TITLE
Confusing compiler error when dealing with references to a function pointer

### ISSUE THREAD

**Issue by HenryNguyen5** [rust-lang/rust#51233]
When using a reference to a function pointer, it gets converted to a reference to a function item instead, making future assignments require a typecast to the wanted function pointer instead.

Relevant link below:
https://play.rust-lang.org/?gist=00a013ae03ba8b50ceb37499985807f1&version=nightly&mode=debug

**Comment by varkor** [comment]
This illustrates several diagnostic issues.
```rust
fn foo() {}

fn main() {
    let _f: fn() = foo; // Works
    let _fref: &fn() = &foo; //~ERROR expected fn pointer, found fn item
}
```
produces the error:
```
error[E0308]: mismatched types
 --> src/main.rs:5:24
  |
5 |     let _fref: &fn() = &foo; //~ERROR expected fn pointer, found fn item
  |                        ^^^^ expected fn pointer, found fn item
  |
  = note: expected type `&fn()`
             found type `&fn() {foo}`
```
1. It's not clear what `fn pointer` or `fn item` are, especially for a beginner. (Arguably the term `fn item` is compiler jargon.)
2. The notation `fn() {foo}` is meaningless unless you're already familiar with how Rust handles function types.
3. The user is trying to take a reference to a function here. What they actually want is a function pointer (i.e. without any reference), but it can seem intuitive to take a reference to a function instead. The error message should explain what's going on, and in the ideal case suggest removing the references.

**Comment by estebank** [comment]
Current output:

```
error[[E0308]](https://doc.rust-lang.org/nightly/error_codes/E0308.html): mismatched types
 --> src/main.rs:5:24
  |
5 |     let _fref: &fn() = &foo; //~ERROR expected fn pointer, found fn item
  |                -----   ^^^^ expected `&fn()`, found `&fn() {foo}`
  |                |
  |                expected due to this
  |
  = note: expected reference `&fn()`
             found reference `&fn() {foo}`
  = note: fn items are distinct from fn pointers
  = note: when the arguments and return types match, functions can be coerced to function pointers
help: consider casting to a fn pointer
  |
5 |     let _fref: &fn() = &(foo as fn()); //~ERROR expected fn pointer, found fn item
  |                        ~~~~~~~~~~~~~~
```
