### ISSUE TITLE
`rustc --explain E0495` missing documentation

### ISSUE THREAD

**Issue by smklein** [rust-lang/rust#51243]
This error message was reported while compiling a project of mine locally:
`error[E0495]:` cannot infer an appropriate lifetime for autoref due to conflicting requirements`

The compiler advised the following:
For more information about this error, try `rustc --explain E0495`.

However, that results in the following:

$ rustc --explain E0495
error: no extended information for E0495

For reference:

$ rustc --version
rustc 1.28.0-nightly (990d8aa74 2018-05-25)

**Comment by MisieEugene** [comment]
Hi,
I have the same issue with my stable installation.

For reference:

$ rustc --version
rustc 1.27.1 (5f2b325f6 2018-07-07)

**Comment by luojia65** [comment]
Same problem. I've installed `Version 1.33.0 (2aa4c46cf 2019-02-28)`.

**Comment by JohnTitor** [comment]
Seems fixed in the latest beta(rustc 1.40.0-beta.1 (76b40532a 2019-11-05)) and nightly
@smklein @MisieEugene @luojia65 could you check it?

**Comment by JohnTitor** [comment]
Closing as fixed.
If you still have the problem, feel free to re-open this!
