### ISSUE TITLE
When type inference depends on the content of a closure, earlier statements do not make use of this information

### ISSUE THREAD

**Issue by dylanede** [rust-lang/rust#51273]
Minimal example:

```rust
fn main() {
    // Behaviour does not appear linked to the use of unimplemented!()
    let x = unimplemented!();

    // Move the definition of g above this line to get this to compile
    x.0; // E0282: cannot infer type for `_`
    let g = || {
        let x: (i32, i32) = x;
    };
}
```
[playground](http://play.rust-lang.org/?gist=9990b078745e0f65827b1820940e9080&version=nightly&mode=debug)

This appears in stable, beta and nightly.

This appears to be a case where type inference should not depend on the order of these statements in the function.

This problem can be a deal-breaker when unnameable types are involved and reordering the statements isn't possible.

**Comment by leodasvacas** [comment]
You're right, type checking should not depend on the order of the statements, however it's a know limitation that sometimes it does, notably in indexing `x[0]`, field access `x.0` and method cals `x.foo()`. You don't even need the closure for that:
```rust
let x = unimplemented!();
// Move `let x` above this line to get this to compile
x.0; // E0282: cannot infer type for `_`
     // note: type must be known at this point
let x: (i32, i32) = x;
```
If you look closely at the nightly error you'll see the `note: type must be known at this point` which marks the fact that type checking failed early. We hope to improve this in the future, but for now I'm closing this as a known issue. Thank you for the report!

**Comment by dylanede** [comment]
@leodasvacas, OK, is there an issue tracking this somewhere then? If not, maybe one should be created.

**Comment by leodasvacas** [comment]
@dylanede We don't have a comprehensive issue tracking this, it would be good to have one. #50692 was about the same thing. rust-lang-nursery/chalk#105 is about the first thing we need to do to improve this.
