### ISSUE TITLE
FAQ on "How do I return a closure from a function?" no longer correct because impl Fn

### ISSUE THREAD

**Issue by FranklinChen** [rust-lang/rust#51289]
https://www.rust-lang.org/en-US/faq.html#how-do-i-return-a-closure-from-a-function is no longer correct because now it is possible to return a closure without boxing it thanks to returning `impl Fn`.

**Comment by est31** [comment]
It should probably also mention that if the closure doesn't capture anything, you can return a function pointer now, as non capturing closures coerce to function pointers.

**Comment by pietroalbini** [comment]
The FAQ is managed on the [rust-lang/rust-www repo](https://github.com/rust-lang/rust-www). Can you open an issue there? Thanks!
