### ISSUE TITLE
Add support for fragment specifiers in intra-doc-links

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#51284]
It should be possible to link to things like https://doc.rust-lang.org/nightly/std/vec/struct.Vec.html#indexing via `[Vec#indexing]`.

This is pretty straightforward to implement. We already track fragment specifiers for things like methods and enum variants, which we extract [here](https://github.com/rust-lang/rust/blob/aa094a43cc041c8483b7c80fb0ec4be233dd01b7/src/librustdoc/clean/mod.rs#L1193). What we can do additionally is when parsing if we come across `#foo`, strip it out, continue resolution, and if the resolved thing doesn't already have a fragment, use this instead.

I volunteer @sunjay to work on this, because he's the one who wanted this feature 😉 

cc @QuietMisdreavus 

Unsure if this needs an RFC.

**Comment by killercup** [comment]
Looks useful to me.

I agree a simplistic version of this is trivial to implement. The original idea with intra-doc-links howeve was to ensure at rustdoc-render-time that the links are valid. To implement that vision here, we'd need to ensure that the target item actually has a fragment with given name. _This_ might not be trivial: Most fragment identifiers are generated by turning a headline into a valid HTML ID. (I'm not sure if rustdoc does anything more than that. It try to should prevent setting the same ID twice, but that is probable another issue.)

**Comment by GuillaumeGomez** [comment]
Just like @killercup said: won't be as easy as might look like. But where would be the fun otherwise? 😛

**Comment by Manishearth** [comment]
Don't we already support this?

https://github.com/rust-lang/rust/blob/3014f23ddd437d2ba9947383c4565d09c1eb39f2/src/librustdoc/passes/collect_intra_doc_links.rs#L578

**Comment by GuillaumeGomez** [comment]
We actually already do it, indeed. I'm closing this issue then.
