### ISSUE TITLE
Can i use match field name in struct?

### ISSUE THREAD

**Issue by fundon** [rust-lang/rust#51293]
```rust
struct WorldCup {
   match: String,
}
```

error
```
^^^^^ expected identifier, found keyword
```

**Comment by rizakrko** [comment]
Keywords are reserved by the Rust language and may not be used as identifiers such as names of functions, variables, parameters, struct fields, modules, crates, constants, macros, static values, attributes, types, traits, or lifetimes. `match` is one of them.
[Related section in documentation](https://doc.rust-lang.org/book/second-edition/appendix-01-keywords.html)

**Comment by xpe** [comment]
@rizakrko There is more to this story...

One can use raw identifiers, as explained at https://doc.rust-lang.org/reference/identifiers.html :

> A raw identifier is like a normal identifier, but prefixed by r#. (Note that the r# prefix is not included as part of the actual identifier.) Unlike a normal identifier, a raw identifier may be any strict or reserved keyword except the ones listed above for RAW_IDENTIFIER

These raw identifiers are *not* allowed: crate, self, super, Self


So, if you want to use 'match' in a struct, do this:

```rs
struct WorldCup {
   r#match: String,
}

fn main() {
    let wc = WorldCup { r#match: "19 July 1930 Argentina 6-3 Mexico".to_string() };
    println!("{}", wc.r#match);
}
```

https://doc.rust-lang.org/reference/identifiers.html
