### ISSUE TITLE
Failed to compile (signal: 9, SIGKILL: kill)

### ISSUE THREAD

**Issue by TomasHubelbauer** [rust-lang/rust#51309]
Hey, I set up a new Cargo project using Actix-web and its verbatim example code. This meant adding an `actix-web` dependency and replacing the text in `src/main.rs`. I did this on a fresh Ubuntu 16.04 x64 install where only `ca-certificates` and `build-essential` were installed before Rust (from Rustup).

When I went to compile the project using `cargo run`, the build failed while compiling `http`. I've used `--verbose` to see what was up and got this:

```
> rustc --crate-name http /root/.cargo/registry/src/github.com-1ecc6299db9ec823/http-0.1.5/src/lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 -C metadata=c5fc1c2aeed1cb92 -C extra-filename=-c5fc1c2aeed1cb92 --out-dir /root/www/target/debug/deps -L dependency=/root/www/target/debug/deps --extern fnv=/root/www/target/debug/deps/libfnv-7a9f4c1f096c756f.rlib --extern bytes=/root/www/target/debug/deps/libbytes-5673bf19e74e48d8.rlib --cap-lints allow
Killed.
```

I filed an issue for this in `http` hyperium/http#207, but was advised to file here as it may be a compiler bug? So here goes. Anything I can do to help debug further I will. I am not that familiar with Unix debuggers, but I can provide some traces and stuff like that if told how.

**Comment by ishitatsuyuki** [comment]
It's likely caused by OOM. What machine is it running on?

**Comment by TomasHubelbauer** [comment]
Yeah it's probably a given now, the machine only has 500 MB RAM, I will try to add more RAM to it and will retry, but I am almost certain this is correct so I will close and reopen if I find different results.
