### ISSUE TITLE
Broken MIR: scope[1] index exists, but source_scope_local_data.len() == 1

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#51314]
One test that produces such broken MIR is https://github.com/rust-lang/rust/blob/master/src/test/run-pass/mir-inlining/ice-issue-45885.rs

the MIR is

[log.txt](https://github.com/rust-lang/rust/files/2065378/log.txt)

**Comment by oli-obk** [comment]
cc @eddyb  I think promotion fails to adjust the scope indices

**Comment by eddyb** [comment]
I thought the scope data is just cloned from the `fn` - maybe the "local" part is lost?

**Comment by bjorn3** [comment]
The mentioned link gives a 404.

**Comment by jonas-schievink** [comment]
New link: https://github.com/rust-lang/rust/blob/master/src/test/ui/mir/mir-inlining/ice-issue-45885.rs

**Comment by Aaron1011** [comment]
See https://github.com/rust-lang/rust/pull/66203
