### ISSUE TITLE
Rustdoc: File random overwrite each other on Windows because of case insensitive fs.

### ISSUE THREAD

**Issue by crlf0710** [rust-lang/rust#51327]
Minimal case;

````
#![allow(non_camel_case_types)]

pub struct S;

pub struct s;
````

Sorry, maybe this will lead to ugly hacks, however, I believe some action should be taken.

**Comment by ollie27** [comment]
duplicate of #25879

**Comment by crlf0710** [comment]
Yes, it is, searched but didn't find it... closing. Thanks
