### ISSUE TITLE
`assert!(false, "{}")` compiles and prints `{}`

### ISSUE THREAD

**Issue by rocallahan** [rust-lang/rust#51338]
```
assert!(false, "{}")
```
prints `{}` but
```
assert!(false, "{}", 77);
```
prints `77`. Given that the second parameter is interpreted as a format string, shouldn't it fail to compile if you don't provide enough parameters?

**Comment by rocallahan** [comment]
Happens on stable and nightly.

**Comment by mcarton** [comment]
This has been known for a while, Clippy even has [a lint about it](https://rust-lang-nursery.github.io/rust-clippy/master/index.html#panic_params).

**Comment by ollie27** [comment]
Yeah, this is a duplicate of #22932.

**Comment by rocallahan** [comment]
OK
