### ISSUE TITLE
Add std::boxed::Box::downcast_ref()

### ISSUE THREAD

**Issue by hkcorac** [rust-lang/rust#51337]
Hi,

Currently `Box` has this:

```rust
pub fn downcast<T>(self) -> Result<Box<T>, Box<Any + 'static>> where T: Any
```

Could you consider adding `::downcast_ref()`? Sometimes I don't want to consume the box.

For example:

```rust
let components: Vec<Box<Component>> = ...
for c in components.iter() {
    if let Some(ref button) = c.downcast_ref::<Button>() { ... }
}
// The components would be used again later,
// so consuming them is not a solution
```

Thank you,

**Comment by sfackler** [comment]
downcast_ref is already available on &Any: https://doc.rust-lang.org/std/any/trait.Any.html#method.downcast_ref

**Comment by hkcorac** [comment]
Thank you, I know that function. There's a small issue that it just downcasts to `Box<Trait>` (not a concrete type). I think I'll research more.
