### ISSUE TITLE
panic_implementation: Error message talks about the panic_impl lang item when missing

### ISSUE THREAD

**Issue by phil-opp** [rust-lang/rust#51341]
If the new [`panic_implementation` attribute](https://github.com/rust-lang/rust/pull/50338) is missing, the error message mentions the a `panic_impl` lang item:

```
error: language item required, but not found: `panic_impl`
```

Instead it should probably mention that a `panic_implementation` function is missing.

**Edit:** Seems like I didn't read it carefully enough. The error message doesn't mention the old `panic_fmt` language item, but a new `panic_impl` language item. Either way, a error message mentioning the `panic_implementation` attribute would be better.

**Comment by japaric** [comment]
Under the hood we have replaced the old `panic_fmt` with a new `panic_impl` lang item but this is an implementation detail of `#[panic_implementation]`. I think we can special case the error message for missing `panic_impl` to, instead, mention `#[panic_implementation]` but, off the top of my head, I don't know where that would be in the code base.
