### ISSUE TITLE
Impl enum variants

### ISSUE THREAD

**Issue by hkcorac** [rust-lang/rust#51371]
Hi,

To use generics in collections, I have to wrap objects inside `Box`. Later to get back the concrete types, I can use `Any::downcast_ref()`. However that function can't be used with `match`.

So currently I'm using this way:

```rust
enum Component {
    Button(Button),
    Label(Label),
}

struct Button;
struct Label;
```

`Component` can be easily put in a collection. And it's more convenient when using with `match`. However as you can see, it doubles the names.

May I ask if you could consider adding `impl` for enum variants? So above code can be refactored like this:

```rust
// I added some more fields for the next match example
enum Component {
    Button { width: u32, height: u32, },
    Label { visible: bool, },
}

impl Component::Button {
    fn desc(&self) -> String {
        format!("Button size: {}x{}", self.width, self.height)
    }
}
impl Component::Label {
    fn other_desc(&self) -> String {
        format!("Label is visible: {}", self.visible)
    }
}

match component {
    Component::Button as b => ...,
    Component::Label as l => ...,
}
```

Currently I can't think of how docs work. I'm not sure if docs can apply to `impl` block.

I really think this is a great feature...

Thank you,

---

**Edited**

Updated examples.

**Comment by frewsxcv** [comment]
Thanks for the suggestion! This will require an RFC – please file an issue here: https://github.com/rust-lang/rfcs/issues

**Comment by hkcorac** [comment]
@frewsxcv 

Really thank you. If you didn't suggest me to file an RFC issue, I would just shrug it off  :-D

Here's the RFC issue: <https://github.com/rust-lang/rfcs/issues/2465>
