### ISSUE TITLE
[rustdoc] unclear experimental api notes

### ISSUE THREAD

**Issue by liigo** [rust-lang/rust#51387]
Which API is a nightly-only experimental API? The one followed by the note, or the one it follows? It's not very clear to me.

![notes](https://user-images.githubusercontent.com/346530/41019431-30f2e472-6991-11e8-888a-c35272b554a5.png)

**Comment by hellow554** [comment]
You are right. Any ideas how to improve it?
One solution could be an indention on the same level as the methodcomment is.

![grafik](https://user-images.githubusercontent.com/921462/41021223-f1f61ba2-6965-11e8-9e49-8c199f63a920.png)

Any other ideas?

**Comment by liigo** [comment]
How about ...

> `escape_debug` is a nightly-only experimental API

or

>  🡹⇪↑⇪This is a nightly-only experimental API

**Comment by QuietMisdreavus** [comment]
It doesn't seem like the indentation fix is actually doing anything for the issue you're describing. You seem to have more of an issue about the unstable banner appearing outside the "folded" docs, creating a situation where it's not obvious which function declaration it's attached to, at least when everything's folded up. Would folding the unstable banner inside the docs help?

**Comment by hellow554** [comment]
You are totaly right, I didn't even noticed it! That would be good as well, but then you have to explictly unfold the item (if you folded all items, for example with the keyboard) to see, that it is unstable. 
So I am a little bit indecisive. One may want to hide the unstable box, but you also should always be able to see, that that one is unstable? :| Hmmm... @GuillaumeGomez help! :D

**Comment by liigo** [comment]
How about tag it with `experimental`/`unstable`/`0.0.0` ? (and a popup tooltip)
![exp](https://user-images.githubusercontent.com/346530/42200601-9e590150-7ec6-11e8-8601-610e644bbc0e.png)

**Comment by hellow554** [comment]
I really like the expiremental flag. `0.0.0` is not that expressive I think. Or instead of experimental nightly-only? Or use a yellow-ish background?

**Comment by GuillaumeGomez** [comment]
We can't put it on the same line, it's already super loaded.

**Comment by GuillaumeGomez** [comment]
This isn't the issue. In case you have a super long function/trait/whatever name, it'll be very ugly and difficult to read. This line is at its max length so we'll have to find another location.
