### ISSUE TITLE
Make ./x.py errors more machine-grep-able

### ISSUE THREAD

**Issue by mark-i-m** [rust-lang/rust#51385]
We should systematically make all errors emitted by ./x.py more grep-able. This will make life easier for @TimNN and other bots.

**Comment by mark-i-m** [comment]
Yes, I mostly mean compile and test failures -- anything that would fail a Travis build. Surprisingly, these are not as easy to find as one might expect, since TimNNBot often gives not-very-helpful snippets (e.g. too much or too little, such as https://github.com/rust-lang/rust/pull/51335#issuecomment-394215712).

Instead we should print something like "[ERROR START]" and "[ERROR END]" around the portions we want bots to pick up.

**Comment by Mark-Simulacrum** [comment]
The bot isn't based on start/stop lines iirc, so I'm not sure that's the right approach. @timnn probably knows better than me, though.

**Comment by hellow554** [comment]
One way could be `--output-format=json|xml|...`. 
I mean, the effort to do this is quite high, but you have to decide if it's worth it.

**Comment by mark-i-m** [comment]
There doesn't seem to be high demand for this. Shall I close the issue?
