### ISSUE TITLE
Missing copyright notice in the MIT / APACHE license

### ISSUE THREAD

**Issue by MaikKlein** [rust-lang/rust#51390]
The [LICENSE-APACHE](https://github.com/rust-lang/rust/blob/master/LICENSE-APACHE#L178-L189) misses the copyright notice.

And the [MIT](https://opensource.org/licenses/MIT) license also seems to [miss a copyright notice](https://github.com/rust-lang/rust/blob/master/LICENSE-MIT#L1).

I am not a lawyer and I don't know if this is necessary.

**Comment by joshtriplett** [comment]
Yes, per the discussion on https://github.com/rust-lang/rust/pull/43498 this was intentional.
