### ISSUE TITLE
"explicit predicates of" and "predicates of" have the same dep-node

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#51409]
Both the `explicit_predicates_of` and `predicates_of` queries have the same dep-node:

https://github.com/rust-lang/rust/blob/c131bdcaff68d35f96e954baac4340206779335f/src/librustc/ty/maps/mod.rs#L104-L105

This causes failures when the `infer_outlives_requirements` feature is used with incremental compilation. What needs to be done to fix this is the following:

1. First, create a test.
2. Second, create a new dep-node `ExplicitPredicatesOfItem` for this query.

### Test

If we add a test in `src/test/incremental` sort of like this, it ought to fail:

```rust
// revisions: one 

// Regression test that `infer_outlives_predicates` can be used with
// incremental without an ICE.

#![feature(infer_outlives_requirements)]

struct Foo<'a, T> {
  x: &'a T 
}

fn main() { }
```

### New dep-node

To make a new dep-node, you want to copy and paste this variant here:

https://github.com/rust-lang/rust/blob/c131bdcaff68d35f96e954baac4340206779335f/src/librustc/dep_graph/dep_node.rs#L502

The compiler should then lead you on a little tour of what else needs to be modified.

cc @toidiu

**Comment by Smibu** [comment]
This can be closed; the `fix` message format of #51467 was slightly wrong so GitHub left this open.
