### ISSUE TITLE
libstd/sys/redox/os.rs: unused static variable

### ISSUE THREAD

**Issue by nodakai** [rust-lang/rust#51419]
https://github.com/rust-lang/rust/blob/master/src/libstd/sys/redox/os.rs#L33

```rust
const TMPBUF_SZ: usize = 128;
static ENV_LOCK: Mutex = Mutex::new();
```

Could anybody confirm if they can safely be removed?  It looks like they were copy-and-pasted from `unix/os.rs` but I'm not familiar with Redox.

**Comment by varkor** [comment]
Fixed in #51555.
