### ISSUE TITLE
[feature]  Implement `Borrow` for `Rc<Box<T>>` (or in a generic transitive manner)

### ISSUE THREAD

**Issue by cipriancraciun** [rust-lang/rust#51438]
Currently `Borrow` is implemented for both `Rc` and `Box` individually, however sometimes one uses `Rc<Box<T>>` and needs it to have `Borrow` implemented.

My concrete use-case is the following:  I'm using `Rc<Box<str>>` as the backing value of symbols in a Scheme interpreter, and I need to have a `HashMap<Rc<Box<str>>, Value>` be addressable for any `&str`.  However the compiler complains that it can't borrow an `str` from `Rc<Box<str>>`.  Unfortunately one can't implement `Borrow` for those as both are part of `std`, and thus "external" from the developer's crate.

Therefore my feature request is to implement `Borrow` at least for a few useful combinations of `Rc`, `Arc`, `Box`, and `T` and `Borrow<T>` (so that one could use `Rc<Box<String>>` and still have it `Borrow<str>`.

----

Generalizing upon that, perhaps a "transitive" `Borrow` implementation might help cover all these cases, say for a depth up to 4 or 5.

**Comment by Centril** [comment]
In this case, I think you could use `HashMap<Rc<str>, Value>` instead, which as a bonus avoids an indirection:
```rust
use std::collections::HashMap;
use std::rc::Rc;

fn main() {
    let mut hm: HashMap<Rc<str>, ()> = HashMap::new();
    hm.insert("foo".into(), ());
    println!("{:?}", hm.get("foo"));
    // output = Some(())
}
```

**Comment by cipriancraciun** [comment]
In certain cases perhaps one could use `Rc<str>`, but in general if one has a `Box<Trait>`, one will eventually need an `Rc<Box<Trait>>`.  (Moreover the "transitive" feature would cover other things such as `Rc<RefCell<Box<Trait>>>` or similar.)

----

Moreover currently transforming an `Box<Trait>` into an `Rc<Trait>` would require an extra allocation and copy, which is less efficient than switching a `String` to `Box<str>` and then wrapping it into an `Rc<Box<str>>` (both require the allocation for `String/Box` and the allocation for `Rc`, but the later eludes the extra copy, and thus re-uses the memory of the existing `String/Box`.)

See the implementations for various `From<T> for Rc<T>`:
* https://doc.rust-lang.org/src/alloc/rc.rs.html#1125-1137 -- does a copy followed by a drop of the original vector;
* https://doc.rust-lang.org/src/alloc/rc.rs.html#1109-1114 -- does again a copy followed by a drop;
* https://doc.rust-lang.org/src/alloc/rc.rs.html#683

**Comment by Enselic** [comment]
Triage: The general case already works, doesn't it? The below program prints `1 2 1`.

```rust
use std::rc::Rc;

trait Trait {
    fn foo(&self) -> u32;
}

struct A;

impl Trait for A {
    fn foo(&self) -> u32 {
        1
    }
}

struct B;

impl Trait for B {
    fn foo(&self) -> u32 {
        2
    }
}

fn main() {
    let b: Box<dyn Trait> = Box::new(A);
    let rc: Rc<dyn Trait> = Rc::new(B);
    let rcb: Rc<Box<dyn Trait>> = Rc::new(Box::new(A));
    println!("{} {} {}", b.foo(), rc.foo(), rcb.foo());
}
```

I don't quite understand when a `Rc<Box<T>>` or `Box<Rc<T>>` would be needed, so would you mind giving a code example where they are needed? Both `Box` and `Rc` manage heap-allocated data, and containing one in the other just seems to add unnecessary indirection. But I might be missing something.

**Comment by Enselic** [comment]
> It's also a low priority item, as it only simplifies the life of the developer, thus if this can't be easily implemented, you can even close this issue with WONTFIX.

Thank you for getting back to me with a clarification. It can probably be implemented, but since Box&lt;Rc&lt;T>>, Rc&lt;Box&lt;T>>, etc is an [anti-pattern](https://rust-lang.github.io/rust-clippy/master/index.html#/redundant_allocation), and since it seems counter-productive to make anti-patterns easier to use, let's close this as won't fix.
