### ISSUE TITLE
Issue with E0381 and using a boolean to track initialization

### ISSUE THREAD

**Issue by mtreinish** [rust-lang/rust#51447]
When declaring a variable outside of a for loop and tracking whether it's set with a boolean and only accessing that inside an if block isn't track properly and will raise an E0381 uninitialized variable even though the variable will also have an assigned variable when it's accessed. I came up with a small reproduce case here:

```
fn main() {
    let mut time;
    let mut time_found = false;
    for i in 1..10 {
        if i == 1 {
            time_found = true;
            time = i;
        }
    }
    if time_found {
        let a = time + 1;
    }
}
```

Will not build because of E0381 on the `let a = time + 1;` line. However, because time is only being used inside the if block it will always have a defined value it's never going to be uninitialized there. 

While this synthetic case doesn't make much sense in the real world, I'm hitting this in a more complex example where using a boolean to track the the state of having the value defined for a variable like this was the only way I could think to ensure the value was always set. Especially because I can't come up with a sane value to initialize for the type of this variable.

I'm new to rust so I'm not sure if there is something obvious I'm missing here, but this seems like a bug in that the compiler isn't able to track this case properly.

## Meta

`rustc --version --verbose`:
rustc 1.26.2
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-linux-gnu
release: 1.26.2
LLVM version: 6.0

**Comment by DutchGhost** [comment]
Rustc can not tell if the value was set or not, and therefore fails to compile (oh no, you *might* be reading uninitialized memory!)

Maybe you could try using the Option type, where Some(T) indicates the value was set, and None that no value was set.

Note that many functions and methods return the Option type, for example the .find() method on Iterators, it returns Some(T) when the value was found, and None if the value was not found

**Comment by ishitatsuyuki** [comment]
This doesn't look like a thing we can action on the language side.

Relationship between separate variables is

1. Hard to be proven by machines
2. Error prone for humans

And this is what the type systems try to avoid. In short, just use the Option type.

**Comment by Mark-Simulacrum** [comment]
I agree that it's unlikely we could practically catch this in more cases. I'd also worry that most such attempts would be error-prone, in terms of letting you use variables that have uninitialized memory. This approach (specifically) where a boolean is used to track the status of another variable seems like the poster-child case where an Option is the right approach (and will likely compile to the same code, I'd imagine).

As such, I'm going to close this issue as out of scope and not practical to implement.
