### ISSUE TITLE
Remove the libc shim

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#51465]
PR #51440 has removed the need for the shim. Now the only reason to keep it is so that we can have and enable the rustbuild feature, but this can be done by rustc internal code depending on libc as well. For this we require a change of the upstream libc Cargo.toml though as rustbuild currently is not included there.

**Comment by stokhos** [comment]
Hi est31,  
Do I  need to triage this issue, since you have already referenced to an older issue.

**Comment by Mark-Simulacrum** [comment]
Yep, we'll want to label this as C-cleanup and A-rustbuild, which I've now done.
