### ISSUE TITLE
Unable to fall through past $:lifetime matcher

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust#51477]
This is similar to the same buggy behavior we saw for `$:ident` matchers fixed in 1.20.0.

For example in Rust 1.19 the following code fails to compile with the message `"expected ident, found @"`, but correctly prints `ident` followed by `other` as of 1.20.

```rust
macro_rules! m {
    ($ident:ident) => { println!("ident"); };
    ($other:tt) => { println!("other"); };
}

fn main() {
    m!(ident);
    m!(@);
}
```

The `$:lifetime` matcher is currently broken in the same way.

```rust
macro_rules! m {
    ($lifetime:lifetime) => { println!("lifetime"); };
    ($other:tt) => { println!("other"); };
}

fn main() {
    m!('lifetime);
    m!(@);
}
```

```
error: expected a lifetime, found `@`
 --> src/main.rs:8:8
  |
8 |     m!(@);
  |        ^
```

rustc 1.28.0-nightly (2a0062974 2018-06-09)

@sgrif @durka

**Comment by dtolnay** [comment]
The ident issue was #27832, so mentioning @kennytm who fixed that one in #42913. Would you be interested in taking a look at this similar case?

**Comment by kennytm** [comment]
Duplicate of #50903. @jrlusby should still be working on it I think?

**Comment by dtolnay** [comment]
Thanks! Let's continue to track this as part of #50903.
