### ISSUE TITLE
FR: Support flagfile in rustc (`@file` syntax)

### ISSUE THREAD

**Issue by damienmg** [rust-lang/rust#51473]
Hello,

In the process of thinking how to better integrate Bazel & RLS (bazelbuild/rules_rust#95) I found out that `rustc` doesn't support flag file, that is file that contains a list of arguments that is to be parsed by the compiler. Because the way Bazel works, it has crates that can live in various place in the system. It creates symlink at the moment to put everything in one directory but that is not required except that the number of -L flags will ends up being large without it.

It's a very common way of passing options in standard compilers (gcc, clang, javac).

Related RFC: rust-lang/rfcs#2136 (build system integration)

**Comment by Mark-Simulacrum** [comment]
Implemented; tracking issue: https://github.com/rust-lang/rust/issues/63576.
