### ISSUE TITLE
Match is not smart enough to deduce the only possible catch-all type

### ISSUE THREAD

**Issue by Disasm** [rust-lang/rust#51479]
This example compiles successfully:
```
fn f2() -> Result<i32, String> {
    unimplemented!()
}

fn f1() -> Result<i64, String> {
    match f2() {
        Ok(value) => Ok(value as i64),
        Err(err) => Err(err),
    }
}
```

However, this example does not:
```
fn f2() -> Result<i32, String> {
    unimplemented!()
}

fn f1() -> Result<i64, String> {
    match f2() {
        Ok(value) => Ok(value as i64),
        err => err,
    }
}
```

Obviously, `err` can only be of `Err(e)` kind so it's correct to return it from `f1()`.

**Comment by estebank** [comment]
This is because `err` is of type `Result<i32, String>::Err`, which doesn't autocast to `Result<i64, String>::Err`. They are in effect two different types.

That being said, for this case the idiomatic code would be

```
fn f1() -> Result<i64, String> {
    f2().map(|v| v as i64)
}
```
or
```
fn f1() -> Result<i64, String> {
    Ok(f2()? as i64)
}
```

**Comment by dtolnay** [comment]
The `Err(err) => Err(err)` match arm is not a no-op, it is doing:

```rust
match f2() {
    Ok(value) => Ok(value as i64),
    Err::<i32, String>(err) => Err::<i64, String>(err),
}
```

Accepting `err => err` when only the error types are the same may break code in which `err => err` establishes that the ok types are the same. For example:

```rust
fn f2<T>() -> Result<T, String> {
    unimplemented!()
}

fn f1() -> Result<i64, String> {
    match f2() {
        Ok(value) => Ok(value as i64),
        err => err,
    }
}
```

This compiles today but an implicit conversion from `Err::<T1, String>` to `Err::<T2, String>` would make the choice of `T` type parameter for `f2` ambiguous.

**Comment by estebank** [comment]
Cc #47560

**Comment by Spoonbender** [comment]
Triage: no change

Since [the reason is known and is a non-bug](https://github.com/rust-lang/rust/issues/51479#issuecomment-396092392), can we close this issue?

**Comment by estebank** [comment]
@Spoonbender potentially, but I would like it if we had a structured suggestion for [the presented cases](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=e21b8b4c30f0d74d2a5c5c8e88dd21a1), but I understand it might be too niche of a situation to make it worth it to handle it.
