### ISSUE TITLE
Deprecated attribute on trait impls is useless

### ISSUE THREAD

**Issue by Havvy** [rust-lang/rust#51470]
I'd expect the following code to warn, but it doesn't:

```rust
struct Struct;

trait Trait {
  fn f(&self);
}

#[deprecated(since="0.0.0" note="example deprecation")]
impl Struct for Trait {
  fn f(&self) {}
}

fn main() {
  Struct.f();
}
```

Note: It **is** an error to put the `deprecated` attribute on the `fn f` in the `impl` itself.

**Comment by Havvy** [comment]
This should be A-Trait, not A-Impl-Trait.

**Comment by kennytm** [comment]
Duplicateof #39935.
