### ISSUE TITLE
Add a dynamic heap-allocated buffer type to alloc

### ISSUE THREAD

**Issue by zesterer** [rust-lang/rust#51494]
I'm sure this has been requested many times before, but I couldn't seem to find another issue related to the topic.

Currently, when requiring a buffer for something such as network socket I/O, it is conventional to use `Vec<u8>` to allocate a buffer of the necessary size to contain the packet.

There are two problems with this approach.

1) Newcomers to Rust, confused by the lack of a dynamic array type, tend to use `Vec::with_capacity(n)` to allocate enough space for their buffer. Since the vector's length remains at 0 however, the slice returned by `.as_mut_slice()` also has length zero, leading to unintended (and surprisingly subtle) bugs when a supposedly incorrect number of bytes are retrieved from a socket.

2) An alternative solution is to use the `vec!` macro to produce a zero-filled vector of the intended size like `let mut buf = vec![0u8; n]`. This intuitively feels like an inefficient way to allocate such a buffer since it is unnecessarily zero-filled before use. I'm unsure whether the compiler is capable of optimising this away, but it not an ergonomic solution regardless.

Using a vector to solve this problem does not feel clean or ergonomic: it feels like a hack to account for a yet-to-be-implemented feature.

I am aware of the existence of the experimental `RawVec` type, but as far as I know the intended use case is very different.

Instead, I suggest a `Buf<T: Copy + Clone>` type be added to `alloc` that provides an interface not dissimilar in nature to `Box<T>`. The type would not be required to zero-fill its contents upon instantiation.

```rust
let mut buf = Buf::with_length(n);
my_socket.read(&mut buf);
```

as an ergonomic alternative to

```rust
let mut buf = vec![0u8; n]
my_socket.read(buf.as_mut_slice());
```

**Comment by remexre** [comment]
Problem: Not all `Copy` types are required to have all bitpatterns be valid. For example, `&'static str`.

**Comment by zesterer** [comment]
@remexre Is there a trait implemented only by POD types such as primitives that could be used to constraint this?

**Comment by remexre** [comment]
Not that I'm aware of; an unsafe POD auto trait could probably be created, but that's solidly in RFC-required territory.

**Comment by ishitatsuyuki** [comment]
Properly initializing is essential for safe behaviour. If you are sure that its value is never read before written (and want to trade off performance for safety), why not `vec![mem::uninitialized();n]`?

**Comment by zesterer** [comment]
@ishitatsuyuki If the internal type is an integer primitive, is an undefined value considered an unsafe value?

**Comment by rkruppe** [comment]
Precise answers will have to wait for finalized unsafe code guidelines, but for numerous it's basically certain that there will be some ways to trigger UB by handling "uninitialized values" carelessly, even "uninitialized `u8`s". It's best to assume that any and all operations on uninitialized memory are UB, save for except initializing it with `ptr::write` and friends. That's what the [reference currently states](https://doc.rust-lang.org/reference/behavior-considered-undefined.html), for example.

**Comment by ishitatsuyuki** [comment]
@zesterer Yes, especially on IA64 uninitialized registers has a different value. It's better not to rely on it.

Also, zero wiping memory is somewhat cheap (and sometimes free), and there's a `calloc` function dedicated for such allocations.

**Comment by zesterer** [comment]
Okay. Those are all reasonable point that I fully accept. But that doesn't seem like a barrier to creating a `Buf` type implemented for the integer primitives, does it?

**Comment by rkruppe** [comment]
I don't understand where you're coming from. Perhaps that's because you've not given a lot of detail about *how* this `Buf` type would work. Without that, all I can say is: If there is any way it would give safe code a way to read uninitialized memory of any type (integer primitive or not), then it's unsound right now and will very likely remain unsound as Rust evolves.

**Comment by rkruppe** [comment]
To elaborate, the example at the start:

```rust
let mut buf = Buf::with_length(n);
my_socket.read(&mut buf);
```

implies that this would allow reading uninitialized memory (because you can apparently create such an uninitialized buffer and turn it into a slice of non-zero length, all in safe code). I don't want to jump to conclusions, you're welcome to lay out a specific API and argue for its soundness, but if you do this you'll have to deal with the fact that uninitialized memory is UB to read, period.

**Comment by zesterer** [comment]
I imagined an interface that would look and be implemented like the follows.

```
use std::ops::{Deref, DerefMut};
use std::net::UdpSocket;

pub trait BufItem: Clone {
    fn empty() -> Self;
}

impl BufItem for u8 { fn empty() -> Self { 0 } }
impl BufItem for u16 { fn empty() -> Self { 0 } }
impl BufItem for u32 { fn empty() -> Self { 0 } }
// etc...

pub struct Buf<T: BufItem> {
    data: Vec<T>,
}

impl<T: BufItem> Buf<T> {
    pub fn with_length(len: usize) -> Buf<T> {
        Buf {
            data: vec![T::empty(); len],
        }
    }
}

impl<T: BufItem> Deref for Buf<T> {
    type Target = [T];
    fn deref<'a>(&'a self) -> &'a [T] {
        &self.data
    }
}

impl<T: BufItem> DerefMut for Buf<T> {
    fn deref_mut<'a>(&'a mut self) -> &'a mut [T] {
        &mut self.data
    }
}




fn test() {
    let sock = UdpSocket::bind("127.0.0.1: 5900").unwrap();

    let mut buf = Buf::with_length(4096);
    sock.recv(&mut buf);
}
```

**Comment by zesterer** [comment]
It's considerably more ergonomic. Using vectors (which intuitively are structures that change size) feels ugly and strange as the idiomatic solution to this problem. It also solves the problem I mention in my original post relating to zero-length vectors.

**Comment by sfackler** [comment]
This seems like something that should be built out in a third party library first.

**Comment by jonas-schievink** [comment]
Closing in favor of an external crate / an RFC once there has been more out-of-tree experimentation with this. Let me know if you think this should be reopened.
