### ISSUE TITLE
`attempt to subtract with overflow` on obviously OK expression

### ISSUE THREAD

**Issue by chengyuhui** [rust-lang/rust#51495]
```rust
const MAX_DATA_LEN: usize = 2^14 - 16;
``` 
yields `attempt to subtract with overflow` 

If replace 2^14 with 16368 (the same value), everything works fine.

![image](https://user-images.githubusercontent.com/1381736/41232480-1740a79a-6db9-11e8-937b-05c2b7c7d77d.png)

```
nightly-x86_64-pc-windows-msvc (default)
rustc 1.28.0-nightly (8afb89493 2018-06-08)
```

**Comment by nikic** [comment]
`^` is the [xor operator](https://en.wikipedia.org/wiki/Exclusive_or), not the power operator. Rust does not have a built-in power operator. For powers of two you can use `1 << 14`. For general powers you can use the `pow` method: `2.pow(14)`.

**Comment by chengyuhui** [comment]
Sorry for such a stupid question..
