### ISSUE TITLE
Logo contribution

### ISSUE THREAD

**Issue by Honshubloc** [rust-lang/rust#51503]
Hi :)
I´m wondering if you could be interested in a new fresh logo for your site https://www.rust-lang.org
I´m around here searching for cool open source projects to offer some graphic contributions for free and i found yours :) once i´m not an expert programmer :P this is my way to be useful for the community.
Please tell me if you are interested.
Regards

**Comment by cuviper** [comment]
In my opinion, the Rust logo is pretty well established and doesn't need to be refreshed yet.  However, there was a similar sort of thread in the users forum for the broader community:
https://users.rust-lang.org/t/projects-in-need-of-designers/17191

**Comment by Honshubloc** [comment]
Thank you for your feedback.
I will take a look into that thread ;)
Regards

**Comment by steveklabnik** [comment]
Since this is not a bug, I'm going to close. Thanks!
