### ISSUE TITLE
Renamed lints in 1.27 beta

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#51501]
**Please note it's unlikely this change will be reverted before the release.**
This issue exists mostly to notify crate authors about the change.

In the next release of Rust, 1.27.0, a few lints will be renamed to be consistent with the other names and [RFC 344](https://github.com/rust-lang/rfcs/blob/master/text/0344-conventions-galore.md#lints). You can find the full rationale for the change and the list of changed lints in PR https://github.com/rust-lang/rust/pull/50879.

Your crates have `#[deny(warnings)]` in the build, so the change broke their build. If you want to allow the lint while still supporting old compilers you can use:

```
#![allow(unknown_lints, renamed_and_removed_lints, old_lint, new_lint)]
```

* [elastic](https://crates.io/crates/elastic) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.27-9/beta-2018-06-04/reg/elastic-0.20.10/log.txt)) cc @KodrAus
* [itm](https://crates.io/crates/itm) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.27-9/beta-2018-06-04/reg/itm-0.2.1/log.txt)) cc @japaric
* [libjwt](https://crates.io/crates/libjwt) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.27-9/beta-2018-06-04/reg/libjwt-0.1.0/log.txt)) cc @LightDiscord
* [libpasta](https://crates.io/crates/libpasta) regressed from stable to beta ([build log](http://cargobomb-reports.s3.amazonaws.com/beta-1.27-9/beta-2018-06-04/reg/libpasta-0.1.0-rc1/log.txt)) cc @samscott89
* [mqtt](https://crates.io/crates/mqtt) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.27-9/beta-2018-06-04/reg/mqtt-0.1.4/log.txt)) cc @flier
* [sherpa](https://crates.io/crates/sherpa) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.27-9/beta-2018-06-04/reg/sherpa-0.4.0/log.txt)) cc @mikeastock
* [slack-hook](https://crates.io/crates/slack-hook) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.27-9/beta-2018-06-04/reg/slack-hook-0.6.0/log.txt)) cc @compressed
* [sudo_plugin](https://crates.io/crates/sudo_plugin) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.27-9/beta-2018-06-04/reg/sudo_plugin-1.1.0/log.txt)) cc @stouset
* [ptx-builder](https://crates.io/crates/ptx-builder) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.27-9/beta-2018-06-04/reg/ptx-builder-0.3.6/log.txt)) cc @denzp
* [serde_qs](https://crates.io/crates/serde_qs) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.27-9/beta-2018-06-04/reg/serde_qs-0.4.0/log.txt)) cc @samscott89
* [japaric/itm](https://github.com/japaric/itm) (GitHub repo) regressed from stable to beta ([build log](http://cargobomb-reports.s3.amazonaws.com/beta-1.27-9/beta-2018-06-04/gh/japaric.itm/log.txt)) cc @japaric

**Comment by petrochenkov** [comment]
The root reason for all the regressions is actually `error-chain`, so everything will be fixed if https://github.com/rust-lang-nursery/error-chain/pull/247 is merged and minor version of `error-chain` is released.

Does anybody know who currently has rights in that repo? @Yamakaky and @brson seem to be unavailable.

**Comment by est31** [comment]
> Does anybody know who currently has rights in that repo? @Yamakaky and @brson seem to be unavailable.

What matters far more than git access is who has crates.io access which according to the crates.io page is @alexcrichton @Yamakaky and @brson . Not sure how alex can be reached before the 1.27 release is out.

**Comment by Dylan-DPC** [comment]
> Not sure how alex can be reached before the 1.27 release is out.

This is why we created the [Rust Bus Organisation](https://users.rust-lang.org/t/bus-factor-1-for-crates/17046/30). In such emergency cases, we can push releases on the owner's behalf.

**Comment by KodrAus** [comment]
In my opinion, this is the kind of thing that can happen with `#[deny(warnings)]`, and while fixing it would be nice in the meantime there's also the solution of not denying warnings. I don't think it's worth bothering Alex over.

**Comment by Yamakaky** [comment]
To be honest, I'm not really programming in rust these time (following the news though),so I kinda left error-chain behind. `failure` being there, I'm not sure it's worth it to maintain error-chain.

**Comment by pietroalbini** [comment]
@Yamakaky 1.27 release is next week, if you have time to cut out a new error-chain release it would be awesome!
