### ISSUE TITLE
#[repr(align)] still marked as expermental

### ISSUE THREAD

**Issue by dragonite44** [rust-lang/rust#51517]
I'm trying to compile code that uses the `crossbeam-utils` crate, which uses the `#[repr(align)]` attribute.  On nightly linux, the crate compiles fine. But on nightly windows, rustc throws an error about the attribute still being experimental.
```
error[E0658]: the struct `#[repr(align(u16))]` attribute is experimental (see is
sue #33626)
  --> C:\Users\Kyle\.cargo\registry\src\github.com-1ecc6299db9ec823\crossbeam-ut
ils-0.4.0\src\cache_padded.rs:19:1
   |
19 | #[repr(align(64))]
   | ^^^^^^^^^^^^^^^^^^
   |
   = help: add #![feature(repr_align)] to the crate attributes to enable

error[E0658]: non-string literals in attributes, or string literals in top-level
 positions, are experimental (see issue #34981)
  --> C:\Users\Kyle\.cargo\registry\src\github.com-1ecc6299db9ec823\crossbeam-ut
ils-0.4.0\src\cache_padded.rs:19:1
   |
19 | #[repr(align(64))]
   | ^^^^^^^^^^^^^^^^^^
   |
   = help: add #![feature(attr_literals)] to the crate attributes to enable

error: aborting due to 2 previous errors
```
I can't install rust on another windows computer because the rustup installer is broken. So I'm wondering if this is a bug with my installation or not.

### Meta
I'm using `rustc 1.28.0-nightly (1d4dbf488 2018-06-11)` on both `nightly-x86_64-unknown-linux-gnu` and `nightly-x86_64-pc-windows-msvc`

**Comment by kennytm** [comment]
Could you run `cargo rustc -- -vV` on the directory of your package to ensure the nightly rustc is used?

**Comment by dragonite44** [comment]
`cargo rustc -- -vV` doesn't show anything new, just the compilation errors. Running `cargo build --verbose` returns
```
   Compiling crossbeam-utils v0.4.0
     Running `rustc --crate-name crossbeam_utils C:\Users\Kyle\.cargo\registry\src\github.com-1ecc6299db9ec823\crossbeam-utils-0.4.0\src\lib.rs
 --crate-type lib --emit=dep-info,link -C debuginfo=2 --cfg "feature=\"default\"" --cfg "feature=\"use_std\"" -C metadata=bef58e98434bc762 -C e
xtra-filename=-bef58e98434bc762 --out-dir C:\Users\Kyle\Desktop\test\target\debug\deps -L dependency=C:\Users\Kyle\Desktop\test\target\debug\de
ps --cap-lints allow`
error[E0658]: the struct `#[repr(align(u16))]` attribute is experimental (see issue #33626)
  --> C:\Users\Kyle\.cargo\registry\src\github.com-1ecc6299db9ec823\crossbeam-utils-0.4.0\src\cache_padded.rs:19:1
   |
19 | #[repr(align(64))]
   | ^^^^^^^^^^^^^^^^^^
   |
   = help: add #![feature(repr_align)] to the crate attributes to enable

error[E0658]: non-string literals in attributes, or string literals in top-level positions, are experimental (see issue #34981)
  --> C:\Users\Kyle\.cargo\registry\src\github.com-1ecc6299db9ec823\crossbeam-utils-0.4.0\src\cache_padded.rs:19:1
   |
19 | #[repr(align(64))]
   | ^^^^^^^^^^^^^^^^^^
   |
   = help: add #![feature(attr_literals)] to the crate attributes to enable

error: aborting due to 2 previous errors

error: Could not compile `crossbeam-utils`.

Caused by:
  process didn't exit successfully: `rustc --crate-name crossbeam_utils C:\Users\Kyle\.cargo\registry\src\github.com-1ecc6299db9ec823\crossbeam
-utils-0.4.0\src\lib.rs --crate-type lib --emit=dep-info,link -C debuginfo=2 --cfg feature="default" --cfg feature="use_std" -C metadata=bef58e
98434bc762 -C extra-filename=-bef58e98434bc762 --out-dir C:\Users\Kyle\Desktop\test\target\debug\deps -L dependency=C:\Users\Kyle\Desktop\test\
target\debug\deps --cap-lints allow` (exit code: 101)
```

**Comment by kennytm** [comment]
☹️ comment out the `[dependencies]` section from Cargo.toml and check again? Or maybe just run `rustc -vV` while inside that folder.

**Comment by dragonite44** [comment]
```
rustc 1.25.0-nightly (4e3901d35 2018-01-23)
binary: rustc
commit-hash: 4e3901d35f6a8652f67111e7272263c9e62ab3e1
commit-date: 2018-01-23
host: x86_64-pc-windows-gnu
release: 1.25.0-nightly
LLVM version: 4.0
```
Sorry I didn't get the right command.

**Comment by kennytm** [comment]
Looks like your nightly is actually 1.25.0, not 1.28.0. 

You mentioned "rustup installer is broken", but do you already have rustup installed? Try running:

* rustup self update
* rustup update

and check again?

**Comment by dragonite44** [comment]
I updated nightly tonight and did it again, no change. rustc -Vv still shows 1.25 nightly.

**Comment by jonas-schievink** [comment]
I've hit this on Rust 1.21.0 on Travis: https://travis-ci.org/jonas-schievink/xml-rpc-rs/jobs/391259820

**Comment by sfackler** [comment]
@jonas-schievink `#[repr(align)]` isn't stable in 1.21.0.

**Comment by jonas-schievink** [comment]
@sfackler Ah, thanks. Looks like some crate didn't bump its version correctly, then.

**Comment by kennytm** [comment]
@dragonite44 Please run `rustup override list` and check if that folder is manually overridden to use the outdated nightly.

**Comment by dragonite44** [comment]
@kennytm I have no overrides on my entire system

**Comment by kennytm** [comment]
@dragonite44 Heh. Could you ensure cargo and rustc are managed by rustup?

1. Run `which rustc` (in bash) or `where rustc` (in cmd.exe) and check if the correct rustc is selected (it should be at `C:\Users\<yourname>\.cargo\bin\rustc`)
2. If it is managed by rustup, run `rustup toolchain list` and check what toolchains are selected.
3. Verify that:

    * The `RUSTUP_TOOLCHAIN` environment variable is *not* defined
    * There is *no* file named `rust-toolchain` in the current directory

**Comment by dragonite44** [comment]
Thank you @kennytm for all your help.
