### ISSUE TITLE
Unexpected result converting an i64 to an f64

### ISSUE THREAD

**Issue by ruifonseca** [rust-lang/rust#51520]
Hi,

The following program prints:
> f64 = 2.2
> i64 as f64 = 2
> 2.2 - 2 = 0.20000000000000018

```rust
fn main() {
    let flo: f64 = 2.2;
    let int: i64 = 2;
    println!("f64 = {}", flo);
    println!("i64 as f64 = {}", int as f64);
    println!("{} - {} = {}", flo, int, flo - (int as f64));
}
```
Verified on:
> stable-x86_64-unknown-linux-gnu unchanged - rustc 1.26.2 (594fb253c 2018-06-01)

Regards,
Rui

**Comment by jonas-schievink** [comment]
`f64` is a double precision floating-point number. Those cannot accurately represent all numbers, similar to how you can't write `1/3` as a decimal and have to resort to rounding down at the end to get something like `0.3333333`.

In particular, floating-point numbers can't represent `0.1` or `0.2` without rounding, so the result is expected. JavaScript gets the same result, and so does C/C++ when using a `double`.

**Comment by rkruppe** [comment]
Yes, and the reason you're nevertheless getting `f64 = 2.2` as output is: while the number is rounded and not exactly equal to 2.2, Rust (and other languages) prefer the shortest decimal output that results in the same f64 when parsed back (so you can round-trip floats losslessly, but the output isn't always a huge 17+ digit string).

**Comment by ruifonseca** [comment]
@jonas-schievink, @rkruppe, thank you for your clarifications.
Closing the issue ;)
