### ISSUE TITLE
Incorrect suggestion when encountering enum variant where type should be

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#51523]
In cases like the following
https://github.com/rust-lang/rust/blob/ef8cb40c9c03fe60aac47c8736045231633dbdac/src/test/ui/issue-35675.stderr#L39-L46

we suggest using `std::prelude::v1` as an enum because `std::prelude::v1::Ok` is an enum variant. It shouldn't suggest this unless the path as mentioned is assured to be a valid enum (and we should use a `span_suggestion` instead of `help`).

**Comment by euclio** [comment]
I'm trying to work on this, but I'm a bit stuck. I'm trying to modify `is_enum_variant` in librustc_resolve/src/lib.rs to check if the parent def of the given def id is an Enum, but I'm not sure how to actually get the parent def in the context of the resolver. It seems like I could call `self.parent` (?), but then how do I get a `Def` from the `DefId`?

**Comment by estebank** [comment]
Current output:

```
error[E0573]: expected type, found variant `Ok`
  --> $DIR/issue-35675.rs:19:13
   |
LL | fn foo() -> Ok {
   |             ^^
   |             |
   |             not a type
   |             help: try using the variant's enum: `std::result::Result`
```
