### ISSUE TITLE
Micro optimization idea: resue string buffer for FromIterator

### ISSUE THREAD

**Issue by Lucretiel** [rust-lang/rust#51541]
https://github.com/rust-lang/rust/blob/07c415c2154f29d6dce8da0154ef41c8a5497fbf/src/liballoc/string.rs#L1720-L1727

Basically the idea is that, for `impl FromIterator<String> for String`, we reimplement it slightly so that newly returned string reuses and reallocates the buffer of the first string in the iterator. It would look something like this:

```
fn from_iter(iter: I) -> String {
    match iter.next() {
        None => String::new(),
        Some(base) => { base.extend(iter); base }
    }
}
```

Of course, this might not be worth the added complexity– in particular, I'm not sure what the implications are for added branching– so I'm writing this issue to solicit any feedback before creating a PR.

**Comment by ishitatsuyuki** [comment]
I think that it will likely be a reallocation + move which is basically as expensive as allocating a brand new string. Thus this doesn't sound high priority to me; but maybe worth trying :)

**Comment by scottmcm** [comment]
Hmm, I agree that in general it's unlikely that the first string happens to have enough capacity for the whole iterator, so this might be of minimal value in general.

It would, however, be a clear win for a case where there happens to only be one element in the iterator, though, so might be worth doing for that alone.

**Comment by lnicola** [comment]
@Lucretiel Can this be closed?
