### ISSUE TITLE
E0424 short message weirdly confusing

### ISSUE THREAD

**Issue by Havvy** [rust-lang/rust#51547]
This invalid function gives two instances of E0424.

```
fn foo(self: i32) -> i32 { self }
```

```
error[E0424]: expected unit struct/variant or constant, found module `self`
 --> src/main.rs:8:8
  |
L | fn foo(self: i32) -> i32 { self }
  |        ^^^^ `self` value is only available in methods with `self` parameter

error[E0424]: expected value, found module `self`
 --> src/main.rs:8:28
  |
L | fn foo(self: i32) -> i32 { self }
  |                            ^^^^ `self` value is only available in methods with `self` parameter
```

The long diagnostic for this error states "The self keyword was used in a static method." which while slightly wrong in this case (it's a free function, not a method at all), it's more correct than what's emitted by the compiler.

Overall, this diagnostic needs to be cleaned up.

1. In the first instance, the error message should state "`self` parameter can only be declared on methods".
2. In the first instance, the help message should just be removed.
3. In the second instance, it probably shouldn't even be emitted. Possibly check if a parameter was erroneously named `self` and if so, pretend it's a valid variable name in the function. Maybe a `note` pointing out its usage as part of the first emitted error would be okay here?
4. The long error description (in the error index) should say "free function or method".

**Comment by durka** [comment]
I have some related gripes about this error message:

```rust
error[E0424]: expected unit struct/variant or constant, found local variable `self`
  --> expr.rs:18:50
   |
18 |     struct S; impl S { fn foo(self) { let self = 42; } }
   |                                           ^^^^ `self` value is only available in methods with `self` parameter
```

The error seems to have a second meaning, namely "`self` used as an identifier for binding but not in the argument list", and this fires whether or not the method has a `self` parameter. This isn't covered in the `--explain` either. Should it be split it to a different error code?

**Comment by estebank** [comment]
[Current output](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=1339429a8cbfe56e08e71717925c8c64):

```
error: unexpected `self` argument in function
 --> src/lib.rs:1:14
  |
1 | fn foo(self: i32) -> i32 { self }
  |              ^^^ `self` is only valid as the first argument of an associated function

error[E0424]: expected value, found module `self`
 --> src/lib.rs:1:28
  |
1 | fn foo(self: i32) -> i32 { self }
  |                            ^^^^ `self` value is a keyword only available in methods with `self` parameter
```

[The case in the comment](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=cf7499b82a61cac8a055491147f28171) still has the same output.
