### ISSUE TITLE
Small error in documentation example

### ISSUE THREAD

**Issue by cheeeeee** [rust-lang/rust#51546]
I've been going through Rust's documentation to learn the language and I think there might be a small error in one of the examples on [](https://doc.rust-lang.org/book/second-edition/ch05-03-method-syntax.html.)

```
impl Rectangle {
    fn can_hold(&self, other: &Rectangle) -> bool {
        self.width > other.width && self.height > other.height
    }
}
```
`self.width > other.width && self.height > other.height`

should probably be ...

`self.width >= other.width && self.height >= other.height'

If you consider two equal sides are capable of containing other another.  That might depend if you're thinkings in two dimensions or three.

**Comment by Havvy** [comment]
Eh, if I had two squares and tried to put one inside the other, I'd fail and at best, one would be on top of the other.

Though really, both interpretations of "can hold" can be seen as correct, which makes it a bad example function, IMO.

**Comment by cheeeeee** [comment]
Yeah. I guess I wanted to make sure I understood the problem at least. If you were to take two sheets of paper and put them directly on top of one another and cut out a square then each square would be able to exactly container the other since neither square would exceed the other squares boundaries. To be clear this is the example on 5.3 the Method Syntax.

**Comment by steveklabnik** [comment]
> To be clear this is the example on 5.3 the Method Syntax.

The book has its own repo, https://github.com/rust-lang/book, and so bugs against it should be filed over there. Would you mind-re-filing this? I basically agree with @Havvy; both are valid interpretations, and so we should consider changing the example. Thanks!
