### ISSUE TITLE
rust should install also cargo

### ISSUE THREAD

**Issue by psumbera** [rust-lang/rust#51573]
cargo is considered as library and it doesn't deliver Cargo.lock. It's expected that cargo binary is delivered together with rust:

https://github.com/rust-lang/cargo/commit/5c9665f41c6b4d3b99d3b9f8b48a286f5f154692#commitcomment-29086264

But rust install doesn't install cargo.

**Comment by ishitatsuyuki** [comment]
I think you should set `extended` flag in config.toml?

**Comment by hellow554** [comment]
Sorry, but I don't get your issue.
When I type `./x.py install` cargo will be installed along, right (please correct me if I'm wrong!)? So, what is rust in your issue. Is it the repository, then language, the program (rustc)?

**Comment by psumbera** [comment]
I do 'gmake install' for rustc. I'm packaging Rust for Solaris OS.

**Comment by wesleywiser** [comment]
@ishitatsuyuki Is correct. You might also need to adjust the `tools` property accordingly. [See here](https://github.com/rust-lang/rust/blob/5205ae8bdc2991eecf3bfbb58ed8f56c0673e738/config.toml.example#L156-L164)

**Comment by psumbera** [comment]
Thanks for tip on cargo.toml. It solves my problem!
