### ISSUE TITLE
Trait impl hidden by trait bound on function

### ISSUE THREAD

**Issue by stephaneyfx** [rust-lang/rust#51586]
I could have sworn I read a similar issue a couple of days/weeks ago but I could not find it back. #37138 seems related too.
Shoudn't this code compile? [playground](https://play.rust-lang.org/?gist=935194b9d6a8e1ba13a414e9829dae63&version=stable&mode=debug)

```rust
struct A;
trait Foo<T> {}
impl Foo<i32> for A {}

fn f<T>(_: T) where A: Foo<T> {
    g(3i32);
    // Works:
    // g::<i32>(3);
}

fn g<T>(_: T) where A: Foo<T> {}

fn main() {
    f(3);
}
```

```
error[E0308]: mismatched types
 --> src/main.rs:6:7
  |
6 |     g(3i32);
  |       ^^^^ expected type parameter, found i32
  |
  = note: expected type `T`
             found type `i32`

error: aborting due to previous error
```

**Comment by Centril** [comment]
Seems like a bug? 

Just to illustrate that this is not specific to `i32` and having the same type variable names (tested on nightly, etc.):
```rust
#![crate_type = "lib"]

struct A;
struct B;
trait Foo<T> {}
impl Foo<B> for A {}

fn f<T0>(_: T0) where A: Foo<T0> {
    g::<_>(B); // expected type `T0`
}

fn g<T1>(_: T1) where A: Foo<T1> {}
```

But this works fine:

```rust
struct A;
struct B;
trait Foo<T> {}
impl Foo<B> for A {}

fn main() { g::<_>(B); }

fn g<T>(_: T) where A: Foo<T> {}
`````

**Comment by stephaneyfx** [comment]
@Centril: As requested, I tried with older rust versions and the original example is rejected even by rust 1.0.0: https://godbolt.org/g/ECbAi4

**Comment by Centril** [comment]
@stephaneyfx Great, thank you ❤️; then at least there's no regression :)

**Comment by stephaneyfx** [comment]
This looks very much like #24066 and the original example not compiling seems to be intentional: see comments starting at https://github.com/rust-lang/rust/pull/33108#issuecomment-212874598, especially from @eddyb and @aturon.
