### ISSUE TITLE
Suggest correct `println` call

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#51585]
When trying to write `println!(x);`, suggest `println!("{}", x);`.

https://users.rust-lang.org/t/wtf-is-this-problem/18045

**Comment by csmoe** [comment]
Since the `x` may impl `Display` or `Debug`, so `{:?}`/`{}`, which one should be suggested firstly?

**Comment by ollie27** [comment]
#30143 might complicate this because the current error message for `println!(x);` comes from `concat!` not `format_args!` like with `print!(x);`.

**Comment by estebank** [comment]
@csmoe ideally we would check if `x` is debug or display and suggest accordingly, but we already have help text when we get that wrong, so we could (temporarily) give a best guess suggestion and let the compiler guide users with the follow up errors.

@ollie27 you're right.
