### ISSUE TITLE
Provide a clearer error message for semicolons after structs and similar

### ISSUE THREAD

**Issue by joshtriplett** [rust-lang/rust#51603]
Right now, writing something like `struct S {};` just produces a parse error:

```
error: expected item, found `;`
 --> src/main.rs:1:12
  |
1 | struct S {};
  |            ^ help: consider removing this semicolon
```

We could make this error message much clearer by recognizing this common error and specifically saying "don't put a semicolon after a struct/union/enum declaration".

**Comment by PramodBisht** [comment]
@joshtriplett just to clarify should we change `help` or `error` message here?

**Comment by PramodBisht** [comment]
@joshtriplett got it you have mentioned changing the error message.

**Comment by PramodBisht** [comment]
@joshtriplett ok got it, you have mentioned its `error` message.
