### ISSUE TITLE
Compiler suggests using the removed placement syntax

### ISSUE THREAD

**Issue by mickethespike** [rust-lang/rust#51602]
So I'm writing a hangman app in Rust and I get this weird error message. It doesn't make sense since `<-` isn't even in Rust anymore.

```   Compiling hangman v0.1.0 (file:///home/toot/Projects/hangman)
error: expected `{`, found `in`
  --> src/main.rs:8:17
   |
8  |           if line in words {
   |  _________________-^
9  | |             println!("Success");
10 | |         } else {
   | |_________- help: try placing this code inside a block: `{ words <- { println!("Success"); }; }`

error: aborting due to previous error

error: Could not compile `hangman`.
```

**Comment by kennytm** [comment]
Could we just stop parsing [`in «expr» «block»`](https://github.com/rust-lang/rust/blob/c45ae9ea3a9a073d7791de7ffc4f6762120602f5/src/libsyntax/parse/parser.rs#L2773-L2783) as an `ObsoleteInPlace` expression? Will it break any macros or code behind `#[cfg]`?

**Comment by pietroalbini** [comment]
Yeah https://github.com/rust-lang/rust/issues/50832.

**Comment by kennytm** [comment]
#50832 was about `x <- y` though

**Comment by aidanhs** [comment]
I think the same issue applies though - the parser still needs to be able to recognise the code as *something*. So if there are crates using that syntax, they'll break in the same way.

**Comment by estebank** [comment]
Current output:

```
error: expected `{`, found `in`
 --> src/main.rs:2:10
  |
2 |       if i in 0..10 {
  |       --   -^
  |  _____|____|
  | |     |
  | |     this `if` statement has a condition, but no block
3 | |         break;
4 | |     }
  | |_____- help: try placing this code inside a block: `{ (0..10) <- { break ; }; }`
```

Still need to remove the suggestion, but otherwise the error would seem reasonable:

```
error: expected `{`, found `in`
 --> src/main.rs:2:10
  |
2 |     if i in 0..10 {
  |     --   ^^
  |     |
  |     this `if` statement has a condition, but no block
```

**Comment by estebank** [comment]
@PramodBisht I believe that `in` and type ascription (`:`) are the only two that regularly cause problems with this kind of errors.
