### ISSUE TITLE
Type error for loops in a non-() position moves to the `break` statement

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#51669]
Rust has support for `break` within `loop` returning a value:

```rust
let x = loop {
 // ...
 break 5;
}
```

This is a relatively less-known feature.

If your loop is in a position where a type other than unit is expected, breaks in the loop may get a rather weird error ([playpen](https://play.rust-lang.org/?gist=2d97992c9b21b31fccb103fc692c907a&version=stable&mode=debug))

```rust
fn foo() -> u8 {
    loop {
        // ...
        if true {
            break;
        }
        // ...
    }
}
```

```
error[E0308]: mismatched types
 --> src/main.rs:7:13
  |
7 |             break;
  |             ^^^^^ expected (), found u8
  |
  = note: expected type `()`
             found type `u8`
```

This error makes sense if you know that `break` can take a value, but most people don't, and this makes it kinda confusing. We should have better diagnostics here, perhaps move the primary error to the loop itself and add a note to the `break`, or vice versa.

(found by @jubitaneja)

**Comment by jubitaneja** [comment]
Thanks, @Manishearth for teaching me this cool trick! Breaking with a value is really useful.

**Comment by oli-obk** [comment]
That type error is backwards. We are expecting a u8, nothing in your example supplies a u8

**Comment by oli-obk** [comment]
Also I think the error is exactly where it should be, but we should definitely add some explanation. Value-break is probably not the only place where a type mismatch error could benefit from some additional notes

**Comment by estebank** [comment]
> That type error is backwards. We are expecting a u8, nothing in your example supplies a u8

Handled in #63337.

> Also I think the error is exactly where it should be, but we should definitely add some explanation. Value-break is probably not the only place where a type mismatch error could benefit from some additional notes

If that is so, then this ticket should be closed when that PR is merged. Otherwise we can keep open exclusively to point at the enclosing `loop` when appropriate.

**Comment by estebank** [comment]
Current output:

```
error[E0308]: mismatched types
 --> src/main.rs:7:13
  |
4 | fn foo() -> u8 {
  |             -- expected `u8` because of return type
...
7 |             break;
  |             ^^^^^
  |             |
  |             expected `u8`, found `()`
  |             help: give it a value of the expected type: `break 42`
```
