### ISSUE TITLE
Implement Future for TaskObj

### ISSUE THREAD

**Issue by cramertj** [rust-lang/rust#51667]
TaskObj is a unit future wrapper. It should implement the `Future` trait.

**Comment by MajorBreakfast** [comment]
I'm happy to say that through arcane magic I was able to hide this impl from you when you reviewed my PR. So, here it is: https://github.com/rust-lang/rust/blob/2177378e34c5ad431b245e3bd7cd6cd38ab9053a/src/libcore/task.rs#L517-L526

😁

**Comment by cramertj** [comment]
@MajorBreakfast haha nice! Sorry I missed it.
