### ISSUE TITLE
Syntax for refutable bind

### ISSUE THREAD

**Issue by axos88** [rust-lang/rust#51674]
Hello,

As per E0005, all binds must be irrefutable.
I'm seemingly stumbling into this issue quite a lot and wondering if there are any intentions to relax that requirement by introducing `Option<T>` into the mix.

I find myself wanting to do something like this:

```
  struct X { a: u32 };
  struct Y { b: u32 };

  enum Foo {
    Bar(X)
    Baz(Y)
  }

  let foo: Foo = Foo::Bar(X { a: 42 });
    
  let Foo::Bar(x) = foo;  // I would expect the type of x to be Option<X>, and provide None if foo the pattern does not match.
```

We could call it syntactic sugar for:

```
  let x = if let Foo::Bar(_x) = foo { Some(_x) } else { None };
```

**Comment by Mark-Simulacrum** [comment]
This is a fairly major change to the language. If you or someone else wants to pursue this, please follow the RFC process: https://github.com/rust-lang/rfcs#before-creating-an-rfc.

**Comment by axos88** [comment]
So why close this? I wish we could talk about it wether it's just me, or there is genuine interest in getting this done?

**Comment by Mark-Simulacrum** [comment]
We can -- as the process that I linked to notes, the place to do that is internals.rust-lang.org, not this issue tracker, which is intended only for bug reports and minor feature requests.

> The most common preparations for writing and submitting an RFC include talking the idea over on #rust-internals, discussing the topic on our developer discussion forum, and occasionally posting "pre-RFCs" on the developer forum. You may file issues on this repo for discussion, but these are not actively looked at by the teams.
