### ISSUE TITLE
ICE in E0657.rs and impl_trait_projections.rs on nightly

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#51683]
Nightly ICEs when building two tests from the `ui` test suite for me:

- `src/test/ui/error-codes/E0657.rs`
- `src/test/ui/impl_trait_projections.rs`

[Transcript here](https://gist.github.com/nikomatsakis/0a88000f8b87938ea694c5b47269fb65).

Apparently this does not always occur when running the full test suite.

cc @oli-obk

**Comment by oli-obk** [comment]
Fixed by https://github.com/rust-lang/rust/pull/51773
