### ISSUE TITLE
rustdoc: only show `intra_doc_link_resolution_failure` lints for items being documented

### ISSUE THREAD

**Issue by QuietMisdreavus** [rust-lang/rust#51684]
One thing i noticed about this lint is that it's firing for items that aren't even being exported. For example, in [this build log](https://gitlab.com/panicbit/ruststone/-/jobs/76546103), there are a lot of repeat hits for the `cfg_if!` macro, even though i would not expect all of these crates to be re-exporting the macro. In one particular situation, it seems to have caused a crate with `#![deny(warnings)]` on it to fail to build, just because of this dependency! We should probably wait to emit these lints until the passes which strip items have been run, to reduce some of these erroneous reports.

**Comment by QuietMisdreavus** [comment]
cc @GuillaumeGomez since you implemented both the lint and the warning that preceded it.

**Comment by QuietMisdreavus** [comment]
cc https://github.com/rust-lang/rust/issues/43466 as well since it's an intra-doc-link provlem

**Comment by clarcharr** [comment]
Just ran into this. I would like to see these capped to warn like they are normally for lints on dependency crates, rather than preventing a doc build on my crate for something I can't control.

**Comment by GuillaumeGomez** [comment]
You can now play with cap-lints with rustdoc just like you would with rustc. However, this issue is a separate problem which needs to be fixed on its own.

**Comment by QuietMisdreavus** [comment]
It took a bit of a refactor, but i've posted https://github.com/rust-lang/rust/pull/52800 to solve this issue.
