### ISSUE TITLE
package librustdoc's source a la rustc-ap-libsyntax

### ISSUE THREAD

**Issue by QuietMisdreavus** [rust-lang/rust#51693]
Since librustdoc isn't shipped as part of the sysroot, the only way to build on top of it would be to build it yourself. Shipping the code for this in a similar way to `rustc-ap-libsyntax` would help this out.

cc @alexcrichton @Mark-Simulacrum

**Comment by jonas-schievink** [comment]
What is the usecase for this? Using save-analysis data, which is the approach taken by [Doxidize](https://github.com/steveklabnik/doxidize) and the RLS, seems like a better idea to me, since it's a more stable interface.

**Comment by Mark-Simulacrum** [comment]
I'm going to close this. If there's continued interest in the future then https://github.com/alexcrichton/rustc-auto-publish is the right place to file an issue probably.
