### ISSUE TITLE
Playground ICE while playing around with nasal demons

### ISSUE THREAD

**Issue by flying-sheep** [rust-lang/rust#51706]
when encountering [this comment](https://www.reddit.com/r/rust/comments/8sv575/announcing_rust_127/e13n6jh/) i wanted to play around with it, resulting in [this](https://play.rust-lang.org/?gist=e1a6e4fd8a63a31852b998a0394e5460&version=stable&mode=debug)

reproduced here:

```rust
extern crate rand;

use std::intrinsics::transmute;

fn main() {
    unsafe { call_me_maybe(); }
}

unsafe fn call_me_maybe() -> ! {
    if rand::random() {
        transmute(())
    } else {
        loop {}
    }
}
```

And I get:

```
   Compiling playground v0.0.1 (file:///playground)
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:335:21
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: internal compiler error: unexpected panic

[…]

note: rustc 1.27.0 (3eda71b00 2018-06-19) running on x86_64-unknown-linux-gnu

note: compiler flags: -C codegen-units=1 -C debuginfo=2 --crate-type bin
```

**Comment by fanzier** [comment]
The `rand::random()` doesn't seem to matter, this also crashes:
```rust
unsafe fn dont_call_me() -> ! { 
    std::mem::transmute(()) 
}

fn main() {
    unsafe { dont_call_me() }
}
```

[Playground](https://play.rust-lang.org/?gist=218e6c76ee3a135bde8d3aabdbbcd2d9&version=undefined&mode=undefined)

**Comment by varkor** [comment]
This is [fixed on Nightly](https://play.rust-lang.org/?gist=218e6c76ee3a135bde8d3aabdbbcd2d9&version=nightly&mode=undefined) (by https://github.com/rust-lang/rust/pull/50803). It instead results in undefined behaviour, as expected.
