### ISSUE TITLE
Rust doesn't optimize bounds checks that Go 1.11 does

### ISSUE THREAD

**Issue by xfix** [rust-lang/rust#51709]
After reading https://docs.google.com/presentation/d/1tpeJZFObkeick4CF-mx0L3CeCgvT15B96aJeRpxEPcE/preview#slide=id.g3bc6fcf60c_0_200, I noticed that there were three examples of Go optimizing bounds checks. None of those are optimized by Rust nightly in release mode as I see calls in assembly to bounds checking error function.

```rust
#![crate_type = "lib"]

/* now fixed
pub fn one(s: &[u8], suffix: &[u8]) -> bool {
    s.len() >= suffix.len() && s[s.len() - suffix.len()..] == *suffix
}

pub fn two(a: &[i32]) -> i32 {
    let mut x = 0;
    for i in (0..a.len()).rev() {
        x += a[i];
    }
    x
}
*/

pub fn three(i: usize, b: &mut [i32]) {
    if i >= b.len() {
        return;
    }
    for j in 0..i {
        b[j] += 1;
    }
}
```

**Comment by leonardo-m** [comment]
Rustc will need specific passes for bounds checks elision, optimization of integer operations with overflow, escape analysis, devirtualization, and perhaps more.

**Comment by xfix** [comment]
Example `one` is now optimized correctly.

**Comment by xfix** [comment]
With an update to LLVM 12, example `two` is now optimized correctly.

**Comment by leonardo-m** [comment]
This doesn't have array bound tests, so there could be something fishy:

```rust
pub fn four(i: usize, b: &mut [i32]) {
    if i >= b.len() {
        return;
    }
    for x in &mut b[.. i].iter_mut() {
        *x += 1;
    }
}
```

**Comment by xfix** [comment]
As of Rust 1.73.0, this issue was fixed.
