### ISSUE TITLE
Prevent await from creating a generator

### ISSUE THREAD

**Issue by cramertj** [rust-lang/rust#51719]
The await macro implemented in #51580 can be abused to create a generator (e.g. `|| await!()`). This shouldn't be allowed.

**Comment by BatmanAoD** [comment]
Is there an explanation somewhere of why this is necessarily bad?

**Comment by cramertj** [comment]
@BatmanAoD The fact that `await!()` internally uses `yield` is an implementation detail which shouldn't be exposed to end users. Eventually we'd like to be able to use `async` generators (where both `yield` and `await` are valid and mean very different things) in order to write `Stream`s.

**Comment by BatmanAoD** [comment]
Ah, okay.

Is there any compelling reason to permit `await!` inside a closer at all, with any semantics?

**Comment by cramertj** [comment]
@BatmanAoD Non-`async` closures? No. `await` shouldn't be allowed outside of `async` closures, blocks, or functions.

**Comment by BatmanAoD** [comment]
Oh, I didn't notic that the `async`/`await` RFC permitted specifying that a closure could be `async`. Yes, I meant non-`async` closures.

Inside of `async` closures, permitting `await!` as-is shouldn't really be a problem, right?

**Comment by tmandry** [comment]
Should this be tagged as AsyncAwait-Blocker?

**Comment by cramertj** [comment]
Yup!

**Comment by cramertj** [comment]
(but it's also in the group of issues that would be obviously fixed by native syntax)
