### ISSUE TITLE
No way to make a static *mut _

### ISSUE THREAD

**Issue by jD91mZM2** [rust-lang/rust#51718]
# Situation

In relibc we need a way to have a static with the signature of
```
#[no_mangle]
pub static stdin: *mut FILE
```
Currently we have two statics, one for the file and one for the pointer.
However, using `unsafe { &mut default_stdin } as *mut _` doesn't work because
```
error[E0017]: references in statics may only refer to immutable values
  --> src/stdio/src/default.rs:68:36
   |
68 | pub static mut stdout: *mut FILE = unsafe { &mut default_stdout } as *mut _;
   |                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ statics require immutable values
```

We were thinking of solving this with `UnsafeCell`, but it's not Sync and can't be used in a static, and the `get` function is not const fn.

```
error[E0277]: the trait bound `core::cell::UnsafeCell<FILE>: core::marker::Sync` is not satisfied
  --> src/stdio/src/default.rs:10:1
   |
10 | / static default_stdin: UnsafeCell<FILE> = UnsafeCell::new(FILE {
11 | |     flags: constants::F_PERM | constants::F_NOWR | constants::F_BADJ,
12 | |     rpos: ptr::null_mut(),
13 | |     rend: ptr::null_mut(),
...  |
22 | |     lock: AtomicBool::new(false),
23 | | });
   | |___^ `core::cell::UnsafeCell<FILE>` cannot be shared between threads safely
   |
   = help: the trait `core::marker::Sync` is not implemented for `core::cell::UnsafeCell<FILE>`
   = note: shared static variables must have a type that implements `Sync`

error[E0015]: calls in statics are limited to constant functions, struct and enum contructors
  --> src/stdio/src/default.rs:65:35
   |
65 | pub static mut stdin: *mut FILE = default_stdin.get();
   |                                   ^^^^^^^^^^^^^^^^^^^
```

The only way we see of doing this is with `unsafe { &default_stdin } as *const _ as *mut _`, as you can see [here](https://gitlab.redox-os.org/redox-os/relibc/blob/c24d1e2b361eae5227d2294d98e45d0658374785/src/stdio/src/default.rs#L68), however, that's undefined behavior according to the [nomicon](https://doc.rust-lang.org/nomicon/transmutes.html).

# Proposition

We can work around the Sync problem with a wrapper, but we need `get` to be const fn.

**Comment by oli-obk** [comment]
I haven't looked at the `get` method body, but it seems like a prime candidate for const fn. 

Until it becomes so, is casting an immutable reference to an UnsafeCell into a const ptr and then into a mut ptr also UB? If not, you can just do that for now

**Comment by oli-obk** [comment]
cc @RalfJung

**Comment by jD91mZM2** [comment]
I have no idea, but I would guess it is since the nomicon says "Transmuting is *always* undefined behavior". For now we solved it by using a function instead of a variable, and binding a C macro to call that function behind the scenes. It's probably slower, but it works until this is fixed.

**Comment by RalfJung** [comment]
> however, that's undefined behavior according to the nomicon.

Where are you getting that from?

`*const _` and `*mut _` are the same type, as far as UB is concerned. The difference is just a lint.

**Comment by RalfJung** [comment]
> is casting an immutable reference to an UnsafeCell into a const ptr and then into a mut ptr also UB? If not, you can just do that for now

Well, the docs say you should use `get`... but with `x: &UnsafeCell<T>`, I think `x as *const _ as &mut T` should be fine, that's effectively reimplementing `get`.

**Comment by asquared31415** [comment]
`UnsafeCell::get` is `const fn` as of 1.32.  The following program compiles:
```rust
use core::cell::UnsafeCell;

#[repr(transparent)]
struct SyncUnsafeCell<T>(UnsafeCell<T>);

// SAFETY: don't do bad things
unsafe impl<T> Sync for SyncUnsafeCell<T> {}

#[repr(transparent)]
struct SyncPtr<T>(*mut T);

// SAFETY: don't do bad things
unsafe impl<T> Sync for SyncPtr<T> {}

struct S;

static DEFAULT: SyncUnsafeCell<S> = SyncUnsafeCell(UnsafeCell::new(S));
#[no_mangle]
static VAL: SyncPtr<S> = SyncPtr(DEFAULT.0.get());
```

**Comment by RalfJung** [comment]
Hm, should it be concerning that we have "references in statics may only refer to immutable values" but then we allow `DEFAULT.0.get` which takes a reference to an interior mutable value?

`check_mut_borrow` specifically complains about mutable references, but we allow interior mutable references. I forgot why that makes sense.

**Comment by workingjubilee** [comment]
Also compiles now:

```rust
pub static mut stdout: *mut FILE = &raw mut default_stdout;

pub struct FILE(i32);
static mut default_stdout: FILE = FILE(1);
```
