### ISSUE TITLE
We shouldn't use the host's `uint` for target sizes.

### ISSUE THREAD

**Issue by jld** [rust-lang/rust#5172]
It's unclear how likely we are to ever deal with ≥4GiB things (or possible things; e.g., if an mmapped region is cast to a huge fixed array type or something like that), let alone when cross-compiling from 32-bit to 64-bit, but this is probably something that should be cleaned up.

For comparison, LLVM seems to mostly use `uint64_t` for sizes; there are a few `unsigned`s but I think they may all be for cases like individual machine-level values where the sizes can't overflow.

**Comment by frewsxcv** [comment]
[The code in question](https://github.com/rust-lang/rust/blob/2e2372c6c4a265992b0eb615ea9fdee4ab999143/src/librustc_trans/trans/common.rs#L794-L816) that @eddyb mentioned

**Comment by nagisa** [comment]
The code in question now uses AsU64 and AsI64.

**Comment by steveklabnik** [comment]
There's been a lot of ongoing work to move away from `usize` to specific sizes where it makes sense, so I don't think this ticket is particularly useful anymore.
