### ISSUE TITLE
Document that match guards are "distributed" across mutliple patterns

### ISSUE THREAD

**Issue by HMPerson1** [rust-lang/rust#51745]
Example function ([playground](https://play.rust-lang.org/?gist=862fa253d8f1b3209ae29ea336911968&version=stable&mode=debug)):
```rust
fn or(b1: bool, b2: bool) -> bool {
    match (b1, b2) {
        (b, _) | (_, b) if b => true,
        _ => false,
    }
}
```
When we call `or(false, true)`, it matches the `(b, _)` pattern, then runs the guard which fails, *then matches the `(_, b)` pattern in the same arm and runs the guard again* which succeeds, and then finally returns `true`.

With the current documentation ([book](https://doc.rust-lang.org/book/second-edition/ch18-03-pattern-syntax.html#extra-conditionals-with-match-guards), [refererence](https://doc.rust-lang.org/reference/expressions/match-expr.html)), it's not clear that after matching `(b, _)` and failing the guard, it will try to match the `(_, b)` pattern in the same arm instead of failing the whole arm proceeding to the next arm (`_ => false`).

See also #26998, #26012.

**Comment by steveklabnik** [comment]
Could you please open this against the reference instead? Thanks!
