### ISSUE TITLE
Run compiler unit tests without stage 1 build

### ISSUE THREAD

**Issue by cramertj** [rust-lang/rust#51748]
`./x.py test src/libsyntax --stage 0` builds all the way through a stage 1 build before actually running the tests, so any changes to libsyntax require rebuilding all of rustc in order to rerun the unit tests. This is a really slow process, making it much harder to write and run unit tests for rustc code.

**Comment by jyn514** [comment]
I think this is a duplicate of https://github.com/rust-lang/rust/issues/44293.
