### ISSUE TITLE
Unclear "cannot infer" error message instead of expected "cannot move out of borrowed content"

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/rust#51759]
The error message for the following code is very unclear:

```rust
struct Parser<'a> {
    buf: &'a mut Vec<u8>,
}

impl<'a> Parser<'a> {
    fn parse(&mut self) -> Option<Packet<'a>> {
        Some(Packet {
            buf: self.buf,
        })
    }
}

struct Packet<'a> {
    buf: &'a mut Vec<u8>,
}
```

```
error[E0495]: cannot infer an appropriate lifetime for lifetime parameter `'a` due to conflicting requirements
 --> src/main.rs:9:14
  |
9 |         Some(Packet {
  |              ^^^^^^
  |
note: first, the lifetime cannot outlive the anonymous lifetime #1 defined on the method body at 8:5...
 --> src/main.rs:8:5
  |
8 | /     fn parse(&mut self) -> Option<Packet<'a>> {
9 | |         Some(Packet {
10| |             buf: self.buf,
11| |         })
12| |     }
  | |_____^
note: ...so that reference does not outlive borrowed content
 --> src/main.rs:10:18
  |
10|             buf: self.buf,
  |                  ^^^^^^^^
note: but, the lifetime must be valid for the lifetime 'a as defined on the impl at 7:1...
 --> src/main.rs:7:1
  |
7 | impl<'a> Parser<'a> {
  | ^^^^^^^^^^^^^^^^^^^
  = note: ...so that the expression is assignable:
          expected std::option::Option<Packet<'a>>
             found std::option::Option<Packet<'_>>
```

The mentioned conflict does not seem to make sense, since it's just moving `&'a mut T` to a place that expects a `&'a mut T`. The actual problem is that `self.buf` cannot be moved out of the mutable reference to `self`. The error message looks a lot better when moving `self.buf` into a local variable like this:

```rust
    fn parse(&mut self) -> Option<Packet<'a>> {
        let buf = self.buf;
        Some(Packet {
            buf,
        })
    }
```

```
error[E0507]: cannot move out of borrowed content
 --> src/main.rs:9:19
  |
9 |         let buf = self.buf;
  |                   ^^^^----
  |                   |
  |                   cannot move out of borrowed content
  |                   help: consider using a reference instead: `&self.buf`
```

(the actual fix was wrapping the `buf` field in an `Option` and `take`ing it out when constructing the `Packet`)

With `#![feature(nll)]`, the error message for the original code looks different, but still roughly as bad:
```
error: free region `` does not outlive free region `'a`
  --> src/main.rs:9:14
   |
9  |           Some(Packet {
   |  ______________^
10 | |             buf: self.buf,
11 | |         })
   | |_________^
```

**Comment by nikomatsakis** [comment]
I agree that the compiler's error is confusing. It's correct from the compiler's POV; this is because, when you have `buf: self.buf`, we implicitly insert a `&mut *`, so the compiler sees `buf: &mut *self.buf` (this is called a "reborrow coercion"). So then the problem shows up as this reborrow lasting too long. But it'd be nice if we could explain this in some clearer way. Still, this is a problem that pre-dates NLL, so i'm removing the NLL tag from it, or at least marking it as NLL-deferred.

**Comment by pnkfelix** [comment]
NLL premeeting triage. A lot of Rust's audience is unlikely to be familiar with auto-injected reborrows+derefs coercions here, and better diagnostics could help bridge that gap.

So, marking P-medium.

**Comment by estebank** [comment]
NLL Output:
```
error: lifetime may not live long enough
  --> src/lib.rs:9:9
   |
7  |   impl<'a> Parser<'a> {
   |        -- lifetime `'a` defined here
8  |       fn parse(&mut self) -> Option<Packet<'a>> {
   |                - let's call the lifetime of this reference `'1`
9  | /         Some(Packet {
10 | |             buf: self.buf,
11 | |         })
   | |__________^ returning this value requires that `'1` must outlive `'a`
```

Without NLL the output remains unchanged.

Changing the signature of `parse` to `fn parse(&'a mut self) -> Option<Packet<'a>>` makes the code compile, and is hinted at (but not suggested) by the NLL output.

**Comment by matthewjasper** [comment]
Changing the signature will probably break code calling the method though. There isn't a suggestion we can easily provide without more context.

**Comment by oli-obk** [comment]
Diagnostics triage: It's not clear that we can suggest anything here to the user and it would at least be very hard to do. Closing as wontfix
