### ISSUE TITLE
fs::write does not flush/sync, and thus does not guarantee the data ends up on disk

### ISSUE THREAD

**Issue by faern** [rust-lang/rust#51775]
`fs::write` is indeed just a shorthand for `File::create` and `Write::write_all`, as the documentation states. But these two calls alone does not guarantee the data has arrived to the destination when `fs::write` returns. At least on Windows if you use `fs::write` and then reboot, the data is never written to disk.

Is this by design, or a bug? If you want to make sure the data you write ends up on disk, you can't use this convenient helper function. I'm not sure how others use this function, but this problem makes this helper not applicable in almost any situation for me.

I propose changing the implementation to also flush before returning.

**Comment by bluetech** [comment]
By "flush" do you mean calling [`sync_all`](https://doc.rust-lang.org/std/fs/struct.File.html#method.sync_all) (`fsync` on unix) before closing the file?

**Comment by faern** [comment]
Ok. Apparently `Write::flush` is a no-op on Windows: https://github.com/rust-lang/rust/blob/master/src/libstd/sys/windows/fs.rs#L336

So maybe `File::sync_all` is what we might want here? as you suggested.

**Comment by sfackler** [comment]
Call `File::sync_data` or `File::sync_all` if you want to do your best to ensure that all of the data has been written fully through to the disk.

These are very expensive operations, so we don't call them automatically. Code that needs to make guarantees about data consistency should use them as necessary.

**Comment by faern** [comment]
But neither of those operations are static methods, they need the `File` instance. So what you are saying is that one should not use `fs::write` at all for writing where consistency has some importance?

**Comment by sfackler** [comment]
Yep - fs::write is a convenience for the common case.

**Comment by faern** [comment]
Yes, OK. I knew it was a convenience for the common case. I just had another view of what the common case was. But I agree now that syncing all the way might count as that common.
