### ISSUE TITLE
rename-dependency doesn't perform hyphen/underscore translation

### ISSUE THREAD

**Issue by kazcw** [rust-lang/rust#51795]
When renaming a dependency in Cargo.toml (rust-lang/cargo#5422),

This works: `not_a = { path = "../a", package = "a" }`
This doesn't: `not-a = { path = "../a", package = "a" }`; attempting to import the crate results in `can't find crate for not_a`

It's never necessary to use hyphens in a rename, but supporting it would be less surprising.

**Comment by ehuss** [comment]
This should be fixed in the latest nightly (fixed via rust-lang/cargo#6140).

**Comment by dwijnand** [comment]
I can confirm this is fixed, tested using the 2018-11-09 nightly I have installed.
