### ISSUE TITLE
DirEntry.metadata() vs. Path.metadata()

### ISSUE THREAD

**Issue by FliegendeWurst** [rust-lang/rust#51808]
It seems like the two functions return different data for the same path.
```rust
let file: DirEntry = get_entry();
let a = file.metadata().unwrap().modified().unwrap(); // this is 0
let b = file.path().metadata().unwrap().modified().unwrap(); // this is the correct time
```
I'm using nightly version 2018-06-18 on Linux. Is this supposed to happen?

**Comment by kennytm** [comment]
Hi, is your system 32-bit or 64-bit?

**Comment by FliegendeWurst** [comment]
64-bit, why do you ask?

**Comment by kennytm** [comment]
Does this happen if you use 1.27.0-stable?

**Comment by FliegendeWurst** [comment]
It works fine on stable.
