### ISSUE TITLE
nll: incorrect unused_mut with move closure

### ISSUE THREAD

**Issue by kazcw** [rust-lang/rust#51801]
With the [nll feature](rust-lang/rust#43234) enabled, a "variable does not need to be mutable" warning is emitted incorrectly when a variable is mutated from inside a move closure.

```
#![feature(nll)]

fn main() {
    let mut baz = 4; // "warning: variable does not need to be mutable"
    move || { baz = 6 };
}   
```

**Comment by leonardo-m** [comment]
Related to #50897 ?

**Comment by nikomatsakis** [comment]
Tagging as NLL-deferred because #51918 has precedence
