### ISSUE TITLE
Unexpected/undocumented `binary_search` behavior with duplicates

### ISSUE THREAD

**Issue by scottjmaddox** [rust-lang/rust#51817]
`slice::binary_search` (and perhaps its cousins?) behave in a fairly unexpected (and undocumented) way in the presence of duplicates:

```rust
let s = &[0, 1, 1, 1, 1, 2];
// What I would expect:
assert_eq!(s.binary_search(&1), Ok(1));
// Actual result:
assert_eq!(s.binary_search(&1), Ok(4));
```

While not strictly a bug (since the documentation does not state a particular behavior in this case) it would be fairly simple to tweak the implementation to provide the more expected behavior of returning the first match. Either way, it would be preferable if the behavior were documented.

Making the change at this point might result in some unexpected code breakage, even though the behavior is not documented. In order to ease the transition, it may be best to rename the current implementation to `reverse_binary_search` or similar, and provide the expected implementation for `binary_search`.

**Comment by kennytm** [comment]
The exact behavior is deliberately unspecified. In fact it is "[documented](https://doc.rust-lang.org/std/primitive.slice.html#method.binary_search)" that the position is unspecified:

> ... the fourth could match **any** position in [1, 4].
>
> ```rust
> let s = [0, 1, 1, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55];
> // ...
> let r = s.binary_search(&1);
> assert!(match r { Ok(1...4) => true, _ => false, });
> ```

See #45333 for a discussion.

**Comment by scottjmaddox** [comment]
Thanks for your response. I completely missed that detail when reading the documentation. Perhaps an extra phrase/sentence could be added to the documentation summary to make it more explicit? I'm probably not alone in skipping reading the `Examples` section if the function's usage is self explanatory. It could be changed, for example, to:

> If the value is found then Ok is returned, containing the index of the matching element. If there are multiple matches, then any one of the matches could be returned. If the value is not found then Err is returned, containing the index where a matching element could be inserted while maintaining sorted order.

**Comment by frewsxcv** [comment]
@scottjmaddox That wording looks good to me! Do you want to open a pull request with that change? If not, I can 💁‍♂️

**Comment by frewsxcv** [comment]
Also we may want to add the same addition to `binary_search_by` and `binary_search_by_key`

**Comment by scottjmaddox** [comment]
Hey, sorry, just now seeing your response (it was buried in gmail). If you would be willing to submit the PR, that would be awesome!

**Comment by frewsxcv** [comment]
Opened a PR: https://github.com/rust-lang/rust/pull/54700/
