### ISSUE TITLE
[nll] do a crater run with NLL enabled, track results

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#51827]
It'd be good for us to do a crater run with NLL enabled by default and try to track the results.  One problem is that it's not clear if the compiler will bootstrap with NLL enabled (https://github.com/rust-lang/rust/issues/51823). In order to disconnect these two questions, we came up with the following strategy in a [brief IRC discussion](https://mozilla.logbot.info/rust-infra/20180626#c14937862):

- Make a build of rustc where `-Zborrowck=mir` is the default **but only if the `RUSTC_BOOTSTRAP` environment variable is not set**.
- Open a `[WIP]` PR with this branch and do a crater run.

After some discussion on IRC, w

**Comment by nikomatsakis** [comment]
Zulip thread [can be found here](https://rust-lang.zulipchat.com/#narrow/stream/122657-wg-nll/topic/crater-run-and-analysis)

**Comment by Mark-Simulacrum** [comment]
We've started a crater run with ef9a322843fa9f1d6eb6f05b3ba8f9f96ef1de46, this run is master vs. master with `-Zborrowck=mir` on one. Results should be available in around ~3 days.

**Comment by Mark-Simulacrum** [comment]
@lqd is working through the two crater runs we've done so far. It also turned out that we should enable `-Ztwo-phase-borrows` as well; we've now done so. This is the latest crater run: https://cargobomb-reports.s3.amazonaws.com/nll-3/index.html.

**Comment by nikomatsakis** [comment]
This has been done. @lqd is a :superhero:
