### ISSUE TITLE
rustdoc: trait pages don't show impl docs

### ISSUE THREAD

**Issue by llogiq** [rust-lang/rust#51834]
For example, the page for `u64` shows an `impl From<bool> for u64` that is well documented, whereas the page for `From` shows only the bare trait and method signature without any docs.

I see the method `html/render.rs`: `fn render_implementor(..)` appears to render the trait implementors, but I don't have enough time to navigate the byzantine structure of librustdoc to find where best to insert the doc comments. If someone knowledgeable agrees to mentor me here, I'll gladly take this.

**Comment by GuillaumeGomez** [comment]
As far as I can tell, this is intended. Implementors section is big, adding docs in it would make it very. We could add a short version of it like we do in some other places?

**Comment by llogiq** [comment]
I don't see where the problem is: The `u64` page shows the docs only when expanded, so there is no extra space needed – the button to expand comes directly before the `impl` part, and that space is otherwise empty.

My example is exemplary in another sense, too: From the trait page, you're not going to know whether a particular impl

* allocates
* requires other resources
* loses information

The impl docs might shed light on those issues, but you'll have to click on the implementing type, then search for the trait impl on that page, which, I argue, makes for bad UX.

**Comment by GuillaumeGomez** [comment]
Ok, I'll add it then, hidden by default.
