### ISSUE TITLE
All rust related binaries (rustc, cargo, rustup) freeze if uv4l is installed and launched not under root.

### ISSUE THREAD

**Issue by Nalorokk** [rust-lang/rust#51831]
This programs affected:

rustc
cargo
rustup
rust-gdb
rustdoc

All of them will freeze early with last lines in strace like that:

`rt_sigprocmask(SIG_UNBLOCK, [RTMIN RT_1], NULL, 8) = 0
ugetrlimit(RLIMIT_STACK, {rlim_cur=8192*1024, rlim_max=RLIM_INFINITY}) = 0
readlink("/etc/malloc.conf", 0x7ee554f4, 4096) = -1 ENOENT (No such file or directory)
futex(0x76f060ac, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0x973ba4, FUTEX_WAIT_PRIVATE, 2, NULL`

Problem happens only with uv4l services installed if rust launched under not root user. Before uv4l installation everything works fine.

Problem happens on raspbian, don't know if another machines affected.

Steps to reproduce:

1) Install latest raspbian linux (happens on lite and desktop editions)
2) [Install uv4l](https://www.linux-projects.org/uv4l/installation/)
3) Now all rust binaries (both from rustup.rs and from package manager) will not work under not root.

**Comment by Nalorokk** [comment]
This problem happens for at least Rust versions 1.15.0 - 1.27.0

**Comment by est31** [comment]
When testing, do you actually start rustc,cargo,rustdoc or do you start the wrapper?

**Comment by Nalorokk** [comment]
> When testing, do you actually start rustc,cargo,rustdoc or do you start the wrapper?

Binaries from /.rustup/toolchains/stable-armv7-unknown-linux-gnueabihf/bin/

**Comment by est31** [comment]
Yeah that's without the wrapper.

**Comment by Nalorokk** [comment]
LD_PRELOAD=/usr/lib/uv4l/uv4lext/armv6l/libuv4lext.so from uv4l package was causing this problem, probably not rust bug
