### ISSUE TITLE
ICE while compiling the ffi_helpers in 1.28 beta

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#51841]
Building the `ffi_helpers` crate causes an ICE in beta 1.28. Looking at the backtrace seems like that's caused by the const evaluator.

* [ffi_helpers](https://crates.io/crates/ffi_helpers) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.28-1/beta-2018-06-22/reg/ffi_helpers-0.1.0/log.txt)) cc @Michael-F-Bryan

cc @oli-obk

**Comment by Mark-Simulacrum** [comment]
@oli-obk is fixing so not going to bisect this
