### ISSUE TITLE
Test suites of xml-rs and quick-xml crates fails on 1.28 beta

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#51843]
I think that's caused by a change in the debug repr, but I haven't bisected/checked.

* [quick-xml](https://crates.io/crates/quick-xml) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.28-1/beta-2018-06-22/reg/quick-xml-0.12.1/log.txt)) cc @tafia
* [xml-rs](https://crates.io/crates/xml-rs) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.28-1/beta-2018-06-22/reg/xml-rs-0.8.0/log.txt)) cc @tomaka

**Comment by tomaka** [comment]
cc @netvl

**Comment by Mark-Simulacrum** [comment]
65a16c000720f286c91747b91e6d9caa7b1bb63c -- https://github.com/rust-lang/rust/pull/49283 -- cc @rust-lang/libs

Looks like an intentional change though.

**Comment by pietroalbini** [comment]
FYI, there was a similar regression in a past release (#47619), and this was the decision:

> @sfackler - https://github.com/rust-lang/rust/issues/47619#issuecomment-359205246
> We make zero guarantees as to what Debug implementations look like.

**Comment by SimonSapin** [comment]
This was indeed intentional, and I support the quoted comment about the lack of guarantee.

**Comment by Mark-Simulacrum** [comment]
Okay, I'm going to close as this isn't something we're going to fix.

**Comment by tafia** [comment]
Just fyi, quick-xml tests are no longer relying on Debug format. They all use Display only.
