### ISSUE TITLE
bs58 crate fails to build tests in 1.28 beta

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#51845]
[That test code](https://github.com/mycorrhiza/bs58-rs/blob/dbb0fecd867a3358dad16666592621b56130218a/src/decode.rs#L159-L163) doesn't make sense to me... but it was working in 1.27 somehow.

* [bs58](https://crates.io/crates/bs58) regressed from stable to beta ([build log](https://cargobomb-reports.s3.amazonaws.com/beta-1.28-1/beta-2018-06-22/reg/bs58-0.2.0/log.txt)) cc @Nemo157

**Comment by Nemo157** [comment]
`::decode` is both a [module](https://github.com/mycorrhiza/bs58-rs/blob/dbb0fecd867a3358dad16666592621b56130218a/src/lib.rs#L67) and a [function](https://github.com/mycorrhiza/bs58-rs/blob/dbb0fecd867a3358dad16666592621b56130218a/src/lib.rs#L137).

Throwing together a [test playground](https://play.rust-lang.org/?gist=4a74b2c3ba8e408c5718ae88467c71ef&version=stable&mode=debug) indicates that the issue could be #38260, but if so I'm not sure why it was building on 1.27. I'm installing 1.27 locally right now to check.

**Comment by Nemo157** [comment]
Yeah, I get the same error when running the tests with 1.27 locally:

```
error: `self` no longer imports values
   --> bs58-rs/src/decode.rs:150:19
    |
150 |     use decode::{ self, DecodeError };
    |                   ^^^^
    |
    = note: #[deny(legacy_imports)] on by default
    = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
    = note: for more information, see issue #38260 <https://github.com/rust-lang/rust/issues/38260>
```

Guess I need to fix that.

**Comment by pietroalbini** [comment]
> `::decode` is both a [module](https://github.com/mycorrhiza/bs58-rs/blob/dbb0fecd867a3358dad16666592621b56130218a/src/lib.rs#L67) and a [function](https://github.com/mycorrhiza/bs58-rs/blob/dbb0fecd867a3358dad16666592621b56130218a/src/lib.rs#L137).

Oh, I didn't check in the `lib.rs` file. That explains it.

Thanks for looking into this @Nemo157! I'm closing the issue as won't fix.
