### ISSUE TITLE
asmjs-unknown-emscripten produces wasm because of changed defaults in Emscripten

### ISSUE THREAD

**Issue by badboy** [rust-lang/rust#51856]
Emscripten recently introduced a breaking change defaulting to Wasm generation instead of asmjs (in v1.38.1 from 05/17/2018, [changelog](https://github.com/kripken/emscripten/blob/bd050e64bb0d9952df1344b8ea9356252328ad83/ChangeLog.markdown#v1381-05172018)).

It now requires `-s WASM=0` to be passed to disable this behavior. It seems like that should be fine for older Emscripten as well, so we could just pass it unconditionally. 

I'd like to add this myself tomorrow.

**Comment by Serentty** [comment]
It seems like this is happening again, if Compiler Explorer is anything to go by.

**Comment by workingjubilee** [comment]
Regressed in Rust 1.40, [Godbolt](https://rust.godbolt.org/z/K5M1WGG7o).

**Comment by workingjubilee** [comment]
Judging by many exceptions carved into the codebase in this general direction, it appears it has been believed that "asmjs is just another way to say wasm32" when that is not the case at all?
