### ISSUE TITLE
infer outlives doesn't work across crates

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#51858]
This example fails to compile:

```rust
#![feature(infer_outlives_requirements)]

struct Bar<'a, T> {
    f: std::slice::IterMut<'a, T>
}

fn main() { }
```

however this purely intra-crate example works:

```rust
#![feature(infer_outlives_requirements)]

struct Foo<'a, T: 'a> {
    x: &'a T
}

struct Bar<'a, T> {
    f: Foo<'a, T>
}

fn main() { }
```

cc @toidiu

**Comment by toidiu** [comment]
Going to run the error scenario locally to better debug the issue.

**Comment by nikomatsakis** [comment]
OK I think I see the problem.

## First, to explain what I expect to happen:

When we are inferred the outlives for `Bar`, I expect us to see that `std::slice::IterMut<'a, T>` requires that `T: 'a` must hold, and hence infer that as an outlives requirement on `Bar`. This works locally but not across crates.

## How to fix

I believe the problem is centered on this line:

https://github.com/rust-lang/rust/blob/9f79d2f86af73da483f4fe8e2422c15c79221d32/src/librustc_typeck/outlives/implicit_infer.rs#L267

In particular, this is part of the function that handles the case where we see a reference to a struct lke `IterMut<'a, T>`. It's supposed to be looking up the "explicit predicates" on that struct. That is fine for crate-local things, but for cross-crate things, inference is already complete, so we can just lookup the full set of predicates.

I think what we want is to rework the "explicit predicates map" setup. Currently, we do a kind of pre-pass that populates this map:

https://github.com/rust-lang/rust/blob/a385095f9a6d4d068102b6c72fbdc86ac2667e51/src/librustc_typeck/outlives/mod.rs#L95

I think we should populate the map lazilly instead. I would think it should be a type:

```rust
crate struct ExplicitPredicatesMap<'tcx> {
  map: FxHashMap<DefId, RequiredPredicates<'tcx>>
}
```

The map would publish one method:

```rust
impl ExplicitPredicatesMap<'tcx> {
    crate fn explicit_predicates_of(&mut self, tcx: TyCtxt<'_, '_, 'tcx>, def_id: DefId) -> &RequiredPredicates<'tcx> {
        self.map.entry(def_id).or_insert_with(|| {
            let predicates = if def_id.is_local() {
                tcx.explicit_predicates_of(def_id)
            } else {
                tcx.predicates_of(def_id)
            };
            let required_predicates = {
                // process predicates and convert to `RequiredPredicates` entry, see below
            };
            required_predicates
        }
    }
}
```

The "processing comment" would basically be doing the same as this existing code, which filters down `Predicate<'tcx>` values to a `RequiredPredicate<'tcx>`:

https://github.com/rust-lang/rust/blob/a385095f9a6d4d068102b6c72fbdc86ac2667e51/src/librustc_typeck/outlives/explicit.rs#L51-L76
