### ISSUE TITLE
rustup doesn't print in colour and messes up \r

### ISSUE THREAD

**Issue by EvilRobotOverlord** [rust-lang/rust#51898]
When I update Rust, it looks like this:
![capture](https://user-images.githubusercontent.com/23280582/42092286-0221907a-7bc6-11e8-8e11-946e2b076d58.PNG)
I'm using Windows 10 Home Single Language, Version 1803.
I use Hyper as my terminal emulator (I just love its UI). It auto-updates, but I don't think the version of Hyper is relevant because it has done this for every update I've done.
Right now, I have `rustup 1.11.0 (e751ff9f8 2018-02-13)`.

Using powershell doesn't print in colour but re-printing on the same line works.

**Comment by pmarcelll** [comment]
Rustup has its own repo and issue tracker [here](https://github.com/rust-lang-nursery/rustup.rs), so I think you should open an issue there.

**Comment by EvilRobotOverlord** [comment]
I will do that. I'm closing this issue to repost it there.
