### ISSUE TITLE
NLL: incorrect "unused mut" lint warning, with multiple closures

### ISSUE THREAD

**Issue by lqd** [rust-lang/rust#51904]
Found while trying to bootstrap Rust with NLL enabled, just in case we're not already tracking this incorrect warning (as we're already tracking other similar ones in #51801 and #51830 and more).

Reduced from `libsyntax::parser::parser::parse_dot_or_call_expr_with`. Probably not exactly minimal, but smaller than the whole parser :)

Repro here on the [playground](https://play.rust-lang.org/?gist=006f54543251c34541a879a2fb1a0365&version=nightly&mode=debug)

**Comment by nikomatsakis** [comment]
Tagging as NLL-deferred because #51918 has precedence
