### ISSUE TITLE
nll: incorrect unused-mut warnings

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#51918]
There are a lot of incorrect `unused_mut` warnings coming up. I'm going to make this meta-bug for tracking them because it's very unclear how many underlying issues there are:

- https://github.com/rust-lang/rust/issues/50897
- https://github.com/rust-lang/rust/issues/51801
- https://github.com/rust-lang/rust/issues/51830
- https://github.com/rust-lang/rust/issues/51904

**Comment by matthewjasper** [comment]
There are at least two different issues here it seems:

```rust
fn foo(ref x: i32) {}

fn bar() {
    let mut x = 0;
    move || {
        x = 1;
    };
}
```

I'll try to have a PR for the first one over the weekend.
The second one requires move investigation, because the code is certainly trying to avoid linting in this case.

**Comment by nikomatsakis** [comment]
@matthewjasper what remains now that your PR landed?

**Comment by matthewjasper** [comment]
I don't think there are any more bugs. I think this is just waiting for this to be on nightly a few days to be sure.

**Comment by nikomatsakis** [comment]
Closing as fixed then. @matthewjasper let me know if you think that's wrong!
