### ISSUE TITLE
libtest output for common CI systems

### ISSUE THREAD

**Issue by lzybkr** [rust-lang/rust#51924]
It would be useful if `libtest` would write a file in a format supported by CI systems.

Based on [AppVeyor](https://www.appveyor.com/docs/running-tests/#uploading-xml-test-results) and [VSTS](https://docs.microsoft.com/en-us/vsts/pipelines/tasks/test/publish-test-results?view=vsts), it looks like `junit` or `xunit3` could be good choices.

**Comment by Mark-Simulacrum** [comment]
I think this is out of scope for libtest which tries to be pretty minimal, but piping libtest's JSON output (https://github.com/rust-lang/rust/issues/49359) to some other command should be feasible.
