### ISSUE TITLE
Text bug - Sleeping bag

### ISSUE THREAD

**Issue by Draxascsgeau** [rust-lang/rust#51927]
Hello, the game has a problem with the french language. The text which says "respawn in sleeping bag" is in french a very long sentence and it is hiding the sleeping bag's name.
Could you please update this text to a shorter sentence so that we can read the sleeping bags' names.
Thanks

**Comment by sfackler** [comment]
This is a repository for the Rust programming language, not the Rust video game. You should file this over on the game's issue tracker: https://jira.facepunch.com
