### ISSUE TITLE
[tracking issue] const fn std::mem::needs_drop

### ISSUE THREAD

**Issue by Havvy** [rust-lang/rust#51929]
The issue title says it all really. std::mem::needs_drop is a function that doesn't change from call to call once monomorphized, so it should be a const function.

EDIT:

This has been implemented and it is waiting for stabilization now.

**Comment by oli-obk** [comment]
blocked on https://github.com/rust-lang/rust/pull/51570

**Comment by JoshBrudnak** [comment]
@oli-obk is this still blocked? If not I would like to help out with it. :+1:

**Comment by oli-obk** [comment]
Should be fine to add behind a feature gate.

The steps are basically the same as https://github.com/rust-lang/rust/pull/51171 and https://github.com/rust-lang/rust/pull/51299 (but you can do them in a single PR)

**Comment by mjbshaw** [comment]
It might be nice to keeps this issue open until `const_needs_drop` is stabilized.

**Comment by mjbshaw** [comment]
I know it's only been a few months since this was implemented, but I'm curious what the road to stabilization is. I've been using this in my objrs crate and it's been working great. At what point should I send a stabilization PR?

**Comment by Mark-Simulacrum** [comment]
I've nominated this for libs team to take a look at and decide whether or not to propose FCP for stabilization.

**Comment by sfackler** [comment]
I've added T-lang since they'd better know if this bit of const-fn-ness is ready to stabilize.

@rfcbot fcp merge

**Comment by Centril** [comment]
Seems unobjectionable (assuming the implementation is up to snuff...? cc @oli-obk).

**Comment by oli-obk** [comment]
Yea, the impl has baked in miri since long before it was in const eval. I also rechecked it and I see no reason not to stabilize.

**Comment by Centril** [comment]
👋 @joshtriplett @nikomatsakis @pnkfelix @withoutboats
