### ISSUE TITLE
Suggest adding `return` or moving items before block/control flow expression statement when expression statement followed only by item statements and there's no trailing expression

### ISSUE THREAD

**Issue by Havvy** [rust-lang/rust#51937]
Basically, when the code is of the form

```rust
fn fn_name() -> return_type {
    statements;
    { control flow expression without terminating semicolon }
    items
    /* no terminating expression */
}
```

then when the mismatched type error happens on the control flow expression statement, check if every following statement is an item declaration. If it is, emit a help pointing out that the item declaration statements are causing the control flow expression to be an expression statement and that the default unit return value is returned. It can probably be fixed by adding a `return` or moving the item declarations to before the expression statement so it gets treated as an expression.

Probably more crazy, make it a non-fatal error by actually assuming the programmer meant for it to be the final expression if the type matches the return type of the function.

For an example, consider the following function:

```rust
fn example_fn() -> i32 {
  if helper_fn() == 0 {
    10
  } else {
    20
  }

  fn helper_fn() -> i32 { 0 }
}
```

Currently it prints out two type errors. One states that the if should be of type `unit`, but it's actually type `i32`. The other states the function block should be of type `i32`, but it is actually of type `unit`. Instead, it should give a single error pointing out that item declaration of `helper_fn` prevents the `if` from being in the return expression position and to either manually return the `if` or to move `helper_fn` to before the `if` expression. And then, for the possibly crazy part, actually presume there's a return there and continue compilation so that other errors can be collected.

**Comment by estebank** [comment]
Current output, no material change:

```
error[E0308]: mismatched types
 --> src/lib.rs:3:5
  |
3 |     10
  |     ^^ expected (), found integer
  |
  = note: expected type `()`
             found type `{integer}`

error[E0308]: mismatched types
 --> src/lib.rs:5:5
  |
5 |     20
  |     ^^ expected (), found integer
  |
  = note: expected type `()`
             found type `{integer}`

error[E0308]: mismatched types
 --> src/lib.rs:1:20
  |
1 | fn example_fn() -> i32 {
  |    ----------      ^^^ expected i32, found ()
  |    |
  |    implicitly returns `()` as its body has no tail or `return` expression
  |
  = note: expected type `i32`
             found type `()`
```

**Comment by estebank** [comment]
Current output:

```
error[E0308]: mismatched types
 --> src/lib.rs:3:5
  |
2 | /   if helper_fn() == 0 {
3 | |     10
  | |     ^^ expected `()`, found integer
4 | |   } else {
5 | |     20
6 | |   }
  | |___- expected this to be `()`
  |
help: you might have meant to return this value
  |
3 |     return 10;
  |     ++++++   +

error[E0308]: mismatched types
 --> src/lib.rs:5:5
  |
2 | /   if helper_fn() == 0 {
3 | |     10
4 | |   } else {
5 | |     20
  | |     ^^ expected `()`, found integer
6 | |   }
  | |___- expected this to be `()`
  |
help: you might have meant to return this value
  |
5 |     return 20;
  |     ++++++   +

error[E0308]: mismatched types
 --> src/lib.rs:1:20
  |
1 | fn example_fn() -> i32 {
  |    ----------      ^^^ expected `i32`, found `()`
  |    |
  |    implicitly returns `()` as its body has no tail or `return` expression
```
