### ISSUE TITLE
async fn inside fn fails to parse

### ISSUE THREAD

**Issue by cramertj** [rust-lang/rust#51933]
This fails to parse: `fn foo() { async fn bar() { } }`.

**Comment by memoryruins** [comment]
Other variants:

```rust
async fn foo() { async fn bar() {} }
```

```rust
let inside_closure = || { async fn bar() {} };
```

```rust
let async_closure = async || {};
```

**Comment by memoryruins** [comment]
All of these examples, including your original example, parse without an issue with the new 2018 edition option enabled on the playground.

**Comment by nikomatsakis** [comment]
Closing as duplicate of #58652
