### ISSUE TITLE
spanned HIR node enums should be named FooKind rather than being named Foo_ and glob-exported

### ISSUE THREAD

**Issue by zackmdavis** [rust-lang/rust#51968]
@petrochenkov [writes](https://github.com/rust-lang/rust/pull/51866#discussion_r199343206):

> The convention enum `Something_ { SomethingVariant }` is "deprecated" and exists in HIR only because not all HIR structures were updated to the "modern" form `enum SomethingKind { Variant }` like it was done in AST.

> New structures should not use it, so it'd be better to rename `Visibility_` to `VisibilityKind`.

The referenced changes to AST were mostly in February 2016's #31487 ([justification](https://github.com/rust-lang/rust/pull/29766#issuecomment-156059150)). The following HIR nodes are still using the underscore-suffix convention, and should probably be changed to the `Kind` style for consistency:

- [ ] [`BinOp_`](https://github.com/rust-lang/rust/blob/1.27.0/src/librustc/hir/mod.rs#L925)
- [ ] [`Stmt_`](https://github.com/rust-lang/rust/blob/1.27.0/src/librustc/hir/mod.rs#L1096)
- [ ] [`Decl_`](https://github.com/rust-lang/rust/blob/1.27.0/src/librustc/hir/mod.rs#L1142)
- [ ] [`Variant_`](https://github.com/rust-lang/rust/blob/1.27.0/src/librustc/hir/mod.rs#L1895)

**Comment by varkor** [comment]
Presumably this applies to [`Expr_`](https://github.com/rust-lang/rust/blob/1.27.0/src/librustc/hir/mod.rs#L1303) too?

**Comment by zackmdavis** [comment]
Ah, yes: I was searching for `Spanned`, but the same rationale would apply to `Expr_`, `Ty_`, and `ForeignItem_`.

**Comment by oli-obk** [comment]
Since any of these changes will break clippy I would be delighted if a PR doing them would also update clippy with the relevant changes. Not a blocker though!
