### ISSUE TITLE
Tracking issue for RFC 2296, `Option::replace`

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#51998]
This is a tracking issue for the RFC *"Add `Option::replace` to the core library"* (rust-lang/rfcs#2296).

**Steps:**

- [x] Implement the RFC (https://github.com/rust-lang/rust/pull/52003)
- [x] Stabilization PR ([see instructions on forge][stabilization-guide])

[stabilization-guide]: https://forge.rust-lang.org/stabilization-guide.html
[doc-guide]: https://forge.rust-lang.org/stabilization-guide.html#updating-documentation

**Unresolved questions:**

None

**Comment by Centril** [comment]
cc @SimonSapin this has baked in nightly for roughly 9.5 weeks; should we stabilize?

**Comment by SimonSapin** [comment]
Looks good to me.

@rfcbot fcp merge

**Comment by Centril** [comment]
@Kerollmops would you be willing to write up a stabilization PR?

**Comment by Kerollmops** [comment]
Yes, I will do that !

**Comment by Centril** [comment]
I believe there's nothing more left to do; closing therefore.
