### ISSUE TITLE
Incorrect URL for the Visual C++ Build Tools

### ISSUE THREAD

**Issue by ubsan** [rust-lang/rust#52008]
rustup-init.exe suggests http://landinghub.visualstudio.com/visual-cpp-build-tools`, which doesn't go anywhere; the correct URL is https://visualstudio.microsoft.com/downloads/#tools

**Comment by aaronsky** [comment]
It looks like this may have been fixed in [rust-lang-nursery/rustup.rs](https://github.com/rust-lang-nursery/rustup.rs/commit/d6e5fcb0263156ff0db3ee55b0d7bcca7f678a72).

**Comment by estebank** [comment]
This change has seen been [released](https://github.com/rust-lang/rustup.rs/releases).
