### ISSUE TITLE
[nll] optimize tuple-stress benchmark by skipping visit of types that do not have regions

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#52027]
The tuple-stress benchmark appears to be ridiculously slow with NLL. Profiling suggests that the majority of costs come from the liveness constraint generation code:

https://github.com/rust-lang/rust/blob/860d169474acabdc53b9a698f8ce02eba7e0daeb/src/librustc_mir/borrow_check/nll/type_check/liveness.rs#L36-L42

Specifically, the vast majority of samples (50%) occur in the `push_type_live_constraint` function:

https://github.com/rust-lang/rust/blob/860d169474acabdc53b9a698f8ce02eba7e0daeb/src/librustc_mir/borrow_check/nll/type_check/liveness.rs#L158-L163

This function primarily consists of a walk over all the free regions within a type:

https://github.com/rust-lang/rust/blob/860d169474acabdc53b9a698f8ce02eba7e0daeb/src/librustc_mir/borrow_check/nll/type_check/liveness.rs#L170-L172

However, the types in question don't really involve regions (they are things like `(u32, f64, u32)` etc). It turns out that we have a "flags" mechanism that tracks the content of types, designed for just such a purpose. This should allow us to quickly skip. The flags are defined here, using the `bitflags!` macro:

https://github.com/rust-lang/rust/blob/860d169474acabdc53b9a698f8ce02eba7e0daeb/src/librustc/ty/mod.rs#L418-L419

The flag we are interested in `HAS_FREE_REGIONS`:

https://github.com/rust-lang/rust/blob/860d169474acabdc53b9a698f8ce02eba7e0daeb/src/librustc/ty/mod.rs#L432-L434

We should be able to optimize the `for_each_free_region` to consult this flag and quickly skip past types that do not contain any regions. `for_each_free_region` is defined here:

https://github.com/rust-lang/rust/blob/860d169474acabdc53b9a698f8ce02eba7e0daeb/src/librustc/ty/fold.rs#L256-L260

It uses a "type visitor" to do its work:

https://github.com/rust-lang/rust/blob/860d169474acabdc53b9a698f8ce02eba7e0daeb/src/librustc/ty/fold.rs#L289-L290

we want to add callback for the case of visiting types which will check this flag. Something like the following ought to do it:

```rust
fn visit_ty(&mut self, ty: Ty<'tcx>) -> bool {
  if ty.flags.intersects(HAS_FREE_REGIONS) {
    self.super_ty(ty)
  } else {
    false // keep visiting
  }
}
```

**Comment by nnethercote** [comment]
FWIW, I think the first code snippet in the above description should be this:
https://github.com/rust-lang/rust/blob/860d169474acabdc53b9a698f8ce02eba7e0daeb/src/librustc_mir/borrow_check/nll/type_check/liveness.rs#L85-L92
