### ISSUE TITLE
Borrow lifetimes for function arguments should follow evaluation order, not lexical order

### ISSUE THREAD

**Issue by iainmerrick** [rust-lang/rust#52035]
I've hit several cases where the borrow checker prevents reasonable-looking code where the same objects are used in both a function call and its arguments. This often happens when calling a method on "self" that also needs to reference self to calculate an argument.

I tried this code:

```
#[derive(Debug, Default)]
struct Foo {
	values: Vec<usize>,
}

impl Foo {
	fn size(&self) -> usize {
		self.values.len()
	}
	fn inc(&mut self) {
		self.values.push(self.size());
	}
}

fn main() {
	let mut foo = Foo::default();
	foo.inc();
    println!("{:?}", foo);
}
```

I expected this to work because `self.size()` is calculated first; it just copies a value out and does not retain a reference. After this, `self.values.push` can safely take a mutable reference.

Instead, this happened: <explanation>

```
error[E0502]: cannot borrow `*self` as immutable because `self.values` is also borrowed as mutable
  --> hello.rs:11:20
   |
11 |         self.values.push(self.size());
   |         -----------      ^^^^       - mutable borrow ends here
   |         |                |
   |         |                immutable borrow occurs here
   |         mutable borrow occurs here
```

It looks like `self.values` grabs a mutable reference _before_ the `self.size()` call. The lifetime of `self.values` is lexically scoped over the entire function call, but I expected the arguments to be fully evaluated first. (Is borrowing always entirely lexically scoped? I can see how that makes for easier error messages...)

You can work around the problem just by manually splitting it across two lines:

```
	fn inc(&mut self) {
		let n = self.size();
		self.values.push(n);
	}
```

But I really expect that to be a trivial transformation with identical semantics. It's surprising that it has such different borrow behavior. It would be great if the borrow checker could do this kind of transformation automatically.

## Meta

`rustc --version --verbose`:

rustc 1.28.0-nightly (e3bf634e0 2018-06-28)
binary: rustc
commit-hash: e3bf634e060bc2f8665878288bcea02008ca346e
commit-date: 2018-06-28
host: x86_64-apple-darwin
release: 1.28.0-nightly
LLVM version: 6.0

**Comment by iainmerrick** [comment]
Also happens when written in this form:

```
fn inc(&mut self) {
    self.push(self.size());
}
```

Thinking about it, as `self` is an implicit first argument, this really means something like:

```
push(&mut self, size(&self))
```

So it does make sense that that first `&mut self` would block the second borrow, at least if arguments are evaluated left-to-right. I wonder if there could be a special case for the `self` case? Always evaluate that implicit argument last?

**Comment by pmarcelll** [comment]
I believe this is fixed by non-lexical lifetimes (more info [here](https://github.com/rust-lang/rfcs/blob/master/text/2094-nll.md#method-calls)), which is one of the major new features for this year, so the Rust team is actively working on this. NLL is tracked by #43234.

**Comment by iainmerrick** [comment]
Fantastic, glad to hear this is in the works! I’m pretty new to Rust so I wasn’t sure if I’d simply misunderstood the reason for this behavior.
