### ISSUE TITLE
edition lint: unnecessary `T: 'a` annotations

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#52042]
We might want to wait until https://github.com/rust-lang/rust/issues/51858 is implemented before landing (not sure), but we can begin implementation.

**Comment by nikomatsakis** [comment]
Getting this 100% right would probably be fairly hard, but we can probably start with something very simple: essentially, we just identify `T: 'a` where-clauses in structs and .. don't do them.

```rust
struct Foo<T: 'a> { .. }
```

becomes 

```rust
struct Foo<T> { }
```

I tried this by hand on Rayon and it all worked great ;).
