### ISSUE TITLE
NLL ICE: "unresolved inference variable in outlives"

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#52057]
The crater run turned up a number of crates encountering an ICE with a message like "unresolved inference variable in outlives" (see list in https://github.com/rust-lang/rust/issues/52054). I'm not sure what is the problem yet but I'm filing this bug to track the issue.

A good representative is combine-language-2.0.0-beta4, which failed with [this log](https://cargobomb-reports.s3.amazonaws.com/nll-1/ef9a322843fa9f1d6eb6f05b3ba8f9f96ef1de46/reg/combine-language-2.0.0-beta4/log.txt).

**Comment by matthewjasper** [comment]
Self contained example. Related to #51649?

```rust
// Delayed ICE:
// error: internal compiler error: unresolved inference variable in outlives: _#0t
#![feature(nll)]

pub trait Parser {
    type Input;

    #[inline(always)]
    fn parse_first(input: &mut Self::Input);
}

impl<'a, I, P: ?Sized> Parser for &'a mut P
where
    P: Parser<Input = I>,
{
    type Input = I;

    fn parse_first(_: &mut Self::Input) {}
}

fn main() {}
```

**Comment by pnkfelix** [comment]
triage re-assigning to self

**Comment by nikomatsakis** [comment]
I think this may have been fixed by #51959. At least @matthewjasper's example no longer reproduces. I'll have to try the original crate.

**Comment by nikomatsakis** [comment]
OK wait. @matthewjasper's example now fails to build, whereas it builds without `nll`. It no longer ICEs though.

**Comment by nikomatsakis** [comment]
Ah, I see the problem. It arises because we don't normalize types before computing the implied bounds in the universal regions code:

https://github.com/rust-lang/rust/blob/fefe81605d6111faa8dbb3635ab2c51d59de740a/src/librustc_mir/borrow_check/nll/universal_regions.rs#L502-L506

even though we just "liberated" late-bound regions:

https://github.com/rust-lang/rust/blob/fefe81605d6111faa8dbb3635ab2c51d59de740a/src/librustc_mir/borrow_check/nll/universal_regions.rs#L487-L492

**Comment by nikomatsakis** [comment]
It's a bit tricky -- we don't just want to insert a random call to normalize until we've finished generating all the "free regions". That call could produce outlives obligations we have to propagate to the right place. It's not that big a deal, in fact at this point we *have* generated all the free regions:

https://github.com/rust-lang/rust/blob/fefe81605d6111faa8dbb3635ab2c51d59de740a/src/librustc_mir/borrow_check/nll/universal_regions.rs#L494

but we still need to route the resulting outlives obligations to the right place. This will take a touch of reorganization in the code.

**Comment by nikomatsakis** [comment]
I'm working on this. It's non-trivial.

**Comment by nikomatsakis** [comment]
But I'm getting there =)
