### ISSUE TITLE
Put a Visual C++ Build Tools installation GIF animation somewhere.

### ISSUE THREAD

**Issue by crlf0710** [rust-lang/rust#52056]
Hi, quite a few beginners lost themselves during trying to properly install Visual C++ Build Tools. 

I wonder if someone can make an GIF animation demonstrating how to install it step-by-step, and include that as part of the official online documentation?

**Comment by steveklabnik** [comment]
The issue is that this changes over time, which is part of why it's hard to find. It would also break a GIF even harder than the links. I don't think we plan on doing this, thank you for the suggestion though!
