### ISSUE TITLE
NLL: Implicit reborrow hides error "Cannot move out of Struct with destructor"

### ISSUE THREAD

**Issue by lqd** [rust-lang/rust#52059]
Found while triaging the NLL crater run, in Servo's `url` crate.

[Playground](https://play.rust-lang.org/?gist=14e1e0c616b95e846e46fd4a322d8c06&version=nightly&mode=debug&edition=2015)

There's a Drop impl preventing , so the error should at least mention it. But the implicit reborrow `self.url` hides this error with a `'*self.url' does not live long enough` one.

Changing the impl to 
```rust
impl<'a> S<'a> {
    fn finish(self) -> &'a mut String {
        let p = self.url;
        p
    }
}
```

gives a better error message: `self.url` `cannot move out of type "S<'_>", which implements the "Drop" trait`.

**Comment by pnkfelix** [comment]
assigning to self, hoping to investigate this week

**Comment by pnkfelix** [comment]
(to be clear, even an *explicit* reborrow would produce the error message that is being deemed inferior here...)

**Comment by pnkfelix** [comment]
Okay I think I have a patch to fix this. And it seems like it improves some of our other diagnostics elsewhere. Will post PR soonish.
