### ISSUE TITLE
coherence check affected by module ordering

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#52050]
As reported by @konstin on the rustfmt repo in https://github.com/rust-lang-nursery/rustfmt/issues/2824, apparently the pyo3 project coherence check is affected by module ordering:

---

rusfmt breaks [pyo3](https://github.com/pyo3/pyo3) in the sense that it doesn't build after running `cargo fmt`.

Reproducing:
```shell
git clone https://github.com/pyo3/pyo3
cd pyo3
git checkout 68c14a5707dd92ceef7619c0a5444cefcc78a0f6 # Recent, but fixed commit
cargo build # Fine
cargo fmt
cargo build # Broken
```

The last command results in a conflicting implementations error, even though only the formatting should have changed:

```
error[E0119]: conflicting implementations of trait `python::IntoPyDictPointer` for type `()`:
   --> src/objects/dict.rs:247:1
    |
247 | / impl<K, V, I> IntoPyDictPointer for I
248 | | where
249 | |     K: ToPyObject,
250 | |     V: ToPyObject,
...   |
260 | |     }
261 | | }
    | |_^ conflicting implementation for `()`
    | 
   ::: src/noargs.rs:61:1
    |
61  |   impl IntoPyDictPointer for () {
    |   ----------------------------- first implementation here
    |
    = note: upstream crates may add new impl of trait `std::iter::Iterator` for type `()` in future versions
```

Versions:
 * `cargo fmt --version`: rustfmt 0.8.2-nightly (87edd75 2018-06-22)
 * `rustc --version`: rustc 1.28.0-nightly (e3bf634e0 2018-06-28)

**Comment by nikomatsakis** [comment]
This may be related to incremental compilation. @Rantanen [follows up with this](https://github.com/rust-lang-nursery/rustfmt/issues/2824#issuecomment-402325323):

---

Got curious about this so did some research into it.

This feels like a rustc bug. The offending file is `src/objects/mod.rs` and the cause is the reordering of the `mod` statements at the bottom.

After `cargo fmt` the mod import list is in the following order (highlights mine):

```rust
mod boolobject;
mod bytearray;
mod dict;  // <- dict
pub mod exc;
mod floatob;
mod iterator;
mod list;
mod module;  // <- module
mod sequence;
mod set;
mod slice;
mod stringdata;
mod stringutils;
mod tuple;
mod typeobject;  // <- typeobject
```

This causes the compilation error. I could fix this in two ways.

- Raise the highlighted lines on top of all the imports and order them as `typeobject`, `module` and `dict`.
- Drop the highlighted lines to the bottom of all the imports and order them as `typeobject`, `dict` and `module`.

Also once the crate has been built successfully, it will continue to compile just fine even with `cargo fmt` restoring the "broken" order. The build will fail only after deleting `target/debug/incremental/pyo3*` and `target/debug/deps/pyo3*`.

Also looking at the error message. That is an impl for `I` where `I: IntoIterator<Item = (K, V)>`. How is that a conflicting implementation for type `()` - is there some "empty tuple into any iterator" `impl` somewhere?

**Comment by nikomatsakis** [comment]
Nominating as it seems pretty important to know what is happening here.

**Comment by nikomatsakis** [comment]
I can reproduce the problem following the given steps.

**Comment by nikomatsakis** [comment]
Nominating as P-high, I will investigate.

**Comment by pnkfelix** [comment]
visited for triage. @nikomatsakis is currently out, but scheduled to be back early next week, so we'll just wait until then to see what progress is made.

**Comment by nikomatsakis** [comment]
Huh. Very curious. So I am able to reproduce the error (and lack of error) -- though with modern compilers something has changed with respect to proc macros so I had to remove a few `pub use` to get things building.

Applying `cargo fmt` does make the error start happening.

But reordering modules in the way described by @Rantanen did not (for me) make the error go away. I was however testing with `CARGO_INCREMENTAL=0` which may be a factor.

Also, just applying cargo fmt to `objects/mod.rs` did not make the error **start**.

**Comment by nikomatsakis** [comment]
The error *does* seem to arise if I format just these two files: `src/objects/mod.rs` and `src/lib.rs`

**Comment by nikomatsakis** [comment]
Actually, just `src/lib.rs` is enough

**Comment by nikomatsakis** [comment]
specifically this diff:

```diff
diff --git a/src/lib.rs b/src/lib.rs
index 729185a..640234b 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -197,23 +197,23 @@ macro_rules! wrap_function (
     };
 );
 
-pub mod python;
-mod err;
+#[doc(hidden)]
+pub mod argparse;
+pub mod buffer;
+#[doc(hidden)]
+pub mod callback;
 mod conversion;
+mod err;
+pub mod freelist;
 mod instance;
+mod noargs;
 mod object;
-mod objects;
 mod objectprotocol;
-mod noargs;
+mod objects;
+pub mod prelude;
+pub mod python;
 mod pythonrun;
-#[doc(hidden)]
-pub mod callback;
 pub mod typeob;
-#[doc(hidden)]
-pub mod argparse;
-pub mod buffer;
-pub mod freelist;
-pub mod prelude;
 
 // re-export for simplicity
 #[doc(hidden)]
```

**Comment by konstin** [comment]
> though with modern compilers something has changed with respect to proc macros so I had to remove a few pub use to get things building.

Yep, that's fixed on master since the v0.3.0 tag

**Comment by nikomatsakis** [comment]
This diff seems to suffice to make the error start to happen:

```diff
Unstaged changes (1)
modified   src/lib.rs
@@ -201,10 +201,10 @@ pub mod python;
 mod err;
 mod conversion;
 mod instance;
+mod noargs;
 mod object;
 mod objects;
 mod objectprotocol;
-mod noargs;
 mod pythonrun;
 #[doc(hidden)]
 pub mod callback;
```

**Comment by nikomatsakis** [comment]
So the strategy of inserting into the tree is that it walks over a list of `&mut DefId` representing the children at any given level:

https://github.com/rust-lang/rust/blob/5ba21844f6c85a0cd55c8ea0250d5cd758134f84/src/librustc/traits/specialize/specialization_graph.rs#L113-L116

If it finds that the current def-id D is broader than some child C, it replaces C with D:

https://github.com/rust-lang/rust/blob/5ba21844f6c85a0cd55c8ea0250d5cd758134f84/src/librustc/traits/specialize/specialization_graph.rs#L167-L173

and adds C as a child of D:

https://github.com/rust-lang/rust/blob/5ba21844f6c85a0cd55c8ea0250d5cd758134f84/src/librustc/traits/specialize/specialization_graph.rs#L262-L268

The flaw here is that there is not a **single** list of children. Rather, there are many lists, sorted by the simplified types. If the simplied type of C is not equal to the simplified type of D, then D ends up in the wrong list.

Probably the fix is to not try to be so clever. We can just remove C from the appropriate list and then (separately) add D -- or, if we want to micro-optimize, we could replace C with D if they share a simplified type, but that feels a bit overkill to me.
