### ISSUE TITLE
API Documentation Page Hiding Results

### ISSUE THREAD

**Issue by zacheryph** [rust-lang/rust#52074]
https://doc.rust-lang.org/std likes to _hide_ or just not show results at all.

If you search for `to_ascii_` you see results for `u8` and the `std::ascii::AsciiExt` trait. These were deprecated as of 1.26, made stable in `1.23` on str (and other places) with the `feature = "ascii_method_on_intrinsics"` flag. However the `to_ascii_` functions do not show up for anything outside of `AsciiExt` and `u8`. Looking more carefully at the results for `to_ascii_` it will say `In Names (10)` but only shows 4 results. I have not found anyway to get it to show any of these methods on `str` at all through the search.

Another example:
* Search for `to_deg`, says 31 results, but only shows 8. it shows `f64::to_degrees` (and others...)
* Search for `to_degr` says 2 results, shows 1. now you see `f32::to_degrees` but not `f64::to_degrees`.

**Comment by GuillaumeGomez** [comment]
It's a bug fixed a while ago.

**Comment by zacheryph** [comment]
Ahh. I do see these work in `/nightly/std` URL.  "a while" as in the `std` docs will get updated with the 1.28 release or _just at some point_? ;)

Thank You.

**Comment by GuillaumeGomez** [comment]
Well, it should be fixed in next release normally.
