### ISSUE TITLE
Cannot use associated const to specify static array length

### ISSUE THREAD

**Issue by diwic** [rust-lang/rust#52070]
pub trait Foo {
        const SIZE: usize;
        fn whatever() {
            // compiles fine
            let _x = [Self::SIZE, 3usize];
            // fails with error[E0599]: no associated item named `SIZE` found for type `Self` in the current scope
            let _y = [3usize; Self::SIZE];
        }
    }

This looks like a bug to me - I believe both rows should compile just fine.
It exists in both stable and nightly.

**Comment by vitalyd** [comment]
This is essentially a dupe of https://github.com/rust-lang/rust/issues/43408

**Comment by tarcieri** [comment]
#60551 is a similar issue specific to associated constants
