### ISSUE TITLE
NLL: Implied bounds computation misses some relationships

### ISSUE THREAD

**Issue by lqd** [rust-lang/rust#52078]
Found while triaging the NLL-enabled crater run, and extracted from `specs-0.10`.

```rust
#![feature(nll)]
#![allow(unused_variables)]

struct Drain<'a, T: 'a> {
    _marker: ::std::marker::PhantomData<&'a T>,
}

trait Join {
    type Value;
    fn get(value: &mut Self::Value);
}

impl<'a, T> Join for Drain<'a, T> {
    type Value = &'a mut Option<T>;
    
    fn get<'b>(value: &'b mut Self::Value) {
    }
}

fn main() {
}
```

[Playground](https://play.rust-lang.org/?gist=1cede31dc3f102bb779ae37607c719b0&version=nightly&mode=debug&edition=2015)

Note: the added `'b` is to make the error message clearer, about a the missed relationship between `'a` and `'b` from the argument type (maybe because it is going through the associated type).

Otherwise `fn get(value: &mut Self::Value)` yields this more obscure `free region "'a" does not outlive free region ""`.

**Comment by nikomatsakis** [comment]
Turns out to be fixed by https://github.com/rust-lang/rust/pull/51959
