### ISSUE TITLE
error message when trying to move from an Rc or Arc is ungreat

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#52086]
This example

```rust
use std::rc::Rc;

struct Bar { field: Vec<i32> }

fn main() {
    let x = Rc::new(Bar { field: vec![] });
    drop(x.field);
}
```

gives this error:

```
error[E0507]: cannot move out of borrowed content
 --> src/main.rs:7:10
  |
7 |     drop(x.field);
  |          ^ cannot move out of borrowed content
```

That is confusing -- after all, `x` is not borrowed!

The problem is that `Rc` only implements `Deref`, and hence we wind up lowering to `Deref::deref(&x).field`, and `deref` returns a `&Bar`.

We should probably say:

```
error[E0507]: cannot move out of `Rc`
 --> src/main.rs:7:10
  |
7 |     drop(x.field);
  |          ^ cannot move out of an `Rc`
```

**Comment by nikomatsakis** [comment]
This could be fixed in the (NLL) borrow check. It could *maybe* be fixed by altering typeck as well -- but borrowck seems perhaps easier. So I'm going to tag as an NLL bug, even though it's not specific to NLL.

**Comment by NikosEfthias** [comment]
Seems this issue is not fixed yet despite the merge. 
```
            let dt = std::rc::Rc::new(dt);
            let _d = dt.clone();
            for d in *_d
            {
            ...
            }
```
this code fails
