### ISSUE TITLE
Incorrect deprecation notice on some AsciiExt methods

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust#52085]
For example [`AsciiExt::is_ascii_hexdigit`](https://doc.rust-lang.org/1.27.0/std/ascii/trait.AsciiExt.html#method.is_ascii_hexdigit) says:

> This method will be deprecated in favor of the identically-named inherent methods on `u8`, `char`, `[u8]` and `str`.

But we decided not to carry `is_ascii_hexdigit` to methods on `[u8]` and `str` as discussed in https://github.com/rust-lang/rust/issues/39658#issuecomment-333977502.

The deprecated methods that are not provided for `[u8]` and `str` should instead say something like:

> This method will be deprecated in favor of the identically-named inherent methods on `u8` and `char`. For `[u8]` use `.iter().all(u8::is_ascii_hexdigit)`. For `str` use `.bytes().all(|b| b.is_ascii_hexdigit())`.

**Comment by zajlerke** [comment]
I would like to give this a shot if you don't mind.
