### ISSUE TITLE
Build Fails (misaligned thread local)

### ISSUE THREAD

**Issue by TheDarkula** [rust-lang/rust#52114]
@oli-obk and @kennytm

Using `rustc 1.27.0 (3eda71b00 2018-06-19)` on Arch Linux, x86_84.

Building with `./x.py test --stage 1 src/test/{ui,compile-fail,run-pass} --bless` causes one test failure.

Relevant error bits:
```
---- [run-pass] run-pass/issue-44056.rs stdout ----

error: test run failed!
status: signal: 4
command: "rustc/build/x86_64-unknown-linux-gnu/test/run-pass/issue-44056/a"
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------

------------------------------------------

thread '[run-pass] run-pass/issue-44056.rs' panicked at 'explicit panic', tools/compiletest/src/runtest.rs:3140:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    [run-pass] run-pass/issue-44056.rs

test result: FAILED. 0 passed; 1 failed; 3039 ignored; 0 measured; 0 filtered out
```

**Comment by atsampson** [comment]
I'm seeing the same single test failure with rustc-1.29.1. This test is built with `-Ctarget-feature=+avx`, and I'm building on a CPU that doesn't have AVX (Xeon E5520); it dies with an illegal instruction error when it hits the first AVX instruction (a VPXOR). Should it be disabled on non-AVX machines?

**Comment by nnethercote** [comment]
I was getting this late last week after updating. It went away after I deleted my `build` directory and rebuilt.

**Comment by RalfJung** [comment]
Related to https://github.com/rust-lang/rust/issues/55537?

**Comment by RalfJung** [comment]
I am going to assume this got fixed when https://github.com/rust-lang/rust/issues/55537 got fixed. If anybody sees this issue again, please open a new one.
