### ISSUE TITLE
NLL: Invalid "cannot borrow as mutable more than once" error related to array of mutable references

### ISSUE THREAD

**Issue by lqd** [rust-lang/rust#52111]
Found while triaging the nll-1 crater run, extracted from `fscm-0.1.1`.

[Playground](https://play.rust-lang.org/?gist=f2508e5e901567baa711575f6172534e&version=nightly&mode=debug&edition=2015)

Accessing the `first` element in the array generates an error about the `second` element borrowing `_` more than once at a time. Mutating the `second` element compiles fine though.

**Comment by matthewjasper** [comment]
This looks like it was fixed by #51894

**Comment by lqd** [comment]
Confirmed on the latest nightly
