### ISSUE TITLE
configure: not canonicalizing relative directories

### ISSUE THREAD

**Issue by Ionic** [rust-lang/rust#52112]
A call like `./configure [...] --local-rust-root=./build/stage0` (possibly also `--llvm-root` and others) will lead to very difficult-to-debug errors.

I spent two hours trying to figure out why bootstrapping `core` always failed with an OS error ("No such file or directory"). It boiled down to the bootstrap compiler not being executable since `configure` does not canonicalize relative paths.

**Comment by jyn514** [comment]
@Ionic are you still running into this problem? If so, can you give a full set of commands to reproduce the error? I ran this locally and it seemed to work ok.

**Comment by Ionic** [comment]
I can't tell or test right away. :/

I haven't touched the OS X machine I've been seeing this error with for two years. Note that the issue is four years old by now. Might have been fixed by now. Maybe we can close the report for now and I can re-open it (or add another comment?) if I still see it?

**Comment by jyn514** [comment]
👍 sounds good, I appreciate the quick response.
