### ISSUE TITLE
`&self` sugar is not consistent with other `&identifier` bindings

### ISSUE THREAD

**Issue by danielhenrymantilla** [rust-lang/rust#52130]
Rust's `&self` sugar is equivalent to `self: &Self`. But in any other scenario, binding to a variable (let's call it `slf` in the examples) with `&slf` idiom actually performs a pattern-match against a reference so that the value of the `slf` variable ends up being an owned value instead of a reference.

Or at least that's what my [test code](https://play.rust-lang.org/?gist=95189c68e15f1f2b252a71dce132d2b2) seems to indicate (I strongly encourage you to have a look at it: https://gist.github.com/danielhenrymantilla/95189c68e15f1f2b252a71dce132d2b2)

Here is an example that should illustrate this point :
```rust
/* compiler ensures that check_ref::<T>(x) can only be called iff x: &T */
fn check_ref<T> (_: &T) {}

#[derive(Clone, Copy, PartialEq)]
struct Slf;

#[test]
fn ampself_notation ()              // &slf
{
    let &slf = &Slf;             // <-- &self logic here */
    // check_ref::<Slf>(slf);    // does not compile!
    check_ref::<Slf>(&slf);      // this does
    assert!(&slf == &Slf);
    assert!(slf == Slf);
    /* => slf is NOT a ref /!\ */
}

#[test]
fn ampself_notation_equivalent ()   // Explanation:
{
//  let &slf =  (&Slf);          // does a pattern-match equivalent to:
    let  slf = *(&Slf);          // move borrowed value => requires Copy
    // check_ref::<Slf>(slf);    // Can't compile => slf isn't a ref
    check_ref::<Slf>(&slf);      // &slf is.
    assert!(slf == Slf);
}

/* ===== (&slf) vs (slf: &Slf) -> NOT THE SAME TYPE ===== */

#[test]
fn function_case ()
{
//  let ampself_notation_wrong = |&slf| {
//      check_ref::<Slf>(slf);          // Can't compile => slf isn't a ref
//  }

    let ampself_notation_right = |&slf| { 
        check_ref::<Slf>(&slf);
        assert!(slf == Slf);
        /* => slf is NOT a ref /!\ */
    };

    ampself_notation_right(&Slf);    // borrowed input
    /* ===== (&slf) vs (slf: &Slf) -> NOT THE SAME TYPE ===== */
}

/* self functions / (static) methods */
impl Slf {
    fn ampself_notation_wrong (&self) {
        check_ref::<Slf>(self);
        assert!(self == &Slf);
        /* => self is a ref */
    }

//  fn ampself_notation_right (&self) {
//      check_ref::<Slf>(&self);
//      /* Can't compile => self is indeed a ref */
//  }
}

#[test]
fn self_method_case ()
{
    Slf::ampself_notation_wrong(&Slf);  // borrowed input
    /* ===== (&self) vs (self: &Self) -> THE SAME TYPE !?? ===== */
}
```

### TL,DR:
- **for a non-special identifier like `slf`, the binding `&slf <- expr` where `expr: &Slf` does not lead to `slf: &Slf` but to `slf: Slf` following the expected "pattern-matching" rules.**
- **for the special identifier `self`, however, the first-arg-of-the-method binding does not lead to `self: Self` but to `self: &Self` instead.**

NB: Although not tested, I guess the same could be said of `&mut identifier`

**Comment by ExpHP** [comment]
You are right, it is inconsistent.  `&self` is not understood as `&(self)`, but rather as an entire semantic unit in its own right that is equivalent to `self: &Self`.

Personally speaking, this has been a thorn in my side from day one, and it took me a good year straight of writing rust to finally break the habit of accidentally doing this: (now I only make this mistake maybe 5% of the time)

```rust
// original code
impl Struct {
    fn method(&self) { ... }
}

// adding an argument after some refactoring...
impl Struct {
    fn method(&self, &other: Struct) { ... }  // oops! Should be `other: &Struct`
}
```

and for a while when I was first starting out, I used to explicitly write `self: &Self` instead just to help myself stop making this mistake.

---

Doing anything to change this would be a significant language change that very likely needs to go through the [RFC process](https://github.com/rust-lang/rfcs).  As a syntactical change, this is something that could theoretically be changed across editions.

My gut feeling is that it will be difficult to convince the community that a change is necessary, and that there was no doubt plenty of bikeshedding before its stabilization given how pervasive the feature is. Any new proposal will require some research into past discussions to make sure it has new arguments to bring to the table.

**Comment by danielhenrymantilla** [comment]
@rkruppe & @ExpHP : I am not suggesting anything, since it is way out of my field (I am still a beginner in rust). My intention writing this "issue" was to first check if I had understood this correctly (I am content with 'roughly' ^^) and second to have this "observation" written down somewhere for the curious people to find (I couldn't find an already existent topic on the matter elsewhere), and some room for discussion on the topic.

Following that idea, I think **the doc could actually add a section for the `&identifier` meaning** : the general pattern-matching case that seems to need the `Copy` trait (which makes sense imho, since the `*&` operation trivially attempts to move stuff out of borrowed content) and a special mention saying that, for convenience reasons, the `&self` and `&mut self` sugar **do not** follow that very same convention.
This way, things would be clearer, specially when working with the natural example that @ExpHP pointed out.

I have been reading what [the doc says about the `&identifier` pattern-match](https://doc.rust-lang.org/book/second-edition/ch18-03-pattern-syntax.html#destructuring-references), and they don't even mention [the `Copy` requirement implicitly satisfied by the inner type of their example, `i32`](https://play.rust-lang.org/?gist=484e23b138678ab441dcb1ad42f2b69b)

**Comment by Ixrec** [comment]
Hypothetically, if we could change this, what would the "consistent" sugar for `self` arguments even be? `self&`? `&(self)`? `self:&`? `self as &`?

**Comment by rkruppe** [comment]
FYI, questions and discussions that aren't targeted at fixing an issue of Rust are better suited for the forums (http://users.rust-lang.org/ or https://internals.rust-lang.org/ depending).

> the general pattern-matching case that seems to need1 the Copy trait

This isn't true, only if the remainder of the pattern actually tries to copy out some data does that data need to be `Copy`. For example, the pattern `&Some(..)` works even if the type in the Option isn't Copy, and `&(ref x, ref y)` matched against `(String, Vec<i32>)` works as well (it makes `x: &String` and `y: &Vec<i32>`).

> a special mention saying that, for convenience reasons, the &self and &mut self sugar do not follow that very same convention.

This seems reasonable to me, but I'm not up to speed with the docs so this is all I can say about it.

**Comment by Mark-Simulacrum** [comment]
I'm going to close this as it sounds like there isn't a concrete work-item here beyond writing an RFC for a change in future editions. Discussion of how best to introduce users should happen on internals.rust-lang.org and then be moved to the appropriate repository (perhaps rust-lang/book?)
