### ISSUE TITLE
rust stages for armv6/7-linux-gnueabi{hf} from static.rust-lang.org do not include rust-docs anymore 

### ISSUE THREAD

**Issue by stefson** [rust-lang/rust#52133]
This is valid for >=rust-1.26.0, the rust-docs folder has been included before that version. For instance with rust-1.25.0 it was just fine. I know that there is a thing called rustup, but there are various reasons to prefere an install from the stage archives via ```install.sh``` 

There were a few problems with cross compile and rust-docs in the past, this may be related somehow. 

Please include rust-docs in the future, if there is a reason not to do that please communicate it. And also please check other archs for the same error, I can only speak for armv6/7! Thanks!

**Comment by Mark-Simulacrum** [comment]
We no longer build documentation for these platforms; I believe the expectation is that users will use linux (x86_64-unknown-linux-gnu) documentation instead.

cc @alexcrichton

**Comment by djc** [comment]
This is an issue in https://bugs.gentoo.org/660512.

So where is the policy described? rust-docs is still being published for seemingly obscure target triples like `i386-apple-ios`, but not things like `armv6` that people actually use, which seems a weird thing to do. Either it's something like one-per-OS or everything-for-tier-2.

**Comment by Mark-Simulacrum** [comment]
It might be a bug that we're publishing the ios docs -- cc @kennytm

Generally speaking the policy isn't described anywhere currently (though we should probably fix that).

**Comment by djc** [comment]
So can we please get some clarity on why this got changed/what the policy should look like? I'm happy to help clarify a policy and/or put it in writing, I just don't want to encode stuff now that might turn out to be wrong later because I'm guessing at motivations for this particular change.

**Comment by pietroalbini** [comment]
At the moment [only tier 1 platforms](https://github.com/rust-lang/rust/blob/f8d34596ff74da91e0877212a9979cb9ca13eb7e/src/tools/build-manifest/src/main.rs#L125-L132) gets the `rust-docs` component packaged with rustup.

The change was made in https://github.com/rust-lang/rust/pull/49187 because building those docs took a long time on our CI system (which was timing out often at the time) and we guessed few people were using those. AFAIK nobody complained (except when the change broke rustup upgrades, but that's another story).

**Comment by Mark-Simulacrum** [comment]
I don't think we're really tracking anything in particular here -- we don't have the CI budget today to produce this documentation and there's not much we can do here today. You can mostly work around it today (presuming you have the disk space), by doing something like `rustup toolchain install stable-x86_64-unknown-linux-gnu` and `rustup doc --toolchain stable-x86_64-unknown-linux-gnu` I believe which should be sufficient for most use cases. Perhaps we ideally would default to the linux docs if we don't have the specific platform's docs but that's a rustup request more so than rust-lang/rust, I think.
