### ISSUE TITLE
[Rust 2018] pub use can't export crates

### ISSUE THREAD

**Issue by CryZe** [rust-lang/rust#52140]
If instead of `pub extern crate some_crate;` you use `pub use some_crate;` in Rust 2018, the crate isn't actually reexported.

**Comment by aturon** [comment]
cc @petrochenkov

**Comment by steveklabnik** [comment]
Got bit by this today

**Comment by pnkfelix** [comment]
as with #52141: visited for triage. P-high. Not sure who is going to work on it; @petrochenkov do you think you have space on your plate to look at this?

**Comment by petrochenkov** [comment]
The reason is probably that resolution for single-segment imports is implemented as a special case in `fn finalize_import`, it probably should happen in some other function that's called earlier than "finalize".

If someone can investigate this now, please do.
I'll be able to do it in 3-4 weeks.

**Comment by nikomatsakis** [comment]
Visiting during compiler meeting. It appears that @eddyb and @petrochenkov have been discussing this bug over in #52923, going to assign to @eddyb
