### ISSUE TITLE
Non-public tuple fields causes confusing error message when crossing module boundaries

### ISSUE THREAD

**Issue by KallDrexx** [rust-lang/rust#52144]
```
mod first {
    #[derive(Debug)]
    pub struct SomeId(u32);    
}

mod second {
    use ::first::SomeId;

    #[derive(Debug)]    
    pub enum MyEnum {
        Variant1 {
            id: SomeId
        }
    }
}

fn main() {
    use first::SomeId;
    use second::MyEnum;

    let test = MyEnum::Variant1 {
        id: SomeId(32),
    };
    
    println!("{:?}", test);
}
```

This gave me the following error message:

```
error[E0423]: expected function, found struct `SomeId`
  --> src/main.rs:22:13
   |
22 |         id: SomeId(32),
   |             ^^^^^^
   |             |
   |             did you mean `Some`?
   |             constructor is not visible here due to private fields
help: possible better candidate is found in another module, you can import it into scope
   |
1  | use first::SomeId;
   |
```

It turns out the fix for this was to change my struct definition to `pub struct SomeId(pub u32);`.  This was not obvious to me for several reasons:

1. The `expected function, found struct SomeId` is odd because that's what I'm trying to perform, so it appears like it's erroring because it's doing what I want.
1. The suggestion for the use statement is completely incorrect, as that use statement already exists and won't fix the problem
1. The `constructor is not visible here due to private fields` didn't make sense to me as the rust book never gives an example of the `Struct(pub fieldType)` syntax, so I assumed tuple fields had the same visibility as the struct itself.

It probably needs a recommendation for tuple structs to show that all fields should be marked as `pub`

**Comment by oyvindln** [comment]
Even more confusing when you have an empty tuple like this: 
```pub struct Tuple(())```

```pub struct Tuple(pub ())```
:confused:

**Comment by estebank** [comment]
Current output:

```
error[E0423]: expected function, tuple struct or tuple variant, found struct `SomeId`
  --> file17.rs:22:13
   |
22 |         id: SomeId(32),
   |             ^^^^^^
   |             |
   |             constructor is not visible here due to private fields
   |             help: a tuple variant with a similar name exists: `Some`
```

We should point at the def span of `SomeId` when we say `constructor is not visible here due to private fields`.

**Comment by compiler-errors** [comment]
Current output:

```
error[[E0423]](https://doc.rust-lang.org/stable/error-index.html#E0423): cannot initialize a tuple struct which contains private fields
  --> src/main.rs:22:13
   |
22 |         id: SomeId(32),
   |             ^^^^^^ help: a tuple variant with a similar name exists: `Some`
   |
note: constructor is not visible here due to private fields
  --> src/main.rs:3:23
   |
3  |     pub struct SomeId(u32);    
   |                       ^^^ private field
```

Could provide a structured suggestion, but at least does point at the private field in question.
