### ISSUE TITLE
Setting up the Rust compiler

### ISSUE THREAD

**Issue by Raj2032** [rust-lang/rust#52148]
When I ran the Rustup executable, I was told to install the Visual Studio C++ build tools via this link
http://landinghub.visualstudio.com/visual-cpp-build-tools

This link appears to be dead and should be replaced by this link

https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2017

Please refer to this image when I am prompted to install VS C++ build tools

https://discourse-cdn-sjc1.com/business5/uploads/rust_lang/original/2X/8/8ffaf2d9348097bdb18b380383a270773776a3c3.png

**Comment by csmoe** [comment]
Fixed by https://github.com/rust-lang-nursery/rustup.rs/pull/1428
