### ISSUE TITLE
2018 preview transition confusion

### ISSUE THREAD

**Issue by ehuss** [rust-lang/rust#52146]
I want to see if I am understanding the process for updating a package to use the 2018 preview.  It seems like the following steps must be taken in the following order, otherwise bad things happen.

0. `cargo +nightly install cargo-fix`
1. Add `#![feature(rust_2018_preview)]` to *every* target.
2. Run `cargo +nightly fix --prepare-for 2018 --allow-dirty -- --all-targets`
3. Add `cargo-features = ["edition"]` and `edition = "2018"` to Cargo.toml.

It's not entirely clear to me the relationship between step 1 and 3.  I can't do step 3 first, otherwise `cargo fix` will fail.  However, after doing step 3, I can remove the `rust_2018_preview` attribute?  
Also, I can't run step 2 first, otherwise it doesn't do anything.

Am I understanding it correctly?  The process seemed a little confusing and took some trial and error to figure out the correct steps.  

I also don't know what `cargo +nightly fix` by itself (without the prepare flag) is intended for.  I can't find a scenario where it actually does something, other than finish without changes or error out (because the code still has 2015 syntax).

Using `rustc 1.29.0-nightly (e06c87544 2018-07-06)` and `cargo-fix 0.4.1`

cc @Mark-Simulacrum

**Comment by ehuss** [comment]
BTW, I have now read the [transitioning](https://rust-lang-nursery.github.io/edition-guide/editions/transitioning.html) guide (I was initially looking at something else). I think it does explain this a little more clearly, although the commands needed are a little different.  In particular, you need to update every target (which if you have a lot of tests, can take a while to track everything down) and use `--allow-dirty` and `--all-targets`, otherwise it will fail to compile tests which usually need updating.

**Comment by Dylan-DPC** [comment]
@ehuss since this is resolved, you can close the issue unless you want to propose some other changes to the upgrade guide.
