### ISSUE TITLE
[Rust 2018] Inconsistent anonymous lifetimes

### ISSUE THREAD

**Issue by CryZe** [rust-lang/rust#52142]
This is allowed by Rust 2018:
```rust
impl<T: SomeTrait<'_>> SomeType<T> { ... }
```
while this is not allowed:
```rust
fn foo<T: SomeTrait<'_>>() { ... }
```

**Comment by CryZe** [comment]
I replicated this on the playground: https://play.rust-lang.org/?gist=b7f75c8e5df6945c2065892882b59764&version=nightly&mode=debug&edition=2018

**Comment by aturon** [comment]
Duplicate of https://github.com/rust-lang/rust/issues/45667
