### ISSUE TITLE
RustDoc - compilefail does not allow for code which does not parse

### ISSUE THREAD

**Issue by voelklmichael** [rust-lang/rust#52161]
<short summary of the bug>

I tried this code: (compile with rustdoc!)
pub fn test() {
    //! ```compile_fail
    //! let y = 'y̆';
    //! ```
}

This example does not compile (I guess it does not even parse).
This is unfortunate because I explicitly marked it as "compile_fail'.
(I'm note sure if this is a feature or not.)

Note: This is my first bug report, so I expect that I'm doing everything wrong (is this the correct repository for rustdoc complaints?).

**Comment by csmoe** [comment]
https://doc.rust-lang.org/rustdoc/documentation-tests.html#attributes
enclose the code with triple-backticks and annotate attributes behind it.
```rust
pub fn test() {
    //! ```compile_fail
    //! let y = 'y';
    //!  ```
}
```

**Comment by voelklmichael** [comment]
sorry for the confusion:
The original example looked like this: (note the "non-character" y̆ - it consists of two unicode "characters")

pub fn test() {
    //! ```compile_fail
    //! let y = 'y̆';
    //! ```
}
(Apparently, my clipboard/browser have some issues with unicode)

**Comment by csmoe** [comment]
paste your code into http://play.rust-lang.org/ 
then copy the share link here.

**Comment by voelklmichael** [comment]
https://play.rust-lang.org/?gist=0875f27f004d89d12d87891ad30183ba&version=stable&mode=debug&edition=2015

**Comment by voelklmichael** [comment]
Thanks for reopening.
I don't know if this needs to be fixed or not (I have no productive use-case), but it should be documented somewhere.
A parse_fail attribute would be nice, but maybe of no real-world use for a documentation tool.

**Comment by steveklabnik** [comment]
Triage: this example now passes, so I am assuming this got fixed somewhere along the way. Closing!
