### ISSUE TITLE
[chalkify] duplicate predicates with `predicates_defined_on`

### ISSUE THREAD

**Issue by scalexm** [rust-lang/rust#52187]
It seems like I missed this one when reviewing #51895:
https://github.com/rust-lang/rust/blob/c6807bb1b282e0c5398aa4e659dbc165b6f3c81b/src/test/ui/chalkify/lower_env1.stderr#L7-L8

(same duplicate just below in that same file)

I'm just opening this issue for reference, I'll take some time to investigate later.

cc @nikomatsakis if it's still there when you get back, cc @tmandry

**Comment by scalexm** [comment]
Hint: this duplication is only triggered when using the following form for a super trait:
```rust
trait Bar where Self: Foo {}
```
For the alternative syntax `trait Bar: Foo {}` as well as any where clause not of the form `Self: ...`, the output seems fine.

**Comment by scalexm** [comment]
Ok found the culprit: `explicit_predicates_of` collects the where clauses explicitly written on the trait, and then also adds those returned by `super_predicates_of`. But `super_predicates_of` collects both the « inline » super trait bounds e.g. `trait Bar: Foo` *and* the ones included as where clauses e.g. `where Self: Foo`, but the `where Self: Foo` was already collected before calling `super_predicates_of`, hence the duplicate.

Overall, this is not a big problem apart from giving chalk (and maybe some parts of rustc not using e.g. a `HashMap` or `HashSet`) the same clause twice. However for clean outputs, I’d just suggest having an additional `explicit_super_predicates_of` or something like that (which would not need to be added as a query), which would only return super trait bounds written in the form `trait Bar: Foo` and which would be used by `explicit_predicates_of`.

cc @nikomatsakis

**Comment by nikomatsakis** [comment]
Sounds about right to me
