### ISSUE TITLE
Sequential checked_add and saturating_add of constants don't get combined together

### ISSUE THREAD

**Issue by scottmcm** [rust-lang/rust#52203]
```rust
pub fn test_saturating(a: u32) -> u32 {
    a.saturating_add(7).saturating_add(13)
}
```

gets compiled to

```rust
playground::test_saturating:
	add	edi, 7
	mov	eax, -1
	cmovb	edi, eax
	add	edi, 13
	cmovae	eax, edi
	ret
```

but ideally it would get compiled to `a.saturating_add(20)`, aka

```rust
playground::test_saturating:
	add	edi, 20
	mov	eax, -1
	cmovae	eax, edi
	ret
```

Ditto for checked_add.

Playground repro: https://play.rust-lang.org/?gist=eeea31ea85491e38bdd6d456b9f6e47f&version=nightly&mode=release&edition=2015

Found looking at step_by, which would like `.next(); .nth(step)` to collapse nicely for ranges (https://github.com/rust-lang/rust/issues/52065).

**Comment by hellow554** [comment]
I ask myself if this should be fixed in LLVM directly, rather than rust, so two consecutive saturatings/checked adds should be merged?

**Comment by scottmcm** [comment]
@hellow

**Comment by scottmcm** [comment]
@hellow554 Yes, it'll probably need LLVM changes unless there's some way we could emit it differently that would work better -- this would be rather complicated to do MIR, AFAICT.

**Comment by scottmcm** [comment]
Confirmed that LLVM can't do this kind of fold in C++ either.  Filed an LLVM bug:
- https://bugs.llvm.org/show_bug.cgi?id=38146

**Comment by scottmcm** [comment]
Might get fixed, or at least easier to fix, if https://github.com/rust-lang/rust/issues/55286 happens.
