### ISSUE TITLE
#![feature(proc_macro)] breaks some custom derive attributes

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#52219]
Originally reported as https://github.com/rust-lang-nursery/rustfix/issues/126 this is reduced to:

```rust
// foo.rs
#![crate_type = "proc-macro"]

extern crate proc_macro;

use proc_macro::TokenStream;

#[proc_macro_derive(Foo)]
pub fn foo(a: TokenStream) -> TokenStream {
    "".parse().unwrap()
}

#[proc_macro_derive(Bar, attributes(custom))]
pub fn bar(a: TokenStream) -> TokenStream {
    "".parse().unwrap()
}
```

```rust
// bar.rs
#![cfg_attr(broken, feature(proc_macro))]
#![crate_type = "lib"]

#[macro_use]
extern crate foo;

#[derive(Foo, Bar, Debug)]
#[custom = "test"]
pub enum A{
    B,
    C,
}
```

compiles with:

```
$ rustc +nightly foo.rs
$ rustc +nightly bar.rs -L .
$ rustc +nightly bar.rs -L . --cfg broken
error: cannot find attribute macro `custom` in this scope
 --> bar.rs:8:3
  |
8 | #[custom = "test"]
  |   ^^^^^^

error: aborting due to previous error
```

**Comment by alexcrichton** [comment]
cc @petrochenkov, I'm not really sure what this classifies under, it seems like maybe https://github.com/rust-lang/rust/pull/50911 although `#![feature(use_extern_macros)]` doesn't break it, only `#![feature(proc_macro)]` does. After https://github.com/rust-lang/rust/pull/52081 though it may be broken by `use_extern_macros` (I'm not 100% sure where this is happening)

**Comment by petrochenkov** [comment]
>I'm not really sure what this classifies under, it seems like maybe #50911 although `#![feature(use_extern_macros)]` doesn't break it

This falls under ["attribute resolution is mess"](https://github.com/rust-lang/rust/issues/35896#issuecomment-403841893) and ["some things are gated by `proc_macro` while they should be gated by macro modularization (`use_extern_macros`)"](https://github.com/rust-lang/rust/pull/52081#issuecomment-403851396).

**Comment by cramertj** [comment]
I hit this error last week when trying to update a crate that used `failure`'s derive macros. I found that `use`ing the macro would give me the attribute error, but `#[macro_use]`ing the crate worked.

**Comment by alexcrichton** [comment]
@cramertj I think that may be a separate bug, can you file a different issue?

I believe I've fixed this issue in https://github.com/rust-lang/rust/pull/52230
