### ISSUE TITLE
Procedural macro crates should require at most one definition per macro name

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#52225]
Discovered by @alercah [here](https://github.com/rust-lang/rust/issues/35896#issuecomment-403874183), this crate should be rejected:

```rust
#![crate_type = "proc-macro"]

extern crate proc_macro;

use proc_macro::TokenStream;

#[proc_macro]
pub fn bad(_ : TokenStream) -> TokenStream { "".parse().unwrap() }

#[proc_macro_derive(bad)]
pub fn deriver(_ : TokenStream) -> TokenStream { "".parse().unwrap() }
```

**Comment by alexcrichton** [comment]
I believe this would be fixed by @petrochenkov suggestion [here](https://github.com/rust-lang/rust/issues/35896#issuecomment-403886824) where definition of a macro inserts an entry into the macro namespace, although @petrochenkov correct me if I'm wrong!

**Comment by petrochenkov** [comment]
>`#[proc_macro_derive(bad)]`

The issue solvable by inserting a dummy entry into macro namespace is not about inert attributes in derives, but about this case.

```rust
macro foo() {} // Should be future-proofed and report an error

#[proc_macro]
fn foo(...) -> ... { ... }
```
