### ISSUE TITLE
Type error on `if` expression mentions `match` arms

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#52228]
e.g.,

```
fn foo() -> Option<usize> {
    if true {
        0
    } else {
        1
    }
}
```

Gives `error[E0308]: match arms have incompatible types`

**Comment by LightDiscord** [comment]
It's because the return type and your declaration doesn't match. You should return an Option variant.

```rust
fn foo() -> Option<usize>
    if true {
        Some(0)
    } else {
        Some(1)
    }
}
```

**Comment by dgriffen** [comment]
I would be interested in picking this up but I'm not sure where to begin.

**Comment by varkor** [comment]
@nrc: I can't reproduce this. [This example works fine, for instance](https://play.rust-lang.org/?gist=b00e52296f4b990d008320924233441a&version=nightly&mode=debug&edition=2015), with `error[E0308]: mismatched types`. Can you provide a Playground link?

**Comment by nrc** [comment]
Sorry, I've lost the example that led to this and can't repro with a simple case :-(
