### ISSUE TITLE
Apache and MIT licenses do not contain copyright name or year

### ISSUE THREAD

**Issue by nektro** [rust-lang/rust#52236]

**Comment by nektro** [comment]
Thanks for the link. Apache instead has a [`Copyright [yyyy] [name of copyright owner]`](https://github.com/rust-lang/rust/blob/master/LICENSE-APACHE#L189). Didn't know if this was intended, would be happy to close otherwise :)

**Comment by frewsxcv** [comment]
My understanding is that section is not meant to be filled out – it's a template for how Apache wants you to put that text at the top of each licensed file.
