### ISSUE TITLE
Brace vs Parenthesis mismatch error message could be more helpful

### ISSUE THREAD

**Issue by KallDrexx** [rust-lang/rust#52237]
```
enum Test {
    Val1 { val: u32 },
}

fn main() {
    let test = Test::Val1{val: 3};
    match test {
        Test::Val1(val) => println!("{}", val),
    }
}
```

This gives the following error
```
Compiling playground v0.0.1 (file:///playground)
error[E0532]: expected tuple struct/variant, found struct variant `Test::Val1`
 --> src/main.rs:8:9
  |
8 |         Test::Val1(val) => println!("{}", val),
  |         ^^^^^^^^^^ did you mean `Test::Val1 { /* fields */ }`?

error: aborting due to previous error

For more information about this error, try `rustc --explain E0532`.
error: Could not compile `playground`.

To learn more, run the command again with --verbose.
```

This was confusing for a bit as my enum had a variety of tuple vs struct enums (parenthesis vs brace) and it was very confusing for a few minutes on why it was saying I was wrong, yet telling me to put in what seemed like the same value I had in.  Fonts can make it hard to notice the difference that the suggestion is using braces and my code is using parenthesis.

It would be awesome if the suggestion could detect this difference and suggest the correct notation.

**Comment by JohnTitor** [comment]
Current output:

```
error[E0532]: expected tuple struct/variant, found struct variant `Test::Val1`
 --> src/lib.rs:8:9
  |
2 |     Val1 { val: u32 },
  |     ----------------- `Test::Val1` defined here
...
8 |         Test::Val1(val) => println!("{}", val),
  |         ^^^^^^^^^^ did you mean `Test::Val1 { /* fields */ }`?
```

**Comment by estebank** [comment]
Current output:

```
error[E0532]: expected tuple struct or tuple variant, found struct variant `Test::Val1`
 --> src/main.rs:8:9
  |
2 |     Val1 { val: u32 },
  |     ----------------- `Test::Val1` defined here
...
8 |         Test::Val1(val) => println!("{}", val),
  |         ^^^^^^^^^^^^^^^ help: use struct pattern syntax instead: `Test::Val1 { val }`
```

I don't think we can do much to make the difference between `()` and `{}` more obvious (other than coloring or more verbose output), which I am disinclined to do for this case. If we make the output more verbose, people have a tendency to not read as much of them. I have planned doing some more work on the coloring side that has a larger scope than this one case.

Closing as handled, but do not hesitate to make your case if you believe it should remain open.
