### ISSUE TITLE
complie errors

### ISSUE THREAD

**Issue by dulumao** [rust-lang/rust#52249]
[root@node1 tikv]# rustup override set nightly-2017-05-29
info: syncing channel updates for 'nightly-2017-05-29-x86_64-unknown-linux-gnu'
info: latest update on 2017-05-29, rust version 1.19.0-nightly (d47cf08d5 2017-05-28)
info: downloading component 'rustc'
info: downloading component 'rust-std'
info: downloading component 'cargo'
info: downloading component 'rust-docs'
info: installing component 'rustc'
info: installing component 'rust-std'
info: installing component 'cargo'
info: installing component 'rust-docs'
info: override toolchain for '/Servdata/server/tikv' set to 'nightly-2017-05-29-x86_64-unknown-linux-gnu'

  nightly-2017-05-29-x86_64-unknown-linux-gnu installed - rustc 1.19.0-nightly (d47cf08d5 2017-05-28)

[root@node1 tikv]# make build
cargo build --features "default portable sse no-fail"
    Updating git repository `https://github.com/rust-fuzz/libfuzzer-sys.git`
    Updating registry `https://github.com/rust-lang/crates.io-index`
    Updating git repository `https://github.com/pingcap/rust-rocksdb.git`
    Updating git repository `https://github.com/pingcap/kvproto.git`
    Updating git repository `https://github.com/pingcap/tipb.git`
    Updating git repository `https://github.com/busyjay/jemallocator.git`
    Updating git repository `https://github.com/pingcap/murmur3.git`
    Updating git repository `https://github.com/busyjay/libz-sys.git`
    Updating git repository `https://github.com/busyjay/lz4-rs.git`
    Updating git repository `https://github.com/gyscos/zstd-rs.git`
    Updating git repository `https://github.com/busyjay/rust-snappy.git`
    Updating git repository `https://github.com/alexcrichton/bzip2-rs.git`
 Downloading sys-info v0.5.1
 Downloading derive_more v0.11.0
 Downloading tokio-timer v0.1.1
 Downloading url v1.7.0
 Downloading grpcio v0.3.0
 Downloading slog-async v2.3.0
 Downloading utime v0.2.0
 Downloading futures-cpupool v0.1.8
 Downloading lazy_static v0.2.8
 Downloading slog-stdlog v3.0.2
 Downloading byteorder v0.5.1
 Downloading futures v0.1.17
 Downloading prometheus v0.4.2
 Downloading crc v1.2.0
 Downloading raft v0.3.0
 Downloading protobuf v2.0.2
 Downloading serde_json v1.0.2
 Downloading log v0.3.9
 Downloading regex v0.1.70
 Downloading backtrace v0.2.3
 Downloading slog v2.2.3
 Downloading clap v2.23.3
 Downloading serde v1.0.52
 Downloading fail v0.2.0
 Downloading uuid v0.6.3
 Downloading crossbeam-channel v0.2.1
 Downloading slog-term v2.4.0
 Downloading toml v0.4.3
 Downloading fxhash v0.2.1
 Downloading rand v0.3.14
 Downloading bitflags v1.0.1
 Downloading mio v0.5.1
 Downloading zipf v0.2.0
 Downloading time v0.1.38
 Downloading serde_derive v1.0.8
 Downloading libc v0.2.42
 Downloading indexmap v1.0.1
 Downloading tokio-core v0.1.6
 Downloading fnv v1.0.5
 Downloading chrono v0.4.0
 Downloading nix v0.9.0
 Downloading prometheus-static-metric v0.1.4
 Downloading rustc-serialize v0.3.24
 Downloading quick-error v0.2.2
 Downloading tempdir v0.3.4
 Downloading slog-scope v4.0.1
 Downloading fs2 v0.4.0
 Downloading gcc v0.3.53
 Downloading syn v0.13.11
 Downloading quote v0.5.2
 Downloading unicode-xid v0.1.0
 Downloading proc-macro2 v0.3.8
 Downloading slab v0.3.0
 Downloading percent-encoding v1.0.0
 Downloading matches v0.1.2
 Downloading idna v0.1.0
 Downloading unicode-normalization v0.1.2
 Downloading unicode-bidi v0.2.3
 Downloading grpcio-sys v0.2.3
 Downloading log v0.4.1
 Downloading cfg-if v0.1.3
 Downloading pkg-config v0.3.8
 Downloading cc v1.0.3
 Downloading cmake v0.1.28
 Downloading thread_local v0.3.5
 Downloading take_mut v0.2.2
 Downloading lazy_static v1.0.0
 Downloading unreachable v1.0.0
 Downloading void v1.0.2
 Downloading winapi v0.2.8
 Downloading kernel32-sys v0.2.2
 Downloading winapi-build v0.1.1
 Downloading num_cpus v1.6.2
 Downloading crossbeam v0.2.12
 Downloading spin v0.4.6
 Downloading hyper v0.9.18
 Downloading unicase v1.4.0
 Downloading typeable v0.1.2
 Downloading traitobject v0.0.1
 Downloading language-tags v0.2.2
 Downloading cookie v0.2.5
 Downloading solicit v0.4.4
 Downloading mime v0.2.2
 Downloading httparse v1.1.2
 Downloading rustc_version v0.1.7
 Downloading semver v0.1.20
 Downloading hpack v0.2.0
 Downloading lazy_static v0.1.16
 Downloading quick-error v1.2.1
 Downloading rand v0.4.2
 Downloading byteorder v1.2.3
 Downloading num-traits v0.1.32
 Downloading dtoa v0.4.1
 Downloading itoa v0.3.1
 Downloading regex-syntax v0.3.1
 Downloading aho-corasick v0.5.3
 Downloading utf8-ranges v0.1.3
 Downloading memchr v0.1.11
 Downloading thread_local v0.2.7
 Downloading thread-id v2.0.0
 Downloading rustc-demangle v0.1.2
 Downloading dbghelp-sys v0.2.0
 Downloading backtrace-sys v0.1.15
 Downloading glob v0.2.11
 Downloading bitflags v0.8.2
 Downloading vec_map v0.7.0
 Downloading term_size v0.3.0
 Downloading ansi_term v0.9.0
 Downloading unicode-width v0.1.4
 Downloading unicode-segmentation v1.1.0
 Downloading atty v0.2.2
 Downloading strsim v0.6.0
 Downloading crossbeam-utils v0.4.1
 Downloading crossbeam-epoch v0.4.3
 Downloading parking_lot v0.5.5
 Downloading smallvec v0.6.2
 Downloading arrayvec v0.4.7
 Downloading crossbeam-utils v0.3.2
 Downloading memoffset v0.2.1
 Downloading scopeguard v0.3.3
 Downloading nodrop v0.1.12
 Downloading owning_ref v0.3.3
 Downloading parking_lot_core v0.2.13
 Downloading stable_deref_trait v1.0.0
 Downloading term v0.5.1
 Downloading isatty v0.1.7
 Downloading num v0.1.32
 Downloading num-integer v0.1.32
 Downloading num-iter v0.1.32
 Downloading miow v0.1.5
 Downloading slab v0.1.3
 Downloading nix v0.5.1
 Downloading net2 v0.2.23
 Downloading bytes v0.3.0
 Downloading ws2_32-sys v0.2.1
 Downloading bitflags v0.4.0
 Downloading serde_derive_internals v0.15.1
 Downloading quote v0.3.12
 Downloading syn v0.11.11
 Downloading synom v0.11.3
 Downloading unicode-xid v0.0.4
 Downloading tokio-io v0.1.1
 Downloading iovec v0.1.0
 Downloading bytes v0.4.1
 Downloading scoped-tls v0.1.0
 Downloading mio v0.6.6
 Downloading lazycell v0.4.0
 Downloading bitflags v0.9.1
 Downloading signal v0.4.1
 Downloading procinfo v0.3.1
 Downloading nom v1.2.4
   Compiling crossbeam-utils v0.4.1
   Compiling unicode-width v0.1.4
   Compiling scopeguard v0.3.3
   Compiling regex-syntax v0.3.1
   Compiling httparse v1.1.2
   Compiling byteorder v1.2.3
   Compiling quick-error v1.2.1
   Compiling scoped-tls v0.1.0
error: the struct `#[repr(align(u16))]` attribute is experimental (see issue #33626)
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-utils-0.4.1/src/cache_padded.rs:20:1
   |
20 | / pub struct CachePadded<T> {
21 | |     inner: T,
22 | | }
   | |_^
   |
   = help: add #![feature(repr_align)] to the crate attributes to enable

error: non-string literals in attributes, or string literals in top-level positions, are experimental (see issue #34981)
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/crossbeam-utils-0.4.1/src/cache_padded.rs:19:1
   |
19 | #[repr(align(64))]
   | ^^^^^^^^^^^^^^^^^^
   |
   = help: add #![feature(attr_literals)] to the crate attributes to enable

error: aborting due to previous error(s)

error: Could not compile `crossbeam-utils`.
Build failed, waiting for other jobs to finish...
error: build failed
make: *** [build] 错误 101
[root@node1 tikv]#

**Comment by oli-obk** [comment]
I would assume that `crossebeam-utils-0.4.1` is not compatible wtih `nightly-2017-05-29`. Is there any particular reason you are using a very old nightly?

**Comment by csmoe** [comment]
Based on my previous experience of contributing to tikv, it uses `rust-toolchain` to specific rustc-verion, please follow its contributing guide.
