### ISSUE TITLE
rustdoc does not document associated constants in structs

### ISSUE THREAD

**Issue by vks** [rust-lang/rust#52260]
The following does not get documented as expected:
```rust
pub struct Foo;

impl Foo {
    /// This doc comment won't be shown anywhere.
    pub const BAR: u32 = 7;
}
```
The documentation comment seems to be ignored.

**Comment by ollie27** [comment]
Which version of rustdoc are you using? It works fine for me using 1.27 stable and newer:

![image](https://user-images.githubusercontent.com/7189418/42661299-b2b21ed2-8625-11e8-88b8-acfee8e81e3b.png)

**Comment by vks** [comment]
I don't remember which version I was using, but I can't reproduce the bug anymore with rustc 1.29.0-nightly (6a1c0637c 2018-07-23).
