### ISSUE TITLE
Better documentation for Iter::zip behavior

### ISSUE THREAD

**Issue by Lucretiel** [rust-lang/rust#52279]
In particular, we should specify and document what exactly zip does when its first child terminates. Currently, as soon as `self.a.next()` returns None, it short-circuits execution without calling `self.b.next()`. This could lead to some potential surprising behavior:

```
self.a  1  2  3     5  6
self.b  1  2  3  4  5  6
------
self    11 22 33    54 65
```

To be clear, I'm not saying this behavior is bad; just that it should be more explicitly documented. This will allow developers to more confidently build abstractions on top of Zip, knowing exactly what it does with the underlying iterator.

**Comment by rustyseris** [comment]
In this case, I would even day that the documentation is misleading.
`When either iterator returns None, all further calls to next will return None.`

**Comment by frewsxcv** [comment]
This was addressed in https://github.com/rust-lang/rust/pull/50719, which will hit stable Rust on August 2nd.

https://doc.rust-lang.org/stable/std/iter/trait.Iterator.html#method.zip

https://doc.rust-lang.org/beta/std/iter/trait.Iterator.html#method.zip

**Comment by Lucretiel** [comment]
That's close, but I'd propose a further change, to emphasize that zip always does `a.next(); b.next()`, and that if `a.next()` returns None, it short circuits and returns None immediately, without calling `b.next()`

**Comment by frewsxcv** [comment]
Opened a pull request for this: https://github.com/rust-lang/rust/pull/52477
