### ISSUE TITLE
beta backport PR 52232

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#52311]
This is a dummy issue linking to PR #52232 so that we can have an open issue (which is apparently a requirement if one wants to leverage the rfcbot).

**Comment by pnkfelix** [comment]
@rfcbot fcp merge

I propose that we approve backporting #52232 to beta.

Since time is somewhat limited, and back ports are usually less controversial than the usual things that go through the fcp process, I'm going to add the additional note if there are no unresolved formal concerns in a week's time, I will just check off any unmarked check boxes. (This effectively inverts the rfcbot into "approved by default.")

**Comment by kennytm** [comment]
What about stable?

**Comment by pnkfelix** [comment]
ugh I guess I will open a separate issue for stable? hashtag what a pain

**Comment by pnkfelix** [comment]
(who was the genius who suggested using async to resolve this. ... ;)
