### ISSUE TITLE
stable backport PR 52232

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#52312]
This is a dummy issue linking to PR #52232 so that we can have an open issue (which is apparently a requirement if one wants to leverage the rfcbot).

**Comment by pnkfelix** [comment]
@rfcbot fcp merge

I propose that we approve backporting #52232 to stable.

I'm more wary of stable backports than I am of beta backports, so: I am **not** inverting the rfcbot on this ticket the same way that I did on #52311. If we do not get a sufficient number of check boxes ticked off, then the PR will **not** be approved for a backport to the stable channel.

**Comment by nagisa** [comment]
@rfcbot reviewed

I find it kind of objectionable that we’ll end up releasing not one but *two* point releases this cycle…

**Comment by pietroalbini** [comment]
By the way, isn't the core team responsible for approving point releases?

**Comment by Mark-Simulacrum** [comment]
The core team also discussed this today and we're generally in favor of a 1.27.2 release, scheduled for next Thursday. I will be creating and cross-linking an internals post to this thread after the next nightly release asking for interested users to test and try to find holes in the fix (and, probably, match ergonomics in general) with the goal of finding problems before the point release.

**Comment by pnkfelix** [comment]
closing, @Mark-Simulacrum says this has been backported.
