### ISSUE TITLE
beta backport PR 51956

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#52313]
This is a dummy issue linking to PR #51956 so that we can have an open issue (which is apparently a requirement if one wants to leverage the rfcbot).

**Comment by pnkfelix** [comment]
@rfcbot fcp merge

I propose that we approve backporting this to beta.

Since time is somewhat limited, and back ports are usually less controversial than the usual things that go through the fcp process, I'm going to add the additional note **if there are no unresolved formal concerns in a week's time, I will just check off any unmarked check boxes**. (This effectively inverts the rfcbot into "approved by default.")

----

@oli-obk You had proposed discussing this at a compiler meeting. I *assume* that such a discussion actually occurred during my absence. If your objection for some reason did not apply to nightly but *does* apply to beta, I encourage you to issue a formal concern here and hopefully that will prompt further conversation that will let us resolve this.

**Comment by pnkfelix** [comment]
darn it forgot to add tag first

**Comment by pnkfelix** [comment]
@rfcbot fcp merge

I propose that we approve backporting this to beta.

Since time is somewhat limited, and back ports are usually less controversial than the usual things that go through the fcp process, I'm going to add the additional note **if there are no unresolved formal concerns in a week's time, I will just check off any unmarked check boxes**. (This effectively inverts the rfcbot into "approved by default.")

----

@oli-obk You had proposed discussing this at a compiler meeting. I *assume* that such a discussion actually occurred during my absence. If your objection for some reason did not apply to nightly but *does* apply to beta, I encourage you to issue a formal concern here and hopefully that will prompt further conversation that will let us resolve this.

**Comment by oli-obk** [comment]
We did indeed discuss this and I have no objections to backporting this. Quite the opposite. Not backporting would mean some people can't document their code anymore once this hits stable
