### ISSUE TITLE
Update emscripten-llvm to version 7

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/rust#52323]
See https://github.com/kripken/emscripten-fastcomp/issues/193#issuecomment-403834842

emscripten already supports the wasm backend in LLVM7, so we should move the current emscripten-llvm from version 4.0 to that, so that we can remove all the workarounds lying around for LLVM < 5.0 (LLVM 5 is the new minimum supported version).

**Comment by nikic** [comment]
I've tried updating to emscripten 1.38.15 locally. There were some test failures related to exported symbols. E.g.

```
#![feature(linkage)]
#[linkage = "external"]
pub static TEST2: bool = true;
fn main() {}
```

results in

> ERROR:root:undefined exported function: "__ZN3foo5TEST217he2beacac66605ee4E"

emcc is called with `"EXPORTED_FUNCTIONS=[\"__ZN3foo5TEST217he2beacac66605ee4E\",\"_main\",\"_rust_eh_personality\"]"`.

Possibly EXPORTED_FUNCTIONS previously also worked with non-function symbols but now no longer does?

**Comment by kripken** [comment]
Emscripten recently changed to error on undefined symbols, instead of just warn, that might be the cause of that error. You can disable that with `-s ERROR_ON_UNDEFINED_SYMBOLS=0` (but, maybe this is something worth fixing).

**Comment by nikic** [comment]
@kripken Rust explicitly passes `ERROR_ON_UNDEFINED_SYMBOLS=1` to emcc, so it was already operating in this mode beforehand. I ended up dropping statics from the exported symbols if emscripten is used (https://github.com/rust-lang/rust/pull/55626/files#diff-f6e6083c951157a35938312877e731b6R391). Does that sound reasonable? From what I understand, it doesn't really make sense to export anything other than functions when emscripten is used.

**Comment by kripken** [comment]
Oh, sorry, then my previous comment is irrelevant then.

Does "statics" mean global variables? It's possible to export both functions and global variables in emscripten, but i think it's extremely rare that globals are needed to be exported (when a global variable is exported, its address is exported).

**Comment by nikic** [comment]
@kripken Yeah, by statics I mean global variables. How does one specify globals that should be exported? Should they be part of `EXPORTED_FUNCTIONS` or something else?

**Comment by kripken** [comment]
@nikic we export them in shared modules (MAIN_MODULE etc. flags), but there isn't a way to export specific ones, I believe.
