### ISSUE TITLE
Consolidate generic "parameter" versus "argument" distinction

### ISSUE THREAD

**Issue by varkor** [rust-lang/rust#52327]
There's currently an internal distinction in the terminology for generic parameters (the variables in a type signature) and generic arguments (the actual values for those variables that is passed in).

For example:
```rust
fn foo<'a, B, const C: usize>(); // `'a`, `B`, `C` are generic parameters

foo::<'static, usize, 0>(); // `'static`, `usize`, `0` are generic arguments
```

This terminology is used inconsistently in user-facing strings, like error messages. For example, `E0087` has text such as `expected at most 0 type parameters, found 1 type parameter` (when they're actually arguments), whereas `E0244` (`wrong number of type arguments`) uses the correct terminology.

Currently "parameter" is often used instead of "argument", but it would be nice to make this consistent.

**Comment by cramertj** [comment]
:bike: :derelict_house:: I usually call them both "parameters." If you said "generic argument", I'd think you were referring to an argument whose type was generic.

**Comment by eddyb** [comment]
We could keep using "parameter" if we're referring to the *definition*, as opposed to the *use*.
E.g. "`Vec` has 1 type parameter, but 2 types were given".

**Comment by johnbcoughlin** [comment]
@varkor I'd like to get my feet wet, so I'm going to attempt this issue!

**Comment by saleemjaffer** [comment]
@varkor I would like to take a shot at this if its okay. I'm a newbie to rust.

**Comment by varkor** [comment]
@saleemjaffer: you're welcome to take a look at this. I don't have much advice about where to start, other than searching through the codebase for instances of "generic parameter"/"generic argument" and similar and checking whether they're consistent with the definitions above. I think this has improved lately, so there may no longer be so many cases that need fixing.

**Comment by varkor** [comment]
@eddy [points out](https://discordapp.com/channels/442252698964721669/443151243398086667/616973782409805860) that:
> the error "error[E0061]: this function takes 1 parameter but 0 parameters were supplied" should probably say "N arguments were supplied" instead of "N parameters were supplied"

**Comment by mightyiam** [comment]
Which directories contain the code that creates error messages, please?

**Comment by varkor** [comment]
@mightyiam: the diagnostics messages appear in most of the `compiler/` subdirectories. However, I'm not sure of specific examples where this parameter/argument distinction is incorrect now: I think this issue has slowly been addressed since it was opened. If you can find any more incorrect examples, then you'd be very welcome to open a pull request correcting them, but it may be a wild goose chase. I'm going to close this issue accordingly, but we can reopen if mistakes are found.
