### ISSUE TITLE
Rustdoc sidebar: methods from impls on references to generic types differing in mutability have the same link

### ISSUE THREAD

**Issue by lqd** [rust-lang/rust#52321]
In the sidebar for `Option`, https://doc.rust-lang.org/nightly/std/option/enum.Option.html, we can see two `cloned` methods.

![image](https://user-images.githubusercontent.com/247183/42654762-0a97fc22-861a-11e8-8973-b997d6f7ae4b.png)

The problem is that both links have the same URL even though they come from different impls: they point to https://doc.rust-lang.org/nightly/std/option/enum.Option.html#method.cloned when the second one should probably point to https://doc.rust-lang.org/nightly/std/option/enum.Option.html#method.cloned-1

Assigning to imperio as he requested I do so :)

**Comment by ollie27** [comment]
This looks like a duplicate of #50746.

**Comment by lqd** [comment]
True :) thank you @ollie27
