### ISSUE TITLE
Proc-macro definition attributes are accepted in arbitrary non-item positions

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rust#52329]
For example,
```rust
#![feature(proc_macro)]

fn main() {
    #[proc_macro]
    let x = 10;
    #[proc_macro_attribute]
    let x = 11;
    #[proc_macro_derive]
    let x = 12;
}
```

*A lot* of stable built-in attributes have this issue as well, but if we can fix it in this specific case, then why not.
I think these kinds of checks are usually performed in `librustc/hir/check_attr.rs`.

**Comment by csmoe** [comment]
For some built-in attributes like:
https://github.com/rust-lang/rust/blob/64f7de92166f1f7d940575feff57ac33bc384550/src/libstd/panicking.rs#L176-L186
is this one legal in this issue?

**Comment by petrochenkov** [comment]
@csmoe 
Yes, a number of attributes is valid in non-item positions.
This issue is only about three `#[proc_macro*]` attributes.

**Comment by petrochenkov** [comment]
Closing, see https://github.com/rust-lang/rust/pull/52367#issuecomment-405122349
