### ISSUE TITLE
rustbuild: panic executing tidy with local rustc

### ISSUE THREAD

**Issue by ishitatsuyuki** [rust-lang/rust#52337]
config.toml: https://gist.github.com/0c9bf562b8e4e14142e2549059111e61

```
$ ./x.py test src/tools/tidy
Updating only changed submodules
Submodules updated in 0.02 seconds
    Finished dev [unoptimized] target(s) in 0.21s                                                                                                            
thread 'main' panicked at 'assertion failed: !use_snapshot || stage == 0', bootstrap/builder.rs:778:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
failed to run: /home/ishitatsuyuki/Documents/rust/build/bootstrap/debug/bootstrap test src/tools/tidy
Build completed unsuccessfully in 0:00:01
```

**Comment by jyn514** [comment]
@ishitatsuyuki I can't reproduce this, `rustc = "/home/joshua/.local/lib/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rustc"` works fine for me. Are you still running into this?

**Comment by jyn514** [comment]
Well, it does give an error:
```
./x.py fmt is not supported on this channel
```
so I guess there's another bug that it should use the stage0.txt rustfmt instead of blindly using nightly. But that's a separate issue IMO.

**Comment by ishitatsuyuki** [comment]
Well, it's 3 years old. Time to close this, workflows have changed anyway.
