### ISSUE TITLE
`Ty::ty_to_def_id` does not yield all possible `DefId`s that it could

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#52341]
I don't know if this is really problem, but e.g. the `ReachEverythingInTheInterfaceVisitor` reimplements this function (and yields a bunch of other `DefId`s, too.

This needs some looking at

Mostly leaving this here so I don't forget

**Comment by eddyb** [comment]
`ty_to_def_id` is probably a hack for cache keying, and should ideally be removed?
