### ISSUE TITLE
Expansion info is reset for the mark

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust#52363]
```rust
format_args!({ #[derive(repro)] struct ProcMacroHack; });
```

Correct behavior on all compilers 1.15.0 through 1.28.0-beta.10:

```
error: format argument must be a string literal.
 --> src/main.rs:5:18
  |
5 |     format_args!({ #[derive(repro)] struct ProcMacroHack; });
  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

But on nightly:
(UPDATE: The ICE is now suppressed, but the issue still needs investigation.)
```
thread 'main' panicked at 'expansion info is reset for the mark 2
old: ExpnInfo {
    call_site: Span {
        lo: BytePos(
            56
        ),
        hi: BytePos(
            113
        ),
        ctxt: #0
    },
    def_site: None,
    format: MacroBang(
        format_args
    ),
    allow_internal_unstable: true,
    allow_internal_unsafe: false,
    local_inner_macros: false,
    edition: Edition2015
}
new: ExpnInfo {
    call_site: Span {
        lo: BytePos(
            88
        ),
        hi: BytePos(
            109
        ),
        ctxt: #0
    },
    def_site: None,
    format: MacroAttribute(
        derive(repro)
    ),
    allow_internal_unstable: true,
    allow_internal_unsafe: false,
    local_inner_macros: false,
    edition: Edition2015
}', libsyntax_pos/hygiene.rs:114:17
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: internal compiler error: unexpected panic
```

---

#### Repro script

```sh
#!/bin/sh

cargo new repro
cargo new --lib repro_macro

cat >repro/src/main.rs <<'REPRO'
#[macro_use]
extern crate repro_macro;

fn main() {
    format_args!({ #[derive(repro)] struct ProcMacroHack; });
}
REPRO

cat >>repro/Cargo.toml <<'REPRO'
repro_macro = { path = "../repro_macro" }
REPRO

cat >repro_macro/src/lib.rs <<'REPRO'
extern crate proc_macro;
use proc_macro::TokenStream;

#[proc_macro_derive(repro)]
pub fn repro(_input: TokenStream) -> TokenStream {
    "".parse().unwrap()
}
REPRO

cat >>repro_macro/Cargo.toml <<'REPRO'
[lib]
proc-macro = true
REPRO

cargo build --manifest-path repro/Cargo.toml
```

---

Mentioning @petrochenkov because this bug was exposed by #51726.

**Comment by pnkfelix** [comment]
visiting for triage.

@petrochenkov do you have any status update to report here?

**Comment by petrochenkov** [comment]
No updates, low priority.
I'll look into this after edition-related macro modularization work is complete.

**Comment by petrochenkov** [comment]
In the worst case, the issue can be masked by turning the assert into debug assert.

**Comment by pnkfelix** [comment]
downgrading to P-medium to reflect lower-priority status.

**Comment by nikomatsakis** [comment]
@petrochenkov 

> In the worst case, the issue can be masked by turning the assert into debug assert.

So do we want to remove the assertion and file a follow-up issue to resurrect it? Seems like we should "close the issue" by doing that? 

[Some discussion here](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/subject/weekly.20meeting.202018-08-23/near/132641048)

**Comment by nikomatsakis** [comment]
(In particular, it seems a bit odd to have a `debug_assert` that we know fails sometimes.)

**Comment by nikomatsakis** [comment]
Bumping up to P-high to "stop the bleeding"

**Comment by arielb1** [comment]
For easy reference: we are referring to the following assertion:
https://github.com/rust-lang/rust/blob/20ce91076af125eda82bb36e446e67b1c7af4218/src/libsyntax_pos/hygiene.rs#L107-L116

**Comment by petrochenkov** [comment]
Assert is removed in https://github.com/rust-lang/rust/pull/53653

**Comment by petrochenkov** [comment]
I'll keep this issue open for future investigation.
Expansion data not being immutable is clearly a bug, this shouldn't happen.

**Comment by petrochenkov** [comment]
Fixed in https://github.com/rust-lang/rust/pull/62476
