### ISSUE TITLE
libtinfo.so.5: error adding symbols: DSO missing from command line, Debian 8.1

### ISSUE THREAD

**Issue by blabarna** [rust-lang/rust#52369]
Good day!
Please, can you help me with the problem, or give me info about such problem,
which appears when I tried to build grin using this manual:
https://github.com/mimblewimble/grin/blob/master/doc/build.md

on the command cargo build --release 
the next error is shown and all compilation process breaks:
-------------------------------
= note: /usr/bin/ld: /home/vrchng/grin/target/release/deps/libncurses-051434f8df6639e7.rlib(ncurses-051434f8df6639e7.ncurses0-b8c5c8b15a5ffdd661ec5c5fe1f91cff.rs.rcgu.o): undefined reference to symbol 'halfdelay'
          //lib/i386-linux-gnu/libtinfo.so.5: error adding symbols: DSO missing from command line
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error

error: Could not compile `grin`.
-------------------------------
[rustc_grin1.log](https://github.com/rust-lang/rust/files/2194881/rustc_grin1.log)

Thanks

**Comment by nagisa** [comment]
This is a user mistake. Either grin or you are expected to request rustc to link in `tinfo`.

`halfdelay` may be a macro in ncurses and it is an user mistake to try to link to it.

Report these issues against the project you are trying to build.

**Comment by blabarna** [comment]
Thank you much for your answer!
I shall check dependencies and makefile to solve my problem
