### ISSUE TITLE
nll allows `&'static Fn()` to contain function local upvars

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#52384]
```
#![feature(nll)]

fn main() {
    let x = 42;
    let _: &'static _ = &|| { let x = x; x };
}
```

I don't think this should compile. I didn't test whether we can actually abuse this to do unsoundness, but this snippet seems very unintuitive

**Comment by nikomatsakis** [comment]
I don't think this is #47184 **exactly** -- we *are* enforcing user-given types in this particular case, but I think we are probably **not** requiring them to be well-formed. As a result, if the type of `_` is `&'static T`, we don't end up requiring that `T: 'static`.

I suspect that you would have a similar error with something like `struct Foo<T: 'static>` and an annotation `let x: Foo<_> = ...`. 

This ought to be fixed for EP2. Nominating.

**Comment by nikomatsakis** [comment]
Assigning to myself as this intersects my branch for #48071 quite a bit.

**Comment by nikomatsakis** [comment]
Actually, I think @matthewjasper was right! In particular, I think we don't currently enforce type annotations that are placed on patterns that are not variable bindings. So e.g. this does not compile:

```rust
#![feature(nll)]
#![allow(warnings)]

fn main() {
    let x = 42;
    let y: &'static _ = &|| { let x = x; x };
}
```

**Comment by nikomatsakis** [comment]
Going to close as a duplicate of #47184
