### ISSUE TITLE
#![warn(trivial_numeric_casts)] stays cached when commenting out or uncommenting

### ISSUE THREAD

**Issue by martin-t** [rust-lang/rust#52387]
Starting with this code:
```rust
#![warn(trivial_numeric_casts)]

fn main() {
    println!("{}", 0u8 as u8);
}
```
and running `cargo build`, it correctly warns:
```
warning: trivial numeric cast: `u8` as `u8`. Cast can be replaced by coercion, this might require type ascription or a temporary variable
 --> src/main.rs:4:20
  |
4 |     println!("{}", 0u8 as u8);
  |                    ^^^^^^^^^
  |
note: lint level defined here
 --> src/main.rs:1:9
  |
1 | #![warn(trivial_numeric_casts)]
  |         ^^^^^^^^^^^^^^^^^^^^^
```

Then I comment out the warn setting as `//#![warn(trivial_numeric_casts)]` and run `cargo build` again but it still warns:
```
warning: trivial numeric cast: `u8` as `u8`. Cast can be replaced by coercion, this might require type ascription or a temporary variable
 --> src/main.rs:4:20
  |
4 |     println!("{}", 0u8 as u8);
  |                    ^^^^^^^^^
  |
note: lint level defined here
 --> src/main.rs:1:9
  |
1 | //#![warn(trivial_numeric_casts)]
  |         ^^^^^^^^^^^^^^^^^^^^^
```
The underline is off as if the `//` wasn't there.

Changing the code in any way (e.g. `1u8`) probably invalidates the cache because the warnings disappear.

Tested on `rustc 1.27.1 (5f2b325f6 2018-07-07)` and `rustc 1.29.0-nightly (254f8796b 2018-07-13)`.

**Comment by Enselic** [comment]
Triage: I can't reproduce this any longer. Can you?

**Comment by martin-t** [comment]
Tested on 1.76 nightly and it no longer happens so it probably got fixed at one point. Thanks for checking up on the issue. Closing.
