### ISSUE TITLE
Integers print inconsistently via the `println!` macro

### ISSUE THREAD

**Issue by jay-tyler** [rust-lang/rust#52407]
I'm just starting to learn Rust, and have been creating some simple shell scripts.

I have a function that looks like this, where reader is either a file or stdin.
```
fn count_lines<R>(reader: R) -> usize
    where R: BufRead
{
    let lines = reader.lines();
    let mut count = 0;
    for _ in lines {
        count = count + 1;
        println!("{}", count);
    }
    println!("{}", count);
    println!("{}", count);
    count
}
```

And the output looks like this when the reader is constructed via `std::io::stdin()` with a subsequent `lock()`.
```
$ cargo run --bin count
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `/Users/jason/rust/shell_scripts/target/debug/count`
first_line
1
second_line
2
third_line
3
3D
3
```
Notice the end count first prints as a `3D`, and then subsequently prints as `3`. I don't see any "D" suffixes when the reader is an open `File`.

Currently running
```
$ rustc --version
rustc 1.27.0 (3eda71b00 2018-06-19)
```

**Comment by sfackler** [comment]
I don't think the D is coming from the standard library. It could be coming from the terminal printing `^D` for the Ctrl-D you've presumably used to close stdin though?

**Comment by jay-tyler** [comment]
@sfackler That's a reasonable suggestion, but I tried it without any `println!` statements, and I don't get a `D` printing anywhere. Also not seeing it for other non-Rust shell scripts, like using `cat` against stdin.

It looks like if I use only a single `println!` statement, against an empty string, on the last `println!` above, I do get a `^D`.

Just to be clear, here are the cases:
* no `println!`: no printing for `^D` at all
* single `println!("")` prints `^D`
* code + input above: prints `3D` without the caret `^`

Do I need to lock stdout here? It looks like I get the behavior above regardless of whether I first print with Stdin dropped (i.e. out of scope) or with StdinLock in-scope.

**Comment by sfackler** [comment]
I can't reproduce that behavior with fish in tmux in urxvt. The shell is the thing that decides whether or not to print ^D.

**Comment by jay-tyler** [comment]
@sfackler I'm using iTerm2/bash on a MacBook. Same behavior inside `tmux`. The results above suggest some kind of race condition against stdout, which isn't likely to reproduce consistently across all devices and terminals.

Do you have a reference for the shell deciding to print `^D`? Genuinely curious, and have tried `^D` aka EOF with a bunch of different programs/shells, all with very different behavior.
* `ipython`: handles EOF by printing `Do you really want to exit ([y]/n)?`
* `python`: prints `^D` before returning to prompt
* `cat`: prints nothing and returns to prompt
* `wc -l`: displays a highlighted `^D` which disappears after a second `^D`. Returns to prompt.

Most of the behavior I'm seeing above seems to be programmatically defined. I'd like to catch and handle the EOF in Rust if I can. Seems to be possible in most programming languages.

**Comment by sfackler** [comment]
You don't really "catch" an EOF - you just get a return value of 0 when reading from whatever reached the end of input. The `lines` iterator completes iteration when that happens.

Nothing in your process is printing the string `^D` - you can run it in dtruss if you want to verify.

**Comment by jay-tyler** [comment]
@sfackler Ok, thanks, I tried tracing via `dtruss` and it looks like you're right. The `D` isn't coming from my Rust program. Here's a truncated output in case anyone from the future is curious:

```
$sudo dtruss /target/release/count
[snip]

write(0x1, "1\n\0", 0x2)		 = 2 0
line_2
2
read(0x0, "line_2\n\0", 0x2000)		 = 7 0
write(0x1, "2\n\0", 0x2)		 = 2 0
line_three
3
read(0x0, "line_three\n\0", 0x2000)		 = 11 0
write(0x1, "3\n\0", 0x2)		 = 2 0
3D
3
read(0x0, "t\b\0", 0x2000)		 = 0 0
write(0x1, "3\n\0", 0x2)		 = 2 0
write(0x1, "3\n\0", 0x2)		 = 2 0
sigaltstack(0x7FFEE1D88A50, 0x0, 0x0)		 = 0 0
munmap(0x10DF25000, 0x20000)		 = 0 0
```
