### ISSUE TITLE
Add span to E0391

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#52417]
Current output:

```
error[E0391]: cycle detected when computing layout of `std::option::Option<S>`
   |
note: ...which requires computing layout of `S`...
   = note: ...which again requires computing layout of `std::option::Option<S>`, completing the cycle
note: cycle used when compile_codegen_unit
```

**Comment by euclio** [comment]
I took a look at this, and it looks like calls to the `layout_of` query need to be associated with a span. However, I'm not familiar enough with the query system to figure out how to do that. Looks like the normalization query needs a span as well.

**Comment by estebank** [comment]
This has since been fixed.
