### ISSUE TITLE
auxiliary files in compile-test aren't compatible with `extern_prelude` feature

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#52428]
When we use the "auxiliary crate" feature in compile-test, it adds a `-L <aux-path>` flag that points rustc at the directory where to find those crates. This means that when rustc sees an `extern crate` it then searches those directories. It's good to have the ability to test that behavior, but it's not the way that cargo drives rustc -- and as a result it's not compatible with the new extern-prelude feature set, requiring [awkward run-make tests like extern-prelude](https://github.com/rust-lang/rust/blob/master/src/test/run-make-fulldeps/extern-prelude/Makefile). 

It would probably be better for compiletest, by default, to add a `--extern foo=<path-to-foo>` flag for each auxiliary crate. We could maybe keep a way to use the "auxdir" option.

cc @petrochenkov @zackmdavis @nrc @qmx

**Comment by nikomatsakis** [comment]
Here is where to find the current code around auxiliary crates. The idea, for review, is that tests can have a `// aux-build:foo.rs` annotation like this one:

https://github.com/rust-lang/rust/blob/3d5753fda1ee8f729da1061e931e13b043f479a5/src/test/pretty/attr-derive.rs#L11

When we see such an annotation, we will build the crate `auxiliary/foo.rs`. This is done in this loop here:

https://github.com/rust-lang/rust/blob/3d5753fda1ee8f729da1061e931e13b043f479a5/src/tools/compiletest/src/runtest.rs#L1490

We then later add a `-L` flag with the directory. Here is one such place but there seem to be several:

https://github.com/rust-lang/rust/blob/3d5753fda1ee8f729da1061e931e13b043f479a5/src/tools/compiletest/src/runtest.rs#L1311

The *ideal* seems to me to be to instead be adding `--extern` flags, but it'll take a bit of digging to see just the best place to do it.

**Comment by ehuss** [comment]
I think this is now essentially resolved via #67074 which added the aux-crate header which uses `--extern` instead of `-L`.

It's not a huge benefit because aux crates still default to 2015, and you can't refer to these crates in `use` statements, unless you change the edition in the aux crate.

**Comment by jieyouxu** [comment]
compiletest triage: indeed, closing as resolved.
