### ISSUE TITLE
rustdoc: mut in param is implementation detail

### ISSUE THREAD

**Issue by derekdreery** [rust-lang/rust#52427]
I'm reporting this as a pet peeve. If this is incorrect, or has been brought up before, then I apologize.

Consider the following code

```rust
/// Takes a number and increments it.
pub fn inc(mut x: usize) -> usize {
    x = x + 1;
    x
}
```

Now obviously this is a silly implementation of the function, but there are times when making a parameter mutable is useful. To avoid seeing it in documentation I often do the following:

```rust
pub fn inc(x: usize) -> usize {
    let mut x = x;
    // ...
}
```

It would be easier if the fact that the parameter is mutable is just elided in the documentation. It's an implementation detail and is of no interest to the caller.

**Comment by cuviper** [comment]
Isn't this already hidden?  For your example, I get:

![image](https://user-images.githubusercontent.com/36186/42772749-3cffc654-88e0-11e8-9358-b1d9d3712afb.png)

**Comment by derekdreery** [comment]
woooop can confirm that it doesn't show `mut` anymore :D
