### ISSUE TITLE
should be possible to do [CopyableVariant, ..n] for a non-copyable type

### ISSUE THREAD

**Issue by thestinger** [rust-lang/rust#5244]
This should be fixable by special casing this (the type isn't copyable, but for this specific case the variant is).

This problem only exists with fixed-size vectors since `vec::from_fn(10, |_| None)` works with non-copyable types.

@nikomatsakis thinks this should be fixable

**Comment by steveklabnik** [comment]
closing in favor of https://github.com/rust-lang/rfcs/pull/832, which is going to end up doing this.

**Comment by Gankro** [comment]
That RFC only provides the functionality in the vec macro through Clone. This still wouldn't allow a `vec![None::<SomethingNotClone>; 10]`, and of course has no affect on the standard `[T; n]` syntax.

**Comment by steveklabnik** [comment]
Ah, I mis-read: I thought that it was supporting non-Clone too.

**Comment by steveklabnik** [comment]
Moving to the RFC repo generally https://github.com/rust-lang/rfcs/issues/1366
