### ISSUE TITLE
rustfmt removes oddly placed comments

### ISSUE THREAD

**Issue by zacheryph** [rust-lang/rust#52444]
rustfmt likes to remove commented lines that are found in odd places.  This appears to affect both stable and nightly `rustfmt`.

### Input File
```rust
struct X<T>
// where
//     T: Clone
{
    inner: String,
}
```

### After rustfmt
```rust
struct X<T> {
    inner: String,
}
```

**Comment by frewsxcv** [comment]
Similar issue https://github.com/rust-lang-nursery/rustfmt/issues/2781#issuecomment-396085985

**Comment by zacheryph** [comment]
@frewsxcv thank you. Added comment to that ticket and will close this ticket in favor of. Kind of forgot about nursery :x
