### ISSUE TITLE
[LLVM 7] use funnel shift intrinsic to implement rotates

### ISSUE THREAD

**Issue by rkruppe** [rust-lang/rust#52457]
https://reviews.llvm.org/rL337221 introduced new intrinsics in LLVM IR that make it easier to guarantee that integer rotates will make it to the backend intact and can be lowered to a hardware rotate instruction (instead of possibly being split up into shifts and bitwise ors). Since we already expose rotates as methods on integer types, we could just change the implementation of those methods to lower to these IR intrinsics. As soon as we're on an LLVM version that supports these intrinsics, that is, but I wanted to file this issue before I forget about them.

cc @eddyb @nox

**Comment by nagisa** [comment]
This is definitely something we want to do. We already have a few issues around that complain about `.rotate_xxx` not optimising down to a rotate instruction. See e.g. https://bugs.llvm.org/show_bug.cgi?id=37461
