### ISSUE TITLE
improper_ctypes lint unaffected by lint attributes on the foreign items themselves.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#52456]
```rust
// The attribute around the whole FFI block works.
#[allow(improper_ctypes)]
extern {
    // But this one on an individual FFI item doesn't.
    #[allow(improper_ctypes)]
    fn exit(_: &String);
}
``` 

The problem arises because the lint iterates over the children of `ForeignMod` (`extern {...}`):
https://github.com/rust-lang/rust/blob/2ddc0cbd56ff1695f24b4f5daa14642bd21e4af0/src/librustc_lint/types.rs#L788-L792
and it does so through `check_item`, but only `check_foreign_item` would be affected by attributes on the individual foreign `fn` / `static` / `type` children of the `extern {...}` block.
`check_foreign_item` could be used instead, with the small change that the `abi` has to be obtained from `cx.tcx.hir.get_foreign_abi(ni.id)`, instead of `nmod`'s field (as `nmod` would be gone).

cc @nikomatsakis @Manishearth

**Comment by VPashkov** [comment]
I would like to take this on if nobody else is working on that.
