### ISSUE TITLE
Refactor away the `TypeckTables::cast_kinds` field

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#52482]
# Motivation

This field has a lot of code going into creating it, while its use sites barely care at all about all the nice data it contains. They could just as well compute the data they need themselves. Computing the data is cheap, so there's no point in computing this ahead of time.

# Instructions

## 1. Eliminate uses

The field is used in two places:

1. HIR -> MIR conversion https://github.com/rust-lang/rust/blob/50702b28383c15907c29e8f70256cdd439800834/src/librustc_mir/hair/cx/expr.rs#L590
2. rvalue promotion https://github.com/rust-lang/rust/blob/50702b28383c15907c29e8f70256cdd439800834/src/librustc_passes/rvalue_promotion.rs#L371

The 1. use can be fixed by just checking whether the type of `source` is the same type as `expr_ty`. This means all `foo as Bar` casts get ignored if `foo` is already of type `Bar`. Which is exactly what that code is trying to do.

The 2. use actually wants to know the cast kind, but there's no need to get that from the `cast_kinds` field. Instead one would again obtain the type of the expression being cast and the type being cast to, and then do exactly what MIR based borrowck does when going through the same code (Use `CastTy` to figure out the details): https://github.com/rust-lang/rust/blob/38168a77d7174baf59334f8c196d6ae4136b928a/src/librustc_mir/transform/qualify_consts.rs#L719-L725

## 2. Eliminate the field and all the code feeding into it

This part is easy now. Remove the field, and the compiler will guide you to all the places it's used. All you have to do is remove code until the compiler is happy.

**Comment by eddyb** [comment]
cc @nikomatsakis @arielb1

**Comment by cjkenn** [comment]
I'd like to take a look at this. I should be able to get a pr in a few days (possibly with a few questions  -_-)

**Comment by oli-obk** [comment]
@cjkenn awesome! Don't hesitate to ask here or on irc/discord if you have any questions

**Comment by cjkenn** [comment]
@oli-obk For case 1, do we intend to do something like this:
```rust
let source_ty = cx.tables().expr_ty(source);
if source_ty == expr_ty {
    // Convert the lexpr to a vexpr.
    ExprKind::Use { source: source.to_ref() }
else {
...
```
I'm unsure if this results in the same behaviour as the current code

**Comment by oli-obk** [comment]
Oh right. So basically Rptr -> Rptr casts, Rptr -> Ptr casts and any cast where the types are equal. I think that are the only coercions?

**Comment by eddyb** [comment]
@arielb1 However, if it's a coercion cast, doesn't the coercion happen *on top of* the unadjusted type? I guess I'm not sure where the coercion is exactly... I'm guessing on the `source` expression?

**Comment by mcr431** [comment]
@cjkenn @oli-obk Is this still being actively worked on?

**Comment by arielb1** [comment]
@eddyb 

> @arielb1 However, if it's a coercion cast, doesn't the coercion happen on top of the unadjusted type? I guess I'm not sure where the coercion is exactly... I'm guessing on the source expression?

Yea, but if you have a no-op coercion (i.e. "just a subtyping conversion"), the adjusted type of the source expression can be the same as the type of the source expression, and a supertype of the type of the destination expression.

**Comment by cjkenn** [comment]
@mcr431 I haven't worked on this at all really :( I'm unsure what to do, and if this is something we can/want to do.

**Comment by ZerothLaw** [comment]
Is this work still needed? Will it conflict with Chalkification?

**Comment by saleemjaffer** [comment]
@oli-obk I would like to take a shot at this :) I am a newbie to rust.

**Comment by oli-obk** [comment]
sure! The instructions in the main issue should still apply, even if the exact locations of the code may have changed

**Comment by saleemjaffer** [comment]
@oli-obk 
For 1. I do something like this but keep gettting a `thread 'rustc' panicked at 'bad input type for cast', src/libcore/option.rs:1038:5d`. I am stuck at this. Any help?
```rust
        hir::ExprKind::Cast(ref source, ref cast_ty) => {
            // Check for a user-given type annotation on this `cast`
            let user_provided_types = cx.tables.user_provided_types();
            let user_ty = user_provided_types.get(cast_ty.hir_id);

            debug!(
                "cast({:?}) has ty w/ hir_id {:?} and user provided ty {:?}",
                expr,
                cast_ty.hir_id,
                user_ty,
            );
            
            let source_ty = cx.tables().expr_ty(source);
            let cast = if source_ty == expr_ty {
                // Convert the lexpr to a vexpr.
                ExprKind::Use { source: source.to_ref() }
            } 
```

**Comment by oli-obk** [comment]
Do you have a backtrace of that panic?

I think it would be easier to review if you open a PR with your changes and we'll discuss the problems there. Basically just a single PR for the 1.
