### ISSUE TITLE
Having two UNIX_EPOCH constants is a potential source of confusion

### ISSUE THREAD

**Issue by ssokolow** [rust-lang/rust#52519]
While trying to get comfortable with `SystemTime`, I found myself extremely confused because it appeared that `UNIX_EPOCH` was usable, despite being marked unstable.

It wasn't until I checked bug #49502 that I finally realized what I'd repeatedly overlooked: What was being successfully used was `std::time::UNIX_EPOCH` rather than `std::time::SystemTime::UNIX_EPOCH`.

The simplest way to head off this kind of confusion would be to have the documentation for the two `UNIX_EPOCH` definitions mention each other's existence.

**Comment by Dylan-DPC** [comment]
the constant has stabilised now, and they have the same documentation so this is less of a problem now.
