### ISSUE TITLE
BufWriter::new should say what the current default capacity is

### ISSUE THREAD

**Issue by Havvy** [rust-lang/rust#52513]
The docs for `BufWriter::new()` currently state "Creates a new BufWriter with a default buffer capacity." It should state what that capacity currently is (and state that it may be subject to changes).

**Comment by tbu-** [comment]
This seems to be fixed: [nightly docs of BufWriter::new](https://doc.rust-lang.org/nightly/std/io/struct.BufWriter.html#method.new).

**Comment by Havvy** [comment]
Yes. 😄
