### ISSUE TITLE
fs::copy and io::copy should See Also each other

### ISSUE THREAD

**Issue by Havvy** [rust-lang/rust#52524]
I was pointed at `fs::copy` on IRC earlier, but couldn't use it with `tempfile` because that just gives a `File`. Had `fs::copy` had a "See also" link to `io::copy`, I would have found it without complaining that I couldn't use `fs::copy`. And for similar reasons, `io::copy` should See Also to `fs::copy` for those who do want to copy a file based on paths and not readers and writers.

**Comment by frewsxcv** [comment]
I opened a PR for this: https://github.com/rust-lang/rust/pull/53376
