### ISSUE TITLE
[ui] Incorrect hint: Ok(wrap) instead *Deref

### ISSUE THREAD

**Issue by fzzr-** [rust-lang/rust#52537]
Reproduced on versions:
- `rustc 1.29.0-nightly (12ed235ad 2018-07-18)`
- `rustc 1.29.0-nightly (9fd3d7899 2018-07-07)`
- `rustc 1.27.0 (3eda71b00 2018-06-19)`

Isolated example to reproduce:
```rust
use std::ops::Deref;

struct Error {}
struct State {}
struct StateDeref { inner: State }

impl Deref for StateDeref {
	type Target = State;
	fn deref(&self) -> &Self::Target { &self.inner }
}

fn get_state() -> Result<StateDeref, Error> { Err(Error {}) }

fn need_ref_state_from(state: &State) -> bool { true }

fn state_info() -> Result<bool, Error> { Ok(need_ref_state_from(&get_state()?)) }
```

Actual error:
```txt
error[E0308]: try expression alternatives have incompatible types
   --> src/main.rs:16:66
    |
16  | fn state_info() -> Result<bool, Error> { Ok(need_ref_state_from(&get_state()?)) }
    |                                                                  ^^^^^^^^^^^^
    |                                                                  |
    |                                                                  expected struct `State`, found struct `StateDeref`
    |                                                                  help: try wrapping with a success variant: `Ok(get_state()?)`
    |
    = note: expected type `State`
               found type `StateDeref`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
```

Mentioned suggestion about "wrap into `Ok`" is incorrect at all. There we should deref the value from the `get_state()?`.

- - -

Expected error:   (something like this)
```txt
...
expected struct `State`, found struct `StateDeref`
help: try re-dereference(?) with a success variant: `&*get_state()?`
```

**Comment by zackmdavis** [comment]
Here's where the suggestion gets issued:

https://github.com/rust-lang/rust/blob/6cc78bf8d76383395e307cef5e601cfe561337e6/src/librustc/infer/error_reporting/mod.rs#L504-L513

The motivation was to solve #51632 (where a `?`-expression appears in tail position, which seemed likely to be a common mistake), but it turns out that there are other situations where we run into a type mismatch between match arms of a desugared `?` expression. We regret the error.

**Comment by kornelski** [comment]
Here's another case of this:

```rust
struct Foo;

fn takes_ref(_r: &Foo) {}

fn returns_result() -> Result<Foo,()> {}

fn main() -> Result<(),()> {
    takes_ref(returns_result()?);
    Ok(())
}
```

> 8 |     takes_ref(returns_result()?);
  |               ^^^^^^^^^^^^^^^^^
  |               |
  |               expected &Foo, found struct `Foo`
  |               help: try wrapping with a success variant: `Ok(returns_result()?)`
  |
  = note: expected type `&Foo`
             found type `Foo`

**Comment by estebank** [comment]
@zackmdavis I see what's happening, we're _only_ checking wether the error came from a `?` desugaring, disregarding the types involved. It should be possible to check that information as well, even if the suggestion is only provided when  it's a `Result` where everything but the error type matches. (I think it's ok if the supplied error cannot be converted to the expected error, as this suggestion exposes newcomers to a non-obvious construct at least.)

**Comment by zackmdavis** [comment]
> even if the suggestion is only provided when it's a `Result`

Clippy [has helper functions](https://github.com/rust-lang-nursery/rust-clippy/blob/4a7601bd5570c9bc7632ec57a595134afb13a4a5/clippy_lints/src/methods/mod.rs#L1730) to detect this that we might want to uplift ...

**Comment by zackmdavis** [comment]
(But for now I'm just going to remove the suggestion.)
