### ISSUE TITLE
Consider borrowing here: `&0`

### ISSUE THREAD

**Issue by jjl** [rust-lang/rust#52544]
```
error[E0308]: mismatched types
  --> src/schema_parser.rs:91:20
   |
91 |             if i < 0 {
   |                    ^
   |                    |
   |                    expected &i64, found integral variable
   |                    help: consider borrowing here: `&0`
   |
   = note: expected type `&i64`
              found type `{integer}`
```

What I actually wanted was `*i`.

**Comment by oli-obk** [comment]
The problem is by the time this error is emittedwe don't have the information about the root cause anymore. In this case that would be the type of `i` being checked for `PartialOrd` and figuring out the the rhs needs to be of the same type.

Clippy has a lint that will tell you to clean it up afterwards, but we should probably issue a better diagnostic to begin with.

**Comment by hellow554** [comment]
@jjl, can you please create a MCVE?

**Comment by csmoe** [comment]
@hellow554
```rust
fn main() {
    let i: &i64 = &1;
    if x < 0 {}
}
```

**Comment by hellow554** [comment]
Please excuse my naïvety, but why is this (according to csmoes MCVE) a problem? You can actually write `i < &0` and everything works just fine. Can you please explain this part (to me)?

**Comment by oli-obk** [comment]
The comparison operator already takes references to both sides. so it seems simpler to dereference the lhs and save the monomorphizer and the optimizer some effort

**Comment by rakshith-ravi** [comment]
Resurrecting this. 

@oli-obk what're the benefits of dereferencing the lhs instead of referencing the rhs?

Also, if I were to go about fixing this, where would I start?

**Comment by oli-obk** [comment]
The benefit is that `x < y` expands to `Ord::cmp(&x, &y)`, so if you start out with `x < &y` you get `Ord::cmp(&x, &&y)`, seems better to just do `Ord::cmp(&*x, y)` instead (since `&*` is a no-op that gets easily removed).

I'm not sure how to solve this or whether we should try at all.

**Comment by rakshith-ravi** [comment]
I want to get started with this, but would appreciate some mentoring from someone before I do, to point me in the right direction please

**Comment by oli-obk** [comment]
There's a reason I marked this as `E-hard`. I have no idea how to do this reasonably. I'm sorry, but I have no hints for you, and I don't even know if it's possible to do in a reasonable way.

**Comment by rakshith-ravi** [comment]
If someone wants to claim this up, feel free to. Until then, I'll try and fix this.

**Comment by Alexendoo** [comment]
Hi, are you still working on this issue @rakshith-ravi?

**Comment by rakshith-ravi** [comment]
Hey @Alexendoo. I've been meaning to fix this up. I've reached a point where I know exactly how to fix this as well. I just haven't found the time to fix this. Feel free to take it up, considering I wouldn't be having the time to work on this in the forseeable future.

**Comment by Alexendoo** [comment]
@rustbot release-assignment

If do you find the time in the future, please claim this issue again. Until then I'll free it up in case anybody else wants it

**Comment by sjwang05** [comment]
Is anyone currently working on this? If not, I'd be happy to give it a go.

@rustbot claim
