### ISSUE TITLE
URL in Error note for E0277 is invalid - #dynamically-sized-types--sized

### ISSUE THREAD

**Issue by rbuckland** [rust-lang/rust#52554]
## The compiler presents a URL in the error explanation which is invalid

I expected a valid URL
Instead, the URL links to the correct page, but the anchor is invalid.

## Details

The URL presented is 
[https://doc.rust-lang.org/book/second-edition/ch19-04-advanced-types.html#dynamically-sized-types--sized](https://doc.rust-lang.org/book/second-edition/ch19-04-advanced-types.html#dynamically-sized-types--sized)

but should be 

[https://doc.rust-lang.org/book/second-edition/ch19-04-advanced-types.html#dynamically-sized-types-and-sized)](https://doc.rust-lang.org/book/second-edition/ch19-04-advanced-types.html#dynamically-sized-types-and-sized)

The anchor is different. (`and` is missing)

( I could not find "where" in this repo this is )

**This is a summary of the error I was presented**
```
error[E0277]: the size for values of type `[std::collections::BTreeMap<&str, &_>]` cannot be known at compilation time
  ...
    = note: to learn more, visit <https://doc.rust-lang.org/book/second-edition/ch19-04-advanced-types.html#dynamically-sized-types--sized>
  ...
```

## Rust Version

```
rustc 1.29.0-nightly (1ecf6929d 2018-07-16)
binary: rustc
commit-hash: 1ecf6929dc3b309cdfcb7239260777dab38242b9
commit-date: 2018-07-16
host: x86_64-unknown-linux-gnu
release: 1.29.0-nightly
LLVM version: 7.0
```

**Comment by csmoe** [comment]
Fixed in latest rustc https://github.com/rust-lang/rust/blob/1c84d8187395b641616649a0f16f15a78ea8bbce/src/libcore/marker.rs#L98
