### ISSUE TITLE
#[test] visibility changes can produce conflicts and type errors with glob use.

### ISSUE THREAD

**Issue by djrenren** [rust-lang/rust#52557]
Because `#[test]` marks tests as public so that they can be reexported (avoiding E0364), they can cause namespace pollutions that only occur in test builds.

Minimal repro:
```rust
mod A {
    #[test]
    fn foo() {}
}

mod B {
    pub fn foo() -> bool {
        true
    }
}

use B::foo;
use A::*;

fn conflict() {
    let x: bool = foo();
}
```

In a normal build, the only `foo` in scope is `B::foo`, but in a test build `A::foo` will shadow it. And produce the following error:

```
error[E0308]: mismatched types
  --> ./test.rs:20:19
   |
20 |     let x: bool = foo();
   |                   ^^^^^ expected bool, found ()
   |
   = note: expected type `bool`
              found type `()`
```

**Comment by djrenren** [comment]
I propose that instead of expanding:

```rust
#[test]
fn foo() {}
```

to: 

```rust
pub fn foo(){}
pub mod __test_reexports {
   pub use super::foo;
}
```

we expand to:

```rust
pub mod __test_reexports {
    use super::*;
    pub fn foo() {...}
}
```

This is a breaking change but only for the semi-pathological case where you have test functions referencing each other. It also brings test into line with standard builds in that `#[test]` are not referenceable. (in debug/release due to removal, and in test due to a gensymed module).

**Comment by nrc** [comment]
>  the semi-pathological case where you have test functions referencing each other

I bet that's not uncommon enough to make a breaking change. However, I would expect test functions that reference each other to do so via relative paths, and this would only be breaking if absolute paths were used (iiuc). In any case we should probably just fix this and do a Crater run.

**Comment by nrc** [comment]
cc @petrochenkov and @rust-lang/compiler 

We might be able to hack something in name resolution? Perhaps glob imports don't treat test functions as public? Or we give them some weird hygiene marker or something?

**Comment by djrenren** [comment]
Actually if we did:

```rust
use __test_reexports::*;

pub mod __test_reexports {
    use super::*;
    pub fn foo() {...}
}
```

I think we'd be compatible and safe

**Comment by djrenren** [comment]
Well, technically we should `use` or `pub use` each test in accordance with it's visibility

**Comment by eddyb** [comment]
I much better prefer https://github.com/rust-lang/rfcs/pull/2471#issuecomment-397241123 as a solution to *all* our testing woes. I'll maybe try to prototype it soon.

**Comment by djrenren** [comment]
Fixed by https://github.com/rust-lang/rust/pull/52890
