### ISSUE TITLE
Support for ending with semicolon of a single line of a match arm

### ISSUE THREAD

**Issue by hkcorac** [rust-lang/rust#52559]
Hi,

In Rust `1.27.1`, this doesn't compile:

```rust
fn test() -> u8 { 0 }
fn main() {
    match test() {
        0 => test();, // <-- I wish to be able to use this syntax
                      // Sometimes I wist to discard the returning value...
        _ => (),
    }
}
```

It only compiles if it is:

```rust
        0 => { test(); },
```

May I ask if you could consider adding support for the first syntax? I think it might be complicated. So it's ok if it's not.

Thank you,

**Comment by hellow554** [comment]
This needs a RFC, as its changing the language itself. You may want to create one, or ask on https://users.rust-lang.org if anybody is interested in creating a RFC with/for you.

**Comment by hkcorac** [comment]
@hellow554 

Thank you I understand. After thinking again, it seems it's not important. So I'm closing this issue.
