### ISSUE TITLE
Calling macros with full paths doesn't work with implicit crates

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#52576]
```rust
// edition = "2018"
// [dependencies] lazy_static = "1.0.1"

#![feature(rustc_2018_preview)]
#![feature(use_extern_macros)]
lazy_static::lazy_static! {static ref FOO: u8 = 1;}
```

This fails to compile (even with `extern crate lazy_static`). It does compile if I add a `use lazy_static`.

AIUI this is a bug, you should be able to import directly from crates in macros as well.

cc @dtolnay  @alexcrichton

**Comment by petrochenkov** [comment]
This is a sub-issue of https://github.com/rust-lang/rust/issues/52512 (fix is in progress).
