### ISSUE TITLE
nightly emits incorrect relocation section entries

### ISSUE THREAD

**Issue by Navidem** [rust-lang/rust#52578]
The relocation section entries emitted by current nightly has incorrect `index`. 
For example, the following entry 
`        FunctionIndexLeb {
            offset: 11,
            index: 1819
        },`
is emitted for the following call instruction:
` 000eab: 10 c5 8a 80 80 00          | call 1349 <__rdl_alloc>
`
The expected `index` is 1349.

A simple project to reproduce the issue is attached.
Compile command used: 
`cargo +nightly build --target wasm32-unknown-unknown`
Relocations are emitted using .cargo/config as this:
`[build]
rustflags = ["--emit", "obj", "-C", "link-args=--relocatable --no-gc-sections", "-C", "codegen-units=1"]`

[nightly-reloc-bug.zip](https://github.com/rust-lang/rust/files/2215670/nightly-reloc-bug.zip)

**Comment by alexcrichton** [comment]
I think that this is likely an issue with LLD rather than rustc, and it's also seen quite a few changes since this was first opened, so I'm going to close this. This should likely be raised with LLD if it's still an issue.
