### ISSUE TITLE
Spurious unwrap_err() of Ok at 'net::tcp::tests::connect_timeout_unbound' on Windows

### ISSUE THREAD

**Issue by kennytm** [rust-lang/rust#52590]
Symptom: On Windows, the libstd test `net::tcp::tests::connect_timeout_unbound` panicked for unexpectedly connected to a local closed TCP socket without timing out.

```
---- net::tcp::tests::connect_timeout_unbound stdout ----
thread 'net::tcp::tests::connect_timeout_unbound' panicked at 'called `Result::unwrap_err()` on an `Ok` value: TcpStream { addr: V4(127.0.0.1:3434), peer: V4(127.0.0.1:3434), socket: 1028 }', libcore\result.rs:945:5
```

Previous instances:

* 2018-05-19T07:41:59Z — https://github.com/rust-lang/rust/pull/50760#issuecomment-390386940 (i686-msvc-1)
* 2018-06-04T15:32:27Z — https://github.com/rust-lang/rust/pull/51246#issuecomment-394398017 (i686-mingw-1)
* 2018-06-30T14:00:20Z — https://github.com/rust-lang/rust/pull/51849#issuecomment-401543056 (x86_64-mingw)
* 2018-07-21T18:51:09Z — https://github.com/rust-lang/rust/pull/51485#issuecomment-406816274 (i686-msvc-1)

**Comment by nnethercote** [comment]
I've seen this on my Linux box recently, so much so that I think it has become a permafail.
