### ISSUE TITLE
Spurious "this expression will panic at runtime" error (regression)

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#52603]
This code:

```rust
pub trait Foo {
    fn foo(self) -> u32;
}

impl<T> Foo for T {
    fn foo(self) -> u32 {
        fn bar<T>() { loop {} }
        bar::<T> as u32
    }
}
```

when compiled yields:

```
$ rustc +nightly foo.rs --crate-type lib
error: this expression will panic at runtime
 --> foo.rs:8:9
  |
8 |         bar::<T> as u32
  |         ^^^^^^^^^^^^^^^ a raw memory access tried to access part of a pointer value as raw bytes
  |
  = note: #[deny(const_err)] on by default

error: aborting due to previous error
```

but it compiles on stable/beta!

cc @oli-obk, you may know where this is coming from?

**Comment by oli-obk** [comment]
Yea I do. This is fallout from making sure `1/(false as usize)` lints about division by zero.

While the lint message is nonsensical, we should be linting the truncation of addresses, should we not?

**Comment by alexcrichton** [comment]
True! I'd be fine with a warning to say "you should use `usize` to avoid losing data"
