### ISSUE TITLE
 A-rust-2018-preview cargo fix failed

### ISSUE THREAD

**Issue by huoyuanliao** [rust-lang/rust#52606]
Hi, core team:
I'am trying to transition my rust binary source code to 2018-editon, with the method introduced in https://www.ncameron.org/blog/how-to-help-test-the-2018-edition/
then cargo fix failed when compile the crate with cargo-features = ["edition"],edition = '2018' declare.

the error detail is: handle a mod as a crate ,and can't find 'types' crate, actually it is a mod file, and declared in lib.rs: mod types;

software version:
cargo 1.29.0-nightly (506eea76e 2018-07-17)
rustc 1.29.0-nightly (874dec25e 2018-07-21)
the source code is:https://github.com/huoyuanliao/scade.git

thanks

**Comment by Dylan-DPC** [comment]
@huoyuanliao 

you need to change your use statements from 
```rust
pub use inbound::inbound_scan;
```
to

```rust
pub use crate::inbound::inbound_scan;
```

(and likewise for the other use statements)

**Comment by alexcrichton** [comment]
Thanks for the report @huoyuanliao! I think the bug here is that you need to run `cargo fix` *before* enabling the 2018 edition. [The edition guide](https://rust-lang-nursery.github.io/edition-guide/editions/transitioning.html) has detailed step-by-step instructions for how to automatically transition code, mind giving those a spin?

**Comment by huoyuanliao** [comment]
thanks a lots!
I Realized that I followed the wrong steps in https://www.ncameron.org/blog/how-to-help-test-the-2018-edition/
add cargo-features = ["edition"] and edition = '2018' before cargo fix --prepare-for 2018. and as a newbee  to rust, I misunderstood the meaning of this statement in cargo fix. 2018 edition is a big step for rust, it could simplified the semantics a lot. I'll tracking this features and report truly ISSUE. thanks again :)  @alexcrichton  @Dylan-DPC

**Comment by huoyuanliao** [comment]
Hi , I am back.   : (   
another question: does the cargo-fix with "#![warn(rust_2018_idioms)]" could not fix the #[macro_use] and the "extern crate  XXX" statement? when running cargo +nightly fix, it just gave a warning as:
"warning: deprecated `#[macro_use]` directive used to import macros should be replaced at use sites with a `use` statement to import the macro instead".  but do not modify source code. does it must be modify manually?

**Comment by alexcrichton** [comment]
@huoyuanliao ah yes indeed! Right now only some lints have automatic fixes, but others like the warning you've pointed out do not have automatic fixes (but may in the future!)
