### ISSUE TITLE
Rustdoc do not render code block with closures in tables properly

### ISSUE THREAD

**Issue by earthengine** [rust-lang/rust#52643]
The following markdown

```markdown
|a     |b|
|------|-|
|`|v|e`|e|
```

didn't render to
<table><thead><tr><th>a     </th><th>b</th></tr></thead><tbody>
<tr><td><code>|v|e</code></td><td>e</td></tr>
</tbody></table>

It renders to

<table><thead><tr><th>a     </th><th>b</th></tr></thead><tbody>
<tr><td>`</td><td>v</td><td>e`</td><td>e</td></tr>
</tbody></table>

instead. Which makes it harder to use closures in tables for demostration. The workaround is embedded HTML, of cause.

(The github markdown have simular problem and I have to use embedded HTML in this post as well, so I am not sure what the standard is...)

**Comment by steveklabnik** [comment]
This is apparently correct according to the spec, or at least, the same as the reference implementation: https://spec.commonmark.org/dingus/?text=%7Ca%20%20%20%20%20%7Cb%7C%0A%7C------%7C-%7C%0A%7C%60%7Cv%7Ce%60%7Ce%7C

As such, I don't think it's a bug with us; it's either a bug in `pulldown-cmark` or a bug in CommonMark itself. So I'm gonna give this a close; please pursue one of those things if you want to change this!

**Comment by earthengine** [comment]
Please note, the commonmark demostrated above is not even supporting tables. So it would not be a good demostration to show what the markdown spec is.

Also I will trace `pulldown-cmark` for this issue.

**Comment by Ixrec** [comment]
The only standard for table markdown that I'm aware of is [Github's markdown spec](https://github.github.com/gfm/#tables-extension-), which extends CommonMark with tables and a few other things.

What spec is Rustdoc supposed to be using these days?

Within the context of Github's spec, as [Example 193](https://github.github.com/gfm/#example-193) demonstrates, you're expected to backslash-escape any vertical bars that you don't want to be taken as column separators, even if they're part of an inline element like a "code span". To extend that example with yours:

```
| f\|oo  |
| ------ |
| b `\|` az |
| b **\|** im |
| q `|u|u` x |
| q `\|u\|u` x |
```

renders as:

| f\|oo  |
| ------ |
| b `\|` az |
| b **\|** im |
| q `|u|u` x |
| q `\|u\|u` x |
