### ISSUE TITLE
"ld: unknown option: -plugin" when cross-compiling Linux -> OSX as of 1.27.0

### ISSUE THREAD

**Issue by yrashk** [rust-lang/rust#52657]
I have been previously cross-compiling my project using osxcross (https://github.com/sit-fyi/sit/commit/8d9c368329a502e070f46b521b0da21158afebac#diff-beb069f53b3284f57ea9b6fc9ffcad99) and it was working fine until I switched it to 1.27.2 (https://github.com/sit-fyi/sit/blob/5cf5059326f910f56664286dfe4ff63357cd5026/build-tools/cross-compile-osx/Dockerfile)

It now fails to compile with `ld: unknown option: -plugin`. I've tried 1.27.0 and it produces the same error.

Not sure if this would be considered a regression, but in case if it would, I wanted to raise attention to it. Also, is there any way to work around this?

**Comment by sfackler** [comment]
This line seems pretty suspicious:

```
RUN ln -s /osxcross/target/bin/x86_64-apple-darwin15-ld  /osxcross/target/bin/ld
```

It's going to cause the cross linker used as the host linker for things like build scripts which is not going to work.

**Comment by yrashk** [comment]
@sfackler Steven, thank you for your feedback.

I wondered about that, too, however that was the only way back then to make everything work on 1.26 -- or, rather, the only one I found to work at the time. Perhaps, something changed in 1.27 that rendered that hack useless. If I disable it, compiling `backtrace-sys` crate fails with

```
warning: x86_64-apple-darwin15-ranlib: warning for library: .libs/libbacktrace.a the table of contents is empty (no object file members in the library define global symbols)
objcopy:/sit/target/release/build/backtrace-sys-b8cd9e70ead7da52/out/__tmp/__.SYMDEF SORTED: File format not recognized
```

I will keep investigating, hopefully there's the right combination that can make it work on 1.27. Thank you for your time and pinpointing the culprit, again.

**Comment by sfackler** [comment]
Here's the set of environment variables that I've found works for Linux -> OSX cross compilation:

```
ENV CC_x86_64-apple-darwin=x86_64-apple-darwin15-clang \
    CXX_x86_64-apple-darwin=x86_64-apple-darwin15-clang++ \
    AR_x86_64-apple-darwin=x86_64-apple-darwin15-ar \
    CARGO_TARGET_X86_64_APPLE_DARWIN_LINKER=x86_64-apple-darwin15-clang
```

The first 3 in particular are probably the ones that will fix the libbacktrace issue. My guess is that it was using the host `ar` which produced an archive that the OSX ranlib can't understand.

**Comment by yrashk** [comment]
Thank you. After some experimentation, this seems to have worked:

```
FROM rust:1.27.2
RUN apt-get update && apt-get install -y clang autotools-dev automake cmake libfuse-dev fuse git
RUN rustup target add x86_64-apple-darwin
RUN git clone https://github.com/tpoechtrager/osxcross && cd osxcross && git checkout 1a1733a
COPY MacOSX10.11.sdk.tar.xz /osxcross/tarballs/
RUN cd osxcross && UNATTENDED=1 OSX_VERSION_MIN=10.7 ./build.sh
ENV PATH="/osxcross/target/bin:$PATH"
ENV CARGO_TARGET_X86_64_APPLE_DARWIN_LINKER x86_64-apple-darwin15-clang
ENV CC_X86_64_APPLE_DARWIN_LINKER x86_64-apple-darwin15-clang
ENV CC x86_64-apple-darwin15-cc
ENV CMAKE_C_LINK_EXECUTABLE x86_64-apple-darwin15-ld
ENV CMAKE_C_COMPILER_EXTERNAL_TOOLCHAIN x86_64-apple-darwin15-cc
ENV CMAKE_C_COMPILER x86_64-apple-darwin15-cc
```
