### ISSUE TITLE
Accept let-binding as a defining use of existential type

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust#52653]
Per https://github.com/rust-lang/rust/issues/52632#issuecomment-407235743, the following is expected to work. Currently it does not find the defining use of `Clonable` provided by the `let` binding.

```rust
#![feature(existential_type)]

existential type Clonable: Clone;

fn main() {
    let _x: Clonable = 0i32;
}
```

```console
error[E0308]: mismatched types
 --> src/main.rs:6:24
  |
6 |     let _x: Clonable = 0i32;
  |                        ^^^^ expected anonymized type, found i32
  |
  = note: expected type `Clonable`
             found type `i32`

error: could not find defining uses
 --> src/main.rs:3:1
  |
3 | existential type Clonable: Clone;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Mentioning the existential types tracking issue #34511
Mentioning @oli-obk and @cramertj

**Comment by oli-obk** [comment]
Yea I didn't even try to get that to work. I mean, we don't have `let x: impl Debug = "foo";` and impl Trait is stable. This feature needs a whole new inference visitor in typeck. currently it's hard coded to only try filling out these types for return types

**Comment by cramertj** [comment]
All the examples in this thread seem to work now, so I'm closing this issue. [Playground example](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=7a7d82ccff3e6dfcff8a629608d71a13).

**Comment by oli-obk** [comment]
Doesn't work for me: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=c046f7fa47605ab59e24c14adb39a34a

**Comment by dtolnay** [comment]
Looks like it requires #![feature(impl_trait_in_bindings)].

**Comment by oli-obk** [comment]
Oh. There was a playground link. I should pay more attention before pressing buttons
