### ISSUE TITLE
Rustc should not emit duplicate box_free functions

### ISSUE THREAD

**Issue by glandium** [rust-lang/rust#52660]
I was looking at some LLVM-IR for $reasons, and I saw 194 different versions of `box_free` in the same file, where the only difference was in the hash in the symbol. Like:

```llvm
; alloc::alloc::box_free
; Function Attrs: inlinehint nounwind uwtable
define internal fastcc void @_ZN5alloc5alloc8box_free17h012fde3887d48197E(i64* nonnull %ptr) unnamed_addr #2 {
start:
  %0 = bitcast i64* %ptr to i8*
  tail call void @__rust_dealloc(i8* nonnull %0, i64 24, i64 8) #8
  ret void
}

; alloc::alloc::box_free
; Function Attrs: inlinehint nounwind uwtable
define internal fastcc void @_ZN5alloc5alloc8box_free17h024947a2ed392428E(i64* nonnull %ptr) unnamed_addr #2 {
start:
  %0 = bitcast i64* %ptr to i8*
  tail call void @__rust_dealloc(i8* nonnull %0, i64 40, i64 8) #8
  ret void
}
```

etc.

Each of them seems to be used only once, so it seems rustc emits such a method for each drop happening, even when the signature is the same (there *is* a box_free that takes a i8*)

**Comment by nagisa** [comment]
These functions are generic instantiations for different types `T`. See [the definition](https://github.com/rust-lang/rust/blob/d692ab406ebab720f99f950ac3e9aba1e01296af/src/liballoc/alloc.rs#L166)

**Comment by nagisa** [comment]
Also even in your own example there’s a difference in how `__rust_dealloc` is called. I’ll close this as invalid. Feel free to complain if you feel differently.

**Comment by glandium** [comment]
Oh, I overlooked the sizes passed to dealloc being different.
