### ISSUE TITLE
arbitrary_self_types don't support lifetime elision

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/rust#52675]
I mentioned this [on the RFC](https://github.com/rust-lang/rfcs/pull/2362#issuecomment-406804183) recently, but since this is being hit by `futures` 0.3 I thought it's worth having an issue for the current implementation in case it's an easy fix.

```rust
#![feature(arbitrary_self_types)]

struct Foo;
struct Bar<'a>(&'a Foo);

impl std::ops::Deref for Bar<'_> {
    type Target = Foo;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}

impl Foo {
    fn a(&self) -> Bar<'_> {
        Bar(self)
    }
    
    fn b(c: &Self) -> Bar<'_> {
        Bar(c)
    }

    fn c(self: Bar<'_>) -> Bar<'_> {
        self
    }
    
    fn d(e: Bar<'_>) -> Bar<'_> {
        e
    }
}

fn main() {
    let foo = Foo;
    { foo.a() };
    { Foo::b(&foo) };
    { Bar(&foo).c() };
    { Foo::d(Bar(&foo)) };
}
```

```
error[E0106]: missing lifetime specifier
  --> src/main.rs:15:32
   |
15 |     fn c(self: Bar<'_>) -> Bar<'_> {
   |                                ^^ expected lifetime parameter
   |
   = help: this function's return type contains a borrowed value, but there is no value for it to be borrowed from
   = help: consider giving it a 'static lifetime
```

([playground](https://play.rust-lang.org/?gist=5c55d289aa110de505ca8c3520addfda&version=nightly&mode=debug&edition=2015))

**Comment by nox** [comment]
Any progress on that? I need this feature in Servo and the absence of lifetime elision is a huge papercut.

**Comment by Nemo157** [comment]
This also interacts with the just added suggestion in #58919, the suggested fix won't work:

```rust
impl Foo {
    fn c(self: Bar<'_>) -> impl std::fmt::Debug {
        self
    }
}
```

[suggests adding](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=bf0c75403cc7a43a239941e5604fd1f2) `+ '_` to the return type, but [that gives](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=4d8d24141408a90143482c45bb3c09f0)

```
error[E0106]: missing lifetime specifier
```
