### ISSUE TITLE
std::path::Path does not support path contains '~'

### ISSUE THREAD

**Issue by JackWzh** [rust-lang/rust#52689]
```rust
use std::path::Path;

fn main() {
    let p = Path::new("~/Downloads");
    assert!(p.exists());
}
```

and got panicked...

Is there any specific reason for Rust not supporting '~' ?

In Unix-like systems it's quite common to use ~ in path, I think it's fair enough to support '~'

**Comment by ExpHP** [comment]
For input arguments to a program, that is usually handled by the shell before the program is even executed:

```
$ echo ~
/home/lampam
```

`~` is in fact a valid filename on UNIX, so doing this transformation automatically seems to be a bad idea.  I know that Python and Haskell both do not do it.

There is the [`expanduser` crate](https://crates.io/crates/expanduser) for performing this transformation on demand, and something like it could perhaps be proposed for addition to the standard library.

**Comment by tyan-boot** [comment]
`~` is handled by shell itself. Using `~` in your program doesn't work not only in rust but also in c++, etc.

If you want to access to home dir, consider using [dirs crate](https://crates.io/crates/dirs).
