### ISSUE TITLE
#[used] does not cause static to become a symbol in the emitted ELF binary

### ISSUE THREAD

**Issue by fitzgen** [rust-lang/rust#52682]
## Test Case

`Cargo.toml`:

```toml
[package]
name = "used"
version = "0.1.0"
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]

[dependencies]
```

`src/lib.rs`:

```rust
#![feature(used)]

// `DUMMY` does not show up in the ELF binary, despite being `#[used]`.
#[used]
static DUMMY: fn(y: f64) -> f64 = bar as fn(y: f64) -> f64;

fn bar(y: f64) -> f64 {
    y
}

fn main() {
    println!("Hello, world!");

    // Uncommenting this *will* cause `_ZN4used5DUMMY17h21bf8a70` to show up in
    // the ELF binary.
    //
    // println!("Hello, world! {}", DUMMY as *mut fn(f64) -> f64 as usize);
}
```

## Steps to Reproduce

```
$ cargo build && nm target/debug/used | grep bar
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s

$ cargo build && nm target/debug/used | grep DUMMY
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
```

After uncommenting the last `println!`:

```
$ cargo build && nm target/debug/used | grep DUMMY
   Compiling used v0.1.0 (file:///home/fitzgen/scratch/used)
    Finished dev [unoptimized + debuginfo] target(s) in 0.39s
0000000000263060 d _ZN4used5DUMMY17h21bf8a70ebc23562E

$ cargo build && nm target/debug/used | grep bar
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
00000000000064c0 t _ZN4used3bar17hc7a846f29778a0f5E
```

## Expected Results

Both `DUMMY` and `bar` show up in the emitted ELF binary when the last `println!` is commented out.

## Actual Results

Neither `DUMMY` nor `bar` show up in the emitted ELF binary when the last `println!` is commented out.

------------------------------

Rust version: 

```
$ rustc --version
rustc 1.29.0-nightly (6a1c0637c 2018-07-23)
```

Linux version:

```
$ uname -a
Linux big-beefy 4.15.0-24-generic #26-Ubuntu SMP Wed Jun 13 08:44:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

-------------------------------------

Tried reproducing on OSX / Mach-O files and the symbols *did* show up there o_O I wouldn't have expected this to be system specific.

Let me know if there is any more information I should provide!

------------------------------------------

+cc @japaric

**Comment by japaric** [comment]
This is working as intented. As [specified in the RFC](https://github.com/rust-lang/rfcs/blob/master/text/2386-used.md#guide-level-explanation) `#[used]` guarantees that the symbol will be in the object file *emitted by the compiler*; the *linker* is, however, free to drop the symbol -- if you want to keep the symbol *after* linking you additionally will need a linker script (cf. `KEEP` and `EXTERN`).

Using your example code:

``` console
$ cargo rustc --release -- --emit=obj

$ nm -C target/release/deps/used-81376e9de841c190.o
0000000000000000 T main
                 U std::io::stdio::_print
0000000000000000 T std::rt::lang_start
0000000000000000 t std::rt::lang_start::{{closure}}
                 U std::rt::lang_start_internal
0000000000000000 t core::ops::function::FnOnce::call_once
0000000000000000 t core::ptr::drop_in_place
0000000000000000 t used::bar
0000000000000000 t used::main
0000000000000000 d used::DUMMY
```

The DUMMY symbol is present.

**Comment by fitzgen** [comment]
Thanks for explanation @japaric !
