### ISSUE TITLE
rustup-init fails to find MSVC 2017 build tools without vcvarsall.bat pre-execution

### ISSUE THREAD

**Issue by mqudsi** [rust-lang/rust#52683]
Under (a clean installation of) Windows Server 2012 R2 with the latest version of the Microsoft C++ Build Tools 2017 installed (without the 2015 build tools component installed), the most recent rustup-init.exe release fails to find the build tools unless the Visual Studio build environment is first initialized (via `vcvarsall.bat amd64`) in the same shell that `rustup-init.exe` is later executed under.

Otherwise, a warning message about Visual C++ prerequisites not being installed is displayed.

**Comment by mqudsi** [comment]
I can narrow this down further now; in the default case this does not occur, but if no Windows SDK is selected for installation when running the build tools installer (i.e. the compiler, linker, etc. are all installed but the Windows header and library files are not) then `rustup-init.exe` will not be able to detect the presence of the build tools without running in a `vcvarsall.bat` environment.

Given that the platform sdk is not required for compiling rust applications, this should not be the case.

**Comment by jonas-schievink** [comment]
Closing this since this is an issue with rustup (which might be resolved to some extent?)
