### ISSUE TITLE
ICE with -Zmir-opt-level=3

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#52691]
trying to build `aho-corasick v0.5.3` with `-C opt-level=3 -Zmir-opt-level=3` ICEs:

```
thread 'main' panicked at 'assertion failed: lo >= filemap.original_start_pos && lo <= filemap.original_end_pos', librustc_metadata/decoder.rs:345:9
```

**Comment by leonardo-m** [comment]
Dupe of #50411 ?

**Comment by oli-obk** [comment]
different ICE

**Comment by osa1** [comment]
I'm unable to reproduce this with nightly. In case I did something wrong here's the steps I took:

- Unpack aho-corasick-0.5.3 crate
- `cargo +stage1 rustc --lib -- -Copt-level=3 -Zmir-opt-level=3` -- no panic
- rm -rf target, add `--release` to the previous command -- no panic
- rm -rf target
- `cargo +stage1 rustc --bin aho-corasick-dot -- -Copt-level=3 -Zmir-opt-level=3`
- rm -rf target, add --release to the previous command

stage 1 build with `debug = true` and `debug_assertions = true`.

**Comment by oli-obk** [comment]
I'm not even remotely sure how to write a regression test for this. It was probably fixed by one of the debuginfo PRs, which have a lot of their own tests already
