### ISSUE TITLE
Concatenating bytestrings fails; rustc suggests non-existent `bconcat!()`

### ISSUE THREAD

**Issue by jsgf** [rust-lang/rust#52710]
`concat!()` doesn't work on bytestrings (why?). When trying it, it fails with:
```
1 | const FOO: &[u8] = concat!("foo", "bar");
  |                    ^^^^^^^^^^^^^^^^^^^^^
  |                    |
  |                    expected slice, found str
  |                    help: consider adding a leading `b`: `bconcat!("foo", "bar")`
  |
  = note: expected type `&'static [u8]`
             found type `&'static str`
```

`bconcat!()` sounds interesting, but it isn't documented, and the compiler doesn't accept it:
```
error: cannot find macro `bconcat!` in this scope
 --> src/main.rs:1:20
  |
1 | const FOO: &[u8] = bconcat!("foo", "bar");
  |                    ^^^^^^^ help: you could try the macro: `concat`
```

I think the real fix here is that `bconcat!()` should exist.

**Comment by jsgf** [comment]
Heh indeed. I originally tried `concat!(b"foo", b"bar")`, but:
```
error: cannot concatenate a byte string literal
 --> src/main.rs:1:28
  |
1 | const FOO: &[u8] = concat!(b"foo", b"bar");
  |                            ^^^^^^

error: cannot concatenate a byte string literal
 --> src/main.rs:1:36
  |
1 | const FOO: &[u8] = concat!(b"foo", b"bar");
  |                                    ^^^^^^

error: aborting due to 2 previous errors
```

I can't think of a reason why `concat` shouldn't support this though. Is there something I'm missing?

**Comment by kennytm** [comment]
cc @estebank  #51978 about the `bconcat` diagnostic issue.

**Comment by estebank** [comment]
I'll take a look and fix the incorrect suggestion.

The `concat!()` restriction is here:

https://github.com/rust-lang/rust/blob/master/src/libsyntax_ext/concat.rs

It seems to me that the only real restriction that it _should_ have is not mixing byte str literals and str literals when concatenating, and even then it should be possible to convert from one to the other.

Changing the linked code to keep _two_  accumulators, one for `str` and another as a `Vec<u8>` for byte `str`, and returning `base::MacEager::expr(cx.expr_lit(sp, ast::LitKind::ByteStr(rustc_data_structures::sync::Lrc::new(byte_acc))))` would be enough to add the desired functionality.

@rust-lang/lang is there any reason to not change `concat!()` to accept concatenating multiple byte `str`s?

**Comment by estebank** [comment]
The diagnostic bug [is fixed in nightly](http://play.rust-lang.org/?gist=b9468573ce64ffd3abcbac8491bb9343&version=nightly&mode=debug&edition=2015) by #51978.

**Comment by estebank** [comment]
Closing. There's now an RFC for the feature and the bug has been fixed.
