### ISSUE TITLE
Some tier 2 platforms not available anymore on rustup

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#52715]
These tier 2 platforms have no builds on stable, and are marked as `available = false` in the manifest. Since these are tier 2 we should ship binaries for them (without guaranteeing they work).

* `aarch64-unknown-cloudabi`
* `armv7-unknown-cloudabi-eabihf`
* `i686-unknown-cloudabi`
* `powerpc-unknown-linux-gnuspe` (not in the [platform support](https://forge.rust-lang.org/platform-support.html), but I guess tier 2)
* `sparc-unknown-linux-gnu` (not in the [platform support](https://forge.rust-lang.org/platform-support.html), but I guess tier 2)

**Comment by aidanhs** [comment]
We've decided that these have probably been missing forever and we're fine demoting to Tier '2.5' on the forge.

**Comment by aidanhs** [comment]
Discussion: https://mozilla.logbot.info/rust-infra/20180731#c15097689-c15097740

**Comment by aidanhs** [comment]
Demoted in https://forge.rust-lang.org/platform-support.html

**Comment by RalfJung** [comment]
Given that the forge says "This status is accidental", shouldn't there an issue somewhere that tracks getting the remaining "tier 2.5" platforms out of that tier?
