### ISSUE TITLE
2018: #[macro_export(local_inner_macros)] breaks recursion in submodules

### ISSUE THREAD

**Issue by durka** [rust-lang/rust#52726]
I tried adding `#[macro_export(local_inner_macros)]` to make a macro usable outside my crate, but it broke usability *inside* the crate (like for tests). The code:

```rust
#[macro_export(local_inner_macros)]
macro_rules! foo {
    () => { bar!(); };
}

macro_rules! bar {
    () => {}
}

mod tests {
    foo!();
}
```

This works in 2015, and it works in 2018 if you remove `(local_inner_macros)`, but with both it doesn't. This seems like a problem for the migration path.

**Comment by dtolnay** [comment]
This is being fixed in #52234.

**Comment by stjepang** [comment]
I have a similar problem. In `crossbeam-channel` I put `#[macro_export(local_inner_macros)]` above the `select` macro:

```rust
#[macro_export(local_inner_macros)]
macro_rules! select {
    // ...
}
```

Then, in another crate I invoke the macro like this:

```rust
select! { default => {} }
```

This works on stable Rust, but doesn't compile on nightly anymore:

```
error[E0433]: failed to resolve. Could not find `unreachable` in `$crate`
  --> examples/csp.rs:40:5
   |
40 |     select! { default => {} }
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^ Could not find `unreachable` in `$crate`
   |
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
```

It's complaining about this invocation of `unreachable!()`:

```rust
#[macro_export(local_inner_macros)]
macro_rules! select {
    // ...

    (@codegen_finalize
        $token:ident
        $index:ident
        $selected:ident
        $handles:ident
        ()
        ()
        ()
    ) => {
        unreachable!("internal error in crossbeam-channel")
    };

    // ...
}
```

If I change this to `std::unreachable!`, it will compile on nightly but not on stable anymore. Ugh. :(

Is there anything I can do to make this compile on both stable and nightly?

**Comment by stjepang** [comment]
Works perfectly, thank you!
