### ISSUE TITLE
`std::fs::Metadata::len()` returns `u64` not `usize`

### ISSUE THREAD

**Issue by sanmai-NL** [rust-lang/rust#52737]
Why? One problem is, to allocate a buffer in the size of the file, you need to do a possibly truncating cast to `usize`. Of course, the truncation shouldn’t happen here in practice, but still I wonder.

## Meta

`std` >= 1.0.0.

**Comment by sfackler** [comment]
Files can be larger than your processes address space.

**Comment by sanmai-NL** [comment]
Thanks for your hint. Yeah, that’s true sometimes, it depends on the underlying filesystem. What I wondered about is what 32-bits CPU assembly would look like when it handles 64 bits numbers. So would this code compile for a 32 bits target. I’ve found that this works, it will just be slower and use two CPU registers to represent the 64-bit number. Anyway, understandble `u64` was chosen over a smaller integer type for a cross-platform API.
