### ISSUE TITLE
Rust DWARF debug info creates duplicate `DW_TAG_structure_type`s with the same name

### ISSUE THREAD

**Issue by rocallahan** [rust-lang/rust#52762]
Given this pretty common pattern
```
enum Foo { Bar(Bar) }
struct Bar { ... }
```
`rustc` generates two `DW_TAG_structure_type` entries in the same namespace both called `Bar`, one for the Rust struct, the other for the `Foo::Bar` variant. This is a problem for tools that want to refer to DWARF structure types by name (e.g. when trying to guess type identities across compilation unit boundaries). It would also be a problem if a user tries to refer to the type `Bar` in the user interface of a debugger (without additional hacks like ignoring types containing `RUST$ENUM$DISR`).

**Comment by tromey** [comment]
Yes, with my patch, the structure type that is generated for the enum variant is nested in the enum:
```
 <2><394>: Abbrev Number: 7 (DW_TAG_structure_type)
    <395>   DW_AT_name        : (indirect string, offset: 0x2cc): Foo
    <399>   DW_AT_byte_size   : 0
    <39a>   DW_AT_alignment   : 1
 <3><39b>: Abbrev Number: 8 (DW_TAG_variant_part)
 <4><39c>: Abbrev Number: 9 (DW_TAG_variant)
 <5><39d>: Abbrev Number: 10 (DW_TAG_member)
    <39e>   DW_AT_type        : <0x3a6>
    <3a2>   DW_AT_alignment   : 1
    <3a3>   DW_AT_data_member_location: 0
 <5><3a4>: Abbrev Number: 0
 <4><3a5>: Abbrev Number: 0
 <3><3a6>: Abbrev Number: 7 (DW_TAG_structure_type)
    <3a7>   DW_AT_name        : (indirect string, offset: 0x2c8): Bar
    <3ab>   DW_AT_byte_size   : 0
    <3ac>   DW_AT_alignment   : 1
```
