### ISSUE TITLE
nll: remove "warning: not reporting region error due to nll"

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#52768]
As I understand it, our plan has always been to remove this warning eventually.

Certainly it cannot stay as it currently stands.

And from what I've seen, the diagnostics that we now report from MIR-borrowck tend to be good enough that the warning is just noise.

**Comment by pnkfelix** [comment]
(in fact, taking care of this would bring a number of the `.nll.stderr` into 100% alignment with the corresponding `.stderr` file, which would reduce our burden for reviewing those.)

**Comment by pnkfelix** [comment]
But on the other hand, my diagnostic review (#52663) is revealing a couple of cases where a diagnostic is missing useful info that we used to report, and I *think* they correspond to these region errors that we are not reporting.

**Comment by nikomatsakis** [comment]
I'm bumping the priority on this and nominating it for discussion.

**Comment by pnkfelix** [comment]
So the only issue that I'm aware of that we need to fix *eventually* in NLL is the diagnostic regression which I have now filed as #53771

**Comment by pnkfelix** [comment]
but I also do not think that #53771 needs to be resolved for RC (see the end of the description for that issue for why).

Anyway, the question still remains: Are we ready to kill that "region error" warning?

**Comment by zilbuz** [comment]
If that's okay, I can prepare a PR with the warning removed and wait for the question to be resolved before merging it?

If the modification is just removing a warning, I think it should be fairly resilient to merge conflicts. Or is it more complicated than that?

**Comment by nikomatsakis** [comment]
> Anyway, the question still remains: Are we ready to kill that "region error" warning?

I think we are

**Comment by pnkfelix** [comment]
> > Anyway, the question still remains: Are we ready to kill that "region error" warning?
> 
> I think we are

I agree and am going to r+ PR #53865
