### ISSUE TITLE
docs: dead link to std::vec::Vec::extend()

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#52774]
[````extend_from_slice````](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.extend_from_slice) links to [````extend````](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.extend) however it seems there is no such method in the docs.

**Comment by matthiaskrgr** [comment]
Ok that is interesting, when I click the link from within the doc, nothing happens, however if I click the link from this issue, I get to a different page. :confused: 

I'm using firefox 61.0.1

**Comment by GuillaumeGomez** [comment]
It's because the method `extend` is within the `Extend` trait implementation. Since it's not really an issue, I wonder if we should close it now...

cc @rust-lang/docs

**Comment by frewsxcv** [comment]
The link is broken in the docs, so I think we should leave this open since we need to fix that.

**Comment by GuillaumeGomez** [comment]
No it's not really broken since the link exists: https://doc.rust-lang.org/stable/std/vec/struct.Vec.html#impl-Extend%3CT%3E

**Comment by GuillaumeGomez** [comment]
I suppose #52517 is the one?

**Comment by bjorn3** [comment]
Noticed another error in the docs of `extend_from_slice`:

> Note that this function is same as extend except that it is specialized to work with slices instead. If and when Rust gets specialization this function will likely be deprecated (but still available).

`extend` is already specialized for slices

**Comment by GuillaumeGomez** [comment]
@bjorn3 Please open an issue for this one, otherwise it'll get lost.

**Comment by kzys** [comment]
#52517 is similar but we need to have the same code for `hashchange` to address the issue.

https://developer.mozilla.org/en-US/docs/Web/Events/hashchange
