### ISSUE TITLE
Type inference fails in situation with associated types

### ISSUE THREAD

**Issue by GeorgeLyon** [rust-lang/rust#52794]
At the bottom of the following code, there are two lines: one with turbo-fish, and one without. The turbo-fish line succeeds but omitting the turbo-fish causes the type inference system to give up.

Since `Operation` has no generic parameters it can be implemented at most once for a particular type, so the compiler should have no problems understanding that I mean the `StringOp` version of perform.

`rustc --version`
`rustc 1.27.2 (58cc626de 2018-07-18)`

```
trait Operation {
    type Response: Sized;
}

struct IntOp {}

impl Operation for IntOp {
    type Response = i64;
}

struct StringOp {}

impl Operation for StringOp {
    type Response = String;
}

trait Dispatcher {
    fn dispatch<Op: Operation, Response>(&self, &Operation<Response = Response>) -> Response;
}

struct TestDispatcher {}

impl Dispatcher for TestDispatcher {
    fn dispatch<Op: Operation, Response>(&self, op: &Operation<Response = Response>) -> Response {
        unimplemented!()
    }
}

fn main() {
    let t = TestDispatcher {};
    let i = IntOp {};
    let s = StringOp {};

    // Succeeds
    let x = t.dispatch::<IntOp, _>(&i);

    // Fails
    let y = t.dispatch(&s);
}
```

**Comment by dtolnay** [comment]
```rust
fn dispatch<Op: Operation, Response>(
    &self,
    op: &Operation<Response = Response>,
) -> Response
```

The `Op` type parameter does not appear in the method arguments or return value, so there would be no way for the compiler to infer a choice of `Op`. In the case of `t.dispatch(&s)` both `IntOp` and `StringOp` could be chosen.

I suspect what you meant to write was:

```rust
fn dispatch<Op: Operation>(&self, op: &Op) -> Op::Response
```

which infers successfully.
