### ISSUE TITLE
Add redirect for docs.rust-lang.org

### ISSUE THREAD

**Issue by mrmonday** [rust-lang/rust#52803]
Not sure if this is the right place for this issue, sorry if it's not.

Would it be possible to add a redirect for http://docs.rust-lang.org/ -> http://doc.rust-lang.org/?

There's a mixture of `doc`/`docs` used as subdomains for documentation of different languages/libraries - even Rust has `docs.rs`. I often type the wrong one, it would be nice if it redirected to the right place.

**Comment by pietroalbini** [comment]
The redirect is in place.
