### ISSUE TITLE
Box::into_raw doesn't document that the returned pointer will not be null

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/rust#52806]
The existence of the unstable `Box::into_raw_non_null` kind of hints that this is the case (as does an understanding of how Box internally works), but it would be nice for unsafe code to actually guarantee this.

**Comment by estk** [comment]
@kennytm and @jonas-schievink I started looking into this and I'd be happy to update the docs. After having a look over the code however I was a bit confused about how if at all the docs could be improved.

This line: https://github.com/rust-lang/rust/blob/ccb550fb455eac46098b352875ba387eb982919d/src/liballoc/boxed.rs#L155
Seems to me be sufficient to indicate that the pointer will not be null, @jonas-schievink how do you think it should be improved?

**Comment by sfackler** [comment]
Box always points to a valid allocation, and null is not a valid allocation.
