### ISSUE TITLE
Make Duration a wrapper type around nanoseconds counter?

### ISSUE THREAD

**Issue by newpavlov** [rust-lang/rust#52818]
Currently `Duration` is defined as:
```Rust
pub struct Duration {
    secs: u64,
    nanos: u32, // Always 0 <= nanos < NANOS_PER_SEC
}
```
This leads to a certain amount of shims which handle secs/nanos. We could change it's definition to:
```Rust
pub struct Duration { nanos: u128 }
```
This will simplify code, will improve performance a bit, and will allow `new` to be made `const fn` without allowing panics in CTFE, at the cost of 4 additional bytes and clear redundancy of the struct, as it will be able to measure durations up to 1e22 years. (age of the universe is "just" 1.38e10 years) Existing public API of course will stay the same as today.

What do you think?

**Comment by nagisa** [comment]
The current struct definition matches `struct timespec`, thus giving extremely cheap conversions when such duration needs to be passed to syscalls. On UNIXes, anyway.

**Comment by newpavlov** [comment]
Conversion will be very [cheap](https://godbolt.org/g/e8wNpv), also it will be amortized by simplification of other methods. The only worry is performance on non-64 bit systems.

**Comment by rkruppe** [comment]
The (u64,u32)->u128 conversion is rather more expensive on CPUs without 64b x 64b ->128b instruction (e.g., most 32 bit ISAs). And that wasn't even the direction @nagisa referred to, for u128 -> (u64, u32) you need a 128b / 64b *divide* which can take >100 cycles even when available as a single instruction.

**Comment by newpavlov** [comment]
How about hypothetical `u96` type which will be implemented as `(u32, u64)` for 64-bit platforms and `[u32; 3]` for 32-bit platforms? (and `[u16; 6]` on 16-bit) Though if we'll its count implementation , net sum of code complexity will be probably negative...

**Comment by rkruppe** [comment]
Besides the complexity of implementing such a type (and the language level complexity of having it in the language!), it also doesn't really address the performance concern, since a 96 bit division is still pretty expensive to do in software and AFAIK there's no general purpose CPU that implements that directly (so you'd still be falling back to 128 bit division instructions, if available at all).
