### ISSUE TITLE
ICE cat_errd: no type-dependent def for method call

### ISSUE THREAD

**Issue by cramertj** [rust-lang/rust#52815]
Caused by attempting to compile tests (not the normal build) of [this fuchsia crate](https://fuchsia-review.googlesource.com/c/garnet/+/178946) after transitioning to the 2018 edition (edition is probably unrelated).

The full error and backtrace is in [this gist](https://gist.github.com/cramertj/9fea20dea37be4454ac0f163afe8c9d8).

**Comment by Centril** [comment]
@cramertj Do you think you could create an mcve for this?

**Comment by cramertj** [comment]
Definitely not-- I'll close this, since it's two years old, doesn't seem to have been re-reported since, and is incredibly poorly specified.
