### ISSUE TITLE
Example programs in 'Rust by Example' return 'undefined' in browser

### ISSUE THREAD

**Issue by bitfield** [rust-lang/rust#52871]
Example: https://doc.rust-lang.org/rust-by-example/hello.html

Clicking the 'Run' button to run the code example prints 'undefined' instead of the expected "Hello world!". I looked at a few other examples, but they all fail in the same way.

**Comment by kennytm** [comment]
This is because play.rust-lang.org recently changed its (private) API. We need to update these lines in `mdbook`:

https://github.com/rust-lang-nursery/mdBook/blob/29b3ff14c7e47c62f331080e3a92bf5c2484cf52/src/theme/book.js#L112-L119

cc @shepmaster (playground) @mattico @Michael-F-Bryan (mdbook).

**Comment by frewsxcv** [comment]
Should we look into reverting the play.rust-lang.org API  for now? Having it broken for two release cycles seems doesn't seem ideal

**Comment by shepmaster** [comment]
I've added default values to that API for now. There are zero reliability guarantees for every playground API *except* `/evaluate.json`.

**Comment by mattico** [comment]
`mdbook` 0.1.10 has a fix for this issue, though most existing documentation will likely not be rebuilt. I'll make sure we  switch to the `/evaluate.json` endpoint for the next release (https://github.com/rust-lang-nursery/mdBook/issues/753).

**Comment by steveklabnik** [comment]
This has been fixed. Closing!
