### ISSUE TITLE
use_debug ignoring allow()

### ISSUE THREAD

**Issue by ssokolow** [rust-lang/rust#52889]
With the following code, the `writeln!` line triggers a `use_debug` lint message while the `expect_fun_call` (which is produced by the same line and `allow`ed by the same attribute) is successfully suppressed.

```rust
// Make rustc's built-in lints more strict (I'll opt back out selectively)
#![warn(warnings)]

// Set clippy into a whitelist-based configuration so I'll see new lints as they come in
#![cfg_attr(feature="cargo-clippy", warn(clippy, clippy_pedantic, clippy_style, clippy_complexity,
                                         clippy_perf, clippy_correctness, clippy_restriction))]

// Opt out of the lints I've seen and don't want
#![cfg_attr(feature="cargo-clippy", allow(assign_ops, float_arithmetic))]
```

```rust
        let stderr_fail_msg = "Error writing to stderr";
```

```rust
        // Print the backtrace if available
        if let Some(backtrace) = e.backtrace() {
            #[cfg_attr(feature="cargo-clippy", allow(expect_fun_call, use_debug))]
            writeln!(stderr, "backtrace: {:?}", backtrace).expect(stderr_fail_msg);
        }
```

This is on Clippy `0.0.212` as distributed by rustup corresponding to rustc 1.29.0-nightly (54628c8ea 2018-07-30) for the `nightly-x86_64-unknown-linux-gnu` target.

**UPDATE:** Here's a [playground link](http://play.rust-lang.org/?gist=9f67b2f95aed128633f5484de24b7377&version=nightly&mode=debug&edition=2015) which reproduces the problem as of this writing if you choose `Tools > Clippy`.

**Comment by jonas-schievink** [comment]
This no longer seems to happen, so I'll close this. If the issue reappears, please open an issue in the clippy repository: https://github.com/rust-lang/rust-clippy
