### ISSUE TITLE
Conditional compilation based on the type of a type parameter

### ISSUE THREAD

**Issue by axos88** [rust-lang/rust#52894]
Hello,

Theoretically it should be possible to do something like this:

```
  struct Foo<T>(t: T) ;

  impl<T> Foo<T> {
    fn new(t: T) -> Foo<T> {
      (... schtuff ...)
      when T is Debug {
        println!("Initialized Foo with value: {:?}", t);
      } else {
        println!("Initialized Foo with unprintable value");
      }
    return ret;
    }
```

I guess this conditional compilation would take place during/after monomorphisation.
Is something like this supported by the compiler? (yet?) Is there a name for such a feature?
Any plans to support it?

**Comment by bjorn3** [comment]
You could use specialisation (requires a nightly compiler and isn't sound atm, so you could cause memory unsafety using it):

https://play.rust-lang.org/?gist=e4e043e1fee70030e2242134f6007155&version=nightly&mode=debug&edition=2015

```rust
#![feature(specialization)]
#![allow(dead_code)]

use std::fmt::Debug;

trait MaybeDebug {
    fn maybe_debug(&self);
}

impl<T> MaybeDebug for T {
    default fn maybe_debug(&self) {
        println!("Initialized Foo with unprintable value");
    }
}

impl<T: Debug> MaybeDebug for T {
    fn maybe_debug(&self) {
        println!("Initialized Foo with value: {:?}", self);
    }
}

struct Foo<T> {
    t: T
}

impl<T> Foo<T> {
    fn new(t: T) -> Foo<T> {
        // (... schtuff ...)
        t.maybe_debug();
        Foo {
            t
        }
    }
}

struct NoDebug;

fn main() {
    Foo::new(());
    Foo::new(0);
    Foo::new(NoDebug);
}
```

**Comment by dtolnay** [comment]
Specialization a.k.a. `default fn` is the closest to what you have in mind -- that feature is being tracked in https://github.com/rust-lang/rust/issues/31844.

Something like `when T is Debug { ... }` would require [an RFC](https://github.com/rust-lang/rfcs).
