### ISSUE TITLE
unresolved external symbol GetUserProfileDirectoryW

### ISSUE THREAD

**Issue by crusty-dave** [rust-lang/rust#52892]
I am hitting the following link error when trying to link a rust library in VS 2017 & VS 2015.  I am trying to call an FFI function that is in the library.  I don't have any calls to GetUserProfileDirectoryW() in my code.

> jims_uri.lib(std-76a5f3e41ba6c505.std2-64a60500296bcccc86151a235f68563b.rs.rcgu.o) : error LNK2019: unresolved external symbol GetUserProfileDirectoryW referenced in function _ZN3std3sys7windows14fill_utf16_buf17hbd7bb37a3f16fbfcE

My suspicion is that I need something in addition to libc?  However, if that is the case, it would seem to be a bug?  In any case, a work-around would be appreciated.  Perhaps an issue with static libraries.  Also I am building on Windows 10 / 64-bit.

Cargo.toml

```
[package]
name = "jims_uri"
version = "0.1.0"
authors = ["me"]

[lib]
crate-type = ["staticlib", "rlib"]

[dependencies]
libc = "0.2.0"
widestring = "0.3.0"
lazy_static = "1.0.2"

url = "1.7.1"

```

**Comment by crusty-dave** [comment]
Thanks for the link, unfortunately it appears that I am using C:\Program Files (x86)\Windows Kits\8.1\Lib, why won't that work?  If I am building my Visual Studio project with the same version, why should Rust care?  Am I pulling in something that requires 10\Lib - if so - isn't that a bug?

**Comment by retep998** [comment]
`GetUserProfileDirectoryW` is from `userenv.lib` which does come with the Windows 8.1 SDK. When linking against a Rust `staticlib` you must also link against certain libraries that it depends on. Rust used to automatically tell you which libraries you needed, but unfortunately you must now explicitly ask for it by passing `--print native-static-libs` to Rust.

![](https://i.imgur.com/IiSIzHF.png)

**Comment by crusty-dave** [comment]
Thanks, after a bit of work (google) I figured out how to get the command that I needed to add the option to, however, what do I do with this?

> note: Link against the following native artifacts when linking against this static library. The order and any duplication can be significant on some platforms.
> 
> note: native-static-libs: advapi32.lib ws2_32.lib userenv.lib shell32.lib msvcrt.lib
> 

Is there a way to specify them in my cargo.toml file?

Thanks again,
-Dave

**Comment by retep998** [comment]
You're creating a `staticlib` in Rust to then use from some other project probably in another language, right? If so, what `--print native-static-libs` is telling you is what libraries you need to link to when linking to `jims_uri.lib` *from your other project*.

**Comment by crusty-dave** [comment]
I added userenv.lib to my MSVC project, but I still get the link error:

> Severity	Code	Description	Project	File	Line	Suppression State
> Error	LNK2019	unresolved external symbol GetUserProfileDirectoryW referenced in function _ZN3std3sys7windows14fill_utf16_buf17h1f8072387770573dE	JimsSrxInterface	C:\Users\dweaver\git\cic.c\srv\common\JimsSrxInterface\jims_uri.lib(std-a2acd5f5dca269de.std3-89676acb5a26ecabe2ed84f0c51d9c6f.rs.rcgu.o)	1	
> 

I will double check it to make sure I didn't screw it up somehow.

**Comment by crusty-dave** [comment]
After adding the following, it links, thanks so much for all the help! :)

```
#pragma comment(lib, "userenv.lib")
#pragma comment(lib, "ws2_32.lib")

```
This was way too painful...

**Comment by rokit** [comment]
For future visitors, here is an easy cargo command to see the libs:
```
cargo rustc -q -- --print=native-static-libs
```
-q, --quiet = Do not print cargo log messages
