### ISSUE TITLE
`rustc` doesn't output anything but exits with 101 and doesn't emit any files

### ISSUE THREAD

**Issue by LukasKalbertodt** [rust-lang/rust#52913]
```rust
trait Foo {
    type Out;
}

impl<T> Foo for Box<T> {
    type Out where T: Clone = T;
}

fn main() {}
```

Compiling this code results in no output by `rustc`. But `rustc` exits with 101 and does not produce any artifacts. ([On Playground](https://play.rust-lang.org/?gist=672aaaced9b3c727c0f2db69f023de18&version=stable&mode=debug&edition=2015))

The error happens with:
- `rustc 1.27.1 (5f2b325f6 2018-07-07)`, 
- `rustc 1.27.2 (58cc626de 2018-07-18)`, and
- `rustc 1.29.0-nightly (874dec25e 2018-07-21)`

**Comment by shepmaster** [comment]
```
rustc -Z time-passes a.rs
  time: 0.001	parsing
  time: 0.000	recursion limit
  time: 0.000	crate injection
  time: 0.000	plugin loading
  time: 0.000	plugin registration
  time: 0.000	pre ast expansion lint checks
    time: 0.037	expand crate
    time: 0.000	check unused macros
  time: 0.037	expansion
  time: 0.000	maybe building test harness
  time: 0.000	maybe creating a macro crate
  time: 0.000	creating allocators
  time: 0.000	AST validation
  time: 0.000	name resolution
  time: 0.000	complete gated feature checking
  time: 0.000	lowering ast -> hir
  time: 0.000	early lint checks
  time: 0.000	indexing hir
  time: 0.000	load query result cache
  time: 0.000	looking for entry point
  time: 0.000	looking for plugin registrar
  time: 0.000	loop checking
  time: 0.000	attribute checking
  time: 0.000	stability checking
```

If I set breakpoints on

- `rustc::middle::stability::check_unstable_api_usage`
- `rustc_typeck::check_crate`
- `rustc_passes::rvalue_promotion::check_crate`

It hits the first two but not the third, seemingly pointing to `rustc_typeck::check_crate` returning an `Err`.

**Comment by kennytm** [comment]
The silent exit is a regression. From godbolt,

* #### 1.23.0

    ```
    error: expected `=`, found `where`
     --> <source>:6:14
      |
    6 |     type Out where T: Clone = T;
      |              ^^^^^
    error[E0046]: not all trait items implemented, missing: `Out`
     --> <source>:5:1
      |
    2 |       type Out;
      |       --------- `Out` from trait
    ...
    5 | / impl<T> Foo for Box<T> {
    6 | |     type Out where T: Clone = T;
    7 | | }
      | |_^ missing `Out` in implementation
    error: aborting due to 2 previous errors
    ```

    exit code = 101

* #### 1.24.0–1.25.0

    ```
    error: cannot continue compilation due to previous error
    ```

    exit code = 101

* #### 1.26.0–1.28.0(beta)

    No message, exit code = 101

* #### 1.29.0(nightly)

    No message, exit code = 1

**Comment by Mark-Simulacrum** [comment]
cc @rust-lang/compiler -- it'd be good to find out why we stopped providing any output at all here

**Comment by estebank** [comment]
https://github.com/rust-lang/rust/blob/11f812aa7d1df09724f94c2b095f6dbfd367da17/src/libsyntax/parse/parser.rs#L1349

https://github.com/rust-lang/rust/blob/11f812aa7d1df09724f94c2b095f6dbfd367da17/src/libsyntax/parse/parser.rs#L4940-L4963

**Comment by estebank** [comment]
It's not the parsing itself, it's that in 1.24 the feature was introduced: https://github.com/rust-lang/rust/pull/45904.

**Comment by nikomatsakis** [comment]
Calling P-high but we don't yet have an obvious assignee. Still, seems bad that there is no diagnostic output at all! Not a good look.

**Comment by varkor** [comment]
The core issue is reported in https://github.com/rust-lang/rust/issues/47206. However, the example here also demonstrates that `where` clauses aren't being feature gated properly.

**Comment by varkor** [comment]
I've made https://github.com/rust-lang/rust/pull/53235 to address the surface problem, which is that you can trigger this on stable, without declaring the `generic_associated_types` feature. I thought it was better to fix that part of the problem straight away.

**Comment by varkor** [comment]
Narrowing it down a little more:
https://github.com/rust-lang/rust/blob/1aa6c23a70a2b85693cad2ecaaf9f32b7f588aa2/src/librustc_typeck/astconv.rs#L1157-L1163
`path.def` is `Def::Err` at this point when the `where` clauses are defined, so something's going wrong before that point.
