### ISSUE TITLE
Make unnameable tests an error

### ISSUE THREAD

**Issue by djrenren** [rust-lang/rust#52917]
Right now the compiler will simply allow tests that cannot be run. The following will compile but will not run any tests.

```rust
fn foo() {
  #[test]
  fn bar(){}
}
```

This constitutes a silent failure and should probably be a hard error (or at least a warning). There's a lint for it: `UnnameableTestFunctions` but it isn't run by default.

**Comment by estebank** [comment]
[In nightly](http://play.rust-lang.org/?gist=a9c61d8ce418a0c6cd6501dee2d5d5f9&version=nightly&mode=debug&edition=2015), introduced in #51450:

```
warning: cannot test inner function
 --> src/main.rs:2:3
  |
2 |   #[test]
  |   ^^^^^^^
  |
  = note: #[warn(unnameable_test_functions)] on by default
```

It warns by default, it just hasn't landed in stable yet.
