### ISSUE TITLE
Unable to parse `&!` value into a reference of never type in some conditions

### ISSUE THREAD

**Issue by luojia65** [rust-lang/rust#52933]
My bug reproduces when sometimes I try to use the value of `&!`.

Firstly I tried to get a pointer address on `&()` by `println!("{:p}", &());`, I got an output for pointer address like `0x56082e8a5780`. But when I try it on the reference of a never type like `&!`, I wrote like this: 
```rust
#![feature(never_type)]
fn main() {
    println!("{:p}", &!);
}
``` 
I expected it to print a pointer address like what I did for `&()`. However a compile error occurred:
```
   Compiling hello v0.0.1 (file:///<project root path>)
error: expected expression, found `<eof>`
 --> src/main.rs:3:23
  |
3 |     println!("{:p}", &!);
  |                       ^ expected expression

error: aborting due to previous error

error: Could not compile `hello`.
```
It seems like my rustc has failed to parse `&!`. 
But if I run my code like this: 
```rust
#![feature(never_type)]
fn main() {
    println!("{} {}", std::mem::size_of::<&()>(), std::mem::size_of::<&!>());
                                                                   // ^^ I use `&!` here
}
```
A correct output is printed: `8 8`. 

There is nothing in my `Cargo.toml` dependencies, and I got my rustc version using `rustc --version --verbose`:
```
rustc 1.29.0-nightly (e94df4acb 2018-07-31)
binary: rustc
commit-hash: e94df4acb4c3f42fdc224a7164b63a99240add1e
commit-date: 2018-07-31
host: x86_64-apple-darwin
release: 1.29.0-nightly
LLVM version: 7.0
```

**Comment by kennytm** [comment]
This is expected: `!` is a type, not a value. It's like the following is an error as well:

```rust
fn main() {
    println!("{:p}", &usize);
}
```

In fact, the point of `!` is that *no* values will have this type, so there won't be any short-hand to construct a value of type `!` either. You could write `&panic!()`, `&loop {}`, `&return` etc, these expressions have type `&!` by not ever returning any value.

**Comment by luojia65** [comment]
Unlike `()`, `!` is not a value. Thank you @kennytm ! 👍
