### ISSUE TITLE
NLL: regressions due to weakness in two-phase borrows 

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#52934]
Look at https://github.com/rust-lang-nursery/rust-clippy/issues/2982

It seems like some of the changes NLL is requiring were expected to be handled silently by two phase borrows

**Comment by pnkfelix** [comment]
(its also possible that rust-lang-nursery/rust-clippy#2982 was in fact due to this oversight in the 2018 migration mode: #52967 )

**Comment by nikomatsakis** [comment]
Based on the contents of rust-lang-nursery/rust-clippy#2982, it appears @pnkfelix that you now believe these to be *legitimate regressions* (i.e., NLL-fixed-by-NLL)? I'm inclined therefore to close this issue? Or am I wrong...

**Comment by nikomatsakis** [comment]
Leaving untriaged for now.

**Comment by mikerite** [comment]
This is fixed. The borrow checker warnings aren't emitted with the current nightly compiler. See rust-lang-nursery/rust-clippy#3085.

**Comment by nikomatsakis** [comment]
Nominating for discussion — probably we can just close this? I put it on the milestone too just to help us keep things tidy

**Comment by pnkfelix** [comment]
@nikomatsakis its not that I thought they were legitimate regressions.

It that I believe(d) rust-lang-nursery/rust-clippy#2982 was **mis-identified** as being the fault of 2PB, when in fact it was a much simpler problem that was subsequently fixed.

Its quite possible that we *do* need an issue tracking all the cases where 2PB could be improved. But I don't think it would be useful for this issue to serve that purpose.

**Comment by pnkfelix** [comment]
Having said that, I think I agree that some minimized tests that model what was going on in  rust-lang-nursery/rust-clippy#2982 may indeed be a good idea, assuming that those cases really do significantly differ from any tests that were part of PR #52967

**Comment by pnkfelix** [comment]
(I'll do the minimization, since I already had dipped my toe in this a month ago.)

**Comment by pnkfelix** [comment]
Now, having done the minimization, there are two cases to consider:

 1. The `self.hash_expr(&self.cx.body(..).value)` invocations on lines 20 and 23,
 2. The `reg.register_late_lint_pass(Box::new(Thing::new(&reg.sess.target)))` invocation on line 45

I *think* niko has already expressed a little concern about case 1 in [a comment here on the clippy repo](https://github.com/rust-lang-nursery/rust-clippy/pull/3085#discussion_r212942180).

(I want to look a little more carefully at both cases before I add more notes...)

**Comment by pnkfelix** [comment]
Result of investigating case 1: The reason that the call to `self.hash_expr` is allowed there, AFAICT, is that `self` has an *immutable borrow* somewhere along the path from it to the AST map it borrows, and therefore a `&mut self` still cannot do anything to interfere with the result of the `&self.cx.body(..).value`.

For example, this works: https://play.rust-lang.org/?gist=bd9009010499a92e0cfb9985d7bf1330&version=nightly&mode=debug&edition=2018

But if I change the latter to *mutably borrow* the AST map from `SpanlessHash`, it stops working: https://play.rust-lang.org/?gist=b3e05fdc13eff13093541487df2bfa06&version=nightly&mode=debug&edition=2018

This is enough to convince me that we aren't seeing evidence of unsoundness from case 1 in my previous comment.

(I'm going to dive into case 2 next.)

**Comment by pnkfelix** [comment]
I think case 2 is another instance of the same phenomenon: the `Registry` has only an immutable reference to the `Session`, and so the `reg.register_late_lint_pass` does not interfere with the `&reg.sess.target` borrow.

**Comment by pnkfelix** [comment]
Hmm I may have spoken too soon for case 2; unlike the previous analysis, changing to `struct Registry<'a> { sess: &'a mut Session }` does not cause the compiler to start rejecting the example. Investigating now.

**Comment by pnkfelix** [comment]
Oh, in my minimization, `struct TriviallyCopyPassByRef` carries no references (and has no lifetimes on its type). That might explain why changing the registry to have a `&mut Session` did not cause any errors to trigger.

**Comment by pnkfelix** [comment]
One might reasonably wonder: "Wait, what do those examples (case 1 and 2 from [my above comment](https://github.com/rust-lang/rust/issues/52934#issuecomment-418146411)) have to do with two-phase borrows."

I think the best answer to might be for me to just add two tests using revisions to illustrate the cases here, with a revision set like { borrowck=ast, borrowck=mir, borrowck=mir+two-phase-borrows }, and then that should show how the errors arise when you leave out support for two-phase-borrows.

**Comment by pnkfelix** [comment]
(I have a test written up, will post a PR soon.)
