### ISSUE TITLE
Cargo 0.29.0 listed in stage0.txt cannot build the beta branch

### ISSUE THREAD

**Issue by Keruspe** [rust-lang/rust#52935]
Either I'm missing something on my side or it seems that cargo 0.29 cannot buid the beta as clippy i using `edition` in its `Cargo.toml`

```
error: failed to parse manifest at `/var/tmp/paludis/build/dev-lang-rust-1.29.0-scm/work/rust-1.29.0-scm/src/tools/clippy/Cargo.toml`
                                                                                                                                     
Caused by:                                                                                                                           
  the cargo feature `edition` requires a nightly version of Cargo, but this is the `stable` channel                                  
```

**Comment by oli-obk** [comment]
This only works inside the rust build system. You can't build rust with a beta compiler without the build system hackery.

**Comment by Keruspe** [comment]
Well, this is the output of `./x.py dist` so I guess it qualifies as « inside the rust build system », doesn’t it?

**Comment by oli-obk** [comment]
A clean checkout with default settings and all submodules updated gives you this error? There's always a very specific nightly + cargo that are needed to build the compiler.

**Comment by semarie** [comment]
@oli-obk  the beta branch could be build with stable compiler. the exact version is referencied in `src/stage0.txt`.

as the switch to 1.28.0 as stable is recent (I am unsure if it is already published, but according to RELEASES.md it should be 2018-08-02), @Keruspe could you check the output of `cargo -vV` ? I have the same error when cargo from 1.27.2 is used, but it seems good with 1.28.0 (my build isn't finished, but with 1.27.2 it fails at begining).

my output (for rustc and cargo):
```
$ rustc -vV
rustc 1.28.0
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-openbsd
release: 1.28.0
LLVM version: 6.0
$ cargo -vV
cargo 1.28.0
release: 1.28.0
```

**Comment by Mark-Simulacrum** [comment]
It is unsupported to build not through x.py - it looks like you might be doing that.

**Comment by semarie** [comment]
you could specify your own rustc/cargo binaries via `config.toml`. in my case, it is because openbsd isn't a supported platform.

**Comment by oli-obk** [comment]
Setting RUSTC_BOOTSTRAP=1 should suffice
