### ISSUE TITLE
Emitted LLVM bytecode is missing `mainCRTStartup` symbol

### ISSUE THREAD

**Issue by hydroper** [rust-lang/rust#52950]
Just running `rustc -emit llvm-bc hello_world.rs` generates `hello_world.bc` fine, but, if attempting to run `lld-link -o hello_world.bc` to generate an exe, I get:

> lld-link: error: <root>: undefined symbol: mainCRTStartup

It's of course not an `rustc` error, but something is missing in the bytecode I think.

**Comment by nagisa** [comment]
`mainCRTStartup` should be provided by Microsoft’s CRT library which is not information that’s stored in the bytecode. Closing, complain if you feel differently and I’ll reopen.

**Comment by hydroper** [comment]
@nagisa Will `rustc` always emmit the same kind of LLVM bytecode among different host environments? 

E.g., if I'm emmiting `main.bc` from Mac OSX, the LLVM bytecode will still depend on the `mainCRTStartup`, just like the way I emmit it from Windows. Is that right?

**Comment by nagisa** [comment]
Host environment is of no consequence here. Only the target matters. If you compile targeting Windows, it will contain `mainCRTStartup` regardless of what host you compile from. If you compile targeting macOS, it will not contain `mainCRTStartup` and instead contain macOS-specific function(s).
