### ISSUE TITLE
Search bar for stable docs broken on Chromium

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/rust#52999]
Since the 1.28.0 release, the search bar on https://doc.rust-lang.org/std/ has stopped working for me on Chromium 68.0.3440.84. Typing something to search doesn't do anything and the console shows this error:

```
Uncaught TypeError: Cannot read property 'length' of undefined
    at findArg (main.js:689)
    at execQuery (main.js:954)
    at execSearch (main.js:1342)
    at search (main.js:1427)
```

This does not happen on Firefox. The nightly docs over at https://doc.rust-lang.org/nightly/std/ also work fine for me.

**Comment by Mark-Simulacrum** [comment]
cc @rust-lang/docs -- this looks rather bad

**Comment by Mark-Simulacrum** [comment]
er, @rust-lang/rustdoc I think is what I meant

**Comment by djrenren** [comment]
FWIW, just tested on Chrome Version 68.0.3440.84 on Windows and it works fine.

**Comment by kennytm** [comment]
Works fine for me too. @jonas-schievink try to [clear your cache](https://superuser.com/questions/220179/how-can-i-do-a-cache-refresh-in-google-chrome)?

**Comment by GuillaumeGomez** [comment]
@jonas-schievink What search did you make?

**Comment by jonas-schievink** [comment]
It does work now (might indeed have been a bad cache - maybe the caching strategy isn't quite optimal?). Closing.
