### ISSUE TITLE
Deduplicate Cargo in the RLS on CI

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#53005]
Once https://github.com/rust-lang/rust/pull/52919 lands we'll have updated the RLS which updates `racer`, and `racer` has recently picked up a dependency on the `cargo` crate. Unfortunately though this is a `cargo` crate from crates.io, which differs from the `src/tools/cargo` crate in-tree. This means that when we build the RLS it's linking against *two* optimized versions of Cargo, which not only takes up a good deal of space but also takes up a good deal of build time.

In talking with @nrc on IRC one solution here would be to avoid using racer's `cargo` feature. The RLS already depends on `cargo`-the-crate and should be able to provide the functionality necessary for racer, for example implementing [racer's `ProjectModelProvider` trait](https://github.com/racer-rust/racer/blob/18bd2c510a195bb21fe520c73c43a4ed9515e6c7/src/racer/project_model.rs#L33-L39)

**Comment by alexcrichton** [comment]
In fixing this we should add a `tidy` check which ensures that in rust-lang/rust's workspace there's only one entry in the lock file for the `cargo` crate

**Comment by nrc** [comment]
cc https://github.com/racer-rust/racer/issues/914

**Comment by mati865** [comment]
cc https://github.com/rust-lang/rust/issues/52072
