### ISSUE TITLE
2018 update: error[E0463]: can't find crate for `structopt`

### ISSUE THREAD

**Issue by gibfahn** [rust-lang/rust#53010]
## WORKAROUND:

 The fix is to add structopt as a direct dependency in the `Cargo.toml`.

## Error

I hit this error when upgrading a CLI crate to the Rust 2018 edition:

```console
$ cargo build
   Compiling quicli-edition v0.1.0 (file:///Users/gib/tmp/quicli-edition)
error[E0463]: can't find crate for `structopt`
 --> src/main.rs:8:17
  |
8 | #[derive(Debug, StructOpt)]
  |                 ^^^^^^^^^ can't find crate

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: Could not compile `quicli-edition`.

To learn more, run the command again with --verbose.
```

I've tried to give a minimal reproduction here: [gibfahn/quicli-edition](https://github.com/gibfahn/quicli-edition)

Basically: 
- I followed the [quicli getting started guide](https://killercup.github.io/quicli/) to get set up. 
- Everything works in the 2015 edition (https://github.com/gibfahn/quicli-edition/commit/626f47c494f7595fe3d64dc8d4cb1b6be33819e6)
- When I upgrade (following the edition guide) I get the above error: (https://github.com/gibfahn/quicli-edition/commit/81977e7c934194e226d99bf9a881c0b3bded921f)
- The fix is to add structopt as a direct dependency in my `Cargo.toml`. This wasn't necessary with the 2015 edition (https://github.com/gibfahn/quicli-edition/commit/4ce7ba9d09b96f52dbbc0f1f214617a2fdbff82b).

Obviously this could be just a mistake on my part, or it could be a change `quicli` needs to make (cc/ @killercup ).

**Comment by killercup** [comment]
Very interesting, thanks for opening this issue and providing the
reproduction steps.

Quicli uses `pub use foo::*;` to re-export (proc) macros. Apparently, this
no longer works the same way in the new edition?

**Comment by tathanhdinh** [comment]
I fall in this problem too :), 
@killercup do you know how to fix this?

**Comment by killercup** [comment]
Haven't looked into it yet, @tathanhdinh. I'll ask around and try to come up with an alternative. Until then, you should probably just import structopt directly.

**Comment by ErichDonGubler** [comment]
I was able to fix this by using an explicit import from the `prelude` module in `quicli`:

```rust
use quicli::prelude::StructOpt;
```

Using a glob import (`use quicli::prelude::*`) doesn't seem to have the desired effect, though. I get the following error when attempting to use the glob import like documentation indicates:

```
error[E0433]: failed to resolve. Could not find `structopt` in `{{root}}`
  --> src/main.rs:44:17
   |
44 | #[derive(Debug, StructOpt)]
   |                 ^^^^^^^^^ Could not find `structopt` in `{{root}}`
```

My `rustup show` says:

```
active toolchain
----------------

beta-x86_64-pc-windows-msvc (default)
rustc 1.30.0-beta.7 (0ebb25088 2018-09-22)
```

**Comment by synek317** [comment]
Have you found any other solution for this?

**Comment by gibfahn** [comment]
>Have you found any other solution for this?

Yeah, see the first line:

>The fix is to add structopt as a direct dependency in the Cargo.toml.

**Comment by jackh726** [comment]
@killercup @Centril Just tested this on the latest nightly and it builds without issue. Does this need a test?

**Comment by Centril** [comment]
@jackh726 yeah that would be nice.

**Comment by steveklabnik** [comment]
Triage: doesn't look like we ever got a test.

**Comment by gibfahn** [comment]
>... nor an MCVE, therefore I think this can be closed

When I filed this I did include what I believe to be an MCVE, see this in the issue:

>I've tried to give a minimal reproduction here: [gibfahn/quicli-edition](https://github.com/gibfahn/quicli-edition)

I just tried it, and after updating to the 2021 edition, it still fails.

Repro steps:

```console
❯ git clone https://github.com/gibfahn/quicli-edition && cd quicli-edition

❯ cargo --version
cargo 1.71.0 (cfd3bbd8f 2023-06-08)

❯ cargo build
   Compiling quicli-edition v0.1.0 (/Volumes/Shared-Data/Users/gib/code/tmp/quicli-edition)
error[E0433]: failed to resolve: could not find `structopt` in the list of imported crates
 --> src/main.rs:4:17
  |
4 | #[derive(Debug, StructOpt)]
  |                 ^^^^^^^^^ could not find `structopt` in the list of imported crates
  |
  = note: this error originates in the derive macro `StructOpt` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0433`.
error: could not compile `quicli-edition` (bin "quicli-edition") due to previous error

❯ sed 's/# structopt/structopt/' <Cargo.toml >Cargo.toml.tmp

❯ mv Cargo.toml.tmp Cargo.toml

❯ cargo build
    Finished dev [unoptimized + debuginfo] target(s) in 0.02s
warning: the following packages contain code that will be rejected by a future version of Rust: syn v0.14.5
note: to see what the problems were, use the option `--future-incompat-report`, or run `cargo report future-incompatibilities --id 1`
``` 

So could we reopen this?

**Comment by apiraino** [comment]
@gibfahn as you correctly point out, the tutorial suggests adding `structopt` as direct dependendy and importing that crate. Maybe the tutorial was updated since opening this issue?

(importing the crates as suggested in the tutorial leads to another error, unrelated to this issue)

**Comment by gibfahn** [comment]
I believe the quicli tutorial was updated to work around this bug (probably by @killercup who posted in this thread). Unless this is expected cargo/rust behaviour, this seems like a bug we should fix no?

**Comment by apiraino** [comment]
I think this was the expected action to be taken when migrating from 2015 -> 2018.

Compiling a 2015 edition _today_ with the provided code is proving a bit difficult (tried with `cargo +1.30 check`), all the dependencies have upgraded in a way that I think it complicates reproducing a real MCVE
