### ISSUE TITLE
NLL migration mode is accepting code that both NLL and AST-borrowck reject!

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#53026]
D'oh: while investigating #52979, I found a case where we are downgrading the NLL errors to warnings (due to the migration mode added in #52681), but AST-borrowck issues an error for the test! (This may explain #53004, at least in part...)

Namely, [ui/borrowck/issue-45983.rs](https://github.com/rust-lang/rust/blob/master/src/test/ui/borrowck/issue-45983.rs). Here is the test:

https://github.com/rust-lang/rust/blob/e415b5ecc0d7f669a96404fafc030819997f03e3/src/test/ui/borrowck/issue-45983.rs#L11-L19

Here is the AST-borrowck output (a hard error):

https://github.com/rust-lang/rust/blob/e415b5ecc0d7f669a96404fafc030819997f03e3/src/test/ui/borrowck/issue-45983.stderr#L1-L11

And here is the NLL output (another hard error):

https://github.com/rust-lang/rust/blob/e415b5ecc0d7f669a96404fafc030819997f03e3/src/test/ui/borrowck/issue-45983.nll.stderr#L1-L25

But here is the output from `-Z borrowck=migrate -Z two-phase-borrows`:

```
warning: not reporting region error due to nll
  --> ../src/test/ui/borrowck/issue-45983.rs:17:27
   |
17 |     give_any(|y| x = Some(y));
   |                           ^

warning: borrowed data escapes outside of closure
  --> ../src/test/ui/borrowck/issue-45983.rs:17:18
   |
16 |     let x = None;
   |         - `x` is declared here, outside of the closure body
17 |     give_any(|y| x = Some(y));
   |               -  ^^^^^^^^^^^ `y` escapes the closure body here
   |               |
   |               `y` is a reference that is only valid in the closure body
   |
   = warning: This error has been downgraded to a warning for backwards compatibility with previous releases.
           It represents potential unsoundness in your code.
           This warning will become a hard error in the future.

warning[E0594]: cannot assign to `x`, as it is not declared as mutable
  --> ../src/test/ui/borrowck/issue-45983.rs:17:18
   |
16 |     let x = None;
   |         - help: consider changing this to be mutable: `mut x`
17 |     give_any(|y| x = Some(y));
   |                  ^^^^^^^^^^^ cannot assign
   |
   = warning: This error has been downgraded to a warning for backwards compatibility with previous releases.
           It represents potential unsoundness in your code.
           This warning will become a hard error in the future.
```

ui/borrowck/issue-45983.rs is one particular instance of this, but now that I've found one, I'm certain there are more.

This is pretty bad. Very high priority to fix.

**Comment by matthewjasper** [comment]
This code looks suspicious:
https://github.com/rust-lang/rust/blob/59fa6bd6c14eebd213884da08a33639b4c848bb3/src/librustc/infer/error_reporting/mod.rs#L306-L312

**Comment by pnkfelix** [comment]
Ha I should have just left this to @matthewjasper to fix, since we seem to have independently identified the culprit.

**Comment by matthewjasper** [comment]
I think I've already assigned myself to enough issues.
