### ISSUE TITLE
Does FromRawFd own the RawFd?

### ISSUE THREAD

**Issue by npmccallum** [rust-lang/rust#53029]
`RawFd` is an alias to `c_int`, which implements `Copy`. However, it is not clearly documented whether or not passing `RawFd` to `FromRawFd` means that the resulting object will close the file descriptor when it is dropped. If so, then `Self` should probably be required to implement `Drop`.

**Comment by FenrirWolf** [comment]
Which part is unclear? The [documentation](https://doc.rust-lang.org/std/os/unix/io/trait.FromRawFd.html#tymethod.from_raw_fd) for `from_raw_fd` states the following: "This function **consumes ownership** of the specified file descriptor. The returned object will take responsibility for closing it when the object goes out of scope." (emphasis theirs).

**Comment by npmccallum** [comment]
I knew I missed something. Thanks!
