### ISSUE TITLE
Poor debug info in optimized code

### ISSUE THREAD

**Issue by jsgf** [rust-lang/rust#53036]
At the moment debugging optimized code is pretty tricky. Even with full debug info enabled, most/all of the locals and parameters are `<optimized out>`. (Linux + gdb)

I believe that DWARF can include info to regenerate the logical value of a variable that has been removed by optimization. Is this something llvm needs to support, or rustc, or both?

In general how can this be improved?

cc @tromey @Mark-Simulacrum

**Comment by tromey** [comment]
The way to check a specific case is to following the instructions here: https://rust-lang-nursery.github.io/rustc-guide/compiler-debugging.html#debugging-llvm.  In particular what you want to do is compile a small test program, have it emit the LLVM IR (see the discussion of `-C llvm-args=-print-after-all`), and then search through the dumps to see when the debug information is lost.

**Comment by tromey** [comment]
Bug #46698 is a specific case to still be investigated, FWIW.

**Comment by steveklabnik** [comment]
Triage: while this bug does contain one specific case, it's also very general. We have a bunch of bugs open related to debuginfo not being sufficient. I'm going to make a judgement call and give this one a close. Please file follow-up issues for specific things that can be improved, if issues aren't open already. Thanks!
