### ISSUE TITLE
Should warn for enabling the same feature twice

### ISSUE THREAD

**Issue by scottmcm** [rust-lang/rust#53032]
I just noticed that rustc_mir is enabling `in_band_lifetimes` twice:

https://github.com/rust-lang/rust/blob/88e0ff14a81a2122222e32cf7c285f585c516cfd/src/librustc_mir/lib.rs#L18

https://github.com/rust-lang/rust/blob/88e0ff14a81a2122222e32cf7c285f585c516cfd/src/librustc_mir/lib.rs#L30

Would be good to have a warning to help people notice this kind of superfluous code.

**Comment by varkor** [comment]
This is fixed by https://github.com/rust-lang/rust/pull/52644.
