### ISSUE TITLE
Procedural Macros don't seem to be working

### ISSUE THREAD

**Issue by CryZe** [rust-lang/rust#53064]
It's not entirely clear to me whether they are supposed to be working on the beta channel like I'm trying to use them (function like), but at least the errors I'm getting contradict themselves, so if they aren't supposed to be working like this, then the errors need some work at least:
![https://i.imgur.com/WV2yj3S.png](https://i.imgur.com/WV2yj3S.png)

**Comment by CryZe** [comment]
Ah, looks like this is waiting on `use_extern_macros`. Not sure if the errors are worth cleaning up then.

**Comment by dtolnay** [comment]
Use_extern_macros is already being stabilized in https://github.com/rust-lang/rust/pull/50911 so I don't believe we need to invest in fixing the error message. Thanks anyway!
