### ISSUE TITLE
rust-docs components for some triples stopped being generated after 1.25.0

### ISSUE THREAD

**Issue by djc** [rust-lang/rust#53070]
Not sure if this is the right repo, feel free to redirect me.

Between 1.25.0 and 1.26.0 something changed such that a number of target triples no longer have the `rust-docs` component available on static.r-l.o (for example, `mips-unknown-linux`). Was this intentional, and if so, what was the rationale? We were actually using these in Gentoo packaging (for some arm variants).

**Comment by cardoe** [comment]
Just leaving the breadcrumb to what initiated this for the future: https://bugs.gentoo.org/660512

**Comment by djc** [comment]
I'll close this as a duplicate from #52133.
