### ISSUE TITLE
1.29 first Crater run

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#53072]
cc @rust-lang/release

**Comment by pietroalbini** [comment]
@craterbot run name=beta-1.29-1 start=1.28.0 end=beta-2018-08-01 cap-lints=warn p=1

**Comment by petrochenkov** [comment]
@pietroalbini 
Does this crater run includes https://github.com/rust-lang/rust/pull/52841?

**Comment by petrochenkov** [comment]
@Mark-Simulacrum 
Not backport, that PR is known to cause some breakage and we need to know what it broke.

**Comment by Mark-Simulacrum** [comment]
Ah, okay. We can probably start a crater run separately for it, let me see if I can do that (on a different issue). Will cc you.

**Comment by Mark-Simulacrum** [comment]
@craterbot name=pr-52841 start=master#40cb4478a3f550bf12d81cdcf08cc9ef3985ed41 end=master#40e4b6ee3dd70a05007915bd1c15c150a7b7899f cap-lints=warn mode=check-only

**Comment by Mark-Simulacrum** [comment]
@craterbot abort=pr-52841

**Comment by Mark-Simulacrum** [comment]
@craterbot abort name=pr-52841

**Comment by Mark-Simulacrum** [comment]
@craterbot run name=pr-52841 start=master#40cb4478a3f550bf12d81cdcf08cc9ef3985ed41 end=master#40e4b6ee3dd70a05007915bd1c15c150a7b7899f cap-lints=warn mode=check-only

**Comment by Mark-Simulacrum** [comment]
Er, wrong issue for all those commands. Shouldn't matter much though.

**Comment by scottmcm** [comment]
Awesome to see the `unstable_name_collisions` warning in the before for a bunch of these breaks :)

**Comment by Mark-Simulacrum** [comment]
Triaged the report, no new regressions -- mostly flatten and https://github.com/rust-lang/rust/issues/53140.
