### ISSUE TITLE
Crater run for 52841, resolve: Implement prelude search for macro paths, implement tool attributes

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#53089]
cc @petrochenkov

**Comment by Mark-Simulacrum** [comment]
@craterbot run name=pr-52841 start=40cb4478a3f550bf12d81cdcf08cc9ef3985ed41 end=40e4b6ee3dd70a05007915bd1c15c150a7b7899f cap-lints=warn mode=check

**Comment by Mark-Simulacrum** [comment]
@craterbot run name=pr-52841 start=40cb4478a3f550bf12d81cdcf08cc9ef3985ed41 end=40e4b6ee3dd70a05007915bd1c15c150a7b7899f cap-lints=warn mode=check-only

**Comment by Mark-Simulacrum** [comment]
:tada: Experiment **`pr-52841`** is completed!
:newspaper: [Open the full report](https://crater-reports.s3.amazonaws.com/pr-52841/index.html).

:warning: If you notice any spurious failure [please add them to the blacklist](https://github.com/rust-lang-nursery/crater/blob/master/config.toml)!
:information_source: **Crater** is a tool to run experiments across parts of the Rust ecosystem. [Learn more](https://github.com/rust-lang-nursery/crater)

(I'm totally craterbot)

cc @petrochenkov

**Comment by petrochenkov** [comment]
Fixed in https://github.com/rust-lang/rust/pull/53270
