### ISSUE TITLE
`existential type` can accept generic bounds that do not specify a trait

### ISSUE THREAD

**Issue by varkor** [rust-lang/rust#53090]
```rust
#![feature(existential_type)]

existential type Foo: 'static; // ok

fn foo() -> Foo {
    "foo"
}

fn bar() -> impl 'static { // error: at least one trait must be specified
    "foo"
}

fn main() {}
```

Although the [RFC](https://github.com/rust-lang/rfcs/pull/2071) wasn't explicit about this, it seems that this is an oversight, as `existential type` should function like return-position `impl Trait`.

**Comment by varkor** [comment]
@rkruppe points out this could be useful when using tokens passed in and out of a module (that is, inside the module in which the `existential type` is declared, we're able to do whatever we like with it, because the type is transparent, but outside we just have a lifetime bound for convenience).

Feel free to close if this is the desired behaviour. I thought it'd be worth double-checking in case this was overlooked.

**Comment by jonhoo** [comment]
@varkor I ran into what I believe is the same issue over in https://github.com/rust-lang/rust/issues/34511:
```rust
trait Foo {
    type Assoc;
}

struct Bar;
impl Foo for Bar {
    existential type Assoc;
}
```
The above doesn't compile. You need to write (note the `: ;`)
```rust
    existential type Assoc: ;
```

**Comment by oli-obk** [comment]
@varkor should we maybe close this issue? I think it's fine for `existential type` to be more powerful than `impl Trait` in return position. We only need to be able to desugar `impl Trait` to `existential type`, there's no obligation in the opposite direction

**Comment by jonhoo** [comment]
@oli-obk that seems reasonable to me, although I do think the parsing issue above ought to be fixed (though that's probably a separate issue).

**Comment by varkor** [comment]
There's nothing wrong in practice with `existential type` being more expressive, but it doesn't seem useful to allow pure lifetime bounds in `existential type` or `impl Trait`. Even though it's possible for them to be different, I don't see a good reason they should be. I still think we should apply the same error for `existential type` (and then potentially relax it later if we find that it's useful).

**Comment by oli-obk** [comment]
Oh yea, I'd be perfectly happy with requiring a trait in the bounds of existential types.

**Comment by doctorn** [comment]
Hello! I'd like to take a look at this

**Comment by oli-obk** [comment]
Great!

So the error for `fn foo() -> impl 'static` is generated in https://github.com/rust-lang/rust/blob/8af675a07576940ba24e3d91abd10b029b937946/src/librustc_passes/ast_validation.rs#L423 

I'm guessing that all that's needed is to replicate the same thing for `ItemKind::Existential` in https://github.com/rust-lang/rust/blob/8af675a07576940ba24e3d91abd10b029b937946/src/librustc_passes/ast_validation.rs#L575

Maybe pull out the check into a method that you can call from both sites
