### ISSUE TITLE
Unix: RwLock is incorrect

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#53127]
I think the [`sys::unix::rwlock` implementation](https://github.com/rust-lang/rust/blob/b2397437530eecef72a1524a7e0a4b42034fa360/src/libstd/sys/unix/rwlock.rs) is incorrect in the sense that it has undefined behavior, for two reasons:

* ~~The access to `write_locked` is not properly synchronized: In `read`, we access `write_locked` even if `pthread_rwlock_rdlock` failed.~~ This is [fixed](https://github.com/rust-lang/rust/pull/55865).
* Worse, POSiX read-write locks have UB when the thread holding the write lock attempts to acquire it again -- and yet nothing is stopping exactly that from happening in `write`. If we really want to use POSIX rwlocks, I think we have to implement a reentrancy detector. (And then maybe we also want to use that for mutex, so that we can use the static initializer and the most efficient code path?)

**Comment by RalfJung** [comment]
I based my statements on http://pubs.opengroup.org/onlinepubs/7908799/xsh/pthread_rwlock_wrlock.html. @sfackler points out that at https://linux.die.net/man/3/pthread_rwlock_wrlock, behavior for re-acquiring the write lock is defined as "may deadlock" -- but not UB.

**Comment by sfackler** [comment]
macOS does explicitly identify the behavior as undefined.

**Comment by sfackler** [comment]
cc @alexcrichton - we talked about this a bit during RustConf.

**Comment by alexcrichton** [comment]
I agree that we're basically at the point that there's a ridiculous amount of constraints from OS primitives that the only program which *doesn't* have undefined behavior is correct ones, and we all know how often we write correct programs.

All these discussions are spread out over a number of issues though and PRs, and it's really difficult to keep it all in my own head at least. "This is UB" is a very strong motivation for reimplementing the standard library's primitives, but I think the scale of a change such as this would probably want to go through the RFC process. Such an RFC would be a great location to centralize all the various hazards of OS primitives and how unreasonable it is for us to try to appease all possible implementations. That in turns provides excellent motivation for alternative strategies.

**Comment by retep998** [comment]
You mean like this RFC? https://github.com/rust-lang/rfcs/pull/1632

**Comment by alexcrichton** [comment]
I've opened an [internals post](https://internals.rust-lang.org/t/standard-library-synchronization-primitives-and-undefined-behavior/8439) to continue more long-form discussion on the topic of continuing to fix these issues.

**Comment by RalfJung** [comment]
I just noticed that the [latest version of the POSIX docs](https://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_rwlock_wrlock.html) mandate

>  If a deadlock condition occurs or the calling thread already owns the read-write lock for writing or reading, the call shall either deadlock or return [EDEADLK].

So some time between the 1997 version and the 2018 version, this seems to have changed.

Can we expect Apple (and generally all our POSIX platforms) to follow a recent enough POSIX to rely on this?

**Comment by Amanieu** [comment]
Older versions of glibc (pre-2.25) use hardware lock elision on Intel CPUs which makes recursive locking succeed when it should otherwise deadlock.

**Comment by RalfJung** [comment]
Looks like [even the 2004 version](https://pubs.opengroup.org/onlinepubs/009695399/functions/pthread_rwlock_trywrlock.html) already says
>  The calling thread acquires the write lock if no other thread (reader or writer) holds the read-write lock rwlock. Otherwise, the thread shall block until it can acquire the lock. The calling thread may deadlock if at the time the call is made it holds the read-write lock (whether a read or write lock).

"may deadlock" here could be interpreted as "or cause UB", but then saying "may deadlock" would be redundant as of course a deadlock is a valid implementation of UB. So arguably, UB was not permitted any more for 15 years now.

@Amanieu 
So that's pre-2016 glibc versions, if I got the release date right.

Bummer, this means we still need to keep the extra reentrant-rwlock-checks around in libstd (but we should have comments explaining that this is just to defend against non-compliant implementations).

**Comment by RalfJung** [comment]
For the question of whether we can rely on macOS using a recent enough POSIX, I found [this "conformance statement"](https://www.opengroup.org/csq/repository/noreferences=1&RID=apple%25252FXY1%25252F13.html) but could not figure out which POSIX version it says macOS conforms with.

**Comment by Amanieu** [comment]
Relevant issue: https://github.com/rust-lang/rust/issues/33770

**Comment by RalfJung** [comment]
Oh, that was for Mutex as well, not rust RwLock?

[This is particularly scary](https://github.com/rust-lang/rust/issues/33770#issuecomment-220847521)... so they still do that? I would think if `PTHREAD_MUTEX_DEFAULT == PTHREAD_MUTEX_NORMAL` one can assume default mutexes to behave the same as "normal" mutexes...

**Comment by Amanieu** [comment]
I believe they still do that, but I haven't checked.

**Comment by RalfJung** [comment]
For `Mutex` only though, right? Arguably that is compliant with POSIX, the standard doesn't *say* that `PTHREAD_MUTEX_DEFAULT == PTHREAD_MUTEX_NORMAL` implies anything, it just seems like a reasonable assumption.

For `RwLock` though, if they still do lock elision (and don't have any reentrancy guards themselves), that's a clear POSIX violation -- right?

**Comment by Amanieu** [comment]
Yes, only for `Mutex` and only if you don't use `pthread_mutexattr_settype` to explicitly select `PTHREAD_MUTEX_NORMAL`. So they are still standard-compliant (ish).

For `RwLock` they currently don't do elision so they are standard compliant. But old glibc is not standard compliant.
