### ISSUE TITLE
`x.py bench` should not use terse format

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#53132]
The output of `./x.py bench` is usually fairly unreadable because of the "terse" output format that generally just prints a single character per test:
```
iiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiiitest collections::hash::bench::find_existing     ... bench:      19,958 ns/iter (+/- 921)
test collections::hash::bench::find_nonexisting  ... bench:      19,747 ns/iter (+/- 1,804)
test collections::hash::bench::get_remove_insert ... bench:         116 ns/iter (+/- 11)
```
It should not use the "terse" format for `bench`, where per-test output is actually expected.

**Comment by Milo123459** [comment]
What should this be changed to? What would be better?

**Comment by RalfJung** [comment]
Nice :)
