### ISSUE TITLE
Lint is insulting

### ISSUE THREAD

**Issue by scorcher24** [rust-lang/rust#53137]
If you want freedom over how to name things and not have to deal with warnings about that, you need add this lint:

`#![allow(bad_style)]`

I personally think that this is ridiculous and insulting to any developer mature enough to decide over his own naming conventions. I therefore propose renaming it to 

`#![allow(custom_naming_conventions)]`

This is a lot more neutral.

**Comment by Mark-Simulacrum** [comment]
We've discussed this previously at https://github.com/rust-lang/rust/issues/41646; I'm going to close this as I believe we've implemented an alternative as suggested here.
