### ISSUE TITLE
Windows 7: std::io::last_os_error is set after printing to stdout

### ISSUE THREAD

**Issue by nicokoch** [rust-lang/rust#53155]
This happens on Windows 7, cannot test on newer Windows.
Basically, something wrong happens with file handles when using the `println!` macro, not sure what exactly.

Minimal repro:
```rust
use std::io;
fn main() {
    println!("{:?}", io::Error::last_os_error());
    println!("{:?}", io::Error::last_os_error());
}
```

Actual output:
```
Os { code: 0, kind: Other, message: "Der Vorgang wurde erfolgreich beendet." }
Os { code: 6, kind: Other, message: "Das Handle ist ungültig." }
```

Expected output:
```
Os { code: 0, kind: Other, message: "Der Vorgang wurde erfolgreich beendet." }
Os { code: 0, kind: Other, message: "Der Vorgang wurde erfolgreich beendet." }
```

Sorry for German localization in the error messages.

I noticed this because of some obscure behaviour in the windows API (a function returned != 0, but LastError wasn't set accordingly).

cc @retep998 
cc https://github.com/retep998/winapi-rs/issues/658

**Comment by nicokoch** [comment]
Additional info: I am using stable rust 1.28

**Comment by hellow554** [comment]
Works for me on Windows 10:
 * 1.27.2
 * 1.28
 * beta
 * nightly

Can't test Windows 7 :( sorry

**Comment by hellow554** [comment]
Does it occur more than once? (e.g. can you reproduce it?)

**Comment by nicokoch** [comment]
Yes, this happens every time I execute the program

**Comment by kennytm** [comment]
("Das Handle ist ungültig" means "The handle is invalid" in English)

**Comment by sfackler** [comment]
Seems like it could be this call: https://github.com/rust-lang/rust/blob/master/src/libstd/sys/windows/stdio.rs#L43-L46

**Comment by retep998** [comment]
Windows system functions generally guarantee that they will set the last error when they fail, but offer no guarantees as to the state of the last error when they succeed (some may clear the error, some may leave it alone, some may change it).

The only action that Rust could take here is for any libstd function that calls system functions to clear the last error when it returns success.

**Comment by nicokoch** [comment]
@sfackler I'm using `git bash`on windows 7 (which is just the mingw terminal if I'm not mistaken.
Maybe that resolves to `Pipe` in the call you mentioned.

Maybe we should `SetLastError(0)` in that branch?

I understand this is not really a bug (if the function errors, we have a pipe, otherwise a terminal), but maybe we can reduce the confusion if we reset the OS error in the former case.

**Comment by retep998** [comment]
Personally I'd rather that Rust offer no guarantees about the result of `Error::last_os_error()` when called after any libstd function that calls some system function. It should only be used directly after calling a system function yourself and only when that function is documented to have set the last error.

**Comment by steveklabnik** [comment]
Triage:

> There is a case to be made here about documenting this though.

I agree, though we should get @rust-lang/libs signoff before re-categorizing this bug.

**Comment by Zymlex** [comment]
Same problem.

Normal:
```rust
let mut stdout = stdout();
stdout.write_fmt(format_args!("{}", unsafe { winapi::um::errhandlingapi::GetLastError() }));
stdout.write_fmt(format_args!("{}", unsafe { winapi::um::errhandlingapi::GetLastError() }));
```
Normal:
```rust
print!("{}", Error::last_os_error());
print!("{}", Error::last_os_error());
```
Bug:
```rust
let mut stdout = stdout();
stdout.write_fmt(format_args!("{}\n", unsafe { winapi::um::errhandlingapi::GetLastError() }));
stdout.write_fmt(format_args!("{}", unsafe { winapi::um::errhandlingapi::GetLastError() }));
```
Bug:
```rust
println!("{}", Error::last_os_error());
println!("{}", Error::last_os_error());
```

Windows 10
1.51.0-nightly
1.49.0-stable
