### ISSUE TITLE
Allow specifying rustup doc toolchain

### ISSUE THREAD

**Issue by pickfire** [rust-lang/rust#53158]
If we would like to open the nightly docs with stable as default toolchain. We need to:

```
$ rustup default nightly
$ rustup doc --std
$ rustup default stable
```

As well, part of my confusions is that I thought the following works.

- `rustup +nightly doc` (cargo uses this so I thought it applies to rustup)
- `rustup doc --toolchain=nightly` (`rustup component add clippy preview --toolchain=nightly` works though)

Or maybe there's a quick way to switch between stable and nightly docs if both toolchains are installed?

**Comment by cuviper** [comment]
You should file this request on https://github.com/rust-lang-nursery/rustup.rs

I agree that `rustup doc --toolchain` would be consistent with how its handled elsewhere.

As a workaround, `rustup run nightly -- rustup doc --std` will set the active toolchain for the next command, which happens to be `rustup` again. :smile:

You can achieve the same thing with `env RUSTUP_TOOLCHAIN=nightly rustup doc --std`.
