### ISSUE TITLE
Pretty printing debuginfo for size-optimized enums is broken

### ISSUE THREAD

**Issue by michaelwoerister** [rust-lang/rust#53153]
The [code](https://github.com/rust-lang/rust/blob/11a902431b8e66da8486b3b9a2d8527746c6ab1a/src/librustc_codegen_llvm/debuginfo/metadata.rs#L1248-L1289) that generates the special DWARF field names for size-optimized enums is broken for a while now. PRs keep getting opened to "fix" this on the pretty printer side but that's not possible because the debuginfo does not contain the necessary information for the pretty printer to correctly decode a given value. See https://github.com/rust-lang/rust/pull/51777#issuecomment-404828872 for an example and some discussion on a possible fix.

This will be fixed eventually when enums get a proper representation in DWARF. Meanwhile, it's unclear how much of a priority fixing this is.

cc @tromey

**Comment by tromey** [comment]
You might as well assign this to me, along with the other enum debuginfo bugs.  I'm working on those as quickly as I can; though since we've normally considered lldb a prerequisite, and that is going somewhat slowly (see PR #52716 for the gory details), it may yet be a while.
