### ISSUE TITLE
moving Pin API  to a seperate module

### ISSUE THREAD

**Issue by nivkner** [rust-lang/rust#53170]
@withoutboats proposed in #49150 to move the Pin API to its own module in order to have a place to provide a high level overview for it.
I am making this a separate issue to discuss this particular aspect of the stabilization process, to not overload the tracking issue.

I found a problem with trying to move the API:
both the `Option` type and `Future` trait in `core` depend on `PinMut` directly so it can't just be moved from `core`, and `PinBox` requires allocation so it can't be in `core`.

should those types just be re-exportd from `core` and `alloc` into a module for the sake of unified documentation then? or is there some other way?

**Comment by cramertj** [comment]
@nivkner It sounds like there's some confusion-- I think the discussion was about moving them into their own module (e.g. `mod pin`), not their own crate. They would still be defined in the core and alloc crates.

**Comment by nivkner** [comment]
yeah, but aren't those apis already exposed as `core::mem::PinMut` and `alloc::boxed::PinBox`?

is there no need to make sure when someone is, for example, switching to `#[no_std]`, that they can just use `extern crate core as std` or something like that? because then uses of `core::pin::PinMut` won't compile

**Comment by withoutboats** [comment]
@nikver with the way core/std are currently set up, the way to do this is:

1. Put `PinMut` in a module called `pin` in `libcore`.
2. In `libstd`, create a `pin` module with `PinBox` and `pub use core::pin::*;` in it.

**Comment by nivkner** [comment]
implemented the change described here in #53227, so closing this, thanks.
