### ISSUE TITLE
[nll] use NLL during bootstrapping

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#53172]
An important correctness milestone is to have the compiler itself use NLL when bootstrapping. We've made some stabs at this but we need to start doing it all the time.

### Instructions

- Log into Zulip and head to [correct thread](https://rust-lang.zulipchat.com/#narrow/stream/122657-wg-nll) to say hi =)
- Select a crate from the list below
- Leave a comment that you are trying it
- Verify that `./x.py build --stage 1` works for you
- Add `#![cfg_attr(not(stage0), feature(nll))]` to the lib.rs file
    - This incantation adds `#![feature(nll)]`, but only once we get to stage1 -- otherwise we'd be using the beta version of NLL, which is old and buggy.)
- Try `./x.py build --stage 1` again and see if it works
- If so, open a PR

### Crate list

- [x] `liballoc` -- https://github.com/rust-lang/rust/pull/53211
- [x] `liballoc_jemalloc` -- https://github.com/rust-lang/rust/pull/53211
- [x] `liballoc_system` -- https://github.com/rust-lang/rust/pull/53211
- [x] `libarena` -- https://github.com/rust-lang/rust/pull/53214
- [ ] `libbacktrace`
- [ ] `libcompiler_builtins`
- [x] `libcore` -- https://github.com/rust-lang/rust/pull/53230
- [x] `libfmt_macros` -- https://github.com/rust-lang/rust/pull/53219
- [x] `libgraphviz` -- https://github.com/rust-lang/rust/pull/53211
- [ ] `liblibc`
- [x] `libpanic_abort` -- https://github.com/rust-lang/rust/pull/53219 
- [x] `libpanic_unwind` -- https://github.com/rust-lang/rust/pull/53219
- [x] `libproc_macro` -- https://github.com/rust-lang/rust/pull/53230
- [x] `libprofiler_builtins` -- https://github.com/rust-lang/rust/pull/53230
- [x] `librustc` -- https://github.com/rust-lang/rust/pull/53230
- [x] `librustc_allocator` -- https://github.com/rust-lang/rust/pull/53230
- [x] `librustc_apfloat` -- https://github.com/rust-lang/rust/pull/53219
- [x] `librustc_asan` -- https://github.com/rust-lang/rust/pull/53214
- [x] `librustc_borrowck` -- https://github.com/rust-lang/rust/pull/53211
- [x] `librustc_codegen_llvm` -- https://github.com/rust-lang/rust/pull/53230
- [x] `librustc_codegen_utils` -- https://github.com/rust-lang/rust/pull/53230
- [x] `librustc_cratesio_shim` -- https://github.com/rust-lang/rust/pull/53219
- [x] `librustc_data_structures` -- https://github.com/rust-lang/rust/pull/53230
- [x] `librustc_driver` -- https://github.com/rust-lang/rust/pull/53219
- [x] `librustc_errors` -- https://github.com/rust-lang/rust/pull/53214
- [x] `librustc_incremental` -- https://github.com/rust-lang/rust/pull/53219
- [x] `librustc_lint` -- https://github.com/rust-lang/rust/pull/53211
- [x] `librustc_llvm` -- https://github.com/rust-lang/rust/pull/53230
- [x] `librustc_lsan` -- https://github.com/rust-lang/rust/pull/53230
- [x] `librustc_metadata` -- https://github.com/rust-lang/rust/pull/53214
- [x] `librustc_mir` -- https://github.com/rust-lang/rust/pull/53230
- [x] `librustc_msan` -- https://github.com/rust-lang/rust/pull/53230
- [x] `librustc_passes` -- https://github.com/rust-lang/rust/pull/53214
- [x] `librustc_platform_intrinsics` -- https://github.com/rust-lang/rust/pull/53230
- [x] `librustc_plugin` -- https://github.com/rust-lang/rust/pull/53214
- [x] `librustc_privacy` -- https://github.com/rust-lang/rust/pull/53214
- [x] `librustc_resolve` -- https://github.com/rust-lang/rust/pull/53214
- [x] `librustc_save_analysis` -- https://github.com/rust-lang/rust/pull/53214
- [x] `librustc_target` -- https://github.com/rust-lang/rust/pull/53219
- [x] `librustc_traits` -- https://github.com/rust-lang/rust/pull/53214
- [x] `librustc_tsan` -- https://github.com/rust-lang/rust/pull/53214
- [x] `librustc_typeck` -- https://github.com/rust-lang/rust/pull/53230
- [x] `librustdoc` -- https://github.com/rust-lang/rust/pull/53230
- [x] `libserialize` -- https://github.com/rust-lang/rust/pull/53230
- [x] `libstd` -- https://github.com/rust-lang/rust/pull/53230
- [x] `libstd_unicode` -- rolled into libcore 
- [x] `libsyntax` -- https://github.com/rust-lang/rust/pull/53230
- [x] `libsyntax_ext` -- https://github.com/rust-lang/rust/pull/53230
- [x] `libsyntax_pos` -- https://github.com/rust-lang/rust/pull/53219
- [x] `libterm` -- https://github.com/rust-lang/rust/pull/53219
- [x] `libtest` -- https://github.com/rust-lang/rust/pull/53230
- [x] `libunwind` -- https://github.com/rust-lang/rust/pull/53219
- [ ] `stdsimd`

**Comment by bemeurer** [comment]
I'm going to be attempting this for `liballoc`, `liballoc_jemalloc`, and `liballoc_system` just to start.

**Comment by pnkfelix** [comment]
The remaining four crates:
 * liblibc
 * libbacktrace
 * libcompiler_builtins
 * stdsimd

are all "external dependencies", in the sense that they are crates that have been factored out and are hosted on separate repositories (still within the `rust-lang` or `rust-lang-nursery` ecosystems).

So, it seems like the **vast** majority of work here is done, and the important thing is: It seems clear that we *can* bootstrap ourselves using NLL.

Therefore, I am closing this task as "effectively finished"

**Comment by memoryruins** [comment]
Note: locally, ``libcompiler_builtins`` successfully built with NLL

Well done, everyone :)
