### ISSUE TITLE
[nll] do another crater run and check the results

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#53171]
We have almost fixed all the problems we found in the last crater run. We should do another `cargo check` run at some point. We need to have the `-Zborrowck=mir -Ztwo-phase-borrows` options supplied by default.

Once the crater run is done, we have to analyze the results.

cc @Mark-Simulacrum for advice on the best way to do that, do we need to make a PR with those options enabled by default?

**Comment by Mark-Simulacrum** [comment]
That's probably the easiest way to get what we want, yes.

**Comment by nikomatsakis** [comment]
I'm going to close this -- @lqd did the crater run, and we've analyzed the results and opened the requisite issues. The following links contain the analyzed results:

- [hackmd document](https://hackmd.io/yK9YhE8-TGGA79tqOpkoCA?both)
- https://github.com/nikomatsakis/nll-crater-run-results/pull/1
- ICEs are found in https://github.com/rust-lang/rust/issues/53482
