### ISSUE TITLE
Tracking Issue for const `unreachable_unchecked`

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/rust#53188]
Currently one cannot call `unreachable_unchecked` in constant functions, so one cannot add hints of the form:

```rust
const fn foo(x: i32) -> i32 {
    if x < 0 { unreachable_unchecked() } else { x * 2 } 
}
```

These types of hints can heavily influence code generation, which can substantially change the performance of `const fn` when they are invoked at run-time. 

It would be a shame to have to write and call `foo_compile_time` and `foo_run_time` because the code generated for `foo_compile_time` is sub-par.

This issue has been assigned to @canova via [this comment](https://github.com/rust-lang/rust/issues/53188#issuecomment-660317181).

**Comment by gnzlbg** [comment]
@oli-obk the RFC for `if`/`match` in const was merged and is pending an implementation right? When that's implemented, will `unreachable_unchecked` still be useless?

**Comment by oli-obk** [comment]
No it makes sense after we have conditional control flow.

**Comment by q2p** [comment]
As I understand `if` / `match` in const functions is now implemented.
Can `unreachable_unchecked` be made `const fn` now?

**Comment by oli-obk** [comment]
yes. Basically you just need to add the `rustc_const_unstable` attribute to the intrinsic and wrapper function. This is documented at https://rustc-dev-guide.rust-lang.org/stability.html?highlight=rustc_const_un#rustc_const_unstable Let me know if anything is unclear (in which case we should update the guide)

**Comment by canova** [comment]
Hi, It looks like previous PR is not being worked on currently. I'm working on this and will create a PR soon.
@rustbot claim

**Comment by josephlr** [comment]
As mentioned in #76209, this issue should be reopened (to track stablization)

**Comment by lzutao** [comment]
cc @RalfJung ^
