### ISSUE TITLE
[nll] optimize + fix `check_if_reassignment_to_immutable_state`

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#53189]
`check_if_reassignment_to_immutable_state` has the of handling assignments to immutable local variables. These are a bit tricky: you are allowed to assign to an immutable local variable, but only if it has never been assigned to before. Actually, the logic implemented in the NLL borrow checker is kind of wrong (or at least inconsistent with the AST checker). It's also just slow.

Here is an example of the sort of assignments that should be accepted ([playground](https://play.rust-lang.org/?gist=ea1288910f0a2d7c35c4987908e500dd&version=nightly&mode=debug&edition=2015)):

```rust
#![feature(nll)]

fn main() {
    let x: (u32, u32);
    
    if true {
        x = (1, 2);
    } else {
        x = (3, 4);
    }
    
    drop(x);
}
```

This example is **rightly rejected** (but we should check to ensure we have a test) ([playground](https://play.rust-lang.org/?gist=5d731471b5de93c6e15d198feb5fc102&version=nightly&mode=debug&edition=2015)):

```rust
#![feature(nll)]

fn main() {
    let x: (u32, u32);
    x = (1, 2);
    x = (3, 4);
    drop(x);
}
```

This example **should be rejected but currently is not** ([playground](https://play.rust-lang.org/?gist=bddb5e348fd76c46b13b5a71eea1df59&version=nightly&mode=debug&edition=2015)):

```rust
#![feature(nll)]

fn main() {
    let x: (u32, u32);
    
    x.0 = 22;
}
```

In addition to being slightly wrong, the current implementation is also slow. It iterates over all initialized paths and checks that the path being assigned to (e.g., `x.0` in the third example) is disjoint from all of them:

https://github.com/rust-lang/rust/blob/52c785bfc24e43c668c9022cc1e79edcd6dcfd7c/src/librustc_mir/borrow_check/mod.rs#L1612-L1619

I will write below how I think it *should* work.

**Comment by nikomatsakis** [comment]
I think what we should do:

- Distinguish the case of assignment directly to an **immutable local** (`x = ...`) from **any other place**.
  - For assignments to an immutable local, we find the move-path-index and just check the "ever initialized" bit directly.
  - For assignments to any other place, we use the `self.access_place` method with `LocalMutationIsAllowed::No` (unlike now, where we use `ExceptUpvars`).

**Comment by nikomatsakis** [comment]
As a bonus, I think we could remove `ExceptUpvars` entirely. It is only used in two places -- the one above, and here:

https://github.com/rust-lang/rust/blob/master/src/librustc_mir/borrow_check/nll/invalidation.rs#L358-L372

and both should now be just `No`.

**Comment by nikomatsakis** [comment]
@spastorino would like to take this on.

**Comment by pnkfelix** [comment]
At some point I thought we had considered allowing a structs fields to be initialized independently .... don’t remember how far that went at the moment ....

**Comment by nikomatsakis** [comment]
@pnkfelix 

We were considering it, but we don't presently allow it. Even with NLL this does not compile, for example:

```rust
#![feature(nll)]

fn main() {
    let x: (u32, u32);
    x.0 = 1;
    x.1 = 2;
    println!("{:?}", x);
}
```

**Comment by nikomatsakis** [comment]
It's true though that the existing borrow checker is sort of inconsistent here -- if you do `let mut x`, then it permits `x.0 = 1` and `x.1 = 2` but rejects using `x` as a whole (just like NLL does).

**Comment by nikomatsakis** [comment]
I was suggesting that we match the existing behavior because it's simple to do — I am not opposed to being smarter later on though. 

I guess to do this the "right" way we would do something like:

- Find the move path corresponding to the place being assigned
  - If there is no *precise* match, that is an error (e.g., assigning to a single field of a drop struct)
- If there *is* a precise match, check its bit

Sound about right @pnkfelix ?

**Comment by memoryruins** [comment]
Following a similar table format from #53114:

| Sample | AST | MIR | Example |
| - | - | - | - |
| ``let x: (u32, u32); x.0 = 1; x.1 = 2;`` | ❌ | ✔️ | [Example](https://play.rust-lang.org/?gist=339ca215fb57d4919474a01f6b6d655c&version=nightly) |
| ``let mut x: (u32, u32); x.0 = 1; x.1 = 2;`` | ✔️ | ⚠️ | [Example](https://play.rust-lang.org/?gist=5d8a037d192569c9ca06e6cfd9d0df20&version=nightly) |
| ``println!("{:?}", x);`` | ❌ | ❌ | [Example](https://play.rust-lang.org/?gist=ef9366f446aa24e3e979d0028d6b9661&version=nightly) |

**Comment by nikomatsakis** [comment]
@memoryruins I guess that the ⚠️ in that table refers to the fact that you get a warning about the `mut` not being needed? That would be false if we take the simplified version, I guess.

In any case, I can go either way here. I'd be fine with matching the AST checker, because it's easy to do, and then trying to revisit this whole question more carefully (in particular, I would want later references to `x` to work). 

But it's also not that hard to make the current system more efficient, and I think it is *more* internally consistent than what the AST checker does.

**Comment by memoryruins** [comment]
Correct, the ⚠️ refers to the following warning:
```rust
4 |     let mut x: (u32, u32);
  |         ----^
  |         |
  |         help: remove this `mut`
```
