### ISSUE TITLE
env::vars panics if environ is null

### ISSUE THREAD

**Issue by snsmac** [rust-lang/rust#53200]
The following code panics:
```
unsafe { libc::clearenv(); };
assert_eq!(env::vars().count(), 0);
```

The problem is that env assumes that environ is not null. See [Rust env implementation](https://github.com/rust-lang/rust/blob/master/src/libstd/sys/unix/os.rs#L415)

The [clearenv(3 )](http://man7.org/linux/man-pages/man3/clearenv.3.html) function on linux is often implemented by freeing environ and setting it to null. See [uclibc](https://github.com/kraj/uClibc/blob/ca1c74d67dd115d059a875150e10b8560a9c35a8/libc/stdlib/setenv.c#L172) and [glibc](https://github.com/bminor/glibc/blob/master/stdlib/setenv.c#L312)

In my opinion the stdlib could handle this more gracefully and return an empty iterator instead of panicking

**Comment by BurntPizza** [comment]
I'm working on a PR.
