### ISSUE TITLE
miri ICE promote const: impossible case reached

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/rust#53201]
[Playground](https://play.rust-lang.org/?gist=904a700fead099ae8534f3bfa67e7e9d&version=nightly&mode=debug&edition=2015):

```rust
#![feature(const_fn, rustc_attrs, attr_literals, untagged_unions)] 

/// A single unconstrained byte (0-255).
#[derive(Copy, Clone, Debug)]
pub struct ImmByte(u8);
impl ImmByte {
    /// Constructor
    #[inline]
    #[rustc_args_required_const(0)]
    pub const fn new(value: u8) -> Self {
        ImmByte(value)
    }
}

pub struct v128([u8; 16]);

impl v128 {
    #[inline]
    #[rustc_args_required_const(0)]
    pub const unsafe fn const_(imm: [ImmByte; 16]) -> v128 {
        union U {
            imm: [ImmByte; 16],
            vec: v128,
        }
        U { imm }.vec
    }
}

fn main() {
    let _a = v128::const_([
        ImmByte::new(0),
        ImmByte::new(1),
        ImmByte::new(2),
        ImmByte::new(3),
        ImmByte::new(4),
        ImmByte::new(5),
        ImmByte::new(6),
        ImmByte::new(7),
        ImmByte::new(8),
        ImmByte::new(9),
        ImmByte::new(10),
        ImmByte::new(11),
        ImmByte::new(12),
        ImmByte::new(13),
        ImmByte::new(14),
        ImmByte::new(15),
    ]);
}
```

produces

```shell
error: internal compiler error: librustc_mir/transform/promote_consts.rs:334: impossible case reached

thread 'main' panicked at 'Box<Any>', librustc_errors/lib.rs:578:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: aborting due to previous error
```

cc @oli-obk

**Comment by cramertj** [comment]
Not that this fixes the issue, but `[ImmByte; 16]` and `v128([u8; 16])` aren't necessarily guaranteed to have the same representation without `#[repr(C)]` or `#[repr(transparent)]` on both `v128` and `ImmByte`.

**Comment by oli-obk** [comment]
minified:

```rust
#![feature(const_fn, rustc_attrs, attr_literals)] 

#[rustc_args_required_const(0)]
pub const fn new(value: u8) -> u8 {
    value
}

#[rustc_args_required_const(0)]
pub unsafe fn const_(_: u8) {
    unimplemented!()
}

fn main() {
    let _a = const_(new(0));
}
```

https://play.rust-lang.org/?gist=2032873a12df78fc3e4537d26735a050&version=nightly&mode=debug&edition=2015

@eddyb is this a victim of the backwards algorithm for promotion? Just a hunch, but it might have promoted away the call to `new` and then end up trying to promote the `0`, but it's not in the place where it was expected, because it now lives inside the promoted. So it ends up trying to promote an argument in a basic block that was already promoted away

**Comment by gnzlbg** [comment]
thanks @cramertj , I'll update the PR that triggered this - for context https://github.com/rust-lang-nursery/stdsimd/pull/549

**Comment by oli-obk** [comment]
As a workaround until we fix this ICE, you can introduce an intermediate explicit constant for the argument to `v128::const_`. Or is this part of a user-exposed API?

**Comment by gnzlbg** [comment]
This is part of a user-exposed API, but that workaround should allow me to at least get the const tests running.

**Comment by eddyb** [comment]
> Just a hunch, but it might have promoted away the call to new and then end up trying to promote the 0, but it's not in the place where it was expected, because it now lives inside the promoted.

It won't remove the definition if there's more than one use (unless this is fallout from your changes?)

**Comment by oli-obk** [comment]
There's only one use. I don't see how my changes could have caused this, but it seems possible. I'll do a bisection

**Comment by eddyb** [comment]
Oh, I see, `#[rustc_args_required_const]` is `Candidate::Argument` and that's missing something lie:
https://github.com/rust-lang/rust/blob/a3ad012e2d33680d40b325258c0da532d0a884f3/src/librustc_mir/transform/promote_consts.rs#L376-L379

**Comment by oli-obk** [comment]
Fix instructions:

* Add a `IndexVec<BasicBlock, bool>` which, like the `temps` variable, is used to mark blocks whose terminator has been promoted out.
* skip promoting all such terminators when encountering said block id in a `Candidate::Argument` (https://github.com/rust-lang/rust/blob/a3ad012e2d33680d40b325258c0da532d0a884f3/src/librustc_mir/transform/promote_consts.rs#L384)

**Comment by eddyb** [comment]
@oli-obk You can use a `BitVector<BasicBool>`, although I'm not even sure it's necessary.
A promoted call ends up as a `Goto`, so you could just skip it based on that?
