### ISSUE TITLE
[nll] do not compute initialization state for temporaries

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#53243]
Beyond https://github.com/rust-lang/rust/issues/53242, we can probably optimize the computation of initialization state more generally. Right now, we compute initialization state for **all** move-paths, even those that are compiler-generated temporaries. But compiler-generated temporaries should always be (e.g.) initialized before use and I don't *think* we'll ever generate more than one use of them? (i.e., we won't generate move violations)

Still, these computations are used not just for NLL but also for the "dynamic drop lowering" code, so we have to be careful here.

cc @pnkfelix @arielb1

**Comment by arielb1** [comment]
We definitely need to determine the initialization state of temporaries to 

One good way to think about this might be to detect "short-lived variables" that only live for a small number of basic blocks, and treat them specially.

**Comment by nikomatsakis** [comment]
I'm going to close this issue for now. @nnethercote had some good ideas for optimizing the dataflow that seem more promising (representing gen/kill sets using sparse sets) and I'm curious to see what comes of that first.
