### ISSUE TITLE
[nll] do not compute `ever_inits` for *all* state

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#53242]
Currently, we compute the `ever_inits` set for **all move-paths**, but we only ever care about its result for move-paths rooted in **immutable, user-defined locals**. The dataflow computations in general are a very significant part of html5ever and tuple-stress but they show up in other benchmarks too of course. Reducing this cost would be a small but simple win.

The `EverInitializedPaths` set is defined here:

https://github.com/rust-lang/rust/blob/f6d43ed84207c7e58f363f46e5a438ff40f2b311/src/librustc_mir/dataflow/impls/mod.rs#L568

And this is where we allocate the number of bits we need:

https://github.com/rust-lang/rust/blob/f6d43ed84207c7e58f363f46e5a438ff40f2b311/src/librustc_mir/dataflow/impls/mod.rs#L571-L573

As you can see, it is equal to the full set of move-paths. We'd need some sort of map that maps from a `MovePathIndex` to a reduced index, containing only those move-paths that begin with immutable, user-defined local variables.

cc @rust-lang/wg-compiler-nll

**Comment by matthewjasper** [comment]
We also care about mutable user defined variables, for the unused mut lint.

**Comment by nikomatsakis** [comment]
Ah. Too bad. =)

**Comment by nikomatsakis** [comment]
Going to close this for now.
