### ISSUE TITLE
Panic when trying to `use` macro

### ISSUE THREAD

**Issue by jD91mZM2** [rust-lang/rust#53269]
The compiler panicked

I tried this code:  
[compiler-crash tag on rust-nix](https://gitlab.com/jD91mZM2/rust-nix/tree/compiler-crash).
`cargo test`

I expected to see this happen: A normal compilation error  
Instead, this happened: The rust compiler panicked

## Meta

`rustc --version --verbose`:
```
rustc 1.30.0-nightly (7e8ca9f8b 2018-08-03)
binary: rustc
commit-hash: 7e8ca9f8bd8325398e76bc30ac09aab138bbb127
commit-date: 2018-08-03
host: x86_64-unknown-linux-gnu
release: 1.30.0-nightly
LLVM version: 7.0
```
2018 edition of rust

Backtrace: https://gist.github.com/0bf4ae25ef77940633fda40257b16cab

**Comment by jD91mZM2** [comment]
Minimal reproduction example:

```Rust
macro_rules! m {
    () => {}
}

mod m {
    use crate::nonexistent_module::m;

    fn f() {
        m!();
    }
}
```

**Comment by petrochenkov** [comment]
Fixed locally as a part of larger refactoring, will submit a PR soon.
