### ISSUE TITLE
Rustdoc creates wrong links

### ISSUE THREAD

**Issue by emabee** [rust-lang/rust#53277]
Concrete example: in the module description for the module ‚types‘ in my crate hdbconnect, see https://docs.rs/hdbconnect/0.6.0/hdbconnect/ , there are two links to other (root) members of the crate that _work_. When navigating into the module ‚types‘, the same text is shown, but the links are wrong.

**Comment by GuillaumeGomez** [comment]
You used relative paths so it seems logical they're not working when you change "folder". Currently, there is no real solution to this problem in the stable rustdoc. However, intra-links (which are in nightly) allows you to fix it by doing:

```rust
/// [`HdbValue`]
/// [HdbValue]
```

Then rustdoc will generate the link correctly depending what item it's documenting.

**Comment by emabee** [comment]
Great, and thanks, will adapt as soon as it is available!
