### ISSUE TITLE
Docs for Extend don't show all implementors

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/rust#53276]
- https://doc.rust-lang.org/nightly/core/iter/trait.Extend.html

<img width="994" alt="screen shot 2018-08-11 at 4 24 04 pm" src="https://user-images.githubusercontent.com/416575/43995778-0e27ccde-9d83-11e8-97ae-bd3d60b951e6.png">

**Comment by ExpHP** [comment]
You're on the page for the one in `core`.  The one in `std` has more impls:

https://doc.rust-lang.org/nightly/std/iter/trait.Extend.html

Did you reach that page by browsing `std` docs? Maybe there is an errant link to the core docs somewhere.

**Comment by frewsxcv** [comment]
🙃
