### ISSUE TITLE
Changing rustc_codegen_llvm only will not rerun the tests

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#53284]
Running the tests with

> python x.py test --stage=1

changing the rustc_codegen_llvm and running the tests again with

> python x.py test --stage=1

will ignore all the tests that have passed during the first run.

**Comment by cuviper** [comment]
It also seems like changes to `rustc_codegen_llvm` don't trigger the following stages of the compiler itself to rebuild.
