### ISSUE TITLE
Trademark restrictions?

### ISSUE THREAD

**Issue by g4jc** [rust-lang/rust#53287]
Want to fix this bug? There are [instructions below](https://github.com/rust-lang/rust/issues/53287#issuecomment-479520262).

-------------------

This github repository does not contain a trademark file, and I am curious if https://www.rust-lang.org/en-US/legal.html still applies, as it would seem.

> Uses that require explicit approval
> 
>     **Distributing a modified version of the Rust programming language or the Cargo package manager and calling it Rust or Cargo requires explicit, written permission from the Rust core team.** We will usually allow these uses as long as the modifications are (1) relatively small and (2) very clearly communicated to end-users.
> 
>     Selling t-shirts, hats, and other artwork or merchandise requires explicit, written permission from the Rust core team. We will usually allow these uses as long as (1) it is clearly communicated that the merchandise is not in any way an official part of the Rust project and (2) it is clearly communicated whether profits benefit the Rust project.
> 
>     Using the Rust trademarks within another trademark requires written permission from the Rust core team except as described above.

Debian and some other distributions are applying patches against the Rust language and Cargo package. I assume this qualifies as something which requires explicit approval? 

If so, removing or restricting packages from Cargo would also be considered a modification. e.g. some distributions may wish to block access to Cargo downloads that are not in compliance with license standards.

Just wanted to get some clarification on this as it is not mentioned here in the repo and some folks seems to think that because there is no trademark "here" that rust-lang can be distributed with modifications without approval. I believe the only way such modifications would be allowed unrestricted, is if "rust" was not used at all in the package and it was clearly defined as a rebranded fork that is not affiliated with the official package - Otherwise the trademark policy is still enforced.

**Comment by nagisa** [comment]
This question should be asked at the [email address](mailto:trademark@rust-lang.org) linked on the Legal page rather than here.

**Comment by g4jc** [comment]
Just received a response. It seems a TRADEMARK.md may be useful to direct people to the appropriate [information](https://www.rust-lang.org/en-US/legal.html) from github.

> You are correct that we intended the trademark to apply when
> distributing a package or other binary called "Rust" -- and in
> particular that if modifications are made, then we would expect a
> trademark request outlining the sorts of changes being made (as the
> policy notes though, we are inclined to accept such a request).
> 
> 
> regards,
> Niko

This issue can be closed once trademark notification is included or mentioned on README.md.
Thank you.

**Comment by steveklabnik** [comment]
I've tagged this issue as `E-easy` and `E-mentor`. To close this bug, we should add a new section to https://github.com/rust-lang/rust/blob/master/README.md that mentions that there are trademarks on the rust name and logo, and link to https://www.rust-lang.org/policies/media-guide.

If you want to fix this bug and need any help, please let me know, and I'm happy to assist!

**Comment by agnxy** [comment]
Hi @steveklabnik 
I'd like to work on this and opened #59748 to add a section about trademarks. But I'm not sure whether I made appropriate wording. Could you please help to review? Thanks a lot.

**Comment by irelativism** [comment]
Any news regarding this ^
Cheers
