### ISSUE TITLE
Add riscv64imac_unknown_none_elf support

### ISSUE THREAD

**Issue by ingenieroariel** [rust-lang/rust#53308]
https://github.com/rust-lang/rust/pull/52787 added support only for riscv32imac_unknown_none_elf.

I am working on riscv64imac_unknown_none_elf soft cores (running sel4) and would love to be able to use Rust, in particular: https://github.com/PolySync/cargo-fel4

I don't know the domain yet but would love to learn by going through the PR submission process to add that architecture if there are no reasons to exclude it. Are there reasons for not including riscv64imac related to hardware in the wild? 

/cc @japaric

**Comment by rkruppe** [comment]
RV64 support in LLVM is practically nil at this point, so we can't just generate code for it yet.

**Comment by lachlansneff** [comment]
Yeah, the riscv port of nebulet is waiting on support for riscv64 (as well as its various extensions).

**Comment by memoryruins** [comment]
> I'm really excited to see interest in RV64 support in Rust and I'm keen to do what I can to support you in this. The immediate priority is pretty clear - get these patches merged upstream. Beyond that, please keep tagging me in issues that I can help with and of course file bug reports on bugs.llvm.org when appropriate.

https://github.com/rust-embedded/wg/issues/218#issuecomment-433366805

**Comment by tarcieri** [comment]
I'm very much interested in this as well (for use on the HiFive Unleashed)

**Comment by fintelia** [comment]
Have the relevant patches been merged at this point?

**Comment by memoryruins** [comment]
Wow, nearly all the patches have been merged to LLVM by now.
Posted an update in https://github.com/rust-embedded/wg/issues/218#issuecomment-457873256

**Comment by Disasm** [comment]
I hope we can close the issue: `riscv64imac-unknown-none-elf` and `riscv64gc-unknown-none-elf` targets are already in nightly.

**Comment by ingenieroariel** [comment]
Closing, thanks!
