### ISSUE TITLE
Incorrect URL redirection in the doc of `BTreeMap`

### ISSUE THREAD

**Issue by luojia65** [rust-lang/rust#53338]
When I open the [doc for `std::collections::btree_map::BTreeMap`](https://doc.rust-lang.org/std/collections/btree_set/struct.BTreeSet.html), I found a hyperlink referring to `BTreeMap` on the second line, which incorrectly redirect to:
```
https://doc.rust-lang.org/std/collections/btree_set/struct.BTreeMap.html
```
instead of one of the following:
```
https://doc.rust-lang.org/std/collections/btree_map/struct.BTreeMap.html
https://doc.rust-lang.org/std/collections/struct.BTreeMap.html
```
thus caused an HTTP 404 error.

Looking into the [source code](https://github.com/rust-lang/rust/blob/a8763b5370ed044b6e703981217f074e8ddf1e7c/src/liballoc/collections/btree/set.rs#L36), I found out that this hyperlink redirects to `struct.BTreeMap.html`. This could work for the type aliases of `BTreeSet` as `std::collections::BTreeSet`, for the reason that `struct.BTreeSet.html` and `struct.BTreeMap.html` are together in the same path, but does not work for `std::collections::btree_set::BTreeSet` as there isn't a `BTreeMap` in `std::collections::btree_set`.

Additionally, there is also an incorrect redirection on [`std::colletions::hash_set::HashSet`](https://doc.rust-lang.org/std/collections/hash_set/struct.HashSet.html) where there is a hyperlink for struct `HashMap` which does not exist in `std::collections::hash_set`.

The rust version for `doc.rust-lang.org` is `Version 1.28.0 (9634041f0 2018-07-30)`.

**Comment by ollie27** [comment]
This is a duplicate of #32130.

**Comment by luojia65** [comment]
(Closing thia because of duplication)
