### ISSUE TITLE
The msvc targets depend on the msvc linker but `link.exe` was not found

### ISSUE THREAD

**Issue by SerhiiBilyk** [rust-lang/rust#53330]
When I'm trying `rustc main.rs` I receive next error 

`error: linker `link.exe` not found
  |
  = note: The system cannot find the file specified. (os error 2)

note: the msvc targets depend on the msvc linker but `link.exe` was not found

note: please ensure that VS 2013 or VS 2015 was installed with the Visual C++ option

error: aborting due to previous error

error: Could not compile `rust`.`

I have already install MS Build tools C++.
What I'm doing wrong?
Thank you

**Comment by retep998** [comment]
When installing VC++ did you remember to install the Windows SDK component?

**Comment by SerhiiBilyk** [comment]
Probably yes, thank you :)

**Comment by anonymousReaper** [comment]
@SerhiiBilyk were you able to solve the initial issue? How did you get to run the main.rs program could you share the steps here. I've been trying for 3 days now to get this running on a Windows 10 x64. Thanks!

**Comment by xiamuguizhi** [comment]
解决办法：

下载安装 visualcppbuildtools_full.exe

下载链接在这：https://download.microsoft.com/download/5/f/7/5f7acaeb-8363-451f-9425-68a90f98b238/visualcppbuildtoo

**Comment by diesdasnicolas** [comment]
ne
