### ISSUE TITLE
Make the `NonZero*` methods const fn

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#53331]
and undo the const -> fn changes in https://github.com/rust-lang/rust/pull/53315/files#diff-a4a060a3c734b42317d2b9136d68918eL186

This requires changing applicable methods on `NonZero*` from `fn` to `const fn`, adding the `#[rustc_const_unstable="const_nonzero*_methods"]` attribute to all of them and adding some tests ensuring that the methods are not const fn on stable rust.

**Comment by eddyb** [comment]
Doesn't this require panicking in constants?

**Comment by oli-obk** [comment]
Ah I thought there were more trivial methods.

This issue is only acctionable for `get` at the moment

**Comment by MagnumOpus21** [comment]
Hi, I'd like to help out on this. I would appreciate if some one gave me pointers on what needs to be accomplished.

**Comment by oli-obk** [comment]
Steps:

1. add `const` to https://github.com/rust-lang/rust/blob/master/src/libcore/num/mod.rs#L80
2. add the `rustc_const_unstable` attribute
3. add a test in `src/test/ui/const` that shows a const usage of the method (needs the feature gate specified in `rustc_const_unstable`
4. See whether the linked commit above can be partially reverted

**Comment by MagnumOpus21** [comment]
@Cyres I will do that sir. Was busy with my internship.

**Comment by Cyres** [comment]
@MagnumOpus21 If you need help, don't hesitate to ping me here, in Discord (Cyres#8322) or on [StackOverflow](https://stackoverflow.com/users/3131852/tim-diekmann) in the rust chat room.

**Comment by MagnumOpus21** [comment]
Thank you 😄 @Cyres
