### ISSUE TITLE
Write_mir_pretty panics when called on drop glue

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rust#53334]
Its probably here (likely got inlined):
https://github.com/rust-lang/rust/blob/7bbcd005b30582d07f1a39dcf50f77b54e055828/src/librustc_mir/util/pretty.rs#L558-L559

backtrace:

```
[...]
   9: core::panicking::panic
             at libcore/panicking.rs:52
  10: rustc_mir::util::pretty::write_mir_intro
  11: rustc_mir::util::pretty::write_mir_pretty
[...]
```

**Comment by eddyb** [comment]
@bjorn3 Can you set `debuginfo-lines = true` in `config.toml`? That way you should be able to get much better backtraces.

**Comment by Centril** [comment]
@bjorn3 Do you have a reproducer for this?

**Comment by bjorn3** [comment]
This can't be reproduced with `--emit mir`, as that only prints real functions. To reproduce you need to for example modify cg_clif to print mir for every `Instance` seen.

**Comment by eddyb** [comment]
We should be able to add `-Z dump-mir` support for shims, if we don't have it already.
