### ISSUE TITLE
Setting MIRI_BACKTRACE should not affect CTFE

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#53355]
MIRI_BACKTRACE should configure miri, but should not have an effect on CTFE that's part of normal rustc operation.

Cc @oli-obk

**Comment by oli-obk** [comment]
That seems very hard to differentiate. And I sometimes did actually need the `MIRI_BACKTRACE` for figuring out problems in CTFE.

Since you probably just don't want all the noise from CTFE while running miri, you can `std::env::set_var` the variable automatically in miri, this will happen after the compilation is done, so you'll only see miri backtraces.

**Comment by oli-obk** [comment]
the backtrace is generated in the `From` impl of `EvalError`. There's no `Machine` available and it would be very painful to thread it through.

https://github.com/rust-lang/rust/blob/81cfaad030435aae447d73c66123b3df856c09cb/src/librustc/mir/interpret/error.rs#L124-L126

**Comment by RalfJung** [comment]
Oh, dang...

> you can std::env::set_var the variable automatically in miri, this will happen after the compilation is done, so you'll only see miri backtraces.

So what would the UI be? We change librustc to look for CTFE_BACKTRACE, and then miri wil check for MIRI_BACKTRACE and set CTFE_BACKTRACE before execution starts?

**Comment by oli-obk** [comment]
yea, that seems a good solution.

**Comment by RalfJung** [comment]
We also need to fix the way backtraces are printed... they should not be printed immediately when the error is converted, but only later when the error is shown to the user. We do still create errors that we never act on, and finding the right backtrace is pretty hard ATM.

**Comment by oli-obk** [comment]
We used to do that. I changed it to the current system when I got rid of the old CTFE error enum. we can probably add an optional field to the EvalError type which stores the backtrace as long as it's not compared, hashed,. .. or interacts with any traits implemented for the type

**Comment by RalfJung** [comment]
Okay... yeah I think we have to change it. Right now, for my debugging, MIRI_BACKTRACE is useless; all it does is produce several thousand lines of backtraces.

**Comment by RalfJung** [comment]
I think I'd like the same for `RUST_LOG`... something that makes miri set that variable once compilation is done.

Of course, in a query-based compiler, I don't even know what that means...

**Comment by RalfJung** [comment]
I am working on that (PR is blocked by https://github.com/rust-lang/rust/pull/53821#issuecomment-423092605)
