### ISSUE TITLE
Migrate remaining compile-fail tests to ui

### ISSUE THREAD

**Issue by davidtwco** [rust-lang/rust#53353]
As part of #53196, `compile-fail` tests were migrated to `ui` tests. As part of this PR, some tests remained as `compile-fail` tests - due to an unresolvable issue (at the time) with the test that meant delaying migration meant more sense than holding up the PR (which needed rebased _a lot_). The main issues exhibited were:

- Extra lines of output on some platforms - there is currently no way to normalize a whole line out of the output, therefore tests that had extra lines on some platforms had to say as `compile-fail` tests.
  - This is the case with most of the tests updated in the later commits of #53196 that mention specific platforms.
- Non-deterministic ordering of error messages.

**Comment by estebank** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/65440

**Comment by wesleywiser** [comment]
This was completed in #80453.
