### ISSUE TITLE
rustdoc: blanket impl does not work for re-exported items

### ISSUE THREAD

**Issue by ehuss** [rust-lang/rust#53374]
The new "blanket implementations" does not seem to work if an item is re-exported in a different location.  For example:

```rust
pub struct S2 {}
mod m {
    pub struct S {}
}
pub use m::*;
```

`S2` shows the blanket implementations, but `S` does not.

Tested with rustc 1.30.0-nightly (d5a448b3f 2018-08-13).

cc @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
Wrote the fix. I add some tests then I open the PR.
