### ISSUE TITLE
Errors returned by MetadataLoader are silently discarded

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rust#53381]

**Comment by oli-obk** [comment]
Do you have some more info? Is this something users experience? Or is it mostly custom drivers running into problems?

**Comment by bjorn3** [comment]
When implementing `rustc::middle::cstore::MetadataLoader` myself I accidentally tried to parse a different file type. This returned an error from `get_rlib_metadata`, but the error was never printed to the user, instead it said ``error[E0463]: can't find crate for `...` ``.

**Comment by bjorn3** [comment]
> Is this something users experience?

It's possible if an rlib/dylib gets corrupt, because then it won't say the file is corrupt.

> Or is it mostly custom drivers running into problems?

Yes
