### ISSUE TITLE
existential types cannot be defined in terms of themselves at all

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#53398]
I assumed that the following code would be legal, as it does not require indefinitely sized types, but apparently somewhere the existential type is revealed too early:

```rust
#![feature(existential_type)]

existential type Foo: Fn() -> Foo;

fn foo() -> Foo {
    foo
}

fn main() {
}
```

([Playground](https://play.rust-lang.org/?gist=5f1d47f0078f56a599979fec40f2d508&version=nightly&mode=debug&edition=2015))

Errors:

```
   Compiling playground v0.0.1 (file:///playground)
error[E0271]: type mismatch resolving `<fn() -> Foo {foo} as std::ops::FnOnce<()>>::Output == fn() -> Foo {foo}`
 --> src/main.rs:3:1
  |
3 | existential type Foo: Fn() -> Foo;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected anonymized type, found fn item
  |
  = note: expected type `Foo`
             found type `fn() -> Foo {foo}`
  = note: the return type of a function must have a statically known size

error: aborting due to previous error

For more information about this error, try `rustc --explain E0271`.
error: Could not compile `playground`.

To learn more, run the command again with --verbose.

```

**Comment by Aaron1011** [comment]
Updated version:

```rust
#![feature(type_alias_impl_trait)]

type Foo = impl Fn() -> Foo;

fn foo() -> Foo {
    foo
}

fn main() {
}
```

This still doesn't compile.

**Comment by nikomatsakis** [comment]
Using min-type-alias-impl-trait ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=bcb63c9ce529e5186506f2f06fef587e)), you get an error. 

I think this is ok, though, as it is we don't support cyclic types like this. 

I'm going to mark this as E-needs-test.

**Comment by nikomatsakis** [comment]
If we adopted a different model of impl trait, one where they were more "nominal" and hence could be cyclic, that'd be a different thing.
