### ISSUE TITLE
Shouldn't Child::wait_with_output wait first, and collect output later?

### ISSUE THREAD

**Issue by pzmarzly** [rust-lang/rust#53402]
[Child::wait_with_output](https://github.com/rust-lang/rust/blob/1.28.0/src/libstd/process.rs#L1278)

```rust
    /// Simultaneously waits for the child to exit and collect all remaining
    /// output on the stdout/stderr handles, returning an `Output`
    /// instance.
    ///
    /// The stdin handle to the child process, if any, will be closed
    /// before waiting.
```

```rust
        drop(self.stdin.take());
        match (self.stdout.take(), self.stderr.take()) {
            // ...
            (Some(out), Some(err)) => {
                let res = read2(out.inner, &mut stdout, err.inner, &mut stderr);
                res.unwrap();
            }
        }
        let status = self.wait()?;
```

Right now it closes stdin, collects output and then starts to wait for the process to finish, ignoring its output. This doesn't look like intended behavior.

**Comment by oconnor663** [comment]
You might need to clarify what you mean by "ignoring its output". The `read2` function there reads each pipe until its closed, so there can't be any more output after it returns.

**Comment by pzmarzly** [comment]
Okay, the function indeed works as expected. I didn't connect the fact that after EOF nothing can be written to the pipe, and thought that `read2` would return during a "pause" in data stream (e.g. if child `println!("Shutting down..."); sleep_ms(500);println!("Some important data")`).
