### ISSUE TITLE
Using `Self::EnumVariant` fails

### ISSUE THREAD

**Issue by varkor** [rust-lang/rust#53414]
```rust
enum Enum {
    Variant,
}

impl Enum {
    fn choose() -> Self {
        Self::Variant //~ ERROR no variant named `Variant` found for type `Enum` in the current scope
    }
}
```
I'm not sure if this is supposed to be allowed or not, but the error message is incorrect. Is there an up-to-date document describing all the places `Self` is allowed instead of a type name?

**Comment by Havvy** [comment]
This is #49683

**Comment by varkor** [comment]
Thanks, I tried searching but managed to overlook this!
