### ISSUE TITLE
Hidden items in external crate are made public when inline glob re-exported 

### ISSUE THREAD

**Issue by SergioBenitez** [rust-lang/rust#53417]
Consider a crate `parent` with the following items:

```rust
mod module;

#[doc(hidden)]
pub use module::Hidden;
pub use module::Visible;
```

where `module.rs` contains:

```rust
pub enum Hidden {  }
pub enum Visible {  }
```

Now consider a crate `foo` that inline, glob-exports `parent` in a module `par`:

```rust
extern crate parent;

pub mod par {
    #[doc(inline)]
    pub use parent::*;
}
```

The item `Hidden` is rendered in the rustdocs for `foo::par` when it shouldn't be.

To work around this issue, `#[doc(hidden)]` can be applied to the `Hidden` item in `module.rs`:

```rust
#[doc(hidden)]
pub enum Hidden {  }
pub enum Visible {  }
```

This workaround only works when `#[doc(hidden)]` is applied to the _source definition_.

cc @QuietMisdreavus

**Comment by QuietMisdreavus** [comment]
I just used this sample with the latest nightly (`rustdoc 1.30.0-nightly (20dc0c507 2018-09-19)`) and it didn't seem to show the `Hidden` struct? Can you confirm that this is still an issue?

**Comment by SergioBenitez** [comment]
This is still an issue. I've updated the issue with a complete, working example, as well as a workaround the points to the root of the issue (`#[doc(hidden)]` being ignored on the re-export in `parent`).

**Comment by SergioBenitez** [comment]
As a matter of update: this is unfortunately still an issue. As a result, Rocket's docs for its [`http`](https://api.rocket.rs/v0.4/rocket/http/index.html) module leak hidden types.

**Comment by GuillaumeGomez** [comment]
Should be fixed by https://github.com/rust-lang/rust/pull/109697.
