### ISSUE TITLE
Testing polling for rfcbot

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#53421]
Using this issue to try out rfcbot :)

**Comment by Centril** [comment]
foobar baz

@rfcbot poll lang Isn't this nice?

baz bar

**Comment by Centril** [comment]
Let's try this again...

@rfcbot poll lang Isn't this nice?

lorem ipsum

**Comment by Centril** [comment]
Note to self:
+ [ ] rfcbot should accept a command even tho the issue has no T- labels.
   + [ ] this only applies if a specific team is directly asked.
   + [ ] the one who starts the poll doesn't need to be on that team, but has to be on *some* team.
+ [ ] rfcbot should poll every team labeled on the issue if no specific team is mentioned.
+ [ ] rfcbot should backlink to the comment where the poll was started.
+ [ ] Consider wording of "Team member.." when poll starter is asking a different team.

**Comment by varkor** [comment]
How about:
```
@Centril (T-lang) has asked T-compiler, T-dev-tools, and T-lang for consensus on [topic]:

> Quote
```
in general and:
```
@Centril has asked T-lang for consensus on [topic]:

> Quote
```
when it's the same team.

**Comment by Centril** [comment]
@varkor  Neat; I'm using that :)

@ishitatsuyuki That depends on the one running the poll and the folks answering. If a team member sees the poll and disagrees, it would be good if they said why (like in a comment) ;) But there's no way with `@rfcbot poll` to explicitly disagree.

**Comment by ishitatsuyuki** [comment]
I have another question: how do you plan to use the vote results? AFAIK majority rule doesn't always apply in this community; here's a related discussion that discuss the usefulness of reactions: https://internals.rust-lang.org/t/up-votes-instead-of-down-votes-on-rfcs/6309

If it's not about the numbers, how would you going to use this feature? I guess tagging the whole team is useful as it can be used as a summary of people commented.

**Comment by Centril** [comment]
@ishitatsuyuki  this command is meant for inter-team communication and for team members to ask questions and build consensus but not as a substitute for FCPs. Don't see these as votes or as changing the RFC process. :)

See https://github.com/anp/rfcbot-rs/issues/214 for why this command came about.

**Comment by Centril** [comment]
@rfcbot poll compiler Lorem ipsum?
