### ISSUE TITLE
non-defining existential type use in defining scope with empty lifetime name

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/rust#53457]
Really not sure where the error here is coming from, as far as I can tell there should only be a single relevant lifetime, `'a`. The same function written as a free function generic over a `Write` returning `impl Future<...> + 'a` works fine (included in the playground). I'll try and come up with a reduced example in the next couple of days [(playground)](https://play.rust-lang.org/?gist=5bb231c73d550274e62c986c79f9df77&version=nightly&mode=debug&edition=2015)

```text
error: non-defining existential type use in defining scope
  --> src/lib.rs:19:5
   |
19 | /     {
20 | |         poll_fn(move |cx| self.reborrow().poll_close(cx))
21 | |     }
   | |_____^ lifetime `` is part of concrete type but not used in parameter list of existential type
```

```rust
#![feature(arbitrary_self_types, existential_type, pin, futures_api)]

use std::future::Future;
use std::marker::Unpin;
use std::mem::PinMut;
use std::task::{self, Poll};

pub trait Write {
    type Error;

    fn poll_close(self: PinMut<Self>, cx: &mut task::Context) -> Poll<Result<(), Self::Error>>;
}

existential type Close<'a, W: Write>: Future<Output = Result<(), W::Error>> + 'a;

trait WriteExt: Write {
    fn close<'a>(self: PinMut<'a, Self>) -> Close<'a, Self>
    where
        Self: Sized,
    {
        poll_fn(move |cx| self.reborrow().poll_close(cx))
    }
}

// ------------
// from futures-util-preview 0.3

pub struct PollFn<F> {
    f: F,
}

impl<F> Unpin for PollFn<F> {}

pub fn poll_fn<T, F>(f: F) -> PollFn<F>
where
    F: FnMut(&mut task::Context) -> Poll<T>,
{
    PollFn { f }
}

impl<T, F> Future for PollFn<F>
where
    F: FnMut(&mut task::Context) -> Poll<T>,
{
    type Output = T;

    fn poll(mut self: PinMut<Self>, cx: &mut task::Context) -> Poll<T> {
        (&mut self.f)(cx)
    }
}
```

(CC @oli-obk in case you have any hints on where to look)

**Comment by Nemo157** [comment]
Minimized example ([playground](https://play.rust-lang.org/?gist=0d056f4ae21a7bc25df74fc122842254&version=nightly&mode=debug&edition=2015))

```rust
#![feature(existential_type)]

trait Future {
    fn poll(&self, cx: &mut ());
}

trait Write {
    fn poll_close(&self, cx: &mut ());
}

existential type Close<'a, W: Write>: Future + 'a;

fn broken<'a, W: Write>(w: &'a W) -> Close<'a, W> {
    PollFn(move |cx| w.poll_close(cx))
}

fn working<'a, W: Write>(w: &'a W) -> impl Future + 'a {
    PollFn(move |cx| w.poll_close(cx))
}

pub struct PollFn<F: Fn(&mut ())>(F);

impl<F> Future for PollFn<F> where F: Fn(&mut ()) {
    fn poll(&self, cx: &mut ()) {
        (&self.0)(cx)
    }
}
```

```
error: non-defining existential type use in defining scope
  --> src/lib.rs:13:51
   |
13 |   fn broken<'a, W: Write>(w: &'a W) -> Close<'a, W> {
   |  ___________________________________________________^
14 | |     PollFn(move |cx| w.poll_close(cx))
15 | | }
   | |_^ lifetime `` is part of concrete type but not used in parameter list of existential type
```

Removing the `cx` parameter everywhere makes this work, at a guess it seems like existential types are incorrectly attributing the lifetime of the `&mut ()` that should be hidden in the closure to the concrete type.

**Comment by oli-obk** [comment]
This might be because existential types skip (https://github.com/rust-lang/rust/blob/6bf6d50a6ff7685b4aa09172d9d09f03f250da9d/src/librustc/middle/resolve_lifetime.rs#L637) the lifetime hacks (https://github.com/rust-lang/rust/blob/6bf6d50a6ff7685b4aa09172d9d09f03f250da9d/src/librustc/middle/resolve_lifetime.rs#L656) that `impl Trait` does

**Comment by talchas** [comment]
Even more minified:

```rust
existential type X: Clone;

fn bar<F: Fn(&i32) + Clone>(f: F) -> F {
    f
}

fn foo() -> X {
    bar(|x| ())
}
```

or using more stdlib stuff:

```rust
existential type X: Iterator<Item = i32>;

fn temp() -> X {
    vec![1].into_iter().filter(|x| *x > 1)
}
```

**Comment by ExpHP** [comment]
Also seen in `const`/`static` items of type `impl Fn(&T)`: #55272

**Comment by MSleepyPanda** [comment]
I've hit this as well, have reduced it further:
```rust
#![feature(existential_type)]

existential type Foo<R>: Fn(&R) -> ();

fn bar<R>() -> Foo<R> {
    |r| ()
}

```

[Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=20766e09527a463207cc5d1e7805336b)

Changing from `Fn(&R) -> ()` to `Fn(R) -> ()` works

**Comment by Lymia** [comment]
Has there been progress in fixing this? I'd be willing to see if I can start work on a PR myself since I've been having issues with this.

**Comment by oli-obk** [comment]
I think it should be enough to add a `ReLateBound(_)` arm to https://github.com/rust-lang/rust/blob/0576ac109b1ee40cc3201ac3c9ed58339487140e/src/librustc_typeck/check/writeback.rs#L508

**Comment by oberien** [comment]
This seems to have been fixed recently, as the example in https://github.com/rust-lang/rust/issues/53457#issuecomment-455091820 didn't work on nightly 2019-04-11, but now works on the playpen (if you click the link in that comment).

**Comment by oli-obk** [comment]
The fix was in https://github.com/rust-lang/rust/pull/60799
