### ISSUE TITLE
Issues with crt2.o and dllcrt2.o from mingw.

### ISSUE THREAD

**Issue by crlf0710** [rust-lang/rust#53454]
Those crt2.o and dllcrt2.o files have to match the gcc.exe used. So for example when i use win-gnu target in a msvc toolchain, I'll install my own copy of MINGW, and it should provide gcc.exe and those .o files, and i shouldn't use the rust-provided one.

So I suggest:
1. We package these files in "rust-mingw" component instead of current "rust-std" component in win-gnu builds.
2. Make people able to use an environment variable or something to specify where to pick these .o files in the linker command.

**Comment by Amanieu** [comment]
Could we always use the crt2.o from the host toolchain? We can get the path by invoking `i686-w64-mingw32-gcc -print-file-name=crt2.o`

**Comment by mati865** [comment]
That was my idea about solving it but couldn't manage to make simple fix.
Probably the best way here would be calling `cc` once to get the path and cache it. Since it will be the C toolchain lib dir possibility of finding conflicting Rust libs should be zero.

**Comment by cup** [comment]
https://github.com/rust-lang/rust/issues/47048
https://github.com/rust-lang/rust/issues/49078

https://github.com/rust-lang/rust/issues/53454
https://github.com/rust-lang/rust/issues/59604
https://github.com/rust-lang/rust/issues/60912
https://github.com/rust-lang/rust/issues/67483
https://github.com/rust-lang/rust/pull/67429
