### ISSUE TITLE
Expose libproc_macro in rust-src component

### ISSUE THREAD

**Issue by kngwyu** [rust-lang/rust#53463]
To use it for [racer](https://github.com/racer-rust/racer) completion.
cc @nrc

**Comment by nrc** [comment]
@rust-lang/infra IS there a downside to doing this?

**Comment by kennytm** [comment]
No problem for me.

**Comment by Mark-Simulacrum** [comment]
Slightly increased file sizes, but presumably not that big a problem.

**Comment by aidanhs** [comment]
Discussed this in an infra team meeting, we don't see any issues.
