### ISSUE TITLE
Add support for the Visual Studio Express 2017 linker

### ISSUE THREAD

**Issue by lucatrv** [rust-lang/rust#53474]
Support for the Visual Studio 2017 linker was added with PR #38584, and I guess that `rustc` now works either with the Community or the Professional or the Enterprise releases (see comparison [here](https://visualstudio.microsoft.com/vs/compare/)). However that PR does not cover [Visual Studio Express 2017](https://visualstudio.microsoft.com/vs/express/), whose linker is located at `c:\Program Files (x86)\Microsoft Visual Studio\2017\WDExpress\VC\Tools\MSVC\14.12.25827\bin\Hostx86\x64\link.exe`.

In order for `rustc` to find the Visual Studio Express 2017 linker I need to run `c:\Program Files (x86)\Microsoft Visual Studio\2017\WDExpress\VC\Auxiliary\Build\vcvarsx86_amd64.bat`.

I'm on Windows 7, running `rustc` version 1.28.0 (stable).

**Comment by lucatrv** [comment]
1. I confirm that `C:\Program Files (x86)\Microsoft Visual Studio\2017\WDExpress\VC\Auxiliary\Build\Microsoft.VCToolsVersion.default.txt` exists.
2. With Visual Studio Express 2017 there's no choice, Windows SDK is always installed.
3. I can build binaries with Rust after running `vcvarsx86_amd64.bat`.

If I do not mistake, "regular" Visual Studio releases are installed in `C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\`, while Visual Studio Express is installed in `C:\Program Files (x86)\Microsoft Visual Studio\2017\WDExpress\`, does Rust look both within `Enterprise` and `WDExpress` folders?

**Comment by retep998** [comment]
My Visual Studio is installed in `C:\Program Files (x86)\Microsoft Visual Studio\2017\Community`. `Enterprise` is only for the Enterprise version of VS. Again, there is **nothing** in the code that is specific to `Enterprise` or `Community` or `WDExpress`. The code simply uses a COM api provided by Microsoft to ask where VS is installed, and then looks for `VC\Auxiliary\Build\Microsoft.VCToolsVersion.default.txt` inside that installation to find the latest VC++ toolchain.

What are the contents of `C:\Program Files (x86)\Microsoft Visual Studio\2017\WDExpress\VC\Auxiliary\Build\Microsoft.VCToolsVersion.default.txt`? Inside the directory `C:\Program Files (x86)\Microsoft Visual Studio\2017\WDExpress\VC` could you run either `tree /F` in cmd or `Get-ChildItem -Recurse` in powershell and upload the output?

**Comment by lucatrv** [comment]
Thanks for the explanation.

The content of `C:\Program Files (x86)\Microsoft Visual Studio\2017\WDExpress\VC\Auxiliary\Build\Microsoft.VCToolsVersion.default.txt` is:

> 14.12.25827

Here is the output of `Get-ChildItem -Recurse`: [Get-ChildItem-Recurse.txt](https://github.com/rust-lang/rust/files/2308358/Get-ChildItem-Recurse.txt)

**Comment by retep998** [comment]
Are you on 32-bit Windows or 64-bit Windows? It appears you *only* have `Hostx86` toolchains. If you're on 32-bit Windows, that's fine, but if you're on 64-bit Windows (which seems likely given the existence of `C:\Program Files (x86)`) then Rust is trying to look for the `Hostx64` toolchains and failing. Please let me know as there may need to be a fallback implemented.

**Comment by lucatrv** [comment]
Yes I am on Windows 7 64-bit. I do not see any options in the VS Express 2017 installer to choose the x86 or x64 toolchains, moreover on the [VS Express website](https://visualstudio.microsoft.com/vs/express/) I read:

> Develop for WPF, WinForms, ASP.NET, Universal Windows Platform, Win32, Android, iOS, and many more platforms all from one IDE with everything you need

so I guess VS Express 2017 is limited to Win32.

**Comment by MichaelMcDonnell** [comment]
@lucatrv do you still need Visual Studio Express 2017 support? Visual Studio 2019 and 2022 have both been available for a long time.

**Comment by lucatrv** [comment]
@MichaelMcDonnell currently I am using Visual Studio Build Tools 2022, I agree that nowadays support for Visual Studio Express 2017 is not needed anymore, so I'm closing this issue.

**Comment by MichaelMcDonnell** [comment]
Great! Thanks @lucatrv!

**Comment by dofuuz** [comment]
Actually, VS Express is the only free option for enterprise in Windows platform. (Unless MinGW toolchain used)

MS [allowed VS Build tools in enterprise, but it's usage is limited](https://devblogs.microsoft.com/cppblog/updates-to-visual-studio-build-tools-license-for-c-and-cpp-open-source-projects/). So, enterprise should purchase license in order to develop with Rust.

This is how Python packaging system detects VS 2017 Express: https://github.com/pypa/setuptools/pull/2663
I hope this might help, and someone fix this issue. I am not familiar with Rust, so I cannot fix this issue by myself :(
