### ISSUE TITLE
error[E0428]: the name `_` is defined multiple times | using 2018 edition and uniform paths

### ISSUE THREAD

**Issue by sbstp** [rust-lang/rust#53484]
This error comes from an example file that uses the library I'm working on. The library itself compiles fine, the example does not. Full error:
 ```
error[E0428]: the name `_` is defined multiple times
  |
  = note: `_` must be defined only once in the type namespace of this module

error: aborting due to previous error

For more information about this error, try `rustc --explain E0428`.
error: Could not compile `tinyhttp`.
```
The bug only occurs when I use a relative `pub use`.
```rust
// src/lib.rs
pub use crate::error::{HttpError, HttpResult}; // OK
pub use crate::request::parse::ResponseReader; // OK
pub use error::{HttpError, HttpResult}; // BREAKS
pub use request::parse::ResponseReader; // BREAKS
```
Using `rustc 1.30.0-nightly (b2028828d 2018-08-16)` on Debian sid amd64

The full project source can be found [here](https://github.com/sbstp/tinyhttp/tree/2b888a255b330d74addb871757b3c8c7c7a25df8). The error occurs in `examples/cat.rs`.

**Comment by eddyb** [comment]
cc @petrochenkov I didn't realize this would happen, but we lose the `gensym` cross-crate (we should really avoid doing that, but that seems hard) - probably just need to avoid leaving the canaries in any sort of export maps, for now.

**Comment by petrochenkov** [comment]
>avoid leaving the canaries in any sort of export maps, for now

Yes, looks like a good short-term solution.
