### ISSUE TITLE
#[cfg(...)] ignores namespace

### ISSUE THREAD

**Issue by kennytm** [rust-lang/rust#53489]
Repro:

```rust
fn main() {
    println!("           cfg(a) = {}", cfg!(a));
    println!("cfg(something::a) = {}", cfg!(something::a));
}
```

```console
$ rustc --cfg 'a' 1.rs && ./1
           cfg(a) = true
cfg(something::a) = true

$ rustc --cfg 'something::a' 1.rs && ./1
           cfg(a) = true
cfg(something::a) = true

$ rustc --cfg 'what::a' 1.rs && ./1
           cfg(a) = true
cfg(something::a) = true
```

while I expected these should print `true/false`, `false/true` and `false/false` instead.

(Note: this also affects `--print cfg` which `something::a` is collapsed to `a`)

cc @petrochenkov @eddyb 

---

```
$ rustc -vV
rustc 1.30.0-nightly (33b923fd4 2018-08-18)
binary: rustc
commit-hash: 33b923fd44c5c5925e635815fce68bdf1f98740f
commit-date: 2018-08-18
host: x86_64-apple-darwin
release: 1.30.0-nightly
LLVM version: 7.0
```

**Comment by eddyb** [comment]
What happens if you also have `cfg(a)`, does that interact with `cfg(something::a)`?

**Comment by kennytm** [comment]
@eddyb Oh no, `cfg(something::a)` is the same as `cfg(a)`. Edited the issue.

**Comment by kennytm** [comment]
This behavior exists since 1.27. On 1.26 or before, `#[cfg(module::path)]` is simply a syntax error.

**Comment by petrochenkov** [comment]
This looks like an unintended side-effect of https://github.com/rust-lang/rust/pull/50030 that allowed arbitrary paths in meta-items (including nested ones), but `fn name()` for meta-items still returns the last segment ignoring everything else.
cc @flip1995 @topecongiro 

Most of attributes, including `cfg` want nested meta-item paths to be single-segment.
So, looks like `fn name` should return `Option<Name>` and all its callers need to be taught to deal with `None` somehow - report an error, or pass it further, etc.

**Comment by eddyb** [comment]
I'd suggest having a flag on "meta-item parsing" to say whether it should allow paths at all - most of the builtin attributes don't need paths.

**Comment by petrochenkov** [comment]
The `cfg` issue specifically was fixed in https://github.com/rust-lang/rust/pull/53893.
