### ISSUE TITLE
The nightly documentation does not display "impl"

### ISSUE THREAD

**Issue by denisandroid** [rust-lang/rust#53494]
When generating the documentation, I noticed that the functions with `impl` are displayed empty as a result. But in a stable version of the compiler everything is fine.
При создании документации я заметил, что функции с `impl` в результате отображаются пустым. Но в стабильной версии компилятора все в порядке.
## Compiler:
`rustc 1.30.0-nightly (33b923fd4 2018-08-18)` - nightly <--- Not displayed
`rustc 1.28.0 (9634041f0 2018-07-30)` - stable <--- OK

## Nightly:

![1](https://user-images.githubusercontent.com/13841983/44309479-08257e00-a3d0-11e8-99e7-69724df6af27.png)

## Stable:

![2](https://user-images.githubusercontent.com/13841983/44309483-11aee600-a3d0-11e8-8cad-6f69274a1c19.png)

**Comment by ehuss** [comment]
I think this is the same as #52376.

**Comment by GuillaumeGomez** [comment]
Fixed in #53541.
