### ISSUE TITLE
Tracking issue for RFC 2306, "Add core::convert::identity"

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#53500]
This is a tracking issue for the RFC "Add `fn identity<T>(x: T) -> T { x }` to `core::convert`" (rust-lang/rfcs#2306).

**Steps:**

- [x] Implement the RFC: https://github.com/rust-lang/rust/pull/47562
- [x] Stabilization PR: https://github.com/rust-lang/rust/pull/57322

[stabilization-guide]: https://forge.rust-lang.org/stabilization-guide.html
[doc-guide]: https://forge.rust-lang.org/stabilization-guide.html#updating-documentation

**Unresolved questions:**

None.

**Comment by shepmaster** [comment]
The documentation suggests:
```rust
#![feature(convert_id)]
use std::convert::identity;

let iter = vec![Some(1), None, Some(3)].into_iter();
let filtered = iter.filter_map(identity).collect::<Vec<_>>();
assert_eq!(vec![1, 3], filtered);
```

I'd argue this is actively non-idiomatic Rust. It is better to use `flatten`

```rust
let iter = vec![Some(1), None, Some(3)].into_iter();
let filtered = iter.flatten().collect::<Vec<_>>();
assert_eq!(vec![1, 3], filtered);
```

I'm bringing this up here because if we can't have good examples, perhaps the feature doesn't carry it's own weight.

**Comment by shepmaster** [comment]
The documentation suggests using `identity` to "do nothing among other interesting functions" and "that changes nothing in a conditional" (which are really the same example). I think this is very weak motivation because it cannot be used with a function of different arity:

```rust
#![feature(convert_id)]
use std::convert::identity;

fn manipulation(x: u32, y: u32) -> u32 {
    x + y
}

fn main() {
    let do_stuff = if true { manipulation } else { identity };
    let _results = do_stuff(1, 2);
}
```

```
error[E0308]: if and else have incompatible types
 --> src/main.rs:9:20
  |
9 |     let do_stuff = if true { manipulation } else { identity };
  |                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ incorrect number of function parameters
  |
  = note: expected type `fn(u32, u32) -> u32 {manipulation}`
             found type `fn(_) -> _ {std::convert::identity::<_>}`
```

**Comment by Centril** [comment]
@SimonSapin How do you feel about stabilizing this?

**Comment by SimonSapin** [comment]
Let’s.

@rfcbot fcp merge
