### ISSUE TITLE
Wrong result after short circuit in const_let

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust#53515]
I would expect this program to print `true`. As of rustc 1.30.0-nightly (33b923fd4 2018-08-18) it prints `false`. If you change `const fn` to `fn` then it prints `true` as expected.

```rust
#![feature(const_fn, const_let)]

const fn id(condition: bool) -> bool {
    let mut ret = true;

    // If condition is true, we short circuit and ret remains true.
    // If condition is false, we assign ret = false.
    let _ = condition || { ret = false; true };

    ret
}

fn main() {
    println!("{}", id(true));
}
```

Mentioning @oli-obk.
Mentioning const_let tracking issue https://github.com/rust-lang/rust/issues/48821.

**Comment by oli-obk** [comment]
Uh.... Apparently short circuiting operators don't exist in consts:

https://github.com/rust-lang/rust/blob/d2048b6db375299b681d4f4728b8e7cad9f74d5f/src/librustc_mir/hair/cx/expr.rs#L328-L358

cc @eddyb 

Since we did not have a way to observe short circuiting before the `const_let` feature, this transformation was correct.

Note that const fn is unnecessary:

```rust
#![feature(const_let)]

const COND: bool = true;

const X: bool = {
    let mut ret = true;

    // If COND is true, we short circuit and ret remains true.
    // If COND is false, we assign ret = false.
    let _ = COND || { ret = false; true };

    ret
};

fn main() {
    println!("{}", X);
}
```

**Comment by RalfJung** [comment]
So where is the tracking issue to allow `if` in `const` so that we can get rid of this hack?

`if` seems like a fairly innocent feature.

**Comment by oli-obk** [comment]
`if` is very innocent if you ignore associated constant bodies and using associated constants in generic functions (where the associated constant is taken from a generic parameter).

@eddyb can we just mark any MIR containing `SwitchInt` to be `NOT_PROMOTABLE`, `NEEDS_DROP` and `MUTABLE_INTERIOR` (https://github.com/rust-lang/rust/blob/master/src/librustc_mir/transform/qualify_consts.rs#L51) even if they aren't? And then later loosen the constraints?

**Comment by RalfJung** [comment]
> if is very innocent if you ignore associated constant bodies and using associated constants in generic functions (where the associated constant is taken from a generic parameter).

What is the problem there?

**Comment by oli-obk** [comment]
We need to check whether

```rust
if T::FOO {
    Some(Cell::new(42))
} else {
    None
}
```

results in a `Freeze` value or not. While this example is fairly easy, once you get local variables and mutable state it gets very messy and needs a proper dataflow analysis.

Since `(Some(Cell::new(42)), None).1` currently counts as "contains interior mutability", imo we can just say that `if true { None } else { Some(Cell::new(42)) }` also does

**Comment by RalfJung** [comment]
Oh, we are already more precise than the type is?

**Comment by RalfJung** [comment]
I think the place that has the best information about this kind of stuff is the sanity check. So if we make that part of the query for constants, it could probably do this.

**Comment by Centril** [comment]
This no longer compiles on nightly:
```rust
error[E0019]: constant function contains unimplemented expression type
 --> src/main.rs:8:13
  |
8 |     let _ = condition || { ret = false; true };
  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error
```

**Comment by RalfJung** [comment]
So I think this can be closed because there's no longer an incorrect result. See https://github.com/rust-lang/rust/issues/49146 for the tracking issue for control flow in `const fn` (that includes short-circuiting).
