### ISSUE TITLE
Unify E0243, E0244 and E0107

### ISSUE THREAD

**Issue by varkor** [rust-lang/rust#53525]
[E0243](https://doc.rust-lang.org/error-index.html#E0243) and [E0244](https://doc.rust-lang.org/error-index.html#E0244) are both errors about providing the wrong number of generic arguments. Having both is unnecessary: it'd be better if they were unified with [E0107](https://doc.rust-lang.org/error-index.html#E0107) — the analogous error for lifetimes.

`GenericArgMismatchErrorCode` can go once this is done.

**Comment by iancormac84** [comment]
Minor nit: The link for E0107 actually points to E0243.

**Comment by varkor** [comment]
Fixed, thanks!

**Comment by mcr431** [comment]
Can I take this? Would be my first contribution so might take me a few days.

**Comment by varkor** [comment]
@mcr431: absolutely! The diagnostics are in `src/librustc_typeck/diagnostics.rs`. You'll want to add: `#### Note: this error code is no longer emitted by the compiler.` for E0243 and E0244 and change the text for E0107 to refer to all generic arguments (you can probably merge the examples from E0243 and E0244 into its examples).

You can then remove `GenericArgMismatchErrorCode` here:
https://github.com/rust-lang/rust/blob/ee9bd0fd99ef5049f53b5d8233369187637cb71c/src/librustc_typeck/astconv.rs#L102-L106
and just use `E0107` instead (you might need to do a little cleaning up in `check_generic_arg_count`). Then you can run all the ui tests with `--bless` to update them to the new error codes (`./x.py test src/test/ui -i --stage 1 --bless`). That should be it!

If you have any questions, feel free to ask here or on [Discord](http://discord.gg/rust-lang) / #rustc. Once you're done, put `r? @varkor` in the pull request and I'll review it. Thanks!

**Comment by mcr431** [comment]
@varkor Awesome, thanks!

**Comment by mcr431** [comment]
@varkor GenericArgMismatchErrorCode struct is also used for E0088 and E0090 -- too many lifetime arguments and too few lifetime arguments respectively. Is this supposed to convert those to use E0107 as well as its pretty much the same use case?

**Comment by varkor** [comment]
@mcr431: oh, I forgot about those — yes, these should be merged with E0107 too. Then we'll just have a single error for "you didn't give the right number of generic arguments" (the actual error message itself will give the details about which kind of generic argument, and how many, so we don't need to separate the error codes too). Thanks!

**Comment by varkor** [comment]
@mcr431: if you run the tests with `--bless`, it should update most of them automatically. In some places you might need to modify the `//~ ERROR` comments in the test itself though. I'd expect quite a lot of test output to change, so don't worry if you end up needing to modify some of the tests.

**Comment by mcr431** [comment]
@varkor understood. How should I handle the errors such as ui/error-codes/E0244.rs (as well as all other removed error codes). Should these tests be removed (and then added to ui/error-codes/E0107.rs) or should I just edit them to use 0107 error code? Not super familiar with the testing structure so not sure if this question makes any sense.

**Comment by varkor** [comment]
@mcr431: ah, I forgot about those. I would edit them to use the `E0107` error code (the other deprecated error codes still seem to have tests).

**Comment by mcr431** [comment]
@varkor Thank you!

**Comment by mcr431** [comment]
Didn't realize you said I should remove E0001 and already submitted PR. let me know If i should modify to remove it

**Comment by varkor** [comment]
> Didn't realize you said I should remove E0001 and already submitted PR.

Don't worry about it; it's technically unrelated.
