### ISSUE TITLE
Disallow attribute macros named cfg

### ISSUE THREAD

**Issue by djrenren** [rust-lang/rust#53531]
`#[cfg()]` runs before name resolution so no proc macro attribute named `cfg` could ever be called. We should make this a hard error at the declaration site to protect people from this confusion.

**Comment by djrenren** [comment]
I think this would be a good issue for mentoring. I'm happy to help out.

**Comment by Havvy** [comment]
The `test` attribute seems to be similarly ignored.

**Comment by otavio** [comment]
I could give it a go. As a first time contributor please be patient 😉

**Comment by djrenren** [comment]
@Havvy Yeah, though that's not by necessity, so I wanna do a crater run and see if we could give it normal resolution.

**Comment by eddyb** [comment]
I'd do it during name resolution instead, so you can do `#[foo::cfg(...)]` just fine, but not import it unqualified.

cc @petrochenkov

**Comment by petrochenkov** [comment]
I have a PR in progress that resolves the penultimate item in https://github.com/rust-lang/rust/pull/50911#issuecomment-411605393 and passes all attributes through name resolution, that includes `cfg` as well.

(Disallowing proc macros named `cfg` is both too much - `#[foo::cfg]` is ok, and not enough - `use my_non_cfg_attr_macro as cfg;`).
