### ISSUE TITLE
insert for slices

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust#53538]
While working with slices and arrays I sometimes need a slice function similar to Vec::insert:

```
let mut a = [10, 20, 30, 40];
a.insert_shift(1, 5);
assert!(a == [10, 5, 20, 30]);
```

All the items gets shifted on the right, and the last item of the slice drops down.

**Comment by ExpHP** [comment]
Implementation in terms of stable functions:

```rust
fn insert_shift(&mut self, i: usize, value: T) {
    self[i..].rotate_right(1);
    self[i] = value;
}
```

I don't have a strong opinion about it right now as it's not something I ever found myself reaching for. 
 Can you share your use cases?

**Comment by leonardo-m** [comment]
Yes, the rotate is good enough.
