### ISSUE TITLE
-Zdump-mir does not dump all the MIR: drop glue missing

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#53532]
There seems to be no way currently to dump at least some of the MIR that rustc generates itself, e.g. for drop.

In the following code
```rust
struct Bar(u16); // ZSTs are tested separately

static mut DROP_COUNT: usize = 0;

impl Drop for Bar {
    fn drop(&mut self) {
        assert_eq!(self.0 as usize, unsafe { DROP_COUNT }); // tests whether we are called at a valid address
        unsafe { DROP_COUNT += 1; }
    }
}

fn main() {
    let b = [Bar(0), Bar(1), Bar(2), Bar(3)];
    assert_eq!(unsafe { DROP_COUNT }, 0);
    drop(b);
    assert_eq!(unsafe { DROP_COUNT }, 4);

    // check empty case
    let b : [Bar; 0] = [];
    drop(b);
    assert_eq!(unsafe { DROP_COUNT }, 4);
}
```
I can clearly see miri execute an `Offset` binop (a binop which is only ever emitted by the auto-generated drop glue), but grepping the entire dump directory for `Offset` shows no hit.

**Comment by RalfJung** [comment]
I got started on this, wrote https://github.com/RalfJung/rust/tree/mir-shim-dump. Now it tries to dump MIR for shims. The problem is, in

https://github.com/rust-lang/rust/blob/dae6c9364108847393075b57a17fd7eaf3f37600/src/librustc_mir/util/pretty.rs#L196-L198

we call `def_path`, which asserts that the `DefId` comes from the local crate, but for shims that is not always true (it could be `core::ptr::drop_in_place`).

@oli-obk @eddyb any suggestions?

**Comment by eddyb** [comment]
@RalfJung Use the method on `tcx` that works cross-crate.

**Comment by eddyb** [comment]
I'd say it's worth fixing these. Instead of checking the body owner kind, could it check `tcx.describe_def`? Only `Def::Fn` and `Def::Method` should have method arguments and `Def::Static` would make it print `static`.

**Comment by RalfJung** [comment]
Dumping MOR of another crate works now. However, MIR dumping expects to dump polymorphic MIR, meaning (a) all drop shims get the same filename, overwriting one another, and (b) in the dumped MIR, you cannot even see which type this is dropping.

I guess I have to adjust `to_filename_friendly_no_crate` at the least?

**Comment by RalfJung** [comment]
That sounds like a real bad hack. :/  Not to mention that it'd require some global state.

**Comment by eddyb** [comment]
Oh the printing is a side-effect of building MIR? Oops, I forgot.
Well then, put a (type) hash in the file name (cc @michaelwoerister)

**Comment by RalfJung** [comment]
I hear @matthewjasper has a branch where dumping shims at least somewhat works. Could you point me to that branch?

**Comment by RalfJung** [comment]
I rebased the branch to see if I can make some more progress, but what used to work doesn't work any more.  I am now getting a panic in [this line](https://github.com/RalfJung/rust/blob/d115af217ed92b4f00fa13c9031493cfb1b4f338/src/librustc_mir/util/pretty.rs#L574) when dumping the MIR for `DefId(0/1:11 ~ test[317d]::main[0]::{{constant}}[0])` (using the code from the OP).

Any idea why that `DefId` cannot be described?
