### ISSUE TITLE
Remove mem.rs line numbers from const-size_of-cycle.stderr

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust#53547]
https://github.com/rust-lang/rust/blob/1558ae7cfd5e1190d3388dcc6f0f734589e4e478/src/test/ui/consts/const-size_of-cycle.stderr#L5

It is not nice for this test to fail any time we insert a line in mem.rs, as happened in https://github.com/rust-lang/rust/pull/53503. Please implement this test in a way that does not hardcode a line number.

Please also try to find standard library line numbers in other ui tests and scrub those in the same way.

As far as I can tell, the const-size_of-cycle.stderr file was newly added in #53196 so attn @davidtwco.

**Comment by dtolnay** [comment]
`rg SRC_DIR/lib src` turns up only one other case:

https://github.com/rust-lang/rust/blob/1558ae7cfd5e1190d3388dcc6f0f734589e4e478/src/test/ui/impl-trait/impl-generic-mismatch.stderr#L33

**Comment by davidtwco** [comment]
@eddyb I think it could make sense to keep line numbers for paths like it is now - I think there could be an (admittedly rare) case where a change causes an error to be reported on an incorrect line and that wouldn't be spotted (although, the highlighted code from the error would need to be the same on both lines - which isn't impossible, just unlikely).

Either way, I'll put together a PR that normalizes these two cases for the time being.

**Comment by davidtwco** [comment]
Submitted #53558 that adds normalization for this case to `compiletest` as I think we wouldn't ever want to assert that line numbers from compiler source do not change in error messages.
