### ISSUE TITLE
Pass closure captures explicitly in HIR, and refer to them by index, not local ID.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#53553]
HIR lowering happens after name resolution, so we know the set of captures (aka "upvars" aka "freevars") of each closure. We could write them out in the closure expression/"definition" instead of keeping an extra map around, and we could also change the `Def::Upvar` of their uses in the body, to use an index instead of referring to each captured local's original `NodeId` / `HirId`.

This way I think we can have closure bodies completely disjoint from the bodies the closures are instantiated in, maybe even at the `HirId` level. Ideally we would change the HIR in such a way that expr/pat/etc. nodes can't reference locals/labels across `HirId` "owners".
That is, we have `DefId`s for "global definitions" and everything else (ignoring the type-level signatures/where clauses etc. for the moment) lives in bodies that can't refer to eachother.

cc @nikomatsakis @michaelwoerister

**Comment by michaelwoerister** [comment]
Sounds good.

**Comment by eddyb** [comment]
The refactors that already happened seem better than what I was proposing here.
Notably, the map is gone, and upvars are computed *from* the HIR.
While I considered it, it would be pretty annoying to collect upvars during HIR lowering.
