### ISSUE TITLE
Constant validation is not cached

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#53561]
Constant validation is not part of the query that evaluates constants, because it would cause cycle errors in case a static directly or transitively contained a pointer back to itself.

One possible solution is to wrap another query around the `const_eval` query, not exposing the `const_eval` query to regular callers (similar to `is_freeze_raw`) and having a wrapper query around it that does the validation and thus also caches the validation.

**Comment by RalfJung** [comment]
The same mechanism is also needed for generic constants to get any validation at all.

Also, when we are adding "wrapper queries", it might be a good idea to have separate queries for const and static. The current situation there (about who reports which errors when, and about whether the result *must* be `ByRef` or *must* be normalized to use `Scalar` where possible) is rather messy.
