### ISSUE TITLE
Rename "anonymized types" internally (TyAnon & friends) to "opaque types" (TyOpaque etc.).

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#53576]
~~Now that we're settling on "static existentials" for the generalized version of `-> impl Trait`, I think it's time to retire my original nomenclature and use the official(?) one uniformly in the compiler.~~

**EDIT**: going with "opaque", see below.

cc @cramertj @oli-obk @aturon @Centril

**Comment by eddyb** [comment]
Alternatively, since @varkor protests, I'd be fine with `TySome` and "some type" in error messages (okay maybe it's just that I find this part amusing).
cc @aturon @Centril

**Comment by ms2300** [comment]
@eddyb Can I take this ticket on? As it'd be the first ticket I'd take here is there anything I should know beyond the contributing.md?

**Comment by eddyb** [comment]
@varkor wants it to be `TyOpaque`, so maybe we should do that instead instead of my half-baked ideas.

@ms2300 Seems good! Searching for `Anon` and `anon` should find you all of the relevant places in the codebase (you can ignore `AnonConst` - if you see more that you're not sure about, feel free to ask).

**Comment by Centril** [comment]
I, like @varkor, would be most happy with `TyOpaque` instead of vocabulary reminiscent of existential types (e.g. `TySome`, `TyExists`, ..)

**Comment by ms2300** [comment]
Sounds good, I'll let you all know if I have more questions

**Comment by ms2300** [comment]
So I'm looking into it and AnonConst, AnonPipe, LateBoundAnon, BrAnon, and Anon (in the FileName sense) don't need to be changed right? Really all that needs to be changed is the internal type of Anon -> Opaque which used to be TyAnon correct?

**Comment by varkor** [comment]
> So I'm looking into it and AnonConst, AnonPipe, LateBoundAnon, BrAnon, and Anon (in the FileName sense) don't need to be changed right?

That's right.

> Really all that needs to be changed is the internal type of Anon -> Opaque which used to be TyAnon correct?

Yes, and anything that might refer to `TyAnon` as an "anonymous type" (for example in error messages or diagnostics), as well as variable and function names, such as anything containing `anon_ty`, or `mk_anon`, etc. It's quite hard to find all of these, but if you search for `anon` (case insensitive, but possibly mid-word), you should find most of them.

**Comment by ms2300** [comment]
I just opened a pr to fix this issue -> https://github.com/rust-lang/rust/pull/53705
