### ISSUE TITLE
Tidy CTFE/miri

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#53596]
CTFE/miri (the code in `src/librustc/mir/interpret` and `src/librustc_mir/interpret`) is currently exempt from tidy:

https://github.com/rust-lang/rust/blob/24bc544db4238a8248be7d6e7eae893cf945f1f2/src/tools/tidy/src/lib.rs#L79-L80

That should not be hard to fix, it is mostly a matter of adding a license header everywhere and breaking long lines into less than 100 characters. Basically, start by removing the above two lines from tidy, and then `./x.py --stage 1 test tidy` will tell you all that needs fixing.

**Comment by bemeurer** [comment]
@RalfJung I'd like to take this, if that's OK :)

**Comment by RalfJung** [comment]
That's perfect :) Let me know if you need anything!

**Comment by bemeurer** [comment]
@RalfJung Is this the correct license header?
```
// Copyright 2013-2015 The Rust Project Developers. See the COPYRIGHT
// file at the top-level directory of this distribution and at
// http://rust-lang.org/COPYRIGHT.
//
// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
// option. This file may not be copied, modified, or distributed
// except according to those terms.
```

**Comment by bemeurer** [comment]
@RalfJung Yeah, I had `2013-2015` before, since I just pasted it from some random file, but I updated it to just say `2018`

**Comment by memoryruins** [comment]
Impeccable timing #53617 #53654

**Comment by RalfJung** [comment]
Well, yeah^^

**Comment by bemeurer** [comment]
Hehehe
