### ISSUE TITLE
Documentation: add goal-oriented method tables to the API documentation

### ISSUE THREAD

**Issue by kud1ing** [rust-lang/rust#53593]
I've recently struggled to use `HashMap` in a certain way.

To help me, i've assembled the methods in goal-oriented tables:

![HashMap](https://user-images.githubusercontent.com/391975/58480897-96970f00-815b-11e9-9308-6139789dca0c.png)

I think it would be beneficial to both users and Rust developers to have something like this in the API docs.

The tables show some empty cells, which means the functionality is not provided but in some cases it would be beneficial, e.g. in the rows "replace all entries" or "remove some entries according to a predicate".

**Comment by Havvy** [comment]
We discussed this during the docs team meeting yesterday. Overall, the idea has promise. Your tables are a great start for HashMap. The main concern we have right now is that the docs for those pages are already so long, that making them longer could make them less useful. This could be solved by having a way to auto-hide the section. And given the low number of people able to attend the meeting, we'd like to have more members weigh in.

**Comment by kud1ing** [comment]
Thank you for considering it.

I too think, that page length could be problematic. Since the API is quite stable, this could live outside of the standard lib documentation as well, without the danger of to much divergence. But i don't know where.
