### ISSUE TITLE
COPYRIGHT url 404s 

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#53601]
A lot (at least 11.000) of files, for example
https://github.com/rust-lang/rust/blob/d96cc6e2865ff2cc77f061ae97e58aae50f5a1e9/src/test/run-pass/issue-12133-3.rs#L3
link to http://rust-lang.org/COPYRIGHT but the page ````404````s.

**Comment by varkor** [comment]
The simplest solution is to make http://rust-lang.org/COPYRIGHT redirect to https://github.com/rust-lang/rust/blob/master/COPYRIGHT.

**Comment by matthiaskrgr** [comment]
Ah, I didn't see the rust-www repo... :/

**Comment by varkor** [comment]
I think that's probably the right place for it to belong. Let's close this one to stop anyone getting any ideas about editing 11k files... 😅
