### ISSUE TITLE
Lifetimes get replaced with 'static in Self within (return position) impl Trait.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#53613]
```rust
#[derive(Copy, Clone)]
struct Invariant<'a>(std::marker::PhantomData<&'a mut &'a ()>);

impl<'a> Invariant<'a> {
    fn lazy_dup(self) -> impl Fn() -> (Invariant<'a>, Self) {
        || (self, self)
    }
}
```
```rust
error[E0308]: mismatched types
 --> src/lib.rs:6:19
  |
6 |         || (self, self)
  |                   ^^^^ lifetime mismatch
  |
  = note: expected type `Invariant<'static>`
             found type `Invariant<'a>`
```

I didn't write `'static` anywhere - it comes from part of the implementation of `impl Trait`, and `Self` references lifetimes (from the `impl` header) "indirectly", hiding them from `impl Trait` logic.

cc @cramertj @oli-obk @nikomatsakis

**Comment by nikomatsakis** [comment]
There is a variant of this problem that was revealed in #62221. If you write `T::Item`, and we expand that (in type-checking) to `<T as Foo<'a>>::Item`, the `'a` is overlooked as well ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=21a3567255a2d0c49e28d39d58f1949a)):

```rust
pub trait HasItem<'a> {
    type Item;
}

// Does not work:
fn example1<'a, T: HasItem<'a>>(item: T::Item) -> impl IntoIterator<Item = T::Item> {
    Some(item)
}

// Works:
fn example2<'a, T: HasItem<'a>>(item: T::Item) -> impl IntoIterator<Item = <T as HasItem<'a>>::Item> {
    Some(item)
}

fn main() { }
```

**Comment by nikomatsakis** [comment]
[I left some notes in this Zulip topic](https://rust-lang.zulipchat.com/#narrow/stream/187312-wg-async-foundations/topic/.60Self.60.20and.20.60'static.60.20.2361949/near/170476808) that explain one way to fix this problem. The idea is basically to detect `Self` during lowering and take it into account.

**Comment by Arnavion** [comment]
Just like https://github.com/rust-lang/rust/issues/61949 I guess this is also fixed by https://github.com/rust-lang/rust/pull/115659 ? The test case in the OP compiles fine today, other than needing to add `move` to the closure to make it `move || (self, self)`

**Comment by Dylan-DPC** [comment]
Closing this as it's fixed and it compiles to a different error with indication on how to fix it by adding `move` to the closure.
