### ISSUE TITLE
Remove -Z time-passes and error with "-Z self-profile should be used instead".

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#53631]
Remaining issues with `-Z self-profile`:
* [ ] at least as much granularity as `-Z time-passes` had pre-queries
* [ ] trigger on unsuccessful compilation / ICE / Ctrl+C, as well
* [ ] real-time progress indicator (#53630 perhaps?)

cc @steveklabnik @wesleywiser @alexcrichton @rust-lang/compiler

**Comment by nikomatsakis** [comment]
I'm in favor!

**Comment by Zoxc** [comment]
I'm against. I use `-Z time-passes` all the time when doing any performance work.

**Comment by bemeurer** [comment]
I'd like to take this on if that's okay :)

**Comment by bjorn3** [comment]
`-Z self-profile` provides a much less detailed output

**Comment by kennytm** [comment]
I'm mildly against if the replacement can't print some compilation progress at real time.

**Comment by eddyb** [comment]
@bjorn3 How so, does it not have a per-query breakdown? I'll shamefully admit I opened this issue away from my laptop when I remembered `-Z self-profile` landed, and I haven't played with it yet.

Either way, we should track the remaining problems with `-Z self-profile` in this issue, and remove `-Z time-passes` when they're resolved.

@Zoxc also mentioned on IRC that it doesn't work when there are errors.

@kennytm Ah, great point, I had forgotten. Would #53630 solve the "real time" problem for you?
I'd add that maybe we should catch `Ctrl+C` and *also* print the profile summary then too.

**Comment by kennytm** [comment]
@eddyb works for me 😃

**Comment by wesleywiser** [comment]
@eddyb We don't have per-query breakdown yet, just broad level categorization. Per-query is the next thing I plan on working on.

**Comment by nagisa** [comment]
I want some way to output various "events" pertaining to the query system (query X start, query X end, query X etc) in whatever format, as they occur. Preferably the format would target some tooling that already exists, but I cannot really advise on anything in particular at the moment. See [this comment](https://github.com/rust-lang/rust/issues/53630#issuecomment-415396437) for examples of what I’m talking about.

This could possibly be the solution for the granularity problem. I can say from experience, that tracing such events is definitely not as expensive as it may sound and usually introduces overhead in proximity of tens to hundreds of ns per event.

**Comment by eddyb** [comment]
@nagisa I think we already have something similar because of dep graph tracking, but @michaelwoerister knows more than me here (I remember seeing event-collecting threads).

**Comment by nagisa** [comment]
Looking into webrender I noticed it uses [thread_profiler](https://github.com/glennw/thread_profiler), which implements https://docs.google.com/document/d/1CvAClvFfyA5R-PhYUmn5OOQtYMH4h6I0nSsKchNAySU/edit#heading=h.yr4qxyxotyw. Links lead to [catapult](https://github.com/catapult-project/catapult), which upon the first blush seems similar to the tools I referenced before.

**Comment by nikomatsakis** [comment]
That is roughly what the old stuff did, iirc. I think we mostly ripped that out. I like the idea emitting events, at least in principle. I also like the idea of per-query profiling. I **also** like the idea of removing time-passes =) 

It seems like we can fix things to emit a result in the case of error without great difficulty? Mostly a matter of using a `Drop` impl or something, no?

**Comment by nikomatsakis** [comment]
Ah I see @eddyb already made a check-list, 👍 from me. I'd be ok with removing `-Ztime-passes` earlier too but I don't mind waiting.

**Comment by FrankSD** [comment]
Anyone is  working on this?

**Comment by wesleywiser** [comment]
Hi @FrankSD! The self-profile feature has a fair bit of churn going on right now. Before you decide to work on this, I'd recommend stopping by the [`t-compiler/wg-self-profile` channel on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/187831-t-compiler.2Fwg-self-profile).

**Comment by jyn514** [comment]
I don't think we should remove time-passes until self-profile measures memory usage: https://github.com/rust-lang/rust/issues/81348

**Comment by john-h-k** [comment]
Is this still a desired thing?

**Comment by jyn514** [comment]
I would rather not make this change. -Z time-passes is nice because you can get feedback while compilation is still ongoing, without having to wait for it to finish. It's less accurate but it's also a lot nicer to use.

**Comment by fee1-dead** [comment]
I'm going to close this issue based on the comments below since it appears that no further input is likely.
