### ISSUE TITLE
Box docs don't mention that you can move out of them

### ISSUE THREAD

**Issue by ExpHP** [rust-lang/rust#53634]
I wanted to link somebody to documentation explaining that you can dereference a `Box` to move the value onto the stack, but... neither the `boxed` module nor `Box` mention this or show any examples!

https://doc.rust-lang.org/stable/std/boxed/index.html
https://doc.rust-lang.org/stable/std/boxed/struct.Box.html

**Comment by frewsxcv** [comment]
Opened a PR for this: https://github.com/rust-lang/rust/pull/54544
