### ISSUE TITLE
Usage of proc_macro library for programming compilers that are not procedural macros

### ISSUE THREAD

**Issue by ptal** [rust-lang/rust#53647]
The Rust error messages library (`Diagnostic` and the like) could be very convenient and useful to developers of compiler's prototypes. Unfortunately, `proc_macro` keeps private a bunch of functions that would be necessary to use it outside of the context of a macro. It is as simple as creating a `Span`, but also more complex as keeping track and managing source files.

Compiler developers have only few alternatives:

* Relying on library such as `syntex` that makes these modules and functions public (but it is not maintained anymore...).
* Build an in-house error reporting system (what a waste of time).
* Design the language as an EDSL in Rust to be able to use `proc_macro` (what if the host language is not Rust).

A solution might be to provide factory functions guarded behind an option, so the user needs to opt-in, as it would clearly not be the mainstream usage.

Long-term arguments in favor to make more `proc_macro` functions public:
* A first step towards a real toolbox for compiler programmers who wants to use Rust for prototyping. This is extremely common in research for example. Besides, researchers who would use Rust could also teach it.
* Obtaining a first-rate compiler with good error messages without spending too much time on the infrastructure.

Examples: two of my projects [bonsai](https://github.com/ptal/bonsai) and [oak](https://github.com/ptal/oak) rely on `syntex` for error reporting, and thus cannot be compiled on Rust stable.

**Comment by eddyb** [comment]
Note that everything here must be compatible with the new proc-macro bridge from #49219.
(including the fact that `proc_macro` is useless outside of a proc-macro crate being used by `rustc`, unless a custom `Server` is implemented, e.g. by using the `syn`-based `proc-macro2` stable mode)

I think more things could be added, but we have to be a bit careful about every addition.

Expanding the `SourceFile` API to be able to load files and provide access to their source as `String`, or even lex to a `TokenStream`, seems useful and doable, as does `Span` manipulation.

cc @alexcrichton @dtolnay @petrochenkov

**Comment by memoryruins** [comment]
[codespan](https://github.com/brendanzab/codespan) is worth checking out.

cc @brendanzab

**Comment by brendanzab** [comment]
Yeah, currently trying to grow codespan into something along those lines, but it's still very behind in terms of parity when it comes to the quality of Rust's error diagnostics. But hopefully it can be improved further in a combined effort - just need to start somewhere!

**Comment by ptal** [comment]
@eddyb An advantage of `proc_macro` is that users always create new `span` by merging existing ones, and thus cannot(?) create "wrong spans". That is why I suggested that we should maybe guards some functionalities from being used inside the context of a procedural macro.

@brendanzab `codespan` is cool but in the long-term, what are the advantages of developing two different error reporting mechanisms? Moreover, I suspect the one in Rust will be more used, tested and probably maintained.
Another use case is that I'd need both `Span` from procedural macros and from "normal compiler" to be the exact same objects (for compatibility matters).

**Comment by brendanzab** [comment]
I agree. Ideally we would be able to get bug reports from upstreamed to a common library (whatever that is). Rust's error reporting is quite tied to rustc however, and hence some of the design decisions don't match up with, for example, compilers that are designed as language servers from the start. Some of these have been inherited by codespan's `CodeMap` type, but @Marwes, @wycats, and I have been discussing ways to get around these limitations on the Gitter channel though.

The longer term vision is to allow many different languages built in Rust to share a similar error reporting mechanism so that we can share the bug fixes and UX improvements, and make it easier for us all to build language-servers and editor plugins. Still a longish way off that dream though.

**Comment by eddyb** [comment]
> That is why I suggested that we should maybe guards some functionalities from being used inside the context of a procedural macro.

You can't use `proc_macro` *at all* outside of the context of a procedural macro.
Some things *may happen* to work right now, but *fundamentally can't* after #49219.

**Comment by alexcrichton** [comment]
The `proc_macro2` crate should be used for developers which need a working `proc_macro` in all contexts, otherwise there's no current plans to get `proc_macro` working outside the compiler, so I'm going to close this
