### ISSUE TITLE
Replace std::io::lazy::Lazy with a copy of lazy-static's similar, but Once-using, type.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#53646]
It's not clear why `std::io::lazy` doesn't use `Once`, as that was available at the time when it was introduced.

#53108 marked `Lazy::new` as `unsafe` because of the lack of reentrance safety in the mutex being used, but `Once` *specifically doesn't* have reentrancy issues.

`lazy_static` version: https://github.com/rust-lang-nursery/lazy-static.rs/blob/13159c2b615903d93b4cd4f98d17fdfe70392a3a/src/inline_lazy.rs

However, we need to change it per https://github.com/rust-lang-nursery/lazy-static.rs/issues/117, otherwise it's **unsound**.

cc @RalfJung @alexcrichton

**Comment by RalfJung** [comment]
There was also some discussion on IRL to [move lazy-static into libstd](https://internals.rust-lang.org/t/pre-rfc-lazy-static-move-to-std/7993/) and claims that it is not necessary with `const fn`. Why can't this use `Once` more directly and entirely safely?

**Comment by RalfJung** [comment]
https://github.com/rust-lang/rust/pull/53604 changes `Lazy` to be even more similar to `Once`, so I guess changing it all the way should be trivial now...

In fact, @oli-obk why wasn't that changed as part of that PR? Just to keep the changes smaller?

**Comment by oli-obk** [comment]
> Just to keep the changes smaller?

yes

**Comment by RalfJung** [comment]
`Lazy` does some magic to also register an at-exit hook for deallocation:
```rust
        // If we successfully register an at exit handler, then we cache the
        // `Arc` allocation in our own internal box (it will get deallocated by
        // the at exit handler). Otherwise we just return the freshly allocated
        // `Arc`.
        let registered = sys_common::at_exit(move || {
            let ptr = {
                let _guard = self.lock.lock();
                self.ptr.replace(done())
            };
            drop(Box::from_raw(ptr))
        });
```
Maybe that's why it can't just use `Once`. `self.ptr` is actually written to twice: once to initialize, and once to de-initialize.

**Comment by workingjubilee** [comment]
We stabilized LazyLock and LazyCell. I think we're done here.

**Comment by RalfJung** [comment]
This issue wasn't about stabilizing anything, it was entirely about std internals... turns out this was fixed 4 years ago on https://github.com/rust-lang/rust/commit/bab15f773afd5724023d9a065b5af276e2468ff5.

**Comment by workingjubilee** [comment]
Yes, "we stabilized these" was, in this case, short for "we have refactored almost every single instance of Lazy-whatever in the standard library."
