### ISSUE TITLE
Dead link in `Vec::extend_from_slice` std lib documentation.

### ISSUE THREAD

**Issue by vext01** [rust-lang/rust#53665]
Hi,

There's a broken link in the `std::Vec` docs:

![doc-bug](https://user-images.githubusercontent.com/604955/44581169-90bb6a00-a794-11e8-9dd0-850e463c9cd1.png)

Clicking it is a `NOP`.

Thanks!

**Comment by matthiaskrgr** [comment]
Hi, this is a duplicate to https://github.com/rust-lang/rust/issues/52774

**Comment by vext01** [comment]
OK, shall I close it?

Thanks

**Comment by frewsxcv** [comment]
Yeah, we'll track this in the other issue. Thanks for reporting it though!
