### ISSUE TITLE
Optimize layout of nested field-less enums

### ISSUE THREAD

**Issue by newpavlov** [rust-lang/rust#53669]
```rust
pub enum Bar {
    A = 1,
    B = 2,
    C = 3,
}

pub enum Baz {
    D = 4,
    E = 5,
    F = 6,
}

pub enum Foo {
    Bar(Bar),
    Baz(Baz),
}
```

Currently `Foo` takes 2 bytes, even though it can be trivially represented as a single `u8`.

**Comment by leoschwarz** [comment]
I think this is related to https://github.com/rust-lang/rust/issues/46213, which is as far as I understand a more general case of your proposed optimization.

**Comment by newpavlov** [comment]
Hm, looks like it. I will close this issue in favor of the linked one.
