### ISSUE TITLE
rustdoc repeats implementation 13 times

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#53689]
This has probably already been filed... but rustdoc displays an impl 13 times [here](https://doc.rust-lang.org/nightly/std/borrow/trait.ToOwned.html#foreign-impls).

**Comment by GuillaumeGomez** [comment]
We weren't sure once was enough. :D

**Comment by GuillaumeGomez** [comment]
It actually allowed me to see more UI bugs. Opening an issue for those ones.
