### ISSUE TITLE
introduce a fresh variant for "non-normalized" associated types

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#53683]
In the compiler today, we have one variant for associated type projections (e.g., `T::Foo`):

https://github.com/rust-lang/rust/blob/727eabd68143e968d8826ee29b8ea7792d29fa96/src/librustc/ty/sty.rs#L156-L158

We use context to know whether this is normalized or not -- basically, it should *always* be normalized, unless the type results from one of those queries that fetches the type that the user wrote for something like a field etc. In the lazy normalization approach that Chalk uses, however, we would want to be able to explicitly represent this difference.

The job here is to add a new variant. I think we should call it `TyUnnormalizedProjection`. This would be entirely unused for now -- but when we start to enable chalk, we will create this type when translating user types directly, and only create `TyProjection` in the case that we have attempted to normalize the projection and failed.

cc @tmandry @scalexm

**Comment by scalexm** [comment]
Introduced in #54789.
