### ISSUE TITLE
x.py: --keep-stage 1 does not imply --keep-stage 0

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#53698]
To rerun tests without rebuilding the compiler, I just did `./x.py --keep-stage 1 test ...`. Unfortunately, now I have to wait for >20min because it turns out that this does *not* keep stage 0. That is rather surprising -- it should keep all lower stages.

Cc @Mark-Simulacrum

**Comment by Mark-Simulacrum** [comment]
That's not necessarily what you want, for example rebuilding the stage0 compiler but using old std from stage1. You should be able to specify two (or more) keep-stage arguments if you want to keep more than one stage.

**Comment by RalfJung** [comment]
There are situations where that old std can still work? oO okay.

**Comment by Mark-Simulacrum** [comment]
Most situations, in fact. If you've not changed metadata encoding and maybe a few other things then it should work just fine.
