### ISSUE TITLE
Empty bounds lists in where clauses cause the type to not be WF-checked.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#53696]
This produces no error:
```rust
fn foo() where Vec<dyn Copy>: {}
```

Just like the other known "missing WF checks" bug (#21903):
```rust
type Foo = Vec<dyn Copy>;
```

Unlike type aliases, I don't believe you can even reach the type written in the `where` clause without any bounds, since it doesn't even "remain in the type/trait-system" (e.g. inference can't pick it up).

So it's not as bad, but I did come up with use for it as a WF requirement, in https://github.com/rust-lang/rust/issues/44580#issuecomment-415956389.

cc @rust-lang/lang @RalfJung @petrochenkov

**Comment by cramertj** [comment]
@Centril We're pretty permissive with parsing "zero or more" of many syntax elements, e.g. `fn foo() where {}` also compiles.

**Comment by Centril** [comment]
@cramertj Oh I see; that's where this is coming from. It didn't click initially; Thanks! ❤️

**Comment by Centril** [comment]
We discussed this briefly on the meeting and the consensus was that if crater passes, then this is fine.

**Comment by eddyb** [comment]
This is waiting on @nikomatsakis or someone else r+'ing #53707 (crater was clean).
