### ISSUE TITLE
Don't suggest extra clone when converting cloned slice to Vec

### ISSUE THREAD

**Issue by sunjay** [rust-lang/rust#53692]
Let's say you have the following (simplified) code: ([Rust Playground](https://play.rust-lang.org/?gist=9d7cea54df29ef7784f3c044fb389031&version=stable&mode=debug&edition=2015))

```rust
fn main() {
    let items = vec![1, 2, 3];
    let ref_items: &[i32] = &items;
    let items_clone: Vec<i32> = ref_items.clone();
}
```

This results in the following error:

```rust
error[E0308]: mismatched types
 --> src/main.rs:4:33
  |
4 |     let items_clone: Vec<i32> = ref_items.clone();
  |                                 ^^^^^^^^^^^^^^^^^
  |                                 |
  |                                 expected struct `std::vec::Vec`, found &[i32]
  |                                 help: try using a conversion method: `ref_items.clone().to_vec()`
  |
  = note: expected type `std::vec::Vec<i32>`
             found type `&[i32]`
```

The suggested fix `ref_items.clone().to_vec()` will work, but `to_vec` already copies the data so the extra `clone` is wasteful. The error message should instead suggest `ref_items.to_vec()`.

This is an error you can run into if `ref_items` was previously of type `&Vec<i32>` and you changed it to a slice after writing the rest of the code.

**Comment by csmoe** [comment]
Note: this kind of improvement applies to `&str` too: 
https://play.rust-lang.org/?gist=187e7bb009a976693176dcb45d3fdc8a&version=stable&mode=debug&edition=2015
```rust
fn main() {
    let s = "hi";
    let string: String = s.clone();
}
```
Err:
```
error[E0308]: mismatched types
 --> src/main.rs:3:26
  |
3 |     let string: String = s.clone();
  |                          ^^^^^^^^^
  |                          |
  |                          expected struct `std::string::String`, found &str
  |                          help: try using a conversion method: `s.clone().to_string()`
  |
  = note: expected type `std::string::String`
             found type `&str`
```
