### ISSUE TITLE
Make the error generated by using tuple indexing on an array more specific.

### ISSUE THREAD

**Issue by Tom1380** [rust-lang/rust#53712]
Attempting to compile this:
```rust
let a = [100, 100];
a.0;
```
will give this error:
```
error[E0609]: no field `0` on type `[{integer}; 2]`
```
I was thinking that a clearer error could be something along the lines of:
```
error[E----]: attempting to use tuple indexing on an array.
```
and give this hint:
```
help: change this to `a[0]`
```

**Comment by varkor** [comment]
This should be straightforward to add a help message for. This error message is emitted here:
https://github.com/rust-lang/rust/blob/352b852f5b199dad36b5dc62a24e9bad4c18a671/src/librustc_typeck/check/mod.rs#L3318-L3320
The `match` immediately afterwards is responsible for giving suggestions relevant to the particular type. You'd need to add a new case for `ty::Array` ([defined here](https://github.com/rust-lang/rust/blob/352b852f5b199dad36b5dc62a24e9bad4c18a671/src/librustc/ty/sty.rs#L115-L116)) and emit an appropriate message (there are examples for other types in the `match` expression), if the field is numeric.

If anyone'd like to tackle this, just post a reply here — I can give more details as needed (but it's always useful to try working things out yourself first, to get a feel for where to find things).

**Comment by Tom1380** [comment]
I don't have any experience with Rustc's codebase, but I would be willing to give it a try.

**Comment by varkor** [comment]
@Tom1380: great! If you need any help, you can post a comment here, or ask on [Discord](http://discord.gg/rust-lang) or #rustc. Once you add the help message, you'll need to add a test for it (there are plenty of examples in `src/test/ui` — you can run `./x.py test [filename] --bless` to test and produce the output).
