### ISSUE TITLE
Rename all mentions of `nil` to `unit` or `()`

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#53719]
Ancient Rust used the term `nil` to describe the empty tuple. The compiler still uses this in a few places (e.g. the `mk_nil` method). All of these mentions should be changed to the current terminology or just outright `()` in comments.

**Comment by bemeurer** [comment]
I'd like to take this on if that's okay @oli-obk :)

**Comment by oli-obk** [comment]
It's all yours!
