### ISSUE TITLE
`Range` is not a lang item

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rust#53720]
https://github.com/rust-lang/rust/blob/c0955a34bcb17f0b31d7b86522a520ebe7fa93ac/src/libcore/ops/range.rs#L79-L89

Rustc always lowers it to `::ops::Range`.

https://github.com/rust-lang/rust/blob/caed80ba4ba8d9f4d3fa8aa9af6c4092d779cd9d/src/librustc/hir/lowering.rs#L3781-L3809

Found some more lowerings like this

https://github.com/rust-lang/rust/blob/caed80ba4ba8d9f4d3fa8aa9af6c4092d779cd9d/src/librustc/hir/lowering.rs#L4207

https://github.com/rust-lang/rust/blob/caed80ba4ba8d9f4d3fa8aa9af6c4092d779cd9d/src/librustc/hir/lowering.rs#L4809

https://github.com/rust-lang/rust/blob/caed80ba4ba8d9f4d3fa8aa9af6c4092d779cd9d/src/librustc/hir/lowering.rs#L3774

They should probably be a lang item.

**Comment by durka** [comment]
Related to #20541.

**Comment by Mark-Simulacrum** [comment]
This is still the case today, though is a bit harder to grep for as rustc uses symbols now for the elements, e.g., https://github.com/rust-lang/rust/blob/3014f23ddd437d2ba9947383c4565d09c1eb39f2/src/librustc_ast_lowering/expr.rs#L850

**Comment by davidtwco** [comment]
Closing, fixed by #75145.
