### ISSUE TITLE
Attribute on attribute action

### ISSUE THREAD

**Issue by caitp** [rust-lang/rust#53729]
I'd l ike to be be able to do something like this:

```rust
#[cfg(....some thing)]
#![some inner attributes]  // omitted if the above attr evaluates false

#[cfg(...some alternative thing)]
#![some alternative inner attributes]  // ditto
```

but of course, attributes don't seem to qualify as "Items",  so there's no way to do this.

This could be used for conditionally using the `inline` attr on some method to easily see a difference in perf or executable size between 2 builds, or conditionally using some crate-wide linker attributes, or what have you.

**Comment by sfackler** [comment]
The cfg_attr attribute handles this:

```rust
#![cfg_attr(...some thing, some inner attributes)]
```

**Comment by caitp** [comment]
Is this in the book? I don’t think this was mentioned in the attrs chapter

**Comment by caitp** [comment]
That said, even if this use-case is technically possible, it's not that nice of a way to do it, compared with C preprocessor conditional blocks. It seems like once there are more attrs exposed, there will be more of a need for something better.

**Comment by memoryruins** [comment]
The [reference](https://doc.rust-lang.org/stable/reference/attributes.html#conditional-compilation) mentions it as well.

**Comment by Havvy** [comment]
There's no reason that `#[cfg_attr(cond_expr, attr)]` cannot be extended to take multiple attributes. It would need to go through the RFC process first, but it should be uncontroversial.

**Comment by Centril** [comment]
Not speaking for the whole lang team... but extending this to `#[cfg_attr(cond_expr, $(attr),+)]` seems like a trivial change that could just be proposed as a PR imo with a feature gate on it. It probably doesn't need a full RFC.

**Comment by caitp** [comment]
Hum, one thing I did want to do seems to not be possible with cfg_attr, or an y other workaround I've tried, short of patching the binary as Servo seems to do  (https://github.com/servo/servo/blob/da8f06b0f9da13cdd3331528d620792e5672eb73/python/servo/build_commands.py#L262-L266)

It would be nice to be able to do something like

```
// avoid the editbin malarky
#![cfg_attr(ndebug, windows_subsystem = "windows")]
```

--- but, it doesn't seem to be possible to query the current profile via `cfg!()` or `cfg()`, for whatever reason --- or at least, as far as I can tell, ndebug support has been removed, and debug_assertions seems to be primarily enabled either manually or during tests.

**Comment by jonas-schievink** [comment]
`debug_assertions` is enabled depending on the Cargo profile in use. By default `cargo build` and `cargo test` will set it, while `cargo build --release` won't.

Support for `cfg_attr` to apply multiple attributes is coming with the next Rust version, 1.33.0, so I'll close this since this seems solved.
