### ISSUE TITLE
compiletest does not pass `--extern` flags

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#53737]
In https://github.com/rust-lang/rust/pull/51456, @qmx and I noticed that compiletest, when using aux-build libraries, simply supplies the compiler with `-L` instead of using the `--extern lib_name=path-to-rlib` compiler argument form. This is a shame because the latter form is what cargo actually uses in practice!

We ought to add another comment form to use the latter. Something like:

```
// aux-build:lib_name=file.rs
```

or perhaps a different header name.

(We could also retrofit the existing `aux-build` to use `--extern`, but it seems useful to be able to test in both modes, actually, so I'd prefer to add something new.)

**Comment by eddyb** [comment]
I have a branch where I implemented the `--extern crate_name` form *without* a path, (which was suggested for Rust 2018) and started using it with `// compile-flags:--extern lib_name`.

Which way is preferred here?

**Comment by qmx** [comment]
@eddyb care to link the branch?

**Comment by nikomatsakis** [comment]
@eddyb my preference would be to be able to test All The Things, I guess? That is, I see value in both. I guess the motivation for `--extern` though is to make Rust 2018 niceties available to people that are not using cargo (and hence want `-L`)? (Which makes sense)

**Comment by jieyouxu** [comment]
compiletest triage: this is actually not actionable:

- For `//@ aux-build`s, the ui tests are by default compiled with Edition 2015, where the `--extern` is insufficient anyway, as you still have to write `extern crate xxx;`.
- There is `//@ aux-crate` which does pass the `--extern` by default.
