### ISSUE TITLE
False positive for dead_code lint in test support code

### ISSUE THREAD

**Issue by djc** [rust-lang/rust#53760]
I'm using a test support module as explained [in the book](https://doc.rust-lang.org/stable/book/second-edition/ch11-03-test-organization.html#submodules-in-integration-tests).

However, it turns out that functions in the submodule are regarded as `dead_code` unless they are used in every test module.

This seems clearly wrong. I'm guessing the submodules are substituted into each test scenario module and the submodules are thus not linted for all test scenarios at the same time.

**Comment by Havvy** [comment]
Do you have an example of this behaviour we can look at?

**Comment by djc** [comment]
Here's a reduced test repository: https://github.com/djc/tests-common-dead

To see the problem, `touch tests/common/mod.rs`, then run `cargo test`.

(It occurs to me that the problem might be related to the fact that there are multiple module declarations for `common` in this case, but I can't think of another way of doing it.)

**Comment by Havvy** [comment]
One workaround is too just `#![allow(dead_code)]` in `tests/common/mod.rs`.

**Comment by djc** [comment]
That's what I have now. But it took me a while to figure out; and the lint is just wrong.

**Comment by steveklabnik** [comment]
Triage: I don't believe the lint is wrong. Each file in the `tests` directory is compiled as a separate thing. When `bar.rs` is compiled, there is `mod common;`, meaning the module is private, and `common::baz` is never used.  That `foo.rs` uses it isn't really something that rust can know about.

This may be slightly confusing at first, but it is working as intended, as far as I know. thanks for the report!
