### ISSUE TITLE
NLL reports "borrow used here in later iteration of loop" in cases outside of loop

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#53773]
Spawned off of https://github.com/rust-lang/rust/issues/53220#issuecomment-411760394

In this code ([play](https://play.rust-lang.org/?gist=5bbb4640a98bcddae6b0f1569e31807c&version=nightly&mode=debug&edition=2015)), we report "borrow used here in later iteration of loop" for the `members.len()` call that is not within the loop.

```
#![feature(nll)]

struct Archive;
struct ArchiveIterator<'a> { x: &'a Archive }
struct ArchiveChild<'a> { x: &'a Archive }

struct A { raw: &'static mut Archive }
struct Iter<'a> { raw: &'a mut ArchiveIterator<'a> }
struct C<'a> { raw: &'a mut ArchiveChild<'a> }

impl A { pub fn iter(&self) -> Iter<'_> { panic!() } }
impl Drop for A { fn drop(&mut self) { } }
impl<'a> Drop for C<'a> { fn drop(&mut self) { } }

impl<'a> Iterator for Iter<'a> {
    type Item = C<'a>;
    fn next(&mut self) -> Option<C<'a>> { panic!() }
}


fn error(archive: &A) {
    let mut members: Vec<&mut ArchiveChild<'_>> = vec![];
    for child in archive.iter() {
        members.push(child.raw);
    }
    members.len();
}
  
fn main() { }
```

(I assume this is due to some bug in how we are attempting to reverse-engineer the existence of a loop by analyzing the basic-block control-flow of MIR alone.)

**Comment by estebank** [comment]
If you comment out `members.len();` [the label is more appropriate](https://play.rust-lang.org/?gist=0113581411392514772d0f98612fb552&version=nightly&mode=debug&edition=2015) (same text points at `members` in `members.push`), but it's not helpful enough.

**Comment by estebank** [comment]
@pnkfelix It seems that would be the relevant issue. I was pointing out what happens when removing the line as it hints at where the problem might be introduced in rustc.

**Comment by nikomatsakis** [comment]
I believe that the change I suggested in https://github.com/rust-lang/rust/issues/54015 would also fix this.

**Comment by nikomatsakis** [comment]
I'm sort of tempted to close one or the other as a duplicate, in fact.

**Comment by nikomatsakis** [comment]
Adding to RC 2 milestone as a "nice to have", though I think we should merge with #54015

**Comment by pnkfelix** [comment]
This is fixed, presumably by PR #54343

**Comment by pnkfelix** [comment]
I spoke too soon.

The current output, according to [play](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2015&gist=ec4e521f3ec7029816198f0d79584a37), is:

```
error[E0713]: borrow may still be in use when destructor runs
  --> src/main.rs:24:22
   |
24 |         members.push(child.raw);
   |                      ^^^^^^^^^
25 |     }
   |     - here, drop of `child` needs exclusive access to `*child.raw`, because the type `C<'_>` implements the `Drop` trait
26 |     members.len();
   |     ------- borrow used here, in later iteration of loop

error: aborting due to previous error
```

so, we still have the "in later iteration of loop" in the diagnostic.

**Comment by nikomatsakis** [comment]
Removing from the Rust 2018 Release milestone.

**Comment by nikomatsakis** [comment]
Created a topic for this on zulip ([link](https://rust-lang.zulipchat.com/#narrow/stream/122657-wg-nll/topic/.2353773.20erroneous.20loop.20diagnostic)) and assigned @spastorino

**Comment by pnkfelix** [comment]
NLL triage. P-medium.
