### ISSUE TITLE
Global paths cannot start with `crate`

### ISSUE THREAD

**Issue by cramertj** [rust-lang/rust#53770]
There was a recent regression in the ability to write code like

```rust
use {
    crate::{...},
    ...
};
```

It used to work under the new edition but now reports "failed to resolve. global paths cannot start with `crate`". cc @eddyb, @petrochenkov

**Comment by cramertj** [comment]
Additionally, `use { self::... };` and `use { super::... };` have never worked, and it'd be great if these could be fixed as well (though obviously that's a separate issue from the specific regression here).

**Comment by eddyb** [comment]
One more radical solution (than the immediate "defer insertion of `CrateRoot` until you have the first path segment) is to *never* insert `CrateRoot` on any edition, and instead treat `ModuleOrUniformRoot::UniformRoot` like the result of `resolve_crate_root`, in `resolve_ident_in_module_unadjusted`, when `uniform_paths` is not enabled.
