### ISSUE TITLE
existential impl Trait gets seriously confused about lifetimes, "impl T + 'static" does not satisfy static lifetime

### ISSUE THREAD

**Issue by khuey** [rust-lang/rust#53791]
This is simplified from some real code I have.

```rust
use std::borrow::BorrowMut;
use std::marker::PhantomData;

trait T {}

impl<X> T for Box<X> where X: T {}

struct S<'a> {
    phantom: PhantomData<&'a u32>,
}

struct U;

impl T for U {}

fn f1<'a, R>(_: R) -> impl T + 'static
    where R: BorrowMut<S<'a>>
{
    let f = Box::new(U);
    f
}

fn f2<'a>(s: S<'a>) -> impl T + 'static {
    f1::<S<'a>>(s)
}

fn f1_boxed<'a, R>(_: R) -> Box<T>
    where R: BorrowMut<S<'a>>
{
    let f = Box::new(U);
    f
}

fn f2_boxed<'a>(s: S<'a>) -> Box<T> {
    f1_boxed::<S<'a>>(s)
}
```

The boxed versions compile fine, but the impl Trait version fails with

```
error[E0477]: the type `impl T` does not fulfill the required lifetime
  --> src/lib.rs:23:24
   |
23 | fn f2<'a>(s: S<'a>) -> impl T + 'static {
   |                        ^^^^^^^^^^^^^^^^
   |
   = note: type must satisfy the static lifetime
```

I see this on both stable and 1.30.0-nightly (7061b2775 2018-08-28).

**Comment by estebank** [comment]
I'm not sure if the compiler is supposed to be accepting this code to begin with.

[With NLL enabled](https://play.rust-lang.org/?gist=fcf603b5f16d5b733350033752d8fc33&version=nightly&mode=debug&edition=2015), the diagnostic is slightly more illuminating:

```
error[E0700]: hidden type for `impl Trait` captures lifetime that does not appear in bounds
  --> src/lib.rs:25:24
   |
25 | fn f2<'a>(s: S<'a>) -> impl T + 'static {
   |                        ^^^^^^^^^^^^^^^^
   |
note: hidden type `impl T` captures the lifetime 'a as defined on the function body at 25:7
  --> src/lib.rs:25:7
   |
25 | fn f2<'a>(s: S<'a>) -> impl T + 'static {
   |       ^^
```

Changing either [the return type to `impl T + 'a`](https://play.rust-lang.org/?gist=3e8717a570db27a38fddff3c9c19b4fa&version=nightly&mode=debug&edition=2015) or [the argument type to `'static`](https://play.rust-lang.org/?gist=0ba50ae9317d32ca97dbd80660c89fd0&version=nightly&mode=debug&edition=2015) makes the compile succeed.

**Comment by khuey** [comment]
Sure, but the return value doesn't actually depend on the lifetime 'a.

**Comment by khuey** [comment]
@mbrubeck says this is #42940
