### ISSUE TITLE
ICE in libserialize with incremental build across changed rustc version

### ISSUE THREAD

**Issue by cramertj** [rust-lang/rust#53792]
We're hitting this intermittently in Fuchsia-- it seems like when we update rustc, sometimes the incremental cache isn't cleared out appropriately and it causes ICEs in libserialize. I'm not sure if this counts as "WONTFIX" based on the fact that we're updating between random non-nightly hashes without manually cache-clearing, but it'd be nice if rustc could recognize the mismatch and ignore un-parseable incremental caches, or at least give a better error message.

[Full backtrace](https://gist.github.com/cramertj/d84f1c0b33d1de7bbaee88d7b13570a9)

**Comment by cramertj** [comment]
[Full logs are here](https://gist.github.com/cramertj/7dedfd4fb1bed5325511039832f19463)

**Comment by pnkfelix** [comment]
discussed briefly at compiler team meeting. P-high. Assigning to @michaelwoerister for further investigation.

**Comment by michaelwoerister** [comment]
The compiler will deem a cache directory incompatible if it was produced by a compiler with a different `CFG_VERSION`: https://github.com/rust-lang/rust/blob/994cdd918589535d705177545bf503cd0c3c5148/src/librustc_incremental/persist/file_format.rs#L97-L110

So if you are producing your compiler in some non-standard way, this mechanism might not work for you. I'm happy to take suggestions for a different scheme that is more robust in your case.

**Comment by cramertj** [comment]
@michaelwoerister We produce our compiler using a custom script that runs `./x.py install`. Is there something preventing incremental from using a hash of the current compiler itself? That seems like it would be more robust.

**Comment by michaelwoerister** [comment]
You mean a hash of the `src` directory? Or all the executables and dylibs? It's doable but it would some effort to integrate that into the build system.

**Comment by cramertj** [comment]
Opened https://fuchsia-review.googlesource.com/c/infra/recipes/+/196927 to take care of this on our end.

**Comment by michaelwoerister** [comment]
>  It does seem like a more "robust" approach, in that folks building a custom rustc don't have to become aware of CFG_VERSION through ICEs

Yes, you are certainly right there. If we can find a way of integrating this into the build system in a way that doesn't keep breaking, I'd be happy to switch to this behavior.

**Comment by michaelwoerister** [comment]
Maybe someone from @rust-lang/infra has a good idea how to implement this in bootstrap: What we need is some kind of hash of the compiler's behavior. That could be a hash of its binaries, or it could be a hash of all the files and settings that went into compiling it. We would want to hard-code this hash somewhere, probably into the `rustc` executable. That way all the dylibs could be built (so we can hash them) and then that value would then be available when the `rustc` executable is compiled. Do Cargo build scripts support something like this -- that is, execute a step after dependencies have been built and then set an environment variable for the final `rustc` invocation?

**Comment by alexcrichton** [comment]
Cargo unfortunately doesn't support that sort of execution model, but one thing we could do is have the build system hash `config.toml` perhaps? (or hash its own internal `Config` structure) and then pass that down as an env var? It may be enough to salt a hash at least perhaps.

**Comment by michaelwoerister** [comment]
Would that catch local changes to source code?

**Comment by alexcrichton** [comment]
Ah no, it would not!

**Comment by eddyb** [comment]
Could it be because of missing `git` information?
@cramertj What does `rustc -vV` print, out of one of those builds?

**Comment by pnkfelix** [comment]
triage: discussed in [compiler team meeting](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/subject/weekly.20meeting.202018-09-20/near/134312924).

It sounds like @cramertj identified a workaround for the problem locally, which led us to consider downgrading to P-medium.

Also: It sounds like the bulk of the (potential) work here, and the necessary evaluation of priority, lies with the infrastructure team.

(@michaelwoerister tells me that the compiler changes on their own would be trivial.)

So, removing T-compiler from the issue, delegating its management entirely to T-infra. (Leaving at P-high, but noting that we would not currently object to a downgrade to P-medium...)

**Comment by eddyb** [comment]
@cramertj Depending on how you build Rust, you might be missing commit info in the builds: https://github.com/rust-lang/rust/blob/e5c6575801028f5e089ef2e7720aa1af9d452334/src/bootstrap/config.rs#L635-L636

You want either to set `ignore-git` to `false`, or, better, `channel` to `"nightly"`.

**Comment by eddyb** [comment]
@tkilbourn in the #fuchsia IRC channel gave me a `rustc -vV` sample:
```
% buildtools/linux-x64/rust/bin/rustc -vV
rustc 1.30.0-dev
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-linux-gnu
release: 1.30.0-dev
LLVM version: 8.0
```
This is *definitely* guaranteed to run into problems.

@alexcrichton I wish we could strike a better balance - maybe cache a git hash when, say, last time libcore was dirty, according to Cargo (so everything *had to* be rebuilt anyway)? Or at least cache it on the first build, and keep reusing it forever until that build dir is cleaned.
I strongly suspect these Fuchsia builds are automated and don't keep a build dir around, so they would get a fresh git hash every time, if we do it this way.

**Comment by cramertj** [comment]
> I strongly suspect these Fuchsia builds are automated and don't keep a build dir around, so they would get a fresh git hash every time, if we do it this way.

Yep, they are automated-- the recipe is [here](https://fuchsia.googlesource.com/infra/recipes/+/master/recipes/rust_toolchain.py).

**Comment by alexcrichton** [comment]
@eddyb sounds like a reasonable strategy to me!
