### ISSUE TITLE
Support `cargo fix` for rename deprecations

### ISSUE THREAD

**Issue by withoutboats** [rust-lang/rust#53802]
Ideally, when a deprecation happens because of a rename, `cargo fix` could rename it for you.

We could make the deprecation warning issue the correct suggestion by adding another field to the `rustc_deprecated` attribute, as in:

```rust
#[rustc_deprecated(renamed = "std::str::str::trim_start")]
```

**Comment by kornelski** [comment]
That would be great. I've used these methods in many places. 

While I like the new names better, I don't feel the need to change the my code, so the deprecation churn is slightly annoying.
