### ISSUE TITLE
not possible to specify ios/macos versions requirements when cross-compiling for ios

### ISSUE THREAD

**Issue by mtak-** [rust-lang/rust#53808]
I want some way to pass these arguments through cargo while doing a cross compile to iOS:
- `miphoneos-version-min`
- `mios-simulator-version-min`
- `mmacos-version-min`

I don't see a way to do accomplish this without breaking either the `build.rs` scripts or the actual cross-compiled code.

Setting the environment variable `MACOSX_DEPLOYMENT_TARGET` will set `mmacos-version-min` for the build.rs scripts (yay) and the cross compiled code (boo - fails to build). The story is the reverse with `IPHONEOS_DEPLOYMENT_TARGET` - breaks build scripts, and works for the cross-compiled code.

Certain libraries like [metal-rs](https://github.com/gfx-rs/metal-rs) have min iOS version requirements greater than iOS 7.0 which appears to be the default, so it'd be pretty handy if there was a way to tweak these flags.

I'm thinking there might be a way using `RUSTC_WRAPPER` or some sort of `.cargo/config`, but I haven't fully investigated it yet.

[#29664](https://github.com/rust-lang/rust/issues/29664) seems a little related.

**Comment by ForceBru** [comment]
So, is there a way to pass these arguments yet? I tried setting `IPHONEOS_DEPLOYMENT_TARGET="12.0"`, but still got the following while building `rustc`:

```
CXXFLAGS_aarch64-apple-ios = Some("-fPIC --target=aarch64-apple-ios -arch arm64 -miphoneos-version-min=7.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk -fembed-bitcode")
```

When I set `CFLAGS="-miphoneos-version-min=12.0"`, this variable changes:

```
CXXFLAGS_aarch64-apple-ios = Some("-fPIC -miphoneos-version-min=12.0 --target=aarch64-apple-ios -arch arm64 -miphoneos-version-min=7.0 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk -fembed-bitcode")
```

But there's still the option `-miphoneos-version-min=7.0`, which comes _after_ the one that's set to `12.0`, so the latter is overridden...

**Comment by ovasquez** [comment]
Any updates about this issue? I'm using the env variable `IPHONEOS_DEPLOYMENT_TARGET` and it's not working.

**Comment by seungillee** [comment]
I'm also curious about this issue. Is there any way to specify minimum ios deployment target version?

**Comment by keith** [comment]
theoretically `IPHONEOS_DEPLOYMENT_TARGET` should control this, any idea where the version is coming from? I believe this is where it's supposed to be handled https://github.com/rust-lang/rust/blob/271dcc1d40b57ad129d88fef1aa7f239308fbfb4/compiler/rustc_target/src/spec/apple_base.rs#L292-L295 and with a quick test I see it working:

```
% cargo build --target aarch64-apple-ios-sim
% otool -lv target/aarch64-apple-ios-sim/debug/lolrust | grep -A2 IOSS
 platform IOSSIMULATOR
    minos 17.0
      sdk 17.0
% IPHONEOS_DEPLOYMENT_TARGET=14.0 cargo build --target aarch64-apple-ios-sim
% otool -lv target/aarch64-apple-ios-sim/debug/lolrust | grep -A2 IOSS
 platform IOSSIMULATOR
    minos 14.0
      sdk 17.0
```

**Comment by madsmtm** [comment]
Triage: I believe the original issue was about setting both `MACOSX_DEPLOYMENT_TARGET` and `IPHONEOS_DEPLOYMENT_TARGET`, this was fixed in https://github.com/rust-lang/rust/pull/64254, so this issue can be closed.

Concretely, the following now works for running build scripts locally with a deployment target of macOS 11, and building the binary with a deployment target of iOS 14:
```console
MACOSX_DEPLOYMENT_TARGET=11.0 IPHONEOS_DEPLOYMENT_TARGET=14.0 cargo build --target aarch64-apple-ios-sim
```
