### ISSUE TITLE
doc ordering seems random

### ISSUE THREAD

**Issue by chisophugis** [rust-lang/rust#53812]
https://doc.rust-lang.org/std/iter/trait.IntoIterator.html#implementors

impl<'a, T> IntoIterator for &'a mut [T; 12]
impl<'a, T> IntoIterator for &'a [T; 25]
impl<'a, T> IntoIterator for &'a mut [T; 21]
impl<'a, T> IntoIterator for &'a [T; 2]
...

this ordering doesn't make any sense and makes the docs harder to navigate.

**Comment by kzys** [comment]
It has been fixed on nightly. The fix will come to stable eventually.
https://doc.rust-lang.org/nightly/std/iter/trait.IntoIterator.html#implementors
