### ISSUE TITLE
rustdoc: [src] links stopped jumping to line

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#53817]
The page at https://doc.rust-lang.org/nightly/std/vec/struct.Vec.html links to https://doc.rust-lang.org/nightly/src/alloc/vec.rs.html#300-303 when clicking [src], but the line numbers are ignored on the latter page: It stays at the top of the page.

This is with Firefox 62 Beta.

**Comment by GuillaumeGomez** [comment]
Already fixed in #53747. Waiting for merge.
