### ISSUE TITLE
Incorrect span for multiline format string with errors

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#53836]
[Given a multiline format string with an unclosed brace](https://play.rust-lang.org/?gist=9b8a0a5d5bcd851014f6572088002ada&version=nightly&mode=debug&edition=2015), the inner span to the format string is shifted 1 character to the right for each newline.

Introduced in #52649.

**Comment by johnfercher** [comment]
I would like to help with this issue. May someone give me some informations about how I can help?

**Comment by estebank** [comment]
@johnfercher I believe one of the uses of `seen_newlines` should be there, which causes the span to be shifter by one for each newline, [possibly this one](https://github.com/rust-lang/rust/pull/52649/files#diff-b1a8cbfd82e0e33a362f270c6cab425eR165).

You should modify [this file](https://github.com/rust-lang/rust/pull/52649/files#diff-281e435541bc22c7246f1f4f81f7f4df) to include the incorrect case in the description, and use `./x.py test src/test/ui --bless` to update the corresponding `stderr` file. You can use `git diff` to see if the change you made is actually doing what you expect it to do.
