### ISSUE TITLE
confusing diagnostic when variable name equals function name

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#53841]
`rustc 1.30.0-nightly (02cb8f2a4 2018-08-29)`
code:
````rust
struct VersionInfo {
    commit_hash: Option<String>,
}

impl VersionInfo {
    pub fn new() -> VersionInfo {
        let commit_hash: Option<String>;

        if false {
            commit_hash = commit_hash();
        } else {
            commit_hash = Some(String::from("bla"));
        }

        VersionInfo {
            commit_hash,
        }
    }
}


fn commit_hash() -> Option<String> {
    Some("hi".to_string())
}
````

This causes a very confusing error message
````
error[E0618]: expected function, found enum variant `commit_hash`
  --> rustc_tools_util/src/lib.rs:11:27
   |
8  |         let commit_hash: Option<String>;
   |             ----------- `commit_hash` defined here
...
11 |             commit_hash = commit_hash();
   |                           ^^^^^^^^^^^^^ not a function
help: `commit_hash` is a unit variant, you need to write it without the parenthesis
   |
11 |             commit_hash = commit_hash;
   |                           ^^^^^^^^^^^
error: aborting due to previous error
````

First, the message talks about "enum variant", does it mean `struct variant`?
Second, I don't get why it does not compile anyway.
If I rename ````commit_hash()```` to ````get_commit_hash()```` it builds, but why can't it figure out that that a var and function are different things even if they have the same name?

Fun fact: 
this doesn't build either
````rust
    pub fn new() -> VersionInfo {
        let commit_hash: Option<String>;
        commit_hash = commit_hash();

        VersionInfo {
            commit_hash,
        }
    }
````
but this does:
````rust
    pub fn new() -> VersionInfo {
        let commit_hash: Option<String> = commit_hash();

        VersionInfo {
            commit_hash,
        }
    }
````

Shouldn't the 2 snippets behave identical?

**Comment by estebank** [comment]
> Shouldn't the 2 snippets behave identical?

They are not because on the second case the local binding `commit_hash` doesn't exist _yet_, so the  mod level `commit_hash` function is not yet shadowed. In the other case, the function `commit_hash` has been shadowed by the local binding, so it fails to compile.

**Comment by matthiaskrgr** [comment]
Just ran into this again with a more simple case :(

````rust
fn a() {}

fn main() {
    let a: bool = false;
    if a {
        a();
    }
}
````
IMO this should compile because we know that  `fn a()` is of type `Fn ..` and not `bool` so `if a` querying the `let a` variable is the only thing that makes sense here..?

The error message is not really helping imo
````
error[E0618]: expected function, found `bool`
 --> src/main.rs:7:9
  |
5 |     let a: bool = false;
  |         - `a` has type `bool`
6 |     if a {
7 |         a();
  |         ^--
  |         |
  |         call expression requires function
  ````
  
  I wonder if type ascription could solve this:
  `  if a: bool { `
