### ISSUE TITLE
Nuke the `const_to_allocation` query

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#53847]
This query is not doing anything anymore and only used in two locations.

Steps for resolving this issue:

1. grep for `const_to_allocation` and remember where the two `tcx.const_to_allocation` calls are
2. remove every mention of it
3. grep for `ConstToAllocation`
4. remove every mentioon of it
5. start building (this takes some time before it hits your use sites, let the computer work in parallel to you)
6. go back to the former call sites and replace them by pattern matching on the argument to extract the necessary data from the `ByRef` and panic if it's not `ByRef`.
7. remove all the comments at the call sites talking about the query
8. open a PR
9. ping @RalfJung on the PR and watch his happiness meter go up

**Comment by RalfJung** [comment]
> go back to the former call sites and replace them by pattern matching on the argument to extract the necessary data from the ByRef and panic if it's not ByRef.

We might just have a small helper function in `librustc_mir/const_eval.rs` doing this extraction. Depends on how often it is used, I guess.

**Comment by RalfJung** [comment]
Happiness meter up :)
