### ISSUE TITLE
Optimize miri engine performance for sanity checks of arrays

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#53845]
The knowledge about all the elements in an array can be used to run a single check instead of running the checks on each element one at a time (suggested in https://github.com/rust-lang/rust/pull/53671#issuecomment-417566432).

This is currently [only done for strings](https://github.com/rust-lang/rust/blob/1114ab684fbad001c4e580326d8eb4d8c4e917d3/src/librustc_mir/interpret/validity.rs#L323), but could just as well be done for arrays of various types with `Scalar` layout.

The E-easy part of this issue is to check for arrays/slices of the builtin integer types and simply verify that there are no relocations in the entire array and that the entire array has no undefined bytes. Should be possible by simply calling https://github.com/rust-lang/rust/blob/1114ab684fbad001c4e580326d8eb4d8c4e917d3/src/librustc_mir/interpret/memory.rs#L740 and checking whether it returned `Ok`. No need to actually check the value.

The E-medium part is to refactor https://github.com/rust-lang/rust/blob/1114ab684fbad001c4e580326d8eb4d8c4e917d3/src/librustc_mir/interpret/validity.rs#L99 to take a bunch of closures which do the final checks. Instead of doing the check for a single memory location, run it for the entire array at once. This means the function won't have https://github.com/rust-lang/rust/blob/1114ab684fbad001c4e580326d8eb4d8c4e917d3/src/librustc_mir/interpret/validity.rs#L101 as an argument anymore, but instead the closures pass around some generic value. E.g https://github.com/rust-lang/rust/blob/1114ab684fbad001c4e580326d8eb4d8c4e917d3/src/librustc_mir/interpret/validity.rs#L110-L113 would be replaced by a closure call, and its result would be fed into the next closure e.g. in https://github.com/rust-lang/rust/blob/1114ab684fbad001c4e580326d8eb4d8c4e917d3/src/librustc_mir/interpret/validity.rs#L166 . Note that https://github.com/rust-lang/rust/issues/53826 should be done before this, otherwise you'll go crazy while attempting to fiddle this refactoring into the current code

**Comment by RalfJung** [comment]
> take a bunch of closures which do the final checks

I have no idea what you are suggesting here. The array field operand iteration is already quite optimized, so for which cases do you expect performance gains here? For non-integer scalars, we still have to actually check every single element for being valid.

Also we have again the question of when to look for the layout vs. the type.

**Comment by RalfJung** [comment]
> Even scalars with a valid range less than the full range require doing the access checks

Oh, I thought you'd only do this for "full-range scalars".

For anything else, the perf win will be smaller, and I am afraid we'll have to start tearing down those beautiful abstractions and make the code ugly. :/
