### ISSUE TITLE
Merge `Promoted` and `Static` variants of `mir::Place`

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#53848]
This would allow merging most of the code in https://github.com/rust-lang/rust/blob/1114ab684fbad001c4e580326d8eb4d8c4e917d3/src/librustc_mir/interpret/place.rs#L470

I suggest to create a single variant (Maybe just leave the `Static` variant), but modify the [`Static` struct](https://github.com/rust-lang/rust/blob/83ddc33347cade429fdb47509818e775a67c1af6/src/librustc/mir/mod.rs#L1727) fields for the `DefId` (update docs that the `DefId` is the one of the containing function in case of a promoted) and additionally add an `Option<Promoted>` field.

**Comment by csmoe** [comment]
I'm working on [changing](https://github.com/rust-lang/rust/pull/53247) the representation of `mir::Place`, since that may take some time to be merged, so block this for easing rebase-stuff at first and this issue will be unblocked as soon as the PR merged.

**Comment by saleemjaffer** [comment]
@oli-obk I would like to take this up.

**Comment by oli-obk** [comment]
Cool! So I think the changes necessary are

1. Remove the `Promoted` variant https://github.com/rust-lang/rust/blob/aa97448caf49ee25271a5ad58482283404b9144f/src/librustc/mir/mod.rs#L1914
2. Add an `Option<Promoted>` field to https://github.com/rust-lang/rust/blob/master/src/librustc/mir/mod.rs#L1920-L1923
3. Recompile and follow the fallout to always create a `Static` variant
    * Everywhere where we used to create `Promoted`, fill in the `Option<Promoted>` with `Some`
    * Everywhere where we used to create `Static`, use `None`
4. Merge the two arms in https://github.com/rust-lang/rust/blob/aa97448caf49ee25271a5ad58482283404b9144f/src/librustc_mir/interpret/place.rs#L586 (this might be a little finicky, so maybe start out by just doing what the current code is doing by differentiating between the `Some` and the `None` case)

**Comment by saleemjaffer** [comment]
@oli-obk 
https://github.com/rust-lang/rust/blob/aa97448caf49ee25271a5ad58482283404b9144f/src/librustc_mir/transform/promote_consts.rs#L289-L298

If i have to replace the `Place::Base(PlaceBase::Promoted(box (promoted_id, ty))) ` with the `PlaceBase::Static` variant, what do I do for the `def_id` for  `PlaceBase::Static`?

**Comment by oli-obk** [comment]
the `DefId` should be the one of the current function. So for now you'll need to give https://github.com/rust-lang/rust/blob/aa97448caf49ee25271a5ad58482283404b9144f/src/librustc_mir/transform/promote_consts.rs#L146 a `DefId` field that refers to the current function. Then you can access the field here
