### ISSUE TITLE
PartialEq example is not symmetric

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#53844]
With https://github.com/rust-lang/rust/pull/51760 landed, the `PartialEq` documentation now at the same time states

> Formally, the equality must be (for all a, b and c):
> *   symmetric: a == b implies b == a; and
> * [...]

And gives an example that is not symmetric: `b1 == BookFormat::Paperback` typechecks, but `BookFormat::Paperback == b1` does not.

Cc @gnzlbg @GuillaumeGomez @steveklabnik

**Comment by gnzlbg** [comment]
I can fix this in #53386 .

**Comment by steveklabnik** [comment]
Triage: that PR was never merged, so this is still open.

**Comment by frewsxcv** [comment]
Opened a PR for this https://github.com/rust-lang/rust/pull/57357
