### ISSUE TITLE
Review and improve HashMap's handling of an empty table

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#53853]
In https://github.com/rust-lang/rust/pull/53804, I fixed the most immediate problem arising from how `HashMap` handles the empty table, but @gnzlbg still (rightly) sees more problems. We still use `1` instead of `NonNull::dangling()` as value for `EMPTY`, and `ptr()` even tests equality with `EMPTY` to return NULL instead. We can't really use non-NULL pointers as [sentinel values like that](https://github.com/rust-lang/rust/pull/52508), and NULL is often a worse choice than an aligned dangling pointer because the latter are at least valid for zero-sized operations.

See [here](https://github.com/rust-lang/rust/pull/53804#discussion_r213964404) for @gnzlbg's suggestions.

**Comment by Mark-Simulacrum** [comment]
I'm going to close this issue since our hash maps are now a thin wrapper around hashbrown which hopefully doesn't suffer from these issues; if it does, this should be refiled upstream. A cursory examination didn't find any obvious problems for sentinel use of dangling or so.

**Comment by gnzlbg** [comment]
Yes none of this applies to the new hashbrown impl. cc @Amanieu in case they want to re-read the comments and any of that rings a bell, but I haven't see anything like that in hashbrown.

**Comment by Amanieu** [comment]
I agree, I don't think any of this applies to hashbrown.
