### ISSUE TITLE
A run-pass test has conflicting repr hints

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#53857]
The following code hits the lint that warns about conflicting `repr` hints on a datatype.

https://github.com/rust-lang/rust/blob/c2afca36672a85248f4da3e8db8cdfac198ad4ad/src/test/run-pass/issue-39720.rs#L15-L23

(I'm just filing this ticket so I have something to point at from a PR for #53764.)

**Comment by Enselic** [comment]
Fixed by https://github.com/rust-lang/rust/pull/67770/files#diff-4a4d51d87ccad2714c791293302c0b146e8c9292fbf59bbfddd5a927b78dcf2c
