### ISSUE TITLE
Allow user not to install llvm shared object

### ISSUE THREAD

**Issue by Keruspe** [rust-lang/rust#53852]
Current rust nightly installs `/usr/lib/libLLVM-7.so`. This will cause conflict with the system-provided llvm as soon as llvm 7 is packaged.
It is thus impossible to use the rust-provided llvm in a future-proof way for system packages, making it mandatory to use the system-provided llvm (lacking rust patches).

It would be great to provide a way to use static linking like before (even if that means duplicating work with the thinLTO stuff).

**Comment by nagisa** [comment]
We probably should link LLVM into the backend shared library statically.

**Comment by cuviper** [comment]
This is a consequence of #53245 which started linking LLVM tools dynamically and #53828 which moved libLLVM to the main rustc component to be easily shared.  I believe the codegen-backends are still linked statically to LLVM though.
