### ISSUE TITLE
For same type, same trait implementation in different modules,  produce 'conflicting implementation for'. Clash across modules boundaries.

### ISSUE THREAD

**Issue by cheblin** [rust-lang/rust#53862]
```Rust
struct Bar(i32);

mod a {
    pub fn same_name() {} ///  isolated

    use ::std::io::*;
    impl Read for super::Bar { //clash
        fn read(&mut self, buf: &mut [u8]) -> Result<usize> {
            Ok(0)
        }
    }
}

mod b {
    pub fn same_name() {} ///  isolated

    use ::std::io::*;
    impl Read for super::Bar {  //clash
        fn read(&mut self, buf: &mut [u8]) -> Result<usize> {
            Ok(0)
        }
    }
}

fn main() {
}
```

[Compiler on this code](https://play.rust-lang.org/?gist=7bf8178359e95dd782972230f9f313ab&version=nightly&mode=debug&edition=2015) issue following error
```
error[E0119]: conflicting implementations of trait `std::io::Read` for type `Bar`:
  --> src\main.rs:20:5
   |
8  |     impl Read for super::Bar {
   |     ------------------------ first implementation here
...
20 |     impl Read for super::Bar {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^ conflicting implementation for `Bar`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0119`.
```

**Comment by sfackler** [comment]
The location of an implementation does not matter. `Bar` implements `Read` in all contexts regardless of what module the `impl Read for Bar` is in.

**Comment by cheblin** [comment]
Could you please point me where I can read get exactly this knowledge. Thank you.

Any way I expected dispatching depends on module used, With function it works.
```Rust
mod a {
    pub fn same_name() { println!("mod a") }
}

mod b {
    pub fn same_name() { println!("mod b") }
}

fn main() {
    {
        use a::*;
        same_name();
    }
    {
        use b::*;
        same_name();
    }
}
``` 

> mod a
> mod b
> 
> Process finished with exit code 0

**Comment by Havvy** [comment]
From https://doc.rust-lang.org/reference/items/implementations.html#trait-implementation-coherence, second paragraph:

"Two trait implementations overlap when there is a non-empty intersection of the traits the implementation is for, the implementations can be instantiated with the same type."

Your case is the trivial case where there's one type and one trait in each impl, and they both are equivalent.

In general, associated items are scoped to the item the impl is for, not to the module it is defined in. Privacy of the item containing the impl doesn't even matter.

**Comment by Havvy** [comment]
Closing because, AFAICT, there's nothing actionable here.

@cheblin If you have any more questions regarding this, feel free to ask them here. Otherwise, you can also ask them in users.rust-lang.org, IRC, Discord, Reddit, etc. etc.
