### ISSUE TITLE
Is it idiomatic to use `impl<T> From<T> for Option<T>` in argument position?

### ISSUE THREAD

**Issue by Cyres** [rust-lang/rust#53886]
See [this question on StackOverflow][2] with no answers so far.

This trait is [implemented since 1.12.0][1]:
```rust
impl<T> From<T> for Option<T> {
    fn from(val: T) -> Option<T> {
        Some(val)
    }
}
```

How idiomatic is this as an argument? Consider this example:

```rust
fn do_things(parameters: &Foo, optional_argument: impl Into<Option<Duration>>) {
    let optional_argument = optional_argument.into();
    // use it...
}
```

If you see the documentation, it's (more or less) clear (if you know, that this trait is implemented). But if you see the code, you may be confused:

```rust
do_things(params, Duration::from_millis(100));
```
Is this fine to use or should it be avoided?

  [1]: https://doc.rust-lang.org/std/option/enum.Option.html#impl-From%3CT%3E
  [2]: https://stackoverflow.com/questions/51886379

**Comment by nagisa** [comment]
This is a tracker for the issues in rustc. For support, consider posting your question on [users.rlo](https://users.rust-lang.org/), [stackoverflow](https://stackoverflow.com/), [reddit](https://www.reddit.com/r/rust/), or asking on one of the chat platforms: [#rust on irc.mozilla.org](https://www.rust-lang.org/en-US/community.html#irc-channels), [discord](https://discordapp.com/invite/aVESxV8).

See also [this RFC](https://github.com/rust-lang/rfcs/issues/323), which is postponed indefinitely, but nevertheless has a great amount of discussion around the topic of optional arguments.
