### ISSUE TITLE
Cargo and Rustc Can't seem to find the alloc crate

### ISSUE THREAD

**Issue by BinaryAura** [rust-lang/rust#53889]
I've been trying to learn more about the internals of rust by implementing data structures. I've been following this [article](https://doc.rust-lang.org/nomicon/vec.html), but it calls for using heap::allocate() rustc says heap is unresolved and I found that the heap module is in the alloc crate but, Cargo can't find it, unlike core, and rustc, says the 'alloc' is unresolved.

**Comment by GabrielMajeri** [comment]
The article you mention hasn't been updated in a while, the functions you are looking for are in the [`std::alloc`](https://doc.rust-lang.org/std/alloc/index.html) module.

**Comment by jonas-schievink** [comment]
Closing as a duplicate of https://github.com/rust-lang-nursery/nomicon/issues/83
