### ISSUE TITLE
x.py fix

### ISSUE THREAD

**Issue by zackmdavis** [rust-lang/rust#53896]
#53816 (migrating part of the codebase to use `'_` lifetimes in type names) ended up involving quite a lot of manual text-editing labor because, unfortunately, rustfix doesn't work with `x.py`. (You might think that you could run `cargo fix` on an individual crate, but after supplying [missing feature flags](https://github.com/rust-lang/rust/blob/28bcffead74d5e17c6cb1f7de432e37f93a6b50c/src/libsyntax/feature_gate.rs#L2091-L2095) and environment variables (`RUSTC_ERROR_METADATA_DST`, `CFG_COMPILER_HOST_TRIPLE`), you end up triggering [an assertion](https://github.com/rust-lang/rust/blob/28bcffead74d5e17c6cb1f7de432e37f93a6b50c/src/librustc/ty/sty.rs#L711) that I don't know how to hack around.) It would be nice if there was an `x.py fix` that worked (even if the need won't come up very often).

This issue should probably receive the A-rustbuild, C-feature-request, T-infra, and P-low labels.

**Comment by Mark-Simulacrum** [comment]
Seeing as I believe we'd like to migrate the compiler over to 2018 edition (and probably std?), I think p-medium might be more accurate.

**Comment by ljedrz** [comment]
I've started working on this.
