### ISSUE TITLE
Always output errors after warnings

### ISSUE THREAD

**Issue by darkwater** [rust-lang/rust#53906]
Currently, compiler errors are sometimes output before warnings, which means I'd have to scroll up to view them if there are a lot of warnings. Since errors are more important than warnings, I think they should be immediately visible. In fact, I think warnings such as unused imports are completely irrelevant when the code fails to compile. Besides, the current behaviour is inconsistent and can be confusing.

**Comment by Mark-Simulacrum** [comment]
I think we don't want to do this as it means we'd need to buffer errors which may lead to the error not being seen for a long time (whereas we could've shown it a while back) when compiling large crates. Thanks for the suggestion though!

**Comment by darkwater** [comment]
How about an option to disable warnings after an error has occurred, then? Warnings before the first error will still be shown, and there should be a message like "Further warnings are suppressed".

**Comment by Mark-Simulacrum** [comment]
If you're expecting lots of warnings, then `#![allow(warnings)]` would work (or `RUSTFLAGS="-Awarnings" cargo ...`)
