### ISSUE TITLE
Testing polling for rfcbot, take 3

### ISSUE THREAD

**Issue by joshtriplett** [rust-lang/rust#53915]
This is a test issue for rfcbot, please ignore.

**Comment by joshtriplett** [comment]
@rfcbot poll cargo Test poll, please ignore.

**Comment by joshtriplett** [comment]
@rfcbot poll lang Test poll, please ignore

What happens with a second poll in the same issue?

**Comment by estebank** [comment]
@joshtriplett can this be closed?
