### ISSUE TITLE
Tracking issue for RFC 2471, "Add lint warning for inner function marked as `#[test]`"

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#53911]
This is a tracking issue for the RFC "Add lint warning for inner function marked as `#[test]`" (rust-lang/rfcs#2471).

**Steps:**

- [x] Implement the RFC
- [ ] Is there anything left to do?

**Unresolved questions:**

None

**Comment by estebank** [comment]
I believe we can close this as is. The linked PR was all needed to satisfy the RFC as it stands.
