### ISSUE TITLE
Testing polling for rfcbot take 2

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#53914]
Follow up issue to https://github.com/rust-lang/rust/issues/53421.

**Comment by Centril** [comment]
@rfcbot poll lang Lorem ipsum?

**Comment by joshtriplett** [comment]
@rfcbot poll cargo Testing polling, please ignore.

**Comment by Centril** [comment]
@rfcbot poll T-cargo Testing polling, please ignore.

**Comment by Centril** [comment]
@rfcbot poll compiler, lang Testing polling, please ignore.

**Comment by Centril** [comment]
Let's test the same team again.

@rfcbot poll lang Lorem ipsum?

**Comment by estebank** [comment]
@Centril can this be closed?

**Comment by Centril** [comment]
@estebank Sure; I'll make new issues if need be. :)
