### ISSUE TITLE
Type error refers to wrong type

### ISSUE THREAD

**Issue by Boscop** [rust-lang/rust#53923]
I had this code:
```rust
    if let Some(mode) = self.active_automations.get(&p) {
        for (i, &ap) in MAP_AUTOMATION.iter() {
            use self::AutomationMode::*;
            use self::AutomationParam::*;
            let val = match (ap, mode) {
                (ApInc, Inc(step)) => step,
                _ => 0.,
            };
            device.set_encoder(i, val);
        }
    }
```

which caused this error:
```
error[E0308]: match arms have incompatible types
   --> src\devices\bcr\mod.rs:530:16
    |
530 |                       let val = match (ap, mode) {
    |  _______________________________^
531 | |                         (ApInc, Inc(step)) => step,
532 | |                         _ => 0.,
    | |                              -- match arm with an incompatible type
533 | |                     };
    | |_____________________^ expected &f32, found floating-point variable
    |
    = note: expected type `&f32`
               found type `{float}`
```

But the actual error was that `mode` is a ref but should be a value, i.e. I should have written `&` before `mode` like:
```rust
    if let Some(&mode) = self.active_automations.get(&p) {
```
(or `let val = match (ap, *mode) {`).

Btw, `ap` and `*mode` are both enum types, only `step` is a f32, so the error that `rustc` is showing is wrong here.

**Comment by csmoe** [comment]
```rust
let val = match (ap, mode) {
    (ApInc, Inc(step)) => step,  // &f32
    _ => 0.,  // f32
};
```
your matching arm is incompatible indeed(`&f32` vs `f32`), the error message exactly complained this.
what's your point of `Type error refers to wrong type`?

**Comment by Boscop** [comment]
Ah right, with `match_default_bindings`, `step` is `&f32`.
I forgot that `match_default_bindings` is always on now..
(I intentionally never enabled that when it was an optional feature, because I want to be explicit instead.)
