### ISSUE TITLE
1_u32.pow(5) == 1_u32.pow(5) + 64_u32.pow(5) + 128_u32.pow(5) + 192_u32.pow(5)

### ISSUE THREAD

**Issue by Doaxan** [rust-lang/rust#53924]
Is it normal? In the future, this can cause unpredictable missed errors, as in my case.
`fn main() {
    if 1_u32.pow(5) == 1_u32.pow(5) + 64_u32.pow(5) + 128_u32.pow(5) + 192_u32.pow(5) {
        println!("TRUE?")
    }
}`
cargo build --release
Console Output: TRUE?

**Comment by jonas-schievink** [comment]
If you try it in debug mode, you get this:

```
thread 'main' panicked at 'attempt to multiply with overflow', /checkout/src/libcore/num/mod.rs:3535:23
```

Note that these overflow checks are not used in release mode (as they're very costly), so what you're seeing is likely the result of this overflow.

**Comment by ishitatsuyuki** [comment]
Integer overflow is defined as wrapping in release, because checking for them will cause a noticeable slowdown.

It already panic in debug. This is wontfix.

**Comment by nagisa** [comment]
Closing as per comments above.
