### ISSUE TITLE
Invalid crate type should helpfully suggest valid crate type

### ISSUE THREAD

**Issue by Havvy** [rust-lang/rust#53958]
Errornous code: <sub>Yes, it's only a single line</sub>

```rust
#![crate_type = "proc_macro"]
```

Current output:

```
   Compiling playground v0.0.1 (file:///playground)
error: invalid `crate_type` value
 --> src/lib.rs:1:1
  |
1 | #![crate_type = "proc_macro"]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: #[deny(unknown_crate_types)] on by default

error: aborting due to previous error

error: Could not compile `playground`.
```

Expected:

```
   Compiling playground v0.0.1 (file:///playground)
error: invalid `crate_type` value
 --> src/lib.rs:1:1
  |
1 | #![crate_type = "proc_macro"]
  |                 ^^^^^^^^^^^^ did you mean "proc-macro"?
  |
  = note: #[deny(unknown_crate_types)] on by default

error: aborting due to previous error

error: Could not compile `playground`.
```

The change here is that the error is on the value of the attribute and it asks the "did you mean" question that you get when you mistype a variable.

**Comment by phansch** [comment]
I would like to work on this.

From a first look, I would re-use
https://github.com/rust-lang/rust/blob/b7c6e8f1805cd8a4b0a1c1f22f17a89e9e2cea23/src/libsyntax/util/lev_distance.rs#L15

somewhere around here:
https://github.com/rust-lang/rust/blob/b7c6e8f1805cd8a4b0a1c1f22f17a89e9e2cea23/src/librustc_driver/driver.rs#L1476-L1481
