### ISSUE TITLE
Idea: impl chains ("else impls") for when other impls don't match

### ISSUE THREAD

**Issue by Boscop** [rust-lang/rust#53953]
A lot of the possible `impl` surface of a trait can't be `impl`d in today's Rust because of the restrictions placed on `impl`s.
I think it would be useful to have a way to express `if THIS impl doesn't match, try THAT impl`, [in a chain](https://www.reddit.com/r/rust/comments/9ce1t8/blanket_from_impl_woes/e5asj24/), like in PureScript: https://github.com/purescript/purescript/issues/2315

E.g. in Rust:
```rust
impl<.. /* some bounds */> Trait for Foo { ... }
else
impl<.. /* other bounds */> Trait for Foo { ... }
else
impl ...
```

---

It could even be possible to specify `else impl`s for `impl`s defined in dependency crates, if we can refer to them by a name.
That would require named impls, which there is already some demand for:

https://github.com/rust-lang/rfcs/issues/2251

https://internals.rust-lang.org/t/looking-for-rfc-coauthors-on-named-impls/6275

**Comment by oli-obk** [comment]
This is a feature request to change the language and as such needs an RFC. I suggest you discuss this in the internals forum to figure out the caveats and then open an rfc
