### ISSUE TITLE
rustc: Error messages feel like they're backwards

### ISSUE THREAD

**Issue by sethwm** [rust-lang/rust#53965]
This [code snippet] illustrates a problem I've always had with the Rust compiler's error messages:

```
use std::ops::Deref;

fn foo<Inner: Deref<Target=[u8]>, Outer: Deref<Target=[Inner]>>(buf: Outer) {}

pub fn main() {
    let data = [0_u8];
    foo(&&[&data]);
}
```

The compiler error is:

```
error[E0271]: type mismatch resolving `<&&[&[u8; 1]; 1] as std::ops::Deref>::Target == [_]`
 --> src/main.rs:7:5
  |
7 |     foo(&&[&data]);
  |     ^^^ expected reference, found slice
  |
  = note: expected type `&[&[u8; 1]; 1]`
             found type `[_]`
note: required by `foo`
 --> src/main.rs:3:1
  |
3 | fn foo<Inner: Deref<Target=[u8]>, Outer: Deref<Target=[Inner]>>(buf: Outer) {}
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Intuitively, for me, `found` and `expected` are swapped.  I expect the function to be the point of reference, and therefore the `expected` value and I expect the call site to be the candidate, and therefore the `found` value.  However it seems reverse.  Above you can see the `expected` type is the call site's `&[&[u8; 1]; 1]` and the `found` type is the function's `[_]`.  I this often slows me down  when chasing compile errors as I have to stop and mentally reverse my perception about expected and found.

I hesitate to call this a bug, as I think it's a matter of opinion.  But it does feel the opposite of intuitive for me.

```
$ rustc --version
rustc 1.28.0 (9634041f0 2018-07-30)
```

[code snippet]: https://play.rust-lang.org/?gist=33f4e30e4abac0ea1db3ed4352ece0bd&version=stable&mode=debug&edition=2015

**Comment by atorstling** [comment]
I agree. Came here to report the same type of confusing error message for this [code](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=18220b6456c29aef42a8be02e95da21e): 

```
#![feature(trait_alias)]

trait F8 = FnOnce() -> u8;

fn higher<T: F8>(t: T) -> u8 {
    t()
}

fn main() {
    higher(|| 3u16);
}
```

This yields:
```
higher(|| 3u16);
   |     ^^^^^^ expected u16, found u8
```

**Comment by estebank** [comment]
Current output:

```
error[E0271]: type mismatch resolving `<&&[&[u8; 1]; 1] as std::ops::Deref>::Target == [_]`
 --> src/main.rs:7:5
  |
3 | fn foo<Inner: Deref<Target=[u8]>, Outer: Deref<Target=[Inner]>>(buf: Outer) {}
  |    ---                                         -------------- required by this bound in `foo`
...
7 |     foo(&&[&data]);
  |     ^^^ expected slice, found `&[&[u8; 1]; 1]`
  |
  = note: expected slice `[_]`
              found type `&[&[u8; 1]; 1]`
```

```
error[E0271]: type mismatch resolving `<[closure@src/main.rs:10:12: 10:19] as std::ops::FnOnce<()>>::Output == u8`
  --> src/main.rs:10:5
   |
5  | fn higher<T: F8>(t: T) -> u8 {
   |    ------    -- required by this bound in `higher`
...
10 |     higher(|| 3u16);
   |     ^^^^^^ expected `u8`, found `u16`
```
