### ISSUE TITLE
`#[deny]` in expansion of proc macro is ignored

### ISSUE THREAD

**Issue by japaric** [rust-lang/rust#53975]
Affects `proc_macro_bang!` and `#[proc_macro_attr]`

### STR

``` rust
// crate: bar
// proc-macro = true
extern crate proc_macro;
#[macro_use]
extern crate quote;

use proc_macro::TokenStream;

#[proc_macro_attribute]
pub fn bar(_: TokenStream, _: TokenStream) -> TokenStream {
    quote!(
        #[deny(dead_code)]
        fn bar() {}
    ).into()
}

#[proc_macro]
pub fn baz(_: TokenStream) -> TokenStream {
    quote!(
        #[deny(dead_code)]
        fn baz() {}
    ).into()
}
```

``` rust
// crate: baz
// crate-type: rlib

extern crate bar;

use bar::{bar, baz};

#[bar]
const FOO: () = ();

baz!();
```

Compiling this code succeeds

``` console
$ cargo build && echo OK
OK
```

``` console
$ cargo expand | tail -n9
```

``` rust
extern crate bar;

use bar::{bar, baz};

#[deny(dead_code)]
fn bar() {}

#[deny(dead_code)]
fn baz() {}
```

Compiling the expanded code results in two errors, as expected:

``` console
$ cargo build
cargo build
   Compiling foo v0.1.0 (file:///home/japaric/tmp/foo)
warning: unused imports: `bar`, `baz`
 --> src/lib.rs:3:11
  |
3 | use bar::{bar, baz};
  |           ^^^  ^^^
  |
  = note: #[warn(unused_imports)] on by default

error: function is never used: `bar`
 --> src/lib.rs:6:1
  |
6 | fn bar() {}
  | ^^^^^^^^
  |
note: lint level defined here
 --> src/lib.rs:5:8
  |
5 | #[deny(dead_code)]
  |        ^^^^^^^^^

error: function is never used: `baz`
 --> src/lib.rs:9:1
  |
9 | fn baz() {}
  | ^^^^^^^^
  |
note: lint level defined here
 --> src/lib.rs:8:8
  |
8 | #[deny(dead_code)]
  |        ^^^^^^^^^

error: aborting due to 2 previous errors
```

### Meta

```
$ rustc -V
rustc 1.30.0-nightly (1c2e17f4e 2018-09-04)
```

The name of the expanded function is not a problem. Renaming them to e.g. `foo` and `quux` doesn't change the outcome.

cc @alexcrichton @petrochenkov apologies if this has already been reported. I didn't search too hard.

**Comment by alexcrichton** [comment]
This phenomena is currently intentional and a relatively recent change, specifically this code --

https://github.com/rust-lang/rust/blob/780b0c7bbfacc56f59a729881b5c95cd2c61ff97/src/librustc/lint/mod.rs#L619-L633

which was updated in https://github.com/rust-lang/rust/pull/52467

**Comment by japaric** [comment]
Interesting.

On one hand, I like this change because it means I no longer have to sprinkle `#[allow(unsafe_code)]` all over the expansion of my proc macros so that they won't break builds where the user is using `#![deny(unsafe_code)]`. 

On the other hand, I was relying on this to prevent a user error. I have this attribute that turns a function into `#[export_name = ".."] pub fn name(..` and was using `#[deny(dead_code)]` to force the user to make the function *reachable*. If the function is not reachable the symbol won't be external or worst, it could be dropped by the compiler; this would cause linking to fail, or worst linking could succeed but the user function would be ignored. I have written this requirement in the docs but wanted a compile time check because some people don't (carefully) read the API docs.

Ideally, I would be using some feature to make a symbol external regardless of whether is `pub` or reachable or neither and this wouldn't be a problem but such feature doesn't exist AFAIK.

Oh well, I'll write the requirement in **bold** and just deal with the future "why isn't this working?" questions. Thanks for the info.
