### ISSUE TITLE
no method named `report`

### ISSUE THREAD

**Issue by oneforall2** [rust-lang/rust#53986]
libdir: "/tmp/A/build32/rustc-1.28.0-src/build/x86_64-unknown-linux-gnu/stage2/lib"
error[E0599]: no method named `report` found for type `rustc_mir::interpret::EvalContext<'_, '_, '_, Evaluator<'_>>` in the current scope
   --> tools/miri/src/lib.rs:257:17
    |
257 |             ecx.report(&mut e, true, None);
    |                 ^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: Could not compile `miri`.

Caused by:
  process didn't exit successfully: `/tmp/A/build32/rustc-1.28.0-src/build/bootstrap/debug/rustc --crate-name miri tools/miri/src/lib.rs --error-format json --crate-type lib --emit=dep-info,link -C opt-level=2 -C metadata=9efa420ea1992488 -C extra-filename=-9efa420ea1992488 --out-dir /tmp/A/build32/rustc-1.28.0-src/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps --target x86_64-unknown-linux-gnu -L dependency=/tmp/A/build32/rustc-1.28.0-src/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps -L dependency=/tmp/A/build32/rustc-1.28.0-src/build/x86_64-unknown-linux-gnu/stage2-tools/release/deps --extern byteorder=/tmp/A/build32/rustc-1.28.0-src/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/libbyteorder-5273e3c4110ae99a.rlib --extern env_logger=/tmp/A/build32/rustc-1.28.0-src/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/libenv_logger-3df2329b7cabf0d4.rlib --extern lazy_static=/tmp/A/build32/rustc-1.28.0-src/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/liblazy_static-638a76e11b513f2f.rlib --extern log=/tmp/A/build32/rustc-1.28.0-src/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/liblog-6d4dba4432744554.rlib --extern regex=/tmp/A/build32/rustc-1.28.0-src/build/x86_64-unknown-linux-gnu/stage2-tools/x86_64-unknown-linux-gnu/release/deps/libregex-014bb716384ef753.rlib` (exit code: 101)
command did not execute successfully: "/usr/bin/cargo" "build" "--target" "x86_64-unknown-linux-gnu" "-j" "4" "-v" "--release" "--frozen" "--manifest-path" "/tmp/A/build32/rustc-1.28.0-src/src/tools/miri/Cargo.toml" "--features" "" "--message-format" "json"
expected success, got: exit code: 101
  < ToolBuild { compiler: Compiler { stage: 2, host: "x86_64-unknown-linux-gnu" }, target: "x86_64-unknown-linux-gnu", tool: "miri", path: "src/tools/miri", mode: ToolRustc, is_ext_tool: true, extra_features: [] }
< Miri { compiler: Compiler { stage: 2, host: "x86_64-unknown-linux-g

**Comment by oli-obk** [comment]
You're probably building an old miri version. please use the master branch

**Comment by oli-obk** [comment]
If you have further problems, feel free to open an issue in the miri repo
