### ISSUE TITLE
2018 edition - confusing error message when declaring unnamed parameters

### ISSUE THREAD

**Issue by EpicatSupercell** [rust-lang/rust#53990]
This code works correctly on nightly and stable
```rust
trait Trait {
    fn func(u8);
}
```
but not on 2018 edition, where it returns the error
```
error: expected one of `:` or `@`, found `)`
 --> src/main.rs:2:15
  |
2 |     fn func(u8);
  |               ^ expected one of `:` or `@` here
```

Changing it to `func(_: u8)` solves it.
 
Is this an intended change?
I couldn't find anything about it in the edition guide.

**Comment by jonas-schievink** [comment]
Yes, this was done in https://github.com/rust-lang/rust/pull/53612
