### ISSUE TITLE
Integer types ‘to_bytes’ and ‘from_bytes’ docs outdated

### ISSUE THREAD

**Issue by yrp604** [rust-lang/rust#54001]
For example https://doc.rust-lang.org/std/primitive.u64.html#method.to_bytes

The method is now called {to,from}_{le,be,ne}_bytes and the current tracking issue seems to be #52963

**Comment by jebrosen** [comment]
Note that the "nightly" documentation has the correct information, see https://doc.rust-lang.org/nightly/std/primitive.u64.html#method.to_be_bytes

**Comment by sfackler** [comment]
Yep, the docs linked in the original post are for the stable release which does not contain the rename.
