### ISSUE TITLE
No global memory allocator error when testing no_std crate that does link to std

### ISSUE THREAD

**Issue by IsaacWoods** [rust-lang/rust#54010]
I have a no_std crate that imports std when testing:
``` rust
#![no_std]
#![feature(alloc)]

extern crate alloc;

#[cfg(test)]
#[macro_use]
extern crate std;
```

However, I get this error during testing:
```
error: no global memory allocator found but one is required; link to std or add #[global_allocator] t
o a static item that implements the GlobalAlloc trait.
```

Allocating on the heap during testing does appear to work, so I'm assuming this is just a case of the warning still being emitted.

**Comment by zesterer** [comment]
I have the same issue. Any update?

**Comment by sfackler** [comment]
`cargo test` builds the crate both as a library (for doctests) and as a test executable. You only pull in std for the test executable, so the error message could be coming from building as a library.

**Comment by cbeck88** [comment]
I have the same issue, error message seems to be spurious

**Comment by dvdhrm** [comment]
Yeah, the error message is emitted when building the `doctest` library. Funnily enough, it does not cause the build to fail. That is, `cargo test` still continues running and then exits with success (0).

Sadly, there is currently no way to link in a default allocator (or `std` for that matter) for doctests. There is the unstable `doc_cfg` feature that provides `cfg(rustdoc)`, but I don't see how to achieve something similar without relying on unstable features.

I simply use `doctest = false` until this is fixed.

**Comment by RalfJung** [comment]
Related: https://github.com/rust-lang/rust/issues/52243

**Comment by Nemo157** [comment]
> Sadly, there is currently no way to link in a default allocator (or `std` for that matter) for doctests. 

If you don't put `#[no_std]` inside the doctest it will be linked against `std` even when testing a `#[no_std]` crate, you can think of each doctest as a separate crate. If you do want a different allocator you can add a `#[global_allocator]` static like in a normal binary. Even though this error message is printed the doc tests should still be running.

**Comment by RalfJung** [comment]
Also see https://github.com/rust-lang/rust/issues/52243#issuecomment-404088408: the error is basically spurious.
