### ISSUE TITLE
Bounds check on const/static arrays are not eliminated

### ISSUE THREAD

**Issue by kornelski** [rust-lang/rust#54039]
The compiler is smart enough to eliminate bounds check on a slice from a function argument, but not on a slice from a global array.

Here, as expected, `s[index]` bounds check is eliminated after compiler sees `s.get(index+2)` succeed:

```rust
pub fn elide1(s: &[u8], index: u32) -> u8 {
    let index = index as usize;
    if let Some(&len) = s.get(index+2) {
        s[index] 
    } else {0}
}
```

However, the same code, but with `const` array instead of a slice, does have a bounds check:

```rust
const s: [u8; 5] = [1,2,3,4,5];

pub fn elide2(index: u32) -> u8 {
    let index = index as usize;
    if let Some(&len) = s.get(index+2) {
        s[index] 
    } else {0}
}
```

Tested on rustc 1.30.0-nightly (6e0f1cc15 2018-09-05) 

The globals are poisonous for this optimization. `let slice = &global[..];` doesn't help. Even the slice-using function that usually optimizes well, becomes worse if it gets inlined at a call site using a global.

**Comment by nikic** [comment]
This optimizes well on beta. Unless there is some other case where this issue persists, I'd consider this fixed.

**Comment by kornelski** [comment]
Yes, I can confirm it's nice on beta and today's nightly. Thanks!
