### ISSUE TITLE
Cold Structs

### ISSUE THREAD

**Issue by cramertj** [rust-lang/rust#54044]
```rust
#[cold]
struct DonnerParty;

fn main() {
    #[cold] 5;
}
```
Is it intentional that this work? If so, what is it supposed to do? [The reference](https://doc.rust-lang.org/reference/attributes.html#function-only-attributes) lists it as a function-only attribute, but I've always known it to work on expressions like loops as well.

**Comment by petrochenkov** [comment]
A lot of attributes (most of them?) are not validated in any way, neither locations, nor syntax.
So, something like this works as well:
```
#[cold(foo = 10)]
fn f() {}
```
This is a known issue, but I'm not sure there's a single issue about the attribute validation problem in general.

**Comment by Havvy** [comment]
I'll add a line saying that the attribute is allowed on other places in the reference. That said, it'd be nice to make it a warning in the 2018 edition, error by default in the 2021 edition, and removed completely in the 2024 edition.

@petrochenkov Having an actual list of said attributes would be useful for said documentation purposes.

@cramertj You can't put attributes on expressions, only statements or blocks. Are you saying `#[cold]` has an effect when placed on loops? If so, that should _definitely_ be documented as well. I did touch that section recently, mainly by removing it and making new sections for the attributes it contains. https://havvy.net/rust-reference/attributes.html#cold-attribute but I only added information about putting the attribute on associated functions.
