### ISSUE TITLE
【std::process::Command]】 cmd/bash console does not show after build with "windows" subsystem on windows

### ISSUE THREAD

**Issue by di3663** [rust-lang/rust#54053]
after add
```
#![windows_subsystem = "windows"]
```

**Comment by ishitatsuyuki** [comment]
It's not clear what is your desired result, and what's actually happening. Please edit and elaborate in your issue body.

**Comment by RyanSquared** [comment]
From the documentation [here](https://msdn.microsoft.com/en-us/library/fcc1zstk.aspx), this is an intended effect. The `windows_subsystem` attribute is for modifying how Windows should treat the binary. In this case, using the `"windows"` subsystem means that your program is not intended to create a console window. You can re-enable this by using `#![windows_subsystem = "console"]`.

**Comment by di3663** [comment]
I mean how can I execute a console program(of courses not hidden) when "windows" subsystem enabled if this is normal result should be (console hidden) on windows.

Yes, when "windows" subsystem enabled, sunprocess spawned with std::process::Command will not show it's console.

**Comment by di3663** [comment]
thanks for your replies.

**Comment by Archieeeeee** [comment]
> I mean how can I execute a console program(of courses not hidden) when "windows" subsystem enabled if this is normal result should be (console hidden) on windows.
> 
> Yes, when "windows" subsystem enabled, sunprocess spawned with std::process::Command will not show it's console.

Hello, I have the same problem and did you find a solution?
