### ISSUE TITLE
Site doc bug：Rust Programming Book Chinese Version not Accessible

### ISSUE THREAD

**Issue by chenge** [rust-lang/rust#54077]
```
This site cannot be loaded due to a certificate error: 
https://kaisery.gitbooks.io/rust-book-chinese/content/
```
Right version seems to be here:

https://kaisery.github.io/trpl-zh-cn/

**Comment by csmoe** [comment]
thanks, but it's a rust-www issue, please report there.
https://github.com/rust-lang/rust-www
