### ISSUE TITLE
warning: type `__` should have a camel case name such as `CamelCase`

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#54099]
A type with the name `_X` doesn't get a warning, but `__` does.

**Comment by osa1** [comment]
I think this was deliberately done, we even have a test about this (`ui/lint/issue-54099-camel-case-underscore-types.rs`):

```rust
type __ = isize; //~ ERROR type `__` should have a camel case name such as `CamelCase`
```

Should I update the test?

**Comment by eddyb** [comment]
@osa1 Oh this should have a decision then?

**Comment by osa1** [comment]
Alright. I updated my patch, it should now pass the tests. We can merge or close based on the decision.
