### ISSUE TITLE
Functions pointers with associated type parameters can't cast to pointers

### ISSUE THREAD

**Issue by michaelwu** [rust-lang/rust#54094]
```rust
trait Zoo {
    type X;
}

impl Zoo for u16 {
    type X = usize;
}

fn foo(abc: <u16 as Zoo>::X) {}

fn main() {
    let x: *const u8 = foo as _;
}
```

([Playground](https://play.rust-lang.org/?gist=0803ae70e4f8848bf10d3f11174600cc&version=nightly&mode=debug&edition=2015))

Errors:

```
   Compiling playground v0.0.1 (file:///playground)
error[E0605]: non-primitive cast: `fn(<u16 as Zoo>::X) {foo}` as `*const u8`
  --> src/main.rs:13:24
   |
13 |     let x: *const u8 = foo as _;
   |                        ^^^^^^^^
   |
   = note: an `as` expression can only be used to convert between primitive types. Consider using the `From` trait

error: aborting due to previous error

For more information about this error, try `rustc --explain E0605`.
error: Could not compile `playground`.

To learn more, run the command again with --verbose.

```

Seems like this should work.

**Comment by eddyb** [comment]
Huh, what if you cast it to `fn(_)`? That works, right?

**Comment by michaelwu** [comment]
Adding an intermediate cast to `fn(_)` does make it work. [Playground](https://play.rust-lang.org/?gist=aaa46b7d3a84be944db0a95137c5fdc5&version=nightly&mode=debug&edition=2015)

**Comment by eddyb** [comment]
So having a projection in the type, blocks the cast from happening? That's a bit weird.
cc @nikomatsakis @arielb1

**Comment by arielb1** [comment]
The fn_sig function on fn item types is returning unnormalized types directly from the tcx.

Defined in https://github.com/rust-lang/rust/blob/f1aefb48d2ec7ac38a66c964396a5aec729b7a28/src/librustc/ty/sty.rs#L1739-L1747

The relevant call-site is at 
https://github.com/rust-lang/rust/blob/f1aefb48d2ec7ac38a66c964396a5aec729b7a28/src/librustc_typeck/check/cast.rs#L432-L443
