### ISSUE TITLE
Declarative Macros 2.0 places macros at root, not at module level (nightly)

### ISSUE THREAD

**Issue by samsieber** [rust-lang/rust#54112]
I'm assuming that with #35896 (modularization), this is something we'll want to change.

For example, I try 

```rust
#![feature(decl_macro)]

pub mod module {
  pub macro test_macro() {
    println!("hello world");
  }
}
```

And the macro ends up at the root of the documentation, even though with the 2018 edition I access it through "use whatever_crate_its_in::module::test_macro".

**Comment by jyn514** [comment]
Closing as duplicate of https://github.com/rust-lang/rust/issues/74355 - even though this issue is older, that one has more discussion.
