### ISSUE TITLE
libsyntax visitor does not visit the paths in macros

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#54110]
It's a minor point, but the macro struct includes a path:

https://github.com/rust-lang/rust/blob/551244f05b92f90fe327f8f0a6d9a6e674eaab1b/src/libsyntax/ast.rs#L1223-L1228

However, the `walk_mac` helper just ignores this completely:

https://github.com/rust-lang/rust/blob/551244f05b92f90fe327f8f0a6d9a6e674eaab1b/src/libsyntax/visit.rs#L650-L652

As a result — well, a partial result — the early lint checker just ignores this `path` altogether (in particular, `visit_path` is never invoked, and hence `check_path` and friends are not invoked):

https://github.com/rust-lang/rust/blob/551244f05b92f90fe327f8f0a6d9a6e674eaab1b/src/librustc/lint/context.rs#L1119-L1121

This was a contributing factor to https://github.com/rust-lang/rust/issues/53686.

I say that this is a "partial result" because the early lint checker never calls `walk_mac` -- but, really, it *ought* to. And, if it did, and `walk_mac` did what it was supposed to do and walked all the subparts, then everything would be fine.

Adding a hacky fix for now.

**Comment by nikomatsakis** [comment]
cc @Manishearth @oli-obk — Do you agree that the lint visitor ought to change here?

cc @petrochenkov — do the paths in macros have a `NodeId` like other paths? That was one thing I wans't sure of when I tried to push this through.

**Comment by petrochenkov** [comment]
>do the paths in macros have a NodeId like other paths?

No, node ids are assigned during expansion to "final" nodes that will stay in AST after expansion.
