### ISSUE TITLE
Make rustc::middle::region::Scope's fields public...

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#54122]
... and remove [the entire impl block](https://github.com/rust-lang/rust/pull/54032/files/8053f6319a6c18a23a406e12dede7ff158d3d561#diff-eaec58cd2e0c9e0564f2f3f7e417340cR157) for constructing values of type `Scope`

This will cause a lot of fallout throughout the compiler requiring changing `Scope::Foo(x)` to `Scope { id: x, data: ScopeData::Foo }`

cc https://github.com/rust-lang/rust/pull/54032#discussion_r216618208

First https://github.com/rust-lang/rust/pull/54032 needs to get merged though.

**Comment by maxdeviant** [comment]
@oli-obk I can take a look at this, if you'd like 👍
