### ISSUE TITLE
No documentation on why packed types + Drop aren't UB

### ISSUE THREAD

**Issue by ubsan** [rust-lang/rust#54148]
https://play.rust-lang.org/?gist=73b84464abe00fb3564dbe30f10a4da7&version=stable&mode=debug&edition=2015

`<Dropper as Drop>::drop` is passed an unaligned reference to `Dropper`, which is UB.

cc @rust-lang/lang

**Comment by ubsan** [comment]
Ah, nevermind; apparently, we generate a shim that copies the value before calling drop on it. We should document this.

**Comment by eddyb** [comment]
cc @arielb1

**Comment by alercah** [comment]
Is it possible to break it if `Dropper` is immovable?

**Comment by cramertj** [comment]
@alercah @RalfJung just left a comment about that on the [Pin tracking issue](https://github.com/rust-lang/rust/issues/49150#issuecomment-420717470).

**Comment by RalfJung** [comment]
@ubsan what would be a good place to document this? Do we have attribute docs so we can put it with repr(packed)?

Might be worth reopening (and renaming) this issue to track that missing doc.

**Comment by alercah** [comment]
[The reference](https://doc.rust-lang.org/nightly/reference/type-layout.html) seems like the right place for it.

**Comment by ubsan** [comment]
Or the Rustonomicon?

**Comment by alercah** [comment]
I think the long-term vision should be the reference holding normative text, and the 'Nomicon being more of a practical guide. So probably the correct answer is both.

**Comment by steveklabnik** [comment]
re-filing against the reference https://github.com/rust-lang-nursery/reference/issues/488

if anyone wants to put this in the nomicon, they can, but it's optional, IMHO.
