### ISSUE TITLE
Self Profiling Causes ICE With Parallel rustc

### ISSUE THREAD

**Issue by TheDarkula** [rust-lang/rust#54141]
I parallelised `check_crate()` in `src/librustc_passes/rvalue_promotion.rs`. Then ran a test compile on the regex crate with `cargo rustc -- -Z time-passes -Z query-threads=4`.

This caused an ICE saying:
```
thread '<unnamed>' panicked at 'end_activity() was called but a different activity was running', librustc/util/profiling.rs:179:17
```

cc @wesleywiser @Zoxc

**Comment by wesleywiser** [comment]
The self profiler isn't compatible with parallel queries yet. Right now, there's just a singleton instance of the profiler but with parallel queries we probably need one per worker thread stored in TLS or something. At the end, we'll aggregate all the info together and display it.

For now, it's probably a good idea to disable the self profiler if you are using parallel queries.

**Comment by TheDarkula** [comment]
Ah, that explains rustc yelling at me.
Thanks for the info

**Comment by TheDarkula** [comment]
@wesleywiser Awesome! Thanks so much for this.
Now I can get back to work on parallelism :)
