### ISSUE TITLE
diagnostics: better warning in case of let declaration and assignment operator: let y += 4

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#54143]
````rust
fn main() {
    let y = 3;
    let y = y + 4;
````
this code compiles fine, but if I try to use something like let y += 4; rustc has no idea what is going on:
````rust
fn main() {
    let y = 3;
    let y += 4;
}
````
````
    Compiling mul v0.1.0 (file:///tmp/mul)
error: expected one of `:`, `;`, `=`, or `@`, found `+=`
 --> src/main.rs:3:11
  |
3 |     let y += 4;
  |           ^^ expected one of `:`, `;`, `=`, or `@` here
error: aborting due to previous error
````

I wonder if we could figure out that the user wants `let y = y + 4` in this case and suggest it?

**Comment by memoryruins** [comment]
Instead of shadowing, I would first think they meant to type ``y += 4;`` without the ``let``.

**Comment by memoryruins** [comment]
But it that’s assuming too much, then I think your suggestion is better than nothing.

**Comment by JohnTitor** [comment]
The current output:
```
error: can't reassign to an uninitialized variable
 --> src/main.rs:3:11
  |
3 |     let y += 4;
  |           ^^ help: initialize the variable
  |
  = help: if you meant to overwrite, remove the `let` binding
```

The diagnostics have improved by #83062 and others. Closing as fixed.
