### ISSUE TITLE
LTO + opt-level=2 breaks mipsel-unknown-linux-musl

### ISSUE THREAD

**Issue by vi** [rust-lang/rust#54159]
```
memory allocation of 2006167552 bytes failedAborted
```

the program (or at least that part of the program) works if built with opt-level="s" or without lto or on another platform. On some build variations there is a strange `Result::unwrap() on an Err value: Os { code: 21, kind: Other, message: "Is a directory" }` error instead of the allocation failure.

Was building [websocat](https://github.com/vi/websocat), commit "239570d94c1ad127ffc17e097dfbe08c847157f5" with `cargo build --release  --target=mipsel-unknown-linux-musl --features seqpacket,workaround1`, on `rustc 1.30.0-nightly (1c2e17f4e 2018-09-04)`, with linker set to `OpenWrt-SDK-malta-le_gcc-5.3.0_musl-1.1.16.Linux-x86_64/..../mipsel-openwrt-linux-musl-gcc`

There is a coredump file, but gdb in OpenWRT SDK fails to produce usable backtrace from it (even for debugging version in non-errored case).

Is this issue worth additional investigation?

**Comment by workingjubilee** [comment]
It wasn't specified, what does "breaks" mean here? Did it fail to build at all or did websocat fail to run successfully when built?

**Comment by vi** [comment]
@workingjubilee As far as i remember, it was a runtime error when trying to run the resulting executable.

**Comment by workingjubilee** [comment]
Oh. That sounds normal, then? I think? Allocating huge amounts of memory on a memory-constrained platform can happen, and that generally terminates your program, and allocations can also get optimized out or otherwise perturbed by optimizations (though I am surprised at 2 gigabytes, that seems unusual...).

My apologies for only unearthing this during triage quite a while later! If you happen to have the computer you were using to test and can replicate this with recent rustcs, we can possibly take a further look.

**Comment by vi** [comment]
@workingjubilee There is no reason to allocate 2GB of memory in that program. I expect it is to be some codegen problem in LLVM or rustc, leading to undefined behaviour.

**Comment by workingjubilee** [comment]
It _does_ seem also-likely it's a miscompilation leading to a math error ("suddenly the 32-bit platform's code decides to allocate slightly less than 2 to the 31st power bytes of memory" sounds a bit suspicious...)

So sure.

**Comment by vi** [comment]
Tried something similar (using big-endian though) with `openwrt-sdk-21.02.3-malta-be_gcc-8.4.0_musl.Linux-x86_64` and `rustc 1.69.0-nightly (c18a5e8a5 2023-01-25)` and `websocat v1.11.0` - no obvious errors when running (using qemu) the build with LTO and opt-level=2 or =3.

**Comment by workingjubilee** [comment]
Neat! I guess we can close this, then? It probably was one of the (many) MIPS bugs that LLVM fixed in... ~2019, I'm guessing.
