### ISSUE TITLE
have a travis job that makes sure benchmarks don't break

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#54176]
I have seen `./x.py bench` break several times now, would it be possible to have a ci job run (or cargo check?) the benchmarks once to make sure everything compiles?

**Comment by csmoe** [comment]
If I get your point, 
1. create a `/bench` task inside `src/ci/docker` as the existing images like `x86_64-gnu` did(but with some custom modification like `ENV SCRIPT python2.7 ../x.py bench`), 
2. exec `./src/ci/docker/run.sh bench`
