### ISSUE TITLE
MIR inlining should work with any `ty::FnDef` callee operand, not just constants.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#54193]
This code:
https://github.com/rust-lang/rust/blob/994cdd918589535d705177545bf503cd0c3c5148/src/librustc_mir/transform/inline.rs#L96-L97

should not pattern-match on `func`, but rather call its `ty` method to get its type.

What this means is that `let f = foo; f();` should inline as well as `foo()` (but today it doesn't).

cc @nikomatsakis

**Comment by nagisa** [comment]
Actually it should handle both cases, I think. Handling the `func` constant is useful when the type has been erased but constant propagation managed to propagate the actual function anyway.

**Comment by christianpoveda** [comment]
Working on this one :)
