### ISSUE TITLE
Cover reference equality in primitive.reference API docs

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#54197]
This page: https://doc.rust-lang.org/std/primitive.reference.html

It's not obvious that reference equality is accomplished via implicit reference-pointer coercion plus `ptr::eq`. The `ptr::eq` docs mention this, but I would not look there to find reference equality.

The reference primitive page is someplace I would look for info about reference equality. Update this page to discuss reference equality, and link to `ptr::eq`.

**Comment by V1shvesh** [comment]
Can I help with this issue?

**Comment by V1shvesh** [comment]
@brson Still waiting for your reply

**Comment by QuietMisdreavus** [comment]
@V1shvesh Sorry, it looks like @lucasloisp got to this now, in https://github.com/rust-lang/rust/pull/54755.
