### ISSUE TITLE
Silent failure for empty range

### ISSUE THREAD

**Issue by jeffreydecker** [rust-lang/rust#54204]
I've just run into an issue where with trying to for loop over a range where the upper bound is one above the _MAX_ of the primitive represented by _i_ as shown below:

`// i is u8`
`for i in 0..256 {...}`

I understand that in this particular case 0 and 256 are the same, meaning that the range `0..0` and `0..256` with regard to _u8_ are the same. Part of the issue in my opinion is that I'd argue that the above code is also equivalent to the below code:

`// i is u8`
`for i in 0..=255 {...}`

I definitely understand the argument that they aren't so to be fair, if the first example can/will not be supported that's totally reasonable seeing as 256 is outside of the range of a _u8_. 

However, I do think it's reasonable for the compiler to at least bark at you about the first example considering the loop and it's contained code are essentially dead/unreachable code.

My initial proposal would be to just have the compiler at least warn you about the unreachable nature of your code from example 1. My pie in the sky ask would be that the compiler would be smart enough to handle the first example, again though, I do understand why that might not be a popular ask.

**Comment by ExpHP** [comment]
But it *does* bark at you:

```
warning: literal out of range for u8
 --> src/main.rs:4:17
  |
4 |     for i in 0..256 {
  |                 ^^^
  |
  = note: #[warn(overflowing_literals)] on by default
```

**Comment by jeffreydecker** [comment]
Hmmm, you're right! I guess I ran into this within a macro I'm working on so I just don't get some of the compiler stuffs in that case. Must have missed the waring the first time I ran the example outside of a macro. Thanks!

I realized after writing this issue that I also meant to include the example below which does not complain:

`// i is u8`
`for i in 0..0 {...}`

Obviously it's a ridiculous scenario so probably not worth covering but to me `0..0` and `0..256` should probably warn you in the same/a similar way. So maybe warning about unreachable code? 

Either way, thanks for the quick follow up 😸

**Comment by estebank** [comment]
Agree that we should probably add an "empty range" lint for cases like `0..0`.

**Comment by hellow554** [comment]
Related: https://github.com/rust-lang/rust/issues/47213

**Comment by zackmdavis** [comment]
This is covered by Clippy's [`reverse_range_loop` lint](https://rust-lang-nursery.github.io/rust-clippy/master/index.html#reverse_range_loop), which is on #53224's shortlist of Clippy lints to potentially uplift to rustc.

**Comment by estebank** [comment]
Then we can safely close this ticket, as it will be handled by the clippy one.
