### ISSUE TITLE
Improve 'Higher-ranked trait bounds' section of reference

### ISSUE THREAD

**Issue by jeekobu** [rust-lang/rust#54202]
https://doc.rust-lang.org/reference/trait-bounds.html

The last paragraph in particular has English errors and is incomprehensible:

> Higher-ranked lifetimes may also be specified just before the trait, the only end of the following trait instead of the whole bound. This function is difference is the scope of the lifetime parameter, which extends only to the equivalent to the last one.

**Comment by Havvy** [comment]
Refiled as https://github.com/rust-lang-nursery/reference/issues/416
