### ISSUE TITLE
Add ability to check rustc version via cfg_attr

### ISSUE THREAD

**Issue by vityafx** [rust-lang/rust#54220]
I am using diesel and I have to use this thing:

```rust
#![allow(proc_macro_derive_resolution_fallback)]
```

However, it is allowed to use it only in rustc >= 1.29 so it breaks compatibility if I write it so. I'd like to write it as the following:

```rust
#![cfg_attr(
    rustc_version_higher_than(1, 28),
    allow(proc_macro_derive_resolution_fallback)
)]
```

This requires adding such a attribute (`rustc_version_higher_than`) with corresponding checks. If anyone agreed, I'd do it myself, just point me where I can see for such a code as an example and where I can put it.

P.S. For checking is it less (if anyone needs that someday) it would be good just to use `not`:

```rust
#![cfg_attr(
    not(rustc_version_higher_than(1, 28)),
    allow(proc_macro_derive_resolution_fallback)
)]
```

**Comment by cuviper** [comment]
The current state of the art is to check the version in your `build.rs`, perhaps using crates like [`version_check`](https://crates.io/crates/version_check) or [`rustc_version`](https://crates.io/crates/rustc_version), then print your own `"cargo:rustc-cfg=whatever"` to use in your main sources.

The compiler could add something like you suggest, with enough ~~bikeshedding~~ design work, but then you'd have to wait for that compiler release as the minimum version you could ever check for.

**Comment by Centril** [comment]
This is proposed in https://github.com/rust-lang/rfcs/pull/2523.

**Comment by vityafx** [comment]
@cuviper I know that there is a more or less hacky-way of doing this but this should be done via the compiler preprocessor things as I have written above because there must be an easy way of doing this, obviously.

**Comment by Mark-Simulacrum** [comment]
Closing in favor of https://github.com/rust-lang/rfcs/pull/2523.
