### ISSUE TITLE
The help for deprecated panic_implementation attribute is bad

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#54246]
```
warning: use of deprecated attribute `panic_implementation`: This attribute was renamed to `panic_handler`. See https://github.com/rust-lang/rust/issues/44489#issuecomment-415140224
  --> test.rs:13:1
   |
13 | #[panic_implementation]
   | ^^^^^^^^^^^^^^^^^^^^^^^ help: remove this attribute
   |
   = note: #[warn(deprecated)] on by default
```

Namely,

```
   | ^^^^^^^^^^^^^^^^^^^^^^^ help: remove this attribute
```

will not help at all in resolving the issue. The `help` should either not exist at all or suggest replacement to `#[panic_handler]` (moving the suggestion from the warning itself).

**Comment by varkor** [comment]
If anyone'd like to take this on, it should be straightforward.

https://github.com/rust-lang/rust/blob/6bd2d5703d5944def902ec9dca6ea8aae07c8963/src/libsyntax/feature_gate.rs#L720-L724

I think the clearest way to address this is to modify the `Deprecated` type to have a second `Option<&'static str>` field, which is `None` if there is no suggested replacement and `Some(replacement_feature)` if the feature has been deprecated in favour of `replacement_feature`.

You'd then need to update the occurrences of `Deprecated` (in the case of `panic_implementation`, it needs `Some("panic_handler")` — others may also have sensible substitutes) and make this lint:
https://github.com/rust-lang/rust/blob/6bd2d5703d5944def902ec9dca6ea8aae07c8963/src/librustc_lint/builtin.rs#L793-L798
suggest replacing the feature attribute if a substitute exists.

Some tests might also need updating afterwards.

(Also, `This attribute` should be `this attribute` in the `panic_implementation` deprecation notice.)

**Comment by varkor** [comment]
@snaedis: great! Feel free to ask here if you need any help with the fix!

**Comment by snaedis** [comment]
@varkor first stab is ready; feedback would be much appreciated!
