### ISSUE TITLE
Each call of tcx.{declared_,explicit_,}predicates_of clones the GenericPredicate struct, which includes a Vec.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#54274]
Did we forget to intern/`Rc` it? cc @nikomatsakis @arielb1 @nnethercote

**Comment by eddyb** [comment]
Sorry, I got confused. All the functions in `rustc::ty::query` that return `GenericPredicates`.

**Comment by nikomatsakis** [comment]
I've noticed this before but never filed an issue. I think we probably ought to `Rc`, yes.

**Comment by nikomatsakis** [comment]
(Or intern)

**Comment by nnethercote** [comment]
#55778 fixes some of these, the ones that show up in profiles. There are still a couple more that were more annoying to fix.
