### ISSUE TITLE
Rustc internal documentation 404

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rust#54275]
https://doc.rust-lang.org/nightly/nightly-rustc/rustc

![screenshot_2018-09-16 not found](https://user-images.githubusercontent.com/17426603/45597326-cc7bd500-b9ca-11e8-9f24-d7d1a4e7a130.png)

**Comment by Mark-Simulacrum** [comment]
Working on fixing this.

**Comment by bjorn3** [comment]
I believe you are in the middle of uploading it :)

![screenshot_2018-09-16 rustc - rust](https://user-images.githubusercontent.com/17426603/45597469-39906a00-b9cd-11e8-8703-279d8c889429.png)

**Comment by Mark-Simulacrum** [comment]
I believe rustc docs should be completely ready now.

**Comment by bjorn3** [comment]
Confirmed. Thanks for the quick fix!
