### ISSUE TITLE
Stability checker prevents return-position impl trait in the standard library

### ISSUE THREAD

**Issue by scottmcm** [rust-lang/rust#54283]
Previously hit here: https://github.com/rust-lang/rust/pull/52896#issuecomment-409149134 (thanks, eddyb)

The way I hit this in a change I was trying:
```
   Compiling core v0.0.0 (file:///C:/src/rust/src/libcore)
←[0m←[1m←[38;5;9merror←[0m←[0m←[1m←[38;5;15m: This node does not have a stability attribute←[0m
←[0m   ←[0m←[0m←[1m←[38;5;14m--> ←[0m←[0mlibcore\num\f32.rs:604:35←[0m
←[0m    ←[0m←[0m←[1m←[38;5;14m|←[0m
←[0m←[1m←[38;5;14m604←[0m←[0m ←[0m←[0m←[1m←[38;5;14m| ←[0m←[0m    pub fn total_ordered(self) -> impl Ord {←[0m
←[0m    ←[0m←[0m←[1m←[38;5;14m| ←[0m←[0m                                  ←[0m←[0m←[1m←[38;5;9m^^^^^^^^←[0m
```

Instructions from oli-obk in https://github.com/rust-lang/rust/pull/52896#issuecomment-409560629 :

> Should be enough to add an arm to

https://github.com/rust-lang/rust/blob/a2af8667b1a5166137510aeb2aaad9945f81db6d/src/librustc/middle/stability.rs#L356

> for `ItemExistential(ExistTy { parent_fn_id: Some(_) })` which also skips the `check_missing_stability` call

**Comment by hellow554** [comment]
Your bash seems to use some fancy-dancy colors. Sadly github does not support control-sequences. Can you please edit your post and remove them? :)

**Comment by scottmcm** [comment]
@hellow554 Sadly that's what I literally get on windows these days, from x.py:

![image](https://user-images.githubusercontent.com/18526288/45610773-fdcbc380-ba11-11e8-97c3-20406fadf62d.png)

**Comment by ZerothLaw** [comment]
This looks like it is resolved - ran the exact same command @scottmcm used. Should this be closed?

**Comment by scottmcm** [comment]
@ZerothLaw Had you added an `impl Trait` to core when testing?  I hit it with this extra change: https://github.com/scottmcm/rust/commit/af0afa928468597034101e02a6be620e0bb24f03#diff-14f327fd5e3b91eb2e9af0690596d156R604

**Comment by ZerothLaw** [comment]
This seems to now be resolved on latest master branch.

**Comment by TheSirC** [comment]
Should this issue be closed @scottmcm  ?

**Comment by workingjubilee** [comment]
There appear to be many instances of `-> impl FnMut` and others in core, this issue should be closed.

**Comment by Florian-Schoenherr** [comment]
found this randomly on codetribute lol
@scottmcm can you close this? 😄
