### ISSUE TITLE
Illegal Instruction Promoting const panic!

### ISSUE THREAD

**Issue by cramertj** [rust-lang/rust#54305]
[Playground link](https://play.rust-lang.org/?gist=fbb623a0c1b4a200a1567b40b8673756&version=nightly&mode=debug&edition=2015)
```rust
#![feature(min_const_fn, const_panic)]

const fn foo() {
    panic!("")
}

fn main() {
    let _: &'static () = &foo();
}
```

causes an illegal hardware instruction. cc @oli-obk

**Comment by OvermindDL1** [comment]
In debug mode, release mode, or both?  I've seen this happen in release mode because it's undefined behaviour so an optimization pass kills it.

**Comment by matthiaskrgr** [comment]
According to the playground it happens for both, release and debug.

**Comment by oli-obk** [comment]
Yea we need to solve this before stabilization. When failing to generate the promoted static we can insert an actual panic.

**Comment by oli-obk** [comment]
This has been circumvented by https://github.com/rust-lang/rust/pull/53851
