### ISSUE TITLE
Emscripten target spurious internal compiler errors (corrupted double-linked list)

### ISSUE THREAD

**Issue by kvark** [rust-lang/rust#54312]
(I'm not completely sure if it's a Rust bug in the first place, but previously we've had issues with emscripten target linking/compiling, and they were resolved on Rust side, so here we come again).

You can see the error happening in [this travis job](https://travis-ci.org/gfx-rs/gfx/jobs/429764864#L1342):
> Error in `/emsdk_portable/llvm/clang/bin/llc': corrupted double-linked list: 0x000000000379a1e0 ***

According to https://github.com/gfx-rs/gfx/pull/2408, it happens on both wasm32 and asmjs targets, and the error may look different:
- corrupted size vs. prev_size
- double free or corruption (!prev)

**Comment by jonas-schievink** [comment]
Duplicate of https://github.com/rust-lang/rust/issues/47023, as far as I can tell
