### ISSUE TITLE
Mismatched types diagnostic for async fn return type trusts random returns over function signature

### ISSUE THREAD

**Issue by Arnavion** [rust-lang/rust#54326]
With

```rust
#![feature(async_await, futures_api)]

async fn foo() -> i32 {
    if false {
        return Ok(6);
    }

    5
}
```

the errors are:

```
error[E0308]: mismatched types
 --> src/lib.rs:8:5
  |
8 |     5
  |     ^ expected enum `std::result::Result`, found integral variable
  |
  = note: expected type `std::result::Result<{integer}, _>`
             found type `{integer}`

error[E0271]: type mismatch resolving `<impl std::future::Future as std::future::Future>::Output == i32`
 --> src/lib.rs:3:19
  |
3 | async fn foo() -> i32 {
  |                   ^^^ expected enum `std::result::Result`, found i32
  |
  = note: expected type `std::result::Result<{integer}, _>`
             found type `i32`
  = note: the return type of a function must have a statically known size

error: aborting due to 2 previous errors
```

It seems the compiler prefers to trust the `return Ok(6)` line over the function signature, so it ends up marking the function signature and the one return that matches that signature as errors.

In comparison, the diagnostic for regular non-async fns trusts the function signature and flags the `return Ok(6)` as the error.

```rust
fn foo() -> i32 {
    if false {
        return Ok(6);
    }

    5
}
```

```
error[E0308]: mismatched types
 --> src/lib.rs:3:16
  |
3 |         return Ok(6);
  |                ^^^^^ expected i32, found enum `std::result::Result`
  |
  = note: expected type `i32`
             found type `std::result::Result<{integer}, _>`

error: aborting due to previous error
```

This latter diagnostic is much better since the user presumably wrote the function signature intentionally.

---

I hit this while refactoring a large async fn, and it took some time to figure out why the compiler kept insisting that the function should return a `Result` when I had no intention for it to do that - a stray early-return in the middle of the function that was returning an `Ok()`.

**Comment by cramertj** [comment]
The code that lowers `async fn` body doesn't currently get passed the expected return type of the function, instead allowing it to be inferred. I'll take this one-- should be an easy fix.

**Comment by nikomatsakis** [comment]
We decided that this bug is **not blocking** stabilization; confusing though it may be, it's not a severe enough "diagnostic fail" to block stabilization.

**Comment by nikomatsakis** [comment]
Nonetheless, I've tagged this with E-needs-mentor because it seems eminently fixable, even if not a **blocker**.

**Comment by davidtwco** [comment]
Current status of this after #60592 is [in this Zulip topic](https://rust-lang.zulipchat.com/#narrow/stream/187312-t-compiler.2Fwg-async-await/topic/mismatched.20types.20diag.20.2354326/near/165052299).

**Comment by derekdreery** [comment]
I've hit this today and was confused for a while. [Here's a playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=1c5a0aeb94b9a113201a848e771a7260).

**Comment by jonas-schievink** [comment]
This is not limited to closures/generators/async await but seems to occur generally with `impl Trait` in return position:

```rust
trait Tr {
    type A;
}

impl<A> Tr for A {
    type A = A;
}

fn f() -> impl Tr<A=u8> {
    ()
}
```

```
error[E0271]: type mismatch resolving `<() as Tr>::A == u8`
 --> src/lib.rs:9:11
  |
9 | fn f() -> impl Tr<A=u8> {
  |           ^^^^^^^^^^^^^ expected (), found u8
  |
  = note: expected type `()`
             found type `u8`
  = note: the return type of a function must have a statically known size
```

Additionally, the second note is wrong (`()` is `Sized`).

This does not happen when changing the code to use a boxed trait instead (expected and found are in the right order).

**Comment by nikomatsakis** [comment]
We actually solved the *initial* example given ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=e4971122e943bac8b9ec5cba9e6d8aae)):

```rust

async fn foo() -> i32 {
    if false {
        return Ok(6);
    }

    5
}

fn main() { }
```

gives

```
error[E0308]: mismatched types
 --> src/main.rs:3:16
  |
3 |         return Ok(6);
  |                ^^^^^ expected i32, found enum `std::result::Result`
  |
  = note: expected type `i32`
             found type `std::result::Result<{integer}, _>`
```

I think the case that @jonas-schievink is describing is pretty different. I moved it to https://github.com/rust-lang/rust/issues/68561 and I'm closing this issue.
