### ISSUE TITLE
Tracking issue for duration_float

### ISSUE THREAD

**Issue by newpavlov** [rust-lang/rust#54361]
Rust PRs: #52813, #59102

This feature adds the following float related methods to `Duration`:
- `as_secs_f64(&self) -> f64`
- `as_secs_f32(&self) -> f32`
- `from_secs_f64(secs: f64) -> Duration`
- `from_secs_f32(secs: f32) -> Duration`
- `mul_f64(self, rhs: f64) -> Duration`
- `mul_f32(self, rhs: f32) -> Duration`
- `div_f64(self, rhs: f64) -> Duration`
- `div_f32(self, rhs: f64) -> Duration`

`div_duration` methods are tracked in #63139.

**Comment by m-ou-se** [comment]
What needs to happen before this can be stabilized?

**Comment by icefoxen** [comment]
> f64 vs f32

The only sane options are "have versions for both", or "`f64` because it's more general and people can always downcast.

Also, yes, what needs to happen for this to stabilize?

**Comment by newpavlov** [comment]
I guess we probably should rename methods to `as_f64_secs`, `from_f64_secs` and `div_duration_f64`, so we will have an option to add analogous `f32` methods.

**Comment by smokytheangel0** [comment]
What can I do to help?

**Comment by aloucks** [comment]
> I guess we probably should rename methods to `as_f64_secs`, `from_f64_secs` and `div_duration_f64`, so we will have an option to add analogous `f32` methods.

`as_secs_f64` and `from_secs_f64` would be more consistent.

**Comment by ghedo** [comment]
What's left to do to stabilize this feature? Any ETA?

**Comment by icefoxen** [comment]
It *looks* like this is finished and can be marked as stabilized, and so incorporated into the next stable release.  Is there anything I can do to help with that?

**Comment by tyranron** [comment]
Is there any discussion or reasoning of why such duplicative interface was chosen?

It seems that a generic interface like `from_secs<T>(secs: T) -> Duration` will feel more natural/idiomatic for such generics-adopted language like Rust is.

I've found only [this mention](https://github.com/rust-lang/rust/pull/59102#issue-260002954):

> With [`num_traits::Float`](https://docs.rs/num-traits/0.2.6/num_traits/float/trait.Float.html) we could've reduced number of methods by factor of two, but unfortunately it's not part of `std`.

But one can argue that in this situation another add-hoc inner trait can be introduced in `std`.

Would you be so kind to explain the reasoning of current stabilized interface?

**Comment by faern** [comment]
Yeah, having standard library traits for floats and ints implemented by all corresponding types would be good for many places. But this is probably not the place to discuss that in particular.

I also feel this API is very duplicating. My interpretation is that the reasoning behind it is that there is some loss of precision involved with using floats, and people want that to stand out so it does not go unnoticed. See this message and the messages leading up to it: https://github.com/rust-lang/rust/pull/62756#issuecomment-518695524

If there were a `Float` trait then the two extra methods for each operation could at least be joined to one. For example `from_secs_float(secs: impl Float) -> Duration`, and the duplication could be cut in half.

**Comment by shadiakiki1986** [comment]
For future-comers, upgrading to `rustc>=1.38` fixes this
