### ISSUE TITLE
Crater runs for beta 1.30

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#54364]
cc @rust-lang/release

**Comment by pietroalbini** [comment]
@craterbot run name=beta-1.30-1 start=stable end=beta-2018-09-19

**Comment by pietroalbini** [comment]
@craterbot p=10

**Comment by Mark-Simulacrum** [comment]
I think we forgot to set cap lints (e.g. [this](https://crater-reports.s3.amazonaws.com/beta-1.30-1/beta-2018-09-19/reg/cargo-audit-0.5.2/log.txt) should not be build-fail); though there's few enough regressions that it might not matter?

**Comment by pietroalbini** [comment]
I'll triage this tomorrow. And yes, I forgot to set cap-lints :(

**Comment by sgrif** [comment]
Should cap-lints be default?

**Comment by pietroalbini** [comment]
> Should cap-lints be default?

No, because it's only useful for beta runs, not the ones started by the other teams. You can see some discussion about this in https://github.com/rust-lang-nursery/crater/pull/190#issuecomment-369599059

**Comment by pietroalbini** [comment]
@craterbot run name=beta-1.30-2 start=1.29.1 end=beta-2018-09-23 cap-lints=warn

**Comment by Mark-Simulacrum** [comment]
Triage finished. No new "classes" of regressions found; but it would be good to do another run once backports/fixes land for the remaining issues (probably ~Tuesday).

**Comment by Mark-Simulacrum** [comment]
@craterbot run name=1.30-beta.15 start=1.29.2 end=beta-2018-10-13 cap-lints=warn p=1
