### ISSUE TITLE
Improve "self" errors a bit

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/rust#54369]
Currently it looks like this:

```
let self = process_queue.self();
    ^^^^ `self` value is only available in methods with `self` parameter
```

Rewording a bit like "`self` value is a keyword only available in methods with `self` parameter" would read a bit better and would be more explicit.

**Comment by estebank** [comment]
Label emitted in the following two places

https://github.com/rust-lang/rust/blob/3bc2ca7e4f8507f82a4c357ee19300166bcd8099/src/librustc_resolve/lib.rs#L3024-L3025

The easiest change is rewording as proposed. A harder change would be to make it context dependent and figure out wether it is in happening in a `let` binding to provide a more tailored message.

**Comment by raventid** [comment]
Hi, I took an easy path and implemented https://github.com/rust-lang/rust/pull/54495. If you dislike this approach I can redo this, but It feels to me that taking context in account complicates things, plus I'm not sure about wording.
