### ISSUE TITLE
New compiler error in beta: this constant cannot be used, attempted to read undefined bytes

### ISSUE THREAD

**Issue by sdroege** [rust-lang/rust#54387]
Since latest beta (and nightly), some of my crates have errors like the following

```
error: this constant cannot be used
  --> src/udpsrc.rs:47:1
   |
47 | const DEFAULT_CAPS: Option<gst::Caps> = None;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ attempted to read undefined bytes
```

A standalone testcase replicating all the involved types can be found below (depends only on the `libc` crate).

I don't know if the error is valid, but in any case I don't understand what it means so at least the error message could be improved a bit :)

```rust
use std::marker;
use std::ptr;

extern crate libc;
use libc::{c_int, c_uint, c_void, size_t};

#[repr(C)]
pub struct CapsRef(ffi::GstCaps);

pub type Caps = GstRc<CapsRef>;

pub trait MiniObject {}
impl MiniObject for CapsRef {}

pub struct GstRc<T: MiniObject> {
    obj: ptr::NonNull<T>,
    borrowed: bool,
    phantom: marker::PhantomData<T>,
}

mod ffi {
    use super::*;

    #[repr(C)]
    #[derive(Copy, Clone)]
    pub struct GstCaps {
        pub mini_object: GstMiniObject,
    }

    #[repr(C)]
    #[derive(Copy, Clone)]
    pub struct GstMiniObject {
        pub type_: GType,
        pub refcount: c_int,
        pub lockstate: c_int,
        pub flags: c_uint,
        pub copy: GstMiniObjectCopyFunction,
        pub dispose: GstMiniObjectDisposeFunction,
        pub free: GstMiniObjectFreeFunction,
        pub n_qdata: c_uint,
        pub qdata: gpointer,
    }

    pub type GstMiniObjectCopyFunction =
        Option<unsafe extern "C" fn(*const GstMiniObject) -> *mut GstMiniObject>;
    pub type GstMiniObjectDisposeFunction =
        Option<unsafe extern "C" fn(*mut GstMiniObject) -> gboolean>;
    pub type GstMiniObjectFreeFunction = Option<unsafe extern "C" fn(*mut GstMiniObject)>;

    pub type gboolean = c_int;

    pub type GType = size_t;

    pub type gpointer = *mut c_void;

}

const FOO: Option<Caps> = None;

fn main() {
    let _meh = FOO;
}
```

**Comment by csmoe** [comment]
the testcase compiles with `stable-1.29.0`.

**Comment by rkruppe** [comment]
Minimized:

```rust
pub struct GstRc {
    _obj: *const (),
    _borrowed: bool,
}

const FOO: Option<GstRc> = None;

fn main() {
    let _meh = FOO;
}
```

**Comment by pnkfelix** [comment]
Visited during T-compiler meeting. Tentatively assigning to @eddyb for investigation.

**Comment by eddyb** [comment]
cc @RalfJung @oli-obk I can't find anything in the validation code that's reading the wrong thing - it should be able to tell this is a `None`, which has `0` fields.

**Comment by AstralSorcerer** [comment]
I've been looking into this. It seems that the issue stems from [here](https://github.com/rust-lang/rust/blob/master/src/librustc/mir/interpret/value.rs#L34). Specifically, because the niche-filling enum representation is used for `Option<GstRc>` and similar types, and the niche that gets filled is the second field (the `bool`), it is actually the second part of the `ScalarPair` that is defined, not the first.

**Comment by eddyb** [comment]
Ahh, you're right! I don't know why only the second component was special-cased.

**Comment by RalfJung** [comment]
Seems like @oli-obk's quest to keep `Undef` contained within the CTFE engine failed at last. :/

However, in this case nothing should even be trying to convert to a `ConstValue`. So I am not sure if that's really the problem.

**Comment by RalfJung** [comment]
Actually it looks like this is not a `ScalarPair`, but a `Scalar` being undef. At least that's what the line numbers are saying. It does not make much sense though.

**Comment by RalfJung** [comment]
I am working on a fix.

**Comment by eddyb** [comment]
Should this be closed before we get a beta backport?

**Comment by pietroalbini** [comment]
Backported to beta. Closing this.
