### ISSUE TITLE
NLL: lost "borrowed value needs to live until here" (diagnostic regression compared to AST-borrowck)

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#54382]
Spun off of my investigation of #21114, #54556 

Consider this code ([play](https://play.rust-lang.org/?gist=4affed0d73a59d45a9922a17e15c7a9a&version=nightly&mode=debug&edition=2015 )):

```rust
#![cfg_attr(use_nll, feature(nll))]

fn main() {
    {
        let mut _thing1 = D(Box::new("thing1"));
        D("other").next(&_thing1)
    }

    ;
}

#[derive(Debug)]
struct D<T: std::fmt::Debug>(T);

impl<T: std::fmt::Debug>  Drop for D<T> {
    fn drop(&mut self) {
        println!("dropping {:?})", self);
    }
}

impl<T: std::fmt::Debug> D<T> {
    fn next<U: std::fmt::Debug>(&self, _other: U) -> D<U> { D(_other) }
    fn end(&self) { }
}
```

Under AST-borrowck, this emits the diagnostics:

```
Standard Error

   Compiling playground v0.0.1 (/playground)
error[E0597]: `_thing1` does not live long enough
 --> src/main.rs:6:26
  |
6 |         D("other").next(&_thing1)
  |                          ^^^^^^^ borrowed value does not live long enough
7 |     }
  |     - `_thing1` dropped here while still borrowed
8 | 
9 |     ;
  |     - borrowed value needs to live until here
```

under NLL, it only emits this:

```
error[E0597]: `_thing1` does not live long enough
 --> src/main.rs:6:25
  |
6 |         D("other").next(&_thing1)
  |                         ^^^^^^^^ borrowed value does not live long enough
7 |     }
  |     - `_thing1` dropped here while still borrowed
```

In particular, the note 8 "borrowed value needs to live until here" that highlights the semi-colon after the end of the block is no longer emitted.

My current plan for addressing #54556 is to improve diagnostics. The first step in that path, IMO, would be to figure out how to bring back the note about how long the borrowed value needs to live.

**Comment by nikomatsakis** [comment]
Current output:

```
error[E0597]: `_thing1` does not live long enough
 --> src/main.rs:6:25
  |
4 |        {
  |   _____-
  |  |_____|
  | ||
5 | ||         let mut _thing1 = D(Box::new("thing1"));
6 | ||         D("other").next(&_thing1)
  | ||                         ^^^^^^^^ borrowed value does not live long enough
7 | ||     }
  | ||     -
  | ||     |
  | ||_____`_thing1` dropped here while still borrowed
  | |______a temporary with access to the borrow is created here ...
  |        ... and the borrow might be used here, when that temporary is dropped and runs the `Drop` code for type `D`
```

the labels look good, but the spans associated with them -- woah...

**Comment by pnkfelix** [comment]
Hmm I wonder why the temp is being given the span of the whole block rather than the blocks tail expr

**Comment by pnkfelix** [comment]
And likewise, why the drop of the temporary is no longer associated with the span of the semicolon on the whole statement ...

**Comment by pnkfelix** [comment]
Triage: While I do want to address this, I don't think we would feel all that inclined to backport a fix to the beta channel.

So, tagging as P-high, but removing from the Release milestone.

----

Also, I'm going to assign this to myself since I've taken a special interest in issues involving tail expressions of blocks.
