### ISSUE TITLE
Get the eval out of miri engine

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#54395]
> I would prefer if this was named ConstEvalInterpreter or ConstEvalMachine to keep in the spirit of const_eval names while removing "eval" from everywhere in the interpret module.

So, in particular, `EvalContext` should become something else. `InterpContext`? `InterpretContext`?

The actual renaming is pretty easy to do, but there is a high change of conflicts with other PRs, so you should arrange the timing with @oli-obk and @RalfJung.

**Comment by eddyb** [comment]
`InterpretCx` is probably the direction we'd want to go towards.

**Comment by csmoe** [comment]
I prefer `InterpCtxt` which is more consistent with `TyCtxt` for type context.

**Comment by christianpoveda** [comment]
Hi @RalfJung, I'd like to help in this one to get my feet wet. How/when shall we begin?

**Comment by RalfJung** [comment]
We currently have https://github.com/rust-lang/rust/pull/54380 and https://github.com/rust-lang/rust/pull/53821 in flight and I have https://github.com/RalfJung/rust/tree/pointer-provenance lined up. We should wait for these to land, I think... which could take a bit at the current speed. :/

Until then, you could prepare a list of renames. Is there anything in `librustc_mir::interpret` that also has "eval" in its name?

**Comment by christianpoveda** [comment]
Well, according to ripgrep we have `EvalResult`, `EvalErrorKind` and `EvalSnapshot`

**Comment by RalfJung** [comment]
Sounds reasonable. So which new names do we want to pick? `s/Eval/Interp/` sounds reasonable?

**Comment by eddyb** [comment]
FWIW the "latest" convention, that I apparently forgot to try and convert the rest of the compiler to, is the `Cx` suffix for types.

**Comment by eddyb** [comment]
@christianpoveda I'm not sure we needed the `Eval` prefix, except for `EvalResult` - can we do the `io::Result` thing here?

**Comment by christianpoveda** [comment]
Sure :)

**Comment by RalfJung** [comment]
Things sure have calmed down a bit. You should probably work on top of https://github.com/rust-lang/rust/pull/55915 though, that one is I think the most conflict-risky.

But we should first assemble a list of renames that we all are happy with. Which renames to you intend to do?

**Comment by christianpoveda** [comment]
Sure, let me check the source code and I'll put a list

**Comment by kenta7777** [comment]
I'd like to tackle this issue. How shall we begin?

**Comment by oli-obk** [comment]
As a first step you can look for all uses of `EvalContext` and rename them to `InterpretCx`

**Comment by kenta7777** [comment]
As the next step, should I rename `EvalErrorKind` to `InterpretErrorKind` or make a list for renames?

**Comment by eddyb** [comment]
For errors/results, maybe we can do the `io::{Error, Result}` thing and have `interpret::{Error, Result}`?

**Comment by Centril** [comment]
I think that can turn rather ambiguous and contextual in a large codebase like rustc.

**Comment by eddyb** [comment]
It bothers me how much shorter `Miri` is than `Interpret`.
Maybe `IError` and `IResult`?

**Comment by Centril** [comment]
@eddyb `InterpError`?

**Comment by eddyb** [comment]
I have to say that shorter prefixes are ambiguous, and the only other shortenings I can think of involve removing vowels, i.e. `IntrptError`. Nevermind, "interp" only has one non-leading vowel...
So `MiriError` or `InterpError` it is?

**Comment by Centril** [comment]
It is.

**Comment by kenta7777** [comment]
Could I rename `EvalErrorKind` to `InterpError`?
similary, `EvalResult` to `InterpResult`, `EvalSnapshot` to `InterpSnapshot`?

**Comment by kenta7777** [comment]
This is a list for renames.
- [ ] `EvalErrorKind` to `InterpError`
- [ ] `EvalResult` to `InterpResult`
- [ ] `EvalSnapshot` to `InterpSnapshot`
