### ISSUE TITLE
Diagnostic information does not include item attributes

### ISSUE THREAD

**Issue by jrobsonchase** [rust-lang/rust#54400]
Original rustfix issue: https://github.com/rust-lang-nursery/rustfix/issues/147

When rustc outputs warnings like "you don't need this extern crate line anymore, delete it," it doesn't include accompanying attributes. This leads rustfix to apply its suggestion to delete the extern crate line, but leave the attribute, which then gets applied to the next item.

For example:
```rust
#[cfg(unix)]
extern crate nix;

mod foo;
```
becomes
```rust
#[cfg(unix)]

mod foo;
```
which applies the `#[cfg(unix)]` attribute to `mod foo;` which is definitely not what was desired.

**Comment by zackmdavis** [comment]
Here's where we issue the diagnostic:

https://github.com/rust-lang/rust/blob/2fa1390f6c1ca36b0cc1c126e6d295d360f42b6c/src/librustc_typeck/check_unused.rs#L137-L152

_Assuming_ the cfg attribute is actually preserved by earlier passes, then correcting for this case should be easy (look for it in `tcx.get_attrs` and extend the span correspondingly), but I don't remember offhand whether that's true and don't have time to investigate right now. If it isn't, then this is similar-in-spirit to #45216 in that we "just" want the span of an attribute, but would need to do some nontrivial rearchitecting work to make it available.
