### ISSUE TITLE
In beta 1.30.0-beta.2, `cargo test` runs rustdoc with `-Zunstable-options`, which errors

### ISSUE THREAD

**Issue by yarrow** [rust-lang/rust#54437]
In beta 1.30.0-beta.2, `cargo test` runs `rustdoc -Zunstable-options --edition=2018 ...` which errors out with 

> error: the option `Z` is only accepted on the nightly compiler

Using `rustdoc --edition=2018 ...`, omitting the `-Zunstable-options` flag, works as expected.

## Meta
```
cargo --version --verbose
cargo 1.30.0-beta (308b1eabd 2018-09-19)
release: 1.30.0
commit-hash: 308b1eabd6195812b91d646a0292224bb014b449
commit-date: 2018-09-19

rustdoc --version --verbose
rustdoc 1.30.0-beta.2 (7a0062e46 2018-09-19)
binary: rustdoc
commit-hash: 7a0062e46844def0edcd86da1abafafd9cdbbeaf
commit-date: 2018-09-19
host: x86_64-apple-darwin
release: 1.30.0-beta.2
LLVM version: 8.0
```

**Comment by alexcrichton** [comment]
Thanks for the report! This should be fixed on our `beta` branch now and the new beta should become available tonight!

**Comment by yarrow** [comment]
Yay!  I figured this was probably known, but didn't find it on a quick scan.
