### ISSUE TITLE
use rust-gdb with rr?

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#54433]
I could not figure out how to use rust-gdb with rr. I tried e.g. `RUST_GDB='rr replay' rust-gdb` but it just dumps out the usage information from `rr` (same with `RUST_GDB='rr'`). 

Maybe @tromey or @rocallahan knows?

**Comment by rocallahan** [comment]
How about `rr replay -d rust-gdb`?

**Comment by zmitchell** [comment]
I suppose this issue has been forgotten about. `rr replay -d rust-gdb` works now, so I think this issue can be closed.

**Comment by tromey** [comment]
Closing then, thanks.
