### ISSUE TITLE
Using BitAnd<T> for truncation on integer types?

### ISSUE THREAD

**Issue by npmccallum** [rust-lang/rust#54435]
Would rust be willing to take a pull request that implements BitAnd<T> on integer types for all smaller versions of the int?

For example:
```rust
impl BitAnd<u64> for u128 { type Output = u64 }
impl BitAnd<u32> for u128 { type Output = u32 }
impl BitAnd<u16> for u128 { type Output = u16 }
impl BitAnd<u8> for u128 { type Output = u8 }

impl BitAnd<u32> for u64 { type Output = u32 }
impl BitAnd<u16> for u64 { type Output = u16 }
impl BitAnd<u8> for u64 { type Output = u8 }

impl BitAnd<u16> for u32 { type Output = u16 }
impl BitAnd<u8> for u32 { type Output = u8 }

impl BitAnd<u8> for u16 { type Output = u8 }
```

This would enable effortless, correct and infallible truncation in generic contexts. Is this problem sophisticated enough to warrant an RFC?

**Comment by npmccallum** [comment]
(The problem of how to handle `usize` on u32 given its variable size is a corner case...)

**Comment by jonas-schievink** [comment]
Closing because of the issues encountered with the PR https://github.com/rust-lang/rust/pull/54442. This can be prototyped in an external library (like [`cast`](https://docs.rs/cast/0.2.2/cast/)), and might be addressed by https://github.com/rust-lang/rfcs/pull/2484 as well.
