### ISSUE TITLE
Box<dyn ::std::io::Write> is "undeclared module dyn".

### ISSUE THREAD

**Issue by vi** [rust-lang/rust#54439]
Including in current state of 2018 edition.

https://stackoverflow.com/questions/51071925/error-e0433-when-dyn-used-with-absolute-path

Shall there be a special error message and [auto-applicable] suggestion to surround with brackets: `Box<dyn(::std::io::Write)>`?

**Comment by euclio** [comment]
Is this still a problem? I'm not able to reproduce it in the 2018 edition.
