### ISSUE TITLE
Tracking issue for Rust working groups

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#54445]
This is a temporary tracking issue that exists to track the full set of Rust Working Groups. For each working group, we track the chat channel, associated team, as well as a short description of its purpose.

**Definition:** A Rust Working Group is a set of people working at common purpose. Working Groups are associated with a Rust team. Unlike a Rust Team, Working Groups don't have "formal decision making power", though often they are charged with drawing up recommendations, RFCs, or other documents for the teams (which is then intended to make the final decision).

###  Networking services

**Scope:** Focusing on the end-to-end experience for both sync and async networking code, in coordination with the growing ecosystem in this space.
**Contact(s):** @withoutboats and @cramertj

### WebAssembly

**Scope:** Focusing on the end-to-end experience of embedding Rust code in JS libraries and apps via WebAssembly.

**Contact(s):** @fitzgen
**Get involved:** https://github.com/rustwasm/team#get-involved

### CLI Apps

**Scope:** Focusing on the end-to-end experience of writing CLI apps, both large and small, in Rust.

**Contact(s):** @killercup

### Embedded Devices

**Scope:** Focusing on the end-to-end experience of using Rust in resource-constrained environments and non-traditional platforms.

**Contact(s):** @japaric

### WG-NLL

**Scope:** Implementing the new MIR-based borrow check and non-lexical lifetimes. See the [tracking issue](https://github.com/rust-lang/rust/issues/43234) for more information.

**Chat channel:** The [wg-nll stream on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/122657-wg-nll).

**Contact(s):** @nikomatsakis and @pnkfelix

### WG-UCG

**Scope:** Working out the "Unsafe Code Guidelines", which define what kind of behavior unsafe code can and cannot do. The [unsafe-code-guidelines repository][UCG-repo] is where most of the discussion takes place (see the README, which explains the general setup, and the issues).

[UCG-repo]: https://github.com/rust-rfcs/unsafe-code-guidelines/

**Chat channel:** The [wg-unsafe-code-guidelines stream on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/136281-wg-unsafe-code-guidelines) is used for coordination.

**Contact(s):** @nikomatsakis and @avadacatavra

### WG-Grammar

**Scope:** Working out a the official, formal grammar for Rust and validating it against existing implementations.
See the [announcement thread](https://internals.rust-lang.org/t/proposal-grammar-working-group/8442) for more details.

**Chat Channel:** `#wg-grammar` on [Discord]

**Contact(s):** @centril and @qmx

### WG-Traits

**Scope:** Revamping the rustc trait implementation to follow the Chalk approach.

**Chat Channel:** There is a #wg-traits on [Discord], but the group is currently on hiatus until Rust 2018 ships. =)

**Contact(s):** @nikomatsakis

### WG-Compiler-Performance

**Scope:** Improving rustc compilation performance (build times).

**Chat Channel:** There is a #wg-compiler-performance on [Discord], but the group is currently somewhat inactive.

**Contact(s):** @nikomatsakis

### WG-Codegen

**Scope:** Improving code generated by rustc. [Announcement thread](https://internals.rust-lang.org/t/announcing-the-codegen-working-group/7434).

**Chat Channel:** #wg-codegen on IRC and probably elsewhere too.

**Contact(s):** @nox 

[Discord]: https://discord.gg/rust-lang

**Comment by ExpHP** [comment]
The WG-grammar announcement thread link points to a post about a security WG.

**Comment by nikomatsakis** [comment]
Whoops, fixed!

**Comment by nikomatsakis** [comment]
(Also, I expect some things are missing here... I just added what I could think of off the top of my head. We should complete the list.)

**Comment by Havvy** [comment]
There's also embedded, cli, wasm, and net WGs. And perhaps a Windows WG.

**Comment by crlf0710** [comment]
Just for curious, which working group does things like "const generics" or "unsized rvalue" belong to?

**Comment by Havvy** [comment]
Neither of those have working groups.

**Comment by nagisa** [comment]
We also have a codegen WG, I edited the top message with the details.

**Comment by nikomatsakis** [comment]
@Havvy 

> There's also embedded, cli, wasm, and net WGs. 

Duh, forgot the domain working groups. I've added them. Domain leaders, if you want to add contact info, would be appreciated.

**Comment by Havvy** [comment]
I don't have contact info.

**Comment by phansch** [comment]
Should the [dev tool WGs](https://github.com/nrc/dev-tools-team/blob/master/org-chart.md) be mentioned here? There's a bunch of WG channels for those, in the `dev-tools-team` category on discord. I'm not sure if any of them have anyone particular  to contact.

**Comment by fitzgen** [comment]
> ### WebAssembly
> 
> **Scope:** Focusing on the end-to-end experience of embedding Rust code in JS libraries and apps via WebAssembly.
> 
> **Contact(s):** @fitzgen

How to get involved in the Rust and WebAssembly domain WG: https://github.com/rustwasm/team#get-involved

**Comment by nikomatsakis** [comment]
Closing because this information is now available on our web page!

https://www.rust-lang.org/governance/wgs
