### ISSUE TITLE
[1.30 beta] tester crate broken

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#54466]
**This regression will probably be marked as "won't fix". This issue notifies crate authors.**

The `tester` crate doesn't work anymore on 1.30 beta. The rationale for this is in https://github.com/rust-lang/rust/pull/53410#issuecomment-417126544.

* [tester](https://crates.io/crates/tester) `0.4.1` regressed from stable to beta ([build log](https://crater-reports.s3.amazonaws.com/beta-1.30-1/beta-2018-09-19/reg/tester-0.4.1/log.txt)) cc @messense

**Comment by pnkfelix** [comment]
Closing as WONTFIX based on previously linked reasoning, transcribed below for posterity:

> Also @alexcrichton it looks like I broke this: https://crates.io/crates/tester but I don't think that should have ever been allowable in the first place.
>
> It used an implementation detail of how the compiler used `libtest` to test itself, to trick the stable compiler into thinking that `tester` was actually `libtest` and allow it to test itself.
