### ISSUE TITLE
Incomplete warning min_const_fn for unstable trait bounds other than Sized

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/rust#54469]
```rust
#![feature(min_const_fn)]
use std::marker::PhantomData;
pub struct Foo<T>(PhantomData<T>);
pub trait Bar {}
impl<T: Bar> Foo<T> {
    pub const fn foo() -> Self {
        Foo(PhantomData)
    }
}
fn main() {}

```

([Playground](https://play.rust-lang.org/?gist=0cf5d9242ccb701d1c193701a64c717d&version=nightly&mode=debug&edition=2015))

Errors:

```
   Compiling playground v0.0.1 (/playground)
error: trait bounds other than `Sized` on const fn parameters are unstable
 --> src/main.rs:5:6
  |
5 | impl<T: Bar> Foo<T> {
  |      ^

error: aborting due to previous error

error: Could not compile `playground`.

To learn more, run the command again with --verbose.

```

The error should mention which feature has to be enabled to make use of this. The feature is `const_fn`.

cc @oli-obk @eddyb

**Comment by oli-obk** [comment]
Pointing at the `Bar` is hard. It might be multiple bound spread out through where bounds and generics.

We can change the message to "this generic parameter has nontrivial bounds which is not permitted in const fn"

**Comment by gnzlbg** [comment]
FWIW I think that the bigger issue is that the message says that the feature is unstable, but doesn't mention how the feature is actually called. I guessed, and happened to guess just fine, but if `min_const_fn` becomes stable at some point, the error should properly mention which features users have to enable for this on nightly.
