### ISSUE TITLE
[1.30 beta] Cargo does not accept examples with invalid names anymore

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#54479]
Crates with invalid examples were testable before, but not in 1.30 beta.

```
[package]
name = "gfx-rs advanced example"
version = "0.1.0"
```

* [nical/lyon](https://github.com/nical/lyon) regressed from stable to beta ([build log]()) cc @nical 

cc @rust-lang/cargo

**Comment by ehuss** [comment]
This is a consequence of rust-lang/cargo#6021.  To be clear, the target names don't have spaces, just the package name.

**Comment by nical** [comment]
Thanks a lot for the heads up, fixed in https://github.com/nical/lyon/pull/417

**Comment by alexcrichton** [comment]
I'll nominate this for discussion at the next triage meeting, but seeing how @nical had such a quick fix I'm tempted to leave this "locked down" as a result of the change, especially as we only found one related regression!

**Comment by withoutboats** [comment]
We discussed this in the meeting today and decided that it was a bug fix. Package names should not allow spaces.

**Comment by Mark-Simulacrum** [comment]
There's also a number of other packages that regressed because of this (around 10) but the fixes should all be trivial so I agree with the resolution here.
