### ISSUE TITLE
[1.30 beta] Unresolved import errors in a few crates

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#54471]
Some crates are failing in 1.30 beta with errors like this one:

```
 error[E0432]: unresolved import `geometry::Isometry`
   --> /cargo-home/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.15.3/src/base/cg.rs:15:16
    |
 15 | use geometry::{Isometry, IsometryMatrix3, Orthographic3, Perspective3, Point, Point3, Rotation2,
    |                ^^^^^^^^ no `Isometry` in `geometry`. Did you mean to use `isometry`?
```

* [casimir-fdfd](https://crates.io/crates/casimir-fdfd) `0.2.0` regressed from stable to beta ([build log](https://crater-reports.s3.amazonaws.com/beta-1.30-1/beta-2018-09-19/reg/casimir-fdfd-0.2.0/log.txt)) cc @ThomasdenH
* [ipfs-api](https://crates.io/crates/ipfs-api) `0.5.0-alpha2` regressed from stable to beta ([build log](https://crater-reports.s3.amazonaws.com/beta-1.30-1/beta-2018-09-19/reg/ipfs-api-0.5.0-alpha2/log.txt)) cc @ferristseng
  * [world_id](https://crates.io/crates/world_id) `0.1.0` (depends on `ipfs-api`) regressed from stable to beta ([build log](https://crater-reports.s3.amazonaws.com/beta-1.30-1/beta-2018-09-19/reg/world_id-0.1.0/log.txt)) cc @icefoxen
* [riscan-pro](https://crates.io/crates/riscan-pro) `0.2.1` regressed from stable to beta ([build log](https://crater-reports.s3.amazonaws.com/beta-1.30-1/beta-2018-09-19/reg/riscan-pro-0.2.1/log.txt)) cc @gadomski
* [Enet4/propan](https://github.com/Enet4/propan) regressed from stable to beta ([build log](https://crater-reports.s3.amazonaws.com/beta-1.30-1/beta-2018-09-19/gh/Enet4.propan/log.txt)) cc @Enet4 

cc @petrochenkov

**Comment by petrochenkov** [comment]
The root issue is in the `nalgebra` crate and it's something that was fixed between `nalgebra 0.16.0` and `nalgebra 0.16.1`.

**Comment by icefoxen** [comment]
Most of these crates seem to not use `nlagebra` at all.  All of these build logs seem to have something wrong with `serde` involved; for example, `ipfs-api` gets a lot of errors associated with its use of `#[serde(rename_all = "PascalCase")]`, along the lines of:

```

Sep 21 17:09:54.166 INFO kablam! error: cannot determine resolution for the attribute macro `serde`
Sep 21 17:09:54.166 INFO kablam!   --> /cargo-home/registry/src/github.com-1ecc6299db9ec823/nalgebra-0.15.3/src/linalg/symmetric_tridiagonal.rs:16:5
Sep 21 17:09:54.166 INFO kablam!    |
Sep 21 17:09:54.166 INFO kablam! 16 |     serde(
Sep 21 17:09:54.166 INFO kablam!    |     ^^^^^
Sep 21 17:09:54.166 INFO kablam!    |
Sep 21 17:09:54.166 INFO kablam!    = note: import resolution is stuck, try simplifying macro imports
```

All the other build logs appear to have "undefined type or module" along with the error ` import resolution is stuck, try simplifying macro imports`.  Removing the `serde` annotations from `ipfs-api` lets it build successfully, though the protocol it speaks is then incorrect.

**Comment by petrochenkov** [comment]
Yes, `ipfs-api` is a separate case (probably with the same underlying issue in rustc) and it's already tracked separately in https://github.com/rust-lang/rust/issues/54386, the other regressed crates use `nalgebra`.

**Comment by icefoxen** [comment]
Aha, thanks!

**Comment by petrochenkov** [comment]
Minimized:
```rust
#![allow(unused)]

#[macro_use]
extern crate serde_derive;

use self::one::*;
use self::two::*;

mod serde {}

mod one {
    use serde;

    #[derive(Serialize)]
    #[serde]
    struct One;
}

mod two {
    use serde;

    #[derive(Serialize)]
    #[serde]
    struct Two;
}

fn main() {}
```

**Comment by petrochenkov** [comment]
Fixed in https://github.com/rust-lang/rust/pull/54518
All the crates listed in https://github.com/rust-lang/rust/issues/54471#issue-362858527 build successfully now.
