### ISSUE TITLE
[1.30 beta] More chars considered alphanumeric in 1.30

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#54481]
More chars are considered alphanumeric in 1.30 (like `²`), so the test suite of a few crates is failing.

* [munch](https://crates.io/crates/munch) `0.6.0` regressed from stable to beta ([build log](https://crater-reports.s3.amazonaws.com/beta-1.30-1/beta-2018-09-19/reg/munch-0.6.0/log.txt)) cc @utkarshkukreti

**Comment by cuviper** [comment]
This appears to be a deliberate change, #51609.
cc @rust-lang/libs

**Comment by alexcrichton** [comment]
I've put this on our agenda to discuss, thanks for the cc!

**Comment by SimonSapin** [comment]
`char::is_alphanumeric` is only used in munch in a test. The test happened to use `²` as a character where that method was expected to return false, but there doesn’t seem to be a reason why this couldn’t be any other character, like some punctuation. The test is not about alphanumeric-ness, that’s just a `char -> bool` function that happened to be readily available.

I was somewhat ambivalent about #51609, but now that it’s landed I don’t think this particular regression is something to worry about.
