### ISSUE TITLE
[1.30 beta] Missing LLVM shared library

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#54480]
A crate doesn't work anymore because we stopped shipping LLVM as a shared library.

* [rustc-llvm-proxy](https://crates.io/crates/rustc-llvm-proxy) `0.1.1` regressed from stable to beta ([build log](https://crater-reports.s3.amazonaws.com/beta-1.30-1/beta-2018-09-19/reg/rustc-llvm-proxy-0.1.1/log.txt)) cc @denzp

cc @alexcrichton

**Comment by eddyb** [comment]
cc @rust-lang/compiler We should be allowed to break code that bypasses toolchain stability, right?
We don't guarantee what we put in the sysroot, or where it is, and these crates should ideally not even allow themselves to be used outside of nightly.

**Comment by nagisa** [comment]
Similar to https://github.com/rust-lang/rust/issues/48714. Closing.
