### ISSUE TITLE
How to create a custom attribute ?

### ISSUE THREAD

**Issue by yanishoss** [rust-lang/rust#54506]
# How to create a custom attribute ?

Hello, i want to know how to create custom attributes like this:
```rust
#[my_attribute()]
struct Something {
...
}
```

Could you help me ?

**Comment by abonander** [comment]
Since proc macros have recently been stabilized it seems that the guide I wrote for them in the Unstable Book has disappeared, and now we don't really have any public documentation for them. That's unfortunate.

**Comment by abonander** [comment]
@steveklabnik should we just move the old Unstable Book entry for the `proc_macro` feature to TRPL or something?

**Comment by steveklabnik** [comment]
I’ll be writing the chapter this week.

**Comment by steveklabnik** [comment]
Closing as a duplicate of https://github.com/rust-lang/book/issues/1283
