### ISSUE TITLE
Inconsistent syntax between struct and impl.

### ISSUE THREAD

**Issue by kokjo** [rust-lang/rust#54523]
I am pretty new to rust, but the following issue confuses me.

Assume that we have a trait A.
For defining structs we have the following syntax:
`struct Foo<Bar: A> {...}`
but when writing implementations we write:
`impl<Bar: A> Foo<Bar>{...}`
Is it possible to introduce a new syntax for impl? Like:
`impl Foo<Bar: A> {...}`
which would just desugar to the above implementation?

The first implementation syntax seems inconsistent with the struct syntax.

**Comment by varkor** [comment]
Permitting the bounds on `impl` to be emitted is tracked in https://github.com/rust-lang/rust/issues/15872.

**Comment by steveklabnik** [comment]
Yes, additionally, new features like this need to go through an RFC. Closing!
