### ISSUE TITLE
RefCell<Rc<?>> vs Rc<RefCell<?>> in Chapter 15 of the Rust Book

### ISSUE THREAD

**Issue by winstonewert** [rust-lang/rust#54531]
Chapter 15.6 of the Rust Book includes the following code:

```
struct Node {
    value: i32,
    parent: RefCell<Weak<Node>>,
    children: RefCell<Vec<Rc<Node>>>,
}
```

This has a `Rc` inside a `RefCell`, but the pattern in other places and the previous section is put the `RefCell` inside the `Rc`. It would be nice if the book either used the more common idiom or explained why the rationale for not doing it.

**Comment by steveklabnik** [comment]
Can you re-file against https://github.com/rust-lang/book/ please? Thanks!
