### ISSUE TITLE
std::io::Seek's documentation about seeking beyond the end of a stream is confusing

### ISSUE THREAD

**Issue by Xpyder** [rust-lang/rust#54562]
https://doc.rust-lang.org/std/io/trait.Seek.html
std::io::Seek

I got confused by this line and [wasted some people's time](https://internals.rust-lang.org/t/std-seek/8472) over on internals.rust 
> A seek beyond the end of a stream is allowed, but implementation defined.

so after a little discussion it seems like this might be better wording for those of us who are silly
>A seek beyond the end of a stream is allowed, but it is implementation-defined.

The hyphen makes it clear “implementation defined” is a known concept (and matches it’s usage elsewhere) and the “it is” makes it a bit more clear that the full sentence is considered and intentional.

While normally I find brevity improves clarity, in this case if you don’t realize “implementation defined” is a single concept, it sounds like a thought that trailed off after an edit

**Comment by Xpyder** [comment]
Thanks @shepmaster, I know other projects I've worked with have Easy and Documentation as tags so I wasn't sure if you guys might do the same

**Comment by shepmaster** [comment]
Yep, they're just actual labels over on the right ;-)

**Comment by cuviper** [comment]
> wasted some people's time

Don't worry about that!  It's very easy for developers to misjudge whether such descriptions will make sense to the target users.  Pointing these things out is a great way to contribute to documentation.
