### ISSUE TITLE
aarch64-pc-windows-msvc target needs to treat `extern "stdcall"` like `extern "C"`

### ISSUE THREAD

**Issue by froydnj** [rust-lang/rust#54569]
Compiling code like:

https://github.com/jcjones/u2f-hid-rs/blob/ea7244febb010bb8e02c5e01dd6f2b9a0082884a/src/windows/winapi.rs#L22-L49

results in:

```
LLVM ERROR: Unsupported calling convention
```

presumably because `rustc` attempts to translate it into an x86-specific ABI, which the AArch64 backend rightly rejects.

`clang` already ignores `__stdcall` for non-x86 targets:

https://reviews.llvm.org/D36105

I'm not completely sure what the right answer for Rust is.  I think `Target::adjust_abi` is the rough equivalent of the above clang bit and needs to take a few more cases into account for non-x86 Windows:

https://github.com/rust-lang/rust/blob/31789a658bb6b6c78da1f2b99a5f169e4e8b983b/src/librustc_target/spec/mod.rs#L764-L776

@alexcrichton does that sound right?  If so, I'll code up a patch.

**Comment by alexcrichton** [comment]
Sounds like a good place to me!
