### ISSUE TITLE
Missing self_in_typedefs help message

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust#54563]
This code compiles with recent Nightly:

```
#![feature(self_in_typedefs)]
enum Tree { Empty, Node(Box<Self>, i32, Box<Self>) }
fn main() {}
```

If I remove the feature, on Nightly:

```
enum Tree { Empty, Node(Box<Self>, i32, Box<Self>) }
fn main() {}
```

It gives error messages but no suggestion to add the self_in_typedefs feature:

```
error[E0411]: cannot find type `Self` in this scope
 --> ...\test.rs:1:29
  |
1 | enum Tree { Empty, Node(Box<Self>, i32, Box<Self>) }
  |                             ^^^^ `Self` is only available in traits and impls

error[E0411]: cannot find type `Self` in this scope
 --> ...\test.rs:1:45
  |
1 | enum Tree { Empty, Node(Box<Self>, i32, Box<Self>) }
  |                                             ^^^^ `Self` is only available in traits and impls

error: aborting due to 2 previous errors
```

For some other features Rustc gives such help:

```
enum Tree { Empty, Node(Box<Tree>, i32, Box<Tree>) }
fn main() {
    let t = Tree::Node(box Tree::Empty, 0, box Tree::Empty);
}
```

```
error[E0658]: box expression syntax is experimental; you can call `Box::new` instead. (see issue #49733)
 --> ...\test.rs:3:24
  |
3 |     let t = Tree::Node(box Tree::Empty, 0, box Tree::Empty);
  |                        ^^^^^^^^^^^^^^^
  |
  = help: add #![feature(box_syntax)] to the crate attributes to enable
```

**Comment by Centril** [comment]
cc @alexreg and https://github.com/rust-lang/rust/issues/49303

**Comment by estebank** [comment]
The `help` needs to be added here

https://github.com/rust-lang/rust/blob/31789a658bb6b6c78da1f2b99a5f169e4e8b983b/src/librustc_resolve/lib.rs#L2998-L3007

You can see [how such a `help` text was added in the past](https://github.com/rust-lang/rust/commit/383a5df58cf29e640b1b77da301825a5abc86ce7#diff-c2552a106550d05b69d5e07612f0f812R997).

**Comment by alexreg** [comment]
@estebank I noticed there's also `tcx.sess.opts.unstable_features.is_nightly_build()`. I this any different?

**Comment by estebank** [comment]
Nope, if that is available use that one. They should both be the same value.

**Comment by alexreg** [comment]
Okay sure. We don't have a `tcx` in this case though, I later realised, so I'll use your original approach! Ready to merge?
