### ISSUE TITLE
handle user type annotations in NLL for complex patterns

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#54570]
One of the major remaining items for https://github.com/rust-lang/rust/issues/47184 is that we do not handle user-type annotations around "complex patterns", like `let (x, y): (T, U)`. I described my [plan for how to handle this](https://github.com/rust-lang/rust/issues/47184#issuecomment-420041056) in a comment earlier. The basic idea is that a user type annotation should be tracked as not only a type but a series of projection elements that can be applied to that type. Opening this issue to track this particular change.

**Comment by pnkfelix** [comment]
triage of unassigned milestone issues at NLL meeting, assigning to self

**Comment by pnkfelix** [comment]
I am still working on this; my mysteriously stopped working after the rebase that introduced `visit_user_ty` so I think I just messed up my rebase and need to investigate that properly.

**Comment by pnkfelix** [comment]
Still working on this. Decided midway through a rebase that I needed to redo it by hand, but hopefully adopting a less invasive implementation strategy. Will try to report back more over weekend.

**Comment by pnkfelix** [comment]
demoting to 2018 release, in accordance with #47184

**Comment by pnkfelix** [comment]
(my branch is working again, huzzah. Will hopefully post PR soonish. Its a big one so I'm not sure if it will land in time for the release.)
