### ISSUE TITLE
#[target_feature(enable = "avx2")] can be applied to non-functions, but doesn't do anything

### ISSUE THREAD

**Issue by nicokoch** [rust-lang/rust#54584]
[Playground link demonstrating the problem](https://play.rust-lang.org/?gist=3be94bfbac4854bd5bfa98638d4e6bb6&version=stable&mode=release&edition=2015)

[Playground link when it works](https://play.rust-lang.org/?gist=f54e9bd36a36075b2e0fdd7387b70ecf&version=stable&mode=release&edition=2015)

The compiler should tell me that the annotation will not do anything (in the first case)

**Comment by thomwiggers** [comment]
Your example doesn't work anymore, because the playground doesn't require `target_feature(enable="avx2")` to compile/run AVX2 code anymore.

**Comment by jethrogb** [comment]
Issue remains.

cc @gnzlbg
