### ISSUE TITLE
NLL: unused_mut lint triggered by `for _ in <unreachable>`

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#54586]
Consider the following code ([play](https://play.rust-lang.org/?gist=64782aed5cd427f5249c7cba182db7a8&version=nightly&mode=debug&edition=2015)):

```rust
#![feature(nll)]
#![allow(unreachable_code)]

fn main() {
    for _ in { return (); 0..3 } {
    }
}
```

It signals the following diagnostic:

```
warning: variable does not need to be mutable
 --> src/main.rs:5:14
  |
5 |     for _ in { return (); 0..3 } {
  |              --^^^^^^^^^^^^^^^^^
  |              |
  |              help: remove this `mut`
  |
  = note: #[warn(unused_mut)] on by default
```

Which is pretty nonsensical in appearance.

(It almost certainly arises due to a *legitimate* `mut` appeared in the expansion of `for`. We probably just need to check whether a `mut` that has been introduced is due to legitimate source code or if its due to an internal expansion, and use that knowledge when we decide whether to signal the `unused_mut` lint.)

**Comment by pnkfelix** [comment]
putting on the RC2 milestone under the assumption that this should be relatively straight-forward to resolve.

**Comment by varkor** [comment]
This should be fixed in https://github.com/rust-lang/rust/pull/54125, when it's merged.

**Comment by pnkfelix** [comment]
I'm going to also assign @varkor since they have been participating in discussion about this. Even if @varkor makes the main PR, @blitzerr might be helpful in e.g. confirming the quality of the regression test, etc.
