### ISSUE TITLE
1.31 version nightly

### ISSUE THREAD

**Issue by ehuss** [rust-lang/rust#54594]
I noticed the version of nightly is still 1.30, and I was wondering if updating that is waiting for something?  Just slightly confusing, not critical to me.

**Comment by Mark-Simulacrum** [comment]
I think we haven't bumped the beta compiler yet, I'll go ahead and make that PR soon.

**Comment by leonardo-m** [comment]
Why isn't Nightly versions bumped automatically when there's a major point release?

**Comment by cuviper** [comment]
The raw version could simply be bumped as soon as beta is branched from it, but then bumping the bootstrap compiler needs to update `stage0` conditionals.
