### ISSUE TITLE
`impl_trait_in_bindings` fails with `Option<impl Trait>`

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#54600]
This example ICEs:

```rust
#![feature(nll)]
#![feature(impl_trait_in_bindings)]

use std::fmt::Debug;

fn main() {
    let x: Option<impl Debug> = Some(44_u32);
    println!("{:?}", x);
}
```

The reason is that the code which chooses when to "reveal" opaque types looks only for opaque types at the top level (and, oddly, it does so only if ordinary unification fails; having code that branches based on whether unification succeeded is in general a bad idea, so we should fix that too):

https://github.com/rust-lang/rust/blob/c7df1f530b8a88f471e60e933868e7ddf456974d/src/librustc_mir/borrow_check/nll/type_check/mod.rs#L893-L899

More deeply, though, this code is taking a somewhat flawed approach. In particular, it is looking at the results of **inference**, but -- at least presently -- opaque types can end up in the inferred type in one of two ways. (As shown by #54593.) 

For example, one might have a mixture of opaque types that came from a recursive call (and which ought not to be revealed) and opaque types that the user wrote:

```rust
#![feature(nll)]
#![feature(impl_trait_in_bindings)]

use std::fmt::Debug;

fn foo() -> impl Copy {
    if false {
        let x: (_, impl Debug) = (foo(), 22);
    }
    ()
}

fn main() { }
```

The correct way to do this, I suspect, is to leverage the user-type annotations that we are tracking for NLL.

cc @alexreg @cramertj @eddyb

**Comment by nikomatsakis** [comment]
Another relevant example:

```rust
#![feature(nll)]
#![feature(impl_trait_in_bindings)]

use std::fmt::Debug;

fn foo() -> String {
    let x: impl Debug = 22;
    format!("{}", x)
}

fn main() { }
```

This fails to compile, which seems correct, though I'm not sure precisely what semantics we want.

Alternatively, we may want to encode the `impl Debug` sort of thing as a kind of cast that "obscures" the underlying type? Have to think about it.

**Comment by alexreg** [comment]
@nikomatsakis I think the second example works exactly as intended (and as the RFC specifies). It's intuitive to me, at least.

You're right about the first example; that's the wrong way to go about it. I didn't see a better approach at the time though, and I forgot about it while solving other issues. The lowering and type checking is basically okay, that said... it's the NLL borrow checking that's the problem. Which I think is something that requires your expertise, to be honeast.

**Comment by Centril** [comment]
Tagging T-lang due to Niko's notes in https://github.com/rust-lang/rust/issues/54600#issuecomment-424872005.

**Comment by mikeyhew** [comment]
@nikomatsakis 
> another relevant example:

Shouldn't `format!("{}", x)` should be `format!("{:?}", x)`?

**Comment by alexreg** [comment]
@mikeyhew Nope, I think he meant that... since he follows it by sating "This fails to compile, which seems correct". With `{:?}` it actually compiles, as it should. :-)

**Comment by nikomatsakis** [comment]
Hmm before going any further I also want to raise up a few interesting questions. The possibility of `ref` patterns on the left-hand-side with `impl` types in the type is sort of "curious" -- I suspect we just disallow it, so that we can treat the initializer as a "value" (and not a place).

Right now, the initializers can kind of act in two ways. e.g., here, `y` winds up acting as a place expresion and not a value expression:

```rust
let y = 22;
let ref x: u32 = y; // equivalent to `let x = &y;`
```

In principle you could have:

```rust
let ref x: impl Debug = y;
```

and wind up with `x` having the type `&<opaque Debug>`. This may or may not add some complexity — I guess we'll see. If so, we could always disallow `ref` bindings in the patterns when an `impl Trait` type is used as a type ascription.

**Comment by nikomatsakis** [comment]
So what happens when you have a `&dyn Trait` binding today? The answer is that the you wind up in the "coerce types" code:

https://github.com/rust-lang/rust/blob/365b9001e588cf3d91561894b0e44389e31ae000/src/librustc_typeck/check/coercion.rs#L166

Here `a` (the "source") would be the type of the initializer and `b` is some type that includes a `dyn Trait`. This will wind up considering an "unsize coercion":

https://github.com/rust-lang/rust/blob/365b9001e588cf3d91561894b0e44389e31ae000/src/librustc_typeck/check/coercion.rs#L200

This routine is pretty complex and I'll skip over the details (reminds me though that https://github.com/rust-lang/rust/issues/50753 would be really nice to fix). It will however ultimately produce an [`Adjustment`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc/ty/adjustment/struct.Adjustment.html), which will include an [`AdjustKind::Unsize`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc/ty/adjustment/enum.Adjust.html#variant.Unsize) step.

This adjustment is stored alongside the source expression (here, `y`)  and is taken into account when producing MIR:

https://github.com/rust-lang/rust/blob/365b9001e588cf3d91561894b0e44389e31ae000/src/librustc_mir/hair/cx/expr.rs#L81-L85

**Comment by jyn514** [comment]
Triage: the first example still gives an ICE.
```
error: internal compiler error: broken MIR in DefId(0:6 ~ playground[abce]::main) (_1 = Option::<u32>::Some(const 44_u32)): bad assignment (std::option::Option<impl std::fmt::Debug> = std::option::Option<u32>): NoSolution
 --> src/main.rs:7:33
  |
7 |     let x: Option<impl Debug> = Some(44_u32);
  |                                 ^^^^^^^^^^^^
  |
  = note: delayed at compiler/rustc_mir/src/borrow_check/type_check/mod.rs:253:27
```

**Comment by lqd** [comment]
For people following at home, `impl-trait-in-bindings` is on its way of being removed and reimplemented: https://github.com/rust-lang/rust/issues/86729
