### ISSUE TITLE
Regression in Option<NonNull<usize>> memory layout (4 byte -> 8 byte)

### ISSUE THREAD

**Issue by qwerty19106** [rust-lang/rust#54608]
Documentation on [NonNull](https://doc.rust-lang.org/std/ptr/struct.NonNull.html): 
> Option<NonNull<T>> has the same size as *mut T.

But it is false now.

Example code:
``` Rust
#![feature(ptr_internals)]

use std::mem::size_of;
use std::ptr::*;


fn main() {
    println!("size_of::<Option<&usize>             = {}", size_of::<Option<&usize>>());
    println!("size_of::<Option<NonNull<usize>>>    = {}", size_of::<Option<NonNull<usize>>>());
    println!("size_of::<Option<Unique<usize>>>     = {}", size_of::<Option<Unique<usize>>>());
}
```

Result:
```
size_of::<Option<&u8>             = 8
size_of::<Option<NonNull<u8>>>    = 8
size_of::<Option<Unique<u8>>>     = 8
```

Rust version:
```
$ rustc --version
rustc 1.30.0-nightly (4141a4079 2018-09-25)
```

[playground](https://play.rust-lang.org/?gist=4a960cc17e3c6b00541e8ac6c40f4515&version=nightly&mode=debug&edition=2018)

**Comment by kennytm** [comment]
The playground is running on a 64-bit platform which a pointer is 8 byte long. This is only a problem if these returned 8 on a 32-bit platform.

**Comment by hellow554** [comment]
You could have checked that with printing the size of `&u8` ;)

```rust
#![feature(ptr_internals)]

use core::mem::size_of;
use core::ptr::*;


fn main() {
    println!("size_of::<&u8>={}", size_of::<&u8>());
    println!("size_of::<Option<&u8>>={}", size_of::<Option<&u8>>());
    println!("size_of::<Option<NonNull<u8>>>={}", size_of::<Option<NonNull<u8>>>());
    println!("size_of::<Option<Unique<u8>>>={}", size_of::<Option<Unique<u8>>>());
}
```

([Playground](https://play.rust-lang.org/?gist=485e2e713e3c57bed89d36b0ed3e0e1d&version=nightly&mode=debug&edition=2018))

Output:

```
size_of::<&u8>=8
size_of::<Option<&u8>>=8
size_of::<Option<NonNull<u8>>>=8
size_of::<Option<Unique<u8>>>=8

```

**Comment by nagisa** [comment]
Closing as not-a-bug as per comments above.

**Comment by qwerty19106** [comment]
Thanks for your response.
I thought that playground is running on a 32-bit platform.
