### ISSUE TITLE
Failed to compile [T; std::mem::size_of::<U>()]

### ISSUE THREAD

**Issue by tuxzz** [rust-lang/rust#54611]
[This code:](https://play.rust-lang.org/?gist=8804439a7e6e9a03c3ffd664c11389eb&version=stable&mode=debug&edition=2015)

    fn func<T>(x: T)
    where
        T: Copy + Sized
    {
        let _ = [123i32; std::mem::size_of::<T>()];
    }

Compiler raises:

    error[E0277]: the size for values of type `T` cannot be known at compilation time
    --> src/lib.rs:5:22
      |
    5 |     let _ = [123i32; std::mem::size_of::<T>()];
      |                      ^^^^^^^^^^^^^^^^^^^^^^ doesn't have a size known at compile-time

An obvious bug.

**Comment by varkor** [comment]
Thanks! This is tracked in https://github.com/rust-lang/rust/issues/43408.
