### ISSUE TITLE
Confusing error when missing #[derive(Clone)]

### ISSUE THREAD

**Issue by mkeeter** [rust-lang/rust#54625]
This is not quite a bug, but it has surprised me twice, so I figured I'd open an issue.

Consider the following code:

```
struct Boop {
    i: usize
}

impl Boop {
    fn next(&self) -> Boop {
        let mut out = self.clone();
        out.i += 1;
        return out;
    }
}
```

This fails to compile with the error message
```
 --> src/main.rs:9:16
  |
9 |         return out;
  |                ^^^ expected struct `Boop`, found &Boop
  |
  = note: expected type `Boop`
             found type `&Boop`
```

If you add `#[derive(Clone)]` to the `struct` definition, then it works, but that's a weirdly non-local change that's not hinted at by the error.  Could the compiler's error message be more helpful?

```rustc --version --verbose
rustc 1.29.1 (b801ae664 2018-09-20)
binary: rustc
commit-hash: b801ae66425cf7c3c71052b19ef8f145b0d0513d
commit-date: 2018-09-20
host: x86_64-apple-darwin
release: 1.29.1
LLVM version: 7.0```

**Comment by juchiast** [comment]
The problem is `&T` also implement `Clone`, so `self.clone()` in this context is called on `&Boop`. Therefore it is cloning a reference, not cloning the value.

That is what I know, I have no idea on how to make it better.

**Comment by mkeeter** [comment]
Yup – in the broken state, the type checker finds
- We're returning a `T`
- We've cloning a `&T`, which gives an `&T`
- Oh no!

The unintuitive behavior is that if `#[derive(Clone)]` is provided, then the type-checker solves backwards from
- We're returning a `T`
- `out` must be a `T`
- We can clone `&T` to `T` instead!

I wonder if there's a way to detect this pattern and offer a suggestion in the error message.

**Comment by estebank** [comment]
Current output:

```
error[E0308]: mismatched types
 --> src/lib.rs:9:16
  |
6 |     fn next(&self) -> Boop {
  |                       ---- expected `Boop` because of return type
...
9 |         return out;
  |                ^^^ expected `Boop`, found `&Boop`
  |
note: `Boop` does not implement `Clone`, so `&Boop` was cloned instead
 --> src/lib.rs:7:23
  |
7 |         let mut out = self.clone();
  |                       ^^^^
help: consider annotating `Boop` with `#[derive(Clone)]`
  |
1 + #[derive(Clone)]
2 | struct Boop {
  |
```
