### ISSUE TITLE
Please add retpoline support.

### ISSUE THREAD

**Issue by dancrossnyc** [rust-lang/rust#54637]
For a project at Google, we need retpoline support. Taylor Cramer suggested I open an issue; my initial search didn't reveal any pre-existing issues that seemed particularly relevant. There was a reddit thread that stalled after identifying some blocking issues (LLD integration, LLVM upgrades, etc) all of which have, I believe, subsequently been addressed. https://www.reddit.com/r/rust/comments/7saomi/status_of_spectre_variant_2_mitigation_in_rust/

As I understand it, the heavy lifting for this is in LLVM and it simply needs to be plumbed through.

Put another way, just as clang provides `-mretpoline` (https://reviews.llvm.org/D41723), I'm looking for something similar in the Rust toolchain.

Thanks!

**Comment by leonardo-m** [comment]
If Google wants this small part in Rust I'm sure Google could pay someone here for the implementation (assuming Google doesn't have people willing to become expert about Rust enough to create this pull request themselves).

**Comment by alexcrichton** [comment]
Some simple testing in clang shows that `-C target-feature=+retpoline` may be sufficient in Rust to work here. Does that work for you?

**Comment by eddyb** [comment]
cc @rust-lang/compiler

**Comment by GabrielMajeri** [comment]
I'm no security expert, but from what I can tell from [the LLVM code](https://reviews.llvm.org/D41723), this `retpoline` patch changes the PLT?

Because it just so happens we [have a PR which will disable the PLT by default](https://github.com/rust-lang/rust/pull/54592) and it seems that it might reduce the performance impact of retpoline (or even make it *mostly* unnecessary).
If you also build your C/C++ libraries with a global `CFLAGS=-fno-plt` you should be able to 100% remove the PLT from your binaries, making `retpoline` useless.

**Comment by nagisa** [comment]
We should still support retpolines when @PLT is used. That being said, it seems to me that this is almost entirely a linker’s job (i.e. all of the support is being added to `lld` and I haven’t seen any patches against LLVM itself). This means that implementing this is probably as easy as passing the relevant flags to linker and can be done even now (`-Clink-args`) without any explicit support from the compiler?

**Comment by dancrossnyc** [comment]
Thanks all! I'll take what's written here and see if I can plumb the appropriate flags through cargo etc to get retpolines in the generated binary. I'll report back with results.

**Comment by cyplo** [comment]
Heya, any news on this one @dancrossnyc ?

**Comment by dancrossnyc** [comment]
Sorry for the delayed response; I was traveling over the new year.

We put this in a while back and it seems to be working as expected. Thanks, all!
