### ISSUE TITLE
typo in std::thread::sleep

### ISSUE THREAD

**Issue by vn971** [rust-lang/rust#54644]
The documentation says: https://doc.rust-lang.org/std/thread/fn.sleep.html
```
... function will not return early due to a signal being received or a spurious wakeup.
```
Is that a typo? The function CAN return early right? (due to the reasons outlined)

<strike> I can make a fixing PR after confirmation.</strike>
UPD: Made a PR as well.

**Comment by vn971** [comment]
Made a PR straight away though.

**Comment by dtolnay** [comment]
Let's continue with the improvements in #54646, but based on https://github.com/rust-lang/rust/pull/54646#issuecomment-425498308 this sentence was accurate.
