### ISSUE TITLE
Warning for empty derive list should say derive modes and not traits

### ISSUE THREAD

**Issue by Havvy** [rust-lang/rust#54653]
The warning currently says: "warning: empty trait list in `derive`". This was true before Macros 1.1, but since then, you can derive arbitrary items, not just traits. As such, it should say "empty derive mode list".

**Comment by Centril** [comment]
I think that is less helpful even if it is more true; I would retain the mention of traits because in almost all cases, `#[derive(..)]` contains a list of traits (and I personally consider it a wart in the language that you can reference anything but traits...).

**Comment by dtolnay** [comment]
+1 to @Centril, I would keep calling them traits and it can be a dirty secret that derives can emit whatever they want.

**Comment by jonas-schievink** [comment]
I guess this can be closed. Feel free to reopen if you disagree.
