### ISSUE TITLE
trait permitting extra members

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#54665]
I've been tinkering locally with a crate called [salsa](https://github.com/nikomatsakis/salsa). Along the way, I noticed that my impl permits me to add extra members. e.g., [I have this trait](https://github.com/nikomatsakis/salsa/blob/36e2b9cdcc01228560f9fb7ffdfadf466d21e60d/src/lib.rs#L26-L32):

```rust
pub trait QueryContext: QueryContextStorageTypes {
    fn salsa_runtime(&self) -> &runtime::Runtime<Self>;
}
```

But in my cargo example I can use [this impl](https://github.com/nikomatsakis/salsa/blob/36e2b9cdcc01228560f9fb7ffdfadf466d21e60d/examples/storage_varieties/implementation.rs#L27-L35):

```rust
impl salsa::QueryContext for QueryContextImpl {
    fn extra(&self) -> u32 {
        0
    }

    fn salsa_runtime(&self) -> &salsa::runtime::Runtime<QueryContextImpl> {
        &self.runtime
    }
}
```

What the heck is going on here? I couldn't easily reproduce this in a smaller example, so I saved the commit. It did reproduce cleanly after `rm -rf target` and `cargo clean`, so I guess it's (probably?) not an incremental bug.

To reproduce:

- Clone the salsa repo at https://github.com/nikomatsakis/salsa and go to the commit `36e2b9cdcc01228560f9fb7ffdfadf466d21e60d`.
- Run `cargo build --example storage_varieties`
- Observe that build does not fail

Marking as T-compiler and P-high. P-high because this could be a very dangerous bug in terms of backwards compat risk! But I'm hoping it's something more bizarre (e.g., not rebuilding when I think it is). I did validate though that adding other weird stuff (e.g., invalid tokens) causes compilation to fail. Assigning to myself to investigate on Monday.

**Comment by GabrielMajeri** [comment]
@nikomatsakis Hi, while playing around with that example I found something interesting:

If I add an

```rust
extern crate salsa;
```

at the top it does error correctly:

```rust
error[E0407]: method `extra` is not a member of trait `salsa::QueryContext`                                                                              
  --> examples/storage_varieties/implementation.rs:30:5                                                                                                  
   |                                                                                                                                                     
30 | /     fn extra(&self) -> u32 {                                                                                                                      
31 | |         0                                                                                                                                         
32 | |     }                                                                                                                                             
   | |_____^ not a member of trait `salsa::QueryContext`                                                                                                 
                                                     
```

So at least this seems to be an issue with the new Rust 2018 module system?

**Comment by GabrielMajeri** [comment]
I think I've got a minimal repro. Considering a Rust 2018 crate with a library and a binary:

`lib.rs`:
```rust
pub trait Foo {
    fn foo();
}
```

`main.rs`:
```rust
// Uncomment to make error work:
//extern crate repro;

pub struct Bar;

impl repro::Foo for Bar {
    fn foo() {}

    // This compiles!
    fn extra() {}
}

fn main() {}
```

I can also work around the bug by adding a `use repro::Foo;`

**Comment by nikomatsakis** [comment]
@GabrielMajeri awesome, thanks!

**Comment by nikomatsakis** [comment]
cc @petrochenkov — any ideas? I'm looking into the code a bit

**Comment by nikomatsakis** [comment]
The immediate cause of the problem is that `current_trait_ref` is `None` here:

https://github.com/rust-lang/rust/blob/5472b0718f286266ab89acdf234c3552de7e973c/src/librustc_resolve/lib.rs#L2612

**Comment by nikomatsakis** [comment]
We seem to enter this block of code with a successful resolution in `def`:

https://github.com/rust-lang/rust/blob/5472b0718f286266ab89acdf234c3552de7e973c/src/librustc_resolve/lib.rs#L2472-L2485

But something goes wrong after that.

**Comment by nikomatsakis** [comment]
It seems like the problem is that `resolve_path` returns "Indeterminate"

**Comment by nikomatsakis** [comment]
Here is the output from some logs I added, showing the value of `def` and also the result of the call to `resolve_path`:

```
DEBUG 2018-10-04T16:36:34Z: rustc_resolve: with_optional_trait_ref: def=Trait(DefId(9/0:3))
DEBUG 2018-10-04T16:36:34Z: rustc_resolve: resolve_path(path=[repro#0, Foo#0], opt_ns=None, record_used=false, path_span=Span { lo: BytePos(42), hi: BytePos(52), ctxt: #0 }, crate_lint=SimplePath(NodeId(9)))
DEBUG 2018-10-04T16:36:34Z: rustc_resolve: resolve_path ident 0 repro#0
DEBUG 2018-10-04T16:36:34Z: rustc_resolve: with_optional_trait_ref: path_resolution=Indeterminate
```

**Comment by nikomatsakis** [comment]
cc @eddyb also — maybe you or @petrochenkov has some clue what's happening here based on the above output.

**Comment by petrochenkov** [comment]
I'll look at this once I'm back from vacation next week (unless it's resolved before that).

**Comment by pnkfelix** [comment]
visited for triage. Leaving on RC2 milestone, and thus, leaving at P-high.

**Comment by petrochenkov** [comment]
Fixed in https://github.com/rust-lang/rust/pull/55102
