### ISSUE TITLE
proc_macro::Span::source_file() returns incorrect paths

### ISSUE THREAD

**Issue by macpp** [rust-lang/rust#54677]
in some cases, proc_macro::Span::source_file() returns SourceFile with path "src/main.rs" , even if macro was used in other file/module

how to recreate:

in proc_macro crate: 
src/lib.rs
```
#![feature(proc_macro_span)]
extern crate proc_macro;
use proc_macro::TokenStream;
#[proc_macro_attribute]
pub fn pmacro_source_file_test(_metadata: TokenStream, input: TokenStream) -> TokenStream {
    println!("tokens:");
    println!("{}", &input);
    for x in input.clone().into_iter() {
        let file = x.span().source_file();
        println!("file path: {:?} , is_real: {}", file.path(), file.is_real());
    }
    input
}
```

in test crate
src/main.rs
```
#[macro_use]extern crate proc_macro_test; // #[pmacro_source_file_test] 
mod test;
fn main() {}
```
src/test.rs
```
#[pmacro_source_file_test]
pub fn some_fn() {}

#[pmacro_source_file_test]
enum Enum1 {
    one
}

#[pmacro_source_file_test]
struct Struct1 {
    x : String
}

#[pmacro_source_file_test]
enum Enum2 {}

#[pmacro_source_file_test]
struct Struct2 {}
```

after using `cargo build` i get following output:
```
tokens:
pub fn some_fn() { }
file path: "src/test.rs" , is_real: true
file path: "src/test.rs" , is_real: true
file path: "src/test.rs" , is_real: true
file path: "src/test.rs" , is_real: true
file path: "src/test.rs" , is_real: true
tokens:
enum Enum1 { one, }
file path: "src/main.rs" , is_real: true
file path: "src/main.rs" , is_real: true
file path: "src/main.rs" , is_real: true
tokens:
struct Struct1 {
    x: String,
}
file path: "src/main.rs" , is_real: true
file path: "src/main.rs" , is_real: true
file path: "src/main.rs" , is_real: true
tokens:
enum Enum2 { }
file path: "src/test.rs" , is_real: true
file path: "src/test.rs" , is_real: true
file path: "src/test.rs" , is_real: true
tokens:
struct Struct2 {
}
file path: "src/test.rs" , is_real: true
file path: "src/test.rs" , is_real: true
file path: "src/test.rs" , is_real: true
```

when span::source_file().path() is invoked on span from `Struct1` or `Enum1` it returns "src/main.rs" , but should "src/test.rs" - `Struct1` and `Enum1` are defined  in src/test.rs. 
Path is correct for empty enums and empty structs.
As far as i know, this bug can happen with functions too, but i don't have simple example for now. 

`rustc --version --verbose`:
rustc 1.30.0-nightly (63d51e89a 2018-09-28)
binary: rustc
commit-hash: 63d51e89af33a7cc1c81bbaee335131b7bd00803
commit-date: 2018-09-28
host: x86_64-unknown-linux-gnu
release: 1.30.0-nightly
LLVM version: 8.0 

**update:** 
probably consequence of #43081

**Comment by dtolnay** [comment]
Spans should currently be considered best-effort but frequently totally incorrect. Closing in favor of #43081 since the core problem is being tracked there.
