### ISSUE TITLE
CStr unchecked constructor can be a const fn

### ISSUE THREAD

**Issue by abonander** [rust-lang/rust#54678]
The current implementation of `CStr::from_bytes_with_nul_unchecked()` is not valid in a const context, but it can easily be tweaked so that it is:

```rust
pub const unsafe fn from_bytes_with_nul_unchecked(bytes: &[u8]) -> &Self {
    union BytesToCStr<'a> {
        bytes: &'a [u8],
        cstr: &'a CStr,
    }
    
    BytesToCStr { bytes }.cstr
}
```

**Comment by oli-obk** [comment]
At this point you can just enable the `const_transmute` feature gate and use `transmute`. There's no need for unions anymore

**Comment by abonander** [comment]
@oli-obk I thought `transmute` was explicitly not going to become `const` as per the discussion in #49450.

**Comment by oli-obk** [comment]
Yes I would like such constructors, too. But that needs and RFC and probably has a lot of caveats that we want to think about.

I did not know about that issue. I commented there.
