### ISSUE TITLE
Lack initialization of dylib when it built with optimization

### ISSUE THREAD

**Issue by katyo** [rust-lang/rust#54691]
Shared library with constructor function (crate_type = "cdylib"):

```rust
#[cfg_attr(target_os = "linux", link_section = ".init_array")]
pub static INITIALIZE: extern "C" fn() = myplugin_initialize;

// constructor function
#[no_mangle]
pub extern "C" fn myplugin_initialize() {
    println!("myplugin initialized");
}
```

Expected behavior:
The function `myplugin_initialize()` runs on library loading.

Unexpected behavior:
When the crate compiled with --release or when opt-level > 0 the function not runs.

_**NOTE1:** Using ".ctors" instead of ".init_array" as **link_section** gives same result._

_**NOTE2:** Changing **crate-type** from "cdylib" to "dylib" solves this issue, but I actually would like to build "cdylib" not "dylib"._

See https://github.com/katyo/rust_test_cdylib

**Comment by katyo** [comment]
Yes, adding `#[used]` directive to symbol helps avoid removing it by linker.
Thanks for this solution!

Where can I read about all supported directives?

**Comment by jonas-schievink** [comment]
Not sure how complete it is, but check out https://doc.rust-lang.org/reference/attributes.html
