### ISSUE TITLE
min_const_fn doesn't take #[allow_internal_unstable] into account

### ISSUE THREAD

**Issue by Amanieu** [rust-lang/rust#54710]
The `intrusive-collections` crate has a [macro](https://github.com/Amanieu/intrusive-rs/blob/bebd10d4bb6efc9ce6a6e3080703e4f59e7dff59/src/adapter.rs#L174) which defines a `const fn` that may have complex trait bounds. This macro uses `#[allow_internal_unstable]` to allow crates to use this macro without needing to enable any nightly features (just the "nightly" cargo feature on `intrusive-collections`).

To reproduce simply run `cargo test` on the crate: it will fail in one of the doc tests:
```
running 9 tests
test src/adapter.rs - intrusive_adapter (line 123) ... ignored
test src/adapter.rs - intrusive_adapter (line 131) ... ignored
test src/adapter.rs - intrusive_adapter (line 150) ... FAILED
test src/lib.rs -  (line 152) ... ok
test src/key_adapter.rs - key_adapter::KeyAdapter (line 19) ... ok
test src/adapter.rs - container_of (line 85) ... ok
test src/lib.rs -  (line 93) ... ok
test src/lib.rs -  (line 22) ... ok
test src/lib.rs -  (line 190) ... ok

failures:

---- src/adapter.rs - intrusive_adapter (line 150) stdout ----
error: trait bounds other than `Sized` on const fn parameters are unstable
  --> src/adapter.rs:168:35
   |
19 | intrusive_adapter!(MyAdapter3<'a, T: ?Sized> = &'a Test2<T>: Test2<T> { link: LinkedListLink } where T: Clone + 'a);
   |                                   ^

thread 'src/adapter.rs - intrusive_adapter (line 150)' panicked at 'couldn't compile the test', librustdoc/test.rs:333:13
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    src/adapter.rs - intrusive_adapter (line 150)

test result: FAILED. 6 passed; 1 failed; 2 ignored; 0 measured; 0 filtered out

error: test failed, to rerun pass '--doc'

```

**Comment by eddyb** [comment]
IIRC this is intentional, the solution is probably to change `allow_internal_unstable` to take a list of feature-gates to allow (since here you want `const_fn` *not* `min_const_fn`).
I wanted to do this before I got caught up in Rust 2018 things, I should try to make it work now.
cc @oli-obk

**Comment by oli-obk** [comment]
`#[allow_internal_unstable]` without a list of feature gates still works but is reporting a warning about being deprecated. You should always pass a list of features nowadays. I think this has baked long enough that we can remove the deprecated "allow everything" scheme.

**Comment by Amanieu** [comment]
`#[allow_internal_unstable]` now accepts a list of feature gates, so this can be closed.
