### ISSUE TITLE
x.py in incremental mode still rebuilds stage0-rustc if stage0-std changed.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#54712]
That is, `stage0-rustc` appears to lose incremental artifacts.
cc @alexcrichton @Mark-Simulacrum

**Comment by Mark-Simulacrum** [comment]
Yes, I believe this is because rustc/cargo will otherwise error on "found a new std" or something like that? I don't quite see how incremental is different from the normal compilation here?

**Comment by eddyb** [comment]
@Mark-Simulacrum incremental would still work even if dependencies changed.
I think the fundamental problem here is that `x.py` deletes everything, whereas `cargo clean` (which, IIRC, does not remove incremental artifacts by default) would be appropriate.

**Comment by Mark-Simulacrum** [comment]
Hm, I thought `cargo clean` was equivalent to `rm -rf target` essentially -- @alexcrichton could you clarify that? Would it be better to use cargo clean in rustbuild?

**Comment by alexcrichton** [comment]
Regardless of what `cargo clean` does I don't think we should execute it here. Rustbuild is overly conservative in what it deletes, and it can get away probably with just deleting the `deps` folder instead of the entire folder. That would leave around the incremental cache.

I believe, however, that `cargo clean` is like `rm -rf target`

**Comment by eddyb** [comment]
Looking at the code, these `clear_if_dirty` calls appear to be relevant: https://github.com/rust-lang/rust/blob/d99a320cba42f661aebfa1293b7b2ec3603dda75/src/bootstrap/builder.rs#L758-L786

The problem is that the directory `my_out` refers to is non-trivially structured.

Instead of removing `$my_out/*`, we need to remove all the files (or at least the ones that are artifacts) and the `deps` directory in `$my_out{/$target,}/{release,debug}/`.

**Comment by schomatis** [comment]
If someone could provide the appropriate guidance for a newbie I'd be very interested in working on this one.

In my particular case this issue manifested itself while working on https://github.com/rust-lang/rust/pull/58505, where any modifications to the `librustc_mir` code caused the `stage0-codegen` to be removed and rebuild (along with all of its dependencies, `cc`, `num_cpus`, `memmap`, etc.), doubling the time it took to perform any tests on it (to the point I hackily avoided removing anything altogether except for the `.stamp` file, https://github.com/schomatis/rust/commit/00a10a71281ba4073f74bc3eb4f7465ec9897a0a).

(Not totally related to this, but if possible I'd also like to add some more visibility to the intra-stage dependencies, manifested through the rules in the `clear_if_dirty` calls, maybe at the `builder::Step` or `bootstrap::Mode` level.)

**Comment by eddyb** [comment]
I keep hitting this, specifically it keeps rebuilding `rustc_codegen_llvm` and `rustdoc`, every time I change rustc, which cause them to take much longer than any of the rustc crates, and this issue has become my main bottleneck (now that I'm building on a `-j48` machine).

**Comment by eddyb** [comment]
Nominating for discussion (specifically, allocating resources towards this) at the next relevant team meeting (tagged both @rust-lang/infra and @rust-lang/compiler, as I'm not sure which has "jurisdiction" here).

**Comment by Mark-Simulacrum** [comment]
It'd be helpful to know how much rustbuild can "trust" the compiler here. Can we keep incremental artifact directories around from previous versions of the compiler?

**Comment by michaelwoerister** [comment]
The compiler can only work with incremental artifacts that it created itself. For any other version of the compiler it has to assume that it's incompatible. It usually just ignores such incompatible artifacts, but in the bootstrapping scenario, it might not always be smart enough to do that.

**Comment by Zoxc** [comment]
I think the question here is will rustc's incremental artifacts correctly deal with crates changing (including adding and removing crates) in the sysroot. If so, we could keep the `incremental` folder around. Cargo assumes the sysroot is unchanging, which is why we remove the `target` directory in the first place.

**Comment by eddyb** [comment]
Incremental doesn't care about `--extern` vs `-L`, so I'd expect it to be pretty resilient here.

**Comment by pnkfelix** [comment]
triage: P-medium. (this inefficiency in incremental comp. would be nice to resolve, but is not P-high IMO.)
