### ISSUE TITLE
thread 'main' panicked at 'assertion failed: index < u32::MAX as usize'

### ISSUE THREAD

**Issue by Praveer1981** [rust-lang/rust#54735]
C:\Users\kumarpr\.cargo\bin>twiggy monos C:\TEMP\AcFabricBackend.wasm
thread 'main' panicked at 'assertion failed: index < u32::MAX as usize', C:\Users\kumarpr\.cargo\registry\src\github.com-1ecc6299db9ec823\twiggy-ir-0.2.0\./ir.rs:414:9
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: BaseThreadInitThunk
  19: RtlUserThreadStart

**Comment by memoryruins** [comment]
The assert is from [twiggy](https://github.com/rustwasm/twiggy):
https://github.com/rustwasm/twiggy/blob/931a1b45475c4bfd3a77baad21a82579ab446667/ir/ir.rs#L413
Similar issue on twiggy’s repo: https://github.com/rustwasm/twiggy/issues/151

**Comment by Praveer1981** [comment]
I didn't understand what is the fix?

**Comment by Praveer1981** [comment]
Is there any defect in twiggy.exe? my .wasm file size is 30 MB

**Comment by memoryruins** [comment]
You probably want to open the issue on twiggy’s repository, since the assert is from the twiggy and there are previous similar issues.

**Comment by memoryruins** [comment]
If you’re looking to decrease the file size, check out https://rustwasm.github.io/book/game-of-life/code-size.html
