### ISSUE TITLE
No warning for unused function using `impl Trait` on beta and nightly

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/rust#54754]
The following code only warns that `f` is unused on stable, not on beta or nightly:

```rust
trait Trait {}
impl<T> Trait for T {}

fn f() -> impl Trait {}
```

(apologies if this is a duplicate, but a quick search didn't turn anything up)

**Comment by FelixMcFelix** [comment]
Yeah, the likely fix for this is to create a query for lints that removes all levels under `AccessLevel::Reachable`, or manually strip the entries each time. The former probably makes more sense. I wasn't sure we'd need to do this at the time, it shouldn't take too long.

**Comment by jonas-schievink** [comment]
I've implemented a more minimal fix at #54810. It should be safe to backport to beta, if this is wanted at all.

**Comment by pnkfelix** [comment]
(assigning self just to make sure everything gets followed up on here)

**Comment by pnkfelix** [comment]
tagged as P-high since it was a regression.
