### ISSUE TITLE
confusing error message around trait object bound

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#54779]
This example:

```rust
#![feature(in_band_lifetimes)]
#![feature(nll)]

trait DebugWith<Cx: ?Sized> {
    fn debug_with(&'me self, cx: &'me Cx) -> DebugCxPair<'me, Self, Cx> {
        DebugCxPair { value: self, cx }
    }
    
    fn fmt_with(&self, cx: &Cx, fmt: &mut std::fmt::Formatter<'_>) -> std::fmt::Result;
}

struct DebugCxPair<'me, Value: ?Sized, Cx: ?Sized>
where
    Value: DebugWith<Cx>,
{
    value: &'me Value,
    cx: &'me Cx,
}

trait DebugContext { }

struct Foo {
    bar: Bar
}

impl DebugWith<dyn DebugContext> for Foo {
    fn fmt_with(&self, cx: &dyn DebugContext, fmt: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let Foo { bar } = self;
        bar.debug_with(cx);
        Ok(())
    }
}

struct Bar { }

impl DebugWith<dyn DebugContext> for Bar {
    fn fmt_with(&self, cx: &dyn DebugContext, fmt: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        Ok(())
    }
}

fn main() { }
```

gives this error:

```
error: unsatisfied lifetime constraints
  --> src/main.rs:29:9
   |
27 |     fn fmt_with(&self, cx: &dyn DebugContext, fmt: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
   |                 -          - let's call the lifetime of this reference `'1`
   |                 |
   |                 let's call the lifetime of this reference `'2`
28 |         let Foo { bar } = self;
29 |         bar.debug_with(cx);
   |         ^^^^^^^^^^^^^^^^^^ argument requires that `'1` must outlive `'2`
```

It took me some time to puzzle out what was happening here:

- `cx: &dyn DebugContext` expands to `&'a dyn (DebugContext + 'a)`
- the default from the *impl* however is `dyn (DebugContext + 'static)`
- the impl method is accepted because it is *more* general than the trait definition
- but it fails to recursively invoke

The error message without NLL, of course, is also not very illuminating.

**Comment by matthewjasper** [comment]
Assigning myself to bookmark.

**Comment by estebank** [comment]
> the default from the impl however is `dyn (DebugContext + 'static)`

This seems to be a persistent ergonomics wart where traits get evaluated to `'static` (happens as well with returning `&(impl Trait)` and others I can't remember now) where it isn't expected. It is a bit sad, and we can improve the diagnostic errors, but I'm worried we'll be unable to preempt _all_ the cases from being caught by accurate diagnostics, pushing people away from deeply nested structures. Maybe that is for the best, though.

**Comment by pnkfelix** [comment]
discussed with @nikomatsakis . We agreed this is not a blocker for 2018 edition. Tagging with NLL-deferred so it does not clog up our triage process.

**Comment by pnkfelix** [comment]
I forgot to actual test how migration-mode (enabled for the 2018 edition) compares to `#![feature(nll)]`.

<details>

Current (nightly) 2018 edition output ([play](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=69a1ebb510ab314d4c16d4e095429f79)): 

```
error[E0495]: cannot infer an appropriate lifetime due to conflicting requirements
  --> src/main.rs:26:24
   |
26 |         bar.debug_with(cx);
   |                        ^^
   |
note: first, the lifetime cannot outlive the anonymous lifetime #2 defined on the method body at 24:5...
  --> src/main.rs:24:5
   |
24 | /     fn fmt_with(&self, cx: &dyn DebugContext, fmt: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
25 | |         let Foo { bar } = self;
26 | |         bar.debug_with(cx);
27 | |         Ok(())
28 | |     }
   | |_____^
note: ...so that the declared lifetime parameter bounds are satisfied
  --> src/main.rs:26:24
   |
26 |         bar.debug_with(cx);
   |                        ^^
   = note: but, the lifetime must be valid for the static lifetime...
   = note: ...so that the expression is assignable:
           expected &(dyn DebugContext + 'static)
              found &dyn DebugContext

error: aborting due to previous error
```

Current (nightly) output with `#![feature(nll)]` ([play](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=7f9eea660e3fcaaf0a7cfbef3650b591)):

```
error: lifetime may not live long enough
  --> src/main.rs:28:24
   |
26 |     fn fmt_with(&self, cx: &dyn DebugContext, _fmt: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
   |                            - let's call the lifetime of this reference `'1`
27 |         let Foo { bar } = self;
28 |         bar.debug_with(cx);
   |                        ^^ cast requires that `'1` must outlive `'static`
```

</details>

**Comment by pnkfelix** [comment]
As for this week's triage, tagging this as P-medium priority.

**Comment by estebank** [comment]
I recently landed some changes (https://github.com/rust-lang/rust/pull/72543 and https://github.com/rust-lang/rust/pull/72804) that are tangentially related to this but a similar strategy to them could be applied to this case.

**Comment by marmeladema** [comment]
Since `in_band_lifetimes` feature has been removed, can this issue be closed as obsolete?

**Comment by jackh726** [comment]
The example without `in_band_lifetimes`: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=d0d998218da2b4376859b07acc331644

The error message isn't the same as migrate mode, but is on-par in terms of information (pointing out that the anonymous lifetime doesn't live as long as `'static`). This issue can be closed by adding the above as a test.
