### ISSUE TITLE
Using Self::default() instead of TypeAlias::default() causes an ICE on nightly.

### ISSUE THREAD

**Issue by rodrimati1992** [rust-lang/rust#54785]
In the process of adding my project to travis-ci I got a nightly ICE from using "Self::default() instead of TypeAlias::default()" inside an impl block for type aliases.This works fine on stable.

This is the log for the first error:
https://travis-ci.org/rodrimati1992/type_level/jobs/436599429

This is the log for the second error:
https://travis-ci.org/rodrimati1992/type_level/jobs/436607478

This are the changes made to add the project to travis-ci,
including the commits that fix the error in my project:
https://github.com/rodrimati1992/type_level/commit/9411158f19e4515e15d01db66bb4da6ec7db857a

The files that were changed to fix the error were :

- type_level_examples/src/bin/_03_vis_wrapper.rs

- type_level_examples/src/bin/_07_split_mut.rs

**Comment by estebank** [comment]
Could you help us narrow down which nightly introduced the problem for you? How recently were you able to build before the current issue?

Particularly, I'm intrigued by https://github.com/rust-lang/rust/pull/53751, namely nightly from September 12th vs 14th and https://github.com/rust-lang/rust/pull/54346 September 19th vs 21st.

**Comment by estebank** [comment]
Nevermind, I believe I found the culprit https://github.com/rust-lang/rust/pull/52568/files#diff-2c49ea48a32b1e12546e0517e544ef58R315

@oli-obk can you take a look? I'm not sure I understand why we're `panic`ing in that case instead of always emitting or at least cancelling those diagnostics.

**Comment by rodrimati1992** [comment]
I will try this in those nightlys anyway and report which ones break.

**Comment by oli-obk** [comment]
The actual error is

```
error: internal compiler error: broken MIR in DefId(0/0:10 ~ _03_vis_wrapper[21d9]::rectangle[0]::{{impl}}[0]::new[0]) (const std::default::Default::default): bad constant user type Canonical { variables: [], value: fn() -> rectangle::RectangleInner<type_level_values::const_wrapper::ConstWrapper<<type_level_RectangleAcessible::ConstRectangleAcessible<type_level_values::reexports::Void, type_level_values::reexports::Void> as type_level_values::field_traits::SetField_<type_level_RectangleAcessible::__fields::All, type_level_Accessibility::Accessible>>::Output, type_level_values::const_wrapper::PhantomKind>> {<rectangle::RectangleInner<type_level_values::const_wrapper::ConstWrapper<<type_level_RectangleAcessible::ConstRectangleAcessible<type_level_values::reexports::Void, type_level_values::reexports::Void> as type_level_values::field_traits::SetField_<type_level_RectangleAcessible::__fields::All, type_level_Accessibility::Accessible>>::Output, type_level_values::const_wrapper::PhantomKind>> as std::default::Default>::default} } vs fn() -> rectangle::RectangleInner<type_level_values::const_wrapper::ConstWrapper<type_level_RectangleAcessible::ConstRectangleAcessible<type_level_Accessibility::Accessible, type_level_Accessibility::Accessible>, type_level_values::const_wrapper::PhantomKind>> {<rectangle::RectangleInner<type_level_values::const_wrapper::ConstWrapper<type_level_RectangleAcessible::ConstRectangleAcessible<type_level_Accessibility::Accessible, type_level_Accessibility::Accessible>, type_level_values::const_wrapper::PhantomKind>> as std::default::Default>::default}: NoSolution
  --> type_level_examples/src/bin/_03_vis_wrapper.rs:42:13                                             
   |                                                                                                   
42 |             Self::default()                                                                       
   | 
```

The `panic!` quoted in https://github.com/rust-lang/rust/pull/52568/files#diff-2c49ea48a32b1e12546e0517e544ef58R315 is just a way to abort the compiler after dumping all the ICEs

**Comment by Centril** [comment]
@rodrimati1992 Could you produce a minimal example for this? Also, does it reproduce on the current nightly?

**Comment by rodrimati1992** [comment]
I'll leave it at can't reproduce with a minimal example,I tried to but couldn't.

I haven't touched the `type_level` repository since december 2018(nor used it),and the `type_level_values` crate hasn't been able to compile due to recursive impl errors since then.

**Comment by spastorino** [comment]
Sorry, I was a bit fast to ping the cleanup-crew group.

In an ideal world what we would like to do is to go back to the rustc version where this started to manifest and try to get an MVCE and then try to see if this is still an issue in current rustc versions.

However, the bug as written is based on abandoned code and it's kind of non actionable for us.

**Comment by spastorino** [comment]
After going over this with @pnkfelix we decided to tag as `P-low` with the intention to close it because it's kind of non actionable for us.

**Comment by spastorino** [comment]
Closing this as non actionable as per comment from last triage meeting. If someone wants to provide an MCVE and something that is more actionable, please feel free to comment and we can reopen this issue.
