### ISSUE TITLE
The compiler reported twice

### ISSUE THREAD

**Issue by Zhihang-Liu** [rust-lang/rust#54794]
When the compiler prompts an error or warning, it will be displayed twice.
(frequency: Each)

**Comment by Zhihang-Liu** [comment]
E.g:
![image](https://user-images.githubusercontent.com/29578696/46428485-b31eab00-c776-11e8-8b05-8a0ba0a1cd04.png)

**Comment by Zhihang-Liu** [comment]
stable
![image](https://user-images.githubusercontent.com/29578696/46429177-60de8980-c778-11e8-90bf-8666dd6806db.png)

**Comment by estebank** [comment]
This is https://github.com/rust-lang/cargo/issues/5128 running `rustc` twice. It needs to be fixed.
