### ISSUE TITLE
Why isn't ManuallyDrop `transparent`?

### ISSUE THREAD

**Issue by ubsan** [rust-lang/rust#54793]
See title.

@nagisa 

It should be guaranteed, imo, that `ManuallyDrop<T>` has the same object and ABI representation as `T`.

**Comment by nagisa** [comment]
IIRC `transparent` was being worked on at about the same time as `ManuallyDrop` which is why `ManuallyDrop` wasn’t made transparent. I also remember mildly there being attempts to make `ManuallyDrop` `transparent` before…

**Comment by ubsan** [comment]
@nagisa Would it be possible to just add it to the type? It's not a breaking change, and it's clearly desirable.

**Comment by ubsan** [comment]
Oh, hey, what do you know, it's fixed in nightly :P
