### ISSUE TITLE
When profiling generated gcno files can have weird source files

### ISSUE THREAD

**Issue by calixteman** [rust-lang/rust#54791]
When profiling the following code (with CARGO_INCREMENTAL=0 RUSTFLAGS="-Zprofile -Ccodegen-units=1" cargo +nightly run):
extern crate thread_local;
use thread_local::ThreadLocal;
fn main() {
    let tls: ThreadLocal<u32> = ThreadLocal::new();
    assert_eq!(tls.get(), None);
    assert_eq!(tls.get_or(|| Box::new(5)), &5);
    assert_eq!(tls.get(), Some(&5));
}

the generated file ./target/debug/deps/thread_local-45219195a6458363.gcno have some strange file informations:
$ llvm-cov-7 gcov -dump thread_local-45219195a6458363.gcno 2>1 | rg '<' 
9:File '<__lazy_static_internal macros>'
11:<__lazy_static_internal macros>:creating '<__lazy_static_internal macros>.gcov'
13:File '<__thread_local_inner macros>'
15:<__thread_local_inner macros>:creating '<__thread_local_inner macros>.gcov'

**Comment by Enselic** [comment]
Triage: Can you still reproduce? I closed a similar issue some days ago but this looks slightly different. It is probably fixed now though.

**Comment by Enselic** [comment]
Triage: No objections, so let's close.
