### ISSUE TITLE
misleading "try adding parentheses" in match with comma

### ISSUE THREAD

**Issue by ChrisJefferson** [rust-lang/rust#54807]
Consider the following (incorrect) code.

```
enum E { A,B,C }

fn x(e:E) -> i32 {
    match e {
        A,B => 1,
        C => 2
    }
}
```

The comma in the match is obviously supposed to be a `|`. However, rustc recommends I rewrite to `(A,B)`, which makes the situation worse, as the compile error becomes `expected enum E, found tuple`.

**Comment by oli-obk** [comment]
>  is obviously supposed

I disagree. It could be either of these. At the point where we're suggesting this we don't know the type of the match or any other details.

We could suggest both `(A, B)` and `A | B` to make it clear that the user should put some thought into fixing the error.

**Comment by 11Takanori** [comment]
This seems like a nice first issue for a beginner like me to contribute to, so I'd be happy to tackle this one.

**Comment by ChrisJefferson** [comment]
I don't know where the suggestions are mades but in this case (A,B) is obviously wrong, as it doesn't type check, while A|B does :)

**Comment by oli-obk** [comment]
> I don't know where the suggestions are mades but in this case (A,B) is obviously wrong, as it doesn't type check, while A|B does :)

We have no way to distinguish between your code sample and the following code sample.

```rust
fn x(e: (u8, u8)) -> i32 {
    match e {
        A,B => 1,
        C => 2
    }
}
```

The error is happening during parsing. This means we have no type information available. All we know is that we're parsing a pattern. Think about it this way, what can you tell about the following code snippet:

```rust
    match e {
        A,B => 1,
        C => 2
    }
```

Just looking at that without looking at the surroundings tells you nothing, except that `A`, `B` and `C` are either constants or enum variants if the programmer didn't ignore a warning about lowercase variable names.

**Comment by ZerothLaw** [comment]
@11Takanori Just checking in - have you made progress on this issue? Willing to pitch in on it. 

I'd like to slightly modified the initial code with:

```rust
enum E {A, B, C}

fn foo(e: E) -> u32 {
    match e {
        E::A,E::B => 0, 
        E::C => 1
    }
}
```
Error message is the same, but you can see that the compiler has more information, and still giving the wrong message.

**Comment by Knium** [comment]
Is someone working on this issue? I'm a first timer but want to try.
