### ISSUE TITLE
Inconsistent error reporting by std::fs::copy()

### ISSUE THREAD

**Issue by piscisaureus** [rust-lang/rust#54800]
When `fs::copy()` is passed a non-existing, but otherwise valid, `from` path, the resulting error is inconsistent between platforms.

* On Unix, it reports `ErrorKind::InvalidInput`. See https://github.com/rust-lang/rust/blob/5597ee8a6483238421750fce4eb7031b12852428/src/libstd/sys/unix/fs.rs#L839-L842.
* On Windows, it reports `ErrorKind::NotFound`, which is the result of mapping the `ERROR_FILE_NOT_FOUND` error, which is reported by `CopyFileExW`. See https://github.com/rust-lang/rust/blob/5597ee8a6483238421750fce4eb7031b12852428/src/libstd/sys/windows/fs.rs#L746-L747 and https://github.com/rust-lang/rust/blob/1114ab684fbad001c4e580326d8eb4d8c4e917d3/src/libstd/sys/windows/mod.rs#L64.

I would argue that `Error:NotFound` is the better choice here.

**Comment by nicokoch** [comment]
But `Error::InvalidInput` is also returned when the input file is a directory.
So `Error::NotFound` is not the best option here.

IMO, we should just return whatever the os returns and not care about "error fast paths", as implemented on unix right now.

**Comment by piscisaureus** [comment]
> But `Error::InvalidInput` is also returned when the input file is a directory.
> So `Error::NotFound` is not the best option here.

I wasn't suggesting to always return `Error::NotFound` regardless of what the problem is.
But when the `from` file doesn't exist, `Error::NotFound` seems pretty reasonable, right?

> IMO, we should just return whatever the os returns and not care about "error fast paths". So the check would disappear completely from the unix implementation.

Mapping the OS error is definitely better than this.
It's also not a fast "fast path", since this requires an extra syscall.

**Comment by ChrisDenton** [comment]
As far as I understand [the current Linux code](https://github.com/rust-lang/rust/blob/9c9ae85a4773be3c1e33717e4fa9759b4ce020ef/library/std/src/sys/unix/fs.rs#L1402), `InvalidInput` is only returned in the case where the `from` is a symlink to a directory

https://github.com/rust-lang/rust/blob/9c9ae85a4773be3c1e33717e4fa9759b4ce020ef/library/std/src/sys/unix/fs.rs#L1350-L1354

https://github.com/rust-lang/rust/blob/9c9ae85a4773be3c1e33717e4fa9759b4ce020ef/library/std/src/sys_common/fs.rs#L7-L10

So I think this issue can be closed?

**Comment by ChrisDenton** [comment]
Since I'm pretty sure this has been fixed and there have not been any comments otherwise in years, I'll close this now. But I'll be happy to reopen if I missed something,

**Comment by lucacasonato** [comment]
This is indeed fixed. I just removed our work around code from Deno :)
