### ISSUE TITLE
Allow to specify pub as the default visibility

### ISSUE THREAD

**Issue by Zauberklavier** [rust-lang/rust#54805]
At the moment Rust forces you to write `pub` in front of every symbol even when you know you want everything to be public or otherwise don't care about enforced visibility. In the way of reducing friction I think a module level `#![public_is_default]` or `#![default_visibility(pub)]` would be a great addition.

**Comment by Havvy** [comment]
This would require a way to specify a private publicness. It should also go through the [RFC](https://github.com/rust-lang/rfcs/) process.

**Comment by Zauberklavier** [comment]
Indeed so. I'll submit an RFC then.
