### ISSUE TITLE
Compiler Team Weekly Agenda

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#54818]
Prioritization Procedure for the Weekly Meeting: https://hackmd.io/pHb6eTZ2Sjy6XZmwXZHIBA?view#Prioritization-WG---Procedure

(look at the above link first; we are trying to make the above document be *the* canonical resource for preparing for and running the weekly T-compiler triage meeting.)

The agenda itself is constructed by following this procedure: https://hackmd.io/WJ0G17DHTHGgv0OW9I2PxA?view (which is also linked from the above document, since it is *the* canonical resource for running the meeting).

----

**This issue exists to describe the compiler team triage meeting and to collect links about it.** It is closed for comments since it's not meant to collect discussion; if you'd like to give feedback about the steering meeting, please feel free to [open a topic in Zulip][z].

[z]: https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler

If you are looking for the description of the compiler planning (aka "steering") meeting, see #58850

# Compiler Team Meeting Stuff
(A replacement for the [unsupported+EOL'ed etherpad](https://public.etherpad-mozilla.org/p/rust-compiler-meeting))

# WHERE IS THE COMPILER MEETING TAKING PLACE

We are in the process of evaluating various chat platforms.
  * See (and weigh in) at associated async discussion here: https://internals.rust-lang.org/t/where-should-the-compiler-team-and-perhaps-working-groups-chat/7894/44
The next meeting is scheduled to take place ON ZULIP

<details>

- October 4: https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/subject/weekly.20meeting.202018-10-04/near/135183234
- September 27: https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/subject/weekly.20meeting.202018-09-27/near/134744613
- September 20: https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/subject/weekly.20meeting.202018-09-20/near/134310881
- September 13: https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/subject/weekly.20meeting.202018-09-13/near/133886161
- September 6: Discord in the #compiler channel
- August 30: Discord in the #compiler channel https://discordapp.com/channels/442252698964721669/443151243398086667/484724478689935360
- August 23: Zulip https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/weekly.20meeting.202018-08-23
- August 16: Zulip https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/weekly.20meeting.202018-08-16
- August 09: Zulip https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/weekly.20meeting.202018-08-09
- August 02: Zulip https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/weekly.20meeting.202018-08-02

</details>

If you are the meeting organizer, you can see the steps for running the meeting after the Agenda section below.

# AGENDA

## Review/Continue Weekly Pre-Meeting Triage (30min)

 * Either enumerate [unassigned P-high issues][P-high T-compiler unassigned], or ask people to review them (based on how many other items will fill up agenda).
 * Explicitly enumerate the [beta-backport nominations][I-BetaNominated T-compiler] and [stable-backport nominations][I-StableNominated T-compiler].
 * If there is time,
   * [Waiting for our team][], and
   * [I-nominated T-compiler][]

## Working Grop Check-in (30min)

 * [schedule][WG checkin schedule]

[WG checkin schedule]: https://rust-lang.github.io/compiler-team/about/triage-meeting/

# Procedure (for meeting organizer)

 * On the day of the meeting, some hours before hand, create two `#t-compiler` topics on Zulip
   * First topic name `weekly meeting YYYY-MM-DD #54818`; message text:
     > `Hi @*T-compiler/meeting* ; the triage meeting will be starting in H hours M minutes`
   * Second topic name `pre-meeting triage YYYY-MM-DD #54818`; message text:
     > I will be doing pre-triage in this channel.
   * Right-click that first pre-triage message, choose "Copy link to conversation", then post that link into the weekly meeting channel, with text like:
     > I will be doing `[pre-triage in a parallel topic](LINK-GOES-HERE)`
    * If you haven't already, figure out which working groups (at most two) should do their check-in's this week. Consult the [WG checkin schedule][]. In any case, state on in meeting topic channel which WG's will be doing check-ins, and be sure to `@`-address the relevant leads as reminders to them.
    * Switch now from the meeting channel to the pre-meeting triage channel, and do the pre-triage (see process with lists of issues below).
      * If during the pre-triage you identify issues that are worth bubbling up to the larger group, post corresponding messages back on the meeting channel itself.
  * When it is time for the meeting to start:
    * Write `Hi @*T-compiler/meeting*! Add a :wave: emoji to show you're here :)` in the meeting channel to announce it is starting (and get an approximate attendees list).
    * Immediately after starting the meeting, state that there are 5 minutes for general announcements that anyone can chime in on.

# PERSISTENT URLs

## Pre-triage Process

 * Unprioritized I-nominated issues [T-compiler][I-nominated T-compiler without P-label] and also [no team assigned][I-Nominated without P-label no team assigned] (for comparison see [all-teams][I-nominated without P-label all-teams]); prepass to identify candidates for P-high marking.
   * As you traverse the nominated issues, be sure to remove nomination tags from issues where it is not clear whether there is actually a point to discuss. (Sometimes nomination is just an implicit request for prioritization.)
 * Also for pre-pass: [beta-regressions without P-label][] and [nightly-regressions without P-label][]
 * Also for pre-pass: [I-nominated issues][I-nominated T-compiler] where the label should be removed (e.g. because it was discussed in the last meeting).
 * [I-BetaNominated T-compiler][], and also [no team assigned][I-BetaNominated no team assigned] (see also [all-teams][I-BetaNominated All Teams]).
    * During pre-triage, make sure to add T-compiler where appropriate to the cases of [no team assigned][I-BetaNominated no team assigned].
 * [I-StableNominated T-compiler][] (and [all-teams][I-StableNominated All Teams])
 * Traverse [Waiting for our team][] and explicitly nominate any that you think may be able to be resolved *quickly* in triage meeting.
 * [P-high T-compiler][]
   * [P-high T-compiler unassigned][]

[beta-regressions without P-label]: https://github.com/rust-lang/rust/issues?utf8=%E2%9C%93&q=is%3Aopen+label%3Aregression-from-stable-to-beta++-label%3AP-high++-label%3AP-medium+-label%3AP-low+-label%3AT-libs+-label%3AT-infra+-label%3AT-rustdoc
[nightly-regressions without P-label]: https://github.com/rust-lang/rust/issues?utf8=%E2%9C%93&q=is%3Aopen+label%3Aregression-from-stable-to-nightly++-label%3AP-high++-label%3AP-medium+-label%3AP-low+-label%3AT-infra+-label%3AT-rustdoc
[I-nominated T-compiler without P-label]: https://github.com/rust-lang/rust/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3AT-compiler+-label%3AP-high++-label%3AP-medium+-label%3AP-low+label%3AI-nominated
[I-Nominated without P-label no team assigned]: https://github.com/rust-lang/rust/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+-label%3AP-high++-label%3AP-medium+-label%3AP-low++label%3AI-nominated+-label%3AT-compiler+-label%3AT-libs+-label%3AT-infra+-label%3AT-rustdoc++-label%3AT-lang
[I-nominated without P-label all-teams]: https://github.com/rust-lang/rust/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+-label%3AP-high++-label%3AP-medium+-label%3AP-low++label%3AI-nominated
[I-nominated T-compiler]: https://github.com/rust-lang/rust/issues?q=is%3Aopen+label%3AI-nominated+label%3AT-compiler

[P-high T-compiler]: https://github.com/rust-lang/rust/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3AT-compiler+label%3AP-high+
[P-high T-compiler unassigned]: https://github.com/rust-lang/rust/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3AT-compiler+label%3AP-high+no%3Aassignee
[RC2 milestone]: https://github.com/rust-lang/rust/milestone/56
[Release milestone]: https://github.com/rust-lang/rust/milestone/55
[I-BetaNominated T-compiler]: https://github.com/rust-lang/rust/issues?utf8=%E2%9C%93&q=label%3Abeta-nominated+label%3AT-compiler
[I-BetaNominated All Teams]: https://github.com/rust-lang/rust/issues?utf8=%E2%9C%93&q=label%3Abeta-nominated
[I-BetaNominated no team assigned]: https://github.com/rust-lang/rust/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+-label%3AP-high++-label%3AP-medium+-label%3AP-low++label%3Abeta-nominated+-label%3AT-compiler+-label%3AT-libs+-label%3AT-infra+-label%3AT-rustdoc++-label%3AT-lang+
[I-StableNominated T-compiler]: https://github.com/rust-lang/rust/issues?utf8=%E2%9C%93&q=+label%3Astable-nominated+label%3AT-compiler
[I-StableNominated All Teams]: https://github.com/rust-lang/rust/issues?utf8=%E2%9C%93&q=+label%3Astable-nominated

 * Pre-triage may reveal bugs that are good candidates for the ICE-Breakers (groups dedicated to hopefully-small tasks in focused sub-areas). You can [tag issues](https://rust-lang.github.io/rustc-guide/ice-breaker/about.html#tagging-an-issue-for-an-ice-breaker-group) accordngly with the corresponding team.

----

 * [Stable-to-beta regressions][] (all! not just T-compiler) 
 * [Stable-to-nightly regressions][] (all! not just T-compiler)

[Stable-to-beta regressions]: https://github.com/rust-lang/rust/labels/regression-from-stable-to-beta 
[Stable-to-nightly regressions]: https://github.com/rust-lang/rust/labels/regression-from-stable-to-nightly 

----

 * [Waiting for our team][]
 * [I-nominated T-compiler][] and [(all-teams)][I-nominated All teams]

[Waiting for our team]: https://github.com/rust-lang/rust/pulls?q=is%3Aopen+is%3Apr+label%3AS-waiting-on-team+label%3AT-compiler
[I-nominated T-compiler]: https://github.com/rust-lang/rust/issues?utf8=%E2%9C%93&q=is%3Aopen+label%3AI-nominated+label%3AT-compiler 
[I-nominated T-compiler old link]: https://is.gd/RNZI1C 
[I-nominated All teams]: https://github.com/rust-lang/rust/labels/I-nominated (all teams)

----

* Outstanding Tool Breakage (needs a link for appropriate github search)

 * [Unprioritized T-compiler][]
   * [Just our team's ICEs](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3AT-compiler+label%3AI-ICE+-label%3AA-NLL+-label%3AT-lang+-label%3AT-libs+-label%3AP-high+-label%3AP-medium+-label%3AP-low+)
   * [Just our team's non-ICEs](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3AT-compiler+-label%3AI-ICE+-label%3AA-NLL+-label%3AT-lang+-label%3AT-libs+-label%3AP-high+-label%3AP-medium+-label%3AP-low+)

[Unprioritized T-compiler]: https://github.com/issues?utf8=%E2%9C%93&q=is%3Aopen+is%3Aissue+label%3AT-compiler+-label%3AP-high+-label%3AP-medium+-label%3AP-low

 * [Stable-to-stable regressions][] (all! not just T-compiler)
   * [excluding things already labeled][Stable-to-stable regressions excluding things already labeled]

[Stable-to-stable regressions]: https://github.com/rust-lang/rust/labels/regression-from-stable-to-stable
[Stable-to-stable regressions excluding things already labeled]: https://github.com/rust-lang/rust/issues?utf8=%E2%9C%93&q=is%3Aopen+label%3Aregression-from-stable-to-stable+-label%3AP-medium+-label%3AP-high+-label%3AP-low

 * [RFC spreadsheet][]
 * [RFCs][]
 * [perf regressions][]
 * [rust-icci regressions][]

[RFC spreadsheet]: https://docs.google.com/spreadsheets/d/1M8xKBIgkul5SUW0e_P1-H2DQ1N3or-JePdxrJv3wpfg/edit#gid=0
[RFCs]: https://github.com/rust-lang/rfcs/pulls?q=is%3Aopen+is%3Apr+label%3AT-compiler
[perf regressions]: http://perf.rust-lang.org/index.html
[rust-icci regressions]: https://travis-ci.org/rust-icci

### RLS Related things

 * [A-rls bugs not tagged T-compiler](https://github.com/rust-lang/rust/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3AA-rls+-label%3AT-compiler)
 * [T-dev-tools bugs not associated with other teams](https://github.com/rust-lang/rust/issues?page=1&q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3AT-dev-tools+-label%3AT-rustdoc+-label%3AT-compiler+-label%3AT-infra+-label%3AT-cargo&utf8=%E2%9C%93)

# IRC nicks to ping when meeting starts

Add yourself if you are missing in the list and want to get pinged

nmatsakis eddyb oli_obk nagisa pnkfelix mw varkor oli_obk_ qmx wesleywiser davidtwco

# AGENDA

Move away from etherpad, possible solutions:
* a gist (this page is mostly static anyway)
* a google doc
* a dropbox paper
* https://notepad.pw
* https://cryptpad.fr (has a markdown thingy)
* http://hackmd.io

eddyb writes:

https://github.com/rust-lang/rust/pull/48575#issuecomment-380635967

nox writes:

https://github.com/rust-lang/rust/issues/50825 is a blocker to do a rustup in Servo and see the impact of MergeFunctions there.

**Comment by Centril** [comment]
FYI: For the etherpad stuff there's also http://hackmd.io/.

**Comment by pnkfelix** [comment]
(discussion with some other team members made me realize that there's no reason for this issue to remain open, even *if* I still want to keep the number around for ease of hyperlinking from e.g. zulip. People can still visit closed issues, edit them, etc)
