### ISSUE TITLE
Javascript error (implementations-list)

### ISSUE THREAD

**Issue by derekdreery** [rust-lang/rust#54826]
The following  code causes an error when viewing the `ansi_term` crate documentation in a browser:

```javascript
if (getCurrentValue('rustdoc-trait-implementations') !== 'false') {
    onEach(document.getElementById('implementations-list').getElementsByClassName('collapse-toggle'), collapser);
}
```

the error is:

```javascript
document.getElementById(...) is null
```

`$ rustc --version`: `rustc 1.30.0-beta.11 (f11dae2b2 2018-10-03)`

**EDIT** Updated beta version (still happening).

**Comment by GuillaumeGomez** [comment]
Fixed.
