### ISSUE TITLE
Confusing diagnostic with assocaited constants

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#54849]
I wrote some code that looks like this, just to see if it would work:

```rust
pub struct A<T> {
    data: [T; A::SIZE],
}

impl<T> A<T> {
    const SIZE: usize = 4;
}
```

This gives an error like this:

```text
error[E0282]: type annotations needed
 --> src/lib.rs:2:15
  |
2 |     data: [T; A::SIZE],
  |               ^^^^^^^ cannot infer type for `T`

error: aborting due to previous error
```

There's no `T` in `A::SIZE`, so it's not clear how I would annotate that. Just in general, I find this diagnostic quite confusing.

**Comment by Centril** [comment]
I tried the following:
```rust
pub struct A<T: Sized> {
    data: [T; A::<T>::SIZE],
}

impl<T: Sized> A<T> {
    const SIZE: usize = 4;
}
```
but the compiler wasn't too happy with that either; this could all be a bug?

**Comment by dtolnay** [comment]
I would expect @steveklabnik's code not to compile for the same reason that this code does not compile. It is ambiguous which `A<T>`'s associated constant is being referred to.

```rust
pub struct A<T> {
    data: T,
}

impl<T> A<T> {
    const SIZE: usize = std::mem::size_of::<T>();
}

fn main() {
    println!("{}", A::SIZE);
}
```

@Centril's code should compile but this is being tracked in https://github.com/rust-lang/rust/issues/43408.

**Comment by steveklabnik** [comment]
I still wonder if the diagnostic can be improved, but I have no concrete suggestions, so let's keep this closed. If anyone has any thoughts, let me know!
