### ISSUE TITLE
libcore and f32::{abs, mod_euc}

### ISSUE THREAD

**Issue by petoknm** [rust-lang/rust#54876]
Are there plans for moving stuff like this into the core crate? I am doing embedded stuff and currently I would like to use the brand spanking new mod_euc methods for floats and can't.

```
error[E0599]: no method named `mod_euc` found for type `f32` in the current scope
  --> src/main.rs:46:23
   |
46 |     let r = (5.0_f32).mod_euc(2.0);
   |                       ^^^^^^^
```

I found [this comment](https://github.com/rust-lang/rust/pull/49389#issuecomment-377067213) that just points to an ease of first implementation as the reason for this being in the std crate. Are there any other reasons for this? If not, I could try to pull this and some related functionality from std to core crate.

**Comment by petoknm** [comment]
`.abs()` is also handy to have in no_std environments sometimes
```
error[E0599]: no method named `abs` found for type `f64` in the current scope
  --> src/main.rs:26:17
   |
26 |         r + rhs.abs()
   |                 ^^^
```

**Comment by Centril** [comment]
I would suggest writing up a PR; if it can be in libcore I see no reason why it shouldn't.

**Comment by petoknm** [comment]
Seems like this exact issue is already being discussed in:
 - https://github.com/rust-lang/rust/pull/49896
 - https://github.com/rust-lang/rust/issues/50145
 - https://github.com/rust-lang/rfcs/issues/2505
