### ISSUE TITLE
feature request: String::from("...") => d"..."

### ISSUE THREAD

**Issue by AmjadHD** [rust-lang/rust#54879]
It is common to use dynamic `String`s but using `String::From("...")` or `"...".to_string()` can get tedious, so it'll be more productive to write a string litteral `d"..."` instead. It's more productive, removes the apparent distance between both types of strings and it's syntactically sweeter.

**Comment by Centril** [comment]
To make this change, [an RFC needs to be written](https://github.com/rust-lang/rfcs) but I would first recommend getting some feedback about the idea at [the internals forum](http://internals.rust-lang.org/) before writing an RFC.

**Comment by AmjadHD** [comment]
Ok, Done.
