### ISSUE TITLE
Implement Try for ExitStatus

### ISSUE THREAD

**Issue by fenhl** [rust-lang/rust#54889]
It would be useful if `std::process::ExitStatus` implemented `std::ops::Try`. This could reduce boilerplate code where multiple `Command`s need to be spawned and checked.

Open question: What's a good error type? `ExitStatus` itself already contains all the relevant error information from the command, but being able to return a result of `Err(ExitStatus::from_code(0))` would be weird. (Thanks @scottmcm for pointing this out.)

**Comment by scottmcm** [comment]
Note that if the trait redesign from https://github.com/rust-lang/rust/issues/42327#issuecomment-379955253 were to happen, a distinct error type would no longer be needed and thus this would become substantially more reasonable.

**Comment by luser** [comment]
For a real-world example of where this would be useful, sccache runs compiler commands and wants to exit with the same status as the compiler:
https://github.com/mozilla/sccache/blob/3f318a8675e4c3de4f5e8ab2d086189f2ae5f5cf/src/lib.rs#L71
https://github.com/mozilla/sccache/blob/3f318a8675e4c3de4f5e8ab2d086189f2ae5f5cf/src/commands.rs#L526

**Comment by ratmice** [comment]
I believe that this should be closed as per the libs-api discussion in #93565
