### ISSUE TITLE
The #[panic_handler] attribute can be applied to non-functions

### ISSUE THREAD

**Issue by phil-opp** [rust-lang/rust#54896]
It's possible to apply the `panic_handler` attribute to an `extern crate` statement without errror:

```rust
#[panic_handler]
extern crate some_example_crate;
```

It only causes a linker error:

```
rust-lld: error: undefined symbol: rust_begin_unwind
```

(When the `panic_handler` attribute is not defined there is a much better "`#[panic_handler]` function required, but not found" error. There is also a nice error when the function signature is wrong. But it seems like the above case is not handled.)

**Comment by Centril** [comment]
cc @japaric

**Comment by japaric** [comment]
I'm very busy this week and probably won't have time to look at this until next Wednesday but if someone wants to take a stab at this I would look for the logic used by `#[global_allocator]`: that attribute gives you `"error: allocators must be statics"` when applied to non-static items.

**Comment by pnkfelix** [comment]
Visited for triage. Does not seem super critical to resolve immediately. Putting on the Release milestone (rather than RC2) to reflect this, and also downgrading priority to P-medium.
