### ISSUE TITLE
Tracking issue for "Create safe LLVM bindings"

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#54892]
Refiling https://github.com/rust-lang/rfcs/issues/644 here.

> rustc's LLVM bindings are a bit of a hodgepodge. Some abstractions have been added on top of the C bindings, but not consistently. It would be nice to do some serious cleanup here so that rustc is using only safe, high-level bindings.

cc https://github.com/rust-lang/rust/pull/52461

**Comment by tbu-** [comment]
#8274

**Comment by Centril** [comment]
Nothing has happened here for over a year so I think the issue doesn't carry it's weight.
