### ISSUE TITLE
Warn when known types are used as generic placeholders

### ISSUE THREAD

**Issue by lu-zero** [rust-lang/rust#54905]
Since hardly it is what you want and it leads to funny error messages, [here an example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2015):
``` rust
struct S<T> {
    foo: T,
}
impl<u16> S<u16> {
    fn fee(&self, idx: usize) -> u16 {
        if (self.foo as usize) < idx {
            idx as u16
        } else {
            4
        }
    }
}
fn main() {
    let f: S<u16> = S { foo: 42 };
    println!(" {}", f.fee(13));
}
```

**Comment by oli-obk** [comment]
Clippy reports

```
warning: This generic shadows the built-in type `u16`
 --> src/main.rs:4:6
  |
4 | impl<u16> S<u16> {
  |      ^^^
  |
  = note: #[warn(clippy::builtin_type_shadow)] on by default
  = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.212/index.html#builtin_type_shadow
```

Adding new warnings to rustc requires an RFC, as such I am going to close this. If the existing clippy lint is not covering your use cases, please don't hesitate to open an issue on the clippy repository

**Comment by oli-obk** [comment]
Unfortunately not, I don't know of any RFC that just added a lint.
