### ISSUE TITLE
Result::unwrap()` on an `Err` value: ()', libcore/result.rs:945

### ISSUE THREAD

**Issue by WandyLau** [rust-lang/rust#54900]
panicked at 'called `Result::unwrap()` on an `Err` value: ()', libcore/result.rs:945

This seems an old issue, and I saw the fix. But I still got this issue on Mac with rustc version 1.29.0

**Comment by F001** [comment]
This is expected behavior. Please ensure the value of `Result` be not an `Err` when using `unwrap`. You can use `unwrap_or` or `unwrap_or_else` instead, if the panic is not what you want.

**Comment by csmoe** [comment]
could you provide the back trace from `RUST_BACKTRACE=1` here?

**Comment by dtolnay** [comment]
If this is happening in user code, this is the documented behavior of Result::unwrap:
https://doc.rust-lang.org/std/result/enum.Result.html#method.unwrap

```rust
fn main() {
    let result: Result<usize, ()> = Err(());
    result.unwrap();
}
```

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', libcore/result.rs:945:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

If this is happening in the compiler while compiling a crate, please post a minimal source file that reproduces the problem along with the output of `RUST_BACKTRACE=1 cargo build`.

**Comment by WandyLau** [comment]
OK. Sorry for the late reply due to the time zone. This comes from client code. a project named indy-sdk. Any clue will be appreciated. Thanks in advance.

thread 'commands::wallet::tests::open::open_works_for_twice' panicked at 'called `Result::unwrap()` on an `Err` value: ()', libcore/result.rs:945:5
stack backtrace:
   0:        0x10d958aaf - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::hdfdb4ba75a1dcb88
                               at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:        0x10d947a6a - std::sys_common::backtrace::print::h5823bdde4d2f8639
                               at libstd/sys_common/backtrace.rs:71
                               at libstd/sys_common/backtrace.rs:59
   2:        0x10d95bf83 - std::panicking::default_hook::{{closure}}::h06fc925781e26cfe
                               at libstd/panicking.rs:211
   3:        0x10d95bcae - std::panicking::default_hook::hdfdcc6f72e7aec0a
                               at libstd/panicking.rs:221
   4:        0x10d95c677 - <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get::h7799216912757d62
                               at libstd/panicking.rs:475
   5:        0x10d95c21c - std::panicking::continue_panic_fmt::h2b83096170ce8c01
                               at libstd/panicking.rs:390
   6:        0x10d95c108 - std::panicking::try::do_call::hdceefc76f62a2c0e
                               at libstd/panicking.rs:325
   7:        0x10d99bed1 - core::ptr::drop_in_place::h01d49206069e70d4
                               at libcore/panicking.rs:77
   8:        0x10d56c77b - core::result::unwrap_failed::h306980ed616f4c91
                               at /Users/travis/build/rust-lang/rust/src/libcore/macros.rs:26
   9:        0x10d557643 - <core::result::Result<T, E>>::unwrap::hb22d76d8d692aabb
                               at /Users/travis/build/rust-lang/rust/src/libcore/result.rs:782
  10:        0x10d5fa9db - indy_cli::commands::wallet::tests::create_and_open_wallet::h345cae265e2eca0d
                               at src/commands/wallet.rs:1177
  11:        0x10d601c24 - indy_cli::commands::wallet::tests::open::open_works_for_twice::ha4d963cbc0440726
                               at src/commands/wallet.rs:647
  12:        0x10d654330 - indy_cli::__test::TESTS::{{closure}}::h6174f389474b3b96
                               at src/commands/wallet.rs:643
  13:        0x10d5a5e90 - core::ops::function::FnOnce::call_once::ha8a973f01c753a30
                               at /Users/travis/build/rust-lang/rust/src/libcore/ops/function.rs:223
  14:        0x10d6c2d01 - <F as alloc::boxed::FnBox<A>>::call_box::h9acd716f24414edd
                               at libtest/lib.rs:1451
                               at /Users/travis/build/rust-lang/rust/src/libcore/ops/function.rs:223
                               at /Users/travis/build/rust-lang/rust/src/liballoc/boxed.rs:642
  15:        0x10d967f5e - panic_unwind::dwarf::eh::read_encoded_pointer::hee47015c59adccfd
                               at libpanic_unwind/lib.rs:105
  16:        0x10d6e3dec - std::sys_common::backtrace::__rust_begin_short_backtrace::hf43e3d1f1b47de1e
                               at /Users/travis/build/rust-lang/rust/src/libstd/panicking.rs:289
                               at /Users/travis/build/rust-lang/rust/src/libstd/panic.rs:392
                               at libtest/lib.rs:1406
                               at /Users/travis/build/rust-lang/rust/src/libstd/sys_common/backtrace.rs:136
  17:        0x10d6e46c7 - std::panicking::try::do_call::h164983cc87ea19b7
                               at /Users/travis/build/rust-lang/rust/src/libstd/thread/mod.rs:409
                               at /Users/travis/build/rust-lang/rust/src/libstd/panic.rs:313
                               at /Users/travis/build/rust-lang/rust/src/libstd/panicking.rs:310
  18:        0x10d967f5e - panic_unwind::dwarf::eh::read_encoded_pointer::hee47015c59adccfd
                               at libpanic_unwind/lib.rs:105
  19:        0x10d6d9ac4 - <F as alloc::boxed::FnBox<A>>::call_box::h2abbfd46af541782
                               at /Users/travis/build/rust-lang/rust/src/libstd/panicking.rs:289
                               at /Users/travis/build/rust-lang/rust/src/libstd/panic.rs:392
                               at /Users/travis/build/rust-lang/rust/src/libstd/thread/mod.rs:408
                               at /Users/travis/build/rust-lang/rust/src/liballoc/boxed.rs:642
  20:        0x10d95b7c7 - std::sys_common::thread::start_thread::hffea5e9f9f11b206
                               at /Users/travis/build/rust-lang/rust/src/liballoc/boxed.rs:652
                               at libstd/sys_common/thread.rs:24
  21:        0x10d946a08 - std::sys::unix::thread::Thread::new::thread_start::hce603054d9b5b6fc
                               at libstd/sys/unix/thread.rs:90
  22:     0x7fff5d560660 - _pthread_body
  23:     0x7fff5d56050c - _pthread_start

**Comment by hayd** [comment]
The annoying part of this issue is that you have no idea/indication of which line called unwrap.
