### ISSUE TITLE
Iterator of `slice` has poor performance than `for loop`

### ISSUE THREAD

**Issue by tuxzz** [rust-lang/rust#54928]
[I've made a simple performance test](https://github.com/tuxzz/t.rust-speed-test) ([Playground](https://play.rust-lang.org/?gist=a05bb448060e7634a4a908d12191cf2b&version=nightly&mode=release&edition=2018))

On my machine

|          Test          | Time(s) |
|------------------------|---------|
|       slice_iter       |  0.875  |
|   slice_loop_safe_bad  |  0.519  |
|  slice_loop_safe_good  |  0.298  |

On playground

|          Test          | Time(s) |
|------------------------|---------|
|       slice_iter       |  1  |
|   slice_loop_safe_bad  |  0.537  |
|  slice_loop_safe_good  |  0.304  |

Iterate over a slice is about **3x slower** than `for loop` and about **2x slower** than bad implemention of `for loop`. (and about **7x slower** than `unchecked for loop` on my test, but it uses unsafe)
Maybe a bug?

**Comment by scottmcm** [comment]
This isn't the slice iterator's problem; most of it is that `zip` is often ungreat.  One can do better, for example, rewriting in a slightly different form, the same way the different `for` loops have different performance when written in different ways.  The following is competitive with safe_good:
```rust
use itertools::Itertools;
fn fn_slice_method_4(x: &[f32], out: &mut [f32]) {
    assert_eq!(x.len(), out.len());
    let mut it = x.iter().tuples();
    out.iter_mut().tuples().for_each(|(a0, a1)| {
        let (b0, b1) = it.next().unwrap();
        *a0 = *b1 * 123.0;
        *a1 = *b0 * 456.0;
    });
}
```

Also, reminder to be very careful that you're comparing equivalent things.  Your `for` loop examples assert that the slice lengths match, and thus have one fewer loop termination condition than your iterator example, which can make a _big_ difference to LLVM's loop canonicalization.

**Comment by Enselic** [comment]
Triage: Closing since the performance can not be expected to be the same, as explained above.
