### ISSUE TITLE
rustc crashes if main is wrongly defined by the user

### ISSUE THREAD

**Issue by yshui** [rust-lang/rust#54930]
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=6373ceb34c1fd2de892861530777d98d

**Comment by Centril** [comment]
I'm going to speculatively add `I-ICE` to this.

**Comment by euclio** [comment]
Looks like a duplicate of #9307.

**Comment by estebank** [comment]
This is certainly a duplicate of #9307.
