### ISSUE TITLE
Rebuild LLVM when it changed

### ISSUE THREAD

**Issue by Ekleog** [rust-lang/rust#54959]
I've spent the past few hours looking through documentation for how to build rustc with a patched LLVM without success. Currently, the best I'm at is:
```
submodules = false
fast-submodules = false
```
And then build with:
```
./x.py build --stage 1 src/llvm src/libstd
```

But even that doesn't rebuild anything unless I `rm -Rf build`. Which completely loses incremental compilation results.

Is there any way to make this development workflow better? Rebuilding from scratch at every change is… painful.

**Comment by kennytm** [comment]
You need to modify `src/rustllvm/llvm-rebuild-trigger` to rebuild LLVM.

**Comment by Ekleog** [comment]
Thanks! Leaving open for the documentation problem :)
