### ISSUE TITLE
async fn: 'static lifetime not inferred for Arc trait object

### ISSUE THREAD

**Issue by jamadazi** [rust-lang/rust#54974]
Playground link to reproduce: https://play.rust-lang.org/?gist=697ecc0c55cbf30bee0fb2d87736f704&version=nightly&mode=debug&edition=2018

Changing the suggested type to `Arc<SomeTrait + 'static>` fixes the compiler error.

Having to manually specify this does not seem intentional. Perhaps this `'static` lifetime should be automatically inferred?

**Comment by nikomatsakis** [comment]
Tagging as **blocking** -- this issue ought to be resolved before async-await can be stabilized, because it is generally surprising and kind of a bug. However, we expect it to get fixed by fixing https://github.com/rust-lang/rust/issues/56238 (see that issue for notes as to why).
