### ISSUE TITLE
Allow asserts and panics to abort process quietly.

### ISSUE THREAD

**Issue by vi** [rust-lang/rust#54981]
Currently assertions cause executable to be bloated up by various formatting-related symbols like

```
 0.5%   2.8%   1020B       std <core::fmt::builders::PadAdapter<'_> as core::fmt::Write>::write_str
 0.4%   2.3%    860B       std core::char::methods::<impl char>::escape_debug
 0.4%   2.2%    804B       std core::fmt::Formatter::pad_integral
```

, causing executables that carefully choose functions to call in order to stay under X kilobytes to suddenly grow by about 40-150 kilobytes. Additionally, `pthread_*` symbols appear in otherwise single-threaded module. Symbol count may jump by about 800.

Shall there be some mode (like `panic = "really-abort"`) or a libstd feature settable in `Xargo.toml` that makes all panics just do plain raw abort without trying to collect backtrace or print anything at all?

**Comment by vi** [comment]
Looks like making `panicking::{continue_panic_fmt,begin_panic}` just do the abort makes it small again.

Is a pull request about this welcome?

**Comment by vi** [comment]
With the new feature merged in, one can opt out formatting and panic handling using `panic_immediate_abort` and `#![no_main]`. This can bring static executable size under 20 kilobytes.

You need to 

* use Xargo,
*  `#![no_main]  #[no_mangle] pub fn main(...) {...}`,
* `std = {default-features=false, features=["panic_immediate_abort"]}
` line in `Xargo.toml`,
* panic=abort,
* LTO and
*  obviously avoid `println!`s yourself.

All panics and failed asserts will just cause Illegal Instruction.

**Comment by rhendric** [comment]
Hey @vi, I'm so glad you got this in! I followed your instructions above and my binaries are getting smaller. However, `ldd` tells me that there's still a libpthread dependency in my compiled (single-threaded) binaries. Have you succeeded in getting rid of that?

**Comment by rhendric** [comment]
You're right, I get the same as you. But trying that helped me figure out that adding the libc crate seems to be what adds the libpthread dependency, so thanks!

**Comment by johnthagen** [comment]
@vi In your tiny example, is there a reason you used `opt-level = "s"` instead of `opt-level = "z"`? I thought `"z"` was always strictly better at minimizing the size.

**Comment by vi** [comment]
@johnthagen , I don't think `s` vs `z` is relevant for such a small example. Unlike most other measures to reduce size bloat, `z` can cause more performance loss compared to `s`. And I don't remember observing significant size changes between `s` and `z`. Is the differene only about loop unrolling or there's more?

**Comment by johnthagen** [comment]
> Is the differene only about loop unrolling or there's more?

That's the only thing I've heard of. [The Cargo reference](https://doc.rust-lang.org/cargo/reference/manifest.html#the-profile-sections) just says:

> `# 's' attempts to reduce size, 'z' reduces size even more.`

**Comment by johnthagen** [comment]
@vi Looks like the latest `nightly` (`rustc 1.32.0-nightly (f4a421ee3 2018-12-13)`) might have broken this example / Xargo?

https://travis-ci.org/johnthagen/min-sized-rust/jobs/467982878#L498

**Comment by vi** [comment]
@johnthagen , Indeed: https://github.com/rust-lang/rust/pull/56092

> this almost for sure breaks out-of-tree std-building tools like xargo and cargo-xbuild

**Comment by johnthagen** [comment]
@vi Do you know if `panic_immediate_abort` can be enabled using [`-Z build-std`](https://doc.rust-lang.org/cargo/reference/unstable.html#build-std) rather than Xargo? Given Xargo has been in maintenance mode for years, it seems like `build-std` would be preferable. If so, would you be able to provide an example on how to enable it in a `build-std` build?

**Comment by johnthagen** [comment]
After playing around a bit with this myself, I was able to get this to work by using [`-Z build-std-features`](https://doc.rust-lang.org/cargo/reference/unstable.html#build-std-features):

```
cargo +nightly build -Z build-std=std,panic_abort -Z build-std-features=panic_immediate_abort --target x86_64-unknown-linux-gnu --release;
```

**Comment by leighmcculloch** [comment]
Is there an issue tracking stabilizing `panic_immediate_abort`?

**Comment by ChrisDenton** [comment]
It requires rebuilding the standard library, which means it depends on [build-std](https://github.com/rust-lang/wg-cargo-std-aware).
