### ISSUE TITLE
nll: strange suggestion to "consider removing the `*`

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#54985]
Spawned off of https://github.com/rust-lang/rust/pull/54825#discussion_r223111783

For this code:

https://github.com/rust-lang/rust/blob/fe8ace8da3e2dba750fe09587628b2c36d303267/src/test/ui/borrowck/borrowck-move-from-unsafe-ptr.rs#L12-L15

which produces this diagnostic output: 

https://github.com/rust-lang/rust/blob/fe8ace8da3e2dba750fe09587628b2c36d303267/src/test/ui/borrowck/borrowck-move-from-unsafe-ptr.nll.stderr#L4-L8

@nikomatsakis made this comment about the HELP on line 8:

> Pre-existing but: it is...strange that we make this suggestion. It seems almost certainly wrong. It doesn't preserve the type or "intent" of the code in any particular way...? It's also distinct from what the AST checker says, which is to suggest `&*x` (though I would argue that is *also* wrong, for similar reasons). It feels like the best suggestion *might* be `ptr::read` but I'm sort of inclined to just not suggest anything at all.

**Comment by estebank** [comment]
https://github.com/rust-lang/rust/blob/b8b4150c042b06c46e29a9d12101f91fe13996e0/src/librustc_mir/borrow_check/move_errors.rs#L353-L406

**Comment by pnkfelix** [comment]
How bad might it be to just remove this suggestion entirely (vs attempting to fine tune when we emit it)? Can we easily weigh the good it brings vs the harm it causes?

**Comment by pnkfelix** [comment]
NLL triage. Tagging as P-medium priority.

**Comment by oli-obk** [comment]
Diagnostics triage: marking as E-easy since it's just removing the suggestion

**Comment by u32i64** [comment]
Shouldn't this be closed because #61332 is now merged?
