### ISSUE TITLE
LLVM failures cause exit status 1

### ISSUE THREAD

**Issue by euclio** [rust-lang/rust#54992]
Related to #51971.

If a fatal error occurs in LLVM, the compiler exits with status 1. This is problematic, because if a test is expecting a compilation failure, the test could still pass. It also makes it difficult to test for the presence of ICEs in general.

A simple fix would be to patch our copy of LLVM to exit with 101 (like ICEs) in `report_fatal_error`, but any other ideas would be appreciated.

**Comment by cuviper** [comment]
Those error functions all call `sys::RunInterruptHandlers()`, which sounds like it could be a great hook for us, but then that only calls `RemoveFilesToRemove()`. :/

**Comment by cuviper** [comment]
There is [`install_fatal_error_handler`](https://github.com/rust-lang/llvm/blob/ee7a10441d0f8c7cd5c7356a8e5f46cba5791082/include/llvm/Support/ErrorHandling.h#L30-L47) though, and that handler gets called first.

**Comment by euclio** [comment]
That sounds nice, but if we exit with 101 in the handler won't we be skipping any other cleanup (`sys::RunInterruptHandlers`, plus any future cleanup that gets added there)? Or could we just call it in our handler?

I'm interested in putting a patch together, but I'm unfamiliar with how we link Rust to C++. The error handler needs to be able to consume a `std::string`.

**Comment by cuviper** [comment]
> or simply panic

We shouldn't do anything that looks like exception unwinding.  See `install_fatal_error_handler`:

```cpp
  /// It is dangerous to naively use an error handler which throws an exception.
  /// Even though some applications desire to gracefully recover from arbitrary
  /// faults, blindly throwing exceptions through unfamiliar code isn't a way to
  /// achieve this.
```

> won't we be skipping any other cleanup (`sys::RunInterruptHandlers`, plus any future cleanup that gets added there)? Or could we just call it in our handler?

I think we can call it -- it's publicly declared in `llvm/Support/Signals.h`.  We might want to keep a note to make sure we check for new cleanup needed when we update LLVM though.

> I'm interested in putting a patch together, but I'm unfamiliar with how we link Rust to C++. The error handler needs to be able to consume a `std::string`.

We bridge C++ code in [`src/rustllvm/`](https://github.com/rust-lang/rust/tree/master/src/rustllvm).  You could just write our handler in C++ there, and add some C-FFI function for `librustc_codegen_llvm` to call and hook that up.
