### ISSUE TITLE
Bound TryFrom::Error to Debug

### ISSUE THREAD

**Issue by lu-zero** [rust-lang/rust#55006]
Otherwise code such as

``` rustc
foo.try_into().unwrap()
```

Would require a quite verbose trait bound.

**Comment by clarcharr** [comment]
With RFC 2289 you can just do `T: TryFrom<Error: Debug>` which isn't that bad of a bound.

IMHO, if there were a way to move `Error` to libcore, I would recommend requiring that instead. But I'm not quite sure that's the best.

We could also do `Debug + Send + Sync` but that might be too restrictive.

Basically, I don't know if this is the best way to go about it.

**Comment by scottmcm** [comment]
While I agree that all types should generally be `Debug`, is there any precedent in core for requiring a bound like this?  People bothered by the verbosity could just use a derived trait and blanket impl to not need to repeat it, or eventually probably just a trait alias.

**Comment by lu-zero** [comment]
I'd dare to say that if you return a Result your error type must be Debug...

**Comment by dhardy** [comment]
> People bothered by the verbosity could just use a derived trait and blanket impl to not need to repeat it

Way to make `std` hard to use for no reason.

Unfortunately this would now be a breaking change to introduce, but *if* it could be deemed acceptable would very much be worth doing IMO.

**Comment by sfackler** [comment]
TryFrom is stable, we are not going to be adding bounds to it.

**Comment by dhardy** [comment]
Unfortunate.

There is an alternative solution, but it is considerably more complex: https://github.com/rust-lang/rfcs/issues/2207
