### ISSUE TITLE
'error[E0405]: cannot find trait 'trait_name' in the crate root' while custom a derive

### ISSUE THREAD

**Issue by fpcsong** [rust-lang/rust#55026]
I write a test on costom derives with rust version  **rustc 1.31.0-nightly (77af31408 2018-10-11)**, here is my project structure:
```
├── countable_macro
│   ├── Cargo.toml
│   └── src
│       └── lib.rs
├── countable_trait
│   ├── Cargo.toml
│   └── src
│       └── lib.rs
└── test_macro
    ├── Cargo.lock
    ├── Cargo.toml
    └── src
        └── main.rs
```
dependencies was set correctly so that I can call function in **countablr_trait/src/lib.rs** in **test_macro/src/main.rs**, and I can compile **countable_macro** correctly, but when I try to derive a trait in **countablr_trait/src/lib.rs**, I got a error "cannot find trait `Countable` in the crate root'".
**countable_macro/src/lib.rs**
```rust
extern crate proc_macro;
extern crate syn;
#[macro_use]
extern crate quote;
use crate::proc_macro::TokenStream;

#[proc_macro_derive(Countable)]
pub fn summable_fields(input: TokenStream) -> TokenStream {
    let ast = syn::parse(input).unwrap();
    let expanded = expand_summable_fields(&ast);
    expanded
}
fn expand_summable_fields(ast: &syn::DeriveInput) -> TokenStream {
    
    let n = ast.attrs.len();
    let name = &ast.ident;
    let (impl_generics, ty_generics, where_clause) = ast.generics.split_for_impl();
    let gen = quote! {
        impl #impl_generics ::Countable for #name #ty_generics #where_clause {
            fn count_fields(&self) -> usize {
                #n
            }
        }
    };
    gen.into()
}

```

**countable_trait/src/lib.rs**
```rust
pub trait Countable {
	fn count_fields(&self) -> usize;
}
pub fn add_one(x : i32)->i32{
    x+1
}
```
**test_macro/src/main.rs**
```rust
#![feature(proc_macro)]
#[macro_use]
extern crate countable_macro;
extern crate countable_trait;
use countable_trait::Countable;

#[derive(Countable)]
struct S1 {
    x: u32,
    y: u8,
}
#[derive(Countable)]
struct S2 {
    s: String,
    x: u64,
    y: i64,
}
#[derive(Countable)]
struct S3 {
    s: String,
}
fn main() {
    countable_trait::add_one(4);
    let s1 = S1 { x: 32, y: 8 };
    let s2 = S2 {
        s: "test".into(),
        x: 1,
        y: 2,
    };
    let s3 = S3 { s: "test3".into() };
}

```

build got error:
```
error[E0405]: cannot find trait `Countable` in the crate root
 --> src/main.rs:7:10
  |
7 | #[derive(Countable)]
  |          ^^^^^^^^^ not found in the crate root
help: possible candidate is found in another module, you can import it into scope
  |
5 | use countable_trait::Countable;
  |

```

**Comment by fpcsong** [comment]
> Looks like you are using 2018 edition and absolute paths (`::foo`) are used for extern crates in it, `crate::Countable` should work in this case.
> 
> The error message shouldn't say "in the crate root" though.

thanks for your help but it doesn't work for me. It says 
```
use crate::Countable;
  |     ^^^^^^^^^^^^^^^^ no `Countable` in the root
```
I test several times, when I delete '#[derive(Countable)]' line the code in description can works, so I think there may some problem with the custom derives

**Comment by dhardy** [comment]
You need to remember that macros merely inject code; what code do you want the macro to inject? You can use:

- `Countable` — since you already import the trait in the target module with `use countable_trait::Countable;`, this should work.
- `countable_trait::Countable` — since the target crate directly depends on `countable_trait`, this should work (assuming Edition 2018; for classic Rust you need to prepend `::`)

Note that your `countable_macro` crate doesn't need to depend on the `countable_trait` crate. You can in fact do the reverse and use the macro inside the same crate which defines the trait, except in this case the second option above won't work (at least in Edition 2018).

Unfortunately though I don't think there is a perfect solution which "just works" in all contexts.

**Comment by fpcsong** [comment]
I have find the reason, it is all because the **syn** (maybe the version problem), when I rewrite the following line, it works but get a wrong result, but, it is another question about **syn**.

```rust

 let gen = quote! {
        impl #impl_generics ::Countable for #name #ty_generics #where_clause {
            fn count_fields(&self) -> usize {
                #n
            }
        }
    };
```
change to 

```rust
let gen = quote! {
        // #ast
        impl Countable for #name {
            fn count_fields(&self) -> usize {
                #n
            }
        }
    };

```
so there is no problem with the path :)
