### ISSUE TITLE
rustup target add powerpc64le-unknown-linux-musl fails

### ISSUE THREAD

**Issue by malbarbo** [rust-lang/rust#55020]
With the message:

```
error: component 'rust-std' for 'powerpc64le-unknown-linux-musl' is unavailable for download
```

It is show in the output of `rustup target list`. It seems than powerpc64le-unknown-linux-musl is in the build manifest but is not built.

**Comment by pietroalbini** [comment]
`powerpc64le-unknown-linux-musl` is not present in our [platform support list](https://forge.rust-lang.org/platform-support.html), so we don't guarantee official builds will be available, or that those builds will work.

cc @rust-lang/infra, we should probably clarify that the target is tier 3.

**Comment by malbarbo** [comment]
I think that is enough to remove the target from [here](https://github.com/rust-lang/rust/blob/e6381a7f37402dd5f346256b3773ae2e72853fc3/src/tools/build-manifest/src/main.rs#L94).
