### ISSUE TITLE
Destructuring arguments in trait methods with bodies fails with a syntax error

### ISSUE THREAD

**Issue by ivanbakel** [rust-lang/rust#55036]
You can't destructure an argument in a trait method which has code in the body.

### Minimal example

```rust
struct Foo { 
    bar: Bar
}

struct Bar;

trait Baz {
    fn foo_in_trait(Foo { bar }: Foo) {
        do_nothing();
    }
}

fn foo(Foo { bar }: Foo) {
    do_nothing();
}

fn do_nothing() {
}
```

### Expectation

This should work fine. Destructuring an argument in a trait method seems totally reasonable.

### Reality

The line `fn foo_in_trait(Foo { bar }: Foo) {` gives errors

```
error: expected one of `!`, `(`, `)`, `+`, `,`, `::`, or `<`, found `{`
 --> test.rs:8:25
  |
8 |     fn foo_in_trait(Foo { bar }: Foo) {
  |                         ^ expected one of 7 possible tokens here

error: expected one of `!`, `(`, `)`, `+`, `-`, `::`, `<`, `_`, `box`, `false`, `mut`, `ref`, or `true`, found `{`
 --> test.rs:8:25
  |
8 |     fn foo_in_trait(Foo { bar }: Foo) {
  |                         ^ expected one of 13 possible tokens here

error: expected one of `async`, `const`, `extern`, `fn`, `type`, `unsafe`, or `}`, found `:`
 --> test.rs:8:32
  |
8 |     fn foo_in_trait(Foo { bar }: Foo) {
  |                                ^ expected one of 7 possible tokens here
```

### Meta

rustc version: `rustc 1.31.0-nightly (5af0bb830 2018-10-10)`

### Let's speculate

This might be related to #53051, maybe? In particular, I would expect to see the error message from that pull request in this case, if this were validly invalid code.

**Comment by ehuss** [comment]
> This should work fine.

FWIW, your sample code is now valid in the 2018 edition.

**Comment by ivanbakel** [comment]
I think it might be a regression brought about by the recent PR.

**Comment by ehuss** [comment]
Oh, you're right, my bad!

It looks like the error was regressed by #54415.

**Comment by Centril** [comment]
cc https://github.com/rust-lang/rfcs/pull/2522

**Comment by petrochenkov** [comment]
Fixed in https://github.com/rust-lang/rust/pull/57251
