### ISSUE TITLE
Warn for extra semicolons

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust#55038]
I suggest to give some kind of warning or hint to remove the double ;; here:

```
fn main() {
    println!("hello");;
}
```

The D language is different from Rust so the situation isn't directly comparable, but in a case like this gives a warning like this:

`temp.d(2,22): Warning: use '{ }' for an empty statement, not a ';'`

See also the same suggestion for Clippy: https://github.com/rust-lang-nursery/rust-clippy/issues/3305

**Comment by Centril** [comment]
cc https://github.com/rust-lang/rfcs/pull/2479
