### ISSUE TITLE
Option should have method `get_or_default`

### ISSUE THREAD

**Issue by Boscop** [rust-lang/rust#55042]
There is some symmetry between the methods of `HashMap`'s `Entry` and `Option`, e.g. 
https://doc.rust-lang.org/nightly/std/collections/hash_map/enum.Entry.html#method.or_insert
https://doc.rust-lang.org/nightly/std/option/enum.Option.html#method.get_or_insert

https://doc.rust-lang.org/nightly/std/collections/hash_map/enum.Entry.html#method.or_insert_with
https://doc.rust-lang.org/nightly/std/option/enum.Option.html#method.get_or_insert_with

But the analogue of `Entry`'s [`or_default`](https://doc.rust-lang.org/nightly/std/collections/hash_map/enum.Entry.html#method.or_default) is missing from `Option`:
`Option` should have a method `get_or_default`, that does conceptually the same as `or_default` by doing `self.get_or_insert_with(|| Default::default())` (returns `&mut T`).

(This use case occurs often in some projects of mine..)

**Comment by clarcharr** [comment]
This is already available as [`Option::unwrap_or_default`](https://doc.rust-lang.org/std/option/enum.Option.html#method.unwrap_or_default).

**Comment by Centril** [comment]
Closing as completed.

**Comment by Boscop** [comment]
@clarcharr It's not the same because it consumes the `Option` instead of mutating it. 
One can do `opt = Some(opt.unwrap_or_default());` but then one doesn't have a `&mut T` to work with, that refers to the content of the `Option`! 
In the use-cases where I needed this, I need to have the `&mut T` from that point on, just like with `Entry`'s `or_default`.
So I think it's still worth adding the `get_or_default` method that returns a `&mut T` to the contents of the `Option`.
(In fact, I need this behavior more often with `Option` than with `HashMap`'s `Entry`.)
Can we please re-open this issue? :)

**Comment by CasperN** [comment]
Bump, please consider reopening this.

```rust
self.get_or_default()
```
is 20 characters shorter than
```rust
self.get_or_insert_with(Default::default)
```
