### ISSUE TITLE
[rustdoc] discoverability of parameter and return type search results

### ISSUE THREAD

**Issue by memoryruins** [rust-lang/rust#55056]
spawned from https://github.com/onur/docs.rs/issues/241

The ability to search by parameter and return types sometimes goes undiscovered, even when the feature is desired (see the issue above). Part of this might be because the options do not appear until after the first search.

Currently, results look like the following. It seems benign if one knows to read it as "Results for PAddr In Names", but that might not be immediately obvious.

![paddr_name](https://user-images.githubusercontent.com/6868531/46912902-e23fd400-cf4f-11e8-9e63-cf349636b778.png)

Some ideas:
Move the bar closer to the search bar (removed the "In"s). This change alone might not be entirely obvious either, although it gives the tabs more breathing space.
![paddr_edit_2](https://user-images.githubusercontent.com/6868531/46912755-56787880-cf4c-11e8-9220-863ecce84998.png)

To help show that the tabs affect the search results, we could change the tab titles to be read as actions.
![paddr_edit](https://user-images.githubusercontent.com/6868531/46912749-203af900-cf4c-11e8-9b75-1b2b96158ae9.png)

from @Havvy 
> I like both suggestions. I even have one more to add. In the "Results for X", it should say "Results for X in Parameters" when searching parameters. Though that won't help with discoverability. "Results for X in Names" would look weird though, so leave that one off.

Variation of the above:
```
Name Results for X
Parameter Results for X
Return Type Results for X
```

**Comment by ExpHP** [comment]
A variation on the third option (remove two of the "by"s):

Search by Name
Search Parameters
Search Return Types

**Comment by GuillaumeGomez** [comment]
I prefer the first option (the "in" one).

**Comment by memoryruins** [comment]
Do you mean the original “In” screenshot or first as in Havvy’s variation? (both valid)
