### ISSUE TITLE
Rename deref() to borrow() in Deref Trait

### ISSUE THREAD

**Issue by felipenoris** [rust-lang/rust#55074]
The method name `deref` in the `Deref` trait is misleading. When you execute it, you get a reference that will be used to implement the dereference logic later.

In the Deref Coercion, if `m` is of a type that implements `Deref`, then `&m`  will actually execute `m.deref()`.  A better naming would be `m.borrow()` in this case. This is naming is currently used by `RefCell`.

**Comment by Havvy** [comment]
It would be an extremely breaking change to change the method name of a stdlib trait. This cannot be done.

**Comment by oli-obk** [comment]
Such changes would need to go through the RFC process and can't be handled in an issue. But I agree with @Havvy in that I see no way this can be done without being a breaking change
