### ISSUE TITLE
Refiling "#[repr(simd)] struct(isize, isize) not allowed"

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#55078]
Refiling https://github.com/rust-lang/rfcs/issues/2513 here.

This probably does not require an RFC (according to me and @nrc).
However, we'd like @BurntSushi and @alexcrichton to sign off on this.

cc @rust-lang/compiler
cc @gnzlbg 

> Repro (playground: https://play.rust-lang.org/?gist=efa6e5caf752ccca651014ae5009feb8&version=nightly&mode=debug&edition=2015):
> 
> ```rust
> #![feature(repr_simd)] 
> 
> #[repr(simd)] struct A(isize, isize); // ERROR
> 
> #[cfg(target_pointer_width = "64")]
> type isize_ = i64;
> 
> #[cfg(target_pointer_width = "32")]
> type isize_ = i32;
> 
> #[repr(simd)] struct B(isize_, isize_); // Q: Is this ok?
> ```
> 
> produces
> 
> ```
> error[E0077]: SIMD vector element type should be machine type
>  --> src/main.rs:3:15
>   |
> 3 | #[repr(simd)] struct A(isize, isize);
>   |               ^^^^^^^^^^^^^^^^^^^^^^^
> 
> error: aborting due to previous error
> ```
> 
> I am wondering why aren't `isize` and `usize` allowed ? I currently work around this to implement simd vectors of pointers, but maybe that's broken for reason I don't understand?

**Comment by Centril** [comment]
@rfcbot f? @BurntSushi
@rfcbot f? @alexcrichton 
@rfcbot merge

**Comment by Centril** [comment]
- [ ] signoff from @BurntSushi 
- [ ] signoff from @alexcrichton

**Comment by Centril** [comment]
@rfcbot concern signoff-from-alex-and-andrew

**Comment by scottmcm** [comment]
This is just adding another type to a feature that isn't on the path to stabilization, right?

@rfcbot reviewed

**Comment by Centril** [comment]
@scottmcm yep :) (https://github.com/rust-lang/rust/issues/27731 tracks `repr(simd)` in general)

**Comment by gnzlbg** [comment]
While `#[repr(simd)] struct A(isize, isize);` currently errors, `#[repr(simd)] struct A<T>(T, T); type B = A<isize>;` currently accidentally works on nightly. 

The `packed_simd` crate has used this "bug" to export vectors of pointers and vectors of `usize`/`isize`/`msize` for a while and uses them in some of the examples (e.g. the `examples/aobench` `tiled.rs` algorithm). 

Lifting the restriction makes something that's already possible and useful a bit easier to do. Also, the current plan is to never stabilize `repr(simd)`, but to expose it through a `std` API. On stable, some of these are already exposed via `std::arch` (e.g. `__m128`), but none of them interact with `isize`/`usize` - so this does not interact with stable types at all. 

Something like [RFC2366](https://github.com/rust-lang/rfcs/pull/2366) with support for packed SIMD vectors of pointers would need to be added to the language for this to land on stable.

**Comment by alexcrichton** [comment]
The `#[repr(simd)]` feature currently (and I can't forsee at least) have any path to stabilization. In that sense I would not personally recommend working on this feature as it's basically just a building block for `std::arch`, which we must expose to the language somehow.

I suspect, however, that fixing this is probably a few lines of a patch. While I wouldn't at all prioritize this I wouldn't stop it if someone were motivated.

**Comment by varkor** [comment]
> I suspect, however, that fixing this is probably a few lines of a patch.

Namely, removing this line:
https://github.com/rust-lang/rust/blob/423d8109868c1f926f2cfcc3bff980c3daa515fd/src/librustc/ty/sty.rs#L1748

**Comment by Centril** [comment]
I'll interpret https://github.com/rust-lang/rust/issues/55078#issuecomment-429884227 as "signoff" :)

@rfcbot resolve signoff-from-alex-and-andrew

**Comment by gnzlbg** [comment]
FWIW I actually had forgotten that I filled the RFC issue that resulted in this one being open. 

I just wanted to know why did someone go through the trouble of preventing `isize`/`usize` in vector types. I couldn't find any reasons for this, the code has no comments, and we have been using them for a long time in `packed_simd` just fine. I just wanted to triple-check that we didn't miss anything.

I'd guess the answer is that no, we didn't miss anything.

Since this "bug" is easy to fix, maybe it should be E-Easy and mentoring available. 

But I wasn't suggesting that we should fix this. It is trivial to work around (and fix), and it only impacts perma-unstable internal rustc APIs. Having an FCP about this feels extremely overkill.

**Comment by eddyb** [comment]
@gnzlbg It's very possible the code used a categorization that dates back to a time where Rust had (or wanted to have?) bigints for `int`/`uint` and the types with numbers in them were "machine integers".

**Comment by varkor** [comment]
Mentoring instructions:
1. Remove the line mentioned in https://github.com/rust-lang/rust/issues/55078#issuecomment-429902724.
2. Add a test like the mentioned in the issue post: https://github.com/rust-lang/rust/issues/55078#issue-369959177.

**Comment by polybuildr** [comment]
Looks like this was fixed in PR #59201 and merged by bors. Should this issue be closed now?
