### ISSUE TITLE
"Notable Traits" for &[u8] includes Write, which is only on &mut [u8]

### ISSUE THREAD

**Issue by scottmcm** [rust-lang/rust#55082]
https://doc.rust-lang.org/nightly/std/string/struct.String.html#method.as_bytes

The popup has
> ### Important traits for &'a [u8]
> `impl<'a> Read for &'a [u8]`
> `impl<'a> Write for &'a mut [u8]`

`Write` seems like it shouldn't be in that list.

**Comment by GuillaumeGomez** [comment]
cc @QuietMisdreavus

**Comment by scottmcm** [comment]
Triage: still repros on the current nightly.
