### ISSUE TITLE
Incorrect inference of lifetime bound for existential type

### ISSUE THREAD

**Issue by jonhoo** [rust-lang/rust#55099]
Consider the following code ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2015&gist=05a628733369900fde16d8a122f5c52d)):
```rust
fn reply<'a, I: 'a>(_: I) -> impl Future<Item = (), Error = ()> + 'static {
    // do something with argument
    // then build future that does not borrow I
    futures::future::ok(())
}

fn foo(foo: String) -> Box<Future<Item = String, Error = ()>> {
    Box::new(reply(&foo).map(move |_| foo))
}
```

This code doesn't compile because `impl Trait` [assumes](https://github.com/rust-lang/rfcs/blob/master/text/1951-expand-impl-trait.md#assumption-2-treating-all-type-variables-as-in-scope-for-impl-trait-suffices-for-the-vast-majority-of-cases) that all type parameters are in scope for the concrete type. This [may](https://github.com/rust-lang/rust/issues/34511#issuecomment-383248062) get fixed eventually, but for the time being, we can work around it using `existential type` (rust-lang/rfcs#2071; [playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2015&gist=05a628733369900fde16d8a122f5c52d)):

```rust
#![feature(existential_type)]
existential type Reply: Future<Item = (), Error = ()>;

fn reply<'a, I: 'a>(_: I) -> Reply { futures::future::ok(()) }

fn foo(foo: String) -> Box<Future<Item = String, Error = ()>> {
    Box::new(reply(&foo).map(move |_| foo))
}
```

However, this pattern does not compose. This example fails to compile ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2015&gist=895b570d6f05bee2562f11fdfe9662bb)):

```rust
#![feature(existential_type)]

struct Foo<'a> {
    x: &'a mut (),
}

existential type F1: Future<Item = (), Error = ()>;
existential type F2: Future<Item = (), Error = ()>;

impl<'a> Foo<'a> {
    fn foobar(&mut self) -> F1 {
        futures::future::ok(())
    }

    fn reply<I>(&mut self, _: I) -> F2 {
        self.foobar().and_then(move |_| futures::future::ok(()))
    }
}
```

with the error

```
error: non-defining existential type use in defining scope
  --> src/lib.rs:19:40
   |
19 |       fn reply<I>(&mut self, _: I) -> F2 {
   |  ________________________________________^
20 | |         self.foobar().and_then(move |_| futures::future::ok(()))
21 | |     }
   | |_____^ lifetime `'a` is part of concrete type but not used in parameter list of existential type

error: type parameter `I` is part of concrete type but not used in parameter list for existential type
  --> src/lib.rs:19:40
   |
19 |       fn reply<I>(&mut self, _: I) -> F2 {
   |  ________________________________________^
20 | |         self.foobar().and_then(move |_| futures::future::ok(()))
21 | |     }
   | |_____^
```

I'm not entirely sure _why_ this fails, but it seems like the code should be accepted?

/cc @Nemo157

**Comment by jonhoo** [comment]
Or a somewhat simpler example with just a single existential ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2015&gist=940ab6293ff85539485ecbc332ff11af)):
```rust
#![feature(existential_type)]

struct Foo<'a> {
    x: &'a mut (),
}

existential type F: Future<Item = (), Error = ()>;

impl<'a> Foo<'a> {
    fn foobar(&mut self) -> Result<(), ()> {
        Ok(())
    }

    fn reply<I>(&mut self, _: I) -> F {
        self.foobar().into_future().and_then(move |_| futures::future::ok(()))
    }
}
```

**Comment by jonhoo** [comment]
@estebank Maybe also tag with `A-impl-trait` since it's related to existentials? And possibly `T-compiler` (or is this `T-lang` terretority?)

**Comment by Arnavion** [comment]
[Smaller repro without `futures` dependency:](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=3343d8d3abdef80b375b0105c2870f53)

```rust
#![feature(existential_type)]

trait Future {
    type Item;
}

struct AndThen<F>(F);

impl<F> Future for AndThen<F> {
    type Item = ();
}

struct Foo<'a> {
    x: &'a mut (),
}

existential type F: Future<Item = ()>;

impl<'a> Foo<'a> {
    fn reply(&mut self) -> F {
        AndThen(|| ())
    }
}
```

Replacing `AndThen(|| ())` with `AndThen(())` compiles fine.
