### ISSUE TITLE
high-level rustc-guide docs on chalk-integration

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#55100]
The existing rustc-guide docs need some organization and love. Let's start with a high-level overview on the various moving parts and their relationship to one another.

**Comment by sunjay** [comment]
Hello! I am available to help work on this! :smile:

**Comment by tmandry** [comment]
Here are some topics we _could_ cover in a high-level overview...

- what is trait solving? which things does it do, which things does it not?
- introduce trait solving goals in terms of logical (prose) statements
- introduce queries, what they are used for

Basically, cover the motivation and most basic concepts in the introduction, and the further chapters can flesh out those ideas in much greater detail (like they already do).

Glossary terms: (many of these may link back to a page with more details)
- canonical type
- inference variable
- bound type
- bound variable
- environment
- clause
- program clause
- goal
- domain goal
- universe
- placeholder

As @nikomatsakis was saying, we may want to hop on a call to talk it over soon.

**Comment by sunjay** [comment]
Thanks for writing that up! These are great things to cover!

> what is trait solving? which things does it do, which things does it not?

This is somewhat covered here:
https://rust-lang-nursery.github.io/rustc-guide/traits/resolution.html

> introduce trait solving goals in terms of logical (prose) statements

We somewhat do this here, though not as much in prose:
https://rust-lang-nursery.github.io/rustc-guide/traits/lowering-to-logic.html

> introduce queries, what they are used for

I actually don't think we do this! Which is somewhat surprising given how fundamental it is. Great idea!

> Glossary terms:

I definitely think these need to be defined. All of these are fundamental to understanding the way we communicate about chalk.

> high-level rustc-guide docs on chalk-integration

This is the issue title. Are we focusing on docs about chalk itself and its concepts, or about documenting the way that chalk is being integrated into the compiler so more people can contribute to it?

**Comment by tmandry** [comment]
Regarding where things are already covered, I did see those (thanks for adding pointers). IMHO one problem right now is that most of the knowledge is _there_, but split up in a way that it's hard to grasp the big picture. I think it makes sense to put them all together in a single introduction at _a very high level of abstraction_ (hence my emphasis on prose – but I could be convinced otherwise).

The old-style traits is eventually going away, so I personally think it's okay to repeat some stuff from there.

Good point re: issue title! I may have misunderstood the original goal. In any case, those are my thoughts on how to better cover chalk concepts 😄

**Comment by nikomatsakis** [comment]
> introduce queries, what they are used for

By this, do you mean the compiler's queries, or "trait queries"? The compiler's query system is introduced here:

https://rust-lang-nursery.github.io/rustc-guide/query.html

I think that the intended interaction between the compiler query system and the chalk trait engine is something we should talk through and document. To some extent, it's a work-in-progress =)

**Comment by tmandry** [comment]
> By this, do you mean the compiler's queries, or "trait queries"?

Yes, trait queries is what I meant.

On second thought, there should really be a focus on any “public” API (query or otherwise) that other parts of the compiler can use. IME, knowing exactly what the boundaries of a component are is just as important for understanding as knowing what’s in it.

**Comment by tmandry** [comment]
I just posted a PR to do some light editing and refactoring of the traits chapter: https://github.com/rust-lang-nursery/rustc-guide/pull/219

**Comment by tmandry** [comment]
Okay, I put together a list of all the tasks I can think of. Some of these are quite simple, as they're just moving content around or copying it from @nikomatsakis blog posts :)

If you want to work on something, simply edit this comment and put your name at the end of the line.

- [ ] SLG Solver (see [this blog post](http://smallcultfollowing.com/babysteps/blog/2018/01/31/an-on-demand-slg-solver-for-chalk/))
  - I think this could be easily done by copying from the blog post, perhaps with light edits and/or additions for context
- [ ] Context trait: see [this paper doc](https://paper.dropbox.com/doc/chalk-doc-talk--AQP4v7z~~toQHwwlHe7Hp~A6AQ-dHA8ZmYXpd8d9bUuKIey9)
  - this could be part of the SLG section
- [ ] Unification: see [blog1](http://smallcultfollowing.com/babysteps/blog/2017/03/25/unification-in-chalk-part-1/), [blog2](http://smallcultfollowing.com/babysteps/blog/2017/04/23/unification-in-chalk-part-2/)
- [ ] FInd a home for Universes (currently documented under [region inference](https://rust-lang-nursery.github.io/rustc-guide/borrow_check/region_inference.html#placeholders-and-universes))
- [ ] Coherence (please add pointers if you have them!)
- [ ] Chalk Overview additions
  - add new module structure
  - add “elaborate test harness” concept which @nikomatsakis always uses to describe chalk
- [ ] Glossary: see [chalk glossary](https://github.com/rust-lang-nursery/chalk/blob/master/GLOSSARY.md), [this comment](https://github.com/rust-lang/rust/issues/55100#issuecomment-430071173)
- [ ] The lowering module in rustc
  - add info about how e.g. `Normalize` is actually implemented, `TypeEqual`

---

I think it helps to know what we're shooting for. Here's a strawman for the eventual structure. Please let me know what you think!

0. Intro
1. Lowering to logic
  i. Goals and clauses
  ii. Equality and associated types
  iii. Implied bounds
  iv. Region constraints
  v. The lowering module in rustc
  vi. Lowering rules
  vii. Well-formedness checking
2. Solving logic programs
  i. Unification
  ii. Universes
  iii. The SLG Solver (sub-sub-sections: `Context` trait)
3. Canonical queries
  i. Canonicalization
4. An Overview of Chalk
5. Bibliography

**Comment by oli-obk** [comment]
T-types triage: closing as it's not tracking anything particularly actionable. We can work on docs or open specific issues for things that should be documented.

**Comment by spastorino** [comment]
Maybe we should open an issue like this in rustc-dev-guide itself.
