### ISSUE TITLE
emit unused_attributes lint for silly attributes

### ISSUE THREAD

**Issue by zackmdavis** [rust-lang/rust#55112]
We already have an `UnusedAttributes` late lint pass for attributes that don't get [marked as having been used somewhere](https://github.com/rust-lang/rust/blob/df0d6ad9c1510630b234f6bb96a69a081de0b307/src/libsyntax/attr/mod.rs#L42-L47), but recent discussion has touched on the idea of also directly (during normal complication, not as a lint pass) issuing the lint for attributes that don't make much sense (but which we don't want to go to the length of declaring errors, _e.g._, for backwards-compatibility reasons). These include:
 - [x] [`#[derive()]`](https://github.com/rust-lang/rust/issues/54651#issuecomment-425565263)
 - [x] ~[`#[must_use]` on functions with unit or uninhabited return type](https://github.com/rust-lang/rust/issues/54828#issuecomment-427246850)~
 - [ ] [`#[allow()]`, `#[warn()]`, _&c._](https://github.com/rust-lang/rust/pull/54683#discussion_r225381179)

**Comment by varkor** [comment]
I think "#[must_use] on functions with unit or uninhabited return type" should be a Clippy lint rather than a compiler lint.

**Comment by Centril** [comment]
I've stricken `#[must_use]` per @varkor's note.

**Comment by ehuss** [comment]
Posted #88681 which adds some checks for empty attributes like `#[allow()]`.
