### ISSUE TITLE
path suggestions in Rust 2018 should point out the change in semantics

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#55130]
In an example like this one ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=97c11a30f8237100fac6f8dd8ae5ab17)):

```rust
#![warn(rust_2018_idioms)]

mod bar {
    pub fn x() { }
}

mod baz {
    use bar::x;
}

fn main() {
}
```

we get the following output in Rust 2018:

```
error[E0432]: unresolved import `bar`
 --> src/main.rs:8:9
  |
8 |     use bar::x;
  |         ^^^ Did you mean `crate::bar`?
```

It'd be nice to have an additional note:

```
error[E0432]: unresolved import `bar`
 --> src/main.rs:8:9
  |
8 |     use bar::x;
  |         ^^^ Did you mean `crate::bar`?
  |
  | = note: `use` statements changed in Rust 2018; read more at XXX
```

where `XXX` is probably https://rust-lang-nursery.github.io/edition-guide/ ?

**Comment by pnkfelix** [comment]
has a PR in flight. no discussion needed AFAICT. removing nomination tag.
