### ISSUE TITLE
Bug?  `ptr::offset` has different behaviors under different Rust versions

### ISSUE THREAD

**Issue by ZhangHanDong** [rust-lang/rust#55143]
```rust
fn main() {
    let s: &str = "Rust";
    let ptr: *const u8 = s.as_ptr();
    unsafe {
        println!("{:?}", *ptr.offset(1) as char); // u
        println!("{:?}", *ptr.offset(3) as char); // t
        println!("{:?}", *ptr.offset(255) as char); // ÿ
    }
}
```

[code - playground](https://play.rust-lang.org/?version=beta&mode=debug&edition=2018&gist=e64cc40b983ed7fd1236ae58f3e5a93e)

Output in Beta : 

```
'u'
't'
' '
```

But in Stable and Nightly：

```
'u'
't'
'ÿ'
```

**Comment by rkruppe** [comment]
This is not a bug. Executing `ptr.offset(255)` results in Undefined Behavior (["resulting pointer must be either in bounds or one byte past the end of the same allocated object"](https://doc.rust-lang.org/std/primitive.pointer.html#method.offset)), so this program can have any behavior at all.

The specific behavior you're seeing in those two instances is probably just printing the byte that happens to be in memory at address `ptr as usize + 255`.
