### ISSUE TITLE
add a section to the Rustdoc Book about the in-doc settings

### ISSUE THREAD

**Issue by QuietMisdreavus** [rust-lang/rust#55165]
Rustdoc has accumulated a handful of settings that users can toggle as they read docs, but we don't document them anywhere. It would be ideal if we had some documentation about these options in the Rustdoc Book that described their functionality better than the short descriptions shown on the settings page itself.

![image](https://user-images.githubusercontent.com/5217170/47120611-f4ae5c00-d234-11e8-9501-e47e71aa0412.png)

**Comment by DevQps** [comment]
@QuietMisdreavus I don't mind picking this up, unless you want to do this yourself! I do however have some questions!:

- The Rustdoc book you mean is (this one)[https://doc.rust-lang.org/rustdoc/what-is-rustdoc.html] right?
- Do you suggest adding a new section to this book or would you include it in an already existing section?
- What do you believe is not clear / elaborated enough in the short descriptions? I do not know the specific details of each switch are there any side-effects that are not in the short description?

**Comment by steveklabnik** [comment]
Triage: no changes.

The rustdoc book is that one, @DevQps ! I am not a rustdoc maintainer these days (cc @GuillaumeGomez ) but I would probably make a new section. While the short description is good, I think it would make sense to show the options in slightly more detail, for example, maybe a before/after.

**Comment by DevQps** [comment]
@steveklabnik Bit of a late reply :) @GuillaumeGomez Do you have something to add to this? Otherwise I will follow what Steve said!
