### ISSUE TITLE
Tracking issue for [T]::rchunks, rchunks_mut, rchunks_exact, rchunks_exact_mut

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#55177]
Implemented in https://github.com/rust-lang/rust/pull/54580.

These are similar to `chunks`, `chunks_mut`, `chunks_exact`, and `chunks_exact_mut` respectively, but they start from the end of the slice. They differ from calling `.rev()` on those other iterators (which is also possible) when the slice’s length is not a multiple of  the chunk size: the remainder (either a smaller chunk or accessible through a separate method) is at the start of the slice instead of the end.

CC #47115 which tracks `chunks_exact` and `chunks_exact_mut`.

**Comment by sdroege** [comment]
Stabilization of this is in https://github.com/rust-lang/rust/pull/55178 together with `chunks_exact()` and `chunks_exact_mut()`
