### ISSUE TITLE
Update rustdoc to last rustc trait solving update

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/rust#55197]
As seen in [here](https://github.com/rust-lang/rust/pull/54199#issuecomment-421133939).

**Comment by weiznich** [comment]
Is there any pointer what exactly needs to be changed where?

**Comment by GuillaumeGomez** [comment]
No, apparently there is nothing left to update on rustdoc. The problem still lies [here](https://github.com/rust-lang/rust/blob/master/src/librustdoc/clean/blanket_impl.rs#L110).
