### ISSUE TITLE
Method `as_ref` not suggested when it should

### ISSUE THREAD

**Issue by KillTheMule** [rust-lang/rust#55198]
As per https://www.reddit.com/r/rust/comments/9pb3ah/what_cool_stuff_have_you_learned_about_rust/e80zqpc/, I'm reporting a case where the method `as_ref`  is not suggested by the compiler to use to convert an `&Option<T>` to an `Option<&T>`. Here's a [playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=ce328b4e9b10d6bef229de7373744650), the non-working code is

```rust
pub struct Keyword {}

pub struct ParsedLine<'a> {
  pub keyword: Option<&'a Keyword>,
}

impl<'a> From<&'a Option<Keyword>> for ParsedLine<'a>
{
  fn from(k: &'a Option<Keyword>) -> ParsedLine<'a>
  {
      ParsedLine{keyword: k}
  }
}
```
```
error[E0308]: mismatched types
  --> src/main.rs:13:27
   |
13 |       ParsedLine{keyword: k}
   |                           ^ expected enum `std::option::Option`, found reference
   |
   = note: expected type `std::option::Option<&Keyword>`
              found type `&'a std::option::Option<Keyword>`
```

The playground is using stable, I'm seeing this behavior on `rustc 1.31.0-nightly (de3d640f5 2018-10-01)` as well locally. If I should provide more information, let me know :)

**Comment by estebank** [comment]
For both [`Result` (if appropriate)](https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=1df39e74d4c5088c24dce0ea60e572bf) and `Option` it should suggest using `as_ref()`:

```
error[E0308]: mismatched types
  --> src/main.rs:13:27
   |
13 |       ParsedLine{keyword: k}
   |                           ^
   |                           |
   |                           expected enum `std::option::Option`, found reference
   |                           help: use `as_ref` here: `k.as_ref()`
   |
   = note: expected type `std::option::Option<&Keyword>`
              found type `&'a std::option::Option<Keyword>`
```
