### ISSUE TITLE
rustc panic on unwrap in rustc_codegen_llvm::llvm::diagnostic::Diagnostic::unpack when using custom target

### ISSUE THREAD

**Issue by thepowersgang** [rust-lang/rust#55216]
When using [this custom target](https://github.com/thepowersgang/wince-books/blob/master/armv4-mingw32ce.json) to compile libcore (and I'd assume any other crate), rustc ICEs on an unwrap in the above named function.

This unwrap at [diagnostic.rs:88](https://github.com/rust-lang/rust/blob/master/src/librustc_codegen_llvm/llvm/diagnostic.rs#L88) seems to be only able to fail if there's a null reference in LLVM (or in the rustc shim)

**Comment by thepowersgang** [comment]
Correction: The original diagnosis was wrong, the crash is in `InlineAsmDiagnostic::unpack`. it's expecting `instruction` to be non-None/null, but LLVM appears to permit this to be `nullptr`

Reference: 
- https://github.com/rust-lang/rust/blob/master/src/librustc_codegen_llvm/llvm/diagnostic.rs#L120
- https://github.com/llvm-mirror/llvm/blob/88ab670/include/llvm/IR/DiagnosticInfo.h#L162

**Comment by nikic** [comment]
There was an attempt to fix this at #55193, which ran into an assertion on Windows.
