### ISSUE TITLE
Feature request: std::process:success

### ISSUE THREAD

**Issue by mcandre** [rust-lang/rust#55215]
Do not assume that all hosts use zero exit code to indicate success. This convention applies to most operating systems but not all. I'm trying to track down the Reddit thread (?) where I learned this historical tidbit, but I can't find it at the moment.

It would be good for the `std::process` API to provide a `success()` function akin to `abort()`, that automatically feeds a host-specific error code for "success" state into `exit()`. Maybe even rename `exit()` to `exit_custom()` and deprecate with a warning about different operating system conventions around exit codes? This can help Rust code become more cross-platform by default.

**Comment by scottmcm** [comment]
You might be interested in [`ExitCode::SUCCESS`](https://doc.rust-lang.org/std/process/struct.ExitCode.html#associatedconstant.SUCCESS), though that whole struct is in need of someone to put some design work in (https://github.com/rust-lang/rust/issues/48711#issuecomment-390015331) and make an official proposal of where to go with it.

**Comment by jonas-schievink** [comment]
Should this be closed in favor of #48711?

**Comment by Mark-Simulacrum** [comment]
Yes, closing in favor of https://github.com/rust-lang/rust/issues/48711.
