### ISSUE TITLE
It should be unsafe to cast an extern function to a function pointer

### ISSUE THREAD

**Issue by matthewjasper** [rust-lang/rust#55226]
The following code gives a linker error, which arguably shouldn't happen in safe code.

```rust
extern {
    fn doesnt_exist();
}
fn main() {
    println!("{:p}", doesnt_exist as unsafe extern "C" fn());
}
```

[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=eda6bc925330bfabf1ed09e5bdfc648d)

**Comment by rkruppe** [comment]
How is this unsound? Linker errors aren't great, but how do they jeopardize memory safety in any way?

**Comment by matthewjasper** [comment]
Closing as a dupe of #46188 (which shows how this is a soundness issue)

**Comment by rkruppe** [comment]
That issue has nothing to do with linker errors. The only common factor is that it involves an `extern` declaration.

**Comment by rkruppe** [comment]
Ok so apparently we agree it's a different issue from #46188, which means my original question still stands: how is this a soundness issue?

**Comment by anirudhb** [comment]
This seems like a linker problem to me; Rust has no way to fix this without something like a non-executable/null pointer check, which would have performance impacts on casting. For all `rustc` knows, when the code is linked, it could be referring to a global static, but only the linker knows that.

**Comment by Centril** [comment]
@matthewjasper any thoughts on https://github.com/rust-lang/rust/issues/55226#issuecomment-431684846?

**Comment by Mark-Simulacrum** [comment]
To my knowledge this is essentially unfixable without implementing a linker ourselves or somehow catching the linker errors and re-displaying them in a nicer way, both of which seem impossible or out of scope, so I'm going to close this. I agree with folks that this is not a soundness issue.
