### ISSUE TITLE
Blanket implementation docs seem to be missing generic parameters on traits

### ISSUE THREAD

**Issue by scottmcm** [rust-lang/rust#55256]
https://doc.rust-lang.org/nightly/std/mem/union.MaybeUninit.html#impl-From
```rust
impl<T> From for T
```

Expected:
```rust
impl<T> From<T> for T
```

**Comment by GuillaumeGomez** [comment]
I will take a look.

**Comment by jyn514** [comment]
This is now working:
![image](https://user-images.githubusercontent.com/23638587/102278376-b8034b80-3ef7-11eb-80f5-12f4c44be273.png)
