### ISSUE TITLE
Feature request: Splats

### ISSUE THREAD

**Issue by mcandre** [rust-lang/rust#55255]
Could Rust have a way to expand a collection into distinct function call parameters, similar to splats from Ruby and Python?

**Comment by leonardo-m** [comment]
Doing this for tuples could be useful.

**Comment by tikue** [comment]
I don't have an opinion on this, but I'm imagining the syntax would be:

```rust
fn add(x: i32, y: i32) -> i32 { x + y }

fn main() {
    let items = vec![1, 2, 3];
    items.into_iter()
        .enumerate()
        .map(|tuple| add(tuple...))
        ...
}
```

**Comment by memoryruins** [comment]
Using fn_traits on nightly:

```rust
#![feature(fn_traits)]

fn add(x: i32, y: i32) -> i32 {
    x + y
}

fn main() {
    let tuple = (1, 3);
    println!("{}", add.call(tuple));
}
```

[playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2015&gist=02960f50f38cc2c02cfa94f633f0642c)

**Comment by steveklabnik** [comment]
Traige: major new language features go through the RFC process, please pursue this there! Thanks!
