### ISSUE TITLE
Don't require so many explicit bindings for method chains

### ISSUE THREAD

**Issue by mcandre** [rust-lang/rust#55267]
The Rust compiler often nags the developer to explicitly bind expressions to temporary variable names, such as chaining `.join()` method calls on a `std::path::Path` object. When the initial `Path::new(...)` expression is not explicitly bound, the compiler complains that this subexpression does not live until the end of the scope.

That's dumb. Could the compiler do a better job keeping method chains alive until the end of the scope? Perhaps create some variable bindings behind the scenes, on behalf of the developer.

**Comment by Dylan-DPC** [comment]
Closing this issue as no further details were provided
