### ISSUE TITLE
Introduce more powerful (nightly) compiler plugins

### ISSUE THREAD

**Issue by Ekleog** [rust-lang/rust#55277]
I recently came up with a use case that would, I think, require more powerful compiler plugins (that I'm assuming won't reasonably be possible to implement stably anytime soon, hence this not being in the rfcs repo): implementing a MC/DC strategy similar to SQLite's, but with splitting at the crate boundary, so that crates could be independently tested.

To do this, I'd need to instrument every single branch in the crate, before any optimization takes place. And so to add a pass that *modifies* the AST or, preferably, the HIR. (I think there are no optimizations at the HIR level… right? there are none mentioned in the rustc guide at least)

Do you think this is a reasonable feature nightly rust could want?

**Comment by Ekleog** [comment]
And necessarily I forgot to add the link to my current understanding of compiler plugins: I'm assuming current compiler plugins are defined by [this Registry](https://manishearth.github.io/rust-internals-docs/rustc_plugin/registry/struct.Registry.html), maybe I haven't found the right documentation and the feature I wish for is already present?

**Comment by oli-obk** [comment]
The canonical way to modify the compilation is via `driver`s. E.g. clippy has a driver (https://github.com/rust-lang-nursery/rust-clippy/blob/master/src/driver.rs) for running its lints additionally to the full compilation.

I suggest that you write such a driver instead of trying to use the plugin interface.

For instrumenting every branch, the AST and HIR are not the right structures to modify. For one, there is no good way of doing so. I suggest you write a MirPass and register that (similiarly to how clippy registers its lints). You `MirPass` can then instrument every `mir::Terminator`, which are the only places where you can have branchin in MIR.

**Comment by Ekleog** [comment]
Hmm, sounds like it'd solve the issue triggering this report I guess, thanks!

My issue with intrumenting MIR is that there is a risk that MIR is optimized, isn't it? Here the point is really to instrument every branch as written by the developer. And it actually even needs to carry enough information (which I think of propagating through attributes) to be able to mark a branch as “fail-safe” (eg. `a[0]`'s bound-check should be marked as a “fail-safe”, that's not expected to be ever called, but it's also the case of potentially other checks that the user may decide to add), so I'd assume the MIR is already too “low-level”.

To do that I am thinking of modifying is basically the crate code with macros expanded, so I assumed that'd be the AST/HIR? Will read more in the rustc book anyway for more details.

Anyway, feel free to close this issue if you think passes that modify compilation should not be registered via `#![feature(plugin)]` but always via a `driver`, and thanks for the help!

**Comment by oli-obk** [comment]
> My issue with intrumenting MIR is that there is a risk that MIR is optimized, isn't it?

you can insert your MIR pass to run before optimizations.

> a branch as “fail-safe” (eg. a[0]'s bound-check should be marked as a “fail-safe”, that's not expected to be ever called)

bound checks already exist in the MIR in the form of assertions. If you call `foo[x]` on a vector, these won't show up in the MIR though, as you'd just see a function call to `<Vec<T> as Index>::index`

> but it's also the case of potentially other checks that the user may decide to add

Do you have an example of the user-side of this? I currently can't imagine how that would look.

**Comment by oli-obk** [comment]
For now you can emulate such an assert with a macro that produces

```rust
[()][!(must_be_true_condition) as usize];
```

which will generate a MIR assert on the condition

It would be totally cool to lower some asserts directly to MIR asserts, but that's an entirely different story.

> feel free to close this issue if you think passes that modify compilation should not be registered via #![feature(plugin)] but always via a driver

**Comment by Ekleog** [comment]
> For now you can emulate such an assert with a macro that produces
>
> ```rust
> [()][!(must_be_true_condition) as usize];
> ```
>
> which will generate a MIR assert on the condition

Hmm, the idea is more to have a tag similar to `unlikely()` but that'll
be parsed by the compiler driver, actually :)

Anyway, will try to do it with a driver when I get some time!
Thank you for your feedback :)

**Comment by oli-obk** [comment]
Yes of course. I meant so you can start without having to modify the compiler itself. I think that it'll be much easier to get such an intrinsic into the compiler if you have a working prototype that uses the hack.
