### ISSUE TITLE
Missing rust_eh_personality with wasm32-unknown-emscripten

### ISSUE THREAD

**Issue by CryZe** [rust-lang/rust#55276]
When compiling with the wasm32-unknown-emscripten target, the recent nightly compilers can't seem to find the rust_eh_personality symbol. https://travis-ci.org/LiveSplit/livesplit-core/jobs/444812213#L605
It works just fine with the asmjs-unknown-emscripten target.

**Comment by nstoddard** [comment]
I've seen this too, but only when `panic = 'abort'` is enabled. Is that enabled for your project?

**Comment by CryZe** [comment]
Yeah I have it set to abort.
