### ISSUE TITLE
Using alloc crate with 2018 edition & no_std requires self prefix

### ISSUE THREAD

**Issue by topecongiro** [rust-lang/rust#55284]
The following code does compile with 2015 edition, whereas with 2018 edition it fails.

```rust
#![no_std]
#![feature(alloc)]

extern crate alloc;

use alloc::alloc::Layout;

fn allocate(size: usize) -> *mut u8 {
    unsafe { alloc::alloc::alloc(Layout::from_size_align(size, 32).unwrap()) }
}
```

- [Playground in 2018](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=150a82a89e210f0effb30247ad987e50)
- [Playground in 2015](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2015&gist=20ee51c55df7206274015d5a8c24aa6c)

However if I add a `self::` prefix to the `use` statement, it compiles in both edition:

```rust
#![no_std]
#![feature(alloc)]

extern crate alloc;

use self::alloc::alloc::Layout;

fn allocate(size: usize) -> *mut u8 {
    unsafe { alloc::alloc::alloc(Layout::from_size_align(size, 32).unwrap()) }
}
```

- [Playground in 2018](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=3094c30526eedcd0fbe4ff616a25571d)

I do not know why I need to add `self::` when using 2018 edition. My apologies if this is an expected behavior. (On a side note, is there a better way to use `alloc::alloc::alloc`? The crate, module and function being the same name is kind of ridiculous 😛 )

**Comment by petrochenkov** [comment]
>I do not know why I need to add `self::` when using 2018 edition.

Because on 2018 edition imports starting with non-keywords always refer to extern crates passed with `--extern` (or built-in `std`/`core`).

This is going to be addressed by https://github.com/rust-lang/rust/pull/54658.

**Comment by steveklabnik** [comment]
Closing, since this isn't a bug / addressed by that issue. Thanks @topecongiro !

**Comment by topecongiro** [comment]
@petrochenkov I see. Thanks!
