### ISSUE TITLE
Cargo: Allow local packages to satisfy dependencies

### ISSUE THREAD

**Issue by mcandre** [rust-lang/rust#55299]
For rapid prototyping, it would be more convenient for cargo to be able to work with locally-installed Cargo packages, rather than requiring changes to be published to crates.io, and rather than inserting `path = `... configurations in `Cargo.toml`. Please let Cargo see locally installed packages when building projects!

**Comment by memoryruins** [comment]
Cargo’s issue tracker can be found [here](https://github.com/rust-lang/cargo/issues). One of Cargo’s [source replacement](https://doc.rust-lang.org/cargo/reference/source-replacement.html) options might fit your needs.
