### ISSUE TITLE
Obtain the index of a function in a trait's vtable

### ISSUE THREAD

**Issue by moonheart08** [rust-lang/rust#55294]
This would be useful for constructing artificial vtables for some trait (Still very dangerous, and is the use case i'm interested in most), or for otherwise working on interop between external code and rust. If it's possible to get this data via procedural macros, that works too (for my purposes, anyways), but allowing this data to be optionally bundled into the resulting program for interop purposes would be great.

**Comment by Ekleog** [comment]
As far as I understand, currently trait vtables are not guaranteed to be stable, and not even guaranteed to exist (if the same behaviour can be done through other means). If you want to expose such a function, I'd think you'd have more luck at [the RFC repo](https://github.com/rust-lang/rfcs/), but you'll likely need to come up with a practical detailed example where it is required enough to make the loss in future potential optimizations worth it :)

**Comment by Enselic** [comment]
Triage: I agree this will need an RFC, so let's close this issue.
