### ISSUE TITLE
Tracking issue for slice_partition_at_index

### ISSUE THREAD

**Issue by Mokosha** [rust-lang/rust#55300]
This is the tracking bug for the discussion outlined in rust-lang/rfcs#1470.

I'm working on implementing this in the `libstd`, and will add it as an unstable feature pending resolution of any comments that may arise in this thread. I plan to add comprehensive testing as well.

**Comment by scottmcm** [comment]
A thought: since we have `sort` and `sort_unstable`, should the method that got implemented be `partition_unstable` instead?  It would be reasonable to have a stable version as well -- for example, it's what's needed for Sean Parent's example at https://youtu.be/W2tWOdzgXHA?t=796

**Comment by umanwizard** [comment]
Hi @Mokosha , is this expected to be stabilized eventually?

**Comment by Mokosha** [comment]
@umanwizard I have no idea what the standardization process is for features, so I don't really know how to answer that. Happy to support whatever needs to be done for that though!

**Comment by SimonSapin** [comment]
APIs currently pointing here below. These seem very niche to me. @rust-lang/libs any thoughts?

```rust
impl<T> [T] {
    pub fn partition_at_index(&mut self, index: usize) -> (&mut [T], &mut T, &mut [T])
        where T: Ord
    {…}
    pub fn partition_at_index_by<F>(&mut self, index: usize, mut compare: F)
                                    -> (&mut [T], &mut T, &mut [T])
        where F: FnMut(&T, &T) -> Ordering
    {…}
    pub fn partition_at_index_by_key<K, F>(&mut self, index: usize, mut f: F)
                                           -> (&mut [T], &mut T, &mut [T])
        where F: FnMut(&T) -> K, K: Ord
    {…}
}
```

**Comment by alexcrichton** [comment]
The naming here threw me for a spin and once I got around to reading the documentation this does seems something standard-library-ish but I agree it's pretty niche. On naming `at_index` I think can be replaced with just `at` (e.g. `split_at`, not `split_at_index`). I find the name "partitioning" confusing when it's actually doing a sort and returning the `index`'th element. The documentation also indicates that it's unstable, but we currently have a convention of "stable unless otherwise specified", so the term `*_unstable_*` may want to be somewhere in the name.

**Comment by Ixrec** [comment]
I think "doing a sort and ..." is at best a very misleading description. Every element is guaranteed to end up on the correct side of the `index`th element, but no (non-trivial) subsequence of the slice is guaranteed to end up in sorted order, much less the whole slice. So even something like "partial sort" would be extremely misleading.

Do you know of any other term for this? I've only ever heard this operation referred to as `partition` in C++ (they even have a `stable_partition`), and also as `partition` in pretty much every pseudocode description of quicksort. The only alternatives that come to mind are synonyms like "segregate" which don't seem any better.

(but I agree with s/`at_index`/`at`, and adding an `unstable`)

**Comment by scottmcm** [comment]
This isn't C++'s `partition`, but rather `nth_element` (<https://en.cppreference.com/w/cpp/algorithm/nth_element>), right?

If so I think it's an excellent thing to have in the library, especially since the complicated parts of the implementation are things that `sort_unstable` already needs, to the maintenance cost is low.

(Interestingly, not that this method is actually an answer to [an exercise in the book](https://doc.rust-lang.org/book/ch08-03-hash-maps.html?highlight=median#summary).)

**Comment by Mokosha** [comment]
Yes, this is closer to C++'s [`nth_element`](https://github.com/rust-lang/rust/pull/55448#issue-226379411).

With regards to the naming -- there were some alternatives to `partition` proposed in [the RFC](https://github.com/rust-lang/rfcs/issues/1470), but `partition` seemed to be more akin to what others expected such a function to be called. I'd caution against using simply `at` instead of `at_index` because by having users provide their own comparators, we would need to change `at_index_by` to be `at_by`, which could be confusing. I otherwise agree that dropping the `_index` and adding `_unstable_` would be generally good.

With the attention of @rust-lang/libs, though, provided the procedure outlined [here](https://internals.rust-lang.org/t/stabilizing-apis-in-the-standard-library/5906) is still followed, what else needs to be done for stabilization?

**Comment by glandium** [comment]
FWIW, this was confusing to me at quick glance because in python `partition` does, on the surface, the same thing as `partition_at_index`... without the sorting part.

**Comment by Digital-Monk** [comment]
I'm fine with `partition_at_index`, and prefer to keep the `_index` in there, because otherwise I would tend to think it was partitioning at (by?) a value and returning the index...  Sorry, that may be mental corruption caused by my students when I was teaching ComSci, but I've found that being explicit about index-vs-value is useful, especially as you get more powerful libraries.

(Sorry if I necro'ed this and everything is already decided.  Just my 2 cents...)

**Comment by jesperdj** [comment]
These algorithms (what C++ `std::nth_element` does and what these `partition_by_...` functions do) are [selection algorithms](https://en.wikipedia.org/wiki/Selection_algorithm) and they are related to partitioning and sorting algorithms such as [quicksort](https://en.wikipedia.org/wiki/Selection_algorithm).

**Comment by jagill** [comment]
I'd like to "push for stabilization", as per the [stabilization guide](https://rustc-dev-guide.rust-lang.org/stabilization_guide.html).  These functions are very useful for building various types of spatial indices (RTrees, KDTrees, etc), for which you need to repeatedly partition, but not sort.  From reading the comments, it seems only the name is still under discussion.  Is that true?  If so how do we drive that to completion?  Are there other concerns?

If there aren't, then I can start the Documentation PR and writing a stabilization report (probably with some oversight and feedback!).

**Comment by Amanieu** [comment]
The main issue that that for consistency with `sort`/`sort_unstable` we should add `_unstable` to the function names since this is an unstable partitioning algorithm. The one downside is that the function names then start to get a bit long (`partition_unstable_at_index_by_key`).

**Comment by Mokosha** [comment]
Adding `_unstable` seems to be what's left. What do people think about dropping the `at` as well as `index` from the name to keep it concise (just `partition_unstable`/`partition_unstable_by_key`)? The main arguments against it would be the ambiguity brought up by @Digital-Monk and things like inconsistency between what's out there (Python, C++, etc).

If the only thing left is `_unstable` then that's fairly straightforward.

**Comment by Amanieu** [comment]
`partition` would refer to a different operation than what this function currently does.

Currently `partition_at_index` is equivalent to C++'s `nth_element`, not `partition`.
- https://en.cppreference.com/w/cpp/algorithm/partition
- https://en.cppreference.com/w/cpp/algorithm/nth_element

**Comment by adamreichold** [comment]
> Currently partition_at_index is equivalent to C++'s nth_element, not partition.

I somewhat agree, yet I never found C++'s choice of name to very memorable. Since other people already mentioned that the context is selection algorithms and that the "index" is actually identifying the desired order statistic, how about `select_{k,n}th_unstable(_by(_key))`?

**Comment by Amanieu** [comment]
I'm happy with `select_nth_unstable` (there is a precedent for `nth` in iterator methods).

**Comment by jagill** [comment]
I'm happy with any of the suggested names.  One argument in support of `select_nth_unstable` is that it is functioning the same as `quick_select`, which is a relatively well-known algorithm, so the name has that precedent as well.

**Comment by Mokosha** [comment]
All aboard the `select_nth` train!

**Comment by Amanieu** [comment]
OK let's stabilize with a rename to `select_nth_unstable`.

@rfcbot fcp merge

**Comment by jesperdj** [comment]
> `partition` would refer to a different operation than what this function currently does.
> 
> Currently `partition_at_index` is equivalent to C++'s `nth_element`, not `partition`.
> 
> * https://en.cppreference.com/w/cpp/algorithm/partition
> * https://en.cppreference.com/w/cpp/algorithm/nth_element

Ok, but...: the name used in C++, `nth_element`, is not great. This function does more than select the nth element - it also rearranges the elements in the collection so that all elements that are "less than" the nth element are to the left, and all elements that are "greater than" the nth element are to the right of it. In other words: C++ `nth_element` does in fact partition the collection (just not in the way that `partition` does).

So I don't like the name `select_nth` because that also doesn't fully explain what the function does.

**Comment by jagill** [comment]
> So I don't like the name `select_nth` because that also doesn't fully explain what the function does.
Are you in favor of the `partition_at_*` names?  If so, with or without `_unstable`?  Or do you have another suggestion?

I think the unfortunate reality is that there is no good name for this particular function -- each candidate has its flaws.  Over the last 2 years no one has found a name that is universally liked, so we may have to go with the least objectionable choice.

**Comment by adamreichold** [comment]
> So I don't like the name select_nth because that also doesn't fully explain what the function does.

I agree with this observation, but as @jagill pointed out, no name that would fulfill this criterion has been proposed so far.

`select_nth_unstable` does not try to, but rather tries to invoke "selection algorithm" as the relevant context to better understand how this algorithm fits into the larger landscape of sorting and order statistics.

**Comment by JulianKnodt** [comment]
What about something like `bisect_at_*` or `bisect_nth_*`? Altho I worry that bisect is not used commonly enough for it to be immediately clear. I personally am fine with any name, but bisect seems to fit what is missing.

**Comment by KodrAus** [comment]
I'm on board with `select_nth_unstable`, given we haven't found any names that don't come with their own downsides, and the downside for `select_nth_unstable` is that it's "as bad" as the equivalent used in C++. That seems like a fair tie-breaker to me.

**Comment by umanwizard** [comment]
Was something with `top` in the name considered? E.g. `select_top_n_unstable`.

Similar functions (not exactly the same, but close enough) are named `topk` and `top_k` in PyTorch and TensorFlow respectively.

**Comment by Amanieu** [comment]
I don't think we can do much better than `select_nth_unstable` so let's just stick with that.

**Comment by jagill** [comment]
@Amanieu I'm happy to make the PR changing the name and stabilizing the issue, but I have a question:  If we change the name, this will be breaking for anyone who's been using the current name.  It this acceptable, or is there an aliasing step that will preserve behavior for those using the feature flag?

**Comment by scottmcm** [comment]
@jagill It's nightly so it's allowed, but to make it a bit easier on nightly users it's generally preferable to to stabilize it under a different feature gate name so the old method can be left there for a month or two before being removing.

**Comment by est31** [comment]
I've opened #93480 to remove the deprecated and unstable `partition_at_index_*` functions that were added to ease the transition to the stable feature.
