### ISSUE TITLE
NLL: review uses of `revisions: migrate nll` that are already covered by compare-mode

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#55312]
This is just a work item I want to file. We can clean up our test suite slightly by removing occurrences of revisions that are made redundant by `compare-mode`.

(Note that there are *some* cases where we deliberately opt out of compare-mode and then use the revisions system to emulate it. Those can stay, though it would be good to review them too.)

**Comment by matthewjasper** [comment]
Updated this to reflect the change to migrate mode everywhere.

This is waiting for #60171 to land first.

**Comment by marmeladema** [comment]
I would be happy to help if someone could write some notes about what needs to be done 🙏

**Comment by jackh726** [comment]
I'm going to go ahead and close this. As mentioned on [zulip](https://rust-lang.zulipchat.com/#narrow/stream/122657-t-compiler.2Fwg-nll/topic/nll.20diagnostics.20issues/near/277465747), I think it makes sense to actually do the opposite here: explicitly move tests with different NLL output to use revisions. This allows us to incrementally review test output differences and add error annotations to the test files. This lowers to burden of review of the final stabilization PR (which should just remove the revision, non-NLL error annotations, and a bless).

compare-mode=nll is good to ensure we don't *miss* test differences though
