### ISSUE TITLE
crossbeam_epoch::pin perf regression

### ISSUE THREAD

**Issue by Eh2406** [rust-lang/rust#55317]
According to the work done on lolbench there was a perf regression on 
[crossbeam_epoch_0_4_0::pin::single_pin](https://lolbench.rs/benchmarks/crossbeam-epoch-0-4-0-pin-single-pin.html) and [crossbeam_epoch_0_4_0::pin::multi_pin](https://lolbench.rs/benchmarks/crossbeam-epoch-0-4-0-pin-multi-pin.html) between nightly 10-11 and 10-12
cc @anp

**Comment by nikic** [comment]
Commit range: https://github.com/rust-lang/rust/compare/5af0bb830...77af31408

Not seeing anything obvious in there. #54592 looks the most relevant, but I don't really see how that one would *hurt* performance.

**Comment by Enselic** [comment]
Triage: To make progress here we'll need some form of MCVE. Labeling appropriately.

**Comment by jackh726** [comment]
Closing since there's actually no usable info on how the perf regression shows.
