### ISSUE TITLE
NLL: ui/E0501.rs refers to "first borrow" but not "second borrow"

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#55314]
This diagnostic output

https://github.com/rust-lang/rust/blob/f99911a4a0bead7dd1f9ef2f90442844434cc391/src/test/ui/E0501.ast.nll.stderr#L1-L13

is not a *regression*, per se. But we put in effort to identify something as the "first borrow" (rather than "previous borrow"); that means we should similarly identify the other borrow as the "second borrow".

**Comment by pnkfelix** [comment]
triage: P-medium

**Comment by wildarch** [comment]
I'll have a go at this :smile:
