### ISSUE TITLE
Arc and Weak should be #[repr(transparent)]

### ISSUE THREAD

**Issue by SoniEx2** [rust-lang/rust#55311]
I make these assumptions: https://docs.rs/eventbus/0.2.0/src/eventbus/lib.rs.html#155

And I won't stop making them, even if I technically can't rely on them. There's absolutely no reason why you can't compare an Arc and a Weak without upgrading.

**Comment by NeoLegends** [comment]
(ignoring the highly offensive comment in your code that suggests you don't even want help)

Why is temporarily upgrading for the comparison a problem? Did you run into measurable performance issues?

**Comment by jonas-schievink** [comment]
Yeah, this could be much more easily solved by adding `Weak::as_ptr`, and possibly `Arc/Rc::as_ptr` (which you don't *really* need since those `Deref` already). Alternatively, adding all 3 missing combinations of `Arc/Rc::ptr_eq` would work too.

**Comment by SoniEx2** [comment]
If you have an &Arc and an &Weak, e.g. because the Arc is the owned variant and the Weak is in a larger datastructure like a HashMap or a Vec, you can avoid atomic operations if you can just compare the Arc and the Weak directly. I'm not sure when it's desired to avoid atomic operations but ppl tell me it's a good idea to avoid atomic operations whenever possible. (they also say that, when possible, Relaxed is better than Aquire/Release is better than SeqCst)

Newer versions of eventbus don't compare Arcs and Weaks. This may change in the future, tho.

**Comment by Mark-Simulacrum** [comment]
We provide as_raw/into_raw on Weak and Arc (Rc as well, I believe) through https://github.com/rust-lang/rust/issues/60728.
