### ISSUE TITLE
NLL migrate mode: issues two errors for single move out of borrow

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#55310]
This code ([play](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=563c4d90b71073cafd9036bb16043116)):

```rust
struct S;
pub fn main() {
    let x = S;
    let _y = *&x;
}
```

issues the following diagnostics under migrate mode:

```
error[E0507]: cannot move out of borrowed content
 --> src/main.rs:4:14
  |
4 |     let _y = *&x;
  |              ^^^
  |              |
  |              cannot move out of borrowed content
  |              help: consider removing the `*`: `&x`

error[E0507]: cannot move out of data in a `&` reference
 --> src/main.rs:4:14
  |
4 |     let _y = *&x;
  |              ^^^
  |              |
  |              cannot move out of data in a `&` reference
  |              cannot move

error: aborting due to 2 previous errors
```

It issues only a single error under either of AST-borrowck or pure NLL.

**Comment by pnkfelix** [comment]
(This is obviously one particular instance of #53004)

**Comment by pnkfelix** [comment]
I think this test:

https://github.com/rust-lang/rust/blob/f99911a4a0bead7dd1f9ef2f90442844434cc391/src/test/ui/by-move-pattern-binding.nll.stderr#L1-L28

is another instance of this. (But when/if we resolve this, one should double check that claim.)

**Comment by pnkfelix** [comment]
This is probably fixed by PR #55221

**Comment by jonas-schievink** [comment]
On current stable and nightly, the code only outputs one diagnostic now (migrate mode is on by default, right?).

**Comment by matthewjasper** [comment]
Yes, this is fixed.
