### ISSUE TITLE
Add `.count_starts_with` and `.count_ends_with` to String 

### ISSUE THREAD

**Issue by anyputer** [rust-lang/rust#55326]
Or like `.count_prefix` and `.count_suffix` which would be shorter.

`.count_starts_with` would count the amount of times a String or str starts with something

Example:
```rust
let count1 = "haha you're funny".count_starts_with("ha");
let count2 = "hello!!!".count_ends_with("!");

assert_eq!(2, count1);
assert_eq!(3, count2);
```

**Comment by scottmcm** [comment]
I feel that things like this probably shouldn't be added until the pattern API stabilizes (cc https://github.com/rust-lang/rust/issues/27721 & https://github.com/rust-lang/rfcs/pull/2500).  It's possible this could be better as `.prefixes("ha").count()`, using iterators.

**Comment by Enselic** [comment]
Triage: Thank you for the proposal.

[This](https://github.com/rust-lang/rfcs/blob/master/libs_changes.md) page says

> For instance new APIs almost certainly merit an RFC. Especially as std has become more conservative in favour of the much more agile cargoverse.

So I'll close this issue. Adding this kind of API needs to go through an RFC.

**Comment by Nilstrieb** [comment]
Not an RFC, see https://std-dev-guide.rust-lang.org/development/feature-lifecycle.html for the process.
