### ISSUE TITLE
Rust 2018 fails to compile code with outlives relation removed

### ISSUE THREAD

**Issue by Osspial** [rust-lang/rust#55334]
When building my code after running `cargo fix --edition-idioms`, the compiler throws a bunch of lifetime errors. This seems to be because rustfix removed some outlives requirements, which breaks the impls that depend on those impls.

This uses nightly features so neither version will compile on the beta branch. I've tested it against the latest nightly.

Outlives requirements were removed from these lines:
https://github.com/Osspial/derin/blob/00d3c5593bb363b9fefb8c7252599f22bcdad84e/derin_core/src/widget_stack/mod.rs#L35
https://github.com/Osspial/derin/blob/00d3c5593bb363b9fefb8c7252599f22bcdad84e/derin_core/src/offset_widget.rs#L33

And replaced as follows:
https://github.com/Osspial/derin/blob/c87b95e40b2004fa121c8dfe81c4c952497eb87f/derin_core/src/widget_stack/mod.rs#L35
https://github.com/Osspial/derin/blob/c87b95e40b2004fa121c8dfe81c4c952497eb87f/derin_core/src/offset_widget.rs#L33

Base commit: https://github.com/Osspial/derin/tree/00d3c5593bb363b9fefb8c7252599f22bcdad84e
Fixes applied: https://github.com/Osspial/derin/tree/c87b95e40b2004fa121c8dfe81c4c952497eb87f

Error messages: https://pastebin.com/raw/3dCs533J

This is either a bug in the compiler or in rustfix, but I'm reporting it here first since it seems more likely to be a compiler error.

**Comment by jonas-schievink** [comment]
If rustfix removed a constraint that's actually required, this is a bug in rustfix, not the compiler.

Diff of rustfix application: https://github.com/Osspial/derin/compare/00d3c5593bb363b9fefb8c7252599f22bcdad84e...c87b95e40b2004fa121c8dfe81c4c952497eb87f

**Comment by Dylan-DPC** [comment]
Closing this as it's a rustfix issue
