### ISSUE TITLE
Feature `tool_lints` is not stabilized until 1.31

### ISSUE THREAD

**Issue by jtgeibel** [rust-lang/rust#55331]
The release notes currently state (last item under [Misc](https://github.com/rust-lang/rust/blob/master/RELEASES.md#misc)) that the tool_lints feature is stabilized.  It links to #53459 where some warnings were added directing users to the new syntax, but the feature wasn't actually stabilized until #54870 and is currently only available on nightly.  I tested locally with both beta and the pre-release builds of 1.30.0.

**Comment by petrochenkov** [comment]
@jtgeibel 
The release notes talk about tool attributes (`#[rustfmt::skip]`) rather than tool lints (`#[allow(clippy::something)]`).
Tool attributes were indeed stabilized on 1.30.
(Closing as not-an-issue.)
