### ISSUE TITLE
rustdoc: lint if a private item has doctests

### ISSUE THREAD

**Issue by QuietMisdreavus** [rust-lang/rust#55333]
Based on the reaction to https://github.com/rust-lang/rust/pull/54438 it looks like we shouldn't stop running these tests, but i still feel like they're not useful to have, because you can't use private items in doctests anyway. Could we make a lint to check for these, even if it's allow-by-default?

cc @rust-lang/rustdoc

**Comment by GuillaumeGomez** [comment]
Good idea!

**Comment by seanmonstar** [comment]
Maybe I'm crazy, but I use this to easily get compile-fail tests: https://github.com/seanmonstar/warp/blob/master/src/filter/mod.rs#L65

**Comment by GuillaumeGomez** [comment]
The point is to lint about private doc tests, not making them fail. :)
