### ISSUE TITLE
Dangling raw pointers in constants will ICE in codegen

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#55353]
cc @RalfJung 

```rust
#![feature(const_let)]

const FOO: *const u32 = {
    let x = 42;
    &x
};

fn main() {
    let x = FOO;
}
```

([Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2015&gist=5b6003a004b94a45e1884c402fff107e))

Errors:

```
   Compiling playground v0.0.1 (/playground)
warning: unused variable: `x`
  --> src/main.rs:10:9
   |
10 |     let x = FOO;
   |         ^ help: consider using `_x` instead
   |
   = note: #[warn(unused_variables)] on by default

error: internal compiler error: librustc_mir/monomorphize/collector.rs:1174: alloc id without corresponding allocation: 3

thread 'main' panicked at 'Box<Any>', librustc_errors/lib.rs:600:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: aborting due to previous error


note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.31.0-nightly (f99911a4a 2018-10-23) running on x86_64-unknown-linux-gnu

note: compiler flags: -C codegen-units=1 -C debuginfo=2 --crate-type bin

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `playground`.

To learn more, run the command again with --verbose.

```

**Comment by oli-obk** [comment]
Fix instructions:

The `if` in https://github.com/rust-lang/rust/blob/8ec22e7ec7ed0da2add0763d239e77c5474f3d4a/src/librustc_mir/interpret/validity.rs#L211 doesn't handle raw pointers at all, because the assumption is that we can't know anything about raw pointers.

In fact we can know one thing, and that is whether the raw pointer is dangling.

So, expand the condition to handle the `ty.is_unsafe_ptr()` case and call `self.memory.get(place.ptr)`. If that results in an `Ok`, then we're good, but if you get an `Err`, it can essentially only mean that we got a dangling pointer. So you can call `validation_failure!` with an appropriate error.

Remember to also add a test in `src/test/ui/consts` to make sure that this doesn't ICE the compiler anymore.

**Comment by RalfJung** [comment]
Why do you want to validate raw pointers not to dangle? That seems wrong, they are allowed to.

**Comment by RalfJung** [comment]
I thought you had https://github.com/rust-lang/rust/pull/55262 which would bail out during interning when it sees a dangling relocation. That didn't land yet, so I am not surprised we have this ICE.
