### ISSUE TITLE
In std docs, <code></code> spans are unreadable in one case

### ISSUE THREAD

**Issue by yarrow** [rust-lang/rust#55372]
This is about the documentation for `std`; apologies if this is the wrong place to file.

In one very specific case, &lt;code&gt;&lt;/code&gt; blocks have a dark grey background in the light theme as well as the dark theme, making them almost impossible to read.

I see this

* only for Firefox — not for Chrome or Safari; and
* only for https://doc.rust-lang.org/std/ (which https://doc.rust-lang.org/ links to) — not for https://doc.rust-lang.org/stable/std/ or the offline documentation or https://doc.rust-lang.org/beta/std/ or https://doc.rust-lang.org/nightly/std/ 

## Meta
Firefox 63.0 (64-bit) on MacOs Sierra 10.12.6

**Comment by GuillaumeGomez** [comment]
Do you have a screenshot please? Also on a precise page would be useful. It's very likely a CSS issue.

**Comment by yarrow** [comment]
I no longer see this!  Glitch on my end?   My apologies.
