### ISSUE TITLE
Should there be a warning at compile time when implementing Drop trait with creation of same type inside?

### ISSUE THREAD

**Issue by tom7980** [rust-lang/rust#55388]
I'm fairly new to Rust and have been working through the reference book recently, I've just covered the Drop trait implementation and thought it would be fun to see what happens if I create a new instance of the type I just dropped inside of the function. 

Obviously this is completely nonsensical as nobody is going to do this but as you can probably tell this caused my stack to overflow and crash the program, would an error message at compile time be appropriate for something like this? 

I can't see why anyone would want to initialise new variables inside of the drop trait but it's possible.

Example code of my implementation:
```
struct CustomSmartPointer {
    data: String,
}

impl CustomSmartPointer{
    fn new(s: String) -> CustomSmartPointer {
        CustomSmartPointer{
            data: s,
        }
    }
}

impl Drop for CustomSmartPointer {
    fn drop(&mut self){
        println!("Dropping & creating new pointer");
        let c = CustomSmartPointer::new(String::from("test"));
        println!("New pointer created in memory");
    }
}

fn main() {
    let c = CustomSmartPointer::new(String::from("test"));
}
```

**Comment by oli-obk** [comment]
cc @wesleywiser 

Do you think your new MIR based unconditional recursion lint could be extended to also know about `Drop` calls?

**Comment by wesleywiser** [comment]
@oli-obk I think that's totally possible. It should just be a matter of handling `TerminatorKind::Drop`

https://github.com/rust-lang/rust/blob/8ec22e7ec7ed0da2add0763d239e77c5474f3d4a/src/librustc/mir/mod.rs#L1032-L1036

and treating it as a call to `Drop::drop()` for the item's type.

**Comment by oli-obk** [comment]
I'm guessing we should handle this in in https://github.com/rust-lang/rust/blob/694cf752988728ba5da85c36c2deaeefeb49c05e/src/librustc_mir/lints.rs#L128 

The type of the dropped item can probably be extracted from the `Place`

**Comment by agnxy** [comment]
Hi @oli-obk , I'd like to work on this to dive deep into rustc.

**Comment by oli-obk** [comment]
Great!

So there's already some advice up above, but I'll repeat what I think are the steps needed:

1. write a test that should be causing this lint to be emitted
1. add a match arm for `TerminatorKind::Drop` to https://github.com/rust-lang/rust/blob/694cf752988728ba5da85c36c2deaeefeb49c05e/src/librustc_mir/lints.rs#L128
2. obtain the drop type by calling `place.ty(tcx, mir).to_ty(tcx)`
3. figure out if that type is already the real type we wanted or whether it's a pointer/reference to the real type. Use `info!` statements for that and pass `RUST_LOG=rustc_mir::lints` to the command line when you invoke the test
4. if it's not the type, adjust it by extracting the correct type (e.g. using `ty.builtin_deref(true)`
5. register a call to `Drop::drop` with the `Self` type set to the type you obtained
    * this is a little bit involved, you first need to get the lang item for the drop trait. Start off by calling https://doc.rust-lang.org/nightly/nightly-rustc/rustc/ty/struct.TyCtxt.html#method.lang_items and have a look at the docs for how to get the drop trait out of that
    * When you have the drop trait, get the `DefId` of its method (No idea how to do that off the top of my head, if you get stuck on this, don't hesitate to ask)
    * With the `DefId` of the `Drop::drop` method and the type to be dropped, you can use `Instance::resolve` to get an `Instance` for the concrete `T::drop` method. The `resolve` method takes a `DefId` and `Substs`, so you'll have to create substs with just the concreate type as an element. Look at some calls to `mk_substs` to see how to do that.

**Comment by tom7980** [comment]
>    * When you have the drop trait, get the `DefId` of its method (No idea how to do that off the top of my head, if you get stuck on this, don't hesitate to ask)

It looks like this method in LanguageItems returns an option with the DefId inside of it, looks like it procedurally generates methods for all the kinds of items.

https://github.com/rust-lang/rust/blob/05812fa8c588473f03e3fa7cf59cd84f4f37c715/src/librustc/middle/lang_items.rs#L91-L94

including the drop_trait method: 

https://doc.rust-lang.org/nightly/nightly-rustc/rustc/middle/lang_items/struct.LanguageItems.html#method.drop_trait

Not sure if this is helpful but I'm quite interested in how it all works so thought I'd do some digging. Look forward to seeing how it's all worked out though.

**Comment by agnxy** [comment]
Hi @oli-obk @tom7980 ,
Thanks for your guidance.
I made a little progress with the following prototype.
```
let drop_type = location.ty(mir, tcx).to_ty(tcx);
// get the drop trait's DefId
let drop_trait = tcx.lang_items().drop_trait().unwrap();
// get DefId of its method
let drop_fn = tcx.associated_items(drop_trait).next().unwrap();
```

But I haven't figured out how to use `mk_substs` to create substs as a parameter of `Instance::resolve`. I tried something like `tcx.mk_substs(std::iter::once(Kind::from(drop_type)))` but got ICE when compiling std. And another question is, after we get an `Instance`, is the next step for `TerminatorKind::Drop` match arm similar with the following code? https://github.com/rust-lang/rust/blob/694cf752988728ba5da85c36c2deaeefeb49c05e/src/librustc_mir/lints.rs#L101 Thanks a lot.

**Comment by agnxy** [comment]
Thanks @tom7980 @oli-obk . I'll continue investigating and studying trait solving in rustc.


> can you elaborate on the ICE? I'm guessing it's due to your unwrap calls?

Removing `unwrap` calls doesn't fix this. It seems that the compiler fails to resolve an obligation at `codegen_fulfill_obligation`. I have attached the [backtrace](https://github.com/rust-lang/rust/files/2591581/bt.log) and [debug log](https://github.com/rust-lang/rust/files/2591580/debug.log). And here is the sample [code](https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=bf4ea39f66749ba86765c699e19ed691).

**Comment by oli-obk** [comment]
This failure is happening because we are in a generic context.

There are three ways to continue

1. make `codegen_fulfill_obligation` return an `Option` in case the arguments are too generic to resolve
2. call  `needs_subst()` on the `drop_type`, if the result is `true`, then we don't proceed to use `Instance::resolve` and just use the fallback
3. always use the fallback and don't try to resolve `Drop`, not sure if that will actually work in practice, but it's worth a try.

**Comment by tom7980** [comment]
So I've been looking at this in my spare time and tried implementing it with `needs_subst()` on the drop type, but I'm also getting the same issue with being in a generic context and the compiler not being able to resolve an instance of the drop method on the type. I'm looking at how I would make `codegen_fulfill_obligation` return an `Option` currently but need to work on that further.

My real question is however, once we have the `T::drop` method `defId` & `substs` what is the best way to check that we are initializing the same type inside of the method and produce an error?

**Comment by Enselic** [comment]
I managed to make some progress on this. With #113902 recursive drop is detected in simple cases. Right now the problem is false positives, which I think are caused by MIR analysis being done before drop elaboration. I think we can fix it by moving analysis to after drop elaboration. Just a theory though.
