### ISSUE TITLE
Can't find E0704 error code info

### ISSUE THREAD

**Issue by Undin** [rust-lang/rust#55398]
**Environment**: rustc 1.31.0-nightly (4bd4e4130 2018-10-25) and rustc 1.30.0 (da5f414c2 2018-10-24)

Rustc produces E0704 error code on the following (syntactically wrong) code:
```rust
mod foo {
    pub(foo) struct Bar {
        x: i32
    }
}
```
```
error[E0704]: incorrect visibility restriction
  --> src/main.rs:35:9
   |
35 |     pub(foo) struct Bar {
   |         ^^^ help: make this visible only to module `foo` with `in`: `in foo`
   |
   = help: some possible visibility restrictions are:
           `pub(crate)`: visible only on the current crate
           `pub(super)`: visible only in the current module's parent
           `pub(in path::to::module)`: visible only on the specified path

error: aborting due to previous error

For more information about this error, try `rustc --explain E0704`.
```
But but neither `rustc --explain E0704` nor `https://doc.rust-lang.org/error-index.html` is aware of this error

**Comment by DevQps** [comment]
@Undin I can pick this up unless you'd want to do it yourself!

@steveklabnik This will be the first the I am writing docs for errors. I guess the general structure looks a bit like this?:

- Short description of the error
- Example of bad syntax
- Example of good syntax

Or should there be something else I can add?

**Comment by Undin** [comment]
@DevQps Unfortunately, at this moment I don't have enough time to fix it myself so I will be glad if you fix it

**Comment by DevQps** [comment]
@Undin I will try my best this week! Hopefully I'll be able to create a PR on Wednesday. I'll tag you once it's done :)
