### ISSUE TITLE
rustc 1.30.0's linker flavor inference is a non-backwards compat change to -Clinker

### ISSUE THREAD

**Issue by jsgf** [rust-lang/rust#55396]
In our environment we end up setting `-Clinker` to a script called `ld.sh`; this script is implemented in terms of `gcc` as `rustc` used to expect. Now it treats it as a direct invocation of `ld`.

This was introduced in #52101.

I think rather than inferring the linker flavor from the name of the executable, rustc should either:
1. invoke the binary with --version to try to work out what its dealing with, and/or
2. have a stable `-Clinker-flavor` option to set it explicitly

There's an unstable -Zlinker-flavor option, which I think should have been stabilized at the same time as flavor inference. Ideally inference should be opt-in with `-Clinker-flavor=infer`, with the default being the old default of `-Clinker-flavor=gcc` (at least for Linux platforms).

**Comment by alexcrichton** [comment]
Oh dear, sorry for the breakage! I think there's probably a few things we can do to help mitigate this:

* For backwards compatibility, inference should only chop off `*.exe` and not other extensions when inferring a flavor. I think we'll still want to infer the flavor by default as it fixed a number of issues and empowered a number of embedded use cases to become stable. I also think we want to avoid running `--version` as running a binary has quite a bit of overhead unfortunately
* Simultaneously I think we should likely stabilize `-C linker-flavor` as mentioned here to allow explicit configuration via the command line.

@jsgf does it work for now for y'all to rename to `gcc.sh`? Do the above steps sound ok to you?

Also, cc @japaric

**Comment by alexcrichton** [comment]
@jsgf ah yeah the heuristic includes looking for` -ld` at the end, and we chop off the file extension to handle `.exe` on Windows. You should be able to work around it locally by renaming to `-gcc.sh`.

**Comment by pnkfelix** [comment]
triage: P-high.

**Comment by pnkfelix** [comment]
assigning to @nagisa to take point on moving forward on how we're going to address this

**Comment by pnkfelix** [comment]
T-compiler triage: this has one work-item PR (#56349) that landed, and then the final step is in PR #56351, which has gotten approval via rfcbot so I think all that remains is to bors r+ PR #56351 ?

**Comment by pnkfelix** [comment]
T-compiler triage. PR #56351 landed, so closing this as fixed.

**Comment by jsgf** [comment]
Thanks everyone!
