### ISSUE TITLE
rustdoc won't show impls with enough trait indirection

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#55409]
```rust
pub trait IsA<T> {}

impl<T> IsA<T> for T {}

pub struct Foo;

pub trait Bar {}
impl<T: IsA<Foo>> Bar for T {}
```

`Foo` implements `Bar`, but this won't show up in rustdoc.

the gstreamer bindings exhibit this: https://sdroege.github.io/rustdoc/gstreamer/gstreamer/struct.DeviceMonitor.html , https://sdroege.github.io/rustdoc/gstreamer/gstreamer/trait.DeviceMonitorExt.html

This may be architecturally hard to do, in that case it may be worth looking into a `doc(proxy=foo)` attribute that lets you ask for an impl to explicitly show up on the page of a certain type. This also is useful in cases like #55408 where your impl is on `Wrapper<Foo>` but you want it to be discoverable from `Foo`

**Comment by Manishearth** [comment]
cc @QuietMisdreavus @GuillaumeGomez

**Comment by ollie27** [comment]
Since 1.30 rustdoc displays blanket impls on applicable types:

![image](https://user-images.githubusercontent.com/7189418/47606499-26c97600-da0c-11e8-933c-8514bb1f29e8.png)

**Comment by Manishearth** [comment]
Huh, looks like rustdoc didn't rebuild locally
