### ISSUE TITLE
Show implementations on typedefs on their page (or show a way to request such impls)

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#55408]
For example, [this type](https://sdroege.github.io/rustdoc/gstreamer/gstreamer/buffer/type.Buffer.html) doesn't list its impls, they can be found [here](https://sdroege.github.io/rustdoc/gstreamer/gstreamer/buffer/type.Buffer.html) which is kind of counterintuitive.

Ideally, if you have `type Foo = Bar<Baz>;`, it should show `impl Bar<Baz> {}` blocks (and perhaps `impl Bar` too?)

cc @QuietMisdreavus @GuillaumeGomez

**Comment by Manishearth** [comment]
Additionally, for "wrapper" types you should be able to find impls on their specializations on the inner type page, really: `impl Foo for Rc<Baz>` should show up on `Baz`'s page, or should have a mechanism for being requested to show up on `Baz`'s page (there's an alternate proposal to solve this in #55409)

**Comment by ollie27** [comment]
This looks like a duplicate of #32077.

> Additionally, for "wrapper" types you should be able to find impls on their specializations on the inner type page, really: `impl Foo for Rc<Baz>` should show up on `Baz`'s page

I think that's already the case, `impl<'a> From<&'a OsStr> for Rc<OsStr>` shows on the page for [`OsStr`](https://doc.rust-lang.org/nightly/std/ffi/struct.OsStr.html#impl-From%3C%26%27a%20OsStr%3E-2).

**Comment by Manishearth** [comment]
Doesn't work on this simple testcase:

``
pub struct Rc<T>(T);

pub struct Foo;


impl Rc<Foo> {
    pub fn bar() {}
}
```

**Comment by QuietMisdreavus** [comment]
Right now, if you have `pub type Asdf = Foo<Bar>`, rustdoc will show any impls directly on `Asdf`. (That was https://github.com/rust-lang/rust/pull/42027.) Attempting to go farther and display impls on `Foo<Bar>` would require rustdoc to query the definition on the type alias, including its type and lifetime parameters and their bounds, then be able to check against impls on the "real" type (potentially recursively, if a type alias is given in terms of another alias!).

It looks like https://github.com/rust-lang/rust/issues/32077 has become "document all available impls on type aliases based on their definition", and this sounds like the same.

@Manishearth Also, your code sample is incomplete; i don't see how that is related to type aliases.

**Comment by Manishearth** [comment]
@QuietMisdreavus it's related to my followup comment about wrapper types

**Comment by QuietMisdreavus** [comment]
If the wrapper type implements Deref/DerefMut, then the applicable methods will appear on the wrapper's page. if you're asking for `bar()` to appear on `Foo`'s page, then we have to be able to be able to mark such types as "transparent" somehow so rustdoc knows to add those methods in. (Do we change how we handle Deref so that methods directly on Deref-able wrappers appear on their Targets?)

In any case, that would make this thread about two problems; one about type aliases and the other about Deref. Please file a second issue to split these.

**Comment by Manishearth** [comment]
https://github.com/rust-lang/rust/issues/55551
