### ISSUE TITLE
Docs for `for` keyword should mention `for<'a>`

### ISSUE THREAD

**Issue by SoniEx2** [rust-lang/rust#55416]
Docs for `for` keyword should mention `for<'a>` (I guess issue titles still can't have code :/)

**Comment by frewsxcv** [comment]
FYI, there are some existing docs about `for<'a>` in the Reference:

- https://doc.rust-lang.org/nightly/reference/trait-bounds.html#higher-ranked-trait-bounds

**Comment by Centril** [comment]
@SoniEx2 a PR would be welcome.
