### ISSUE TITLE
..fields be allowed to initialize private fields

### ISSUE THREAD

**Issue by stepancheg** [rust-lang/rust#55424]
Code:

```
mod foo {
    #[derive(Default)]
    pub struct Bar {
        pub baz: u32,
        qux: u32,
    }
}

fn main() {
    let b = foo::Bar { baz: 10, ..Default::default() };
}
```

doesn't compile, although this equivalent code works:

```
fn main() {
    let mut b: foo::Bar = Default::default();
    b.baz = 10;
}
```

`..fields` should be allowed when it affects only private fields.

**Comment by oli-obk** [comment]
Closing as this is working as expected according to the RFC. Any suggested changes should be discussed in the internals forum and refined into a new RFC.
