### ISSUE TITLE
Please ship llvm-as in the llvm-tools-preview component

### ISSUE THREAD

**Issue by lu-zero** [rust-lang/rust#55427]
It could be used by crates such as `nasm-rs` to reduce the discrepancies between windows `lib` and no-windows `as`.

See also https://github.com/rust-embedded/cargo-binutils/issues/33

**Comment by mkroening** [comment]
I think this was resolved in https://github.com/rust-lang/rust/pull/78968, right?

**Comment by Dylan-DPC** [comment]
Closing this as it's resolved by #78968
