### ISSUE TITLE
Inneficient code generation, unless splitting part of the code into #[inline(always)] sub-function

### ISSUE THREAD

**Issue by newpavlov** [rust-lang/rust#55458]
(from #43702)

Both examples are completely equivalent after inlining, but the second one gets compiled into a more efficient assembly:
```Rust
pub fn square(mut buf: &mut [u8], self_buf: &[u8; 16*8]) {
  while buf.len() >= self_buf.len() {
      let (l, r) = {buf}.split_at_mut(self_buf.len());
      buf = r;
      for i in 0..16*8 { l[i] ^= self_buf[i]; }
  }
}
```
https://rust.godbolt.org/z/mXrwhv

```Rust
#[inline(always)]
fn xor(l: &mut [u8], self_buf: &[u8; 16*8]) {
  for i in 0..16*8 { l[i] ^= self_buf[i]; }
}

pub fn square(mut buf: &mut [u8], self_buf: &[u8; 16*8]) {
  while buf.len() >= self_buf.len() {
      let (l, r) = {buf}.split_at_mut(self_buf.len());
      buf = r;
      xor(l, self_buf);
  }
}
```
https://rust.godbolt.org/z/Uk3X3Z

**Comment by newpavlov** [comment]
BTW using `zip` breaks auto-vectorization:
```rust
pub fn square(mut buf: &mut [u8], self_buf: &[u8; 128]) {
  while buf.len() >= self_buf.len() {
      let (l, r) = {buf}.split_at_mut(self_buf.len());
      buf = r;
      for (a, b) in l.iter_mut().zip(self_buf.iter()) {
        *a ^= *b;
      }
  }
}
```
https://rust.godbolt.org/z/SLIi9D

**Comment by elichai** [comment]
Any updates on this? breaking auto-vectorization when doing something more idiomatic isn't good :/

**Comment by newpavlov** [comment]
The autovectorization issue is fixed, but the first link still results in a better assembly. For some reason IIUC the compiler inserts a tail processing code in two other cases, even though chunks are guaranteed to be always 128-byte long.

**Comment by newpavlov** [comment]
Nightly compiler now produces the same assembly for all 3 snippets, so I am gonna close this issue as fixed.
