### ISSUE TITLE
Change Request:  cargo rename oldprojectname newprojectname

### ISSUE THREAD

**Issue by omac777** [rust-lang/rust#55481]
I have a project that I create with:
`cargo create oldprojectname`

I intuitively thought I could simply rename the directory to newprojectname and it would build an executable with the very same name.  It did not.

In order for this to happen, to my surprise, I needed to do:
-modify Cargo.lock to rename the executable from oldprojectname  to newprojectname
-modify Cargo.toml to rename the executable from oldprojectname  to newprojectname
-modify src/main.rs to rename the executable from oldprojectname  to newprojectname
-cargo clean
-cargo build

Why? Because the clap crate requires you to name the executable within the main.rs for the help usage.

I know I'm nitpicking here, but I feel that it could be done in a way where you modify the oldprojectname to newprojectname at one location and the change propagates everywhere else automatically via calling rust apis rather than hard-coding the binary name everywhere.

Thank you for listening.

**Comment by ExpHP** [comment]
Note that Cargo has its [own issue tracker](https://github.com/rust-lang/cargo/issues).

A cargo command taking the name of an existing directory does not fit at all into the mental model of cargo for me.  There is no connection between directory name and package name in cargo, except for the fact that `cargo new` defaults to `--name $(basename <path>)`.

> modify Cargo.lock to rename the executable from oldprojectname to newprojectname

This shouldn't be necessary, as Cargo.lock is updated automatically when the crate is built, and references to the old crate name will be pruned.

> Because the clap crate requires you to name the executable within the main.rs for the help usage.

See https://docs.rs/clap/2.32.0/clap/macro.app_from_crate.html.

**Comment by steveklabnik** [comment]
I'm going to close this, as it should be filed against cargo. Thanks!
