### ISSUE TITLE
Cannot find `assert` in $crate::core using [no_std]

### ISSUE THREAD

**Issue by Robbepop** [rust-lang/rust#55482]
```rust
#![no_std]
macro_rules! foo {
    ($e:expr) => {
        $crate::core::assert!($e);
        $crate::core::assert_eq!($e, true);
    };
}
pub fn foo() { foo!(true); }
```

Compiling the above code generates this error message:

```
error[E0433]: failed to resolve. Could not find `assert` in `core`
  --> src/lib.rs:5:23
   |
5  |         $crate::core::assert!($e);
   |                       ^^^^^^ Could not find `assert` in `core`
...
13 |     foo!(true);
   |     ----------- in this macro invocation
```

However, this compiles:

```rust
#![no_std]
macro_rules! foo {
    ($e:expr) => {
        assert!($e); // no more `$crate::core::` path prefix!
        $crate::core::assert_eq!($e, true);
    };
}
pub fn foo() { foo!(true); }
```

Note that for the `assert_eq` invokation both versions `$crate::core::assert_eq!` and just `assert_eq!` works.

Is this intended behaviour or a bug?

Try it yourself at [the playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=c8f38832ae0cd32eba783e59040ec79e).

**Comment by stephaneyfx** [comment]
This may be related to the issue where macros (it seems limited to built-in ones) don't work when called qualified with their path. [Playground]( https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=0944c3d0bcd4255f7051073f81afaf65)

```rust
fn main() {
    // These macros are built into the compiler and calling them qualified
    // with their path does not work:
    //
    // let _ = std::column!();
    // let _ = std::format_args!("blah");
    // let _ = std::concat!("abc", "def");

    // But it works with non built-in macros:
    let _ = std::format!("blah");
    let _ = std::vec![0, 1];
}
```

**Comment by petrochenkov** [comment]
`assert` is not defined in the `core` library, it's a built-in macro defined by the language.
`assert_eq` in its turn is indeed defined in `core`, so it can be used as `core::assert_eq!(...)`.

It should be possible to make a proxy macro `assert` in `core` calling built-in `assert`, it may require some care about what rusdoc shows for that macro though.

**Comment by dtolnay** [comment]
This is a bug. [The documentation of libcore shows assert being provided by core.](https://doc.rust-lang.org/core/index.html#macros) I understand that there is nuance around built-in macros but it's clear to me that `core::assert!` should be accepted.

**Comment by steveklabnik** [comment]
Triage: the docs of libcore should probably be updated.

**Comment by jyn514** [comment]
Is the request for `core::assert!` to be accepted or for rustdoc to stop documenting `core::assert`? If the former, this should be tagged `T-libs` or `T-compiler`, not `T-rustdoc`.

**Comment by jyn514** [comment]
@dtolnay @steveklabnik you've said contradicting things: @dtolnay said `core::assert!` should be accepted as-is and @steveklabnik said the docs shouldn't show `core::assert!` as valid. Which is it? Does it need an RFC?

**Comment by dtolnay** [comment]
`$crate::core::assert!` needs to work. It does not require an RFC. According to OP, `$crate::core::assert_eq!` already works.

**Comment by dtolnay** [comment]
It's possible there was a rustdoc issue *also*. According to https://github.com/rust-lang/rust/issues/55482#issuecomment-453784352, rustdoc was showing `assert!` in core even though it was not exposed by core in a way that was callable.

**Comment by jyn514** [comment]
Heh, after all that it turns out this compiles as-is (maybe assert was moved to core recently?). I'll add a test for it.
