### ISSUE TITLE
Spurious failure in test_inherit_env

### ISSUE THREAD

**Issue by kennytm** [rust-lang/rust#55503]
Symptom: the test `process::tests::test_inherit_env` failed even if the PR doesn't touch this part of the standard library.

```
[01:56:52] test process::tests::test_inherit_env ... FAILED
...
[01:56:52] thread '<unnamed>' panicked at 'output doesn't contain `RUN_TEST_NEW_ENV2=456`
...
```

Previous instances:

* 2018-10-30T10:42:14Z: https://github.com/rust-lang/rust/pull/55496#issuecomment-434251998 (arm-android)
* 2018-09-08T08:22:09Z: https://github.com/rust-lang/rust/pull/53935#issuecomment-419623084 (x86_64-gnu-distcheck)

It is known that this test had a race condition, and the fix #42795 wasn't merged.

**Comment by Enselic** [comment]
This issue can be closed, because the test was removed in https://github.com/rust-lang/rust/commit/d1cd4e8d0d383842acfe2d6ea75eed1e0c0909ac
