### ISSUE TITLE
nll: respect user type annotations with constants in patterns

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#55511]
Breaking off from #47184 -- we need to respect user type annotations in patterns. Here are some examples:

Compiles without NLL ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2015&gist=8a181a6e956584682108e19b61a4077c)):

```rust
trait Foo<'a> {
    const C: &'a u32;
}

impl<'a, T> Foo<'a> for T {
    const C: &'a u32 = &22;
}

fn foo() {
    let a = 22;
    match &a {
        <() as Foo<'static>>::C => { }
        &_ => { }
    }
}

fn main() {
}
```

Errors without NLL ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2015&gist=819e4fbf897e343be51f6847e140c6ce)):

```rust
use std::cell::Cell;

trait Foo<'a> {
    const C: Option<Cell<&'a u32>>;
}

impl<'a, T> Foo<'a> for T {
    const C: Option<Cell<&'a u32>> = None;
}

fn foo() {
    let a = 22;
    let b = Some(Cell::new(&a));
    match b {
        <() as Foo<'static>>::C => { }
        _ => { }
    }
}

fn main() {
}
```

**Comment by pnkfelix** [comment]
triage: Either this is something that we're planning to implement *and* backport to the beta channel... or its something that is not *that* high priority.

Given that this is an NLL-sound issue, I'm going to assume that it is indeed high priority and belongs on the Release milestone.

Thus, tagging as P-high

**Comment by pnkfelix** [comment]
Just a quick note: this one *is* rejected by NLL.

```rust
#![feature(nll)]

use std::cell::Cell;

trait Foo<'a> {
    const C: Option<Cell<&'a u32>>;
}

impl<'a, T> Foo<'a> for T {
    const C: Option<Cell<&'a u32>> = None;
}

fn foo<'a>(r: &'a i32) {
    let b = Some(Cell::new(r));
    match b {
        <() as Foo<'static>>::C => { }
        _ => { }
    }
}

fn main() {
}
```

From looking at the MIR generated for the first example, perhaps the problem stems from this ?

```
        StorageLive(_1);                 // bb0[0]: scope 0 at ../../should-cfail.rs:12:9: 12:10
        _1 = const 22u32;                // bb0[1]: scope 0 at ../../should-cfail.rs:12:13: 12:15
...
        _4 = &'static _1;                // bb0[6]: scope 1 at ../../should-cfail.rs:13:28: 13:30
```

**Comment by pnkfelix** [comment]
triage: assigning to self

**Comment by pnkfelix** [comment]
didn't get a chance to look into this further today. Unassigning self (I'll be back from leave in ~2 weeks, but I want to make sure other people know that this is available to hack on in the meantime).

**Comment by nikomatsakis** [comment]
Removing from milestone — sufficiently obscure that it need not be a release blocker
