### ISSUE TITLE
document constant expressions in rust.md reference manual

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#5551]
The section on "static items" (formerly entitled "constants") refers to some class of "constant expressions", but we have not defined what these are.

(I think catamorphism has noted this via comments in a few issues I have seen, but I have not seen an actual Issue for this topic; so I am promoting it to a full fledged issue.)

In particular, if we need a subgrammar, or some other sort of static analysis to classify the constant expressions correctly, then we should document it.

**Comment by steveklabnik** [comment]
We now do not refer to 'constant expressions' in the reference at all, and the section on statics seems fine to me. Giving this a close.

**Comment by nikomatsakis** [comment]
@steveklabnik I'm not sure I agree with this assessment. I guess it depends on what level of precision we are shooting for.

**Comment by steveklabnik** [comment]
Okay, fill me in :)

**Comment by steveklabnik** [comment]
Triage: have had several conversations about this, never quite been sure exactly what we want to put and where.

**Comment by steveklabnik** [comment]
The reference is now in its own repo, so I have migrated this issue: https://github.com/rust-lang-nursery/reference/issues/18

Side note: wow, a four digit issue ID. An endangered species at this point...
