### ISSUE TITLE
Error 0212 is missing from the error index

### ISSUE THREAD

**Issue by shepmaster** [rust-lang/rust#55523]
I was debugging code like this:

```rust
trait ExtractFrom<'a> {
    type Extracted;
}

fn sort_by_extractor<T>()
where
    T: for<'a> ExtractFrom<'a>,
    T::Extracted: Copy,
{
}
```

And got this error:

```
error[E0212]: cannot extract an associated type from a higher-ranked trait bound in this context
 --> src/lib.rs:8:5
  |
8 |     T::Extracted: Copy,
  |     ^^^^^^^^^^^^
```

However, 0212 is not documented in the error index.

**Comment by zackmdavis** [comment]
(subtask of #32777)

**Comment by shepmaster** [comment]
@zackmdavis should I just close this, as it's probably not adding anything useful?

**Comment by varkor** [comment]
E0212 is on the list, so it's probably better just to use #32777 as the tracking issue for this code.
