### ISSUE TITLE
URL in `use` update lint goes to 404

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#55577]
The URL that we even test for at <https://github.com/rust-lang/rust/blob/master/src/test/ui/rust-2018/local-path-suggestions-2018.stderr> does not work for me: It points to https://doc.rust-lang.org/edition-guide/rust-2018/module-system/path-clarity.html, which is 404 not found.

Cc @davidtwco

**Comment by davidtwco** [comment]
I believe this is currently intended. The edition guide isn't currently available at that URL but that is the URL that it will be hosted at eventually.

cc @steveklabnik @nikomatsakis

**Comment by steveklabnik** [comment]
That's correct.

**Comment by davidtwco** [comment]
Closing as the link no longer 404s.
