### ISSUE TITLE
Tracking issue for feature `extern_crate_item_prelude`

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rust#55599]
With this feature `extern crate foo as bar;` item placed into the crate root puts the name `bar` into extern prelude. This has the next effects:
- The name is in scope in the whole crate, including inner modules, like other prelude names.
- On 2018 edition imports can refer to that name `use bar::zzz;` or `use ::bar::zzz;`, plus non-import absolute paths can refer to it as well `let z = ::bar::zzz;`.

More details are available on the implementation PR - https://github.com/rust-lang/rust/pull/54658.

**Comment by Nemo157** [comment]
Is this intended to be stable for the initial 2018 release? It seems important for a nice experience with proc-macros (otherwise you must use `crate::proc_macro` everywhere except `src/lib.rs`).

If not, this appears to have no forward-compat warning when building under 2015, which causes a failure to migrate with `cargo fix`:

```rust
error[E0658]: use of extern prelude names introduced with `extern crate` items is unstable (see issue #54658)
  --> interp-macros/src/lib.rs:12:5
   |
12 | use proc_macro::TokenStream;
   |     ^^^^^^^^^^
   |
   = help: add #![feature(extern_crate_item_prelude)] to the crate attributes to enable
```

**Comment by SimonSapin** [comment]
>  this appears to have no forward-compat warning 

I’ve also hit this and filed https://github.com/rust-lang/rust/issues/55592

**Comment by steveklabnik** [comment]
Knowing if this will ship in 1.31 or not is important for the book, for the reasons that @Nemo157 mentioned. Could we maybe get an answer here?

**Comment by petrochenkov** [comment]
@aturon and @steveklabnik wanted to stabilize this for the edition release on #edition-planning discord channel.

This should be ready for stabilization and backport to 1.31 beta once https://github.com/rust-lang/rust/pull/55884 lands (or some fixes for *this* feature are extracted from that PR).
I'll prepare a stabilization report.
