### ISSUE TITLE
1.30.1 point release tracking issue

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#55594]
This issue tracks the 1.30.1 point release, which is scheduled to be released on Thursday 8th.

PRs that are going to be included in the point release:

* #54199: overlook overflows in rustdoc trait solving (e783d2be405353b2ea99b77e107beb2970096b90)
* https://github.com/rust-lang/rust/pull/55717 to fix diesel building
* #55325: Fix link to macros chapter
* #55362: Remove `cargo new --edition` from release notes.
* rust-lang/cargo#6122: Second attempt at fixing msys terminal width.

cc @rust-lang/release

**Comment by Eh2406** [comment]
If it is not hard to do, I'd be ok including rust-lang/cargo#6122.

**Comment by ehuss** [comment]
I'm happy to prepare the PRs for the cargo issue, but I don't know how the decision gets made as to whether or not it should be included.

**Comment by pietroalbini** [comment]
@ehuss @Eh2406 the cargo team should decide if the fix is safe to be backported.

**Comment by pietroalbini** [comment]
The rustdoc fix is not fully done: https://github.com/rust-lang/rust/issues/54524 is still a stable-to-stable regression. If we can fix that soon we should hold off making the point release, to avoid doing a second one.

**Comment by alexcrichton** [comment]
@ehuss I think it's definitely safe to backport that to stable, so if you'd like feel free to prepare the stable branch for Cargo!

**Comment by joelgallant** [comment]
Is #55590 going to be included? @pietroalbini

**Comment by pietroalbini** [comment]
Yep.

**Comment by jonas-schievink** [comment]
Should this also include https://github.com/rust-lang/rust/pull/55717 to fix https://github.com/rust-lang/rust/issues/54524?

**Comment by pietroalbini** [comment]
@jonas-schievink yep, that PR has been included.
