### ISSUE TITLE
Implement `Index` for `SliceIndex` types for `str`

### ISSUE THREAD

**Issue by alercah** [rust-lang/rust#55603]
While writing a generic implementation today, I was surprised that you can't do `s[i]` for `i: SliceIndex<S>`, if `s` is of slice type `&S`. Doing `s.get(i).unwrap()` is an easy enough workaround, but feels really bad. Replacing the various explicit impls with one for `SliceIndex` would feel much nicer.

**Comment by eddyb** [comment]
cc @rust-lang/libs

**Comment by sfackler** [comment]
The bounds on `[T]`'s `get` and `Index` impls seem the same?

https://doc.rust-lang.org/std/primitive.slice.html#method.get
https://doc.rust-lang.org/std/primitive.slice.html#impl-Index%3CI%3E

**Comment by SimonSapin** [comment]
Perhaps @alercah meant for `str` rather than slices? https://doc.rust-lang.org/std/primitive.str.html#impl-Index%3CRange%3Cusize%3E%3E

**Comment by alercah** [comment]
Ah, yes, I did. I mistakenly assumed they are in fact the same. :)

**Comment by sfackler** [comment]
Ah yeah, that seems like an oversight!
