### ISSUE TITLE
Tracking issue for feature `extern_in_paths`

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rust#55600]
Allows using `extern` in paths to unambiguously refer to items in extern crates - `extern::my_crate::foo`.

This feature is superseded by absolute paths `::my_crate::foo` on 2018 edition, and has little value on 2015 edition where `extern crate` items are supposed to be used instead.
As a result, the feature is supposed to be removed once 2018 edition ships.

**Comment by Centril** [comment]
@rfcbot close

Per @petrochenkov's notes above I propose that we remove `extern::` once the 2018 edition has shipped.

**Comment by Centril** [comment]
@petrochenkov Now that FCP is complete, could you either 1) write up mentoring instructions, 2) fix it up yourself? :)
