### ISSUE TITLE
Make Semicolons optional

### ISSUE THREAD

**Issue by AnirudhVyas** [rust-lang/rust#55602]
Why does Rust insist on using semi colons - is it needed?

**Comment by nagisa** [comment]
Yes. The grammar becomes ambiguous without them.

A request of this scale would require an RFC which are filled at [the rust-lang/rfcs repository](https://github.com/rust-lang/rfcs). Therefore closing.

**Comment by AnirudhVyas** [comment]
thank you for response. I have filed one - https://github.com/rust-lang/rfcs/issues/2583#issue-376904159
