### ISSUE TITLE
Sort struct methods by alphabetical order

### ISSUE THREAD

**Issue by ghost** [rust-lang/rust#55605]
Sometimes when looking at the documentation for various structures, it can be difficult to view the methods list and find a method that starts with, let's say, an "a." As of now, the `Vec` methods look like this (at the left):
![non-alphabetical](https://user-images.githubusercontent.com/16357077/47892517-c6787100-de1d-11e8-8003-a37b9e22e86c.PNG)
But it might be useful to sort these by alphabetical order for finding methods at-a-glance without having to resort to searching for them using the search bar at the top.

**Comment by Lonami** [comment]
They're generally grouped by functionality, but I agree that when searching for a method, alphabetical order helps a lot.

**Comment by jyn514** [comment]
This has been implemented: 
![Screenshot_20200827-001101_Ecosia](https://user-images.githubusercontent.com/23638587/91383337-e0a4ef80-e7f9-11ea-997f-0505f9193433.jpg)
