### ISSUE TITLE
Result / Option of non-null / non-zero types are not FFI-safe

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/rust#55615]
I am writing an FFI wrapper for a library that has a function returning an integer error code:

```rust
extern "C" fn foo() -> libc::c_int;
```

The error code of `foo` is `0` on success and non-zero on error. As suggested by @kennytm , I can do the following dance to obtain a `NonZeroU{width}` type that's suitable to hold a `c_int` (note: `NonZero<libc::c_int>` does not work anymore, and the `NonZeroI{width}` variants have been removed, so more extra dance is then necessary to convert the unsigned integers to a `libc::c_int` to be able to compare this with with std error codes like `libc::EINVAL`):

```rust
pub trait NonZeroUInt { type NonZero; }
impl NonZeroUInt for i32 { type NonZero = core::num::NonZeroU32; }
impl NonZeroUInt for i64 { type NonZero = core::num::NonZeroU64; }
impl NonZeroUInt for isize { type NonZero = core::num::NonZeroUsize; }

pub type NonZeroCInt = <libc::c_int as NonZeroUInt>::NonZero;
```

However, when I then try to use `Result` in FFI:

```rust
extern "C" fn foo() -> Result<(), NonZeroCInt>;
```

I get an error stating that `Result` is not FFI-safe. This type is really similar to an `Option<&'static 32>` which is FFI-safe: an enum with 2 variants, one is zero sized, and the other has niches. 

`Option<NonNull<*mut i32>>`, `Option<NonZeroU32>`, and `Result<(), NonZeroU32>` are not, however, FFI safe.

Is this an oversight ? 
cc @eddyb @SimonSapin

**Comment by steveklabnik** [comment]
I think this isn't an oversight; `Option` has been special-cased here to be identical in representation to the original type, but non-repr-c enums, like Result, have no layout guarantees whatsoever.

I guess in theory we *could* do this for `Result<(), T>` where T is a NonZero type, but I imagine that's an RFC.

**Comment by eddyb** [comment]
@steveklabnik that's not exactly the case, the shape is what's checked, so if you have your own `Option`-like type, the lint will allow it.
We could also allow variants with ZST fields.

But regardless of `Result`, I think the `Option` examples should all work.
What's missing is recursing through transparent newtypes, or just using layout to tell that the inner type is non-null.

cc @RalfJung @nikomatsakis @rkruppe @nagisa

**Comment by steveklabnik** [comment]
Sure, I was talking about the spec, not the lint. Unless I’m mistaken and the lint is the spec. I thought only Option was truly guaranteed even if we do always do the optimization for any option-like type. I could be wrong!

**Comment by eddyb** [comment]
@steveklabnik Ah, alright, I agree then, we should spec this (via UCG, I guess).
That would inform the lint, but the lint doesn't need to be perfect.

**Comment by RalfJung** [comment]
This kind of stuff was being discussed recently at https://github.com/rust-rfcs/unsafe-code-guidelines/issues/10

**Comment by gnzlbg** [comment]
> That would inform the lint, but the lint doesn't need to be perfect.

So there are two orthogonal issues convoluted in my OP. First, is whether the niche optimizations for these types of enums are guaranteed or not. If they are not guaranteed, then using these in C FFI is pretty much undefined behavior independently of what Rust currently does. That should be clarified in the UCG and the current discussion seems to suggest that these should be guaranteed. What does Rust currently do here? Does this unconditionally perform these optimizations?

Second, is whether the warning raised by the `improper_ctypes` lint is correct or not.  This depends on what the UCG-wg decides, but I wish this lint was actually perfect "according to the spec". Passing types through C FFI is already hard due to many factors, and guaranteed niche optimizations make reasoning about the correctness of C FFI code harder. It would be nice to be able to rely on this lint.

**Comment by newpavlov** [comment]
We have a similar situation in the `wasi` crate. We would like to rely on layouts being exactly the same for these two structs definitions:
```rust
#[repr(C)]
pub struct __wasi_event_t {
    pub userdata: u64,
    pub error: u16,
    pub type_: u8,
    pub u: T,
}

#[repr(C)]
pub struct Event {
    pub userdata: u64,
    pub error: Result<(), NonZeroU16>,
    pub type_: u8,
    pub u: T,
}

const _ASSERT1: [(); 32] = [(); core::mem::size_of::<__wasi_event_t>()];
const _ASSERT2: [(); 32] = [(); core::mem::size_of::<Event>()];
const _ASSERT3: [(); 0] =  [(); __WASI_ESUCCESS as usize];
```
Note the asserts. Since we check at compile time that both structs have exactly the same size, it means that niche optimization is applied, meaning that `Result<(), NonZeroU16>` and `u16` have exactly the same memory representation. So will be casting of `*mut Event` to `*mut __wasi_event_t` correct under such conditions?

**Comment by gnzlbg** [comment]
@eddyb I think this could be a small RFC proposing to guarantee this, and including the couple of motivating examples shown here. We don't have to wait for the UCGs to come up with an RFC. 

I don't know if this might also be FCP material for a PR to the reference. I would be more comfortable with it being a proper RFC.

**Comment by workingjubilee** [comment]
Resolved by RFC 3391
