### ISSUE TITLE
`c_void` has wrong rustc support level in docs

### ISSUE THREAD

**Issue by jethrogb** [rust-lang/rust#55619]
The documentation page for [`core::ffi::c_void`](https://doc.rust-lang.org/core/ffi/enum.c_void.html) says it's available at version 1.1.0, however, it's only available at version 1.30.0.

**Comment by Proximyst** [comment]
While the module `c_void` lays in, `core::ffi`, was stabilised at 1.30.0, the type `c_void` was stabilised at 1.1.0, which again makes the docs correct. The docs for the module [`core::ffi`](https://doc.rust-lang.org/core/ffi/index.html) say 1.30.0.

**Comment by IsaacWoods** [comment]
So I did the original PR to create `core::ffi::c_void`, and probably agree with @jethrogb in hindsight. The `c_void` type was originally available at `std::os::raw::c_void`, [which should stay at `1.1.0`](https://github.com/rust-lang/rust/blob/master/src/libstd/ffi/mod.rs#L174). However, both [`std::ffi::c_void`](https://github.com/rust-lang/rust/blob/master/src/libstd/ffi/mod.rs#L174) and [`core::ffi::c_void`](https://github.com/rust-lang/rust/blob/master/src/libcore/ffi.rs#L27) should probably be changed to `1.30.0`.

**Comment by ExpHP** [comment]
This has happened before as well:

https://github.com/rust-lang/rust/issues/49651
