### ISSUE TITLE
Bad compiler error

### ISSUE THREAD

**Issue by npip99** [rust-lang/rust#55620]
At the end of [this thread](https://github.com/rust-lang/rust-by-example/issues/390), I saw

```
fn main() {
    if let Some(&pat) = Some(&Box::new(1)) {
        println!("{:?}", pat);
    }
}
```

With the error

```
error[E0507]: cannot move out of borrowed content
 --> ref.rs:2:17
  |
2 |     if let Some(&pat) = Some(&Box::new(1)) {
  |                 ^---
  |                 ||
  |                 |hint: to prevent move, use `ref pat` or `ref mut pat`
  |                 cannot move out of borrowed content
```

This error I don't think should've had that hint there. The hint is great when it's well-placed, but this time it doesn't make much sense, since it implies `&pat` should be replaced with `ref pat`. In the poster's case, autoderef handles `println!` even when `ref pat` is used, so perhaps the OP never noticed, but in many other cases this would cause issues. Using `ref pat` would cause `pat` to be of type `&&Box`, which isn't going to be the intent of the programmer.

I think what the compiler means here is that `pat` should be replaced with `ref pat`, which would be `&ref pat`, and yeah that's correct. `&ref pat` can always be simplified to `pat` itself, so basically the compiler should avoid outputting the hint whenever the erroring identifier comes after an `&` (Since that would always lead to a redundant `&ref` construct if the hint is followed).

**Comment by hellow554** [comment]
Sorry, but I don't get you. `Some(ref path)` is correct in this case and should be used, because you have a `&Box`.
Yes you can omit the `ref` and just write `Some(path)` but then you move the value, which is not always possible, but `ref` is.

**Comment by hellow554** [comment]
```rust
#[derive(Debug)]
struct Foo;

fn main() {
    let v = vec![Some(Foo)];

    if let Some(ref pat) = v[0] {
        println!("{:?}", pat);
    }
}
```

for example cannot be solved by removing `ref`, because you would move the value out of content, so I think this is totaly fine.

**Comment by estebank** [comment]
Current output:

```
error[E0507]: cannot move out of borrowed content
 --> src/main.rs:2:25
  |
2 |     if let Some(&pat) = Some(&Box::new(1)) {
  |                  ---    ^^^^^^^^^^^^^^^^^^ cannot move out of borrowed content
  |                  |
  |                  data moved here
  |
note: move occurs because `pat` has type `std::boxed::Box<i32>`, which does not implement the `Copy` trait
 --> src/main.rs:2:18
  |
2 |     if let Some(&pat) = Some(&Box::new(1)) {
  |                  ^^^
```
