### ISSUE TITLE
Cyclic dependency bug processing RPIT `impl Trait`

### ISSUE THREAD

**Issue by alexreg** [rust-lang/rust#55634]
```rust
trait Foo: Fn(i32) + Send {}

impl<T: ?Sized + Fn(i32) + Send> Foo for T {}

fn gives_foo() -> impl Foo {
    let f = |x| println!("{}", x);
    f
}

fn main() {
    gives_foo()(42);
}
```

yields

```
error[E0391]: cycle detected when processing `gives_foo::{{impl-Trait}}`
 --> test.rs:5:19
  |
5 | fn gives_foo() -> impl Foo {
  |                   ^^^^^^^^
  |
note: ...which requires processing `gives_foo::{{impl-Trait}}`...
 --> test.rs:5:19
  |
5 | fn gives_foo() -> impl Foo {
  |                   ^^^^^^^^
note: ...which requires processing `gives_foo::{{impl-Trait}}`...
 --> test.rs:5:19
  |
5 | fn gives_foo() -> impl Foo {
  |                   ^^^^^^^^
  = note: ...which again requires processing `gives_foo::{{impl-Trait}}`, completing the cycle
note: cycle used when processing `gives_foo`
 --> test.rs:5:1
  |
5 | fn gives_foo() -> impl Foo {
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^
```

I originally thought this was my PR https://github.com/rust-lang/rust/pull/55101 that was at fault, but I've now confirmed this bug occurs on master, so it looks like it isn't... not in the latest nightly though, as of now, so it must have been a recent PR.

CC @nikomatsakis @oli-obk

**Comment by alexreg** [comment]
Okay, weirdly this is only happening when I have `RUST_LOG="rustc_typeck::astconv=debug"`.

**Comment by oli-obk** [comment]
Yea, the logging output might call `type_of` on the item to be printed. If that happens while processing `type_of`, you get a cycle. Not sure how to resolve that

**Comment by alexreg** [comment]
Yep I think that’s it. Hmm.

**Comment by oli-obk** [comment]
Hmm. why does printing cause type_of to be called on the TyAnon? Can you investigate and remove the call? it should not be necessary.

**Comment by steveklabnik** [comment]
Triage: given

> Okay, weirdly this is only happening when I have RUST_LOG="rustc_typeck::astconv=debug".

and how much the compiler has changed since nov of 2018 (even though that module still exists), and with no other comments, I am gonna guess that this may not reproduce, and even if it did, wouldn't affect users. So I'm gonna give it a close. @alexreg if this still reproduces for you today, please feel free to re-open.

**Comment by alexreg** [comment]
@steveklabnik I believe I figured out the cause of this while working on another PR, and solved it. In any case, seems reasonable to close.
