### ISSUE TITLE
False "warning: unused `#[macro_use]` import"

### ISSUE THREAD

**Issue by In-line** [rust-lang/rust#55648]
Logs:
- [Stable 1.30.0](https://travis-ci.org/In-line/source_query_cacher/jobs/450226275#L602)
- [Beta 1.31.0-beta.4](https://travis-ci.org/In-line/source_query_cacher/jobs/450226294#L713)
- [Nightly 1.32.0-nightly](https://travis-ci.org/In-line/source_query_cacher/jobs/450226295#L816)

[Source code](https://github.com/In-line/source_query_cacher/blob/6807abe547ca43e23baea7226f8999918cd6c79d/src/bin/bin.rs)

**Comment by ExpHP** [comment]
It is unused, because `use` statements now import macros (including derives), and you have:

```rust
use structopt::StructOpt;
```

I tried it and the crate does compile without the annotation.

**Comment by In-line** [comment]
Thanks!
