### ISSUE TITLE
NLL Diagnostic Review 3: Diagnostic mentions lack of initialization instead of incorrect mutability

### ISSUE THREAD

**Issue by davidtwco** [rust-lang/rust#55652]
@pnkfelix's review comments: 
> ui/borrowck/reassignment_immutable_fields_overlapping.nll.stderr AST-borrowck complains about the local being immutable. NLL complains about lack of initialization. This is probably expected, but we should double-check.

**Comment by pnkfelix** [comment]
triage: P-medium. (We should look into this, but even if its wrong, I'm not going to push for a backport.)
