### ISSUE TITLE
Duplicated documentation for primitive type pointer

### ISSUE THREAD

**Issue by d-e-s-o** [rust-lang/rust#55656]
Please have a look at 
![rust-doc-multiple-links-to-same-stuff](https://user-images.githubusercontent.com/6610056/47954806-0b9ac100-df4c-11e8-9a20-464290181c1f.png)
(source https://doc.rust-lang.org/std/primitive.pointer.html)

It appears that for some reason the documentation for `primitive type pointer` contains a duplicated set of documentation links. `is_null`, `as_ref` and all subsequent methods appear twice in the pane on the left. The links are exactly identical from what I can tell. Not sure whether the problems lies with Rust doc, the documentation itself, or some part of the [doc.rust-lang.org](https://doc.rust-lang.org)( infrastructure (unlikely, I guess).

**Comment by steveklabnik** [comment]
I believe this is a duplicate; there’s an old issue about NonNull. I’m on my phone so I can’t look for it right now.

**Comment by oli-obk** [comment]
isn't this duplication just a result of `*const T` and `*mut T` being distinct types?

**Comment by GuillaumeGomez** [comment]
Possibly.
