### ISSUE TITLE
NLL Diagnostic Review 3: Unions not reinitialized after assignment into field

### ISSUE THREAD

**Issue by davidtwco** [rust-lang/rust#55651]
@pnkfelix's review comments:
> ui/borrowck/borrowck-union-move-assign.nll.stderr rejecting sound uses of unions; it reports 3 errors when only one expected. We should make a run-pass test from the two cases we expect to accept.

For the record, here's the relevant part of the test in question ([play](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=d379adbbd3f8e54cf8352a824bd2adf1)):

```rust
#![feature(untagged_unions)]
struct A;
struct B;
union U {
    a: A,
    b: B,
}
fn main() {
    unsafe {
        {
            let mut u = U { a: A };
            let _a = u.a;
            u.a = A;
            let _a = u.a; // OK
        }
        {
            let mut u = U { a: A };
            let _a = u.a;
            u.b = B;
            let _a = u.a; // OK
        }
    }
}
```

**Comment by pnkfelix** [comment]
This should be NLL-complete, not NLL-sound, right?

**Comment by davidtwco** [comment]
@pnkfelix Yeah, it should. My bad.

**Comment by pnkfelix** [comment]
I think it would be a good idea to make a run-pass test adapted from the two parts of the test that do not error, checking that the state of the union is set up in the expected manner.

**Comment by pnkfelix** [comment]
triage: P-high, not *not* Release milestone. This issue is bad enough for fix quickly, but there's no reason to beta-backport (as I explained on the PR itself here https://github.com/rust-lang/rust/pull/55657#issuecomment-436267272 )
