### ISSUE TITLE
Way to turn off cargo progressbar

### ISSUE THREAD

**Issue by mocsy** [rust-lang/rust#55677]
Since 1.30 Cargo comes with a strange progress-bar which is turned on by default.
It significantly increases the lines on the output and requires a lot more scrolling if I want to look at what cargo did.
I want to turn it off permanently.

Maybe off by default would be nice for anything large enough to have more than 3 dependencies?

Example output from my console:

`Building [====================================================>  ] 212/216:                                                                                     Building [====================================================>  ] 212/216:                                                                                     Building [====================================================>  ] 212/216:                                                                                     Building [=====================================================> ] 213/216:                                                                                     Building [=====================================================> ] 213/216:                                                                                     Building [=====================================================> ] 213/216:                                                                                     Building [=====================================================> ] 214/216:                                                                                     Building [=====================================================> ] 214/216:                                                                                     Building [=====================================================> ] 214/216:                                                                                     Building [=====================================================> ] 214/216:                                                                                     Building [=====================================================> ] 214/216:                                                                                     Building [=====================================================> ] 215/216:                                                                                                                                                                     Finished dev [unoptimized + debuginfo] target(s) in 1m 32s`

Nothing useful here to see, got to scroll back an entire screen to find a useful information.

**Comment by jonas-schievink** [comment]
That's a bug either in Cargo or in the terminal library it's using. The progress bar normally just occupies a single line and disappears completely when the build is done.

**Comment by nagisa** [comment]
The bug should be reported against [cargo](https://github.com/rust-lang/cargo/issues) instead. Closing.
