### ISSUE TITLE
Adding a equality constraint on an associated type can break the checks

### ISSUE THREAD

**Issue by tomaka** [rust-lang/rust#55697]
The following code works fine:

```rust
trait Upgr<S> {}

trait Proto {
    type S;
    type Upgr: Upgr<Self::S>;
}

struct Wrapper<P>(P);

impl<P: Proto> Proto for Wrapper<P> {
    type S = P::S;
    type Upgr = P::Upgr;
}
```

However if you change the last few lines for this:

```rust
impl<X, P: Proto<S = X>> Proto for Wrapper<P> {
    type S = P::S;
    type Upgr = P::Upgr;
}
```

Then you get:
> error[E0277]: the trait bound `<P as Proto>::Upgr: Upgr<X>` is not satisfied

([link to playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2015&gist=6bb1efd2c4a1ec9cab8b5a6dbb88f357))

Using `type S = X;` also doesn't work.

**Rust version: nightly.**
Apologize if an issue already exists. The vocabulary for this kind of problems is kind of tricky, which makes it hard to search for existing issues.

**Comment by Globidev** [comment]
The playground seems to compile fine since rust `1.49.0`
I can't pinpoint to the exact PR that solved it but this issue seems to be fixed 🙂

**Comment by tomaka** [comment]
Thanks!
