### ISSUE TITLE
Chaining function calls results in different output

### ISSUE THREAD

**Issue by Michael-Dutchband** [rust-lang/rust#55691]
New project, still new to the language, was expecting this to have no effect. Except it does? Not sure what to search for on possible causes.

```
edition = "2018"

[dependencies]
dirs = "1.0"
```

Then just a simple oneliner;
```rust
extern crate dirs;

fn main() {
	let path = dirs::home_dir().unwrap().push("file.txt");

	println!("{:?}", path);
}
```
Gives;
```
> cargo run
   Compiling block_generator v0.1.0 (Z:\block_generator)
    Finished dev [unoptimized + debuginfo] target(s) in 2.06s
     Running `target\debug\block_generator.exe`
()
>
```

What? No panic, just.. nothing? That makes no sense. To debug, I want to easily see the intermediates, so I make it mutable and split it up into two statements;

```rust
extern crate dirs;

fn main() {
	let mut path = dirs::home_dir().unwrap();
	
	path.push("file.txt");

	println!("{:?}", path);
}
```

```
> cargo run
   Compiling block_generator v0.1.0 (Z:\block_generator)
    Finished dev [unoptimized + debuginfo] target(s) in 2.10s
     Running `target\debug\block_generator.exe`
"C:\\Users\\mmee\\file.txt"
>
```

The problem disappeared?

Making the one-liner mutable just makes the compiler warn about it, doesn't result in the correct output.

Since it's "just function calls" I don't think I should be looking at the dirs crate for the culprit. Is there a language nuance I misunderstood?

Using;
> rustc 1.32.0-nightly (8b096314a 2018-11-02)
binary: rustc
commit-hash: 8b096314a6381e28834ddb1e662ce90e5b32736b
commit-date: 2018-11-02
host: x86_64-pc-windows-msvc
release: 1.32.0-nightly
LLVM version: 8.0

(Last two days don't have rls-preview, when I noticed this happening I was running a nightly from half October, so it's been this way a while now)

Thanks

**Comment by jonas-schievink** [comment]
`PathBuf::push` modifies the `PathBuf` in place and returns nothing, or `()`, so that's what you're assigning to `path` in the first example. For questions like this, I recommend posting them to the [user forum](https://users.rust-lang.org/) since this issue tracker is meant for bugs only.

**Comment by Michael-Dutchband** [comment]
I feel stupid now - completely overlooked that! Makes total sense, thanks.
