### ISSUE TITLE
Cross-compiling Rust applications?

### ISSUE THREAD

**Issue by mcandre** [rust-lang/rust#55699]
I tried specifying `ld.lld` as a linker for a NetBSD target, but Rust complains that it cannot find `-lpthread` and so on. Does anyone know if there's a script, ideally for every available rustup target, to automatically install the requisite things to get cross-compilation to work? I imagine MSVC would be rather difficult, as this usually requires a full Visual Studio installation in either a VM or wine or something.

Any interest in promoting cross-compilation into the normal Rust tool set? I'm really jealous of Go's native cross-compilation in comparison, where the user doesn't need to muck around with any additional toolchains, linkers, config files, or headers. It Just Works^TM.

For one-off ports, it's almost worth going through the effort of setting up the right bits for `cargo build --target`... to do its thing. But I wouldn't want to spend that much time, per target, figuring out how to install my dev tools. I'm honestly defaulting to Go for most projects specifically for the cross-compilation support. For Rust, I am working around this limitation by [looping](https://github.com/mcandre/tonixxx/tree/master/examples/bronze) over Vagrant boxes to (semi-)rapidly port my Rust projects to an array of different targets.

I also tried Docker containers, of course, as these would in theory be faster. But it takes too much work to setup cross-compilation toolchains in Linux that VM's seem to be the most efficient option for now :/

**Comment by steveklabnik** [comment]
Please ask questions like this on users.rust-lang.org; we try to keep the issue tracker for bugs only. Thanks!
