### ISSUE TITLE
Global allocator conflict when testing libstd on stage0

### ISSUE THREAD

**Issue by tarka** [rust-lang/rust#55708]
Previously I was able to perform quick testing of libstd using the command `./x.py test src/libstd/ --stage 0 --no-doc`. However this recently started failing with `error: the #[global_allocator] in this crate conflicts with global allocator in: std`. `git bisect` narrows the problem to this commit:

    commit 61e89446ef6e115630faa75c985c599d739f7586
    Author: Alex Crichton <alex@alexcrichton.com>
    Date:   Sat Oct 20 19:04:42 2018 -0700

    Remove all jemalloc-related content
    
    This commit removes all jemalloc related submodules, configuration, etc,
    from the bootstrap, from the standard library, and from the compiler.
    This will be followed up with a change to use jemalloc specifically as
    part of rustc on blessed platforms.

It was merged to master in `6cfc6033955dd2685dfa7baeec6f6bc3bfdfe2f1`.

Is stage0 testing supported, or is this a regression?

cc @alexcrichton

**Comment by alexcrichton** [comment]
stage0 testing isn't supported in the sense that it's not tested on CI, but it's supported in the sense that it should be technically feasible! This probably just needs a `not(test)` annotation somewhere on it to fix the issue!

**Comment by JohnTitor** [comment]
Is this already fixed? I couldn't reproduce this issue.

**Comment by petrochenkov** [comment]
@JohnTitor 
This is a transient stage0 problem, such problems should not be tracked by GitHub issues generally.
