### ISSUE TITLE
nm and llvm-nm fail on x86_64-apple-darwin and x86_64-unknown-linux-gnu

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/rust#55729]
EDIT: this PR reproduces the issue on linux and macosx: https://github.com/alexcrichton/jemallocator/pull/96

To reproduce, 

* fetch this `jemallocator`'s commit: https://github.com/alexcrichton/jemallocator/commit/bc8e0715165778ec7a54569bcf75694009ffd30d
* get the llvm-tools component: ` rustup component add llvm-tools-preview`
* get the path of `llvm-nm`: ./rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/bin/llvm-nm
* build jemallocator (e.g. `cargo build`) and find an rlib: find target/ -name "*jemallocator*.rlib"

* run `llvm-nm` on the rlib

In my system, that produces: 

```
target//debug/deps/libjemallocator-1bcf45a160ad029b.rlib(jemallocator-1bcf45a160ad029b.259l020hnygfmc3u.rcgu.o):
                 U __ZN12jemalloc_sys13MALLOCX_ALIGN17h7c2651df971d116aE
0000000000000000 T __ZN12jemallocator15layout_to_flags17hde8e3346c7bf7f40E

target//debug/deps/libjemallocator-1bcf45a160ad029b.rlib(jemallocator-1bcf45a160ad029b.4se31p93r3crimbe.rcgu.o):
0000000000000000 T __ZN4core3num23_$LT$impl$u20$usize$GT$14trailing_zeros17h7ff2703fc51580f0E

target//debug/deps/libjemallocator-1bcf45a160ad029b.rlib(jemallocator-1bcf45a160ad029b.lca5ibdjxqyke4u.rcgu.o):
0000000000000000 T __ZN12jemalloc_sys13MALLOCX_ALIGN17h7c2651df971d116aE
                 U __ZN4core3num23_$LT$impl$u20$usize$GT$14trailing_zeros17h7ff2703fc51580f0E
/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/bin/llvm-nm: target//debug/deps/libjemallocator-1bcf45a160ad029b.rlib(rust.metadata.bin) The end of the file was unexpectedly encountered
```

> The end of the file was unexpectedly encountered

I get the same error with the system's `nm`.

This might be a regression.

**Comment by alexcrichton** [comment]
AFAIK this has always been the case, `nm` has never been able to process all entries in an archive.

**Comment by gnzlbg** [comment]
Damn, I've used the system's nm a lot in the `mach` crate and never had an issue with it, but maybe the archives generated don't trigger the issues that the `jemallocator` ones do.

**Comment by jonas-schievink** [comment]
This sounds like a bug in LLVM, so closing in favor of an upstream bug report. Feel free to reopen if this is incorrect. (A combination of the [`ar`](https://crates.io/crates/ar) and [`goblin`](https://crates.io/crates/goblin) crates might yield better results than the LLVM tools here)
