### ISSUE TITLE
std::io::Result<()> is twice as big as it should be

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/rust#55726]
```rust
fn main() {
    let s = std::mem::size_of::<std::io::Result<()>>(); 
    println!("{}", s);
}
```

returns 16 on the playground, but on `x86_64-unknown-linux-gnu` AFAICT `std::io::Result<()>` is either `Ok` if the error code is zero, or an `Err` if the error code is not-zero. That means that it should have the same size as `c_int`.

The problem appears to be that the `Error` type can be zero. It has three variants:

* `Os(i32)`  [here](https://github.com/rust-lang/rust/blob/9653f790333d1270f36f1614e85d8a7b54193e75/src/libstd/io/error.rs#L78) should probably be `Os(NonZero<i32>)` at least on unixes, 
* `ErrorKind` [here](https://github.com/rust-lang/rust/blob/9653f790333d1270f36f1614e85d8a7b54193e75/src/libstd/io/error.rs#L101) can be zero, but maybe we can avoid this by giving the variants values that are not zero?
* `Box<...>` is never null, so there is nothing to do here.

If there is a way to ensure that `Error` is never zero, then we can fix this issue.

**Comment by gnzlbg** [comment]
cc @eddyb

**Comment by eddyb** [comment]
Isn't `io::Result<()>` the same size as `io::Error`?
It's impossible to make it any smaller, because `io::Result<()>` contains `io::Error`.

`Result<(), Option<Box<T>>>` is 16 bytes too on x64, and has a subset of `io::Result<()>`'s values.

**Comment by gnzlbg** [comment]
> Isn't io::Result<()> the same size as io::Error?

Indeed, for some reason I assumed that `io::Error` would be just a `c_int` in unixes, but it appears that it does a lot more.
