### ISSUE TITLE
Replace an occurrence of nearest_common_ancestor with is_direct_ancestor

### ISSUE THREAD

**Issue by jameshamm** [rust-lang/rust#55727]
In a [blog post](https://blog.mozilla.org/nnethercote/2018/04/30/how-to-speed-up-the-rust-compiler-in-2018/) concerned with the performance of the rust compiler, it mentions nearest_common_ancestor (in [region.rs](https://github.com/rust-lang/rust/blob/master/src/librustc/middle/region.rs#L605)) is a hot section of code.

To see where the function is used, I grepped the repo for the function name, which gave 3 results. They are the function definition and two uses of it in [mod.rs](https://github.com/rust-lang/rust/blob/master/src/librustc/infer/lexical_region_resolve/mod.rs).

```
$ grep -r "nearest_common_ancestor"
src/librustc/infer/lexical_region_resolve/mod.rs:                    .nearest_common_ancestor(fr_scope, s_id);
src/librustc/infer/lexical_region_resolve/mod.rs:                    .nearest_common_ancestor(a_id, b_id);
src/librustc/middle/region.rs:    pub fn nearest_common_ancestor(&self, scope_a: Scope, scope_b: Scope) -> Scope {
```

The first use of it checks if the nearest common ancestor is the first of the two checked nodes (scopes in this case).

```
let r_id = self.region_rels
    .region_scope_tree
    .nearest_common_ancestor(fr_scope, s_id);
if r_id == fr_scope {
    ...
}
```
The current implementation is overkill as this is equivalent to checking if the first parameter is the same as the second parameter, or is a direct ancestor of the second. Checking if a node is an ancestor of another would hopefully be much simpler and more performant.

```
let region_scope_tree = self.region_rels.region_scope_tree;
if region_scope_tree.is_direct_ancestor(fr_scope, s_id) {
   ...
}
```

An example implementation of the proposed function could look something like a modified version of the current code for nearest common ancestor

```
pub fn is_direct_ancestor(&self, scope_a: Scope, scope_b: Scope) -> bool {
    if scope_a == scope_b { return true; }

    let mut a = scope_a;

    // If `a` has no parent it must be the root, which guarantees
    // it must be a direct ancestor of `b`.
    let (parent_a, parent_a_depth) = match self.parent_map.get(&a) {
        Some(pd) => *pd,
        None => return true,
    };

    let mut b = scope_b;

    // If `b` has no parent it must be the root.
    // As they are not the same scope, `a` is not a direct ancestor.
    let (parent_b, parent_b_depth) = match self.parent_map.get(&b) {
        Some(pd) => *pd,
        None => return false,
    };

    if parent_a_depth >= parent_b_depth {
        // `a` is lower than or the same height as `b`, so it cannot be a direct ancestor. 
        return false;
    }
    
    // Walk `b` up the tree until it is at the same depth as `a`.
    b = parent_b;
    for _ in 0..(parent_b_depth - parent_a_depth - 1) {
        b = self.parent_map.get(&b).unwrap().0;
    }

    // If they are not the same node when at the same depth, then `a` is not an ancestor of `b`
    return a == b;
}
```

This could do less work if the function is to return false, and roughly the same if it is true. If maintaining the parent_map used to get the parent id and depth is too costly, another implementation could be a copy of "is_descendant_of" from [another section of the compiler](https://github.com/rust-lang/rust/blob/master/src/libsyntax_pos/hygiene.rs#L136) modified to work on scopes.

Since I don't have performance numbers (or any other metrics to back me up), take the above with a grain of salt.

**Comment by nnethercote** [comment]
Thanks for the suggestion. I just looked at a bunch of profiles and the previous improvements to `nearest_common_ancestor` mean that it's no longer a hotspot. E.g. in a couple of workloads it accounted for just over 0.1% of instructions executed, but in most workloads it didn't even register that high. So I don't there's much blood left to be squeezed from this stone :)

Also, I heard that the function might be removed altogether once the old borrow checker is removed. @nikomatsakis, is that true?

**Comment by kadiwa4** [comment]
Neither of the 2 functions exist anymore, so I assume this is irrelevant now
