### ISSUE TITLE
[Rust 2018] cannot use `pest` `#[grammar = "..."]` without `#[macro_use] extern crate pest_derive;`

### ISSUE THREAD

**Issue by lucatrv** [rust-lang/rust#55735]
As in subject, I understood that with Rust 2018:
```rust
#[macro_use] extern crate pest_derive;
```
should not be required anymore, as reported here:
https://rust-lang-nursery.github.io/edition-guide/rust-2018/macros/macro-changes.html

However, without that statement, the following code fails to compile:
```rust
#[derive(Parser)]
#[grammar = "csv.pest"]
pub struct CSVParser;
```
with error:

> error[E0658]: The attribute `grammar` is currently unknown to the compiler and may have meaning added to it in the future (see issue #29642)

**Comment by steveklabnik** [comment]
Did you

    use pest_derive::Parser;

?

**Comment by lucatrv** [comment]
Sorry, I just did:
```rust
use pest::Parser;
```
Thanks for your hint
