### ISSUE TITLE
Formatted print doesn't work as expected with debug + enum

### ISSUE THREAD

**Issue by macabeus** [rust-lang/rust#55749]
If you use the debug print and a formatter such as `{: <3?}` with a `enum` to print the case name, the code does not work as expected.

```rust
#[derive(Debug)]
enum MyEnum {
    AB,
}

fn main() {
    let value = MyEnum::AB;
    println!("[{: <3?}]", value); // The result is `[AB]`
                                  // while I expected that the result is `[AB ]`.
}
```

It's only work if the enum has a value:

```rust
#[derive(Debug)]
enum MyEnum {
    AB(i32),
}

fn main() {
    let value = MyEnum::AB(42);
    println!("[{:<3?}]", value); // The result is `[42 ]`
}
```

Maybe we should fix this behaviour?

[Also, I've open a question at Stackoverflow about this behaviour.](https://stackoverflow.com/questions/53183198/why-debug-print-does-not-formatted-an-enum-as-expected)

**Comment by hellow554** [comment]
As already said on Stackoverflow, this might be related to https://github.com/rust-lang/rust/issues/55584

**Comment by estebank** [comment]
Closing as duplicate of #55584.
