### ISSUE TITLE
Avira anti-virus marks this item as infected

### ISSUE THREAD

**Issue by paul-hammant** [rust-lang/rust#55763]
`rustc-1.30.0-src/src/tools/lldb/unittests/SymbolFile/DWARF/Inputs/test-dwarf.exe`

It is installed for some unit test with Rust for some purpose ?

Relates to (Mac):

`Homebrew/downloads/1d49ea42373b3bc3a966ce08027f958cb636942ca4e1d2273dd608b9c29a0485--rustc-1.30.0-src.tar.gz`

**Comment by jonas-schievink** [comment]
It's part of LLDB's test suite and likely a false positive

**Comment by paul-hammant** [comment]
I'll inform Avira that https://github.com/llvm-mirror/lldb/blob/master/unittests/SymbolFile/DWARF/SymbolFileDWARFTests.cpp (or the exe from it) is innocent.

**Comment by paul-hammant** [comment]
![image](https://user-images.githubusercontent.com/82182/49792764-70a3bc80-fd2b-11e8-9899-d34c0e59b8ab.png)
