### ISSUE TITLE
Non-deterministic bytes within newly init, unsafely extended vector

### ISSUE THREAD

**Issue by flagello** [rust-lang/rust#55776]
~Nightly-only failure as far as I can see.~ I am able to reproduce in a few single runs locally on nigthly, [while an infinite loop did the trick within the playground on both nigthly](
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2015&gist=92eadab21e26625996b08d4a388da2c9) and [stable](https://play.rust-lang.org/?version=stable&mode=debug&edition=2015). _(Update: Am I missing something? Should I always zero-out manually?)_

```rust
fn test() {
    let mut a: Vec<u8> = Vec::new();
    let mut b: Vec<u8> = vec![0];

    const x: usize = 4096;
    const k: usize = 512;
    const z: usize = 64;
    let y = 2;
    let a_len = a.len();
    let b_len = b.len();

    a.reserve(x);
    b.reserve(k);

    unsafe { a.set_len(a_len + y * z) };
    unsafe { b.set_len(b_len + y * z) };

    assert_eq!(a.iter().max(), Some(&0));
    assert_eq!(b.iter().max(), Some(&0));
}
```

`git clone git@github.com:flagello/rust-nightly-test-case-a.git`

**Comment by jonas-schievink** [comment]
I don't see any reason why this should have ever worked, uninitialized memory can contain anything. The behaviour might have changed with the move to the system allocator.

**Comment by flagello** [comment]
I see. I was unaware I need zero-out if I am expecting them to be there. Thanks!
