### ISSUE TITLE
Combine 32-bit and 64-bit code

### ISSUE THREAD

**Issue by phil-opp** [rust-lang/rust#55773]
I'm trying to write a x86 bootloader in Rust, that initializes the CPU from 16-bit real mode to 32-bit protected mode to 64-bit long mode. This means that I have to combine code for the different modes in a single executable. I'm currently using global_asm for the 16-bit and 32-bit code (together with the `.code16` and `.code32` inline assembly flags), but I would like to port the 32-bit stage to Rust.

So I would like to link 32-bit Rust code with 64-bit Rust code. My approach was to create a `protected_mode` sub-crate that is compiled through a build script and later linked in. The question is how I can link the two crates with different targets together. I tried the following approaches:

- Adding `extern crate protected_mode` to the parent crate and passing the protected_mode rlib as `--extern` argument to rustc. This errors because the targets don't match.
- Passing the rlib to the linker without adding extern crate: This works, but only if I keep the sub-crate very simple. As soon as I try to use the formatting system or anything that might panic, I get linker errors about undefined symbols: <details>
    ```
  = note: rust-lld: error: undefined symbol: core::fmt::num::_$LT$impl$u20$core..fmt..Display$u20$for$u20$u32$GT$::fmt::hb0a0361a2e8dea8a
          >>> referenced by protected_mode.9viz2vjs-cgu.7
          >>>               protected_mode-90beb11cf4901381.protected_mode.9viz2vjs-cgu.7.rcgu.o:(stage_3) in archive protected_mode/target/i686-bootloader/release/libprotected_mode.rlib
          
          rust-lld: error: undefined symbol: core::fmt::write::h2819bacac5a4927b
          >>> referenced by protected_mode.9viz2vjs-cgu.7
          >>>               protected_mode-90beb11cf4901381.protected_mode.9viz2vjs-cgu.7.rcgu.o:(stage_3) in archive protected_mode/target/i686-bootloader/release/libprotected_mode.rlib
          
          rust-lld: error: undefined symbol: core::panicking::panic_bounds_check::h6267e601085674a8
          >>> referenced by protected_mode.9viz2vjs-cgu.1
          >>>               protected_mode-90beb11cf4901381.protected_mode.9viz2vjs-cgu.1.rcgu.o:(core::fmt::Write::write_char::h6daa05da5e25b944) in archive protected_mode/target/i686-bootloader/release/libprotected_mode.rlib
          
          rust-lld: error: undefined symbol: core::fmt::write::h2819bacac5a4927b
          >>> referenced by protected_mode.9viz2vjs-cgu.2
          >>>               protected_mode-90beb11cf4901381.protected_mode.9viz2vjs-cgu.2.rcgu.o:(_$LT$core..fmt..Write..write_fmt..Adapter$LT$$u27$_$C$$u20$T$GT$$u20$as$u20$core..fmt..Write$GT$::write_fmt::h6d6f1028afbd8582) in archive protected_mode/target/i686-bootloader/release/libprotected_mode.rlib
          
          rust-lld: error: undefined symbol: core::panicking::panic_bounds_check::h6267e601085674a8
          >>> referenced by protected_mode.9viz2vjs-cgu.2
          >>>               protected_mode-90beb11cf4901381.protected_mode.9viz2vjs-cgu.2.rcgu.o:(_$LT$core..fmt..Write..write_fmt..Adapter$LT$$u27$_$C$$u20$T$GT$$u20$as$u20$core..fmt..Write$GT$::write_str::hcc7ec8903b08bf8c) in archive protected_mode/target/i686-bootloader/release/libprotected_mode.rlib
    ```
</details>

- Compiling the sub-crate as staticlib. This throws linker errors about duplicate `rust_begin_unwind` and `rust_eh_personality` symbols, since they are defined in both the staticlib and the executable. I tried to rename them, but it seems like these names are hardcoded internally.

Is there any other way to combine 32-bit and 64-bit code?

**Comment by nagisa** [comment]
Compile all the binaries separately (into statically linked static relocation executables, not libraries) and combine them all into a single binary as the final link step by placing binary executables. This is commonly done in e.g. embedded to achieve separation between the bootloader and the application (making application firmware updatable).

The usual approach is this:

1. Pick which binary will be your "master" and use a linker script carve out sections of sufficient size at predefined addresses for the sub-firmwares (most of the time it does not matter which binary is the “one”);
2. Compile the executables for the other targets and convert them to binary files (objcopy -O binary);
3. Place said binary files into the sections carved out previously.

---

That being said… This is a tracker for the issues in rustc. For support, consider posting your question on [users.rlo](https://users.rust-lang.org/), [stackoverflow](https://stackoverflow.com/), [reddit](https://www.reddit.com/r/rust/), or asking on one of the chat platforms: [#rust on irc.mozilla.org](https://www.rust-lang.org/en-US/community.html#irc-channels), [discord](https://discordapp.com/invite/aVESxV8) or [zulip](https://rust-lang.zulipchat.com/#).

Thus closing.

**Comment by phil-opp** [comment]
@nagisa Thanks a lot for the explanation!

Sorry for opening an issue for this. I wasn't sure whether the duplicate symbols and the linker errors are intended or maybe a bug. I will ask at other places first in the future.
