### ISSUE TITLE
Tool to detect/display function dependencies in Rust crates

### ISSUE THREAD

**Issue by pcwalton** [rust-lang/rust#558]
This would be useful for many things:

* Figuring out which functions are dead and can be removed.
* Visualize function dependencies (with `dot`).
* Be the basis for a Rust `ccache` workalike.
* On-demand, lazy unit tests.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#605
