### ISSUE TITLE
Name _ defined multiple times

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#55811]
https://crater-reports.s3.amazonaws.com/beta-1.31-1/beta-2018-10-30/reg/type_level_examples-0.0.22/log.txt, https://crates.io/crates/type_level_examples/0.0.22

```
error[E0428]: the name `_` is defined multiple times
Nov 02 01:29:54.935 INFO kablam!   |
Nov 02 01:29:54.935 INFO kablam!   = note: `_` must be defined only once in the type namespace of this module
```

This appears to ICE on nightly so maybe that's the underlying cause?

cc @petrochenkov

**Comment by petrochenkov** [comment]
Fixed in https://github.com/rust-lang/rust/pull/56117
