### ISSUE TITLE
Rust's release-mode overflow mode with division is slightly weird

### ISSUE THREAD

**Issue by ubsan** [rust-lang/rust#55829]
This is not technically a bug, but is odd. For most operations, `overflow-checks = false` makes `x + y` equivalent to `x.wrapping_add(y)`, for example - however, for division and remainder that isn't true. `x / y` is actually equivalent to, well, `x / y` in debug mode. Is this intentional?

**Comment by sfackler** [comment]
Division by 0 is undefined behavior in LLVM so the checks need to stay in unconditionally I believe: https://llvm.org/docs/LangRef.html#udiv-instruction

**Comment by ubsan** [comment]
@sfackler ah, interesting! It would be good to make sure that `(MIN / -1) = MIN` is valid behavior in release mode, even if it's not the behavior we follow in rustc.
