### ISSUE TITLE
error message when creating a closure and directly calling not very clear

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/rust#55851]
Creating a closure and directly calling it:

```rust
fn main() { let _ = ||{}(); }
```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=71d1d0422049f8b5b9b0bb866da117e7))

Errors:

```
   Compiling playground v0.0.1 (/playground)
error[E0618]: expected function, found `()`
 --> src/main.rs:1:23
  |
1 | fn main() { let _ = ||{}(); }
  |                       ^^^^ not a function

error: aborting due to previous error
For more information about this error, try `rustc --explain E0618`.
```

Which doesn't really hint at what the problem is. The problem is that the closure must be surrounded by `()` - [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=080dab281694a896b7920ccce9a3e389):

```rust
fn main() { let _ = (||{})(); }
```

**Comment by estebank** [comment]
To make matters more fun, the following is valid rust code:

```
fn main() { let _ = ||{||{}}(); }
```

---

It'll be hard to deal with this as it's the parser creating a certain AST that the type checker then chokes on without enough context. We might be able to special case this, but would only feel comfortable if it were a very small amount of code to deal with it.
