### ISSUE TITLE
Remove the !Send and !Sync impls for proc_macro::LineColumn

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust#55881]
https://doc.rust-lang.org/1.30.0/proc_macro/struct.LineColumn.html

https://github.com/rust-lang/rust/blob/ca79ecd6940e30d4b2466bf378632efcdf5745c7/src/libproc_macro/lib.rs#L396-L404

https://github.com/rust-lang/rust/blob/ca79ecd6940e30d4b2466bf378632efcdf5745c7/src/libproc_macro/lib.rs#L406-L409

This struct consists of two public fields. It holds a line number and a column number. Given that all the fields are public, no additional private state could be added here backward compatibly in the future. As such, it should be fine for this type to be Send and Sync.

This came up because in proc-macro2 there is no way for us to opt out of auto traits for such a struct in a way that supports current stable Rust.

@eddyb this type has no private state so I assume it is the exception you had in mind in https://github.com/alexcrichton/proc-macro2/issues/141#issuecomment-434876734.

**Comment by eddyb** [comment]
Yeah, pretty much.

**Comment by Centril** [comment]
> This struct consists of two public fields. It holds a line number and a column number. Given that all the fields are public, no additional private state could be added here backward compatibly in the future. As such, it should be fine for this type to be Send and Sync.

The fields and the type are not stabilized yet tho so we can change things?
I'm inclined to not have public fields here or at least have one private field that let's us extend this type in the future if we want to.

**Comment by eddyb** [comment]
> at least have one private field

We can just use `#[non_exhaustive]` now, can't we?

But also, this is literally a newtyped pair of integers, to give field names.
`LineColumn` is, and will ever be, *just* a line and a column.

We wouldn't change it in the future, if we needed to provide more information, we'd instead add more APIs wherever we currently return a `LineColumn`, to return something else.

**Comment by Centril** [comment]
> We can just use `#[non_exhaustive]` now, can't we?

If it works. ;)

> We wouldn't change it in the future, if we needed to provide more information, we'd instead add more APIs wherever we currently return a `LineColumn`, to return something else.

That doesn't seem like a good assumption to me; imo let's do the conservative thing for now. Also, the `1`-indexed nature of `LineColumn` is not something you can make sure of when you expose the field as public.

That said, I have no problems with removing `!Send` and `!Sync` here specifically.

Also... Not to start a bikeshed... but `LineColumn` feels like someone took `pub line` and `pub column` and then stuck them together into `LineColumn`; It's descriptive/literal but it also doesn't seem conventional.

**Comment by eddyb** [comment]
> Also... Not to start a bikeshed... but `LineColumn` feels like someone took `pub line` and `pub column` and then stuck them together into `LineColumn`; It's descriptive/literal but it also doesn't seem conventional.

Yes, that's *literally* what it is, it's `{ line: usize, column: usize }` (but we don't have records).

**Comment by steveklabnik** [comment]
This code now lives in `.\src\libproc_macro\lib.rs`, but still has the impls.

**Comment by eddyb** [comment]
@steveklabnik I'm confused, the PR description links to `src/libproc_macro/lib.rs` (and it doesn't even look edited), did you mean it was moved somewhere else?

**Comment by kadiwa4** [comment]
outdated issue; `LineColumn` was removed in 1.72.0.
