### ISSUE TITLE
Fail to download files during bootstrap

### ISSUE THREAD

**Issue by herquan** [rust-lang/rust#55887]
I tried run command to build:
`python x.py build`
But failed with this error message:
```
Exception calling "DownloadFile" with "2" argument(s): "The request was aborted: Could not create SSL/TLS secure
channel."
At line:1 char:1
+ (New-Object System.Net.WebClient).DownloadFile('https://static.rust-l ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException
```
I checked the code and found we download bootstrap files through powershell command, which I guess is not necessary. So attachment is my fix, using urllib rather than external dependencies.

[patch.diff.txt](https://github.com/rust-lang/rust/files/2570600/patch.diff.txt)
The HEAD before my change is `06118eac4c602a22d2004c98756a95f2c5ec95d5`

**Comment by ehuss** [comment]
See #55840 for the proposed fix.

**Comment by estebank** [comment]
Closing as per #55840.
