### ISSUE TITLE
#[link_args] attribute is always linted as unused

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#55895]
Spawned off of https://github.com/rust-lang/rust/issues/29596#issuecomment-368060862

This code ([play](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2015&gist=d728ae6e5e092b07bb57e7dee82301d0)):

```rust
#![feature(link_args)]

#![link_args = ""]
fn main() {}
```

issues the following diagnostic output:

```
warning: unused attribute
 --> src/main.rs:3:1
  |
3 | #![link_args = ""]
  | ^^^^^^^^^^^^^^^^^^
  |
  = note: #[warn(unused_attributes)] on by default
```

(It doesn't matter what you put into the `link_args` string argument; I just chose an empty string to demonstrate a case where the input would (portably) compile successfully apart from the aforementioned warning.)

At this point I don't know if the original intention was for `#[link_args]` to only have semantic meaning when attached to particular items (e.g. `extern { ... }` blocks), or if this is just some oversight during implementation of its feature gate, but it certainly seems wrong.

**Comment by petrochenkov** [comment]
This is still an issue even if the attribute is attached to an `extern` block.
```
#![feature(link_args)]

#[link_args = "-static"] // warning: unused attribute
extern {}

fn main() {}
```

**Comment by kadiwa4** [comment]
Outdated issue: `#[link_args]` has been removed in favor of `-C link-arg=ARG`.
