### ISSUE TITLE
Add allow-by-default lint when using item deprecated in the future

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#55892]
With https://github.com/rust-lang/rust/issues/30785 resolved, there now is a way to deprecate an item "for the future".  It would be nice to be able to e.g. clean libstd from using such future-deprecated items and then to make sure that future PRs will not re-introduce new uses of that item again. I am thinking, for example, of when we will deprecate `mem::uninitialized` in favor of `MaybeUninit`: Once we got rid of all its uses in some crate here, we'll want to make sure people not aware of this deprecation do not accidentally reintroduce new uses of `mem::uninitialized` in libstd.

So maybe we could have an allow-by-default lint that libstd (and its dependencies) opt in to that complains about using items that are marked for future deprecation?

**Comment by varkor** [comment]
This should be very straightforward to add by essentially copying what the current `deprecated` lint does, but limited to future deprecations.
https://github.com/rust-lang/rust/blob/d6828cefd3787e8a732991d6273afc8793104cc3/src/librustc/lint/builtin.rs#L217-L222
I can provide more detailed mentoring for those interested in tackling the issue, but I imagine one should be able to figure out the details without too much trouble.

**Comment by mominul** [comment]
I'd like to take this issue! If I get struck, I'll ask on the discord channel.

**Comment by mominul** [comment]
Sorry, I got quite busy in my studies. If anyone wants to take this issue in the meantime, please do!

**Comment by aheart** [comment]
I would like to give this a try.

**Comment by FrankSD** [comment]
Can i  take  this  issue?

**Comment by RalfJung** [comment]
I'm afraid it is already taken: https://github.com/rust-lang/rust/pull/56203
