### ISSUE TITLE
Setup Indy SDK build environment for Windows

### ISSUE THREAD

**Issue by liviu99** [rust-lang/rust#55924]
I am trying to setup Indy SDK build environment for Windows following https://github.com/hyperledger/indy-sdk/blob/master/doc/windows-build.md steps.
Unfortunately, after I run **cargo build** command, I get the following error:
failed to parse manifest at Cargo.toml.

Caused by: could not parse input as TOML

Caused by: unexpected character found: '\u{0}' at line 1

**Comment by retep998** [comment]
Why does your `Cargo.toml` start with a `NUL` byte?

**Comment by liviu99** [comment]
I've done again all the steps within the tutorial and now works. Thank you!
