### ISSUE TITLE
rustdoc doesn't handle #![feature] attributes

### ISSUE THREAD

**Issue by QuietMisdreavus** [rust-lang/rust#55938]
With the following crate:

```rust
#![feature(doc_cfg)]

#[doc(cfg(unix))]
pub struct SomeStruct;
```

Attempting to build it on stable will fail as expected, but generating docs will pass, no problem:

```console
$ cargo +stable build
   Compiling asdf v0.1.0 (/home/misdreavus/git/asdf)
error[E0554]: #![feature] may not be used on the stable release channel
 --> src/lib.rs:1:1
  |
1 | #![feature(doc_cfg)]
  | ^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0554`.
error: Could not compile `asdf`.

To learn more, run the command again with --verbose.

$ cargo +stable doc
 Documenting asdf v0.1.0 (/home/misdreavus/git/asdf)
    Finished dev [unoptimized + debuginfo] target(s) in 0.79s
```

The output docs also happily use the feature in question:

![image](https://user-images.githubusercontent.com/5217170/48446990-614b4680-e760-11e8-8a25-2bd2691eaf0b.png)

I would expect rustdoc to also choke on the `#![feature]` attribute, but it turns out that it doesn't. This is probably not an issue in practice, but this doesn't seem intended?

**Comment by abonander** [comment]
It would actually be neat if `rustdoc` rendered information about the nightly features a crate uses in the root docs.

**Comment by najamelan** [comment]
I think this is broken as of stable 1.41 (haven't double checked version exactly), which is a regression. It broke my CI on stable... It is a little annoying to work around. You must not use a cargo feature to turn this on, lest `--all-features` now doesn't work anymore on stable and you must always run rustdoc with `cargo +nightly doc`. 

@yandros posted a workaround for avoiding enabling with a feature [on the user forum](https://users.rust-lang.org/t/blog-post-crate-publishing-tips-and-guidelines/39391/8?u=najamelan).

**Comment by najamelan** [comment]
Further breakage comes with `cargo test`. If using the workaround posted by @yandros, `rustdocflags` will be enabled for doc tests, so `cargo test` will no longer work on stable.

**Comment by jyn514** [comment]
> I would expect rustdoc to also choke on the #![feature] attribute, but it turns out that it doesn't. This is probably not an issue in practice, but this doesn't seem intended?

This was fixed at some point, stable now correctly gives an error:

```
$ rustdoc +stable --version
rustdoc 1.50.0 (cb75ad5db 2021-02-10)
$ rustdoc +stable feature.rs 
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> feature.rs:1:1
  |
1 | #![feature(doc_cfg)]
  | ^^^^^^^^^^^^^^^^^^^^

error: Compilation failed, aborting rustdoc
```

**Comment by jyn514** [comment]
> It would actually be neat if `rustdoc` rendered information about the nightly features a crate uses in the root docs.

This seems useful - could you open a separate issue for it?
