### ISSUE TITLE
Adding new crate-type target increases size of another crate-type target

### ISSUE THREAD

**Issue by tiras-j** [rust-lang/rust#55942]
**Problem**
Adding an additional crate-type listing appears to affect the size of other crate types, specifically moving from `crate-type = ["cdylib", "staticlib"]` --> `crate-type = ["cdylib", "staticlib", "rlib"]` appears to increase the size of the "cdylib" output (in this case a Linux `.so` ELF) by 100% (2MB -> 4MB) which is suspiciously close to the size of the "rlib" output.

The motivation is to provide benchmarking (via [criterion](https://github.com/japaric/criterion.rs)) which of course involves depending on the the core crate to build benchmark functions against. This dependency requires a Rust-style output target, not an arbitrary binary that "cdylib" generates. Adding the "rlib" target does in fact allow the benchmarking but the side-effect of the dramatically increased binary size is not viable, and this size increase appears through the standard `cargo build --release` process itself.

**Steps**
Hard to provide concise steps - but basically add an "rlib" type target for an existing "cdylib" crate that exports an some FFI? If this is a _me_ problem, I'd love to hear how to fix this!

**Notes**

Output of `cargo version`:
`cargo 1.30.0 (36d96825d 2018-10-24)`

Also - `rustc 1.30.0 stable` as the toolchain.

**Comment by alexcrichton** [comment]
I've also transferred this issue to rust-lang/rust because I believe this is largely a compiler issue rather than a Cargo issue

**Comment by tiras-j** [comment]
I see! Yea I was speculating it might be compiler being a bit too clever in optimizing build times by re-using some incremental steps that were much larger for the rlib target. I wonder if changes the order of the crate-type targets would have an impact? I'll try to throw together a simple project that demonstrates this behavior - hopefully it shouldn't be too hard.

In the mean-time do you have any thoughts on the problem I was originally trying to tackle - namely conditionally building a Rust lib (rlib or lib, just not cdylib etc) when running benchmark suites so that I can properly `extern crate <mycrate>` in the external benchmarks? The workaround I currently am using is running the benchmark against the cdylib by mapping the exported FFI symbols (which in reality is a better "true" benchmark in some ways). I'm doing this with a conditional `rustc-link-search=target/release` in an empty build script - but it requires that the release binary be pre-built (since it doesn't seem that any intermediate build from the `cargo bench` command generates full cdylib outputs that I can find?)

I'd be happy with either conditionally building a lib/rlib crate-type for `cargo bench` or having a proper link path to a binary that's built as part of the bench target that I can reliably link against instead of relying on the binary being pre-built with a `cargo build --release` before running the `cargo bench`.

**Comment by tiras-j** [comment]
I see - that should be simple enough to put together! I'll still try to throw together a quick project that demonstrates this behavior to link here just for future investigation.

Thanks for the help!

**Comment by tiras-j** [comment]
@alexcrichton I was looking at this again today and I'm almost certain it has to do with "rlib" targets interfering with LTO on the "cdylib" target. I have a tiny example project with this behavior I could share if needed (perhaps by pushing it to github and linking? Not sure the best way to share something like that).

But basically adding the "rlib" target seems to cause the DSO to be generated at the same size as a non-LTO release (might be coincidence, but it's certainly something).

**Comment by alexcrichton** [comment]
@tiras-j that sounds right to me! I think the bug here is that there's something like `get_all_exported_symbols` somewhere in the compiler, and the presence of an rlib makes that much larger than it would otherwise be.

**Comment by tiras-j** [comment]
@alexcrichton well looking at the lto.rs [here](https://github.com/rust-lang/rust/blob/f6e9485bfc245eb5f10b1f2b0a786538d12d1cb0/src/librustc_codegen_llvm/back/lto.rs#L111) definitely seems pretty clear that LTO is abandoned if any target is a non-LTO target. However I'm not seeing that diag message compiling with `--verbose` but I also know very little about hacking on the compiler so I'm probably not looking in the right places.

**Comment by alexcrichton** [comment]
@tiras-j oh right yeah, Cargo will silently turn off LTO even though you request it if it sees `rlib` in the crate-types. It does that because of that line in the compiler, it knows it will fail

**Comment by tiras-j** [comment]
@alexcrichton well that certainly explains what I was seeing with the binary size changes when adding an `rlib` target! I suppose we can close this ticket now, however it would be nice if this side-effect was made more visible to the user in some way - particularly since it's likely anyone building `cdylib` targets with LTO enabled will probably care quite a bit about binary size. Manifesting that diag message would likely be enough - but I'm not sure where that message is going during the compilation, as I don't see it shown even when running cargo with `--verbose`. Any thoughts?

**Comment by alexcrichton** [comment]
Ah right this was previously opened as https://github.com/rust-lang/rust/issues/51009, so yeah let's close in favor of that.

It does also seem like some sort of diagnostic here would be useful!
