### ISSUE TITLE
Tracking issue for `time_checked_add` feature

### ISSUE THREAD

**Issue by sgeisler** [rust-lang/rust#55940]
This is a tracking issue for PR #55527 .

This feature adds a `checked_add(&self, &Duration) -> Option<SystemTime>` function to `std::time::SystemTime` and as a prerequisite also for all platform specific time structs. This also led to the refactoring of many `add_duration(&self, &Duration) -> SystemTime` functions to avoid redundancy (they now unwrap the result of `checked_add_duration`).

**Comment by Amanieu** [comment]
This should be added to `Instant` as well. We're seeing some need for this in `parking_lot` to handle wait timeouts.

**Comment by faern** [comment]
I pushed a PR for adding the same functionality to `Instant` under the same feature gate name. I hope this is fine. They seem extremely related (and share a lot of the implementation) and the feature name fits both.

**Comment by faern** [comment]
This has now been extended so the feature covers both `checked_add` and `checked_sub` on both `Instant` and `SystemTime`. Together with the fact that `Duration` already have these, it's now possible to handle all time types without risking panics on nightly (whenever the next nightly comes out).

**Comment by vi** [comment]
Why no `Instant::checked_duration_since`?

**Comment by vi** [comment]
Implemented `checked_duration_since`: https://github.com/rust-lang/rust/pull/58395

**Comment by faern** [comment]
@vi Could we not keep that as a separate feature? As to not slow this one down. No one reported they might have any need for `checked_duration_since` when we developed `checked_add` and `checked_sub`.

**Comment by vi** [comment]
OK, renaming the feature in the pull request.
