### ISSUE TITLE
why bother to declare extern crate your_xxx_crate  before use it

### ISSUE THREAD

**Issue by code-brewer** [rust-lang/rust#55946]
I have code a demo project as bellow, where code run well but i do not declare `extern crate greetings;`

I wonder why many rust examples online write `extern crate xxx;` clause  before to use xxx crate ?  
It seem unnecessary from my demo project. 

Can somebody explain when need to  declare  `extern crate xxx;` ?

> 
├── Cargo.lock
├── Cargo.toml
├── greetings
│   ├── Cargo.toml
│   └── src
│       └── lib.rs
├── src
│   └── main.rs

and having root Cargo.toml as:

`[dependencies]
greetings = { path = "greetings" }`

also, main.rs
`fn main() {
    greetings::hello();
}
`

then cargo run work as expect to print greeting message.

**Comment by StyMaar** [comment]
It used to be necessary, but it's not anymore in [the 2018 edition](https://rust-lang-nursery.github.io/edition-guide/rust-2018/module-system/path-clarity.html?highlight=exte#no-more-extern-crate).
