### ISSUE TITLE
A Rust Keystone Enclave SDK for Secure Enclaves

### ISSUE THREAD

**Issue by nathanawmk** [rust-lang/rust#55950]
I have a privacy-preserving requirement for blockchain-based/anchored identity and I believe a Rust-based SDK coupled with Open-source Secure Hardware Enclave such as the Keystone Enclave is the way forward.

Would like to know if this is a feasible idea? 

https://crypto.stackexchange.com/questions/64009/rust-keystone-enclave-sdk

https://keystone-enclave.org/

Nathan Aw

**Comment by jonas-schievink** [comment]
Discussions and questions like this are better suited for the users forum (https://users.rust-lang.org/) or IRC, not this issue tracker (which is for bugs and tracking RFCs only)

**Comment by nagisa** [comment]
Closing.
