### ISSUE TITLE
Tracking issue: edition manifest changes

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#55967]
- [ ] - rename rls and rustfmt to not include `-preview`
- [ ] - add profiles

cc @alexcrichton

**Comment by alexcrichton** [comment]
So nowadays I'm sort of terrified about doing anything with rustup, so I've attempted to run this through its paces to make sure that if we deploy this change whether it will actually work. Unfortunately it looks like it doesn't work?

I played around with our dev artifacts, and I was specifically applying a few changes for an updated manifest:

* All instances of `rls-preview` were replaced with `rls` (same for `rustfmt`
* This section was added to the end:

```toml
[rename.rls-preview]
to = 'rls'
# ... same for rustfmt 
```

If I installed a previous compiler with rls-preview then updating the compiler to this new manifest simply removed the rls-preview. Additionally `rustup component add rls-preview` would fail on the new manifest saying "component not found".

I think both of these aspects means there's bugs in rustup's handling of `[rename]` so we won't be able to do this by the time of the edition :(

**Comment by nrc** [comment]
> If I installed a previous compiler with rls-preview then updating the compiler to this new manifest simply removed the rls-preview

I think you would need to have rls rather than rls-preview available to download too (I'd expect an error about this, but perhaps it is swallowed because rustup thinks it is a temporarily missing component?)

> Additionally rustup component add rls-preview would fail on the new manifest saying "component not found".

I think this was never implemented

**Comment by alexcrichton** [comment]
In the new manifests though the `rls-preview` component didn't exist and only `rls` existed, but rustup didn't do the transition from `rls-preview` to `rls` automatically. I thought it would though?

**Comment by alexcrichton** [comment]
@nrc the behavior I was seeing was that the rls component was available and listed in the manifest as available, but rustup didn't install the renamed component it just uninstalled the previous one. I may have tested a wrong manifest though!
