### ISSUE TITLE
Update Rustfmt to 1.0

### ISSUE THREAD

**Issue by nrc** [rust-lang/rust#55965]
Tracking for the edition. Blocking issues on Rustfmt are at https://github.com/rust-lang-nursery/rustfmt/issues?q=is%3Aopen+is%3Aissue+milestone%3A%221.0+%28edition+rc1%29%22 though none of these will actually block, so I think I'll update on Monday and be done.

**Comment by alexcrichton** [comment]
@nrc does https://github.com/rust-lang/rust/pull/56111 close this issue?
