### ISSUE TITLE
max and min of treeset/treemap?

### ISSUE THREAD

**Issue by alok** [rust-lang/rust#55975]
Since trees are naturally based on ordered types, it would be nice to have a method to access the min and max values of a tree (or keys in the case of a treemap). This isn't high priority, but is something I noticed when trying to implement some data structures in Rust.

**Comment by scottmcm** [comment]
Since the iterators are sorted and double-ended, can't you just do `.iter().next()`/`.iter().next_back()`?

**Comment by kadiwa4** [comment]
The requested methods have been stabilized in 1.66.0 (`first*` and `last*` on `BTreeMap`/`BTreeSet`).
