### ISSUE TITLE
Tracking issue for weak_ptr_eq

### ISSUE THREAD

**Issue by Thomasdezeeuw** [rust-lang/rust#55981]
This is a tracking issue for `rc::Weak::ptr_eq` and `sync::Weak::ptr_eq`.

Feature gate: #![feature(weak_ptr_eq)].

Steps:

- [x] Implement the RFC (#55987).
- [ ] Stabilization PR.

---
Old issue:

`Rc` has a function called `ptr_eq` it compares if the `Rc` points to the value, not the values themselves. I would like to add the same function to `Weak`. I got an implementation but have two questions:

- Does this require an RFC? Or is this small enough to do without one.
- What to do with dangling pointer, e.g. created by `Weak::new()`. I would argue always return `false` if either one is dangling.

**Comment by jethrogb** [comment]
This is a small API introduction, it doesn't require an RFC. You can just file a PR.

**Comment by F001** [comment]
I have a question that why `Weak` didn't have `strong_count` and `weak_count` methods either.
I think these methods are also useful.

**Comment by Thomasdezeeuw** [comment]
@F001 I agree, you could create a PR and then someone from the libs team will comment (atleast that is what I did).

**Comment by vorner** [comment]
Hello. This looks potentially useful. How long does a feature this small need to sit around before it's considered for stabilization? (if I'm not missing something, there's no issue raised with this currently)

**Comment by Thomasdezeeuw** [comment]
If the team agrees I can make a stabilisation pr for 1.35/1.36.

**Comment by jonas-schievink** [comment]
Nominating to discuss stabilization. See PR #61797.

**Comment by alexcrichton** [comment]
I'm going to de-nominate this because stabilization happens outside of triage meetings and happens when a libs team member feels confident enough to propose stabilization.

**Comment by Thomasdezeeuw** [comment]
Anything I can do to advance the stabilisation?

**Comment by jonas-schievink** [comment]
@Thomasdezeeuw Apparently https://github.com/rust-lang/rust/pull/61797 is now nominated, so the libs team should discuss it soon

**Comment by Thomasdezeeuw** [comment]
@jonas-schievink I missed that, thanks.
