### ISSUE TITLE
`print!` and friends should flush on '\r' as well as '\n'

### ISSUE THREAD

**Issue by RandomInsano** [rust-lang/rust#56015]
I read some of #23818 and I'm unsure exactly what the standards are in C++, Java, Python and friends for this issue (if needed I can do research), but it seems unusual that output which includes a carriage return (ex: "Time to go: {} seconds\r") does not flush the output stream up to the point that the carriage return should be acted upon.

I'd expect this functionality to match what occurs when a new-line character is sent.

I'm runnin `rustc 1.32.0-nightly (6b9b97bd9 2018-11-15)` if that's relevant to discussion.

**Comment by Lucretiel** [comment]
What other languages do:

- Go: no built in line buffering
- Python: Flush on Newline or Carriage Return
- C++: By default, follows whatever your local stdio.h is doing. No C++-specific behavior.
- C: (http://www.cplusplus.com/reference/cstdio/setvbuf/) Only looks at newline, not carriage return.

With the caveat that this should be a change to `LineWriter`, as opposed to a change specific to the `print` macros, I'd be in favor of this (so long as it doesn't significantly impact performance).

**Comment by RandomInsano** [comment]
From setvbuf:

> For output buffers, data is output to the buffer until its maximum capacity is reached, then it is flushed

I’d need to double check how often my Rust app was outputting carriage-return text, but I want to believe it simply didn’t.

**Comment by Enselic** [comment]
Triage: Thank you for the suggestion. This would have very big impact on the Rust ecosystem, and by my estimation needs to go through an RFC, so I'll go ahead and close this issue now. See https://github.com/rust-lang/rfcs/blob/master/libs_changes.md for more info on when an RFC is needed (which I would say is clearly needed in this case).
