### ISSUE TITLE
build in function for median and mean

### ISSUE THREAD

**Issue by flip111** [rust-lang/rust#56025]
Would be nice to have a function on vector (iterator ?) to get the median and the mean. Possibly other related numerical functions such as standard deviation.

**Comment by jonas-schievink** [comment]
We already have `Iterator::{sum, product, min, max}`, so having more statistics-related consumers *might* make sense, although these could also start out in an external crate like [itertools](https://github.com/bluss/rust-itertools) or a crate focused on statistics.

**Comment by Dylan-DPC** [comment]
This is better suited for a separate crate so closing this
