### ISSUE TITLE
Confusing interaction between deref coercion and unknown type

### ISSUE THREAD

**Issue by euclio** [rust-lang/rust#56036]
I wrote something like the following code:

```
// fn function_that_doesnt_exist() -> String {
//    String::new()
// }

fn test(s: &str) {
    println!("{}", s);
}

fn test2(s: String) {
    println!("{}", s);
}

fn main() {
    let s = function_that_doesnt_exist();
    test(&s);
    test2(s);
}
```

https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=4be367b5c1d5a1d3d6eb20001c171825

Notice that the actual error is the missing `function_that_doesnt_exist`, but the compiler confusingly reports errors about `str` not having a size known at compile time, presumably because it infers the type of `s` as `str`. When I was writing this code, I missed the message about the missing function, so I was left scratching my head for a bit. It might be nice to silence such errors when the type of the variable is unknowable.

**Comment by estebank** [comment]
CC https://github.com/rust-lang/rust/issues/50333 https://github.com/rust-lang/rust/issues/56607

I believe that `s` should be marked as TyErr, which will cause the knock down errors to be elided.

**Comment by VirrageS** [comment]
It seems to be fixed

**Comment by euclio** [comment]
It's not, current output on nightly:

```
error[E0425]: cannot find function `function_that_doesnt_exist` in this scope
  --> src/main.rs:14:13
   |
14 |     let s = function_that_doesnt_exist();
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0308]: mismatched types
  --> src/main.rs:16:11
   |
16 |     test2(s);
   |           ^
   |           |
   |           expected struct `std::string::String`, found `str`
   |           help: try using a conversion method: `s.to_string()`
```

The "mismatched types" error should not be emitted.

**Comment by euclio** [comment]
Not fully, there's still a "mismatched types" error that ideally shouldn't be emitted:

```
error[E0425]: cannot find function `function_that_doesnt_exist` in this scope
  --> src/main.rs:14:13
   |
14 |     let s = function_that_doesnt_exist();
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0308]: mismatched types
  --> src/main.rs:16:11
   |
16 |     test2(s);
   |           ^
   |           |
   |           expected struct `std::string::String`, found `str`
   |           help: try using a conversion method: `s.to_string()`
```

**Comment by VirrageS** [comment]
Yup, right. Sorry! I was fixated on "not having a size known at compile time" that I didn't notice that we still produce an error for inferred type.
