### ISSUE TITLE
Poor diagnostic for `impl for T`

### ISSUE THREAD

**Issue by ZirconiumX** [rust-lang/rust#56031]
I accidentally typed `impl for T` instead of `impl T`, and the diagnostic ([playground](https://play.rust-lang.org/?version=beta&mode=debug&edition=2018&gist=037ebcc0fd36d424aea1989f99343c92)) wasn't very helpful:
```
  |
3 | impl for T {}
  |          ^ expected `<` here
```

This appears to be because of this syntax:
```rust
impl for<'a> T
```

However it makes no sense in this case. Perhaps better diagnostics would look something like this:
```
  |
3 | impl for T {}
  |     ^ expected type
```

**Comment by troiganto** [comment]
Maybe relatedly, this code compiles on stable 1.30.0:

```rust
trait Trait {}

impl for<'a> Trait {}

fn main() {}
```
([Playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=207448b1341c30a2f30e7f6b74c0abfa))
