### ISSUE TITLE
Spurious failure "failed to remove file ... Access is denied" in cargo test `profile_selection_check_all_targets*` on Windows

### ISSUE THREAD

**Issue by kennytm** [rust-lang/rust#56040]
Symptom: On `x86_64-msvc-cargo`, a cargo test with name like `profile_selection_check_all_targets*` failed to build due to error like

```
error: failed to remove file `C:\projects\rust\build\x86_64-pc-windows-msvc\stage2-tools\x86_64-pc-windows-msvc\cit\t988\foo\target\debug\libfoo.rmeta`
Caused by:
  Access is denied. (os error 5)
```

Previous instances:

* https://github.com/rust-lang/rust/pull/55672#issuecomment-439655316 (2018-11-17T23:28:49Z)
* https://github.com/rust-lang/rust/pull/56017#issuecomment-439684333 (2018-11-18T11:05:10Z)

Note: the cargo submodule was most recently updated by #55830 on 2018-11-10T15:03:11Z, but the 7 days of inactivity suggests #55830 may not be the cause.

**Comment by ehuss** [comment]
I think this will be fixed once #55999 lands. There is a change in how `.rmeta` files are handled (rust-lang/cargo#6292) that looks like it will clear it up.

I don't know why it is showing up all of a sudden. I was going to say it may be related to the switch to gce, but it also happened on cargo's ci (rust-lang/cargo#6319).

**Comment by kennytm** [comment]
Thanks. Raised the priority of #55999.

**Comment by ehuss** [comment]
Closing as this was resolved a long time ago.
