### ISSUE TITLE
Miscompilation since rustc 1.32.0-nightly (04fdb44f5 2018-11-03)

### ISSUE THREAD

**Issue by ordian** [rust-lang/rust#56069]
[parity-ethereum](https://github.com/paritytech/parity-ethereum) tests (in module ethcore-miner, sorry don't have time to minimize the test case) fail since nightly-2018-11-04, but pass on stable, beta and nightly-2018-11-03: 
```
❯ rustup toolchain install nightly-2018-11-03
nightly-2018-11-03-x86_64-unknown-linux-gnu installed - rustc 1.32.0-nightly (8b096314a 2018-11-02)
❯ cargo +nightly-2018-11-03 test -p ethcore-miner
test result: ok. 57 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
❯ rustup toolchain install nightly-2018-11-04 
nightly-2018-11-04-x86_64-unknown-linux-gnu installed - rustc 1.32.0-nightly (04fdb44f5 2018-11-03)
❯ cargo +nightly-2018-11-04 test -p ethcore-miner
test result: FAILED. 50 passed; 7 failed; 0 ignored; 0 measured; 0 filtered out
```

**Comment by nagisa** [comment]
Took a short look at this during the T-compiler meeting. It would be ideal to have a smaller reproduction case to work off as it does not immediately clear whether this is an actual bug in the compiler.

**Comment by nikic** [comment]
The big item in https://github.com/rust-lang/rust/compare/8b096314a...04fdb44f5 is the jemalloc removal. It would be good to check whether explicitly enabling jemalloc fixes the issue. (And by "fix" I mean "hide" -- this would indicate memory corruption.)

**Comment by ordian** [comment]
Ah, right, I guess this is related to `heapsize` crate we're using, which requires jemalloc to work properly if I'm not mistaken.
