### ISSUE TITLE
std::any's documentation should use dyn

### ISSUE THREAD

**Issue by 0xrgb** [rust-lang/rust#56062]
https://doc.rust-lang.org/std/any/index.html
https://doc.rust-lang.org/std/any/trait.Any.html

Newcomers who learn rust with rust book 2018 edition can be confused, because official book recommends `&dyn TraitObject` and does not say about `&TraitObject`.

**Comment by Centril** [comment]
@0xrgb I think a PR fixing this would be welcome. :)
