### ISSUE TITLE
beta regresssion: ICE: allocation missing in dead_alloc_map 

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#56082]
[Discovered by crater](https://crater-reports.s3.amazonaws.com/beta-1.31-2/beta-2018-11-13/reg/cage-0.2.6/log.txt), looks like:

```
$ git clone https://github.com/faradayio/cage
$ cd cage
$ cargo test --no-default-features # passes
$ cargo +beta test --no-default-features # ICEs
```

cc @rust-lang/compiler, cc @emk

**Comment by alexcrichton** [comment]
Also [`rusty_dashed`](https://crater-reports.s3.amazonaws.com/beta-1.31-2/beta-2018-11-13/reg/rusty_dashed-0.2.1/log.txt) (cc @TLmaK0)

**Comment by Mark-Simulacrum** [comment]
cc @oli-obk @RalfJung @eddyb -- I think this may have been fixed on master but perhaps not backported? I seem to recall something similar -- perhaps https://github.com/rust-lang/rust/issues/55287.

**Comment by pietroalbini** [comment]
This is fixed by https://github.com/rust-lang/rust/pull/55385, which is in the rollup.

**Comment by alexcrichton** [comment]
Ok cool, thanks @pietroalbini!
