### ISSUE TITLE
beta-regression: type_level_examples "the name `_` is defined multiple times"

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#56087]
[Discovered by crater](https://crater-reports.s3.amazonaws.com/beta-1.31-2/beta-2018-11-13/reg/type_level_examples-0.0.22/log.txt):

```
$ git clone https://github.com/rodrimati1992/type_level
$ cd type_level/type_level_examples
$ git reset --hard fc536e556daba9d818767f4df1ba323abb0948ad
$ cargo +beta test
```

cc @rust-lang/compiler 

Note that this regression doesn't affect the master branch, so not cc'ing the author yet

**Comment by Mark-Simulacrum** [comment]
I believe this is a duplicate but IIRC the previous one was closed so perhaps it re-regressed.

**Comment by alexcrichton** [comment]
Ah yes indeed, duplicate of https://github.com/rust-lang/rust/issues/55811
