### ISSUE TITLE
beta regression: postgis "the trait bound ... is not satisfied"

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#56084]
Discovered [by crater](https://crater-reports.s3.amazonaws.com/beta-1.31-2/beta-2018-11-13/reg/postgis-0.6.0/log.txt):

```
$ git clone https://github.com/andelf/rust-postgis
$ cd rust-postgis
$ cargo +beta test
```

cc @rust-lang/compiler, cc @andelf, @pka

**Comment by Mark-Simulacrum** [comment]
Should be fixed by https://github.com/rust-lang/rust/pull/56003, and this issue is a duplicate of https://github.com/rust-lang/rust/issues/54467; closing.
