### ISSUE TITLE
rust nightly compiler bug

### ISSUE THREAD

**Issue by karasjoh000** [rust-lang/rust#56121]
Created some tests to run against a rocket backend and got this: 
![rust_bug](https://user-images.githubusercontent.com/21280439/48826553-7f481680-ed1f-11e8-9bc0-629fabd8a641.jpeg)

It says to report, so I thought I should report it...

**Comment by hellow554** [comment]
Can you please rerun the command and prepend `RUST_BACKTRACE=1`, e.g. `RUST_BACKTRACE=1 cargo build` and then post that as **text**? Thank you very much!

**Comment by karasjoh000** [comment]
https://github.com/karasjoh000/forecast.git project will appear here soon once uploaded, sure I will run that

**Comment by karasjoh000** [comment]
`[ Wed Nov 21 | 12:08 AM | cs453_finalproj_backend ]: RUST_BACKTRACE=1 cargo test
   Compiling hyper v0.12.14                                                                                                                                                                                                        
   Compiling rocket v0.3.17                                                                                                                                                                                                        
thread 'main' panicked at 'librustc/hir/map/hir_id_validator.rs:31:                                                                                                                                                                
HirIdValidator: The recorded owner of path segment super (id=37140) is ::server[0]::conn[0]::{{?}}[34] instead of ::server[0]::conn[0]::{{?}}[34]::{{?}}[0]                                                                        
HirIdValidator: Same HirId ::server[0]::conn[0]::{{?}}[34]::{{?}}[0]/2 assigned for nodes path segment super (id=37140) and path segment spawn_all (id=90258)', librustc/util/bug.rs:47:26                                         
stack backtrace:                                                                                                                                                                                                                   
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace                                                                                                                                                                    
   1: std::sys_common::backtrace::_print                                                                                                                                                                                           
   2: std::panicking::default_hook::{{closure}}                                                                                                                                                                                    
   3: std::panicking::default_hook                                                                                                                                                                                                 
   4: rustc::util::common::panic_hook                                                                                                                                                                                              
   5: std::panicking::rust_panic_with_hook                                                                                                                                                                                         
   6: std::panicking::begin_panic                                                                                                                                                                                                  
   7: rustc::util::bug::opt_span_bug_fmt::{{closure}}                                                                                                                                                                              
   8: rustc::ty::context::tls::with_opt::{{closure}}                                                                                                                                                                               
   9: rustc::ty::context::tls::with_context_opt                                                                                                                                                                                    
  10: rustc::ty::context::tls::with_opt                                                                                                                                                                                            
  11: rustc::util::bug::opt_span_bug_fmt                                                                                                                                                                                           
  12: rustc::util::bug::bug_fmt                                                                                                                                                                                                    
  13: rustc::hir::map::hir_id_validator::check_crate                                                                                                                                                                               
  14: rustc::hir::map::map_crate                                                                                                                                                                                                   
  15: rustc::util::common::time                                                                                                                                                                                                    
  16: rustc_driver::driver::compile_input                                                                                                                                                                                          
  17: rustc_driver::run_compiler_with_pool                                                                                                                                                                                         
  18: <scoped_tls::ScopedKey<T>>::set                                                                                                                                                                                              
  19: rustc_driver::run_compiler                                                                                                                                                                                                   
  20: <scoped_tls::ScopedKey<T>>::set                                                                                                                                                                                              
  21: syntax::with_globals                                                                                                                                                                                                         
  22: __rust_maybe_catch_panic                                                                                                                                                                                                     
  23: rustc_driver::run                                                                                                                                                                                                            
  24: rustc_driver::main                                                                                                                                                                                                           
  25: std::rt::lang_start::{{closure}}                                                                                                                                                                                             
  26: std::panicking::try::do_call                                                                                                                                                                                                 
  27: __rust_maybe_catch_panic                                                                                                                                                                                                     
  28: std::rt::lang_start_internal                                                                                                                                                                                                 
  29: main                                                                                                                                                                                                                         
query stack during panic:                                                                                                                                                                                                          
end of query stack   `

**Comment by sinkuu** [comment]
This seems like #55376. Can you update to a recent nightly?

**Comment by karasjoh000** [comment]
cargo 1.31.0-nightly (2d0863f65 2018-10-20)

**Comment by karasjoh000** [comment]
`rustup update && cargo update` <-- run this?

**Comment by karasjoh000** [comment]
okay looks like it is working now. Running on cargo 1.32.0-nightly (b3d0b2e54 2018-11-15)
