### ISSUE TITLE
Duplicate definition of type for rustc::mir::Constant

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rust#56137]
[`rustc::mir::Constant`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc/mir/struct.Constant.html) has a field `ty`, but its field `literal` contains a `Const` which itself already contains a `Ty`.

**Comment by oli-obk** [comment]
These types aren't always equal. e.g. the lifetimes often differ, and I think around impl trait some inconsistencies can happen, too. we should probably document this much better and/or figure out whether we need the duplication

**Comment by eddyb** [comment]
Looks like #61041 is blocked on fixing this.

**Comment by RalfJung** [comment]
This is interesting, maybe:
```rust
impl<'tcx> TypeFoldable<'tcx> for Constant<'tcx> {
    fn super_fold_with<F: TypeFolder<'tcx>>(&self, folder: &mut F) -> Self {
        Constant {
            span: self.span.clone(),
            ty: self.ty.fold_with(folder),
            user_ty: self.user_ty.fold_with(folder),
            literal: self.literal.fold_with(folder),
        }
    }
    fn super_visit_with<V: TypeVisitor<'tcx>>(&self, visitor: &mut V) -> bool {
        self.ty.visit_with(visitor) || self.literal.visit_with(visitor)
    }
}
```
Notice how `super_visit_with` skips `user_ty`, but `super_fold_with` does not. OTOH, the mismatch you are seeing is between `ty` and `literal`, and they both look to be treated the same.

**Comment by RalfJung** [comment]
OTOH, the implementation for `Const` also does some weird stuff:
```rust
impl<'tcx> TypeFoldable<'tcx> for &'tcx ty::Const<'tcx> {
    fn super_fold_with<F: TypeFolder<'tcx>>(&self, folder: &mut F) -> Self {
        let ty = self.ty.fold_with(folder);
        let val = self.val.fold_with(folder);
        folder.tcx().mk_const(ty::Const {
            ty,
            val
        })
    }

    fn fold_with<F: TypeFolder<'tcx>>(&self, folder: &mut F) -> Self {
        folder.fold_const(*self)
    }

    fn super_visit_with<V: TypeVisitor<'tcx>>(&self, visitor: &mut V) -> bool {
        self.ty.visit_with(visitor) || self.val.visit_with(visitor)
    }

    fn visit_with<V: TypeVisitor<'tcx>>(&self, visitor: &mut V) -> bool {
        visitor.visit_const(self)
    }
}
```
In particular it implements `visit_with` and `fold_with`, which does not usually seem to be done? Does it do that correctly (not calling the `super_*` methods, in particular)?

**Comment by eddyb** [comment]
@RalfJung All of that is fine. `ty::Const` is "unusual" because it's one of the 3 "entities" (`Ty` and `ty::Region` have the same treatment).

I'm already fixing this. MIR construction *is just wrong* and likely has been since forever.
MIRI kept papering over this issue by not using the `ty` field of `ty::Const`.

**Comment by eddyb** [comment]
Huh, looks like the bug is pretty recent: https://github.com/rust-lang/rust/commit/5cd28066214a4a255bac6655c20bf05cb95730fd#diff-c599d3d6879ad974960a24abd4e4bdb6R953
It was introduced in #59178, *after* this issue - had we removed the duplication earlier, the bug would've been prevented, heh.
