### ISSUE TITLE
Hashmap raw_entry crash

### ISSUE THREAD

**Issue by sgodwincs** [rust-lang/rust#56158]
While trying out the experimental hashmap raw entry API, I found that the following code crashes

```rust
#![feature(hash_raw_entry)]

use std::collections::HashMap;

fn main() {
    let map: HashMap<&str, &str> = HashMap::new();
    map.raw_entry().search_bucket(0, |_| false);
}
```

While the corresponding version using `raw_entry_mut` does not. I'd expect it to return `None` in this case since the map doesn't even have any items.

rustc 1.32.0-nightly (f1e2fa8f0 2018-11-20)

**Comment by steveklabnik** [comment]
I just double checked, and this is indeed a segfault, not a panic.

**Comment by sgodwincs** [comment]
This only seems to happen when the capacity of the hashmap is 0. Using `HashMap::with_capacity(1)` avoids the problem.

**Comment by sfackler** [comment]
cc #56167

**Comment by Amanieu** [comment]
cc @Gankro @fintelia

**Comment by Amanieu** [comment]
`RawEntry` is calling `search_hashed_nonempty` on an empty table. `RawEntryMut` does the same thing, but calls `reserve(1)` first so it's fine.

**Comment by kpp** [comment]
There is no method `::search_bucket` anymore.

**Comment by Amanieu** [comment]
The crash doesn't happen any more since the switch to hashbrown.
