### ISSUE TITLE
Link to procedural macros doc is broken

### ISSUE THREAD

**Issue by glandium** [rust-lang/rust#56179]
The release notes for 1.30 have a link to the "new chapter available" for procedural macros:
https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1300-2018-10-25

That link points to https://doc.rust-lang.org/nightly/book/2018-edition/ch19-06-macros.html, which currently says

```
The 2018 edition of the book is no longer distributed with Rust's documentation.

If you came here via a link or web search, you may want to check out the current version of the book instead.

If you have an internet connection, you can find a copy distributed with Rust 1.30.
```

None of the links on that page send to the right place.

**Comment by hellow554** [comment]
Not only that chapter, but all of them will show the text above.

**Comment by steveklabnik** [comment]
Yes, this is changing in 1.31. Release notes are pretty immutable, IMHO, but I’ll leave it up to the release team if they want to fix it or not.

**Comment by Enselic** [comment]
Triage: My understanding is that the link was valid when the release was made, but has simply become outdated by now. I don't think anyone reads 1.30 release notes any longer, so let's close this as won't fix.
