### ISSUE TITLE
Rustdoc issues with macro reexport

### ISSUE THREAD

**Issue by weiznich** [rust-lang/rust#56173]
I've toying around a bit with how and where to document things. For this I've tried to reexport things at certain locations. To let the documentation appear on the reexported location I've been using `#[doc(inline)]`. This works fine for normal items, but fails for macros generated by macro rules and for custom derives. They are continued to be rendered just as reexports.

Reproducing example:
```rust
/// item
pub struct SomeItem {
    i: i32
}

/// some macro
#[macro_export]
macro_rules! foo {
    ($i: ident) => {}
}

/// foo
pub mod bar {
    #[doc(inline)]
    pub use super::SomeItem;

    #[doc(inline)]
    pub use foo;
}

````

Resulting docs for `bar`:
![docs](https://user-images.githubusercontent.com/1674512/48922990-7e8bbd80-eea2-11e8-9b25-50a99fdf23b8.png)

I would expect that the documentation appears inline similar like the documentation of `SomeItem`.

Rustdoc version:
```
rustdoc --version       
rustdoc 1.32.0-nightly (0b9f19dff 2018-11-21)
```

**Comment by weiznich** [comment]
@bkchr See the PR I've opened. That does fix the problem for me. (It basically worked, but missed some pieces to do the actual inlining in case of macros.)

**Comment by bkchr** [comment]
@weiznich nice :)
