### ISSUE TITLE
Windows: OsStr need not be valid UTF-8

### ISSUE THREAD

**Issue by DemiMarie** [rust-lang/rust#56171]
On Windows, filenames (and many other strings) are stored in UCS-2, not UTF-8.  This corresponds to [WTF-8], not UTF-8.  Furthermore, the NT kernel uses length-specified strings via the [`UNICODE_STRING`] struct, and uses only `\` as the path separator.  Therefore, many APIs (such as [`NtCreateFile`] and [`NtCreateKey`]) actually allow NUL characters in names.  While the NTFS driver does not allow NUL to be part of a filename, registry keys can have NUL characters in there names.

Therefore, I propose that `OsStr` on Windows be able to be created from any valid [WTF-8], and that an API be provided that allows them to be created with NUL characters.

[WTF-8]: <//simonsapin.github.io/wtf-8/>
[`NtCreateFile`]: <//docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/ntifs/nf-ntifs-ntcreatefile>
[`NtCreateKey`]: <//docs.microsoft.com/en-us/windows-hardware/drivers/ddi/content/wdm/nf-wdm-zwcreatekey>
[`UNICODE_STRING`]: <//docs.microsoft.com/en-us/windows/desktop/api/subauth/ns-subauth-_unicode_string>

Also see https://github.com/rust-lang/rust/issues/53261#issuecomment-441102501

**Comment by retep998** [comment]
`OsStr` literally already is this. It stores WTF-8 instead of UTF-8 and is capable of holding NUL characters just fine.

**Comment by estebank** [comment]
Leaving open as under the purview of @rust-lang/docs, like #53261.

**Comment by Mark-Simulacrum** [comment]
Closing since this seems to be satisfied by the existing APIs (per above comments and reading the API docs today). #53261 touches on the more specific issue of `std::ffi` docs being misleading about the underlying representation of `OsString` on Windows, but that's an orthogonal and separate concern.
