### ISSUE TITLE
Mismatched types should suggest From/Into conversions

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/rust#56181]
This program ([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=dc8acdb722b6c34d6ec5cf5ba89d9d24)):

```rust
use std::{process::Stdio, fs::File};
pub fn foo(_x: Stdio) {}
pub fn bar(x: File) { foo(x) }
```

errors with

```
error[E0308]: mismatched types
 --> src/lib.rs:3:27
  |
3 | pub fn bar(x: File) { foo(x) }
  |                           ^ expected struct `std::process::Stdio`, found struct `std::fs::File`
  |
  = note: expected type `std::process::Stdio`
             found type `std::fs::File`

error: aborting due to previous error
```

but there is an impl of `From<File>` for `Stdio`, such that this code ([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=97436a7e5d3a14700dd48e92b9733acf)): 

```rust
use std::{process::Stdio, fs::File};
pub fn foo(_x: Stdio) {}
pub fn bar(x: File) { foo(x.into()) }
```

compiles and works as expected.

The error message should have a note stating that there is a conversion available, and a fix suggestion. That would be a huge boon for API discoverability. If there are multiple APIs that take `File` and return `Stdio`, the error message should suggest some of them with some sort of prioritization (`From`/`TryFrom` traits, `::from`/`::new` methods, `.as_...` methods, etc.)

**Comment by estebank** [comment]
CC https://github.com/rust-lang/rust/issues/37384, https://github.com/rust-lang/rust/issues/42499

**Comment by kadiwa4** [comment]
Fixed (nightly 2023-01-27):
```
error[E0308]: mismatched types
 --> src/lib.rs:3:27
  |
3 | pub fn bar(x: File) { foo(x) }
  |                       --- ^ expected struct `Stdio`, found struct `File`
  |                       |
  |                       arguments to this function are incorrect
  |
note: function defined here
 --> src/lib.rs:2:8
  |
2 | pub fn foo(_x: Stdio) {}
  |        ^^^ ---------
help: call `Into::into` on this expression to convert `File` into `Stdio`
  |
3 | pub fn bar(x: File) { foo(x.into()) }
  |                            +++++++

For more information about this error, try `rustc --explain E0308`.
error: could not compile `playground` due to previous error
```
