### ISSUE TITLE
Allow passing of argumets to the linker

### ISSUE THREAD

**Issue by derpmarine168** [rust-lang/rust#56218]
It would be nice to be able to pass specific argumets to the linker. This would mean people could avoid hacks like [this](https://stackoverflow.com/a/45810714/9761034). This would be especialy useful for passing particular flags to Emscripten ([like optimisation flags](https://kripken.github.io/emscripten-site/docs/tools_reference/emcc.html#emcc-compiler-optimization-options)), and other custom linkers.

**Comment by sfackler** [comment]
`rustc -C link-arg=foo`

**Comment by derpmarine168** [comment]
In cargo?

**Comment by derpmarine168** [comment]
oh, I realise that this should probably be a cargo issue.

**Comment by nagisa** [comment]
There are multiple ways to make Cargo pass arbitrary arguments to rustc, including the `-Clink-arg=...`:

* `cargo rustc`;
* `RUSTFLAGS` environment variable;
* `.cargo/config` file (allows to specify `rustflags`)…

---

Since this is not an issue in rustc, closing.
