### ISSUE TITLE
Wishlist: add `Contains` trait

### ISSUE THREAD

**Issue by alok** [rust-lang/rust#56226]
This is inspired by Python's `__contains__`, which lets you write things like `if x in xs` very readably. The `in` keyword appears to only be used in the for-loop syntax (also like Python), so there isn't any ambiguity in using it.

Not high priority, but a (seemingly harmless) bit of syntactic sugar.

**Comment by steveklabnik** [comment]
We don’t generally track features like this with issues; small features can just have a PR, large features need to go through the RFC process.

This would be a pretty big change, and has been suggested before and proven controversial. You should write up an RFC; it never got to that stage previously.

Thank you!
