### ISSUE TITLE
Building libstd without any features does not work

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#56228]
Building libstd without any features set leads to
```
error[E0463]: can't find crate for `panic_unwind`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: Could not compile `std`.

To learn more, run the command again with --verbose.
error: `"cargo" "build" "--release" "--manifest-path" "/tmp/xargo.qBKqt1BCzPhj/Cargo.toml" "--target" "x86_64-unknown-linux-gnu" "-p" "std"` failed with exit code: Some(101)
```
Looks like we try to use that crate even if the feature is not set (and hence the dependency not enabled in Cargo.toml)?

Cc @alexcrichton

**Comment by alexcrichton** [comment]
This looks like it's likely related to compiling with panic=unwind, if panic=abort is used does it fix the error?

**Comment by RalfJung** [comment]
That gets me a bit further, but libtest still fails to build:
```
error[E0463]: can't find crate for `panic_unwind`
  --> /home/r/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libtest/lib.rs:57:1
   |
57 | extern crate panic_unwind;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error
```
Seems libtest does not support panic=abort?

**Comment by alexcrichton** [comment]
Ah yeah that's true, libtest currently has no way to work with panic abort

**Comment by jonas-schievink** [comment]
Should this be closed? It seems unlikely to me that libtest will get support for panic=abort, and libstd appears to build fine now (which this issue is about).

**Comment by RalfJung** [comment]
@jonas-schievink so you tested libstd with no features and no compiler flags?

**Comment by jonas-schievink** [comment]
No, but that failure looked expected to me. Perhaps I misread though.

**Comment by RalfJung** [comment]
I see. So that would be considering panic_unwind / panic_abort features mandatory in the sense that they cannot both be left off.

I could live with that, but it should be better documented in the `Cargo.toml` then.

**Comment by walksanatora** [comment]
so wait how do you fix this

**Comment by jyn514** [comment]
`cargo build -Zbuild-std-features='' -Zbuild-std` on a hello-world project works for me, so I'm going to assume this has been fixed (and indeed I see that the `panic_abort` crate is now mandatory).

@walksanatora I'm not sure how to fix your exact problem, but it doesn't look related to the original issue. The issue tracker is not a support forum. For future questions please ask in one of these places:

https://discord.gg/rust-lang/
https://discord.gg/rust-lang-community/
https://users.rust-lang.org/
https://rust-lang.zulipchat.com/
