### ISSUE TITLE
RefCell<String>.as_ptr().read() causes a SegFault when called 205 times or more

### ISSUE THREAD

**Issue by limaconoob** [rust-lang/rust#56227]
I try to read the content of a RefCell<String> multiple times, and it causes a SegFault everytime at the 205th attempt.

https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=26b681c2421550745aaaa82913c43e18

Note : When I change the `RefCell<String>` to a `RefCell<u32>`, everything works perfectly no matter how many times I try to read the RefCell.

**Comment by sfackler** [comment]
Every iteration through that loop, your (unsafe) call to `ptr::read` causes the string to be freed. After double-freeing the string 204 times, the allocator is apparently sufficiently corrupted to segfualt.

**Comment by limaconoob** [comment]
Thank you for your answer. I tried to use .clone() to avoid that behavior, but it doesn't work aswell.
However, someone told me to replace the .as_ptr().read() method by a .as_ref().unwrap(), and this fixed my problem so far, by the fact that this returns an Option<&String> (aka a reference on it)
