### ISSUE TITLE
Rustdoc: Allow implicit `fn main() -> Result<_, _>`

### ISSUE THREAD

**Issue by llogiq** [rust-lang/rust#56260]
Rustdoc now allows us to use `?` in our tests. Unfortunately, this requires writing the `fn main() -> ..` manually, which really shouldn't be needed IMHO.

So we now have to write:

```rust
/// ```rust
///# fn main() -> Result<(), ()> {
/// let foo = Ok(1usize);
/// assert!(foo? > 0);
///# }
/// ```
```

where it should suffice to write:

```rust
/// ```rust
/// let foo = Ok(1usize);
/// assert!(foo? > 0);
/// ```
```

Doing so will make the tests shorter and hopefully lead to more `?` and less `unwrap` in tests.

**Comment by Centril** [comment]
Feels like a no-brainer to me; would be great. :)

**Comment by scottmcm** [comment]
I think there are two things we want before doing this:
- `try fn`, so that it can _always_ be `try fn main() -> TBD {`, and existing code will just work.
- The `Try` re-do, so we can make a type that accepts any error type (since it'll just error anyway).

**Comment by sinkuu** [comment]
`fn main() -> impl std::process::Termination`?

**Comment by llogiq** [comment]
Yes, that's what I'm thinking, and I'm setting up a PR for that. However, it's still unstable.

**Comment by QuietMisdreavus** [comment]
I talked about this back in March on the "`?` in main" tracking issue: https://github.com/rust-lang/rust/issues/43301#issuecomment-374990514

That sample you gave isn't even valid as-is, unless `()` coercing to `Ok(())` is also in the pipeline?

**Comment by llogiq** [comment]
That'll be next, hopefully. I wonder if it suffices to `impl From<T> for <Result<T, !>>` or if we need to keep a generic error type (which might mess with type inference). In any event, having both the aforementioned and `impl From<Result<T, !>> for T` should be a no-brainer, right?
