### ISSUE TITLE
rustfmt and rls are only available on x86, x86_64, aarch64, and arm+neon

### ISSUE THREAD

**Issue by cuviper** [rust-lang/rust#56261]
Use of `rustfmt` -> `bytecount` -> `simd` only works on x86, x86_64, aarch64, and arm+neon, so all other arches are broken.  See also https://github.com/rust-lang/rustfmt/issues/3216.

I'm marking this as a regression since `rustfmt` and `rls` worked fine on all arches on 1.30 stable.  I'm aware the rest are not Tier-1 targets though.

I believe a simple workaround for distro packagers like myself would be to just patch out the enablement of `bytecount`'s `simd-accel` feature in `rustfmt/Cargo.toml`.

**Comment by alexcrichton** [comment]
@nrc this seems pretty bad, maybe the dependency can be removed for now?

**Comment by alexcrichton** [comment]
Er nvmd, looks like it's fixed upstream, I think bother the beta and master branches now need an update?

**Comment by alexcrichton** [comment]
Retagging as a nightly regression now that the rollup has landed, @cuviper can you confirm tomorrow that beta has all the available rustfmts? It looks like `rustfmt-beta-arm-unknown-linux-gnueabi.tar.xz` got uploaded at least!

**Comment by cuviper** [comment]
Well, I checked, but it seems beta is still at `rustc 1.31.0-beta.19 (42053f9f0 2018-11-26)`.

**Comment by cuviper** [comment]
OK, `1.31.0-beta.20 (8940af3ce 2018-11-30)` looks good, thanks!

**Comment by alexcrichton** [comment]
Perfect, thanks!
