### ISSUE TITLE
rbt vcf-to-txt panics with when encountering multi-allelic variants

### ISSUE THREAD

**Issue by warthmann** [rust-lang/rust#56272]
Hello,

I ran
bcftools view --apply-filters PASS --output-type u annotated/all.vcf.gz | rbt vcf-to-txt -g --fmt DP AD --info ANN

and encountered a panic: 

thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', /checkout/src/libcore/slice/mod.rs:2336:10
note: Run with `RUST_BACKTRACE=1` for a backtrace.

it seems to happen at places of multi-allelic SNPs, like these

Chr01   54167   .       GA      G,*     1215.97 PASS  
Chr01   54176   .       A       T,C     1218.68 PASS  

I am working around by adding "--max-alleles 2" to the bcftools view call.
However, it would be nice if 'rbt vcf-to-txt' could deal with multi allelic SNPs, or at least exit more gracefully/informatively. 

thanks a lot for your attention
best
Norman

**Comment by jonas-schievink** [comment]
(closing since this does not look like a bug in Rust - leave a comment if you disagree and I'll reopen)
