### ISSUE TITLE
compiletest: `//~ ERROR` should be interpreted as applying to all revisions

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#56279]
Spawned off of https://github.com/rust-lang/rust/pull/56244/files#r236635792

Right now, you have to write explicit `//[rev]~ ERROR` annotations for *each* revision `rev` in a given test. This is true even when all of the revisions can use *identical* annotations.

We should change `compiletest` so that occurrences of `//~ ERROR` are still parsed and are treated as synonymous for a copy of that same annotation for every revision in the `// revisions:` set.

**Comment by oli-obk** [comment]
In some situations it would also have been nice to be able to specify a set of revisions like `//[revA revB]~ ERROR`.

**Comment by tmiasko** [comment]
Since #66524 `//~ ERROR` applies to all revisions, and `//[A,B]~ ERROR` to revisions `A` and `B`.
