### ISSUE TITLE
Tracking issue for std::ptr::hash

### ISSUE THREAD

**Issue by dwijnand** [rust-lang/rust#56286]
Implemented in #56250 as `#[unstable(feature = "ptr_hash")]`.

**Comment by dtolnay** [comment]
Updated from:

```rust
fn hash<T, S: Hasher>(hashee: *const T, into: &mut S)
```

to:

```rust
fn hash<T: ?Sized, S: Hasher>(hashee: *const T, into: &mut S)
           ^^^^^^
```

in #56751. Thanks @mbrubeck.

**Comment by SimonSapin** [comment]
Seems straightforward enough to me.

@rfcbot fcp merge

**Comment by matklad** [comment]
Question:

We have `Arc::ptr_eq`, should we have `Arc::ptr_hash` as well?

**Comment by SimonSapin** [comment]
We could, but that’s going quickly into diminishing returns IMO. You can always use something like `std::ptr::hash::<T, _>(&*arc, s)`
