### ISSUE TITLE
beta regression: gltf-viewer ambiguous imports

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#56316]
[Discovered by crater](https://crater-reports.s3.amazonaws.com/beta-1.31-4/beta-2018-11-24/reg/gltf-viewer-0.4.0/log.txt):

```
$ git clone https://github.com/bwasty/gltf-viewer
$ cd gltf-viewer
$ cargo +beta build
```

cc @petrochenkov

**Comment by petrochenkov** [comment]
This is an expected bug-fix regression, it was previously found by the crater run in https://github.com/rust-lang/rust/pull/55884 as well.
It has a dedicated test - https://github.com/rust-lang/rust/blob/master/src/test/ui/imports/issue-55884-1.rs.

**Comment by alexcrichton** [comment]
👍 

cc @bwasty just to make sure you're aware!
