### ISSUE TITLE
Allow detecting panic strategy from a cfg

### ISSUE THREAD

**Issue by thomcc** [rust-lang/rust#56318]
It would be nice to be able to say something like:

```rust
#[cfg(not(panic = "abort"))]
fn do_thing() {
    // Do thing with unwind safety in mind, but possibly more slowly.
}

#[cfg(panic = "abort")]
fn do_thing() {
    // Faster implementation that doesn't need to account for panic safety.
}
```

Failing that, a runtime check to detect the panic would also be acceptable for many cases, although a compile-time approach would be preferable for obvious reasons.

Apologies if there's already a way to do this that I couldn't find. Also apologies if this requires an RFC.

**Comment by dlight** [comment]
https://github.com/rust-lang/rust/pull/74754 will fix this (on nightly) when merged.

**Comment by thomcc** [comment]
It got merged!

**Comment by boozook** [comment]
Could be awesome to get same for `build-std-features` ❤️‍🔥

```rust
#[cfg(build_std_features = "panic_immediate_abort")]
```
