### ISSUE TITLE
beta regression: svgdom struct is private

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#56317]
[Discovered by crater](https://crater-reports.s3.amazonaws.com/beta-1.31-4/beta-2018-11-24/reg/resvg-0.3.0/log.txt):

```
$ git clone https://github.com/RazrFalcon/resvg
$ cd resvg
$ git reset --hard v0.3.0
$ cargo +beta build
```

cc @petrochenkov

**Comment by petrochenkov** [comment]
This is an expected bug-fix regression, it was previously found by the crater run in https://github.com/rust-lang/rust/pull/55884 as well.
It has a dedicated test - https://github.com/rust-lang/rust/blob/master/src/test/ui/imports/issue-55884-2.rs.

**Comment by alexcrichton** [comment]
👍 

cc @RazrFalcon, just to make sure you're aware!

**Comment by RazrFalcon** [comment]
Thanks. Not sure how this should be fixed. It actually works in master, but not in v0.13. And I wan't to make v0.13.1.
