### ISSUE TITLE
edition compatibility lints: Warning about `dyn` in a macro incorrectly

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#56327]
This code:

```rust
#![warn(rust_2018_compatibility)]

macro_rules! foo {
    () => {
        fn _foo() {
            let _x: Box<dyn Drop>;
        }
    }
}

foo!();
```

[when compiled](https://play.rust-lang.org/?version=beta&mode=debug&edition=2015&gist=675981bcb1aa7b8745ab8367da524a05) under 2015 edition yields:

```
warning: `dyn` is a keyword in the 2018 edition
 --> src/lib.rs:6:25
  |
6 |             let _x: Box<dyn Drop>;
  |                         ^^^ help: you can use a raw identifier to stay compatible: `r#dyn`
  |
note: lint level defined here
 --> src/lib.rs:1:9
  |
1 | #![warn(rust_2018_compatibility)]
  |         ^^^^^^^^^^^^^^^^^^^^^^^
  = note: #[warn(keyword_idents)] implied by #[warn(rust_2018_compatibility)]
  = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in the 2018 edition!
  = note: for more information, see issue #49716 <https://github.com/rust-lang/rust/issues/49716>
```

but the warning and suggestion are incorrect!

First reported at https://github.com/rust-lang/cargo/issues/6359

This also applies to [macro invocations](https://play.rust-lang.org/?version=beta&mode=debug&edition=2015&gist=576740ac5638033d4eb302095c45eca6)

**Comment by pnkfelix** [comment]
(I nominated this for discussion at a future T-compiler meeting because I want us to figure out what our intent was for this bug, and I also want to try to develop a firmer policy for how such cases should be addressed going forward.

**Comment by pnkfelix** [comment]
discussed at T-compiler meeting.  calling this P-medium. ( @nikomatsakis and I are not currently sure what our intentions are for `dyn` here.)

@pnkfelix is going to assign this to themself to see if there's any simple resolution focused on special casing behavior for `dyn` in macro bodies.
