### ISSUE TITLE
rustdoc: duplicated lifetimes

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#56331]
Example: https://doc.rust-lang.org/nightly/std/slice/struct.Iter.html
```
pub struct Iter<'a, T> where
    T: 'a + 'a,  { /* fields omitted */ }
```

Behavior is observable on stable and nightly.

Clearly `'a + 'a` can be shortened to just `'a`.

**Comment by QuietMisdreavus** [comment]
This is a problem with how the struct is represented when re-exporting from a different crate. For example, [this is how it looks in `libcore`](https://doc.rust-lang.org/nightly/core/slice/struct.Iter.html):

```
pub struct Iter<'a, T: 'a> { /* fields omitted */ }
```

The `T: 'a` gets converted into a where clause in the re-export, but i'm not sure what introduces the duplicate lifetime bound.

**Comment by BartMassey** [comment]
Current documentation still has evidence of this bug: see e.g. `Ref` in https://doc.rust-lang.org/std/cell/struct.Ref.html
