### ISSUE TITLE
Q: how popular is Windows 7 among Rust installs

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#56344]
The T-compiler team recently had a bug that was Windows 7 specific.

We internally guessed since Windows 7 is EOL'ed, it is not Tier 1.

But then further discussion led us to wonder whether it is nonetheless a popular target for Rust installs.

So, this issue poses the Question: How popular is Windows 7 for our audience? What platform tier is it?

**Comment by Zoxc** [comment]
Windows 7 EOL is Jan. 14, 2020, just for reference

**Comment by retep998** [comment]
Why don't we ask these sort of questions in the Rust survey? Or perhaps gather some basic statistics via rustup itself?

**Comment by steveklabnik** [comment]
Questions like this are for internals.rust-lang.org; we try to keep the issue tracker for actionable bugs. Please open a discussion over there, thank you!

**Comment by WAFFO** [comment]
Posted a quick strawpoll on r/rust for anyone curious.

It's about as expected.

https://old.reddit.com/r/rust/comments/a1jskw/what_os_do_you_build_rust_on_os_census/
