### ISSUE TITLE
E0005; should all constructors be listed?

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#56379]
See https://github.com/rust-lang/rust/pull/56362#discussion_r237904889 for context.

cc @estebank @petrochenkov @varkor

**Comment by estebank** [comment]
Maybe we could do that with an upper bound, as having more than ~3 listed ranges will get really noisy. Imagine if you had a check for every other integer in u16, you'd have 32K ranges! I'd be fine with it as long as this is handled gracefully.

It'll also be nice to mention when a range between two values involves `std::{integer}::MAX` or `MIN`.

**Comment by Centril** [comment]
@estebank Yeah an upper bound makes sense.

**Comment by varkor** [comment]
> It'll also be nice to mention when a range between two values involves std::{integer}::MAX or MIN.

Yeah, this was a case I was thinking about too — it'll probably be fairly common case, so it'd be good to handle properly.

**Comment by estebank** [comment]
@Centril is there still work left to do on this front?

**Comment by varkor** [comment]
The match algorithm still short-circuits and reports only the first unencountered constructor in some cases. You can see this in some of the test cases for https://github.com/rust-lang/rust/pull/65160, for instance.

**Comment by Nadrieril** [comment]
Couldn't find an example with missing integer ranges like the one mentioned in the OP; I suspect we've fixed those. Here's a different one ([play](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=6d51af7602cc33d5b0de0b3ca47f6bb6)):
```rust
enum Foo {
    A(bool),
    B(bool),
    C(bool),
}
fn main() {
    match Foo::A(true) {
        Foo::A(true) => {},
        Foo::B(true) => {},
        Foo::C(true) => {},
    }
}
```
This only errors about `A(false)` not being covered.

Also I'm adding my favorite label so I can find this later.
@rustbot modify labels: +A-exhaustiveness-checking
