### ISSUE TITLE
{integer} is magic, but sometimes not magic enough

### ISSUE THREAD

**Issue by glandium** [rust-lang/rust#56370]
Consider the following code:
```rust
fn foo(s: usize) -> usize {
    s
}

fn main() {
    let f = foo(0);
}
```
0 is an {integer}, and it's magically found that it's valid to use as an usize. If the argument type had been a different integer type, that would work too.

However, the following doesn't work:
```rust
fn foo<S: Into<usize>>(s: S) -> usize {
    s.into()
}

fn main() {
    let f = foo(0);
}
```
It fails to compile with:
```
error[E0277]: the trait bound `usize: std::convert::From<i32>` is not satisfied
 --> src/main.rs:6:13
  |
6 |     let f = foo(0);
  |             ^^^ the trait `std::convert::From<i32>` is not implemented for `usize`
  |
  = help: the following implementations were found:
            <usize as std::convert::From<bool>>
            <usize as std::convert::From<u16>>
            <usize as std::convert::From<u8>>
```

**Comment by memoryruins** [comment]
It is [inferred](https://rust-lang.github.io/rustc-guide/type-inference.htm) to be 0usize. x would also be an usize in the following
```rust
let x = 0;
let f = foo(x);
```

This will error at compile-time, as foo expects an usize and we passed in an i32
```rust
let x: i32 = 0;
let f = foo(x);
```

> The type of an unsuffixed integer literal is determined by type inference:
>
> If an integer type can be uniquely determined from the surrounding program context, the unsuffixed integer literal has that type.
>
> If the program context under-constrains the type, it defaults to the signed 32-bit integer i32.
>
> If the program context over-constrains the type, it is considered a static type error.

https://doc.rust-lang.org/reference/tokens.html?#number-literals

**Comment by memoryruins** [comment]
As for the second example, it appears to be unable to infer it and defauls to i32, which does not have an impl to convert to usize.

**Comment by varkor** [comment]
How would you expect the second example to work? It has to pick an arbitrary integer type that satisfies the trait bound. `usize` is one choice, but so is `u16`, `u8`, etc. At the moment, the rules are simple: try to infer an integer type and fallback to `i32`. If these sorts of programs were accepted, then there would have to be a documented hierarchy of fallback integer types.

**Comment by nagisa** [comment]
Although how fallback to i32 operates is not ideal, there is nothing sensible to be done here to make the second example work in any sensible manner. Closing.
