### ISSUE TITLE
RustDoc: Search should "follow" trait generics for parameter and return tabs

### ISSUE THREAD

**Issue by akatechis** [rust-lang/rust#56386]
Repost from https://github.com/rust-lang/docs.rs/issues/266

If I search the name of a trait, it would be nice to see matches for parameter and return tabs for functions that include that trait as a trait bound.

In the screenshot below, State is a trait of the kiss3d crate, and the render_with_state shown has <S: State> trait bounds on it, so it would be nice to see that function under the "In parameters" tab as well. Ditto for functions where the trait object is returned.

![image](https://user-images.githubusercontent.com/1058931/49312918-be126500-f4b3-11e8-8537-d00cbc28b3fb.png)

**Comment by GuillaumeGomez** [comment]
It'll be working once #59004 is merged.

**Comment by kadiwa4** [comment]
It is fixed indeed.

**Comment by GuillaumeGomez** [comment]
Cl
osing then.
