### ISSUE TITLE
assert! in edition 2018 has a non-hygienic use of panic!

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/rust#56389]
This code runs fine on edition 2015, and has no warnings with `#![warn(rust_2018_compatibility)]`, but fails to compile on edition 2018 ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=78bae85bb457b7415dd39ecf23a1046c)):

```rust
#![no_implicit_prelude]

fn main() {
    assert!(true);
}
```

error message:

```
error: cannot find macro `panic!` in this scope
 --> src/main.rs:4:5
  |
4 |     assert!(true);
  |     ^^^^^^^^^^^^^^
  |
  = help: have you added the `#[macro_use]` on the module/import?
```

**Comment by Centril** [comment]
cc @petrochenkov

**Comment by petrochenkov** [comment]
This isn't a problem with `assert` alone, most of std/core macros call other macros unhygienically (some were recently fixed though https://github.com/rust-lang/rust/pull/55597).
I was actually going to fix this systematically, it's just not a highest priority work.

Also, using `$crate::panic!()` etc in std macros is technically a breaking change, because especially creative users could override standard panics and other macros with their own versions, so we'll probably need a crater run.

**Comment by Nemo157** [comment]
`assert` isn't actually a `std` macro, it's a builtin (otherwise it would have to be called as `std::assert!` above). I was surprised to find that `std::assert_eq!` actually has a hygienic use of `panic!` while `assert!` doesn't. IMO it would be nice to actually remove builtins from Rust's public API and hide them all behind `core` macros, (e.g. `macro_rules! assert { ($tt:tt) => { _builtin_assert!($tt) } }`), but that's probably a breaking change at this point.

**Comment by petrochenkov** [comment]
`assert_eq` also calls `panic` unhygienically (not via `$crate::panic!()`).

>IMO it would be nice to actually remove builtins from Rust's public API and hide them all behind core macros

+1

>but that's probably a breaking change at this point.

Probably not (modulo `no_implicit_prelude` which is pretty much unused).
IIRC, the main problem was documentation - it should show actual accepted inputs rather than `$tt:tt`, but that should be solvable somehow.

**Comment by Nemo157** [comment]
> `assert_eq` also calls `panic` unhygienically (not via `$crate::panic!()`).

That's surprising, it [appears to work](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=8c6cfd7926923dba20c742d1d0a10bb4) in edition 2018 with `no_implicit_prelude` still somehow...

**Comment by Nemo157** [comment]
#58702 appears to have extended the non-hygienity to other `core` macros, for crates using both edition 2015 and 2018:

```console
> # d6f513ec7d1e83c8689f94fb48686dd11f1d1c80 is just before #58702
> echo '#![no_implicit_prelude] fn main() { ::std::assert_eq!(1, 1) }' | rustc +d6f513ec7d1e83c8689f94fb48686dd11f1d1c80 --edition 2018 -

> echo '#![no_implicit_prelude] fn main() { ::std::assert_eq!(1, 1) }' | rustc +d6f513ec7d1e83c8689f94fb48686dd11f1d1c80 --edition 2015 -

> # 5d20ff4d2718c820632b38c1e49d4de648a9810b is the merge of #58702
> echo '#![no_implicit_prelude] fn main() { ::std::assert_eq!(1, 1) }' | rustc +5d20ff4d2718c820632b38c1e49d4de648a9810b --edition 2015 -
error: cannot find macro `panic!` in this scope
 --> <anon>:1:37
  |
1 | #![no_implicit_prelude] fn main() { ::std::assert_eq!(1, 1) }
  |                                     ^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: have you added the `#[macro_use]` on the module/import?
  = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: aborting due to previous error

> echo '#![no_implicit_prelude] fn main() { ::std::assert_eq!(1, 1) }' | rustc +5d20ff4d2718c820632b38c1e49d4de648a9810b --edition 2018 -
error: cannot find macro `panic!` in this scope
 --> <anon>:1:37
  |
1 | #![no_implicit_prelude] fn main() { ::std::assert_eq!(1, 1) }
  |                                     ^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: have you added the `#[macro_use]` on the module/import?
  = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: aborting due to previous error
```

**Comment by Nemo157** [comment]
The non-hygienity even extends to the `panic` macro itself, `::std::panic!()` expands to `panic!("explicit panic")` and gives `error: cannot find macro `panic!` in this scope`.

**Comment by petrochenkov** [comment]
For all macros *beside* `panic` the underlying issue is fixed in https://github.com/rust-lang/rust/pull/61629.
`panic` is special, https://github.com/rust-lang/rust/pull/61629 describes the situation in more detail.

**Comment by petrochenkov** [comment]
I'm going to close this in favor of https://github.com/rust-lang/rust/issues/61567 (which doesn't have a discussion distracting from the primary issue).
