### ISSUE TITLE
Tracking issue for feature `extern_crate_self`

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rust#56409]
With this feature `extern crate NAME as RENAME;` now accepts `NAME`=`self` and interprets it as referring to the local crate.

As with other `extern crate` items, `RENAME` in this case gets into extern prelude and therefore can be used from absolute paths and imports on 2018 edition.

```rust
extern crate self as serde; // Adds local crate to extern prelude as `serde`

mod foo { ... }

// Anywhere in this crate
use serde::foo; // OK
::serde::foo; // OK
```

The feature's primary purpose is to resolve https://github.com/rust-lang/rust/issues/54647 and support migration of proc macro crates to 2018 edition.

Implementation PR - https://github.com/rust-lang/rust/pull/55275.

**Comment by mehcode** [comment]
This would be excellent. Is there something blocking stabilization here? 

The "work-around" described in a related issue gets significantly more awkward if you're expanding proc-macros in doctests. See my recent edition upgrade on `diesel`: https://github.com/diesel-rs/diesel/blob/af1ff2476f997d6eb04fffd58260705d77ff6b6f/diesel_derives/src/util.rs#L81-L96

**Comment by petrochenkov** [comment]
>Is there something blocking stabilization here?

I don't think so, someone just needs to submit a stabilization PR, and then it should go through the "official" approval by the lang team.
