### ISSUE TITLE
ICE on beta in macro expansion: "byte index out of bounds" in resolve_imports

### ISSUE THREAD

**Issue by Shadlock0133** [rust-lang/rust#56411]
<details><summary>
lib.rs:
</summary><p>

```rust
macro_rules! import {
    ( $($name:ident),* ) => {
        $(
            mod $name;
            pub use self::$name;
        )*
    }
}

import!(day1);
```
</p></details>
day1.rs is empty
<details><summary>
error
</summary><p>
<pre><font color="#AB4642"><b>➜  </b></font><font color="#86C1B9"><b>ice</b></font> <font color="#7CAFC2"><b>git:(</b></font><font color="#AB4642"><b>master</b></font><font color="#7CAFC2"><b>) </b></font><font color="#F7CA88"><b>✗</b></font> RUST_BACKTRACE=1 cargo +beta build
<font color="#A1B56C"><b>   Compiling</b></font> ice v0.1.0 (/home/shadlock0133/projects/rust/ice)                                           
thread &apos;main&apos; panicked at &apos;byte index 45 is out of bounds of `self::$name`&apos;, libcore/str/mod.rs:2094:9   
stack backtrace:                                                                                         
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace                                          
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49                                            
   1: std::sys_common::backtrace::print                                                                  
             at libstd/sys_common/backtrace.rs:71                                                        
             at libstd/sys_common/backtrace.rs:59                                                        
   2: std::panicking::default_hook::{{closure}}                                                          
             at libstd/panicking.rs:211                                                                  
   3: std::panicking::default_hook                                                                       
             at libstd/panicking.rs:227                                                                  
   4: rustc::util::common::panic_hook                                                                    
   5: std::panicking::rust_panic_with_hook                                                               
             at libstd/panicking.rs:480                                                                  
   6: std::panicking::continue_panic_fmt                                                                 
             at libstd/panicking.rs:390                                                                  
   7: rust_begin_unwind                                                                                  
             at libstd/panicking.rs:325                                                                  
   8: core::panicking::panic_fmt                                                                         
             at libcore/panicking.rs:77                                                                  
   9: core::str::slice_error_fail                                                                        
             at libcore/str/mod.rs:0                                                                     
  10: core::str::traits::&lt;impl core::slice::SliceIndex&lt;str&gt; for core::ops::range::RangeTo&lt;usize&gt;&gt;::index::{{closure}}
  11: rustc_resolve::Resolver::report_conflict                                                           
  12: rustc_resolve::resolve_imports::ImportResolver::resolve_imports                                    
  13: rustc_resolve::macros::&lt;impl syntax::ext::base::Resolver for rustc_resolve::Resolver&lt;&apos;a, &apos;crateloader&gt;&gt;::resolve_imports
  14: syntax::ext::expand::MacroExpander::expand_fragment                                                
  15: syntax::ext::expand::MacroExpander::expand_crate                                                   
  16: rustc_driver::driver::phase_2_configure_and_expand_inner::{{closure}}                              
  17: rustc::util::common::time                                                                          
  18: rustc_driver::driver::phase_2_configure_and_expand                                                 
  19: rustc_driver::driver::compile_input                                                                
  20: rustc_driver::run_compiler_with_pool                                                               
  21: rustc_driver::driver::spawn_thread_pool                                                            
  22: rustc_driver::run_compiler                                                                         
  23: &lt;scoped_tls::ScopedKey&lt;T&gt;&gt;::set                                                                    
  24: &lt;std::panic::AssertUnwindSafe&lt;F&gt; as core::ops::function::FnOnce&lt;()&gt;&gt;::call_once                    
  25: __rust_maybe_catch_panic                                                                           
             at libpanic_unwind/lib.rs:102                                                               
  26: rustc_driver::run                                                                                  
  27: rustc_driver::main                                                                                 
  28: std::rt::lang_start::{{closure}}                                                                   
  29: std::panicking::try::do_call                                                                       
             at libstd/rt.rs:59                                                                          
             at libstd/panicking.rs:310                                                                  
  30: __rust_maybe_catch_panic                                                                           
             at libpanic_unwind/lib.rs:102                                                               
  31: std::rt::lang_start_internal                                                                       
             at libstd/panicking.rs:289                                                                  
             at libstd/panic.rs:392                                                                      
             at libstd/rt.rs:58                                                                          
  32: main                                                                                               
  33: __libc_start_main                                                                                  
  34: &lt;unknown&gt;                                                                                          
query stack during panic:                                                                                
end of query stack                                                                                       
                                                                                                         
error: internal compiler error: unexpected panic                                                         
                                                                                                         
note: the compiler unexpectedly panicked. this is a bug.                                                 
                                                                                                         
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
                                                                                                         
note: rustc 1.31.0-beta.19 (42053f9f0 2018-11-26) running on x86_64-unknown-linux-gnu                    
                                                                                                         
note: compiler flags: -C debuginfo=2 -C incremental --crate-type lib                                     
                                                                                                         
note: some of the compiler flags provided by cargo are hidden                                            
                                                                                                         
<font color="#AB4642"><b>error:</b></font> Could not compile `ice`.                                                                          

To learn more, run the command again with --verbose.
</pre>
</p></details>

**Comment by petrochenkov** [comment]
More or less same as https://github.com/rust-lang/rust/issues/56187.
`fn report_conflict` should stop doing span arithmetics.
cc @estebank @mockersf

**Comment by estebank** [comment]
@mockersf we could completely avoid span arithmetics by giving `ImportDirectiveSubclass::SingleImport` more useful spans, instead of having to come up with them on the spot. The counterarguments to that would be that it would increase memory usage in every import and that this suggestion is already useless in macro context (especially in this case).
