### ISSUE TITLE
Tracking issue for `shrink_to` feature

### ISSUE THREAD

**Issue by ordovicia** [rust-lang/rust#56431]
### Steps

- [x] Implementation (#49400)
- [x] Remove assert as suggested in https://github.com/rust-lang/rust/issues/56431#issuecomment-444521616
  - Resolved in https://github.com/rust-lang/rust/pull/81335
- [ ] Stabilization

### Questions

* Does this need an RFC?

cc @Diggsey

**Comment by kennytm** [comment]
Someone needs to update `BinaryHeap::shrink_to` to point to this issue.

**Comment by ordovicia** [comment]
I was just doing it :smile:

**Comment by Amanieu** [comment]
Currently the `shrink_to` method will panic if the given capacity is greater than the current one. I think this should be changed to silently ignore such cases instead.

I can see `shrink_to` being particularly useful when you want to reuse an existing allocation for something different (for example another pass of a multi-pass algorithm). The container will usually be empty at this point and you just want to ensure that a large allocation used for one pass doesn't clog up memory for the rest of the program's lifetime.

**Comment by ErichDonGubler** [comment]
I would agree with @Amanieu here -- I've just recently found a case where `shrink_to` would be handy, particularly if it silently no-op'd in the case of capacity actually being smaller than the specified maximum.

**Comment by Amanieu** [comment]
I have changed the behavior in hashbrown to no-op if the current capacity is smaller than the minimum (https://github.com/Amanieu/hashbrown/pull/67). There is currently still an assert in the libstd wrapper around hashbrown that panics though.

**Comment by In-line** [comment]
IMHO I would prefer shrink_to not to panic. I think it is better to return `Result<usize, TooSmallError>`? 

`Ok(..)` would contain previous capacity.
`Err(...)` will be returned in case of failure, containing required minimum.

With this change if I need code to panic, I will just `unwrap()`, but with current behavior it seems to be error prone.

**Comment by qasemsherfi** [comment]
I'm need really wallet

**Comment by qasemsherfi** [comment]
I'm need my wallet can work with exchange and send and receive

**Comment by marmeladema** [comment]
I think https://github.com/rust-lang/rust/pull/81335 fixed the last remaining concern.
Could it be stabilized, at least for `Vec`?
I am ready to do the PR if needed :+1:

**Comment by Folyd** [comment]
@kwf Feel free to file a stabilize PR.  See: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
