### ISSUE TITLE
building rust: failed to parse manifest for tool miri. cargo feature 'default-run' requires a nightly version of cargo but this is the beta channel

### ISSUE THREAD

**Issue by placidchat** [rust-lang/rust#56449]
I'm compiling rust, and this error popped up

error: failed to parse manifest at 'rust/src/tools/miri/Cargo.toml'
caused by: the cargo feature 'default-run' requires a nightly version of Cargo, but this is the 'beta' channel

how is this resolved?

**Comment by jonas-schievink** [comment]
Please follow the build instructions in the readme. You're probably not running the right command (for building Rust, the `x.py` build tool must be used).

**Comment by ehuss** [comment]
Closing as this is quite old, and I believe should be resolved.
