### ISSUE TITLE
'_ stops working for parameters in the "Into trick"

### ISSUE THREAD

**Issue by scottmcm** [rust-lang/rust#56450]
I was surprised that elision didn't allow an underscore lifetime on `bar` here:
```rust
fn foo(x: CodeNodeRef<'_>) {} // works
fn bar(x: impl Into<CodeNodeRef<'_>>) {} // ERROR: missing lifetime specifier
```
https://play.rust-lang.org/?gist=4023c378d2f54e77362bcb94d17dfbd9

**Comment by Centril** [comment]
Reduced:
```rust
fn foo(x: Wibble<'_>) {}
fn bar(x: impl Quux<Wibble<'_>>) {}

trait Quux<T> {}
struct Wibble<'a>(&'a ());
```

---------------

This might not be a bug as the interpretation of `x: impl Quux<Wibble<'_>>` could reasonably be `x: impl for<'a> Quux<Wibble<'a>>` so it's unclear what the rank of `'_` is.

Also note that `x: impl Quux<impl Copy>` is likewise forbidden and it's similar in kind in that it could also mean `x: impl for<T: Copy> Quux<T>` if we had `-XQuantifiedConstraints`.

cc @rust-lang/lang

**Comment by eddyb** [comment]
> `-XQuantifiedConstraints`

Do you mean "type HRTB"? We should probably use Rust terminology instead of GHC feature flags.

**Comment by Centril** [comment]
> > `-XQuantifiedConstraints`
> 
> Do you mean "type HRTB"? We should prefer Rust terminology to GHC feature flags.

[Yes](https://homepages.inf.ed.ac.uk/wadler/papers/quantcc/quantcc.pdf). (Higher Rank Trait Bounds is *really bad* jargon that is particularly misleading when `for<'a> fn(&'a X) -> &'a Y` is used since that is a higher ranked type and not a bound...)

**Comment by cramertj** [comment]
Yup, this is intentional since it's not clear whether we want an HRTB interpretation or a single-use elided lifetime.

**Comment by scottmcm** [comment]
Oh, right.  I should have remembered from the IHLE discussion of the same.
