### ISSUE TITLE
LLVM assertion in crushtool crate

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#56482]
The crushtool crate [fails to compile](https://crater-reports.s3.amazonaws.com/beta-1.31-5/master%238940af3cea4a9a9deabcaf843b2f8cad9a83fc61/reg/crushtool-0.3.10/log.txt) when LLVM assertions are enabled:

```
rustc: /checkout/src/llvm/lib/IR/Type.cpp:241: static llvm::IntegerType *llvm::IntegerType::get(llvm::LLVMContext &, unsigned int): Assertion `NumBits >= MIN_INT_BITS && "bitwidth too small"' failed.
```

This is **not** a regression, it's confirmed to also fail on 1.28.0 (alt builds are not available past that). You might want to remove the crate's lockfile if you test it locally.

**Comment by nikic** [comment]
Assertion occurs via SelectionDAGBuilder::lowerRangeToAssertZExt(), likely fixed by https://github.com/llvm-mirror/llvm/commit/30005234d7dd9172d4ee8d1fc63f555b2a810ae0.

**Comment by nikic** [comment]
Verified that this is indeed fixed on master. The last LLVM upgrade pulled in the fix.
