### ISSUE TITLE
LLVM assertion in simdnoise crate

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#56483]
The simdnoise crate [is failing to build](https://crater-reports.s3.amazonaws.com/beta-1.31-5/master%238940af3cea4a9a9deabcaf843b2f8cad9a83fc61/reg/simdnoise-2.3.6/log.txt) with an LLVM assertion:

```
rustc: /checkout/src/llvm/lib/Target/X86/MCTargetDesc/X86MCCodeEmitter.cpp:118: static uint8_t (anonymous namespace)::X86MCCodeEmitter::ModRMByte(unsigned int, unsigned int, unsigned int): Assertion `Mod < 4 && RegOpcode < 8 && RM < 8 && "ModRM Fields out of range!"' failed.
```

This is not a regression, it's confirmed to also fail on 1.28.0 (alt builds are not available past that).

**Comment by jonas-schievink** [comment]
Wow, this one's amazing.

**Comment by nikic** [comment]
This one still reproduces on master.

**Comment by nikic** [comment]
Unfortunately, I wasn't able to get this to assert with `--emit=llvm-bc` and a separate `llc` invocation.

**Comment by FrankSD** [comment]
Can an absolute beginner take this one?Let me know if someone is working on this already

**Comment by jonas-schievink** [comment]
@FrankSD This is an assertion failure in the very depths of LLVM's machine code backend, you can try to find a minimal test case if you want, but I wouldn't recommend finding or fixing the actual bug to a beginner (but feel free to try if you feel *very* ambitious!). You can also try your hand at one of the [E-Easy](https://github.com/rust-lang/rust/issues?q=is%3Aopen+is%3Aissue+label%3AE-easy) issues, which are specifically meant for beginners.

**Comment by mati865** [comment]
I can reproduce it with some old nightlies but `rustc 1.33.0-nightly (03acbd71c 2019-01-14)` works just fine.

**Comment by nikic** [comment]
@mati865 Did you use an assertion-enabled build? I tried again just now and am still seeing the assertion:

```
nikic@helios:~/rust-simd-noise$ rustc +ae1ba150a280ebe428c760fbbbd58ae758ba9ea7-alt -V
rustc 1.34.0-nightly (ae1ba150a 2019-01-29)
nikic@helios:~/rust-simd-noise$ cargo +ae1ba150a280ebe428c760fbbbd58ae758ba9ea7-alt build
   Compiling simdeez v0.4.2
   Compiling simdnoise v2.3.6 (/home/nikic/rust-simd-noise)
rustc: /checkout/src/llvm-project/llvm/lib/Target/X86/MCTargetDesc/X86MCCodeEmitter.cpp:118: static uint8_t (anonymous namespace)::X86MCCodeEmitter::ModRMByte(unsigned int, unsigned int, unsigned int): Assertion `Mod < 4 && RegOpcode < 8 && RM < 8 && "ModRM Fields out of range!"' failed.
error: Could not compile `simdnoise`.
```

**Comment by mati865** [comment]
@nikic my bad, new nightly builds don't have llvm assertions enabled.
