### ISSUE TITLE
Printout of "The Rust Programming Language" is truncated

### ISSUE THREAD

**Issue by jimis** [rust-lang/rust#56499]
Using Firefox, go to "The Rust Programming Language" manual page and click on the print button on the upper right corner. The print dialog pops-up, so select "print to PDF". The full URL is this:

https://doc.rust-lang.org/book/2018-edition/print.html

Results: The margins are messed up. The left half of the page is empty, the right half is missing (text is truncated in all pages). See attachment "mozilla.pdf", which is a printout of the first 10 pages of the manual.

[mozilla.pdf](https://github.com/rust-lang/rust/files/2643702/mozilla.pdf)

**Comment by steveklabnik** [comment]
Could you re-file this against https://github.com/rust-lang-nursery/mdbook please? thank you!

**Comment by jimis** [comment]
For reference: https://github.com/rust-lang-nursery/mdBook/issues/840
