### ISSUE TITLE
trait objects of a fundamental trait are treated as fundamental types

### ISSUE THREAD

**Issue by arielb1** [rust-lang/rust#56503]
I don't think this is intentional, at least it is not documented in the RFCs [1023] or [2451]:

[2451]: https://github.com/rust-lang/rfcs/blob/master/text/2451-re-rebalancing-coherence.md
[1023]: https://github.com/rust-lang/rfcs/blob/master/text/1023-rebalancing-coherence.md

## STR

Crate a (compile with `should_not_have_an_effect`):
```Rust
#![feature(fundamental)]

pub trait Abc {}

#[cfg_attr(should_not_have_an_effect, fundamental)]
pub trait Foo<T> {}
```

Crate b:
```Rust
extern crate a;

pub struct Bar;
impl a::Abc for a::Foo<Bar> {}
```

## Expected Result

The `cfg_attr` does not have an effect - the code gives this error:
```
error[E0117]: only traits defined in the current crate can be implemented for arbitrary types
 --> b.rs:4:1
  |
4 | impl a::Abc for a::Foo<Bar> {}
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ impl doesn't use types inside crate
  |
  = note: the impl does not reference any types defined in this crate
  = note: define and implement a trait or new type instead

error: aborting due to previous error
```

## Actual result

With `--cfg should_not_have_an_effect`, the code compiles

## Stability consequences

This can't be observed in stable code right now - the only stable `#[fundamental]` traits are `Sized` (which doesn't have type parameters) and the `Fn` traits (which can only be implemented for tuples, and these are never fundamental). However, if we *did* stabilize a "normal" `#[fundamental]` trait with type parameters, this would be visible on stable.

**Comment by arielb1** [comment]
This should either be fixed (`#[fundamental]` trait objects don't act as `#[fundamental]` types) or documented in the RFCs.

**Comment by nikomatsakis** [comment]
Discussed in the @rust-lang/lang meeting. We decided that for now we should just make `#[fundamental]` trait objects not act as `#[fundamental]` types.

**Comment by arielb1** [comment]
No warning period needed because this is a nightly feature? I think I'll E-mentor this.
