### ISSUE TITLE
-C target-feature=+foo overrides previous values

### ISSUE THREAD

**Issue by jbeich** [rust-lang/rust#56527]
I'm trying to pass **multiple** `-C target-feature` conditionally downstream. However, despite +/- for adding/removing a feature it appears only the last value takes effect.

```rust
$ cat >a.rs
fn main() {
    if cfg!(target_feature="avx2") {
        println!("AVX2 available");
    }
    if cfg!(target_feature="fma") {
        println!("FMA available");
    }
}

$ rustc a.rs -C target-feature=+avx2 -C target-feature=+fma
$ ./a
FMA available
$ rustc a.rs -C target-feature=+avx2,+fma
$ ./a
AVX2 available
FMA available
```

**Comment by cuviper** [comment]
FWIW, you can check for `cfg` values without any test program like:

    $ rustc --print cfg  -C target-feature=+avx2 -C target-feature=+fma

    $ rustc --print cfg  -C target-feature=+avx2,+fma

**Comment by petrochenkov** [comment]
I agree that it's a bug and will try to fix it.

**Comment by petrochenkov** [comment]
Fixed in https://github.com/rust-lang/rust/pull/72094.
