### ISSUE TITLE
rustdoc no longer renders source

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#56526]
For example, see https://doc.rust-lang.org/nightly/src/core/sync/atomic.rs.html#1112-1114 -- the source is blank for me. I've tried hard-refreshing but that didn't appear to help.

master -> beta promotion happened today so this may also be a regression (not sure since beta hasn't yet deployed)

cc @rust-lang/rustdoc

**Comment by Walther** [comment]
Seems to be a style / css issue, if I'm not mistaken, the contents are still there: scroll down far enough, and you'll see the source, below the line numbers.

<img width="855" alt="screen shot 2018-12-04 at 20 38 13" src="https://user-images.githubusercontent.com/2943750/49490377-9fd69d00-f804-11e8-86e1-3d0c0c5b8666.png">

**Comment by Walther** [comment]
On a quick glance with inspector, toggling this value
```.example-wrap {
 width:100%;
}```
looked like a quick workaround. Haven't tested if it causes any other complications

**Comment by GuillaumeGomez** [comment]
There is already a PR open to fix it: #56498.

**Comment by hellow554** [comment]
Related: https://github.com/rust-lang/docs.rs/issues/264#issuecomment-443449347

**Comment by QuietMisdreavus** [comment]
Docs.rs has a separate issue causing its source view to act like this. It needs its own fix to make that work.

**Comment by QuietMisdreavus** [comment]
Because of the timing of its merge, https://github.com/rust-lang/rust/pull/56498 will appear in tomorrow's nightly, which will fix this issue.

**Comment by GuillaumeGomez** [comment]
Since #56498 got merged, we can close this issue I assume.
