### ISSUE TITLE
Miscompilation resulting in execution of a `ud2` instruction

### ISSUE THREAD

**Issue by IsaacWoods** [rust-lang/rust#56543]
This regression appears between `nightly-2018-10-30` (produces working code) and `nightly-2018-11-30` (produces miscompilation). I have not had the chance to bisect further.

Because of the nature of the environment (Rust program relocated and run by UEFI firmware), investigation has been difficult, but I have tracked the execution of the `ud2` instruction to the `new` function of this struct:
``` rust
#[derive(Debug)]
#[repr(C)]
pub struct BootMemory<T>(core::ptr::Unique<T>);

impl<T> BootMemory<T> {
    pub unsafe fn new() -> BootMemory<T> {
        BootMemory(Unique::new_unchecked(core::ptr::null_mut()))
    }
}
```

The code is compiled using a custom target specification:
```
{
    "llvm-target": "x86_64-pc-windows-msvc",
    "target-endian": "little",
    "target-pointer-width": "64",
    "target-c-int-width": "32",
    "os": "none",
    "arch": "x86_64",
    "data-layout": "e-m:e-i64:64-f80:128-n8:16:32:64-S128",
    "executables": true,
    "disable-redzone": true,
    "panic-strategy": "abort",
    "linker-flavor": "lld-link",
    "pre-link-args": {
        "lld-link": [
            "/SUBSYSTEM:EFI_Application",
            "/ENTRY:uefi_main"
        ]
    },
    "exe-suffix": ".efi",
    "position-independent-executables": "true",
    "emit-debug-gdb-scripts": false
}
```

I will update this issue if I find more information

**Comment by nikic** [comment]
You are initializing `Unique<T>`, which must have a non-null value, with null. This is undefined behavior and in this case (luckily!) results in a `ud2` instruction.

You should either replace `Unique<T>` with a type that accepts null values (such as a pointer type), or use `Option<Unique<T>>`.

Generally, if you encounter `ud2` it's very likely to be due to some unsafe code triggering undefined behavior.

**Comment by IsaacWoods** [comment]
Ah, of course, that'll teach me; thanks very much, sorry for the clutter!
