### ISSUE TITLE
LinkedList's "constant time" push fallacy

### ISSUE THREAD

**Issue by leventov** [rust-lang/rust#56552]
The documentation for `LinkedList` says:

> The LinkedList allows pushing and popping elements at either end in constant time.

That is not quite correct, because pushing elements at either end requires a heap allocation, that could require creating a new arena in the allocator, that may trigger defragmentation of memory in the kernel... i. e. ultimately it may take many seconds to push an element to a LinkedList, even on the systems without swap.

So maybe it's better to mention in the doc that LinkedList should still be used with wariness for applications with hard realtime requirements.

**Comment by cuviper** [comment]
Constant time in this context means it's O(1) with respect to the length of the list.  It's not committing to some absolute deadline like RT environments would care about.

**Comment by sfackler** [comment]
This is not a distinction that I have ever seen be made in documentation.

**Comment by hellow554** [comment]
[The Big O notation](https://en.wikipedia.org/wiki/Big_O_notation) describes the the time of an algorithmn in respect to its size. Just what `cuviper` said, it doesn't say anything about environmental requirements, it's all about the algorithmn.

**Comment by Mark-Simulacrum** [comment]
Yes, it seems to me that this is a "constant time" with respect to O(1), not that the time is going to be low or high -- just that it will not depend on the existing length of the list. I'm going to close this as such, but let us know if you disagree and we can reopen.

**Comment by leventov** [comment]
What about rephrasing it as follows:

"The LinkedList allows popping elements at either end in constant time, and pushing elements at either end in time independent of the size of the list: the latency of pushing is determined by a single small heap allocation."

It may sound intimidating for beginners, but I would say this is a good thing: LinkedList's documentation shouldn't make it look appealing at any point, in any way.

**Comment by nikic** [comment]
Popping elements at either end is also not "constant time" under this definition. You could get an interrupt while popping and the kernel might decide to deschedule your thread for an indeterminate amount of time.

Apart from atomics maybe, there is not a whole lot of places where one can give such strong guarantees, and imho mentioning this in the documentation will be more harmful than helpful.

**Comment by leventov** [comment]
> Popping elements at either end is also not "constant time" under this definition. You could get an interrupt while popping and the kernel might decide to deschedule your thread for an indeterminate amount of time.

Not constant wall clock time, but constant user time, maybe if there is no swap.

Yes, definitely it doesn't make sense to mention those things in the doc of every data structure, but probably makes sense to make an exception for LinkedList due to it's uselessness. Making LinkedList to look more obscure and unappealing is helpful because less beginners are lured by the familiarity of this textbook data structure and use it.

**Comment by nikic** [comment]
I absolutely agree that use of LinkedList should be discouraged, but I think the current docs already do so in the very next sentence:

> Almost always it is better to use Vec or VecDeque instead of LinkedList. In general, array-based containers are faster, more memory efficient and make better use of CPU cache.
