### ISSUE TITLE
debug_assert should clarify impact on downstream crates

### ISSUE THREAD

**Issue by burdges** [rust-lang/rust#56551]
It's clear that [`debug_assert!`](https://doc.rust-lang.org/nightly/std/macro.debug_assert.html) runs in debug builds for the crate in which it lives.  It's should be clarified _if_ debug builds can only link to other debug builds, and thus that `debug_assert!` in downstream crates catch errors in the upstream crate usage of the downstream crate. 

There is a separate issue of this pattern being questionable: 
```
pub fn foo(&'static T) {
    debug_assert!(T.is_a_good_T(),"You gave a bad T in a debug build, so please fix it.  I believe that, if you never give me a bad &'static T in a debug build, then you cannot give me a bad &'static T in a release build.");
    ...
}
```

**Comment by hellow554** [comment]
I don't get your point. `debug_assert!` behaves like a normal assert if you run your program with `cargo run`. This will also affect crates you include, e.g. they will also have the `debug_assert!`s enabled.
When you compile your program with `cargo build --release` the `debug_assert!`s will be thrown out and no longer make any computation or assertion.
What do you want to be clarified?

**Comment by burdges** [comment]
We have a crate `foo` that provides a function `foo` containing a `debug_assert!`, and some crate `bar` includes `foo::foo`, so we expect the `debug_assert!` should run during debugging, like say to improve test perfomance.  Instead, `bar` could attempt to call a release build of `foo`.  Is this possible?  easy?  

If so, then the `debug_assert!` documentation should contain some warning about keeping debug builds for libraries as part of your debug cycle.  If not, then the `debug_assert!` documentation should be clearer.

**Comment by hellow554** [comment]
>  Is this possible?
Of course it's possible, but not within your normal workflow. As I said, if you run `cargo run` all crates you depend on will be built with debug mode enabled. Only if you use `cargo run --release` all dependencies, aka crates, will also built in release mode.

**Comment by hellow554** [comment]
```
$ cat ../foo/src/lib.rs 
pub fn foo(v: u8) {
    debug_assert!(v < 128);
    println!("{}", v);
}
$ cat src/main.rs 
extern crate foo;

fn main() {
    foo::foo(8);
    foo::foo(128);
}
$ cat Cargo.toml 
[package]
name = "bar"
version = "0.1.0"
authors = []

[dependencies]
foo = {path ="../foo"}

$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/bar`
8
thread 'main' panicked at 'assertion failed: v < 128', /tmp/tmp.WvYvoFMNXk/foo/src/lib.rs:2:5
note: Run with `RUST_BACKTRACE=1` for a backtrace.

$ cargo run --release
    Finished release [optimized] target(s) in 0.01s
     Running `target/release/bar`
8
128
```

**Comment by burdges** [comment]
Cool.  I suppose this issue can be closed since it sounds like avoiding the `debug_asserts!` requires considerable trickery.  There are no minimal tweaks to the`debug_assert!` that cover this, but maybe something as a part of singling out `cargo run` as a way to get debug builds in app crates.
