### ISSUE TITLE
Support 16-bit targets in `get_pointer_width`

### ISSUE THREAD

**Issue by varkor** [rust-lang/rust#56567]
https://github.com/rust-lang/rust/blob/4bb5d35659b6d8579007f49db09aa1d35782b834/src/tools/compiletest/src/util.rs#L103-L109
We should also support `"16bit"` here.

Once that's supported, the `precise_pointer_matching` test can be updated: https://github.com/rust-lang/rust/blob/4bb5d35659b6d8579007f49db09aa1d35782b834/src/test/ui/precise_pointer_size_matching.rs#L1-L6

**Comment by Centril** [comment]
cc @pnkfelix

**Comment by eddyb** [comment]
https://github.com/rust-lang/rust/blob/4bb5d35659b6d8579007f49db09aa1d35782b834/src/tools/compiletest/src/util.rs#L104
That's very fragile, it should've used `rustc --print=cfg` instead (or `--print=target-spec-json` and parse the output as JSON).
cc @nikomatsakis @kennytm

**Comment by kadiwa4** [comment]
No longer relevant since #100260.
