### ISSUE TITLE
Best way to remove Clippy and rustfmt previews before installing their 1.0 equivants?

### ISSUE THREAD

**Issue by JosephTLyons** [rust-lang/rust#56569]
I have the preview versions installed of these tools, are there commands to remove them before installing the stable versions, or is this automatically done with the update to Rust 2018?

**Comment by JosephTLyons** [comment]
It seems as if they are updated or removed when installing rust 2018, is this correct?

**Comment by madgene** [comment]
rustup self update
rustup toolchain remove stable
rustup toolchain add stable
rustup component add clippy rustfmt rls

**Comment by JosephTLyons** [comment]
Thank you!
