### ISSUE TITLE
Is Cargo Fix supposed to add 'edition = "2018"'?

### ISSUE THREAD

**Issue by JosephTLyons** [rust-lang/rust#56570]
I'm not entirely sure what all Cargo Fix is supposed to do.  I know its supposed to help migrate code from 2015 to 2018, but I'm not sure of the details.  I thought it would add 'edition = "2018"' to the toml file, but it does not.  Is this expected behavior?

**Comment by sfackler** [comment]
It is not: https://doc.rust-lang.org/stable/edition-guide/editions/transitioning-an-existing-project-to-a-new-edition.html#enabling-the-new-edition-to-use-new-features

**Comment by JosephTLyons** [comment]
Thank you.  What is cargo fix doing then?

**Comment by sfackler** [comment]
https://doc.rust-lang.org/stable/edition-guide/editions/transitioning-an-existing-project-to-a-new-edition.html#updating-your-code-to-be-compatible-with-the-new-edition

**Comment by steveklabnik** [comment]
Questions like this are best posed on users.rust-lang.org. It seems like we’ve got some answers, but if there’s more to discuss, please open a thread there. Thanks!
