### ISSUE TITLE
No nightly on 2018-12-07

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#56586]
```
$ rustup update
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
info: checking for self-updates

   stable-x86_64-unknown-linux-gnu unchanged - rustc 1.31.0 (abe02cefd 2018-12-04)
  nightly-x86_64-unknown-linux-gnu unchanged - rustc 1.32.0-nightly (14997d56a 2018-12-05)
```
As you can see, the latest nightly still has a commit dating from 2018-12-05, meaning it is the nightly created on 2018-12-06 (shortly after midnight).  There was no nightly created today.

Cc @rust-lang/infra

**Comment by RalfJung** [comment]
No, but I made a PR updating miri do a commit that's in a miri PR, not in miri master.  Because GH adds PR commits to the target repo I thought that should work, and it did work locally.

I now made a branch in the miri repo containing that commit,  I don't know if having it in a branch vs. a PR makes a difference though (I think it should not).

Is the release machine using an ancient version of git?

**Comment by o01eg** [comment]
> Is the release machine using an ancient version of git? Seems like the same problem that @jethrogb had (#56307 (comment)) with git 2.7 (which is almost 3 years old).

I got same issue with git 2.19.

**Comment by Mark-Simulacrum** [comment]
`git` on RCS is currently 2.7.4 so that might explain at least part of the problem. I've filed https://github.com/rust-lang/rust-central-station/pull/119 to try and update the Ubuntu used for RCS...

**Comment by alexcrichton** [comment]
We got a nightly last night, so closing! I think this is otherwise diagnosed and being fixed
