### ISSUE TITLE
Stabilize `feature(int_error_matching)`

### ISSUE THREAD

**Issue by ethanboxx** [rust-lang/rust#56587]
I am not very familiar with the stabilization process but I don't know of anything holding back `feature(int_error_matching)`.

The pull request can be found [here](https://github.com/rust-lang/rust/pull/55705)

**Comment by ZirconiumX** [comment]
Since it got merged a fortnight ago, I think it's best to wait for it to get used and tested in practice instead of stabilising it right now. It's possible the devs find a better approach for this problem.

**Comment by jonas-schievink** [comment]
See https://rust-lang.github.io/rustc-guide/stabilization_guide.html for details on the stabilization process.

**Comment by jonas-schievink** [comment]
Closing in favor of the tracking issue https://github.com/rust-lang/rust/issues/22639. In order to stabilize this, a libs team member has to start the FCP period.
