### ISSUE TITLE
Installer is very slow in Asia especially in China

### ISSUE THREAD

**Issue by jinfagang** [rust-lang/rust#56591]
Typically, without VPN this speed is very slow:

```
➜  rust curl https://sh.rustup.rs -sSf | sh

info: downloading installer

```

And then timeout connection, is the rust team consider provide some image in China for accelerate installation?

**Comment by ishitatsuyuki** [comment]
There are mirrors provided by Chinese universities. Use at your own risk.

```
RUSTUP_DIST_SERVER=https://mirrors.ustc.edu.cn/rust-static/
```

**Comment by jinfagang** [comment]
@ishitatsuyuki How to use it anyway. Set it as enviroment viriable?

**Comment by jinfagang** [comment]
@ishitatsuyuki Try replace original url:

```
./rustup-init.sh 
info: downloading installer
curl: (22) The requested URL returned error: 404 
rustup: command failed: downloader https://mirrors.ustc.edu.cn/rust-static//x86_64-unknown-linux-gnu/rustup-init /tmp/tmp.zRbA4qBy8N/rustup-init

```

**Comment by jinfagang** [comment]
As well as:

```
info: downloading installer
curl: (22) The requested URL returned error: 404 
rustup: command failed: downloader https://mirrors.ustc.edu.cn/rust-static/x86_64-unknown-linux-gnu/rustup-init /tmp/tmp.vHhhJ0eZPL/rustup-init

```

**Comment by crlf0710** [comment]
@ishitatsuyuki This doesn't work with the shell script downloader... unless this is merged:
https://github.com/rust-lang/rustup.rs/pull/1495

**Comment by csmoe** [comment]
Closes as an issue from rust-lang/rustup.rs and resolved.
