### ISSUE TITLE
Rust 1.32 crater runs

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#56608]

**Comment by Mark-Simulacrum** [comment]
@craterbot run name=beta-1.32-1 start=1.30 end=beta-2018-12-05 cap-lints=warn p=1

**Comment by Mark-Simulacrum** [comment]
@craterbot start=1.31

**Comment by Mark-Simulacrum** [comment]
@craterbot name=beta-1.32-1 start=1.31

**Comment by Mark-Simulacrum** [comment]
@craterbot run name=beta-1.32-rustdoc-1 start=1.31 end=beta-2018-12-05 mode=rustdoc

**Comment by pietroalbini** [comment]
@craterbot name=beta-1.32-rustdoc-1 start=1.31.0

Also fixed `beta-1.32-1` by manually updating the database.
