### ISSUE TITLE
Instant::now can go backward

### ISSUE THREAD

**Issue by goffrie** [rust-lang/rust#56612]
As in https://github.com/rust-lang/rust/issues/51648#issuecomment-441063768.

I've seen "specified instant was later than self" panics in the wild, in particular on Windows (32-bit x86). Googling reveals stuff like https://stackoverflow.com/questions/44020619/queryperformancecounter-on-multi-core-processor-under-windows-10-behaves-erratic which suggests that QueryPerformanceCounter can't really be relied on... frustratingly.

Perhaps libstd should work around this and enforce that `Instant::now()` never go backward (with an atomic global, or something?)

**Comment by goffrie** [comment]
Ok, I'm not sure that SO link was the best reference, but e.g. https://chromium.googlesource.com/chromium/src/base/+/master/time/time_win.cc#14 also claims that QPC is buggy.

**Comment by alexcrichton** [comment]
I've opened https://github.com/rust-lang/rust/pull/56988 to apply such a hammer to libstd as well

**Comment by gabrieljones** [comment]
This hammer is a code smell. This means that I can continue to get the wrong time even after a server's internal clock has been corrected by a time synchronizing service such as NTP. We should not be panicking when the diff between two instants is negative. That possibility should be documented.

> Time is an illusion. Lunchtime doubly so.

> Don’t panic

**Comment by the8472** [comment]
You already posted exactly the same comment in #56988, please do not spam.

Also note that `Instant` has no notion of "wrong time" in the sense of NTP since all it does is measure relative intervals, not absolute time.
