### ISSUE TITLE
Type Parameter for Once

### ISSUE THREAD

**Issue by Ericson2314** [rust-lang/rust#56664]
When I made a [spin lock version](https://mvdnes.github.io/rust-docs/spin-rs/spin/struct.Once.html) of `Once` for `spin`, I added a type parameter so this could act more like a promise of sorts. The is used in, e.g. `lazy-static`, store the result of the initialization function. It would be nice if `Once` became `Once<T = ()>` and offered the same expanded API.

One can always hand roll this with `Cell`, as `lazy-static` does when not using `spin`, but the composition of the `Once` and interior mutability is unsafe and thus requires extra care. This is exactly analogous to locks without the "slot", as POSIX threads defines the interface, also being unsafe/unergonomic.

Relatedly, there have long been murmers of moving `lazy_static` itself into `std`. I'm personally on the fence about that, but if we do so I see no reason why not to generalize `Once` as this issue proposes. There is also https://github.com/rust-lang-nursery/lazy-static.rs/issues/111 advocating less macro magic by having the `Lazy<T>` type be exposed. Well, that `Lazy<T>` is basically `Once<T>`.

**Comment by Mark-Simulacrum** [comment]
I'm going to close this out in favor of moving once_cell/lazy_static into std. I suspect that we'll be doing that fairly soon, and I suspect that adding a type parameter to `std::sync::Once` is considerably more error prone (it would complicate the type quite a bit, at least).
