### ISSUE TITLE
are there any plans on support for i in 10..0？

### ISSUE THREAD

**Issue by ruoru** [rust-lang/rust#56669]
```rs
// this can run.
for i in 0..10 {

}

// but this can not run.
for i in 10..0 {

}

```

**Comment by abonander** [comment]
That would actually be `(1..=10).rev()` since I assume the 0 is not supposed to be included but the 10 is.

**Comment by clarcharr** [comment]
You can also do `(10..0).step_by(-1)`.

**Comment by pmarcelll** [comment]
@clarcharr IIRC `step_by` doesn't work with negative numbers.

**Comment by steveklabnik** [comment]
Questions like this are best posed on https://internals.rust-lang.org/ . Thank you!
