### ISSUE TITLE
Compilation error with guess game

### ISSUE THREAD

**Issue by pradeepisro** [rust-lang/rust#56673]
I got the following error while compiling the guess game example.<br>

    error[E0432]: unresolved import `rand`
	 --> src/main.rs:2:5
	  |
	2 | use rand::Rng;
	  |     ^^^^ Maybe a missing `extern crate rand;`?

	error[E0658]: access to extern crates through prelude is experimental (see issue #44660)
	 --> src/main.rs:7:25
	  |
	7 |     let secret_number = rand::thread_rng().gen_range(1, 101);
	  |                         ^^^^

	warning: unused import: `rand::Rng`
	 --> src/main.rs:2:5
	  |
	2 | use rand::Rng;
	  |     ^^^^^^^^^
	  |
	  = note: #[warn(unused_imports)] on by default

	error[E0599]: no method named `gen_range` found for type `rand::ThreadRng` in the current scope
	 --> src/main.rs:7:44
	  |
	7 |     let secret_number = rand::thread_rng().gen_range(1, 101);
	  |                                            ^^^^^^^^^
	  |
	  = help: items from traits can only be used if the trait is in scope
	help: the following trait is implemented but not in scope, perhaps add a `use` for it:
	  |
	1 | use rand::Rng;
	  |

	error: aborting due to 3 previous errors

	Some errors occurred: E0432, E0599, E0658.
	For more information about an error, try `rustc --explain E0432`.
	error: Could not compile `guess_game`.

Environment:
1. rust-1.26.1
2. Ubuntu 16.04.5 LTS

The error was resolved when I added `extern crate rand;`. Is the example out of date?

**Comment by Patryk27** [comment]
The newest stable Rust is 1.31 - try upgrading (`rustup update`).

**Comment by steveklabnik** [comment]
@massih please see the comment above about rust versions; you need to be running rustc 1.31 or higher, and you need to have `edition = "2018"` in your `Cargo.toml` (which Cargo will add for you automatically)

**Comment by massih** [comment]
@steveklabnik I am using `rustc 1.31.1` but I created the project using intellij instead of `cargo`, and there was no `edition = "2018"` in the `Cargo.toml`. After adding the edition in the cargo file it works, probably I messed it up during the project creation in intellij. Thanks for quick response.

**Comment by bblur** [comment]
I'm using the newest rustc && cargo. And "Edition = 2018" also exists in Cargo.toml. But it still failed to import rand.
When I add rand in Cargo.toml, it works.
e.g.
[dependencies]
rand = "0.8.0"
