### ISSUE TITLE
ICE when trying to process a circular dependency between traits

### ISSUE THREAD

**Issue by Patryk27** [rust-lang/rust#56670]
Hi,

Following code causes an ICE (only on nightly - it doesn't panic at the stable version):
```rust
trait Foo where Self: Bar {
    type Context: Foo;
}

trait Bar where Self: Foo {
    
}
```
The problematic clause is `type Context: Foo;` - without it the compiler correctly determines that there's a cycle between `Foo` and `Bar`, whereas adding that instruction terminates compiler with:
```
thread 'main' panicked at 'did not find a cycle', src/librustc/ty/query/job.rs:146:9
note: Run with `RUST_BACKTRACE=1` for a backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.32.0-nightly (b68fc18c4 2018-11-27) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `bug`.

To learn more, run the command again with --verbose.
```

**Comment by pnkfelix** [comment]
triage: P-high T-compiler

**Comment by alexreg** [comment]
Intuition says this is closely related to https://github.com/rust-lang/rust/issues/56288. Thoughts?

**Comment by nikomatsakis** [comment]
Hmm, I am not able to reproduce any ICE on a currently nightly. So far I have tried:

- nightly-2018-12-18
- nightly-2018-12-08
- nightly-2018-12-07

with no dice. @Patryk27 are you still seeing this problem? If so, can you run `rustc -vV` and tell me what you see?

**Comment by alexreg** [comment]
Looks like PR #56863 fixed it?

**Comment by Patryk27** [comment]
Yeah, it seems to be fixed now - thanks!
