### ISSUE TITLE
Option for rustc to build the smallest executable possible?

### ISSUE THREAD

**Issue by ehouarn-perret** [rust-lang/rust#56687]
I was reading this link: https://lifthrasiir.github.io/rustlog/why-is-a-rust-executable-large.html and it kinda makes sense bout why Rust executable are relatively big without any optimization (actually a bit scary when I compare to Go executable which include a GC...) but still surprise that the --release flag does not make it that smaller out of the box.

I am wondering if there is any plan to bring another build (via an option or something not too obscure) option that would make the smallest possible Rust, out of the box?

**Comment by steveklabnik** [comment]
Please post questions like this on internals.rust-lang.org; we keep the issue tracker for bugs only. Thanks!
