### ISSUE TITLE
wrapping_offset recommends the user do UB

### ISSUE THREAD

**Issue by ubsan** [rust-lang/rust#56697]
"If you need to cross object boundaries, cast the pointer to an integer and do the arithmetic there." This is still UB, even if you cast to an integer. The sentence should be removed - there is _no_ way to move across objects in Rust like this without causing UB.

**Comment by rkruppe** [comment]
I'm not so sure about this. There have to be some provenance-ish rules, but pointer<->integer casts aren't nearly as strict as you say in today's implementation and I see no reason to expect they ever will be. Even LLVM's current rules (which are vague and inconsistent and need to be improved) are not so strict as to say you can't cross object boundaries *at all*.

For example, consider the offset `o = ptrtoint(p2) - ptrtoint(p1)` where `p1` points into one allocation and `p2` points into another. Under LLVM's ["based on" rules](https://llvm.org/docs/LangRef.html#pointer-aliasing-rules), `inttoptr(ptrtoint(p1) + o)` is based on both p1 and p2, so it can be dereferenced if `p2` can. In contrast, with `getelementpointer` (which is what `wrapping_offset` compiles down to), going from one allocation to another with `GEP(p1, ptrtoint(p2) - ptrtoint(p1))` is not OK (the GEP result is only based on `p1`).

As for the future: there are plausible semantics for pointers in optimizing compilers which don't assign much meaning to integers and integer arithmetic even on addresses created from pointers and grant "wildcard" provenance to every pointer created from integers.

So it seems clear to me that the ptrtoint->int arithmetic->inttoptr route is effectively UB in fewer cases, and will be formally UB in fewer cases when we have formal rules for Rust itself. While clearly there are cases where it's still UB, removing this recommendation without replacement seems unhelpful to people who need to cross object boundaries or at least reduce the risk of miscompilations. I'd like to at least leave a note that crossing object boundaries can be OK in certain circumstances which are still to be determined.

**Comment by RalfJung** [comment]
IIRC I added that sentence, and it still reflects my understanding of LLVM semantics: Integers do not have provenance, and if you do integer arithmetic to cross object boundaries, that's okay.

**Comment by ubsan** [comment]
@ralfjung you can cross object boundaries just fine, but actually dereferencing the resulting pointer is not. Even if it's not currently taken advantage of, the following is still UB (assuming the branch is taken):

```rust
fn main() {
  let mut x : i32 = 0;
  let mut y : i32 = 1;
  let px = &mut x as *mut i32 as usize;
  let py = px + 4;
  if (py == &y as *const i32 as usize) {
    unsafe {
      *(py as *mut i32) = 0; // UB
    }
  }
  y
}
```

**Comment by RalfJung** [comment]
@ubsan The only thing that makes your example UB is that you are using a raw pointer to write to a location that has never been made available for writes through raw pointers. That's an aliasing model situation, which is entirely orthogonal to crossing object boundaries.

If we change this to
```rust
fn main() {
  let mut x : i32 = 0;
  let mut y : i32 = 1;
  let px = &mut x as *mut i32 as usize;
  let py = px + 4;
  if (py == &mut y as *mut i32 as usize) {
    unsafe {
      *(py as *mut i32) = 0;
    }
  }
}
```
I think there is no UB. AFAIK nothing in LLVM makes this UB -- and if it would, LLVM would have a problem because LLVM considers your code equivalent to the following, which is not UB:
```rust
fn main() {
  let mut x : i32 = 0;
  let mut y : i32 = 1;
  let px = &mut x as *mut i32 as usize;
  let py = px + 4;
  if (py == &y as *const i32 as usize) {
    unsafe {
      *(&y as *const i32 as usize as *mut i32) = 0; // not UB
    }
  }
}
```
The two are only an integer substitution away from each other, which is a transformation LLVM does.

The following example is more clear, allowed by LLVM, and IMO even allowed by C (after all, your are casting the exact same value back that you got, you just did some trivial arithmetic in the mean time):
```rust
fn main() {
  let mut x : i32 = 0;
  let mut y : i32 = 1;
  let px = &mut x as *mut i32 as isize;
  let py = &mut y as *mut i32 as isize;
  let py2 = px + (py - px);
  *(py2 as *mut i32) = 2; // not UB
}
```

**Comment by ubsan** [comment]
@RalfJung hmm. You may be right. Still, I think it's a suspect thing to recommend without a full, accepted model.

**Comment by RalfJung** [comment]
The purpose of that recommendation was mostly to make people write
```rust
  let px = &mut x as *mut i32 as isize;
  let py = &mut y as *mut i32 as isize;
  let py2 = px + (py - px);
  *(py2 as *mut i32) = 2; // not UB
```
instead of
```rust
  let px = &mut x as *mut i32;
  let py = &mut y as *mut i32;
  let py2 = px.wrapping_offset(py.offset_from(px));
  *(py2 as *mut i32) = 2; // UB
```
If you have suggestions for how to improve the documentation, I am all ears :)

**Comment by ubsan** [comment]
@RalfJung I don't think that's actually a thing people write, among unrelated objects...

**Comment by nikomatsakis** [comment]
Is it your claim @ubsan that there is literally no blessed way to do "cross-object pointer arithmetic"?

If not, how *would* you suggest people do that sort of thing?

I admit I don't have a ready example of code that does something like this, but I feel like it's something I've done before (perhaps causing UB in the process =) or at least *thought* about doing. Trying to remember why now.

**Comment by nikomatsakis** [comment]
@ubsan did you intend to close this issue?

**Comment by ubsan** [comment]
@nikomatsakis yes, see the PR for reasoning.
