### ISSUE TITLE
Rustbuild should be able to test libstd without building a compiler

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/rust#56694]
Currently, any attempt to build or test a part of libstd forces rustc and rustdoc to be built, even though the downloaded bootstrap compiler already contains rustc and rustdoc executables. What's worse is that the only way to prevent the compiler build is by using `--keep-stage`, which has numerous issues and can even break the build directory in certain cases.

Rustbuild should be taught to use the the downloaded toolchain to build and test parts of libstd. It should either do so by default, or at least when `--stage=0` is passed.

**Comment by ehuss** [comment]
I'm going to close this as I believe it is fixed. ./x.py test src/libcore --stage 0 should only use stage0 rustc/rustdoc now.  Feel free to reopen if I misinterpreted!

cc #50367
