### ISSUE TITLE
 unresolved import `exonum::messages::Signed`

### ISSUE THREAD

**Issue by rakhmanu** [rust-lang/rust#56712]
Hi 
The src seems like correct as it does not implement an error while cargo build. However if i do cargo test, there is a mistake "unresolved import `exonum::messages::Signed`" I do not understand this mistake pls help me to fix
thanks in advance 
use exonum::{
    api::node::public::explorer::TransactionQuery,
    crypto::{self, Hash, PublicKey, SecretKey},
    messages::{self, RawTransaction, Signed},
};

**Comment by Patryk27** [comment]
This is most likely not a bug in the compiler - create a thread on http://reddit.com/r/rust/ or some Rust-related forum; this way you'll get help faster.

**Comment by estebank** [comment]
You can also ask for these kind of questions in https://users.rust-lang.org. This issue tracker is for bugs on the compiler or documentation of the language.
