### ISSUE TITLE
should `let _: T = RHS` be synonymous with `let _ = RHS: T`?

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#56715]
Spawned off of https://github.com/rust-lang/rust/issues/55748#issuecomment-446171809

The Rust test suite currently has the following test of how subtyping and "covariance" (*) works with respect to regions.

https://github.com/rust-lang/rust/blob/3a3121337122637fa11f0e5d42aec67551e8c125/src/test/run-pass/regions/regions-variance-covariant-use-covariant.rs#L24-L31

The problem is that there are small variations on this test that exercise very different parts of the compiler, and potentially expose incoherence in the semantics.

Here is some code that explores the different behaviors one might witness ([play](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2015&gist=ccfaf7d8ba72b3a063913e8b96f33044)):

```rust
#![feature(type_ascription)]
#![allow(dead_code)]

// SUMMARY OF BEHAVIOR
//
// EDITION        WILD      VAR       EXPR      ARG
// -----------    ------    ------    ------    ------
// 2015/AST       accept    accept    reject    accept
// 2018/NLL       accept    accept    reject    accept
// PATCHED        reject    accept    reject    accept

#[derive(Copy, Clone)]
struct Covariant<'a> {
    f: extern "Rust" fn(&'a isize)
}

fn ascribe_wild<'a>(co: Covariant<'a>) {
    let _: Covariant<'static> = co;  // (ascribe on) WILD(card)
}

fn ascribe_var<'a>(co: Covariant<'a>) {
    let _c: Covariant<'static> = co; // (ascribe on) VAR
}

fn ascribe_expr<'a>(co: Covariant<'a>) {
    let _ = co: Covariant<'static>;  // (ascribe on) EXPR
}

fn co_arg(_co_s: Covariant<'static>) { }

fn pass_actual_arg<'a>(co: Covariant<'a>) {
    co_arg(co);                      // (actual )ARG(ument)
}

pub fn main() {}
```

The entry in the summary that says "PATCHED" is for a 2018 compiler with the following patch applied to the following line of code:

https://github.com/rust-lang/rust/blob/3a3121337122637fa11f0e5d42aec67551e8c125/src/librustc_mir/build/matches/mod.rs#L1339-L1340

```
diff --git a/src/librustc_mir/build/matches/mod.rs b/src/librustc_mir/build/matches/mod.rs
index 7e7c0b1555..89f95368ad 100644
--- a/src/librustc_mir/build/matches/mod.rs
+++ b/src/librustc_mir/build/matches/mod.rs
@@ -1336,7 +1336,7 @@ impl<'a, 'gcx, 'tcx> Builder<'a, 'gcx, 'tcx> {
                     source_info,
                     kind: StatementKind::AscribeUserType(
                         ascription.source.clone(),
-                        ty::Variance::Covariant,
+                        ty::Variance::Invariant,
                         box ascription.user_ty.clone().user_ty(),
                     ),
                 },
```

The  original reasoning behind that patch is that *every* other place that we use `AscribeUserType`, we use an `Invariant` relation, not a `Covariant` one.

Note that the PATCHED version continues to handle the VAR and ARG cases in a manner consistent with the previous editions of Rust. In other words, in this instance, it just changes how `let _: T = RHS;` behaves to act more like `let _ = RHS: T;`

----

(*): I put "covariance" in quote because I think Rust's definition of co/contravariance on regions is tied to a mental model that is not ideal for practical usage, see also https://github.com/rust-lang/rfcs/issues/391

**Comment by pnkfelix** [comment]
(Also, the aforementioned patch would also fix the test from #55748 ([play](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=d23e8e709163e9c4afdfc7dc03621a90)) where NLL is causing us to accept code that we previously would have rejected. So could be used as an attempt to argue that the aforemented patch is "good"; but its entirely possible that a different path exists for a fix to #55748, so I won't further attempt to argue for the change on that basis. Instead I think the decision should be made based on the presentation of the various cases given above in this issue #56715 )

**Comment by pnkfelix** [comment]
I think this is a T-lang issue as well as an NLL one. The change I am suggesting seems like it might only impact NLL (and will be downgraded to a warning when it errors under migration mode), but it still is something I want the T-lang team to look at. So I'll add that label here too.

**Comment by nikomatsakis** [comment]
We discussed this a bit in the @rust-lang/lang meeting and decided that we needed to have further discussion.

@pnkfelix -- one thing I would note though is that, as presently implemented, `expr: T` performs a **type equality** rule, but that was considered a temporary hack. I think that is the source of the discrepancy you are talking about?

**Comment by pnkfelix** [comment]
> `expr: T` performs a **type equality** rule, but that was considered a temporary hack. I think that is the source of the discrepancy you are talking about?

This seems likely.

I wasn't aware it was meant to be a temporary hack. I'll go see if I can find record of discussion of that matter.

**Comment by Centril** [comment]
@pnkfelix You might want to take a look here: https://github.com/rust-lang/rfcs/pull/2522.

**Comment by pnkfelix** [comment]
@Centril hmm while I do see that RFC discusses lifetimes, I'm not sure if it goes so far as to discuss whether `PAT: T` will use subtyping or type-equality (when considering lifetimes within types) when it checks the ascription...? Maybe an unresolved question? Or am I overlooking something?

**Comment by Centril** [comment]
@pnkfelix See judgements in the [section on static semantics](https://github.com/Centril/rfcs/blob/rfc/generalized-type-ascription/text/0000-generalized-type-ascription.md#semantics-and-type-checking). The first and second subsections notes that given types `τ` and `σ` and some term `x` (or pattern), then `ImplicitlyCoercible(τ, σ), x : τ => (x : σ) : σ`. This is broader than subtyping; implicit coercions are OK. For patterns default match bindings are also taken into account.

**Comment by pnkfelix** [comment]
During a [discussion on zulip](https://rust-lang.zulipchat.com/#narrow/stream/122657-wg-nll/subject/.2356715.20meaning.20of.20type.20ascription/near/152030317), @nikomatsakis pointed out to me that given `let PAT: T_LHS = RHS`, it would be weird to perform coercions between RHS based on T_LHS and yet not allow subtyping between `T_LHS` and whatever the type of RHS is.

I found that to be a pretty compelling argument against what I am proposing here.
