### ISSUE TITLE
Rustdoc code view is broken

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#56720]
The source code view rendered by rustdoc, e.g. at https://doc.rust-lang.org/beta/src/std/error.rs.html, is broken:

![](https://screenshotscdn.firefoxusercontent.com/images/dc6b16b8-9343-4c55-aae3-a24307c46e36.png)

If I scroll down a lot, the code shows up.

This happens with both Firefox Beta and Chromium, on Linux.

**Comment by bjorn3** [comment]
Same for me with firefox dev-edition, Linux.

**Comment by QuietMisdreavus** [comment]
It's a CSS issue that's fixed on nightly, which means we need to backport https://github.com/rust-lang/rust/pull/56498 and/or related CSS PRs that happened around that time. cc @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
Just backporting the linked PR should be enough.

@QuietMisdreavus: I'll let you handle this part I guess. ;)

**Comment by QuietMisdreavus** [comment]
Since https://github.com/rust-lang/rust/pull/56819 merged, and the linked page is no longer showing the issue, i'm closing this.
