### ISSUE TITLE
Specify `RUST_BACKTRACE` is an env var on `panic`

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#56734]
The current `panic` message doesn't specify that `RUST_BACKTRACE` is an env variable, which can be difficult to understand for newcomers.
```
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by kinnison** [comment]
On the assumption that changing this message would not be considered a breaking change, I think this would be fairly easy and I'd like to give it a go to get my feet wet in the compiler codebase.

I would propose changing the message to:

    note: Run with `RUST_BACKTRACE=1` in the environment to display a backtrace.

Would that be suitable?
