### ISSUE TITLE
await macro is not in libcore.

### ISSUE THREAD

**Issue by james-darkfox** [rust-lang/rust#56767]
The `await!()` macro is defined in `std` but not in `core`, is there any reason for this?

**Comment by bjorn3** [comment]
It uses thread local storage, which isnt available outside libstd.

**Comment by james-darkfox** [comment]
@bjorn3 Hm. So it does. Looks like @Nemo157 's embrio fills the spot.

https://github.com/Nemo157/embrio-rs/blob/master/embrio-async/dehygiene/src/lib.rs

**Comment by Nemo157** [comment]
It's intended to be moved to `core` at some point (there's a few ways to reimplement it, `embrio-async`'s implementation is one but has some relatively spread out safety guarantees, adding the ability for generators to take resume arguments is another that I think would avoid needing any `unsafe` code at all).

I thought this was already noted on the tracking issue (#50547), but looking at it again it doesn't appear so, adding this issue to the unresolved questions would probably be useful.

**Comment by james-darkfox** [comment]
Thanks @Nemo157

**Comment by nikomatsakis** [comment]
Marking as **not blocking** for stabilization. Obviously we want things to work from core eventually, but it's ok if that doesn't work to start. Moreover, the **major** blocker here is resolving how generator arguments should work -- once that works, it seems clear that we'll be able to solve this.

**Comment by cramertj** [comment]
Closing this in favor of https://github.com/rust-lang/rust/issues/56974
