### ISSUE TITLE
Huge compile time regression with `edition = "2018"` enabled

### ISSUE THREAD

**Issue by weiznich** [rust-lang/rust#56780]
While trying to port diesel to the 2018 edition I've noticed an huge increase in the compile time.

With the 1.31.0 stable release:

* With edition: `cargo check  841,19s user 19,39s system 97% cpu 14:40,77 total`
* Without edition: `cargo check  23,16s user 0,54s system 98% cpu 24,076 total`

Steps to reproduce:

* Checkout [diesel](https://github.com/weiznich/diesel/commit/486786274a97669b836691a7d0c7797fb540da45)
* Add `edition = "2018"` to the diesel core crate (in the diesel folder)
* Run `cargo check` there
* Ignore all errors, wait till the compiler has finished

Side notes:
* Happens also on nightly (4a45578bc 2018-12-07)
* Does not happen with `#![feature(nll)]` on the 2015 edition
* Seems to be somehow related to implementing traits for generic tuples (Error messages out of those impls are coming later)

**Comment by weiznich** [comment]
`cargo check` generates 1899 error messages. I remember having that much errors before without taking that much time to get them. 
Also I expected `cargo fix` to make a crate compatible with the 2018 edition, seems like this does not work for diesel 😟

**Comment by Mark-Simulacrum** [comment]
`cargo fix` needs to be run before `edition = 2018` is placed in the toml; did you follow the directions in the [guide](https://doc.rust-lang.org/nightly/edition-guide/editions/transitioning-an-existing-project-to-a-new-edition.html)?

**Comment by weiznich** [comment]
I've run `cargo fix`, but it reported:
```
warning: failed to automatically apply fixes suggested by rustc to crate `diesel`

after fixes were automatically applied the compiler reported errors within these files:

  * diesel/src/type_impls/date_and_time.rs

This likely indicates a bug in either rustc or cargo itself,
and we would appreciate a bug report! You're likely to see 
a number of compiler warnings after this message which cargo
attempted to fix but failed. If you could open an issue at
https://github.com/rust-lang/cargo/issues
quoting the full output of this command we'd be very appreciative!
…
```

**Comment by Mark-Simulacrum** [comment]
Checking out https://github.com/weiznich/diesel/commit/486786274a97669b836691a7d0c7797fb540da45 and running `cargo check` already gives me an error, so I don't expect migration to work...

```
error[E0107]: wrong number of type arguments: expected 1, found 2
  --> diesel_derives/src/util.rs:48:84
   |
48 | pub fn ty_for_foreign_derive(item: &DeriveInput, flags: &MetaItem) -> Result<Type, Diagnostic> {
   |                                                                                    ^^^^^^^^^^ unexpected type argument


```

**Comment by weiznich** [comment]
Are you're sure that you use that version? I cannot reproduce that error on a clean clone. Also our [CI succeeds](https://github.com/diesel-rs/diesel/pull/1936) on that commit.

**Comment by Mark-Simulacrum** [comment]
Ah, I was using the master branch, not that commit. My bad.

I am seeing a bunch of warnings and a few errors when attempting to fix diesel; I suspect this may be due to the proc macros (but I thought we had hygiene for those, so not sure).

cc @alexcrichton on the cargo fix failure, full log here: https://gist.github.com/Mark-Simulacrum/0b9935097208f07b93e3b7e522f22e1e

**Comment by weiznich** [comment]
So I've managed to get cargo fix to work. (The issue was that diesel generated some code using custom derives that was using the old syntax for use statements …). The fixed branch is [here](https://github.com/weiznich/diesel/tree/test_2018_edition)

After that the compile times are back to ~normal.
