### ISSUE TITLE
u32::checked_shl is not checking for overflows

### ISSUE THREAD

**Issue by adriamb** [rust-lang/rust#56823]
Hi,
I'm been doing some tests and it seems that the `checked_shl` is not working properly in `u32`, so the output of the program

```
fn main() {
    let v : u32 = u32::max_value();
    for s in 0..7 {
        print!("{:032b}\n",v.checked_shl(s).unwrap());
    }
}
```
is
```
11111111111111111111111111111111
11111111111111111111111111111110
11111111111111111111111111111100
11111111111111111111111111111000
11111111111111111111111111110000
11111111111111111111111111100000
11111111111111111111111111000000
```
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=f22daa97aa101d87131b66a527efacc3

**Comment by jonas-schievink** [comment]
This is what it's supposed to do - it will only return `None` if you try to shift by more than the number of bits in a `u32`.

**Comment by estebank** [comment]
If you change `7` for `33` you will get a panic due to the `unwrap`. This is indeed [working as expected](https://doc.rust-lang.org/std/primitive.u32.html#method.checked_shl).

**Comment by adriamb** [comment]
Ok! Thanks for your quick answer! 

The current documentation says:

Shifts a number to the left, checking for overflow. If overflow happens, None is returned.

maybe is better if it says

Shifts a number to the left, checking if the parameter overflows the current type size. If overflow happens, None is returned.

If not, is easy to think that this operation checks the final value, when what has been checked is the parameter.

**Comment by estebank** [comment]
What documentation are you referring to? I see:

> Checked shift left. Computes self << rhs, returning None if rhs is larger than or equal to the number of bits in self.

**Comment by adriamb** [comment]
In the first Google result that is in https://docs.diesel.rs/num_traits/ops/checked/trait.CheckedShl.html 

Now I see that this is an already resolved issue
https://github.com/rust-num/num-traits/issues/57... 

Lesson leart, always check last version (I checked with other guy before reporting and we didn't think that the description could be wrong in this way...)
