### ISSUE TITLE
try_block cannot be used everywhere an expression can

### ISSUE THREAD

**Issue by rodrigorc** [rust-lang/rust#56828]
The following code fails to compile (`rustc --edition=2018`):
```
#![feature(try_blocks)]
fn main() {
    match try { 0 } {
        None => (),
        Some(_) => ()
    };
}
```

The compiler error is:
```
error: expected expression, found reserved keyword `try`
 --> test.rs:3:11
  |
3 |     match try { 0 } {
  |     ----- ^^^ expected expression
  |     |
  |     while parsing this match expression

```
Adding parentheses or braces, it will compile fine:
```
    match ( try { 0 } ) { ... } //warning: unnecessary parentheses around `match` head expression
    match { try { 0 } } { ... }
```
The same issue happens with other constructs such as:
```
    if let Some(_) = try { 0 } { }
    for _ in try { 0 } { } //should fail because of "cannot infer type", not "expected expression"
```

**Comment by Centril** [comment]
cc @scottmcm

**Comment by Centril** [comment]
Yeah I think `match loop { ... } {` is the better comparison here so it's probably a bug.

**Comment by rodrigorc** [comment]
> ```rust
> match loop { break } {
> ```
> 
This is exactly what a thought. I didn't know that this:
> ```rust
> struct try { x: i32 }
> fn main() {
>     let x = 1;
>     match try { x } {
>         try { .. } => {}
>     }
> }
> ```
was not allowed, so in my head the parentheses were always redundant. Is there any reason for why we need parentheses around a struct literal? A parser ambiguity, maybe? Because I would expect that to work, too.
