### ISSUE TITLE
New rustdoc "Loading content..." feature breaks inbound anchors

### ISSUE THREAD

**Issue by JohnHeitmann** [rust-lang/rust#56872]
If you visit a doc page on docs from nightly with a url that includes an anchor, e.g. `'.../doc/std/iter/trait.Iterator.html#method.size_hint'`, then the page stops loading due to a js error. The "Loading content..." messages remain forever and no doc content appears.

The js error is:
```
main.js:222 Uncaught TypeError: h3.getElementsByClassName is not a function
    at expandSection (main.js:222)
    at main.js:2416
    at main.js:2462
```

**Comment by GuillaumeGomez** [comment]
Fixed by #56876.
