### ISSUE TITLE
nightly doc gives dark theme only

### ISSUE THREAD

**Issue by hellow554** [rust-lang/rust#56871]
On the nightly api page (https://doc.rust-lang.org/nightly/std/) you will automatically have the dark theme selected. That is the unexpected thing number 1. The next thing is, that even if you change it to the light theme, it will only work for the current page. As soon as you click on a link to any other page, it will have the dark theme selected again.

**Comment by Centril** [comment]
cc @GuillaumeGomez @QuietMisdreavus 

I have the same experience (Firefox Developer Edition 65.0b2 (64-bit), Windows 10).
