### ISSUE TITLE
Missing iterations

### ISSUE THREAD

**Issue by samueltardieu** [rust-lang/rust#56883]
The following code prints "foo" 4 times with stable and beta, but prints nothing with rustc 1.33.0-nightly (93c2f055b 2018-12-15).

```rust
fn main() {
    std::iter::once(0).cycle().skip(1).take(4).for_each(|_| println!("foo"));
}
```

Replacing `once()` by something else or replacing `for_each()` with `map()` exhibits the same behaviour.

**Comment by bluss** [comment]
It looks like the `try_fold` impl for Cycle in commit fbe5aa57ed810733f2fd4047cf5e5c24aebd8b01 is is not correct, this is probably the cause.

**Comment by samueltardieu** [comment]
Indeed, it looks like if you try to fold after you have just exhausted a copy of your original iterator, you are out of luck and will exit immediately with the initial value.
