### ISSUE TITLE
Inverse drop order in a tuple?

### ISSUE THREAD

**Issue by vorner** [rust-lang/rust#56880]
Hello

I was experimenting with the code from nomicon (in my occasional attempts to bring it more up to date) and discovered something strange. I have this code on playground:

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=88b21c3520dead8c751e9818c2f1e001

It compiles (while if I put the tuple in the reverse order, eg `(inspector, days)`, it doesn't and it complains days is dropped first). This however seems to be in conflict with what this RFC says:

https://github.com/rust-lang/rfcs/blob/master/text/1857-stabilize-drop-order.md#tuples-structs-and-enum-variants

> Struct fields are dropped in the same order as they are declared. Consider, for instance, the struct below:

And 

> Tuples and tuple structs show the same behavior, as well as enum variants of both kinds (struct and tuple variants).

Is this a bug or is it intended? If so, where is it documented? If it changed, should the RFC somehow be marked as not being up to date?

**Comment by vorner** [comment]
A little update. It seems to be happening only when unpacked by a pattern, so maybe it is not specified by the RFC at all? But this code *is* a bit surprising in how it acts:

https://play.rust-lang.org/?version=stable&mode=release&edition=2018

**Comment by jonas-schievink** [comment]
Yeah, this is happening because you're unpacking the tuple into 2 local variables (which are dropped in reverse order). The second example tries to drop the entire tuple, which would drop `tuple.0` before `tuple.1`.

**Comment by vorner** [comment]
OK, then it's likely not a bug. But it did scare me a bit 😇. Sorry for the false alarm.
