### ISSUE TITLE
Cannot infer lifetime when mutable (works when non-mutable)

### ISSUE THREAD

**Issue by rom1v** [rust-lang/rust#56915]
Given some type with a lifetime parameter (`X`), I want to expose some "view":

```rust
struct X<'a>(&'a u32);

struct View<'a> {
    x: &'a X<'a>,
}

struct ViewMut<'a> {
    x: &'a mut X<'a>,
}
```

The problem occurs when I try to implement a function returning such a view.

If I implement only non-mutable view, it works:

```rust
impl X<'_> {
    fn view(&self) -> View {
        View { x: self }
    }
}
```

or equivalently:

```rust
impl<'a> X<'a> {
    fn view(&'a self) -> View<'a> {
        View { x: self }
    }
}
````

For mutable view, this works:

```rust
impl<'a> X<'a> {
    fn view_mut(&'a mut self) -> ViewMut<'a> {
        ViewMut { x: self }
    }
}
```

but this does not:

```rust
impl X<'_> {
    fn view_mut(&mut self) -> ViewMut {
        ViewMut { x: self }
    }
}
```

Which fails with:

```
error[E0495]: cannot infer an appropriate lifetime for lifetime parameter `'a` due to conflicting requirements
  --> test.rs:13:9
   |
13 |         ViewMut { x: self }
   |         ^^^^^^^
   |
note: first, the lifetime cannot outlive the anonymous lifetime #1 defined on the method body at 12:5...
  --> test.rs:12:5
   |
12 | /     pub fn view_mut(&mut self) -> ViewMut {
13 | |         ViewMut { x: self }
14 | |     }
   | |_____^
   = note: ...so that the expression is assignable:
           expected ViewMut<'_>
              found ViewMut<'_>
note: but, the lifetime must be valid for the lifetime '_ as defined on the impl at 11:8...
  --> test.rs:11:8
   |
11 | impl X<'_> {
   |        ^^
   = note: ...so that the expression is assignable:
           expected &mut X<'_>
              found &mut X<'_>

error: aborting due to previous error

For more information about this error, try `rustc --explain E0495`.
```

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=c079e2ed2e2d0822bda99d5506a62ba0

**Comment by jonas-schievink** [comment]
I don't think this is a bug, `ViewMut` is invariant over `'a`, so both lifetimes in the `&mut self` expression (which is `self: &'1 mut X<'2>`) must be exactly equal

**Comment by rom1v** [comment]
I'm not sure to understand why this is different between the mut and non-mut version. Could you elaborate?

**Comment by jonas-schievink** [comment]
`&'a mut T` is invariant over lifetimes in `T`, while `&'a T` is variant, so the former has stricter requirements for compatible types. You might want to read the corresponding Rustonomicon chapter: https://doc.rust-lang.org/nomicon/subtyping.html

**Comment by rom1v** [comment]
Thank you :+1:
