### ISSUE TITLE
aliases.js and source-files.js duplicate entries.

### ISSUE THREAD

**Issue by daxpedda** [rust-lang/rust#56921]
**Problem**
Generating new docs with `cargo doc` without cleaning the files (for example with `cargo clean`) creates duplicate entries in `aliases.js` and `source-files.js`.
The expected behaviour is no duplicate entries.

**Steps**
I created an example repository here: https://github.com/daxpedda/docs_test.
Going through the commits the bug can be seen easily ([#1](https://github.com/daxpedda/docs_test/blob/4c1bdc5d078a92bee0bf473aedaf9547b3fc9bec/target/doc/aliases.js), [#2](https://github.com/daxpedda/docs_test/blob/24d42e94e7247e0f30de726a2e853f47d70916bf/target/doc/aliases.js), [#3](https://github.com/daxpedda/docs_test/blob/102d2d0983b8ec68b8ee9bff30c2487133fb5555/target/doc/aliases.js), [#4](https://github.com/daxpedda/docs_test/blob/b4899ac154433248ab720c278cf588036a6d9a38/target/doc/aliases.js), [#5](https://github.com/daxpedda/docs_test/blob/08fd58264b2d74232cfb7975c1308ebf627bff6f/target/doc/aliases.js)).

1. Run `cargo doc` on a crate with anything to document.
2. Change some documentation and re-run `cargo doc` without cleaning the files (for example with `cargo clean`).
3. Check the files `target/doc/aliases.js` and `target/doc/source-files.js` to see the duplicate entries.

**Possible Solution(s)**
I didn't look at the code of cargo before, so I have no clue. Obviously a quick hack would be just to overwrite the file and regenerate it every time, I don't think the issue is pressing enough to use a hack though.

**Notes**
I tested this bug on the nightly toolchain on Windows and Linux.

**Comment by alexcrichton** [comment]
Thanks for the report! I've trasferred this to the rust-lang/rust repository as this is likely a rustdoc bug rather than a Cargo bug

**Comment by GuillaumeGomez** [comment]
Indeed, fixing it.
