### ISSUE TITLE
Different behaviors of allocator in nuanced snippets

### ISSUE THREAD

**Issue by Pslydhh** [rust-lang/rust#56929]
<pre><code>use std::sync::mpsc;
use std::thread;
fn main() {
    const STEPS: usize  = 1000000;
    thread::sleep(std::time::Duration::from_millis(10));
    let now = std::time::Instant::now();

    let (tx1, rx1) = mpsc::channel();
    for _ in 0..STEPS {
        let _ = tx1.send(1);
//    }
//    for _ in 0..STEPS {
        assert_eq!(rx1.try_recv().unwrap(), 1);
    }

    let elapsed = now.elapsed();
    println!("recv duration: {} secs {} nanosecs\n", elapsed.as_secs(), elapsed.subsec_nanos());
    thread::sleep(std::time::Duration::from_millis(10000));
}</code></pre>

The two lines comment/no-comment, the RES of this process is 1.7/47MB in the test.

**Comment by Pslydhh** [comment]
> The uncommented version first sends a million objects, allocating a large amount of memory in the process, most of which is then kept around by the allocator even after being deallocated by try_recv.

I must say that I personally disagree with this optimization(only linux, no optimization for windows) . 
I think it maybe better used as a parameterized option or something like it. :)
And the Implementation of optimization could't reclaim memory in the nested threads, even when thread done:
<pre><code>use std::sync::mpsc;
use std::thread;

fn main() {
    const STEPS: usize  = 1000000;
    thread::sleep(std::time::Duration::from_millis(10));
    let now = std::time::Instant::now();

    let t = thread::spawn(|| {
        let t = thread::spawn(|| {
            let (tx1, rx1) = mpsc::channel();
            for _ in 0..STEPS {
                let _ = tx1.send(1);
            }
            for _ in 0..STEPS {
                assert_eq!(rx1.try_recv().unwrap(), 1);
            }
        });

        t.join().unwrap();

        let (tx1, rx1) = mpsc::channel();
        for _ in 0..STEPS {
            let _ = tx1.send(1);
        }
        for _ in 0..STEPS {
            assert_eq!(rx1.try_recv().unwrap(), 1);
        }
    });

    t.join().unwrap();

    let (tx1, rx1) = mpsc::channel();
    for _ in 0..STEPS {
        let _ = tx1.send(1);
    }
    for _ in 0..STEPS {
        assert_eq!(rx1.try_recv().unwrap(), 1);
    }

    let elapsed = now.elapsed();
    println!("recv duration: {} secs {} nanosecs\n", elapsed.as_secs(), elapsed.subsec_nanos());
    thread::sleep(std::time::Duration::from_millis(10000));
}
</code></pre>

**Comment by Pslydhh** [comment]
Thank you for the suggestion! @jonas-schievink

**Comment by Pslydhh** [comment]
> With the lines commented out, the `try_recv` will immediately deallocate the memory allocated by `send` and allows the subsequent `send` to reuse the allocation on each iteration. The uncommented version first `send`s a million objects, allocating a large amount of memory in the process, most of which is then kept around by the allocator even after being deallocated by `try_recv`. This is just an optimization pretty much all allocators do, because they assume your program is going to need that memory again in the near future.

I found that this optimization described here happened in beta(1.32.0-beta.7)/nightly(1.33.0-nightly) versoin, but not in stable(1.31.1) version. The stable version fits my intuition.
Is this will be Stabilization?
cc @jonas-schievink

**Comment by jonas-schievink** [comment]
Closing since this is behaving as expected. We do not control and thus cannot guarantee the behavior of the system allocator. Allocator behavior may change between versions and is not considered part of stability guarantees.
