### ISSUE TITLE
Incorrect help message for bad tuple indexing on parenthesised array

### ISSUE THREAD

**Issue by varkor** [rust-lang/rust#56963]
```rust
fn main() {
    let x = [0u32];
    (x as [u32; 1]).0
}
```
The help message suggests:
```
help: instead of using tuple indexing, use array indexing: `x as [u32; 1][0]`
```
The parentheses have gone missing.

This is related to https://github.com/rust-lang/rust/issues/56714.

**Comment by zackmdavis** [comment]
This kind of thing (compare to _e.g_. #55109) happens when we use the pretty printer to synthesize suggestions.

https://github.com/rust-lang/rust/blob/d99a320cba42f661aebfa1293b7b2ec3603dda75/src/librustc_typeck/check/mod.rs#L3375-L3377
