### ISSUE TITLE
Dist index gone

### ISSUE THREAD

**Issue by jethrogb** [rust-lang/rust#56971]
These indices are out of date:
* https://static.rust-lang.org/dist/index.html
* https://static.rust-lang.org/dist/index.txt

Edit: they're 404's now.

**Comment by jethrogb** [comment]
I have no idea how to get a link to discord, but there was some discussion on this in the infra channel at 2018-12-18 10:42 UTC and 2018-12-18 12:32 UTC.

Main takeaways from that discussion:
* generating the index was taking to long, the recommendation is to use the AWS S3 List Objects API
* listing all objects using the AWS S3 List Objects API takes a very long time because you'll be rate-limited after a few requests
* rustup currently doesn't use the index, but also rustup currently doesn't have a way to list which toolchains are installable

**Comment by jethrogb** [comment]
I think there should be an index of at least all available toolchains, and preferably also for each toolchain which components exist.

**Comment by hellow554** [comment]
The links above are dead

**Comment by acmcarther** [comment]
I'm not sure if this is the main thread of this issue, but hopefully an observer here can redirect me if not.

Is [this comment](https://github.com/rust-lang/rust/issues/56971#issuecomment-448471533) saying that removing the index was deliberate? That index is the suggested means of finding older releases on the [other installation methods](https://forge.rust-lang.org/other-installation-methods.html) page.

> Past releases can be found in [the archives](https://static.rust-lang.org/dist/index.html).

**Comment by jethrogb** [comment]
@estebank T-doc? Should be T-infra

**Comment by Mark-Simulacrum** [comment]
This is expected behavior, and movement here is unlikely at this point so I'm going to close.

**Comment by jethrogb** [comment]
@Mark-Simulacrum why is movement unlikely? IIRC @pietroalbini had some thoughts on this.

**Comment by Mark-Simulacrum** [comment]
There are options to explore, but they're all pretty internal and this issue won't really help with tracking them I think. I suppose we could move it to the infra team repo.

**Comment by SimonSapin** [comment]
A work-around is to run AWS Command Line Interface. However it takes a while and as far as I can tell there is no server-side glob filtering. When possible, requesting a dated sub-directory is more reasonable.

```
$ time aws --no-sign-request s3 ls static-rust-lang-org/dist/ | wc -l
61253

real	0m45.545s
user	0m21.830s
sys	0m1.977s

$ time aws --no-sign-request s3 ls static-rust-lang-org/dist/2019-09-02/ | wc -l
1998

real	0m4.342s
user	0m1.495s
sys	0m0.143s
```

**Comment by jethrogb** [comment]
@SimonSapin I had written this limitation:
> * listing all objects using the AWS S3 List Objects API takes a very long time because you'll be rate-limited after a few requests
I don't remember exactly what I was trying to do here but it's not clear to me why you're not running into the same issue.

**Comment by SimonSapin** [comment]
45 seconds for this feels like a very long time to me. When I don’t pipe the output it seems to come in bursts. Maybe the cli tool rate-limits itself.

**Comment by jethrogb** [comment]
> 45 seconds for this feels like a very long time to me.

True, but the way I was remembering it, it was in the minutes or tens of minutes.

**Comment by Mark-Simulacrum** [comment]
So, to be clear, the list command there is issuing hundreds or thousands of API queries so it'll likely be slow -- the solution here is to use the S3 Inventory API but no one has gotten around to implementing that just yet. 

Part of the reason why is that no super solid reasons for wanting to list objects in the _whole_ bucket have been provided yet; we do have index.html (which internally uses list API, via JS, IIRC) in each subdirectory of the static.rust-lang.org bucket.

**Comment by jethrogb** [comment]
The full list is needed to know all nightlies that exist, e.g. for bisecting.

**Comment by Mark-Simulacrum** [comment]
Both bisection tools that I've written simply run forwards by single-day increments after binary search hits a spot if they can't download nightlies which works well.

Is there any need for _all_ the files to be included? If it's just the top-level directory list so to speak then we can probably add that at fairly low implementation cost since it's append-only and such...

**Comment by jethrogb** [comment]
I just need an index of all `channel-rust-XYZ.toml` files that exist, and I think that should be sufficient for must users. Note that `XYZ` may be a channel name (beta, nightly) or a version number (stable).

**Comment by Mark-Simulacrum** [comment]
Okay, I'll put that on my agenda for this week or so to investigate and see if we can provide that relatively easily, and if so start doing so.

**Comment by Mark-Simulacrum** [comment]
As a quick update I've internally setup weekly inventories of static.rust-lang.org and will check back in a couple days (AWS indicates we should get the first one in ~48 hours).

**Comment by andrewchambers** [comment]
Guys you need tarballs so people packaging rust can download rust source code. The archives on github don't have the vendor directory. I can't understand the reason you can't generate single html file listing releases.

**Comment by Mark-Simulacrum** [comment]
Source tarballs, among others, are published for all releases to static.rust-lang.org.

https://manifests.rust-lang.org/manifests.txt is what I've come up with to hopefully satisfy @jethrogb's demands at least. Note that the format here is unstable, and we may stop updating this / remove it / etc at any time. It currently contains all nightly, beta, and stable manifests in the static.rust-lang.org/dist/{date}/ directories, which should be sufficient for essentially all use cases. Beyond that, let me know if additional information or a reworking of the format would be useful, by filing an issue at https://github.com/rust-lang/generate-manifest-list/.

**Comment by jethrogb** [comment]
> @jethrogb's demands
I like to think of them as request :smile: 

I think the stable manifests are missing.

**Comment by andrewchambers** [comment]
@Mark-Simulacrum the link you posted is not valid.

**Comment by Mark-Simulacrum** [comment]
Ah, we've since decided we don't need a separate domain, so it should be semi-permanently at https://static.rust-lang.org/manifests.txt now. 

I can't find any links to the source tarballs right now (we should add them to https://forge.rust-lang.org/infra/other-installation-methods.html, feel free to file a PR at https://github.com/rust-lang/rust-forge/); but they are published. For example, https://static.rust-lang.org/dist/2019-09-15/rustc-nightly-src.tar.gz or https://static.rust-lang.org/dist/2019-08-15/rustc-1.37.0-src.tar.xz.

**Comment by andrewchambers** [comment]
Note, those rustc tarballs don't have dependencies included, which seems to be a big oversight to me.
