### ISSUE TITLE
region tests incorrectly passing with NLL enabled

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#56993]
The following tests pass under NLL, but ought not to (in some cases, light editing is required to observe that):

- [`ui/regions/regions-assoc-type-in-supertrait-outlives-container.rs`](https://github.com/rust-lang/rust/blob/master/src/test/ui/regions/regions-assoc-type-in-supertrait-outlives-container.rs), [modified variant](https://gist.github.com/nikomatsakis/71755772d41d86daa871a6acc52b506d)
- [`ui/regions/regions-free-region-ordering-caller.rs`](https://github.com/rust-lang/rust/blob/master/src/test/ui/regions/regions-free-region-ordering-caller.rs)
- [`ui/regions/regions-outlives-projection-container-wc.rs`](https://github.com/rust-lang/rust/blob/master/src/test/ui/regions/regions-outlives-projection-container-wc.rs)
- [`ui/regions/regions-outlives-projection-container-hrtb.rs`](https://github.com/rust-lang/rust/blob/master/src/test/ui/regions/regions-outlives-projection-container-hrtb.rs)

To observe the problems, though, you need to run in true NLL mode (i.e., `#![feature(nll)]` or `-Zborrowck=mir`). In migration mode, the lexical borrow checker still reports the errors in question.

**Comment by matthewjasper** [comment]
This appear to have regressed between nightly-2018-10-24 and nightly-2018-10-26

**Comment by matthewjasper** [comment]
These tests are now properly tested with NLL enabled using revisions. Once migrate mode is the default we can switch compare mode to use `-Zborrowck=mir` and close this issue.
