### ISSUE TITLE
New Rust 2018 macro use syntax force the need to add internal macros (if the used macro require them)

### ISSUE THREAD

**Issue by robmv** [rust-lang/rust#57013]
When adding a `use` for an external crate macro, that references other macros, the compiler force to add all internal macros, for example, using the [error-chain](https://crates.io/crates/error-chain) crate

```rust
use error_chain::error_chain;

error_chain! {
    foreign_links {
        IO(std::io::Error);
    }
}
```
The following error is shown:

```
error: cannot find macro `error_chain_processing!` in this scope
```
The only way to fix this is to add all macros to the macro use:

```rust
use error_chain::{error_chain, error_chain_processing, impl_error_chain_kind, impl_error_chain_processed, impl_extract_backtrace, ChainedError};
```
Many of these macros are not for external use, so this new Rust 2018 syntax makes these more verbose, exposing internal names to the crate client code. Using a wildcard like:

```rust
use error_chain::*
```
works, but pollutes the client namespace importing everything. The old `#[macro_use]` at least only imported macros

Note: Related to #25003

**Comment by steveklabnik** [comment]
The fix is for `error_chain` to do this: https://doc.rust-lang.org/edition-guide/rust-2018/macros/macro-changes.html#local-helper-macros

Since this isn't a bug, and we already have a feature to address it, I'm going to give it a close!
