### ISSUE TITLE
attempting to address path clarity warnings for 2018 edition with StructOpt macro led to ICE

### ISSUE THREAD

**Issue by ashleygwilliams** [rust-lang/rust#57015]
**the code i tried:** 
- https://github.com/ashleygwilliams/cargo-generate/pull/135
- noticed there was a typo, fixed it, still getting an ICE https://github.com/ashleygwilliams/cargo-generate/pull/136

**i expected:** 
- cargo-generate/pull/135, to not compile and give an error about `structStructOpt` typo
- cargo-generate/pull/136, to compile (and no longer display 2018 warnings about path clarity)

**instead, what happened:**

```
Compiling cargo-generate v0.2.1 (/Users/ag_dubs/rust/cargo-generate)
thread 'main' panicked at 'assertion failed: directive.imported_module.get().is_none()', src/librustc_resolve/resolve_imports.rs:892:21
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.33.0-nightly (790f4c566 2018-12-19) running on x86_64-apple-darwin

note: compiler flags: -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

error: Could not compile `cargo-generate`.
```

system info:
```
Ashleys-MacBook-Pro-2:cargo-generate ag_dubs$ rustc --version --verbose
rustc 1.33.0-nightly (790f4c566 2018-12-19)
binary: rustc
commit-hash: 790f4c566d9802dfcadc26398dde2051cfe6ec9f
commit-date: 2018-12-19
host: x86_64-apple-darwin
release: 1.33.0-nightly
LLVM version: 8.0
```

**Comment by ashleygwilliams** [comment]
i also get this on stable and earlier nightlies, if that is at all useful.

**Comment by ashleygwilliams** [comment]
(also please feel free to let me know if i can provide any more info- this is my first time filing a compiler bug! thanks for all your hardwork and help <3)

**Comment by nikomatsakis** [comment]
Nominating -- we should keep focus on Rust 2018-related bugs like this, I think.

**Comment by nikomatsakis** [comment]
@ashleygwilliams 

> i expected: it to compile

Did you? I mean, there is a typo, right? Do you mean, you expected a controller error?

Specifically I see this in the diff:

>   #[derive(structStructOpt)] 

and I think it should be `StructOpt`?

**Comment by nikomatsakis** [comment]
I guess you are saying you get the same ICE from https://github.com/ashleygwilliams/cargo-generate/pull/136/files, which has a fix... did you try a cargo clean?

(I'm wondering if it is related to incremental compilation.)

**Comment by ashleygwilliams** [comment]
yeah, so i noticed the typo, and then fixed it (hence the 2 PRs- i included both on the offchance that there were 2 issues.) i expected the 2nd one to compile, and the first one (after i noticed the typo, to not compile but give an error re: the typo).

i will run a cargo clean and see if it helps!

**Comment by nikomatsakis** [comment]
OK, thanks for the clarification.

**Comment by ashleygwilliams** [comment]
just ran `cargo clean` and have the same error message.

**Comment by petrochenkov** [comment]
Fixed in https://github.com/rust-lang/rust/pull/57185
