### ISSUE TITLE
开发工具欠缺太多， 开发体验太差

### ISSUE THREAD

**Issue by roadhub** [rust-lang/rust#57072]
1. 对新手太不友好，安装完成后还得一大堆配置，就不能一次性配置好吗，还要我自己去安装各种组件，我哪知道哪个组件是干嘛的
2. 我也不知道这是为何， 不定时出现，
```curl: (35) LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to sh.rustup.rs:443```
3. 文档不完善，尤其是对新手来说，入门存在巨大障碍，希望能改进

**Comment by ishitatsuyuki** [comment]
Please use only English on the issue tracker. If you have any questions, go to your local forum or users.rust-lang.org (English only).
请不要在这里问问题。Issues仅限bug或者feature request，而且需要有具体性。

1. 最低需要的组件都是一次性安装的。其他组件一般都会IDE提示你安装。
2. 你被墙了
3. Rust属于比较高级和复杂的语言，我们知道，所以我们不断的在改进文档。The Rust Programming Language算是官方入门文档，如果你不精通英语，推荐你找一个翻译版。
