### ISSUE TITLE
[rustdoc] Incorrent links in sidebar for same name methods

### ISSUE THREAD

**Issue by shalzz** [rust-lang/rust#57093]
rustdoc links to the first method for same name methods in the sidebar

For example in the sidebar for https://doc.rust-lang.org/std/vec/struct.Vec.html
the `len` method below the `Methods from Deref<Target = [T]>` section
links to https://doc.rust-lang.org/std/vec/struct.Vec.html#method.len
when it should link to https://doc.rust-lang.org/std/vec/struct.Vec.html#method.len-1

This seems like same as issue #25001 but the fix isn't applied to the sidebar as well.

**Comment by GuillaumeGomez** [comment]
This is working on stable so I'm closing it.
