### ISSUE TITLE
Support for PowerPC/PowerPC64 on FreeBSD

### ISSUE THREAD

**Issue by lenoil98** [rust-lang/rust#57112]
Since there's native support in rust for PowerPC on Linux and NetBSD.  Would it be difficult to add support for PowerPC/PowerPC64 on FreeBSD?

**Comment by glaubitz** [comment]
Yes, it should be fairly easy to add FreeBSD support for ppc, ppc64 and sparc64 unless there are any peculiarities in the FreeBSD ABI that I'm unaware of. I can have a go at this.

**Comment by lenoil98** [comment]
Great! I will help where I can.  I've already started working on the target spec for ppc and ppc64.  I used the Linux and NetBSD files as guides.  Not sure if they're correct.

**Comment by lenoil98** [comment]
Great! I will help where I can.

**Comment by lenoil98** [comment]
Using the powerpc and powerpc64 spec files from Linux and NetBSD, I created the below spec file for FreeBSD.

file:///usr/ports/tmp/mrustc/rustc-1.19.0-src/src/librustc_back/target/powerpc64_unknown_freebsd.rs

**Comment by lenoil98** [comment]
Here's a spec files I created for FreeBSD.

**Comment by lenoil98** [comment]
I've  created spec files for FreeBSD.

// Copyright 2018 The Rust Project Developers. See the COPYRIGHT
// file at the top-level directory of this distribution and at
// http://rust-lang.org/COPYRIGHT.
//
// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
// option. This file may not be copied, modified, or distributed
// except according to those terms.

use spec::{LinkerFlavor, Target, TargetResult};

pub fn target() -> TargetResult {
    let mut base = super::freebsd_base::opts();
    base.cpu = "ppc64".to_string();
    base.pre_link_args.get_mut(&LinkerFlavor::Gcc).unwrap().push("-m64".to_string());
    base.max_atomic_width = Some(64);

    Ok(Target {
        llvm_target: "powerpc64-unknown-freebsd".to_string(),
        target_endian: "big".to_string(),
        target_pointer_width: "64".to_string(),
        target_c_int_width: "32".to_string(),
        data_layout: "E-m:e-i64:64-n32:64".to_string(),
        arch: "powerpc64".to_string(),
        target_os: "freebsd".to_string(),
        target_env: "".to_string(),
        target_vendor: "unknown".to_string(),
        linker_flavor: LinkerFlavor::Gcc,
        options: base,
    })
}

// Copyright 2018 The Rust Project Developers. See the COPYRIGHT
// file at the top-level directory of this distribution and at
// http://rust-lang.org/COPYRIGHT.
//
// Licensed under the Apache License, Version 2.0 <LICENSE-APACHE or
// http://www.apache.org/licenses/LICENSE-2.0> or the MIT license
// <LICENSE-MIT or http://opensource.org/licenses/MIT>, at your
// option. This file may not be copied, modified, or distributed
// except according to those terms.

use spec::{LinkerFlavor, Target, TargetResult};

pub fn target() -> TargetResult {
    let mut base = super::freebsd_base::opts();
    base.pre_link_args.get_mut(&LinkerFlavor::Gcc).unwrap().push("-m32".to_string());
    base.max_atomic_width = Some(32);

    Ok(Target {
        llvm_target: "powerpc-unknown-freebsd".to_string(),
        target_endian: "big".to_string(),
        target_pointer_width: "32".to_string(),
        target_c_int_width: "32".to_string(),
        data_layout: "E-m:e-p:32:32-i64:64-n32".to_string(),
        arch: "powerpc".to_string(),
        target_os: "freebsd".to_string(),
        target_env: String::new(),
        target_vendor: "unknown".to_string(),
        linker_flavor: LinkerFlavor::Gcc,
        options: base,
    })
}

**Comment by glaubitz** [comment]
@lenoil98 Has this target been added now?

**Comment by lenoil98** [comment]
I must have inadvertently closed this.  However, attached are changed to add support for powerpc64 on FreeBSD.

[patch-ppc64.txt](https://github.com/rust-lang/rust/files/2751202/patch-ppc64.txt)

**Comment by goosnarrggh** [comment]
I see that ppc64 support was added, and it is actually available now for ppc64 ELFv1 ABI (FreeBSD 12.x), and both ppc64 and ppc64le ELFv2 ABI (soon-to-be-released FreeBSD 13).

How far has anyone made it with bringing up support for 32-bit ppc, on either FreeBSD 12.x (with gcc 4.2 in the base system, and thus probably relying on a newer gcc/llvm compiled from source code via the ports), or else FreeBSD 13 (with llvm in the base system)?

If someone (perhaps me) were to volunteer to continue working on such a project, what next steps would be required?

**Comment by barracuda156** [comment]
@goosnarrggh Have you gotten anywhere with Rust for ppc?
