### ISSUE TITLE
Tracking issue for Option::copied

### ISSUE THREAD

**Issue by xfix** [rust-lang/rust#57126]
This is a tracking issue for `Option::copied`.

Added in #56534. Feature gate: `#![feature(copied)]`.

Related feature: `iter_copied` in #57127.

**Comment by pmarcelll** [comment]
Did you mean `Option::copied` in the first sentence?

**Comment by xfix** [comment]
@pmarcelll Fixed.

**Comment by Centril** [comment]
So we added a newtype `Copied` because that's what we usually do. However, in this case, we could simply reuse `Cloned` and implement copied as:
```rust
fn copied<'a, T>(self) -> Cloned<Self> where
    Self: Iterator<Item = &'a T>,
    T: 'a + Copy, 
```

Are there notable reasons not to do this that I'm missing? Doing so would substantially decrease the cost of this feature for the standard library.

**Comment by xfix** [comment]
`Cloned` type wouldn't have the guarantees that `Copied` does, as it calls the `clone` method, which can have side-effects (it shouldn't, but it's not something we can depend on).

**Comment by xfix** [comment]
See #57970.

**Comment by SimonSapin** [comment]
The comment about the `Copied` type belongs in https://github.com/rust-lang/rust/issues/57127. Since I see no objection to `Option::copied`:

@rfcbot fcp merge

**Comment by matklad** [comment]
Am I correct that this now awaits for a stabilization PR?

**Comment by SimonSapin** [comment]
Yes.

**Comment by matklad** [comment]
Stabilization PR is up: #59231
