### ISSUE TITLE
Tracking issue for Iterator::copied

### ISSUE THREAD

**Issue by xfix** [rust-lang/rust#57127]
This is a tracking issue for Iterator::copied.

Added in #56534. Feature gate: `#![feature(iter_copied)]`.

Related feature: `copied` in #57126.

**Comment by SimonSapin** [comment]
@Centril, do you feel your comment in https://github.com/rust-lang/rust/issues/57126#issuecomment-458314544 is still an objection to the state of this feature, given the response in https://github.com/rust-lang/rust/issues/57126#issuecomment-458502921?

**Comment by Centril** [comment]
@SimonSapin So ultimately, https://github.com/rust-lang/rust/pull/57970 was closed meaning that we are comfortable with the specialization. If that specialization is always in place then `Copied` is a redundant type (and the impls that come with it are also redundant). However, keeping the cost and the `Copied` type also has less of a risk attached to it so there's a trade-off here. I don't know what the right choice is, but those are the facts as I see them.

**Comment by hellow554** [comment]
@xfix 

> This is a tracking issue for Iterator::cloned.

Should be \`Iterator::copied'` :)

**Comment by xfix** [comment]
@hellow554 Fixed.

**Comment by xfix** [comment]
For reference, `.map(|&x| x)` pattern is quite common according to https://codesearch.aelve.com/rust/search?query=%5C.%5Cs*map%5Cs*%5C(%5Cs*%5C%7C%5Cs*(%3F%3A%26%5Cs*%5Cw%2B%5Cs*%5C%7C%5Cs*%5C%7B%3F%5Cs*%5Cw%2B%7C%5Cw%2B%5Cs*%5C%7C%5Cs*%5C%7B%3F%5Cs*%5C*%5Cs*%5Cw%2B)%5Cs*%5C%7D%3F%5Cs*%5C)&insensitive=off&space=off&precise=off&sources=on

**Comment by Manishearth** [comment]
@Centril Is there anything blocking stabilization here? We'd like to suggest this in Clippy, see https://github.com/rust-lang/rust-clippy/issues/3958

(The crux is that `.copied()` is clearer than `.map(|&x| x)`, but `.cloned()` gives off the wrong impression)

**Comment by Centril** [comment]
@Manishearth That's not my call... =D

Picking random libs member... @sfackler is there anything blocking stabilization here?

**Comment by sfackler** [comment]
Doesn't seem like it.

@rfcbot fcp merge
