### ISSUE TITLE
Nightly broken with pear_codegen ( & rocket ? )

### ISSUE THREAD

**Issue by Asone** [rust-lang/rust#57120]
Hi,

## version information 
```
rustup 1.16.0 (beab5ac2b 2018-12-06)
cargo 1.33.0-nightly (2cf1f5dda 2018-12-11)
rustc 1.33.0-nightly (ddab10a69 2018-12-23)
```

## description of bug

Lately in a rust project it seems our pipe has broken with last versions of rust nightly, Rocket and Pear_codegen. 

After a few research it seems we have a problem kind of similar with the [following issue](https://github.com/SergioBenitez/Rocket/issues/507) which attributed the break to rust nightly so i open up the issue here. If i'm wrong feel free to close the issue. 

I've tried to build up a docker container with the same parameters used in the pipe and get the same problem. 

Here's the stacktrace : 

```
error[E0599]: no variant named `concat` found for type `syntax::tokenstream::TokenStream` in the current scope
   --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/pear_codegen-0.0.20/src/lib.rs:330:54
    |
330 |                 mac.node.tts = ThinTokenStream::from(TokenStream::concat(streams));
    |                                                      ^^^^^^^^^^^^^^^^^^^ variant not found in `syntax::tokenstream::TokenStream`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: Could not compile `pear_codegen`.
```

you can check the pipe and errors more in details [here](https://framagit.org/tricoteuses/tricoteuses-api-assemblee/-/jobs/293879) for a specific build and [here](https://framagit.org/tricoteuses/tricoteuses-api-assemblee/pipelines) for the history of builds. 

I've been checking [this file]() as it seemed referenced in the stacktrace :
```
/usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/pear_codegen-0.0.20/src/lib.rs:330:54
```

However the file doesn't seem to be the right one as there is no line n°330.  

Unfortunately my knowledge of rust is not extended enough to provide with deeper knowledge of the bug. If there's any additional information that you need me to provide, please feel free to notify me. 

Also, any explanation to understand how this happens/how to fix that kind of issues is welcome in order to give help if i can. 

Thank you. 

P.S : i'll open a similar issue on pear repo in order to notify of the bug and get it fixed if it comes from there.

**Comment by Aaron1011** [comment]
`TokenStream::concat` appears to have been renamed to `TokenStream::new` in commit https://github.com/rust-lang/rust/commit/e80c7ddb05ee584c12131a4713173a3eafc49f4a

**Comment by Asone** [comment]
as per @jebrosen recommended, the project has been updated to rocket 0.4. 

I close the current ticket as it is not fixable itself and our pipeline is effective with the new version of rocket. 

Thanks for the quick answers !

Much datalove !
