### ISSUE TITLE
Clone derive documentation is inconsistent

### ISSUE THREAD

**Issue by doitian** [rust-lang/rust#57123]
https://github.com/rust-lang/rust/blob/27c4335287c62d0a343c6103a69c4c742ce44c0e/src/libcore/clone.rs#L73

> the standard library only implements `Clone` up until arrays of size 32

https://github.com/rust-lang/rust/blob/27c4335287c62d0a343c6103a69c4c742ce44c0e/src/libcore/clone.rs#L98

> Array types, for all sizes, if the item type also implements `Clone` (e.g., `[i32; 123456]`)

Playground example:

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=3341d51ba6dc6be3f1652fee12dd4835

**Comment by Centril** [comment]
@doitian Could you file a PR fixing the inconsistency?

**Comment by u2** [comment]
https://github.com/u2/test_clone

**Comment by doitian** [comment]
Close it since #57125 is merged.
