### ISSUE TITLE
Why does save-analysis use it's own syntax?

### ISSUE THREAD

**Issue by jendrikw** [rust-lang/rust#57136]
In the save-analysis file of liballoc, the value/signature of https://github.com/rust-lang/rust/blob/14b96659e4e9b2f31431df48f47c219957e2666a/src/liballoc/task.rs#L98 looks like this: `fn <W> (wake: Arc<W>) -> LocalWaker`, which is not valid rust code.

There is little documentation available for the save-analysis, but as far as I understood it, the `value` field is supposed to represent the signature. In most other languages, the signature of a function doesn't include the parameter names.

For consistency, I think it would be better if the field would either include the function name or leave of the parameter names.

Edit: I want this to be able to parse the string with syn, which expects either a name for the function or no names for the arguments.

**Comment by jendrikw** [comment]
I know, but the function name `local_waker` is missing from the string, so it's impossible to parse it.

**Comment by csmoe** [comment]
@jendrikw oops, I misunderstood your comments, sorry.

**Comment by steveklabnik** [comment]
Triage: a long time later, save-analysis is eventually on the way out, and so this might just be moot.

**Comment by marmeladema** [comment]
I think its been fixed by https://github.com/rust-lang/rust/pull/73155 at least for function signature as this issue is about. I can probably be closed.
cc @Xanewok

**Comment by jyn514** [comment]
Save-analysis has been [removed from the compiler](https://github.com/rust-lang/rust/pull/101841).
