### ISSUE TITLE
Incorrect UX for back navigation after search in docs

### ISSUE THREAD

**Issue by mqudsi** [rust-lang/rust#57135]
The UX for navigating after a search in the documentation in incorrect. Upon searching in the documentation, the search takes over the contents of the current page, i.e. it is not displayed in a lightbox or pop-up div. In this case, the use of the back navigation button should act as exiting the search and returning to the page in the documentation that the user was on prior to triggering the search feature.

In practice, using the back button goes back to the *2nd to last* page the user was on before triggering search, and a backwards-then-forwards double navigation is required to end up on the page that the user was on before search.

The solution is to use the history push state api to add an entry to the backwards navigation stack that would return the user to the last-viewed page upon triggering the search after clicking the backwards navigation button.

(Yes, I am aware that it is possible to close the search box and go back to the last page via other means. The point is that the content of the window act as if a full navigation has taken place, in which case the most natural means of returning to the original content for the user is to press the back button and not escape, etc.)

**Comment by ecstatic-morse** [comment]
This feature is [already implemented](https://github.com/rust-lang/rust/blob/8e2063d02062ee9f088274690a97826333847e17/src/librustdoc/html/static/main.js#L1522-L1528) and works as described on Firefox 64. Perhaps the author's browser doesn't support the history API or feature detection is not working correctly.

**Comment by GuillaumeGomez** [comment]
It's not working the same way on `file://` urls but it should indeed.

**Comment by GuillaumeGomez** [comment]
Here's the PR for reference: https://github.com/rust-lang/rust/pull/28400

**Comment by mqudsi** [comment]
Yes, I was working with locally compiled documentation.

**Comment by mqudsi** [comment]
Fwiw; I believe the correct solution here is to trigger an actual Page navigation upon search, such that use of the history api not needed.

**Comment by GuillaumeGomez** [comment]
@mqudsi: You don't want that. In case you're looking for an element on the current page, it'll reload the whole page, which isn't very nice. I tested to ren-enable the history management locally with `file://` and it seemed to work so I'll send a PR for it.

**Comment by mqudsi** [comment]
@GuillaumeGomez I mean only when search has already taken over the page (so the contents are completely hidden and navigation or ajax manipulation looks the same). Remember this is local, so there is no network-associated delay.

**Comment by GuillaumeGomez** [comment]
Try the iterator trait page locally. :smiling_imp:
