### ISSUE TITLE
rustbuilds rebuilds libstd even when it did not change [recent regression]

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#57142]
For just a few weeks now, I am seeing many cases where rustbuild rebuilds stage 0 libstd (and hence rebuilds *everything*) even though nothing changed there.  I have not yet tried to reproduce this in a clean dir (that would take forever due to all the rebuilding), but the steps are roughly as follows:

* Start with a clean dir
* `./x.py --stage 0 build src/librustc`
* `./x.py --stage 0 build src/librustc`

The last step will rebuild everything even though nothing changed.

The timing coincides a little with libstd depending on crates io, but that could be mere coincidence.

Cc @alexcrichton

**Comment by RalfJung** [comment]
Hm, I tried in a clean dir and cannot reproduce. I could have sworn I saw this multiple times. I'll reopen if I can reproduce later.

**Comment by petrochenkov** [comment]
I see this too, it doesn't reproduce with clean build.
You need to
- Run `./x.py test --bless --stage 1 src/test/ui --test-args something`
- Make some changes to libcore or liballoc (?), not necessarily yourself, but for example by rebasing on master.
- Run `./x.py test --bless --stage 1 src/test/ui --test-args something` again.
- Run `./x.py test --bless --stage 1 src/test/ui --test-args something` again, which should be no-op, but it will actually start building almost everything starting with liballoc.

**Comment by petrochenkov** [comment]
I have confirmed that it's indeed caused by touching libcore.

**Comment by ehuss** [comment]
This has been bugging me, too.  I bisected the regression to #56092.  cc @alexcrichton.  I don't fully understand why, but for some reason Cargo thinks that one of liballoc's dependencies has changed, but I don't see any of them being different.  I'll keep poking to better understand why the fingerprint check is failing.

The following is a relatively quick repro:
`touch src/libcore/lib.rs ; ./x.py build src/libstd --stage=0 ; ./x.py build src/libstd --stage=0`
The second build should be fresh, but it isn't.
