### ISSUE TITLE
rustup: 1.31.1 cannot be updated to via rustup on macos

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#57148]
Similar issue to https://github.com/rust-lang/rust/issues/57111 affects 1.31.1. Running rustup update fails to update the stable version of the compiler on my macos VM.

```
$ rustup update
info: syncing channel updates for 'stable-x86_64-apple-darwin'
info: latest update on 2018-12-20, rust version 1.31.1 (b6c32da9b 2018-12-18)
info: downloading component 'rustc'
 62.6 MiB /  62.6 MiB (100 %)   9.0 MiB/s ETA:   0 s                
info: downloading component 'rust-std'
 49.0 MiB /  49.0 MiB (100 %)   8.7 MiB/s ETA:   0 s                
info: downloading component 'cargo'
info: downloading component 'rust-docs'
info: installing component 'rustc'
info: installing component 'rust-std'
info: installing component 'cargo'
info: installing component 'rust-docs'
info: rolling back changes
error: could not rename component file from '/Users/nagisa/.rustup/tmp/u_96yv_zujys157v_dir/bk' to '/Users/nagisa/.rustup/toolchains/stable-x86_64-apple-darwin/share/man'
error: could not rename component file from '/Users/nagisa/.rustup/tmp/grcxr4i_29ol40_4_dir/bk' to '/Users/nagisa/.rustup/toolchains/stable-x86_64-apple-darwin/share/zsh'
error: could not rename component file from '/Users/nagisa/.rustup/tmp/pm8pirnch2ibpwx0_dir/bk' to '/Users/nagisa/.rustup/toolchains/stable-x86_64-apple-darwin/etc'
error: could not rename component file from '/Users/nagisa/.rustup/tmp/u3d1ccpi5umjpke6_dir/bk' to '/Users/nagisa/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin'
error: failed to install component: 'rust-docs-x86_64-apple-darwin', detected conflict: '"share/doc/rust/html"'
```

On my linux machine no such problem could be reproduced.

**Comment by clemensw** [comment]
Had no problem on mac, but similar problem on Linux for 1.31.1:
$ rustup update stable
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: latest update on 2018-12-20, rust version 1.31.1 (b6c32da9b 2018-12-18)
info: downloading component 'rustc'
info: downloading component 'rust-std'
info: downloading component 'cargo'
info: downloading component 'rust-docs'
info: downloading component 'rust-analysis'
info: downloading component 'rls'
info: downloading component 'rustfmt'
info: downloading component 'rust-std' for 'asmjs-unknown-emscripten'
info: downloading component 'rust-src'
info: downloading component 'rust-std' for 'x86_64-unknown-linux-musl'
info: removing component 'rustc'
info: removing component 'rust-std'
info: removing component 'cargo'
info: removing component 'rust-docs'
info: removing component 'rust-analysis'
info: removing component 'rls'
info: removing component 'rustfmt'
info: removing component 'rust-std' for 'asmjs-unknown-emscripten'
info: removing component 'rust-src'
info: removing component 'rust-std' for 'x86_64-unknown-linux-musl'
info: installing component 'rustc'
info: rolling back changes
error: could not rename component file from '/home/clemens/.rustup/tmp/e2fw89j1wnis7cen_dir/bk' to '/home/clemens/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/share'
error: could not rename component file from '/home/clemens/.rustup/tmp/sm6nmf9auvwl_19d_dir/bk' to '/home/clemens/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/share/doc'
error: could not rename component file from '/home/clemens/.rustup/tmp/w6cn8xkriiy5yc07_dir/bk' to '/home/clemens/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu'
error: could not rename component file from '/home/clemens/.rustup/tmp/57a8mdwnj29qz900_dir/bk' to '/home/clemens/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/share/man'
error: failed to install component: 'rustc-x86_64-unknown-linux-gnu', detected conflict: '"lib/librustc-c0b0e3599e0c7f59.so"'

**Comment by Mark-Simulacrum** [comment]
I seem to have been able to update...

```
info: syncing channel updates for 'stable-x86_64-apple-darwin'
info: latest update on 2018-12-20, rust version 1.31.1 (b6c32da9b 2018-12-18)
info: downloading component 'rustc'
 62.6 MiB /  62.6 MiB (100 %)  14.7 MiB/s ETA:   0 s
info: downloading component 'rust-std'
 49.0 MiB /  49.0 MiB (100 %)  14.9 MiB/s ETA:   0 s
info: downloading component 'cargo'
info: downloading component 'rust-docs'
info: downloading component 'rustfmt'
info: removing component 'rustc'
info: removing component 'rust-std'
info: removing component 'cargo'
info: removing component 'rust-docs'
info: removing component 'rustfmt'
info: installing component 'rustc'
info: installing component 'rust-std'
info: installing component 'cargo'
info: installing component 'rust-docs'
info: installing component 'rustfmt'

  stable-x86_64-apple-darwin updated - rustc 1.31.1 (b6c32da9b 2018-12-18)
```

**Comment by nagisa** [comment]
So at least the problem is reproducible, lmk if you need any other specific info to reproduce.

**Comment by Mark-Simulacrum** [comment]
Hm, okay -- unfortunately I am not on zfs so a similar rollback scheme wouldn't work here. I'm not sure what information would be needed additionally... the PR that caused the failure on nightly is almost certainly not the problem here as it's too recent (merged ~3 days ago)...

**Comment by nagisa** [comment]
From the output it feels like the root cause is the missing "removing component" part of the upgrade process.

**Comment by Mark-Simulacrum** [comment]
I'm going to go ahead and close this as I suspect it's *extremely* rare that this happens given that we haven't had other reports, if it is still a bug. Regardless it's probably in rustup, not the packaging scripts themselves, so should be filed there.
