### ISSUE TITLE
rustdoc: [src] link missing for data types

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#57143]
When looking at data types (for example [this one](https://doc.rust-lang.org/nightly/nightly-rustc/rustc/mir/struct.BasicBlock.html)) there used to be a [src] link to jump to the definition of the type.  That link is no longer there.  It would be great to have it back!

**Comment by GuillaumeGomez** [comment]
That's because it's defined inside a macro: https://doc.rust-lang.org/nightly/nightly-rustc/src/rustc/mir/mod.rs.html#997

I guess we can clone then?

**Comment by RalfJung** [comment]
Hm, I feel rustdoc could still do a better job -- like, it could point at the macro invocation.
