### ISSUE TITLE
Procedural macros book?

### ISSUE THREAD

**Issue by alexreg** [rust-lang/rust#57172]
With the proliferation of books on various topics within Rust (as well as larger 3rd party libs), I was thinking the community would really benefit from a book on the now reasonably mature feature of procedural macros. I've gotten positive feedback to the idea when I've brought it up, but I'd be curious to hear what the proc macro guys and docs team think of it. It would be a bit of effort to get this off the ground, but well worth it in the end, I feel.

CC @alexcrichton @dtolnay

**Comment by steveklabnik** [comment]
Discussion questions like this are best suited for internals.rust-lang.org. Thanks!
