### ISSUE TITLE
`rustc_layout_scalar_valid_range_start` doesn't prevent `unused_unsafe` lint

### ISSUE THREAD

**Issue by varkor** [rust-lang/rust#57183]
Edit: this is just a stage 0 problem, so we can conditionally ignore those warnings for now.

---

`rustc_layout_scalar_valid_range_start` requires `unsafe`, but does not cause `unsafe` blocks to be counted as "used", meaning that the following:
https://github.com/rust-lang/rust/blob/3cda631ea45bac643ed9e4968f9292b0244a5b82/src/libcore/num/mod.rs#L71
is warned as unused, but removing the `unsafe` causes an error.

**Comment by varkor** [comment]
Another issue is that `rustc_layout_scalar_valid_range_start` attributes are also considered unused when they are not.

**Comment by pietroalbini** [comment]
Why is this closed? It's still present (encountered it during beta promotion).

**Comment by pietroalbini** [comment]
Not on the beta itself, apparently.

**Comment by oli-obk** [comment]
That issue is really tracked in https://github.com/rust-lang/rust/issues/57178
