### ISSUE TITLE
macro_rules macros that expand to proc_macro invocations produce wrong hygiene information.

### ISSUE THREAD

**Issue by CensoredUsername** [rust-lang/rust#57207]
When a macro_rules! macro expands to a proc_macro invocation, the proc_macro is handed invalid hygiene info when the $:expr matcher was used to forward tokens.

I've prepared a minimal test case in https://github.com/CensoredUsername/proc_macro_hygiene. Simply compile the normal_macro crate in there to produce the given error.

I expected to see this happen: This project should compile without errors.

Instead, this happened: an error is produced indicating that the passed through local variable cannot be found in the scope of the macro.

## Meta

This requires `#![feature(proc_macro_hygiene)]` due to the proc_macro being used in expression context.

`rustc --version --verbose`:

rustc 1.33.0-nightly (59183180f 2018-12-29)
binary: rustc
commit-hash: 59183180f718fc2212828e180f2f856f0db1bb9c
commit-date: 2018-12-29
host: x86_64-pc-windows-msvc
release: 1.33.0-nightly
LLVM version: 8.0

**Comment by dtolnay** [comment]
The compiler has no way to convert $:expr to TokenStream while preserving spans, which is the core issue tracked in #43081. Closing as #43081 is sufficient for tracking this problem.
