### ISSUE TITLE
cargo fix --edition-idioms tackles macro twice

### ISSUE THREAD

**Issue by richo** [rust-lang/rust#57211]
Sorry if this is already reported, I couldn't find it in the tracker.

This was the easiest case for me to repro, but obviously it could be minimized further to any type with a hidden lifetime param.

```rust
macro_rules! bug {
    ($struct:ident) => {
        impl std::fmt::Debug for $struct {
            fn fmt(&self, fmt: &mut std::fmt::Formatter) -> std::fmt::Result {
                fmt.debug_struct(stringify!($struct))
                    .field("token", &"...")
                    .finish()
            }
        }
    };
}

struct Sensitive {
    token: String,
}
bug!(Sensitive);

struct Other {
    token: String,
}
bug!(Other);
```

from inspecting the output of `--broken-code`, cargo fix is adding the lifetime param once for each invocation of the macro.

**Comment by ehuss** [comment]
I believe this is #55768.

**Comment by richo** [comment]
So it is! Amusing that our usecases were identical.
