### ISSUE TITLE
Error help msg when attempting usage of ~ as unary operator misleading

### ISSUE THREAD

**Issue by tcullum-gpsw** [rust-lang/rust#57239]
I find the error message confusing and possibly incorrect when attempting to use `~` as a unary operator:

In current Rust stable and nightly, I get:

```
error: `~` cannot be used as a unary operator
 --> src/main.rs:5:11
  |
5 |     num = ~num + 1;
  |           ^ help: use `!` to perform bitwise negation
```

The "help" is misleading because it is suggesting using `!`  to "perform bitwise negation." But this is not really what ~ performs. [NEG and NOT are two separate instructions ](http://www.penguin.cz/~literakl/intel/n.html) which perform different things. I think this message would be best changed to "perform bitwise NOT" or "perform bitwise one's complement"

**Comment by nagisa** [comment]
`~` *is* referred to as “bitwise not”, “binary complement” *and* “bitwise negation” among many other names, so the current diagnostic is valid. Not sure where the confusion might arise here, because “bitwise” implies that the operation is… well… bitwise.

**Comment by mark-i-m** [comment]
`bitwise not` would be my preferred phrasing...
