### ISSUE TITLE
Profile Guided Optimization (PGO) not working on aarch64

### ISSUE THREAD

**Issue by robsmith11** [rust-lang/rust#57257]
Using the latest nightly on `aarch64-unknown-linux-gnu` installed with `rustup`, I am getting the following error when I attempt to run any crate with PGO:

```
$ RUSTFLAGS="-Z pgo-gen=/tmp/prof.data" cargo run                                                                   Compiling play v0.1.0 (/home/me/play)
error[E0463]: can't find crate for `profiler_builtins`                                                                  
error: aborting due to previous error
```

**Comment by maklemenz** [comment]
Facing the same issue. I'm trying to compile rustc with pgo.

**Comment by froydnj** [comment]
It looks like aarch64-unknown-linux-gnu is built without `--enable-profiling`.
