### ISSUE TITLE
2018 edition fails to import modules for binary projects

### ISSUE THREAD

**Issue by hkcorac** [rust-lang/rust#57252]
Hello Rust developers,

My project is a binary project:

```shell
├── Cargo.lock
├── Cargo.toml
├── src
    ├── a.rs
    ├── main.rs
    └── z.rs
```

Without `edition = "2018"`, my imports work:

```rust
mod a;
mod z;
```

With `edition = "2018"`, above imports don't work. Prefixing `crate::a` or `self::a` doesn't work either.

Error message is:

```shell
error[E0658]: imports can only refer to extern crate names passed with `--extern` on stable channel (see issue #53130)
  --> src/main.rs:13:5
   |
1  | mod a;
   | ------ not an extern crate passed with `--extern`
```

I stripped down the error message at line `#13`, it's just `use a::something;`.

I think it's a bug, may I ask if you could verify?

Thank you,

**Comment by petrochenkov** [comment]
This is correct behavior in the "anchored path" model which is currently in effect on stable.
Going to be fixed once https://github.com/rust-lang/rust/pull/56759 lands.

**Comment by hkcorac** [comment]
Thank you, I'm closing this issue.
