### ISSUE TITLE
Wasm32 not supported ?

### ISSUE THREAD

**Issue by sriharikapu** [rust-lang/rust#57254]
This is the issue is.

```
rustup target add wasm32-unknown-unknown
error: toolchain 'nightly-x86_64-apple-darwin' does not support components
```

![screen shot 2019-01-02 at 10 05 02 am](https://user-images.githubusercontent.com/6247133/50578487-e5bf6900-0e75-11e9-86af-bb83593efd23.png)

**Comment by estebank** [comment]
Have you done the following?

```
rustup update
rustup target add wasm32-unknown-unknown --toolchain nightly
```

**Comment by hellow554** [comment]
@sriharikapu is this issue still relevant or did you resolve your problem?

**Comment by sriharikapu** [comment]
It's resolved thanks everyone
