### ISSUE TITLE
x86-interrupt calling convention leads to wrong error code in debug mode

### ISSUE THREAD

**Issue by phil-opp** [rust-lang/rust#57270]
When using the [x86-interrupt calling convention](https://github.com/rust-lang/rust/issues/40180) for an exception with error code, the error code is wrong in debug mode. I checked the assembly code and it seems like it loads the first field of the exception stack frame instead of the error code, i.e. it is off by 8 bytes, so this seems to be a bug in LLVM. The interesting thing is that the error code is correct in release mode.

It worked correctly with nightly `(9389e23a8 2017-12-31)`, so it is a regression. I'm currently trying different Rust versions to find out when the problem was introduced:

Nightly | Works?
-----| ------
(9389e23a8 2017-12-31) | Yes
(8ccab7eed 2018-01-31) | Yes
(bd98fe0c0 2018-02-06) | Yes
(3bcda48a3 2018-02-09) | Yes
(45fba43b3 2018-02-10) | No
(b8398d947 2018-02-11) | No
(4d2d3fc5d 2018-02-13) | No
(0ff9872b2 2018-02-28) | No
(1ffb32147 2018-05-31) | No
(f4a421ee3 2018-12-13) | No

**Edit**: The problem was introduced between the 2018-02-09 and the 2018-02-10 nightly. These are the relevant commits: https://github.com/rust-lang/rust/compare/3bcda48...45fba43. I think it was most likely the upgrade to LLVM 6 in https://github.com/rust-lang/rust/pull/47828, which was [huge](https://github.com/rust-lang/llvm/compare/bc344d5bc23c61ff9baf82d268a0edf199933cc3...9f81beaf32608fbe1fe0f2a82f974e800e9d8c62).

See https://github.com/phil-opp/blog_os/issues/513 for more context.

**Comment by phil-opp** [comment]
I think I found the problem. I'm currently preparing a LLVM patch.

**Comment by phil-opp** [comment]
I submitted a patch upstream: https://reviews.llvm.org/D56275.

**Comment by phil-opp** [comment]
A patch for fixing this issue was merged to LLVM in [rL354837](https://reviews.llvm.org/rL354837). I'm not sure how closely Rust tracks current LLVM changes and whether it's worth a backport.

**Comment by toothbrush7777777** [comment]
@phil-opp Has this been corrected? Does it work in recent Rust nightlies?

**Comment by mati865** [comment]
LLVM 8 (the one which Rust is using) was branched in January and it haven't been backported.
Therefore it's still not fixed.

**Comment by toothbrush7777777** [comment]
@mati865 Thank you for letting me know. Do you know if there are any plans to backport the fixes into Rust's copy of LLVM?

**Comment by mark-i-m** [comment]
@toothbrush7777777 IIUC we avoid doing that because maintaining the patches on our copy is a pain.

**Comment by mark-i-m** [comment]
But the fix is in the LLVM trunk branch, so it should end up in whatever the next version of LLVM is...

**Comment by phil-opp** [comment]
I thought about doing a backport PR, but the diff is quite large because the patch in [rL354837](https://reviews.llvm.org/rL354837) depends on the refactoring in [rL351616](https://reviews.llvm.org/rL351616) (so we would need to include it too). So I think it's better to wait for the next regular update of Rust's LLVM fork.

**Comment by toothbrush7777777** [comment]
@mark-i-m So that will be LLVM 9, right? Do you have any idea when that will be finished/copied to Rust's LLVM?

**Comment by mati865** [comment]
LLVM 9 is expected to be released around September 2019, Rust may migrate earlier.

**Comment by phil-opp** [comment]
There is now a (work in progress) pull request to update Rust to LLVM 9 at https://github.com/rust-lang/llvm-project/pull/19. GitHub doesn't display all commits, so I'm not 100% sure that it contains https://github.com/llvm/llvm-project/commit/2f055f026ad76f3503c7c40c40f4b71594adbe55, but I see no reason why it shouldn't.

**Comment by kyrias** [comment]
(I just double checked, and the `9.0-2019-07-12` branch does indeed contain the fix.)

**Comment by mati865** [comment]
@phil-opp LLVM 9 has made it's way to nightly, could you retest and close the issue?

**Comment by phil-opp** [comment]
@mati865 Sure. I tried it with both `rustc 1.38.0-nightly (bc2e84ca0 2019-07-17)` and `rustc 1.38.0-nightly (95b1fe560 2019-07-20)`. Both nightlies reported a correct error code, so the issue seems to be fixed.
