### ISSUE TITLE
ICE with mutually recursive infinite-sized type and enum from another module

### ISSUE THREAD

**Issue by XavilPergis** [rust-lang/rust#57271]
I'm getting a very touchy ICE on `rustc 1.33.0-nightly (9eac38634 2018-12-31) running on x86_64-unknown-linux-gnu`. I'm not 100% sure what it has to do with...

Here is the minimum example I can trigger the ICE with:
```rust
// in `crate::signature` / `src/signature.rs`
use crate::field::BaseType;

pub enum ObjectType {
    Class(ClassTypeSignature),
    Array(TypeSignature),
    TypeVariable(()),
}

pub struct ClassTypeSignature {
    pub package: (),
    pub class: (),
    pub inner: (),
}

pub enum TypeSignature {
    Base(BaseType),
    Object(ObjectType),
}

// in `crate::field` / `src/field.rs`
#[derive(Copy, Clone, Debug, Eq, PartialEq, Hash)]
pub enum BaseType {
    Byte,
    Char,
    Double,
    Float,
    Int,
    Long,
    Short,
    Boolean,
}
```

I'm expecting to see an error about an infinitely-sized type, but instead the compiler crashes. Changes that make the compiler ***not*** ICE:
- Moving `field::BaseType` into `signature`
- Making `ObjectType`/`TypeSignature` not mutually recursive
- Rearranging or removing any field/variant from any of these structs/enums
- Making `ObjectType::Class` not contain `ClassTypeSignature`

Output of `RUST_BACKTRACE=1 cargo build`: https://gist.github.com/XavilPergis/102774c6c542403db10a351ff013f356
Original code that ICE'd: https://gist.github.com/XavilPergis/dafc2bb478f18cee700f78e16eea81cd

**Comment by estebank** [comment]
The error is raised here because it is expected that an error should have been emitted before reaching this code branch, presumably by `force_from_dep_node`:

https://github.com/rust-lang/rust/blob/ec194646fef1a467073ad74b8b68f6f202cfce97/src/librustc/dep_graph/graph.rs#L632-L642

**Comment by XavilPergis** [comment]
Here's the code in my repository, by the way: https://github.com/XavilPergis/rvm/blob/ice/class/src/signature.rs

**Comment by jakubadamw** [comment]
@XavilPergis, I tried to compile your `ice` branch with the 2018-12-31 nightly and it produced the expected errors with no ICEs. Same with the newest nightly and the stable 1.36.
