### ISSUE TITLE
Tracking issue for making std-surfaced macro intrinsics available via `std::` paths

### ISSUE THREAD

**Issue by mark-i-m** [rust-lang/rust#57289]
Quoting @cramertj in https://github.com/rust-lang/rust/issues/53128#issuecomment-450965320

@mark-i-m Are you referring to how std-surfaced macro intrinsics aren't yet usable by their std paths? e.g. This code only works if you remove `std::`:

```rust
fn main() {
    println!("{}", std::format_args!("{}", 5));
}
```

```
error[E0433]: failed to resolve: could not find `format_args` in `std`
 --> src/main.rs:2:25
  |
2 |     println!("{}", std::format_args!("{}", 5));
  |                         ^^^^^^^^^^^ could not find `format_args` in `std`

error: aborting due to previous error
```

**Comment by cramertj** [comment]
cc @eddyb, @petrochenkov

**Comment by scottmcm** [comment]
This appears to compile today: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=8171ccfef9558bc62896f1c530b903d8
