### ISSUE TITLE
Better error for swapping period and ::

### ISSUE THREAD

**Issue by ayende** [rust-lang/rust#57316]
I wrote the following code, and got this error. 

```
sslb.set_verify_callback(openssl::ssl::SslVerifyMode.PEER, |_, _| true);// accept all certificates
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^ did you mean `openssl::ssl::SslVerifyMode { /* fields */ }`?
```

A better error would be to suggest `openssl::ssl::SslVerifyMode::PEER`, because if the type has a member of this name, it is very likely a typo

**Comment by estebank** [comment]
CC #47666. Not the same parser code, but similar type of enhancement to user experience.
