### ISSUE TITLE
`fn(Args...) -> Ouptut` should be `'static`

### ISSUE THREAD

**Issue by alercah** [rust-lang/rust#57325]
The following code is rejected by the compiler:

```rust
fn foo<T: 'static>() {}

fn bar<'a>() {
    foo::<fn(&'a ())>();
}
```

([playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=83b8b2f14d38b39261e29e4a957b9c9e))

The error is

```
error[E0477]: the type `fn(&'a ())` does not fulfill the required lifetime
 --> src/lib.rs:4:5
  |
4 |     foo::<fn(&'a ())>();
  |     ^^^^^^^^^^^^^^^^^
  |
  = note: type must satisfy the static lifetime
```

This seems clearly like an overly zealous borrowck; `fn` types don't have any internal state and so the fact that they might have a lifetime parameter in an argument is clearly irrelevant. Indeed, it works fine to give `foo` an argument of type `T` and then call it with a concrete argument:

```rust
fn foo<T: 'static>(_: T) {}

fn baz(_: &()) {}

fn bar() {
    foo(baz);
}
```

This has ripple effects through the type system, since it affects every type which uses `PhantomData<fn(Args...) -> Output>`.

Similarly, though I'm not quite sure it's identical since it's a trait, we see something similar for `Fn`:

```rust
trait Static: 'static {}
impl<T> Static for dyn Fn(T) + 'static {}
```

gives a similar error, that the compiler needs `T: 'static` to be satisfied. But this seems quite strange that we could have a trait `+ static` not satisfy the `'static` bound, after all is that not the point of the requirement `+ 'static`?

This issue is being reported after a long Discord conversation with @Centril and Cyphix where we couldn't figure out what was up.

**Comment by djozis** [comment]
>This is acting correctly

>I would have preferred to consider types like `T` in the impl above to be disallowed from appearing in the `type Bar` definition

@nikomatsakis: From the above, may I clarify: Would I be right to interpret your comment as an acknowledgment that this is not behaving as it ultimately should? Does this issue become changing "types like `T` in the impl above to be disallowed from appearing in the `type Bar` definition" so that `fn(&'a ())` can become `'static`, for example?

**Comment by ChaseElectr** [comment]
> `<X as Foo>::Bar: 'static` if `X: 'static`

Why this should be true?

It seems that if I have a struct `Bar<T>`, `Bar<T>: 'static` will force require the `T` to be `'static` regardless the real relationship of `Bar` and `T`. It doesn't make sense to me.

Maybe a set of generic lifetime inherit rules could solve this problem?

**Comment by nikomatsakis** [comment]
@djozis 

> From the above, may I clarify: Would I be right to interpret your comment as an acknowledgment that this is not behaving as it ultimately should? 

I think you can interpret my comment as "this is a language wart and I would be interested in trying to see if we can get away with changing the rules here". That said, backwards compatibility may make that impossible. (We could *possibly* use something edition-gated, haven't thought much about it.) In any case, this would require an RFC in my opinion, so I'm going to close this issue as "working as expected for now".

**Comment by nikomatsakis** [comment]
@ChaseElectr please refer to RFC 1214 for justification and reasoning.
