### ISSUE TITLE
Improve "if and else have incompatible types" error

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#57348]
When `if` and `else` arms have incompatible types, like below, the compiler should point at both arms with the evaluated type and also suggest removal of trailing semicolon if relevant.

```
fn main() {
    let a = if false { "x" } else { "y"; };
}
```

[Current](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=cd54d41c43d1b10a53aef3fd1bd0c848):

```
error[E0308]: if and else have incompatible types
 --> src/main.rs:2:13
  |
2 |     let a = if false { "x" } else { "y"; };
  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected &str, found ()
  |
  = note: expected type `&str`
             found type `()`
```
Suggested:
```
error[E0308]: if and else have incompatible types
 --> src/main.rs:2:13
  |
2 |     let a = if false { "x" } else { "y"; };
  |                        ---          ^^^- help: remove this semicolon
  |                        |              |
  |                        |              expected &str, found ()
  |                        this arm evaluates to &str
  = note: expected type `&str`
             found type `()`
```

_Example taken from [lessons learned in Converting a Python library to Rust](https://alantrick.ca/writings/programming/python_to_rust/) article_

**Comment by ishitatsuyuki** [comment]
I think we don't even need the "expected type" and "found type" lines here. The biggest issue is that "expected" and "found" are unclear and doesn't easily map to "if" and "else" arms, so we should move to "this arm has" completely.

**Comment by estebank** [comment]
It would be a good time to give this error its own error code, where we can document the behavior in a teachable way, instead of lumping it into the generic "type mismatch" bag.
