### ISSUE TITLE
Suggested replacement name is slightly too self-biased

### ISSUE THREAD

**Issue by illicitonion** [rust-lang/rust#57372]
When compiling this snippet:
```rust
pub struct S { 
    settings: String,
}

impl S { 
    pub fn foo(setting: String) -> String {
        settings.to_string()
    }   
}
```

where `foo`'s arg is named `setting` but accessed as `settings` (which exists on `S`), the error message given is:

```
error[E0425]: cannot find value `settings` in this scope
 --> src/lib.rs:7:9
  |
7 |         settings.to_string()
  |         ^^^^^^^^
  |         |
  |         `self` value is a keyword only available in methods with `self` parameter
  |         help: try: `self.settings`
```

This is a useful error message, but is slightly too `self`-focused. The error message should probably _either_ suggest the `setting` parameter ("maybe you made a typo"), _or_ read as it currently does but also suggest adding a `self` parameter and changing to `self.settings`. But right now, saying "`self` value is a keyword only available in methods with `self` parameter" is confusing and misleading, because the `self` keyword doesn't actually appear in the code anywhere, only in the suggestion.

**Comment by estebank** [comment]
Current output:

```
error[E0425]: cannot find value `settings` in this scope
 --> src/lib.rs:7:9
  |
7 |         settings.to_string()
  |         ^^^^^^^^ a field by this name exists in `Self`
```

**Comment by compiler-errors** [comment]
Suggests both now.

```
error[[E0425]](https://doc.rust-lang.org/stable/error-index.html#E0425): cannot find value `settings` in this scope
 --> src/lib.rs:7:9
  |
7 |         settings.to_string()
  |         ^^^^^^^^
  |         |
  |         a field by this name exists in `Self`
  |         help: a local variable with a similar name exists: `setting`
```
