### ISSUE TITLE
Suggest removing parenthesis surrounding lifetimes

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#57386]
[Given](https://github.com/rust-lang/rust/blob/1f64f60d5cba64beca6e812e16d6d99519d3551b/src/test/ui/parser/trait-object-lifetime-parens.rs):

```
trait Trait {}
fn f<'a, T: Trait + ('a)>() {}
```
suggest the correct syntax
```
error: parenthesized lifetime bounds are not supported
  --> $DIR/trait-object-lifetime-parens.rs:5:24
   |
LL | fn f<'a, T: Trait + ('a)>() {}
   |                        ^
help: remove the braces
   |
LL | fn f<'a, T: Trait + 'a>() {}
   |                     ^^
```

**Comment by goldenlentils** [comment]
I'd like to work on this (I'm new)

**Comment by estebank** [comment]
@goldenlentils feel free to reach out for any help you might need! And take a look at [The Forge](https://forge.rust-lang.org/), particularly [the explanation on how to run tests](https://forge.rust-lang.org/x-py.html#run-specific-tests) (`./x.py test src/test/ui --stage 1 --bless` is what I normally run).

You will find the code that emits this error in `parse_generic_bounds_common` in `libsyntax/parse/parser.rs`. You will need to change the `span_err` call for an `struct_span_err` that will give you a `DiagnosticBuilder` that you can modify using `span_suggestion_with_applicability`. You can search the codebase (and the same file) for how to use it.

**Comment by goldenlentils** [comment]
@estebank Thanks!

I managed to get the error to look like this:

```
error: parenthesized lifetime bounds are not supported
 --> /home/igor/dev/sandbox/sample.rs:3:21
  |
3 | fn f<'a, T: Trait + ('a)>() {}
  |                     ^^^^ help: remove the parentheses: `'a`

error: aborting due to previous error
```

Or, if using `span_suggestion_short_with_applicability`:

```
error: parenthesized lifetime bounds are not supported
 --> /home/igor/dev/sandbox/sample.rs:3:21
  |
3 | fn f<'a, T: Trait + ('a)>() {}
  |                     ^^^^ help: remove the parentheses

error: aborting due to previous error
```

As I understand, the help message appears inline because of the condition `sugg.msg.split_whitespace().count() < 10` at `librustc_errors/emitter.rs:46`. Is this fine? Is any of the two options above preferable?

**Comment by estebank** [comment]
@igorsdv your understanding is correct. Being inline is fine and I'm partial towards the short version, at least in this case.
