### ISSUE TITLE
When recovering `char`s, still give them the `char` type, instead of `&str`

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#57384]
[`test/ui/parser/lex-bad-char-literals-3.stderr`](https://github.com/rust-lang/rust/blob/1f64f60d5cba64beca6e812e16d6d99519d3551b/src/test/ui/parser/lex-bad-char-literals-3.stderr) shouldn't emit a type error.

**Comment by estebank** [comment]
This line would have to be changed to use `token::Char`:

https://github.com/rust-lang/rust/blob/8e2063d02062ee9f088274690a97826333847e17/src/libsyntax/parse/lexer/mod.rs#L1448

Ideally, we would add a new literal type `Err` here

https://github.com/rust-lang/rust/blob/8e2063d02062ee9f088274690a97826333847e17/src/libsyntax/parse/token.rs#L59-L69

that will later be interpreted to be of type `TyErr`, in order to avoid having _any_ type errors involving this problematic literal, regardless of wether a `&str` or a `char` were expected.

**Comment by JohnTitor** [comment]
@estebank I wanna tackle this, but I don't know how to add a new literal type `Err`.
If you have time, please tell me.

**Comment by estebank** [comment]
@JohnTitor That would be the "hard" way of solving this. That would entail adding a new `Lit` variant, in the code linked above, deal with the fallout of doing so (most likely by ignoring it in most places) and transforming it to a `TyErr` when giving it a type (it is receiving `TyStr` at the moment). You should be able to find it by following the errors after adding the variant, but if not ping me and we can look at it together.

**Comment by JohnTitor** [comment]
@estebank I want to open a PR for fixing this issue, can I ask you to review?

**Comment by estebank** [comment]
@JohnTitor of course! Just add `r? @estebank` to the description of the PR.
