### ISSUE TITLE
Add primary label to incorrect doc comments

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#57382]
Desired output:

```
error: expected item after doc comment
  --> $DIR/doc-before-extern-rbrace.rs:2:5
   |
LL |     /// hi
   |     ^^^^^^ this doc comment doesn't document anything
```

**Comment by JohnTitor** [comment]
@estebank I came up with this change (`src/libsyntax/parse/parser.rs:4478`), but this may be wrong. What do you think?
```
self.struct_span_err(self.prev_span, message)
    .span_label(self.prev_span, "this doc comment doesn't document anything")
    .emit();
```

**Comment by estebank** [comment]
@JohnTitor that seems correct to me. I believe there are a couple of other places where we check for incorrect doc comments that will also need to have the `span_label` added.

**Comment by estebank** [comment]
That's less than ideal. Could you show the diff from your change? It would be unusual the change from `span_err` to `struct_span_err` to cause that difference in output.

**Comment by JohnTitor** [comment]
here https://github.com/JohnTitor/rust/commit/9ab2320098088a500ca4c8b48e8c8508951952db
This change isn't good because doc comments and attributes don't separate. But it wouldn't be matter.

**Comment by JohnTitor** [comment]
@estebank I found the cause, so I can add spans. But I cannot find other place to add spans, could you tell me?

**Comment by estebank** [comment]
@JohnTitor I'm not sure I understand the problem, could you expand?

**Comment by JohnTitor** [comment]
@estebank Sure.
`struct_span_err` outputs an error using `DiagnosticBuilder`, but `span_err` does using `emit`.
`emit` checks if continuing after error. This `abort_if_errors` returns `FatalError.raise()`.

https://github.com/rust-lang/rust/blob/e2f221c75932de7a29845c8d6f1f73536ad00c41/src/librustc_errors/lib.rs#L646-L651

When I added `FatalError.raise()` after `emit()` in `src/libsyntax/parse/parser.rs`, there is one error(aborted process).

**Comment by JohnTitor** [comment]
@estebank Is my solution good, or is there better solution?
If it’s not too much trouble, I'd like to make a PR and ask you to review.

**Comment by estebank** [comment]
@JohnTitor I would like to avoid having a `FatalError.raise()` after this. I noticed that the current method `expected_item_err` doesn't return anything, it should return a `PResult` with the `DiangosticBuilder` created, and be called with a `?` now. That way when we encounter this error we no longer attempt to parse the item expected after, ending up again with only one error. Other than that, I think you're in the right track.

**Comment by JohnTitor** [comment]
@estebank Okay, I want to solve this issue for now.
