### ISSUE TITLE
Suggest appropriate place for type argument after associated type

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#57385]
[Like we do for lifetimes](https://github.com/rust-lang/rust/pull/56220), suggest the appropriate place for type arguments written after associated an type.

[Given](https://github.com/rust-lang/rust/blob/1f64f60d5cba64beca6e812e16d6d99519d3551b/src/test/ui/parser/issue-32214.rs)

```
trait Trait<T> { type Item; }
pub fn test<W, I: Trait<Item=(), W> >() {}
fn main() { }
```
we currently emit
```
error: type parameters must be declared prior to associated type bindings
  --> $DIR/issue-32214.rs:5:34
   |
LL | pub fn test<W, I: Trait<Item=(), W> >() {}
   |                                  ^
```

**Comment by davidtwco** [comment]
Re-opening as this was regressed by #58191 (11874a0c14a1637a310f0088a2c91ceb2810f6dd).

**Comment by estebank** [comment]
Why wasn't that regression caught by our tests?

**Comment by davidtwco** [comment]
> Why wasn't that regression caught by our tests?

The test was also changed.

**Comment by IFcoltransG** [comment]
The above code now generates a suggestion.
```
help: move the constraint after the generic argument
  |
2 | pub fn test<W, I: Trait<W, Item = ()> >() {}
  |                        ~~~~~~~~~~~~~~
  ```
I assume this issue can be closed.
