### ISSUE TITLE
Feature request: tunable for extern function definition ELF relocation type

### ISSUE THREAD

**Issue by jbaublitz** [rust-lang/rust#57390]
I have a prototype of a [toy Linux kernel module written in Rust](https://github.com/jbaublitz/knock-out). I previously had it working until recently when I rebuilt it with a newer version of Rust and LLVM and `insmod module.ko` started throwing an error in dmesg logs about `unknown rela relocation 9`. I did a `readelf` and realized that all of the `extern "C"` functions I'd declared were generating ELF entries with the `R_X86_64_GOTPCREL` relocation entry type which is defined as having a value of 9. This is apparently illegal for kernel modules after looking at the allowable ELF relocation types in the kernel module infrastructure.

I have a few questions:
1. Is this change recent?
2. If so, was this a change on the Rust side or LLVM side?
3. Would you be willing to work with me on either finding a linking-based solution (if possible) or a PR for tuning the resulting relocation type of extern-declared functions?

I am not sure if there's a simple linking flag I'm missing but the ones I've tested, as well as using any of the relocation strategies available through codegen options, yield the same results.

**Comment by jason-ni** [comment]
Another rust linux kernel module project is also blocking on this issue. https://github.com/alex/linux-kernel-module-rust/pull/67 .

**Comment by jbaublitz** [comment]
@jason-ni Let me try that and see if this resolves it. Thanks for pointing me in that direction.

**Comment by jbaublitz** [comment]
Hey @jason-ni, thank you so much for your help! I was able to resolve this with the following options on newer Rust compilers: `--crate-type=staticlib -C relocation-model=static -C code-model=kernel -Z plt=y`. I'm gonna close this out.
