### ISSUE TITLE
Dead link (http://citizencodeofconduct.org/) in Code of Conduct

### ISSUE THREAD

**Issue by claudijd** [rust-lang/rust#57402]
I was reading through the projects code of conduct document and noticed that http://citizencodeofconduct.org/ is no longer a valid URI.  If someone had a good alternative I could send a PR for the fix.

**Comment by Mark-Simulacrum** [comment]
cc @ag_dubs -- should we move this to the website since I believe the CoC is hosted there?

**Comment by frewsxcv** [comment]
That URL resolves for me, maybe it's fixed now?

**Comment by DevQps** [comment]
> That URL resolves for me, maybe it's fixed now?

Same here, it seems to be fixed indeed!
@Mark-Simulacrum It seems to be that the Code of Conduct on [Rust's website](https://www.rust-lang.org/policies/code-of-conduct) is shorter and less detailed then the one on [http://citizencodeofconduct.org/](http://citizencodeofconduct.org/). I am not sure if that has to be an issue, but otherwise we could replace those links maybe?

**Comment by claudijd** [comment]
It does appear fixed now, thanks all for the follow up.

**Comment by Timwi** [comment]
The link is once again broken, and ironically while googling for just the domain name, my first search result was this issue ticket. Go figure

**Comment by frewsxcv** [comment]
Maybe we should link to the Internet Archive is this is going to be a recurring issue? https://web.archive.org/web/20200330154000/http://citizencodeofconduct.org/

**Comment by Coronon** [comment]
> 
> 
> Maybe we should link to the Internet Archive is this is going to be a recurring issue? https://web.archive.org/web/20200330154000/http://citizencodeofconduct.org/
> 
> Or https://github.com/stumpsyn/policies/blob/master/citizen_code_of_conduct.md

I find linking to the Internet Archive to be a really inelegant solution. Isn't it possible to self-host the CCoC to avoid any further issues? Maybe get in touch with them and ask for permission through `board at stumptownsyndicate.org`? Their website http://stumptownsyndicate.org/ seems to be dead as well.

**Comment by XAMPPRocky** [comment]
I'm going to close this in favour of https://github.com/rust-lang/www.rust-lang.org/issues/1212 since the content is on the website not the rust repo.
