### ISSUE TITLE
Suggestion for pub(crate) doesn't handle reexports well

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#57410]
First [reported upstream](https://github.com/rust-lang/cargo/issues/6465#issuecomment-448836441) this code:

```rust
#![warn(unreachable_pub)]

pub use self::m::f;

mod m {
    pub use self::imp::f;  // Recommends pub(crate), but that causes an error above.
    mod imp {
        pub fn f() {}
    }
}
```

[gives the warning](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=5ffaaac3b2b02e553a1090c955bdc046):

```
warning: unreachable `pub` item
 --> src/lib.rs:6:5
  |
6 |     pub use self::imp::f;  // Recommends pub(crate), but that causes an error above.
  |     ---^^^^^^^^^^^^^^^^^^
  |     |
  |     help: consider restricting its visibility: `pub(crate)`
  |
note: lint level defined here
 --> src/lib.rs:1:9
  |
1 | #![warn(unreachable_pub)]
  |         ^^^^^^^^^^^^^^^
  = help: or consider exporting it for use by other crates

    Finished dev [unoptimized + debuginfo] target(s) in 0.57s
```

but the suggestions, when applied, doesn't compile!

**Comment by estebank** [comment]
Should it suggest `pub mod m` instead?

**Comment by ehuss** [comment]
> Should it suggest `pub mod m` instead?

Wouldn't that be a change in semantics (`m` would be reachable by other users)?  The original code looks correct to me.  The `use self::imp::f;` item is reachable from the root re-export.  It seems to me that the lint shouldn't fire in this case.
