### ISSUE TITLE
Compile time perf regression for packed-simd's max-rss

### ISSUE THREAD

**Issue by memoryruins** [rust-lang/rust#57432]
packed-simd's max-rss and faults regressed in #56723

https://perf.rust-lang.org/compare.html?start=ae167c91aa9abefcd4a9697b5560330ef18e2e3e&end=d6d32ac25df2984f66b6abd14c1096880e04179a&stat=max-rss

compare | 2019-01-04 (ae167c91) | 2019-01-04 (d6d32ac2)
-- | -- | -- 

max-rss

```rust
packed-simd-check
	avg: 153.5%	min: 2.4%	max: 241.9%
packed-simd-opt
	avg: 119.0%	min: 2.2%	max: 229.7%
packed-simd-debug
	avg: 117.2%	min: -0.7%	max: 226.8%
```

faults

```rust
packed-simd-check
	avg: 149.2%	min: 0.6%	max: 235.8%
packed-simd-opt
	avg: 113.7%	min: 0.6%	max: 225.5%
packed-simd-debug
	avg: 113.6%	min: 0.6%	max: 223.3%
```

Other crates' max-rss were affected, although not to the extent above.

cc @oli-obk

**Comment by mati865** [comment]
Looks like there were some issues with  the perf but latest results show improvement for packed-simd.

**Comment by memoryruins** [comment]
#57442 definitely helped :)

https://perf.rust-lang.org/compare.html?start=01af12008d63a64446a86d995e772f8a539a4202&end=ec504def3665b0bc2ec80bede6dba2c603928315&stat=max-rss

compare | 2019-01-27 (01af1200) | 2019-01-28 (ec504def) | % change
-- | -- | -- | --

max-rss

```rust
packed-simd-check
	avg: -10.1%	min: -14.7%	max: 0.3%
packed-simd-debug
	avg: -8.5%	min: -14.2%	max: -0.1%
packed-simd-opt
	avg: -9.2%	min: -14.0%	max: -2.8%
```

![image](https://user-images.githubusercontent.com/6868531/51952861-fbd63000-2407-11e9-81bb-5986c999fbe8.png)
