### ISSUE TITLE
Support x86_64-musl as a host architecture

### ISSUE THREAD

**Issue by farcaller** [rust-lang/rust#57439]
Now that #55163 is closed this bug will serve as an aggregate for musl host architecture support. The known blockers are:

- #53968

**Comment by mati865** [comment]
`rustup toolchain install nightly-x86_64-unknown-linux-musl` works now but it's not useful on most of glibc based distros unless you have unwinder built with musl.
There is WIP PR for musl built `rustup` which will run on musl based distros.

**Comment by sanmai-NL** [comment]
@mati865: Great! We can avoid rustup using an installer archive from e.g. https://static.rust-lang.org/dist/2019-03-17/rust-nightly-x86_64-unknown-linux-musl.tar.gz. Part of a container build script:

````sh
set -ex
tar -C /tmp/ -xzf /tmp/rust-nightly-x86_64-unknown-linux-musl.tar.gz
sh -- /tmp/rust-nightly-x86_64-unknown-linux-musl/install.sh --verbose --prefix=/opt/
PATH="/opt/bin/:{PATH:?}"
export PATH
printf '%s\n' '/lib' '/usr/local/lib' '/usr/lib' '/opt/lib' '' > /etc/ld-musl-x86_64.path
cargo -h
````

Compiling packages that transitively depend on procedural macros does not work, however. :(
See https://github.com/rust-lang/cargo/issues/5266.

**Comment by mati865** [comment]
There is basic musl host toolchain available so this issue is fixed.

I'll track remaining things in https://github.com/rust-lang/rust/issues/59302.
