### ISSUE TITLE
Move cfg_if macro from libstd to libcore

### ISSUE THREAD

**Issue by dlrobertson** [rust-lang/rust#57446]
## Summary

If possible I would like to move the `cfg_if` macro from `src/libstd/macros.rs` to `src/libcore/macros.rs`.

## Motivation

The `cfg_if` macro could potentially increase the readability of some `cfg`s in `no_std` code. In particular it could dramatically improve the readability of some code in `libcore` e.g. `ffi::VaList` (why I'm interested in moving it :smile:). I don't see anything in the macro that would make it invalid in `libcore`.

**Comment by alexcrichton** [comment]
Unfortunately we don't have a great way to export a macro from libcore to use in libstd that isn't part of the public API. We aren't quite ready yet I think to make this part of the public API but duplicating the definition should be fine as its a pretty simple macro

**Comment by dlrobertson** [comment]
@alexcrichton :+1: Thanks for the info. I'll hold off on duplicating it in `libstd` until I know I need it then.

**Comment by djc** [comment]
@alexcrichton can you elaborate on why we don't want to make `cfg_if` public? It came up recently in the [left-pad index dicussions](https://internals.rust-lang.org/t/calculating-which-3rd-party-crates-are-good-candidates-for-std-inclusion-via-left-pad-index/11129), seems like it would be good to expose this publicly in std and core.

**Comment by alexcrichton** [comment]
More discussion about this is at https://github.com/rust-lang/rust/pull/59443 as well. I do not personally have an opinion on whether or not this should be exported from `core` or not. I don't personally have the motivation to push for that stabilization and/or inclusion myself.

**Comment by Mark-Simulacrum** [comment]
I am going to close this issue as it's been somewhat obsoleted by the fact that libstd depends on cfg-if (the crate) now, and libcore can always duplicate if necessary. I imagine we might even be able to get libcore to depend on cfg-if (since it's a macro-only crate I believe), but that's likely harder :)
