### ISSUE TITLE
[rustdoc] Sort items alphabetically in the sidebar

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/rust#57448]
Currently, the items on the rustdoc pages are sorted in the order of apparition in the source code. I think it'd be nicer to have them sorted alphabetically.

cc @rust-lang/docs @rust-lang/rustdoc @Geal

**Comment by the8472** [comment]
Items that are related may be grouped in the source, sorting would remove that association. E.g.  you can find `Vec::new` and `Vec::with_capacity` next to each other and on top since those are likely the first method you'll need.

**Comment by QuietMisdreavus** [comment]
One thing i would like to see is grouping things that *aren't* methods (e.g. associated consts, i don't know if there's anything else you can associate to a type right now) separately from methods. We already break out associated types for traits, it seems right to break out associated consts from the "Methods" section.

**Comment by nagisa** [comment]
Re-sorting alphabetically something that is often carefully sorted by the author already (in source) seems… wrong. At the very least there is a good reason why constructing methods appear first in the source, then many of the deconstructing methods, then `first` and `last`, `first_mut` and `last_mut` etc close together, etc.

Adding extra heuristics will help with some of the groupings and orderings but not the others.

**Comment by GuillaumeGomez** [comment]
That's a lot of things I didn't think about. Also, if there is already a flag to disable it, then it's all fine.

**Comment by Geal** [comment]
@GuillaumeGomez @QuietMisdreavus sorry I couldn't participate on this last night, but I have something to add: keeping the declaration order is nice, but what I would really like is that the index on the left of the page be sorted.
Keeping methods close to each other when they're related in the main content is useful. But an unsorted index is a bit awkward to use.

**Comment by GuillaumeGomez** [comment]
@Geal On this point I agree. I reopen the issue with this purpose.
