### ISSUE TITLE
Binary operations involving &1.0 always infer f64

### ISSUE THREAD

**Issue by ExpHP** [rust-lang/rust#57447]
Originally posted as a comment on #36549, but in hindsight this may be a different issue. (in that `#36549` *very clearly looks like a bug*, whereas this one is in a potential gray area)

[Relevant URLO thread](https://users.rust-lang.org/t/the-iterator-binds-its-associated-type-not-by-the-first-call/23991).

```rust
let _: f32 = 1. - 1.;   // allowed
let _: f32 = 1. - &1.;  // type error
let _: f32 = &1. - 1.;  // type error
let _: f32 = &1. - &1.; // type error
```

In the latter 3 cases, the type of `&1.` is apparently defaulted to `&f64`:

```
   Compiling playground v0.0.1 (/playground)
error[E0271]: type mismatch resolving `<f64 as std::ops::Sub<&f64>>::Output == f32`
 --> src/main.rs:3:21
  |
3 |     let _: f32 = 1. - &1.; // type error
  |                     ^ expected f64, found f32

error[E0271]: type mismatch resolving `<&f64 as std::ops::Sub<f64>>::Output == f32`
 --> src/main.rs:4:22
  |
4 |     let _: f32 = &1. - 1.; // type error
  |                      ^ expected f64, found f32

error[E0271]: type mismatch resolving `<&f64 as std::ops::Sub<&f64>>::Output == f32`
 --> src/main.rs:5:22
  |
5 |     let _: f32 = &1. - &1.; // type error
  |                      ^ expected f64, found f32
```

To a mortal like me, it seems that the only reason the first line works is because the compiler must have a special case for binary operations between two unconstrained "floating-point flavored" type inference variables. Can the compiler not just special case the latter three examples in the same way it special cases the first?

**Comment by nikomatsakis** [comment]
OK, it took me a minute to remember this, but indeed there is a built-in rule that favors floating point values:

https://github.com/rust-lang/rust/blob/6ecad338381cc3b8d56e2df22e5971a598eddd6c/src/librustc_typeck/check/op.rs#L81-L100

It basically encodes in the inference scheme the idea that `x + y` has the result type of `x` so long as `x` meets certain patterns. In this particular case:

https://github.com/rust-lang/rust/blob/6ecad338381cc3b8d56e2df22e5971a598eddd6c/src/librustc_typeck/check/op.rs#L702-L706

Certainly it is possible that we could generalize this to accept `&f32` etc
