### ISSUE TITLE
for _ in 0..x makes non-inlined call to Range::next()

### ISSUE THREAD

**Issue by kornelski** [rust-lang/rust#57455]
Looks like bug #41097 

```rust
fn main() {
    for _ in 0 .. 100 {}
}
```

Translates to non-inlined calls to `Range::next()`:  https://rust.godbolt.org/z/jZ62Td

**Comment by nagisa** [comment]
There is a missing optimisation flag in your reproducer. With `-O` the inlining happens and the end result is a function that does a leaf return.

Closing. Complain if you feel I was wrong and we’ll reopen.

**Comment by kornelski** [comment]
Ouch, sorry! I assumed godbolt had it on by default :/
