### ISSUE TITLE
save-analysis doesn't dump ref entry for struct name in static method calls

### ISSUE THREAD

**Issue by staktrace** [rust-lang/rust#57462]
Here's a small testcase:

```rust
struct Foo {
}

impl Foo {
  fn new() {
  }
}

fn main() {
  Foo::new();
}
```

If you run this through `rustc -Z save-analysis` and look at the save-analysis JSON file, you'll see that there is no entry for the `Foo` part of `Foo::new()`. This seems like a bug.

**Comment by staktrace** [comment]
According to `rustc -Z ast-json test.rs` the expression is a `ExprKind::Call` where the `Foo::new` part would be a `Path` with two `PathSegment`s. This seems to be processed in `process_path` [here](https://github.com/rust-lang/rust/blob/167ceff01ec2f01f677fa6351646255d3dacbb98/src/librustc_save_analysis/dump_visitor.rs#L765). Not obvious to me why it would fail, since the `write_sub_paths_truncated` part at the end looks like it should deal with the first path segment.

**Comment by Xanewok** [comment]
cc me

**Comment by emilio** [comment]
I'm taking a look at this, fwiw. `process_method_call` does nothing with the segment, looks like it should.

**Comment by emilio** [comment]
Oh, it's a bit more subtle, but I see what's going on now.

**Comment by emilio** [comment]
I got a fix, testing to see if I can remove hacks to existing code now.

**Comment by emilio** [comment]
Fix is at https://github.com/rust-lang/rust/pull/57474, but it's unclear to me how to add a test for this. Any doc I could look at?
