### ISSUE TITLE
master doens't build on Windows due to CR characters in rustc-guide

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#57479]
`tidy` is failing with

    tidy error: C:\Users\steve\src\rust\src\doc\rustc-guide\ci\install.sh:24: CR character

on both `check_line_lengths.sh` and `install.sh` on the `rustc` guide. I'm using MSVC.

Any thoughts here?

**Comment by retep998** [comment]
That *should* have been fixed by https://github.com/rust-lang/rustc-guide/pull/246.

**Comment by steveklabnik** [comment]
Supposedly, the rustc repo was set to the commit *after* that PR landed, so that seems very strange...

**Comment by steveklabnik** [comment]
I deleted the `build` directory and this seemed to fix it. I have no idea why, but let's trust CI and not me 😆

**Comment by petrochenkov** [comment]
The submodule may need to be re-initialized.
