### ISSUE TITLE
Broken link to unstable book in rustc_plugin API docs

### ISSUE THREAD

**Issue by fkohlgrueber** [rust-lang/rust#57489]
The [documentation of rustc_plugin](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_plugin/index.html) links to the plugin feature in the unstable book, but that link is broken.

It points to:
https://doc.rust-lang.org/nightly/nightly-rustc/unstable-book/language-features/plugin.html

While the correct link would be:
https://doc.rust-lang.org/nightly/unstable-book/language-features/plugin.html

In the source, the link is relative:
`../unstable-book/language-features/plugin.html`

I'd be interested in fixing this, but I don't know whether a relative or absolute link is better in this situation.

**Comment by steveklabnik** [comment]
Relative links are best, as they work offline without a web server.

**Comment by fkohlgrueber** [comment]
The rustc api documentation doesn't get build locally by default, right?

I could replace the relative link with `../../unstable-book/language-features/plugin.html` which should work for the hosted paths I showed above, but I don't know whether this works for the local use-case as well. Do you have any suggestions?

**Comment by polybuildr** [comment]
@fkohlgrueber, I wasn't able to find the docs for rustc_plugin locally by default (using `locate`) so it seems likely that you're correct. It also seems quite likely that the path change you've proposed will work just as well for local installations, so I'd suggest going ahead and making a PR and then the reviewer(s) can comment on whether the solution is acceptable.

**Comment by agnxy** [comment]
I tried to build rustc_plugin doc and the unstable book. The rustc_plugin doc lives at
`build/x86_64-unknown-linux-gnu/compiler-doc/rustc_plugin/index.html` and the link which points to the local unstable book is `build/x86_64-unknown-linux-gnu/doc/unstable-book/language-features/plugin.html`. So the correct relative path is different from the online docs.
I'm new to Rust documentation. There might be something I'm missing here :smile:

**Comment by agnxy** [comment]
I created a PR for further discussion. The fix replaces the broken link with a correct absolute link as suggested in [the comment](https://github.com/rust-lang/rust/issues/57489#issuecomment-482933292).
