### ISSUE TITLE
from_*e_bytes and to_n*_bytes equivalents for floats

### ISSUE THREAD

**Issue by clarfon** [rust-lang/rust#57492]
These feel appropriate to add for completeness, and would simply chain `from_bits` or `to_bits` with the appropriate integer method.

I'll add a PR soon.

This issue has been assigned to @lzutao via [this comment](https://github.com/rust-lang/rust/issues/57492#issuecomment-508420816).

**Comment by nagisa** [comment]
Byte order conversions on floats themselves make no sense. The conversions should be done before float’s `from/to_bits` functions are called.

**Comment by nagisa** [comment]
Err, I misread the proposal the first time around...
