### ISSUE TITLE
rustup self update stuck on 'info: installing component 'rust-docs''

### ISSUE THREAD

**Issue by evertvr** [rust-lang/rust#57490]
Updating from rustc 1.25.0 (84203cac6 2018-03-25) on Windows 7 with command 'rustup update', update get's stuck on rust-docs installation. When I kill the update, and run 'rustc -V', it looks rust has been updated to the new version.

**Comment by jonas-schievink** [comment]
How long did you try? If Windows Defender is running it might check every file as it is written, which means considerable slowdown.

**Comment by mati865** [comment]
Installation most likely wasn't stuck but it takes long time to finish. There are 2 issues with Windows: AV software and NTFS.

More details in https://github.com/rust-lang/rustup.rs/issues/1540

**Comment by evertvr** [comment]
Thanks for the quick reply. I re-ran it, and after ~5 minutes the update completed.
