### ISSUE TITLE
`net::tcp::tests::fast_rebind` test occasionally fails

### ISSUE THREAD

**Issue by nnethercote** [rust-lang/rust#57509]
I've seen it fail a couple of times on my Ubuntu 18.04 box.

The only other evidence of failure I can find after searching online is here: https://github.com/rust-lang/rust/pull/25172#issuecomment-99804343

**Comment by dtolnay** [comment]
It fails relatively frequently for me on Linux, maybe 1 out of 4 times.

```console
---- net::tcp::tests::fast_rebind stdout ----
thread '<unnamed>' panicked at 'received error for `TcpListener::bind(&addr)`: Address already in use (os error 98)', src/libstd/net/tcp.rs:1326:13


failures:
    net::tcp::tests::fast_rebind
```

It looks like someone else has observed it failing on macOS as well: #51006. I think I will send a PR to delete the test.
