### ISSUE TITLE
compiletest: compare_output() fails on Windows due to different line endings

### ISSUE THREAD

**Issue by fkohlgrueber** [rust-lang/rust#57515]
The comparison of stdout / stderr output for ui tests fails on Windows for projects checked out using git and the recommended line ending settings.

For example, this is the output when running `cargo test` in the `test-project` folder of the [compiletest-rs](https://github.com/laumann/compiletest-rs) project:

```
...
running 1 test
test [ui] ui\dyn-keyword.rs ... FAILED

failures:

---- [ui] ui\dyn-keyword.rs stdout ----
normalized stderr:
error: `dyn` is a keyword in the 2018 edition
  --> $DIR/dyn-keyword.rs:17:9
   |
17 |     let dyn = (); //~ ERROR dyn
   |         ^^^ help: you can use a raw identifier to stay compatible: `r#dyn`
   |
note: lint level defined here
  --> $DIR/dyn-keyword.rs:14:9
   |
14 | #![deny(keyword_idents)]
   |         ^^^^^^^^^^^^^^
   = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in the 2018 edition!
   = note: for more information, see issue #49716 <https://github.com/rust-lang/rust/issues/49716>

error: aborting due to previous error



expected stderr:
error: `dyn` is a keyword in the 2018 edition
  --> $DIR/dyn-keyword.rs:17:9
   |
17 |     let dyn = (); //~ ERROR dyn
   |         ^^^ help: you can use a raw identifier to stay compatible: `r#dyn`
   |
note: lint level defined here
  --> $DIR/dyn-keyword.rs:14:9
   |
14 | #![deny(keyword_idents)]
   |         ^^^^^^^^^^^^^^
   = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in the 2018 edition!
   = note: for more information, see issue #49716 <https://github.com/rust-lang/rust/issues/49716>

error: aborting due to previous error



diff of stderr:

 error: `dyn` is a keyword in the 2018 edition
   --> $DIR/dyn-keyword.rs:17:9
    |
 17 |     let dyn = (); //~ ERROR dyn
    |         ^^^ help: you can use a raw identifier to stay compatible: `r#dyn`
    |
 note: lint level defined here
   --> $DIR/dyn-keyword.rs:14:9
    |
 14 | #![deny(keyword_idents)]
    |         ^^^^^^^^^^^^^^
    = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in the 2018 edition!
    = note: for more information, see issue #49716 <https://github.com/rust-lang/rust/issues/49716>

 error: aborting due to previous error



The actual stderr differed from the expected stderr.
Actual stderr saved to C:\Users\felix\AppData\Local\Temp\compiletestsGP0Kn\dyn-keyword.stderr
To update references, run this command from build directory:
tests/ui/update-references.sh 'C:\Users\felix\AppData\Local\Temp\compiletestsGP0Kn' 'dyn-keyword.rs'
...
```

On Windows, Git's recommended line ending setting is *Checkout Windows-style, commit Unix-style* (see [here](https://stackoverflow.com/questions/10418975/how-to-change-line-ending-settings)). This means that the line endings of all files (including `*.stderr`) are converted from `LF` to `CRLF` on checkout.

Since line breaks in the actual output get normalized to `LF` (see [here](https://docs.rs/compiletest_rs/0.3.18/src/compiletest_rs/runtest.rs.html#2531-2532)), the comparison between actual and expected output fails (see [here](https://docs.rs/compiletest_rs/0.3.18/src/compiletest_rs/runtest.rs.html#2570)).

Additionally, the `fixed` actual output doesn't get normalized and therefore can have `CRLF` line endings (see [here](https://docs.rs/compiletest_rs/0.3.18/src/compiletest_rs/runtest.rs.html#2571-2290)).

My suggestion would be to add another check to [`compare_output()`](https://docs.rs/compiletest_rs/0.3.18/src/compiletest_rs/runtest.rs.html#2570):

```
if actual == expected {
    return 0;
}

// check if files only differ in line endings
if actual.replace("\r\n", "\n") == expected.replace("\r\n", "\n") {
    return 0;
}
```

I can open a PR if you agree that this is the right way to solve the issue. What do you think?

**Comment by retep998** [comment]
https://github.com/rust-lang/rust/blob/master/.gitattributes should ensure that all checked out files use `LF` even on Windows when Git is configured to checkout windows-style.

**Comment by fkohlgrueber** [comment]
Ok, thanks for the clarification. I'll report the issue there than.
