### ISSUE TITLE
Regression from stable to beta: examples dir in workspace top-level

### ISSUE THREAD

**Issue by jonhoo** [rust-lang/rust#57524]
In [`tower`](https://github.com/tower-rs/tower), we have a root-level `examples/` directory in a workspace. This means that we also have to list `[dev-dependencies]` in the [root-level `Cargo.toml`](https://github.com/tower-rs/tower/blob/5fa089b6b9dc0a2ed9cff64d0659b3faa07bc586/Cargo.toml#L21). This works just fine on the current stable (`1.31.1`), but fails to compile on `1.32 beta` and nightly with:
```
error: failed to parse manifest at `/home/jon/dev/others/tower/Cargo.toml`

Caused by:
  virtual manifests do not specify [dev-dependencies]
```
Seems like an unwanted regression from stable?

**Comment by ehuss** [comment]
I'm not sure if I understand your setup.  How is `examples/channel_service.rs` used?  Cargo has never read dependencies from a virtual manifest, so an error was added to indicate the format is not valid (https://github.com/rust-lang/cargo/pull/6276).

**Comment by jonhoo** [comment]
I'll leave that question to @carllerche as I'm not the one who set up the crate :)

**Comment by jonas-schievink** [comment]
Should this issue be moved to Cargo instead?

**Comment by jonas-schievink** [comment]
Closing in favor of a Cargo issue, but I think this is intentional and never *actually* worked (the examples were just ignored)
