### ISSUE TITLE
Ipv4Addr::is_global() returns true for non global address

### ISSUE THREAD

**Issue by JakubOnderka** [rust-lang/rust#57558]
This code should be correct, because according to [IANA IPv4 Special-Purpose Address Registry](https://www.iana.org/assignments/iana-ipv4-special-registry/iana-ipv4-special-registry.xhtml) document, all address in `0.0.0.0/8` are not global reachable. 

```rust
#![feature(ip)]
use std::net::Ipv4Addr;

fn main() {
    let ip = Ipv4Addr::new(0, 0, 0, 1);
    assert!(!ip.is_global());
}
```

But it panic on assertion failed in latest nightly (2019-01-11) (see [Rust Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=1d680e16d48ef1bb4279f850f34ac0d3))

**Comment by frewsxcv** [comment]
Relevant thread: https://github.com/rust-lang/rust/issues/27709Th

**Comment by hellow554** [comment]
@JakubOnderka please post a proper link to the playground by clicking on "share" in the upper right corner and copying that link it gives you.

**Comment by JakubOnderka** [comment]
> @JakubOnderka please post a proper link to the playground by clicking on "share" in the upper right corner and copying that link it gives you.

Sorry, fixed
