### ISSUE TITLE
[rustdoc/nightly] can not toggle source sidebar

### ISSUE THREAD

**Issue by joekyo** [rust-lang/rust#57601]
In nightly channel, the source code html pages generated by rustdoc has an icon at the left upper corner `>` , which can be used for toggling a list of the source files and it is quite handy.
The problem is that in the recent nightly version of rustdoc, maybe starting from January this year, the toggle icon is still there, but it doesn't work anymore. When it is clicked, the file list doesn't show up.
As I remember it can work in December last year, e.g. in `nightly-2018-12-18` it works.

**Comment by joekyo** [comment]
Looks like the lack of `<div id="source_sidebar">...</div>` causes this problem.

**Comment by joekyo** [comment]
cc @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
Good catch! Will fix as soon as possible.
