### ISSUE TITLE
No ordinary backtrace when query stack is printed

### ISSUE THREAD

**Issue by alexreg** [rust-lang/rust#57616]
When debugging rustc, I often want backtraces, naturally. Normally they appear fine, but sometimes, during queries, I only get the query stack printed, without the ordinary backtrace. That is, I get something like

```
thread 'rustc' panicked at 'encountered error with `-Z treat_err_as_bug', src/librustc_errors/lib.rs:490:13
query stack during panic:
#0 [explicit_predicates_of] processing `Bar::{{impl-Trait}}`
#1 [predicates_defined_on] processing `Bar::{{impl-Trait}}`
#2 [predicates_of] processing `Bar::{{impl-Trait}}`
#3 [explicit_predicates_of] processing `Bar`
#4 [predicates_defined_on] processing `Bar`
#5 [predicates_of] processing `Bar`
#6 [typeck_tables_of] processing `a`
#7 [type_of] processing `Bar`
end of query stack

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.
```

but not something like

```
thread 'rustc' panicked at 'encountered error with `-Z treat_err_as_bug', src/librustc_errors/lib.rs:490:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
   6: std::panicking::begin_panic
   7: rustc_errors::Handler::emit_db
   8: rustc_errors::diagnostic_builder::DiagnosticBuilder::emit
   9: rustc::ty::query::plumbing::<impl rustc::ty::context::TyCtxt<'a, 'gcx, 'tcx>>::emit_error
  10: <rustc::ty::sty::TyKind<'tcx> as rustc::util::ppaux::Print>::print
  11: rustc::util::ppaux::<impl core::fmt::Debug for rustc::ty::TyS<'tcx>>::fmt
  12: core::fmt::builders::DebugTuple::field
  13: <core::option::Option<T> as core::fmt::Debug>::fmt
  14: core::fmt::write
  15: <core::fmt::Arguments<'_> as core::fmt::Display>::fmt
  16: core::fmt::write
  17: env_logger::filter::Filter::matches
  18: <env_logger::Logger as log::Log>::log
  19: log::__private_api_log
  20: <(dyn rustc_typeck::astconv::AstConv<'gcx, 'tcx> + 'o)>::create_substs_for_ast_path
  21: rustc::hir::PathSegment::with_generic_args
  22: <(dyn rustc_typeck::astconv::AstConv<'gcx, 'tcx> + 'o)>::create_substs_for_ast_trait_ref
  23: <(dyn rustc_typeck::astconv::AstConv<'gcx, 'tcx> + 'o)>::instantiate_poly_trait_ref_inner
...
```

Really, I want both in such circumstances.

Note, I'm building rustc master on macOS 10.14.2.

(P.S. Is there a reason line numbers aren't printed for backtraces? At least only for the panic line, and no others?)

CC @Zoxc

**Comment by alexreg** [comment]
The issue seems to be that `backtrace::print` is returning `Err(Custom { kind: Other, error: UnwindError(_URC_NORMAL_STOP) })` in such scenarios. Odd.

**Comment by wesleywiser** [comment]
Do you have `debug-info-lines=true` in your `config.toml`? 

From the [rustc guide](https://rust-lang.github.io/rustc-guide/compiler-debugging.html): 

> IIRC backtraces don't work on Mac and on MinGW, sorry. If you have trouble or the backtraces are full of unknown, you might want to find some way to use Linux or MSVC on Windows.

> In the default configuration, you don't have line numbers enabled
> If you want line numbers for the stack trace, you can enable debuginfo-lines=true or debuginfo=true in your config.toml and rebuild the compiler.

**Comment by alexreg** [comment]
I do, yes. `debuginfo-lines`, without the first hyphen, I presume you mean?

Just noticed that adding `-Z verbose` produces the desired backtrace though! Not sure if this is intended behaviour, but does the job for now...

**Comment by alexreg** [comment]
@wesleywiser Is the above intended behaviour, meaning we should probably close this issue now... or should we tag it so it can be addressed?

**Comment by wesleywiser** [comment]
@alexreg I'm on macOS and have been consistently getting backtraces. Are you still experiencing this issue?

**Comment by Zoxc** [comment]
`-Z verbose` should not affect stack traces.

**Comment by alexreg** [comment]
Yees, this still occurs. When query information is printed, backtraces are omitted.

**Comment by cjgillot** [comment]
We now get both the backtrace and the query stack.
