### ISSUE TITLE
Nightly documentation is broken

### ISSUE THREAD

**Issue by pravic** [rust-lang/rust#57628]
Windows, different browsers.

Nightly https://doc.rust-lang.org/nightly/std/path/struct.Path.html#method.is_absolute
Stable https://doc.rust-lang.org/stable/std/path/struct.Path.html#method.is_absolute

Link text is invisible:

![image](https://user-images.githubusercontent.com/724639/51169768-c553cd80-18bd-11e9-8feb-180c376273e2.png)

**Comment by pravic** [comment]
cc @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
Nice catch. Will send the patch as soon as I can.

**Comment by pravic** [comment]
Thanks!

**Comment by Osspial** [comment]
This also causes the hyperlinks in the function declaration line to not work.
