### ISSUE TITLE
Detect loops that cannot be automatically vectorized

### ISSUE THREAD

**Issue by thedrow** [rust-lang/rust#57622]
Clang has a warning option that warns about loops that cannot be automatically vectorized.
This is often important for developers who'd like to optimize their code by manually using intrinsics or ordering the code in an auto-vectorizable way.
rustc would benefit from such option.

**Comment by matthiaskrgr** [comment]
I think you want something like
`RUSTFLAGS="-C remark=loop-vectorize -C debuginfo=2" cargo build --release`

**Comment by thedrow** [comment]
Maybe I do but that's not very user friendly.

**Comment by steveklabnik** [comment]
Triage: no change

**Comment by thedrow** [comment]
Now that I'm thinking about this, maybe this should be a part of clippy or another linter.

**Comment by matthiaskrgr** [comment]
I don't think that clippy can effectively know which loops LLVM will be able to vectorize.

**Comment by thedrow** [comment]
But clippy compiles the code before analyzing it, doesn't it?
Maybe we can collect all the warnings from LLVM and display them to the user?

**Comment by sfackler** [comment]
Clippy does not compile the code.

**Comment by workingjubilee** [comment]
As rustc has evolved to be much more loosely coupled to its codegen backends, and as such a loosely-coupled front-end it really should not be in the business of replacing existing code-emission analysis tools, I am closing this per the reasoning I elaborated on further over here: https://github.com/rust-lang/rust/issues/66268#issuecomment-1175687091
