### ISSUE TITLE
`if` goto wrong branch in some cases on mips-unknown-linux-musl

### ISSUE THREAD

**Issue by nanpuyue** [rust-lang/rust#57631]
## code
```rust
fn main() {
    let v = 2u64;

    println!("{}", v & 1u64 == 1u64);

    if v & 1u64 == 1u64 {
	println!("true");
    } else {
        println!("false");
    }
}
```
## output
```
# cargo run
   Compiling helloworld v0.1.0 (/root/build/helloworld)
    Finished dev [unoptimized + debuginfo] target(s) in 33.60s
     Running `target/debug/helloworld`
false
true
```
![20190115212448](https://user-images.githubusercontent.com/1524609/51183490-55206880-190c-11e9-8aa1-992064e75855.png)

## environment 

target: `mips-unknown-linux-musl`
system: openwrt 18.06.1
rustc: `1.31.1 (b6c32da9b 2018-12-18)`/`1.33.0-nightly (f381a9625 2019-01-04)`/`1.33.0-nightly (03acbd71c 2019-01-14)`
build: debug

**Comment by nikic** [comment]
Deja vu. This looks very similar to the recent https://bugs.llvm.org/show_bug.cgi?id=40172 in wasm and after taking a quick look at Mips FastISel, it seems to have a similar issue. The branch condition is not zexted.

**Comment by nikic** [comment]
I've reported https://bugs.llvm.org/show_bug.cgi?id=40325 upstream.

**Comment by nagisa** [comment]
P-medium. Thanks for reporting it upstream, @nikic.

**Comment by nikic** [comment]
Fix landed upstream, https://github.com/llvm/llvm-project/commit/fcbd7f64953b04f42dd59f606e45dc8e88a27548 in monorepo.

**Comment by nikic** [comment]
If we didn't cherry-pick before, this fix was part of the LLVM 9 upgrade, so should be fixed in current nightly.
