### ISSUE TITLE
PanicInfo get message in rust stable?

### ISSUE THREAD

**Issue by andreeaflorescu** [rust-lang/rust#57638]
Hey, I was wondering if there is any plan in having the method `message` from `PanicInfo` available in rust stable. The [documentation](https://doc.rust-lang.org/1.29.0/std/panic/struct.PanicInfo.html) points to an issue that is closed (https://github.com/rust-lang/rust/issues/44489).

Related to the following issues in Firecracker:
- [pretty-printing panics](https://github.com/firecracker-microvm/firecracker/issues/837)
- [user inquiry](https://github.com/firecracker-microvm/firecracker/issues/836)

Is there another recommended way to get the panic information? I was also thinking about replacing the panic_hook with catch_unwind but we might get into problems if the external crates that we are using are implementing panic with abort.

**Comment by hellow554** [comment]
IIRC `PanicInfo` implement `Display` which means you can either do `println!("{}", panicinfo)` or `let info = panicinfo.to_string()`. I guess `message` will be removed therefore.

**Comment by andreeaflorescu** [comment]
I can hack my way around this. Thanks for the response.
