### ISSUE TITLE
NLL accepts higher-ranked subtype that non-NLL rejects

### ISSUE THREAD

**Issue by matthewjasper** [rust-lang/rust#57642]
The following code example ([playground](https://play.rust-lang.org?version=nightly&mode=debug&edition=2018&gist=e598eb97e155c66c710959b52ae8e765))

```rust
// #![feature(nll)]

trait X {
    type G;
    fn make_g() -> Self::G;
}

impl<'a> X for fn(&'a ()) {
    type G = &'a ();

    fn make_g() -> Self::G {
        &()
    }
}

trait Y {
    type F;
    fn make_f() -> Self::F;
}

impl<T> Y for fn(T) {
    type F = fn(T);
    
    fn make_f() -> Self::F {
        |_| {}
    }
}

// Always an error, but the message is bad
fn higher_ranked_region_has_lost_its_binder() {
    let x = <fn (&())>::make_g();
}

// Works, but only with feature(nll)
fn magical() {
    let x = <fn (&())>::make_f();
}
```

 produces the output

<details>

```text
error[E0308]: mismatched types
  --> src/lib.rs:31:13
   |
31 |     let x = <fn (&())>::make_g();
   |             ^^^^^^^^^^^^^^^^^^ one type is more general than the other
   |
   = note: expected type `X`
              found type `X`

error[E0308]: mismatched types
  --> src/lib.rs:36:13
   |
36 |     let x = <fn (&())>::make_f();
   |             ^^^^^^^^^^^^^^^^^^ one type is more general than the other
   |
   = note: expected type `Y`
              found type `Y`
```
</details>

The second example also unexpectedly compiles in full NLL mode.

**Comment by nikomatsakis** [comment]
I renamed the title to focus on the part I would most like to investigate, which is why this function works but only with feature-nll:

```rust
// Works, but only with feature(nll)
fn magical() {
    let x = <fn (&())>::make_f();
}
```

That seems like a blocker to disabling migration mode.

**Comment by pnkfelix** [comment]
cc #57895

**Comment by pnkfelix** [comment]
marking P-medium to reflect that this is solely about `#![feature(nll)]`, not migration mode (#58781). When the latter becomes higher priority, this will likewise be raised up.

**Comment by matthewjasper** [comment]
Update: this is only an issue now with `-Zno-leak-check`

**Comment by pnkfelix** [comment]
cc #59490

**Comment by oli-obk** [comment]
Diagnostics triage: this is not a diagnostics issue

**Comment by Aaron1011** [comment]
This is now a compiler error with `-Z no-leak-check`:

```
error: higher-ranked subtype error
  --> test.rs:31:13
   |
31 |     let x = <fn (&())>::make_g();
   |             ^^^^^^^^^^^^^^^^^^^^
```

**Comment by matthewjasper** [comment]
Yes, but it should be two compiler errors, one in make_f and one on make_g.

**Comment by Aaron1011** [comment]
Looking at this further - why don't want want `magical` to compile? It looks perfectly correct to me.

**Comment by Aaron1011** [comment]
On the latest nightly, passing `-Z borrowck=mir -Z no-leak-check` causes `higher_ranked_region_has_lost_its_binder` and `magical` to produce `higher-ranked subtype error`.

I think this is now purely a diagnostic issue, rather than a soundness issue.
