### ISSUE TITLE
Fails to infer associated type bounds with for

### ISSUE THREAD

**Issue by jonhoo** [rust-lang/rust#57671]
The following code does not compile ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=8586a743d1fa146d66ffe832bb113e31)):
```rust
trait Bar<T> {
    type Assoc;
}
impl<'a> Bar<&'a ()> for () {
    type Assoc = Box<Send>;
}

fn oops<C>()
where
    for<'a> C: Bar<&'a ()>,
    for<'a> <C as Bar<&'a ()>>::Assoc: Send,
{
}

fn main() {
    oops::<()>();
}
```
with
```
error[E0277]: `<() as Bar<&'a ()>>::Assoc` cannot be sent between threads safely
  --> src/lib.rs:16:5
   |
16 |     oops::<()>();
   |     ^^^^^^^^^^ `<() as Bar<&'a ()>>::Assoc` cannot be sent between threads safely
   |
   = help: the trait `for<'a> std::marker::Send` is not implemented for `<() as Bar<&'a ()>>::Assoc`
note: required by `oops`
  --> src/lib.rs:8:1
   |
8  | / fn oops<C>()
9  | | where
10 | |     for<'a> C: Bar<&'a ()>,
11 | |     for<'a> <C as Bar<&'a ()>>::Assoc: Send,
12 | | {
13 | | }
   | |_^
```
The issue seems to be that the `for<'a>` does not "carry along" the `Send` bound for `Assoc` in the `impl Bar for ()`. This code compiles on the other hand compiles just fine:
```rust
trait Bar<T> {
    type Assoc;
}
impl<'a> Bar<&'a ()> for () {
    type Assoc = Box<Send>;
}

fn oops<'a, C>()
where
    C: Bar<&'a ()>,
    <C as Bar<&'a ()>>::Assoc: Send,
{
}

fn main() {
    oops::<()>();
}
```
Notice that the only change is that `'a` is now a lifetime parameter of `oops`, which removes the need for the `for<'a>`. I _believe_ the `for<'a>` version should also be correct though?

**Comment by sfackler** [comment]
This looks like a duplicate of #56556.

**Comment by jonhoo** [comment]
@sfackler hmm, yes, I believe that's right! Closing in favor of #56556, and then posting this example code there to add a test case.
