### ISSUE TITLE
unused_extern_crates: wrong suggestion for aliased crate

### ISSUE THREAD

**Issue by ehuss** [rust-lang/rust#57672]
The following suggests converting to a `use`, but that causes it to fail to compile because `use` does not insert into the prelude.

```rust
#![warn(unused_extern_crates)]

extern crate time as time_crate;  // Suggests replacing with `use`.

pub mod m {
    pub use time_crate::Duration;   // But this will fail to compile.
}
```

Perhaps the suggestion should be removed if there is a rename?  

rustc 1.33.0-nightly (2fadb0a16 2019-01-13)
(This is after uniform-paths and the #57557 fix.)

**Comment by sunjay** [comment]
Related case of what seems to be the same issue as this: https://github.com/rust-lang/rust/issues/60222

(Thanks to @ehuss for pointing that out)
