### ISSUE TITLE
[docs] trim_start_matches and trim_end_matches have copy+pasted docs

### ISSUE THREAD

**Issue by vitiral** [rust-lang/rust#57686]
[`trim_start_matches`](https://doc.rust-lang.org/std/string/struct.String.html#method.trim_start_matches) states:

> **Text directionality**
>
> A string is a sequence of bytes. 'Left' in this context means the first position of that byte string; for a language like Arabic or Hebrew which are 'right to left' rather than 'left to right', this will be the right side, not the left.

But "left" is never mentioned XD

Same is true for `trim_end_matches`.

(Note: copy/pasted from `trim_left_matches` and `trim_right_matches`)

**Comment by hellow554** [comment]
Would you mind to open a PR and fix it? ;)
