### ISSUE TITLE
Implementors in documentation aren't clickable

### ISSUE THREAD

**Issue by xfix** [rust-lang/rust#57695]
Compare:

https://doc.rust-lang.org/stable/std/panic/trait.RefUnwindSafe.html
https://doc.rust-lang.org/nightly/std/panic/trait.RefUnwindSafe.html

It's not possible to click on `AtomicBool` in `impl RefUnwindSafe for AtomicBool` anymore, while it is possible on stable and beta.

**Comment by hellow554** [comment]
@GuillaumeGomez

**Comment by hellow554** [comment]
Funny enough, the link is still there, but you can't click it

![grafik](https://user-images.githubusercontent.com/921462/51322120-dee34980-1a64-11e9-8748-8617e0eb3cda.png)

Not entirely sure, but it may be https://github.com/rust-lang/rust/pull/56874 @JohnHeitmann

**Comment by hellow554** [comment]
It is the `display: flex` from the h3. If i remove that attribute with the developer console I can click the link. I'm not very familar with flex (although I heard it is super cool!), so I cannot say what exactly happens here. Maybe a browser bug?

**Comment by GuillaumeGomez** [comment]
I'll take a look (and thanks @m-ou-se for the lead!).

**Comment by JohnHeitmann** [comment]
My change broke that. Sorry folks! @GuillaumeGomez's fix looks good to me.
