### ISSUE TITLE
Distinguish between error vs. warning for external macros

### ISSUE THREAD

**Issue by holygits** [rust-lang/rust#57716]
I often see compiler notes for *warnings* accompanied with this message:
```
   = note: this error originates in a macro outside this <...>
```

would it be more sensible and correct to say `this _warning_ originates...`?

Very superficial but I find seeing "error" in compilation logs catches my eye far too often and
its only a warning. Happy to submit PR if it is a valid change.

**Comment by estebank** [comment]
This can be easily added at

https://github.com/rust-lang/rust/blob/daa53a52a2667533d5fe59bfcc5b8614b79c3d31/src/librustc_errors/emitter.rs#L850-L871

by looking at the [`Diagnostic::code` or, if not available, the`Diagnostic::level`](https://github.com/rust-lang/rust/blob/daa53a52a2667533d5fe59bfcc5b8614b79c3d31/src/librustc_errors/diagnostic.rs#L12-L19) and changing the text accordingly.
