### ISSUE TITLE
Deprecate must_use

### ISSUE THREAD

**Issue by mcandre** [rust-lang/rust#57711]
Could the compiler warn when any trait is unused, without having to explicitly mark each trait source `must_use`?

**Comment by jonas-schievink** [comment]
`must_use` is not for the trait itself, but for values of type `impl Trait` or `dyn Trait`, and causes a warning when a value of that type is dropped without being used.

Warning when traits are unused would be part of the `dead_code` lint which also fires when you have an unused `struct` or other item.

**Comment by Centril** [comment]
@jonas-schievink covers the issue well; for further inquiries I'd recommend elaborating on your designs at http://internals.rust-lang.org/.
