### ISSUE TITLE
rustc is using three versions of rand

### ISSUE THREAD

**Issue by scottmcm** [rust-lang/rust#57724]
I noticed this scrolling by while "Building stage0 compiler artifacts" today:
```rust
   Compiling rand_pcg v0.1.1
   Compiling rand v0.6.1
   Compiling flate2 v1.0.6
   Compiling rand v0.4.3
   Compiling rand v0.5.5
   Compiling winapi-util v0.1.1
```

Optimistically flagging E-easy

**Comment by JohnTitor** [comment]
@scottmcm I'd like to work on this, how can I fix? make rustc use one version(maybe v0.6.1)?

**Comment by JohnTitor** [comment]
@ishitatsuyuki Thanks! When I checked, it seems each rand version is used.

**Comment by ishitatsuyuki** [comment]
Yeah, it's natural that they are all used, and you could try to eliminate those crates using old `rand` by upgrading or refactoring. That said, there isn't much drawback with an older `rand`, so in that case this issue can be just closed.

**Comment by JohnTitor** [comment]
Oh, I'm sorry, I misunderstood. Hmmm, I think we don't have to fix this quickly and this may be a catalyst for a newbie like me to contribute, so I leave this, okay?

**Comment by hellow554** [comment]
@ishitatsuyuki but one could argue that it will lower the time to compile so it's worth to fix IMHO ;)

**Comment by JohnTitor** [comment]
Uh, would it be better to fix?

**Comment by hellow554** [comment]
Disclaimer: I'm not a core member, but IMHO this is worth fixing. Also scottmcm who is a core member opened this issue, so I guess you're good to go and fix that issue @JohnTitor :)

**Comment by JohnTitor** [comment]
Okay, I want to try to fix. For instance, `crossbeam-channel` depends on `rand v0.5.5`, how can I update or refactor this?

**Comment by scottmcm** [comment]
@hellow554 I'm not on compiler (or core), so don't take my word on this one :slightly_smiling_face: 

@JohnTitor It looks like upstream rayon needs 0.5, so you could consider making a PR to upgrade it to 0.6.  (Maybe [ask someone on rayon first](https://gitter.im/rayon-rs/Lobby).)  Also, it seems that [rustc-rayon hasn't been updated in 6+ months](https://github.com/rust-lang-nursery/rustc-rayon/commits/fiber), so they'd probably appreciate a PR to upgrade it to newer upstream.

**Comment by cuviper** [comment]
Current rayon only uses rand as a dev-dependency, since rayon-rs/rayon#571. That wouldn't show up in Cargo.lock here at all, if rustc-rayon follows suit.

**Comment by lnicola** [comment]
So the latest versions are `rustc-rayon 1.0.3` and `rustc-rayon-core 1.4.1`, but `0.1.1` is used in this repository. They come from `librustc_data_structures`. Maybe those dependencies should be updated?

**Comment by polybuildr** [comment]
It looks like this was fixed in PR #58908 and merged by bors. Should this issue be closed now?

**Comment by sfackler** [comment]
There are still 3 versions of rand in use: https://github.com/rust-lang/rust/blob/master/Cargo.lock#L4173-L4175

**Comment by mati865** [comment]
https://github.com/rust-lang/rust/pull/58805 will remove rand 0.5, I can get rid of 0.4 anytime but there are many PRs modifying Cargo.lock right now.

**Comment by lnicola** [comment]
Update: `rand 0.4.3` is used by `phf_generator`, `rayon_core` and `redox_users`.

**Comment by cuviper** [comment]
That's with `rayon-core 1.4.0` -- `1.4.1` only uses `rand 0.5` as a dev-dependency.

**Comment by lnicola** [comment]
I didn't check now, but at some point `rustc` was using an old version of a custom fork of `rayon`.

**Comment by cuviper** [comment]
`rustc-rayon` has rebased since then, so it already reflects that dependency change.

**Comment by lnicola** [comment]
I tried to fix a part of this in https://github.com/rust-lang/rust/pull/61597, but it didn't come out as planned. There is dependency and license whitelist that needs to be updated.

I think just running `cargo update` leaves only one usage of `rand 0.4` via `ammonia` and `mdbook 1` (which can be updated). But then there is the licensing story, and it's not very clear to me which dependencies are used by the tools, and which by the compiler.

**Comment by mati865** [comment]
Last time I checked `mdbook` was the only thing preventing of `rand 0.4`, otherwise I'd fix it already.
We are working on removing it but it's blocked on releasing new version of `mdbook`.

**Comment by lnicola** [comment]
I think `rustc-rayon` goes away after a `cargo update`, so that one might be easy to fix.

**Comment by mati865** [comment]
So `rustc-rayon` released new version since.

> Is it just that most of them are for the tools, not for std and rustc?

Correct, dependencies of everything that is created by `dist` are tracked by single `Cargo.lock`.

> Does somebody run cargo update from time to time?

Dependencies are often updated separately as needed because upgrading everything at once is likely to break something and it's easier to find what is wrong when you change like 5 dependencies instead of 50.

**Comment by mati865** [comment]
Also you can run the same image that found the error (`x86_64-gnu-llvm-6.0` in this case) by using these steps https://github.com/rust-lang/rust/blob/master/src/ci/docker/README.md
