### ISSUE TITLE
Rustdoc: quoted code in fake italics

### ISSUE THREAD

**Issue by tspiteri** [rust-lang/rust#57748]
For example in the `i32` primitive documentation, there is some text in italics: “See also the `std::i32` module.” I think the “`std::i32`” part should not be in italics. BTW, the italics are fake italics, as the stylesheet does not provide the italics for the monospace font.

![screenshot_2019-01-18 i32 - rust](https://user-images.githubusercontent.com/18604588/51415071-d1b58000-1b74-11e9-9aae-5dd39b7093f7.png)

**Comment by GuillaumeGomez** [comment]
No, it's working as expected from the commonmark spec. You can test "\*foo \`i32\` blabla\*" [here](https://spec.commonmark.org/dingus/).
