### ISSUE TITLE
Impl Drop for a global_allocator silently fails

### ISSUE THREAD

**Issue by sheredom** [rust-lang/rust#57753]
I've been experimenting with the GlobalAlloc API and came across a perhaps interesting failure:

```
extern crate libc;

use std::alloc::{GlobalAlloc, Layout};

pub struct TestAllocator;

unsafe impl Sync for TestAllocator {}

impl Drop for TestAllocator {
    fn drop(&mut self) {
        panic!("Never hit!"); // No compile time warning, no runtime panic!
    }
}

unsafe impl GlobalAlloc for TestAllocator {
    unsafe fn alloc(&self, layout: Layout) -> *mut u8 { libc::memalign(layout.align(), layout.size()) as *mut u8 }
    unsafe fn dealloc(&self, ptr: *mut u8, _layout: Layout) { libc::free(ptr as *mut libc::c_void); }
}

#[global_allocator]
static A: TestAllocator = TestAllocator;
```

I am new enough to rust that I thought I could add a drop method to a static - which I think is not expected to be supported. But the compiler didn't error to tell me that implementing Drop wasn't supported, and I spent quite a bit of time trying to work out why lldb wasn't hitting the breakpoint in my drop method!

Would it be possible to make the compiler error here? Or at least warn the user that the drop method will never be called?

Link to the playground https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=2b5b2fc9ea97526cb0c14d5341e9a78d

**Comment by nagisa** [comment]
`Drop` types in statics weren’t allowed before and the decision to allow and ignore the drop was made through consensus via the RFC process: [#1440](https://github.com/rust-lang/rfcs/blob/master/text/1440-drop-types-in-const.md).

**Comment by sheredom** [comment]
Hey @nagisa - thanks for the info! Since y'all have already decided this I'll put my problems down to newness with the language. Feel free to close this issue!
