### ISSUE TITLE
-ized/-ised spelling inconsistency in AST

### ISSUE THREAD

**Issue by zackmdavis** [rust-lang/rust#57773]
(A tiny spelling nit I noticed while reviewing #57768; may be suitable for a new contributor to practice getting started with building `rustc`. I _think_ we prefer the American spelling _-ized_, but maybe someone could confirm this?)

https://github.com/rust-lang/rust/blob/0c0c585281740aba4c91cbfd385f5e1fbe313d11/src/libsyntax/ast.rs#L139

**Comment by jonas-schievink** [comment]
Yes, AFAIK we use American spelling everywhere (as do most projects).
