### ISSUE TITLE
Book chapter about Advanced Lifetimes contains no longer relevant example

### ISSUE THREAD

**Issue by hseeberger** [rust-lang/rust#57785]
Since 1.31.0 chapter 19.2 about Advanced Lifetimes, subchapter [Ensuring One Lifetime Outlives Another with Lifetime Subtyping](https://doc.rust-lang.org/book/ch19-02-advanced-lifetimes.html#ensuring-one-lifetime-outlives-another-with-lifetime-subtyping), contains an example which is no longer relevant: thanks to new lifetime elision rules it is not necessary to explicitly specify the lifetime subtype.

Maybe we should change the code example to something like this:

```rust
fn shorter<'a, 'b: 'a>(s1: &'a str, s2: &'b str) -> &'a str {
    if s1.len() < s2.len() {
        s1
    } else {
        s2
    }
}
```

**Comment by jonas-schievink** [comment]
The section has been removed from the book.
