### ISSUE TITLE
can't compile under 32-bit Linux

### ISSUE THREAD

**Issue by mauricev** [rust-lang/rust#57797]
I'm emerging rust under 32-bit funtoo. Portage internally downloads the source, prepares and runs whatever compiling is needed. It fails as follows:

Compiling bootstrap v0.0.0 (/var/tmp/portage/dev-lang/rust-1.32.0/work/rustc-1.32.0-src/src/bootstrap)
    Finished dev [unoptimized] target(s) in 1m 52s
failed to parse TOML configuration '/var/tmp/portage/dev-lang/rust-1.32.0/work/rustc-1.32.0-src/config.toml': expected a table key, found a right bracket at line 33
failed to run: /var/tmp/portage/dev-lang/rust-1.32.0/work/rustc-1.32.0-src/build/bootstrap/debug/bootstrap build --config=/var/tmp/portage/dev-lang/rust-1.32.0/work/rustc-1.32.0-src/config.toml -j2 --exclude src/tools/miri
Build completed unsuccessfully in 0:01:58

This error doesn't appear under 64-bit Funtoo, so it appears related to the fact the build environment above is 32-bit.

**Comment by hellow554** [comment]
Can you show us the content of `/var/tmp/portage/dev-lang/rust-1.32.0/work/rustc-1.32.0-src/config.toml`?

**Comment by mauricev** [comment]
[llvm]
optimize = true
release-debuginfo = false
assertions = false
targets = "X86"
[build]
build = "i686-unknown-linux-gnu"
host = ["i686-unknown-linux-gnu"]
target = ["i686-unknown-linux-gnu"]
cargo = "/var/tmp/portage/dev-lang/rust-1.32.0/work/rust-stage0/bin/cargo"
rustc = "/var/tmp/portage/dev-lang/rust-1.32.0/work/rust-stage0/bin/rustc"
docs = false
submodules = false
python = "python3.6"
locked-deps = true
vendor = true
extended = false
tools = []
[install]
prefix = "/usr"
libdir = "lib/rust-1.32.0"
docdir = "share/doc/rust-1.32.0"
mandir = "share/rust-1.32.0/man"
[rust]
optimize = true
debuginfo = false
debug-assertions = false
use-jemalloc = true
default-linker = "i686-pc-linux-gnu-gcc"
channel = "stable"
rpath = false
lld = false
[target.]
cc = "i686-pc-linux-gnu-gcc"
cxx = "i686-pc-linux-gnu-g++"
linker = "i686-pc-linux-gnu-gcc"
ar = "i686-pc-linux-gnu-ar"

**Comment by mauricev** [comment]
Under 64-bit, the line [target.] says [target.x86_64-pc-linux-gnu], so it seems that under 32-bit, the rust compilation is leaving this line incorrectly blank. Presumably, it should read [target.i686-pc-linux-gnu].

**Comment by hellow554** [comment]
Just a nitpick: Please surround your `Cargo.toml` content with \`\`\` so it appears as code block, thanks :)

**Comment by mauricev** [comment]
There you go.

**Comment by hellow554** [comment]
You removed the `[llvm]` tag at the top and the \`\`\` in the end need to be in a single line (sorry ^^)

**Comment by mauricev** [comment]
Fixed.

**Comment by xen0n** [comment]
So this is at most a packaging issue, and this upstream issue could perhaps be closed? Usually such build failures are to be reported to the distro bug tracker first, not to mention the distro is actually Gentoo-based...
