### ISSUE TITLE
Spelling suggestions should consider trailing exclamation points

### ISSUE THREAD

**Issue by bstrie** [rust-lang/rust#5780]
```
< sawrubh> suppose I wrote assert instead of assert!, I get this message
           : unresolved name: `assert`. Did you mean: `result`? what's
           the thing which generates the last suggestion
< sawrubh> I think that suggesting that I'm missing an ! would be more
           helpful, so just wondering who decides and how it decides what
           to suggest as the solution
```
As an aside, `assert` -> `result` is still a hilariously large edit distance.

**Comment by frewsxcv** [comment]
Still an issue (same input/output as @huonw's comment above)

**Comment by Manishearth** [comment]
This can be done by holding on to the SyntaxEnv (or just a vec of strings built from the syntaxenv) after `expand_crate` and passing it down to librustc_resolve through the driver. Not exactly a clean solution, but not too bad either.

**Comment by Manishearth** [comment]
https://github.com/rust-lang/rust/pull/29968
