### ISSUE TITLE
Beta standard library docs do not show signature for linked methods

### ISSUE THREAD

**Issue by tspiteri** [rust-lang/rust#57814]
For example, https://doc.rust-lang.org/beta/std/primitive.i8.html#method.min_value shows:
![screenshot_2019-01-21 i8 - rust](https://user-images.githubusercontent.com/18604588/51493085-5f32e300-1db4-11e9-8219-38245d1bc83a.png)

In nightly, the signature is shown but unhighlighted, for example https://doc.rust-lang.org/nightly/std/primitive.i8.html#method.min_value shows:
![screenshot_2019-01-21 i8 - rust 1](https://user-images.githubusercontent.com/18604588/51493158-af11aa00-1db4-11e9-8792-d75f584ac9bb.png)

**Comment by hellow554** [comment]
Related: https://github.com/rust-lang/rust/issues/57628

**Comment by QuietMisdreavus** [comment]
@GuillaumeGomez https://github.com/rust-lang/rust/pull/57646 needs to be backported, but it also looks like the yellow highlight doesn't show any more?

**Comment by GuillaumeGomez** [comment]
Ah, a new issue. I'll fix it quickly.

**Comment by tspiteri** [comment]
@GuillaumeGomez This is fixed in the nightly page, but not in the beta page. Is this going to be fixed in beta before the 1.33.0 release?

**Comment by GuillaumeGomez** [comment]
It hasn't been backported? Urg...

**Comment by tspiteri** [comment]
Seems to be fixed now.
