### ISSUE TITLE
[LLVM9+] Use llvm.psub in offset_from

### ISSUE THREAD

**Issue by scottmcm** [rust-lang/rust#57818]
Ref http://lists.llvm.org/pipermail/llvm-dev/2019-January/129095.html & https://reviews.llvm.org/D56598

offset_from tracking issue: https://github.com/rust-lang/rust/issues/41079

Previous discussion about `offset_from` wanting a different subtraction mode than existed in LLVM at the time: https://github.com/rust-lang/rust/issues/41079#issuecomment-375840978

(Hmm, Ralf was CC'd on the llvm-dev mail suggesting this, so I bet this is exactly what we need :slightly_smiling_face:)

**Comment by nagisa** [comment]
There does not appear to be consensus on the feature yet and I suspect that the instruction/intrinsic will go through many iterations before landing, if at all.

**Comment by scottmcm** [comment]
Agreed this is not currently actionable, @nagisa.  (I should have put that in the op, not just the 9+ in the title.) Feel free to close this for now in you prefer.

**Comment by nagisa** [comment]
It seems enough to have a mention of this in the tracking issue. I’m fairly confident we will eventually notice when/if psub actually happens anyway.

Closing.
