### ISSUE TITLE
Rust documentation for Instant::elapsed() missing prototype

### ISSUE THREAD

**Issue by penguin359** [rust-lang/rust#57824]
The documentation for the elapsed() method of std::time::Instant is missing it's prototype in the generated documentation for the current Beta release. The issue can be seen here:

https://doc.rust-lang.org/beta/std/time/struct.Instant.html#method.elapsed

It appears to already be fixed on the nightly release, but it should be backported to Beta.

**Comment by hellow554** [comment]
Is this the same as https://github.com/rust-lang/rust/issues/57814 ?

**Comment by GuillaumeGomez** [comment]
Yes it is. Closing it. Thanks @penguin359!
