### ISSUE TITLE
Add an is_default() to Default trait

### ISSUE THREAD

**Issue by aledomu** [rust-lang/rust#57838]
I wanted to ask if this an addition small enough to not need the whole RFC + discussion process.

My idea, which is something at times I wished was there, is to add an implemented method to the `Default` trait like this:

```rust
pub trait Default {
    ...
    pub fn is_default(&self) -> bool {
        self == Self::default()
    }
}
```

Note that the method automatically works for any struct that implements `Default::default()`.

Let me know what you think.

**Comment by aledomu** [comment]
I didn't give this a second thought but you're right. Anyways what I wanted to highlight is the idea behind the example.

**Comment by Centril** [comment]
Since this doesn't seem backwards compatible I'll go ahead and close the issue. For follow ups I'd recommend http://internals.rust-lang.org/.
