### ISSUE TITLE
repr(simd) struct with one i64 element incorrectly emits x86_mmx

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/rust#57832]
Reproducer ([godbolt](https://gcc.godbolt.org/z/Wk6IMd)):

```rust
#[repr(simd)] pub struct Foo(i64);
#[no_mangle] pub fn foo(x: Foo) -> Foo { x } 
```

on x86_64 emits

```llvm
define void @foo(x86_mmx* noalias nocapture sret dereferenceable(8), x86_mmx* noalias nocapture readonly dereferenceable(8) %x) unnamed_addr #0 {
  %1 = bitcast x86_mmx* %x to i64*
  %2 = load i64, i64* %1, align 8
  %3 = bitcast x86_mmx* %0 to i64*
  store i64 %2, i64* %3, align 8
  ret void
}
```

It should be emitting a `<1 x i64>` type instead. The `x86_mmx` type forces the use of MMX registers and comes with its huge bag of pitfalls when interfacing between MMX and x87 code. 

Access to this type should be provided on x86 and x86_64 somehow else, maybe using a `repr(simd_x86_mmx)` ?  This type is only relevant for `core::arch` when implementing `__m64` on x86/x86_64 anyways. 

Internally, we probably want to treat `x86_mmx` as a vector type in rustc, but it should be a vector type different from all other vector types. Maybe we can add a `.is_mmx()` method to the `simd_vector` types that can be used to query whether a 64-bit wide vector is an x86_mmx type. I don't remember if whether a vector type is `x86_mmx` or a normal vector types matters anywhere in rustc except for when doing codegen for the vector type.

**Comment by workingjubilee** [comment]
Rust no longer supports using MMX intrinsics or emitting MMX instructions (except possibly via inline assembly). The reproducer now generates

```llvm
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

define void @foo(<1 x i64>* noalias nocapture sret dereferenceable(8) %0, <1 x i64>* noalias nocapture readonly dereferenceable(8) %x) unnamed_addr #0 {
  %1 = getelementptr inbounds <1 x i64>, <1 x i64>* %x, i64 0, i64 0
  %2 = load i64, i64* %1, align 8
  %3 = getelementptr inbounds <1 x i64>, <1 x i64>* %0, i64 0, i64 0
  store i64 %2, i64* %3, align 8
  ret void
}

attributes #0 = { nofree norecurse nounwind nonlazybind uwtable "probe-stack"="__rust_probestack""target-cpu"="x86-64" }

!llvm.module.flags = !{!0, !1}

!0 = !{i32 7, !"PIC Level", i32 2}
!1 = !{i32 2, !"RtLibUseGOT", i32 1}
```

This issue can be closed.
