### ISSUE TITLE
dbg!() without parameters

### ISSUE THREAD

**Issue by inv2004** [rust-lang/rust#57845]
Hello,
I found **dbg!(..)** is very useful, but, unfortunately it does not support **dbg!()** without expression, which could help to debug your program also.

I found that **println!()** did not work in first versions also, but later it was fixed, that is why I suppose **dbg!()** has the same story.

dbg!(()) is ok, but its just workaround.

Thank you,

**Comment by mark-i-m** [comment]
Could you make a PR for this?
