### ISSUE TITLE
compiletest: previously-succeeding tests are still rerun.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#57864]
Running e.g. `./x.py test --stage 1 src/test/mir-opt` several times currently results in all the tests being ran every single time, instead of skipping those that succeeded already.

I'm not sure when this started happening, but it's recent, somewhere in the past few weeks.
It could perhaps be caused by #56680, although I don't recall having issues around the time that PR was merged. Also, I have no indication that anyone else has this issue, could be my build dir.

cc @Mark-Simulacrum

**Comment by euclio** [comment]
See #57529 as well.

**Comment by oli-obk** [comment]
I can confirm this happening on my machine, too. I've only had this for a few days though (definitely not last week) and I rebase very frequently

**Comment by Mark-Simulacrum** [comment]
I will attempt to investigate this tonight and try and get a fix out soon, but not sure yet if I'll have the time.

**Comment by Mark-Simulacrum** [comment]
I've posted the fix at #57871
