### ISSUE TITLE
Segfault in cast over empty from heap

### ISSUE THREAD

**Issue by botika** [rust-lang/rust#57868]
It is complicated to describe. 

I leave it how to reproduce it in all versions.
https://gist.github.com/botika/54c88efd4884a3c0e5af52d1a59a0a5e

When a pointer to a something empty is cast, it fails with segfault when the pointer comes from the heap.

Issue:
https://github.com/rust-iendo/v_htmlescape/issues/17
PR:
https://github.com/rust-iendo/v_htmlescape/pull/18

**Comment by sfackler** [comment]
You are loading 32 bytes from a 0 byte allocation. That's undefined behavior.

**Comment by botika** [comment]
I know, but in both cases the same thing happens and only fails in one. 
Could not point to the same place in the 2 cases? 

Otherwise I will have to check the length of the slice at 0. And I do not like anything when it should be a valid pointer in two cases.

**Comment by sfackler** [comment]
Undefined behavior is undefined. It happens to be the case that today, under those optimization settings, one of those calls doesn't segfault but tomorrow it could start, or launch nethack, or do anything else.

**Comment by botika** [comment]
I understand, that is to say that to cast pointers I have to make sure before they slice have the minimum length, always, if I do not want to have an unexpected behavior. 

Thanks for your time. 
I close
