### ISSUE TITLE
Direct coercion from closures to `unsafe fn` pointers

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#57883]
While you can coerce closures to `fn` pointers, it is currently not possible to coerce closures to `unsafe fn` pointers since that requires a transitive coercion from `fn` pointers to `unsafe fn` pointers. We do not allow transitive coercions. Example:
```rust
static A: fn() = || {}; // OK
static B: unsafe fn() = A; // OK
static C: unsafe fn() = || {}; // ERROR; would require the two coercions above transitively.
```
This behavior of current Rust was unexpected in https://github.com/rust-lang/rfcs/pull/2592#discussion_r250462675.

@cramertj had the idea to implement an immediately attainable direct coercion between closures and `unsafe fn` pointers rather than go the more complex and contentious route of transitive coercions (which may have unforeseen consequences). This idea seems reasonable to me.

cc @nikomatsakis @arielb1 

PS: should we fcp the PR once made?

**Comment by cramertj** [comment]
> should we fcp

Traditionally we've just accepted PRs for transitive coercions, since they already have a standing RFC. One of these was actually one of my first rustc changes: https://github.com/rust-lang/rfcs/issues/1762

**Comment by arielb1** [comment]
Looks like just a bug.
