### ISSUE TITLE
Regression in match patterns in beta

### ISSUE THREAD

**Issue by Razican** [rust-lang/rust#57894]
Hello, the pattern matching in match arms seems to have different behavior in stable than in beta/nightly.

I tried this code:

```rust
use std::i8;

fn main() {
    let a = Some(-50_i8);
    match a {
        Some(c @ i8::MIN...-101) | Some(c @ 101...i8::MAX) => println!("out of bounds, {}", c),
        _ => println!("OK"),
    }
}
```

I expected to see this happen: In all chains, it should print "OK".

Instead, this happened: It prints "OK" in stable, but it prints "out of bounds, -50" in beta/nightly.

[Example in the playground](https://play.rust-lang.org/?version=beta&mode=debug&edition=2018&gist=0874084dd8b91a733ffaf7c7fa32d5c8)

I understand that this code is not very idiomatic, but still, I think that the behavior should be consistent between Rust versions.

**Comment by jonas-schievink** [comment]
Introduced between `nightly-2018-12-14` and `nightly-2018-12-15`, resp.

    rustc 1.32.0-nightly (f4a421ee3 2018-12-13)

    rustc 1.33.0-nightly (96d1334e5 2018-12-14)

[Commits between those nightlies](https://github.com/rust-lang/rust/compare/f4a421ee3...96d1334e5)

**Comment by varkor** [comment]
https://github.com/rust-lang/rust/pull/56695 does look like the culprit. I'll try to fix this tomorrow. Thanks @jonas-schievink!

**Comment by pnkfelix** [comment]
triage: P-high. Assigning to @varkor
