### ISSUE TITLE
rustdoc: broken link for logo on settings page

### ISSUE THREAD

**Issue by dhardy** [rust-lang/rust#57892]
Running `cargo doc` locally builds a `settings.html` page with the Rust project logo in the top-left corner. This logo URL and its link target seem to be hard-coded?
```html
<a href='.//index.html'><img src='https://www.rust-lang.org/logos/rust-logo-128x128-blk.png' alt='logo' width='100'></a>
```
The link target `index.html` does not exist. (IIRC the rustdoc team made a deliberate decision not to generate this page, though personally I think it should exist since multiple crates may be documented from the same repo.)

I believe this is a change in a very recent version of the nightly compiler. [Our hosted doc](https://rust-random.github.io/rand/settings.html) does not include the logo, presumably because it has not been updated since (cargo deadlinks spots the broken URL and makes the test fail).

Also see: https://github.com/deadlinks/cargo-deadlinks/issues/36

**Comment by GuillaumeGomez** [comment]
Taking a look.
