### ISSUE TITLE
rustc 1.32 using system LLVM-7 crashes with: error: failed to load bc of "core.9adngr8s-cgu.0": Invalid record

### ISSUE THREAD

**Issue by Whissi** [rust-lang/rust#57903]
On Gentoo Linux we have the same problem like reported in #57762, downstream bug: https://bugs.gentoo.org/675752

I now applied the two patches (https://github.com/llvm-mirror/llvm/commit/da1fb72bb305d6bc1f3899d541414146934bf80f and https://github.com/llvm-mirror/llvm/commit/cc1f2a595ead516812a6c50398f0f3480ebe031f) to our llvm-7 version but fd (https://github.com/sharkdp/fd) is still failing to build. New error is:

```
INFO 2019-01-25T18:55:20Z: rustc_codegen_llvm::back::lto: linking "core.9adngr8s-cgu.0"
error: failed to load bc of "core.9adngr8s-cgu.0": Invalid record

error: aborting due to previous error
[...]
Could not compile `fd-find`.), unknown: false, exit_code: 101 }
error: Could not compile `fd-find`.
```

Please see the attached verbose build.log.
[build.log.zip](https://github.com/rust-lang/rust/files/2797432/build.log.zip)

**Comment by Whissi** [comment]
Patching rust iwth https://github.com/rust-lang/rust/commit/1c95f5a34c14f08d65cdd198827e3a2fcb63cf39 doesn't help.

**Comment by nagisa** [comment]
There is a somewhat conflicting signal – the [comment 16](https://bugs.gentoo.org/675752#c16) seems to say that the patch does fix the compilation issue.

Would it be possible to get the sample file that is referenced in the error message (use `-Csave-temps` and `-Ccodegen-units=1`)?

**Comment by Whissi** [comment]
Not sure if I did it the right way, I set `RUSTFLAGS="-Csave-temps -Ccodegen-units=1" ` environment variable. Here's the complete target directory, I hope it is included: https://dev.gentoo.org/~whissi/stuff/fd-7.2.0_target_201901252245.tar.xz

**Comment by nagisa** [comment]
Ah, my bad. It seems that the failing bytecode comes from libcore, so it won’t be included in the `target/`.

**Comment by gyakovlev** [comment]
looks like we figured it out, https://github.com/rust-lang/rust/commit/1c95f5a34c14f08d65cdd198827e3a2fcb63cf39 actually fixes rust with system installed llvm-7

**Comment by Whissi** [comment]
Right. The problem `error: failed to load bc of "core.9adngr8s-cgu.0": Invalid record` seems to be caused by sccache usage I tried while I started to investigate the original issue #57762 before the bug + solution was filed here to speed up bisect a little bit :/
