### ISSUE TITLE
Nightly regression: Can't perform LTO when compiling incrementally

### ISSUE THREAD

**Issue by PvdBerg1998** [rust-lang/rust#57947]
I updated to the nightly `2019-01-27 msvc` from `2019-01-25 msvc` and my release profile using `lto = true` broke.

The error message given is `Can't perform LTO when compiling incrementally`.

**Comment by Mark-Simulacrum** [comment]
Cc @michaelwoerister - related to Cargo release changes, I suspect.

**Comment by nagisa** [comment]
This is a cargo bug, with a fix at https://github.com/rust-lang/cargo/pull/6610. Closing.
