### ISSUE TITLE
rustc compiles feature AVX into cpu-target=core2

### ISSUE THREAD

**Issue by frehberg** [rust-lang/rust#57945]
rustc can be told to use target-features, even if not supported by target CPU is , for example AVX on Core2
```
$ /opt/src/rust-1.32.0/bin/rustc -C opt-level=3 -C target-cpu=core2 -C lto -C codegen-units=1 -C target-feature=+avx2,+fma nbody.rs -o nbody.rust-7.rust_run

$ ./nbody 500
Illegal instruction (core dumped)
```

I would expect rustc terminating the compilation with error, if target-feature=X is not supported by target-cpu=Y

Please see the features supported by cpu-target "core2"
```shell
$ rustc --print cfg -C target-cpu=core2 -C opt-level=3
target_arch="x86_64"
target_endian="little"
target_env="gnu"
target_family="unix"
target_feature="fxsr"
target_feature="sse"
target_feature="sse2"
target_feature="sse3"
target_feature="ssse3"
target_os="linux"
target_pointer_width="64"
unix
```

**Comment by nagisa** [comment]
This behaviour is intended. The instruction set used is not specified by `target-cpu` specifically, but rather by a set of `target-features`, some of which are implied by `target-cpu` itself.
