### ISSUE TITLE
Tracking issue for `.trailing_ones()` + `leading_ones()`

### ISSUE THREAD

**Issue by yoshuawuyts** [rust-lang/rust#57969]
This is a tracking issue for the feature `leading_trailing_ones` which adds `trailing_ones` and `leading_ones` to all primitive integer types. (`trailing_zeros` and `leading_zeros` already existed before.)

**TODO**:

- [x] Merge implementation #68165 
- [ ] Adjust documentation ([see instructions on rustc-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-guide][stabilization-guide])

[stabilization-guide]: https://rust-lang.github.io/rustc-guide/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rust-lang.github.io/rustc-guide/stabilization_guide.html#documentation-prs

**Unresolved questions**
- none so far?

## Implementation History
- Initial implementation https://github.com/rust-lang/rust/pull/68165
- Stabilization PR https://github.com/rust-lang/rust/pull/73032

**Comment by nagisa** [comment]
Lets repurpose this into a tracking issue so that you would have stuff to put into the tracking issue in the PR...

**Comment by SimonSapin** [comment]
Closing since https://github.com/rust-lang/rust/pull/55715 did not land. Feel free to reopen if/when it does.

**Comment by crlf0710** [comment]
Now that here's another PR(#68165), maybe we should reopen this issue? @SimonSapin @nagisa

**Comment by djc** [comment]
So we've had this for a while now, and it would be nice to stabilize. Seems pretty simple. Libs team folks?

**Comment by jplatte** [comment]
Stabilized in #73032, this issue should probably be closed.
