### ISSUE TITLE
Tracking issue for Weak::{weak_count, strong_count}

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/rust#57977]
This issue tracks stabilization for 4 methods added in https://github.com/rust-lang/rust/pull/56696:

* `std::rc::Weak::{strong_count, weak_count}`
* `std::sync::Weak::{strong_count, weak_count}`

**Comment by bdonlan** [comment]
Although these were added for testing, it is occasionally useful to have a way to probe optimistically for whether a weak pointer has become dangling, without actually taking the overhead of manipulating atomics. Are there any plans to stabilize this?

**Comment by glebpom** [comment]
Having this stabilized would help. Currently, the only way to check if a weak pointer has become dangling is to call `upgrade`, which is by far expensive.

**Comment by stepancheg** [comment]
> Currently, the only way to check if a weak pointer has become dangling is to call upgrade, which is by far expensive

Exactly my thoughts. So instead of stabilizing `strong_count` and `weak_count` we probably want `fn has_strong(&self) -> bool`.

**Comment by alexcrichton** [comment]
A [concern has been listed](https://github.com/rust-lang/rust/pull/65778#issuecomment-548241446) for stabilization, so if those here interested in this would be willing to help out with that, that would be great!
