### ISSUE TITLE
AppVeyor spuriously killing a dist- job with message "Build exceeded allowed resource quotas"

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#58025]
Symptom: A job on AppVeyor (currently all are `dist-x86_64-mingw`) is killed while creating the setup EXE, with the AppVeyor message

> Build exceeded allowed resource quotas. Fix your build to consume less resources or contact AppVeyor support to request quotas increase.

We guess the quota mentioned is the [disk space](https://github.com/rust-lang/rust/pull/58079#issuecomment-459995579). 

https://github.com/rust-lang/rust/pull/57514#issuecomment-459108022 (2019-01-30T21:04:02Z) is the first known instance. This error is occurring once to twice per day.

**Comment by mati865** [comment]
#57514 passed after retry.

When comparing logs:
* failure: https://ci.appveyor.com/project/rust-lang/rust/builds/22006972/job/7ooc207am74l0w8p
* success: https://ci.appveyor.com/project/rust-lang/rust/builds/22023180/job/rj0c96ymab0thxk2

Both get to the point:
```
Successful compile (288.031 sec). Resulting Setup program filename is:
C:\projects\rust\build\tmp\dist\exe\rust-nightly-x86_64-pc-windows-gnu.exe
rust.wxs
ui.wxs
rustwelcomedlg.wxs
RustcGroup.wxs
DocsGroup.wxs
CargoGroup.wxs
StdGroup.wxs
ClippyGroup.wxs
MiriGroup.wxs
AnalysisGroup.wxs
GccGroup.wxs
```
Then failed job output stops (process hangs?) while successful job prints warnings for `.wsx` objects and finishes the build.

**Comment by kennytm** [comment]
I've replaced the issue description and title with the actual issue.

**Comment by pietroalbini** [comment]
[Contacted AppVeyor support about this](https://help.appveyor.com/discussions/problems/20562-build-exceeded-allowed-resource-quotas).

**Comment by pietroalbini** [comment]
According to AppVeyor support [the problem was disk space](https://help.appveyor.com/discussions/problems/20562-build-exceeded-allowed-resource-quotas#comment_46980631), and they increased our quota by 10Gb. Closing this.
