### ISSUE TITLE
rustc 1.34.0-nightly (da6ab956e 2019-01-27) and later make encoding_rs with packed_simd go from one .s to 31 .rcgu.s files

### ISSUE THREAD

**Issue by hsivonen** [rust-lang/rust#58023]
# Steps to reproduce

1. Clone https://github.com/hsivonen/encoding_rs
2. `cd encoding_rs`
3. `git checkout simd`
4. `rustup default rustup default 1.32.0`
5. `rustup target add  armv7-unknown-linux-gnueabihf`
6. `RUSTC_BOOTSTRAP=1 RUSTFLAGS='-C target_feature=+neon,+thumb-mode,+thumb2' cargo rustc --target armv7-unknown-linux-gnueabihf --features simd-accel --release -- --emit asm`
7. `find target | grep -c '\.s$'`
8. `rm -rf target`
9. `git checkout packed_simd`
10. `rustup default nightly`
11. `rustup target add thumbv7neon-unknown-linux-gnueabihf`
12. `cargo rustc --target thumbv7neon-unknown-linux-gnueabihf --features simd-accel --release -- --emit asm`
13. `find target | grep -c '\.s$'`

# Actual results

In the `simd` + Rust 1.32 case, there is one `.s` file. In the `packed_simd` + Rust 1.34 case, `encoding_rs` is split across 31 `.s` files. These are all `.rcgu.s` files. Examining these files suggests lesser inlining within `encoding_rs`, although code from `packed_simd` and `core::arch` appears to have gotten inlined.

# Expected result

Expected one `.s` file with the same level of inlining in the `packed_simd` + Rust 1.34 case as with the `simd` + Rust 1.32 case.

# Additional info

When building an actual binary from a different top-level crate (`encoding_bench`), the  `packed_simd` + Rust 1.34 case regresses performance relative to the `simd` + Rust 1.32 on Exynos 5.

**Comment by hsivonen** [comment]
`RUSTFLAGS='-C codegen-units=1' cargo rustc --target thumbv7neon-unknown-linux-gnueabihf --features simd-accel --release -- --emit asm` does not change things.

**Comment by hsivonen** [comment]
> do you have a `cargo/.config` or custom profiles

I don't have a `cargo` directory under `encoding_rs`. I don't have `.config` or `config` under `~/.cargo`. I'm not aware of having custom profiles.

**Comment by hsivonen** [comment]
One `.s` with 1.33.0-beta.4. Must be a _very_ recent change.

**Comment by hsivonen** [comment]
First nightly with 31 `.s` files: rustc 1.34.0-nightly (da6ab956e 2019-01-27)
Last nightly with one `.s` file: rustc 1.33.0-nightly (20c2cba61 2019-01-26)

**Comment by hsivonen** [comment]
[GitHub comparison of the two.](https://github.com/rust-lang/rust/compare/20c2cba61dc83e612d25ed496025171caa3db30f...da6ab956e1002517803ecd38b904504a1223274b)

**Comment by hsivonen** [comment]
The most suspicious commit in that range seems to be the [new cargo version](https://github.com/rust-lang/rust/commit/cd39cf748e3a5ab7cc4449ba9acfddb969c79209). Maybe the compiler didn't change but the way cargo invokes it did.

**Comment by hsivonen** [comment]
Well, in that range cargo [turned on incremental compilation by default](https://github.com/rust-lang/cargo/commit/2c408583ce4936d7ab5f07a46db8fdcc954925a1).

**Comment by hsivonen** [comment]
Link to the PR for [turning on incremental compilation](https://github.com/rust-lang/cargo/pull/6564).

**Comment by hsivonen** [comment]
Indeed, `incremental = false` under `[profile.release]` in `Cargo.toml` returns the behavior to a single `.s`.

**Comment by hsivonen** [comment]
Adding `incremental = false` under `[profile.bench]` in the `Cargo.toml` did not fix the regression relative to the `simd` crate on the Thumb2 on ARMv7 CPU case. How should I verify that `incremental = false` is taking effect in a `cargo bench` scenario?

**Comment by hsivonen** [comment]
rustc 1.34.0-nightly (da6ab95 2019-01-27) vs. rustc 1.33.0-nightly (20c2cba 2019-01-26) does not show a benchmarking difference on x86_64 (tested on a Haswell desktop i7).

**Comment by hsivonen** [comment]
Since in the `incremental = true` world `--emit asm` no longer shows the true output (i.e. ThinLTO) isn't done, I guess I should use an external disassembler to examine if post-ThinLTO inlining is still bad in the Thumb2 case. (I don't know at what stage of compliation Thumb trampolines are generated in the ThinLTO case, so I don't know if Thumb trampolines could interfere with ThinLTO inlining in a manner that's irrelevant to e.g. x86_64.)

**Comment by gnzlbg** [comment]
You need to set incremental = false for the bench profile.

**Comment by hsivonen** [comment]
> You need to set incremental = false for the bench profile.

I tried again with 

```toml
[profile.bench]
incremental = false
```

in both the `Cargo.toml` for `encoding_bench` and the `Cargo.toml` for `encoding_rs`. For the previous benchmark run, I put it in the `Cargo.toml` for `encoding_bench` only. Having it also in the `Cargo.toml` of `encoding_rs` made no difference, so most likely the perf regression in comparison to the `simd` crate has nothing to do with incremental compilation.

I intend to disassemble the bench binaries next.

**Comment by hsivonen** [comment]
It seems that incremental compilation isn't the cause of the regression. [The instructions generated for horizontal reductions are.](https://github.com/hsivonen/encoding_rs/issues/23#issuecomment-460599391)
