### ISSUE TITLE
Make destination directory different from install directory

### ISSUE THREAD

**Issue by Wetitpig** [rust-lang/rust#58038]
When I want to build a debian package, it would be better if I could first install the files to a specific directory before packaging.

However, will setting the `prefix` option in `configure.py` different from `/usr/local` lead to problems when the package is later installed in `/usr/local`? Thanks!

**Comment by Mark-Simulacrum** [comment]
I'm not sure a definitive answer can be given by anyone without trying and figuring that out.

Largely, I would expect the answer is no, but if not, it's unlikely that an issue would ever be fixed -- but PRs are in general welcome.
