### ISSUE TITLE
Improve readability of inline suggestions touching multiple other spans

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#58032]
For example:

```
error[E0252]: the name `A` is defined multiple times
  --> $DIR/import-twice.rs:6:14
   |
LL | use foo::{A, A};
   |           ---^
   |           || |
   |           || `A` reimported here
   |           |help: remove unnecessary import
   |           previous import of the type `A` here
   |
   = note: `A` must be defined only once in the type namespace of this module
```

There are three spans: `A`, `A, ` and the second `A`. Looking at this output in the terminal makes it hard to notice that the first two spans do not actually overlap (they just touch) and how far the suggestion span goes (does it cover the second `A`?). Eventually you can figure it out, but it'd be nice if in cases like this the suggestion weren't shown inline at all.

This can be done in https://github.com/rust-lang/rust/blob/8a0e5faec7f62e3cfd88d6625ce213d93b061305/src/librustc_errors/emitter.rs#L39-L65

The logic for this might become a bit involved, but a first approximation would be to identify spans that overlap/touch at least once.

**Comment by saleemjaffer** [comment]
@estebank Can I take a shot at this? I'm new to rust.

**Comment by estebank** [comment]
@saleemjaffer the actual code change won't be too hard, I believe that it is contained entirely inside src/librustc_errors/emitter.rs, but it might frustrating due to the amount of tweaking of the logic needed to get this fixed. I certainly think that you'd be able to get it fixed, but we'll need first to come up with a test case, because the one that triggered the creation of this ticket is no longer going to reproduce due to a change in how we emit that suggestion in particular.

**Comment by saleemjaffer** [comment]
> There are three spans: A, A, and the second A

I can see only 2 `A`. How are there three?

**Comment by estebank** [comment]
In the current output of the compiler we're only showing 2, but if you revert the changes in the first file of this PR https://github.com/rust-lang/rust/pull/58296/files#diff-d6c1a78a970f7c6174f36c924862b879R560 you will see the output shown in the report above, where the spans are:

```
LL | use foo::{A, A};
   |           -
   |           |---
   |           || ^
   |           || |
   |           || `A` reimported here
   |           |help: remove unnecessary import
   |           previous import of the type `A` here
```

**Comment by estebank** [comment]
We now have support for suggestions that are either always displayed as a `note` without any code or hidden and only shown to tools. These kind of suggestions are good for proactive management of this problem.
