### ISSUE TITLE
`include!` should add file dependencies like `include_str!`

### ISSUE THREAD

**Issue by wizeman** [rust-lang/rust#58069]
Let's say I use the `include!` macro and then do `cargo build`. If I then change the included file and re-run `cargo build`, cargo should rebuild. However, right now, it doesn't seem to do anything.

In other words, I'm encountering the same problem as in #24348, except with the `include!` macro instead of the `include_bytes!` macro.

**Comment by ehuss** [comment]
I can't seem to reproduce this issue (even with older releases).  Files included via `include` are registered in the dep-info output. If you're still able to reproduce this, feel free to reopen.
