### ISSUE TITLE
Beta miscompiles match when a pattern has a range including signed minimum

### ISSUE THREAD

**Issue by tspiteri** [rust-lang/rust#58067]
```rust
fn main() {
    let x = match 1i8 {
        -0x80..=-1 => -99,
        0..=10 => 0,
        _ => 99,
    };
    println!("{}", x);
}
```
This prints `-99` instead of `0`. 

Changing the first pattern to `-0x80 | -0x7f..=-1 => -99,` will work around the issue.

Changing it to `-0x80..=-0x7f | -0x7e..=-1` reintroduces the issue.

**Comment by Centril** [comment]
cc @varkor -- is this the same as the bug you fixed in https://github.com/rust-lang/rust/pull/57978?

**Comment by memoryruins** [comment]
@Centril It is. the example on nightly now prints `0`, as well as the `-0x80..=-0x7f | -0x7e..=-1` version
`rust version 1.34.0-nightly (852701ad6 2019-02-01)`

@tspiteri thank you for reporting! the fix was accepted for beta backport and will be on there soon ^^

**Comment by tspiteri** [comment]
Works in updated nightly, thanks! I didn't find the dup as I looked in open issues only, so I missed #57894 which was closed a couple of hours earlier!
