### ISSUE TITLE
Error while installing parity ubuntu 18.10

### ISSUE THREAD

**Issue by rogersebastiany** [rust-lang/rust#58063]
Hello!
I'm starting on this 
I'm reading the 'mastering ethereum' e-book and I'm having trouble to follow the book's how to install parity
I've installed: git, go, openssl libssl-dev libudev-dev cmake, and cargo (by apt)
go version: 1.11.5 linux/amd64
cargo 1.30.0
I've cloned parity from github at https://github.com/paritytech/parity
after download and change directory to parity folder i did
cargo install
error: failed to parse manifest at `/home/roger/parity/ethcore/call-contract/Cargo.toml`

Caused by:
  feature `rename-dependency` is required

consider adding `cargo-features = ["rename-dependency"]` to the manifest
Then, i tryed to add 'cargo-features = ["rename-dependency] to Cargo.toml
after that, the following error after trying to cargo install again:
cargo install
error: failed to parse manifest at `/home/roger/parity/ethcore/call-contract/Cargo.toml`

Caused by:
  invalid type: sequence, expected a version string like "0.9.8" or a detailed dependency like { version = "0.9.8" } for key `dependencies.cargo-features`

`[package]
name = "ethcore-call-contract"
version = "0.1.0"
license = "GPL-3.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
types = { path = "../types", package = "common-types" }
ethereum-types = "0.4"
bytes = { version = "0.1", package = "parity-bytes" }
cargo-features = ["rename-dependency"]`

Sorry if im being too noob I really am :)
Thx

**Comment by jonas-schievink** [comment]
You have to update your Rust toolchain. If you still have trouble, consider asking for help on https://users.rust-lang.org/, this issue tracker is meant for bugs only.

**Comment by coronelargie** [comment]
its a bug

**Comment by rogersebastiany** [comment]
i think it is realy a bug becouse my software is up do date

**Comment by coronelargie** [comment]
intall

**Comment by coronelargie** [comment]
just reverse it

**Comment by jonas-schievink** [comment]
You are running Cargo 1.30, the current release is 1.32 - if you need help with installing please ask on the forum

**Comment by rogersebastiany** [comment]
roger@roger-Z450LA:~/parity$ rustc --version
rustc 1.30.0
roger@roger-Z450LA:~/parity$ cargo --version
cargo 1.30.0
roger@roger-Z450LA:~/parity$ rustup update stable
rustup: command not found
roger@roger-Z450LA:~/parity$ cargo update
error: failed to parse manifest at `/home/roger/parity/ethcore/call-contract/Cargo.toml`

Caused by:
  feature `rename-dependency` is required

consider adding `cargo-features = ["rename-dependency"]` to the manifest

bug??

**Comment by TejasQ** [comment]
Why is this closed?
