### ISSUE TITLE
Stabilizing `Any::get_type_id` as `Any::type_id` breaks crates on stable

### ISSUE THREAD

**Issue by rustonaut** [rust-lang/rust#58126]
Some crates (like `mail`) break with the patch which stabilizes `Any::get_type_id` as `Any::type_id`.

The reason is that (many?/some?) " custom trait object" implementations have their own `SomeTrait::type_id` method leading to an ambiguity when calling `instance.type_id()`.

### Example (from `mail` crate)

```
use std::any::{Any, TypeId};

[...]

pub trait EncodableInHeader: Send + Sync + Any + Debug {
    fn encode(&self, encoder:  &mut EncodingWriter) -> Result<(), EncodingError>;

    fn boxed_clone(&self) -> Box<EncodableInHeader>;

    #[doc(hidden)]
    fn type_id( &self ) -> TypeId {
        TypeId::of::<Self>()
    }
}

[...]

impl EncodableInHeader {

    #[inline(always)]
    pub fn is<T: EncodableInHeader>(&self) -> bool {
        self.type_id() == TypeId::of::<T>()
    }
}
```
==> **new compiler error without changing code** from this commit on https://github.com/SimonSapin/rust/commit/fb5d3c1f379e42b9d31887b744982159a0dc651b.

### Proposed solution

None, but maybe do a crater run to find more fallout and inform crate maintainers

**Comment by Mark-Simulacrum** [comment]
We've made this stabilization and the fallout here is inference, which is permitted under our policy. In any case we won't be reverting this now that it's on stable so closing this issue.
