### ISSUE TITLE
Blank right side border in table generated by rustdoc in Firefox

### ISSUE THREAD

**Issue by lzutao** [rust-lang/rust#58134]
**Edit**: Add test code in metadata.

---

It is ugly in my crate (not public yet), see below image displayed in Firefox:

![image](https://user-images.githubusercontent.com/15225902/52185931-c93c9500-2856-11e9-96b8-d77ce2679619.png) 

but in Chromium:

![image](https://user-images.githubusercontent.com/15225902/52186005-5849ad00-2857-11e9-875b-7c6d3914b3ee.png)

At least in Chromium, the right side border of the table is displayed.

I tested in both 1.31.0, 1.32.0 and 1.34.0-nightly (852701ad6 2019-02-01), those have the same effect. I didn't test previous versions because I'm using Rust 2018.

## Metadata

<details>

<summary>OS and software info</summary>

OS: Xubuntu 18.04.1
Browser: Firefox 65.0 (All extensions are disabled)

### Rustdoc:

```command line
% rustdoc -Vv
rustdoc 1.32.0 (9fda7c223 2019-01-16)
binary: rustdoc
commit-hash: 9fda7c2237db910e41d6a712e9a2139b352e558b
commit-date: 2019-01-16
host: x86_64-unknown-linux-gnu
release: 1.32.0
LLVM version: 8.0
```

</details>
<details>
<summary>Build with below code to test locally with `rustdoc`</summary>

```rust
/// Tone (thanh điệu), which also called "accent", lists all possible
/// tones in Vietnamese.
///
/// These tones are:
///
/// Tone        | Example
/// ------------|--------
/// None        | a
/// Grave       | à
/// Acute       | á
/// Hook above  | ả
/// Tilde       | ã
/// Dot below   | ạ
#[derive(Debug, PartialEq)]
pub enum Tone {
    // Thanh bằng hoặc không dấu
    None = 0,
    // Thanh huyền
    Grave,
    // Thanh sắc
    Acute,
    // Thanh hỏi
    HookAbove,
    // Thanh ngã
    Tilde,
    // Thanh nặng
    DotBelow,
}
```

</details>

**Comment by memoryruins** [comment]
Do the tables render without the right side border on
https://doc.rust-lang.org/nightly/std/collections/index.html?

---

Some screenshots from my laptop / desktop:

Firefox `64.0` / Arch Linux

![unknown](https://user-images.githubusercontent.com/6868531/52195041-33881200-2824-11e9-85e7-5f7070c2e9f1.png)

Firefox `65.0` / Windows 10

![screenshot 4550](https://user-images.githubusercontent.com/6868531/52194845-83b2a480-2823-11e9-922a-a6a8a1dfee32.png)

Firefox Nightly `67.0a1 (2019-02-03)` / Windows 10

![screenshot 4551](https://user-images.githubusercontent.com/6868531/52194859-8f05d000-2823-11e9-94ea-ab3b2521accc.png)

---

Although I wasn't able to recreate the blank side, only Firefox Nightly rendered the table to expectations (there are slight offsets in previous versions).

**Comment by lzutao** [comment]
No, it has the right side border (with a slight offset):

![image](https://user-images.githubusercontent.com/15225902/52198010-112ddd00-2894-11e9-8378-fee6c3fbc25f.png)

---

You could try to build this document source with `rustdoc` :
```rust
/// Tone (thanh điệu), which also called "accent", lists all possible
/// tones in Vietnamese.
///
/// These tones are:
///
/// Tone        | Example
/// ------------|--------
/// None        | a
/// Grave       | à
/// Acute       | á
/// Hook above  | ả
/// Tilde       | ã
/// Dot below   | ạ
```

**Comment by memoryruins** [comment]
Unable to test it locally currently, but one difference is that the tables on collections’ page has borders in the markdown as well. Does it make any difference by adding them? It doesn’t make a difference on github markdown, but worth a shot.

```rust
//! ## Sequences
//!
//! |                | get(i)         | insert(i)       | remove(i)      | append | split_off(i)   |
//! |----------------|----------------|-----------------|----------------|--------|----------------|
//! | [`Vec`]        | O(1)           | O(n-i)*         | O(n-i)         | O(m)*  | O(n-i)         |
//! | [`VecDeque`]   | O(1)           | O(min(i, n-i))* | O(min(i, n-i)) | O(m)*  | O(min(i, n-i)) |
//! | [`LinkedList`] | O(min(i, n-i)) | O(min(i, n-i))  | O(min(i, n-i)) | O(1)   | O(min(i, n-i)) |
```

**Comment by lzutao** [comment]
@memoryruins I added left and right borders, and even when using module document
syntax `//!`, nothing is different.

**Comment by GuillaumeGomez** [comment]
@lzutao Please make your code available somewhere so I can test it because I can't reproduce it...

**Comment by lzutao** [comment]
@GuillaumeGomez I updated the issue details.

**Comment by memoryruins** [comment]
I was able to recreate something similar with your example:

Toggle the light/dark theme off and on a bit.
![image](https://user-images.githubusercontent.com/6868531/52227814-9908ec80-287e-11e9-9008-a85fcca9a67e.png)

The right border will retain the black border on light theme and vice versa:
![image](https://user-images.githubusercontent.com/6868531/52227481-a70a3d80-287d-11e9-80ec-5fcb936c3593.png)
![image](https://user-images.githubusercontent.com/6868531/52227495-affb0f00-287d-11e9-86c9-1f3637c6a96b.png)

Recreated on the collections page (only on the sequences box in this screenshot).
![image](https://user-images.githubusercontent.com/6868531/52227542-d28d2800-287d-11e9-8843-083e3e89da61.png)

If I  resize the page after the border glitches, the border re-appears (most likely due to media queries).
![image](https://user-images.githubusercontent.com/6868531/52227510-b6898680-287d-11e9-816a-8003225825fe.png)

**Comment by lzutao** [comment]
> Did you switch themes before opening the issue? 

I switched themes, but nothing changes.

> Does resizing make any difference?

Yes! Resizing to < 100% or to 110%, it will display the border
<details><summary>Click to display the image</summary>

![image](https://user-images.githubusercontent.com/15225902/52228722-adcc9b00-28e5-11e9-9237-1de27e86ca79.png)

</details>

but to 120%, the border disappeared.

**Comment by lzutao** [comment]
Missing a cell?
![image](https://user-images.githubusercontent.com/15225902/52533085-370a2480-2d61-11e9-9ea2-3fb35f36cf5e.png)

**Comment by GuillaumeGomez** [comment]
Interesting! I was about to look into it. I'll do the two at once.
