### ISSUE TITLE
s390x-unknown-linux-gnu hangs in QEMU

### ISSUE THREAD

**Issue by asomers** [rust-lang/rust#58149]
https://github.com/rust-lang/libc/pull/1235 added an integration test with the test harness enabled.  It's libc's first integration test that uses the test harness, and it's hanging on s390x even though there are _no_ tests enabled for that architecture.  @gnzlbg thinks that the bug might lie in rustc, not QEMU.

**Comment by nagisa** [comment]
I *think* it is a QEMU issue. At least I *think* there is a build of s390x rustc done on real hardware for I *think* debian.

**Comment by gnzlbg** [comment]
@asomers same here as with the  #58148 issue. It might be worth it to try to find if there is a qemu bug open upstream, and if not, fill one.

**Comment by asomers** [comment]
After more investigation, this looks like a QEMU issue.  At least, QEMU doesn't spit out enough information to prove otherwise.  The qemu process core dumps before it prints anything Rust-related.

**Comment by greg5678** [comment]
If you want to try Rust on an x390x system you can request access [here](https://linuxone.cloud.marist.edu/cloud/#/register?flag=vm).

**Comment by gnzlbg** [comment]
The problem is more all the work required to set up that in CI, than getting access itself.
