### ISSUE TITLE
Allow sorting modules by import order in documentation

### ISSUE THREAD

**Issue by Ppjet6** [rust-lang/rust#58144]
It would be nice to be able to sort modules by the order they are declared, in the generated documentation. At the moment it seemed to unconditionally be sorted alphabetically.

See for example this [XMPP parsing library](https://docs.rs/xmpp-parsers/0.12.2/xmpp_parsers/), I'd like to have it sorted by XEP numbers, as declared in the [`lib.rs` file](https://gitlab.com/xmpp-rs/xmpp-parsers/blob/d811c10ed350453826dc6167b4d38245c0795625/src/lib.rs#L33).

**Comment by GuillaumeGomez** [comment]
Ok.

**Comment by GuillaumeGomez** [comment]
There is actually already an option for that: `sort-modules-by-appearance`. Closing then!
