### ISSUE TITLE
sparc64-unknown-linux-gnu crashes in QEMU

### ISSUE THREAD

**Issue by asomers** [rust-lang/rust#58148]
https://github.com/rust-lang/libc/pull/1235 added an integration test with the test harness enabled.  It's libc's first integration test that uses the test harness, and it's failing on sparc with a SIGILL even though there are _no_ tests enabled for that architecture.  @gnzlbg thinks that the bug might lie in rustc, not QEMU.

**Comment by nagisa** [comment]
This is a QEMU issue. rustc works fine on real hardware.

Tested by your’s truly.

**Comment by gnzlbg** [comment]
@nagisa thank you ! 

do you happen to know if there is a bug open in qemu upstream ? @asomers we might want to track that, and re-enable the tests once we upgrade the Docker containers to a newer version of qemu with the fix.

**Comment by nagisa** [comment]
Don't know any bugs upstream, now I have looked for any, nor I have investigated what exactly makes it not work.
