### ISSUE TITLE
 how to convert to rust?

### ISSUE THREAD

**Issue by calidion** [rust-lang/rust#58177]
c code:
```
typedef int32_t fe[10];

```

**Comment by nagisa** [comment]
This is a tracker for the issues in rustc. For support, consider posting your question on [users.rlo](https://users.rust-lang.org/), [stackoverflow](https://stackoverflow.com/), [reddit](https://www.reddit.com/r/rust/), or asking on one of the chat platforms: [#rust on irc.mozilla.org](https://www.rust-lang.org/en-US/community.html#irc-channels), [discord](https://discordapp.com/invite/aVESxV8) or [zulip](https://rust-lang.zulipchat.com/#).

**Comment by nagisa** [comment]
To answer your question, that type is equivalent to `[c_int; 10]` in rust.

**Comment by Stargateur** [comment]
For the record: https://stackoverflow.com/q/54527297/7076153
