### ISSUE TITLE
Adding comment to function causes "overflow evaluating the requirement"

### ISSUE THREAD

**Issue by kjeremy** [rust-lang/rust#58188]
> $ rustc --version
> rustc 1.32.0 (9fda7c223 2019-01-16)
> 
> $ rustup toolchain list
> stable-x86_64-pc-windows-msvc (default)

Discovered when running `cargo check` on `rust-analyzer`. The command succeeds but adding a comment before (as in `// this is a comment` before https://github.com/rust-analyzer/rust-analyzer/blob/88702a758f031f33452e9acac621841552ec9f8a/crates/ra_lsp_server/src/main_loop/handlers.rs#L695

causes 

> $ cargo check
    Checking ra_lsp_server v0.1.0 (C:\projects\test\rust-analyzer\crates\ra_lsp_server)
error[E0275]: overflow evaluating the requirement `*const ra_hir::path::GenericArg: std::panic::RefUnwindSafe`
   --> crates\ra_lsp_server\src\main_loop.rs:491:10
    |
491 |     pool.execute(move || {
    |          ^^^^^^^
    |
    = help: consider adding a `#![recursion_limit="128"]` attribute to your crate
    = note: required because it appears within the type `core::nonzero::NonZero<*const ra_hir::path::GenericArg>`
    = note: required because it appears within the type `std::ptr::Unique<ra_hir::path::GenericArg>`
    = note: required because it appears within the type `alloc::raw_vec::RawVec<ra_hir::path::GenericArg>`
    = note: required because it appears within the type `std::vec::Vec<ra_hir::path::GenericArg>`
    = note: required because it appears within the type `ra_hir::path::GenericArgs`
    = note: required because it appears within the type `alloc::sync::ArcInner<ra_hir::path::GenericArgs>`
    = note: required because it appears within the type `*const alloc::sync::ArcInner<ra_hir::path::GenericArgs>`
    = note: required because it appears within the type `core::nonzero::NonZero<*const alloc::sync::ArcInner<ra_hir::path::GenericArgs>>`
    = note: required because it appears within the type `std::ptr::NonNull<alloc::sync::ArcInner<ra_hir::path::GenericArgs>>`
    = note: required because it appears within the type `std::sync::Arc<ra_hir::path::GenericArgs>`
    = note: required because it appears within the type `std::option::Option<std::sync::Arc<ra_hir::path::GenericArgs>>`
    = note: required because it appears within the type `ra_hir::path::PathSegment`
    = note: required because it appears within the type `*const ra_hir::path::PathSegment`
    = note: required because it appears within the type `core::nonzero::NonZero<*const ra_hir::path::PathSegment>`
    = note: required because it appears within the type `std::ptr::Unique<ra_hir::path::PathSegment>`
    = note: required because it appears within the type `alloc::raw_vec::RawVec<ra_hir::path::PathSegment>`
    = note: required because it appears within the type `std::vec::Vec<ra_hir::path::PathSegment>`
    = note: required because it appears within the type `ra_hir::path::Path`
    = note: required because it appears within the type `ra_hir::expr::Expr`
    = note: required because it appears within the type `*const ra_hir::expr::Expr`
    = note: required because it appears within the type `core::nonzero::NonZero<*const ra_hir::expr::Expr>`
    = note: required because it appears within the type `std::ptr::Unique<ra_hir::expr::Expr>`
    = note: required because it appears within the type `alloc::raw_vec::RawVec<ra_hir::expr::Expr>`
    = note: required because it appears within the type `std::vec::Vec<ra_hir::expr::Expr>`
    = note: required because it appears within the type `ra_arena::Arena<ra_hir::expr::ExprId, ra_hir::expr::Expr>`
    = note: required because it appears within the type `ra_hir::expr::Body`
    = note: required because it appears within the type `alloc::sync::ArcInner<ra_hir::expr::Body>`
    = note: required because it appears within the type `*const alloc::sync::ArcInner<ra_hir::expr::Body>`
    = note: required because it appears within the type `core::nonzero::NonZero<*const alloc::sync::ArcInner<ra_hir::expr::Body>>`
    = note: required because it appears within the type `std::ptr::NonNull<alloc::sync::ArcInner<ra_hir::expr::Body>>`
    = note: required because it appears within the type `std::sync::Arc<ra_hir::expr::Body>`
    = note: required because it appears within the type `ra_hir::expr::scope::ExprScopes`
    = note: required because it appears within the type `alloc::sync::ArcInner<ra_hir::expr::scope::ExprScopes>`
    = note: required because it appears within the type `*const alloc::sync::ArcInner<ra_hir::expr::scope::ExprScopes>`
    = note: required because it appears within the type `core::nonzero::NonZero<*const alloc::sync::ArcInner<ra_hir::expr::scope::ExprScopes>>`
    = note: required because it appears within the type `std::ptr::NonNull<alloc::sync::ArcInner<ra_hir::expr::scope::ExprScopes>>`
    = note: required because it appears within the type `std::sync::Arc<ra_hir::expr::scope::ExprScopes>`
    = note: required because of the requirements on the impl of `std::panic::RefUnwindSafe` for `salsa::derived::DerivedStorage<ra_ide_api::db::RootDatabase, ra_hir::db::ExprScopesQuery, salsa::derived::AlwaysMemoizeValue>`
    = note: required because it appears within the type `ra_hir::db::HirDatabaseGroupStorage__<ra_ide_api::db::RootDatabase>`
    = note: required because it appears within the type `ra_ide_api::db::__SalsaDatabaseStorage`
    = note: required because of the requirements on the impl of `std::panic::RefUnwindSafe` for `salsa::runtime::SharedState<ra_ide_api::db::RootDatabase>`
    = note: required because it appears within the type `alloc::sync::ArcInner<salsa::runtime::SharedState<ra_ide_api::db::RootDatabase>>`
    = note: required because it appears within the type `*const alloc::sync::ArcInner<salsa::runtime::SharedState<ra_ide_api::db::RootDatabase>>`
    = note: required because it appears within the type `core::nonzero::NonZero<*const alloc::sync::ArcInner<salsa::runtime::SharedState<ra_ide_api::db::RootDatabase>>>`
    = note: required because it appears within the type `std::ptr::NonNull<alloc::sync::ArcInner<salsa::runtime::SharedState<ra_ide_api::db::RootDatabase>>>`
    = note: required because it appears within the type `std::sync::Arc<salsa::runtime::SharedState<ra_ide_api::db::RootDatabase>>`
    = note: required because it appears within the type `salsa::runtime::RevisionGuard<ra_ide_api::db::RootDatabase>`
    = note: required because it appears within the type `std::option::Option<salsa::runtime::RevisionGuard<ra_ide_api::db::RootDatabase>>`
    = note: required because it appears within the type `salsa::runtime::Runtime<ra_ide_api::db::RootDatabase>`
    = note: required because it appears within the type `ra_ide_api::db::RootDatabase`
    = note: required because of the requirements on the impl of `ra_db::CheckCanceled` for `ra_ide_api::db::RootDatabase`
    = note: required because of the requirements on the impl of `ra_db::SourceDatabase` for `ra_ide_api::db::RootDatabase`
    = note: required because of the requirements on the impl of `salsa::plumbing::QueryGroup<ra_ide_api::db::RootDatabase>` for `ra_db::SourceDatabaseStorage`
    = note: required because it appears within the type `ra_ide_api::db::__SalsaDatabaseStorage`
    = note: required because it appears within the type `salsa::runtime::SharedState<ra_ide_api::db::RootDatabase>`
    = note: required because of the requirements on the impl of `std::marker::Send` for `std::sync::Arc<salsa::runtime::SharedState<ra_ide_api::db::RootDatabase>>`
    = note: required because it appears within the type `salsa::runtime::RevisionGuard<ra_ide_api::db::RootDatabase>`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0275`.
error: Could not compile `ra_lsp_server`.

**Comment by jonas-schievink** [comment]
Can reproduce. Starts working again after running `cargo clean`, so marking as incr. comp. bug

**Comment by jonas-schievink** [comment]
Ah, looks like this is already fixed on nightly though. Can someone confirm?

**Comment by kjeremy** [comment]
Still happening on 1.33.0

**Comment by jonas-schievink** [comment]
@kjeremy can you try on nightly/beta please?

**Comment by kjeremy** [comment]
This particular error doesn't seem to happen on nightly anymore.

**Comment by Dylan-DPC** [comment]
@kjeremy can you confirm if this still occurs on the latest stable & nightly? or is this fixed already? [sorry for the 4 year later ping :P ]

**Comment by apiraino** [comment]
Closing as this incr-comp issue is old and we never managed to obtain an MCVE or a way to reproduce. the issue is supposedly fixed
