### ISSUE TITLE
Explicit underflow allowed in match 

### ISSUE THREAD

**Issue by spcan** [rust-lang/rust#58194]
In the code below, when matching an `usize`, the compiler allows for explicit underflow of said `usize` with no compiler error. As you can see this underflow is very explicit and the compiler should be able to notice this. Explicit overflows are also allowed by the compiler.

What is the "supposed" behaviour (or undefined behaviour) for this underflow and what kind of runtime error should I expect if `n as usize = 0`?

I'm just curious of what happens in this case as I'm not an expert on Rust. If there's some documentation of this "feature", and already open issue or a RFC on this, please link to it, as I haven't found anything on it.
```
fn my_function(n: MyEnum) {
    let (n1, n2) = match n as usize{
        0..8 => (3, (n-1)*4),
        _     => (4, (n-8)*4),
    }
}
```

**Comment by jonas-schievink** [comment]
Please direct questions to the user forum at https://users.rust-lang.org/ or another place (eg. the Discord or IRC). This issue tracker is meant for bugs only.
