### ISSUE TITLE
Spurious SIGILL (signal 4) when linking with `cc` on macOS during doctest

### ISSUE THREAD

**Issue by kennytm** [rust-lang/rust#58209]
Symptom: The Linker crashes with signal 4, e.g.

```
error: linking with `cc` failed: signal: 4
```

Previous instances:

| Date | URL | Failing test |
|----|----|----|
| 2018-08-31T21:30:20Z | https://github.com/rust-lang/rust/pull/53533#issuecomment-417794193 | alloc.rs - alloc::alloc (line 62) |
| 2018-09-29T19:38:06Z | https://github.com/rust-lang/rust/pull/54601#issuecomment-425670539 | hex.rs - hex::[u8]::to_hex (line 32) |
| 2018-10-17T16:28:07Z | https://github.com/rust-lang/rust/pull/55134#issuecomment-430697029 | ../stdsimd/coresimd/macros.rs - coresimd::x86::__m128 (line 27) |
| 2018-10-17T23:16:07Z | https://github.com/rust-lang/rust/pull/54349#issuecomment-430821686 | src/test/rustdoc/test_option_check/bar.rs - bar::foooo (line 16) |
| 2018-11-23T08:50:08Z | https://github.com/rust-lang/rust/pull/55767#issuecomment-441182604 | alloc.rs - alloc::System (line 106) |
| 2018-11-30T11:50:06Z | https://github.com/rust-lang/rust/pull/56214#issuecomment-443180787 | /Users/travis/build/rust-lang/rust/src/doc/unstable-book/src/language-features/generators.md - generators::_::Generators_as_state_machines (line 166) |
| 2018-12-02T05:06:07Z | https://github.com/rust-lang/rust/pull/55010#issuecomment-443482109 | src/test/rustdoc/test_option_check/bar.rs - bar::foooo (line 16) |
| 2018-12-09T16:14:08Z | https://github.com/rust-lang/rust/pull/56463#issuecomment-445550130 | ../stdsimd/coresimd/macros.rs - coresimd::x86::__m128 (line 292) |
| 2018-12-11T03:22:07Z | https://github.com/rust-lang/rust/pull/56092#issuecomment-446058541 | alloc.rs - alloc::alloc (line 66) |
| 2019-01-20T08:26:07Z | https://github.com/rust-lang/rust/pull/57647#issuecomment-455846844 | src/test/rustdoc/test_option_check/bar.rs - bar::foooo (line 6) |

**Comment by wesleywiser** [comment]
Closing since this hasn't happened in a long time.

**Comment by jieyouxu** [comment]
Triage: closing as per comment above (forgot to actually close :3)
