### ISSUE TITLE
Tracking issue for str::as_mut_ptr

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#58215]
This is a tracking issue for `str::as_mut_ptr`:
```rust
impl str {
    /// Converts a mutable string slice to a raw pointer.
    ///
    /// As string slices are a slice of bytes, the raw pointer points to a
    /// [`u8`]. This pointer will be pointing to the first byte of the string
    /// slice.
    ///
    /// It is your responsibility to make sure that the string slice only gets
    /// modified in a way that it remains valid UTF-8.
    ///
    /// [`u8`]: primitive.u8.html
    pub fn as_mut_ptr(&mut self) -> *mut u8;
}
```

Implemented in https://github.com/rust-lang/rust/pull/58200

**Comment by SimonSapin** [comment]
Given that the implementation is trivial I don’t think letting it "bake" in Nightly is any use. And since `[T]` already has this method and `str` already has the `*const` version of this, I don’t expect this to be controversial at all. Still, let’s go through the usual dance:

@rfcbot fcp merge
