### ISSUE TITLE
Tracking issue for PathBuf capacity methods

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#58234]
- `capacity`
 - `with_capacity`
 - `clear`
 - `reserve`
 - `reserve_exact`
 - `shrink_to_fit`
 - `shrink_to`, should probably not be stabilized before [`OsString::shrink_to`](https://doc.rust-lang.org/nightly/std/ffi/struct.OsString.html#method.shrink_to), see https://github.com/rust-lang/rust/issues/56431

**Comment by aaronstillwell** [comment]
Happy to take this as a first contribution to rust.

**Comment by Mark-Simulacrum** [comment]
Great! I'd be happy to help you get started, just let me know if you want mentoring/instructions at any level!

**Comment by aaronstillwell** [comment]
@Mark-Simulacrum are you able to define a list of the methods that need to be implemented as part of this PR?

**Comment by Mark-Simulacrum** [comment]
I think all of these will essentially call the underlying functions on `OsString`.

 - [ ] `capacity`
 - [ ] `with_capacity`
 - [ ] `clear`
 - [ ] `reserve`
 - [ ] `reserve_exact`
 - [ ] `shrink_to_fit`
 - [ ] `shrink_to` -- this one is more of a maybe, since it's unstable on OsString. We can reuse the same tracking issue for this.

We'll probably want to add all of these under the same feature gate.

**Comment by aaronstillwell** [comment]
@Mark-Simulacrum thanks for that. I have the implementation drafted locally. I'm having some difficulty however in running the tests for stdlib - even a `cargo check` is producing errors not related to my changes. Is there any documentation I've missed for best practices on compiling / working on stdlib?

**Comment by Mark-Simulacrum** [comment]
You'll want to use x.py; for your scenario I believe `x.py test --stage 0 src/libstd` and/or `x.py check src/libstd` are the commands you want. I'm not sure where the most current documentation is.

**Comment by ordovicia** [comment]
[This page on rustc guide](https://rust-lang.github.io/rustc-guide/how-to-build-and-run.html) describes how to use `x.py`.

**Comment by bheesham** [comment]
Triage: since #58539 has been merged, can this be closed?

**Comment by Mark-Simulacrum** [comment]
No, this is now the tracking issue for the stabilization of those APIs.

**Comment by Mark-Simulacrum** [comment]
Reviewing this since then, I think it may be worth removing these APIs and replacing them with something like `AsRef<OsString> for PathBuf` and `AsMut`. These aren't really commonly used so hiding them as such seems reasonable and is less heavy.

**Comment by kornelski** [comment]
I'd love to see these stabilized. I have a tool that manipulates lots of paths, so I'd like to avoid needless reallocations.

* I generate lots of temporary paths in a loop. `PathBuf.clear() + PathBuf.push()` would work nicely to reuse the buffer.

* I need to concatenate several components. I know their length, so I could use `PathBuf::with_capacity()`

* I want to store lots of paths for later. `Box<Path>` is a bit smaller than `PathBuf`, but if I can't reserve exact capacity, `into()` will reallocate.

**Comment by Amanieu** [comment]
@rfcbot merge

**Comment by dtolnay** [comment]
@rfcbot reviewed
assuming we're only stabilizing capacity + with_capacity + clear + reserve + reserve_exact + shrink_to_fit;&ensp;and shrink_to is being moved to https://github.com/rust-lang/rust/issues/56431 instead.

**Comment by Mark-Simulacrum** [comment]
I've posted a stabilization PR in #71328.
