### ISSUE TITLE
Add some crates sources to "rust-src" distribution.

### ISSUE THREAD

**Issue by taeguk** [rust-lang/rust#58268]
In `IntelliJ-Rust` and `rls-vscode`, `rust-src` component is used to acquire standard crates sources.
But, in currently, `librustc`, `librustc_plugin`, and `libsyntax` are emitted in the list below.
https://github.com/rust-lang/rust/blob/ad433894abd4231fb2102416a520ae995ee09aed/src/bootstrap/dist.rs#L889
So, syntax highlighting and code completion are not working when using those crates in `IntelliJ-Rust` or `rls-vscode`.

There was similar issue #55279 about `libproc_macro` and it was fixed in #55280.
How about adding those crates (`librustc`, `librustc_plugin`, and `libsyntax`) to the list above, too?

Related issue: https://github.com/intellij-rust/intellij-rust/issues/2623

**Comment by ishitatsuyuki** [comment]
Related: https://github.com/rust-lang/rust/issues/42667

**Comment by eddyb** [comment]
Is this still a concern? I don't think the current set of crates (`librustc` and `librustc_ast`) are enough to cover plugin dependencies anymore but I don't think we've heard back from anyone about it.

IMO the solution used here (to add compiler crates to `rust-src`) is not ideal, and we should probably have any compiler sources available through a different `rustup` component, *if* we actually need them.

cc @Mark-Simulacrum

**Comment by RalfJung** [comment]
Also see https://github.com/rust-lang/rust/pull/69631
