### ISSUE TITLE
Box<Any>::type_id() != &Any.type_id()

### ISSUE THREAD

**Issue by purpleposeidon** [rust-lang/rust#58286]
```rust
fn main() {
    use std::any::*;
    assert_eq!(
        (Box::new(true) as Box<Any>).type_id(),
        (&true as &Any).type_id(),
    );
}
```

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=a1b9c1941d80992eba16bf1452273e9c

**Comment by crlf0710** [comment]
This is expected behavior, since `Box<dyn Any>` does implement `Any` and gives a different `type_id` than what `bool` gives.

**Comment by crlf0710** [comment]
try `(Box::new(true) as Box<Any>).as_ref().type_id()` to accomplish what you want.
