### ISSUE TITLE
core::ffi::VaList does not pass improper_ctypes lint

### ISSUE THREAD

**Issue by dlrobertson** [rust-lang/rust#58280]
## Summary

On x86_64, Aarch64, and PowerPC `core::ffi::VaList` will not pass the `improper_ctypes` lint, but it should.

## Example

Given the following:

```rust
#![no_std]
#![feature(c_variadic)]
#![deny(improper_ctypes)]
use core::ffi::VaList;

extern "C" {
    pub fn some_fn(_: i32, _: VaList);
}
```

The compiler will yield:

```
error: `extern` block uses type `()` which is not FFI-safe: tuples have unspecified layout
 --> test.rs:7:31
  |
7 |     pub fn some_fn(_: i32, _: VaList);
  |                               ^^^^^^
  |
note: lint level defined here
 --> test.rs:3:9
  |
3 | #![deny(improper_ctypes)]
  |         ^^^^^^^^^^^^^^^
  = help: consider using a struct instead

error: aborting due to previous error
```

## Description

The implementation of `VaListImpl` for the x86_64, Aarch64, and PowerPC architectures uses `*mut ()` or `*const ()` as the pointer type for the pointers to the architecture specific save areas (e.g., [the x86_64 implementation](https://github.com/rust-lang/rust/blob/76cdccb2c2b90539fe37f4a264a80c94d395cc78/src/libcore/ffi.rs#L116-L117)).

**Comment by dlrobertson** [comment]
`core::ffi` defines `c_void`. Perhaps `c_void` should be used instead of `()`

**Comment by nagisa** [comment]
It would be fine to just special-case the `va_list` language item in the lint implementation.

**Comment by dlrobertson** [comment]
> It would be fine to just special-case the `va_list` language item in the lint implementation.

This seems reasonable to me too. The `VaList` structure should (for obvious reasons) always be FFI safe.
