### ISSUE TITLE
Const generic parameters have incorrect hygiene

### ISSUE THREAD

**Issue by varkor** [rust-lang/rust#58307]
Const generic parameters are treated as hygienic by `macro_rule` because it uses "`let` variable hygiene" rather than "item hygiene".

See https://github.com/rust-lang/rust/issues/57523#issuecomment-453788106 and https://github.com/rust-lang/rust/pull/58191#discussion_r254251259.

cc @petrochenkov

**Comment by jonas-schievink** [comment]
cc https://github.com/rust-lang/rust/issues/44580

**Comment by varkor** [comment]
https://github.com/rust-lang/rust/issues/44580#issuecomment-472825354 looks like it could be related to this issue.
