### ISSUE TITLE
No indication of license for content on the Rust wiki

### ISSUE THREAD

**Issue by asb** [rust-lang/rust#5831]
I had a look, but couldn't see any indication for the intended license of content on the Rust wiki. This isn't necessarily a major issue, but it's not inconceivable people could contribute content that would be useful to pull in to official Rust documentation.

**Comment by brson** [comment]
It seems unlikely that I'm ever going to get around to fixing this. It's just not that important. The most important thing remaining is policy documentation and that rightly belongs somewhere not world-editable.

**Comment by steveklabnik** [comment]
Does this mean we can just remove the wiki then?

**Comment by steveklabnik** [comment]
I have backed up the wiki to https://github.com/rust-lang/rust-wiki-backup , so we have a copy, and am disabling it in the main repository. If there's more important content that needs replacing, please open issues. Thanks.

**Comment by alexchandel** [comment]
This is rather depressing. I used to regularly curate the "Community libraries" wiki page.

**Comment by lahwran** [comment]
When is the wiki coming back?
