### ISSUE TITLE
Fix rustdoc-js unit-test for substring after removal of unstable API

### ISSUE THREAD

**Issue by Matthias247** [rust-lang/rust#58331]
As discovered in #57992, the test in https://github.com/rust-lang/rust/blob/master/src/test/rustdoc-js/substring.js referenced an API unstable, which lead to a breaking test when the API was removed.

Per discussion with @GuillaumeGomez I am removing the test inside #57992 in order to unblock that change. The test should be fixed afterwards. Ideally without referencing unstable APIs.

**Comment by GuillaumeGomez** [comment]
The simplest way to fix this issue is to make the substring search outside of the std libs. It'll be easier when https://github.com/rust-lang/rust/pull/58330 will get merged.
