### ISSUE TITLE
Updating LLVM version

### ISSUE THREAD

**Issue by Disasm** [rust-lang/rust#58335]
I'd like to add tier2 platforms for RV64IMAC and RV64GC targets. However, [simple target implementation](https://github.com/rust-lang/rust/pull/58012) cannot be built against current rustc/8.0-2019-01-16 LLVM version. We need to get some LLVM patches for RV64 from upstream (which are already there). At the moment I have no idea how to achieve this. Hypothetical choices are:
* Cherry-pick only the necessary patches into Rust LLVM tree
* Determine some point in upstream LLVM which contains all needed patches and merge it into Rust LLVM tree
* Rebase Rust LLVM tree to the point mentioned above

I will experiment with different choices, but I need to know which approach is actually used and what should I do next.

**Comment by davidlt** [comment]
Maybe Alex @asb could provide a good suggestion. He also provided an update on RISC-V support in LLVM at FOSDEM 2019: https://fosdem.org/2019/schedule/event/riscvllvmclang/

**Comment by nikic** [comment]
This depends on how many patches we're talking. If it's just two or three, they can be cherry-picked (you can submit a PR at https://github.com/rust-lang/llvm-project). If a lot of changes are necessary, then the Rust LLVM fork will have to be rebased.

**Comment by Disasm** [comment]
@nikic At the moment I can build RV64 support with 16 patches, but I can try to reduce this patch set. Theoretical minimum is 4 patches, but I haven't tried this yet.

**Comment by michaelwoerister** [comment]
Can we update to LLVM 8 proper? The rc2 for that is already out.

**Comment by nikic** [comment]
We are already on LLVM 8. These changes are part of LLVM 9.

**Comment by michaelwoerister** [comment]
Ah, OK. I hope we stay on LLVM 8 until the next beta branches off.
