### ISSUE TITLE
Various documentation for SIMD stuff is out of date

### ISSUE THREAD

**Issue by Lokathor** [rust-lang/rust#58360]
* [x] https://doc.rust-lang.org/core/arch/aarch64/index.html points you to a `stdsimd` feature and issue https://github.com/rust-lang/rust/issues/27731, but that issue says it's tracking `coresimd`, perhaps the docs there need to change. Except that at [the bottom of the issue](https://github.com/rust-lang/rust/issues/27731#issuecomment-429249091) it's apparently the case that the issue itself has run its course and we need a new tracker that's got the modern state of things figured out.
* [x] https://doc.rust-lang.org/core/arch/index.html the arch links are broken (but the module links work). Those URLs just need to get updated
* [x] https://doc.rust-lang.org/core/arch/x86_64/struct.__m64.html also points to what it calls `stdsimd` but has a different tracking number (https://github.com/rust-lang/rust/issues/48556) and the issue it points to is now closed, so that needs to be updated to point to a live issue that actually includes it.

**Comment by Lokathor** [comment]
It seems that things that use the `__m64` type also wrongly point to the same #48556 issue, such as https://doc.rust-lang.org/core/arch/x86_64/fn._mm_avg_pu16.html

**Comment by workingjubilee** [comment]
The arch links were fixed.
We no longer support `__m64` directly, so in a sense we no longer have that concern.

The only issue remaining here is needing to detangle the `stdsimd` issue / feature and redirect appropriately.
