### ISSUE TITLE
Adding a `Drop` impl to a type is a breaking change

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#58379]
uncommenting the drop impl in the following program causes it to not compile

```rust
struct Foo;

/*
impl Drop for Foo {
    fn drop(&mut self) { }
}
*/

const fn new(_: Foo) { }
```

if the definition of `Foo` were in another crate, adding that `Drop` impl would break compilation of the crate with the `const fn`.

cc @Centril 

I don't think adding a drop impl was a breaking change before `const fn`. But maybe I just can't come up with an example.

**Comment by petrochenkov** [comment]
>`let _a = x.0;`

This case is fixable (there was an RFC allowing this in 2017-2018, but I can't find it), but things are currently moving in the opposite direction with that RFC being closed and https://github.com/rust-lang/rfcs/pull/2514 + https://github.com/rust-lang/rust/pull/56440 being accepted.

**Comment by oli-obk** [comment]
> Not exactly sure what is wanted from the lang team here

Well, this is a regression in the language, so I assumed the lang team would be the relevant team to figure this out.

Since there is an example that shows that adding `Drop` impls to types is a breaking change even ignoring `const fn`, there's nothing to act on here I think.
