### ISSUE TITLE
rustc --target=$TARGET --foo should print the target's cfgs (target_arch, pointer width, etc.)

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/rust#58398]
It would be great to have a way of dumping the target's cfgs (target_arch, target_os, target_pointer_width, etc. ) programmatically from the CLI by using something like `rustc --target=$TARGET --print-target-cfgs`. 

If these are printed in a format that's easily readable by, e.g., POSIX sh scripts (e.g. one `cfg=value` per line), then we could more easily improve the rust forge to contain more information about Rust targets.

**Comment by nagisa** [comment]
```
$ rustc --target=riscv32imac-unknown-none-elf --print=cfg
debug_assertions
target_arch="riscv32"
target_endian="little"
target_env=""
target_has_atomic="16"
target_has_atomic="32"
target_has_atomic="8"
target_has_atomic="ptr"
target_os="none"
target_pointer_width="32"
target_vendor="unknown"
```
?

**Comment by gnzlbg** [comment]
Ah cool, didn't know that `--print` could do this!
