### ISSUE TITLE
mingw-check job is building the compiler, not just checking

### ISSUE THREAD

**Issue by scottmcm** [rust-lang/rust#58410]
Example: https://travis-ci.com/rust-lang/rust/jobs/177017513
```
1298:   Checking compiler artifacts (x86_64-unknown-linux-gnu -> i686-pc-windows-gnu)
1502:   Building stage0 compiler artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
```

This is costing an extra ~18 minutes of travis time per PR build (maybe more).

cc @kennytm who I talked with on Discord about this

**Comment by phansch** [comment]
I added this in https://github.com/rust-lang/rust/pull/57010. Is there some way to avoid building the full compiler for these tests or would it make sense to move this to another job?

**Comment by mati865** [comment]
@scottmcm I believe it's fixed, here is latest `mingw-check` job: https://travis-ci.com/rust-lang/rust/jobs/194269571

**Comment by scottmcm** [comment]
Agreed.  Thanks, @mati865!
