### ISSUE TITLE
Empty closure doesn't implement Fn when passed directly as FnMut argument

### ISSUE THREAD

**Issue by timvermeulen** [rust-lang/rust#58424]
```rust
fn takes_fn(_: impl Fn()) {}
fn takes_fn_mut<F: FnMut()>(f: F) -> F { f }

// compiles:
let x = || {};
takes_fn(takes_fn_mut(x));

// doesn't compile:
takes_fn(takes_fn_mut(|| {}));
```
([Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=f1bf0bc5e4149d61d2a6dff4c9ed4a19))

I expected both versions to compile.

**Comment by Centril** [comment]
cc @nikomatsakis -- this seems like a bug to me and feels similar to how `let f = |x: &u8| x;` is treated differently when passed directly or not tho the cause might not be the same.

**Comment by timvermeulen** [comment]
Never mind, duplicate of #26085
