### ISSUE TITLE
Comma required after stuct field followed by conditional compilation

### ISSUE THREAD

**Issue by Sogomn** [rust-lang/rust#58427]
Currently I have this code
```rust
struct Thing {
    //...

    #[cfg(not(feature = "web"))]
    value_function: Box<Fn(Vec<f64>) -> f64 + Sync>
    #[cfg(feature = "web")]
    value_function: Box<Fn(Vec<f64>) -> f64>
}
```
Which produces
```
error: expected `,`, or `}`, found `#`
  --> src/lib.rs:70:49
   |
70 |     value_function: Box<Fn(Vec<f64>) -> f64 + Sync>
   |                                                    ^
```
regardless whether the feature is enabled or not.

Both fields are technically the last one in the struct, so omitting the comma shouldn't matter, right?

**Comment by Centril** [comment]
> Both fields are technically the last one in the struct, so omitting the comma shouldn't matter, right?

Not according to the parser which runs before any `#[cfg(..)]` stripping occurs.

**Comment by estebank** [comment]
Also, the prevalent style is to have trailing commas, as it makes diffs nicer when adding fields after the last one.

**Comment by Sogomn** [comment]
Thanks for the answers, wasn't sure if it's intended.
