### ISSUE TITLE
panic invoking self-referential closure through Option<Box<FnBox>>

### ISSUE THREAD

**Issue by anderspapitto** [rust-lang/rust#58441]
Here, I create a closure f which captures itself, and recurses via that capture. This panics unwrapping `f`, despite my having clearly assigned `f` to a `Some` value.

```
#![feature(fnbox)]

use std::boxed::FnBox;

fn main() { 
    let mut b = true;
    let mut f: Option<Box<FnBox() -> ()>> = None;
    f = Some(Box::new(move || {
        if b {
            b = false;
            f.unwrap()();
        };
    }));
    println!("f is now a Some: {:?}", f.is_some());
    f.unwrap()();
}
```

yields

```
   Compiling playground v0.0.1 (/playground)
    Finished dev [unoptimized + debuginfo] target(s) in 0.78s
     Running `target/debug/playground`
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:345:21
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=3f6508ff9c49059bab5d069215f0f30b

**Comment by anderspapitto** [comment]
This is perhaps a simpler example. Note that assigning to `x` is disallowed because it is considered borrowed by the closure, but assigning to `f` is allowed, and then breaks.

```
#![feature(fnbox)]

use std::boxed::FnBox;

fn main() { 
    let mut x = 3;
    let mut f: Option<Box<FnBox() -> ()>> = None;
    let g = || {
        println!("x {}", x);
        f.unwrap()();
    };
    x = 4; // illegal, x is borrowed by g
    f = Some(Box::new(|| { println!("inside f")})); // legal!!!!!!!!!!!!!!!!!
    g();
}
```

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=6d4333cb1ab8c2c88fb7fdf8a960422b

**Comment by jonas-schievink** [comment]
This is the same problem as in #58443: Here, in both examples, the `None` is moved into the closure, so the `.unwrap()` in the closure panics. You then assign a `Some` to the moved-out-of variable, so then `.is_some()` is true and the outer unwrap works.

The `x = 4;` assignment doesn't work because `x` is only borrowed by the closure, not moved into it (since all uses of `x` inside the closure only require a reference).
