### ISSUE TITLE
[src] links in rustdoc do not honor --extern-html-root-url

### ISSUE THREAD

**Issue by QuietMisdreavus** [rust-lang/rust#58472]
Originally reported at https://github.com/rust-lang/docs.rs/issues/298

The crate mentioned in that issue has a `#![doc(html_root_url)]` attribute set, and the `[src]` link that points to that crate is using that to base its url. However, the `--extern-html-root-url` that docs.rs passes to rustdoc should be overriding that setting. We should investigate how rustdoc generates `[src]` links, and see whether it needs to be modified to account for `--extern-html-root-url`, like how other cross-crate links are made.

**Comment by GuillaumeGomez** [comment]
The whole thing happens in [here](https://github.com/rust-lang/rust/blob/master/src/librustdoc/html/render.rs#L1355-L1384) and it seems the `--extern-html-root-url` option has priority over `#![doc(html_root_url)]`. Now my guess is: it's not given to sub-crates for some reason. Investigations continue!

**Comment by ollie27** [comment]
The [build log](https://docs.rs/crate/futures-preview/0.3.0-alpha.12/builds/137380) shows rustdoc was passed `--extern-html-root-url 'futures_util_preview=https://docs.rs/futures-util-preview/0.3.0-alpha.12'` but the crate name is `futures_util` not `futures_util_preview`. It looks like docs.rs needs to use the actual crate name not the package name.

**Comment by QuietMisdreavus** [comment]
@ollie27 That makes sense! I'll reopen the issue on docs.rs and close this one (and @GuillaumeGomez's PR).
