### ISSUE TITLE
Compiler warning for where clause

### ISSUE THREAD

**Issue by xd009642** [rust-lang/rust#58471]
My where clauses in traits recently had some unnecessary noise that the compiler could warn against:

What I was doing:
```Rust
impl<T> SomeTrait<T> where T: Clone, T: Debug
```

What I should have been doing:
```Rust
impl<T> SomeTrait<T> where T: Clone + Debug
```

I'd be happy to implement this myself if there's a consensus on adding this as a warning, though I may need some mentoring :+1:

**Comment by estebank** [comment]
These probably make more sense as clippy lints.

**Comment by xd009642** [comment]
That makes sense, I've raised an issue on clippy as well https://github.com/rust-lang/rust-clippy/issues/3764.

**Comment by Centril** [comment]
Closing in favor of the clippy issue.
