### ISSUE TITLE
Documentation for std::path::PathBuf::pop is slightly wrong

### ISSUE THREAD

**Issue by nathan** [rust-lang/rust#58474]
The documentation for `std::path::PathBuf::pop()` says:

> Returns `false` and does nothing if `self.file_name` is `None`. Otherwise, returns `true`.

However, `self.file_name()` is `None` when the path ends in `..`—but `pop()` still does removes that component and returns `true`. The docs should probably be changed to reflect that `pop()` [truncates and returns true unless *`self.parent()`* is `None`](https://github.com/rust-lang/rust/blob/f47ec2ad5b6887b3d400aee49e2294bd27733d18/src/libstd/path.rs#L1254).

```rust
use std::path::PathBuf;

fn main() {
  let mut p = PathBuf::from("/foo/bar/..");
  println!("{:?} {:?}", p.display(), p.file_name());
  println!("{:?}", p.pop());
  println!("{:?} {:?}", p.display(), p.file_name());
  println!("{:?}", p.pop());
  println!("{:?} {:?}", p.display(), p.file_name());
  println!("{:?}", p.pop());
  println!("{:?} {:?}", p.display(), p.file_name());
  println!("{:?}", p.pop());
  println!("{:?} {:?}", p.display(), p.file_name());
}
```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=3192d44720353ec0ec7381b7845040a8))

Output:

```
"/foo/bar/.." None
true
"/foo/bar" Some("bar")
true
"/foo" Some("foo")
true
"/" None
false
"/" None
```

**Comment by hellow554** [comment]
@nathan would you try to open a PR and edit the required paragraph?

https://github.com/rust-lang/rust/blob/master/src/libstd/path.rs#L1231-L1261

**Comment by nathan** [comment]
@hellow554 Sure thing! #58496
