### ISSUE TITLE
[CI] 3 hour timeout is not enough

### ISSUE THREAD

**Issue by Disasm** [rust-lang/rust#58480]
There was only one successful build in the last 24 hours: https://github.com/rust-lang/rust/pull/58446#issuecomment-463516558
All other builds were failed with timeout either on Travis or AppVeyor.

Related: https://github.com/rust-lang/rust/issues/58160

**Comment by pietroalbini** [comment]
The infra team already discussed this in the past, and our consensus is to keep the timeout to 3 hours. Our CI builds already take too long, limiting the amount of PRs we can merge in a day even if each of them doesn't fail. We prefer to work torwards reducing the amount of time spent on CI, and the timeout is an incentive to do so.
