### ISSUE TITLE
Nightly compiler 'inconsistent resolution for an import' for crate

### ISSUE THREAD

**Issue by bsoptei** [rust-lang/rust#58499]
I have a crate that compiles smoothly with stable, but with nightly I get the following error:
thread 'main' panicked at 'src\librustc_resolve\resolve_imports.rs:840: inconsistent resolution for an import', src\librustc\util\bug.rs:47:26

To reproduce, here's the link to the crate:
https://crates.io/crates/photonix_derive

## Meta
rustc 1.32.0 (9fda7c223 2019-01-16)
binary: rustc
commit-hash: 9fda7c2237db910e41d6a712e9a2139b352e558b
commit-date: 2019-01-16
host: x86_64-pc-windows-msvc
release: 1.32.0
LLVM version: 8.0

Backtrace:
   0: std::sys_common::alloc::realloc_fallback
   1: std::panicking::take_hook
   2: std::panicking::take_hook
   3: <rustc::ty::sty::Binder<rustc::ty::ProjectionPredicate<'tcx>> as rustc::ty::ToPredicate<'tcx>>::to_pr
edicate
   4: std::panicking::rust_panic_with_hook
   5: <rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor<'a, 'b, 'cl> as syntax::visit::Visitor<
'a>>::visit_ty
   6: <rustc_resolve::CrateLint as core::fmt::Debug>::fmt
   7: <rustc_resolve::CrateLint as core::fmt::Debug>::fmt
   8: <rustc_resolve::CrateLint as core::fmt::Debug>::fmt
   9: <rustc_resolve::CrateLint as core::fmt::Debug>::fmt
  10: <rustc_resolve::check_unused::UnusedImportCheckVisitor<'a, 'b, 'cl> as syntax::visit::Visitor<'a>>::v
isit_use_tree
  11: <rustc_resolve::check_unused::UnusedImportCheckVisitor<'a, 'b, 'cl> as syntax::visit::Visitor<'a>>::v
isit_use_tree
  12: rustc_resolve::resolve_imports::ImportResolver::finalize_imports
  13: rustc_resolve::Resolver::resolve_crate
  14: <rustc_driver::pretty::UserIdentifiedItem as core::fmt::Debug>::fmt
  15: rustc_driver::driver::count_nodes
  16: rustc_driver::driver::compile_input
  17: rustc_driver::run_compiler
  18: <rustc_driver::profile::trace::Query as core::fmt::Debug>::fmt
  19: rustc_driver::run_compiler
  20: <rustc_driver::profile::trace::Query as core::fmt::Debug>::fmt
  21: <rustc_driver::pretty::UserIdentifiedItem as core::fmt::Debug>::fmt
  22: _rust_maybe_catch_panic
  23: rustc_driver::profile::dump
  24: rustc_driver::main
  25: <unknown>
  26: std::panicking::update_panic_count
  27: _rust_maybe_catch_panic
  28: std::rt::lang_start_internal
  29: <unknown>
  30: <unknown>
  31: BaseThreadInitThunk
  32: RtlUserThreadStart
query stack during panic:
end of query stack

**Comment by pnkfelix** [comment]
triage: P-high.

**Comment by pnkfelix** [comment]
but I dont think it warrants nomination beyond that.I trust @petrochenkov will address this in some manner.

**Comment by pnkfelix** [comment]
I'm having difficulty reproducing the problem.

The issue description says that the problem arises on nightly, not stable; but the meta-information presented seems to describe a version of the compiler from the stable channel, not nightly.

I have built the crate successfully against several versions of nightly; all of them compile successfully.

@bsoptei , did you change the source code of the crate itself to work around this problem? In other words, do I need to back track to an earlier version of the code in order to witness its reproduction?

**Comment by pnkfelix** [comment]
(its also possible that this problem is somehow connected to reuse of previous build artifacts, which is another factor that can hinder reproduction.)

**Comment by petrochenkov** [comment]
The reproduction crate successfully builds on stable, beta and nightly channels, so I'm going to close as cannot-reproduce.
