### ISSUE TITLE
Native C++ FFI in the same manner as D

### ISSUE THREAD

**Issue by bstrie** [rust-lang/rust#5853]
@sanxiyn and @jdm have expressed interest in doing this, possibly in the 0.8 cycle.

http://www.reddit.com/r/rust/comments/1c3clf/c_ffi/c9codm1

**Comment by steveklabnik** [comment]
This issue has been moved to the RFCs repo: rust-lang/rfcs#602

**Comment by ArcaneEngineer** [comment]
Is this a likely addition during 2016? Or likely further on that that?
