### ISSUE TITLE
PrefixComponent looks at different fields in Eq and PartialEq

### ISSUE THREAD

**Issue by scottmcm** [rust-lang/rust#58552]
PrefixComponent has two fields and derives Eq:
https://github.com/rust-lang/rust/blob/9a3392e174a432a5f06c1157befc1ce0fae74bec/src/libstd/path.rs#L415-L422

But then it implements PartialEq _without_ deriving, and only looking at one of the fields:

https://github.com/rust-lang/rust/blob/9a3392e174a432a5f06c1157befc1ce0fae74bec/src/libstd/path.rs#L445-L450

I'm pretty sure that's wrong.

I suspect the fix is to explicitly implement `Eq`, as `PartialOrd` and `Ord` are also explicitly implemented to look at only the one field.

**Comment by sfackler** [comment]
`Eq` doesn't look at anything at all - it has no methods. It's simply a marker that states that the type's `PartialEq` methods behave a certain way.

**Comment by scottmcm** [comment]
Doh, brainfart.  Sorry for the noise, @sfackler.
