### ISSUE TITLE
libcore fails to build for sparc-unknown-linux-gnu

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/rust#58564]
The error is: 

```
LLVM ERROR: Cannot select: 0x7fc74ada41a0: ch = AtomicFence 0x7fc74ade17b8:1, Constant:i32<7>, Constant:i32<1>
  0x7fc74ada48f0: i32 = Constant<7>
  0x7fc74ada4f08: i32 = Constant<1>
In function: _ZN67_$LT$core..sync..atomic..AtomicBool$u20$as$u20$core..fmt..Debug$GT$3fmt17h129cea9414411e56E
error: Could not compile `core`.
```

**Comment by mati865** [comment]
LLVM was upgraded in nightly, could you retest?

**Comment by gnzlbg** [comment]
I can't, libc build jobs have been broken since the LLVM upgrade. Once all issues are resolved I will be able to retest.

**Comment by mati865** [comment]
Still fails: https://dev.azure.com/mati865/libc/_build/results?buildId=30&view=logs&j=d8d52ea2-3718-5ce1-d513-bf40cd76823d

**Comment by JohnTitor** [comment]
Seems this is resolved at some point in upgrading LLVM, CI for `sparc-unknown-linux-gnu` now works fine (rust-lang/libc#1935). I'm going to close this as fixed but feel free to re-open if I'm missing something :)
