### ISSUE TITLE
Optimized code generates valgrind errors

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#5856]
We are accumulating a lot of valgrind suppressions because of this: http://llvm.org/bugs/show_bug.cgi?id=12319

**Comment by steveklabnik** [comment]
Triage: @huonw 's `valgrind rustc` example still reproduces.

**Comment by Mark-Simulacrum** [comment]
So I'm not quite sure what the status here is. @thestinger is correct as I understand it: this cannot be fixed without crippling LLVM's optimizations. So should this be closed?

**Comment by Mark-Simulacrum** [comment]
Closing. This is an LLVM problem (and, AIUI, a general problem with optimizing code) -- valgrind doesn't handle this properly, and there's ~nothing we can do as I understand it.
