### ISSUE TITLE
rust 1.32.0: Inconsistent libc versions used

### ISSUE THREAD

**Issue by he32** [rust-lang/rust#58572]
It looks like rust 1.32.0 is inconsistent in which versions of `libc` it uses:

- `vendor/libc/Cargo.toml` says `0.2.45`
- `src/liblibc/Cargo.toml` says `0.2.43`

Is there a good reason for this apparent version skew?

**Comment by jonas-schievink** [comment]
These shouldn't matter much since the actual version is stored in `Cargo.lock` anyways, and the versions only differ in the patch version, so they should end up using the same libc version. Closing as not-a-bug, but let me know if this is wrong and I'll reopen.
