### ISSUE TITLE
compiler error E0505 example compiles with 2018 edition

### ISSUE THREAD

**Issue by gurgalex** [rust-lang/rust#58586]
Taken from [https://doc.rust-lang.org](https://doc.rust-lang.org/error-index.html#E0505)
[Erroneous code compiles fine for E0505](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=5bf27b44da06b2b181d41c0c7eec98fc)

A possible way to [trigger E0505 in the 2018 edition](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=93372135deaafc1f1e74982b664d5d3d)

Rust version 1.32 on playground

**Comment by gurgalex** [comment]
Where are the error code examples in the repo?

**Comment by hellow554** [comment]
https://github.com/rust-lang/rust/blob/8af675a07576940ba24e3d91abd10b029b937946/src/librustc_mir/diagnostics.rs#L1540-L1557

**Comment by gurgalex** [comment]
Which part do I need to build for rustc --explain E0505 to reflect changes in `rust/src/librustc_mir/diagnostics.rs`?

**Comment by zackmdavis** [comment]
I think a [stage 1 build](https://rust-lang.github.io/rustc-guide/how-to-build-and-run.html) should be fine? `./x.py build -i --stage 1 src/libtest`
