### ISSUE TITLE
Bootstrap compiler for FreeBSD/PowerPC64

### ISSUE THREAD

**Issue by lenoil98** [rust-lang/rust#58585]
Now that powerpc64-unknown-freebsd supports has been added.  There is no bootstrap compiler download available.  When, if ever, will a bootstrap compiler be available.  Otherwise, how do you cross compile rustc?

**Comment by Mark-Simulacrum** [comment]
This isn't the best place to discuss this - internals would be better.

However, to answer your question, if (maybe when) we're building a full toolchain for any target I believe it should automatically be available as a bootstrap compiler within at most 6 weeks of landing in master.
