### ISSUE TITLE
`Duration::as_millis` and `Duration::from_millis` has different integer types

### ISSUE THREAD

**Issue by niklasad1** [rust-lang/rust#58580]
Would be nice if both [Duration::as_millis](https://doc.rust-lang.org/std/time/struct.Duration.html#method.from_millis) and [Duration::from_millis](https://doc.rust-lang.org/std/time/struct.Duration.html#method.as_millis) had the same integer types.

For example:

```rust
  let dur: Duration = Default::default();
  let millis: u128 = dur.as_millis();
  // make a new Duration 
  // don't work
  let dur2 = Duration::from_millis(millis); 
``

**Comment by jonas-schievink** [comment]
This isn't really possible since changing the type used by `from_millis` is a breaking change and `as_millis` is only possible because `u128` is a thing now (so changing that to `u64` would defeat the purpose of that function)

**Comment by niklasad1** [comment]
Right, everytime I want to convert `millis: u128` to a Duration I need to do it manually which doesn't seem like an ideal API to me!

**Comment by jonas-schievink** [comment]
Duration only stores 96 bits internally, you'd have to either extend that or do some amount of truncation anyways

**Comment by niedzielski** [comment]
Is a "`from_millis128()`" API a bad idea? As a new Rust user, I hit this issue too and was surprised that I couldn't go back and forth between milliseconds as a primitive and Duration.

I'm not sure what's best practice. If a change to the API doesn't make sense, a change to the documentation describing the recommended handling of a u128 would be a splendid improvement :+1: Thank you!

**Comment by Dylan-DPC** [comment]
Closing this as it would be a breaking change if it happens, plus there are other concerns listed above.
