### ISSUE TITLE
impl FromStr for NonZeroU8, NonZeroU16, ...

### ISSUE THREAD

**Issue by bcmyers** [rust-lang/rust#58604]
Is there any reason why the following types couldn't implement `core::str::FromStr`?

* `core::num::NonZeroU8`
* `core::num::NonZeroU16`
* `core::num::NonZeroU32`
* `core::num::NonZeroUsize`
* `core::num::NonZeroU64`
* `core::num::NonZeroU128`

**Comment by scottmcm** [comment]
Sounds plausible, though what the error type should be is an interesting question -- there's nothing in `IntErrorKind` that seems to be a good match for "`NonZeroIsize` was zero".

**Comment by bcmyers** [comment]
`IntErrorKind::Underflow` maybe? Although I agree that's a stretch. Otherwise, you'd have to either:

* Introduce a new error type (`ParseNonZeroUintError`???), or 
* Add a variant to `IntErrorKind` (which might be OK since it's meant to be non-exhaustive (I think)).

In any case, these kinds of decisions are above my pay grade :). Just seems a shame that this integer functionality (`FromStr`) isn't available for NonZero types as well.

**Comment by hellow554** [comment]
Taking this issue :party:
