### ISSUE TITLE
ctfe validation on unaligned references does not mention expected / provided alignment

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/rust#58617]
This code ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=6974adc5eb31718faeaf0456a302c6f3)):

```rust
fn main() {
    unsafe {
        use std::mem::transmute;
        let a = 0_u8;
        let b = &a as *const u8 as *const u64;
        //let _c: &u64 = transmute(b);
        let _d = *b;
    }
}
```

errors under miri with

```
tried to access memory with alignment 1, but alignment 8 is required
```

This snippet, however ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=c8f31335496a1688f67bde0f84464fc4)): 

```rust
fn main() {
    unsafe {
        use std::mem::transmute;
        let a = 0_u8;
        let b = &a as *const u8 as *const u64;
        let _c: &u64 = transmute(b);
        //let _d = *b;
    }
}
```

errors with

```
type validation failed: encountered unaligned reference
```

It would be great if this error about the validity of references would also state that "alignment 1, but alignment 8 is required" or similar.

cc @oli-obk @RalfJung

**Comment by oli-obk** [comment]
I think all we need is https://github.com/rust-lang/rust/blob/0e25a6829c66302dc06c351bb494774e3d075f77/src/librustc_mir/interpret/validity.rs#L360-L361 to actually use the fields of the `AlignmentCheckFailed` and add their information to the validation failure string.

**Comment by pmccarter** [comment]
I'd like to do it.

**Comment by oli-obk** [comment]
It's all your's, let me know if you have any questions

**Comment by pmccarter** [comment]
Hmm both of these snippets seem to compile in the playground (when unused use removed).

**Comment by gnzlbg** [comment]
Yes the examples compile fine. The issue is triggered by running them under miri.

**Comment by oli-obk** [comment]
You can probably repro the same thing in rustc with const eval by making the final value be such an invalid reference

**Comment by oli-obk** [comment]
Jup, here's a repro (that you can use as a regression test, too):

```rust
#![feature(const_transmute)]
const FOO: &u64 = unsafe {
    use std::mem::transmute;
    let a = &0_u8;
    let b = a as *const u8 as *const u64;
    transmute(b)
};
```

**Comment by hellow554** [comment]
Note, that clippy does emit an error:

> error: casting from `*const u8` to a more-strictly-aligned pointer (`*const u64`)

**Comment by gnzlbg** [comment]
@hellow554 thanks, i've reported the issue there tiL https://github.com/rust-lang/rust-clippy/issues/3797
