### ISSUE TITLE
fs::copy() does not handle sparse files

### ISSUE THREAD

**Issue by haraldh** [rust-lang/rust#58635]
A convenience method like fs::copy() should try to prevent pitfalls a
normal user doesn't think about.

Not handling sparse files could fill up the users disk very quickly.

In case of an empty umask, setting the file mode early prevents
temporarily world readable or even writeable files,
because the default mode is 0o666.

In case the target is a named pipe or special device node, setting the
file mode can lead to unwanted side effects, like setting permissons on
`/dev/stdout` or for root setting permissions on `/dev/null`.

See also
https://github.com/rust-lang/rust/issues/26933
https://github.com/rust-lang/rust/issues/37885

**Comment by haraldh** [comment]
see #58636 for the fix

**Comment by Mark-Simulacrum** [comment]
I believe we've decided that sparse files are not something we want to handle; the file mode and special device issue we've fixed. Closing.

**Comment by avirtuos** [comment]
@Mark-Simulacrum I realize this is an old issue but can you share some insights into why it was decided that sparse files are not something you want to handle? There are a few growing rust projects related to VMMs like ( https://github.com/firecracker-microvm/firecracker ) that are built largely with rust and frequently trip over this limitation.

**Comment by Mark-Simulacrum** [comment]
Likely largely based on discussion in https://github.com/rust-lang/rust/pull/55909 and https://github.com/rust-lang/rust/pull/58636, though it's been some time since then. Feel free to drop by #t-libs on Zulip and ask for folks opinions now.

(It may also be that the necessary work to make this happen is easier now, if the kernel APIs have simplified somewhat).

**Comment by avirtuos** [comment]
@Mark-Simulacrum thanks, will follow up as you suggest after reading those items.
