### ISSUE TITLE
Align dbg!() and line!() output

### ISSUE THREAD

**Issue by ranxiverba** [rust-lang/rust#58647]
Hello. 

Please, consider this issue as a minor.

Output of dbg!() macro will be better if it will align source code line number. I found that line!() macro does it. I think it would be nice if this macro always emit 4 chars, because most source code files has less than 10k lines. Consider the example:

    [some/main.rs:84] hex::encode(dst.as_ref()) = "686aca464489"
    [some/main.rs:126] hex::encode(src.as_ref()) = "f8c91afe015f"

I guess this will be better:

    [some/main.rs:  84] hex::encode(dst.as_ref()) = "686aca464489"
    [some/main.rs: 126] hex::encode(src.as_ref()) = "f8c91afe015f"

or

    [some/main.rs:0084] hex::encode(dst.as_ref()) = "686aca464489"
    [some/main.rs:0126] hex::encode(src.as_ref()) = "f8c91afe015f"

Thank you.

**Comment by Centril** [comment]
If we're going to pick between those two new formats I'd go with the latter since it doesn't feel "empty". However, I'm not sure that the common case would benefit from a change.

**Comment by alexcrichton** [comment]
Closing in accordance with the same action as https://github.com/rust-lang/rust/pull/58753, and the PR has some more information as to why.
