### ISSUE TITLE
async fn should be disallowed entirely on 2015 edition

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#58652]
As described in https://github.com/rust-lang/rust/issues/53714, we currently permit a small amount of `async` notation in 2015, but we can't extend that to the complete feature set (e.g., await keywords etc). This was done as part of a transitionary tactic (so people could move to Rust 2018) but by now that is not necessary. We should just prohibit `async fn` in Rust 2015 entirely at this point.

**Comment by nikomatsakis** [comment]
Note we should also test nested async fn in fns, as described in https://github.com/rust-lang/rust/issues/51933

**Comment by doctorn** [comment]
Hello, I'd like to have a go at this
