### ISSUE TITLE
llvm-nm no symbols for standalone wasm32 modules

### ISSUE THREAD

**Issue by nhynes** [rust-lang/rust#58657]
[**MWE crate**](https://github.com/nhynes/wasm-nm-mwe)

### Summary

In the context of `wasm32-unknown-unknown`, I'm trying to discovery why an exported symbol in an external static library isn't being found during Rust linking. I hoped that `cargo nm` would yield insight but it does not find any symbols. Oddly, it _does_ work for clang-compiled libraries.

From the MWE readme:

**Actual output**: `no symbols`
**Expected output**: `main` is exported

Output of `wasm-nm`:
```
p __wasm_call_ctors
e main
```

Alternatively, perhaps someone could suggest how to see what symbols are visible to the `rustc` linker and where the exports went?

**Comment by alexcrichton** [comment]
I believe this is a toolchain issue and is inherent to how the object format for wasm modules was unstable at the time this was opened. Tools will eventually settle though and support will be implemented, but this isn't an issue to track in rustc.
