### ISSUE TITLE
Rustdoc does not show reexported members when using #[doc(inline)] on other crate

### ISSUE THREAD

**Issue by TimDiekmann** [rust-lang/rust#58693]
**Expected behavior:**

Both, module and trait, are shown:

![image](https://user-images.githubusercontent.com/21277928/53298038-de8a5b00-3827-11e9-9f24-e330e9487f02.png)

---

**Observed behavior:**

Only module is shown:

![image](https://user-images.githubusercontent.com/21277928/53298025-9cf9b000-3827-11e9-9cac-6db56954de99.png)

---

**Reproduction:**

```sh
# Create project
cargo new rustdoc-test 
cd rustdoc-test

# Create inner crate
cargo new rustdoc-test-inner --lib  

# Add inner crate as dependency and to workspace
echo -e "rustdoc-test-inner = { path = \"rustdoc-test-inner\" }\n\n[workspace]\nmembers = [\"rustdoc-test-inner\"]" >> Cargo.toml 

# Reexport inner crate with `#[doc(inline)]`
echo -e "#[doc(inline)]\npub use rustdoc_test_inner;" >> src/main.rs

# Define a trait and reexport it in `prelude`
echo -e "pub mod prelude {\n    pub use super::FooTrait;\n}\n\npub trait FooTrait {}" > rustdoc-test-inner/src/lib.rs
cargo doc --open
```

**Notes**
- Tested on latest nightly and stable
- Without `#[doc(inline)]` it's shown, however it's reexported as crate and is not compatible with `cargo doc --no-deps`

CC #24305

**Comment by fmease** [comment]
Now works as expected, closing.

(Reproduction steps were slightly outdated (need to move `[workspace]` decl above `[dependencies]`) & omitted some details (creation of inner package `rustdoc-test-inner`)).
