### ISSUE TITLE
intra-doc links to modules instead of primitives inside standard library

### ISSUE THREAD

**Issue by tspiteri** [rust-lang/rust#58699]
For example in the doc for [`str::len`](https://doc.rust-lang.org/nightly/std/primitive.str.html#method.len):

> This length is in bytes, not [`char`](https://doc.rust-lang.org/nightly/std/char/index.html)s or graphemes.

The `char` in the doc links to [char/index.html](https://doc.rust-lang.org/nightly/std/char/index.html) instead of [primitive.char.html](https://doc.rust-lang.org/nightly/std/primitive.char.html).

Outside of the standard library, `char` links to the primitive, unless there is a `use std::char;` statement in which case it links to the module.

**Comment by GuillaumeGomez** [comment]
Therefore we should try to link to types before modules I assume? I'll see how it comes out.

**Comment by tspiteri** [comment]
Yes I think types should go before modules.

After all it's always possible to use ``[`char`][`std::char`]`` if you actually want to link to the `std::char` module using `char` as the link text.

**Comment by GuillaumeGomez** [comment]
Oh btw, you can force the resolution by adding the type before hand like `method@len`. I wonder if this is documented somewhere...

**Comment by GuillaumeGomez** [comment]
It comes from the compiler directly. We need to re-order how the items are resolved.

cc @rust-lang/compiler

**Comment by jyn514** [comment]
@GuillaumeGomez an alternative is to resolve in an empty module first and only then resolve in the current scope. This ambiguity is only possible for primitives, any other types will give a multiple definition error: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=16d8de614c51403e2f8576f355ed6f9c. Since primitives are always in scope they will be the only thing in scope in the empty module (assuming there's no `super`, `crate`, or `self` keyword).

**Comment by jyn514** [comment]
> @jyn514 I'm a bit wary of doing this because having the char module in scope is not a common situation, and it will get weirder for people who have a different char module.

> I think we should resolve to whatever is in scope, but if `type@` is explicitly mentioned we can then force resolve to the primitive.

_Originally posted by @Manishearth in https://github.com/rust-lang/rust/issues/74063#issuecomment-653964147_

@Manishearth is this still your opinion? That would mean closing this issue as wontfix, but I'm not convinced that's the most clear behavior.

**Comment by Manishearth** [comment]
@jyn514 Well, I would close this as fixed, but yes. I think this is a pretty rare situation to be in and the current behavior is not incorrect, it's just surprising, but "fixing" it would also make it surprising to another group.

**Comment by jyn514** [comment]
@Manishearth and I discussed this again and decided it would be less surprising than the current behavior (@Manishearth himself made the same mistake in https://github.com/rust-lang/rust/pull/74470!) So I plan to implement this sometime soon.
