### ISSUE TITLE
impl trait from unboxed_closure does not accept closures

### ISSUE THREAD

**Issue by CodeSandwich** [rust-lang/rust#58708]
It's impossible to pass closure to a generic fn with impl trait argument when the trait comes from unboxed_closure feature. 

This compiles (uses impl Fn with arrow):
```rust
fn main() {
    baz(|x| x);
}

fn baz(_: impl Fn(bool) -> bool) {}
```
But this fails (uses impl trait from unboxed_closure):
```rust
fn main() {
    bar(|x| x);
}

fn bar(_: impl Fn<bool, Output = bool>) {}
```
Returns error:
```
found signature of `fn(_) -> _`
expected signature of `fn(bool) -> _`
```
Precise definition of closure's types does not help.
[Playground](https://play.rust-lang.org/?version=nightly&edition=2018&gist=eed841ca58c977c7a7e5041f27b50fa4)

**Comment by sfackler** [comment]
The desugared version of `Fn(bool) -> bool` is `Fn<(bool,), Output = bool>` - the first generic argument has to be a tuple not a bare value.

**Comment by CodeSandwich** [comment]
Oh my goodness, of course! Sorry for the noise.
