### ISSUE TITLE
Bad error message for when an assigned associated type does not satisfy the trait bounds

### ISSUE THREAD

**Issue by LukasKalbertodt** [rust-lang/rust#58707]
This code:

```rust
trait Bar {}

trait Foo {
    type Assoc: Bar;
}

impl Foo for () {
    type Assoc = bool;
}
```

Leads to (stable 1.32 and nightly 1.34):

```
error[E0277]: the trait bound `bool: Bar` is not satisfied
 --> src/lib.rs:7:6
  |
7 | impl Foo for () {
  |      ^^^ the trait `Bar` is not implemented for `bool`
```

The error is that `bool` does not implement `Bar`. I would expect that the error points to the line `type Assoc = bool;`, potentially with a good note. Example:

```
error[E0277]: the trait bound `bool: Bar` is not satisfied
 --> src/lib.rs:7:6
  |
8 |     type Assoc = bool;
  |     ^^^^^^^^^^^^^^^^^^ the trait `Bar` is not implemented for `bool`
  |
  = note: trait `Foo` requires the associated type `Assoc` to satisfy the bound `Bar`
```

**Comment by hellow554** [comment]
Dup of https://github.com/rust-lang/rust/issues/57663 ?

**Comment by LukasKalbertodt** [comment]
@hellow554 Yep, looks extremely similar! Since it's not exactly the same, I copied my example to your issue to make sure both things are actually solved at some point (just in case fixing one does not fix the other). But yes, this can be closed now.
