### ISSUE TITLE
Duplicate library and language feature gates silently fail

### ISSUE THREAD

**Issue by dlrobertson** [rust-lang/rust#58715]
## Summary

If a language feature and a library feature are given the same name `![feature(<name>)]` will only evaluate the language feature.

## Expected Result

There should either be some sort of error that is thrown if both a language feature and a library feature have the same name, or both should be evaluated.

**Comment by Centril** [comment]
Seems like something that could go into `tidy`? cc @rust-lang/infra

**Comment by varkor** [comment]
It should be straightforward to make this an error. I'll look into it.
