### ISSUE TITLE
Idiomatic Rc::clone is unusable with dyn Trait parameters

### ISSUE THREAD

**Issue by neyo8826** [rust-lang/rust#58716]
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=0771a25efd95be83580de70b3d08db75

AFAIK `Rc::clone()` should be used, instead of `.clone()`.
It seems free functions are getting their type parameters from the outer scope, not from their own arguments.
Can we coerce it somehow

**Comment by jonas-schievink** [comment]
Isn't this just caused by the fact that `.`-syntax performs coercions on the receiver?

**Comment by neyo8826** [comment]
```rust
fn clone(&self) -> Self;
fn clone(&self) -> Rc<T>;
```
So, the UFCS version gets it actual type from the caller site (`Rc<T>`).
The coercion shoud occour after the function call, since the type of `self` is fix, not the coerced result.
We could restrict this deduction inversion for cases invovin subtyping only (`T` as `dyn Trait`)

**Comment by kennytm** [comment]
This is rust-lang/rust-clippy#2048 which is also one of the reasons why the [`clippy::clone_on_ref_ptr` lint](http://rust-lang.github.io/rust-clippy/current/index.html#clone_on_ref_ptr) has been [demoted](https://github.com/rust-lang/rust-clippy/pull/2355) to the "restriction" group. That is, we no longer consider in general `Rc::clone(&st)` is more idiomatic than `st.clone()`.

The workaround is to write `Rc::<St>::clone(&st)`, BTW.
