### ISSUE TITLE
rustdoc: redundant `where 'env: 'env`

### ISSUE THREAD

**Issue by stjepang** [rust-lang/rust#58737]
Source: https://docs.rs/crossbeam/0.7.1/crossbeam/thread/struct.Scope.html

Generated by rustdoc:

```rust
pub struct Scope<'env>
where
    'env: 'env,
 { /* fields omitted */ }
```
Original code:

```rust
pub struct Scope<'env> {
    handles: SharedVec<SharedOption<thread::JoinHandle<()>>>,
    wait_group: WaitGroup,
    _marker: PhantomData<&'env mut &'env ()>,
}
```

Rustdoc has somehow inferred the `'env: 'env` bound, which is a tautology.

**Comment by ollie27** [comment]
This needs to be reopened because #58894 didn't actually fix this. An example from `std` is https://doc.rust-lang.org/nightly/std/fmt/struct.Arguments.html 
![image](https://user-images.githubusercontent.com/7189418/55690740-41295780-598d-11e9-9a0e-c975e03fcc03.png)

**Comment by jyn514** [comment]
This is no longer present for `Arguments` on nightly ... can someone come up with an MVCE?

**Comment by jyn514** [comment]
Since `Arguments` is fixed on master and [`Scope` works as well](https://docs.rs/crossbeam/0.8.0/crossbeam/thread/struct.Scope.html), I'm going to close this. Feel free to reopen if you find somewhere else this bug appears.
