### ISSUE TITLE
enum variants aren't considered to be const

### ISSUE THREAD

**Issue by doy** [rust-lang/rust#5873]
This compiles:
```rust
static i: int = 4;

fn main () {
    let x: [int, ..i] = [1, 2, 3, 4];
    println(fmt!("%?", x));
}
```
But this doesn't:
```rust
enum Foo {
    Bar = 4,
}
static i: int = Bar as int;

fn main () {
    let x: [int, ..i] = [1, 2, 3, 4];
    println(fmt!("%?", x));
}
```
```
test2.rs:7:11: 7:21 error: expected constant expr for vector length: Can't cast str to int
test2.rs:7     let x: [int, ..i] = [1, 2, 3, 4];
                      ^~~~~~~~~~
```
That error message doesn't seem to make sense, but that may be because it's just confused - I also get this error message in other circumstances, and I don't understand what the difference is:
```
src/info/builtin.rs:79:11: 79:52 error: expected constant expr for vector length: Non-constant path in constant expr
src/info/builtin.rs:79 static db: [[Option<&'static str>, ..ncap], ..nterm] = [
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by frewsxcv** [comment]
*Visiting for triage*

Updated the example to compile with the latest Rust

```rust
enum Category {
    A,
    B,
    C,
    NumCategories,
}
static NUM_CATEGORIES: uint = Category::NumCategories as uint;

fn main() {
    let the_categories: [Category; NUM_CATEGORIES] = [Category::A, Category::B, Category::C];
    println!("{}", the_categories);
}
```

[Playpen](http://is.gd/R4iAJJ)

Can confirm it still doesn't compile

```


<anon>:7:24: 7:28 warning: the `uint` type is deprecated; use `usize` or a fixed-sized integer
<anon>:7 static NUM_CATEGORIES: uint = Category::NumCategories as uint;
                                ^~~~
<anon>:7:24: 7:28 help: add #![feature(int_uint)] to the crate attributes to silence this warning
<anon>:7 static NUM_CATEGORIES: uint = Category::NumCategories as uint;
                                ^~~~
<anon>:7:58: 7:62 warning: the `uint` type is deprecated; use `usize` or a fixed-sized integer
<anon>:7 static NUM_CATEGORIES: uint = Category::NumCategories as uint;
                                                                  ^~~~
<anon>:7:58: 7:62 help: add #![feature(int_uint)] to the crate attributes to silence this warning
<anon>:7 static NUM_CATEGORIES: uint = Category::NumCategories as uint;
                                                                  ^~~~
<anon>:10:25: 10:51 error: expected constant expr for array length: non-constant path in constant expr [E0250]
<anon>:10     let the_categories: [Category; NUM_CATEGORIES] = [Category::A, Category::B, Category::C];
                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~
playpen: application terminated with error code 101
Program ended.
```

**Comment by pnkfelix** [comment]
So, just to review the situation, and repeat what @nikomatsakis and I stated earlier:

1. The original bug from the description has been fixed.  Namely, these two programs both run:

    First program:
    ```rust
    const I1: usize = 4;

    fn main () {
        let x: [i32; I1] = [1, 2, 3, 4];
        println!("{:?}", x);
    }
   ```

    Second program:
    ```rust
    enum Foo {
        Bar = 4,
    }
    const I2: usize = Foo::Bar as usize;

    fn main () {
        let x: [i32; I2] = [1, 2, 3, 4];
        println!("{:?}", x);
    }
    ```

2. There is *another* program from [a comment above](https://github.com/rust-lang/rust/issues/5873#issuecomment-23384763) that does not work, but I do not think it was ever part of Rust's design that it *would* work as written:

```rust
#[derive(Debug)]
enum Category {
    A,
    B,
    C,
    NumCategories,
}
const NUM_CATEGORIES: usize = Category::NumCategories as usize;

use Category::*;

fn main() {
    let the_categories: [Category; NUM_CATEGORIES] = [A, B, C];
    println!("{:?}", the_categories);
}
```

This is the case where you get the following error:
```
<anon>:34:25: 34:51 error: expected constant expr for array length: non-constant path in constant expr [E0250]
<anon>:34     let the_categories: [Category; NUM_CATEGORIES] = [A, B, C];
```

----

Footnote 1: both @pnkfelix and @nikomatsakis think the last program above is using an *anti-pattern*; that is, it is not idiomatic Rust to encode meta-information like "the number of enum variants" as a member itself of the enum.  (We may extend the language in the future with some sort of associated constant that provides such information, but that is not part of the current design.)

Footnote 2: there is a straight-forward workaround, if one wants to insist on using the anti-pattern: Put an explicit value in for the `NumCategories` variant:

```rust
#[derive(Debug)]
enum Category {
    A,
    B,
    C,
    NumCategories = 3,
}
const NUM_CATEGORIES: usize = Category::NumCategories as usize;

use Category::*;

fn main() {
    let the_categories: [Category; NUM_CATEGORIES] = [A, B, C];
    println!("{:?}", the_categories);
}
```

Note also that the Rust compiler will *catch* if you put too low a value in for `NumCategories above, as long as you have not assigned "out-of-band" values to the earlier variants.  In other words, this code will fail to compile:

```rust
#[derive(Debug)]
enum Category {
    A,
    B,
    C,
    NumCategories = 2, // this is too low!
}
const NUM_CATEGORIES: usize = Category::NumCategories as usize;

use Category::*;

fn main() {
    let the_categories: [Category; NUM_CATEGORIES] = [A, B];
    println!("{:?}", the_categories);
}
```

This yields the compile-time error:
```
<anon>:27:5: 27:22 error: discriminant value `2` already exists [E0081]
<anon>:27     NumCategories = 2, // this is too low!
              ^~~~~~~~~~~~~~~~~
<anon>:26:5: 26:6 note: conflicting discriminant here
<anon>:26     C,
              ^
```

(I suspect there may even be a straight-forward macro one could write that creates a static array of all the values, to ensure that the provided number is also not too large.  Demonstrated here: http://is.gd/rGTANu Though such a macro would benefit from extensions like https://github.com/rust-lang/rfcs/issues/407 for counting.)

**Comment by pnkfelix** [comment]
I think we should close this ticket.  Nominating for closure.

**Comment by pnkfelix** [comment]
(closing)

**Comment by tommit** [comment]
Let me get this straight. Rust doesn't allow using c-like enum variants in compile-time evaluation contexts in general, unless the user opts-in to this workaround you've pointed out. Library writers don't know which ones of their public c-like enum variants might be needed to be used as compile-time constants, so they'd have to explicitly specify the values for each variant.

To me this is clearly a compiler bug, and as far as I can tell, you refuse to fix it just because the person reporting it happened to be using an anti-pattern in demonstrating it.

**Comment by tikue** [comment]
It's backwards compatible to add implicit ordinals, no?

**Comment by pnkfelix** [comment]
@tommit compiler bug != language feature

**Comment by pnkfelix** [comment]
> I believe the phrase "C-like enum variant" is meant to refer to variants that have been given an explicit value. 

I might be wrong on this point; I will check more carefully when I am in front of a computer again

**Comment by tommit** [comment]
[The Reference](http://doc.rust-lang.org/reference.html#enumerations) claims the following:
>Enums have a discriminant. You can assign them explicitly: `enum Foo { Bar = 123 }`
>
>If a discriminant isn't assigned, they start at zero, and add one for each variant, in order.
>You can cast an enum to get this value: `let x = Foo::Bar as u32; // x is now 123u32`
>
>This only works as long as none of the variants have data attached. If it were Bar(i32), this is disallowed.

From that quote I gather, that given the `enum E { A, B }`, Rust guarantees that `E::A as usize == 0_usize` and `E::B as usize == 1_usize`. If Rust can make those guarantees now in its reference manual, then why can't it make the same guarantees at compile-time?

@pnkfelix You say that it's a language feature that these unassigned nullary enum variants (which belong to an enum whose all variants are nullary) aren't compile-time constants. What is the language design reasoning behind this feature?

**Comment by pnkfelix** [comment]
@tommit I was not attempting to claim that it was a language feature that these aren't compile-time constants.  (I do concede that my earlier response can be interpreted that way.)

I was trying to claim that changing the current language to treat them as compile-time constants *would* be a language feature, and thus should go through the RFC process.  (After all, a ticket like this really isn't the appropriate venue to debate the value of such a change.)

----

Here's the essence of what I was thinking when I wrote that response: I have been long under the impression that we were reserving the right to change how discriminant values are assigned by the compiler if not explicitly assigned by programmer.

(Of course actually allowing such a change would probably require restricting the current language; i.e. `Variant as Type` when `Variant` would need to be outlawed during dynamic execution in addition to it being disallowed at compile time.  And I imagine we could not do that unless we simultaneously accepted https://github.com/rust-lang/rfcs/pull/639 and probably provided a stable API to that RFC as well.)

Its quite possible that my mental model of what we were planning to permit in the future was simply over-aggressive; i.e. that no one else on the team was planning on ever changing the assignment of discriminant values, at least not for enum variants that do not have a data payload attached.

**Comment by pnkfelix** [comment]
reopening and putting on agenda for next meeting; this deserves discussion at the team meeting, if only to get clarification about what guarantees we plan with respect to discriminant value assignment.

**Comment by tommit** [comment]
@pnkfelix Thank you for getting this thing to get sorted out and for clearing up my earlier confusion.

**Comment by nikomatsakis** [comment]
Hmm, I tend to agree with @tommit that it should work for both explicitly assigned and unassigned values, if it works at all.

**Comment by nikomatsakis** [comment]
(I didn't fully appreciate when commenting before that it worked only in one case and not the other.)

**Comment by pnkfelix** [comment]
So after discussing with @nikomatsakis i concluded that my mental model is simply wrong, and that there is not sufficient value in trying to future-proof our future discriminant value assignment.  In particular @nikomatsakis pointed out to me multiple times that the chosen discriminant value need not be directly represented as the numeric value chosen; thus various tricks I was anticipating (usually revolving around ensuring that e.g. bit patterns are non-zero) should be able to be adopted in the future.

Anyway, the bugs been reopened; we should fix this, for consistency's sake.

**Comment by pnkfelix** [comment]
triage: P-high

(In some sense this is a feature request, or at least a request for consistently deploying a particular feature.   Fixing this may be important when/if `const fn` comes, but its hard to tell right now.)

**Comment by pnkfelix** [comment]
Decided to file a fresh issue, #23898, to ease triage.  (I.e. right now the main item left on this bug is hard to actually extract from the thread of conversation as presented.)
