### ISSUE TITLE
LLVM ERROR: SEH unwind data splitting not yet implemented on aarch64

### ISSUE THREAD

**Issue by emilio** [rust-lang/rust#58735]
Rust's version of LLVM doesn't seem to have https://bugs.llvm.org/show_bug.cgi?id=40311. That's giving us a lot of headache on Firefox.

https://bugzilla.mozilla.org/show_bug.cgi?id=1530098#c4
https://bugzilla.mozilla.org/show_bug.cgi?id=1516337#c33
https://bugzilla.mozilla.org/show_bug.cgi?id=1529681

Could we get that revision uplifted to the Rust LLVM version, please?

cc @dmajor @froydnj

**Comment by nikic** [comment]
The mentioned revision is already in the rust LLVM fork, update pending in #58408.

**Comment by nikic** [comment]
The LLVM update has gone through in the meantime. Is this issue resolved now?

**Comment by emilio** [comment]
I'm not sure yet. https://bugzilla.mozilla.org/show_bug.cgi?id=1531986 tracks updating to Nightly, but I can't land that until https://bugzilla.mozilla.org/show_bug.cgi?id=1521249 lands and such.

I'm happy to tentatively close this though, I'll reopen if it appears again.
