### ISSUE TITLE
AsRef docs link to old version of the book

### ISSUE THREAD

**Issue by Lokathor** [rust-lang/rust#58740]
https://doc.rust-lang.org/std/convert/trait.AsRef.html

Links to

https://doc.rust-lang.org/book/first-edition/borrow-and-asref.html

**Comment by lzutao** [comment]
Fixed on nightly https://doc.rust-lang.org/nightly/std/convert/trait.AsRef.html.

**Comment by steveklabnik** [comment]
Thanks for both of you! For reporting, and for checking that it's fixed. Closing!
