### ISSUE TITLE
Tuple semantic names

### ISSUE THREAD

**Issue by NN---** [rust-lang/rust#58751]
Today Rust allows either defining tuple without names or define struct with names.
It would be nice feature to have semantic names in tuples which are just names hint while writing the code.
For instance, C# language has such feature:
https://docs.microsoft.com/en-us/dotnet/csharp/tuples

```cs
var anonymous = (16, "a perfect square"); // Regular tuple without semantic names
var named = (Answer: 42, Message: "The meaning of life"); // Semantic names
var differentNamed = (SecretConstant: 42, Label: "The meaning of life"); // Semantic names

// But type of named and type of differentNamed is the same, thus they can be assigned to each other
named = differentNamed;
```

This requires a small syntax extension, e.g.:

```rust
struct RGB(red: i32, blue: i32, green: i32);

let rgb = RGB(1, 2, 3) ;// Here editor can show names hints

let red = rgb.0; // Same as below
let red = rgb.red; // Same as above
```

**Comment by jonas-schievink** [comment]
This is basically https://github.com/rust-lang/rfcs/pull/2584

**Comment by NN---** [comment]
Thanks.
Do you know when this proposal is expected to be included in the language ?

**Comment by jonas-schievink** [comment]
After the RFC is accepted (which it might not be), someone needs to implement it. Depending on *how much* people want this feature and *how complex* it is to implement that can either happen before the RFC is even accepted (and would get merged once the RFC is accepted), or take many months.

Once it's implemented and merged to master it will land in the next nightly as an unstable feature. Then, depending on priorities and issues discovered with the feature, it can get stabilized after a few more months or, if you're unlucky, take over a year to get anywhere.

**Comment by NN---** [comment]
Are you sure rust-lang/rfcs#2584 allows to assign two instances with different names ?
I understand that the intent is to have structural compatibility for two structs having the same field names.
My sample differs by assigning two instances with different semantic names.

**Comment by qnighy** [comment]
You could instead do this: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=9d57a68e0f7b994f696e40f131bb0c47

**Comment by NN---** [comment]
Interesting, I didn't know you can make struct and function with the same name.
The only missing part is tuple structural equality, and much simpler syntax :)
