### ISSUE TITLE
Coercion happens after typechecking

### ISSUE THREAD

**Issue by MaikKlein** [rust-lang/rust#58774]
```
struct Foo(u32);
impl std::ops::Deref for Foo {
    type Target = u32;
    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl std::ops::DerefMut for Foo {
    fn deref_mut(&mut self) -> &mut Self::Target {
        &mut self.0
    }
}

trait U32 {}
impl U32 for u32 {}
fn foo<T: U32>(f: &mut T) {}
fn main() {
    let mut i = 42;
    foo(&mut i);
    let mut f = Foo(42);
    foo(&mut f); // <= doesn't compile
}
```
[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=2d5b59f2c2933cd504f8e893b861d078)

`foo(&mut f);` doesn't compile because I assume the compiler just checks if the given type implements `U32`. Should the compiler deref before it type checks?

**Comment by ishitatsuyuki** [comment]
Deref coercion does not apply to `DerefMut`. Could that be the cause?

**Comment by Centril** [comment]
I think this is correct behavior going by the reference at least, but I'm not sure... [Relevant section:](https://doc.rust-lang.org/nightly/reference/type-coercions.html)
> A coercion can only occur at certain coercion sites in a program; these are typically places where the desired type is explicit or can be derived by propagation **from explicit types (without type inference).** 

cc @nikomatsakis

**Comment by MaikKlein** [comment]
I have to say I am not too familiar with the terminology but to me an explicit type is a type that the compiler already knows which `Foo` should satisfy.

An inferred type to me would be `foo(&mut panic!())`, and I wouldn't expect this to work at all.

The rules state `&mut T to &mut U if T implements DerefMut<Target = U>` which I think the code above satisfies?

**Comment by Centril** [comment]
> Deref coercion does not apply to `DerefMut`. Could that be the cause?

No,

```rust
struct Foo { f: () }

impl std::ops::Deref for Foo {
    type Target = ();
    fn deref(&self) -> &() {
        &self.f
    }
}

trait A {}
impl A for () {}
fn foo<T: A>(f: &T) {}

fn main() {
    foo(&());
    foo(&Foo { f: () }); // Errors.
}
```

**Comment by ExpHP** [comment]
> Are generics considered explicit?

I would think explicit means "everything but generics"!  (or rather, "everything but type inference variables")

At the point where the compiler is ready to insert a coercion here, here is what it sees:

```rust
let r: &mut Foo = &mut f;
foo::<_>(r);
```

That `_` becomes a type inference variable.  This unifies with anything, so the compiler refuses to insert any coercions, and then it performs type inference and concludes that the type inference variable is equal to `Foo`.

**Comment by MaikKlein** [comment]
Closing this since it seems to adhere to the 'spec'.
