### ISSUE TITLE
Enable decoding unicode without copying from io::Cursor

### ISSUE THREAD

**Issue by thedrow** [rust-lang/rust#58806]
Currently `std::str::from_utf8()` and `std::String::from_utf8_lossy()` only accept references to byte arrays.
This is fine until one uses an `io::Cursor` which forces us to allocate a buffer and copy data into it using `cursor.read_exact()` or `cursor.read_to_end()`.

I think we should introduce an API that allows me to decode Unicode characters in a stream without unnecessary copying.
I'm not sure how this API would look like though.

**Comment by Mark-Simulacrum** [comment]
[Read::read_to_string](https://doc.rust-lang.org/nightly/std/io/trait.Read.html#method.read_to_string) doesn't guarantee no copies, but in practice the default implementation will decode into the backing allocation of the String and then check the new bytes are UTF-8 (without copying).

I'm going to close this as such for the time being, but if you have a concrete API proposal that's not currently met feel free to file an [API proposal](https://github.com/rust-lang/libs-team/issues/new/choose).
