### ISSUE TITLE
No docs for String on stable?

### ISSUE THREAD

**Issue by matklad** [rust-lang/rust#58827]
Hi! Looks like docs for std string methods are missing on stable release?

https://doc.rust-lang.org/std/string/struct.String.html#method.as_bytes

![37906c37-5439-48fd-b536-8562abd30309](https://user-images.githubusercontent.com/1711539/53617277-8d97af80-3bf7-11e9-8c1c-36474ff792be.jpeg)

THe methods section is empty :( 

Everything works ok for beta.

**Comment by matklad** [comment]
Note that the screenshot was taken from iPad. I know checked using Firefox on linux, and the methods are there.

**Comment by hellow554** [comment]
This is the same for other structs, e.g. [`std::sync::Arc`](https://doc.rust-lang.org/std/sync/struct.Arc.html) (Firefox 64, Windows)

![grafik](https://user-images.githubusercontent.com/921462/53631180-410d9d80-3c12-11e9-8ad2-a8bfaadb6908.png)

@GuillaumeGomez this is (at least for me) very critical! We need a patch for this asap.

**Comment by matklad** [comment]
cc @rust-lang/docs :)

Note that it does work for some people. I wonder if this is some temporary internet caches thing?

**Comment by jonas-schievink** [comment]
Looks like a rustdoc problem more than anything. Did you try clearing your caches? I know I have to do that after pretty much every stable release or stuff breaks for me.

cc @rust-lang/rustdoc

**Comment by GuillaumeGomez** [comment]
I have tested and I can't reproduce it on my linux's chrome and firefox. So I don't know what's going on and I don't have an ipad to test specifically what's wrong on this platform...

**Comment by hellow554** [comment]
It was indeed a caching problem. Sorry for the noise :/ Although it shouldn't happen IMHO.

**Comment by jonas-schievink** [comment]
Yes, it would be nice to find a proper solution for this. I've also opened issues in the past that were just due to a stale browser cache.

**Comment by GuillaumeGomez** [comment]
We could by changing the name of the script files like docs.rs does. Where could I change it @rust-lang/infra ?

**Comment by kennytm** [comment]
Isn't the script path hard-coded in `src/librustdoc/html/layout.rs`?

**Comment by GuillaumeGomez** [comment]
It's generated and can be changed (we have options for that in rustdoc).

**Comment by QuietMisdreavus** [comment]
Could we just start adding a `--resource-suffix` in bootstrap with something that matches the version string (or just the latest commit if necessary)? That would ensure that the filename is different so that the CDN wouldn't serve old files to the wrong version's docs.

**Comment by GuillaumeGomez** [comment]
@QuietMisdreavus I did. Look at #58848. :)
