### ISSUE TITLE
Spurious warnings around uninhabited types with 1.33

### ISSUE THREAD

**Issue by nox** [rust-lang/rust#58844]
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=25adf77e74f612769891852bfeaf237c

Using uninhabited enums for some targets or combinations of crate features are a useful common idiom and this probably shouldn't emit any warning.

**Comment by varkor** [comment]
What problem are you seeing here? That `let var = /* diverging expression */;` marks `var` as an unused variable? Could you give an example where this isn't reasonable behaviour (i.e. can't trivially be refactored to be avoided)?

**Comment by nox** [comment]
What do you mean by trivially? This is a convenient way to represent platform-specific behaviour: have a type an uninhabited enum on some platforms and something useful in others, and then you can write code that abstracts over the two.

This is what the code is in that case:

https://github.com/servo/webrender/blob/89c79c227245e6fb7c447de157058e65b7868189/wrench/src/angle.rs#L10-L73

I also use uninhabited enums extensively in `serde_urlencoded`:

https://github.com/nox/serde_urlencoded/blob/3ae533293191ee8339b92ee51faee1fdd5900002/src/ser/part.rs#L39-L45

Actually `serde` defines the uninhabited type itself:

https://github.com/serde-rs/serde/blob/master/serde/src/ser/impossible.rs



I don't see why an empty enum should trigger the warning, we literally have [an issue](https://github.com/rust-lang/rust/issues/38885) filed against this very repo about not making `#[derive(Debug)]` warn on an empty enum for example, why is this any different?

**Comment by nox** [comment]
[Upstream](https://bugzilla.mozilla.org/show_bug.cgi?id=1531512) is going to prefix both concerned variables in webrender with an `_`, even though those values *are* indeed used on Windows where `Context` isn't an empty enum.

Not knowing about the fact that empty enums can lead to warnings, I would be myself really confused as to why the variables are prefixed, given they totally look used in the code, even if only on some platforms.

This new spurious warning means you basically have to either prefix variables with `_` (confusing), mark every snippet that may use such uninhabited types with `#[allow(…)]` (also confusing, why is the allow there when all the code looks used and there is no apparently unreachable code), or mark every snippet with `#[cfg(…, allow(…))]` (tiresome because I don't remember at all instants on which platforms the thing is uninhabited). Meanwhile, if there is any really unused variable in the code, those legit warnings will be silenced.

**Comment by nikic** [comment]
@nox Inhabitnedness checks are privacy based, so consuming code will only get these warnings if it "knows" that the type is uninhabited. Maybe you can use something like `pub struct Context { privately_uninhabited: ! }` to solve this?

**Comment by nox** [comment]
That is helpful, thanks, I wasn't aware of how visibility affects the inhabitedness check. Closing this issue.
