### ISSUE TITLE
AsRef/AsMut implementations aren't inlined

### ISSUE THREAD

**Issue by WildCryptoFox** [rust-lang/rust#58867]
Many `AsRef` and `AsMut` implementations in core do not have `#[inline]` and yet these tiny no-op functions are called from the assembly.

[The following assembly maps to `AsMut<[T]> for [T]`](https://doc.rust-lang.org/nightly/src/core/convert.rs.html#485-496)

Any quick search for `as_ref` or `as_mut` in `convert.rs` shows many instances, some with but many without `#[inline]`.

```asm
_ZN63_$LT$$RF$mut$u20$T$u20$as$u20$core..convert..AsMut$LT$U$GT$$GT$6as_mut17h47b72d0f8c3b94ffE:
     .cfi_startproc
     movq    (%rdi), %rax
     movq    8(%rdi), %rdx
     retq
```

**Edit**: [`Default::default` is another example where more aggressive inlining should be used](https://doc.rust-lang.org/nightly/src/core/slice/mod.rs.html#2795-2804)

**Comment by jonas-schievink** [comment]
You just need `#[inline]`. The LLVM hint wouldn't even be needed at all - `#[inline]` puts the function into all codegen units that reference it, that's all you typically need for small functions to be inlined.

You almostly *never* want `#[inline(always)]`, since it's even respected in debug mode, where it just needlessly impacts compile times.

**Comment by james-darkfox** [comment]
Thanks @jonas-schievink for the correction.

**Comment by Olavhaasie** [comment]
I would like to do this, If no one else has taken it yet

**Comment by sfackler** [comment]
LLVM should normally be inlining in release builds these unless you're using multiple codegen units without LTO.

**Comment by james-darkfox** [comment]
@sfackler I haven't tweaked the config for codegen units nor LTO. So whatever the default is.

**Comment by sfackler** [comment]
I remembered that we generally don't want to add `#[inline]` on functions that are already eligible for inlining: #52704.

**Comment by james-darkfox** [comment]
Thanks @sfackler.  [This comment suggests using ThinLTO in release builds incremental builds disabled](https://github.com/rust-lang/rust/pull/52704#issuecomment-408536474) but obviously that isn't desired as incremental building is very desirable for rapid testing (especially in my case where I need to read the optimized assembly).

**Comment by sfackler** [comment]
Incremental ThinLTO works now IIRC.

**Comment by james-darkfox** [comment]
Cool. And enabled by default on at least the latest nightly. Should this be closed?

**Comment by lcnr** [comment]
This seems to be fixed.

See https://rust.godbolt.org/z/j9Ts8P

**Comment by Dylan-DPC** [comment]
Closing this as it is covered by #71576
