### ISSUE TITLE
Optimization discrepancy between clang/llvm and rustc/llvm. -O1 vs -Os

### ISSUE THREAD

**Issue by james-darkfox** [rust-lang/rust#58869]
With either O1 or Os clang uses increment. With O1 rustc produces add instructions. With Os rustc produces increment instructions. Is there any reason for this difference? llvm-mca says the instructions perform equally, its just that increment is smaller.

https://godbolt.org/z/VsIcT1

This minor issue might hint that other less minor issues may be present regarding the choices of optimizations.

**Comment by nikic** [comment]
This is due to https://reviews.llvm.org/D58412, which landed upstream very recently and isn't part of LLVM 8 (which Rust currently uses).

**Comment by james-darkfox** [comment]
@nikic Thanks. Just confirmed that llvm7 (two clicks on godbolt) does indeed use add.
