### ISSUE TITLE
Rust incorrectly accepts unbalanced parentheses

### ISSUE THREAD

**Issue by mjbshaw** [rust-lang/rust#58886]
Rust incorrectly accepts the following code (which is missing a `)`):
```rust
pub struct Value {
}

pub fn new() -> Result<Value, ()> {
    Ok(Value {
    } // Look ma, no `)`!
}
```

So far this seems to only happen if the code is inside a submodule. Shell script to reproduce:
```sh
#!/bin/bash

cargo new --lib this_should_not_build
mkdir this_should_not_build/src/foo

cat >> this_should_not_build/src/lib.rs <<-'EOF'
    pub mod foo;
EOF

cat > this_should_not_build/src/foo/mod.rs <<-'EOF'
    pub struct Value {
    }

    pub fn new() -> Result<Value, ()> {
        Ok(Value {
        }
    }
EOF

cd this_should_not_build
cargo build
```

My compiler version: `rustc 1.34.0-nightly (0ea22717a 2019-03-02)`

**Comment by estebank** [comment]
Likely introduced in #57944. I'll take a look at it tomorrow.

**Comment by dekellum** [comment]
Thanks for reporting this and fixing, with tests! This can be a bit disconcerting if you dev on nightly, but target some stable (which will then fail to build):  dekellum/body-image@dc78182b66
