### ISSUE TITLE
async/await: Usage of trait objects reports multiple different lifetimes when only one is used

### ISSUE THREAD

**Issue by Matthias247** [rust-lang/rust#58885]
The following code ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=535ed0ffe0d0736a9739b48431c44bcc)) fails to compile:

```rust
#![feature(futures_api, async_await, await_macro)]

struct Xyz {
    a: u64,
}

trait Foo {}

impl Xyz {
    async fn do_sth<'a>(
        &'a self, foo: &'a dyn Foo
    ) -> bool
    {
        true
    }
}
```

Error:
```
error[E0709]: multiple different lifetimes used in arguments of `async fn`
  --> src/lib.rs:11:10
   |
11 |         &'a self, foo: &'a dyn Foo
   |          ^^                ^^^^^^^ different lifetime here
   |          |
   |          first lifetime here
   |
   = help: `async fn` can only accept borrowed values with identical lifetimes
```

This is very surprising, since only one lifetime is visible.

Workaround (thanks to @Nemo157 ):

Defining the function as
```
async fn do_sth<'a>(&'a self, foo: &'a (dyn Foo + 'a)) -> bool
```

will allow compilation.

**Comment by nikomatsakis** [comment]
Tagging as **blocking** -- this issue ought to be resolved before async-await can be stabilized, because it is generally surprising and kind of a bug. However, we expect it to get fixed by fixing https://github.com/rust-lang/rust/issues/56238 (see that issue for notes as to why).
