### ISSUE TITLE
String concatenation

### ISSUE THREAD

**Issue by NN---** [rust-lang/rust#58889]
Why Rust implements implement trait add only for:
- [x] String + &str
- [x] String + &String

While it doesn't implement trait add for:
- [ ] &String + &str
- [ ] &str + String
- [ ] String + String
- [ ] &String + &String

**Comment by steveklabnik** [comment]
Please ask questions on users.rust-lang.org. We try to keep the bug tracker for bugs only. Thanks!

**Comment by NN---** [comment]
Ok.
I can make a PR making these operators available and making sure everything compiles as expected.
Will this PR be accepted ?
