### ISSUE TITLE
multiple applicable items in scope - type_id

### ISSUE THREAD

**Issue by Dylan-DPC** [rust-lang/rust#58922]
From a crater run:

```
[INFO] [stderr]    Compiling downcast v0.9.2 (/opt/crater/workdir)
[INFO] [stderr] error[E0034]: multiple applicable items in scope
[INFO] [stderr]    --> src/lib.rs:120:38
[INFO] [stderr]     |
[INFO] [stderr] 120 |     fn is_type(&self) -> bool { self.type_id() == TypeId::of::<T>() }
[INFO] [stderr]     |                                      ^^^^^^^ multiple `type_id` found
[INFO] [stderr]     |
[INFO] [stderr] note: candidate #1 is defined in the trait `Any`
[INFO] [stderr]    --> src/lib.rs:29:5
[INFO] [stderr]     |
[INFO] [stderr] 29  |     fn type_id(&self) -> TypeId { TypeId::of::<Self>() }
[INFO] [stderr]     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[INFO] [stderr]     = help: to disambiguate the method call, write `Any::type_id(&self)` instead
[INFO] [stderr] note: candidate #2 is defined in the trait `std::any::Any`
[INFO] [stderr]     = help: to disambiguate the method call, write `std::any::Any::type_id(&self)` instead
[INFO] [stderr] 
[INFO] [stderr] error: aborting due to previous error
[INFO] [stderr] 
[INFO] [stderr] For more information about this error, try `rustc --explain E0034`.
[INFO] [stderr] error: Could not compile `downcast`.
```

Found this error in the following crates: 
[Downcast](https://crates.io/crates/downcast/0.9.2): [crater log](https://crater-reports.s3.amazonaws.com/beta-1.34-1/beta-2019-02-27/reg/downcast-0.9.2/log.txt) 

[Findr](https://crater-reports.s3.amazonaws.com/beta-1.34-1/beta-2019-02-27/reg/findr-0.1.5/log.txt): [crater log](https://crater-reports.s3.amazonaws.com/beta-1.34-1/beta-2019-02-27/reg/findr-0.1.5/log.txt)

[ncollide](https://crates.io/crates/ncollide/0.14.1) - [crater log](https://crater-reports.s3.amazonaws.com/beta-1.34-1/beta-2019-02-27/reg/ncollide-0.14.1/log.txt)

[ncollide-geometry](https://crates.io/crates/ncollide_geometry/0.6.3) - [crater log](https://crater-reports.s3.amazonaws.com/beta-1.34-1/beta-2019-02-27/reg/ncollide_geometry-0.6.3/log.txt) 

cc crate authors: @stevedonovan @elrnv @sebcrozet

**Comment by estebank** [comment]
This is fallout from the recent change from [`get_type_id` to `type_id`](https://github.com/rust-lang/rust/pull/57834).

**Comment by sebcrozet** [comment]
We already fixed this on ncollide. The fix required a breaking change so it was released as ncollide 0.18.
And the ncollide-geometry crate is no longer maintained.

**Comment by pietroalbini** [comment]
cc @rust-lang/libs

**Comment by SimonSapin** [comment]
This sounds like business as usual when adding / stabilizing new methods on existing standard library types, and upstream already has a work-around. So I’m inclined to close this with no change.

**Comment by khimaros** [comment]
FYI, this appears to have transitively broken the `sqlite` crate. Is there a workaround?
