### ISSUE TITLE
ICE with `#![feature(existential_type)]` + closure

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#58951]
Encountered this when working on test cases for an RFC:
```rust
#![feature(existential_type)]

existential type A: Iterator;
fn def_a() -> A { 0..1 }
pub fn use_a() {
    def_a().map(|x| x);
}
```
cc @oli-obk

This seems related to other issues.

**Comment by oli-obk** [comment]
I'm confused. Either this was fixed since yesterday's nightly (it still ICEs on nightly but works locally on master), or something really odd is going on

**Comment by Centril** [comment]
@oli-obk  Is that the upstream master? Otherwise maybe someone merged a PR or something..

**Comment by Centril** [comment]
This still ICEs on nightly.

**Comment by Aaron1011** [comment]
This now compiles successfully on the latest nightly.
