### ISSUE TITLE
Compiling libcore with -Zlower-128bit-ops broken

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rust#58969]
```
error: requires `u128_shro` lang_item
```

The u128 lang items are only defined in `compiler_builtins`.

**Comment by scottmcm** [comment]
This feature never got finished; there are all sorts of problems.  Empirically (the types got stabilized) the expectation is that the LLVM backends should just add support; that it's not Rust's problem.

**Comment by bjorn3** [comment]
I understand.
