### ISSUE TITLE
Cross compiling liballoc using cargo-xbuild is broken on nightly

### ISSUE THREAD

**Issue by digitalstreamio** [rust-lang/rust#58979]
This used to work fine on nightly up until nightly-2019-01-18-x86_64-unknown-linux-gnu or so. More recent versions are producing compiler errors.

Repro steps:

> git clone https://github.com/digitalstreamio/zinc64
> cd zinc64
> make kernel

this will in turn execute 

> cargo xbuild -p zinc64-rpi --target=aarch64-unknown-none --release

Compiler output/errors:

```
cargo xbuild -p zinc64-rpi --target=aarch64-unknown-none --release
    Updating crates.io index
   Compiling core v0.0.0 (/home/raytracer/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libcore)
   Compiling compiler_builtins v0.1.7
   Compiling rustc-std-workspace-core v1.0.0 (/home/raytracer/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/tools/rustc-std-workspace-core)
   Compiling alloc v0.0.0 (/tmp/xargo.fnWzThd4nUTS)
error[E0432]: unresolved import `SearchResult`
 --> /home/raytracer/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/liballoc/collections/btree/search.rs:6:5
  |
6 | use SearchResult::*;
  |     ^^^^^^^^^^^^ did you mean `self::SearchResult`?

error[E0432]: unresolved import `UnderflowResult`
  --> /home/raytracer/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/liballoc/collections/btree/map.rs:14:5
   |
14 | use UnderflowResult::*;
   |     ^^^^^^^^^^^^^^^ did you mean `self::UnderflowResult`?

.....

error: aborting due to 69 previous errors

Some errors occurred: E0425, E0432, E0531.
For more information about an error, try `rustc --explain E0425`.
error: Could not compile `alloc`.
```

**Comment by digitalstreamio** [comment]
It seems the following commit is causing problems 

"liballoc: apply uniform_paths."
Feb 2
commit 748970dfa9c12c1a09da4ff3ec724e4dbf7e796d

https://github.com/rust-lang/rust/commit/748970dfa9c12c1a09da4ff3ec724e4dbf7e796d#diff-02bad9328a699a220dca897c0457c1dc

**Comment by steveklabnik** [comment]
My understanding is that xargo is abandoned. Try `cargo-xbuild`?

**Comment by digitalstreamio** [comment]
I am using cargo xbuild, but it seems to internally call or reference xargo.  This is the command line that gets executed:

cargo xbuild -p zinc64-rpi --target=aarch64-unknown-none --release

**Comment by digitalstreamio** [comment]
It seems updating cargo-xbuild from 0.5.3 to 0.5.5 fixes the issue. Sorry for the confusion.
