### ISSUE TITLE
Segfault when using C compatible variadic functions

### ISSUE THREAD

**Issue by thedataking** [rust-lang/rust#58980]
This example prints `test 1 2 3` when compiled and run in debug mode:

```rust
#![feature(c_variadic)]

extern "C" {
    #[no_mangle]
    fn vprintf(_: *const libc::c_char, _: ...) -> libc::c_int;
}

#[no_mangle]
unsafe extern "C" fn variadic(fmt: *const libc::c_char, a: ...)
 -> libc::c_int {
    vprintf(fmt, a)
}

fn main() {
    let fmt = std::ffi::CString::new("test %d %d %d\n").expect("new failed");
    unsafe {
        variadic(fmt.as_ptr(), 1, 2, 3);
    }
}
```

Compiling and running in release mode causes a segfault in [`glibc/stdio-common/vfprintf.c:1286`](https://code.woboq.org/userspace/glibc/stdio-common/vfprintf.c.html#1296) because `ap`  is nul. Enabling debug info in release mode via `Cargo.toml` makes the segfault go away.

## Meta

```
$ rustc --version --verbose
rustc 1.35.0-nightly (f22dca0a1 2019-03-05)
binary: rustc
commit-hash: f22dca0a1bef4141e75326caacc3cd59f3d5be8e
commit-date: 2019-03-05
host: x86_64-unknown-linux-gnu
release: 1.35.0-nightly
LLVM version: 8.0
```

**Comment by dlrobertson** [comment]
@thedataking thanks for reporting this. The example should probably look more like the following. The example still segfaults (even in debug mode).

```rust
#![feature(c_variadic)]
use std::ffi::VaList;

extern "C" {
    // vprintf signature is `int vprintf(const char * format, va_list arg)`
    #[no_mangle]
    fn vprintf(_: *const libc::c_char, _: VaList) -> libc::c_int;
}

#[no_mangle]
unsafe extern "C" fn variadic(fmt: *const libc::c_char, a: ...) -> libc::c_int {
    // `va_start` in theory should be automatically called giving you a
    // `VaList` at `a` here.
    vprintf(fmt, a)
    // `va_end` should be called here.
}

fn main() {
    let fmt = std::ffi::CString::new("test %d %d %d\n").expect("new failed");
    unsafe {
        variadic(fmt.as_ptr(), 1, 2, 3);
    }
}
```

If `a` is used in the function `variadic` the issue does not happen. Essentially we're optimizing `variadic` to the following

```
define i32 @variadic(i8* %fmt, ...) unnamed_addr #3 personality i32 (i32, i32, i64, %"unwind::libunwind::_Unwind_Exception"*, %"unwind::libunwind::_Unwind_Context"*)* @rust_eh_personality {
start:
  %personalityslot = alloca { i8*, i32 }, align 8
  %0 = invoke i32 @vprintf(i8* %fmt, i64* align 8 dereferenceable(24) undef)
          to label %bb2 unwind label %cleanup
  ...
```

Note the missing `va_start` and `va_end`. I think this is happening because we're hitting [src/librustc_codegen_ssa/mir/mod.rs:536-540](https://github.com/rust-lang/rust/blob/master/src/librustc_codegen_ssa/mir/mod.rs#L536-L540). I'll do some more investigation shortly.

**Comment by dlrobertson** [comment]
@thedataking the code I list in the above example should work with after https://github.com/rust-lang/rust/pull/58985 is merged.
