### ISSUE TITLE
Mismatched types diagnostic sometimes points at both return type and return statement for the expectation reason

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#58982]
[The output for](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=ace0042d07550c5b32e79be3cd9f0524) the following code is slightly incorrect and shouldn't really point at the value of the `return` statement:

```
fn foo(bar: usize) -> usize {
    if bar % 5 == 0 {
        return 1;
    };
}

fn main() {
    println!("Hello, {}!", foo(1))
}
```

```
error[E0308]: mismatched types
 --> src/main.rs:1:23
  |
1 | fn foo(bar: usize) -> usize {
  |    ---                ^^^^^ expected usize, found ()
  |    |
  |    this function's body doesn't return
2 |     if bar % 5 == 0 {
3 |         return 1;
  |                - expected because of this statement
  |
  = note: expected type `usize`
             found type `()`
```

**Comment by pmccarter** [comment]
I can look into this.

**Comment by pmccarter** [comment]
Hey @estebank so my understanding is that the previous return site should be highlighted only for impl Trait valued functions. Somehow this needs to be detected in some generic coercion functionality for the span to be emitted with that error. Any thoughts on that? Is this only applicable to stable branch for some reason?

**Comment by estebank** [comment]
The current output no longer points incorrectly at the `return` statement:

```
error[E0308]: mismatched types
 --> src/main.rs:1:23
  |
1 | fn foo(bar: usize) -> usize {
  |    ---                ^^^^^ expected usize, found ()
  |    |
  |    this function's body doesn't return
  |
  = note: expected type `usize`
             found type `()`
```
