### ISSUE TITLE
LLVM asserts "Cannot get the value bit index of a constant bit" on powerpc64le

### ISSUE THREAD

**Issue by cuviper** [rust-lang/rust#58996]
@ajdlinux found this assertion failure building `dist-powerpc64le-linux` in #58991:

```text
   Compiling syntax_ext v0.0.0 (/checkout/src/libsyntax_ext)
[RUSTC-TIMING] syntax_ext test:false 59.344
rustc: /checkout/src/llvm-project/llvm/lib/Target/PowerPC/PPCISelDAGToDAG.cpp:1114: unsigned int {anonymous}::BitPermutationSelector::ValueBit::getValueBitIndex() const: Assertion `hasValue() && "Cannot get the value bit index of a constant bit"' failed.
[RUSTC-TIMING] rustc test:false 731.190
rustc exited with signal: 6
error: Could not compile `rustc`.
```

Reproducing this depends on having LLVM assertions enabled, which we don't normally have on CI for `DEPLOY=1` builds.

I was also able to reproduce this with big-endian `dist-powerpc64-linux`.

**Comment by cuviper** [comment]
I bisected this in LLVM and filed a bug: https://bugs.llvm.org/show_bug.cgi?id=41088

**Comment by ajdlinux** [comment]
Thanks!

**Comment by cuviper** [comment]
This is fixed by [D72038](https://reviews.llvm.org/D72038), which will release in LLVM 10 (see also #67759). I suppose we could backport this to the current LLVM 9 build, as it applies cleanly, but I'm not sure how much we need this. It doesn't seem to cause problems in non-asserting builds, at least.

**Comment by cuviper** [comment]
We have since updated to LLVM 10.
