### ISSUE TITLE
empty crates depend on libcore

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/rust#58997]
This crate:

```rust
#![crate_type = "rlib"]
#![no_std]
```

implicitly contains an `extern crate core` even though it does not use anything from it (not even lang-items).

**Comment by jonas-schievink** [comment]
Not sure this is a bug - libcore is opt-out just like libstd is, you need `#![no_core]`

**Comment by steveklabnik** [comment]
Yes, this is expected behavior; see https://doc.rust-lang.org/stable/reference/crates-and-source-files.html#preludes-and-no_std

**Comment by gnzlbg** [comment]
Can't do that in stable Rust =/

**Comment by steveklabnik** [comment]
That's tracked by https://github.com/rust-lang/rust/issues/29639

**Comment by gnzlbg** [comment]
The discussion on Discord suggested that this attribute was intended to be perma-unstable.
