### ISSUE TITLE
async: hidden type for `impl Trait` captures lifetime that does not appear in bounds

### ISSUE THREAD

**Issue by jethrogb** [rust-lang/rust#59001]
```rust
#![feature(async_await, futures_api, await_macro)]

use std::future::Future;

async fn enter<'a, F, R>(mut callback: F)
where
    F: FnMut(&'a mut i32) -> R,
    R: Future<Output = ()> + 'a
{
    unimplemented!()
}
```

```
error[E0700]: hidden type for `impl Trait` captures lifetime that does not appear in bounds
 --> src/lib.rs:6:1
  |
6 | where
  | ^
  |
note: hidden type `impl std::future::Future` captures the lifetime 'a as defined on the function body at 5:16
 --> src/lib.rs:5:16
  |
5 | async fn enter<'a, F, R>(mut callback: F)
  |                ^^
```

I think this is a bug? The RFC says

> All of the input lifetimes to this function are captured in the future returned by the async function

so I'd expect the function to return `impl Future<...> + 'a`.

**Comment by csmoe** [comment]
lifetime `'a` is not needed here cc https://github.com/rust-lang/rfcs/blob/master/text/2394-async_await.md#lifetime-capture-in-the-anonymous-future

**Comment by jethrogb** [comment]
@csmoe what do you mean "not needed"? You changed the signature of the function.

**Comment by Matthias247** [comment]
@jethrogb This compiles for me on on [playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=5c5ddf89512760bcfe13b9a70af3e190).

**Comment by jethrogb** [comment]
@Matthias247 that's strange. The playground appears broken currently, but when I compile that locally with the latest nightly I still get the original error.

**Comment by csmoe** [comment]
cc @cramertj

**Comment by cramertj** [comment]
Yes, this is a bug I'm currently working on fixing.

**Comment by nikomatsakis** [comment]
Marking this as **blocking** as it is part of the lifetime refactoring work that @cramertj has already started doing and should be addressed by that (as discussed [here](https://rust-lang.zulipchat.com/#narrow/stream/187312-t-compiler.2Fwg-async-await/topic/meeting.202019.2E03.2E12/near/160589879)).
