### ISSUE TITLE
Add "nightly" and "beta" cfg options.

### ISSUE THREAD

**Issue by lachlansneff** [rust-lang/rust#59028]
We should be able to use `cfg(nightly)` and `cfg(beta)` instead of having to use features.

For example of why this is necessary:
The new ffi-unwinding behavior on nightly will crash when you unwind through an ffi-barrier. You can fix this by adding the `#[unwind(allowed)]` attribute, but this requires a nightly compiler. If we add a "nightly" cargo feature, it cannot be enabled by default if we want to support stable, so when the user is compiling on a nightly compiler, they must enable the "nightly" feature or the code will crash in a non-clear way.

**Comment by lachlansneff** [comment]
As a stand-in, you can add the following code to your `build.rs`:

```rust
// Enable "nightly" cfg if the current compiler is nightly.
if rustc_version::version_meta().unwrap().channel == rustc_version::Channel::Nightly {
    println!("cargo:rustc-cfg=nightly");
}
```

**Comment by Mark-Simulacrum** [comment]
I think this will need an RFC if we're to add it (seems potentially thorny) so I'm going to close this. If you'd be interested in filing one, see some docs here: https://github.com/rust-lang/rfcs/#when-you-need-to-follow-this-process
