### ISSUE TITLE
ICE with trait alias when alias refers to bare Self

### ISSUE THREAD

**Issue by seanmonstar** [rust-lang/rust#59029]
```rust
trait Svc<Req> {
    type Res;
}

// ICEs:
trait MkSvc<Target, Req> = Svc<Target> where Self::Res: Svc<Req>;

// works:
// trait MkSvc<Target, Req> = Svc<Target> where <Self as Svc<Target>>::Res: Svc<Req>;
```

Related playground: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=e29c998d2dc1d0c0ef60f4f3bd5ae934

The compiler outputs:

```
error: internal compiler error: src/librustc/hir/map/mod.rs:546: ty_param_owner: trait alias MkSvc (id=17) not a type parameter

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:620:9
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
error: aborting due to previous error

note: the compiler unexpectedly panicked. this is a bug.

note: rustc 1.35.0-nightly (88f755f8a 2019-03-07) running on x86_64-unknown-linux-gnu
```

cc https://github.com/rust-lang/rust/issues/41517

**Comment by alexreg** [comment]
Thanks for the report. I don't *think* the fix for this is too difficult judging by your example. Unfortunately, I'm very busy right now. You've contributed to rustc before, if I'm not mistaken... would you be interested in taking up this fix if I mentored/reviewed?

**Comment by seanmonstar** [comment]
@alexreg I'd be happy to help. I spent a couple hours last night trying to figure out how to work on the related "import methods" issue, and was completely at a loss of how to find it.

**Comment by alexreg** [comment]
@seanmonstar Super! I'd like to tackle method importing for both trait aliases and maybe type aliases too, but due to my lack of experience in that area, I'll probably need to chat it over with someone first. (@rust-lang/compiler, any ideas who would be good for this?)

This issue should be no problem though. Would you like me to post some general suggestions/pointers here, or chat about it? I'm on Discord/Zulip if you prefer the latter.

**Comment by seanmonstar** [comment]
@alexreg If you wouldn't mind leaving pointers here, it'll be easier to find later (like Monday). Or maybe someone can beat me to it. I got to this line from the panic message at least: https://github.com/rust-lang/rust/blob/b2ea6c86ae8b9f8845aaff5a1453e4f5ceb53d59/src/librustc/hir/map/mod.rs#L546

**Comment by alexreg** [comment]
@seanmonstar Unfortunately I didn't get a chance to have a proper look at this on the weekend, but I've just looked quickly, and I'm *hoping* the fix may be as easy as matching `ItemKind::TraitAlias` as well as `ItemKind::Trait` on https://github.com/rust-lang/rust/blob/b2ea6c86ae8b9f8845aaff5a1453e4f5ceb53d59/src/librustc/hir/map/mod.rs#L544

Let me know what this yields.

**Comment by alexreg** [comment]
@Centril Did you nominate this because of my questions about importing or what?

**Comment by Centril** [comment]
@alexreg I-ICEs are generally nominated for triage I think.

**Comment by alexreg** [comment]
Okay.

**Comment by pnkfelix** [comment]
triage: looks like a P-high ICE.

**Comment by pnkfelix** [comment]
triage: assigning to @seanmonstar
