### ISSUE TITLE
Rust's libLLVM-8.so doesn't work with clang

### ISSUE THREAD

**Issue by emilio** [rust-lang/rust#59034]
Which means that programs that run `clang` from a build script, or from cargo in some other way, fail.

Steps to Reproduce:
0. Have a clang binary pointing to clang-8 installed and in your path.
1. rustup install nightly
2. git clone https://github.com/rust-lang/rust-bindgen && cd $_
3. cargo test

Actual results: /usr/bin/clang: relocation error: /lib64/libclangBasic.so.8: symbol _ZTIN4llvm14FoldingSetBaseE version LLVM_8 not defined in file libLLVM-8.so with link time reference

Expected results: not so

This only happens if ran from cargo, if I run the test executable manually then stuff works, so I suspect this is some LD_LIBRARY_PATH mungling that cargo or rustup do under the hood.

This is technically a regression from https://github.com/rust-lang/rust/pull/58408, same problem does not exist with rust stable / beta and clang 7.

There's a slight chance that there's an issue on how clang-8 is built in Fedora, so I also filed https://bugzilla.redhat.com/show_bug.cgi?id=1687047, but I think it's unexpected that clang when called from cargo / build scripts uses rust's libLLVM.so, and probably should be avoided.

cc @alexcrichton

**Comment by nagisa** [comment]
Is `clang` invoked from a build script? It is possible that cargo neglects removing the unnecessary `LD_LIBRARY_PATH` or similar environment variables before invoking the script in question.

**Comment by nagisa** [comment]
cc https://github.com/rust-lang/cargo/issues/2888

**Comment by cuviper** [comment]
See also #55737.

We should probably set a custom suffix per #53987. Maybe even include the Rust version to help avoid bootstrap issues like what commit 2d21df8a3fd7 saw. (cc @Mark-Simulacrum)

**Comment by Mark-Simulacrum** [comment]
Yep, I think a suffix of rust version (or maybe LLVM submodule commit?) would be good.

I think we'd appreciate a PR for something like that; I would expect it to be a matter of making the version suffix default be `-rust-1.33.0-<sha>` or something along those lines.

**Comment by emilio** [comment]
Sure, that sounds good, I can give that a shot.

**Comment by emilio** [comment]
I sent https://github.com/rust-lang/rust/pull/59173 with a change that I _hope_ will address this, but see there why I cannot confirm it will :)

**Comment by pnkfelix** [comment]
triage: P-high, assigning to @emilio
