### ISSUE TITLE
Struct field initialization code order matters

### ISSUE THREAD

**Issue by kaikalii** [rust-lang/rust#59030]
Consider this struct:
```rust
struct Foo {
    s: String,
    metric: u64,
}
```
In order to determine the metric, I might have some function:
```rust
fn s_metric(s: &str) -> u64 {
    // Probably something less trivial than this
    s.len() as u64
}
```
If I want to initialize a `Foo`, writing the initialization for each field in the same order as the definition will not work:
```rust
fn main() {
    let s = String::new();
    let foo = Foo {
        s,
        metric: s_metric(&s),
    };
}
```
This gives the error:
```
error[E0382]: borrow of moved value: `s`
  --> src\main.rs:14:26
   |
13 |         s,
   |         - value moved here
14 |         metric: s_metric(&s),
   |                          ^^ value borrowed here after move
   |
   = note: move occurs because `s` has type `std::string::String`, which does not implement the `Copy` trait
```
Reordering the field initializers fixes this error:
```rust
fn main() {
    let s = String::new();
    let foo = Foo {
        metric: s_metric(&s),
        s,
    };
}
```
I know that this is a very small thing, but should which order you write the field initializers really matter? It seems like figuring this out should be part of NLL or something similar. 

I have considered that that are cases where letting the compiler figure this order out for you without changing the semantics of the code might be very compicated if not impossible. Is this the case?

**Comment by jonas-schievink** [comment]
Struct initialization always executes from top to bottom right now, and changes to it are generally RFC territory. In your specific case automatically detecting that it wouldn't change semantics would also be impossible since `s_metric` might modify `s` through interior mutability.

Closing in favor of an RFC
