### ISSUE TITLE
Confusing error message when returning a closure that contains a borrowed parameter

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/rust#59074]
```rust
fn wrap_vec_in_closure<'a, T>(xs: &'a Vec<T>) -> (impl Fn() -> &'a Vec<T>)
where
    T: Clone,
{
    || xs
}
```

[Playpen](https://play.rust-lang.org/?version=beta&mode=debug&edition=2018&gist=bddf698ebbb0ad211075c3d3bd3e418a)

Error:

```
error[E0373]: closure may outlive the current function, but it borrows `xs`, which is owned by the current function
 --> src/lib.rs:5:5
  |
5 |     || xs
  |     ^^ -- `xs` is borrowed here
  |     |
  |     may outlive borrowed value `xs`
  |
```

-----------

> closure may outlive the current function, but it borrows `xs`, which is owned by the current function

Is it correct to say `xs` is owned by the current function? i.e. is it correct to think of `xs` as an 'owned' borrow? Is there better wording we can use here?

**Comment by pnkfelix** [comment]
The diagnostic here does seem a bit frustrating.

----

I'll include my long-winded explanation here, if only to provide foundations for figuring out better messaging.

 * The occurrence of the identifier `xs` within the closure is going to be treated implicitly as a *borrow* of the first (and only) formal parameter to `wrap_vec_in_closure`. (That formal parameter is named `xs`.)
 * The formal parameter itself **is** indeed owned by the current function. I.e. it is a piece of state (namely a pointer to a `Vec<T>`) that will only hang around on the stack frame for as long as this function is being invoked.
 * The data that formal parameter points to (the `Vec<T>`) is *not* owned by the current function; but the occurrence of `xs` within the closure is not directly pointing to the `Vec<T>`; it is pointing to the formal parameter which then points to the `Vec<T>`.

----

So where does this leave us? We could attempt to distinguish between borrowing the variable `xs` versus borrowing the data that `xs` points to.

We could also try to a better job, in the diagnostic itself, of recognizing the case when the thing that is being borrowed is itself of type `&_`, and we might be able to provide a more tailored/nuanced explanation in such cases.

**Comment by estebank** [comment]
Current outout

```
error[E0597]: `xs` does not live long enough
 --> src/lib.rs:5:8
  |
1 | fn wrap_vec_in_closure<'a, T>(xs: &'a Vec<T>) -> (impl Fn() -> &'a Vec<T>)
  |                        --                         ----------------------- opaque type requires that `xs` is borrowed for `'a`
  |                        |
  |                        lifetime `'a` defined here
...
5 |     || xs
  |     -- ^^ borrowed value does not live long enough
  |     |
  |     value captured here
6 | }
  |  - `xs` dropped here while still borrowed
```

**Comment by estebank** [comment]
We now suggest adding `'a` as a bound to the return type:

```
error[E0597]: `xs` does not live long enough
 --> src/lib.rs:5:8
  |
1 | fn wrap_vec_in_closure<'a, T>(xs: &'a Vec<T>) -> (impl Fn() -> &'a Vec<T>)
  |                        --                         ----------------------- opaque type requires that `xs` is borrowed for `'a`
  |                        |
  |                        lifetime `'a` defined here
...
5 |     || xs
  |     -- ^^ borrowed value does not live long enough
  |     |
  |     value captured here
6 | }
  |  - `xs` dropped here while still borrowed
  |
help: you can add a bound to the opaque type to make it last less than `'static` and match `'a`
  |
1 | fn wrap_vec_in_closure<'a, T>(xs: &'a Vec<T>) -> (impl Fn() -> &'a Vec<T> + 'a)
  |                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

after doing that, you get a suggestion to use `move`, which fixes the problem:

```
error[E0373]: closure may outlive the current function, but it borrows `xs`, which is owned by the current function
 --> src/lib.rs:5:5
  |
5 |     || xs
  |     ^^ -- `xs` is borrowed here
  |     |
  |     may outlive borrowed value `xs`
  |
note: closure is returned here
 --> src/lib.rs:5:5
  |
5 |     || xs
  |     ^^^^^
help: to force the closure to take ownership of `xs` (and any other referenced variables), use the `move` keyword
  |
5 |     move || xs
  |     ^^^^^^^
```

I feel like this is enough to close this ticket, but feel free to ping me if consider that we still need to improve the closure borrow capture errors.
