### ISSUE TITLE
Possible to access borrow checker data (ideally in proc_macro)?

### ISSUE THREAD

**Issue by nhynes** [rust-lang/rust#59086]
Is there any way to get the dataflow graph from the borrow checker as a lightweight substitute for symbolic execution? Ideally, this would be possible from a proc_macro but this would require using the borrow checker as a standalone library.

I see Polonius but it doesn't look like it's usable as a library.

**Comment by jonas-schievink** [comment]
We try to keep this issue tracker for bugs only, so questions like this are better asked on the forum at https://users.rust-lang.org/ or some other place.

**Comment by nhynes** [comment]
Maybe someone should add an issue template that makes note of that. Thanks for manually pointing it out, though.
