### ISSUE TITLE
Spurious private-in-public error for impl block

### ISSUE THREAD

**Issue by joshlf** [rust-lang/rust#59090]
The following code [results in a private-in-public error](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=2b1919ea9dab750907c6e55437594543):

```rust
pub(crate) trait Foo {}

pub struct Bar<T>(T);

impl<T: Foo> Bar<T> {
    pub(crate) fn new(t: T) -> Bar<T> {
        Bar(t)
    }
}
```

```text
error[E0445]: crate-visible trait `Foo` in public interface
 --> src/lib.rs:5:1
  |
1 |   pub(crate) trait Foo {}
  |   ---------- `Foo` declared as crate-visible
...
5 | / impl<T: Foo> Bar<T> {
6 | |     pub(crate) fn new(t: T) -> Bar<T> {
7 | |         Bar(t)
8 | |     }
9 | | }
  | |_^ can't leak crate-visible trait
```

This seems wrong to me; though the impl block is on a public type, none of the methods in it are public.

**Comment by petrochenkov** [comment]
This currently works as expected, but https://github.com/rust-lang/rust/issues/48054 is going to change the rules once implemented, so the error will no longer be reported.

**Comment by joshlf** [comment]
OK, sounds good, thanks!
