### ISSUE TITLE
Add convenience wrappers for `type_dependent_defs`

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#59094]
Most uses of that method mostly directly unwrap or just want to know the `DefId`. So we could use several kind of convenience wrappers:

* [ ] `fn opt_type_dependent_def(&self, id: HirId) -> Option<Def>`
* [ ] `fn type_dependent_def(&self, id: HirId) -> Def`
* [ ] `fn type_dependent_def_id(&self, id: HirId) -> DefId`

**Comment by stepnivlk** [comment]
hey @oli-obk, happy to take this one if its still available

**Comment by oli-obk** [comment]
Wow that was fast! Yes of course! If you have any questions, don't hesitate to ask here or on discord/zulip.

**Comment by stepnivlk** [comment]
@oli-obk Hi again :).
So I started implementing proposed methods and updating calls to them over the codebase and I noticed one `def_id` extracting pattern when there's something like this:
```rust
if let Some(def) = self.tables.type_dependent_defs().get(expr.hir_id) {
  let def_id = def.def_id();
  // do something with `def_id`
} else {
  // do something else
}
```
It seems to me like we can introduce fourth method:
`fn opt_type_dependent_def_id(&self, id: HirId) -> Option<DefId>`

Allowing us to rewrite previous example as:
```rust
if let Some(def_id) = self.tables.opt_type_dependent_def_id(expr.hir_id) {
  // do something with `def_id`
} else {
  // do something else
}
```
Leading to little bit cleaner code. Let me know what you think.

**Comment by oli-obk** [comment]
Good idea!

**Comment by wesleywiser** [comment]
This can be closed now right?
