### ISSUE TITLE
Build fails in llvm with  error: ‘IntRinsic’ has not been declared

### ISSUE THREAD

**Issue by snsmac** [rust-lang/rust#59099]
Build command:
./x.py build

Failure: 

> [ 53%] Building CXX object lib/Transforms/InstCombine/CMakeFiles/LLVMInstCombine.dir/InstCombineAndOrXor.cpp.o
In file included from /home/jr/src/rust/src/llvm-project/llvm/lib/IR/Function.cpp:1030:
/home/jr/src/rust/build/x86_64-unknown-linux-gnu/llvm/build/include/llvm/IR/IntrinsicImpl.inc: In function ‘llvm::Intrinsic::ID llvm::Intrinsic::getIntrinsicForGCCBuiltin(const char*, llvm::StringRef)’:
/home/jr/src/rust/build/x86_64-unknown-linux-gnu/llvm/build/include/llvm/IR/IntrinsicImpl.inc:29637:8: error: ‘IntRinsic’ has not been declared
       {IntRinsic::x86_avx512_scatterdiv4_sf, 118888}, // __builtin_ia32_scatterdiv4sf
        ^~~~~~~~~
make[2]: *** [lib/IR/CMakeFiles/LLVMCore.dir/build.make:310: lib/IR/CMakeFiles/LLVMCore.dir/Function.cpp.o] Error 1

OS: Ubuntu 18.10
c++ --version: c++ (Ubuntu 8.2.0-7ubuntu1) 8.2.0

config.toml : https://pastebin.com/5apWAFA9

**Comment by jonas-schievink** [comment]
Does it work with a lowercase `r`? :smile:

**Comment by snsmac** [comment]
Yeah, i did a clean rebuild and now it works, i have no clue where the uppercase R comes from
