### ISSUE TITLE
"extern type" should use `opaque` type in LLVM

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#59095]
Currently, in a situation like
```rust
extern {
    type Foo;
    static mut BAR: Foo;
}
```
we generate a zero-sized struct as the LLVM type for `Foo`. LLVM might use this  to assume that `BAR` has size 0, which would be fatal. And anyway it seems prudent for extern types, that should match C's declared-but-not-defined types, to match what Clang does for the corresponding C types -- which is to use `opaque`.

See https://github.com/rust-lang/rust/pull/58271 for an attempt to fix this, which ran into LLVM assertion failures.

Cc @eddyb

**Comment by eddyb** [comment]
Maybe `opaque` is different than what I was doing, which was to leave the body of the LLVM struct type unfilled? cc @nagisa

**Comment by rkruppe** [comment]
If you use those words precisely in the sense LLVM documentation does, then that should do the trick. The easiest way to be sure would be to look at `--emit llvm-ir` output and see whether it says `opaque` or `{}`.

**Comment by nagisa** [comment]
From the assertion it appears that something somewhere is doing a GEP(i) on a pointer to an [opaque type](https://llvm.org/docs/LangRef.html#opaque-structure-types) (a different thing from a `{}`). Since the size of an opaque element is not known, obviously GEP(i) cannot work. `{}` will have a size and `GEP(i)s` will work, although will not necessarily produce an expected result.

**Comment by eddyb** [comment]
I suspect it's caused by compiling code working with this:
https://github.com/rust-lang/rust/blob/aa97448caf49ee25271a5ad58482283404b9144f/src/librustc/ty/mod.rs#L591-L607

However, that would just be just "tail-opaque" and its *overall size* shouldn't matter.

**Comment by NeoRaider** [comment]
As @eddyb suspected, the `List<T>` code is what triggers the issue in the rustc build. I've reduced the code to the following minimal reproducers:

```rust
#![feature(extern_types)]
#![allow(dead_code)]

extern "C" {
    pub type Opaque;
}

pub struct TailOpaque {
    a: usize,
    opaque: Opaque,
}

pub fn foo(v: &TailOpaque) -> &Opaque {
    &v.opaque
}
```

```rust
#![feature(extern_types)]
#![allow(dead_code)]

extern "C" {
    pub type Opaque;
}

pub struct TailOpaque {
    a: usize,
    b: usize,
    opaque: Opaque,
}

pub fn foo(v: &TailOpaque) -> usize {
    v.b
}
```

It seems that accessing or referencing any field of a tail-opaque struct past the first element triggers the assertion failure.

**Comment by NeoRaider** [comment]
Okay, digging further into this I have come to a few conclusions:

The rustc issue leading to the assertion failure is our attempt to generate a getelementptr instruction, which is invalid for unsized types. By commenting out a few sanity checks, I could get LLVM to emit IR with such an instruction, but it would then fail at a later step.

At this point, I was wondering why the issue only affects "extern type" (with PR #58271), and not all unsized types, for example a struct with a `str` last element. The solution is that regular unsized structs are emitted with a length-0 array, so they are sized from LLVM's point of view: A Rust `struct Foo(usize, str)` becomes `%Foo = type { [0 x i64], i64, [0 x i8], [0 x i8] }` in LLVM IR.

That leaves me with the question if there is a fundamental difference between "extern type" and existing unsized types which would require us to use `opaque` for one, but not for the other?

**Comment by NeoRaider** [comment]
One more data point, which may be relevant for unsized statics: clang (tested with 10.0.0) emits externals of unknown size as "size 0" as well:

```c
extern const char foo[];
```
turns into
```llvm
@foo = external global [0 x i8], align 1
```
My interpretation of this is that using an empty struct and not `opaque` in LLVM should be fine (unless LLVM somehow treats empty arrays and empty structs differently, in which case switching to an empty array for Rust external types would be the way to go?)

Unless someone has a different interpretation, I propose we go with one of the following options, so we can move to stabilize external types:
1. Keep the `struct {}` that is currently implemented and close this issue
2. Replace type emitted to LLVM with `[0 x i8]` (I can take case of the PR) and then close this issue

**Comment by RalfJung** [comment]
So the argument seems to be: clang doesn't use that pattern for opaque types, but it uses it for *something*, and thus the pattern is probably legal?

That seems reasonable. Before we rely on this, could someone file an LLVM bug asking them to state this explicitly in their LangRef (that `extern` globals may be larger than the type that is given, and that it is okay to access that larger part with `getelementptr inbounds`).

**Comment by NeoRaider** [comment]
@RalfJung I don't think we ever use `getelementptr inbounds` to access the opaque part of an external or tail-external type, because it's, well, opaque. The worst one can do without raw pointer arithmetic or otherwise unsafe code would be to access the first address of the opaque part - which is always valid because of the usual one-byte-past-the-end rule for pointer validity.

I would actually have expected that regular slices are a bigger problem, as `getelementptr inbounds` will be used for accesses into the "tail" of an unsized type, for example:
```rust
pub struct Foo(usize, str);
pub fn foo(v: &Foo) -> &u8 {
    unsafe { &v.1.as_bytes().get_unchecked(1) }
}
```
But there is no problem in this case either, as we emit slices as length 0 arrays - and the handling of this case is explained in detail here: https://llvm.org/docs/GetElementPtr.html#what-happens-if-an-array-index-is-out-of-bounds

**Comment by RalfJung** [comment]
The issue is with cases like
```rust
extern {
    type Foo;
    static mut BAR: Foo;
}
```
At least after cross-crate inlining (LTO, maybe even cross-language LTO), there can well be actual accesses to `BAR` happening, I think. After all `opaque` is not an intrinsic property of that static, it just expresses our lack of knowledge about it. Some code somewhere will now the actual dimenions of it (everything else would be rather pointless), and with sufficient inlining that code can end up in our crate that only sees an opaque type.

**Comment by NeoRaider** [comment]
Okay, in that case we should switch over to `[0 x i8]` just to be safe - I think the explanation in https://llvm.org/docs/GetElementPtr.html#what-happens-if-an-array-index-is-out-of-bounds makes it quite clear that accessing parts of an array past the end of a type is fine - that `inbounds` is about the actual size of the allocation, not about the size of the LLVM type.

**Comment by hanna-kruppe** [comment]
FWIW, I don't think that page really addresses the concern. It tells us that static type information of the *pointer* or GEP is irrelevant and the actual allocation size matters, but the type of global variables in fact determines the actual allocation size. Certainly with `static X: [u8; 4]`, a GEP calculating `(&X[0]).offset(5)` is going out of bounds. Maybe for `extern` globals the type isn't assumed to be authoritative, but that doesn't follow from those docs you linked.

**Comment by NeoRaider** [comment]
I see. I can make a request for clarification over at the LLVM bug tracker as soon as my account is approved.

**Comment by NeoRaider** [comment]
https://bugs.llvm.org/show_bug.cgi?id=45681

**Comment by mjbshaw** [comment]
Can https://bugs.llvm.org/show_bug.cgi?id=45681 be closed now that https://reviews.llvm.org/D78952 was merged? And are there any other clarifications required before Rust can use `opaque` for extern types?

**Comment by NeoRaider** [comment]
@mjbshaw I think the LLVM bug can be closed. As I understand it, the result of the merge is the opposite though for Rust: With the clarified LLVM spec, there should be no reason for Rust to use `opaque` for extern types - meaning the issues we had with our attempts to use `opaque` don't need to block stabilization of extern types anymore, and this issue can be closed.

(@RalfJung Please correct me if any of this is inaccurate)

**Comment by RalfJung** [comment]
Yeah that sounds right, the LLVM patch seems pretty clear about this. Thanks for pushing this through on the LLVM side!
