### ISSUE TITLE
compiletest path normalization is too aggressive

### ISSUE THREAD

**Issue by euclio** [rust-lang/rust#59109]
Notice that the backslashes in the help output for intra-doc link warnings are incorrectly converted to forward slashes:

https://github.com/rust-lang/rust/blob/de5c3c4b07fb37028bb36b2271271caf24eec6f3/src/test/rustdoc-ui/intra-links-warning.stderr#L8

The normalization is currently just a replace on all backslashes:

https://github.com/rust-lang/rust/blob/b244f61b77c42d7be695afd7901ee4418559e518/src/tools/compiletest/src/runtest.rs#L3083

**Comment by pnkfelix** [comment]
Could we perhaps use the [canonicalize](https://doc.rust-lang.org/std/fs/fn.canonicalize.html) method here?
