### ISSUE TITLE
Tracking issue for udp_peer_addr

### ISSUE THREAD

**Issue by LinusU** [rust-lang/rust#59127]
Tracking issue for making `peer_addr()` on `UdpSocket` stable: #59106, #59104

**Comment by sanxiyn** [comment]
FYI, in Rust issue tracker, "tracking issue" is a jargon for stabilizing features already in nightly. As I understand, `peer_addr` is not yet in nightly?

**Comment by jonas-schievink** [comment]
@sanxiyn A tracking issue has to be opened before a feature can land in nightly, because the `#[unstable]` attribute needs an issue number to refer to. https://github.com/rust-lang/rust/pull/59106 has also been approved already, so it'll land in one of the next nightlies.

**Comment by MOZGIII** [comment]
How about moving this to stable?

**Comment by ghedo** [comment]
What's left to do to stabilize this feature? Any ETA?

**Comment by Thomasdezeeuw** [comment]
Can this be stablised for 1.37?

**Comment by stjepang** [comment]
Can we kick off FCP for stabilization?

**Comment by Dylan-DPC** [comment]
@rust-lang/libs any updates?

**Comment by sfackler** [comment]
@rfcbot fcp merge
