### ISSUE TITLE
error: unknown codegen option: `passes\`

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#59142]
I've got a weird bug:

```rust
> cargo build
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `rustc - --crate-name ___ --print=file-names -C passes\=lint --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-typ
e staticlib --crate-type proc-macro` (exit code: 1)
--- stderr
error: unknown codegen option: `passes\`
```

If you see there, it's doing `-C passes\=lint`. 

Fails on both

```
> rustc --version
rustc 1.33.0 (2aa4c46cf 2019-02-28)
> rustc --version
rustc 1.35.0-nightly (e68bf8ae1 2019-03-11)
```

I have no idea where that `\` is coming from. Any ideas?

**Comment by ehuss** [comment]
Everything between `--print=file-names` and `--crate-type` comes from user-configured rustflags (`RUSTFLAGS` from env, or `target.*.rustflags` or `build.rustflags` from `.cargo/config`).

**Comment by steveklabnik** [comment]
uuuuugh thank you. (Somehow an experimental RUSTFLAGS i was working on persisted across shell invocations, thank you!)
