### ISSUE TITLE
Unused variables suggest `_prefix` for patterns with `ref` bindings when `_` wildcard would suffice

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#59153]
```
error: unused variable: `e`
   --> src/librustc_resolve/error_reporting.rs:234:41
    |
234 |             if let PathSource::Expr(ref e) = source {
    |                                         ^ help: consider prefixing with an underscore: `_e`
    |
    = note: `-D unused-variables` implied by `-D warnings`
```

The correct suggestion is either to remove the `ref e` and supply `_e` or to change the code to `ref e: _`.

**Comment by ehuss** [comment]
I think this may be the same as #54180.

**Comment by estebank** [comment]
It's very similar. It'll probably be fixed by the same code.

**Comment by petrochenkov** [comment]
>remove the `ref e` and supply `_e`

This may cause a "can't move out from `source`" error later.

>... or to change the code to `ref e: _`

It's longer and noisier, why is this better than `ref _e`?
The existing diagnostic looks like the best alternative to me.

**Comment by pnkfelix** [comment]
> > ... or to change the code to `ref e: _`
> 
> It's longer and noisier, why is this better than `ref _e`?
> The existing diagnostic looks like the best alternative to me.

Longer, noisier, and invalid: [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=06c7cae1ffb1b1d3cc61bf71cad28fc5)

The only thing I can think of that is actually valid code that looks like that in this context is `Variant { 0: ref _e }` ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=5341a3a7a38bf734ba57d6bbf33f4af2))

but like @petrochenkov , I do not see why one would suggest that over `Variant(ref _e)`

**Comment by pnkfelix** [comment]
Or maybe the intent is to suggest `Variant(_)` rather than `Variant(ref e)` ?

**Comment by pnkfelix** [comment]
In any case, if we are indeed talking about tuple-structs, I don't see how the given suggestion as implemented is "incorrect." It may not be *ideal* (if I'm right that `Variant(_)` should always be a valid option here), but striving for the ideal is a feature request, not a bug fix

**Comment by estebank** [comment]
This is what I get for creating tickets sleep deprived. I misread the error as having the problem in #54180. We can close this one.
