### ISSUE TITLE
`cargo test` fails on #![no_main] crates

### ISSUE THREAD

**Issue by johnthagen** [rust-lang/rust#59162]
`cargo test` behaves very strangely / incorrectly on `#![no_main]` projects.

```rust
// main.rs
#![no_main]

#[no_mangle]
pub fn main(_argc: i32, _argv: *const *const u8)  {
    println!("Hello World");
}

#[cfg(test)]
mod tests {
    #[test]
    fn it_works() {
    }
}
```

```toml
# Cargo.toml
[package]
name = "rust-test"
version = "0.1.0"
edition = "2018"

[dependencies]
```

```bash
$ rustc --version
rustc 1.33.0 (2aa4c46cf 2019-02-28)

$ cargo test
    Finished dev [unoptimized + debuginfo] target(s) in 0.11s
     Running target/debug/deps/rust_test-2fde18cd93d5074c
Hello World
error: test failed, to rerun pass '--bin rust-test'
```

Note that:

1 . The tests fail.
2. `Hello World` is printed, indicating that the `no_mangle`'d `main` was actually executed?

If `#![no_main]` and `#[no_mangle]` are removed, `cargo test` runs properly.

**Comment by Richard-W** [comment]
The solution here is to use  `#![cfg_attr(not(test), no_main)]` instead of `#![no_main]`. Then `no_main` will only be active in non-test configurations.

**Comment by johnthagen** [comment]
@Richard-W Thank you for the work around. Would it make sense for this to be something that is handled by `cargo test` for the user? It does seem at least a little surprising behavior (and exposes some of the magic `cargo test` is doing for the user).

**Comment by jonas-schievink** [comment]
The problem here is that you replaced Rust's main function with one that doesn't return a status code to libc. Adjusting the code so that `fn main` returns `i32`, and putting a `0` at the end of it fixes this.
