### ISSUE TITLE
Segmentation fault (address boundary error) when optimizations off

### ISSUE THREAD

**Issue by alexbuzzbee** [rust-lang/rust#59171]
I think this shell session sums it up:

```
[20:42:21] me@my-box /project/path (0) 
> target/debug/program
fish: “target/debug/program” terminated by signal SIGSEGV (Address boundary error)
[20:42:24] me@my-box /project/path (139) 
> target/release/program

Rust panicked.
[20:42:27] me@my-box /project/path (127) 
>
```

There's obviously something else wrong with my program (thus the panic (I've had to override the panic handler for... reasons)), but that's not Rust's fault.

I also used `gdb` to take a look at what's going on and found this around the point of the crash with `disassemble`:

```
   0x0000555555557ce6 <+134>:   xorps  %xmm0,%xmm0
   0x0000555555557ce9 <+137>:   movups %xmm0,0x12c(%rsp)
=> 0x0000555555557cf1 <+145>:   movaps %xmm0,0x120(%rsp)
   0x0000555555557cf9 <+153>:   movaps %xmm0,0x110(%rsp)
   0x0000555555557d01 <+161>:   movaps %xmm0,0x100(%rsp)
   0x0000555555557d09 <+169>:   movaps %xmm0,0xf0(%rsp)
   0x0000555555557d11 <+177>:   movaps %xmm0,0xe0(%rsp)
   0x0000555555557d19 <+185>:   movaps %xmm0,0xd0(%rsp)
```

With the `release` build (optimizations enabled), `disassemble` shows:

```
   0x000055555555534f <+63>:    xorps  %xmm0,%xmm0
   0x0000555555555352 <+66>:    movups %xmm0,0x116(%rsp)
   0x000055555555535a <+74>:    movups %xmm0,0x10a(%rsp)
=> 0x0000555555555362 <+82>:    movups %xmm0,0xfa(%rsp)
   0x000055555555536a <+90>:    movups %xmm0,0xea(%rsp)
   0x0000555555555372 <+98>:    movups %xmm0,0xda(%rsp)
   0x000055555555537a <+106>:   movups %xmm0,0xca(%rsp)
   0x0000555555555382 <+114>:   movups %xmm0,0xba(%rsp)
```

Note that the instruction pointer has passed the point of the panic in the `debug` build.

If necessary, I can provide full source (or more disassemblies), but the relevant section is:

```rust
let mut addr: lens_syscalls::sockaddr_un = lens_syscalls::sockaddr_un{sun_family: 1, sun_path: [0; 108]};
```

I wrote `lens_syscalls` myself. The relevant struct declaration (based on `struct sockaddr_un` from the Linux man pages) is:

```rust
#[repr(C)]
pub struct sockaddr_un {
  pub sun_family: u16,
  pub sun_path: [u8; 108],
}
```

Version:

```
rustc 1.35.0-nightly (7c19e1eed 2019-03-12)
binary: rustc
commit-hash: 7c19e1eed5418b8c02be65d678417b241ee01a3e
commit-date: 2019-03-12
host: x86_64-unknown-linux-gnu
release: 1.35.0-nightly
LLVM version: 8.0
```

**Comment by Mark-Simulacrum** [comment]
Full source would be appreciated (ideally in a form that is readily compilable, for reproduction purposes).

**Comment by alexbuzzbee** [comment]
Alright, the libraries and so forth can be found [here](https://gitlab.com/lens-os/) in several different projects. The program can be found [here](https://gitlab.com/lens-os/msgserver). Please forgive my un-idiomatic Rust, I'm working fairly directly with the Linux kernel syscall API and I haven't worked out all the niceties yet. It has to be compiled with its own `build.sh` because it needs to change some linker configuration, because it's `no_std` but running on Linux so it has its own `_start` (I know that's horrifying and might be part of the crazy edge case that triggers this bug), and I haven't gotten around to writing a target spec.

**Comment by Mark-Simulacrum** [comment]
I *suspect* this is because of the `-Znostartfiles` that is being passed to the linker; at this point I'm guessing we're expecting a startup routine where there is none or something along those lines.

I'm able to reproduce the segfault with the following if I compile with `rustc -Zpre-link-arg=-nostartfiles main.rs`

```rust
fn main() { }
```

**Comment by parched** [comment]
What's the value of the stack pointer at the crash? Is it 16 byte aligned? If not, can you look at the backtrace to see where it got unaligned?

**Comment by hellow554** [comment]
```rust
#![feature(lang_items)]
#![no_std]
#![no_main]

use core::panic::PanicInfo;

#[lang = "eh_personality"]
extern "C" fn eh_personality() {}

#[panic_handler]
fn panic(a: &PanicInfo) -> ! { 
    loop {}
}

#[no_mangle]
pub extern "C" fn _start() {}
```

(compile it with `rustc -Zpre-link-arg=-nostartfiles main.rs`)

@alexbuzzbe can you confirm that this code is roughly the same as your error?

In that case this is perfectly legal, because `_start` needs to call the [`exit` syscall](https://en.wikipedia.org/wiki/Exit_(system_call)) in order to exit the program properly.

(proof: a C program with

```c
void _start() {

}
```
and compiled with `gcc -o c_main start.c -nostartfiles` also segfaults)

**Comment by alexbuzzbee** [comment]
Key point: `_start` has nowhere to return to. If it doesn't call `_exit`, it'll just jump off to some random garbage "return address" it finds on the stack and segfault. However, the issue I'm seeing is happening (apparently) while zeroing memory on the stack, which seems like a very different issue to me.

**Comment by alexbuzzbee** [comment]
The error happens well before any possible return from `_start`, so that is not the issue. To double-check, I've added an `exit` call to the end of the program and the problem still occurs.

@parched No such luck; stack pointer is `0x7fffffffe3c8` at the crash.

**Comment by hellow554** [comment]
> Is it 16 byte aligned? 

> stack pointer is 0x7fffffffe3c8 at the crash

therefore it's not properly aligned. 

That's the exact difference between the "unoptimized code" (`0x0000555555557cf1 <+145>:   movaps %xmm0,0x120(%rsp)`) and the "optimized code" (`0x0000555555555362 <+82>:    movups %xmm0,0xfa(%rsp)`).

movaps: Move Aligned ...
moups: Move Unaligned ...

You will need to properly align your pointer beforehand I guess. There happens a lot in `_start`, that may be one of the things.

**Comment by alexbuzzbee** [comment]
I see. Didn’t notice the difference in instructions. Many thanks, I suppose it’s not Rust’s fault after all.
