### ISSUE TITLE
Shouldn't a non-miri flag be added for syntax-extension

### ISSUE THREAD

**Issue by sntdevco** [rust-lang/rust#59177]
This is an excerpt from [syntax-extension-cfg](https://github.com/rust-lang/rust/blob/master/src/test/run-pass/macros/syntax-extension-cfg.rs)
```
// compile-flags: --cfg foo --cfg qux="foo"
// check <- Add #[cfg(not(miri))] // Miri does not support panics
pub fn main() {
    
    
    if ! cfg!(foo) { panic!() }
    if   cfg!(not(foo)) { panic!() }
    if ! cfg!(qux="foo") { panic!() }
    if   cfg!(not(qux="foo")) { panic!() }
    if ! cfg!(all(foo, qux="foo")) { panic!() }
// -- Omitted for brevity ---
```
Shouldn't the flag, as mentioned above be added (by the check comment)?

**Comment by oli-obk** [comment]
cc @ralfjung

**Comment by sntdevco** [comment]
Closing at it supports panics but not `should_panic` tests or `catch_panic`

**Comment by RalfJung** [comment]
That's a run-pass test for macros, Miri doesn't do anything with that (right now). But this might become relevant when progress is made on https://github.com/RalfJung/miri-test-libstd/issues/1.
