### ISSUE TITLE
ICE (ish): Segfault with the following code

### ISSUE THREAD

**Issue by raphaelcohn** [rust-lang/rust#59184]
When trying to compile the code below in a file `asm.rs`, the Rust compiler segfaults (Segmentation Fault 11).

Example command line:-

```
rustc --edition=2018 asm.rs
```

(The presence of the `--edition` tag seems irrelevant).

When asking for LLVM IR output, a segfault does not occur, eg `rustc --emit llvm-ir -o asm.ir -v --edition=2018 asm.rs`.

The segfault also does not happen if the call to `read_after_raising_any_exceptions()` is removed from main. It's possible my assembler is mis-formed, but that's not completely germane - the compiler should not segfault.

Version details from `rustc -V`: `rustc 1.35.0-nightly (719b0d984 2019-03-13)`
OS: Mac OS 10.14.2 , running on a Mac Pro trashcan.

Rust code:-

```rust
#![feature(asm)]

fn main()
{
    println!("Hello, world! {}", read_after_raising_any_exceptions());
}

#[inline(never)]
pub fn read_after_raising_any_exceptions() -> u16
{
	unsafe
	{
		// See <https://github.com/HJLebbink/asm-dude/wiki/FSTCW_FNSTCW>.
		let mut control_word: u16;
		asm!
		(
			"fstcw $0"
			:
				// Output constraints.
				"=m"(control_word)
			:
				// Input constraints.
			:
				// Clobbers.
			:
				// Options.
				"volatile"
		);
		control_word
	}
}
```

**Comment by hellow554** [comment]
Maybe related to https://github.com/rust-lang/rust/issues/51130 ?

**Comment by raphaelcohn** [comment]
Possibly.

**Comment by Amanieu** [comment]
This issue does not apply to the new `asm!` ([RFC 2850](https://github.com/rust-lang/rfcs/pull/2850)) which doesn't support memory constraints.

The legacy `llvm_asm!` is deprecated and is no longer maintained.
