### ISSUE TITLE
Allow customising ty::TraitRef's printing behavior.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#59188]
(Originally discussed in https://github.com/rust-lang/rust/pull/58140#discussion_r254136845)
Right now a `TraitRef` prints as ` <T as Trait<U>>` via "debug" (`{:?}`) and `Trait<U>` via "display" (`{}`) - this is used all over rustc to indicate what printed form of the trait is desired.

However, it would be overall cleaner for "display" and "debug" printing to match (or even for `fmt::Display` to not be implemented at all, perhaps?), and provide all the information that exists (i.e. including the `Self` type).

We would then need a replacement for printing "just the trait path with its parameters", and I think we can have a method, `.print_only_trait_path()`, that returns a wrapper which has the different formatting behavior.

**Comment by eddyb** [comment]
Blocked on #58140.

Also, in order to do this thoroughly, `fmt::Display` would need to be removed from `TraitRef` (comment-out its section in `src/librustc/ty/print/pretty.rs`) and all uses of formatting it with `{}` would have to be put through the new `.print_only_trait_path()` method instead.

Only after that is done and everything compiles again, can `fmt::Display` be re-enabled for `TraitRef` (and it can be given the same behavior as `{:?}` today).
Some simplification of `ty::print` may be possible afterwards (right now associated items of a trait have to print `<T as Trait<U>>` themselves, without the special-casing `Trait<U>` would be printed).

cc @nikomatsakis

**Comment by stepnivlk** [comment]
hey @eddyp https://github.com/rust-lang/rust/pull/58140 got merged does it mean you're happy with proceeding forward with this one? If so I think I can tackle it.

**Comment by nathankleyn** [comment]
Hey @eddyp! I would love to pick this one up and got a bit of the way into exploring this, but wondering — what did you have in mind for where `.print_only_trait_path` would be implemented?

As in — is this method added to the existing `Print` / `PrettyPrinter` traits somehow? Using a new wrapper trait with that method which is `impl`d only for `ty::TraitRef`? A `fn` at the top level somewhere? Somehow else?

**Comment by nathankleyn** [comment]
Hey @eddyb! I would love to pick this one up and got a bit of the way into exploring this, but wondering — what did you have in mind for where `.print_only_trait_path` would be implemented?

As in — is this method added to the existing `Print` / `PrettyPrinter` traits somehow? Using a new wrapper trait with that method which is `impl`d only for `ty::TraitRef`? A `fn` at the top level somewhere? Somehow else?

**Comment by eddyp** [comment]
@stepnivlk you probably meant @eddyb

**Comment by eddyb** [comment]
`TraitRef::print_only_trait_path` would only construct a trivial wrapper around `self` (and that wrapper would be e.g. `pub struct TraitRefPrintOnlyTraitPath<'tcx>(ty::TraitRef<'tcx>);`).
We can also have the same method on `PolyTraitRef` (i.e. `Binder<TraitRef>`) that returns `Binder<TraitRefPrintOnlyTraitPath>` (using `map_bound`).

Then, in  `ty::print::pretty`, we'd have change this to be on `TraitRefPrintOnlyTraitPath`:
https://github.com/rust-lang/rust/blob/316a391dcb7d66dc25f1f9a4ec9d368ef7615005/src/librustc/ty/print/pretty.rs#L1530-L1532
and also here:
https://github.com/rust-lang/rust/blob/316a391dcb7d66dc25f1f9a4ec9d368ef7615005/src/librustc/ty/print/pretty.rs#L1449

(since that is the behavior for printing with `{}`, i.e. `fmt::Display`, it's the one we want to force to go through `print_only_trait_path`)

**Comment by nathankleyn** [comment]
Thanks @eddyb — that's really helpful! I'll try to make a start on this and see how far I get, it's a really great way to explore my way around the compiler internals some more! 🤞

**Comment by Areredify** [comment]
@nathankleyn can I snatch this?

**Comment by nathankleyn** [comment]
@Areredify Feel free! Some partial work here if it helps: https://github.com/nathankleyn/rust/commit/f5ec9d8c9136e2368d7f89e44d6e240d7b8e2801

However it was, when I was last working on it, giving me some confusing issues and I couldn't untangle it.
