### ISSUE TITLE
Remove `-Zborrowck=compare`

### ISSUE THREAD

**Issue by matthewjasper** [rust-lang/rust#59193]
This flag is mostly unused and adds complexity. This may be best to split across multiple PRs. 

- [x] Remove the flag (#60513)
- [x] Remove from tests (#60513)
- [x] Remove error reporting from AST borrow check
- [x] Remove librustc_borrowck dependency on librustc_mir 
- [ ] Remove error codes that are only emitted by AST borrow check
- [ ] Remove the `Origin` enum
- [ ] Remove `BorrowckErrors` trait or make it `pub(crate)`
- [ ] Move `borrowck_errors` and `suggest_ref_mut` into the borrow_check module

**Comment by pnkfelix** [comment]
NLL triage: prioritizing as P-medium.

**Comment by chrisvittal** [comment]
I'm willing to start poking at this. Removing the flag is easy enough. But what should I be doing with the tests that have the flag?

**Comment by matthewjasper** [comment]
Removing the flag, and updating the message, this should be done after #59114, so that the migrate mode output is being tested.

**Comment by matthewjasper** [comment]
@chrisvittal do you still want to work on this?

**Comment by chrisvittal** [comment]
I do. I’ll have a PR soon.

**Comment by matthewjasper** [comment]
@chrisvittal are you working on the rest of this?

**Comment by chrisvittal** [comment]
No Sorry. I should have told you sooner.
