### ISSUE TITLE
Regression in decl_macro emitted item resolutions

### ISSUE THREAD

**Issue by IsaacWoods** [rust-lang/rust#59196]
On the current nightly (`2019-03-13`), the following code fails ([link to the playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=6d73c384ad5f6ed59543869f51b5b60a)):
``` rust
#![feature(decl_macro)]

macro bar() {
    pub enum Bar {
        A,
        B,
        C
    }
}

bar!();

fn main() {
    let _ = Bar::A;
    let _ = Bar::B;
    let _ = Bar::C;
}
```
with the error:
```
error[E0433]: failed to resolve: use of undeclared type or module `Bar`
  --> src/main.rs:14:13
   |
14 |     let _ = Bar::A;
   |             ^^^ use of undeclared type or module `Bar`

error[E0433]: failed to resolve: use of undeclared type or module `Bar`
  --> src/main.rs:15:13
   |
15 |     let _ = Bar::B;
   |             ^^^ use of undeclared type or module `Bar`

error[E0433]: failed to resolve: use of undeclared type or module `Bar`
  --> src/main.rs:16:13
   |
16 |     let _ = Bar::C;
   |             ^^^ use of undeclared type or module `Bar`
```

This seems to be an issue with the `decl_macro` feature specifically - declaring the same macro with `macro_rules` works as intended.

**Comment by estebank** [comment]
CC @petrochenkov

**Comment by Centril** [comment]
Is this actually a bug?

**Comment by IsaacWoods** [comment]
@Centril I hope it is - otherwise it would be impossible for a macro to declare items that could then be used?

Note: the macro is being invoked; I’m not expecting to access the item from inside the macro, but the item it generates.

**Comment by petrochenkov** [comment]
This works as expected, `macro` macros are fully hygienic (unlike `macro_rules` macros that are hygienic only for local variables).
As a result, `Bar` created by the macro and `Bar` used in `main` are totally different `Bar`s.

Opt-out from that hygiene is supposed to be explicit (https://github.com/rust-lang/rfcs/pull/2498 or something like that), but it's not yet implemented.
```rust
macro bar() {
    pub enum #Bar {
        ...
    }
}
```

In the meantime, identifiers that are not supposed to be hygienic can be passed to a `macro` as arguments.
```rust
macro bar($Bar: ident) {
    pub enum $Bar {
        ....
    }
}

bar!(Bar);
```

**Comment by IsaacWoods** [comment]
Okay, thanks for clarifying @petrochenkov (and apologies @Centril) - I didn't realise macros 2.0 would be that hygienic.
