### ISSUE TITLE
Use `track_errors` instead of hand-rolling such a check

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#59215]
Const eval asserts that reporting an error for statics actually worked. This is not only done in a wrong way (checks for no error having happened in the entire compilation), it's also very fragile. We should instead use the `track_errors` method around the `report_as_error` call, and in case `track_errors` returns `Ok`, we need to do the `delay_span_bug`.

The relevant code that needs to be changed can be found in https://github.com/rust-lang/rust/blob/16e7e05e95a6a5a1e0dba54ae722274bd7d725f7/src/librustc_mir/const_eval.rs#L645-L654

**Comment by estebank** [comment]
Wouldn't using `track_errors` cause the compiler to stop at const evaluation? Ideally we would want the compiler to choose a reasonable recovery value (just a binding of `TyErr`?) and continue to minimize the loop of "fix 5 errors, get 300 errors" (#39275).

**Comment by oli-obk** [comment]
`track_errors` doesn't actually stop anything. It just gives you a `Result::Err` if new errors occured and a `Result::Ok` otherwise.

**Comment by JohnTitor** [comment]
@oli-obk I want to solve this, could I open a PR(and ask you to review)?

**Comment by oli-obk** [comment]
Jup! It's all yours!
