### ISSUE TITLE
Warn when lifetime parameters are unused.

### ISSUE THREAD

**Issue by thestinger** [rust-lang/rust#5922]
**UPDATE:** Updating this issue to reflect current thinking, which is that inference should issue a warning when a lifetime parameter is inferred to be bivariant (which implies that the parameter is unused).

**ORIGINAL:** It's sometimes necessary to specify a lifetime on an object that *doesn't* contain borrowed pointers, because lifetime dependencies can be required for safety outside of Rust's borrowed pointer system. A dummy borrowed pointer member is a workaround, but wasteful.

@nikomatsakis

**Comment by steveklabnik** [comment]
closing in favor of https://github.com/rust-lang/rust/issues/22212
