### ISSUE TITLE
Index out of sync on doc.rust-lang.org

### ISSUE THREAD

**Issue by yushih** [rust-lang/rust#59249]
On the page https://doc.rust-lang.org/std/vec/struct.Vec.html  there are functions missing from the left-side index panel, `sort`, `sort_by_key` among others.

**Comment by lzutao** [comment]
The link you give is broken. Anyway, those methods `sort`, `sort_by_key` is from [slice](https://doc.rust-lang.org/std/primitive.slice.html#method.sort_by_key).

**Comment by yushih** [comment]
(Linked fixed. Thanks for pointing out)
But they are supposed to be under the "Methods from Deref<Target=[T]>" header as are other methods from slice, right?

**Comment by jyn514** [comment]
This is fixed on stable: https://doc.rust-lang.org/std/vec/struct.Vec.html#method.sort_by_key
