### ISSUE TITLE
rustdoc: `code` block within portability span is unreadable on dark theme

### ISSUE THREAD

**Issue by ehuss** [rust-lang/rust#59261]
The portability span uses code blocks for target features, but these have a default dark background color that is unreadable on the dark theme.

<img width="241" alt="image" src="https://user-images.githubusercontent.com/43198/54496124-fa25d600-48a8-11e9-8fdc-ac688287f457.png">

Sample page: https://doc.rust-lang.org/nightly/core/arch/x86_64/index.html

**Comment by GuillaumeGomez** [comment]
Indeed, will send a fix.
