### ISSUE TITLE
Cannot find public existing method

### ISSUE THREAD

**Issue by aristarh2704** [rust-lang/rust#59274]
When I use OwningRef in my code and try call "erase_owner", rustc says:
error[E0599]: no method named `erase_owner` found for type `rustc_data_structures::owning_ref::OwningRef<std::boxed::Box<[u8]>, [u8]>` in the current scope

**Comment by hellow554** [comment]
There is a little chance we can help you right now. We don't have code to look at nor additional information e.g. why it should work. 

Can you please share some code, e.g. preferable a so called [MCVE](http://stackoverflow.com/help/mcve). You can use [the playground](https://play.rust-lang.org/) to create such MCVE.

**Comment by oli-obk** [comment]
Closing as unactionable. Please consider the suggestions by @hellow554 or asking on one of the chat platforms: https://www.rust-lang.org/community

**Comment by aristarh2704** [comment]
`rustc_data_structures::owning_ref::OwningRef::erase_owner` not implemented for `Box<T:?Sized>`
[https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=3902a7036b84f6ea5ad27fe0c90cceab](url)
But there [https://github.com/rust-lang/rust/blob/d51a437e28ab2cebbee9d54c3dbfe06e59f242d1/src/librustc_data_structures/sync.rs#L60-L65](url) this method work properly.
