### ISSUE TITLE
prebuilt rust-std's libraries are not stripped

### ISSUE THREAD

**Issue by stefson** [rust-lang/rust#59272]
hey there, I'm not sure where to direct this :) 

it is just that the prebuilt rust-1.32.0-${RUST_CHOST}.tar.xz stages include rust-std suitable for ${RUST_CHOST}, and those are non-debug + stripped libraries. 

whereas prebuilt rust-std-1.32.0-${FOREIGN_RUST_CHOST}.tar.xz has the rustlib libraries with debug info, hence not stripped. 

since it's possible to strip them with cross-binutils, do you think you could release them as stripped in the future?

**Comment by hellow554** [comment]
You could use `llvm-strip` for cross platform strip without the need to install a toolchain for different targets.

**Comment by stefson** [comment]
Where's the point in your argument? This is about the prebuilt rust-std files from static.rust-lang.org, and unless I've got access to the infra behind it I can't do anything. Cross compiling a rust-std on my own is a different story though.

**Comment by richardwhiuk** [comment]
Alternatively, should `rust-1.32.0-${RUST_CHOST}.tar.xz` contain debug info? That sounds like a nice thing to have...

**Comment by cuviper** [comment]
AFAIK, all `rust-std` packages are supposed to have debug info. What is your `${RUST_CHOST}` where this is missing?
