### ISSUE TITLE
Tracking issue for todo! macro

### ISSUE THREAD

**Issue by matklad** [rust-lang/rust#59277]
This is a tracking issue for `todo!` macro.

Added in #56348. Feature gate: `#![feature(todo_macro)]`.

When stabilizing, we should adjust documentation for `unimplemented!` to point towards `todo!`

**Comment by stjepang** [comment]
Anyone wants to FCP for stabilization?

I find this macro so handy I began putting `#![feature(todo_macro)]` everywhere.

**Comment by stjepang** [comment]
It's been a while -- just a ping in case this slipped through. :)

**Comment by matklad** [comment]
I guess we should submit stabilization PR and run FCP on that? Note that the PR needs to adjust docs for `unimplemented` as well. I can send the PR, but not immediately: putting out fires in rust-analyzer :D

**Comment by SimonSapin** [comment]
I don’t have a strong opinion on this one, but since it landed and there doesn’t seem to be significant issues discussed since:

@rfcbot fcp merge

**Comment by FlyingCanoe** [comment]
why is this not stable wet?

**Comment by matklad** [comment]
@FlyingCanoe it will be stable with Rust 1.40: https://github.com/XAMPPRocky/rust/blob/relnotes-1.40.0/RELEASES.md#stabilized-apis

**Comment by SimonSapin** [comment]
The stabilization PR https://github.com/rust-lang/rust/pull/61879 should have closed this issue. In fact it even landed before FCP in this thread was started…
