### ISSUE TITLE
rustdoc search should ensure it shows exact matches

### ISSUE THREAD

**Issue by scottmcm** [rust-lang/rust#59287]
I was trying to find https://doc.rust-lang.org/nightly/nightly-rustc/syntax/ptr/struct.P.html in rustdoc, but that doesn't show up anywhere if I just search for `P`: https://doc.rust-lang.org/nightly/nightly-rustc/rustc_mir/transform/?search=P

It _does_ show up if I search for `"P"` (https://doc.rust-lang.org/nightly/nightly-rustc/rustc_mir/transform/?search=%22P%22) so there's a workaround, but I think it'd be nice if when I type an exact name, things with that exact name show up at the top, or something.

**Comment by GuillaumeGomez** [comment]
It's supposed to so this some adjustments to be done on the "search engine". I'll take a look.
