### ISSUE TITLE
Iter with step_by(2) performs slowly

### ISSUE THREAD

**Issue by wooleyra** [rust-lang/rust#59281]
Comparing the performance between these similar functions, the one that uses the iterator with the step_by(2) function performs significantly slower than the one using a traditional "while loop".

``` Rust
fn is_prime_iter(num: u32) -> bool {
    if num == 2 {
        return true;
    }
    if num % 2 == 0 {
        return false;
    }
    let mut is_prime = true;
    for i in (3..num).step_by(2) {
        if num % i == 0 {
            is_prime = false;
            break;
        }
    }
    is_prime
}

fn is_prime_loop(num: u32) -> bool {
    if num == 2 {
        return true;
    }
    if num % 2 == 0 {
        return false;
    }
    let mut is_prime = true;
    let mut i = 3;
    while i < num {
        if num % i == 0 {
            is_prime = false;
            break;
        }
        i += 2;
    }
    is_prime
}
```
Running the experimental `cargo bench --all-targets` produced the following results for me using the nightly-x86_64-unknown-gnu toolchain (1.35.0-nightly):
```
// benchmark value: 15485867
test tests::bench_is_prime_iter  ... bench:  26,813,870 ns/iter (+/- 337,054)
test tests::bench_is_prime_loop ... bench:  21,607,357 ns/iter (+/- 242,028)
```

**Comment by hellow554** [comment]
Interesting enough, if you are using `all` instead of manual if/break it gets even slightly faster

```
# cargo bench
    Finished release [optimized] target(s) in 0.01s
     Running target/release/deps/foo-8f4575d6c09c1e6c

running 3 tests
test allbar ... bench:      89,120 ns/iter (+/- 2,359)
test iter   ... bench:     109,650 ns/iter (+/- 3,717)
test loop   ... bench:      92,457 ns/iter (+/- 2,685)
```

([Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=619001d6a7a28a2711a41a8e84043003))

**Comment by scottmcm** [comment]
For tiny loop bodies like this it's not unusual for internal iteration to be faster -- `chain` is the same.

**Comment by nikic** [comment]
Godbolt: https://rust.godbolt.org/z/LRTDre

**Comment by steveklabnik** [comment]
Triage: no change

**Comment by jrmuizel** [comment]
Comparing `checked_add` in a loop vs step_by shows there's something special going on in with `step_by` beyond the `checked_add`
https://rust.godbolt.org/z/79aTac847

**Comment by the8472** [comment]
#111850 fixed this.

https://rust.godbolt.org/z/h1M73Tf34

The iter and loop assembly look a bit different but in both cases there are just 3 branches in the loop:

* panic
* loop exit
* backedge

A big improvement compared to the rustc 1.33 version which had tons of branches

The benchmarks from https://github.com/rust-lang/rust/issues/59281#issuecomment-474233552 look identical now:

```
test allbar ... bench:     133,624 ns/iter (+/- 1,487)
test iter   ... bench:     133,673 ns/iter (+/- 1,271)
test r#loop ... bench:     133,629 ns/iter (+/- 1,067)
```

So I think this can be closed.
