### ISSUE TITLE
rustc can't write in internal Android filesystem

### ISSUE THREAD

**Issue by hydroper** [rust-lang/rust#59292]
On Termux's file system, `rustc` hello-world compiles, but I need to edit files from QuickEdit/Quoda editors, but they can't access hidden app data (`/data`), so how would I edit my Rust in Termux fs? On the other hand, there's the UserLAnd app (that emulates Ubuntu/Debian/Arch Linux), but I'm not sure if it works too and is not elegant.

Doing a hello-world in my internal file system fails:

```sh
$ cd /sdcard/Hydroper
$ cargo new hello-world
$ cd hello-world0
$ cargo rustc --target armv7-linux-androideabi
```

I receive this:

```
error: failed to link or copy `/storage/emulated/legacy/Hydroper
  /hello-world/target/armv7-linux-androideabi
  /debug/deps/hello_world-1a5a0f0d60d07a86`
to `/storage/emulated/legacy/Hydroper
  /hello-world/target/armv7-linux-androideabi
  /debug/hello-world`

Caused by:
  Operation not permitted (os error 1)
```

With some warnings based on the following:

```
warning: error copying object file `/storage/emulated/legacy/Hydroper
  /hello-world/target/armv7-linux-androideabi
  /debug/deps/hello_world-1a5a0f0d60d07a86.15tmymq5l8gl9bw.rcgu.o`
to incremental directory as `/storage/emulated/legacy/Hydroper
  /hello-world/target/armv7-linux-androideabi
  /debug/incremental/hello_world-2rcp0qtfldxo0/s-fahrccndht-uujlbh-working/15tmymq5l8gl9bw.o`:

    Operation not permitted (os error 1)
```

And I'm rooted (Android 5.1.1). I did `$ termux-setup-storage`.

**Comment by mati865** [comment]
What filesystem do you have on SD Card? Is it FAT32?

**Comment by Lonami** [comment]
This really doesn't sound like an issue with Rust itself. Consider editing the files from within Termux with any console editor (vim, nano, you name it), or triple check the file permissions/owner.

**Comment by hydroper** [comment]
@Lonami I need to type in a proper code editor as I'm using a touch-only device.

> or triple check the file permissions/owner.

Did you mean `chmod`?

**Comment by hydroper** [comment]
It's a Android protection issue...
