### ISSUE TITLE
there should be warning or error when mutating const

### ISSUE THREAD

**Issue by abbychau** [rust-lang/rust#59307]
https://gist.github.com/08f01df0252e9fa272ad5dd0e4bb70e7

please refer to `S.x += 1;` to the above code.

**Comment by petrochenkov** [comment]
Similar issues - https://github.com/rust-lang/rust-clippy/issues/829, https://github.com/rust-lang/rust/issues/55721, https://github.com/rust-lang/rust/issues/40543

**Comment by jonas-schievink** [comment]
Seems like a duplicate of https://github.com/rust-lang/rust/issues/55721
