### ISSUE TITLE
Double-drop of moved object in closure

### ISSUE THREAD

**Issue by antoyo** [rust-lang/rust#59319]
Hi.
The following code causes a double-drop:
```rust
#[derive(PartialEq)]
struct Object {
}

impl Drop for Object {
    fn drop(&mut self) {
        println!("Drop");
    }
}

fn main() {
    let object = Object {};
    let callback = move || {
        println!("Called");
        if object == object {
        }
    };
    let boxed: Box<Box<FnOnce()>> = Box::new(Box::new(callback));

    let ptr = Box::into_raw(boxed) as *mut Box<Fn()>;
    let from_raw: Box<Box<Fn()>> = unsafe { Box::from_raw(ptr) };
    from_raw();
    println!("After from_raw()")
}
```
[Playground here.](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=99c9d6ba2622598365dc6fa9f0da3a23)

I'm not sure what is going on.
Is this normal behavior because I converted a `FnOnce` to a `Fn`?
Thanks.

**Comment by sfackler** [comment]
> ```rust
>     let ptr = Box::into_raw(boxed) as *mut Box<Fn()>;
>     let from_raw: Box<Box<Fn()>> = unsafe { Box::from_raw(ptr) };
> ```

This is undefined behavior.

**Comment by jonas-schievink** [comment]
Not a Rust bug, so closing
