### ISSUE TITLE
target-cpu is an invalid print request

### ISSUE THREAD

**Issue by lwshang** [rust-lang/rust#59317]
In [rustc book](https://doc.rust-lang.org/rustc/codegen-options/index.html#target-cpu), it suggest that `rustc --print target-cpu` will provide the valid options of `target-cpu`.

When I tried it in both stable and nightly rustc, the output are the same:

```
$ rustc --print target-cpu                                                                                                                                                                                 
error: unknown print request `target-cpu`
```

We may have wrong document in rustc book. Or the command used to work but now it is not supported because of some recent change in `rustc --print` behavior.

**Comment by jonas-schievink** [comment]
It's `rustc --print target-cpus`, note the trailing `s`
