### ISSUE TITLE
Get `x.py test` output in human-readable format

### ISSUE THREAD

**Issue by alexreg** [rust-lang/rust#59332]
When `x.py test` fails, the stdout and stderr are in JSON format, most annoyingly. How can we get it in the usual human-readable format? (This should really be default, by the way.)

**Comment by Centril** [comment]
Maybe it would be sufficient to pretty print the JSON for now?

**Comment by phansch** [comment]
I think https://github.com/rust-lang/rust/pull/59128 may be fixing this, in addition to colored output? Specifically https://github.com/rust-lang/rust/pull/59128/commits/7c8482cfb375ec6985dca4fa7736a258cc076725.

cc @oli-obk

**Comment by alexreg** [comment]
@phansch Cool. You may well be right, judging by that. Incidentally, I should have said the `--error-format` option is misleading (and not properly documented in the case of `x.py`)... it seems to simply get ignored.

**Comment by jyn514** [comment]
x test no longer outputs in JSON format by default; I'm going to close this.
