### ISSUE TITLE
Unable to backtrace using gdb on ARM

### ISSUE THREAD

**Issue by ILyoan** [rust-lang/rust#5934]
gdb couldn't backtrace stack frames on ARM.

This is because gdb couldn't unwind from a frame using custom personality routine.
Apparently, gdb wants  `__gxx_personality_v0` to be statically linked so that gdb can assume that the custom personality routine finally uses GNU personality and the value in the .extab is also encoded for GNU personality.

**Comment by steveklabnik** [comment]
Giving this a close, as it's very very old, as @errordeveloper mentions.

Let me know if this is incorrect.
