### ISSUE TITLE
Truncating conversion between numeric primitive types

### ISSUE THREAD

**Issue by JoeVirtual** [rust-lang/rust#59379]
Hi,

i am looking for a way in the rust stdlib to convert truncating a numeric primitive type into another numeric primitive type. 

Like the Traits `From`, `Into` or `TryFrom`, `TryInto` provides.

The conversion i am looking for tuncates the value to the numeric bounds of the result type, for example:

- `255u8`  to `i8` results into `127i8` ,
-  `-128i8` to `u8` results into `0u8`,
-  `-129i16` to `i8` results into `-128i8`

It would be nice to get besides the tuncated result value also an info if the number was tuncated by the conversion, but this is not so important.

Thanks in advance.

**Comment by jonas-schievink** [comment]
This doesn't currently exist and would likely have to go through an RFC. It can also be prototyped in an external crate (eg. something like [`cast`](https://docs.rs/cast/0.2.2/cast/)). Closing in favor of that.

**Comment by JoeVirtual** [comment]
Thanks @jonas-schievink for the response and the reference to the crate.
I will try to create a crate and prototype this, but my experince with rust is very limited, so this will take awhile.

**Comment by jonas-schievink** [comment]
Sure! If you have any questions, feel free to ask in the user forum at https://users.rust-lang.org/ or on IRC.
