### ISSUE TITLE
Follow up on `const_eval.rs` `check_match` call

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#59378]
https://github.com/rust-lang/rust/pull/59199#discussion_r267637931

**Comment by oli-obk** [comment]
Super-High-Level Instructions:

Replace https://github.com/rust-lang/rust/blob/master/src/librustc_mir/const_eval.rs#L617-L632 with

```rust
if def_id.is_local() && tcx.typeck_tables_of(def_id).tainted_by_errors {
    return Err(ErrorHandled::Reported);
}
```

And then follow up by making sure that the compiler doesn't ICE anywhere (e.g. during MIR building). It should probably "just work" nowadays. A crater run isn't necessary, as this will only ICE if an error wasn't handled properly. Successfully compiling code is unaffected.

**Comment by whitfin** [comment]
@oli-obk I took a look at this and all tests seem fine in `librustc_mir` just dropping in the code you have above as you said.

However  I just wanted to check https://github.com/rust-lang/rust/blob/master/src/librustc_mir/const_eval.rs#L625-L627 is no longer needed? Pretty unfamiliar with this code so I wanted to confirm before submitting as it's not explicitly mentioned in the other thread that it should be removed.

**Comment by oli-obk** [comment]
Yes that should be removed, too. It will automatically be run when fetching the MIR of the current constant.

**Comment by whitfin** [comment]
@oli-obk ok, cool! I have filed a PR for this in https://github.com/rust-lang/rust/pull/59781. Let me know if anything needs to be updated!
