### ISSUE TITLE
problem with floor function

### ISSUE THREAD

**Issue by jblindsay** [rust-lang/rust#59388]
There appears to be an unexpected behaviour with the floor function for f64 (likely f32 as well). When applied to values greater than -1.0 and less than 0.0, it returns 0.0 instead of -1.0. That is, it is rounding up (ceil) rather than down in this one range of values.

`assert_eq!(-0.8f64.floor(), -1f64);`

**Comment by varkor** [comment]
```rust
fn main() {
    let x = -0.8_f64;
    println!("{}", -0.8_f64.floor()); // 0
    println!("{}", x.floor());        // -1
}
```
I think this is a bug in const evaluation.

**Comment by ollie27** [comment]
`-0.8f64.floor()` is equivalent to `-(0.8f64.floor())` not `(-0.8f64).floor()`.

**Comment by oli-obk** [comment]
Maybe clippy could lint `-foo.operation()` expressions?

**Comment by varkor** [comment]
Whoops. I do think the precedence here is confusing. It's easy to think of the minus sign as being part of the literal. A clippy lint would be helpful.

**Comment by oli-obk** [comment]
Opened https://github.com/rust-lang/rust-clippy/issues/3903
