### ISSUE TITLE
The code is not compiled on arm

### ISSUE THREAD

**Issue by aristarh2704** [rust-lang/rust#59386]
This code (https://play.rust-lang.org/?version=nightly&mode=release&edition=2018&gist=ff147eaa994ee5c8ab8516b2ac65fd8e) successfully compiled in playground, but is not compiled on arm-unknown-linux-gnueabihf.
Compiler output: 
```
error[E0597]: `**a` does not live long enough
  --> playground.rs:26:56
   |
26 |         let metadataref:MetadataRef=myowningref.map(|a|*a).erase_owner();
   |                                                        ^^- borrowed value only lives until here
   |                                                        |
   |                                                        borrowed value does not live long enough
   |
note: borrowed value must be valid for the anonymous lifetime #2 defined on the body at 26:53...
  --> playground.rs:26:53
   |
26 |         let metadataref:MetadataRef=myowningref.map(|a|*a).erase_owner();
   |                                                     ^^^^^


```

**Comment by jonas-schievink** [comment]
Please provide more information. Where is the code, which Rust version are you using, what commands are you running to reproduce this?

**Comment by aristarh2704** [comment]
> Please provide more information. Where is the code, which Rust version are you using, what commands are you running to reproduce this?

I'm using rustc 1.35.0-nightly (2019-03-20) on my phone, and rustc 1.35.0-nightly (2019-03-22) on playground

**Comment by jonas-schievink** [comment]
It doesn't build with `rustc` because the default edition is 2015. You need the 2018 edition (`--edition 2018`) for non-lexical lifetimes.
