### ISSUE TITLE
std::time issues 

### ISSUE THREAD

**Issue by dmitsuki** [rust-lang/rust#59391]
std::time doesn't really work like one would expect it to. For example, if you take a duration and get it as milliseconds, but there isn't any whole milliseconds, it just returns nothing. 

That is really unexpected behavior. If you get a number as milliseconds, but you don't have a whole millisecond, you should be given a fraction. The division between seconds and nanoseconds is also odd to me. 

A much better way to handle it seems to be to return as seconds as a double and any other conversion can be handled by division. As of right now the only real way to use it is to do it yourself adding nanoseconds, but that doesn't seem to be how a time module should function.

**Comment by Mark-Simulacrum** [comment]
An f64 would likely lose precision.

In any case I believe this is documented on the relevant APIs; and these are already stabilized so can't be changed at this point, further questions should go to the forums (internals or users).
