### ISSUE TITLE
Stop emitting `DW_AT_linkage_name` for non-mangled symbols

### ISSUE THREAD

**Issue by rocallahan** [rust-lang/rust#59422]
Debuggers will try to demangle `DW_AT_linkage_name` names. However, rustc (1.33) is emitting non-mangled names in `DW_AT_linkage_name` attributes for `#[no_mangle]` symbols. I think you can just omit `DW_AT_linkage_name` completely for these symbols, which will also save a tiny bit of space.

**Comment by tromey** [comment]
This is a dup of #46487
