### ISSUE TITLE
Reserve additional elements in Vec does not reserve additional elements

### ISSUE THREAD

**Issue by CasualX** [rust-lang/rust#59438]
I have a loop which appends to a Vec of u8, I append to the vector by reserving enough additional capacity, writing in the buffer reserved by the capacity and calling set_len when done. However using `reserve` in certain cases does not grow the vector! violating the documented behavior that the resulting capacity should have at least the specified additional elements.

I tried this code: [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=e365a5aeb5f5248d983428982ef9bd4a)

```rust
fn main() {
	let sizes = &[220, 224, 248, 216];
	let mut vec = Vec::<u8>::new();
	for &size in sizes {
		let vec_len = vec.len();
		let vec_cap = vec.capacity();
		if vec_len + size > vec_cap {
			let additional = vec_len + size - vec_cap;
			vec.reserve(additional); // This fails to reserve additional elements!
			//vec.reserve_exact(additional); // This works!
			assert!(vec.capacity() >= vec_len + size,
				"vec_len: {}, vec_cap: {}, size: {}, additional: {}, vec.capacity(): {}",
				 vec_len,     vec_cap,     size,     additional,     vec.capacity());
		}
		unsafe { vec.set_len(vec_len + size) };
	}
}
```

I expected to see this happen: Code works as expected and at every iteration there is enough capacity

Instead, this happened: In the last iteration it tries to ensure at least 216 bytes are present, but the capacity didn't change! The assert triggers with the following message, you can observe how the capacity hasn't changed even though 20 additional elements were requested.

`thread 'main' panicked at 'vec_len: 692, vec_cap: 888, size: 216, additional: 20, vec.capacity(): 888'`

## Meta

Latest stable, see playground. Appears to be a problem in std lib implementation of reserve as it breaks on playground (linux os, I imagine) and on my computer (x64_86 windows msvc).

**Comment by jonas-schievink** [comment]
I think `reserve` will reserve `additional` more elements compared to the `Vec`s current *length*, not *capacity*, so this looks like an expected outcome. You probably want to do `vec.reserve(size);` directly.

**Comment by CasualX** [comment]
D'oh it seems you are correct and I misread the docs... I've no idea how I managed to overlook the clearly stated expected capacity of at least `self.len() + additional`...
