### ISSUE TITLE
Tracking issue for `cfg_if`

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/rust#59442]
This issue tracks the stabilization of `libcore`'s `cfg_if!` macro. See: https://github.com/rust-lang/rust/pull/59443

**Comment by jonas-schievink** [comment]
Added in https://github.com/rust-lang/rust/pull/59336, I think?

**Comment by SimonSapin** [comment]
#59443 was closed, and #59336 adds the macro but does not export it. Closing as there is no public unstable API to track here. Feel free to reopen if/when the macro is exported.

**Comment by RalfJung** [comment]
In the light of https://github.com/rust-lang/rust/issues/65860 we might reconsider actually exposing this from libcore: fn-like macros are "more powerful" in some sense than attribute-based ones, in particular around syntax the compiler does not understand. We don't ship a fn-like `cfg` macro in libcore, but with the recent syntax feature gating issues I feel we should -- and `cfg_if` seems like a great choice for that.

**Comment by gnzlbg** [comment]
A `cfg_if!` like addition would require an RFC, and in the PR that proposed adding it a couple of people argued that they would prefer a `cfg_match!` instead, but nobody has put much work into exploring that.

**Comment by Centril** [comment]
Fwiw, while I prefer `cfg_match!` I think `cfg_if!` is a decent solution as well.
cc @SimonSapin & @alexcrichton -- does this require an RFC or is a PR enough?

**Comment by RalfJung** [comment]
Agreed, `match` seems more Rust-y than an if-else chain.

**Comment by alexcrichton** [comment]
Given the contention in the past with `cfg_if!` it feels like its best to be safe and have an RFC for this.
