### ISSUE TITLE
Targeted suggestions for specific "no method" errors on standard library types

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust#59450]
Rustc currently shows a perfectly reasonable error message when calling a nonexistent method:

```rust
use std::collections::BTreeSet;

fn main() {
    let mut set = BTreeSet::new();
    set.push("");
}
```

```console
error[E0599]: no method named `push` found for type `std::collections::BTreeSet<_>` in the current scope
 --> src/main.rs:5:9
  |
5 |     set.push("");
  |         ^^^^
```

<br>

But for specific frequently encountered cases, it would be great to show a more targeted error that gives the name of the method you almost definitely meant to call, despite not being similar enough to trigger the "did you mean" suggestion.

Candidates would be cases that arise often from refactoring (this applies to BTreeSet::push, which I see every now and then after replacing a Vec with a BTreeSet) or cases of a Rust API being named differently from an equivalent C++ API.

- BTreeSet::push ⟶ suggest `insert`
- [Vec::push_back](https://en.cppreference.com/w/cpp/container/vector/push_back) ⟶ suggest `push`
- VecDeque::push ⟶ suggest `push_back`
- Vec::length, [Vec::size](https://en.cppreference.com/w/cpp/container/vector/size) ⟶ suggest `len`

**Comment by estebank** [comment]
Do you think this would be a common enough pattern that it'd be worth creating something like `rustc_on_unimplemented` but for confusables?

Something like

```
trait BTreeSet {
    #[rustc_confusables("insert")]
    fn push() {}
}
```

```
error[E0599]: no method named `push` found for type `std::collections::BTreeSet<_>` in the current scope
 --> src/main.rs:5:9
  |
5 |     set.push("");
  |         ^^^^ help: you might have meant to use `insert`
```

**Comment by dtolnay** [comment]
Something similar to rustc_on_unimplemented sounds like it would work! I don't know enough about the diagnostics implementation to know what the other options are.

Bonus points if it is straightforward for a new rustc contributor to add a confusable and corresponding test case.

**Comment by fmease** [comment]
We could also reuse (abuse?) `#[doc(alias = "…")]` for this. I think I've seen this mentioned a few times.

**Comment by kadiwa4** [comment]
Maybe relevant: #107108 adds `doc(alias)` support to that error

**Comment by jieyouxu** [comment]
Now that PR #112239 is merged, it should be easy to add `#[rustc_confusables(...)]` to some of these methods.

**Comment by estebank** [comment]
I'll have #120730 close this ticket. We can open new ones for specific methods that require more aliases.
