### ISSUE TITLE
x.py clean extracts bootstrap compiler just to delete it again, if called 2 times

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#59465]
Running `./x.py clean` will extract the bootstrap compiler (beta) just to remove it again afterwards, if called consecutively.

````
./x.py build # bootstrap compiler is downloaded and extracted
./x.py clean # extracted compiler is removed
./x.py clean # boostrap compiler is extracted, and the removed again (??). 
````

repo @ c5fb4d0d2f464bc9ab61f7693ed4dde4d9326820

**Comment by Mark-Simulacrum** [comment]
This isn't really fixable - clean is implemented in Rust which means we need to compile rustbuild so we need to unpack the bootstrap compiler.
