### ISSUE TITLE
Bors cheat sheet link dead in CONTRIBUTING.md

### ISSUE THREAD

**Issue by wchargin** [rust-lang/rust#59475]
The link in “For @bors, this [cheat sheet] is helpful” in the [“Helpful
Links and Information” section][sec] of the `CONTRIBUTING.md` guide
currently gives a 500:

> # Error: 500 Internal Server Error
>
> Sorry, the requested URL `'http://localhost:7942/'` caused an error:
> 
> ```
> Internal Server Error
> ```

This was previously fixed in #44004, but both the old link and the new
link now seem to be down.

[sec]: https://github.com/rust-lang/rust/blob/33ef0bad21d6bb646c7c3ab0dbf381ca96c324bf/CONTRIBUTING.md#helpful-links-and-information
[cheat sheet]: https://buildbot2.rust-lang.org/homu/

**Comment by frewsxcv** [comment]
maybe we should take [the old contents](https://web.archive.org/web/20180924035000/https://buildbot2.rust-lang.org/homu/) and throw it in a markdown file in [the repo](https://github.com/rust-lang/homu) and link to that?

**Comment by frewsxcv** [comment]
...or also figure out what that 500 is :P

**Comment by pietroalbini** [comment]
Fixed now.

**Comment by wchargin** [comment]
Great; thank you!
