### ISSUE TITLE
call String struct .clone() very very slow!

### ISSUE THREAD

**Issue by zhuxiujia** [rust-lang/rust#59492]
call String struct .clone() very very slow!
<pre>
#[bench]
fn Bench_isOpt(b: &mut Bencher) {
    let s=String::from("asdfasdfasdf");
    b.iter(|| {
        s.clone();
    });
}
//test lib::RustExpressionEngine::runtime_test::Bench_isOpt       ... bench:          43 ns/iter (+/- 30)
</pre>

but in golang,clone string just  use
<pre>BenchmarkParser-12    	2000000000	         0.47 ns/op</pre>

Sometimes .clone () has to be used because of string borrowing problems, but it consumes a lot of performance. 
What do you do? How to clone without losing performance？

**Comment by Mark-Simulacrum** [comment]
I suspect this is due to Go's use of a GC or perhaps a different String implementation. Regardless, I don't think this issue is actionable -- if you would like to discuss the differences between Go and Rust's Strings is best done on internals.r-l.o or users.r-l.o.

**Comment by zhuxiujia** [comment]
> I suspect this is due to Go's use of a GC or perhaps a different String implementation. Regardless, I don't think this issue is actionable -- if you would like to discuss the differences between Go and Rust's Strings is best done on internals.r-l.o or users.r-l.o.

If rust is slower than gc lang like go,java, why do we use rust?
We should solve problems rather than avoid them. 
If we use a lot of string manipulation, the performance will be very, very poor.

**Comment by zhuxiujia** [comment]
> I suspect this is due to Go's use of a GC or perhaps a different String implementation. Regardless, I don't think this issue is actionable -- if you would like to discuss the differences between Go and Rust's Strings is best done on internals.r-l.o or users.r-l.o.

I found that the root problem of rust was the Vec
it is slow ，Slow insertion causes slow string splicing

**Comment by qnighy** [comment]
In https://users.rust-lang.org/ you may find people who would help you improving performance of your Rust code.
