### ISSUE TITLE
{:x?} to print `0x10` instead of `10`

### ISSUE THREAD

**Issue by calidion** [rust-lang/rust#59518]
currently `println("{:x?}", 0x10)` will print `10` instead of `0x10`, which is confusing from `10` in decimal.

**Comment by ordovicia** [comment]
Formatting with `{:#x}` prints leading `0x`.
[Doc](https://doc.rust-lang.org/std/fmt/index.html#sign0), [Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=d4db67450cc982665e2118160c2f59da)

**Comment by calidion** [comment]
@ordovicia thanks.
