### ISSUE TITLE
libprofiler_builtins is missing compile-time flags

### ISSUE THREAD

**Issue by michaelwoerister** [rust-lang/rust#59531]
For example `COMPILER_RT_HAS_FCNTL_LCK` and `COMPILER_RT_HAS_ATOMICS` are not being set. Would it be possible to use `cmake` (i.e. compiler-rt's regular build system) to find out which flags to set?

cc @rust-lang/infra @rust-lang/compiler

**Comment by michaelwoerister** [comment]
@alexcrichton I wonder if I can somehow use `cfg!(target_has_atomic = "cas")` for detecting whether to set the `COMPILER_RT_HAS_ATOMICS` flags. I guess that executing this in the build script would only tell me about the host platform, right? Is there a way to query `rustc`'s target platform spec?

**Comment by alexcrichton** [comment]
If you execute `rustc +nightly --print cfg` Cargo will use that to set env vars for the build script. When a build script is executed the env vars match the target we're executing the script for, so Cargo should set `CARGO_CFG_TARGET_HAS_ATOMIC=cas` (IIRC). 

Either that should be fine or just simply enabling it via a whitelist of platforms would be fine by me personally

**Comment by michaelwoerister** [comment]
Indeed: `CARGO_CFG_TARGET_HAS_ATOMIC = "16,32,64,8,cas,ptr"` :heart:
