### ISSUE TITLE
std::env::SplitPaths does not document its Item type

### ISSUE THREAD

**Issue by brettcannon** [rust-lang/rust#59543]
Reading both https://doc.rust-lang.org/std/env/struct.SplitPaths.html and https://doc.rust-lang.org/std/env/fn.split_paths.html there's no specification that the `Item` type for the iterator is `PathBuf`. To me it seemed ambiguous what an "iterator that splits an environment variable into paths"  or "an iterator over the paths" returns since it could be the string representing the paths -- which is `OsStr` -- or an actual `Path` object.

I'm happy to submit a PR if this is makes sense enough to fix (since according #30093 it used to specify this detail and now it doesn't with a quick perusal of https://github.com/rust-lang/rust/blame/master/src/libstd/env.rs not turning up anything obvious as to why the change).

**Comment by DevQps** [comment]
@brettcannon If you unfold `impl<'a> Iterator for SplitPaths<'a>` at the Trait Implementation section in [SplitPaths](https://doc.rust-lang.org/std/env/struct.SplitPaths.html) you can see that `Item = type Item = PathBuf`. Did you mean that this should be more clearly mentioned in the description of [SplitPaths](https://doc.rust-lang.org/std/env/struct.SplitPaths.html) (or maybe `split_paths` as well)?

I do think it would be nice if some extra text on `SplitPaths` would be added that clarifies the item type of the iterator!

**Comment by brettcannon** [comment]
@DevQps since I didn't even think of expanding `impl<'a> Iterator for SplitPaths<'a>` for the info (which in hindsight makes sense), my answer is "yes, mentioning it explicitly as part of the main summary would be handy".

As I said, if this is deemed reasonable I'm happy to do the PR to add the change.

**Comment by DevQps** [comment]
@brettcannon That would be great! Let us know what you come up with!

**Comment by brettcannon** [comment]
Looks like someone snagged fixing this before I had a chance to get to it, so I'll let #60022 and its author handle fixing this.

**Comment by DevQps** [comment]
@brettcannon Nice :) Let's wait for that then :)
