### ISSUE TITLE
Give the Unstable Book a title

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/rust#59554]
Similar to https://github.com/rust-lang/rfcs/pull/2669, but for the [Unstable Book](https://doc.rust-lang.org/unstable-book/index.html)

Right now, titles look like: `<title>emit_stack_sizes - </title>`

To do this, we might just need to add a `book.toml` file in [this directory](https://github.com/rust-lang/rust/tree/master/src/doc/unstable-book)

**Comment by gruberb** [comment]
I created a [PR](https://github.com/rust-lang/rust/pull/59569) for this issue. The title I added is "The Rust Unstable Book".  Or should it just be "The Unstable Book"?

**Comment by frewsxcv** [comment]
What you have looks great, thanks!

**Comment by frewsxcv** [comment]
Looks like there's still no title set after https://github.com/rust-lang/rust/pull/59569 🤔

**Comment by gruberb** [comment]
Hmm... I'll check later when I am
home!

**Comment by gruberb** [comment]
@frewsxcv I double checked and it seems it's not being able to compile since there is no `SUMMARY.md`. When I run it locally the title is there, but the index is empty.

So I'll add a `SUMMARY.md` and create a new PR.

**Comment by frewsxcv** [comment]
It's been a while since I looked at this code, so not entirely sure how it all works, but I think the summary.md file is generated here: https://github.com/rust-lang/rust/tree/master/src/tools/unstable-book-gen/src

**Comment by gruberb** [comment]
I see. I took inspiration from the other books (like [embedded](https://github.com/rust-embedded/book/tree/07fd3880ea0874d82b1d9ed30ad3427ec98b4e8a)). When I reproduce it for the unstable book, I get the title and everything.

So maybe I just have to add the `book.toml` to the `unstable-book-gen` folder. I never touched the books before so I am not sure why the unstable book behaves differently.

**Comment by ehuss** [comment]
@gruberb The unstable book is generated by a tool (`unstable-book-gen`) which processes and copies the files from `src/doc/unstable-book` to `build/*/md-doc/unstable-book` and then mdbook is run against that folder to save the output to `build/*/doc/unstable-book`.

I would probably edit [`unstable-book-gen`](https://github.com/rust-lang/rust/blob/acd8dd6a50d505057a7d7ad8d0d7a4c2bd274200/src/tools/unstable-book-gen/src/main.rs#L141) to copy the `book.toml` file over along with the source files.

**Comment by frewsxcv** [comment]
seems to be working now, thanks @gruberb!

https://doc.rust-lang.org/nightly/unstable-book/language-features/infer-static-outlives-requirements.html
