### ISSUE TITLE
Nightly fails to build unless git is installed

### ISSUE THREAD

**Issue by jbeich** [rust-lang/rust#59565]
Regressed by https://github.com/rust-lang/rust/pull/59303. Source archives don't have `.git` subdirectory, so missing `git` executable shouldn't be fatal.

```
thread 'main' panicked at 'Command::new("git").args(&["rev-parse", "--verify",
                           &format!("@:./{}" ,
                                    submodule)]).current_dir(&builder.src).output() failed with No such file or directory (os error 2)', src/bootstrap/native.rs:82:26
```

http://beefy9.nyi.freebsd.org/data/112amd64-default/497233/logs/errors/rust-nightly-1.35.0.20190330_1.log

**Comment by Mark-Simulacrum** [comment]
cc @euclio and @cuviper 

It might be worth just always rebuilding in source archives -- it seems reasonable to assume most people aren't editing the code in those. Unsure though; perhaps that's not a correct assumption.

**Comment by cuviper** [comment]
> It might be worth just always rebuilding in source archives

Yes, that was the intention, which you can see in the `else` case after checking `git_output.status.success()`. But I guess missing git entirely fails sooner, in the `Command::output()` call.

**Comment by cuviper** [comment]
Perhaps we should be using `GitInfo::new` for this, which has conditions for ignoring git or missing `.git`. That would also return the current *actual* hash in that path, which is probably even better to use than the submodule recorded in rust's `HEAD` (`@:./path`) or index (`:./path`).

**Comment by cuviper** [comment]
Actually, the `Build` already contains `in_tree_llvm_info` and `emscripten_llvm_info`!

**Comment by euclio** [comment]
Thanks for the quick fix!
