### ISSUE TITLE
musl arm tun ioctl different type

### ISSUE THREAD

**Issue by comicfans** [rust-lang/rust#59563]
hello , I'm trying to build https://github.com/cloudflare/boringtun with target arm-unknown-linux-musleabi , but failed with  

<pre>
   --> src/device/tun_linux.rs:125:31
    |
125 |         if unsafe { ioctl(fd, SIOCGIFMTU, &ifr) } < 0 {
    |                               ^^^^^^^^^^ expected i32, found u32

</pre>

but arm-unknown-linux-gnueabi can build successful

**Comment by jonas-schievink** [comment]
This is not a bug in Rust, please report it in the right repository. If you need any help, you can also ask in the user forum here: https://users.rust-lang.org/

**Comment by comicfans** [comment]
OK, so rust didn't provide cross platform for these low level interface , they still depends on the triple libc (even same arch/os)?
