### ISSUE TITLE
`core` lacks a stable version of `transmute`

### ISSUE THREAD

**Issue by Lokathor** [rust-lang/rust#59573]
We obviously have `std::mem::transmute`, but for `core` we only have

* `core::intrinsics::transmute`: unstable / feature gated
* `core::mem::transmute_copy`: which is _actually_ more dangerous than `transmute` because it's missing the "before and after have the same size" check.

So can we get `core::mem::transmute`?

**Comment by jonas-schievink** [comment]
It's there, it's just a reexport of the intrinsic: https://doc.rust-lang.org/core/mem/index.html#reexports

**Comment by jonas-schievink** [comment]
(which is stable, so I don't know what you're referring to)

**Comment by Lokathor** [comment]
Oh, well then the _docs_ are messed up because if you search for `transmute` it doesn't list out `core::mem::transmute` as being available.

**Comment by Lokathor** [comment]
On the Discord I was referred to this PR: https://github.com/rust-lang/rust/pull/57848

but that's from back in January, so it's confusing why the search still doesn't work right

https://doc.rust-lang.org/std/index.html?search=transmute

**Comment by Arnavion** [comment]
@Lokathor I see `core::mem::transmute` in your link.

(Note that the search index is defined in a `.js` file that can be cached. If you still don't see it, try hard-refreshing.)

**Comment by Lokathor** [comment]
alright, just some confusion then
