### ISSUE TITLE
Current Windows nightly misses `rust-lld`

### ISSUE THREAD

**Issue by phil-opp** [rust-lang/rust#59661]
The 2019-04-02 Windows nightly ~~has no `rust-lld` included~~ uses a different directory for `rust-lld` so that `rustc` does not find it anymore. You can see this by downloading the nightly `x86_64-pc-windows-msvc` archive from https://forge.rust-lang.org/other-installation-methods.html#standalone-installers. In contrast to stable, beta, and earlier nightlies, the current nightly has no `rust-nightly-x86_64-pc-windows-msvc/rustc/lib/rustlib/x86_64-pc-windows-msvc/bin` folder.

Versions:

rustc 1.35.0-nightly (428943cc2 2019-04-02)
binary: rustc
commit-hash: 428943cc290e64187e0698f41853ef316c0a7d03
commit-date: 2019-04-02
host: x86_64-pc-windows-msvc
release: 1.35.0-nightly
LLVM version: 8.0
cargo 1.35.0-nightly (63231f438 2019-03-27)

**Comment by alexcrichton** [comment]
Thanks for the report! @phil-opp can you confirm the exact installer that you're using? I unfortunately don't have a windows machine to reproduce on right now, but both these URLs contains `rust-lld.exe` in what I believe is the expected location:

* https://static.rust-lang.org/dist/2019-04-03/rustc-nightly-x86_64-pc-windows-msvc.tar.gz (rustup)
* https://static.rust-lang.org/dist/2019-04-03/rust-nightly-x86_64-pc-windows-msvc.tar.gz (one combined installer)

**Comment by phil-opp** [comment]
@alexcrichton They indeed contain a ` rust-lld.exe` but it seems like the location is wrong.

For https://static.rust-lang.org/dist/2019-04-03/rustc-nightly-x86_64-unknown-linux-gnu.tar.gz :

```
find -name "rust-lld"
./rustc/lib/rustlib/x86_64-unknown-linux-gnu/bin/rust-lld
```

For https://static.rust-lang.org/dist/2019-04-03/rustc-nightly-x86_64-pc-windows-msvc.tar.gz :

```
find -name "rust-lld.exe"
./rustc/bin/rustlib/x86_64-pc-windows-msvc/bin/rust-lld.exe
```

For https://static.rust-lang.org/dist/2019-04-02/rustc-nightly-x86_64-pc-windows-msvc.tar.gz :

```
find -name "rust-lld.exe"
./rustc/lib/rustlib/x86_64-pc-windows-msvc/bin/rust-lld.exe
```

So for some reason the `rustlib` directory now lives in `rustc/bin` instead of `rustc/lib`. I assume that this is the reason that `rustc` does not find `rust-lld` anymore on Windows in the latest nightly.

**Comment by alexcrichton** [comment]
Heh, an excellent point! Given the [regression range](https://github.com/rust-lang/rust/compare/f69422288...428943cc2) this is almost surely https://github.com/rust-lang/rust/pull/59341/files.

cc @o01eg, would you mind taking a look at this? I'm going to post a PR to revert that change in the meantime

**Comment by phil-opp** [comment]
Closing as per my comments in https://github.com/rust-lang/rust/pull/59668#issuecomment-479523038:

> I did some more investigation on #59661 and I'm no longer sure that `rustc` is at fault here, since all my projects that failed the Windows CI job today use `cargo xbuild`/`xargo` in some way. So the problem might as well be that the sysroot build tools do not copy the new directory. I will check this and report back as soon as I can!



> Ok, I can now confirm that the problem was that #59341 broke `cargo-xbuild`/`xargo`. When we update these tools to copy `bin/rustlib` too everything works again.
> 
> So this revert isn't needed. I'm very sorry for the wrong bug report!
