### ISSUE TITLE
Use `declare_lint_pass!` for internal lints

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#59683]
In https://github.com/rust-lang/rust/pull/59669 a `declare_lint_pass!` macro is introduced. In https://github.com/rust-lang/rust/pull/59316 two new lints are added that don't use this macro. This issue tracks fixing that.

- https://github.com/rust-lang/rust/pull/59316/files#diff-2451d441a5f5b7e7b0d0a63f45b66212R31 (use `impl_lint_pass!` here)
- https://github.com/rust-lang/rust/pull/59316/files#diff-2451d441a5f5b7e7b0d0a63f45b66212R73 (use `declare_lint_pass!` here)

cc @oli-obk @flip1995

**Comment by hgallagher1993** [comment]
Ya I'll take this on :+1:
