### ISSUE TITLE
PathBuf pop()s even if file_name is None

### ISSUE THREAD

**Issue by pongad** [rust-lang/rust#59714]
[Playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=48e3c5e8812e20c1d165e9d9330eb2c6)

The documentation states that `pop` should do nothing and return false if `file_name` is `None`, but it returns true and actually removes the ".." component.

**Comment by Stargateur** [comment]
it's not more a documentation error and should be if if `parent()` return `None` ?

**Comment by Stargateur** [comment]
Duplicate of https://github.com/rust-lang/rust/issues/58474 already fix in https://github.com/rust-lang/rust/pull/58496

**Comment by pongad** [comment]
Ah thank you for the pointer!
