### ISSUE TITLE
Miri component missing even though toolstate is green

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#59746]
According to https://rust-lang-nursery.github.io/rust-toolstate/, Miri's tests are currently passing, but still as we can see at https://rust-lang.github.io/rustup-components-history/, the Miri component is not actually available. I am not sure what is going wrong.

Cc @oli-obk @rust-lang/infra

**Comment by kennytm** [comment]
The bug is the components history's date is at 2019-04-03.

**Comment by RalfJung** [comment]
Oh, you are right. I saw some other CI failures elsewhere and thought they were caused by the component not being available, but instead that was just another instance of https://github.com/rust-lang/miri/issues/675. Sorry for the noise!
