### ISSUE TITLE
Enum variant struct pattern matching inconsistency?

### ISSUE THREAD

**Issue by Avi-D-coder** [rust-lang/rust#59753]
Given an enum with this shape.

```rust
enum FB {
    Foo { foo: bool },
    Bar,
}
```
In order to pattern match multiple `Foo` variants together an extra struct is required.
```rust
struct FooV {
    foo: bool,
}
enum FB {
    Foo(FooV),
    Bar,
}

match (fb1, fb2) {
        (FB::Foo(f1), FB::Foo(f2)) => f1.foo == f2.foo,
        _ => unimplemented!(),
};
```

Why doesn't the following work with the original enum struct? 
```rust
match (fb1, fb2) {
        (FB::Foo f1, FB::Foo f2) => f1.foo == f2.foo,
        _ => unimplemented!(),
};
```

**Comment by jonas-schievink** [comment]
Questions like this are best asked on the user forum at https://users.rust-lang.org/. We try to keep this issue tracker for bugs only.

The feature you're looking for is probably "enum variant types" https://github.com/rust-lang/rfcs/pull/2593
