### ISSUE TITLE
Suggest parenthesising multiple arguments to dbg!()

### ISSUE THREAD

**Issue by varkor** [rust-lang/rust#59763]
```rust
fn main() {
    dbg!(5, 10); // error: no rules expected the token `,`
}
```
It would be nice if the compiler suggested the intended form: `dbg!((5, 10))` as this seems like a reasonable mistake. This is specific to a particular macro, though, so I'm not sure how flexible we can be with diagnostics here.

**Comment by Centril** [comment]
Or we could just make the macro accept `dbg!(5, 10)`...
