### ISSUE TITLE
vec.clone() is slow

### ISSUE THREAD

**Issue by zhuxiujia** [rust-lang/rust#59773]
```
#[bench]
fn Bench_Clone(b: &mut Bencher) {
    let test=vec![1 as u8];
    b.iter(|| {
        test.clone();
    });
}
//result    ... bench:          49 ns/iter (+/- 0)
```
Why is VEC cloning so slow? Causing String struct to be slow？？

**Comment by lzutao** [comment]
@zhuxiujia Slow compared to which?

**Comment by leonardo-m** [comment]
"1 as u8" is better written "1u8" or something similar.

**Comment by zhuxiujia** [comment]
> "1 as u8" is better written "1u8" or something similar.

yes, any type(i32,String,f64.....)  bench  also cost  49 ns/iter (+/- 0)

**Comment by zhuxiujia** [comment]
> "1 as u8" is better written "1u8" or something similar.

you can try it, 100% also very slow!

**Comment by zhuxiujia** [comment]
> @zhuxiujia Slow compared to which?

compared with any type like  vec![ 1 as  i32 ],vec![ 1 as f64 ],vec!["1"]...   all  of           `49 ns/iter (+/- 0)`
but , other struct .clone() only use   `0 ns/iter (+/- 0)`
Is it because VEC data is stored on the heap instead of on the stack?

**Comment by sfackler** [comment]
Yes

**Comment by BourgondAries** [comment]
Most likely your struct uses only stack memory, and since the heap is non-deterministic (sbrk from the OS), you force the LLVM to not optimize your code.

With a struct, use `black_box(black_box(struct).clone())`.

Looking at the disassembly, LLVM won't even generate code for stack copy benchmarks (`iter_inner`) even with `black_box`, that's why you get `0 ns/iter`.

**Comment by zhuxiujia** [comment]
> Most likely your struct uses only stack memory, and since the heap is non-deterministic (sbrk from the OS), you force the LLVM to not optimize your code.
> 
> With a struct, use `black_box(black_box(struct).clone())`.
> 
> Looking at the disassembly, LLVM won't even generate code for stack copy benchmarks (`iter_inner`) even with `black_box`, that's why you get `0 ns/iter`.

Thank you, as you said, why do other languages like “go，java“ clone performance is not low? is  llvm not auto optimization assembly code?

**Comment by SimonSapin** [comment]
Have you benchmarked a heap allocation and deallocation taking, together, significantly less than 49 nanoseconds in Go or Java?

**Comment by zhuxiujia** [comment]
> Have you benchmarked a heap allocation and deallocation taking, together, significantly less than 49 nanoseconds in Go or Java?

```
package main

import "testing"

func BenchmarkClone(b *testing.B) {
	b.StopTimer()
	var str = "dfasdfas"
	var target=[]byte{}
	b.StartTimer()
	for i := 0; i < b.N; i++ {
		copy([]byte(str),target)
	}
}
//BenchmarkClone-8   	200000000	         7.29 ns/op
//PASS
```

**Comment by zhuxiujia** [comment]
> Have you benchmarked a heap allocation and deallocation taking, together, significantly less than 49 nanoseconds in Go or Java?

```
 public static void main(String[] args) {
        Date start=new Date();
        ArrayList<String> list=new ArrayList<String>();
        list.add("dsf");
        list.add("fsadf");
        for (int i=0;i<100000;i++){
            list.clone();
        }
       System.out.println((new Date().getTime()-d.getTime())/100000f+" ns/op");
    }
//              150ns/op
```

**Comment by BourgondAries** [comment]
> > Have you benchmarked a heap allocation and deallocation taking, together, significantly less than 49 nanoseconds in Go or Java?
> 
> it is in golang code.
> 
> ```
> package main
> 
> import "testing"
> 
> func BenchmarkClone(b *testing.B) {
> 	b.StopTimer()
> 	var str = "dfasdfas"
> 	var target=[]byte{}
> 	b.StartTimer()
> 	for i := 0; i < b.N; i++ {
> 		copy([]byte(str),target)
> 	}
> }
> //BenchmarkClone-8   	200000000	         7.29 ns/op
> //PASS
> ```

I don't know Go very well but this might just be copying stack data, have you tried attaching valgrind to see if it allocates?

**Comment by SimonSapin** [comment]
It might be worth trying with https://crates.io/crates/jemallocator_global as well.

**Comment by the8472** [comment]
Take a look at https://crates.io/crates/smallvec if you want on-tack cloning of small vecs

**Comment by zhuxiujia** [comment]
> > > Have you benchmarked a heap allocation and deallocation taking, together, significantly less than 49 nanoseconds in Go or Java?
> > 
> > 
> > it is in golang code.
> > ```
> > package main
> > 
> > import "testing"
> > 
> > func BenchmarkClone(b *testing.B) {
> > 	b.StopTimer()
> > 	var str = "dfasdfas"
> > 	var target=[]byte{}
> > 	b.StartTimer()
> > 	for i := 0; i < b.N; i++ {
> > 		copy([]byte(str),target)
> > 	}
> > }
> > //BenchmarkClone-8   	200000000	         7.29 ns/op
> > //PASS
> > ```
> 
> I don't know Go very well but this might just be copying stack data, have you tried attaching valgrind to see if it allocates?

golang slice data stored on heap!I don't know why go is so fast.

**Comment by BourgondAries** [comment]
> > > > Have you benchmarked a heap allocation and deallocation taking, together, significantly less than 49 nanoseconds in Go or Java?
> > > 
> > > 
> > > it is in golang code.
> > > ```
> > > package main
> > > 
> > > import "testing"
> > > 
> > > func BenchmarkClone(b *testing.B) {
> > > 	b.StopTimer()
> > > 	var str = "dfasdfas"
> > > 	var target=[]byte{}
> > > 	b.StartTimer()
> > > 	for i := 0; i < b.N; i++ {
> > > 		copy([]byte(str),target)
> > > 	}
> > > }
> > > //BenchmarkClone-8   	200000000	         7.29 ns/op
> > > //PASS
> > > ```
> > 
> > 
> > I don't know Go very well but this might just be copying stack data, have you tried attaching valgrind to see if it allocates?
> 
> golang slice data stored on heap!I don't know why go is so fast.

Optimization. Using valgrind I get 65 allocs on that benchmark, and so is equivalent to:
```
    let string = "dfasdfas";
    let mut target = ['\0'; 8];
    for (idx, i) in string.chars().enumerate() {
        target[idx] = i;
    }
```

So Go is not storing anything on the heap, or at least not allocating during each iteration of the benchmark.

Your Rust benchmark using `Vec` does 2_459_093 allocs (according to valgrind) during the benchmark, because it actually allocs on each run.

**Comment by zhuxiujia** [comment]
> > > > > Have you benchmarked a heap allocation and deallocation taking, together, significantly less than 49 nanoseconds in Go or Java?
> > > > 
> > > > 
> > > > it is in golang code.
> > > > ```
> > > > package main
> > > > 
> > > > import "testing"
> > > > 
> > > > func BenchmarkClone(b *testing.B) {
> > > > 	b.StopTimer()
> > > > 	var str = "dfasdfas"
> > > > 	var target=[]byte{}
> > > > 	b.StartTimer()
> > > > 	for i := 0; i < b.N; i++ {
> > > > 		copy([]byte(str),target)
> > > > 	}
> > > > }
> > > > //BenchmarkClone-8   	200000000	         7.29 ns/op
> > > > //PASS
> > > > ```
> > > 
> > > 
> > > I don't know Go very well but this might just be copying stack data, have you tried attaching valgrind to see if it allocates?
> > 
> > 
> > golang slice data stored on heap!I don't know why go is so fast.
> 
> Optimization. Using valgrind I get 65 allocs on that benchmark, and so is equivalent to:
> 
> ```
>     let string = "dfasdfas";
>     let mut target = ['\0'; 8];
>     for (idx, i) in string.chars().enumerate() {
>         target[idx] = i;
>     }
> ```
> So Go is not storing anything on the heap, or at least not allocating during each iteration of the benchmark.
> 
> Your Rust benchmark using `Vec` does 2_459_093 allocs (according to valgrind) during the benchmark, because it actually allocs on each run.
> 
> Edit: Because the go benchmark uses bytes, it's more equivalent to byte strings in rust (since char has boundary checks)
> 
> ```
>     let string = b"dfasdfas";
>     let mut target = [b'\0'; 8];
>     b.iter(|| {
>         for (idx, i) in string.iter().enumerate() {
>             target[idx] = *i;
>         }
>     });
> ```
> For which I get `2 ns/iter` on my machine. Admittedly, using `smallvec` yields `11 ns/iter` (it does some checks inside `smallvec` and clones somewhat naively).

some times because of Rust borrow problem  i must use  String struct  .   
but in Rust  String struct have a vec<u8> data，so clone a String  must be cost 49 ns/iter (+/- 0)
or  Even worse！so How to optimize it?

**Comment by zhuxiujia** [comment]
> > > > > Have you benchmarked a heap allocation and deallocation taking, together, significantly less than 49 nanoseconds in Go or Java?
> > > > 
> > > > 
> > > > it is in golang code.
> > > > ```
> > > > package main
> > > > 
> > > > import "testing"
> > > > 
> > > > func BenchmarkClone(b *testing.B) {
> > > > 	b.StopTimer()
> > > > 	var str = "dfasdfas"
> > > > 	var target=[]byte{}
> > > > 	b.StartTimer()
> > > > 	for i := 0; i < b.N; i++ {
> > > > 		copy([]byte(str),target)
> > > > 	}
> > > > }
> > > > //BenchmarkClone-8   	200000000	         7.29 ns/op
> > > > //PASS
> > > > ```
> > > 
> > > 
> > > I don't know Go very well but this might just be copying stack data, have you tried attaching valgrind to see if it allocates?
> > 
> > 
> > golang slice data stored on heap!I don't know why go is so fast.
> 
> Optimization. Using valgrind I get 65 allocs on that benchmark, and so is equivalent to:
> 
> ```
>     let string = "dfasdfas";
>     let mut target = ['\0'; 8];
>     for (idx, i) in string.chars().enumerate() {
>         target[idx] = i;
>     }
> ```
> So Go is not storing anything on the heap, or at least not allocating during each iteration of the benchmark.
> 
> Your Rust benchmark using `Vec` does 2_459_093 allocs (according to valgrind) during the benchmark, because it actually allocs on each run.
> 
> Edit: Because the go benchmark uses bytes, it's more equivalent to byte strings in rust (since char has boundary checks)
> 
> ```
>     let string = b"dfasdfas";
>     let mut target = [b'\0'; 8];
>     b.iter(|| {
>         for (idx, i) in string.iter().enumerate() {
>             target[idx] = *i;
>         }
>     });
> ```
> For which I get `2 ns/iter` on my machine. Admittedly, using `smallvec` yields `11 ns/iter` (it does some checks inside `smallvec` and clones somewhat naively).

Rust Vec  just like  go slice,so this test must  use Rust vec,  not  array or slice
