### ISSUE TITLE
wrapping_$op() and saturating_$op() should be #[must_use]

### ISSUE THREAD

**Issue by tormol** [rust-lang/rust#59787]
I just had a bug due to a `wrapping_add()` having no effect because the return value was ignored:

```rust
let mut foo = foo();
foo.x.wrapping_add(bar); // should be foo.x = foo.x.wrapping_add(bar);
foo.y = baz; // so no warning about foo not needing to be mutable
```
It's an easy mistake to make when rewriting `foo.x += bar` to handle overflow.

EDIT: (I didn't do enough searching before opening this issue)

On one hand this is a subset of #48926, and covers a lot of methods so [RFC #2450](https://github.com/rust-lang/rfcs/pull/2450) would be better. On the other hand this issue is a v2 of #50124 for the parts of it not covered by [#50149](https://github.com/rust-lang/rust/pull/50149).

## Meta
```
rustc 1.35.0-nightly (f8673e0ad 2019-04-03)
binary: rustc
commit-hash: f8673e0ad85e98997faa76fa7edc99c5825f46ee
commit-date: 2019-04-03
host: x86_64-unknown-linux-gnu
release: 1.35.0-nightly
LLVM version: 8.0
```

**Comment by lzutao** [comment]
What do you mean? If you comment the `foo.y` line, you would get the unused warning:
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=15090d92e645a5cdcd2af9071c92e3d9

**Comment by alex** [comment]
I would expect, in either version, a warning on the `wrapping_add` line about an unused result.

**Comment by varkor** [comment]
I agree that this could have been included as part of https://github.com/rust-lang/rust/issues/50124, so I don't think it'd be controversial to open a pull request adding `#[must_use]` to the `wrapping_*` variants.

**Comment by memoryruins** [comment]
+1, I've seen this bite a few users in chats. searching logs, one said:
> I'm using wrapping_add in yet another obligatory chip8 emulator and didn't store the result in a register, took me a few hours to find. thing is, I'm using that because of the panic for overflows, ironically exactly that is what caused me to write this bug

**Comment by Mark-Simulacrum** [comment]
AFAICT, this has since been done. Closing.
