### ISSUE TITLE
E0424 The self keyword was used in a static method.

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/rust#59782]
E0424 states:

> The self keyword was used in a `static` method.

But `static` method is probably wrong, it should just say a non-method (I don't think we have a technical term to refer to methods that do not take an arbitrary self type as first argument). 

It continues with:

> Please check if the method's argument list should have contained self, &self, or &mut self (in case you didn't want to create a static method), and add it if so.

That's outdated, `&mut Pin<Self>` (and others) work too. So this should be updated to cover arbitrary `Self` types.

**Comment by gnzlbg** [comment]
cc @Centril

**Comment by Centril** [comment]
Yea; the diagnostic is wrong. Methods are only those things which have a receiver (`self`). Other things are functions (methods are too)... we don't have a word for "thing that is a function but not a method" so "non-method" works and is clear in its explanatory purpose.

**Comment by petrochenkov** [comment]
"Static method" is just an older terminology, which should be natural and familiar if you used any other popular language before, but the doc (or lang) team made a decision not to use it in documentation at one point without providing a good alternative.

If you want to "fix" this you may want to update a bunch of other docs as well, rust-by-example in particular.

**Comment by gnzlbg** [comment]
@centril I think it would be better to get the lang team to sign on how to call these. I agree with @petrochenkov that we used to have terminology for these (`static` methods, inherent functions, UFCS, ...) which have been phased out without a replacement.

From a grammar POV, an `impl {}` block contains associated items, so methods are just associated functions with a receiver, and these are just associated functions. I'd guess that non-methods would work as well, but I'm not too fond of that name.

**Comment by Centril** [comment]
@gnzlbg I don't view "non-method" as a name really; it's describing things explicitly by opposition to methods, which makes sense for this diagnostic since having a `self` is the defining characteristic of a method and the problem was that it wasn't a method.

cc @rust-lang/lang @rust-lang/docs 

I don't want to FCP this... it's not important enough to get all the team to sign off.

**Comment by estebank** [comment]
Regarding arbitrary self types... There are a couple of places where suggestions or help text is technically incorrect by omission, like this one. We need to walk the line of being correct, thorough, and succinct. I'm not sure this case is a good place to teach people about this feature, depending on how much text/space it takes.

**Comment by Centril** [comment]
@estebank  perhaps link to a more elaborate description in the message?

**Comment by gnzlbg** [comment]
@estebank maybe using something like: "self receivers (like `self`, `&self`, or `&mut self`)", where "self receivers" links to their page in the reference would be correct (because of self receiver), succinct, and approachable for beginners (because it contains the three most common cases).

**Comment by dayo777** [comment]
Just came across this error in Rust edition 2021. I understand what the error means, but for anyone looking for a simpler explanation,
*it typically indicates that you are trying to reference a method, associated function, or field that is not defined or accessible in the current scope of that impl block. *

```Rust
struct MyStruct {
    name: String
}

impl MyStruct {
    fn first_fn() {
        self.second_fn()
    }
    
    fn second_fn(&self) {
        println!("Second fn");
   }
}
```

The above code was similar to my use-case. To make the code work, you have to make the `first_fn` &self in other to add it to scope so that you can reference the second function.

**Comment by estebank** [comment]
Note that the current error for that example is

```
error[E0424]: expected value, found module `self`
 --> src/lib.rs:7:9
  |
6 |     fn first_fn() {
  |        -------- this function doesn't have a `self` parameter
7 |         self.second_fn()
  |         ^^^^ `self` value is a keyword only available in methods with a `self` parameter
  |
help: add a `self` receiver parameter to make the associated `fn` a method
  |
6 |     fn first_fn(&self) {
  |                 +++++
```

which I feel provides the context needed. @dayo777 is there anything there that you'd want to add?

**Comment by dayo777** [comment]
Hello @estebank , nothing.
