### ISSUE TITLE
RISC-V -mcmodel=medium 

### ISSUE THREAD

**Issue by fintelia** [rust-lang/rust#59802]
[LLVM recently added some support for mcmodel=medium ](https://reviews.llvm.org/D54143) (which is equivalent to GCC's mcmodel=medany).  I believe that this means that it is now possible to cherry pick the relevant commits and expose support from Rust.

See also: rust-embedded/wg/issues/218

**Comment by laanwj** [comment]
great !
would be useful for me as well: Kendryte K210 expects code to run from fixed address `80000000`, so medlow relocations get truncated

**Comment by arunthomas** [comment]
Greetings from Oxidize!

It'd be great if someone could bump LLVM, so we can start adding support for Linux/RV64 targets. It was suggested @alexcrichton might be the person to ping about this.

@asb Is there a specific LLVM version you would recommend? I assume we want at least https://github.com/llvm/llvm-project/commit/da20f5ca74522c5ad7630180e7b99709e453dee5, but I imagine there may be other upstream fixes that are needed.

Thanks!

CCing @Disasm @jamesmunns

**Comment by fintelia** [comment]
@arunthomas Rust can already target bare metal Rv64 (with the riscv64imac-unknown-none-elf target). What is missing is the ability to place the code/symbols at locations outside the range [-2GB, 2GB]. That isn't too much of an issue for writing supervisor mode code which can just configure the MMU to map those addresses to point to RAM, but machine mode can't pick the memory layout of the board it runs on.

**Comment by Disasm** [comment]
I also really want these patches to be merged. I've already tried to merge upstream branch as well as to deduce a cherry-pick-able set of commits but failed in both cases. Because of that, I can't tell whether these patches will fix the issue or not. At the moment I'm stuck waiting for help. I'm ready to give it another try, but I need some guidance. Maybe @alexcrichton or @asb could help me?

**Comment by alexcrichton** [comment]
There's instructions/rationale about updating LLVM hosted at https://rust-lang.github.io/rustc-guide/codegen/updating-llvm.html. Instructions are slightly out of date but I'll send a PR to fix them.

**Comment by Disasm** [comment]
(Current status) This patch arrived in LLVM: https://github.com/llvm/llvm-project/commit/a5240361dd64a1e9d70caead940e626f45fd4655
Now LLVM is able to generate pc-relative address load instructions for global variables and functions.
