### ISSUE TITLE
Travis mac builds are slower and keep timing out

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#59815]
We've been trying to land the Clippy update (https://github.com/rust-lang/rust/pull/59783, now https://github.com/rust-lang/rust/pull/59810) and it keeps timing out on the Travis Mac build

This timeout has also happened on https://github.com/rust-lang/rust/pull/58972#issuecomment-481290868

All the logs do not point to clippy or miri (the things updated in that PR) being the culprit. On closer inspection of the `[TIMING]` entries in the logs, comparing with [an older, sucessful build](https://travis-ci.com/rust-lang/rust/builds/107391619), it seems like every step is just ~25% slower on mac now. Perhaps this is a Travis issue?

cc @rust-lang/infra

**Comment by Mark-Simulacrum** [comment]
So it does look like this might be a Travis problem.

From a successful build, these are apple logs (https://api.travis-ci.com/v3/job/190975601/log.txt, https://api.travis-ci.com/v3/job/190975602/log.txt, https://api.travis-ci.com/v3/job/190975603/log.txt, https://api.travis-ci.com/v3/job/190975604/log.txt, https://api.travis-ci.com/v3/job/190975605/log.txt). Notably, the hostname varies between "***@1.worker-custom-2-75bc78f648-bb6bn.macstadium-prod-1" and "***@27571.wjb-2". I think this might indicate that the jobs are running on different physical hardware.

On a failed build, these are the apple logs (); hostname is always "***@1.worker-custom-2-75bc78f648-bb6bn.macstadium-prod-1". That this bit is the same as previously (but there is no wjb-2 host) leads me to believe we've been queued onto the same hardware.

**Comment by pietroalbini** [comment]
Contacted Travis support about this.

**Comment by Manishearth** [comment]
I've closed the tree for now

**Comment by pietroalbini** [comment]
This has been fixed.
