### ISSUE TITLE
doc: Hard to read feature name on nightly doc in dark theme

### ISSUE THREAD

**Issue by lzutao** [rust-lang/rust#59817]
The feature name [`renamed_spin_loop`](https://doc.rust-lang.org/nightly/std/hint/fn.spin_loop.html) on nightly doc is hard to read in dark theme.

![image](https://user-images.githubusercontent.com/15225902/55817309-731df380-5b1e-11e9-9006-f69e1509c549.png)

**Comment by GuillaumeGomez** [comment]
I was pretty sure I fixed this recently. That's weird...
