### ISSUE TITLE
SPMD compiling

### ISSUE THREAD

**Issue by flip111** [rust-lang/rust#59824]
SPMD compiling is said to have performance benefits over a regular C compiler. I post this because i haven't seen it mentioned anywhere on this issue tracker before. The technique might be useful to apply to the rust compiler in some way as well.

Links (performance):
https://ispc.github.io/perf.html
https://github.com/gnzlbg/aobench (comparison to a rust program)

Links (rust):
https://github.com/cgaebel/rispc "invokes the Intel's SPMD compiler"
https://github.com/theotherphil/spimdy not sure what it does

Links (general):
https://ispc.github.io/
https://github.com/ispc/ispc
https://pharr.org/matt/blog/2018/04/30/ispc-all.html
http://www.joshbarczak.com/blog/?p=1120
https://youtu.be/KzqNQMpRbac?t=2173
https://github.com/ekmett/rts
https://github.com/ekmett/spmd
https://github.com/nlguillemot/CppSPMD

**Comment by sanxiyn** [comment]
[Sierra](http://sierra-lang.github.io/), SPMD extension for C++, is especially relevant. Sierra is cited as inspired by ispc in "The story of ispc" part 10.

**Comment by Twinklebear** [comment]
I'll add a mention of my own project which helps with integrating ISPC and Rust: https://github.com/Twinklebear/ispc-rs/ . With the separate runtime and compile time crates, for using/calling and building the ISPC code respectively, you can write a Rust crate which distributes pre-compiled vectorized code written in ISPC without needing your users to have the ISPC compiler installed themselves. You do need to provide a pre-compiled binary of the library for each OS target, and should compile it to target multiple ISAs for portability. Once that's done it can be packaged with the crate and distributed, like in the [intel-tex-rs](https://github.com/gwihlidal/intel-tex-rs) crate, which provides bindings for Intel's ISPC texture compressor in Rust.

It would be really nice to have something higher-level than explicit intrinsics implemented natively in Rust, through something similar to how CUDA works now through nvcc. Even a subset of code supported through some compiler plugin where you could write something like the example below and have the operations vectorized and control flow masking handled would be fantastic. 

```rust
#[simd]
fn funnything(a: &[f32], b: &[f32], out: &mut [f32]) {
    foreach i in 0..a.len() {
        if a[i] > b[i] {
            out = a[i] - b[i];
        } else {
            out = a[i] + b[i];
        }
    }
}
```

**Comment by Mark-Simulacrum** [comment]
Closing. If someone wants to pursue this, please follow the RFC process here https://github.com/rust-lang/rfcs#before-creating-an-rfc.
