### ISSUE TITLE
Add impl From<&String> for String

### ISSUE THREAD

**Issue by jsgf** [rust-lang/rust#59827]
If a function takes `impl Into<String>` it would be nice to pass it a `&String` (say, from pattern matching) without additional friction.

https://github.com/rust-lang/rust/pull/59825 implements this.

**Comment by Stargateur** [comment]
that could hive unnecessary clone

**Comment by jsgf** [comment]
This is functionally identical to the existing `From<&str> for String` impl.

The clone would be necessary - if the receiving function needs to own the `String`, and all you have is a `&String`, then someone has to do a clone. If it didn't need to own it then it could take `&str` (or `impl AsRef<str>`). And if you had a `String` to pass in, then it would hit the no-op `impl From<T> for T` blanket impl.

**Comment by hellow554** [comment]
Do you have an example why this is useful? `&String` coerces to `&str` so there is no need to implement this.

**Comment by jsgf** [comment]
@hellow554 >  `&String coerces to &str`

No it doesn't, but it `Derefs` to it. The specific case I had was:
```
fn somefunction(s: impl Into<String>) {
    println!("a String: {}", s.into())
}

match &someenum {
SomeCase { string_field } => somefunction(string_field), // string_field: &String
...
}
```

Currently the nicest way to handle this is `somefunction(string_field.as_str())`, since there's a `From<&str> for String`.

**Comment by hellow554** [comment]
Okay, that's true. But you will have the same issue with `Vec`, `&Vec` and `&[_]`. What about that?

**Comment by jsgf** [comment]
To quote me: https://github.com/rust-lang/rust/pull/59825#issuecomment-481802640
