### ISSUE TITLE
intra-rustdoc-links: fails for re-exported module docs

### ISSUE THREAD

**Issue by ehuss** [rust-lang/rust#59833]
The links at https://doc.rust-lang.org/nightly/std/cmp/index.html are not rendering, but they work correctly on the core page (https://doc.rust-lang.org/nightly/core/cmp/index.html).

<img width="258" alt="image" src="https://user-images.githubusercontent.com/43198/55829742-40dfa800-5ac4-11e9-9ca1-ec519d1f9c6e.png">

Same with https://doc.rust-lang.org/nightly/std/str/pattern/index.html vs https://doc.rust-lang.org/nightly/std/core/pattern/index.html

**Comment by jhpratt** [comment]
Any updates on this issue? I'm running into it now, and there's no trivial workaround if the module isn't also public.

**Comment by Manishearth** [comment]
Filed https://github.com/rust-lang/rust/issues/65983 with more information on this so someone can pick it up if they want to
