### ISSUE TITLE
Python 2.7 build dependency

### ISSUE THREAD

**Issue by Raatty** [rust-lang/rust#59838]
I notice python 2.7 is specified as a dependency to compile rustc. Python2.7 will be end of life next year. Just wondering if anything is actively being done to remove this dependency.  This might be something I could work on, just need pointing the right direction.

**Comment by hellow554** [comment]
The complete bootprocess is written in python (2) afaik. Have a look at 

https://github.com/rust-lang/rust/blob/master/x.py

and start working from there on.

**Comment by Raatty** [comment]
Hmmm a better question, If i was to change all the python related files to python3 most likely breaking python2 compatability completely would that be an acceptable pr?
or is there a specific reason for the python2 choice?

**Comment by euclio** [comment]
Unfortunately LLVM currently has a hard dependency on Python 2, mostly for debuginfo tests. There's also Mac OS to consider, which doesn't ship Python 3 but ships Python 2. 

However, the Rust project is in a pretty good state for Python 3 compatibility, and the project is open to patches that fix Python 3 compatibility while preserving Python 2 compatibility. As far as I know, all scripts in the Rust repository should run with both interpreters.

**Comment by Raatty** [comment]
Tbh i havent actually done a test compile yet but if it does acually work on python3 i guess the readme is lieing then, and i checked out llvm the list python >=2.7 as a dependancy.  I got but windows and linux i can test on, i gues ill try a test build on both with using python3 and if it does work i think it be pretty safe for me to exit the readme to match llvms req of >=2.7 replcacing what it says about python 3 not working.Because I'm pretty sure 3 is greater than or equal to 2.7

**Comment by euclio** [comment]
Take a look at these lines from LLVM's CMake configuration:

https://github.com/llvm/llvm-project/blob/827aeb461c227cc5f5fd0e452aa237ae869034bd/llvm/CMakeLists.txt#L668-L682

I wouldn't say the Rust README is lying, it's just that using Python 3 is unsupported. You can try to use Python 3 to build, but there's a caveat that it might not work.

**Comment by Raatty** [comment]
I can confirm that rustc compiles successfully on windows 10 with msvc 2017 python 3.7.3. 166 tests failed tho, all complaining about failing to spawn make. I didn't see any python tracebacks tho.

**Comment by jonas-schievink** [comment]
Also note that Travis is planning to update the default Python version to 3.6. From #59873:

> On April 16th 2019, the default Python version used to run your builds
> will be updated from Python 2.7 to Python 3.6
> If your builds rely on the current default Python version 2.7, you can
> pin your project to continue using this version by specifying it in your
> `.travis.yml` file:
> ```yaml
> language: python
> python: '2.7'
> ```

**Comment by jonas-schievink** [comment]
cc @rust-lang/infra

**Comment by hellow554** [comment]
@jonas-schievink would you care to edit the title and correct the spelling mistake? ^^

**Comment by pietroalbini** [comment]
That Travis thing shouldn't affect us: they talk about the default language when you use `language: python` (and we use `language: shell`), not the preinstalled binaries.

I'll let @Mark-Simulacrum or @alexcrichton comment on `./x.py` though.

**Comment by Mark-Simulacrum** [comment]
We have long held the policy of supporting 3.x in our scripts while keeping backwards compatibility with 2.7.

Do we know what LLVMs plans are for the migration?

**Comment by Raatty** [comment]
to be honest that travis thing is just anouther sign that python3 should be used, its just going to get harder and harder as time goes on to keep using python2.

**Comment by saleemjaffer** [comment]
I can pick this up!

**Comment by Mark-Simulacrum** [comment]
I don't think we have a concrete plan yet; the next step seems to be to investigate when and how LLVM will be migrating to 3.x python.

**Comment by czipperz** [comment]
So should we update the README?  It currently says:

>`python` 2.7 (but not 3.x)

Maybe it should be revised to:

>`python` 2.7 (3.x is not supported by the LLVM project for testing)

**Comment by h-vetinari** [comment]
Seems that LLVM supporting python 3 is close: https://reviews.llvm.org/D64894

**Comment by MatthiasSaihttam** [comment]
It seems that this issue is more actively being discussed in issue #65063 and its associated PR, #66605.

**Comment by Mark-Simulacrum** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/65063.
