### ISSUE TITLE
rustdoc: link to method (with anchor) does not unfold method documentation

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#59841]
When linking directly to a method, as in https://doc.rust-lang.org/nightly/std/os/unix/process/trait.CommandExt.html#tymethod.pre_exec, that method's documentation should be opened.  I am pretty sure this used to be the case?  Currently, it just highlights the method but still requires the user to press `[+]` to actually see the documentation.

**Comment by jyn514** [comment]
This is fixed on nightly: https://doc.rust-lang.org/nightly/std/sync/struct.Arc.html#method.as_ref

(If you don't have auto-hide items set, you can turn it on in settings; it will still work even so.)
