### ISSUE TITLE
Simplify and unify rustdoc sidebar styles

### ISSUE THREAD

**Issue by lambda** [rust-lang/rust#59860]
Rustdoc's sidebar uses several visually heavyweight elements, and also has inconsistent styling between different sections.

This has been broken out of #59829 to provide smaller, actionable items that can be independently discussed and worked on. A review of rustdoc for accessibility, especially for dyslexia and attention disorders, finds that there are a number of visually distracting elements in rustdoc which can draw attention away from the main content. This should be considered along with the other issues mentioned in #59829 about the overall effect of a number of distracting elements on the page.

There are several heavyweight UI elements.

* The headings for the item in question, and the parent item, are enclosed in a black-bordered, white background box, contrasting with the background
* The crate name is bold in the parent item box
* There are high contrast horizontal rules on both sides delimiting the headings in the current page
* There are large, bold headings, with a lot of whitespace and low-contrast horizontal rules below in the parent item section
* Headings are centered, while items are left justified

In addition, the two sections have quite inconsistent styling.

* Headings in the top section are same size as individual items, but centered and delimited by heavy horizontal rules
* Headings in the bottom section are a large, bold font, with a lot of space and very light horizontal rules

<img width="200" alt="Screenshot of current item section of sidebar" src="https://user-images.githubusercontent.com/37398/55911876-8c22b500-5baf-11e9-8ef1-8ca156cfde3f.png"><img width="201" alt="Screenshot of parent item section of sidebar" src="https://user-images.githubusercontent.com/37398/55911418-9ee8ba00-5bae-11e9-8392-a286751d87a0.png">

We can compare that with the sidebar in mdBook; while they serve different purposes, it is useful to look at them together.

mdBook simply uses an outline view for nesting, without larger or bolder headings. It does have bold chapter/section numbers, which is slightly attention grabbing, but otherwise is both a simpler style and fits more content into the sidebar with less decoration.

<img width="303" alt="Screen Shot 2019-04-10 at 4 42 17 PM" src="https://user-images.githubusercontent.com/37398/55911985-bc6a5380-5baf-11e9-8e67-e26c79cb2efd.png">

Specific recommendations:

* [ ] Drop the black bordered white boxes in the sidebar
* [ ] Drop the black horizontal rules in the sidebar
* [ ] Use at most two attributes to distinguish levels of headings and individual items. Those could include:
  - Indentation, as in an outline view like mdBook
  - Font size
  - Font boldness
  - Extra whitespace
  - Single light horizontal rule
* [ ] Prefer left-aligned text to centered

**Comment by jsha** [comment]
Here's a prototype of a revised sidebar:

https://rustdoc.crud.net/jsha/cool-sidebar/std/string/struct.String.html
https://rustdoc.crud.net/jsha/cool-sidebar/std/string/index.html

https://github.com/rust-lang/rust/compare/master...jsha:cool-sidebar?expand=1
