### ISSUE TITLE
tests directory can't use 2018 module style, requires mod.rs

### ISSUE THREAD

**Issue by Clockwork-Muse** [rust-lang/rust#59871]
```
rustc --version --verbose
rustc 1.33.0 (2aa4c46cf 2019-02-28)
binary: rustc
commit-hash: 2aa4c46cfdd726e97360c2734835aa3515e8c858
commit-date: 2019-02-28
host: x86_64-pc-windows-msvc
release: 1.33.0
LLVM version: 8.0
```

Due to the fact that I prefer to keep my files small, and tests (mostly) separated from deployed code, I've been using the `tests` directory.  
Unfortunately, I can't convert the directory to the new style module declarations.  For a project that has this structure:
```
test_mod
    src
        some_module
            sub_module.rs
        lib.rs
        some_module.rs
    tests
        some_module_test
            sub_module_test.rs
        lib.rs
        some_module_test.rs
    Cargo.toml
```
.... it errors out with:
```
error[E0583]: file not found for module `sub_module_test`
 --> tests\some_module_test.rs:1:9
  |
1 | pub mod sub_module_test;
  |         ^^^^^^^^^^^^^^^
  |
  = help: name the file either sub_module_test.rs or sub_module_test\mod.rs inside the directory "tests"

error: aborting due to previous error
```

Moving `test_mod\tests\some_module_test\sub_module_test.rs` to `test_mod\tests\sub_module_test.rs` yields:

```
error[E0583]: file not found for module `sub_module_test`
 --> tests\some_module_test.rs:1:9
  |
1 | pub mod sub_module_test;
  |         ^^^^^^^^^^^^^^^
  |
  = help: name the file either some_module_test\sub_module_test.rs or some_module_test\sub_module_test\mod.rs inside the directory "tests"

error: aborting due to previous error
```
... which suggests that the layout _should_ be valid.

So, is the intention that I be able to convert to the new style?  Or is the expectation that the old style still be used here?

I'm guessing that this might be related to the fact that `test_mod\tests\lib.rs` can actually be named anything, and the code still compiles/runs - which means you should be able to remove that file, if the paths otherwise worked the same.

[example_project.zip](https://github.com/rust-lang/rust/files/3066882/example_project.zip)

**Comment by ehuss** [comment]
I think there may be some confusion about how Cargo treats the `tests` directory.  Every file in `tests/` is treated as a separate crate (called an "integration test" here).  If you want to use non-mod-rs style modules, I would suggest placing the test inside a subdirectory with a `main.rs` file.  For example:

```
tests/
tests/mytest/
tests/mytest/main.rs
tests/mytest/sub_module.rs
...etc
```

There are various other approaches.  You can explicitly list each test in `Cargo.toml` with the `[[test]]` table, and set `autotests = false` in the `[package]` section to disable Cargo's automatic `*.rs` scanning. Example:

```toml
[package]
name = "mypkg"
version = "0.1.0"
# Tell Cargo not to auto-scan for all tests/*.rs files.
autotests = false 

[[test]]
name = "mytest"
```

Then you can have `tests/mytest.rs` and it can import modules as desired.  

You can learn more about this at https://doc.rust-lang.org/cargo/reference/manifest.html#integration-tests

**Comment by Clockwork-Muse** [comment]
... Yup, I think that does it.
Thanks!

**Comment by ryanpeach** [comment]
`tests/mytest/`

I did this and it just seems... odd. Either this should be noted in the rustdoc, in the clippy errors, or changed to be consistent with a rusts `src` folder.
