### ISSUE TITLE
Inconsistent behaviour when using < and > in casted environments

### ISSUE THREAD

**Issue by Licenser** [rust-lang/rust#59872]
when comparing a type cast f64 `>` and `<` behave differently see:

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=03511939f184aad522383ddb03d25e44

While I don't want to say which is the 'right' behavior, it should be consistent over both `>` and `<` .

**Comment by jonas-schievink** [comment]
We could either reject `_ as f64 > X` as well, which would be a breaking change (and not a necessary one), or somehow find a way to allow `_ as f64 < X`, which would likely involve infinite parser lookahead. Both routes are RFC territory and at least the latter has been discussed in the past for other reasons, so closing in favor of an RFC discussion.

**Comment by Licenser** [comment]
Could we link the RFC discussion for reference?

**Comment by jonas-schievink** [comment]
The most recent one I believe is https://github.com/rust-lang/rfcs/pull/2544
