### ISSUE TITLE
Travis is updating default Python version

### ISSUE THREAD

**Issue by lzutao** [rust-lang/rust#59873]
Copied from [their changelog](https://changelog.travis-ci.com/upcoming-python-default-version-update-96873):

> On April 16th 2019, the default Python version used to run your builds 
> will be updated from Python 2.7 to Python 3.6
> 
> If your builds rely on the current default Python version 2.7, you can 
> pin your project to continue using this version by specifying it in your 
> `.travis.yml` file:
> ```yaml
> language: python
> python: '2.7'
> ```

**Comment by MSleepyPanda** [comment]
cc https://github.com/rust-lang/rust/issues/59838

**Comment by lzutao** [comment]
Try the triage bot again :))
@rustbot modify labels: +A-build and +A-rustbuild

**Comment by hellow554** [comment]
Maybe ping the infra team?

**Comment by jonas-schievink** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/59838 (I've left a comment regarding the Travis version update)
