### ISSUE TITLE
tidy should skip files based on mtime.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#59884]
We can have a stamp file that tidy writes on success, and is used to determine, on subsequent runs, which files have changed since, and only read those.
I'm getting these times right now:
```rust
Building stage0 tool tidy (x86_64-unknown-linux-gnu)
    Finished release [optimized] target(s) in 0.28s
tidy check
Build completed successfully in 0:00:03
```
In lieu of running `tidy` in parallel (which AFAIK is not possible) with the build, I want to run it before the build, but this means the time until I get errors from the compiler is delayed by a few seconds.
Skipping most of the work should allow tidy to complete much faster.

cc @alexcrichton @Mark-Simulacrum

**Comment by jyn514** [comment]
Since https://github.com/rust-lang/rust/pull/108772, tidy takes less than a second to run for me locally. I'm going to close this since I think the performance is good enough for now, but I don't mind reopening if it's still slow for you.
