### ISSUE TITLE
Windows Defender detects Trojan:Script/Foretype.A!ml

### ISSUE THREAD

**Issue by Weasy666** [rust-lang/rust#59882]
The Windows Defender detects the Trojan:Script/Foretype.A!ml when compiling the dependencies aka extern crates of my project. The defender interrupts the rust build chain and it exits with an error, stopping me from doing my work. Looks like it is in a crate named `quote`, at least that is what the error tells me -> `error: Could not compile 'quote'.`
Happened for the first time today, after doing a `rustup update` to upgrade to the newest `1.35.0-nightly (6f3e9c367 2019-04-04)`
![image](https://user-images.githubusercontent.com/11967542/55966334-7d540500-5c78-11e9-980d-716a6e144924.png)

So...is this a general rust problem? Because this didn't happen before upgrading the rust toolchain, or should i open a issue at [quote](https://github.com/dtolnay/quote)?

**Comment by jonas-schievink** [comment]
It's detecting the *compressed LLVM bitcode* of an object file as a virus. I'd file an issue with Microsoft's support for this, they're the only ones who can properly fix this.

**Comment by Weasy666** [comment]
K, thx. I will do that.
