### ISSUE TITLE
core::str::{EscapeDebug,EscapeDefault,EscapeUnicode} are not available in std

### ISSUE THREAD

**Issue by ollie27** [rust-lang/rust#59893]
I assume they should be re-exported in `std::str`.

cc @rust-lang/libs

**Comment by jonas-schievink** [comment]
cc @rust-lang/release looks like this was missed, similar to the `NonZero*` issue fixed in https://github.com/rust-lang/rust/pull/59843

**Comment by Centril** [comment]
Huh... I thought I had link-checked everything... apparently I checked the wrong thing.

**Comment by camelid** [comment]
I believe this issue should be closed as the PR to fix this was merged last year: #59908
