### ISSUE TITLE
Unexpected panic when going from debug to release build

### ISSUE THREAD

**Issue by ckaran** [rust-lang/rust#59919]
I'm using [ctor](https://crates.io/crates/ctor) to fake the creation of constants when using [noisy_float](https://crates.io/crates/noisy_float).  I've discovered that my code runs correctly in debug builds, but the same code panics in release builds.  I've created a minimal repository [here](https://github.com/ckaran/noisy_float_issue) that illustrates the problem.

**Comment by jonas-schievink** [comment]
Reproduces on 1.33.0 as well. Seems like this code in `ctor` might be missing a `#[used]`?

https://github.com/mmastrac/rust-ctor/blob/1fb201c60600ef3e7d3604132dc0d9d390f06372/ctor/src/lib.rs#L203-L206

**Comment by jonas-schievink** [comment]
Ah, it's already reported there: https://github.com/mmastrac/rust-ctor/issues/15

**Comment by jonas-schievink** [comment]
> Seems like this code in `ctor` might be missing a `#[used]`?

Yup, that fixes it, closing in favor of the upstream issue.
