### ISSUE TITLE
Possibly unintended compiler behaviour when instanciating empty structs

### ISSUE THREAD

**Issue by hargoniX** [rust-lang/rust#59927]
I am not exactly sure wether this qualifies as bug however, when I define two empty structs in two different ways, namely:
```
struct Test;
struct Test2 {}
```
And later instanciate them using the following code
```
fn main() {
    let t1 = Test {};
    let t2= Test2 {};
    let t3 = Test;
    let t4 = Test2;
}
```
The rust compiler throws the following error
```
error[E0423]: expected value, found struct `Test2`
 --> src/main.rs:8:14
  |
8 |     let t4 = Test2;
  |              ^^^^^
  |              |
  |              did you mean `Test2 { /* fields */ }`?
  |              help: a unit struct with a similar name exists: `Test`
```
Which (again I believe I'm not sure) is not supposed to happen right? There are no fields I could put in there, why should I have to type the {} in order to make an instance of it?
## Meta
Im using the rust playground at the day of creating this with a debug build and the stable rust version 1.34.0

**Comment by petrochenkov** [comment]
This is expected behavior specified by [RFC 1506](https://github.com/rust-lang/rfcs/blob/master/text/1506-adt-kinds.md).
The difference between `Test` and `Test2` is that the first one has a const-like constructor, while the second one doesn't.

**Comment by hargoniX** [comment]
I see, sorry for bothering then and thanks for the explanation
