### ISSUE TITLE
mirror-all-snapshots.py cannot download 2012-10-09-cd6f24f-macos snapshot

### ISSUE THREAD

**Issue by ivan** [rust-lang/rust#5993]
`src/etc/mirror-all-snapshots.py` tries to download http://static.rust-lang.org/stage0-snapshots/rust-stage0-2012-10-09-cd6f24f-macos-i386-7f2f2857eac33ff0792e4ea7a3ff91a09304fcab.tar.bz2 , but static.rust-lang.org serves an AccessDenied error for this snapshot.

```
downloading http://static.rust-lang.org/stage0-snapshots/rust-stage0-2012-10-09-cd6f24f-macos-i386-7f2f2857eac33ff0792e4ea7a3ff91a09304fcab.tar.bz2
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
115   231    0   231    0     0    781      0 --:--:-- --:--:-- --:--:--  4529
Traceback (most recent call last):
  File "src/etc/mirror-all-snapshots.py", line 35, in <module>
    raise Exception("bad hash on download")
Exception: bad hash on download
```

**Comment by frewsxcv** [comment]
For what it's worth, the original link @ivan (the OP) posted works for me and I'm able to download that snapshot. I think this can be closed?

**Comment by FlaPer87** [comment]
Closing as per previous comments.
