### ISSUE TITLE
Max & Min on BTreeMap are unexpectedly slow

### ISSUE THREAD

**Issue by jeremycochoy** [rust-lang/rust#59947]
Hello,

The use of iterator's `max` and `min` function do not seams to take advantage of the specific ordering of BTreeMap and looks like it is browsing the whole container.
Although it is still possible to have fast access to minimum and maximum element by using `first` and `first_back`, this is not semantically explicite and you can expect that developers may not know the subtilities regarding BTreeMap's implementation and could assume the complexity should be the same.

Here is the benchmark result
```
running 4 tests
test bench_first ... bench:           9 ns/iter (+/- 0)
test bench_last  ... bench:           8 ns/iter (+/- 0)
test bench_max   ... bench:       3,603 ns/iter (+/- 536)
test bench_min   ... bench:       3,755 ns/iter (+/- 328)
```

and here is the benchmark code:
```
#![feature(test)]

extern crate test;
#[macro_use]
extern crate lazy_static;

use test::Bencher;
use std::collections::BTreeMap;

lazy_static! {
    static ref MAP: BTreeMap<i32, i32> = {
        let mut map = BTreeMap::new();

        for i in 0..1000 {map.insert(i, i);}

        map
    };
}
#[bench]
fn bench_max(b: &mut Bencher) {

    b.iter(|| {MAP.iter().max()});
}

#[bench]
fn bench_first(b: &mut Bencher) {

    b.iter(|| {MAP.iter().next()});
}

#[bench]
fn bench_last(b: &mut Bencher) {
    b.iter(|| {MAP.iter().next_back()});
}

#[bench]
fn bench_min(b: &mut Bencher) {
    b.iter(|| {MAP.iter().min()});
}
```

I don't know the details of the trait implementation, but I think it would be very nice for the community if you can make `std::collections::btree_map::Iter` take advantage of the ordering. :)

**Comment by jonas-schievink** [comment]
Correct me if I'm wrong, but it seems like `min` just needs to forward to `next`, while `max` can call `next_back`. This is possible only because tuples are lexicographically ordered and a map cannot contain the same key twice.

This should be done for `Iter`, `IterMut`, `IntoIter` and `Keys`. While we're at it, it can also be done for `Range` and `RangeMut`.

Given that `BTreeSet` just uses `BTreeMap` internally the same likely applies there and its iterators should forward `min` and `max` to the `BTreeMap` iterators.

**Comment by lfairy** [comment]
That change would technically break backward compatibility, since the original implementations drained the whole iterator whereas the new implementation will leave most of the elements in place. I think that's fixable though – swap in an empty range before returning the result.

**Comment by lfairy** [comment]
I think there's another possible issue with this change.

Currently, `.min()` and `.map(|x| x).min()` and `.min_by_key(|x| x)` work the same way. But with this specialization, they will have wildly different performance characteristics.

Do we have a policy on when specializing an iterator method is appropriate? My concern is that if we optimize some special cases, then users might expect other similar cases to be optimized in the same way, leading to [confusion when that doesn't happen](https://stackoverflow.com/q/54035356/617159). I wonder what we can do to prevent such issues from popping up here.

**Comment by the8472** [comment]
There are other optimizations that will let you run off a performance cliff if you deviate from the happy path. E.g. vec allocation relies on the OS giving you zeroed pages to avoid initializing it, making even very large empty vecs fairly cheap. If you allocate a vec but pre-init to some other value it can suddenly get a lot slower.

Leaving performance on the table to reduce surprises does not seem like a great tradeoff. And add ing `map` to the iterator chain is a far bigger change than changing the vec initialization value.

**Comment by cuviper** [comment]
>That change would technically break backward compatibility, since the original implementations drained the whole iterator whereas the new implementation will leave most of the elements in place.

`Iterator::min()` and `max()` consume `self`, so the remains of the iterator will just drop normally. That's a no-op for the iterators by reference, and `IntoIter` should properly drop the remaining items. So I don't see a problem as far as that goes.

I think the only observable change would be if the key type has side effects in `Ord`/`PartialOrd`, but I doubt we should commit to exact guarantees in how that's called.

**Comment by lfairy** [comment]
@cuviper My concern wasn't with whether the elements of the collection get dropped or not, because (as you note) it works either way.

The difference I was thinking of was with this code:

```rust
let mut it = my_map.into_iter();
it.by_ref().min();
println!("{:?}", it.next());
```

With the old implementation, this code would print `None` as all the items have been consumed. But a specialized implementation, if written in a naive way, would only consume the first element, leaving the last line to print `Some(<second element>)` instead.

Technically the `Iterator::min` docs don't guarantee how many elements get consumed, though, so maybe we can get away with not addressing this.

**Comment by cuviper** [comment]
Calling `.by_ref().min()` uses the generic implementation for `&mut I where I: Iterator`, which wouldn't be affected by changes on the specific types here.

**Comment by scottmcm** [comment]
I recall a conversation about why we don't make `.last()` just call `.next_back()` for DEI, but I can't seem to find it to go look at what the reasoning was...

**Comment by the8472** [comment]
@scottmcm that was #60130
