### ISSUE TITLE
Dead link in src/doc/reference.md

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#59960]
In the forums I found a link to https://github.com/rust-lang/rust/blob/master/src/doc/reference.md; that document seems to have moved but the new location given there just gives an error 404.

**Comment by jonas-schievink** [comment]
It's a relative link to `reference/index.html`, which only works on the rendered output. On the [rendered version](https://doc.rust-lang.org/reference.html) of your page, the link works.

**Comment by DevQps** [comment]
@jonas-schievink I guess that means we can close this issue right?

**Comment by jonas-schievink** [comment]
Probably, yeah. If this turns out to be wrong, just let me know and I'll reopen.
