### ISSUE TITLE
HashMap / HashSet should be smarter to pickup most efficient hasher

### ISSUE THREAD

**Issue by hanabi1224** [rust-lang/rust#59969]
When key type is convertible to integer, it would be memory efficient to make hash the integer itself.

**Comment by jonas-schievink** [comment]
Shouldn't this already roughly be what happens when you `#[derive(Hash)]` on an integer newtype (so you don't even need any conversion traits)? If not, can you elaborate a bit on what exactly you're proposing here?

**Comment by hanabi1224** [comment]
@jonas-schievink It's not likely that HashMap / HashSet have already chosen the most efficient hash algorithm smartly, according to https://crates.io/crates/fnv
The Rust FAQ states that while the default Hasher implementation, SipHash, is good in many cases, it is notably slower than other algorithms with short keys, such as when you have a map of integers to other values. In cases like these, FNV is demonstrably faster.

**Comment by jonas-schievink** [comment]
The choice of SipHash is separate from choosing what data to hash and was deliberate in order to protect against Hash-DoS attacks. It is unlikely that this will be changed, and if so, would likely need an RFC, so closing in favor of that. As you have noted, you can always plug in a different hasher if you don't need the DoS protection.

**Comment by hanabi1224** [comment]
@jonas-schievink  Yes, it allows ppl to provide faster hasher, but what about memory efficiency?  Current Hasher trait always uses u64 as hash key,  for large HashMap<u16, T>, even if I implement a hasher to use u16 itself as hash key, 6 bytes are wasted for each entry, any solutions to this?  Thanks!

**Comment by jonas-schievink** [comment]
`HashMap` doesn't necessarily store the whole hash, it only has to store the key. The actual implementation might store a few bits or bytes of the hash to improve efficiency.

I agree that the `Hash` and `Hasher` traits aren't optimal though - it would be nice if they worked with more than just `u64` (you want smaller types, while larger ones also make sense for cryptographic hashes). Unfortunately this would be a breaking change, so it's not likely to happen and would definitely also need an RFC.

You can also look into building a more specialized data structure to solve your problem. Maybe a `BTreeMap` would be more efficient for your use case? If not, building a custom `HashMap` is always an option. This quickly gets pretty complicated though, so unless you're sure that you really need the performance/memory use improvement I wouldn't recommend rolling your own `HashMap`.

You can also ask the user forum at https://users.rust-lang.org/ if they have any ideas on how to make this work efficiently, but you'll have to state the problem you want to solve in more detail.
