### ISSUE TITLE
Typo in release notes causes syntax error with given example

### ISSUE THREAD

**Issue by lukaslueg** [rust-lang/rust#59961]
The example given in the [release notes](https://blog.rust-lang.org/2019/04/11/Rust-1.34.0.html) for doc-tests using `?` currently reads

```
/// ```rust
/// use std::io;
/// let mut input = String::new();
/// io::stdin().read_line(&mut input)?;
/// # Ok::<(), io:Error>(())
/// ```
fn my_func() {}
```

Notice the `io:Error`, which should read `io::Error` :-)

**Comment by jonas-schievink** [comment]
Thanks for the report. Opened a fix at https://github.com/rust-lang/blog.rust-lang.org/pull/377
