### ISSUE TITLE
Add get_path to File

### ISSUE THREAD

**Issue by heckad** [rust-lang/rust#60008]
I propouse to add `get_path` to `File` wich return path to opened file. How could it be  implemented?

**Comment by aristarh2704** [comment]
> I propouse to add `get_path` to `File` wich return path to opened file. How could it be implemented?

In Linux it's possible rename file while it opened. In this situation `get_path` returns old path to file, which will be wrong.

**Comment by jonas-schievink** [comment]
(perhaps `needs-rfc` isn't the right thing here, but this doesn't seem to be implementable on all platforms to me, so maybe we should just close?)

**Comment by the8472** [comment]
There are many cases where this can fail or is simply not available. In addition to the case already mention there also are anonymous files created with `O_TMPFILE` or `File` instances created from file descriptors that don't actually reference to files but some other objects. The path could also be too long to fit `PATH_MAX`.

At best such a function could return a `Result<Option<PathBuf>>`

**Comment by Dylan-DPC** [comment]
Closing this due to the concerns listed above
