### ISSUE TITLE
Implement `await` syntax

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#60016]
As of this writing, we have not settled the *precise* syntax we will use for `await`. However, we have decided that we want to decide -- so it makes sense to get started on implementation. **This issue is focused purely on implementation issues; the question of what syntax to use is covered in https://github.com/rust-lang/rust/issues/57640.**

**Comment by cramertj** [comment]
I've finished this, pending changes to whatever final syntax is chosen.

**Comment by estebank** [comment]
CC #51751

**Comment by cramertj** [comment]
@estebank Yeah, it fixes #51751 and #51719.
