### ISSUE TITLE
Trait alias makes method call ambigous

### ISSUE THREAD

**Issue by athre0z** [rust-lang/rust#60021]
When a trait alias to a trait with a method with the same name as a method on a struct is in scope, rustc is suddenly unable to disambiguate the trait method from the struct method.

[Playground link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=9e9f3cccd1c40d5cd5b6df57ee55e253)

```rust
#![feature(trait_alias)]

trait SomeTrait {
    fn map(&self) {}
}

impl<T> SomeTrait for Option<T> {}

trait SomeAlias = SomeTrait; // comment this out and everything works

fn main() {
    let x = Some(123);
    Option::map(x, |z| z);  // Error: multiple `map` found

    let x = Some(123);
    x.map(|z| z);  // Fine, no error.
}
```

```
error[E0034]: multiple applicable items in scope
  --> src/main.rs:13:5
   |
13 |     Option::map(x, |z| z);  // Error: multiple `map` found
   |     ^^^^^^^^^^^ multiple `map` found
   |
note: candidate #1 is defined in an impl of the trait `SomeTrait` for the type `std::option::Option<_>`
  --> src/main.rs:4:5
   |
4  |     fn map(&self) {}
   |     ^^^^^^^^^^^^^
   = note: candidate #2 is defined in an impl for the type `std::option::Option<_>`
```

**Comment by jonas-schievink** [comment]
cc https://github.com/rust-lang/rust/issues/55628

**Comment by Centril** [comment]
cc @seanmonstar, @alexreg, and @petrochenkov  -- Is `trait SomeAlias = SomeTrait;` importing the trait with higher priority than inherent items?

**Comment by petrochenkov** [comment]
>Is `trait SomeAlias = SomeTrait;` importing the trait with higher priority than inherent items?

It shouldn't do that, looks like a bug.
A method introduced into scope via trait alias (import) should behave identically to methods introduced with a trait (import), that means lower priority than inherent items.
