### ISSUE TITLE
assert! allows invalid trailing tokens in expression

### ISSUE THREAD

**Issue by adlerd** [rust-lang/rust#60024]
```rust
fn main() {
    assert!(true some extra junk, "whatever");  
    assert!(true some extra junk);                    
}
```

([Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=ff19f9ba70a1c5b936b658a4914182a7))

**Output:**
```
   Compiling playground v0.0.1 (/playground)
    Finished dev [unoptimized + debuginfo] target(s) in 0.54s
     Running `target/debug/playground`
```

**Version:**
* 1.34.0
* 1.35.0 2019-04-15 nightly (2975a3c4befa8ad610da)

**Expected:**
```
error: expected one of `.`, `;`, `?`, or an operator, found `some`
 --> src/main.rs:2:18
  |
2 |     assert!(true some extra junk, "whatever");
  |                  ^^^^ expected one of `.`, `;`, `?`, or an operator here
```

**Original report:**
https://www.reddit.com/r/rust/comments/bdbtpr/hey_rustaceans_got_an_easy_question_ask_here/el1gm0h/

**Comment by jonas-schievink** [comment]
1.26.0 is the first version that accepts this. 1.25.0 rejects it with:

```
error: no rules expected the token `some`
 --> test.rs:2:18
  |
2 |     assert!(true some extra junk, "whatever");  
  |                  ^^^^

error: no rules expected the token `some`
 --> test.rs:3:18
  |
3 |     assert!(true some extra junk);                    
  |                  ^^^^

error: aborting due to 2 previous errors
```

**Comment by jonas-schievink** [comment]
(not really a regression since *more* code now compiles)

**Comment by Centril** [comment]
Adding T-compiler since `assert!` is a built-in.

**Comment by rasendubi** [comment]
Opened https://github.com/rust-lang/rust/pull/60039—it should fix the issue.

**Comment by pnkfelix** [comment]
triage: P-medium. I'm going to assume we don't need any future-compat machinery for a bug of this nature, *unless* the crater run on PR #60039 indicates that there are occurrences of this mis-use of `assert!` in the wild.
