### ISSUE TITLE
Run automatically UI tests when opening a PR changing rustdoc/CSS/JS content

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/rust#60033]
I think the change will need to take place in https://github.com/rust-lang/highfive to make things smoother.

cc @QuietMisdreavus

**Comment by JohnTitor** [comment]
@GuillaumeGomez So, IIUC we expect it's done by this config?
https://github.com/rust-lang/highfive/blob/4966ceffefe8eba2756c84e7dc17d5cca9fa431f/highfive/configs/rust-lang/rust.json#L53

But I'm unsure if that config runs ui tests nowadays. And it seems our highfive fails to add the label when opened PRs that touch rustdoc related things, I doubt this is the cause.
Also, this is a nit point but the mention should be `@rust-highfive`, not `@highfive` imo.

**Comment by GuillaumeGomez** [comment]
It's done.
