### ISSUE TITLE
Remove `visit_subpats` parameter from `check_pat`

### ISSUE THREAD

**Issue by varkor** [rust-lang/rust#60043]
The `visit_subpats` parameter is a hack (to fix [a problem with range patterns](https://github.com/rust-lang/rust/commit/c1487145493c54b41df16eb7ffe6fdd3b82e6a78)) that should be refactored. The idea is that the state should be contained in `EllipsisInclusiveRangePatterns` instead.

This should be straightforward to fix.
1. Remove the `&mut bool` parameter from
https://github.com/rust-lang/rust/blob/6ed6f1461dd0d89c85a334f8d8ce7957611f2dfe/src/librustc/lint/mod.rs#L374
(You'll also need to update the signature of `check_pat` in `src/librustc_lint/unused.rs`.
2. Add a `check_pat_post` method with an identical signature below it.
3. Remove the `visit_subpats` condition from https://github.com/rust-lang/rust/blob/6ed6f1461dd0d89c85a334f8d8ce7957611f2dfe/src/librustc/lint/context.rs#L1166-L1173
4. Run an early lint pass for `check_pat_post` at the end.
5. Add a `Option<NodeId>` field to `EllipsisInclusiveRangePatterns` in https://github.com/rust-lang/rust/blob/6ed6f1461dd0d89c85a334f8d8ce7957611f2dfe/src/librustc_lint/builtin.rs#L1289
(Look at `DeprecatedAttr` for an example of a lint with fields.)
You'll also need to initialise it with `None` here:
https://github.com/rust-lang/rust/blob/6ed6f1461dd0d89c85a334f8d8ce7957611f2dfe/src/librustc_lint/lib.rs#L97
6. This should be replaced with an assignment of the new field in `EllipsisInclusiveRangePatterns` to `pat.id`:
https://github.com/rust-lang/rust/blob/6ed6f1461dd0d89c85a334f8d8ce7957611f2dfe/src/librustc_lint/builtin.rs#L1315
7. `check_pat` should be early-exited if the field is `Some(..)`.
8. Add a `check_pat_post` implementation to `EllipsisInclusiveRangePatterns` and reset the field to `None` if the pattern ID matches the field ID.
9. Make sure the UI tests still pass with no changes.

**Comment by stepnivlk** [comment]
hi @varkor, I'm happy to take care of this one if it's not taken already.

**Comment by varkor** [comment]
@stepnivlk: go ahead! Let me know if you have any questions or problems with the implementation! :)
