### ISSUE TITLE
Permit unused generic const parameters in type definitions

### ISSUE THREAD

**Issue by varkor** [rust-lang/rust#60047]
```rust
#![feature(const_generics)]

struct A<const N: usize>;
```
should compile, as there are no variance issues with respect to const parameters. (See https://github.com/rust-lang/rust/issues/44580#issuecomment-482797427.)

**Comment by cramertj** [comment]
Technically we could do this with `'static` types as well, right? `struct A<T: 'static>;` also doesn't have any variance issues that I can think of.

**Comment by jonas-schievink** [comment]
Related: https://github.com/rust-lang/rust/issues/59875

**Comment by Centril** [comment]
@cramertj We can do it sensibly for all type parameters by assuming that `PhantomData<T>` is there for all unused type parameters `T`. But that's a larger discussion.

**Comment by cramertj** [comment]
@Centril sorry, that's a different thing-- that's assuming a variance. I'm talking about allowing it where we don't have to assume a variance because variance can't matter.

**Comment by rkruppe** [comment]
But variance is not the only thing determined by how the type parameter is used, it also affects dropck, auto traits, and possibly more that I'm forgetting right now. So `T: 'static` doesn't remove the need to "assume" things when `T` is unused.

**Comment by cramertj** [comment]
Good point! :)
