### ISSUE TITLE
Nonsensical extra diagnostics for E0425 in static methods

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#60057]
The following code ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=dae0528ebd48ed0e5552b6f5e374de7a)):

```rust
struct A {
    banana: u8,
}

impl A {
    fn new(peach: u8) -> A {
        A {
            banana: banana // note: banana not in scope here
        }
    }
}
```

produces the following error:

```
error[E0425]: cannot find value `banana` in this scope
 --> src/lib.rs:8:21
  |
8 |             banana: banana
  |                     ^^^^^^
  |                     |
  |                     `self` value is a keyword only available in methods with `self` parameter
  |                     help: try: `self.banana`
```

First, `help` is wrong, because this is a static method and self is not available in scope. Second it is not clear why a line above `help` is talking about `self` at all.

**Comment by petrochenkov** [comment]
The original logic was to
1) recommend `self.banana`, that's a common mistake
2) then recommend adding `self` assuming it's forgotten, that's also a common mistake, which is *especially* likely if you are referring to something that is named exactly like a field.

Unfortunately, the messages were reworded and repositioned by later changes.
