### ISSUE TITLE
Can define and use async fn without feature gate on nightly

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/rust#60069]
```rust
#![feature(futures_api)]

pub struct Foo;

impl Foo {
    pub async fn foo(&mut self) {
    }
}

fn main() {
    let mut bar = Foo;
    bar.foo();
}
```

([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=9b689ceb9145b9ba586b1a923bbad4bf)) runs without error, for some reason the `async_await` feature gate is not required.

(cc @nikomatsakis @cramertj)

**Comment by pnkfelix** [comment]
@Nemo157 Just to be clear: Is there a way to access `async fn` with **no** feature gate at all? The provided example is at least opting into `#![feature(futures_api)]`.

If one must use *some* feature gate to use `async fn`, then I'd be tempted to prioritize this as P-medium, not P-high.

**Comment by pnkfelix** [comment]
(leaving nominated and unprioritized for now, at least until above question is resolved.)

**Comment by pnkfelix** [comment]
triage: Based on @eddyb's statement that our plan is to stabilize futures "soon", I'll assign this P-high priority for now. Leaving nominated due to the question I posted above.

**Comment by Nemo157** [comment]
@pnkfelix not that I could find, but `futures_api` is currently in FCP for stabilization.

**Comment by varkor** [comment]
Stabilisation issue: https://github.com/rust-lang/rust/issues/59725
