### ISSUE TITLE
Small errors in the documentation for `rchunks_exact` and `rchunks_exact_mut`

### ISSUE THREAD

**Issue by cyrozap** [rust-lang/rust#60068]
While reading through some documentation I found what appear to be a few copy/paste errors.

### `rchunks_exact`

"beginning of the slice" should be "end of the slice" here:
https://github.com/rust-lang/rust/blob/9387927ae2c0d2a283f6c48b705f25d38bb6e692/src/libcore/slice/mod.rs#L840-L841

The second " of the slice" should be removed from the end of this sentence:
https://github.com/rust-lang/rust/blob/9387927ae2c0d2a283f6c48b705f25d38bb6e692/src/libcore/slice/mod.rs#L851-L852

### `rchunks_exact_mut`

The second " of the slice" should be removed from the end of this sentence:
https://github.com/rust-lang/rust/blob/9387927ae2c0d2a283f6c48b705f25d38bb6e692/src/libcore/slice/mod.rs#L892-L893

**Comment by hellow554** [comment]
Hey @cyrozap  You already figured out the correct locations in the sourcecode, why don't you open a PR and fix that? It would be a easy first PR for you and a great opportunity to contribute to Rust.
Is that something that you can do?
