### ISSUE TITLE
Test examples in the Books.

### ISSUE THREAD

**Issue by DevQps** [rust-lang/rust#60079]
# Description

I was reading Weekly Rust and stumbled upon [this article](https://blog.guillaume-gomez.fr/articles/2019-04-13+Keeping+Rust+projects%27+README.md+code+examples+up-to-date)

It shows that examples in external Markdown files can be tested with a simple command:
```doctest!("../README.md");```

I am unsure if the examples are currently being tested, but maybe this would be a real gain in making sure that examples in "the books" are being kept up to date?

**Comment by jonas-schievink** [comment]
This is basically covered by `#[doc(include = "file")]` - https://github.com/rust-lang/rust/issues/44732

**Comment by DevQps** [comment]
@jonas-schievink I edited the title and description a little since it was a little vague compared to what I meant.

Just to make sure that I understand correctly!:

```#[doc(include = "file")]``` allows one to include an external Markdown file as documentation right? Is this already being used to test the examples that are present in the books? (The Rustbook, etc). 

I guess in order to test the examples in the books using ```#[doc(include = "file")]``` we would need to create a separate project for each book (which would then also generate docs that are present in the Markdown files that currently describe the books). Whereas if we would use ```doctest!``` we could include them as "tests" without documentation being generated for them.

I wonder what you think about this.

**Comment by jonas-schievink** [comment]
The books are using [mdBook](https://github.com/rust-lang-nursery/mdBook), which already supports running code examples using [`mdbook test`](http://rust-lang-nursery.github.io/mdBook/cli/test.html). At least the Rust book uses this in CI. Since all the books are maintained in separate repos anyways, I'll close this in favor of upstream issues/PRs if any are *not* using `mdbook test`.

**Comment by DevQps** [comment]
@jonas-schievink I completely agree then! I apologize for opening this issue without researching this more thoroughly!
