### ISSUE TITLE
rustdoc `--enable-index-page` broken

### ISSUE THREAD

**Issue by bobbobbio** [rust-lang/rust#60096]
The index page that is printed out when using the `--enable-index-page` looks broken. This is using the development version of 1.34.

There is just a bunch of junk, and links to crates are missing:
![Screenshot from 2019-04-18 14-47-59](https://user-images.githubusercontent.com/531660/56393450-52722f80-61e9-11e9-8002-ddb0ea8cd507.png)

**Comment by GuillaumeGomez** [comment]
Taking a look.
