### ISSUE TITLE
Suboptimal assembly for unsigned and signed integer division

### ISSUE THREAD

**Issue by flagello** [rust-lang/rust#60122]
```rust
#![feature(core_intrinsics)]
use std::hint::*;
use std::intrinsics::*;

macro_rules! assert {
    { $e:expr } => { 
        unsafe {
            if unlikely(!($e)) {
                unreachable_unchecked();
            }
        }
    }
}

pub fn half_u(i: u32) -> u32 {
    i * 3 / 6
}

pub fn half_s(i: i32) -> i32 {
    assert!(i >= 0);
    i * 3 / 6
}

pub fn half_s_no_assert(i: i32) -> i32 {
    i * 3 / 6
}
```

results in (same for stable) ([Godbolt](https://godbolt.org/z/mw_io8))

```asm
example::half_u:
        lea     ecx, [rdi + 2*rdi]
        mov     eax, 2863311531
        imul    rax, rcx
        shr     rax, 34
        ret

example::half_s_no_assert:
        lea     eax, [rdi + 2*rdi]
        cdqe
        imul    rax, rax, 715827883
        mov     rcx, rax
        shr     rcx, 63
        shr     rax, 32
        add     eax, ecx
        ret
```

while in Zig ([via Andrew Kelley](https://twitter.com/andy_kelley/status/1119295864097464320) (in response to C++ below)) ([Godbolt](https://godbolt.org/z/GKiYMz)) (yes, LLVM does not take advantage of the `unreachable` in `assert` (Zig‘s is equivalent to the above (without unlikely)) contrary to gcc with C++ contracts)

```zig
const std = @import("std");
const assert = std.debug.assert;

export fn half_unsigned(index: u32) u32 {
    return index*3/6;
}

export fn half_signed_no_assert(index: i32) i32 {
    return @divTrunc(index*3,6);
}

export fn half_signed_assert(index: i32) i32 {
    assert(index >= 0);
    return @divTrunc(index*3,6);
}
```

```asm
half_unsigned:
        mov     eax, edi
        shr     eax
        ret

half_signed_assert:
        mov     eax, edi
        shr     eax, 31
        lea     eax, [rax + rdi]
        sar     eax
        ret

half_signed_no_assert:
        jmp     half_signed_assert
```

while in C++ with contracts `gcc` `-std=c++2a -O3 -fcontract-semantic=default:assume` ([via John McFarlane](https://twitter.com/JSAMcFarlane/status/1119164321873813504)) ([Godbolt](https://godbolt.org/z/HRltyR))

```cpp
auto half(unsigned index)
{
    return index*3/6;
}

auto half(int index)
{
    [[assert: index>=0]];
    return index*3/6;
}
```

```asm
half(unsigned int):
        lea     eax, [rdi+rdi*2]
        mov     edx, 2863311531
        imul    rax, rdx
        shr     rax, 34
        ret
half(int):
        mov     eax, edi
        sar     eax
        ret
```

while in C++ without contracts `gcc` `-O3` ([Godbolt](https://godbolt.org/z/nl-M-p))

```cpp
auto half(unsigned index)
{
    return index*3/6;
}

auto half(int index)
{
    return index*3/6;
}
```

```asm
half(unsigned int):
        lea     eax, [rdi+rdi*2]
        mov     edx, 2863311531
        imul    rax, rdx
        shr     rax, 34
        ret
half(int):
        mov     eax, edi
        shr     eax, 31
        add     eax, edi
        sar     eax
        ret
```

**Comment by nikic** [comment]
Could you please explain in more detail what the suboptimality here is on Rust's side?

Please keep in mind that in zig integer overflow is UB, which is why in zig `x*3/6` is the same as `x>>1`, but in Rust it isn't.

**Comment by nagisa** [comment]
> Please keep in mind that in zig integer overflow is UB, which is why in zig `x*3/6` is the same as `x>>1`, but in Rust it isn't.

To expand, with Rust’s guaranteed will-not-be-UB-and-will-wrap semantics, `x * (3 / 6)` will not result in the same value as `(x * 3) / 6` for all of the `x`, which is why Rust is not able to do this.

In C++, much like with Zig, overflow for integer operations on *signed* integers is UB, but that is not the case for unsigned integers which are guaranteed to have wrapping semantics, which is why the C++’s unsigned case is the same as Rust’s.

**Comment by Mark-Simulacrum** [comment]
It seems that this is a discussion, and not a bug, as this behavior is expected. As such, I'm going to close. Thanks!
