### ISSUE TITLE
Wrong size_of for Option<fn()> values

### ISSUE THREAD

**Issue by ahomescu** [rust-lang/rust#60129]
For the following code ([Playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=691a0a12ae0989938e96174c93aa545a)):
```Rust
pub fn foo() {}

fn main() {
    let ofn = Some(foo);
    println!("sizeof:{}", ::std::mem::size_of_val(&ofn));
    
    let ofn = Some(foo as fn());
    println!("sizeof:{}", ::std::mem::size_of_val(&ofn));
}
```
the output I'm getting is
```
sizeof:1
sizeof:8
```
instead of both of them being 8. Is this intended?

**Comment by vitalyd** [comment]
This is intentional.  The first `ofn` is an `Option` wrapper over an `fn item` - that’s a ZST pointing at a concrete fn, with no dynamicism.  The second `ofn` is an fn pointer, which is a dynamic pointer at an arbitrary `fn()` (and therefore a word size).
