### ISSUE TITLE
suffixes on a tuple index are invalid 

### ISSUE THREAD

**Issue by Dylan-DPC** [rust-lang/rust#60138]
from a crater run: 
```
error: suffixes on a tuple index are invalid
[INFO] [stderr]    --> tests/common/mod.rs:133:10
[INFO] [stderr]     |
[INFO] [stderr] 133 | #[derive(Interact)]
[INFO] [stderr]     |          ^^^^^^^^ invalid suffix `usize`
[INFO] [stderr] 
[INFO] [stderr] error: proc-macro derive produced unparseable tokens
[INFO] [stderr]    --> tests/common/mod.rs:133:10
[INFO] [stderr]     |
[INFO] [stderr] 133 | #[derive(Interact)]
[INFO] [stderr]     |          ^^^^^^^^
[INFO] [stderr] 
```

crate affected: interact (0.3.3), named-tuple (0.1.2), photonix (0.1.1), serde_tuple (0.2.2), susy-codec (3.1.0), thrift (0.12.0), zeroize (0.6.0)
authors: @da-x, @flier, @bsoptei, @kardeiz,  @SUSYLABS, @apache, @tony-iqlusion
logs:
https://crater-reports.s3.amazonaws.com/beta-1.35-1/beta-2019-04-11/reg/interact-0.3.3/log.txt
https://crater-reports.s3.amazonaws.com/beta-1.35-1/beta-2019-04-11/reg/named_tuple-0.1.2/log.txt
https://crater-reports.s3.amazonaws.com/beta-1.35-1/beta-2019-04-11/reg/photonix-0.1.1/log.txt
https://crater-reports.s3.amazonaws.com/beta-1.35-1/beta-2019-04-11/reg/serde_tuple-0.2.2/log.txt
https://crater-reports.s3.amazonaws.com/beta-1.35-1/beta-2019-04-11/reg/susy-codec-3.1.0/log.txt
https://crater-reports.s3.amazonaws.com/beta-1.35-1/beta-2019-04-11/reg/thrift-0.12.0/log.txt,
https://crater-reports.s3.amazonaws.com/beta-1.35-1/beta-2019-04-11/reg/zeroize-0.6.0/log.txt

probable duplicate of #59418

**Comment by Centril** [comment]
cc https://github.com/rust-lang/rust/issues/59553

**Comment by Centril** [comment]
thrift and zeroize are the regressions that are most notable here; the others don't have notable reverse dependencies.
