### ISSUE TITLE
Example for HashMap.entry() is instead for HashMap.get()

### ISSUE THREAD

**Issue by cheako** [rust-lang/rust#60148]
https://doc.rust-lang.org/std/collections/struct.HashMap.html#method.entry

pub fn entry(&mut self, key: K) -> Entry<K, V>
[src][−]
Gets the given key's corresponding entry in the map for in-place manipulation.

Examples
use std::collections::HashMap;

let mut letters = HashMap::new();

for ch in "a short treatise on fungi".chars() {
    let counter = letters.entry(ch).or_insert(0);
    *counter += 1;
}

assert_eq!(letters[&'s'], 2);
assert_eq!(letters[&'t'], 3);
assert_eq!(letters[&'u'], 1);
assert_eq!(letters.get(&'y'), None);

**Comment by Lonami** [comment]
No, they use `entry` for filling `letters` (maps letters to their count), which is the point of the example.

To verify it, they use `[]` access for seen letters, but it would panic for `'y'` which isn't present so they must use `get`.

**Comment by jonas-schievink** [comment]
Yeah, the `or_insert` here is key - it inserts a `0` value into the map if none exists. With `get`/`insert` this would require 2 lookups instead of just one. Closing, although improvements to the docs to make them more clear are always welcome!
