### ISSUE TITLE
rust stdlib analysis contains absolute paths from appveyor and travis-CI

### ISSUE THREAD

**Issue by staktrace** [rust-lang/rust#60157]
Running something like `rustup component add rust-analysis` will download a tarball containing the `-Zsave-analysis` data for the rust stdlib crates. However, these JSON files in some cases contain absolute paths for the environment they were generated in, like `/Users/travis/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.46/src/unix/mod.rs` or similar windows paths at `C:\Users\appveyor`, or other absolute paths like `/cargo/registry/src/github.com-1ecc6299db9ec823/rustc-demangle-0.1.10/src/lib.rs`. It would be better if the analysis data had relative paths so that the analysis files can be used on other machines.

See also https://github.com/rust-lang/rls/issues/1339, /cc @Xanewok

**Comment by Xanewok** [comment]
I believe we can use [`--remap-path-prefix`](https://github.com/rust-lang/rust/issues/41555) to fix that.
 
Now we encode some of the paths (which are represented as `PathBuf`s in rls-data see https://github.com/rust-lang/rust/pull/60053#issue-271487318) as a byte vector, so it'd be also good for https://github.com/rust-lang/rust/pull/60053 to land so we can see how much of the paths are affected.

**Comment by jyn514** [comment]
The compiler should be using `/rustc/<long hash>` for these paths consistently since https://github.com/rust-lang/rust/pull/83813.

**Comment by jyn514** [comment]
Save-analysis has been [removed from the compiler](https://github.com/rust-lang/rust/pull/101841).
