### ISSUE TITLE
Shorten `Associated` to `Assoc` and rename `Method` to `AssocFn`.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#60163]
We've been moving away from the "static method" terminology, so IMO we should be more uniform with all associated items, and treat the general case of "methods that may or may not have `self`" as simply "associated functions".
"Method" terminology would then remain primarily for "method call", i.e. dot syntax for asymmetrically providing the `self` argument.

Because `AssociatedFn` is a bit long, I'd find it fitting if we shortened `Associated`, across rustc, to `Assoc`, so we end up with `AssocFn` (which only one letter longer than `Method`).
Also, when `Method` appears in the context of associated items *already* (e.g. `{Trait,Impl}ItemKind`), it can be just `Fn`.

cc @rust-lang/compiler (and in particular, I'm curious what @nikomatsakis thinks the decision process for "cosmetic" changes like these should be)

**Comment by nikomatsakis** [comment]
I think that discussing terminology like this is probably a good fit for a design meeting. I also think this particular change is a good idea.

**Comment by nikomatsakis** [comment]
I've added this to my [temporary list of design meeting ideas](https://hackmd.io/mHlmaUYMSy2SJ5HgjVoVSg?edit)

**Comment by agnxy** [comment]
Hi @eddyb @nikomatsakis I'd like to work on this if the decision has been made.

**Comment by oli-obk** [comment]
@agnxy one thing that doesn't need a decision is to change all things named `Associated...` to `Assoc...`. So you can do that already.

**Comment by eddyb** [comment]
Remaining possible renames:
* `associated` -> `assoc`, `Associated` -> `Assoc`: https://github.com/rust-lang/rust/blob/75208942f6144daac669e8e382029fc33bdce841/src/librustc/query/mod.rs#L374-L381
* `Method` -> `Fn`: https://github.com/rust-lang/rust/blob/75208942f6144daac669e8e382029fc33bdce841/src/librustc/ty/mod.rs#L203-L208
* `method` -> `fn`: https://github.com/rust-lang/rust/blob/75208942f6144daac669e8e382029fc33bdce841/src/librustc/ty/mod.rs#L197-L199


There's also things like `rustc_typeck::check::compare_method` that could be called something like `compare_assoc` but ideally it would be clearer that it validates `impl` assoc items against `trait` ones, for matching signature/type, where clauses, etc. (cc @nikomatsakis)

**Comment by nikomatsakis** [comment]
Note: as part of the effort to "extract a shared library for types", I want to do a review of naming conventions for things like this and try to reach some decisions.

**Comment by nikomatsakis** [comment]
I have mixed feelings about "shortening things" like `Assoc`. I do appreciate it being concise, but I also think that writing things out has a surprisingly nice effect on things feeling more readable overall.

**Comment by nikomatsakis** [comment]
But I think that using "associated function" instead of "method" is perhaps wise, particularly if it applies uniformly to things with `&self` and without.

**Comment by nico-abram** [comment]
@eddyb can this issue be closed? From what I understand of the discussion above all the renamings accepted were done, and the permalinks from your comment give a 404 when I try to move to the master branch because src/librustc no longer exists
