### ISSUE TITLE
Wrong display of ETA during rust instalation

### ISSUE THREAD

**Issue by q2p** [rust-lang/rust#60161]
During installation of Rust on Ubuntu 18.04 it was showing the ETA of downloadable components.
And it should've said `ETA: 3 min 4 s`, but instead it said `ETA: 3.0653233491173086 min 3.9194009470385254 s`.

It's probably because values aren't casted to an integer type or because they aren't rounded up.

Here is a screenshot of the process (look at the very bottom):
![Screenshot](https://user-images.githubusercontent.com/11664429/56479719-ff49f680-64e0-11e9-82d1-d1f913b78d11.png)

I did install rust with this command: `curl https://sh.rustup.rs -sSf | sh`

Here is `rustc --version --verbose`
```
rustc 1.35.0-beta.1 (2bc1d406d 2019-04-10)
binary: rustc
commit-hash: 2bc1d406dd5eda8bb3fd0d08a9a1a534740f9e79
commit-date: 2019-04-10
host: x86_64-unknown-linux-gnu
release: 1.35.0-beta.1
LLVM version: 8.0
```

**Comment by memoryruins** [comment]
Thanks for reporting! It is a [rustup](https://github.com/rust-lang/rustup.rs/) issue.
It was fixed in https://github.com/rust-lang/rustup.rs/pull/1699, and the patch will be included in rustup `1.18.0`.
