### ISSUE TITLE
Allow `vec[]!` macro to support combination of elements and repeat syntax

### ISSUE THREAD

**Issue by zakcutner** [rust-lang/rust#60170]
I've come across some unexpected behaviour using the `vec![]` macro. It allows the use of both an elements and repeat syntax like so...

```rust
let a = vec![1, 2, 3]; // [1, 2, 3]
let b = vec![1; 3]; // [1, 1, 1]
```

However, it doesn't appear to allow a combination of the two like this...

```rust
let c = vec![1, 2; 3]; // [1, 2, 2, 2]
```

...or even this...

```rust
let d = vec![1, 2; 3, 4]; // [1, 2, 2, 2, 4]
```

I'm unsure as to whether this is the intended behaviour of the macro and to whether this is a bug or feature request that I should create an RFC for?

It appears logical and useful to me that the macro should also support the latter cases. Apologies if this has already been brought up, I couldn't find anything about this.

**Comment by the8472** [comment]
> let c = vec![1, 2; 3]; // [1, 2, 2, 2]

It's not obvious to me that this should result in `[1, 2, 2, 2]` and not `[1, 2, 1, 2, 1, 2]`

**Comment by estebank** [comment]
Although being restrictive in the supported syntax of this macro can be annoying, it does make it much harder to accidentally introduce a hard to spot typo and maintains a 1 to 1 mapping with the only accepted syntax of array literals. Supporting `let d = vec![1, 2; 3, 4];` makes it hard to notice when skimming wether `d` contains `[1, 2, 2, 2, 4]` or `[1, 2, 3, 4]`.

The error today for this syntax is

```
error: no rules expected the token `;`
 --> src/main.rs:2:18
  |
2 | let d = vec![1, 2; 3, 4]; // [1, 2, 2, 2, 4]
  |                  ^ no rules expected this token in macro call
```

but it could in the future suggest the appropriate change (`,`) to make it work.

In general diagnostics operate in the "negative space" of the syntax, allowing us to infer intent from the context while not "polluting" the language's grammar.

**Comment by Centril** [comment]
The reason `vec![...]` exists in the first place is to emulate the syntax for array construction `[...]`.
You can see this in that `vec![1, 2, 3]` and `[1, 2, 3]` are allowed as well as `vec![42; 3]` and `[42; 3]`.
I think it would be quite unfortunate to break this symmetry and allow `vec!` to diverge from arrays, thus, if we do changes, they should be done both to arrays and to `vec!`.

However, for reasons noted by https://github.com/rust-lang/rust/issues/60170#issuecomment-485567575 and https://github.com/rust-lang/rust/issues/60170#issuecomment-485597625 it seems inadvisable to change anything to either.
