### ISSUE TITLE
Python lldb .so has wrong rpath, can't load libLLVM.so.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#60194]
The `llvm/lib/python2.7/site-packages/lldb/_lldb.so` file is loaded by the Python lldb package, and depends on `libLLVM-8-rust-1.36.0-dev-84abffda0.so`, without a relative/absolute path to it.
`libLLVM-8-*.so` is located in `llvm/lib`, so `LD_LIBRARY_PATH` or rpath are necessary.

The rpath for `_lldb.so` (obtained with `patchelf --print-rpath`) starts with `$ORIGIN/../lib`, which is wrong for something that's nested in the Python package, and should be `$ORIGIN/../../../../lib`, instead, but I don't know what's generating that rpath.

I was able to get `debuginfo` tests to work by doing:
```sh
patchelf --set-rpath $(
    patchelf --print-rpath build/x*64*linux*/llvm/lib/python2.7/site-packages/lldb/_lldb.so \
    | sed -E 's|\.\.|../../../..|'
) build/x*64*linux*/llvm/lib/python2.7/site-packages/lldb/_lldb.so
```

cc @alexcrichton @michaelwoerister

**Comment by pnkfelix** [comment]
[Visiting for wg-debugging triage](https://rust-lang.zulipchat.com/#narrow/stream/317568-t-compiler.2Fwg-debugging/topic/.5Btriage.20mtg.5D.202022-10-17/near/304476169)

@eddyb sorry, can you say more about the context of the breakage you are observing? Are you saying that you are seeing the debuginfo tests fail on your machine? Do you know what we might have to do on our own hosts to observe the same breakage?

(I know this was from three years ago, for all I know the problem has been resolved since then.)

**Comment by eddyb** [comment]
Based on the paths in this report, this is `lldb` *locally built from source*.

But AFAICT there's no way to do that nowadays (@Mark-Simulacrum may be able to shed more light on this):
https://github.com/rust-lang/rust/blob/abd77441010d74430be5c34a2e62002e578fa165/src/bootstrap/native.rs#L469-L492

I think I can cheese it by shoving `LLVM_ENABLE_PROJECTS="lldb"` into `llvm.build-config` in `config.toml`, though (and then running `./x.py build src/llvm-project`).

(Ugh, there's a weird CMake error with that complaining about some `clang-resources` thing, but changing it from `lldb` to `clang;lldb` make it build - just slower because it's building thousand of irrelevant C++ files).

---

### *(half an hour later)*

```console
$ patchelf --print-rpath build/x*64*linux*/llvm/lib/python*/site-packages/lldb/_lldb*.so | tr -t ':' '\n' | rg -v nix/store
$ORIGIN/../lib
```
So it's still using the same (wrong one) - there is no such `../lib` directory from where it's at, and `$ORIGIN/../../../../lib` would still be likely needed.

*However*, given that there's no way to cause this to be built anymore, and presumably distro-provided LLDB packages aren't as broken as building from source, we can close this as "maybe upstream bug we don't care about" (it might even be our mistake if we set some "install directory" wrong via LLVM's CMake and cause it to not generate the correct relative path?).
