### ISSUE TITLE
The `String::from` link is broken(?).

### ISSUE THREAD

**Issue by Songbird0** [rust-lang/rust#60200]
Hi,

[This anchor](https://doc.rust-lang.org/std/string/struct.String.html#method.from) doesn't seem to work.

Tested on: Firefox 66.0.3 (64 bits) and Vivaldi 2.4.

**Comment by hellow554** [comment]
Where do you have that anchor from?

**Comment by Songbird0** [comment]
At this line <https://doc.rust-lang.org/src/alloc/string.rs.html#74>.


Le mar. 23 avr. 2019 à 17:23, Marcel Hellwig <notifications@github.com> a
écrit :

**Comment by czipperz** [comment]
Should it perhaps be pointing to https://doc.rust-lang.org/std/string/struct.String.html#impl-From%3C%26%27a%20str%3E ?

**Comment by ollie27** [comment]
This looks like the same issue as #52517 and #52774.

**Comment by ehuss** [comment]
@ollie27 I'm not sure it is related to collapsing.  It looks like the fragments changed in 1.33 (it worked previously).  The new fragments look like `#method.from-2` with **-2** or some number to the individual impl.  However, it looks like this link has always been wrong.  The actual impl (`From<&str> for String`) doesn't seem to be listed anywhere? I'm a little confused.

**Comment by ollie27** [comment]
@ehuss `#method.from` is still there under [`impl From<String> for Rc<str>`](https://doc.rust-lang.org/std/string/struct.String.html#impl-From%3CString%3E) on the stable docs, it's just collapsed. The number suffixes are added if there is more than one with the same name but the first never gets a suffix. `impl From<&str> for String` is listed as [`impl<'a> From<&'a str> for String`](https://doc.rust-lang.org/std/string/struct.String.html#impl-From%3C%26%27a%20str%3E).

**Comment by ehuss** [comment]
Oh, indeed! It is not uncollapsing. I thought that had all been fixed.

Regardless, the fragment for the `str` impl method keeps changing (in stable it is `method.from-6` and in nightly it is `method.from-8`).  If the intent is to link to the correct impl, there should probably be a more stable way to do it (not sure if intra-doc links would help here).

If is desired to just link to the impl (which doesn't seem to have problems with collapsing) it could link to `impl-From%3C%26%27_%20str%3E` as @czipperz said (note it is `'_` in nightly, not `'a`, which is another worrisome point about these links getting broken over time — unfortunately this file is ignored by the linkchecker).

**Comment by czipperz** [comment]
It seems like we should have a compile time check to ensure links aren't broken.  Is this possible?

**Comment by ehuss** [comment]
@czipperz There is a linkchecker, but it is [disabled](https://github.com/rust-lang/rust/blob/bfb443eb1de484fde141fa9090a9f4291cbe60a5/src/tools/linkchecker/main.rs#L127) for String due to #32129.

**Comment by GuillaumeGomez** [comment]
I added this issue to my "I need to fix that" list.

**Comment by GuillaumeGomez** [comment]
Fixed.
