### ISSUE TITLE
refactor uses of freevars to use the upvar list

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#60205]
As part of https://github.com/rust-lang/rust/issues/53488, we need to refactor code that relies on the [`freevars`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc/ty/struct.TyCtxt.html#method.freevars) helper to figure out what things a closure captures. The freevars function just lists the "base variables" that a closure uses. This used to be equivalent to the sets of captures  but that is what we are trying to change.

@blitzerr already introduced a new field to the `TypeckTables`, [the `upvar_list`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc/ty/struct.TypeckTables.html#structfield.upvar_list). This maps from each closure to the list of upvars captured by it. These upvars are identified by a `UpvarId` -- eventually, though, they will be expected to contain additional information, so that a closure like `|| foo(&x.y.z)` might record that it captures `x.y.z` and not just `x`. 

There is a list of freevars uses [in this dropbox paper document](https://paper.dropbox.com/doc/RFC-2229-Roadmap--AbyHgfP5qKd~_4jgx3G89FG4Ag-cJKrePDCZR54T5kVbuoQk). This issue should be extended with a list of the uses. I'll also add some mentoring instructions for specific cases to try and get things rolling.

[There is a Zulip topic for discussion of this issue.](https://rust-lang.zulipchat.com/#narrow/stream/189812-t-compiler.2Fwg-rfc-2229/topic/freevar.20refactoring.20.2360205)

**Comment by nikomatsakis** [comment]
## Mentoring instructions

The first use is in `make_mirror_unadjusted`:

https://github.com/rust-lang/rust/blob/7b4f8f969caa9321b2c4881b00162ee2d68896fd/src/librustc_mir/hair/cx/expr.rs#L534

In this code, we zip two lists:

- the list of free variables `freevars` 
- the types of the upvars (captured variables) from the closure (`substs.upvar_tys(def_id, cx.tcx)`)

These lists are meant to contain the same number of items. I think we want to change this to iterate over the `upvar_uses`. To start, we need to get the `TypeckTables` -- in this particular case, those are available from `cx.tables()`. We need to index the `upvar_list` with the closure's def-id, which is available here as the variable `def_id` ([defined here](https://github.com/rust-lang/rust/blob/7b4f8f969caa9321b2c4881b00162ee2d68896fd/src/librustc_mir/hair/cx/expr.rs#L524)). So we can get the list of upvars by doing `cx.tables().upvar_list[&def_id]` instead of calling `cx.tcx.with_freevars(expr_node_id, |freevars|..)`. 

Next problem: the old code was giving us a vector of [`hir::FreeVar`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc/hir/struct.Freevar.html) values, but the `upvar_list` field will be giving us a `Vec<UpvarId>`. Hmm. However, if you look at what we do with each free variable (`fv`), you'll see that we call `capture_freevar`:

https://github.com/rust-lang/rust/blob/7b4f8f969caa9321b2c4881b00162ee2d68896fd/src/librustc_mir/hair/cx/expr.rs#L1181-L1185

which in turn uses the parameter `freevar` to... create an `UpvarId`:

https://github.com/rust-lang/rust/blob/7b4f8f969caa9321b2c4881b00162ee2d68896fd/src/librustc_mir/hair/cx/expr.rs#L1186-L1190

So, basically, we can now pass in the `UpvarId` directly, which is easier. But there is one complication: the `hir::Upvar` included a `Def` value that was given to `convert_var`. That *is* actually kind of annoying, as we no longer have "ready access" to such a `Def`. However, I think we have all the pieces we need to construct one. We want a [`Def::Upvar`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc/hir/def/enum.Def.html#variant.Upvar), which needs three things:

- a `NodeId` for the variable that was captured -- we can get this by invoking [`hir_to_node_id`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc/hir/map/struct.Map.html#structfield.hir_to_node_id) with the [`hir_id`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc/ty/struct.UpvarPath.html#structfield.hir_id) from the `UpvarId`.
- an index -- this is the index within the `upvar_list`, so we can pass that in by modifying the loop above
- the closure's node-id -- we can get that by calling [`as_local_node_id`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc/hir/map/struct.Map.html#method.as_local_node_id) on the closure def-id (which the calling function already has)

A *nicer* refactoring, though, might be to extract out the handling of upvars from [`convert_var`](https://github.com/rust-lang/rust/blob/7b4f8f969caa9321b2c4881b00162ee2d68896fd/src/librustc_mir/hair/cx/expr.rs#L970-L973) into a helper which does not expect a `Def`, but instead expects the `HirId` (not `NodeId`) of the variable being captured, index, and closure-def-id. Then we could just invoke the function directly with those things. The `convert_var` function could then invoke this helper after doing the conversions [it is](https://github.com/rust-lang/rust/blob/7b4f8f969caa9321b2c4881b00162ee2d68896fd/src/librustc_mir/hair/cx/expr.rs#L984) [already doing](https://github.com/rust-lang/rust/blob/7b4f8f969caa9321b2c4881b00162ee2d68896fd/src/librustc_mir/hair/cx/expr.rs#L989).

**Comment by JohnTitor** [comment]
I'd like to work on this.

**Comment by hbina** [comment]
Is this issue still available to be picked up? I would like to work on it.

**Comment by csmoe** [comment]
@hbina rfc-2229 is paused now, you can subscribe to this workgroup in complier-team repo to get the latest update once it restarts.

**Comment by hbina** [comment]
@csmoe oh, I didn't know thats a thing. Heading over there now!

**Comment by nikomatsakis** [comment]
I think this issue is kind of outdated, closing
