### ISSUE TITLE
Default docs.rs setting is harder to navigate

### ISSUE THREAD

**Issue by Firstyear** [rust-lang/rust#60215]
Docs.rs (after this change https://github.com/rust-lang/rust/pull/49954/files ) now collapses function definitions by default. This means that the default view a consumer of documentation now sees:

<img width="658" alt="Screen Shot 2019-04-24 at 07 56 31" src="https://user-images.githubusercontent.com/271005/56618622-84aae380-6666-11e9-9c76-34e126b8c330.png">

The small "[+]" as a symbol is really hard to notice, and so people can easily overlook that it's there - I know I would not have thought to click it unless I was told to, and I now have people asking if my libraries are documented at all (they are), but they don't see it because of the default collapse.

There are a few changes I would suggest here to make this more user-interaction and human friendly:

* The function definitions should be expanded by default and the setting should be per-user to collapse (This is this issue here).
* The item should be "[+ expand]" or "[- collapse]" - text helps people to understand the way to use an item, where currently you could over look the "[+]" as a list marker instead. https://github.com/rust-lang/rust/issues/60255
* The settings in the settings menu don't seem to "persist" so, that's a unique problem of itself. (Already open issue)

Thank you! 

EDIT: Added missing link.
EDIT 2: Clarify this issue's context and add link.

**Comment by GuillaumeGomez** [comment]
If I get approval from @rust-lang/rustdoc, I'll change the default values so the functions aren't collapsed by default.

So what do you think about it @rust-lang/rustdoc?

**Comment by Firstyear** [comment]
Thanks for this! What about changing the “[+]” element to be clearer about it’s behaviour?

**Comment by GuillaumeGomez** [comment]
That's another debate.

**Comment by Firstyear** [comment]
If that is another debate would you prefer to have another issue opened with relation to that matter?

**Comment by GuillaumeGomez** [comment]
Yes please!

**Comment by QuietMisdreavus** [comment]
Oh, i didn't realize our default was to fold up the function docs! Yes, we should leave those unfolded if there's no overriding setting.

**Comment by Mark-Simulacrum** [comment]
We appear to no longer fold functions by default (at least when looking at a random rustdoc page in private browsing to hopefully ignore any locally-stored preferences of mine).
