### ISSUE TITLE
Rename mir::Mir to mir::Body, by analogy with hir::Body.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#60229]
I think it would make more sense than the current setup, as a `Mir` coresponds to the body of a constant or function, in MIR.
Also, MIR encompasses more than just bodies - e.g. the miri value representation, but arguably the whole type/trait-system (including chalk) could be considered an integral part of "the Mid-level rustc IR".

* [x] rename the types (done in https://github.com/rust-lang/rust/pull/60928)
* [x] rename variable, argument and field names to `mir_body` where it used to be `mir`

cc @rust-lang/compiler

**Comment by marimeireles** [comment]
Hi @eddyb can I take this one this one to get my feet wet on rust?

**Comment by nikomatsakis** [comment]
I feel pretty good about this naming. As far as process, I feel like we could probably make this specific decision rather quickly. We could also try to have a dedicated nomenclature discussion, where we look over a lot of names and try to "harmonize" them, rather than doing things piecemeal. But this particular choice feels like a clear win.

**Comment by eddyb** [comment]
@marimeireles Sure, go ahead!

**Comment by imbrem** [comment]
Could I try part 2 of this, or is it already taken?

**Comment by varkor** [comment]
@imbrem: it looks like no-one else is working on this, so go ahead!

**Comment by eddyb** [comment]
Not sure it should be `mir_body` - in MIR-specific code, such as all of `rustc::mir` and `rustc_mir`, it could just be `body`, as it would be unambiguous.

**Comment by imbrem** [comment]
@eddyb I agree. I'll get to it in a few hours or so!

**Comment by imbrem** [comment]
Oh also, what do I do about the lifetime `'mir`. Just leave it as is?

**Comment by JohnTitor** [comment]
Does #61506 make the second checkbox checked? @eddyb

**Comment by imbrem** [comment]
@JohnTitor that was certainly my intention haha

**Comment by oli-obk** [comment]
Yea this looks resolved to me
