### ISSUE TITLE
Wrong span/confusing error for comma in macro pattern

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#60233]
I don't know what to make of this error.

```rust
use std::fmt::Debug;

macro_rules! check {
    ($ty:ty, $expected:expr) => {
        
    };
    ($ty_of:expr, $expected:expr) => {
        
    };
}

fn main() {
    check!(
        <str as Debug>::fmt,
        "foo",
    );
}

```

([Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=ed520a9951a2d801f5caac7803fa351d))

Errors:

```
   Compiling playground v0.0.1 (/playground)
error: expected identifier, found `,`
  --> src/main.rs:14:16
   |
14 |         <str as Debug>::fmt,
   |                ^
   |                |
   |                expected identifier
   |                help: remove this comma

error: aborting due to previous error

error: Could not compile `playground`.

To learn more, run the command again with --verbose.

```

On stable (1.34) the output is

```
error: expected identifier, found `,`
  --> src/main.rs:14:25
   |
14 |         <str as Debug>::fmt,
   |                         ^
   |                         |
   |                         expected identifier
   |                         help: remove this comma
```

**Comment by estebank** [comment]
I'm pretty sure this is fallout from the "missing comma here" suggestion for macros, that evaluates the macro again with the current arguments but adding a comma token in between the argument tokens in different combinations to see if it would be correct. My guess is that that is causing a parse error that doesn't happen for normal things than only have one token in them. We can disable the suggestion when fully qualified paths are involved.
