### ISSUE TITLE
Tracking issue for Pin::{into_inner, into_inner_unchecked} (feature `pin_into_inner`)

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/rust#60245]
This is a tracking issue for `Pin::into_inner` and `Pin::into_inner_unchecked`, proposed and implemented in https://github.com/rust-lang/rust/pull/60165.

**Comment by cramertj** [comment]
@rust-lang/libs These have been available on nightly for some time with no controversy. They're pretty useful when working with `Pin`-- do y'all have anything you'd like to see here before merging?

**Comment by alexcrichton** [comment]
Let's see! Proposed APIs look to be:

* https://doc.rust-lang.org/nightly/core/pin/struct.Pin.html#method.into_inner
* https://doc.rust-lang.org/nightly/core/pin/struct.Pin.html#method.into_inner_unchecked

@rfcbot fcp merge

**Comment by cramertj** [comment]
@alexcrichton I don't think you can r+ issues ;)

**Comment by ghedo** [comment]
Since this seems to have gone quiet again, I took the liberty of creating https://github.com/rust-lang/rust/pull/63985 to do the actual stabilization.
