### ISSUE TITLE
All links in std::cmp docs are broken

### ISSUE THREAD

**Issue by sunjay** [rust-lang/rust#60241]
https://doc.rust-lang.org/std/cmp/index.html

![image](https://user-images.githubusercontent.com/530939/56677440-91433200-668e-11e9-867f-e6420dbbe413.png)

Notice the `[` and `]` around various things in the docs. Those should be links.

**Comment by jonas-schievink** [comment]
Looks like they've been broken since they were rewritten to use the intra-doc-links feature.

**Comment by ehuss** [comment]
See #59833. I think this is because the module is reexported and the intra-doc-links don't handle that.

**Comment by sunjay** [comment]
Heh. @ehuss I seem to be catching many of the same issues as you. :smile: 

Closing as duplicate. Thanks everyone!
