### ISSUE TITLE
Tracking issue for `Option::flatten`

### ISSUE THREAD

**Issue by ethanboxx** [rust-lang/rust#60258]
[PR](https://github.com/rust-lang/rust/pull/60256)

**Comment by elahn** [comment]
I was trying to `flat_map()` and found `map().flatten()` does the trick. This has been on nightly for 4 months, can we stabilise it?

**Comment by ethanboxx** [comment]
@Centril Helped me get this merged. What is the stabilization process?

**Comment by Centril** [comment]
@ethanboxx I'd just file a PR to stabilize it and we'll ask T-libs to FCP.

**Comment by Dylan-DPC** [comment]
The feature has been stabilised. Closing this. Thanks :)
