### ISSUE TITLE
Someone should rewrite Docker and Kubernetes in Rust.

### ISSUE THREAD

**Issue by tan20290** [rust-lang/rust#60268]
Someone do it.

**Comment by sfackler** [comment]
General discussions are better left for reddit.com/r/rust or users.rust-lang.org.

**Comment by plantenos** [comment]
Please stand by for an upcoming release of Kubernetes, Docker and LXC/D in rust

**Comment by AntonSmolkov** [comment]
And elasticsearch/lucene, please😂

**Comment by AbhimanyuAryan** [comment]
Lol

**Comment by leon3s** [comment]
https://github.com/nxthat/nanocl

**Comment by dengyunsheng250** [comment]
and Redis. please
