### ISSUE TITLE
Stable rustc always panics on arm/musl

### ISSUE THREAD

**Issue by dragonmaus** [rust-lang/rust#60297]
Stable rust is unable to compile anything on `arm-unknown-linux-musleabihf` (Raspberry Pi gen 1 running Void Linux).

Even a simple program like the following:
```rust
fn main() {
    println!("Hello, world!");
}
```
throws an "internal compiler error: unexpected panic" at "already borrowed: BorrowMutError".

## Meta

`rustc --version --verbose`:
```
rustc 1.34.0
binary: rustc
commit-hash: unknown
commit-date: unknown
host: arm-unknown-linux-musleabihf
release: 1.34.0
LLVM version: 8.0
```

Backtrace:
```
thread 'rustc' panicked at 'already borrowed: BorrowMutError', src/libcore/result.rs:997:5
stack backtrace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: std::panicking::rust_panic_with_hook
   6: <unknown>
   7: rust_begin_unwind
   8: core::panicking::panic_fmt
   9: <unknown>
  10: syntax::attr::is_known
  11: <unknown>
  12: <unknown>
  13: <syntax::ext::expand::InvocationCollector<'a, 'b> as syntax::mut_visit::MutVisitor>::flat_map_item
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <syntax::ext::expand::InvocationCollector<'a, 'b> as syntax::mut_visit::MutVisitor>::flat_map_item
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: syntax::ext::expand::MacroExpander::expand_crate
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: rustc_driver::driver::compile_input
  26: <unknown>
  27: <unknown>
  28: rustc_driver::run_compiler
  29: <unknown>
  30: __rust_maybe_catch_panic
  31: <unknown>
  32: <unknown>
  33: <unknown>
query stack during panic:
end of query stack

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.34.0 running on arm-unknown-linux-musleabihf
```

**Comment by mati865** [comment]
Probably not musl specific: https://github.com/rust-lang/rust/issues/57665

@dragonmaus can you try with nightly? Hopefully it will have better debug info.

**Comment by dragonmaus** [comment]
@mati865 Rustup steadfastly refuses to work on this machine at all*, and -nightly is not available in the distro repositories, so I do not think I can be very helpful with that.

*The one from rustup.rs fails when it tries to run the rustup-init it downloads (with nothing more than a generic OS error message), and the one from the distro repositories complains as follows:
```
error: Pre-checks for host and toolchain failed: Provided host 'arm-unknown-linux-musleabihf' couldn't be
converted to partial triple
If you are unsure of suitable values, the 'stable' toolchain is the default.
Valid host triples look something like: arm-unknown-linux-musleabihf
```
so I can make neither heads nor tails of it.

**Comment by pnkfelix** [comment]
triage: not sure what tier the given platform is, so I'm not assigning a priority to this yet. Leaving nominated for discussion.

**Comment by pietroalbini** [comment]
`arm-unknown-linux-musleabihf` is tier 2.

**Comment by nikomatsakis** [comment]
triage: P-high

Seems like a pretty important problem to get to the bottom of.

**Comment by pnkfelix** [comment]
nominating for discussion at meeting, hopefully to find someone with access to arm/musl to take this  on.

**Comment by pnkfelix** [comment]
triage: it is silly to act like this platform is getting the attention of a P-high bug.

I'm going to leave this nominated (in hopes of finding someone to take it on), but downgrade from P-high to P-medium, because I need to get the set of P-high issues under control.

**Comment by pnkfelix** [comment]
(also, can we at least check what our behavior is for this target under QEMU?)

**Comment by pnkfelix** [comment]
Someone said they heard on twitter that it's working now. Closing!
