### ISSUE TITLE
What does ! before a trait mean?

### ISSUE THREAD

**Issue by sci4me** [rust-lang/rust#60308]
For example: https://doc.rust-lang.org/src/std/sync/mpsc/mod.rs.html#495

**Comment by Centril** [comment]
It denotes that `Send` is *not* implemented (i.e. a "negative" implementation).
See https://github.com/rust-lang/rfcs/blob/master/text/0019-opt-in-builtin-traits.md#default-and-negative-impls for more details.

**Comment by sci4me** [comment]
Thanks!
