### ISSUE TITLE
miri component gets shipped even though the tests fail

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#60301]
Looking at https://rust-lang.github.io/rustup-components-history/, it seems like Miri is getting shipped as a rustup component even though the tests fail. Unfortunately, Miri is currently entirely usable, so it'd probably be better if it did not get shipped in this state. Is that something we can do?

Cc @oli-obk

**Comment by RalfJung** [comment]
@rust-lang/infra what would be the best place to change this? I think I'd prefer Miri not to be shipped at all when the tests fail; I'd rather people stick to an old-but-working Miri than to a new-but-broken one.

I found https://github.com/rust-lang/rust/blob/master/src/ci/docker/x86_64-gnu-tools/checktools.sh but that does not seem to decide if a component gets built for distribution or not.

**Comment by oli-obk** [comment]
https://github.com/rust-lang/rust/blob/6312b89fdabce0aedf613391266e08c0deef2324/src/bootstrap/dist.rs#L1368-L1369 seems to suggest that it is supposed to work as you describe that it should be working. Since it obviously doesn't and I can't see how that comment could be true from looking at the source, I'm guessing this is some refactoring fallout. I'll dig a little into git blame

**Comment by oli-obk** [comment]
I found it. The comment was added for rls in https://github.com/rust-lang/rust/commit/686c1015cfa341748b6de20114e8caba4626931b but then the code making the comment true was removed later

**Comment by RalfJung** [comment]
See https://github.com/rust-lang/rust/pull/61656#issuecomment-500112801 for why this is hard to fix: the `dist` builders don't even run the tool tests, so they cannot know if the tests pass. :/

Also, that's probably for the better actually, as the "tools" builder sets --cfg miri to be more Miri-friendly and we don't want that in the release artifacts.

**Comment by RalfJung** [comment]
One (crazy?) thing we could so is have the dist builders query the toolstate repo to figure out if the tests are passing...

**Comment by kennytm** [comment]
That will either retrieve an outdated toolstate or will need to block until the toolstate is uploaded ...

**Comment by RalfJung** [comment]
Without blocking it would lag behind by 1 merged PR, yes.

**Comment by mati865** [comment]
@RalfJung would it be possible to add some kind of build assert so Miri fails on `dist` builders when Rust internals change too much?

**Comment by RalfJung** [comment]
Well `dist` builders already know when Miri fails to build because internals change too much. The issue is things that make Miri still compile but break the test suite.

**Comment by RalfJung** [comment]
@kennytm would it be possible to at least change the logic that opens issues such that for Miri, it opens an issue like https://github.com/rust-lang/rust/issues/60533 when the tests fail? I could also try to implement that if you point me to the right place.

So far we have had zero cases of Miri tests spuriously failing.

**Comment by mati865** [comment]
That should be easy to do: https://github.com/rust-lang/rust/blob/0e4a56b4b04ea98bb16caada30cb2418dd06e250/src/tools/publish_toolstate.py#L152

**Comment by RalfJung** [comment]
Gave it a shot at https://github.com/rust-lang/rust/pull/61938

**Comment by RalfJung** [comment]
@Centril had an interesting idea: can't we do the "don't ship broken tools" as part of a post-processing step? We anyway do some little amount of work when a commit hits `master` (as opposed to `auto`), such as actually updating the toolstate repo. So maybe that could also either delete the broken components from the S3 bucket, or else generate a file to be put into the S3 bucket that says which of the components are *really* there so that the broken ones can be considered "not there"?

@kennytm do you think something like that would be possible?

**Comment by RalfJung** [comment]
Thinking about this again, probably the most natural place to do this is in the [code that turns CI artifacts into nightly releases](https://github.com/rust-lang/rust-central-station/tree/master/promote-release). That could "just" also check the toolstate database for the commit it is promoting, and then (possibly only for certain tools) just not add them to the nightly if their toolstate is not green.

**Comment by RalfJung** [comment]
This is biting us again right now, where CI knows that Miri is broken but we ship the component anyway, leading to CI failures in downstream projects that have Miri in their CI.

**Comment by RalfJung** [comment]
My PR is [getting reverted](https://github.com/rust-lang/rust/pull/64543) because I was incorrectly assuming that all commits have their toolstate recorded in the toolstate repo. Reopening.

**Comment by RalfJung** [comment]
FTR, for testing `build-manifest`, I downloaded some artifacts:
```
mkdir dist && cd dist
wget 'https://s3-us-west-1.amazonaws.com/rust-lang-ci2/rustc-builds/5670d048c0f88af9976b5505c7853b23dd06770d/rust-nightly-x86_64-unknown-linux-gnu.tar.gz'
wget 'https://s3-us-west-1.amazonaws.com/rust-lang-ci2/rustc-builds/5670d048c0f88af9976b5505c7853b23dd06770d/miri-nightly-x86_64-unknown-linux-gnu.tar.gz'
```
then I edited my `config.toml`:
```
# somewhere in the existing part
channel = "nightly"

# add at the bottom
[dist]
sign-folder = "dist"
upload-addr = "dist"
```
and finally I ran
```
BUILD_MANIFEST_DISABLE_SIGNING=1 ./x.py dist hash-and-sign
```
This produces stuff in `build/dist`.

**Comment by RalfJung** [comment]
So @pietroalbini @kennytm  looks like we have logic in `change_toolstate` that specifically does not commit to the toolstate repo if nothing changed:

https://github.com/rust-lang/rust/blob/5670d048c0f88af9976b5505c7853b23dd06770d/src/ci/docker/x86_64-gnu-tools/checktools.sh#L112-L113

Unfortunately, this means that we cannot easily fetch the toolstate of the to-be-produced release in build-manifest, which caused my [original approach](https://github.com/rust-lang/rust/pull/64451) to fail.

Would it be okay for you to change this logic to record the toolstate of *all* commits in the toolstate repo? Or would you prefer if I try to find another approach for solving this issue? Right now I am somewhat out of ideas though if we cannot even use the toolstate repo to communicate this information.

**Comment by mati865** [comment]
Wouldn't it be simpler to save list of "good" components to something like `available_components` and upload it alongside tarballs?
Running `curl 'https://s3-us-west-1.amazonaws.com/rust-lang-ci2/rustc-builds/<hash>/available_components'` would show what you need.

**Comment by RalfJung** [comment]
I guess we could upload the two JSON files from the two tool runners somehow? Not sure which would be the right places to hook for that, though.

**Comment by RalfJung** [comment]
Status: blocked on https://github.com/rust-lang/rust/pull/65274 which is blocked on https://github.com/rust-lang/rust/pull/65202

**Comment by pietroalbini** [comment]
This seems to be finally fixed! Today nightly was shipped with #65274, and everything looks normal :tada:

**Comment by RalfJung** [comment]
Miri is "test-fail" now, so with the next nightly we should be able to see if indeed it gets removed from rustup as it should.

**Comment by pietroalbini** [comment]
Confirmed it's working! On `nightly-2019-11-08` miri is missing.
