### ISSUE TITLE
Empty doc tests should be linted

### ISSUE THREAD

**Issue by Phrohdoh** [rust-lang/rust#60319]
Run tests for https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=8ac29ea8121d53906e7a77cd01ccbe70 and you'll get the following diagnostic:

```
warning: invalid start of a new code block
 --> /playground/src/lib.rs:1:1
  |
1 | //! Hello
  | ^^^^^^^^^
```

But to be as helpful as possible the diagnostic should, if possible, point to the start of the invalid code block.

**Comment by euclio** [comment]
Hm, this error was actually removed in #60140 because I didn't think it could actually be produced. Looks like it was possible to trigger by writing an empty doc test.

On master, this code produces a passing doc test now. IMO, that is the correct behavior.

**Comment by Phrohdoh** [comment]
> There should probably be a test for it.

I agree completely.

Would this mean re-introducing this message but improving the message (replacing _invalid_ with _empty_ or something similar)?

I believe that is the best course of action as warning on an empty code block is completely valid and desired IMO.

**Comment by euclio** [comment]
The original code only caught this incidentally. I think this check would make more sense as a rustdoc lint instead of a hard warning. Could be added to `check-code-block-syntax` or a new pass entirely.

**Comment by euclio** [comment]
@Phrohdoh could you edit this issue to reflect the current status? It should be something like "Empty doc tests should be linted".

**Comment by tommilligan** [comment]
@euclio @Phrohdoh I'd like to take this issue - should have a PR this week for review.
