### ISSUE TITLE
borked looking src files in docs.rs

### ISSUE THREAD

**Issue by yaahallo** [rust-lang/rust#60342]
The html view of the source files from tokio-trace seem to be coming out malformed.

https://docs.rs/tokio-trace/0.1.0/src/tokio_trace/macros.rs.html#331-403

![Screenshot from 2019-04-27 14-00-01](https://user-images.githubusercontent.com/1993852/56855092-df0da380-68f5-11e9-8b36-95a7a00de143.png)

This can  be reproduced locally by cloning tokio then running

```sh
cd tokio/tokio-trace
cargo doc --open
```

and clicking on pretty much any random src button it seems.

Broken in both firefox and chrome. Though I've only tested it on fedora 29.

**Comment by Mark-Simulacrum** [comment]
I can't reproduce this locally with the beta compiler so I'm closing - docs.rs probably just needs a rebuild (easiest to obtain via a republish).
