### ISSUE TITLE
mpsc may be crashed as tail is some

### ISSUE THREAD

**Issue by qiangshou007** [rust-lang/rust#60345]
https://github.com/rust-lang/rust/blob/938d4ffe16c4430e1dcede570b06227114cb73d5/src/libstd/sync/mpsc/mpsc_queue.rs#L97

tail may be some as hold the shadow value when concurrent

**Comment by steveklabnik** [comment]
Triage: no change

**Comment by jyn514** [comment]
Should be fixed by https://github.com/rust-lang/rust/pull/93563.
