### ISSUE TITLE
tuple destruction to initialized variables

### ISSUE THREAD

**Issue by BO41** [rust-lang/rust#60343]
(I hope I am in the right repo and this isn't a duplicate or a dump question :)

Currently (using rust `1.34.1`) destructing a tuple is only possible to newly created variables.
```rust
let mut foo = 0;
let mut bar = 1;

(foo, bar) = (2,3);
```
This code fails with following error.
```  
 |
 | (foo, bar) = (2,3);
 | ^^^^^^^^^^^^^^^^^^ left-hand of expression not valid
```
---
But this is valid.
```rust
let mut foo = 0;
let mut bar = 1;

let test = (2,3);

foo = test.0;
bar = test.1;
```

I think it would be **intuitive** to destruct into already known variables rather than having to create a new one.

**Comment by varkor** [comment]
This is https://github.com/rust-lang/rfcs/issues/372.
