### ISSUE TITLE
Tidy: Enforce that groups in declare_feature! are sorted by version number

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#60361]
In the `declare_features! ( ... )` list in `src/libsyntax/feature_gate.rs`, enforce that groups (internal, user-facing, ...) of features are ordered by version number with the newest last. The groups will need to be scoped in some way with a comment, e.g. `// feature group START` + `feature group END`.

This makes it easier to see what things are newer and gives a better overview when considering stabilization.

cc @oli-obk 
cc https://github.com/rust-lang/rust/pull/60354
cc https://github.com/rust-lang/rust/pull/60362

**Comment by rasendubi** [comment]
I would like to work on this. I think I'll be able to add the feature to tidy, but I'll need help for splitting features into groups.
