### ISSUE TITLE
Strange `unreachable` warning in `Future`

### ISSUE THREAD

**Issue by sbwtw** [rust-lang/rust#60394]
[Code](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=2aa6652b80ed39efe9a8759fcd8733dd):
```rust
use futures::future;
use futures::Future;

fn f() -> impl Future<Item = (), Error = ()> {
    future::ok(unimplemented!())
}

fn main() {
    let s = f();

    tokio::run(s);
}

```
And when build with `cargo build`, It will says the `future::ok(unimplemented!())` is unreachable expression.
but when `cargo run`, I got a panic: `thread 'main' panicked at 'not yet implemented', src\main.rs:5:16`. the `unimplemented!()` macro is worked.

**Comment by Centril** [comment]
What happens here is that the function call `future::ok(...)` is unreachable. The macro "call" itself isn't.
We can see this with:
```rust
use futures::{future, Future};

fn f() -> impl Future<Item = (), Error = ()> {
    let _u = unimplemented!();
    future::ok(_u)
}

fn main() {
    tokio::run(f());
}
```

-------------

cc @estebank Can we highlight the issue like so perhaps?
```rust
warning: unreachable expression
 --> src/main.rs:4:5
  |
4 |     future::ok(unimplemented!())
  |     ^^^^^^^^^^^----------------^
```

**Comment by estebank** [comment]
I think this will be a side effect of a long standing paper cut, where we point at the method or entire statement instead of the argument that caused a problem. I can take a look, but I don't think this will be fixed in the near term.
