### ISSUE TITLE
ICE with existential_type feature

### ISSUE THREAD

**Issue by phil-opp** [rust-lang/rust#60407]
Code ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=3647f89ce24af3db7c673dbc4e02f556)):

```rust
#![feature(existential_type)]

existential type Debuggable: core::fmt::Debug;

static mut TEST: Option<Debuggable> = None;

fn main() {
    unsafe { TEST = Some(foo()) }
}

fn foo() -> Debuggable {
    0u32
}
```
The `core::fmt::Debug` trait is just an example, the error occurs with every trait I tried.

Error:

```
error: internal compiler error: broken MIR in DefId(0/0:4 ~ playground[be34]::TEST[0]) (bb0[0]): equate_inputs_and_outputs: `std::option::Option<Debuggable>==std::option::Option<Debuggable>` failed with `NoSolution`
 --> src/main.rs:5:1
  |
5 | static mut TEST: Option<Debuggable> = None;
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', src/librustc_errors/lib.rs:355:17
```

<details>
<summary>Backtrace</summary>

```
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: rustc::util::common::panic_hook
   5: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:478
   6: std::panicking::begin_panic
   7: <rustc_errors::Handler as core::ops::drop::Drop>::drop
   8: core::ptr::real_drop_in_place
   9: <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop
  10: core::ptr::real_drop_in_place
  11: rustc_interface::interface::run_compiler_in_existing_thread_pool
  12: std::thread::local::LocalKey<T>::with
  13: scoped_tls::ScopedKey<T>::set
  14: syntax::with_globals
query stack during panic:
end of query stack
```
</details>

Possibly related to https://github.com/rust-lang/rust/issues/54899, https://github.com/rust-lang/rust/issues/53678, and https://github.com/rust-lang/rust/issues/60371#issuecomment-487679827. Feel free to close this if this is a duplicate. I thought this might be useful for debugging because it (unlike the two other issues) does not use generators or futures.

cc @oli-obk (assigned to the two other issues)

**Comment by Centril** [comment]
Proposed prio: P-Low.

**Comment by oli-obk** [comment]
heh. I don't think using `existential type`s for anything but functions counts as a defining use. You can work around this ICE by placing `foo` and `Debuggable` into their own module: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=f244de8aa281ac5960be54980e5ba03f

**Comment by DutchGhost** [comment]
I guess you hit the same as this: https://github.com/rust-lang/rust/issues/60371#issuecomment-487679827

**Comment by phil-opp** [comment]
@oli-obk 

> You can work around this ICE by placing `foo` and `Debuggable` into their own module:

Interesting! I'm glad to see that my approach works in principle.

**Comment by phil-opp** [comment]
@DutchGhost This seems quite similar indeed. I added the link to the issue description. Since I'm not sure if this is really the same I will keep this issue open for now.

**Comment by pnkfelix** [comment]
triage: P-high due to ICE; removing nomination.

**Comment by pnkfelix** [comment]
this should block #34511

**Comment by pnkfelix** [comment]
triage: Downgrading to P-medium based on this being an unstable feature. (Though arguably it is a feature that is so close to stabilization that we should re-update this to P-high in the near term.)

**Comment by Aaron1011** [comment]
This no longer ICEs on the latest nightly.
