### ISSUE TITLE
Move async/await UI tests into a folder

### ISSUE THREAD

**Issue by cramertj** [rust-lang/rust#60418]
We want to move all async / await tests (run-pass, ui, ...) into a single folder under `src/test/ui/async-await` to facilitate overview and the eventual stabilization report. Organization beyond that into sub-folders would also be useful to further make everything clear and reviewable.

**Comment by Centril** [comment]
Labeling as "blocking" since this should be done as part of the run up to the report.

**Comment by varkor** [comment]
Fixed in https://github.com/rust-lang/rust/pull/61138.
