### ISSUE TITLE
Some features were removed instead of deprecated/stabilized

### ISSUE THREAD

**Issue by jethrogb** [rust-lang/rust#60427]
From @varkor in https://github.com/rust-lang/rust/pull/52644#issuecomment-488143743:

> it seems some past features were simply removed outright rather than being deprecated as they should be. ... I think we'll need to retroactively make these features deprecated.

This applies at least to the following features:

* collections
* str_char
* unicode
* alloc

There might be others.

**Comment by Centril** [comment]
If they were stabilized they should be added to the `accepted` list and otherwise to the `removed` list.

**Comment by rasendubi** [comment]
1. All of the mentioned flags are lib flags. Is it OK to add them to `feature_gate.rs`? (I am not sure as these are "lang" features and might be handled differently.)

2. e.g., `fs_read_write` was stabilized as `fs_read_write_bytes` (0600d0f38d4998f1cacb3b97408224a0ee350db4). Should we add the old name? as `accepted`?

3. A part of `alloc` was renamed to `alloc_prelude` (without stabilization) (5d1022ad7b82168aee243d2adcbd83d1e886586f). The rest was stabilized as `alloc` (fc928a18bad0b6aa275a6908351b164f6f4abcd6). @jethrogb are you sure you get an error when using `alloc`?

(If anyone feels like doing code archeology, a simple `git log -p -S '"str_char"'` seems to give pretty good results.)

**Comment by jethrogb** [comment]
> 2. e.g., fs_read_write was stabilized as fs_read_write_bytes (0600d0f). Should we add the old name? as accepted?

I think they should be added as removed

> 3. ... @jethrogb are you sure you get an error when using alloc?

I thought I was with some nightly version between nightly-2018-08-14 and nightly-2019-04-27, but I can't reproduce this right now.

**Comment by varkor** [comment]
> 1. All of the mentioned flags are lib flags. Is it OK to add them to feature_gate.rs? (I am not sure as these are "lang" features and might be handled differently.)

Yeah, I'm not sure whether we want to flag removed libs features differently. It'd probably be nice to keep a record, but I'm not sure if the difference is valuable.

> 2. e.g., fs_read_write was stabilized as fs_read_write_bytes (0600d0f). Should we add the old name? as accepted?

I agree with @jethrogb: we should probably mark it as removed. (Alternatively, we could track "renamings of feature flags", like we do for lints, so we could produce better diagnostics.)

**Comment by Centril** [comment]
It's rather weird to add libs features to the language feature list. I also think it's not the end of the world to just throw away the removed feature gate list entirely; it's essentially technical debt that we are monotonically increasing at the moment. The only think that we'd need to do is to not error. Adding these features, which seemingly hasn't bothered anyone for a long time, only for the purposes of consistency seems to be a weak motivation.

**Comment by Enselic** [comment]
Triage: Since many years has passed now the risk of messing with feature flags seems greater than the benefit of fixing them (and I'm unsure exactly what that means atm tbh). I'll go ahead and close this with this motivation from above comment:

>  Adding these features, which seemingly hasn't bothered anyone for a long time, only for the purposes of consistency seems to be a weak motivation.
