### ISSUE TITLE
FailureNote JSON value is not useful

### ISSUE THREAD

**Issue by ehuss** [rust-lang/rust#60425]
Currently the `FailureNote` diagnostic level [serializes to the empty string](https://github.com/rust-lang/rust/blob/5b7baa53c91d7c33b925fc8aec553e3521548a07/src/librustc_errors/lib.rs#L837).  This results in JSON messages containing `level: ""`, which I'm not sure how to interpret.  

This was added in #48684, though reading that PR I can't really figure out why it was added and how it relates to compiletest changes.

An easy way to see this is to trigger a diagnostic that prints "For more information…", for example:

```rust
// E0005
let Some(_y) = Some(1);
```

will emit a JSON value like this:

```json
{
  "message": "For more information about this error, try `rustc --explain E0005`.",
  "code": null,
  "level": "",
  "spans": [],
  "children": [],
  "rendered": "For more information about this error, try `rustc --explain E0005`.\n"
}
```

The empty string is not very descriptive of how to handle the message.  I would suggest having it serialize to something more deliberate, such as "failure-note".  I can't really tell what the intent of `FailureNote` is, so it's hard to say what it should be.  

cc @GuillaumeGomez who might know more.

**Comment by GuillaumeGomez** [comment]
Serialising as "failure-note" sounds good to me. Weird we didn't do it beforehand...

**Comment by afnanenayet** [comment]
I'd like to pick this up
