### ISSUE TITLE
Hide `found a, expected b` label when suggestion is provided

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#60430]
I'm ambivalent about this, but @oli-obk pointed this case out in https://github.com/rust-lang/rust/pull/60159#discussion_r277263162

When providing a suggestion for a type error that would fix the problem, we have the following output:

```
error[E0308]: mismatched types
  --> $DIR/type-mismatch-struct-field-shorthand-2.rs:5:19
   |
LL |     let _ = RGB { r, g, c };
   |                   ^
   |                   |
   |                   expected f64, found f32
   |                   help: you can convert an `f32` to `f64`: `r: r.into()`
```

we could change it to

```
error[E0308]: mismatched types
  --> $DIR/type-mismatch-struct-field-shorthand-2.rs:5:19
   |
LL |     let _ = RGB { r, g, c };
   |                   ^ help: you can convert an `f32` to `f64`: `r: r.into()`
```

but I'm not sure wether that is a good move.

**Comment by Centril** [comment]
I think a good diagnostic consists at minimum of:
1. what went wrong,
2. how you can fix it

but this move would get rid of 1. so I'm not a fan.
