### ISSUE TITLE
Tracking issue for floats ↔ bytes conversions

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#60446]
~https://github.com/rust-lang/rust/pull/58756~ #62366 adds:

```rust
impl f32 {
    pub const fn to_be_bytes(self) -> [u8; 4] { self.to_bits().to_be_bytes() }
    pub const fn to_le_bytes(self) -> [u8; 4] { self.to_bits().to_le_bytes() }
    pub const fn to_ne_bytes(self) -> [u8; 4] { self.to_bits().to_ne_bytes() }
    pub const fn from_be_bytes(bytes: [u8; 4]) -> Self { Self::from_bits(u32::from_be_bytes(bytes)) }
    pub const fn from_le_bytes(bytes: [u8; 4]) -> Self { Self::from_bits(u32::from_le_bytes(bytes)) }
    pub const fn from_ne_bytes(bytes: [u8; 4]) -> Self { Self::from_bits(u32::from_ne_bytes(bytes)) }
}

impl f64 {
    pub const fn to_be_bytes(self) -> [u8; 8] { self.to_bits().to_be_bytes() }
    pub const fn to_le_bytes(self) -> [u8; 8] { self.to_bits().to_le_bytes() }
    pub const fn to_ne_bytes(self) -> [u8; 8] { self.to_bits().to_ne_bytes() }
    pub const fn from_be_bytes(bytes: [u8; 8]) -> Self { Self::from_bits(u64::from_be_bytes(bytes)) }
    pub const fn from_le_bytes(bytes: [u8; 8]) -> Self { Self::from_bits(u64::from_le_bytes(bytes)) }
    pub const fn from_ne_bytes(bytes: [u8; 8]) -> Self { Self::from_bits(u64::from_ne_bytes(bytes)) }
}
```

PR discussion summary: unlike corresponding integer methods, these can be implemented without `unsafe` code. So the need for having them in the standard library feels less pressing. At the same time, it might not be obvious to everyone that `to_bits` and `from_bits` can be combined with integer methods in this way. So having these float methods helps discoverability.

**Comment by lzutao** [comment]
Those methods above is not const anymore. We have to make `f*::from_bits` const
to mark above methos as const.
Also see https://github.com/rust-lang/rust/pull/58756#issuecomment-488391942.

**Comment by That3Percent** [comment]
There is a typo in the documentation. f64::from_le_bytes reads "Create a floating point value from its representation as a byte array in big endian." but it should say "... little endian". There may be other such typos, I only checked this function.

**Comment by lzutao** [comment]
You're right. Could you send a pull request to fix that typo?

**Comment by That3Percent** [comment]
Looks like you already did. Linking to it here just in case anyone is reading the thread:  #63366 To be honest, the suggestion kind of blew my mind that I, too, could contribute to rust-lang. I'll submit a PR next time. Thanks.

**Comment by SimonSapin** [comment]
Any remaining issue?

@rfcbot fcp merge
