### ISSUE TITLE
doc: dead link to std::boxed::Box::borrow

### ISSUE THREAD

**Issue by Songbird0** [rust-lang/rust#60442]
Hi,

I don't know if it's related to the issue #60200 (feel free to close it immediatly if so), but for the sake of completeness... [std::boxed::Box::borrow](https://doc.rust-lang.org/std/boxed/struct.Box.html#method.borrow) is dead.

cc @GuillaumeGomez

**Comment by DevQps** [comment]
I see that the method does not exist anymore. So that basically means that all documentation containing a reference to the borrow method should be updated right?

**Comment by GuillaumeGomez** [comment]
A little pass on the doc is required then.

**Comment by DevQps** [comment]
@GuillaumeGomez Thanks for your swift response! I will go and create a PR for this right away.

**Comment by GuillaumeGomez** [comment]
Thanks!

**Comment by ollie27** [comment]
Duplicate of #60200
