### ISSUE TITLE
powf for NaN returns 1

### ISSUE THREAD

**Issue by CodeSandwich** [rust-lang/rust#60468]
The `powf` for floating point numbers seems to have optimization: when base is 1, always return 1. This optimization does not check if exponent is a number, so 
```rust
1f32.powf(std::f32::NAN) == 1.
```
This behavior is same for debug and release modes, f32 and f64. [playground](https://play.rust-lang.org/?gist=6ae46b284c646d24acfd5704897fe136)

**Comment by nikic** [comment]
Relevant code in LLVM: https://github.com/llvm-mirror/llvm/blob/b79c73bd103edafbaff703c7230fcf1fe4e3b920/lib/Transforms/Utils/SimplifyLibCalls.cpp#L1421

**Comment by nagisa** [comment]
The contract for the `powf` function allows this behaviour (cited from linux’s man-pages for `powf(3)`):

>       Except as specified below, if x or y is a NaN, the result is a NaN.
>       If x is +1, the result is 1.0 (even if y is a NaN).
>       If y is 0, the result is 1.0 (even if x is a NaN).

**Comment by nagisa** [comment]
Interestingly, that does not correspond to any `IEEE-754` `pow*` operation, but it does properly follow the POSIX and C99 standards, so closing as not-a-bug.

**Comment by jonas-schievink** [comment]
This could use additional documentation though, the docs for `powf` are very bare-bones right now

**Comment by nagisa** [comment]
Copying the documentation for most functions from the POSIX standard would make sense for me, but that probably wants a separate issue specifically about that.

**Comment by qnighy** [comment]
> Interestingly, that does not correspond to any `IEEE-754` `pow*` operation, but...

It seems to comply with IEEE754 `pow` behavior described in IEEE754-2008 p.44 (§9.2.1 Special values):

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=7a8b40ddf93beb95fdc19932762f4ee3

**Comment by hkBst** [comment]
@qnighy your sample seems to be missing f64::NAN.
