### ISSUE TITLE
Unify binop errors wording

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#60497]
[The following](https://play.rust-lang.org/?gist=27c03aa1ea7239c56fb2ec66749ee2c4&version=nightly) [two errors](https://play.rust-lang.org/?gist=9bdfbdb401d5e39baf22a31ff125dae8&version=nightly) are actually the same problem but have different output because they are handled in different parts of the compiler. We should unify the output to have similar, if not the same, text.

```
error[E0277]: cannot add `std::option::Option<i8>` to `i8`
 --> src/main.rs:5:13
  |
5 | let sum = x + y;
  |             ^ no implementation for `i8 + std::option::Option<i8>`
  |
  = help: the trait `std::ops::Add<std::option::Option<i8>>` is not implemented for `i8`
```
```
error[E0369]: binary operation `+` cannot be applied to type `std::option::Option<i8>`
 --> src/main.rs:5:13
  |
5 | let sum = y + x;
  |           - ^ - i8
  |           |
  |           std::option::Option<i8>
  |
  = note: an implementation of `std::ops::Add` might be missing for `std::option::Option<i8>`
```

This issue has been assigned to @LeSeulArtichaut via [this comment](https://github.com/rust-lang/rust/issues/60497#issuecomment-562471788).

**Comment by Lonami** [comment]
How should one go about implementing this? Somehow sorting the operator order to pick consistently? Or better to always show the two hints for both orderings?

**Comment by estebank** [comment]
We could do it by picking and matching wording from both errors to make them consistent with each other. The E0277 one can be updated by changing the [`rustc_on_unimplemented` text for the trait](https://github.com/rust-lang/rust/blob/38264937fc16624b4f3959dec12c0440e5a8f628/src/libcore/ops/arith.rs#L68-L90), while E0369 can be updated by changing the following code:

https://github.com/rust-lang/rust/blob/ef9a876f8297e26859469b004047e0946ed10565/src/librustc_typeck/check/op.rs#L329-L422

I think in the end E0369 should mimic E0277 and not worry about adding the type labels to E0277.

**Comment by JohnTitor** [comment]
I'll work on this but I don't catch better wording. One of options is to change E0369 `cannot be applied to type {}` to `cannot be applied to type {} and {}`, is this reasonable? And should we also unify note/help wording?

**Comment by estebank** [comment]
@JohnTitor I believe that doing the following should be enough to close this ticket:

```
error[E0277]: cannot add `std::option::Option<i8>` to `i8`
 --> src/main.rs:5:13
  |
5 | let sum = x + y;
  |             ^ no implementation for `i8 + std::option::Option<i8>`
  |
  = help: the trait `std::ops::Add<std::option::Option<i8>>` is not implemented for `i8`

error[E0369]: cannot add `i8` to `std::option::Option<i8>`
 --> src/main.rs:5:13
  |
5 | let sum = y + x;
  |           - ^ - i8
  |           | |
  |           | no implementation for `std::option::Option<i8> + i8`
  |           std::option::Option<i8>
  |
  = note: an implementation of `std::ops::Add` might be missing for `std::option::Option<i8>`
```

@LeSeulArtichaut feel free to reach out if you need help with this.

**Comment by LeSeulArtichaut** [comment]
@estebank I don't know what to do with the comparaison operations. For example, [this](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=8224adfb1221a9362df769bf0da0afab) gives me E0308, and I haven't figured out a case with comparaison operators where E0369 is emmited. Am I missing something?

**Comment by estebank** [comment]
@LeSeulArtichaut it is ok if you only tackle a subset of all the binops, we can get back to `==` and other bool binops friends later.
