### ISSUE TITLE
Amazon S3 will stop supporting path-style bucket access

### ISSUE THREAD

**Issue by cuviper** [rust-lang/rust#60528]
https://forums.aws.amazon.com/ann.jspa?annID=6776

> Virtual-hosted style requests are supported for all S3 endpoints in all AWS regions. S3 will stop accepting requests made using the path-style request format in all regions starting September 30th, 2020. Any requests using the path-style request format made after this time will fail.

In theory, we just need to change all `https://s3-us-west-1.amazonaws.com/rust-lang-ci2/` URLs to `https://rust-lang-ci2.s3-us-west-1.amazonaws.com/`. Emscripten also pulls from `mozilla-games`.

There's also `$SCCACHE_BUCKET` = `rust-lang-ci-sccache2`.

**Comment by cuviper** [comment]
[HN commenters](https://news.ycombinator.com/item?id=19821406) mention concerns about DNS privacy and periods in bucket names, but I think neither of those apply to Rust CI.

**Comment by RalfJung** [comment]
[This](https://github.com/kennytm/rustup-toolchain-install-master/blob/e783c300e2f4e26eeb5eead86be18cbad802cca5/src/main.rs#L59) is one place that needs fixing.

Cc @kennytm

**Comment by kennytm** [comment]
@RalfJung Thanks, fixed in rustup-toolchain-install-master v1.6.1.

**Comment by cuviper** [comment]
https://aws.amazon.com/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/

> In response to feedback on the original deprecation plan that we announced last week, we are making an important change. Here’s the executive summary:
> 
> **Original Plan** – Support for the path-style model ends on September 30, 2020.
> 
> **Revised Plan** – Support for the path-style model continues for buckets created on or before September 30, 2020. Buckets created after that date must be referenced using the virtual-hosted model.

So our existing buckets will be fine after all.
