### ISSUE TITLE
Normalize use of backticks in syntax for user-facing compiler messages

### ISSUE THREAD

**Issue by alexreg** [rust-lang/rust#60532]
This is more pedantry from me, and admittedly not very high-priority, but I have noticed that there are discrepancies between compiler error/informational messages where syntax is included in them – some use backticks around code syntax, some don't. Furthermore, some start with lower case (the vast majority), while some don't.

For example:

```
"attribute must be of the form `#[derive(Trait1, Trait2, ...)]`"
```
vs.
```
"type does not implement `fmt::Debug`; consider adding #[derive(Debug)] \
```
(an internal inconsistency in this second case too!)

It would be nice to normalise this according  some guidelines. I'd imagine the guidelines should agree with rustdoc as much as possible, though starting all messages with lower case may be desirable, since it is "command-line fashion".

**Comment by fakenine** [comment]
Hello, I would like to work on this one! cc @varkor

**Comment by varkor** [comment]
@fakenine: I'm not sure of a principled way to go about this, but you can look in the compiler for error messages (coming from `span_err` and similar functions) and update any that have code in them to be surrounded by backticks. Running `x.py test src/test/ui --bless` then should update all the test files.

**Comment by alexreg** [comment]
Thanks @fakenine, sounds good.

**Comment by alexreg** [comment]
Unfortunately a lot of this will have to be done manually as @varkor hints at, but a good deal can be automated by searching with regexps, e.g. ``".*[^`]#\[\w+`` will find lines including a string terminator followed (eventually) by an attribute, where the attribute is not preceded by a backtick. You can probably make a shortlist of similar patterns and then create regexps for them.

**Comment by fakenine** [comment]
Thanks for the tips, I will look into that!

**Comment by alexreg** [comment]
Hi @fakenine. Any help on this so far? Let me know if you need advice or an initial cursory review!

**Comment by fakenine** [comment]
Hi @alexreg ! Thanks for the help. I was on holidays so I didn't get the time to start properly looking on it. I should be able to start this weekend

**Comment by alexreg** [comment]
No problem. Keep us posted, and feel free to ask here or on Discord. :-)

**Comment by fakenine** [comment]
Hello @alexreg! I have opened a WIP PR here https://github.com/rust-lang/rust/pull/61901

There are indeed lots of changes to do manually and results to sort with the regexes, but I'm confident about it :)

**Comment by fakenine** [comment]
I think this can be marked as resolved now :tada:

**Comment by alexreg** [comment]
Yep!
