### ISSUE TITLE
min and max are lacking on integers

### ISSUE THREAD

**Issue by ElectricCoffee** [rust-lang/rust#60556]
I'm not sure if this is intentional, and if it is, I can't imagine why.

Just today I had to write this gem of a one-liner
```rust
let max_val = (next_hp as f32).max(next_pwr as f32).max(next_def as f32) as i32;
```
That could just as easily just have been
```rust
let max_val = next_hp.max(next_pwr).max(next_def);
```
If i32 implemented `max`.
It strikes me as odd that a function that seems to be this trivial and useful doesn't exist on integers, but does on floats.

There isn't much more to say about the issue, other than that.
It would certainly be a quality of life improvement if it were to be implemented.

**Comment by ishitatsuyuki** [comment]
It's intentional because `f{32,64}::{min,max}` maps to actual hardware instruction in FPU.

You probably want `std::cmp::max`, or for three numbers, you can use `Iterator::max` by constructing an array/Vec.
