### ISSUE TITLE
Don't force the use of snake case !

### ISSUE THREAD

**Issue by Allenyn** [rust-lang/rust#60578]
Don't force the use of snake case ! Give it to developer !

Thanks.

**Comment by hellow554** [comment]
```
fn main() {
    #[allow(non_snake_case)]
    let FOO = 3;
}
```

**Comment by memoryruins** [comment]
It is a warning, but it is not forced. If you want to silence the warning entirely in a crate, add `#![allow(non_snake_case)]` at the top of lib.rs

**Comment by frewsxcv** [comment]
Rust does have warnings, but does not force snake case. You can opt-out of the warnings by adding `#![allow(non_snake_case)]` to your crate root.
