### ISSUE TITLE
Make a pdf version of the std api reference.

### ISSUE THREAD

**Issue by ghost** [rust-lang/rust#60577]

**Comment by VitalyAnkh** [comment]
You can use [Pandoc](http://pandoc.org) to convert these html version document files.

**Comment by hellow554** [comment]
@catastrop a more detailed description would be helpful though. Do you want something like doxygen which gives you a multi-hundred page PDF?

@rustbot modify labels: T-doc

**Comment by DevQps** [comment]
It reminds me a bit of this issue: #20866 which about generating epub and pdf versions of the Book. But maybe the idea behind it can be used for this as well?

**Comment by XVilka** [comment]
Related: https://github.com/rust-lang-nursery/mdBook/issues/88

**Comment by catastrop** [comment]
Why this is so hard to make a pdf? I have created a similar issue but no one response. All of them are closed.

Is this really too hard. Or just ......

**Comment by catastrop** [comment]
@VitalyAnkh, why they don't do that?

**Comment by catastrop** [comment]
@hellow554 , yes i (we) want one or more multi hundred pages long pdf like Julia, Ocaml, Python, R, Haskell, ARM, Intel.

**Comment by catastrop** [comment]
To make Rust more accessible you need offline, printable, readable on many devices documents.

**Comment by jonas-schievink** [comment]
@catastrop Please stop spamming issues, it will not get this resolved any faster. Rustdoc is not capable of outputting to PDF natively, it can only create the HTML-based documentation that is already available.

Like someone already said, you can try using Pandoc to convert the documentation, but the result might not look very good.

The only way to *properly* resolve this is by adding first-class PDF support to rustdoc, which, given the current architecture and state of rustdoc, is going to be very difficult. The rustdoc team is also only 4 people who are busy with other issues.

**Comment by hellow554** [comment]
@catastrop  I don't get your arguments. Rustdoc can already be access offline, because the doc is always installed along with the standard library and the compiler. **Always**. Just use `rustup doc --std` and it will be opened in your browser right away. **Locally** (remove your network cable and see that it still works)

**Comment by XVilka** [comment]
Note, that the code for generating PDF files already exists, it just require a bit of integration: https://github.com/Geemili/mdproof

**Comment by jyn514** [comment]
IMO this doesn't really make sense to add to Rustdoc. The way I see this happening is by implementing the JSON backend (https://github.com/rust-lang/rfcs/pull/2963) and then someone in the community can then make a PDF renderer using the JSON.

**Comment by jyn514** [comment]
--output-format=json has landed on nightly.

**Comment by Dylan-DPC** [comment]
Closing this as it is better suited for an external tool
