### ISSUE TITLE
Use of raw RWLock instead of RwLock

### ISSUE THREAD

**Issue by hellow554** [rust-lang/rust#60576]
https://github.com/rust-lang/rust/blob/7ac02005f3d7ac4b2c32b82dde365107aa2aafdf/src/libstd/panicking.rs#L57-L58

looking at these two lines of code is very frightening.
Is there a specific reason to use `RWLock` instead of `RwLock`? I would open a PR with either using `RwLock` or a comment describing why `RWLock` is needed here.

@rustbot modify labels: T-libs

**Comment by Lonami** [comment]
Just another thought, isn't the naming itself a bit dangerous? `RW` vs. `Rw` seems like an easy typo to make. Perhaps renaming `RW` as `RawRw` could help?

**Comment by sfackler** [comment]
`RwLock` can't be statically initialized, or at least couldn't be when that code was written. That'll change once the parking_lot PR lands.

**Comment by hellow554** [comment]
Hey @sfackler 
has the parking_lot PR already landed? Can you maybe tell the PR number? I would like to give it a shot to cleanup this.

**Comment by mati865** [comment]
It was not merged: https://github.com/rust-lang/rust/pull/56410#issue-comment-box

**Comment by hellow554** [comment]
I will close this comment as I don't see that this can and will be addressed any time soon. Thank you for your answer mati :)
