### ISSUE TITLE
"No variables matched as repeating at this depth" is checked late

### ISSUE THREAD

**Issue by mark-i-m** [rust-lang/rust#60587]
For example, the following compiles, but an error message is issued when the macro is used: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=491ff00e42a73bdcda9c8da783050097

(and likewise for all the other errors in that file)

**Comment by mark-i-m** [comment]
The code that issues this error is in `syntax::ext::tt:transcribe`

**Comment by estebank** [comment]
Cc https://github.com/rust-lang/rust/issues/35853

**Comment by mark-i-m** [comment]
Closing in favor of #61053
