### ISSUE TITLE
t! macro can be replaced by '?' operator

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/rust#60580]
This file defines a `t!` macro, but it seems like we can remove that macro and just use the new `?` unary operator instead.

https://github.com/rust-lang/rust/blob/7ac02005f3d7ac4b2c32b82dde365107aa2aafdf/src/libstd/sys/unix/process/process_unix.rs#L170-L175

There might be other files with a `t!` macro defined.

**Comment by mati865** [comment]
https://github.com/rust-lang/rust/issues/37939 should be fixed first
