### ISSUE TITLE
Functions in libbacktrace_sys use malloc/free/realloc directly

### ISSUE THREAD

**Issue by glandium** [rust-lang/rust#60599]
It's unfortunate that the functions in libbacktrace_sys go around the `#[global_allocator]` and uses the system allocator directly. That said, I'm not sure what those functions are used for. They don't seem to be used by the panic code.

Cc: @SimonSapin

**Comment by glandium** [comment]
Cc @alexcrichton

**Comment by SimonSapin** [comment]
Is this an issue for https://github.com/alexcrichton/backtrace-rs/issues?

**Comment by glandium** [comment]
Maybe?

**Comment by Mark-Simulacrum** [comment]
I'm going to close this since this is intentional (and somewhat unavoidable) given current constraints; I suspect that a move to gimli or similar would be a fairly large refactor which would likely touch this anyway and as such cleanup the direct malloc/free calls.

**Comment by glandium** [comment]
You could use mmap.c instead of alloc.c. That would still not make it use the #[global_allocator], but at least it wouldn't be using malloc/free. Alternatively, you could provide your own functions for those that are provided by alloc.c or mmap.c, and link that instead of alloc.c or mmap.c. None of these require control over the libbacktrace upstream source.
