### ISSUE TITLE
Improve diagnostics for missing associated types

### ISSUE THREAD

**Issue by alexreg** [rust-lang/rust#60595]
When the user fails to specify associated types for a trait object, the span used for the label ``associated type `Output` must be specified`` is the entire trait object, when it should ideally just be the trait (bound) from which the associated type is missing.

For example, we currently get:

```
3 | type Foo = Add + Sub;
  |            ^^^^^^^^^ associated type `Output` must be specified
```

when we really want something like:

```
3 | type Foo = Add + Sub;
  |            |     ^^^ associated type `Output` must be specified
  |            ^^^^      associated type `Output` must be specified
```

Note that PR https://github.com/rust-lang/rust/pull/59445 will ensure that there at least are *two* labels in the above example, which is more correct, although the spans of both labels will still be the entire trait object.

See also https://github.com/rust-lang/rust/pull/59445#discussion_r280960056.

CC @estebank @eddyb @Centril

**Comment by eddyb** [comment]
cc @varkor

**Comment by estebank** [comment]
[Current output](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=191cf5d33552a16d1610c77a46d118fa):

```
error[E0191]: the value of the associated types `Output` (from the trait `std::ops::Add`), `Output` (from the trait `std::ops::Sub`) must be specified
 --> src/lib.rs:1:12
  |
1 | type Foo = std::ops::Add + std::ops::Sub;
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |            |
  |            associated type `Output` must be specified
  |            associated type `Output` must be specified
```

It mentions all of the types that need the associated type set, but the span is still the same.

**Comment by estebank** [comment]
#67268 touches this part of the codebase. It doesn't address it, but it should be possible to build on it to do so. With that PR, the output is

```
error[E0191]: the value of the associated types `Output` (from trait `std::ops::Add`), `Output` (from trait `std::ops::Sub`) must be specified
 --> file12.rs:1:12
  |
1 | type Foo = std::ops::Add + std::ops::Sub;
  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ associated types `Output`, `Output` must be specified
```
