### ISSUE TITLE
Add a standardized construction method for struct !

### ISSUE THREAD

**Issue by Allenyn** [rust-lang/rust#60598]
Please add a standardized construction method for struct ! 
This is useful .

**Comment by estebank** [comment]
Could you clarify what you mean? Struct literals can already be used and you can implement the `Debug` trait for your types.

**Comment by hellow554** [comment]
@Allenyn please be a little more concrete with your issues. 
What I **think** what you want it something similar to a constructor, right? E.g. `let a = new B()`. 

I think the big plus point is, that such constructor does not exist per se! It is amazing. Every wondered how you signal errors which can happen in a constructor (e.g. a File cannot be opened, or a parameter is invalid)? 
I love it the way Rust does not force you to have a constructor, but "static methods" which can be arbitrary in its name.

If you want a `new Foo()` thing, you can use `Default`, e.g. `let a = Foo::default()`.

**Comment by Allenyn** [comment]
@hellow554  Thanks for your explanation.

**Comment by hellow554** [comment]
@Allenyn also please notice, that the github issue tracker is most likely used for bugs and issues in the rust language itself.
Questions and such are better asked in the [user forum](https://users.rust-lang.org) or [discord](https://discordapp.com/invite/rust-lang) if you want.
