### ISSUE TITLE
Clarification on **must** word in CStr::from_bytes_with_nul_unchecked docs

### ISSUE THREAD

**Issue by kpp** [rust-lang/rust#60606]
https://github.com/rust-lang/rust/blob/55c48b4e823ad3518bb8e6d3fd7da4f2fc0c5fc2/src/libstd/ffi/c_str.rs#L1017

Let's take a look at https://doc.rust-lang.org/std/ffi/struct.CStr.html#method.from_bytes_with_nul_unchecked :

> Unsafely creates a C string wrapper from a byte slice.
  This function will cast the provided bytes to a CStr wrapper without performing any sanity checks. The provided slice **must** be nul-terminated and not contain any interior nul bytes.

In some weird cases it is OK to create CStr from a non-nul-terminated and containing any interior nul bytes. It does not feel right to do so, because CStr stands for type representing a borrowed reference to a nul-terminated array of bytes, however it can be useful when dealing with a tricky C code. Let's take a look where (I believe) there is no UB and no errors:

```
use std::ffi::CStr;

fn main() {
    let bytes = [42, 0, 42];
    unsafe {
        let cstr = CStr::from_bytes_with_nul_unchecked(&bytes[..]);
        let ptr = cstr.as_ptr();
        dbg!(ptr);
    };
}
```

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=e5d413791dc64a7d85be34733fb297eb

According to https://www.ietf.org/rfc/rfc2119.txt **MUST**:

> MUST   This word, or the terms "REQUIRED" or "SHALL", mean that the
   definition is an **absolute** requirement of the specification.

So I feel like "**must** be nul-terminated and not contain any interior nul bytes" is too absolute for the docs, and the word **should** will fit better (with some kind of clarification), because:

> SHOULD   This word, or the adjective "RECOMMENDED", mean that there
   may exist valid reasons in particular circumstances to ignore a
   particular item, but the full implications must be understood and
   carefully weighed before choosing a different course.

cc @RalfJung

**Comment by jonas-schievink** [comment]
Your example is different from the linked playground, the `42` and `0` are swapped

**Comment by kpp** [comment]
> the 42 and 0 are swapped

Thanks, fixed.

**Comment by berkus** [comment]
For C string to be not UB, it "*must* be nul-terminated and *should not* contain any interior nul bytes".

It could contain interior nuls, the only downside is that to C-side this string would look differently (i.e. be a different string).

**Comment by kpp** [comment]
By definition C string is defined as a contiguous sequence of code units terminated by nul, however it is safe to cast a CStr with interior nul bytes to `char*` and to pass it to FFI functions with `bytes.len()` where you need a buffer not a C string.

> For C string to be not UB

So it is not a UB to create a CStr with without terminal nul, it will be UB to read uninitialized data past the end of the buffer that you get from that CStr.

**Comment by ollie27** [comment]
The implementations of `CStr` and `CString` assume that the nul byte is always at the end. For example [`to_bytes`](https://github.com/rust-lang/rust/blob/17dba3b6e450c357a881c8cbe6cfce87b7b9d6bd/src/libstd/ffi/c_str.rs#L1107-L1110) removes the last byte because it has to be the first nul. Changing `CStr` to allow interior nul bytes would cause a lot of breakage.

**Comment by RalfJung** [comment]
AFAIK this invariant of `CStr` is a *safety* invariant, so violating it can lead to UB down the road (including when a safe operation gets called on this data), but does not lead to immediate UB.

But that still warrants a MUST IMO -- if you violate it, you are leaving the bounds of what the API even talks about.

**Comment by kpp** [comment]
@RalfJung thank you. Let it be MUST.
