### ISSUE TITLE
Preallocate `DefId`s for lang items and use lang items in lowering

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#60607]
Right now, our lowering code uses string-paths to call e.g. `Iterator::next` when lowering `for` loops:

https://github.com/rust-lang/rust/blob/c6ac57564852cb6e2d0db60f7b46d9eb98d4b449/src/librustc/hir/lowering.rs#L4653-L4655

This triggers a name resolution call

https://github.com/rust-lang/rust/blob/c6ac57564852cb6e2d0db60f7b46d9eb98d4b449/src/librustc/hir/lowering.rs#L5263-L5273

which will then give us a resolved path, but that's

1. potentially expensive, since it happens *every time* a specific path is generated (which happens a lot for `?` and `for` expansions/lowerings)
2. seems uncool since it's stringly typed

I think it would be neat if we could instead create the `lang_items` table early in the process and just grab the appropriate item out of that table.

cc @Centril @eddyb @petrochenkov 

As a first experiment to check out the impact we could create a cache for path resolutions so we only run the path resolution code once and just overwrite all `HirId`s in the generated path with new `HirId`s whenever we fetch a cached resolution.

**Comment by Centril** [comment]
I'm going to take a look at this as a side-project :)

**Comment by matthewjasper** [comment]
see also #61019

I have an old branch for this here for anyone interested:
https://github.com/matthewjasper/rust/commit/a227c706b7809ff07021baf3856b7540d5b57f8a#diff-c0f791ead38d2d02916faaad0f56f41d 

Also see this comment: https://github.com/matthewjasper/rust/commit/a227c706b7809ff07021baf3856b7540d5b57f8a#r40107992

**Comment by ayazhafiz** [comment]
I am interested in finishing up the work you started @matthewjasper, if you don't already have plans to do so.

**Comment by matthewjasper** [comment]
I don't have plans to finish that work any time soon.

**Comment by davidtwco** [comment]
Opened #75145 to resolve this using @matthewjasper's earlier work.
