### ISSUE TITLE
std::cmp Documentation has some typos

### ISSUE THREAD

**Issue by OptimisticPeach** [rust-lang/rust#60614]
Hi there, I was just browsing the [`std::cmp`](https://doc.rust-lang.org/std/cmp/index.html) documentation and came across some funny looking text:
>* [Eq] and [PartialEq] are traits that allow you to define total and partial equality between values, respectively. Implementing them overloads the == and != operators.
> * [Ord] and [PartialOrd] are traits that allow you to define total and partial orderings between values, respectively. Implementing them overloads the <, <=, >, and >= operators.
> * [Ordering][cmp::Ordering] is an enum returned by the main functions of [Ord] and [PartialOrd], and describes an ordering.
> * [Reverse][cmp::Reverse] is a struct that allows you to easily reverse an ordering.
> * [max][cmp::max] and [min][cmp::min] are functions that build off of [Ord] and allow you to find the maximum or minimum of two values.

It seems that there are just a few links that are broken, so I thought I'd just make an issue. I would submit a PR with the fix, but I'm not sure how to do these kinds links.

**Comment by ehuss** [comment]
This is #59833.  intra-rustdoc-links has issues with reexporting between crates.

**Comment by OptimisticPeach** [comment]
Closing in favor of #59833
