### ISSUE TITLE
Add infix syntax

### ISSUE THREAD

**Issue by leaxoy** [rust-lang/rust#60624]
Since we have add postfix syntax, like `.await` ,  so need we support infix syntax in lang.
With infix syntax:
`list.iter().sum()` -> `list iter sum`
`a.add(b)` -> `a add b`
``

In summary, `a invoke b` or `a invoke`.

**Comment by hellow554** [comment]
`a.add(b)` -> `a + b`.

Beside that, not sure if trolling. If not, this needs an RFC https://github.com/rust-lang/rfcs.

**Comment by jonas-schievink** [comment]
This is definitely RFC territory. Closing.
