### ISSUE TITLE
Are blanket Future impls necessary?

### ISSUE THREAD

**Issue by stjepang** [rust-lang/rust#60645]
We currently have the following blanket impls:

```rust
impl<F: ?Sized + Future + Unpin> Future for &mut F
{ ... }

impl<F: ?Sized + Future + Unpin> Future for Box<F>
{ ... }

impl<F: Future> Future for AssertUnwindSafe<F>
{ ... }

impl<P> Future for Pin<P>
where
    P: Unpin + ops::DerefMut,
    P::Target: Future,
{ ... }
```

All of these blanket impls are on types that deref to something that implements `Future`. But then there are similar types that don't have a blanket `Future` implementation - for example, `MutexGuard`.

I wonder if these impls are necessary in practice if `fut.await` will auto-deref `fut` to a value that implements `Future`. I'm opening this issue just to double-check whether we really want to stabilize those blanket impls.

**Comment by Nemo157** [comment]
The final impl is very important for non `.await` usecases, it is what allows you to take a `Future + !Unpin`, pin it in your stack frame, then call a generic function like [`future::select`](https://rust-lang-nursery.github.io/futures-api-docs/0.3.0-alpha.15/futures/future/fn.select.html) which requires a `Future + Unpin`.

To get a similar impl for `MutexGuard` maybe the first two implementations could be merged into something generic over reference types (although this seems likely to run into coherence issues)?

```rust
impl<P> Future for P
where
    P: Unpin + ops::DerefMut,
    P::Target: Future + Unpin,
{ ... }
```

**Comment by mark-i-m** [comment]
cc @withoutboats @cramertj

**Comment by cramertj** [comment]
Yes, the last impl especially is critically important, and the others are nice conveniences. `fut.await` will not auto-deref.

**Comment by stjepang** [comment]
> `fut.await` will not auto-deref.

Do we explicitly not want it to auto-deref or is that something we'll think about in the future? Will `.await` auto-deref when we introduce `DerefMove`?

**Comment by cramertj** [comment]
I mean, never say never, but I certainly wouldn't expect the thing we stabilize to perform auto-deref, and I don't personally have plans to introduce this. The logic around deref is quite complicated, and the interactions with pinning here are especially unclear.

**Comment by stjepang** [comment]
I see, thanks. My last question would then be: does `foo.await` consume (i.e. drop) `foo` or not?

Also feel free to close this issue if you think it's been resolved.

**Comment by cramertj** [comment]
@stjepang `foo.await` consumes the expression `foo`. If `foo` is an `&mut T`, for example, it'll act just as if you passed an `&mut T` into a function as an argument (i.e. you'll still be able to use it). If `foo` was a non-Copy value, it will be consumed.

**Comment by cramertj** [comment]
Closing this issue as resolved-- yes, these impls are necessary in order to make `Future`s use possible today, in much the same way as the wrapper impls for `io::Read`/`Write`, `Iterator`, etc.
