### ISSUE TITLE
`existential type` complains about `'_` in concrete type of self-borrowing generators

### ISSUE THREAD

**Issue by cramertj** [rust-lang/rust#60655]
[Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=66371e7a7928adff2c93668c76514113)

```
error: non-defining existential type use in defining scope
  --> src/main.rs:9:22
   |
9  |   fn bar() -> ServeFut {
   |  ______________________^
10 | |     async move {
11 | |         let x = 5;
12 | |         await!(foo(&x))
13 | |     }
14 | | }
   | |_^ lifetime `'_` is part of concrete type but not used in parameter list of existential type

error: aborting due to previous error
```

cc @oli-obk

**Comment by oli-obk** [comment]
Am I correct in assuming that this should not compile, but report an error about returning a reference to the local variable `x`?

**Comment by oli-obk** [comment]
Expanded version:

```rust
#![feature(gen_future)]
#![feature(generators)]
#![feature(async_await, await_macro, existential_type)]

use std::future::{self, Future};

async fn foo(__arg0: &u8) {
}

pub existential type ServeFut: Future<Output = ()>;

fn bar() -> ServeFut {
    ::std::future::from_generator(move || {
        let x = 5;

        {
            let mut pinned = foo(&x);
            loop {
                match future::poll_with_tls_context(unsafe {
                    std::pin::Pin::new_unchecked(&mut pinned)
                }) {
                    std::task::Poll::Ready(x) => {
                        break x;
                    }
                    _ => (),
                }
                yield ()
            }
        }
    })
}
fn main() {}
```

[Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=3952774a5b377daffe0f9ab911e2e586)

**Comment by cramertj** [comment]
> Am I correct in assuming that this should not compile, but report an error about returning a reference to the local variable x? 

No, this should definitely compile.

>  Or is the self-borrowing generator part what makes this work? so the x is part of the generator struct and the &x is the yielded thing?

`&x` isn't yielded, but yes, it's a local variable inside the generator.

**Comment by oli-obk** [comment]
Hmm, so because the generator contains references, it has lifetimes, but these lifetimes actually refer to the generator again? Do we have a special kind of lifetime that we use for this? We should just ignore those generator lifetimes for existential types.

**Comment by cramertj** [comment]
There's no special lifetime afaik (cc @Zoxc @tmandry).

**Comment by matthewjasper** [comment]
We should ignore all bound regions. Function pointers have the same issue:

```rust
existential type A: Sized;

fn foo() -> A {
    (|x| ()) as for<'a> fn(&'a i32)
}

fn main() {}
```
