### ISSUE TITLE
`DefIndex` can use `newtype_index!`

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rust#60666]
https://github.com/rust-lang/rust/pull/60647#issuecomment-490856656
>Note, this could probably be further simplified by using `newtype_index!` for `DefIndex` and switching things to `IndexVec<DefIndex, _>` where appropriate. But let's land this first `:)`

**Comment by petrochenkov** [comment]
cc @fabric-and-ink

**Comment by fabric-and-ink** [comment]
I will look into it!

**Comment by petrochenkov** [comment]
Two more possible cleanups that are possible after removal of `DefIndexAddressSpace`:
https://github.com/rust-lang/rust/pull/60647#discussion_r283391646
https://github.com/rust-lang/rust/pull/60647#discussion_r283394682

**Comment by fabric-and-ink** [comment]
I think, this can be closed now.

**Comment by oli-obk** [comment]
@fabric-and-ink 	the two linked comments are still unresolved I think?

**Comment by fabric-and-ink** [comment]
You are right. I had the original topic in mind.

One of the linked comments is resolved. I don't know how to resolve the [second one](https://github.com/rust-lang/rust/pull/60647#discussion_r283394682).

**Comment by petrochenkov** [comment]
The second is fixed in https://github.com/rust-lang/rust/pull/59953, closing this issue.
