### ISSUE TITLE
round-trippability of `HIR` pretty printing

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#60663]
Should it be possible to feed the output of `--unpretty=hir` back to rustc without requiring the user to do any changes? Right now this is only possible for very trivial code, and even then requires adding some feature gates.

Any code with moderately complex expansions will require additional imports or touching the code. Some things I've noticed:

* #60661 (async fn, probably easily fixed)
* #60662 (existential type, easily fixed)
* `$crate` shows up in paths
* `'_` lifetimes where there were inferred lifetimes in signatures before

**Comment by oli-obk** [comment]
cc @rust-lang/compiler is this something we should strive to address? Seems a good start for new contributors as it's mostly detective work and trying out stuff.

In order to actually test it we'd need to change compiletest.

1. a way to run all `compile-pass` and `run-pass` test after pretty printing instead of normally
2. to have a new flag `//not-unpretty-hir-roundtrippable` that we'd put on those `compile-pass` or `run-pass` tests that don't work yet.
3. have some builder run tests with pretty printing (shouldn't be much slower I hope)

**Comment by petrochenkov** [comment]
>is this something we should strive to address?

Nah, for HIR pretty-printing there should be no such requirements, IMO.
It just should look reasonable enough to make HIR debugging possible.

(AST pretty printing is another story, proc macros and [tools](https://github.com/rust-lang/rust/pull/57915) do use it for generating well-formed code, even it it's not entirely reliable due to hygiene etc.)

**Comment by petrochenkov** [comment]
I mean if some fix is trivial and improves the output, then we should accept it, but if it requires preserving some data in HIR solely for pretty-printing, then we should not.

**Comment by Mark-Simulacrum** [comment]
Closing. I agree that this is not generally desirable, specific (simple) bug fixes can come as PRs; issues are not appropriate (as we don't _want_ it, but don't object to it).
