### ISSUE TITLE
error: duplicate lang item in crate `std`

### ISSUE THREAD

**Issue by BaoshanPang** [rust-lang/rust#60688]
I am seeing this issue:
error: duplicate lang item in crate `std`: `f64_runtime`.
  |
  = note: first defined in crate `std`.

It looks like the crate 'std' has been linked twice, the problem is how can I figure out why it has been linked twice? Is there any tool to check which rlib is pulling the 'std'?

**Comment by Aaron1011** [comment]
Can you post instructions for reproducing this?

**Comment by BaoshanPang** [comment]
After "./x.py clean" and rebuild, the problem went away. Sorry for the false alarm.

**Comment by jonas-schievink** [comment]
In that case, I'll close this. If this ever reappears and you can reproduce it, feel free to open a new issue!
