### ISSUE TITLE
`HashMap::with_capacity` doesn't work if the hasher is not `RandomState`

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rust#60699]
You have to use `HashMap::with_capacity_and_hasher(capacity, Default::default())` instead.

`with_capacity` should probably be available for any hasher that implements `Default`.

**Comment by petrochenkov** [comment]
Same applies to `HashMap::new`.

Perhaps type inference is the reason why they are not provided?
Not sure.

**Comment by Mark-Simulacrum** [comment]
@rustbot label: -E-easy

I think it's safe to say that if we haven't done this yet it's likely not actually an easy thing to fix; I suspect that the reason is indeed type inference (and/or type parameter defaults) and we just haven't gotten around to fixing it.

**Comment by sfackler** [comment]
We haven't done this because parameter defaults aren't taken into account for type inference.

**Comment by cuviper** [comment]
> Same applies to `HashMap::new`.

At least with `S: Default`, you can use `HashMap::default()` -- in fact that's all `new()` does.

**Comment by Mark-Simulacrum** [comment]
I'm going to close this since we basically can't make progress here without type parameter defaults which are a ways off (and I think this is a fairly "well known" desire, so it's unlikely that we'll forget).
