### ISSUE TITLE
[rustdoc] Wrong Re-exports display

### ISSUE THREAD

**Issue by saona-raimundo** [rust-lang/rust#60698]
In this [documentation](https://bheisler.github.io/RustaCUDA/rustacuda/prelude/index.html), the re-exports are oddly displayed:
There are structs and traits that are not shown as re-exports, but further in the documentation.

I am new to Rust, sorry if this is not the place to rise this issue.

**Comment by hellow554** [comment]
Can you explain what you mean by oddly? They are listed as re-exports.

**Comment by rasa200** [comment]
Hi, sorry for the delay. Thanks for the quick answer.

In the code you can see `pub use crate::stream::{Stream, StreamFlags};`, where Stream is a struct of the crat. It is shown in the documentation as `pub use crate::stream::Stream`, which is how it was intended.

In the other hand, in the code there is also `pub use crate::memory::{CopyDestination, DeviceBuffer, UnifiedBuffer};`, to re-export two other structs and one trait. But they are shown in the documentation in the Structs and Traits section inside the module prelude, as if there were a `#[doc(inline)]`, which is not there.

Looking at the source code, I would think that all the re-exports would be documented the same way, and I don't see a reason why some are documented differently.

Am I missing some `#[doc(no_inline)]`? 
Why would it be necessary in this case?

**Comment by rasa200** [comment]
Hi there!

Any idea about this?
Thanks beforehand.

**Comment by saona-raimundo** [comment]
Adding `#[doc(no_inline)]` fixed the issue!

This should not keep happening as [In Rust 2018 and later, if you pub use one of your dependencies, rustdoc will not eagerly inline it as a module unless you add `#[doc(inline)]`.](https://doc.rust-lang.org/rustdoc/the-doc-attribute.html#docno_inlinedocinline)
