### ISSUE TITLE
Cleanup hack to expect `scrutinee: bool` in if-to-match desugaring in match-expr typeck

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#60707]
In https://github.com/rust-lang/rust/pull/59288 a hack is introduced in `rustc_typeck::check::_match::check_match` that checks, via `MatchSource::IfDesugar`, whether an `if`-expression was desugared to `match` and if so, it requires that the scrutinee be typed at `bool`.

We might want to remove this hack in favor of a more principled solution, with options:

1. Fix type ascription such that it admits coercions and then use `ExprKind::Type(...)` to set the expectation that the type be coercible to `bool`. This will require adjustments to diagnostics logic to reduce clutter.

2. Use a cast `$scrutinee as bool` and use `ExprKind::Cast(...)` to set the expectation that the type be coercible to `bool`. Same applies wrt. diagnostics.

3. Add a flag in the type ascription HIR that enables the "coercion" behavior we want. This is still a hack but potentially less of a hack.

4. Remove the hack entirely and permit `if &true { ... }` to type check.

   This is a semantic change to the language but perhaps a desirable one. I (@Centril) believe it would facilitate usability since there are cases where you call a function and end up with `&bool`, e.g. indexing a slice of `bool`s. Right now you would have to deref the returned `&bool` to make it work. I also think it is a semantic simplification of the language since `if` becomes more of a pure in-language desugaring than before. cc @rust-lang/lang about this idea of applying default-match-bindings to `if` conditions. 

For more context, see https://github.com/rust-lang/rust/pull/59288#issuecomment-490970899 and https://github.com/rust-lang/rust/pull/59288#pullrequestreview-233660158.

**Comment by c410-f3r** [comment]
Some things are outdated. For example, `MatchSource::IfDesugar` does not exist anymore.

**Comment by Mark-Simulacrum** [comment]
I'm going to go ahead and close this per https://github.com/rust-lang/rust/issues/53667#issuecomment-1221601412; it seems like the majority or all of this is no longer the case today. I tried poking around in the compiler to find related code but didn't see anything that stood out as particularly relevant. hir::ExprKind has an If variant today, for example.
