### ISSUE TITLE
x.py test should be able to test subfolders

### ISSUE THREAD

**Issue by varkor** [rust-lang/rust#60718]
It would be very useful if `./x.py test src/test/ui/subfolder` would run every UI test in `src/test/ui/subfolder` (at the moment it runs every single UI test). `./x.py test` currently works for [individual files](https://github.com/rust-lang/rust/issues/48483) and for entire test suites, but not directories.

**Comment by varkor** [comment]
The `--test-args` flag might become obsolete if this becomes possible.

**Comment by Centril** [comment]
> The `--test-args` flag might become obsolete if this becomes possible.

Please no... :) `--test-args` is still useful for testing files that have similar names or if you are just too lazy to give an absolute path.

**Comment by petrochenkov** [comment]
>./x.py test currently works for individual files
