### ISSUE TITLE
Nested structures

### ISSUE THREAD

**Issue by aristarh2704** [rust-lang/rust#60731]
Please, add support for nested structures.

**Comment by Centril** [comment]
Please elaborate.

**Comment by rodrimati1992** [comment]
Do you mean something like this:
```
pub struct A{
    nested:struct{
        field0:u32,
    },
}
```
where you declare anonymous structs inside a regular one?

**Comment by Mark-Simulacrum** [comment]
Closing. If someone wants to pursue this, please follow the RFC process here https://github.com/rust-lang/rfcs#before-creating-an-rfc. If you'd like to discuss it further internals.rust-lang.org is the way to go.
