### ISSUE TITLE
Missing documentation for while keyword

### ISSUE THREAD

**Issue by timvisee** [rust-lang/rust#60736]
I noticed the `while` keyword seems to be missing from the [official documentation][docs]. Keywords like `loop` and `for` are documented. Nor does `while` come up when searching at the top.

Is there a reason for it missing?

[docs]: https://doc.rust-lang.org/std/#keywords

**Comment by jonas-schievink** [comment]
These are probably just missing because nobody added documentation for them yet, so feel free to send a PR.

**Comment by lzutao** [comment]
If anyone is interested, you need to add documentation here: https://github.com/rust-lang/rust/blob/master/src/libstd/keyword_docs.rs

**Comment by Pulkit07** [comment]
I will take care of this one :)

**Comment by timvisee** [comment]
Cool! Wanted to do it, but haven't been able to start on it yet. Perfect if you can take it over.

**Comment by Pulkit07** [comment]
> Cool! Wanted to do it, but haven't been able to start on it yet. Perfect if you can take it over.

In that case, it will be nice to have you review the PR: https://github.com/rust-lang/rust/pull/60761.

**Comment by hellow554** [comment]
Partially resolved by #60817 
I think this can be closed in favor of #34601. What do you think @jonas-schievink ?

**Comment by jonas-schievink** [comment]
https://github.com/rust-lang/rust/pull/60761 will close this when merged, and it addresses `while` specifically, so we can also wait for that to land
