### ISSUE TITLE
Remove Bitrig support

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/rust#60743]
Bitrig is a now defunct OpenBSD fork. It has been mostly successful and some of it's changes have been merged back into OpenBSD. It's development has halted ~2 years ago, and it never got another release after 1.0 in 2014.

Rust had some limited support for Bitrig (as a Tier 3 platform). I think we should remove the support to clean up the libstd code a bit.

(inspired by https://github.com/rust-lang/rust-forge/pull/165, which just unlists it)

**Comment by mazocomp** [comment]
@jonas-schievink the current maintainer of Rust port in OpenBSD is @semarie, he makes sure Rust and Cargo also work at aarch64-unknown-openbsd and i686-unknown-openbsd, so shouldn't those two be mentioned as Tier 3 at The Rust Forge?

**Comment by jonas-schievink** [comment]
@mazocomp That makes sense to me! You can file a PR at https://github.com/rust-lang/rust-forge if you like.
