### ISSUE TITLE
Weird compiler behavior when compiling a dynamic library

### ISSUE THREAD

**Issue by eugene2k** [rust-lang/rust#60758]
When the code below is compiled with `crate-type=cdylib` the function `fooBar` is excluded from the symbol table, however when the code below is compiled with `crate-type=dylib` the function `fooBar` is present:
```
pub extern "C" fn fooBar() -> u8 {
    0
}
```
When the function is decorated with the `#[no_mangle]` attribute it is present in both cases.

[Edit: the following is my mistake, sorry]
When the function is decorated with attribute `#[cfg(allow_non_snake_case]` it is absent in both cases even if it is also decorated with `#[no_mangle]`. Furthermore, if the code is modified like so:
```
#[cfg(allow_non_snake_case)]
pub extern "C" fn fooBar() -> u8 {
}
```
the compiler doesn't even report an error, apparently ignoring the function entirely.

Tested on linux stable and nightly.

**Comment by jonas-schievink** [comment]
`#[cfg(allow_non_snake_case)]` is not a lint attribute, it will remove the item it's applied to when rustc isn't invoked with `--cfg allow_non_snake_case`. Did you mean to use `#[allow(non_snake_case)]` instead?

**Comment by eugene2k** [comment]
Ah, okay, that explains part of the problem. I rarely use the this feature and forgot the proper way to use it.

**Comment by jonas-schievink** [comment]
> When the code below is compiled with `crate-type=cdylib` the function `fooBar` is excluded from the symbol table, however when the code below is compiled with `crate-type=dylib` the function `fooBar` is present:

This might be intentional: A `cdylib` is meant to be used from non-Rust code, so only unmangled functions are accessible (since mangling is not generally predictable by non-Rust code), while a `dylib` is meant to be used from other Rust code, so mangled names are still accessible since all code is built with the same rustc.

**Comment by Mark-Simulacrum** [comment]
Closing in favor of https://github.com/rust-lang/rfcs/issues/2771 as the only feature request ("bug") here is that the cdylib has no nice way of exporting the symbol.
