### ISSUE TITLE
Add impl_trait_in_bindings to INCOMPLETE_FEATURES

### ISSUE THREAD

**Issue by matthewjasper** [rust-lang/rust#60764]
cc #60473,  #60407, #58956

**Comment by varkor** [comment]
If you want to fix this, all you need to do is add the string `"impl_trait_in_bindings"` to:
https://github.com/rust-lang/rust/blob/0df1e57991e34825697b1659732c0716e7508519/src/libsyntax/feature_gate.rs#L565-L568
And update the tests that make use of that feature to catch the new warning that is emitted.
