### ISSUE TITLE
Is using array pointers with FFI UB?

### ISSUE THREAD

**Issue by elichai** [rust-lang/rust#60776]
Hi,
I want to know if it is UB to pass a C function that receives `uint8_t arr[20]`
an array pointer(`*mut [u8; 20]`) instead of a regular pointer(`*mut u8`)?
are pointers and length equivalent to arrays? or is this UB?

cc @emilio https://github.com/rust-lang/rust-bindgen/issues/1561

**Comment by hellow554** [comment]
As this isn't directly an issue, I would recommend you to ask on the [user forum](https://users.rust-lang.org) or [stackoverflow](https://stackoverflow.com/questions/tagged/rust) instead.

**Comment by jonas-schievink** [comment]
Seems to be answered in this forum thread already: https://users.rust-lang.org/t/is-using-array-pointers-with-ffi-ub/28197

**Comment by elichai** [comment]
Yeah I posted there after @hellow554 requested.
If anyone can verify that his answer is correct I'll be glad.

Thank you.
