### ISSUE TITLE
Documentation for pointer::add should explain why it is unsafe

### ISSUE THREAD

**Issue by fintelia** [rust-lang/rust#60789]
The documentation for [pointer::add](https://doc.rust-lang.org/std/primitive.pointer.html#method.add) does a good job explaining under what conditions it can trigger undefined behavior, but only very subtly alludes to why the function wasn't implemented fully with safe Rust. Perhaps instead say something like:

> ### Safety
> **This function is unsafe because it passes special annotations to LLVM to improve performance**. For a completely safe alternative use wrapping_add instead. For this function, if any of the following conditions are violated, the result is Undefined Behavior:

**Comment by Centril** [comment]
I'm not a big fan of mentioning LLVM documentation like that. We should try to move away from being so tied to that backend.

**Comment by fintelia** [comment]
Good point. Perhaps "the compiler backend" instead of "LLVM"? I think it is important to mention in some form though because the only reason the function is unsafe at all is because of a detail on how it gets passed to LLVM. I didn't even realize it was unsafe until someone offhandedly mentioned it in an unrelated thread. The name `add` certainly doesn't help here, if anything `add_unchecked` would be a much more obvious choice though it is probably too late on that point.

**Comment by Centril** [comment]
@fintelia That's perhaps a comment which is more suitable in the implementation of the function rather than as a doc comment then.

**Comment by fintelia** [comment]
@Centril I'm not sure I follow, the issue is that this function documentation doesn't concisely say "this doesn't work how you expect, here's why" (The reason one would expect that pointer::add would be safe is that both the rust book and the nomicon are very clear that it is safe for pointers to hold *any* value aligned or otherwise)

Though perhaps the doc-comment is the wrong place since most people are unlikely to look there at all. When is the last time you read the documentation for on obvious function like say `usize::add`? Why should `pointer::add` be any different?  Given that add is used so frequently in unsafe code, perhaps this could be resolved just by giving it some discussion in the nomicon?
