### ISSUE TITLE
rustdoc: Extra margin in enum definition

### ISSUE THREAD

**Issue by jethrogb** [rust-lang/rust#60792]
The enum definition at https://doc.rust-lang.org/nightly/nightly-rustc/rustc_errors/diagnostic/enum.DiagnosticId.html currently looks like:
```
pub enum DiagnosticId {
    Error(String),
    Lint(    String),
}
```
(note the extra space in `Lint`)

This seems to be the culprit (added in 825a11ea):
```
.type-decl>pre>:nth-child(2) {
 margin-left:1.8em !important;
}
```

cc @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
Fixed by #60093. Duplicate of #60042. Closing it then. Thanks though!
