### ISSUE TITLE
improve the "must use" lint for `Future` to suggest await

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#60797]
The following code [gives a "must use" warning](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=1dce9a2ee23813a18dfcf2b4d6bfa2fe) (which is awesome!), but the warning is not as clear as it could be:

```rust
#![feature(async_await)]
#![allow(dead_code)]

async fn foo() {
    bar();
}

async fn bar() {
}

fn main() { }
```

This results in:

```
warning: unused implementer of `std::future::Future` that must be used
 --> src/main.rs:5:5
  |
5 |     bar();
  |     ^^^^^^
  |
  = note: #[warn(unused_must_use)] on by default
  = note: futures do nothing unless polled
```

it should probably say "futures do nothing unless you await them" or something. Most people won't know what 'polled' is all about, I think.

**Comment by Centril** [comment]
The current note originates from:
https://github.com/rust-lang/rust/blob/a9ec99f4201ec33026a468ef1289f98a95b4d71a/src/libcore/future/future.rs#L26

To change it, simply edit that.

**Comment by Schultzer** [comment]
What about ` #[must_use = "futures stays idle unless you await them"] ` ?

**Comment by aesedepece** [comment]
> What about `#[must_use = "futures stays idle unless you await them"]` ?

In any case, `#[must_use = "futures stay idle unless you await them"]`. Just a typo :wink: 

I would actually expect something in the line of:

```
#[must_use = "a future does nothing unless you await or poll it. Did you miss using the `await!` macro on it?"]
```

**Comment by Centril** [comment]
We may want to work in the fact that you can use `my_future.await` somehow.
Other than that, `#[must_use = "futures stay idle unless you await them"]` sounds pretty good.

**Comment by aesedepece** [comment]
@Centril what trait does provide `my_future.await`? :astonished:

**Comment by Centril** [comment]
@aesedepece `my_future.await` is equivalent to `await!(my_future)` and is likely to replace it eventually. See https://boats.gitlab.io/blog/post/await-decision/.

I think for now `#[must_use = "futures stay idle unless you await them"]` might be good enough and we could tweak later.

**Comment by aesedepece** [comment]
That makes sense to me!

Am I ok to work on this?

>
