### ISSUE TITLE
The name "Rust" collides with other names - hard to find books.

### ISSUE THREAD

**Issue by JohnReedLOL** [rust-lang/rust#60812]
It's hard to find Rust books on Amazon because "Rust" is such a generic word. 

See: https://smile.amazon.com/s?k=Rust&i=stripbooks&rh=p_72%3A1250222011&dc&qid=1557806275&rnid=1250219011&ref=sr_nr_p_72_2 

Go changed to "GoLang". Would you consider changing Rust to "RustLang"?

**Comment by hellow554** [comment]
The domain (same as the github name) is already "rust-lang".

**Comment by jonas-schievink** [comment]
Most of the results in that query *are* Rust-the-Language books for me. And yeah, this is basically already done (Go didn't exactly [change their name](https://tip.golang.org/doc/faq#go_or_golang) either). Closing.

**Comment by JohnReedLOL** [comment]
If I can call Rust "RustLang" the way I call Go "Golang", then that's fine. Closing.
