### ISSUE TITLE
ICE when using struct constructor with explicit const generic arguments

### ISSUE THREAD

**Issue by jplatte** [rust-lang/rust#60818]
This very simple example ([Playground link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=516357843078a0b1bdaef643bc20c8a5)):

```rust
#![feature(const_generics)]

struct Generic<const V: usize>;

fn main() {
    let _ = Generic::<0>;
}
```

results in: `error: internal compiler error: src/librustc_typeck/collect.rs:1407: unexpected const parent path def Def(Ctor(Struct, Const), DefId(0:13 ~ playground[d52b]::Generic[0]::{{constructor}}[0]))`. Changing it to use curly braces around `0` does not help.

**Comment by DutchGhost** [comment]
This does work:
```Rust
#![feature(const_generics)]

struct Generic<const V: usize>;

fn main() {
    let _ = Generic::<{0}>{};
}
```

**Comment by davidtwco** [comment]
@varkor I was actually just experimenting locally to see if I could fix this and I think I have, I could put a PR up in a few minutes.
