### ISSUE TITLE
GNU default host triple

### ISSUE THREAD

**Issue by cup** [rust-lang/rust#60810]
If I download this file:

https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-msvc/rustup-init.exe

and run I get this result by default:

~~~
Current installation options:

   default host triple: x86_64-pc-windows-msvc
     default toolchain: stable
  modify PATH variable: yes
~~~

However if I download this file:

https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-gnu/rustup-init.exe

and run I get the same result. With GNU RustUp why is it not setting GNU ABI for
the default host triple?

**Comment by lzutao** [comment]
You want to ask this in rust-lang/rustup instead.

**Comment by cup** [comment]
https://github.com/rust-lang/rustup.rs/issues/1851

**Comment by jonas-schievink** [comment]
Closing in favor of https://github.com/rust-lang/rustup.rs/issues/1851
