### ISSUE TITLE
{signed integer}::saturating_[div|neg] might make sense

### ISSUE THREAD

**Issue by HadrienG2** [rust-lang/rust#60833]
Although the `{signed integer}::min_value() / -1` scenario is arguably an edge case, it does exist, and could potentially justify the existence of a `saturating_div` operation for symmetry with other saturating operations.

**EDIT:** By the same argument `saturating_neg` should probably also exist.

**Comment by clarfon** [comment]
In this case it might make sense to also have a `saturating_rem` for parity with `saturating_div`.

**Comment by kadiwa4** [comment]
Both functions are stable now: [`saturating_div`](https://doc.rust-lang.org/stable/core/primitive.i32.html#method.saturating_div) and [`saturating_neg`](https://doc.rust-lang.org/stable/core/primitive.i32.html#method.saturating_neg).
