### ISSUE TITLE
Should improper_ctypes pierce through impl Trait?

### ISSUE THREAD

**Issue by hanna-kruppe** [rust-lang/rust#60855]
While reviewing #60300 I noticed for the first time that the improper_ctypes lint normalizes with the "reveal_all" mode. I don't have a nuanced understanding of what that means exactly but based on the general description in the rustc docs and experimentation (see below) I think that's probably the wrong choice for this lint, because it exposes details to the user that are normally hidden during type checking.

For example, [in this program](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=76fdb36dcf516354a400647c26b64e87) using existential types, the lint pierces through otherwise-opaque existentials to look at the underlying (hidden) type, thus it both

- accepts code that is only FFI-safe because of the particular type underlying the existential, which users of that type shouldn't know or rely on
- leaks the underlying type to the user in error messages when (correctly) rejecting uses of an existential type as FFI-unsafe

I can't quickly find an equivalent using only stable `impl Trait`, because we don't have `typeof(function)`, but if there's a way to write "Option of the return type of this function" in stable Rust, then that would presumably have the same issue.

cc @eddyb for fact-checking my understanding that this is because of reveal_all

**Comment by eddyb** [comment]
@rkruppe User-facing diagnostics should avoid the `Reveal::All` mode, yeah. In fact, the other variant of `Reveal` is literally `Reveal::UserFacing` - also the doc comments are pretty explicit about this:
https://github.com/rust-lang/rust/blob/37ff5d388f8c004ca248adb635f1cc84d347eda0/src/librustc/traits/project.rs#L28-L68

cc @nikomatsakis @nagisa @oli-obk @Manishearth

**Comment by davidtwco** [comment]
I've been using `LateContext`'s `param_env` over `ParamEnv::reveal_all()` in recent PRs that modify the `improper_ctypes` lint (see #72700, #73287, and #73257). 

In each recent PR, I've ensured that opaque types are prohibited (in the spirit of "FFI-safety of a type not relying on particular type behind an opaque type being FFI-safe") - with the exception of when a opaque type is used in a projection (#73287).

Unless there are specific examples of behavior that still need to be changed as a result of this issue - should this issue be closed?

**Comment by hanna-kruppe** [comment]
My litmus test for closing this would be "all the normalizing done in improper_ctypes uses `Reveal::UserFacing`", which is hard to audit for while there's multiple PRs in flight that address parts of the problem. After those PRs are all merged, we can see if there's any `Reveal::All` remaining and if so, their location should tell us how to exercise any remaining questionable behavior.

**Comment by davidtwco** [comment]
I've put up #73758 to fix the remaining two places that `Reveal:All` is used now that the other PRs have landed.
