### ISSUE TITLE
Document or deprecate single argument assert macro

### ISSUE THREAD

**Issue by matklad** [rust-lang/rust#60856]
One of my students have written the following code today:

```rust
assert!(red >= 0.0, red <= 1.0);
```

Although it looks like it checks two conditions, it actually expands to

```rust
if !(red >= 0.0) { panic!(red <= 1.0) }
```

That is, it panics with a boolean value.

This is highly surprising and not really documented (there are docs on `panic!`, but not on the `assert!`).

We can just document this behavior, but it seems better to just fix it? Can we deprecate particular macro forms?

**Comment by Centril** [comment]
I think we could issue a lint (not deprecation) for cases which are clearly mistaken. However, the form `assert!(false, "string_literal");` is useful so we want to avoid linting on that.

**Comment by matklad** [comment]
Ah, so the difference here is not actually in the macro itself, but in the runtime.

That is, `assert!(false, 92)` prints `panicked at 'Box<Any>' and `assert!(false, ("oups"))` prints  `'anicked at 'oups'` not because the syntax is different, but because the runtime panic hook downcasts payload to string. 

Yeah, in this case, the best we can do is probably document + lint

**Comment by hellow554** [comment]
> However, the form `assert!(false, "string_literal");` is useful so we want to avoid linting on that.

Is it possible for the compiler to detect whether the second argument it either a `&str` or a `String`? If yes, it's trivial, if not, what to do?

**Comment by Centril** [comment]
@hellow554 During the macro expansion phase of the compiler I believe we can check syntactically whether it is a string literal or not. This would however lint on a string or string slice stored in a binding. In the HIR we don't have access to whether it came from `assert!` but we could possibly preserve a mark on the `Span` and use that during post-typeck linting to make decisions based on types.

**Comment by steveklabnik** [comment]
Triage: no change

**Comment by jyn514** [comment]
> I think we could issue a lint (not deprecation) for cases which are clearly mistaken. However, the form assert!(false, "string_literal"); is useful so we want to avoid linting on that.

Triage: both of these cases are covered by `non_fmt_panic`, which is on by default:

```
warning: panic message is not a string literal
 --> src/main.rs:3:25
  |
3 |     assert!(red >= 0.0, red <= 1.0);
  |                         ^^^^^^^^^^
  |
  = note: `#[warn(non_fmt_panic)]` on by default
  = note: this is no longer accepted in Rust 2021
help: add a "{}" format string to Display the message
  |
3 |     assert!(red >= 0.0, "{}", red <= 1.0);
  |                         ^^^^^
```
