### ISSUE TITLE
How to add a new target (triple) that can be built by the official branch nightly

### ISSUE THREAD

**Issue by chandde** [rust-lang/rust#60858]
I’m working on enabling ARM32, namely thumbv7a-pc-windows-msvc, the majority of changes has been committed already, however, there is some issue building it successfully, so it’s not built by the master branch and user cannot install this target using rustup. I’m still working on making it build end to end at least reach stage 2. Once it can build, I’d like to have it built in rust master, so user can simply rustup add target to get it.

I’m looking at aarch64-pc-windows-msvc, it’s built, but not tested, I’d like to achieve the same availability for thumbv7a. So what it takes to get me there?

I did a rough search, here’s thumbv7a in rust master, 2 files,
(https://github.com/search?l=&q=thumbv7a-pc-windows-msvc+user%3Arust-lang+repo%3Arust&type=Code)

And here’s aarch64 in rust master, 8 files,
(https://github.com/search?l=&q=aarch64-pc-windows-msvc+user%3Arust-lang+repo%3Arust&type=Code)

Does it mean give or take, I need to add least make changes to the other 6 files to align with aarch64? Please advise.

I also posted the same question in the forum, https://users.rust-lang.org/t/how-to-add-a-new-component-triple-that-can-be-built-by-the-official-branch-nightly/28267, please let me know which one is better for this ask.

**Comment by Mark-Simulacrum** [comment]
I suspect we do not have the CI budget for this right now, especially on Windows.

However, before suggesting that we add this platform to CI, we'll need a working implementation on master. For that I would suggest filing PRs over issues and/or discussing on internals as the project itself does not have the resources to maintain or provide support for tier 2 platforms; issues would likely be unhelpful as such.
