### ISSUE TITLE
Cargo fmt doesnt handle const generics correctly

### ISSUE THREAD

**Issue by DutchGhost** [rust-lang/rust#60863]
When I run `cargo fmt` over the following code:
```Rust
#![feature(const_generics)]

pub struct S<const N: usize>;
impl S<{ 0 }> {}
```

the impl block is formatted to this:
```Rust
impl S<{ 0 }> { 0 }> {}

```
which then obviously fails to compile.

playground: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=be54fe6369c6945d0a5e7a372ce49098

**Comment by DutchGhost** [comment]
Can be closed since this is a rust-fmt issue:
https://github.com/rust-lang/rustfmt/issues/3554

**Comment by Lonami** [comment]
@DutchGhost you can close the issue yourself too.

**Comment by jonas-schievink** [comment]
Closing in favor of rust-lang/rustfmt#3554
