### ISSUE TITLE
rustdoc generates <div> in <h4> when implementing things with #[must_use] and other attributes

### ISSUE THREAD

**Issue by kentfredric** [rust-lang/rust#60865]
Similar to #60403 

For example, when one generates rustdoc for something that implements Iterator, the generated HTML is (with manual pretty-printing)

```html
<h4 id='method.collect' class="method">
  <code id='collect.v'>
    <div class="docblock attributes">
      #[must_use = "if you really need to exhaust the iterator, consider `.for_each(drop)` instead"]
    </div>
    fn
    <a href='https://doc.rust-lang.org/nightly/core/iter/traits/iterator/trait.Iterator.html#method.collect' 
      class='fnname'>collect</a>
      &lt;B&gt;(self) -&gt; B 
     <span class="where fmt-newline">
       where<br>&nbsp;&nbsp;&nbsp;&nbsp;B: 
       <a class="trait" 
            href="https://doc.rust-lang.org/nightly/core/iter/traits/collect/trait.FromIterator.html" 
            title="trait core::iter::traits::collect::FromIterator">FromIterator</a>
       &lt;Self::
       <a class="type"
            href="https://doc.rust-lang.org/nightly/core/iter/traits/iterator/trait.Iterator.html#associatedtype.Item" 
            title="type core::iter::traits::iterator::Iterator::Item">Item</a>
        &gt;,&nbsp;
     </span>
   </code>
   <span class='since' title='Stable since Rust version 1.0.0'>1.0.0</span>
   <a class='srclink' 
         href='https://doc.rust-lang.org/nightly/src/core/iter/traits/iterator.rs.html#1464-1466' 
         title='goto source code'>[src]</a>
</h4>
```
This HTML contradicts HTML spec, and causes problems when parsed by a strict parser ( such as html-tidy )

Additionally, this renders very oddly:

![snapshot_20190516_100607](https://user-images.githubusercontent.com/44790/57812882-6f872780-77c2-11e9-97b2-299bc23907d3.png)
![snapshot_20190516_100626](https://user-images.githubusercontent.com/44790/57812888-744bdb80-77c2-11e9-86a2-247eee724799.png)

```bash
rustc --version
#rustc 1.36.0-nightly (372be4f36 2019-05-14)
```

**Comment by GuillaumeGomez** [comment]
What alternative do you suggest?

**Comment by kentfredric** [comment]
The solution of using a `<span>` instead of `<div>` worked satisfactorily for the other example.

( The side issue with the weird rendering is more about the weird double-"+", there's probably a better way of doing this, but I'm a bit short of ideas how )

**Comment by GuillaumeGomez** [comment]
It's complicated indeed. I'll send a PR to change this soon.
