### ISSUE TITLE
Don't ignore generator fields in miri

### ISSUE THREAD

**Issue by tmandry** [rust-lang/rust#60889]
Right now, saved locals in generators are special-cased in miri, because they might not always be initialized.

With #59897 and #60187, we have the framework to fix this: fields are now only put in generator variants where they are live. The problem remains with aggregate fields, however, e.g.

```rust
fn gen() {
  let x: (i32, i32);
  x.0 = 5;
  yield;
  dbg!(x.0);
}
```

In this case `x.1` is never initialized. This still presents a special case, because we cannot have a partially-unitialized field in a regular struct or enum type.

One way to remove the special-casing in miri is to wrap the type of every generator field in `MaybeUninitialized` when we return it from [`rustc::ty::layout::field()`](https://github.com/rust-lang/rust/blob/1962adea6ad9b992516ae56ad7f8c5bc33b951cb/src/librustc/ty/layout.rs#L1723). This required making `MaybeUnitialized` a lang item, though, and doesn't actually give us any new features.

Eventually, I think we'd like to handle aggregate fields explicitly, so we can sanitize UB in generators.

**Comment by tmandry** [comment]
cc @RalfJung @Zoxc @eddyb @cramertj

**Comment by RalfJung** [comment]
> Right now, saved locals in generators are special-cased in miri, because they might not always be initialized.

In Miri and [in layout code](https://github.com/rust-lang/rust/blob/b982867a7349f84c17317599b59aeb5a7d8a83be/src/librustc/ty/layout.rs#L2032), and for the same reason.

**Comment by RalfJung** [comment]
> This required making MaybeUnitialized a lang item, though, and doesn't actually give us any new features.

Well, it gives us a "more correct" layout for generators, for some notion of correctness. Also technically we wouldn't have to do this for *every* field, if you know which fields can be partially initialized for a particular yield point you can encode that. And that might give us layout optimizations.

**Comment by nikomatsakis** [comment]
Marking as "deferred" from a stabilization perspective.

**Comment by RalfJung** [comment]
@tmandry in https://github.com/rust-lang/rust/pull/69257, I removed the generator hack and everything still seems to work. Is that expected? Has generator layout been fixed (e.g. by https://github.com/rust-lang/rust/pull/69257 -- though I thought someone said that would not fix this issue)?

**Comment by tmandry** [comment]
@RalfJung IIRC, you're basically relying on an implementation detail of how MIR gets built, which is that it doesn't leave partially-initialized aggregates in the generator prior to `yield`ing (it only creates aggregates once all their pieces are initialized).

But if this changed, it would probably mean the layouts we report for generators are wrong. So it's probably best if this gets relied on and tested by miri (in addition to testing in rustc).

Just to double check -- would [this test](https://github.com/rust-lang/miri/blob/331175638f9ac30dc19c87f3a86521e3f1dea962/tests/run-pass/generator.rs#L93-L97) fail if the aggregate were actually created?

**Comment by RalfJung** [comment]
> Just to double check -- would this test fail if the aggregate were actually created?

It would definitely fail if Miri's layout-guided recursive descend would ever actually hit a field of `!` type. As in, if the code actually claimed to have created a `(String, !)` aggregate (and, say, pass it somewhere by value), that should cause an error.

> it doesn't leave partially-initialized aggregates in the generator prior to yielding (it only creates aggregates once all their pieces are initialized).

So, in that test case, the generator does not preserve a `(String, !)` across the yield point, only a `String`? I think it has to, or else it would have to say that it is a `MaybeUninit<(String, !)>`.

**Comment by nikomatsakis** [comment]
> you're basically relying on an implementation detail of how MIR gets built, which is that it doesn't leave partially-initialized aggregates in the generator prior to yielding (it only creates aggregates once all their pieces are initialized).

I would not call this an implementation detail. If we were going to change this, we'd have to have some other modification to MIR to "signal" when the aggregate is fully constructed (it's relevant to borrow check, for example, and it affects visible drop order as well).

**Comment by tmandry** [comment]
> So, in that test case, the generator does not preserve a `(String, !)` across the yield point, only a `String`? I think it has to, or else it would have to say that it is a `MaybeUninit<(String, !)>`.

Correct.

> I would not call this an implementation detail. If we were going to change this, we'd have to have some other modification to MIR to "signal" when the aggregate is fully constructed (it's relevant to borrow check, for example, and it affects visible drop order as well). Not to say we _can't_ change it, but we can't do it lightly and without affecting other systems.

Okay, that makes me feel better then :)

**Comment by RalfJung** [comment]
I suppose this means we can close this issue? I also [extended the Miri test](https://github.com/rust-lang/miri/pull/1203/files) to try harder to catch invalid generator states by doing typed (and thus validated) copies of the entire generator after each yield (and then discarding them again, so this does not constitute "moving" the generator).

**Comment by tmandry** [comment]
Yep! That looks great, closing now.
