### ISSUE TITLE
Make a PDF version of the documentation.

### ISSUE THREAD

**Issue by catastrop** [rust-lang/rust#60906]
Everybody doesn't have a internet connection all the time.

**Comment by MSleepyPanda** [comment]
When you install rust via rustup, you'll have a local copy of the documentation. See this question on [stackoverflow](https://stackoverflow.com/questions/27592046/how-can-i-download-rust-api-docs).

Also cc https://github.com/rust-lang/rust/issues/20866

**Comment by catastrop** [comment]
I want a pdf

**Comment by jonas-schievink** [comment]
Rustdoc can not generate PDF output right now. Adding first-class support for that in the current architecture is very tricky, and crates for generating PDFs are still pretty immature. As a workaround, you can print the website to PDF, but it's not going to look very nice. I suggest just using the locally installed HTML docs instead.

**Comment by GuillaumeGomez** [comment]
This is clearly not a priority for the moment. Also I'm curious: what is wrong with using locally generated documentation? Why would you prefer using a PDF?

**Comment by hellow554** [comment]
@jonas-schievink  this is a dup of https://github.com/rust-lang/rust/issues/60577

@catastrop you can use `rustup doc --std` to open the standard API

**Comment by jonas-schievink** [comment]
True, closing in favor of https://github.com/rust-lang/rust/issues/60577

**Comment by catastrop** [comment]
Provide a pdf

**Comment by catastrop** [comment]
Why this is so hard to make a pdf? I have created a similar issue but no one response. All of them are closed.

Is this really too hard. Or just ......

**Comment by GuillaumeGomez** [comment]
Because the documention is **HUGE**. Besides, it works locally, why needing a PDF then?
