### ISSUE TITLE
please consider to include rust-std-thumbv7neon-unknown-linux-gnueabihf into the rust-armv7-unknown-linux-gnueabihf archive on static.rust-lang.org

### ISSUE THREAD

**Issue by stefson** [rust-lang/rust#60905]
hey there, firefox want's to see the additionall rust-std `thumbv7neon-unknown-linux-gnueabihf` if one uses >=rust-1.34 and passes --enable-neon, on armv7 + linux toolchain. 

so, do you think you could add this rust-std library into the snapshots hosted on static.rust-lang.org, and maybe make them installable as an option via the --components switch of install.sh? 

I know there's rustup, but my distro doesn't fancy it so much :-)

**Comment by jonas-schievink** [comment]
Seems to me that this would be way simpler to solve by just using rustup...

**Comment by stefson** [comment]
We use a systemwide installation of rust, using rustup as package manager for managing the rust toolchain simply isn't going to happen. Anyway, I managed to find a way to install additional std with distros package manager, therefore closing.
