### ISSUE TITLE
Error message for question mark operator should message conversion

### ISSUE THREAD

**Issue by sunjay** [rust-lang/rust#60917]
I've been working with a lot of people who are either new to Rust or new to its latest features (like the question mark operator) and I'm noticing a lot of confusion around a specific error message.

Suppose you have the following code:

```rust
#[derive(Debug)]
struct Error1;
#[derive(Debug)]
struct Error2;

fn foo() -> Result<(), Error1> {
    Err(Error1)
}

fn main() -> Result<(), Error2> {
    foo()?;
    
    Ok(())
}
```

This gives you the error:

```
error[E0277]: the trait bound `Error2: std::convert::From<Error1>` is not satisfied
  --> src/main.rs:11:5
   |
11 |     foo()?;
   |     ^^^^^^ the trait `std::convert::From<Error1>` is not implemented for `Error2`
   |
   = note: required by `std::convert::From::from`
```

However, if you look at the actual code, it isn't obvious where the `From` trait is even being used.

The [documentation for the `From` trait](https://doc.rust-lang.org/std/convert/trait.From.html) actually does mention this briefly, though most people I encounter don't go as far as looking that up. The error message is pretty daunting if you're new to the language.

I propose that we add something to the error message when we see that they are using the question mark:

```
help: the question mark operation (`?`) implicitly performs a conversion
      on the error value using the `From` trait. If no conversion is
      defined, you will see this error message.
```

This conveys exactly where the `From` trait is being used and why they may be running into this issue. You certainly don't have to use this exact wording. Feel free to use whatever fits. :)

**Comment by estebank** [comment]
For what it's worth, [the current output points at the question mark now](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=a940a39dbcaa3175853c05e358040625):

```
error[E0277]: `?` couldn't convert the error to `Error2`
  --> src/main.rs:11:10
   |
11 |     foo()?;
   |          ^ the trait `std::convert::From<Error1>` is not implemented for `Error2`
   |
   = note: required by `std::convert::From::from`
```

**Comment by sunjay** [comment]
Thanks! That's a good start. I find that just pointing to it isn't enough because people don't even know that the question mark operator performs a conversion. The [edition guide] (https://doc.rust-lang.org/edition-guide/rust-2018/error-handling-and-panics/the-question-mark-operator-for-easier-error-handling.html) (a top result for looking up "rust question mark operator") doesn't even reference the From trait.

**Comment by estebank** [comment]
Does https://github.com/rust-lang/rust/pull/60924 look like what you had in mind, @sunjay?
