### ISSUE TITLE
Should #[naked] functions default to #[inline(never)] ?

### ISSUE THREAD

**Issue by fintelia** [rust-lang/rust#60919]
Currently, the compiler is allowed to inline naked functions if it wants to. For a normal function, inlining is fine because the compiler can remove the function prologue/epilogue and the remaining will behave as expected. However for naked functions, the developer provides the prologue/epilogue and those *aren't* removed by the compiler. This almost surely will result in incorrect behavior. Accordingly I think it would make sense for the compiler to not inline naked functions unless the developer explicitly opted-in.

**Comment by comex** [comment]
In the other thread, alistair23 found that [Clang automatically marks naked functions as noinline.](https://github.com/llvm/llvm-project/blob/master/clang/lib/CodeGen/CodeGenModule.cpp#L1539)

**Comment by npmccallum** [comment]
Yes, `#[naked]` functions should imply `#[inline(never)]`.
