### ISSUE TITLE
Reinstate edition-guide toolstate check

### ISSUE THREAD

**Issue by ehuss** [rust-lang/rust#60929]
This is a tracking issue for reverting the change introduced in #60791 which disabled the toolstate check for the edition-guide.

It is currently blocked on #60459 which is causing a test failure in the edition-guide.  I will reinstate the check as soon as that issue is fixed.

@Mark-Simulacrum has requested the labels t-release and I-nominated.

**Comment by Mark-Simulacrum** [comment]
Tags are so that we don't forget this, we should keep it nominated until it's fixed.

**Comment by pietroalbini** [comment]
The check has was reinstated in PR https://github.com/rust-lang/rust/commit/8d419588f1ce626c37cc05780c8eb37322726fa4.

**Comment by ehuss** [comment]
@pietroalbini I think you have the wrong issue?  There were two things (rls and edition guide).  The PR you noted just reverted the RLS change.  The edition-guide was separate (and done in a different way).  It's still blocked on #60459.

**Comment by pietroalbini** [comment]
...oh, that's what happen when I read just half of the title :sweat_smile:

**Comment by pnkfelix** [comment]
triage: P-high. Assigning to self. Will likewise triage #60459. Removing nominated tag.

**Comment by pnkfelix** [comment]
actually I'll leave nominated tag, since this is for a team other than T-compiler so I don't want to mess with their tags.
