### ISSUE TITLE
`use some::module::self;` and `use some::module;` not semantically equivalent

### ISSUE THREAD

**Issue by jrobsonchase** [rust-lang/rust#60941]
In instances where a path can represent both a module and a function or macro, the `self` import will only import the module and not the function/macro, whereas everything will be imported if the `use` statement ends with just the module/macro/function name.

This causes issues with `rustfmt`'s `merge_imports` option: https://github.com/rust-lang/rustfmt/issues/3362

If rustc is "working as intended," the behavior is such that `merge_imports` will never be able to safely create `self` imports.

**Comment by jonas-schievink** [comment]
@petrochenkov might know about this

**Comment by jrobsonchase** [comment]
@Nemo157 referred me to [this issue](https://github.com/rust-lang/rust/issues/51845) that came up before, but I couldn't find any reference in any of the linked issues to how `self` imports are supposed to be treated.

**Comment by petrochenkov** [comment]
This is working as intended :)

The thing before `::` (e.g. `foo` in `foo::bar` or `foo::self`) is always a type/module, so path resolutions can never "bifurcate" in the middle, so a path can resolve to 3 things at most, determined entirely by the last segment.

**Comment by gnzlbg** [comment]
@petrochenkov why can't we make `self` special here ?

**Comment by jrobsonchase** [comment]
I'm with @gnzlbg; this seems unnecessarily confusing. Intuitively, `use something::{self};` should be the same as `use something;`, and I feel like that's how the vast majority of people interpret the syntax. It's going to get extra weird when people start taking imports like

```rust
use foo::{
    self,
    bar,
    baz,
};
```
, delete `bar` and `baz`, and then get confused when rustfmt [does the right thing](https://github.com/rust-lang/rustfmt/issues/3568) and leaves them with `use foo::{self};`. At least the opposite case with `merge_imports = true` (`use foo::bar; use foo::baz; use foo` -> `use foo; use foo::{bar, baz};`[^1]) doesn't look obviously *wrong*.

[^1]: Not yet fixed, rustfmt still produces `self` imports

Also, it seems inconsistent since I don't see an obvious way to get at *just* a function or macro, while you *can* get only the module with `self` imports.
