### ISSUE TITLE
🔍 Improving search on docs with Algolia's DocSearch

### ISSUE THREAD

**Issue by Shipow** [rust-lang/rust#60956]
Hello Rust Lang team,<br><br>I've noticed that your documentation could take advantage of our <a href='https://community.algolia.com/docsearch/'>DocSearch</a> initiative.<br><br>So, we went on <b>trying to improve the search and came up with this demo:</b><br>💖<a href='https://docsearch-rust-lang.netlify.com/'>Try out the search here</a> 💖 (we've added docsearch.js to a mirror of your docs).<br><br>Algolia's DocSearch is crawling the website every 24h, extracting content from every page. Then this content is made searchable by Algolia's API and exposed to the user with a searchbox and its custom dropdown.<br><br>You might have already used DocSearch on some popular docs like <a href='https://getbootstrap.com/docs/4.1/getting-started/introduction/'>Bootstrap</a>, <a href='https://vuejs.org/v2/guide/'>Vue</a>, <a href='https://api.jquery.com/'>jQuery</a>, <a href='https://reactjs.org/docs/getting-started.html'>React</a>, <a href='https://jestjs.io/docs/en/api'>Jest</a>, <a href='https://docs.gitlab.com/'>Gitlab</a>, <a href='https://docs.brew.sh/'>Brew</a>, <a href='https://devcenter.heroku.com/'>Heroku</a>, <a href='https://support.invisionapp.com/'>Invision</a>, <a href='https://stripe.com/docs'>Stripe</a>, <a href='https://www.algolia.com/doc/'>Algolia</a>, ...<br>So far, we are maintaining our crawler for 1500+ docs.<br><br><img src='https://res.cloudinary.com/hilnmyskv/image/upload/v1558102381/docsearch-dropdown.png' alt='docsearch autocomplete preview'><br><br><ul><li><a href='https://community.algolia.com/docsearch/'>DocSearch</a> is fast, it handles typos and highlighting.</li><li>Search results jump directly to the matching part of the page.</li><li>Whenever your markup changes you can <a href='https://github.com/algolia/docsearch-configs/blob/master/configs/rust-lang.json'>customize the configuration</a> on DocSearch repository.</li><li>You'll also have access to a dashboard of the most queried terms, as well as those that yields no results. We found it to be a very good way of knowing how to improve our documentation.</li><li>DocSearch is and will remain <b>FREE</b> (provided by <a href='https://www.algolia.com/'>Algolia</a>).</li></ul><br><b>Are you interested? 👍 👎</b><br><br><br>Ping @shipow or @s-pace<br>

**Comment by csmoe** [comment]
cc @rust-lang/rustdoc

**Comment by jonas-schievink** [comment]
This doesn't seem to index rustdoc output, just the books.

Personally I'm not a big fan of depending on an external service just for searching the books. This just seems like free advertising for Algolia. If someone is interested in improving the book search, they could always contribute to [mdBook](https://github.com/rust-lang-nursery/mdBook) directly. That way, the search would also work offline. Will this search degrade gracefully (using the existing mdBook search) when the service isn't reachable?

**Comment by Shipow** [comment]
Hi @jonas-schievink, thanks for your feedback.

Depending on a tiers party is always a tricky choice that needs to be carefully evaluated. I believe the main topics to look at are cost, privacy, dependency and availability.

DocSearch has been created 4 years ago as a giveback to the community. As you noticed, the service is provided by Algolia which as a strong relation with open source. We only ask the project to display the Algolia logo at the bottom of the opened dropdown. There is no hidden cost, it's free.

About the data, Algolia gives the owners the possibility to learn more about the search usage through its dashboard but every queries are anonymized, users are safe. 

Concerning the offline support, we are not covering this use case and most of the time the search is just made unavailable when browsing the online documentation offline. Algolia does provide some tools for handling this, but we don't support it yet. It's i believe an advanced UX case.
DocSearch is relaying on Algolia's infrastructure which is handling some heavy load on big ecommerce websites where the search feature is crucial. On the availability part, we you got you covered! ;)

Implementing DocSearch is just few lines of js, the product is not perfect yet but we are aiming  the state of the art with the help of the community. Basically if your users don't like it, removing it or contributing to improve it would be easy! Also we do free support. All day long.

I'd be happy to ear more about your concerns on those points.

**Comment by jonas-schievink** [comment]
I know that offline capabilities are important to many people here, and this change would potentially regress them (depending on how it's integrated). However I don't really have any say in this and will defer this to the docs team to decide.

**Comment by Shipow** [comment]
Thanks, this kind of feedback help us improve. If offline search in the documentation is a thing, we'll add it to the roadmap. I don't have any data on this yet but i'm planning to send a survey so I'll add this part for sure.

**Comment by GuillaumeGomez** [comment]
Currently, rust docs search doesn't need a server and works offline. We want to keep it this way. However, improving the rust docs search process itself would be very appreciated. Thanks for the proposition though and good continuation!
