### ISSUE TITLE
Printing warnings about use of std::process::Command::args(&std::path::PathBuf)

### ISSUE THREAD

**Issue by hkcorac** [rust-lang/rust#60954]
Hello Rust developers,

Recently I found a small issue with my code. For example:

```rust
use std::path::PathBuf;
use std::process::Command;

fn main() {
    let this_file = PathBuf::from(file!()).canonicalize().unwrap();
    Command::new("echo").args(&this_file).status().unwrap();
}
```

Note that we pass a reference `&pathBuf` to `args()` -- not `arg()`. That call will break up the path into multiple parts, and send them to target command.

For example if the file is `/a/b/c/main.rs`, then `echo` will print:

```shell
/ a b c main.rs
```

The issue is:

- `Command::args()` accepts `IntoIterator<Item = AsRef<OsStr>>`.
- `&'a PathBuf` implements `IntoIterator<Item = &'a OsStr>`.

From my use, I mistyped `arg()` as `args()`. My consequence was bad: my target program was `tar`, and it started compressing whatever it could touch in the path. Luckily I discovered that and stopped it when the compressed file was just about 2+ GB.

This is not a bug. However, would you please make Cargo print a warning when it encounter such a misuse?

Thank you,

**Comment by jonas-schievink** [comment]
This sounds like something [Clippy](https://github.com/rust-lang/rust-clippy) could do.

**Comment by hkcorac** [comment]
Thank you, that helps me.

I'm closing this issue.
