### ISSUE TITLE
Error about drop in `const fn` without any dropping happening

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#60964]
The `take_inner` function won't ever evaluate a destructor. This is a bug in `const_qualif` I think

```rust
pub struct Wrapper {
    inner: String,
}

pub const fn take_inner(w: Wrapper) -> String {
    w.inner
}
```

([Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=b8e295330e924263e8c29ec68871becf))

Errors:

```
   Compiling playground v0.0.1 (/playground)
error[E0493]: destructors cannot be evaluated at compile-time
 --> src/lib.rs:5:28
  |
5 | pub const fn take_inner(w: Wrapper) -> String {  // <<< lint suggestion here fails to compile
  |                         ^ constant functions cannot evaluate destructors

error: aborting due to previous error

error: Could not compile `playground`.

To learn more, run the command again with --verbose.

```

**Comment by ecstatic-morse** [comment]
This particular example is fixed by `#![feature(const_precise_live_drops)]` (#73255), which moves live drop checking for constants after drop elaboration. I think we can close this?
