### ISSUE TITLE
The dangle function in docs should be marked as "Does not compile"

### ISSUE THREAD

**Issue by PunKeel** [rust-lang/rust#60975]
https://doc.rust-lang.org/book/ch04-02-references-and-borrowing.html

Right under this sentence, the code does not compile - but is not marked as such
>Let’s take a closer look at exactly what’s happening at each stage of our dangle code:

![](https://pbs.twimg.com/media/D7Ase2DWkAELxU1.jpg)

**Comment by steveklabnik** [comment]
Hi! Thanks for the report; I should have been more clear on twitter. The book's tracker is at https://github.com/rust-lang/book/issues/new, would you mind filing there please? Thanks!
