### ISSUE TITLE
Deprecate try! macro in favor of ?

### ISSUE THREAD

**Issue by BO41** [rust-lang/rust#61000]
I propose to mark the [`try!`](https://doc.rust-lang.org/nightly/std/macro.try.html) macro as deprecated.

---

Reasons for it:
- `?` was [stabilized in 1.13](https://blog.rust-lang.org/2016/11/10/Rust-1.13.html#the--operator), November 2016. **2+years** ago
- there is an [interest](https://github.com/rust-lang/rust-clippy/issues/1361) in having a lint for replacing `try!` with `?` for  **2+years** 
- `try` is a keyword in [rust 2018](https://github.com/rust-lang/rust/issues/50412) and needs to be written as `r#try!`
- "["The Rust Programming Language", 2nd edition (book)](https://doc.rust-lang.org/book/second-edition/) and ["Rust by Example"](https://doc.rust-lang.org/stable/rust-by-example/) have both already removed all mentions of `try!`."
- the [doc of `try!`](https://doc.rust-lang.org/nightly/std/macro.try.html) literally names the definition of deprecation
> The `?` operator was added to replace `try!` and should be used instead.

---
There are no real downsides :smiley: 
(I am happy to wait for https://github.com/rust-lang/rust/issues/37939 ;)

**Comment by Centril** [comment]
I did some investigation on the playground and it seems that the reason `r#try!` isn't deprecated yet is because `macro_rules!` cannot be deprecated at all. cc @petrochenkov

**Comment by BO41** [comment]
Thanks for the response @Centril .
Seems like this is true.

I thought you could deprecate any struct/function/etc :grimacing:

**Comment by petrochenkov** [comment]
>because macro_rules! cannot be deprecated at all

The issue is https://github.com/rust-lang/rust/issues/49912, someone (not me) needs to do the work.

**Comment by BO41** [comment]
>Deprecation and stability checking is actually done after macro expansion

So I assume clippy can't check this either, or am I wrong?

Otherwise we could make a general clippy lint for `#[deprecated]` on macros
(which would solve #49912 as well).

**Comment by petrochenkov** [comment]
>Deprecation and stability checking is actually done after macro expansion

It can work at any point if name resolution results are available.
Stability checking is already implemented for macros and deprecation checking can be done by analogy.

**Comment by lzutao** [comment]
I take this at #62672 .
