### ISSUE TITLE
Why Rust uses LLVM? It is written in C++. Why rust isn't completely self-hosted?

### ISSUE THREAD

**Issue by catastrop** [rust-lang/rust#61013]

**Comment by jonas-schievink** [comment]
Hi! This issue tracker is mainly meant for bug reports and concrete, small feature requests. Questions like this are better asked in the user forum at https://users.rust-lang.org/ or on [one of the chat platforms](https://www.rust-lang.org/community) used by the Rust community.

**Comment by catastrop** [comment]
This is a feature request.

**Comment by jonas-schievink** [comment]
Rewriting LLVM in Rust is out of scope for this project, but if you're looking for a code generator written in Rust then [Cranelift](https://github.com/CraneStation/cranelift) might be what you're looking for. There are plans to add it as a rustc backend in addition to LLVM (check the docs in the repo I linked for details).

**Comment by LifeIsStrange** [comment]
This is like saying "why not throw away 317 000 commits of work by experts for a slight idiomatic improvement".
At most one could suggest to llvm developers, to accept new llvm modules written in rust, those incrementally rustifying llvm.
Even with that, I'm not sure it would be an improvement as most llvm would have a costly technical debt, and rust has sometimes worse codegen than llvm + currently lack some "big" features they are used to.

**Comment by catastrop** [comment]
they created rust because c++ isn't good enough for their need. If c++ is bad why they use llvm?
