### ISSUE TITLE
Array comparison shouldn't forward to slice implementation

### ISSUE THREAD

**Issue by rickvanprim** [rust-lang/rust#61012]
Currently the PartialEq and PartialOrd traits for the array primitive forward to the slice implementations.

https://doc.rust-lang.org/src/core/array.rs.html#81-86
```
macro_rules! __impl_slice_eq1 {
    ($Lhs: ty, $Rhs: ty) => {
        __impl_slice_eq1! { $Lhs, $Rhs, Sized }
    };
    ($Lhs: ty, $Rhs: ty, $Bound: ident) => {
        #[stable(feature = "rust1", since = "1.0.0")]
        impl<'a, 'b, A: $Bound, B> PartialEq<$Rhs> for $Lhs where A: PartialEq<B> {
            #[inline]
            fn eq(&self, other: &$Rhs) -> bool { self[..] == other[..] }
            #[inline]
            fn ne(&self, other: &$Rhs) -> bool { self[..] != other[..] }
        }
    }
}
```

However this introduces an unnecessary size check which has already been validated at compile time.

Apologies if this is already a known issue awaiting on const generics to solve.

**Comment by jonas-schievink** [comment]
Are you sure LLVM doesn't optimize this out? It only needs to constant-propagate the array length.

**Comment by rickvanprim** [comment]
Compiled in Stable with Release target.
```
#[no_mangle]
fn foo(a: [u8; 16], b: [u8; 16]) -> book
{
    a == b
}
```
Produces:
```
foo:
	cmpq	%rsi, %rdi
	je	.LBB0_1
	movdqu	(%rdi), %xmm0
	movdqu	(%rsi), %xmm1
	pcmpeqb	%xmm0, %xmm1
	pmovmskb	%xmm1, %eax
	cmpl	$65535, %eax
	sete	%al
	retq

.LBB0_1:
	movb	$1, %al
	retq
```

I'm just assuming the branch in there is the length check.  Regardless it seems like this shouldn't output a branch.

**Comment by jonas-schievink** [comment]
I'm pretty sure that compares the addresses of the arrays and early-returns `true` when they're pointing to the same array (arrays are passed via address internally on x86-64).

**Comment by rkruppe** [comment]
Yes, this is an early-out for returning true, not a size comparison for safety or for returning false early. It's still redundant in this case because the two parameters will never be equal.

**Comment by jonas-schievink** [comment]
(annotated asm to make it more clear what's happening)
```
foo:
	cmpq	%rsi, %rdi  ; compare array pointers
	je	.LBB0_1     ; same array? return `true` early
	movdqu	(%rdi), %xmm0  ; move one array into XMM0 (16 Byte register)
	movdqu	(%rsi), %xmm1  ; move the other array into XMM1
	pcmpeqb	%xmm0, %xmm1 ; byte-wise compare arrays, set byte in XMM1 to `0xFF` when equal, to `0x00` if not
	pmovmskb	%xmm1, %eax  ; move the MSb of all result bytes into the low 16 bits of `eax`
	cmpl	$65535, %eax  ; compare packed mask with 65535 (all 16 bits set)
	sete	%al  ; set return value to 1 if all 16 bits are set (equal), to 0 if not
	retq

.LBB0_1:
	movb	$1, %al  ; same array, return `true` early
	retq
```

**Comment by rickvanprim** [comment]
Thanks for the additional context!  Is this worth keeping open on the unnecessary pointer compare (for this case where the parameters are by value), or should I close this?

**Comment by nagisa** [comment]
@rkruppe I’m fairly confident it is possible for `a` and `b` to be comparable at a machine level, e.g.

 ```
  static ARR: [u8; 16] = [0; 16];
foo(ARR, ARR);
```

generates

```asm
# %bb.0:
	leaq	playground::ARR(%rip), %rdi
	movq	%rdi, %rsi
	jmpq	*foo@GOTPCREL(%rip)     # TAILCALL
                                        # -- End function
```

making both arguments have the same address. Thus closing as not applicable.

**Comment by rkruppe** [comment]
Oh, huh, in retrospect that makes sense (we do the copy to a local stack slot explicitly in the IR, rather than leaving it to the ABI lowering in the backend). Good catch!
