### ISSUE TITLE
std::arch docs are missing (404)

### ISSUE THREAD

**Issue by kornelski** [rust-lang/rust#61038]
The `std::arch` module is not documented since 1.34 release:

* https://doc.rust-lang.org/std/arch/ = 404
* https://doc.rust-lang.org/stable/std/arch/ = 404
* https://doc.rust-lang.org/nightly/std/arch/ = 404
* https://doc.rust-lang.org/1.33.0/std/arch/ = present

**Comment by hellow554** [comment]
https://doc.rust-lang.org/1.34.0/src/std/lib.rs.html#361

```
#[doc(no_inline)]
```

CC https://github.com/rust-lang-nursery/stdsimd/pull/640

@rustbot modify labels: T-doc

**Comment by hellow554** [comment]
@gnzlbg  maybe you can enlighten me, why you choose `#[doc(no_inline)]`?

**Comment by gnzlbg** [comment]
> maybe you can enlighten me, why you choose `#[doc(no_inline)]`?

See https://github.com/rust-lang/rust/pull/57808#issuecomment-457390549 and the conversation around that.

**Comment by kornelski** [comment]
OK. It's intentional. 

Google still ranks older version of /std/…/arch higher than latest /core/arch, but that's another problem.

**Comment by gnzlbg** [comment]
FWIW I think that we should try to do better here.

In stdsimd itself, we just provide different docs of the crates, one for each target. In libc we do the same. But libstd tries to compile libcore/liballoc/libstd for all targets/target-features/... at once, and then generate a single "doc" web-site containing the info for all of them at once, and to present it nicely. The problem itself is hard, and the current approach has limitations like this one.

@QuietMisdreavus an alternative here would be to not try to generate the docs all at once, but to, e.g., compile the libstd docs for the different targets, generating multiple docs, and then as a post-processing step, manually merge them for the `core::arch`/`std::arch` modules.
