### ISSUE TITLE
Rename type to typedef.

### ISSUE THREAD

**Issue by heckad** [rust-lang/rust#61049]
I think using keyword `type` to define new types big mistake, because the type can be in anything struct. (Type of order, type of filed). Now I shold write `type_` insted of `type` becouse is keyword. I propouse rename `type` to `typedef` in the next big language iteration.

**Comment by jonas-schievink** [comment]
Language changes like this need to go through the RFC process at https://github.com/rust-lang/rfcs. Closing in favor of discussion there.
