### ISSUE TITLE
Enum 6.1 rust book missing

### ISSUE THREAD

**Issue by jamshaid3** [rust-lang/rust#61040]
let some_number = Some(5);
let some_string = Some("a string");

let absent_number: Option<i32> = None; // IN THIS LINE (None) must be Option::None

**Comment by jonas-schievink** [comment]
Thanks for reporting! The book is hosted at https://github.com/rust-lang/book/ though, so please open an issue there (or directly submit a PR).

**Comment by hellow554** [comment]
Are we talking about this one: https://doc.rust-lang.org/stable/book/ch06-01-defining-an-enum.html#the-option-enum-and-its-advantages-over-null-values ?

Why do you think it must be `Option::None`? Why not `Option::Some`? The answer is, that `Some` and `None` are in the [prelude](https://doc.rust-lang.org/std/prelude/v1/index.html), therefore you don't need an explicit import.

**Comment by jonas-schievink** [comment]
Right, there's no need to change anything here (the code example is also tested automatically). The issue text is missing the `<i32>` though.
