### ISSUE TITLE
rustdoc: Automatic light/dark theme

### ISSUE THREAD

**Issue by fenhl** [rust-lang/rust#61079]
Websites can now automatically switch between light and dark themes based on system settings using [`prefers-color-scheme`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme). It would be nice if rustdoc had a theme that looks like the light theme by default but looks like the dark theme in the `@media (prefers-color-scheme: dark)` condition. Since this is backward-compatible with the current default being the light theme, it could even be made the new default.

**Comment by GuillaumeGomez** [comment]
We can't do it through CSS directly, however it's possible to have a workaround with JS. I'll give it a try soon.
