### ISSUE TITLE
Ambiguity variable/value in the guessing game section of the book

### ISSUE THREAD

**Issue by fxn** [rust-lang/rust#61101]
Hi! I am absolutely new to Rust.

I have started reading the book online, and after introducing the concept of mutable and inmutable _variables_ in the chapter where the guessing game is developed, the explanation for

```rust
io::stdin().read_line(&mut guess)
    .expect("Failed to read line");
```

is that you need to pass to `read_line` a mutable _string_.

This is not consistent with the wording so far, I believe. We have defined what is a mutable _variable_. I interpret a string is the _value_ the variable holds, different.

Probably, an experienced Rustacean is used to some abuse of language, or they know what the text means. But to a totally newcomer, the concept of mutable value is undefined at that early point in the book.

**Comment by jonas-schievink** [comment]
This should be filed over at https://github.com/rust-lang/book/
