### ISSUE TITLE
Rust version 1.35.0 - rustc error after update

### ISSUE THREAD

**Issue by shyaamsundhar** [rust-lang/rust#61112]
Hello,
I just updated rust to 1.35.0 using rustup. After updating I tried to check the version using rustc command, But I got the following error:
![image](https://user-images.githubusercontent.com/6845982/58307113-49ddcc00-7e1b-11e9-9dbf-50bced39f061.png)

The OS is Windows 10 (1709)

Kindly let me know if any additional details are needed.

**Comment by mati865** [comment]
Are you using msvc or gnu version?

**Comment by shyaamsundhar** [comment]
> 
> 
> Are you using msvc or gnu version?


I was using msvc. 

Additional information:
After update the rustup command also seems to have been removed.

![image](https://user-images.githubusercontent.com/6845982/58320189-bd420680-7e38-11e9-85bc-7a68ecc3412a.png)

**Comment by mati865** [comment]
Check if you still have `%userprofile%/.cargo/bin` in your PATH and try running rustup directly from there.

@rustbot modify labels: +O-windows-msvc

**Comment by shyaamsundhar** [comment]
Okay. To solve this, all I had to do was download rustup-init.exe from rust lang website and install again. 
Now problem solved. Closing this issue. 

![image](https://user-images.githubusercontent.com/6845982/58321181-19a62580-7e3b-11e9-9ef2-3148f1752498.png)
