### ISSUE TITLE
What about a `Take` trait?

### ISSUE THREAD

**Issue by lachlansneff** [rust-lang/rust#61148]
I saw issue #61129, and thought that it might be a good idea to generalize it.

The prelude could export a new trait called `Take`.

```rust
pub trait Take {
    fn take(&mut self) -> Self;
}
```

A lot of types could implement it, `Vec<T>` for example. The `take` method on `Option<T>` could be moved into this trait, etc.

The `Take` trait could even be implemented for every type that implements `Default`:

```rust
impl<T> Take for T
where
    T: Default
{
    fn take(&mut self) -> Self {
        mem::replace(self, Default::default())
    }
}
```

**Comment by czipperz** [comment]
This was suggested in the other thread. However, it doesn't seem to make much sense to override this in any other way that the default implementation.

**Comment by jonhoo** [comment]
Yeah, I have the same suspicion as @czipperz -- how often do you expect the implementation for this to differ from replacing with the default?

**Comment by czipperz** [comment]
It also would suffer from the fact that traits must be explicitly implemented. Anyway, thank you for your comment and contribution to the discussion!

**Comment by Mark-Simulacrum** [comment]
I think this is essentially a topic for discussion and we don't really have any clear idea of what we'd use this for (there's also https://github.com/rust-lang/rust/issues/61129 where this idea has already been discussed quite a bit). If you'd like to discuss this further I would do so on internals. Thanks!
