### ISSUE TITLE
cargo has to be installed before buildng rust from source code?

### ISSUE THREAD

**Issue by BaoshanPang** [rust-lang/rust#61142]
In README.md, there is:

>>then run these two commands and then try sudo ./x.py install again:

>>$ cargo install cargo-vendor
>>$ cargo vendor

But later it also says:
>> This install does not include Cargo, Rust's package manager, which you may also want to build.

So for the 'cargo' used above, where it comes from? Do we have to instal cargo before building rust from source code?

**Comment by sanxiyn** [comment]
Rust build system automatically downloads Cargo to be used for build. Exactly what is downloaded is specified in `src/stage0.txt`.

**Comment by BaoshanPang** [comment]
Hi Danxiyn,

Thanks for your help.
From stage0.txt, I see a beta cargo would be downloaded for build:
date: 2019-03-20
rustc: beta
cargo: beta

Is there a way to tell the system to download a nightly version? I am asking this question because I need to use command "cargo update" in the build source tree, but this function is only supported in nightly version.

Thanks,
Baoshan

**Comment by sanxiyn** [comment]
Rust issue tracker is not a Q&A board. You may have better luck at https://internals.rust-lang.org/.

As for the title of this issue, the answer is no. Cargo does not need to be installed before building Rust, because build itself does installation for you. Closing.
