### ISSUE TITLE
suggest syntax `pub:` affect all the following member

### ISSUE THREAD

**Issue by micfan** [rust-lang/rust#61158]
How do you like this kind syntax like c++?

```
struct Something {
    // by default member is private
    priv_a: usize

// the `pub:` syntax can make all the following member public
pub:
    pub_a: String,
    pub_b: i32,
    pub_c: i32,
    pub_d: i32,
}
```

**Comment by hellow554** [comment]
This kind needs a RFC. Please go to https://github.com/rust-lang/rfcs/ and check out the readme and see what steps to take to open one.

@rustbot modify labels: C-feature-request T-lang needs-rfc

**Comment by hellow554** [comment]
Hmmm. Any good reason for this?

**Comment by micfan** [comment]
Yes, needs a RFC. Just have thought of C++ access control syntax
