### ISSUE TITLE
azure: Enable [RUSTC-TIMING] log lines in Azure Pipelines

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#61163]
Currently in Travis CI and AppVeyor we output lines like this one in the build logs:

```
[00:49:42] [RUSTC-TIMING] chalk_macros test:false 0.948
```

These lines are emitted by rustbuild and are used to analyze how much time is spent in each compilation step. We should also emit them in Azure.

**Comment by mati865** [comment]
It's enabled but only for `auto` branch:
https://github.com/rust-lang/rust/blob/dec4c5201f88efbc3020b04ba96a5ee2c3b6cfcd/src/ci/run.sh#L28-L30

**Comment by alexcrichton** [comment]
Indeed, they're showing up in the auto logs!
