### ISSUE TITLE
azure: Move most of the bash scripts out of the Azure yamls into separate files

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#61169]
Consider putting any bash script longer than a few lines in a standalone script that can be invoked instead of inlined into yml, perhaps under a /scripts folder.

This allows you to easily run & lint the script, whereas it takes extra steps to do so in yaml.

_Originally posted by @zachChilders in https://github.com/rust-lang/rust/pull/60777_

**Comment by alexcrichton** [comment]
I would personally say that we shouldn't necessarily strive to remove all >1 line scripts from the `*.yml` files. I think there's a lot to benefit from having it all centralized in one location, *especially* if there's different scripts for different platforms. If all our CI platforms share the same script I think it's ok to extract, but once Windows does one thing and Unix does another thing I personally find it more clear to follow scripts inline than to have to chase down a bunch of files to make sure everything is synchronized.

**Comment by pietroalbini** [comment]
This is done.
