### ISSUE TITLE
azure: Figure out data retention in Azure

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#61165]
I saw around the docs and the UI that Azure Pipelines has configurable data retention for build logs. We should configure it to store them indefinitely.

**Comment by calebcartwright** [comment]
This may have changed, but the last time I'd checked into it, the retention for YAML builds was still a bit limited in terms of configurability

Some relevant documentation:
* https://docs.microsoft.com/en-us/azure/devops/pipelines/policies/retention?view=azure-devops
* https://docs.microsoft.com/en-us/azure/devops/release-notes/2018/sprint-142-update#default-retention-for-yaml-pipelines

Others have definitely encountered scenarios when they need to retain a pipeline run indefinitely though. On any completed run (build or release pipeline) there is an option to maintain that specific run indefinitely that can be done manually:
![image](https://user-images.githubusercontent.com/13042488/58597723-d3880200-823e-11e9-936f-6cbb64e77e4a.png)

Folks have also added extensions that allow for adding a step to a pipeline to automatically retain it, such as https://marketplace.visualstudio.com/items?itemName=mmajcica.retain-release. I'm not sure if any of those existing extensions work for builds (I've only used them for release pipelines), but even if they don't, I suspect something very similar could be done for build pipelines.

**Comment by pietroalbini** [comment]
An update, I managed to extend the retention on rustc to 2 years, but we'll discuss this in more depth with Microsoft people in the following days.

**Comment by pietroalbini** [comment]
Discussed this with Microsoft, they're going to follow up privately with us on that. Demoting to P-medium.

**Comment by pietroalbini** [comment]
Triage: no update happened on this. There are still 1.5 years to figure out a solution though.

**Comment by shepmaster** [comment]
Triage: We'll probably be out of Azure when this becomes an issue.

**Comment by shepmaster** [comment]
Although we might need to configure something similar for GHA?

**Comment by pietroalbini** [comment]
We talked about this in the 2020-09-02 infra team meeting, and decided the effort needed to push for this or implement a backup ourselves is not worth it compared to the benefits we'd get from indefinite retention.
