### ISSUE TITLE
Incorrect default object lifetime bounds in 1.34.2

### ISSUE THREAD

**Issue by MaikKlein** [rust-lang/rust#61179]
```
use std::ptr::NonNull;
trait Bar {}
struct Foo;
impl Foo {
    fn get_mut(&mut self, i: usize) -> Option<&mut (dyn Bar)> {
        None
    }
    fn foo(&mut self) {
        unsafe {
            let i1 = self
                .get_mut(0)
                .map(|val| NonNull::new_unchecked(val as *mut dyn Bar));
            if let Some(mut i1) = i1 {
                let mut i2 = self
                    .get_mut(1)
                    .map(|val| NonNull::new_unchecked(val as *mut dyn Bar));
                if let Some(mut i2) = i2 {
                    let r1 = i1.as_mut();
                    let r2 = i2.as_mut();
                }
            }
        }
    }
}
fn main() {}
```

This compiles under 1.34.2, but shouldn't. This doesn't compile in 1.34.0. It appears that the lifetime bounds where assumed to be `'static` in 1.34.2. `Option<&mut (dyn Bar +'static)>`.

**Comment by jonas-schievink** [comment]
> This doesn't compile in 1.34.0.

It build fine for me, however nightly is rejecting the code since `rustc 1.35.0-nightly (87a436377 2019-03-03)`. That is a soundness fix introduced by https://github.com/rust-lang/rust/pull/58673, I believe.

**Comment by jonas-schievink** [comment]
Ah, I think you meant 1.35.0 instead. This is effectively a duplicate of https://github.com/rust-lang/rust/issues/60927 then.

**Comment by MaikKlein** [comment]
Oh yeah it does indeed compile in 1.34.0. I only checked it with https://rust.godbolt.org/z/YpLEHy Maybe not something that I should rely on.

Yeah it seems like a duplicate.
