### ISSUE TITLE
Should "01.01.01.01" be parsed as legal IPv4 ?

### ISSUE THREAD

**Issue by huangjj27** [rust-lang/rust#61186]
original problem: https://leetcode-cn.com/problems/validate-ip-address/
while `std::net::IpAddr::parse` successfully parse the address, but the leetcode problem doesn't regard the address as "legal",

test DEMO:
```
use std::net::IpAddr;

fn main() {
    if let Ok(IpAddr::V4(_)) = "01.01.01.01".parse() {
        println!("parsed!");  // it gets in!
    }
}
```

Usually, we consider IPv4 address containing only non-leading-zero number 0-255 legal, but not those with leading-zero numbers in. Should we change the behavior?

**Comment by kennytm** [comment]
It is definitely legal. Either Leetcode is wrong or the question doesn't suppose you to "cheat" with the standard library.

* <https://01.01.01.01/>

```sh
$ ping 01.01.01.01
PING 01.01.01.01 (1.1.1.1): 56 data bytes
```

```python
>>> import ipaddress
>>> ipaddress.IPv4Address('01.01.01.01')
IPv4Address('1.1.1.1')
```

```go
package main

import (
	"net"
	"fmt"
)

func main() {
	fmt.Println(net.ParseIP("01.01.01.01")) // prints 1.1.1.1
}
```

**Comment by WiSaGaN** [comment]
Are we sure it is not parsing it as octal? https://superuser.com/questions/857603/are-ip-addresses-with-and-without-leading-zeroes-the-same
