### ISSUE TITLE
Examples related to "non-lexical lifetimes" are not updated on doc.rust-lang.org/error-index.html

### ISSUE THREAD

**Issue by gauravvnera** [rust-lang/rust#61183]
It appears that the examples showing borrow errors are not updated to reflect recent changes related to non-lexical lifetimes. For instance, https://doc.rust-lang.org/error-index.html#E0503 shows an example that compiles fine with the latest rust:
```
fn main() {
    let mut value = 3;
    // Create a mutable borrow of `value`. This borrow
    // lives until the end of this function.
    let _borrow = &mut value;
    let _sum = value + 1; // error: cannot use `value` because
                          //        it was mutably borrowed
}
```

**Comment by jonas-schievink** [comment]
E0503 has since been updated. Are there any left, or can this be closed?

**Comment by gauravvnera** [comment]
Thanks for it! Closing the issue.
