### ISSUE TITLE
duplicate_macro_exports lint says it will be a hard error in 2018 but it is still a lint

### ISSUE THREAD

**Issue by ehuss** [rust-lang/rust#61221]
[`duplicate_macro_exports`](https://github.com/rust-lang/rust/pull/50143) is marked as a [future incompatible lint](https://github.com/rust-lang/rust/blob/5187be620c76a313a19b9b596e1bce3a80a345dd/src/librustc_lint/lib.rs#L314-L318).  However, it was never made a hard error, so in 2018 you still get the note:

> this was previously accepted by the compiler but is being phased out; it will become a hard error in the 2018 edition!

and points to a [closed issue](https://github.com/rust-lang/rust/issues/35896).

If I am understanding the terminology correctly, there is a difference between a "hard error" and a "deny by default lint" where a hard error cannot be disabled, correct?

AFAIK, this is the only future incompatible lint (with a specified edition) that does not have a hard error implemented.

I'm not sure if this is intentional or tracked anywhere (I can't find any).  It's a minor pedantic issue, since it is deny-by-default, it seems unlikely to be a problem.  I'm not sure if it should be left as-is, make it a hard error in 2018, or remove the edition from the future note.

cc @petrochenkov

**Comment by petrochenkov** [comment]
I remember making it a deny-by-default lint, but don't remember making it edition-dependent (this is a part of macro modularization, which happened on both editions), perhaps it was an accidental copy-paste.

I'd be ok with making it an error after a crater run.

**Comment by jonas-schievink** [comment]
This is now a hard error from what I can tell.

**Comment by ehuss** [comment]
Was converted to an error in #65785.
