### ISSUE TITLE
Document what happens if `std::iter::Take`'s `n` is greater than the amount of elements

### ISSUE THREAD

**Issue by KizzyCode** [rust-lang/rust#61222]
The documentation of [`std::iter::Take`](https://doc.rust-lang.org/stable/std/iter/struct.Take.html) gives no information about what happens if the underlying iterator yields less elements than `Take` should take.
Does it return less than `n` elements, does it panic, ...

Maybe we should change

> An iterator that only iterates over the first `n` iterations of `iter`.

to something like

> An iterator that only iterates over the first `n` iterations of `iter`. If `iter` yields less elements than `n`, only the amount of elements produced by `iter` will be returned.

However english is not my mother tongue and I'm pretty sure there is a much better formulation than this (even to my ears this sounds clumsy)^^

**Comment by czipperz** [comment]
Well I believe it is correct right now.  It just returns the result of `self.iter.next()`.  It doesn't really care what it returns.  Some iterators restart iteration after one `None`, for example [`Fuse`](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.fuse)

**Comment by howaboutsynergy** [comment]
> for example Fuse

unless I'm missing something, that [Fuse](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.fuse) [example](https://doc.rust-lang.org/std/iter/trait.Iterator.html#examples-21) is [flawed](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2015&gist=4a358180b3a8934f5e6734563675a38b) ie. panics when overflow. (in playground, switch from Debug to Release for a possible fix)

**Comment by Mark-Simulacrum** [comment]
There's not really a notion I think of the amount of elements an iterator returns -- i.e., take will limit the amount of times `Some` could be returned but other than that it'll simply call `next` on the underlying iterator. We could perhaps provide an example that `None` is still returned, e.g., something like the following, but I'm not sure it's super helpful since `None` is the only thing that could really be returned.

```rust
let v = vec![1, 2];
let mut iter = v.into_iter().take(5);
assert_eq!(iter.next(), Some(1));
assert_eq!(iter.next(), Some(2));
assert_eq!(iter.next(), None);
...
```

**Comment by KizzyCode** [comment]
Well, my problem (as a foreign speaker) is that the function is not called `take_up_to`, but `take`, which (at least to me) *implies* some sort of "guarantee" that it would take exactly `n` elements.

While within the iterator-logic the behavior is completely logical, for me in the first minutes it was not.

**Comment by czipperz** [comment]
Yep. I agree it is kinda weird

**Comment by poliorcetics** [comment]
@KizzyCode I made a PR for that, is the added explanation clear from you point of view ?

**Comment by poliorcetics** [comment]
The PR fixing this has been merged, this could be closed.

**Comment by jieyouxu** [comment]
Closing as docs were updated.
