### ISSUE TITLE
Is it posible to enforce dynamic dispatch for all generic during compile time?

### ISSUE THREAD

**Issue by david0u0** [rust-lang/rust#61260]

**Comment by jonas-schievink** [comment]
Hi! This issue tracker is mainly meant for bug reports and concrete, small feature requests. Questions like this are better asked in the user forum at https://users.rust-lang.org/ or on [one of the chat platforms](https://www.rust-lang.org/community) used by the Rust community.

To answer your question, this is not currently supported and it's unlikely that it can be supported in general (ie. in *all* possible cases involving generics), but I do remember some discussion about doing this to improve compile times.

**Comment by david0u0** [comment]
@jonas-schievink 
Thanks for the quick reply :)
