### ISSUE TITLE
rust-gdbgui script is not installed

### ISSUE THREAD

**Issue by jonblack** [rust-lang/rust#61282]
According to merge request #53774, and the line `builder.install(&builder.src.join("src/etc/rust-gdbgui"), &sysroot.join("bin"), 0o755);` in `src/bootstrap/dist.rs`, the script `rust-gdbgui` should be installed in `~/.cargo/bin/rust-gdbgui`.

With rust 1.35.0 I don't see this script installed. I'm running linux, so the installer should be going into that branch. I can see `rust-gdb` and `rust-lldb`.

When I copy the file manually, it works.

**Comment by JeanMertz** [comment]
I was looking into gdbgui as well, and can confirm that this is still the case.

**Comment by Ryan1729** [comment]
I can also confirm that I needed to copy [the script](https://github.com/PhilipDaniels/rust/blob/master/src/etc/rust-gdbgui) to `~/.cargo/bin/rust-gdbgui` with rust 1.44.0

**Comment by iacchus** [comment]
I opened it with `rustup run nightly rust-gdbgui` or `rustup run stable rust-gdbgui` after installing it: `pip install gdbgui`

**Comment by awoimbee** [comment]
`rust-gdbgui` is in fact installed with the rust toolchain, it sits in `~/.rustup/toolchains/{TOOLCHAIN}/bin/rust-gdbgui`
The only issue is that `rust-gdbgui` isn't in `/usr/bin/`:

```bash
~$ ls -l /usr/bin/rust*
lrwxrwxrwx 1 root root   15  9 juil. 00:43 /usr/bin/rustc -> /usr/bin/rustup
lrwxrwxrwx 1 root root   15  9 juil. 00:43 /usr/bin/rustdoc -> /usr/bin/rustup
lrwxrwxrwx 1 root root   15  9 juil. 00:43 /usr/bin/rustfmt -> /usr/bin/rustup
lrwxrwxrwx 1 root root   15  9 juil. 00:43 /usr/bin/rust-gdb -> /usr/bin/rustup
lrwxrwxrwx 1 root root   15  9 juil. 00:43 /usr/bin/rust-lldb -> /usr/bin/rustup
-rwxr-xr-x 1 root root 6,6M  9 juil. 00:43 /usr/bin/rustup
```

`rustup run stable rust-gdbgui` works

**Comment by jyn514** [comment]
I'm not sure what the original problem was here, but `rust-gdbgui` is installed locally for me with rustup, and packaged with the Ubuntu `rust-gdb` package; and the code for it is exactly the same as the code for `rust-gdb`: https://github.com/rust-lang/rust/blob/7f5ce942809e15f65d91089e8baacc6affdf6c9c/src/bootstrap/dist.rs#L545-L546

So I think this has been fixed.
