### ISSUE TITLE
Send/Sync type parameters come after const parameters in docs

### ISSUE THREAD

**Issue by varkor** [rust-lang/rust#61292]
https://github.com/rust-lang/rust/blob/721268583759224d0f6476e0b8b196cc8afbdea0/src/test/rustdoc/generic-const.rs#L12-L13
Const parameters should always be trailing (at least with respect to type/lifetime parameters). I'm not sure whether this is specifically a rustdoc issue or not yet.

**Comment by GuillaumeGomez** [comment]
Strange since we read them as they come... So we have to force their position at the end? Let's go for it then...
