### ISSUE TITLE
`core::panic` documentation is useless

### ISSUE THREAD

**Issue by jplatte** [rust-lang/rust#61327]
For some reason, the [documentation for `core::panic`](https://doc.rust-lang.org/core/macro.panic.html) does not contain any of the useful pieces of information of `std::panic`'s documentation and instead references a non-existent module `std::macros`.

**Comment by czipperz** [comment]
So it turns out the panic macro is defined in both libcore and libstd.  Both have documentation.  They are defined differently.  Presumably libstd is the "better" implementation while libcore is the fallback when nostd is enabled.

I'm considering opening a PR that copies the documentation.  Thoughts?

**Comment by czipperz** [comment]
I believe the documentation points the the other one because it doesn't want duplication of comments.  Which is bad.  But it might be better for std to point to core rather than the other way around.  Or something like that.

**Comment by jplatte** [comment]
To avoid duplicating the text while still having the same doc comment for both macros, one could use the external_doc feature: https://doc.rust-lang.org/nightly/unstable-book/language-features/external-doc.html

**Comment by czipperz** [comment]
AFAIK there isn't a usual place to put these sorts of markdown files.  Where would you recommend?  We could move `libcore/macros.rs` to `libcore/macros/mod.rs` and then store all the markdown files in there?

**Comment by jplatte** [comment]
Fixed by https://github.com/rust-lang/rust/pull/66395
