### ISSUE TITLE
Make sure generic parameters can be unordered internally

### ISSUE THREAD

**Issue by varkor** [rust-lang/rust#61334]
Although we currently require generic parameters to be ordered — lifetimes, types, consts — internally there should be no such restriction (other than the error message). However, currently we also require generic parameters to be ordered this way internally. This has caused issues in the past, for example:
https://github.com/rust-lang/rust/blob/9c9b7b4eaceefe88bafc3b4e3529635973320253/src/librustc_passes/ast_validation.rs#L441-L446
and https://github.com/rust-lang/rust/pull/61333. Requiring ordering causes pain points like these, without making anything easier to deal with.

The compiler has got better at handling these now that all parameters are stored in a single vector, but they still need to be ordered in some locations. To fix this, it's probably simplest to add a feature gate `unordered_generic_params` which disables the order check and trace exactly what requires the parameters to be sorted, removing those restrictions. The feature flag will allow us to add regression tests.

**Comment by petrochenkov** [comment]
There are some language implications with lifetimes.

Lifetime arguments in `foo<'a, 'b, T, U>` can be elided and inferred independently from type arguments - `foo<T, U>`, so with unordered generics it would technically look like an "expected a lifetime argument, found a type argument" error.
This needs to continue working somehow.

**Comment by varkor** [comment]
I believe the compiler supports generic parameters in any order now, though the restriction is still enforced for now.
