### ISSUE TITLE
ICE: rustc crashed on const generics

### ISSUE THREAD

**Issue by qwerty19106** [rust-lang/rust#61341]
Test code:
``` Rust
#![feature(const_generics)]

use std::mem::MaybeUninit;

#[repr(transparent)]
pub struct OsThreadStack<const N: usize>(MaybeUninit<[u64; N]>);

fn main() {

}
```

It produced error:
``` Rust
error: internal compiler error: src/librustc/ty/sty.rs:2311: expected constant usize, got Const {
    ty: usize,
    val: Param(
        N/#0,
    ),
}
```

Playground version: rustc 1.37.0-nightly (2019-05-29 37d001e4d)

[playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=dc28c72478b76d23c757772335970b68)

**Comment by varkor** [comment]
This may be the same as https://github.com/rust-lang/rust/issues/61337. Both should be added as regression tests when this is fixed.

**Comment by qwerty19106** [comment]
Also this code give other error:
```
#![feature(const_generics)]

use core::mem::MaybeUninit;

#[repr(C)]
pub struct OsThreadStack<const N: usize> {
    stack: MaybeUninit<[u64; N / 8]>
}

fn main() {
}
```

```
error: internal compiler error: constant in type had an ignored error
 --> src/main.rs:7:5
  |
7 |     stack: MaybeUninit<[u64; N / 8]>
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by varkor** [comment]
@qwerty19106: thanks, I've opened that as a new issue (as it has a different error message): https://github.com/rust-lang/rust/issues/61368.

**Comment by varkor** [comment]
Note that this only occurs when `#[repr(transparent)]` is present.

**Comment by varkor** [comment]
I have a fix for this (separate from the one for https://github.com/rust-lang/rust/issues/61337).
