### ISSUE TITLE
hash_map::IterMut changed Send bounds with hashbrown

### ISSUE THREAD

**Issue by cuviper** [rust-lang/rust#61357]
In 1.35, `IterMut`'s `Send` requires `K: Send`, but in 1.36-beta it requires `K: Sync`. Both are auto-derived, so it must be a change in their internals. Obviously, `hashbrown` is quite different than the old implementation.

https://doc.rust-lang.org/1.35.0/std/collections/hash_map/struct.IterMut.html#impl-Send
![image](https://user-images.githubusercontent.com/36186/58648375-69af3d00-82be-11e9-84a4-23bcc3ad5500.png)

https://doc.rust-lang.org/beta/std/collections/hash_map/struct.IterMut.html#impl-Send
![image](https://user-images.githubusercontent.com/36186/58648430-864b7500-82be-11e9-91d2-f6903d4f083f.png)

Ditto for `ValuesMut`. I'm not sure if there's any real impact in this, but it should be considered, and perhaps audit for other similar changes.

cc @Amanieu, as discussed on IRC.

**Comment by Amanieu** [comment]
This is fixed in hashbrown 0.4.0.

**Comment by aclonegeek** [comment]
@Amanieu Shouldn't `ValuesMut` be fixed as well?

**Comment by cuviper** [comment]
Since `ValuesMut` is actually based on `IterMut`, it derives the same constraints.
https://docs.rs/hashbrown/0.4.0/hashbrown/hash_map/struct.ValuesMut.html#synthetic-implementations

**Comment by aclonegeek** [comment]
@cuviper Ah, gotcha. Thanks! Sorry for the false alarm :).

**Comment by Aaron1011** [comment]
I think it would be a good idea to add a run-pass to check that these auto-trait impls don't change again.

**Comment by gnzlbg** [comment]
@Aaron1011 might make sense to add them as tests to most collections. `Vec`, `VecDeque`, etc. don't have tests for these either.
