### ISSUE TITLE
Unsafe block is overlooked

### ISSUE THREAD

**Issue by DutchGhost** [rust-lang/rust#61365]
I know this code horribly wrong, and it doesnt compile. Even when I expect it to compile:
```Rust
#![feature(const_fn_union)]
#![feature(const_generics)]

union Transmute {
    example: Example,
    num: usize,
}
    
#[derive(Copy, Clone)]
#[repr(C)]
enum Example {
    field = 1,
}

const fn transpose(n: usize) -> Example {
    unsafe {
        Transmute { num: n }.example
    }
}


fn main() {
}
```

It complains that we need an unsafe block:
```
error[E0133]: access to union field is unsafe and requires unsafe function or block
  --> src/main.rs:17:9
   |
17 |         Transmute { num: n }.example
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ access to union field
   |
   = note: the field may not be properly initialized: using uninitialized data will cause undefined behavior

error: aborting due to previous error

```

but we wrapped it in an unsafe block!

Changing the function signature to `const *unsafe* fn transpose(n: usize) -> Example` does compile, and then we can leave out the inner unsafe block.

**Comment by Centril** [comment]
cc @oli-obk

**Comment by oli-obk** [comment]
> Changing the function signature to const *unsafe* fn transpose(n: usize) -> Example does compile, and then we can leave out the inner unsafe block.

oh oh. That's bad. That shouldn't happen. (As unions are not ok in `const fn` under any circumstances at thistime). Although `const unsafe fn` isn't really that bad, as you can't do anything weird with it I guess. cc @RalfJung

**Comment by oli-obk** [comment]
Note that with a feature gate you can get this without `const unsafe fn`: https://github.com/rust-lang/rust/issues/51909

**Comment by RalfJung** [comment]
Yeah IIRC we wanted to ban union field accesses in *all* `const fn` including `unsafe const fn`. Why is that even a separate code path?

**Comment by oli-obk** [comment]
Oh.. wait, the `const_fn_union` feature gate is activated. Nevermind, sorry about the ping. This is just a bug in the feature gate not allowing enough.

**Comment by DutchGhost** [comment]
Related to https://github.com/rust-lang/rust/issues/59729 maybe?

**Comment by RalfJung** [comment]
The code in the OP compiles in the latest nightly. Closing.
