### ISSUE TITLE
Check existing uses of `unwrap_usize` for `ty::Array`

### ISSUE THREAD

**Issue by varkor** [rust-lang/rust#61381]
Generally, we should be using `assert_usize`, which will fail gracefully if we have a generic parameter as an array length instead, and handling that case specially. Using `unwrap_usize` has caused issues in the past: https://github.com/rust-lang/rust/pull/61380.

ICEs resulting from this issue have the form:
```
error: internal compiler error: src/librustc/ty/sty.rs:2311: expected constant usize, got Const {
    ty: usize,
    val: Param(
        N/#0,
    ),
}
```

**Comment by yodaldevoid** [comment]
`unwrap_usize` was renamed to `eval_usize` in commit 9b87d22ea83a1b5955d5355f91125456c4dc4bab.

**Comment by lcnr** [comment]
What's our current status here?

**Comment by varkor** [comment]
I don't think anyone did a formal triage, but I skimmed through at some point, and there weren't any more worrying uses. It might be safe to close this, and reopen if we hit the same ICE again.

**Comment by lcnr** [comment]
I also looked over this in the past and didn't see anything obviously incorrect. So let's go ahead with closing this
and and look into this a bit more if it causes another ICE.
