### ISSUE TITLE
Const-generic arguments are not printed in error messages

### ISSUE THREAD

**Issue by jplatte** [rust-lang/rust#61395]
This code ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=71becd94ee21012d9ce69a2d8744d964)):

```rust
#![feature(const_generics)]

struct Generic<const C: usize>;

fn main() {
    let _: Generic<0> = Generic::<1>;
}
```

results in

```
error[E0308]: mismatched types
 --> src/main.rs:6:25
  |
6 |     let _: Generic<0> = Generic::<1>;
  |                         ^^^^^^^^^^^^ expected `0usize`, found `1usize`
  |
  = note: expected type `Generic<>`
             found type `Generic<>`
```

with missing const arguments in the `note: ...` at the bottom.

**Comment by imbrem** [comment]
Hey guys could I take this on?

**Comment by imbrem** [comment]
Just FYI, same problem with messages involving const generics and matches, e.g.
```rust
#![feature(const_generics)]

struct Generic<const C: usize>;


fn main() {
    let x = Generic::<0>;
    let y = Generic::<1>;
    let _ = match 1 {
        0 => x,
        _ => y
    };
}
```
([Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=21e17eef4e8eba2370966c12c1c7d00a))

**Comment by imbrem** [comment]
Interestingly, when I use concrete types for the function example, things display properly:
```rust
#![feature(const_generics)]

struct Generic<const C: usize>;

fn foo(x : usize) {}

fn main() {
    let x = Generic::<0>;
    foo(x);
}
```
gives
```
error[E0308]: mismatched types
 --> src/main.rs:9:9
  |
9 |     foo(x);
  |         ^ expected usize, found struct `Generic`
  |
  = note: expected type `usize`
             found type `Generic<0usize>`
```
([Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=ba006a768e93de6be31f2de5d5bcfdb1))

**Comment by varkor** [comment]
@imbrem: you're welcome to look into fixing this! However, I'm not sure what might be causing this problem, so I don't have any suggestions for where to start looking yet.

**Comment by imbrem** [comment]
@varkor I spent a few hours doing some digging and I can't find anything yet as well, though I'm as of yet still quite unfamiliar with the code-base. I might have more time tomorrow to look things over again, or maybe the day after.
