### ISSUE TITLE
installing rust in an android based app termux without root permissions gives error.

### ISSUE THREAD

**Issue by AniketGupta07** [rust-lang/rust#61396]
I tried to install rust in an android app termux  but since it does not need root permission so running **curl https://sh.rustup.rs -sSf | sh**. Gives error: **rust $HOME differs from euid-obtained home directory**

**Comment by jonas-schievink** [comment]
Thanks for the report! However, the rustup installer shouldn't need root permissions, so this looks like some other Android-specific problem. Please report the issue at https://github.com/rust-lang/rustup.rs/, since this is the issue tracker for rustc and the standard library, not rustup.

**Comment by Kingdaviz619** [comment]
I keep facing this problem when trying to install rust on termux "$HOME differs from euid-obtained home directory", any walk around would be appreciated 👏
