### ISSUE TITLE
On temporary value dropped while borrowed error use structured suggestion

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#61405]
From https://www.reddit.com/r/rust/comments/bv90s7/temporary_value_dropped_while_borrowed/

We currently supply the following diagnostic:
```
let mut words = con.unwrap().split_whitespace().peekable();
                ^^^^^^^^^^^^                              - temporary value is freed at the
                |                                                     end of this statement
   |            |
   |            creates a temporary which is freed while still in use
   |
   |             while words.peek().is_some() {
   |                   ----- borrow later used here
   |
   = note: consider using a `let` binding to create a longer lived value
```

The note should be a structured suggestion that looks at the current line, figures out the indentation, finds the span for the beginning of the line and suggests adding a line above with a `let` binding. This should make it clearer what we're suggesting. Additionally, it'd be nice if we could add either a succinct explanation or a link to the book with an explanation of what might be happening here.

**Comment by kennethbgoodin** [comment]
I want to attempt this issue. I see where the diagnostic is being generated, currently looking for how to get the current line/indentation.

**Comment by estebank** [comment]
Getting those things will require a bit of trial and error. You can take a look at `source_map::span_to_margin` for the way to get the indentation of a given span, and you'll need to add a new similar method to give you the span corresponding to the beginning of the line.

Feel free to reach out if you need extra guidance.

**Comment by kennethbgoodin** [comment]
Okay, thank you.

**Comment by kennethbgoodin** [comment]
What's the best way to debug this? Right now I'm running a specific test with `./x.py test -i src/test/ui/span/slice-borrow.rs --stage 1 --keep-stage 1` but that still takes a while to compile and doesn't give me much in the way of debug logging. I do have debug enabled in my local `config.toml`.

**Comment by jhpratt** [comment]
Right now I'm creating a temporary variable solely to satisfy the compiler. It's not even possible within an anonymous block, and that bit I don't fully understand.

I'd think it's possible for the compiler to perform the suggested action internally (and silently), but I'm also not familiar with the exact details of rustc. Is this not the case?

**Comment by Areredify** [comment]
@kennethbgoodin would you mind me picking this up?

**Comment by Areredify** [comment]
@estebank do you maybe have a pointer for an existing suggestion structured similarly?

**Comment by estebank** [comment]
I can't think of an example off the top of my head, and we don't really do this heavy text wrangling for suggestions much because it is very error prone.

**Comment by RobertLemmens** [comment]
This would be a nice feature to have. Took me some minutes today to find my mistake, an error like this would have speed up the process.

**Comment by Xenunxenunowski** [comment]
could be a great thing for new comers :)

**Comment by V0ldek** [comment]
This is already improved with a multipart suggestion in the nightly version.

```rust
#![allow(unused_variables)]
fn foo() -> i32 { 22 }
fn bar(x: &i32) -> &i32 { x }
fn main() {
    let p = bar(&foo());
    let q = *p;
}
```

Gives this diagnostic for `cargo +nightly check`:

```ini
error[E0716]: temporary value dropped while borrowed
 --> src/main.rs:5:18
  |
5 |     let p = bar(&foo());
  |                  ^^^^^ - temporary value is freed at the end of this statement
  |                  |
  |                  creates a temporary which is freed while still in use
6 |     let q = *p;
  |             -- borrow later used here
  |
help: consider using a `let` binding to create a longer lived value
  |
5 ~     let binding = foo();
6 ~     let p = bar(&binding);
  |

For more information about this error, try `rustc --explain E0716`.
```

Seems to have been done in #99258 by @estabank yourself, so this can probably be closed :)
