### ISSUE TITLE
integer overflow in CTFE implementation of rotate_left

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#61406]
The following code ICEs when compiled with a rustc with debug-assertions enabled:
```rust
const X: i16 = 0i16.rotate_left(124);
```

The problem is in the implementation of `rotate_left`, specifically in this line: https://github.com/rust-lang/rust/blob/75f464481ed8c924086fc0b9a2d31841bbdbcabd/src/librustc_mir/interpret/intrinsics.rs#L197
The subtraction overflows here.

Cc @oli-obk

**Comment by nikic** [comment]
Fix should be:

```
// replace
let inv_shift_bits = (width_bits - raw_shift_bits) % width_bits;
// with
let inv_shift_bits = (width_bits - shift_bits) % width_bits;
```

**Comment by hgallagher1993** [comment]
Ya I'll take this on :+1:

**Comment by RalfJung** [comment]
@hgallagher1993 	awesome! @nikic 	above already pretty much gave the mentoring instructions, except for one thing: please also add a test case. Or rather, please extend the existing test case at `src/test/ui/consts/const-int-rotate.rs`.

Let me know if you need any more assistance.

**Comment by RalfJung** [comment]
@lzutao @hgallagher1993 	looks like you are both on this now? Not sure how that happened...
