### ISSUE TITLE
Allow the use of const parameters from outer definitions

### ISSUE THREAD

**Issue by varkor** [rust-lang/rust#61414]
We would like this to pass:
```rust
#![feature(const_generics)]

fn foo<const X: u32>() -> u32 {
    fn bar() -> u32 {
        X
    }
    bar() * 2
}

fn main() {
    assert_eq!(foo::<6>(), 12);
}
```
See [this IRLO post](https://internals.rust-lang.org/t/cant-use-type-parameters-from-outer-function-why-not/3156/4) for motivation.

**Comment by Centril** [comment]
This would be an implementation of [`{-# LANGUAGE ScopedTypeVariables #-}`](https://www.microsoft.com/en-us/research/publication/lexically-scoped-type-variables/) as in the Glasgow Haskell Compiler but specifically for const generic parameters.

I do think we should generalize this to type parameters at least and make this work for non-impl items (possibly not for others) in general. Lifetimes are also something to consider... and likely tricky and it should also impact const generics and type parameters implicitly.

**Comment by lcnr** [comment]
discussed this while triaging const generics issues in https://rust-lang.zulipchat.com/#narrow/stream/260443-project-const-generics/topic/.60F-generic_const_exprs.60.20triage/near/287352481

**Comment by lcnr** [comment]
implementing this would require a lang MCP or an RFC. As such I am closing this issue.

I generally don't think we should have a special case for const parameters here. I don't think there's a meaningful difference between const and type parameters.
