### ISSUE TITLE
Incorrect elimination of `loop {}`

### ISSUE THREAD

**Issue by ksqsf** [rust-lang/rust#61434]
It's observed that the following program (compile with optimizations) results in an illegal instruction exception, but does not crash when compiled without optimizations.

```rust
fn work() { // no `-> !` here
    loop{}
}

fn main() {
    work();
    println!("test")
}
```

LLVM IR:

```
; playground::main
; Function Attrs: norecurse noreturn nounwind nonlazybind readnone uwtable
define internal void @_ZN10playground4main17h13d813b46f0ec3d7E() unnamed_addr #2 {
start:
  unreachable
}
```

I'm not sure how this can happen given loop's semantics. In no way should an optimization eliminate the loop altogether. My guess: LLVM or rustc substitutes `unreachable` for the body of `work`, but later `work` is inlined into `main`.

I understand it's better to use `-> !` explicitly, but this code compiles cleanly without any warnings and errors. Rust's typing rules cannot rule out such programs?

**Comment by ksqsf** [comment]
Update: adding `-> !` does not solve this problem. Maybe an LLVM bug?

**Comment by varkor** [comment]
Yes, this is unfortunately a longstanding LLVM bug: see https://github.com/rust-lang/rust/issues/28728.

**Comment by DutchGhost** [comment]
This is known,

See this issue: https://github.com/rust-lang/rust/issues/28728
