### ISSUE TITLE
Trivial type constructed on stack and moved to heap in release mode

### ISSUE THREAD

**Issue by lukaslueg** [rust-lang/rust#61431]
I vaguely remember this has been a known issue before, so feel free to shut it down: The following code get's compiled by 1.35.0 in release-mode with `codegen-units=1 lto=yes panic=abort`...

```rust

pub struct Sketch {
    regs: [u16; 1 << 14],
}

impl Default for Sketch {
    fn default() -> Self {
        Self {
            regs: [0; 1 << 14],
        }
    }
}
```

... and when constructing a `Box<Sketch>` using `Default::default()`, the resulting disassembly shows up as

```
.text:00000000000126CF                 lea     rdi, [rsp+30h+Sketch] ; s
.text:00000000000126D7                 mov     edx, 8000h      ; n
.text:00000000000126DC                 xor     esi, esi        ; c
.text:00000000000126DE                 call    cs:memset_ptr_0
.text:00000000000126E4                 mov     edi, 8000h      ; size
.text:00000000000126E9                 call    cs:malloc_ptr_0
.text:00000000000126EF                 test    rax, rax
.text:00000000000126F2                 jz      loc_12FC6
.text:00000000000126F8                 mov     rbx, rax
.text:00000000000126FB                 lea     rsi, [rsp+30h+Sketch] ; src
.text:0000000000012703                 mov     edx, 8000h      ; n
.text:0000000000012708                 mov     rdi, rax        ; dest
.text:000000000001270B                 call    cs:memcpy_ptr_0
```

This clears 32kb of memory on the stack, allocates 32kb on the heap and then moves 32kb of zeroes from the stack to the heap. I would have expected a simple call to `calloc` or at least the `memcpy` being avoided.

**Comment by nikic** [comment]
This needs more precise reproduction instructions. I tried this, and it generated reasonable code: https://rust.godbolt.org/z/T19PxW Including also on 1.35.

**Comment by lukaslueg** [comment]
Can't reproduce either, although I tested it at the time :-/
