### ISSUE TITLE
Implementing Eq/PartialEq/Hash for [T; 48] and [T; 64]

### ISSUE THREAD

**Issue by anhbakhia** [rust-lang/rust#61445]
Currently `Eq`, `PartialEq`, `Hash` are only implemented for slices up to 32 elements: `[T; 32]`.

`[T; 48]` and `[T; 64]` are common slices, used for SHA-384, SHA3-384, SHA-512, SHA3-512, KECCAK-512... Could you consider implementing `Eq`, `PartialEq`, `Hash` for `them? This would help library authors a lot.

Thank you,

**Comment by czipperz** [comment]
I believe `[T; N]` (for any `N`) will be generically implemented for those traits soon.  See #60466 for more details.

**Comment by scottmcm** [comment]
Adding more sizes has been rejected before, so with const generics coming soon, I'm going to close this.
