### ISSUE TITLE
LLVM warnings on mips* when using `-C target-cpu=native`

### ISSUE THREAD

**Issue by infinity0** [rust-lang/rust#61440]
This is causing the cargo 0.35.0 tests to fail on mips* - e.g. [mips64el](https://buildd.debian.org/status/fetch.php?pkg=cargo&arch=mips64el&ver=0.35.0-1&stamp=1559294794&raw=0).

~~~~
$ rustc --version
rustc 1.34.2
$ cat hello.rs
fn main() {}
$ rustc -C target-cpu=native hello.rs
'generic' is not a recognized processor for this target (ignoring processor)
'generic' is not a recognized processor for this target (ignoring processor)
'generic' is not a recognized processor for this target (ignoring processor)
'generic' is not a recognized processor for this target (ignoring processor)
'generic' is not a recognized processor for this target (ignoring processor)
[..]
~~~~

**Comment by infinity0** [comment]
Seems related to #53322 but I wasn't sure how to adapt the fix from there to this.

**Comment by infinity0** [comment]
@alexcrichton Looks like your solution in #53642 relies on using LLVM's llvm::sys::getHostCPUName however on mips* this returns "generic":

~~~~
$ cat lol.cc
#include <llvm/Support/Host.h>
#include <stdio.h>

using namespace llvm;

int main() {
  printf("%s\n", sys::getHostCPUName());
}
$ g++ -I/usr/lib/llvm-7/include lol.cc -lLLVM-7 && ./a.out
generic
~~~~

(on my own intel box this returns `skylake`)

**Comment by workingjubilee** [comment]
Checking reports for newer versions like [Debian Bullseye](https://buildd.debian.org/status/package.php?p=cargo&suite=bullseye), the current stable release, buildd appears to pass this for remaining `mips*` architectures. Closing on the assumption that this was cleared.
