### ISSUE TITLE
Not all `fn`s are `'static`?

### ISSUE THREAD

**Issue by scottmcm** [rust-lang/rust#61450]
Given that `fn`s cannot carry an environment, I would have expected them to always be `'static`, regardless of their arguments or return types, but apparently a non-`'static` argument type _or_ return type makes a `fn` non-`'static`:

```rust
fn foo<T>(_: T) where (fn(T) -> T): 'static {}

fn main() {
    let x = 4;
    let y = &x;
    foo::<&i32>(y);
}
```
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=8d616d31ca8d43dcaf2e779fa0b09b62
```rust
error[E0597]: `x` does not live long enough
 --> src/main.rs:5:13
  |
5 |     let y = &x;
  |             ^^ borrowed value does not live long enough
6 |     foo::<&i32>(y);
  |     -------------- argument requires that `x` is borrowed for `'static`
7 | }
  | - `x` dropped here while still borrowed
```

Originating Discord conversation: https://discordapp.com/channels/442252698964721669/448237931136679936/584609250882486282

**Comment by rodrimati1992** [comment]
[Here](https://github.com/rust-lang/rust/issues/57325) is a previous issue on the same thing.

**Comment by scottmcm** [comment]
Thanks, @rodrimati1992 -- I'll close this as a dup.
