### ISSUE TITLE
Query `visibility()` doesn't seem to behave correctly for trait implementations

### ISSUE THREAD

**Issue by orium** [rust-lang/rust#61464]
The `visibility` query for the trait implementations seems to give the wrong result.  Take this example:

```rust
pub trait Foo {}

impl Foo for i32 {}
```

If I ask for the visibility of the `impl foo for i32 {}` I will get a `ty::Visibility::Restricted(...)`, when the correct result should be `Public`.

In my mind an impl is public if all concrete input types and all type bounds are public.

**Comment by petrochenkov** [comment]
The query returns "nominal" visibility, i.e. `pub(x)` for `pub(x) struct S { ... }`.

Impls don't have nominal visibility at all (`pub(x) impl Tr for T { ... }` is an error), so the query probably returns some default value (`pub(self)`, most probably) that doesn't make sense.

You can define visibility for impls in various ways depending on the use case, see e.g. `fn of_impl` in `src/librustc_privacy/lib.rs`, but that's a recursive "type visibility", not nominal visibility.

**Comment by orium** [comment]
Thanks @petrochenkov.  In that case I will close this issue.
