### ISSUE TITLE
rustdoc ICE (2/3) in markdown - unexpected node in tree (Header)

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#61478]
Possibly fixed by https://github.com/rust-lang/rust/pull/60802 (awaiting beta backport approval)

root: sensehat-screen - 1 detected crates which regressed due to this; cc @saibatizoku
<details>

```
 * sensehat-screen-0.2.2: [start](https://crater-reports.s3.amazonaws.com/beta-1.36-2/1.35.0/reg/sensehat-screen-0.2.2/log.txt) v. [end](https://crater-reports.s3.amazonaws.com/beta-1.36-2/beta-2019-05-30/reg/sensehat-screen-0.2.2/log.txt); cc @saibatizoku
```

</details>

root: reciter - 1 detected crates which regressed due to this; cc @XBagon
<details>

```
 * reciter-0.1.2: [start](https://crater-reports.s3.amazonaws.com/beta-1.36-2/1.35.0/reg/reciter-0.1.2/log.txt) v. [end](https://crater-reports.s3.amazonaws.com/beta-1.36-2/beta-2019-05-30/reg/reciter-0.1.2/log.txt); cc @XBagon
```

</details>

root: mvdb - 1 detected crates which regressed due to this; cc @jamesmunns
<details>

```
 * mvdb-0.3.0: [start](https://crater-reports.s3.amazonaws.com/beta-1.36-2/1.35.0/reg/mvdb-0.3.0/log.txt) v. [end](https://crater-reports.s3.amazonaws.com/beta-1.36-2/beta-2019-05-30/reg/mvdb-0.3.0/log.txt); cc @jamesmunns
```

</details>

root: auto_enums - 1 detected crates which regressed due to this; cc @taiki-e
<details>

```
 * auto_enums-0.5.5: [start](https://crater-reports.s3.amazonaws.com/beta-1.36-2/1.35.0/reg/auto_enums-0.5.5/log.txt) v. [end](https://crater-reports.s3.amazonaws.com/beta-1.36-2/beta-2019-05-30/reg/auto_enums-0.5.5/log.txt); cc @taiki-e
```

</details>

root: csplit - 1 detected crates which regressed due to this; cc @efronlicht
<details>

```
 * csplit-0.1.0: [start](https://crater-reports.s3.amazonaws.com/beta-1.36-2/1.35.0/reg/csplit-0.1.0/log.txt) v. [end](https://crater-reports.s3.amazonaws.com/beta-1.36-2/beta-2019-05-30/reg/csplit-0.1.0/log.txt); cc @efronlicht
```

</details>

root: font8x8 - 1 detected crates which regressed due to this; cc @saibatizoku
<details>

```
 * font8x8-0.2.4: [start](https://crater-reports.s3.amazonaws.com/beta-1.36-2/1.35.0/reg/font8x8-0.2.4/log.txt) v. [end](https://crater-reports.s3.amazonaws.com/beta-1.36-2/beta-2019-05-30/reg/font8x8-0.2.4/log.txt); cc @saibatizoku
```

</details>

root: tao-of-rust - 1 detected crates which regressed due to this; cc @ZhangHanDong
<details>

```
 * tao-of-rust-1.0.2: [start](https://crater-reports.s3.amazonaws.com/beta-1.36-2/1.35.0/reg/tao-of-rust-1.0.2/log.txt) v. [end](https://crater-reports.s3.amazonaws.com/beta-1.36-2/beta-2019-05-30/reg/tao-of-rust-1.0.2/log.txt); cc @ZhangHanDong
```

</details>

**Comment by jonas-schievink** [comment]
(this is likely to be a dupe of https://github.com/rust-lang/rust/issues/60482, which was fixed by https://github.com/rust-lang/rust/pull/60802, which I've now `beta-nominated`)

**Comment by QuietMisdreavus** [comment]
I checked `reciter` and it looks like the ICE isn't present on nightly.

**Comment by Mark-Simulacrum** [comment]
Confirmed that this was fixed before stable, I'm actually going to close since re-regressing here seems highly unlikely (and hopefully tests were added in the underlying crate that was the cause of this).
