### ISSUE TITLE
rustdoc ICE (3/3) in markdown - unwrap on nil value

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#61479]
Possibly fixed by https://github.com/rust-lang/rust/pull/60802 (awaiting beta backport approval)

root: shellwords - 1 detected crates which regressed due to this; cc @jimmycuadra
<details>

```
 * shellwords-1.0.0: [start](https://crater-reports.s3.amazonaws.com/beta-1.36-2/1.35.0/reg/shellwords-1.0.0/log.txt) v. [end](https://crater-reports.s3.amazonaws.com/beta-1.36-2/beta-2019-05-30/reg/shellwords-1.0.0/log.txt); cc @jimmycuadra
```

**Comment by QuietMisdreavus** [comment]
Confirming the ICE is no longer present on nightly.

**Comment by jonas-schievink** [comment]
Closing this as fixed.
