### ISSUE TITLE
Rustdoc generic array impl doesnt show length

### ISSUE THREAD

**Issue by DutchGhost** [rust-lang/rust#61487]
The following code:
```Rust
#![feature(const_generics)]

pub trait Array {
    type Item;
}

impl <T, const N: usize> Array for [T; N] {
    type Item = T;
}
```

produces the following docpage:
https://imge.to/i/vedzx

Obviously the `N` is missing in the specification for what type the trait is implemented.. `for [T; _]`

**Comment by GuillaumeGomez** [comment]
That's because const-generics support continues to be added into rustdoc. Thanks for opening this issue, I'll fix it soon.

**Comment by DutchGhost** [comment]
No problem. I'll be happy trying to find more of these, so when the feature finally rolls out, we can generate clean and neat documentation for it :D

**Comment by GuillaumeGomez** [comment]
Sure, but you'll have to be on nightly to keep up to date. :p
