### ISSUE TITLE
regression: duplicate matcher binding in macros

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#61481]
root: nes - 1 detected crates which regressed due to this; cc @TrionProg
<details>

```
 * nes-0.1.1: [start](https://crater-reports.s3.amazonaws.com/beta-1.36-2/1.35.0/reg/nes-0.1.1/log.txt) v. [end](https://crater-reports.s3.amazonaws.com/beta-1.36-2/beta-2019-05-30/reg/nes-0.1.1/log.txt); cc @TrionProg
```

</details>

**Comment by mark-i-m** [comment]
This regression was fixed in https://github.com/TrionProg/nes/pull/2

The crate just hasn't been updated.

**Comment by mark-i-m** [comment]
And FWIW, it fixed a bug in that crate.

**Comment by mark-i-m** [comment]
@Mark-Simulacrum ^^^

**Comment by Mark-Simulacrum** [comment]
I'll leave this open for now for the compiler team to decide, but I expect that we'll simply close this as an expected regression (and perhaps the crate's author will publish a new version).

**Comment by Centril** [comment]
Closing per note in https://github.com/rust-lang/rust/issues/61481#issuecomment-498165910. I also don't see the language team being OK with reintroducing this bug (I'm not).
