### ISSUE TITLE
Mutable PathBuf acts weirdly

### ISSUE THREAD

**Issue by sntdevco** [rust-lang/rust#61483]
I was storing logs in `/serveroplogs/` using the `std::fs` crate. Now a funny thing happened:
```rust
let mut path = PathBuf::new();
path.push("/serveroplogs/");
let subdir = String::from("localhost_443");
path.push(subdir); println!("This is the path: {:?}", path);
// The above prints "/serveroplogs/localhost_443"
path.push("/log1.log");
println!("This is the final path: {:?}", path);
// This suprisingly prints "/log1.log"
```
A running version can be seen [here](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=00dc561240451d77e9b12c888a74c844)
And the gist can be accessed [here](https://gist.github.com/sntdevco/eb94a323159eb5437f005832e1fe523a)

### Meta
- rustc version: rustc 1.35.0 (3c235d560 2019-05-20)
- cargo version: cargo 1.35.0 (6f3e9c367 2019-04-04)
- rustup version: rustup 1.18.3 (435397f48 2019-05-22)

**Comment by lzutao** [comment]
It is acting as expected in std doc: https://doc.rust-lang.org/nightly/std/path/struct.PathBuf.html#method.push

**Comment by sntdevco** [comment]
@lzutao Right so the `/` results in the previous path to be ignored if I'm not wrong

**Comment by lzutao** [comment]
Yes, the doc states that
> If pushed `path` is absolute, it replaces the current path.

**Comment by sntdevco** [comment]
Closed as the issue is <html><span style="background-color: #2196F3">not-a-bug</span></html>
