### ISSUE TITLE
can't find crate for rustc_serialize

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#61480]
root: clippy_panic - 1 detected crates which regressed due to this; cc @gibfahn
<details>

```
 * gibfahn/clippy-panic: [start](https://crater-reports.s3.amazonaws.com/beta-1.36-2/1.35.0/gh/gibfahn.clippy-panic/log.txt) v. [end](https://crater-reports.s3.amazonaws.com/beta-1.36-2/beta-2019-05-30/gh/gibfahn.clippy-panic/log.txt); cc @gibfahn
```

</details>

**Comment by phansch** [comment]
Looking at the README of https://github.com/gibfahn/clippy-panic, I think this repo can be whitelisted as it has been crashing two years ago as well. It's basically invoking Clippy in a now unsupported way, I believe.

**Comment by gibfahn** [comment]
Yeah, I think https://github.com/rust-lang/rust-clippy/issues/1638#issuecomment-289443768 contains the answer here.

This was only supposed to be a temp repo to repro a specific bug, which is no longer relevant. I've deleted the repo, thanks for the reminder!

**Comment by Mark-Simulacrum** [comment]
Closing this then as it's probably not a concern then.
