### ISSUE TITLE
ICE with const generics parameter in literal array length.

### ISSUE THREAD

**Issue by crlf0710** [rust-lang/rust#61490]
Seems similar to #61368, but different:
```
#![feature(const_generics)]

fn f<const LEN: usize>() {
    let a = [true; LEN];
}
```

[play link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=731229edd18cede4ef760299569496c4)

@varkor @yodaldevoid

**Comment by est31** [comment]
Both error message and code look very similar to #61336 , just that the type is set/fixed.

**Comment by varkor** [comment]
This definitely seems to be a problem with repeat expressions in particular.

**Comment by crlf0710** [comment]
Closing as a duplicate of #61336. Sorry :P
