### ISSUE TITLE
Rustup update nightly fails on Linux

### ISSUE THREAD

**Issue by fungl164** [rust-lang/rust#61517]
info: latest update on 2019-06-04, rust version 1.37.0-nightly (6ffb8f53e 2019-06-03)
error: component 'rls' for target 'x86_64-unknown-linux-gnu' is unavailable for download for channel 'nightly'

```
$ cat /etc/os-release
NAME="Ubuntu"
VERSION="19.04 (Disco Dingo)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 19.04"
VERSION_ID="19.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=disco
UBUNTU_CODENAME=disco
```

```
$ uname -a
Linux linux-pc 5.0.10-surface-linux-surface #5 SMP Wed May 1 06:29:54 EDT 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by jonas-schievink** [comment]
This is normal when the RLS doesn't build on nightly anymore (see https://github.com/rust-lang/rust/issues/61461). You can either remove that component before the update, or use stable (if that's possible), where the RLS is always guaranteed to be available. Or you can wait until the build is fixed and update then.

You can check https://rust-lang.github.io/rustup-components-history/ for a quick overview over the rustup components that are available.

**Comment by fungl164** [comment]
Thank you!
