### ISSUE TITLE
u128 rotate broken on wasm32-unknown-unknown

### ISSUE THREAD

**Issue by kazcw** [rust-lang/rust#61521]
Any use of u128::rotate_{left,right} with target=wasm32-unknown-unknown causes generation of an invalid WASM module. I don't know if this is a bug in rust or LLVM.

```
#[test] fn test() { 1u128.rotate_right(1) }
```

cargo web test --target=wasm32-unknown-unknown:
```
   Compiling test-rotate v0.1.0 (/home/kaz/repo/test-rotate)
    Finished dev [unoptimized + debuginfo] target(s) in 0.20s
    Processing "test_rotate-11d8ed67e1303d79.wasm"...
    Finished processing of "test_rotate-11d8ed67e1303d79.wasm"!
Error loading Rust wasm module 'test_rotate_11d8ed67e1303d79': <CompileError>
error: unhandled exception thrown
error:     CompileError: AsyncCompilation: (null): Compiling wasm function "_ZN4core3num22_$LT$impl$u20$u128$GT$11rotate_left17h80813d4a39024717E" failed: call[3] expected type i32, found get_local of type i64 @+2112
error: source: http://localhost:33257/:0:0
```

**Comment by alexcrichton** [comment]
I believe that this is a bug elsewhere than rustc itself, the error message here isn't coming from Rust/LLVM and the code compiles/works for me, so you may want to narrow this down to which part of the wasm pipeling is error'ing out and report it there.
