### ISSUE TITLE
Replace mention of IRC with Discord

### ISSUE THREAD

**Issue by Shadlock0133** [rust-lang/rust#61524]
There are still [few mentions](https://github.com/rust-lang/rust/search?q=IRC&unscoped_q=IRC) of IRC in the repo. Removing them is not a priority but it will avoid confusion for newcomers.

**Comment by initram** [comment]
Should these places be replaced with references to the rust discord server, or just be removed outright?

**Comment by Shadlock0133** [comment]
Probably replaced. Gonna update title.

**Comment by radu-matei** [comment]
Opened https://github.com/rust-lang/rust/pull/61531 to address this.

**Comment by leo-lb** [comment]
This is horrible.

**Comment by Shadlock0133** [comment]
@leo-lb If you haven't read about it yet, [here](https://blog.rust-lang.org/2019/04/26/Mozilla-IRC-Sunset-and-the-Rust-Channel.html) is the post from April.

**Comment by leo-lb** [comment]
@Shadlock0133 Yeah I read already. I'd remove the mention of any particular discussion channel, instead of putting Discord in. I can't wait for Matrix to become more mature so the Rust project can use it. Falling back to Discord is quite bad for a FOSS project.

**Comment by Shadlock0133** [comment]
@leo-lb IMO we should just mirror subreddit solution and point to Discord.
