### ISSUE TITLE
macro_rules follow logic allocates uselessly in the happy path

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#61543]
E.g. in https://github.com/rust-lang/rust/blob/ab7cf71d4c6dd1696cb0eb52ad172bce296578cc/src/libsyntax/ext/tt/macro_rules.rs#L1045 a vec is created, only to be thrown away if the macro actually works out. I think we can just turn most places into an early return in the happy path and then only allocate in the error path.

Do not work on this issue before https://github.com/rust-lang/rust/pull/61541 is merged.

Also, https://github.com/rust-lang/rust/blob/ab7cf71d4c6dd1696cb0eb52ad172bce296578cc/src/libsyntax/ext/tt/macro_rules.rs#L1015 hasn't had its docs updated to reflect the source changes.

**Comment by L117** [comment]
@oli-obk Are there any reasons to not use constant/static slices and convert them to vecs on demand?

Or maybe even convert
```rust
enum IsInFollow {
    Yes,
    No(Vec<&'static str>),
    Invalid(String, &'static str),
}
```
to something like
```rust
enum IsInFollow {
    Yes,
    No(&'static [&'static str]),
    Invalid(String, &'static str),
}
```
so there's no need to allocate vecs (In all cases) anymore?

**Comment by oli-obk** [comment]
That's a great idea! I haven't checked whether it'll work everywhere, but I think it should.
