### ISSUE TITLE
example `compile_fail` code from tokenlock crate compiles due to NLL

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#61564]
* tokenlock-0.1.6: [start](https://crater-reports.s3.amazonaws.com/beta-1.36-1/1.35.0/reg/tokenlock-0.1.6/log.txt) v. [end](https://crater-reports.s3.amazonaws.com/beta-1.36-1/beta-2019-05-30/reg/tokenlock-0.1.6/log.txt); cc `@yvt`

I believe this is due to NLL now being enabled and making these 'locks' no longer work. Haven't confirmed this, though.

**Comment by nikomatsakis** [comment]
Looking at the code, I agree -- the examples need to be tweaked. I didn't dig deeply enough to understand the premise of the crate and whether it is indeed sound.

**Comment by pnkfelix** [comment]
i'll look into this

**Comment by pnkfelix** [comment]
I put a PR up on the `tokenlock` crate. I don't think we need to do anything else here; any crate relying on lexical-lifetimes is going to hit issues with NLL. (And NLL is well worth the cost of "breaking" such crates.)

**Comment by pnkfelix** [comment]
closing as not-a-bug.
