### ISSUE TITLE
regression: assert_eq cannot find panic with no_implicit_prelude

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#61567]
This only works on 2015 edition. This code sample will fail to compile on [beta](https://play.rust-lang.org/?version=beta&mode=debug&edition=2015) but succeed on [stable](https://play.rust-lang.org/?version=stable&mode=debug&edition=2015).

```rust
#![no_implicit_prelude]

fn _foo() {
    assert_eq!(10, 20);
}
```

cc @petrochenkov

**Comment by petrochenkov** [comment]
For all macros *beside* `panic` the underlying issue is fixed in https://github.com/rust-lang/rust/pull/61629.
`panic` is special, https://github.com/rust-lang/rust/pull/61629 describes the situation in more detail.

**Comment by petrochenkov** [comment]
https://github.com/rust-lang/rust/pull/61971 implements a temporary solution, but I'd rather leave this as wontfix.

**Comment by pnkfelix** [comment]
Discussed at T-compiler meeting. Closing as wont-fix.

**Comment by petrochenkov** [comment]
https://github.com/rust-lang/rust/pull/62002 provides a proper solution.

**Comment by m-ou-se** [comment]
https://github.com/rust-lang/rust/pull/78343 would fix this.
