### ISSUE TITLE
couldn't load codegen backend on windows-gnu

### ISSUE THREAD

**Issue by sailfish009** [rust-lang/rust#61561]
win7_64 msys64

$ ./x.py install
Updating only changed submodules
Submodules updated in 1.12 seconds
    Finished dev [unoptimized] target(s) in 1.98s
Building stage0 std artifacts (x86_64-pc-windows-gnu -> x86_64-pc-windows-gnu)
    Finished release [optimized] target(s) in 1.75s
Copying stage0 std from stage0 (x86_64-pc-windows-gnu -> x86_64-pc-windows-gnu / x86_64-pc-windows-gnu)
Building stage0 test artifacts (x86_64-pc-windows-gnu -> x86_64-pc-windows-gnu)
    Finished release [optimized] target(s) in 0.63s
Copying stage0 test from stage0 (x86_64-pc-windows-gnu -> x86_64-pc-windows-gnu / x86_64-pc-windows-gnu)
Building stage0 compiler artifacts (x86_64-pc-windows-gnu -> x86_64-pc-windows-gnu)
    Finished release [optimized] target(s) in 2.89s
Copying stage0 rustc from stage0 (x86_64-pc-windows-gnu -> x86_64-pc-windows-gnu / x86_64-pc-windows-gnu)
Building stage0 codegen artifacts (x86_64-pc-windows-gnu -> x86_64-pc-windows-gnu, llvm)
warning: In file included from ../rustllvm/rustllvm.h:5,
warning:                  from ../rustllvm/PassWrapper.cpp:6:
warning: C:/msys64/work/rust/src/llvm-project/llvm/include/llvm/ADT/ArrayRef.h: In instantiation of 'llvm::ArrayRef<T>::ArrayRef(const std::initializer_list<_Tp>&) [with T = long long unsigned int]':
warning: C:/msys64/work/rust/src/llvm-project/llvm/include/llvm/IR/DIBuilder.h:645:74:   required from here
warning: C:/msys64/work/rust/src/llvm-project/llvm/include/llvm/ADT/ArrayRef.h:102:37: warning: initializing 'llvm::ArrayRef<long long unsigned int>::Data' from 'std::initializer_list<long long unsigned int>::begin' does not extend the lifetime of the underlying array [-Winit-list-lifetime]
warning:   102 |     : Data(Vec.begin() == Vec.end() ? (T*)nullptr : Vec.begin()),
warning: In file included from ../rustllvm/rustllvm.h:5,
warning:                  from ../rustllvm/RustWrapper.cpp:1:
warning: C:/msys64/work/rust/src/llvm-project/llvm/include/llvm/ADT/ArrayRef.h: In instantiation of 'llvm::ArrayRef<T>::ArrayRef(const std::initializer_list<_Tp>&) [with T = long long unsigned int]':
warning: C:/msys64/work/rust/src/llvm-project/llvm/include/llvm/IR/DIBuilder.h:645:74:   required from here
warning: C:/msys64/work/rust/src/llvm-project/llvm/include/llvm/ADT/ArrayRef.h:102:37: warning: initializing 'llvm::ArrayRef<long long unsigned int>::Data' from 'std::initializer_list<long long unsigned int>::begin' does not extend the lifetime of the underlying array [-Winit-list-lifetime]
warning:   102 |     : Data(Vec.begin() == Vec.end() ? (T*)nullptr : Vec.begin()),
warning: In file included from ../rustllvm/rustllvm.h:5,
warning:                  from ../rustllvm/ArchiveWrapper.cpp:1:
warning: C:/msys64/work/rust/src/llvm-project/llvm/include/llvm/ADT/ArrayRef.h: In instantiation of 'llvm::ArrayRef<T>::ArrayRef(const std::initializer_list<_Tp>&) [with T = long long unsigned int]':
warning: C:/msys64/work/rust/src/llvm-project/llvm/include/llvm/IR/DIBuilder.h:645:74:   required from here
warning: C:/msys64/work/rust/src/llvm-project/llvm/include/llvm/ADT/ArrayRef.h:102:37: warning: initializing 'llvm::ArrayRef<long long unsigned int>::Data' from 'std::initializer_list<long long unsigned int>::begin' does not extend the lifetime of the underlying array [-Winit-list-lifetime]
warning:   102 |     : Data(Vec.begin() == Vec.end() ? (T*)nullptr : Vec.begin()),
warning: In file included from C:/msys64/work/rust/src/llvm-project/llvm/include/llvm/Linker/IRMover.h:13,
warning:                  from C:/msys64/work/rust/src/llvm-project/llvm/include/llvm/Linker/Linker.h:14,
warning:                  from ../rustllvm/Linker.cpp:1:
warning: C:/msys64/work/rust/src/llvm-project/llvm/include/llvm/ADT/ArrayRef.h: In instantiation of 'llvm::ArrayRef<T>::ArrayRef(const std::initializer_list<_Tp>&) [with T = long long unsigned int]':
warning: C:/msys64/work/rust/src/llvm-project/llvm/include/llvm/IR/DIBuilder.h:645:74:   required from here
warning: C:/msys64/work/rust/src/llvm-project/llvm/include/llvm/ADT/ArrayRef.h:102:37: warning: initializing 'llvm::ArrayRef<long long unsigned int>::Data' from 'std::initializer_list<long long unsigned int>::begin' does not extend the lifetime of the underlying array [-Winit-list-lifetime]
warning:   102 |     : Data(Vec.begin() == Vec.end() ? (T*)nullptr : Vec.begin()),
    Finished release [optimized] target(s) in 0.48s
Assembling stage1 compiler (x86_64-pc-windows-gnu)
Building stage1 std artifacts (x86_64-pc-windows-gnu -> x86_64-pc-windows-gnu)
   Compiling core v0.0.0 (C:\msys64\work\rust\src\libcore)
   Compiling compiler_builtins v0.1.15
error: couldn't load codegen backend "C:\\msys64\\work\\rust\\build\\x86_64-pc-windows-gnu\\stage1\\lib\\rustlib\\x86_64-pc-windows-gnu\\codegen-backends\\rustc_codegen_llvm-llvm.dll": "The specified procedure could not be found. (os error 127)"

error: Could not compile `core`.
warning: build failed, waiting for other jobs to finish...
error: build failed
command did not execute successfully: "C:\\msys64\\work\\rust\\build\\x86_64-pc-windows-gnu\\stage0\\bin\\cargo.exe" "build" "--target" "x86_64-pc-windows-gnu" "-j" "4" "--release" "--features" "panic-unwind backtrace compiler-builtins-c" "--manifest-path" "C:\\msys64\\work\\rust\\src/libstd/Cargo.toml" "--message-format" "json"
expected success, got: exit code: 101
failed to run: C:/msys64/work/rust/build/bootstrap/debug/bootstrap install
Build completed unsuccessfully in 0:00:33

**Comment by sailfish009** [comment]
i found that, unlike stage0, in stage1 not copy following 3 files:

libgcc_s_seh-1.dll
libstdc++-6.dll
libwinpthread-1.dll

C:\>dumpbin /dependents C:\\msys64\\work\\rust\\build\\x86_64-pc-windows-gnu\\st
age1\\lib\\rustlib\\x86_64-pc-windows-gnu\\codegen-backends\\rustc_codegen_llvm-
llvm.dll
Microsoft (R) COFF/PE Dumper Version 14.22.27706.1
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file C:\\msys64\\work\\rust\\build\\x86_64-pc-windows-gnu\\stage1\\lib\\
rustlib\\x86_64-pc-windows-gnu\\codegen-backends\\rustc_codegen_llvm-llvm.dll

File Type: DLL

  Image has the following dependencies:

    ADVAPI32.dll
    KERNEL32.dll
    msvcrt.dll
    ole32.dll
    SHELL32.dll
    libgcc_s_seh-1.dll
    libstdc++-6.dll
    std-628b34239afd544d.dll
    rustc_cratesio_shim-1286e1e1e25e9401.dll
    rustc_data_structures-2fe798d50cc1988d.dll
    arena-6a0e10874a3e95a7.dll
    syntax_pos-7d77f4de5c784c3b.dll
    rustc_errors-75e0d9f7a3216c59.dll
    rustc_target-afb73b93701b273b.dll
    syntax-1b86f5297a43462e.dll
    rustc_fs_util-51440b05ae415ecd.dll
    rustc-7f75934bde937904.dll
    rustc_allocator-efb755307bc90225.dll
    rustc_incremental-217d1250b4277d9a.dll
    rustc_codegen_utils-df25ac251788eeee.dll
    rustc_codegen_ssa-26e20ca0ffb36a8b.dll

  Summary

        1000 .CRT
        2000 .bss
       75000 .data
        8000 .debug_abbrev
        1000 .debug_aranges
        3000 .debug_frame
       85000 .debug_info
       12000 .debug_line
       2B000 .debug_loc
        2000 .debug_ranges
        2000 .debug_str
      3EF000 .edata
       19000 .idata
       A5000 .pdata
      FC0000 .rdata
       39000 .reloc
       79000 .rustc
     2337000 .text
        1000 .tls
       E3000 .xdata

**Comment by YairHalberstadt** [comment]
I have the same issue: https://stackoverflow.com/questions/56473344/couldnt-load-codegen-backend-when-compiling-rust-on-windows-using-mingw-64?noredirect=1#comment99649355_56473344

**Comment by sailfish009** [comment]
replace llvm with latest version in my private [repo](https://bitbucket.org/sailfish009/rust) (which works fine 2019-5-18), result same error. so there is something wrong with latest src/llvm-project.

**Comment by sailfish009** [comment]
found the reason, latest mingw gcc 9.1.0 cause some missing dll problem. (although, compile rust source was fine).

if you have old version msys2, this will works for you:

pacman -R  mingw-w64-x86_64-gcc-libs  
pacman -R  mingw-w64-x86_64-gcc mingw-w64-x86_64-cmake
pacman -U /var/cache/pacman/pkg/mingw-w64-x86_64-gcc-libs-8.3.0-2-any.pkg.tar.xz
pacman -U /var/cache/pacman/pkg/mingw-w64-x86_64-gcc-8.3.0-2-any.pkg.tar.xz
pacman -U /var/cache/pacman/pkg/mingw-w64-x86_64-cmake-3.14.4-1-any.pkg.tar.xz

./x.py install
rustc -vV
rustc 1.37.0-dev
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-pc-windows-gnu
release: 1.37.0-dev
LLVM version: 8.0

**Comment by mati865** [comment]
This issue is not fixed and shouldn't have been closed.

**Comment by sailfish009** [comment]
@mati865 Technically correct, but rust is compiled fine with gcc 8.3 version.
only problem with gcc 9.x, may be rust need to be modified with gcc 9.x syntax.

**Comment by mati865** [comment]
Ntldd output:
```
 ntldd D:\\Projects\\rust\\build\\x86_64-pc-windows-gnu\\stage1\\lib\\rustlib\\x86_64-pc-windows-gnu\\codegen-backends\\rustc_codegen_llvm-llvm.dll
        std-1bafbda090a28ede.dll => not found
        fmt_macros-b2c296fbc2d2182c.dll => not found
        rustc_driver-acfddf0893838c24.dll => not found
        ADVAPI32.dll => C:\WINDOWS\SYSTEM32\ADVAPI32.dll (0x000000000ab10000)
        KERNEL32.dll => C:\WINDOWS\SYSTEM32\KERNEL32.dll (0x000000000abb0000)
        msvcrt.dll => C:\WINDOWS\SYSTEM32\msvcrt.dll (0x000000000abb0000)
        ole32.dll => C:\WINDOWS\SYSTEM32\ole32.dll (0x000000000ab10000)
        SHELL32.dll => C:\WINDOWS\SYSTEM32\SHELL32.dll (0x000000000af70000)
        libgcc_s_seh-1.dll => D:\msys64\mingw64\bin\libgcc_s_seh-1.dll (0x0000000000080000)
        libstdc++-6.dll => D:\msys64\mingw64\bin\libstdc++-6.dll (0x000000000ab10000)
```

**Comment by guanqun** [comment]
I had the same issue... and the mingw gcc version is 9.2.0

**Comment by sailfish009** [comment]
you can install gcc 8.x from [here](http://repo.msys2.org/mingw/x86_64/).

**Comment by pnkfelix** [comment]
triage: assigning to self for initial investigation.

**Comment by sailfish009** [comment]
with latest rust and gcc (from ubuntu 19.10), this bug looks like solved.

$ ./rustc -vV
rustc 1.40.0-dev
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-linux-gnu
release: 1.40.0-dev
LLVM version: 9.0

$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/9/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none:hsa
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 9.2.1-8ubuntu1' --with-bugurl=file:///usr/share/doc/gcc-9/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++,gm2 --prefix=/usr --with-gcc-major-version-only --program-suffix=-9 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --enable-bootstrap --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none,hsa --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 9.2.1 20190909 (Ubuntu 9.2.1-8ubuntu1) 

$ uname -a
Linux ubuntu 5.3.0-13-generic #14-Ubuntu SMP Tue Sep 24 02:46:08 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by mati865** [comment]
@sailfish009 it has never affected targets other than windows-gnu.

**Comment by CDirkx** [comment]
One downside of downgrading to gcc 8.3 and cmake 3.14 and building rust source is that I got errors messages similar to: [gcc internal compiler error](https://github.com/msys2/MINGW-packages/issues/4409) and [cmake missing dll](https://github.com/dokan-dev/dokany/issues/720), both of which are resolved in the newer versions. There are workarounds and backports of the fixes, but it would be a lot easier to be able to just use the latest version of gcc.

**Comment by pnkfelix** [comment]
visiting for triage. Being honest (with myself and you): I just can't allocate time/resources to this bug. (It does not help that Windows is not a primary nor secondary dev platform for me.)

Unassigning self and will post request for windows-dev to take this on

**Comment by Amanieu** [comment]
OK, so after a bit of debugging, here's what going on:
- The DLLs in `build/i686-pc-windows-gnu/stage0/bin` are from an older version of MinGW. These come as part of the bootstrap package.
- The DLLs in `/mingw32/bin` are from a newer version of MinGW. They have extra symbols that are not present in the older DLLs.
- The stage1 rustc is built against the system MinGW libraries and the LLVM codegen backend depends on one of the new symbols from `libstdc++-6.dll`.
- `PATH` is used to search for DLLs but the way bootstrap set this up ends up with `build/i686-pc-windows-gnu/stage0/bin` having priority over `/mingw32/bin`.
- The `rustc` binary doesn't link against libstdc++ and therefore works fine, however when the LLVM codegen backend is loaded, it will try to use the old `libstdc++-6.dll` which is missing some needed symbols.

**Comment by Amanieu** [comment]
As a workaround, you can copy the newer MinGW dlls from `/mingw32/bin` into `build/i686-pc-windows-gnu/stage0/bin`.
