### ISSUE TITLE
Invalid suggestion to use a vertical bar in `let a, b = x;`

### ISSUE THREAD

**Issue by goffrie** [rust-lang/rust#61573]
Introduced in #57008, the [following program](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=4043a87379488b48fbfa3a2bad796e88)
```
fn main() {
    let a, b = x;
}
```
yields the following message:
```
error: unexpected `,` in pattern
 --> src/main.rs:2:10
  |
2 |     let a, b = x;
  |          ^
help: try adding parentheses to match on a tuple..
  |
2 |     let (a, b) = x;
  |         ^^^^^^
help: ..or a vertical bar to match on multiple alternatives
  |
2 |     let a | b = x;
  |         ^^^^^
```

However, the suggestion `let a | b = x;` is nonsensical.

**Comment by petrochenkov** [comment]
`let a | b` is supposed to work eventually (https://github.com/rust-lang/rust/issues/48215, https://github.com/rust-lang/rust/issues/54883), but it's not yet implemented.

**Comment by goffrie** [comment]
I see. However, in this case, `a | b` would still not be a legal pattern.

**Comment by compiler-errors** [comment]
This was resolved.
