### ISSUE TITLE
Expose AST ranges of definition body bounds in save-analysis data

### ISSUE THREAD

**Issue by asutherland** [rust-lang/rust#61596]
We've recently updated the Firefox searchfox code indexer to do a "position:sticky" trick so that namespaces/class definitions/method definitions provide context for the source code you're looking at.  Our Clang indexer has easy access to the C++ AST to expose this information, but our rust indexer depends on the save-analysis data which only has access to the locations of the token/symbol being defined, not the range of the body of the thing being defined.

It would be invaluable to expose these AST ranges, or have some easy way to reconstruct the AST data given the save-analysis data.

https://bugzilla.mozilla.org/show_bug.cgi?id=1557442 tracks the searchfox enhancement bug that would like this data.  For this issue, I think labels A-save-analysis T-dev-tools may be appropriate.

**Comment by jyn514** [comment]
Save-analysis has been [removed from the compiler](https://github.com/rust-lang/rust/pull/101841).
