### ISSUE TITLE
Rustdoc rendering of underscore_imports a.k.a. impl-only-use is unuseful

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/rust#61592]
I tried using a lot of `pub use Foo as _;` in futures to avoid issues with preludes and extension trait shadowing, unfortunately Rustdoc currently doesn't seem to have any special handling of this feature resulting in a big list of exported `_` traits:

<img width="401" alt="Screenshot 2019-06-06 at 18 50 37" src="https://user-images.githubusercontent.com/81079/59050952-fb551680-888b-11e9-8093-184d2eea1a36.png">

**Comment by GuillaumeGomez** [comment]
Well, looks as expected from my opinion. 🤣 

What you suggest that rustdoc should do in this case?

**Comment by Nemo157** [comment]
I really can't think of something that's super obvious. What I would want is to have the original name in there as the main link, but somehow making it obvious that the name isn't actually visible at this path.

Actually, looking at this a little more there is an actual bug here that really makes these docs unusable, all those `_` traits link to the page `futures/prelude/trait._.html`, which then includes the documentation for just one of them.

---

Hmmm, playing with it a little more I tried using `doc(no_inline)` on all these, I think that looks better than having the traits inlined as `_`, maybe if a trait is exported `as _` and is exposed elsewhere in the crate documentation it should default to `no_inline`?


<img width="429" alt="Screenshot 2019-06-06 at 23 19 09" src="https://user-images.githubusercontent.com/81079/59067286-7ed52e80-88b1-11e9-8b12-9b8857978024.png">

**Comment by GuillaumeGomez** [comment]
Sounds like a good idea. I'll try to do it \*soon\*.
