### ISSUE TITLE
consider "delegated ownerwhip"

### ISSUE THREAD

**Issue by maddanio** [rust-lang/rust#61600]
hello,

i have been closely watching rust. coming from, and firmly staying, in c++ development and intimately knowing the issues rust is trying to solve.

my biggest issue with rust is the fact that to enforce ownership the way rust does any object graph either needs to be a tree, or one needs to completely give up on deterministic life times by using shared pointers (rc/arc).

i think this could be alleviated by allowing for "delegated ownership", i.e. somehow telling the compiler that a certain object has a lifetime scoped by some other object (i.e. the life time of the members of container are scoped by the container). that way non-tree object graphs (i.e. DAGs) would become possible in a safe manner, i.e. without using unsafe.

I feel this is very important because as soon as injection is used, i.e. a reference of one side of the tree is injected into the other side, possibly via callbacks, the tree property is effectively violated. and while this can in theory be mitigated via clever messaging mechanisms these do bear overhead that can become very significant both in maintenance burden and performance (think doubly linked list).

Has there beeen any consideration in this direction?

**Comment by jonas-schievink** [comment]
Language feature requests like this need to go through our [RFC process](https://github.com/rust-lang/rfcs), so I'll close this issue in favor of that. A good place to start discussing new features without having to write an entire RFC is by opening an issue in the issue tracker of the RFCs repo or by posting on https://internals.rust-lang.org/.

> i.e. somehow telling the compiler that a certain object has a lifetime scoped by some other object (i.e. the life time of the members of container are scoped by the container)

This sounds similar to arena allocation, which can already be done today. They're unsafe abstractions living on crates.io, and they generally only allow immutable access (unless I misremember) modulo interior mutability, but AFAIK you can even build cyclic graphs with them.

**Comment by maddanio** [comment]
hey, thanks for the quick response. will try to dig into that. if what you say is true (i.e. only allowing immutable access) then its not quite what i was imagining. but to be taken serious i really need to dig further. thanks!
