### ISSUE TITLE
azure: retry downloading the AWS CLI on network errors

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#61604]
It might happen that [downloading the AWS CLI fails](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/451/logs/445) due to a spurious network error.

The implementation should be really similar to https://github.com/rust-lang/rust/pull/61485, but applied to the AWS CLI download on Linux.

**Comment by wesleywiser** [comment]
Hi, I'd like to take this.
