### ISSUE TITLE
add option of outputting doc attributes to crates + a doc fetching tool

### ISSUE THREAD

**Issue by thestinger** [rust-lang/rust#6160]
Similar to Python's `pydoc` tool, it should just take a path and resolve it to the correct docstring. The REPL could also take advantage of this with a `:help` meta-command.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#650
