### ISSUE TITLE
x.py can't compile target json spec

### ISSUE THREAD

**Issue by mtthw-meyer** [rust-lang/rust#61628]
I'm trying to build Rust for a arm7 platform with neon enabled. I've got the spec dumped from armv7-unknown-linux-gnueabihf and changed the features to enable neon. I can't figure out how to get x.py to actually compile this thing without complaining. I have a sysroot with the appropriate compilers and I've tried building stage 0 and stage 1 with it.

    "features": "+v7,+vfp3,+d16,+thumb2,+neon

The first issue is there seems to be a bug with the bootstrap. It tries to use the .json to reference the config.toml and custom compilers get ignored. I have:

config.toml
```
[target.armv7-custom-linux-gnueabihf]
cc = "arc-aca-linux-gcc"
linker = "arc-aca-linux-gcc-ld"
ar = "arc-aca-linux-gcc-gnueabihf-ar"
```

```
./x.py build -i --stage 0 --target=armv7-custom-linux-gnueabihf.json --verbose
..snip..
CC_armv7-custom-linux-gnueabihf.json = "cc"
```
Opps, that's not the right compiler! At some point the .json should get removed and doesn't. And you can't just name it without the json and use it because cargo rejects it as not being a built-in target then and you can't add .json to the toml either.

Assuming I can get all that work I'll need to use wrappers for the compiler targets because there doesn't seem to be any support for sysroot built in already.

[armv7-custom-linux-gnueabihf.json](https://github.com/rust-lang/rust/files/3266972/armv7-custom-linux-gnueabihf.txt)

git status
HEAD detached at 37ff5d388f

**Comment by Mark-Simulacrum** [comment]
`x.py --target` doesn't currently accept JSON target specs, you'd need to pass that through some alternate means. I think it's possible your best bet is to add the target spec as a native one to the beta branch, create a compiler, and then use that as the bootstrap compiler via `rustc = ` in config.toml.

I don't think supporting JSON target specs is reasonable in rustbuild (i.e., it's out of scope) so I'm going to close this issue. If the above suggestion doesn't work then perhaps e.g. RUSTFLAGS will.
