### ISSUE TITLE
std::process::Command error messages leave a lot to be desired

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#61648]
````rust
 fn main() {
    let a = std::process::Command::new("blabla").output();
    let b = std::process::Command::new("ls").current_dir("blabla").output();

    println!("a: {:?}", a);
    println!("b: {:?}", b);
}
````

both commands will error and we will get
````
a: Err(Os { code: 2, kind: NotFound, message: "No such file or directory" })
b: Err(Os { code: 2, kind: NotFound, message: "No such file or directory" })
````
however there is no way to tell what is causing the error.
for `a` it is the `new()` argument that cannot be found, for `b` it is the `current_dir()` argument that could not be found.

We should be able to see what causes the problem right away.
It would already help a lot if the thing that could not be found was printed like so:
`No such file or directory: "blabla"`

**Comment by Mark-Simulacrum** [comment]
I don't think this is tenable today, since the relevant error doesn't have the space for any reference to the file/directory that isn't found. Including this information has a performance cost that the language can't accept. As such I'm going to close.
