### ISSUE TITLE
IBM z/OS (z System platform) target support

### ISSUE THREAD

**Issue by XVilka** [rust-lang/rust#61657]
There is seem [LLVM port for z/OS](https://www.ibm.com/developerworks/community/blogs/5894415f-be62-4bc0-81c5-3956e82276f3/entry/XL_C_C_V2_3_1_for_z_OS_V2_3_web_deliverable_is_available_today_on_March_29_2019?lang=en), and Rust supports s390, so should be possible to support the z/OS system as a full-featured target.

See example of the [Swift language porting](https://forums.swift.org/t/z-os-swift-and-encodings/5897) by IBM.

**Comment by petrochenkov** [comment]
This is not something that is supposed to be tracked by an issue in this repo.
If IBM or enthusiasts are interested in implementing such support, the patches will be accepted if they meet conditions of the target tier policy (https://github.com/rust-lang/rfcs/pull/2803).
