### ISSUE TITLE
Do you get feedback from users' Travis CI builds automatically?

### ISSUE THREAD

**Issue by 8573** [rust-lang/rust#61678]
[The documentation][1] on using Rust with Travis CI notes—

> The Rust team appreciates testing against the `beta` and `nightly` channels, even if you are only targeting `stable`.

If I, as a user of Rust who targets only stable, follow this recommendation and have Travis CI test my crate against beta and nightly as well, will you automatically get reports of any regressions such testing finds in beta/nightly, or would I have to look at the logs of failing beta/nightly builds and provide such feedback manually?

[1]: <https://docs.travis-ci.com/user/languages/rust/>

**Comment by lzutao** [comment]
No, rust should never collect user data automatically. It is recommend to provide
feedback manually.

**Comment by Mark-Simulacrum** [comment]
Yes, we don't get any reporting but would appreciate regression/bug reports as early as possible (even on nightly!).
