### ISSUE TITLE
Const variables cannot have cyclical references

### ISSUE THREAD

**Issue by rickvanprim** [rust-lang/rust#61674]
The following code produces an E0391 error.  Seems like this should be solvable, at least in this simplistic case.  Is this something that is likely to be allowed in the future?

```
struct Foo
{
    value: &'static Foo
}

const BAR: Foo = Foo { value: &BAZ };
const BAZ: Foo = Foo { value: &BAR };
```

**Comment by scottmcm** [comment]
`const`s aren't `static`s, so don't really have addresses, so that's doing rvalue-static-promotion, at which point it infinitely recursing seems expected, so no, I personally don't expect this would be different in future.

**Comment by rickvanprim** [comment]
Ah interesting, I wasn't aware of that!  Is there any other functional difference between a const and a static that's worth considering before replacing all my const expressions that I expect to have a fixed location with static?  The only thing that comes to mind is being able to declare const's inside of impl blocks but not static's.
