### ISSUE TITLE
add implementation of http and other related protocol to standard library

### ISSUE THREAD

**Issue by catastrop** [rust-lang/rust#61689]
We need use libraries for every time we want to do something with web. 
That's not helpful.

A language that came out in 2010s should have them. Like Golang has. Please consider to add them to standard library.

**Comment by nagisa** [comment]
As noted [here](https://github.com/rust-lang/rust/issues/61219#issuecomment-496030461) on a duplicate issue filled by you yourself, introducing such an API surface would require an RFC.

That being said, general direction of the Rust standard library is to provide only the core-most utilities and the user is expected to get the rest from the easy-to-use crates ecosystem.

**Comment by catastrop** [comment]
What will happen if i don't have internet connection?

**Comment by jonas-schievink** [comment]
Cargo has an [offline mode](https://github.com/rust-lang/cargo/issues/5655) that will reuse cached crates. You can also mirror crates on a machine in your local network.

**Comment by jonas-schievink** [comment]
Also, please stop filing duplicate issues. They won't make your problems get prioritized.
