### ISSUE TITLE
no issue created when clippy toolstate breaks

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#61693]
https://github.com/rust-lang/rust/pull/61672 broke clippy toolstate but there was no issue created automatically.

Probably linked to rls/clippy decoupling https://github.com/rust-lang/rust/pull/61670

**Comment by ehuss** [comment]
I don't think it is related to rls.  `clippy-driver` has never opened an issue when it has broken in the past.  

[The logs](https://travis-ci.com/rust-lang/rust/builds/114849497) say `I/O error: HTTP Error 422: Unprocessable Entity` which is GitHub's error message for "Sending invalid fields".  Unfortunately the script doesn't print the response body.

I can't see anything unusual in the script to explain why it would fail only for clippy-driver.  My best guess is that there is something wrong with the list of assignees. The API docs say you can assign up to 10, so the larger number shouldn't be a problem.

@kennytm I could add some more debug output to publish_toolstate.py to understand the 422 error.  I could also try to run the code locally with my own github token to see what the error is, but I don't want to generate noise pinging people if it succeeds.

**Comment by kennytm** [comment]
Apparently the GitHub API docs is wrong, unassignable users *are* causing the 422 errors instead of being silently dropped [as documented](https://developer.github.com/v3/issues/#create-an-issue).

No issues for clippy-driver because `@llogiq`, `@mcarton` and `@phansch` can't be assigned.

I think rustfmt will have the same issue because `@topecongiro` can't be assigned.

Additionally, no issues for #62003 because the assignees array included the PR author `@christianpoveda`, which also can't be assigned.

**Comment by kennytm** [comment]
(Re-nominating for what to do with the `assignees` field. )

**Comment by kennytm** [comment]
In yesterday's infra meeting, we have decided to fix this issue by separating the list of people to be assigned and mentioned, and also the PR author will no longer be assigned automatically. 

This could be implemented  by

1. Copy the `MAINTAINERS` configuration into a new dictionary of lists of usernames  `ASSIGNEES` containing only the assignable members: https://github.com/rust-lang/rust/blob/d3e2cec29225a46298ec4ebf082f34ebd7cfeecf/src/tools/publish_toolstate.py#L16-L31
2. Do not compute `assignees` in `issue()`, instead, accept another argument into the function https://github.com/rust-lang/rust/blob/d3e2cec29225a46298ec4ebf082f34ebd7cfeecf/src/tools/publish_toolstate.py#L65-L75
3. Obtain the assignees here https://github.com/rust-lang/rust/blob/d3e2cec29225a46298ec4ebf082f34ebd7cfeecf/src/tools/publish_toolstate.py#L163-L166

**Comment by ehuss** [comment]
I'm curious if it is necessary to set the assignee field at all.  If all the people are @ mentioned in the body, they should be sufficiently notified.   Does setting the assignee field have any benefits that I'm not aware of?  It seems like skipping all this would simplify it a lot.  These issues typically get fixed very quickly anyways.

**Comment by kennytm** [comment]
Assignees can reach the issues again from https://github.com/issues/assigned, but for mentions it will be gone once the notification is read.

**Comment by matthiaskrgr** [comment]
Is there a reason for keeping the issue open?
I think this might be fixed? cc https://github.com/rust-lang/rust/issues/62338

**Comment by RalfJung** [comment]
https://github.com/rust-lang/rust/pull/62023 implemented the strategy that the author of the breaking PR does not get assigned any more. So creating issues should always work now.

However, we still assume all people listed in `MAINTAINERS` can be assigned. That seems reasonable; the list is manually curated and at least historically adding people to *some* team was not a high bar.

So, closing this issue as fixed.

**Comment by ehuss** [comment]
>  we still assume all people listed in `MAINTAINERS` can be assigned

I don't think this is true. There are people in MAINTAINERS that cannot be assigned. For example, for clippy llogiq and mcarton are not members of this repo.  Given that, I'm a bit baffled how #62338 got opened.  It seemed to assign the first two people, and then ignored the rest?

**Comment by RalfJung** [comment]
Oh. That sounds like fun.

Any reason they can't be added so the org so that they can be assigned? Seems reasonable that people maintaining tools important enough to be tracked this way are added to the org (AFAIK that doesn't even automatically entail any new powers).

**Comment by RalfJung** [comment]
Otherwise my proposal would be to make `MAINTAINERS` a dictionary mapping tools to a pair of strings; the first will be assigned and the second just mentioned. That seems nicer to me than what @kennytm proposed, which would duplicate the tool list.

**Comment by RalfJung** [comment]
I think this has been resolved by https://github.com/rust-lang/rust/pull/64119.
