### ISSUE TITLE
Dist analysis step panics when trying to copy save-analysis

### ISSUE THREAD

**Issue by petrhosek** [rust-lang/rust#61703]
We're seeing the following error on our builders that are building Rust toolchain for Fuchsia:
```
Dist analysis
image_src: "/b/s/w/ir/k/recipe_cleanup/rust9mc0u9/build/build/x86_64-unknown-linux-gnu/stage2-std/x86_64-unknown-linux-gnu/release/deps/save-analysis", dst: "/b/s/w/ir/k/recipe_cleanup/rust9mc0u9/build/build/tmp/dist/rust-analysis-nightly-x86_64-unknown-linux-gnu-image/lib/rustlib/x86_64-unknown-linux-gnu/analysis"
thread 'main' panicked at 'fs::read_dir(src) failed with No such file or directory (os error 2)', src/bootstrap/lib.rs:1217:18
```
The `save-analysis` directory is entirely missing for the host target. I've been debugging this and I believe the problem is that for host target, we don't build `std` in `stage2`, we always uplift it from `stage1`, and therefore we never generate `save-analysis` in `stage2`. We should probably uplift `save-analysis` from `stage1` as well.

**Comment by Mark-Simulacrum** [comment]
Seems reasonable, I think - happy to review a PR or if you could give a specific set of reproduction instructions (ideally ones that would work on linux).
