### ISSUE TITLE
More systematic compile/run markup for "pass" UI tests

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rust#61712]
TLDR:
```
In test files:

// check-pass
// build-pass
// run-pass

In `x.py` command line (forcing):

--force =check
--force >=check
--force <=check
--force =build
--force >=build
--force <=build
--force =run
--force >=run
--force <=run

In `x.py` command line (running a subset):

--select =check
--select >=check
--select <=check
--select =build
--select >=build
--select <=build
--select =run
--select >=run
--select <=run
```

TODO:
More detailed description, motivation, etc.

cc @Centril

**Comment by Centril** [comment]
I've added:
```rust
    /// Only run tests that match any of these modes.
    pub filter_mode: Option<Vec<Mode>>,
```
to `Config`.

The thinking is that you pass `--filter-mode run-pass,compile-fail,...` and have only those tests run.

A `--filter-mode` scheme seems easiest to implement given the current compiletest infrastructure and doesn't require us to rename a bunch of annotations.

**Comment by petrochenkov** [comment]
After some thought, perhaps filtering is not even necessary with `--force check`.
I'll make some experiments and report (sometime this week).

**Comment by petrochenkov** [comment]
Addressed by https://github.com/rust-lang/rust/pull/61778 and https://github.com/rust-lang/rust/pull/61755.
