### ISSUE TITLE
Release x86_64-pc-windows-gnu target of mingw-w64 6.x 

### ISSUE THREAD

**Issue by songdongsheng** [rust-lang/rust#61710]
Currently,   x86_64-pc-windows-gnu target build on mingw-w64 v5.x (2 years ago):

`
x86_64-6.3.0-release-posix-seh-rt_v5-rev2.7z

GNU ld (GNU Binutils) 2.27
gcc version 6.3.0 (x86_64-posix-seh-rev2, Built by MinGW-W64 project)
`

Nowadays, Debian 10 and Msys2 provide mingw-w64 v6.x:

`# dpkg -l | grep  mingw-w64
ii  binutils-mingw-w64-x86-64                   2.31.1-11+8.3                amd64        Cross-binutils for Win64 (x64) using MinGW-w64
ii  gcc-mingw-w64-base                          8.3.0-6+21.2                 amd64        GNU Compiler Collection for MinGW-w64 (base package)
ii  gcc-mingw-w64-x86-64                        8.3.0-6+21.2                 amd64        GNU C compiler for MinGW-w64 targeting Win64
ii  mingw-w64-common                            6.0.0-3                      all          Common files for Mingw-w64
ii  mingw-w64-x86-64-dev                        6.0.0-3                      all          Development files for MinGW-w64 targeting Win64
`

This caused error 'undefined reference to `__onexitend''.

**Comment by mati865** [comment]
Related https://github.com/rust-lang/rust/issues/47048
Latest toolchain release by mingw-w64 couldn't build LLVM: https://github.com/rust-lang/rust/pull/51989

@rustbot modify labels: +O-windows-gnu

**Comment by gnzlbg** [comment]
@mati865 is there an a script somewhere to workaround this in appveyor ?

**Comment by mati865** [comment]
@gnzlbg I don't know if there is script that automatically fixes everything (there are different errors depending on many things), you'd have to try replacing various `*.a` and `.o` files and changing linker to use external compiler.
If you point me the repo I'll try to get it working later today or tomorrow.

For the ultimate fix I think Rust should prefer to use external toolchain libs if they are available but I didn't have time to understand all the code involved in the linking.

**Comment by gnzlbg** [comment]
I was working on this ctest PR which started triggering the issue because it uses fprintf from C: https://github.com/gnzlbg/ctest/pull/73

**Comment by mati865** [comment]
This issue is now obsolete since Rust prefers system C toolchain instead of shipped one so builds no longer fail with `undefined reference to __onexitend`.

**Comment by mati865** [comment]
Mingw-w64 has been updated to latest version on nightly.

**Comment by Mark-Simulacrum** [comment]
Closing as resolved per above.
