### ISSUE TITLE
two separate but identical versions of a crate in dependency tree

### ISSUE THREAD

**Issue by brenzi** [rust-lang/rust#61725]
I get the following funny behaviour:

```
> cargo tree  -i -p untrusted
error: There are multiple `untrusted` packages in your project, and the specification `untrusted` is ambiguous.
Please re-run this command with `-p <spec>` where `<spec>` is one of the following:
  https://github.com/briansmith/untrusted#0.6.2
  https://github.com/briansmith/untrusted#0.6.2
```
As you see, the versions are identical but cargo seems not to realize that

This issue causes errors like
```
  --> /home/brenzi/.cargo/registry/src/github.com-1ecc6299db9ec823/libp2p-core-0.7.1/src/identity/rsa.rs:74:27
   |
74 |                           Input::from(msg),
   |                           ^^^^^^^^^^^^^^^^ expected struct `untrusted::Input`, found a different struct `untrusted::Input`
   |
   = note: expected type `untrusted::Input<'_>` (struct `untrusted::Input`)
              found type `untrusted::Input<'_>` (struct `untrusted::Input`)
note: Perhaps two different versions of crate `untrusted` are being used?
```

I assume this is caused by a patch statement in workspace Cargo.toml
```
...
[patch.crates-io]
untrusted = { git = "https://github.com/briansmith/untrusted" }
...
```
which is needed because otherwise two *truly* different versions of `untrusted` would collide.

Here's my repo showing this behaviour: https://github.com/scs/substraTEE-worker/tree/brenzi-ra

**Comment by brenzi** [comment]
This is related to https://github.com/rust-lang/cargo/issues/6961

And actually, I should've filed the issue with cargo, not with rust. Sorry

**Comment by Mark-Simulacrum** [comment]
Closing, please refile as a Cargo issue if this is still a problem (or followup on rust-lang/cargo#6961).
