### ISSUE TITLE
as_ref suggestions should warn about UB concerns

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#61786]
With https://github.com/rust-lang/rust/pull/61444 we are now suggesting people to use `as_ref` when they have a raw pointer and need a reference. With https://github.com/rust-lang/rust/pull/61785 `as_ref` gets some expanded documentation on UB avoidance. It might be a good idea to mention that also in the actual suggestion, so people don't have to open the docs to be aware of this.

Cc @estebank

**Comment by imbrem** [comment]
Can I take this on, since no one seems to have done it yet?

**Comment by RalfJung** [comment]
Sure, it's yours!
