### ISSUE TITLE
Provide a way to generate doc comment content

### ISSUE THREAD

**Issue by SillyFreak** [rust-lang/rust#61795]
I'm trying to generate doc comments from a more concise form, and as far as I can tell there is no way to do this. My example is citing an external source: given the reference `"label"`, I want to generate

    /// See [somewhere](https://example.com/document/#somewhere)

I have tried a few avenues of injecting doc content: `#[doc = my_doc!("foo")]` [doesn't work](https://stackoverflow.com/a/41945753/371191); an attribute macro `#[my_doc("foo")]`, generating a `#[doc = "foo"]` attribute, interacts incorrectly with literal doc comments/attributes, and multiple "macro doc attributes":

```
/// a
///
#[my_doc("b")]
///
/// c
///
#[my_doc("d")]
///
/// e
```

becomes

> d b a
> c
> e

that is, macro expansion happens first, reversing order, then doc comments/attributes come after; so it seems attribute macros are not really applicable for this. 

I can't judge what would be the implications of various avenues to fix this, but I wanted to put the report out there.

**Comment by jonas-schievink** [comment]
Maybe what [`doc-comment`](https://docs.rs/doc-comment) does could help?

**Comment by SillyFreak** [comment]
Hmm, it lets me implement what I need, and solves what I asked for in the title. Thanks for the suggestion!

That it requires to wrap my definition into the macro invocation (i.e. `doc_comment!("...", struct Foo;);` is a little annoying, but I think it can't be helped. Writing `#[my_doc(quote!(""))]`does not work, so there is currently no hope to implement doc-comment as an attribute macro.
