### ISSUE TITLE
azure: `sccache` not found

### ISSUE THREAD

**Issue by ecstatic-morse** [rust-lang/rust#61790]
The Azure pipeline is currently failing on my PR because it is [unable to find `sccache`](https://dev.azure.com/rust-lang/rust/_build/results?buildId=606&view=logs&jobId=d5810e3a-0d17-5d9d-3d2e-f99007e94ae9&taskId=e50ec509-f79e-5c61-3d86-4e0717295716&lineStart=136&lineEnd=136&colStart=1&colEnd=42).

**Comment by pietroalbini** [comment]
This should be fixed by https://github.com/rust-lang/rust/pull/61772.
