### ISSUE TITLE
`unreachable_code` warning when invoke `.await` on async diverging function

### ISSUE THREAD

**Issue by nextzhou** [rust-lang/rust#61798]
I tried this code:

```rust
async fn foo() {
    endless().await;
}

async fn endless() -> ! {
    loop {}
}
```

I expected to see this happen: no build warn

Instead, this happened:
```
warning: unreachable expression
 --> src/main.rs:8:5
  |
8 |     endless().await;
  |     ^^^^^^^^^^^^^^^
  |
  = note: #[warn(unreachable_code)] on by default
```

## Meta

`rustc --version --verbose`:

```
rustc 1.37.0-nightly (5f3656ce9 2019-06-11)
binary: rustc
commit-hash: 5f3656ce9a2212fad872605b7a4ee103a155e9f3
commit-date: 2019-06-11
host: x86_64-unknown-linux-gnu
release: 1.37.0-nightly
LLVM version: 8.0
```

**Comment by Centril** [comment]
@jonas-schievink This seems like expected behavior to me, what is the bug?

**Comment by nikomatsakis** [comment]
We [discussed this a bit on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/187312-wg-async-foundations/topic/unclear.20issue.20triage/near/168958460). The likely cause is that parts of the await desugaring are being linted against. We can likely check the span to see if the code that is being linted against is part of the `.await` desugaring, but we do want to be careful to ensure that

```rust
async fn foo() {
    return; bar().await;
}

async fn bar() {
}
```

still gets a lint warning.

**Comment by nikomatsakis** [comment]
Marking as deferred as this doesn't seem like a problem that needs to block stabilization.

**Comment by Centril** [comment]
cc @varkor who has done some work on the inhabited logic stuff.

**Comment by ChrisGreenaway** [comment]
I'm now getting this warning even for functions that loop but eventually return. It worked fine with nightly-2019-08-21, but the latest nightly (2019-09-17) is broken.

For example, this code generates a warning:
```
async fn run(&mut self) {
    loop {
        match self.target_status {
            Some(_) => self.update_status().await,
            None => match &self.current_status {
                OperationStatus::PENDING => self.set_target_status(OperationStatus::EXECUTING),
                OperationStatus::EXECUTING => match self.operation.run().await {
                    Ok(()) => self.set_target_status(OperationStatus::SUCCESSFUL),
                    Err(e) => self.set_target_status(OperationStatus::FAILED(format!("{:?}", e))),
                },
                _ => return,
            },
        }
    }
}
```

with the warning repeated twice:
```
  --> src\operations.rs:82:29
   |
82 |       async fn run(&mut self) {
   |  _____________________________^
83 | |         loop {
84 | |             match self.target_status {
85 | |                 Some(_) => self.update_status().await,
...  |
95 | |         }
96 | |     }
   | |_____^
error: unreachable expression
  --> src\operations.rs:82:29
   |
82 |       async fn run(&mut self) {
   |  _____________________________^
83 | |         loop {
84 | |             match self.target_status {
85 | |                 Some(_) => self.update_status().await,
...  |
95 | |         }
96 | |     }
   | |_____^

```

**Comment by PvdBerg1998** [comment]
Can confirm. I believe this regressed somewhere after nightly 09-09-2019.

**Comment by MOZGIII** [comment]
I think I have this in my code here: https://github.com/MOZGIII/netsound/blob/cc16cd94c3b5d0e75e18719f223e205f4aaaadb0/src/net/recv.rs#L46

Can somebody confirm this? If not I'll file another bug report.

**Comment by PvdBerg1998** [comment]
@MOZGIII yeah that's the same, the function can "never" return from the unconditional loop.
