### ISSUE TITLE
#![feature(type_alias_enum_variants)]: Unit variant pattern through a type alias to generic enum requires type annotations

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#61801]
The following, which I expect to work, fails to infer the type of `OptAlias::None`:

```rust
#![feature(type_alias_enum_variants)]

enum Option<T> {
    None,
    Some(T),
}

type OptAlias<T> = Option<T>;

fn work_on_alias(x: OptAlias<u8>) {
    match x {
        OptAlias::None => (), //~ ERROR type annotations needed
        _ => (),
    }
}
```

In HIR, `OptAlias::None` should correspond to:
```rust
PatKind::Path(
    QPath::TypeRelative(_, P(
        PathSegment { res: Some(
            Res::Def(DefKind::Ctor(CtorOf::Variant, CtorKind::Const))
        ), .. }
    ))
)
```

However, if we change the snippet to:

```rust
#![feature(type_alias_enum_variants)]

enum Option<T> {
    None,
    Some(T),
}

type OptAlias<T> = Option<T>;

fn work_on_alias(x: OptAlias<u8>) {
    match x {
        OptAlias::None {} => (), // Note the changed pattern.
        _ => (),
    }
}
```
it all works out fine.

I also tested changing `None` to a tuple variant and that works also.

cc @petrochenkov @eddyb @alexreg 

cc https://github.com/rust-lang/rust/pull/61682

**Comment by Centril** [comment]
It might be a good idea to trace the difference between `check_pat_path` and `check_pat_tuple_struct` because they look relatively similar and yet they behave differently in terms of inference.

**Comment by petrochenkov** [comment]
Value (`OptAlias::None`/`OptAlias::None()`) and type (`OptAlias::None {}`) namespaces execute very different logic for type inference (`resolve_ty_and_res_ufcs`/`instantiate_value_path` vs `check_struct_path`).
It's quite possible that there are intended and unintended observable differences.

>check_pat_path and check_pat_tuple_struct

Rather `check_pat_path` and `check_pat_struct`.
(`check_pat_tuple_struct` is the same "value" case as `check_pat_path`.)
