### ISSUE TITLE
Get rid of the `test-miri` flag in `config.toml`

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#61833]
The `test-miri` flag changes whether `-Zalways-encode-mir` is passed to rustc, causing all metadata beyond stage 0 to include MIR of all functions, even private monomorphic ones. Instead, what we can do is to have miri tests first run `cargo miri setup` to generate that special `libstd` in CI in addition to the regular `libstd`. Then tests can be run with special `libstd`.

cc @RalfJung

**Comment by RalfJung** [comment]
Worse, it also makes `--cfg miri` passed to rustc, meaning we get the hasbrown without SIMD!

**Comment by RalfJung** [comment]
Oh also, ideally this could use or at least share some code with the [build script Miri uses to do the same on its own CI](https://github.com/rust-lang/miri/blob/master/miri).

**Comment by RalfJung** [comment]
I submitted a PR for this at https://github.com/rust-lang/rust/pull/63162.
