### ISSUE TITLE
rustc runs out of memory when compiling an `if` statement with no block, enclosed in parentheses

### ISSUE THREAD

**Issue by kuretchi** [rust-lang/rust#61858]
I tried this code:

```rust
fn main() {
    (if foobar)
}
```

```bash
$ ulimit -v 2000000  # 2 GB
$ rustc main.rs
```

`rustc` first outputs some error messages and then hangs up trying to allocate a large amount of memory.

```
error: expected `{`, found `)`
 --> main.rs:2:15
  |
2 |     (if foobar)
  |      --       ^ expected `{`
  |      |
  |      this `if` statement has a condition, but no block

error: expected expression, found `<eof>`
 --> main.rs:3:1
  |
3 | }
  | ^ expected expression

memory allocation of 1610612736 bytes failedAborted (core dumped)
```

[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=28d004ae7c4726088b4faecf892cb543)

## Meta

`rustc --version --verbose`:

```
rustc 1.35.0 (3c235d560 2019-05-20)
binary: rustc
commit-hash: 3c235d5600393dfe6c36eeed34042efad8d4f26e
commit-date: 2019-05-20
host: x86_64-unknown-linux-gnu
release: 1.35.0
LLVM version: 8.0
```

**Comment by lzutao** [comment]
Rust 1.34.0 and before is OK: https://godbolt.org/z/dFMxwR

**Comment by pnkfelix** [comment]
triage: P-medium. Removing nomination. Assigning to self and @estebank for initial investigation.

**Comment by dwrensha** [comment]
I'm seeing the same behavior on the following programs:
```rust
pub fn m(<k<kn(m(nka[ nka[ (]k(
```

and 
```rust
fn z() { loop { w& if ( if (r( loop { w if ( if (r
```

These were found with the help of [libfuzzer-sys](https://github.com/rust-fuzz/libfuzzer-sys).

**Comment by dwrensha** [comment]
Another program that I also observe to make `rustc` run out of memory:
```rust
fn a() -> i32 { let c c2( } fn b(x:[
```

**Comment by estebank** [comment]
The original report is caused due to `Parser::expected_tokens` growing unbounded in a bad parser code path, in part due to it being a `Vec` and not a `FxHashSet` (which it can't be at the moment). Now that I have a clue at what causes the behavior, I'll dig deeper for the trigger.
