### ISSUE TITLE
Trying to use same existential type for two functions cause cycle dependency

### ISSUE THREAD

**Issue by shootingsyh** [rust-lang/rust#61863]
On a nightly rustup 1.18.3 (435397f48 2019-05-22)
Some code like this
```
#![feature(existential_type)]
pub trait T {
    fn bla() -> ();
}

pub struct S {
  v: u64
}

impl T for S {
    fn bla() -> () {}
}

existential type TE: T;
pub fn bla() -> TE {
    return S {v:1}
}

pub fn bla2() -> TE {
    bla()
}
```

cause error 

> Compiling playground v0.0.1 (/playground)
> error[E0391]: cycle detected when processing `TE`
>   --> src/lib.rs:14:1
>    |
> 14 | existential type TE: T;
>    | ^^^^^^^^^^^^^^^^^^^^^^^
>    |
> note: ...which requires processing `bla2`...
>   --> src/lib.rs:19:21
>    |
> 19 |   pub fn bla2() -> TE {
>    |  _____________________^
> 20 | |     bla()
> 21 | | }
>    | |_^
>    = note: ...which again requires processing `TE`, completing the cycle
> note: cycle used when collecting item types in top-level module
>   --> src/lib.rs:1:1
>    |
> 1  | / #![feature(existential_type)]
> 2  | | pub trait T {
> 3  | |     fn bla() -> ();
> 4  | | }
> ...  |
> 20 | |     bla()
> 21 | | }
>    | |_^
> 
> error: concrete type differs from previous defining existential type use
>   --> src/lib.rs:19:1
>    |
> 19 | / pub fn bla2() -> TE {
> 20 | |     bla()
> 21 | | }
>    | |_^ expected `S`, got `TE`
>    |
> note: previous use here
>   --> src/lib.rs:15:1
>    |
> 15 | / pub fn bla() -> TE {
> 16 | |     return S {v:1}
> 17 | | }
>    | |_^
> 
> error: aborting due to 2 previous errors

playground link: 
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=71c724f92b074d0b6f355a6aaf8d3d1a

**Comment by Aaron1011** [comment]
I think the most straightforward way to resolve this would be to try to 'recover' from the cycle error, and see if processing any other items allows us to constraint the existential type. Unfortunately, [the docs state](https://rust-lang.github.io/rustc-guide/queries/query-evaluation-model-in-detail.html) that cycle recovery was removed.
