### ISSUE TITLE
rustc should use vendor names for target features

### ISSUE THREAD

**Issue by newpavlov** [rust-lang/rust#61895]
Right now in source code we follow vendor names and not LLVM ones (e.g. `rdrand` and not `rdrnd`). Translation is handled [here](https://github.com/rust-lang/rust/blob/master/src/librustc_codegen_llvm/llvm_util.rs#L214). But when enabling target feature via `rustc` flags we have to use LLVM names, i.e. `-C target-feature=+rdrnd` and `+rdrand` will not work. So we have inconsistency on our hands.

At the very least vendor names provided in `rustc` flags should be translated to LLVM ones. Additionally I think we should not expose LLVM names at all, including in `rustc --print target-features`.

Relevant: #50077, #48369

**Comment by rkruppe** [comment]
cf. https://github.com/rust-lang/rust/issues/49653
