### ISSUE TITLE
recruitment：Block chain rust development engineer

### ISSUE THREAD

**Issue by caesarchad** [rust-lang/rust#61905]
Hello, I'm Bob from Bitconch, the world's only high-performance blockchain with 120,000 TPS(MVP) compatible with eitfang smart contracts.It benefits from innovative reputation proof (POR) algorithms.Bitconch also helps developers engage and share their perspective users.Developers can deploy their dapps or nodes on the Bitconch blockchain to achieve more users, higher bit-r values and better rewards.Developers who need to attract users will also benefit from bit-t systems, which encourage users to use as many applications as possible.

What benefits do we have as a young Internet company???
The administration department beautiful greasy young lady sisters will prepare delicious snacks for you!What!!!Let's eat and knock on some code.There are so many different kinds of drinks.

We Bitconch to and from work do not knock card, do not knock card, do not knock card, ultra-elastic working time, free zero touch.

Bitconch also has independent gyms and showers. Bitconch promotes healthy work and healthy living. Nothing is more important than your health.
There are many benefits to explore for yourself!

Current position ↓

Block chain Rust development engineer

Main work list:

Bitconch is an early stage startup based in the business heart of China, Shanghai. We are set to revolutionize the financial services world by leveraging Social Graph and Blockchain Technology. Our mission is to create an autonomous, decentralized financial services platform that will enable our customers to quickly build applications with top performance and high availability.

We are looking for exceptional developers, whether experienced or junior, that are entrepreneurial/innovative at heart. You must be able to demonstrate your excellence through projects, and/or open source technology contribution. You will need to have a deep passion for technology, perseverance and determination to succeed in this position.

The ideal candidate is looking for a challenge and has experience working on a large scale platform. You should have an aptitude for architectural decisions which optimize scalability and performance. This role also requires you to wear multiple hats and think outside of the box, it is a rewarding experience full of opportunities for growth and professional development.

If you wish to be a part of the next wave of technical innovation and have a passion for software development and continuous learning, this is the opportunity for you!

Responsibilities:

• Design and architect the blockchain protocol based on the product demand, implement decentralized, distributed blockchain consensus and syncing protocol
• Design, develop, test, deploy, maintain, and improve software across the stack. Write clean, high quality code and test cases
• Deploy product on cloud-base infrastructure, and provide input on improvement of such hardware and software work with IT staff in providing assistance in software development, creating of test plans, deployment plans, and other project direction
• Use continuous integration technology to build, deploy and test all aspect of the products to ensure high quality delivery
• Strictly adhere to all security protocols and processes and work diligently to protect the assets of the company and its customers
• Developing new functionality and maintaining existing components, Develop automated tests and deliver high-quality code to production within a short development cycle
• Identify issues and implement solutions to complex problems in large-scale backend infrastructure platforms
• Manage and maintain blockchain/cloud infrastructure as required
• Work with researchers to transform prototype solutions into well architected applications
• Work with development teams to ensure reliable transfer of technology
• Keep abreast of the latest developments in the field by continuous learning and proactively champion promising new methods relevant to the problems at hand
• Monitor, research and evaluate Blockchain technologies
Basic Qualifications:

• Expert knowledge of multiple programming languages such as C++, Go, Java, JavaScript, Python
• Strong knowledge of data structures, algorithms, operating systems, and distributed systems fundamentals.
• Strong understanding of databases, NoSQL systems, storage and distributed persistence technologies
• Strong troubleshooting and performance tuning skills
• Understanding of microservices architecture and Docker infrastructure,familiar with Linux and DevOps in Docker
• Understanding of security technologies: PKI, Crypto, identity management
• Strong sense of ownership, passion to build quality products for massive scale in collaborative, agile environment and excitement to learn.
• Strong communication (written and verbal), time management and interpersonal skills
• Experience working in an Agile/Scrum development process, including flexibility and willingness to accept a change in priorities as necessary
• BS in in Computer Science or related engineering fields
Preferred Qualifications:

• Demonstrated hands-on experience with blockchain technology, ideally with Bitcoin, Ethereum, Hyperledger Fabric and cryptocurrencies in general
• Deep understanding of mainstream consensus algorithm, including but not limited to PoW, PoR, PoS, DPoS, PBFT, Paxos, Raft and so on.
• Experience creating blockchain frameworks and business applications, including decentralized applications (DAPPS), smart contracts and custom tokens
• Experience with one or more blockchain application development platform: Ethereum Solidity, HyperLedger Fabric, R3/Corda, NEO, etc.
• MS/PhD in in Computer Science or related engineering fields
Experience:

• Software Development: 3 years
Education:

• Bachelor's
Language:

• Chinese Mandarin
• English

Looking forward to your joining
Please send your resume (including all previous excellent projects and experience, if possible) to:
563279521 @qq.com
Address: 7 / f, building C7, no.36, lane 1688, guo-quan north road, yangpu district, Shanghai

**Comment by csmoe** [comment]
For rust jobs, we have https://twitter.com/ThisWeekInRust.
