### ISSUE TITLE
Missing linker symbols with incremental build

### ISSUE THREAD

**Issue by jsgf** [rust-lang/rust#61917]
I'm seeing linker errors of the form:
```
  = note: buck-out/dev/gen/scm/mononoke/mononoke_types/mononoke_types-unittest#binary,unittest/mononoke_types_unittest-3fe649e44bd0ade8.42tcmeh8woei6igl.rcgu.o:42tcmeh8woei6igl:function mononoke_types_unittest::hash::Sha256::from_bytes: error: undefined reference to '<T as core::convert::Into<U>>::into'
          buck-out/dev/gen/scm/mononoke/mononoke_types/mononoke_types-unittest#binary,unittest/mononoke_types_unittest-3fe649e44bd0ade8.42tcmeh8woei6igl.rcgu.o:42tcmeh8woei6igl:function mononoke_types_unittest::hash::Sha1::from_bytes: error: undefined reference to '<T as core::convert::Into<U>>::into'
          clang-8: error: linker command failed with exit code 1 (use -v to see invocation)
```

I have no idea how to get a small repro for this, but:
- This is a Buck build, rather than cargo
- It only happens with incremental builds. If I either remove the incremental DB or disable incremental builds, it works
- It only happens at opt-level=1; opt-level=0 and opt-level=3 are fine
- It goes away if I make small code changes, but it doesn't seem to matter what (which says incremental)
- Changing codegen-units doesn't affect anything.

This might be a dup of https://github.com/rust-lang/rust/issues/45929, but I'm not sure what.

Ugh, and now I can't repro it again. This, or something like it, has been showing up every week or so, so I'll update the next time I hit it.

**Comment by jonas-schievink** [comment]
Yeah this has popped up [quite a few times](https://github.com/rust-lang/rust/issues?utf8=%E2%9C%93&q=is%3Aopen+label%3AA-incr-comp+label%3AA-linkage). Nominating to prioritize and maybe get to the bottom of these problems. I've also got a reliable reproduction of this in https://github.com/rust-lang/rust/issues/59535.

**Comment by ehuss** [comment]
Cargo recently had a user report something similar (https://github.com/rust-lang/cargo/issues/7015) where disabling incremental solved the problem.  I wasn't able to ever repro it myself, though.  I'm not sure if T-compiler wants more examples or information, or if the general problem is understood.

**Comment by dtolnay** [comment]
Closing in favor of #59535 which has a reliable repro based on Cargo. I transferred the nomination.
