### ISSUE TITLE
Weird 2018 module hierarchy issue.

### ISSUE THREAD

**Issue by crlf0710** [rust-lang/rust#61924]
I'm trying to migrate a library called `winit` to 2018 module hierarchy, but this issue blocks me from finishing it. The problem is this:
The files:
```
src/platform_impl.rs
src/platform_impl/windows.rs
src/platform_impl/windows/dpi.rs
```

In `platform_impl.rs`:
```
#[cfg(target_os = "windows")]
#[path="platform_impl/windows.rs"]
mod platform;
```

In `src/platform_impl/windows.rs`:
```
mod dpi;
```

However, the compiler cannot find the `src/platform_impl/windows/dpi.rs` file, instead, it is only looking for `src/platform_impl/dpi.rs` or `src/platform_impl/dpi/mod.rs`.

Is this expected behavior?

**Comment by est31** [comment]
See also #59345

**Comment by crlf0710** [comment]
Yes, exactly. Tried to search for existing issue, but didn't find it. Sorry, I'll close as duplicate.
