### ISSUE TITLE
failed to run rustc to learn about target-specific information

### ISSUE THREAD

**Issue by ghost** [rust-lang/rust#61925]
~~~
$ cargo new aa
Created binary (application) `aa` package

$ cd aa
$ cargo build
error: failed to run `rustc` to learn about target-specific information

Caused by:
process didn't exit successfully: `rustc - --crate-name ___ --print=file-names
--crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib
--crate-type staticlib --crate-type proc-macro` (exit code: 0xc0000135,
STATUS_DLL_NOT_FOUND)
~~~

**Comment by lzutao** [comment]
Please provide more information: 
* What is your operating system? What is its version? What is its architecture?
* What is your rustc version (run `rustc -Vv` to get output)?

**Comment by cup** [comment]
so i installed rust to directory `aaaaa`, then symlinked `rustc` and `cargo` to directory `bbbbb`.

directory `bbbbb` is on my `PATH`, but not directory `aaaaa`. this seems to be causing the problem. if i just delete `bbbbb` and add `aaaaa` to my `PATH` then everything works

but other programming languages dont require this. "Go", "D" and "Nim" all work with the symlink method. Rust should too.

**Comment by lzutao** [comment]
It should. But that's often a job of rustup. How do you install rust? From rustup or 
from archive? Also please provide more information listed in https://github.com/rust-lang/rust/issues/61925#issuecomment-502962172 .

**Comment by nagisa** [comment]
My suspicion is that, with symlinking, rustc’s sysroot changes – that is where it looks for dynamic libraries such as codegen backends – which did not get symlinked along with rustc.

Can you please run `rustc --print sysroot` for both original installation of rustc and the symlinked rustc?

**Comment by cup** [comment]
> What is your rustc version (run `rustc -Vv` to get output)?

~~~
rustc 1.35.0 (3c235d560 2019-05-20)
binary: rustc
commit-hash: 3c235d5600393dfe6c36eeed34042efad8d4f26e
commit-date: 2019-05-20
host: x86_64-pc-windows-gnu
~~~

> How do you install rust?

~~~
lessmsi x rust-1.35.0-x86_64-pc-windows-gnu.msi
~~~

> Can you please run `rustc --print sysroot` for both original installation of
> rustc

~~~
C:\Rust
~~~

> and the symlinked rustc?

~~~
C:\Rust
~~~

**Comment by ehsanmok** [comment]
I've found the same issue in one of the Ubuntu 18.04 servers today. Uninstalled `rustup self uninstall` and did the fresh installation `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh` but it cannot compile anything.

**Comment by nagisa** [comment]
Might be a separate issue, please file another one.

**Comment by ehsanmok** [comment]
@nagisa It turned out the culprit was sccache and everything is ok now.

**Comment by palfrey** [comment]
I hit this, because I had `RUSTC_WRAPPER=sccache` set but didn't have `sccache` installed yet

**Comment by mati865** [comment]
Triage: works for me.

I've tried with directory symlink and directory junction. In both cases `windows-gnu` cargo can compile hello-world example with only symlink/junction being available in PATH.

**Comment by Mark-Simulacrum** [comment]
I'm going to go ahead and close this per @mati865's testing. New issues can be filed if this is still a bug.

**Comment by ra0x3** [comment]
- Just a small note for others that might come across this issue. 
- `sccache` was indeed the issue for me as well - using [cross.rs](https://github.com/cross-rs/cross)
- Solved by removing `rustc-wrapper` from the `[build]` of `~/.cargo/config.toml`
- Using `rustc 1.67` on `x86-64-apple-darwin`
