### ISSUE TITLE
Windows Shell32.lib is not linked by default?

### ISSUE THREAD

**Issue by top1st** [rust-lang/rust#61921]
while cargo install and compile time the shell32 functions not included.
while building we can update build.rs file but when install from online how i have to setup it?

.\cargo\.cartes.toml
.\rustup\settings.toml

or need to crate new config file?

**Comment by top1st** [comment]
then it is that crate's responsibility to ensure that shell32.lib is being linked in.

I have problem while instaling disel_cli on windows.
shell32 functions and openssl functions in libpq not linking well.
Why issues closed? I still did not solved this problem. How i can set default to link shell32.lib while cargo install disel_cli?

cargo build can resolve shell32 by adding build.rs file
but i did not solved while cargo install [package from online]

**Comment by retep998** [comment]
If you're having linking issues with diesel_cli or with libpq then please report them on the issue trackers for diesel_cli and libpq. This issue was closed because it is not Rust's fault and therefore does not belong on this issue tracker.
