### ISSUE TITLE
Lint on uses of XOR as if it were POW: `2 ^ 32`

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#61934]
[Given `2^32`](https://mobile.twitter.com/johnregehr/status/1139295920997068800) [is a common](https://codesearch.isocpp.org/cgi-bin/cgi_ppsearch?q=2%5E32&search=Search) [enough mistake](https://stackoverflow.com/questions/4843304/why-is-my-power-operator-not-working) to make, to the point that [GCC is adding a lint for it](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=90885), we probably should lint `2 ^ 8`, `2 ^ 16`, `2 ^ 32` and `2 ^ 64` as well and suggest `2u64.pow(x)` or even better `std::u64::MAX`.

**Comment by jonas-schievink** [comment]
https://github.com/rust-lang/rust-clippy/pull/4213 implements this in clippy

**Comment by nagisa** [comment]
This does not really pass the bar for no-false-positive-lints-in-rustc and is also RFC material.

**Comment by estebank** [comment]
Closing in lieu of the clippy lint
