### ISSUE TITLE
The Iterator trait is not always linked in the list of implementors

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#61958]
!["Iterator" linked in "Implementations on foreign types" but not in the "Implementors" section](https://user-images.githubusercontent.com/679122/59767223-7ebe3100-92aa-11e9-820b-1650ee39a0bd.png)

**Comment by nagisa** [comment]
At the end of the list of implementors some of the `Iterator`s *are* linked though.

**Comment by ebarnard** [comment]
This looks to be true generally: https://doc.rust-lang.org/nightly/std/fmt/trait.Display.html.

**Comment by memoryruins** [comment]
Introduced in 1.10.0
https://doc.rust-lang.org/1.9.0/std/fmt/trait.Display.html
https://doc.rust-lang.org/1.10.0/std/fmt/trait.Display.html
then misses links for every version into current nightly.

**Comment by lolbinarycat** [comment]
triage: seems to be fixed now.
