### ISSUE TITLE
`allow(unused)` suppresses unrelated lints

### ISSUE THREAD

**Issue by BartMassey** [rust-lang/rust#61954]
`rustc 1.35.0`. This program compiles with no warnings.

```rust
#![allow(unused)]

fn main() {
    let mut hello = "hello";
    if (0 == 0) {
        println!("{}", hello);
    }
}
```

Removing the first line gives the expected warnings about unneeded `mut` and parens on the `if` test.

**Comment by matthiaskrgr** [comment]
Hi, this is not a bug.

`allow(unused)` allows the `unused` LINT GROUP which consists of the following lints:

`unused-imports, unused-variables, unused-assignments, dead-code, unused-mut, unreachable-code, unreachable-patterns, unused-must-use, unused-unsafe, path-statements, unused-attributes, unused-macros, unused-allocation, unused-doc-comments, unused-extern-crates, unused-features, unused-labels, unused-parens`

Note that `unused-mut` is among them.

**Comment by BartMassey** [comment]
Huh. TIL. Definitely violated the principle of least surprise for me, but I guess I see the logic in it. Thanks for the prompt response.
