### ISSUE TITLE
found two different crates with name `rustc_demangle` that are not distinguished by differing `-C metadata`

### ISSUE THREAD

**Issue by udoprog** [rust-lang/rust#61966]
When building latest master with `./x.py build -i`, I get the following error:

(Sorry about the image, but multiline copy+paste is currently broken in my dev build of windows terminal.)

![image](https://user-images.githubusercontent.com/111092/59786053-ab804180-92c6-11e9-9157-5689b1d54c9d.png)

Error pasted for search:

```
found two different crates with name `rustc_demangle` that are not distinguished by differing `-C metadata`. This will result in symbol conflicts between the two.
```

Note that I've also [applied this patch](https://github.com/rust-lang/rust/issues/61911#issuecomment-502932782) to solve the build breakage on msvc 2019.

Forcibly downgrading or specifying the version to to `=0.1.14` like this solves the issue, but I have no idea why it happens in the first place:

```diff
diff --git a/src/librustc_codegen_llvm/Cargo.toml b/src/librustc_codegen_llvm/Cargo.toml
index 4ae8303c76..134ac8625f 100644
--- a/src/librustc_codegen_llvm/Cargo.toml
+++ b/src/librustc_codegen_llvm/Cargo.toml
@@ -13,7 +13,7 @@ test = false
 [dependencies]
 cc = "1.0.1" # Used to locate MSVC
 num_cpus = "1.0"
-rustc-demangle = "0.1.15"
+rustc-demangle = "=0.1.14"
 rustc_llvm = { path = "../librustc_llvm" }
 memmap = "0.6"
 
diff --git a/src/librustc_codegen_ssa/Cargo.toml b/src/librustc_codegen_ssa/Cargo.toml
index a4cb517faf..66bdde6723 100644
--- a/src/librustc_codegen_ssa/Cargo.toml
+++ b/src/librustc_codegen_ssa/Cargo.toml
@@ -14,7 +14,7 @@ test = false
 bitflags = "1.0.4"
 cc = "1.0.1"
 num_cpus = "1.0"
-rustc-demangle = "0.1.15"
+rustc-demangle = "=0.1.14"
 memmap = "0.6"
 log = "0.4.5"
 libc = "0.2.44"
diff --git a/src/librustc_codegen_utils/Cargo.toml b/src/librustc_codegen_utils/Cargo.toml
index b218d18a06..4e32caf134 100644
--- a/src/librustc_codegen_utils/Cargo.toml
+++ b/src/librustc_codegen_utils/Cargo.toml
@@ -14,7 +14,7 @@ test = false
 flate2 = "1.0"
 log = "0.4"
 punycode = "0.4.0"
-rustc-demangle = "0.1.15"
+rustc-demangle = "=0.1.14"
 
 syntax = { path = "../libsyntax" }
 syntax_pos = { path = "../libsyntax_pos" }
```

**Comment by jonas-schievink** [comment]
Does it happen after `./x.py clean` as well?

**Comment by udoprog** [comment]
This was a clean checkout, but I'll give it a try ASAP.

**Comment by udoprog** [comment]
Also, I forgot to mention that I'm building with `-i`. Edited the original post.

**Comment by jonas-schievink** [comment]
Ah okay, I've sometimes seen something like this happen after `git pull`ing when there's already stuff built, but if it's a clean checkout that's not the same problem.

**Comment by udoprog** [comment]
Cleaning fixed it. Must've been something that happened during the initial build failure when I applied [the patch](https://github.com/rust-lang/rust/issues/61911#issuecomment-502932782) to fix the MSVC 2019 build failure.

Thanks!
