### ISSUE TITLE
Convert unsized slice to boxed slice

### ISSUE THREAD

**Issue by Coder-256** [rust-lang/rust#61980]
Currently, AFAIK there is no easy way to clone dynamically sized slices into boxed slices (correct me if I'm wrong). Here are the only two ways I've found, both of which are ugly and indirect:

```rust
let array: [usize; 4] = [1, 2, 3, 4];
let i = 2; // A variable set at runtime
let slice: &[usize] = &array[1..=i];

let boxed_array: Box<[usize]> = Box::new(array);

// error[E0277]: the size for values of type `[usize]` cannot be known at compilation time
// let boxed_slice: Box<[usize]> = Box::new(*slice);

let boxed_slice: Box<[usize]> = slice.to_vec().into_boxed_slice();
let boxed_slice2: Box<[usize]> = slice.iter().map(|x| *x).collect();
```

Converting into a `Vec` makes no sense since the slice is immutable and will not grow, and manually iterating over the slice and collecting into a box seems needlessly complex. Neither way makes sense, and it is unclear which one is better (or whether a better way exists).

Essentially I think the issue is that `Box::new` does not work with references, which is problematic since dynamically sized types (like `slice` in the example above) cannot be dereferenced. Is this intentional, an oversight, or just a current limitation of dynamically sized types? (or am I missing an easier way to do this?)

**Edit**: This is on the latest stable (1.35)

**Comment by clarfon** [comment]
This will be a thing once unsized locals work.

**Comment by ollie27** [comment]
There is [`impl<'_, T> From<&'_ [T]> for Box<[T]> where T: Copy`](https://doc.rust-lang.org/nightly/std/boxed/struct.Box.html#impl-From%3C%26%27_%20%5BT%5D%3E) so the following work:

```rust
let boxed_slice3: Box<[usize]> = slice.into();
let boxed_slice4 = Box::<[usize]>::from(slice);
```

**Comment by Coder-256** [comment]
@ollie27 Oops! 😳 I completely missed that. Thank you!
