### ISSUE TITLE
Installer: allow different installation directories

### ISSUE THREAD

**Issue by catastrop** [rust-lang/rust#61985]
can i use `/usr/local/bin` for rust tool-chain installation?

**Comment by jonas-schievink** [comment]
This should be filed in https://github.com/rust-lang/rust-installer or https://github.com/rust-lang/rustup.rs, depending on which installer you're referring to.

**Comment by catastrop** [comment]
please don't close this issue.

**Comment by jonas-schievink** [comment]
@catastrop This issue tracker is only for things relating to the Rust compiler and standard library. The installer and rustup have their own issue trackers, which I've linked above.
