### ISSUE TITLE
memory is freed before use

### ISSUE THREAD

**Issue by BaoshanPang** [rust-lang/rust#61993]
With the following code:
```rust
#![allow(stable_features)]
#![feature(process_exec, rustc_private)]

extern crate libc;
use std::ptr;
use std::ffi::{CString};
use libc::{c_char};

pub struct CStringArray {
    items: Vec<CString>,
    ptrs: Vec<*const c_char>
}

impl CStringArray {
    pub fn with_capacity(capacity: usize) -> Self {
        let mut result = CStringArray {
            items: Vec::with_capacity(capacity),
            ptrs: Vec::with_capacity(capacity+1)
        };
        result.ptrs.push(ptr::null());
        result
    }
    pub fn push(&mut self, item: CString) {
        let l = self.ptrs.len();
        self.ptrs[l-1] = item.as_ptr();
        self.ptrs.push(ptr::null());
        self.items.push(item);
    }
    #[inline(never)]
    pub fn as_ptr(&self) -> *const *const c_char {
        self.ptrs.as_ptr()
    }
}
fn main()
{   
    let mut result = CStringArray::with_capacity(10);
    result.push(CString::new("1=2").expect("error"));
    let opt = Some(result);
    //let x = opt.unwrap();
    //let y = x.as_ptr();
    let y = opt.unwrap().as_ptr();                                                                                                 
    unsafe { libc::puts(*y); }
}
```

I get a segment fault in running.
But if I change the code `let y = opt.unwrap().as_ptr();` to:
```rust
let x = opt.unwrap();
let y = x.as_ptr();
```
Then I can get expected output: `"1=2"`.

**Comment by DutchGhost** [comment]
`.unwrap()` takes ownership of the option, and returns an owned value back.

Then you *directly* pass that value (as a referencr) to `.as_ptr()`, and then the value's scope ends, so it is dropped.
So at the point `y` is created, it is a dangling pointer.

In the other case, `x` is still in scope, so `y` is a valid pointer.

**Comment by BaoshanPang** [comment]
From my program experience I don't feel there is any difference between the two cases.
Also shouldn't rustc report an error for the first case? I think one of rust's design goals is to get rid of these dangling pointer.

**Comment by BaoshanPang** [comment]
Let me ask the question in a different way:
How should I write the code so it works properly?

For code:
let x = opt.unwrap();
let y = x.as_ptr();

As opt is a option it could panic which is not what I want.

**Comment by DutchGhost** [comment]
There is a difference, and its scope of the variables.
It shouldn't emit an error, Rust only emits errors if you use the bultin reference types `&T` and `&mut T`.
Those have constraints that they may not be dangling, may not be 0, must be valid, and for `&mut T` an additional constraint that it must be unique. All these constraints are enforced by the compiler.

You use raw pointers, which is your responsibility to get right.

The reason raw pointers exist, is that `&T` and `&mutT` are too restrictive *sometimes*. (e.g, implementing a fast Vec would literally impossible using those).

Your first example also panics if the option is None.

I suggest reading the book: https://doc.rust-lang.org/book/,
and the nomicon: https://doc.rust-lang.org/nomicon

**Comment by nagisa** [comment]
Closing as invalid.
