### ISSUE TITLE
Tracking issue for member constraints in region inference

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#61997]
# Member constraints

https://github.com/rust-lang/rust/pull/61775 introduced "member constraints" as part of stabilizing async functions. These extend region inference to accommodate `impl Trait` return types that contain multiple unrelated lifetimes (e.g., `impl Trait<'a, 'b>` where neither `'a: 'b` nor `'b: 'a`).  We decided to introduce a feature gate for other cases until we have time to gain more experience.

# Learn more

The working of these constraints is described in [the rustc-guide](https://github.com/rust-lang/rustc-guide) -- as of this writing, however, [the PR](https://github.com/rust-lang/rustc-guide/pull/344) has not yet landed.

# Current status

- [x] Implemented (https://github.com/rust-lang/rust/pull/61775)
- [x] Described in rustc-guide (https://github.com/rust-lang/rustc-guide/pull/344)
- [ ] Stabilized

# Related issues

- Impl trait (#34511)
- Uncertain interaction with impl trait in bindings (https://github.com/rust-lang/rust/issues/61773)

**Comment by runiq** [comment]
Triage: The first two boxes can be checked and the rustc-guide PR has landed, so this:

> as of this writing, however, [the PR](https://github.com/rust-lang/rustc-guide/pull/344) has not yet landed.

is inaccurate now, which is a good thing. :)

**Comment by nikomatsakis** [comment]
I am beginning work towards stabilizing this.

@rustbot claim

**Comment by nikomatsakis** [comment]
This was completed in #84701
