### ISSUE TITLE
Bad error message using function scoped type alias

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#62005]
_Taken from https://github.com/rust-lang/rust/issues/45447#issuecomment-496068787:_

```
error[E0401]: can't use generic parameters from outer function
 --> src/lib.rs:3:14
  |
1 | fn foo<T>() {
  |        - type variable from outer function
2 |     //fn bar
  |          --- try adding a local generic parameter in this method instead
3 |     type U = T;
  |              ^ use of generic parameter from outer function
```
It appears to just blindly do a search for ```fn``` as it suggest annotating a comment if it find it in one.

---

Right now the code uses string munching to find the outer `fn` scope, but it should be tracking that information in a different way.

**Comment by compiler-errors** [comment]
This bad suggestion doesn't seem to be made anymore.
