### ISSUE TITLE
The prebuilt sccache is old

### ISSUE THREAD

**Issue by lzutao** [rust-lang/rust#62015]
I think the prebuilt sccache version that rustc CI using is old.
https://github.com/rust-lang/rust/blob/9d5b6efdf62dbcd7bdf8e78a5f69c1b6678fd155/.travis.yml#L269
https://github.com/rust-lang/rust/blob/9d5b6efdf62dbcd7bdf8e78a5f69c1b6678fd155/src/ci/docker/scripts/sccache.sh#L4

Should we build and upload the new one?

**Comment by Mark-Simulacrum** [comment]
I think we can update sccache but it's not really an urgent need for us -- the current version works fine. We can update it when it becomes necessary but for now there's no reason to. Thanks!

**Comment by lzutao** [comment]
@Mark-Simulacrum Apparently there was an issue: https://github.com/mozilla/sccache/issues/429

**Comment by Mark-Simulacrum** [comment]
We don't use sccache for Rust compilations so that shouldn't be a problem for us.
