### ISSUE TITLE
please provide a PDF version of the documentation

### ISSUE THREAD

**Issue by catastrop** [rust-lang/rust#62014]

**Comment by sfackler** [comment]
#60906

**Comment by catastrop** [comment]
when we will a pdf?

**Comment by catastrop** [comment]
Why this is so hard to make a pdf? I have created a similar issue but no one response. All of them are closed.

Is this really too hard. Or just ......

**Comment by catastrop** [comment]
@sfackler,
 i (we) want one or more multi hundred pages long pdf like Julia, Ocaml, Python, R, Haskell, ARM, Intel.
