### ISSUE TITLE
std::string::String trim does not trim \0

### ISSUE THREAD

**Issue by aknarts** [rust-lang/rust#62020]
As a result of working with openssl I get a Vec<u8> that is \0 padded, when I try to trim this string to remove the end of line included in the string there are no changes happening

Example code: 
```rust
let bytes = vec![97, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0];
println!("Bytes: {:?}", bytes);
let string = String::from_utf8(bytes).unwrap();
println!("String: \"{}\"", string);
println!("String bytes: {:?}", string.as_bytes());
let trimmed_string = string.trim();
println!("String: \"{}\"", trimmed_string);
println!("String bytes: {:?}", trimmed_string.as_bytes());
let properly_trimmed_string = string.trim_matches(|c: char| c.is_whitespace() || c=='\0');
println!("String: \"{}\"", properly_trimmed_string);
println!("String bytes: {:?}", properly_trimmed_string.as_bytes());
```

Result of this being:
```
Bytes: [97, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
String: "a
"
String bytes: [97, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
String: "a
"
String bytes: [97, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
String: "a"
String bytes: [97]
```

Expected functionality: At the very least the \n(char 10) should be trimmed as \0 is an end of string and should be ignored

This has a trivial workaround it just caught me off guard that the \0 is preserved during the conversion to string and that it is not ignoring \0 during the trim operation.

## Meta

Tested on stable and nightly

**Comment by oli-obk** [comment]
The `trim` documentation states that

> Returns a string slice with leading and trailing whitespace removed.

and

> 'Whitespace' is defined according to the terms of the Unicode Derived Core Property White_Space.

Since `\0` is not defined as whitespace, `trim` won't treat it as such

I think what you really want is not `trim`, but `truncate` at the first `\0`, because otherwise if you get `vec![97, 10, 0, 0, 0, 0, 42, 0, 0, 0, 0, 0]` you still have some `\0` in your string.

```rust
    if let Some(first) = bytes.iter().position(|&b| b == 0) {
        bytes.truncate(first);
    }
```

**Comment by jonas-schievink** [comment]
Yeah, `0x00` is not considered a special end-of-string marker in Rust, and also isn't whitespace, so it won't be removed or ignored. Closing since this is working as expected.
