### ISSUE TITLE
Deduplicate error messages

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#62022]
cc @RalfJung 	

https://github.com/rust-lang/rust/blob/3977cc2b3760d786b6722f1b7f705e57a63fb96e/src/librustc_mir/const_eval.rs#L557-L568

and 

https://github.com/rust-lang/rust/blob/3977cc2b3760d786b6722f1b7f705e57a63fb96e/src/librustc_mir/interpret/intern.rs#L293-L305

could be deduplicated by creating a function in `const_eval.rs` and calling it from both sites

This issue has been assigned to @chansuke via [this comment](https://github.com/rust-lang/rust/issues/62022#issuecomment-504761851).

**Comment by chansuke** [comment]
I'd like to work on this issue.

**Comment by oli-obk** [comment]
Great! It's all yours.

**Comment by saleemjaffer** [comment]
@chansuke Are you still working on this? If not I can pick it up :)

**Comment by wesleywiser** [comment]
This was closed in #62760
