### ISSUE TITLE
"Go to latest version" shown for up-to-date crates with yanked versions

### ISSUE THREAD

**Issue by d-e-s-o** [rust-lang/rust#62056]
Please check out the following screenshot:
![doc-goto-latest-version](https://user-images.githubusercontent.com/6610056/59965519-32e6d400-94c4-11e9-9cdf-d19faf7051b9.png)

It shows a link (in orange) that indicates that there is a more up-to-date version of the doc for this crate. At the time of this writing 0.1.27 is the most recent version of `futures`. In fact, if I click on it, I just end up where I already was.

Now, what actually seems to be happening is that we link to https://docs.rs/futures/0.2.3-docs-yank.4 which then just redirects us back, because, well, 0.2.3 has been yanked.

I believe it would be a better user experience if we did not indicate that there is a more recent version available to begin with in that case.

**Comment by jonas-schievink** [comment]
This is a docs.rs-specific issue and should be filed at https://github.com/rust-lang/docs.rs

**Comment by jonas-schievink** [comment]
Looks like this will be fixed by https://github.com/rust-lang/docs.rs/pull/322

**Comment by d-e-s-o** [comment]
Ah, thanks for the pointers!
