### ISSUE TITLE
Built-in derive macros `Send` and `Sync` exist

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rust#62050]
Their single purpose is improving diagnostics.
When those macros expand they always produce an error saying that `unsafe impl Send for Foo {}` should be written explicitly rather than derived.

So, when https://github.com/rust-lang/rust/pull/61877 is implemented you'll be able to write `use Send` or `use std::Send` without an error, but that's not an intent.

The macros should be removed, and `derive(Send)` should result in a resolution error, and the suggestion to write `unsafe impl Send for Foo {}` explicitly should be put on that resolution error.

**Comment by eddyb** [comment]
I would've half-expected e.g. `use core::Clone;` to never work, and instead the builtin macro be exposed from `core::clone::Clone` and `core::prelude::v1::Clone` (and both overlap with the `Clone` trait).
But it sounds like that's not going to be the case?

**Comment by petrochenkov** [comment]
@eddyb 
I've answered in https://github.com/rust-lang/rust/pull/62086#issuecomment-505095170.
