### ISSUE TITLE
Add a method for computing the absolute difference between unsigned integers

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#62111]
See discussion in https://github.com/rust-lang/rust/pull/62103#discussion_r296988078.

**Comment by ExpHP** [comment]
I suggest not calling it `abs_sub` due to the confusion created by the (terribly misnamed) [function on floats](https://doc.rust-lang.org/std/primitive.f64.html#method.abs_sub), whose tortured legacy continues to this day in `num_traits::Signed`.

**Comment by Centril** [comment]
@ExpHP `abs_diff` perhaps?

**Comment by leonardo-m** [comment]
abs_difference ?

**Comment by Centril** [comment]
What do you think about adding:
```rust
fn abs_difference<T: Sub<Output = T> + Ord>(x: T, y: T) -> T {
    if x < y {
        y - x
    } else {
        x - y
    }
}
```
instead of doing it on just the unsigned integer types?

**Comment by scalexm** [comment]
`distance` is a good name, I think, as it is the mathematical term for `abs(x-y)`.

I dislike @centril’s above generalization, as what it does is unrelated with the name of the function in most cases (the first thing that comes to mind is that something called an « absolute difference » should be a non-negative real number).

**Comment by HeroicKatora** [comment]
The term `distance` seems too generic from the standpoint of a mathematical motivation, it is also used in the context of very different metric spaces than the one induced by the L1-norm. I think 'absolute difference' hits the nail on the head and with the given prior art of abbreviations that would make `abs_diff` my clear favorite. Similar to `abs`, `checked_sub` and other functions it doesn't seem necessary to add it in another way than as a method.

**Comment by Toniman20** [comment]
Until that happens, I've found the easiest way to do this is:
`let x = max(y, z) - min(y, z);`

**Comment by orlp** [comment]
If no one has any objections I can make a pull request implementing the following functions:

```rust
fn abs_difference(slf: u8,  other: u8)  -> u8;
fn abs_difference(slf: u16, other: u16) -> u16;
fn abs_difference(slf: u32, other: u32) -> u32;
fn abs_difference(slf: u64, other: u64) -> u64;
fn abs_difference(slf: i8,  other: i8)  -> u8;
fn abs_difference(slf: i16, other: i16) -> u16;
fn abs_difference(slf: i32, other: i32) -> u32;
fn abs_difference(slf: i64, other: i64) -> u64;
```

where for unsigned types the implementation would be

```rust
fn abs_difference(slf: U, other: U)  -> U {
    if slf < other {
        other - slf
    } else {
        slf - other
    }
}
```

and for signed types

```rust
fn abs_difference(slf: I, other: I)  -> U {
    if slf < other {
        (other as U).wrapping_sub(slf as U)
    } else {
        (slf as U).wrapping_sub(other as U)
    }
}
```

**Comment by sffc** [comment]
Just sharing some experience from the wild: I have code of the form

```rust
// a and b are i16
if a > b {
    let c = a.abs_diff(b) as usize;
    // do something with c
}
```

where I check `if a > b` before I call `abs_diff`, because I need a different code path for that case versus the `a <= b` case. However, that check is repeated within the `abs_diff` impl, so I was wondering whether I should write out the `wrapping_sub` manually. But, it [appears that](https://play.rust-lang.org/?version=stable&mode=release&edition=2021&gist=fcf3927749c6d7ed938d38075f0dc3c4) when the compiler decides to inline `abs_diff`, it is smart enough to collapse the `if` statements into one. So I think using vanilla `abs_diff` is fine for my case. Thanks for adding it!
