### ISSUE TITLE
Explanation of E0207 is not what actually happens

### ISSUE THREAD

**Issue by yshui** [rust-lang/rust#62144]
Unconstrained lifetime parameters are actually allowed: 

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=e4deca509f64a6d600ae49904e966124

Unlike what's described here: https://github.com/rust-lang/rust/blob/d3e2cec29225a46298ec4ebf082f34ebd7cfeecf/src/librustc_typeck/error_codes.rs#L1941-L1950

For comparison, unconstrained type parameters do generate error:

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a4d2a865a8a311e0eb46f8ed8583c671

**Comment by ayushmishra2005** [comment]
@yshui I would like to address this. What should be error message for E0207?

**Comment by yshui** [comment]
@ayushmishra2005 Maybe just don't mention lifetime parameter?

**Comment by ayushmishra2005** [comment]
@yshui I think this has been fixed already. Can you please try again?

**Comment by yshui** [comment]
@ayushmishra2005 I don't think it has been: https://github.com/rust-lang/rust/blob/master/src/librustc_error_codes/error_codes/E0207.md

**Comment by ayushmishra2005** [comment]
@yshui Sorry My bad. I missed checking this file. Let me fix and raise PR.

**Comment by yshui** [comment]
@ayushmishra2005 Thanks :+1:
