### ISSUE TITLE
Deterministic int to float conversion

### ISSUE THREAD

**Issue by AljoschaMeyer** [rust-lang/rust#62175]
[Casting](https://doc.rust-lang.org/reference/expressions/operator-expr.html#semantics) from an integer type to a floating point type leaves the rounding behavior explicitly unspecified. Is there (or are there plans for) some way of deterministically turning an int into a float regardless of the target architecture? I really don't want `9007199254740993u64 as f64` to be converted to `9007199254740992.0` on one machine and `9007199254740994.0` on another (the example u64 is 2^53 + 1, the smallest natural number not precisely representable as an f64).

Options could be to either use the floating point rounding mode (interpreting the int as real number and then rounding it to the next representable float just like the semantics of all IEEE754 float operations), or supporting explicit rounding modes.

Apologies if such a feature already exists and I just didn't find it.

**Comment by jonas-schievink** [comment]
This might just be a bug in the reference. rustc probably just emits `uitofp`, which uses the default rounding mode. In fact, LLVM *only* supports the default rounding mode AFAIK (which is "round to nearest, ties to even").

**Comment by Centril** [comment]
Some discussion in https://github.com/rust-lang-nursery/reference/pull/607.

**Comment by estebank** [comment]
Further discussion in https://internals.rust-lang.org/t/tryfrom-for-f64/9793/29

**Comment by nikomatsakis** [comment]
Discussed in @rust-lang/lang meeting and @joshtriplett will try to follow up with this as well as rust-lang-nursery/reference#607.

**Comment by joshtriplett** [comment]
Is this something that would naturally vary between targets? Would specifying this break any existing or anticipated targets?

If the answer to both questions is "no", then I'm fine with specifying this. If we don't *currently* have consistent behavior on this point across all our existing targets, then I don't think the standard should precede the implementation here.

**Comment by jturner314** [comment]
This appears to be resolved, so this issue can be closed.

(The [reference now specifies the rounding mode](https://doc.rust-lang.org/stable/reference/expressions/operator-expr.html#type-cast-expressions). See rust-lang/reference#607.)
