### ISSUE TITLE
Conditional features should be made clear in generated docs

### ISSUE THREAD

**Issue by jdm** [rust-lang/rust#62188]
I spent a bunch of time looking at https://docs.rs/winapi/0.3.7/x86_64-pc-windows-msvc/winapi/um/fileapi/struct.BY_HANDLE_FILE_INFORMATION.html, seeing that there was a Default implementation for the type, and then hitting errors when trying to call BY_HANDLE_FILE_INFORMATION::default() in code that was using winapi 0.3.7. Eventually I clicked on https://docs.rs/winapi/0.3.7/x86_64-pc-windows-msvc/src/winapi/macros.rs.html#381 and realized that the implementation is only generated if the impl-default feature is enabled. I think it would be very helpful to expose information about conditional compilation in the generated documentation somehow in order to avoid problems like this in the future.

**Comment by silverweed** [comment]
+1
I would love to see all the features of a crate directly in its rustdoc.

**Comment by pickfire** [comment]
It would be nice for rustdoc to be able to show which feature enables a function beside it. @QuietMisdreavus Is this feasible? Just wondering if this issue relates to https://github.com/rust-lang/rust/issues/55938

**Comment by jyn514** [comment]
This is `doc(cfg())` I think: https://doc.rust-lang.org/rustdoc/unstable-features.html#documenting-platform-feature-specific-information. Can this be closed in favor of https://github.com/rust-lang/rust/issues/43781 ?

**Comment by retep998** [comment]
It's unfortunate that we have to add an extra attribute to document that instead of preserving the cfg information so rustdoc can report it directly.

**Comment by jyn514** [comment]
That's https://github.com/rust-lang/rust/issues/1998 and is much harder to fix.

**Comment by jyn514** [comment]
I'm going to close this since I don't think it has any requests that aren't covered by https://github.com/rust-lang/rust/issues/43781 or https://github.com/rust-lang/rust/issues/1998. I don't see a way to do this automatically without #1998.
