### ISSUE TITLE
std::define! macro, consistansy with std::include!

### ISSUE THREAD

**Issue by TomerZeitune** [rust-lang/rust#62190]
I would like to suggest adding a macro for #define. 
Rust already has a way to basically copy paste data into your file like #include , the `include! `macro.  

I know Rust does not have a dumb preprocessor like C/C++. But I think adding a `define!` macro will make the standard lib more consistent since Rust already has an `include!` macro.  

This macro will function just like #define in C.

Sometimes you just need these less than ideal primitive solutions. They aren't recommended but they should be there just like `include!`. Obviously `define! ` paired with `cfg!` is very powerful. The current solution is just not good enough. 

Rust's `define!` macro should only apply to the current scope.

One problem with #define in C, is that some people overuse it and create their own little unreadable language. Since in Rust you don't have to copy paste your own code everywhere and the `define!` macro only applies to the current scope this shouldn't be a problem in Rust. If you are unsure what something means it will probably be written inside the current scope or at the top of the file. No spaghetti.

This feature just like `include!` will not be recommended to use. The possibility should still be there. Rust is safe but not limiting.

**Comment by jonas-schievink** [comment]
A new feature like this would need to go through our [RFC process](https://github.com/rust-lang/rfcs), so closing in favor of that. You can also open a pre-RFC discussion on our internals forum at https://internals.rust-lang.org/
