### ISSUE TITLE
Number to/from string API

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#6220]
This is an umbrella issue following on from/working with #4819. The number <-> string conversion needs work and thought.

For example, the current to_str version allocates, and the current from_str doesn't work with the compiler optimisations very well: none of the (for example) exponent parsing code is removed when the function is specialised for `int`s.

Another important thing to consider is how non-primitive numbers (e.g. bigint/rational) are to be supported/helped (including not at all, other than the normal to/from_str traits)

**Comment by gsingh93** [comment]
Here's a library that's doing something like this: https://github.com/mahkoh/scan

**Comment by aturon** [comment]
@huonw Is there anything actionable here right now, or should this perhaps move to the RFCs repo?

**Comment by huonw** [comment]
I think this is basically solved/irrelevant, e.g. https://github.com/rust-lang/rust/pull/24612, https://github.com/rust-lang/rust/pull/30175 makes us handle floats right, and the new formatting infrastructure allows them to be done without allocations (i.e. we have more than just the old `to_str`). I think other aspects are better handled elsewhere (e.g. RFC repo, or an external crate).
