### ISSUE TITLE
Self-hosting rustc, compile to Wasm

### ISSUE THREAD

**Issue by lastmjs** [rust-lang/rust#62202]
It would be amazing if rustc could self-host and compile itself to Wasm. This would make it possible and very simple to use rustc in the browser, in Node.js, and anywhere else there is a Wasm VM. Hopefully the benefits of this are obvious, greatly simplifying the Rust toolchain and setup.

**Comment by memoryruins** [comment]
Some progress was made in https://github.com/rust-lang/miri/issues/722

**Comment by Mark-Simulacrum** [comment]
I don't think we need an issue to track this. If someone is interested, PRs are probably the best way to move this forward; discussion can happen on internals.
