### ISSUE TITLE
core doc-tests don't run

### ISSUE THREAD

**Issue by cuviper** [rust-lang/rust#62218]
I'm adding something to `Iterator`, and I wanted to try my examples, but I can't seem to get any doc tests to run for `core`.

```text
$ ./x.py test --doc libcore
[...]
Building rustdoc for stage1 (x86_64-unknown-linux-gnu)
    Finished release [optimized] target(s) in 0.07s
Testing core stage1 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
    Finished release [optimized] target(s) in 0.07s
   Doc-tests core

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

Same for `./x.py test --doc src/libcore`.

If I remove the `--doc` parameter, it does run unit tests, but still 0 doc tests.

I'm suspicious of this comment:

https://github.com/rust-lang/rust/blob/3849a5f83b82258fd76a3ff64933b81d7efeffa1/src/libcore/lib.rs#L50-L51

**Comment by cuviper** [comment]
I guess #62213 and #61199 are meant to address this?

**Comment by jonas-schievink** [comment]
> I guess #62213 and #61199 are meant to address this?

Correct

**Comment by QuietMisdreavus** [comment]
Now that https://github.com/rust-lang/rust/pull/61199 has landed, this should be fixed.

**Comment by ollie27** [comment]
Yeah, I've checked the recent build logs on azure and the core doctests are now being run.
