### ISSUE TITLE
Spurious RLS test failures

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#62225]
The RLS tests regularly fail on the tools builder even when the PR didn't touch anything RLS-related, and then the next PR landing switches the toolstate back to test-pass again. This is particularly bad during the week before the beta cutoff, where such a test failure leads to the PR being rejected.

I have seen this for weeks or even months, but to my surprise could not find an issue tracking this yet.
Cc @rust-lang/infra @Xanewok 

Some examples (with failing platform and test):
https://github.com/rust-lang/rust/pull/62209#issuecomment-506914620 (Linux, client_changing_workspace_lib_retains_diagnostics)
https://github.com/rust-lang/rust/pull/61199#issuecomment-506927309 (Linux, client_find_definitions)
https://github.com/rust-lang/rust/pull/61891#issuecomment-503326076 (Windows, client_completion_suggests_arguments_in_statements)
https://github.com/rust-lang/rust/pull/61932#issuecomment-503269750 (Linux, client_completion_suggests_arguments_in_statements)
https://github.com/rust-lang/rust/pull/61771#issuecomment-502950833 (Linux, client_completion_suggests_arguments_in_statements)
https://github.com/rust-lang/rust/pull/61889#issuecomment-502619562 (Windows, client_completion_suggests_arguments_in_statements)
https://github.com/rust-lang/rust/pull/60730#issuecomment-502447094 (Windows, client_completion_suggests_arguments_in_statements)
https://github.com/rust-lang/rust/pull/59752#issuecomment-502365726 (Linux, client_completion_suggests_arguments_in_statements)
https://github.com/rust-lang/rust/pull/61817#issuecomment-502228768 (Linux, client_find_definitions)
https://github.com/rust-lang/rust/pull/61789#issuecomment-501542743 (Linux, client_completion_suggests_arguments_in_statements)
https://github.com/rust-lang/rust/pull/61722#issuecomment-501353560 (Linux, client_completion_suggests_arguments_in_statements)
https://github.com/rust-lang/rust/pull/61758#issuecomment-501157704 (Linux, client_find_definitions)

And that's just for the last 17 days!

**Comment by kennytm** [comment]
The tracking issue is in rust-lang/rls#1265.

**Comment by Centril** [comment]
https://github.com/rust-lang/rust/pull/62209#issuecomment-506914620 also seems spurious.

**Comment by RalfJung** [comment]
Indeed, and it's an interesting one: `client_changing_workspace_lib_retains_diagnostics` failed, which is not in my list above.

So this bug has already caused two PRs to fail to land within the last 24h.

**Comment by Xanewok** [comment]
Merged RLS test fixes:
- 19 days ago landed https://github.com/rust-lang/rust/pull/61694 which should've fixed stomping tests due to shared `TARGET_DIR`, which specifically fixed `client_changing_workspace_lib_retains_diagnostics`
- 10 days ago landed https://github.com/rust-lang/rust/pull/61861 which ignored `client_completion_suggests_arguments_in_statements` for now

> #62209 (comment) (Linux, client_changing_workspace_lib_retains_diagnostics)

Failed because it's a stable backport, which doesn't yet include #61694

> client_completion_suggests_arguments_in_statements

Double-checked and every failure is prior to merging https://github.com/rust-lang/rust/pull/61861

...which means that the only spurious test failure in the past 10 days is https://github.com/rust-lang/rust/pull/61199#issuecomment-506927309 (the other two instances of `client_find_definitions` were 15 and 17 days ago) so this isn't nearly as severe now as it was before.

It looks like `client_find_definitions` remains to be the only spurious test now.

**Comment by RalfJung** [comment]
@Xanewok thanks for the update, good to hear that `client_completion_suggests_arguments_in_statements` was disabled for now.

Do you have any inkling as to what might cause these failures?

**Comment by Xanewok** [comment]
I have a hunch that we might have a race in Racer (heh) + RLS in `client_completion_suggests_arguments_in_statements` but what's interesting is that it seems to be the only test relying on Racer that's failing intermittently

About `client_find_definitions` I can't say much - IIRC it's only data from save-analysis, I didn't go into that yet. Might be something inside rls-analysis (lowering save-analysis into DB-like index) but again didn't check it thoroughly yet

**Comment by RalfJung** [comment]
FWIW, this seems to be still happening:
https://github.com/rust-lang/rust/pull/68778#issuecomment-581405243

**Comment by ehuss** [comment]
Closing as #100863 has removed RLS.
