### ISSUE TITLE
Inconsistent syntax between `unsafe async fn` and `async fn unsafe`

### ISSUE THREAD

**Issue by topecongiro** [rust-lang/rust#62232]
There is an inconsistency in the ordering of `async` and `unsafe` keywords that come before the fn signature. A plain function signature requires `async unsafe fn`, whereas a method signature requires `unsafe async fn`:

```rust
#![feature(async_await)]

struct A;

pub async unsafe fn thing() -> Result<(), ()> {
    unimplemented!()
}

impl A {
    pub unsafe async fn thing(&mut self) -> Result<(), ()> {
        unimplemented!()
    }
}

fn main() {}
```

- A related PR: https://github.com/rust-lang/rust/pull/61319.
- [A link to the playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=7f3d5ee4b0dbbeeff14e93e537e5fac5)
- An original issue in rustfmt: https://github.com/rust-lang/rustfmt/issues/3662

**Comment by Centril** [comment]
Ouch seems I forgot about implementations in https://github.com/rust-lang/rust/pull/61319.
I assumed it was the same code path... :(

Thanks for reporting this!

**Comment by Centril** [comment]
I have a fix in https://github.com/rust-lang/rust/pull/62241.
