### ISSUE TITLE
Exempt Miri from "no tools breakage the week before beta cutoff"?

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#62266]
Would it make sense to exempt Miri from the rule that tools must not regress the week before the beta is branched? Miri is anyway not distributed with the beta, it's a nightly-only tool. And this "no breakage" rule makes landing PRs during that timeframe very painful.

Cc @rust-lang/infra @oli-obk

**Comment by Centril** [comment]
This is also painful for the person doing rollup ops most of the time (me). =P

**Comment by pietroalbini** [comment]
Discussed this at the infra meeting, we're ok merging a patch for this.

@rustbot modify labels: -I-nominated

**Comment by RalfJung** [comment]
Oh, wow, okay the code is much more spaghetti than I thought.

The `beta_required` there is not for doing the check the week before the beta cutoff, it is for doing the check *when we are on the beta (or stable) branch*.

**Comment by kennytm** [comment]
Someday we should to rewrite all these 🍝 bash script using Python (or Rust) 🤷.

I think https://github.com/rust-lang/rust/pull/62759#discussion_r304720878 should have exempted miri.

**Comment by RalfJung** [comment]
> Someday we should to rewrite all these spaghetti bash script using Python (or Rust) 🤷.

Yeah, the usual problem with CI/infrastructure scripts. ;)

Not having things spread across 2 or 3 files (in 2 totally different directories!) would also help.

**Comment by RalfJung** [comment]
This was fixed by https://github.com/rust-lang/rust/pull/62759.
