### ISSUE TITLE
Unconditionally breaking `loop`s not allowed in constants.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#62272]
*Technically* a regression from 1.24 to 1.25, but I don't think anyone used this.
Example code which used to be allowed:
```rust
pub const FOO: () = loop { break; };
```

I'm pretty sure this changed with #47802, which added the `FalseUnwind` terminator to MIR, but didn't handle it in const-checking (which otherwise ignores cleanup blocks).

cc @matthewjasper @nikomatsakis

**Comment by Centril** [comment]
I think this is a technicality and that we can continue to let this be broken since no one said a peep about it since 1.25. The upside is that the syntactic surface of const eval is clearer.

**Comment by eddyb** [comment]
On the PR I explained why I think we should fix this *even if* we want to ban loops: https://github.com/rust-lang/rust/pull/62274#issuecomment-508714495
