### ISSUE TITLE
Box::into_pin is unstable but has #0 as the tracking issue

### ISSUE THREAD

**Issue by moxian** [rust-lang/rust#62288]
Please see https://doc.rust-lang.org/stable/std/boxed/struct.Box.html#method.into_pin :
![screenshot](https://cdn.discordapp.com/attachments/273541522815713281/595422844398075919/unknown.png)

**Comment by Centril** [comment]
Blame: https://github.com/rust-lang/rust/pull/57313.

cc @Nemo157
