### ISSUE TITLE
There's a bug when you multiply two Numbers

### ISSUE THREAD

**Issue by guoxingyun** [rust-lang/rust#62299]
use std::ops::Mul;
amount is 2224.0001_f64
my result===
amount_clone.mul(10000.0)=22240001.000000004----amount_clone.mul(10000.0).floor()=22240001

my code==
 println!("amount_clone.mul(10000.0)={}----amount_clone.mul(10000.0).floor()={}",amount_clone.mul(10000.0),amount_clone.mul(10000.0).floor());

**Comment by Lonami** [comment]
Works as expected, floating point numbers can't represent most real numbers precisely.
