### ISSUE TITLE
structural_match bug:  deep refs like `& &B` leak use of PartialEq

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#62307]
(Spawned off of investigation of #61188)

rust-lang/rfcs#1445 says that we're supposed to reject uses of consts with ADT's that don't implement `#[structural_match]` (i.e. ADT's that do not do `#[derive(PartialEq, Eq)]`.

Unfortunately, we did not quite finish the job. Consider the following code ([play](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=92cbbf1bf22e561eb05ee48a902a94eb)):

```rust
#[derive(Debug)]
struct B(i32);

// Overriding PartialEq to use this strange notion of equality exposes
// whether `match` is using structural-equality or method-dispatch
// under the hood, which is the antithesis of rust-lang/rfcs#1445
impl PartialEq for B {
    fn eq(&self, other: &B) -> bool { std::cmp::min(self.0, other.0) == 0 }
}

const ZER_B: & & B = & & B(0);
const ONE_B: & & B = & & B(1);

fn main() {
    if let ONE_B = ZER_B {
        println!("CLAIM Z: {:?} matches {:?}", ONE_B, ZER_B);
    }

    if let ONE_B = ONE_B {
        println!("CLAIM O: {:?} matches {:?}", ONE_B, ONE_B);
    }
}
```

This prints:

```text
CLAIM Z: B(1) matches B(0)
```

but I would expect to see something like the error you get if you use constants of type `&B` instead of `& &B`:

```text
error: to use a constant of type `B` in a pattern, `B` must be annotated with `#[derive(PartialEq, Eq)]`
  --> src/main.rs:15:12
   |
15 |     if let ONE_B = ZER_B {
   |            ^^^^^
```

**Comment by Centril** [comment]
[Me and @pnkfelix briefly discussed this on Discord.](https://discordapp.com/channels/442252698964721669/443151243398086667/595619060289634304)

**Comment by pnkfelix** [comment]
I have a patch for this in progress.

**Comment by pnkfelix** [comment]
(the change suggested in PR #62339 fixes this and has a regression test for it.)
