### ISSUE TITLE
libstd requires explicit version of rand crate

### ISSUE THREAD

**Issue by jasonbking** [rust-lang/rust#62308]
Most everything else in the rustc repo that needs the rand crate is specifying "0.6" for the version, while libstd has "0.6.1" in its Cargo.toml.  Unfortunately, this prevented rust from building on illumos systems without manually patching the rand crate (and is a blocker for rust-lang/rust#55553) in ~/.cargo/.... (without patching, anything using the rand functions will crash with an illegal system call error). The rand crate itself was fixed in Feb, but the libstd dependency on 0.6.1 prevents any fixed version from being used.

It seems likely there must have been a reason to not rely on semver like all the other components, but it's not obvious what it was/if it's still relevant, so it's not clear if merely updating libstd's Cargo.toml to "0.6" is sufficient, or if something more is required.

**Comment by nagisa** [comment]
Feel free to send in a PR which changes the version from `0.6.1` to `^0.6.1`.

**Comment by mati865** [comment]
`0.6.1` and `^0.6.1` [are exactly the same](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#specifying-dependencies).
Explicit version would be `=0.6.1`

What you need to to is upgrading `rand` in `Cargo.lock`.

**Comment by Mark-Simulacrum** [comment]
I'm closing this as it's either outdated by this point or should likely be resolved with a concrete implementation via PR, we're generally happy to bump dependency versions as needed for work.
