### ISSUE TITLE
1.36 changes the `UnwindSafe` impl precondition for HashMap

### ISSUE THREAD

**Issue by CAD97** [rust-lang/rust#62301]
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=0e5a528fc978a90aa15bbf01f68dd1bf

```rust
assert_unwind_safe::<HashMap<(), UnsafeCell<()>>>();
```

Successfully compiles on stable 1.35, fails on beta/pre 1.36.

**Comment by CAD97** [comment]
First reported to FireFox ESR and shared on irlo here: https://internals.rust-lang.org/t/rust-1-36-0-pre-release-testing/10490/2?u=cad97

**Comment by SimonSapin** [comment]
https://github.com/rust-lang/rust/blob/ef064d2f66bf5851e1da1a016627ff1395f6c9ad/src/libstd/panic.rs#L209-L212

The `UnwindSafe` impl for `Unique<T>`  requires `T: UnwindSafe`, but the one for `NonZero<T>` requires `T: RefUnwindSafe`.

**Comment by SimonSapin** [comment]
https://github.com/rust-lang/rust/pull/62304 is a possible fix.
