### ISSUE TITLE
const fns have no documentation

### ISSUE THREAD

**Issue by MortenLohne** [rust-lang/rust#62348]
`const` functions seems to be an entirely undocumented language feature. As far as I can see, it's not mentioned anywhere in book or the reference. Judging by the release notes, they've been in the language since before 1.33, so it seems to just have been forgotten?

**Comment by Centril** [comment]
> or the reference.

https://doc.rust-lang.org/nightly/reference/items/functions.html#const-functions

**Comment by MortenLohne** [comment]
_Thank you_, I thought I would never find any information.
