### ISSUE TITLE
Add valid examples to `std::ptr::{read,write}_unaligned`

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#62357]
With https://github.com/rust-lang/rust/pull/62323 the only example (that had UB and was thus invalid) in `std::ptr::read_unaligned` and `std::ptr::write_unaligned` is removed.

We should add a valid example of using the aforementioned functions.

cc @rust-lang/wg-unsafe-code-guidelines 

This issue has been assigned to @Freyskeyd via [this comment](https://github.com/rust-lang/rust/issues/62357#issuecomment-509231782).

**Comment by RalfJung** [comment]
Slices are one context in which one could conceivably create an unaligned raw pointer:
```rust
fn read_usize(x: &[u8]) -> usize {
  assert!(x.len() >= mem::size_of::<usize>());
  let ptr = x.as_ptr() as *const usize;
  unsafe { ptr.read_unaligned() }
}
```
Thanks to @Shnatsel on Zulip.

**Comment by Freyskeyd** [comment]
Hello!

I would like to work on this one :)

**Comment by RalfJung** [comment]
Fixed by https://github.com/rust-lang/rust/pull/62493.
