### ISSUE TITLE
Tracking issue for Box::into_pin (feature `box_into_pin`)

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/rust#62370]
This is a tracking issue for `Box::into_pin` implemented in https://github.com/rust-lang/rust/pull/57313

```rust
impl<T: ?Sized> Box<T> {
    pub fn into_pin(boxed: Box<T>) -> Pin<Box<T>>;
}
```

**Comment by Nemo157** [comment]
> I don't think this is really a useful feature to specialize in this way. Can't you just use the hyper fish operator to disambiguate?
> &mdash; @czipperz (https://github.com/rust-lang/rust/pull/57313#issuecomment-508542568)

There are currently 2 _unambiguous_ stable ways to convert a `Box<T>` into a `Pin<Box<T>>` without additional inference constraints

```rust
let foo: Box<T> = ...;
let bar = <Pin<Box<_>>>::from(foo);
let bar: Pin<Box<_>> = foo.into();
```

Also, at the moment `let bar = Pin::from(foo);` works because there is only one trait implementation that can satisfy that call, but because `Pin` and `Box` are `#[fundamental]` it's possible for an external library to add an additional `From` implementation that makes that ambiguous ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=c8a8b62b3d3782f826c3e63d4ce181ec)).

In a lot of cases where you need to convert into a `Pin<Box<_>>` you're likely to have inference available to guide the `.into()` call as well, but not always.

**Comment by czipperz** [comment]
Well there's also `Box::pin(foo)` right?

**Comment by czipperz** [comment]
Mmh but that takes a `T` and wraps it into `Pin<Box<T>>`.  I think with that context `Box::into_pin` makes a lot of sense.

**Comment by joshtriplett** [comment]
Shall we stabilize `Box::into_pin`?

@rfcbot merge

**Comment by BurntSushi** [comment]
> Also, at the moment `let bar = Pin::from(foo);` works because there is only one trait implementation that can satisfy that call, but because `Pin` and `Box` are `#[fundamental]` it's possible for an external library to add an additional `From` implementation that makes that ambiguous ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=c8a8b62b3d3782f826c3e63d4ce181ec)).

It seems like this is something that should be mentioned in the docs of `into_pin`, specifically as something that differentiates it from `Pin::from`.
