### ISSUE TITLE
Get rid of uses of mem::uninitialized

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#62397]
https://github.com/rust-lang/rust/commit/007d87f1719e2fcf2ff36aef8b6dc866fa276386 added a bunch of `allow(deprecated)` because there are still a few places where we use `mem::uninitialized`. These should all be fixed, to remove the `allow` (and hopefully prevent other deprecated methods from being used there).

* [x] SGX
* [x] libterm
* [x] librustc_codegen_llvm
* [x] std::io::util
* [ ] CloudAbi layout tests (`src/libstd/sys/cloudabi/abi/cloudabi.rs`)
* [ ] rustc tests

Cc @EdSchouten  for CloudAbi, @jethrogb for SGX.

**Comment by JulianGindi** [comment]
Going to take a stab at addressing this issue

**Comment by JulianGindi** [comment]
Actually looks like some of this was already handled.

**Comment by RalfJung** [comment]
The SGX and libterm and codegen ones have been handled. CloudAbi and `std::io::util` remain open as far as I can see.

**Comment by JulianGindi** [comment]
> CloudAbi and `std::io::util` remain open as far as I can see.

Ah, gotcha. Will take a crack at it. Thanks!

**Comment by jethrogb** [comment]
And what about all the tests?

**Comment by JulianGindi** [comment]
> And what about all the tests?

Good question. I'm a bit less confident with figuring out how to handle those tests. I removed `mem::uninitialized` from CloudAbi and std::io::util and tests still pass. I can submit a PR with just that change, but I want to remove it from the tests as well if that's appropriate. 

My progress can be [viewed here](https://github.com/rust-lang/rust/compare/master...JulianGindi:replace-mem-uninitialized) for reference/guidance.

**Comment by RalfJung** [comment]
I'm less worried about the tests TBH. The affected ones fairly deliberately cause UB. They can probably be fixed by replacing it with `MaybeUninit::uninit().assume_init()` and adding a comment that we cause UB here but for some reason we still want to test this.

@JulianGindi IMO it anyway makes sense to separate the test changes from the others as they are unrelated, so why don't you make a PR with what you got?

**Comment by JulianGindi** [comment]
Sounds good @RalfJung. I have that test code as well for later if we want to move forwards with it. I have submitted the PR and it's linked above.

**Comment by RalfJung** [comment]
The remaining open boxes in this issue are up for grabs again. To properly fix this, you should have some experience with unsafe code.

Maybe I should mark this "hard" instead of "medium"? I don't know how to figure out which label is more appropriate. It's not a lot of work to do this, but it requires rewriting some subtle unsafe code that deals with uninitialized memory.

**Comment by RalfJung** [comment]
@ nathanwhit please make you to mention in an issue when you are (partially) addressing it. Now we both did the same work but in different ways.

**Comment by RalfJung** [comment]
@nathanwhit please make you to mention in an issue when you are (partially) addressing it. Now we both did the same work but in different ways.

**Comment by nathanwhit** [comment]
I'm sorry, that's totally my mistake. These are my first few contributions, so I'm still in the process of learning the ropes. I'll make sure to do so in the future.

**Comment by RalfJung** [comment]
No hard feelings, just letting you know. :)

**Comment by Diggsey** [comment]
Seems like under the new UB guidelines, those tests should be testing unspecified rather than uninitialised values. (I believe they're being called "frozen" values?)

**Comment by nathanwhit** [comment]
I've done work on addressing this for CloudAbi (excluding the tests), the PR with my work so far is #62738, feedback is much appreciated!

**Comment by Mark-Simulacrum** [comment]
Remaining (removable) cases in our test cases are removed in https://github.com/rust-lang/rust/pull/67507. I also filed https://github.com/NuxiNL/cloudabi/issues/18 upstream to suggest fixing the CloudABI piece; I don't think we should keep this open once #67507 lands as the CloudABI issue *must* be fixed upstream (the file says "don't edit").

**Comment by m-ou-se** [comment]
I've updated [the upstream `cloudabi.rs`](https://github.com/NuxiNL/cloudabi/blob/master/rust/cloudabi.rs) to fix this problem, and also include the other changes that were made in the `rust` repository (`#[non_exhaustive]`, and using `*mut` instead of `&mut` for output parameters).
