### ISSUE TITLE
future doc in doc.rs still use await!

### ISSUE THREAD

**Issue by aohan237** [rust-lang/rust#62394]
it supposed to be .await?

https://doc.rust-lang.org/std/future/trait.Future.html

> The core method of future, poll, attempts to resolve the future into a final value. This method does not block if the value is not ready. Instead, the current task is scheduled to be woken up when it's possible to make further progress by polling again. The context passed to the poll method can provide a Waker, which is a handle for waking up the current task.

> When using a future, you generally won't call poll directly, but instead **await!** the value.

**Comment by sfackler** [comment]
This is already fixed on nightly: https://doc.rust-lang.org/nightly/std/future/trait.Future.html

**Comment by aohan237** [comment]
ok. i thought new release come out, so the doc will be upgraded too.

any way, you know that will be good
