### ISSUE TITLE
Confusing diagnostic for lifetime mismatch

### ISSUE THREAD

**Issue by smarnach** [rust-lang/rust#62400]
This [came up on StackOverflow](https://stackoverflow.com/q/56897524) today. In reduced form, this function
```rust
fn foo<T>(x: &mut &mut T) {
    *x = *x;
}
```
results in this error message
```
error[E0623]: lifetime mismatch
 --> src/lib.rs:2:10
  |
1 | fn foo<T>(x: &mut &mut T) {
  |              -----------
  |              |
  |              these two types are declared with different lifetimes...
2 |     *x = *x;
  |          ^^ ...but data from `x` flows into `x` here
```
([Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=b0a4d9db4b8d07542f9fd6e7e72049c6))

The error message tags a _single_ type and claims it is two types with different lifetimes, which is not really helpful in understanding the error.

**Comment by pnkfelix** [comment]
This is what you get if you go to full blown NLL (not migration mode) ([play](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=90e4ffb5cfe4c67633501a834689a275)):

```rust
#![feature(nll)]

fn foo<T>(x: &mut &mut T) {
    *x = *x;
}

fn main() { }
```

yields:

```
error: lifetime may not live long enough
 --> src/main.rs:4:5
  |
3 | fn foo<T>(x: &mut &mut T) {
  |              -    - let's call the lifetime of this reference `'2`
  |              |
  |              let's call the lifetime of this reference `'1`
4 |     *x = *x;
  |     ^^^^^^^ assignment requires that `'1` must outlive `'2`
```

**Comment by pnkfelix** [comment]
tagged as NLL-fixed-by-NLL based on the improvement to the diagnostic itself.

**Comment by smarnach** [comment]
@pnkfelix My understanding has been that the assignment triggers an implicit reborrow, so it is equivalent to `*x= &mut **x;`, and the reborrow does not live long enough. If this understanding is correct, the new error message does not fully address this issue, but I may very well be wrong here.

**Comment by pnkfelix** [comment]
@smarnach The reborrow doesn't have to be short-lived. The lifetime-inference system might well give it a sufficiently long lifetime to ensure it remains valid at its destination.

I am still puzzling over this example and some variants thereof.

Namely, this one (which we currently accept) scared me at first:

```rust
fn foo<'a>(x: &'a mut [&'a mut &'static str]) { x[0] = x[1]; }
```

since that ends up with an array that, at least in terms of its memory, holds two `&mut _` references to the same thing... but this may be okay, since it should also ensure that array is no longer usable by anyone, including `foo` itself and `foo's` caller.

**Comment by smarnach** [comment]
@pnkfelix I was mainly replying to your (striked out) comment about moving out of the outer reference – I don't think the assignment results in a move, but rather in a reborrow.

If we name the lifetimes `&'a mut &'b mut T`, the reborrow can only live for the intersection of `'a` and `'b`, so the NLL error message is probably correct, but if even you find it puzzling there may still be room for improvement. Maybe the error message could explain the implicit reborrow, and give a name to the lifetime of the reborrow?

**Comment by steveklabnik** [comment]
Triage: this message is still the same, and I do think it's a bit confusing, personally.
