### ISSUE TITLE
Group all ABI tests.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#62401]
There are a bunch of run-pass tests that should be in `run-pass/abi` (or some other directory if anyone has a better suggestion), and many of them are mentioned here: https://github.com/rust-lang/rust/blob/baab1914ec9a9742776a8147780947b48fddf54d/src/test/run-pass/abi-sysv64-arg-passing.rs#L7-L23
You can also look for tests that mention `rust_test_helpers` - most of the functions from that C library are used to test ABIs.

cc @nagisa @rkruppe

This issue has been assigned to @kper via [this comment](https://github.com/rust-lang/rust/issues/62401#issuecomment-509506173).

**Comment by kper** [comment]
Is there a way to test if its still working?

**Comment by eddyb** [comment]
@kper look at the number of tests reported by `./x.py test --stage 1 src/test/run-pass`.
They should be identical before and after the move.

**Comment by kper** [comment]
@eddyb ok, the results look good. Can you check?
