### ISSUE TITLE
Random lines of code(?) printed into azure logs

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#62415]
Some sample logs:
 * https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/2418/logs/166 has:
```
2019-07-05T01:49:34.1238250Z r? @matthewjasper
2019-07-05T01:49:34.1238312Z ```rust
```
```
2019-07-05T01:49:34.1237351Z     match DropTemps($cond) {
```
```
2019-07-05T01:49:34.1233848Z Here we remove `hir::ExprKind::While`.
```

cc @rylev @johnterickson @ethomson

**Comment by Mark-Simulacrum** [comment]
All of these have `r? @<gh username>` in the environment variable section. There are hundreds more, at least. There's probably other patterns but I just haven't found them because it's somewhat painful to look (they are semi-random strings, after all).

https://dev.azure.com/rust-lang/rust/_build/results?buildId=1367&view=logs&jobId=0e47216c-a892-589a-a5b3-5fa9021bc5b1
https://dev.azure.com/rust-lang/rust/_build/results?buildId=2152&view=logs&jobId=31dd0613-6798-5f1e-0745-49f35ecf5123
https://dev.azure.com/rust-lang/rust/_build/results?buildId=2348&view=logs&jobId=2ed0550f-e734-5ebf-52c6-1bfc19f5811c
https://dev.azure.com/rust-lang/rust/_build/results?buildId=1813&view=logs&jobId=c8d040bd-2103-5051-ff1e-9fedef6965c4
https://dev.azure.com/rust-lang/rust/_build/results?buildId=1139&view=logs&jobId=6485e793-6f9a-5940-bdfb-daa9459b44ef
https://dev.azure.com/rust-lang/rust/_build/results?buildId=2405&view=logs&jobId=c0f22b62-72a5-5af6-d7bd-82fa4423f374
https://dev.azure.com/rust-lang/rust/_build/results?buildId=498&view=logs&jobId=f63b3ca7-cbb3-5440-2716-816dad6162da
https://dev.azure.com/rust-lang/rust/_build/results?buildId=2265&view=logs&jobId=7e9c1385-f003-5191-6e56-de8b58facc56
https://dev.azure.com/rust-lang/rust/_build/results?buildId=1249&view=logs&jobId=47b783a2-4c27-5eda-9fea-98cf506c800a
https://dev.azure.com/rust-lang/rust/_build/results?buildId=1249&view=logs&jobId=1e2ea934-bbbb-565e-7dc4-298083bc67af

**Comment by ethomson** [comment]
A quick glance at the first output suggests to me that it's not random code, nor is it in the logs (at least not due to log pollution).  That's the commit message and it's actually in the _environment_.

We set `BUILD_SOURCEVERSIONMESSAGE` to the source version's commit message.  It looks like we're not splitting newlines correctly.  If this makes sense given what you're seeing, I'll make sure that we address it.

**Comment by Mark-Simulacrum** [comment]
I think that makes some sense -- but e.g. in https://dev.azure.com/rust-lang/rust/_build/results?buildId=1249&view=logs&jobId=1e2ea934-bbbb-565e-7dc4-298083bc67af

I have the following which looks like the `r?` line is just.. separate from any relevant environment variable. Unless I misunderstood, I would expect any commit message lines to be after `BUILD_SOURCEVERSION_MESSAGE` -- not scattered throughout. But maybe by "splitting newlines" you mean something different than I do :)

```
MSDEPLOY_HTTP_USER_AGENT=VSTS_d439fc94-e01f-4249-b63e-d8392bc0247c_build_10_0
PATH=/usr/local/cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
PIPELINE_WORKSPACE=/home/vsts/work/1
PWD=/home/vsts/work/1/s
r? @oli-obk
RUSTUP_HOME=/usr/local/rustup
SCCACHE_BUCKET=rust-lang-ci-evalazure-sccache
SHLVL=1
submodules: Update clippy from 149a988 to 5a11ed7b
SYSTEM_ARTIFACTSDIRECTORY=/home/vsts/work/1/a
SYSTEM=build
```

**Comment by johnterickson** [comment]
Good news - I know what the issue is!
Bad news - I am pretty sure I wrote it 😬

```
printenv | sort
```
This will take the out of printenv as a list of lines and then sort the lines.  When an environment variable has multiple lines, then ` | sort` will tear those lines from each each and sort them alongside the names of variables.

I think I had reported this as "bug" to @willsmythe only for him to explain the above to me :)

**Comment by Mark-Simulacrum** [comment]
Sounds good. I'm downgrading this to P-low on our end as it doesn't seem like all that bad for us. Thanks for investigating so quickly!

**Comment by willsmythe** [comment]
One way you could fix ...

```
printenv -0 | sort -z | tr '\0' '\n'
```

**Comment by Mark-Simulacrum** [comment]
I'm not sure this is still relevant in current CI and don't think it merits tracking or changes even if it is. Closing.
