### ISSUE TITLE
Cleanup: Consistently use `Param` instead of `Arg`

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#62426]
For example, ideally [`fn visit_arg`](https://doc.rust-lang.org/nightly/nightly-rustc/syntax/visit/trait.Visitor.html#method.visit_arm) would be named `fn visit_param` since this is about formal parameters (in function signatures and from the POV inside the function body) instead of actual arguments (the values you pass to functions).

The type [`Arg`](https://doc.rust-lang.org/nightly/nightly-rustc/syntax/ast/struct.Arg.html) should probably be named `Param`.

(This is not an exhaustive list, there are other places "arg" is used not mentioned here that should probably use "param" instead)

cc @petrochenkov @c410-f3r
cc https://github.com/rust-lang/rust/pull/61856

This issue has been assigned to @kper via [this comment](https://github.com/rust-lang/rust/issues/62426#issuecomment-509170324).

**Comment by kper** [comment]
Can I work on this?

**Comment by csmoe** [comment]
@kper you can assign to yourself with `@rustbot claim`.

**Comment by csmoe** [comment]
@kper it's already "assign"ed to you.

**Comment by Freyskeyd** [comment]
Hello,

I'm searching for a simple issue to start with, after reading this I think I can help but I've some question.

How can I define which part must be replace ?

thank's

**Comment by kper** [comment]
I tried to begin with the renaming and I have been wondering how aggressive I should rename? It is kind of hard for me to see when I have real arguments or parameters. My first try (Commit 6c9051c as referenced above) led to extremely a lot of change. Can I have some feedback?

In addition, I noticed that the issue has a "blocked" label. Should I therefore wait until #61856 is finished?

**Comment by Centril** [comment]
> Should I therefore wait until #61856 is finished?

I think that's a good idea.

> It is kind of hard for me to see when I have real arguments or parameters. My first try (Commit [6c9051c](https://github.com/rust-lang/rust/commit/6c9051ceaff4226944253f83855954b0e9b41e67) as referenced above) led to extremely a lot of change. Can I have some feedback?

This looks largely right, tho I didn't look at `parser.rs`. In general, if something refers to things a function accepts rather than the expressions (or types when it's about type args) passed into them, then they are parameters and not arguments.

Please also avoid running `rustfmt` on the code as that will make everyone else have to rebase and it makes it harder to review the actual changes.

**Comment by c410-f3r** [comment]
#61856 has been merged

**Comment by kper** [comment]
@Centril can you look over my commit? :)

**Comment by Centril** [comment]
@kper Can you file it as a PR? Easier to review that way.

**Comment by kper** [comment]
@Centril sure :)
