### ISSUE TITLE
typo in `core::arch::x86_64::_mm_add_epi64` formatting

### ISSUE THREAD

**Issue by Lokathor** [rust-lang/rust#62454]
<https://doc.rust-lang.org/core/arch/x86_64/fn._mm_add_epi64.html>

The `b` var is written with an opening double quote instead of an opening backtick.

**Comment by BO41** [comment]
issue is fixed and should be closed :wink: 

@JohnTitor it is nice that you fix those issue. It would be great if you could include a `fixes #62454` in your PR :smiley:

**Comment by Lokathor** [comment]
Got it.
