### ISSUE TITLE
Increase the arity of tuple with automatic implementation of std traits

### ISSUE THREAD

**Issue by fredpointzero** [rust-lang/rust#62466]
Currently up to 12-ary tuple have common traits implemented (PartialEq, Eq, ...).

(see https://github.com/rust-lang/rust/blob/master/src/libcore/tuple.rs)

In my case, I need to have more than that (I currently use 32, but it may be more).

In the end, I expect the tuple to have those traits implemented, and if not, having a way to implements them.

So, it can be either: 
 - Increasing the maximum arity of tuples (but the issue may comme back later)
 - Be able to explicitly impl them (currently this is forbidden to do a blanket implementation as those traits belongs to std)
 - Have a way to set the arity of supported tuples when compiling.

Do you think this is something possible?

Thanks!

**Comment by scottmcm** [comment]
I suspect that this will be like the requests to raise the limits on arrays: the answer will be that they won't be raised until a language feature is added to allow the limit to be removed entirely.

**Comment by Dylan-DPC** [comment]
Closing this, it would be better to have the language feature over continuously changing it to arbitrary values
