### ISSUE TITLE
Automatically add crate to workspace with `cargo new`

### ISSUE THREAD

**Issue by czipperz** [rust-lang/rust#62471]
I think it would make sense if there was a flag to `cargo new` such as `--workspace` that would add the new crate to the workspace.  There is already workspace detection:

```
~/rust-comp master $ cargo new --lib abc
warning: compiling this new crate may not work due to invalid workspace configuration

current package believes it's in a workspace when it's not:
current:   /home/czipperz/rust-comp/abc/Cargo.toml
workspace: /home/czipperz/rust-comp/Cargo.toml

this may be fixable by adding `abc` to the `workspace.members` array of the manifest located at: /home/czipperz/rust-comp/Cargo.toml
Alternatively, to keep it out of the workspace, add the package to the `workspace.exclude` array, or add an empty `[workspace]` table to the package's manifest.
Created library `abc` package
```

So it probably wouldn't be too hard to have a way to automate the step of

>adding `abc` to the `workspace.members` array

**Comment by Centril** [comment]
This should be filed over at https://github.com/rust-lang/cargo/issues/.

**Comment by czipperz** [comment]
Brilliant it's already in motion over there https://github.com/rust-lang/cargo/issues/6378
