### ISSUE TITLE
lifetime-parametric GATs cause ICEs (with feature(generic_associated_types))

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#62521]
Many people playing with `#[feature(generic_associated_types)]` have noticed that they break very easily when you attempt to use a lifetime formal parameter.

Examples follow

## ICE: Region parameter out of range

#62326 ([play](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=1f746eb41c0bf5be7e9257e988955aed)):

```rust
#![feature(generic_associated_types)]
trait Iterator {
    type Item<'a>: 'a;
}
```

#58694 ([play](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=b68503853a25ca17e4977a8bb9a98d17))

```rust
#![feature(generic_associated_types)]
trait Foo {
  type PublicKey<'a> : From<&'a [u8]>;     
}
```
#49362 ([play](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=3327573fdbd07347d0d9af9e46060e5d))

```rust
#![feature(generic_associated_types)]

trait Trait {
    type Associated<'a>;
}

impl Trait for () {
    type Associated<'a> = &'a ();
}
```

## ICE: cannot convert `ReEarlyBound(0, 'b)` to a region vid

#60654 ([play](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=953cda8237dac3b12d848576be095e6a))

```rust
#![feature(generic_associated_types)]
struct Foo;

impl Iterator for Foo {
    type Item<'b> = &'b Foo;

    fn next(&mut self) -> Option<Self::Item> {
        None
    }
}
```

----

This obviously blocks stabilization of GATs (#44265).

**Comment by pnkfelix** [comment]
(also copying labels from the issues in the description)

**Comment by estebank** [comment]
CC https://github.com/rust-lang/rust/issues/56445, seemingly same underlying issue, has longer thread.

**Comment by hellow554** [comment]
Not online an ICE will occur if you put `Self::Item` in the return type, but also as a parameter:

```rust
#![feature(generic_associated_types)]

trait Foo {
    type Bar<'a>;
    fn baz<'a>(_: Self::Bar) ;
}

impl Foo for () {
    type Bar<'a> = &'a ();
    fn baz<'a>(_: Self::Bar) {}
}

fn main () {}
```
