### ISSUE TITLE
diagnostic for naive recursive async functions is really unfriendly

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#62539]
The following Rust source ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=137001df1ae7afa5b2b4b0fe649b8ed6)):

```rust
#![feature(async_await)]

async fn foo(n: usize) {
    if n > 0 {
        foo(n - 1).await;
    }
}

fn main() {
}
```

gives the error:

```
error[E0720]: opaque type expands to a recursive type
 --> src/main.rs:3:24
  |
3 | async fn foo(n: usize) {
  |                        ^ expands to self-referential type
  |
  = note: expanded type is `std::future::GenFuture<[static generator@src/main.rs:3:24: 7:2 n:usize {usize, bool, impl std::future::Future, ()}]>`
```

We could be a lot clearer.

**Comment by nikomatsakis** [comment]
I think an error like

```
error[E0720]: recursion is not supported in async fn
 --> src/main.rs:3:24
  |
3 | async fn foo(n: usize) {
  |                        ^ async fn cannot invoke themselves directly
  |
  = note: to create a recursive async fn, you must rewrite to return a boxed future
  = for more information, see https://rust-lang.github.io/async-book/index.html
```

**Comment by nikomatsakis** [comment]
I suspect we can intercept that "opaque type" error and check on the [`origin`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc/infer/opaque_types/struct.OpaqueTypeDecl.html#structfield.origin) field of the opaque type, looking for [`AsyncFn`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc/hir/enum.ExistTyOrigin.html#variant.AsyncFn)

**Comment by withoutboats** [comment]
In addition to adding specific output for async fn, it would also be good to stop outputing "self-referential type" in any context, and instead use "recursive type" as this error message does at one point. Nowadays, "self-referential" is used very often to mean they have references pointing into themselves, rather than how it is being used here, and someone who googles it will get very unhelpful results.

**Comment by nikomatsakis** [comment]
It looks like the error is issued here:

https://github.com/rust-lang/rust/blob/b8ec4c4d11ede0fba333a0474ed473dbe82aacf1/src/librustc_typeck/check/mod.rs#L1317-L1331

That function is invoked from here:

https://github.com/rust-lang/rust/blob/b8ec4c4d11ede0fba333a0474ed473dbe82aacf1/src/librustc_typeck/check/mod.rs#L1379-L1384

In that caller's location, we can access the argument to the [`Existential`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc/hir/enum.ItemKind.html#variant.Existential) variant, which is a [`ExistTy`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc/hir/struct.ExistTy.html) struct. That struct has a field [`origin`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc/hir/struct.ExistTy.html#structfield.origin) that tell us where the existential type came from. If we pass that field into the original function I cited, it can check if this is an async function and alter the error message wording.

**Comment by gilescope** [comment]
I presume use a new error number rather than E0720?

**Comment by Centril** [comment]
Fixed in https://github.com/rust-lang/rust/pull/62871.
