### ISSUE TITLE
include material on async fn in the Rust reference

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#62566]
This is a "rust-lang/rust" placeholder for https://github.com/rust-lang-nursery/reference/issues/634, since that exists in another repo/org.

**Comment by nikomatsakis** [comment]
I am taking a first pass at this.

**Comment by skade** [comment]
If I see that right, https://github.com/rust-lang-nursery/reference/pull/635 seems reasonably complete and mainly waits for #62149 to be merged before being included in the reference?

**Comment by Centril** [comment]
@skade Yeah we wait for the stabilization PR to go through before changing the reference; the PR is indeed reasonably complete aside from some nits.

**Comment by Centril** [comment]
Closing this in favor of tracking the remaining reference work in the reference repo.
