### ISSUE TITLE
Async blocks are leaky about wording wrt. `?` in diagnostics

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#62570]
E.g. consider:

```rust
#![feature(async_await)]

fn foo() {
    let x = async move {
        Err(())?;

        1
    };
}
```

which yields the diagnostic:

```
error[E0277]: the `?` operator can only be used in a function that returns `Result` or `Option` (or another type that implements `std::ops::Try`)
 --> src/lib.rs:5:9
  |
5 |         Err(())?;
  |         ^^^^^^^^ cannot use the `?` operator in a function that returns `{integer}`
  |
  = help: the trait `std::ops::Try` is not implemented for `{integer}`
  = note: required by `std::ops::Try::from_error`
```

Ostensibly the user might think of `fn foo` as "the function" but it is in fact the `async` block that is "the function" here. That seems like something which would confuse users who are not familiar with the lowering and whatnot (most users).

**Comment by theduke** [comment]
I ran into this.

It's much more confusing if the outer function actually returns a result.

This is bad enough that it imo should be considered `AsyncAwait-Blocking`.

```rust
#![feature(async_await)]

async fn f() -> Result<(), ()> {
    async {
        Err(())?
    }.await;
    
    Ok(())
}
```

**Comment by estebank** [comment]
At this point there are enough cases that we would want to disambiguate between that it makes sense to extend `on_unimplemented` to have some way of obtaining the enclosing scope's description (`closure`/`function`/`method`/`async` block, etc.).

**Comment by Centril** [comment]
I think something like:

```rust
#[rustc_on_unimplemented(
   on(all(
       any(from_method="from_error", from_method="from_ok"),
       from_desugaring="QuestionMark"),
      message="the `?` operator can only be used in {ItemCtx} \
               that returns `Result` or `Option` \
               (or another type that implements `{Try}`)",
      label="cannot use the `?` operator in {ItemCtx} that returns `{Self}`"),
   on(all(from_method="into_result", from_desugaring="QuestionMark"),
      message="the `?` operator can only be applied to values \
               that implement `{Try}`",
      label="the `?` operator cannot be applied to type `{Self}`")
)]
```

would make sense, which is basically @estebank's idea.

**Comment by gilescope** [comment]
There's almost no difference between an async closure and an async function call in the hir. For now async functions may also have to be reported as being an async closure...

**Comment by gilescope** [comment]
E.g.
```
async fn an_async_function() -> u32 {
    let x: Option<u32> = None;
    x?; //~ ERROR the `?` operator
    22
}
```
vs:
```
async fn an_async_block() -> u32 {
    async {
        let x: Option<u32> = None;
        x?; //~ ERROR the `?` operator
        22
    }.await
}
```
All the other cases seem fine, but not sure for this one how to proceed...

**Comment by estebank** [comment]
Can't you add a field to the relevant hir element to signal the difference?
