### ISSUE TITLE
Meaningless usage of comment decorators

### ISSUE THREAD

**Issue by tcharding** [rust-lang/rust#62601]
We have a number of places in the code base that use 'comment decorators' i.e. from `rustlib/src/rust/src/libcore/option.rs`
```
/////////////////////////////////////////////////////////////////////////////
// Type implementation
/////////////////////////////////////////////////////////////////////////////

impl<T> Option<T> {
```
This adds no extra meaning to the code and is totally specific to the developer that wrote it.  We should remove this sort of thing :)
```
[path/to/rustlib/src/rust/src/libcore/] $ egrep -R '/////////////////////' | wc -l
74
```

This issue has been assigned to @sd234678 via [this comment](https://github.com/rust-lang/rust/issues/62601#issuecomment-518989825).

**Comment by sd234678** [comment]
I think this might want closing as well now, @nikomatsakis?

**Comment by nikomatsakis** [comment]
Sounds good, thanks! Closing per [this conversation](https://github.com/rust-lang/rust/pull/63347#issuecomment-525172315).
