### ISSUE TITLE
Update error message for `self`

### ISSUE THREAD

**Issue by limira** [rust-lang/rust#62609]
I did some search and find no similar issue, so here is my report:

Compile the following code:
```rust
struct Data;
impl Data {
    fn rc(self: &std::rc::Rc<Self>) {
        println!("&rc");
    }
}
```
Give the error:
```
error[E0658]: `&std::rc::Rc<Data>` cannot be used as the type of `self` without the `arbitrary_self_types` feature
 --> src/main.rs:3:17
  |
3 |     fn rc(self: &std::rc::Rc<Self>) {
  |                 ^^^^^^^^^^^^^^^^^^
  |
  = note: for more information, see https://github.com/rust-lang/rust/issues/44874
  = help: consider changing to `self`, `&self`, `&mut self`, or `self: Box<Self>`
```
Think the **last line** of the error message should be updated to match the current status: https://doc.rust-lang.org/reference/items/associated-items.html which states:

>If the type of the self parameter is specified, it is limited to one of the following types:
>
>* `Self`
>* `&Self`
>* `&mut Self`
>* `Box<Self>`
>* `Rc<Self>`
>* `Arc<Self>`
>* `Pin<P>` where P is one of the above types except Self.

**Comment by limira** [comment]
But it is better if Rust supports `self: &Rc<Self>`, is it possible?

**Comment by hellow554** [comment]
It's not yet possible. See the compiler output:

> cannot be used as the type of `self` without the `arbitrary_self_types` feature

See [the unstable book](https://doc.rust-lang.org/unstable-book/language-features/arbitrary-self-types.html) for that feature flag. So you have to use a nightly compiler and opt into that feature to use it. There's nothing werong here. The reference is referencing the nightly compiler and not the stable one.

**Comment by limira** [comment]
At least `self: Rc<Self>` [works on stable](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=6e53aefd23aaab09a54970a190d08c79) (unless I am confused), but the error message only suggest `&self`, `&mut self`, or `self: Box<Self>`.

**Comment by hellow554** [comment]
Upsidaisy. you're right, my bad. Would you think you could do a PR and improve that? Should be fairly easy. Ask here if you need some guidance.

**Comment by limira** [comment]
I do a quick search and found at least 3 instances of `help` with the same content in [wfcheck: the first here](https://github.com/rust-lang/rust/blob/71f9384e3bec467158a628e2d11e77ffada16a90/src/librustc_typeck/check/wfcheck.rs#L807), the second on `L825`, the third is on `L832` (all in the same file). If I do it, I want to replace them with a
```rust
    const HELP_FOR_SELF_TYPE: &str = "consider changing to `self`, `&self`, `&mut self`, `self: Box<Self>`, \
                                     `self: Rc<Self>`, `self: Arc<Self>`, or `self: Pin<P>` (where P is one \
                                     of the previous types except `Self`)";
```
then use `.help(HELP_FOR_SELF_TYPE)` in all 3 locations.

Hope it goes well, because I don't think I will try to compile Rust on my tiny machine!

**Comment by limira** [comment]
I create a PR #62712
