### ISSUE TITLE
[1.38] Placement new syntax no longer parses

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#62617]
root: mbox 0.3.1; cc @kennytm causes:
  * resin-os/healthdog-rs: [start](https://crater-reports.s3.amazonaws.com/beta-1.37-1/1.36.0/gh/resin-os.healthdog-rs/log.txt) v. [end](https://crater-reports.s3.amazonaws.com/beta-1.37-1/beta-2019-07-04/gh/resin-os.healthdog-rs/log.txt); cc `@willnewton`

root: rayon-hash 0.2.0 cc @cuviper 
  * coder543/xray: [start](https://crater-reports.s3.amazonaws.com/beta-1.37-1/1.36.0/gh/coder543.xray/log.txt) v. [end](https://crater-reports.s3.amazonaws.com/beta-1.37-1/beta-2019-07-04/gh/coder543.xray/log.txt); cc `@coder543`

Root cause of these on our side is #60803 which removed support for parsing placement new even under `#[cfg(false)]` and the like. The crater run done there seems to have not found these -- not sure why. We might be testing more now than we were before.

**Comment by kennytm** [comment]
The `<-` support in `mbox` has been removed in 0.5.0.

The `mbox 0.3.1` dependency was introduced by `systemd 0.1.0`, but the current version is `systemd 0.4.0` which doesn't depend on `mbox`. 

`resin-os/healthdog-rs` depends on `systemd 0.*` so a `cargo update` is enough to remove the broken `mbox` dependency.

FYI @willnewton you may want to run `cargo update` to update the `Cargo.lock`.

**Comment by cuviper** [comment]
> root: rayon-hash 0.2.0 cc @cuviper
> 
> * coder543/xray: [start](https://crater-reports.s3.amazonaws.com/beta-1.37-1/1.36.0/gh/coder543.xray/log.txt) v. [end](https://crater-reports.s3.amazonaws.com/beta-1.37-1/beta-2019-07-04/gh/coder543.xray/log.txt); cc `@coder543`

`rayon-hash` came up in #50832 and was fixed in 0.3.0. It's up to 0.5.0 now, and deprecated in favor of `hashbrown/rayon` anyway. @coder543 should update, if this `xray` project is at all active.

**Comment by coder543** [comment]
@cuviper `xray` is unfortunately not being developed any further

**Comment by coder543** [comment]
@Mark-Simulacrum those "ccs" you tried to do to tag people don't work because you put them in code blocks, just FYI...

**Comment by cuviper** [comment]
@coder543 would you accept a PR bumping dependencies? Otherwise, maybe we should remove this repo from crater's list.

**Comment by coder543** [comment]
@cuviper yeah, either option would be fine!

**Comment by Mark-Simulacrum** [comment]
> @Mark-Simulacrum those "ccs" you tried to do to tag people don't work because you put them in code blocks, just FYI...

That's intentional, I try to not ping downstream users before the root cause is assessed and/or addressed by that author.

**Comment by coder543** [comment]
Updated code has been merged

**Comment by nagisa** [comment]
Since this syntax was never intended to be stablised, I think it is fine to say it was an oversight unstable syntax is not gated.

**Comment by nagisa** [comment]
We should decide how we want to deal with unstable syntax.

If unstable syntax like in this particular instance the `<-` operator, was properly gated, people would have to always use nightly if any code uses features with unstable syntax, even if such uses appeared behind `#[cfg]`. The current situation ended up not gating the syntax properly which is now causing problems when changing/removing it. Tagging T-lang to make them aware of it.

**Comment by petrochenkov** [comment]
I try to ensure during reviews that new features changing the grammar are gated at parse time.

**Comment by Mark-Simulacrum** [comment]
Removing T-compiler and nominating for T-lang -- I think we should close this; the ungated syntax landed a long time ago and we're pretty good these days about ensuring that we check grammar early enough that this isn't a problem (as @petrochenkov notes).

**Comment by Centril** [comment]
Me, @cramertj, and @qmx agree with @Mark-Simulacrum's rationale and so we'll close this as resolved.
