### ISSUE TITLE
[1.38] rayon failing test

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#62616]
* rayon-1.1.0: [start](https://crater-reports.s3.amazonaws.com/beta-1.37-1/1.36.0/reg/rayon-1.1.0/log.txt) v. [end](https://crater-reports.s3.amazonaws.com/beta-1.37-1/beta-2019-07-04/reg/rayon-1.1.0/log.txt); cc @cuviper

Haven't actually attempted to reproduce this locally but looks like something that might be worth looking at.

**Comment by cuviper** [comment]
Yeah, the `iter_panic_fuse` test isn't fully deterministic: https://github.com/rayon-rs/rayon/issues/667

No worries on the compiler side -- closing.
