### ISSUE TITLE
Add Option::err_or* to complement Option::ok_or*

### ISSUE THREAD

**Issue by jonhoo** [rust-lang/rust#62625]
We already have `Option::ok_or` and `Option::ok_or_else` to go from `Option<T>` to `Result<T, _>`, but we have no method to perform the opposite conversion from `Option<E>` to `Result<_, E>`.

(Eventual) tracking issue for #62624.

**Comment by jfrimmel** [comment]
The typo in the title (`err_ok` instead of `err_or`) is misleading :smile:

**Comment by jonhoo** [comment]
@jfrimmel haha, good point, fixed!

**Comment by SimonSapin** [comment]
Closing since https://github.com/rust-lang/rust/pull/62624 has not landed. Feel free to reopen when it does.
