### ISSUE TITLE
Code under the 2-clause-BSD license is not documented as a compatible license for the Rust runtime

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/rust#62620]
The 2-clause-BSD license is not documented in the tidy script as being a compatible license for the rust runtime dependencies. We used to ship BSD licensed code as part of libstd until recently: https://github.com/rust-lang/rust/commit/0b85b64d6b70b100f6222a96ff2337c302b386f1#diff-4131508972c86fdd799a5f7d41fdd323 and we shipped jemalloc for a long time as part of the runtime on many targets. 

We still do ship code with the MPL2.0 license in some targets, see: https://github.com/rust-lang/rust/blob/master/src/tools/tidy/src/deps.rs#L51

The deps check of the tidy script should be better documented to explain what's allowed and what isn't.

**Comment by Mark-Simulacrum** [comment]
We discussed this a bit today and concluded that we don't need the SGX dependencies to be appropriately licensed (they're somewhat "third party") so I'm closing this issue.

**Comment by gnzlbg** [comment]
So does that mean that it is ok to add third party libraries to the runtime under this license?

**Comment by Mark-Simulacrum** [comment]
Not in general. In this case, it's specifically for SGX so that's why we're not concerned about it.

**Comment by gnzlbg** [comment]
This issue was way broader than SGX is using an incompatible license.
