### ISSUE TITLE
Bring back suggestion for splitting `<-` in a comparison

### ISSUE THREAD

**Issue by varkor** [rust-lang/rust#62632]
```rust
fn main() {
    if x<-1 {
    }
}
```
produces:
```
error: expected `{`, found `<-`
```
It would be nice if it produced a suggestion to split it up:
```rust
if x < -1 {
```
(This [used to happen](https://github.com/rust-lang/rust/pull/60803#discussion_r303081575), but was broken in a previous change.)

**Comment by agnxy** [comment]
Hi @varkor I'd like to try this one. Just found the removed suggestion.
@rustbot claim

**Comment by iluuu1994** [comment]
@agnxy It doesn't look like you're still working on this. Is it ok if I take over?

**Comment by agnxy** [comment]
@iluuu1994 Sure. Thanks for your help.
