### ISSUE TITLE
Odd type mismatch error?

### ISSUE THREAD

**Issue by mark-i-m** [rust-lang/rust#62630]
I got the following while working on #58281. I messed up the condition of an `if` (so that its type was `usize` instead of `bool`) as the error correctly points:

```console
   Compiling rustc_mir v0.0.0 (/nobackup/rust2/src/librustc_mir)
error[E0308]: mismatched types
   --> src/librustc_mir/borrow_check/nll/region_infer/error_reporting/outlives_suggestion.rs:150:12
    |
150 |         if self.constraints_to_add.len() {
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |            |
    |            expected bool, found usize
    |            in this expansion of `desugaring of `if``
    |            in this macro invocation

```

Except that this is not part of a macro invocation or definition, to the best of my knowledge, so what does "desugaring of `if`" mean and what is the `macro invocation`?

**Comment by estebank** [comment]
It'd be nice to have a reduced test case, as I haven't been able to replicate this.

**Comment by mark-i-m** [comment]
I will try to minimize it soon.

**Comment by mark-i-m** [comment]
@Centril I am wondering if this may be related to your work on desugaring if/while...

**Comment by Centril** [comment]
@mark-i-m it most definitely is. Take a look at lowering.rs of if expressions to see the reason. I will be on vacation for a week so I won't be able to work on this during that time.

**Comment by Mark-Simulacrum** [comment]
I can't reproduce this and as such am going to close presuming it's been fixed since then, if not, let's reopen with a reproduction.
