### ISSUE TITLE
Rust binaries seem a bit large

### ISSUE THREAD

**Issue by zzywysm** [rust-lang/rust#62664]
Rust newbie here, going through the rust-lang book, specifically chapter 1.2.

>$ rustc --version
>rustc 1.36.0 (a53f9df32 2019-07-03)
>$ cat main.rs 
>fn main()
>{
>	println!("Hello, world!");
>}
>
>$ rustc main.rs 
>$ ls -la
>total 528
>drwxr-xr-x  4 zzy  staff     128 Jul 13 12:21 .
>drwxr-xr-x  3 zzy  staff      96 Jul 13 11:59 ..
>-rwxr-xr-x  1 zzy  staff  **264480** Jul 13 12:21 main
>-rw-r--r--  1 zzy  staff      43 Jul 13 12:00 main.rs
>$ rustc -C opt-level=s main.rs
>$ ls -la
>total 528
>drwxr-xr-x  4 zzy  staff     128 Jul 13 12:22 .
>drwxr-xr-x  3 zzy  staff      96 Jul 13 11:59 ..
>-rwxr-xr-x  1 zzy  staff  **264000** Jul 13 12:22 main
>-rw-r--r--  1 zzy  staff      43 Jul 13 12:00 main.rs

That seems like it's at least 263000 more bytes than needed to print "Hello world" to stdout.  Is there a better compiler flag to pass to reduce the binary size?

**Comment by zzywysm** [comment]
Forgot to mention, this is on macOS Mojave.

**Comment by Mark-Simulacrum** [comment]
This is a good first step in understanding, though it's a bit outdated: https://lifthrasiir.github.io/rustlog/why-is-a-rust-executable-large.html. However, the best place for such questions is users.rust-lang.org or internals.rust-lang.org - this issue tracker is kept solely for issues. Thank you!
