### ISSUE TITLE
Nested method calls with `&mut` receivers result in borrowck errors

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#6268]
This is challenging to resolve. I thought I could fit into the new borrow checker, but it is worth addressing separately since there are a number of subtle issues. What this really amounts to is that you need to support borrows where the lifetime of the borrow pointer does not encompass the borrow itself. To handle this safely, we wind up with two loans, the primary one and then a secondary, aliasing loan that tracks the fact that a pointer has been created, even if the memory it points at cannot be dereferenced yet.

Part of #5074

**Comment by cmr** [comment]
Triage bump; still an issue.

**Comment by kballard** [comment]
cc me, I still hit this with surprising regularity.

**Comment by nikomatsakis** [comment]
Closing in favor of https://github.com/rust-lang/rfcs/issues/811

**Comment by dcsommer** [comment]
Seems to be a blocker for some async IO patterns needed for lowest-latency processing. cc me.
