### ISSUE TITLE
Failed in tidy due to submodule

### ISSUE THREAD

**Issue by JohnTitor** [rust-lang/rust#62706]
In the latest rust-lang/rust master, we see many tidy (`x.py test src/tools/tidy`) errors probably due to stdarch(stdsimd).

Errors, for example:

- CR characters
- line longer than 100 chars
- tab characters

I already ran `x.py clean` but the issue hasn't been fixed.

**Comment by lzutao** [comment]
Tidy runs fine on my machine: 4b65a86ebace8600c8e269e8bfe3365cdc460e68

**Comment by JohnTitor** [comment]
@lzutao Thanks, this issue may be unique to me...

**Comment by JohnTitor** [comment]
Oh, it seems that `stdsimd` was out of submodules because it was renamed, and caused the tidy errors as rustc code. So the tidy errors are unique to me.
