### ISSUE TITLE
Which is accessor method of MetadataExt?

### ISSUE THREAD

**Issue by lzutao** [rust-lang/rust#62711]
https://github.com/rust-lang/rust/blob/4b65a86ebace8600c8e269e8bfe3365cdc460e68/src/libstd/os/linux/fs.rs#L36-L41

**Comment by hellow554** [comment]
`as_raw_stat` returned the [stat struct](https://doc.rust-lang.org/std/os/linux/raw/struct.stat.html) containing all the information.
Now you should access them via the methods provided by the trait, e.g. [`st_dev`](https://doc.rust-lang.org/std/os/linux/fs/trait.MetadataExt.html#tymethod.st_dev), [`st_ino`](https://doc.rust-lang.org/std/os/linux/fs/trait.MetadataExt.html#tymethod.st_ino), [`st_mode`](https://doc.rust-lang.org/std/os/linux/fs/trait.MetadataExt.html#tymethod.st_mode) etc.

**Comment by lzutao** [comment]
Thanks for explanation. But I think reading the deprecated message is misleading.

**Comment by Mark-Simulacrum** [comment]
PRs to change the wording would likely be accepted, but nothing better comes to mind right now. It seems pretty straightforward to me what the deprecation means.
