### ISSUE TITLE
Why is Rust free?

### ISSUE THREAD

**Issue by ghost** [rust-lang/rust#62721]
Hello Rust developers,

I have tried searching on rust-lang.org and related websites. I've searched wikipedia and the Internet. But I can't find the answer to my question: Why is Rust free?

May I ask if you could add that answer to rust-lang.org? Just in case other people have that same question.

Thank you,

**Comment by jonas-schievink** [comment]
Hi! This issue tracker is mainly meant for bug reports and concrete, small feature requests. Questions like this are better asked in the user forum at https://users.rust-lang.org/ or on [one of the chat platforms](https://www.rust-lang.org/community) used by the Rust community.

Once an answer is found, feel free to open a PR to https://github.com/rust-lang/www.rust-lang.org/ adding it to the website (if it fits somewhere). This repo here is used to track issues in the Rust compiler and standard library, not its website.
