### ISSUE TITLE
Improving error for unnecessary parentheses in `for` loop head

### ISSUE THREAD

**Issue by badboy** [rust-lang/rust#62724]
The following code:

```rust
fn main() {
    let v = vec![1,2,3];
    
    for (x in v) { }
}
```

leads to this error:

```
error: expected one of `)`, `,`, or `@`, found `in`
 --> src/main.rs:4:12
  |
4 |     for (x in v) { }
  |            ^^ expected one of `)`, `,`, or `@` here
```

([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=0cc6c5cf1f381e2f05fce24b1e59ecba))

A colleague of mine typed this code, coming with a C++/JavaScript/Kotlin background where parentheses are required in the `for` loop head.

I wonder if it’s possible/worth it to make that error message nicer and easier to understand. (@estebank asked me to file this issue, so it doesn't get lost)

**Comment by hellow554** [comment]
I wonder why this isn't accepted. You can write `if (x == 3) { }`, so shouldn't this code be accepted as well? 🤔

**Comment by badboy** [comment]
> I wonder why this isn't accepted. You can write `if (x == 3) { }`, so shouldn't this code be accepted as well? 🤔

The syntax for that loop is explicitly `"for" $pattern "in" $expression {}`.
For `if` the syntax would be `if $expression {}` and only the expression can contain the parentheses.
Of course it _could_ be just accepted with optional parentheses for the loop, but we don't really want that (and parentheses in `if` are a lint-warning)
