### ISSUE TITLE
core::fmt::Formatter needs setter methods

### ISSUE THREAD

**Issue by Lokathor** [rust-lang/rust#62731]
If you're given a format string when formatting a struct there's no way to

1) read some of that data
2) decide how to format the struct fields.
3) have those fields then format themselves according to an alternate `Formatter` based on your decision above.

**Example:** if you get a width argument, you can't use some of the width space yourself and then tell an inner field to format itself with a smaller width value because you used some of it.

So `Formatter` should get methods to change its configuration for things that are safe to change (width, alternate flag, precision, etc)

**Comment by Mark-Simulacrum** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/19207.
