### ISSUE TITLE
Docker build stopped due to lot of memory usage during dependencies compilation

### ISSUE THREAD

**Issue by MarcAntoine-Arnaud** [rust-lang/rust#62747]
Hello,

I'm currently face to a big issue for me.
Trying to build the docker image of this project: https://github.com/FTV-Subtil/rs_http_worker
I cannot achieve it as lot of memory is used, so workers swap a lot and build take more than 1h.

Do you have some ideas to optimise build ? In term of memory usage ?

Thanks
Marc-Antoine

**Comment by Patryk27** [comment]
Hi, I think you might be better off asking this question on [Reddit](https://www.reddit.com/r/rust) or other Rust-related forums - GitHub is an issue tracker related to Rust compiler's bugs.

**Comment by jonas-schievink** [comment]
Yep, that's correct, please make use of the forums or Reddit.
