### ISSUE TITLE
rustdoc doesn't render links in Trait Implementations sections

### ISSUE THREAD

**Issue by lzutao** [rust-lang/rust#62741]
https://doc.rust-lang.org/nightly/std/iter/struct.Flatten.html#method.scan
![image](https://user-images.githubusercontent.com/15225902/61345900-28c8b300-a881-11e9-8454-90b780310685.png)
https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html#method.scan
![image](https://user-images.githubusercontent.com/15225902/61345923-39792900-a881-11e9-937f-6ce620adc8b7.png)

As we can see, `fold` is not linked in the first image.

**Comment by GuillaumeGomez** [comment]
Problem isn't coming from intra links contrary to my first thought but just that we're "removing" links. For instance we use `[fold]` but define it below, therefore the markdown cannot generate the link.

**Comment by lzutao** [comment]
I don't get it. But if you see this as won't fix, feels free to close this issue.

**Comment by GuillaumeGomez** [comment]
No, I wrote the fix. However it'll certainly break a few things in the std (same issue with short doc when listing items at the top level, the non absolute urls will be bad haha).
