### ISSUE TITLE
ICE while switching a type definition between enum and trait

### ISSUE THREAD

**Issue by topecongiro** [rust-lang/rust#62751]
I have observed an ICE when I run `cargo check`. At that time I was switching a type definition between `enum` and `trait` on my own type.

At first I was using a trait:
```rust
trait Block {
 // ...
}
```

on implementing it further I realized that I needed to use GAT, so I switched to using an enum:
```rust
enum Block {
  // ...
}
```

and then I encountered the ICE.

 The error message is as follows:

```
error: internal compiler error: src/librustc/dep_graph/graph.rs:688: DepNode Hir(rustfmt_nightly[590c]::visitable[0]::Block[0]::items[0]) should have been pre-allocated but wasn't.
```

The ICE disappeared after I run `cargo clean`. I have not yet able to reproduce it. I will update this issue once I come up with a minimal working example.

### rustc version
`rustc 1.38.0-nightly (07e0c3651 2019-07-16)`

**Comment by hellow554** [comment]
Maybe related to #62649 ?

**Comment by jonas-schievink** [comment]
Yeah, looks like a pretty clear duplicate. Closing.
