### ISSUE TITLE
hashbrown's trait implementations appear in std docs

### ISSUE THREAD

**Issue by 17cupsofcoffee** [rust-lang/rust#62763]
Perhaps this is a known issue, but I've noticed that since `hashbrown` was integrated into the standard library, impls from that crate now [show up under the 'Implementations on Foreign Types' section of the trait docs](https://doc.rust-lang.org/std/iter/trait.IntoIterator.html#foreign-impls).

This is unfortunate, since the `hashbrown` versions of those types aren't actually accessible through `std` (`std::collections::HashMap` and `std::collections::HashSet` are [effectively newtypes wrapping them](https://doc.rust-lang.org/src/std/collections/hash/map.rs.html#207-209)). Adding to the confusion, these seem to get precedence naming-wise over the actual implementations that you *can* use, which are [referred to by their fully qualified names further down the page](https://doc.rust-lang.org/std/iter/trait.IntoIterator.html#impl-IntoIterator-5).

I'm not sure if anything can actually be done about this without changes to rustdoc, and it's not a huge deal, but I figured it was worth raising :)

**Comment by GuillaumeGomez** [comment]
I only saw hashbrown in examples. If so, it can be fixed easily. Or did I miss something?

**Comment by GuillaumeGomez** [comment]
I just realised that it's not linking to std types apparently, which is weird... Also, I think we should "hide" the hashbrown types if possible since I \*think\* they're public for the moment.

**Comment by 17cupsofcoffee** [comment]
[The std types do have links](https://doc.rust-lang.org/std/iter/trait.IntoIterator.html#impl-IntoIterator-5) - what I'm getting at is that the first `HashMap` and `HashSet` listed *aren't* the `std` ones :p They're [`hashbrown::HashMap`](https://docs.rs/hashbrown/0.5.0/hashbrown/struct.HashMap.html#impl-IntoIterator) and [`hashbrown::HashSet`](https://docs.rs/hashbrown/0.5.0/hashbrown/struct.HashMap.html#impl-IntoIterator), hence why the examples match the ones shown on that crate's docs. Those impls are the ones from `hashbrown` that the `std` wrapper types [forward on to](https://doc.rust-lang.org/src/std/collections/hash/map.rs.html#1705).

**Comment by GuillaumeGomez** [comment]
> The std types do have links - what I'm getting at is that the first HashMap and HashSet listed aren't the std ones :p

That's what I meant when I wrote "I just realised that it's not linking to std types apparently, which is weird..." (badly said though).

What's difficult is that we have types depending on std types which depend on those types. Circular documentation, I think that's a first haha!

**Comment by Mark-Simulacrum** [comment]
We should probably apply `#![cfg_attr(feature = "rustc_internal_api", doc(hidden))]` on the crate? Presumably that'll work, though not sure if we directly re-export any part of hashbrown from std...

**Comment by 17cupsofcoffee** [comment]
As far as I can tell, the only usages of `hashbrown` are in [`map.rs`](https://github.com/rust-lang/rust/blob/master/src/libstd/collections/hash/map.rs), and they're all private.

**Comment by jyn514** [comment]
I think this was fixed by https://github.com/rust-lang/rust/pull/76571 - @17cupsofcoffee can you double check?

**Comment by 17cupsofcoffee** [comment]
Yes, the issue seems to be fixed - the only `HashMap` mentioned on that page now is the `std` one 🎉
