### ISSUE TITLE
Minor 1.36 rustdoc regression:  \] after a link is not treated as an escape

### ISSUE THREAD

**Issue by MaulingMonkey** [rust-lang/rust#62770]
A minor change in behavior between 1.35.0 and 1.36.0.  Repro example here:

```
/// \[This escapes both brackets\]
/// \[[This escapes only the left bracket as of 1.36.0](https://www.google.com/)\]
pub fn example() {
}
```

Run a standard `cargo doc`.  In 1.36.0, the link will display `\]` instead of `]` after the link, whereas in 1.35 it will display `]` after the link.

**Comment by ehuss** [comment]
I filed https://github.com/raphlinus/pulldown-cmark/issues/375 for this.
