### ISSUE TITLE
Cross-crate re-export produces invalid rustdoc for impl Trait

### ISSUE THREAD

**Issue by fatemender** [rust-lang/rust#62779]
In a cross-crate reexport of an `impl Trait`-accepting function, rustdoc formats it in a wrong way which is not even valid Rust.

Let `crate1` be:

```rust
pub trait MyTrait {}
pub fn accepts_impl(_t: impl MyTrait) {}
```

Let `crate2` be:

```rust
pub use crate1::{MyTrait, accepts_impl};
```

If we generate docs for `crate2`, we get this definition for the (re-exported) `accepts_impl`:

```rust
pub fn accepts_impl<impl MyTrait>(_t: impl MyTrait) 
where
    impl MyTrait: MyTrait, 
```

I see some similarities with #60113 here.
Both issues still reproduce on stable 1.36.0 and nightly bc2e84ca0.

**Comment by sinkuu** [comment]
#61613 should fix this problem.

**Comment by Disasm** [comment]
It seems this issue is no longer present.
`rustc 1.41.0 (5e1a79984 2020-01-27)`

**Comment by jyn514** [comment]
Closing since this was fixed by https://github.com/rust-lang/rust/pull/61613
