### ISSUE TITLE
str::trim_start_matches and similar should not trust Searcher to return valid indices

### ISSUE THREAD

**Issue by thomcc** [rust-lang/rust#62773]
For example, https://github.com/rust-lang/rust/blob/bc2e84ca0939b73fcf1768209044432f6a15c2e5/src/libcore/str/mod.rs#L3748, and the equivalent in trim_end_matches.

The functions on Searcher that return these are not unsafe, and *someday* could be implemented outside the stdlib. Also the cost of the bounds/char boundary check there is probably going to be quite low.

In practice this doesn't matter since it's not stable, but still.

**Comment by scottmcm** [comment]
Is this really a bug?  It looks like `i` is coming from a [`Searcher`](https://doc.rust-lang.org/std/str/pattern/trait.Searcher.html), which is an `unsafe trait`:

https://github.com/rust-lang/rust/blob/bc2e84ca0939b73fcf1768209044432f6a15c2e5/src/libcore/str/mod.rs#L3740-L3750

**Comment by thomcc** [comment]
Whoops, my bad, I missed that the trait was unsafe.
