### ISSUE TITLE
Disable llvm orcjit

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rust#62798]

**Comment by jonas-schievink** [comment]
@bjorn3 I'm assuming this impacts our distribution size somewhat?

**Comment by bjorn3** [comment]
That too, but I was actually thinking about the compilation time.

**Comment by Mark-Simulacrum** [comment]
Presumably this really only affects LLVM compile times? If so it seems like we don't really gain much from doing this and marginally increase our complexity as we need to specify the options to pass down to LLVM's build system. I'd probably be willing to accept a PR doing this, though! The changes will need to be made to src/bootstrap/native.rs.

**Comment by nikic** [comment]
We already don't link the ExecutionEngine components, and I don't believe LLVM has support for disabling the compilation itself.

**Comment by Mark-Simulacrum** [comment]
In that case I'll close this -- if there's information otherwise we can reopen.
