### ISSUE TITLE
drop `let` keyword when using `mut`

### ISSUE THREAD

**Issue by catastrop** [rust-lang/rust#62796]

**Comment by jonas-schievink** [comment]
Hi! Changes to the language need to go through our [RFC process](https://github.com/rust-lang/rfcs). Before an RFC is written, the feature can also be discussed in our [internals forum](https://internals.rust-lang.org/) to find other people interested in it.

Closing in favor of an RFC.

**Comment by catastrop** [comment]
@jonas-schievink , don't close let us discuss

**Comment by qnighy** [comment]
We can discuss, but in an appropriate place. In fact there's already [a thread](https://internals.rust-lang.org/t/suggestion-mut-like-let-keyword/8851) for the same (or similar) proposal.
