### ISSUE TITLE
re-land #62150 (Implement mem::{zeroed,uninitialized} in terms of MaybeUninit)

### ISSUE THREAD

**Issue by ishitatsuyuki** [rust-lang/rust#62825]
#62150 got reverted to give users some time to migrate; we should re-land it.

**Original issue:**

https://github.com/rust-lang/rust/pull/62150 has changed the behavior of `mem::uninitialized()` (and `zeroed()`), causing a few popular crates to be killed by `SIGILL`. A writeup can be found [here](https://github.com/amethyst/amethyst/issues/1808#issuecomment-513449537).

There are cases where outdated (EOL) versions of downstream dependencies have this issue. In that case, the upstream crate will have to migrate to a newer major version of the dependency, which means it will have to deal with those breaking changes.

Therefore, I suggest we back out the change for at least one stable release, providing the community with the time to upgrade.

cc @RalfJung

**Comment by RalfJung** [comment]
Note that (to my knowledge) this change is in nightly only currently, and won't become stable until 1.38 (released in late September). But it causes trouble e.g. by making CI fail, I suppose.

Nominating for lang team discussion. I hope I am doing this right.^^

**Comment by RalfJung** [comment]
Some more relevant discussion:

* https://github.com/rust-lang/rust/issues/52898#issuecomment-505782110 is an old issue about `mem::zeroed` causing SIGILLs when used incorrectly.
* I [proposed](https://internals.rust-lang.org/t/make-mem-uninitialized-and-mem-zeroed-panic-for-some-types-where-0-is-a-niche/10605) to eventually make `zeroed` (and `uninitialized`) panic deterministically for some more cases that we can detect statically.

**Comment by joshtriplett** [comment]
Rather than panicking at runtime, could we detect this at *compile-time*, and issue a compile-time warning about calling `mem::uninitialized` or `mem::zeroed` with a type of `&T` and similar?

**Comment by joshtriplett** [comment]
Based on discussion in the lang team: we'd be fine with backing this out, but we *do* need a lint or similar mechanism to make sure people notice and fix code.

**Comment by RalfJung** [comment]
@joshtriplett
> Rather than panicking at runtime, could we detect this at compile-time, and issue a compile-time warning about calling mem::uninitialized or mem::zeroed with a type of &T or a function type or similar?

I assume you are responding to [this proposal](https://internals.rust-lang.org/t/make-mem-uninitialized-and-mem-zeroed-panic-for-some-types-where-0-is-a-niche/10605)?

For some cases yes, but not reliably in generic contexts.

**Comment by joshtriplett** [comment]
On July 25, 2019 12:38:13 PM PDT, Ralf Jung <notifications@github.com> wrote:
>@joshtriplett
>> Rather than panicking at runtime, could we detect this at
>compile-time, and issue a compile-time warning about calling
>mem::uninitialized or mem::zeroed with a type of &T or a function type
>or similar?
>
>I assume you are responding to [this
>proposal](https://internals.rust-lang.org/t/make-mem-uninitialized-and-mem-zeroed-panic-for-some-types-where-0-is-a-niche/10605)?
>
>For some cases yes, but not reliably in generic contexts.

Doesn't have to be perfect. If we can detect common cases like `&T` and function types, that would help people know they need to migrate.

**Comment by RalfJung** [comment]
Agreed. I think we can do something that traverses the type as far as we see it, and complains when it finds a reference, `fn`, `NonNull` or `NonZero*`.

We should probably stop looking when encountering an enum, or else we'd have to figure out which variant would be picked by the all-0 bit pattern and then look at the fields of that.

**Comment by RalfJung** [comment]
@ishitatsuyuki beta branches in 12 days. If you want this to be backed out, someone has to do it before that.

**Comment by ishitatsuyuki** [comment]
Is the lint a requirement for backing out? If so, we may want to reach a consensus on how to implement the check.

**Comment by RalfJung** [comment]
> Is the lint a requirement for backing out?

No, I don't think so. @joshtriplett could you clarify?

**Comment by joshtriplett** [comment]
Definitely not a requirement for backing out. More a requirement to happen well in advance of re-adding.

**Comment by RalfJung** [comment]
I'm working on a lint, should have a PR read tomorrow.

**Comment by RalfJung** [comment]
Lint PR up at https://github.com/rust-lang/rust/pull/63346

**Comment by RalfJung** [comment]
@joshtriplett what is the timeline you had in mind for putting the change back in place? `uninit` and `init` are two rather questionable intrinsics, so I'd like to get rid of them for good as soon as we can.

To my knowledge, the only crates that we know got broken by this are x11-rs (the broken part of which is "one giant hack" in the words of the maintainer) and old versions of `crossbeam::queue` (version 0.4 is reported to be broken; 0.5 has been released 9 months ago but I do not know if that one is fixed but crossbeam-queue 0.1 released 7 months ago and it is fixed).

**Comment by Centril** [comment]
> @joshtriplett what is the timeline you had in mind for putting the change back in place? `uninit` and `init` are two rather questionable intrinsics, so I'd like to get rid of them for good as soon as we can.

We discussed a one version grace period in this issue (see OP) and in the language team meeting. The lint has also been implemented (and then some...) so I think we should go ahead and revert the revert.

**Comment by RalfJung** [comment]
Okay. I personally would prefer to have a dynamic check in place as well on top of the static check that we have, just to be sure.

But either way I won't have time to work on this for this release cycle.

**Comment by RalfJung** [comment]
Status update: I filed https://github.com/rust-lang/rust/pull/66059 to add some run-time protection on top of the static lint that we already have (a first version of that lint is stable for 5 weeks already; a stronger version will become stable in a week).

Once the run-time protection lands, my plan is to wait a week to see if there's a big outcry like there was when #62150 landed. If not, I'll submit a PR to re-implement #62150 and kill the `init` and `uninit` intrinsics.

**Comment by RalfJung** [comment]
Re-landing PR is up at https://github.com/rust-lang/rust/pull/69922.
