### ISSUE TITLE
ICE on recursive struct

### ISSUE THREAD

**Issue by sgrif** [rust-lang/rust#62838]
repro code:

https://gist.github.com/sgrif/959bb5f820a0c9a616f569ea2195ff7c

`Expression` on line 68 should be `Box<Expression>`, introducing the indirection fixes the ICE. I haven't attempted to reduce beyond this example.

`rustc 1.36.0 (a53f9df32 2019-07-03)`

**Comment by NieDzejkob** [comment]
The crash seems to involve the incremental compilation mechanism. Triggering the ICE once will "store" it in the target folder, so you need to do a clean build to check whether a modified input still reproduces the bug. I'll try to minimise the example.

**Comment by NieDzejkob** [comment]
The bug stopped reproducing on clean builds even though I changed nothing. I'm really confused...

**Comment by nikomatsakis** [comment]
Checking in from the compiler team:

Is this a regression? I'm going to mark as P-medium as it seems to be "just an ICE" at this point.

**Comment by nikomatsakis** [comment]
Not to say we shouldn't fix it, mind you =) @NieDzejkob thanks for your efforts to minimize!

@sgrif are you still able to reproduce?

**Comment by sgrif** [comment]
I agree this is "just an ICE", and should be prioritized as such -- especially since the code to reproduce it would fail to compile anyway. I'm not sure what the first version where this occurs is.

I can still reproduce on the latest nightly. I get a more specific compiler error:

> error: internal compiler error: src/librustc/dep_graph/graph.rs:722: try_mark_previous_green() - Forcing the DepNode should have set its color

**Comment by sgrif** [comment]
I will note that I had to change that line to `Box<Expression>` to get it to compile once, then remove the `Box` to get the recursive version in order for the ICE to occur

**Comment by ackxolotl** [comment]
This might be the same issue as #61323. What do you think?

**Comment by hellow554** [comment]
This is a dup of #61323 indeed. Thanks for pointing it out @ackxolotl

**Comment by sgrif** [comment]
Closing as a dupe
