### ISSUE TITLE
Add a way to get the number of bits in a representation

### ISSUE THREAD

**Issue by danieldulaney** [rust-lang/rust#62836]
A few `core` APIs return values related to a number of bits. For example, the various [`leading_zeros` methods](https://doc.rust-lang.org/std/primitive.usize.html#method.leading_zeros), [`trailing_zeros` methods](https://doc.rust-lang.org/std/primitive.usize.html#method.trailing_zeros), [`count_zeros` methods](https://doc.rust-lang.org/std/primitive.usize.html#method.count_zeros), and [`count_ones` methods](https://doc.rust-lang.org/std/primitive.usize.html#method.count_ones). When working with these, you often need to determine the number of bits in the given number's representation. There does not appear to be an officially-supported way to do this in Rust. In fact, I could not find any documentation or RFC endorsing 8 bits per byte as a hard requirement. For example, will `size_of::<u32>()` always be 4? [Edit: Actually, it does say at the top of the `usize` primitive type that it will be 4 bytes on a 32-bit target at 8 bytes on a 64-bit target. I do wish it was slightly more prominent.]

There are at least three options:
- Add a `BITS_PER_BYTE` or similar constant somewhere with the value 8, and add documentation that `size_of::<T>() * BITS_PER_BYTE` is the number of bits in `T`'s representation.
- Add a `size_of_bits::<T>()` method in `core::mem` that returns the size of a type in bits
- Note in the documentation that the number of bits in an item's representation is always 8 times its size in bytes, but don't make a code change. Developers who need the size of an object can define their own `BITS_PER_BYTE` constant.

I think that this would be a small but valuable addition to the standard library. Having to define a magic number in my code that is not based on any official documentation feels like a design deficiency.

Is this something that needs an RFC? If so, I would be happy to write one up. (It would be my first RFC, so I'd appreciate any guidance).

**Comment by danieldulaney** [comment]
BTW, an example of some code that would benefit from this is a bitwise implementation of `floor_log2`:

```rust
fn floor_log2(x: usize) -> usize {
    const BITS_PER_BYTE: usize = 8;

    BITS_PER_BYTE * std::mem::size_of<usize>() - (x.leading_zeros() as usize) - 1
}
```

**Comment by jhpratt** [comment]
Is there _any_ system where 8 bits isn't a byte, and does Rust support that? I'd be very surprised if that ever changed.

**Comment by nagisa** [comment]
> Is there any system where 8 bits isn't a byte

There are, but Rust consciously does not and will not support them.

**Comment by danieldulaney** [comment]
Would it be possible to put that in the docs somewhere? I searched for "8 bits" in the `std` source and in the RFCs repository and didn't see it anywhere.

**Comment by RalfJung** [comment]
Cc @gnzlbg @rust-lang/wg-unsafe-code-guidelines 

There is some documentation of this at https://rust-lang.github.io/unsafe-code-guidelines/layout/scalars.html.

**Comment by gnzlbg** [comment]
@RalfJung we do say there that the `{i,u}{N}` types are `N` bits wide, that is, `u8` and `i8` are exactly 8 bits wide. The API documentation of these types says the same, e.g., see the [`u8`](https://doc.rust-lang.org/std/primitive.u8.html) documentation.

I don't know where would the right place to say in the UCGs book that 1 byte is always 8-bit, if anywhere. Maybe we could add a note there somewhere ?

The documentation of [`mem::size_of`](https://doc.rust-lang.org/std/mem/fn.size_of.html) do explicitly say that `u8` and `i8` are 1 byte wide, and it also explicitly says that `u32` is 4 bytes wide, answering the other questions of the OP. If the docs aren't clear enough, we could reword them.

**Comment by Mark-Simulacrum** [comment]
I believe we provide the necessary guarantees (in particular, @gnzlbg's note around `u8` guaranteeing to be 8 bits, mem::size_of returning 1 for u8...). I don't think our docs should be improved here, though if someone has specific ideas, we would happy to consider a PR. I am against a constant for the number of bits per byte, since that seems not too useful to have in std (and any library/file can trivially define such a constant if interested).

**Comment by danieldulaney** [comment]
It looks like this was added in 1.53.0 as [`u8::BITS`](https://doc.rust-lang.org/std/primitive.u8.html#associatedconstant.BITS)
