### ISSUE TITLE
Rustdoc link with module@ does not link to the module

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust#62830]
Starting with an ambiguous lib.rs:

```rust
pub mod x {}
pub fn x() {}

/// [x]
pub struct S;
```

rustdoc correctly reports the ambiguity and suggests the possible resolutions:

```console
warning: `x` is both a module and a function
 --> src/lib.rs:4:6
  |
4 | /// [x]
  |      ^ ambiguous link
  |
  = note: `#[warn(intra_doc_link_resolution_failure)]` on by default
help: to link to the module, prefix with the item type
  |
4 | /// [module@x]
  |      ^^^^^^^^
help: to link to the function, add parentheses
  |
4 | /// [x()]
  |      ^^^
```

In this case I want to link to the module so let's update lib.rs:

```rust
pub mod x {}
pub fn x() {}

/// [module@x]
pub struct S;
```

`cargo doc` accepts this without warnings but the generated html file contains:

```html
<a href="../repro/fn.x.html" title="module@x">module@x</a>
```

I would expect [module@x] to link to the module x, not the function x.

*Mentioning tracking issue: #43466*

**Comment by dtolnay** [comment]
Workaround: leverage rustc's name resolution instead of rustdoc's. https://github.com/dtolnay/syn/commit/ae1983c87afe0e04c884b7d11f513ea6baf54f84

```rust
pub mod x {}
pub fn x() {}

/// [module@x]
///
/// [module@x]: crate::rustdoc_workaround::x_module
pub struct S;

// https://github.com/rust-lang/rust/issues/62830
mod rustdoc_workaround {
    pub use crate::x::{self as x_module};
    //             ^^^^^^^^ no ambiguity with function
}
```

**Comment by jyn514** [comment]
This is coming directly from `rustc_resolve`, so I'm not sure how to fix it. Maybe @Manishearth has ideas? The issue is that currently we can only select between types, values, and macros, and modules count as all three so there's not a way to say 'only give me modules'. https://doc.rust-lang.org/nightly/nightly-rustc/rustc_resolve/enum.Namespace.html

**Comment by jyn514** [comment]
I think eventually we should switch rustdoc to using https://doc.rust-lang.org/nightly/nightly-rustc/rustc_resolve/late/struct.LateResolutionVisitor.html#method.smart_resolve_path which has support for fine distinctions like this through [`PathSource`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_resolve/late/enum.PathSource.html). That would also fix #74207. But I have no idea how hard that would be.

**Comment by Manishearth** [comment]
Yeah I don't know either. I'm not sure how that overlap works in resolve. @eddyb might?

We could tweak the resolve resolution functions to force looking for modules.

**Comment by eddyb** [comment]
I don't know much about name resolution, you want @petrochenkov.

Only thing I know is that it should be possible to get a `PerNs<Res>` and then use whichever namespace you want from there at your discretion.

**Comment by Manishearth** [comment]
@eddyb the problem is that modules seem to be special and exist in all namespaces but also overlap. Do you have an idea of how that works?

**Comment by eddyb** [comment]
"Modules count as all three" sounds wrong? Modules live in the type namespace last I checked.

**Comment by Manishearth** [comment]
Oh! Maybe we should just switch modules to being a type then, I was under the impression they lvied in all namespaces

**Comment by Manishearth** [comment]
And yeah, seems like types cannot overlap with modules.

**Comment by jyn514** [comment]
Wait I'm confused - I thought functions are in the type namespace? Are they values instead?

**Comment by Manishearth** [comment]
Functions are values
