### ISSUE TITLE
Allow generic parameters in intra doc link

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust#62834]
```rust
pub struct Collection<T> { __: T }

/// [`Collection`], [`Collection<T>`]
pub struct S;
```

Currently this renders as \` <a href="#">Collection</a>, \[`Collection<T>`\] \`, where the first link is ok but the second link is not rendered. I think these should both point to struct.Collection.html. For some types it can be clearer to include the type parameters when discussing them.

*Mentioning the tracking issue: #43466*

**Comment by Nemo157** [comment]
In relation to the objection @GuillaumeGomez had on the tracking thread, I have [a usecase](https://github.com/rust-lang/rust/issues/62867) where I want to link to the different parts of a fully applied (nested) generic type.

Extending the example slightly, should the following also work:

```rust
pub struct Collection<T> { __: T }

pub struct U;

/// [`Collection`], [`Collection<T>`], [`Collection<U>`]
pub struct S;
```

and should that result in something like:

> <a href=//Collection><code>Collection</code></a>, <a href=//Collection><code>Collection&lt;T&gt;</code></a>, <a href=//Collection><code>Collection</code></a><code>&lt;</code><a href=//U><code>U</code></a><code>&gt;</code>

?

**Comment by nixpulvis** [comment]
Would it make sense to support entire specialized doc pages like ".../target/doc/general/struct.General<i32>.html" (exact URL can't look like this I believe) so a link to a specific type of a polymorphic type can filter out all other `impl`s from the docs.

**Comment by jyn514** [comment]
>  support entire specialized doc pages

That seems a much bigger change than the one originally suggested. For one thing we'd have to design what the page should look like.

I wonder if we could hack this by deleting all text between `<` and `>` in intra-doc links? AFAIK the only time those are valid is for generics, and an unclosed delimiter would be a syntax error in a type.

>

**Comment by jyn514** [comment]
I've also seen people trying to use `Some(T)` which would be nice to support. This one is tricky because `Some()` is parsed as a function disambiguator. But maybe since currently don't distinguish between functions and other types just stripping the `T` would work?

**Comment by GuillaumeGomez** [comment]
I'm still strongly against it. However, I don't remember if we can mix type and anchor? Like: `[Collection#some-impl]`. In this case, it'd fix all issues I assume and is far more simple to implement (if not already done).

**Comment by jyn514** [comment]
Direct link so all the discussion is in one place: https://github.com/rust-lang/rust/issues/43466#issuecomment-513503459

**Comment by jyn514** [comment]
> In this case, it'd fix all issues I assume and is far more simple to implement (if not already done).

Well, it's still possible to link to `Some` directly. But it makes you use `[Some(T)](Some)` instead of the direct `[Some(T)]`. So I think we should consider making it easier for the same reason as `Option<T>`. See https://github.com/rust-lang/rust/pull/74300#discussion_r456380463 for an example.

**Comment by camelid** [comment]
Is a simple version of this planned to be implemented? A nice start would be something where `Vec<T>` just links to `Vec`. Then a lot of duplication like this could be avoided:

```markdown
Here's a link to [`Vec<T>`].

[`Vec<T>`]: Vec
```

**Comment by jyn514** [comment]
Mentoring instructions:

Just before calling [`resolve_with_disambiguator`](https://github.com/rust-lang/rust/blob/8a13fc494d4365e57d8f343219f0201458b68591/src/librustdoc/passes/collect_intra_doc_links.rs#L981), replace `path_str` with a version that has everything in `<>` stripped. Note that this should match the brackets: `Vec<Option<T>>` should turn into `Vec`, not `Vec>`.

**Comment by camelid** [comment]
I would be interested in implementing this.

@rustbot claim
