### ISSUE TITLE
test attribute doesn't check if another test attribute is specified

### ISSUE THREAD

**Issue by DoumanAsh** [rust-lang/rust#62847]
Currently if you slap `#[test]` two times you're going to get double tests in `cargo test` output.
I suspect it doesn't really care about presence of other attributes.
And I only noticed it because `tokio::test` attribute that wraps async functions for  tests also appends own `#[test]`

Not sure if it is bug and diagnostic message should be presented to user?

**Comment by DoumanAsh** [comment]
There are several compilation diagnostics for test attribute already, so I think it wouldn't be strange to add one more to warn user about multiple attributes?
https://github.com/rust-lang/rust/blob/5c26b523686497a46d10104c7295f366099a298c/src/libsyntax_ext/test.rs#L48

**Comment by JaniM** [comment]
This seems to have already been solved.
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=e773dbfad8d0a29e249c4d6e76ff1d0a

@rustbot release-assignment

**Comment by Nilstrieb** [comment]
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=47770a0622f3ee4f950fcd5f0919c626
it's not actually

**Comment by Nilstrieb** [comment]
So I'm closing this. Turning this into a hard error would probably involve an edition or at least some cratering and I don't think it's worth doing that, when the problem is already solved with the warning.
