### ISSUE TITLE
tidy complains about valid stability attribute

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#62846]
With the following stability attribute
```rust
    #[unstable(
        feature = "internal_uninit_const",
        issue = "0",
        reason = "hack to work around promotability",
    )]
```
tidy complained
```
tidy error: /checkout/src/libcore/mem/maybe_uninit.rs:256: malformed stability attribute: missing `feature` key
```
Seems like it's parser is a bit too simplified.

See https://github.com/rust-lang/rust/pull/62799#issuecomment-513543333 for the CI failure and https://github.com/rust-lang/rust/pull/62799/commits/f3abbf71035e469fce6db37bdb444ce3e50e870f for the work-around.

**Comment by varkor** [comment]
The parsing is very simplistic:
https://github.com/rust-lang/rust/blob/83dfe7b27cf2debecebedd3b038f9a1c2e05e051/src/tools/tidy/src/features.rs#L436-L446

**Comment by RalfJung** [comment]
Can't we just make rustc complain about malformed `stable`/`unstable` attributes? What is the reason why tidy has to check this?

**Comment by petrochenkov** [comment]
@RalfJung 
`rustc` already complains about missing `feature`s and other ill-formed stability attributes.
Tidy wants to collect those features to complain about something else, first of all (e.g. about a feature not having a dedicated test etc.).

**Comment by Mark-Simulacrum** [comment]
I'm going to close this as won't fix. Expanding tidy into a full fledged parser is something I'd like to avoid as much as possible, and this seems like something that's fairly easy to work around. Maybe we could refile on rustc-guide or similar as a "here's a hint that this error might be buggy" and associate how to fix it, not sure.
