### ISSUE TITLE
Missing x86/x86_64 intrinsic: `_mm_loadu_si32`

### ISSUE THREAD

**Issue by Lokathor** [rust-lang/rust#62876]
[intel guide](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#techs=SSE2&text=_mm_loadu_si32)

[rust docs show it as not there](https://doc.rust-lang.org/std/index.html?search=_mm_loadu_si32)

**Comment by Lokathor** [comment]
Note: `_mm_storeu_si32` is also missing

**Comment by TDecking** [comment]
These intrinsics were added in https://github.com/rust-lang/stdarch/pull/1594.
