### ISSUE TITLE
Link error if panic_handler is marked #[inline]

### ISSUE THREAD

**Issue by comex** [rust-lang/rust#62888]
Test case:
```rust
#![feature(core_intrinsics)]
#![no_std]
#![no_main]

#[panic_handler]
#[inline(always)]
pub fn panic_imp(_: &core::panic::PanicInfo) -> ! {
    unsafe { core::intrinsics::abort(); }
}

#[no_mangle]
pub extern fn main() -> i32 {
    panic!()
}
```

Compiling with:
```
rustc foo.rs -C panic=abort -O -C link-arg=-lSystem 
```

(This is on macOS; on other platforms you probably want different link args.)

I get:
```
  = note: Undefined symbols for architecture x86_64:
            "_rust_begin_unwind", referenced from:
                core::panicking::panic_fmt::h5e21b2f040947e1b in libcore-785d18b4fffac943.rlib(core-785d18b4fffac943.core.c3we4nte-cgu.0.rcgu.o)
```

In retrospect this error makes sense, since `#[inline(always)]` normally prevents a function from being instantiated unless needed.  But there should be an exception for lang items.

Without LTO, `#[inline(always)]` is futile anyway.  But with LTO, rustc can emit IR with the function marked `alwaysinline`, and the linker should respect that.

Edit: This also happens with just `#[inline]`.

**Comment by Mark-Simulacrum** [comment]
Seems like we should forbid `#[inline]` in the interim since fixing this is presumably hard but we should at least avoid the linker errors (even if this is not a common case).

**Comment by Enselic** [comment]
Triage: Can you still reproduce this on mac? I get no linker errors on Ubuntu 22.04.1 LTS (WSL 2) with this command:

```sh
rustc foo.rs -C panic=abort -O -C link-arg=-lc
```

```console
$ rustc -vV
rustc 1.76.0-nightly (87e1447aa 2023-11-30)
binary: rustc
commit-hash: 87e1447aadaa2899ff6ccabe1fa669eb50fb60a1
commit-date: 2023-11-30
host: x86_64-unknown-linux-gnu
release: 1.76.0-nightly
LLVM version: 17.0.5
```

**Comment by saethlin** [comment]
I suspect this has either been fixed for a long time, or I fixed it during the cleanups that resulted from bootstrapping with `-Zcross-crate-inline-threshold=always`.
