### ISSUE TITLE
integer method `wrapping_abs` should be made const

### ISSUE THREAD

**Issue by Lokathor** [rust-lang/rust#62925]
The current `wrapping_abs` definition is

```rust
            pub fn wrapping_abs(self) -> Self {
                if self.is_negative() {
                    self.wrapping_neg()
                } else {
                    self
                }
            }
```

But for any integer type you can perform a branchless/const wrapping absolute with

```rust
macro_rules! branchless_abs {
  ($x:expr, $u:ty) => {{
    const SHIFT: u32 = core::mem::size_of::<$u>().wrapping_mul(8).wrapping_sub(1) as u32;
    let mask = ($x as $u).wrapping_shr(SHIFT);
    ($x as $u).wrapping_add(mask) ^ mask
  }};
}
```

This produces code that's only about as bad as the existing `wrapping_abs` at opt-level 0, and is identical at opt-level 2 or 3.

https://rust.godbolt.org/z/PTGeg2

So, I think that we should consider moving `wrapping_abs` to this formulation and making the method `const`.

**Comment by gnzlbg** [comment]
You can replace many `if` and `match` uses in `const fn` by just computing the result of all branches and blending them with the condition. For `wrapping_abs`, that would be:

```rust
pub const fn abs(x: i32) -> i32 {
    let a = ((x < 0) as i32) * x.wrapping_neg();
    let b = ((x <= 3 ) as i32) * x;
    a.wrapping_add(b)
}
```

I find it much simpler to follow that using the shifts and the mask, and the approach can be transferred to many other algorithms.

**Comment by mati865** [comment]
It's const stable for quite some time: https://github.com/rust-lang/rust/blob/86c0b85da98a3c69e0fc9014e36e1c88bd3ae8d7/src/libcore/num/mod.rs#L1596
This issue should be closed.
