### ISSUE TITLE
Documentation: remember the selected crate in search

### ISSUE THREAD

**Issue by pravic** [rust-lang/rust#62929]
Right now it is allowed to select whether we want to search within all crates or in the specific ones (e.g. core, std, etc).

It would be really useful to remember the selected option, because in most cases we want to search in the std crate only.

cc @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
Good idea!

**Comment by pravic** [comment]
Does not work, neither in stable nor nightly.

* Go to https://doc.rust-lang.org/nightly/std/index.html
* Choose the "std" option.
* Type Option, click on it
* We still see the "All crates" on the [result page](https://doc.rust-lang.org/stable/std/option/enum.Option.html).


@GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
Indeed, will take a look quickly.

**Comment by pravic** [comment]
Works perfectly now. Thanks!
