### ISSUE TITLE
`mismatched types` error in Listing 2-4  of the book

### ISSUE THREAD

**Issue by LiyuCode** [rust-lang/rust#62934]
#### Env:
rustc 1.36.0 (a53f9df32 2019-07-03)
Windows 10 64 bits

#### Problem:
In the Listing 2-4 of https://doc.rust-lang.org/book/ch02-00-guessing-game-tutorial.html#comparing-the-guess-to-the-secret-number . It seems the guess is a `String` and secret_number is a `i32`, the code `guess.cmp(&secret_number)` trick `mismatched types` error. 

#### Possible missing:
adding a sentence like the following before the `cmp` one :

```
let guess: u32 = guess.trim().parse()
    .expect("Failed to convert your input into a number");`
```

**Comment by Centril** [comment]
This issue should be filed at https://github.com/rust-lang/book/issues/.

@steveklabnik can you transfer it?

**Comment by LiyuCode** [comment]
my bad.
The error is solved in the later of the book
