### ISSUE TITLE
Documentation: Add a link to the keywords list

### ISSUE THREAD

**Issue by pravic** [rust-lang/rust#62939]
As per [this request](https://github.com/rust-lang/rust/issues/34601#issuecomment-514586053):

Add the following link (`/std/index.html#keywords`) next to the existing ones:

**See all std's items**
Re-exports
Primitive Types
Modules
Macros
[Keywords](https://doc.rust-lang.org/nightly/std/index.html#keywords) <-- this one.

cc @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
Thanks for opening the issue! I'll send the PR tomorrow (but if you want to do it, please go ahead 😃).
