### ISSUE TITLE
Allocation::bytes should be private

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#62931]
The `bytes` field of an [`Allocation`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc/mir/interpret/struct.Allocation.html) is a very subtle one -- the values in there often do not mean what one might intuitively think. First of all the doc comment should probably be improved, but secondly I think we need to make this field private. See https://github.com/rust-lang/rust/pull/62655#discussion_r306753992 for a very subtle bug that happened because it was not private.

Cc @oli-obk @eddyb

**Comment by eddyb** [comment]
Might also help to rename it to something like `unrelocated_bytes`.

**Comment by RalfJung** [comment]
`unrelocated_raw_maybe_initialized_bytes_dont_touch`
