### ISSUE TITLE
Spurious failures when downloading awscli from PyPI

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#62967]
We recently started seeing multiple network failures while downloading awscli from PyPI:

* https://github.com/rust-lang/rust/pull/62960: [log 1](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/4208/logs/707), [log 2](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/4210/logs/722), [log 3](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/4212/logs/709)
* https://github.com/rust-lang/rust/pull/62914: [log 1](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/4276/logs/695)
* https://github.com/rust-lang/rust/pull/62805: [log 1](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/4273/logs/611)

This issue tracks this kind of failure.

**Comment by pietroalbini** [comment]
Opened a PR to add more debug information: https://github.com/rust-lang/rust/pull/63007

**Comment by Centril** [comment]
https://github.com/rust-lang/rust/pull/63025#issuecomment-515599989

**Comment by Centril** [comment]
https://github.com/rust-lang/rust/pull/63025#issuecomment-515603500

**Comment by Centril** [comment]
https://github.com/rust-lang/rust/pull/63028#issuecomment-515628170

**Comment by petrochenkov** [comment]
https://github.com/rust-lang/rust/pull/62550#issuecomment-515670491
