### ISSUE TITLE
Make references to GitHub issues in diagnostics consistent

### ISSUE THREAD

**Issue by shepmaster** [rust-lang/rust#62976]
Some diagnostics include a link to GitHub issues. From the ui testsuite, I found at least these two patterns:

```
 = note: for more information, see https://github.com/rust-lang/rust/issues/51999
```

```
 = note: for more information, see issue #36887 <https://github.com/rust-lang/rust/issues/36887>
```

These should use the same format. My preference is for the latter:

> `see issue #XXXXX <https://github.com/rust-lang/rust/issues/XXXXX>`

/cc @varkor

**Comment by shepmaster** [comment]
General steps:

1. Do some initial review of the *.stderr files in `src/test/ui` and see how many distinct patterns there are. I'd say this requires some knowledge of command line text processing.

1. Identify the sources of each distinct pattern in the source code and unify them.

1. The tests will need to be [updated with the new diagnostics](https://rust-lang.github.io/rustc-guide/tests/adding.html?highlight=bless#editing-and-updating-the-reference-files).

**Comment by punitkoura** [comment]
@shepmaster I'd like to take this up. Seems like a good first contribution to Rust.
Do we have an ETA for this?

**Comment by shepmaster** [comment]
@punitkoura that’s wonderful! ❤️ 

> Do we have an ETA for this?

I don’t think there’s any rush; it was mostly a minor annoyance I had when maintaining the playground.

**Comment by punitkoura** [comment]
I did an initial pass finding the different types of patterns of referencing Github issues. I was able to find 8 different types as follows - 

```bash
(base) C02XF1TZJHD3:rust pkoura$ grep -rh --include "*.stderr" "/issues/" src/test/ui | sed -E 's/\#[0-9]+/#<ISSUE>/g' | sed -E 's/issues\/[0-9]+/issues\/<ISSUE>/g' | sort -u
           see https://github.com/rust-lang/rust/issues/<ISSUE> for more details
   = note: for more information, see https://github.com/rust-lang/rust/issues/<ISSUE>
   = note: for more information, see issue #<ISSUE> <https://github.com/rust-lang/rust/issues/<ISSUE>>
   = note: for more information, see issue https://github.com/rust-lang/rust/issues/<ISSUE>
   = note: the trait is implemented for `()`. Possibly this error has been caused by changes to Rust's type-inference algorithm (see: https://github.com/rust-lang/rust/issues/<ISSUE> for more info). Consider whether you meant to use the type `()` here instead.
error: use of deprecated attribute `no_debug`: the `#[no_debug]` attribute was an experimental feature that has been deprecated due to lack of demand. See https://github.com/rust-lang/rust/issues/<ISSUE>
note: use of `&&` operator here does not actually short circuit due to the const evaluator presently not being able to do control flow. See https://github.com/rust-lang/rust/issues/<ISSUE> for more information.
warning: use of deprecated attribute `no_debug`: the `#[no_debug]` attribute was an experimental feature that has been deprecated due to lack of demand. See https://github.com/rust-lang/rust/issues/<ISSUE>
```

**Comment by punitkoura** [comment]
Will focus now on identifying the sources of these patterns in the source code.

**Comment by eupn** [comment]
@shepmaster please take a look at #63008 PR. @punitkoura, thanks for a list of patterns, you might take a look as well.

**Comment by varkor** [comment]
@punitkoura: if you want help finding another good issue to work on, feel free to send me a message on Discord or Zulip. Any of the E-easy or E-mentor issues are good choices, though.

**Comment by punitkoura** [comment]
Thanks @varkor. I'll be on the lookout 🙂
