### ISSUE TITLE
No way to extract flags arguments from unix::OpenOptionsExt 

### ISSUE THREAD

**Issue by cyphar** [rust-lang/rust#62972]
At the moment, if I want to write an interface that uses `OpenOptions`, but doesn't use the `OpenOptions::open` interface it's simply not possible to implement. The short reason why this is needed is because I am [writing a library](https://github.com/openSUSE/libpathrs) that uses `libc::openat` (which needs the actual flag arguments).

Would it be possible to add something like `OpenOptionsExt::mode` and `OpenOptionsExt::flags` to return the internal flag structure so that it can be used outside the stdlib? Otherwise it's simply not possible to have an ergonomic Rust library that uses interfaces other than `OpenOptions::open` which simply isn't sufficient for the security usecases I have.

**Comment by ExpHP** [comment]
From the point of view of a consumer of crates, I'd actually be surprised to see a crate take `std::fs::OpenOptions` as an argument for its own API; I'd expect them to invent their own types.  As an instance of the Builder pattern, `std::fs::OpenOptions` is not so much a data structure as it is a glorified function with optional/named arguments.

(I'm not saying that this is necessarily a bad idea to add to the standard lib; I'm just surprised by the use case)

**Comment by cyphar** [comment]
Ah okay, maybe I'm not quite familiar enough with what is considered "idiomatic" in Rust API design. The point of view I have from Go and C is that you would want to re-use existing structures (in Go, almost everyone re-uses `os.FileMode` and similar types) so users know what's going on just by looking at the signature -- but if that is not actually the case then we can close this.

**Comment by steveklabnik** [comment]
Triage: it's been a bit over a year. I too would be surprised by this. I wonder what @rust-lang/libs thinks.

**Comment by cyphar** [comment]
Since opening this, I've just opted to take `libc::c_int` directly and not bother with having a Rust-native representation of open flags (since at the end of the day, new open flags can be added at any time and new programs may use them without recompiling the C library). I'm also more proficient at Rust now, and I agree that it seems out of place for the stdlib (it seems like most stdlib types are more like Lego bricks you can use to build wrappers than general-purpose structures you should reuse outside of their original purpose).
