### ISSUE TITLE
rustdoc: Searching for path (including a `::`) does not work

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#63005]
Say I want to find the docs for `Vec::new`, so I search for that. What I get is [this](https://doc.rust-lang.org/nightly/std/?search=Vec%3A%3Anew): almost all of these results are entirely irrelevant.

rustdoc search should understand enough about Rust syntax to handle `::` appropriately.

**Comment by hellow554** [comment]
IIRC this used to work at some time :/

**Comment by CryZe** [comment]
Looks like this is a regression in 1.36:
Here it still works: https://doc.rust-lang.org/1.35.0/std/?search=Vec%3A%3Anew
Here it doesn't: https://doc.rust-lang.org/1.36.0/std/?search=Vec%3A%3Anew

**Comment by RalfJung** [comment]
Well, it works better. It still shows lots of junk even for prior versions.

I mean, when I search for `from_raw_parts` it also does not show every method that contains the word "from". So searching `Vew::new` should not show every method called `new`.

**Comment by kawa-yoiko** [comment]
Hi!

This regression seems to be introduced in #59622. I have a patch in #64094 and would be grateful if anyone interested helps review it.
