### ISSUE TITLE
Lifetime elision rules in `self` types

### ISSUE THREAD

**Issue by taiki-e** [rust-lang/rust#63003]
This issue tracking lifetime elision rules in `self` types.

Here are test cases of elision rules introduced in #61207: https://github.com/rust-lang/rust/blob/d79d13f9e6ca05f2002446addfbd68e63e419cc1/src/test/ui/self/elision/README.md
This rule has already been applied in Rust 1.36 (see #62209).

**Comment by taiki-e** [comment]
Update:
  * #63254 merged, the linked rules are now applied in all versions after 1.36.
  * #63383 adds async fn version of lifetime elision tests.

**Comment by Mark-Simulacrum** [comment]
I think this is no longer relevant -- it's not clear what else we have to track here. In practice the decision to prioritize self types for lifetime elision (even in nested cases. e.g., within `Pin<&mut Self>`) seems to not be one we can readily change at this point (it's pretty widely used I suspect).

My suspicion is that this was tracking the change to the elision rules prior to the decision to change things, but that's now been done.
