### ISSUE TITLE
Missing documentation folder in armv7-unknown-linux-gnueabihf installer (both standalone and using rustup)

### ISSUE THREAD

**Issue by amcajal** [rust-lang/rust#63019]
Tried in Linux raspberrypi 4.4.9-v7 Friday, May 6 2016, armv7l GNU/Linux.  All the steps described below were executed in 23th or July, 2019.

While following the installation guide (ref001, at the bottom of this report), and once Rust is sucessfully installed in the system (stable version, 1.36.0; compiling with rustc works, etc), the following command fails:
`rustup doc`

A quick look at <home_dir>/.rustup/toolchains/stable-armv7-unknown-linux-gnueabihf/share/doc shows that the "/html" folder does not exist (with the index.html file and all the documentation)

Here is the output of executing the "tree" utility in <home_dir>/.rustup/toolchains/stable-armv7-unknown-linux-gnueabihf/share/doc. No html folder is present in neither of the components (also, a "find" command does find any index, just in case)

_+-- cargo
¦   +-- LICENSE-APACHE
¦   +-- LICENSE-MIT
¦   +-- LICENSE-THIRD-PARTY
¦   +-- README.md
+-- clippy
¦   +-- LICENSE-APACHE
¦   +-- LICENSE-MIT
¦   +-- README.md
+-- rust
¦   +-- COPYRIGHT
¦   +-- LICENSE-APACHE
¦   +-- LICENSE-MIT
¦   +-- README.md
+-- rustfmt
    +-- LICENSE-APACHE
    +-- LICENSE-MIT
    +-- README.md_

Removing the toolchain and reinstalling again does not fix the error. Neither adding the documentation manually with the following comand:
`rustup component add rust-docs`

The previous command returns the following error:

_toolchain 'stable-armv7-unknown-linux-gnueabihf' does not contain component 'rust-docs' for target 'stable-armv7-unknown-linux-gnueabihf'_

The standalone install for this very same architecture (ref002) also lacks the /html folder.

This lack of documentation does not happen in other installations (i.e, x86_64-unknown-linux-gnu works well both with rustup and standallone)

Does not know if this lack of documentation in the specified installation is intended or is a bug.
**Could this happen in other installations too?**

### REFERENCES
ref001:
    https://doc.rust-lang.org/book/ch01-01-installation.html

ref002:
    https://forge.rust-lang.org/other-installation-methods.html#standalone

**Comment by jonas-schievink** [comment]
I think we intentionally don't build docs for the non-tier-1 targets to save on CI time, but I could be wrong.

**Comment by Mark-Simulacrum** [comment]
That's correct. IIRC, last time I looked at this it was possible to download the linux docs through rustup so that would be my recommendation. Closing as won't fix.
