### ISSUE TITLE
Builtin macro pattern separator

### ISSUE THREAD

**Issue by Undin** [rust-lang/rust#63039]
Since #62243 builtin macros use `,` as a separator between different patterns. Although, all other macros use `;` instead.
Is it intended change?
This change breaks parser in IntelliJ Rust plugin. Should we adjust our parser or it should be fixed from stdlib side?

**Comment by Undin** [comment]
@petrochenkov

**Comment by petrochenkov** [comment]
The comma is not specific to built-in macros, but rather to unstable `macro` macros in general (which are currently used to define built-in macros).

So, it's reasonable for IntelliJ to adjust its parser if it wants to support unstable code.

**Comment by petrochenkov** [comment]
(Note that the comma itself is pretty questionable, so it's likely that it will be changed into something else, for example no separator at all, once `macro` macros are closer to stabilization.)

**Comment by Undin** [comment]
@petrochenkov Thanks for quick reply!
Then we will adjust our parser
