### ISSUE TITLE
ANSI mode text breakage on Windows PowerShell

### ISSUE THREAD

**Issue by realSmushyTaco** [rust-lang/rust#63060]
1.) In the "Type here to search" box search "Registry Editor" and open the Registry Editor app (If it asks if you want to allow the app to make changes to your device choose "Yes").

2.) Click the drop down arrow for "HKEY_CURRENT_USER" and select the folder named "Console".

3.) In the box where it says "Name", "Type", and "Data" look for the name "VirtualTerminalLevel" (Under "Name" of course). If you don't see "VirtualTerminalLevel" right click in the box, hover over "New" and click "DWORD (32-bit) Value" and give it the name "VirtualTerminalLevel".

4.) Right click on "VirtualTerminalLevel" and click "Modify..." (A window named "Edit DWORD (32-bit) Value" should pop up).

5.) Make sure the "Value name:" is "VirtualTerminalLevel", make sure the "Value data:" is "1", and make sure the "Base" has "Hexadecimal" selected. After all that information has been properly set click "OK" and exit the Registry Editor app (This registry option has to be set to "1" so ANSI mode is enabled by default so text coloring with ANSI escape sequences works by default).

After doing this try running this example code in Windows PowerShell:

fn main() {
    println!("Hello, world!\t\t\tHow's life?");
}

The tabs are completely broken (As seen in picture below)
![Windows PowerShell bug](https://user-images.githubusercontent.com/41648290/62001109-55f53c80-b09d-11e9-80c6-f53aadecb05b.png)

but when run on something else like Command Prompt the tabs work perfectly (As seen in picture below)
![Command Prompt Comparison](https://user-images.githubusercontent.com/41648290/62001123-aff60200-b09d-11e9-8e83-3b64fba47c6f.png)

**Comment by nagisa** [comment]
Extremely unlikely to be a Rust bug. Does this work the way you expect with *equivalent* code written in other languages.

**Comment by realSmushyTaco** [comment]
#include <iostream>

int main()
{
    std::cout << "Hello World!\t\t\tHow's life?";
}

You're right, This C++ code has the exact same issue.
