### ISSUE TITLE
write a self hosted compiler

### ISSUE THREAD

**Issue by catastrop** [rust-lang/rust#63070]

**Comment by Centril** [comment]
Elaborate?

**Comment by catastrop** [comment]
remove LLVM and replace it with tools written in rust.

**Comment by nikic** [comment]
https://github.com/rust-lang/rust/issues?q=is%3Aissue+author%3Acatastrop+is%3Aclosed

Please do not open the same issue again and again. You already opened three other issues on this topic.

**Comment by catastrop** [comment]
........ i am not using rust
