### ISSUE TITLE
Invalid span when emitting a diagnostic note on the top-level module

### ISSUE THREAD

**Issue by jakubadamw** [rust-lang/rust#63091]
While I was investigating a fix for #63064, I noticed one problematic error case, where, as it turns out, the compiler emits a broken span.

```rust
fn main() {}

trait Foo<X = Box<dyn Foo>> {}
```

This is the error I'm getting with the nightly:

```
error[E0391]: cycle detected when processing `Foo::X`
 --> ./src/test/ui/cycle-trait/cycle-trait-default-type-trait-oneliner.rs:3:23
  |
3 | trait Foo<X = Box<dyn Foo>> {}
  |                       ^^^
  |
  = note: ...which again requires processing `Foo::X`, completing the cycle
note: cycle used when collecting item types in top-level module
 --> ./src/test/ui/cycle-trait/cycle-trait-default-type-trait-oneliner.rs:1:1
  |
1 | fn main() {}
  | ^^^^^^^^^
```

The second span should extend to the whole top-level module but instead terminates at the first `{`. This is due to how `SourceMap::def_span()` is defined:

https://github.com/rust-lang/rust/blob/023525dbda35748a10713471b948974b68a1c2cc/src/libsyntax/source_map.rs#L689-L691

This works kind of okay for all item definitions, except for top-level modules. I did try to come up with a way to fix it up in `libsyntax`, but there's no clean way of doing it as it only deals with `Spans`. I figured the place to look at would be:

https://github.com/rust-lang/rust/blob/023525dbda35748a10713471b948974b68a1c2cc/src/librustc/ty/query/plumbing.rs#L313-L315

but I am not at all familiar with the new query system, so decided to file this issue.

**Comment by jakubadamw** [comment]
@eddyb, there's a relevant-looking `FIXME` with your name in that file:
https://github.com/rust-lang/rust/blob/master/src/librustc/ty/query/plumbing.rs#L900-L909

Would you have an idea on a good fix for this? Seemed like an easy one for me at first but then I noticed that it would involve meddling with this plumbing.

**Comment by eddyb** [comment]
That `def_span` is pretty weird, cc @petrochenkov

**Comment by estebank** [comment]
Current output:

```
error[[E0391]](https://doc.rust-lang.org/stable/error_codes/E0391.html): cycle detected when computing type of `Foo::X`
 --> src/main.rs:3:23
  |
3 | trait Foo<X = Box<dyn Foo>> {}
  |                       ^^^
  |
  = note: ...which immediately requires computing type of `Foo::X` again
note: cycle used when collecting item types in top-level module
 --> src/main.rs:1:1
  |
1 | / fn main() {}
2 | |
3 | | trait Foo<X = Box<dyn Foo>> {}
  | |______________________________^
```
