### ISSUE TITLE
Support armv7-unknown-linux-gnueabi and armv7-unknown-linux-musleabi (soft-float variants)

### ISSUE THREAD

**Issue by adrian-budau** [rust-lang/rust#63101]
Currently for armv7 only the hardfloat variants (`armv7-unknown-linux-gnueabihf` and `armv7-unknown-linux-musleabihf`) are supported.

I'll try to open a pull request as this seems to be a small change.

**Comment by hellow554** [comment]
Is there a reason you don't use the `thumbv7*-*` targets instead?

**Comment by adrian-budau** [comment]
None of those targets support the `std`. In particular I require only the `armv7-unknown-linux-muselabi` target, but I mentioned both because it makes sense.

And `arm-unknown-linux-musleabi` doesn't work because some instructions use the `CP15` register which is disabled/does not exist on our hardware (it's not particularly clear for us).
