### ISSUE TITLE
decl macro 2.0 doesn't allow trailing comma

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rust#63102]
```rust
macro abc {
    () => {},
```

([Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=6986bf981691d75da249f136a16e2e07))

Errors:

```
   Compiling playground v0.0.1 (/playground)
error: unexpected end of macro invocation
 --> src/lib.rs:2:14
  |
2 |     () => {},
  |              ^ missing tokens in macro arguments

error: aborting due to previous error

error: Could not compile `playground`.

To learn more, run the command again with --verbose.

```

**Comment by matthewjasper** [comment]
But they do accept a trailing `;`: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=f8bd2841ec49d0222be9ad6124bdd0a4

**Comment by bjorn3** [comment]
Maybe someone forgot to change the trailing `;` into `,` when changing the separating `;` into `,` in the (copied?) parse code?
