### ISSUE TITLE
Should PartialOrd provide impl for Ord to avoid boilerplate?

### ISSUE THREAD

**Issue by oblitum** [rust-lang/rust#63104]
Currently `std` gives the following example in "[How can I implement `Ord`?](https://doc.rust-lang.org/std/cmp/trait.Ord.html#how-can-i-implement-ord)":

```rust
use std::cmp::Ordering;

#[derive(Eq)]
struct Person {
    id: u32,
    name: String,
    height: u32,
}

impl Ord for Person {
    fn cmp(&self, other: &Self) -> Ordering {
        self.height.cmp(&other.height)
    }
}

impl PartialOrd for Person {
    fn partial_cmp(&self, other: &Self) -> Option<Ordering> {
        Some(self.cmp(other))
    }
}

impl PartialEq for Person {
    fn eq(&self, other: &Self) -> bool {
        self.height == other.height
    }
}
```

I was wondering why this boilerplate couldn't be reduced, because it seems clear that in almost all cases of `Ord` implementation, `PartialOrd` implementation can be done in terms of the former.

I suspect this is in its current state because it exists prior to [specialization](https://github.com/rust-lang/rfcs/pull/1210)? If you have the following:

```rust
impl<T: Ord> PartialOrd for T {
    fn partial_cmp(&self, other: &Self) -> Option<Ordering> {
        Some(self.cmp(other))
    }
}
```

Am I right that the `std` example could be updated to:

```rust
use std::cmp::Ordering;

#[derive(Eq)]
struct Person {
    id: u32,
    name: String,
    height: u32,
}

impl Ord for Person {
    fn cmp(&self, other: &Self) -> Ordering {
        self.height.cmp(&other.height)
    }
}

impl PartialEq for Person {
    fn eq(&self, other: &Self) -> bool {
        self.height == other.height
    }
}
```
?

**Comment by shingtaklam1324** [comment]
This conflicts with the existing blanket `impl` in `core`.

```
error[E0119]: conflicting implementations of trait `std::cmp::PartialOrd<&_>` for type `&_`:
 --> src/lib.rs:3:1
  |
3 | impl<T: Ord> PartialOrd for T {
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: conflicting implementation in crate `core`:
          - impl<A, B> std::cmp::PartialOrd<&B> for &A
            where A: std::cmp::PartialOrd<B>, A: ?Sized, B: ?Sized;
```

which removing would be a breaking change (and very unlikely considering how commonly used that blanket `impl` is)

**Comment by oblitum** [comment]
@shingtaklam1324 what this is basically saying is that given `impl<T: Ord>` is too general that it also covers references, and there's an specialization for references already, then the two collide.

**Comment by shingtaklam1324** [comment]
Pretty much.

`PartialOrd<Rhs=Self>`, so replace `B` with `A` in the error.

Essentially what `rustc` is complaining about is that there are now two implementations of the same thing

Consider a type `A: Ord`

1. First way
    1. since `Ord: PartialOrd`
    2. `A` must `impl PartialOrd`
    3. `impl PartialOrd<&A>` from `core`'s `impl<A, B> std::cmp::PartialOrd<&B> for &A`
2. Second Way
    1. `impl Ord<&A>` from `core`'s `impl<'_, A> Ord for &'_ A`
    2. `impl PartialOrd<&A>` from your `impl<T: Ord> PartialOrd for T`

**Comment by scottmcm** [comment]
This has been a wish for a _long_ time (such as https://github.com/rust-lang/rfcs/pull/1028).  I think it's better tracked in the RFCs repo, since it depends on languages changes, and is plausibly just a requirement to be addressed in a specialization RFC.  (Or a different change, which would also take an RFC.)
