### ISSUE TITLE
"Try invoking the function" hint

### ISSUE THREAD

**Issue by Patryk27** [rust-lang/rust#63100]
Hi,

Let's consider following code:
```rust
fn foo() -> usize {
    0
}

fn bar(i: usize) {
    
}

fn main() {
    bar(foo);
}
```
Right now it fails with the `expected usize, found fn item` message - I think it would be helpful if compiler bragged about missing parentheses when function's return type matches expected type:
```rust
fn main() {
    bar(foo);
//      ^^^ expected usize, found fn item
//          hint: try invoking the function: foo()
}
```
It may even help a little bit when dealing with `async` functions - recently I've written:
```rust
async fn foo() {
    
}

fn bar(f: impl Future<Output=()>) {
    
}

fn main() {
    bar(foo);
}
```
... and it took me a few minutes to notice that what I actually wanted was `bar(foo())`.

**Comment by cramertj** [comment]
@Centril why was this tagged async-await?

**Comment by Centril** [comment]
> @Centril why was this tagged async-await?

> It may even help a little bit when dealing with async functions - recently I've written:

**Comment by cramertj** [comment]
I don't think that makes this an async/await issue in any way, though. :woman_shrugging:

**Comment by gilescope** [comment]
It's a great suggestion either way. Going to take a crack at it if I may?
@rustbot claim

**Comment by gilescope** [comment]
Move to close this as PR #63337 now merged in nightly fixes this:

```
   |
2  | fn foo() -> usize {
   | ----------------- fn() -> usize {foo} defined here
...
11 |     bar(foo);
   |         ^^^
   |         |
   |         expected usize, found fn item
   |         help: use parentheses to call this function: `foo()`
   |
   = note: expected type `usize`
              found type `fn() -> usize {foo}`
```

**Comment by gilescope** [comment]
@Centril thoughts?

**Comment by Centril** [comment]
The message for async/await is still bad:

```

error[E0277]: the trait bound `fn() -> impl std::future::Future {foo}: std::future::Future` is not satisfied
  --> src/main.rs:10:5
   |
10 |     bar(foo);
   |     ^^^ the trait `std::future::Future` is not implemented for `fn() -> impl std::future::Future {foo}`
   |
note: required by `bar`
  --> src/main.rs:7:1
   |
7  | fn bar(f: impl Future<Output = ()>) {}
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Leaving this up to @estebank

**Comment by Patryk27** [comment]
IMO the `{foo} defined here` part looks weird (why brackets?) - how about:
```
2  | fn foo() -> usize {
   | ----------------- function `fn() -> usize` (named `foo`) defined here
```

**Comment by estebank** [comment]
@Patryk27 I feel like `fn foo() -> usize` could also work and be more natural. At the same time, I'd like to unify how we refer to functions and closures (currently `[closure@file.rs:LL:CC]`), and I feel that the braces style is would be suitable for them: `fn(_) -> _ {file.rs:LL::CC}`.

**Comment by Patryk27** [comment]
@estebank Thanks, I understand - I'm not certain about curly braces in this position, since it changes their meaning (from denoting block to denoting location, depending on whether it is part of code block or message) and thus, to me, they are kinda confusing.

IMO the `fn(_) -> _ [file.rs:LL:CC]` construct could be more legible, since brackets are not usually set together with functions (contrary to curly braces), so they stand out more.

**Comment by estebank** [comment]
https://github.com/rust-lang/rust/pull/63870:

```
error[E0277]: the trait bound `fn() -> impl std::future::Future {foo}: std::future::Future` is not satisfied
  --> $DIR/async-fn-ctor-passed-as-arg-where-it-should-have-been-called.rs:9:5
   |
LL | fn bar(f: impl Future<Output=()>) {}
   | --------------------------------- required by `bar`
...
LL |     bar(foo);
   |     ^^^ the trait `std::future::Future` is not implemented for `fn() -> impl std::future::Future {foo}`
   |
   = help: it looks like you forgot to use parentheses to call the function: `foo()`
```

😊
