### ISSUE TITLE
Tracking issue for div_duration

### ISSUE THREAD

**Issue by newpavlov** [rust-lang/rust#63139]
Rust PR: #62756

This feature adds the following methods to `Duration`:
- `div_duration_f64(self, rhs: Duration) -> f64`
- `div_duration_f32(self, rhs: Duration) -> f32`

**Comment by jhpratt** [comment]
Anything in particular holding up the stabilization here? The implementation is trivial and docs lgtm.

**Comment by DemiMarie-parity** [comment]
I would like to add methods that return an exact `u128`, but that can wait.

**Comment by KodrAus** [comment]
These methods are a little odd, but seem reasonable to me following the example given: https://github.com/rust-lang/rust/pull/62756#issuecomment-516060456

**Comment by Rua** [comment]
Given how straightforward these methods are, I don't think there's any problem stabilising them?

**Comment by KodrAus** [comment]
They're straightforward in implementation, but conceptually tricky at a glance. I think the docs will need some fleshing out before stabilizing but I don't have any other concerns if somebody wants to write a PR!

**Comment by workingjubilee** [comment]
This needs more testing with various interesting float values, and should not be stabilized without such.

**Comment by Xaeroxe** [comment]
https://github.com/rust-lang/rust/pull/106570 tests added
