### ISSUE TITLE
Compute all argument-less const fns via `eval_const` to cache their evaluation

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#63130]
cc https://github.com/rust-lang/rust/pull/61626#issuecomment-514719862

We are already doing that for nullary intrinsics (#61626), it seems like we could get some perf gains from this, even cross crate.

**Comment by RalfJung** [comment]
Does this have any consequences re: promotion or const-checking? The rules for that are currently difference for consts and const fns.

**Comment by oli-obk** [comment]
No, this just adds caching to zero arg const fns, there's no language change together with it.

**Comment by RalfJung** [comment]
@oli-obk I think this [has been implemented](https://github.com/rust-lang/rust/blob/04e7f96dd89b1f0ad615dff1c85d11d4c4c64cb4/src/librustc_mir/const_eval/machine.rs#L27) in the mean time? Can this issue be closed?
