### ISSUE TITLE
Rustdoc search results truncated

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rust#63138]
https://docs.rs/cranelift-codegen/0.37.0/cranelift_codegen/ir/trait.InstBuilder.html?search=I32X

![image](https://user-images.githubusercontent.com/17426603/62130746-f768d200-b2d9-11e9-89d9-b9201ff5dda2.png)

Reason: `max-height: calc(100vh - 32px);` on parent `<div class="rustdoc trait container-rustdoc">`.

**Comment by GuillaumeGomez** [comment]
It was a docs.rs bug and has been fixed by https://github.com/rust-lang/docs.rs/pull/389
