### ISSUE TITLE
Using proc macros through a re-exported crate raises rustc_private unstability error

### ISSUE THREAD

**Issue by pustaczek** [rust-lang/rust#63142]
When a library A depends on a library B, which re-exports a library C that (re-?)exports procedural macros, using them in A through the re-export in B may result in an E0658 error.

I tried this code:

```rust
// src/lib.rs

use inner::serde::Deserialize;

#[derive(Deserialize)]
pub struct S;
```
```rust
/// inner/src/lib.rs

pub use serde;
```

I expected to see this happen: code compiles successfully.

Instead, this happened: the compilation failed with the following error message:
```
    Checking wololo v0.1.0 (/home/matcegla/wololo)
error[E0658]: use of unstable library feature 'rustc_private': this crate is being loaded from the sysroot, an unstable location; did you mean to load this crate from crates.io via `Cargo.toml` instead?
 --> src/lib.rs:3:10
  |
3 | #[derive(Deserialize)]
  |          ^^^^^^^^^^^
  |
  = note: for more information, see https://github.com/rust-lang/rust/issues/27812
  = help: add `#![feature(rustc_private)]` to the crate attributes to enable

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: Could not compile `wololo`.

To learn more, run the command again with --verbose.
```

## Meta

`rustc --version --verbose`:
```
rustc 1.38.0-nightly (07e0c3651 2019-07-16)
binary: rustc
commit-hash: 07e0c3651ce2a7b326f7678e135d8d5bbbbe5d18
commit-date: 2019-07-16
host: x86_64-unknown-linux-gnu
release: 1.38.0-nightly
LLVM version: 8.0
```

**Comment by Mark-Simulacrum** [comment]
This is just a case of poor diagnostics. Macros today have no way of knowing that they should import from `inner::serde` rather than `serde`, so you're seeing the effects of use-paths directed into the sysroot. If we didn't use serde in the compiler, the message would instead be "no crate serde found."

I think as a standalone issue this is unlikely to get fixed (as it's not _really_ a bug). Closing.
