### ISSUE TITLE
Generic type parameters used in expression?

### ISSUE THREAD

**Issue by schungx** [rust-lang/rust#63140]
Is there a way to use a generic type parameter in an expression?

For example:

~~~rust
fn SomeGenericFunc<T>() {
    if T : Display {
        // Here we know T implements Display
        println!("{}", T);
    } else if T : Debug {
        // Here we know T implements Debug
        println!("{:?}", T);
    } else {
        println!("Hey, don't know how to print!");
    }
}
~~~

Obviously, during actual code generation when instantiating the actual types, the irrelevant code branches can be safely omitted.

**Comment by jonas-schievink** [comment]
Hi! This issue tracker is mainly meant for bug reports and concrete, small feature requests. Questions like this are better asked in the user forum at https://users.rust-lang.org/ or on [one of the chat platforms](https://www.rust-lang.org/community) used by the Rust community.
