### ISSUE TITLE
lint of unnecessary parentheses around `if` condition may case error

### ISSUE THREAD

**Issue by bravomikekilo** [rust-lang/rust#63156]
when unnecessary parentheses is removed, may lack a whitespace between `if` and `expr`.

example
`if(is_prime) {println!("hello")};`
while be replaced to
`ifis_prime {println!("hello")};`

Maybe we should replare `(expr)` with a pair of whitespace around `expr`, instead of just `expr`;

**Comment by bravomikekilo** [comment]
I am working on it.

**Comment by etherpan** [comment]
Previous code
if **(fee > 4)** {
        stake_pool.fee = 4;    
    } else {
        stake_pool.fee = fee;
    }
    
Updated code

if **fee > 4** {
        stake_pool.fee = 4;    
    } else {
        stake_pool.fee = fee;
    }
