### ISSUE TITLE
Toolstate for Linux not correctly published

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#63190]
The toolstate for Linux at https://rust-lang-nursery.github.io/rust-toolstate/ claims that tools are still failing. E.g., https://github.com/rust-lang/rust/pull/63141 landed, but only the Windows toolstate was considered fixed after that.

Looks like something is breaking publishing Linux toolstate?

Cc @pietroalbini @kennytm

**Comment by pietroalbini** [comment]
Apparently the publish environment variable is not properly propagated to the Linux builder...

**Comment by RalfJung** [comment]
The [build log](https://dev.azure.com/rust-lang/rust/_build/results?buildId=4796) for that Miri PR shows the right JSON:
```
{"nomicon":"test-pass","rls":"test-pass","embedded-book":"test-pass","edition-guide":"test-pass","rustbook":"test-fail","clippy-driver":"test-pass","miri":"test-pass","reference":"test-pass","book":"test-pass","rust-by-example":"test-pass","rustfmt":"test-pass"}
```
I cannot see an error message anywhere.
