### ISSUE TITLE
document some diagnostics for min TAIT in stabilization report

### ISSUE THREAD

**Issue by varkor** [rust-lang/rust#63205]
This issue was repurposed. It now refers to documenting the diagnostics for various errors and other cases in the [`min_type_alias_impl_trait` stabilization report](https://hackmd.io/o9KO-D8aSb6bJgQ1froVTA). -- @nikomatsakis 

~~After https://github.com/rust-lang/rust/issues/63063 and in preparation for stabilising type alias `impl Trait` (https://github.com/rust-lang/rust/issues/63063), we'll want to look at the diagnostics as a whole (especially regarding the "opaque type" terminology) as they're definitely subpar at the moment.~~

~~sub-issues:~~
~~* https://github.com/rust-lang/rust/issues/66723~~

~~cc @Centril, @estebank~~

**Comment by oli-obk** [comment]
We fixed the only sub-issue of this and are generally fairly on top of the diagnostics around type alias impl trait
