### ISSUE TITLE
Formal parameter attributes won't be passed into proc-macro

### ISSUE THREAD

**Issue by Hexilee** [rust-lang/rust#63210]
As this [example repo](https://github.com/Hexilee/params-attribute-example/blob/master/proc-macro-tests/rename_params.rs)

This is the example proc-macro:

```rust
extern crate proc_macro;
use proc_macro::TokenStream;

#[proc_macro_attribute]
pub fn rename_params(_args: TokenStream, input: TokenStream) -> TokenStream {
    println!("{}", &input);
    input
}
```

This is the test:

```rust
#![feature(param_attrs)]
use params_attribute_example::rename_params;

#[rename_params]
fn hello(a: i32, #[val] b: i32) {}
```

Run `cargo expand --test rename-params`，both of `println` result and `expand` result are: 

```rust
fn hello(a: i32, b: i32) {}
```

Formal parameter attributes disappear in proc-macro.

Toolchain: `nightly-x86_64-apple-darwin(8a58268b5 2019-07-31)`

**Comment by Centril** [comment]
cc @c410-f3r @petrochenkov  https://github.com/rust-lang/rust/issues/60406

**Comment by Centril** [comment]
I have a fix in https://github.com/rust-lang/rust/pull/63212.
