### ISSUE TITLE
Fix test style in unused parentheses lint test

### ISSUE THREAD

**Issue by bravomikekilo** [rust-lang/rust#63237]
Update test file to use `#![deny(unused_parens)]` + `//~ ERROR` annotations instead of `pretty-json` (see https://rust-lang.github.io/rustc-guide/tests/adding.html)

The files need to update are:
- `test/lint/unused_parens_json_suggestions.rs`
- `test/lint/used_parens_remove_json_suggestion.rs`

This issue has been assigned to @polyedre via [this comment](https://github.com/rust-lang/rust/issues/63237#issuecomment-543196226).

**Comment by JohnTitor** [comment]
is the correct file name `use_suggestion_json.rs`, not `used_parens_remove_json_suggestion.rs`?

And what about this comment?
https://github.com/rust-lang/rust/blob/2c13edcd9d64f640261c488e04459733313f3843/src/test/ui/lint/unused_parens_json_suggestion.rs#L4-L8

**Comment by polyedre** [comment]
Is the problem fixed ? If not, I would like to work on it !

**Comment by JohnTitor** [comment]
@polyedre WIP PR has been closed due to inactivity so you can work on this.

**Comment by polyedre** [comment]
@JohnTitor I would like to be assigned to this issue. Am I supposed to do a new pull request ?

**Comment by JohnTitor** [comment]
@rustbot claim @polyedre

Go ahead!

**Comment by JohnTitor** [comment]
Hmm, it's odd, anyway, you can assign the issue to yourself by comment `@rustbot claim`
