### ISSUE TITLE
"can't qualify macro invocation with `pub`" error can fire without any macro invocations

### ISSUE THREAD

**Issue by little-arhat** [rust-lang/rust#63255]
With #63180 in effect, code using `existential type` produces confusing error:

```
error: can't qualify macro invocation with `pub`
 --> src/mixer.rs:6:1
  |
6 | pub existential type T: MotorCtrl;
  | ^^^
  |
  = help: try adjusting the macro to put `pub` inside the invocation
```

The actual fix is to change

`pub existential type T: MotorCtrl;` to `pub type T = impl MotorCtrl;` and to enable `type_alias_impl_trait` feature, instead of `existential_type`.

**Comment by Centril** [comment]
I don't think it is worth having special cased diagnostics for `existential type`.

**Comment by little-arhat** [comment]
@Centril true, it wasn't stabilized anyway. But I think it's good to have this issue here to help people googling an error.

**Comment by jonas-schievink** [comment]
The same issue occurs when using `pub auto unsafe trait` instead of the correct `pub unsafe auto trait`:

```rust
pub auto unsafe trait SingleCoreSend {}
```

```
error: can't qualify macro invocation with `pub`
 --> src/lib.rs:1:1
  |
1 | pub auto unsafe trait SingleCoreSend {}
  | ^^^
  |
  = help: try adjusting the macro to put `pub` inside the invocation

error: expected one of `!` or `::`, found `unsafe`
 --> src/lib.rs:1:10
  |
1 | pub auto unsafe trait SingleCoreSend {}
  |          ^^^^^^ expected one of `!` or `::` here

error: aborting due to 2 previous errors
```

Note that this happens even when the feature is turned off.

**Comment by birkenfeld** [comment]
Also seen with functions and a simple typo:
```
pub asyn fn test() {}
```
Error:
```
error: can't qualify macro invocation with `pub`
 --> src/main.rs:1:1
  |
1 | pub asyn fn test() {}
  | ^^^
  |
  = help: try adjusting the macro to put `pub` inside the invocation

error: expected one of `!` or `::`, found keyword `fn`
 --> src/main.rs:1:10
  |
1 | pub asyn fn test() {}
  |          ^^ expected one of `!` or `::`
```

I'm not sure how the parser gets the idea that a macro was coming there...

**Comment by ChrisJefferson** [comment]
Just as another practical example, I wrote (having a C++ brain hiccup) `pub typedef mytype = usize;`, which produced the same message about macros and confused me until I found `typedef` isn't a macro, or in fact anything.

**Comment by gihrig** [comment]
> I don't think it is worth having special cased diagnostics for existential type.

But the error goes well beyond `existential`:

A missing `const` will trigger this error:

```rust
pub mod DEFAULT_BBOX {
  pub mod _northEast {
    pub lat: f64 = 48.82099347817258;
    pub lng: f64 = 9.299583435058596;
  }
```
```bash
error: can't qualify macro invocation with `pub`
  --> src/constants/Map.rs:11:5
   |
11 |     pub lat: f64 = 48.82099347817258;
   |     ^^^
   |
   = help: try adjusting the macro to put `pub` inside the invocation
```

The problem of course, is that the correct code is:

```rust
    pub const lat: f64 = ...
```

$ rustc -V
rustc 1.43.0-nightly (58b834344 2020-02-05)

macOS 10.14.6

**Comment by Centril** [comment]
Today you get:
```rust
error: visibility `pub` is not followed by an item
 --> src/lib.rs:1:1
  |
1 | pub existential type T: MotorCtrl;
  | ^^^ the visibility
  |
  = help: you likely meant to define an item, e.g., `pub fn foo() {}`

error: expected item, found `existential`
 --> src/lib.rs:1:5
  |
1 | pub existential type T: MotorCtrl;
  |     ^^^^^^^^^^^ expected item
```
...which seems good enough.
