### ISSUE TITLE
The standard library should have a basic future runtime

### ISSUE THREAD

**Issue by lachlansneff** [rust-lang/rust#63267]
While libraries like Tokio and runtime exist, there's a real discovery problem for new users. And importing a large library like those can increase compile time a bunch and whatnot. 

For ease of use, I'm proposing that the standard library contains a simple future runtime. It doesn't have to be too complex or too specialized; if users need something that optimizes more for their use case, they can import a crate.

**Comment by Mark-Simulacrum** [comment]
This needs to be an RFC, as it's a major addition to the standard library. If someone (perhaps you!) wants to pursue this, please follow the RFC process here https://github.com/rust-lang/rfcs#before-creating-an-rfc.

**Comment by lachlansneff** [comment]
@Mark-Simulacrum  I mainly opened this issue as a place for discussion, I am happy to create an RFC as well.

**Comment by Mark-Simulacrum** [comment]
Discussion for such things is best placed on internals.rust-lang.org; this is an issue tracker primarily.
