### ISSUE TITLE
rustdoc: `DerefMut` methods are missing from sidebar

### ISSUE THREAD

**Issue by lnicola** [rust-lang/rust#63276]
Take a look at https://doc.rust-lang.org/std/vec/struct.Vec.html. The sidebar has `Deref<Target=[T]>`, but not `DerefMut`, so methods like `sort` are missing.

**Comment by GuillaumeGomez** [comment]
Thanks for reporting it. Since another issue is already open, I'll close this one.

Duplicates of https://github.com/rust-lang/rust/issues/60326.

**Comment by lnicola** [comment]
@GuillaumeGomez do you happen to know when the documentation published on https://doc.rust-lang.org/std/vec/struct.Vec.html will get updated?

**Comment by leo60228** [comment]
@lnicola It probably won't be fixed there until the next stable release, but it's already fixed on the nightly docs: https://doc.rust-lang.org/nightly/std/vec/struct.Vec.html

**Comment by lnicola** [comment]
@leo60228 thanks, I thought https://doc.rust-lang.org/std/vec/struct.Vec.html was the location of the nightly docs :smile:.

I suppose it's intentional that the `DerefMut` methods show up under `Deref`?

**Comment by GuillaumeGomez** [comment]
Yes it is.
