### ISSUE TITLE
Different error messages between async and regular functions

### ISSUE THREAD

**Issue by Patryk27** [rust-lang/rust#63277]
Hi,

Let's consider following code:
```rust
fn foo() -> Result<bool, ()> {
    unimplemented!()
}

fn bar() -> Result<(), ()> {
    foo()?;
    ()
}
```
There's an error in the penultimate line - it should say `Ok(())` and Rust correctly helps to spot the mistake:
```
  |
7 | fn bar() -> Result<(), ()> {
  |             -------------- expected `std::result::Result<(), ()>` because of return type
8 |     foo()?;
9 |     ()
  |     ^^ expected enum `std::result::Result`, found ()
  |
  = note: expected type `std::result::Result<(), ()>`
             found type `()`
```
The situation changes a bit when we switch to async functions:

```rust
#![feature(async_await)]

async fn foo() -> Result<bool, ()> {
    unimplemented!()
}

async fn bar() -> Result<(), ()> {
    foo().await?;
    ()
}
```
The error message now says `the '?' operator can only be used in a function that returns 'Result' or 'Option'`, which is totally unhelpful, since the function *is* (or at least *should be*) returning a `Result`, according to its signature.

It seems that, when dispatching error messages, the actual return types have precedence over signatures in async functions, but it's exactly the other way around in regular functions, which leads to kinda unexpected and confusing error messages.

**Comment by Patryk27** [comment]
For reference, it seems it's a duplicate of: https://github.com/rust-lang/rust/issues/54326.

**Comment by cramertj** [comment]
Closing as duplicate.
