### ISSUE TITLE
How to do Zero-fill right shift in rust?

### ISSUE THREAD

**Issue by ZhouHansen** [rust-lang/rust#63278]
```rust
fn main(){
  let i:i32 = -9;
  println!("{}", i >>> 3)
}
```

**Comment by jonas-schievink** [comment]
Hi! This issue tracker is mainly meant for bug reports and concrete, small feature requests. Questions like this are better asked in the user forum at https://users.rust-lang.org/ or on [one of the chat platforms](https://www.rust-lang.org/community) used by the Rust community.
