### ISSUE TITLE
Is the order of procedural macro attribute execution guaranteed per item?

### ISSUE THREAD

**Issue by azriel91** [rust-lang/rust#63336]
Hiya, is there an intentional guarantee that procedural macro attributes are executed outward-in per item? To illustrate ([repo](https://github.com/azriel91/proc_macro_attribute_order)):

```rust
// attr_* appends a new field to the struct

#[attr_0(u8)]
#[attr_1(u16)]
#[attr_2(u32)]
struct Hello;

#[attr_2(u32)]
#[attr_1(u16)]
#[attr_0(u8)]
struct Hello2;
```

generates:

```rust
struct Hello(u8, u16, u32);
struct Hello2(u32, u16, u8);
```

That's the behaviour, but I'd like to confirm if I can rely on it (and if it should be documented).

https://github.com/rust-lang/rust/issues/56058 may be related, but I haven't checked the details whether the "each invocation" is per procedural macro (and potentially losing the order guarantee).

**Comment by Centril** [comment]
cc @eddyb @petrochenkov 

-- To my knowledge we make no guarantees about the execution order of proc macro expansion.

**Comment by ehuss** [comment]
According to https://github.com/rust-lang-nursery/reference/issues/578#issuecomment-485373291 it is not defined.

**Comment by Mark-Simulacrum** [comment]
That issue seems canonical enough and has a reply from @eddyb so I'm going to close this in favor of the reference (where such things should ultimately be documented anyway, I think).

**Comment by Nemo157** [comment]
This isn't really about the _execution order_ of proc-macro-attributes, but rather the _application order_. Even if all the macros from the example were deterministic and side-effect free the order in which they are applied to the AST will affect the final result.

(But still, this might be better as a reference issue).
