### ISSUE TITLE
Warn about path change for `#[doc(include)]`

### ISSUE THREAD

**Issue by hdevalence** [rust-lang/rust#63335]
Recently (https://github.com/rust-lang/rust/pull/60938) the path root for `#[doc(include)]` files was changed.   This change makes a lot of sense, and it's not difficult to update, but there is now a situation where code using the old path roots won't compile on new nightlies and vice versa.

Because the error message is just that the file is missing, there's a lot of confusion (e.g., https://github.com/dalek-cryptography/bulletproofs/pull/290,  https://github.com/dalek-cryptography/bulletproofs/pull/282, https://github.com/dalek-cryptography/bulletproofs/issues/292, https://github.com/dalek-cryptography/curve25519-dalek/pull/269, https://github.com/dalek-cryptography/curve25519-dalek/pull/275) about build failures.

Would it be possible to add a warning to the "file missing" error for `#[doc(include)]` noting that the path changed recently?  This won't help the case of compiling new-doc-paths-on-old-nightlies but might give a hint about what's going on when there's a build failure with old-doc-paths-on-new-nightlies.

**Comment by jyn514** [comment]
This changed over 15 months ago and I plan to deprecate doc(include) on the next beta bump (in favor of https://github.com/rust-lang/rust/issues/78835), so I don't think it makes sense to add at this point. I'm sorry that this change was not communicated clearly at the time.
