### ISSUE TITLE
Rust execute the SHELL command 'git --no-pager log --author=authorname' cannot get output

### ISSUE THREAD

**Issue by ZihoRo** [rust-lang/rust#63344]

**Comment by ZihoRo** [comment]
If there is no parameter '--author=authorname' I can get output. But execute "git --no-pager log --pretty=format:'%ad,%d %s' --since='2019-01-01' --until='2019-06-30' --date =format: '%Y-%m-%d %H:%M:%S' --all", each line will be wrapped by ' character, and executed directly in the terminal is no ' character package

**Comment by ZihoRo** [comment]
I don't know if this question should belong to rust or git.

The above comments are from Google Translate

**Comment by Mark-Simulacrum** [comment]
This is probably better suited for users.rust-lang.org or a similar forum; I'm going to close on the assumption that this isn't a bug in std. It would be worthwhile to include a minimal code example that reproduces your unexpected behavior.
