### ISSUE TITLE
`std::iter::count` and `std::iter::count_with` functions

### ISSUE THREAD

**Issue by alexreg** [rust-lang/rust#63357]
It would be great to have these functions, which would behave similarly to the `once` / `once_with` and `repeat` / `repeat_with` functions, except they would iterate a fixed number of times (given by a `usize`) instead of just once/infinitely.

**Comment by KrishnaSannasi** [comment]
So, like `repeat(...).take(n)`? This doesn't seem useful to me.

**Comment by ExpHP** [comment]
I've wanted this myself a number of times.

The problem with `repeat(...).take(n)` is that it doesn't implement `ExactSizeIterator` or `DoubleEndedIterator`.

**Comment by KrishnaSannasi** [comment]
Ok, that seems like a good reason to do this.

**Comment by clarfon** [comment]
Perhaps an `InfiniteIterator` trait could be added to help in these cases? That way, `repeat(x).take(n)` is always `ExacpSizeIterator`.

**Comment by alexreg** [comment]
> The problem with `repeat(...).take(n)` is that it doesn't implement `ExactSizeIterator` or `DoubleEndedIterator`.

Exactly.

**Comment by Centril** [comment]
> Perhaps an `InfiniteIterator` trait could be added to help in these cases? That way, `repeat(x).take(n)` is always `ExactSizeIterator`.

I believe this requires mutually exclusive traits.

**Comment by Mark-Simulacrum** [comment]
`(0..20).map(|_| ...)` is how I've always done this; it works well, is fairly obvious after looking at it, and I'm confident I'll never reach for an import since this exists. Maybe we can document this pattern instead of adding more types and functions?

**Comment by alexreg** [comment]
@Mark-Simulacrum Sure, that's the obvious alternative... but has anyone profiled that vs. a more direct approach? Also, see the above comment vs. issues with trait implementations.

**Comment by Mark-Simulacrum** [comment]
Ranges are, in fact, double ended, exact, and TrustedLen. We probably should add Fused to that (looks like it's just an accidental omission). Map preserves all of those.

Performance wise, I'm not sure. I suspect you can't really do better than Range because you basically are just doing what it is...

**Comment by alexreg** [comment]
Possibly. I'd still be interested in benchmarks.

**Comment by steveklabnik** [comment]
Triage: it's been a year. If anyone is interested in implementing this and doing benchmarks, please send in a pull request if it is indeed better than the map. Thanks.
