### ISSUE TITLE
Intra-rustdoc links do not work for all primitives

### ISSUE THREAD

**Issue by nixpulvis** [rust-lang/rust#63351]
Coming from the tracking issue #43466.

I'm trying to link to [`slice::rotate_left`](https://doc.rust-lang.org/std/primitive.slice.html#method.rotate_left) and it doesn't seem to be supported I tested [`pointer::is_null`](https://doc.rust-lang.org/stable/std/primitive.pointer.html#method.is_null) as well, to test if it's just polymorphic primitives, and it seems that might be the issue, since it also doesn't work as a intra-link.

/cc @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
I'll recheck it and see what's going on.

**Comment by GuillaumeGomez** [comment]
The problem here is that, even if being primitive types, they're not considered as is in the compiler since they're generic. Therefore, the problem might be way more complicated to fix considering I have no idea how to link to a slice or a pointer...

**Comment by nixpulvis** [comment]
Yea looking at the code, it seems things might stem from here:

https://github.com/rust-lang/rust/blob/60960a260f7b5c695fd0717311d72ce62dd4eb43/src/librustc_resolve/lib.rs#L770-L793

Based on this and the [list of primatives in the STD docs](https://doc.rust-lang.org/std/#primitives), I'm guessing the following is a complete list of generic (or otherwise unimplemented) primitives:

- `array`
- `fn`
- `pointer`
- `reference`
- `slice`
- `tuple`
- `unit`
- `never`

This seems to be more broad than just generics however, since the `unit` type is `()`. The issue is with types with "names" different from their syntax. (`()` vs `unit`).

I'm not sure I have anything super useful to add however.

**Comment by GuillaumeGomez** [comment]
The solution would be to "simply"  try to check the current path and if not working, try to check if the first part of the path can be considered as primitive type (such as slice or pointer) and retry with this change. We already do something similar in some cases.

**Comment by jyn514** [comment]
> The solution would be to "simply" try to check the current path and if not working, try to check if the first part of the path can be considered as primitive type (such as slice or pointer) and retry with this change.

I'm not sure it's that simple. If you look at https://doc.rust-lang.org/nightly/nightly-rustc/rustc_hir/enum.PrimTy.html, none of the primitives you listed are present. Looking at https://doc.rust-lang.org/nightly/nightly-rustc/rustc_hir/def/enum.Res.html, there isn't even a `Res` for all the types - `!` and `()` are conspicuously absent.

> The issue seems to affect types with "names" different from their syntax, e.g. () vs unit.

This isn't the issue, `fn` also doesn't work. The issue is that these are missing from `PrimTy`.

**Comment by jyn514** [comment]
A possible solution is to move from `Res` to `Ty` as the canonical way to look up primitives, using [`TyCtxt::type_of`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/struct.TyCtxt.html#method.type_of). Everything except primitives could keep using Res, it's only primitives that would have to change.

**Comment by jyn514** [comment]
Yeah no I take it back, `resolve()` immediately returns the `Res` and so you can no longer distinguish it from ADTs. So this really does need a full refactor of `collect_intra_doc_links`.

**Comment by jyn514** [comment]
Ok, the bits that are actually used from `Res` are:
- For primitive types, just the URL fragment from `is_primitive` and the fact that it's a primitive
- For ADTs, it calls `register_res` and stores that `DefId`. It also stores a URL fragment but I'm pretty sure that's just user defined and not tied to the `Res`.
  + `register_res` which mostly just calls

```rust
    inline::record_extern_fqn(cx, did, kind);
    if let TypeKind::Trait = kind {
        inline::record_extern_trait(cx, did);
    }
```

The URL fragment is independent of `Res`. The fact that it's a primitive is independent of `Res`. The `Kind` is somewhat tied to the `Res`, but you could get the same info from a `Ty` or `TyKind`. However, I don't see an easy way to go from an ADT to a `TyKind` or `Ty`.

So, this scheme might work:

```rust
enum Resolution {
    Def(DefKind, DefId),  // replaces `Res::Def`
    Primitive { fragment: String },
}
```

Hmm ... that doesn't seem so bad.

**Comment by clarfonthey** [comment]
Not sure if this is 100% related, but if you auto-link `[\`()\`]` or `[!]` it doesn't go to `tuple` or `never` as expected.

**Comment by jyn514** [comment]
@clarfonthey correct, that's this issue.
