### ISSUE TITLE
ICE when iterating over a `u16` range whose bounds exceed 64k

### ISSUE THREAD

**Issue by apoelstra** [rust-lang/rust#63364]
An ICE is observable with this code:
```
fn part(_: u16) -> u32 {
    1
}

fn main() {
    for n in 100_000.. {
        let _ = part(n);
    }
}
```
```
thread 'rustc' panicked at 'index out of bounds: the len is 1 but the index is 1', src/librustc_lint/types.rs:79:12
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```
Changing `part` to take a `u32` rather than `u16` makes the ICE go away.

[Playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=66d0df88b40762a0c82eab85850a26d5)

**Comment by thepowersgang** [comment]
Investigation shows that `65536` will trigger the ICE, while `65535` will not

**Comment by estebank** [comment]
Introduced in https://github.com/rust-lang/rust/commit/13962aff37bbe23e1c9063e2298318e1a9da8af2#diff-d4213b0b0cef0ac9073ce6c7a3024192R79

cc @varkor
