### ISSUE TITLE
Confusing documentation for compile_error!()

### ISSUE THREAD

**Issue by SOF3** [rust-lang/rust#63375]
Referring to https://github.com/rust-lang/rust/blob/db7c773a6be2f050d1d1504763819ea3916f5428/src/libcore/macros.rs#L681-L683

> It's the compiler-level form of panic!, which emits an error at runtime, rather than during compilation.

It is unclear whether the "which" refers to "panic!" or "the compiler-level form of panic!". It is more clear to write:
> It is the compiler-level form of `panic!`, **but** emits an error during compilation, rather than at runtime.

**Comment by Centril** [comment]
@SOF3 Can you file a PR with the change?
