### ISSUE TITLE
Fix ambiguity issue with associated_type_bounds

### ISSUE THREAD

**Issue by iluuu1994** [rust-lang/rust#63393]
Follow up of #61738.

These two particular cases could not be refactored due to an ambiguity issue:

---

https://github.com/rust-lang/rust/blob/2d1a551e144335e0d60a637d12f410cf65849876/src/libcore/iter/adapters/flatten.rs#L70-L76

With `#![feature(associated_type_bounds)]`

```rust
impl<I: DoubleEndedIterator, U, F> DoubleEndedIterator for FlatMap<I, U, F>
where
    F: FnMut(I::Item) -> U,
    U: IntoIterator<IntoIter: DoubleEndedIterator>,
{
    #[inline]
    fn next_back(&mut self) -> Option<U::Item> { self.inner.next_back() }
```

Result (line numbers are off):

```
error[E0221]: ambiguous associated type `Item` in bounds of `U`
   --> src/libcore/iter/adapters/flatten.rs:77:39
    |
77  |     fn next_back(&mut self) -> Option<U::Item> { self.inner.next_back() }
    |                                       ^^^^^^^ ambiguous associated type `Item`
    |
   ::: src/libcore/iter/traits/iterator.rs:94:5
    |
94  |     type Item;
    |     ---------- ambiguous `Item` from `iter::traits::iterator::Iterator`
    |
   ::: src/libcore/iter/traits/collect.rs:211:5
    |
211 |     type Item;
    |     ---------- ambiguous `Item` from `iter::traits::collect::IntoIterator`
```

---

https://github.com/rust-lang/rust/blob/2d1a551e144335e0d60a637d12f410cf65849876/src/libcore/iter/adapters/flatten.rs#L107-L110

With `#![feature(associated_type_bounds)]`

```rust
pub struct Flatten<I: Iterator<Item: IntoIterator>> {
    inner: FlattenCompat<I, <I::Item as IntoIterator>::IntoIter>,
}
```

Result (line numbers are off):

```
error[E0221]: ambiguous associated type `Item` in bounds of `I`
   --> src/libcore/iter/adapters/flatten.rs:112:30
    |
112 |     inner: FlattenCompat<I, <I::Item as IntoIterator>::IntoIter>,
    |                              ^^^^^^^ ambiguous associated type `Item`
    |
   ::: src/libcore/iter/traits/collect.rs:211:5
    |
211 |     type Item;
    |     ---------- ambiguous `Item` from `iter::traits::collect::IntoIterator`
    |
   ::: src/libcore/iter/traits/iterator.rs:94:5
    |
94  |     type Item;
    |     ---------- ambiguous `Item` from `iter::traits::iterator::Iterator`
```

---

cc @Centril @alexreg

**Comment by Centril** [comment]
cc also @nikomatsakis

**Comment by alexreg** [comment]
Thanks for this report. If you/Centril/someone could produce a MCVE, I would then be happy to investigate further... right now I don't have the time to reduce it though, sory.

**Comment by iluuu1994** [comment]
I tried again for an hour or two without success. Unfortunately I don't know enough about the internals to understand how this could happen. I'll look at the associated type bounds PR, maybe that will help.

**Comment by Centril** [comment]
This is odd; I basically pasted the code in `flatten.rs` verbatim into the [playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=f9643e7164fc020e8c010500abe91abd), made it compile,  and the made the tweaks above. The issue still won't reproduce but it does reproduce when I `./x.py check`. 

Maybe this is a bootstrapping issue...
