### ISSUE TITLE
Clean up `parse_bottom_expr` to use list parsing utility

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#63396]
_From https://github.com/rust-lang/rust/pull/63337#discussion_r312221122_

The following code should be using the common list parsing utilities:

https://github.com/rust-lang/rust/blob/2d1a551e144335e0d60a637d12f410cf65849876/src/libsyntax/parse/parser.rs#L2052-L2070

CC @Centril

**Comment by achan1989** [comment]
What/where are the common list parsing utilties?
