### ISSUE TITLE
Improve diagnostic for `break` in `async { ... }` block

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#63391]
With:
```rust
#![feature(async_await)]

fn foo() {
    async {
        break;
    };
}
```
you get:
```rust
error[E0267]: `break` inside of a closure
 --> src/lib.rs:5:9
  |
5 |         break;
  |         ^^^^^ cannot break inside of a closure
```

Note how it references "a closure" which seems confusing for a user who doesn't presume the implementation.

**Comment by gilescope** [comment]
I'm assuming its ok to leave this as the same error code of E0267 - in essence it's the same error, just more specific text.

**Comment by Centril** [comment]
Yeah I think it's fine.
