### ISSUE TITLE
E0529 should suggest turning the matched `Vec` into a slice

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#63414]
```
error[E0529]: expected an array or slice, found `std::vec::Vec<{integer}>`
  --> src/test/ui/suggestions/vec-macro-in-pattern.fixed:4:14
   |
LL |         Some([x]) => ()
   |              ^^^ pattern cannot match with input type `std::vec::Vec<{integer}>`

error: aborting due to previous error
```

CC #63399

**Comment by gregberns** [comment]
Just ran into this. Would be helpful to explain how to turn it into a slice in the explanation. In my case: `match &rows[..] { [value1] ....`, I had to `&rows[..]`. As some one relatively new, I'd have to google how to transform `Some([x])` into a slice. When the suggestion on what to try is in the error it saves so much time :)
Thanks for a great language!!

**Comment by estebank** [comment]
Current output [for the base case](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=32b7ddb57549ee5b4ef15c3d6a709ef1)

```
error[E0529]: expected an array or slice, found `Vec<{integer}>`
 --> src/main.rs:4:9
  |
3 |     match x {
  |           - help: consider slicing here: `x[..]`
4 |         [..] => {}
  |         ^^^^ pattern cannot match with input type `Vec<{integer}>`
```

and for [the option wrapped case](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=846b0e2cd499379687f0464b06ff115d):

```
error[E0529]: expected an array or slice, found `Vec<{integer}>`
 --> src/main.rs:4:14
  |
3 |     match Some(x) {
  |           ------- help: consider using `as_deref` here: `Some(x).as_deref()`
4 |         Some([..]) => {}
  |              ^^^^ pattern cannot match with input type `Vec<{integer}>`
```
