### ISSUE TITLE
Rustdoc search result links to 404

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#63435]
On the following page:

https://doc.rust-lang.org/nightly/nightly-rustc/rustc/?search=niche_start

clicking on any of the two search results yields a 404 error.

**Comment by jonas-schievink** [comment]
The first link goes to

    https://doc.rust-lang.org/nightly/nightly-rustc/rustc/ty/layout/DiscriminantKind/enum.DiscriminantKind.html#structfield.niche_start

while it should point to

    https://doc.rust-lang.org/nightly/nightly-rustc/rustc/ty/layout/enum.DiscriminantKind.html#variant.Niche.field.niche_start

So this is doubly wrong (the path has an extra folder that isn't there, and the anchor is also wrong)

**Comment by RalfJung** [comment]
The links seem fixed now.
