### ISSUE TITLE
Consider move libarena and libgraphviz out of tree

### ISSUE THREAD

**Issue by crlf0710** [rust-lang/rust#63457]
These code doesn't get touched a lot. So maybe it makes sense to move them out instead of generating auto publish packages every day.

**Comment by matklad** [comment]
Note that `libarena` already exists out of tree as https://crates.io/crates/typed_arena, which is a well maintained and widely used crate.

**Comment by crlf0710** [comment]
Opened https://github.com/SimonSapin/rust-typed-arena/issues/28 .

**Comment by Mark-Simulacrum** [comment]
I'm going to close this as I think doing this is best done as publishing a crate (perhaps a direct copy of in-tree code), getting the code in a state perhaps more fit for crates.io, and then using it in tree. Just copying the code to a separate repository does not seem helpful, and indeed, seems actively harmful.
