### ISSUE TITLE
Some(..).is_some() is false for redox_syscall datastructure

### ISSUE THREAD

**Issue by AdminXVII** [rust-lang/rust#63454]
When using the redox_syscall crate, the compiler fail at an `assert!(Some(..).is_some())`. This bug however is only present with the crate: locally defining the same datastructure runs perfectly.

Equality still works, though, as the fields can be compared.

## Minimum reproducible example
```rust
use syscall::SigAction;

fn main() {
    assert!(Some(SigAction::default()).is_some());
}
```

## Expected
The assert is successful

## Actual result
The binary panics at the assert.

## Tested on
cargo 1.38.0-nightly (677a180f4 2019-07-08), with x86_64 Linux

Demo: https://gitlab.redox-os.org/AdminXVII/some-is-none-bug-demo

**Comment by Mark-Simulacrum** [comment]
The default impl is UB; this program is not defined - it may work or may not, but never does so reliably. Function pointers are like references and must never be null; they should be wrapped in Option.
