### ISSUE TITLE
Recursive macro call inside concat macro fails to find macros referred to by $crate

### ISSUE THREAD

**Issue by cwfitzgerald** [rust-lang/rust#63460]
```rust
#[macro_export]
macro_rules! separator {
    () => { "/" };
}

#[macro_export]
macro_rules! concat_separator {
    ( $e:literal, $($other:literal),+ ) => {
        concat!($e, $crate::separator!(), $crate::concat_separator!($($other),+))
    };
    ( $e:literal ) => {
        $e
    }
}

fn main() {
    println!("{}", concat_separator!(2, 3, 4))
}
```

([Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=5e5eeda6572b99d39911309e18d8f2f8))

Errors:

```
   Compiling playground v0.0.1 (/playground)
error[E0433]: failed to resolve: could not find `separator` in `$crate`
  --> src/main.rs:9:29
   |
9  |         concat!($e, $crate::separator!(), $crate::concat_separator!($($other),+))
   |                             ^^^^^^^^^ could not find `separator` in `$crate`
...
17 |     println!("{}", concat_separator!(2, 3, 4))
   |                    -------------------------- in this macro invocation

error[E0433]: failed to resolve: could not find `concat_separator` in `$crate`
  --> src/main.rs:9:51
   |
9  |         concat!($e, $crate::separator!(), $crate::concat_separator!($($other),+))
   |                                                   ^^^^^^^^^^^^^^^^ could not find `concat_separator` in `$crate`
...
17 |     println!("{}", concat_separator!(2, 3, 4))
   |                    -------------------------- in this macro invocation
```

If either the recursion ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=e7e443dabc9692464ecbb07830286ea0)) or the `concat!` is removed ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=305b013ef718cdb15ba3f1a2cad7ea8d)), this compiles exactly as expected. Additionally, if I explicitly name my crate, it works as expected, but would be vulnerable to crate renames in user code (can't reproduce in playground because it doesn't build a library).

**Comment by nrc** [comment]
If you try and build Rustup, you get a similar failure, but without recursion or `$crate`. Seems that just using another macro and `concat` is enough in some circumstances

**Comment by lzutao** [comment]
cc @petrochenkov for the hygiene macro in #63535

**Comment by lzutao** [comment]
This code ([playpen](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=e74a4689efba586e7372d2f37c33da5c)] compiles on stable but not on nightly and beta:
```rust
mod outer {
    macro_rules! foo {
        () => {
            "foo"
        };
    }

    macro_rules! bar {
        () => {
            concat!(foo!(), "bar")
        };
    }

    pub fn baz() {
        format!(bar!());
    }
}
```

**Comment by petrochenkov** [comment]
@lzutao 
Please, file a separate issue for the regression, I'll prioritize it over pre-existing issues (which the original issue seems to be).

**Comment by lzutao** [comment]
Thanks, I filed it in #63685

**Comment by petrochenkov** [comment]
Fixed in https://github.com/rust-lang/rust/pull/63717.

**Comment by cwfitzgerald** [comment]
Thanks for your work on this!
