### ISSUE TITLE
Compiler is awkwardly happy with fns without Box

### ISSUE THREAD

**Issue by JasonShin** [rust-lang/rust#63481]
Hi, I'm writing a functional programming library in Rust, and I found some weird behaviour with typing. 

In the below code to emulate `Apply`

```
use crate::functor::Functor;
use crate::hkt::{HKT, HKT3};

pub trait Apply<A, F, B>: Functor<A, B> + HKT3<A, F, B>
where
    F: FnOnce(A) -> B,
{
    fn ap(self, f: <Self as HKT3<A, F, B>>::Target2) -> <Self as HKT<A, B>>::Target;
}

impl<A, F, B> Apply<A, F, B> for Option<A>
where
    F: FnOnce(A) -> B,
{
    fn ap(self, f: Self::Target2) -> Self::Target {
        self.and_then(|v| f.map(|z| z(v)))
    }
}
```

The compiler successfully compiles it without any issues. In short, what it is trying to do is set `F: FnOnce(A) -> B` so HKT3 of Option can pick it up and turn into `Option<FnOnce(A) -> B>`. Please checkout [HKT3 code here](https://github.com/JasonShin/fp-core.rs/blob/master/fp-core/src/hkt.rs). 

However, I encountered a compilation issue, while trying to do the exact same thing but without `HKT` emulations. The error is `FnOnce(A) -> B is the size for values of type (dyn std::ops::FnOnce(A) -> B + 'static) cannot be known at compilation time`. See the below refactored code that causes the previously-mentioned error:

```
pub trait Apply<A, B>: Functor<A, B>
{
    type FAB;
    type Output;
    fn ap(self, f: Self::FAB) -> Self::Output;
}

impl<A, B> Apply<A, B> for Option<A>
{
    type FAB = Option<Fn(A) -> B>;
    type Output = Option<B>;
    fn ap(self, f: Self::FAB) -> Self::Output {
        self.and_then(|v| f.map(|z| z(v)))
    }
}
```

To fix this, I just have to change `Option<Fn(A) -> B>` to `Option<Box<Fn(A) -> B>>`. Why does the error even happen when I am simply rewriting the same code into a different way? Maybe it's a bug in the compiler?

**Comment by jonas-schievink** [comment]
`Fn(A) -> B` is a trait object, so it has a dynamic size. `Option<T>` has an implicit `T: Sized` bound and so it can not store a value of that type.

Also see this chapter in the book: https://doc.rust-lang.org/book/ch19-04-advanced-types.html#dynamically-sized-types-and-the-sized-trait

Closing as not-a-bug.
