### ISSUE TITLE
Spurious expired crates.io certificate on CI

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#63510]
We encountered multiple spurious failures while trying to download crates from crates.io, related to an expired certificate. This is probably something happening on the CI VMs, as the crates.io certificate is expiring in a few months (maybe the clock goes back to the epoch for whatever reason?).

```
    Updating crates.io index
 Downloading crates ...
error: failed to sync

Caused by:
  failed to download from `https://crates.io/api/v1/crates/openssl-src/111.1.0+1.1.1a/download`

Caused by:
  [60] SSL peer certificate or SSH remote key was not OK (SSL certificate problem: certificate has expired)
```

* https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/5716/logs/1050
* https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/5729/logs/944

cc @Mark-Simulacrum @sgrif

**Comment by alexcrichton** [comment]
Another report of this at https://bugzilla.mozilla.org/show_bug.cgi?id=1573324, and this is happening all across the community on CI I'm seeing as well, it's not just our own CI. One instance is this build - https://dev.azure.com/alexcrichton/openssl-src-rs/_build/results?buildId=769

**Comment by sgrif** [comment]
I've opened a support ticket with Heroku and refreshed the certificate in the meantime (hopefully that clears out whatever cache is stale)

**Comment by sgrif** [comment]
If folks are continuing to see this, please comment here

**Comment by sgrif** [comment]
This appears to be resolved, please reach out to me if this happens again.
