### ISSUE TITLE
Tracking issue for map_ok and map_err method for Poll<Option<Result<T, E>>>

### ISSUE THREAD

**Issue by 95th** [rust-lang/rust#63514]
Currently map_ok and map_err methods are given for Poll<Result<T, E>>.

We should provide similar methods for Poll<Option<Result<T, E>>> as they are helpful in stream building code.

---

### Steps

- [x] Implementation: https://github.com/rust-lang/rust/pull/63512
- [ ] Stabilization

### Open questions

None

**Comment by mzabaluev** [comment]
Any plans to stabilize this?

**Comment by m-ou-se** [comment]
There aren't any open questions about this feature, and this has seen quite a few releases already. So it looks like this would be ready for stabilization.

@rfcbot merge

**Comment by KodrAus** [comment]
This was stabilized in #80968
