### ISSUE TITLE
Any rust-related command opens non-unicode file called "cargo" or "rustup"

### ISSUE THREAD

**Issue by Cipirain** [rust-lang/rust#63523]
When using any of the rust related commands, it opens a file that has 3 identifiable characters at the top and a mixed amount of bullcrap in the rest. "ELF" is at the top. Please take a look for yourself cause It's causing me tons of problems.
[rustup.txt](https://github.com/rust-lang/rust/files/3497665/rustup.txt)

**Comment by Lonami** [comment]
This "crap" is machine code. For some reason, the `rustup` binary is being opened by your text editor instead of being ran:
```sh
$ file rustup.txt
rustup.txt: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/l, for GNU/Linux 2.6.9, with debug_info, not stripped
$ ./rustup.txt -v
rustup 1.18.3 (435397f48 2019-05-22)
```

**Comment by Cipirain** [comment]
I figured as much, but was quite confused as it was working fine yesterday until I began working on writing a hashing algorithm in another language, which at that point, it had broken. Sorry for late reply, but I'll try this fix.

**Comment by Cipirain** [comment]
I've just realized I can't actually use chmod, as I'm on Windows, and installing anything that isn't a ready-to-go executable is a nightmare on this terrible OS. And I do not use rust on my Ubuntu sub-system.

**Comment by Cipirain** [comment]
I'm just going to resort to reinstalling. This is a major random problem though.
