### ISSUE TITLE
Date time chronology calendar JSR-310 capabilities within rust

### ISSUE THREAD

**Issue by omac777** [rust-lang/rust#63532]
I understand JSR-310 was mentioned earlier.  I understand others have mentioned this as issue on github, but why has the issue been closed when I haven't seen the capabilities as being implemented yet?  If they have been implemented, please indicate where they are.

Thank you
https://github.com/rust-lang/rust/issues/14657
https://mail.mozilla.org/pipermail/rust-dev/2014-June/010247.html

Also, when I examined the new nom rust parser, it highlighted an iso datetime parser however without all the other JSR-310 capabilities which lead me to bring up this issue again.
There was no validation of the date time, just parsing.  Looking for a date time validator, I found none within rust sufficient to address all the JSR-310.

Thank you for listening.

**Comment by jonas-schievink** [comment]
This is better suited as functionality for an external crate such as [chrono](https://docs.rs/chrono). Adding big components like this to the standard library also needs to go through the [RFC process](https://github.com/rust-lang/rfcs), so closing in favor of that.
