### ISSUE TITLE
Codegen backend handles compare binops for the unit type

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rust#63551]
https://github.com/rust-lang/rust/blob/c43d03a19f326f4a323569328cc501e86eb6d22e/src/librustc_codegen_ssa/mir/rvalue.rs#L586-L592

libcore however doesn't use those for the implementations for `PartialEq` and `PartialOrd` for the unit type.

https://github.com/rust-lang/rust/blob/c43d03a19f326f4a323569328cc501e86eb6d22e/src/libcore/cmp.rs#L933-L939

https://github.com/rust-lang/rust/blob/c43d03a19f326f4a323569328cc501e86eb6d22e/src/libcore/cmp.rs#L980-L985

This means that the special case in cg_ssa can be removed.

**Comment by punitkoura** [comment]
Hi @bjorn3 @Centril, I'd like to work on this. Would be a good initial contribution to Rust :)

**Comment by punitkoura** [comment]
I'm really new to the code base, though. Could you clarify what the `cg_ssa` means above?

**Comment by jonas-schievink** [comment]
> Could you clarify what the `cg_ssa` means above?

That's `librustc_codegen_ssa`, a part of the code generation code in rustc. The code in the first snippet is located there.

**Comment by punitkoura** [comment]
Thanks for clarifying that! I'll go through the code and post any questions here.

**Comment by luigishat** [comment]
Would love to help but don't know where to start. If mentoring is still possible please ping me or send me in the right direction somehow 👍 .

**Comment by luigishat** [comment]
or maybe @jonas-schievink if your up to the task :)

**Comment by jonas-schievink** [comment]
@luigishat I think you just need to look at `src/librustc_codegen_ssa/mir/rvalue.rs` and remove the check for `is_unit` that was mentioned. You can check https://rust-lang.github.io/rustc-guide/ for an overview of the compiler and instruction on how to build it and run tests.

**Comment by luigishat** [comment]
@jonas-schievink Thanks seems to be a little simpler then I thought once I dug into the docs. Will do hope your having a good one 👍 .
