### ISSUE TITLE
CStr::from_ptr should be documented to not allow strings bigger than isize::MAX

### ISSUE THREAD

**Issue by xfix** [rust-lang/rust#63590]
In #53784, `slice::from_raw_parts` was documented to not allow slices larger than `isize::MAX` bytes. However, `CStr::from_ptr` is not documented to have the same requirement, despite allowing the user to obtain a slice larger than `isize::MAX` bytes with its `to_bytes` method.

**Comment by elichai** [comment]
I think this issue can be closed Now that https://github.com/rust-lang/rust/pull/64326 is merged :)
