### ISSUE TITLE
Rust treat Self as dynamic when it shouldn't

### ISSUE THREAD

**Issue by Pzixel** [rust-lang/rust#63593]
Here is a sample code:

```rust
trait Inner<S> {}

trait MyTrait {
    fn something<I: Inner<Self>>(i: I);
}
```

Which fails to compile with 

>  error[E0277]: the size for values of type `Self` cannot be known at compilation time
 --> src/lib.rs:4:5
  |
4 |     fn something<I: Inner<Self>>(i: I);
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ doesn't have a size known at compile-time

OTOH if we add a special `This` associated type then we are completely fine:

```rust
#![feature(associated_type_defaults)]

trait Inner<S> {}

trait MyTrait {
    type This = Self;
    fn something<I: Inner<Self::This>>(i: I);
}
```

It looks like an undesirable behavior.

**Comment by jonas-schievink** [comment]
That this fails to compile is intended. Unlike type parameters, traits do not have a default `: Sized` bound, so `Self` in traits has an unknown size.

The issue with associated type defaults might be fixed by https://github.com/rust-lang/rust/pull/61812, I'll check that later.
