### ISSUE TITLE
Stabilize RFC 2451, re-rebalance coherence

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#63599]
# Stabilization Proposal

I am writing to propose we stabilize the implementation of [RFC 2451], "re-rebalancing coherence" ([tracking issue]).

[RFC 2451]: https://rust-lang.github.io/rfcs/2451-re-rebalancing-coherence.html
[tracking issue]: https://github.com/rust-lang/rust/issues/55437

## Brief Summary

The RFC modifies the coherence rules. It used to be that, when implementing a non-local trait, if Ti was the first "local type", then all type parameters were forbidden before that point. In practice, that meant that this impl was illegal:

```rust
struct Local;

impl<T> Foreign<Local> for Vec<T> { }
//              ^^^^^          ^
//              |              type parameter
//              first local type
```

The RFC lightly generalizes these rules. In particular, type parameters are now allowed before Ti, but *only* if they are **covered**, defined in the RFC as:

> Covered Type: A type which appears as a parameter to another type. For example, `T` is uncovered, but the `T` in `Vec<T>` is covered. This is only relevant for type parameters.

This means that the impl above is now legal, because the type`T` is covered by `Vec`. Note that an impl like the following would still be illegal:

```rust
struct Local;

impl<T> Foreign<Local> for T { }
//              ^^^^^      ^
//              |          type parameter (uncovered)
//              first local type
```

It is considered a (semver) breaking change for parent crates to add impls with uncovered type parameters (this was already the case even with the old rules, I believe). Therefore, this generalization of the rules cannot permit a conflict between the parent crate and a child crate. ([See RFC for a more detailed argument.](https://rust-lang.github.io/rfcs/2451-re-rebalancing-coherence.html#concrete-orphan-rules))

(NB: I've elided details of `#[fundamental]` in this summary, see the RFC for full details.)

## Changes since the RFC was approved

None

## Test cases

This section describes the patterns covered by new tests added for this RFC, or tests that seemed relevant to this RFC, with links to the test files.

- `impl<T> Foreign<Local> for Foreign<T, Foreign>` -- [re-rebalance-coherence.rs](https://github.com/rust-lang/rust/blob/1cdcea920e56a5d0587307a4c9cf8fff5c77c4bc/src/test/ui/coherence/re-rebalance-coherence.rs#L11), [re-rebalance-coherence-rpass.rs](https://github.com/rust-lang/rust/blob/master/src/test/ui/coherence/re-rebalance-coherence-rpass.rs#L12) (these appear to be duplicate tests)
- `impl<T> Foreign for Foreign<T, Local<T>>` -- [coherence-cow.rs](https://github.com/rust-lang/rust/blob/1cdcea920e56a5d0587307a4c9cf8fff5c77c4bc/src/test/ui/coherence/coherence-cow.rs#L18), [coherence-cow.rs](https://github.com/rust-lang/rust/blob/1cdcea920e56a5d0587307a4c9cf8fff5c77c4bc/src/test/ui/coherence/coherence-cow.rs#L23)
- `impl<T,U> Foreign for Foreign<T, Local<U>>` -- [coherence-cow.rs](https://github.com/rust-lang/rust/blob/1cdcea920e56a5d0587307a4c9cf8fff5c77c4bc/src/test/ui/coherence/coherence-cow.rs#L28), [coherence-pair-covered-uncovered.rs](https://github.com/rust-lang/rust/blob/1cdcea920e56a5d0587307a4c9cf8fff5c77c4bc/src/test/ui/coherence/coherence-lone-type-parameter.rs#L9)
- `impl<T> Foreign<Local> for T` -- [coherence-bigint-param.rs](https://github.com/rust-lang/rust/blob/1cdcea920e56a5d0587307a4c9cf8fff5c77c4bc/src/test/ui/coherence/coherence-bigint-param.rs#L11)
- `impl Foreign for Local<T>` -- [coherence-covered-type-parameter.rs](https://github.com/rust-lang/rust/blob/1cdcea920e56a5d0587307a4c9cf8fff5c77c4bc/src/test/ui/coherence/coherence-covered-type-parameter.rs#L15), [coherence-iterator-vec.rs](https://github.com/rust-lang/rust/blob/1cdcea920e56a5d0587307a4c9cf8fff5c77c4bc/src/test/ui/coherence/coherence-iterator-vec.rs#L15)
- `impl<T> Foreign<T> for Foreign` -- [coherence-all-remote.rs](https://github.com/rust-lang/rust/blob/1cdcea920e56a5d0587307a4c9cf8fff5c77c4bc/src/test/ui/coherence/coherence-all-remote.rs#L9)
- `impl Foreign<Local> for Foreign` -- [coherence-bigint-int.rs](https://github.com/rust-lang/rust/blob/1cdcea920e56a5d0587307a4c9cf8fff5c77c4bc/src/test/ui/coherence/coherence-bigint-int.rs#L14), [coherence-bigint-vecint.rs](https://github.com/rust-lang/rust/blob/1cdcea920e56a5d0587307a4c9cf8fff5c77c4bc/src/test/ui/coherence/coherence-bigint-vecint.rs#L14)
- `impl<T> Foreign for T` -- [coherence-cross-crate-conflict.rs](https://github.com/rust-lang/rust/blob/1cdcea920e56a5d0587307a4c9cf8fff5c77c4bc/src/test/ui/coherence/coherence-cross-crate-conflict.rs#L12), [coherence-lone-type-parameter.rs](https://github.com/rust-lang/rust/blob/1cdcea920e56a5d0587307a4c9cf8fff5c77c4bc/src/test/ui/coherence/coherence-lone-type-parameter.rs#L9)
- `impl Foreign for Foreign<Local>` -- [coherence-vec-local.rs](https://github.com/rust-lang/rust/blob/1cdcea920e56a5d0587307a4c9cf8fff5c77c4bc/src/test/ui/coherence/coherence-vec-local.rs#L14)
- `impl<T> Foreign<Foreign<T>, Local> for Foreign<T>` -- in https://github.com/rust-lang/rust/pull/64414
- `impl<T> Foreign<Local> for Fundamental<T>` -- in https://github.com/rust-lang/rust/pull/64414

## Missing items

- [ ] Open PR against the reference, updating documentation
- [x] Fix https://github.com/rust-lang/rust/issues/64412
- [ ] Add more tests for fundamental patterns -- we did not by any means tile the space

**Comment by nikomatsakis** [comment]
@rfcbot fcp merge

Dear @rust-lang/lang, I propose that we **stabilize** the re-rebalancing coherence changes. This issue opens with a description of the changes and some examination of test cases. Please review and feel free to note any missing patterns, I'm opening a PR shortly adding and adjusting tests as needed. 

Also, I don't think we've updated the reference, so I've included a checklist item to do that.

**Comment by Centril** [comment]
> I will open a PR shortly covering one missing pattern, where the Ti with the local type is T2:
> 
>     * `impl<T> Foreign<Foreign<T>, Local> for Foreign<T>`
> 
>     * XXX tests involving fundamental

@rfcbot concern make-sure-we-add-these-tests

:)

**Comment by scottmcm** [comment]
Curiosity: is `T` covered by `[T; N]` and `(T,)`?

**Comment by nikomatsakis** [comment]
Hmm, writing up some new tests, I am finding that the current implementation is not working as expected! In particular, the behavior around fundamental types seems wrong, or else I am misreading the RFC.

For example, this impl is allowed:

```rust
impl<T> Remote1<Local> for Box<T> { }
```

This is despite the text in the RFC which says:

> Once again, it is important to note that for the purposes of coherence, `#[fundamental]` types are special. `Box<T>` is not considered covered, and `Box<LocalType>` is considered local.

I presume here that "`Box<T>` is not considered covered" meant that the `T` is not considered covered (correct, @sgrif?).

That said, I'm not sure if this is a *problem*. The RFC states (correctly) that adding any blanket impl must be considered a breaking change, where a breaking impl is any impl that contains an uncovered type parameter. This implies that if some parent crate were to add something like this:

```rust
impl<T> Remote1<T> for Box<_> { } // where _ represents any type at all
```

that would be a major breaking change. But such an impl would be needed to match the type above, since there is no way for the parent crate to name the local type.

**Comment by sgrif** [comment]
Yeah, "The `T` in `Box<T>` would be more precise

**Comment by nikomatsakis** [comment]
So I created a [google spreadsheet](https://docs.google.com/spreadsheets/d/1WlroTEXE6qxxGvEOhICkUpqguYZP9YOZEvnmEtSNtM0/edit?usp=sharing) with the existing tests and patterns. @weiznich did an amazing job filling in a lot of details. I still found *some* categories we don't seem to cover, though I'm not sure how important they are. We also have some duplicate coverage, due in part to the poor naming convention for earlier tests. Overall I feel pretty comfortable about moving forward, though I also think it wouldn't hurt to tile the space when it comes to tests.

@Centril you have to clear your concern for this to leave FCP

**Comment by weiznich** [comment]
@nikomatsakis Should I've try to find some time to write a PR adding the missing test cases?

**Comment by nikomatsakis** [comment]
@weiznich if you don't mind doing so, that'd be awesome! The other thing that might be useful is to rename the existing tests so they all fit the new naming scheme we were using.

**Comment by Centril** [comment]
@rfcbot resolve make-sure-we-add-these-tests
@rfcbot reviewed

Let's handle the tests with the stabilization PR. :)
@weiznich Perhaps you'd like to author the stabilization PR?

**Comment by weiznich** [comment]
@Centril stabilization PR means just a PR that moves [this feature](https://github.com/rust-lang/rust/blob/master/src/libsyntax/feature_gate/active.rs#L472) for `active.rs` to `accepted.rs`, change the state from `active` to `accepted` and the version number to 1.40.0. Additionally change the tests in `src/test/ui/coherence` to remove the feature because it's stable then.
