### ISSUE TITLE
1.37 source component packaging looks different from previous versions

### ISSUE THREAD

**Issue by vitalyd** [rust-lang/rust#63605]
Hi,
Apologies if reporting this here isn't the most appropriate place, but thought someone else may run into it as well.

It appears there're some material differences in how the Rust 1.37 release is packaged, namely around the source download.

The [tarball](https://static.rust-lang.org/dist/rustc-1.37.0-src.tar.gz) for stable sources is named differently.  Up to 1.36, it used to be of the form `rust-src-1.36.0.tar.gz` (adjusting for the version, of course).  This broke some automation scripts I have, but ok - no big deal really.

The larger issue is there's no `install.sh` in there anymore.  I have some scripts that vendor the Rust toolchain, and they're expecting to find that shell script in there to install the `rust-src` component.  What's the new mechanism to accomplish that?

I couldn't find any reference to this change in the 1.37 release notes, but perhaps I didn't look hard enough (to my credit, I did try a few quick github repo searches but to no avail).

Happy to answer any questions or provide more info.

Thanks

**Comment by vitalyd** [comment]
@Mark-Simulacrum would you happen to know anything about this?

**Comment by ollie27** [comment]
https://static.rust-lang.org/dist/rust-src-1.37.0.tar.gz loads fine for me.

**Comment by jonas-schievink** [comment]
Yeah, the old format still works and also contains `install.sh`.

**Comment by vitalyd** [comment]
@ollie27 / @jonas-schievink thanks - I must've not had enough coffee today cause I could've sworn I looked for the old one earlier and didn't find it.  Sorry for the noise then 🤦‍♂ 

Ok, and so while we're on the subject - the expectation is the `rust-src` tarball will continue existing and we should install the `rust-src` components via the `install.sh` there, right? I shouldn't try to modify my scripts to use the `rustc-src`? By the way, is it intentional that https://forge.rust-lang.org/other-installation-methods.html#source is providing links to `rustc-src` and not `rust-src`?

Thanks

**Comment by vitalyd** [comment]
Closing as the root issue is my brainfart :).
