### ISSUE TITLE
Short-circuit behavior and order in expressions results in 15x performance difference?

### ISSUE THREAD

**Issue by adamdrake** [rust-lang/rust#63622]
I have just started playing with Rust again via Project Euler Problem 4 and I noticed some interesting short-circuit behavior in expressions.  In the two functions below, `v2()` is approximately 15 times faster than `v1()` just due to the ordering in the `if`.  It's great that there is a short-circuit option and accompanying speedup, but is it expected that developers will be mindful of the ordering required to achieve it?

This reminds me of the old days of struct packing.

Please advise if this is working as intended or is an issue.

To test, just run `cargo bench`.

```rust
#![allow(unused)]
#![feature(test)]
extern crate test;
use test::Bencher;

fn is_palindromic_v1(i: i32) -> bool {
    return i.to_string().chars().rev().collect::<String>() == i.to_string();
}

// v1, naive attempt: multiply three-digit numbers until palindrome is found, keep it, go until the end
fn v1() -> i32 {
    let mut res = 0;
    for i in 100..=999 {
        for j in 100..=999 {
            let prod = i * j;
            if is_palindromic_v1(prod) && prod > res {  // <-- function evaluation first
                res = prod;
            }
        }
    }
    return res;
}

// v2, same as v1 but with && order swapped
fn v2() -> i32 {
    let mut res = 0;
    for i in 100..=999 {
        for j in 100..=999 {
            let prod = i * j;
            if prod > res && is_palindromic_v1(prod) {  // <-- swapped here and ~15x faster
                res = prod;
            }
        }
    }
    return res;
}

mod benchmarks {
    use super::*;
    
    #[bench]
    fn bench_v1(b: &mut Bencher) {
        b.iter(|| v1())
    }
    
    #[bench]
    fn bench_v2(b: &mut Bencher) {
        b.iter(|| v2())
    }
}
```

**Comment by leijurv** [comment]
This is intended. If `prod > res` evaluates to true, it will short circuit and not evaluate the slow function `is_palindromic_v1`

> is it expected that developers will be mindful of the ordering required to achieve it?

Yes

**Comment by adamdrake** [comment]
Thank you for the response.  I am familiar with the short-circuit semantics but since I hadn't ever heard of it in relation to Rust I wasn't sure if it was desired/documented behavior.  Perhaps just too new to the language to have perused enough of the documentation.
