### ISSUE TITLE
Wasm bundle for sys crate with FFI exports is empty

### ISSUE THREAD

**Issue by lopopolo** [rust-lang/rust#63629]
I'm trying to compile [`mruby-sys`](https://github.com/artichoke/artichoke/tree/master/mruby-sys) to wasm. `mruby-sys` builds a C static library using the `cc` crate. `cc` generates two wasm files, one of which I can't read with `0000004: error: bad magic value` error. The other looks like valid wasm and I can read it with `wasm2wat`.

crate `mruby-sys` [exports](https://github.com/artichoke/artichoke/blob/d74f157b3150d5166b0e62f7553bb913bc7f0f25/mruby-sys/src/lib.rs#L24-L25):
- all FFI bindings to `extern "C"` functions 
- several Rust functions that are annotated with `#[inline]`.

The resulting wasm bundle for `mruby-sys` is empty:

```wasm
(module
  (type (;0;) (func))
  (func $__wasm_call_ctors (type 0))
  (table (;0;) 1 1 anyfunc)
  (memory (;0;) 17)
  (global (;0;) (mut i32) (i32.const 1048576))
  (global (;1;) i32 (i32.const 1048610))
  (global (;2;) i32 (i32.const 1048610))
  (global (;3;) i32 (i32.const 1048576))
  (export "memory" (memory 0))
  (export "__heap_base" (global 1))
  (export "__data_end" (global 2))
  (export "__rustc_debug_gdb_scripts_section__" (global 3))
  (data (;0;) (i32.const 1048576) "\01gdb_load_rust_pretty_printers.py\00"))
```

**Comment by alexcrichton** [comment]
Thanks for the report, but this is likely a build issue with mruby-sys, and unrelated to rustc's wasm support.
