### ISSUE TITLE
Expose llvm.ptrmask intrinsic

### ISSUE THREAD

**Issue by nikic** [rust-lang/rust#63656]
LLVM recently added a ptrmask intrinsic, intended for use with tagged pointers: https://llvm.org/docs/LangRef.html#llvm-ptrmask-intrinsic

It allows masking off bits from a pointer without going through ptrtoint/inttoptr and breaking alias analysis in the process. We might want to expose this somehow...

**Comment by leonardo-m** [comment]
This could be a quite useful thing for Rust if handled well (at least used by a Cargo crate).

**Comment by Mark-Simulacrum** [comment]
This is now exposed on nightly: https://doc.rust-lang.org/nightly/std/primitive.pointer.html#method.mask. Since there's already a tracking issue (https://github.com/rust-lang/rust/issues/98290), closing in favor of that.
