### ISSUE TITLE
Fn coercion rules seem inconsistent

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#63665]
Consider the following code (which compiles; [playground](https://play.rust-lang.org/?version=stable&mode=release&edition=2018&gist=8902809bc4f0bf6a0752131d9695eda9)):

```
fn f(_: usize) {
    unimplemented!();
}

fn main() {
    let err = Err(());
    f(err.unwrap_or_else(err_exit));
    unreachable!();
}

fn err_exit(_: ()) -> ! {
    std::process::exit(1);
}
```

If you change `let err = Err(());` to `let err: Result<usize, ()> = Err(());`, then it fails with 'error[E0271]: type mismatch resolving `<fn(()) -> ! {err_exit} as std::ops::FnOnce<((),)>>::Output == usize`' ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=ac780bab0fd34778c4a5a60071fcc4c8)).

This seems inconsistent - I'm not sure why this is happening but I feel like the behavior should be the same in both cases.

**Comment by KrishnaSannasi** [comment]
This is because `err` is inferred to be `Result<!, ()>` not `Result<usize, ()>`. Then after the `unwrap_or` the `!` gets coerced into a `usize`

**Comment by jyn514** [comment]
That makes sense, I guess. My real complaint is that `fn () -> !` doesn't get coerced to `fn () -> usize` but that's not related to this issue so I'll close it.
