### ISSUE TITLE
Local rustdoc search doesn't work with --no-deps

### ISSUE THREAD

**Issue by Boddlnagg** [rust-lang/rust#63666]
I'm having an issue that is similar to https://github.com/rust-lang/docs.rs/issues/316, but it's about local docs.

I'm using `cargo doc --no-deps --open`, and on the opened page the search does not work. It shows "Loading search results..." and doesn't complete, just like in the link above.

The JS console says: `TypeError: paths is undefined (main.js:95:15458)`, and in the JS debugger I see the following: It's trying to access `rawSearchIndex['byteorder'].p`, but `rawSearchIndex['byteorder']` does not have `p`. It looks like the following:

```
rawSearchIndex['byteorder']: {…}
doc: "This crate provides convenience methods for encoding and decoding numbers in either [big-endian or little-endian order]."
items: (265) […]
paths: (5) […]
<prototype>: {…}
```

However, for my own crate it works correctly:
```
rawSearchIndex['climeta']: {…}
doc: ""
i: (2184) […]
p: (143) […]
<prototype>: {…}
```

Actually I guess there should be nothing about `byteorder` at all in the index, because I built the docs with `--no-deps`, and alas, when building without `--no-deps`, the search works!

Now, I tried to build again with `--no-deps`, and it still works. Apparently it was trying to load some old index file that had an outdated format ...

It's great when a problem gets solved while writing the issue report 😆, but I think this issue might still serve a purpose, so I'll open it anyway, if only for others to find it. And maybe rustdoc should try harder to not load outdated index files.

**Comment by Boddlnagg** [comment]
And now I noticed: When I build with `--no-deps` after having built without `--no-deps`, the other crates are still shown in the docs and found via the index, but I want to see only my own crate ... do I have to delete the `target/doc` directory?

**Comment by GuillaumeGomez** [comment]
Yes, when generating docs, rustdoc look at the target directory and changes a few things depending on what it finds. To go back on your original issue, I think it'll fail again if you remove the folder and regenerate with `--no-deps`. I'll assign myself on it.

**Comment by lolbinarycat** [comment]
triage: seems fixed

**Comment by GuillaumeGomez** [comment]
Please don't close issues if there is no regression test.

**Comment by lolbinarycat** [comment]
is there a label for "fixed, but has no regression test"?

**Comment by GuillaumeGomez** [comment]
Not that I know of.

**Comment by lolbinarycat** [comment]
found it.
