### ISSUE TITLE
please provide JSON support to the standard library 

### ISSUE THREAD

**Issue by nocord** [rust-lang/rust#63661]
to work with json we need library. Which we don't want. Please provide support JSON to std lib

**Comment by jonas-schievink** [comment]
Hi! Large additions to the language or standard library need to go through our [RFC process](https://github.com/rust-lang/rfcs). Before an RFC is written, the feature can also be discussed in our [internals forum](https://internals.rust-lang.org/) to find other people interested in it.

Closing in favor of an RFC.

**Comment by nocord** [comment]
@jonas-schievink   Why you don't make an RFC?

**Comment by nocord** [comment]
@jonas-schievink ,  don't you want JSON support ?

**Comment by Ixrec** [comment]
There's already a bunch of crates for dealing with JSON, most famously `serde`.

[Unlike many other language ecosystems, "X is useful" is not an argument for putting X in Rust's `std` library](https://internals.rust-lang.org/t/expansion-of-standard-library/10475/7?u=ixrec), at least not by itself. There has to be some additional reason why a separate create is not good enough, and I'm not aware of any such reason for JSON handling.

**Comment by nocord** [comment]
JSON is a standardized file format

**Comment by qnighy** [comment]
That "standard" has nothing to do with the Rust "standard" library. Most people are happy with `serde_json` when dealing with the standard format. As an extreme example, there's an ITU-T standard format called ASN.1 but I know of no language with standard support for it.

I agree that JSON is really popular (regardless of whether standardized or not), but that alone does not support inclusion in Rust std, as explained above. This is the general policy in nowadays Rust and other crates like `num`, `regex`, `chrono` and `log` also follows this rule.
