### ISSUE TITLE
Implement a self hosted compiler

### ISSUE THREAD

**Issue by nocord** [rust-lang/rust#63662]
Make everything of rust in rust

**Comment by jonas-schievink** [comment]
rustc is already self-hosted, with the exception of LLVM. Reimplementing LLVM in Rust is outside of the scope of the Rust project. An alternative codegen backend using cranelift is being developed [here](https://github.com/bjorn3/rustc_codegen_cranelift/), but it will not replace the default LLVM backend.

**Comment by nocord** [comment]
@jonas-schievink, so we are depending on C++ for working with Rust. But Rust was created, because C++ isn't good enough

**Comment by nocord** [comment]
>rustc is already self-hosted

How can it be? You are depending on LLVM for generating machine code
