### ISSUE TITLE
#![macro_use] triggers unused attributes warning

### ISSUE THREAD

**Issue by topecongiro** [rust-lang/rust#63680]
Replacing `#[macro_use] mod foo;` with `#![macro_use]` inside foo.rs triggers unused attribute warning even if it is necessary.

Using rustc 1.39.0-nightly (2111aed0a 2019-08-17).

**Comment by Centril** [comment]
cc @petrochenkov

**Comment by petrochenkov** [comment]
Cannot reproduce this, neither outer nor inner `#[macro_use]` on modules never produce `unused` warnings, even if they are actually unused.

**Comment by topecongiro** [comment]
I was quite mistaken. There were **both** outer and inner macro_use attributes, which is why the inner attribute was warned as unused.

My apologies for the noise.
