### ISSUE TITLE
core::ffi::c_void is marked as "stable since 1.1", but it was added in 1.30

### ISSUE THREAD

**Issue by Lokathor** [rust-lang/rust#63694]
The title says it all really.

* Missing `ffi` entirely: https://doc.rust-lang.org/1.29.0/core/
* Present in the new `ffi` module: https://doc.rust-lang.org/1.30.0/core/ffi/index.html

**Comment by hellow554** [comment]
It was just moved in https://github.com/rust-lang/rust/pull/53910 from std to core. So.. both is quite correct. 
I can't find any mentioning of the stable since attribute. Maybe it was just accepted because it was just a move?

**Comment by Lokathor** [comment]
Ah-ha, but users before 1.30 can't use it in core, I think it should get a new stable-since tag.
