### ISSUE TITLE
Debug implementaton for `&(x: impl Debug)` should prepend `&`

### ISSUE THREAD

**Issue by omarabid** [rust-lang/rust#63708]
dbg! is not displaying the type correctly for reference objects/variables.

Comment here: https://www.reddit.com/r/rust/comments/cp8y58/hey_rustaceans_got_an_easy_question_ask_here/ex76hhq/

Code here: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=ed9fb6649d0a281ac6d2ecf39eb7a51b

Expect output is `&MyStruct` but dbg! is displaying as `MyStruct` which is not accurate.

**Comment by jonas-schievink** [comment]
It's possible to make the `Debug` impl for `&T` prepend a `&` before forwarding, but I'm pretty sure `println!`, `write!`, etc. all implicitly create references to their arguments, so this would make those behave very unintuitively (the behavior with method calls might also be surprising if this is changed).

**Comment by Centril** [comment]
This has nothing to do with `dbg!` as noted in the reddit discussion. If you want to change the behavior of `Debug for &T` to prepend `&` I'd recommend filing a PR.

**Comment by sfackler** [comment]
Our standard behavior for Debug implementations on smart pointers has them directly delegate - `Arc<T>` debugs just like `T`, not `Arc(T)` or whatever, for example.

**Comment by Mark-Simulacrum** [comment]
Closing. I agree with @Centril that this is best suited for a PR (rather than an issue that is likely to get lost/abandoned).
