### ISSUE TITLE
window.hashchange is not a function

### ISSUE THREAD

**Issue by richardwhiuk** [rust-lang/rust#63707]
When selecting Rust source code with either the latest stable or the latest nightly, the following is seen:

```
main-20190703-1.36.0-a53f9df32.js:1 Uncaught TypeError: window.hashchange is not a function
    at set_fragment (main-20190703-1.36.0-a53f9df32.js:1)
    at HTMLDocument.document.onclick (main-20190703-1.36.0-a53f9df32.js:1)
```

e.g. see https://docs.rs/ensure/0.2.1/src/ensure/lib.rs.html#11 and try and select some lines

Suspect that https://github.com/rust-lang/rust/blob/master/src/librustdoc/html/static/main.js#L347 should be `highlightSourceLines(null)`.

**Comment by chocol4te** [comment]
@richardwhiuk Which browser were you seeing this on? I'm not seeing it on latest Safari or Firefox
