### ISSUE TITLE
[bug] async specialization is not parsed

### ISSUE THREAD

**Issue by jhpratt** [rust-lang/rust#63716]
The `async` keyword doesn't seem to currently work with specialization (namely `default fn`). The order of keywords does not matter — I'm not sure which it's supposed to be.

Minimal example from @dtolnay in dtolnay/async-trait#25:

```rust
macro_rules! item {
    ($i:item) => {}
}

item! {
    trait Trait {
        async default fn f() {}
    }
}

item! {
    trait Trait {
        default async fn f() {}
    }
}
```

which gives the following error

```
error: expected one of `extern`, `fn`, or `unsafe`, found `default`
 --> src/main.rs:7:15
  |
7 |         async default fn f() {}
  |               ^^^^^^^ expected one of `extern`, `fn`, or `unsafe` here

error: missing `fn`, `type`, or `const` for trait-item declaration
  --> src/main.rs:12:18
   |
12 |       trait Trait {
   |  __________________^
13 | |         default async fn f() {}
   | |________^ missing `fn`, `type`, or `const`

error: aborting due to 2 previous errors
```

**Comment by cramertj** [comment]
Note that `async` in traits is not yet allowed, so this would be meaningless even if it parsed.

**Comment by dtolnay** [comment]
@cramertj #[async_trait] can handle this if rust will parse it.

**Comment by jhpratt** [comment]
@cramertj Where this came up is when attempting to use the `async-trait` crate, which uses a proc macro to transform async traits to current syntax. I was attempting to use it in Rocket when I ran into this.
