### ISSUE TITLE
Strange E0505 error ... is this a bug?

### ISSUE THREAD

**Issue by DavePearce** [rust-lang/rust#63719]
Hey Folks,

So, I've been fuzz testing `rustc` nightly using a range of generated programs and am digesting the findings.  This one stood out to me:

```
 fn main() { 
        let mut x = 1; 
        { 
            let mut y = &mut x; 
            y = y; 
            y; 
        } 
        x; 
    }
```

This currently reports an E0505 on the playground and Rust nightly.  However, removing the nop `y=y;` and its fine.  This feels like a bug to me ... thoughts?

**Comment by ExpHP** [comment]
```
y = y;
```

I think this is technically a reborrow (`y = &mut *y`) rather than a no-op, because the lhs and rhs are both known to be `&mut _`.  Though this is the first time I've ever seen a reborrow cause *fewer* programs to compile versus a move!

(amusingly, though, the MIR is simply `_2 = _2`)

**Comment by DavePearce** [comment]
Ok, have found some more related cases:

```
fn main() { let mut x = Box::new(0); { let mut y = &mut x; y = y; let mut z = &y; z; y; } x; }
```
Above gives `E0502` and `E0505`.
```
fn main() { let mut x = 0; { let mut y = &mut x; y = y; y = y; y; } x; }
```
Above gives `E0499` and `E0505`.

**Comment by nikomatsakis** [comment]
Discussed in lang team pre-triage meeting. Maybe @matthewjasper you'd be game to investigate and take a look at what's happening here?
