### ISSUE TITLE
offline docs doesnot show symbols proper on firefox

### ISSUE THREAD

**Issue by Karuturirs** [rust-lang/rust#63727]
The offline docs  does not show symbols properly such as navigation to previous page, next page, table of content, change theme, search and print this book in firefox browser only.

tried > rustup docs --book
opened docs in firefox.

//version
> rustc --version --verbose
rustc 1.37.0 (eae3437df 2019-08-13)
binary: rustc
commit-hash: eae3437dfe991621e8afdc82734f4a172d7ddf9b
commit-date: 2019-08-13
host: x86_64-apple-darwin
release: 1.37.0
LLVM version: 8.0

attaching file 
<img width="1437" alt="Screen Shot 2019-08-19 at 7 45 01 PM" src="https://user-images.githubusercontent.com/7746544/63314037-48595e00-c2bb-11e9-8c5b-72d4e5dd4faa.png">

**Comment by jonas-schievink** [comment]
Thanks for the report! This should be filed in https://github.com/rust-lang-nursery/mdBook though since it's not an issue with rustc or the standard library.

The symbols are loaded from Google Fonts, did you block that by any chance?
