### ISSUE TITLE
[Feature request] Compiler might automatically pick a concrete type for generic Option<T>

### ISSUE THREAD

**Issue by krobmd** [rust-lang/rust#63735]
Hello Rust developers,

My versions are:

- rustc: `1.37.0 (eae3437df 2019-08-13)`
- Cargo: `1.37.0 (9edd08916 2019-08-02)`

Currently this does not compile:

```rust
use std::path::Path;

fn test<P>(_: Option<P>) where P: AsRef<Path> {}

fn main() {
    test(None);
}
```

Error message:

```shell
error[E0282]: type annotations needed
 --> src/main.rs:6:5
  |
6 |     test(None);
  |     ^^^^ cannot infer type for `P`
```

If I change `main()` to below then it will compile:

```rust
fn main() {
    test::<&str>(None);
}
```

May I ask if you could consider adding new feature where:

- If a generic type is within an `Option<T>`, and the user passes `None` to it.
- And, if the compiler sees _at least_ one possible concrete type of that parameter.
- Then, please make the compiler pick one of them.

Since the user passes a `None` value, the automatically picked concrete type is not important.

Thank you,

**Comment by jonas-schievink** [comment]
Hi! Large additions to the language or standard library need to go through our [RFC process](https://github.com/rust-lang/rfcs). Before an RFC is written, the feature can also be discussed in our [internals forum](https://internals.rust-lang.org/) to find other people interested in it.

Closing in favor of an RFC.

> Since the user passes a `None` value, the automatically picked concrete type is not important.

This isn't true, the type's trait impls can be used by the called function if there's at least one function without a `self` argument.

**Comment by krobmd** [comment]
@jonas-schievink 

Thanks, I'm not clear about your answer (_"This isn't true..."_). But I think you're right. I'm new to Rust so I'll have to learn more.

Since my knowledge is limited, I think I'll won't try the RFC route.

**Comment by jonas-schievink** [comment]
Consider for example:

```rust
use std::path::Path;

fn test<P>(_: Option<P>) where P: AsRef<Path> + Default {
    let instance = P::default();
}

fn main() {
    test(None);
}
```

Now the type chosen for `P` becomes observable because `test` will call a function that depends on the type.

This doesn't mean this couldn't be done, of course, but it's a non-trivial thing to solve and decide on.

**Comment by krobmd** [comment]
@jonas-schievink 

I apologize if I'm making github send you a lot of emails. I just want to say thank you, for your excellent explanation.

Have a nice day to you,

**Comment by jonas-schievink** [comment]
No problem at all!
