### ISSUE TITLE
Tracking issue for `linux_syscall`

### ISSUE THREAD

**Issue by newpavlov** [rust-lang/rust#63748]
PR: #63745

Unresolved questions:
- [ ] Should we add syscalls to `core` or keep only in `std`?
- [ ] Do we still need the workaround for `syscall6` on x86?

**Comment by hellow554** [comment]
How is a syscall supported in a `core` environment? I don't think that that will make sense

**Comment by newpavlov** [comment]
In the essence it's not that different from supporting `target_arch` which we do in `core::arch::x86_64`, but this time those functions will be feature-gated behind `target_os`. And since calling syscalls involves just a tiny assembly snippet, it would not cause `core` bloat. Read the discussion linked in the PR. Also I think this issue is relevant as well: #36193

**Comment by joshtriplett** [comment]
@newpavlov I would very much like to use these functions in `no_std` projects that don't link to std or libc. That would be my primary use case for direct use of syscalls.
