### ISSUE TITLE
Suggest removing `self` import when not in a list

### ISSUE THREAD

**Issue by varkor** [rust-lang/rust#63741]
```rust
use std::self; // error[E0429]: `self` imports are only allowed within a { } list
```
we should offer the suggestion to remove `::self`, as this is likely what the user intended.

This issue has been assigned to @mibac138 via [this comment](https://github.com/rust-lang/rust/issues/63741#issuecomment-623142619).

**Comment by Centril** [comment]
@petrochenkov Would it simplify or complicate things if we simply allowed this instead of rejecting it?

**Comment by petrochenkov** [comment]
~Simplify.

**Comment by Centril** [comment]
Might be worth doing that in that case.

**Comment by petrochenkov** [comment]
It needs some amount design work though (not large).

The idea is to treat `self` and `super` in Rust paths as `.` and `..` in filesystem paths.
Some questions arise in the process, e.g. if `bar` is an import (symlink), then whose parent `bar::super` refers too, or whether `use foo::super [as name];` is allowed without the `as name` part and what name it introduces (`use foo::self;` needs to be allowed for compatibility and introduces `foo`).

Also cc https://github.com/rust-lang/rust/issues/48067 (path concatenation in macros).

**Comment by nikomatsakis** [comment]
Visited in compiler triage. I think this is medium priority, clearly, but I am guessing that @Centril intended the nomination for the lang team.

Wearing my lang team hat, I think I'd expect this to compile, but I don't have strong opinions about it.

**Comment by nikomatsakis** [comment]
We discussed this in the [lang team meeting last week](https://paper.dropbox.com/doc/T-Lang-Meeting-2019.08.29--AkPey8vYlpUMLsS_5MeBVJlZAg-ydagQSwNNH0iSwUy225pZ). We decided that there were some reasons to tread carefully here: in particular, we didn't really want to admit the possibility of "non-canonical" paths like `use foo::bar::self::super::bar`. Moreover, there isn't a strong reason to accept this pattern -- it would definitely be linted against, and if you have some kind of tooling that wishes to emit `self` for simplicity, they can always emit things like `use foo::bar::{self}`.

So the conclusion was "probably better to just leave it alone for now" from a language perspective.

If we *were* to accept `foo::self`, we'd want some conditions:

- always the last item in a path
- do not accept super in that position, just self

**Comment by comex** [comment]
In addition to a suggestion, the compiler could have better error recovery.  Currently, the following produces errors on both the first and second line; it should only error on the first line:
```rust
use std::mem; // `self` imports are only allowed within a { } list
fn main() { mem::drop(42); } // use of undeclared type or module `mem`
```
