### ISSUE TITLE
Check stdout/stderr of run-pass run portion

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#63751]
We currently check the compiler's output, but it's sometimes useful to check that the run-pass test itself is outputting the same as before. In particular, @tmandry expressed a desire to test libtest in this fashion.

Taking a look at the code, we probably want to add another header flag (`check-run-results`) around  [here in this file](https://github.com/rust-lang/rust/blob/51879c3abaedb926739095d19a2af638ee6a07d8/src/tools/compiletest/src/header.rs#L332); and then when running the generated executable [here](https://github.com/rust-lang/rust/blob/51879c3abaedb926739095d19a2af638ee6a07d8/src/tools/compiletest/src/runtest.rs#L3050-L3056) we should replicate [this expected loading code](https://github.com/rust-lang/rust/blob/51879c3abaedb926739095d19a2af638ee6a07d8/src/tools/compiletest/src/runtest.rs#L2949-L2970) down. If possible, it'd be great to extract some sort of function that would load results and compare them, but I'm not sure how feasible that is in a clean manner.

**Comment by Mark-Simulacrum** [comment]
I've assigned to @tmandry for now because I believe they might be interested in landing this more quickly than perhaps mentoring will be able to but let us know if you're interested!

**Comment by Centril** [comment]
This would be great; we could use this to simplify the hacks in testing `dbg!` for example.

**Comment by tmandry** [comment]
I would _like_ to get it soon, but I probably won't be getting to this until next week at least :)

**Comment by tmandry** [comment]
Thanks for providing the mentoring instructions, by the way!

**Comment by nathanwhit** [comment]
I'm interested in working on this (or rather, I've done some work on this based on the mentoring instructions) if that's okay. Based on what I've done so far, I think I'll be ready to submit a PR within the next day or so.

**Comment by nathanwhit** [comment]
To test the functionality, I updated the test for the `dbg!` macro (noted by @Centril) to use the new header flag. Would it be more reasonable to make a separate PR for that once these changes are approved, or could I include it in the same PR? Apologies if this is off-topic.

**Comment by Mark-Simulacrum** [comment]
Not at all! That seems like a reasonable change to make in the same PR, though it would be good to split it out into a separate commit for easier reviewing. Thanks!
