### ISSUE TITLE
Custom diagnostic for bad `mut` in pattern with sub-bindings

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#63764]
Given (as brought up in https://github.com/rust-lang/rust/pull/63693#discussion_r315926681 CC @Centril):
```
pub fn main() {
    struct Foo { x: isize }
    let mut Foo { x: x } = Foo { x: 3 };
}
```
[We currently emit a parse error](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=6d82fda1a1539a49791170dbba18a7e0):
```
error: expected one of `:`, `;`, `=`, or `@`, found `{`
 --> src/main.rs:3:17
  |
3 |     let mut Foo { x: x } = Foo { x: 3 };
  |                 ^ expected one of `:`, `;`, `=`, or `@` here
```

It should instead parse as if it were `let Foo { x: mut x } = Foo { x: 3 };` (medium priority), silence any complaints that `mut` is unnecessary (lower priority) and emit a custom error explaining that `mut` cannot lead a pattern with subpatterns (must have), and suggest the appropriate `mut` placement in the sub-bindings (nice to have):

```
error: incorrect `mut` pattern
 --> src/main.rs:3:17
  |
3 |     let mut Foo { x: x } = Foo { x: 3 };
  |         ^^^ patterns with sub-bindings can't be marked as `mut`
help: mark the individual sub-bindings as `mut` instead
3 |     let Foo { x: mut x } = Foo { x: 3 };
  |        --        ^^^
```

**Comment by Centril** [comment]
This should be relatively easy to do by hooking into https://github.com/rust-lang/rust/blob/bea0372a1a7a31b81f28cc4d9a83a2dc9a79d008/src/libsyntax/parse/parser/pat.rs#L289 or where it is called. If a `ref` token does not follow you simply call the recursive pattern parser and then once you have parsed a `PatKind` you walk (with a mutating visitor) to all the binding sites, insert a `mut` there, pretty print it and suggest the output.

**Comment by Centril** [comment]
Marking as blocked for now on https://github.com/rust-lang/rust/pull/63693 so we don't get a lot of conflicts.
