### ISSUE TITLE
benefits of using macro

### ISSUE THREAD

**Issue by nocord** [rust-lang/rust#63775]
macro makes code less readable. without macro the code is more predictable

**Comment by nocord** [comment]
even println! is a macro

**Comment by nocord** [comment]
They are making code less readable

**Comment by nocord** [comment]
One of problems that c/c++ have

**Comment by nocord** [comment]
stop the macro hell

**Comment by nocord** [comment]
also why you need `->` for specifying  return type. It's totally unnecessary

**Comment by nocord** [comment]
rust was created because C++ wasn't good. Which is right. This is also a reason behind Golang . but now go doesn't depend on other language. But Rust depends on C++. 
......

**Comment by nocord** [comment]
When i talk about this they tell me that this project doesn't have the goal of rewriting LLVM in Rust. Why you need LLVM? Can't you write your own compiler infrastructure?

**Comment by jonas-schievink** [comment]
Hi! Changes to the language or standard library need to go through our [RFC process](https://github.com/rust-lang/rfcs). Before an RFC is written, the feature can also be discussed in our [internals forum](https://internals.rust-lang.org/) to find other people interested in it.

Closing in favor of an RFC.

**Comment by nocord** [comment]
>Closing in favor of an RFC

This is one of the most annoying things in rust repo issue comment

**Comment by nocord** [comment]
Can't you make an rfc

**Comment by nocord** [comment]
One of my account is flagged because of this

**Comment by Lonami** [comment]
They have better things to do than writing RFCs for everyone's needs. If you want to propose a change, you go through the formal process like everyone else does. The account is probably flagged due to the amount of "spam" you are causing (you could write a single comment with all you have to say).

**Comment by BurntSushi** [comment]
I've also reported your account to GitHub. Please stop.
