### ISSUE TITLE
Compiler symbol resolution works when it shouldn't

### ISSUE THREAD

**Issue by Triavanicus** [rust-lang/rust#63785]
So here is the code that works when it shouldn't:
```rust
let m = unsafe { mem::transmute::<&mut [u8], &mut [u32]>(&mut chunk) };
#[cfg(target_endian = "big")]
for j in 0..16 {
    M[j] = M[j].swap_bytes();
}
```

And this doesn't work, as expected.
```rust
let m = unsafe { mem::transmute::<&mut [u8], &mut [u32]>(&mut chunk) };
//#[cfg(target_endian = "big")]
for j in 0..16 {
    M[j] = M[j].swap_bytes();
}
```

the symbol `M` gets resolved to `m` when `#[cfg(target_endian = "big)]` is present. I am currently running the latest stable msvc version of rust.
Edit: same on nightly.

![Capture0](https://user-images.githubusercontent.com/7131135/63435599-d4b76e00-c3ec-11e9-8357-43a401302781.PNG)
![Capture1](https://user-images.githubusercontent.com/7131135/63435600-d4b76e00-c3ec-11e9-8cbd-c1c00907f019.PNG)

**Comment by jonas-schievink** [comment]
What architecture are you building for?

**Comment by Triavanicus** [comment]
64 bit

**Comment by jonas-schievink** [comment]
`#[cfg(target_endian = "big")]` will be stripped before name resolution if the target architecture is little-endian, which x86(_64) is, so it's expected that this compiles. You can use `if cfg!(...)` instead to have the compiler check the code for any target.

**Comment by Triavanicus** [comment]
Ah, I see. Thanks for clearing that up.
