### ISSUE TITLE
&str->String in the docs

### ISSUE THREAD

**Issue by axil** [rust-lang/rust#63797]
This chunk was supposedly copy-pasted as is from `std::str::from_utf8`
https://github.com/rust-lang/rust/blob/bdfd698f37184da42254a03ed466ab1f90e6fb6c/src/liballoc/string.rs#L430-L432
It should read

    A String ([`String`]) is made of bytes

**Comment by sam09** [comment]
Hi there. Can I pick this up as first-timer task?
