### ISSUE TITLE
impl Display for Path

### ISSUE THREAD

**Issue by benw** [rust-lang/rust#63822]
It's deliberate that to date Path does not impl Display. It's a conservative stance that says that because the conversion to utf8 can be lossy, there isn't necessarily one obviously correct way to display a path.

I'd like to revisit that decision, in the interests of convenience. I can't imagine that anyone does anything other than call .display() or .to_string_lossy(). The current inconvenience might tend to encourage people to use &str/String rather than &Path/Pathbuf, which I think is a worse outcome. Also, impl Display for Path does not preclude anyone from providing a different way of displaying paths should they choose to.

**Comment by benw** [comment]
Also I'd be interested to hear whether @huonw's thoughts on this have changed since #15827.

**Comment by Mark-Simulacrum** [comment]
See most recent discussion in https://github.com/rust-lang/rust/pull/49868 -- nominating for T-libs but I suspect that they may (still) not have sufficient bandwidth to deal with this question.

**Comment by benw** [comment]
Ah thanks, I searched but failed to find that.

**Comment by benw** [comment]
Fwiw, after reading #49868 I am personally firmly in the camp of "Display means pretty-printing for user-visible output". I never understood Display to imply that roundtrip would be possible, and it's not obvious to me that "faithful representation" implies roundtrip.

However, I see that people with insight and experience have invested considerable effort in thinking and discussing this issue, it's certainly not trivial, and I'm glad to see that I'm not the only one thinking this is a pain point worth addressing.

Also, please don't panic, that would be awful.

**Comment by abonander** [comment]
Whether or not it's specified in the API contracts, I think there's a widespread expectation that a `Display` impl for a type will produce the original value when the result is passed to a corresponding `FromStr` (in this case, on `PathBuf`). I can't think of any existing types that go against this expectation. Maybe floats?

**Comment by alexcrichton** [comment]
I don't think enough has changed since https://github.com/rust-lang/rust/pull/49868 for us to reconsider this, so I'm going to close this.
