### ISSUE TITLE
How to disable rust runtime stack_overflow check

### ISSUE THREAD

**Issue by YangZhou1997** [rust-lang/rust#63826]
Hi community, 

I was using [GEM5](http://gem5.org/Main_Page) architecture simulator to run Rust binaries. However, GEM5 simulator does support syscall sigaltstack, which is called by libstd/sys/unix/stack_overflow.rs further by libstd/rt.rs (sys::stack_overflow::init()). 

I was wonder if I can disable the stack_overflow check in Rust libstd. I know there was an option in rustc: -C no-stack-check, but this is depreciated now. 

Any suggestions are appreciated! 

Best,
Yang

**Comment by nagisa** [comment]
You’ll need to create a new target for your simulator, adjust the so that this target does not use `sigaltstack` and compile your binary for your new target. Most of the compiler flags do not influence the behaviour of libstd.

**Comment by YangZhou1997** [comment]
@nagisa 
Thanks for the comments. I am using x86_64-unknown-linux-musl target for building static binaries. Is there any example or tutorial of build new target based on x86_64-unknown-linux-musl? say, how to specify configurations in config.toml under rust/

**Comment by nagisa** [comment]
Not aware of any tutorial, but [`xargo`](https://github.com/japaric/xargo) and a custom target json should be all you really need to have/do.

**Comment by nagisa** [comment]
xargo readme specifically has  a section on custom targets.

**Comment by YangZhou1997** [comment]
@nagisa 
Thanks for the suggestions. 

However, I fail in running Xargo :(. 
But I find I can build my own rustc using ./x.py build --target x86_64-unknown-linux-musl, and link it using: 
rustup toolchain link stage1 build/x86_64-unknown-linux-gnu/stage1
rustup toolchain link stage2 build/x86_64-unknown-linux-gnu/stage2

However, I can only build my project using cargo +stage1 build. 
Using cargo +stage2 build, or cargo +stage2 build --target x86_64-unknown-linux-musl will both fail. It shows can't find crate for `std`. 

I guess my building was not complete. Do you have any suggestion about it? 
Thanks in advance.

**Comment by Mark-Simulacrum** [comment]
You'll likely want to ask on users.rust-lang.org or internals.rust-lang.org; this is not the right place for general help (unlike those locations); so closing, since there is no bug here.
