### ISSUE TITLE
Is the comment re. unstable-book in `src/libsyntax/feature_gate/active.rs` still relevant?

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#63840]
See https://github.com/rust-lang/rust/pull/63824#discussion_r316941434.

The comment currently exists in `src/libsyntax/feature_gate.rs` but is being moved in the PR above to `src/libsyntax/feature_gate/active.rs`.

cc @oli-obk

**Comment by est31** [comment]
unstable-book-gen at least uses tidy which seems to have been updated by https://github.com/rust-lang/rust/commit/3cfb6bc73a429a67f87c6542de2b8f9395cf4b94

So any autogenerated unstable book page won't need any updates. Any non-autogenerated page will need one though as the tracking issue is hardcoded there. Changes that aren't detected automatically are for example when the tracking issue changes and the entry in the book is not updated. When the feature stabilizes, there is a tidy error though. So yes, active is a good place for that comment.

**Comment by Centril** [comment]
@oli-obk Seems the answer is "yes". I'll close this for now.
