### ISSUE TITLE
compiler

### ISSUE THREAD

**Issue by javad-salehi** [rust-lang/rust#63841]
my english is not good , So let's say by example.
let x = if {}{};//error:^ expected if condition here
let x = if{()}{};//error : ^^ expected bool, found ()
let x = if{return ()}{}:its correct and condition evaluated to false.but i think -> error:^^ expected bool, found ()
if it is correct why if{()} is incorrect.

**Comment by BO41** [comment]
you should use code blocks beginning and ending with \``` or \` :wink: 

```{ }``` are markers for code blocks.
`{ ( ) }` is equal to `( )` which isn't a bool.
`if { return () }` is also not an bool, but the `return` exits the current function, so not being a bool doesn't matter.
```rust
fn main() {
    let x = if{return}{};
    println!("bar");
}
```
^ in this example `println!` never gets called since the function is returned before.

**Comment by BO41** [comment]
```rust
warning: unreachable block in `if` expression
 --> src/main.rs:2:23
  |
2 |     let x = if{return}{println!("bar");};
  |                       ^^^^^^^^^^^^^^^^^^
  |
  = note: #[warn(unreachable_code)] on by default
```
though, the error message is a bit confusing. Not just the block _in_ the `if` expression is unreachable, but everything after `return`

**Comment by jonas-schievink** [comment]
Hi! This issue tracker is mainly meant for bug reports and concrete, small feature requests. Questions like this are better asked in the user forum at https://users.rust-lang.org/ or on [one of the chat platforms](https://www.rust-lang.org/community) used by the Rust community.
