### ISSUE TITLE
Lint for unused unstable feature gates

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#63850]
I've seen two codebases now that used to have unused feature gates:

* https://github.com/libra/libra/commit/2f44be56a14492be236ec30925dec3d5e31342ad (this commit was in july while duration_float stabilized in August)
* https://github.com/libra/libra/commit/e263fbdc1dd83305d9962d0c239d1f06e462b389
* https://github.com/nushell/nushell/pull/367

It would be cool to lint for feature gates that are still unstable but are not "used" by the codebase anywhere so they can be removed. That way, it's easy to know which nightly features a codebase actually still needs.

**Comment by joshtriplett** [comment]
I'd like to see this as well.

**Comment by Centril** [comment]
This seems reasonably added to the `unused` lint group as `unused_feature`.

It shouldn't be too complicated but it will require making sure that all the locations where feature gate checking is done is accounted for. Note that this is not just in `libsyntax/feature_gate/check.rs` but is also done in an ad-hoc fashion in later stages of compilation. To do this, you'll need to keep a set of used gates and then add features when gates were useful. This is a good opportunity to make the overall gating mechanisms less ad-hoc.

I'd be interested in hearing what @petrochenkov thinks about this from a technical POV though.

**Comment by varkor** [comment]
This used to exist — the tracking issue is https://github.com/rust-lang/rust/issues/44232.

**Comment by est31** [comment]
Oh I see. Closing as a dupe of #44232 then. I hope it gets fixed. @Centril could you put the nominated label onto that issue instead?
