### ISSUE TITLE
ICE trying to run cargo clippy on hello world lib.rs

### ISSUE THREAD

**Issue by nico-abram** [rust-lang/rust#63876]
I just tried running `cargo clippy` on the exercism rust track hello world (https://exercism.io)
I tried this code:

Here are the contents of the folder I'm trying to run it on: https://github.com/nico-abram/rust_test_exercism

I expected to see this happen: Clippy.

Instead, this happened: https://i.imgur.com/VFsT3ig.png . Backtrace: https://i.imgur.com/DYxGBaU.png . Log: https://github.com/nico-abram/rust_test_exercism/blob/master/error.log

## Meta

`rustc --version --verbose`:
rustc 1.38.0-nightly (60960a260 2019-08-12)
binary: rustc
commit-hash: 60960a260f7b5c695fd0717311d72ce62dd4eb43
commit-date: 2019-08-12
host: x86_64-pc-windows-msvc
release: 1.38.0-nightly
LLVM version: 9.0

Backtrace: https://github.com/nico-abram/rust_test_exercism/blob/master/error.log

I'm on windows 7 64 bit.

**Comment by hellow554** [comment]
Could you please put the baktrace and error message as text here, instead of an image, use a three backticks block to format the text block, like this:

\`\`\`
your error reporting message
goes here
all along
\`\`\`

**Comment by mati865** [comment]
I suppose it's the same underlying issue as in https://github.com/rust-lang/rust/issues/62717
There is no nightly with Clippy and this fix yet.
