### ISSUE TITLE
#[unwind(aborts)] does nothing on `extern "Rust" fn`

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#63883]
I would expect the following code to abort, and never print `Hello`:
```rust
#![feature(unwind_attributes)]

#[unwind(aborts)]
fn foo() { // implicitly: extern "Rust"
    panic!("foooo");
}

fn main() {
    if let Err(_) = std::panic::catch_unwind(|| foo()) {}
    println!("Hello");
}
```
But instead, the `unwind` attribute [is ignored](https://github.com/rust-lang/rust/blob/d760df5aea483aae041c9a241e7acacf48f75035/src/librustc_mir/build/mod.rs#L490).

Cc @gnzlbg

**Comment by gnzlbg** [comment]
That looks like a bug. cc @eddyb @alexcrichton

**Comment by eddyb** [comment]
`extern "Rust" fn` is just `fn`, and having `extern "Rust"` in the testcase may create the wrong impression (i.e. this bug has nothing to do with FFI).

Still, the attribute should either work and cause an abort *or* error as unapplicable.

**Comment by RalfJung** [comment]
I deliberately made it explicit, but sure, I can adjust the example.
