### ISSUE TITLE
[1.38] Regression: lifetime name `'s` declared twice in the same scope

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rust#63886]
https://github.com/rust-lang/rust/issues/63628#issuecomment-524585351

>lifetime name `'s` declared twice in the same scope

>lifetime name `'input` declared twice in the same scope

```
./reg/cff/0.5.0/beta-2019-08-13.txt:[INFO] [stderr] error[E0263]: lifetime name `'s` declared twice in the same scope
./reg/sfnt/0.12.0/beta-2019-08-13.txt:[INFO] [stderr] error[E0263]: lifetime name `'s` declared twice in the same scope
./reg/tarrasque/0.10.0/beta-2019-08-13.txt:[INFO] [stderr] error[E0263]: lifetime name `'s` declared twice in the same scope

./reg/reformation/0.4.1/beta-2019-08-13.txt:[INFO] [stdout] error[E0263]: lifetime name `'input` declared twice in the same scope
```

@matthewjasper explains what happens in https://github.com/rust-lang/rust/issues/63628#issuecomment-524610919.

**Comment by nikomatsakis** [comment]
This is a result of https://github.com/rust-lang/rust/pull/63083, which was a (largely) bug fix that made lifetime parameters use hygiene in a comparable way to other things. Nominating for lang but recommendation is "won't fix".

**Comment by nikomatsakis** [comment]
We discussed this in the [Sep 05](https://paper.dropbox.com/doc/T-Lang-Meeting-2019.09.05--AkmYatur2MDikhHZuCgppWpxAg-qA0w3GsE7WJMX3v05orXV) @rust-lang/lang meeting and decided this is a "bug fix" and hence "won't fix" is the appropriate result. Closing.
