### ISSUE TITLE
[1.38] Regression: expected open delimiter

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rust#63889]
https://github.com/rust-lang/rust/issues/63628#issuecomment-524587696

>expected open delimiter

```
./reg/dtolnay/0.0.2/beta-2019-08-13.txt:[INFO] [stderr] error: expected open delimiter
```

Expected breakage of an unstable feature (`my_macro! name { ... }` no longer parses), caused by https://github.com/rust-lang/rust/pull/62258.

**Comment by nikomatsakis** [comment]
Closing as expected and acceptable (unstable feature).
