### ISSUE TITLE
[1.38] Regression: attributes starting with `rustc` are reserved for use by the `rustc` compiler

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rust#63887]
https://github.com/rust-lang/rust/issues/63628#issuecomment-524586506

>attributes starting with `rustc` are reserved for use by the `rustc` compiler

```
./reg/select-rustc/0.1.2/beta-2019-08-13.txt:[INFO] [stdout] error[E0658]: attributes starting with `rustc` are reserved for use by the `rustc` compiler
```

Expected breakage from https://github.com/rust-lang/rust/pull/62133, attributes of the form `rustc::anything` are now reserved for `rustc`.

**Comment by nikomatsakis** [comment]
Check-in from compiler team:

Closing as expected.
