### ISSUE TITLE
Rust Installer: OS Error 649: The create operation failed because the name contained at ...

### ISSUE THREAD

**Issue by nabeghe** [rust-lang/rust#63898]
I got the below information when installing the rustup-init.exe

<pre>
error: component download failed for rustc-x86_64-pc-windows-msvc
info: caused by: could not rename downloaded file from 'C:\Users\Hadi\.rustup\downloads\923e829d67102e45fc16eeae727a4dad13f7abe6239b99fef0e4a233c7509880.partial' to 'C:\Users\Hadi\.rustup\downloads\923e829d67102e45fc16eeae727a4dad13f7abe6239b99fef0e4a233c7509880'
info: caused by: The create operation failed because the name contained at least one mount point which resolves to a volume to which the specified device object is not attached. (os error 649)
</pre>
what's wrong?!

**Comment by jonas-schievink** [comment]
Thanks for the report! This looks like a bug in rustup, so please file it over here: https://github.com/rust-lang/rustup.rs/
