### ISSUE TITLE
[1.38] Regression: cannot determine resolution for the derive macro `Debug`

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rust#63893]
https://github.com/rust-lang/rust/issues/63628#issuecomment-524636403

>cannot determine resolution for the derive macro `Debug`

```
./reg/ruroonga_command/0.3.4/beta-2019-08-13.txt:[INFO] [stderr] error: cannot determine resolution for the derive macro `Debug`
```

Minimized:
```rust
use Enum::Debug;

#[derive(Debug)] // Add some more derives if the error does not reproduce
enum Enum {
    Debug
}
```
This is a regression from https://github.com/rust-lang/rust/pull/63248, and https://github.com/rust-lang/rust/pull/63867 works in the same direction but hasn't landed yet.

Basically, the import is blocked until the derive is expanded and the derive is blocked until the import is resolved, so we have a deadlock.

This worked previously, because we did some things in less principled way (textual comparisons instead of resolution), which allowed us to produce the `enum` earlier, before resolving the `Debug`, but now we need to resolve it before producing the `Enum`.

This is fixable in principle, by making the expansion infra more fine-grained (introducing some new "resolved, but not yet ready for expansion" states), but I'm afraid that's not something that could be backported to beta.
So, I'd say wontfix. Unfortunate, but seems acceptable given the number of affected crates (one regression found).

**Comment by nikomatsakis** [comment]
Nominating for lang team to check-in, but recommendation from @petrochenkov is to mark this as "won't fix".

**Comment by nikomatsakis** [comment]
In the @rust-lang/lang meeting on [Sep 05](https://paper.dropbox.com/doc/T-Lang-Meeting-2019.09.05--AkmYatur2MDikhHZuCgppWpxAg-qA0w3GsE7WJMX3v05orXV), we decided that "won't fix" was an appropriate decision.
