### ISSUE TITLE
[1.38] Regression: custom attribute panicked

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rust#63895]
https://github.com/rust-lang/rust/issues/63628#issuecomment-524641889

>custom attribute panicked

```
[INFO] [stderr]    Compiling display-as v0.4.6 (/opt/crater/workdir)
[INFO] [stderr] error: custom attribute panicked
[INFO] [stderr]    --> tests/format_as.rs:104:5
[INFO] [stderr]     |
[INFO] [stderr] 104 |     #[with_template("Foo " self.0)]
[INFO] [stderr]     |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[INFO] [stderr]     |
[INFO] [stderr]     = help: message: with_template must be applied to an impl that ends in '{}', not { }
```

One more victim to the pretty-printing changes (https://github.com/rust-lang/rust/pull/62667), whitespace-related in this case.

Here's what the macro does:
```rust
    if last.to_string() != "{  }" {
        /* report error */
    }
```
Pretty unreliable check, isn't it?

**Comment by estebank** [comment]
I feel this is a reasonable breaking change.

**Comment by nikomatsakis** [comment]
Discussed in [compiler triage meeting today](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/weekly.20meeting.202019-09-05.20.2354818/near/174976832). Closing as expected and reasonable.
