### ISSUE TITLE
[1.38] Regression: proc-macro derive panicked

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rust#63896]
https://github.com/rust-lang/rust/issues/63628#issuecomment-524643597

>proc-macro derive panicked

```
[INFO] [stderr] error: proc-macro derive panicked
[INFO] [stderr]   --> src/lib.rs:11:1
[INFO] [stderr]    |
[INFO] [stderr] 11 | / proc_macro_item_decl! {
[INFO] [stderr] 12 | |     /// Generates a default blanket impl for a generic trait that gets passed into
[INFO] [stderr] 13 | |     /// `autoimpl!`, with the same type parameters and type bounds as its trait.
[INFO] [stderr] 14 | |     ///
[INFO] [stderr] ...  |
[INFO] [stderr] 44 | |     autoimpl! => generate_auto_impl_impl
[INFO] [stderr] 45 | | }
[INFO] [stderr]    | |_^
[INFO] [stderr]    |
[INFO] [stderr]    = help: message: assertion failed: `(left == right)`
[INFO] [stderr]              left: `Some("#[allow(unused,")`,
[INFO] [stderr]             right: `Some("#[allow(unused")`
```

All of the 62 regressions are due to old versions of `proc-macro-hack` having an assert expecting `#[allow(unused,` instead of `#[allow(unused ,`.
So this is again a consequence of whitespace changes in pretty-printing (https://github.com/rust-lang/rust/pull/62667).

I think we should be able to fix this by special casing the comma token during token stream pretty-printing and not printing the space before it.

**Comment by petrochenkov** [comment]
Fixed in https://github.com/rust-lang/rust/pull/63897.

**Comment by nikomatsakis** [comment]
Just FYI, we discussed this in the [Sep 05](https://paper.dropbox.com/doc/T-Lang-Meeting-2019.09.05--AkmYatur2MDikhHZuCgppWpxAg-qA0w3GsE7WJMX3v05orXV) @rust-lang/lang meeting. We felt like the action here was appropriate -- while in general we do not guarantee stability of pretty printing, it makes sense to be judicious, and in this *particular* case not having a leading space before `,` just looks better anyway. 😛
