### ISSUE TITLE
Collect occurrences of `{}` for mismatched braces diagnostic

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#63904]
Many editors _helpfully_ auto close delimiters when writing them down. It is not uncommon for this to cause the following to occur:
```
fn main() {}
    let _ = ();
}
```

It'd be a good idea for the parser or lexer to keep track of these empty blocks to provide an error closer to

```
error: unexpected close delimiter: `}`
 --> src/main.rs:3:1
  |
1 | fn main() {}
  |           -- this block is empty, you might have not meant to close it
2 |     let _ = ();
3 | }
  | ^ unexpected close delimiter
```

**Comment by PramodBisht** [comment]
@estebank can I take this on, if nobody is working on this?

**Comment by XiangQingW** [comment]
@PramodBisht Are you still working on this? I'm happy to take it if not.

**Comment by PramodBisht** [comment]
@XiangQingW Please allow me 2-3 days to check this issue.

**Comment by PramodBisht** [comment]
@XiangQingW Please take this forward.

**Comment by XiangQingW** [comment]
> @XiangQingW Please take this forward.

Ok, I'll try to dive into.
