### ISSUE TITLE
ICE having include! in code from stdin when calling rustc

### ISSUE THREAD

**Issue by andjo403** [rust-lang/rust#63900]
to reproduce the fault this can be used: 
`echo 'include!("auxiliary/empty.rs"); pub fn main(){}' | rustc - `

will result in this ICE:

`thread 'rustc' panicked at 'cannot resolve relative path in non-file source ', src/libsyntax/ext/source_util.rs:189:22 note: Run with RUST_BACKTRACE=1 environment variable to display a backtrace.
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: rustc 1.36.0 (a53f9df 2019-07-03) running on x86_64-unknown-linux-gnu`

the question is what is the path that shall be used when the code is from stdin maybe some temp file name in the currrent working dir.

**Comment by mystor** [comment]
This ICE also occurs when using `include_bytes!` and `include_str!`, which makes sense as they use the same mechanism under the hood ([`include`](https://github.com/rust-lang/rust/blob/e5b8c118a38e8f3319813de56386bf43751582d7/src/libsyntax_ext/source_util.rs#L79), [`include_str`](https://github.com/rust-lang/rust/blob/e5b8c118a38e8f3319813de56386bf43751582d7/src/libsyntax_ext/source_util.rs#L125), [`include_bytes`](https://github.com/rust-lang/rust/blob/e5b8c118a38e8f3319813de56386bf43751582d7/src/libsyntax_ext/source_util.rs#L150)). The mechanism is also used by [`#[doc(include="x")]`](https://github.com/rust-lang/rust/blob/e5b8c118a38e8f3319813de56386bf43751582d7/src/libsyntax_expand/expand.rs#L1421), meaning it also [ICEs](https://github.com/rust-lang/rust/blob/e5b8c118a38e8f3319813de56386bf43751582d7/src/libsyntax_expand/base.rs#L1085).

```bash
$ echo 'include_str!("x");' | rustc -
thread 'rustc' panicked at 'cannot resolve relative path in non-file source `<anon>`'
$ echo 'include_bytes!("x");' | rustc -
thread 'rustc' panicked at 'cannot resolve relative path in non-file source `<anon>`'
$ echo '#![feature(external_doc)] #![doc(include="x")]' | rustc -
thread 'rustc' panicked at 'cannot resolve relative path in non-file source `<anon>`'
```

**Comment by mystor** [comment]
While poking at this I also noticed that `mod foo;` items are silently ignored, and filed #65601.
