### ISSUE TITLE
Default sysconfdir

### ISSUE THREAD

**Issue by Lord-Kamina** [rust-lang/rust#63915]
I'm not sure this is actually a bug but it seems like it could be. The default sysconfdir in config.toml is `/etc`; which means it bypasses the user-defined prefix, in turn resulting in the installation failing if not running as root (even when installing to a user folder or, as was my case, the tree for a package manager or whatever)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jyn514** [comment]
The docs for `sysconfdir` say:
```toml
# Where to install system configuration files
# If this is a relative path, it will get installed in `prefix` above
#sysconfdir = "/etc"
```
So I don't think this is a bug; if you want to install to `/usr/local/etc`, you can set `sysconfdir = "etc"` instead.
