### ISSUE TITLE
linking with `cc` failed: exit code: 1

### ISSUE THREAD

**Issue by IThawk** [rust-lang/rust#63910]
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/opt/rust/target/debug/build/log-2c3a5c1cf08eb014/build_script_build-2c3a5c1cf08eb014.build_script_build.tzwt6ic0-cgu.0.rcgu.o" "/opt/rust/target/debug/build/log-2c3a5c1cf08eb014/build_script_build-2c3a5c1cf08eb014.build_script_build.tzwt6ic0-cgu.1.rcgu.o" "/opt/rust/target/debug/build/log-2c3a5c1cf08eb014/build_script_build-2c3a5c1cf08eb014.build_script_build.tzwt6ic0-cgu.10.rcgu.o" "/opt/rust/target/debug/build/log-2c3a5c1cf08eb014/build_script_build-2c3a5c1cf08eb014.build_script_build.tzwt6ic0-cgu.11.rcgu.o" "/opt/rust/target/debug/build/log-2c3a5c1cf08eb014/build_script_build-2c3a5c1cf08eb014.build_script_build.tzwt6ic0-cgu.12.rcgu.o" "/opt/rust/target/debug/build/log-2c3a5c1cf08eb014/build_script_build-2c3a5c1cf08eb014.build_script_build.tzwt6ic0-cgu.13.rcgu.o" "/opt/rust/target/debug/build/log-2c3a5c1cf08eb014/build_script_build-2c3a5c1cf08eb014.build_script_build.tzwt6ic0-cgu.14.rcgu.o" "/opt/rust/target/debug/build/log-2c3a5c1cf08eb014/build_script_build-2c3a5c1cf08eb014.build_script_build.tzwt6ic0-cgu.15.rcgu.o" "/opt/rust/target/debug/build/log-2c3a5c1cf08eb014/build_script_build-2c3a5c1cf08eb014.build_script_build.tzwt6ic0-cgu.2.rcgu.o" "/opt/rust/target/debug/build/log-2c3a5c1cf08eb014/build_script_build-2c3a5c1cf08eb014.build_script_build.tzwt6ic0-cgu.3.rcgu.o" "/opt/rust/target/debug/build/log-2c3a5c1cf08eb014/build_script_build-2c3a5c1cf08eb014.build_script_build.tzwt6ic0-cgu.4.rcgu.o" "/opt/rust/target/debug/build/log-2c3a5c1cf08eb014/build_script_build-2c3a5c1cf08eb014.build_script_build.tzwt6ic0-cgu.5.rcgu.o" "/opt/rust/target/debug/build/log-2c3a5c1cf08eb014/build_script_build-2c3a5c1cf08eb014.build_script_build.tzwt6ic0-cgu.6.rcgu.o" "/opt/rust/target/debug/build/log-2c3a5c1cf08eb014/build_script_build-2c3a5c1cf08eb014.build_script_build.tzwt6ic0-cgu.7.rcgu.o" "/opt/rust/target/debug/build/log-2c3a5c1cf08eb014/build_script_build-2c3a5c1cf08eb014.build_script_build.tzwt6ic0-cgu.8.rcgu.o" "/opt/rust/target/debug/build/log-2c3a5c1cf08eb014/build_script_build-2c3a5c1cf08eb014.build_script_build.tzwt6ic0-cgu.9.rcgu.o" "-o" "/opt/rust/target/debug/build/log-2c3a5c1cf08eb014/build_script_build-2c3a5c1cf08eb014" "/opt/rust/target/debug/build/log-2c3a5c1cf08eb014/build_script_build-2c3a5c1cf08eb014.43x3k5trofy6u2hs.rcgu.o" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-nodefaultlibs" "-L" "/opt/rust/target/debug/deps" "-L" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,--start-group" "-Wl,-Bstatic" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-4a76ff35a356aedf.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-e11c7b3b3225afe2.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libbacktrace-13217ede3d276f16.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libbacktrace_sys-621a9ee22da6caa1.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-546c844e8071bbeb.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-be9569e4d599746f.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-47d8845cef2a3bc5.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-017511bce73a530c.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-be7979c57a08057b.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-d6459c4f0817c67c.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-580035dd98451925.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-aee5c24fff305dea.rlib" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-8a55a4098920125a.rlib" "-Wl,--end-group" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-9fc4b5be2ba5cc19.rlib" "-Wl,-Bdynamic" "-ldl" "-lrt" "-lpthread" "-lgcc_s" "-lc" "-lm" "-lrt" "-lpthread" "-lutil" "-lutil"
  = note: collect2: fatal error: cannot find 'ld'
          compilation terminated.

**Comment by IThawk** [comment]
Compiling proc-macro2 v1.0.1
       Fresh unicode-xid v0.2.0
   Compiling syn v1.0.4
       Fresh semver-parser v0.7.0
       Fresh autocfg v0.1.6
   Compiling libc v0.2.62
   Compiling serde v1.0.99
       Fresh rand_core v0.4.2
     Running `rustc --edition=2018 --crate-name build_script_build /root/.cargo/registry/src/mirrors.ustc.edu.cn-15f9db60536bad60/proc-macro2-1.0.1/build.rs --color always --crate-type bin --emit=dep-info,link -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="proc-macro"' -C metadata=c075aa345fbb329f -C extra-filename=-c075aa345fbb329f --out-dir /opt/rust/target/debug/build/proc-macro2-c075aa345fbb329f -L dependency=/opt/rust/target/debug/deps --cap-lints allow`
     Running `rustc --edition=2018 --crate-name build_script_build /root/.cargo/registry/src/mirrors.ustc.edu.cn-15f9db60536bad60/syn-1.0.4/build.rs --color always --crate-type bin --emit=dep-info,link -C debuginfo=2 --cfg 'feature="clone-impls"' --cfg 'feature="default"' --cfg 'feature="derive"' --cfg 'feature="parsing"' --cfg 'feature="printing"' --cfg 'feature="proc-macro"' --cfg 'feature="quote"' --cfg 'feature="visit"' -C metadata=cb8b7ff7e80c231c -C extra-filename=-cb8b7ff7e80c231c --out-dir /opt/rust/target/debug/build/syn-cb8b7ff7e80c231c -L dependency=/opt/rust/target/debug/deps --cap-lints allow`
     Running `rustc --crate-name build_script_build /root/.cargo/registry/src/mirrors.ustc.edu.cn-15f9db60536bad60/serde-1.0.99/build.rs --color always --crate-type bin --emit=dep-info,link -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="derive"' --cfg 'feature="serde_derive"' --cfg 'feature="std"' -C metadata=4fde228495b44b98 -C extra-filename=-4fde228495b44b98 --out-dir /opt/rust/target/debug/build/serde-4fde228495b44b98 -L dependency=/opt/rust/target/debug/deps --cap-lints allow`
   Compiling byteorder v1.3.2
   Compiling arrayvec v0.4.11
       Fresh lazy_static v1.4.0
       Fresh stable_deref_trait v1.1.1
     Running `rustc --crate-name build_script_build /root/.cargo/registry/src/mirrors.ustc.edu.cn-15f9db60536bad60/byteorder-1.3.2/build.rs --color always --crate-type bin --emit=dep-info,link -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=91a250bc51984d46 -C extra-filename=-91a250bc51984d46 --out-dir /opt/rust/target/debug/build/byteorder-91a250bc51984d46 -L dependency=/opt/rust/target/debug/deps --cap-lints allow`
     Running `rustc --crate-name build_script_build /root/.cargo/registry/src/mirrors.ustc.edu.cn-15f9db60536bad60/arrayvec-0.4.11/build.rs --color always --crate-type bin --emit=dep-info,link -C debuginfo=2 --cfg 'feature="array-sizes-33-128"' --cfg 'feature="default"' --cfg 'feature="serde"' --cfg 'feature="serde-1"' --cfg 'feature="std"' -C metadata=93de4411de92eb23 -C extra-filename=-93de4411de92eb23 --out-dir /opt/rust/target/debug/build/arrayvec-93de4411de92eb23 -L dependency=/opt/rust/target/debug/deps --cap-lints allow`
       Fresh nodrop v0.1.13
   Compiling log v0.4.8
       Fresh cfg-if v0.1.9
     Running `rustc --crate-name build_script_build /root/.cargo/registry/src/mirrors.ustc.edu.cn-15f9db60536bad60/libc-0.2.62/build.rs --color always --crate-type bin --emit=dep-info,link -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="std"' -C metadata=a1fcfd5405a3b144 -C extra-filename=-a1fcfd5405a3b144 --out-dir /opt/rust/target/debug/build/libc-a1fcfd5405a3b144 -L dependency=/opt/rust/target/debug/deps --cap-lints allow`
     Running `rustc --crate-name build_script_build /root/.cargo/registry/src/mirrors.ustc.edu.cn-15f9db60536bad60/log-0.4.8/build.rs --color always --crate-type bin --emit=dep-info,link -C debuginfo=2 --cfg 'feature="release_max_level_info"' --cfg 'feature="std"' -C metadata=2c3a5c1cf08eb014 -C extra-filename=-2c3a5c1cf08eb014 --out-dir /opt/rust/target/debug/build/log-2c3a5c1cf08eb014 -L dependency=/opt/rust/target/debug/deps --cap-lints allow`
       Fresh smallvec v0.6.10
       Fresh scopeguard v0.3.3
       Fresh scopeguard v1.0.0
   Compiling proc-macro2 v0.4.30
     Running `rustc --crate-name build_script_build /root/.cargo/registry/src/mirrors.ustc.edu.cn-15f9db60536bad60/proc-macro2-0.4.30/build.rs --color always --crate-type bin --emit=dep-info,link -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="proc-macro"' -C metadata=545a37a69fc3c974 -C extra-filename=-545a37a69fc3c974 --out-dir /opt/rust/target/debug/build/proc-macro2-545a37a69fc3c974 -L dependency=/opt/rust/target/debug/deps --cap-lints allow`

**Comment by jonas-schievink** [comment]
@IThawk What are you trying to build? This looks like your native toolchain is broken (`cc` can't find `ld`). How did you install Rust?

**Comment by IThawk** [comment]
use rustup_init

**Comment by crlf0710** [comment]
If you're using linux, you can install `binutils` and try again.

**Comment by IThawk** [comment]
thank you very much.  i use "yum install binutils"   solve this problem
