### ISSUE TITLE
Migrate test suite to use run-pass stdout/stderr testing

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#63924]
Where possible, we should prefer to use the functionality added by https://github.com/rust-lang/rust/pull/63825 instead of `std::process` and the like. At least one such test is known, but it's possible more can be found.

**Comment by RalfJung** [comment]
> verify we're ignoring cloudabi, emscripten, and sgx in all of them

It does not at all seem like we do:
```
$ rg run-pass src/test/ui | wc -l
3200
$ rg ignore-cloudabi src/test/ui | wc -l
82
```

**Comment by RalfJung** [comment]
I think that file changed in https://github.com/rust-lang/rust/pull/63825 was ignored just because it uses `process` -- but just running the test seems to work fine on those platforms. I suppose CI has some way to cross-run them and compiletest uses that?

**Comment by RalfJung** [comment]
That's how I initially read that comment, and I still do, yes.

**Comment by RalfJung** [comment]
Well I think we want to remove those `ignore` from the test that got changed in https://github.com/rust-lang/rust/pull/63825.

**Comment by RalfJung** [comment]
Well, that PR hasn't landed yet, so you could just r- and ask the author to remove the ignore?

I can't even open a PR to fix this until that PR landed.^^

**Comment by RalfJung** [comment]
Thanks a lot!

**Comment by RalfJung** [comment]
@Mark-Simulacrum I only just saw you changed the bug title... I guess I should reopen as you repurposed the issue? Or would it make more sense to open a new one, as the existing discussion here will be rather confusing?
