### ISSUE TITLE
redundant_semicolon and clippy::no_effect tripped without emitting line numbers

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#63967]
Using nightly-2019-08-26.

In [this TiKV PR](https://github.com/tikv/tikv/pull/5261#issuecomment-525569617) we upgraded the compiler. Our tidb_query component tripped the redundant_semicolon lint (and seemingly in turn clippy::no_effect) but rustc/clippy did not tell us the line number.

I couldn't find the code that triggered the lint and had to just allow both for the whole crate.

This issue has been assigned to @nathanwhit via [this comment](https://github.com/rust-lang/rust/issues/63967#issuecomment-528487292).

**Comment by estebank** [comment]
Introduced in https://github.com/rust-lang/rust/pull/62984. It has caused similar effects in other cases like https://github.com/rust-lang/rust/issues/63947. CC https://github.com/rust-lang/rust/issues/63679.

**Comment by Centril** [comment]
cc @nathanwhit @varkor

**Comment by nikomatsakis** [comment]
Check-in from compiler team:

Marking as P-high " as this is a regression, though admittedly one without particularly serious consequences (the lint can always be allowed). 

@nathanwhit or @varkor, perhaps one of you can take a stab at this? Please [claim the issue](https://github.com/rust-lang/triagebot/wiki/Assignment) if you do start working on it (even if it's just to write mentoring instructions).

**Comment by nikomatsakis** [comment]
Also, it'd be great to get a minimized version of the problem. Therefore, marking as E-needs-mvce.

**Comment by nathanwhit** [comment]
I'll work on this. Looking into it a bit, I think it has to do with the lint's interaction with custom proc macro attributes. Specifically, when the item `TokenStream` passed to the attribute contains a redundant semicolon, every span in the `TokenStream` is the dummy span. This occurs in both this issue and #63947. It's definitely due to the changes to the parser, but I'm not sure why the changes would have that effect on the spans.
@rustbot claim

**Comment by pnkfelix** [comment]
@nathanwhit just in case you didn't see, the attempt to fix this with your PR #64387 failed the rollup, see https://github.com/rust-lang/rust/pull/64387#issuecomment-533755695
