### ISSUE TITLE
Unify errors for Unit pattern on Tuple and Struct variants

### ISSUE THREAD

**Issue by djrenren** [rust-lang/rust#63983]
Code Example ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=73d19f6e2a08205bb03e3741d6588de5)):
```
enum MyEnum {
    Tuple(i32),
    Struct { s: i32 },
}

fn foo(en: MyEnum) {
    match en {
        MyEnum::Tuple => "",
        MyEnum::Struct => "",
    };
}
```

<img width="805" alt="image" src="https://user-images.githubusercontent.com/634666/63895019-e7a8e000-c9a2-11e9-8639-5ea535061734.png">

Currently we provide a "do you mean..." for the `Struct` but not for the `Tuple`. We probably should provide one for both.

**Comment by Phosphorus15** [comment]
Consider fixing #63988 Btw (which is a similar enhancement)

**Comment by almielczarek** [comment]
I'd like to work on this if it is still available.

**Comment by estebank** [comment]
@almielczarek go ahead!

Ideally, you could turn the output into

```
error[E0532]: expected unit struct/variant or constant, found tuple variant `MyEnum::Tuple`
 --> src/lib.rs:8:9
  |
8 |         MyEnum::Tuple => "",
  |         ^^^^^^^^^^^^^ help: missing arguments: `MyEnum::Tuple(_)`

error[E0532]: expected unit struct/variant or constant, found struct variant `MyEnum::Struct`
 --> src/lib.rs:9:9
  |
9 |         MyEnum::Struct => "",
  |         ^^^^^^^^^^^^^^ help: missing struct fields: `MyEnum::Struct { s }`
```

but just changing the tuple case would be enough.

**Comment by guanqun** [comment]
@estebank  I created a PR, could you please help review. I took a look at your suggestion of updating all the errors to `help: missing struct fields..`, that seemed too many changes, not sure if it was necessary, so I just added the tuple case.
