### ISSUE TITLE
async-await: mutually recursive functions compile sometimes

### ISSUE THREAD

**Issue by mb64** [rust-lang/rust#64004]
In the following code:

```rust
async fn rec_1() {
    rec_2().await;
}

async fn rec_2() {
    rec_1().await;
}
```

This gives an error when it is a part of a `lib` crate.  However, as a part of a `bin` crate, it compiles.

Here's an [erroneously compiling playground link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&code=async%20fn%20rec_1()%20%7B%0A%20%20%20%20rec_2().await%3B%0A%7D%0A%0Aasync%20fn%20rec_2()%20%7B%0A%20%20%20%20rec_1().await%3B%0A%7D%0A%0Afn%20main()%20%7B%7D) and a [correctly erroring playground link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&code=async%20fn%20rec_1()%20%7B%0A%20%20%20%20rec_2().await%3B%0A%7D%0A%0Aasync%20fn%20rec_2()%20%7B%0A%20%20%20%20rec_1().await%3B%0A%7D)

**Comment by MSleepyPanda** [comment]
I guess that's because in the binary, it knows that it will be unused. If you were to actually use it, it [errors](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=e3363513b1985785a3b8cdc5aa59c938)

**Comment by cramertj** [comment]
Tagging as blocking because fixing this is a potential future-compat hazard.
