### ISSUE TITLE
Why can't update libc to 0.2.63 or 0.2.64?

### ISSUE THREAD

**Issue by BaoshanPang** [rust-lang/rust#64009]
I notice by default we are using libc 0.2.61. and we can update it to 0.2.62 if using "cargo update -p libc".
But I see the latest libc version is 0.2.64. Is there any special reason that prevent us from using the version 0.2.63 or version 0.2.64?

Thanks,
Baoshan

**Comment by Mark-Simulacrum** [comment]
Concretely, no, but any changes to Cargo.lock in rust-lang/rust usually uncover edge cases. PRs are the best way to update dependencies.

Closing.
