### ISSUE TITLE
Matches on tuples of boxes present incorrect dereference help text

### ISSUE THREAD

**Issue by djrenren** [rust-lang/rust#64024]
Consider the following broken code([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=f9637cf1265ffb17eeac765c000ba345)):

```rust
struct S(i32);

fn main() {
    let x = Box::new(S(1));
    let y = Box::new(S(2));
    let f = match (x, y) {
        (S(a), S(b)) => (a,b),
        _ => (1,2)
    };
}
```

We get this error message:
![image](https://user-images.githubusercontent.com/634666/64049296-35e7eb80-cb29-11e9-9622-058ba7d747ce.png)

The suggested fix is to deref `*(x,y)` which is invalid. It should be `(*x, *y)`.

NOTE: This is a minimal example because for some reason, this help text doesn't appear on unit structs.

**Comment by zackmdavis** [comment]
(Not "mentoring" exactly, but at least preliminary grep and code-reading research—)

The suggestion is issued here:

https://github.com/rust-lang/rust/blob/fba38ac27e2ade309f4c2504a6d6cd3556972a28/src/librustc/infer/error_reporting/mod.rs#L610-L620

The `MatchExpressionArmPattern` obligation seems to be coming from here:

https://github.com/rust-lang/rust/blob/fba38ac27e2ade309f4c2504a6d6cd3556972a28/src/librustc_typeck/check/demand.rs#L75-L79

**Comment by ldm0** [comment]
Update:
It suggest nothing now:
```
error[E0308]: mismatched types
 --> src/main.rs:7:10
  |
6 |     let f = match (x, y) {
  |                   ------ this expression has type `(std::boxed::Box<S>, std::boxed::Box<S>)`
7 |         (S(a), S(b)) => (a,b),
  |          ^^^^ expected struct `std::boxed::Box`, found struct `S`
  |
  = note: expected struct `std::boxed::Box<S>`
             found struct `S`

error[E0308]: mismatched types
 --> src/main.rs:7:16
  |
6 |     let f = match (x, y) {
  |                   ------ this expression has type `(std::boxed::Box<S>, std::boxed::Box<S>)`
7 |         (S(a), S(b)) => (a,b),
  |                ^^^^ expected struct `std::boxed::Box`, found struct `S`
  |
  = note: expected struct `std::boxed::Box<S>`
             found struct `S`

error: aborting due to 2 previous errors
```

**Comment by rylev** [comment]
Closing since the incorrect help text is no longer being suggested.
