### ISSUE TITLE
RangeBounds<T> impl for Range*<&T> is missing ?Sized

### ISSUE THREAD

**Issue by talchas** [rust-lang/rust#64027]
Much like the impl for `(Bounds<&T>, Bounds<&T>)`,  `impl<T> RangeBounds<T> for RangeFrom<&T> {` could use a `T: ?Sized`. This would allow
```rust
let map = BTreeMap::<String, i32>::new()
map.range::<str, _>("a"..);
```
to compile the way it does when using Bound. (Unfortunately I think the turbofish is still needed, and I don't see any better way to use range on a String)

(Range and RangeTo of course also would want this)

**Comment by kennethbgoodin** [comment]
This sounds straightforward -- would this be a good issue for someone relatively new to contributing?

**Comment by Mark-Simulacrum** [comment]
Yes, I think a PR here is the best way to go, probably we'd want to add `?Sized` to all the RangeBounds impls

**Comment by ThatsNoMoon** [comment]
Based on the reception to https://github.com/rust-lang/rust/pull/64327, should this be closed? I ran into this trying to use `BTreeMap::range`, but it doesn't seem like this implementation is practical/desired.

**Comment by Dylan-DPC** [comment]
Closing this based on the comments in #64327
