### ISSUE TITLE
vec![] creates broken vector of tuples with nulls in memory if a lot of elements passed.

### ISSUE THREAD

**Issue by starfear** [rust-lang/rust#64055]
**Description:** for example I can create vector with over 50K elements, using vec![/* elements */];
When I iterate values in vector I can meet that my tuple value is null (0), and next values will be null too.
I tried same with array, &[(i64, i64, i64)].to_vec(), but it's working correctly.
I also found a relationship between length and index where nulls begins
* 25K elements: all is working, all elements are correctly shown.
* 50K elements: index where null values begin is 6310 for me.
* 75K elements: index where null values begin is 31310 for me.

![Image example](https://cdn.discordapp.com/attachments/443150878111694848/617612212277870593/unknown.png)

**Example of code:** https://gist.github.com/starfear/d3ba0c1d68a9b4922b1cc07482efe0ec.
**Operation System**: ArchLinux (X86_64)
**Toolchain**: stable-x86_64-unknown-linux-gnu

**Comment by jonas-schievink** [comment]
How do you determine that there are 0 values? The gist doesn't do that, and adding 3 `assert!`s in the loop doesn't seem to fire for me.

**Comment by dcchut** [comment]
I made two versions of the example: [i32](https://gist.github.com/dcchut/39b4f678e51c9f12170e9c53e806a74b) and [i64](https://gist.github.com/dcchut/b2c2853b504e4b824c07b3c03a158b51).  

**Stable (stable-x86_64-pc-windows-msvc, rustc 1.37.0 (eae3437df 2019-08-13))**
In debug mode, both examples error out with `thread 'main' has overflowed its stack`.  In release mode, the i32 version runs correctly, while the i64 version panics as below:
```
thread 'main' panicked at 'assertion failed: `(left != right)`
  left: `0`,
 right: `0`', src\main.rs:6:9
```
**Nightly (nightly-x86_64-pc-windows-msvc, rustc 1.39.0-nightly (fba38ac27 2019-08-31))**
Same error as stable for debug mode.  In release mode, both i32 and i64 work correctly.

**Comment by starfear** [comment]
> ~How do you determine that there are 0 values? The gist doesn't do that, and adding 3 `assert!`s in the loop doesn't seem to fire for me.~ Ah nevermind, the division just never seems to fail for me. Did you install Rust using rustup, or did you install from the Arch repos?

yes, Im sorry for gist, it only shows that I tried to divide something by zero(value), I installed rustc from rustup

**Comment by Mark-Simulacrum** [comment]
I cannot reproduce this on x86_64-unknown-linux-gnu and I hope/doubt that this is architecture specific. I'm going to close.

My reproduction consisted of downloading the gist https://gist.github.com/starfear/d3ba0c1d68a9b4922b1cc07482efe0ec and running `rustc -Copt-level=3 foo.rs` and then `./foo`. This completes successfully. If there are other steps that I should take, please let us know and we can reopen.
