### ISSUE TITLE
Add warnig for assignment to temporary

### ISSUE THREAD

**Issue by no111u3** [rust-lang/rust#64089]
For simple useless code:
```
fn main() {
    const N: (usize, usize) = (10, 20);
    N.0 = 0;
    println!("{:?}", N);
}
```
rust compiller no any warnings/errors.
But clippy have an one display item:
```
warning: assignment to temporary
 --> src/main.rs:3:5
  |
3 |     N.0 = 0;
  |     ^^^^^^^
  |
```
I think upper warning need to display in rust compiler too.

**Comment by Mark-Simulacrum** [comment]
Movement of lints from clippy into rustc generally speaking needs an RFC, so this'll need to go through that process.
