### ISSUE TITLE
Inconsistent analysis results for unsafe blocks and operators

### ISSUE THREAD

**Issue by rchaser53** [rust-lang/rust#64093]
related: https://github.com/rust-lang/rustfmt/issues/3770
rust playground link: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=ef4769175cb5b4febb445b05c1e27b82

The second !unsafe block return &&bool. I think the second block should return bool.

```rust
fn return_bool() -> bool {
    unsafe { false }            // expected (), found bool
        && !unsafe { true }     // expected bool found &&bool
        && !unsafe { false }    // expected bool found bool
}
```

**Comment by Mark-Simulacrum** [comment]
Simplifies to:

```rust
fn return_bool() -> bool {
    {
        false
    }
    && { false }     
        && { false } 
}
```

**Comment by nagisa** [comment]
This is an expected corner-case in parsing. See https://github.com/rust-lang/rust/issues/17930.

Closing.
