### ISSUE TITLE
Improve `rustc::hir::PatKind::Wild`

### ISSUE THREAD

**Issue by JohnTitor** [rust-lang/rust#64101]
The [`slice_patterns` feature](https://doc.rust-lang.org/nightly/unstable-book/language-features/slice-patterns.html) introduces the `..` wildcard. It seems classified as `rustc::hir::PatKind::Wild` along with `_`.
However, `Wild` currently has no information to distinguish between `_` and `..`. It'd be nice if we could easily distinguish `..` from `_`. And we may also mention `..` as well as `_` here.

https://github.com/rust-lang/rust/blob/bbd48e6f166739344528a5fff4f02516b77d7916/src/librustc/hir/mod.rs#L977-L979

**Comment by Centril** [comment]
What problem are you trying to solve here? In AST, `..` is represented as `ast::PatKind::Rest` but in certain specific cases in HIR where you get an error, it is lowered to `hir::PatKind::Wild` -- maybe we should just introduce `hir::PatKind::Err` instead for those.

**Comment by JohnTitor** [comment]
@Centril Oh, I didn't know that. I'm trying not to catch `..` here.

https://github.com/rust-lang/rust-clippy/blob/1f9993729b3af307e3508d604be008374d62d465/clippy_lints/src/misc.rs#L463-L477

Currently, it seems this `if let` catches not only `_` but also `..`.

**Comment by Centril** [comment]
Seems like a problem on Clippy's side. The lint should be moved to an analysis on AST, not HIR.

**Comment by JohnTitor** [comment]
Ah, so, it's my fault. I'll investigate again, Should we close this?

**Comment by Centril** [comment]
Yes, let's.
