### ISSUE TITLE
E0631 has duplicated diagnostics

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#64165]
https://github.com/rust-lang/rust/blob/master/src/test/ui/anonymous-higher-ranked-lifetime.stderr has duplicated redundant diagnostics. We should come up with a deduplicating strategy to avoid them.

**Comment by gilescope** [comment]
^ This. It really looks unprofessional when the errors are doubled up. And it's pretty unhelpful when your going through errors in the IDE and realise the error is pointing at a location you've already fixed.

Would rustc devs want a switch to see all the errors so they could check if some error was being raised far too many times? Or can we just keep things simple for now?

**Comment by gilescope** [comment]
I see all the code is in librustc_errors.

struct Diagnostic supports Hash, PartialEq...

**Comment by gilescope** [comment]
In librustc, session has a one_time_diagnostics for deduplicating helpful notes so that we don't repeat them (#24690 and #44953).

**Comment by gilescope** [comment]
Hang on, those diagnostics aren't pure duplicates. One is fn, the other is for.

**Comment by estebank** [comment]
They are caused by different `Obligation`s, because closures introduce two. But that is the internal state of how the compiler reasons about closures, not something that needs (or can) to be communicated succinctly to the user in a way that makes sense. We have multiple places where we just keep a set of `Span`s or some other identifier and deduplicate specific errors where the underlying cause is different but the outwards behavior is the same.

**Comment by hbina** [comment]
Hello, I would like to work on this, but I am not entirely sure what to do here? Should I manually remove the duplicate tests from this "text" file?

**Comment by estebank** [comment]
@hbina thank you for wanting to help. Sadly this was already fixed in https://github.com/rust-lang/rust/pull/64937 a couple of days back. Feel free to look at other tickets labeled `E-easy` and `E-mentor` for good first tickets to work on!
