### ISSUE TITLE
Cross-compilation of rust 1.37.0 fails with multiple crate matches

### ISSUE THREAD

**Issue by he32** [rust-lang/rust#64185]
Having dealt with issue #63828, another one crops up which is more directly
related to rust.  While building, I hit several instances of this particular error message:

```
   Compiling rustc-ap-arena v491.0.0
   Compiling rustc-ap-syntax_pos v491.0.0
   Compiling rustc-ap-rustc_errors v491.0.0
error[E0464]: multiple matching crates for `rustc_macros`
 --> /usr/pkgsrc/lang/rust/work/rustc-1.37.0-src/vendor/rustc-ap-rustc_errors/diagnostic.rs:9:5
  |
9 | use syntax_pos::{MultiSpan, Span};
  |     ^^^^^^^^^^
  |
  = note: candidates:
          crate `rustc_macros`: /usr/pkgsrc/lang/rust/work/rustc-1.37.0-src/build/x86_64-unknown-netbsd/stage1/lib/rustlib/x86_64-unknown-netbsd/lib/librustc_macros-ea0ff5a28254b1a0.so
          crate `rustc_macros`: /usr/pkgsrc/lang/rust/work/rustc-1.37.0-src/build/x86_64-unknown-netbsd/stage1-tools/release/deps/librustc_macros-a3f969e09b70c389.so
```

This error is only seen when trying to cross-compile rust itself; in this instance
I'm building on `NetBSD/amd64` with `NetBSD/aarch64` as target.  The same problem
is seen for the other non-native targets I usually cross-build for (`armv7`, `powerpc`,
`sparc64`).

Any ideas how to deal with this problem?

**Comment by mati865** [comment]
Basically duplicate of https://github.com/rust-lang/rust/issues/62558

Tools cannot be build when cross compiling.

**Comment by jonas-schievink** [comment]
Closing in favor of #62558
