### ISSUE TITLE
Make x86_64-linux-kernel target be tier-2

### ISSUE THREAD

**Issue by alex** [rust-lang/rust#64183]
This would mean compiling libcore in CI, and publishing those artifacts. This would add a lot of value to the efforts to get Rust support into the mainline kernel, since it will mean all the building can be done with just cargo, no 3rd party tools.

I'm happy to do whatever work is needed to wire this up, but I wasn't sure what code needs changing to make this happen! If someone can point me the right way, or just to a previous PR that moved something to tier-2, I'll run from there!

cc: @joshtriplett

**Comment by Centril** [comment]
Already? We landed the `-linux-kernel` target like 1 hour ago...

**Comment by alex** [comment]
If there's a preference for letting it sit for a while first, I'll of
course defer to that. It was built entirely on an out of tree target that'd
been stable for a while, so I expect it will be too  :-)

**Comment by joshtriplett** [comment]
We want to get there eventually, but I expect this will need to wait for a while. We should find out everything needed to make this tier 2, but I do think it'll need to wait until we have the solution a little more complete.

**Comment by alex** [comment]
Is there a good checkpoint I should consider for coming back to this?

**Comment by jonas-schievink** [comment]
cc https://github.com/rust-lang/rfcs/pull/2803

Closing since I don't think it's terribly useful to keep this issue open.
