### ISSUE TITLE
cdylib for the target `wasm32-wasi`

### ISSUE THREAD

**Issue by yurydelendik** [rust-lang/rust#64187]
**Problem**
cannot produce cdylib for the target `wasm32-wasi`

**Steps**

1. Add "cdylib" to the Cargo.toml, e.g.
    ```
    cargo new check-wasi && cd check-wasi
    echo "[lib]" >> Cargo.toml 
    echo "crate-type = [\"cdylib\"]" >> Cargo.toml
    ```
2. Build using
    ```
    cargo +nightly build --target=wasm32-wasi
    ```
3. Observe
    ```
    error: cannot produce cdylib for `check-wasi v0.1.0` as the target `wasm32-wasi` does not support these crate types
    ```

**Possible Solution(s)**
Allow cdylib for all wasm32-* targets: it's available for wasm32-unknown-unknown and is required by wasm-pack

**Comment by alexcrichton** [comment]
I've transferred this to the rust-lang/rust repository after debugging it and am working on a fix locally (the fix is here in the compiler, not in Cargo)
