### ISSUE TITLE
Maximum number of backtrace frames is not configurable

### ISSUE THREAD

**Issue by Aaron1011** [rust-lang/rust#64194]
The standard library currently has a [hard-coded limit of 100 frames](https://github.com/rust-lang/rust/blob/618768492f0c731fcb770dc2d178abe840846419/src/libstd/sys_common/backtrace.rs#L18) when printing a backtrace. However, some applications may have larger call stacks - without rebuilding libstd, it's impossible for them to obtain proper backtraces.

The standard library should provide an environment variable which overrides the default backtrace frame limit.

**Comment by cramertj** [comment]
Once https://github.com/rust-lang/rust/pull/64152 lands, `RUST_BACKTRACE=full` will bypass this limit.

**Comment by Aaron1011** [comment]
Fixed in https://github.com/rust-lang/rust/pull/64152
