### ISSUE TITLE
[Feature Request] compile time arguments

### ISSUE THREAD

**Issue by elichai** [rust-lang/rust#64212]
Currently the closest thing to C's preprocessor conditional compilations we have is the cfg and the features.

But there's one missing piece, and that's and that's values in those variables.

Currently the design idea of features is to be incremental which doesn't make sense with having values in those features.
The thing is that in practice a lot of crates don't really use features as incremental and have mutually exclusive features.

I understand that the incremental features idea is rooted pretty deep in cargo's dependency resolvement. 
Is there a way to have this without a big problem with having the same dependency twice in the dependency graph but with different values?
Could we maybe have some symbol randomness and just treat them as two different libraries?

**Comment by steveklabnik** [comment]
Feature requests like this go through our RFC process https://github.com/rust-lang/rfcs

I would encourage you to pursue this over there. Thanks!
