### ISSUE TITLE
LLVM doesn't build  on the first try when cross compilling to windows-gnu host

### ISSUE THREAD

**Issue by mati865** [rust-lang/rust#64218]
Running `./x.py build --host x86_64-pc-windows-gnu --target x86_64-pc-windows-gnu` from Linux will fail on building LLVM for Windows (so it's 2nd LLVM build) because somehow LLVM_ON_UNIX is defined:
```
/home/mateusz/Projects/rust/rust/src/llvm-project/llvm/include/llvm/Support/FileSystem.h:164:3: error: ‘uid_t’ does not name a type; did you mean ‘pid_t’?
  164 |   uid_t fs_st_uid = 0;
      |   ^~~~~
      |   pid_t
```

Magic happens when running the same command second time without cleaning build dir or changing anything. It will finish LLVM build and install the files.

Rust build will fail on `librustc_codegen_llvm` because of missing `shell32` but this could be unrelated (although [CMake should link it](https://github.com/llvm/llvm-project/blob/6d6babf7457c8128072cb23f079123fa76cafc5b/llvm/lib/Support/CMakeLists.txt#L8)).

**Comment by chumd** [comment]
Someone manipulated s scricpt
