### ISSUE TITLE
Tracking issue: slice_internals?

### ISSUE THREAD

**Issue by yoshuawuyts** [rust-lang/rust#64217]
I was looking at the unstable [`core::slice::memchr`](https://doc.rust-lang.org/core/slice/memchr/fn.memchr.html) API, and couldn't figure out the corresponding tracking issue (it's still set to `#0`). Is there meant to be one? How can I read up on its stabilization status?

Thanks heaps!

**Comment by Centril** [comment]
Issue 0 means it is internal and permanently unstable.
