### ISSUE TITLE
fmt::Debug for right-to-left strings

### ISSUE THREAD

**Issue by s3bk** [rust-lang/rust#64228]
When formatting strings using fmt::Debug, the normal right-to-left characters are printed as is. This will mangle the entire display line in a rather unpredicable way.

[Playground demo](https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=03b109a38ef2ecdd7b318ffd722d3cef)

```
    let arr = [
      "א",
      "ב",
      "ג",
      "a",
      "b",
      "c",
    ];
```
is rendered right now as: `["א", "ב", "ג", "a", "b", "c"]`
where it should be rendered as `[⁨"א"⁩, ⁨"ב"⁩, ⁨"ג"⁩, ⁨"a"⁩, ⁨"b"⁩, ⁨"c"⁩]`

**Comment by s3bk** [comment]
My proposes solution is to insert

> `U+2068` FIRST STRONG ISOLATE (Treat the following text as isolated and in the direction of its first strong directional character that is not inside a nested isolate.)

before the opening quotes and

>  `U+2069` POP DIRECTIONAL ISOLATE (End the scope of the last LRI, RLI, or FSI.)

after the closing quote.

**Comment by Manishearth** [comment]
This will only happen on the playground, terminals don't handle this at all.

I don't think we should be adding bidi directives to the debug output.

Perhaps the playground should have a strong directionality on its output field.
