### ISSUE TITLE
Migrate to LLVM{Get,Set}ValueName2

### ISSUE THREAD

**Issue by rkruppe** [rust-lang/rust#64223]
We currently use the C APIs `LLVM{Get,Set}ValueName` which return/take a 0-terminated `char *`, but those APIs have been deprecated a while ago in favor of `LLVM{Get,Set}ValueName2` which return/take pairs of `char *` + length (the C-friendly lowering of `llvm::StringRef`) which need not be 0-terminated. We should migrate to those APIs. Besides avoiding silly error cases for names that contain a 0 byte, it would also make conversions from `&str` to LLVM name free, and reduce the cost of the opposite direction to an UTF-8 validity check (plus, I suspect many or all code paths that do that could just as well use `&[u8]`, and that conversion actually is 100% free).

**Comment by eddyb** [comment]
Any idea how old the new APIs are? I don't see any reason not to switch other than that.

**Comment by rkruppe** [comment]
They were added in https://github.com/llvm/llvm-project/commit/025c78f5d7174e4ab7725fcfc7caec03c611d59e which is in the 7.0 release, what's our minimum supported LLVM version these days?

**Comment by rkruppe** [comment]
The current minimum is 6, but considering the constraints raised when it was bumped from 5 to 6 (https://github.com/rust-lang/rust/pull/56642) it seems to me that bumping to 7 might be OK already. Worth a try IMO.

**Comment by nikic** [comment]
@rkruppe We'll have to wait for #63649 to land first, as emscripten is still on LLVM 6.

**Comment by rkruppe** [comment]
I just realized, if we cared enough we could also provide our own equivalent of these functions in src/rustllvm (and just remove them when we drop LLVM 6 support). The C API was just lagging behind, the C++ APIs have supported it for much longer.

**Comment by cuviper** [comment]
FYI, #66973 bumps to LLVM 7.
