### ISSUE TITLE
Factor out pluralisation checks in diagnostics

### ISSUE THREAD

**Issue by varkor** [rust-lang/rust#64238]
The following pattern is common in diagnostic messages in rustc:

```rust
format!("found {} thing{}", x, if x != 1 { "s" } else { "" })
```

It would be good to extract all of these pluralisation checks into a function or macro:

```rust
format!("found {} thing{}", x, pluralise(x))
```

There's already one in src/librustc/ty/error.rs, but it's not used anywhere else, so we could move it to somewhere in src/librustc_errors, and replace the occurrences of this pattern with the macro.

https://github.com/rust-lang/rust/blob/0b97726e6c524d2cc0de4c2f5b1284eca010a7b2/src/librustc/ty/error.rs#L85-L89

This issue has been assigned to @V1shvesh via [this comment](https://github.com/rust-lang/rust/issues/64238#issuecomment-529086433).

**Comment by V1shvesh** [comment]
I'd love to be assigned to this issue!

**Comment by V1shvesh** [comment]
So, I have moved the macro under `src/librustc_errors` in a file called `pluralise.rs`. I have also located all the occurrences of the pattern.

I am a bit new to Rust, so I still am learning about the module system. How shall I pull the macro into the scope of all the relevant files?

**Comment by varkor** [comment]
@V1shvesh: I'd put it in `src/librustc_errors/lib.rs`, so we don't have one new file for a single macro. Then you can use it from `use syntax::errors;`.

**Comment by V1shvesh** [comment]
Thanks for pointing me in the right direction @varkor!

**Comment by varkor** [comment]
@V1shvesh: searching for `{ "s" } else { "" }` in rustc, I can see a few cases that weren't caught by https://github.com/rust-lang/rust/pull/64280, e.g. in `resolve_lifetime.rs`, `diagnostics.rs`, etc. Let's keep this issue open until they've all been replaced with the new macro.

**Comment by glorv** [comment]
I have open a [pr](https://github.com/rust-lang/rust/pull/64342) to refactor the pluralisations remain, @Centril please have a look at it, thanks.

**Comment by V1shvesh** [comment]
@varkor Oh, my bad. @glorv thanks for helping out!
