### ISSUE TITLE
Unnecessary mov instruction

### ISSUE THREAD

**Issue by tspiteri** [rust-lang/rust#64234]
For the following code
```rust
extern "C" {
    fn moo(a: i64);
}
pub unsafe fn baa(a: i64) {
    if a != 0 {
        moo(a);
    }
    moo(a);
}
```
I get the following assembly
```asm
example::baa:
  push rbx
  mov rbx, rdi
  test rdi, rdi
  je .LBB0_2
  mov rdi, rbx ;unnecessary
  call qword ptr [rip + moo@GOTPCREL]
.LBB0_2:
  mov rdi, rbx
  pop rbx
  jmp qword ptr [rip + moo@GOTPCREL]
```
The marked `mov` instruction is not necessary, as `rdi` is already equal to `rbx`.

I also think that the `LBB0_2` label can move down one line to just before the `pop` instrucion, as if the branch is taken then `rdi` is still equal to `rbx` as well.

**Comment by scottmcm** [comment]
Can you try repro'ing this in clang?  If it happens there too, then it's an LLVM issue, not a Rust issue.

**Comment by tspiteri** [comment]
I reproduced in clang, so it is indeed an LLVM issue, so I'll submit a bug report there instead.
