### ISSUE TITLE
Builder got stuck on "Updating crates.io index"

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#64248]
In https://github.com/rust-lang/rust/pull/64246#issuecomment-529094551, the test-various builder got stuck (https://dev.azure.com/rust-lang/rust/_build/results?buildId=7573):
```
2019-09-07T06:17:08.8395892Z extracting /checkout/obj/build/cache/2019-08-13/cargo-beta-x86_64-unknown-linux-gnu.tar.gz
2019-09-07T06:17:10.0973441Z     Updating crates.io index
2019-09-07T10:24:09.3054360Z ##[error]The operation was canceled.
2019-09-07T10:24:09.3072651Z ##[section]Finishing: Run build
```

cc @pietroalbini

**Comment by teknoalex** [comment]
i have the same issue

**Comment by pipehappy1** [comment]
I have the same issue on some network. Is this related to some network problem?

**Comment by pietroalbini** [comment]
The crates.io index is downloaded from GitHub, so I would contact GitHub support to ask about it.

**Comment by Canoir** [comment]
I have the same issue, any resolve?

**Comment by mk30** [comment]
based on https://github.com/rust-lang/cargo/issues/7662#issuecomment-561917271, i cleared the contents of `~/.cargo/registry/*`. the crates.io index updated successfully after that.

(cc @Canoir )

**Comment by JohnTitor** [comment]
Triage: I presume this aims to track our CI issues and it doesn't happen on recent our CI builds. The cargo issue itself should go to the cargo repo (like rust-lang/cargo#7662). Therefore I'm going to close.

**Comment by blueglyph** [comment]
Same problem here.

**Comment by JohnTitor** [comment]
@blueglyph Note that this issue is about our CI builder.

**Comment by ArikRahman** [comment]
I had this issue too, I simply changed directory from the terminal into the registry file@mk30 specified and CLion resumed the build.

**Comment by Rtoax** [comment]
```
+ cd ceaos-coreos-pinger-0.0.4
+ /usr/bin/env CARGO_HOME=.cargo /usr/bin/cargo build --release -j32
    Updating crates.io index
```

Could i just skip the `cargo build` procudure?

**Comment by felipelalli** [comment]
Same issue here. Maybe proxy issue?

**Comment by 0xpr03** [comment]
Same here with 3GB and ~400000 entries in the .cargo/registry on windows (using a SSD).

**Comment by ddjerqq** [comment]
make sure to run your IDE as admin or sudo. it fixed for me. also clean the registry cache as per [this comment](https://github.com/rust-lang/rust/issues/64248#issuecomment-839392042)

**Comment by EarthCitizen** [comment]
The solution by @mk30 worked for me. It was hanging at a certain percentage, but after I did what @mk30 suggested above, it instantly started working. Could there be some kind of corruption issue with the index?

**Comment by jalbiero** [comment]
I am experiencing the same issue when building a very simple project (its only dependency is Rocket) inside a docker (it is a fresh environment, the cargo registry is empty)

**Comment by mohit310** [comment]
having same issue on linux

**Comment by nuclyk** [comment]
the same issue on Mac

**Comment by deltakid0** [comment]
Same issue, Debian Stretch 32-bit, I'm trying to add num-bigint crate manually but still the same problem, no solution so far?
