### ISSUE TITLE
Support running with new pass manager

### ISSUE THREAD

**Issue by nikic** [rust-lang/rust#64289]
Rustc currently still uses the legacy LLVM pass manager. There's been some discussion about enabling NewPM by default for Clang 10, so we might want to start migrating in that direction as well.

To start with, we'd probably want a debug option `-Z llvm-pass-manager=new` that is not enabled by default, but can be used to perform initial evaluation.

For reference, this is how newpm use looks like in clang: https://github.com/llvm/llvm-project/blob/90d2be0163e8f84dfc0b73128d873ac8d84c10f8/clang/lib/CodeGen/BackendUtil.cpp#L985

**Comment by cuviper** [comment]
I'm going to take a shot at this.

**Comment by nikic** [comment]
Also looking into this now. Seems less hard than I originally expected, though some things can't be supported (e.g. MergeFunctions doesn't seem to support NewPM yet?)

**Comment by nikic** [comment]
I've created a prototype for newpm at #67954.
