### ISSUE TITLE
Too many `memcpy`s

### ISSUE THREAD

**Issue by nnethercote** [rust-lang/rust#64301]
Cachegrind profiles indicate that the Rust compiler often spends 3-6% of its executed instructions within `memcpy` (specifically `__memcpy_avx_unaligned_erms` on my Linux box), which is pretty incredible.

I have modified DHAT to track `memcpy`/`memmove` calls and have discovered that a lot are caused by obligation types, such as `PendingPredicateObligations` and `PendingObligations`, which are quite large (160 bytes and 136 bytes respectively on my Linux64 machine).

For example, for the `keccak` benchmark, 33% of the copied bytes occur in the `swap` call in the `compress` function:
https://github.com/rust-lang/rust/blob/a6624ed9806fe4caa10de5b94e590f71a4a1eab9/src/librustc_data_structures/obligation_forest/mod.rs#L607-L620

For `serde`, 11% of the copied bytes occur constructing this vector of obligations:
https://github.com/rust-lang/rust/blob/a6624ed9806fe4caa10de5b94e590f71a4a1eab9/src/librustc/ty/wf.rs#L150-L157
and 5% occur appending to this vector of obligations:
https://github.com/rust-lang/rust/blob/ac21131f7859836cd3fcb39231c0162fd892d960/src/librustc/traits/project.rs#L570-L574

It also looks like some functions such as `FulfillmentContext::register_predicate_obligation()` might be passed a `PredicateObligation` by value (using a `memcpy`) rather than by reference, though I'm not sure about that.

I have some ideas to shrink these types a little, and improve how they're used, but these changes will be tinkering around the edges. It's possible that more fundamental changes to how the obligation system works could elicit bigger wins.

**Comment by nnethercote** [comment]
#64302 shrinks the size of some of these types by 24 bytes. For a clean check build of `serde`, it almost halves the number of instructions executed in `memcpy`. AFAICT, the effect is so big because some of the types (e.g. `PredicateObligation`) shrink enough that the compiler generates code to copy them instead of calling `memcpy`.

**Comment by nnethercote** [comment]
I'm going to modify this issue to be about all types that cause many calls to `memcpy`. These types are all > 128 bytes in size.

`DiagnosticBuilder` is another one (and consequently `PResult`). #64374 deals with that.

**Comment by nnethercote** [comment]
`SubregionOrigin` is another one, #64394 improves it.

**Comment by jamesmunns** [comment]
@nnethercote does your profiling show "returning structs by value" to be a significant amount of time spent in memcpy? Since Rust doesn't have guaranteed NRVO (see https://github.com/rust-lang/rust/issues/32966 for details), I've been trying to get a feel for what kind of performance impact implementing this in MIR would cause.

This could perhaps be the cause of your mystery memcpy in https://github.com/rust-lang/rust/issues/64301#issuecomment-531033077, as `smallvec!` could be returning the struct by value (if it's too large at 500ish bytes, LLVM's RVO pass may not catch it reliably), but I have no data to back that up.

**Comment by nnethercote** [comment]
> @nnethercote does your profiling show "returning structs by value" to be a significant amount of time spent in memcpy?

#64374 was one such case. In general, it doesn't seem like a big fraction of the `memcpy` calls, though. I wonder about return values that are less than 128 bytes, though.

**Comment by lnicola** [comment]
Referencing https://github.com/kvark/copyless here, since it can be used to avoid some extra copies.

**Comment by SimonSapin** [comment]
A single 544-bytes `memcpy` sounds to me like the SmallVec is being moved after it was initialized, and yes missing RVO sounds most likely.

This is not the first I hear of accidentally moving a large buffer with SmallVec, I feel this is a design flaw of this library. I’ve been pondering an alternative design (perhaps for a separate crate) where the inline buffer is borrowed:

```rust
let mut buffer = std::mem::Uninitialized::<Foo, N>::uninit();
let queue = SmallSmallVec::new(&mut buffer);
```

This gives a `size_of` similar to that of `Cow<[T]>`, so moving that value around is less of a problem. The downside is that the lifetime parameter makes this much less flexible to use: it’s mostly for cases where a `SmallVec` would stay on the stack.

**Comment by nnethercote** [comment]
#67250 is another tiny win from `memcpy` profiling.

**Comment by nnethercote** [comment]
#67340 is another small win from `memcpy` profiling.

**Comment by nnethercote** [comment]
At this point I have eliminated most of the worst cases and even those have produced only small wins. I will keep an eye out for additional cases in the future, but I don't think we don't need an issue open for it any more.
