### ISSUE TITLE
Error with -Z time-passes

### ISSUE THREAD

**Issue by Ploppz** [rust-lang/rust#64339]
```
$ rustc --version
rustc 1.39.0-nightly (0b36e9dea 2019-09-09)
$ export RUSTFLAGS="-Z time-passes"
$ cargo build

error: failed to parse the cfg from `rustc --print=cfg`, got:
___
lib___.rlib
lib___.so
lib___.so
lib___.a
lib___.so
/home/erlend/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu
debug_assertions
proc_macro
target_arch="x86_64"
target_endian="little"
target_env="gnu"
target_family="unix"
target_feature="fxsr"
target_feature="mmx"
target_feature="sse"
target_feature="sse2"
target_has_atomic="16"
target_has_atomic="32"
target_has_atomic="64"
target_has_atomic="8"
target_has_atomic="cas"
target_has_atomic="ptr"
target_os="linux"
target_pointer_width="64"
target_thread_local
target_vendor="unknown"
unix
time: 0.020; rss: 53MB		total


Caused by:
  malformed cfg value or key/value pair: `time: 0.020; rss: 53MB		total`

```

**Comment by matthiaskrgr** [comment]
I encountered this as well.

What project are you trying to build?

My theory is that it tries to run something like `rustc --print=cfg -Z time=passes` (in `build.rs`?) and then fails to parse the output which is a mix of `--print=cfg` and `-Ztime=passes`...

**Comment by bjorn3** [comment]
> My theory is that it tries to run something like rustc --print=cfg -Z time=passes (in build.rs?)

Way earlier, it runs it right at the start of a compilation to get the rustc version and enabled `#[cfg(...)]`.

> and then fails to parse the output which is a mix of --print=cfg and -Ztime=passes...

Probably

**Comment by Mark-Simulacrum** [comment]
Could someone use https://github.com/rust-lang-nursery/cargo-bisect-rustc to narrow this down to a particular commit?

**Comment by ehuss** [comment]
It looks to be caused by #62419 (I would assume it is #62110 in that rollup).  It is now printing the time-passes information even for `--print`.

**Comment by Mark-Simulacrum** [comment]
@nnethercote would you be up for a fix here?

**Comment by nnethercote** [comment]
I'll take a look on Monday. In the meantime, here's my best guess: I added an extra entry to the `-Ztime-passes` output that prints the total time for the compilation. That extra line may not be indented at all, and it's possible this means it isn't ignored the same way as indented lines.

**Comment by nnethercote** [comment]
My theory about indentation was wrong. It was indeed a bad interaction between `-Ztime-passes` and `--print=...`, because they both print to `stdout`. #64497 has a fix.
