### ISSUE TITLE
toolstate: allow toolstate x->build_fail in rollup PRs

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#64341]
I was trying to implement this myself but was not sure about implementation details, so making a ticket...

Currently, a PR that modifies a tool and does not change it to "test pass" will fail.
If we allowed "test pass"  -> "build fail", "build fail" -> "test fail", and "build fail -> build fail" we would allow tool fix PRs to be rolled up more aggressively.

Currently, tools-change prs are rarely rolled up because if it does not fix the toolstate, or another change in the rollup breaks the tool again, the entire PR will fail and cannot merge.

Thus the idea to allow "tool modified && X -> build fail" toolstate changes ONLY in rollup prs came up.

However I think we need to add some kind of exception for "no tool breakages week" where "x -> test fail" is denied.

cc @Centril

**Comment by Mark-Simulacrum** [comment]
Hm, so I think historically the mindset here has been that there's no point in landing a PR that updates tools if we don't actually fix the tools in said PR. Can you clarify why that's a bad policy to have? I myself don't see much point in bumping a submodule if it doesn't actually net us anything.

**Comment by Centril** [comment]
> Can you clarify why that's a bad policy to have? I myself don't see much point in bumping a submodule if it doesn't actually net us anything.

Suppose you are making a rollup with 10 PRs, 2 of them are for rustfmt/rls/miri-up and clippy-up.
Clippy-ups fail frequently but the others don't. With the current scheme, if Clippy's toolstate is not improved, the whole rollup will also fail wasting many hours where 9 PRs could have landed. Moreover, suppose that both Miri and Clippy fail. In that case, we could have still landed the 8 PRs.

The worst case that happens is that e.g. Clippy doesn't improve, but it at least allows us to land other PRs.

The alternative to this proposal, i.e. the status quo means that I will simply not rollup toolstate PRs in general as they risk failing the rollup.

**Comment by Mark-Simulacrum** [comment]
Interesting. So I guess the perspective is that it's fine if we don't actually improve things since ultimately we'll just land another PR. I think this should then be reasonable to implement.

**Comment by Mark-Simulacrum** [comment]
Toolstate isn't really a thing anymore as far as I know, so closing. (Or at least isn't commonly breaking people).

**Comment by ehuss** [comment]
Toolstate is still being used for docs. Fortunately there has not been any breakage in a long while (last time was July 2022), so yea this isn't really necessary anymore.
