### ISSUE TITLE
question: when there will a Cranelift backend will available

### ISSUE THREAD

**Issue by lithic** [rust-lang/rust#64346]

**Comment by MSleepyPanda** [comment]
Development of a cranelift backend happens at [bjorn3/rustc_codegen_cranelift](https://github.com/bjorn3/rustc_codegen_cranelift). It now passes [large portions](https://github.com/bjorn3/rustc_codegen_cranelift/issues/381#issuecomment-526846544) of the standard library tests.

**Comment by jonas-schievink** [comment]
Closing since this has an answer.

(questions like this are better asked in the user forum at https://users.rust-lang.org/ or on [one of the chat platforms](https://www.rust-lang.org/community) used by the Rust community)
