### ISSUE TITLE
Rename `Kind`

### ISSUE THREAD

**Issue by varkor** [rust-lang/rust#64352]
A `Kind` is not really a kind: it's a term (e.g. a particular type, a particular lifetime or a particular value). However, "`Term`" is overloaded as terms are usually values of particular types (which is just one case here). `KindedTerm` has been suggested.

**Comment by oli-obk** [comment]
For me, this doesn't clarify anthing. It just means I'm gonna learn another name that means nothing.

I liked the `GenericArg` suggestion, since it matches the AST/HIR naming for the equivalent values.

**Comment by varkor** [comment]
> I liked the `GenericArg` suggestion, since it matches the AST/HIR naming for the equivalent values.

How about `GenericVal`, which doesn't imply it's just used for arguments?
