### ISSUE TITLE
Rename `.sty` field on `TyS`

### ISSUE THREAD

**Issue by varkor** [rust-lang/rust#64353]
`.kind` makes more sense, but could be confusing, as it's not a [type-theoretic kind](https://en.wikipedia.org/wiki/Kind_(type_theory)). There's also the issue of having inconsistent ways to name a field containing a `*Kind`, e.g. `.node` and `.kind`. It would be good to make these consistent.

**Comment by Centril** [comment]
I don't like `ty.kind` -- that's a bit of high-degree confusion in the heart of the type system.

I'd like to suggest a third alternative `.form` and `ExprForm` to use consistently everywhere.

**Comment by varkor** [comment]
@eddyb suggested `.which`.

**Comment by Centril** [comment]
I would like to have `.thing` and `ExprThing` be consistent. Idk if `ExprWhich` works so well here.

Another alternative: `.shape: ExprShape`.

**Comment by petrochenkov** [comment]
I'm for `FooKind` / `foo.kind`, which is an existing and widely used convention.
`TyKind` / `ty.kind` is also ok.
The confusion with type-theoretic kinds applies only to a couple of selected cases, and even in case of `ty.kind` it's clear what kind it is, not worth changing conventions everywhere.

`.node` is a legacy convention, I always thought is didn't make much sense, personally, I'd gladly replace it with `.kind` in AST/HIR structures.

**Comment by oli-obk** [comment]
Alternative suggestion:

get rid of the fields on [`TyS`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc/ty/struct.TyS.html) and make the typeflags a query as well as the `outer_exclusive_binder: DebruijnIndex` something that is "computed" on the fly (most types are just `innermost`, but the few that aren't can have this info in their variant)
