### ISSUE TITLE
Rustdoc generates illegal "<div>" inside "<pre>" with traits

### ISSUE THREAD

**Issue by kentfredric** [rust-lang/rust#64371]
Similar to the previous bugs I've filed in this regard with illegal html:

In:  1.39.0-nightly (34e82a7b7 2019-09-10)

The following trait definition: 
```rust


#[cfg_attr(
    feature = "external_doc",
    doc(include = "CacheFieldCollection.md")
)]
#[cfg_attr(
    not(feature = "external_doc"),
    doc = "An abstact representation of 'a thing' that can expose data \
           about its unit."
)]
pub trait CacheFieldCollection {
    /// Returns a struct containing data recorded for this thing
    fn fields(&self) -> &CacheFieldData;
    /// Returns a timestamp indicating time of last modification/update
    fn mtime(&self) -> &chrono::DateTime<Utc>;
}
```
Emits invalid html ( hand formatted ):
```html
<div class="docblock type-decl hidden-by-usual-hider">
<pre class='rust trait'>pub trait CacheFieldCollection {
    fn <a href='#tymethod.fields' class='fnname'>fields</a>(&amp;self) -&gt; &amp;<a class="struct" href="../ccache_stats_reader/struct.CacheFieldData.html" title="struct ccache_stats_reader::CacheFieldData">CacheFieldData</a>;
<div class='item-spacer'></div>    fn <a href='#tymethod.mtime' class='fnname'>mtime</a>(&amp;self) -&gt; &amp;<a class="struct" href="https://docs.rs/chrono/latest/chrono/datetime/struct.DateTime.html" title="struct chrono::datetime::DateTime">DateTime</a>&lt;<a class="struct" href="https://docs.rs/chrono/latest/chrono/offset/utc/struct.Utc.html" title="struct chrono::offset::utc::Utc">Utc</a>&gt;;
}</pre></div>
```

"pre", like headers, only permits child nodes that are "phrasing content", of which, div is excluded.

So the error is from `<div class='item-spacer'></div>`

`htmltidy` handles this by prematurely ending the `<pre>` before the `<div>`, and then reinserting a `<pre>` afterwards, breaking layout:

![snapshot_20190911_160411](https://user-images.githubusercontent.com/44790/64667407-dcc77280-d4ad-11e9-8237-42cbf2f97321.png)

**Comment by hirschenberger** [comment]
So, I assume a `<span class="item-spacer"></span>` would be legal as it is [phrasing content](https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-span-element).

I can change that?

**Comment by nox** [comment]
Why is there even an element to do *spacing*, of all things?

**Comment by hirschenberger** [comment]
I think it makes sense as the non spacing list looks more confusing.
 
![Screenshot_2019-09-15 modbus Client - Rust](https://user-images.githubusercontent.com/1053180/64917876-56a17980-d796-11e9-99c2-3dd497cd6507.png)
![Screenshot_2019-09-15 modbus Client - Rust(2)](https://user-images.githubusercontent.com/1053180/64917892-89e40880-d796-11e9-9b03-2af567e90b70.png)

**Comment by nox** [comment]
That’s not the issue here. The issue is that empty DOM elements aren’t how you are supposed to do spacing. That’s a CSS concern. If you have 1000 methods to space, that’s 999 spacing elements, those things add up and then the page is really hard on browsers.

**Comment by kentfredric** [comment]
Its also rather redundant in the context of a `<pre>` where all you need to add a line feed is ...:
```rust
 print!("\n")
```

Or equivalent.

I mean, you're already doing horizontal alignment with literal whitespace.

**Comment by hirschenberger** [comment]
> Its also rather redundant in the context of a `<pre>` where all you need to add a line feed is ...:
> 
> ```rust
>  print!("\n")
> ```
> 
> Or equivalent.
> 
> I mean, you're already doing horizontal alignment with literal whitespace.

Yes, adding an extra '\n' instead if the spacer-div adds a slightly bigger vertical space, but looks ok.

**Comment by nox** [comment]
If you really want markup, then IMO each trait item should be in its own `li` tag. A trait contents are a list of trait items, after all.
