### ISSUE TITLE
Additional methods for TcpStream to provide more sockopts

### ISSUE THREAD

**Issue by Darneas** [rust-lang/rust#64379]
Dear all,

I'm writing a small TCP-based time-measuring tool and use the `std::net::TcpStream`. It turned out that I want to manipulate additional options via `setsockopt()`, but this is not available in the 
stable API of https://github.com/rust-lang/rust/blob/master/src/libstd/net/tcp.rs.

However, in https://github.com/rust-lang/rust/tree/master/src/libstd/sys_common, the raw `setsockopt()` method is exposed and it would be straightforward to add support for more options.

Now my question is what's the best and most straightforward way to add it---both locally for me and also for the community. I have checked the `CONTRIBUTING.md` guide, but as I want to fiddle around with libstd, I am not sure if I should do an RFC or a PR (and what's the best practise of local libstd modification).

I would be happy to contribute additional TCP-interfacing code to the community, but I would probably need some more guidance from experienced Rustaceans.

Thanks in advance!

**Comment by the8472** [comment]
Have you looked into the [net2](https://crates.io/crates/net2) crate? It supports many additional socket options?

**Comment by Darneas** [comment]
Thanks, it looks like what I was searching for. Sad, that it did not yet make it into `stdlib`. I will check in the next weeks if `net2` fufills our needs and reopen the issue if necessary.
