### ISSUE TITLE
debuginfo: Line-tables-only mode emits much more debuginfo than Clang

### ISSUE THREAD

**Issue by michaelwoerister** [rust-lang/rust#64405]
We probably could emit less debuginfo when compiling with `-Cdebuginfo=1` than we do at the moment. Clang 8.0 emits a lot less debuginfo when compiling with `-gline-tables-only`, with debuginfo not containing any `DW_TAG_subprogram` entries; while stepping through the code with gdb still works.

However, reducing the amount of debuginfo emitted should be done with care since external tools rely on the current behavior (see e.g. #60020).

**Comment by nagisa** [comment]
How can we possibly reduce the amount of debug info in `-Cdebuginfo=1` if external tools rely on it producing more without it being a breaking change?

**Comment by nagisa** [comment]
The only route I see is adding more flags (`-Cdebuginfo=0.5`?).

**Comment by jyn514** [comment]
> How can we possibly reduce the amount of debug info in `-Cdebuginfo=1` if external tools rely on it producing more without it being a breaking change?

Changing the exact behavior of a codegen flag seems like a very liberal definition of "breaking" ... what if we added a new `-C debuginfo=mixed` flag that does what `debuginfo=1` does today? and then reduced the amount we emit for =1? Firefox would have to change the flags they compile with, but that seems okay.
