### ISSUE TITLE
Unification fails when type alias impl trait is used in non-return position

### ISSUE THREAD

**Issue by jonhoo** [rust-lang/rust#64445]
The following code fails to compile, but I believe this should be a supported use-case under https://github.com/rust-lang/rfcs/pull/2515 (and https://github.com/rust-lang/rust/issues/63063):
```rust
#![feature(type_alias_impl_trait)]
type X = impl Iterator<Item = u64> + Unpin;

struct Foo(X);
impl Foo {
    fn new(z: Vec<u64>) -> Self {
        Foo(z.into_iter())
    }
}
```
with
```
error[E0308]: mismatched types
  --> src/lib.rs:12:13
   |
12 |         Foo(z.into_iter())
   |             ^^^^^^^^^^^^^ expected opaque type, found struct `std::vec::IntoIter`
   |
   = note: expected type `X`
              found type `std::vec::IntoIter<u64>`
```
This code on the other hand works just fine with the above `X`:
```rust
fn foo(z: Vec<u64>) -> X {
    z.into_iter()
}
```
Including both `Foo` and `foo` in the same file still produces the same error, so `foo` does not "help" identify `X`.

**Comment by Centril** [comment]
I'm going to say this is a bug... @cramertj confirm?

**Comment by varkor** [comment]
I think the "defining uses" for TAIT are far too restrictive at the moment. I know that @alexreg was intending to look into similar issues.

**Comment by jonhoo** [comment]
This is also becoming increasingly common for people writing their own `impl Future` blocks as library authors move to `async fn` and `-> impl Future` functions (e.g., [`tokio::TcpStream::connect`](https://docs.rs/tokio/0.2.0-alpha.4/tokio/net/tcp/struct.TcpStream.html#method.connect)), since it is now impossible to name the return type so that it can be embedded in other (custom) futures. You can hack around it with `Box` or by adding generic paramters, but neither of those solutions are particularly attractive.

**Comment by cramertj** [comment]
> I'm going to say this is a bug... @cramertj confirm?

Yes, the current set of defining uses is significantly reduced from what is allowed by the RFC.

**Comment by alexreg** [comment]
@varkor @cramertj I think we need a new summary-post (issue?) detailing the defining uses. I will expand it to consts/statics for sure, but within fn bodies is more subject to debate (and trickier to implement).

**Comment by cramertj** [comment]
[RFC 2071](https://github.com/rust-lang/rfcs/blob/master/text/2071-impl-trait-existential-types.md#reference-existential-types) specified that any unification site inside the module could count as a defining use.

**Comment by varkor** [comment]
As long as each use uniquely defines the underlying type, it should be permitted as a defining use. That's as I understand the intention, and the one that makes the most sense (one that albeit might be trickier to implement in some cases).

**Comment by alexreg** [comment]
@varkor Yeah, it certainly will... I think I'm going to need some advice on how to implement it inside of bodies, in this case!

**Comment by varkor** [comment]
We can start with the easier cases, and then slowly address the remaining cases. Let's get consts and statics working first.

**Comment by clarfon** [comment]
I think that the error I'm dealing with is also this. Example:

```
#![feature(type_alias_impl_trait)]
use core::iter::Map;

trait Thing {
    type Iter: Iterator<Item = u32>;
    fn do_thing(val: u32) -> u32;
}

type DoThing<T: Thing> = impl FnOnce(u32) -> u32;

struct ThingIter<T: Thing> {
    inner: Map<T::Iter, DoThing<T>>,
}
```

[Playground link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&code=%23!%5Bfeature(type_alias_impl_trait)%5D%0Ause%20core%3A%3Aiter%3A%3AMap%3B%0A%0Atrait%20Thing%20%7B%0A%20%20%20%20type%20Iter%3A%20Iterator%3CItem%20%3D%20u32%3E%3B%0A%20%20%20%20fn%20do_thing(val%3A%20u32)%20-%3E%20u32%3B%0A%7D%0A%0Atype%20DoThing%3CT%3A%20Thing%3E%20%3D%20impl%20FnOnce(u32)%20-%3E%20u32%3B%0A%0Astruct%20ThingIter%3CT%3A%20Thing%3E%20%7B%0A%20%20%20%20inner%3A%20Map%3CT%3A%3AIter%2C%20DoThing%3CT%3E%3E%2C%0A%7D%0A%0Afn%20main()%20%7B%0A%7D)

**Comment by nikomatsakis** [comment]
This should not be permitted under `min_type_alias_impl_trait` but is; filed #86732.

**Comment by oli-obk** [comment]
This is supported since https://github.com/rust-lang/rust/pull/94081 and we have tests for it
