### ISSUE TITLE
Tracking issue for `cmp::{min_by, min_by_key, max_by, max_by_key}`

### ISSUE THREAD

**Issue by timvermeulen** [rust-lang/rust#64460]
Tracking issue for the `cmp_min_max_by` feature, which adds the `min_by` / `min_by_key` / `max_by` / `max_by_key` functions to `std::cmp`.

PR: #64047

**Comment by Coder-256** [comment]
Is there anything blocking this from stabilizing?

**Comment by KodrAus** [comment]
Doesn't look like it! If somebody would like to open a stabilization PR then we can start a FCP 🙂

**Comment by glittershark** [comment]
Stabilization PR up at #81047
