### ISSUE TITLE
The "unused manifest key" warning doesn't print or halt the publishing with `cargo publish`

### ISSUE THREAD

**Issue by Lokathor** [rust-lang/rust#64476]
Normally if you have a manifest key that cargo doesn't understand many of the commands will print a warning

```
D:\dev\cargo-gba>cargo build
warning: unused manifest key: package.repsitory
```

However, if you use `cargo publish` not only does the accidental key not halt the publishing process without an override flag (as one might expect, similar to how you can't publish with a dirty git state without a flag), but it doesn't even directly print the warning about a bad key. Instead I got the warning about "no documentation, homepage or repository."

```
D:\dev\cargo-gba>cargo publish
    Updating crates.io index
warning: manifest has no documentation, homepage or repository.
See https://doc.rust-lang.org/cargo/reference/manifest.html#package-metadata for more info.
```

**Comment by jonas-schievink** [comment]
Please file this at https://github.com/rust-lang/cargo
