### ISSUE TITLE
ICE with const_generic + associated type + double return statement

### ISSUE THREAD

**Issue by raidwas** [rust-lang/rust#64519]
<short summary of the bug>

I tried this code:

```
#![feature(const_generics)]
#![feature(const_generic_impls_guard)]
use core::array::LengthAtMost32;

struct Foo<const D: usize> {
    state: Option<[u8;D]>,
}
impl<const D: usize> Iterator for Foo<{D}> where
    [u8;D]: LengthAtMost32,
{
    type Item = [u8; D];
    fn next(&mut self) -> Option<Self::Item> {
        return Some(self.state.unwrap().clone());
        return Some(self.state.unwrap().clone());
    }
}
```

I expected to see this happen:
It should build.

Instead, this happened: 
rustc crashed with: 
`error: internal compiler error: src/librustc/infer/unify_key.rs:143: equating two const variables, both of which have known values`

Possible workaround: 
replace `Self::Item` with `[u8;D]`.

## Meta
playground: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=849c7ac992950ce15a2fcf075fd61828

rustc version: 1.39.0-nightly 2019-09-15 96d07e0ac9f0c56b95a2

**Comment by mati865** [comment]
cc @varkor: https://github.com/rust-lang/rust/commit/b872e6358549f6627fac1fa7028a547042152806

**Comment by hellow554** [comment]
Also ICEs without explicit feature gate enabled :/

```rust
// #![feature(const_generics)]

struct Foo<const D: usize>;
impl<const D: usize> Iterator for Foo<{D}>
{
    type Item = [u8; D];
    fn next(&mut self) -> Option<Self::Item> {
        return Some([0; D]);
        return Some([0; D]);
    }
}
```
