### ISSUE TITLE
No new nightly for 2019-09-17

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#64540]
Seems like no nightly was released today. That might be related to https://github.com/rust-lang/rust/pull/64451? Unfortunately I don't think I have access to the logs.

Cc @pietroalbini @rust-lang/infra

**Comment by pietroalbini** [comment]
Logs are missing on the server, let me start a manual release...

**Comment by pietroalbini** [comment]
```
thread 'main' panicked at 'failed to find toolstate for rust commit', src/libcore/option.rs:1166:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by RalfJung** [comment]
Well that is odd. You wouldn't know what commit is is using? (`git_commit_hash` file in the `rust` tarball, if I recall correctly.)

**Comment by RalfJung** [comment]
Is there a way for me to download the "dist" artifacts for better testing? Right now I am manually grabbing a bunch of files from https://s3-us-west-1.amazonaws.com/rust-lang-ci2 (and we only get dir listing for alt builds there it seems so I am using those). That's not very convenient at all.

**Comment by pietroalbini** [comment]
Apparently not all commits are pushed to toolstate ([toolstate commits](https://github.com/rust-lang-nursery/rust-toolstate/commits/master) vs [rustc merges](https://github.com/rust-lang/rust/commits?author=bors)), for example the latest one (5670d048c0f88af9976b5505c7853b23dd06770d) is missing in toolstate [as there was nothing to commit](https://dev.azure.com/rust-lang/e71b0ddf-dd27-435a-873c-e30f86eea377/_apis/build/builds/8311/logs/5).

> Is there a way for me to download the "dist" artifacts for better testing? Right now I am manually grabbing a bunch of files from https://s3-us-west-1.amazonaws.com/rust-lang-ci2 (and we only get dir listing for alt builds there it seems so I am using those). That's not very convenient at all.

[rustup-toolchain-install-master](https://github.com/kennytm/rustup-toolchain-install-master)

**Comment by pietroalbini** [comment]
Reverting the cause in the meantime -- https://github.com/rust-lang/rust/pull/64543.

**Comment by RalfJung** [comment]
Alternatively we could land https://github.com/rust-lang/rust/pull/64542 which will just skip of the toolstate is not found.

> rustup-toolchain-install-master

That installs a toolchain based on these artifacts, but I don't think it gives me access to the tarballs.

FTR, for now I did
```
wget 'https://s3-us-west-1.amazonaws.com/rust-lang-ci2/rustc-builds/5670d048c0f88af9976b5505c7853b23dd06770d/rust-nightly-x86_64-unknown-linux-gnu.tar.gz'
wget 'https://s3-us-west-1.amazonaws.com/rust-lang-ci2/rustc-builds/5670d048c0f88af9976b5505c7853b23dd06770d/miri-nightly-x86_64-unknown-linux-gnu.tar.gz'
```

> Apparently not all commits are pushed to toolstate (toolstate commits vs rustc merges), for example the latest one (5670d04) is missing in toolstate as there was nothing to commit.

So we are only committing when the toolstate *changed*? Ouch. That kills my entire approach :(

**Comment by pietroalbini** [comment]
> That installs a toolchain based on these artifacts, but I don't think it gives me access to the tarballs.

It should print the URLs it's downloading though.
