### ISSUE TITLE
Suggest dereferencing boolean reference when used in 'if'

### ISSUE THREAD

**Issue by Aaron1011** [rust-lang/rust#64557]
The following code:

```rust
fn take_bool(val: bool) {}

fn main() {
    let a = &true;
    if a {
        println!("Hello!");
    }
    take_bool(a)
}
```

gives the following errors:

```
error[E0308]: mismatched types
 --> src/main.rs:5:8
  |
5 |     if a {
  |        ^ expected bool, found &bool
  |
  = note: expected type `bool`
             found type `&bool`

error[E0308]: mismatched types
 --> src/main.rs:8:15
  |
8 |     take_bool(a)
  |               ^
  |               |
  |               expected bool, found &bool
  |               help: consider dereferencing the borrow: `*a`
  |
  = note: expected type `bool`
             found type `&bool`

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0308`.
error: Could not compile `playground`.
```

Note that the first error is missing the "help: consider dereferencing the borrow: `*a`" suggestion.

For consistency, Rust should suggest dereferencing a boolean reference when used in an 'if' expression.

This issue has been assigned to @XiangQingW via [this comment](https://github.com/rust-lang/rust/issues/64557#issuecomment-532930277).

**Comment by XiangQingW** [comment]
@Aaron1011 I'd love to be assigned to the issue.

**Comment by Aaron1011** [comment]
@XiangQingW: You can use `@rustbot claim` to assign the issue to yourself.

**Comment by mayabyte** [comment]
Has a PR been submitted for this yet? I'm happy to take it if not

**Comment by XiangQingW** [comment]
> Has a PR been submitted for this yet? I'm happy to take it if not
Hum... I'm working on this, and sorry for the delay because I was busy last weekend.

**Comment by Aaron1011** [comment]
Fixed in https://github.com/rust-lang/rust/pull/65150
