### ISSUE TITLE
Please include rustup in the stand-alone installers

### ISSUE THREAD

**Issue by martinellison** [rust-lang/rust#64550]
**Describe the problem you are trying to solve**
I installed Rust using a stand-alone installer, but then I could not install additional Rust components.

**Describe the solution you'd like**
The stand alone installers should include Rustup, and anything else that installs using `rustup-init`.

**Notes**
After I installed Rust using a stand-alone installer, there was no way to install Rustup, except to remove the whole Rust installation and re-install using `rustup-init`.

**Comment by alexcrichton** [comment]
I've moved this issue to rust-lang/rust from Cargo, since the installers are built here.

**Comment by Mark-Simulacrum** [comment]
I personally think that we shouldn't do this; a user who wants to use rustup should get rustup directly, rather than from a tarball containing other things.

**Comment by martinellison** [comment]
@mark how do I install rustup if I have run the stand alone install? Rust-install doesn't all this.

**Comment by Mark-Simulacrum** [comment]
There should be no reason to run the standalone installer if you're going to install via rustup; if you've already installed you can likely run an uninstall script (I forget if we have this) or manually delete files.

**Comment by Mark-Simulacrum** [comment]
In any case, I'm going to close this. If rustup is not allowing installation of itself atop a prior rust installation, that seems like a rustup feature request -- rustup can either allow that or perhaps offer to clear out the prior installation via some heuristics.

**Comment by follower** [comment]
> There should be no reason to run the standalone installer if you're going to install via rustup;

FWIW one reason to do this (well, in the other order) is to add target platforms (e.g `wasm32-unknown-unknown`) to a standalone install.

(Still likely to be a `rustup` feature add. :) )
