### ISSUE TITLE
the trait std::error::Error is not implemented for getrandom::error::Error |

### ISSUE THREAD

**Issue by BaoshanPang** [rust-lang/rust#64563]
I am seeing this issue when building rust libstd unit test:

error[E0277]: the trait bound getrandom::error::Error: std::error::Error is not satisfied
--> /folk/prj-rust-dev/bpang/ala-diab-pb19l/fix_bugs/latest/.cargo/git/checkouts/rand-cc8f5b7ec2d3b6d9/64a4000/rand_core/src/er
ror.rs:150:28
|
150 | Error { inner: Box::new(error) }
| ^^^^^^^^^^^^^^^ the trait std::error::Error is not implemented for getrandom::error::Error
|
= note: required for the cast to the object type dyn std::error::Error + std::marker::Send + std::marker::Sync

error: aborting due to previous error

For more information about this error, try rustc --explain E0277.

Is anyone else seeing this issue?

Thanks,
Baoshan

**Comment by Mark-Simulacrum** [comment]
How are you building unit tests?

**Comment by BaoshanPang** [comment]
I am using this command line:
./x.py test --stage 1 --target aarch64-wrs-vxworks src/libstd

**Comment by BaoshanPang** [comment]
And I also use the crate getrandom at https://github.com/Wind-River/getrandom.git to have the supporting for vxWorks:
[patch.crates-io]
getrandom = { git = 'https://github.com/Wind-River/getrandom.git', branch = 'master' }

**Comment by BaoshanPang** [comment]
Sorry, the problem is in the getrandom crate used by me.

**Comment by n-salim** [comment]
See https://github.com/rust-random/getrandom/pull/105 for resolution.
