### ISSUE TITLE
String.find("") returns 'Some(0)' when searching for the empty string; expected 'None'.

### ISSUE THREAD

**Issue by richtourist** [rust-lang/rust#64587]
Hey, Ferris. Thanks for Rust.
I was surprised by the result of following code, though...

fn main() {
    let s = "Ferris".to_string();
    println!("{:?}", s.find("F"));
    println!("{:?}", s.find("e"));
    println!("{:?}", s.find("r"));
    println!("{:?}", s.find("Q"));
    println!("{:?}", s.find(""));
}

I expected:
Some(0)
Some(1)
Some(2)
None
None

But I got:
Some(0)
Some(1)
Some(2)
None
Some(0)    // The empty string "" is not found at index [0], the 'F' is; I expected a 'None'.

eg:  assert_eq!(s.find("", None); //FAIL

To me, 'None' seems more suitable because, well, its not there; and 'Some(0)' seems wrong because two different 'finds' can return the same index.

I confirmed this on the Stable and Nightly versions at the Rust Playground, and couldn't find any similar bug on this site. I tried looking at the source code, too, but it's way beyond me.

What do you think, Ferris?

**Comment by Mark-Simulacrum** [comment]
I believe this is consistent with `s.contains("")` for any string returning true, and in any case, we cannot change the behavior at this point, so I'm going to close.
