### ISSUE TITLE
RFC: Better/Shorter syntax to declare multiple variables

### ISSUE THREAD

**Issue by abbychau** [rust-lang/rust#64602]
When we have multiple variable to be declared, we need to write something like this:

```Rust
let (mut a, mut b, mut c, mut d) = (false, false, false, false);
```
There are two obvious factorizations:

The first part is to factorize the `mut` decorator, so to be `let mut (a, b, c, d)`.
Another part is to spread the value tuple, so to be `false`.

That
```Rust
let mut (a,b,c,d) = false;
```

is short while intuitive.

---

Last, in the long form
```Rust
let (mut a, mut b, mut c, mut d) : (bool, bool, bool, bool) = (false, false, false, false);
```
if the type is required there, then it is able to be shorted to.
```Rust
let mut (a, b, c, d) : bool = false;
```

I have thought of making `bool` and `false` there a bit more obvious like the JS style spread(not really the spreading meaning here though):
`(false..)` and `(bool..)` or using other notations like `x!(bool)` and `[bool]`, and etc., but I think that keeping the simple form is good enough and because it does not seem to induce much misleadings while reading .

**Comment by memoryruins** [comment]
For mut shorthand, there is a previous rfc and discussion in https://github.com/rust-lang/rfcs/pull/2401

**Comment by jonas-schievink** [comment]
Hi! Large additions to the language or standard library need to go through our [RFC process](https://github.com/rust-lang/rfcs). Before an RFC is written, the feature can also be discussed in our [internals forum](https://internals.rust-lang.org/) to find other people interested in it.

Closing in favor of an RFC.
