### ISSUE TITLE
Huge increase of size of std between 2019-07-07 and 2019-07-08

### ISSUE THREAD

**Issue by hellow554** [rust-lang/rust#64605]
```
curl -sI https://static.rust-lang.org/dist/2019-07-0{7,8}/rust-std-nightly-x86_64-unknown-linux-gnu.tar.gz | rg content-length
content-length: 82970771
content-length: 211283629
```

this is a difference of around 120MiB :/
`librustc` alone has been increased by 60Mib that night together with `librustc_driver` with another 54Mib plus 30Mib in `rustc_mir`.
Is there a reason for that huge peak?

**Comment by jonas-schievink** [comment]
Looks like https://github.com/rust-lang/rust/issues/62486

**Comment by hellow554** [comment]
Wow.. I say that issue, but I my mind the date didn't match. You're right. closing it.
