### ISSUE TITLE
Omitting struct field name in cast

### ISSUE THREAD

**Issue by mtib** [rust-lang/rust#64614]
```rust

#[derive(Debug)]
struct Example {
    value : u32
}

fn main() {
    let value : i32 = 100;
    
    let example = Example {
        value : value as u32 // cannot remove the "value :"
    };
    
    println!("{:#?}", example)
}

```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=e202b404caa46b101868e1d867439ad3))

I would argue that one should also be able to write:

```rust

#[derive(Debug)]
struct Example {
    value : u32
}

fn main() {
    let value : i32 = 100;
    
    let example = Example {
        value as u32
    };
    
    println!("{:#?}", example)
}

```

and the compiler should infer the field name.

**Comment by petrochenkov** [comment]
Relevant internals thread: https://internals.rust-lang.org/t/idea-puns-in-simple-patterns/10533.

**Comment by jonas-schievink** [comment]
Hi! Large additions to the language or standard library need to go through our [RFC process](https://github.com/rust-lang/rfcs). Before an RFC is written, the feature can also be discussed in our [internals forum](https://internals.rust-lang.org/) to find other people interested in it.

Closing in favor of an RFC.
