### ISSUE TITLE
Rust should not link sanitizer runtimes unconditionally

### ISSUE THREAD

**Issue by choller** [rust-lang/rust#64629]
I've noticed today that apparently Rust adds sanitizer runtimes such as the ASan runtime during linking and I found this runtime inside a static archive.

As far as I know, these runtimes should not be part of static archives or DSOs, they should only be linked when creating an executable. Adding them to DSOs causes two runtimes to exist when loading the DSO into an ASan binary (we had this problem longer ago in mozilla-central and it was fixed in Clang, see [1]). Adding the runtime to static archives causes linker problems when linking the archive to a C++ binary built with ASan because Clang will add the ASan runtime a second time when linking the executable. For some reason this worked before (maybe if the runtimes used are exactly identical the linker will deduplicate them) but today during building with Rust nightly I got duplicate symbol errors indicating two conflicting ASan RTs.

From what I can tell, Rust should not link these runtimes except if it is producing an executable. The respective code is called here independent of `crate_type`:

https://github.com/rust-lang/rust/blob/ea3ba36f3f4b7f0168a27d23c499efeb2304e2d5/src/librustc_codegen_ssa/back/link.rs#L1376

[1] https://github.com/llvm-mirror/clang/blob/7dbdcfcb827c68b0c380de289a2d7526666b8771/lib/Driver/ToolChains/CommonArgs.cpp#L645

**Comment by choller** [comment]
See also https://bugzilla.mozilla.org/show_bug.cgi?id=1533213

**Comment by choller** [comment]
I'm reopening this because the fix I made is not complete. There is a second place where we inject the sanitizer runtime and that is the `inject_sanitizer_runtime` function in `src/librustc_metadata/creader.rs`. It even explicitly attaches the runtime to static libraries. This is a one-line fix but afterwards the `sanitizer-staticlib-link` test fails. This test failure is expected because the test itself is incorrect as well. I will make another PR that has the fix and also changes the test to include a negative-check for the runtime in staticlibs.

**Comment by tmiasko** [comment]
This was fixed in #65497 & #65241.
