### ISSUE TITLE
Async struct method, <_'> lifetime shadowing

### ISSUE THREAD

**Issue by fominok** [rust-lang/rust#64630]
Hello, I ran into a problem using `<'_>` lifetime with async struct methods, here is the example:

    struct Foo<'a> { swag: &'a i32 }

    impl Foo<'_> {
        async fn bar(&self) -> i32 {
            1337
        }
    }

The error is:
`error[E0496]: lifetime name `'_` shadows a lifetime name that is already in scope`

Everything is fine if I use explicit lifetime like `'a`.

Version: 1.39 Nighly (2019-09-19 9b9d2aff8de4d499b4ba on playground)

**Comment by cramertj** [comment]
This is happening because the desugaring of `async fn` uses the `'_` lifetime. This is sort of unfortunate, but seems backwards compatible to fix, so I don't think we should block on this.

**Comment by nikomatsakis** [comment]
We decided to **focus** on this one in the WG meeting -- @matthewjasper you still interested in working on it?

**Comment by matthewjasper** [comment]
Yes, I'm still interested in working on this. I don't think that this should be too hard to fix though if someone else wants it.
