### ISSUE TITLE
Language specification?    

### ISSUE THREAD

**Issue by lithic** [rust-lang/rust#64653]

**Comment by Mark-Simulacrum** [comment]
If you truly are interested in discussing this, please file a more detailed post explaining why you're interested on internals.rust-lang.org. As it stands, I'm closing this issue as it is unhelpful and (currently) out of scope for this repository.

**Comment by lithic** [comment]
Without a spec everything in rust is undefined

**Comment by qnighy** [comment]
You may be interested in discussions like https://users.rust-lang.org/t/is-there-a-plan-to-get-a-formal-rust-language-specification-at-some-point/21622 and https://internals.rust-lang.org/t/formal-semantics-type-rules/584
