### ISSUE TITLE
Outdated `--explain` text for E0432 "An import was unresolved."

### ISSUE THREAD

**Issue by mattheww** [rust-lang/rust#64668]
See [E0432][1] for the current text.

[1]: https://doc.rust-lang.org/error-index.html#E0432

It currently includes:
«
Paths in `use` statements are relative to the crate root. To import items relative to the current and parent modules, use the `self::` and `super::` prefixes, respectively.
»
The first sentence is untrue in Rust 2018, and so the advice about `self::` is unhelpful.

It also says
«
Or, if you tried to use a module from an external crate, you may have missed the `extern crate` declaration (which is usually placed in the crate root):
»
which I think is unhelpful in Rust 2018.

**Comment by BookOwl** [comment]
I can confirm this is still present in Rust 1.41. I would be happy to make a PR to fix this if someone could give me a pointer on where to make the change.

**Comment by mattheww** [comment]
The text lives in `src/librustc_error_codes/error_codes/E0432.md`

https://github.com/rust-lang/rust/blob/master/src/librustc_error_codes/error_codes/E0432.md
