### ISSUE TITLE
Incorrect description of std::prelude name resolution in standard library docs

### ISSUE THREAD

**Issue by mattheww** [rust-lang/rust#64686]
The [documentation for `std::prelude`][1] states:

[1]: https://doc.rust-lang.org/std/prelude/index.html

> On a technical level, Rust inserts
> 
> ```
> extern crate std;
> ```
> 
> into the crate root of every crate, and
> 
> ```
> use std::prelude::v1::*;
> ```
> 
> into every module.

But I believe the second part of that is no longer a correct description of how the prelude works, as far as user-visible behaviour is concerned.

In particular, the following code compiles, but doesn't if I remove the `use` statement:

```
mod foo {
    use std::prelude::v1::*;
    type Bar = self::String;
}
```

And the following doesn't compile (saying «`String` is ambiguous»), but does if I remove the `use` for the prelude:

```
mod foo {
    use std::prelude::v1::*;
    use bar::*;

    mod bar {
        pub struct String {}
    }

    type Baz = String;
}
```

(Looking in [libsyntax_ext/standard_library_imports.rs][2], I think it is still literally true that the compiler inserts a fake `use` directive, but the resolver treats it [entirely][3] [differently][4] to a normal one, so this doesn't seem to be something it makes sense to document.)

[2]: https://github.com/rust-lang/rust/blob/4ff32c07da9d97e6dc315a4a5c9ffbb797cb27bb/src/libsyntax_ext/standard_library_imports.rs#L83
[3]: https://github.com/rust-lang/rust/blob/4ff32c07da9d97e6dc315a4a5c9ffbb797cb27bb/src/librustc_resolve/resolve_imports.rs#L1294
[4]: https://github.com/rust-lang/rust/blob/4ff32c07da9d97e6dc315a4a5c9ffbb797cb27bb/src/librustc_resolve/build_reduced_graph.rs#L359

**Comment by poliorcetics** [comment]
If I understand correctly (and from what your tests indicates), `use std::prelude::v1::*` is effectively added only at the top of every file ?
