### ISSUE TITLE
cmp::max changed behavior in nightly

### ISSUE THREAD

**Issue by emilio** [rust-lang/rust#64710]
This program ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=8cac9661ef1e135fc25d94f33027c9f0)) changed behavior between https://github.com/rust-lang/rust/compare/97e58c0d3...1dd188489.

And broke bindgen as a result in funny ways.

```rust
use std::cmp;

#[derive(Copy, Clone, Debug, PartialEq, Eq, Ord)]
pub enum SizednessResult {
    NonZeroSized,
    DependsOnTypeParam,
    ZeroSized,
}

impl cmp::PartialOrd for SizednessResult {
    fn partial_cmp(&self, rhs: &Self) -> Option<cmp::Ordering> {
        use self::SizednessResult::*;

        match (*self, *rhs) {
            (x, y) if x == y => Some(cmp::Ordering::Equal),
            (NonZeroSized, _) => Some(cmp::Ordering::Greater),
            (_, NonZeroSized) => Some(cmp::Ordering::Less),
            (DependsOnTypeParam, _) => Some(cmp::Ordering::Greater),
            (_, DependsOnTypeParam) => Some(cmp::Ordering::Less),
            _ => unreachable!(),
        }
    }
}

fn main() {
    println!("{:?}", cmp::max(SizednessResult::ZeroSized, SizednessResult::NonZeroSized))
}
```

I suspect https://github.com/rust-lang/rust/pull/64047.

**Comment by emilio** [comment]
cc @timvermeulen

**Comment by emilio** [comment]
Sorry, changelog is https://github.com/rust-lang/rust/compare/97e58c0d3...ed8b708c1, which discards the llvm upgrade.

**Comment by emilio** [comment]
Looking at this further, I think what's going on is that `Ord` and `PartialOrd` don't agree. This may just be a bug in bindgen, who expected (looks like, I didn't write that code) `PartialOrd::partial_cmp` to be called instead of the `Ord` trait...

**Comment by Centril** [comment]
@emilio which means that this issue should be closed since it's a contract violation on bindgen's end?

**Comment by SimonSapin** [comment]
Yes, I think this std change only exposed an existing bug in bindgen. While it is a behavior change, it likely only occurs with contradictory impls:

https://doc.rust-lang.org/std/cmp/trait.Ord.html#how-can-i-implement-ord
> Implementations of `PartialEq`, `PartialOrd`, and `Ord` must agree with each other.

Closing, thanks for investigating @emilio!
