### ISSUE TITLE
Compiler option to augment implicitly typed variables in the code with explicit type information

### ISSUE THREAD

**Issue by andswitch** [rust-lang/rust#64712]
Hi,

Type inference is nice. You can write code faster since you don't have to change type annotations all over the place when you change the type of one thing somewhere. On the other hand, I also think that in some cases it takes more time to grok implicitly typed code, especially if the problem domain and/or the architecture is new to you. You have to dig more into the code to figure out just what you are looking at.

The Rust plugin for CLion puts little tags with the types next to implicitly typed variables. Imho this is really nice because it gives you the type information immediately. You don't have to backtrack anywhere in the code to figure it out. I think this feature also signals there is a need for people to have type information at hand.

A lot of programming time is spent searching API documentation. To me, this is another reason why the extra step of digging for types in implicitly typed code can be undesirable: it's additional cognitive overhead. First you need to figure out the type, then you need to go to the API docs to figure out how it works. It would be easier if the first step was not necessary.

**Just to be clear: I'm not arguing against the existence of type inference or implicitly typed code.** I just think that maintaining a large code base over a long period of time is easier with explicit type information. Especially because software developers come and go. Explicit type information allows new people to grok code faster.

I wonder if more people feel the same way, and in that case could there be some kind of tool (maybe a compiler flag) that transforms the source code by automatically adding type annotations to implicitly typed variables? Like a pre-processing step that you run manually. Just literally performing Rust's type inference algorithm and saving the resulting type annotations in the code as if you typed them there. Personally, I could see myself applying it for instance to a large legacy code base. I think that could help maintainability of the code in such cases...

**Comment by Mark-Simulacrum** [comment]
I believe this is pretty much out of scope for the compiler itself today and is somewhat non-trivial; there is `rustc --unpretty=hir,typed` I believe but it (probably) doesn't provide this directly.

I think RLA and RLS both provide some level of types-on-hover already, and will only be better at doing so faster and such in the future, making this sort of already done on the editor level.

**Comment by estebank** [comment]
The desired information is only in scope for the compiler when it comes to diagnostics themselves, and we're moving in that direction. As @Mark-Simulacrum the request seems to be more appropriate for the RLS and Rust Analyzer projects.
