### ISSUE TITLE
repr attributes can be applied at module level

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/rust#64734]
Spot what's wrong with this code:

```rust
#![repr(C)] struct Foo(i32);

extern "C" {
    fn foo(x: Foo);
}

fn main() {}
```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=fda6cbd1d9bcae478712b342a354ee1d))

For some reason, top-level `#![repr(..)]` attributes are allowed, so `Foo` isn't `repr(C)`. Sadly, 
@rust-lang/underhanded isn't a thing.

**Comment by jonas-schievink** [comment]
I don't think attributes that affect codegen are checked for validity at all. The same thing happens for `#[cold]`, `#[inline]`, etc.

**Comment by rkruppe** [comment]
Some attributes including `#[repr]` and `#[inline]` [*are* checked](https://github.com/rust-lang/rust/blob/43a5ff4222e1f217ac14331afd59f82ec4204d12/src/librustc/hir/check_attr.rs), it appears it's just not visiting the root module. [Nested modules do get checked](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=0cce4d60cb3f81fa5359f7fd934f17b9).

**Comment by Centril** [comment]
*In case* it turns out that many people rely on this, we could give reasonable (and arguably desirable) interpretation to `#![inline]` and `#![repr(C)]`: apply these recursively in the module to e.g. `struct`s and `fn`s (unless there is conflict, in which case the most-local attribute is chosen).

**Comment by carbotaniuman** [comment]
I feel the standard warn by default, deny by default, hard write approach is the easiest way to handle this.

**Comment by varkor** [comment]
Given that occurrences of `#![repr(C)]` currently do nothing, and it's easy to search for in a codebase (and thus remove or audit), I don't see a strong reason not to start emitting errors, rather than just linting, on these.

**Comment by varkor** [comment]
> I don't think attributes that affect codegen are checked for validity at all. The same thing happens for `#[cold]`, `#[inline]`, etc.

We should fix this too, in the same manner as @rkruppe [pointed out](https://github.com/rust-lang/rust/issues/64734#issuecomment-534565928). (Either as part of this issue, or in a new issue.) Lack of validity checking can cause concrete problems, as in https://github.com/rust-lang/rust/issues/64768.

**Comment by ehuss** [comment]
Closing, as this is now a hard error via #76329.
