### ISSUE TITLE
error: internal compiler error: src/librustc_metadata/decoder.rs:483: entry: id not found: DefIndex(86) in crate aljabar with number 15

### ISSUE THREAD

**Issue by GalOz666** [rust-lang/rust#64730]
Hey everybody :) I was trying to test matrix*vector in aljabar crate by
running "cargo test" on:
```


extern crate aljabar;
use aljabar::{matrix, vector};



#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn identity() {
        let pixel = vector![0,255,255,15];
        let kernel = matrix![
        [0,0,0],
        [0,1,0],
        [0,0,0]];
        assert_eq!(pixel*kernel, pixel);
    }
}


```

  and got this:
> 
> error: internal compiler error: src/librustc_metadata/decoder.rs:483: entry: id not found: DefIndex(86) in crate aljabar with number 15
> 
> thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:644:9
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
> error: aborting due to previous error
> 
> 
> note: the compiler unexpectedly panicked. this is a bug.
> 
> note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
> 
> note: rustc 1.38.0-nightly (60960a260 2019-08-12) running on x86_64-apple-darwin
> 
> note: compiler flags: -C debuginfo=2 -C incremental
> 
> note: some of the compiler flags provided by cargo are hidden
> 
> error: Could not compile `KernelFiltering`.
> 
> 

Not sure if it's a known issue or not but if there's anything else you need from me please let me know :)

**Comment by GalOz666** [comment]
version:

> rustc 1.38.0-nightly (60960a260 2019-08-12)
> binary: rustc
> commit-hash: 60960a260f7b5c695fd0717311d72ce62dd4eb43
> commit-date: 2019-08-12
> host: x86_64-apple-darwin
> release: 1.38.0-nightly
> LLVM version: 9.0
>

**Comment by GalOz666** [comment]
verbose trace:

> 
> error: internal compiler error: src/librustc_metadata/decoder.rs:483: entry: id not found: DefIndex(86) in crate aljabar with number 15
> 
> thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:644:9
> stack backtrace:
>    0: <unknown>
>    1: <unknown>
>    2: <unknown>
>    3: <unknown>
>    4: <unknown>
>    5: <unknown>
>    6: <unknown>
>    7: <unknown>
>    8: <unknown>
>    9: <unknown>
>   10: <unknown>
>   11: <unknown>
>   12: <unknown>
>   13: <unknown>
>   14: <unknown>
>   15: <unknown>
>   16: <unknown>
>   17: <unknown>
>   18: <unknown>
>   19: <unknown>
>   20: <unknown>
>   21: <unknown>
>   22: <unknown>
>   23: <unknown>
>   24: <unknown>
>   25: <unknown>
>   26: <unknown>
>   27: <unknown>
>   28: <unknown>
>   29: <unknown>
>   30: <unknown>
>   31: <unknown>
>   32: <unknown>
>   33: <unknown>
>   34: <unknown>
>   35: <unknown>
>   36: <unknown>
>   37: <unknown>
>   38: <unknown>
>   39: <unknown>
>   40: <unknown>
>   41: <unknown>
>   42: <unknown>
>   43: <unknown>
>   44: <unknown>
>   45: <unknown>
>   46: <unknown>
>   47: <unknown>
>   48: <unknown>
>   49: <unknown>
>   50: <unknown>
>   51: <unknown>
>   52: <unknown>
>   53: <unknown>
>   54: <unknown>
>   55: <unknown>
>   56: <unknown>
>   57: <unknown>
>   58: <unknown>
>   59: <unknown>
>   60: <unknown>
>   61: <unknown>
>   62: <unknown>
>   63: <unknown>
>   64: <unknown>
>   65: <unknown>
>   66: <unknown>
>   67: <unknown>
>   68: <unknown>
>   69: <unknown>
>   70: <unknown>
>   71: <unknown>
>   72: <unknown>
>   73: <unknown>
>   74: <unknown>
>   75: <unknown>
>   76: <unknown>
>   77: <unknown>
>   78: <unknown>
>   79: <unknown>
>   80: <unknown>
>   81: <unknown>
>   82: <unknown>
>   83: <unknown>
>   84: <unknown>
>   85: <unknown>
>   86: <unknown>
>   87: <unknown>
>   88: <unknown>
>   89: <unknown>
>   90: <unknown>
>   91: <unknown>
>   92: <unknown>
>   93: <unknown>
>   94: <unknown>
>   95: <unknown>
>   96: <unknown>
>   97: <unknown>
>   98: <unknown>
>   99: <unknown>
> query stack during panic:
> #0 [type_of] processing `aljabar::Vector3::{{constant}}#0`
> #1 [evaluate_obligation] evaluating trait selection obligation `aljabar::Vector<^1_0, 4usize>: std::ops::Mul<^1_1>`
> #2 [typeck_tables_of] processing `tests::identity`
> #3 [typeck_item_bodies] type-checking all item bodies
> #4 [analysis] running analysis passes on this crate
> end of query stack
> error: aborting due to previous error
>

**Comment by Centril** [comment]
> if there's anything else you need from me please let me know :)

It would help if you can reduce the problem to a minimal reproducer without the crate.

(Also note that ICEs are common for `const_generics`.)

**Comment by GalOz666** [comment]
Not sure if i can manage that. Could be over my head.

**Comment by est31** [comment]
@Centril there is a minimal example here: https://github.com/rust-lang/rust/issues/44580#issuecomment-541319443
