### ISSUE TITLE
Clarify when dependencies are linked

### ISSUE THREAD

**Issue by dhardy** [rust-lang/rust#64731]
The reference documents that [exern crate](https://doc.rust-lang.org/reference/items/extern-crates.html) has some documentation on linkage of dependencies, but appears to relate to Edition 2015 (or at least not mention linking without `extern crate`).

We are considering use of `extern "Rust"` and `#[no_mangle]` for custom backends [in getrandom](https://github.com/rust-random/getrandom/pull/109) ([standalone demo](https://github.com/dhardy/rust-sublib-linking)), however before proceeding would like to know:

1.  if we can rely on this poorly documented aspect of the language
2.  why "multiple definition" errors are not *always* present when declaring multiple backend libs with `extern crate`

**Comment by josephlr** [comment]
I think this is mainly an issue of documenting @alexcrichton's comment here: https://github.com/rust-lang/rust/issues/64402#issuecomment-530852886

To summarize: Cargo dependencies and the `--extern` `rustc` flag just make crates candidates for linking, you have to actually _use_ the crate to link it.
