### ISSUE TITLE
move of mutably borrowed content results in a 'use-after-move' bug

### ISSUE THREAD

**Issue by mversic** [rust-lang/rust#64767]
Having played around with rust I encountered something I consider to be violating rust's ownership rules and manifests as a dreaded _use-after-move_ bug. 

I managed to reduce the error to the next example of a linked list where use-after-move manifests as an endless loop. Maybe an example can be made where this bug results in some variant of the **SegmentationFault** so the priority of this issue could be very high.
```
use std::fmt::Debug;

type Link<T> = Option<Box<Node<T>>>;

struct Node<T> {
    data: T,
    next: Link<T>,
}

struct List<T> {
    head: Link<T>,
}

impl<T> Node<T> {
    fn new(data: T, next: Link<T>) -> Self {
        Node {data, next}
    }
}

impl<T> List<T> {
    fn new() -> Self {
        List {head: None}
    }

    fn push(&mut self, data: T) {
        self.head = Some(Box::new(Node::new(data, self.head.take())));
    }
}

struct Iter<'a, T>(Option<&'a Node<T>>);

impl<'a, T: Debug> IntoIterator for &'a List<T> {
    type Item = &'a T;

    type IntoIter = Iter<'a, T>;
    fn into_iter(self) -> Self::IntoIter {
        Iter(self.head.as_ref().map(|n| n.as_ref()))
    }
}

impl<'a, T> Iterator for Iter<'a, T> {
    type Item = &'a T;

    fn next(&mut self) -> Option<Self::Item> {
        if let Some(node) = self.0 {
            if let Some(next) = &node.next {
                self.0 = Some(next.as_ref());
            }

            return Some(&node.data);
        }

        None
    }
}

impl<T> Drop for List<T> {
    fn drop(&mut self) {
        let mut node = self.head.take();

        while let Some(n) = node {
            node = n.next;
        }
    }
}

fn main() {
    let mut list = List::new();
    list.push(42);

    for e in &list {
        println!("List: {:?}", e);
    }
}
```

### Compiler bug description
When run, this code results in an endless loop. Experienced rustacean will probably notice that this code has a bug in the first line of the implementation of the Iterator trait. On that line there is a move of mutably borrowed content which to my knowledge is violating ownership rules. This bug gives access to the value `self.0`(in the next step of the iteration) after that value was moved. This should be a compile error, and it actually is in all other examples I came up with.

### Manifestation of the bug (_use-after-move_)
The bug results in an endless loop since the iterator value is never replaced with `None` to end the iteration. The above implementation of linked list iterator can be fixed by assigning `None` explicitly like: 
```
impl<'a, T> Iterator for Iter<'a, T> {
    type Item = &'a T;

    fn next(&mut self) -> Option<Self::Item> {
        if let Some(node) = self.0 {
            if let Some(next) = &node.next {
                self.0 = Some(next.as_ref());
            } else {
                self.0 = None;
            }

            return Some(&node.data);
        }

        None
    }
}
```
which is just a workaround for the compiler bug and wouldn't even be allowed if the compiler bug is fixed. 

or using `Option::take` like: 
```
impl<'a, T> Iterator for Iter<'a, T> {
    type Item = &'a T;

    fn next(&mut self) -> Option<Self::Item> {
        if let Some(node) = self.0.take() {
            if let Some(next) = &node.next {
                self.0 = Some(next.as_ref());
            }

            return Some(&node.data);
        }

        None
    }
}
```
which is a proper solution.

## Meta
```
rustc 1.37.0 (eae3437df 2019-08-13)
binary: rustc
commit-hash: eae3437dfe991621e8afdc82734f4a172d7ddf9b
commit-date: 2019-08-13
host: x86_64-unknown-linux-gnu
release: 1.37.0
LLVM version: 8.0
```

**Comment by Mark-Simulacrum** [comment]
`        if let Some(node) = self.0 {` in the Iterator impl is copying a `Option<&'a T>` which is always copy as it's just a shared reference. Your example has a lot of code and it's not really clear why you believe this is a problem -- annotating it with some comments of "move here" "use after move here" would be good if you believe this is indeed a compiler bug.

**Comment by mversic** [comment]
@Mark-Simulacrum Yes, it seems that I misinterpreted the issue. I am sorry to have bothered you
