### ISSUE TITLE
Missing backslash in std::ascii::escape_default docs due to faulty rustdoc rendering

### ISSUE THREAD

**Issue by nliberg** [rust-lang/rust#64761]
In the [documentation for std::ascii::escape_default](https://doc.rust-lang.org/std/ascii/fn.escape_default.html) the doc comment fragment ```Double quote is escaped as `\"`.``` is incorrectly rendered as 
> Double quote is escaped as `"`.

(note the missing backslash) instead of the expected:
> Double quote is escaped as `\"`.

Judging by [this comment](https://github.com/raphlinus/pulldown-cmark/issues/356#issuecomment-516100285) this seems to be due to a bug that was fixed in version 0.5.3 of pulldown-cmark, which is what librustdoc currently uses.

Perhaps the online docs have been rendered with a previous version of pulldown-cmark.

**Comment by jonas-schievink** [comment]
This is already fixed on beta/nightly and will also be fixed in the next stable release
