### ISSUE TITLE
Better error messages for unresolved imports due to privateness when using `use foo::*`

### ISSUE THREAD

**Issue by kud1ing** [rust-lang/rust#6477]
In #6443 @cmr  made rustc for the following code

```
mod foo {
   struct Foo;
}

mod bar {
   use foo::Foo;
   struct Bar {
     x : Foo
   }
}
```

explain `error: unresolved import: found "Foo" in "foo" but it is private`.

When the module members however are imported using `*` this way:

```
mod foo {
   struct Foo;
}

mod bar {
   use foo::*;
   struct Bar {
     x : Foo
   }
}
```

rustc only says `error: use of undeclared type name "Foo"`.

I think the most prominent use case could be `use super::*` in unit-test modules.

**Comment by nham** [comment]
Bumping for triage. This is still an issue as of:

    rustc 1.1.0-nightly (21f278a68 2015-04-23) (built 2015-04-24)

The error with glob imports is:

    test_6477.rs:8:10: 8:13 error: use of undeclared type name `Foo`
    test_6477.rs:8      x : Foo
                            ^~~
    error: aborting due to previous error

Without is:

    test_6477.rs:6:8: 6:16 error: type `Foo` is private
    test_6477.rs:6    use foo::Foo;
                          ^~~~~~~~
    error: aborting due to previous error

**Comment by pmarcelll** [comment]
I seems to be fixed:
```
error[E0412]: type name `Foo` is undefined or not in scope
 --> <anon>:8:10
  |
8 |      x : Foo
  |          ^^^ undefined or not in scope
  |
  = help: you can import it into scope: `use foo::Foo;`.

error: aborting due to previous error
```

**Comment by Mark-Simulacrum** [comment]
This is still not fixed, and indeed we now suggest to import `Foo` into scope -- even though this is impossible!

**Comment by Mark-Simulacrum** [comment]
E-needstest.

```
error[E0603]: struct `Foo` is private
 --> test.rs:6:8
  |
6 |    use foo::Foo;
  |        ^^^^^^^^

error: aborting due to previous error(s)
```

**Comment by Mark-Simulacrum** [comment]
gar, no, that was the wrong code sample..

**Comment by steveklabnik** [comment]
Today:

```text
error[E0412]: cannot find type `Foo` in this scope
 --> .\foo.rs:8:10
  |
8 |      x : Foo
  |          ^^^ not found in this scope
help: possible candidate is found in another module, you can import it into scope
  |
6 |    use foo::Foo;
  |
```

Closing!
