### ISSUE TITLE
error: cannot find derive macro `Copy` in this scope

### ISSUE THREAD

**Issue by BaoshanPang** [rust-lang/rust#64771]
I am seeing this issue when building latest rust with latest libc:
```
error: cannot find derive macro Copy in this scope
--> /folk/prj-rust-dev/bpang/V7LIBC-997/dev/.cargo/git/checkouts/libc-d1297d136f47e864/3a9e5d0/src/unix/linux_like/linux/gnu/b64/x8
6_64/align.rs:1:10
|
1 | #[derive(Copy, Clone, Debug, PartialEq)]
| ^^^^
```
The issue can be reproduced with follow steps:

1. get rust
$ git clone https://github.com/rust-lang/rust.git
2. add libc = { git = 'https://github.com/rust-lang/libc.git' } to Cargo.toml under section [patch.crates-io]:
[patch.crates-io]
libc = { git = 'https://github.com/rust-lang/libc.git' }
3. update Cargo.lock
$ cargo update -p libc
4. build
$ ./x.py build -i --stage 0 src/libstd

Is this casued by some change made recently in rust?

**Comment by Mark-Simulacrum** [comment]
I think we should not try to fix things here until this is in nightly at least -- cc @gnzlbg though

**Comment by BaoshanPang** [comment]
Hi Mark,
 
Just want to understand the problem better. So the problem is in rust(not in libc) and we don't want to fix it at this point?

Thanks,
Baoshan

**Comment by Mark-Simulacrum** [comment]
Just blindly patching libc might not work for a host of reasons, notably libc is a bit interesting in that libc is a dep of std. (Of course, I could be wrong -- and this is actually a bug). If a normal libc compilation (e.g., on nightly, or even with a stage1/stage2 compiler off master) doesn't hit then there's probably no reason to be concerned and we can just proceed as is.

**Comment by gnzlbg** [comment]
@BaoshanPang can you check if this PR fixes your issue ?

**Comment by BaoshanPang** [comment]
@gnzlbg 

I am seeing a different error:
   Compiling libc v0.2.64 (https://github.com/gnzlbg/libc.git?branch=fixs#fe67d7d9)
error: no rules expected the token `(`
  --> /folk/bpang/.cargo/git/checkouts/libc-2d0b80a096c2fb1e/fe67d7d/src/unix/linux_like/linux/gnu/b64/x86_64/align.rs:3:27
   |
3  |     pub struct max_align_t([f64; 4]);
   |                           ^ no rules expected this token in macro call
   |
  ::: /folk/bpang/.cargo/git/checkouts/libc-2d0b80a096c2fb1e/fe67d7d/src/macros.rs:66:1
   |
66 | macro_rules! s {
   | -------------- when calling this macro

error: aborting due to previous error

**Comment by BaoshanPang** [comment]
@gnzlbg 
The build pass with your latest change in branch fixs.
Thanks for the quick action.

**Comment by jonas-schievink** [comment]
Closing this as resolved
