### ISSUE TITLE
Suggestion: Option::take_if()

### ISSUE THREAD

**Issue by Boscop** [rust-lang/rust#64789]
Suggestion: Adding `Option::take_if()`. 
It takes a predicate (similar to filter, but for conditional `.take()`):
```rust
pub fn take_if<P>(&mut self, predicate: P) -> Option<T>
where
    P: FnOnce(&T) -> bool 
{
    match self {
        Some(x) if predicate(x) => self.take(),
        _ => None,
    }
}
```

**Comment by fmease** [comment]
We now have `Option::take_if` since 1.80 (2024-07-25): https://doc.rust-lang.org/std/option/enum.Option.html#method.take_if
