### ISSUE TITLE
Cargo fails building `image` on osx nightly

### ISSUE THREAD

**Issue by HeroicKatora** [rust-lang/rust#64788]
See this build job:

https://travis-ci.org/image-rs/image/jobs/589672851

There is no backtrace or error, just:

> thread 'main' panicked at 'index out of bounds: the len is 2 but the index is 2', src/tools/cargo/src/cargo/util/cpu.rs:152:29

It has already reproduced a second time on that exact job. However, it's only been tested on Travis and not a local machine.

**Comment by Mark-Simulacrum** [comment]
Known bug, should be fixed soon. See https://github.com/rust-lang/cargo/pull/7429.
