### ISSUE TITLE
Add a lint to force adding at least one test for each error code?

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/rust#64811]
A lot of error codes currently don't have ui tests nor long error explanation, therefore we cannot know if they're still thrown by the compiler which isn't an ideal situation... Should we add lint/check for this?

cc @rust-lang/compiler

**Comment by estebank** [comment]
Introducing it will be hard to do precisely because I'm sure a non insignificant amount of them are unreachable now.

**Comment by GuillaumeGomez** [comment]
The lint can add a list of error codes to ignore in a first time. I'm currently going through error codes and adding explanations/tests.
