### ISSUE TITLE
`x.py check` should support `--tests` and `--all`

### ISSUE THREAD

**Issue by varkor** [rust-lang/rust#64827]
`cargo check` supports these flags, but it seems `x.py` does not. This means issues in tests can be overlooked, as in https://github.com/rust-lang/rust/pull/64813#issuecomment-535729781.

**Comment by Centril** [comment]
This would have been invaluable when working on https://github.com/rust-lang/rust/pull/65324.

**Comment by jyn514** [comment]
`x.py check` now supports `--all-targets`, which is a superset of `--tests`.
