### ISSUE TITLE
Misleading documentation in `std::option` module

### ISSUE THREAD

**Issue by jfrimmel** [rust-lang/rust#64844]
The current [`std::option` module](https://doc.rust-lang.org/std/option/index.html#options-and-pointers-nullable-pointers) states, that
> Rust's pointer types must always point to a valid location; there are no "null" pointers.

Which is obviously wrong. There are no null references (`&T`),  but there may be raw null pointers (`*const T`).
Maybe the docs should have used the terminology of __smart__ pointers, which would be less misleading and be correct :smile:

**Comment by steveklabnik** [comment]
I'd accept a PR to change "pointer" to "reference" here.

**Comment by srinivasreddy** [comment]
I think we can close this.
