### ISSUE TITLE
Should async/await be strict keywords?

### ISSUE THREAD

**Issue by ehuss** [rust-lang/rust#64853]
My impression is that `async` and `await` should be strict keywords.  They are currently marked as "unused" or "reserved" ([unused](https://github.com/rust-lang/rust/blob/6d07874e883ae4334b42ef3ab04cc3f52ee711ee/src/libsyntax_pos/symbol.rs#L1093-L1095), [unstable](https://github.com/rust-lang/rust/blob/6d07874e883ae4334b42ef3ab04cc3f52ee711ee/src/libsyntax_pos/symbol.rs#L88-L90)).  I think the main consequence is that in error messages it is called a [reserved keyword](https://github.com/rust-lang/rust/blob/a37fe2de697bb1a9d304e4e811836e125f944cd5/src/libsyntax/parse/parser.rs#L412) if you try to use it as an identifier, when it should just say "keyword".

**Comment by petrochenkov** [comment]
Keywords are supposed to migrate from the "reserved-unused" category to "used" immediately after or together with their stabilization. (There are some related comments on the keyword lists in `symbol.rs`).
Stable `async`/`await` is already on beta, right? Then it's time to mark the keywords as "used" as well.

**Comment by ehuss** [comment]
Thanks, I'll take a look at updating it.
