### ISSUE TITLE
Need to cherry pick LLVM support for wasm exceptions

### ISSUE THREAD

**Issue by tlively** [rust-lang/rust#64857]
[This LLVM commit](https://github.com/llvm/llvm-project/commit/5c3cdef84b82464756bb571c13c31cf7773860c3) makes Emscripten's LLVM backend exception handling scheme work with aggregate types returned by value. This commit needs to be included in Rust's LLVM fork in order to re-enable Emscripten's exception handling support after switching to the upstream LLVM backend in https://github.com/rust-lang/rust/pull/63649, including re-enabling the many disabled tests.

cc @alexcrichton

**Comment by cuviper** [comment]
Instructions for LLVM backports are here:
https://rust-lang.github.io/rustc-guide/codegen/updating-llvm.html#bugfix-updates

I can attempt this if you're not able, just let me know.

**Comment by tlively** [comment]
Thanks for the pointer! I can take care of it.
