### ISSUE TITLE
VecDeque constant time reverse?

### ISSUE THREAD

**Issue by lopopolo** [rust-lang/rust#64905]
The only way to reverse a `VecDeque` is to call `swap` to do an in-place reversal, which is O(n).

My understanding is that `VecDeque` is implemented as a ring buffer which means we should be able to implement reverse in constant time with no element swaps by changing the direction in which the ring is traversed.

Even if this is unacceptable, could `VecDeque` get a `reverse` API to match `Vec`?

**Comment by scottmcm** [comment]
"changing the direction of traversal" is called `Iterator::rev`; I believe an extra flag that would always need to be checked on every operation would be unacceptable as an always-there feature in `VecDeque`.

For "add an api to `VecDeque` that `Vec` has", you can probably just open a PR and get feedback from there from libs.  (Though of course `reverse` is technically on slices, not `Vec`.)

**Comment by lopopolo** [comment]
@scottmcm I think this can be done without flags by flipping the sign on the "move to next index for insertion" operation.

When I refer to "changing direction of traversal", I mean internally to the data structure as it figures out which slots to insert elements into, not the external view of the data structure.

**Comment by scottmcm** [comment]
If anyone arrives here in the future looking for an O(n) reverse, once can (as of 1.48) use `vecdeque.make_contiguous().reverse();`.
