### ISSUE TITLE
Tracking issue for `const extern fn` and `const unsafe extern fn`

### ISSUE THREAD

**Issue by Aaron1011** [rust-lang/rust#64926]
This is a tracking issue for implementing and stabilizing defining a `const extern fn` and `const unsafe extern fn`

- [X] Add a test according to https://github.com/rust-lang/rust/pull/64906#issuecomment-539902772 (added in https://github.com/rust-lang/rust/pull/68370)

## Summary

This allows writing `const unsafe extern "calling-convention" fn` and `const extern "calling-convention" fn`:

Today Rust and C calling conventions are stable (as of 1.62, see #95346). All other calling conventions are still unstable.

```rust
const extern fn foo1(val: u8) -> u8 { val + 1 }
const extern "C" fn foo2(val: u8) -> u8 { val + 1}
const unsafe extern fn bar1(val: bool) -> bool { !val }
const unsafe extern "C" fn bar2(val: bool) -> bool { !val }
```

This can be used to const-ify an `extern fn` (or equivalently, to make a `const fn` callable from external code).

## Test cases

1. Test for defining and calling in Rust code: https://github.com/rust-lang/rust/blob/master/src/test/ui/consts/const-extern-fn/const-extern-fn.rs
2. Test that calling with the wrong calling convention (from a `const` context) leads to an error: https://github.com/rust-lang/rust/blob/master/src/test/ui/consts/miri_unleashed/abi-mismatch.rs

**Comment by RalfJung** [comment]
Could you explain a bit more what this means and what the point is? What does the bare `extern` keyword even do? `extern "Rust" fn` and `fn` are the same thing, after all. (`extern fn` is poorly named; AFAIK it really is about specifying the ABI and has little to do with extern visibility.)

**Comment by Aaron1011** [comment]
@RalfJung: The point is to be able to define an `const extern fn` (i.e. `extern "C" const fn`), which has a C-compatible ABI and can be invoked from const contexts.

**Comment by Centril** [comment]
Implemented in https://github.com/rust-lang/rust/pull/64906.

**Comment by Aaron1011** [comment]
From https://github.com/rust-lang/rust/pull/64906#issuecomment-539902772:

> @Aaron1011 Could we also get a test making sure that we properly report an error when calling a const fn using the wrong ABI, such as calling an extern "C" const fn with the call site assuming it is an extern "Rust" const fn? The checks for that should already exist in the engine (for standalone Miri).

@RalfJung: Are you talking about a `miri-unleashed` test involved function pointers? As far I as know, that's the only way for such an ABI mismatch to occur.

**Comment by RalfJung** [comment]
Yes, I meant a `miri-unleashed` test.

**Comment by Aaron1011** [comment]
@Centril: In https://github.com/rust-lang/rust/pull/64906#issuecomment-537589127, you said:

> However, I think we may eventually want a stabilization RFC that takes into account all of the discussion thus far and elaborates on semantics, use-cases, etc.

Since this PR was merged, https://github.com/rust-lang/libc/pull/1536 was merged, which takes advantage of this feature. Do you still want an RFC prior to stabilization? If so, I'd be happy to start writing one up.

**Comment by Centril** [comment]
Some points:

- The pre-expansion gating of the syntax no longer happens. Post expansion gating is used now instead (so you might want to use that to your advantage).

- An RFC is perhaps unnecessary, but a detailed stabilization report could serve the same purpose, and we'd want that for any stabilization.

- To stabilize this now would be to extend the surface arena under which the soundness hole in https://github.com/rust-lang/rust/issues/58794#issuecomment-471281240 applies, so I would like to see that fixed before stabilizing.

**Comment by RalfJung** [comment]
> To stabilize this now would be to extend the surface arena under which the soundness hole in #58794 (comment) applies, so I would like to see that fixed before stabilizing.

Also see https://github.com/rust-lang/rust/issues/63943 where the soundness hole is tracked.

**Comment by Vurich** [comment]
All the issues that were blocking this feature from being stablised appear to have been addressed, could this be stablised now? I _think_ any code that would want to use it could just use a non-const extern function which wraps a `const fn` Rust-ABI function but if there's no reason for it not to be stablised it then it might as well be.

**Comment by Aaron1011** [comment]
cc @rust-lang/lang - This should be ready for stabilization. I've written up a stabilization report in the issue description.

**Comment by nikomatsakis** [comment]
@rfcbot fcp merge

Sounds good to me! Thanks @Aaron1011!

@RalfJung or @oli-obk would love your verbal "ok" here :)

**Comment by oli-obk** [comment]
Yea, this is a harmless change. Though we should add a test for each calling convention that we support to make sure it actually works in a const context. Or restrict the stabilisation to Rust and C calling conventions.

**Comment by RalfJung** [comment]
Same here, no objections from my side.

Nobody is going to expect that Rust-defined `const extern "C" fn` can be called in a C++ constexpr, right?^^

**Comment by joshtriplett** [comment]
@RalfJung That's something that would need defining on the C++ header side. (And if such a mechanism exists, cbindgen/cxx could generate it given `const extern fn`.)

**Comment by joshtriplett** [comment]
It looks like "C" and "Rust" calling conventions were stabilized for the upcoming 1.62 release.

Other calling conventions could be stabilized as well; is there a blocker for doing so?

**Comment by RalfJung** [comment]
I am not aware of any calling convention being special here. (Other than variadics, but those are generally unstable, not just for `const fn`.)
