### ISSUE TITLE
Mixed signals from errors about trait const fns

### ISSUE THREAD

**Issue by glandium** [rust-lang/rust#64947]
I was trying to define a trait method as const, but it turned out in an error, which, according to [RFC911](https://github.com/rust-lang/rfcs/blob/master/text/0911-const-fn.md) is a design decision, and the [tracking issue for const fn](https://github.com/rust-lang/rust/issues/57563) doesn't seem to indicate any change in that matter.

However, the errors I got from the compiler give mixed signals:
```
error[E0379]: trait fns cannot be declared const
 --> src/num.rs:6:5
  |
6 |     const fn next_multiple_of(self, m: T) -> Self;
  |     ^^^^^ trait fns cannot be const

error[E0658]: const fn is unstable
 --> src/num.rs:6:5
  |
6 |     const fn next_multiple_of(self, m: T) -> Self;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: for more information, see https://github.com/rust-lang/rust/issues/57563
```

This could be interpreted as "trait fns cannot be declared const... yet", while the current status is more like "trait fns cannot be declared const now or in the foreseeable future".

**Comment by Centril** [comment]
I think the most honest thing to do here would be to point at the RFC. cc @oli-obk

**Comment by glandium** [comment]
I think pointing at the RFC in E0379 *and* not emitting E0658 would be better.
