### ISSUE TITLE
`saturating_add` doc is not clear enough

### ISSUE THREAD

**Issue by lzutao** [rust-lang/rust#64940]
Godbolt link: https://godbolt.org/z/9rm4jF

So I expect these two functions has the same assembly:
```rust
pub fn foo(a: i32, b: i32) -> i32 {
    a.saturating_add(b)
}

pub fn bar(a: i32, b: i32) -> i32 {
    match a.checked_add(b) {
        Some(v) => v,
        None => i32::max_value(),
    }
}
```

But the result is not:
```asm
example::foo:
        xor     eax, eax
        mov     ecx, edi
        add     ecx, esi
        setns   al
        add     eax, 2147483647
        add     edi, esi
        cmovno  eax, edi
        ret

example::bar:
        add     edi, esi
        mov     eax, 2147483647
        cmovno  eax, edi
        ret
```

**Comment by hman523** [comment]
Hey I tried solving this but wasn't really sure how to. I believe the implementation to the LLVM generation is right here.
 https://github.com/rust-lang/rust/blob/22bc9e1d9ca49ee4f5cd953088ab09c238a6dd26/src/librustc_codegen_llvm/intrinsic.rs#L471-L508
Hope someone can solve this!

**Comment by lzutao** [comment]
Turn out I was wrong! The `saturating_add` is working correctly (i.e. those two functions
are not equivalent): https://github.com/rust-lang/rust/pull/58003/files#diff-01076f91a26400b2db49663d787c2576R885-R891

I would add some doctests to show that and close this issue.
