### ISSUE TITLE
Const eval incorrectly computes that mutable param is zero

### ISSUE THREAD

**Issue by rinon** [rust-lang/rust#64970]
The following code results in a const eval divide by zero error, when it cannot actually error at runtime:

```rust
pub fn foo(mut n: i32) {
  if n < 0i32 { n = 0i32 }
  if n > 0i32 {
    dbg!((1i32) / n);
  }
}
```

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=ee4964acbb7fe290cfdaa573fddf5195

**Comment by ecstatic-morse** [comment]
Regression caused by 488381ce9ef0ceabe83b73127c659e5d38137df0. cc @wesleywiser @oli-obk

**Comment by hellow554** [comment]
Fun thing, it doesn't even depend on the conditions in the if clause:

```rust
pub fn foo(mut n: i32) {
    if false {
        n = 0i32
    }
    if false {
        dbg!((1i32) / n);
    }
}
```

also ICEs

**Comment by rinon** [comment]
Thanks @wesleywiser!
