### ISSUE TITLE
Bad page rendering with js disabled

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/rust#64988]
For example in here: https://docs.rs/slab/0.4.2/slab/struct.Slab.html

No sections is shown because they're hidden by default. It should be overloaded with noscript so that they show by default in such case.

**Comment by GuillaumeGomez** [comment]
cc https://github.com/rust-lang/docs.rs/issues/419

**Comment by the8472** [comment]
Using [<details>/<summary>](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details) for all sections that can be toggled would be a noscript-compatible, interactive solution. It can still be enhanced by javascript to respect global toggles.

Edge doesn't support it but that just means edge users will have to rely on javascript as they already do today.

**Comment by GuillaumeGomez** [comment]
I'm not sure it'd fix the initial issue which made us add this auto-parts hiding. We're doing a lot of changes into the DOM so the goal is to not render it in order to make the rendering way faster.

**Comment by the8472** [comment]
> We're doing a lot of changes into the DOM so the goal is to not render it in order to make the rendering way faster.

The content of details is hidden by default, only the summary is shown until you open it. So it would keep that property

> Also, we're currently supporting down to IE9. So if a recent browser like Edge doesn't support it, I'm not too much into using such a feature...

I don't see any problems though

|  | IE | Edge | Browsers with `<details>` support | 
| ------------| ------------ |------------ | -------------| 
| javascript | CSS, JS solution<br> as good as current | CSS, JS solution<br> as good as current | `<details>` + JS solution, better accessibility than current | 
| noscript | N/A<br> no noscript extensions in IE | currently broken. could add noscript CSS (as PR does) but leaving it broken would be no worse than current. will move to chromium soon anyway | interactive by default browser behavior, improvement over current |

**Comment by GuillaumeGomez** [comment]
The advantage of the current situation is that it works on all supported browsers whereas `details` would just show everything and slow down the page rendering on old web browsers which are already the slowest. Once we drop old browsers support, I'm all for it but for now, not too much like I said...

**Comment by the8472** [comment]
> The advantage of the current situation is that it works on all supported browsers whereas details would just show everything

Details does not show things by default unless you add the [`open` attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/details#Attributes).

The same behavior can be implemented in old browsers with CSS rules. Javascript would only have to toggle the attribute.

<details><summary>Lorem ipsum </summary>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent et sem et lacus tincidunt posuere id sed orci. Orci varius natoque penatibus et magnis dis parturient montes</details>

**Comment by GuillaumeGomez** [comment]
That doesn't answer my concerns at all:

> The advantage of the current situation is that it works on all supported browsers whereas `details` would just show everything and slow down the page rendering on old web browsers which are already the slowest. Once we drop old browsers support, I'm all for it but for now, not too much like I said...

**Comment by the8472** [comment]
simplified compatibility shim for IE, omitting the caret styling:

```css
// default.css
details > * {display: none;}
details > summary {display: block;}
details[open] > * {display: block;}

// noscript.css
details > * {display: block;}
```

This way it would not show everything by default and still would have to be unfolded via JS, exactly the same as today. No negative impact on rendering performance.
