### ISSUE TITLE
Tracking issue for unsizing casts in const fns

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#64992]
Right now we don't allow unsizing casts (array -> slice or type -> dyn Trait) in const fns on stable.

While we can't allow unsizing to `dyn Trait` until we've figured out trait bounds in const fns, we can easily allow unsizing casts for slices, there's no reason not to have them. The only reason we didn't have them in the initial min_const_fn feature gate was the fact that we preferred overly aggressive rules over accidental stabilization.

The relevant code is https://github.com/rust-lang/rust/blob/dc45735f29788924b9fc351d100e5bf3ebdca162/src/librustc_mir/transform/qualify_min_const_fn.rs#L162-L165 

We need to check the destination and source types for slice and array respectively and permit the cast in that case. We also need to recurse with `check_operand` on the value that is being casted.

**Comment by RalfJung** [comment]
Judging from the feature message, nowadays slices seem to be allowed by `dyn` unsizing is still disallowed -- but only in `const fn`. We also have no tests using this feature (just some compile-fail tests checking the feature gate).

I am not entirely sure why these casts are disallowed *only* in `const fn`, but I assume it is a matter of backwards compatibility. However, this means we already have to be sure that the corresponding Miri code is right, so -- what is blocking us from simply removing this feature gate, and allowing the corresponding code?

**Comment by RalfJung** [comment]
In fact while trying to write a gate test for https://github.com/rust-lang/rust/pull/84310, I was unable to find any example of a piece of code that compiles once `const_fn_unsize` is allowed. I always then additionally get the error about "trait bounds other than `Sized`".

@oli-obk  If we just removed this `UnsizingCast` and all its call sites, is there *any* additional code that would be accepted?

**Comment by RalfJung** [comment]
Ah I found something
```rust
const fn test() {
    let _x = NonNull::<[i32; 0]>::dangling() as NonNull<[i32]>;
}
```
I am not sure why this is gated. It's not a slice directly, but it's also not a lot more complicated.

**Comment by oli-obk** [comment]
Slices are OK, trait objects aren't. If the same code snippet but with trait objects fails even with the feature gate, just removing that check is fine by me (needs stab report and lang team approval on the stab PR)

**Comment by RalfJung** [comment]
Yeah, there is a rather aggressive check for `dyn Trait` appearing anywhere that triggers "trait bounds other than `Sized` are unstable".

**Comment by RalfJung** [comment]
@rust-lang/lang I would like to propose stabilizing this feature.

### Stabilization report

`const_fn_unsize` prevents certain unsizing casts from happening in `const fn` (they were already allowed in `const`/`static` bodies):
```rust
const fn test() {
    let _x = NonNull::<[i32; 0]>::dangling() as NonNull<[i32]>;
}
```
Unsizing casts where the type itself has a slice as "unsized tail" were already allowed, but when the type is a *pointer to* something that has a slice as unsized tail, it was forbidden. By stabilizing `const_fn_unsize`, we allow code like the above. The CTFE engine has supported such code for a long time (and this is battle-tested in standalone Miri), so I see little risk here.

https://github.com/rust-lang/rust/pull/85078 turns `src/test/ui/consts/const_fn_unsize.rs` into a test checking correct functionality of this feature.

**Comment by Mark-Simulacrum** [comment]
Dropping nomination, FCP proceeding smoothly.
