### ISSUE TITLE
Entire program seems to be optimized away

### ISSUE THREAD

**Issue by Daniel-B-Smith** [rust-lang/rust#65008]
I've come across a situation where the presence or absence of a comment changes the program behavior. With the comment present, the program does exactly what I expect (prints a bunch of stuff). Without the comment, the program does nothing and terminates with exit code 0.

I have an example (including Dockerfile) where I've stripped out everything proprietary and some extraneous code here: https://github.com/Daniel-B-Smith/compiler_example As currently committed, the program works fine. Deleting the comment at the bottom of the `main()` function causes the program to misbehave. Apologies that the example is still pretty large.

The example fails on 1.38.0 both with and without `--release`. The code the example is based on has failed with 1.37, 1.38 and the beta (as of yesterday). The program seems to work fine for 1.38.0 on Mac OS X 10.13.16.

Please let me know if there is any additional information that would be valuable.

**Comment by rep-nop** [comment]
Are you sure its not an issue with the Dockerfile somehow? Because [this](https://github.com/Daniel-B-Smith/compiler_example/blob/8489759110d9b5abc45f7ec33d5e99436b2ecb18/Dockerfile#L18) is exactly that -- a program that does nothing and exits with exit code 0.

**Comment by Daniel-B-Smith** [comment]
After additional testing, that appears to be the case. I was thrown off since that Dockerfile works as expected for the mass majority of cases. My apologies for the noise.
