### ISSUE TITLE
Regression in spacing of left margin in diagnostics

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust#65001]
```rust
struct A;
//
//
//
//
//
//
//
fn main() {
    let _: () = A;
    let _: () = B;
}
```

#### `$ cargo +nightly-2019-10-01 check`

This is the correct output.

```console
error[E0425]: cannot find value `B` in this scope
  --> src/main.rs:11:17
   |
11 |     let _: () = B;
   |                 ^ help: a unit struct with a similar name exists: `A`

error[E0308]: mismatched types
  --> src/main.rs:10:17
   |
10 |     let _: () = A;
   |                 ^ expected (), found struct `A`
   |
   = note: expected type `()`
              found type `A`
```

#### `$ cargo +nightly-2019-10-02 check`

Notice that one of the errors has a column of whitespace between the line number and the pipes, the next does not.

```console
error[E0425]: cannot find value `B` in this scope
  --> src/main.rs:11:17
   |
11 |     let _: () = B;
   |                 ^ help: a unit struct with a similar name exists: `A`

error[E0308]: mismatched types
 --> src/main.rs:10:17
  |
10|     let _: () = A;
  |                 ^ expected (), found struct `A`
  |
  = note: expected type `()`
             found type `A`
```

Commit range: https://github.com/rust-lang/rust/compare/22bc9e1d9...702b45e40

**Comment by dtolnay** [comment]
Mentioning @AnthonyMikh @estebank who made changes in librustc_errors. Could this be from #64935?

**Comment by dtolnay** [comment]
It looks like this can cause the wrong line number to be printed. :(

If you bump the problematic line down to line 100, it prints as 10:

```console
error[E0308]: mismatched types
 --> src/main.rs:100:17
  |
10|     let _: () = A;
  |                 ^ expected (), found struct `A`
  |
  = note: expected type `()`
             found type `A`
```

**Comment by estebank** [comment]
It seems like it might be.

**Comment by AnthonyMikh** [comment]
> 
> 
> Mentioning @AnthonyMikh @estebank who made changes in librustc_errors. Could this be from #64935?

Indeed. Upon closer inspection I've found out that 7b4c5c62aaa86301c2f358623bf3bfee39e7beef actually changes the semantics of method: after applying this commit, if `children` is not empty, then `max` of them is not compared with `primary`, although `primary` could actually be greater.

The correct code should rather look like this:

```rust
    fn get_max_line_num(&mut self, span: &MultiSpan, children: &[SubDiagnostic]) -> usize {
        let primary = self.get_multispan_max_line_num(span);
        children.iter()
            .map(|sub| self.get_multispan_max_line_num(&sub.span))
            .max()
            .unwrap_or(0)
            .max(primary)
    }
```

Although it might be not the bug responsible for this issue, it definetely should be fixed. I'll make a PR with fix ASAP

**Comment by estebank** [comment]
Subtle. That seems about right.

**Comment by AnthonyMikh** [comment]
> For every problem there is a solution that is simple, neat—and wrong.
