### ISSUE TITLE
Internal Compiler Error When Making Requests With Hyper

### ISSUE THREAD

**Issue by monarrk** [rust-lang/rust#65017]
I've been staring at this error all day long and finally decided to file a report for it, so here we are.

I'm attempting to make a request using identical code to the [hyper client.rs example](https://github.com/hyperium/hyper/blob/master/examples/client.rs), but I continue to get [this error](https://pastebin.com/BwzguXMD) (invoked by `RUST_BACKTRACE=full cargo build --verbose`. Frankly I don't know much about the inner workings of rust (or even intermediate things about it) so this could very easily be me making a syntax error somewhere and having it just spiral out of control. In any case, this has been driving me nuts and if anyone might know what's going on, I'd really appreciate your help.

**Comment by matthiaskrgr** [comment]
Looks like this is a duplicate of https://github.com/rust-lang/rust/issues/64964

**Comment by monarrk** [comment]
that does seem to be the case, sorry about that
