### ISSUE TITLE
`SocketAddr{V4,V6}` or `Ip{V4,V6}Addr` should have `ANY`/`any` constructor

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#65034]
A commonplace difference between Windows and other targets is that to bind to "all" interfaces, you need to use `LOCALHOST` on Windows and `UNSPECIFIED` everywhere else. We should make this easy via e.g. associated methods like these:

```
SocketAddrV4::any(port)
SocketAddrV6::any(port) // not sure if this wants the flowinfo and scope_id arguments as well
```

**Comment by srinivasreddy** [comment]
I would like to take this.  Okay to raise PR or scheduled for a future release?

**Comment by nagisa** [comment]
You are welcome to implement this, but bear in mind that this issue is my personal feature request and there is no guarantee T-libs will accept it.

**Comment by ollie27** [comment]
> A commonplace difference between Windows and other targets is that to bind to "all" interfaces, you need to use `LOCALHOST` on Windows and `UNSPECIFIED` everywhere else.

@nagisa Are you sure about that? Do you have an example of code that behaves differently on Windows than other targets?

**Comment by nagisa** [comment]
Amusing, I was not able to reproduce this on my recent W10 VM, but I’m fairly confident I had hit this with the more ancient versions of Windows. Closing for now as inapplicable.
