### ISSUE TITLE
Type Inference issue with Option<Box<dyn Trait>>

### ISSUE THREAD

**Issue by sitius2** [rust-lang/rust#65058]
My current project uses a wrapper struct that wraps every occuring error in a struct that has a field of the type Option<Box<dyn std::error::Error>>. During implementation of the From<*> traits I encountered the issue shown in the picture:
![Screenshot 2019-10-02 at 20 12 35](https://user-images.githubusercontent.com/35724051/66131987-a4bad780-e5f4-11e9-9158-26bcdc835ccc.png)

However, when I moved the creation of the Option to the struct initialization and the error was gone.
![Screenshot 2019-10-02 at 20 13 57](https://user-images.githubusercontent.com/35724051/66131985-a4224100-e5f4-11e9-8a03-d8b87a6cfbe6.png)

As far as I know, both code samples should end up being the same.

```
$ rustc --version
rustc 1.38.0 (625451e37 2019-09-23
```

**Comment by jonas-schievink** [comment]
This is expected behavior, also see the nomicon chapter on coercions: https://doc.rust-lang.org/nomicon/coercions.html
