### ISSUE TITLE
Port rust python scripts to python3

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/rust#65063]
Since python2 support will stop at the end of the year, I think it's time to move on. Will send the PR tomorrow.

**Comment by Mark-Simulacrum** [comment]
We will want to also track LLVM pretty closely here.

**Comment by cuviper** [comment]
AFAIK they all work with python3 already, so this would mostly be a matter of defaults, like the `#!` line in `x.py` and the `try` commands in the `configure` script. Plus CI updates to install python3 at all.

Installed scripts like `rust-gdb` and `rust-lldb` need to match whatever is used by that debugger on the target system -- it's best IMO if we can keep those bilingual for python 2/3. For example, while RHEL 7.7 does have python3 now, its gdb is built against libpython2.7, and that won't change.

**Comment by Mark-Simulacrum** [comment]
So we probably want to switch our CI and such to use python 3 by default but be careful when accepting patches to ensure compat with python 2, right? Is that a correct read of the situation?

**Comment by cuviper** [comment]
Yep -- maybe even leave one CI deliberately on python2.7 to be sure.

**Comment by GuillaumeGomez** [comment]
@cuviper We still have some `__future` imports so not sure we're fully compatible with python3. In any case, we can enforce it.

**Comment by cuviper** [comment]
The `__future__` module still exists in 3:
https://docs.python.org/3.7/library/__future__.html

**Comment by GuillaumeGomez** [comment]
Oh? I didn't know this, thanks for the info! Anyway, doesn't hurt to get rid of it in full python3 source code. :)
