### ISSUE TITLE
Create an `apitest` tool for stabilizing core interfaces.

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#6508]
This would be a tool to guarantee stability and backwards-compatibility of core library interfaces. It takes a rust source file (the 'spec') that declares the item's and `pub uses` in core, without implementation. It then parses both the spec and the library and compares them. Any mismatches are errors. Report various metrics about stable/unstable APIs.

The goal is to make it very difficult to change interfaces that are stable. The downside is that you have to ultimately redeclare all of core.

**Comment by steveklabnik** [comment]
Triage: we have stability attributes for this purpose, and while it's not quite the same thing, it's working at the moment. I feel like this may be a conceptual dup of another issue relating to stability detection, but I'm not sure, so leaving it open for now.

**Comment by steveklabnik** [comment]
Revisiting a few months later, we have a good story with how we ensure lack of breakage here, through stability attributes. So giving this a close.
