### ISSUE TITLE
Ephemeral borrow on a RefCell that extracts a Copy struct member in func argument position does not drop the borrow before making the funcall

### ISSUE THREAD

**Issue by lopopolo** [rust-lang/rust#65086]
Playground: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=be4dfa9fda3dbe2c8ccb42c3785bd658

This code panics and I do not think it should.

```rust
use std::cell::RefCell;
use std::rc::Rc;

#[derive(Clone, Copy)]
struct Item(u32);

#[derive(Clone)]
struct Interp(Rc<RefCell<Item>>);

fn func(interp: &Interp, item: u32) {
    interp.0.borrow_mut();
    println!("{}", item);
}

fn main() {
    let interp = Interp(Rc::new(RefCell::new(Item(42))));
    func(&interp.clone(), interp.0.borrow().0);
}
```

**Comment by jonas-schievink** [comment]
Temporaries like `interp.0.borrow()` live until the end of the containing statement (in this case, the call to `func`), so this is expected behavior.

**Comment by lopopolo** [comment]
Thanks Jonas. I’m not sure how I could have known this short of asking a compiler dev. Is a clippy lint (like the ticket I filed) the best way to prevent this mistake?
