### ISSUE TITLE
Add support for `-Ztimings` to `x.py`

### ISSUE THREAD

**Issue by nnethercote** [rust-lang/rust#65088]
Cargo's new experimental `-Ztimings` flag is really cool. See [here](https://gistpreview.github.io/?74d799739504232991c49607d5ce748a) for sample output. It would be great to add support for this to `x.py`. It would help a lot with #65031.

I tried and failed to get `-Ztimings` working with rustc, according to some instructions [here](https://internals.rust-lang.org/t/exploring-crate-graph-build-times-with-cargo-build-ztimings/10975/18). One complication is that rustc normally builds with a beta version of Cargo, but `-Ztimings` is nightly only.

@ehuss : what steps did you take to get the rustc measurements? Thanks!

**Comment by ehuss** [comment]
I didn't run it against rustc, that was Alex.  You have to edit `config.toml` and set `build.cargo` to a nightly version of cargo (like from the `.rustup` directory, or build it yourself).  Then edit the [`cargo` function](https://github.com/ehuss/rust/blob/c6ad892bd0e2616e5d4131afd51dd71ce13a86ed/src/bootstrap/builder.rs#L779) to add `-Ztimings`.  It looks like someone has made a PR to make that read from an env.

**Comment by nnethercote** [comment]
> You have to edit config.toml and set build.cargo to a nightly version of cargo

@alexcrichton: can you give the exact steps here? I tried to do this but failed. Thanks!

**Comment by ehuss** [comment]
What kind of error did you run into?  Here's what my rust `config.toml` looks like (adjust for your setup):

```toml
[build]
cargo = "/Users/eric/.rustup/toolchains/nightly-x86_64-apple-darwin/bin/cargo"
```

And here's what the diff might look like:

```diff
diff --git a/src/bootstrap/builder.rs b/src/bootstrap/builder.rs
index 5d586f0c461..ef01c18eaa0 100644
--- a/src/bootstrap/builder.rs
+++ b/src/bootstrap/builder.rs
@@ -776,7 +776,8 @@ impl<'a> Builder<'a> {
         cargo
             .env("CARGO_TARGET_DIR", out_dir)
             .arg(cmd)
-            .arg("-Zconfig-profile");
+            .arg("-Zconfig-profile")
+            .arg("-Ztimings");

         let profile_var = |name: &str| {
             let profile = if self.config.rust_optimize {
```

I have nightly 2019-10-02, which seems to work.  Sometimes bootstrapping won't work on the latest cargo because the bootstrap code needs updating, but it seems to be working at this point in time.

**Comment by alexcrichton** [comment]
@nnethercote oh I didn't actually add support to `./x.py` when I generated my graphs, I literally just did:

```
$ cd src/rustc
$ cargo +nightly build -Z timings
```

and then fixed any missing env vars that the crates reported. I would expect that @ehuss's patch would work as expected, although it may also require a temporary check for `if stage != 0` somewhere

**Comment by Zoxc** [comment]
You can now do this with `CARGOFLAGS=-Ztimings`.

**Comment by andjo403** [comment]
@nnethercote do you want more support then `CARGOFLAGS_BOOTSTRAP=-Ztimings ./x.py build --stage 1` or can this be closed now?

**Comment by nnethercote** [comment]
I used `CARGOFLAGS=-Ztimings ./x.py build` for the first time yesterday and it worked great!
