### ISSUE TITLE
Is panic message stabilized?

### ISSUE THREAD

**Issue by chessnokov** [rust-lang/rust#65093]
Can I parse output from a program "**thread** 'main' **panicked at** '**called** `Result::unwrap()` on an `Err` value: ()" to detect what panic has occurred?

**Comment by sfackler** [comment]
I would probably not consider it stable, but you can set your own panic hook to produce output that you do know the structure of: https://doc.rust-lang.org/std/panic/fn.set_hook.html

**Comment by Mark-Simulacrum** [comment]
Closing per the above. Certainly the thread name here can change.
