### ISSUE TITLE
VecDeque: add with_exact_capacity

### ISSUE THREAD

**Issue by MOZGIII** [rust-lang/rust#65132]
I've tried this code:
```rust
let vd = VecDeque::with_capacity(1024);
dbg!(vd.capacity());
```
The observed behavior is `vd.capacity() = 2047`

It would be great if there was a call like `fn with_exact_capacity<T>(capacity: usize) -> Result<VecDeque<T>, ()>` that would return a `VecDeque` only and if only it can successfully create a `VecDeque` with exactly the requested capacity, and return an error otherwise.

Some assertions for the proposed behavior:

```rust
let vd_result = VecDeque::with_exact_capacity(1024);
assert!(vd.is_err());
```

```rust
let vd_result = VecDeque::with_exact_capacity(1023);
assert!(vd_result.is_ok());
assert_eq!(vd_result.unwrap().capacity(), 1023);
```

**Comment by jonas-schievink** [comment]
What's the use of such an API that isn't covered by `with_capacity` already?

**Comment by MOZGIII** [comment]
Predictability of the behavior. In some very specific conditions, when I allocate 32 mb vecdeque, I don’t want to unexpectedly be 64 mb. The current *API* doesn’t let me to control this, cause the actual capacity to be allocated is hidden in the implementation details. Now, the proposed API would, without exposing the actual allocation logic, will give me the ability to make the code allocate memory more precisely.

**Comment by MOZGIII** [comment]
In other words, while I can account for the current capacity rounding behavior, it’s not manifested in the API. This proposal preserves that abstraction, while allowing you to react appropriately if the underlying implementations starts to break the invariants you require for the code to have.
Given that `std` can’t be version-controlled independently, I think this is a way to go.

**Comment by bluss** [comment]
VecDeque currently only grows in powers of two, and one slot is always held free (hence capacity will be 2<sup>x</sup> - 1). It would need significant updates to be able to support other allocation sizes.

**Comment by MOZGIII** [comment]
I propose to keep the same size limitations. The difference would be that instead of allocating more than requested, if the requested size in not a power of 2 - 1, to return an error.

**Comment by the8472** [comment]
That would mean callers would depend on implementation details to get a successful allocation, that seems to be a forward-compatibility hazard.

Wouldn't it be better for the caller to simply emit a warning when it detects such undesired behavior and then let the developer to choose a better size if the VecDeque implementation changed?

**Comment by MOZGIII** [comment]
The point is to opt-in the dependency of that implementation detail. For example, with this code I'd catch an error, emit warning and allocate via `with_capacity` if that's desirable. This is implementation detail, and if want to do precise allocations - I *have* to depend on it *even if it's not explicitly expose via the API*.

If `VecDeque` implementation changes we'll just deal with that. It's better than nothing.

**Comment by the8472** [comment]
If you're targeting implementation-specific behavior then you can already do that today by providing a capacity goal that results in the outcome you want, then probe the outcome and emit a warning/error when it doesn't match expectations. You can even put that in your testsuite.

What a new API would do is *encourage* implementation-specific behavior because the set of values that don't result in an error is sparse. I don't think that's a good idea.

Perhaps a `with_capacity_ceiling(limit: usize)` that initializes to a capacity to be `<= limit` based on internal sizing policies.

**Comment by MOZGIII** [comment]
Well, maybe we can add this API as an `unstable`-only?

**Comment by the8472** [comment]
In that case I don't see what value it would add over the create + verify approach.

**Comment by MOZGIII** [comment]
But create + verify is not zero cost.

**Comment by the8472** [comment]
It is with optlevel=2 or above

```rust
pub fn main() -> Result<(), &'static str> {
    let v = std::collections::VecDeque::<u8>::with_capacity(127);
    match v.capacity() {
        127 => Ok(()),
        _ => Err("unexpected capacity")
    }
}
```

```asm
example::main:
        mov     edx, 6
        xor     eax, eax
        ret
```

**Comment by MOZGIII** [comment]
Nice, I think this works for me. It relies on a hell of a lot more implementation details and optimizations though. I don't like that, and would prefer the library solution better, but whatever.

**Comment by MOZGIII** [comment]
Actually, does this still hold for the case where the buffer size is not hardcoded?

**Comment by MOZGIII** [comment]
This case is practically important, because in our use case for some `VecDeque`s we can hardcode the size, but for other we can't.

**Comment by the8472** [comment]
No, in that case it would cost a compare and non-taken branch (2 instructions), but you said you're targeting exact sizes, which can only be achieved by passing specific values that match the current implementation, that does not match what your example does where you can pass arbitrary values.

**Comment by MOZGIII** [comment]
I do pass arbitrary value, and I need the code to properly handle the incorrect with an error instead of an allocation. I think I made it clear that this was my premise from the beginning.

**Comment by MOZGIII** [comment]
Look, I know that I can write the code that does an allocation, then does the check, and then errors out. From the point of the Rust virtual machine it would not be a zero-cost operation in the error case. I want a way to optimize for that error condition. If optimized does some magic - that's good, but not good enough because it's even less reliable than using an unstable API for example, and takes far more caution to maintain.
I'm using rust cause it aims to be a system level language, and it promises predictability and zero cost abstractions. This API here has an issue with both of those. It aims to provide *forward-compatibility* at the cost of runtime overhead. Best shot I got now is to just copy the implementation details size determination logic in my ad-hoc check - this is far worse than having an API that does that. Why you ask? That's because the implementation detail de-facto becomes a part of the API, just by me doing what I need to do. This is not an issue with my task, it's an issue with the API, and not having this captured explicitly does more bad than good to the API maintainers themselves - because at their best effort to actually deliver backward compatibility when the implementation changes they won't be able to observe the breakage. This doesn't prevent maintainers from actually changing the API in a breaking way - but at least they'll take proper measures to inform people accordingly.

**Comment by the8472** [comment]
If you want to fail hard you can make it a debug assert, then it has no costs in release builds.

If you want to emit a warning you can just allocate and test because the fallback code path would have to do the same allocation anyway.

Failing hard in production builds from different rust versions would be contrary to rust's stability guarantees.

> From the point of the Rust virtual machine it would not be a zero-cost operation in the error case.

Neither would it be if the method were implemented. The compare and jump instruction would still have to exist to return an error instead of a success. The resulting assembly would not change.

**Comment by MOZGIII** [comment]
All of that is only true if you assume there is a fallback call to allocate the `VecDeque` with, which is not necessarily true. The error condition could be handled differently, for example with choosing a smaller value instead of a bigger one, or by using an entirely different data structure. It's a challenging exercise to predict how a generic container could be used.

A few thoughts on the API: if we develop this idea further, ideally there would be a newtype of `usize` for supported `VecDeque` capacity sizes, with `TryFrom` for `usize` and some constructor that would build it with rounding to the upper supported value. That might limit the API evolution too much though, so I'm not sure if it's a good idea. On the other hand, it's unlikely that people would be ok with changing `VecDeque`'s internal data structure - simply because people do rely on the implementation detail (i.e. performance predictability) much more than they do in less low-level languages (like Java or Ruby for example).

**Comment by the8472** [comment]
> It's a challenging exercise to predict how a generic container could be used.

Well, sure, but what was your current need that drove you to write the proposal for that method, not hypothetical needs that would rationalize the proposal after it has been made?

I don't see the big picture. Specific uses can already be covered by other means. Also why is this specific to VecDeque? Hash{Map,Set} have similar behavior for similar reasons.

> The error condition could be handled differently, for example with choosing a smaller value instead of a bigger one

I proposed `with_capacity_ceiling(limit: usize)` for that case which would not have to expose implementation details.

**Comment by MOZGIII** [comment]
> Well, sure, but what was your current need that drove you to write the proposal for that method, not hypothetical needs that would rationalize the proposal after it has been made?

I'm created this basically to unlock the possibility of a more precise memory allocations in my app. I'm currently hard-coding the sizes, but I want to expose them as a configuration value. And I want the allocations to be precise if the user demands it.

> Also why is this specific to VecDeque? Hash{Map,Set} have similar behavior for similar reasons.

This a good point, maybe we should think about this in a broader way. Currently the design doesn't try to optimize that error case in any of the existing API. I don't think it was explicitly chosen to not be supported though, but rather simply not taken into account. It would be great to hear from more people that took part in the design process.

> Vec's resizing strategy was changed before at least to be more allocator-friendly.

Well, I'm sure that was a controversial change :) In a sense that people implementing the change couldn't feel confident about not breaking a system or two, and even though it's an internal implementation detail - people were explicitly informed (in the change logs / blog posts). The difference between the resize logic change and the change to introduce this API is that capacity is already somewhat exposed, and if the capacity calculation logic changes in an incompatible way it *will* break the code that relies on it (and that's already possible to rely on that currently, for example when implementing the logic around capacity boundaries). The *precise on success / zero-cost on error* operation mode is not supported though - and the proposed API change solves just that.

**Comment by MOZGIII** [comment]
For my use case, I probably need a `VecDeque` without any kind of resize support for my case, because I want to prevent any allocation after some kind of initialization stage completes. This has little to do with the issue, other than that I'd probably want to switch from the std VecDeque anyway - just to be sure the reallocation support doesn't cost me extra. :) Although, I'm fairly confident in rust zero-cost promise.

**Comment by the8472** [comment]
That sounds like you need a fixed ring buffer, not a resizable deque. There are some on crates.io, even no-std ones.

**Comment by MOZGIII** [comment]
> That sounds like you need a fixed ring buffer, not a resizable deque. There are some on crates.io, even no-std ones.

You're right. And we're using proper ring buffers too, as a competing implementation. Our problem is that we must provide support for `std`'s `VecDeque` too.

**Comment by Mark-Simulacrum** [comment]
I am fairly certain that the use case of wanting very precise allocation patterns is just not really feasible to support with off-the-shelf solutions intended for general consumption -- if you want to internally "rely" on the behavior of VecDeque to allocate 2<sup>x</sup> - 1 then certainly that's possible via an extension trait that provides your `with_capacity_exact` method or something like it and checks internally. But I'm going to close this issue - I think it is out of scope for the standard library; we do not intend to guarantee allocation patterns in quantity or size and would not, today, want to do so I believe. In any case, it seems like if you're fine with an unstable method, the extension trait idea is even better, as it's both stable and in some sense "just as reliable."
