### ISSUE TITLE
Middle size, 80 000 lines, project but very slow, 5 hours, compilation  

### ISSUE THREAD

**Issue by cheblin** [rust-lang/rust#65131]
This code is the [MAVLink ](https://mavlink.io/en/) protocol handler, and generated by one of the MAVLink specification. It is  **C/Rust**  mixed project, so to compile it you will need  **Rust** ,  **CC**  an any  **C**  compiler.

To check how slow  **rustc**  is, [check this out ](https://github.com/cheblin/InRUST), and run  **cargo test**  in the  **GroundControl/demo**  dir

Exactly this project is compiled with error, cause the borrow checker complains in one place.

But anyway, the problem is that compilation is unacceptably slow.

**Description**

[/GroundControl/lib ](https://github.com/cheblin/InRUST/blob/master/GroundControl/lib/src/lib.rs)  **generated API**

[/GroundControl/demo/src/use_case](https://github.com/cheblin/InRUST/blob/master/GroundControl/demo/src/use_case.rs)  **is generated sample of using generated API**

[/GroundControl/demo/src/test](https://github.com/cheblin/InRUST/blob/master/GroundControl/demo/src/test.rs)  **the test**

I generate variation of this project, with same functionality, in C, C++, C#.... They are the compiled in seconds !

What wrong with my Rust project? How can I speed up compilation?

My PC

Intel I7-7700K

RAM 32G

SSD Samsung 970 PRO

**cargo -V**

cargo 1.39.0-nightly (ab6fa8908 2019-09-25)

**rustc -V**

rustc 1.40.0-nightly (22bc9e1d9 2019-09-30)

**Comment by jonas-schievink** [comment]
Please provide build instructions for that code. Running `cargo build` in `GroundControl/lib` gives:
`fatal error: ../config.h: No such file or directory`.

**Comment by cheblin** [comment]
Sorry But I wrote

> and run  **cargo test**  in the  **GroundControl/demo**  dir

**Comment by cheblin** [comment]
> GroundControl/lib gives: gives:.....

I wrote 

>and run  **cargo test**  in the  **GroundControl/demo**  dir

**Comment by jonas-schievink** [comment]
That gives the same error, since it just has a dependency on the crate in `lib`...

**Comment by cheblin** [comment]
Small bug fix  in the build.rs file. 
Please try again.
Thanks.

**Comment by jonas-schievink** [comment]
That didn't fix it

**Comment by cheblin** [comment]
on my debian and windows 10 build script shown:

cargo:warning=**Starting search config.h in....**
cargo:warning=/root/InRUST/GroundControl/demo/target/debug/build/black_box-sys-57f37c06735e9d12/out
cargo:warning=/root/InRUST/GroundControl/demo/target/debug/build/black_box-sys-57f37c06735e9d12
cargo:warning=/root/InRUST/GroundControl/demo/target/debug/build
cargo:warning=/root/InRUST/GroundControl/demo/target/debug
cargo:warning=/root/InRUST/GroundControl/demo/target
cargo:warning=/root/InRUST/GroundControl/demo
cargo:warning=<<< **Find and use generated config.h in root/InRUST/GroundControl/lib/src/** >>>

**Comment by cheblin** [comment]
made more platform specific fixes. 
check now please.

**Comment by tanriol** [comment]
I've looked into this code and likely found the problem.

The bright side: it compiles in under half a minute if the errors are removed.

The part of the code causing this problem is a test function that tries to test everything at once and has about 8000 lines. The function contains (as of commit ee653b1a0170) 76 borrow checker errors and the part that takes 5 hours is generating the 3-point errors for them. The time is dominated by the [repeated recalculation of dominators](https://github.com/rust-lang/rust/blob/421bd77f42c2fe8a2596dbcc1580ec97fb89009f/src/librustc_mir/borrow_check/nll/explain_borrow/mod.rs#L460) for the function body.

**Comment by tanriol** [comment]
A minimized reproduction looks like this
```rust
fn get_pair(_a: &mut u32, _b: &mut u32) {
}

macro_rules! x10 {
    ($($t:tt)*) => {
        $($t)* $($t)* $($t)* $($t)* $($t)*
        $($t)* $($t)* $($t)* $($t)* $($t)*
    }
}

#[allow(unused_assignments)]
fn main() {
    let mut x = 1;

    get_pair(&mut x, &mut x);

    x10!{ x10!{ x10!{ if x > 0 { x += 2 } else { x += 1 } } } }
}
```

On my laptop this code requires about 25 seconds to print the error for the 1000 `if` statements generated above and scales like the cube of the statement count.

**Comment by H2CO3** [comment]
On the bright side, waiting 5 hours for borrowck errors is still faster than trying to debug a memory corruption in a language without borrowck. 😜

**Comment by joshtriplett** [comment]
Thanks to @cheblin for the report and helping us to work with it, and to @tanriol for the quick analysis and fix!
