### ISSUE TITLE
rustfix: Autofix try! macro in edition lint to use `?` operator

### ISSUE THREAD

**Issue by lzutao** [rust-lang/rust#65148]
Now `try!` macro has been deprecated in #62672. I think it's time to automatically
fix `try!(expr)` to `expr?` in edition lint.

**Comment by jugglerchris** [comment]
I've got code with a load of `r#try` so this one's bugging me. :-)

I'm interested in working on it if no-one else is. I haven't worked on rustc so there'll be some learning for me to do first.

**Comment by Centril** [comment]
iirc we took a fairly explicit decision to migrate to `r#try!(...)` because migrating to `?` can break code. And we cannot be sure everyone has migrated to 2018. cc @rust-lang/lang

**Comment by lzutao** [comment]
But this is edition lint for anyone want to migrate from 2015 to 2018 edition.

**Comment by jugglerchris** [comment]
@Centril under what circumstances can `?` break code compared to `r#try!(...)`?

**Comment by Centril** [comment]
The lowering of `?` has `.into()` and uses type inference more as compared to `try!(...)`.

**Comment by nikomatsakis** [comment]
We discussed this in [our lang team meeting on 2019-10-17](https://github.com/rust-lang/lang-team/tree/master/minutes). We concluded that we would prefer not to try to create such a lint. In short, nothing has changed since the Edition handover: it is still hard to get this lint correct and it doesn't seem worth the effort to maintain it (and fix the inevitable bugs). We prefer the rustfmt "normalize `try!`" option. Hence, I'm going to close the issue for now. Thanks for the suggestion @lzutao.

**Comment by joshtriplett** [comment]
@nikomatsakis The one downside of using rustfmt for this: it's difficult to disable the *rest* of rustfmt, if you don't want to combine reformatting your code with substantive changes to your code. Would it be possible to add (and document) a method for converting `try!` to `?` without reformatting code?

**Comment by nikomatsakis** [comment]
@joshtriplett Personally, I think you should reformat the rest of your code first, and then enable the rustfmt option to convert `try!` to `?` (I don't believe it does that by default). Of course, I'm presuming that you *want* to reformat your code (which I think everyone should, though I realize others will disagree). But I think that the set of people who don't want to reformat their code is fairly small -- and the set than then *further* want to remove `r#try` smaller still. This all argues that supporting a lint in the compiler is pretty overkill.

That said, I think that there used to be some tool for converting `try!` to `?` that we used back when `?` was first introduced. Probably it could be dusted off and put to use again. I don't remember much about it though -- I want to say @japaric wrote it?
