### ISSUE TITLE
Implement std::iter::FromIterator<char> for Box<str>

### ISSUE THREAD

**Issue by Duddino** [rust-lang/rust#65163]
This would allow to construct a Box<str> from an iterator, example: ```let string: Box<str> = (0..5).map(|_| '☺').collect();```

This issue has been assigned to @Duddino via [this comment](https://github.com/rust-lang/rust/issues/65163#issuecomment-538747890).

**Comment by jonas-schievink** [comment]
Did you mean [`FromIterator`](https://doc.rust-lang.org/std/iter/trait.FromIterator.html)?

**Comment by Duddino** [comment]
Yes thank you

**Comment by bluss** [comment]
The workaround to use until then is `(0..5).map(|_| '☺').collect::<String>().into_boxed_str()` which will be equivalent to the eventual solution in behaviour and performance.

**Comment by Duddino** [comment]
I made the change, should I proceed with a PR? Sorry if it's a stupid question, but it's my first issue

**Comment by bluss** [comment]
@Duddino  I think you can. The equivalent thing for `Box<[T]>` was in #55843 and the process should be similar.

If you are curious, bigger changes in Rust might require an RFC -- see the [contributing file](https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md).

**Comment by Duddino** [comment]
@blussI Thank you!

**Comment by bluss** [comment]
PR is #65168

**Comment by andersk** [comment]
Presumably @dtolnay’s rejection of #70094 also constitutes a rejection of this bug.
