### ISSUE TITLE
rustc should open the output file as soon as it starts compiling

### ISSUE THREAD

**Issue by sethfowler** [rust-lang/rust#6518]
Consider the following sequence of actions:

- I run `make`, which runs `rustc`.
- I update a source file while `rustc` is compiling.
- `rustc` finishes compiling.

What I expect is that, if I run `make` again, the changes will get detected and `rustc` will be invoked again. What actually happens is that `make` reports that there's nothing to be done.

This is probably because `rustc` is waiting way too long to open the output file, so updates to source files while the compiler's running appear to "happen before" the output file from `make`'s point of view.

**Comment by reem** [comment]
Visiting for triage. This is still a problem, but it's never happened to me.

**Comment by pnkfelix** [comment]
> I wonder if we could have rustc record the "source-file-reading time" in the files it generates, and have it later check against that? Seems like you'd need to hack around 'make' though.

You can pass explicit timestamps to touch, at least the version on my machine.  So it seems like we could grab one timestamp at the outset of running make, and use that for all the stamps we generate.

**Comment by pnkfelix** [comment]
>  So it seems like we could grab one timestamp at the outset of running make, and use that for all the stamps we generate.

Or better still, grab a separate timestamp at each point that we invoke `rustc` and subsequently touch an associated stamp file.  This is probably the most robust approach.
