### ISSUE TITLE
Occasional spurious codegen test failures

### ISSUE THREAD

**Issue by nnethercote** [rust-lang/rust#65224]
Occasionally when running tests, I get these failures:
```
    [codegen] codegen/issue-45222.rs
    [codegen] codegen/issue-45466.rs
    [codegen] codegen/swap-small-types.rs
    [codegen] codegen/vec-iter-collect-len.rs
    [codegen] codegen/vec-optimizes-away.rs
```
My current workaround is to delete my `build` directory, recompile, and re-run the tests. @mati865 suggested that deleting `build/x86_64-unknown-linuxgnu/test` might be sufficient.

**Comment by Enselic** [comment]
Triage: Are you still seeing these spurious failures?

**Comment by nnethercote** [comment]
Haha, no. Thanks for asking :)
