### ISSUE TITLE
Don't rebuild everything on test-or-comment-only changes

### ISSUE THREAD

**Issue by cmr** [rust-lang/rust#6522]
The build system currently rebuilds everything for test-only changes, which is really painful. Ideally, it should get a diff (using git), and check if any of the changes are outside `#[test]` items before deciding that the build is stale.

**Comment by steveklabnik** [comment]
Triage: oh yes this is still so very painful.

**Comment by cmr** [comment]
This is basically foregone at this point.

**Comment by jhasse** [comment]
What does that mean?

(Sorry, no native speaker)

**Comment by Gankro** [comment]
Translation: this is unlikely to ever happen.

**Comment by cmr** [comment]
The current build system makes this pretty much impossible to do. We could technically do it, but it'd be more trouble than it's worth.
