### ISSUE TITLE
Don't cc rust-lang/compiler for toolstate changes

### ISSUE THREAD

**Issue by varkor** [rust-lang/rust#65238]
While it's important to keep on top of regressions to the toolstate, most of the time these issues are fixed quickly, by the author of the PR that caused the regression, or someone else. With GitHub notifications being difficult enough to keep up with as it is, being mentioned on every toolstate change issue is mostly noise. The issues are already tagged T-compiler and nominated, so I think additionally pinging everyone is unnecessary.

I think it would be sensible to change:
https://github.com/rust-lang/rust/blob/528379121ceb5fca5382b4337be7ac064890ec8c/src/tools/publish_toolstate.py#L146
to:
```
cc @{}, the PR reviewer, and nominating for compiler team prioritization.
```
cc @rust-lang/compiler

**Comment by michaelwoerister** [comment]
I think that's a good idea!

**Comment by nikomatsakis** [comment]
I agree that the pings are rarely useful. Nominating is probably sufficient.
