### ISSUE TITLE
Cleanup: Deduplicate implementations of `is_{freeze,copy,sized}_raw`

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#65259]
See: https://doc.rust-lang.org/nightly/nightly-rustc/src/rustc/ty/util.rs.html#1045

This issue has been assigned to @mbStavola via [this comment](https://github.com/rust-lang/rust/issues/65259#issuecomment-540370893).

**Comment by mbStavola** [comment]
I'm interested in taking this!
