### ISSUE TITLE
request: Make `unix::net::SocketAddr` create methods public

### ISSUE THREAD

**Issue by kleimkuhler** [rust-lang/rust#65275]
## Motivation

Recently [tokio-rs/mio](https://github.com/tokio-rs/mio/) needed support for creating the
`std::os::unix::net::SocketAddr` type. While the type is currently public, it is
not possible to create one as both creation methods are private:

* [SocketAddr::new](https://github.com/rust-lang/rust/blob/master/src/libstd/sys/unix/ext/net.rs#L109)
* [SocketAddr::from_parts](https://github.com/rust-lang/rust/blob/master/src/libstd/sys/unix/ext/net.rs#L120)

The workaround was creating a `mio` specific `SocketAddr` that is equivalent to
this type.

A use of needing `SocketAddr::from_parts` is shown [here](https://github.com/tokio-rs/mio/blob/master/src/sys/unix/uds/listener.rs#L101).

#65255 was a quick fix at trying to add this, but it will need `#[unstable]` attribute and therefore be tied to an issue I believe. I wanted to open some brief conversation on if this would be okay and I can add the things missing in that PR.

**Comment by kleimkuhler** [comment]
`T-Libs` label is probably the correct designation.

**Comment by lokalmatador** [comment]
Hi, first time contributor here. Is this still an open request? If so, may I work on it?

**Comment by Thomasdezeeuw** [comment]
I'll to revive this discussion. For Mio we currently have our own version of `unix::net::SocketAddr`, but we really like to move to the std's version before releasing v1 (https://github.com/tokio-rs/mio/issues/1527). We've already been through the process of incorrectly assuming the layout of the IP `SocketAddr` type, see https://github.com/tokio-rs/mio/issues/1386 and https://github.com/rust-lang/rust/pull/78802. We like to prevent repeat of that, but that would mean we need be able to create the type from outside std lib.

**Comment by m-ou-se** [comment]
Unfortunately, we can't just make those `new` and `from_parts` functions public, since they include types from `libc` in the interface, which is a private dependency of std. Some discussion starting here: https://github.com/rust-lang/rust/pull/65255#issuecomment-543169553

Would something like a `SocketAddr::from_path(&Path)` suffice? (Similar to `SocketAddr::from_abstract_namespace`.)

**Comment by Thomasdezeeuw** [comment]
> Unfortunately, we can't just make those `new` and `from_parts` functions public, since they include types from `libc` in the interface, which is a private dependency of std. Some discussion starting here: [#65255 (comment)](https://github.com/rust-lang/rust/pull/65255#issuecomment-543169553)

I understand we don't want to expose `libc` type.

> Would something like a `SocketAddr::from_path(&Path)` suffice? (Similar to `SocketAddr::from_abstract_namespace`.)

That would be a nice start. If we can also have `SocketAddr::from_ip(net::SocketAddr)` (maybe with IPv4/v6 methods as well). Then I think all we need is `AF_VSOCK`, but do that later.

Note that socket2 already has all these methods/`From` impls for its [`SocketAddr`](https://docs.rs/socket2/latest/socket2/struct.SockAddr.html) type.

**Comment by m-ou-se** [comment]
So you want to be able to use `unix::net::SocketAddr` also for IP socket addresses? Mio currently uses separate types for IP and Unix addresses, right?

**Comment by m-ou-se** [comment]
Adding `unix::net::SocketAddr::from_path` and `unix::net::SocketAddr::as_path` seems fine to me. Feel free send a PR for those. We could then kick off an FCP for stabilization together with https://github.com/rust-lang/rust/issues/85410 quickly afterwards.

Extending `unix::net::SocketAddr` for non-unix addresses might be reasonable, but would require a bit more discussion.

**Comment by Thomasdezeeuw** [comment]
> So you want to be able to use `unix::net::SocketAddr` also for IP socket addresses? Mio currently uses separate types for IP and Unix addresses, right?

Yes, but it would nice to easily convert from OS address storage to a Rust type address. But that can become future work.

> Adding `unix::net::SocketAddr::from_path` and `unix::net::SocketAddr::as_path` seems fine to me. Feel free send a PR for those. We could then kick off an FCP for stabilization together with #85410 quickly afterwards.

👍  Will send a pr. What do you think about `SocketAddr::unix` and `SocketAddr::as_unix` to match the `AF_UNIX` constant?

> Extending `unix::net::SocketAddr` for non-unix addresses might be reasonable, but would require a bit more discussion.

**Comment by m-ou-se** [comment]
> +1 Will send a pr. What do you think about `SocketAddr::unix` and `SocketAddr::as_unix` to match the `AF_UNIX` constant?

`from_abstract_namespace` and `as_abstract_namespace` also use `AF_UNIX`, so I don't think that'd be a good name.

**Comment by Thomasdezeeuw** [comment]
> `from_abstract_namespace` and `as_abstract_namespace` also use `AF_UNIX`, so I don't think that'd be a good name.

Should those be folder into `SocketAddr::unix` then? Because I copied the implementation from socket2, which supports abstract namespaces as well.

**Comment by Thomasdezeeuw** [comment]
Implementation pr: https://github.com/rust-lang/rust/pull/93239.

**Comment by Thomasdezeeuw** [comment]
Tracking issue for `std::os::unix::net::SocketAddr::from_path`: https://github.com/rust-lang/rust/issues/93423.

**Comment by Thomasdezeeuw** [comment]
I think this can be closed in favour of https://github.com/rust-lang/rust/issues/93423? Since the `unix_socket_creation` feature does exactly this.

**Comment by Thomasdezeeuw** [comment]
Since https://github.com/rust-lang/rust/issues/93423 is now stabilised (in 1.61) I think this can be closed.
