### ISSUE TITLE
E0599 error message may suggest syntactically invalid fix

### ISSUE THREAD

**Issue by Rantanen** [rust-lang/rust#65284]
[Full code in Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=3b1a6a68ae4db990762e4a542fbf052a)

Missing a trait bound for the trait that defines `fn foo` below:

```rust
fn do_stuff<T : Bar>(t : T) {  // Note the space before the colon in `T : Bar`
    t.foo()
}
```

Results in the following suggestion with an extra colon after the plus.

```
fn do_stuff<T: Foo +: Bar>(t : T) {
```

**Comment by estebank** [comment]
@varkor, you can look at https://github.com/rust-lang/rust/pull/65192/files#diff-0e12890ad498e250783f40f88a8b8ec6R978-R993 and https://github.com/rust-lang/rust/pull/65192/files#diff-0e12890ad498e250783f40f88a8b8ec6R1105-R1125 for inspiration on how to deal with this.

**Comment by varkor** [comment]
@estebank: I came up with a different solution, but there may be a subtlety I'm missing: https://github.com/rust-lang/rust/pull/65289.
