### ISSUE TITLE
"Consider adding an explicit lifetime bound" doesn't take into account existing bounds

### ISSUE THREAD

**Issue by varkor** [rust-lang/rust#65286]
```rust
trait X { fn foo(&self) {} }

fn p3<'a, 'b, T: 'b>(v: T) -> Box<dyn X + 'a> where T: X {
    Box::new(v)
}
```
produces:
```
error[E0309]: the parameter type `T` may not live long enough
 --> src/lib.rs:4:5
  |
3 | fn p3<'a, 'b, T: 'b>(v: T) -> Box<dyn X + 'a> where T: X {
  |               -- help: consider adding an explicit lifetime bound `T: 'a`...
4 |     Box::new(v)
  |     ^^^^^^^^^^^
  |
```
It should suggest `T: 'a + 'b` (or similar), ideally in the same format as E0599.

**Comment by varkor** [comment]
Note that this problem is already present in the test suite:
https://github.com/rust-lang/rust/blob/58b54911fabcd1b328fab78014b6833a4e8cfaa3/src/test/ui/lifetimes/lifetime-doesnt-live-long-enough.stderr#L82-L84

**Comment by estebank** [comment]
We already supply a structured suggestion in this case that can be applied with VSCode. We don't display the whole suggested code to reduce duplication in the text and to fit the intended flow of the text "add lifetime bound..."/"...so that". Changing it should be easy to do, but do we want to?
