### ISSUE TITLE
`rustc_data_structures::static_assert!(false)` does not error

### ISSUE THREAD

**Issue by memoryruins** [rust-lang/rust#65300]
`1.40.0-nightly 2019-10-09 20cc75272619cc452e3a`

 The following does not error locally / on the playground https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=9dde03338a31e2f40491a66dc3a18761

```rust
#![feature(rustc_private)]

extern crate rustc_data_structures;
use rustc_data_structures::static_assert;

fn main() {
    // doesn't error, but should
    static_assert!(2 + 2 == 5);

    // correctly errors when uncommented
    // const _: () = [()][!(2 + 2 == 5) as usize];

    // https://doc.rust-lang.org/nightly/nightly-rustc/src/rustc_data_structures/macros.rs.html#4-11
}
```

If I copy paste the macro into the same file, it errors as expected https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=bec79345cfe7cecf1b92eed6c2736152

```
error: any use of this value will cause an error
  --> src/main.rs:11:23
   |
11 |         const _: () = [()][!($test: bool) as usize];
   |         --------------^^^^^^^^^^^^^^^^^^^^^^^^^^^^^-
   |                       |
   |                       index out of bounds: the len is 1 but the index is 1
...
16 |     static_assert!(2 + 2 == 5);
   |     --------------------------- in this macro invocation
   |
   = note: `#[deny(const_err)]` on by default

```

Checking other macros, [`rustc_data_structures::static_assert_size`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_data_structures/macro.static_assert_size.html) (which is defined next to `static_assert`) and [`static_assertions::const_assert`](https://docs.rs/static_assertions/1.0.0/static_assertions/macro.const_assert.html) error as expected.

**Comment by rodrimati1992** [comment]
This feels like it's related to a [similar issue](https://github.com/rust-lang/rust/issues/61058) I created a while back.

**Comment by oli-obk** [comment]
This is probably because the "error" is just a lint. And we appear to silence it in external macros. We shouldn't do that. IIRC this is just a flag that needs to be set for the `CONST_ERR` lint macro

**Comment by Mark-Simulacrum** [comment]
Yes, we need to set report_in_external_macro param on the lint I believe

**Comment by memoryruins** [comment]
Ah, that makes sense! Building locally with the parameter set to confirm.
@rodrimati1992 it does ^^ will check the samples in there too.
