### ISSUE TITLE
Error E0594 is not described in docs

### ISSUE THREAD

**Issue by DustinByfuglien** [rust-lang/rust#65326]
Error E0594 is not described in docs
https://doc.rust-lang.org/nightly/error-index.html#E0594

```rust

fn main() {
    let v = vec![1u16; 10];
    let p: &[u16] = &v;
    p[0] = 3;
}

```

([Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=9aefb4be4f1073282116596617df32a0))

Errors:

```
   Compiling playground v0.0.1 (/playground)
error[E0594]: cannot assign to `p[_]` which is behind a `&` reference
 --> src/main.rs:5:5
  |
4 |     let p: &[u16] = &v;
  |                     -- help: consider changing this to be a mutable reference: `&mut v`
5 |     p[0] = 3;
  |     ^^^^^^^^ `p` is a `&` reference, so the data it refers to cannot be written

error: aborting due to previous error

error: could not compile `playground`.

To learn more, run the command again with --verbose.

```

**Comment by JohnTitor** [comment]
Many error codes have not long explanations, not only E0594, see the issue #61137. You can add a long explanation to the error code by opening a PR.

**Comment by DustinByfuglien** [comment]
Sorry. May be you don't understand due to my poor English.
Rust have a doc's index file at https://doc.rust-lang.org/nightly/error-index.html
It describes every error code. Errors E0593 and E0595 are described. But E0594 is absent at all.

**Comment by JohnTitor** [comment]
Yes, I understand.
As far as I remember, the explanations (and error codes) in that doc are shown by adding long explanations.
E0593 and E0595 are added already, but E0594 isn't.

e.g. E0595:
https://github.com/rust-lang/rust/blob/4b42e919d640f7c714a7e87c91b4f3a9089552d0/src/librustc_mir/error_codes.rs#L2104-L2122

**Comment by DustinByfuglien** [comment]
Thanks a lot for explanation.
So I think issue can be closed.
