### ISSUE TITLE
Tracking issue for "minimize the rust-std component"

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#65343]
This tracks the issue for doing the stuff mentioned in https://github.com/rust-lang/rust/pull/64823.

Also relevant:

- https://github.com/rust-lang/rust/issues/61978
- https://github.com/rust-lang/rust/issues/62486
- https://github.com/rust-lang/rust/issues/65335
- https://github.com/rust-lang/rust/pull/65337
- https://discordapp.com/channels/442252698964721669/443148290352218115/632573542218858527

**Comment by Mark-Simulacrum** [comment]
This has essentially be done and should be in stable this or next cycle (I forget, to be honest).
