### ISSUE TITLE
Compiling can take hours.

### ISSUE THREAD

**Issue by darkoverlordofdata** [rust-lang/rust#65350]
I've heard that rustc is slow, but I'm actually running into 30 to 120 minute compile times. I only installed rustc yeasterday: rustc 1.38.0 (625451e37 2019-09-23) on Debian Buster. I've tried cloning a couple of game engines from github to compare - Piston, gglz, glium plus a random opengl demo program (github.com/bwasty/learn-opengl-rs).

It is taking forever to compile the example code - learn-opengl-rs took about 20 minutes. Piston can literally run all day and not finish. Gglz took about 2 hrs to compile and run 1 example: cargo run --example 02_hello_world.  Other examples take equally long.

If I change the "Hello World" text in the example and recompile, it again takes hours. 
I run htop, and I cen see that the problem is that all 4 cores are pegged at 100%. It also activates the fan and my computer heats up.

Once the app runs, it stays at 60% per all 4 cores. I am also unable to close or open any windows. I have to ctrl-c and reboot to get back to normal.

I have a Dell Inspiron 15 3521 - it only has a 7th gen i3 4 core, so I don't expect a lot, but I am able to use Android Studio, so its not that slow.

**Comment by jonas-schievink** [comment]
Are you hitting swap during compilation?

**Comment by jonas-schievink** [comment]
> Once the app runs, it stays at 60% per all 4 cores. I am also unable to close or open any windows. I have to ctrl-c and reboot to get back to normal.

This isn't Rusts fault, but it does sound very untypical. Perhaps investigate what's causing this and report an issue upstream? It might also be an issue with your system.

**Comment by nagisa** [comment]
I have no trouble whatsoever compiling stuff on a 4th gen Intel mobile part. 30-120 mins sound so unreasonable that it would point at some hardware or system configuration issue. Could you please try to reproduce this on another machine?

**Comment by wesleywiser** [comment]
According to Dell, the Inspiron 3521 has [between 2-8gb of RAM stock](https://www.dell.com/us/dfh/p/inspiron-15-3521/pd). As @jonas-schievink mentioned, you're probably hitting swap which will significantly hurt compile times. You might try limiting the amount of parallel `rustc` processes which should use less memory by passing the `-j` option to cargo. For example, `cargo build -j 1`.

**Comment by estebank** [comment]
It could be worthwhile to have a message appear the first time `rustc` is invoked or if the compilation process is taking >10 minutes in a machine with low RAM.

**Comment by darkoverlordofdata** [comment]
@wesleywiser  This is the answer, thank you. I set max jobs set to 3, and it takes what I expect - about similar time as clang. I wonder if this is because I'm running debian on crostini. I've never seen any impact from that but maybe there is a race condition from competing with other kvm scheduling.

**Comment by mati865** [comment]
> I wonder if this is because I'm running debian on crostini. I've never seen any impact from that but maybe there is a race condition from competing with other kvm scheduling.

You should rather check how much memory is allocated to Debian because it seems it's not enough and you start swapping.
