### ISSUE TITLE
missing `fn` before `main()` -- error could be improved

### ISSUE THREAD

**Issue by ultrasaurus** [rust-lang/rust#65381]
As a newcomer to Rust, sometimes I forget `fn` before `main()` and the error message doesn't make sense in this instance:

Example file:

```rs
main() {
}
```

Error message
```
error: expected one of `!` or `::`, found `(`
 --> examples/tuple.rs:1:5
  |
1 | main() {
  |     ^ expected one of `!` or `::` here
```

suggested change:

"^ expected prior `fn` for a function declaration or suffix `!` for a macro"

I'm not familiar with a case where `::` would make sense here without other changes too.

**Comment by Centril** [comment]
cc @estebank @petrochenkov -- While this would be good to fix, it is probably difficult and I suspect it requires some thought to avoid erroring on e.g. `main();` (a function call -- consider function defs as "statements"). Also, I would like to merge the function grammars (free, foreign, trait, impl) before adding a diagnostic here to ensure that they can still be merged.

**Comment by estebank** [comment]
Note that [we already do this for trait items](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=b8eb34e1b7e67430b73516dd03a7f37c). In those cases we already do some bounded lookahead to look for `{` or `;` to make sure the suggestion is correct. In this case it would only look for `{`.

**Comment by MatsPalmgren** [comment]
Fwiw, I made this typo today:
```
268 |     pub const initial_value() -> Self {
    |                            ^ expected `:`
```

A better error message would be:
```
268 |     pub const initial_value() -> Self {
    |              ^ did you forget `fn` ?
```

**Comment by eduardocanellas** [comment]
I don't know if it fits here, but it would be good to improve the error messages for users using `function`, `func`, `fun` etc too. The message which appears for this kind of mistake is the same as the error message on this issue. IMO the current message may look very confusing for beginners and even for more experienced folks.

Example: 

```rust
fun main() {}
```

```
error: expected one of `!` or `::`, found `main`
 --> src/lib.rs:1:5
  |
1 | fun main() {}
  |     ^^^^ expected one of `!` or `::`

error: aborting due to previous error

error: could not compile `playground`

To learn more, run the command again with --verbose.
```

**Comment by estebank** [comment]
For the bare C-style `main() {}`, we still don't handle it, but for `fun main() {}` we do:

```
error: expected one of `!` or `::`, found `main`
 --> src/lib.rs:1:5
  |
1 | fun main() {}
  | --- ^^^^ expected one of `!` or `::`
  | |
  | help: write `fn` instead of `fun` to declare a function
```
