### ISSUE TITLE
impl-trait type alias is usable in impl blocks

### ISSUE THREAD

**Issue by DutchGhost** [rust-lang/rust#65384]
As requested in https://github.com/rust-lang/rust/issues/53345#issuecomment-541434579, here's a follow up.

The following code below implements the trait `MyTrait` for an alias `Bar`, which is an alias to `MyTrait`. It doesnt really make sense to implement a trait...for that same trait.

[type_alias_impl_trait](https://github.com/rust-lang/rfcs/blob/master/text/2515-type_alias_impl_trait.md) doesn't mention anything about this, however the previous [existential_type](https://github.com/rust-lang/rfcs/blob/master/text/2071-impl-trait-existential-types.md) notes: 

> One last difference between existential type aliases and normal type aliases is that existential type aliases cannot be used in impl blocks

```Rust
#![feature(type_alias_impl_trait)]

trait MyTrait {}

impl MyTrait for () {}

type Bar = impl MyTrait;

impl MyTrait for Bar {}

fn bazr() -> Bar { }

fn main() {}
```
Im not sure this should be allowed.

cc @Aaron1011 @nikomatsakis @Centril

**Comment by jackh726** [comment]
This is fixed on master.
