### ISSUE TITLE
Error for incorrect identifier patterns could be improved

### ISSUE THREAD

**Issue by lzutao** [rust-lang/rust#65400]
The compiler could suggest that `e` identifier must precede the pattern in the following code:

playpen link: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=ca2dc7094a56b0478edefe0faefefe0e

```rust
fn main() {
    let x = 2;

    match x {
        1 ..= 5 @ e => {}
        _ => {}
    }
}
```

Current error message:
```rust
error: expected one of `=>`, `if`, or `|`, found `@`
 --> src/main.rs:5:17
  |
5 |         1 ..= 5 @ e => {}
  |                 ^ expected one of `=>`, `if`, or `|` here

error: aborting due to previous error
```

It could be improved as:
```rust
error: expected one of `=>`, `if`, or `|`, found `@`
 --> src/main.rs:5:17
  |
5 |         1 ..= 5 @ e => {}
  |                 ^ expected one of `=>`, `if`, or `|` here
                    | help: try `e @ 1 ..= 5`


error: aborting due to previous error
```

**Comment by Centril** [comment]
So what happens after `1 ..= 5` is that we've parsed a `PatKind::Range` and then `@` follows which is not a valid token after a parsed `$pat`. To fix this we can, after having parsed `let pat = ...;` in `parse_pat_with_range_pat`, check if `@` follows and then emit appropriate suggestions. We will need to use some heuristics to figure out what the user wants based on the structure of `pat: PatKind`. Some of the suggestions would be `MachineApplicable` and some not.

cc @estebank
