### ISSUE TITLE
Suggest as_mut to reborrow Pin when calling method

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/rust#65409]
I have seen a lot of newcomers to futures stumble with `Pin<&mut Self>` methods consuming the pin, if possible this seems like a good candidate for a custom diagnostic.

As a self-contained example ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=8cc1535cae505280361d46f504896ee9)):

```rust
use std::pin::Pin;

struct Foo;

impl Foo {
    fn foo(self: Pin<&mut Self>) {}
}

fn main() {
    let mut foo = Foo;
    let foo = Pin::new(&mut foo);
    foo.foo();
    foo.foo();
}
```

currently errors with

```
   Compiling playground v0.0.1 (/playground)
error[E0382]: use of moved value: `foo`
  --> src/main.rs:13:5
   |
11 |     let foo = Pin::new(&mut foo);
   |         --- move occurs because `foo` has type `std::pin::Pin<&mut Foo>`, which does not implement the `Copy` trait
12 |     foo.foo();
   |     --- value moved here
13 |     foo.foo();
   |     ^^^ value used here after move

error: aborting due to previous error

For more information about this error, try `rustc --explain E0382`.
error: Could not compile `playground`.

To learn more, run the command again with --verbose.
```

it would be useful if this error included something like

```
hint: use `foo.as_mut().foo()` to reborrow the `Pin` instead of moving it
```

**Comment by Centril** [comment]
cc @nikomatsakis @matthewjasper @estebank

**Comment by nikomatsakis** [comment]
Seems reasonable to me. Should we tag this A-async-await? Seems to fall under the "async foundations" purview, anyway. (Slight mismatch between those labels, I guess)

**Comment by Centril** [comment]
@nikomatsakis Yes, let's. Any thoughts re. implementation? ;)

**Comment by gilescope** [comment]
Happy to give this one a go - the hint would certainly help me if I stumbled into this.
@rustbot claim

**Comment by gilescope** [comment]
Rather than being specific to Pin, can we expand the scope and add a hint to the general error message:
```
      hint: Maybe [mutably] borrow '&[mut ]foo' [or foo.clone()] here?
                                                    ^ only suggest if T:Clone
```
and if possible specialise the error message if the type supports as_ref()/as_mut()?

As a user, that's the kind of error message I'd be greatful to receive

**Comment by Nemo157** [comment]
For normal `&self`/`&mut self` methods the compiler will implicitly reborrow. If there’s a generalisation here that could help suggest cloning that sounds good to me ([small playground to check the current error message](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=024e230bcc75414041c8af0cab09afc8)).

**Comment by estebank** [comment]
Addressed the `Pin<&mut T>` case in https://github.com/rust-lang/rust/pull/106095.

For the general case of suggesting `.clone()` can't be accomplished at this time because by the time borrowck comes around I can no longer use the inference context to evaluate `T: Clone` for an accurate suggestion.
