### ISSUE TITLE
add mlongcall flag to rustc

### ISSUE THREAD

**Issue by TomE8** [rust-lang/rust#65403]
Please see this StackOverflow [question](https://stackoverflow.com/questions/58356600/how-to-use-a-gcc-flag-in-rustc).

**Comment by jonas-schievink** [comment]
Rust is not GCC, so it doesn't have the same command line interface. Please be more specific as to what specific feature you need.

**Comment by TomE8** [comment]
I need my functions calls to be long-call on a power-pc arch. As in the man page of gcc -mlongcall:

> By default assume that all calls are far away so that a longer and more expensive calling sequence is required.  This is required for
>            calls farther than 32 megabytes (33,554,432 bytes) from the current location.  A short call is generated if the compiler knows the
>            call cannot be that far away.  This setting can be overridden by the "shortcall" function attribute, or by "#pragma longcall(0)".

Hope that clears the question :)

**Comment by jonas-schievink** [comment]
This is already supported as `-Ctarget-features=+longcall`

**Comment by TomE8** [comment]
Thanks. Can you mention your source or direct me to the source code?
