### ISSUE TITLE
Associated function `new` is not defined for any hasher on `HashMap`

### ISSUE THREAD

**Issue by Alphare** [rust-lang/rust#65404]
`HashMap` with a custom hasher does not implement `new()`. Example, with the following type alias:

```rust
type FastHashMap<K, V> = HashMap<K, V, MyFastHasher>;

let h = HashMap::new();  // Works
let f = FastHashMap::new();  // No associated function, etc.
```

Is there a good reason why that should happen? I've resorted to using `default()` since it does the same thing AFAIK, but this seems like an unnecessary restriction.

**Comment by sfackler** [comment]
This is intentional, because associated type defaults don't factor into type inference: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=94783a2a4108c8f70df5fc047bba2edf
