### ISSUE TITLE
Attempting to run an async fn after completion mentions generators

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/rust#65419]
If a user attempts to do something like this ([playground including trivial executor](https://play.rust-lang.org/?version=beta&mode=release&edition=2018&gist=45e22343cc25e9d0eca65a22331ed177)):

```rust
async fn foo() {
}

fn main() {
    let mut future = Box::pin(foo());
    executor::block_on(future.as_mut());
    executor::block_on(future.as_mut());
}
```

they get a panic talking about generators:

```
thread 'main' panicked at 'generator resumed after completion', src/main.rs:1:16
```

This issue has been assigned to @ninjasource via [this comment](https://github.com/rust-lang/rust/issues/65419#issuecomment-545113587).

**Comment by nikomatsakis** [comment]
Hey @Zoxc -- where does this error come from, anyway? A quick ripgrep of the source didn't find an obvious source.

**Comment by Centril** [comment]
Has to be https://doc.rust-lang.org/nightly/nightly-rustc/rustc/mir/interpret/enum.PanicInfo.html#method.description.

**Comment by Zoxc** [comment]
Yeah that's it.

**Comment by nikomatsakis** [comment]
OK, yes, that's what I meant. So to fix this we presumably want to:

* Add a new `PanicInfo` variant with a different description
* Use that `PanicInfo` variant for generators that arose from `async fn`

We would need to get access to the [`generator_kind`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc/hir/struct.Body.html#method.generator_kind) for this generator in this function here;

https://github.com/rust-lang/rust/blob/437ca55f23b7ed0051334a7e38ecabd83a173b53/src/librustc_mir/transform/generator.rs#L989-L995

Right now, I don't think that is stored in the MIR, but we could easily do do (I'd rather not retrieve it from the HIR).

**Comment by ninjasource** [comment]
Hi @nikomatsakis, that makes sense. I'll lean on @gilescope for initial guidance on this and I'll add more comments after I dig a little deeper. Cheers, David

**Comment by gilescope** [comment]
@tmandry we can close this one - @ninjasource has fixed this.
