### ISSUE TITLE
Statically link against glibc

### ISSUE THREAD

**Issue by NilsIrl** [rust-lang/rust#65447]
Reasons for:

1. Performance. According to [this reddit message](https://www.reddit.com/r/rust/comments/a6pna3/why_rust_uses_glibc_and_not_musl_by_default_for/ebzpzld/), musl caused a program to run 9x slower. Musl is also known to be slower in certain configurations in C. This varies a lot with the use case and some might even see a performance increase with musl.
2. Smaller docker containers using `FROM scratch`. [example using musl](https://github.com/vbrandl/yagcdn/blob/master/Dockerfile)

It is possible to link glibc statically as demonstrated [here](https://users.rust-lang.org/t/statically-link-executable-with-glibc/32648/4).

From what I can tell, on the user facing side, this would be enable using `-C target-feature=+crt-static` as described in [the reference](https://doc.rust-lang.org/reference/linkage.html).

**Comment by the8472** [comment]
The reddit thread mentions libm. And another source of speedups might be the malloc implementation (glibc 2.26 introduced thread-local caches). One can already use custom global allocators, maybe it would make sense to link a custom libm too?

**Comment by mati865** [comment]
First blocker is the license. Glibc is licensed under LGPL, it has dynamic linking exception so one can freely link dynamically to it. Static linking doesn't fall under this exception. I'm not a lawyer but I think Rust would have to be licensed as (L)GPL to fit it.

Another thing is glibc doesn't really support static linking, sure it works well for small software but bites you when you need more of it's features.

**Comment by NilsIrl** [comment]
> First blocker is the license. Glibc is licensed under LGPL, it has dynamic linking exception so one can freely link dynamically to it. Static linking doesn't fall under this exception. I'm not a lawyer but I think Rust would have to be licensed as (L)GPL to fit it.

(Obviously not a lawyer but), I'm pretty sure that as long as the code it is linked against is GPLed, it should work.

**Comment by NilsIrl** [comment]
https://www.gnu.org/licenses/gpl-faq.html#LGPLStaticVsDynamic

Should be fine

**Comment by haraldh** [comment]
https://stackoverflow.com/questions/35116327/when-g-static-link-pthread-cause-segmentation-fault-why

**Comment by joshtriplett** [comment]
@haraldh The former should be doable. The latter is a tradeoff that people will need to understand if they statically link glibc, and it's something they already have to deal with if they use `gcc -static`.

**Comment by petrochenkov** [comment]
Implementation instructions:
- Add an entry for glibc-based targets you want to support to https://github.com/rust-lang/libc/blob/master/src/unix/mod.rs#L295-L357
    ```rust
        #[cfg_attr(feature = "rustc-dep-of-std",
                   link(name = "c", kind = "static-nobundle",
                        cfg(target_feature = "crt-static")))]
        #[cfg_attr(feature = "rustc-dep-of-std",
                   link(name = "c", cfg(not(target_feature = "crt-static"))))]
        extern {}
    ```
    (Same as for musl, but `"static"` -> `"static-nobundle"`, because `"static"` is undesirable (https://github.com/rust-lang/rust/issues/72274).)
    Perhaps libm or libpthread will need to be linked in the same way.
- Set `crt_static_respected` to `true` in target specifications for glibc-based targets you want to support (in `compiler\rustc_target\src\spec`).
- Test that it actually works, this will require some building of libstd with cargo overridden libc dependency.

**Comment by petrochenkov** [comment]
@joshtriplett 
>I'd be happy to submit the necessary changes, if you can outline what needs doing. (https://github.com/rust-lang/rust/issues/72274#issuecomment-687679312)

See the comment above.

**Comment by joshtriplett** [comment]
@petrochenkov Thanks!

**Comment by joshtriplett** [comment]
I have this successfully working; just waiting on a release of the libc crate containing https://github.com/rust-lang/libc/pull/1899 .
