### ISSUE TITLE
Cleanup: Move src/test/run-fail to src/test/ui

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#65440]
We have a small amount of tests in `src/test/run-fail`; these should be moved over to various directories in `src/test/ui` depending on what the test is about. (See https://github.com/rust-lang/rust/pull/65438#issuecomment-542245950 for one example of moving run-fail/ tests to ui/.) When moving each test in `src/test/run-fail` you have to add `// run-fail` to the top of each file.

cc @varkor 

This issue has been assigned to @nvlbg via [this comment](https://github.com/rust-lang/rust/issues/65440#issuecomment-542319420).

**Comment by nvlbg** [comment]
I'd like to work on this. First time contributor so it make take me some time to finish it.

**Comment by estebank** [comment]
Note that some of those tests are still there due to non-determinism in the output across multiple platforms. Those should be restricted to run on only one platform to be able to do this move.

**Comment by varkor** [comment]
> Those should be restricted to run on only one platform to be able to do this move.

We should make sure to cross reference these with issues too.

**Comment by nvlbg** [comment]
@estebank are these tests marked somehow? Also how are tests restricted to a single platform?

**Comment by estebank** [comment]
I believe those in particular aren't the ones u was thinking about, but they are marked with ignore- tags. I think they might be either ignore-x86 or ignore-musl, something along those lines.

**Comment by Centril** [comment]
Generally speaking, a trial and error approach should work here... work through the tests a few at a time and see what will go through CI.

**Comment by JesterOrNot** [comment]
I would like to help with this
