### ISSUE TITLE
abstracting over borrowed/owned IntoIterator in generic function isn't representatble

### ISSUE THREAD

**Issue by m4b** [rust-lang/rust#65458]
I don't know what to call this issue; I'm sure someone knows what this could be related to, if it's known, whether there's a solution, etc. Anyway, just posting here though:

Whlie attempting to abstract over a borrow/owned iterator to make a refactor easier, and to benchmark the separate implementations, I effectively stumbled onto this issue where I cannot seem to find a possible way to write the `shape` function that abstracts over whether the iterator returns borrowed elements or not _and_ which both mutates, and iterates immutably, _then_ mutates again. Here is the playground which currently compiles: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=f3d3ae669f256a8c4b73d60a67129132

but uncommenting the final pop makes it uncompilable, and I cannot find any sequence of lifetimes (with or without `for<'a>`) that make it work.

```rust
use std::borrow::Borrow;

pub trait Shape {
    fn pop(&mut self) -> Option<u32>;
}

pub struct Foo {
    data: Vec<u32>
}

impl Shape for Foo {
    fn pop(&mut self) -> Option<u32> {
        self.data.pop()
    }
}

impl<'a> IntoIterator for &'a Foo {
    type IntoIter = std::slice::Iter<'a, u32>;
    type Item = &'a u32;
    fn into_iter(self) -> Self::IntoIter {
        self.data.iter()
    }
}

pub struct Bar {
    data: Vec<u32>
}

impl Shape for Bar {
    fn pop(&mut self) -> Option<u32> {
        self.data.pop()
    }
}

impl<'a> IntoIterator for &'a Bar {
    type IntoIter = std::iter::Cloned<std::slice::Iter<'a, u32>>;
    type Item = u32;
    fn into_iter(self) -> Self::IntoIter {
        self.data.iter().cloned()
    }
}

fn shape<'b, S: 'b, L>( shape: &'b mut S ) -> bool 
where
    S: Shape,
    L: std::fmt::Debug + Borrow<u32>,
	&'b S: IntoIterator<Item = L>,
{
  let x = shape.pop();
  {
    for l in shape.into_iter()
    {
      let l = l.borrow();
      println!("{:?}", l);
    }
  }
  // if this is uncommented, cannot find any combination of lifetimes that work
  //let y = shape.pop();
  true
}

fn main(){
    let mut foo = Foo { data: vec![12, 13] };
    let mut bar = Bar { data: vec![0, 1, 12, 13] };
    shape(&mut foo);
    shape(&mut bar);
}
```

Frustratingly, removing the Borrow bound, and tying a `for<'a>` lifetime to the IntoIterator's items (thus forcing the iterator to be a borrow it's elements) allows it to compile: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=0aca666c579c94cdb07dc3c4a27d8f3a

```rust
use std::borrow::Borrow;

pub trait Shape {
    fn size(&mut self) -> f64;
}

pub struct Foo {
    data: Vec<u32>
}

impl Shape for Foo {
    fn size(&mut self) -> f64 {
        23.0
    }
}

impl<'a> IntoIterator for &'a Foo {
    type IntoIter = std::slice::Iter<'a, u32>;
    type Item = &'a u32;
    fn into_iter(self) -> Self::IntoIter {
        self.data.iter()
    }
}

fn shape<S: Shape, >(
        shape: &mut S,
    ) -> bool 
	where for<'a> &'a S: IntoIterator<Item = &'a u32>,
{
  let size = shape.size(); // shape method
  for l in shape.into_iter() {
    let l = l.borrow();
    println!("{:?}", l);
  }
  let size = shape.size();
  true
}

fn main(){
    let mut foo = Foo { data: vec![12, 13] };
    shape(&mut foo);
}
```

**Comment by jonas-schievink** [comment]
I think it would be more useful to discuss this on the [user forum](https://users.rust-lang.org/), or, if this needs new language features to be solved, in the [RFCs repo](https://github.com/rust-lang/rfcs), so closing in favor of that.
