### ISSUE TITLE
FnMut inside Pin complains about DerefMut not implemented

### ISSUE THREAD

**Issue by roblabla** [rust-lang/rust#65489]
When calling an `FnMut()` from inside a `Pin`, Rust complains that DerefMut is not implemented:

```rust
struct MyFuture<F> {
    f: F,
}

impl<F, T> core::future::Future for MyFuture<F>
where
    F: FnMut() -> Option<T> + Unpin,
{
    type Output = T;
    fn poll(mut self: core::pin::Pin<&mut Self>, cx: &mut core::task::Context) -> core::task::Poll<T> {
        (self.f)();
        core::task::Poll::Pending
    }
}
```

This seemingly equivalent piece of code works properly with no errors: 

```rust
struct MyFuture<F> {
    f: F,
}

impl<F, T> core::future::Future for MyFuture<F>
where
    F: FnMut() -> Option<T> + Unpin,
{
    type Output = T;
    fn poll(mut self: core::pin::Pin<&mut Self>, cx: &mut core::task::Context) -> core::task::Poll<T> {
        let x = &mut *self; // Work around weird bug.
        (x.f)();
        core::task::Poll::Pending
    }
}
```

**Comment by Mark-Simulacrum** [comment]
`(&mut self.f)();` works too. Seems like probably we're not looking at DerefMut sufficiently or with the wrong ParamEnv perhaps?

**Comment by roblabla** [comment]
Spent a couple minutes writing a more self-contained reproducer: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=70745ec56da08ff7a8aeee8fbead6488

**Comment by paulkernfeld** [comment]
I just pasted the first snippet into the Rust Playground with Rust 1.46 and it compiles, so maybe this issue is now fixed?

**Comment by roblabla** [comment]
Indeed, this seems to be fixed.
