### ISSUE TITLE
Allow trait methods to return `impl Trait` types.

### ISSUE THREAD

**Issue by kevincox** [rust-lang/rust#65481]
It should be possible for methods in traits to have a return value specified as `impl Trait`. This would allow traits to return values without having to specify the exact type or wrap in indirection.

This would obviously not be object-safe as the size of the return value would not be known.

**Comment by jonas-schievink** [comment]
Please refer to https://github.com/rust-lang/rfcs/blob/master/text/1522-conservative-impl-trait.md#limitation-to-freeinherent-functions for why this isn't allowed. Doing this requires substantial language design efforts and an RFC, so closing in favor of that.
