### ISSUE TITLE
The ASM compiler identification is unknown

### ISSUE THREAD

**Issue by aristarh2704** [rust-lang/rust#65488]
While building LLVM for target system, cmake prints:

> -- The ASM compiler identification is unknown
 But when I run cmake configure command by hand, it's work normally.
Target: armv7-linux-androideabi.

**Comment by jonas-schievink** [comment]
Please provide more information. What's your build platform and your `config.toml`? Are you using a custom LLVM or the one shipped with Rust?

**Comment by aristarh2704** [comment]
Host is x86_64-unknown-linux-gnu, target is armv7-linux-androideabi. But the problem itself is gone, I don't know why. I try using LLVM shipped with rust.

**Comment by jonas-schievink** [comment]
Okay, if it doesn't occur anymore then I'll close this. If you (or anyone else) finds a way to reproduce this, please let me know and I'll reopen.
