### ISSUE TITLE
Tracking issue for bindings in sub-patterns after `@`s (`feature(bindings_after_at)`)

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#65490]
This is the tracking issue for `#![feature(bindings_after_at)]`, which allows patterns of form `binding @ pat` to have bindings in `pat`, for example `ref x @ Some(y)`.

## Implementation history

- On 2019-12-24, https://github.com/rust-lang/rust/pull/66296, containing the initial implementation, landed. The PR was written by @Centril and reviewed by @pnkfelix and @matthewjasper.

- On 2020-02-10, https://github.com/rust-lang/rust/pull/68992 landed. The PR was written by @matthewjasper and reviewed by @Centril. The PR fixed a parser recovery bug wherein `mut x @ y` would make `y` a mutable binding, manifesting as issues https://github.com/rust-lang/rust/issues/67861 and https://github.com/rust-lang/rust/issues/67926.

- On 2020-02-19, https://github.com/rust-lang/rust/pull/69236 landed. The PR was written by @Centril and reviewed by @estebank. The PR adjusted the parser changes in https://github.com/rust-lang/rust/pull/68992 to retain good error messages on e.g. `mut (x @ y)` patterns, suggesting `mut x @ mut y` as opposed to `mut x @ y`.

- On 2020-03-08, https://github.com/rust-lang/rust/pull/69690 landed. The PR was written by @thekuom and reviewed by @Centril and added run-pass tests for the combination of bindings-after-at, or-patterns, box-patterns, slice-patterns.

- On 2020-03-08, https://github.com/rust-lang/rust/pull/69810 landed. The PR was written by @thekuom and reviewed by @Centril and added dynamic-rop run-pass tests for bindings-after-at.

- On 2020-03-10, https://github.com/rust-lang/rust/pull/69817, written by @thekuom and reviewed by @Centril, landed. The PR added borrow checker tests in combination with or-patterns & other pattern features.

- On 2020-03-26, https://github.com/rust-lang/rust/pull/70389, written by @Centril and reviewed by @mark-i-m, landed. The PR fixed some bugs in diagnostics where we would end up using `_` as the name of the place when matching on a temporary. Now it says *"value"* in the diagnostic instead.

## Old description

Pre-1.0 Rust used to support writing code like: 

```rust
match x {
    y @ z => { ... }
}

match a {
    b @ Some(c) => { ... }
}
```

PR #16053 disabled the ability to write such code. More precisely, it disabled the ability to introduce *any* kind of binding in subpattern `P` in the context of any binding-pattern `ident @ P`

The reason we did this was because it was too hard to handle them soundly in the AST-borrowck.

However, now that we have migrated 100% to NLL and thus MIR-borrowck, we should be able to soundly re-enable this feature, without too much effort (I hope).
 * Back when the feature was removed, we made an [explicit note](https://github.com/rust-lang/rust/pull/16053#issuecomment-50881116) that the long term intention was to reenable it. 
 * And this *is* a useful coding pattern at times. (The whole reason I went looking for this issue, and then decided to file it after discovering it did not seem to exist, was because I wanted to write code that required this feature, namely a pattern like: `ty::Ref(_, adt_ty @ ty::TyS { kind: ty::Adt(adt_def, _), .. }, _)`)

Note that any attempt to re-enable the feature should do a careful survey of the various cases that can arise (copying, moving, mixing ref and non-ref, match ergonomics, ...)

Also, any attempt to re-enable the feature should also attempt to re-add all the tests that were removed with PR #16053

**Comment by pnkfelix** [comment]
I don't *think* implementing this requires an RFC, but I suppose its worth double-checking with the lang team. Nominating for discussion at lang team meeting on that point. 

(And removing from T-compiler for now; no reason to both T-compiler about this until after T-lang has confirmed that we want this feature re-added.)

**Comment by estebank** [comment]
I see the potential for trivial bugs to be enabled and diagnostic text confusion exhacerbated by doing this, which is why I would like to have a very clear plan to extend the pattern checking code to suggest things like `b @ Some(c)` when clearly `Some(c) @ b` was meant.

**Comment by Centril** [comment]
@estebank That has already been fixed in https://github.com/rust-lang/rust/pull/65410?

**Comment by Centril** [comment]
The language team discussed this on 2019-10-17. We agreed with @pnkfelix's assessment that an RFC is not necessary in this case. Moreover, we agreed that this was desirable to remove unnecessary and annoying restrictions ("franken-feature" was used). We did note however that, as with all other features, it is important to have the tests in place, and that a to-be-FCPed stabilization should be filed.

-------------------------

The main implementation work consists of:

- Introducing a feature gate `bindings_after_at`; follow https://rust-lang.github.io/rustc-guide/implementing_new_features.html#stability-in-code to do so.

- Removing the check that bans this (under a feature gate): https://github.com/rust-lang/rust/blob/e5b8c118a38e8f3319813de56386bf43751582d7/src/librustc_mir/hair/pattern/check_match.rs#L648-L685

- Removing (under a feature gate) (since bindings are now allowed it always is `MachineApplicable`) https://github.com/rust-lang/rust/blob/e5b8c118a38e8f3319813de56386bf43751582d7/src/libsyntax/parse/parser/pat.rs#L405-L412

- Writing a barrage of tests to make sure the behavior is both allowed and sound.

**Comment by matthewjasper** [comment]
There might also need to be some MIR lowering changes if we don't want to allow `ref mut x @ ref mut y => { /* only use y */ }`.

**Comment by Centril** [comment]
Ah yes, we probably don't want to allow that (but we can land separate PRs for the different parts of the work since it will be feature gated).

**Comment by pnkfelix** [comment]
> There might also need to be some MIR lowering changes if we don't want to allow `ref mut x @ ref mut y => { /* only use y */ }`.

Shouldn't that be implemented as a syntactic restriction? As in, something that we enforce via analysis of the AST (e.g. by tracking whether a `ref mut x @ ...` occurred and disallowing further `ref mut` bindings within the `...` as we descend into it?)

Or am I missing something -- e.g., perhaps it is most natural to implement the check as part of the recursive descent performed by MIR lowering?

**Comment by matthewjasper** [comment]
Implementing it in HIR sounds reasonable.

**Comment by Centril** [comment]
The initial implementation landed in https://github.com/rust-lang/rust/pull/66296. 🎉

I've filed some issues under [F-bindings_after_at](https://github.com/rust-lang/rust/labels/F-bindings_after_at) which need to be worked on (like those you see above this comment). The two immediate next steps would be to resolve https://github.com/rust-lang/rust/issues/67565 and https://github.com/rust-lang/rust/issues/67523. In particular, the latter issue seems like an important blocker before anything can be stabilized.

**Comment by Centril** [comment]
- On 2020-02-10, https://github.com/rust-lang/rust/pull/68992 landed. The PR was written by @matthewjasper and reviewed by @Centril. The PR fixed a parser recovery bug wherein `mut x @ y` would make `y` a mutable binding, manifesting as issues https://github.com/rust-lang/rust/issues/67861 and https://github.com/rust-lang/rust/issues/67926.

**Comment by Centril** [comment]
- On 2020-20-19, https://github.com/rust-lang/rust/pull/69236 landed. The PR was written by @Centril and reviewed by @estebank. The PR adjusted the parser changes in https://github.com/rust-lang/rust/pull/68992 to retain good error messages on e.g. `mut (x @ y)` patterns, suggesting `mut x @ mut y` as opposed to `mut x @ y`.

**Comment by Centril** [comment]
- On 2020-03-08, https://github.com/rust-lang/rust/pull/69690 landed. The PR was written by @thekuom and reviewed by @Centril and added run-pass tests for the combination of bindings-after-at, or-patterns, box-patterns, slice-patterns.

- On 2020-03-08, https://github.com/rust-lang/rust/pull/69810 landed. The PR was written by @thekuom and reviewed by @Centril and added dynamic-rop run-pass tests for bindings-after-at.

**Comment by Centril** [comment]
- On 2020-02-10, https://github.com/rust-lang/rust/pull/69817, written by @thekuom and reviewed by @Centril, landed. The PR added borrow checker tests in combination with or-patterns & other pattern features.

**Comment by Centril** [comment]
- On 2020-03-26, https://github.com/rust-lang/rust/pull/70389, written by @Centril and reviewed by @mark-i-m, landed. The PR fixed some bugs in diagnostics where we would end up using `_` as the name of the place when matching on a temporary. Now it says *"value"* in the diagnostic instead.

**Comment by WaffleLapkin** [comment]
Is there any plans to stabilize this feature? And if no, what is blocking the stabilization?

**Comment by oli-obk** [comment]
Status update: #69971 is fixed by #78638

So I think the next step (oce #78638 is merged) would be for someone to write a stabilization PR and to have the language team sign off on that PR

**Comment by MarcusDunn** [comment]
# Stabilzation Report

Stabilzed by [85305](https://github.com/rust-lang/rust/pull/85305])

## Description of behaviour

allows for bindings in the pattern after `@`.

```rust
#[derive(Debug)]
struct Point {
    x: i32,
    y: i32,
}

main() {
    let p @ Point {x: px, y: py } = Point {x: 10, y: 23};
    println!("x: {}, y: {}", px, py);
    println!("{:?}", p);
}
```
All pattern matching rules apply, such as `y` being shorthand for `y: y` as well as regular rules with respect to refutable bindings.
```rust
#[derive(Debug)]
struct Point {
    x: i32,
    y: i32,
}

fn main() {
    let point = Point {x: 10, y: 5};
    if let p @ Point {x: 10, y} = point {
        println!("x is 10 and y is {} in {:?}", y, p);
    } else {
        println!("x was not 10 :(");
    }
}
```
## Tests
This feature was originally removed due to [unsoundness](https://github.com/rust-lang/rust/pull/16053) with the borrow checker, as a result, this feature (and the borrow checking rules around it) is very [well tested](https://github.com/rust-lang/rust/tree/master/src/test/ui/pattern/bindings-after-at).

## Documentation
Currently, the reference implies this feature but lacks explicit examples for it. The complete lack of docs is resolved in this [PR](https://github.com/rust-lang/reference/pull/1027). As this feature is fairly niche, the spare documentation seems reasonable.

**Comment by bstrie** [comment]
Now that https://github.com/rust-lang/rust/pull/85305 has landed, can this issue be closed?
