### ISSUE TITLE
"try using a variant of the expected type" suggesting a peculiar syntax

### ISSUE THREAD

**Issue by Patryk27** [rust-lang/rust#65494]
Hi,

I've got following code:
```rust
#[derive(Eq, PartialEq)]
pub struct Foo;

impl Foo {
    fn new() -> Self { Foo }
}

fn main() {
    if None == Foo::new() {
            // ^^^^^^^^^^
            // |
            // expected enum `std::option::Option`, found struct `Foo`
            // help: try using a variant of the expected type: `Some(<Foo>::new())`
    }
}
```
([playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=f86e5f327f92613ab3a8f55e65521c63))

The suggested `<Foo>::new()` syntax is valid, but - quite frankly - spooky (and it seems to be this way from the very beginning of this feature). Could it suggest just `Foo::new()`?

I'd like to tackle this myself, but I'd need at least a hint where to look :-)

**Comment by csmoe** [comment]
improvement needed inside `print_qpath`:
https://github.com/rust-lang/rust/blob/f54911c6f2971b98ede2d21ab8cabd7daa1110ba/src/librustc/hir/print.rs#L1491-L1536

**Comment by estebank** [comment]
@Patryk27 consider also modifying the following to use `span_to_snippet` and only use `pprint` if that method returns `Err`:

https://github.com/rust-lang/rust/blob/fa0f7d0080d8e7e9eb20aa9cbf8013f96c81287f/src/librustc_typeck/check/demand.rs#L175

That way we ensure that we suggest the code as it is in the user's code whenever that is possible, regardless of formatting they might be using and the idiosyncrasies of `pprint`.
