### ISSUE TITLE
Rename first argument Option::unwrap_or to default

### ISSUE THREAD

**Issue by timClicks** [rust-lang/rust#65492]
We [currently](https://doc.rust-lang.org/std/option/enum.Option.html#method.unwrap_or) use the definition for `Option::unwrap_or`: 

```rust
pub fn unwrap_or(self, def: T) -> T
```

I sometimes read `def` as `define`. It would be clearer for me (and hopefully others!) if it had the following signature: 

```rust
pub fn unwrap_or(self, default: T) -> T
```

**Comment by petosorus** [comment]
Hi ! I'm interesting to work on this if no one has started.

**Comment by timClicks** [comment]
Wow, I half expected that this would be closed as wontfix. @petosorus I am happy to submit a patch, but if you want to that would be great.

**Comment by petosorus** [comment]
Lol.
Go ahead!
