### ISSUE TITLE
Rustdoc uses fake italics for code

### ISSUE THREAD

**Issue by tspiteri** [rust-lang/rust#65502]
For example https://doc.rust-lang.org/std/primitive.i32.html has the string “*See also the `std::i32` module*” which inludes code in italics. This is rendered using fake italics because the Source Code Pro italic font is not included.

Adding the italic font would fix this, but at the cost of having an extra font to download. Is the better formatting worth the (one-time?) download?

If there is an interest, I can prepare a PR to include the [latest version](https://github.com/adobe-fonts/source-code-pro/releases/tag/2.030R-ro%2F1.050R-it) of Source Code Pro including the italic font. The sizes are as follows:

| Font | Current Size | Latest Size |
|:-|:-|:-|
| Regular | 55472 | 95872 |
| Semibold | 55360 | 95576 |
| Italic | | 84264 |
| *Total*| 110832 | 275712 |

**Comment by GuillaumeGomez** [comment]
Reopening as it's not fixed.

**Comment by tspiteri** [comment]
The issue was fixed by #65665 but that was reverted because of an external bug. I tried to work around the bug, but since I cannot reproduce the bug itself, I cannot test the workaround myself. However I tried to make it simple to test for anyone who can reproduce the bug. Below I'm reproducing comment https://github.com/rust-lang/rust/pull/65665#issuecomment-558370443 since I posted it on the PR page after the PR was already closed:

As a workaround to the issue, I tried to open the woff files with fontforge and regenerate without doing any modification: my reasoning is that since fontforge does not support svg glyphs, it will remove them, and in fact the woff files do shrink a bit. However since I wasn't able to reproduce the issue I'm not able to test the workaround.

I made a test page to test the workaround: [https://tspiteri.gitlab.io/scp-test/test.html](https://tspiteri.gitlab.io/scp-test/test.html). The page has three pieces of code:
  1. Old: with the old font which should be fine, with dark background and light colour.
  2. New: with the new font which should demonstrate the issue where it exists.  I couldn't reproduce the issue myself.
  3. Fontforged: with the new font passed through fontforge.

If sample New looks bad (black on dark background) and sample Fontforged looks good (light colour on dark background) it means the workaround works. However I'm not even sure that sample New manifests the issue as I'm unable to reproduce the issue. Can someone who can reproduce the issue please have a look?
