### ISSUE TITLE
Mismatched types do not have line number

### ISSUE THREAD

**Issue by patientplatypus** [rust-lang/rust#65514]
```
error[E0308]: mismatched types
  |
  = note: expected type `()`
             found type `std::vec::Vec<u8>`
```

^ That is incredibly frustrating.

EDIT:

Turns out that for *macros* this is an issue apparently (I asked on freenode).

```
#[wasm_bindgen]
pub extern fn handle_mouse_down_stroke(stroke_type: String, stroke_size: u32, stroke_rgba: Vec<u8>, canvas_width: u32, canvas_height: u32, x: u32, y: u32)
-> Vec<u8>
```

vs 

```
#[wasm_bindgen]
pub extern fn handle_mouse_down_stroke(stroke_type: String, stroke_size: u32, stroke_rgba: Vec<u8>, canvas_width: u32, canvas_height: u32, x: u32, y: u32)
// -> Vec<u8>
```

This gives an error. This narrows down the field of bad error messages, but it is still an open issue.

**Comment by Mark-Simulacrum** [comment]
I suspect this is fixed now on nightly -- the `extern fn` syntax previously caused macro expansion to lose spans, but should no longer do so I believe (I don't have time to hunt down the PR).

Can you check on nightly?

**Comment by Mark-Simulacrum** [comment]
Ah, I did not remember correctly. This is tracked in https://github.com/rust-lang/rust/issues/64561.
