### ISSUE TITLE
non-empty glob statement regression 1.39

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#65523]
https://crater-reports.s3.amazonaws.com/beta-1.39-1/beta-2019-09-28/reg/impl_ops-0.1.1/log.txt

cc https://github.com/rust-lang/rust/issues/62334
cc @petrochenkov 

cc https://github.com/rust-lang/rust/issues/64962

This issue has been assigned to @XiangQingW via [this comment](https://github.com/rust-lang/rust/issues/65523#issuecomment-543703822).

**Comment by petrochenkov** [comment]
Similarly to https://github.com/rust-lang/rust/issues/65090 this is very likely a combination of the recent changes in expansion order (https://github.com/rust-lang/rust/pull/63248, https://github.com/rust-lang/rust/pull/63867) and globs not fetching macro expanded names properly (https://github.com/rust-lang/rust/issues/56593).

In this case, however, the fix may be to turn the "non-empty glob must import something" error into a lint, we have an issue about that - https://github.com/rust-lang/rust/issues/62334.

**Comment by pnkfelix** [comment]
triage: P-high

**Comment by nikomatsakis** [comment]
Based on @petrochenkov's comment, it sounds like we plan to fix this in some form, and hence I am marking this as P-high.

I'm not clear though on **who** is going to fix this and **how** -- I'm going to re-assign @petrochenkov (as well as @XiangQingW) -- but perhaps somebody could clarify exactly which steps they plan to take? Sounds like maybe fixing https://github.com/rust-lang/rust/issues/62334 is the plan?

**Comment by XiangQingW** [comment]
I'll spend some time to dive into the issue this weekend.

**Comment by Centril** [comment]
This already has an outstanding PR in https://github.com/rust-lang/rust/pull/65539.

**Comment by pnkfelix** [comment]
closing as fixed by #65539
