### ISSUE TITLE
borrowck changes

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#65527]
This issue may need splitting up into smaller issues:

https://crater-reports.s3.amazonaws.com/beta-1.39-1/beta-2019-09-28/gh/eggmund.Prey/log.txt
https://crater-reports.s3.amazonaws.com/beta-1.39-rustdoc-1/beta-2019-09-28/gh/PEshwar.rust_blockchain/log.txt (unrelated to rustdoc)
https://crater-reports.s3.amazonaws.com/beta-1.39-rustdoc-1/beta-2019-09-28/gh/djcsdy.gfx-playground/log.txt (unrelated to rustdoc)
https://crater-reports.s3.amazonaws.com/beta-1.39-rustdoc-1/beta-2019-09-28/gh/efb9-860a-e752-0dac.rustchal/log.txt

cc #64962

**Comment by ecstatic-morse** [comment]
The errors in `eggmund.Prey` are a result of NLL errors becoming fatal. They [existed as warnings](https://crater-reports.s3.amazonaws.com/beta-1.39-1/1.38.0/gh/eggmund.Prey/log.txt) on 1.38

**Comment by ecstatic-morse** [comment]
I [partially minimized](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=724a4beb735a3ac410f01c98d64f41d2) the last error (which occurs in `socketto-0.2.0`).
The `SmallVec` and trait object are necessary. This is a true regression.

**Comment by ecstatic-morse** [comment]
Regression 3 is difficult to minimize. It's a `dropck` problem with a lot of associated types and unsafe code. Here's where the [first](https://github.com/gfx-rs/gfx/blob/b5163cc21e8500936635a11d99912ca5b91ad0de/src/hal/src/command/render_pass.rs#L272) and [second](https://github.com/gfx-rs/gfx/blob/b5163cc21e8500936635a11d99912ca5b91ad0de/src/hal/src/command/render_pass.rs#L347) errors occur.

**Comment by ecstatic-morse** [comment]
@Mark-Simulacrum I've triaged all four regressions and opened an issue for the only unexpected one. I'll close this one in favor of it.

**Comment by Mark-Simulacrum** [comment]
[Crater](https://github.com/rust-lang/crater/blob/master/README.md) queries GitHub for all Rust repositories (I'm not sure on specifics of how GitHub determines that). We then build all of those repositories on our infrastructure.

**Comment by clintnetwork** [comment]
Oh very interesting, thank you 👌
