### ISSUE TITLE
: token not accepted in attribute?

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#65524]
https://crater-reports.s3.amazonaws.com/beta-1.39-1/beta-2019-09-28/reg/jellyschema-0.11.10/log.txt

I can't seem to reproduce this in a trivial example so it might be related to pre-cfg expansion or something like that...

cc https://github.com/rust-lang/rust/issues/64962

**Comment by petrochenkov** [comment]
Most likely introduced by https://github.com/rust-lang/rust/pull/64462.

**Comment by petrochenkov** [comment]
Minimized:
```rust
macro_rules! m { () => () }

#[allow(clippy:all)]
m!();

fn main() {}
```

Inert attributes on macro invocations (like `allow` in this case) disappear during macro expansion.

Previously such attributes were partially checked (compared to inert attributes remaining in the AST), after https://github.com/rust-lang/rust/pull/64462 they are fully checked (in the same way as inert attributes remaining in the AST).

**Comment by estebank** [comment]
It sounds like we would want to warn on these cases.

**Comment by Centril** [comment]
> It may make sense to not check them at all (cc #63221).

Imo, based on a single regression, which also exposed a bug in the crate, it doesn't seem like a justified change.

**Comment by estebank** [comment]
I hadn't checked how many dependencies it had. It should be fine but we must proactively reach out to fix their crate.

**Comment by Centril** [comment]
Done in https://github.com/balena-io-modules/jellyschema/pull/118.
