### ISSUE TITLE
derive structs (inert attribute?) regression 1.39

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#65521]
https://crater-reports.s3.amazonaws.com/beta-1.39-1/beta-2019-09-28/reg/derive_less-0.2.0/log.txt
https://crater-reports.s3.amazonaws.com/beta-1.39-1/beta-2019-09-28/reg/rs621-0.5.0-alpha2/log.txt
https://crater-reports.s3.amazonaws.com/beta-1.39-1/beta-2019-09-28/gh/andrei-cacio.distil-wasm/log.txt
https://crater-reports.s3.amazonaws.com/beta-1.39-rustdoc-1/beta-2019-09-28/gh/nasso.get621/log.txt

possibly cc https://github.com/rust-lang/rust/issues/63221?

cc @petrochenkov 

cc https://github.com/rust-lang/rust/issues/64962

**Comment by petrochenkov** [comment]
This is a consequence of https://github.com/rust-lang/rust/pull/63468.
Attributes on fields, variants and other places are now properly passed through name resolution.
This means we now detect attempts to apply derives to them, while previously they were just ignored.

The new behavior is correct, but we can make a deprecation lint for this if necessary.

**Comment by Centril** [comment]
> The new behavior is correct, but we can make a deprecation lint for this if necessary.

The regressions do not seem numerous or serious enough to warrant that work imo.

**Comment by pnkfelix** [comment]
triage: P-high to decide whether to close as known-bug with no deprecation lint. Nominating for discussion at T-compiler meeting to decide above.

**Comment by nikomatsakis** [comment]
We discussed at the @rust-lang/compiler meeting and decided that the scope of this fallout doesn't merit a future compatibility warning. Therefore, I am closing this issue.
