### ISSUE TITLE
ptr types not default

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#65525]
https://crater-reports.s3.amazonaws.com/beta-1.39-1/beta-2019-09-28/reg/libffi-sys-0.7.0/log.txt
https://crater-reports.s3.amazonaws.com/beta-1.39-1/beta-2019-09-28/reg/libffi-0.7.0/log.txt
https://crater-reports.s3.amazonaws.com/beta-1.39-1/beta-2019-09-28/reg/libsamplerate-sys-0.1.5/log.txt

cc https://github.com/rust-lang/rust/issues/64962

**Comment by pcpthm** [comment]
Likely due to #64710 exposing `bindgen` bug <https://github.com/rust-lang/rust-bindgen/pull/1627>. Updating `bindgen` fixes the issue.

**Comment by pnkfelix** [comment]
closing: this bug was expected, and has been classified as due to `bindgen` breaking contract of `PartialOrd` and `Ord` needing to agree with one another
