### ISSUE TITLE
bindgen changes in 1.39

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#65520]
https://crater-reports.s3.amazonaws.com/beta-1.39-1/beta-2019-09-28/gh/theaaf.decklink-rs/log.txt
https://crater-reports.s3.amazonaws.com/beta-1.39-1/beta-2019-09-28/reg/janet-ll-0.4.1/log.txt
https://crater-reports.s3.amazonaws.com/beta-1.39-1/beta-2019-09-28/reg/srtp2-sys-2.20.1/log.txt
https://crater-reports.s3.amazonaws.com/beta-1.39-1/beta-2019-09-28/gh/Helkafen.vcf_pwm/log.txt

It's unclear whether this is our fault or bindgen or something else, but the behavior does appear to have changed.

cc https://github.com/rust-lang/rust/issues/64962

**Comment by pnkfelix** [comment]
triage: P-high to get to bottom of what happened.

**Comment by ecstatic-morse** [comment]
Probably the same as in #65525, but someone should verify this. According to @pcpthm:

> Likely due to #64710 exposing `bindgen` bug [rust-lang/rust-bindgen#1627](https://github.com/rust-lang/rust-bindgen/pull/1627). Updating `bindgen` fixes the issue.

**Comment by pnkfelix** [comment]
At this point the release is out, so I'm closing this bug as a task not worth following up on formally. (The point of the task is to try to catch bugs before the release. Once the release is out, we can just let people file them if there are real bugs actually present that are not addressed via `cargo update`)
