### ISSUE TITLE
Request: A way to collect a `String` from an `impl Iterator<item=u8>`

### ISSUE THREAD

**Issue by Lokathor** [rust-lang/rust#65538]
As much as rust seems to love iterators and also utf8, there doesn't seem to be a way to collect a `String` from an iterator of bytes. Everything forces you to collect into a `Vec<u8>` and then re-parse that into a `String`.

There is a `FromIterator<char>`, but there also doesn't appear to be a way to get a `char` from 1 to 4 bytes, or any iterator adapter that will turn a stream of utf8 bytes into a stream of `char` values.

**Comment by Mark-Simulacrum** [comment]
I'm also not sure if this is possible - you would need to implement FromIterator for Result<String, Utf8Error> or so, right? That seems like it would overlap with the general impl for Result.

**Comment by passcod** [comment]
Adding some context (from community discord), this is about avoiding the extra allocation when going from bytes to String, not _necessarily_ going through `FromIterator`.

**Comment by Lokathor** [comment]
It doesn't need to be usable with collect. It can be a method on the String type.

```rust
let s: String= String::from_lossy_bytes_iterator(it);

let s: Result<String,???> = String::from_bytes_iterator(it2);
```

That error case in the non-lossy version is going to be annoying to design. You could probably work it out to a normal UTF8Error by converting the String that did parse back into a Vec and then extending it with the remains of the iterator.

**Comment by Mark-Simulacrum** [comment]
I am confused. What extra allocation do you want to avoid? The case of non-utf 8 data?

**Comment by Lokathor** [comment]
Supposing that you currently have a value with type `impl Iterator<Item=u8>`, convert it to String, safely.

As far as I can tell, there's no way to do this in core/alloc/std without first collecting into `Vec<u8>` (allocation 1) and then _separately_ trying to convert that into a `String` (allocation 2).

**Comment by Lokathor** [comment]
There doesn't even appear to be `char::from_utf8_bytes(&[u8]) -> Result<char, Error>` or similar so that you can decode bytes into the individual characters, which you could then build into an iterator adapter to use with the `FromIterator<char>` impl.

**Comment by scottmcm** [comment]
> and then separately trying to convert that into a String (allocation 2)

With https://doc.rust-lang.org/std/string/struct.String.html#method.from_utf8 that's not a separate allocation, though?

**Comment by Lokathor** [comment]
It is in the lossy case.

but closed in favor of https://github.com/rust-lang/rust/issues/64727 since a solution there would solve here too.
