### ISSUE TITLE
save-analysis: adjust `process_formals` wrt. or-patterns

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#65556]
Filing this as a keep-sake for discussion in https://github.com/rust-lang/rust/pull/64250#discussion_r321970321.

cc @Xanewok

**Comment by Centril** [comment]
@Xanewok Or-patterns are "fleshed out" now... ;)

**Comment by varkor** [comment]
@Xanewok: do you know if is this still an issue?

**Comment by Xanewok** [comment]
From what I know, this still needs to be fixed, yes.

**Comment by jyn514** [comment]
Save-analysis has been [removed from the compiler](https://github.com/rust-lang/rust/pull/101841).
