### ISSUE TITLE
[bug] Inline code block starting with space is trimmed

### ISSUE THREAD

**Issue by jhpratt** [rust-lang/rust#65555]
In some documentation that I recently wrote, I had an inline code block that has a leading space.

```
` 5`
```

This is rendered as `<code>5</code>` — notice the lack of a leading space.

Given that the documentation in question is literally to show how a leading space is added, and given that code blocks otherwise display content as-is, this seems like a bug to me.

Reference for full source code in case this behavior isn't consistent: https://github.com/time-rs/time/blob/7dc4cf32c48d4e5113661423b4869b5015decb64/src/lib.rs#L80-L84

**Comment by pietroalbini** [comment]
Thanks for opening this issue @jhpratt! I moved this issue from `rust-lang/docs.rs` to `rust-lang/rust` as this is a rustdoc bug (docs.rs just calls rustdoc to build the documentation).

**Comment by jhpratt** [comment]
Thanks! Wasn't sure if rustdoc had its own repo.

**Comment by Mark-Simulacrum** [comment]
Fix is in https://github.com/rust-lang/rust/pull/65613.

**Comment by jhpratt** [comment]
Thanks @Mark-Simulacrum!

**Comment by GuillaumeGomez** [comment]
As discussed in #65613, better keep it as is and let users decide what they want on their own.
