### ISSUE TITLE
Unexpected FFI/C pointer behavior when MaybeUninit.assume_init() is stored in struct

### ISSUE THREAD

**Issue by parisholley** [rust-lang/rust#65567]
While trying to determine the root cause of #65546 within my code, I am hitting what seems to be unexpected behavior of pointers being shared between Rust and C. I have taken some of the code from #65546 and simplified to the most simplest version possible (creating a replica of the C library behavior without all the extra stuff).

All of the code C + Rust can be found in this repo: https://github.com/parisholley/rust-ptrbug and is easy to reproduce running the two different cargo tests.

As someone who does not come from a C background and just starting to get into Rust, my understanding is that the C code should be free to mutate the object beneath the pointer at any time, and pointer that Rust holds on to should be valid throughout the lifetime of this example application.

Looking at the test cases I put together to reproduce here:

https://github.com/parisholley/rust-ptrbug/blob/af800045e84d84152b7e3808eb3483d5dd7caff0/src/lib.rs#L62-L84

I can see no reasonable explanation as to why that macro would cause the pointer assertions `assert_engine` to fail after a single invocation of `do_get_release_worker`.

To be clear, I have zero use-case for actually having a println!() in my final code (I only discovered this via debugging), but if you follow the conversation in #65546, this same behavior is happening with CString (and possibly other code as well).

**Comment by parisholley** [comment]
i just updated the repo with more test cases, it appears to be a strong correlation between the unexpected behavior and string allocation

**Comment by sfackler** [comment]
The C code assume that the engine struct never moves, as it stores its address in internal data structure: https://github.com/parisholley/rust-ptrbug/blob/master/lib.c#L12. Your rust code is moving it (in the call to assume_init, and when the new function returns), so that pointer becomes dangling.

This is not a general support forum for Rust code. https://users.rust-lang.org or https://reddit.com/r/rust are better places to ask for this kind of help.

**Comment by jonas-schievink** [comment]
Closing as not-a-bug

**Comment by parisholley** [comment]
@sfackler while that may be a fair assessment, are you saying that unless there are changes to the stack, the pointer does not change when rust moves objects? your answer does not explain away my test cases failing inconsistently?

**Comment by sfackler** [comment]
The behavior is undefined. A logical move may or may not become a physical move.

**Comment by parisholley** [comment]
as a note to anyone who sees this in the future, what I am trying to do actually is possible if you take advantage of the right combo of new language features:

```rust
let mut lazy_allocation = MaybeUninit::uninit();

let mut boxed = Box::pin(lazy_allocation);

my_unsafe_c_allocator(boxed.as_mut_ptr());
```

Using that setup, you can put the `boxed` object, anywhere you want, structs, etc.. The "Pin" will tell Rust not to move the C allocated object in memory, no matter who owns the pointer. As a consequence, your API will become more unsafe because to access the pointer again in the future, you will need to do:

```rust
fn do_something_with_pointer(unboxed:*mut my_c_struct){
    unsafe{
        // send ptr to another c function
        unsafe_c_func(unboxed);
    }
}

unsafe { 
   do_something_with_pointer(boxed.as_mut_ptr())
}
```

**Comment by jonas-schievink** [comment]
@parisholley That's not what `Pin` does, `Box` will allocate the object on the heap, and the object isn't moved when the `Box` is moved. You can still move out of a `Box` though (and `Pin`, unless you've made sure your type does *not* implement `Unpin`), so take care not to do that.
