### ISSUE TITLE
proc_macro libraries bloats binary with unused dependencies

### ISSUE THREAD

**Issue by danguafer** [rust-lang/rust#65573]
I have the following situation:

I use a set of dependencies in my proc_macro library, which I need to generate tokens, but I don't want these dependencies to be included in my final binary, because these dependencies are only used during the compilation step.

I am reporting this situation and I am not sure if Rust/Cargo already provide a functionality to workaround this issue of it's a feature to be implemented.

**Comment by Mark-Simulacrum** [comment]
Do you have evidence they are being included? I would not expect proc macro dependencies to be included in the final binary as well.

**Comment by danguafer** [comment]
@Mark-Simulacrum let me provide a background. I am right now developing this:

https://github.com/danguafer/ligen-devenv

`ligen` is a proc_macro to parse impl blocks and generate FFIs for each method. Its dependencies are:
```
proc-macro2 = "1.0.1"
syn = { version = "1.0.2", features = [ "full" ] }
quote = "1.0"
ligen-core = { path = "../ligen-core" }
```
`ligen-core` is the core of `ligen`, its dependencies are:
```
proc-macro2 = "1.0.1"
syn = { version = "1.0.2", features = [ "full" ] }
quote = "1.0"
libloading = "0.5"
```

I am using ligen to generate a static library for `geom` with the exported FFIs.
When I link the static library in my C++ project, it also requires me to link: wsock32 ws2_32 userenv.

**Comment by Mark-Simulacrum** [comment]
Can you see symbols and such from the proc macros in the final static library? The crate dependencies you've provided are for the proc macro -- which, yes, will include those libraries within it. I think the best bet for you to show that this is indeed a bug is to write a simple example of a symbol in the proc macro getting exposed from the staticlib of a crate that depends on that proc macro.

wsock32, ws2_32, and userenv look like perhaps windows libraries -- are you sure these are coming from the ligen dependency? It's possible they're needed by e.g. the standard library (they look like somewhat core functionality, though this is purely based on the names).

**Comment by danguafer** [comment]
@Mark-Simulacrum yes, it looks like they were included by Rust itself.

```
$ cargo rustc -- --print=native-static-libs                                                                                                                                                                                                                                        Compiling testlib v0.1.0 (C:\Users\Veritas-Desktop\dev\danguafer\ligen-devenv\testlib)                                                                                                                                                                                       note: Link against the following native artifacts when linking against this static library. The order and any duplication can be significant on some platforms.                                                                                                                                                                                                                                                                                                                                                                                                 note: native-static-libs: advapi32.lib ws2_32.lib userenv.lib msvcrt.lib
```

Is there any way I can get rid of these dependencies since I am not directly using, let's say, networking at all?

**Comment by Mark-Simulacrum** [comment]
`#![no_std]` might work. I would also think about whether that's actually a problem -- I suspect all(?) Windows libraries ship with those dependencies?

**Comment by retep998** [comment]
If your code does not use any std functionality that relies on symbols from those libraries, then you will not have a dependency on those libraries. If you *do* then you have to either change your code to not use that subset of std functionality, or not use std at all.
