### ISSUE TITLE
Outdated `--explain` examples for E0659 "An item usage is ambiguous."

### ISSUE THREAD

**Issue by mattheww** [rust-lang/rust#65571]
See [E0659][1] for the current text.

[1]: https://github.com/rust-lang/rust/blob/518deda77feb4957bfd311b6cb50baa7ef9ca6a2/src/librustc_resolve/error_codes.rs#L1767

It includes the following example:

```
pub mod moon {
    pub fn foo() {}
}

pub mod earth {
    pub fn foo() {}
}

mod collider {
    pub use moon::*;
    pub use earth::*;
}

fn main() {
    collider::foo(); // ERROR: `foo` is ambiguous
}
```

which needs updating for Rust 2018: it needs `crate::` or `parent::` adding inside `mod collider`.

The same is true in the recommended replacement.

**Comment by Centril** [comment]
cc @GuillaumeGomez
