### ISSUE TITLE
You can't compare &mut i32 with &i32, but you can compare &i32 with &mut i32

### ISSUE THREAD

**Issue by Duddino** [rust-lang/rust#65589]
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=11d3a2fe6f9ec8544d3f64917b99f913

**Comment by Centril** [comment]
Maybe this can be fixed by adding another impl? Not sure if this is typeck's fault or the lack of an impl...

**Comment by ecstatic-morse** [comment]
Both impls [already exist](https://doc.rust-lang.org/std/cmp/trait.PartialEq.html#impl-PartialEq%3C%26%27_%20B%3E-1).

**Comment by Duddino** [comment]
I can try adding impl for PartialOrd (as soon as I get back home) and if it fixes this I will make a PR

**Comment by inquisitivecrystal** [comment]
Per #87328, it looks like this can't be solved backwards compatibly. I think a fix might require a change to the coercion rules. In any case, closing this issue.
