### ISSUE TITLE
With `allow(const_err)`, diagnostics are not very helpful

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#65597]
Consider:
```rust
#![allow(const_err)]

union Trans { i: usize, o: &'static u32 }

const C: () = unsafe { let _val = *Trans { i: 4 }.o; () };

fn main() {
    println!("{:?}", C);
}
```
This deref's a dangling pointer, but due to `allow(const_err)` the only diagnostic we get is
```
error[E0080]: evaluation of constant expression failed
 --> src/main.rs:8:22
  |
8 |     println!("{:?}", C);
  |                      ^ referenced constant has errors

error: aborting due to previous error
```

Making this an allowable lint is not very helpful when later follow-on errors are hard errors.

**Comment by oli-obk** [comment]
We could add a `Silenced` variant to `ErrorHandled` and use it in https://github.com/rust-lang/rust/blob/e5b8c118a38e8f3319813de56386bf43751582d7/src/librustc/mir/interpret/error.rs#L126 if the lint has not been emitted.

Then we can add a note to the `referenced constant has errors` error stating that some errors have been hidden due to `allow(const_err)`

**Comment by luojia65** [comment]
I met this issue when I try to write for embedded devices, for example we need to generate PLL configurations from frequencies set and there could be no solution in some situations where a panic should be fired. After this issue being solved we can write more abstract in embedded rust crates.

**Comment by RalfJung** [comment]
@luojia65 the issue only applies when you do `allow(const_err)`, so I don't understand how you can say "there could be no solution in some situations". Just don't `allow(const_err)`?

**Comment by RalfJung** [comment]
The "hard error" option in https://github.com/rust-lang/rust/issues/71800 would solve this.

**Comment by estebank** [comment]
Current output:

```
warning: lint `const_err` has been removed: converted into hard error, see issue #71800 <https://github.com/rust-lang/rust/issues/71800> for more information
 --> src/main.rs:1:10
  |
1 | #![allow(const_err)]
  |          ^^^^^^^^^
  |
  = note: `#[warn(renamed_and_removed_lints)]` on by default

error[E0080]: evaluation of constant value failed
 --> src/main.rs:5:35
  |
5 | const C: () = unsafe { let _val = *Trans { i: 4 }.o; () };
  |                                   ^^^^^^^^^^^^^^^^^ dereferencing pointer failed: 0x4[noalloc] is a dangling pointer (it has no provenance)

note: erroneous constant used
 --> src/main.rs:8:22
  |
8 |     println!("{:?}", C);
  |                      ^

note: erroneous constant used
 --> src/main.rs:8:22
  |
8 |     println!("{:?}", C);
  |                      ^
  |
  = note: this note originates in the macro `$crate::format_args_nl` which comes from the expansion of the macro `println` (in Nightly builds, run with -Z macro-backtrace for more info)
```
