### ISSUE TITLE
Add `x.py` option to skip rebuilding LLVM

### ISSUE THREAD

**Issue by varkor** [rust-lang/rust#65612]
The compiler LLVM is rebuilt whenever the built version of LLVM doesn't have the right hash. (Previously it was rebuilt based on a special marker file, which was easier to work around.)
https://github.com/rust-lang/rust/blob/f042687959ef15f9c45d7093cd6b01f137da743f/src/bootstrap/native.rs#L88-L108
However, most of the time, having the latest LLVM version is not necessary, but makes rebuilding rustc after rebasing take significantly longer, which is a pain. It would be good to be able to disable this as an option in `x.py` for convenience.

This issue has been assigned to @matthew-healy via [this comment](https://github.com/rust-lang/rust/issues/65612#issuecomment-567610570).

**Comment by varkor** [comment]
To fix this, you'll want to add another option: you should be able to look at the logic for something like `--keep-stage`.
https://github.com/rust-lang/rust/blob/f042687959ef15f9c45d7093cd6b01f137da743f/src/bootstrap/flags.rs#L130-L131

**Comment by Centril** [comment]
It would be good if this could be changed in the config file so you don't have to pass in the option all the time.

**Comment by varkor** [comment]
@Centril: if it's a config file option, then there should be an `x.py` option to rebuild it if necessary. I.e. it shouldn't be necessarily to temporarily change the `Config.toml` to rebuild.

**Comment by Centril** [comment]
@varkor sure that seems good, although they can be implemented separately.

**Comment by spadaval** [comment]
The line you would need to change is near this one: (line 735 of bootstrap.py)        
```python
if self.get_toml('llvm-config') and self.get_toml('lld') != 'true':
        continue
``` 
It would probably be much easier to add a check against a key in the config, than to add a new flag.

**Comment by Walther** [comment]
...sorry, my bad!

@rustbot claim

**Comment by matthew-healy** [comment]
@Walther are you still working on this? I wouldn't mind picking it up if not.

(Sorry - not really sure what the etiquette is re: dormant tickets!)

**Comment by matthew-healy** [comment]
Just saw that @Walther's PR (#65848) lapsed. I'm gonna claim this, if that's okay. Will work on something based on the existing comment there.

@rustbot claim

**Comment by Walther** [comment]
Thank you for picking this up! Getting things fixed is the important thing, and I'm sure I'll find something else to fix in the near future when I have more time 🙂
