### ISSUE TITLE
Feature Request: Automatically add author and version to compiled binary

### ISSUE THREAD

**Issue by mihaigalos** [rust-lang/rust#65636]
Since the `author` and `version` of the rust compiled binary is specified in the `*.toml` file anyway, why not automatically add that information to the binary and make it accessible with `--version`?

**Comment by jonas-schievink** [comment]
This is already accessible through environment variables Cargo sets. Providing command line argument handling is not something Rust will do by default, and would have to go through the RFC process anyways, so closing.

**Comment by jonas-schievink** [comment]
For the environment variables Cargo sets, refer to https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-crates

**Comment by mihaigalos** [comment]
I am sorry, I would like to have the information present in the `*.toml` file in the compiled binary. The compiled binary should be cargo-agnostic. I would like to be able to invoke `./binary --version`.

**Comment by qnighy** [comment]
For that purpose, this example may help you: https://github.com/clap-rs/clap/blob/master/examples/09_auto_version.rs
