### ISSUE TITLE
Rustbot self-assigns issues when using "claim" or "assign" keywords

### ISSUE THREAD

**Issue by trivikr** [rust-lang/rust#65645]
This appears to be incorrect behavior.
Issues assigned to rustbot https://github.com/rust-lang/rust/issues?q=is%3Aissue+rustbot+assign+assignee%3Arustbot

Example comments:
* https://github.com/rust-lang/rust/issues/65523#issuecomment-543703822
* https://github.com/rust-lang/rust/issues/65440#issuecomment-542319420
* https://github.com/rust-lang/rust/issues/65254#issuecomment-540657880

Note that rustbot self-assigns the issue instead of assigning to the person claiming or being asked to assign to

This issue has been assigned to @trivikr via [this comment](https://github.com/rust-lang/rust/issues/65645#issuecomment-544311174).

**Comment by trivikr** [comment]
Example comment in this issue: https://github.com/rust-lang/rust/issues/65645#issuecomment-544311174
The issue was self-assigned by rustbot, and not to @trivikr

**Comment by trivikr** [comment]
Relevant code:
* https://github.com/rust-lang/triagebot/blob/365fdb0ac2ea440ceec7d0193c42a8feffa3868a/parser/src/command/assign.rs#L46-L50
* https://github.com/rust-lang/triagebot/blob/365fdb0ac2ea440ceec7d0193c42a8feffa3868a/parser/src/command/assign.rs#L55-L60

**Comment by trivikr** [comment]
This issue can be transferred to https://github.com/rust-lang/triagebot
Documentation: https://help.github.com/en/articles/transferring-an-issue-to-another-repository

**Comment by Mark-Simulacrum** [comment]
Intentional behavior. GH API doesn't let us assign to a non-member user. See issue description for who it is assigned to.
