### ISSUE TITLE
Make TypeFoldable derivable

### ISSUE THREAD

**Issue by Aaron1011** [rust-lang/rust#65674]
Currently, the (internal) `TypeFoldable` trait must be implemented via the fairly verbose `EnumTypeFoldableImpl!` and `BraceStructTypeFoldableImpl!` macros. Adding a `derive(TypeFoldable)` proc-macro to `librustc_macros` would allow us to delete a large amount of code, and would drastically simplify adding new `TypeFoldable` implementations.

**Comment by cjgillot** [comment]
Hello,
I would like to do that. 
Do you mind?

**Comment by Aaron1011** [comment]
@cjgillot: Go ahead :)

**Comment by eddyb** [comment]
Technically a subset of / related to https://github.com/rust-lang/rust/issues/36588 - although I think I went a bit crazy with the ideas there, and just regular derives for a lot of traits is fine.
