### ISSUE TITLE
Is there "__attribute__(address_space(256))" in Rust compiler?

### ISSUE THREAD

**Issue by mincheolsung** [rust-lang/rust#65680]
Hi, I want to use "Memory references off the GS segment" in Rust.
Below is an example of it in clang.

`#define GS_RELATIVE __attribute__((address_space(256)))`
`int foo(int GS_RELATIVE *P) {`
 `return *P;`
`}`
Which compiles to (on X86-32):
`_foo:`
`movl 4(%esp), %eax`
`movl %gs:(%eax), %eax`
`ret`

Check https://buildmedia.readthedocs.org/media/pdf/clang/release_37/clang.pdf on the page 128

**Comment by jonas-schievink** [comment]
Hi! This issue tracker is mainly meant for bug reports and concrete, small feature requests. Questions like this are better asked in the user forum at https://users.rust-lang.org/ or on [one of the chat platforms](https://www.rust-lang.org/community) used by the Rust community.

I'm pretty sure that address space indices are LLVM-specific, so using them as-is would make programs incompatible with other backends.
