### ISSUE TITLE
rustdoc cannot resolve private intra-rustdoc link

### ISSUE THREAD

**Issue by dragostis** [rust-lang/rust#65697]
When in a private `mod`, rustdoc fails to resolve a private member when called with `--document-private-items`.

A project like this...
`src/lib.rs`:
```rust
mod foo;
```

`src/foo.rs`:
```rust
//! [`Bar`]
struct Bar;
```

... results in:
```
warning: `[Bar]` cannot be resolved, ignoring it...
 --> src/foo.rs:1:6
  |
1 | //! [`Bar`]
  |      ^^^^^ cannot be resolved, ignoring
  |
  = note: `#[warn(intra_doc_link_resolution_failure)]` on by default
  = help: to escape `[` and `]` characters, just add '\' before them like `\[` or `\]`

```

**Comment by jyn514** [comment]
The culprit is here: https://github.com/rust-lang/rust/blob/ea7181b5f7a888c2cf969ae86de7207fa5fb40aa/src/librustdoc/html/format.rs#L471

We should check there if `--document-private-items` was passed, and if so, don't skip the item.

**Comment by jyn514** [comment]
Fixed in https://github.com/rust-lang/rust/pull/72771
