### ISSUE TITLE
Error in compilation error

### ISSUE THREAD

**Issue by zhuxiujia** [rust-lang/rust#65701]
Error in Compile error:
<code>
 fn decode<T>(& self){
   self.for_each(|item| {});
}
</code>
will painc   move occurs because *self has type mysql::QueryResult<'_>, which does not implement the Copy trait

but  if you edit to:
<code>
 fn decode<T>(&mut self){
   self.for_each(|item| {});
}
</code>
it will Compile successfully！

This error indicates （move occurs because *self has type mysql::QueryResult<'_>, which does not implement the Copy trait）    that if you are a new user of rust, you don't know where the problem is.

**Comment by Tloru** [comment]
There is not an error in the message itself. Are you suggesting that this particular error message should include a note that points beginners in the right direction? If so, what note would point out "where the problem is"?

**Comment by zhuxiujia** [comment]
> There is not an error in the message itself. Are you suggesting that this particular error message should include a note that points beginners in the right direction? If so, what note would point out "where the problem is"?

Yes, I suggest pointing out exactly why the compilation failed in rust.  to help new user to  find   where the problem is

**Comment by jonas-schievink** [comment]
Please provide a self-contained example reproducing the bad error message

**Comment by estebank** [comment]
For cases like these, we now produce [the following output](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=94ba6b43dc6b6509df6cfc33e9fef78d), where we tell you exactly the change you need to make:

```
error[E0596]: cannot borrow `*self` as mutable, as it is behind a `&` reference
 --> src/main.rs:3:9
  |
3 |         self.bar()
  |         ^^^^^^^^^^ `self` is a `&` reference, so the data it refers to cannot be borrowed as mutable
  |
help: consider changing this to be a mutable reference
  |
2 |     fn foo(&mut self) {
  |            ~~~~~~~~~
```
