### ISSUE TITLE
Specific error message when trying to exhaustively match on pointer types

### ISSUE THREAD

**Issue by SergioBenitez** [rust-lang/rust#65712]
As the title suggests, exhaustive pattern checking for `usize` and `isize` fails when checks for similar patterns for `{i,u}{n}` succeed. Consider the following program ([playground link]):

```rust
// Okay.
fn g(len: u8) {
    match len {
        0 => { }
        1 => { }
        2 => { }
        3 ..= std::u8::MAX => { }
    }
}

// Fails.
fn f(len: usize) {
    match len {
        0 => {},
        1 => {},
        2 => {},
        3 ..= std::usize::MAX => {},
    }
}

// Okay.
fn j(len: i32) {
    match len {
        std::i32::MIN ..= -1 => {},
        0 => { }
        1 => { }
        2 => { }
        3 ..= std::i32::MAX => { }
    }
}

// Fails.
fn h(len: isize) {
    match len {
        std::isize::MIN ..= -1 => {},
        0 => { }
        1 => { }
        2 => { }
        3 ..= std::isize::MAX => { }
    }
}
```

While checking succeeds for `g` (`u8`) and `j` (`i32`), it fails for `f` (`usize`) and `h` (`isize`).

cc @varkor

[playground link]: https://play.rust-lang.org/?version=nightly&mode=release&edition=2018&gist=4d8f55f11f9d173c114269bd4c3f6653

---

This is intentional (exhaustive matching on pointers is tracked at https://github.com/rust-lang/rust/issues/56354), but where we _would_ exhaustively match, then we could suggest using `#![feature(precise_pointer_size_matching)]` and explain why the pattern wasn't exhaustively matched.

**Comment by varkor** [comment]
Exhaustive pattern matching is disabled by default for `usize` and `isize` because the width differs depending on the platform. You can enable it using `#![feature(precise_pointer_size_matching)]`. There's a tracking issue at https://github.com/rust-lang/rust/issues/56354.

**Comment by SergioBenitez** [comment]
@varkor If that's the case, the error message should allude to this.

**Comment by varkor** [comment]
That's a good point — we could emit better diagnostics here. Let's repurpose this issue for that.

**Comment by Nadrieril** [comment]
The error is now:
```
error[E0004]: non-exhaustive patterns: `_` not covered
 --> src/main.rs:2:11
  |
2 |     match len {
  |           ^^^ pattern `_` not covered
  |
  = help: ensure that all possible cases are being handled, possibly by adding wildcards or more match arms
  = note: the matched value is of type `usize`
  = note: `usize` does not have a fixed maximum value, so a wildcard `_` is necessary to match exhaustively
```
So we can close this

**Comment by varkor** [comment]
And there's a test for it already, perfect.
https://github.com/rust-lang/rust/blob/85bc9538920850e5bd7c1023c9ffbf5e8e69be6a/src/test/ui/pattern/usefulness/non-exhaustive-pattern-pointer-size-int.stderr#L1-L10
Thanks!
