### ISSUE TITLE
Tracking issue for the `matches!` macro

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#65721]
https://github.com/rust-lang/rust/pull/65479 adds this macro to the prelude:

```rust
#[macro_export]
macro_rules! matches {
    ($expression:expr, $( $pattern:pat )|+ $( if $guard: expr )?) => {
        match $expression {
            $( $pattern )|+ $( if $guard )? => true,
            _ => false
        }
    }
}
```

Example usage:

```rust
let foo = 'f';
assert!(matches!(foo, 'A'..='Z' | 'a'..='z'));

let bar = Some(4);
assert!(matches!(bar, Some(x) if x > 2));
```

**Comment by SimonSapin** [comment]
This caused a regression in html5ever because the prelude macro becomes ambiguous with a macro that was brought into scope by a glob import: https://github.com/servo/html5ever/pull/402

@rust-lang/lang, could we make that situation not an error? It seems that we could resolve the ambiguity in favor of the glob import since it is "more local" to the rest of the code in the module.

**Comment by eddyb** [comment]
cc @petrochenkov

**Comment by petrochenkov** [comment]
>could we make that situation not an error?

For macros (and imports) it's hard to do.

To remove the ambiguity error we need to prove that with any expansion order and any import resolution order `matches` materializes from the `use mac::*` glob "not later" than from prelude.

Otherwise we'll get code that compiles today but not tomorrow depending on random implementation details. (Making e.g. things like [this](https://rust-lang.zulipchat.com/#narrow/stream/195180-t-compiler.2Fwg-pipelining/topic/Starting.20crate.20build.20before.20the.20dependencies.20are.20ready) impossible.)

**Comment by SimonSapin** [comment]
I have a memory of a change made to treat differently during name resolution items that are unstable, so that new standard library addition can (at first) warn instead of error when they conflict with existing code. However I couldn’t find this again. Maybe it was only for traits?

**Comment by petrochenkov** [comment]
Yeah, that was for method resolution.

**Comment by SimonSapin** [comment]
Would a similar special case for unstable prelude items make sense?

**Comment by SimonSapin** [comment]
The 1.42 cycle starts soon. Any objection?

@rfcbot fcp merge

**Comment by jonhoo** [comment]
Should we also add a `assert_matches!` macro at the same time that `Debug`-prints the value if the match fails?

**Comment by SimonSapin** [comment]
I personally find that one less useful, but feel free to also propose it in a PR.

**Comment by jonhoo** [comment]
How do we feel about giving this the "relnotes" tag?

**Comment by lzutao** [comment]
Already on the stabilized PR: #67659

**Comment by SimonSapin** [comment]
@jonhoo I thought `RELEASES.md` listed all new(ly-stabilized) APIs? I added `relnotes` to the stabilization PR on that basis. That’s what the label is for, right? This is not to say this should necessarily be mentioned in the release blog post.

**Comment by danielhenrymantilla** [comment]
Could `matches!` be enhanced to also accept a leading `|`?
```rust
matches!(expr,
    | SomeFirstPattern
    | SomeOtherPattern
    ...
);
```

This would be consistent with the syntax of Rust accepting it where fallible patterns are accepted:

```rust
match expr {
    | SomeFirstPattern $(=> ...)?
    | SomeOtherPattern => ...
}
```
