### ISSUE TITLE
use xz files for stage0 download if on system with xz

### ISSUE THREAD

**Issue by stefson** [rust-lang/rust#65757]
I noticed that if `./x.py` is run from a git checkout, the build script downloads the rust-std and rustc, and cargo stage0 archives from static.rust-lang.org in the tar.gz format. Those are a lot bigger in size than the also delivered tar.xz files, usually adds some 30% in download time and consumed bandwith. Do you think you could possibly change the script to use `tar.xz` in the future? 

here's a snipet from my log: 

```
downloading https://static.rust-lang.org/dist/2019-09-26/rust-std-1.38.0-x86_64-unknown-linux-gnu.tar.gz.sha256
running: curl -# -y 30 -Y 10 --connect-timeout 30 --retry 3 -Sf -o /var/tmp/portage/dev-lang/rust-999/temp/tmprecglk92.sha256 https://static.rust-lang.org/dist/2019-09-26/rust-std-1.38.0-x86_64-unknown-linux-gnu.tar.gz.sha256
################################################################################### 100,0%
downloading https://static.rust-lang.org/dist/2019-09-26/rust-std-1.38.0-x86_64-unknown-linux-gnu.tar.gz
running: curl -# -y 30 -Y 10 --connect-timeout 30 --retry 3 -Sf -o /var/tmp/portage/dev-lang/rust-999/temp/tmp_2fjvg1r https://static.rust-lang.org/dist/2019-09-26/rust-std-1.38.0-x86_64-unknown-linux-gnu.tar.gz
################################################################################### 100,0%
verifying /var/tmp/portage/dev-lang/rust-999/temp/tmp_2fjvg1r
```

**Comment by guanqun** [comment]
I did a quick check and the boostrap script uses `tarfile` module to do the unpacking, and as our build system need to support at least python 2.7 which unfortunately doesn't contain the support of `xz` out of box. see the reference here: https://docs.python.org/2/library/tarfile.html
however, when we transition to python 3, then this `tarfile` supports `xz`: https://docs.python.org/3/library/tarfile.html

**Comment by guanqun** [comment]
I created a PR to use `.tar.xz` if `x.py` is called with python3. I tried locally with msvc and it works fine.

**Comment by stefson** [comment]
does this work depending on wether it's either 

`python2 ./x.py build` for using tar.gz

or `python3 ./x.py build` for using tar.xz then?

**Comment by guanqun** [comment]
that's right. because python 2 doesn't have xz support in its tarball library, see the link above. we could import other libraries but that would require extra dependencies.
