### ISSUE TITLE
diagnostics: suggest putting type behind binding variable in case of match x -> type

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#65768]
While doing some refactoring I accidentally  ended up with something like this:
````rust
let x = match 3_i32 -> bool {
    4 => true,
    _ => false,
};
````

````
error: expected one of `.`, `?`, `{`, or an operator, found `->`
 --> src/main.rs:2:21
  |
2 | let x = match 3_i32 -> bool {
  |         -----       ^^ expected one of `.`, `?`, `{`, or an operator here
  |         |
  |         while parsing this match expression

error: aborting due to previous error
````
Obviously  I wanted `let x: type` instead of `match -> type` :sweat_smile: 

````rust
let x: bool = match 3_i32  {
    4 => true,
    _ => false,
};
````

Perhaps the compiler could detect this and suggest putting the type after the binding variable?

**Comment by Centril** [comment]
This feels too random to me. Other than you accidentally typing it out, I don't think the sequence `$expr -> $type` is something of a common mistake. Moreover, the suggestion is from the POV of the AST fairly non-local and hacky to achieve with a recursive decent parser.

Imo I don't think we should add recovery for this case, at least not until we have stable type ascription (which would make the suggestion way easier to provide).

**Comment by estebank** [comment]
I'm gonna agree with @centril and close this ticket.
