### ISSUE TITLE
Improve error message for `impl Self`

### ISSUE THREAD

**Issue by sunjay** [rust-lang/rust#65784]
Suppose you have the following reduced code example:

```rust
impl Self {   
}
```

This gives you the error message:

```
error[E0391]: cycle detected when processing `<impl at src/lib.rs:1:1: 3:2>`
 --> src/lib.rs:1:6
  |
1 | impl Self {
  |      ^^^^
  |
  = note: ...which again requires processing `<impl at src/lib.rs:1:1: 3:2>`, completing the cycle
note: cycle used when collecting item types in top-level module
 --> src/lib.rs:1:1
  |
1 | impl Self {
  | ^^^^^^^^^
```

This is confusing because there isn't actually any obvious cycle (unless you know things about compilers). E0391 actually describes itself with an example like this:

```rust
trait FirstTrait : SecondTrait {

}

trait SecondTrait : FirstTrait {

}
```

This looks nothing like the original code example.

We should probably detect this case and provide a more useful message that indicates that `Self` is a special keyword that can be used within the impl block, but not as the type of the impl block itself.

**Comment by Centril** [comment]
I'm curious how `impl Self { ... }` happened -- can you describe the scenario?

**Comment by petar-dambovaliev** [comment]
@Centril I am also curious. I don't know of a language that supports that.
We should improve error messages when there is an actual real world example.

**Comment by compiler-errors** [comment]
@BoxyUwU fixed this, the error message on nightly looks like this now:

```
error: `Self` is not valid in the self type of an impl block
 --> src/lib.rs:1:6
  |
1 | impl Self {   
  |      ^^^^
  |
  = note: replace `Self` with a different type
```

Further improvements on the error message would be nice as a new issue, so newcomers can discover the issue, since it'd probably be a good E-easy task.

**Comment by BoxyUwU** [comment]
Oh I didn't realise there was an issue open for this..
