### ISSUE TITLE
Tracking issue for slice_ptr_range

### ISSUE THREAD

**Issue by m-ou-se** [rust-lang/rust#65807]
Tracking issue for `slice_ptr_range` added by https://github.com/rust-lang/rust/pull/65806. See https://github.com/rust-lang/rfcs/pull/2791

**Comment by jhpratt** [comment]
Anything holding up stabilization on this? I'd like to be able to use this to check if two slices overlap, as pointers implement `Ord`. It seems like a simple API that doesn't have a ton of complexity to it.

**Comment by josephlr** [comment]
Note that with #71499 these functions can be made `const fn`. The stabilization of these methods as `const fn` can just be tracked as part of #71499.

**Comment by m-ou-se** [comment]
> Note that with #71499 these functions can be made `const fn`. The stabilization of these methods as `const fn` can just be tracked as part of #71499.

Thanks! PR: #77097.
