### ISSUE TITLE
Missed optimization: regression 1.29 -> 1.30, makes unnecessary load from memory

### ISSUE THREAD

**Issue by safinaskar** [rust-lang/rust#65876]
Consider this code: https://godbolt.org/z/QpiBK3 .
Code:
```rust
pub fn f(a: &mut i32, b: &mut i32) -> (i32, i32, i32) {
    let c = *a;
    let d = *b;
    *a = 0;
    (c, d, *b)
}
```
Asm (1.30):
```asm
example::f:
        movl    (%rsi), %eax
        movl    (%rdx), %ecx
        movl    $0, (%rsi)
        movl    (%rdx), %edx
        movl    %eax, (%rdi)
        movl    %ecx, 4(%rdi)
        movl    %edx, 8(%rdi)
        movq    %rdi, %rax
        retq
```

We read from memory at line `let d = *b` (from `%rdx`) and then we read from memory again at line `(c, d, *b)` (again from `%rdx`).

But in Rust (unlike C and C++) we know that two mutable references cannot point to same location. So, we missed optimization. This is regression

**Comment by jonas-schievink** [comment]
This is likely due to the known issues with LLVM's `noalias` annotation. See https://github.com/rust-lang/rust/issues/54878.

**Comment by Mark-Simulacrum** [comment]
This has since been fixed. Current nightly output doesn't load from memory twice for rdx.

```
f:
        mov     rax, rdi
        mov     ecx, dword ptr [rsi]
        mov     edx, dword ptr [rdx]
        mov     dword ptr [rsi], 0
        mov     dword ptr [rdi], ecx
        mov     dword ptr [rdi + 4], edx
        mov     dword ptr [rdi + 8], edx
        ret
```
