### ISSUE TITLE
nll crater run for 1.40

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#65897]
This is to hopefully give a more up to date impression of regressions for the upcoming NLL post.

**Comment by Mark-Simulacrum** [comment]
@craterbot run start=beta-2019-10-27 end=nightly-2019-10-27 mode=check-only cap-lints=allow p=1

**Comment by Mark-Simulacrum** [comment]
@craterbot retry-report

**Comment by Aaron1011** [comment]
Crater seems to be stuck

**Comment by Mark-Simulacrum** [comment]
Maybe try this again, not sure... @pietroalbini probably needs to take a look.

@craterbot retry-report

**Comment by pietroalbini** [comment]
@craterbot retry-report

**Comment by jonas-schievink** [comment]
That's a lot of borrowck regressions. cc @matthewjasper

**Comment by matthewjasper** [comment]
There are also a lot of regressions due to our expansion gating and fixes because features are gated on beta but not nightly. Could another run be done on the regressed crates with the current nightly?

**Comment by Mark-Simulacrum** [comment]
Oh, yeah, to be clear I had not intended for anyone to take a look yet, this was a preliminary run that we can definitely reduce down somewhat :)

@craterbot run start=beta-2019-11-02 end=try#5e633973aa9255a88b65a39484627bb54e6044b3 mode=check-only cap-lints=allow p=1 crates=https://gist.githubusercontent.com/Mark-Simulacrum/b2b7233c91ea255e3d6d053b1c2bd821/raw/c7f32c4fe19446e3e08f44b82708c3db9d0ceea2/nll-crates.txt

This should be a much reduced run which compares just these crates with a more recent commit on the end point which is in fact compiled as if it was beta (avoiding unstable feature related regressions/fixes, hopefully -- this commit is stolen from https://github.com/rust-lang/rust/pull/66063)

**Comment by TimNN** [comment]
@craterbot abort

**Comment by Mark-Simulacrum** [comment]
@craterbot run start=beta-2019-11-03 end=try#5e633973aa9255a88b65a39484627bb54e6044b3 mode=check-only cap-lints=allow p=1 crates=https://gist.githubusercontent.com/Mark-Simulacrum/b2b7233c91ea255e3d6d053b1c2bd821/raw/c7f32c4fe19446e3e08f44b82708c3db9d0ceea2/nll-crates.txt

(per https://static.rust-lang.org/dist/2019-11-03 this date should be correct -- off by one errors, I tell you!)

**Comment by Aaron1011** [comment]
Something gives me the feeling that ```Experiment pr-65897-1 has encountered an error``` :smile:

**Comment by Mark-Simulacrum** [comment]
The majority of these are known -- in particular, nalgebra, rusttype and url still have a lot of reverse-dependencies that haven't updated on github (and that have lockfiles). I think those aren't too interesting, we can exclude them for the most part -- that set needs to just `cargo update` to resolve the problem to our knowledge.

There are at least 53 (around 60 total, I believe) crates.io crates that break due to the NLL switch -- I think we should try to get patches land in all of those over the next 6 weeks so that by the time this hits stable we hopefully only have regressions in a few or no crates.io crates. 

See https://hackmd.io/@simulacrum/BkkP1gbor for a list of roots from this run
