### ISSUE TITLE
cstore_impl dependency format linkage sometimes unknown 

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#65890]
spawned off of #64872 

The `match` input here (on line 245):

https://github.com/rust-lang/rust/blob/9285d401a6070094747465962bc49969b93e14c5/src/librustc_metadata/cstore_impl.rs#L243-L249

sometimes returns `None`

Its not yet clear to me under which scenarios that happens. But when it does happen, the dependency may be (re)exported from a static or a dynamic crate. This is probably a sign that the logic here needs to be revised in some way (assuming that the information in question *is* available somewhere in the data structures; otherwise, we'll need to try to add it).

In any case, this issue is to log the problem, so that I can link to it from any tests I encounter  that were previously assuming that the `-Z share-generics` optimization would always fire in this scenario.

**Comment by pnkfelix** [comment]
Hmm I guess @alexcrichton has a [theory](https://github.com/rust-lang/rust/pull/65781#issuecomment-546394248) as to how to interpret `None` here.

**Comment by pnkfelix** [comment]
@michaelwoerister was this fixed by #68277 ?

**Comment by michaelwoerister** [comment]
No, #68277 didn't change anything there. It fixed the `-Zshare-generics` problems by going another route.

**Comment by Enselic** [comment]
Triage: The quoted code was completely removed in https://github.com/rust-lang/rust/commit/d21f9b7fd6d4e41257bb4a6db64e9873767374dc. From what I understand, it is not known how to reproduce the problem. Now that the problematic code is removed, it is unclear to me how to take action here.

Closing as obsolete. Apologies in advance if that is inappropriate. Then of course feel free to re-open.
