### ISSUE TITLE
A way to test differences in diagnostics between stable and nightly

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#65903]
Sometimes we do things like `if self.sess.opts.unstable_features.is_nightly_build() {` to switch between diagnostics for stable and nightly, e.g. as in https://github.com/rust-lang/rust/pull/65893.

It would be good to have a way to tell a nightly compiler to behave as-if it was a stable one by making `.is_nightly_build()` return `false`. Ideally, this would be provided as a `-Z` flag which can be used in UI tests.

cc @estebank

**Comment by fmease** [comment]
Since #132993 setting the env var `RUSTC_BOOTSTRAP` to `-1` achieves this.
