### ISSUE TITLE
`c_void` stabilized since 1.30.0?

### ISSUE THREAD

**Issue by lzutao** [rust-lang/rust#65922]
I compile this snippet with Rust 1.1.0 : https://rust.godbolt.org/z/L3Ks20
```rust
pub type HANDLE = *mut ::std::ffi::c_void;
```

The snippet cannot be compiled. The compiler outputs:
```rust
<source>:1:24: 1:42 error: use of undeclared type name `std::ffi::c_void`
<source>:1 pub type HANDLE = *mut ::std::ffi::c_void;
                                      ^~~~~~~~~~~~~~~~~~
```

After searching a little bit, I know that #53910 moved `std::os::raw::c_void` to the as is.
But when reading std doc, people may assume that they could use this reexport
since Rust 1.1.0.
![image](https://user-images.githubusercontent.com/15225902/67740760-84dad000-fa49-11e9-9168-8a730fa943f5.png)

What could we do to improve this situation?

**Comment by lzutao** [comment]
Or we could state that people could use `std::os::raw::c_void` in older Rust versions.

**Comment by mati865** [comment]
Duplicate of https://github.com/rust-lang/rust/issues/63694?

**Comment by lzutao** [comment]
Indeed. Let's close it then.
