### ISSUE TITLE
Allow `Unsize` implementation

### ISSUE THREAD

**Issue by timothee-haudebourg** [rust-lang/rust#65926]
Currently, user implementation of the `Unsize` trait is forbidden by the compiler. Why is the reason other than it is unsafe ?

For instance, what if I want to have:
```rust
struct Dyn<T> {
  data: T,
  padding: [u8]
}

unsafe impl Unsize<Dyn<MyType>> for MyType { }
```

It is very unsafe, sure, but would that break some hidden assumptions for the `CoerceUnsized` trait for instance ? If not, why is it not allowed ?

As for why it would be interesting, you can consider this very much unsafe use case, implementing some kind of object-oriented data types, with containers:
```rust
struct A {
  ...
}

struct B {
  a: A,
  ...
}

unsafe impl Unsize<Dyn<B>> for B { }
unsafe impl Unsize<Dyn<A>> for B { }

fn main () {
  let b : Rc<Dyn<B>> = Rc::new(B { ... }) as Rc<Dyn<B>>;
  let b_as_a : Rc<Dyn<A>> = b.clone() as Rc<Dyn<A>>;
}
```

**Comment by jonas-schievink** [comment]
How would the compiler know how to perform the unsizing operation? All existing impls are built into rustc because it has to know how to perform them.

**Comment by timothee-haudebourg** [comment]
Hum right. It's not possible then. Would it be possible with a version of `Unsize` defined like this:
```rust
unsafe trait Unsize<U> {
    fn unsize(&self) -> &U
}
```
where the `unsize` function is basically in charge of converting a thin pointer into a fat one?

**Comment by Mark-Simulacrum** [comment]
We don't currently want to allow this functionality, even in an unstable fashion. I would look at "custom unsized types" and some other, I believe similarly named rfcs that have been proposed in the past.

The last impl you suggested is basically AsRef.

**Comment by timothee-haudebourg** [comment]
Thanks for the answers, I'm closing the issue.

Maybe as a last remark concerning `AsRef`, I feel like it is not exactly the same thing since there are no guaranties that the output of `as_ref` references the same value as `self`. The `unsafe` in my version of `Unsize` was meant to represent this "contract".
