### ISSUE TITLE
Custom attr on module causes macro import to be unresolved

### ISSUE THREAD

**Issue by TheDan64** [rust-lang/rust#65935]
```rust
#![feature(custom_attribute)]

#[my_header = "foo.c"]
pub mod foo {
    use c2rust_bitfields::BitfieldStruct;

    #[derive(BitfieldStruct)]
    struct Foo {
    }
}
```

will fail to compile with

```rust
error: cannot determine resolution for the derive macro `BitfieldStruct`
 --> src/main.rs:7:14
  |
7 |     #[derive(BitfieldStruct)]
  |              ^^^^^^^^^^^^^^
  |
  = note: import resolution is stuck, try simplifying macro imports

error: aborting due to previous error
```

However, removing the `my_header` attr will let it compile again.

**Comment by Mark-Simulacrum** [comment]
cc @petrochenkov 

Hm, the custom attribute feature might be at fault here, I suspect you want to make the custom attribute a normal macro (perhaps one that expands to a constant or something, not sure what the use case here is exactly). But this is total guesswork.

**Comment by petrochenkov** [comment]
`#![feature(custom_attribute)]` is not supported and slated for removal (with https://github.com/rust-lang/rust/pull/57921#issuecomment-469067145 being the expected replacement), so I'd close this as wontfix.

**Comment by Mark-Simulacrum** [comment]
That sounds reasonable. Closing.
