### ISSUE TITLE
stringify! space adds strange space before :tt symbol

### ISSUE THREAD

**Issue by stevenroose** [rust-lang/rust#65940]
Ok sorry for the strange title at first, that was my search query entered in a wrong text box.

So I'm trying to use a macro to use a string and prefix it for usage in a build tag.

But the issue is quite well summed up in this code snippet: 

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=9905252de14993fa6a31b3c73c5d0a01

The result is `prefix_ doe`. Note the space.

Seems to be related to https://github.com/rust-lang/rust/issues/55658. But in his example he does some much more complex things.

**Comment by ExpHP** [comment]
Yes.  You stringified two tokens, so the output has a space to ensure there are two separate tokens.

If you need to concatenate identifiers, look at the [`paste` crate](https://docs.rs/paste/0.1.6/paste/).
