### ISSUE TITLE
Error in cross compile: linking with `C:\msys64\mingw64\bin\x86_64-w64-mingw32-gcc.exe` failed: exit code: 1

### ISSUE THREAD

**Issue by bluretrece** [rust-lang/rust#65988]
Hi, I'm currently trying to run the [triangle example by Vulkano-rs](https://github.com/vulkano-rs/vulkano-examples), unfortunately I'm getting the following error:
```
   Compiling rand_jitter v0.1.4
   Compiling time v0.1.42
   Compiling winit v0.19.4
   Compiling vulkano-shaders v0.13.0
   Compiling rand v0.6.5
   Compiling jpeg-decoder v0.1.16
   Compiling cgmath v0.17.0
   Compiling image v0.21.3
   Compiling vulkano-win v0.13.0
error: linking with `C:\msys64\mingw64\bin\x86_64-w64-mingw32-gcc.exe` failed: exit code: 1

```

[Full error here](https://pastebin.com/0VghdUvJ)

[I followed this workaround](https://github.com/rust-lang/rust/issues/47048) by peope who faced a similar issue, but I didn't had luck. 

I'm trying to cross compile using: `cargo build --target x86_64-pc-windows-gnu --bin triangle`. My current toolchain is `stable-x86_64-pc-windows-msvc`. I have `C:\msys64\mingw64\bin` in my PATH. 

This is inside my `./cargo./config` file: 
```
[target.x86_64-pc-windows-gnu]
rustflags=["-Clink-arg=-lworkaround_47048"]
linker="C:\\msys64\\mingw64\\bin\\x86_64-w64-mingw32-gcc.exe"
ar="C:\\msys64\\mingw64\\bin\\ar.exe"
```
What am I missing? What am I doing wrong? I'm running out of ideas. I kindly ask for suggestions.

**Comment by mati865** [comment]
Root issue has been fixed by https://github.com/rust-lang/rust/pull/67429 and this is not the place to report issues like this one anyway.
