### ISSUE TITLE
Some points about documentation (generator)

### ISSUE THREAD

**Issue by flip111** [rust-lang/rust#65984]
Hello, i'm (still) new to rust. There are some points i notice about the documentation that are strange to me.

I will take this documentation https://docs.rs/image/0.22.3/image/ as example

1. The crate description has a little `[-]` in front of it when i click on it the description just disappears. Why add this thing to the page to hide documentation? Maybe it's personal taste that i like less noise in the page.
2. Following there are Re-exports, Modules, Structs, Enums, Traits. Functions and Type definitions. I thought structs and enums are types, why is "type definition" in a different category?
3. There is no chapter in the rust book how to browse the documentation.
4. The documentation has no linearity about "how to get started". I think this is not just because the example crate (image) does not have a "how to get started" section. But also that the doc generator tool does not seem to encourage this somehow in the page design it outputs. And also because the types and functions don't always point to each other (could this be deduced?) Some possible paths the reader can take:
    1. Start with data, let's see about an `RgbImage` which is an alias to `ImageBuffer` it seems. This struct has a method `from_raw` which seems usable (no guidance if this is the right starting point).
    2. Start with function `load` `Create a new image from a Reader`. Looks goods, but i don't have a reader (link missing).
    3. Turns out the reader is hidden in `io | Input and output of images.`. With a nice description but not describing `load` (found this by browsing source code on github as opposed to just reading the docs)
5. Would be nice if the docs gave some explanation about themselves. I see `Auto Trait Implementations`, what is that? There is no link to look it up. When i search the rust book for `auto trait` i don't get clear results either.
6. Can someone explain why people would want to read about re-exports of other modules before reading about the modules in the crate itself ? IMO modules is like "table of contents" for the crate.
7. double `[+]` usage in https://docs.rs/image/0.22.3/image/io/struct.Reader.html#blanket-implementations When clicking `[+]` you get a bar saying `[+] Show hidden documentation items`. Can the first `[+]` not just display it without requiring the second plus?
8. It's not possible to look (not search when you know a keyword) for, example, a function. This is because functions are tucked away in modules. I can not get a list of functions with the module where to find it. I think the documentation is optimized for how the source files are laid out and not necessarily for finding information within them. PHP documentation is so clear on this, for example take this list https://www.php.net/manual/en/ref.image.php yes it's a long read, but after reading it or just a glance if that is enough for you, you have a pretty good idea what this extension can do. When i read rust documentation it's like spaghetti of pages linking to each other until it doesn't and then you go to github to follow along in source code with examples (if there are any). I mean the documentation looks nice and tidy and everything is grouped in it's category, but when you start clicking it and using it, it becomes messy and you have 20 tabs in your browser.

I understand the need for modules to make code ... well modular. But when using them are they like a mini crate in a crate or just some namespace the author need it to dump some code in. Well it depends i guess. But when you just want to use some function you don't really care from which module to use it. It's only when you start treating modules as table of contents and try to find your functions that way (by browsing all the modules individually to see what functions they have).

I think because the documentation was written by people who already know rust really well. And because the rust book is there specifically to teach rust. That it was forgotten that the documentation also needs to have it's "onboarding of new users" and not just the book.

**Comment by Ixrec** [comment]
I believe the "Type Definitions" section is specifically about type _aliases_. That could definitely be improved.

**Comment by workingjubilee** [comment]
Without disagreeing with the (correct) observation that the documentation could be better integrated, the `[-]`/`[+]` expander/collapser, while it might seem trivial, really does assist navigating documentation, especially big documentation, but it's meant to be combined with the settings you can find from every crate: https://docs.rs/async-std/0.99.11/settings.html 

You might want to toggle all of those off.

**Comment by awoimbee** [comment]
Please close.
This is not an issue but multiple issues, there is no way to correctly address all of these points in one place.

Nevertheless, I tried to address all of the points:
- 1: useful for big text blocks
- 2: please open an issue about "type definitions" not matching the correct chapter in the rust book ("Creating Type Synonyms with Type Aliases").
- 3: There is no chapter in the documentation about how to use a computer (open separate issue if you're adamant)
- 4: most crate have at least an example section, look at the new version of image. Other talking points are related to the image crate, not rustdoc
- 5: open separate issue
- 6: re-exports are part of the table of content
- 7: its one idiosyncrasy that makes sense when you take everything into account (open separate issue)
- 8: open a feature request

**Comment by flip111** [comment]
Thanks for the review.
