### ISSUE TITLE
Document intra-rustdoc links in the unstable book

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#66000]
https://github.com/rust-lang/rust/issues/43466

Also figure out where the docs belong when it stabilizes.

The implementation has diverged a bit from the original RFC (rust-lang/rfcs#1946). We should have some good docs on all the syntaxes supported.

cc @clarfon 

This issue has been assigned to @rcoh via [this comment](https://github.com/rust-lang/rust/issues/66000#issuecomment-605071840).

**Comment by jegacs** [comment]
Hi, I'm surfing throughout the getting started issues so I can conritbute for the first time, does this still need help?

**Comment by LeSeulArtichaut** [comment]
I'd like to take a look at this

@rustbot claim

**Comment by LeSeulArtichaut** [comment]
Oh, @jegacs do you still want to do this? Sorry, I missed your comment 😕

**Comment by jegacs** [comment]
Yeah, I would be happy to help. But I found a little bit hard to understand what issues are still looking for help. I am completley new to rust so even tho this is a easy issue perhaps it will take me a little bit more time, if you find you can fix this quick, go ahead.

**Comment by LeSeulArtichaut** [comment]
I think everyone is in the same position. But go ahead, take this
@rustbot release-assignment
