### ISSUE TITLE
Suggest adding feature when a function / method / module defined behind such feature and it's not enabled

### ISSUE THREAD

**Issue by upsuper** [rust-lang/rust#66034]
When I was trying to migrate my crate to reqwest 0.10, there is a confusing compile error stating
> error[E0599]: no method named `json` found for type `reqwest::async_impl::request::RequestBuilder` in the current scope

I had a brief look at the doc and could still find it. I eventually realized that it requires an additional feature `json` (as the doc correctly points out but overlooked by me).

I believe the compiler should have enough information about functions / method / module which are defined behind a feature, so it can probably step in and suggest such feature for this kind of errors so that people don't need to check code or even `Cargo.toml` of the crate to know what to do.

**Comment by estebank** [comment]
Fixed by https://github.com/rust-lang/rust/pull/109005
