### ISSUE TITLE
hide RUST_BACKTRACE note if RUST_BACKTRACE=0

### ISSUE THREAD

**Issue by jdxcode** [rust-lang/rust#66039]
I love how rust tells me to how to show the full backtrace:

```
❯ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.00s
     Running `target/debug/variables`
thread 'main' panicked at 'assertion failed: false', src/main.rs:2:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

However, if I've set `RUST_BACKTRACE=0` (as opposed to not having the env var set) I feel it should hide that message to tidy up the output.

**Comment by Aaron1011** [comment]
I don't think this is a good idea. The usermight not be aware that `RUST_BACKTRACE=0` - it could have come from a shell .rc file, or a `source`'d shell script.

**Comment by Ixrec** [comment]
Since panics should only happen in rare and unexpected situations, I also think the tradeoffs here favor always showing the notice even if `RUST_BACKTRACE` somehow ended up set to 0 instead of unset.
