### ISSUE TITLE
error during test parsing when there is no whitespace

### ISSUE THREAD

**Issue by JesterOrNot** [rust-lang/rust#66064]
When there is not whitespace during parse I get this message
thread 'main' panicked at 'byte index 4 is out of bounds of `6+5`', src/libcore/str/mod.rs:2051:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
here is the repo
https://github.com/JesterOrNot/MathLang
open in gitpod: https://gitpod.io/#https://github.com/JesterOrNot/MathLang
![image](https://user-images.githubusercontent.com/50386709/68090090-7f103080-fe35-11e9-923d-5dc99c61a915.png)

**Comment by nicokoch** [comment]
Well, the highest index of "6+5" is 2. This is a bug in your code, not in rustc.

**Comment by JesterOrNot** [comment]
K cool!
