### ISSUE TITLE
Complete move to "diagnostic items"

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#66075]
With https://github.com/rust-lang/rust/pull/60966, we can avoid lang items and manual path matching for lints, and instead mark them in the code. But I think there are some places that could still be ported to the new system:

* [ ] The `InvalidValue` lint uses `match_def_path` for `transmute` -- somehow, using a diagnostic item did not work (`is_diagnostic_item` returns false).
* [x] Aren't `Rc` and `Arc` lang items just for diagnostics? Here's where they get used: https://github.com/rust-lang/rust/blob/f49f38871389041671cc710a044e8360091840a3/src/librustc_typeck/check/expr.rs#L879-L880
    And, indirectly, at
    https://github.com/rust-lang/rust/blob/f49f38871389041671cc710a044e8360091840a3/src/librustc_mir/borrow_check/error_reporting.rs#L720-L723
    So, I am not sure if those should be lang items or diagnostic items now? No language semantics is attached to them, the uses above are just in error messages from what I can see. 
* [x] There's also no language semantics attached to `MaybeUninit`; it is a lang item because it gets used in layout construction for generators. Doesn't really fit "diagnostics item" either, though. (EDIT: decided this makes more sense to remain a lang item)

@oli-obk @Centril any thoughts?

**Comment by Centril** [comment]
> So, I am not sure if those should be lang items or diagnostic items now? No language semantics is attached to them, the uses above are just in error messages from what I can see.

If they are only used in diagnostics then they shouldn't be lang items.

> * There's also no language semantics attached to `MaybeUninit`; it is a lang item because it gets used in layout construction for generators. Doesn't really fit "diagnostics item" either, though.

A reasonable argument could be made for "layout construction for generators" => language semantics attached; but it's a sort of code-reuse that's going on in layout construction... something with similar semantics as compared to `MaybeUninit<T>` could ostensibly be used instead. cc @tmandry
