### ISSUE TITLE
Document the maximum and minimum values of each number type

### ISSUE THREAD

**Issue by yoshuawuyts** [rust-lang/rust#66099]
Values such as [`u8::MAX`](https://doc.rust-lang.org/std/u8/constant.MAX.html) are nice when coding because they capture the max allowed value of a number without needing to hard-code it yourself, or apply tricks to compute it.

However when trying to decide which number type to use, it'd be nice to have a plain-text definition of the number types in the documentation. Because even [clicking through to the source](https://doc.rust-lang.org/src/core/num/uint_macros.rs.html#11) does not yield the information you're looking for.

I think this would be a small change that could make getting used to Rust's number types significantly easier. Thanks!

## Screenshots
![Screenshot_2019-11-05 std i8 MAX - Rust](https://user-images.githubusercontent.com/2467194/68172387-9ce5ae80-ff77-11e9-8c69-8936be2285d2.png)
_Rust's `MAX` docs don't contain much information currently. It seems like it wouldn't be too bad to add a bit more to it._

**Comment by Manishearth** [comment]
We should also do this for some of the other constants that are floating around (like EPSILON)

If we do this for usize we should make sure to mention both values

Some of these are macro generated, so this could be a bit tricky to get right!

**Comment by Mark-Simulacrum** [comment]
I suspect the macro bit is actually maybe leading to the problem here -- I seem to recall something going by recently about constants getting pretty-printed into metadata, which I assumed meant we were rendering their values in rustdoc. Maybe the macros are leading to that not happening?

That won't help for usize/isize I guess but I think it would be good to look into this theory for the other types at least a bit

**Comment by Manishearth** [comment]
I don't think we ever show constant values in rustdoc. Would be nice to, but there are a bunch of tricky bits.

**Comment by varkor** [comment]
> I don't think we ever show constant values in rustdoc.

Unstably, we show constant values for const generics, so we need to handle const value printing in rustdoc anyway. It's not perfect yet, but it works in most simple situations. We should be able to use the same infrastructure to print `const` values.

**Comment by Otolock** [comment]
I would be interested in adding this for at least for the integer types listed in [the book](https://doc.rust-lang.org/book/ch03-02-data-types.html#integer-types). What is the preferred way that this look like on the documentation? 

Something like:
> The largest value that can be represented by this integer type: -128

Or 

> The largest value that can be represented by this integer type.
>> -128

Or would it be similar to the documentation for the [primitive type i8's `min_value()` function](https://doc.rust-lang.org/std/primitive.i8.html#method.min_value), where an `assert_equal` is used to state the expected value?

**Comment by Otolock** [comment]
cc @steveklabnik

**Comment by steveklabnik** [comment]
IMHO, the former is simpler and straightforward, seems good to me.

**Comment by segfaultsourcery** [comment]
I wouldn't mind taking this on, if it's not already taken.
