### ISSUE TITLE
Minor typo in explanation for `E0080` in `Rustc error index`

### ISSUE THREAD

**Issue by JOE1994** [rust-lang/rust#66105]
# Content Bug Report

## Page(s) Affected
https://doc.rust-lang.org/error-index.html#E0080

## What needs to be fixed?
A minor grammar mistake. (Below) **'an'** needs to be changed to **'a'**.

> This error indicates that the compiler was unable to sensibly evaluate **an** constant expression that had to be evaluated.

## P.S.
Error message from **rustc 1.40.0-nightly(2477e2493 2019-11-04)** (invoked with `rustc --explain E0080`) also contains the same typo, so should I also report this issue to the [Rust repository](https://github.com/rust-lang/rust)?

**Comment by Manishearth** [comment]
Yes, this belong on the other repository. Moving

**Comment by JOE1994** [comment]
I can take care of this :smile:

**Comment by JOE1994** [comment]
https://doc.rust-lang.org/error-index.html#E0080

Typo still shows in the above link. I am currently not sure what I can do to fix it.

**Comment by Manishearth** [comment]
That link will get fixed when your changes hit stable.

You'll see it first on https://doc.rust-lang.org/nightly/error-index.html
the next time a nightly happens.
