### ISSUE TITLE
async-block diagnostics do not suggest async move when it may be needed

### ISSUE THREAD

**Issue by WildCryptoFox** [rust-lang/rust#66107]
[(playground)](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=3d75e33c51d66cd9dd7a95d71648a5cd)

```rust
//* f hits lifetime errors
fn f(a: &usize) -> (impl '_ + Future<Output = ()>, &usize) {
    (async { *a; }, a)
}
// */

// g compiles as expected
fn g(a: &usize) -> (impl '_ + Future<Output = ()>, &usize) {
    async fn h(a: &usize) { *a; }
    (h(a), a)
}
```

```
error[E0515]: cannot return value referencing function parameter `a`
 --> src/main.rs:5:5
  |
5 |     (async { *a; }, a)
  |     ^^^^^^^^^^-^^^^^^^
  |     |         |
  |     |         `a` is borrowed here
  |     returns a value referencing data owned by the current function
```

This issue has been assigned to @gizmondo via [this comment](https://github.com/rust-lang/rust/issues/66107#issuecomment-610613109).

**Comment by WildCryptoFox** [comment]
Flipped problem. Works for async-block but not async-fn. [(playground)](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=07972711607de8902f99c456d8824742)

```rust
async fn f(_: &Cell<usize>) {}
fn g(_: &Cell<usize>) -> impl Future<Output = ()> {
    async {}
}

fn check<F, T>(f: fn(&Cell<T>) -> F, t: &mut T) -> F
where
    F: Future<Output = ()>,
{
    f(Cell::from_mut(t))
}

fn main() {
    // fails
    check(f, &mut 0);
    // works
    check(g, &mut 0);
}
```

**Comment by nikomatsakis** [comment]
The error is correct, so what we are looking for here is a diagnostic improvement. The problem is that `async { *a }`, much like a closure, defaults to borrowing `a` in place -- so when we try to return, it has a reference to `a` as `a` is going out of scope. 

To fix the error, you need `async move` ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=1ac9f7457fc3910dfc33965236871b65)). 

The situation is exactly analogous to closures and move closures. Note that in the analogous closure example ([playground]()), we give a different error, complete with a suggestion:

```
error[E0373]: closure may outlive the current function, but it borrows `a`, which is owned by the current function
 --> src/main.rs:5:6
  |
5 |     (|| { *a; }, a)
  |      ^^    - `a` is borrowed here
  |      |
  |      may outlive borrowed value `a`
  |
note: closure is returned here
 --> src/main.rs:5:5
  |
5 |     (|| { *a; }, a)
  |     ^^^^^^^^^^^^^^^
help: to force the closure to take ownership of `a` (and any other referenced variables), use the `move` keyword
  |
5 |     (move || { *a; }, a)
  |      ^^^^^^^
```

It seems like we should adapt the `async { }` case to be closer to the closure wording.

**Comment by nikomatsakis** [comment]
Marking this as OnDeck since it seems like this might be a common mistake, and I think the fix should be relatively straightforward.

**Comment by WildCryptoFox** [comment]
Ah thanks @nikomatsakis this makes sense.

**Comment by tmandry** [comment]
Ping from triage. @gilescope are you working on this?

**Comment by tmandry** [comment]
Ping. @gilescope are you interested in continuing to work on this, or should I un-assign?

**Comment by nikomatsakis** [comment]
@rustbot claim

I'm going to "claim" this issue, but only to write mentoring instructions! If anybody is interested in taking a crack at it, I'd be happy to help.

**Comment by gilescope** [comment]
Sorry - if anyone else wants it that’s cool. I seem to have fingers in quite a few pies at the moment.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by nikomatsakis** [comment]
@gizmondo thanks!!
