### ISSUE TITLE
rustc: can't find macros and others when compiling Redox 0.5.0

### ISSUE THREAD

**Issue by tomasritter** [rust-lang/rust#66124]
Have a problem with compiling an older Redox version. 
I'm on Ubuntu 19.04, rustc version doesn't seem to matter (2018-08 and up), xargo 0.3.13-16. 

Error output:
[out.txt](https://github.com/rust-lang/rust/files/3810321/out.txt)

**Comment by Mark-Simulacrum** [comment]
It looks like you're compiling with a std/core that isn't compatible with the compiler you're using (i.e., `lang = "va_list"` needs to be defined). I don't believe that this is a compiler bug so I'm going to close; I suspect you want to file this with redox itself (they likely know more about it than we do)...
