### ISSUE TITLE
Raw ident suggestion should only trigger if the code is otherwise well-formed

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#66126]
Right now the raw ident suggestion when using a reserved keyword somewhere where it is not allowed is context free, leading to misleading output:

https://twitter.com/isislovecruft/status/1191768296590315520

The parser should perform some lookahead to see if it could actually continue parsing if a raw identifier had been supplied in its place and if so, only then suggest raw idents.

**Comment by petrochenkov** [comment]
Or we shouldn't suggest using raw identifiers if we cannot do that easily *and* reliably.
