### ISSUE TITLE
MIR inlining does not handle `SourceScopeLocalData`

### ISSUE THREAD

**Issue by Aaron1011** [rust-lang/rust#66137]
During the MIR inlining pass, we add scopes from the callee to `Body.source_scopes` in the caller. However, we do not update `source_scope_local_data`, which causes any inlined scopes to have no entry in the caller `source_scope_local_data`. This causes an [ICE in Miri](https://github.com/rust-lang/rust/issues/66077) when we try to generate a stacktrace - however, the ICE occurs in rustc code, so it's possible that we might run across this without Miri.

**Comment by eddyb** [comment]
Sounds like a simple enough omission, but I'm surprised this doesn't break any of our `mir-opt` tests.

**Comment by Aaron1011** [comment]
I don't think this is `E-Easy` - `source_scope_local_data` is crate local, and it's not immediately obvious to me what the correct beehvaior is for cross-crate inlining.

**Comment by eddyb** [comment]
@Aaron1011 Oh, I thought the concern was entirely about same-crate, sorry!

I think the fix in that case is to move the `ClearCrossCrate` inward, i.e. change `SourceScopeData` to contain a `ClearCrossCrate<SourceScopeLocalData>` - I don't think the size of `SourceScopeData` is critical (but we should run perf anyway).

**Comment by Aaron1011** [comment]
@eddyb: `SourceScopeData` doesn't contain `SourceScopeLocalData`. Your change would require wrapping both fields of `SourceScopeLocalData` in `ClearCrossCrate`, since `SourceScopeLocalData` is stored in an `IndexVec` in `Body.source_scope_local_data`

**Comment by Aaron1011** [comment]
Oops, I misread your proposal - you were talking about *changing* `SourceScopeData` to contain a `SourceScopeLocalData`. I'll try that.

**Comment by oli-obk** [comment]
This was fixed in https://github.com/rust-lang/rust/pull/66789 as far as I can tell
