### ISSUE TITLE
error[E0463]: can't find crate for `rustc`

### ISSUE THREAD

**Issue by hermanventer** [rust-lang/rust#66130]
As of rustc 1.40.0-nightly (10a52c25c 2019-10-24) I can no longer compile MIRAI. See https://github.com/facebookexperimental/MIRAI/pull/334 and https://travis-ci.com/facebookexperimental/MIRAI/jobs/252884062.

Interestingly, it compiles just fine on my laptop. It is only the Travis CI build that fails for me. It seems unlikely that this is an intentional change.

Looking at the change logs, it seems that https://github.com/rust-lang/rust/commit/175d325ccbaccf40907a8bb8184ee65a5f62ca8a#diff-70b2d0110e1bf5edce7452fb1e35ec9b might be at least a proximate cause for this.

If there is a better way for me to plug into the rust compiler, I'll be glad to do so.

**Comment by Mark-Simulacrum** [comment]
I suspect that this is because you need to add the `rustc-dev` component.

**Comment by hermanventer** [comment]
Thanks that does the trick. I failed to notice that Travis installs rustc with --profile=minimal.
