### ISSUE TITLE
Introduce a crate for common AST definitions

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#66149]
Context: https://github.com/rust-lang/rust/pull/65884#issuecomment-550192118

For example:

- `Mutability` is shared between AST / HIR / ...
- `CaptureBy` and `CaptureClause` fill the same role.
- `Constness`
- `Unsafety`
- `Movability` and `GeneratorMovability` (?)
- `BindingMode`

Suggested crate name `rustc_ast_common`.

cc @oli-obk

**Comment by cjgillot** [comment]
Hi,

I would like to do that if you don't mind.
I will try to submit a draft during the weekend.

**Comment by oli-obk** [comment]
wrt to creating a global crate, we should hold up on that. Merging types where no new crate is needed is uncontroversial I believe, but adding a new crate just for this should be discussed first

**Comment by Centril** [comment]
Closing as moot for the time being.
