### ISSUE TITLE
Using wasm32-wasi target to create WASM for stand-alone WASM Virtual Machine

### ISSUE THREAD

**Issue by tpmccallum** [rust-lang/rust#66177]
I am compiling the following code for use in WASM implementation.

```
#[no_mangle]
pub extern fn adding(a: u32, b: u32) -> u32 {
    a + b
}
```
When I compile with wasm32-wasi target and try to execute in [a stand-alone WASM VM](https://github.com/WAVM/WAVM) called (WAVM) I get [an error](https://github.com/WAVM/WAVM/issues/219).

```
Failed to link module:
Missing import: module="wasi_unstable" export="fd_write" type="func (i32, i32, i32, i32)->i32"
```

My code does compile in Rust (using the wasm32-wasi target) without any issues and I do get the `(import "wasi_unstable" "fd_write" (func $fd_write (type 7)))` text in my wat.

I would just like to open up some communication about using Rust -> WASM in a non-browser environment. Specifically, using WASM in a stack-based Virtual Machine as apposed to a runtime environment (i.e. Lucet etc). A question being, what are the bare minimum standards which both wasm32-wasi and WAVM can both implement to enable Rust programmers to execute their code on WAVM?
 
Thank you

**Comment by sfackler** [comment]
The `wasm32-unknown-unknown` target is a better choice if you want to use WASM without a standardized runtime.

**Comment by tpmccallum** [comment]
Thank you @sfackler 
It turns out that I was using --abi=bare when executing WAVM command. It turns out that `--abi=bare` is meant to let you execute a module without giving it access to WASI or any other host functionality.
I used `--abi=wasi` thanks to some advice and it all worked out.
I can now do the following
Write this Rust
```
#[no_mangle]
pub extern fn main(a: i32, b: i32) {
    let z = a + b;
    println!("The value of x is: {}", z);
}
```
Build it with a target `wasm32-wasi`
Then run this
```
wavm run --abi=wasi --function=main ~/add_numbers_via_wavm/target/wasm32-wasi/release/adding_lib.wasm 2 2
```
Which returns the following output
```
The value of z is: 4
```
Thanks for the response!
Kind regards
Tim
