### ISSUE TITLE
[Installing rust] Small suggestion for possible improvement

### ISSUE THREAD

**Issue by rubyFeedback** [rust-lang/rust#66193]
Hey there,

I am on linux but I managed to break my local openssl installation. I will fix this later,
but I was also trying to compile librsvg, and this needs rust, so I needed rust.

I went this way:

  curl https://sh.rustup.rs -sSf | sh

But this then failed via:

-> 

info: profile set to 'default'
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: latest update on 2019-11-07, rust version 1.39.0 (4560ea788 2019-11-04)
info: downloading component 'cargo'
  4.7 MiB /   4.7 MiB (100 %)   4.7 MiB/s in  1s ETA:  0s
info: downloading component 'clippy'
  1.8 MiB /   1.8 MiB (100 %) 431.0 KiB/s in  1s ETA:  0s
info: downloading component 'rust-docs'
 11.8 MiB /  11.8 MiB (100 %) 783.4 KiB/s in 23s ETA:  0s
info: downloading component 'rust-std'
176.4 MiB / 176.4 MiB (100 %)   2.6 MiB/s in  4m  6s ETA:  0s     
info: downloading component 'rustc'
 43.1 MiB /  66.3 MiB ( 65 %) 938.0 KiB/s in  2m 37s ETA: 25serror: component download failed for rustc-x86_64-unknown-linux-gnu
error: caused by: could not download file from 'https://static.rust-lang.org/dist/2019-11-07/rustc-1.39.0-x86_64-unknown-linux-gnu.tar.xz' to '/root/.rustup/downloads/5b2a435a4c034615d70cfc383abe9924cbd1ffd4669caa55ce6539f22ed979ed.partial'
error: caused by: error reading from socket
error: caused by: timed out

I think it failed due to requiring https.

I then went to simply download rustup-init, and this one worked fine. So the only real
issue here for me is one of convenience, the more "manual" work via rustup-init
worked fine, but the https variant worked not so well.

I have usability suggestions:
1) Check whether https can actually work here or not prior to trying. This should
be quite simple, e. g. test whether the above error (time out) may happen, and
if so respond on it.
2) More importantly than 1, though, I would suggest also displaying the URL
towards rustup-init, and perhaps some notification such as "your installation of
openssl does not appear to be working" or something like that. The URL may
be useful for people similar to my position where the install fails.

Normally the above works fine, but not right now with my broken openssl. :P

Wget has a --no-check certification option or so; I use this to still be able to
download stuff, even with a broken openssl, and it works. I'd like for rust to
also have something like this available if possible, because as the example
above shows, the manual download via rustup-init actually works fine, so
the issue for my use case is simply one of convenience. If you want to go
fancy, you could also add another menu that asks the users whether he
wants to download rustup-init instead (but this may be more difficult
to test for all platforms ... or more work ... so i am not sure if that one is
worth to change since it may not affect lots of people - but indicating
the URL in case of failure may be not too much extra work, so it could
happen easily).

The URL I was then using was this one here btw:

https://forge.rust-lang.org/infra/other-installation-methods.html

And rustup-init from there worked fine. (Not sure why it may fail
in the other case ... one could try to download again without https,
just simple http, but no idea if the rust team wants to do so - 
everyone is so focused on security, even if security means that
you can not get anything installed automatically and instead
have to go through it manually ;) )

**Comment by csmoe** [comment]
thanks for reporting, but this is more like a https://github.com/rust-lang/rustup.rs/issues issue, could you request an improvement there?
