### ISSUE TITLE
Add From<NonZero*> impls for wider NonZero types

### ISSUE THREAD

**Issue by newpavlov** [rust-lang/rust#66196]
For example in `getrandom` to convert `NonZeroU16` to `NonZeroU32` we have to write code like this:
```rust
num::NonZeroU32::new(e.get() as u32).unwrap().into()
```
Instead of using a simple `e.into()`.

This issue has been assigned to @peter-wilkins via [this comment](https://github.com/rust-lang/rust/issues/66196#issuecomment-553191408).

**Comment by c3st7n** [comment]
Opened a PR for this (https://github.com/rust-lang/rust/pull/66479), but I just noticed it was supposed to be assigned to @peter-wilkins, aplogies I hadn't noticed this.

**Comment by c3st7n** [comment]
I must have branched from an old commit or similar, will fix.

**Comment by newpavlov** [comment]
Fixed in #66277.
