### ISSUE TITLE
1.39 error messages don't properly truncate, making autogenerated files (e.g. bindgen) spam the terminal

### ISSUE THREAD

**Issue by q66** [rust-lang/rust#66229]
A paste is worth a thousand words, even if it has many thousands of words itself: https://gist.githubusercontent.com/q66/7004995a784b59475134a290512cf545/raw/a42c4af7648c142175c5244494f74d30dfe1b340/gistfile1.txt

**Comment by q66** [comment]
Actually, the source file appears to be one line. It's generated by rust-bindgen.

**Comment by q66** [comment]
Here's the generated file from firefox: https://gist.githubusercontent.com/q66/ac25123ed168f61e2972af0bbc90fff0/raw/229094c3e8dfda7382eec22563d08538eaf83c03/gistfile1.txt

**Comment by estebank** [comment]
https://github.com/rust-lang/rust/pull/63402 implements the feature, but it needs to be integrated with `cargo`.

**Comment by est31** [comment]
See also the bindgen bug: https://github.com/rust-lang/rust-bindgen/issues/1600

I've added some pretty-printing code to my own project: https://github.com/RustAudio/deepspeech-rs/commit/3323b0e228608fc00e876a4712a4139959aee119 

Optimally it would live in bindgen though. Want to port it to bindgen, @q66 ?

**Comment by q66** [comment]
no thanks, i have enough of my own work and prefer to touch this kinda stuff as little as possible. For now, I took patches from Gentoo to fix compilation of firefox/thunderbird (and adapted it for other stuff so that e.g. icecat can also build), which seems to work ok.

**Comment by estebank** [comment]
I believe all of the work necessary here has been completed. Extremely long types in messages are now truncated and written to disk, and cargo passes through the terminal's width to `rustc` to truncate the code window in diagnostics.
