### ISSUE TITLE
rust 1.39.0 bootstraping error: found two different crates with name `bitflags` that are not distinguished by differing `-C metadata`

### ISSUE THREAD

**Issue by aplanas** [rust-lang/rust#66224]
Hi,

I am trying to update rustc from 1.38 to 1.39 in openSUSE, and for some architectures I have a consistent error:

```
[ 5912s]    Compiling rustdoc v0.0.0 (/home/abuild/rpmbuild/BUILD/rustc-1.39.0-src/src/librustdoc)
[ 5913s] error[E0523]: found two different crates with name `bitflags` that are not distinguished by differing `-C metadata`. This will result in symbol conflicts between the two.
[ 5913s]   --> src/librustdoc/html/markdown.rs:36:5
[ 5913s]    |
[ 5913s] 36 | use pulldown_cmark::{html, CowStr, Event, Options, Parser, Tag};
[ 5913s]    |     ^^^^^^^^^^^^^^
[ 5913s] 
[ 5913s] error: aborting due to previous error
[ 5913s] 
[ 5913s] error: could not compile `rustdoc`.
[ 5913s] warning: build failed, waiting for other jobs to finish...
[ 5914s] error: build failed
```

For example:

https://build.opensuse.org/package/live_build_log/home:aplanas:branches:devel:languages:rust/rust/openSUSE_Tumbleweed/x86_64

and 

https://build.opensuse.org/package/live_build_log/home:aplanas:branches:devel:languages:rust/rust/openSUSE_Tumbleweed/i586

I noted that this is happening in some architectures when 1.38 is used to compile 1.39, and in all architectures when 1.39 is used to compile 1.39.

Is this a known issue? Any place where I can start digging into?

Thanks!

**Comment by mati865** [comment]
You will want to backport https://github.com/rust-lang/rust/commit/73369f32621f6a844a80a8513ae3ded901e4a406

cc https://github.com/rust-lang/rust/issues/65795 @Mark-Simulacrum

**Comment by Mark-Simulacrum** [comment]
Yep, sorry for this breakage, we still don't really understand what caused it (haven't spent time investigating) but the patch is a known fix :)

Closing.

**Comment by aplanas** [comment]
Thanks! Is already backported, and OBS is now building the new package.
