### ISSUE TITLE
Code formatting question

### ISSUE THREAD

**Issue by dingelish** [rust-lang/rust#66237]
Hi there, I'm looking into libcore and find some formatting issues, such as

```diff
diff --git a/src/libcore/alloc.rs b/src/libcore/alloc.rs
index 1b06baeb711..01d15a45cc4 100644
--- a/src/libcore/alloc.rs
+++ b/src/libcore/alloc.rs
@@ -7,9 +7,9 @@
 use crate::cmp;
 use crate::fmt;
 use crate::mem;
-use crate::usize;
-use crate::ptr::{self, NonNull};
 use crate::num::NonZeroUsize;
+use crate::ptr::{self, NonNull};
+use crate::usize;
```

```diff
-impl dyn Any+Send {
+impl dyn Any + Send {
```

Wonder if such fixes are welcome. Thanks!

**Comment by Mark-Simulacrum** [comment]
Generally speaking, we try to keep pure formatting PRs to a minimum as they cause unnecessary churn, so the answer is mostly no. We are currently working on integrating rustfmt into CI and formatting the repository, though, so hopefully that'll resolve most of these automatically :)
