### ISSUE TITLE
Find a better way to hook panic starting from Miri

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#66247]
With https://github.com/rust-lang/rust/pull/60026, Miri support unwinding. To this end it needs to hook into the code that libstd uses to start unwinding. The lowest "funnel" that all unwinding goes through is `__rust_start_panic`, which is an FFI import in libstd which is then implemented by either `libpanic_abort` or `libpanic_unwind`. However, hooking that in Miri is a bad choice as for unwinding, we need to still run the following code to get the panic payload into the shape that `__rust_maybe_catch_panic` expects:

```rust
pub unsafe extern "C" fn __rust_start_panic(payload: usize) -> u32 { 
    let payload = payload as *mut &mut dyn BoxMeUp; 
    imp::panic(Box::from_raw((*payload).box_me_up())) 
} 
```
Emulating this code in Miri is a big mess, so instead we right now use `cfg(miri)` to overwrite `imp::panic`. The overwritten code than calls an intrinsic, `miri_start_panic`, which is easy to implement in Miri.

This works fairly well but requires collaboration from `libpanic_unwind`, which @eddyb is not happy about. He is proposing a lang item instead, which however I am worried will make the entire panicking story even more messy: there's already at least 2 layers of indirection there where we jump to *whereever* based on what gets linked elsewhere in the crate tree (`panic_handler` and `miri_start_panic`), this would add a third.

Cc @Aaron1011 @oli-obk

**Comment by RalfJung** [comment]
Code compiled for miri (with `--cfg miri`) now no longer runs LLVM codegen, which gives us more freedom in whatever we might want to implement here.

**Comment by RalfJung** [comment]
These days we use an "miri-implemented FFI function" to trigger unwinding. IMO that's not too bad actually. This issue is also not very actionable. so I propose we close it.

@oli-obk what do you think?

**Comment by oli-obk** [comment]
I agree. While I have ideas for these kind of "body is runtime code, miri/ctfe run something differently" kind of functions, we don't need to keep something open that is targetted at just the panic hook
