### ISSUE TITLE
Confusing error message when calling f(AsRef<...>, &str) with (str, &str)

### ISSUE THREAD

**Issue by DevJac** [rust-lang/rust#66258]
The following code produces a confusing error message:
```rust
use std::convert::AsRef;
use std::path::Path;

fn main() {
    foo("bar", &"baz");
    //         ^^^^^^ doesn't have a size known at compile-time???
    // Error message will clearly show that the second argument is the problem,
    // but the first argument is the problem.
}

fn foo(_bar: &dyn AsRef<Path>, _baz: &str) {}
```
[Rust Playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a7239aa6d77e5a590057ad2b7758a6a6)

The confusing error when compiling the above code will be:
```
error[E0277]: the size for values of type `str` cannot be known at compilation time
 --> src/main.rs:5:16
  |
5 |     foo("bar", &"baz");
  |                ^^^^^^ doesn't have a size known at compile-time
  |
  = help: the trait `std::marker::Sized` is not implemented for `str`
  = note: to learn more, visit <https://doc.rust-lang.org/book/ch19-04-advanced-types.html#dynamically-sized-types-and-the-sized-trait>
  = note: required for the cast to the object type `dyn std::convert::AsRef<std::path::Path>`
```
I first observed this error message behavior with Rust 1.39.

**Comment by jonas-schievink** [comment]
Can you explain what exactly you find confusing and why?

**Comment by DevJac** [comment]
The error message says that the _second_ argument in the function call is the problem, but this is not the case. It is the _first_ argument in the function call which is the problem.

Furthermore, the error points exactly at the `&str` value and says it "doesn't have a size known at compile-time", which is confusing because references do have a known size.

**Comment by jonas-schievink** [comment]
Thanks for explaining, that makes sense. Reclassifying as a bug since the span is wrong.
