### ISSUE TITLE
Destructuring of incorrectly defined struct produces ICE

### ISSUE THREAD

**Issue by olegnn** [rust-lang/rust#66270]
Attempt to use destructuring on incorrectly defined struct produces ICE.
Code:
```rust
struct Bug {
    incorrect_field: 0,
}

struct Empty {}

fn main() {
    let Bug {
        any_field: Empty {},
    } = Bug {};
}
```

Output:
```
error: expected type, found `0`
 --> src/main.rs:2:22
  |
2 |     incorrect_field: 0,
  |                      ^ expected type

thread 'rustc' panicked at 'no index for a field', src/libcore/option.rs:1190:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.39.0 (4560ea788 2019-11-04) running on x86_64-unknown-linux-gnu

note: compiler flags: -C codegen-units=1 -C debuginfo=2 --crate-type bin

note: some of the compiler flags provided by cargo are hidden
```
[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=6f9444ac585e746128fc962ebd2c7bab)

**Comment by Lonami** [comment]
There's no need for `struct Empty`, and there's also no need to use a non-existing field. The following also ICEs:
```rust
struct Bug {
    foo: 0,
}

fn main() {
    let Bug { foo: 0 } = Bug {};
}
```

**Comment by olegnn** [comment]
@Lonami thank you for corrections! 👍

> There's no need for struct Empty

I wanted to show that correct nested destructuring produces ICE
```rust 
let Bug { any_field: Empty {} } // correct if we define `any_field: Empty {}` while 
let Bug { foo: 0 } // produces `refutable pattern` any way
``` 
> no need to use a non-existing field

Field `foo` doesn't exist too because it has incorrect definition 😩

Try following code ([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=74b549c1ed1438bd01c3743b9c24069c)): 
```rust
struct Bug {
    foo: 0,
}

fn main() {
    let bug = Bug { foo: 5 };
    bug.foo;
}
```
<details><summary>Spoiler</summary>
<p>

```
error[E0609]: no field `foo` on type `Bug`
 --> src/main.rs:7:9
  |
7 |     bug.foo;
  |         ^^^ unknown field
```

</p>
</details>

> maybe you implied that with "any field"

Exactly, it has name `any_field` because of that 😉

**Comment by Centril** [comment]
cc @matthewjasper since you are working on `MemCategorizationContext`

**Comment by matthewjasper** [comment]
This is fixed by #66246. I'll add a test for this tomorrow.

**Comment by Alexendoo** [comment]
@matthewjasper did the test get added? Looks to me that 0de037c7b69c147f5235b7ee1134c78935a39788 got lost to the ether

**Comment by matthewjasper** [comment]
Oh. I guess not then.
