### ISSUE TITLE
Tracking issue for From<NonZero*> impls for wider NonZero types

### ISSUE THREAD

**Issue by peter-wilkins** [rust-lang/rust#66291]
Tracking issue to convert non-zero integer types to wider non-zero integer types when the underlying type supports the conversion.

For example: 
```
num::NonZeroU32::new(e.get() as u32).unwrap().into()
```
becomes
```
e.into()
```

**Comment by jonas-schievink** [comment]
Impls don't need tracking issues as they cannot be unstable

**Comment by hellow554** [comment]
My fault. Sorry for this! 😕

**Comment by peter-wilkins** [comment]
No worries, I learned something. :smiley: 
Is the PR still OK referencing this issue?
```
#[unstable(feature = "nz_int_conv", issue = "66196")]
```

**Comment by jonas-schievink** [comment]
@peter-wilkins You can mark those impls as stable (since the current nightly version)
