### ISSUE TITLE
ipnet build error

### ISSUE THREAD

**Issue by sallyyu0** [rust-lang/rust#66307]
Getting following errors today, any ideas please?

Compiling lock_api v0.3.1
error[E0658]: use of unstable library feature 'iter_nth_back'
--> /home/zzz/.cargo/registry/src/github.com-1ecc6299db9ec823/ipnet-2.1.0/src/ipext.rs:638:5
|
638 | / fn nth_back(&mut self, n: usize) -> OptionSelf::Item {
639 | | match *self {
640 | | IpAddrRange::V4(ref mut a) => a.nth_back(n).map(IpAddr::V4),
641 | | IpAddrRange::V6(ref mut a) => a.nth_back(n).map(IpAddr::V6),
642 | | }
643 | | }
| |_____^
|
= note: for more information, see #56995

error[E0658]: use of unstable library feature 'iter_nth_back'

...
error: aborting due to 5 previous errors

For more information about this error, try `rustc --explain E0658`.
error: Could not compile `ipnet`.
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by sfackler** [comment]
That method was stabilized in the 1.37 release. You'll need to update your Rust distribution.
