### ISSUE TITLE
Null fat pointers

### ISSUE THREAD

**Issue by elichai** [rust-lang/rust#66316]
Hi,
Currently if you want a null fat pointer you need to do something like this:
```
ptr::null_mut::<[u8;0]>() as *mut [u8]
```
which isn't fun and take a while to find.
I see 2 ways of implementing this in libcore:
1: 
```
pub const fn null_mut_fat<T>() -> *mut [T] {
    null_mut::<[T;0]>() as *mut [T] 
}

pub const fn null_fat<T>() -> *const [T] {
    null::<[T;0]>() as *const [T] 
}
```

2. (Which I think is better because it doesn't bloat more functions)
```
pub fn null<T: ?Sized>() -> *mut T {
    unsafe { MaybeUninit::zeroed().assume_init() }
}
```

The problem is that the second currently isn't possible in a `const fn`. it requires making both `zeroed()` and `assume_init()` `const fn`s, which is physically possible (by making ~4-5 functions `const fn`, the only problem there is the `debug_assert` in `write_bytes`)

But I don't know what's the safety consequences of using intrinsics in `const fn`.
If it is safe I can start PRing some of these functions to be `const fn`.

**Comment by cuviper** [comment]
We have previously decided that Rust's `is_null()` should only depend on the data pointer -- see the discussions in #44932, #46094, and https://github.com/rust-lang/rfcs/issues/433#issuecomment-345495505. The "fat" part of a pointer is trivial for slices, where a 0 length will do fine, but a trait object pointer always needs to have a valid vtable.

**Comment by elichai** [comment]
@cuviper
Are you telling me that `*mut Trait` with a null vtable is UB?

But that's a raw pointer. It should only be UB when dereferenced @eddyb

**Comment by cuviper** [comment]
See also https://github.com/rust-lang/unsafe-code-guidelines/issues/166

**Comment by elichai** [comment]
Github should add a facepalm emoji

**Comment by ExpHP** [comment]
There's more than just dereferencing to worry about here.  It would appear to me that, by requiring the vtable pointer to be non-null, we enable a niche optimization on `Option<NonNull<dyn Trait>>`.

**Comment by Mark-Simulacrum** [comment]
I am closing this in favor of the UCG issue (https://github.com/rust-lang/unsafe-code-guidelines/issues/166). I don't think we're in a position to decide these things on rust-lang/rust issues; the UCG process for now is the best way to provide feedback on these issues.
