### ISSUE TITLE
unused_labels should be reported as warnings

### ISSUE THREAD

**Issue by BartMassey** [rust-lang/rust#66324]
A long while back there was Issue #50751 which pointed out that the compiler was not linting for unused break labels. This resulted after a lot of fantastic hard work in PR #50763 which added the `unused_labels` lint.

At the time, the lint was set to `allow` by default. The consensus was that there would need to be a review and a crater run before it was changed to `warn`. Issue #50751 was closed without this happening, and this is where we stand today.

I'd love to see this changed to `warn` by default. Any chance that could happen?

**Comment by Centril** [comment]
Seems reasonable; want to file a PR? cc @rust-lang/lang

**Comment by BartMassey** [comment]
Working…

**Comment by BartMassey** [comment]
OK, PR #66325 is in the queue. Let me know if I need to do something different. Thanks!
