### ISSUE TITLE
cargo install --frozen tries to access the internet despite vendoring

### ISSUE THREAD

**Issue by stevenroose** [rust-lang/rust#66343]
`cargo install --frozen` with a vendor directory set in `.cargo/config` is updating the crates-io index while it shouldn't do that.

This can currently be solved with `--offline`, but it should not attempt reach out to the internet with `--frozen`.

Also, `--offline` doesn't exist before v1.36.0.

**Comment by ExpHP** [comment]
> Also, `--offline` doesn't exist before v1.36.0.

Neither would any change to this behavior... :P

**Comment by sfackler** [comment]
This should be filed on the rust-lang/cargo repository.

**Comment by stevenroose** [comment]
Sorry. Created https://github.com/rust-lang/cargo/issues/7584.
