### ISSUE TITLE
Use `report_in_external_macro` in internal lints

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#66370]
Filing this since @eddyb had the idea and so that we don't forget.

This issue has been assigned to @afnanenayet via [this comment](https://github.com/rust-lang/rust/issues/66370#issuecomment-570743582).

**Comment by eddyb** [comment]
cc @flip1995 @oli-obk

**Comment by oli-obk** [comment]
It should be as easy (unless I'm overlooking something) as adding `report_in_external_macro: true` to all declare_tool_lint invocations https://github.com/rust-lang/rust/blob/56237d75b4271a8a2e0f47d86ea76ebf6d966152/src/librustc/lint/internal.rs#L53 and then fixing the fallout (changing imports as described by the lint)

**Comment by afnanenayet** [comment]
I'd like to handle this

@rustbot claim
