### ISSUE TITLE
Compiler crash on "if" without "else" in async fn

### ISSUE THREAD

**Issue by guzt** [rust-lang/rust#66387]
```rust
async fn f() -> Result<(), failure::Error> {
    if "a" != "b" {
        return Err("c".to_string());
    }
}

```

([Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=7c50ae4cb0d4169c289cbdeea491a48b))

Triggers on playground on beta and nightly channels, not on stable.

Stacktrace: https://gist.github.com/guzt/32437a394c5c3401f8ec80a6863efe56

**Comment by guzt** [comment]
Even smaller sample (from Dan Johnson):

> async fn f() -> i32 {
>     if true {
>         return 0;
>     }
> }
>

**Comment by pnkfelix** [comment]
triage: P-high. Removing nomination.

**Comment by pnkfelix** [comment]
triage: P-high, removing nomination label.
