### ISSUE TITLE
Feature request: Add a wrapper around fexecve

### ISSUE THREAD

**Issue by danieldulaney** [rust-lang/rust#66404]
`fexecve` is a little-known but very useful Unix (POSIX-2008, implemented on [Linux](https://linux.die.net/man/3/fexecve) and [BSD](https://www.freebsd.org/cgi/man.cgi?query=fexecve&apropos=0&sektion=0&manpath=FreeBSD+12.1-RELEASE+and+Ports&arch=default&format=html)) library function that works just like `execve`, but based on a file descriptor instead of a file name. It would fit nicely into the [`std::os::unix::process::CommandExt`](https://doc.rust-lang.org/std/os/unix/process/trait.CommandExt.html) trait.

It could be added inside `CommandExt` as `fn new_fd(file: &mut File) -> Self` or as `unsafe fn new_fd(fd: RawFd) -> Self`.

Outstanding questions include:
- Should the API call accept a `File` or a `RawFd`?

Potential issues include:
- The Linux man page mentions that it may fail on systems without `/proc` (no mention on the OpenBSD manpage).
- The behavior can be emulated fairly easily (though potentially not zero-cost) by using the existing process spawning features with `/proc/{pid}/fd/{fd}` as the path.

**Comment by jonas-schievink** [comment]
Why does this need to be in the standard library? Is there an equivalent on Windows and macOS?

The nix crate already has a wrapper around this function in [`nix::unistd::fexecve`](https://docs.rs/nix/0.15.0/nix/unistd/fn.fexecve.html).

**Comment by retep998** [comment]
As far as I can tell Windows does not have an equivalent to this.

**Comment by Dylan-DPC** [comment]
Closing this as it is platform-dependent and likely better as an external crate than in std at the moment
