### ISSUE TITLE
Come up with regression test for #66286

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#66422]
Follow up to #66286 and #66390, as per https://github.com/rust-lang/rust/pull/66390#issuecomment-554078954.

Minimize a test that exercises the same codepath as

```rust
extern crate wasm_bindgen;
use wasm_bindgen::prelude::*;

#[wasm_bindgen]
pub extern fn third(a: Vec(u32)) -> u32 {
    return a[3]
}
```

**Comment by hellow554** [comment]
As already stated in https://github.com/rust-lang/rust/issues/66286#issuecomment-552339589 the `wasm_bindgen` proc macro can be reduced to:

```rust
extern crate proc_macro;

use proc_macro::TokenStream;
use quote::ToTokens;

#[proc_macro_attribute]
pub fn wasm_bindgen(attr: TokenStream, input: TokenStream) -> TokenStream {
    let mut tokens = proc_macro2::TokenStream::new();
    let item = syn::parse::<syn::Item>(input).expect("parse");

    if let syn::Item::Fn(f) = item {
        f.to_tokens(&mut tokens);
    }

    tokens.into()
}
```

**Comment by camelid** [comment]
How do you write a UI test that depends on 3rd-party libraries?

**Comment by estebank** [comment]
@camelid https://github.com/rust-lang/rust/blob/5c6f7b32aab683276d4feb1810244ccf72bda736/src/test/ui/proc_macro.rs is an example of a test that relies on a proc_macro, and we can use @hellow554's snippet for the necessary proc_macro being tested.
