### ISSUE TITLE
Replace Debug representation in const value pretty print

### ISSUE THREAD

**Issue by iwikal** [rust-lang/rust#66451]
As discussed in #65859, we shouldn't be using Debug for user facing output.

**Comment by varkor** [comment]
I think this only affects pointers, so this ought not to be a problem for `min_const_generics`.

**Comment by lcnr** [comment]
this issue isn't really relevant anymore, as we now use `fn pretty_print_const_valtree` for this:

https://github.com/rust-lang/rust/blob/baf382e63c023259fa1f9042f8f479f183ca6ed3/compiler/rustc_middle/src/ty/print/pretty.rs#L1417-L1541

This should also deal with references by printing a `&` and then calling `pretty_print_const_valtree` recursively.

as a test case, consider https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=cf3ef9d61a8bd2f727db22dd6b755863

while that's getting fixed, also change the `try_destructure_const` to just return a `DestructredConst`, ICE in cases where it currently returns `None`, and rename it to `destructure_const`. Destructuring a valtree should be infallible.

Finally, move the implementation of that query to a new module `rustc_ty_utils::consts`.
