### ISSUE TITLE
bootstrap/rustbuild: `--test-args` has no effect for cargo tests

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#66458]
I tried running `./x.py test src/tools/cargo --test-args rustc`, expecting that only tests with "rustc" in their name would be run. However, this has no effect. It looks like `--test-args` is just ignored.

**Comment by jyn514** [comment]
Looks like duplicate of https://github.com/rust-lang/rust/issues/72536

**Comment by jyn514** [comment]
This has been fixed, `x t src/tools/cargo --stage 0 --test-args util::auth::Secret` only runs 3 tests for me locally.
