### ISSUE TITLE
Nightly channel repo

### ISSUE THREAD

**Issue by aristarh2704** [rust-lang/rust#66475]
Where I can find nightly channel repo that uses "make" build system?

**Comment by jonas-schievink** [comment]
The `configure` script in the repo will generate a Makefile you can use to build Rust.

**Comment by aristarh2704** [comment]
No. In nightly source archive I founded "mk" dir, which is missing in master branch and others.

**Comment by csmoe** [comment]
@aristarh2704 checkout `src/bootstrap/`, you can find `mk` inside it.

**Comment by aristarh2704** [comment]
Now nightly channel src points to [rustc-nightly-src](https://static.rust-lang.org/dist/rustc-nightly-src.tar.gz), but some time ago another link was available: [rust-nightly-src](https://static.rust-lang.org/dist/rust-nightly-src.tar.gz). It is in this archive that I see the "mk" directory.

**Comment by aristarh2704** [comment]
Sorry, I just found that this archive turns out to contain the code of 2015
