### ISSUE TITLE
Ref/& Pattern Matching Inconsistency in Structs

### ISSUE THREAD

**Issue by quixotrykd** [rust-lang/rust#66480]
Rust pattern matching and destructuring allows the use of `&` and `ref`.

In the example below, the use of these is intuitive.

```rust
fn main() {
    let a: (u32) = (1234);
    let (ref ref_a) = a;

    let b: (&u32) = (&1234);
    let (&deref_b) = b;
}
```

In this case, we end up with ref_a of type `&u32`, and deref_b of type `u32`. Simple enough -- we can go both ways with both `ref` and `&` in pattern matching.

In the instance with structs, this consistency breaks down when matching struct field names. In the example that follows, this is shown:

```rust
struct Borrowed {
    val: u32
}

fn main() {
    let a = Borrowed {
        val: 1234
    };

    let Borrowed {ref val} = a;
}
```

In this case, val is borrowed as `&u32`, mirroring tuple functionality. The following example on the other hand, does not work.

```rust
struct Derefed<'a> {
    val: &'a u32
}

fn main() {
    let a = Derefed {
        val: &1234
    };

    let Derefed {&val} = a; // error: expected identifier, found `&`
    let Derefed {val: &val} = a; // works as expected
}
```

While not functionality-breaking, it is extremely non-intuitive that this matching only works via `ref`, and not via `&` for structs, when binding to the same variable name.

Is this intended behavior and/or required to avoid ambiguity in parsing?

**Comment by jonas-schievink** [comment]
"struct field shorthand" patterns are intended to work like this. Changes to the grammar need to go through our [RFC process](https://github.com/rust-lang/rfcs), so closing in favor of that.
