### ISSUE TITLE
Cannot compile `dotenv v0.10.1`

### ISSUE THREAD

**Issue by notriddle** [rust-lang/rust#66508]
This is a dependency of [diesel](https://github.com/diesel-rs/diesel). I was trying to compile `diesel_cli`; it failed on both the master branch and the current published version.

    `error_chain` is ambiguous (derive helper attribute vs any other name)

Indeed, the code does seem to treat `error_chain` as simultaneously a derive macro and an attribute macro. It works fine on stable.

**Comment by weiznich** [comment]
Example of failing builds: https://dev.azure.com/diesel-rs/diesel/_build/results?buildId=624&view=logs.

**Comment by mati865** [comment]
@rustbot modify labels: +E-needs-bisection

It'd be nice if somebody pinpointed specific PR (or nightly at least).

Maybe @petrochenkov has a clue what could have caused it.

**Comment by weiznich** [comment]
Seems to be introduced at nightly-2019-11-17. Unfortunately I'm not able to bisect that further because cargo-bisect-rustc is telling me: `authentication required but no callback set; class=Ssh (23)`

**Comment by mati865** [comment]
Likely https://github.com/rust-lang/rust/pull/64694

**Comment by petrochenkov** [comment]
This is a consequence of https://github.com/rust-lang/rust/pull/64694, I'll provide a [fix](https://github.com/rust-lang/rust/pull/64694#issuecomment-535518843) ASAP.

**Comment by petrochenkov** [comment]
Fixed in https://github.com/rust-lang/rust/pull/66529.
