### ISSUE TITLE
Intra-rustdoc links do not work for unqualified names in doc for a trait impl method

### ISSUE THREAD

**Issue by mzabaluev** [rust-lang/rust#66509]
There may be a problem with using intra-rustdoc links (#43466) in doc for a method implementation in a trait impl item. [This fixup](https://github.com/mzabaluev/futures-rs/commit/080680140af6eee3792e76c027aa1f7665a2395f#diff-3ed4c5e9ab0c32c94bb5516a4ef796b9) had to be made because an unqualified link to the `Policy` trait that is declared into the same module was rendered as `[Policy]` without the link. Other unqualified links to `Policy` in documentation elsewhere in the same module work as expected.

## Meta

`rustc --version --verbose`:
rustc 1.41.0-nightly (5c5b8afd8 2019-11-16)
binary: rustc
commit-hash: 5c5b8afd80e6fa1d24632153cb2257c686041d41
commit-date: 2019-11-16
host: x86_64-unknown-linux-gnu
release: 1.41.0-nightly

**Comment by xliiv** [comment]
Perhaps related to https://github.com/rust-lang/rust/issues/54172

**Comment by xliiv** [comment]
@mzabaluev is this duplicate of https://github.com/rust-lang/rust/issues/54172 ?
If so we could close it.

**Comment by mzabaluev** [comment]
> @mzabaluev is this duplicate of #54172 ?

No, that issue is about links to a specific impl method. Here, the link is to an unqualified trait name, but it is located in the doc of an impl method of a different trait, which somehow breaks it.

**Comment by xliiv** [comment]
> unqualified trait name

What is `an unqualified trait name`? Could you give an example of it?
Sorry i couldn't find anything suitable for it.

**Comment by mzabaluev** [comment]
@xliiv Here's a minimized test case:

```
use std::fmt;

pub trait Pretty {
    fn to_pretty(&self) -> String;
}

pub struct Ooh<T>(T);

impl<T: Pretty> fmt::Display for Ooh<T> {
    /// Uses [`Pretty`] to format the inner object.
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
        f.write_str(&self.0.to_pretty())
    }
}
```

It works in nightly, so I assume it is fixed.

**Comment by xliiv** [comment]
Great news!
