### ISSUE TITLE
Compiler error E0623

### ISSUE THREAD

**Issue by donaldcallen** [rust-lang/rust#66519]
Compiler error E0623 is missing from the error index at https://doc.rust-lang.org/error-index.html

**Comment by JohnTitor** [comment]
E0623 is now documented on nightly: https://doc.rust-lang.org/nightly/error-index.html#E0623
And for now, we have many undocumented error codes, tracking issue is #61137

**Comment by donaldcallen** [comment]
Ok. Thanks for the explanation and the knowledge that this isn't an oversight.

Good idea to note on the error index web page that all error codes aren't documented and they are being worked on.
