### ISSUE TITLE
match arms have incompatible types

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#66516]
https://crater-reports.s3.amazonaws.com/beta-1.40-1/beta-2019-11-06/gh/HristoKolev.sync-dir/log.txt

Possibly due to flatten getting stabilized or something like that, need to investigate further.

**Comment by ecstatic-morse** [comment]
1.37.0-stable gives the following warning when building this crate:

```
warning: a method with this name may be added to the standard library in the future
   --> src/global/extensions.rs:132:26
    |
132 |             Some(v) => v.flatten(),
    |                          ^^^^^^^
    |
    = note: #[warn(unstable_name_collisions)] on by default
    = warning: once this method is added to the standard library, the ambiguity may cause an error or change in behavior!
    = note: for more information, see issue #48919 <https://github.com/rust-lang/rust/issues/48919>
    = help: call with fully qualified syntax `global::extensions::OptionFlatten::flatten(...)` to keep using the current method
```

It seems this is allowed breakage and we should maybe ping the author?

**Comment by Mark-Simulacrum** [comment]
Makes sense to me. cc @HristoKolev -- this is likely to be closed as accepted breakage, so you'll likely want to update your crate/repository
