### ISSUE TITLE
Add message to tell all the error codes aren't documented on Error Index

### ISSUE THREAD

**Issue by JohnTitor** [rust-lang/rust#66521]
For now, all the error codes aren't documented and it causes some confusion like #65326 and #66519.
So, I think it'd be nice to have a message to tell all the error codes aren't documented on Error Index.
It's temporary until adding explanations is complete but it's worth to do so.
What about? @rust-lang/docs

**Comment by GuillaumeGomez** [comment]
Some error codes can't really be added into this list because they only thrown on internal. Also, not sure how you would want this to be done. I added a few securities to avoid having removed error codes without a note or error codes not having at least one test.

**Comment by JohnTitor** [comment]
> Also, not sure how you would want this to be done.

I mean we can add a note to the top of https://doc.rust-lang.org/nightly/error-index.html
something like: 
```
NOTE: This document doesn't cover all the error codes. Some only show on internal, others aren't documented yet. See also [tracking issue](#61137).
```

**Comment by GuillaumeGomez** [comment]
From my point of view, this isn't a good idea since some people might just then think that this isn't worth looking if not all error codes are there. Also, we have "holes" in the error codes list (some people have issues adding one to the highest error code I think :rofl: ).

**Comment by JohnTitor** [comment]
Uhm, somehow we should avoid the confusion but I have no strong opinion for this option. If you have an option better than this, it'd be nice. I'm closing this issue in favor of the above objection.

**Comment by GuillaumeGomez** [comment]
No I don't (that's why I'm adding missing long error explanations). I don't think this idea is a good one, but I'm definitely open to hear others!
