### ISSUE TITLE
`Pin` is unsound due to rogue Deref/DerefMut implementations

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#66544]
@comex [found a soundness bug in `Pin`](https://internals.rust-lang.org/t/unsoundness-in-pin/11311). This issue is to track that.

Discussion is happening on IRLO currently, let's try not to fork that.

**Comment by eddyb** [comment]
I don't think people are necessarily seeing this, pinging all labelled teams:
cc @rust-lang/compiler @rust-lang/lang @rust-lang/libs

**Comment by est31** [comment]
PR with a proposed fix: #67039

**Comment by RalfJung** [comment]
Well, a proposed partial fix.

**Comment by xfix** [comment]
I still think the partial fix is worth it. I don't think we would want to resolve this particular issue in any other way. Meanwhile, other soundness issues are more complicated.

**Comment by RalfJung** [comment]
> I still think the partial fix is worth it.

Fully agreed, and thanks for preparing that PR! I was just pointing out that the PR will not be sufficient to consider the problem solved.
