### ISSUE TITLE
Account for unicode char width when calculating vertical label lines

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#66552]
In [ui/terminal-width/non-whitespace-trimming-unicode.stderr](https://github.com/rust-lang/rust/blob/master/src/test/ui/terminal-width/non-whitespace-trimming-unicode.stderr) we account for the visible char width when calculating the label and span positions, but we do not do so for the vertical bar tying them together, causing the following output:

```
error[E0308]: mismatched types
  --> $DIR/non-whitespace-trimming-unicode.rs:4:415
   |
LL | ...♬♭♮♯♰♱♲♳♴♵♶♷♸♹♺♻♼♽♾♿⚀⚁⚂⚃⚄⚅⚆⚈⚉4"; let _: () = 42;  let _: &str = "🦀☀☁☂☃☄★☆☇☈☉☊☋☌☍☎☏☐☑☒☓  ☖☗☘☙☚☛☜☝☞☟☠☡☢☣☤☥☦☧☨☩☪☫☬☭☮☯☰☱☲☳☴☵☶☷☸☹☺☻☼☽☾☿♀♁♂♃...
   |                                             --   ^^ expected (), found integer
   |                                                      |
   |                                             expected due to this
   |
   = note: expected type `()`
              found type `{integer}`

error: aborting due to previous error
```

where it should be

```
error[E0308]: mismatched types
  --> $DIR/non-whitespace-trimming-unicode.rs:4:415
   |
LL | ...♬♭♮♯♰♱♲♳♴♵♶♷♸♹♺♻♼♽♾♿⚀⚁⚂⚃⚄⚅⚆⚈⚉4"; let _: () = 42;  let _: &str = "🦀☀☁☂☃☄★☆☇☈☉☊☋☌☍☎☏☐☑☒☓  ☖☗☘☙☚☛☜☝☞☟☠☡☢☣☤☥☦☧☨☩☪☫☬☭☮☯☰☱☲☳☴☵☶☷☸☹☺☻☼☽☾☿♀♁♂♃...
   |                                             --   ^^ expected (), found integer
   |                                             |
   |                                             expected due to this
   |
   = note: expected type `()`
              found type `{integer}`

error: aborting due to previous error
```

(Found during https://github.com/rust-lang/rust/pull/66539/)

**Comment by TheSamsa** [comment]
I would like to solve this as a first time issue. Best with some pointers where to start :)

**Comment by estebank** [comment]
@TheSamsa the code that draws the vertical lines is at

https://github.com/rust-lang/rust/blob/3f93ffc3334b77cc9025f68dfcea92098987abf3/src/librustc_errors/emitter.rs#L901-L927

and the one that draws the span labels is right below

https://github.com/rust-lang/rust/blob/3f93ffc3334b77cc9025f68dfcea92098987abf3/src/librustc_errors/emitter.rs#L949-L974

I think the error might be using `margin.computed_left` instead of `left`, but I'm not entirely certain.

If this is your first time compiling `rustc`, you probably want to read the [rustc guide](https://rust-lang.github.io/rustc-guide/about-this-guide.html), but the TL;DR: is "run `./x.py test src/test/ui --stage 1 --bless` to build the compiler up to the first stage and update the `stderr` test output files".

**Comment by TheSamsa** [comment]
Thank you!
I did read the rustc guide, and even compiled it on my own once. But thanks for the direction, and the note to the PR.
I'll do my best :wink:
