### ISSUE TITLE
min const fn checks don't check set discriminant target

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#66556]
Leaving this issue as a reminder for https://github.com/rust-lang/rust/pull/66507/files#r347252249

It should be as simple  as adding a check_place call to the `SetDiscriminant`

This issue has been assigned to @christianpoveda via [this comment](https://github.com/rust-lang/rust/issues/66556#issuecomment-557729322).

**Comment by ecstatic-morse** [comment]
This bug appears in `check_consts::validation` as well: https://github.com/rust-lang/rust/blob/618b01f9fa0a6b4e7e2ce5b3409abe104b80c4a8/src/librustc_mir/transform/check_consts/validation.rs#L546-L554

**Comment by christianpoveda** [comment]
I'm taking this one :P
