### ISSUE TITLE
AllocatorKind::GlobalExe is never constructed

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rust#66550]
Defined at https://github.com/rust-lang/rust/blob/9285d401a6070094747465962bc49969b93e14c5/src/libsyntax/expand/allocator.rs#L9

Search results: https://github.com/rust-lang/rust/search?q=DefaultExe

**Comment by petrochenkov** [comment]
Fixed in https://github.com/rust-lang/rust/pull/66697.
