### ISSUE TITLE
Is the generic passage on `register_dtor` still relevant?

### ISSUE THREAD

**Issue by hellow554** [rust-lang/rust#66572]
https://github.com/rust-lang/rust/blob/ab6cb0197188f0c842d7dd2e378777f0bc0f6240/src/libstd/sys/unix/fast_thread_local.rs#L12

The corresponding issue #18804 has been closed by PR #52635, so is that passage still relevant or can it be removed?

This issue has been assigned to @chansuke via [this comment](https://github.com/rust-lang/rust/issues/66572#issuecomment-564599725).

**Comment by Mark-Simulacrum** [comment]
Seems likely it can be removed. Marking as E-help-wanted; I don't expect we'll do this ourselves but if someone files a PR removing the comment I think it's likely we can accept that pretty easily.

**Comment by chansuke** [comment]
Hi:) I would like to work on this.
