### ISSUE TITLE
Support a rustup-toolchain-install-master contribution workflow for rustdoc

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#66581]
Currently to hack on rustdoc you need to build all of rustc, which takes forever and hinders contribution.

It might be better to do what clippy does: use [rustup-toolchain-install-master](https://github.com/kennytm/rustup-toolchain-install-master)

Currently this works on rustdoc with the following steps:

```rust
# setup
cargo install rustup-toolchain-install-master
rustup-toolchain-install-master -n master -c rustc-dev -f

# remove workspace file so that we don't mess with rustbuild
rm Cargo.toml

cd src/tools/rustdoc
cargo +master build
./target/debug/rustdoc
```

cc @GuillaumeGomez @QuietMisdreavus @Mark-Simulacrum 

It may also be worth making this kind of workflow a more first-class part of x.py.

**Comment by Mark-Simulacrum** [comment]
This was discussed at the all hands this year wrt to integration into x.py. I've not yet had the time/energy to sit down and do it, even though it is not very difficult I expect. I should probably try and write up mentoring instructions.

**Comment by Manishearth** [comment]
In the meantime it may be worth investigating the RTIM solution (importantly, how to use this compiled rustdoc, `rustup run master ./target/debug/rustdoc foo.rs`) and documenting it

**Comment by jyn514** [comment]
I'm working on this in https://github.com/rust-lang/rust/pull/79540.

**Comment by jyn514** [comment]
This has been subsumed by `download-rustc` I think; I don't have any plans to make this work with rust-toolchain directly.
