### ISSUE TITLE
[rustdoc] Cannot select search bar in core crate

### ISSUE THREAD

**Issue by lzutao** [rust-lang/rust#66593]
Steps to reproduce:
* Open https://doc.rust-lang.org/nightly/core/index.html
* Click in search bar, which doesn't work. Also the 'S' shortcut doesn't work.

cc @GuillaumeGomez

**Comment by lzutao** [comment]
Maybe it's #66514 to blame.

**Comment by hellow554** [comment]
Works for me :/ caching issues? Have you tried ctrl+F5?

**Comment by lzutao** [comment]
Yeah. Clearing cache is helpful. Closing as that.
