### ISSUE TITLE
Add TAU consts to f32 and f64

### ISSUE THREAD

**Issue by icefoxen** [rust-lang/rust#66616]
Where `tau = 2 * pi`.

In aesthetic terms, very much in the vein of ha-ha-only-serious, the argument is described [here](https://tauday.com/tau-manifesto).

In practical terms, we already have const's for pi divided by various useful integers, so why not include multiplying it by the only really useful integer as well?

PR is trivial and already implemented in https://github.com/icefoxen/rust/commit/50173bdd292d5edb7195f7f53cdc339142fad790 , but apparently I need a feature name and issue number and such associated with it, hence this ticket.

**Comment by lzutao** [comment]
Python and C++ doesn't seem to include that constant either.

**Comment by memoryruins** [comment]
Python 3.6 added a tau constant, `math.tau`.  Nim and Perl 6 include one as well.

**Comment by hellow554** [comment]
@icefoxen without any guarantees, I'm sure it's pretty safe to just open a PR with an explanation and some reasoning and see what happens. To open an issue for asking is not necessary, just a tracking issue afterwards will be needed.

**Comment by ollie27** [comment]
See also: rust-lang/rfcs#1486

**Comment by Dylan-DPC** [comment]
Closing this as it is easier to create a tracking issue when the rfc is accepted. Thanks

**Comment by est31** [comment]
Tracking issue: #66770

**Comment by steveklabnik** [comment]
For posterity's sake, this was rejected back in https://github.com/rust-lang/rust/pull/15248; any new RFCs would have to address that discussion.
