### ISSUE TITLE
Implement Default for NoneError?

### ISSUE THREAD

**Issue by withoutboats** [rust-lang/rust#66611]
I want to ask: should we implement Default for NoneError?

This would allow users to create a NoneError on stable but still not to name the type. I would like to be able to do this, obviously, which is why I want to implement this.

The biggest hazard I see would be that it would limit our ability to change the definition of `NoneError`. In particular, I want to ask: would this make it impossible to change `Option`'s error type to `()` and so on? (In my opinion, the "opt into throwing from options" concept has been unergonomic and very unhelpful.)

**Comment by xfix** [comment]
I believe this can be closed now that `NoneError` was removed.
