### ISSUE TITLE
In Rust: assert_ne! macro has a second form, where a custom panic message can be provided

### ISSUE THREAD

**Issue by kamranajabbar** [rust-lang/rust#66628]
#### Issue
I am trying to use assert_ne! macro but facing the following issue as mentioned in attachment, I would like to print my custom message when the case failed but can not print my message. As shares in below screenshot.

#### Reference
[Offical Example URL](https://docs.w3cub.com/rust/std/macro.assert_ne/)

#### Sourcecode
>let a = 3;
>let b = 2;
>assert_ne!(a, b);
>
>assert_ne!(a, b, "we are testing that the values are not equal");

#### Aspected Result
The custom message "we are testing that the values are not equal" should be printed at panic.

**Comment by jonas-schievink** [comment]
The screenshot is missing.

Doing `assert_ne!(1, 1, "oops");` does correctly print the message:

```
thread 'main' panicked at 'assertion failed: `(left != right)`
  left: `1`,
 right: `1`: oops', src/main.rs:2:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

**Comment by kamranajabbar** [comment]
Yes, its showing custom messages.
