### ISSUE TITLE
[ICE] with or_patterns

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust#66626]
I don't know if you want bug reports about unfinished features:

	#![feature(or_patterns)]
	enum Foo { A, B, C, D }

	fn main() {
		let x = Some(Foo::B);

		let _y = match x {
			Some(Foo::A | Foo::B | Foo::C) => 0,
			Some(Foo::D) => 1,
			None => 2,
		};
	}

Gives:

warning: the feature `or_patterns` is incomplete and may cause the compiler to crash
 --> ...\bug1.rs:1:12
  |
1 | #![feature(or_patterns)]
  |            ^^^^^^^^^^^
  |
  = note: `#[warn(incomplete_features)]` on by default

error: internal compiler error: src\librustc_mir\hair\pattern\_match.rs:1806: support for or-patterns has not been fully implemented yet.

thread 'rustc' panicked at 'Box<Any>', src\librustc_errors\lib.rs:892:9
stack backtrace:
   0: mingw_set_invalid_parameter_handler
...
  52: mingw_set_invalid_parameter_handler
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: rustc 1.41.0-nightly (53712f863 2019-11-21) running on x86_64-pc-windows-gnu

query stack during panic:
#0 [check_match] processing `main`
#1 [analysis] running analysis passes on this crate
end of query stack
error: aborting due to previous error

**Comment by matthewjasper** [comment]
Given that the panic message is "support for or-patterns has not been fully implemented", I don't think this issue needs tracking outside of #54883.
