### ISSUE TITLE
Having no right to kill a subprocess after capturing the output

### ISSUE THREAD

**Issue by SchrodingerZhu** [rust-lang/rust#66635]
In order to capture the output, I need to partial move the fields of `stdout` and `stdin`. However, after partial moving these two fields I of course lose the right to kill the child process. Someone may argue that I shall be able to work around using mutable borrow of `stdout` and `stdin`, but in my case, the behaviors are not the same.

```rust
Ok(mut child) => {
                    {
                        let mut input = child.stdin.expect("unable to get input");
                        input.write(crate::config::global_config().root_password.as_bytes()).unwrap();
                        input.flush().unwrap();
                    }
                    let output =
                        child.stdout.expect("unable to get output");
                    let mut buffer = Vec::new();
                    buffer.resize(crate::config::global_config().submit_chunk_size, 0_u8);
// something else
                    output.read(buffer.as_mut())
}
```
I tested out that if I use mutable borrow here, the program will somehow block there while the current partial moving method works fine. However, I cannot close the process on need with the current method. Is there a logic cycle here?

**Comment by jonas-schievink** [comment]
If you *must* move out of `stdin`, you can always call `child.stdin.take()`, which will leave a `None` in its place.

**Comment by jonas-schievink** [comment]
This issue tracker is mainly meant for bug reports and concrete, small feature requests. Questions like this are better asked in the user forum at https://users.rust-lang.org/ or on [one of the chat platforms](https://www.rust-lang.org/community) used by the Rust community.
