### ISSUE TITLE
rustc --explain shouldn't display hidden lines

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/rust#66632]
In codeblocks, you can hide lines when starting it with "# ". Currently, `rustc --explain` does display them, whereas it shouldn't.

**Comment by contrun** [comment]
This is already done in https://github.com/rust-lang/rust/blob/303d8aff6092709edd4dbd35b1c88e9aa40bf6d8/src/librustc_driver/lib.rs#L540

**Comment by GuillaumeGomez** [comment]
Indeed! Thanks for the info @contrun !
