### ISSUE TITLE
SSE disabled libstd creates an error

### ISSUE THREAD

**Issue by mincheolsung** [rust-lang/rust#66644]
I added disabling SSE and MMX on https://github.com/hermitcore/rust/blob/ab6cb0197188f0c842d7dd2e378777f0bc0f6240/src/librustc_target/spec/x86_64_unknown_hermit.rs#L7 and built libstd.

When I tried to build an application with `-C soft-float`, I got `LLVM ERROR: SSE register return with SSE disabled`.

**Comment by jonas-schievink** [comment]
It is possible that LLVM simply does not handle this, since you're building for x86-64, which always has SSE available.

**Comment by mincheolsung** [comment]
I tried with `-Ctarget-feature=+soft-float` instead of `-C soft-float` and it fixed the issue.
