### ISSUE TITLE
Rustc does not free memory before calling the linker

### ISSUE THREAD

**Issue by cjgillot** [rust-lang/rust#66643]
Hello,

While compiling rust-analyzer, I witnessed elevated memory usage by rustc while the linker is active. In that case, more that 600 MB is allocated by the compiler. In cargo-parallelized build, this is a lot.

rustc version: 1.40.0-nightly (5da4b4d47 2019-10-28)

Thank you for investigating this.

**Comment by matprec** [comment]
I think this can closed now that https://github.com/rust-lang/rust/pull/66707 is merged.
