### ISSUE TITLE
Bug: Inconsistent deserialization of serde_json::from_str

### ISSUE THREAD

**Issue by hskang9** [rust-lang/rust#66676]
Hello, I was investigating why `cargo publish` command would convert hyphen and underscore to the same underscore to make upload request to crates.io, and I think I found out that [this line](https://github.com/rust-lang/crates.io/blob/66c60dc1c2f7b582643fe5ccb79f40363e277b4d/src/controllers/krate/publish.rs#L227) created the problem.

`serde_json::from_str` changes hyphens and underscore to underscore arbitarily.

Here is the code for an example: 
```rust
extern crate serde_json;

use serde_json::Value;

fn main() {
    let data: Value = serde_json::from_str("{\"foo\": \"why-why\", \"bar\": \"why_why\"}").unwrap();
    println!("data: {:?}", data);
    // data: {"bar":"baz","foo":13}
    println!("object? {}", data.is_object());
    // object? true

    let obj = data.as_object().unwrap();
    let foo = obj.get("foo").unwrap();

    println!("array? {:?}", foo.as_str());
    // array? None
    println!("u64? {:?}", foo.as_str());
    // u64? Some(13u64)

    for (key, value) in obj.iter() {
        println!("{}: {}", key, match *value {
            Value::String(ref v) => format!("{} (string)", v),
            _ => format!("other")
        });
    }
    // bar: why_why (string)
    // foo: why-why (string)
    // and foo == bar.....?
}
```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=351e60b9cfb596f85ea72cce0a65df9b))

Output:

```
data: Object({"bar": String("why_why"), "foo": String("why-why")})
object? true
array? Some("why-why")
u64? Some("why-why")
bar: why_why (string)
foo: why-why (string)

```

Errors:

```
   Compiling playground v0.0.1 (/playground)
    Finished dev [unoptimized + debuginfo] target(s) in 0.55s
     Running `target/debug/playground`

```
and [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=7e5874855db8884e427f8c780fae11d6)

**Comment by jonas-schievink** [comment]
That does not look inconsistent to me.

**Comment by hskang9** [comment]
Yes This is definitely my mistake.
