### ISSUE TITLE
core::panicking module docs are outdated

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#66689]
The module docs at the top of https://github.com/rust-lang/rust/blob/e41ced3f8d8e2f3f377ef931458e612d5f3d1f3f/src/libcore/panicking.rs seem outdated: they mention `fn panic_impl(fmt: fmt::Arguments, file_line_col: &(&'static str, u32, u32)) -> !` as the signature for the panic_impl, but the actual signature at the bottom of the same file is `fn panic_impl(pi: &PanicInfo<'_>) -> !`.

The comment also says that it does not allow failing with a `Box<Any>` value, but `PanicInfo` contains something very similar, a `&'a (dyn Any + Send)`.

I would send a PR adjusting the signature, but the second makes be belief someone with some actual knowledge of our panicking infrastructure should look at this.

Cc @alexcrichton

**Comment by alexcrichton** [comment]
Yes the signature has bitrotted over time and just needs an update, the bit about `Box` is libcore-specific and still accurate though.

**Comment by Mark-Simulacrum** [comment]
I think #66694 updated the comments as needed and seems consistent with the state of the world today, so closing (but feel free to reopen of course if I'm wrong!)
