### ISSUE TITLE
Running rustfmt on rust-lang/rust codebase

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust#66688]
Filing this to track https://internals.rust-lang.org/t/running-rustfmt-on-rust-lang-rust-and-other-rust-lang-repositories/8732 in a way that doesn't get locked every 90 days, since I believe we all still want this to happen.

> Using rustfmt would have several wins:
>
> - Adopt a uniform style, of course
> - But also resolve problems that contributors have either:
>   - trying to figure out our style (heh, good luck)
>   - accidentally running rustfmt on stuff that drags in a lot of auxiliary diffs
>
> There are obviously two main approaches:
>
> - Flag day
> - Gradual transition
>
> I am partial to “flag day” myself, but I could go either way.
>
> There is another question too: how to keep things formatted? In my ideal world, this would be fairly painless, but I’m not sure how best to achieve that (one idea I had was a [rustfmtbot](https://internals.rust-lang.org/t/idea-rustfmtbot/5039) that runs rustfmt on people’s PRs and pushes commits automatically, but that does not exist afaik).

**Comment by Centril** [comment]
The compiler team decided to move forward with enforcing formatting on the repo in https://github.com/rust-lang/compiler-team/issues/80 and the plan is being implemented in https://github.com/rust-lang/rust/pull/65939.

**Comment by Centril** [comment]
Closing as done.
