### ISSUE TITLE
Tracking issue for `btreemap_remove_entry`

### ISSUE THREAD

**Issue by billyrieger** [rust-lang/rust#66714]
[`HashMap::remove_entry`](https://doc.rust-lang.org/std/collections/struct.HashMap.html#method.remove_entry) has been stable since 1.27.0 (issue #46344) but there is no corresponding method for `BTreeMap`. If this is something that should be added I'd be happy to implement it.

**Comment by hellow554** [comment]
@billyrieger feel free to open a PR

**Comment by billyrieger** [comment]
Implemented in #68378.

**Comment by JohnTitor** [comment]
The method is unstable and this should be tracking issue, re-opening.
