### ISSUE TITLE
Add remove, contains functions to BinaryHeap

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#66724]
[BinaryHeap](https://doc.rust-lang.org/stable/std/collections/struct.BinaryHeap.html) currently only has functions to pop the maximum element and push an arbitrary element to it. There is no function to remove a given element from the heap or to check whether the heap contains an element. Both are kinda common operations.

**Comment by hellow554** [comment]
But isn't that excactly the purpose of a BinaryHeap. You are most likely only interested in the biggest/smallest element. If you just want an ordered thing, use a `BTreeSet` which will provide the needed functions.

**Comment by est31** [comment]
There is no pop function in a BTreeSet although you could probably use `iter().next()` for the same functionality.

Anyways, there are algorithms where you are interested in the minimum of a set in one step, then you remove it as well as items associated with it (which aren't neccessarily minima themselves). Then you are interested in the minimum again, etc. What I'm doing right now is to have a separate `HashSet` that I'm adding removed items to, and then simply doing a continue operation in the pop loop if the item is in the removed list. It might be faster than using the `BinaryHeap` for it, but it's not really a nice design.

For me, the purpose of a BinaryHeap is not that its operations are restricted, but that the invariant of a minimum being quickly accessible is maintained.

**Comment by est31** [comment]
@billyrieger as you made  #68378 , do you want to make this one next?

**Comment by billyrieger** [comment]
>For me, the purpose of a BinaryHeap is not that its operations are restricted, but that the invariant of a minimum being quickly accessible is maintained.

I agree with this sentiment. On the other hand, one could argue adding these operations would unnecessarily clutter the `BinaryHeap` API. Regardless, I'll take a stab at this.

**Comment by coriolinus** [comment]
One use case comes straight from Wikipedia: the [A* algorithm](https://en.wikipedia.org/wiki/A*_search_algorithm#Pseudocode)  specifically suggests using a heap for `openSet`, and it assumes that `.contains` is available:

```
                if neighbor not in openSet
                    openSet.add(neighbor)
```

IMO `.remove` and `.contains` are reasonable operations to add to any container; they are fundamental, and do not clutter the API.

**Comment by gowrizrh** [comment]
I am stuck right exactly here, for exactly what @coriolinus mentioned. I'm implementing a number of algorithms from the A* family and there's specifically no `.contains` in a BinaryHeap which is a priority queue as said by the docs. 

```rust
    if !open.contains(neighbour) { // this would be great!
        open.push(neighbour);
    }
```

**Comment by Neutron3529** [comment]
> I am stuck right exactly here, for exactly what @coriolinus mentioned. I'm implementing a number of algorithms from the A* family and there's specifically no `.contains` in a BinaryHeap which is a priority queue as said by the docs.
> 
> ```rust
>     if !open.contains(neighbour) { // this would be great!
>         open.push(neighbour);
>     }
> ```

what about `fn insert(&mut self, value: T) -> bool`?
```rust
    if !open.insert(neighbour){
        // do something after we insert the neighbour, or do nothing as your code suggests.
    }
```

**Comment by Neutron3529** [comment]
> ```rust
>     if !open.contains(neighbour) { // this would be great!
>         open.push(neighbour);
>     }
> ```

a `fn insert(&mut self, item: T)->bool` is more beautiful here.
```rust
    if open.insert(neighbour) { 
        // this would be great!
    }
```
Previously I made a mistake that think `insert` is as fast and easy to implement as `push`..
I'm fixing that problem, the PR will be later.
That PR may provide sub-linear time complexity, but slower than push.

**Comment by est31** [comment]
I think I'll close this because such functions would have bad (linear) performance characteristics: https://github.com/rust-lang/rust/issues/82001#issuecomment-778692012

**Comment by thisisrandy** [comment]
This is the top Google hit for "rust BinaryHeap contains" and the top DuckDuckGo hit under `github.com`, so in case anyone comes here searching for a way to test `BinaryHeap` membership, please note that you can do so using `iter`/`any` as in `my_heap.iter().any(|heap_item| heap_item == test_item)`.

**Comment by est31** [comment]
With `as_slice` (unstable, see #83659), you can also do `my_heap.as_slice().contains(needle)`. `contains` is also always linear time, but it has some optimized implementations for some types.
