### ISSUE TITLE
for loop 

### ISSUE THREAD

**Issue by ren895837248** [rust-lang/rust#66729]
```
let mut v = vec![1];
 let vR = &mut v;

 for item in vR {
            println!("{}", item);
    }
    vR.push(2);


 --> src\main.rs:14:5
   |
7  |     let vR = &mut v;
   |         -- move occurs because `vR` has type `&mut std::vec::Vec<i32>`, which does not implement the `Copy` trait
8  | 
9  |     for item in vR {
   |                 --
   |                 |
   |                 value moved here
   |                 help: consider borrowing to avoid moving into the for loop: `&vR`
...
14 |     vR.push(2);
   |     ^^ value borrowed here after move
```

**Why does the for loop transfer a referenced value?**

**Comment by hellow554** [comment]
First: Please use three backticks (\```) to format your code properly. 
Second: this bugtracker is used for compiler errors or any problems with the rust compiler itself. If you have any questions, please use the user forum at https://users.rust-lang.org.
Third: Rust compiler errors/messages are very good. Please read them carefully, e.g. the help secion: 

>  help: consider borrowing to avoid moving into the for loop: `&vR`

**Comment by CGQAQ** [comment]
> **Why does the for loop transfer a referenced value?**

because vR itself is consider as owned value that owns a mut ref that reference to v
