### ISSUE TITLE
Matching on exhaustive enum errors with `const_if_match`

### ISSUE THREAD

**Issue by jhpratt** [rust-lang/rust#66756]
Example: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=13a9fbc4251d7db80f5d63b1dc35a98b

```rust
#![feature(const_if_match)]

enum E {
    A,
    B,
    C
}

const fn f(e: E) {
    match e {
        E::A => {}
        E::B => {}
        E::C => {}
    }
}
```

```none
error[E0723]: const fn with unreachable code is not stable
  --> src/lib.rs:10:11
   |
10 |     match e {
   |           ^
   |
   = note: for more information, see issue https://github.com/rust-lang/rust/issues/57563
   = help: add `#![feature(const_fn)]` to the crate attributes to enable
```

CC: #49146, @ecstatic-morse

**Comment by ecstatic-morse** [comment]
The error originates from [this match arm](https://github.com/rust-lang/rust/blame/91642e3ac0120c8e9cdd5f3c85ad03f3bf1b8b69/src/librustc_mir/transform/qualify_min_const_fn.rs#L340). Adding `#![feature(const_fn)]` does enable the example above. Interestingly, no `Unreachable` terminator appears in the MIR for that function. This suggests that we are running const checks before a cleanup pass that removes `Unreachable` terminators for exhaustive `match` expressions.

@oli-obk We have a few choices here. What do you think?

**Comment by Centril** [comment]
> I am leaning towards just removing `Unreachable` from the `min_const_fn` checks. What do you think?

Let's gate the removal on `const_if_match` for now to make sure we don't accidentally allow anything on stable.

**Comment by oli-obk** [comment]
> I am leaning towards just removing Unreachable from the min_const_fn checks. What do you think?

Oh yea, I just left it in there so we don't accidentally allow something. I couldn't figure out how to trigger it, so I preferred to deny it.
