### ISSUE TITLE
rustdoc not resolving intra crate items in markdown links

### ISSUE THREAD

**Issue by lopopolo** [rust-lang/rust#66767]
The following Rust Doc link:

```rust
/// Decoding errors from [`bubblebabble::decode`](crate::decode).
```

generates this HTML

```html
<p>Decoding errors from <a href="crate::decode"><code>bubblebabble::decode</code></a>.</p>
```

`decode` is a `pub` function in the crate root.

```shell
$ rustc --version --verbose
rustc 1.39.0 (4560ea788 2019-11-04)
binary: rustc
commit-hash: 4560ea788cb760f0a34127156c78e2552949f734
commit-date: 2019-11-04
host: x86_64-apple-darwin
release: 1.39.0
LLVM version: 9.0
```

**Comment by ehuss** [comment]
> ```shell
> rustc 1.39.0 (4560ea788 2019-11-04)
> ```

intra-doc-links only work on nightly.  Can you try with that toolchain?

**Comment by lopopolo** [comment]
That did the trick. I'll close this issue, but I'm wondering when this will be available in stable? Having to install two rust toolchains adds latency to my build.

**Comment by ehuss** [comment]
You can follow the tracking issue at #43466 for updates on the status.  I don't think anyone has a time frame, but it looks like a few people have been working on it again recently.
