### ISSUE TITLE
prettyprinter reorders comments to show before doc comments

### ISSUE THREAD

**Issue by ben0x539** [rust-lang/rust#6678]
```
$ echo '/** foo */ /* bar */ fn f() {}' | rustc - --pretty
/* bar */
/** foo */
fn f() { }
```

I'm not sure this is supposed to happen, but maybe it's prettier this way...

**Comment by steveklabnik** [comment]
Triage: still here.

**Comment by mrhota** [comment]
Triage: still here in nightly (using rustup)

**Comment by steveklabnik** [comment]
Triage: no change in behavior, though the flags have changed:

```
> rustc +nightly -Z unstable-options --pretty=normal .\foo.rs
/* bar */
/** foo */
fn f() { }
```

**Comment by workingjubilee** [comment]
Closing this on the hypothesis of "if this was unintended behavior, someone would have fixed it within the past 10 years". Seems harmless, but maybe I'm wrong? :woman_shrugging:

**Comment by varkor** [comment]
@workingjubilee: seems less likely this is intended behaviour and more likely this is just low priority compared to other issues.
