### ISSUE TITLE
Passing --disable-per-crate-search to rustdoc disables search altogether

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#66816]
docs.rs ran into this this morning, see https://github.com/rust-lang/docs.rs/pull/497.

This seems to have been caused by https://github.com/rust-lang/rust/pull/66298, which disabled the search bar by default. The logic to reenable search was a little buggy - [`getSearchElement()`](https://github.com/rust-lang/rust/blob/master/src/librustdoc/html/static/main.js#L47) looks for an element with the 'search' id, but that ID is not set when `--disable-per-crate-search` is enabled.

Steps to replicate:

```
cat '/// Hello, world!
fn main() {
}' > tmp.rs
rustdoc +nightly -Zunstable-options --disable-per-crate-search tmp.rs
xdg-open doc/tmp/index.html
```

cc @QuietMisdreavus @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
I'll try to take a look tomorrow.
