### ISSUE TITLE
Public items and macros shouldn't be able to have the same name

### ISSUE THREAD

**Issue by expenses** [rust-lang/rust#66812]
Consider this extremely simple example:

`src/lib.rs`
```rust
pub use std::vec;
```

Because it's not clear which `vec` we're talking about, both get exported: 

<img width="655" alt="Screen Shot 2019-11-27 at 3 51 18 PM" src="https://user-images.githubusercontent.com/13566135/69733566-d308ef00-112d-11ea-998a-62cf9f9987f2.png">

This is not a huge problem, but it's awkward and causes namespace confusion. One possible use-case would be to have both a `Whatever` trait and a `Whatever` derive macro, but I think it would probably make more sense to either: A) do something special with trait derive macros so that this is allowed, or B) change derive macros to be something like `WhateverDerive` etc.

**Comment by jonas-schievink** [comment]
Changing this would be a breaking change, and would probably also need to go through the RFC process, so closing.
