### ISSUE TITLE
arrays require explicit coercion to &[T]

### ISSUE THREAD

**Issue by tdyas** [rust-lang/rust#66830]
The following code seems like it should compile since a coercion seems to be performed for the `insert` but not performed for the `contains_key`.

```
use std::collections::HashMap;

fn main() {
    let mut h: HashMap<&[u8], &[u8]> = HashMap::new();
    h.insert(b"foo", b"bar");
    if h.contains_key(b"foo") {
        println!("YES");
    } else {
        println!("NO");
    }
}
```

The error is:

```
error[E0277]: the trait bound `&[u8]: std::borrow::Borrow<[u8; 3]>` is not satisfied
 --> src/main.rs:6:10
  |
6 |     if h.contains_key(b"foo") {
  |          ^^^^^^^^^^^^ the trait `std::borrow::Borrow<[u8; 3]>` is not implemented for `&[u8]`
  |
  = help: the following implementations were found:
            <[T; _] as std::borrow::Borrow<[T]>>
```

Changing `h.contains_key(b"foo")` to `h.contains_key(b"foo" as &[u8])` fixes the error and the code works as expected. If byte literals are arrays, why is coercion to `&[u8]` done implicitly for the `insert` but not the `contains_key`?

**Comment by csmoe** [comment]
checkout the docs of `HashMap::contains_key`, you should notice the trait bound on `K` and `Q`.
then https://doc.rust-lang.org/std/borrow/trait.Borrow.html#examples has a good explanation, array(`[u8; _]`)'s `Hash` implementation(calculated from its elements) differs from slice(`[u8]`) which calculated from its length.
