### ISSUE TITLE
Give many `impl Iterator` return types an ExactSizeIterator bound

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#66865]
E.g. in https://github.com/rust-lang/miri/pull/1083/files?utf8=%E2%9C%93&diff=unified&w=1#r352037361 we had to use weird code to check that the iterator is the same length as a slice.

After changing the `fn args_iter` function to have an ExactSizeIterator bound, we should undo the hack

This issue has been assigned to @hashedone via [this comment](https://github.com/rust-lang/rust/issues/66865#issuecomment-562749644).

**Comment by osa1** [comment]
What do you mean by "many"? Is this about grepping `impl Iterator` returns in `std` and replacing them with `impl ExactSizeIterator` whenever possible? I'd like to give this a try but not sure what exactly this is asking.

**Comment by oli-obk** [comment]
Ah, not libstd, just in the compiler. But yea, you got the right idea, grep for it, see if it can be ExactSizeIterator, if not leave it

**Comment by hashedone** [comment]
Hi, this looks pretty easy and I would actually try to get involved into rustc - could I take this one as starting point for incoming weekend?

**Comment by osa1** [comment]
@hashedone Go for it. Just search for `impl Iterator` returns in the compiler source code and replace them with `impl ExactSizeIterator` whenever possible.
