### ISSUE TITLE
Documentation for sys::unix::fd::FileDesc::drop is confusing

### ISSUE THREAD

**Issue by atomashpolskiy** [rust-lang/rust#66876]
```rust
impl Drop for FileDesc {
    fn drop(&mut self) {
        // Note that errors are ignored when closing a file descriptor. The
        // reason for this is that if an error occurs we don't actually know if
        // the file descriptor was closed or not, and if we retried (for
        // something like EINTR), we might close another valid file descriptor
        // opened after we closed ours.
        let _ = unsafe { libc::close(self.fd) };
    }
}
```

While being strict to the letter of [POSIX close(2)](https://pubs.opengroup.org/onlinepubs/9699919799/functions/close.html), this comment looks to me as a little too abstract and therefore unnecessarily fear-inducing. Maybe it would make sense to expand it by saying that at least some of the major Unix-like systems do make sure to always close the FD, even when `close()` is interrupted, and that this is a pretty rare situation anyway, because it may happen only if a custom signal handler is set by the process. Maybe even provide some illuminating links like [this epic discussion by POSIX workgroup](http://austingroupbugs.net/view.php?id=529). Making so might save time for people, who are not aware of the details of this issue, but nevertheless care enough about their FDs always being closed to start digging the Web for answers :) Thank you for reading.

**Comment by GrigorenkoPV** [comment]
Looks like this piece of code got moved over the last 4 years. Currently the comment in question resides here:

https://github.com/rust-lang/rust/blob/cce6a6e22e715bd74455f2560a956ab920c3a914/library/std/src/os/fd/owned.rs#L176-L180
