### ISSUE TITLE
Link in rust.md is outdated

### ISSUE THREAD

**Issue by TisonKun** [rust-lang/rust#66888]
https://github.com/rust-lang/rust/blob/master/src/doc/reference/index.html gives 404.

**Comment by jonas-schievink** [comment]
What's rust.md? The reference is hosted at https://doc.rust-lang.org/nightly/reference/

**Comment by TisonKun** [comment]
@jonas-schievink this file https://github.com/rust-lang/rust/blob/master/src/doc/rust.md

**Comment by steveklabnik** [comment]
That page is rendered as https://doc.rust-lang.org/rust.html, and the link works there. It's not expected for it to work on GitHub.
