### ISSUE TITLE
Break up libcore/ptr/mod.rs into multiple files

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust#66891]
https://github.com/rust-lang/rust/blob/master/src/libcore/ptr/mod.rs

It is currently at 2974 lines, and applying rustfmt to it puts it over tidy's 3000 line filelength limit.

I will add `// ignore-tidy-filelength` for now because having it formatted is more important than having it below the line count limit, but we will want to follow up with one or more PRs to factor this file better.

**Comment by dtolnay** [comment]
`// ignore-tidy-filelength` added in #66892.

**Comment by TheSamsa** [comment]
I woul like to split it up.
Is there any recommendation on how to cut it?

**Comment by Mark-Simulacrum** [comment]
Moving the impl blocks for `*mut T` and `*const T` to two separate files should drastically reduce the number of lines in the mod.rs file, and I think makes sense in general.
