### ISSUE TITLE
Confusing "this function doesn't have a `self` parameter" hint when using macro

### ISSUE THREAD

**Issue by Patryk27** [rust-lang/rust#66898]
Hi,

```rust
pub struct Foo;

macro_rules! call_bar {
    () => {
        self.bar();
    }
}

impl Foo {
    pub fn foo(&self) {
        call_bar!();
    }
    
    pub fn bar(&self) {
        
    }
}
```
... returns:
```
error[E0424]: expected value, found module `self`
  --> src/lib.rs:5:9
   |
5  |           self.bar();
   |           ^^^^ `self` value is a keyword only available in methods with a `self` parameter
...
10 | /     pub fn foo(&self) {
11 | |         call_bar!();
   | |         ------------ in this macro invocation
12 | |     }
   | |_____- this function doesn't have a `self` parameter
```
([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=ac598b90db1d000f5c88d55661d4fdd7))

Message says `this function doesn't have a 'self' parameter`, even though it *does* have a `self` parameter, which is kinda confusing.

This happens only on beta and nightly, since current stable doesn't provide that hint at all.

Thanks,
Patryk.

**Comment by FireCubez** [comment]
This happened to me on an old nightly (I believe 1.38.0 when it was still nightly, I may be wrong)

**Comment by ChosunOne** [comment]
Running into this issue as well.  What is the actual problem?

**Comment by Ryan1729** [comment]
I just ran into what appears to be the same issue on `1.43.1`, in the context of a trait method.
