### ISSUE TITLE
Specialization does not work correctly during constant evaluation.

### ISSUE THREAD

**Issue by Lymia** [rust-lang/rust#66901]
A crate using specialization I've been working on seems to have broken sometime between `nightly-2019-11-19` and `nightly-2019-11-20`. After a bit of debugging, it seems the issue is that specialization doesn't always work correctly in const contexts.

[This code](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=a22248608ba3b6ee06212a9496ed1644), for example, returns the following:

```
const_bool::<TypeA>: in default impl
const_bool::<TypeB>: in default impl
const_str::<TypeA>: in specialized impl
const_str::<TypeB>: in default impl
run_method::<TypeA>: in specialized impl
run_method::<TypeB>: in default impl
```

On earlier versions, this would have returned the following:

```
const_bool::<TypeA>: in specialized impl
const_bool::<TypeB>: in default impl
const_str::<TypeA>: in specialized impl
const_str::<TypeB>: in default impl
run_method::<TypeA>: in specialized impl
run_method::<TypeB>: in default impl
```

This bug does not happen when the `-Z mir-opt-level=0` flag is set, and it behaves the same as prior versions.

**Comment by oli-obk** [comment]
cc @wesleywiser const prop is evaluating polymorphic code and evaluating to a default instead of bailing out due to being too generic

**Comment by eddyb** [comment]
I'm guessing `Instance::resolve` is missing this bit of logic (NB "polymorphic MIR optimizations"):
https://github.com/rust-lang/rust/blob/8f1bbd69e13c9e04a4c2b75612bc0c31af972439/src/librustc/traits/project.rs#L1075-L1090
