### ISSUE TITLE
ConstEval/ConstProp: get rid of `Panic` error kind

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#66902]
With the Miri engine now having support for properly executing panics, a panicking program does not really constitute an "interpreter error" any more. So we should get rid of the `InterpError::Panic` variant.

* We'll need to decide what else to do with the `throw_panic!` that still exist. [This one](https://github.com/rust-lang/rust/blob/8f1bbd69e13c9e04a4c2b75612bc0c31af972439/src/librustc_mir/interpret/place.rs#L390) I think should be `throw_ub!` instead; same for the "division/remainder by zero" [in this file](https://github.com/rust-lang/rust/blob/8f1bbd69e13c9e04a4c2b75612bc0c31af972439/src/librustc_mir/interpret/operator.rs). With well-formed MIR I think those are all unreachable, but I see no harm in letting Miri also support some "reasonable" MIR that rustc would never emit (such as omitting the bounds check on an array access, or the div-by-zero check). [Overflowing pointer arithmetic](https://github.com/rust-lang/rust/blob/8f1bbd69e13c9e04a4c2b75612bc0c31af972439/src/librustc/mir/interpret/pointer.rs#L91) should also be UB I think.
* ConstEval should probably format an error message directly when a panic occurs ([here](https://github.com/rust-lang/rust/blob/8f1bbd69e13c9e04a4c2b75612bc0c31af972439/src/librustc_mir/interpret/intrinsics.rs#L372) or in the new `assert_panic` hook added by https://github.com/rust-lang/rust/pull/66874). This could be propagated outwards via a new `MachineError(String)` variant of `InterpError`, if nothing else fits.
* I am not sure what ConstProp should do. The `throw_panic!` mentioned above are, I think, currently actually hit by ConstProp -- but maybe those same errors can be better shown by determining that the condition of an `Assert` terminator is constant, and indeed that might explain why we currently sometimes have duplicate error messages. It also contains a `throw_panic!` [here](https://github.com/rust-lang/rust/blob/8f1bbd69e13c9e04a4c2b75612bc0c31af972439/src/librustc_mir/transform/const_prop.rs#L489).

Cc @oli-obk @wesleywiser

**Comment by wesleywiser** [comment]
> ConstProp -- but maybe those same errors can be better shown by determining that the condition of an Assert terminator is constant

Unless I'm not understanding what you're saying, that's exactly how it currently works in ConstProp:

https://github.com/rust-lang/rust/blob/d8bdb3fdcbd88eb16e1a6669236122c41ed2aed3/src/librustc_mir/transform/const_prop.rs#L817-L822

**Comment by RalfJung** [comment]
> that's exactly how it currently works in ConstProp

Yeah I think that is what I imagined. So I will start by experimenting with replacing the `throw_panic!` that we have with `throw_ub!`.

**Comment by RalfJung** [comment]
>  I will start by experimenting with replacing the throw_panic! that we have with throw_ub!.

PR opened at https://github.com/rust-lang/rust/pull/66927.

**Comment by RalfJung** [comment]
> With well-formed MIR I think those are all unreachable

Turns out that assumption is wrong: the MIR of promoteds actually is not well-formed in this sense; it can contain unchecked array/slice accesses.
