### ISSUE TITLE
Slightly incorrect help message with mismatched typs in async code

### ISSUE THREAD

**Issue by jfrimmel** [rust-lang/rust#66910]
The following works, since `foo` and `bar` return `()`, so the expression is simply returned:
```rust
fn foo() {}
fn bar() {
    foo()
}
```
The "equivalent" code in the `async` context yields a compiler error:
```rust
async fn foo() {}
async fn bar() {
    foo()
}
```
```
error[E0308]: mismatched types
  --> src/main.rs:62:5
   |
62 |     foo()
   |     ^^^^^- help: try adding a semicolon: `;`
   |     |
   |     expected (), found opaque type
   |
   = note: expected type `()`
              found type `impl core::future::future::Future`
```
The help message would be correct for non-async-code with mismatched types, but in the async case a `.await` should be suggested.

Technically the current help message is correct, but leads to another warning (that can be even overlooked):
```
warning: unused implementer of `core::future::future::Future` that must be used
  --> src/main.rs:62:5
   |
62 |     foo();
   |     ^^^^^^
   |
   = note: `#[warn(unused_must_use)]` on by default
   = note: futures do nothing unless you `.await` or poll them
```
So you have to do a second compile iteration.

I'd suggest to spawn a help message like that:
```
error[E0308]: mismatched types
  --> src/main.rs:62:5
   |
62 |     foo()
   |     ^^^^^- help: try to await the future: `.await`
   |     |
   |     expected (), found opaque type
   |
   = note: expected type `()`
              found type `impl core::future::future::Future`
```

**Comment by jfrimmel** [comment]
Note: this is the message with the current nightly (_rustc 1.41.0-nightly (25d8a9494 2019-11-29)_).
Rust 1.39 does not even spawn the help message

**Comment by nikomatsakis** [comment]
Async await traige: marking as on-deck, as suggesting the use of `.await` seems pretty useful and general

**Comment by Aaron1011** [comment]
I started working on this, then realized that it already exists: https://github.com/rust-lang/rust/pull/62067

However, it looks like we don't currently attempt to emit suggestions for certain coercions (including the return type coercion), which is why it doesn't show up here. I'm working on emitting coercion suggestions in more places.
