### ISSUE TITLE
rustdoc: consolidate multiple identical "supported with *feature* only"

### ISSUE THREAD

**Issue by birkenfeld** [rust-lang/rust#66921]
See https://docs.rs/tokio/0.2.2/tokio/sync/index.html under the **Modules** heading:

![image](https://user-images.githubusercontent.com/144359/69911239-dbf10d80-1418-11ea-86ca-9c28b5e4f79e.png)

**Comment by GuillaumeGomez** [comment]
Pretty funny!

**Comment by hirschenberger** [comment]
I'd like to give this a try.
