### ISSUE TITLE
union pseudo keyword is no longer accepted in enum variant position as of 2019-11-25

### ISSUE THREAD

**Issue by CAD97** [rust-lang/rust#66943]
[playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=73cb95fefead52beaa4e1ccc8a1a410b)

```rust
enum Rule {
    union,
}
```

Initially reported in https://github.com/arabidopsis/typescript-definitions/issues/4 and then https://github.com/pest-parser/pest/issues/429.

My best guess is https://github.com/rust-lang/rust/pull/66592; cc @estebank 

This issue has been assigned to @kamleshbhalui via [this comment](https://github.com/rust-lang/rust/issues/66943#issuecomment-560559372).

**Comment by CAD97** [comment]
Interesting note: this does not apply to `async` when in `edition=2015` mode.

**Comment by Centril** [comment]
Regression introduced in #66641. My bad... should have remembered that `union` is contextual!

The fix should be to remove this line:
https://github.com/rust-lang/rust/blob/4007d4ef26eab44bdabc2b7574d032152264d3ad/src/librustc_parse/parser/item.rs#L1742

and add a regression test for `enum A { union }`, `enum B { union {} }`, and `enum C { union() }`.

**Comment by estebank** [comment]
You'll need to change

```rust
    fn recover_nested_adt_item(&mut self, keyword: Symbol) -> PResult<'a, bool> {
        if self.token.is_keyword(kw::Enum) ||
            self.token.is_keyword(kw::Struct) ||
            self.token.is_keyword(kw::Union)
        {
```

to something along the lines of

```rust
    fn recover_nested_adt_item(&mut self, keyword: Symbol) -> PResult<'a, bool> {
        if (self.token.is_keyword(kw::Enum) ||
            self.token.is_keyword(kw::Struct) ||
            self.token.is_keyword(kw::Union))
            && self.look_ahead(1, |t| t.is_ident())
        {
```
