### ISSUE TITLE
Almost unable to even download

### ISSUE THREAD

**Issue by Y-Less** [rust-lang/rust#66953]
**Problem**
Windows download link was not on the getting started page:

![image](https://user-images.githubusercontent.com/991078/69952519-a2430400-14f7-11ea-8d4f-505782bacd9a.png)

**Steps**

1. Go to the homepage on Windows.
2. Not be detected as using Windows (don't know how to reproduce this).
3. No "No I'm not" link.  There is a "Other installation methods" link, but it is a 404.

**Possible Solution(s)**
I eventually found a link to the Windows installer in the rustp repo, but it wasn't obvious.

**Comment by jonas-schievink** [comment]
As this is an issue with the website, please file it over at https://github.com/rust-lang/www.rust-lang.org/. It might also be an issue with your browser (maybe it's deliberately setting a user agent that makes it show up as a Unix-like OS).
