### ISSUE TITLE
On identifier not found, detect swapped words

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#66968]
On identifiers that have more than one word, it is relatively common to write them in the wrong order (`foo_bar_baz` → `foo_baz_bar`). These are normally not found by Levenshtein distance checks, but we could do a basic "split on `_`, sort and join before comparison" so that we could suggest the right identifier.

This issue has been assigned to @cjkenn via [this comment](https://github.com/rust-lang/rust/issues/66968#issuecomment-570732117).

**Comment by LeSeulArtichaut** [comment]
I'd like to try to work on this.

As `foo_bar_baz` is short enough to be caught by the Levenstein distance, I wrote [this example](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=a895b9c42ea9f4238e5fe8fec4194cf6) for testing:

```Rust
fn main() {
    let long_variable_name = true;
    println!("{}", long_name_variable);
}```

@rustbot claim

**Comment by LeSeulArtichaut** [comment]
@estebank I'm thinking about the priority of the different possible matches. I tend to think that a match found by levenstein distance should have a greater priority, but what do you think?

**Comment by estebank** [comment]
@LeSeulArtichaut it's tricky. I feel that your instinct might be right but we'd only know when looking at real world usage. The nice thing is that the lev distance check by its very nature it is limited, so doing the swapped words check as a fallback should work out ok in practice.

**Comment by LeSeulArtichaut** [comment]
Releasing my assignment, as I am not sure to be able to commit.
In case someone want to take on this, here is the function that should be modified.
https://github.com/rust-lang/rust/blob/ae1b871cca56613b1af1a5121dd24ac810ff4b89/src/libsyntax/util/lev_distance.rs#L46-L82
@rustbot release-assignment

**Comment by LeSeulArtichaut** [comment]
(I think this is appropriate, please tell me if it isn't)
@rustbot modify labels to +E-Easy

**Comment by cjkenn** [comment]
I can take a stab at this, seems reasonable with previous comments.

@rustbot claim
