### ISSUE TITLE
What is the difference between `async move || {}` and `|| async move {}` ?

### ISSUE THREAD

**Issue by unegare** [rust-lang/rust#66986]
the question was initially posted here: 
https://stackoverflow.com/questions/59156473/what-is-the-difference-between-async-move-and-async-move

But for remaining unresolved there I think that it may be answered here.

**Comment by jonas-schievink** [comment]
Hi! This issue tracker is mainly meant for bug reports and concrete, small feature requests. Questions like this are better asked in the user forum at https://users.rust-lang.org/ or on [one of the chat platforms](https://www.rust-lang.org/community) used by the Rust community.
