### ISSUE TITLE
Google Code In 

### ISSUE THREAD

**Issue by Alexsabou135** [rust-lang/rust#66992]
```rust
fn main() {
    println!("Hello,GCI!");
}
```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a66b3bc1cfb9c5ab771bf23c87be3119))

Output:

```
Hello,GCI!

```

Errors:

```
   Compiling playground v0.0.1 (/playground)
    Finished dev [unoptimized + debuginfo] target(s) in 0.65s
     Running `target/debug/playground`

```

**Comment by jhpratt** [comment]
What exactly is this supposed to be?

**Comment by jonas-schievink** [comment]
Closing since there does not seem to be an issue here.

**Comment by csmoe** [comment]
welcome to the rust-lang community :)
It's not an error, just some output from https://github.com/rust-lang/cargo, which is rust's build system,
a typical error should look like this with explicit `error` message:
```rust
error: incorrect close delimiter: `}`
 --> src/main.rs:3:1
  |
1 | fn main() {
  |           - close delimiter possibly meant for this
2 |     println!("Hello,GCI!"
  |             - un-closed delimiter
3 | }
  | ^ incorrect close delimiter

error: aborting due to previous error

error: could not compile `playground`.

To learn more, run the command again with --verbose.
```
