### ISSUE TITLE
run-make/thumb-none-cortex-m is no-op due to incompatible `# only-target` directives

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#67018]
I was working on making a run-make test today for a particular thumb target.

While looking over how we do this elsewhere, I found this bit of code:

https://github.com/rust-lang/rust/blob/5f1d6c44034ac143f7a3e56ae7ea8858dcbb61ca/src/test/run-make/thumb-none-cortex-m/Makefile#L13-L16

From my local testing, it seems like having multiple `# only-target` lines of this form has the net effect of making the test a no-op that does not test anything: since a target matching line 13 will not match line 14, and vice versa, there are no targets that can run on this test.

We should either revert the portion of the commit that did this:

https://github.com/rust-lang/rust/commit/f15d20c1f78c220d0790b13e2af30670053ee0d8#diff-463654a579bb644f5d94cd0e1a6ff232

```diff
- # See https://stackoverflow.com/questions/7656425/makefile-ifeq-logical-or
- ifneq (,$(filter $(TARGET),thumbv6m-none-eabi thumbv7em-none-eabi thumbv7em-none-eabihf thumbv7m-none-eabi))
+ # only-thumbv6m-none-eabi
+ # only-thumbv7em-none-eabi
+ # only-thumbv7em-none-eabihf
+ # only-thumbv7m-none-eabi
```

or figure out some other way to express the desired property here

(or change the semantics of `# only-target` when multiple targets are provided to make it gather all such targets up in a set before doing the check for membership... but I am wary of making such a change since doing it right would require differentiating e.g. processor target vs OS target, for example...)

**Comment by pnkfelix** [comment]
Also, It looks like there may be other instances of the same mistake elsewhere in the test suite, such as in:


https://github.com/rust-lang/rust/blob/5f1d6c44034ac143f7a3e56ae7ea8858dcbb61ca/src/test/run-make/thumb-none-qemu/Makefile#L3-L4

**Comment by jonas-schievink** [comment]
Oof, not good. It shouldn't be hard to make rustbuild outright reject this scenario though.

**Comment by pnkfelix** [comment]
Further effort on #67020 has led me to conclude that these `# only-target` lines do not work at all, at least not for cross-compilation.
