### ISSUE TITLE
i686-pc-windows-msvc: remove pdb file

### ISSUE THREAD

**Issue by 220160239** [rust-lang/rust#67012]
I compile on i686-pc-windows-msvc, the output file (*.exe) include RSDS information. I do not need pdb file, how can I remove it ?

**Comment by jonas-schievink** [comment]
Have you tried compiling without debug info?

**Comment by 220160239** [comment]
> Have you tried compiling without debug info?

I tried set debug=false in cargo.toml, but pdb file still existed.

**Comment by jonas-schievink** [comment]
Cargo does not remove old files when recompiling. Deleting the file should work.

**Comment by 220160239** [comment]
> Cargo does not remove old files when recompiling. Deleting the file should work.

I delete the whole target folder,  set "[profile.release]  debug = false" in cargo.toml, then execute “cargo build --release”, the pdb file is still there.  Is there something I ignored ?

**Comment by retep998** [comment]
Rust will always ask the linker to emit debug info for `-msvc` targets, regardless of whether `debug` is true or false. Is the issue that emitting a PDB file causes the linker to hardcode a path to the PDB in your binary and you don't want that for security reasons? If so, you can use the `-Clink-arg` rustc command line parameter to pass `/DEBUG:NONE` to the linker.

**Comment by 220160239** [comment]
> Rust will always ask the linker to emit debug info for `-msvc` targets, regardless of whether `debug` is true or false. This is intended behavior and not a bug.
> 
> Is the issue that emitting a PDB file causes the linker to hardcode a path to the PDB in your binary and you don't want that for security reasons? If so, you can use the `-Clink-arg` rustc command line parameter to pass `/DEBUG:NONE` to the linker.

Thinks,  that's the solution.

**Comment by csmoe** [comment]
Closes as resolved.
