### ISSUE TITLE
libstd: Store capacity of std::vec::Vec on the heap?

### ISSUE THREAD

**Issue by michaelwoerister** [rust-lang/rust#67024]
This has probably been discussed before but in case it hasn't: It should be possible to store a vec's capacity as part of its heap allocation and thus shrink `Vec` from three to two words. It would make a difference for code that contains many empty `Vec`s and code that moves them around a lot. The downside is that the implementation is a bit more complicated and that the capacity can only be accessed after following a pointer. It might still be a worthwhile trade off.

cc @rust-lang/libs (and @nnethercote who likes this kind of thing `:)`)

**Comment by SimonSapin** [comment]
Why just the capacity and not also the length? https://crates.io/crates/thin-vec does that.

Either way, this may not be possible or desirable for `std::vec::Vec<T>` since we have existing APIs like `From<Box<T>>` or `from_raw_parts`.

> It would make a difference for code that contains many empty `Vec`s and code that moves them around a lot.

If you have specific pieces of code in mind, try changing it to use `ThinVec` or something like it?

**Comment by Amanieu** [comment]
This was attempted with `HashMap` but the results seemed to be in the noise:
- https://github.com/rust-lang/hashbrown/pull/76
- https://github.com/rust-lang/rust/pull/60470

**Comment by michaelwoerister** [comment]
> Why just the capacity and not also the length?

I would expect that the length needs to be accessed more often than the capacity, so it would be less good of a trade-off. Hard to tell without a set of reference benchmarks though.

Thanks for the links, @Amanieu! 

Feel free to close this issue if you have reason to believe that it won't improve performance/memory consumption or just isn't worth the trouble.

**Comment by SimonSapin** [comment]
>  this may not be possible […] for `std::vec::Vec<T>`

I think this is the first concern for this proposal as is. But that doesn’t mean that having *some* container like that isn’t worth investigating.

**Comment by michaelwoerister** [comment]
The docs for `from_raw_parts` says

> - `ptr` needs to have been previously allocated via String/Vec<T> (at least, it's highly likely to be incorrect if it wasn't).

So it's possible to make this work, probably, but would also probably break lots of code in the wild.

**Comment by KrishnaSannasi** [comment]
Given that we guarantee 

> Most fundamentally, Vec is and always will be a (pointer, capacity, length) triplet. No more, no less. The order of these fields is completely unspecified, and you should use the appropriate methods to modify these. The pointer will never be null, so this type is null-pointer-optimized.

This is not possible

**Comment by michaelwoerister** [comment]
Well, that decides it `:)` Great find, @KrishnaSannasi!
