### ISSUE TITLE
Code-in Rust Hello

### ISSUE THREAD

**Issue by hussen2003** [rust-lang/rust#67030]
```rust
fn main() {
    println!("Hello, GCI!");
}
```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=7f2df80bfbf725d885a701228ca5ce51))

**Comment by Mark-Simulacrum** [comment]
Closing as this does not appear to be an issue.

**Comment by qnighy** [comment]
#66992 has a similar code snippet. I guess someone is teaching Rust using Rust Playground and this issue is created mistakingly by clicking the "Open an issue on the Rust GitHub repository" link?

**Comment by jonas-schievink** [comment]
There were some misleading instructions on the Google Code-In site, I've messaged the people running it and they've fixed it, so this shouldn't happen again
