### ISSUE TITLE
locate the static library in system directories

### ISSUE THREAD

**Issue by richardchey** [rust-lang/rust#67050]
the code can solve the problem , but it isn't my attention. my real problem is why this error occurred only in this case.

```rust
fn main() {
    println!("cargo:rustc-link-search=<crypto-path>");
    println!("cargo:rustc-link-lib=static=crypto");
}
```
might help here, and this issue belongs to https://github.com/rust-lang/cargo , if you this doesn't work, please file an issue there.

_Originally posted by @csmoe in https://github.com/rust-lang/rust/issues/66861#issuecomment-559705956_

**Comment by csmoe** [comment]
Thanks for clarifying, please open this issue at https://github.com/rust-lang/cargo , rustc has nothing to do with this kind of linking.
