### ISSUE TITLE
Make librustc_error_code dynamically linked so it doesn't rebuild everything every time

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/rust#67061]

**Comment by jyn514** [comment]
@GuillaumeGomez this issue is quite old and doesn't have a description. Is it still relevant? If so, can you talk more about what problem it's trying to solve and the proposed fix?

**Comment by GuillaumeGomez** [comment]
No I think it's not an issue anymore. The build system has been remade quite a few times since then. Closing.
