### ISSUE TITLE
HashMap documentation inconsistency

### ISSUE THREAD

**Issue by brprice** [rust-lang/rust#67093]
The online docs (https://doc.rust-lang.org/std/collections/hash_map/index.html) claim that
  - for the module: "A hash map implemented with linear probing and Robin Hood bucket stealing."
(from https://github.com/rust-lang/rust/blob/master/src/libstd/collections/mod.rs#L436)
  - for the HashMap struct: "A hash map implemented with quadratic probing and SIMD lookup."
(from https://github.com/rust-lang/rust/blob/master/src/libstd/collections/hash/map.rs#L17)

I suspect the module docs are out of date, and should have been updated in https://github.com/rust-lang/rust/commit/cf46bd5037a86237b9be4eb218d57d71bb8e2ccf.

**Comment by TheSamsa** [comment]
I'll do that, if it is fine to be done by a non english native speaker.
