### ISSUE TITLE
Very slow binary execution after build if network connection exists but works slow

### ISSUE THREAD

**Issue by olegnn** [rust-lang/rust#67095]
Following code, executed right after fresh build using `cargo +nightly run --offline`  command
```rust
fn main() { 
    println!("Running..."); 
}
```
took 23 seconds to run.
```
$ time cargo +nightly run --offline
   Compiling strange v0.1.0 (/Users/oleg/Documents/strange)
    Finished dev [unoptimized + debuginfo] target(s) in 0.39s
     Running `target/debug/strange`
Running...
cargo +nightly run --offline  0,20s user 0,14s system 1% cpu 23,153 total
```
But my current record is 1 minute.
```
cargo +nightly run --offline 0,56s user 0,31s system 1% cpu 1:04,35 total
```
It looks like even with `--offline` flag it attempts to make some network request(s) if network connection is established.

**Comment by jonas-schievink** [comment]
Does this also happen if you run the compiled executable directly (`target/debug/strange`)?

**Comment by olegnn** [comment]
This happens **only** after fresh build. (If execute the same code twice, it works fine)
If run directly, it builds fast
```
$ time cargo +nightly build
   Compiling strange v0.1.0 (/Users/oleg/Documents/strange)
    Finished dev [unoptimized + debuginfo] target(s) in 0.54s
cargo +nightly build  0,20s user 0,16s system 64% cpu 0,562 total
```
and executes instantly
```
$ time ./target/debug/strange
Running...
./target/debug/strange  0,00s user 0,00s system 0% cpu 0,362 total
```

**Comment by jonas-schievink** [comment]
In that case this looks like a Cargo bug, so please file this at https://github.com/rust-lang/cargo
