### ISSUE TITLE
api-ms-win-core-rtlsupport-l1-2-0 is missing

### ISSUE THREAD

**Issue by 220160239** [rust-lang/rust#67188]
Compile icedtea-web on i686-pc-windows-msvc, the output javaws.exe can not be started on win7 or win2008, the error message is "The program can't start because api-ms-win-core-rtlsupport-l1-2-0 is missing from your computer. Try reinstalling the program to fix this program",  But it can be started on win10 and win2012. What's the reason?

**Comment by mati865** [comment]
Cc @retep998

**Comment by retep998** [comment]
The Rust standard library does not link to anything that would cause a dependency on `api-ms-win-core-rtlsupport-l1-2-0`. Something in your code or one of your dependencies is linking to a system library that results in a dependence on `api-ms-win-core-rtlsupport-l1-2-0`. If you want to maintain compatibility with Windows 7 you'll have to modify whatever is doing that.
