### ISSUE TITLE
Trait bounds don't work on default associated types

### ISSUE THREAD

**Issue by pythondude325** [rust-lang/rust#67187]
Trait bounds fail for default associated types, but not for re-assigned associated types.

The following code does not compile as seen in [this playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=3b5078eddbef70496303d67d53e62c54).
```rust
#![feature(associated_type_defaults)]

trait T {
    type Item = ();
}

struct Foo;
impl T for Foo {}

fn f<I: T>() -> I::Item where I::Item: Default {
    Default::default()
}

fn main(){
    f::<Foo>();
}
```
This gives the error ``error[E0277]: the trait bound `<Foo as T>::Item: std::default::Default` is not satisfied``

But the code does compile if `impl T for Foo {}` is replaced with
```rust
impl T for Foo {
    type Item = ();
}
```
as seen on [this playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=0cf56d1acbaed124fa3c52b14348b4a8)

## Meta

`rustc --version --verbose`:
```
rustc 1.41.0-nightly (59947fcae 2019-12-08)
binary: rustc
commit-hash: 59947fcae6a40df12e33af8c8c7291014b7603e0
commit-date: 2019-12-08
host: x86_64-unknown-linux-gnu
release: 1.41.0-nightly
LLVM version: 9.0
```

**Comment by Centril** [comment]
cc @jonas-schievink

**Comment by jonas-schievink** [comment]
This will be fixed by https://github.com/rust-lang/rust/pull/61812, but I'm not adding a test for this issue specifically since there are already plenty (and the normalization of the assoc. type is controlled by flipping a single `bool` in librustc).
