### ISSUE TITLE
[NLL] Should this code compile with NLL?

### ISSUE THREAD

**Issue by quixoticaxis** [rust-lang/rust#67201]
Here's the code:
```rust
fn main() {
    let mut v = vec![1, 2, 3];
    v.swap(0, v.iter().position(|num| *num == 3).unwrap());
}
```
Should this code compile? And what is the right place to ask questions about it?
I've got here following some awesome rustaceans' advises to read [this RFC](https://github.com/rust-lang/rfcs/pull/2025) and then [this tracking issue](https://github.com/rust-lang/rust/issues/43234).

**Comment by jonas-schievink** [comment]
No, I believe this needs full two-phase borrows (https://github.com/rust-lang/rust/issues/46901).

> And what is the right place to ask questions about it?

It's best to ask question on the [user forum](https://users.rust-lang.org/), the `/r/rust` subreddit, or Discord (or any other chat platform used by Rustaceans). If it's something about the feature tracked by the tracking issue, that isn't outlined in the RFC, then it might also be appropriate to drop a comment in the tracking issue.
