### ISSUE TITLE
Shared borrow of the data inside a mutex

### ISSUE THREAD

**Issue by Luro02** [rust-lang/rust#67229]
I would like to borrow the internal data of the mutex (immutable), therefore it would be nice to have such a function:

```rust
impl<T> Mutex<T> {
    fn get_ref(&self) -> LockResult<&T> {
        // The data is borrowed immutably, so
        // there's no need to lock the inner mutex.
        let data = unsafe { &*self.data.get() };
        poison::map_result(self.poison.borrow(), |_| data)
    }
}
```

# Concerns
Does this cause any problems with multiple threads accessing the data?
I think this can only cause problems, if there is already an exclusive borrow in use.

# Benefits
Having this function could allow implementing PartialEq (and other traits) on types, that use a Mutex

```rust
struct UsesMutex {
   data: Mutex<usize>
}

impl PartialEq for UsesMutex {
    fn eq(&self, other: &Self) -> bool {
         self.data.get_ref() == other.get_ref()
    }
}
```

**Comment by sfackler** [comment]
```
        // The data is borrowed immutably, so
        // there's no need to lock the inner mutex.
```

That is not true at all. Some other thread could modify the value you have a reference to while you hold it.
