### ISSUE TITLE
Implement PartialEq for Cursor

### ISSUE THREAD

**Issue by Luro02** [rust-lang/rust#67226]
I am thinking about something like this
```rust
impl<T: PartialEq> PartialEq for Cursor<T> {
    fn eq(&self, other: &Self) -> bool { self.get_ref() == other.get_ref() && self.position() == other.position() }
}
```
is there a reason why this is not implemented?

**Comment by jonas-schievink** [comment]
This implementation would mean that two Cursors pointing at different positions of the same data would compare equal (can be fixed by also comparing `position`, of course).

**Comment by Luro02** [comment]
I updated the implementation
