### ISSUE TITLE
core::slice::Iter and core::slice::IterMut aren't NonNull-optimized

### ISSUE THREAD

**Issue by Kixunil** [rust-lang/rust#67228]
I randomly noticed that [`self.ptr`](https://github.com/rust-lang/rust/blob/master/src/libcore/slice/mod.rs#L3367) of `core::slice::Iter` [may never be null](https://github.com/rust-lang/rust/blob/master/src/libcore/slice/mod.rs#L3219) (also because of [unconditionally calling `from_raw_parts`](https://github.com/rust-lang/rust/blob/master/src/libcore/slice/mod.rs#L3162)), but it's not contained in `NonNull<T>`, so it isn't optimized.

I [double checked](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=f5dd15dfc1372d25e2ecdc154b65369b) for compiler internal Voodoo and it confirms the lack of optimization.

I was thinking about fixing it just for fun, but it occurred to me that the current code uses `assume` at several places and maybe it'd be a good idea to rather add `assume` into `NonNull::as_ptr` to clean it up? Not sure, so I'm asking. (Also maybe add assume to `<[T]>::as_ptr()`, but that's a different topic.)

**Comment by Mark-Simulacrum** [comment]
I suspect that directly using NonNull here is much better than an assume inside NonNull::as_ptr; assume often has poor interactions with LLVM's optimizer (especially when frequently inserted, as it would be with e.g., NonNull::as_ptr).

I would personally accept a PR that fixes this assuming that the code is improved by such a change and benchmarks do not regress.

**Comment by Kixunil** [comment]
I'm highly surprised `assume` has poor interactions, I'd expect it to be noop at worst. Sounds like an LLVM bug?

Anyway, I guess I'd go with minimal PR that doesn't mess with it.

**Comment by Mark-Simulacrum** [comment]
`assume` can "overfit" by providing too much information in ways that LLVM is not quite prepared for essentially. The minimal PR is likely better in any case :)
