### ISSUE TITLE
Accept samurai as ninja alternative

### ISSUE THREAD

**Issue by pickfire** [rust-lang/rust#67231]
[Samurai](https://github.com/michaelforney/samurai) is a ninja-compatible build system written in C (rather than C++) and is shorter as in lines of code (not verified) so probably performs faster than ninja. It would be good to allow to specify the use of samurai as an alternative to ninja.

See similar discussion from alpine linux https://lists.alpinelinux.org/~alpine/devel/%3CBYZDB5LH4OVY.9FDVF5I3J954%40homura%3E

**Comment by hellow554** [comment]
Why not RIIR? ;)

Seriously:
If it's compatible, what stops you from using it, if you like? Just make a symlink or similar. 
Why do you think rust should use samurai instead of ninja?

**Comment by steveklabnik** [comment]
As far as I know, ninja is only used for LLVM, so this bug report would have to go to them, not to us.

**Comment by Mark-Simulacrum** [comment]
Yes, if LLVM gains support for other build tools (?) then we'd be happy to pipe that support through via a PR into config.toml, but otherwise I don't think this is issue is directly actionable for us, so I'm going to close. Thanks!
