### ISSUE TITLE
Recursion limit silently ignored if it overflows a `usize`

### ISSUE THREAD

**Issue by ecstatic-morse** [rust-lang/rust#67265]
The following code [fails to compile](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=8b1e97d1ea8d2a581bd5024935dea292) since it exceeds the default recursion limit. Using `2056` as the recursion limit works as expected.

```rust
#![recursion_limit = "99999999999999999999999999999999999999999999999999999"]
//#![recursion_limit = "2056"]

macro_rules! explode {
    (recurse; $head:tt $($tail:tt)*) => { explode!(recurse; $($tail)*); };
    (recurse;) => {};
    
    (0; $($tt:tt)*) => { explode!(1; $($tt)* $($tt)* $($tt)*); };
    (1; $($tt:tt)*) => { explode!(2; $($tt)* $($tt)* $($tt)*); };
    (2; $($tt:tt)*) => { explode!(3; $($tt)* $($tt)* $($tt)*); };
    (3; $($tt:tt)*) => { explode!(recurse; $($tt)* $($tt)* $($tt)*); };
}

explode!(0; a b c);
```

This is because we don't check for integer overflow errors when parsing limits:

https://github.com/rust-lang/rust/blob/e9469a6aec2f49fa1e2ae670649f293866932253/src/librustc/middle/recursion_limit.rs#L19-L33

There's a few options here. My preference would be to silently default to `usize::MAX` when overflow occurs.

This issue has been assigned to @fisherdarling via [this comment](https://github.com/rust-lang/rust/issues/67265#issuecomment-565265070).

**Comment by fisherdarling** [comment]
Hi! I'd like to try and handle this. If I understand this correctly, we should check if there is an `ParseIntError`, and if that error is an overflow. If it's an overflow, we default to `usize::MAX`?

@rustbot claim

**Comment by estebank** [comment]
@fisherdarling correct
