### ISSUE TITLE
Consider precedence btw `pat : type` (ascription) & `p0 | ... | pn` (or_patterns)

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#67309]
We should ensure that we consider the precedence of type ascription in relation to or-patterns, e.g.

```rust
let A(x) | B(y): T;
```

should probably bind as `(A(x)) | (B(y): T)` and not `(A(x) | B(x)): T`. This might not make a semantic difference because both sides should be of the same type, but parsing in the right way is a more iron-clad guarantee of forward-compatibility.

For `@`-patterns, this should ideally also bind as `binding @ (sub: T)` as opposed to `(binding @ sub): T` when writing e.g. `let binding @ sub: T;`. This might be observable via type checking of things like `let ref binding @ A(_): T = scrutinee;` but fortunately `binding: &T` holds here and not `binding: T` so like with or-patterns above we might be good. Still, before stabilizing `F-bindings_after_at` (e.g. `binding @ Some(sub_binding)`) we should endeavor to be more sure.

**Comment by chenyukang** [comment]
Closing now for https://github.com/rust-lang/rust/issues/101728
