### ISSUE TITLE
Sharing nightly target dir between Docker containers doesn't work correctly

### ISSUE THREAD

**Issue by ascclemens** [rust-lang/rust#67301]
Sorry in advance if this is the wrong place for this issue; I'm not sure about the root cause.

When caching the target directory of a build done in a Docker container, restoring
the directory on a different instance of the same container causes many, but not all,
dependencies to be rebuilt.

I can only reproduce this on nightly (`rust version 1.41.0-nightly (3eeb8d4f2 2019-12-12)` as a tested example); stable works as expected.

## Minimal reproduction

This works with `podman` and `docker`.

1. Make a new directory and start a new cargo project in it.
   
   ```sh
   cargo init --bin
   ```
2. Add `proc-macro2 = "1"` to your Cargo.toml dependencies.
3. Start a Docker container with the directory mounted in the
   container.
   
   ```sh
   docker run --rm -it -v "$(pwd)":/src rust:slim
   ```
4. Install the nightly toolchain.
   
   ```sh
   rustup toolchain add nightly
   ```
5. Build the project.

   ```sh
   cd /src
   cargo +nightly build
   ```
6. "Cache" the result.

   ```sh
   tar czf cache.tar.gz target
   ```
7. Ensure restoring the cache works as expected.
   
   ```sh
   rm -rf target
   tar xf cache.tar.gz
   cargo +nightly build
   rm -rf target
   ```
   
   `proc-macro2` should not be rebuilt.
8. Exit the container (`exit` or `Ctrl-D`).
9. Start a new container exactly as we started the previous one.

   ```sh
   docker run --rm -it -v "$(pwd)":/src rust:slim
   ```
10. Install nightly again.
    ```sh
	rustup toolchain add nightly
	```
11. Restore the cache and build.

	```sh
	cd /src
	tar xf cache.tar.gz
	cargo +nightly build
    ```

Notice that after step 11, `proc-macro2` is rebuilt. If you attempt
these steps on stable, `proc-macro2` will not be rebuilt.

**Comment by Elinvynia** [comment]
Perhaps a stupid question, but is the nightly version the exact same between the builds?

**Comment by ascclemens** [comment]
In the example, yes, they were the same version. However, I can no longer reproduce this using the current nightly. I *can* reproduce it on `1.41.0-nightly (27d6f55f4 2019-12-11)`, but it seems like this has been fixed since then.

**Comment by Elinvynia** [comment]
If it works on stable and has worked on nightly for a while then it's okay to consider this fixed, thank you for taking the time to report this and sorry it has taken this long to respond to this!
