### ISSUE TITLE
Extend bindings_after_at (`b1 @ Some(b2)`) tests with nested `or_patterns`

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#67311]
Once `#![feature(or_patterns)]` (#54883), i.e. `pat_0 | ... | pat_n` in nested positions, e.g. `Some(Ok(a) | Err(b))` have progressed sufficiently in their implementation, e.g. when the MIR building implementation is done, we should extend the test suite for `#![feature(bindings_after_at)]` (#65490), e.g. `b1 @ Some(b2)`, to exercise the combination of these two features. Ideally, we would also account for the combination of those two with `#![feature(slice_patterns)]` (#62254) and `#![feature(box_patterns)]` (#29641) as well to make things really air-tight.

This issue has been assigned to @thekuom via [this comment](https://github.com/rust-lang/rust/issues/67311#issuecomment-594281379).

**Comment by Centril** [comment]
This is almost unblocked now that https://github.com/rust-lang/rust/pull/66296 has landed. However, we need more progress on or-patterns.

**Comment by thekuom** [comment]
Can I work on this one?

**Comment by Centril** [comment]
Sure, go right ahead.

@rustbot assign thekuom
