### ISSUE TITLE
Support Intel IceLake ISAs through target_feature

### ISSUE THREAD

**Issue by elalfer** [rust-lang/rust#67329]
Working on CPUID based dispatch for Vector AES code for https://crates.io/crates/crypto_pimitives library.

Based on https://doc.rust-lang.org/reference/attributes/codegen.html#x86-or-x86_64 Rust doesn't support any AVX512 targets.

**Comment by workingjubilee** [comment]
The reference is outdated here, there is partial AVX512 support in core::arch and the compiler on nightly, as can be seen here: https://doc.rust-lang.org/core/arch/x86_64/index.html

As there is quite a lot to support it has not been finished (nor stabilized) however: https://github.com/rust-lang/stdarch/issues/310

**Comment by DevJPM** [comment]
I have looked into implementing this (for nightly at least) however it appears that support is blocked by the compiler not being willing to accept the VAES (and vaguely related VPCLMULQDQ) feature flags for enabling the LLVM intrinsics.

**Comment by workingjubilee** [comment]
In #78361, a large amount of support for AVX512 features was added to the compiler, including all the ones (afaict) that IceLake included, resolving this issue.
