### ISSUE TITLE
How to expose extern function like a proxy

### ISSUE THREAD

**Issue by hanabi1224** [rust-lang/rust#67320]
e.g. I have 
```rust
extern "C" {
    pub fn LZ4_versionNumber() -> c_int;
}
```
Then I want to expose the same function for FFI when I build dynamic lib with cargo
```rust
#[no_mangle]
pub extern "C" fn ffi_LZ4_versionNumber() -> c_int {
    return unsafe { LZ4_versionNumber() };
}
```
My question is that, is there a way to directly expose the function with the same name? Something like 
```rust
extern "C" {
    #[no_mangle]
    #[extern_c]
    pub fn LZ4_versionNumber() -> c_int;
}
```
So that LZ4_versionNumber will appear in dynamic symbol table and be callable from other launguages.  Thanks!

**Comment by jonas-schievink** [comment]
Hi! This issue tracker is mainly meant for bug reports and concrete, small feature requests. Questions like this are better asked in the user forum at https://users.rust-lang.org/ or on [one of the chat platforms](https://www.rust-lang.org/community) used by the Rust community.
