### ISSUE TITLE
Comments in libsyntax/ptr.rs contain outdated references to @T

### ISSUE THREAD

**Issue by alex** [rust-lang/rust#67341]
https://github.com/rust-lang/rust/blob/a605441e049f0b6d5f7715b94b8ac4662fd7fcf6/src/libsyntax/ptr.rs#L1-L27

The comments are quite old and probably need some small updates to reflect `@T` having been removed from the language.

This issue has been assigned to @matthew-healy via [this comment](https://github.com/rust-lang/rust/issues/67341#issuecomment-566504172).

**Comment by matthew-healy** [comment]
I think I should be able to handle this. Hopefully some time in the next few days.

Am I right in thinking I just do this? @rustbot claim

I've found the documentation style RFC, and some info about what `@T` was, which should hopefully be enough info to improve this comment. 👍 If there's anything else specific I should consider plz let me know.

**Comment by Mark-Simulacrum** [comment]
Yes, you can definitely just do this and any questions which come up can be addressed on the (eventual) PR most likely. I imagine it's mostly a matter of just deleting `@T` related documentation; if you want to try and replace it with something more up to date that would be even better.
