### ISSUE TITLE
Don't run CI for draft PRs

### ISSUE THREAD

**Issue by mark-i-m** [rust-lang/rust#67357]
I would like to propose that CI should not be run on PRs that are marked as "Drafts" using the Github ["Drafts" feature](https://github.blog/2019-02-14-introducing-draft-pull-requests/).

Run CI wastes resources and produces lots of noisy messages from rust-highfive bot about failing CI.

**Comment by joshtriplett** [comment]
It should be possible to explicitly ask for them to run through CI, but it makes sense to not run CI on drafts by default.

**Comment by mark-i-m** [comment]
It might be a bit heavy-weight, but I think we can already use `bors try` for that.

**Comment by mark-i-m** [comment]
It looks like Travis, Azure, and Github don't have support for such a feature yet...

**Comment by steveklabnik** [comment]
Triage: this looks to be possible for Github Actions? https://github.community/t5/GitHub-Actions/Don-t-run-actions-on-draft-pull-requests/m-p/55316#M9508

**Comment by pietroalbini** [comment]
We discussed this in [the infrastructure team meeting](https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/2020-09-09.20meeting) and decided not to go forward with this approach. You can see the context on the decision by reading the contents of the meeting.
