### ISSUE TITLE
rustdoc does not render some `where` clauses on functions

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/rust#67366]
For example, the docs for [`pointer::offset`](https://doc.rust-lang.org/std/primitive.pointer.html?search=#method.offset) do not include the `where T: Sized` bound, which is very significant here.

(I could not find any existing issue about this, but there may well be one already since this seems pretty easy to spot)

**Comment by ollie27** [comment]
Duplicate of #24183
