### ISSUE TITLE
[Library] Box::new reuses the same heap address for multi allocations

### ISSUE THREAD

**Issue by kelthuzadx** [rust-lang/rust#67365]
As the documentation explains, **Box::new will allocate memory on the heap and then place the argument into it**. But it would reuse the same heap address if allocation result is not stored someplace. We can reproduce this scenario by a simple snippet:
```rust
fn test() {
    let addr = Box::new(1024);
    println!("{:p}", addr);
}
fn main(){
    test();
    test();
}
// Output
0x7fd2fa402b70
0x7fd2fa402b70
```
No matter how many times I call test(), the program prints an identical address since I don't store the result beyond the test function, the allocated memory is immediately freed and the same heap address will be reused for further allocations. So why does Rust reuse the same heap address, even if the code is in an unsafe block? Is this normal behavior? Should we comment this behavior on Box::new's rustdoc?

**Comment by Mark-Simulacrum** [comment]
This is dependent (but quite common to see) on the memory allocator in use, and is not unexpected behavior. If the memory is deallocated (like Box's destructor does at the end of the `test` function), then the next allocation of the same size and (in some cases) on the same thread is quite likely to use the same memory slot in many allocators.

If you're interested in discussing this further, please direct queries to users.rust-lang.org which is better suited for questions like this. Thanks!
