### ISSUE TITLE
src/librustc/ty/subst.rs:557: type parameter `T/#0` (T/0) out of range when substituting (root type=Some(T)) substs=[]

### ISSUE THREAD

**Issue by MetallicSquid** [rust-lang/rust#67372]
I'm new to this so sorry if I filed this bug incorrectly, but cargo kindly told me to file a report, so I'll do just that.

So I stumbled upon this bug while trying to determine whether an error had occurred by use of a match statement (if you've got any suggestions on how to do that based on the code below, that would be greatly appreciated). Once I ran the code, the following occurred:

```
error: internal compiler error: src/librustc/ty/subst.rs:557: type parameter `T/#0` (T/0) out of range when substituting (root type=Some(T)) substs=[]

thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:778:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.39.0 (4560ea788 2019-11-04) running on x86_64-unknown-linux-gnu

note: compiler flags: -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden
```
as well as:

```
error[E0308]: mismatched types
  --> src/main.rs:79:9
   |
78 |     match metadata.created().unwrap() {
   |           --------------------------- this match expression has type `std::time::SystemTime`
79 |         Ok() => created_meta = "All's good",
   |         ^^^^ expected struct `std::time::SystemTime`, found enum `std::result::Result`
   |
   = note: expected type `std::time::SystemTime`
              found type `std::result::Result<_, _>`

```
but I'm fairly sure this is unrelated to the compiler bug.

Here's the [code](https://github.com/MetallicSquid/rust-cmd-line-tools/blob/master/mega/src/main.rs), specifically between lines 73 and 82.

**Meta:**
Version:
`note: rustc 1.39.0 (4560ea788 2019-11-04) running on x86_64-unknown-linux-gnu`
System:
Regolith Linux (Ubuntu 19.04 & i3) 

Note:
The `metadata` part of the above code is using `std::fs::metadata`.

I don't think there's really anything else for me to say, but feel free to ask questions (whether I can answer them is another matter entirely).

**Comment by jonas-schievink** [comment]
Thanks for the report! Does this also happen on nightly?

**Comment by MetallicSquid** [comment]
**Unrelated:**

I know no one cares, but I solved my bug. :+1:

**Comment by MetallicSquid** [comment]
Sorry, but I don't know how to test whether it happens on nightly. I'm not running nightly.

**Comment by MetallicSquid** [comment]
Also, I just realised that my code link isn't correct. Here's what the code was (between line 73 and 81):

```
 // Creation time doesn't work on all systems, so this needs to be fixed.
    let mut created_meta = "";

    println!("{:?}", metadata.created().unwrap());

    match metadata.created().unwrap() {
        Ok() => created_meta = "All's good",
        Err() => created_meta = "ERROR",
    };
```

Everything other than the code between line 73 and 81 is the same though.

**Comment by MetallicSquid** [comment]
Sorry if that caused any inconvenience.

**Comment by jonas-schievink** [comment]
Fixed on nightly, closing.
