### ISSUE TITLE
improve diagnostics for non-send Futures that might be solved by introducing temporary variables

### ISSUE THREAD

**Issue by yoshuawuyts** [rust-lang/rust#67376]
In https://github.com/http-rs/tide/issues/370 we had a user report that they encountered a `Send` error similar to the ones discussed in https://github.com/rust-lang/rust/issues/64130. Thanks to the diagnostics introduced https://github.com/rust-lang/rust/pull/65345 on nightly we were able to correctly diagnose the root cause of the error.

But for many users this might still not be enough to figure out how to solve this, and we could improve by providing a hint.

## Current Diagnostics

![2019-12-17-175740_1920x1080](https://user-images.githubusercontent.com/2467194/71032157-121ad680-2115-11ea-9546-416c45f50f41.png)

```txt
   Compiling tide-demo v0.1.0 (/home/anon/Code/importcjj/tide-demo)
error: future cannot be sent between threads safely
  --> src/main.rs:47:27
   |
47 |         app.at("/submit").post(|req: tide::Request<State>| {
   |                           ^^^^ future is not `Send`
   |
   = help: the trait `std::marker::Sync` is not implemented for `(dyn futures_io::if_std::AsyncBufRead + std::marker::Send + 'static)`
note: future is not `Send` as this value is used across an await
  --> src/main.rs:49:29
   |
49 |                 let conn = &req.state().pool.get().await;
   |                             ---^^^^^^^^^^^^^^^^^^^^^^^^^- `req` is later dropped here
   |                             |
   |                             await occurs here, with `req` maybe used later
   |                             has type `&tide::request::Request<State>`
```

## Suggested Diagnostics

@estebank suggested we could add a suggestion here:

```txt
help: consider assigning `&req.state().pool` to a temporary variable
```

## Repro
- https://github.com/importcjj/tide-demo/blob/master/src/main.rs

## Refs
- https://github.com/rust-lang/rust/issues/64130
- https://github.com/http-rs/tide/issues/370

**Comment by tmandry** [comment]
Visiting from triage.. assigning @csmoe for implementation and @nikomatsakis to leave some tips.

**Comment by csmoe** [comment]
reproduced with exsited ui testcase:
```rust
use std::any::Any;
use std::future::Future;

struct Client(Box<dyn Any + Send>);

impl Client {
    fn status(&self) -> u16 {
        200
    }
}

async fn get() { }

pub fn foo() -> impl Future + Send {
    //~^ ERROR future cannot be sent between threads safely
    let client = Client(Box::new(true));
    async move {
        match client.status() {
            200 => {
                let _x = get().await;
            },
            _ => (),
        }
    }
}

fn main() {}
```
```txt
  --> $DIR/issue-64130-4-async-move.rs:21:26
   |
LL |         match client.status() {
   |               ------ has type `&Client`
LL |             200 => {
LL |                 let _x = get().await;
   |                          ^^^^^^^^^^^ await occurs here, with `client` maybe used later
...
LL |     }
   |     - `client` is later dropped here
   = note: the return type of a function must have a statically known size
```
rewrite the match expr as:
```rust
let status = client.status();
match status { ... }
```
will fix this.
The problem is that `client` does **NOT** has type `&Client`, but `.status()` creates a temporary borrow `&Client`.
