### ISSUE TITLE
`Command::new(&path).output()` returns incorrect data when child program segfaults

### ISSUE THREAD

**Issue by jaseemabid** [rust-lang/rust#67391]
When a child program segfaults, I'd expect `.output()` to return an `Err(..)` instead of `Ok(..)`.

Minimal reproduction example: 

**segfault.c**:
```c
#include <stdio.h>

int main() {
    int *p = NULL;
    *p = 1;
}
```
**run.rs**:
```rust
use std::os::unix::process::ExitStatusExt;
use std::process::Command;

fn main() -> Result<(), std::io::Error> {
    let exe = Command::new("./a.out").output()?;

    println!(
        "status: `{}`, code: `{:?}`, success: `{}`, signal: {:?}",
        exe.status,
        exe.status.code(),
        exe.status.success(),
        exe.status.signal()
    );

    Ok(())
}
```
I'd expect command's behaviour to match that of executing the program directly.

```
$ clang segfault.c
$ ./a.out
[1]    89887 segmentation fault (core dumped)  ./a.out
$ echo $?
139

$ rustc run.rs
$ ./run
status: `signal: 11`, code: `None`, success: `false`, signal: Some(11)
```

This program must exit with a non zero code and report an error instead of silently returning `Ok()` with empty stderr and stdout. `Command` seems to handle other kind of errors fine, for example non existent binaries correctly report an error:

```
./run
Error: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```

**Comment by jonas-schievink** [comment]
`[1]    89887 segmentation fault (core dumped)  ./a.out` is not printed by the program, it is printed by the shell. Methods on `Command` will only return `Err` if they fail to *spawn* the process, but this is documented. Otherwise there would be no way to obtain the output when the command crashes.

**Comment by jaseemabid** [comment]
@jonas-schievink It might be documented, but the behaviour is a bit counter intuitive. The `Result<>` in the return type hints that all errors would be propagated up, but seems like that's not the case.
