### ISSUE TITLE
const fn for SocketAddr::new, SocketAddrV4::new and SocketAddrV6::new

### ISSUE THREAD

**Issue by gliderkite** [rust-lang/rust#67390]
This is a tracking issue for adding `const fn` to `SocketAddr::new`, `SocketAddrV4::new` and `SocketAddrV6::new` to be able to initialize the socket address at compile time, for example:

```rust
use std::net::{IpAddr, Ipv4Addr, Ipv6Addr, SocketAddrV4, SocketAddrV6, SocketAddr};

const localhost_v4: Ipv4Addr = Ipv4Addr::new(127, 0, 0, 1);
const socket_v4: SocketAddrV4 = SocketAddrV4::new(localhost_v4, 80);
const socket_add_v4: SocketAddr = SocketAddr::new(IpAddr::V4(localhost_v4), 80);

const localhost_v6: Ipv6Addr = Ipv6Addr::new(0x2001, 0xdb8, 0, 0, 0, 0, 0, 1);
const socket_v6: SocketAddrV6 = SocketAddrV6::new(localhost_v6, 80, 0, 0);
const socket_add_v6: SocketAddr = SocketAddr::new(IpAddr::V6(localhost_v6), 80);
```

Open PR: https://github.com/rust-lang/rust/pull/67315

**Comment by DCjanus** [comment]
ping

**Comment by gliderkite** [comment]
@DCjanus This is probably still blocked on some open issues, such as https://github.com/rust-lang/rust/issues/67792.

**Comment by l3utterfly** [comment]
Ping. This feature would really be helpful.

**Comment by faern** [comment]
It would! But it's currently blocked on #78802

**Comment by Mark-Simulacrum** [comment]
I believe these are all done as of ~1.69. In general there's not much value in a tracking issue vs. filing a PR if there's no blockers to stabilize as well, so closing.
