### ISSUE TITLE
missing libstdc++-6.dll in beta-x86_64-pc-windows-gnu (1.41.0-beta.1)

### ISSUE THREAD

**Issue by cuviper** [rust-lang/rust#67408]
I saw this failure in rayon CI: https://ci.appveyor.com/project/cuviper/rayon/builds/29634901/job/y7h1kc7w9wsusl8r
```
info: syncing channel updates for 'beta-x86_64-pc-windows-gnu'
info: latest update on 2019-12-18, rust version 1.41.0-beta.1 (eb3f7c2d3 2019-12-17)
[...]
  beta installed - (error reading rustc version)


Rust is installed now. Great!

To get started you need Cargo's bin directory (%USERPROFILE%.cargo\bin) in your
PATH
environment variable. Future applications will automatically have the
correct environment, but you may need to restart your current shell.
set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
rustc -Vv
Command exited with code -1073741515
```

I'm on Linux, but I tried this build under Wine:

```
005b:err:module:import_dll Library libstdc++-6.dll (which is needed by L"Z:\\home\\jistone\\.rustup\\toolchains\\beta-x86_64-pc-windows-gnu\\bin\\rustc_driver-2602f879d4c5def3.dll") not found
005b:err:module:import_dll Library rustc_driver-2602f879d4c5def3.dll (which is needed by L"Z:\\home\\jistone\\.rustup\\toolchains\\beta-x86_64-pc-windows-gnu\\bin\\rustc.exe") not found
005b:err:module:LdrInitializeThunk Importing dlls for L"Z:\\home\\jistone\\.rustup\\toolchains\\beta-x86_64-pc-windows-gnu\\bin\\rustc.exe" failed, status c0000135
```

It seems @mati865's intention in #65911 was that this should be statically linked, but that was clobbered by #67077 in `src/bootstrap/compile.rs` at least.

The same error occurs on `1.41.0-nightly (3ed3b8bb7 2019-12-17)` (via Wine again for me).

**Comment by mati865** [comment]
Probably the culprit is here: https://github.com/rust-lang/rust/pull/67077/files#r359557571

**Comment by mati865** [comment]
As immediate workaround I suggest adding `libstdc++-6.dll` to the PATH, it should be installed on most of the Windows CI.

**Comment by tan-wei** [comment]
@mati865 Thanks! It works.

**Comment by pnkfelix** [comment]
triage: P-high, has PR, removing nomination.

**Comment by binarycrusader** [comment]
> As immediate workaround I suggest adding `libstdc++-6.dll` to the PATH, it should be installed on most of the Windows CI.

Sadly, that didn't work for me:

"The procedure entry point _ZNSt13__future_base12_Result_baseC2Ev could not be located in the dynamic link library C:\Users\xxxxx\.rustup\toolchains\nightly-x86_64-pc-windows-gnu\bin\rustc_driver-3aaebb9b017b7498.dll."

Just posting as an FYI, not expecting a solution

**Comment by mati865** [comment]
FWIW it was fixed in nightly but not yet in beta.

**Comment by John-Nagle** [comment]
Did this fix make it into stable? I'm getting that error in rustc 1.59.0 (9d1b2106e 2022-02-23).

Cross-compiling from Linux: `cargo build --target x86_64-pc-windows-gnu --examples`

Trying to run  under Wine 7.0.

Wine error messages:

```
0124:err:module:import_dll Library libgcc_s_seh-1.dll (which is needed by L"Z:\\home\\john\\projects\\sl\\SL-test-viewer\\target\\x86_64-pc-windows-gnu\\debug\\examples\\libstdc++-6.dll") not found
0124:err:module:import_dll Library libstdc++-6.dll (which is needed by L"Z:\\home\\john\\projects\\sl\\SL-test-viewer\\target\\x86_64-pc-windows-gnu\\debug\\examples\\scenetest.exe") not found
0124:err:module:LdrInitializeThunk Importing dlls for L"Z:\\home\\john\\projects\\sl\\SL-test-viewer\\target\\x86_64-pc-windows-gnu\\debug\\examples\\scenetest.exe" failed, status c0000135
```

Please, statically link this stuff. 

(Trying to find the correct version of `libstdc++-6.dll`. MinGW has four different versions. Any suggestions?)

**Comment by mati865** [comment]
> Please, statically link this stuff.

It was linked statically in the past, must be regression.
Does it work on other versions for you?

**Comment by mati865** [comment]
Upon closer inspection you are not having problem running rustc but with artifacts built with rustc.
In this case this entirely different issue and you need to find which crate in your dependency tree has linked dynamic libstdc++.

**Comment by John-Nagle** [comment]
Yes. I was using a deprecated package that pulled in some DLLs. Once I got rid of that package, the problem disappeared.

**Comment by hydra** [comment]
> Yes. I was using a deprecated package that pulled in some DLLs. Once I got rid of that package, the problem disappeared.

@John-Nagle two questions: 1) how did you find the offending package, 2) which one was it?  I'm getting the same thing on `rustc 1.61.0-nightly (6a7055661 2022-02-27)`

**Comment by hydra** [comment]
I couldn't find a specific dependency that caused the issue, but upgrading rust from `rustc 1.61.0-nightly (6a7055661 2022-02-27)` to `rustc 1.61.0-nightly (1d9c262ee 2022-03-26)` fixed it for me.
