### ISSUE TITLE
Trait for is_empty?

### ISSUE THREAD

**Issue by mocsy** [rust-lang/rust#67409]
Lots of stuff in std provde pub fn is_empty, shouldn't there be a trait for it?

https://doc.rust-lang.org/nightly/std/collections/struct.HashMap.html#method.is_empty

**Comment by jonas-schievink** [comment]
What would be the use case of abstracting over things that may be empty?

**Comment by mocsy** [comment]
I implement is_empty for my types, then skip their serialization entirely if they are empty.
I could write a derive macro for it as long as the type is composed of types which also implement is_empty.

**Comment by Mark-Simulacrum** [comment]
I'm going to close this as I don't believe we'd be interested in such an abstraction. It's not too hard to implement yourself, and it's unclear what emptiness exactly means. If it's "is the iterator of this type empty" then that is better asked via `.next().is_none()` or so (on the first call) -- and indeed there's also https://github.com/rust-lang/rust/issues/35428.

Generally speaking "emptiness" is not something that is easy to abstract over as an individual bound (i.e., `T: IsEmpty` is not useful as far as I can tell).

Note also that derives have no direct relationship to traits -- you can write a derive macro which expands to calling the is_empty method on many types already, and plausibly even provide that method via an extension trait for some types that don't implement it today.
