### ISSUE TITLE
Cannot sort f64

### ISSUE THREAD

**Issue by Apromixately** [rust-lang/rust#67417]
The following program does not compile:
```
fn main() {
    let fs = vec![11.0, 7.0, 5.0, 3.14, 3.0, 2.7182, 2.0, 1.4142, 9.8, 100.0, 10.0];
    fs.sort();
}
```
the compiler error is:
```
error[E0277]: the trait bound `{float}: std::cmp::Ord` is not satisfied
 --> src/main.rs:3:8
  |
3 |     fs.sort();
  |        ^^^^ the trait `std::cmp::Ord` is not implemented for `{float}`
```

Now, without getting into how this could be implemented - which I don't know anything about - I just wanted to say that this is really bad usability. Plus, the statement that _this programming language cannot sort numbers_ is either insane or funny.

Maybe a possible fix would be a try_sort function which is content with a std::cmp::PartialEq and returns an Error if two elements are not orderable.

**Comment by sinkuu** [comment]
[`slice::sort_by` documentaiton](https://doc.rust-lang.org/std/primitive.slice.html#method.sort_by) has an example to sort `f64`.

**Comment by hellow554** [comment]
Hi @Apromixately 

it seems that you are a beginner of the Rust language. I want to outline, that this issue tracker is primarily used for bugs in the compiler or standard library, not for questions. There is the users forum at https://users.rust-lang.org

But let me give you a few links, why Rust behaves the way you observe:

https://users.rust-lang.org/t/how-to-sort-a-vec-of-floats/2838

https://stackoverflow.com/questions/26489701/why-does-rust-not-implement-total-ordering-via-the-ord-trait-for-f64-and-f32


There is also a crate that gives you some guarantees or orders it in a specific way: https://crates.io/crates/ordered-float

I hope I could help you.
Please close this issue and ask on the user forum (see above) for further questions. The people there are very welcoming and are always there for newcomers in Rust.

**Comment by jonas-schievink** [comment]
Yes, this is covered by sort_by, so closing

**Comment by Apromixately** [comment]
@jonas-schievink Yes, the `sort_by` version kind of works but it does not really compose well.
For example, if I have a vector of Person structs that I want to sort by body-mass-index. The imho natural approach would be
```
people.sort_by_key(|person| person.height / person.weight.pow(2.0));
```
with sort_by this becomes
```
people.sort_by(|a, b| (a.height / a.weigh.pow(2.0)).partial_cmp(b.height / b.weight.pow(2.0))).unwrap()
```
or something like this.
Now you could argue that in this particular case I should just give my key function a name, of course. But if `sort_by_key` is considered useful I think this is a general issue.

**Comment by Apromixately** [comment]
@hellow554 Well, I consider this a bug or at least an important feature but if there is a better issue tracker for the language standard instead of compiler/stdlib I would be happy to post it there instead.

**Comment by Apromixately** [comment]
Oh, and there is https://doc.rust-lang.org/std/primitive.slice.html#method.sort_by_cached_key which does not really work anymore if the output is a float.

**Comment by hellow554** [comment]
> Well, I consider this a bug 

As already said, this is **very** intentional, because of various reasons how floats are defined and behave. That's why there is a difference between `PartialOrd` and `Ord`. Rust gives many more guarantees than any other language (I can think of) and this implies floating numbers for example. You can't compare `NaN` with each other (as well as `±Inf`). You have a workaround if you like, for further discussions please use the rust discourse forum :)

**Comment by Apromixately** [comment]
In case somebody is interested in that discussion: https://users.rust-lang.org/t/cannot-sort-floats/35897
