### ISSUE TITLE
Forbid certain actions to be performed in certain functions

### ISSUE THREAD

**Issue by Mahdrentys** [rust-lang/rust#67411]
Sometimes we don't want certain actions to be performed when we call a specific function. For example, if we write real time stuff like an audio app we don't want allocations to be performed.

So we could have an attribute named `must_not_perform` :

```rust
#[must_not_perform(allocation)]
fn audio_callback(...) {...}
```

And an attribute named `performs` which indicates that the function performs this action. So we would add `#[performs(allocation)]` to `Box::new`, `String::new` and all functions that do allocations in the standard library, and the compiler would walk down all the call stack of the function having a `must_not_perform` attribute to check that there is no call to a function with the corresponding `performs` attribute. And if there is, that would cause a compile error.

It would also be useful in async apps where we could forbid blocking calls, with `#[performs(blocking)]` added to the calls to filesystem and stuff like that in the standard library. The `#[must_not_perform(blocking)]` attribute could even be implicit in async functions.

It's in the spirit of Rust to catch as much as possible mistakes at compile time, and this kind of mistake can't be detected with unit tests.

**Comment by jonas-schievink** [comment]
Something like this needs to go through an RFC, so closing in favor of that
