### ISSUE TITLE
Remove rustc-dev component from default profile

### ISSUE THREAD

**Issue by jethrogb** [rust-lang/rust#67425]
The `rustc-dev` component is larger than all other components of the `default` profile combined, yet most users probably don't care about this. I think it should be removed.

Perhaps another profile `default-poweruser` can be made that does include it.

**Comment by kinnison** [comment]
I'd argue that the `complete` profile (which is basically rust devs-only anyway) might be an acceptable place for this, without needing to add a new profile name.  People who want `default` plus `rustc-dev` can just do `rustup toolchain install nightly --profile default --component rustc-dev`

**Comment by Mark-Simulacrum** [comment]
It was the intent when merging the PR that split the rustc-dev profile out that we would eventually remove it from the default set. I believe this is already true on beta (and perhaps stable as of later today?).

I would accept a PR at this point that removes rustc-dev component from the default set on nightly as well.
