### ISSUE TITLE
Cargo.lock created by cargo 1.41.0-beta incompatible with 1.37.0

### ISSUE THREAD

**Issue by tspiteri** [rust-lang/rust#67423]
If I delete the lock file and generate it with beta 1.41.0, then version 1.37.0 will not be able to parse the lock file. Version 1.38.0 will still be able to parse the lock file.
```
[tmp]$ cargo +beta new --lib try
     Created library `try` package
[tmp]$ cd try
[try]$ echo 'bitflags = "1"' >> Cargo.toml
[try]$ cargo +beta check
    Updating crates.io index
   Compiling bitflags v1.2.1
    Checking try v0.1.0 (/tmp/try)
    Finished dev [unoptimized + debuginfo] target(s) in 1.17s
[try]$ cargo +1.37.0 check
error: failed to parse lock file at: /tmp/try/Cargo.lock

Caused by:
  invalid serialized PackageId for key `package.dependencies`
[try]$ cargo +beta -V
cargo 1.41.0-beta (626f0f40e 2019-12-03)
```

**Comment by tspiteri** [comment]
Oh, it seems this is expected: https://github.com/rust-lang/cargo/commit/366ae3f7bae7e84f6d0d2f9e31f19b0e19c84f4b

Will this be included in the 1.41 release notes compatibility section?

**Comment by Mark-Simulacrum** [comment]
cc @XAMPPRocky

**Comment by XAMPPRocky** [comment]
@tspiteri Yes, I will include this in the release notes.
