### ISSUE TITLE
Line numbers are truncated in diagnostics.

### ISSUE THREAD

**Issue by kevincox** [rust-lang/rust#67431]
Some, but not all, diagnostics are truncating the line number to 2 digits.

Can we remove this truncation? It makes the most visible location for line numbers basically useless.

<pre><font color="#FF6B6B"><b>error[E0560]</b></font><b>: struct `game::Table` has no field named `artifacts`</b>
 <font color="#729FCF"><b>--&gt; </b></font>src/game.rs:1452:4
  <font color="#729FCF"><b>|</b></font>
<font color="#729FCF"><b>14| </b></font>            artifacts: vec![None; state.players],
  <font color="#729FCF"><b>| </b></font>            <font color="#FF6B6B"><b>^^^^^^^^^</b></font> <font color="#FF6B6B"><b>`game::Table` does not have this field</b></font>
  <font color="#729FCF"><b>|</b></font>
  <font color="#729FCF"><b>= </b></font><b>note</b>: available fields are: `shared_a_data`, `shared_b_data`, `shared_c_data`, `shared_d_data`, `shared_e_data` ... and 3 others
</pre>

Note that the correct line number is 1452, however next to the code it displays 14.

**Comment by kevincox** [comment]
Note that some diagnostics output the line number correctly:

<pre><font color="#FF6B6B"><b>error[E0063]</b></font><b>: missing fields `happiness`, `sanity` in initializer of `game::Game`</b>
    <font color="#729FCF"><b>--&gt; </b></font>src/game.rs:1492:18
     <font color="#729FCF"><b>|</b></font>
<font color="#729FCF"><b>1492</b></font> <font color="#729FCF"><b>| </b></font>        let mut game = Game {
     <font color="#729FCF"><b>| </b></font>                       <font color="#FF6B6B"><b>^^^^</b></font> <font color="#FF6B6B"><b>missing `happiness`, `sanity`</b></font>

<font color="#FF6B6B"><b>error</b></font><b>: aborting due to 7 previous errors</b>
</pre>

**Comment by Mark-Simulacrum** [comment]
cc @estebank

Do you happen to have a more minimal example?

**Comment by kevincox** [comment]
I tried reproducing on the playground with no luck. I'll see if I can get a minimal example: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=47795d540db43935a85384ea7dc91249.

`cargo build` is enough to reproduce on my project.

**Comment by estebank** [comment]
What version are you on?

**Comment by kevincox** [comment]
I'm AFK but have been updating between nightlies for a couple of months with be same issue. I'll update with the exact version when I get the chance.

**Comment by wesleywiser** [comment]
I believe this was fixed the day after that nightly (see https://github.com/rust-lang/rust/issues/65001).

**Comment by estebank** [comment]
@kevincox could you `rustup update` to a newer nightly (or stable) to verify whether this is indeed the same issue which has been already fixed?

**Comment by kevincox** [comment]
Ah, PEBKAC. I didn't realize that I had pinned an exact version of nightly for that directory. I've updated and the issue doesn't appear to be occurring anymore.
