### ISSUE TITLE
RELEASES.md on stable branch still at 1.39.0

### ISSUE THREAD

**Issue by sdroege** [rust-lang/rust#67447]
See https://github.com/rust-lang/rust/blob/stable/RELEASES.md

The same is also the case for the 1.40.0 tag but you probably don't want to re-tag for that.

**Comment by Mark-Simulacrum** [comment]
I don't currently anticipate that we'll be changing anything here. However, I would like to update the release process documentation with a reminder to include release notes when promoting beta to stable (potentially from master), so leaving this open and assigning to me.

**Comment by sdroege** [comment]
Ok, then maybe the "compatibility notes" link at the bottom of https://blog.rust-lang.org/2019/12/19/Rust-1.40.0.html should be updated to point to master at least :)

**Comment by Mark-Simulacrum** [comment]
Updated that link.

**Comment by Mark-Simulacrum** [comment]
Closing. I've added a note to our documentation in rust-lang/rust-forge@16d0f8428db4ed09d5b27071968de2b9342e1ecc.
