### ISSUE TITLE
No Warning after forgetting last Semicolon

### ISSUE THREAD

**Issue by youngtrashbag** [rust-lang/rust#67446]
### No Warning about forgetting last Semicolon
So I was writing a simple "hello world" file, and I noticed, that the code compiled without any warnings or errors, even though I had no semicolon on the last line. Now I don't know wether this is supposed to happen or not, but I think it might should be fixed.

### Here is the code:
```rust
fn main() {
    print!("hello, ");
    print!("world!")
}
```

### Then I did:
1. `rustc hello-world.rs`
2. `./hello-world.exe`
    - it might be because I'm using windows

### My Conclusion
So in my Opinion this should be fixed.

**Comment by memoryruins** [comment]
`fn main` in the above expects an unit type to be returned, and printing returns an unit type, which makes the lack of semicolon fine. https://doc.rust-lang.org/std/primitive.unit.html

**Comment by Centril** [comment]
Closing as by-design with @memoryruins's rationale.

**Comment by qnighy** [comment]
Although it's totally valid, I'd expect some clippy lint for this kind of code.

**Comment by Centril** [comment]
Rust is an expression language, and so I think there's nothing wrong with the code above. I would personally be against a Clippy lint unless it's a pedantic one.
