### ISSUE TITLE
#[non_exhaustive] not working for Binary (application)

### ISSUE THREAD

**Issue by ksangabriel** [rust-lang/rust#67452]
I am trying out the new features in 1.40.0 but could not get the expected behavior for `#[non_exhaustive]`. I am expecting compilation errors but got none.

```
#[derive(Debug)]
#[non_exhaustive]
pub enum Countries { PHILIPPINES, MALAYSIA, SINGAPORE, INDONESIA, THAILAND, VIETNAM }

fn main() {
    let home = Countries::THAILAND;

    match home {
        Countries::PHILIPPINES | Countries::MALAYSIA | Countries::INDONESIA | Countries::SINGAPORE | Countries::THAILAND | Countries::VIETNAM => {
            println!("GROUP 1: {:?}", home)
        },
    }
}
```

![image](https://user-images.githubusercontent.com/754968/71262077-d2a0f400-2379-11ea-88e2-1b106ae410fa.png)

Build via CLI

![image](https://user-images.githubusercontent.com/754968/71262259-3e835c80-237a-11ea-9b9b-bcf5ecfa6098.png)

Version Information
![image](https://user-images.githubusercontent.com/754968/71262348-7094be80-237a-11ea-8687-f9d012bf749c.png)

**Comment by jonas-schievink** [comment]
`#[non_exhaustive]` has no effect inside the defining crate. See https://doc.rust-lang.org/reference/attributes/type_system.html#the-non_exhaustive-attribute
