### ISSUE TITLE
Importing 'arrayvec' into a module of a project breaks specific rust code from compiling

### ISSUE THREAD

**Issue by Veykril** [rust-lang/rust#67468]
A friend and I just discovered a weird behaviour in a project when just using arrayvec via a use statement. It compiles fine unless we explicitly use an item of `arrayvec` via a use statement. These items don't have to be used for this bug to occur, only the import matters in any single module in the project to prevent the compilation(this import can even be in a different module than the `>` check).

A short example program: [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=8f5911f2b7dd953964b17cc9a05b3faa)
```rust
// uncomment this unused import to break compilation
//use arrayvec; // 0.5.1

fn main() {
    let foo = "foo";
    let bar = &std::borrow::Cow::Owned(String::new());
    let _ = foo < bar;
}
```

This breaks on both current stable and current nightly with the message
```
error[E0277]: can't compare `str` with `std::borrow::Cow<'_, str>`
 --> src/main.rs:7:17
  |
7 |     let _ = foo < bar;
  |                 ^ no implementation for `str < std::borrow::Cow<'_, str>` and `str > std::borrow::Cow<'_, str>`
  |
  = help: the trait `std::cmp::PartialOrd<std::borrow::Cow<'_, str>>` is not implemented for `str`
  = note: required because of the requirements on the impl of `std::cmp::PartialOrd<&std::borrow::Cow<'_, str>>` for `&str`
```
I assume that something in arrayvec seems to prevent the compiler from being able to deref `&Cow` into a `&str` given that `Cow<'_. str>` does not implement `PartialOrd` for comparing with a `str` slice directly.

**Comment by cuviper** [comment]
It's probably the `PartialOrd<ArrayString<A>> for str` -- otherwise `std` only has `PartialOrd<str> for str`, so the compiler knows what type to force. (There are a bunch of `PartialEq<_> for str` though.)

**Comment by Veykril** [comment]
Ye it seems to be that implementation, then I assume this isn't unexpected behaviour after all? At least it makes sense as to why this fails then.

**Comment by wildbook** [comment]
Would that mean that adding a `use` statement to a library should be treated as a possibly breaking change? That doesn't sound too good.

**Comment by Mark-Simulacrum** [comment]
This is expected behavior, in the sense that inference breakage is allowed, but the arravec crate likely wants to not have that impl (instead only having the unambiguous form which does not overlap with std's types).

Closing.
