### ISSUE TITLE
Potential lifetime bug

### ISSUE THREAD

**Issue by crlf0710** [rust-lang/rust#67473]
```
#![allow(unused_variables, dead_code)]

struct A<X>(X);

trait Foo{}

fn foo_a<'x, X: Foo>(_: &'x A<X>, x: X) -> Box<dyn Foo + 'x> {
    Box::new(x) as _
}

struct B<X>(fn(X));

fn foo_b<'x, X: Foo>(_: &'x B<X>, x: X) -> Box<dyn Foo + 'x> {
    Box::new(x) as _
}
```
Currently this code compiles, but i think the `foo_b` function should not, because B is actually using X in a contravariant way, and rustc should not establish that `X: 'x` from the presence of `&'x B<X>`

**Comment by Centril** [comment]
cc @matthewjasper @nikomatsakis

**Comment by csmoe** [comment]
> because B is actually using X in a contravariant way

It's invariant(=`covariant ^ contravariant`) if I'm right, not contravariant.

**Comment by crlf0710** [comment]
@csmoe corrected me that, lifetimes are always covariant, so i guess this is working intended. Closing for now.

**Comment by nikomatsakis** [comment]
@crlf0710 

> Currently this code compiles, but i think the foo_b function should not, because B is actually using X in a contravariant way, and rustc should not establish that X: 'x from the presence of &'x B<X>

This is expected behavior, for better or worse, ever since [RFC 1214](https://rust-lang.github.io/rfcs/1214-projections-lifetimes-and-wf.html)
