### ISSUE TITLE
ICE "break to unknown label" when referring to label in closure

### ISSUE THREAD

**Issue by digama0** [rust-lang/rust#67475]
```rust
fn main() {
  'a: loop {
    (|| loop { break 'a })()
  }
}
```
reports:

    error: internal compiler error: src/librustc/middle/liveness.rs:1109: break to unknown label
     --> src/main.rs:3:16
      |
    3 |     (|| loop { break 'a })()
      |                ^^^^^^^^

    thread 'rustc' panicked at 'Box<Any>', src/librustc_errors/lib.rs:778:9

This is probably a matter for rfcs, but I would like the above code to work. It seems like it should be possible, since the closure's lifetime is less than `'a`, so the jump can just reset the stack pointer to the stack frame of the outer function. Something like this is necessary for being able to replace embedded `return`s when transforming `for x in xs { ...return... }` with `xs.into_iter().for_each(|x| ...return 'outer_scope...)`.

**Comment by Centril** [comment]
Already fixed on beta & nightly.
