### ISSUE TITLE
Rustup installer flagged for malware

### ISSUE THREAD

**Issue by cloew** [rust-lang/rust#67472]
I tried to install [rustup](https://www.rust-lang.org/tools/install) and it was flagged by Windows Defender. I tried installing anyway and Avast stopped the installation because it tried to install some malware (APEX somethin, I forget the name).

**Comment by memoryruins** [comment]
> (APEX somethin, I forget the name)

Can you post the report by avast and/or defender?

**Comment by cloew** [comment]
The Threat it detected was IDP.ARES.Generic

Trying to see if I can find more information.

**Comment by jonas-schievink** [comment]
Duplicate of https://github.com/rust-lang/rust/issues/56815 and https://github.com/rust-lang/rustup/issues/1568

**Comment by retep998** [comment]
Smartscreen is not the same as Windows Defender, so technically not a duplicate. But this also isn't an actionable issue on Rust's side.
