### ISSUE TITLE
Remove use of `issue = "0"` in submodules (stdarch, cargo, and rustfmt)

### ISSUE THREAD

**Issue by rossmacarthur** [rust-lang/rust#67496]
With #41260 resolved, `issue = "0"` in unstable attributes is disallowed in the compiler because `issue = "none"` should be used instead. However, some submodules haven't been updated to use this yet.

- [x] stdarch (submodule not updated yet)
- [x] cargo (submodule updated in https://github.com/rust-lang/rust/pull/67661)
- [x] rustfmt (submodule not updated yet)

Once this is done the code in `src/libsyntax/attr.rs` that allows `issue = "0"` can be updated.

See https://github.com/rust-lang/rust/pull/67480#issuecomment-568175534

**Comment by xfix** [comment]
All those projects merged the change.

**Comment by JohnTitor** [comment]
I think submodules don't actually block the work, we can move on.
