### ISSUE TITLE
How to use custom-build rustc to build WebAssembly?

### ISSUE THREAD

**Issue by ldm0** [rust-lang/rust#67517]
I tried to use compiled rustc to compile webassembly but failed. I add custom build rustc to toolchain and tried to add `wasm32-unknown-unknown` target but get error message below:
```
rustup target add --toolchain stage2 wasm32-unknown-unknown
error: toolchain 'stage2' does not support components
error: caused by: invalid toolchain name: 'stage2'
```
It seems that custom toolchain don't support components adding. And I can't find any related issue and document, even rustc-guide doesn't mention it. Could someone give me a hint?

**Comment by jonas-schievink** [comment]
Hi! This issue tracker is mainly meant for bug reports and concrete, small feature requests. Questions like this are better asked in the user forum at https://users.rust-lang.org/ or on [one of the chat platforms](https://www.rust-lang.org/community) used by the Rust community.

**Comment by jonas-schievink** [comment]
You can also try asking on internals.rust-lang.org
