### ISSUE TITLE
Implement type- and const-generic associated types

### ISSUE THREAD

**Issue by matthewjasper** [rust-lang/rust#67513]
The compiler errors for the following code:

```rust
#![feature(generic_associated_types)]

trait X {
    type Y<T>;
}
```

This is due to the compiler having no way to represent the implicit `for<T: Sized> Y<T>: Sized` bound on the trait. Some things that would need to be fixed before this can happen are:

- The handling of bound and placeholder types and constants in the compiler needs to be reviewed.
- There needs to be a way to represent traits bounds on bound types. I think the bound above is supposed to become `for<T> if T: Sized { Y<T>: Sized }`.
- Maybe Chalk needs to progress further? Without Chalk we can at least get to the point of trait errors due to lack of (lazy) normalization.

cc @rust-lang/wg-traits

**Comment by tiannian** [comment]
Type arguments in GAT seems not yet implemented. Is this feature being implemented?

**Comment by matthewjasper** [comment]
So, #72788 ended up allowing this because of changes to how bounds are handled. Any issues with this can be tracked in other issues.
