### ISSUE TITLE
Allow generic associate types in trait paths

### ISSUE THREAD

**Issue by matthewjasper** [rust-lang/rust#67510]
The following code should be accepted:

```rust
#![feature(generic_associated_types)]

trait X {
    type Y<'a>;
}

fn f(x: Box<dyn X<Y<'a>=&'a ()>>) {}
// or perhaps:
// fn f(x: Box<dyn for<'a> X<Y<'a>=&'a ()>>) {}

fn g<T: X<Y<'a>=&'a ()>>() {}
```

**Comment by Areredify** [comment]
I'll take at least the ast part of it for now

**Comment by Areredify** [comment]
Am I correct in that we don't accept any type bounds on the left hand side and suggest moving them into a `where` clause?

**Comment by matthewjasper** [comment]
Do you mean is `X<Y<T: SomeTrait>=()>` accepted? I would guess not because the bounds on `T` are already determined by the trait.

**Comment by Areredify** [comment]
We allow repeating bounds in impl blocks though, i.e. this is permitted currently
```
#![feature(generic_associated_types)]
#![allow(incomplete_features)]

trait X<'b> {
    type Y<'a: 'b>;
}

struct _S {}

impl<'a> X<'a> for _S {
    type Y<'b: 'a> = ();
}
```

**Comment by SuperTails** [comment]
Is this still being handled? I am willing to look into it myself, I am currently stuck on needing this feature (and admittedly have a lot of time on my hands with recent events).

**Comment by Areredify** [comment]
@SuperTails  You are welcome to take it, Im busy with chalk work atm

**Comment by zserik** [comment]
https://github.com/rust-lang/rust/issues/44265#issuecomment-655759017

<details>

I found another case where this is needed: I have a trait definition which looks like this:
```rust
pub trait ViewFn<S> {
    type Output<'ast>: Sized;
    fn view<'ast>(&self, node: &'ast S) -> Self::Output<'ast>;
    // ...
}
```
If I want to have a trait bound on `ViewFn` with `Output` constrained to be a reference to a object which implements a specific type, I would require this, e.g. the following currently doesn't work:
```rust
/*[...]*/<T, O, F>/*[...]*/
where
    O: // omitted [...]
    F: ViewFn<T, for<'x> Output<'x> = &'x O>,
```

</details>

**Comment by vandenheuvel** [comment]
Is this a duplicate? I copied this from the RFC. [Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=ef0283dd9e3281802c69b059f97368c3).
```rust
trait StreamingIterator {
    type Item<'a>;
    fn next<'a>(&'a mut self) -> Option<Self::Item<'a>>;
}

fn foo<T: for<'a> StreamingIterator<Item<'a> = &'a [i32]>>(iter: T) { unimplemented!() }
```

**Comment by zserik** [comment]
@vandenheuvel I think that is the same issue, yes.

**Comment by petrochenkov** [comment]
Some thoughts:
- `Trait<A<'a>: Clone>` should be supported as well (https://github.com/rust-lang/rust/issues/52662).
- The syntax should be future compatible with *type* parameters in associated types:
    ```rust
    trait Trait {
        type A<T>;
    }

    Trait<A<T> = u8>
    ```
- What is inside the angle brackets really, arguments or parameters - `A<???>`?
    (Arguments use already defined names and parameters introduce names.)
    Does `Trait<A<u8> = u8>` or `Trait<A<[u8; 10]> = u8>` make sense, or `???` must be a single type parameter?

The `fn f(x: Box<dyn for<'a> X<Y<'a>=&'a ()>>) {}` example in the top comment implies that `???` is an argument after all (use, not definition).
I assume it's equivalent to an (unimplemented) type equality predicate in a `where` clause (`for<'a> X::Y<'a> == &'a`).
Then `???` can indeed be an arbitrary type (or lifetime) like `u8` or `[u8; 10]`.

From that we see that the associated type constraint syntax is really ambiguous with generic type parameters, but also get a clue on how to approach it during parsing.
When parsing a generic argument (inside `Trait<...>`) we just parse a type and then look at the next token:
- If the next token is not `=`, then it's a type argument.
- If the next token is `=` (`Trait<TYPE = ...>`), then
    - if the parsed `TYPE` is a single-segment path, possibly with generic arguments (`Trait<Ident<Args> = ...>`), then we store it into AST as an associated type constraint,
    - otherwise we are reporting a syntactic error.

`for<...>` will be required to introduce names, but our syntax already accepts `for<...>` in that position
```rust
for<'a> Trait<A<'a> = &'a u8>
```
, so we don't have to introduce any new syntax for the name introducer like
```rust
Trait<for<'a> A<'a> = &'a u8>
```
(The only question is whether these two forms can be considered equivalent, it seems like yes.)

**Comment by zserik** [comment]
personally I would prefer
```rust
Trait<for<'a> A<'a> = &'a u8>
```
(about the alternative:) I just wonder what would happen if it may clash, like:
```rust
for<'a> X<'a>: Trait<A<'a> = &'a u8>
```
vs.
```rust
for<'x> X<'x>: Trait<for<'a> A<'a> = &'a u8>
```

I think we should allow both syntax '(es), which should be considered equivalent in simple cases, but may be able to express more complex relations cleanly.

**Comment by petrochenkov** [comment]
The `Trait<for<'a> A<'a> = &'a u8>` form introduces a new syntax and requires a more complex disambiguation because types can start with `for` (`Trait<for<'a> A<'a>>` is a type argument, `Trait<for<'a> A<'a> = &'a u8>` is an assoc type constraint), so I'd prefer to avoid it for now.
It can be added later if it becomes necessary.

**Comment by MingweiSamuel** [comment]
It seems that gat equals gat equality doesn't work, i.e.:
```rust
<A, B>
    A: Gat,
    B: for<'x> Gat<Domain<'x> = A::Domain<'x>>,
```
When you try to use something with the above bound, you get an E0271.

[**Playground Link**](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=415b113c210fea45fe1746d5e0b68f22)

However the following (and other infinitely many variations) do work:
```rust
<A, B, T>
    A: for<'x> Gat<Domain<'x> = T>,
    B: for<'x> Gat<Domain<'x> = T>,
```
```rust
<A, B, T>
    A: for<'x> Gat<Domain<'x> = &'x T>,
    B: for<'x> Gat<Domain<'x> = &'x T>,
```

I think the first bound should cover both the second and third cases, or am I missing something?
