### ISSUE TITLE
Audit & Harden `run-pass` tests for `#![feature(bindings_after_at)]` 

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#67523]
The feature `bindings_after_at` which allows for `x @ Some(y)` patterns, is implemented in https://github.com/rust-lang/rust/pull/66296. The PR doesn't have as good coverage of the dynamic semantics as we might like. Once the PR lands, we should try to improve things before we stabilize the feature.

Notable tests to include:

- [x] Dynamic drop (https://github.com/rust-lang/rust/pull/69810)

cc @pnkfelix @matthewjasper https://github.com/rust-lang/rust/issues/65490

This issue has been assigned to @thekuom via [this comment](https://github.com/rust-lang/rust/issues/67523#issuecomment-595511337).

**Comment by Centril** [comment]
This is now unblocked as https://github.com/rust-lang/rust/pull/66296 has landed.

**Comment by thekuom** [comment]
What is the priority for this? If it's not very high, I can take a shot, but it might take some time since I am still gaining familiarity with the project

**Comment by thekuom** [comment]
I would like to work on this one 👍

**Comment by Centril** [comment]
Go for it :)

@rustbot assign @thekuom

**Comment by Centril** [comment]
Now that https://github.com/rust-lang/rust/pull/69690 has landed, I think we can close this once https://github.com/rust-lang/rust/pull/69810 also lands.
