### ISSUE TITLE
Confusing diagnostic when attempting to implementing trait for tuple

### ISSUE THREAD

**Issue by varkor** [rust-lang/rust#67535]
```rust
impl std::ops::AddAssign for () {
    fn add_assign(&self, other: ()) -> () {
        ()
    }
}
```
produces:
```
error[E0117]: only traits defined in the current crate can be implemented for arbitrary types
  --> src/lib.rs:12:1
   |
12 | impl std::ops::AddAssign for () {
   | ^^^^^-------------------^^^^^--
   | |    |                       |
   | |    |                       this is not defined in the current crate because tuples are always foreign
   | |    this is not defined in the current crate because tuples are always foreign
   | impl doesn't use only types from inside the current crate
   |
   = note: define and implement a trait or new type instead
```
Notice how it highlights `std::ops::AddAssign` and says `this is not defined in the current crate because tuples are always foreign`, despite `AddAssign` have nothing to do with tuples.

**Comment by estebank** [comment]
The change needs to be made somewhere in the logic of

https://github.com/rust-lang/rust/blob/0d2817a439c2ad9fe343f6347eb6d90947893363/src/librustc_typeck/coherence/orphan.rs#L39-L80

**Comment by estebank** [comment]
I see why this happens: `AddAssign` has an `Rhs` type argument with a default type `Self` (`AddAssign<Rhs = Self>`) which means that what was written gets desugared internally to `impl std::ops::AddAssign<Rhs=()> for () { /* ... */ }`, which would have made more sense:

```
error[E0117]: only traits defined in the current crate can be implemented for arbitrary types
  --> src/lib.rs:12:1
   |
12 | impl std::ops::AddAssign<Rhs=()> for () {
   | ^^^^^---------------------------^^^^^--
   | |    |                               |
   | |    |                               this is not defined in the current crate because tuples are always foreign
   | |    this is not defined in the current crate because tuples are always foreign
   | impl doesn't use only types from inside the current crate
   |
   = note: define and implement a trait or new type instead
```

**Comment by TroyNeubauer** [comment]
Would like to work on this. Excited for my first issue!
@rustbot claim

**Comment by estebank** [comment]
@TroyNeubauer you'll have to check whether the trait itself is foreign, and if so avoid adding the "because tuples are always foreign" and instead say "this is not defined in the current crate because this is a foreign trait".
