### ISSUE TITLE
"ref _" pattern should be accepted?

### ISSUE THREAD

**Issue by crlf0710** [rust-lang/rust#67578]
```rust
struct S;
impl Drop for S {
    fn drop(&mut self) {
        println!("D!");
    }
}

fn main () {
    let ref _ = S;
    
    println!("Foo");
}
```
I think this code should compile, but it seems it currently doesn't, giving the error 
```
error: expected identifier, found reserved identifier `_`
```
This written form doesn't conflict with the description within https://doc.rust-lang.org/nightly/reference/patterns.html#reference-patterns, and is indeed useful at times

**Comment by csmoe** [comment]
this works as expected as single `_` is not a valid identifier

**Comment by crlf0710** [comment]
@csmoe I don't agree  `_` is wildcard pattern and i don't see any reason it can't be used here.

@Centril

**Comment by crlf0710** [comment]
Mmmm ok, so it's a Identifier pattern. that's the reason why it's not accepted.

**Comment by crlf0710** [comment]
Opened #67600  as a feature request.
