### ISSUE TITLE
Rust x86_64-pc-windows-msvc throttles CPU to 100%

### ISSUE THREAD

**Issue by tensor-programming** [rust-lang/rust#67570]
Looked around at other issues and didn't seem to find anything about this.  

Ever since I updated the stable branch to `1.40`, I noticed that on compilation and on RLS compilation, the compiler eats my CPU usage and pushes it up to 100%.  This didn't bother me so much until it froze my operating system and forced me to restart during an RLS recompile.  

I incorrectly assumed this had something to do with the compiler version, apparently this happens to me with all of the compilers that I have installed on this machine; not just 1.40.

**Comment by jonas-schievink** [comment]
Please provide an example code base on which this program occurs. How much RAM does your machine have? Is it full, or close to full?

**Comment by tensor-programming** [comment]
I have to correct myself from the initial issue.  

Firstly, I wasn't running 1.40.0 when this crash happened.  I was running 1.39.0 without realizing it because the project that I built was using a rusttoolchain file.  Also, I incorrectly assumed that both the nightly and 1.39.0 were not ramping my CPU usage to 100% because I was building a much smaller project and not seeing this kind of load. In other words, I am seeing a 100% load across all of the compilers that I have installed on my machine if I try to compile a moderately sized application.  

The program that I was compiling is the CLI on the Tauri project that I work on.  This one [here](https://github.com/tauri-apps/tauri/tree/dev/cli/tauri-cli).  I'd say the project is moderately sized.  My machine has 32 gigs of ram and during compilation it was only using maybe 40% of it.  Though actually even without the compilation I am using about 35% of it right now (many chrome tabs open).  When I look at the task manager while cargo compiles the code, I see it spawns 6-7 rustc instances which run at various degrees of load.   

I don't think I've ever seen the compiler put this much load on my CPU, its enough to slow down other programs (VSCode, Emacs etc) and its comparable to when I do video rendering.  Even RLS ramps up to that kind of speeds and I have to wait until it finishes to type in my text editor or else its too slow to respond.

**Comment by retep998** [comment]
Compilation using 100% of your CPU is the *intended* behavior. If you want to limit the amount of concurrency that Rust does you can customize that by specifying `[build] jobs = 1` in the [config](https://doc.rust-lang.org/cargo/reference/config.html).

**Comment by tensor-programming** [comment]
I see, well I guess I made a fuss about nothing.  I do still have concerns considering it crashed my computer.  I've been using rust for 2-3 years now and never encountered this kind of slow down and these problems.

**Comment by retep998** [comment]
Freezing your computer is definitely not intentional, but can happen if all the parallel rust compilations happen to use enough memory to cause page file thrashing. Maxing out CPU usage alone won't freeze your PC but it definitely will cause things to slow down in the meantime.
