### ISSUE TITLE
Occurrences of a libstd or libextra item in the tutorial and manual should link to the docs for it

### ISSUE THREAD

**Issue by lkuper** [rust-lang/rust#6758]
Masklinn recently [suggested on rust-dev](https://mail.mozilla.org/pipermail/rust-dev/2013-May/004139.html) that it would be nice to have cross-linking within the generated HTML docs.  E.g., an occurrence of "`println`" in the tutorial would be a link to [here](http://static.rust-lang.org/doc/core/io.html#function-println) (if I understand the suggestion correctly).  We could do this cross-linking for all top-level items: types, traits, functions, impls, etc.

I wouldn't expect this to happen for code blocks, just for inline code.  Ideally, there would also be a way to turn it off -- both in the sense that we might want to be able to tell rustdoc not to do cross-linking on a particular run (to make the docs build faster), and in the sense that we might want to be able to specify that particular occurrences should never be cross-linked (because after a point it might hinder readability). 

Presumably we'd also eventually want this cross-linking within the documentation itself, too, as well as in the tutorial and manual.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#623
