### ISSUE TITLE
Treat "Failure" and "Safety note" doc comments specially in generated docs

### ISSUE THREAD

**Issue by lkuper** [rust-lang/rust#6759]
As [noted on rust-dev](https://mail.mozilla.org/pipermail/rust-dev/2013-May/004139.html), it's easy for these comments to blend too easily into the surrounding documentation.  Something like a "watch out for this!" icon could help.

**Comment by steveklabnik** [comment]
Triage: no change here.

**Comment by bluss** [comment]
Using headings is very unsatisfactory. I prefer `**Panics** if you blah`.

**Comment by steveklabnik** [comment]
Triage: no changes.

**Comment by Mark-Simulacrum** [comment]
I think we shouldn't really do anything here, and it seems like if we decide to do something we can open an actionable issue and/or try it out by manually doing it -- closing.
