### ISSUE TITLE
[Feature request] Consider accepting "ref _" in wildcard pattern

### ISSUE THREAD

**Issue by crlf0710** [rust-lang/rust#67600]
By using `let ref _x = <expr>`, one can lift the scope of temporary from one-line to the entire current scope. This is convenient and useful. Could we extend this to the wildcard pattern, so we don't have to name the `_x`?

cc. #67578

**Comment by csmoe** [comment]
`ref` will be phased out in the end as a more ergonomics already introduced, and wildcard already "cover" this since you can't use the ref. So I don't think itis necessary.

**Comment by crlf0710** [comment]
the more ergonomics pattern-match syntax is only available in limited situations, as long as it doesn't cover all the use cases of the ole good `ref` (yet) they're two separate things.

**Comment by Centril** [comment]
`ref _` is, as far as I know, never necessary:
```rust
fn foo() {
    match Some((0, 1)) {
        Some((ref _x, _)) => {}
        _ => {}
    }
}
```
You can just use `_` instead.

**Comment by csmoe** [comment]
> the more ergonomics pattern-match syntax is only available in limited situations

I disagree with this, could you list out that?

**Comment by crlf0710** [comment]
@Centril 
After some thought, now i agree that "ref _" is not really the correct thing to add. What i **really** want is something that's anonymous but can force move the value out and promote it to the `'static` lifetime at the same time, and the wildcard pattern cannot force the move. I should think more about this.

@csmoe
Sure, some program like 
`fn foo(ref mut foo: i32) {}`
has no direct equivalences, unless you create a new variable and shadow the old.

**Comment by csmoe** [comment]
`foo: &mut i32` works the same way as `ref mut foo: i32`.
