### ISSUE TITLE
macro export shadowing/duplicate

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#67608]
* root: adhesion-0.5.0: [start](https://crater-reports.s3.amazonaws.com/beta-1.41-1/1.40.0/reg/adhesion-0.5.0/log.txt) v. [end](https://crater-reports.s3.amazonaws.com/beta-1.41-1/beta-2019-12-18/reg/adhesion-0.5.0/log.txt)
 * root: chylli/rust-busybox: [start](https://crater-reports.s3.amazonaws.com/beta-1.41-1/1.40.0/gh/chylli.rust-busybox/log.txt) v. [end](https://crater-reports.s3.amazonaws.com/beta-1.41-1/beta-2019-12-18/gh/chylli.rust-busybox/log.txt)

root: fixed-hash - 4 (4 gh, 0 crates.io) detected crates which regressed due to this
<details>

 * CodeChain-io/codechain-blake-miner: [start](https://crater-reports.s3.amazonaws.com/beta-1.41-1/1.40.0/gh/CodeChain-io.codechain-blake-miner/log.txt) v. [end](https://crater-reports.s3.amazonaws.com/beta-1.41-1/beta-2019-12-18/gh/CodeChain-io.codechain-blake-miner/log.txt)
 * CodeChain-io/codechain-cuckoo-miner: [start](https://crater-reports.s3.amazonaws.com/beta-1.41-1/1.40.0/gh/CodeChain-io.codechain-cuckoo-miner/log.txt) v. [end](https://crater-reports.s3.amazonaws.com/beta-1.41-1/beta-2019-12-18/gh/CodeChain-io.codechain-cuckoo-miner/log.txt)
 * NervosFoundation/serde_bench: [start](https://crater-reports.s3.amazonaws.com/beta-1.41-1/1.40.0/gh/NervosFoundation.serde_bench/log.txt) v. [end](https://crater-reports.s3.amazonaws.com/beta-1.41-1/beta-2019-12-18/gh/NervosFoundation.serde_bench/log.txt)
 * TheWaWaR/cita-create-genesis: [start](https://crater-reports.s3.amazonaws.com/beta-1.41-1/1.40.0/gh/TheWaWaR.cita-create-genesis/log.txt) v. [end](https://crater-reports.s3.amazonaws.com/beta-1.41-1/beta-2019-12-18/gh/TheWaWaR.cita-create-genesis/log.txt)

</details>

root: lsio - 2 (0 gh, 2 crates.io) detected crates which regressed due to this
<details>

 * lsio-0.1.18: [start](https://crater-reports.s3.amazonaws.com/beta-1.41-1/1.40.0/reg/lsio-0.1.18/log.txt) v. [end](https://crater-reports.s3.amazonaws.com/beta-1.41-1/beta-2019-12-18/reg/lsio-0.1.18/log.txt)
 * opentracing-0.1.0: [start](https://crater-reports.s3.amazonaws.com/beta-1.41-1/1.40.0/reg/opentracing-0.1.0/log.txt) v. [end](https://crater-reports.s3.amazonaws.com/beta-1.41-1/beta-2019-12-18/reg/opentracing-0.1.0/log.txt)

</details>

cc @petrochenkov 

cc https://github.com/rust-lang/rust/issues/49084 (though not directly relevant)

I suspect this is a semi-intentional change.

These crates also fail, but with shadowing of built-ins; I suspect this is the same bug:

* root: conniecs-0.2.0: [start](https://crater-reports.s3.amazonaws.com/beta-1.41-1/1.40.0/reg/conniecs-0.2.0/log.txt) v. [end](https://crater-reports.s3.amazonaws.com/beta-1.41-1/beta-2019-12-18/reg/conniecs-0.2.0/log.txt)

 * root: lightning-wire-msgs-0.2.1: [start](https://crater-reports.s3.amazonaws.com/beta-1.41-1/1.40.0/reg/lightning-wire-msgs-0.2.1/log.txt) v. [end](https://crater-reports.s3.amazonaws.com/beta-1.41-1/beta-2019-12-18/reg/lightning-wire-msgs-0.2.1/log.txt)

root: lime-render - 2 (1 gh, 1 crates.io) detected crates which regressed due to this
<details>

 * lime-0.1.0: [start](https://crater-reports.s3.amazonaws.com/beta-1.41-1/1.40.0/reg/lime-0.1.0/log.txt) v. [end](https://crater-reports.s3.amazonaws.com/beta-1.41-1/beta-2019-12-18/reg/lime-0.1.0/log.txt)
 * andrewhickman/ecs-demo: [start](https://crater-reports.s3.amazonaws.com/beta-1.41-1/1.40.0/gh/andrewhickman.ecs-demo/log.txt) v. [end](https://crater-reports.s3.amazonaws.com/beta-1.41-1/beta-2019-12-18/gh/andrewhickman.ecs-demo/log.txt)

</details>

**Comment by Centril** [comment]
Intentionally made an error in https://github.com/rust-lang/rust/pull/65785/commits/8e27c4f3122c2ccb529ee3911a9d7e956f2462cd.
