### ISSUE TITLE
Typo in semaphore in the doc

### ISSUE THREAD

**Issue by yzhong52** [rust-lang/rust#67606]
I noticed that this is fixed by this commit: 

https://github.com/rust-lang/rust/commit/ac27ec2a4877fcbf778e103022c5e654f8c248b0

However, in the rust-lang doc, the typos was still there: 

https://doc.rust-lang.org/1.7.0/std/sync/struct.Semaphore.html

> Deprecated since 1.7.0: easily confused with system sempahores and not used enough to pull its weight

The file is nowhere to be found on the master. So I assume it was deleted and the doc was just out of date?

**Comment by Mark-Simulacrum** [comment]
We do not have semaphores in the standard library today; those docs are quite old (we are on version 1.40 now).
