### ISSUE TITLE
Tracking code that can panic?

### ISSUE THREAD

**Issue by axos88** [rust-lang/rust#67607]
This is just something that occured to me that *might* be useful for a lot of things, but it will probably be a lot of work and might turn out to be a hard (as in non-linear) problem and might not be worth the trouble. Anyways, throwing it in here.

So the compiler potentially *could* track code that is able and is not able to panic. This could lead to solutions to a few things on the wishlist, such as https://github.com/rust-lang/rfcs/pull/1736, and probably many others.

A new set of `Fn` subtypes could be introduced, that would only compile if the code within is unable to panic, and then `core::mem::replace_with` could ask for such a function.
A lot of unsafe code could probably benefit too by `knowing` that a piece of code is unable to panic, or accepting only callbacks / Fn-s that are known not to panic. A lot of safety nets could be removed.
Actually the implementation of the https://github.com/Sgeo/take_mut/blob/master/src/lib.rs is an example where an input closure panicking might lead to UB, and having the compiler make that check can remove the catch_unwind checks.

There will probably be a bit of head scratching around FFI, but I think it might be safe to assume any code that calls FFI can panic (since it can pretty much circumvent all of rust's safety checks).

I'm nowhere near knowledgable enough to make this into an RFC, but if there is generally positive feedback on this, I might try to tackle it.

**Comment by Mark-Simulacrum** [comment]
General discussion like this is best suited for internals.rust-lang.org; I don't think this is the right place for it as it's not really a bug. As such, going to go ahead and close.

You may also find https://github.com/dtolnay/no-panic/ interesting.
