### ISSUE TITLE
temporary value dropped while borrowed

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#67609]
* root: gb2260-0.1.1: [start](https://crater-reports.s3.amazonaws.com/beta-1.41-1/1.40.0/reg/gb2260-0.1.1/log.txt) v. [end](https://crater-reports.s3.amazonaws.com/beta-1.41-1/beta-2019-12-18/reg/gb2260-0.1.1/log.txt)

root: imperative - 3 (1 gh, 2 crates.io) detected crates which regressed due to this
<details>

 * committed-0.1.11: [start](https://crater-reports.s3.amazonaws.com/beta-1.41-1/1.40.0/reg/committed-0.1.11/log.txt) v. [end](https://crater-reports.s3.amazonaws.com/beta-1.41-1/beta-2019-12-18/reg/committed-0.1.11/log.txt)
 * imperative-1.0.1: [start](https://crater-reports.s3.amazonaws.com/beta-1.41-1/1.40.0/reg/imperative-1.0.1/log.txt) v. [end](https://crater-reports.s3.amazonaws.com/beta-1.41-1/beta-2019-12-18/reg/imperative-1.0.1/log.txt)
 * epage/committed: [start](https://crater-reports.s3.amazonaws.com/beta-1.41-1/1.40.0/gh/epage.committed/log.txt) v. [end](https://crater-reports.s3.amazonaws.com/beta-1.41-1/beta-2019-12-18/gh/epage.committed/log.txt)

</details>

cc @matthewjasper (likely MIR borrowck related, though not the transition itself as that happened last cycle)

**Comment by Centril** [comment]
Probably a result of the soundness fixes in https://github.com/rust-lang/rust/pull/66650?

**Comment by matthewjasper** [comment]
This is a change in promotion. cc @ecstatic-morse

**Comment by matthewjasper** [comment]
Minimized:

```rust
static DIVISIONS_200312: Option<String> = None;

pub static DIVISIONS: &[&'static Option<String>] = {
    let x = &[&DIVISIONS_200312];
    x
};
```

**Comment by matthewjasper** [comment]
Maybe #66587?

**Comment by matthewjasper** [comment]
or #66642

**Comment by matthewjasper** [comment]
It's #66950, likely #66654.
