### ISSUE TITLE
[Windows] Way to make child processes inherits parent attributes?

### ISSUE THREAD

**Issue by tesuji** [rust-lang/rust#67616]
Rust is using it internally: https://github.com/rust-lang/rust/search?q=security_attributes&unscoped_q=security_attributes
But rust doesn't expose that to public APIs.
That makes people fall into unsafe Rust with CreateFileW and CreateFile2.

**Comment by lzutao** [comment]
Current usecases:
* https://github.com/rust-lang/rustup/blob/93e6d7dd0fe59ed69d8fde776301bc1b097ffccb/src/cli/self_update.rs#L966
* https://github.com/rust-lang/rust/blob/150322f86d441752874a8bed603d71119f190b8b/src/libstd/sys/windows/process.rs#L283
* https://github.com/rust-lang/rust/blob/d8bdb3fdcbd88eb16e1a6669236122c41ed2aed3/src/libstd/sys/windows/pipe.rs#L147

**Comment by lzutao** [comment]
I changed the feature request. Does this sound more plausible?
cc @repnop for Windows advices.

**Comment by lzutao** [comment]
cc @retep998

**Comment by retep998** [comment]
What you're proposing is adding the `security_attributes` method to the public API exposed through `OpenOptionsExt` on Windows? If so, what should the type signature look like?

**Comment by lzutao** [comment]
> adding the `security_attributes` method

Nope. I just want a way to make child processes inherits its parent attribute.

**Comment by retep998** [comment]
Oh, you want to specify that a handle should be inherited by a child process. Marking the handle as inheritable is actually the wrong thing to do. The *correct* approach which I mentioned in https://github.com/rust-lang/rust/issues/54760 is to explicitly tell `CreateProcess` which handles we want to inherit as done in https://devblogs.microsoft.com/oldnewthing/?p=8873

**Comment by Dylan-DPC** [comment]
Closing this as there is no clear path on what's being proposed and the issue has been stalled as well
