### ISSUE TITLE
type inference regression

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#67610]
* root: varkor/metasub: [start](https://crater-reports.s3.amazonaws.com/beta-1.41-1/1.40.0/gh/varkor.metasub/log.txt) v. [end](https://crater-reports.s3.amazonaws.com/beta-1.41-1/beta-2019-12-18/gh/varkor.metasub/log.txt)

I usually deem these as not too interesting but this one felt a bit out of the norm -- it looks like `&Foo.to_string_lossy()` used to (deref?) coerce to `&str` but not sure. I think it's fine to just close this if we don't want to do deeper investigation here.

cc @varkor

**Comment by varkor** [comment]
I think this was noted in https://github.com/rust-lang/rust/pull/64856#issuecomment-544719717 and it was agreed in FCP to accept this regression: https://github.com/rust-lang/rust/pull/64856#issuecomment-548999127. Thanks for noting it, though!
