### ISSUE TITLE
Promote taking a reference to a static

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#67628]
@eddyb authored a FIXME question in https://github.com/rust-lang/rust/blob/a916ac22b9f7f1f0f7aba0a41a789b3ecd765018/src/librustc_mir/transform/promote_consts.rs#L527 (essentially "why do we need to mark statics as unpromotable?").

The reason we check this is so no relocations to statics ever end up in promoteds. Because otherwise we'd promote references to references to statics: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=05ecec8a395e9b10e16844233a336fc4

I believe the question is in fact asking why this would be problematic. Having the address of a static inside a promoted is absolutely no problem.

Now this is a curious situation. We don't want to widen the scope of promotion, but at the same time, this would simplify promotion because a special case would get eliminated.

cc @RalfJung @ecstatic-morse

**Comment by RalfJung** [comment]
If promoteds are consts under the new scheme, shouldn't they be disallowed from referring to statics, like other consts are? Otherwise they'll trigger the new dynamic check you added?

**Comment by oli-obk** [comment]
uses of promoteds and statics are `Operand::Constant`, that doesn't mean anything about promoteds or statics has changed. The whole "promoteds are consts" thing is just about how the mir accesses promoteds.

Although we'll still have to take care that const fn don't end up getting pointers to (interior or regularly) mutable statics

**Comment by RalfJung** [comment]
Well I think we should conceptually make promoteds constants or statics though, instead of having to maintain a *third* category of compile-time evaluated things. And constants seems to fit best, given they have the restriction that inlining their initializer into all uses and evaluating it at run-time should be equivalent to pre-computing it and just putting the result into the binary.

**Comment by ecstatic-morse** [comment]
Currently, there's a lot of duplication between the logic for [const-checking](https://github.com/rust-lang/rust/blob/a9dd56ff9a08d74c53d5cc22d18f126a12749608/src/librustc_mir/transform/check_consts/validation.rs#L401) and the logic for [promotability](https://github.com/rust-lang/rust/blob/a9dd56ff9a08d74c53d5cc22d18f126a12749608/src/librustc_mir/transform/promote_consts.rs#L560). My long-term goal is to use the same code for both, with the extra checks for promotability running on top of const-checking. If this were accomplished, it would require a special-case to make `&&STATIC` eligible for promotion until constants are allowed to refer to statics.

I think we should maintain the status quo here.

**Comment by oli-obk** [comment]
Yea, these arguments all make total sense

**Comment by Centril** [comment]
> until constants are allowed to refer to statics.

We should not make plans based on this however as, currently, I'm quite skeptical of constants being allowed to refer to statics.

**Comment by RalfJung** [comment]
Is that tracked anywhere? FWIW, I am supportive of it.
