### ISSUE TITLE
unable to build rust on tiers-3 platform

### ISSUE THREAD

**Issue by semarie** [rust-lang/rust#67624]
with the introduction of #65939, the `bootstrap.py` mandatories the use of downloaded `rustfmt`. but all platforms doesn't have binary distribution, mainly tiers-3 platforms like OpenBSD.

For rustc or cargo dependencies, it is possible to use `config.toml` (with `rustc` and `cargo` key in `[build]` section) to point to alternate binaries. this way, `bootstrap.py` doesn't download them and use local supplied binaries.

For `rustfmt` it is currently not possible: if `bootstrap.py` is able to deal with it, `rustbuild` will complains that `rustfmt` isn't a valid key:
```
failed to parse TOML configuration 'config.toml': unknown field `rustfmt`, expected one of `build`, `host`, `target`, `cargo`, `rustc`, `docs`, `
compiler-docs`, `submodules`, `fast-submodules`, `gdb`, `nodejs`, `python`, `locked-deps`, `vendor`, `full-bootstrap`, `extended`, `tools`, `verb
ose`, `sanitizers`, `profiler`, `cargo-native-static`, `low-priority`, `configure-args`, `local-rebuild`, `print-step-timings` for key `build` at
 line 26 column 1
```

What would be the right way to use a local `rustfmt` binary in order to copte with #65939, and not force the use of downloaded binary ?

Would adding a `rustfmt` key in `[build]` section of `config.toml` would be accepted (I could provide a patch of it, if yes) ? or should another method used ?

Cc @anp @Mark-Simulacrum

**Comment by Mark-Simulacrum** [comment]
Yes, that was on oversight on my part. I would be happy to review a patch adding it to config.toml.

You should also be able to comment out the line in stage0.txt as a (possibly) temporary fix, this is my plan for beta and stable branches FWIW.
