### ISSUE TITLE
rustdoc does not verify feature gates

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#67647]
This generates documentation with a stable rustdoc today without any warnings.

```rust
#![feature(raw)]

use std::raw::TraitObject;

pub fn bar() {}
```

Interestingly, rustdoc does seem to check that the feature gate is in the crate (i.e., `#![feature(raw)]` must exist), and will error if a feature gate has been removed (e.g., custom_attribute on nightly).

**Comment by Mark-Simulacrum** [comment]
cc @GuillaumeGomez @rust-lang/rustdoc

**Comment by kinnison** [comment]
I'd guess this is related to https://github.com/rust-lang/rust/blob/master/src/librustdoc/core.rs#L318 somehow.  I'm not entirely sure what rustdoc relies on which would mandate the locking in of the permission to use unstable features, but perhaps @GuillaumeGomez would know?

**Comment by GuillaumeGomez** [comment]
Normally, for such things rustdoc relies on rustc internals to do the work. Maybe an option is badly set?

**Comment by pnkfelix** [comment]
triage: looks like this should be T-rustdoc's call as to what priority to assign here. Leaving unprioritized and nominated, at least for a week.

**Comment by GuillaumeGomez** [comment]
I made the priority medium: it's not a huge bug but the quicker it's fixed, the better it'll be for everyone.

**Comment by ollie27** [comment]
#67989 should fix this.

**Comment by Mark-Simulacrum** [comment]
@ollie27 Thanks! I've also gone ahead and nominated it for beta backport as it's probably good to close the stability hole sooner rather than later; it's a trivial patch.
