### ISSUE TITLE
some items disappear the latest in rustc-ap-syntax

### ISSUE THREAD

**Issue by rchaser53** [rust-lang/rust#67653]
Some items related rustc-ap-syntax::parse are disappeared in the latest in rustc-ap-syntax.
They exist in rustc-ap-syntax version 610.0.0. The current rustfmt uses version 610.0.0.
They are in rustc_parse now, but rustc_parse is [an internal compiler API](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_parse/index.html). we cannot use it.

Is it possible to publish rustc_parse or create the crate something like rustc_ap-lexer for parser?
I am having trouble updating rust-ap- * of rustfmt...

**Comment by rchaser53** [comment]
The following items are examples that disappeared with the latest rustc-ap-syntax.
(The link is the current position in the latest rust source)

- [syntax::parse::parser::Parser](https://github.com/rust-lang/rust/blob/master/src/librustc_parse/parser/mod.rs#L103)
- [syntax::parse::DirectoryOwnership](https://github.com/rust-lang/rust/blob/master/src/librustc_parse/lib.rs#L40)
- [syntax::parse::parser::ModulePathSuccess](https://github.com/rust-lang/rust/blob/master/src/librustc_parse/parser/module.rs#L23)
- [syntax::parse::new_sub_parser_from_file](https://github.com/rust-lang/rust/blob/master/src/librustc_parse/lib.rs#L148)

**Comment by est31** [comment]
I think the relevant issue is https://github.com/alexcrichton/rustc-auto-publish/issues/14

**Comment by rchaser53** [comment]
This issue is resolved, so I close it.
