### ISSUE TITLE
stringify!(r#match) should return "match" instead of "r#match" if token is matched as ident

### ISSUE THREAD

**Issue by kdy1** [rust-lang/rust#67652]
Minimal repro case: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=9a6b2039be61e67303d4e194acd5d4bb

**Comment by jonas-schievink** [comment]
Why? This looks correct to me. `match` is not a valid ident, after all.

**Comment by Mark-Simulacrum** [comment]
I am going to close as expected behavior; `r#match` is a valid identifier but `match` is not, as @jonas-schievink notes.
