### ISSUE TITLE
SIGSEGV during compilation when taking address of extern x86-interrupt fn

### ISSUE THREAD

**Issue by iximeow** [rust-lang/rust#67674]
```rust
#![feature(abi_x86_interrupt)]

#[repr(C)]
pub struct Context<'a> {
    inner: &'a mut u8,
}

extern "x86-interrupt" fn isr(_: Context) { }

pub fn main() {
    println!("oops: {:x}", isr as usize);
}
```

yields

```
> rustc crash.rs 
Segmentation fault (core dumped)
```

Interestingly, it seems like `#[repr(C)]` is load-bearing? No crash without a `repr` on the argument type. Also no crash if the argument is zero-sized (even with `#[repr(C)]`).

**Comment by iximeow** [comment]
It seems like this might be related to https://github.com/rust-lang/rust/issues/63018, where this is also resulting in nonsense IR to LLVM?

**Comment by workingjubilee** [comment]
This no longer appears to crash?

**Comment by iximeow** [comment]
yup, looks like this was fixed in the last few years:

```
[17:53:33] # iximeow:~> ./crash
oops: 55fa21ef0ad0
```

neat!
