### ISSUE TITLE
Major async/await compiler performance regression

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#67706]
Something in #67670 caused a major performance [regression](https://perf.rust-lang.org/compare.html?start=74c4e6a981d3150db8444c8d250e50bbe6b93b6b&end=3a087ad3a924be12343bb035bf9b63ed81f650bf&stat=instructions:u). Query that regressed is normalize_ty_after_erasing_regions, but not sure if that means much. I suspect that https://github.com/rust-lang/rust/pull/65244 is the PR responsible, but have no proof.

**Comment by Centril** [comment]
Seems like the most prudent course of action is to create a revert PR for https://github.com/rust-lang/rust/pull/65244 to see if perf is regained.

**Comment by Mark-Simulacrum** [comment]
I wouldn't be opposed to such a course. Not sure if I'll have the time to do so for a day or two, though.

**Comment by wesleywiser** [comment]
Testing a revert in #67768

**Comment by wesleywiser** [comment]
Looks like #65244 is the cause.

**Comment by pnkfelix** [comment]
triage: P-high; leaving nominated for discussion at meeting (namely discussion of revert)

**Comment by pnkfelix** [comment]
[Discussed](https://zulip-archive.rust-lang.org/131828tcompiler/22121weeklymeeting2020010254818.html#184660427) in T-compiler meeting.

Members present generally approved a revert of PR #65244 to resolve this issue in short term.

**Comment by wesleywiser** [comment]
I guess I should re-open my revert then?

**Comment by Mark-Simulacrum** [comment]
Yes, please do, and I (or someone else) can review it, I think, fairly quickly.

**Comment by tmandry** [comment]
Fixed in #67768.
