### ISSUE TITLE
`test/run-make-fulldeps/pgo-branch-weights` fails occasionally on CI

### ISSUE THREAD

**Issue by JohnTitor** [rust-lang/rust#67746]
You can see this test fails occasionally in some pull requests: https://github.com/rust-lang/rust/pulls?utf8=%E2%9C%93&q=is%3Apr+pgo-branch-weights

I don't think this is due to PR changes. Could we modify, or just remove this for now?

**Comment by Centril** [comment]
cc @Zoxc @michaelwoerister

**Comment by michaelwoerister** [comment]
If the test fails, it indicates that there's a bug to be fixed. I'll try to reproduce.

**Comment by pnkfelix** [comment]
triage: P-high

**Comment by michaelwoerister** [comment]
Has this issue occurred since the potential fix in #67829 landed?

**Comment by JohnTitor** [comment]
I've not seen the failure recently.

**Comment by michaelwoerister** [comment]
I think that's in order, yes. We can re-open if the issue re-appears.
