### ISSUE TITLE
Redundant `use` suggestion for incorrectly invoked macro

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#67740]
The `use` suggestion shouldn't be emitted as `format` is already in scope.

```
error[E0423]: expected function, found macro `format`
   --> src/librustc_typeck/check/pat.rs:627:29
    |
627 |                     e.note(&format("`{}` is interpreted as a constant pattern, not a new blinding", qpath));
    |                             ^^^^^^
    |
help: use `!` to invoke the macro
    |
627 |                     e.note(&format!("`{}` is interpreted as a constant pattern, not a new blinding", qpath));
    |                             ^^^^^^^
help: possible better candidate is found in another module, you can import it into scope
    |
1   | use std::fmt::format;
    |
```

_Edit:_ The suggestion is _correct_: `std::fmt::format` is _not_ the `format!()` macro. That being said, the import suggestion should have slightly different wording if other suggestions are provided. Changing it to "alternatively, another candidate is found..." would make it clearer, but this indeed _not_ a bug.

**Comment by petrochenkov** [comment]
I don't think this is a bug - https://github.com/rust-lang/rust/pull/68294#issuecomment-575852070.
