### ISSUE TITLE
Fn traits with array args no longer work with const_generics enabled

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#67753]
```rust
#![feature(const_generics)]

fn main() {
    takes_closure_of_array_3(|[x, y, z]| {
        println!("args: x={}, y={}, z={}", x, y, z);
    });
}

fn takes_closure_of_array_3<F>(f: F)
where
    F: Fn([i32; 3]),
{
    f([1, 2, 3]);
}
```

([playpen](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=dd61053708a51e96786e54286e048ced))

Gives the error:
```
   Compiling playground v0.0.1 (/playground)
warning: the feature `const_generics` is incomplete and may cause the compiler to crash
 --> src/main.rs:1:12
  |
1 | #![feature(const_generics)]
  |            ^^^^^^^^^^^^^^
  |
  = note: `#[warn(incomplete_features)]` on by default

error[E0391]: cycle detected when const-evaluating + checking `takes_closure_of_array_3::{{constant}}#0`
  --> src/main.rs:11:17
   |
11 |     F: Fn([i32; 3]),
   |                 ^
   |
note: ...which requires const-evaluating + checking `takes_closure_of_array_3::{{constant}}#0`...
  --> src/main.rs:11:17
   |
11 |     F: Fn([i32; 3]),
   |                 ^
......................
9  | / fn takes_closure_of_array_3<F>(f: F)
10 | | where
11 | |     F: Fn([i32; 3]),
12 | | {
13 | |     f([1, 2, 3]);
14 | | }
   | |_^

```

This compiles fine with const_generics not enabled, and is a regression

cc @centril @oli-obk

**Comment by Manishearth** [comment]
(discovered by @jcoglan)

**Comment by Centril** [comment]
cc @nikomatsakis @eddyb @varkor 

Simplified:
```rust
#![feature(const_generics)]

fn main() {
    takes_closure_of_array(|_| {});
}

fn takes_closure_of_array<F>(f: F)
where
    F: FnOnce([i32; 0]),
{
    f([]);
}
```

**Comment by jonas-schievink** [comment]
Isn't this expected fallout?

**Comment by varkor** [comment]
This is an expected consequence of https://github.com/rust-lang/rust/pull/6688.

**Comment by Manishearth** [comment]
Seems like https://github.com/rust-lang/rust/issues/60471 is what's supposed to eventually fix this?

**Comment by pnkfelix** [comment]
triage: P-medium, removing nomination.

**Comment by eddyb** [comment]
@varkor @oli-obk I think we've discussed this before, but what do you think of special-casing literals, to unblock at least some common usecases like this?

**Comment by oli-obk** [comment]
I can't reproduce on master, this may have gotten fixed? (Note that the playground is severely outdated, a fix is underway for that though)

**Comment by varkor** [comment]
@eddyb pointed out that https://github.com/rust-lang/rust/pull/68118 most likely fixed this.
