### ISSUE TITLE
Compiler crash in definition of trait method that takes and returns an associated type with generics.

### ISSUE THREAD

**Issue by NonNullableName** [rust-lang/rust#67754]
The compiler crashed when trying to define an inline method in a trait with an associated type that contains a generic and a bound to that generic.

I tried this code:

```rust
#![features(generic_associated_types,proc_macro_hygiene)]

use core::ops::Deref;
#[doc(hidden)]
pub use high_mem_utils::{DontDrop, DontDropOpt, DropBy};
#[doc(hidden)]
pub use std::{hint::unreachable_unchecked, mem::transmute_copy};
#[doc(hidden)]
pub use std::mem::{MaybeUninit, transmute};
#[doc(hidden)]
pub use macro_helper::{expansion_bucle, expansion_bucle_counted};
#[doc(hidden)]
pub use compile_ops::{add, sub};

pub trait VectorForMapLit {
    type Vect<T>: Deref<Target = [T]>;

    #[inline]
    fn gen<'a, T, C: Fn()>(map: &'a mut Self::Vect, code: C, len: usize) -> &'a mut Self::Vect {
        let mut actual_len = DontDrop(map.len());
        let actual_ptr = &actual_len.0 as *const usize;
        map.reserve(len);
        let mut map = DropBy::new(map, |mut v| unsafe { v.set_len(actual_ptr.read()) });

        unsafe {
            let map_ptr: *mut T = match map.value {
                            Some(ref mut a) => a.as_mut_ptr(),
                            None => unreachable_unchecked(),
                        };

            code();
        }

        let mut vec1 = map.take().unwrap_or_else(|| unsafe { unreachable_unchecked() });
        unsafe { vec1.set_len(actual_len.0) };
        vec1
    }
}
```

I expected they to compile well without expand the macro that use the `gen` method.

Instead,the compiler crashed with the message `error: internal compiler error: src\librustc\ty\subst.rs:610: type parameter ``T/#1`` (T/1) out of range when substituting (root type=Some([T])) substs=[Self]`,where obviously the double backticks are only one.

## Meta

`rustc --version --verbose`:
rustc 1.41.0-nightly (c8ea4ace9 2019-12-14)
binary: rustc
commit-hash: c8ea4ace9213ae045123fdfeb59d1ac887656d31
commit-date: 2019-12-14
host: i686-pc-windows-msvc
release: 1.41.0-nightly
LLVM version: 9.0

**Comment by jonas-schievink** [comment]
Please try this on the newest nightly

**Comment by NonNullableName** [comment]
I will do it and post when I have that version installed,curiosly `rustup update` skipped every component last time I executed they.

**Comment by NonNullableName** [comment]
I did it,the compiler not crash and rather gave me an error.
