### ISSUE TITLE
Trait alias compilation failure when returning impl Alias

### ISSUE THREAD

**Issue by hniksic** [rust-lang/rust#67751]
While working on a [stackoverflow question](https://stackoverflow.com/q/59535042/1600898) I encountered the need for trait aliases. For example, this code ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=291acfce5a541b53d3bb5ee3eee6c267)) uses a very long trait several times:

```rust
fn to_box_factory<F, RET>(f: F) -> impl Fn(&'static str) -> Box<dyn Iterator<Item = &'static str>>
where
    F: Fn(&'static str) -> RET,
    RET: Iterator<Item = &'static str> + 'static,
{
    move |s| Box::new(f(s))
}

fn main() {
    let f1: &dyn Fn(&'static str) -> Box<dyn Iterator<Item = &'static str>> = &to_box_factory(|s| s.split_whitespace());
    let f2: &dyn Fn(&'static str) -> Box<dyn Iterator<Item = &'static str>> = &to_box_factory(|s| s.split_ascii_whitespace());
    let fs = vec![f1, f2];
    fs[0]("rust 2020").for_each(|s| println!("{}", s));
    fs[1]("rust 2020").for_each(|s| println!("{}", s));
}
```

It would improve readability and reduce duplication to introduce a trait alias for `Fn(&'static str) -> Box<dyn Iterator<Item = &'static str>>`. My attempt was to simply replace all uses of the trait with the alias, resulting in the following ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=f43b7b261c6560dbdcf8c24831fe1eb9)):

```rust
#![feature(trait_alias)]
trait BoxFactory = Fn(&'static str) -> Box<dyn Iterator<Item = &'static str>>;

fn to_box_factory<F, RET>(f: F) -> impl BoxFactory
where
    F: Fn(&'static str) -> RET,
    RET: Iterator<Item = &'static str> + 'static,
{
    move |s| Box::new(f(s))
}

fn main() {
    let f1: &dyn BoxFactory = &to_box_factory(|s| s.split_whitespace());
    let f2: &dyn BoxFactory = &to_box_factory(|s| s.split_ascii_whitespace());
    let fs = vec![f1, f2];
    fs[0]("rust 2020").for_each(|s| println!("{}", s));
    fs[1]("rust 2020").for_each(|s| println!("{}", s));
}
```

However, that fails to compile with the following error:

```
error[E0271]: type mismatch resolving `<[closure@src/main.rs:9:5: 9:28 f:_] as std::ops::FnOnce<(&'static str,)>>::Output == std::boxed::Box<(dyn std::iter::Iterator<Item = &'static str> + 'static)>`
 --> src/main.rs:4:36
  |
4 | fn to_box_factory<F, RET>(f: F) -> impl BoxFactory
  |                      ---           ^^^^^^^^^^^^^^^ expected type parameter `RET`, found trait `std::iter::Iterator`
  |                      |
  |                      this type parameter
  |
  = note: expected struct `std::boxed::Box<RET>`
             found struct `std::boxed::Box<(dyn std::iter::Iterator<Item = &'static str> + 'static)>`
  = help: type parameters must be constrained to match other types
  = note: for more information, visit https://doc.rust-lang.org/book/ch10-02-traits.html#traits-as-parameters
  = note: the return type of a function must have a statically known size
```

I'm not sure I understand that error, nor do I understand why the error doesn't appear in the first version.

Curiously, if I just replace `-> impl BoxFactory` with the full incantation of `-> impl Fn(&'static str) -> Box<dyn Iterator<Item = &'static str>>` ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=5d1fb060e67f7bf0add8c70f917b7631)), but leave the other two uses of the alias in `main()`, the code compiles and runs correctly. Is it a bug that returning `impl Alias` fails, while returning `impl [original trait]` works?

Note: I am aware that trait aliases are experimental. My motivation for reporting this issue is to ensure that problems with the feature (if any) are worked out before it is stabilized.

**Comment by hniksic** [comment]
While experimenting with something else, I figured out how to make this example compile. It seems that the type inference from closure is confused, and it compiles when `as _` is added after the closure, i.e. when `move |s| Box::new(f(s))` is changed to `move |s| Box::new(f(s)) as _`.

I'm not sure that `as _` should be required here, and the diagnostics could likely be better. I hope this helps with labeling of this bug.

**Comment by hniksic** [comment]
Note that the same issue is present when you emulate a type alias with a custom trait with a blanket implementation. Instead of a `BoxFactory` alias, we define a new trait with a blanket impl:

```rust
trait BoxFactory: Fn(&'static str) -> Box<dyn Iterator<Item = &'static str>> {}

impl<T> BoxFactory for T where T: Fn(&'static str) -> Box<dyn Iterator<Item = &'static str>> {}
```

Then the original `to_box_factory` results in a very similar compilation error ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=ad71948c6574fd669867c8b70d5b9944)):

```rust
fn to_box_factory<F, RET>(f: F) -> impl BoxFactory
where
    F: Fn(&'static str) -> RET,
    RET: Iterator<Item = &'static str> + 'static,
{
    move |s: &'static str| Box::new(f(s))
}

// error[E0271]: type mismatch resolving `<[closure@src/lib.rs:10:5: 10:42 f:_] as std::ops::FnOnce<(&'static str,)>>::Output == std::boxed::Box<(dyn std::iter::Iterator<Item = &'static str> + 'static)>`
//  --> src/lib.rs:5:36
//   |
// 5 | fn to_box_factory<F, RET>(f: F) -> impl BoxFactory
//   |                      ---           ^^^^^^^^^^^^^^^ expected type parameter `RET`, found trait object `dyn std::iter::Iterator`
//   |                      |
//   |                      this type parameter
//   |
//   = note: expected struct `std::boxed::Box<RET>`
//              found struct `std::boxed::Box<(dyn std::iter::Iterator<Item = &'static str> + 'static)>`
//   = help: type parameters must be constrained to match other types
//   = note: for more information, visit https://doc.rust-lang.org/book/ch10-02-traits.html#traits-as-parameters
//   = note: required because of the requirements on the impl of `BoxFactory` for `[closure@src/lib.rs:10:5: 10:42 f:_]`
//   = note: the return type of a function must have a statically known size
```

...whereas the version with `as _` compiles and runs as expected.

**Comment by jyn514** [comment]
The original code now compiles and runs.

**Comment by hniksic** [comment]
@jyn514 What compiler version does it compile with? When I try it with the 1.55.0-nightly (2021-07-05) currently in the Playground, it fails with the same error message as before. Note that the first snippet is just a setup, the [second one](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=f43b7b261c6560dbdcf8c24831fe1eb9) is the one that actually fails.

**Comment by jyn514** [comment]
Oh sorry, I misread the original issue. Yes, the second one still fails on nightly.

**Comment by plazmoid** [comment]
Both snippets are working now

**Comment by hniksic** [comment]
@plazmoid Indeed, I believe this can be closed.

The stable snippet in from [this comment](https://github.com/rust-lang/rust/issues/67751#issuecomment-724133190) still doesn't compile, but that should probably be submitted as a separate issue, to prevent scope creep.
