### ISSUE TITLE
std::net::TcpListener.incoming documentation says the method is equivalent to accept

### ISSUE THREAD

**Issue by croraf** [rust-lang/rust#67772]
In https://github.com/rust-lang/rust/blob/master/src/libstd/net/tcp.rs#L739-L796 `incoming` and `accept` methods are implemented for TcpListener. 

The docs for `incoming` say
```
Iterating over it (the returned iterator) is equivalent to calling `accept` in a loop.
```

This is not true as `accept()` returns a tuple and `incoming`'s iterator returns only `TcpStream` struct.

**Comment by croraf** [comment]
Perhaps change it with 
```
Iterating over it is equivalent to calling `accept` in a loop, except that `accept` will return a tuple of `(TcpStream, SocketAddr)` instead of just `TcpStream` instance.
```

**Comment by nagisa** [comment]
Functionally it is equivalent and you can recover the peer address through methods on the `TcpStream` type.

**Comment by Mark-Simulacrum** [comment]
Given that we explicitly call out in current [docs](https://doc.rust-lang.org/nightly/std/net/struct.TcpListener.html#method.incoming) that we don't provide the peer addr, I think it's reasonable to say that this is sufficiently done that we don't need an issue tracking it. Further improvements can be done by PR if desired.
