### ISSUE TITLE
Tracking issue for RFC 2632 `?const` trait bound opt-out

### ISSUE THREAD

**Issue by ecstatic-morse** [rust-lang/rust#67794]
This is the tracking issue for the [`?const` opt-out for trait bounds](https://github.com/oli-obk/rfcs/blob/const_generic_const_fn_bounds/text/0000-const-generic-const-fn-bounds.md#const-syntax) described in rust-lang/rfcs#2632. The primary tracking issue for that RFC is #67792. The feature gate for it is `const_trait_bound_opt_out`.

This RFC has not yet been accepted. It is being implemented on a provisional basis to [evaluate the potential fallout](https://github.com/rust-lang/rfcs/pull/2632#issuecomment-567699174).

cc https://github.com/rust-lang/rust/issues/57563

Implementation steps:

* [x] Implement (#68140)
* [ ] Forbid `?const` outside `const fn` or `impl const Trait`

**Comment by clarfonthey** [comment]
From what I understand, this was recently changed to `~const` but none of the tilde-const PRs link back to this one, and the issue name/description should be updated?

**Comment by clarfonthey** [comment]
cc @oli-obk @fee1-dead since from what I understand you two know the most about this change

**Comment by fee1-dead** [comment]
The opt-out is no longer needed. The previous scheme was:

```rust
const fn a<T: /* inferred const bound */ Foo + /* opt-out normal trait bound */ ?const Bar>
```

And the current scheme is now:

```rust
const fn a<T: /* normal trait bound */ Foo + /* const bound if called in a const context */ ~const Bar>
```

This issue should be closed, but it can be reopened if somehow we decide to use `?const` opt-out again.

**Comment by oli-obk** [comment]
yea, const_trait_impl requires the opt in syntax, otherwise you can't write anything but trivial impls

**Comment by clarfonthey** [comment]
So... is there no dedicated tracking issue for `~const`, then?

Mostly because I don't see any easy place someone can look to know what the new syntax means.

**Comment by oli-obk** [comment]
I updated the const_trait_impl tracking issue to link to the latest RFC text
