### ISSUE TITLE
internal compiler error w/ dominator and wasm

### ISSUE THREAD

**Issue by dakom** [rust-lang/rust#67813]
I am using the [dominator](https://github.com/Pauan/rust-dominator) crate for wasm. There is very little documentation on the crate (it's early days) and so I accidentally used it the wrong way. Instead of getting the usual type of compiler errors, I got the following:

```
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: DistinctSources(DistinctSources { begin: (Macros("::dominator::macros::apply_methods"), BytePos(13989417)), end: (Macros("::dominator::macros::with_node"), BytePos(13989825)) })', src\libcore\result.rs:1165:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.40.0-nightly (c23a7aa77 2019-10-19) running on x86_64-pc-windows-msvc

note: compiler flags: -C debuginfo=2 -C incremental --crate-type cdylib

note: some of the compiler flags provided by cargo are hidden
```

The way I mistakenly tried to use it was like this:

```
fn get_dom_tree() -> Dom {
    html!("div", {
        .with_node!(element => {
            .new(element)
        })
    })
}
```

**Comment by jonas-schievink** [comment]
The actual error message is missing. Also, can you provide a self-contained repository that reproduces the ICE?

**Comment by dakom** [comment]
whups, edited just now to paste in the error message. will put together a repo now...

**Comment by dakom** [comment]
@jonas-schievink : https://github.com/dakom/rust-67813

**Comment by jonas-schievink** [comment]
Thanks, that helps! This looks like a duplicate of https://github.com/rust-lang/rust/issues/66805. I'll keep it open in case someone finds a minimal code example that reproduces the problem.

**Comment by Enselic** [comment]
Triage: I can't reproduce this, not even with an older nightly. Can anyone of you still reproduce?

**Comment by Enselic** [comment]
Triage: Closing as not reproducible.
