### ISSUE TITLE
Attributes are reordered before they are passed to a proc-macro

### ISSUE THREAD

**Issue by Luro02** [rust-lang/rust#67839]
I am working on a proc-macro, where I would like to give the user the option, to decide, which attributes (and doc comments) should be forwarded.

For example
```rust
use shorthand::ShortHand;

#[derive(ShortHand)]
#[shorthand(enable(forward(doc)))]
/// This should be in the output
#[shorthand(disable(forward(doc)))]
/// This line should not.
#[shorthand(enable(forward(doc)))]
/// This should be in the output
struct Example {
    value: String,
}
```

as you can see in the above case, the order of the attributes is very important.
Sadly the rust compiler (or the `proc_macro` crate) does reorder the attributes, before passing them to the function as a `TokenStream`.

```rust
#![feature(prelude_import)]
#[prelude_import]                                                               
use std::prelude::v1::*;                                                        
#[macro_use]                                                                    
extern crate std;                                                               
use shorthand::ShortHand;                                                       
/// This should be in the output
/// This line should not.                                                       
/// This should be in the output                                                
#[shorthand(enable(forward(doc)))]
#[shorthand(disable(forward(doc)))]                                             
#[shorthand(enable(forward(doc)))]
struct Example {
    value: String,
}
#[allow(dead_code)]
impl Example {
    #[inline(always)]
    pub fn value(&self) -> &String {
        &self.value
    }
    #[inline(always)]
    pub fn set_value(&mut self, value: String) -> &mut Self {
        self.value = value;
        self
    }
}
#[allow(dead_code)]
fn main() {}
#[main]
pub fn main() -> () {
    extern crate test;
    test::test_main_static(&[])
}
```
(this is the output of `cargo expand`, the proc-macro gets a similar `TokenStream`, where the order is not preserved either)

I think this should not happen and the order should be preserved! Are there any good reasons for reordering them?

related to #36211

**Comment by petrochenkov** [comment]
I agree that the relative order of inert attributes should be kept.
The reordering happens because built-in attributes (like doc comments) and non-builtin attributes are treated differently by macro expansion infrastructure.

I plan to fix this during the upcoming macro invocation collector rewrite (https://github.com/rust-lang/rust/issues/54727#issuecomment-523374617), unless someone gets to it earlier (this should be doable without rewriting the invocation collector entirely).

cc https://github.com/rust-lang/rust/issues/63221

**Comment by Luro02** [comment]
I think this change can wait, until the new macro system is implemented, becuse this would be a breaking change either way. (for example the code given above would have different output, if a macro relies on the current order of attributes)

**Comment by pksunkara** [comment]
Would this issue also include the proposal of ordering from https://github.com/rust-lang/reference/issues/565#issuecomment-485269684? If I currently write,

```rust
#[foo]
#[derive(Bar)]
```

As far as I observed: `foo` proc macro doesn't seem to get `derive` attribute because it looks like `derive` is expanded before it.

**Comment by petrochenkov** [comment]
Fixed in https://github.com/rust-lang/rust/pull/82419.

@pksunkara 
I think your case is different, but it was recently addressed by https://github.com/rust-lang/rust/pull/79078.

**Comment by pksunkara** [comment]
@petrochenkov Really appreciate your hard work in fixing both the issues. I have reworked some of my APIs to not run into this, but I am happy that I can now pick the best ergonomics for my proc-macro libraries instead of trying to navigate these issues.
