### ISSUE TITLE
Move unused_doc_comment lint to a later pass to after proc macro expansion

### ISSUE THREAD

**Issue by yaahc** [rust-lang/rust#67838]
I'm currently writing a crate where I'd like to use doc comments as attributes for a proc macro that generates context directives for errors and log messages via `tracing`.

https://github.com/yaahc/spandoc/blob/master/src/lib.rs

I had originally assumed that if my proc macro stripped out the doc attribute after converting it to a span then the compiler would not lint on the doc comments that actually got used as code, but when I tested this it still lints which implies to me that the unused doc comment lint happens in an earlier pass than proc-macro expansion does.

I'd like to be able to avoid using `#[allow(unused_doc_comments)]` on either the whole function or file because I want the lints to help me find doc comments that I add, expecting them to turn into spans, but which my proc macro does not handle and therefore leaves in as doc comments.

**Comment by yaahc** [comment]
@QuietMisdreavus has told me to cc @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
Could you provide a code sample alongside please?

**Comment by yaahc** [comment]
@GuillaumeGomez  here is a minimal example of spandoc in action https://github.com/yaahc/spandoc-example/blob/master/src/lib.rs

When I comment out the spandoc attribute and expand it you'll see that it generates a doc attribute

```
❯ cargo expand | grep doc
    Checking spandoc-example v0.1.0 (/home/jlusby/git/rust/spandoc-example)
warning: unused doc comment
 --> src/lib.rs:3:5
  |
3 |     /// Span in example
  |     ^^^^^^^^^^^^^^^^^^^
4 |     42
  |     -- rustdoc does not generate documentation for expressions
  |
  = note: `#[warn(unused_doc_comments)]` on by default
    Finished check [unoptimized + debuginfo] target(s) in 0.07s

    # [ doc = " Span in example" ] 42
```

and when I uncomment the spandoc attribute so that it transforms the doc attribute into a span you'll see that it does not have a doc attribute in the final output but it still produces the lint.

```
❯ cargo expand | grep doc
    Checking spandoc-example v0.1.0 (/home/jlusby/git/rust/spandoc-example)
warning: unused doc comment
 --> src/lib.rs:3:5
  |
3 |     /// Span in example
  |     ^^^^^^^^^^^^^^^^^^^
4 |     42
  |     -- rustdoc does not generate documentation for expressions
  |
  = note: `#[warn(unused_doc_comments)]` on by default
    Finished check [unoptimized + debuginfo] target(s) in 0.11s

                        "spandoc_example",
                        Some("spandoc_example"),
```
