### ISSUE TITLE
Incorrect span for errors caused by inferred type information

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#67843]
Given code that looks something like this:

```rust
fn main(){
    let sorted_headers = vec![(String::from("hello"), String::from("world"))];
    let signed_headers = sorted_headers.iter().map(|(k, _)| k.as_str()).collect();
    let canonical_request = ["GET", &signed_headers].join("\n");
}
```

([play rlo](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=12c7b5bb20d4c78209cef35efb006c32))

you will see an error along the lines of:

```
error[E0277]: a collection of type `str` cannot be built from an iterator over elements of type `&str`
 --> src/main.rs:4:59
  |
4 |     let canonical_request = ["GET", &signed_headers].join("\n");
  |                                                           ^^^^ a collection of type `str` cannot be built from `std::iter::Iterator<Item=&str>`
  |
  = help: the trait `std::iter::FromIterator<&str>` is not implemented for `str`
```

while the error is correct, the span here is wrong and should be pointing at the `collect` call for `signed_headers` instead.

To explain why, this is what effectively is happening here:

* `["GET": &str, &(signed_headers: ?)]: [&str]` causes `signed_headers` to be inferred to `str`.
* Therefore `sorted_headers.iter().map(|(k, _)| k.as_str()).collect(): str` which cannot be satisfied as there’s no `IntoIterator for str` implementation (hence the error).

**Comment by Aaron1011** [comment]
This appears to be fixed on the latest nightly.

**Comment by estebank** [comment]
Fixed on nightly in the past week.
