### ISSUE TITLE
doc(hidden) stopped working in binary crates

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust#67851]
https://github.com/rust-lang/cargo/pull/7593 seems relevant. cc @LukasKalbertodt @Eh2406 

If I have the following binary crate, `cargo doc` on stable 1.40.0 will correctly show `g` and not `f`, while beta will show both despite `f` being doc(hidden).

```rust
#[doc(hidden)]
pub fn f() {}
pub fn g() {}
fn main() {}
```

I understand that we want private things documented for bin crates, but I am labeling this a regression because this makes it impossible for macro-generated code to hide distracting implementation details that might overwhelm the actual useful API of the generated code.

I would like to suggest continuing to leave doc(hidden) items out of bin crate documentation as the default behavior of `cargo doc`.

**Comment by Eh2406** [comment]
Your suggestion seems entirely reasonable to me. I don't know what PR wuld need to go where to impl it.

**Comment by dtolnay** [comment]
@rust-lang/cargo @rust-lang/rustdoc, any tips for what PRs would need to go where?

**Comment by LukasKalbertodt** [comment]
Just for reference, the PR you linked (https://github.com/rust-lang/cargo/pull/7593) is not directly responsible for the buggy behavior. You can see the problem with 1.40 by `cargo doc --document-private-items` (which also documents `f`).

Could it be that we simply have to add a `STRIP_HIDDEN` pass here (and potentially some other arrays in that file)?

https://github.com/rust-lang/rust/blob/e845e691c988303ea54cb9de9639a8577b5a9d6b/src/librustdoc/passes/mod.rs#L89-L98

**Comment by jtmoon79** [comment]
Relates to https://github.com/rust-lang/rust/issues/66528
