### ISSUE TITLE
Feature request: cargo doc --deps-only

### ISSUE THREAD

**Issue by najamelan** [rust-lang/rust#67864]
One of the common scenarios for people working offline is getting documentation for dependencies while developing. An obvious moment of needing this is when the current crate is not compiling for some reason or another. Unfortunately when the current crate doesn't compile, cargo doc will refuse to build documentation leading to a bit of a chicken and egg problem.

Unfortunately as well the workaround is a bit tedious:
- cd into /home/user/.cargo/registry/.......
- run cargo doc on the crate
- don't forget to clean up the new target directory when done
- repeat every time you need docs for a dep or think of doing one when your crate compiles and don't `cargo clean`

I would propose to add an option `cargo doc --deps-only` which works without compiling the current crate.

I somewhat expected this to work by running `cargo doc --exclude current_crate`, but that seems to have a different purpose all together.

@GuillaumeGomez @QuietMisdreavus If this idea is acceptable, I wouldn't mind taking a stab at implementing if there is some mentoring to point me to the right places.

**Comment by GuillaumeGomez** [comment]
Not sure to see the point. Just run it on your crate and you'll have the dependencies' documentation. Also, this has to be implemented on cargo side.

**Comment by najamelan** [comment]
I'm sorry, my bad I guess I was thrown off by the non zero exit code, but the deps do appear in the target dir. Thanks for pointing that out. It doesn't give a single point of entry to browse all of them, but it's much less inconvenient than I thought.
