### ISSUE TITLE
Diagnostics for using &Vec after it was moved to a for-loop could be more accurate

### ISSUE THREAD

**Issue by Yura52** [rust-lang/rust#67876]
The code that causes a reasonable compilation error: [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=105a7b01222c6eabc4cad1ecd298fd2d)
The advice is to add "&", however, this leads to another error: [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=0374208d84328bf19d7ade958d3c134b)

I solved the problem by adding ".iter()". It would be nice to mention this in the compiler message, if it is possible.

**Comment by estebank** [comment]
Current output:

```
error[E0277]: `&&mut Vec<i32>` is not an iterator
 --> src/main.rs:2:14
  |
2 |     for x in &v {}
  |              ^^ `&&mut Vec<i32>` is not an iterator
  |
  = help: the trait `Iterator` is not implemented for `&&mut Vec<i32>`
  = note: required for `&&mut Vec<i32>` to implement `IntoIterator`
help: consider removing the leading `&`-reference
  |
2 -     for x in &v {}
2 +     for x in v {}
  |
```
Which then tells you the right thing to do here.
