### ISSUE TITLE
Builds for embedded powerpcle64 have no unmangled memset/memcpy/memmove

### ISSUE THREAD

**Issue by tomtor** [rust-lang/rust#67896]
See https://github.com/antonblanchard/microwatt/pull/125

I have to define my own memset/memcpy/memmove in the calling C-program:

https://github.com/tomtor/microwatt/blob/37bc1f31c2139ec06a56e51ed595e0bc664fdbc8/rust_lib_demo/hello_world.c#L172

This looks related to https://github.com/rust-lang/rust/issues/56814

**Comment by jonas-schievink** [comment]
We don't have any embedded (`#![no_std]`) PowerPC targets. You are building for `powerpc64le-unknown-linux-gnu`, which assumes that libc provides these functions.

**Comment by tomtor** [comment]
Adding `/usr/powerpc64le-linux-gnu/lib/libc.a`

gives

```
/usr/powerpc64le-linux-gnu/lib/libc.a(fileops.o): In function `_IO_new_file_underflow':
(.text+0x628): undefined reference to `_Unwind_Resume'
/usr/powerpc64le-linux-gnu/lib/libc.a(printf_fp.o): In function `__printf_fp_l':
(.text+0x650): undefined reference to `__unordkf2'
(.text+0x68c): undefined reference to `__unordkf2'
(.text+0xcf8): undefined reference to `__lekf2'
/usr/powerpc64le-linux-gnu/lib/libc.a(printf_fphex.o): In function `__printf_fphex':
(.text+0xf8): undefined reference to `__unordkf2'
(.text+0x144): undefined reference to `__unordkf2'
(.text+0x164): undefined reference to `__lekf2'
/usr/powerpc64le-linux-gnu/lib/libc.a(iofputs.o): In function `_IO_fputs':
(.text+0x204): undefined reference to `_Unwind_Resume'
/usr/powerpc64le-linux-gnu/lib/libc.a(iofwrite.o): In function `_IO_fwrite':
(.text+0x2f4): undefined reference to `_Unwind_Resume'
/usr/powerpc64le-linux-gnu/lib/libc.a(iogetdelim.o): In function `_IO_getdelim':
(.text+0x460): undefined reference to `_Unwind_Resume'
Makefile:34: recipe for target 'hello_world.elf' failed
```

**Comment by tomtor** [comment]
> We don't have any embedded (`#![no_std]`) PowerPC targets.

@jonas-schievink Indeed an official tier-2 embedded PowerPC target would be nice, but I would expect that a specific xargo configuration (I already use xargo for building a working soft-float library) would allow use of the current `powerpc64le-unknown-linux-gnu` target.

I fixed it now with this `Xargo.toml`:

```
[target.powerpc64le-unknown-linux-gnu.dependencies]

[dependencies.alloc]
features = ["compiler-builtins-mem"]
```
