### ISSUE TITLE
Inline immutable variable in layout -> llvm type conversion

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rust#67905]
https://github.com/rust-lang/rust/blob/bc1571cc3cfef07251f7df52b95525aa16797ca2/src/librustc_codegen_llvm/type_of.rs#L84-L89

@rustbot modify labels: +A-llvm +C-cleanup

**Comment by nagisa** [comment]
I can see why it was originally outlined – to document what this variable is. cc @eddyb

**Comment by bjorn3** [comment]
Maybe use `cx.type_struct(&[fill], false /*packed*/)` instead?
