### ISSUE TITLE
`cargo doc` not documenting some methods

### ISSUE THREAD

**Issue by anyusernameworks** [rust-lang/rust#67904]
[Here](https://github.com/anyusernameworks/paige) is my code where this issue happens.

As you can see in `src/element.rs`, I have documented the methods for struct `El`. However, when running `cargo doc` or publishing to docs.rs, those docs [are not included in the doc body despite the names being included in the "Methods" pane on the left](https://docs.rs/paige/0.1.0/paige/struct.El.html).

`rustc --version --verbose`:
```
rustc 1.39.0 (4560ea788 2019-11-04)
binary: rustc
commit-hash: 4560ea788cb760f0a34127156c78e2552949f734
commit-date: 2019-11-04
host: x86_64-unknown-linux-gnu
release: 1.39.0
LLVM version: 9.0
```

**Comment by GuillaumeGomez** [comment]
This is because there is a JS execution error. Fixing it.

**Comment by GuillaumeGomez** [comment]
The problem is coming from your code. You have HTML tags in it. Here's the diff to fix it:

```
git diff
diff --git a/src/element/mod.rs b/src/element/mod.rs
index 9485b13..24da473 100644
--- a/src/element/mod.rs
+++ b/src/element/mod.rs
@@ -22,7 +22,7 @@ impl El {
    
    /// Creates a new element that displays its name as text and nothing else
    /// when formatted. This is useful for making innerHTML something other
-   /// than a tag, such as inside the <style> or <script> tags.
+   /// than a tag, such as inside the `<style>` or `<script>` tags.
    pub fn text<N: Into<String>>(text: N) -> Self {
       El {
          is_text: true,
```
