### ISSUE TITLE
std::env::current_dir incorrect in symlink in WSL

### ISSUE THREAD

**Issue by chrisregnier** [rust-lang/rust#67916]
I'm currently using Ubuntu 18.04 in WSL and I ran into an unexpected result from `std::env::current_dir` when I run the program from within a symlinked folder. I think it's giving me the canonicalized path rather than the actual current directory.
```
~/projects/rust/cur_dir_bug$ wslsys
Release Install Date: 0x5d9399aa
Branch: rs5_release
Build: 17763
Full Build: 17763.1.amd64fre.rs5_release.180914-1434
Uptime: 10d 3h 48m
Linux Release: Ubuntu 18.04.3 LTS
Linux Kernel: Linux 4.4.0-17763-Microsoft
Packages Count: 760
```
I like to symlink my `/c/projects/` path to my home directory (`/home/cregnier/projects/`) for easy access, but when I run a program from within the linked path `std::env::current_dir()` returns the `/c/projects/...` path instead. I believe this is incorrect cause now I have no way of actually knowing what folder I'm in since I was trying to walk up the parent tree and expecting to hit the home directory.
I also tried a symlink to `/projects/` to make sure my problem wasn't due to the tilde, and this fails as well.

main.rs
```
fn main() {
    let pwd = std::process::Command::new("pwd")
        .output()
        .unwrap();
    println!("pwd: {:?}", pwd);
    let cur_dir = std::env::current_dir().unwrap();
    assert_eq!(cur_dir, std::path::Path::new("/home/cregnier/projects/rust/cur_dir_bug"));
}
```
```
~/projects/rust/cur_dir_bug$ pwd
/home/cregnier/projects/rust/cur_dir_bug
~/projects/rust/cur_dir_bug$ cargo run
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/cur_dir_bug`
pwd: Output { status: ExitStatus(ExitStatus(0)), stdout: "/c/projects/rust/cur_dir_bug\n", stderr: "" }
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `"/c/projects/rust/cur_dir_bug"`,
 right: `"/home/cregnier/projects/rust/cur_dir_bug"`', src/main.rs:8:2
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
```

Rust should be resolving the current directory as the normalized absolute path, but NOT resolving symlinks, so I suspect canonicalize is being run on things since I don't see another function to normalize without following symlinks.

Is there any other way of getting the ACTUAL current directory in the meantime (since it looks like I can't run `pwd` from within either)?

**Comment by nagisa** [comment]
`env::current_dir` pretty much directly calls `getcwd`. Please verify that `getcwd` is returning what you expect and fill a bug against WSL instead if it does not.

**Comment by chrisregnier** [comment]
Took me a bit to figure out how to do that, but it does look like calling `libc::getcwd` from rust gives back the canonicalized path. 
Looking into it more, I didn't realize `pwd` is a shell builtin different from `/bin/pwd` (which by default assumes the `-P` physical option and returns the canonicalized path rather than the current symlink path). Meanwhile `pwd --help` says it uses `-L` by default to show the logical path instead of the physical. `/bin/pwd -L` will give the correct result.  Very confusing!

So you're right, it doesn't look like a bug in rust, and I don't even think it's a WSL bug either :( . That leads me to wonder if there should be another api to get the logical path (equivalent of `/bin/pwd -L`) instead of the physical path through `getcwd` directly? Although I think that simply uses the env var $PWD so I can do that manually for now.  Thanks.
