### ISSUE TITLE
bad_style doesn't fire for associated types

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#67920]
Associated types are types and thus should be capitalized. I think most code also does this. Recently I accidentally didn't capitalize it and was surprised that it doesn't lint for it:

```Rust
pub trait Foo {
    type hello;
}
```

I'd expect it to say something.

This issue has been assigned to @Fibration via [this comment](https://github.com/rust-lang/rust/issues/67920#issuecomment-571159125).

**Comment by csmoe** [comment]
`bad_style` checking happens inside [src/librustc_lint/nonstandard_style.rs](https://github.com/rust-lang/rust/blob/33640f0e03af2fb31ce380d5389d5545f24ce29a/src/librustc_lint/nonstandard_style.rs#L124), add `check_trait_item` for `NonCamelCaseTypes`, inspect the kind of  [AssocitemKind](https://doc.rust-lang.org/nightly/nightly-rustc/syntax/ast/enum.AssocItemKind.html#variant.TyAlias) inside this checking.

**Comment by Fibration** [comment]
I'd like to put my hand up for this if that's alright? It looks like a good one to get started on.

@rustbot claim
