### ISSUE TITLE
Documentation should clarify what it means for PartialEq and Ord/PartialOrd to "agree"

### ISSUE THREAD

**Issue by dfoxfranke** [rust-lang/rust#67938]
It's obvious that if `a == b`, then `a.partialCmp(b) == Some(Ordering::Equal)`. But what about the converse? Can `==` implement a stricter sense of equality than `partialCmp` does? For example, suppose I have a type that wraps `Arc<String>`. Could I legally give it `Ord/PartialOrd` instances that compare the `String`s, while giving it `Eq/PartialEq` instances that call `ptr_eq` on the `Arc`?

**Comment by Dylan-DPC** [comment]
I feel the documentation specifies it well enough now. If anyone feels there it needs to be clearer, a newer issue might be a better idea than an issue that hasn't got a response for 4 years (minus 2 days :P )

**Comment by dfoxfranke** [comment]
I agree, this can be closed. It was addressed by #85637.
