### ISSUE TITLE
How to make fields displayed? (fields omitted)

### ISSUE THREAD

**Issue by D1mon** [rust-lang/rust#67968]
I want the fields to be displayed. I do not want to open [src] in layers to see the fields. There is no option in the settings for displaying structure fields. Add the ability to enable / disable structure fields.

**Comment by pietroalbini** [comment]
Transferred the issue to the rustc repo.

**Comment by jonas-schievink** [comment]
Private field and `#[doc(hidden)]` fields are hidden by the default rustfmt invocation. You can run `cargo doc --document-private-items` (which calls `rustdoc --document-private-items`) to show the non-`pub` fields.

**Comment by D1mon** [comment]
can you make private appear as an “lock” icon, and public fields as an “lock-open"? https://fontawesome.com/icons?d=gallery&q=lock
To display all fields in the online documentation, and not in the local documentation.
