### ISSUE TITLE
rustbuild cleans too much when building multiple architectures

### ISSUE THREAD

**Issue by infinity0** [rust-lang/rust#67973]
I'm trying to build libstd for wasm32-unknown-unknown and wasm32-wasi at the same time by running:

~~~~
./x.py --host x86_64-unknown-linux-gnu --target wasm32-unknown-unknown src/libstd
./x.py --host x86_64-unknown-linux-gnu --target wasm32-wasi src/libstd
~~~~

However the second call for some reason deletes the whole output of the first one, and I end up only with:

~~~~
$ ls -gG build/x86_64-unknown-linux-gnu/stage2-std
total 8
drwxr-xr-x  7 4096 Jan  7 13:43 release/
drwxr-xr-x  3 4096 Jan  7 13:43 wasm32-wasi/
~~~~

**Comment by Mark-Simulacrum** [comment]
You need to provide both targets to properly populate sysroots - I think the second build should be pretty much instant (i.e. we're just not copying artifacts into the sysroot).

I'm guessing we essentially won't fix this presuming I'm correct about the current behavior.

**Comment by infinity0** [comment]
Ah ok thanks, didn't realise I could pass `--target` twice, I'll try that. The thing is I'm also doing a regular build as well at the same time, i.e. `./x.py build` with no arguments. So what I would end up doing is `./x.py build && ./x.py build --target A --target B src/libstd`, this is supposed to work as expected?

**Comment by Mark-Simulacrum** [comment]
Ah, I think target twice might not work, but comma-separating should.

**Comment by Mark-Simulacrum** [comment]
Yes, that should work - the first build probably isn't necessary though (you can build arbitrarily many targets/hosts at the same time, I believe).

**Comment by infinity0** [comment]
Thanks, this seems to work fine yeah. I agree I think the first build is indeed unnecessary in most cases, I just do it this way on Debian since we arrange the builds to build platform-dependent (i.e. host compiler) and platform-independent (i.e. wasm libstds) stuff separately so that they can be enabled/disabled separately via a config setting, and I didn't want to mess around with conditional flag passing.
