### ISSUE TITLE
Default type parameter on struct ignored during inference

### ISSUE THREAD

**Issue by varkor** [rust-lang/rust#67993]
```rust
use std::marker::PhantomData;

pub struct S<T: Default = ()>(PhantomData<T>);

fn main() {
    let _ = S(PhantomData); // error: type annotations needed for `S<T>`
}
```
It seems clear that the default type parameter should be used here for `T`. I'm not sure if it should be considered a bug or not.

**Comment by cramertj** [comment]
Default type parameters are never used for inference today-- they're only ever used in places like impl headers where the type must be fully qualified but one or more parameters are omitted syntactically.

**Comment by varkor** [comment]
Closing as a duplicate of https://github.com/rust-lang/rust/issues/27336.
