### ISSUE TITLE
Typo on error E0369 description text

### ISSUE THREAD

**Issue by FSciammarella** [rust-lang/rust#68008]
Got this error message when trying to compile a crate using rustc 1.42.0-nightly (859764425 2020-01-07).

```
error[E0369]: cannot substract `systemstat::ByteSize` from `systemstat::ByteSize`
  --> /home/felipe-wsl/.cargo/registry/src/github.com-1ecc6299db9ec823/hegemon-0.1.0/src/providers/memory.rs:37:44         |
37 |                         Some((memory.total - memory.free).as_usize() as f64)
   |                               ------------ ^ ----------- systemstat::ByteSize
   |                               |
   |                               systemstat::ByteSize
   |
   = note: an implementation of `std::ops::Sub` might be missing for `systemstat::ByteSize`

```

The text reads substract instead of subtract.

**Comment by varkor** [comment]
@FSciammarella: if you want to contribute a fix, you would just need to modify these three lines:
https://github.com/rust-lang/rust/blob/ed6468da160bd67a2ce0573427f09a98daff8c07/src/librustc_typeck/check/op.rs#L333
https://github.com/rust-lang/rust/blob/ed6468da160bd67a2ce0573427f09a98daff8c07/src/test/ui/issues/issue-28837.rs#L8
https://github.com/rust-lang/rust/blob/ed6468da160bd67a2ce0573427f09a98daff8c07/src/test/ui/issues/issue-28837.stderr#L11

**Comment by FSciammarella** [comment]
@varkor thanks for your response, I submitted a PR #68023 to fix this.
