### ISSUE TITLE
Inline asm!() with "i" constraint produces the wrong assembly due to (now-fixed) LLVM bug

### ISSUE THREAD

**Issue by stevecheckoway** [rust-lang/rust#68021]
Nightly rustc correctly handles the first of these two inline assembly statements but silently does the wrong thing with the second one ([example on Compiler Explorer](https://godbolt.org/z/XKJDhL)).
```rust
#![feature(asm)]
static FOO: usize = 0;

pub unsafe fn example() {
    asm!("movq $0, %rax" :: "i"(&FOO) :: "volatile");
    asm!("mov rbx, $0" :: "i"(&FOO) :: "intel", "volatile");
}
```

The issue is LLVM's `call asm inteldialect` had a bug that was [fixed](https://reviews.llvm.org/D71436). I think the solution is to cherry-pick the LLVM fix.

You can see the problem directly using LLVM IR [here](https://godbolt.org/z/B8dvKw).

**Comment by Amanieu** [comment]
This issue does not apply to the new `asm!` ([RFC 2850](https://github.com/rust-lang/rfcs/pull/2850)) which uses `sym` operands. Note that `sym` operands only produce the raw symbol name, you are responsible for adding `offset` as needed.

The legacy `llvm_asm!` is deprecated and is no longer maintained.

**Comment by stevecheckoway** [comment]
Thanks. I'll take a look at the new `asm!`.

**Comment by Amanieu** [comment]
I believe we got the LLVM bug fix when we upgraded to LLVM 10.
