### ISSUE TITLE
./x.py -j1 not honored

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#68028]
I can observed `./x.py build -j1` launching 4 threads to build a crate instead of 1 as specified by `-j1` for example while building `proc_macro` while `Building stage0 std artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)`.

Perhaps this is related to https://github.com/rust-lang/cargo/issues/7689 ?

repo @ ed6468da160bd67a2ce0573427f09a98daff8c07

**Comment by Mark-Simulacrum** [comment]
Yeah, I'm going to close this as an upstream bug, there's no threading that we manage ourselves, everything is forked out to Cargo.

(And based on that it sounds like `cc` or so might actually be at fault here).
