### ISSUE TITLE
Russian text in comment kills compiler during compilation. 1.40

### ISSUE THREAD

**Issue by heretic13** [rust-lang/rust#68035]
Hello.
I create a very simple program.
[Cargo.toml.txt](https://github.com/rust-lang/rust/files/4037823/Cargo.toml.txt)
[main.rs.txt](https://github.com/rust-lang/rust/files/4037824/main.rs.txt)

Compilation kill compiler with panic
[err.txt](https://github.com/rust-lang/rust/files/4037837/err.txt)

This bug exists only if using russian characters in comment. English chars not provide error.
BOM UTF-8 or not - irrelevant.

**Comment by jonas-schievink** [comment]
This is already fixed on nightly
