### ISSUE TITLE
Better incrementors/decrementors

### ISSUE THREAD

**Issue by DeepRobin** [rust-lang/rust#68056]
In rust you can increment a mutable variable with 
```rust
let mut x = 0;
x = x + 1;
```

But it is easier to write 
```rust
let mut x = 0;
i++;
// or
i += 1;
```

**Comment by jonas-schievink** [comment]
Hi! Large additions to the language or standard library need to go through our [RFC process](https://github.com/rust-lang/rfcs). Before an RFC is written, the feature can also be discussed in our [internals forum](https://internals.rust-lang.org/) to find other people interested in it.

Closing in favor of an RFC.

**Comment by panstromek** [comment]
`x+=1;` is legal in rust btw. `++` and `--` were not added on purpose, as far as I know, because they have confusing semantics. There are number of forum threads about it.
