### ISSUE TITLE
const extern fn's dont need `fn` specifier

### ISSUE THREAD

**Issue by DutchGhost** [rust-lang/rust#68062]
The following program compiles, and prints `1`:
```Rust
#![feature(const_extern_fn)]

const extern "Rust" PUT_ANYTHING_YOU_WANT_HERE bug() -> usize { 1 }

fn main() {
    dbg!(bug());
}
```

**Comment by DutchGhost** [comment]
As pointed out by @Nemo157 on discord , this also works on stable:
```Rust
const unsafe WhereIsFerris Now() {}
```

**Comment by Centril** [comment]
Regression introduced in 1.40.0, specifically this line: https://github.com/rust-lang/rust/pull/64906/files#diff-af81683dfdae5890b2c6fa2d9b047f0aR163.

**Comment by Centril** [comment]
I have a fix in https://github.com/rust-lang/rust/pull/68073.
