### ISSUE TITLE
port / wrap / package psutil for rust

### ISSUE THREAD

**Issue by graydon** [rust-lang/rust#6808]
https://code.google.com/p/psutil/ is a very tidy collection of generic operating system and process monitoring interfaces, with supporting C code for all our tier-1 platforms. I would very much like to see this ported or exposed-and-wrapped in `std::os`.

**Comment by brson** [comment]
I think this is not suitable for in-tree. Somebody should build this in Cargo.

**Comment by nibrahim** [comment]
Can you elaborate a little? What do you mean by build this in cargo?
