### ISSUE TITLE
Method in a struct with a generic field should satisfy static

### ISSUE THREAD

**Issue by nrxus** [rust-lang/rust#68085]
Since methods never capture from the environment (unlike closures), they should satisfy the `'static` lifetime. However this does not hold for implementations of a struct with a generic parameter. 

If we had a struct like this:
```rust
struct Foo<T>(T);
```

The following two implementations work:
```rust
impl<'a> Foo<&'a i32> {
    fn a(&self) -> std::any::TypeId {
        Self::a.type_id()
    }
}
```

```rust
impl<'a> Foo<&'a mut i32> {
    fn b(&self) -> std::any::TypeId {
        Self::b.type_id()
    }
}
```

These makes sense because even though the field inside is not static, the method is still static. 

However, the following fails to compile:
```rust
impl<T> Foo<T> {
    fn c(&self) -> std::any::TypeId {
        Self::c.type_id()
    }
}
```

With the error:
```
   |
17 | impl<T> Foo<T> {
   |      - help: consider adding an explicit lifetime bound `T: 'static`...
18 |     fn c(&self) -> std::any::TypeId {
19 |         Self::c.type_id()
   |                 ^^^^^^^
   |
note: ...so that the type `for<'r> fn(&'r Foo<T>) -> std::any::TypeId {Foo::<T>::c}` will meet its required lifetime bounds
  --> src/main.rs:19:17
   |
19 |         Self::c.type_id()
   |                 ^^^^^^^
```

It is unclear to me why the latter fails to compile when the earlier two iterations worked even though the T was non-static type (a reference with a non-static lifetime). The method should be static even if it's struct is not, or is my understanding of static for function pointers incorrect? 

[Link to playgrund](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=5ac2a6d6544ad1a9f8bc0d0dd355ce38)

I apologize if this is not a bug and it works as intended, an explanation as to why would be greatly appreciated. I've tried to look for answers elsewhere (discord, discourse, google) to no avail.

**Comment by jonas-schievink** [comment]
This is expected behavior. There's nothing that tells the compiler that T will *always* have a static lifetime.

**Comment by nrxus** [comment]
In the first two examples, the `T` being used is a reference without a static lifetime, and yet I can get the `type_id` of the method just fine. How come if I replace T with a non-static reference, the method satisfied `static` but if I keep it as T, then it needs to be static?

**Comment by jonas-schievink** [comment]
Ah, sorry, I misread. I believe this is still working as expected though, since in the first cases the lifetime in the type gets turned into an HRTB, while in the last case that's not possible for `T`.

**Comment by nrxus** [comment]
Gotcha, that makes some sense, although I still find it confusing. It requires T to be 'static because it cannot use HRTBs for generics. But were it to be a non-static explicit reference instead then it is fine because the `type_id` is the same for all possible lifetimes since it uses HRTB. Thanks and sorry for the false issue report!
