### ISSUE TITLE
MIR optimization results in significantly increased compile time for a rustc-perf benchmark

### ISSUE THREAD

**Issue by ktrianta** [rust-lang/rust#68105]
In PR #66329 we created a MIR optimization pass that optimizes away unreachable basic blocks, i.e., basic blocks whose terminator kind is Unreachable.

Running on `rustc_perf`we observed improvement in all benchmarks except unicode-normalization (avg ~3%) and deeply-nested-opt (**avg: 740644.6%**). A more complete analysis of the compile times can be found [here](https://perf.rust-lang.org/compare.html?start=7bc1665730002a5368b4384613758c7ddc77db09&end=12076066783f508295c7fcc7bda9da738c11b437) and [here](https://github.com/rust-lang/rust/pull/66329#issuecomment-569025087). As explained by @bjorn3, for `deeply-nested-opt` the LLVM related queries are the ones slowing down, not anything inside rustc.

Until the root cause of the increase in compile times is found and fixed, we have made the optimization available only as a level 3 optimization.

**Comment by mati865** [comment]
Could be interesting to test this PR with https://github.com/rust-lang/rust/pull/67954 once it's more polished.
