### ISSUE TITLE
rustdoc: doc_cfg on trait impls needs more visibility

### ISSUE THREAD

**Issue by yaahc** [rust-lang/rust#68100]
I'm trying to annotate all the parts of a crate that are available based on feature flags and I've had the following experience when annotating a trait impl.

```rust
#[cfg(feature = "registry")]
#[cfg_attr(docsrs, doc(cfg(feature = "registry")))]
impl<'a, L, S> LookupSpan<'a> for Layered<L, S>
where
    S: Subscriber + LookupSpan<'a>,
{
    type Data = S::Data;

    fn span_data(&'a self, id: &span::Id) -> Option<Self::Data> {
        self.inner.span_data(id)
    }
}
```

This is what it looks like with the default visibility

![Screenshot from 2020-01-10 11-07-39](https://user-images.githubusercontent.com/1993852/72179528-f3b59d00-3399-11ea-9ed6-1e6d3456eb9e.png)

After expanding a single [+]

![Screenshot from 2020-01-10 11-07-48](https://user-images.githubusercontent.com/1993852/72179534-f6b08d80-3399-11ea-8d06-c01061e1c2fa.png)

Fully expanded

![Screenshot from 2020-01-10 11-08-00](https://user-images.githubusercontent.com/1993852/72179539-f912e780-3399-11ea-95aa-e88ab217a58c.png)

Ideally the default visibility with everything minimized should still indicate that this trait impl is dependent upon the given feature.

**Comment by WaffleLapkin** [comment]
(except I'm missing something) On the latest nightly the messages couldn't be seen at all

Cargo version
```console
% cargo --version
cargo 1.46.0-nightly (c26576f9a 2020-06-23)
```

The code:
```rust
#![cfg_attr(docsrs, feature(doc_cfg))]

pub struct SomeType;

pub trait SomeTrait {
    type SomeAssoc;

    fn some_method(&self);
}

#[cfg(feature = "some_feature")]
#[cfg_attr(docsrs, doc(cfg(feature = "some_feature")))]
impl SomeTrait for SomeType {
    type SomeAssoc = i32;

    fn some_method(&self) {}
}
```

The command:
```console
% RUSTDOCFLAGS="--cfg docsrs" cargo doc --features "some_feature" --open
```

The rendered documentation:
![image](https://user-images.githubusercontent.com/38225716/86044328-a4038480-ba52-11ea-9a27-568c85f73370.png)

Expanded:
![image](https://user-images.githubusercontent.com/38225716/86044391-b5e52780-ba52-11ea-8152-488c24e0d465.png)
