### ISSUE TITLE
Rust port of 'metrics' for libextra

### ISSUE THREAD

**Issue by graydon** [rust-lang/rust#6810]
A clone of the 'metrics' package would be useful for instrumentation. We have enough stuff we want to monitor that it'd be good to standardize the interface.

https://github.com/codahale/metrics
https://github.com/rcrowley/go-metrics

Currently I'm growing some ad-hoc pieces of this in `extra::stats`, the `std::test` benchmarking code, and the log-bin statistics counters in the new GC. Consolidating that and copying best practice structure (eg. properly separating collecting, aggregating and reporting) from the designs of other metrics libraries would be good.

Depends on #7458

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#843
