### ISSUE TITLE
Explanation for why future is not Send is wrong

### ISSUE THREAD

**Issue by tmandry** [rust-lang/rust#68112]
The following code ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=959b4d6882feffb32b66cbbcf6eea2ad)):

```rust
fn main() {
    let send_fut = async {
        let non_send_fut = make_non_send_future();
        let _ = non_send_fut.await;
        ready(0).await;
    };
    require_send(send_fut);
}
```

Gives an error message stating that `non_send_fut` can live until the end of the scope, and that's why `send_fut` is not `Send`:

```
error: future cannot be sent between threads safely
  --> src/main.rs:18:5
   |
6  | fn require_send(_: impl Send) {}
   |    ------------         ---- required by this bound in `require_send`
...
18 |     require_send(send_fut);
   |     ^^^^^^^^^^^^ future returned by `main` is not `Send`
   |
   = help: the trait `std::marker::Sync` is not implemented for `std::cell::RefCell<i32>`
note: future is not `Send` as this value is used across an await
  --> src/main.rs:16:9
   |
14 |         let non_send_fut = make_non_send_future();
   |             ------------ has type `impl core::future::future::Future`
15 |         let _ = non_send_fut.await;
16 |         ready(0).await;
   |         ^^^^^^^^^^^^^^ await occurs here, with `non_send_fut` maybe used later
17 |     };
   |     - `non_send_fut` is later dropped here
```

but it doesn't; it's consumed by value when it gets awaited. The problem is we're awaiting a non-`Send` future inside of `send_fut`, which has to be `Send`.

Also, the text
```
future returned by `main` is not `Send`
```
is wrong; `main` doesn't return anything.

Thanks to @kellerb for the reproducer and @JakeEhrlich for originally reporting this.

**Comment by tmandry** [comment]
> The problem is we're awaiting a non-`Send` future inside of `send_fut`, which has to be `Send`.

Some version of this is roughly the error message I'd want.

**Comment by nikomatsakis** [comment]
A few thoughts:

* I suspect that the code might be incorrectly identifying the `await` that should be highlighted

If you remove the second await, you get this error ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=d26c9c13c4b07aac3ae51440a37ffaae)):

**Comment by csmoe** [comment]
yes, live-across-yield analysis inside generator should be more precise, a test case from `src/test/ui`:
```rust

#![feature(optin_builtin_traits)]
// edition:2018
struct Foo;

impl !Send for Foo {}

fn is_send<T: Send>(t: T) { }

async fn bar() {
    let x = Foo;
    baz().await;
}

async fn baz() { }

fn main() {
    is_send(bar());
}
```
this snippet will compile if the non-Send `Foo`'s scope is [shorten](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=5ece0c5e80c6fc22ab130b815b16b4c7) with a block
