### ISSUE TITLE
Rust port of `criterion` for benchmarking

### ISSUE THREAD

**Issue by graydon** [rust-lang/rust#6812]
The built in unit tester presently contains some very crude one-off automated benchmarking stuff. It was initially a clone of the Go `testing.B` benchmark system (http://golang.org/pkg/testing/#B) but started to drift towards doing statistical measurement in order to get a more stable signal.

I believe Bryan O'Sullivan's `criterion` library (https://github.com/bos/criterion) is the state of the art here. We should port / emulate whatever it does well.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#651
