### ISSUE TITLE
Modify the calculation of timeout in TcpStream::connect_timeout

### ISSUE THREAD

**Issue by danclive** [rust-lang/rust#68168]
https://github.com/rust-lang/rust/blob/3ebcfa1451cfedc13a07e6353d8ade9742dfdc2a/src/libstd/sys/unix/net.rs#L143-L146

Because `TcpStream::connect_timeout` is implemented in the earlier version, `Duration.as_millis` is not yet stable. However, `Duration.as_millis` is already stable at v1.33, where the same calculation is made.

https://github.com/rust-lang/rust/blob/3ebcfa1451cfedc13a07e6353d8ade9742dfdc2a/src/libcore/time.rs#L338-L343

So this paragraph can directly `let mut timeout = timeout.as_millis() as u64;`.

**Comment by JohnTitor** [comment]
As discussed with @sfackler, `as` casting breaks current saturating behavior. So the suggested approach isn't correct.

**Comment by jonas-schievink** [comment]
Why not use `TryFrom` and `.unwrap_or(u64::max_value())`?

**Comment by JohnTitor** [comment]
Ah, yeah, it seems reasonable.

**Comment by danclive** [comment]
After reading the discussion on [this](https://github.com/rust-lang/rust/pull/68281), sorry, I really didn't notice the problem of saturating behavior.

However, for the `connect_timeout` API, let's take another look at the problem.

According to the Duration of the design:
https://github.com/rust-lang/rust/blob/ecbc222855c890c3aabe4848e8d8b312debcf0ff/src/libcore/time.rs#L53-L58

Our time can be said to `Duration: : the new (u64: : max_value (), 1 _000_000_000-1)`, which is `18446744073709551615.999999999s`.

```rust
let duration = std::time::Duration::new(u64::max_value(), 1_000_000_000-1);
println!("{:?}", duration); // 18446744073709551615.999999999s
```

How long is it? 

```rust
println!("{:?} years", u64::max_value() / 86400); // 213503982334601 years
```

However, even if you set up such a long time, we continue to look at the following code:

https://github.com/rust-lang/rust/blob/ecbc222855c890c3aabe4848e8d8b312debcf0ff/src/libstd/sys/unix/net.rs#L151

On the x86_64-unknown-linux-gnu platform, `c_int` is equivalent to `i32`. Here you are. It's also limited by the maximum value of `i32`.

There seems to be inconsistent behavior here, right? Maybe we should limit the upper limit in the first place, for example:

```rust
if timeout.as_secs() == 0 && timeout.subsec_nanos() == 0 {
    return Err(io::Error::new(
        io::ErrorKind::InvalidInput,
        "cannot set a 0 duration timeout",
    ));
}

if timeout.as_millis() > c_int::max_value() as u128{
    return Err(io::Error::new(
        io::ErrorKind::InvalidInput,
        "duration timeout overflow",
    ));
}
```

Maybe there's a better way.

Looking forward to your reply. Thanks. @JohnTitor @sfackler

**Comment by sfackler** [comment]
That code loops over poll until the actual timeout is reached at the top of the loop. The timeout value passed to poll may be shrunk to c_int::max_value() which just means that poll make wake up multiple times (once every ~24 days) if an extremely long timeout is passed.

**Comment by danclive** [comment]
Ok, I seemed to understand of the intention to do so, thank you. Although, 24 days is a long time, here it is.
