### ISSUE TITLE
Clarify tuple structs being functions?

### ISSUE THREAD

**Issue by DoumanAsh** [rust-lang/rust#68173]
Currently something like that would show you that Tuple struct is function

```rust
    let mut is_dealloc = false;
    pub struct MyDeleter<'a>(&'a mut bool);
    impl<'a> Drop for MyDeleter<'a> {
        fn drop(&mut self) {
            println!("drop");
            *(self.0) = true;
        }
    }

    let deleter: () = MyDeleter;
```

```
error[E0308]: mismatched types
  --> src/main.rs:15:23
   |
15 |     let deleter: () = MyDeleter;
   |                       ^^^^^^^^^ expected (), found fn item
   |
   = note: expected type `()`
              found type `fn(&mut bool) -> main::MyDeleter<'_> {main::MyDeleter::<'_>}`
```

This is kinda surprising, but understnadable.
Then, if you remove wrong type, it will just compile, while regular struct would fail
But I think this is not documented behaviour
In fact I actually expected it to fail, but I'm not sure if it is unintentional side effect of how tuples are implemented.

**Comment by xfix** [comment]
This is documented on https://doc.rust-lang.org/reference/expressions/struct-expr.html#tuple-struct-expression.

**Comment by DoumanAsh** [comment]
Oh, ok thanks
