### ISSUE TITLE
Calling unwind via function pointer leads to odd panic message

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#68178]
I was playing around with function pointers to `track_caller` methods (which [doesn't seem entirely implemented yet](https://github.com/rust-lang/rust/pull/65182#issuecomment-573649550)) and arrived at the following testcase:
```rust
fn call_it<T>(f: fn(T), x: T) {
    f(x);
}

fn main() {
    call_it(Result::unwrap, Err(0));
}
```
On stable, this behaves as expected:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: 0', src/libcore/result.rs:1165:5
```
On the latest nightly though, the message is different:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libstd/panicking.rs:369:15
```
The line number points at this:
https://github.com/rust-lang/rust/blob/af958046e5855a4254831102b502f57dafa40f69/src/libstd/panicking.rs#L369

Two things seem odd here for me:
* I am actually surprised that this does not ICE, given that the `ReifyShim` stuff does not seem entirely implemented (at least [this test](https://github.com/rust-lang/rust/pull/65182/commits/b8414c13abf9dc994f9c0dccee848a8b0fb1b061#diff-576c0bfe42a59f60c74b63e865d59d1d) still ICEs).
* But the actual main bug here is that the comment about "always returns Some" seems wrong, so this panics at the wrong place. Clearly, the message shouldn't talk about `Option::unwrap()` when the actual panic is caused by a `Result::unwrap`.

Cc @anp

**Comment by eddyb** [comment]
I thought `ReifyShim` was fully implemented, huh.

Looking at it LLVM IR for that example, it has this:
```llvm
declare void @_ZN4core6result13unwrap_failed17hdb3927d128569fa0E(
    [0 x i8]* noalias nonnull readonly align 1,
    i64,
    {}* nonnull align 1,
    [3 x i64]* noalias readonly align 8 dereferenceable(24),
) unnamed_addr #4
```

This is the same on nightly as on stable, and the `&panic::Location` seems to be missing (I'm guessing `[3 x i64]*` is the vtable pointer for the `&dyn fmt::Debug` argument).

(pretty sure you're seeing `Option::unwrap` failed because the `&panic::Location` is null so the `Some` is observed as a `None`)

I'm not sure if a proper location would be passed to `unwrap_failed` otherwise, but it certainly looks its declaration is mangled.

**Comment by eddyb** [comment]
(ignore previous comment if you saw it, `play.rust-lang.org`'s nightly is from the the wrong *decade*...)

**Comment by anp** [comment]
Here's a [repro of the underlying issue](https://www.irccloud.com/pastebin/sdXJVubn/repros.rs). We're missing logic in https://github.com/rust-lang/rust/blob/master/src/librustc/ty/instance.rs#L143-L145 to:

```
16:29 <eddyb> anp: it should be matching on `InstanceDef::Item(def_id)`, not use `.def_id()`
16:29 <eddyb> that is, `Item` is the only one where it's safe to return `true`
```

cc @eddyb

**Comment by anp** [comment]
Working on fleshing out this failing test case to include const fn's and will open a PR to resolve it.

**Comment by anp** [comment]
As for why the confusing error message: a `PanicInfo` is being created with `self.location` set to a null static reference, [`Some(null)`](https://github.com/rust-lang/rust/blob/master/src/libcore/panic.rs#L128) is `None`, and we get an unwrap failing where it shouldn't.

**Comment by anp** [comment]
Started https://github.com/rust-lang/rust/pull/68302, just failing tests for now.

**Comment by anp** [comment]
Have fixes for both bugs running through CI now.
