### ISSUE TITLE
after borrowing the scope, it not be returned

### ISSUE THREAD

**Issue by comradeHsu** [rust-lang/rust#68175]
struct Integer {
        val:i32,
        string:String
    }

    impl Integer {
        pub fn to_string(&self) -> String {
            return String::from_utf8(vec![self.val as u8]).unwrap();
        }
    }

    struct Long {
        val:i64
    }

    enum Number {
        Int(Integer),
        Lon(Long)
    }

    fn get_constant_info(this: &Vec<Number>, index:usize) -> &Number {
        let info = this.get(index);
        if info.is_none() {
            panic!("Invalid constant pool index!");
        }
        return info.unwrap();
    }

    pub fn get_utf8<'a>(this:Rc<Vec<Number>>,index:usize) -> &'a str {
        let info = get_constant_info(this.as_ref(),index);  ///---- `this` is borrowed here
        let utf8 = match info {
            Int(utf) => utf,
            _ => panic!("info is not NameAndType")
        };
        return utf8.string.as_str();
    }

    #[test]
    fn test() {
        let mut vec = Vec::new();
        vec.push(Int(Integer{ val: 0, string: "0".to_string() }));
        vec.push(Lon(Long{ val: 1 }));
        vec.push(Int(Integer{ val: 2, string: "2".to_string() }));
        vec.push(Lon(Long{ val: 3 }));
        vec.push(Int(Integer{ val: 4,string: "4".to_string() }));
        vec.push(Lon(Long{ val: 5 }));
        let rc = Rc::new(vec);
        let ss = get_utf8(rc,4);
        println!("{}",ss);
    }

**Comment by comradeHsu** [comment]
but if i using "dyn trait" replace to the enum "Number", this problem will not happen

**Comment by lidin** [comment]
The reason why you can't return a reference from `this` is because it is moved into the scope of the `get_utf8` function, so you are returning a reference of a local value, which is not allowed. One fix would be to put `this` behind a shared reference, the same way as in `get_constant_info` (which would also remove the need for an explicit lifetime), and the error disappears. Code is here (I got other errors than the one you described in the comment, so I followed the compiler's messages and remedied those as well):
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=589179da3f2cbf8b52febbc89064c8f5

**Comment by jonas-schievink** [comment]
Hi! This issue tracker is mainly meant for bug reports and concrete, small feature requests. Questions like this are better asked in the user forum at https://users.rust-lang.org/ or on [one of the chat platforms](https://www.rust-lang.org/community) used by the Rust community.

**Comment by comradeHsu** [comment]
> The reason why you can't return a reference from `this` is because it is moved into the scope of the `get_utf8` function, so you are returning a reference of a local value, which is not allowed. One fix would be to put `this` behind a shared reference, the same way as in `get_constant_info` (which would also remove the need for an explicit lifetime), and the error disappears. Code is here (I got other errors than the one you described in the comment, so I followed the compiler's messages and remedied those as well):
> https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=589179da3f2cbf8b52febbc89064c8f5

thinks your review,but what puzzled me was when I used "dyn trait"，there were no such mistakes， Code is here.
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&code=%20%20%20%20use%20std%3A%3Arc%3A%3ARc%3B%0D%0A%20%20%20%20use%20std%3A%3Amem%3B%0D%0A%0D%0A%20%20%20%20pub%20trait%20Num%20%7B%0D%0A%20%20%20%20%20%20%20%20fn%20num(%26self)%20-%3E%20i64%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20pub%20struct%20Integer%20%7B%0D%0A%20%20%20%20%20%20%20%20val%3Ai32%2C%0D%0A%20%20%20%20%20%20%20%20string%3AString%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20impl%20Integer%20%7B%0D%0A%20%20%20%20%20%20%20%20pub%20fn%20to_string(%26self)%20-%3E%20String%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20String%3A%3Afrom_utf8(vec!%5Bself.val%20as%20u8%5D).unwrap()%3B%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20impl%20Num%20for%20Integer%20%7B%0D%0A%20%20%20%20%20%20%20%20fn%20num(%26self)%20-%3E%20i64%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20self.val%20as%20i64%3B%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20pub%20struct%20Long%20%7B%0D%0A%20%20%20%20%20%20%20%20val%3Ai64%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20impl%20Num%20for%20Long%20%7B%0D%0A%20%20%20%20%20%20%20%20fn%20num(%26self)%20-%3E%20i64%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20self.val%3B%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%0D%0A%20%20%20%20pub%20fn%20get_constant_info_1(this%3A%20%26Vec%3CBox%3Cdyn%20Num%3E%3E%2C%20index%3Ausize)%20-%3E%20%26dyn%20Num%20%7B%0D%0A%20%20%20%20%20%20%20%20let%20info%20%3D%20this.get(index)%3B%0D%0A%20%20%20%20%20%20%20%20if%20info.is_none()%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20panic!(%22Invalid%20constant%20pool%20index!%22)%3B%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%20%20%20%20return%20info.unwrap().as_ref()%3B%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%20%20%20%20pub%20fn%20get_utf8_1%3C%27a%3E(this%3ARc%3CVec%3CBox%3Cdyn%20Num%3E%3E%3E%2Cindex%3Ausize)%20-%3E%20%26%27a%20str%20%7B%0D%0A%20%20%20%20%20%20%20%20let%20info%20%3D%20get_constant_info_1(this.as_ref()%2Cindex)%3B%0D%0A%20%20%20%20%20%20%20%20unsafe%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20let%20(data%2C%20_v_table)%20%3A%20(usize%2C%20usize)%20%3D%20%20mem%3A%3Atransmute(info)%3B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20let%20p%20%3D%20data%20as%20*%20const%20()%20as%20*%20const%20Integer%3B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20%26(*p).string.as_str()%3B%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%7D%0D%0A%0D%0A%0D%0A%0D%0A%20%20%20%20%23%5Btest%5D%0D%0A%20%20%20%20fn%20test_1()%20%7B%0D%0A%20%20%20%20%20%20%20%20let%20mut%20vec%3AVec%3CBox%3Cdyn%20Num%3E%3E%20%3D%20Vec%3A%3Anew()%3B%0D%0A%20%20%20%20%20%20%20%20vec.push(Box%3A%3Anew%20(Integer%7B%20val%3A%200%2C%20string%3A%20%220%22.to_string()%20%7D))%3B%0D%0A%20%20%20%20%20%20%20%20vec.push(Box%3A%3Anew(Long%7B%20val%3A%201%20%7D))%3B%0D%0A%20%20%20%20%20%20%20%20vec.push(Box%3A%3Anew(Integer%7B%20val%3A%202%2C%20string%3A%20%222%22.to_string()%20%7D))%3B%0D%0A%20%20%20%20%20%20%20%20vec.push(Box%3A%3Anew(Long%7B%20val%3A%203%20%7D))%3B%0D%0A%20%20%20%20%20%20%20%20vec.push(Box%3A%3Anew(Integer%7B%20val%3A%204%2Cstring%3A%20%224%22.to_string()%20%7D))%3B%0D%0A%20%20%20%20%20%20%20%20vec.push(Box%3A%3Anew(Long%7B%20val%3A%205%20%7D))%3B%0D%0A%20%20%20%20%20%20%20%20let%20rc%20%3D%20Rc%3A%3Anew(vec)%3B%0D%0A%20%20%20%20%20%20%20%20let%20ss%20%3D%20get_utf8_1(rc%2C4)%3B%0D%0A%20%20%20%20%20%20%20%20println!(%22%7B%7D%22%2Css)%3B%0D%0A%20%20%20%20%7D

**Comment by comradeHsu** [comment]
> Hi! This issue tracker is mainly meant for bug reports and concrete, small feature requests. Questions like this are better asked in the user forum at https://users.rust-lang.org/ or on [one of the chat platforms](https://www.rust-lang.org/community) used by the Rust community.

yes i see, but why the same code has different result in test and main function
