### ISSUE TITLE
Checkbox to hide unstable things?

### ISSUE THREAD

**Issue by gilescope** [rust-lang/rust#68184]
It would be great on the docs if there was a checkbox to hide nightly only methods in the generated documentation.
That gives us less methods to wade through to find the one we're after potentially, and may encourage people to pick stable methods by preference.

Apologies if this is the wrong repo for this request?

**Comment by pietroalbini** [comment]
Transferred.

**Comment by GuillaumeGomez** [comment]
I can already tell that I'm not in favor to add this feature into rustdoc directly: it adds more front-end code for a small gain.

**Comment by joshtriplett** [comment]
Not in the generated documentation pages (where it helps to know they exist), but perhaps in the search page. When doing a search, you might turn up many unstable methods, and it's good to know they exist, but then you might want to narrow to a method you can use and check that box. (It should always start out unchecked on each search, and just be something you can check to dynamically hide the unstable methods that the search turns up.)

**Comment by SimonSapin** [comment]
Rather than a dynamic choice left to users, would it make sense to have a static configuration for https://doc.rust-lang.org/stable/std/ v.s. https://doc.rust-lang.org/nightly/std/ ?

**Comment by dcarosone** [comment]
I like the idea that it is just a display filter / toggle, along the lines of other sections that can be expanded and collapsed.

The default state of the toggle could be different depending on whether I'm running `cargo doc` on a nightly or stable toolchain - and for the web cases immediately above.

There are also deprecated things that might be worth filtering similarly, for the "simple" view of "what can I use on stable now?"

**Comment by GuillaumeGomez** [comment]
@dcarosone This is more or less the case.

@SimonSapin Yes, I agree with you on this one.

**Comment by lzutao** [comment]
cc #59853

**Comment by detly** [comment]
I am currently wading through the documentation on [Box](https://doc.rust-lang.org/std/boxed/struct.Box.html) and almost **every** method is nightly-experimental. It is extremely hard to simply see the stable part of the API. I would love a way to switch this off and just focus on what I need.

(In other words, a checkbox to hide the blocks of nox would help the docs on Box not flummox.)

**Comment by evccyr** [comment]
It would be simpler to add badges to the search results to indicate whether a feature is nightly or not.

**Comment by dcarosone** [comment]
Whether you add a tag as content, or via an attribute for CSS to show badges for, is largely the same.
If added as an attribute, a CSS selector can then be used to hide the element. 

The *user experience* is *not at all the same* if they have to mentally filter out even-more-complex visual annotation, or can toggle whether these are hidden.

**Comment by WiktorPrzetacznik** [comment]
Some time has passed, are you still against this checkbox? I'd love to have this and even implement this (as another checkbox in the settings menu).
@GuillaumeGomez @joshtriplett

**Comment by GuillaumeGomez** [comment]
I'll put it up to discussion in next rustdoc team meeting.

**Comment by GuillaumeGomez** [comment]
It was discussed in the last [rustdoc team meeting on zulip](https://rust-lang.zulipchat.com/#narrow/stream/393423-t-rustdoc.2Fmeetings/topic/meeting.2012-02-2024/near/421117022) and we decided that it was not something that we wanted for rustdoc for the following reasons:
 * One benefit of showing the unstable APIs is that it invites people to test them, so having an opt-in for the curious would be good.
 * We want to avoid having too many settings. It's okay to see docs that are not relevant to you; almost all docs are irrelevant to almost all tasks.

Thanks for opening this issue in any case!
