### ISSUE TITLE
tests unoptimized with opt-level = 2

### ISSUE THREAD

**Issue by giarc3** [rust-lang/rust#68187]
With a Cargo.toml that contains
```
[profile.dev]
opt-level = 0

[profile.test]
opt-level = 2
```
running `cargo t --no-run --verbose` results in: 
```
Finished test [unoptimized + debuginfo] target(s) in 2m 44s
```
even though `opt-level = 2` is included in the rustc command. This shows that the build did use the `test` profile, but did not add optimization.

However, changing it to 
```
[profile.dev]
opt-level = 1

[profile.test]
opt-level = 2
```
and running `cargo t --no-run --verbose` results in: 
```
Finished test [optimized + debuginfo] target(s) in 6m 39s
```

This implies that test compilation uses optimization from `[profile.dev]` instead of `[profile.test]` as expected.

## Meta
`rustc --version --verbose`:
```
rustc 1.40.0 (73528e339 2019-12-16)
binary: rustc
commit-hash: 73528e339aae0f17a15ffa49a8ac608f50c6cf14
commit-date: 2019-12-16
host: x86_64-unknown-linux-gnu
release: 1.40.0
LLVM version: 9.0
```

**Comment by jonas-schievink** [comment]
`cargo test` builds the crate twice, once just like `cargo build` does, using the `dev` profile, and once using the `test` profile and passing `--test` to the compiler. Could it be that Cargo just prints what it used for the non-test compilation?

In any case, since this is a Cargo issue this should be filed over at https://github.com/rust-lang/cargo, not here

**Comment by giarc3** [comment]
From the speed of the tests, I think that I can confirm that it is indeed unoptimized when it prints out as such. 
I was unsure of where to open the issue, as I do see Cargo correctly passing `-C opt-level=2` and thought that that implied it was a rust issue.

**Comment by sfackler** [comment]
rustc doesn't print the `Finished test ...` line, cargo does. This issue should be filed over there.

**Comment by giarc3** [comment]
Issue moved to [rust-lang/cargo #7795](https://github.com/rust-lang/cargo/issues/7795) via [**ZenHub**](https://www.zenhub.com/)
