### ISSUE TITLE
`impl<T: Error> Error for Box<T>` means `Box<dyn Error>` does not implement `Error`

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#68185]
Currently the implementation of `Error for Box<T>` looks like this:

```rust
#[stable(feature = "box_error", since = "1.8.0")]
// note the missing `+ ?Sized` bound.
impl<T: Error> Error for Box<T> {
    fn description(&self) -> &str {
        Error::description(&**self)
    }

    #[allow(deprecated)]
    fn cause(&self) -> Option<&dyn Error> {
        Error::cause(&**self)
    }

    fn source(&self) -> Option<&(dyn Error + 'static)> {
        Error::source(&**self)
    }
}
```

which in turn disallows passing in dynamic `Error` objects around as easily as it should be possible to:

```rust
fn main() {
    let x: Box<dyn std::error::Error> = std::io::Error::last_os_error().into();
    fn assert_error<E: std::error::Error>(x: E) {}
    assert_error(x);
    //^~ error[E0277]: the size for values of type `dyn std::error::Error` cannot be known at compilation time
}
```

`Error` by definition of being object safe is implementable for `Box<T: ?Sized>`. We should relax that bound, especially now that `Box<dyn Error>` is becoming the way in the ecosystem to pass around the type-erased error values.

---

I discovered this after I attempted to use an implementation that looks like this:

```rust
impl<F: std::error::Error + Send + Sync + 'static> From<F> for SomeWrapper {
    fn from(f: F) -> Self {
        SomeWrapper(Box::new(f))
    }
}
```

You cannot add an implementation specialized for `Box<...>` either as that’s prevented by the coherence rules.

**Comment by nagisa** [comment]
I will submit a PR for this in a moment.

**Comment by nagisa** [comment]
Hmm, looks like this is is conflicting with

```rust
impl<'a, E: Error + 'a> From<E> for Box<dyn Error + 'a> {}
impl<'a, E: Error + Send + Sync + 'a> From<E> for Box<dyn Error + Send + Sync + 'a> {}
```

and we cannot remove those either :(

**Comment by Centril** [comment]
Seems like this is not actionable right now.

**Comment by nagisa** [comment]
I feel like this is a genuine and a fairly large usability wart, actionable or not. While it is true that the obvious implementation is not possible right now, remember that the standard library also has all the unstable rust under its disposal. Combined with that and perhaps editions if necessary this might become fixable.

**Comment by drozdziak1** [comment]
Is there any workarounds I can apply for this?
