### ISSUE TITLE
Confusing error message when expecting BoxFuture

### ISSUE THREAD

**Issue by tmandry** [rust-lang/rust#68197]
[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=2efde0a804c7661e987283896f013014)

```rust
fn foo() -> BoxFuture<'static, i32> {
    async {
        42
    }
}
```

gives

```
error[E0308]: mismatched types
 --> src/lib.rs:5:5
  |
4 |   fn foo() -> BoxFuture<'static, i32> {
  |               ----------------------- expected `std::pin::Pin<std::boxed::Box<(dyn core::future::future::Future<Output = i32> + std::marker::Send + 'static)>>` because of return type
5 | /     async {
6 | |         42
7 | |     }
  | |_____^ expected struct `std::pin::Pin`, found opaque type
  |
  = note: expected type `std::pin::Pin<std::boxed::Box<(dyn core::future::future::Future<Output = i32> + std::marker::Send + 'static)>>`
             found type `impl core::future::future::Future`
```

The `expected struct std::pin::Pin` in particular is confusing. This can be a pretty intimidating error message for someone new to async/await, when all they forgot was `.boxed()`.

I'm not sure if we can fix this without stabilizing `BoxFuture` so we can sprinkle some magic compiler dust on its error messages. Maybe there's something we can do, though. Maybe some intelligent use of type aliases in our error messages?

cc @JakeEhrlich

**Comment by estebank** [comment]
This can be handled without needing to stabilize the struct. It should act the same way that the primitive type cast suggestions do.

**Comment by nikomatsakis** [comment]
Some observations:

* There is no `BoxFuture` struct, it's a type-alias
* We could suggest invoking `boxed()` *but* that is a method defined only in the futures crate, which feels a bit awkward to me; I'd rather it were part of libstd
* We *can* suggest `Box::pin(async { .. })` as well ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=4e86316d17ad6d277cf9b3c55579a615))

**Comment by tmandry** [comment]
marking as OnDeck, since BoxFuture gets used quite often

**Comment by estebank** [comment]
I have a PR that suggests the right code for this:

<img width="1269" alt="Screen Shot 2020-02-11 at 5 09 37 PM" src="https://user-images.githubusercontent.com/1606434/74293975-5380ca00-4cf1-11ea-8f2f-76310d5204a1.png">

But if first you try `Box::new`:

<img width="1271" alt="Screen Shot 2020-02-11 at 5 10 12 PM" src="https://user-images.githubusercontent.com/1606434/74294099-bd996f00-4cf1-11ea-9e23-5b04f76ae99c.png">

or `Pin::new`:

<img width="1303" alt="Screen Shot 2020-02-11 at 5 11 11 PM" src="https://user-images.githubusercontent.com/1606434/74294060-98a4fc00-4cf1-11ea-8813-835c274fa5b2.png">

we will send you in a wild goose chase:

<img width="946" alt="Screen Shot 2020-02-11 at 5 10 53 PM" src="https://user-images.githubusercontent.com/1606434/74294089-b5d9ca80-4cf1-11ea-82d0-d9cf32cf6fb2.png">

**Comment by estebank** [comment]
Filed https://github.com/rust-lang/rust/issues/69083 for the uncovered cases.
