### ISSUE TITLE
Poor error/docs when attempting to constrain associated types in generic functions

### ISSUE THREAD

**Issue by nyanpasu64** [rust-lang/rust#68202]
Works:

```
use std::ops::Deref;
fn f<T: Deref<Target=i32>>(px: T) {
    let _x: i32 = *px;
}
```

My attempt at translating this to a logically equivalent statement fails:

```
use std::ops::Deref;
fn f<T: Deref>(px: T) where <T as Deref>::Target == i32 {
    let _x: i32 = *px;
}
```

Error:

```
   Compiling playground v0.0.1 (/playground)
error: equality constraints are not yet supported in where clauses (see #20041)
 --> src/lib.rs:2:29
  |
2 | fn f<T: Deref>(px: T) where <T as Deref>::Target == i32 {
  |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0308]: mismatched types
 --> src/lib.rs:3:19
  |
3 |     let _x: i32 = *px;
  |                   ^^^ expected i32, found associated type
  |
  = note: expected type `i32`
             found type `<T as std::ops::Deref>::Target`
  = note: consider constraining the associated type `<T as std::ops::Deref>::Target` to `i32`
  = note: for more information, visit https://doc.rust-lang.org/book/ch19-03-advanced-traits.html

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0308`.
error: could not compile `playground`.
```

I ran into this issue on a plane flight without internet, and was unable to discover this myself. I think I tried `Deref<Result=i32>` which failed to compile because it's called Target and not Result (oops). However, the error message for my alternative formulation was not helpful.

The reference to issue #20041 suggests the working way to write this code: https://github.com/rust-lang/rust/issues/20041#issuecomment-68645136 `fn foo<I>(it: I) where I: Iterator<Item=Foo> {}`. However I did not have functioning Internet on the plane flight, and was relying on the docs (which, like the rustc error message, appear to be unhelpful).

The URL points to the second edition of the book. While DDG searching for `associated type constraint`, I came across the first edition book, https://doc.rust-lang.org/1.30.0/book/first-edition/associated-types.html#trait-objects-with-associated-types , which explains this syntax. The equivalent in the second edition, https://doc.rust-lang.org/book/ch19-03-advanced-traits.html, is linked in the rustc error message. However it is unhelpful for this situation, since it is inexplicably missing instructions on how to constrain associated types as parameters (like a T implementing a specific `Deref`). It only mentions `<PlaceholderType=ConcreteType>` in the context of default values for *input* types in trait *declarations*, not *output* types in trait *usages*.

**Comment by estebank** [comment]
Current output:

```
error: equality constraints are not yet supported in `where` clauses
 --> src/lib.rs:2:30
  |
2 | fn f<T: Deref>(px: T) where  <T as Deref>::Target == i32 {
  |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^ not supported
  |
  = note: [see issue #20041 <https://github.com/rust-lang/rust/issues/20041>](https://github.com/rust-lang/rust/issues/20041) for more information
help: if `Target` is an associated type you're trying to set, use the associated type binding syntax
  |
2 | fn f<T: Deref>(px: T) where  T: Deref<Target = i32> {
  |                              ~~~~~~~~~~~~~~~~~~~~~~

error[[E0308]](https://doc.rust-lang.org/stable/error_codes/E0308.html): mismatched types
 --> src/lib.rs:3:19
  |
3 |     let _x: i32 = *px;
  |             ---   ^^^ expected `i32`, found associated type
  |             |
  |             expected due to this
  |
  = note:         expected type `i32`
          found associated type `<T as Deref>::Target`
help: consider constraining the associated type `<T as Deref>::Target` to `i32`
  |
2 | fn f<T: Deref<Target = i32>>(px: T) where  <T as Deref>::Target == i32 {
  |              ++++++++++++++
```
