### ISSUE TITLE
Make unsafe safer without limiting unsafe

### ISSUE THREAD

**Issue by realSmushyTaco** [rust-lang/rust#68239]
https://users.rust-lang.org/t/what-if-there-was-an-option-to-have-a-garbage-collector-for-unsafe-rust-code/36923?u=smushytaco

Read that whole discuss for all the details, a summary of idea is to have an always optional tracing garbage collector that can be used for unsafe blocks of code so you can make unsafe code safer without limiting unsafe. Rust is a language that revolves around safety so something like this would be a step in the right direction.

**Comment by steveklabnik** [comment]
Changes of this magnitude would require an RFC, and so I'm going to close this issue in favor of that. Thanks!

**Comment by realSmushyTaco** [comment]
https://github.com/rust-lang/rfcs/issues/2851 Alright moved it over there, thanks for the heads up!
