### ISSUE TITLE
Mutable references for mutable and immutable 

### ISSUE THREAD

**Issue by xky0007** [rust-lang/rust#68246]
According to the [Mutable References](https://doc.rust-lang.org/book/ch04-02-references-and-borrowing.html#mutable-references). The lifetime for immutable references is between its introduction and its first use.

**_Note that a reference’s scope starts from where it is introduced and continues through the last time that reference is used._**

And it gave the example:

```
let mut s = String::from("hello");

let r1 = &s; // no problem
let r2 = &s; // no problem
println!("{} and {}", r1, r2);
// r1 and r2 are no longer used after this point

let r3 = &mut s; // no problem
println!("{}", r3);
```

Because both r1 and r2 are used before declaring the r3, so it won't cause error. However, if I change the code to:

```
let mut s = String::from("hello");

let r1 = &s; // no problem
let r2 = &s; // no problem
println!("{}", r1);
// r1 is no longer used, but r2 is pending

let r3 = &mut s; // no problem
println!("{}", r3);
```
I can still run the code, did I make any misunderstanding about this part?

**Comment by Lonami** [comment]
> Continues through the last time that reference was used

In the second case, you last used `r2` in here:
```rust
let r2 = &s;
```

It's not "pending" (and also, nothing stops you from using `r1` again). As soon as you create `r3` though, you can no longer use `r1` or `r2`.

**Comment by xky0007** [comment]
> > Continues through the last time that reference was used
> 
> In the second case, you last "used" `r2` in here:
> 
> ```rust
> let r2 = &s;
> ```
> 
> It's not "pending" (and also, nothing stops you from using `r1` again). So it basically lives in that line (definition to last use, both being in the same line in this case).
> 
> As soon as you create `r3` though, you can no longer use `r1` or `r2`.

Thanks and that make sense.
