### ISSUE TITLE
Cannot use generic const argument without `{}`, despite no conflict

### ISSUE THREAD

**Issue by DrGabble** [rust-lang/rust#68257]
I would expect this code to compile, but it does not:

```rust
#![feature(const_generics)]

struct Foo<const A: usize, const B: usize> {
    a: [usize; A],
    b: [usize; B],
}

impl<const A: usize> Foo<A, 1> {
    fn get_b(&self) -> usize {
        self.b[0]
    }
}

impl<const B: usize> Foo<1, B> {
    fn get_a(&self) -> usize {
        self.a[0]
    }
}


fn main() {
    let foo = Foo { a: [0, 3], b: [0] };
    dbg!(foo.get_b());
}
```

([Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=00aba90934a80e43114bae17991b8caf))

Errors:

```
   Compiling playground v0.0.1 (/playground)
error: type arguments must be declared prior to const arguments
  --> src/main.rs:14:29
   |
14 | impl<const B: usize> Foo<1, B> {
   |                             ^

error: aborting due to previous error

error: could not compile `playground`.

To learn more, run the command again with --verbose.

```

**Comment by hellow554** [comment]
```rust
impl<const B: usize> Foo<1, {B}>
```

works

**Comment by DrGabble** [comment]
Thank you very much for your help! Apologies for troubling you, I'll maybe try stackoverflow first next time.

________________________________

**Comment by varkor** [comment]
I'm surprised this doesn't work, actually, as `B` shouldn't conflict with anything, so should be inferrable as a const. cc @yodaldevoid

**Comment by DrGabble** [comment]
Yeah it confused be how it could figure it out the other way, but not this way round...

**Comment by yodaldevoid** [comment]
Hmm, I'll try taking a poke at this this weekend.

**Comment by yodaldevoid** [comment]
Looks like the check for if consts are before types in argument lists happens before we do our fancy lowering magic that turns consts args that had been parsed as type args into their true selves. Why wasn't this caught earlier? We just didn't test it.

As for how to fix it? We could just remove parameter ordering or at least slightly relax it. Otherwise, we might have to just move this check later on after things have been lowered to HIR.

**Comment by varkor** [comment]
I don't think there's a strong reason for parameter ordering to be enforced and was mainly intended to be conservative. However, it is a small language change, so it might be easier to move this check later on for now.
