### ISSUE TITLE
Adding io::{Read, Write} traits in libcore?

### ISSUE THREAD

**Issue by gendx** [rust-lang/rust#68315]
Currently, libcore contains `core::fmt::Write` but (as far as I understand) nothing of the `std::io::` namespace.

However, `core::fmt::Write` is more constrained than `std::io::Write`, in that it only allows to write UTF-8 strings, as opposed to slices of bytes in general. It seems to me that `std::io::Write` as a trait doesn't require any specific OS support (contrary to `File`, `Stdout`, etc.), and as such would be useful in libcore and would integrate well there.

For an example where it would be useful in a `no_std` context, see https://github.com/tock/tock/issues/1449. In this case, one could essentially re-write the `io::Write` trait, but this seems quite redundant (and wouldn't inter-operate with crates that require a genuine `io::Write` in their API).

In general, it seems to me that `std::io::{Read, Write}`, as well as a other utilities such as `Cursor` or `BufReader` would have their place in libcore, to be able to use them in `no_std` contexts. Or is there any technical difficultly that I missed?

**Comment by jonas-schievink** [comment]
Yes, `io::Error` doesn't work without liballoc. This has been discussed in the past and while I'd *really* like to see this happen, a better place to discuss is this RFCs issue: https://github.com/rust-lang/rfcs/issues/2262
