### ISSUE TITLE
Incorrect/confusing error message on stable in very specific async code

### ISSUE THREAD

**Issue by syntacticsugarglider** [rust-lang/rust#68316]
The following code:
```Rust
struct Struct {
    data: Arc<Mutex<Fut>>,
}

pub fn spawn<F: Send>(future: F) {}

impl Struct {
    fn method(&self) {
        let data = self.data.clone();
        spawn(async move {
            (*data.lock().unwrap()).await;
        });
    }
}
```
fails to compile on stable 1.40 with `cycle detected when processing <impl at src/lib.rs...`

This error message is confusing, as the actual problem is that `spawn` takes a `Send` bound and the MutexGuard returned by `lock` is `!Send`. 

I attempted to reproduce this using any type other than Mutex, including a custom implementation with an identical API, but failed to do so. I then presumed it was an issue specifically related to negative trait implementations, so I switched to nightly to test this, and found that nightly presents a far more comprehensible error message: `Send is not implemented for std::sync::MutexGuard...`

Moreover, this also fails:
```Rust
impl Struct {
    fn method(&self) {
        let data: Arc<Mutex<Fut>> = panic!();
        spawn(async move {
            (*data.lock().unwrap()).await;
        });
    }
}
```
while this prints a sane error message:
```Rust
fn method(_: &Struct) {
    let data: Arc<Mutex<Fut>> = panic!();
    spawn(async move {
        (*data.lock().unwrap()).await;
    });
}
```
which I find quite bizarre.

As far as I can isolate this it appears to be an issue with negative trait implementations in some very specific scope types when the resultant type is a future and is awaited. I'm not sure why this is working in nightly but not fixed in stable and couldn't find a relevant issue regardless.

[playground reproduction](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=9a335ab2c13cfe95b308cf848e456320)

**Comment by jonas-schievink** [comment]
We close issues once they're fixed in nightly. We do sometimes backport fixes to beta if they hit a lot of users, but since this is already fixed on beta and nightly, closing.
