### ISSUE TITLE
rustdoc: run-button is scrolled together with code example

### ISSUE THREAD

**Issue by jfrimmel** [rust-lang/rust#68337]
Currently `rustdoc` emits HTML/CSS for the official Rust std documentation, that includes `Run`-buttons, as shown below (current nightly documentation of [`std::string::String`](https://doc.rust-lang.org/nightly/std/string/struct.String.html)):
![image, if the content is not scrolled](https://user-images.githubusercontent.com/31166235/72662363-8d0e3000-39e6-11ea-94ce-2ba7ad8cff54.png)
This works fine (although sometimes the Run-button might be above code), as long as the content of the code block is not scrollable horizontally.
If, on the other hand, the code block is scrollable horizontally, e.g. because the code shown has really long lines or the browser window is small, the Run button will be scrolled, too:
![image with non-scrolled content](https://user-images.githubusercontent.com/31166235/72662400-f8580200-39e6-11ea-9c58-dd34c0b4236c.png)
![image with scrolled content and Run-button](https://user-images.githubusercontent.com/31166235/72662406-06a61e00-39e7-11ea-824e-31ff3e367f6b.png)
I think the button is supposed to be in the top right hand corner and should stay there, even if the content is scrolled horizontally. I didn't notice similar behavior vertically as there is no "long enough" code example (which is good :smile:)

I think, that a little CSS and possibly a change in the generated HTML should do the trick.

**Comment by JohnTitor** [comment]
Currently, the button has `position: absolute`. When we change it to `sticky` and tweak the position and parent element, it should work fine, I think.
ref. https://developer.mozilla.org/en-US/docs/Web/CSS/position

**Comment by GuillaumeGomez** [comment]
@JohnTitor It doesn't work apparently. And there is a simpler solution: just move the element into the parent which doesn't scroll. :)
