### ISSUE TITLE
Allow Self<T> as a return type

### ISSUE THREAD

**Issue by Luro02** [rust-lang/rust#68344]
Currently this is not valid
```rust
struct Example<T> {}

impl<T> Example<T> {
    pub fn map<U, F: FnOnce(T) -> U>(self, f: F) -> Self<U> {
        unimplemented!();
    }
}
```

I think, that this would be a nice addition to language. I could not find anything on google about it, so I asked [here](https://users.rust-lang.org/t/rfc-or-tracking-issue-for-self-t/37092?u=luro02) if there is already an RFC/issue for it and this does not seem to be the case.

I would love to implement this feature :)

**Comment by crlf0710** [comment]
`Self` keyword stands for a type, so `Self<U>` doesn't make sense.
However
```rust
#![feature(generic_associated_types)]

struct Example<T> {}

impl<T> Example<T> {
    type O<X> = Example<X>;
    
    pub fn map<U, F: FnOnce(T) -> U>(self, f: F) -> Self::O<U> {
        unimplemented!();
    }
}
```
might get supported, since it's a reasonable addition.

**Comment by Luro02** [comment]
I think it does make sense, when you think of `Self` as a type alias
```rust
type Self = Example<T>;
```

You should also look at this post by @Phlopsi
https://users.rust-lang.org/t/rfc-or-tracking-issue-for-self-t/37092/4?u=luro02

**Comment by Centril** [comment]
I think this is essentially asking for [higher kinded types](https://en.wikipedia.org/wiki/Kind_(type_theory)), which is not something that is readily implementable, and is not on the agenda right now. While we might consider that after `generic_associated_types` has baked, this is not something we want to consider right now.
