### ISSUE TITLE
An Suggestion: maybe keyword "unsafe" is not a good term

### ISSUE THREAD

**Issue by dbsxdbsx** [rust-lang/rust#68359]
Rust gives we programmers strong safety, but also gives us freedom to write some code maybe unsafe with keyword "unsafe".  But as should be known to all programmers,   it doesn't mean the code be tagged as "unsafe" is exactly unsafe, as long as we know what we are doing (no undefined behavior).  

For example (maybe crazy), about the classic panic issue--- giving  a value to a vector with index that is out of range.    Does it should be recognized as unsafe **all the time**?  Generally, yes , it is unsafe.   But what if as a reverse engineering,  I know exactly what the data in heap is, and for some purpose, I want to give a value exactly behind the "safe" bound of the vector?

Here, what I want to point out is that I agree with what Rust team think about what Rust should be. But following the road,  I think  maybe  the keyword "unsafe" is **too subjective**, maybe a word more objective is better ,like say "caution".   Though in my own style , I would prefer "!", but to follow Rust philosophy,  a more complex word may be better to  caution us and try best to avoid it.

Ok, I have to admit that the reason for this suggestion is due to the recent "Actix"  issue, I don't want to someone who would be pissed off **by just not quite knowing about  the keyword "unsafe" ,but not exactly unsafety.**

**Comment by jonas-schievink** [comment]
Hi! Changes to the language need to go through our [RFC process](https://github.com/rust-lang/rfcs). Before an RFC is written, the feature can also be discussed in our [internals forum](https://internals.rust-lang.org/) to find other people interested in it.

Closing in favor of an RFC.

**Comment by dbsxdbsx** [comment]
@jonas-schievink ，thanks.
