### ISSUE TITLE
`x.py install` fails for a nonexistent prefix

### ISSUE THREAD

**Issue by kai-alpha** [rust-lang/rust#68369]
#49778 introduced `fs::canonicalize()` which [fails for a nonexistent path](https://doc.rust-lang.org/std/fs/fn.canonicalize.html#errors)

This is a surprise for someone used to GNU Autotools' configure which can create any necessary intermediate directories in `prefix`

**Comment by Mark-Simulacrum** [comment]
Can we do a create_dir_all before canonicalizing perhaps? Not sure if that's correct behavior though.

Generally speaking we're happy to take PRs adjusting these things incrementally as needed, so feel free to file a PR; we're unlikely to fix it ourselves though.

**Comment by kai-alpha** [comment]
Hi @pietroalbini
