### ISSUE TITLE
Consider extending `unused_parens` to `{}`, particularly in const generics

### ISSUE THREAD

**Issue by varkor** [rust-lang/rust#68387]
In const generics, `{}` are required for complex expressions in const generic arguments (e.g. `{M + N}`). They are not required, however, for literals and standalone parameters (in most cases). However, at least at the moment, it is quite common to see curly brackets in user code for all generic arguments. This may be a passing phase, as generic arguments [only recently](https://github.com/rust-lang/rust/pull/66104) started being disambiguated; however, if it is not, we might want to lint on extraneous `{}` to inform users.

This might be useful outside of const generis too, such as in:
```rust
let _ = (5); // lints about unnecessary parens
let _ = {5}; // does not lint
```

**Comment by eddyb** [comment]
I think it makes sense to lint any leaf expressions wrapped in braces.
