### ISSUE TITLE
`PatternError::StaticInPattern` seems to be dead code

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#68395]
https://doc.rust-lang.org/nightly/nightly-rustc/rustc_mir_build/hair/pattern/struct.PatCtxt.html#method.report_inlining_errors never hits `PatternError::StaticInPattern` in practice it seems. We should check if it is actually unreachable.

cc @oli-obk

**Comment by JohnTitor** [comment]
Just checked that the removal doesn't affect any existing tests inside of this repo.

The relevant part:
https://github.com/rust-lang/rust/blob/d568d63b1f9f5fc47e4202e2a2a84142ff6202d8/compiler/rustc_mir_build/src/thir/pattern/mod.rs#L471-L475

The change will remove a pattern error if `is_associated_const` is false. But given we know `DefKind` is const or assoc const, it shouldn't be a problem?
@oli-obk Is that correct?

**Comment by oli-obk** [comment]
yes, we could still use the StaticInPattern error by adding an arm in https://github.com/rust-lang/rust/blob/d568d63b1f9f5fc47e4202e2a2a84142ff6202d8/compiler/rustc_mir_build/src/thir/pattern/mod.rs#L425, which should then hopefully affect tests and improve diagnostics
