### ISSUE TITLE
Move `rustc_passes::liveness` to MIR

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#68419]
Discussion in https://discordapp.com/channels/442252698964721669/443151243398086667/669220265821077535.

The liveness linting code in `rustc_passes::liveness` works on HIR using backwards dataflow. The code is quite complicated and imprecise. Moving it to `rustc_mir::transform` as a new pass could simplify the compiler, improve maintainability, as well as improve precision (e.g., sub-binding level precision for tuples, structs, and arrays).

cc @oli-obk cc @eddyb cc https://github.com/rust-lang/rust/issues/65467 cc https://github.com/rust-lang/rust/issues/51003

**Comment by eddyb** [comment]
Isn't this a duplicate of #51003? cc @nikomatsakis @pnkfelix

**Comment by nikomatsakis** [comment]
I believe it is, closing as duplicate of #51003.
