### ISSUE TITLE
Allow public functions in traits

### ISSUE THREAD

**Issue by asevans48** [rust-lang/rust#68426]
In the spirit of writing better more concise code, it would be nice to be able to implement public functions from traits.

Rust version: 1.40 Stable / 1.42 nightly

Expectation:

Can use traits without writing helper functions

Actual:

Trait functions cannot be marked as public either in the trait or the implementation.

**Comment by jonas-schievink** [comment]
Trait functions are always public, they're "imported" along with the trait.
