### ISSUE TITLE
Improve generic arg–param mismatch errors

### ISSUE THREAD

**Issue by varkor** [rust-lang/rust#68437]
The current diagnostics are a little ad hoc and rely on counting the number of mismatches (e.g. they will only produce an error for the first mismatch). It would be nice to produce diagnostics like:
```
missing generic arguments for `T`, `const N: usize`, `U`
```

cc @eddyb

This issue has been assigned to @rakshith-ravi via [this comment](https://github.com/rust-lang/rust/issues/68437#issuecomment-626317244).

**Comment by varkor** [comment]
This is follow up work for https://github.com/rust-lang/rust/pull/68434.

**Comment by contrun** [comment]
Please give more context on this. I am not sure the error message of which test should be improved.

**Comment by eddyb** [comment]
@contrun This is more of the kind of issue opened to avoid forgetting about finishing some work, sorry for the confusion.

That is, this is @varkor leaving a TODO to themselves about improving the diagnostics from #68434.

**Comment by contrun** [comment]
Ok. I see. Thanks for the explanation.

**Comment by eddyb** [comment]
That said, if @varkor is too busy to work on this, you could talk to them on Discord or Zulip to see what their plans were to turn this into a mentored issue.

**Comment by varkor** [comment]
The idea is essentially this. We currently emit errors telling the user that the generic arguments they provide are in the wrong order: https://github.com/rust-lang/rust/pull/68434/files#diff-5df0144261224cec2047029de05fa827R107
However, what we'd like to do is suggest reordering the parameters, and let rustfix automatically apply the suggestion.

I don't have the bandwidth to work on this at the moment, or any time soon, so if anyone is interested in tackling it, I'll be happy to mentor the issue.

**Comment by rakshith-ravi** [comment]
@varkor would you mind if I take this up?

**Comment by varkor** [comment]
@rakshith-ravi: you're very welcome to! Let me know if you need any guidance in tackling this issue!
