### ISSUE TITLE
`char::is_ascii_digit()` is slower than `char::is_digit(10)`

### ISSUE THREAD

**Issue by ThomasdenH** [rust-lang/rust#68453]
Using the method `is_ascii_digit` on a char is about 17% slower than using `is_digit(10)`. I wouldn't expect there to be a difference, of if there was, I would expect the former to be faster. Could this be improved or are the two not actually equivalent?

**Comment by ThomasdenH** [comment]
I just saw #67143, which I think fixes this.

**Comment by blankname** [comment]
Might want to re-open this as #67143 has been closed.

**Comment by ThomasdenH** [comment]
Alright.

**Comment by LeSeulArtichaut** [comment]
This seems like a duplicate of #65127, which has been fixed by #67585
