### ISSUE TITLE
rustdoc appears to fail with no-std `extern crate alloc` but succeeds

### ISSUE THREAD

**Issue by HeroicKatora** [rust-lang/rust#68486]
When using `rustdoc` in a `no_std` crate that links to `alloc` then an error message of missing a global allocator appears even though the tests actually finish successfully. Note that one can still use `std` in the doctests of such a crate regardless of the attributes.

```rust
//! ```
//! Vec::<usize>::new();
//! ```
#![no_std]
extern crate alloc;
```

```bash
> cargo test --doc
   Compiling no-alloc v0.1.0 (/tmp/no-std-alloc)
    Finished test [unoptimized + debuginfo] target(s) in 0.05s
   Doc-tests no-std-alloc
error: no global memory allocator found but one is required; link to std or add `#[global_allocator]` to a static item that implements the GlobalAlloc trait.

error: aborting due to previous error

running 1 test
test src/lib.rs -  (line 1) ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
> echo $?
0
```

It should either finish with an error status or not print any error messages.

**Comment by Nemo157** [comment]
Duplicate of #54010, which was supposedly closed 3 days ago, does this still reproduce on the latest nightly?

**Comment by HeroicKatora** [comment]
It did not seem like a duplicate at first as the crate itself does *not* link against `std` in the example above, and since the `doctest` portion was never updated in the title or top-level post. It's a duplicate based on reading further in the thread.
