### ISSUE TITLE
Thread Id is not unique for runtime loaded libraries (libloading)

### ISSUE THREAD

**Issue by Visic** [rust-lang/rust#68513]
Threads in a library loaded at runtime share thread id's with each other.  At a minimum this is causing a bug in crossbeam's channels, since they use a thread id comparison at one point expecting them to be unique.

Minimum reproducible example: https://github.com/Visic/Thread-Id-Bug
Crossbeam issue: https://github.com/crossbeam-rs/crossbeam/issues/424
Crossbeam bug demonstration: https://github.com/Visic/crossbeam-dll-test

**Comment by DoumanAsh** [comment]
this is probably consequence of it originating from static counter https://github.com/rust-lang/rust/blob/4f074dea1dbf28d7519bf408b7530e8cba019243/src/libstd/thread/mod.rs#L1058

**Comment by jonas-schievink** [comment]
This is not a supported configuration of Rust's standard library. It expects to be present only once per process. The right way to use it multiple times is to export a cdylib and use an FFI layer.

**Comment by Visic** [comment]
@jonas-schievink Thank you for the information! Would dynamically linking the stdlib work?

**Comment by jonas-schievink** [comment]
That's what you're doing already. It generally is only guaranteed to work when not passing Rust objects across the library boundary. `BTreeMap` has similar behavior where it will break when you have 2 copied of libstd and pass it between them.

**Comment by DoumanAsh** [comment]
I don't think Rust exactly specifies behaviour of static variables in such case, but I suspect it is likely to be similar to C++.
I.e. as long as variable is internally linked, it is not going to be shared between each process that loads dll, therefore each program that links to std would have own instance of id generator

**Comment by Visic** [comment]
> 
> 
> That's what you're doing already. It generally is only guaranteed to work when not passing Rust objects across the library boundary. `BTreeMap` has similar behavior where it will break when you have 2 copied of libstd and pass it between them.

I might be misunderstanding, but specifically I am referring to changing the library from a "cdylib" to "dylib" and compiling everything with -C prefer-dynamic, thereby forcing everything to link dynamically to the stdlib. In testing, it did seem to fix this particular issue. Please correct me if I am wrong in thinking that is a valid fix.

Also, I am curious what you mean about the BTreeMap, do you know of any documentation that talks about it not working across library boundaries?
