### ISSUE TITLE
libntdll.a is not shipped within rust-mingw

### ISSUE THREAD

**Issue by Shadlock0133** [rust-lang/rust#68518]
When compiling cargo under `stable-x86_64-pc-windows-gnu`, it fails at linking with missing ntdll. After posting [issue](https://github.com/rust-lang/cargo/issues/7812) at cargo repo, @mati865 pointed out libntdll.a isn't shipped with rust-mingw component (it's missing [here](https://github.com/rust-lang/rust/blob/73f76b74efcaf21bd5424d87c66cd6ed7fe5c7de/src/bootstrap/dist.rs#L244-L288)).

**Comment by jonas-schievink** [comment]
Seems to be an easy fix according to @mati865:

> open PR which adds that library to this list: https://github.com/rust-lang/rust/blob/73f76b74efcaf21bd5424d87c66cd6ed7fe5c7de/src/bootstrap/dist.rs#L244-L288

**Comment by petrochenkov** [comment]
Closing as wontfix (https://github.com/rust-lang/rust/pull/68519#issuecomment-578601575).
