### ISSUE TITLE
x.py --verbose displays wrong commands

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#68510]
When running ` ./x.py check --verbose`, x.py says

running: "/home/matthias/vcs/github/rust/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "/home/matthias/vcs/github/rust/build/x86_64-unknown-linux-gnu/stage0/bin/cargo" "check" "-Zconfig-profile" "--target" "x86_64-unknown-linux-g...

You can see that it's saying it is running `cargo cargo check ...` which obviously does not work.
One of the cargo paths seems to be wrongly inserted into the print.

**Comment by Mark-Simulacrum** [comment]
This is a rust libstd bug (should be fixed in beta, but we haven't bumped bootstrap compiler). Closing.

It will fix itself in a week or so when we bump to the next version of Rust.
