### ISSUE TITLE
Installation Documentation Suggestion

### ISSUE THREAD

**Issue by zermat** [rust-lang/rust#68547]
In "The Rust Programing Language" Section 1.1 Installing rustup on Linux or macOS it would be nice to have a paragraph at the beginning saying that: "Rust will install in the ~/.cargo and ~/.rustup directories, and that if desired, during installation, you can change where Rust is installed."

I don't tend to install anything on my computer unless I know where it is being installed, as a number of programs make either stupid or arrogant assumptions as to where they think they should be installed.  Rust is nice, in that the installation locations actually make sense.

I assume a similar statement could be made for people installing on Windows.

Additionally, altho this is a moving target, a ballpark indication of size (disk space) would be nice.

**Comment by jonas-schievink** [comment]
The book's contents are hosted at https://github.com/rust-lang/book, so please file this over there (or send a PR)
