### ISSUE TITLE
Are there plans to make rust simpler?

### ISSUE THREAD

**Issue by italomaia-bk** [rust-lang/rust#68569]
Maybe create something like rustscript or something? Learning rust seems quite challenging.

**Comment by jonas-schievink** [comment]
Hi! This issue tracker is mainly meant for bug reports and concrete, small feature requests. Questions like this are better asked in the user forum at https://users.rust-lang.org/ or on [one of the chat platforms](https://www.rust-lang.org/community) used by the Rust community.
