### ISSUE TITLE
`Rvalue::Repeat` should hold a `ty::Const`

### ISSUE THREAD

**Issue by varkor** [rust-lang/rust#68567]
```rust
fn test<const N: usize>() {
    let array = [0; N];
}
```
currently fails with `error: array lengths can't depend on generic parameters`, because we can't tell what concrete value `N` should take here. This is an artificial limitation: when producing a `Rvalue::Repeat`, we currently need to provide the length of the array, which is impossible at this stage.
cc https://github.com/rust-lang/rust/issues/43408#issuecomment-578526551

**Comment by eddyb** [comment]
cc @oli-obk @yodaldevoid
