### ISSUE TITLE
Suggestion: no-op set_permissions for WASI

### ISSUE THREAD

**Issue by RReverser** [rust-lang/rust#68560]
Currently, WASI target implements retrieving permissions with a no-op and just returning a default value:

https://github.com/rust-lang/rust/blob/a237641c7df8125b89b8f9c2a3594964ba8188f8/src/libstd/sys/wasi/fs.rs#L75-L78

However, the corresponding setter method is instead implemented by returning an error:

https://github.com/rust-lang/rust/blob/a237641c7df8125b89b8f9c2a3594964ba8188f8/src/libstd/sys/wasi/fs.rs#L424-L428

This is unfortunate and breaks higher-level APIs like `std::fs::copy` which currently manages to successfully copy contents of file on a WASI target but then fails because the default implementation unconditionally calls `set_permissions`:

https://github.com/rust-lang/rust/blob/d8bdb3fdcbd88eb16e1a6669236122c41ed2aed3/src/libstd/sys_common/fs.rs#L19-L21

To both fix such issues and from a semantic point of view, too, it seems it would be better to mirror the behaviour of the getter (`permissions` method) and just perform no-op in `set_permissions` on a WASI target, at least until WASI specification decides to extend support and add real permissions model.

Would the team be open to this?

**Comment by RReverser** [comment]
Ping @alexcrichton @fitzgen?

**Comment by alexcrichton** [comment]
I would personally prefer to ensure that wasi-libc for C stays in sync with Rust's libstd, so I think that this is probably best a question for the wasi group as opposed to Rust's libstd specifically.

**Comment by RReverser** [comment]
I see; WASI SDK conditionally excludes `chmod` for WASI target during compilation, and I suppose that's what Rust wants to avoid and instead simulates with a runtime error. Fair enough.

In that case, would you be open to adding a specific implementation of `std::fs::copy` for WASI target that just uses `std::io::copy` but doesn't set permissions? There is no direct analogue for it in the wasi-libc anyway, and it would solve this specific API function without changing the rest.
