### ISSUE TITLE
Compiler panic evaluating complex associated types

### ISSUE THREAD

**Issue by svenknobloch** [rust-lang/rust#68578]
Compiler panic evaluating complex associated types meant to [emulate generic associated types](http://lukaskalbertodt.github.io/2018/08/03/solving-the-generalized-streaming-iterator-problem-without-gats.html).

[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=69b21f8d609b6c3a57b939e241e289dd)

**Comment by Aaron1011** [comment]
This looks like another case of https://github.com/rust-lang/rust/issues/62529

**Comment by pnkfelix** [comment]
triage: Closing as duplicate (or at least "instance") of #62529
