### ISSUE TITLE
Expose WASI symlink helper

### ISSUE THREAD

**Issue by RReverser** [rust-lang/rust#68574]
Currently, Unix and Windows expose `std::os::unix::symlink` and `std::os::windows::fs::symlink_file` correspondingly, which both simply accept source and destination by `Path`.

However, the currently exposed WASI method - `std::os::wasi::fs::symlink` is lower-level and requires user to have a file descriptor of the preopened directory in addition to the file paths:

https://github.com/rust-lang/rust/blob/8a79d08fa57e1c257d647c9848e35defcb379c07/src/libstd/sys/wasi/ext/fs.rs#L397-L405

This is different from all other `fs` methods and not ideal, because it requires calling even more lower-level methods to find and retrieve that preopened directory by file path first, and libpreopen isn't exposed to users, so they have to do this all manually.

Moreover, the codebase already contains a higher-level helper for symlinking files by path and hiding these syscall details, it's just not currently exposed to users:

https://github.com/rust-lang/rust/blob/a605441e049f0b6d5f7715b94b8ac4662fd7fcf6/src/libstd/sys/wasi/fs.rs#L538-L541

If this is not too late in terms of backwards compatibility, it would be better to remove the currently exposed low-level syscall and expose this helper instead, so that users could work on paths more easily like they do on other platforms.

Alternatively, it's necessary to at least expose helpers for retrieving the preopen directory from a file path, as otherwise it's not possible to construct symlinks from userland without invoking raw syscalls.

**Comment by RReverser** [comment]
I'm sorry, but since it's been half a year... friendly ping? @alexcrichton do you think we can expose that symlink helper?

**Comment by alexcrichton** [comment]
I'm not really sure what this is proposing myself, so I'm not sure? What is a "symlink helper"?

**Comment by RReverser** [comment]
The second function referenced above - basically a way to create a symlink with just source and dest paths, like you can on other platforms with `std::os::unix::fs::symlink` or `std::os::windows::symlink_file`.

Right now the exposed WASI variant of that function requires not only paths, but also knowing a file descriptor of the preopened dir, making it impossible to use from safe code (since preopened dirs are managed internally by WASI libc).

**Comment by alexcrichton** [comment]
I would personally think that a better option would be to expose `open_parent` in one way or another for wasi since that seems more appropriate for a `sys`-module-functionality.

**Comment by RReverser** [comment]
I totally agree it makes sense for `sys` module in general, but it seems to be more of an implementation detail in this case.

The `std::os::(somename)::fs` often provide OS-specific extensions to regular `fs` methods, not necessarily low-level ones. Symlink, in particular, seems like something that should work as straightforward as, say, `File::open`, `std::fs::copy` or any other universal APIs.

That is, I think all those OS-specific implementations should still follow the deprecated universal API from older Rust times - [`std::fs::soft_link`](https://doc.rust-lang.org/std/fs/fn.soft_link.html) - with same ease of use, just under different namespaces.

**Comment by alexcrichton** [comment]
I'm not exactly the gatekeeper of the wasm module or anything, I'm basically just saying that I would not personally pursue adding this method to the standard library. If you'd like to do so you can certainly do that, however.

**Comment by RReverser** [comment]
I've mostly asked you because you authored that helper function that I'd love to see exposed.

I think it's useful for ease of use and consistency with other platforms. I'm happy to make a PR myself if it would be accepted.

**Comment by RReverser** [comment]
Looks like people are already misusing the currently exposed API for symlinks - since there is no way to use it right :( https://github.com/vitiral/path_abs/pull/50#issuecomment-770120481

**Comment by RReverser** [comment]
Given above, finally got back to this and made a PR to fix it: https://github.com/rust-lang/rust/pull/81542
