### ISSUE TITLE
JavaScript `TypeError: synthetic_implementors is null` error on some trait pages

### ISSUE THREAD

**Issue by ollie27** [rust-lang/rust#68584]
For example on the nightly docs https://doc.rust-lang.org/nightly/std/iter/trait.Iterator.html:

```
TypeError: synthetic_implementors is null main1.42.0.js:1:34607
    register_implementors https://doc.rust-lang.org/nightly/main1.42.0.js:1
    <anonymous> https://doc.rust-lang.org/nightly/main1.42.0.js:1
    <anonymous> https://doc.rust-lang.org/nightly/main1.42.0.js:7
ReferenceError: addSearchOptions is not defined search-index1.42.0.js:7:1
    <anonymous> https://doc.rust-lang.org/nightly/search-index1.42.0.js:7
```

Additionally most of the documentation doesn't load (but not every time):

![image](https://user-images.githubusercontent.com/7189418/73214429-11308800-414a-11ea-9e08-ae30685a6470.png)

I suspect this was caused by #68192 (cc @GuillaumeGomez).

**Comment by GuillaumeGomez** [comment]
Very likely. I'll check how to fix it.
