### ISSUE TITLE
Compiler crashes when resuming compilation

### ISSUE THREAD

**Issue by aristarh2704** [rust-lang/rust#68602]
Sometimes when compiling some packages after stopping the previous build, the compiler crashes with a memory allocation error:
`memory allocation of 1006632960 bytes failedSegmentation fault`

**Comment by Mark-Simulacrum** [comment]
Is this on today's nightly? If so, probably https://github.com/rust-lang/cargo/issues/7840...

If not, can you provide the version of Cargo and rustc (`cargo --version`, `rustc -vV`).
