### ISSUE TITLE
Memory leakage while compiling `imgui-ext` on nightly

### ISSUE THREAD

**Issue by tombuchholz** [rust-lang/rust#68600]
Trying _cargo build_  inside of https://github.com/germangb/imgui-ext using

toolchain: _nightly-x86_64-unknown-linux-gnu_
version: _rustc 1.4.2.0-nightly_
distribution: _arch linux_
kernel: _5.4.15-arch1-1_

does eat up memory (>28GB) until OS kills it.
**On stable toolchain compiling works as expected.**

## Meta
`rustc --version --verbose`:
  rustc 1.42.0-nightly (8a79d08fa 2020-01-27)
  binary: rustc
  commit-hash: 8a79d08fa57e1c257d647c9848e35defcb379c07
  commit-date: 2020-01-27
  host: x86_64-unknown-linux-gnu
  release: 1.42.0-nightly
  LLVM version: 9.0

**Comment by matthiaskrgr** [comment]
I get the same compiling backtrace-sys.

**Comment by matthiaskrgr** [comment]
`perf top` shows high cpu utilization by ` cargo::util::progress::State::tick` and it is actually cargo that consumes all the memory.
This is probably https://github.com/rust-lang/cargo/issues/7840

**Comment by jonas-schievink** [comment]
Oh yeah this is just the Cargo thing.
