### ISSUE TITLE
AtomicF{32,64}

### ISSUE THREAD

**Issue by dvc94ch** [rust-lang/rust#68614]
I was a bit surprised when I didn't find an `AtomicF64` in the std. While performing arithmetic might not be possible, I think that `load` and `store` should work. The specific use case I have is sharing the volume with the audio thread, for which `load` and `store` would be sufficient.

**Comment by Mark-Simulacrum** [comment]
I would probably be mildly against this, as converting to AtomicU64 (i.e., via `to_bits`/`from_bits`) should not be too hard, and in practice I suspect that treating floats as "just bits" (which is what the atomics would have to do) may not be what users expect.

**Comment by dvc94ch** [comment]
I'm not sure if that's the case on all architectures? It seems to hold for x86 and arm.

- [0] https://lists.llvm.org/pipermail/llvm-dev/2014-May/073160.html

**Comment by Mark-Simulacrum** [comment]
I'm not sure I follow -- are you suggesting that we can do something other than wrapping an AtomicU64 in a unit struct AtomicF64 which passes all arguments through into_bits and returns after mapping via from_bits? My understanding was that there are no atomic operations on floating point, which seemed reflected in your initial comment as well, but maybe I misinterpreted?

**Comment by dvc94ch** [comment]
ok so llvm doesn't currently have any extrinsics for `f32`, `f64`. it looks like `to_bits / from_bits` is the only solution. I guess we can close the issue then? Most people will just think oh, there's no `AtomicF{32,64}`, I'll wrap it in a `Mutex`. That's what I did and `rodio` does the same.

**Comment by Mark-Simulacrum** [comment]
Yes, I think that's the thing to do. There may be room in the ecosystem for a crate that has AtomicF32/64, though.

**Comment by Venryx** [comment]
For others looking for a short implementation of the approach mentioned above (of using `AtomicU64` along with `to_bits` and `from_bits`), here is the helper struct I'm using:
```rust
pub struct AtomicF64 {
    storage: AtomicU64,
}
impl AtomicF64 {
    pub fn new(value: f64) -> Self {
        let as_u64 = value.to_bits();
        Self { storage: AtomicU64::new(as_u64) }
    }
    pub fn store(&self, value: f64, ordering: Ordering) {
        let as_u64 = value.to_bits();
        self.storage.store(as_u64, ordering)
    }
    pub fn load(&self, ordering: Ordering) -> f64 {
        let as_u64 = self.storage.load(ordering);
        f64::from_bits(as_u64)
    }
}
```
