### ISSUE TITLE
`todo!()` macro doesn't work with existential return types

### ISSUE THREAD

**Issue by a-rodin** [rust-lang/rust#68610]
I expect the following code to compile:

```rust
fn func<T>() -> impl Iterator<Item = T>
{
    todo!()
}

fn main() {}
```

However, it doesn't compile ([playground link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=673f6237b286ec1d36b00e15c03ed61e)) with the following error:

```
error[E0277]: `()` is not an iterator
```

The reasoning to expect it to work is that I could have put, for example, `vec![].into_iter()` instead of `todo!()`, and it would work.

Note that existential types for traits which don't have type parameters don't have this problem:

```rust
fn func() -> impl Ord
{
    todo!()
}

fn main() {}
```

compiles without issues.

**Comment by sfackler** [comment]
The presence of type parameters isn't related to the code compiling or not. The type of `todo!()` resolves to `()` in this case, which does implement `Ord`, but does not implement `Iterator`.

**Comment by Centril** [comment]
(And if/when the fallback changes to `!` it will still not work for the same reason.)

Closing with @sfackler's explanation. I also think there are other issues regarding `impl Trait` and `!` already.

**Comment by vi** [comment]
How are users supposed to define unimplemented `impl Trait` or async functions without actually thinking about how to actually obtain some value that satisfies the trait (which is sometimes equivalent to actually implementing the function instead of leaving it unimplemented)?

**Comment by jmesmon** [comment]
I've worked around this locally (when writing API skeletons) for myself by writing things like `todo_iter!()` and `todo_stream!()`. Here are the macros I've used:

```
macro_rules! todo_iter {
    () => {{
        todo!();
        #[allow(unreachable_code)]
        [].into_iter()
    }};
}

macro_rules! todo_stream {
    () => {{
        todo!();
        struct F<T>(PhantomData<T>);
        impl<T> Stream for F<T> {
            type Item = T;
            fn poll_next(self: Pin<&mut Self>, _cx: &mut Context<'_>) -> Poll<Option<Self::Item>> {
                Poll::Pending
            }
        }

        #[allow(unreachable_code)]
        F(PhantomData)
    }};
}
```

(there might be a less wordy `todo_stream!()` using `futures-util` and `into_stream()`, the above was written as a direct approach just using `futures-core`).
