### ISSUE TITLE
Values with short-lived lifetimes allowed in matches when a branch returns ptr::null

### ISSUE THREAD

**Issue by worr** [rust-lang/rust#68657]
Howdy! I had an issue with some (admittedly poor) code that seemed to behave differently in release and debug builds.

Here is a short repro of the offending code: https://play.rust-lang.org/?version=stable&mode=release&edition=2018&gist=744b3dd0e3a8171675a1f2969c370915

In a debug build, this code will work as expected. In a release build, this code will sleep for an uncertain amount of time (or more likely be killed by the playground).

If both arms of the match return a `&timespec`, the issue becomes clear, and the compiler catches it correctly: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=b788f0170f6d876aae8fc856d562b34f

It looks like the `timespec` in my example doesn't live long enough, and so may be freed (or even optimized out) in a release build.

Thanks so much!

**Comment by ecstatic-morse** [comment]
This code is UB. `foo` has type `*const timespec`. You create a pointer to a temporary and store it in `foo`, then that temporary goes out of scope at the end of the match arm, invalidating the pointer.

I suppose this is a good example of how implicit conversion from `&T` to `*const T` combined with type inference can have surprising results. Perhaps we could warn when we see code like `let p: *const T = &{ unpromotable expr}`?

**Comment by eatnumber1** [comment]
Is there any case where the production of a temporary from a match arm is correct behavior? Why not just make that case a well-defined compile error?

**Comment by ecstatic-morse** [comment]
Yes. It's correct in almost all cases. `*const T` has no special semantics as far as the borrow checker is concerned. That case is treated the same as if the match arm evaluated to an integer literal.

**Comment by worr** [comment]
@ecstatic-morse Thanks for the explanation, I see how this was my fault now.

Personally, I'd appreciate a warning like that, but that seems like it'd be needlessly noisy in cases where that promotion is intentional. I'll close this issue since it was very much a problem on my end.

Thanks again!
