### ISSUE TITLE
rust/RELEASES.md doesn't list the Box<T> FFI change for 1.41.0

### ISSUE THREAD

**Issue by lilyball** [rust-lang/rust#68676]
The [announcement post](https://blog.rust-lang.org/2020/01/30/Rust-1.41.0.html) for Rust 1.41.0 talks about `Box<T>` now being ABI-compatible with C's `T*` type, but I can't find any mention of that in the [detailed release notes](https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1410-2020-01-30).

**Comment by jonas-schievink** [comment]
The relevant PR is https://github.com/rust-lang/rust/pull/62514 if someone wants to fix this.
