### ISSUE TITLE
ICE with const enum method returning Self

### ISSUE THREAD

**Issue by dylni** [rust-lang/rust#68684]
This code causes an ICE starting from Rust 1.41.0 (stable, beta, and nightly):

```rust
enum Enum {
    A(),
}

impl Enum {
    const fn a() -> Self {
        return Self::A();
    }
}

pub fn main() {
    const A: Enum = Enum::a();
}
```

Error:

```
error: internal compiler error: src/librustc_typeck/check/mod.rs:995: can't type-check body of DefId(0:5 ~ main[2fbc]::Enum[0]::A[0]::{{constructor}}[0])
 --> main.rs:2:5
  |
2 |     A(),
  |     ^^^
```

No extra flags were added. It also happens in release mode.

```
rustc main.rs
```

Rust Playground is at version 1.40.0 and doesn't have the error on stable:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=6683265b3123c0a6835431de2f0c6897

**Comment by Centril** [comment]
Another version:

```rust
enum _Enum {
    A(),
}

type _E = _Enum;

const fn _a() -> _Enum {
    _E::A() // Changing to `_Enum::A()` makes it compile.
}

const _A: _Enum = _a();

fn main() {}

```

**Comment by Centril** [comment]
cc @oli-obk @matthewjasper

**Comment by JohnTitor** [comment]
Bisected: https://github.com/rust-lang/rust/commit/2539b5f157599fbcc005371a34897a42fa0a2421, #66294

**Comment by matthewjasper** [comment]
This should be checking `tcx.has_typeck_tables(def_id)` before calling `typeck_tables_of`:
https://github.com/rust-lang/rust/blob/64184a3288eca13ddfb7bc2e7b5231cbb8d5b88f/src/librustc_mir/const_eval/eval_queries.rs#L292

**Comment by pnkfelix** [comment]
triage: P-high. Removing nomination. Assigning to self.
