### ISSUE TITLE
terminfo testing

### ISSUE THREAD

**Issue by cmr** [rust-lang/rust#6870]
extra::terminfo testing needs to be more thorough and especially we need to distribute some terminfo entries in src/test and verify that all the expected capabilities are there and their correct values.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/term#12
