### ISSUE TITLE
Rust Test Global State Bug

### ISSUE THREAD

**Issue by seriousbusinessuser** [rust-lang/rust#68706]
This is odd one, I can reproduce it only in test environment so it might be related to Rust test system(I also created separate [issue](https://github.com/chronotope/chrono/issues/391) in `chrono` project but not sure yet where this issue belongs to):

Some global state introduces random into  local `offset()`.
Normally with `TZ=Europe/Moscow` `Local.ymd(2000, 10, 29).and_hms(2, 0, 0)` has `+04:00` offset but when it's called within test context with *unused* `bug` variable it sometimes returns `+03:00` offset. 

It's easy to reproduce, create empty project, add `chrono` as depenedncy and create following test file:
```rust
use chrono::{ Local, TimeZone };

#[test]
fn t1() { test_bug(); }

#[test]
fn t2() { test_bug(); }

#[test]
fn t3() { test_bug(); }

#[test]
fn t4() { test_bug(); }

fn test_bug() {
    // If you remove this line then bug goes away.
    let bug = Local.ymd(2000, 11, 29).and_hms(2, 0, 0);

    let expected_time = Local.ymd(2000, 10, 29).and_hms(2, 0, 0);

    assert_eq!(expected_time.offset().to_string(), "+04:00");
}
```

And run it using following:
```bash
for n in {1..100}; do TZ=Europe/Moscow cargo test ; done
```

Expected:
Unused variable `bug` shouldn't affect anything.

Actual:
When `bug` variable is present random tests are failing. 

Setup:
- rustc 1.42.0-nightly (212b2c7da 2020-01-30) 
- rustc 1.42.0-nightly (859764425 2020-01-07)
- chrono 0.4.10

**Comment by jonas-schievink** [comment]
Chrono may call OS functions internally to do the conversion. It is likely that chrono is causing this, not the Rust test runner, so closing in favor of the other bug. If you think this is wrong, please provide an example and I'll reopen.
