### ISSUE TITLE
Setting of member of const struct should not be possible

### ISSUE THREAD

**Issue by gwierzchowski** [rust-lang/rust#68713]
In below listing the assignment line I think should not compile with error like "invalid left-hand side expression" - as it would be in case variable was not a struct.
PS: Moving const definition to the function body does not change anything.

```rust
pub struct Foo {
    bar: bool,
}
const CONF: Foo = Foo { bar: false };

fn main() {
    println!("main 0 {}", CONF.bar); // prints false - OK
    
    // This does compile ?!?
    CONF.bar = true;

    println!("main 1 {}", CONF.bar); // prints false - ?!?
}

```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=78c453988c1bdacb79079aecfb52a4fe))

Output:

```
main 0 false
main 1 false

```

Errors:

```
   Compiling playground v0.0.1 (/playground)
    Finished dev [unoptimized + debuginfo] target(s) in 0.39s
     Running `target/debug/playground`

```

**Comment by jonas-schievink** [comment]
This is working as expected – the LHS of an assignment must be a [*place expression*](https://doc.rust-lang.org/reference/expressions.html#place-expressions-and-value-expressions), which a field access is. This should probably be warned against though, but that is covered by https://github.com/rust-lang/rust/issues/16789, so closing in favor of that.

**Comment by gwierzchowski** [comment]
Got it.
As I understand assignment in my sample is equivalent to:
```rust
Foo { bar: false }.bar = true;
```
Thanks.
