### ISSUE TITLE
missing `AsMut<str>` implementation for `String`

### ISSUE THREAD

**Issue by tspiteri** [rust-lang/rust#68741]
`String` has an inherent method `as_mut_str`, and implements both `DerefMut` and `BorrowMut<str>`. Is there a reason why it does not implement `AsMut<str>`, or was it just an oversight?

**Comment by ExpHP** [comment]
It just goes to show how useless `&mut str` is that nobody was bothered by this until today. :stuck_out_tongue:

**Comment by estebank** [comment]
Tangentially related: https://github.com/rust-lang/rust/issues/44695
