### ISSUE TITLE
2^i should be optimized to 1 << i

### ISSUE THREAD

**Issue by phaazon** [rust-lang/rust#68773]
Hello,

I came across a weird situation with powers of 2. They’re not optimized away to left shifts. [Here’s a Godbolt example](https://godbolt.org/z/LEh7XP).

If you think it should / can be addressed, I’d love to do it! :)

**Comment by jonas-schievink** [comment]
`u32::pow` uses hand-rolled exponentiation by squaring, which LLVM probably can't "see through"

**Comment by kennytm** [comment]
Duplicate of #47234.
