### ISSUE TITLE
Destructuring after assigning enum is not considered irrefutable

### ISSUE THREAD

**Issue by tpdickso** [rust-lang/rust#68775]
Currently, this code fails to compile, as the destructuring of the variant `A` is considered refutable:
```rust
enum Enum {
    A(i32),
    B(f32)
}

fn main() {
    let a = Enum::A(12);
    let Enum::A(x) = a;
    println!("{}", a);
}
```
Irrefutable matches are difficult to determine in general but I think that this is a low-hanging fruit that would enable some useful programming patterns. For example, in my code, I've got a situation where I need to wrap a type in an enum, then call a method on an immutable reference to that enum value, and then pull it back out of the enum so I can use the value again, and it's nice not to have to wrap it in a `match { ... _ => unreachable!() }`.

I don't think there's any way where an immutable reference to an enum could change its variant without invoking undefined behaviour, even considering things like `UnsafeCell`, since correct use of an `UnsafeCell` still shouldn't hand out an immutable reference to the enum value itself while still mutating it.

**Comment by jonas-schievink** [comment]
This sort of program-flow-dependent analysis is deliberately not done at the moment, so changes to this would need to go through the RFC process. Closing in favor of that.

**Comment by tpdickso** [comment]
Do you mind if I ask why? Just out of curiosity; it's a small change on my end. But knowing the sort of analysis that the compiler already does for uninitialized variables, it's unexpected that there would be a specific decision against doing similar for destructuring.

**Comment by jonas-schievink** [comment]
It looks like this in particular could be addressed by giving enum variants their own types, which has come up quite a lot in the past. The oldest issue talking about that seems to be https://github.com/rust-lang/rfcs/issues/754.

**Comment by Ixrec** [comment]
It's more "can of worms" than "low-hanging fruit". Getting this exact snippet of code to compile might not be that hard, but pinning down precisely what code is and isn't allowed by the analysis would be _extremely_ difficult even for a minimal version like this. Similar to how designing Rust's move semantics and borrow checking logic is many times harder than writing a simple example of Rust code that passes the borrow checker.

To actually get anywhere you'd have to propose a feature, a design rule that unambiguously tells us what code would start compiling that didn't before, not just one example snippet. The most concrete idea I'm aware of in this space is [RFC 2593 Enum variant types](https://github.com/rust-lang/rfcs/pull/2593), which is controversial for lots of good reasons.

**Comment by tpdickso** [comment]
I do agree that solving the general problem would be difficult; I was thinking not about a fully-general analysis, but just a small subset. My understanding is that this is how variable initialization is handled in Rust today; determining if an uninitialized variable `let something;` is successfully initialized in a subroutine is in general undecidable, but the compiler still determines the variable to be initialized in some very simple analyses like
```rust
let x;
loop {
  if some_condition {
    x = value;
    break;
  }
}
```
And in this case the compiler won't even require `x` to be `mut` since it's even able to tell that `x` is assigned exactly once, which is definitely *in general* a hard problem.

I don't think the "low-hanging fruit" solution requires determining precisely which code is or isn't allowed, just deciding a very small subset that can be proven correct. In this case I was considering "variable `something` is assigned a value, and never reassigned nor a mutable reference taken before being destructured". Correct me if I'm wrong, but the analysis already done for "variable `something` does not need to be mutable" is already a sufficient condition for this code to compile successfully and safely.

Given that, I don't think enum types per RFC 2593 would have to interact with this.

**Comment by jonas-schievink** [comment]
That analysis would not be sufficient since the value, or at least the discriminant, must be known statically.

**Comment by tpdickso** [comment]
You're right; would the addition of "the variable is initialized using a specific enum variant constructor" be sufficient?

**Comment by jonas-schievink** [comment]
I don't know, but this is a good example of why the RFC process exists.

Besides, it looks like this change would effectively change the specification of match exhaustiveness to be based on dataflow analysis instead of just considering the type of the matched expression. This is a significant change. If we would accept the RFC linked above instead, this change would not be necessary since the exhaustiveness changes fall out naturally when the type of `a` becomes `Enum::A`.

**Comment by tpdickso** [comment]
Yes, I agree, I was just asking out of curiosity. As it stands I don't think the actual impact of the change would be worth opening an RFC for in its current state, but I do think it could be there with some thought, especially if it's an intermediate measure that could be subsumed by enum variant types in the future.

Thank you for your help!
