### ISSUE TITLE
Reduce use of `span.with_lo(span.lo() + BytePos(1))` in `librustc_parse/parser/mod.rs`

### ISSUE THREAD

**Issue by JohnTitor** [rust-lang/rust#68783]
`span.with_lo(span.lo() + BytePos(1))` may cause an ICE if span points strange character so we should use `next_point` instead. But `next_point` isn't actually equivalent with `span.with_lo(span.lo() + BytePos(1))` so it breaks some spans in current diagnostics. We should find out the cause and reduce use of them.

See context: https://github.com/rust-lang/rust/pull/68735#discussion_r373872254

**Comment by dwrensha** [comment]
I think #68845 should fix this.
