### ISSUE TITLE
Rust 1.41 stops recognizing pub const fns from a dep as const, regression from 1.40?

### ISSUE THREAD

**Issue by zhaojiangbin** [rust-lang/rust#68784]
Please find the minimum reproduction code below.

I have a crate using libpnet. Rust 1.40 compiled code just fine. Since I have upgraded Rust to 1.41, the crate no longer compiles. The compiler rejects the code with E0015.

Docs link to the libpnet pub const fn: https://docs.rs/pnet/0.25.0/pnet/packet/udp/struct.MutableUdpPacket.html#method.minimum_packet_size

The reproduction code compiles if the variable HDRLEN is not a const, such as:
```
    let HDRLEN: usize = MutableUdpPacket::minimum_packet_size();
```

I suspect it has something to do with how libpnet generates its structs and impls from macros. I cannot reproduce this regression with "hand-written" const fns such as: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=6a807abac8ec667038eb5d1e7b190329

Minimum reproduction:

main.rs:
```
use pnet::packet::udp::MutableUdpPacket;

fn main() {
    const HDRLEN: usize = MutableUdpPacket::minimum_packet_size();
    println!("{}", HDRLEN);
}
```

Dependencies in Cargo.toml
```
[dependencies]
pnet = { version = "^0.25" }
```

`cargo build --verbose` output:
```
/Users/jzhao/.cargo/bin/cargo build --verbose
       Fresh cfg-if v0.1.10
       Fresh rustc-serialize v0.3.24
       Fresh term v0.4.6
       Fresh unicode-xid v0.0.3
       Fresh ucd-util v0.1.7
       Fresh lazy_static v1.4.0
       Fresh bitflags v0.5.0
       Fresh utf8-ranges v1.0.4
       Fresh glob v0.2.11
       Fresh pnet_base v0.22.0
       Fresh syntex_pos v0.42.0
       Fresh thread_local v0.3.6
       Fresh regex-syntax v0.5.6
       Fresh libc v0.2.66
       Fresh log v0.4.8
       Fresh memchr v2.2.1
       Fresh serde v1.0.104
       Fresh pnet_macros_support v0.25.0
       Fresh log v0.3.9
       Fresh aho-corasick v0.6.10
       Fresh pnet_sys v0.25.0
       Fresh ipnetwork v0.15.1
       Fresh syntex_errors v0.42.0
       Fresh regex v0.2.11
       Fresh pnet_datalink v0.25.0
       Fresh syntex_syntax v0.42.0
       Fresh syntex v0.42.2
       Fresh pnet_macros v0.21.0
       Fresh pnet_packet v0.25.0
       Fresh pnet_transport v0.25.0
       Fresh pnet v0.25.0
   Compiling const_test v0.1.0 (/Users/jzhao/CodeWorks/Rust/tudp/const_test)
     Running `rustc --edition=2018 --crate-name const_test const_test/src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C debuginfo=2 -C metadata=2c79fc94223413d7 -C extra-filename=-2c79fc94223413d7 --out-dir /Users/jzhao/CodeWorks/Rust/tudp/target/debug/deps -C incremental=/Users/jzhao/CodeWorks/Rust/tudp/target/debug/incremental -L dependency=/Users/jzhao/CodeWorks/Rust/tudp/target/debug/deps --extern pnet=/Users/jzhao/CodeWorks/Rust/tudp/target/debug/deps/libpnet-4d0f2024b2405b46.rlib`
error[E0015]: calls in constants are limited to constant functions, tuple structs and tuple variants
 --> const_test/src/main.rs:5:27
  |
5 |     const HDRLEN: usize = MutableUdpPacket::minimum_packet_size();
  |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0015`.
error: could not compile `const_test`.

Caused by:
  process didn't exit successfully: `rustc --edition=2018 --crate-name const_test const_test/src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C debuginfo=2 -C metadata=2c79fc94223413d7 -C extra-filename=-2c79fc94223413d7 --out-dir /Users/jzhao/CodeWorks/Rust/tudp/target/debug/deps -C incremental=/Users/jzhao/CodeWorks/Rust/tudp/target/debug/incremental -L dependency=/Users/jzhao/CodeWorks/Rust/tudp/target/debug/deps --extern pnet=/Users/jzhao/CodeWorks/Rust/tudp/target/debug/deps/libpnet-4d0f2024b2405b46.rlib` (exit code: 1)
```

**Comment by ecstatic-morse** [comment]
Your example builds fine for me on 1.41.0 stable when specifying `pnet = ^0.25`. In your build log, it looks like you're building `pnet-0.25.0` but using `pnet-macros-0.21.0`, which did not mark `minimum_packet_size` [as a `const fn`](https://github.com/libpnet/libpnet/blob/63cc046de94bfa01ffac77515755573b9d1e35e2/pnet_macros/src/decorator.rs#L975).

Could you post your `Cargo.lock` here, then delete it and try again?

**Comment by zhaojiangbin** [comment]
@ecstatic-morse 

Thanks for the quick diagnosis. Now I cannot reproduce it myself either. I don't know how the Cargo.lock file ended up using pnet_macros v0.21.0. I never edit Cargo.lock files by hand. I was able to reproduce the issue with libpnet v0.23.0 and libpnet v0.25.0. But neither contains pnet_macros v0.21.0 as far as I can tell.

In my git repo history, I found the commit where in Cargo.lock pnet_macros was downgraded from v0.23.0 to v0.21.0. This is a big commit where I added a benchmark test and the dev-dep on criterion for a different crate in the same workspace. This different crate does not use libpnet at all. I cannot tell why and how the version of pnet_macros was changed at the same time.

At this point, what's clear is that the issue is definitely not with rustc. It is very likely a problem in my workflow updating the deps and switching between git branches. Also in hindsight, I should have tried to "reproduce" the issue in a clean workspace.

Sorry for the false alarm. Please close the issue as invalid.

**Comment by zhaojiangbin** [comment]
Update: 

I spoke too soon about not reproducng it myself. It still happens with this commit that I added the benchmark test and dev-dep on criterion. It is not happening with commits prior to this one, and not in other branches.

It looks like the issue is caused by that libpnet yanked version 0.23.0. I had been using this version without updating the registry cache for over a month until two days ago when I needed to add the dev-dep on criterion. 

But what's odd is that, now with this commit, cargo insists on using pnet_macros v0.21.0 even after I changed the version of dependencies.pnet to 0.25.0 in my crate. Also tried another version 0.23.1. Same result. I did delete Cargo.lock, ran cargo clean, even removed ~/.cargo/registry.

While this is not a rustc issue anymore, it starts looking like an issue in cargo?

**Comment by ecstatic-morse** [comment]
I'm closing this since it's not a compiler bug. @zhaojiangbin could open an issue on [rust-lang/cargo]?(https://github.com/rust-lang/rust/) I don't know enough about dependency resolution to say whether cargo is doing something wrong here, but the cargo team will be more knowledgeable.

**Comment by zhaojiangbin** [comment]
Opened an issue on cargo: rust-lang/cargo#7866.
