### ISSUE TITLE
Stabilize core::arch::*::has_cpuid()

### ISSUE THREAD

**Issue by npmccallum** [rust-lang/rust#68806]
We currently have an architecture intrinsic:
  - [`core::arch::x86_64::has_cpuid()`](https://doc.rust-lang.org/1.41.0/core/arch/x86_64/fn.has_cpuid.html)
  - [`core::arch::x86::has_cpuid()`](https://doc.rust-lang.org/1.41.0/core/arch/x86/fn.has_cpuid.html)

However, this is part of the larger `stdsimd` feature, the status of which is unclear to me:
https://github.com/rust-lang/rust/issues/48556

Can we stabilize this intrinsic? It is very useful for many other cases. It is small, self-contained and well defined. As far as I can gather, it has simply fallen through the cracks.

@joshtriplett @lkatalin

**Comment by Centril** [comment]
See https://github.com/rust-lang/rust/issues/60123. It seems we wanted to remove it?

**Comment by npmccallum** [comment]
Thanks, I'll close this and comment there.
