### ISSUE TITLE
Tracking issue for `std::io::{BufReader, BufWriter}::capacity`

### ISSUE THREAD

**Issue by JohnTitor** [rust-lang/rust#68833]
#68558 adds `capacity` methods to `BufReader` and `BufWriter`.

Unresolved questions:

**Comment by mbrubeck** [comment]
Can I nominate this for stabilization? It's a straightforward API with no real alternatives possible, and I had a real-world use case for it recently.

**Comment by JohnTitor** [comment]
CC @rust-lang/libs --^?

**Comment by sfackler** [comment]
@rfcbot fcp merge
