### ISSUE TITLE
Please reconsider mips32 "r1" support

### ISSUE THREAD

**Issue by alexpdp7** [rust-lang/rust#68865]
Hi,

In:

https://github.com/rust-lang/rust/pull/48874

, the mips targets were bumped to use the mips32r2 instruction set. There's a few systems being sold today which use cheap mips32-non-r1 chips, like:

https://retrogame300.com/collections/all
https://retromimi.com/products/retro-game-plus

, etc. They use buildroot-derived operating systems, which adds some complexity to adding a new target to Rust, so I'm wondering if it could be acceptable to add a new target or revert that change, as it would make things simpler to code for such devices.

Cheers,

Álex

**Comment by alexpdp7** [comment]
Note: I just tested that:

```
+diff --git a/src/librustc_target/spec/mipsel_unknown_linux_uclibc.rs b/src/librustc_target/spec/mipsel_unknown_linux_uclibc.rs
+index a8152011efa..1e730ea9d47 100644
+--- a/src/librustc_target/spec/mipsel_unknown_linux_uclibc.rs
++++ b/src/librustc_target/spec/mipsel_unknown_linux_uclibc.rs
+@@ -14,8 +14,8 @@ pub fn target() -> TargetResult {
+         linker_flavor: LinkerFlavor::Gcc,
+ 
+         options: TargetOptions {
+-            cpu: "mips32r2".to_string(),
+-            features: "+mips32r2,+soft-float".to_string(),
++            cpu: "mips32".to_string(),
++            features: "mips32,-mips32r2,+single-float".to_string(),
+             max_atomic_width: Some(32),
+             target_mcount: "_mcount".to_string(),
+ 
+-- 
+2.20.1
+
-- 
2.20.1
```

works, allowing me to generate binaries which don't crash on mips32 non-r1. although I'm not so sure about FPU support. If someone comes across this, I documented my whole process for crosscompiling using buildroot, etc. at:

https://github.com/alexpdp7/retrofw2-rust

**Comment by workingjubilee** [comment]
This feature level was fairly deliberately chosen, see the discussion here:
- https://github.com/rust-lang/rust/issues/41606

Since this request was made we now support a number of interesting MIPS targets, some with even lower requirements, so it seems to me that changing this is not necessary. Ultimately, this can be toggled via `-Ctarget-feature`.
