### ISSUE TITLE
25% compile time increase on beta when building async-std

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/rust#68864]
On my machine, `cargo build` on https://github.com/async-rs/async-std/commit/1d875836a2302681a395ee44512a518f0222da4a finishes in ~6.75s on stable 1.41.0, but takes at least 8.50s on the current beta (1.42.0-beta.2 (3d2613e2c 2020-02-04)), an increase of ~25%.

Recent nightlies are still affected, but my perf improvements in https://github.com/rust-lang/rust/pull/68606 and https://github.com/rust-lang/rust/pull/68672 improve things a bit which hides the regression.

**Comment by jonas-schievink** [comment]
```
nightly-2020-01-24

6.77s
6.74s

nightly-2020-01-25

8.38s
8.46s
```

**Comment by jonas-schievink** [comment]
Commits in that range: https://github.com/rust-lang/rust/compare/41f41b2354778375dc72f7ed1d9323626580dc4d...c2d141df59703393c0c683abc259f9a8c3be041a

**Comment by pnkfelix** [comment]
@jonas-schievink i figure until we've narrowed to a specific PR, we can keep the needs-bisect tag, right?

**Comment by pnkfelix** [comment]
triage: P-high. Removing nomination. Assigning to self. might be good to see if we can extract a case to add to perf.rlo from this.

**Comment by michaelwoerister** [comment]
Is this for release or debug builds?

**Comment by jonas-schievink** [comment]
This is just a normal `cargo build`

**Comment by pnkfelix** [comment]
(I cannot reproduce this in a reliable fashion on my Mac.)

**Comment by nikomatsakis** [comment]
Maybe we can use [self-profile](https://blog.rust-lang.org/inside-rust/2020/02/25/intro-rustc-self-profile.html) to try and narrow down what has changed?

**Comment by pnkfelix** [comment]
@jonas-schievink what kind of machine are you using? In particular, what OS (and if Linux, what distribution and version?)

**Comment by jonas-schievink** [comment]
This was on a ThinkPad X1 Carbon running Arch Linux (not sure how up-to-date it was at the time, but not more than a few weeks out of date). I can take another look to narrow this down.

**Comment by jonas-schievink** [comment]
Updating to rustc 1.42.0-beta.5 (4e1c5f0e9 2020-02-28) seems to fix the regression. I can still reproduce with rustc 1.42.0-beta.2 (3d2613e2c 2020-02-04).

That diff contains 665a39c, so that might have fixed it.
