### ISSUE TITLE
map_or Documentation should note that the arguments are eagerly evaluated

### ISSUE THREAD

**Issue by ShaneLillieRAD** [rust-lang/rust#68866]
Apologies if this isn't the appropriate repo to raise this issue on, I can close and re-create it wherever would be more appropriate.

It's a small thing, but in the documentation for both std::result::Result and std::option::Option it's noted that the *_or arguments are eagerly evaluated (with a suggestion to use the *_or_else for lazy evaluation) everywhere except for map_or. The behavior isn't super obvious up front if you're unfamiliar with that fact, but is very much important to know, so it would be nice if they were all consistent in that.

This issue has been assigned to @tom-a-wagner via [this comment](https://github.com/rust-lang/rust/issues/68866#issuecomment-582826225).

**Comment by tom-a-wagner** [comment]
This seems more than easy enough for a first commit.

@rustbot  claim
