### ISSUE TITLE
&str slicing using SliceIndex is slow

### ISSUE THREAD

**Issue by Riey** [rust-lang/rust#68874]
# Summary

It seems closure in unwrap_or_else doesn't inlined

https://github.com/rust-lang/rust/blob/a25d58b41b273993c27a2533dc193b799abbf43f/src/libcore/str/mod.rs#L1854
https://github.com/rust-lang/rust/blob/a25d58b41b273993c27a2533dc193b799abbf43f/src/libcore/str/mod.rs#L1921
https://github.com/rust-lang/rust/blob/a25d58b41b273993c27a2533dc193b799abbf43f/src/libcore/str/mod.rs#L1986

I can't make PR because I don't know how can I fix should this code don't use `unwrap_or_else`? or need some patch for optimizer or LLVM?
# Godbolt

https://godbolt.org/z/TBhkjy

# Benchmark

## Code

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=765da897030741f77b13ce397dc7f882

## Result
```
running 4 tests
test benches::bar_itself ... bench:         195 ns/iter (+/- 0) = 5261 MB/s
test benches::bar_long   ... bench:       2,311 ns/iter (+/- 14) = 5374 MB/s
test benches::foo_itself ... bench:         383 ns/iter (+/- 2) = 2678 MB/s
test benches::foo_long   ... bench:       4,606 ns/iter (+/- 7) = 2696 MB/s

test result: ok. 0 passed; 0 failed; 0 ignored; 4 measured; 0 filtered out
```

**Comment by kevinastone** [comment]
Discussion on reddit: https://www.reddit.com/r/rust/comments/ez64g2/why_spos_is_slower_than_ssplit_atpos1/

**Comment by phjeltman** [comment]
> I can't make PR because I don't know how can I fix should this code don't use unwrap_or_else? or need some patch for optimizer or LLVM?

How about adding a #[inline(always)] annotation to the closure, would that work?
