### ISSUE TITLE
Feature request: plain-text rustdoc output format for CLI friendliness

### ISSUE THREAD

**Issue by rw** [rust-lang/rust#68870]
I do a lot of development on the command line. In particular, I sometimes develop code over an SSH connection (on a remote machine). It would be **very** helpful to not need to start a proxy service that allows me to connect to the machine with a local web browser to look at the documentation for the crates that I write.

I suggest starting with a Markdown output format. I believe this may be simpler to maintain than the HTML/CSS/JS generator.

Golang does this very well, out-of-the-box. It would be great if Rust and Cargo became more commandline-friendly in this way.

I'd be happy to sponsor development of this feature.

Thank you!

**Comment by Mark-Simulacrum** [comment]
I believe that this needs an RFC if this is done. However, I will also note that for the most part, the raw documentation is quite readable, and is generally viewable in the source code of crates you depend on, which can for example be found in ~/.cargo/registry/src/github.com-1ecc6299db9ec823/serde-1.0.104 (the hash may change).

It is also possible to copy the docs (e.g.,  `cargo doc && scp -r $HOST:/path/to/target/docs ./`) locally after generating them.

Given today's model of rustdoc output I don't think we would be able to support what you suggest without a near complete redesign, and I don't think we would currently have the people to do so (nor, really, the interest).

There are also many interesting questions in my opinion to answer around a mapping from rustdoc's HTML output to markdown (some features, like search, are ~impossible in a markdown-based tool, I think).

**Comment by andrewchambers** [comment]
Given recent developments in llms, this might be a useful feature - As an example, godoc is very good for passing documentation to llms.
