### ISSUE TITLE
enum inside the struct

### ISSUE THREAD

**Issue by kunduzb17** [rust-lang/rust#68883]
Below is the example of C++ code , how can I construct the same in rust ?
```
struct AddressType {
        enum Enum {
            NONSTANDARD,
            PUBKEY
        };
    };
AddressType::Enum a = AddressType::PUBKEY;
```

**Comment by Secticide** [comment]
This can be done by using the following:
```
enum Enum {
    NONSTANDARD,
    PUBKEY
}
```
Enums in Rust are fairly close to enum class types in C++ syntactically (but with some extra features). Find more information here:
[Rust book: Chapter 06 - Defining an enum](https://doc.rust-lang.org/book/ch06-01-defining-an-enum.html)

**Comment by kunduzb17** [comment]
But my purpose was to make Enum part of `AddressType` struct,  so that  NONSTANDARD and PUBKEY have same type which is` AddressType::Enum`. In c++ `a` will have value `1` of type ` AddressType::Enum`.

**Comment by Secticide** [comment]
Do you mean that the struct has the purpose of namespacing? If this is the case you could name the enum like so:
```
enum AddressType {
    NONSTANDARD,
    PUBKEY
}
```
This gives both enum values the same type and can be used with the following syntax:
`AddressType::NONSTANDARD`
Or do you intent to have other data members within the struct?

**Comment by jonas-schievink** [comment]
Hi! This issue tracker is mainly meant for bug reports and concrete, small feature requests. Questions like this are better asked in the user forum at https://users.rust-lang.org/ or on [one of the chat platforms](https://www.rust-lang.org/community) used by the Rust community.
