### ISSUE TITLE
linking with `link.exe` failed: exit code: 1120

### ISSUE THREAD

**Issue by mshabab1296** [rust-lang/rust#68882]
I am using the following command to istall diesel_cli
**cargo install diesel_cli --no-default-features --features "mysql"**
I installed MySql Connector C 6.1 also I have Visual Studio 2019 in my Windows 10 PC.

error: linking with `link.exe` failed: exit code: 1120
  |
  = note: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.24.28314\\bin\\HostX64\\x86\\link.exe" "/NOLOGO" "/NXCOMPAT" "/LARGEADDRESSAWARE" "/SAFESEH" "/LIBPATH:C:\\Users\\lenovo\\.rustup\\toolchains\\nightly-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\hello_rocket.16c6andzb0ou53dr.rcgu.o" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\hello_rocket.16lobazfpm3pl6b3.rcgu.o" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\hello_rocket.1a5zkm2sxvlvb0o0.rcgu.o" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\hello_rocket.1bg44u1ot9ksbjig.rcgu.o" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\hello_rocket.1d7kny3uw88184f1.rcgu.o" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\hello_rocket.1gy82hj28wutomp6.rcgu.o" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\hello_rocket.1j8h6s34vt3b8nhx.rcgu.o" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\hello_rocket.1liazp4d5jfwy24y.rcgu.o" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\hello_rocket.1mgyikq5hc7wtqb1.rcgu.o" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\hello_rocket.22dak74big17q104.rcgu.o" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\hello_rocket.22m7800yry2qg1zh.rcgu.o" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\hello_rocket.24vb99ai7613pk10.rcgu.o" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\hello_rocket.27720zab1gidqrkx.rcgu.o" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\hello_rocket.29jk348vk57gb504.rcgu.o" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\hello_rocket.2ablpkbl2dz5knul.rcgu.o" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\hello_rocket.2gs6jm34mjlzsk4u.rcgu.o" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\hello_rocket.2i67ipjzxgktysq2.rcgu.o" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\hello_rocket.2lcmkkuen7y0t9j.rcgu.o" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\hello_rocket.2mxawph0mrdm5yj2.rcgu.o" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\hello_rocket.376k319y7d66qwoh.rcgu.o" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\hello_rocket.39gjewnx5lisv5vr.rcgu.o" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\hello_rocket.3ahbzritzrvwqdxt.rcgu.o" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\hello_rocket.3b49dt5mqm9bfstn.rcgu.o" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\hello_rocket.3bd3jtev8q46ops3.rcgu.o" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\hello_rocket.3j6pmddsjxme56n5.rcgu.o" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\hello_rocket.3k3852gunn9rjk24.rcgu.o" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\hello_rocket.3nk9oya6if9gylkl.rcgu.o" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\hello_rocket.3s434pv2ds6f7x9l.rcgu.o" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\hello_rocket.3t8z13lu7ygzowpi.rcgu.o" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\hello_rocket.3vnf1th7moz5f3em.rcgu.o" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\hello_rocket.3wbzph83z4cxm9l0.rcgu.o" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\hello_rocket.3zqpiii46a3sot45.rcgu.o" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\hello_rocket.41shxj8j1iykxk23.rcgu.o" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\hello_rocket.43jtlhurgeii2t21.rcgu.o" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\hello_rocket.46x7oj61m4eamqyk.rcgu.o" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\hello_rocket.4aen16itvdzz0f78.rcgu.o" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\hello_rocket.4ekvcxlg0a4pzmrg.rcgu.o" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\hello_rocket.4h4w3n28xo8uhry5.rcgu.o" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\hello_rocket.4ij6g3lnk73akbma.rcgu.o" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\hello_rocket.4spsom0lkhy1ybbl.rcgu.o" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\hello_rocket.53g7ayfyf1c6vk2a.rcgu.o" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\hello_rocket.58kz6f9z9sek2xxk.rcgu.o" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\hello_rocket.59hei17ww8euw4ea.rcgu.o" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\hello_rocket.59qrg63d0z4zfhif.rcgu.o" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\hello_rocket.5g8mq7xccuwfom32.rcgu.o" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\hello_rocket.6ajg0par5vxgwcz.rcgu.o" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\hello_rocket.6vt09us3lq2ppc5.rcgu.o" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\hello_rocket.h4u29xfirrm8kfp.rcgu.o" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\hello_rocket.i3yr2ggjgrma87o.rcgu.o" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\hello_rocket.k3ljhd64kcr8ifr.rcgu.o" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\hello_rocket.rnflf8yfobu4yh2.rcgu.o" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\hello_rocket.vrzxp246lkp7evr.rcgu.o" "/OUT:E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\hello_rocket.exe" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\hello_rocket.4g0urjh5klhl07p8.rcgu.o" "/OPT:REF,NOICF" "/DEBUG" "/NATVIS:C:\\Users\\lenovo\\.rustup\\toolchains\\nightly-i686-pc-windows-msvc\\lib\\rustlib\\etc\\intrinsic.natvis" "/NATVIS:C:\\Users\\lenovo\\.rustup\\toolchains\\nightly-i686-pc-windows-msvc\\lib\\rustlib\\etc\\liballoc.natvis" "/NATVIS:C:\\Users\\lenovo\\.rustup\\toolchains\\nightly-i686-pc-windows-msvc\\lib\\rustlib\\etc\\libcore.natvis" "/NATVIS:C:\\Users\\lenovo\\.rustup\\toolchains\\nightly-i686-pc-windows-msvc\\lib\\rustlib\\etc\\libstd.natvis" "/LIBPATH:E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps" "/LIBPATH:E:\\rust\\rocket\\hello-rocket\\target\\debug\\build\\ring-746a859801450bb4\\out" "/LIBPATH:C:\\Program Files\\MySQL\\MySQL Connector C 6.1\\lib\\vs14" "/LIBPATH:C:\\Users\\lenovo\\.rustup\\toolchains\\nightly-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\librocket_contrib-a14f4f1f390a714a.rlib" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\libdiesel-99ef786b9111c345.rlib" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\libmysqlclient_sys-1fbddb8d318e5c51.rlib" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\libr2d2-ffbf2b9d03ce5240.rlib" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\libscheduled_thread_pool-62d9e13e8ffa5c88.rlib" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\libparking_lot-13bcbd19a9fb034b.rlib" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\libparking_lot_core-6ac3373848e12eb0.rlib" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\liblock_api-52c3f1f169ff32e2.rlib" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\libscopeguard-031d985b9f0a40c2.rlib" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\librocket-d576b680db07e655.rlib" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\libatty-505b573698e4400a.rlib" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\libbase64-84107e3635bd99a0.rlib" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\libmemchr-86cae8e0488b7813.rlib" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\libtoml-1c50b2dc8c03352d.rlib" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\libserde-c26cbbf53e5fe52e.rlib" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\libyansi-effe00e7f3a8ad53.rlib" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\librocket_http-4a02f2914d6534b4.rlib" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\libhyper-7da3808e752dbb63.rlib" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\libmime-9dbc6c6d6eacb188.rlib" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\liblog-ba94a3ef0c9ba338.rlib" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\liblog-ebe5a05c3680b95b.rlib" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\libcfg_if-3f4d2fb9ac49be0d.rlib" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\liblanguage_tags-2ea92e22b47d1167.rlib" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\libtypeable-d5ed992a2b0d8ff0.rlib" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\libtraitobject-9f21903ec4332d66.rlib" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\libnum_cpus-5ddf27e47172cbc6.rlib" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\libhttparse-53016c220ba47099.rlib" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\libunicase-7d0fc8ab34d7512f.rlib" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\libunicode_xid-e125e74974c7d197.rlib" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\libstate-4e09c7deb1cd447a.rlib" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\libindexmap-6bf8dbb7c9e073b3.rlib" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\libcookie-b17abdd7042cd9cb.rlib" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\libbase64-9a73d1541690f2a7.rlib" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\libsafemem-463a7af66cd197ab.rlib" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\libbyteorder-20205c9d1b136163.rlib" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\libring-8c0fe310713ef96a.rlib" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\libuntrusted-13443f6ee66e6150.rlib" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\libtime-80d4bf6fb7127614.rlib" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\libwinapi-33173922199c3177.rlib" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\liburl-88f1cd7a927780ff.rlib" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\libidna-be6c18f6bbfd24a2.rlib" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\libunicode_normalization-0b3e4d242413141e.rlib" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\libsmallvec-31c2d7def8b5bb6f.rlib" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\libunicode_bidi-14c001d097010a12.rlib" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\libmatches-f23fa67883b40cb5.rlib" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\libsmallvec-8575fcf0e45dfd5b.rlib" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\libmaybe_uninit-5c30f29999c8eed6.rlib" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\libpercent_encoding-5b1bd8faf180239f.rlib" "E:\\rust\\rocket\\hello-rocket\\target\\debug\\deps\\libpear-e145e81d4d03a869.rlib" "C:\\Users\\lenovo\\.rustup\\toolchains\\nightly-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\libstd-801df100069f1598.rlib" "C:\\Users\\lenovo\\.rustup\\toolchains\\nightly-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\libpanic_unwind-fb2db42fbf7b0c9f.rlib" "C:\\Users\\lenovo\\.rustup\\toolchains\\nightly-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\libhashbrown-1489bcf82015bbd4.rlib" "C:\\Users\\lenovo\\.rustup\\toolchains\\nightly-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\librustc_std_workspace_alloc-d2e9e426f1565277.rlib" "C:\\Users\\lenovo\\.rustup\\toolchains\\nightly-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\libbacktrace-4f39c377136a8563.rlib" "C:\\Users\\lenovo\\.rustup\\toolchains\\nightly-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\librustc_demangle-76600a44b140a10b.rlib" "C:\\Users\\lenovo\\.rustup\\toolchains\\nightly-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\libunwind-3691f60b40d08cb5.rlib" "C:\\Users\\lenovo\\.rustup\\toolchains\\nightly-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\libcfg_if-bb82703678014630.rlib" "C:\\Users\\lenovo\\.rustup\\toolchains\\nightly-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\liblibc-89a628f203a981ea.rlib" "C:\\Users\\lenovo\\.rustup\\toolchains\\nightly-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\liballoc-94eeecbbe69a9b7a.rlib" "C:\\Users\\lenovo\\.rustup\\toolchains\\nightly-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\librustc_std_workspace_core-67ae2f7096061a0c.rlib" "C:\\Users\\lenovo\\.rustup\\toolchains\\nightly-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\libcore-0bf66a4b262355a6.rlib" "C:\\Users\\lenovo\\.rustup\\toolchains\\nightly-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\libcompiler_builtins-afb62433a23c4011.rlib" "advapi32.lib" "advapi32.lib" "cfgmgr32.lib" "fwpuclnt.lib" "gdi32.lib" "kernel32.lib" "msimg32.lib" "ntdll.lib" "opengl32.lib" "synchronization.lib" "user32.lib" "winspool.lib" "ws2_32.lib" "advapi32.lib" "ws2_32.lib" "userenv.lib" "msvcrt.lib"
  = note: libdiesel-99ef786b9111c345.rlib(diesel-99ef786b9111c345.diesel.9hghqceo-cgu.9.rcgu.o) : error LNK2019: unresolved external symbol _mysql_stmt_prepare referenced in function __ZN6diesel5mysql10connection4stmt9Statement7prepare17hbbaa98b13a13a962E
          libdiesel-99ef786b9111c345.rlib(diesel-99ef786b9111c345.diesel.9hghqceo-cgu.9.rcgu.o) : error LNK2019: unresolved external symbol _mysql_stmt_execute referenced in function __ZN6diesel5mysql10connection4stmt9Statement7execute17h9a25e21d65cfdd00E
          libdiesel-99ef786b9111c345.rlib(diesel-99ef786b9111c345.diesel.9hghqceo-cgu.9.rcgu.o) : error LNK2019: unresolved external symbol _mysql_stmt_store_result referenced in function __ZN6diesel5mysql10connection4stmt9Statement7execute17h9a25e21d65cfdd00E
          libdiesel-99ef786b9111c345.rlib(diesel-99ef786b9111c345.diesel.9hghqceo-cgu.9.rcgu.o) : error LNK2019: unresolved external symbol _mysql_stmt_affected_rows referenced in function __ZN6diesel5mysql10connection4stmt9Statement13affected_rows17h8439fdd34068e027E
          libdiesel-99ef786b9111c345.rlib(diesel-99ef786b9111c345.diesel.9hghqceo-cgu.9.rcgu.o) : error LNK2019: unresolved external symbol _mysql_stmt_error referenced in function __ZN6diesel5mysql10connection4stmt9Statement18last_error_message17hff2ef538f079ef21E
          libdiesel-99ef786b9111c345.rlib(diesel-99ef786b9111c345.diesel.9hghqceo-cgu.9.rcgu.o) : error LNK2019: unresolved external symbol _mysql_stmt_bind_result referenced in function __ZN6diesel5mysql10connection4stmt9Statement11bind_result17h193356ffa97cfbd3E
          libdiesel-99ef786b9111c345.rlib(diesel-99ef786b9111c345.diesel.9hghqceo-cgu.9.rcgu.o) : error LNK2019: unresolved external symbol _mysql_stmt_fetch_column referenced in function __ZN6diesel5mysql10connection4stmt9Statement12fetch_column17h7e7832934d06a5a1E
          libdiesel-99ef786b9111c345.rlib(diesel-99ef786b9111c345.diesel.9hghqceo-cgu.9.rcgu.o) : error LNK2019: unresolved external symbol _mysql_stmt_result_metadata referenced in function __ZN6diesel5mysql10connection4stmt9Statement8metadata17h9c4df1979f4d996fE
          libdiesel-99ef786b9111c345.rlib(diesel-99ef786b9111c345.diesel.9hghqceo-cgu.9.rcgu.o) : error LNK2019: unresolved external symbol _mysql_stmt_errno referenced in function __ZN6diesel5mysql10connection4stmt9Statement15last_error_type17hd86dabc2a42d087aE
          libdiesel-99ef786b9111c345.rlib(diesel-99ef786b9111c345.diesel.9hghqceo-cgu.9.rcgu.o) : error LNK2019: unresolved external symbol _mysql_stmt_close referenced in function __ZN84_$LT$diesel..mysql..connection..stmt..Statement$u20$as$u20$core..ops..drop..Drop$GT$4drop17h0f8b06d72094425eE
          libdiesel-99ef786b9111c345.rlib(diesel-99ef786b9111c345.diesel.9hghqceo-cgu.5.rcgu.o) : error LNK2019: unresolved external symbol _mysql_init referenced in function __ZN6diesel5mysql10connection3raw13RawConnection3new17hc699e4e515394d44E
          libdiesel-99ef786b9111c345.rlib(diesel-99ef786b9111c345.diesel.9hghqceo-cgu.5.rcgu.o) : error LNK2019: unresolved external symbol _mysql_options referenced in function __ZN6diesel5mysql10connection3raw13RawConnection3new17hc699e4e515394d44E
          libdiesel-99ef786b9111c345.rlib(diesel-99ef786b9111c345.diesel.9hghqceo-cgu.5.rcgu.o) : error LNK2019: unresolved external symbol _mysql_real_connect referenced in function __ZN6diesel5mysql10connection3raw13RawConnection7connect17h485f3d8e19f2032bE
          libdiesel-99ef786b9111c345.rlib(diesel-99ef786b9111c345.diesel.9hghqceo-cgu.5.rcgu.o) : error LNK2019: unresolved external symbol _mysql_error referenced in function __ZN6diesel5mysql10connection3raw13RawConnection18last_error_message17h109bae33a1e5500eE
          libdiesel-99ef786b9111c345.rlib(diesel-99ef786b9111c345.diesel.9hghqceo-cgu.5.rcgu.o) : error LNK2019: unresolved external symbol _mysql_real_query referenced in function __ZN6diesel5mysql10connection3raw13RawConnection7execute17ha94181887cb9e4e1E
          libdiesel-99ef786b9111c345.rlib(diesel-99ef786b9111c345.diesel.9hghqceo-cgu.5.rcgu.o) : error LNK2019: unresolved external symbol _mysql_set_server_option referenced in function __ZN6diesel5mysql10connection3raw13RawConnection23enable_multi_statements17hf0f8bd0efe53247cE
          libdiesel-99ef786b9111c345.rlib(diesel-99ef786b9111c345.diesel.9hghqceo-cgu.5.rcgu.o) : error LNK2019: unresolved external symbol _mysql_affected_rows referenced in function __ZN6diesel5mysql10connection3raw13RawConnection13affected_rows17h10230b1b7895dcd8E
          libdiesel-99ef786b9111c345.rlib(diesel-99ef786b9111c345.diesel.9hghqceo-cgu.5.rcgu.o) : error LNK2019: unresolved external symbol _mysql_stmt_init referenced in function __ZN6diesel5mysql10connection3raw13RawConnection7prepare17h96d3cfbb5a0b78b1E
          libdiesel-99ef786b9111c345.rlib(diesel-99ef786b9111c345.diesel.9hghqceo-cgu.5.rcgu.o) : error LNK2019: unresolved external symbol _mysql_store_result referenced in function __ZN6diesel5mysql10connection3raw13RawConnection22consume_current_result17hb4e4aaa68f846d3fE
          libdiesel-99ef786b9111c345.rlib(diesel-99ef786b9111c345.diesel.9hghqceo-cgu.5.rcgu.o) : error LNK2019: unresolved external symbol _mysql_free_result referenced in function __ZN6diesel5mysql10connection3raw13RawConnection22consume_current_result17hb4e4aaa68f846d3fE
          libdiesel-99ef786b9111c345.rlib(diesel-99ef786b9111c345.diesel.9hghqceo-cgu.15.rcgu.o) : error LNK2001: unresolved external symbol _mysql_free_result
          libdiesel-99ef786b9111c345.rlib(diesel-99ef786b9111c345.diesel.9hghqceo-cgu.5.rcgu.o) : error LNK2019: unresolved external symbol _mysql_more_results referenced in function __ZN6diesel5mysql10connection3raw13RawConnection12more_results17h8076cd1658d3bfc8E
          libdiesel-99ef786b9111c345.rlib(diesel-99ef786b9111c345.diesel.9hghqceo-cgu.5.rcgu.o) : error LNK2019: unresolved external symbol _mysql_next_result referenced in function __ZN6diesel5mysql10connection3raw13RawConnection11next_result17hdfd4b3ad1ee08e45E
          libdiesel-99ef786b9111c345.rlib(diesel-99ef786b9111c345.diesel.9hghqceo-cgu.5.rcgu.o) : error LNK2019: unresolved external symbol _mysql_close referenced in function __ZN87_$LT$diesel..mysql..connection..raw..RawConnection$u20$as$u20$core..ops..drop..Drop$GT$4drop17h993cc1ba8409dcfbE
          libdiesel-99ef786b9111c345.rlib(diesel-99ef786b9111c345.diesel.9hghqceo-cgu.5.rcgu.o) : error LNK2019: unresolved external symbol _mysql_server_init referenced in function __ZN6diesel5mysql10connection3raw44perform_thread_unsafe_library_initialization28_$u7b$$u7b$closure$u7d$$u7d$17hc0a43373c909e4c5E
          libdiesel-99ef786b9111c345.rlib(diesel-99ef786b9111c345.diesel.9hghqceo-cgu.2.rcgu.o) : error LNK2019: unresolved external symbol _mysql_stmt_fetch referenced in function __ZN6diesel5mysql10connection4stmt8iterator20populate_row_buffers17h7bedbb20f07722faE
          libdiesel-99ef786b9111c345.rlib(diesel-99ef786b9111c345.diesel.9hghqceo-cgu.15.rcgu.o) : error LNK2019: unresolved external symbol _mysql_num_fields referenced in function __ZN6diesel5mysql10connection4stmt8metadata17StatementMetadata6fields17hc8ed6f26828e0cf3E
          libdiesel-99ef786b9111c345.rlib(diesel-99ef786b9111c345.diesel.9hghqceo-cgu.15.rcgu.o) : error LNK2019: unresolved external symbol _mysql_fetch_fields referenced in function __ZN6diesel5mysql10connection4stmt8metadata17StatementMetadata6fields17hc8ed6f26828e0cf3E
          E:\rust\rocket\hello-rocket\target\debug\deps\hello_rocket.exe : fatal error LNK1120: 27 unresolved externals

Can someone please give me a solution for the error ?
Thanks

**Comment by jonas-schievink** [comment]
Looks like you need to install the mysql libraries into a place where the linker can find them. Consider asking on Diesel's Gitter channel, the people there can probably help.
