### ISSUE TITLE
Crater runs for 1.42.0

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#68895]
cc @rust-lang/release

**Comment by pietroalbini** [comment]
@craterbot run name=beta-1.42-1 start=1.41.0 end=beta-2020-02-05 mode=build-and-test cap-lints=warn p=10

**Comment by pietroalbini** [comment]
@craterbot run name=beta-1.42-rustdoc-1 start=1.41.0 end=beta-2020-02-05 mode=rustdoc cap-lints=warn p=5

**Comment by pietroalbini** [comment]
**Do NOT triage the results in the Crater run without coordinating with the release team!**

**Comment by Mark-Simulacrum** [comment]
Finished triage for both crater runs.

$crate may not be imported #69190 
ICE on Tried to access field 0 of union Layout #69191 
Make conflicting_repr_hints a deny-by-default c-future-compat lint https://github.com/rust-lang/rust/pull/68586#issuecomment-586624786
