### ISSUE TITLE
internal compiler error: unexpected lifetime bound

### ISSUE THREAD

**Issue by dwrensha** [rust-lang/rust#68890]
I'm seeing an internal compiler error on the following input (found by [fuzz-rustc](https://github.com/dwrensha/fuzz-rustc)):

```
$ echo "enum e{A((?'a a+?+l))}" > main.rs
$ rustc main.rs
error: `?` may only modify trait bounds, not lifetime bounds
 --> main.rs:1:11
  |
1 | enum e{A((?'a a+?+l))}
  |           ^

error: expected one of `)`, `+`, or `,`, found `a`
 --> main.rs:1:15
  |
1 | enum e{A((?'a a+?+l))}
  |               ^ expected one of `)`, `+`, or `,`

error: internal compiler error: unexpected lifetime bound
 --> main.rs:1:11
  |
1 | enum e{A((?'a a+?+l))}
  |           ^^^

thread 'rustc' panicked at 'Box<Any>', <::std::macros::panic macros>:2:4
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.43.0-nightly (58b834344 2020-02-05) running on x86_64-unknown-linux-gnu

error: aborting due to 3 previous errors
```

The error happens on `nightly` and `beta` but not on `stable`.

**Comment by pnkfelix** [comment]
triage : P-medium, removing nomination, adding needs-bisect.

**Comment by pnkfelix** [comment]
(the bisection here would be entirely automatable if https://github.com/rust-lang/cargo-bisect-rustc/issues/34 were addressed.)

**Comment by JohnTitor** [comment]
Bisected roughly: ICE occurred from #67505 but not panicked, panicked from #68034

**Comment by dwrensha** [comment]
#67148 in particular looks suspicious.
cc @Centril

**Comment by dwrensha** [comment]
Pre-#67148, we return early with an error here: https://github.com/rust-lang/rust/blob/c64eecf4d0907095928fb36fd3a1dd5fb2d9ff06/src/librustc_parse/parser/ty.rs#L82

Post-#67148, in the corresponding code happens in a call to `parse_paren_comma_sep`: https://github.com/rust-lang/rust/blob/1ad6b5e1e69ad3d3509abd8c041bb9fb2dd86c41/src/librustc_parse/parser/ty.rs#L197-L201
and the parser "recovers" from the error encountered in `p.parse_ty()?`, allowing this line to be reached: https://github.com/rust-lang/rust/blob/1ad6b5e1e69ad3d3509abd8c041bb9fb2dd86c41/src/librustc_parse/parser/ty.rs#L217.

**Comment by dwrensha** [comment]
I opened #69014, which takes the stance that `span_bug()` is no longer appropriate here.

It's possible that there's a better fix that changes the way `parse_paren_comma_seq()` works, but that would require a deeper expertise of how these things are supposed to work than I currently have.
