### ISSUE TITLE
Cross compiling from x64 Linux to SPARC Solaris

### ISSUE THREAD

**Issue by Michele31415** [rust-lang/rust#68912]
It has been suggested to me that all that is needed to produce a rust compiler for SPARC Solaris is

`x.py --target sparcv9-sun-solaris`

However, this is getting me nowhere:

```
michele@michele-VirtualBox:~/rust$ ./x.py --target sparcv9-sun-solaris
Updating only changed submodules
Submodules updated in 0.04 seconds
    Finished dev [unoptimized] target(s) in 0.16s
Usage: x.py <subcommand> [options] [<paths>...]
...
failed to run: /home/michele/rust/build/bootstrap/debug/bootstrap --target sparcv9-sun-solaris
Build completed unsuccessfully in 0:00:00

I have already done 

$ rustup target add sparcv9-sun-solaris
$ ./configure --host=sparcv9-sun-solaris
```
This is in Ubuntu x64.  What am I doing wrong?

**Comment by Michele31415** [comment]
Anyone?  I'm pretty stuck here.

**Comment by jonas-schievink** [comment]
Is bootstrap not outputting any error? You didn't post one.

**Comment by Michele31415** [comment]
Nope - that was the sum total of the output from the ./x.py command.  I should add I know very little about how any of this works.

**Comment by jonas-schievink** [comment]
Well, on my system `./x.py --target sparcv9-sun-solaris` prints:

```
Usage: x.py <subcommand> [options] [<paths>...]

Subcommands:
    build       Compile either the compiler or libraries
    check       Compile either the compiler or libraries, using cargo check
    clippy      Run clippy (uses rustup/cargo-installed clippy binary)
    fix         Run cargo fix
    fmt         Run rustfmt
    test        Build and run some test suites
    bench       Build and run some benchmarks
    doc         Build documentation
    clean       Clean out build directories
    dist        Build distribution artifacts
    install     Install distribution artifacts

To learn more about a subcommand, run `./x.py <subcommand> -h`

failed to run: /home/jonas/dev/rust-master/build/bootstrap/debug/bootstrap --target sparcv9-sun-solaris
```

which indicates a usage error. Please refer to the rustc guide at https://rust-lang.github.io/rustc-guide/ for how to build the compiler. If you have any further questions, please post them on one of the chat platforms used by the Rust community, such as https://internals.rust-lang.org/.

**Comment by Michele31415** [comment]
OK, thanks!

**Comment by Gillingham** [comment]
> OK, thanks!

Did you ever get a working solution? I'm looking to solve the same problem.

**Comment by Michele31415** [comment]
Yes, I finally got it working.  Unfortunately, I can't remember what exactly I did and I failed to document it.  My bad.  I think the answer must have been in the rustc guide jonas mentioned.  I believe it was indeed some config thing.

**Comment by Michele31415** [comment]
Ah - this is the guide here: https://blog.rust-lang.org/2016/05/13/rustup.html
