### ISSUE TITLE
Rewrite `box_region.rs` to use generator resume arguments

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/rust#68922]
[`box_region.rs`](https://github.com/rust-lang/rust/blob/3d8778d767f0dde6fe2bc9459f21ead8e124d8cb/src/librustc_data_structures/box_region.rs) makes use of generators, and passes arguments into them via thread-local storage. Now that https://github.com/rust-lang/rust/pull/68524 has landed, this can be rewritten to use generator resume arguments instead, which is much cleaner and possibly also faster.

**Comment by bjorn3** [comment]
I can't find any uses of `box_region` anymore: https://github.com/rust-lang/rust/search?q=box_region&unscoped_q=box_region

**Comment by jonas-schievink** [comment]
`src/librustc_interface/passes.rs` uses it via the exported macros
