### ISSUE TITLE
@ bind on enum values does not actually subclass it

### ISSUE THREAD

**Issue by axos88** [rust-lang/rust#68935]
```
enum E {
    Foo(u32),
    Bar(f32)
}


fn foo(e: &mut E) -> &mut E {
    match e {
        a1 @ E::Foo(..) => {
            println!("{}", &a1.0);
            a1
        },
        x => x
    }
}
```

The compiler should know that `a1` is of type `E::Foo`, therefore it has a field `0: u32`, but it only seems to know that `a1` is of type `E`, which doesn't help.

[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=4bfb83f0e4ba02f372f22c425773833c)

**Comment by jonas-schievink** [comment]
`E::Foo` is not a type; https://github.com/rust-lang/rfcs/pull/2593 sets out to change this, so closing in favor of that.

**Comment by ExpHP** [comment]
Correct.  Enum variants are not types.  If you want to accomplish something similar to this, you will need to put structs inside the enums.

```
enum E {
    Foo(EFoo),
    Bar(EBar),
}

struct EFoo(u32);
struct EBar(f32);

fn foo(e: &mut E) -> &mut E {
    match e {
        E::Foo(a1) => {
            println!("{}", &a1.0);
            a1
        },
        x => x
    }
}
```

Substantial changes to the language such as this go through the RFC process.  An RFC that turns enum variants into types was proposed not too long ago, but has not yet been accepted and appears to be waiting for the lang team to have enough bandwidth to consider it.

https://github.com/rust-lang/rfcs/pull/2593

**Comment by axos88** [comment]
Right. I've read about that over a year ago, I thought it had been implemented.
