### ISSUE TITLE
Suspicious lifetime inference.

### ISSUE THREAD

**Issue by crlf0710** [rust-lang/rust#68948]
I'm not sure whether there's a duplicate issue. Currently [this code](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=e3047d23757ed3a9c2672a5f221511b3) doesn't compile:
```rust
pub fn main() {
    let mut s = "s".to_owned();
    let a = &mut s;
    *a += "";
    let b: _ = a;
    *a += "";
}
```
However it seems to me that a new lifetime variable should be introduced by the `_`? Is there any reason behind this current behavior?

@matthewjasper @nikomatsakis

**Comment by matthewjasper** [comment]
I guess that you're expecting it to compile because these do:

```rust
pub fn main() {
    let mut s = "s".to_owned();
    let a = &mut s;
    *a += "";
    let b: _ = &mut *a;
    *a += "";
}


pub fn main_2() {
    let mut s = "s".to_owned();
    let a = &mut s;
    *a += "";
    let b: &mut _ = a;
    *a += "";
}
```

It doesn't compile because reborrows and moves of mutable references are treated differently. It was a breaking change to turn a move into a reborrow with the old borrow checker, so the behavior of rust 1.0 had to be preserved here.

**Comment by crlf0710** [comment]
@matthewjasper 
Is there any case when turning a move into a reborrow introduces any semantic difference for compile-able programs? This is just a builtin reference after all...

**Comment by matthewjasper** [comment]
If both compile then there's no difference between them.

**Comment by nikomatsakis** [comment]
Visiting from compile triage. I believe this is "working as expected" (for better or worse). In particular, since we don't know the type of the variable `b`, we do indeed register this as a *move* of `a`. Closing.
