### ISSUE TITLE
Switch to LLVM{Get,Set}CurrentDebugLocation2.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#68953]
I'm still not fully sure what's going on, but see https://github.com/llvm/llvm-project/commit/cce47418c93bcd178379fa8c4df5c3327bc19802.

We would probably have to polyfill it on versions that don't have those APIs.

**Comment by workingjubilee** [comment]
Done in https://github.com/rust-lang/rust/pull/109862
