### ISSUE TITLE
Incorrect raw identifier variable name help suggestion

### ISSUE THREAD

**Issue by olegnn** [rust-lang/rust#68962]
Incorrect hint for variable with a similar name defined using raw identifiers
```rust
fn main() {
    let r#final = 1;
    r#fina;
}

```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=6214770563a002ca14cd236cc19f14c0))

Errors:

```
   Compiling playground v0.0.1 (/playground)
error[E0425]: cannot find value `fina` in this scope
 --> src/main.rs:3:5
  |
3 |     r#fina;
  |     ^^^^^^ help: a local variable with a similar name exists: `final`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0425`.
error: could not compile `playground`.

To learn more, run the command again with --verbose.

```

Should be `help: a local variable with a similar name exists: r#final`

**Comment by duckymirror** [comment]
@rustbot claim

I've fixed this issue and will try to find and fix more similarly incorrect suggestions before submitting a PR.

**Comment by nouritsu** [comment]
@rustbot claim

I would love to take this up

**Comment by nouritsu** [comment]
Sorry for dropping this, my exams are around the corner.

**Comment by kmpzr** [comment]
Hi @Dylan-DPC, I'm in the middle of the implementation of this issue. Would it be possible to assign it back to me?

**Comment by kmpzr** [comment]
Unfortunately, I'm extremely busy right now, therefore I will unassign me so that someone else can work on it.
