### ISSUE TITLE
Revert `compute_const` changes in WF

### ISSUE THREAD

**Issue by varkor** [rust-lang/rust#68977]
See https://github.com/rust-lang/rust/pull/56723/files/03b892860da5aff7a10cf4ca1364dbcacb95bfcd#r376641987. Opening this issue so I don't forget about it.

cc @eddyb 

This issue has been assigned to @lcnr via [this comment](https://github.com/rust-lang/rust/issues/68977#issuecomment-601381143).

**Comment by eddyb** [comment]
I was trying something out to show @ruabmbua their idea can't work yet and [accidentally came up with something](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=fa05792ce102f9c98901bc4586ed5e42) that compiles even if it shouldn't. I'm pretty sure it's because of this bug.

**Comment by ruabmbua** [comment]
Extended example: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=aa9afdff6a2f23a8f0cc588fdafe4c17

It would be nice, if is possible to build something like that. Even, if it`s not exactly the same.

**Comment by varkor** [comment]
Assigning to myself so I don't forget, but I'm not sure I'll be able to get to this very soon, so if someone else wants to take it, you're welcome to.

**Comment by eddyb** [comment]
WF is also missing something like this for `ty::ConstKind::Infer`: https://github.com/rust-lang/rust/blob/3c6f982cc908aacc39c3ac97f31c989f81cc213c/src/librustc_trait_selection/traits/wf.rs#L556-L593

Fixing this might require `Predicate::WellFormedConst`, which I thought would replace `Predicate::ConstEvaluatable` but now I'm less sure it would.
It shouldn't hurt to have both at once and we can deduplicate if possible later.

The other problem is this needs to add `Predicate::WellFormedConst`s: https://github.com/rust-lang/rust/blob/3c6f982cc908aacc39c3ac97f31c989f81cc213c/src/librustc_typeck/check/mod.rs#L3341-L3348
