### ISSUE TITLE
Consider emitting LLVM DIFile checksums.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#68980]
We already hash the contents of `SourceFile`s to determine whether the file on disk (if it even exists) still has the same contents, across crates.

I came across [LLVM supporting MD5 and SHA1 checksums](https://llvm.org/docs/LangRef.html#difile) for `DIFile`s, and I'm wondering if it could be useful in a similar way - perhaps debuggers would be able to detect changed sources?

cc @michaelwoerister

**Comment by bjorn3** [comment]
> I'm wondering if it could be useful in a similar way - perhaps debuggers would be able to detect changed sources?

Yes, that is the purpose of the hash, see DWARF5 section 6.2.4.1 opcode DW_LNCT_MD5.
