### ISSUE TITLE
Tracking issue for making ASCII ctype inherent methods `const fn`

### ISSUE THREAD

**Issue by ecstatic-morse** [rust-lang/rust#68983]
This is a tracking issue for making the inherent methods introduced in #46077 into `const fn`. This includes all functions listed in #39658 for both `u8` and `char`, namely:

 * `is_ascii_alphabetic`
 * `is_ascii_uppercase`
 * `is_ascii_lowercase`
 * `is_ascii_alphanumeric`
 * `is_ascii_digit`
 * `is_ascii_hexdigit`
 * `is_ascii_punctuation`
 * `is_ascii_graphic`
 * `is_ascii_whitespace`
 * `is_ascii_control` 

The feature gate for the const version of these functions is `#![feature(const_ascii_ctype_on_intrinsics)]`. These cannot be const-stabilized until `#![feature(const_if_match)]` is stable.

**Comment by DemiMarie-parity** [comment]
Could these be implemented by means of a lookup table?

**Comment by ecstatic-morse** [comment]
@DemiMarie-parity Sorry I missed your comment.

They could be, although the generated code would likely be worse than the branchy version. `#![feature(const_if_match)]` is close to being stabilized (see #49146), so I would prefer to wait until that occurs. If it is delayed for some reason, we could revisit.

**Comment by DemiMarie-parity** [comment]
@ecstatic-morse my experience in practice (albeit in Haskell) has been the opposite ― the lookup table is significantly faster.

**Comment by ecstatic-morse** [comment]
You're welcome to try it out. If it is indeed faster, that would be a valuable addition to the standard library. I will point out that the obvious microbenchmark will put the lookup-table in the L1 cache, so it won't be fair unless you're calling these functions in a tight loop. Perhaps that's the most common mode of use?

**Comment by DemiMarie-parity** [comment]
My tests were done several years ago, and indeed involved calling these functions in a tight loop.  I have no idea if that is the most common use, though.

**Comment by ecstatic-morse** [comment]
I think if you were able to demonstrate that a lookup table based approach was faster in rust, the libs team would seriously consider switching to it. I'm not on the libs team, so I don't know how they weight time vs. memory trade-offs such as this.

If you have any questions about writing microbenchmarks in rust, I'm happy to answer them. If you're not interested, consider opening an issue so someone else can look into it. I think it's an idea that's worth testing.

**Comment by m-ou-se** [comment]
Looks like these were already stabilized as const in 1.47. Closing this issue.
