### ISSUE TITLE
about std output

### ISSUE THREAD

**Issue by toop** [rust-lang/rust#69013]
I very like the Rust lang, We strongly hope to add syntax to template output：
fn main(){
   let string  = “test”；
   println!("${string}");
   // "test"
   //or
   println!("{string}");
  // "test"
}

**Comment by memoryruins** [comment]
A RFC for implicit named arguments in formatting macros was accepted in https://github.com/rust-lang/rfcs/pull/2795
Tracking issue  #67984

**Comment by toop** [comment]
![image](https://user-images.githubusercontent.com/1625023/74207350-35e43e00-4cba-11ea-8b61-8577fbe0b6cc.png)

**Comment by memoryruins** [comment]
The feature is not implemented yet :) the best way to stay updated on its progress is to subscribe to the tracking issue.

**Comment by toop** [comment]
OK! Thank U!!! Waiting for updates。
