### ISSUE TITLE
Choose a naming scheme for codegen debuginfo emission.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#69019]
Right now it's a mix of `debuginfo`, `dbg` and `DI`.
(`DIFoo` is how LLVM refers to its debuginfo metadata)

I would prefer if we had something consistent, e.g.:
* go full on DWARF and use `dw` and `Dw` as prefixes, followed by DWARF names (e.g. `DwSubprogram` for a function)
  * easier to refer back to the DWARF spec
  * LLVM already uses mostly DWARF concepts, and other formats, like CodeView, have to convert from that
* do our own thing, using `dbg` and `Dbg`, with names chosen by us (e.g. `DbgFn`)
  * nicer/cleaner in the context of Rust/MIR
  * potentially confusing/annoying to people who are familiar with DWARF or LLVM's approximation of it

Part of the reason I think we should decide now is @bjorn3 has expressed interest in making most of `rustc_codegen_llvm::debuginfo` LLVM-independent, in order to be able to use it in the Cranelift backend to emit DWARF.
A lot of that code is effectively lowering Rust types into DWARF ones, but using LLVM's API to create LLVM metadata nodes instead of directly emitting DWARF.

If we go with the DWARF-based naming I would go as far as to say that everything other than debug locations and variables inside functions, should go into a `rustc_codegen_dwarf` (or just `rustc_dwarf`) crate.

cc @michaelwoerister @nagisa @rust-lang/wg-mir-opt

**Comment by michaelwoerister** [comment]
I'm fine with making the naming consistent. I think I prefer using generic `dbg/Dbg` prefixes instead of Dwarf-specific ones. I guess a non-LLVM backend on Windows would not use DWARF?

**Comment by wesleywiser** [comment]
LLVM on Windows using the msvc toolchain will output [PDBs](https://llvm.org/docs/PDB/index.html).

I think I would also prefer the generic terminology instead of DWARF specific.

**Comment by eddyb** [comment]
> LLVM on Windows using the msvc toolchain will output PDBs.

That's what I meant by `CodeView` FWIW. However, it still exposes that to the IR in DWARF terminology and concepts, and only translates them internally when generating `PDB`s with `CodeView` debuginfo.

> I think I prefer using generic dbg/Dbg prefixes instead of Dwarf-specific ones.

Alright, let's hope the bikesheds won't get too bad.

> I guess a non-LLVM backend on Windows would not use DWARF?

I mean, yes, but it would still have to deal with a DWARF-centric abstraction even if we don't use literally the DWARF names. I guess the case to make here is that we can accomodate such a backend by tweaking the abstraction away from DWARF?

**Comment by michaelwoerister** [comment]
My main reasoning is that debuginfo in the Rust compiler conceptually does not necessarily mean DWARF, so I would prefer a more generic naming scheme (even though I recognize that in practice things are basically modeled after LLVM which in turn uses DWARF-like concepts). 

I don't have strong feelings on this. I just think that there is little that can go wrong when using a more generic naming scheme, while using a dwarf-oriented naming scheme could become unnecessarily confusing if our model is "mostly DWARF but in some cases not quite", etc.

**Comment by eddyb** [comment]
Having added a couple more debuginfo abstractions in in #68965, I think I'm starting to agree more: we can expose few types, which happen to be semantically very distinct (type/scope/variable/location), and leave most of the naming choice to their constructors (e.g. `dbg_scope_fn` instead of `dw_subprogram`).

And I guess that bare minimal support (`-C debuginfo=1`, just mapping from code ranges to source locations) just needs function scopes and locations, so that should transfer well to other debuginfo formats, and everything else can be best-effort.

**Comment by wesleywiser** [comment]
Visited during wg-debugging triage. Cleanups for the compiler in general are always welcome! I'd recommend anyone interested start by deciding what the generic names should be and then opening an [MCP](https://forge.rust-lang.org/compiler/mcp.html) with those names.
