### ISSUE TITLE
"exceeding_bitshifts" lint does not work in associated consts

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#69021]
The `exceeding_bitshifts` lint should fire on the following code, but it does not:
```rust
pub trait Foo {
    const N: i32;
}

impl<T: Foo> Foo for Vec<T> {
    const N: i32 = T::N << 42; // no warning here
}
```
[Playground](https://play.rust-lang.org/?version=nightly&mode=release&edition=2018&gist=11c45c0bd4b22ff997e69901b3bb0709)
(This testcase now exists in-tree as a FIXME in `ui/lint/lint-exceeding-bitshifts.rs`.)

Cc @oli-obk @wesleywiser 

This issue has been assigned to @jumbatm via [this comment](https://github.com/rust-lang/rust/issues/69021#issuecomment-584603723).

**Comment by jumbatm** [comment]
I'd like to take this.

@rustbot claim

**Comment by RalfJung** [comment]
@jumbatm I have some plans to follow-up on https://github.com/rust-lang/rust/pull/68969 with some cleanup. That might at least partially resolve this issue here. So it's probably best to wait until after that is done.

**Comment by RalfJung** [comment]
All right, https://github.com/rust-lang/rust/pull/69185 landed, so what I planned here is done.

The remaining issue is about associated consts. The issue there is that [`check_binary_op`](https://github.com/rust-lang/rust/blob/d9a328a0ade570608717b0df654306a5268c9f46/src/librustc_mir/transform/const_prop.rs#L544) does not even get called (according to `trace!` output). My guess is that one of the conditionals guarding [this line](https://github.com/rust-lang/rust/blob/d9a328a0ade570608717b0df654306a5268c9f46/src/librustc_mir/transform/const_prop.rs#L850) fails, or maybe we are hitting an [early return in `const_prop`](https://github.com/rust-lang/rust/blob/d9a328a0ade570608717b0df654306a5268c9f46/src/librustc_mir/transform/const_prop.rs#L602),  but I have not tried further.

The issue is all yours, @jumbatm :)

**Comment by jumbatm** [comment]
Great! I'll start investigating.

**Comment by RalfJung** [comment]
Possibly related: https://github.com/rust-lang/rust/issues/70660

**Comment by RalfJung** [comment]
https://github.com/rust-lang/rust/pull/70566 got reverted in https://github.com/rust-lang/rust/pull/71533, so we have to reopen this.
