### ISSUE TITLE
Feature request: `swap_retain`

### ISSUE THREAD

**Issue by Lucretiel** [rust-lang/rust#69043]
I'd like to propose a version of `Vec::retain` that operates more efficiently because it doesn't try to preserve the ordering of retained elements, similar to `Vec::swap_remove`. Possible names would be `retain_unordered` or `swap_retain` (for parity with `swap_remove`). A simple implementation would look like this, though there may obviously be more efficient / optimizer-friendly versions:

```rust
fn swap_retain(&mut self, mut pred: impl FnMut(&T) -> bool) {
    for i in 0.. {
        while i < self.len() && !pred(&self[i]) {
            self.swap_remove(i);
        }
    }
}
```

**Comment by nagisa** [comment]
Not obvious if it indeed would be more efficient. Will likely depend on how many elements are in fact being removed. For cases where `pred` is more often true than not, regular `retain` is likely to be more efficient (due to lower memory throughput and more cache locality).

**Comment by Lucretiel** [comment]
> Not obvious if it indeed would be more efficient. Will likely depend on how many elements are in fact being removed. For cases where `pred` is more often true than not, regular `retain` is likely to be more efficient (due to lower memory throughput and more cache locality).

Even in this case, you still have O(N) copies, vs O(MN) right? If you do a regular `retain` call you're still copying the whole tail of the vector every time you need to drop one of the elements.

**Comment by nagisa** [comment]
Algorithmically you are not required to copy the whole tail every time. As you know that the resulting list will be no larger than the initial one, the algorithm can keep 2 pointers: a write head and the read head & just copy from read head to write head as it iterates through the list.

**Comment by Lucretiel** [comment]
Ah, yes, I see your point. So you're trading an O(drops) vs O(tail), where the latter does benefit from cache locality.

**Comment by workingjubilee** [comment]
Implementing a `swap_retain` would betray in the function name what amounts to an implementation detail: how the unstable `retain` is implemented. This function would have to have a name like `unstable_retain`.
