### ISSUE TITLE
Naming Consistency

### ISSUE THREAD

**Issue by ling-zhou** [rust-lang/rust#69087]
We know **Vector** is abbreviated to **Vec**, why isn't **String** abbreviated to **Str**?

About **Reference Counting**, there are **Rc**, **Arc**, and **Weak**, maybe **Wrc** is a better name for **Weak**.

**Comment by jonas-schievink** [comment]
Hi! This issue tracker is mainly meant for bug reports and concrete, small feature requests. Questions like this are better asked in the user forum at https://users.rust-lang.org/ or on [one of the chat platforms](https://www.rust-lang.org/community) used by the Rust community.
