### ISSUE TITLE
Compiler Optimization: Bitfields

### ISSUE THREAD

**Issue by deeprobin** [rust-lang/rust#69093]
# Combine multiple bools to one byte

A [bool](https://doc.rust-lang.org/reference/types/boolean.html) uses one byte of memory.  Why not combine several booleans?  Assuming false is 0 and true 1, you could use the other bits anyway. This is called a [bitfield](https://en.wikipedia.org/wiki/Bit_field). 

## Currently, bools are represented like this:
`0 = true`
`1 = false`

### Double Bool
`0 = false, false`
`1 = false, true`
`2 = true, false`
`3 = true, true`

### Other examples

I once calculated how much you can save with this.
The maximum value of a u8 is 255.

2^2 = 4 (double bool - 2 bools with 4 possibilities)
3^3 = 27 (triple bool - 3 bools with 27 possibilities)
4^4 = 256 (maxed bool - 4 bools with 256 possibilities)

**Comment by jonas-schievink** [comment]
This would make it impossible to take a reference to a `bool` field. If you want a bitfield, use the `bitflags` crate.
