### ISSUE TITLE
Bounds check optimizations are not applied if the accessed slice len is smaller than the upfront checked slice len

### ISSUE THREAD

**Issue by Matthias247** [rust-lang/rust#69101]
When using a loop and checking exact bounds upfront, vectorized instructions are used:

```rust
pub fn xorl(a: &[u8], b: &[u8], c: &mut [u8]) {
    let (a_bound, b_bound, c_bound) = (&a[..1024], &b[..1024], &mut c[..1024]);
    for i in 0..1024 {
        c[i] = a[i] ^ b[i];
    }
}
```
[Godbolt](https://godbolt.org/z/MVajmQ)

However when the upfront checks actually tests for a bigger slice size, the same optimizations are not applied:

```rust
pub fn xorl(a: &[u8], b: &[u8], c: &mut [u8]) {
    let (a_bound, b_bound, c_bound) = (&a[..2048], &b[..2048], &mut c[..2048]);
    for i in 0..1024 {
        c[i] = a[i] ^ b[i];
    }
}
```
[Godbolt](https://godbolt.org/z/CkwKK4)

Since slices of size 2048 are always also at least of size 1024, I would expect the generated code to be equivalent.

### Meta

`rustc --version --verbose`:

Happens on nightly as well as 1.40 - as seen in Godbolt

**Comment by nikic** [comment]
From a quick look, seems like something indvars should be able to handle based on scev. IV dependent condition is known based on loop entry guard.

**Comment by the8472** [comment]
This seems to be fixed with current nightlies.
