### ISSUE TITLE
Implementing `Index<LocalType>` for arrays causes usize indexing to fail.

### ISSUE THREAD

**Issue by rodrimati1992** [rust-lang/rust#69111]
I tried this code:
[link to playground](https://play.rust-lang.org/?version=stable&mode=release&edition=2018&gist=2e8cacc7a57123869d77f2c7cb68ee6c)
```rust

struct One;

impl<T> Index<One> for [T;10] {
    type Output=T;
    fn index(&self,_:One)->&T{
        let this:&[T]=self;
        &this[1]
    }
}

fn main() {
    let array=[0,1,2,3,4,5,6,7,8,9];
    array[1];
}
```

I expected the code to compile without errors.

Instead I got this compiler error:
```
error[E0308]: mismatched types
  --> src/main.rs:15:11
   |
15 |     array[1];
   |           ^ expected struct `One`, found integer
```

It produces the same error for stable beta and nightly.

The `impl<T> Index<One> for [T;10]` impl started being allowed on Rust 1.41,while on Rust 1.40 it prints the expected orphan impl error:
```
error[E0210]: type parameter `T` must be used as the type parameter for some local type (e.g., `MyStruct<T>`)

 --> <source>:5:6

  |

5 | impl<T> Index<One> for [T;10] {

  |      ^ type parameter `T` must be used as the type parameter for some local type

  |

  = note: only traits defined in the current crate can be implemented for a type parameter
```

**Comment by jonas-schievink** [comment]
This is probably expected behavior, since array do not actually implement `Index` (they deref to slices, which do).

**Comment by SimonSapin** [comment]
What most likely happens is that resolving `array[x]` first looks for a `Index<_> for [T; N]` impl. Normally it isn’t found, so the array is first auto-ref’ed to `&[T; N]` and then auto-coerced to a `&[T]` slice, which does have an `Index` impl. However if `Index<One>` is found, it is apparently "selected" and the value `x`’s type is unified with `One`, which fails.

A simple fix would be to add `impl<T, I, const N> Index<I> for [T; N] where I: SliceIndex<[T]>, [T; N]: LengthAtMost32` (and when const generics are stable remove the length bound), and similarly `IndexMut`. As far as I can tell there shouldn’t be negative consequences to doing that.

**Comment by rodrimati1992** [comment]
Fixed by arrays directly implementing the indexing traits in Rust 1.50.0
