### ISSUE TITLE
_modsi3 macros.rs:255 crash on armv7 & armv7s iOS Device

### ISSUE THREAD

**Issue by ronghui1219** [rust-lang/rust#69116]
my library have armv7 & arm64 arch, but some user have crash like this
_modsi3 macros.rs:255
and this crash only occur on armv7 and armv7s Devices, such as iPod5,1 , iPhone 4,1, arm64 is fine
how can i solve this problem?
rustc 1.39.0 (4560ea788 2019-11-04)

**Comment by memoryruins** [comment]
Which library, and does it occur on a current stable 1.41 and/or nightly?
Do you have a log/backtrace of the crash, and what are the steps to reproduce?

**Comment by ronghui1219** [comment]
i will try 1.41.0 next, here is crash log
```log
Incident Identifier: 61310E5F-047A-434A-BD67-B8061AB02B94
CrashReporter Key:   e782652d3e122b4304499124475e8c49b89670da
Hardware Model:      iPhone4,1
Process:             MyApp [6117]
Path:                /var/containers/Bundle/Application/56055860-95D0-4545-ACD0-BF54A78DCD97/MyApp.app/MyApp
Identifier:          HomeController|com.youku.YouKu
Version:             2012619099 (8.4.8)
Code Type:           ARM
Parent Process:      ? [1]
Date/Time:           2020-02-13 19:17:16 +0800
OS Version:          iPhone OS 9.3.6 (13G37)
Report Version:      104
Exception Type:  EXC_BREAKPOINT
Exception Codes: KERN_INVALID_ADDRESS at 0x01ea0d74
Exception Subtype: SIGTRAP
Triggered by Thread:  0
Thread 0 Crashed:
0   MyApp                    0x01ea0d74 _modsi3 macros.rs:255 (in MyApp)
1   MyApp                    0x052d16af -[MyEventManager _fireEvent:] EventManager.m:359 (in MyApp)
```
question is  in `_fireEvent` , it does not invoke any rust code, just objective-c code,  but as crash log, it crash at _modsi3 macros.rs ,  does rust replace iOS own implementation?

**Comment by nagisa** [comment]
> rust replace iOS own implementation?

Not actively. It _does_ have an implementation of this, but generally having two conflicting symbols should result in linking errors, not one implementation being silently called over the other.

This will definitely require investigation on your part _or_ a fairly isolated mcve.

**Comment by ronghui1219** [comment]
> > rust replace iOS own implementation?
> 
> Not actively. It _does_ have an implementation of this, but generally having two conflicting symbols should result in linking errors, not one implementation being silently called over the other.
> 
> This will definitely require investigation on your part _or_ a fairly isolated mcve.

in `-[MyEventManager fireEvent:]` contain a mod  operation ，like this

```objc
//  a  and b is  NSInteger;
...
    a % b
...
```
above code is all Objective-C Code,  it do not contain any rust code or invoke an rust method,  is that possible rust override  % operation ?

**Comment by ronghui1219** [comment]
it seems like iOS orignal implementation through dynamic library, but my rust library is static library, rust library contain __modsi3 ,then the final app only remain rust __modsi3 implementation,  iOS's dynamic library __modsi3  implementation does not link to final App target, is that possible?

**Comment by nagisa** [comment]
> is that possible?

Sure, sounds plausible enough. It might help to link the rust library to your application in a way that does not leak Rust’s code.

**Comment by ronghui1219** [comment]
now i use [HexFiend](https://github.com/ridiculousfish/HexFiend)  directly rename my rust static library  about those fuctions, such as ___modsi3 -> ___rsmod3  etc
and build , link , then i see iOS owned dynamic library about ___modsi3 has been linked in Xcode link map file
i think about this crash, most likely because rust and iOS own implementation is different,  such as 
```objc
     a % b  // when b is 0, rust crash, and iOS own return 0
```
i don not know how to build a rust dynamic library on iOS , so rename maybe a solution, i hope this will no problem ...
