### ISSUE TITLE
Cannot compiling from source

### ISSUE THREAD

**Issue by paledega** [rust-lang/rust#69124]
![Screenshot_2020-02-13_09-16-19](https://user-images.githubusercontent.com/38860643/74419250-8508ab00-4e41-11ea-9666-cc34f7ca7996.png)

**Comment by jonas-schievink** [comment]
How did you obtain the source code?

**Comment by paledega** [comment]
![Screenshot_2020-02-13_13-37-00](https://user-images.githubusercontent.com/38860643/74440433-ed698380-4e65-11ea-9a1d-5691478a9c9e.png)

**Comment by paledega** [comment]
https://github.com/rust-lang/rust/archive/1.41.0.tar.gz

**Comment by paledega** [comment]
I need rust for compiling librsvg

**Comment by paledega** [comment]
https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/rust

I tried this PKGBUILD. same issue

**Comment by Patryk27** [comment]
Seems like you don't really need to compile the entire `rustc` by yourself - why don't you just [download pre-compiled binaries](https://rustup.rs/)? :-)

**Comment by paledega** [comment]
I wanna compile. I dont wanna use 3. party script

**Comment by paledega** [comment]
@Patryk27 do you know any solve?

**Comment by Patryk27** [comment]
Well, if you want to build it... did you try following [the instructions](https://rust-lang.github.io/rustc-guide/building/how-to-build-and-run.html)?

**Comment by jonas-schievink** [comment]
@paledega rustup is not a third-party script, it is the official recommended installer for Rust.
