### ISSUE TITLE
Add `rust objdump` or `rust dis` for dissecting / disassembling generated libraries

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#6912]
We may or may not already have `objdump` like facilities available, but I do not see them in the help text for `rust`.

There *is* a small inspection facility in `rustc`: `rustc --ls <library-crate>`.  This just scratches the surface of what I might want to see, though.

I also see `rustc::metadata::creader::dump_crates`, but I do not think that is a real disassembler either.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#652
