### ISSUE TITLE
LLVM globals corresponding to miri allocations should be named alloc123.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#69134]
That is, if `-Zfewer-names` is `false` (usually only because of `--emit=llvm-ir`), we should use the same name for LLVM globals we generate out of miri allocs as #67133 does in MIR output (`allocN`).

This way, we can easily see the mapping between MIR and LLVM IR (and it shouldn't be any costlier for regular compilation, which would continue to use unnamed globals).

Relevant code (btw this could probably use extra caching keyed on `AllocId`?):
https://github.com/rust-lang/rust/blob/be493fe8cc40c3d3f6030a1313c1ff747fce770d/src/librustc_codegen_llvm/common.rs#L260-L267

cc @rust-lang/wg-mir-opt @bjorn3 

This issue has been assigned to @chrissimpkins via [this comment](https://github.com/rust-lang/rust/issues/69134#issuecomment-586080842).

**Comment by oli-obk** [comment]
Kinda vague instructions:

1. Replace the `None` for the `static_addr_of_mut` and `static_addr_of` call with a `Some` by creating the name via `ptr.alloc_id.to_string()`.
2. Run all codegen tests and adjust them as necessary.

**Comment by chrissimpkins** [comment]
https://github.com/rust-lang/rust/pull/69155

Mind having a look at the updated checks?  They pass on local stage 1 tests, but I can't verify that they are valid expected values.

**Comment by kumar4467** [comment]
[Great and osam](https://www.beautifulbirthdayimage.com/)

In this having like good and the updated check information. you pass local test i can't verify that they are vaild

**Comment by chrissimpkins** [comment]
merged to master
