### ISSUE TITLE
Absolute path to *.pdb in the binary file

### ISSUE THREAD

**Issue by afonichev** [rust-lang/rust#69143]
Can it be removed somehow?

![image](https://user-images.githubusercontent.com/15726637/74473503-c5554100-4eb4-11ea-89c4-bb3f97225054.png)

**Comment by nagisa** [comment]
This is a tracker for the issues in rustc. For support, consider posting your question on [users.rlo](https://users.rust-lang.org/), [stackoverflow](https://stackoverflow.com/), [reddit](https://www.reddit.com/r/rust/), or asking on one of the chat platforms: [discord](https://discordapp.com/invite/aVESxV8) or [zulip](https://rust-lang.zulipchat.com/#).

---

That said, does `--remap-path-prefix` help?

**Comment by ollie27** [comment]
The [`/PDBALTPATH`](https://docs.microsoft.com/en-us/cpp/build/reference/pdbaltpath-use-alternate-pdb-path?view=vs-2019) linker argument controls this path. For example `/PDBALTPATH:%_PDB%` will cause only `demo.pdb` to be embedded in the binary.

Closing this issue as it's not really the right place to ask questions anyway.
