### ISSUE TITLE
rustdoc: Hide the "Show hidden undocumented items"

### ISSUE THREAD

**Issue by tesuji** [rust-lang/rust#69160]
I enabled in "Auto-hide trait implementations documentation" feature in Settings.
But the "Show hidden undocumented items" strings still displays and it is quite distracting to me:
![image](https://user-images.githubusercontent.com/15225902/74510822-258cc700-4f37-11ea-9c42-ae6f24505757.png)

It would be nice if it hide those strings completely by default.

Note: The screenshot was taken from <https://doc.rust-lang.org/nightly/std/str/pattern/trait.Searcher.html#implementors>.

**Comment by GuillaumeGomez** [comment]
It shouldn't appear in this case so this is a bug. Thanks for reporting it!

**Comment by GuillaumeGomez** [comment]
We don't show the implementors' items anymore so this is not relevant anymore.
