### ISSUE TITLE
Rust incorrectly reports common code in examples as dead code

### ISSUE THREAD

**Issue by suhr** [rust-lang/rust#69170]
There is the `examples` dir: https://github.com/suhr/tox/tree/async/examples

**Expected behavior:** the function [`as_packed_node`](https://github.com/suhr/tox/blob/async/examples/common/mod.rs#L46) should not be reported as dead code, because:

- It's `pub`
- It is used in examples (for example, [here](https://github.com/suhr/tox/blob/async/examples/dht_server.rs#L49))

**Actual behavior:** the function `as_packed_node` is reported as dead code.

Rust versions where the bug occurs: 1.39.0, 1.41.0.

UPDATE: fixed wrong usage link

**Comment by jonas-schievink** [comment]
> It is used in examples (for example, [here](https://github.com/suhr/tox/blob/async/examples/common/mod.rs#L46))

That link points to the function definition

**Comment by suhr** [comment]
Oops, fixed.

**Comment by jonas-schievink** [comment]
This looks like expected behavior, since you're including the `common` module in every test (via `mod common;`). The [echo](https://github.com/suhr/tox/blob/async/examples/echo.rs) test doesn't use it, so it gets the warning.

**Comment by suhr** [comment]
I see. So each example imports module `common` independently. But the `echo` test uses other definition from `common`.

Maybe this behavior is expected, but it is *confusing* for sure.
