### ISSUE TITLE
[Unstable Book] The `compiler_builtins_lib` apparently doesn't even exist any more.

### ISSUE THREAD

**Issue by Lokathor** [rust-lang/rust#69177]
The Unstable Book entry on [how to build a `no_std` binary](https://doc.rust-lang.org/unstable-book/language-features/lang-items.html#writing-an-executable-without-stdlib) says that you need to use the `compiler_builtins` crate if you get specific kinds of linker errors about missing intrinsics. This is true.

It then points you to the [compiler_builtins_lib](https://doc.rust-lang.org/unstable-book/library-features/compiler-builtins-lib.html) feature as the way to access that crate. This is apparently wrong, because `rustc 1.42.0-nightly (9ed29b6ff 2020-01-29)` claims that there is no such feature at all.

However, the readme for the `compiler_builtins` crate [tells you how and when to use the crate](https://github.com/rust-lang/compiler-builtins#when-and-how-to-use-this-crate). It says to just add the git link and an `extern crate compiler_builtins;` and no lang feature. On Linux x86_64 GNU (but not MUSL) this seems to work, though it's easy to also then get [multiple definition errors](https://github.com/rust-lang/compiler-builtins/issues/336), and that seems to be fixed by setting `codegen-units=1`.

Anyway there's no `compiler_builtins_lib` feature so that page should probably go away.

**Comment by JohnTitor** [comment]
`compiler_builtins_lib` feature lives on that crate, see this comment:

https://github.com/rust-lang/rust/blob/e2223c94bf433fc38234d1303e88cbaf14755863/src/tools/tidy/src/unstable_book.rs#L82-L94

But we could improve the doc to avoid confusion.

**Comment by Lokathor** [comment]
So the feature can be activated **only** if you already also include the crate in your build graph?

**Comment by JohnTitor** [comment]
I think so.
And I noticed the nightly book removed the doc: b8ccc0f8a60ac16fdc00f4b2e36e1a5db8b78295. So this can be closed?

**Comment by Lokathor** [comment]
Seems that way,  closing.

**Comment by Lokathor** [comment]
Wait wait wait, that PR is from months ago. The current version of the book as published still has incorrect text. It could be as simple as needing to re-publish the website or something, but this issue is still valid for now.

**Comment by JohnTitor** [comment]
It's just not reached to stable. You can see beta or nightly doc: https://doc.rust-lang.org/nightly/unstable-book/library-features/compiler-builtins-lib.html

**Comment by Lokathor** [comment]
Okay, so the book has a release cadence too.
