### ISSUE TITLE
Significant performance regression on the `encoding` benchmark

### ISSUE THREAD

**Issue by ecstatic-morse** [rust-lang/rust#69197]
#69144 (a rollup)  slowed down check builds of the `encoding` benchmark considerably, see the [task-clock measurements](https://perf.rust-lang.org/compare.html?start=d538b80ad77949e46989cd355cdec193b574f052&end=10104085e4f9f52f405fa1cc5e5e18c4c4cc72d1&stat=task-clock). This degradation has been consistent over the last half-dozen perf runs, so it is not spurious. The following candidates have non-trivial changes to the parts of the compiler that are run during a check build.

* #68728 (parse: merge fn syntax + cleanup item parsing)
* #68938 (fix lifetime shadowing check in GATs) **unlikely**
* #69057 (expand: misc cleanups and simplifications)
* #69108 (Use HirId in TraitCandidate.) **ruled out by #69199**
* #69126 (miri: fix exact_div) **unlikely**

I doubt it is #68938 or #69126 so cc @Centril @cjgillot

**Comment by Centril** [comment]
https://github.com/rust-lang/rust/pull/69057 is mostly a pure refactoring so it seems unlikely?

**Comment by Centril** [comment]
Besides changes in https://github.com/rust-lang/rust/pull/68728/files#diff-f5c049612f32b4eda9adb5019ab10a83, nothing pops out in the parsing PR either.

**Comment by ecstatic-morse** [comment]
Ruled out #69108 via perf results from #69199, so it's likely the big one (#68728) cc @Centril @petrochenkov.

**Comment by ecstatic-morse** [comment]
Some perf builds [around the regression](https://perf.rust-lang.org/index.html?start=7cba853b4f6080bf7831169fe5632ec9b6833242&end=&absolute=true&stat=task-clock#chart-top-outer-container-encoding-check) were stuck in the queue when I posted this, so it may not be #69144.

**Comment by pnkfelix** [comment]
nominating for discussion at meeting for prioritization.

**Comment by pnkfelix** [comment]
[discussed](https://zulip-archive.rust-lang.org/131828tcompiler/74090weeklymeeting2020022054818.html#188650785) at T-compiler meeting. P-high. Removing nomination.

**Comment by ecstatic-morse** [comment]
A significant component of the task-clock measurements for check builds of `encoding` and to a lesser extent `inflate` is the time taken to write a large number of warnings to `stderr`. I believe this is because error messages are written directly to `io::Stderr` which does not buffer, which is supported by the perf results in #69227. Although there's a lot of variance, older nightlies appear to spend less time doing system calls than current ones, which could suggest that changes to diagnostics or diagnostics reporting could be the root cause.

Roughly the same number of errors are reported in old (end of 2019) nightlies as recent ones (~1900 lines output to `stderr`). However, earlier nightlies use many *more* calls to `write(2, ...)` to accomplish this (3500 vs 720). Given this, I would assume that the earlier nightlies would be *slower* than the current ones on the encoding benchmark, not faster. Perhaps someone else is more knowledgable.

**Comment by ecstatic-morse** [comment]
After #69227, the `task-clock` measurements for `encoding-check` are [back to normal](https://perf.rust-lang.org/?start=&end=&absolute=true&stat=task-clock#chart-top-outer-container-encoding-check). I think we should close this, although I wish I had a better idea of when/why the regression occurred.

**Comment by mati865** [comment]
Looking at https://perf.rust-lang.org/compare.html?start=d538b80ad77949e46989cd355cdec193b574f052&end=5d04ce67fd14538d03fa47a2598f80d49fd564c6&stat=task-clock there is only one PR (and also included in perf link you posted in OP): https://github.com/rust-lang/rust/pull/68406

**Comment by ecstatic-morse** [comment]
@mati865 How would that PR cause regressions in check builds? And why would the regression appear in only one crate?

**Comment by mati865** [comment]
No idea, that's what perf shows 🤷‍♂

**Comment by pnkfelix** [comment]
closing as resolved by PR  #69227
