### ISSUE TITLE
beta regression: $crate may not be imported

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#69190]
Number of crates regressed: 26

Looks like essentially all the regressions come from a piston2d-gfx_graphics macro. Bisecting this may be helpful, not sure.

cc @petrochenkov 

<details>

- [`ThePianoDentist/rusty-dota-manager`](https://crater-reports.s3.amazonaws.com/beta-1.42-rustdoc-1/beta-2020-02-05/gh/ThePianoDentist.rusty-dota-manager/log.txt)
- [`XavilPergis/rusty-tiles`](https://crater-reports.s3.amazonaws.com/beta-1.42-rustdoc-1/beta-2020-02-05/gh/XavilPergis.rusty-tiles/log.txt)
- [`bluecereal/a_game`](https://crater-reports.s3.amazonaws.com/beta-1.42-rustdoc-1/beta-2020-02-05/gh/bluecereal.a_game/log.txt)
- [`bluecereal/mvp_transform`](https://crater-reports.s3.amazonaws.com/beta-1.42-rustdoc-1/beta-2020-02-05/gh/bluecereal.mvp_transform/log.txt)
- [`bluecereal/oop_gfx_test`](https://crater-reports.s3.amazonaws.com/beta-1.42-rustdoc-1/beta-2020-02-05/gh/bluecereal.oop_gfx_test/log.txt)
- [`bluecereal/transform`](https://crater-reports.s3.amazonaws.com/beta-1.42-rustdoc-1/beta-2020-02-05/gh/bluecereal.transform/log.txt)
- [`bluecereal/using_math_lib`](https://crater-reports.s3.amazonaws.com/beta-1.42-rustdoc-1/beta-2020-02-05/gh/bluecereal.using_math_lib/log.txt)
- [`carols10cents/color-game`](https://crater-reports.s3.amazonaws.com/beta-1.42-rustdoc-1/beta-2020-02-05/gh/carols10cents.color-game/log.txt)
- [`chip8-rust/chip8-ui`](https://crater-reports.s3.amazonaws.com/beta-1.42-rustdoc-1/beta-2020-02-05/gh/chip8-rust.chip8-ui/log.txt)
- [`despawnerer/piston-tutorial`](https://crater-reports.s3.amazonaws.com/beta-1.42-rustdoc-1/beta-2020-02-05/gh/despawnerer.piston-tutorial/log.txt)
- [`echochamber/rust_spin_wheel`](https://crater-reports.s3.amazonaws.com/beta-1.42-rustdoc-1/beta-2020-02-05/gh/echochamber.rust_spin_wheel/log.txt)
- [`edigiacomo/snake-rust`](https://crater-reports.s3.amazonaws.com/beta-1.42-rustdoc-1/beta-2020-02-05/gh/edigiacomo.snake-rust/log.txt)
- [`fabiosantoscode/life`](https://crater-reports.s3.amazonaws.com/beta-1.42-rustdoc-1/beta-2020-02-05/gh/fabiosantoscode.life/log.txt)
- [`jakmeier/cheer-them-up`](https://crater-reports.s3.amazonaws.com/beta-1.42-rustdoc-1/beta-2020-02-05/gh/jakmeier.cheer-them-up/log.txt)
- [`jakmeier/rusty-shortest-path-map-inspector`](https://crater-reports.s3.amazonaws.com/beta-1.42-rustdoc-1/beta-2020-02-05/gh/jakmeier.rusty-shortest-path-map-inspector/log.txt)
- [`jjjjw/rust_elmish_rocket`](https://crater-reports.s3.amazonaws.com/beta-1.42-rustdoc-1/beta-2020-02-05/gh/jjjjw.rust_elmish_rocket/log.txt)
- [`kamicut/rust-fractal-experiments`](https://crater-reports.s3.amazonaws.com/beta-1.42-rustdoc-1/beta-2020-02-05/gh/kamicut.rust-fractal-experiments/log.txt)
- [`mattkuo/rusty-chips`](https://crater-reports.s3.amazonaws.com/beta-1.42-rustdoc-1/beta-2020-02-05/gh/mattkuo.rusty-chips/log.txt)
- [`nbez/0.1.0`](https://crater-reports.s3.amazonaws.com/beta-1.42-1/beta-2020-02-05/reg/nbez-0.1.0/log.txt)
- [`pierrechevalier83/mengner`](https://crater-reports.s3.amazonaws.com/beta-1.42-rustdoc-1/beta-2020-02-05/gh/pierrechevalier83.mengner/log.txt)
- [`piston-opengex/0.6.0`](https://crater-reports.s3.amazonaws.com/beta-1.42-1/beta-2020-02-05/reg/piston-opengex-0.6.0/log.txt)
- [`robinwhittleton/life_rs`](https://crater-reports.s3.amazonaws.com/beta-1.42-rustdoc-1/beta-2020-02-05/gh/robinwhittleton.life_rs/log.txt)
- [`shmutalov/tick-tack-toe-killer-rs`](https://crater-reports.s3.amazonaws.com/beta-1.42-rustdoc-1/beta-2020-02-05/gh/shmutalov.tick-tack-toe-killer-rs/log.txt)
- [`sumproxy/tetris_tmp`](https://crater-reports.s3.amazonaws.com/beta-1.42-rustdoc-1/beta-2020-02-05/gh/sumproxy.tetris_tmp/log.txt)
- [`whodidthis/gfx-rs-testing`](https://crater-reports.s3.amazonaws.com/beta-1.42-rustdoc-1/beta-2020-02-05/gh/whodidthis.gfx-rs-testing/log.txt)
- [`yeliknewo/souls`](https://crater-reports.s3.amazonaws.com/beta-1.42-rustdoc-1/beta-2020-02-05/gh/yeliknewo.souls/log.txt)

</details>

**Comment by petrochenkov** [comment]
Introduced in https://github.com/rust-lang/rust/pull/67775 ("Make "use $crate" a hard error ").

**Comment by Mark-Simulacrum** [comment]
Looks like probably expected breakage -- fallout is not too big, essentially just one root crate. Would be good to figure out if there's a fixed release of said crate that crater didn't pick up, or try to get the crate maintainer to do so. https://github.com/rust-lang/rust/issues/37390 is the compatibility lint tracking issue.

**Comment by pnkfelix** [comment]
expected breakage.

I think the main work item here would be to make sure that the crate in question has a version people can upgrade to, so that they can at least address this in response to the 1.42.0 release.

**Comment by pnkfelix** [comment]
triage: P-high to confirm that there is an upgrade path for piston2d-gfx_graphics (potentially a 0.27.1, or maybe just relying on their existing versions)

**Comment by pnkfelix** [comment]
Upgrading  `piston2d-gfx_graphics` from 0.27 to 0.30 seems to do the trick.

The actual problem originates in a macro defined in a dependency (the `gfx` crate itself).

**Comment by pnkfelix** [comment]
Closing as expected fallout from the conversion to a hard error.
