### ISSUE TITLE
Error 126 while loading DLL compiled by Rust (as a cdylib) on Windows

### ISSUE THREAD

**Issue by silverweed** [rust-lang/rust#69207]
**Note:** looks very similar to #33842, but I'm opening a new issue since that is closed and old.

Basically I'm having the same issue here. [This](https://github.com/silverweed/ecsde) is my project which has 3 crates: one static lib, one dynamic lib (cdylib) and an executable. 
The dynamic lib (ecs_game) depends on the static lib (ecs_engine) and gets compiled into a single DLL. The executable (ecs_runner) then loads the DLL dynamically (I'm using the `libloading` crate for that).
Here is what happens:
- on Linux/Mac, the lib gets loaded just fine
- on an old (pre-anniversary update) Windows, it gets loaded just fine
- on newer Windows installations, it fails with error 126.

I also tried to create a small C program that uses `LoadLibraryA` directly to load the library and it gives the same exact error.
Am I doing something wrong here?

(this is the C loader:)

```c
#include <windows.h>
#include <stdio.h>

int main() {
	HMODULE lib = LoadLibraryA("ecsde/target/release/ecs_game.dll");
	if (lib) {
		printf("Hurray!\n");
	} else {
		DWORD last_err = GetLastError();
		printf("Failed to load. Last err = %d\n", last_err);
	}
}
```

Note that if I link the DLL at link-time, it works fine. It's just dynamic loading that gives problems.

**Comment by retep998** [comment]
Error 126 for reference is `ERROR_MOD_NOT_FOUND`.

Are you certain that you build and run the program in the same *exact* way between older and newer Windows? The slightest difference can easily cause this.

**Comment by silverweed** [comment]
@retep998 I just found out that on my older Windows it only succeeds if I run the program with `cargo run`: launching the executable directly (e.g. from powershell or git bash) yields the same error 126.

**Comment by retep998** [comment]
Why are there so many `???` in that output? Is `ldd` just really bad?

If you have VC++ I recommend doing `dumpbin /dependents foo.dll` to get DLL dependencies.

My current guess is that you're depending on some C library being provided by one of the crates you depend on, and it succeeds when you run it in a way such that it can be found and it fails otherwise. `cargo run` succeeding whereas running the executable directly failing is the biggest tip off.

**Comment by silverweed** [comment]
Thanks for the help you're giving. I'm a windows newbie, so I am quite disoriented when it comes to troubleshooting this kind of stuff there :S
I ran the command and this is the output (on the older install):
```
Microsoft (R) COFF/PE Dumper Version 14.16.27025.1
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file ecs_game.dll

File Type: DLL

  Image has the following dependencies:

    csfml-graphics-2.dll
    csfml-audio-2.dll
    csfml-window-2.dll
    KERNEL32.dll
    ADVAPI32.dll
    VCRUNTIME140.dll
    api-ms-win-crt-math-l1-1-0.dll
    api-ms-win-crt-string-l1-1-0.dll
    api-ms-win-crt-runtime-l1-1-0.dll
    api-ms-win-crt-heap-l1-1-0.dll

  Summary

        1000 .data
       30000 .pdata
       6B000 .rdata
        1000 .reloc
      211000 .text
```

I guess the most likely culprit here are the csfml libs, which are the only non-system ones.

**Comment by fzyzcjy** [comment]
@silverweed Hi, I am having the same problem. How did you solve it? Thanks!

**Comment by silverweed** [comment]
@fzyzcjy Hello, I just copied the DLLs in the executable directory so it could find them when calling LoadLibrary.
