### ISSUE TITLE
Binaries aren't Libraries

### ISSUE THREAD

**Issue by gilescope** [rust-lang/rust#69206]
Any code in a bin is not callable from any other rust crate.

As soon as a binary gets non-trivial in size you have to switch it over to being a lib and have a binary call into that library. .NET had exactly the same setup for a few years and then they made EXEs be libraries as well as being executables. This meant we could write tests against them just like they were a library. And the issue went away. People didn't feel forced to restructure their code.

For a real life example, there's lots of functionality in diesel cli that we'd like to call programmatically but as it's a bin we can't. We'd have to refactor a lot of that functionality into a lib and then have the bin call that.

At the moment I warn people off doing `cargo new hello_world` and suggest they do `cargo new --lib hello_world` and add a `src/bin/hello_world.rs` because there's almost no point starting with a bin.

Maybe it's a little controversial raising this as a bug, but I've come to the conclusion that it is a bug not a feature. .Net saw it as a usability limitation and they fixed it. If it's technically possible to fix, I think this would provide a smoother experience and remove arbitrary distinctions that don't need to be there.

**Comment by Mark-Simulacrum** [comment]
Any change here would need to be an RFC, I think, so closing in favor of that process.

**Comment by gilescope** [comment]
Okay, will try a pre-rfc on the internals and see if there are takers.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
