### ISSUE TITLE
Incorrect `lifetimes in impl Trait types in bindings are not currently supported` error in latest nightly

### ISSUE THREAD

**Issue by olegnn** [rust-lang/rust#69238]
rustc 1.43.0-nightly (5e7af4669 2020-02-16)

`futures-rs` tests (https://travis-ci.com/rust-lang/futures-rs/jobs/288109824#L1073) now fail on nightly with
```
error: lifetimes in impl Trait types in bindings are not currently supported
  --> src/compat/compat01as03.rs:390:13
   |
12 | let reader: impl tokio_io::AsyncRead = std::io::Cursor::new(input);
   |             ^^^^^^^^^^^^^^^^^^^^^^^^
```
However it worked before and there's no lifetimes in binding.

**Comment by Centril** [comment]
cc @matthewjasper

**Comment by matthewjasper** [comment]
The lifetime being referred to is in the concrete type. This is working as currently intended.
