### ISSUE TITLE
Improve ?Sized diagnostics

### ISSUE THREAD

**Issue by mgattozzi** [rust-lang/rust#69243]
Context: https://twitter.com/mgattozzi/status/1229477994961494021

A way to improve the diagnostics when suggesting to relax trait bounds with ?Sized is to show how one would use it on a struct/fn with their code rather than just suggesting it, making it easier for newer people, or those first encountering the issue to more clearly understand how this works.

cc/ @estebank

**Comment by LeSeulArtichaut** [comment]
What about having a separate error code, so that `--explain` can give details about DSTs?

**Comment by estebank** [comment]
I think that we get 80% there by using `span_suggestion_verbose` instead of `span_suggestion` and an extra 10% by adding a note explaining a bit of this. The last 10% would be a specific error code, but we have shied away from replacing `E0277`s in the past.
