### ISSUE TITLE
Incorrect `this block is empty, you might have not meant to close it` on any channel

### ISSUE THREAD

**Issue by olegnn** [rust-lang/rust#69259]
Any code which has correct `()` and incorrect braces like `f)` after them will produce incorrect `this block is empty, you might have not meant to close it` which will point at the valid parentheses. This behaviour is the same on all channels.
```rust
fn main() {}

fn f) {}
```

([Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=e1c8a9c2395232687c7da75078ce58ac))

Errors:

```
   Compiling playground v0.0.1 (/playground)
error: unexpected closing delimiter: `)`
 --> src/main.rs:3:5
  |
1 | fn main() {}
  |        -- this block is empty, you might have not meant to close it
2 | 
3 | fn f) {}
  |     ^ unexpected closing delimiter

error: aborting due to previous error

error: could not compile `playground`.

To learn more, run the command again with --verbose.

```

**Comment by olegnn** [comment]
Related: https://github.com/rust-lang/rust/issues/68987. It looks like it will incorrectly point to last valid block of any kind of braces.

**Comment by steffahn** [comment]
The message changed, but it is still weird:
```
   Compiling playground v0.0.1 (/playground)
error: unexpected closing delimiter: `)`
 --> src/main.rs:3:5
  |
1 | fn main() {}
  |           -- ...matches this closing brace
  |           |
  |           this opening brace...
2 | 
3 | fn f) {}
  |     ^ unexpected closing delimiter

error: aborting due to previous error

error: could not compile `playground`.

To learn more, run the command again with --verbose.
```

Why should I care about those matching braces? Compiler might as well also tell me that `1+1=2`.
