### ISSUE TITLE
OpenOptions: create() and create_new() are flip flopped

### ISSUE THREAD

**Issue by JesterOrNot** [rust-lang/rust#69254]
I tried this code:

```rust
OpenOptions::new()
        .write(true)
        .create(true)
        .open(&args.target)
```
and it creates a file even if it already exists
```rust
OpenOptions::new()
        .write(true)
        .create_new(true)
        .open(&args.target)
```
This code creates a file only if the file does not exist

But look at the docs
For create()
![image](https://user-images.githubusercontent.com/50386709/74699309-f9d34080-51c5-11ea-802e-d650b3bb5d5c.png)

For create_new()
![image](https://user-images.githubusercontent.com/50386709/74699335-0a83b680-51c6-11ea-97c8-0ea32f4d66c4.png)

I expected to see this happen: *explanation*
The functions to match their docs
Instead, this happened: *explanation*
They each do what the other is described to do
### Meta

`rustc --version --verbose`:
```
rustc 1.41.0 (5e1a79984 2020-01-27)
binary: rustc
commit-hash: 5e1a799842ba6ed4a57e91f7ab9435947482f7d8
commit-date: 2020-01-27
host: x86_64-unknown-linux-gnu
release: 1.41.0
LLVM version: 9.0
```

<details><summary>Backtrace</summary>
<p>

```
gitpod /workspace/nushell $ RUST_BACKTRACE=1 cargo build
   Compiling nu v0.9.1 (/workspace/nushell)
    Finished dev [unoptimized + debuginfo] target(s) in 26.35s
```
</p>
</details>

**Comment by jumbatm** [comment]
This appears to be a doc issue, not a library bug.

In RFC 1252 `expand_open_options`, it says  [`create` should open an existing file, or create a new file if it does not already exist](https://github.com/rust-lang/rfcs/blob/master/text/1252-open-options.md#create), and [`create_new` should open a new file, failing if it doesn't exist](https://github.com/rust-lang/rfcs/blob/master/text/1252-open-options.md#create_new), which is consistent with the observed behaviour. I believe the current wording is a bit ambiguous, though.

cc @pitdicker

@rustbot modify labels to +T-doc
