### ISSUE TITLE
librustc_span has a concurrency bug

### ISSUE THREAD

**Issue by kdy1** [rust-lang/rust#69261]
librustc_span contains a concurrency bug. Even though, rustc works without any problem.
(I guess rustc process does not use multiples threads to load file to sourcemap.)

https://github.com/rust-lang/rust/blob/0176a9eef845e7421b7e2f7ef015333a41a7c027/src/librustc_span/source_map.rs#L216-L261

When multiple threads invoked this method at a time, it results in overlapping spans. 
(Because the lock is released while analyzing the source file)

### Meta
Simple fix: https://github.com/swc-project/swc/pull/672/files#diff-8d69cef1163ff9667c130830b15da62bL181-L188

**Comment by Mark-Simulacrum** [comment]
cc @Zoxc
