### ISSUE TITLE
unknown `-Z` flag specified: macro-backtrace

### ISSUE THREAD

**Issue by samuela** [rust-lang/rust#69267]
I tried running `cargo test` on https://github.com/graphql-rust/juniper at 547cf3e:

```
$ cargo test
...
error[E0432]: unresolved import `futures`
  --> integration_tests/juniper_tests/src/issue_398.rs:39:1
   |
39 | #[juniper::graphql_object]
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^ use of undeclared type or module `futures`
   |
   = note: this error originates in an attribute macro (in Nightly builds, run with -Z macro-backtrace for more info)
...
```

So then I tried:
```
❯ cargo +nightly test -Z macro-backtrace
error: unknown `-Z` flag specified: macro-backtrace
❯ cargo +nightly -Z macro-backtrace test
error: unknown `-Z` flag specified: macro-backtrace
❯ cargo -Z macro-backtrace +nightly test
error: unknown `-Z` flag specified: macro-backtrace
```

I expected to see this happen: The `-Z macro-backtrace` flag to work.

Instead, this happened: Got an error that there was no such option.

### Meta

`rustc --version --verbose`:
```
rustc 1.43.0-nightly (0176a9eef 2020-02-17)
binary: rustc
commit-hash: 0176a9eef845e7421b7e2f7ef015333a41a7c027
commit-date: 2020-02-17
host: x86_64-apple-darwin
release: 1.43.0-nightly
LLVM version: 9.0
```

<details><summary>Backtrace</summary>
<p>

```
❯ RUST_BACKTRACE=1 cargo +nightly test -Z macro-backtrace
error: unknown `-Z` flag specified: macro-backtrace
```

</p>
</details>

**Comment by jonas-schievink** [comment]
You're passing the flag to Cargo, it's a rustc flag

**Comment by samuela** [comment]
Can we improve this error message then? What should the right invocation be?

**Comment by samuela** [comment]
Eg.
```
❯ rustc -Z macro-backtrace
error: no input filename given
❯ cargo rustc -Z macro-backtrace
error: unknown `-Z` flag specified: macro-backtrace
```

**Comment by heckad** [comment]
> You're passing the flag to Cargo, it's a rustc flag

How to pass this flag to compiler throw `cargo run` command?

**Comment by wez** [comment]
This is a pretty terrible UX wart.  The error message gives advice that does not work.  Can this be re-opened and re-assessed?
I feel like the error message should give clearer directions, as the current state is very frustrating.

FWIW, I believe this is a way to pass these flags down:

```
RUSTFLAGS="-Z macro-backtrace" cargo test
```

**Comment by wez** [comment]
At this point I think it would get more visibility to open a new issue that references this
