### ISSUE TITLE
rustdoc: use remap-path-prefix

### ISSUE THREAD

**Issue by nmattia** [rust-lang/rust#69264]
The rust compiler has an option `--remap-path-prefix` for remapping path prefixes. It's useful to avoid runtime messages that are independent of where the source code was located during the build.

As far as I can tell that doesn't apply to `rustdoc`'s `<meta>` info "Source to the Rust file ...", which (to me) is unexpected.

### Meta

```
$ rustc --version --verbose
rustc 1.40.0
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-apple-darwin
release: 1.40.0
LLVM version: 8.0
```

**Comment by jyn514** [comment]
This should be fixed since https://github.com/rust-lang/rust/pull/83813/files#diff-04002bbcf90fc0a3356db4344dee8f1e03d868fa6c0f666713affa7fa2679b6f, I don't think it's tested through.

**Comment by weihanglo** [comment]
To add one more item to the list, `--remap-path-prefix` on rustc also applies to diagnostic messages. However, it is not the case on rustdoc. See the [zulip topic](https://rust-lang.zulipchat.com/#narrow/stream/266220-t-rustdoc/topic/remap-path-prefix.20remap-path-scope/near/455517005).

This is found when trying to resolve issues in <https://github.com/rust-lang/rust/issues/111540>. I expect rustdoc to match the behavior of rustc.

**Comment by weihanglo** [comment]
From [Zulip t-rustdoc](https://rust-lang.zulipchat.com/#narrow/stream/266220-t-rustdoc/topic/remap-path-prefix.20remap-path-scope/near/455537083):

> If rustc supports it (and IIUC it seems like it does), then I think we should match rustc in that.
> Rustdoc diagnostics should normally behave the same as rustc.

So we kinda get a green light for working on this.

**Comment by GuillaumeGomez** [comment]
Taking a look.
