### ISSUE TITLE
Not optimized codegen with NonZeroI32

### ISSUE THREAD

**Issue by crlf0710** [rust-lang/rust#69279]
This code:
```rust
use std::num::NonZeroI32;

pub fn div(a: i16, b: NonZeroI32) -> (i32, i32) {
    let a = a as i32;
    let b = b.get();
    (a / b, a % b)
}
```
should have no possibility of panicking by "divide by zero", however, it seems related check and panicking code is still generated.

**Comment by uenoku** [comment]
It is a longstanding problem: https://github.com/rust-lang/rust/issues/49572

**Comment by jonas-schievink** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/49572
