### ISSUE TITLE
Improve error message for "return type cannot contain a projection or `Self`..."

### ISSUE THREAD

**Issue by tmandry** [rust-lang/rust#69276]
Example ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=6263bc1478126f230d8ef2dae9a5deb0)):

```
error: `async fn` return type cannot contain a projection or `Self` that references lifetimes from a parent scope
 --> src/lib.rs:4:33
  |
4 |     async fn new(i: &'a i32) -> Self {
  |                                 ^^^^
```

- Add a hint: try spelling out the type instead
- Add an error code with an entry in the error index explaining that this is a limitation of the compiler, tracked by #61949

**Comment by kornelski** [comment]
I've ran into this case, which doesn't have a good diagnostic either:

```rust
struct Foo<'a>(&'a ());

impl<'a> Foo<'a> {
    async fn named(arg: &'a ()) -> Foo<'a> {
        Self(arg)
    }
    
    async fn selfie(arg: &'a ()) -> Self {
        Self(arg)
    }
}
```
