### ISSUE TITLE
Replace `#[rustc_args_required_const(n)]` with per-argument attr

### ISSUE THREAD

**Issue by ecstatic-morse** [rust-lang/rust#69282]
[RFC 2565](https://github.com/rust-lang/rfcs/pull/2565), which was recently stabilized, allows individual function parameters to have attributes. One of the [motivating examples](https://github.com/rust-lang/rfcs/blob/master/text/2565-formal-function-parameter-attributes.md#compiler-internals-improving-rustc_args_required_const) for that RFC was the ugliness of `#[rustc_args_required_const]`, which specifies the const argument(s) by index. We should transition away from `#[rustc_args_required_const]` to a per-argument attribute.

@petrochenkov has proposed [`#[rustc_required_const]`](https://github.com/rust-lang/rust/pull/69280#issuecomment-588049122). These attributes are perma-unstable so there are no backwards compatibility concerns.

**Comment by petrochenkov** [comment]
[triagebot] :+1:

**Comment by jakevossen5** [comment]
I would be willing to take this up. Is there any mentors out there who could be available if I have questions?

@rustbot claim

**Comment by LeSeulArtichaut** [comment]
@jakevossen5 Are you still working on this? Or can I take it up?

**Comment by jakevossen5** [comment]
@LeSeulArtichaut , Apologies, I have gotten a bit busy in the past week. I am still working on this and hopefully have a PR up sometime next week.

**Comment by eddyb** [comment]
Ironically, the benefit from this is pretty minor, and it'd be trickier to implement than today, because the param attributes aren't kept cross-crate, so they need to be encoded some other way.

Probably a decent way would be to add a `Lazy<BitSet>` to this, I guess? https://github.com/rust-lang/rust/blob/c6b172f7885cb83842fa15e4b0e2ff1647aebb40/src/librustc_metadata/rmeta/mod.rs#L327-L331

**Comment by jakevossen5** [comment]
@eddyb Do you mean a new element of the struct, like `param_consts` that keeps track of which are constants? Do I understand that correctly?

**Comment by eddyb** [comment]
I think we should resolve #70271 first before touching `#[rustc_args_required_const]` further.

**Comment by jakevossen5** [comment]
Sounds good. I will watch that thread and when it it closed circle back to here.

**Comment by Alexendoo** [comment]
`rustc_args_required_const` has been removed - #85110
