### ISSUE TITLE
Move keyword page makes no mention of async blocks

### ISSUE THREAD

**Issue by That3Percent** [rust-lang/rust#69298]
The [move keyword](https://doc.rust-lang.org/std/keyword.move.html) page currently talks only about the use of move with closures. The `move` keyword is also valid before an async block. For example: `async move { /*...*/ }`. This page could be updated to include that usage.

This issue has been assigned to @Pulkit07 via [this comment](https://github.com/rust-lang/rust/issues/69298#issuecomment-591015230).

**Comment by nikomatsakis** [comment]
## Mentoring instructions

Edit [`src/libstd/keyword_docs.rs`](https://github.com/rust-lang/rust/blob/master/src/libstd/keyword_docs.rs) and make the text talk about async blocks as well.
