### ISSUE TITLE
Miri exception improvements

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#69297]
The Miri engine uses "exceptions" (`InterpResult`) to report misbehaving executions and propagate this information outwards to the machine (const-eval/const-prop/miri-the-tool). When an error is raised, we optionally capture a backtrace to ease debugging.

There are two problems with this:
* [x] Currently, checking whether we want to capture a backtrace is rather expensive (we check an env var). @wesleywiser proposed a scheme to use a session variable instead.
* [ ] Sometimes, the engine *catches* these "exceptions". This means we caught the backtrace in vein. https://github.com/rust-lang/rust/pull/69290 brought some nice speed-up by removing just one case of catching an interpreter error! I think we should never catch these errors. Is there something we can do to prevent accidental catching?

Cc @oli-obk

**Comment by oli-obk** [comment]
The obvious solution is to go through the engine (we could still use the `?` operator and basically not require any changes except to type signatures if we made it an associated constant or at least not an `&self` function), but that requires infecting all error types.

Didn't we also discuss checking the current query name somewhere?

**Comment by wesleywiser** [comment]
> Didn't we also discuss checking the current query name somewhere?

Yes, it was proposed [here](https://github.com/rust-lang/rust/pull/68792#issuecomment-581652542) but at least for `ctfe-stress-4`, that didn't pay off because most of the errors were created during `const_eval-raw` (see [here](https://github.com/rust-lang/rust/pull/68792#issuecomment-588006931)).

**Comment by RalfJung** [comment]
@oli-obk I take you you are talking about the first point? As I wrote above, I think @wesleywiser's proposed scheme of using a session var is a good next step there -- certainly better than what we do now.

**Comment by RalfJung** [comment]
I found some more cases of exceptions being caught:
* https://github.com/rust-lang/rust/blob/97b3d816152774e45d01d44cd5b44565dc7aba58/src/librustc_mir/interpret/validity.rs#L758
* https://github.com/rust-lang/rust/blob/97b3d816152774e45d01d44cd5b44565dc7aba58/src/librustc/mir/interpret/allocation.rs#L384

The first one occurs quite a bit in Miri because we validate all the time (CTFE validates less often so this should be less of an issue, but still). I am not sure how best to fix it, short of implementing https://github.com/rust-lang/miri/issues/841.

**Comment by RalfJung** [comment]
@wesleywiser do you still plan to submit [this approach](https://github.com/rust-lang/rust/commit/2c7e3b548d1b1e57dfc3eec8bf82d9589cf25fe8) as a PR or would you like someone else to take over?

**Comment by wesleywiser** [comment]
@RalfJung Thanks for the reminder! I just posted a slightly more cleaned up version as #69888.

**Comment by RalfJung** [comment]
Status: last time I looked into this, I found some more cases where exceptions are being caught, that are related to handling of pointer provenance and ptr-int casts. I consider this problem blocked on https://github.com/rust-lang/miri/issues/841.

**Comment by RalfJung** [comment]
I am also seeing *many* exceptions being raised and caught in ConstProp -- so, `RUSTC_CTFE_BACKTRACE=1` is a serious slowdown for constprop. I am not sure if there is anything we can do about that... @oli-obk any idea?

Sadly this also masks any exceptions being raised elsewhere, making it really hard to figure out if there are non-constprop instances of this problem left.

**Comment by oli-obk** [comment]
I'm not sure const prop can do better other than duplicating all the checks that would lead to the exceptions being raised. We can do some half measures to eliminate obvious cases.

We could add a `Drop` impl to the error type and require all destructions of the errors to be made explicit. Not sure how annoying that would be in practice, but it could work well.

**Comment by RalfJung** [comment]
We could also do something awful and have some thread-local storage so this code

https://github.com/rust-lang/rust/blob/b9197978a90be6f7570741eabe2da175fec75375/compiler/rustc_middle/src/mir/interpret/error.rs#L116

knows it is inside ConstProp and always treats this as `Disabled`.

**Comment by oli-obk** [comment]
> 
> 
> We could also do something awful and have some thread-local storage so this code
> 
> https://github.com/rust-lang/rust/blob/b9197978a90be6f7570741eabe2da175fec75375/compiler/rustc_middle/src/mir/interpret/error.rs#L116
> 
> knows it is inside ConstProp and always treats this as `Disabled`.

and then re-enable (in a scoped manner) when inside the CTFE query. Seems hacky and annyoing and actually manageable. I think it's fine, it's just for the backtrace printing, nothing that actually affects anyone that is not already debugging CTFE

**Comment by RalfJung** [comment]
I think I'll just use a locally patched rustc that does not do const-prop.^^ But we should maybe make a note that `RUST_CTFE_BACKTRACE=1` currently is rather expensive since it captures a lot of backtraces during const-prop. I'll open an issue for that.

Regarding the issue at hand, the following are the only Miri test cases that have any exceptions caught and discarded. :)
```
    [ui] run-pass/exit.rs
    [ui] run-pass/issue-miri-1075.rs
```

**Comment by RalfJung** [comment]
Ah, and those are expected, since they are using `throw_machine_stop!`.

So I think this issue is solved. :-) We don't have a strategy in place to detect when it arises again in the future, but still I think we can close this one now.
