### ISSUE TITLE
macros which use $crate:: resolve to the wrong name when the crate is renamed

### ISSUE THREAD

**Issue by That3Percent** [rust-lang/rust#69301]
A macro using `$crate::` is supposed to be able to see its namespace regardless of whether that crate is a direct dependency of the caller. This is useful for hygienic purposes.

If a crate is renamed however:

```toml
futures03 = { version = "0.3.1", package = "futures" }
```
Then the compiler fails to find the correct crate, instead using the name of the package.
Using the previous import and the following rust code produces an error:

```rust
async fn test() {
    futures03::try_join!()
}
```

The error produced by cargo check is:
```
failed to resolve: could not find `futures` in `{{root}}`
```

The error shown by rust-analyzer is:
```
failed to resolve: could not find `core_reexport` in `futures`
```

One might try to work around the bug by not renaming the crate. But, doing so presents a problem when importing multiple versions of the same crate under different names (as one may want to do when migrating from futures01 to futures03) since it is not possible to use macros from both crates.

In this case `$crate::` should not expand to `::futures::` but expand to `::futures03::` which would fix the bug.

**Comment by petrochenkov** [comment]
`$crate` doesn't normally expands into `::crate_name`, it resolves directly as `$crate` instead.
In this case it looks like it has to go through pretty-printing before resolution due to some issue like https://github.com/rust-lang/rust/issues/43081, then it indeed turns into `::crate_name` - the closest approximation.

**Comment by petrochenkov** [comment]
The `futures` crate doesn't use `$crate`, it uses `::futures` literally.

So this is not an issue in `rustc`, closing.
