### ISSUE TITLE
Visibility tokens on types in `extern { ... }` blocks are no longer given to procedural macros

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#69315]
I had https://github.com/rustwasm/wasm-bindgen/issues/2009 opened up on a project recently but this looks to be a regression I think. This regressed between nightly-2020-02-19 and nightly-2020-02-20, and bisecting further by commit reveals https://github.com/rust-lang/rust/pull/69271 as the culprit. I'm not sure which of the PRs in that rollup though are the culprit here.

This can be reproduced by running `cargo check` from the `crates/js-sys` folder in the wasm-bindgen repository. Unfortunately this one probably isn't super easy to reproduce, so I'm hoping that someone more knowledgeable can hopefully take a look at this and have a better idea about what's going on. 

There's definitely macros going on in `#[wasm_bindgen]` (the `Memory` type is synthesized by a macro), which leads me to think that https://github.com/rust-lang/rust/pull/69211 may be the culprit? (cc @petrochenkov)

**Comment by petrochenkov** [comment]
The large parser PR from @Centril (https://github.com/rust-lang/rust/pull/69194) could also cause something like this.

**Comment by petrochenkov** [comment]
I'll be able to look at this during the weekend, but it would be great if someone could come up with a minimal reproduction before that.

**Comment by alexcrichton** [comment]
Ok, wanted to get a gut-check to see if it was known what was happening. Did some reduction and it looks like the macro no longer gets the `pub` token for the input type.

Given this input:

```rust
pub mod wasm {
    #[the_macro::the_macro]
    extern "C" {
        pub type Memory;
    }
}

fn main() {
    let _: wasm::Memory;
}
```

then with this macro:

```rust
extern crate proc_macro;

use proc_macro::*;

#[proc_macro_attribute]
pub fn the_macro(_attr: TokenStream, body: TokenStream) -> TokenStream {
    let g = match body.clone().into_iter().nth(2) {
        Some(TokenTree::Group(g)) => g,
        _ => panic!("unexpected input"),
    };
    let tokens = g.stream().into_iter().collect::<Vec<_>>();
    assert_eq!(tokens[0].to_string(), "pub");
    return body;
}
```

it fails with:

```
$ cargo +nightly build
   Compiling wut v0.1.0 (/home/alex/code/wut)
error: custom attribute panicked
 --> src/main.rs:2:5
  |
2 |     #[the_macro::the_macro]
  |     ^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: message: assertion failed: `(left == right)`
            left: `"type"`,
           right: `"pub"`

error: aborting due to previous error

error: could not compile `wut`.

To learn more, run the command again with --verbose.
```

On stable it yields the expected `error[E0658]: extern types are experimental` error which indicates that the `pub` token was fed to the macro.

If the `#[wasm_bindgen]` macro doesn't see the `pub` token it doesn't make the final result public, which is why the privacy error happened in the first place.

**Comment by alexcrichton** [comment]
(updated the issue title to reflect what appears to be the actual bug)

**Comment by Centril** [comment]
Fixed by https://github.com/rust-lang/rust/pull/69334.
