### ISSUE TITLE
Feature request: From<&[T]> for NonNull<T> 

### ISSUE THREAD

**Issue by tspiteri** [rust-lang/rust#69316]
While `NonNull<T>` implements `From<&T>`, it does not implement `From<&[T]>`. Current options:

1. Use `NonNull::new(slice.as_ptr() as *mut T).unwrap()`, and rely on the optimizer to remove the unwrap.
2. Use `unsafe { NonNull::new_unchecked(slice.as_ptr() as *mut T) }`, which is correct but unfortunately has to use `unsafe`.
3. It is tempting to use `NonNull::from(&slice[0])`, which looks more ergonomic than 1 and 2, but has incorrect pointer provenance.

Since both references and slices have `as_ptr` and `as_mut_ptr` methods, I think that `NonNull` should implement `From` for slices as well as for references.

**Comment by jonas-schievink** [comment]
It implements `<'a, T: ?Sized> From<&'a T>`, so this should already work, right?

**Comment by tspiteri** [comment]
But `NonNull::from(slice)` returns `NonNull<[T]>`, it does not return `NonNull<T>`. By comparison, `slice::as_ptr` returns `*const T`, not `*const [T]`.

**Comment by jonas-schievink** [comment]
Ah, I see

**Comment by tspiteri** [comment]
As pointed out in https://github.com/rust-lang/rust/pull/69319#pullrequestreview-363203290, this use case is already solved by `NonNull::from(slice).cast::<T>()`.
