### ISSUE TITLE
release notes could list future-incompat lints that have become hard errors

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#69321]
recent [discussion](https://zulip-archive.rust-lang.org/131828tcompiler/77833premeetingtriage2020022054818.html#188656730) with @spastorino and @Centril led me to the following observations:

 * generally the PR's that upgrade future-compat lints to hard errors are not tagged with `relnotes` label
 * users might like a heads up about such changes. such documentation would give us a central place to say "for version X of popular crate, upgrade to version Y"
 * so perhaps we should start tagging those PR's with `relnotes`, and include them in the Release Notes under the "Compatibility Notes" section.

**Comment by Mark-Simulacrum** [comment]
I'll leave this open, but I believe that we basically just need T-compiler/lang to tag such PRs and that'll make them get included in @XAMPPRocky's input lists for release notes.

**Comment by XAMPPRocky** [comment]
They don't necessarily have to be tagged `relnotes` to end up in the Rust release notes, if there is already a label that uniquely identifies these issues and the changes are in are in before beta. I (or someone else if they're interested) can easily add them to the [`relnotes`](https://github.com/rust-lang/relnotes) tool.

**Comment by Mark-Simulacrum** [comment]
I believe there's no such unique tag today, and I would personally feel a lot better about centralizing into just one tag for ease of use :)

**Comment by XAMPPRocky** [comment]
@Mark-Simulacrum Well I use multiple labels to separate out all the issues in my draft and use `relnotes` as a priority list of those specific changes. e.g.
```
Language
--------
**relnotes**
{{language_relnotes}}

{{language_unsorted}}
```

So if there was a tag it would be helpful and make *my* life easier, but if not it's not a big deal.

**Comment by Mark-Simulacrum** [comment]
Ah, I was unaware! I think adding a C-future-incompatibility tag to such PRs would work well. Not technically exactly what that label usually means but that's okay. cc @Centril because you're involved in most (all?) of those PRs.

**Comment by Centril** [comment]
Using `C-future-compatibility + relnotes` together seems like a clear solution.

**Comment by Mark-Simulacrum** [comment]
Closing as resolved.
