### ISSUE TITLE
Support for partial existentials in TAIT

### ISSUE THREAD

**Issue by CAD97** [rust-lang/rust#69323]
[[playground]](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=f1faf43935fce3efb6f8390c574ee41c) ([Tracking issue](https://github.com/rust-lang/rust/issues/63063#issue-473710023))

With RPIT, it is possible to create a "partial existential":

```rust
fn test1<A: Iterator<Item=&'static str>>(x: A)
    -> Chain<A, impl Iterator<Item=&'static str>>
{
    x.chain(once(","))
}
```

With TAIT, however, this currently produces an error:

```rust
type Chained<A> = Chain<A, impl Iterator<Item=&'static str>>;
fn test2<A: Iterator<Item=&'static str>>(x: A) -> Chained<A> {
    x.chain(once(","))
}
```

This should probably be possible, both for concept parity for factoring unnamed RPIT out into named TAIT, and because this "partial existential" allows parameterizing partial existentials over input types in a way that allows input-type-dependent trait implementation.

**Comment by jackh726** [comment]
Works on master
