### ISSUE TITLE
enhancement request: expose the windows process handle as a extension trait for Child

### ISSUE THREAD

**Issue by rbtcollins** [rust-lang/rust#69335]
The Windows process Handle has rights to the child process that are not always re-obtainable by calling OpenProcess with the process ID. It would be convenient to allow getting the handle as well from the underlying system implementation. This should be a pretty simple extension trait e.g. in std::os::windows::process::ChildExt - I'm happy to put up a patch for that.

Without this, one needs to take the id, call OpenProcess, hope that it is indeed the same process and no race has occurred and that you can obtain a handle to the process, and then proceed to operate on the handle.

**Comment by retep998** [comment]
Uh, `Child` already implements `AsRawHandle` which literally provides the handle you want.

**Comment by rbtcollins** [comment]
Ok, so I am blind - thanks.
