### ISSUE TITLE
Don't suggest adding 'static lifetime to function arguments

### ISSUE THREAD

**Issue by kornelski** [rust-lang/rust#69350]
When using a temporary reference in a context where temporary references are not allowed, rustc gives a technically-correct suggestion that in practice is most often misleading and makes beginners stuck trying to solve a wrong problem:

```rust
fn naninani(arg: &str) {
    std::thread::spawn(|| {
        println!("{}", arg);
    });
}
```

```
error[E0621]: explicit lifetime required in the type of `arg`
 --> src/lib.rs:2:5
  |
1 | fn naninani(arg: &str) {
  |                  ---- help: add explicit lifetime `'static` to the type of `arg`: `&'static str`
2 |     std::thread::spawn(|| {
  |     ^^^^^^^^^^^^^^^^^^ lifetime `'static` required
```

This suggestion is very unlikely to be useful in a real program. If the function is changed to require arguments with a `'static` lifetime, it generally just causes more borrow checking errors at the call sites of the function, causing inexperienced users dig deeper in the wrong direction.

My suggestions:

* Don't make code change suggestions for `'static` lifetime outside of globals. In this case no suggestion at all would be better than a misleading code change.

* Because the correct solution is most likely *not* to use a reference at all, don't focus the message on the (unusual) kind of reference that would work, but explain that most (i.e. non-`'static`) references won't work.

I suggest changing "lifetime `'static` required" say something along the lines of "temporary references are not allowed".

**Comment by timleg002** [comment]
How should I go to avoid this error?

**Comment by kornelski** [comment]
This error in practice means references are forbidden, so don't use references. Usually you'll want to use `Arc` or some other self-contained type like `String` (not `&str`), or `Vec` (not `&[]`).

Please ask questions on https://users.rust-lang.org/

**Comment by SorteKanin** [comment]
Just ran into this incredibly useless compiler message and had to spend some time digging. I agree that this "help" message does more harm than good and it would probably be better to have no help than this suggestion.

**Comment by kornelski** [comment]
Another case of a user stuck, because the compiler told them to have `&'static self`:

https://users.rust-lang.org/t/how-to-solve-this-lifetime-problem/54129?u=kornel

**Comment by timleg002** [comment]
> This error in practice means references are forbidden, so don't use references. Usually you'll want to use `Arc` or some other self-contained type like `String` (not `&str`), or `Vec` (not `&[]`).
> 
> This issue is about development of the Rust compiler. Please ask Rust programming questions on https://users.rust-lang.org/

Thanks for the answer. This needs to be fixed asap
