### ISSUE TITLE
Type aliases and mods of the same name in the same namespace should be forbidden

### ISSUE THREAD

**Issue by bjz** [rust-lang/rust#6936]
The tests for this crate compile ok:

~~~rust
#[link(name = "complex", vers = "test")];
#[crate_type = "lib"];

pub struct ComplexT<T> { x: T, y: T, z: T }

impl<T> ComplexT<T> {
    pub fn new(x: T, y: T, z: T) -> ComplexT<T> {
        ComplexT { x: x, y: y, z: z }
    }
}

pub type Complex32 = ComplexT<f32>;

pub mod Complex32 {
    use super::*;
    pub fn new(x: f32, y: f32, z: f32) -> Complex32 {
        ComplexT::new(x, y, z)
    }
}

#[test]
fn test_Complex() {
    let v = Complex32::new(1.0, 2.0, 3.0);
    println(fmt!("%?", v));
}
~~~

This is incompatible with #6894, and should probably be forbidden.

**Comment by aturon** [comment]
Nominating. This was marked P-backcompat-lang but not previously placed on a milestone. Do we need to do something here for beta?

**Comment by pnkfelix** [comment]
assigning to 1.0-beta milestone: we need to make a decision here and firm up our story about the namespace conflicts.

**Comment by nick29581** [comment]
Note that currently other types and modules don't clash, so that might be a bug too.
