### ISSUE TITLE
`IoSlice` does not implement `Clone`

### ISSUE THREAD

**Issue by eduardosm** [rust-lang/rust#69395]
`IoSlice` (from `std::io`) does not implement the `Clone` trait. Is there a reason for this? Cloning can be safely simulated with `IoSlice::new(*slice)`, but the lack of the `Clone` trait prevents from using functions such as `Vec::<IoSlice>::extend_from_slice`.

**Comment by sfackler** [comment]
IoSlice should be able to implement Copy and Clone - I think the current lack is just an oversight when I added the type. Feel free to make a PR!

**Comment by LeSeulArtichaut** [comment]
If you need someone to file a PR, I’m up!

**Comment by eduardosm** [comment]
> If you need someone to file a PR, I’m up!

I will create a PR soon, but thanks anyways for the offer.

**Comment by LeSeulArtichaut** [comment]
Oops, I already created #69403 😅

**Comment by eduardosm** [comment]
Whops, I didn't see the linked pull request. Never mind then, lets continue with your PR.
