### ISSUE TITLE
E0118 probably shouldn't use the terminology of "base type"

### ISSUE THREAD

**Issue by CAD97** [rust-lang/rust#69392]
[[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=402962d2a426abadef2f25433c19d300)]

```rust
struct Animal;

impl &Animal {}
```

```
error[E0118]: no base type found for inherent implementation
 --> src/lib.rs:3:6
  |
3 | impl &Animal {}
  |      ^^^^^^^ impl requires a base type
  |
  = note: either implement a trait on it or create a newtype to wrap it instead
```

To [quote GIGAOTSOS](https://internals.rust-lang.org/t/why-access-subtyping-is-not-allowed-in-type-extensions/11875/23?u=cad97):

> impl requeres a base type error screams about presence of sybtyping

This should probably use the covered/local terminology from [re-rebalancing coherence](https://github.com/rust-lang/rfcs/pull/2451) instead of "base type" to avoid the problematic overlap with subtyping/inheritance terminology.

**Comment by CAD97** [comment]
[[A-diagnostics](https://github.com/rust-lang/rust/labels/A-diagnostics)] [[C-enhancement](https://github.com/rust-lang/rust/labels/C-enhancement)] [[D-newcomer-roadblock](https://github.com/rust-lang/rust/labels/D-newcomer-roadblock)]

(Not really [C-bug], but it was the closest of the template options.)

**Comment by jumbatm** [comment]
Just fyi, you can do

@rustbot modify labels to -C-bug +A-diagnostics +C-enhancement +D-newcomer-roadblock

which will let you apply most labels yourself. [See here](https://github.com/rust-lang/triagebot/wiki/Labeling).

**Comment by jumbatm** [comment]
... Oh, unless that happens.

**Comment by jumbatm** [comment]
A second attempt :stuck_out_tongue: 

@rustbot modify labels to -C-bug +A-diagnostics +C-enhancement

**Comment by Havvy** [comment]
In the reference, we use the term "nominal type". The error code explanation should also mention unions and trait objects (`impl dyn Send {}` is valid).  If the person use `&NominalType` or `&mut NominalType`, it should also hint at removing the reference and putting them on `Self` in the  associated items. Not sure if I should open a new issue for that one or not though.
