### ISSUE TITLE
internal compiler error: expected `NodeId` to be lowered already for res Local...

### ISSUE THREAD

**Issue by dwrensha** [rust-lang/rust#69401]
I'm seeing an internal compiler error on the following input (found by [fuzz-rustc](https://github.com/dwrensha/fuzz-rustc)):

```rust
struct Inv<'a> {
    x: &'a u8
}
pub trait Foo {
    fn no_bound(b: Inv<(b)>);
}
```

```
$ rustc main.rs
error[E0573]: expected type, found local variable `b`
 --> main.rs:5:25
  |
5 |     fn no_bound(b: Inv<(b)>);
  |                         ^ not a type

thread 'rustc' panicked at 'expected `NodeId` to be lowered already for res Local(
    NodeId(21),
)', src/librustc_ast_lowering/lib.rs:662:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.43.0-nightly (5d04ce67f 2020-02-13) running on x86_64-unknown-linux-gnu

error: aborting due to previous error

For more information about this error, try `rustc --explain E0573`.

```

**Comment by dwrensha** [comment]
Report from `cargo-bisect-rustc`:

> searched nightlies: from nightly-2020-01-01 to nightly-2020-02-16
regressed nightly: nightly-2020-02-07
> searched commits: from https://github.com/rust-lang/rust/commit/58b834344fc7b9185e7a50db1ff24e5eb07dae5e to https://github.com/rust-lang/rust/commit/442ae7f04026c215a03b155eaaf9cde8bb5cf02a
> regressed commit: https://github.com/rust-lang/rust/commit/442ae7f04026c215a03b155eaaf9cde8bb5cf02a

**Comment by dwrensha** [comment]
It looks like https://github.com/rust-lang/rust/pull/68788 caused the regression. (The error happens at 9a4eac39 but not at c9290dceee.)
cc @Centril

**Comment by dwrensha** [comment]
The specific commit where the error starts happening is b2c6eeb713d4cf9b35b7dda6ff2b0274e7f24684.

**Comment by pnkfelix** [comment]
triage: P-high. Removing nomination. Added regression stable-to-nightly tag.

**Comment by Centril** [comment]
Fixed by https://github.com/rust-lang/rust/pull/69539.
