### ISSUE TITLE
Is it a desirable behavior?

### ISSUE THREAD

**Issue by tema3210** [rust-lang/rust#69407]
I tried this code:
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=6bd7b465cf1b76c355e4792768ecd8cb

```rust
#![feature(generic_associated_types)]
#![feature(const_generics)]

trait Test {
    type T: std::ops::Add;
    const C: Self::T;
    fn lower<'a>()-> &'a dyn Test<T=Self::T,C={2+2}>;
}
```

I expected to see this happen: Actually i wanted to blow up compiler (to see, where it blows) =).

Instead, this happened: But things didn't go further from parsing stage.

From playground: `rustc --version --verbose`:
```
1.43.0-nightly 2020-02-22 436494b8f8008b600d64
```
P.S Maybe its still too early for that...

**Comment by jonas-schievink** [comment]
This has nothing to do with const generics or GATs, it's just that you can't specify associated constants in trait objects, which is intended (they are not object safe).
