### ISSUE TITLE
`impl From<Infallible> for MyType` does not solve coercion problems

### ISSUE THREAD

**Issue by AaronKutch** [rust-lang/rust#69448]
[playground link with all the impls and functions in example usage](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=b7849335bba5d3e8ed5f675853501d4e)
The gist is that I have an impl `impl TryFrom<usize> for InvariantType` and function signatures with `TryInto<InvariantType, Error = MyErrorType>`. This enables many ergonomics, but trying to input a plain `InvariantType` into the function conflicts with the blanket `impl TryFrom<T> for T` which has a return type `!` instead of `Error = MyErrorType`.

Since `!` can and will coerce into anything through a future [`impl<T> From<!> for T` ](https://github.com/rust-lang/rust/issues/64715) , and there is a current workaround:
```
impl From<Infallible> for MyError {
    fn from(_: Infallible) -> Self {
        unreachable!()
    }
}
```
it should work, but adding this to the playground link does not change the error message at all.

Also in the playground link, there is a nearly identical error related to a `From<NonZeroUsize> for BitWidth` and its blanket impls. In that case, I can't even apply the attempted workaround because of orphan rules.

**Comment by jonas-schievink** [comment]
Adding the `From` impl does not create a `TryFrom` impl for an unrelated type. Change `typical_function` to take a generic error `E` instead and add `where MyError: From<E>` to its bounds.

**Comment by AaronKutch** [comment]
Thank you, the fix is 
```
pub fn typical_function<W, E>(target_width: W) -> Result<(), MyError>
where
    W: TryInto<BitWidth, Error = E>,
    MyError: From<E>,
{
```
and add the `From<Infallible>` impl. [playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=e4a39e506ddebaac6f59cf0870f359b5).
