### ISSUE TITLE
Audit uses of `FnCtxt::impl_self_ty`

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#69489]
Context: https://github.com/rust-lang/rust/pull/69340#discussion_r382603867

cc @eddyb

**Comment by eddyb** [comment]
IMO it should be possible to fully remove (see comment linked by @Centril).

If it was more widely used (or if removing it doesn't seem to work), it would be important to rename to have `instantiate` in the name to indicate it introduces inference variables.

**Comment by JohnTitor** [comment]
I just tried removing `impl_self_ty` fully, it seems to work well: https://github.com/JohnTitor/rust/commit/e30534d5787dd54baa6309b86504e53d1355f2bf

Could I submit this patch?

**Comment by Centril** [comment]
cc also @nikomatsakis ^---
Error messages are improved at least. :)

**Comment by eddyb** [comment]
@JohnTitor In suggestions you probably don't need `normalize_ty` either, AFAICT it's just used to print the type of the `impl`.

**Comment by JohnTitor** [comment]
@eddyb You're right, thanks! I'd like to submit a PR if you could do further reviews :)
