### ISSUE TITLE
Tracking Issue for general floating point formatting 

### ISSUE THREAD

**Issue by mxxo** [rust-lang/rust#69486]
This is a tracking issue for general human-readable floating point formatting akin to C's `printf("%g")`.

### RFCs:
| Link | Description | 
|---|---|
|[RFC 844](https://github.com/rust-lang/rfcs/issues/844) | Original request for a `%g`-style format | 
|[RFC 2729](https://github.com/rust-lang/rfcs/pull/2729) |  Detailed RFC by @ExpHP proposing a `{:g?}` `Debug` formatter following the stabilization of `{:x?}`. |

### Open questions: 
1. Format specifier and trait (`:g | :g? | :#?`). Extend `Debug` or introduce `LowerGen`, `UpperGen` formatting traits? 

_From RFC 2729:_ 

2. The precise format is subject to heavy bikeshedding.
3. When should the format be considered final? On stabilization of {:g?}? On stabilization of {:g} if it occurs?
4. Public API for this and [RFC 2226](https://github.com/rust-lang/rfcs/pull/2226)

### Links: 
Pre-RFC discussion: https://internals.rust-lang.org/t/pre-rfc-draft-g-or-floating-points-for-humans/9110

### Related crates: 
* [`float-pretty-print`](https://crates.io/crates/float-pretty-print) by @vi 
* [`3photons-rust`](https://github.com/HadrienG2/3photons-rust/blob/master/src/output.rs) by @HadrienG2 implements a `%g`-like formatter. 
* [`sad_monte_carlo`](https://github.com/droundy/sad-monte-carlo/blob/master/src/prettyfloat.rs) by @droudy implements a `%g`-like formatter.

**Comment by jonas-schievink** [comment]
https://github.com/rust-lang/rfcs/pull/2729 has not been accepted yet

**Comment by droudy** [comment]
@droundy
