### ISSUE TITLE
E0583: Improve error message to help with use vs mod confusion

### ISSUE THREAD

**Issue by kornelski** [rust-lang/rust#69492]
Feedback from a [user forum thread](https://users.rust-lang.org/t/module-structure-problem-single-parent-class-multiple-child-classes/38652/9). This code:

```rust
mod foo {
}

mod bar {
    mod foo;
}
```

currently suggests:

>  = help: name the file either foo.rs or foo/mod.rs inside the directory "src/bar"

This is awkwardly worded. It doesn't clearly explain that this syntax creates a new module. It doesn't guess that the user may have meant `use crate::foo`.

I suggest:

1. Improve wording of the message. "To create a new module `crate::bar::foo`, create "src/bar/foo.rs" file" (to keep it simple, without also suggesting 2015-edition path).

2. If there already is a module with that name, suggest `use` instead.

**Comment by kornelski** [comment]
I couldn't find a way to get path to the current module, or names of already parsed modules. 

It seems that this info isn't explicitly tracked at such an early stage in the parsing, and I'm not sure if it's OK to add it.

**Comment by estebank** [comment]
I'm unambiguously in favor of 1 and tepidly positive about 2. The implementation of 2 might be difficult that early on.

**Comment by estebank** [comment]
Current output:

```
error[E0583]: file not found for module `foo`
 --> src/lib.rs:5:5
  |
5 |     mod foo;
  |     ^^^^^^^^
  |
  = help: to create the module `foo`, create file "src/bar/foo.rs" or "src/bar/foo/mod.rs"
```

**Comment by estebank** [comment]
@kornelski resurrected your change under https://github.com/rust-lang/rust/pull/116992
