### ISSUE TITLE
Remove special-case for `simd_shuffle` intrinsics in promotion

### ISSUE THREAD

**Issue by ecstatic-morse** [rust-lang/rust#69493]
#69280 tried to normalize promotion of arguments that must be const by requiring `#[rustc_args_required_const]` everywhere. Currently, intrinsics beginning with the string "simd_shuffle" automatically get their third argument promoted. However, this broke the latest release of the `packed_simd` crate, which does not define the intrinsics with the requisite attribute (see #69313).

Although this is allowed breakage (you can't define intrinsics without the nightly-only `platform_intrinsics` feature), I reverted #69280 for now, since it's just a small cleanup and isn't blocking anything. I opened rust-lang/packed_simd#278 to fix `packed_simd`. Once a version of that crate is released with the fix, we should reapply #69280.

**Comment by workingjubilee** [comment]
@rustbot modify labels: +A-simd
I guess? :shrug:

**Comment by mati865** [comment]
Packed_simd seems unmantained these days, I think it had enough time adjust.
