### ISSUE TITLE
Crate function returns private type

### ISSUE THREAD

**Issue by Algirdyz** [rust-lang/rust#69515]
Hi,
I was told this should not be possible, but it is.
If you add this crate to you project. 
https://crates.io/crates/cargo-deps
and call function `get_dep_graph()` it returns a type that you cannot define in any of your function definitions.

I tried this code:

```rust
use cargo_deps::{get_dep_graph, Config};
let dep_graph = get_dep_graph(Config::default()).unwrap();

test(dep_graph);

fn test(dep_graph: cargo_deps::graph::DepGraph) {
    println!("test!");
}

```

I expected to see this happen: *explanation*

Instead, this happened: *explanation*

`rustc --version --verbose`:
```
rustc 1.41.0 (5e1a79984 2020-01-27)
binary: rustc
commit-hash: 5e1a799842ba6ed4a57e91f7ab9435947482f7d8
commit-date: 2020-01-27
host: x86_64-unknown-linux-gnu
release: 1.41.0
LLVM version: 9.0

```

<details><summary>Backtrace</summary>
<p>

```
error[E0603]: module `graph` is private
  --> src/graph_merger.rs:80:46
   |
80 | fn are_parents_merged(dep_graph: cargo_deps::graph::DepGraph) -> bool{
   |                                              ^^^^^

```

</p>
</details>

**Comment by jonas-schievink** [comment]
That's working as intended. `DepGraph` only has to be `pub`, not reexported in an accessible place.

**Comment by ehuss** [comment]
I believe there is an unimplemented RFC for warnings on this: #48054
