### ISSUE TITLE
Diagnostics: suggest alternatives when `new` constructor is not available

### ISSUE THREAD

**Issue by yoshuawuyts** [rust-lang/rust#69512]
## Failing Code

Consider the following code:

```rust
use std::net::TcpStream;

fn main() {
   let stream = TcpStream::new();
}
```

[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=b0669861e6950a0b2855c437bc1aa0ec)

This fails with an error that simply states that `new` is not available:

```txt
Compiling playground v0.0.1 (/playground)
error[E0599]: no function or associated item named `new` found for type `std::net::TcpStream` in the current scope
 --> src/main.rs:4:28
  |
4 |    let stream = TcpStream::new();
  |                            ^^^ function or associated item not found in `std::net::TcpStream`

error: aborting due to previous error
```

## Working Code

The intent is fairly clear: we want to construct a new `TcpStream` using a method that follows the [Rust naming conventions](https://doc.rust-lang.org/1.0.0/style/style/naming/README.html) for constructors, but that method is not available. Instead the solution is likely to be either `TcpStream::connect` or
`TcpStream::connect_timeout`:

```rust
use std::net::TcpStream;

fn main() {
   let stream = TcpStream::connect("localhost:8080");
}
```

## Diagnostics Suggestions

When `new` is not available it'd be ideal if the compiler could suggest
alternatives. A first heuristic for which methods to suggest be methods on
the same struct that don't take any `self` params, have `Self` as their
return type, and aren't implemented through any trait.

For `TcpStream` this **would** include `TcpStream::connect` and
`TcpStream::connect_timeout`. But **not** `TcpStream::try_clone`,
`TcpStream::from_raw_fd`, `TcpStream::from_raw_socket` and
`std::net::Incoming::next`.

I'm not too sure how to structure the help message exactly, but I could
imagine something along these lines might work:

```txt
Compiling playground v0.0.1 (/playground)
error[E0599]: no function or associated item named `new` found for type `std::net::TcpStream` in the current scope
 --> src/main.rs:4:28
  |
4 |    let stream = TcpStream::new();
  |                            ^^^ function or associated item not found in `std::net::TcpStream`
  = help: Did you mean to use `std::net::TcpStream::connect` or `std::net::TcpStream::connect_timeout`?

error: aborting due to previous error
```

cc/ @estebank

**Comment by Centril** [comment]
Seems like `#[doc(alias(...))]`es should be added to the standard library to fix this.

**Comment by varkor** [comment]
This seems to be the same as https://github.com/rust-lang/rust/issues/51398.

**Comment by Centril** [comment]
Closing in favor of that.

**Comment by yoshuawuyts** [comment]
> Seems like `#[doc(alias(...))]`es should be added to the standard library to fix this.

@Centril For the example I brought up, how would an `#[doc(alias(...))]` work? The `new` method does *not* exist on `TcpStream`. So it shouldn't quality as an alias. Additionally this is intended as an *automated* mechanism to improve the quality of diagnostics, rather than a manual mechanism (like attributes) which would need to be opted into.

While both cases do touch on improving diagnostics for missing methods, I don't think these are equivalent.

**Comment by Centril** [comment]
No but `TcpStream::connect` does exist, so e.g., `#[doc(alias(TcpStream::new))]` on it could add the information necessary (see e.g. `#[doc(alias = "memcpy")]` on `copy_nonoverlapping`) for the compiler to provide the diagnostic.

But I suppose the heuristic you've suggested might work without attributes, although I suspect it would suggest too many false positives, but let's reopen I guess.

**Comment by estebank** [comment]
@yoshuawuyts what do you think of the following?

<img width="779" alt="Screenshot 2023-10-20 at 6 13 57 PM" src="https://github.com/rust-lang/rust/assets/1606434/8492d971-3f5a-45ee-8672-a986ed0c16dc">

**Comment by yoshuawuyts** [comment]
@estebank oh I love it!
