### ISSUE TITLE
Inappropriate "moved value" error

### ISSUE THREAD

**Issue by paulkass** [rust-lang/rust#69536]
Having an uninitialized mutable value in a loop initialized through a mutable borrow causes a compile time error about value moving out of the loop.

I tried this code:

```rust
fn foo() {
    loop {
        let mut bytes;
        bar(&mut bytes);
        println!("{}", bytes);
    }
}

fn bar(a: &mut String) {
    *a = String::from("bar");
}

fn main() {
  foo();
}
```

I expected to see this happen: I expected the code to compile and infinitely print "bar".

Instead, this happened: I got an error saying:

```
error[E0382]: borrow of moved value: `bytes`
 --> src/lib.rs:4:13
  |
3 |         let mut bytes;
  |             --------- move occurs because `bytes` has type `std::string::String`, which does not implement the `Copy` trait
4 |         bar(&mut bytes);
  |             ^^^^^^^^^^ value borrowed here after move
5 |         println!("{}", bytes);
6 |     }
  |     - value moved here, in previous iteration of loop
```

### Meta

`rustc --version --verbose`:
```
rustc 1.43.0-nightly (6d69caba1 2020-02-27)
binary: rustc
commit-hash: 6d69caba110c0c2fb90180df1cbc8be5033b91d4
commit-date: 2020-02-27
host: x86_64-unknown-linux-gnu
release: 1.43.0-nightly
LLVM version: 9.0
```

<details><summary>Backtrace</summary>
<p>

Not applicable, since code doesn't compile.

</p>
</details>

**Comment by Centril** [comment]
The code shouldn't compile, as `bytes` would be uninitialized when calling `bytes` (which is local to each iteration of the loop), which means that `&mut bytes` would sent over uninitialized memory over to `bar`.

However, the diagnostic seems misleading. It would be better to show something like:
```rust
error[E0381]: borrow of possibly-uninitialized variable: `bytes`
 --> src/lib.rs:3:13
  |
3 |         bar(&mut bytes);
  |             ^^^^^^^^^^ use of possibly-uninitialized `bytes`
```

cc @mark-i-m @matthewjasper

**Comment by paulkass** [comment]
I guess this is out of the scope of this particular issue, but what would be a good way of initializing `bytes` if you know it's going to be overridden in the next method? Just putting `let bytes = String::from("hi")` seems likes a pretty ad-hoc solution.

**Comment by mark-i-m** [comment]
@paulkass Perhaps `String::new()`, which does no allocation.

**Comment by estebank** [comment]
Current output:

```
error[[E0381]](https://doc.rust-lang.org/stable/error_codes/E0381.html): used binding `bytes` isn't initialized
 --> src/main.rs:4:13
  |
3 |         let mut bytes;
  |             --------- binding declared here but left uninitialized
4 |         bar(&mut bytes);
  |             ^^^^^^^^^^ `bytes` used here but it isn't initialized
  |
help: consider assigning a value
  |
3 |         let mut bytes = Default::default();
  |                       ++++++++++++++++++++
```
