### ISSUE TITLE
Revisit trailing tokens in assert!

### ISSUE THREAD

**Issue by adlerd** [rust-lang/rust#69531]
About 10 months ago it was necessary to permit typos to become temporary non-errors due to #60024 slipping into a stable release. Since #60039, the compiler has issued a "this will become an error" warning for a subset of accidentally-allowed uses ([Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=51d2b03c4f8a7147d1f7d11907dae607)):

```
fn main() {
    assert!(true "whatever");      // Intended: error. Currently: warning.
    assert!(true;);                // Intended: error. Currently: warning.
    assert!(true some extra junk); // Intended: error. Currently: error.
}
```

Version: 1.43.0 2020-02-26 nightly

Since the fix has been in for far longer than the bug, it would be great to close the loop on this by removing the special cases or converting them to errors.

**Comment by Centril** [comment]
It would be good to open a PR to change this to an error and do a crater run to see how things have progressed thus far.
