### ISSUE TITLE
make_ascii_lower/uppercase for Windows OsString?

### ISSUE THREAD

**Issue by TyPR124** [rust-lang/rust#69566]
The standard library seems to assume calling `make_ascii_uppercase()` on the underlying `[u8]` is safe on Windows, seen here: https://github.com/rust-lang/rust/blob/0eb878d2aa6e3a1cb315f3f328681b26bb4bffdb/src/libstd/sys/windows/process.rs#L35-L41

Would it be reasonable to add a `make_ascii_uppercase()` and/or `make_ascii_lowercase()` to Windows `OsStrExt` and/or `OsStringExt` to make this available to users of std?

Even if the internal representation of OsString changes down the road, I would assume the code above would still need to be replicated with the new representation, so it seems like it should be okay to have `make_ascii_uppercase` a stable/public API.

If this is a reasonable request, I am willing to make a PR with the appropriate methods implemented in the appropriate places.

**Comment by CryZe** [comment]
Considering OsString is a superset of UTF-8, make_ascii_* should work across all platforms.
