### ISSUE TITLE
memory leak in DiagnosticBuilder.into_diagnostic()

### ISSUE THREAD

**Issue by dwrensha** [rust-lang/rust#69600]
This code leaks the `Box` at `self.0`:

https://github.com/rust-lang/rust/blob/d3c79346a3e7ddbb5fb417810f226ac5a9209007/src/librustc_errors/diagnostic_builder.rs#L141-L144

The leak was introduced in 2fcd870711ce267c79408ec631f7eba8e0afcdf6. cc @nnethercote

**Comment by dwrensha** [comment]
We could avoid the leak and the `unsafe` by doing 

```rust
let diagnostic = self.0.diagnostic.clone();
self.cancel();
```

or if we're concerned about performance here, we could maybe do something with `drop_in_place()`.

**Comment by nnethercote** [comment]
Thanks for the report, I will measure the perf effects of the different alternatives.

I'd like to know how you found this -- code inspection? Some kind of tool?

**Comment by dwrensha** [comment]
I found it while running [fuzz-rustc](https://github.com/dwrensha/fuzz-rustc) and noticing that I kept running out of memory. I turned on `-Z sanitize=address` and this popped out.

**Comment by dwrensha** [comment]
Another alternative could be to `std::mem::replace()` in a dummy diagnostic, instead of cloning the existing one.

**Comment by dwrensha** [comment]
Below is an example compiler input that triggers the leak:

```rust
str// bass (FIXMoo {
}


         )
```

**Comment by dwrensha** [comment]
Simpler example that triggers the leak: just a single closing brace
```rust
}
```
