### ISSUE TITLE
Type inference failure in assert_eq!

### ISSUE THREAD

**Issue by jgouly** [rust-lang/rust#69610]
I'm not sure if this is a bug or a feature, or if this code errors as intended.

I tried this code:

```rust
fn foo() -> Vec<u32> {
    todo!()
}

fn test() {
    assert_eq!(vec![], foo());
}

```

I expected to see this happen: type is inferred

Instead, this happened: type inference fails

    error[E0282]: type annotations needed
       |
    75 |     assert_eq!(vec![], cycles);
       |                ^^^^^^ cannot infer type for type parameter `T`
       |

### Meta

`rustc --version --verbose`:
```
rustc 1.43.0-nightly (6d69caba1 2020-02-27)
```

**Comment by jonas-schievink** [comment]
This looks like expected behavior to me, since `assert_eq` uses `vec![] == foo()` internally, which then can't infer the `PartialEq` impl.

**Comment by jgouly** [comment]
@jonas-schievink Thanks, I understand it now. I can swap the operands to get it to infer it!

**Comment by jonas-schievink** [comment]
`assert_eq!(a, b)` does both `a == b` and `b == a`, so in this case you have to provide type annotations like `Vec::<u32>::new()`

**Comment by jgouly** [comment]
Probably not the right place for this conversation.. but why does it do both?

**Comment by jonas-schievink** [comment]
Probably just as an additional check that your PartialEq impl is symmetric, but I don't know for sure

**Comment by ollie27** [comment]
> 
> 
> `assert_eq!(a, b)` does both `a == b` and `b == a`, so in this case you have to provide type annotations like `Vec::<u32>::new()`

@jonas-schievink that hasn't been the case for nearly 5 years: https://github.com/rust-lang/rust/commit/5cf126ae2f6af1cdac901f6995e3c2bab35e587f#diff-a5a0682c18717c9e06e867e1cf2abeb8

**Comment by jonas-schievink** [comment]
Oh. Not sure why I thought that then. I even tested swapping the operands in the example above, and that made it work.
