### ISSUE TITLE
[tracking issue] const fn mem::forget

### ISSUE THREAD

**Issue by DutchGhost** [rust-lang/rust#69616]
`mem::forget` is just a thin wrapper around `ManuallyDrop::new` which is already a const fn. `mem::forget` can thus also be a const fn. The usage would be in const functions dealing with generics where you dont want the generics to get dropped.

* [x] implementation (#69617)
* [x] documentation
* [ ] stabilization

**Comment by ratijas** [comment]
Just for the bookkeeping, with `mem::forget` stabilized by #73887, shouldn't the stabilization checkbox at the top become checked on?

**Comment by DutchGhost** [comment]
> Just for the bookkeeping, with `mem::forget` stabilized by #73887, shouldn't the stabilization checkbox at the top become checked on?

Good point, checked the box now!
