### ISSUE TITLE
CI: don't block further CI results on tidy/fmt

### ISSUE THREAD

**Issue by CAD97** [rust-lang/rust#69613]
[Some irlo context.](https://internals.rust-lang.org/t/forced-rustfmt-is-a-roadblock-to-contributing/11913?u=cad97)

Currently, if a PR has even trivial tidy/fmt errors, the tidy/fmt error early-exits the PR smoke test CI and reports just the tidy/fmt error.

This can be problematic because of the long test cycle; it would reduce the number of required pushes/CI runs if CI could report both tidy/fmt nits alongside the test harness state.

**Comment by Mark-Simulacrum** [comment]
We can likely move tidy to the mingw-check builder and skip it on the longer builder.
