### ISSUE TITLE
Looking to Capture Type Documentation

### ISSUE THREAD

**Issue by YoshikiTakashima** [rust-lang/rust#69662]
Hello!

I'm Yoshiki, a PhD student at CMU.

I was wondering if there was a way to easily get type information from rust's documentation.

For example, I want to enumerate all functions of **std::string::String**, and get the type signatures for them.

I noticed search-by-type was implemented in PR#23289, but it looks like the search-index.js currently being used is different from the one implemented in (probably performance reasons).

Any help with the JSON format, or suggestions on alternative methods will be greatly appreciated.

Thank you for your time.
~Yoshiki

**Comment by steveklabnik** [comment]
Hi!

We try to keep the bug tracker for bugs only; these kinds of questions are better asked on users.rust-lang.org. Thank you!

**Comment by YoshikiTakashima** [comment]
Got it.

Thank you!
