### ISSUE TITLE
Inner attributes on block expressions on match arms are not allowed

### ISSUE THREAD

**Issue by lukas-code** [rust-lang/rust#69675]
I tried this code:

```rust
fn main() {
    match 0 {
        _ => {
            #![allow(unused_variables)]
        }
    }
}
```

I expected to see this happen: The code compiles.

Instead, this happened: The code fails to compile with the following error:
```text
error[E0658]: attributes on expressions are experimental
 --> test.rs:4:13
  |
4 |             #![allow(unused_variables)]
  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: see issue #15701 <https://github.com/rust-lang/rust/issues/15701> for more information
  = help: add `#![feature(stmt_expr_attributes)]` to the crate attributes to enable

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
```

The following code compiles as expected:
```rust
fn main() {
    match 0 {
        _ => {{ // <-- double braces
            #![allow(unused_variables)]
        }}
    }
}
```

### Meta
`rustc --version --verbose`:
```rustc 1.43.0-nightly (d3c79346a 2020-02-29)
binary: rustc
commit-hash: d3c79346a3e7ddbb5fb417810f226ac5a9209007
commit-date: 2020-02-29
host: x86_64-unknown-linux-gnu
release: 1.43.0-nightly
LLVM version: 9.0
```

**Comment by ehuss** [comment]
I believe this is working as expected.  Attributes can be applied to blocks as *statements*, but not as *expressions*.  In some cases, attributes can be used in expressions, but those were accidentally stabilized in #36995, and nobody noticed for a long time. The current stable rules are detailed in https://doc.rust-lang.org/reference/expressions/block-expr.html#attributes-on-block-expressions.   Stabilization in other expression positions is tracked in the linked issue (#15701).

**Comment by Centril** [comment]
@ehuss's summary is accurate. Closing as not-a-bug.
