### ISSUE TITLE
Docs for std::fmt could mention locale

### ISSUE THREAD

**Issue by ExpHP** [rust-lang/rust#69681]
From this discussion: https://users.rust-lang.org/t/is-f64-to-string-localized/39011

> **dan5sch:**
> On this subject: looking into this question, I was surprised how hard it was to get an up-or-down answer from the standard library documentation. Even a detailed page like the module-level documentation for std::fmt doesn't appear to mention the existence of locale-specific conventions and clarify that Rust doesn't vary behavior by locale, when this is a natural question coming from other languages.

> **ExpHP:**
> The concept of a "locale" doesn't even exist in Rust. That's an operating system concept, whereas rust is the sort of language that can be used to write operating systems.
> 
> At present, even the standard library of Rust (where abstractions over the operating system go) does not expose an interface for working with locales.

> **dan5sch:**
> To put my first comment another way: I'm surprised the module documentation doesn't bring up the subject and say what you said directly, when many people like OP will wonder about this.

Yeah, it should probably be mentioned, to give users something to Ctrl+F for.

**Comment by Dylnuge** [comment]
I'm happy to take a pass at this; is a cautionary note in https://doc.rust-lang.org/std/fmt/ the right place or is there somewhere better for it to be?
