### ISSUE TITLE
Exhaustiveness checker errors on unconstructible enum variant

### ISSUE THREAD

**Issue by matprec** [rust-lang/rust#69696]
```rust
use std::marker::PhantomData;

enum Void {}

enum Foo<T=()> {
    Bar,
    Baz,
    Phantom(PhantomData<T>, Void)
}

pub fn test(f: Foo) {
    match f {
        Foo::Bar => println!("Bar"),
        Foo::Baz => println!("Baz"),
    }
}
```

[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=0497db958ae59eb695a000dc5ce2b953)

I expect this to work, since the Phantom case is not constructible, since it contains a Void type.

The exhaustiveness checker instead errors because it thinks that the Phantom case should be covered as well:
```
error[E0004]: non-exhaustive patterns: `Phantom(_, _)` not covered
  --> src/lib.rs:12:11
   |
5  | / enum Foo<T=()> {
6  | |     Bar,
7  | |     Baz,
8  | |     Phantom(PhantomData<T>, Void)
   | |     ------- not covered
9  | | }
   | |_- `Foo` defined here
...
12 |       match f {
   |             ^ pattern `Phantom(_, _)` not covered
   |
   = help: ensure that all possible cases are being handled, possibly by adding wildcards or more match arms

error: aborting due to previous error

```
### Meta

Happens on stable and nightly as of 2020-03-04

**Comment by hellow554** [comment]
But it's correct. Although it can't be constructed, you have to use `_ => {}` for an exhaustive match.
This construct can be used as a workaround for older compiler, that don't support the `#[non_exhaustive]` attribute.
So I think this complain is valid?!

**Comment by matprec** [comment]
I don't think that this is a proper workaround for the `#[non_exhaustive]` attribute, since it doesn't forbid matching explicitly against the `Phantom` variant. The RFC cites `#[doc(hidden)]` in the [How we do this today](https://github.com/rust-lang/rfcs/blob/master/text/2008-non-exhaustive.md#how-we-do-this-today) section.

**Comment by matprec** [comment]
I'd argue that this should be valid, since the error states its intention as "help: ensure that all **possible** cases are being handled" (emphasis mine), yet the `Phantom` variant is not "possible".

**Comment by Centril** [comment]
This compiles if you use `#![feature(exhaustive_patterns)]`, so I'm closing in favor of https://github.com/rust-lang/rust/issues/51085.
