### ISSUE TITLE
Do you have lost compiler based on intel c++ compiler

### ISSUE THREAD

**Issue by AnovaCean** [rust-lang/rust#69699]
I know rust compare the has many versions.Like some of them based on gnu And some of them are based on msvc.Do you have some lessons which are based on intel c++ Compiler.When rustup-init.exe asks me "Default host triple?",I tried input "x 86_64-pc-windows-icc".But it replied That couldn't be converted to practial triple.So can you tell me how to install rust compiler the wage based on intel c++ compiler.

**Comment by jonas-schievink** [comment]
Hi! This issue tracker is mainly meant for bug reports and concrete, small feature requests. Questions like this are better asked in the user forum at https://users.rust-lang.org/ or on [one of the chat platforms](https://www.rust-lang.org/community) used by the Rust community.

**Comment by AnovaCean** [comment]
> Hi! This issue tracker is mainly meant for bug reports and concrete, small feature requests. Questions like this are better asked in the user forum at https://users.rust-lang.org/ or on [one of the chat platforms](https://www.rust-lang.org/community) used by the Rust community.
Sorry, there are some mistakes happened when I am typing title.I mean that do you have rust compiler which is based on intel c++ compiler, except the versions based on gnu and msvc.I often called in for x86 platforms.So intel c++compiler is a better choosing than gnu.

**Comment by retep998** [comment]
To answer your question. `gnu` vs `msvc` is for which *linker* toolchain is used. The Intel C++ compiler isn't a linker toolchain but rather just a compiler, and they key reason people use it is for its code generation. Rust always use LLVM for code generation currently regardless of what target is being used.

**Comment by AnovaCean** [comment]
Thanks!
