### ISSUE TITLE
async Drop tracking issue

### ISSUE THREAD

**Issue by gliderkite** [rust-lang/rust#69695]
I couldn't find any tracking issue for `async Drop`. Please feel free to close this issue if duplicate.

Related references:
- @withoutboats [blog post](https://boats.gitlab.io/blog/post/poll-drop/)
- [Internal discussion](https://internals.rust-lang.org/t/asynchronous-destructors/11127)

**Comment by jonas-schievink** [comment]
There's nothing to track, this still needs to go through an RFC.
