### ISSUE TITLE
Rustdoc many code examples wrapped in fn main {} when copied to clipboard

### ISSUE THREAD

**Issue by BinaryShrub** [rust-lang/rust#69758]
https://doc.rust-lang.org/book/ch11-02-running-tests.html

TL&DR: quite a few examples are wrapped by `fn main() { ... }` which cause them to be incorrect.

Example:

I'm going through the book and noticed when copying from Listing 11-10, using the copy icon, that it results in the following code:

``` rust
#![allow(unused_variables)]
fn main() {
fn prints_and_returns_10(a: i32) -> i32 {
    println!("I got the value {}", a);
    10
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn this_test_will_pass() {
        let value = prints_and_returns_10(4);
        assert_eq!(10, value);
    }

    #[test]
    fn this_test_will_fail() {
        let value = prints_and_returns_10(8);
        assert_eq!(5, value);
    }
}
}
```

This `fn main()` wrapper causes `use super::*;` to fail and result in the following error:
``` rust
error[E0425]: cannot find function `prints_and_returns_10` in this scope
  --> src/lib.rs:15:21
   |
15 |         let value = prints_and_returns_10(4);
   |                     ^^^^^^^^^^^^^^^^^^^^^ not found in this scope

error[E0425]: cannot find function `prints_and_returns_10` in this scope
  --> src/lib.rs:21:21
   |
21 |         let value = prints_and_returns_10(8);
   |                     ^^^^^^^^^^^^^^^^^^^^^ not found in this scope
```

Which is not the error described in the book. My assumption is that the wrapper `fn main()` function should actually not be included and the copy should instead be:

``` rust

#![allow(unused_variables)]
fn prints_and_returns_10(a: i32) -> i32 {
    println!("I got the value {}", a);
    10
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn this_test_will_pass() {
        let value = prints_and_returns_10(4);
        assert_eq!(10, value);
    }

    #[test]
    fn this_test_will_fail() {
        let value = prints_and_returns_10(8);
        assert_eq!(5, value);
    }
}

```

**Comment by ehuss** [comment]
This is an issue for https://github.com/rust-lang/book/.  

The solution is to add `fn main() {}` to https://github.com/rust-lang/book/blob/master/listings/ch11-writing-automated-tests/listing-11-10/src/lib.rs along with appropriate anchor annotations (https://github.com/rust-lang/book/blob/master/listings/ch11-writing-automated-tests/listing-11-08/src/lib.rs is an example), and add the anchor to the `{{#rustdoc_include …}}` markup.

**Comment by BinaryShrub** [comment]
13-1 is also broken

**Comment by GuillaumeGomez** [comment]
This is not a rustdoc issue, indeed. We do not modify the content when someone is copying a codeblock content to clipboard. Please open the issue on the correct repository. :)
