### ISSUE TITLE
wrong deprecation version in Error::description

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#69751]
#66919 has added `#[rustc_deprecated(since = "1.41.0")]` to `Error::description` but the PR made it only into Rust 1.42.0. Thus the version number should be adjusted. cc @dtolnay

**Comment by Mark-Simulacrum** [comment]
We would be happy to accept a PR for this. I suppose it's a trivial enough fix that I would even be willing to backport it (so we avoid 1.42 indicating incorrectly), but only if we get it in quickly enough.

cc @pietroalbini re:backport, since you're doing release

**Comment by est31** [comment]
I won't do it but it should be easy enough.

**Comment by Dylnuge** [comment]
I just made a PR for updating this; this is my first contribution to the project (please let me know if I did the process right)

**Comment by steveklabnik** [comment]
I just noticed this and saw a PR already existed, amazing! 👍 to a backport.
