### ISSUE TITLE
Enabling LTO generates broken code

### ISSUE THREAD

**Issue by almindor** [rust-lang/rust#69752]
Enabling LTO optimizations on [this project](https://github.com/almindor/pinetime-quickstart) as set in [Cargo.toml](https://github.com/almindor/pinetime-quickstart/blob/master/Cargo.toml#L30-L33) produces broken code in release mode for the `ferris_display` example binary.

Removing the profile setup lines fixes it although it seems to be specifically tied to `lto = true`.

If LTO is not enabled the code is almost 2x in text section size (using `size`) and works as expected.

Enabling LTO breaks the code somehow. It does "run" and even the final "rendering done" message is shown, however nothing related to rendering seems to be done. The display stays exactly as before, as if the `embedded-graphics` pipeline did not get called.

I'll try to find out if the missing piece can be identified. Sadly there's no easy way to test this outside of having a pinetime device.

NOTE: I have tested with version 1.38.0 and 1.32.0 in addition to latest stable and all seem to have the same behavior. Another person also reproduced this on their setup.

### Meta

`rustc --version --verbose`:
```
rustc 1.41.1 (f3e1a954d 2020-02-24)
binary: rustc
commit-hash: f3e1a954d2ead4e2fc197c7da7d71e6c61bad196
commit-date: 2020-02-24
host: x86_64-unknown-linux-gnu
release: 1.41.1
LLVM version: 9.0
```

**Comment by jonas-schievink** [comment]
Is there anything that indicates that that is caused by a bug in Rust and not, say, undefined behavior in one of the dependencies?

Have you tried using the nRF52 HAL from master? The crates.io release is quite old by now.

**Comment by almindor** [comment]
I've created [the LTO branch](https://github.com/almindor/pinetime-quickstart/tree/lto) for the project which uses latest master releases of the hal, embedded-graphics and the driver, same result.

Disabling LTO in the release profile makes it work fine, enabling it makes it miss rendering (it seems).

I suspect the actual drawing SPI transfer is not being called with LTO enabled for whatever reason, but I have to do more tests to confirm that. Debug mode works as well of course.

**Comment by almindor** [comment]
This is a pin timing issue, my bad.
