### ISSUE TITLE
Testing the case `assert_fake_source_file`  was used to test for

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#69775]
Context https://github.com/rust-lang/rust/pull/66364#discussion_r388767932.

> Can you open an issue about perhaps testing the case assert_fake_source_file was used to test (SourceFile::is_real() returning false) and leaving a FIXME comment here mentioning that issue and/or in the auxiliary file where assert_fake_source_file is defined?

cc @eddyb

**Comment by Enselic** [comment]
Triage: I don't understand this issue, and I doubt anyone does by now. It has remained open for 4 years without anything at all happening. Let's close as "not actionable"/"obsolete".

**Comment by jieyouxu** [comment]
FTR, this FIXME is still present in one test https://github.com/rust-lang/rust/blob/3c1e750364012e78dcc46e5c96973fab42c7b295/tests/ui/proc-macro/span-api-tests.rs#L11, but I don't understand the FIXME either.
