### ISSUE TITLE
Tracking Issue for OneSidedRange

### ISSUE THREAD

**Issue by cramertj** [rust-lang/rust#69780]
The feature gate for the issue is `#![feature(one_sided_range)]`, introduced in https://github.com/rust-lang/rust/pull/62282.

**Comment by KodrAus** [comment]
Since the linked implementation PR was closed (just from inactivity) we don't really have a feature to track here yet. I'll go ahead and close this one now, but if #62282 resurfaces in the future we can re-open this!

**Comment by its-the-shrimp** [comment]
Should this be reopened now that `OneSidedRange` is on nightly? No clue when it got there, but it is most definitely there, my eyes don't deceive me

https://doc.rust-lang.org/std/ops/trait.OneSidedRange.html

**Comment by its-the-shrimp** [comment]
Also, should this trait be `unsafe`? Since the guarantee of
> must return `Bound::Unbounded` from one of `RangeBounds::start_bound` or `RangeBounds::end_bound`.

Can't be represented by this trait directly (in its current form at least)

Another possibility is the following API for this trait:
```rs
enum OnlyBound<T> {
    Start(Bound<T>),
    End(Bound<T>),
}

trait OneSidedRange<T>: RangeBounds<T> {
    fn bound(&self) -> OnlyBound<T>;
}
```

**Comment by tgross35** [comment]
Reopening as it this does indeed exist and the tracking issue points here, added in https://github.com/rust-lang/rust/pull/88502. See https://github.com/rust-lang/rust/issues/62280 for some discussion about what to do with these traits (added as unresolved questions).

**Comment by tgross35** [comment]
These types should probably move to the newly stable `core::range`. Added an unresolved question so we don't forget it.
