### ISSUE TITLE
std::fs::read makes an extra read call

### ISSUE THREAD

**Issue by joshtriplett** [rust-lang/rust#69803]
Steps to reproduce:

- Create a 1MB test file (`dd if=/dev/zero of=testfile bs=1M count=1`)
- Compile this program: `fn main() { std::fs::read("testfile").unwrap(); }`
- Run it under strace to see the system calls it makes.

Rust performs the following syscalls:

```
read(3, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 1048577) = 1048576
read(3, "", 1)                          = 0
```

The first `read` call does cleverly read one extra byte beyond the file size returned by stat, so that it can check for EOF in the first call. But then a second `read` call for one byte occurs anyway.

**Comment by cuviper** [comment]
> The first `read` call does cleverly read one extra byte beyond the file size returned by stat, so that it can check for EOF in the first call. But then a second `read` call for one byte occurs anyway.

Your first `read` came up a byte short, but it's always allowed to return partial reads. We can't really know it's EOF until we read 0 bytes -- despite the initial `stat` size, the file could still be growing. We need the extra to have space to _try_ that final read, even though we expect it to fail.

https://github.com/rust-lang/rust/blob/3dbade652ed8ebac70f903e01f51cd92c4e4302c/src/libstd/fs.rs#L224-L230

**Comment by RalfJung** [comment]
The comment [here](https://github.com/rust-lang/rust/blob/3dbade652ed8ebac70f903e01f51cd92c4e4302c/src/libstd/io/mod.rs#L2290) also talks about a "final zero-byte read", but unfortunately does not say where in the code that is happening.
I assume it refers to the fact that we only break [the read loop here](https://github.com/rust-lang/rust/blob/3dbade652ed8ebac70f903e01f51cd92c4e4302c/src/libstd/io/mod.rs#L395) on `Ok(0)`?

**Comment by contrun** [comment]
I tried to modify [this line](https://github.com/rust-lang/rust/blob/3dbade652ed8ebac70f903e01f51cd92c4e4302c/src/libstd/io/mod.rs#L399) into
```
            Ok(n) => {
                g.len += n;
                if g.buf.len() > g.len {
                    ret = Ok(g.len - start_len);
                    break;
                }
            }
```

This does not work. I encountered several other compilation failures. I guess I can not assume when the buffer is not fully filled, it is the EOF.

Then I checked out the behavior of `cat`. `cat` also makes an entra syscall.
```
read(3, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 131072) = 1024
write(1, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 1024) = 1024
read(3, "", 131072) 
```

**Comment by Mark-Simulacrum** [comment]
I think this is expected behavior (per https://github.com/rust-lang/rust/issues/69803#issuecomment-596827130), so I'm going to close. If there's docs for short reads indicating EOF then we can re-open.
