### ISSUE TITLE
Tracking Issue for const `mem::discriminant`

### ISSUE THREAD

**Issue by lcnr** [rust-lang/rust#69821]
The feature gate for the issue is `#![feature(const_discriminant)]`.

### History

- [x] Implementation: #69825
- [x] Stabilization PR: https://github.com/rust-lang/rust/pull/116240

### Unresolved issues

* [x] https://github.com/rust-lang/rust/issues/89765 ICE when used on zero variant enums

**Comment by RalfJung** [comment]
The intrinsic is [already implemented in Miri](https://github.com/rust-lang/miri/blob/e6a0c60a0feba65b2ced98b3eae4a2406a7d635e/src/shims/intrinsics.rs#L251), you can copy that to rustc if you want.

If you do, please also submit a PR to Miri to remove the implementation there.

**Comment by oli-obk** [comment]
Should we consider adding more symbol kinds to const eval (like the way pointers can't be read as bits) to ensure that this feature isn't used to read discriminants as integers? Or is doing so at compile time actually something that enables legit use cases?

**Comment by RalfJung** [comment]
What we do for pointers is born out of necessity. For discriminants (a) I cannot think of a practical way to do so, and (b) I view this the same as layout details: it is not UB to use raw pointers to observe and mess with `repr(Rust)` layout *if you get it right*, but layout might change any time so you have no way to be sure that whatever is right for current Rust will remain right in the future.

**Comment by lcnr** [comment]
Would this be to prevent something like this (which may break due to compiler updates)?

```rust
#![feature(core_intrinsics, const_discriminant)]

const ARR: [u32; std::intrinsics::discriminant_value(&Some(7)) as usize] = [42];
```

**Comment by RalfJung** [comment]
@lcnr we already have that with things like
```rust
const ARR: [u32; mem::size_of::<Option<Option<bool>>> = [42];
```

**Comment by stephanemagnenat** [comment]
It seems that `mem::discriminant` is now const, as [the doc shows](https://doc.rust-lang.org/std/mem/fn.discriminant.html). Shouldn't this issue be closed?

**Comment by memoryruins** [comment]
@stephanemagnenat the const part of it is still unstable.

https://github.com/rust-lang/rust/blob/d95745e5fa39680d97a52d0e07ed7842b163bacc/library/core/src/mem/mod.rs#L1014-L1018

If you view nightly docs, it is much clearer, showing `(const: unstable)` next to the function. It will take a couple of releases before that rustdoc feature is part of stable docs.

![image](https://user-images.githubusercontent.com/6868531/123320192-70d9c100-d4ff-11eb-8db0-9d05a1f53ec9.png)

**Comment by stephanemagnenat** [comment]
Thank you for the update!

**Comment by stephanemagnenat** [comment]
Btw, I saw on the PR (#69825) that people were asking for a use case. I have one: I am making a parser for a DSL that must match existing data structures, and these can have members of various types. I thus have a custom `Value` type, and would like these data structures to return a description of themselves that contains which variant of `Value` they accept. I was planning to use the `Discriminant<T>` type, but as it is not stable, I'll probably use the [enum-kinds](https://crates.io/crates/enum-kinds/) crate for now.

**Comment by aleokdev** [comment]
We have a similar issue in https://github.com/mapeditor/rs-tiled, so far we've resorted to [creating a `Tag` enum](https://github.com/mapeditor/rs-tiled/blob/dab7cb6bbd544e83863fc13ae05e7e471de22fe6/src/layers/mod.rs#L25) but using the discriminant would be much cleaner. One thing I'm unsure about though, is how to refer to the discriminant of a variant at compiletime without actually creating an instance of the enum.

**Comment by oli-obk** [comment]
> One thing I'm unsure about though, is how to refer to the discriminant of a variant at compiletime without actually creating an instance of the enum.

I don't think that is possible. There is currently no work being done to allow this, and it's unclear to me how that could be done without making enum variants their own types that you can mention without needing a value

**Comment by aleokdev** [comment]
Maybe some kind of macro could do the job, like `std::mem::discriminant_of!(Enum::Variant)`.

**Comment by oli-obk** [comment]
I'm not saying we can't add it, but that there are no plans for it. This issue is also the wrong place to figure out a design for it, so maybe open a thread on the internals forum?

**Comment by stephanemagnenat** [comment]
I have a use case (currently I ended up using the `strum` and `num_traits` packages). I have a block-based visual programming language (see https://cand.li for a screenshot). Each block has possibly parameters (e.g. speed vector), and all blocks together are joined in a union. Sometimes, we want configurations where only a subset of blocks can be used (e.g. simple mode). It would be convenient to have such configurations const, so that they can be used in const contexts (as a global configuration for example). I had additional use cases, within a parser/compiler for a DSL, but I have forgotten the details now that the code is using the aforementioned packages.

**Comment by dtolnay** [comment]
@rfcbot fcp merge

Adds `const` on the following function, which has been stable since Rust 1.21:

```rust
// core::mem

pub const fn discriminant<T>(v: &T) -> Discriminant<T>
```

Example use cases benefiting from const: https://github.com/rust-lang/rust/issues/69821#issuecomment-868283867, https://github.com/rust-lang/rust/issues/69821#issuecomment-1184123296

**Comment by nikomatsakis** [comment]
@rfcbot reviewed

**Comment by Dylan-DPC** [comment]
Closing this as it has been stabilised.
