### ISSUE TITLE
Unreachable code may violate borrow rules

### ISSUE THREAD

**Issue by CAD97** [rust-lang/rust#69834]
When code is considered provably unreachable, it is allowed to violate the borrow checker rules. This isn't a problem, per-say, because provably unreachable code will never be run. However, this is quite non-intuitive, and can lead to code not being properly checked while parts of it are stubbed out with `todo!()`.

[This code compiles fine with unreachable code that violates the borrow rules.](https://play.rust-lang.org/?edition=2018&gist=77160fdadf2e79e526cb9f65d35fe588)

```rust
fn main() {
    let map: BTreeMap<String, Vec<u8>> = panic!();
    for items in map.values() {
        items.sort();
    }
}
```

```
warning: unreachable expression
  --> src/lib.rs:11:18
   |
10 |     let map: BTreeMap<String, Vec<u8>> = panic!();
   |                                          -------- any code following this expression is unreachable
11 |     for items in map.values() {
   |                  ^^^^^^^^^^^^ unreachable expression
   |
   = note: `#[warn(unreachable_code)]` on by default
```

[When the code is not considered provably unreachable, compilation correctly errors.](https://play.rust-lang.org/?edition=2018&gist=0a3fcbba244f4ccce7807eef3cf49d08)

```rust
fn hole<T>() -> T {
    panic!()
}

fn main() {
    let map: BTreeMap<String, Vec<u8>> = hole();
    for items in map.values() {
        items.sort();
    }
}
```

```
error[E0596]: cannot borrow `*items` as mutable, as it is behind a `&` reference
  --> src/lib.rs:12:9
   |
11 |     for items in map.values() {
   |         ----- help: consider changing this to be a mutable reference: `&mut std::vec::Vec<u8>`
12 |         items.sort();
   |         ^^^^^ `items` is a `&` reference, so the data it refers to cannot be borrowed as mutable
```

**Comment by nagisa** [comment]
This is kind-of by construction, as modern borrowchecker works on CFG (and actively needs that information), and CFG does not unreachable code. (though we do have a concept of false edges...)

**Comment by Centril** [comment]
Closing as not-a-bug per @nagisa's comment.
