### ISSUE TITLE
ICE with `impl_trait_in_bindings`

### ISSUE THREAD

**Issue by JohnTitor** [rust-lang/rust#69840]
### Code

This snippet is found in #60473.

Reduced:
```rust
#![feature(impl_trait_in_bindings)]
#![allow(incomplete_features)]

struct A<'a>(&'a ());

trait Trait<T> {}

impl<T> Trait<T> for () {}

pub fn foo<'a>() {
    let _x: impl Trait<A<'a>> = ();
}

fn main() {}

```

[playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=842adc0fe2c0b7bd2647341f05a6a8d8)

[playground (original)](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=be294fd00d76c662e3991b7fe4a29942)

### Meta

`rustc --version --verbose`:
```
1.43.0-nightly (823ff8cf1 2020-03-07)
```

### Error output

```
error: internal compiler error: opaque type with non-universal region substs
  --> src/main.rs:10:1
   |
10 | / pub fn foo<'a>() {
11 | |     let _x: impl Trait<A<'a>> = ();
12 | | }
   | |_^

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', src/librustc_errors/lib.rs:355:17
```

**Comment by hellow554** [comment]
There's no need to put the two `let _x` into different functions, you can put them both in `foo`.

**Comment by CDirkx** [comment]
Like #70971, when using an anonymous binding (`_`), the above code [compiles](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=ff748ac719ab13869120fbe4c50a4377):
```rust
let _: impl Trait<A<'a>> = ();
```

**Comment by Alexendoo** [comment]
No longer ICEs since #72080
