### ISSUE TITLE
Support installing with linking to non-system libraries

### ISSUE THREAD

**Issue by Evpok** [rust-lang/rust#69865]
Currently, toolchains installed with rustup use system library path and the system dynamic linker.

In some environment it makes installing and using rust overly complicated. [My specific use case](https://users.rust-lang.org/t/why-would-rust-ran-in-linuxbrew-try-to-link-to-system-libc/37435) is a shared environment where the system libs are quite old so users manage their own installations with linuxbrew in their respective homes.

It would be nice to have a way to tell rustup to use other linkers and other library path. Maybe with a flag like `--custom-linker …`

**Comment by Evpok** [comment]
Fair enough. I was thinking about something like rustup setting rpath in the toolchain binaries to the custom location, but maybe that's not the right way to go about it.

**Comment by the8472** [comment]
Wouldn't it be sufficient to prepend something to `PATH` and `LD_LIBRARY_PATH`?

**Comment by Evpok** [comment]
@the8472 Maybe in wrappers around toolchain executables? That's one reason why I was thinking of doing it at rustup level since there are already wrappers defined there. Doing that in the parent shell environment is not a good idea as you still have to rely on *some* system executables and that might break them.

**Comment by Enselic** [comment]
Triage: Since this is out of scope of rustup and rustc binaries and libs are distributed as-is, there is no way I can think of to solve this upstream. It seems to me as if you need to use techniques such as chroot,docker,LD_LIBRARY_PATH, etc. Or build your own Rust toolchain.

Closing as won't fix.
