### ISSUE TITLE
`MaybeRequiresStorage` for generators is not necessary

### ISSUE THREAD

**Issue by ecstatic-morse** [rust-lang/rust#69902]
Continuing from discussion in #69716.

`MaybeRequiresStorage` (introduced in #60187 as `RequiresStorage`) is one of four dataflow analyses used to determine what locals are live across yield points or live at the same time as other locals during the MIR generator pass. I don't see any reason we're not using a [liveness analysis](https://en.wikipedia.org/wiki/Live_variable_analysis) exclusively for this, with an additional check against `MaybeBorrowedLocals ∩ MaybeStorageLive` in cases where borrows can live across suspension points (immovable generators).

`MaybeRequiresStorage` is basically `MaybeStorageLive` with some additional logic that kills locals after they are moved out of. It also incorporates the `MaybeBorrowedLocals` analysis as part of its transfer function, which is probably unnecessary, since we could check the results of `MaybeBorrowedLocals` directly at each yield point. If there is often a large gap between the point at which a local is moved out of and the point at which it is marked `StorageDead`, we could augment `MaybeStorageLive` to kill locals when they are moved out of.

The liveness analysis in [`librustc_mir/util/liveness.rs`](https://github.com/rust-lang/rust/blob/master/src/librustc_mir/util/liveness.rs) will implicitly handle moved-from locals as long as there are no future accesses to them, which is what causes a variable to be marked as live.

I'd like refactor the liveness parts of the MIR generator pass, but will wait for buy-in from its authors. I think that basing the current storage optimization on a combination of a few well-known dataflow analyses will make it easier to reason about and therefore fine-tune. This will involve using the liveness analysis (plus `MaybeBorrowedLocals` / `MaybeStorageLive` inside immovable generators) for [`compute_storage_conflicts`](https://github.com/rust-lang/rust/blob/a03921701cdfe0b2c5422240f3ae370ab21069f1/src/librustc_mir/transform/generator.rs#L599). Does anyone see a problem with this? @tmandry @jonas-schievink

**Comment by RalfJung** [comment]
> we could augment MaybeStorageLive to kill locals when they are moved out of.

Note that, until we have figured out MIR semantics more precisely, this could be problematic... depending on how the analysis results are used, anyway. Moving out of a variable and then putting something back in is legal in Miri right now, and is guaranteed to keep the local at the same address, so points to it may remain valid (modulo Stacked Borrows). `StorageDead` on the other hand is like `free` for a stack variable, all old pointers to it are definitely dangling now.

> If there is often a large gap between the point at which a local is moved out of and the point at which it is marked StorageDead

Maybe another option would be to improve `StorageDead` generation and move it closer to the move point.

**Comment by ecstatic-morse** [comment]
> Moving out of a variable and then putting something back in is legal in Miri right now, and is guaranteed to keep the local at the same address, so points to it may remain valid (modulo Stacked Borrows).

That's good to keep in mind. The current `MaybeRequiresStorage` [is suitably conservative here](https://github.com/rust-lang/rust/blob/c20d7eecbc0928b57da8fe30b2ef8528e2bdd5be/src/librustc_mir/dataflow/impls/storage_liveness.rs#L261), so it should behave the same as `MaybeStorageLive` for borrowed locals.

> Maybe another option would be to improve StorageDead generation and move it closer to the move point.

Yeah, I had #68622 in mind when I brought this up. Specifically the hypothetical `InvalidateBorrows` statement.
