### ISSUE TITLE
`rustdoc --test` erroneously turns text into doc test and fails

### ISSUE THREAD

**Issue by davepacheco** [rust-lang/rust#69905]
I apologize in advance if I'm misunderstanding the expected behavior here, but here goes.  I've got a file with these contents:

```rust
/*!
 * * Hello
 *     * World
 *
  * Lorem
 */
```

This is a little weird, but it's the minimum case I found to reproduce the issue.  The unusual leading space on line 5 is important.  (If you're wondering how I got here, it was from [rustfmt issue 4079](https://github.com/rust-lang/rustfmt/issues/4079).)

I expected that if I ran `rustdoc --test`, I would find that it passed after having run 0 tests, since there doesn't appear to be a doc test here.

But `rustdoc --test` reports:

```
$ rustdoc --version
rustdoc 1.41.0 (5e1a79984 2020-01-27)
$ rustdoc --test issue.rs 

running 1 test
test issue.rs -  (line 2) ... FAILED

failures:

---- issue.rs -  (line 2) stdout ----
error[E0425]: cannot find value `World` in this scope
 --> issue.rs:3:3
  |
3 | * World
  |   ^^^^^ not found in this scope

error: aborting due to previous error

For more information about this error, try `rustc --explain E0425`.
Couldn't compile the test.

failures:
    issue.rs -  (line 2)

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

$ 
```

`rustdoc` seems to have extracted a doc test that includes the chunk of the comment on line 3.

I see the same behavior with the nightly I have installed:

```
$ rustdoc +nightly --version
rustdoc 1.43.0-nightly (158127853 2020-03-10)
$ rustdoc +nightly --test issue.rs 

running 1 test
test issue.rs -  (line 3) ... FAILED

failures:

---- issue.rs -  (line 3) stdout ----
error[E0425]: cannot find value `World` in this scope
 --> issue.rs:4:3
  |
3 | * World
  |   ^^^^^ not found in this scope

error: aborting due to previous error

For more information about this error, try `rustc --explain E0425`.
Couldn't compile the test.

failures:
    issue.rs -  (line 3)

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out

```

You can reproduce this yourself here:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=051d1b04c88609b3dd4140956374a788

Now, you might think this is okay behavior because line 3 includes a leading 4 spaces that could cause it to be treated as a code block.  I think that's not right for a few reasons:

1. The [CommonMark spec for indented code blocks](https://spec.commonmark.org/0.29/#indented-code-blocks) says "there must be a blank line between a paragraph and a following indented code block."  It also says "If there is any ambiguity between an interpretation of indentation as a code block and as indicating that material belongs to a list item, the list item interpretation takes precedence."
2. To test this, I took lines 2-4, dropped the leading " *", and put them into the CommonMark "dingus" tool, which [renders it as a list, not an indented code block](https://spec.commonmark.org/dingus/?text=%20*%20Hello%0A%20%20%20%20%20*%20World%0A%0A).
3. The real kicker is that if you take the exact same example and remove the leading space on **line 5**, then the example works:

```
$ diff issue.rs non-issue.rs 
5c5
<   * Lorem
---
>  * Lorem
$ rustdoc --test non-issue.rs 

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

I'm not sure how that change to line 5 affects how line 3 gets parsed.

**Comment by Luro02** [comment]
This multiline doc comment will be interpreted

```rust
/*!
 * * Hello
 *     * World
 *
  * Lorem
 */
```

as

```markdown
 * * Hello
 *     * World
 *
  * Lorem
```

The leading `*`s will not be removed, because it is missing in the `Lorem`-line (you can see this by running `cargo doc --open`).

By removing one of the two spaces before `* Lorem` it is interpreted as

```markdown
* Hello
    * World

Lorem
```

commonmark.js dingus also interprets the markdown block as code

```markdown
 * * Hello
 *     * World
 *
  * Lorem
```

https://spec.commonmark.org/dingus/?text=%20*%20*%20Hello%0A%20*%20%20%20%20%20*%20World%0A%20*%0A%20%20*%20Lorem

**Comment by davepacheco** [comment]
Thanks for the explanation!  If I'm understanding correctly, the key point is that because line 5 doesn't have the same form as the others (extra leading space), `rustdoc` treats _all_ of the lines differently because it stops removing all of the leading asterisks?  Is that the correct behavior?

**Comment by Luro02** [comment]
>  If I'm understanding correctly, the key point is that because line 5 doesn't have the same form as the others (extra leading space), rustdoc treats all of the lines differently because it stops removing all of the leading asterisks?

Correct

> Is that the correct behavior?

I think so?

```rust
/*!
This is a little documentation example. Here is a list:
 * first item
 * second item
and so on...
 */
```

I think it would be wrong to remove the `*`s in the above.

**Comment by davepacheco** [comment]
I'm not sure if it's a better overall approach, but I think it would make the behavior more predictable if C-style doc comments were required to use leading asterisks.

**Comment by davepacheco** [comment]
Relatedly, is the behavior that you described documented somewhere (namely, that `rustdoc` drops leading ` *` from lines only if all lines in the block comment start that way)?  Or more generally: how does a user learn how code is extracted from doc comments to avoid this kind of confusion?

Thanks again for the help!

**Comment by Luro02** [comment]
Normally it would be documented in the [rust reference](https://doc.rust-lang.org/stable/reference/)
but it is not mentioned there, so I am assuming that someone forgot this.

https://doc.rust-lang.org/reference/comments.html

Sometimes there are RFCs, which document a feature, but for this issue I could not find any related  RFCs.

Feel free to make a PR for it and tag this issue :)
(write `fixes rust-lang/rust#69905` somewhere in the PR)
If you do not want to bother with it, just leave a comment, so I can make a PR instead :)

This is the github repository for the reference:

https://github.com/rust-lang/reference/

**Comment by davepacheco** [comment]
Thanks for looking!  I'd looked as well here but didn't find it:
https://doc.rust-lang.org/rustdoc/documentation-tests.html#syntax-reference

If you'd be willing to make that PR, please do!

**Comment by GuillaumeGomez** [comment]
No, sorry but we don't want this. In C, you start a multiple line comment with `*` to make it look better but it's definitely not mandatory. Therefore, I don't see any reason why rustdoc would want to handle them differently. Rust doc comments are interpreted as markdown and you should therefore take it into account.

If you want to prepend your doc comment lines with something, you can use `//!`. Anyway, I'll close this issue in the meantime but keep the comments open just in case.

Thanks anyway for opening this issue though!
