### ISSUE TITLE
After libsyntax, idents should be replaced by Names

### ISSUE THREAD

**Issue by jbclements** [rust-lang/rust#6993]
This is a FIXME issue; right now, an ident contains information used by expansion. After expansion, this is collapsed down to a single Name (an index into the interner). However, the downstream stuff in librustc refers to "ast::ident" everywhere.  It would save space and time to just pass around one int rather than two, by replacing uses of "ident" with "Name". I don't know if I'll have time to do this. (Planning for my untimely demi^H^Hparture.)

**Comment by cmr** [comment]
Looking through a `git grep Ident librustc*`, it seems this is pretty close to being done.

**Comment by petrochenkov** [comment]
I'm working on this.
So far I see two subtasks to work on:
- There's a bunch of random code everywhere using `Idents` unconsciously, it can be rewritten to work with `Names` unconditionally and without much doubt.
- Some parts of resolve (all code calling `mtwt::resolve`) legitimately need `SyntaxContext` information from `Idents` to resolve hygienic names. So, HIR has to keep at least *some* information about macro expansion despite the general desire to get rid of it. The good news is that many structures in HIR (at least `TraitRef`, `Generics`, `TyPath`, `PatStruct`, `ExprStruct`, `PatEnum`, `PatQPath`, but *not* `ExprPath`) can drop syntax context information at cost of splitting `hir::Path` into `hir::NamePath` and `hir::IdentPath` (with `Name` and `Ident` segments respectively) and some duplication in resolve in code performing path resolution. This duplication can be considered a drawback, so this subtask is not as unambiguous as the previous one. I'd be glad to hear some opinions on this matter.

I'll likely submit two separate PRs to cover these two tasks in order.

**Comment by petrochenkov** [comment]
HIR visitors are somewhere between these two tasks, but I tend to convert them to use `Name`s. The logic is that syntax context information is needed for very narrow task in resolve and is not supposed to be used by general visitors.

**Comment by arielb1** [comment]
@petrochenkov 

We may want to move resolve to the AST.

**Comment by petrochenkov** [comment]
@arielb1 
At least the first my subtask doesn't prevent this move.
(Considering the second one, I'll try to do it anyway just to see what will come of it)

**Comment by petrochenkov** [comment]
cc https://github.com/rust-lang/rust/issues/28139 @nrc

**Comment by jbclements** [comment]
Somewhat off-topic, but I'd love to come up to Mountain View and talk about Macros 2.0 some time.

**Comment by nrc** [comment]
@petrochenkov I'd be strongly against splitting Paths in the manner you suggest, I'd much rather just carry around a little extra redundant information than have to deal with that.

@jbclements we haven't made much progress with macros 2.0 tbh, I'll be sure to ping you once we get stuck in.

**Comment by petrochenkov** [comment]
@nrc
>I'd be strongly against splitting Paths in the manner you suggest, I'd much rather just carry around a little extra redundant information than have to deal with that.

I've just tried to do it and it indeed turned out to be too much trouble for little expected gain. I'll omit this part. The second PR will just remove some remaining random `Ident`s.
