### ISSUE TITLE
macros should be parsed more lazily

### ISSUE THREAD

**Issue by jbclements** [rust-lang/rust#6994]
This is a FIXME issue; currently, macro invocations are parsed too eagerly. In particular, the current system decides before expansion time whether a rhs pattern-use (e.g. $y) is bound or unbound. This is incompatible with macro-producing macros that use a given identifier in a pattern position. It's also incompatible with macros inside macros, where inner binding patterns are believed to be pattern uses. The solution is to delay this decision until the macro is encountered at expansion-time, by which time all outer macros have been expanded.

Here's an example of a macro that doesn't work in the current system:

```
// the z flows into and out of two macros (g & f) along one path, and one (just g) along the
// other, so the result of the whole thing should be "let z_123 = 3; z_123
macro_rules! g (
    ($x:ident) =>
    (
        {macro_rules! f(
            ($y:ident)=>({let $y=3;$x})
        );
         f!($x)})
)

fn a(){g!(z)}
```

Trying to expand this yields this error:
```
Running /usr/local/bin/rustc:
/tmp/g.rs:7:12: 7:13 error: unknown macro variable `y`
/tmp/g.rs:7             ($y:ident)=>({let $y=3;$x})
                        ^
```
... indicating that the $y is believed to be a use, rather than a binder.

**Comment by steveklabnik** [comment]
Triage: OP's code, with a semicolon, still generates the same error.

**Comment by bltavares** [comment]
Triage: There is still the same error happening on `rustc 1.11.0-nightly (6e00b5556 2016-05-29)`


```rust
// the z flows into and out of two macros (g & f) along one path, and one (just g) along the
// other, so the result of the whole thing should be "let z_123 = 3; z_123
macro_rules! g (
    ($x:ident) =>
    (
        {macro_rules! f(
            ($y:ident)=>({let $y=3;$x})
        );
         f!($x)})
);

fn a(){g!(z)}
```

Error:
```
/tmp/zshKZx8Ym:8:14: 8:22 error: unknown macro variable `y`
/tmp/zshKZx8Ym:8             ($y:ident)=>({let $y=3;$x})
                              ^~~~~~~~
/tmp/zshKZx8Ym:8:31: 8:33 error: unknown macro variable `y`
/tmp/zshKZx8Ym:8             ($y:ident)=>({let $y=3;$x})
                                               ^~
error: aborting due to 2 previous errors
```

**Comment by B1Z0N** [comment]
<img width="508" alt="image" src="https://user-images.githubusercontent.com/32279961/210151356-b65bd08a-2ed3-4dcf-9601-c30efb302f72.png">
<img width="1281" alt="image" src="https://user-images.githubusercontent.com/32279961/210151362-f113ec2e-4af1-4969-be74-c63143c0f850.png">

It seem to be working poorly on variadic arguments. Or am I missing something?

<details><summary>CODE</summary>
<p>

#### Here

```rust
macro_rules! code_macro {
  ($gen:ident, $res:ident) => {
    macro_rules! $res {
      ($($token:tt)*) => {
        http_code!($gen $($token)*)
      };
    }
  };
  ($closure:tt, $res:ident) => {
    let f = $closure;
    code_macro!(f, $res)
  };
}
```

</p>
</details>
