### ISSUE TITLE
["the book" docs] the content of chapter 14.3 "Cargo Workspaces" is misleading about the "cargo new" command and the relationship of workspaces and crates

### ISSUE THREAD

**Issue by sify21** [rust-lang/rust#69972]
In chapter 14.3, It's been said at the beginning that "A workspace is a set of packages".   

However, following example says "we’ll create the adder binary crate by running cargo new", which is wrong because we're actually creating a package named adder containing one crate.   

Similarly, the title "Creating the Second Crate in the Workspace" is better to be  renamed "Creating the Second Package in the Workspace", because you create crates in  package.   

Although it's not a big deal, readers may have a wrong understanding about workspace, package, and crate.

**Comment by JohnTitor** [comment]
Hi @sify21, issue about "the book" should be reported to https://github.com/rust-lang/book, could you re-open there?

**Comment by sify21** [comment]
ok
