### ISSUE TITLE
Must use type parameter on struct to use in impl

### ISSUE THREAD

**Issue by aklitzke** [rust-lang/rust#70059]
### Code

Lets say I have a trait which doesn't require any reference to a `Self`:

```rust
trait SayHi {
    fn hi();
}
```
and I want to use this trait in an impl, but don't need an instance of it in a struct anywhere:
```rust
struct Mom { }
impl<Kid: SayHi> Mom {
    fn tell_kid_to_say_hi() {
        Kid::hi();
    }
}
```

[The code fails to compile](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=64ef6ef6609a57e655bfbb8b6e26f911), complaining that `Kid` is unconstrained. However, `Kid` _is_ utilized and necessary to do something like [this](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=6c620a21f99f07520574039cefffbb85):

```rust
struct Bob { }
impl SayHi for Bob {
  fn hi() {
    println!("Hi I'm Bob");
  }
}
fn main() {
  Mom::<Bob>::tell_kid_to_say_hi();
}
```

A kind of gross workaround is to use `Kid` in the structure, just to get the type to be constrained. This usually has a runtime cost though, so something like putting a [zero-sized array inside the structure](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=aa7b61b5175bdbf333408240b550427e) works...

```rust
struct Mom<Kid> { not_used: [Kid; 0] }
impl<Kid: SayHi> Mom<Kid> {
...
```

...but, it just feels like there has to be a better way.

### Meta

`rustc --version --verbose`:
```
rustc 1.42.0 (b8cedc004 2020-03-09)
binary: rustc
commit-hash: b8cedc00407a4c56a3bda1ed605c6fc166655447
commit-date: 2020-03-09
host: x86_64-unknown-linux-gnu
release: 1.42.0
LLVM version: 9.0
```

### Error output

```
the type parameter `Kid` is not constrained by the impl trait, self type, or predicates
```

**Comment by jonas-schievink** [comment]
Language changes like this need an RFC, so closing in favor of that.

**Comment by aklitzke** [comment]
If anyone else runs into this, it looks like a slightly better solution is to use [PhantomData](https://doc.rust-lang.org/beta/std/marker/struct.PhantomData.html).
