### ISSUE TITLE
Negative numbers are not correctly identified as literals inside macros

### ISSUE THREAD

**Issue by connorskees** [rust-lang/rust#70050]
Negative numbers are no longer parsed as literals when used as a parameter to a macro inside a macro. This appears to be a regression from stable to nightly.

According to cargo-bisect-rustc, https://github.com/rust-lang/rust/pull/69023 is responsible (thanks to @jebrosen for helping with this on the Rust discord)
Specifically, the changes to [this function](https://github.com/rust-lang/rust/pull/69023/files#diff-cd934bf3d344974edb4b4bbad00a60c2R407) look suspicious.

The below fails to compile:
```rust
macro_rules! foo {
    ($a:literal) => {
        bar!($a)
    }
}

macro_rules! bar {
    ($b:literal) => {}
}

fn main() {
    // fails on nightly, but not stable
    foo!(-2);
    // doesn't fail
    bar!(-2);
}
```

with the following error on nightly-2020-02-14,

```
~ >cargo b
error: no rules expected the token `-2`
  --> src\main.rs:3:14
   |
3  |         bar!($a)
   |              ^^ no rules expected this token in macro call
...
7  | macro_rules! bar {
   | ---------------- when calling this macro
...
12 |     foo!(-2);
   |     --------- in this macro invocation
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to previous error
```

**Comment by jebrosen** [comment]
> ```
> rustc 1.42.0-nightly (8417d68de 2020-02-03) (compiles)
> rustc 1.43.0-nightly (58b834344 2020-02-05) (does not compile)
> ```

Strange, with `58b834344 2020-02-05` I can compile this successfully. Here's my `cargo-bisect-rustc` report, after originally narrowing it down from `2020-01-25` to `2020-02-14`:

```
searched nightlies: from nightly-2020-02-13 to nightly-2020-02-14
regressed nightly: nightly-2020-02-14
searched commits: from https://github.com/rust-lang/rust/commit/a1912f2e89b77cfe2a0e64b96f444848fe4e2d49 to https://github.com/rust-lang/rust/commit/5d04ce67fd14538d03fa47a2598f80d49fd564c6
regressed commit: https://github.com/rust-lang/rust/commit/be493fe8cc40c3d3f6030a1313c1ff747fce770d
```

> Specifically, the changes to [this function](https://github.com/rust-lang/rust/pull/69023/files#diff-cd934bf3d344974edb4b4bbad00a60c2R407) look suspicious.

My reason for interest in that particular line is that it appears to be the only change that isn't related to `async` or `const`, but it *is* related to literals.

**Comment by jonas-schievink** [comment]
cc @Centril

**Comment by Centril** [comment]
Note to self: "this function" refers to `pub fn can_begin_literal_or_bool(&self) -> bool`.

**Comment by M-PC** [comment]
It changes, and fixing
