### ISSUE TITLE
error when compiling with --allow warnings and --target wasm32-unknown-unknown

### ISSUE THREAD

**Issue by dakom** [rust-lang/rust#70070]
When I set `RUSTFLAGS="--allow warnings"` and try to `cargo build --target wasm32-unknown-unknown` I get the following error:

```
error: output of --print=file-names has changed in the compiler, cannot parse
command was: `rustc - --crate-name ___ --print=file-names --allow warnings --target wasm32-unknown-unknown --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg`
```

rustc 1.43.0-nightly (564758c4c 2020-03-08)
cargo 1.43.0-nightly (bda50510d 2020-03-02)

**Comment by dakom** [comment]
Workaround in the meantime is to add `quiet` feature and `#![cfg_attr(feature = "quiet", allow(warnings))]`

**Comment by jonas-schievink** [comment]
Cargo looks for these strings in the output, which you've disabled:

```
warning: dropping unsupported crate type `dylib` for target `wasm32-unknown-unknown`

warning: dropping unsupported crate type `proc-macro` for target `wasm32-unknown-unknown`
```

Closing since this is an issue with Cargo.
