### ISSUE TITLE
Ungreat change to doctest test names

### ISSUE THREAD

**Issue by ehuss** [rust-lang/rust#70090]
Doctest test names have changed due to #66364.  Doc comments that pass through a macro defined in another crate now seem to report a different span.

```rust
lazy_static::lazy_static! {
    /// Comments
    /// ```
    /// assert!(true);
    /// ```
    static ref FOO: bool = true;
}
```

running with `cargo test --doc` previously looked like this:

```
test <::lazy_static::__lazy_static_internal macros> - FOO (line 26) ... ok
```

Now the test names look like this:

```
test /Users/eric/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.4.0/src/lib.rs - FOO (line 159) ... ok
```

Frankly, neither are particularly great.  It would be nice if the test name used the span from where the macro was invoked, not where it was defined.

`rustc 1.43.0-nightly (c20d7eecb 2020-03-11)`

**Comment by matthiaskrgr** [comment]
This also affects normal backtraces :(
Just got this rather unuseful backtrace while bootstrapping:
````
thread 'rustc' panicked at 'internal error: entered unreachable code', <::std::macros::panic macros>:2:4
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
````

**Comment by Centril** [comment]
cc @eddyb @petrochenkov

**Comment by eddyb** [comment]
@matthiaskrgr What you're describing is entirely in the opposite direction, `<::std::macros::panic macros>` is the old (and arguably bad) kind of `Span` that's impossible to get anymore.
I've hidden your comment to focus on the reported issue.

**Comment by eddyb** [comment]
@ehuss That makes sense, we have a way to get the outermost invocation, that is used by `file!()`/`line!` and `#[track_caller]`:
```rust
span.ctxt().outer_expn().expansion_cause().unwrap_or(span)
```

We'd just need to use this in `rustdoc`.

**Comment by Centril** [comment]
cc @GuillaumeGomez

**Comment by Centril** [comment]
cc @rust-lang/rustdoc

**Comment by spastorino** [comment]
Removed `T-compiler` label, left nomination for `T-rustdoc` to decide about this issue. cc @rust-lang/rustdoc

**Comment by GuillaumeGomez** [comment]
Well, using what @eddyb suggested seems like the best thing to do.
