### ISSUE TITLE
impl Copy for core::iter::Once?

### ISSUE THREAD

**Issue by Kixunil** [rust-lang/rust#70096]
I just hit a situation in which it'd be useful for `core::iter::Once` to impl `Copy` because I need the iterator to be restartable. Is there any good reason to not implement it? This change seems too trivial for RFC, but let me know if I'm wrong.

In case it's decided for `Copy` to be added, I'm willing to make a PR, but writing an RFC for such thing would be too much for me.

**Comment by sfackler** [comment]
We generally do not allow iterators to be copy because it can easily cause confusing behavior as an implicit copy is mutated while the "original" is not. `iter::Once` is already `Clone`, which should be fine to restart it as needed I think.

**Comment by Kixunil** [comment]
Hmm, good point, so we're trading one confusion (implicit copy) for another confusion (`Clone` looks more expensive than `Copy`), but maybe the former is worse than the latter?

**Comment by sfackler** [comment]
>Types that are Copy should have a trivial implementation of Clone. More formally: if T: Copy, x: T, and y: &T, then let x = y.clone(); is equivalent to let x = *y;.

**Comment by Kixunil** [comment]
Yes, I know that, it's just that it may not be immediately apparent to the reader not seeing the type whether it actually has trivial implementation - the reason Rust distinguishes between `Copy` and `Clone` in the first place.

Anyway, it seems to me that if all iterators don't implement `Copy`, then this should actually be `impl Copy for $iterator`, which may require RFC and so this issue should be closed. What do you think?

**Comment by sfackler** [comment]
Yes, implementing Clone for iterators would be a major change IMO.
