### ISSUE TITLE
Macro's literal specifier causes a compilation error when `-` is not followed by a literal.

### ISSUE THREAD

**Issue by kamadak** [rust-lang/rust#70102]
The literal specifier in a marco matches with `-? LiteralExpression` (See <https://doc.rust-lang.org/reference/macros-by-example.html>).
Consider the case where it encounters a `-` not followed by a `LiteralExpression`.  I expect that the rule does not match and the next rule is tried.  However, I get a compilation error.

I tried this code:

```rust
macro_rules! first_token {
    ($first:literal $($rest:tt)*) => ("literal");
    ($first:tt $($rest:tt)*) => (concat!("other: ", stringify!($first)));
}

fn main() {
    let a = 1;
    println!("{}", first_token!(-a));
}
```

I expected to see this happen:
- compilation succeeds.
- `other: -` is printed on execution.

Instead, I get a compilation error:
```
error: unexpected token: `a`
 --> literal.rs:8:34
  |
8 |     println!("{}", first_token!(-a));
  |                                  ^

error: aborting due to previous error
```

### Meta

`rustc --version --verbose`:
```
rustc 1.42.0 (b8cedc004 2020-03-09)
binary: rustc
commit-hash: b8cedc00407a4c56a3bda1ed605c6fc166655447
commit-date: 2020-03-09
host: x86_64-unknown-netbsd
release: 1.42.0
LLVM version: 9.0
```
Also, tested on 1.43.0-nightly.

**Comment by jonas-schievink** [comment]
Non-Terminals in macros are parsed greedily, so when the parsing fails an error is emitted and the next rule isn't tried. This is expected behavior of the `macro_rules` macros, so closing. (there are some other old bugs about this, but I can't find them at the moment)

**Comment by kamadak** [comment]
Thank you for the explanation.
