### ISSUE TITLE
ICE when casting negative discriminant enum values to anything less than bit width

### ISSUE THREAD

**Issue by afinch7** [rust-lang/rust#70114]
Compiling this code on [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=5d837277ab57f55258ef488c9bd7d3b3):
``` rust
enum Nums {
    NegOne = -1,
}

fn main() {
    let kind = Nums::NegOne;
    let _v = kind as i32;
}
```
results in ICE. Casting to anything smaller than `usize`/`isize`(`u32`, `u16`, `i16`, `u8`, `i8`, etc) also results in ICE. Casting to anything same size or larger(`u128`, `i128`, `u64`, `i64`, etc) works fine. Positive discriminant values also work fine.
Version of rustc: `rustc 1.42.0 (b8cedc004 2020-03-09) running on x86_64-unknown-linux-gnu`(on rust playground)
Compiler flags listed as used: `-C codegen-units=1 -C debuginfo=2 --crate-type bin`

**Comment by pnkfelix** [comment]
[godbolt](https://godbolt.org/z/KnacBd) indicates that this was injected in Rust 1.40

**Comment by RalfJung** [comment]
Thanks for the report!

Please always include the ICE message. This time, it seems to be
```
Unsigned value 0xffffffffffffffff does not fit in 32 bits
```
