### ISSUE TITLE
Underflow appears to be treated as undefined behaviour

### ISSUE THREAD

**Issue by rocurley** [rust-lang/rust#70113]
I tried this code:

```rust
fn main() {
    println!("{}, {}", mul1(-1, 1), mul2(-1, 1))
}
fn mul1(mut a: i32, b: i32) -> i32 {
    let mut out = 0;
    while a != 0 {
        out += b;
        a -= 1;
    }
    out
}

fn mul2(a: i32, b: i32) -> i32 {
    if a == 0 {
        0
    } else {
        b + mul2(a - 1, b)
    }
}

```

I expected to see this happen: Either a panic from underflow, or some huge weird result from underflow wrapping.

Instead, this happened: `mul1` and `mul2` appear to have been compied down to imul: [Godbolt](https://godbolt.org/z/KgR9dJ). This is only a valid optimization if underflow is treated as undefined behavior.

### Meta

`rustc --version --verbose`:
```
rustc 1.42.0-nightly (b5a3341f1 2020-01-20)
binary: rustc
commit-hash: b5a3341f1b8b475990e9d1b071b88d3c280936b4
commit-date: 2020-01-20
host: x86_64-unknown-linux-gnu
release: 1.42.0-nightly
LLVM version: 9.0
```

**Comment by lzutao** [comment]
Try with debug build. It will panic on underflow.

**Comment by rocurley** [comment]
Just realized that this behavior is actually correct: the "huge weird result" itself overflows, yielding the same result as doing the multiplication normally. If I try something that actually _should_ yield different results, it does:
```rust
fn main() {
    println!("{}, {}", id1(-1), id2(-1))
}
fn id1(mut a: i32) -> i64 {
    let mut out = 0;
    while a != 0 {
        out += 1;
        a -= 1;
    }
    out
}

fn id2(a: i32) -> i64 {
    if a == 0 {
        0
    } else {
        1 + id2(a - 1)
    }
}

```
