### ISSUE TITLE
use of undeclared lifetime emits incorrect help message

### ISSUE THREAD

**Issue by lcnr** [rust-lang/rust#70152]
In case there is an undeclared lifetime in an ADT deriving `Eq` a wrong help message is emited
```rust
#[derive(Eq, PartialEq)]
struct Test {
    a: &'b str,
}
```
causes the following error

```
error[E0261]: use of undeclared lifetime name `'b`
 --> src/lib.rs:3:9
  |
2 | struct Test {
  |            - help: consider introducing lifetime `'b` here: `<'b>`
3 |     a: &'b str,
  |         ^^ undeclared lifetime

error[E0261]: use of undeclared lifetime name `'b`
 --> src/lib.rs:3:9
  |
3 |     a: &'b str,
  |         ^^ undeclared lifetime
  |
help: consider introducing lifetime `'b` here
  |
1 | #[derive(<'b>, PartialEq)]
  |          ^^^^
help: consider introducing lifetime `'b` here
  |
1 | #[derive(<'b>, PartialEq)]
  |          ^^^^
```

thx, bye

**Comment by lcnr** [comment]
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=e320116b13b1bc736651defba5f2fe93

**Comment by estebank** [comment]
There are two things here:

1) the suggestion should try and identify spans coming from macro expansion and not suggest changes
2) `#[derive(Eq)]` in this case expands to the following:
```rust
#[automatically_derived]
#[allow(unused_qualifications)]
impl ::core::cmp::Eq for Test {
    #[inline]
    #[doc(hidden)]
    fn assert_receiver_is_total_eq(&self) -> () {
        { let _: ::core::cmp::AssertParamIsEq<&'b str>; }
    }
}
```

Note the `&'b str` param, which could avoid having any lifetimes and thing would work correctly. We can probably change the desugaring to not specify the lifetime and then we would avoid the second unnecessary duplicated error.

**Comment by lcnr** [comment]
I believe that we can't remove the explicit lifetime here.
This would allow `Eq` for `&'a T` even if `Eq` is only implemented for `&'static T`.

```rust
use std::marker::PhantomData;

trait A {}

struct Foo;

impl A for &'static Foo {}

struct AssertImpl<T: A>(PhantomData<T>);

pub fn f<'a>(_: &'a ()) {
    let _: AssertImpl::<&Foo>; 
}
```
