### ISSUE TITLE
Cycle is not dectected

### ISSUE THREAD

**Issue by ark0f** [rust-lang/rust#70160]
I tried this code:

```rust
trait IntegerMax {
    const MAX: Self;
}

impl IntegerMax for u8 {
    const MAX: Self = u8::MAX;
}

```

I expected to see this happen: `error[E0391]: cycle detected when processing` (tested on stable 1.42.0)

Instead, this happened: successful compilation 

### Meta

`rustc --version --verbose`:
```
rustc 1.43.0-nightly (2890b37b8 2020-03-06)
binary: rustc
commit-hash: 2890b37b861247de3b8c6ba2ecbcd00048c728a1
commit-date: 2020-03-06
host: x86_64-pc-windows-msvc
release: 1.43.0-nightly
LLVM version: 9.0
```

I've also checked it on playground with nightly 1.44 and got the same behavior.

**Comment by Mark-Simulacrum** [comment]
This is likely because `u8::MAX` now resolves to the inherent constant, https://doc.rust-lang.org/nightly/std/primitive.u8.html#associatedconstant.MAX.

If you change the code to explicitly reference the IntegerMax trait then the cycle error does occur.
```rust
trait IntegerMax {
    const MAX: Self;
}

impl IntegerMax for u8 {
    const MAX: Self = <u8 as IntegerMax>::MAX;
}
```
