### ISSUE TITLE
On macOS, try `getentropy()` before opening `/dev/urandom`?

### ISSUE THREAD

**Issue by hatoo** [rust-lang/rust#70179]
# Background

Hi, I'm developing a HTTP load generator called [oha](https://github.com/hatoo/oha). The application often exceeds the number of open file limit and then, tokio runtime crashes because it tries to open `/dev/urandom` to generate random on macOS.

https://github.com/hatoo/oha/issues/23

# issue

On macOS, according to https://github.com/rust-lang/rust/blob/master/src/libstd/sys/unix/rand.rs, `fill_bytes` always read `/dev/urandom` but opening `/dev/urandom` may fail because of the limit of the number of open files.
So it would be better to try `getentropy` like [getrandom](https://docs.rs/getrandom/0.1.14/getrandom/) before reading `/dev/urandom`.

Thanks.

**Comment by RalfJung** [comment]
Miri would also like that, because it is easier to emulate. :)
