### ISSUE TITLE
Importing modules from inside include! no longer works

### ISSUE THREAD

**Issue by jdm** [rust-lang/rust#70185]
This code works in the 2020-03-19 nightly:

build.rs:
```rust
use std::env;
use std::fs;
use std::path::PathBuf;

fn main() {
    let out_dir = env::var("OUT_DIR").unwrap();
    let path: PathBuf = [out_dir.clone(), "foo.rs".to_string()].iter().collect();
    fs::write(path, "pub mod foo2;").unwrap();

    let path: PathBuf = [out_dir, "foo2.rs".to_string()].iter().collect();
    fs::write(path, "pub fn foo_fn() {}").unwrap();
}
```

lib.rs:
```rust
mod stuff {
    include!(concat!(env!("OUT_DIR"), "/foo.rs"));
}

fn main() {
    stuff::foo2::foo_fn();
}
```

The resulting OUT_DIR looks like:
```
$ ls target/debug/build/regress-d7c49d33c7449edf/out
foo.rs	foo2.rs
```

With the 2020-03-20 nightly, this crate generates the following output:
```
error[E0583]: file not found for module `foo2`
 --> /Users/joshmatthews/regress/target/debug/build/regress-1976556320d6d1b4/out/foo.rs:1:1
  |
1 | pub mod foo2;
  | ^^^^^^^^^^^^^
  |
  = help: to create the module `foo2`, create file "src/stuff/foo2.rs"

error[E0425]: cannot find function `foo_fn` in module `stuff::foo2`
 --> src/main.rs:7:18
  |
7 |     stuff::foo2::foo_fn();
  |                  ^^^^^^ not found in `stuff::foo2`

error: aborting due to 2 previous errors
```

I suspect either https://github.com/rust-lang/rust/pull/68941 or https://github.com/rust-lang/rust/pull/66131.

**Comment by SimonSapin** [comment]
Regression range: https://github.com/rust-lang/rust/compare/f509b26a7...f4c675c47

Merge commits in that range:

* Auto merge of https://github.com/rust-lang/rust/pull/69402 - GuillaumeGomez:extend-search, r=kinnison
* Auto merge of https://github.com/rust-lang/rust/pull/70137 - RalfJung:miri, r=RalfJung
* Auto merge of https://github.com/rust-lang/rust/pull/66131 - eddyb:local-def-id, r=petrochenkov
* Auto merge of https://github.com/rust-lang/rust/pull/70132 - Centril:rollup-oe8unsn, r=Centril
* Rollup merge of https://github.com/rust-lang/rust/pull/70088 - tmiasko:atomic-copy, r=eddyb
* Rollup merge of https://github.com/rust-lang/rust/pull/70005 - GuillaumeGomez:code-block-signs, r=kinnison
* Rollup merge of https://github.com/rust-lang/rust/pull/69969 - iximeow:sigstack-guard-page, r=cuviper
* Rollup merge of https://github.com/rust-lang/rust/pull/69959 - alexcrichton:fix-panic-in-print, * r=Mark-Simulacrum
* Rollup merge of https://github.com/rust-lang/rust/pull/69929 - cuviper:unicode-13.0.0, r=Mark-Simulacrum
* Rollup merge of https://github.com/rust-lang/rust/pull/69814 - jonas-schievink:gen-ret-unw, r=Zoxc
* Rollup merge of https://github.com/rust-lang/rust/pull/69443 - ehuss:tidy-license, r=skade,Mark-Simulacrum
* Rollup merge of https://github.com/rust-lang/rust/pull/69036 - eddyb:monoshim, r=nikomatsakis
* Rollup merge of https://github.com/rust-lang/rust/pull/68941 - Aaron1011:fix/imported-span, r=petrochenkov
* Auto merge of https://github.com/rust-lang/rust/pull/70118 - pietroalbini:rollup-pgjc90i, r=pietroalbini
* Rollup merge of https://github.com/rust-lang/rust/pull/70116 - pietroalbini:ci-fix-windows-python-path, * r=Mark-Simulacrum
* Rollup merge of https://github.com/rust-lang/rust/pull/70112 - Centril:rollup-gpi5tbq, r=Centril
* Rollup merge of https://github.com/rust-lang/rust/pull/70106 - ehuss:fix-tidy-fmt-twice, r=Mark-Simulacrum
* Rollup merge of https://github.com/rust-lang/rust/pull/70075 - GuillaumeGomez:fix-repr-display, * r=petrochenkov
* Rollup merge of https://github.com/rust-lang/rust/pull/69920 - Centril:hir-cleanup, r=Zoxc
* Rollup merge of https://github.com/rust-lang/rust/pull/69899 - ecstatic-morse:const-idx-methods, r=oli-obk
* Rollup merge of https://github.com/rust-lang/rust/pull/69839 - RalfJung:miri-error-cleanup, r=oli-obk
* Rollup merge of https://github.com/rust-lang/rust/pull/69838 - Centril:expand-module, r=petrochenkov
* Rollup merge of https://github.com/rust-lang/rust/pull/69837 - jonas-schievink:gen-discr-opt, r=tmandry
* Rollup merge of https://github.com/rust-lang/rust/pull/69189 - matthewjasper:erase-the-world, r=nikomatsakis
* Rollup merge of https://github.com/rust-lang/rust/pull/69139 - GuillaumeGomez:cleanup-e0308, r=Dylan-DPC
* Rollup merge of https://github.com/rust-lang/rust/pull/67749 - gilescope:keyword-in, r=Dylan-DPC

**Comment by jonas-schievink** [comment]
probably cause: https://github.com/rust-lang/rust/pull/69838

cc @Centril

**Comment by jdm** [comment]
Looks like this should be fixed by https://github.com/rust-lang/rust/pull/70184?

**Comment by Centril** [comment]
@jdm Yeah that should fix it.

**Comment by Centril** [comment]
https://github.com/rust-lang/rust/pull/70184 has landed now. @jdm can you confirm on the next nightly whether the issue was fixed for y'all?

**Comment by SimonSapin** [comment]
Confirmed fixed in `nightly-2020-03-22` https://community-tc.services.mozilla.com/tasks/KSO29SSUQyaUgw_WyYnkgg/runs/0/logs/live/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FKSO29SSUQyaUgw_WyYnkgg%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log#L367

Thanks for the quick response!
