### ISSUE TITLE
Merge two impl BufReader blocks

### ISSUE THREAD

**Issue by lzutao** [rust-lang/rust#70191]
Can we merge two impl block?
https://github.com/rust-lang/rust/blob/f4c675c476c18b1a11041193f2f59d695b126bc8/src/libstd/io/buffered.rs#L107-L109
Currently there is no way to create a `BufReader<R>` where R not impl Read trait.

**Comment by Mark-Simulacrum** [comment]
Why do you want such a BufReader?

**Comment by lzutao** [comment]
I do not want that BufReader. I just ask could we merge two impl blocks?

**Comment by Mark-Simulacrum** [comment]
Looking at the implementation, both new and with_capacity make use of the Read impl, so we can't just not have it. I suspect we can't merge the latter methods in for backwards compatibility reasons anyway (someone could be working with fully generic bufreaders).  If you want to pursue small cleanups like this I would recommend filing pull requests directly.

I'm going to close this, if you want to discuss further please go to internals.rust-lang.org.
