### ISSUE TITLE
./x.py failed

### ISSUE THREAD

**Issue by lzutao** [rust-lang/rust#70208]
```console
% python3 ./x.py 
info: Downloading and building bootstrap before processing --help
      command. See src/bootstrap/README.md for help with common
      commands.
Updating only changed submodules
Submodules updated in 0.03 seconds
    Finished dev [unoptimized] target(s) in 0.22s
Traceback (most recent call last):
  File "./x.py", line 11, in <module>
    bootstrap.main()
  File "/home/lzutao/fork/rust/compiler/src/bootstrap/bootstrap.py", line 950, in main
    bootstrap(help_triggered)
  File "/home/lzutao/fork/rust/compiler/src/bootstrap/bootstrap.py", line 936, in bootstrap
    run(args, env=env, verbose=build.verbose)
  File "/home/lzutao/fork/rust/compiler/src/bootstrap/bootstrap.py", line 136, in run
    ret = subprocess.Popen(args, **kwargs)
  File "/home/lzutao/.local/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/home/lzutao/.local/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/lzutao/fork/rust/compiler/build/bootstrap/debug/bootstrap': '/home/lzutao/fork/rust/compiler/build/bootstrap/debug/bootstrap'
```

cc @pietroalbini @Mark-Simulacrum

**Comment by Centril** [comment]
I've hit this many times, and using `rm -rf build/bootstrap` fixes the issue for me.

**Comment by lzutao** [comment]
Unfortunately, that doesn't help. I got the same error again after removing entire `build` dir.
I think I find the problem. `x.py` does not encounter for `CARGO_BUILD_TARGET` env
(which I set in my `~/.profile` file).

**Comment by lzutao** [comment]
Hence the bootstrap should be in `build/bootstrap/x86_64-unknown-linux-gnu/debug/bootstrap`
rather than `build/bootstrap/debug/bootstrap`.

**Comment by lzutao** [comment]
This line: https://github.com/rust-lang/rust/blob/5f13820478907b09d50baf74f3ff2b78499ecd6c/src/bootstrap/bootstrap.py#L659
We may need to remove `CARGO_BUILD_TARGET` in `x.py`. Or support it properly.

**Comment by Mark-Simulacrum** [comment]
I personally consider this a "user error" in some sense, in that there's a bunch of cargo flags you can set (either in .cargo/config or environment) that'll break x.py -- I don't think we should be removing them ourselves, personally, since it seems like it's hard to be sure that they're really not necessary. I would also not want to support them, though...

However, with `CARGO_BUILD_TARGET` specifically, it seems fine to just drop it from the environment. I would accept a PR doing so in bootstrap.py.
