### ISSUE TITLE
RELEASES.md section for 1.10 contains an entry concerning a nightly feature

### ISSUE THREAD

**Issue by jplatte** [rust-lang/rust#70247]
`concat_idents!` is unstable [to this day](https://github.com/rust-lang/rust/issues/29599), but `RELEASES.md` has this to say about Rust 1.10:

> [Allow `concat_idents!` in type positions as well as in expression positions.](https://github.com/rust-lang/rust/pull/33735)

The release notes shouldn't really be talking about changes to unstable features, right?

**Comment by Mark-Simulacrum** [comment]
Yes, they shouldn't be, this was likely just an oversight at the time. We would be able to accept a PR nixing the entry, I think, even if there's probably not much point (given that 1.10 is quite old at this point).
