### ISSUE TITLE
Equality constraints on associated constants

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#70256]
We currently do not support any way to constrain an associated constant as needing to be equal to some constant value. The natural way to achieve this would be to, by analogy with e.g., `Foo<0>`, also allow `Foo<ID = 0>`. The same disambiguation rules would apply as for `Foo<X>` in terms of when a block `{ ... }` is needed, e.g., `Foo<ID = { N + 1 }>`.

In compiler internal terms, we would redefine `ast::AssocTyConstraintKind` as:
```rust
/// The kinds of an `AssocConstraint`.
#[derive(Clone, RustcEncodable, RustcDecodable, Debug)]
pub enum AssocConstraintKind {
    /// E.g., `A = Bar` in `Foo<A = Bar>`.
    EqualityTy { ty: P<Ty> },
    /// E.g., `A = 0` in `Foo<A = 0>`.
    EqualityConst { ct: AnonConst },
    /// E.g. `A: TraitA + TraitB` in `Foo<A: TraitA + TraitB>`.
    Bound { bounds: GenericBounds },
}
```

cc @varkor @eddyb

**Comment by Centril** [comment]
I've assigned myself, as I will be fixing the parser / lowering aspects of this to start with.

**Comment by dr-orlovsky** [comment]
Any progress on this issue? I see the required changes were made in March, so it seems to be possible to add this feature for now?

**Comment by varkor** [comment]
I believe only (some of) the parsing aspects were addressed, and nothing more. There is still implementation left before this feature is even ready for a feature gate.

**Comment by dtolnay** [comment]
This has been implemented in nightly, so I am closing this feature request in favor of the tracking issue at https://github.com/rust-lang/rust/issues/92827.

Per https://github.com/rust-lang/rust/issues/92827#issuecomment-1032975319, a lang team MCP is eventually going to be required, along with some medium sized doc explaining what is going on and why. @oli-obk will open a hackmd for folks to collaborate in.
