### ISSUE TITLE
Different compiler warnings when building same project in Ubuntu/Windows

### ISSUE THREAD

**Issue by JOE1994** [rust-lang/rust#70252]
When building [`MIRI`](https://github.com/rust-lang/miri) in Windows & Ubuntu,
I observed that `rustc` emits a **warning** in Windows, but not in Ubuntu.
I expected to see same error messages from `rustc` in both Windows & Ubuntu.

I used the same versions of `rustc` and `MIRI` in both Windows and Ubuntu.
* rustc : `rustc 1.44.0-nightly`
* latest commit of `MIRI` that I used : https://github.com/rust-lang/miri/commit/7f476266fdfd9530f9e7c0b4c300dc8ff65edfd1

*Shell above: Windows, Shell below: Ubuntu*
![image](https://user-images.githubusercontent.com/10286488/77238515-096bed80-6ba7-11ea-8a9b-4eca902c81cf.png)

### Meta

* `rustc --version --verbose` (Windows):
```
rustc 1.44.0-nightly (98803c182 2020-03-21)
binary: rustc
commit-hash: 98803c182b2ba6ef5dccb6bf501958249295eac0
commit-date: 2020-03-21
host: x86_64-pc-windows-msvc
release: 1.44.0-nightly
LLVM version: 9.0

```

* `rustc --version --verbose` (Ubuntu):
```
rustc 1.44.0-nightly (98803c182 2020-03-21)
binary: rustc
commit-hash: 98803c182b2ba6ef5dccb6bf501958249295eac0
commit-date: 2020-03-21
host: x86_64-unknown-linux-gnu
release: 1.44.0-nightly
LLVM version: 9.0
```

**Comment by jonas-schievink** [comment]
That's because there's a `#[cfg(target_family = "unix")]` block just below it
