### ISSUE TITLE
Can't override existing configurations

### ISSUE THREAD

**Issue by sstewartgallus** [rust-lang/rust#7025]
Consider the case of someone who wishes to test out a package built in a WIndows configuration on a Linux machine (using WINE.) To do so one should be able to pass in `--cfg 'target_os = "win32"'` and have it override the existing target_os. Suprisingly, instead both configurations are activated. That's okay but what is really bad is that one can't even pass in `--cfg 'not(target_os = "win32")'` and disable the old configuration.

**Comment by steveklabnik** [comment]
This is in the realm of cargo now, with features allowing you to choose things like this, as well as cross-compiling. And without a specific motivation, I think today's behavior is just fine.
