### ISSUE TITLE
Terminology: prefer "outside inference" to "after typeck" (or worse "during codegen").

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#70258]
Example offenders:
https://github.com/rust-lang/rust/blob/a03921701cdfe0b2c5422240f3ae370ab21069f1/src/librustc/ty/normalize_erasing_regions.rs#L18-L20

https://github.com/rust-lang/rust/blob/c6b172f7885cb83842fa15e4b0e2ff1647aebb40/src/librustc_trait_selection/traits/codegen/mod.rs#L18-L19

None of this is particularly true anymore (not that it was great when it used to be true), especially since we started using `miri` for constant evaluation, which uses all the same tools codegen does, and is interleaved/mutually recursive with type-checking.

The only real thing to keep in mind is that if you have inference variables, you're responsible for using `InferCtxt` correctly.

cc @rust-lang/compiler

**Comment by pierwill** [comment]
Review:

- [ ] https://github.com/rust-lang/rust/blob/e015ef5b2633960e7653b744d7a1c3d1d336313a/compiler/rustc_codegen_ssa/src/back/write.rs#L332
- [ ] https://github.com/rust-lang/rust/blob/e015ef5b2633960e7653b744d7a1c3d1d336313a/compiler/rustc_codegen_ssa/src/base.rs#L715
- [ ] https://github.com/rust-lang/rust/blob/e015ef5b2633960e7653b744d7a1c3d1d336313a/compiler/rustc_codegen_ssa/src/traits/mod.rs#L8
- [ ] https://github.com/rust-lang/rust/blob/e015ef5b2633960e7653b744d7a1c3d1d336313a/compiler/rustc_codegen_llvm/src/context.rs#L65
- [ ] https://github.com/rust-lang/rust/blob/e015ef5b2633960e7653b744d7a1c3d1d336313a/compiler/rustc_middle/src/ty/sty.rs#L1408
- [ ] https://github.com/rust-lang/rust/blob/e015ef5b2633960e7653b744d7a1c3d1d336313a/compiler/rustc_middle/src/ty/instance.rs#L347
- [ ] https://github.com/rust-lang/rust/blob/e015ef5b2633960e7653b744d7a1c3d1d336313a/compiler/rustc_middle/src/ty/mod.rs#L1154
- [ ] https://github.com/rust-lang/rust/blob/e015ef5b2633960e7653b744d7a1c3d1d336313a/compiler/rustc_middle/src/ty/mod.rs#L1253
- [ ] https://github.com/rust-lang/rust/blob/e015ef5b2633960e7653b744d7a1c3d1d336313a/compiler/rustc_middle/src/ty/util.rs#L191
- [ ] https://github.com/rust-lang/rust/blob/e015ef5b2633960e7653b744d7a1c3d1d336313a/compiler/rustc_middle/src/ty/util.rs#L267
- [ ] https://github.com/rust-lang/rust/blob/e015ef5b2633960e7653b744d7a1c3d1d336313a/compiler/rustc_codegen_llvm/src/coverageinfo/mod.rs#L85
- [ ] https://github.com/rust-lang/rust/blob/e015ef5b2633960e7653b744d7a1c3d1d336313a/compiler/rustc_middle/src/mir/coverage.rs#L48
- [ ] https://github.com/rust-lang/rust/blob/e015ef5b2633960e7653b744d7a1c3d1d336313a/compiler/rustc_middle/src/mir/mod.rs#L1210
- [ ] https://github.com/rust-lang/rust/blob/e015ef5b2633960e7653b744d7a1c3d1d336313a/compiler/rustc_middle/src/middle/codegen_fn_attrs.rs#L90
- [ ] https://github.com/rust-lang/rust/blob/e015ef5b2633960e7653b744d7a1c3d1d336313a/compiler/rustc_mir_transform/src/coverage/query.rs#L74
- [ ] https://github.com/rust-lang/rust/blob/e015ef5b2633960e7653b744d7a1c3d1d336313a/compiler/rustc_mir_transform/src/coverage/mod.rs#L47
- [ ] https://github.com/rust-lang/rust/blob/e015ef5b2633960e7653b744d7a1c3d1d336313a/compiler/rustc_mir_transform/src/remove_storage_markers.rs#L1
- [ ] https://github.com/rust-lang/rust/blob/e015ef5b2633960e7653b744d7a1c3d1d336313a/compiler/rustc_mir_transform/src/lower_intrinsics.rs#L93
- [ ] https://github.com/rust-lang/rust/blob/e015ef5b2633960e7653b744d7a1c3d1d336313a/compiler/rustc_trait_selection/src/opaque_types.rs#L636
- [ ] https://github.com/rust-lang/rust/blob/e015ef5b2633960e7653b744d7a1c3d1d336313a/compiler/rustc_trait_selection/src/traits/codegen.rs#L58
- [ ] https://github.com/rust-lang/rust/blob/e015ef5b2633960e7653b744d7a1c3d1d336313a/compiler/rustc_trait_selection/src/traits/codegen.rs#L71
- [ ] https://github.com/rust-lang/rust/blob/e015ef5b2633960e7653b744d7a1c3d1d336313a/compiler/rustc_trait_selection/src/traits/codegen.rs#L78
- [ ] https://github.com/rust-lang/rust/blob/e015ef5b2633960e7653b744d7a1c3d1d336313a/compiler/rustc_codegen_gcc/src/coverageinfo.rs#L59
