### ISSUE TITLE
`std::error::Error::source` documentation example uses deprecated `description` method

### ISSUE THREAD

**Issue by olehmisar** [rust-lang/rust#70278]
https://doc.rust-lang.org/std/error/trait.Error.html#method.source. 

The documentation example contains the deprecated `std::error::Error::description` method in the `main` function:
```rust
fn main() {
    match get_super_error() {
        Err(e) => {
            println!("Error: {}", e.description());  // <----------- HERE IT IS
            println!("Caused by: {}", e.source().unwrap());
        }
        _ => println!("No error"),
    }
}
```
This is probably a mistake as `get_super_error` returns a `struct` that `impl`ements the `std::fmt::Display` trait which should be used instead of the deprecated `std::error::Error::description` method. So, this:
```rust
println!("Error: {}", e.description());
```
...should be written like this:
```rust
println!("Error: {}", e);
```

**Comment by jonas-schievink** [comment]
This was fixed by https://github.com/rust-lang/rust/pull/70218
