### ISSUE TITLE
Replace calls to has_local_value with needs_infer.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#70285]
The only difference between the two is that "fresh" variables (a predecessor of the "canonical query" system) are considered `needs_infer`, despite not really taking part in inference.

I think that even without changing/replacing the "freshening" system at all, we can make "fresh" variables not `needs_infer`, removing the need for `TypeFlags::KEEP_IN_LOCAL_TCX` and `has_local_value` (which only existed for the `'gcx` vs `'tcx` split anyway).

If we want to be more explicit, we could rename `needs_infer` to `is_local_to_inference_context` or something similar, but either way I think it makes more sense than "local value".

cc @nikomatsakis @matthewjasper @Zoxc 

This issue has been assigned to @lcnr via [this comment](https://github.com/rust-lang/rust/issues/70285#issuecomment-606851898).

**Comment by lcnr** [comment]
@rustbot claim

I want to look into this, may take a few days though.

**Comment by nikomatsakis** [comment]
This sounds right. I was wondering whether that flag still needed to exist really, given that the gcx/tcx split was removed.

**Comment by eddyb** [comment]
@nikomatsakis What would you prefer we do to "fresh variables"? Does anything rely on `needs_infer` returning `true` for them?

I guess there's at least one place where we want to check if any types or consts could be later replaced ("is further specializable" type checks), but @davidtwco is adding a special flag for that.
I think right now the check omits `ty::Bound` and `ty::Placeholder` (because it checks `needs_infer() || needs_substs()`), which seems wrong.

I'll have to do an audit of all uses of `needs_infer`, I think. @lcnr let's coordinate on Zulip.

**Comment by nikomatsakis** [comment]
I'd like to get rid of fresh variables altogether, but in the meantime, I don't *think* anything should be relying on that -- they really shouldn't leak outside of the select caching in the trait system, I don't think.

**Comment by eddyb** [comment]
Okay I've looked at all `needs_infer` uses, these are the interesting ones:

1. this one is super weird, I think it refers to something that doesn't exist anymore? https://github.com/rust-lang/rust/blob/99009bf31992fb9257b84550dbf7cb509f987952/src/librustc_infer/infer/resolve.rs#L184-L228

2. the specialization check I mentioned, which @davidtwco will open a PR to replace: https://github.com/rust-lang/rust/blob/99009bf31992fb9257b84550dbf7cb509f987952/src/librustc_trait_selection/traits/project.rs#L1053-L1057

3. `select`, which *I believe* likely wants to know about fresh variables too? https://github.com/rust-lang/rust/blob/99009bf31992fb9257b84550dbf7cb509f987952/src/librustc_trait_selection/traits/select.rs#L1110-L1122
used here: https://github.com/rust-lang/rust/blob/99009bf31992fb9257b84550dbf7cb509f987952/src/librustc_trait_selection/traits/select.rs#L2032-L2071

**Comment by davidtwco** [comment]
Submitted #70658 to address the second case from [eddy's comment](https://github.com/rust-lang/rust/issues/70285#issuecomment-607290570).
