### ISSUE TITLE
"escaping bound vars in predicate" with associated_type_bounds, HRTB

### ISSUE THREAD

**Issue by comex** [rust-lang/rust#70292]
[Playground link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=1deecc813d323e46737aef56df8de25e)
```rust
#![feature(unboxed_closures, associated_type_bounds)]

fn foo<F>(f: F) where
    F: for<'a> FnOnce<(&'a i32,), Output: 'a> {}

fn main() {
    foo(|x: &i32| -> &i32 { x });
}
```
produces:
```
error: internal compiler error: src/librustc_typeck/check/mod.rs:692: escaping bound vars in predicate Obligation(predicate=Binder(OutlivesPredicate(_, ReLateBound(DebruijnIndex(1), BrNamed(DefId(0:5 ~ playground[eb44]::foo[0]::'a[0]), 'a)))), depth=0)
 --> src/main.rs:7:5
  |
7 |     foo(|x: &i32| -> &i32 { x }); // OK
  |     ^^^
```

This does not happen if written out in this form, even though I think it should be equivalent:
```rust
    F: for<'a> FnOnce<(&'a i32,)>,
    for<'a> <F as FnOnce<(&'a i32,)>>::Output: 'a,
```    

May or may not be related to #70263.

**Comment by Centril** [comment]
cc @alexreg

**Comment by alexreg** [comment]
@Centril Interesting. Is this (should this be) even supported right now? My point is, you can't do this just by concatenating where bounds, so...

**Comment by Centril** [comment]
Minimized
```rust
#![feature(associated_type_bounds)]

fn foo<F>(f: F)
where
    F: for<'a> Trait<Output: 'a>,
{
}

trait Trait {
    type Output;
}

struct C;

impl Trait for C {
    type Output = ();
}

fn main() {
    foo(C);
}
```

**Comment by Centril** [comment]
Desugared version for reference: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=e52885892c45f3ab84d4f5d75ad46414

**Comment by JohnTitor** [comment]
Triage: This is no longer ICE with the latest nightly, marking as E-needs-test.
