### ISSUE TITLE
Printing of the largest and other very large floats is wrong

### ISSUE THREAD

**Issue by jensnockert** [rust-lang/rust#7030]
If you run std::float::infinity.next_after(1.0)` you get the following (unexpected result)

~~~
=> 179769313486231680088648464220646842686668242844028646442228680066046004606080400844208228060084840044686866242482868202680268820402884062800406622428864666882406066422426822086680426404402040202424880224808280820888844286620802664406086660842040886824002682662666864246642840408646468824200860804260804068888.0
~~~

the expected result is actually something like

~~~
=> 179769313486231580788648464220646842686668242844028646442228680066046004606080400844208228060084840044686866242482868202680268820402884062800406622428864666882406066422426822086680426404402040202424880224808280820888844286620802664406086660842040886824002682662666864246642840408646468824200860804260804068887.0
~~~

**Comment by tshepang** [comment]
@pnkfelix why is this not a 1.0 blocker?

**Comment by pnkfelix** [comment]
@tshepang because at the time of triage, we decided it would be acceptable to fix this after 1.0

As in, we were *not* saying we cannot fix it  just that we would not wait for perfection before releasing 1.0

I do hope the recently posted flt2dec PR gets into 1.0

**Comment by tshepang** [comment]
@pnkfelix Why I wanted to know is why this was decided. For example, is the fix hard and/or time consuming?

**Comment by pnkfelix** [comment]
Yes, fixing this properly is hard.  See PR #24612 for a taste of the difficulty

**Comment by tshepang** [comment]
@pnkfelix thanks
