### ISSUE TITLE
ty::Const pretty printing does not handle aggregates

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#70329]
If one has e.g. a tuple constant with value `(5, 6)` it won't be printed that way, but instead just show a `ConstValue::ByRef` (or dump the raw const memory in case of MIR dumping).

We should permit the pretty printer to walk aggregates in general and only fall back to raw dumping if the const memory is not valid for the type at hand.

The entry point for implementing that is https://github.com/rust-lang/rust/blob/5aa8f199c398644d9fc2bb9ac8cffd14f985686d/src/librustc/ty/print/pretty.rs#L1181-L1190

**Comment by bjorn3** [comment]
https://github.com/oli-obk/priroda/blob/3ae5edc85db1c7d0b4ecb35c5cd739bb8b3254ce/src/render/locals.rs#L182-L236 is the implementation of this in priroda. It only handles `TyKind::Adt` though.

**Comment by oli-obk** [comment]
This is solved nowadays
