### ISSUE TITLE
assert failure in mpsc::shared `recv`

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#70340]
Don’t have minimal reproducer, but the issue reproduces this very often, so I’m hopeful it will be easy to eventually minimize. Either way, reporting the issue now.

The assertion looks like this:

```
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `139656431668000`,
  right: `0`', /rustc/58b834344fc7b9185e7a50db1ff24e5eb07dae5e/src/libstd/macros.rs:16:9
stack backtrace:
   0: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
   1: core::fmt::write
   2: std::io::Write::write_fmt
   3: std::panicking::default_hook::{{closure}}
   4: std::panicking::default_hook
   5: std::panicking::rust_panic_with_hook
   6: rust_begin_unwind
   7: std::panicking::begin_panic_fmt
   8: std::sync::mpsc::shared::Packet<T>::recv
   9: std::sync::mpsc::Receiver<T>::recv_timeout
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

From quick read through the code it looks like the assertion being triggered is this one: https://github.com/rust-lang/rust/blob/55299b2ba99432d10f925cd28ff52fe397577371/src/libstd/sync/mpsc/shared.rs#L252

The assert appears to be timing sensitive, which makes sense given this involves `recv_timeout`.

I believe our usage of the channel is fairly typical, we have one thread consuming the channel with `recv_timeout` and multiple threads producing the data. The assert occurs, I believe, within the first couple pushes to the channel.

**Comment by goffrie** [comment]
Dupe of #39364?

**Comment by nagisa** [comment]
That issue appears to conflate two distinct crashes, although the problem reported by @DenisKolodin in the comments does appear to be relevant.

**Comment by nagisa** [comment]
Duplicate of #39364
