### ISSUE TITLE
Incorrect suggestion after #70074

### ISSUE THREAD

**Issue by lzutao** [rust-lang/rust#70382]
https://github.com/rust-lang/rust/blob/02046a5d402c789c006d0da7662f800fe3c45faf/src/test/ui/type/ascription/issue-47666.stderr#L16-L27

https://github.com/rust-lang/rust/blob/02046a5d402c789c006d0da7662f800fe3c45faf/src/test/ui/type/ascription/issue-47666.stderr#L29-L43

**Comment by lzutao** [comment]
Cc @Centril

**Comment by Centril** [comment]
cc @estebank
