### ISSUE TITLE
Add `winapi` (or variant thereof) as benchmark to perf.rust-lang.org

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#70394]
Spawned off of #48247

There have been instances where we have injected performance issues when compiling `winapi` 

It has been suggested that we add `winapi` as a standard benchmark.

(In general I would like to revisit our benchmarks as a whole, which I guess is a task  covered by #48750.)

*This* issue is more targeted: We should add `winapi`, or a variant that captures its workload but works on Linux hosts, to the set of `rustc` benchmarks that live on perf.rust-lang.org.

**Comment by retep998** [comment]
A similar issue exists here: https://github.com/rust-lang/rustc-perf/issues/181

**Comment by Mark-Simulacrum** [comment]
Seems reasonable to track this just on rustc-perf for now, so going to close this in favor of that.
