### ISSUE TITLE
MIR dump prints the location of each statement as a comment

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#70400]
originally mentioned in https://github.com/rust-lang/rust/pull/69916#discussion_r395162776

Basically all the lines look like

```
return;                          // bb2[0]: scope 0 at $DIR/const-promotion-extern-static.rs:13:1: 13:56
```

which is a lot of noise if used with `mir-opt` tests and `diff` mode, because mir optimizations that don't even touch the current statement may still cause diff fallout because they touch the comments.

Should we just stop emitting the location? Or maybe just specifically for mir-opt tests by creating a new `-Z` flag?

cc @nikomatsakis @pnkfelix @matthewjasper @eddyb

**Comment by Centril** [comment]
That info seems useful to me when e.g., dumping the MIR in the playground -- I think if we're going to make tweaks, let's do it only for mir-opt tests (but please find a way to thread this info without hacks in `Debug` impls).

**Comment by eddyb** [comment]
The comment is printed outside of any formatting `impl`s so we should be fine.

@Centril do you mean the `bb2[0]`, or the scope/span?

I specifically meant the `mir::Location` i.e. the `bbX[Y]`, maybe this issue is unclear.

**Comment by Centril** [comment]
@eddyb both seem useful :)

**Comment by eddyb** [comment]
But have you actually *used it*? I can't remember having used it or imagine how, other than maybe correlating it with some `debug!` output?
If it was missing, worst case you have to count statements or something.

We could maybe normalize `// bb\d+\[\d+\]: ` to just `// ` by default for `mir-opt` tests in `compiletest`, that might be enough.

**Comment by eddyb** [comment]
Looks like printing `mir::Location`s started with #46319, so they're likely used for debugging MIR/NLL borrowck, for which we've already pinged @nikomatsakis and @matthewjasper, I guess?

**Comment by Centril** [comment]
I don't remember it vividly, but I recall that the info was useful when doing my initial investigation in https://github.com/rust-lang/rust/issues/67565. Could be wrong though.

>  If it was missing, worst case you have to count statements or something.

Yeah I could do that, but it was a bit of a time saver not to have to do that work in my head. :)

**Comment by oli-obk** [comment]
We're not printing the basic blocks without `-Zverbose` anymore, so I think there's nothing actionable here
