### ISSUE TITLE
Miri engine is too permissive with type-changing MIR assignments

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#70405]
https://github.com/rust-lang/rust/blob/02046a5d402c789c006d0da7662f800fe3c45faf/src/librustc_mir/interpret/place.rs#L856 just checks whether the layout of the target and value of an assignment is the same. The only time the types can differ is when assigning a `&mut T` to a `&T` variable. We should instead employ a function like 

```rust
fn mir_assign_valid_types(dst: Ty<'tcx>, src: Ty<'tcx>) {
    dst == src || match (&dst.kind, &src.kind) {
        (ty::Ref(_, _, dst_pointee), ty::Ref(_, _, src_pointee)) => dst_pointee == src_pointee,
        _ => false,
    }
}
```

(source https://github.com/rust-lang/rust/pull/69700#discussion_r390399160)

be sure to also add appropriate mutability checks to the patterns (mutable for the source, immutable for the dest)

**Comment by RalfJung** [comment]
@eddyb do we want to keep this open, as you have some future plans for checking subtyping or some such thing?

**Comment by eddyb** [comment]
I'm not sure, I think we should experiment with deeper lifetime erasure but I likely won't have the time to get involved myself any time soon. Maybe that should have its own issue though.
