### ISSUE TITLE
Some functions are inlined when they shouldn't

### ISSUE THREAD

**Issue by calixteman** [rust-lang/rust#70426]
Here is the code:
```rust
struct A;
impl A {
    fn new() -> Self {
        Self {}
    }
}

struct B;
impl B {
    #[inline(never)]
    fn new() -> Self {
        Self {}
    }
}

fn main() {
    let _ = A::new();
    let _ = B::new();
}
```
and then run `rustc -Cinline-threshold=0 --emit=llvm-ir plop.rs && rg '::new' plop.ll`.
The output is:
```bash
113:; plop::B::new
127:; call plop::B::new
```
According to https://doc.rust-lang.org/rustc/codegen-options/index.html#inline-threshold, `A::new` shouldn't be inlined.

**Comment by jonas-schievink** [comment]
The docs don't mention what a threshold of 0 means, perhaps LLVMs cost model determines that the cost of inlining that function is in fact 0.

**Comment by calixteman** [comment]
I'm reading here `only inlines always-inline functions`.

**Comment by jonas-schievink** [comment]
That's opt-level=0, not inline-threshold=0

**Comment by calixteman** [comment]
My bad, you're right.
Anyway, the result is the same with `-C opt-level=0`.

**Comment by jonas-schievink** [comment]
Doesn't seem to happen on [this playground example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=f626f5bc43ce176667a3930e7383253c):

```llvm
define void @_ZN10playground11TTTTTTTTTTT17h3759d258fafcd0c1E() unnamed_addr #2 !dbg !16 {
start:
; call playground::A::new
  call void @_ZN10playground1A3new17h4b221654e29fa3dfE(), !dbg !17
  br label %bb1, !dbg !17

bb1:                                              ; preds = %start
; call playground::B::new
  call void @_ZN10playground1B3new17h3a0060fa4c71b183E(), !dbg !18
  br label %bb2, !dbg !18

bb2:                                              ; preds = %bb1
  ret void, !dbg !20
}
```

**Comment by jonas-schievink** [comment]
Ah, I see the problem. When `-Cinline-threshold` is passed, we create an inlining pass with that threshold, and that ends up inlining `A::new`. This means the docs for or implementation of `-Cinline-threshold` are wrong in at least two ways:

* `-Cinline-threshold=0` does not just inline `#[inline(always)]` functions, as shown here, other functions can also have an inlining cost of 0
* `-Cinline-threshold=0` will *create* an inlining pass if one doesn't already exist in the default pipeline

For example, this invocation reproduces the issue:

    rustc -Cinline-threshold=0 -Copt-level=0 --emit=llvm-ir plop.rs && rg '::new' plop.ll

**Comment by calixteman** [comment]
I supposed that an `inline-threshold=0` would disable inlining.
It doesn't seem to be the case anyway: if `opt-level!=0` then`A::new` and `B::new` are inlined so the annotation `#[inline(never)]` is finally ignored.

**Comment by hanna-kruppe** [comment]
`-C inline-threshold`, `#[inline(never)]`, etc. control a specific pass (well, two of them, `-inline` and `-always-inline`). Other interprocedural analyses optimizations can produce the same result by different means in some cases. For example (just one of many), after noticing that a function has no side effects, calls to it can be removed if the result is not used. I expect that's what is happening with `B::new` at opt-level > 1.

**Comment by workingjubilee** [comment]
The `-Cinline-threshold` directive is now impotent, which, amusingly, fixes this problem.
