### ISSUE TITLE
regression: local ambiguity: multiple parsing options: built-in NTs lifetime 

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#70446]
https://crater-reports.s3.amazonaws.com/beta-1.43-1/beta-2020-03-12/reg/pin-project-lite-0.1.4/log.txt

cc @Centril

**Comment by Centril** [comment]
Possibly accidentally injected by https://github.com/rust-lang/rust/pull/70074.
Would be good to find out why this is happening, so let's @rustbot ping cleanup 
and see if we can bisect / shrink the problem down to something usable for finding a fix.

**Comment by LeSeulArtichaut** [comment]
Failed to confirm that #70074 is the cause:
```tested 342c5f33d097b2dc07a2dbc0ca45a37379d2ff60, got Yes```
Seems like it regressed prior to 342c5f3

**Comment by AminArria** [comment]
```
searched nightlies: from nightly-2020-02-26 to nightly-2020-03-04
regressed nightly: nightly-2020-02-29
searched commits: from https://github.com/rust-lang/rust/commit/6d69caba110c0c2fb90180df1cbc8be5033b91d4 to https://github.com/rust-lang/rust/commit/0eb878d2aa6e3a1cb315f3f328681b26bb4bffdb
regressed commit: https://github.com/rust-lang/rust/commit/0eb878d2aa6e3a1cb315f3f328681b26bb4bffdb
```

For code I used:

```rust
use pin_project_lite::pin_project;

pin_project! {
    pub struct Struct<T: 'static> {
        field: T
    }
}


fn main() {

}
```

**Comment by LeSeulArtichaut** [comment]
[My progress on an MCVE so far](https://play.rust-lang.org/?version=beta&mode=debug&edition=2018&gist=b0d289ad6cc238e3dda42054c305298d)

**Comment by steffahn** [comment]
Minimal example:
```rust
macro_rules! m {
    (  $(: $p:path)?  $(: $l:lifetime)? ) => { m! {@internal $(: $p)?  $(: $l)?  } };
    (@internal   $(: $p:path)?  $(: $l:lifetime)? ) => {};
}


m! {  : 'static }


fn main() {

}
```

**Comment by LeSeulArtichaut** [comment]
Split the macro in two parts to make it easier to follow, and removed the special lifetime `'static`:
```rust
macro_rules! foo {
    ($(: $p:path)?  $(: $l:lifetime)? ) => { bar! {$(: $p)?  $(: $l)?  } };
}

macro_rules! bar {
    ($(: $p:path)?  $(: $l:lifetime)? ) => {};
}

foo! {: 'a }
```

([Playground](https://play.rust-lang.org/?version=beta&mode=debug&edition=2018&gist=47ed3bab6f0881c774b9f93409c49a93))

Error:
```
error: local ambiguity: multiple parsing options: built-in NTs lifetime ('l') or path ('p').
  --> src/lib.rs:2:66
   |
2  |     ($(: $p:path)?  $(: $l:lifetime)? ) => { bar! {$(: $p)?  $(: $l)?  } };
   |                                                                  ^^
...
10 | foo! {: 'a }
   | ------------ in this macro invocation
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to previous error
```

I think we can now @rustbot modify labels: -E-needs-mcve

**Comment by LeSeulArtichaut** [comment]
I believe that the most probable culprit is #69384, cc @petrochenkov

**Comment by LeSeulArtichaut** [comment]
#69384 is indeed the culprit, I can reproduce the bug on b2605c118de31db9d61a9f7d0d158b9bf35f7a4a

**Comment by spastorino** [comment]
This was [briefly discussed during pre-triage](https://rust-lang.zulipchat.com/#narrow/stream/227806-t-compiler.2Fwg-prioritization/topic/pre-meeting.20triage.202020-04-02.20.2354818/near/192575877). Assigning `P-high` for now.

**Comment by petrochenkov** [comment]
Fixed in https://github.com/rust-lang/rust/pull/70768.
