### ISSUE TITLE
regression: mismatched types (lifetimes)

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#70443]
https://crater-reports.s3.amazonaws.com/beta-1.43-1/beta-2020-03-12/gh/FlorianFranzen.dx/log.txt
https://crater-reports.s3.amazonaws.com/beta-1.43-1/beta-2020-03-12/reg/granne-0.5.0/log.txt

Based on the error context, this looks correct, but I am uncertain. Filing a bug.

Each of these might be separate bugs, it is unclear based on the error messages. Certainly they look similar.

cc @matthewjasper

**Comment by Centril** [comment]
I think this is expected fallout from https://github.com/rust-lang/rust/pull/69340. Closing as wontfix.
