### ISSUE TITLE
regression: mismatched types

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#70444]
https://crater-reports.s3.amazonaws.com/beta-1.43-1/beta-2020-03-12/gh/finegeometer.vector-spaces-rs/log.txt

It looks like type parameter order got switched somewhere somehow, though I am unclear how that managed to happen. Possibly related to recent inference work to make binary operators work for references?

**Comment by Mark-Simulacrum** [comment]
Also leaving https://crater-reports.s3.amazonaws.com/beta-1.43-1/beta-2020-03-12/reg/yass-aux-0.1.1/log.txt here in case it's the same underlying bug (looks quite similar at a high level) but we should file a separate issue if not.

**Comment by Mark-Simulacrum** [comment]
cc @Aaron1011 who I think has done some inference related work recently

**Comment by Centril** [comment]
Closing as expected fallout from https://github.com/rust-lang/rust/pull/69340 and wontfix.

https://github.com/rust-lang/rust/issues/70444#issuecomment-604689732 might be unrelated though.
