### ISSUE TITLE
std::io::stdin().read_line(..) blocking in debug but not in release

### ISSUE THREAD

**Issue by Amityville-DE** [rust-lang/rust#70454]
I expected the read_line function to block the thread until i press enter on my keyboard.
With `cargo run` (I think that is debug) everything is fine, but with `cargo build --release | target\release\myprog` the read_line function seems not to block the thread?

Windows 10
`cargo 1.42.0 (86334295e 2020-01-31)`
`rustc 1.42.0 (b8cedc004 2020-03-09)`
`rustup 1.21.1 (7832b2ebe 2019-12-20)`

I tried this code:

```rust
loop {
    println!("Type 'exit' to terminate the program:");
    let mut input: String = String::new();
    let _length = std::io::stdin().read_line(&mut input);
}
```

I expected to see this happen:
1. print message
2. block until enter is pressed
3. repeat

Instead, this happened:
with `cargo run` => exactly what I expected
with `cargo build --release | target\release\myprog` => message is printed over and over again

**Comment by sfackler** [comment]
Why are you piping the output of cargo build into your program?

**Comment by RalfJung** [comment]
The release equivalent of `cargo run` is `cargo run --release`, does that block?

Also indeed that `|` there makes very little sense, maybe you meant `&&`?

**Comment by Amityville-DE** [comment]
`cargo run --release` works as expected

I just piped it in because i did not use any `std::env::args` anyway, but yes that is not a really good command. I used it because I think in Windows Powershell `&&` is not working.

`carg build --release` and `.\target\release\myprog.exe` are also working as expected.
I think this issue can be closed.
Thank you.
