### ISSUE TITLE
Should enum discriminants have generics in scope?

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#70453]
### What are our options?
1. we teach name resolution (`rustc_resolve`) to hide `enum` generic parameters from the discriminant expression
    * this effectively enshrines that we don't want the parameterization to happen
    * I'm not sure this can be backwards-compatible with 2.
2. we keep the current name resolution support but error if we can't evaluate to concrete values
    * the concrete values are necessary to check, at the definition site, that discriminants don't overlap
      * there are special-cases (only the first variant having an explicit discriminant, while the rest keep counting up) where we could check w/o knowing the values
      * long-term we could let more examples compile via explicit `!=` bounds
    * note that expressions that use generics [can still evaluate to concrete values](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=ba0ae8e0eb712b342a61a776ac52c62f)
    * we could make this work w/o `#![feature(const_generics)]` (see examples below) by using the same approach as in #70452, as `enum`s are in a similar situation that shouldn't cause query cycles
    * **EDIT**: opened #70825 for this

<hr/>

### Examples of current behavior:

**Note**: `#![feature(const_generics)]` is used below so that this special-case kicks in: https://github.com/rust-lang/rust/blob/62c6006450d8bd33a351673c1f969846d768aab4/src/librustc_typeck/collect.rs#L1183-L1185

Also, note that the reason for the uniform current treatment (which doesn't consider `enum` parameters as not in scope of discriminants), is because `rustc_resolve` treats surrounding generics as being in scope of `AnonConst`s, always - all the bugs later in compilation are due to the lack of lazy normalization (see #43408).

<hr/>

This ICEs currently ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=35f8107d83236450ee805be54af9c56b)):
```rust
#![feature(const_generics)]

#[repr(usize)]
enum Foo<T> {
    Zero = 0,
    SizeOf = std::mem::size_of::<T>(),
}
```
with
```
error: internal compiler error: src/librustc/ty/mod.rs:2538: enum discriminant depends on generic arguments
 --> src/lib.rs:6:14
  |
6 |     SizeOf = std::mem::size_of::<T>(),
  |              ^^^^^^^^^^^^^^^^^^^^^^^^
```

Same thing happens if a `const` parameter is used instead of `size_of::<T>()`.

If we choose option 2, this ICE will turn into a regular error.

<hr/>

**EDIT**: and this currently compiles on nightly ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=1d143ce466dded9d7c6f5badc7438c7e)):
```rust
#![feature(const_generics, arbitrary_enum_discriminant)]

#[repr(usize)]
enum MyWeirdOption<T> {
    None = 0,
    Some(T) = std::mem::size_of::<*mut T>(),
}
```
And using `*mut *mut T` instead of `*mut T` would make it work even when `T: Sized` isn't known.
(If not for the substitution failure, you could remove `#![feature(const_generics)]`)

<hr/>

cc @rust-lang/compiler @rust-lang/lang

**Comment by petrochenkov** [comment]
This seems equivalent to something like
```rust
type A<T> = [u8; std::mem::size_of::<T>()]; // ERROR the size for values of type `T` cannot be known at compilation time
```
where `T` is "obviously" in scope, it's just not concrete enough for a use in a constant (the current error is weird though).

I don't like the idea of hiding the name `T`, but if this is going to be done in resolve, we could setup a "barrier" making it an error to use it, like in this case
```rust
fn f<T>() {
    fn f() {
        std::mem::size_of::<T>(); // ERROR can't use generic parameters from outer function
    }
}
```
, but I'd still prefer the option 2.

**Comment by eddyb** [comment]
> where `T` is "obviously" in scope, it's just not concrete enough for a use in a constant (the current error is weird though).

No, that's #43408, which is why I added `#![feature(const_generics)]` to enable the fix above.
[This is how it should work](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=46f25a1b6e2c6742fb0e0f13bac37da3) and maybe we should just apply an approach like #70452 to as many cases that won't cause query cycle errors, as we can, even before lazy normalization is ready with the full fix.

> but if this is going to be done in resolve, we could setup a "barrier" making it an error to use it

Right, this matches my intuition for 1., another example of that error being:
```rust
fn f<T>() {
    const _: usize = std::mem::size_of::<T>(); // ERROR can't use generic parameters from outer function
}
```

> but I'd still prefer the option 2.

Me too, if for no other reason that we shouldn't paint ourselves into a corner if we can avoid it.

**Comment by spastorino** [comment]
We've [discussed this briefly during pre triage](https://rust-lang.zulipchat.com/#narrow/stream/227806-t-compiler.2Fwg-prioritization/topic/pre-meeting.20triage.202020-04-02.20.2354818/near/192573725), I think this was `I-nominated` in order to be discussed during some `T-lang` and/or `T-compiler` meeting. Prioritizing it as `P-medium`.

**Comment by eddyb** [comment]
@spastorino "requires nightly" is misleading, I'm only using `#![feature(const_generics)]` to bypass #43408 (`enum` discriminant expressions are in the same boat as array lengths today).
I'll adjust the labels to match reality and reduce confusion.

More to the point: if we apply the #70452 treatment to `enum` discriminants (as a partial #43408 fix), then `#![feature(const_generics)]` won't be necessary.

<hr/>

Also, I've just realized that there is an example which [compiles on nightly](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=d8b8d2adbcb4a7c886d2cb37682dc8b2), I'll add it to the issue description:
```rust
#![feature(const_generics, arbitrary_enum_discriminant)]

#[repr(usize)]
enum MyWeirdOption<T> {
    None = 0,
    Some(T) = std::mem::size_of::<*mut *mut T>(),
}
```

**Comment by eddyb** [comment]
I've just removed the ICE label, after reorganizing the issue description to indicate that the question in the title is the important part, and the ICE is just an example (bonus: the ICE becomes a regular error if we choose option 2, it's not exactly a bug, it's just not printed as a nice user error).

**Comment by nikomatsakis** [comment]
@eddyb 

> I'm not sure this can be backwards-compatible with 2.

Is the reason for this that there might be some type in scope that would otherwise be shadowed?

e.g., 

```rust
struct Foo { }
impl Foo { const Constant: usize = 22; }
enum Bar<Foo> { X = Foo::Constant }
```

**Comment by Centril** [comment]
> 2 we keep the current name resolution support but error if we can't evaluate to concrete values

I'm also fine with this option with the restrictions to known concrete values given the compatibility hazards that the first option is introducing. Presumably, "making it an error to even reference them" as an added restriction would be implemented in resolve. I'm also not opposed to such an additional restriction if it is not too complicated to implement. (I'll just note that I'm not OK with more post-monomorphization errors, but let's indeed defer that discussion.)

**Comment by eddyb** [comment]
Note that the WF precautions we're taking with constants-in-types (see #70107), would result in "prove that this evaluates successfully" requirements bubbling up (when we get a syntax for said bubbling up, i.e. #68436), if we switch `enum` discriminants from early evaluation to that system in the future.

So whichever part of the code passes in types/consts concrete enough for the value to evaluate, will get an error if it fails to evaluate (that's our general constants-in-types WF approach)

**Comment by eddyb** [comment]
> 2. we keep the current name resolution support but error if we can't evaluate to concrete values 

Opened #70825 for this alternative (+ #70452-like treatment for explicit `enum` discriminant expressions).

**Comment by spastorino** [comment]
I'm not sure if this should still be nominated but in any case I guess it's nominated for `T-lang` cc @eddyb

**Comment by Centril** [comment]
Based on the discussion thus far, I believe everyone who has commented is in favor of option 2. (see https://github.com/rust-lang/rust/issues/70453#issue-588822132) which means that the answer to the question in the title is: "Yes, enum discriminants should have generics in scope."

However, this also makes certain commitments which will be observable on stable, e.g., when `#![feature(arbitrary_enum_discriminant)]` is stabilized. Therefore, to confirm this choice through the proper process, I would propose that we confirm that we are going with option 2 (https://github.com/rust-lang/rust/pull/70825).

With that said,
@rfcbot merge

**Comment by spastorino** [comment]
Unnominating this one given that it was already discussed in last compiler weekly meeting.
