### ISSUE TITLE
Type inference + compiler message problems with closures and array of Option<&str>

### ISSUE THREAD

**Issue by Luro02** [rust-lang/rust#70464]
I tried this code:

```rust
fn main() {
    let array: [Option<&str>; 10] = [None; 10];

    String::with_capacity(
        16 + array[0].unwrap().len()
            + array
                .iter()
                .skip(1)
                .flat_map(|&o| o)
                .map(|s: &str| s.len())
                .map(|s: usize| s + 4)
                .sum(),
    );
}
```

I expected to see this happen: it should allocate a string with the size of 16 + the length of the first string + the length of all other elements + 4

Instead, this happened:

```
   Compiling playground v0.0.1 (/playground)
error[E0284]: type annotations needed for `usize`
  --> src/main.rs:11:23
   |
11 |                 .map(|s: usize| s + 4)
   |                       ^ consider giving this closure parameter a type
   |
   = note: cannot resolve `<usize as std::ops::Add<_>>::Output == usize`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0284`.
error: could not compile `playground`.

To learn more, run the command again with --verbose.
```

Okay this message is kind of wrong? I mean my type is `usize` and the compiler seems to know that so what should I annotate? (I think it wants me to annotate the `s + 4` which desugars to `s.add(4)`)

[playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&code=fn%20main()%20%7B%0A%20%20%20%20let%20array%3A%20%5BOption%3C%26str%3E%3B%2010%5D%20%3D%20%5BNone%3B%2010%5D%3B%0A%0A%20%20%20%20String%3A%3Awith_capacity(%0A%20%20%20%20%20%20%20%2016%20%2B%20array%5B0%5D.unwrap().len()%0A%20%20%20%20%20%20%20%20%20%20%20%20%2B%20array%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20.iter()%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20.skip(1)%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20.flat_map(%7C%26o%7C%20o)%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20.map(%7Cs%3A%20%26str%7C%20s.len())%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20.map(%7Cs%3A%20usize%7C%20s%20%2B%204)%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20.sum()%2C%0A%20%20%20%20)%3B%0A%7D%0A)

----

Initially I started with something like this

```rust
fn main() {
    let array: [Option<&str>; 10] = [None; 10];

    String::with_capacity(
        16 + array[0].unwrap().len()
        + array
            .iter()
            .skip(1)
            .flat_map(|&o| o)
            .map(|s| s.len() + 4)
            .sum(),
    );
}
```

```
   Compiling playground v0.0.1 (/playground)
error[E0284]: type annotations needed for `[std::option::Option<&str>; 10]`
 --> src/main.rs:6:9
  |
2 |     let array: [Option<&str>; 10] = [None; 10];
  |         ----- consider giving `array` the explicit type `[std::option::Option<&str>; 10]`, where the type parameter `usize` is specified
...
6 |         + array
  |         ^ cannot infer type for type `usize`
  |
  = note: cannot resolve `<usize as std::ops::Add<_>>::Output == usize`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0284`.
error: could not compile `playground`.

To learn more, run the command again with --verbose.
```

[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&code=fn%20main()%20%7B%0A%20%20%20%20let%20array%3A%20%5BOption%3C%26str%3E%3B%2010%5D%20%3D%20%5BNone%3B%2010%5D%3B%0A%0A%20%20%20%20String%3A%3Awith_capacity(%0A%20%20%20%20%20%20%20%2016%20%2B%20array%5B0%5D.unwrap().len()%0A%20%20%20%20%20%20%20%20%2B%20array%0A%20%20%20%20%20%20%20%20%20%20%20%20.iter()%0A%20%20%20%20%20%20%20%20%20%20%20%20.skip(1)%0A%20%20%20%20%20%20%20%20%20%20%20%20.flat_map(%7C%26o%7C%20o)%0A%20%20%20%20%20%20%20%20%20%20%20%20.map(%7Cs%7C%20s.len()%20%2B%204)%0A%20%20%20%20%20%20%20%20%20%20%20%20.sum()%2C%0A%20%20%20%20)%3B%0A%7D%0A)

Edit: To make the example compile you have to annotate the sum call (`.sum::<usize>()`) [playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&code=fn%20main()%20%7B%0A%20%20%20%20let%20array%3A%20%5BOption%3C%26str%3E%3B%2010%5D%20%3D%20%5BNone%3B%2010%5D%3B%0A%0A%20%20%20%20String%3A%3Awith_capacity(%0A%20%20%20%20%20%20%20%2016_usize%0A%20%20%20%20%20%20%20%20%20%20%20%20%2B%20array%5B0%5D.unwrap().len()%0A%20%20%20%20%20%20%20%20%20%20%20%20%2B%20array%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20.iter()%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20.skip(1)%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20.flat_map(%7C%26o%7C%20o)%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20.map(%7Cs%3A%20%26str%7C%20s.len())%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20.map(%7Cs%3A%20usize%7C%20s%20%2B%204)%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20.sum%3A%3A%3Cusize%3E()%2C%0A%20%20%20%20)%3B%0A%7D%0A)

**Comment by jcaesar** [comment]
I ran into a similar bug. I can't say whether it's the same or not. If it's not, please tell me and I will open another issue.

```rust
let d = "asdf";
println!("{}", d.as_ref());
let _ctx = |step: &'static str| format!("{}", step);
```

[playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=52348437f27c49ff3ec91d35ca729583)

**Comment by estebank** [comment]
We no longer report the invalid suggestion for the original reports, but we still do for the example in the previous comment.

**Comment by estebank** [comment]
Current output:
```
error[[E0284]](https://doc.rust-lang.org/nightly/error_codes/E0284.html): type annotations needed
  --> src/main.rs:12:18
   |
6  |             + array
   |             - type must be known at this point
...
12 |                 .sum(),
   |                  ^^^ cannot infer type of the type parameter `S` declared on the method `sum`
   |
   = note: cannot satisfy `<usize as Add<_>>::Output == usize`
help: consider specifying the generic argument
   |
12 |                 .sum::<S>(),
   |                     +++++
```
```
error[[E0284]](https://doc.rust-lang.org/stable/error_codes/E0284.html): type annotations needed
  --> src/main.rs:11:14
   |
6  |         + array
   |         - type must be known at this point
...
11 |             .sum(),
   |              ^^^ cannot infer type of the type parameter `S` declared on the method `sum`
   |
   = note: cannot satisfy `<usize as Add<_>>::Output == usize`
help: consider specifying the generic argument
   |
11 |             .sum::<S>(),
   |                 +++++
```
```
error[[E0283]](https://doc.rust-lang.org/nightly/error_codes/E0283.html): type annotations needed
 --> src/main.rs:4:22
  |
4 |     println!("{}", d.as_ref());
  |                      ^^^^^^
  |
  = note: multiple `impl`s satisfying `str: AsRef<_>` found in the following crates: `core`, `std`:
          - impl AsRef<OsStr> for str;
          - impl AsRef<Path> for str;
          - impl AsRef<[u8]> for str;
          - impl AsRef<str> for str;
help: try using a fully qualified path to specify the expected types
  |
4 |     println!("{}", <str as AsRef<T>>::as_ref(d));
  |                    ++++++++++++++++++++++++++ ~
```
