### ISSUE TITLE
build a macro `String` in std::string

### ISSUE THREAD

**Issue by uploy** [rust-lang/rust#70465]
I hope to build a macro `String` in std::string

```rs
macro_rules! String {
    ($x: expr) => {
        String::from($x)
    };
}
```

usage
```rs
let s = String!("123");
println!("{}", s); // 123
```

**Comment by jonas-schievink** [comment]
Hi! Additions to the language or standard library need to go through our [RFC process](https://github.com/rust-lang/rfcs). Before an RFC is written, the feature can also be discussed in our [internals forum](https://internals.rust-lang.org/) to find other people interested in it.

Closing in favor of an RFC.
