### ISSUE TITLE
const_generics with default arguments

### ISSUE THREAD

**Issue by lcnr** [rust-lang/rust#70471]
Should the following code be accepted?
```rust
// compiles rn
#![feature(const_generics)]

struct A<T = u32, const N: usize> {
    arg: T,
}

type C = A<u32, 7>;
```
if so, we probably also want to accept the following:
```rust
// this currently fails
type B = A<7>;
//~^ ERROR constant provided when a type was expected
```
[playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=a80b3b2c8ebe0860a4ea9d1faae1d581)

cc @varkor @eddyb

**Comment by rodrimati1992** [comment]
So,how would the following be handled?
```rust
#![feature(const_generics)]

struct A<T = u32, const N: usize> {
    arg: T,
}

type C = u64;
const C: usize = 7;

const _: [A<C>; 0] = [];

```
That is if `Foo<C>` (passing an identifier as a const argument) is eventually allowed.

**Comment by lcnr** [comment]
@rodrimati1992 it should be A<C> should be equal to `A<u32; C>` imo.

rn literals which are in both the type and the value namespace are always used as type params though (see #66615). So this would fail to compile even if we get `A<10>` to work.
