### ISSUE TITLE
[rustdoc] Please add support for `Self` in inter-method docs links

### ISSUE THREAD

**Issue by Lokathor** [rust-lang/rust#70484]
Currently if you have a link in a method's docs to another method on the same type you have to put it as

```md
[`read`](RwVolAddr::read)
```

It would be helpful if `Self` was recognized when linking to other methods of the same type.

```md
[`read`](Self::read)
```

**Comment by xliiv** [comment]
This should be closed, because it looks like duplicate of
https://github.com/rust-lang/rust/issues/70802
which got resolved by
https://github.com/rust-lang/rust/pull/71289
