### ISSUE TITLE
unused_parens incorrectly lints on `if let Ok(x) = (try { ...` 

### ISSUE THREAD

**Issue by comex** [rust-lang/rust#70490]
[Playground link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=32dff2ee98cb5c7d41ed4969e6aa8e1c)
This produces a lint:
```rust
if let Ok(x) = (try { }: Result<(), ()>) {}
```
But removing the parentheses produces an error.

This bug was already mentioned in #42528, but that issue is lost in feature-request purgatory since it asks for the version without parentheses to be allowed.  I'm opening this issue to track the incorrect lint specifically.

(Edit: Fixed the example.)

This issue has been assigned to @lcnr via [this comment](https://github.com/rust-lang/rust/issues/70490#issuecomment-605617622).

**Comment by lcnr** [comment]
@rustbot claim

Will wait for #70081 to get merged before this is fixed though.
