### ISSUE TITLE
No insert-sideeffect can wipe off overflow checks

### ISSUE THREAD

**Issue by kpp** [rust-lang/rust#70497]
I wanted to replace a call to `panic` with a `ud2` instruction only, so I implemented a dummy panic handler which does nothing, enabled overflow checks and lto.

I tried this code:

```rust
#![no_std]
#![no_main]

extern crate libc;

#[no_mangle]
#[inline(never)]
pub fn bar(x: i32) -> i32 {
    x * x
}

#[no_mangle]
pub extern fn main(argc: i32) -> i32 {
    bar(argc)
}

#[panic_handler]
fn panic(_info: &core::panic::PanicInfo) -> ! { loop {} }
```

```toml
[dependencies]
libc = { version = "0.2", default-features = false }

[profile.dev]  
overflow-checks = true
lto = true
opt-level = 2
panic = "abort"
```

I expected to see this happen: `imul + jo to ud2`.

Or at least a possible asm output:

```
$ objdump -Cd -M intel target/debug/panic | grep "<bar>:" -A 7
0000000000000600 <bar>:
 600:	89 f8                	mov    eax,edi
 602:	0f af c7             	imul   eax,edi
 605:	70 01                	jo     608 <bar+0x8>
 607:	c3                   	ret    
 608:	50                   	push   rax
 609:	e8 12 00 00 00       	call   620 <core::panicking::panic>
 60e:	0f 0b                	ud2 
```

Instead, this happened:

```
$ objdump -Cd -M intel target/debug/panic | grep "<bar>:" -A 7
0000000000000600 <bar>:
 600:	89 f8                	mov    eax,edi
 602:	0f af c7             	imul   eax,edi
 605:	c3                   	ret           # sic! there is no `jo` to panic handler
 606:	66 2e 0f 1f 84 00 00 	nop    WORD PTR cs:[rax+rax*1+0x0]
 60d:	00 00 00 

0000000000000610 <main>:
```

`cargo +nightly rustc -- -Z insert-sideeffect` helped me to keep `jo to call panic + ud2`.
Still I want this code to optimize to `jo ud2` without `-Z insert-sideeffect`.

Related issue: https://github.com/rust-lang/rust/issues/28728

### Meta

Reproduced on rustc: on stable 1.37 and 1.42, on 1.44.0-nightly (2fbb07525 2020-03-26)

`rustc -vV`:
```
rustc 1.44.0-nightly (2fbb07525 2020-03-26)
binary: rustc
commit-hash: 2fbb07525e2f07a815e780a4268b11916248b5a9
commit-date: 2020-03-26
host: x86_64-unknown-linux-gnu
release: 1.44.0-nightly
LLVM version: 9.0
```

**Comment by Mark-Simulacrum** [comment]
I don't think a separate issue here is helpful; this has the exact same causes and effects as the primary issue. If you want this and are willing to use nightly, `core::intrinsics::abort()` will compile to ud2 or similar.
