### ISSUE TITLE
build.rs "rerun-if-env-changed" goes out of sync with the actual use site of the env var.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#70517]
This is still in `rustc_codegen_llvm`'s build script:
https://github.com/rust-lang/rust/blob/77621317d643cc5d13da60b26ab68b057668e688/src/librustc_codegen_llvm/build.rs#L4

But the use site has been moved here: https://github.com/rust-lang/rust/blob/77621317d643cc5d13da60b26ab68b057668e688/src/librustc_codegen_ssa/back/link.rs#L1427

This means that `rustc_codegen_ssa` won't be rebuilt when that env var changes. For the record, I haven't seen a bug from this, was just curious where `CFG_PREFIX` may be used and spotted the mismatch.

cc @bjorn3

**Comment by eddyb** [comment]
Found another one: `CFG_COMPILER_HOST_TRIPLE` is used in `src/librustc_session/config.rs` but it's still mentioned by `src/librustc_middle/build.rs`.

cc @Mark-Simulacrum Could we automate ensuring this? e.g. by searching for `env!` in tidy.

**Comment by Mark-Simulacrum** [comment]
Yeah, we can try I guess. Not sure :)

Maybe the right solution is that Cargo would, other than some whitelist, remove unknown variables from rustc's environment -- and the whitelist can be expanded via the build script env-tracking.

**Comment by eddyb** [comment]
@Mark-Simulacrum hmm I wonder if abusing the `.d` file format (from `--emit=dep-info`) or encoding this extra info in a comment, would be a good idea.

**Comment by Mark-Simulacrum** [comment]
You mean such that if you use `env!` we automatically tell Cargo to rebuild on changes? (That's https://github.com/rust-lang/rust/issues/40364).

But yeah, I think that would be good. Ideally this would be "well-integrated" vs. the current state of everyone having to remember to do it.
