### ISSUE TITLE
#! (shebang) stripping doesn't account for spaces.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#70528]
A file containing only this [correctly errors](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=b1d3380c63f1f1b66e5a74f386dfbaaa):
```rust
#![bad_attribute]
```

But this [doesn't error](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=7fab91b933ff640d6c0f627b3def6b5e), as it's stripped the same way [`#!/usr/bin/env ...` (i.e. "shebang")](https://en.wikipedia.org/wiki/Shebang_(Unix)) would be:
```rust
#! [bad_attribute]
```

In this third example, it also strips just the `#!`, [breaking the attribute](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=559a1136c52c2a255bf15e6e113dbb29):
```rust
#!
[bad_attribute]
```

The code responsible is this: https://github.com/rust-lang/rust/blob/8045865873f7cdbb864d0f66ef5ecb0d3ad847b2/src/librustc_lexer/src/lib.rs#L156-L160

It doesn't seem to account for any whitespace between the `!` and `[`.
I believe that we should allow any characters `c` where `c != '\n' && is_whitespace(c)` after the `#!`, and determine whether this is a shebang, by the next character on the same line:
* if there are no non-whitespace characters, it's not a valid shebang
* if the next character is `[`, this is the start of an inner comment
* otherwise, it's probably a shebang

I have no idea what to do for Rust comment syntax (`#!//...` and `#!/*...`), however.

And, of course, at the end of the day, this might be a backwards-incompatible change to make.

cc @matklad @petrochenkov

This issue has been assigned to @rcoh via [this comment](https://github.com/rust-lang/rust/issues/70528#issuecomment-626237132).

**Comment by ayushmishra2005** [comment]
@eddyb 

As I understood from the description, you are saying that 

1) This [errors](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=b1d3380c63f1f1b66e5a74f386dfbaaa) should also come for `#! [bad_attribute]`.
2) `#! /usr/bin/end`  should also be considered as valid shebang and Rust compiler will skip this line.

3) no changes for the third scenario:
#!
[bad_attribute]

Please confirm if we are on same page.

**Comment by eddyb** [comment]
@ayushmishra2005 All of those sound correct, yeah

**Comment by ayushmishra2005** [comment]
Thanks @eddyb . I would like to pick this issue.

@rustbot claim

**Comment by JohnTitor** [comment]
Fixed by #71372.

**Comment by eddyb** [comment]
There are issues with the fix (and it didn't go through Crater), so I'm preparing a revert.
