### ISSUE TITLE
Improve panic messages for Vec methods

### ISSUE THREAD

**Issue by IgorPerikov** [rust-lang/rust#70524]
I've spotted, that `remove()` panic message could've provided details on what values led to this panic, instead of mentioning condition only. Generally speaking this and some other `assert!`s in Vec could've been more detailed. If it's okay to step in, I'd like to offer my help.  

In case of `remove` I'd suggest calling this instead
```rust
assert!(index < len, "removal index {} should be less than length {}", index, len); 
```

I find this more informative than `assertion failed: index < len`

Candidates for improval:

aforementioned `remove`:
https://github.com/rust-lang/rust/blob/5f13820478907b09d50baf74f3ff2b78499ecd6c/src/liballoc/vec.rs#L1034

`insert`:
https://github.com/rust-lang/rust/blob/5f13820478907b09d50baf74f3ff2b78499ecd6c/src/liballoc/vec.rs#L994

`drain`:
https://github.com/rust-lang/rust/blob/5f13820478907b09d50baf74f3ff2b78499ecd6c/src/liballoc/vec.rs#L1292-L1293

`split_off`:
https://github.com/rust-lang/rust/blob/5f13820478907b09d50baf74f3ff2b78499ecd6c/src/liballoc/vec.rs#L1383

**Comment by IgorPerikov** [comment]
@Centril Does triaging mean a green light for this suggestion?

**Comment by Centril** [comment]
@IgorPerikov No, I just apply the relevant labels. :)

**Comment by Centril** [comment]
@IgorPerikov Though this is a small change with little time required to fix, so I'd just make the PR if I were you. :)

**Comment by RalfJung** [comment]
Note: https://github.com/rust-lang/rust/pull/70558 uses the same kind of assertion in `swap_remove` (as the old check had aliasing issues).

Depending on which PR lands first, we should make sure it gets the same panic message as the others.

**Comment by IgorPerikov** [comment]
@RalfJung I think it makes sense to follow the message, that is being currently printed, when trying to access element out of bounds via `[]`. Current message template is `index out of bounds: the len is {len} but the index is {index}`. I followed this idiom to keep it consistent.
