### ISSUE TITLE
Compiler can't infer const parameter from infallible array pattern

### ISSUE THREAD

**Issue by rodrimati1992** [rust-lang/rust#70529]
The compiler can't infer a const parameter based on the expected array type in an infallible pattern.

I tried this code:

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=4673d663e2f78cdc15395c1cc3701d67
```rust
#![feature(const_generics)]

struct ArrayChunks<'a,T,const N:usize>{
    rem: &'a [T],
}

impl<'a,T,const N:usize> Iterator for ArrayChunks<'a,T,N>{
    type Item=&'a [T;N];
    
    fn next(&mut self)->Option<&'a [T;N]>{
        if self.rem.len() < N {
            return None;
        }
        
        let (ret,rem)=self.rem.split_at(N);
        self.rem=rem;
        let ret=unsafe{ std::mem::transmute::<*const T,&[T;N]>(ret.as_ptr()) };
        Some(ret)
    }
}

fn as_chunks<T,const N:usize>(slice:&[T])-> ArrayChunks<'_,T,N> {
    ArrayChunks{rem:slice}
}

fn main(){
    for &[x,y] in as_chunks(&[0,1,2,3,4]) {
        println!("x:{:?} y:{:?}",x,y)
    }
}
```

I expected the code to compile and run without errors.

Instead, I got this compiler error:
```rust
error[E0730]: cannot pattern-match on an array without a fixed length
  --> src/main.rs:27:10
   |
27 |     for &[x,y] in as_chunks(&[0,1,2,3,4]) {
   |          ^^^^^
```

### Meta

The compiler was 1.44.0-nightly (2020-03-28 77621317d643cc5d13da)

This issue has been assigned to @lcnr via [this comment](https://github.com/rust-lang/rust/issues/70529#issuecomment-605910036).

**Comment by Centril** [comment]
Simplified:
```rust
#![feature(const_generics)]

fn as_chunks<const N: usize>() -> [u8; N] {
    loop {}
}

fn main() {
    let [x, y] = as_chunks();
}
```

**Comment by Centril** [comment]
The relevant code is defined here:

- https://github.com/rust-lang/rust/blob/8045865873f7cdbb864d0f66ef5ecb0d3ad847b2/src/librustc_typeck/check/pat.rs#L1360-L1366

- https://github.com/rust-lang/rust/blob/8045865873f7cdbb864d0f66ef5ecb0d3ad847b2/src/librustc_typeck/check/pat.rs#L1396-L1427

- https://github.com/rust-lang/rust/blob/8045865873f7cdbb864d0f66ef5ecb0d3ad847b2/src/librustc_typeck/check/pat.rs#L1460-L1468

**Comment by Centril** [comment]
To solve this, I suspect we'd need to register an obligation `CheckArrayPatLen { has_slice: bool, min_len: u64 }` which is the information required to check what `check_array_pat_len` does and then connect this to a const inference variable. Later on, we'll do the checks which were in `check_array_pat_len` when dealing with the obligation.

cc @varkor @eddyb

**Comment by eddyb** [comment]
What if we just handle the case in which they have to be equal, for now? Because that needs no obligation, you can just unify the constant with the length.

And you'd get a proper mismatch error if the length is not an inference variable.

**Comment by Centril** [comment]
Yeah, scratch what I said. We can tweak the branch here:
```rust
        } else {
            // No idea what the length is, which happens if we have e.g.,
            // `let [a, b] = arr` where `arr: [T; N]` where `const N: usize`.
            self.error_scrutinee_unfixed_length(span);
        }
```
and as you say, unify the constant with the known length.
