### ISSUE TITLE
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', src/librustc/hir/mod.rs:81:37

### ISSUE THREAD

**Issue by tronta** [rust-lang/rust#70523]
I am getting a ICE when compiling the attached code.
[code.zip](https://github.com/rust-lang/rust/files/4398375/code.zip)

As I'm not expert enough to do any reanalysis, I did not do any deduplication of other issues.

## Meta
rustc 1.44.0-nightly (f509b26a7 2020-03-18)
binary: rustc
commit-hash: f509b26a7730d721ef87423a72b3fdf8724b4afa
commit-date: 2020-03-18
host: x86_64-unknown-linux-gnu
release: 1.44.0-nightly
LLVM version: 9.0

## Backtrace:
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', src/librustc/hir/mod.rs:81:37

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: rustc 1.44.0-nightly (f509b26a7 2020-03-18) running on x86_64-unknown-linux-gnu
note: compiler flags: -C debuginfo=2 --crate-type lib
note: some of the compiler flags provided by cargo are hidden

**Comment by jonas-schievink** [comment]
Please update to the newest nightly and try again

**Comment by jonas-schievink** [comment]
fixed on nightly
