### ISSUE TITLE
 Internal Compiler Error: unexpected resolution for an identifier in pattern: SelfCtor(DefId(0:4))

### ISSUE THREAD

**Issue by dwrensha** [rust-lang/rust#70549]
I'm seeing an internal compiler error on the following input (found by [fuzz-rustc](https://github.com/dwrensha/fuzz-rustc)):

```rust
struct S {}
impl S {
    fn foo(&mur Self) {}
}
fn main() {}
```

```
$ rustc main.rs 
error: expected identifier, found keyword `Self`
 --> main.rs:3:17
  |
3 |     fn foo(&mur Self) {}
  |                 ^^^^ expected identifier, found keyword

error: expected one of `:`, `@`, or `|`, found keyword `Self`
 --> main.rs:3:17
  |
3 |     fn foo(&mur Self) {}
  |            -----^^^^
  |            |    |
  |            |    expected one of `:`, `@`, or `|`
  |            help: declare the type after the parameter binding: `<identifier>: <type>`

thread 'rustc' panicked at 'src/librustc_resolve/late.rs:1572: unexpected resolution for an identifier in pattern: SelfCtor(DefId(0:4))', /rustc/699f83f525c985000c1f70bf85117ba383adde87/src/libstd/macros.rs:13:23
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.44.0-nightly (699f83f52 2020-03-29) running on x86_64-unknown-linux-gnu

error: aborting due to 2 previous errors
```

The error happens on nightly but not on beta or stable.

**Comment by dwrensha** [comment]
Report from `cargo bisect-rustc`:

searched nightlies: from nightly-2020-03-09 to nightly-2020-03-30
regressed nightly: nightly-2020-03-16
searched commits: from https://github.com/rust-lang/rust/commit/7cdbc87a49b0b705a41a004a6d486b0952521ae7 to https://github.com/rust-lang/rust/commit/45ebd5808afd3df7ba842797c0fcd4447ddf30fb
regressed commit: https://github.com/rust-lang/rust/commit/e0f5df017368dc3f7cb458fc6d5a5e0420e1d2e5
source code: URL OF A REPOSITORY THAT REPRODUCES THE ERROR

**Comment by dwrensha** [comment]
#70006 looks like the probable culprit. cc @petrochenkov

**Comment by petrochenkov** [comment]
Will fix.

**Comment by Centril** [comment]
@petrochenkov Was already looking at this hehe, I have a fix for you in https://github.com/rust-lang/rust/pull/70555.
