### ISSUE TITLE
Provisioning issues for macOS in GHA

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#70570]
While looking through the GitHub Actions failures I noticed a few builds either failed to start or were killed due to provisioning issues in macOS.

Failed to provision:

* https://github.com/rust-lang-ci/rust/actions/runs/65748461

Received request to deprovision:

* https://github.com/rust-lang-ci/rust/actions/runs/65084440
* https://github.com/rust-lang-ci/rust/actions/runs/64385948

cc @ethomson, any clue why this is happening?

**Comment by ethomson** [comment]
I've not seen this before - @thejoebourneidentity can you help route this?

**Comment by pietroalbini** [comment]
GitHub fixed this issue on their end! :tada:
