### ISSUE TITLE
Do not suggest adding a type parameter on multi-letter types

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#70572]
In the process of writing some code, I didn't import an enum, resulting in

```
error[E0412]: cannot find type `AssignCommand` in this scope
  --> parser/src/command.rs:61:48
   |
61 |     fn maybe_parse_review(&mut self) -> Option<AssignCommand<'a>> {
   |                                                ^^^^^^^^^^^^^ not found in this scope
   |
help: possible candidate is found in another module, you can import it into scope
   |
1  | use crate::command::assign::AssignCommand;
   |
help: you might be missing a type parameter
   |
51 | impl<'a, AssignCommand> Input<'a> {
   |        ^^^^^^^^^^^^^^^
```

The import suggestion is great, but suggesting the type parameter seems likely to be confusing (and IMO, is almost certainly wrong). My suggested heuristic is to avoid suggesting the type parameter if we suggest a candidate in another module, at least, and possibly even avoid suggesting it always if there's more than on letter. It also seems suprising to suggest the type parameter on the impl and not the (more local) function?

I can try to come up with a MCVE, but I suspect it's pretty simple and I wanted to just not forget about this.

**Comment by estebank** [comment]
I do not know if only triggering for short idents is the best course of action: type params are stylistically one upper-case letter in many languages, but not in all. If you [come from Java](https://docs.oracle.com/javase/tutorial/java/generics/types.html) only triggering on one uppercase letter will be fine, but if [you come from Scala](https://docs.scala-lang.org/style/naming-conventions.html#type-parameters-generics) or [C++](https://google.github.io/styleguide/cppguide.html#Type_Names) you would expect `Foo` to be a stylistically valid type param. It doesn't matter what _Rust_'s naming convention is, the people that need these suggestions the most are not familiar with the language yet.

We no longer emit this suggestion when the type is found _somewhere_ and we suggest importing it. I _feel_ it might be enough to close this ticket, but don't _know_ for sure.

**Comment by Mark-Simulacrum** [comment]
I think that's enough, in particular given https://github.com/rust-lang/rust/issues/72640 as well. I don't think I've hit this since the import change landed, too, which makes it less of a concern for me.
