### ISSUE TITLE
Confusing suggestion on incorrect closing `}`

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#70583]
I tried this code:

```rust
pub enum ErrorHandled {
    Reported,
    TooGeneric,
}

impl ErrorHandled {
    pub fn assert_reported(self) {
        match self {
            ErrorHandled::Reported => {}
            ErrorHandled::TooGeneric => panic!(),
        }
    }
}

fn struct_generic(x: Vec<i32>) {
    for v in x {
        println!("{}", v);
    }
    } // <-- incorrect closing brace
}
```

I expected to see this happen: Some more or less helpful message about the imbalanced braces.

Instead, this happened: I got a rather confusing suggestion:
```
error: unexpected closing delimiter: `}`
  --> src/lib.rs:20:1
   |
9  |             ErrorHandled::Reported => {}
   |                                       -- this block is empty, you might have not meant to close it
...
20 | }
   | ^ unexpected closing delimiter
```
The empty block it points to is not even in the same function, so this suggestion is more confusing than helpful.

This issue has been assigned to @kper via [this comment](https://github.com/rust-lang/rust/issues/70583#issuecomment-606851389).

**Comment by kper** [comment]
In the last commit, I simply dropped the "block is empty..." message.
This leads to this error message now:
``` 
error: unexpected closing delimiter: `}`
  --> main.rs:20:1
   |
20 | }
   | ^ unexpected closing delimiter

error: aborting due to previous error
```
Any suggestions what to put there too?

**Comment by kper** [comment]
@RalfJung the PR has been merged. Is the issue resolved for you now? Can you close it?

**Comment by RalfJung** [comment]
Yes the new behavior is perfect, thanks. :)
