### ISSUE TITLE
Generate an empty main function when compiling for wasi without an explicit main?

### ISSUE THREAD

**Issue by lachlansneff** [rust-lang/rust#70592]
When compiling a binary for the `wasm-unknown-wasi` target, perhaps the rust compiler should insert an empty entry point (or rather one that runs initialization code, like pulling in program arguments and whatnot) if there isn't an explicit main function supplied.

**Comment by jonas-schievink** [comment]
Binaries need to specify an `fn main` though, or they won't compile. Or do you mean something else?

**Comment by lachlansneff** [comment]
Ah, sorry, yes I meant libraries that are compiled by themselves and not as part of a larger crate.
