### ISSUE TITLE
Rustdocs link is broken

### ISSUE THREAD

**Issue by xldenis** [rust-lang/rust#70603]
It seems that over the last 24 hours the link to the Rustdocs for the compiler has turned into a 404.

At the bottom of the README there is a link to this url:

https://doc.rust-lang.org/nightly/nightly-rustc/rustc/

which currently returns a Not Found response. 

I'm not sure if this is a problem caused by any recent changes to rustc or by the doc hosting itself. 

This issue has been assigned to @mksyposz via [this comment](https://github.com/rust-lang/rust/issues/70603#issuecomment-606736429).

**Comment by jonas-schievink** [comment]
The crate was renamed, the new link is https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/

Should be an easy fix, but I don't know where that page is located

**Comment by jonas-schievink** [comment]
Oh, the *readme*, duh

**Comment by mksyposz** [comment]
@rustbot claim
Seems easy enough for the first issue😄
