### ISSUE TITLE
Docker layer cache seems to not recognize changes in Rust binaries

### ISSUE THREAD

**Issue by Svedrin** [rust-lang/rust#70666]
I have a somewhat weird issue that I can't put my finger on. Since I have to start _somewhere_, I might as well start by posting an issue, so here goes.

I'm running into issues where, when I build a Docker image by `COPY`ing a Rust binary into a container, Docker's layer cache does not seem to recognize when that binary changes, and just re-uses last time's image. While this could easily be an error in my setup or a bug in Docker, I have only ever experienced this issue with Rust binaries so far, thus I'm posting here first.

# Steps to reproduce

Start by creating a Rust project:

```
~/tmp# cargo init --bin hello
     Created binary (application) project
~/tmp# cd hello/
~/tmp/hello# cargo build --release
   Compiling hello v0.1.0 (/home/mz1030/tmp/hello)
    Finished release [optimized] target(s) in 1.00s
```

This gives you a binary. Note its `sha1sum`:

```
~/tmp/hello# sha1sum target/release/hello
0b9e0dc2dc113b052232b4f5a04c57ef76ec1ce6  target/release/hello
```

Now we create a Dockerfile, build an image from it and validate the checksum:

```
~/tmp/hello# cat Dockerfile
FROM alpine:latest
RUN apk add --no-cache dumb-init

COPY target/release/hello /bin/hello

ENTRYPOINT ["dumb-init", "--"]
CMD [ "/bin/hello" ]

~/tmp/hello# docker build -t hello:latest .
Sending build context to Docker daemon  4.071MB
Step 1/5 : FROM alpine:latest
latest: Pulling from library/alpine
aad63a933944: Pull complete 
Digest: sha256:b276d875eeed9c7d3f1cfa7edb06b22ed22b14219a7d67c52c56612330348239
Status: Downloaded newer image for alpine:latest
 ---> a187dde48cd2
Step 2/5 : RUN apk add --no-cache dumb-init
 ---> Running in 9abea7ac6fac
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
(1/1) Installing dumb-init (1.2.2-r1)
Executing busybox-1.31.1-r9.trigger
OK: 6 MiB in 15 packages
Removing intermediate container 9abea7ac6fac
 ---> f171a2518ecd
Step 3/5 : COPY target/release/hello /bin/hello
 ---> fc04d81ee463
Step 4/5 : ENTRYPOINT ["dumb-init", "--"]
 ---> Running in 5037de0bd3a7
Removing intermediate container 5037de0bd3a7
 ---> 6d077c0dfb27
Step 5/5 : CMD [ "/bin/hello" ]
 ---> Running in c7e877c847c2
Removing intermediate container c7e877c847c2
 ---> d6f396bd4b13
Successfully built d6f396bd4b13
Successfully tagged hello:latest
```

```
~/tmp/hello# docker run --rm -it hello:latest sha1sum /bin/hello
0b9e0dc2dc113b052232b4f5a04c57ef76ec1ce6  /bin/hello
```

That's a match, so far so good.

Now we change something in the binary (just edit it to say something other than `Hello World`), rebuild the binary and see that its hash changed:

```
~/tmp/hello# vi src/main.rs
~/tmp/hello# cargo build --release
   Compiling hello v0.1.0 (/home/mz1030/tmp/hello)
    Finished release [optimized] target(s) in 0.36s
~/tmp/hello# sha1sum target/release/hello
56181859ee1d7ad861aa5f18e4daf84a5e3c056c  target/release/hello
```

We see the sha1sum has changed. Now we rebuild the Docker image. The layer cache re-uses the old images for any steps that haven't changed: Thus
when installing `dumb-init`, it'll notice that it has an image available where it did that already and just use that. However the `COPY` instruction
should notice that the checksum of the file that it's copying has changed, and build a new image rather than re-using the old one. So, here goes:

```
~/tmp/hello# docker build -t hello:latest .
Sending build context to Docker daemon  4.071MB
Step 1/5 : FROM alpine:latest
 ---> a187dde48cd2
Step 2/5 : RUN apk add --no-cache dumb-init
 ---> Using cache
 ---> f171a2518ecd
Step 3/5 : COPY target/release/hello /bin/hello
 ---> Using cache
 ---> fc04d81ee463
Step 4/5 : ENTRYPOINT ["dumb-init", "--"]
 ---> Using cache
 ---> 6d077c0dfb27
Step 5/5 : CMD [ "/bin/hello" ]
 ---> Using cache
 ---> d6f396bd4b13
Successfully built d6f396bd4b13
Successfully tagged hello:latest
```

Ohh boy, in step `3/5` it should _not_ have said `Using cache`. So now of course, when we look at the checksum again, we see that it has not changed:

```
~/tmp/hello# docker run --rm -it hello:latest sha1sum /bin/hello
0b9e0dc2dc113b052232b4f5a04c57ef76ec1ce6  /bin/hello
```

Only when we remove the old images and rebuild everything from scratch do we get the new binary:

```
~/tmp/hello# docker rmi hello:latest
Untagged: hello:latest
Deleted: sha256:d6f396bd4b13e49ae6dd612b5f93db7196ac141299303deebcdacf67b85b248a
Deleted: sha256:6d077c0dfb2736b87be4ee5b1796355373f7576050a42c8f30ddfec0efccde8f
Deleted: sha256:fc04d81ee463db042a5d6e7f4ae856dc7b7ee3c15aef65069017335839e1592d
Deleted: sha256:c6ba0a29cd4aa0eb04154e8299d7e0e667bcc33e2f8217d832d0c6847e24b8d9
Deleted: sha256:f171a2518ecd342d8eb9dd3477d4285d12819d644db28c11537575c7ecf4da77
Deleted: sha256:c17e01892104b8737d71d2889fac3f36d5e7edd4656c9a7c57d02cb9fadf235d

~/tmp/hello# docker build -t hello:latest .
Sending build context to Docker daemon  4.071MB
Step 1/5 : FROM alpine:latest
 ---> a187dde48cd2
Step 2/5 : RUN apk add --no-cache dumb-init
 ---> Running in 4b475f52c987
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
(1/1) Installing dumb-init (1.2.2-r1)
Executing busybox-1.31.1-r9.trigger
OK: 6 MiB in 15 packages
Removing intermediate container 4b475f52c987
 ---> 8eb5f09aeb19
Step 3/5 : COPY target/release/hello /bin/hello
 ---> 58d05bba80c0
Step 4/5 : ENTRYPOINT ["dumb-init", "--"]
 ---> Running in 672310f544ac
Removing intermediate container 672310f544ac
 ---> 3afc7f8e05e4
Step 5/5 : CMD [ "/bin/hello" ]
 ---> Running in f4c497de6866
Removing intermediate container f4c497de6866
 ---> 77e01b385995
Successfully built 77e01b385995
Successfully tagged hello:latest
```

```
~/tmp/hello# docker run --rm -it hello:latest sha1sum /bin/hello
56181859ee1d7ad861aa5f18e4daf84a5e3c056c  /bin/hello
```

# Other considerations

I managed to reproduce this behavior on two of my work machines plus in my CI setup. While those are all _my_ systems, I think they're sufficiently independent from one another so that I hope it's not just me.

Also I've run into this across several projects, some making pretty substantial changes in their binaries between builds.

I'm using Docker quite extensively across different projects, and I've only ever run into this when using Rust -- but as seen here, with Rust I run into it pretty reliably.

**Comment by Mark-Simulacrum** [comment]
Since this is likely a more complex interaction -- and seems plausibly some bug at the intersection of multiple systems (e.g. the fact that the "binary" you're referring to is almost certainly a hardlink, IIRC, which could confuse Docker), I would suggest asking this on users.rust-lang.org first, and if we can have a reproduction with just rustc then filing a bug here.

Thanks!

**Comment by Svedrin** [comment]
@Mark-Simulacrum indeed it _is_ a hardlink, and if I break it up, the file gets updated as intended :open_mouth: thanks for the hint!
