### ISSUE TITLE
"joke ICE" should dump flags

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#70661]
So I wanted to know which exact compiler flags playground is using, and I remembered flags get dumped on an ICE, so I thought I would be clever and [added `break rust;`](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=8f052287967ea0e3bd32e675d80ac645), our joke ICE.

But alas, it does not dump the flags that way. Could we make the joke ICE even more useful than it already is by making it print the compiler flags like normal ICEs do? :D

**Comment by rcoh** [comment]
So, I don't think regular ICE's dump flags?
```
➜  rust git:(russell/70677-raw-str-panic) ✗ rustc -g main.rs    
thread 'rustc' panicked at 'begin <= end (2 <= 1) when slicing `r"`', /rustc/76b11980ad416c3ad6143504c2277757ecacf9b5/src/libcore/str/mod.rs:1920:47
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.44.0-nightly (76b11980a 2020-04-01) running on x86_64-unknown-linux-gnu
```

but maybe I'm missing something

**Comment by RalfJung** [comment]
[This one does](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=aba595feaee264e28ade3c0e818b146b)

```
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.44.0-nightly (76b11980a 2020-04-01) running on x86_64-unknown-linux-gnu

note: compiler flags: -C codegen-units=1 -C debuginfo=2 --crate-type bin

note: some of the compiler flags provided by cargo are hidden
```

**Comment by RalfJung** [comment]
The irony of this is that only now do I realize that I posed this on April 1st.

But I was actually making this suggestion semi-seriously.^^
