### ISSUE TITLE
thread 'rustc' panicked at 'begin <= end (2 <= 1) when slicing `r"`'

### ISSUE THREAD

**Issue by dwrensha** [rust-lang/rust#70677]
On a recent commit (235938d, not yet on a nightly release), I'm seeing the following internal compiler error (found by [fuzz-rustc](https://github.com/dwrensha/fuzz-rustc)):

```
$ echo -n 'r"' > main.rs
$ build/x86_64-unknown-linux-gnu/stage1/bin/rustc main.rs
thread 'rustc' panicked at 'begin <= end (2 <= 1) when slicing `r"`', /home/dwrensha/src/rust/src/libcore/str/mod.rs:1920:47
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.44.0-dev running on x86_64-unknown-linux-gnu
```

**Comment by dwrensha** [comment]
I'm guessing that #70522 is to blame. cc @rcoh

**Comment by rcoh** [comment]
yeah probably me. will fix.

**Comment by dwrensha** [comment]
`cargo-bisect-rustc` confirms that https://github.com/rust-lang/rust/commit/235938d1acdd93d6641a741c81f64e415b786751 is where this error first showed up.

Also, the latest nightly is now out and it the error happens on it.
