### ISSUE TITLE
The miri engine may create pointers to thread locals

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#70684]
I haven't checked whether that is actually true, but we should have an unleash-the-miri-inside-of-you test for the following code snippet. In contrast to normal compilation I expect this to pass compilation and then segfault LLVM or similar, but we may catch it. No matter the result, we should have a test for it.

```rust
#![feature(thread_local)]

use std::thread;

#[thread_local]
static mut A: u8 = 0;

static B: &u8 = unsafe { &A };
```

([Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=454d0d4a5d1a35fc7af275dc40e8e48e))

Errors:

```
   Compiling playground v0.0.1 (/playground)
warning: unused import: `std::thread`
 --> src/lib.rs:3:5
  |
3 | use std::thread;
  |     ^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

error[E0625]: thread-local statics cannot be accessed at compile-time
 --> src/lib.rs:8:27
  |
8 | static B: &u8 = unsafe { &A };
  |                           ^

error: aborting due to previous error

error: could not compile `playground`.

To learn more, run the command again with --verbose.

```

**Comment by eddyb** [comment]
As I suggested elsewhere, I believe `#[thread_local]` `static`s should have their own separate access mechanism, probably their own `Rvalue` (or we could start extending what `Rvalue::{Ref,RawPtr}` can borrow).

That's because getting the address of a `#[thread_local]` `static` is a *fundamentally runtime* operation, and LLVM reusing the same syntax as for regular `static`s, is in the wrong here.

**Comment by oli-obk** [comment]
The "elsewhere" now having a canonical issue: https://github.com/rust-lang/rust/issues/70685

**Comment by oli-obk** [comment]
Ah so this won't work even with unleash mode, because of https://github.com/rust-lang/rust/blob/57e1da59cd0761330b4ea8d47b16340a78eeafa9/src/librustc_mir/transform/check_consts/ops.rs#L372

I guess we can address this together with #70685, our existing tests should be enough then
