### ISSUE TITLE
lexer: Use std::io::Read instead of &str

### ISSUE THREAD

**Issue by deeprobin** [rust-lang/rust#70687]
I think it's better to use the Read Trait rather than a &str, as it can handle larger files, perhaps larger than RAM in Lexer.
[Affected code](https://github.com/rust-lang/rust/blob/master/src/librustc_lexer/src/cursor.rs#L17-L24)

**Comment by Mark-Simulacrum** [comment]
cc @matklad -- this sounds like a fairly major change to the interface, and would also prohibit us from easily doing things like using memchr etc. I'm also not sure that in practice there's ever *source file* that we can't hold in memory; I can't imagine any compiler being able to compile them even if it can lex them

**Comment by jonas-schievink** [comment]
Source files are stored in the `SourceMap` anyways since diagnostics need to print chunks of source code, so I don't think this matters much

**Comment by matklad** [comment]
Yeah, I am completely sure that this is a premature generalization -- we use 32 bits offsets everywhere. 

What *could* be interesting is generalizing this to work with non-contigious strings (like ropes), but that shouldn't be done via the Read trait, as it's important to keep utf-8 invariant in, and io::Error out. 

But even that generalization is premature, String vs Rope is not nearly a bottleneck in rust-analyzer.  I am going to go ahead and close this.
