### ISSUE TITLE
Arc::drop creates a reference to partially dropped value

### ISSUE THREAD

**Issue by CAD97** [rust-lang/rust#70686]
I remembered why I wanted to implement `Layout::for_value_raw` now...

Relevant snippets:

```rust
struct ArcInner<T: ?Sized> {
    strong: atomic::AtomicUsize,
    weak: atomic::AtomicUsize,
    data: T,
}

pub struct Arc<T: ?Sized> {
    ptr: NonNull<ArcInner<T>>,
    phantom: PhantomData<ArcInner<T>>,
}

impl<T: ?Sized> Arc<T> {
    fn inner(&self) -> &ArcInner<T> {
        unsafe { self.ptr.as_ref() }
    }

    unsafe fn drop_slow(&mut self) {
        ptr::drop_in_place(&mut self.ptr.as_mut().data);

        if self.inner().weak.fetch_sub(1, Release) == 1 {
            acquire!(self.inner().weak);
            Global.dealloc(self.ptr.cast(), Layout::for_value(self.ptr.as_ref()))
        }
    }
}

unsafe impl<#[may_dangle] T: ?Sized> Drop for Arc<T> {
    #[inline]
    fn drop(&mut self) {
        if self.inner().strong.fetch_sub(1, Release) != 1 {
            return;
        }

        acquire!(self.inner().strong);

        unsafe {
            self.drop_slow();
        }
    }
}
```

Specifically, `Arc::drop_slow` (and `Weak::drop`) use `Layout::for_value(self.ptr.as_ref())`, which manifests `&ArcInner`.

I don't _think_ this is UB (otherwise, a lot of `ptr::drop_in_place(&mut place)` would be broken), but this code can definitely be improved by using `Layout::for_value_raw`. This issue is to track that.

**Comment by CAD97** [comment]
I take it back, this is probably a reference-to-freed. At least at the MIR level, the reference used for the `Layout::for_value` call is living until after the `dealloc` call. See [`_21` in the MIR for Arc::drop_slow as analyzed in the linked comment](https://github.com/rust-lang/rust/issues/55005#issuecomment-607682682).

**Comment by RalfJung** [comment]
See https://github.com/rust-lang/rust/issues/55005#issuecomment-607777497: at least according to Stacked Borrows, I do not think that there is a bug here.

But indeed my very first aliasing model experiment in 2017 was very unhappy with this code. So I agree using `for_value_raw` would be better here.

**Comment by CAD97** [comment]
This has been fixed; the relevant code now uses `Layout::for_value_raw` on the pointer instead of creating a reference.
