### ISSUE TITLE
Associated lang items

### ISSUE THREAD

**Issue by ecstatic-morse** [rust-lang/rust#70718]
Some associated items have a special meaning in the compiler, for example, `Fn::Output` and `Future::Output`. However, these associated types are often looked up [by name](https://github.com/rust-lang/rust/blob/537ccdf3ac44c8c7a8d36cbdbe6fb224afabb7ae/src/librustc_trait_selection/traits/project.rs#L1329), or worse [by definition order](https://github.com/rust-lang/rust/blob/537ccdf3ac44c8c7a8d36cbdbe6fb224afabb7ae/src/librustc_typeck/check/closure.rs#L685). We should be using the lang item machinery for them.

**Comment by lcnr** [comment]
relevant for #70705
