### ISSUE TITLE
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: SourceNotAvailable

### ISSUE THREAD

**Issue by dwrensha** [rust-lang/rust#70724]
I'm seeing an internal compiler error on the following input (found by [fuzz-rustc](https://github.com/dwrensha/fuzz-rustc)):

```rust
fn a() -> i32 {3}

pub fn main() {
    assert_eq!(a, 0);
}
```

```
$ rustc main.rs
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: SourceNotAvailable { filename: Real("/rustc/76b11980ad416c3ad6143504c2277757ecacf9b5/src/libcore/macros/mod.rs") }', src/librustc_typeck/check/op.rs:524:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.44.0-nightly (76b11980a 2020-04-01) running on x86_64-unknown-linux-gnu
```

**Comment by dwrensha** [comment]
Report from cargo-bisect-rustc:

searched nightlies: from nightly-2020-03-09 to nightly-2020-04-02
regressed nightly: nightly-2020-03-11
searched commits: from https://github.com/rust-lang/rust/commit/3dbade652ed8ebac70f903e01f51cd92c4e4302c to https://github.com/rust-lang/rust/commit/15812785344d913d779d9738fe3cca8de56f71d5
regressed commit: https://github.com/rust-lang/rust/commit/15812785344d913d779d9738fe3cca8de56f71d5

**Comment by Centril** [comment]
Fixed by https://github.com/rust-lang/rust/pull/70725.
