### ISSUE TITLE
A big performance regression in benchmarks

### ISSUE THREAD

**Issue by ljedrz** [rust-lang/rust#70785]
[rustc performance data](https://perf.rust-lang.org/compare.html?start=74bd074eefcf4915c73d1ab91bc90859664729e6&end=6050e523bae6de61de4e060facc43dc512adaccd&stat=instructions:u) shows a pretty big regression between [74bd074e](https://github.com/rust-lang/rust/commit/74bd074eefcf4915c73d1ab91bc90859664729e6) and [6050e52](https://github.com/rust-lang/rust/commit/6050e523bae6de61de4e060facc43dc512adaccd). I don't know if this is expected, but I'm putting this out there in case others see the dent in perf charts and wonder what had happened.

<hr/>

**EDIT**(@eddyb): we how have a [single-PR perf comparison showing the regression](https://perf.rust-lang.org/compare.html?start=9e55101bb681010c82c3c827305e2665fc8f2aa0&end=6050e523bae6de61de4e060facc43dc512adaccd&stat=instructions:u) for #69718.

#70156, the other PR in the range, [is much more of a mixed bag](https://perf.rust-lang.org/compare.html?start=74bd074eefcf4915c73d1ab91bc90859664729e6&end=9e55101bb681010c82c3c827305e2665fc8f2aa0&stat=instructions:u) (but only for a small subset of runs).

**Comment by jonas-schievink** [comment]
cc @arlosi @eddyb

**Comment by eddyb** [comment]
The range is https://github.com/rust-lang/rust/compare/74bd074eefcf4915c73d1ab91bc90859664729e6...6050e523bae6de61de4e060facc43dc512adaccd so the candidates are:
* #70156 "Make the rustc respect the `-C codegen-units` flag in incremental mode."
* #69718 "Add hash of source files in debug info"

Neither PR looks like it was tested for perf individually.

@Mark-Simulacrum I'm curious, why does 9e55101bb681010c82c3c827305e2665fc8f2aa0 (merge commit for #70156) not have its own perf run? Is there a way to trigger one now?

**Comment by Mark-Simulacrum** [comment]
9e55101 is in the queue: https://perf.rust-lang.org/status.html.

**Comment by arlosi** [comment]
It looks like this was caused by #69718. I'll start investigating why.

I timed several compilations of `ripgrep` locally in debug with and without #69718.

```
master (sec): 41 40 39 40 40
revert (sec): 34 34 34 36 34
```

**Comment by eddyb** [comment]
For the record, [this is the single-PR perf comparison showing the regression](https://perf.rust-lang.org/compare.html?start=9e55101bb681010c82c3c827305e2665fc8f2aa0&end=6050e523bae6de61de4e060facc43dc512adaccd&stat=instructions:u) from #69718.
I'll update it the issue description to minimize potential confusion.

@arlosi Two things I'm seeing:
1. there are way worse regressions than `ripgrep`, you can focus on the worse ones to get better contrast in measurements (e.g. `tokio-webpush-simple-debug` even has "patched incremental" runs  slowed down a lot, unlike many others, `clap-rs-debug` being another example I guess)
2. the detailed profile (if you click the percentage for a run) shows a lot of LLVM differences, e.g. for [`tokio-webpush-simple-debug` "clean"](https://perf.rust-lang.org/detailed-query.html?commit=6050e523bae6de61de4e060facc43dc512adaccd&base_commit=9e55101bb681010c82c3c827305e2665fc8f2aa0&benchmark=tokio-webpush-simple-debug&run_name=clean), and most of the regressions are `-debug`, with effectively no `-check` ones, so I think we might be able to get away without a revert, just adding a flag controlling whether LLVM sees these hashes (assuming that's the source of the slowdown)

**Comment by eddyb** [comment]
We have [perf data for the fix](https://perf.rust-lang.org/compare.html?start=7b657d340d715f48449189fea9d032350323a13f&end=607b8582362be8e26df7acc12fa242359d7edf95&stat=instructions:u) (#70803), which at a glance looks right.

[Before the regression to after the fix](https://perf.rust-lang.org/compare.html?start=9e55101bb681010c82c3c827305e2665fc8f2aa0&end=607b8582362be8e26df7acc12fa242359d7edf95&stat=instructions:u) looks like noise, and so does [after the regression to before the fix](https://perf.rust-lang.org/compare.html?start=6050e523bae6de61de4e060facc43dc512adaccd&end=7b657d340d715f48449189fea9d032350323a13f&stat=instructions:u), so I believe this confirms the fix is complete.

For the cost of MD5 hashing compared to SipHash, based on the changes to `-check` runs in the original regression, it looks insignificant.
