### ISSUE TITLE
`Fuse` impls expose use of specialization (`default fn`)

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#70796]
Context: https://github.com/rust-lang/rust/pull/70750#discussion_r403399312

We have some uses of `default fn` in `src/libcore/adapters/fuse.rs` which allow users to specialize those functions. Instead, these `default fn`s should be moved into internal (private) traits so that the specialization isn't exposed.

This issue has been assigned to @rakshith-ravi via [this comment](https://github.com/rust-lang/rust/issues/70796#issuecomment-609995816).

**Comment by rakshith-ravi** [comment]
Supp. Can I take this up?

**Comment by cuviper** [comment]
I fear what the extra indirection will do to #70332, but I guess we'll just have to see...

**Comment by rakshith-ravi** [comment]
Alright. I'll go through that as well and suggest changes there, in case I can think of any. 

Unlike my last PR, this time, I'd like to give this a shot without any mentoring. However, if I get stuck somewhere, I might request for help. Bear with me please.

Anyways, it's a little too late for me here (IST). Will get on it first thing tomorrow morning. Thanks

**Comment by rakshith-ravi** [comment]
So if I understand the situation correctly, we need to have `Iterator` inherit from `IteratorInternal` or something like that, which allows for specialization and perform all our specialized work on that, while not exposing the `default fn`s to anything outside the crate, yes?

This will also mean that `Iterator` will provide a blanket implementation that uses the `IteratorInternal`'s implementation.

**Comment by rakshith-ravi** [comment]
> It's also _possible_ that could work out better if there's a way for `Chain` to directly reach the non-specialized version, rather than shimming its own `Defuse` to avoid `FusedIterator` effects.

I don't think I entirely understand what you're saying. Could you help me clarify that please?

**Comment by cuviper** [comment]
We definitely don't want to change the `Iterator` trait, if that's what you mean. I would look at `Zip` and its `ZipImpl` to see how that's privately specialized.

> > It's also _possible_ that could work out better if there's a way for `Chain` to directly reach the non-specialized version, rather than shimming its own `Defuse` to avoid `FusedIterator` effects.
> 
> I don't think I entirely understand what you're saying. Could you help me clarify that please?

My thought was that we could make #70332 use some internal part of your work, e.g. `FuseImpl`, to bypass some of the nested calls. But now I'm also trying another `Chain` independent of `Fuse` in #70896 which I think is promising...

**Comment by rakshith-ravi** [comment]
Alrighty. Let me know if #70322 requires something specific so that I can implement it accordingly. Would be happy to dive deep into this.

**Comment by rakshith-ravi** [comment]
> We definitely don't want to change the `Iterator` trait, if that's what you mean. I would look at `Zip` and its `ZipImpl` to see how that's privately specialized.

Yup, an implementation similar to `ZipImpl` is exactly what I meant. I'll get right on it then
