### ISSUE TITLE
Const generics: `T` doesn't derive both `PartialEq` and `Eq`

### ISSUE THREAD

**Issue by Aloso** [rust-lang/rust#70790]
I tried this code:

```rust
#![allow(incomplete_features)]
#![feature(const_generics)]

pub trait GT<T: Eq + PartialEq, const N: T> {}
```

This produces the following error on rustc 1.44.0-nightly:

```shell
error[E0741]: the types of const generic parameters must derive `PartialEq` and `Eq`
 --> src/lib.rs:4:42
  |
4 | pub trait GT<T: Eq + PartialEq, const N: T> {}
  |                                          ^ `T` doesn't derive both `PartialEq` and `Eq`

error: aborting due to previous error
```

I guess that const generics with a generic type isn't supported/allowed. If that's the case, this should be mentioned in the error message.

### Meta

`rustc --version --verbose`:
```
rustc 1.44.0-nightly (74bd074ee 2020-04-03)
binary: rustc
commit-hash: 74bd074eefcf4915c73d1ab91bc90859664729e6
commit-date: 2020-04-03
host: x86_64-unknown-linux-gnu
release: 1.44.0-nightly
LLVM version: 9.0
```

**Comment by varkor** [comment]
This is a diagnostics issue. The type needs to *derive* `PartialEq + Eq`, not just implement them. This is because only `structural_match` types can be used for const generics at the moment, but we don't expose that to the user.

**Comment by Aloso** [comment]
@varkor thanks for fixing this so quickly!

Is there a chance that this restriction will be lifted, so the above code compiles?

**Comment by varkor** [comment]
We would like to lift the restriction, but probably not in the first stabilised version of const generics, as it's not easy to get right: we need to be very careful in making sure that we don't accidentally allow unsoundness to sneak in, and there are many subtleties.
