### ISSUE TITLE
build: Why use python in build scripts

### ISSUE THREAD

**Issue by deeprobin** [rust-lang/rust#70794]
Yes, you'll think why do I ask this question. In my opinion using Python as build script is one more dependency. And yes I haven't python installed. I could install it but is a rust build script not more efficient?

Why is there a python build script (x.py)?
I think because this is the rust language we should reduce the code to a minimum of other languages. 
Why not replace x.py with an build script (build.rs). Then rust could be built with `cargo build --release`

**Comment by jonas-schievink** [comment]
Question like this are better asked on https://internals.rust-lang.org/

The TL;DR is that we need to download a specific Rust version to bootstrap the compiler. The compiler build is also a lot more complex than just `cargo build`, but this process is already driven by Rust tooling (you can see more info about this here: https://rustc-dev-guide.rust-lang.org/building/bootstrapping.html).
