### ISSUE TITLE
`as u32` leads to panic

### ISSUE THREAD

**Issue by AlexanderMattheis** [rust-lang/rust#70810]
In the line that I marked with "BUG" I get a stacktrace. It exists also on the current nigtly version.

Test out by yourself https://github.com/AlexanderMattheis/filter/tree/217144a8101a99b797448e4b220be6db72751575

From my side it does not make any sense why it shouldn't work. The full code you find in `src/logic/statistics`.

I tried this code:

```rust
fn get_distribution_parameters(histogram: &[u32; NUMBER_OF_HISTOGRAM_BINS], num_pixels: usize) -> HistogramDistribution {
    let mut sum_a = 0;
    let mut sum_b = 0;

    for i in 0..NUMBER_OF_HISTOGRAM_BINS {
        let value = (i as u32) * (histogram[i] as u32);

        sum_a += value;
        sum_b += (i as u32) * value;  // BUG: i * (value as usize) works, but why?
    }

    let a = sum_a as f64;
    let b = sum_b as f64;
    let count_reciprocal = 1.0 / (num_pixels as f64);

    return HistogramDistribution {
        average: count_reciprocal * a,
        variance: (b - count_reciprocal * (a * a)) * count_reciprocal,
    };
}
```

**Version:**
```
rustc 1.41.1 (f3e1a954d 2020-02-24)
binary: rustc
commit-hash: f3e1a954d2ead4e2fc197c7da7d71e6c61bad196
commit-date: 2020-02-24
host: x86_64-unknown-linux-gnu
release: 1.41.1
LLVM version: 9.0
```

```
rustc 1.44.0-nightly (f509b26a7 2020-03-18)
binary: rustc
commit-hash: f509b26a7730d721ef87423a72b3fdf8724b4afa
commit-date: 2020-03-18
host: x86_64-unknown-linux-gnu
release: 1.44.0-nightly
LLVM version: 9.0
```

**Stacktrace:**
[stacktrace.txt](https://github.com/rust-lang/rust/files/4433554/stacktrace.txt)

The picture you can use to run my program ![Alex](https://user-images.githubusercontent.com/29164150/78493073-57f1be00-7749-11ea-8e64-6b96394a20c9.jpg)

**Comment by jonas-schievink** [comment]
Well, it looks like `sum_b` overflows. It's a `u32` here, but with the commented-out code it's a `usize` instead, which has a bigger range on 64-bit systems. I don't see anything unexpected here, so closing as not-a-bug.

**Comment by AlexanderMattheis** [comment]
Thank you, you were right. I thought somehow that `usize` is always 32-bit.
