### ISSUE TITLE
Is TypeFlags::NOMINAL_FLAGS unnecessary now?

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#70836]
This seems to contain *all* the flags in `TypeFlags`. If I'm guessing right, the flags that used to not be in here, all turned into queries? So they're now cached as queries, instead of by mutating `Ty` itself?
https://github.com/rust-lang/rust/blob/af89eb5e5beda2c1de0c0c031694892a51e8db07/src/librustc_middle/ty/mod.rs#L603-L624

cc @nikomatsakis @Zoxc

**Comment by nikomatsakis** [comment]
If it contains all the flags, then it seems to have no purpose. I'm honestly not sure what the name "nominal" is even meant to refer to here exactly -- I'm sure I gave it that name, but it's not very clear. I guess the point is "flags that should be inherited by containing types; ie., if the type `T` has some flag `F`, and `F` is "nominal", then `Vec<T>` should also have `F`".

Are there any flags that *don't* meet that definition anymore?

**Comment by eddyb** [comment]
@nikomatsakis I think there were "nominal flags" and "cached properties" (using interior mutability), but now the latter is completely gone.

**Comment by nikomatsakis** [comment]
that sounds right. I'd be in favor of removing `NOMINAL_FLAGS` then.

**Comment by tsandstr** [comment]
I would love to help with this one. A quick search shows that `NOMINAL_FLAGS` is only used once in the entire code base, here:

https://github.com/rust-lang/rust/blob/537ccdf3ac44c8c7a8d36cbdbe6fb224afabb7ae/src/librustc_middle/ty/flags.rs#L30-L32

Looks like this could just be changed to
`self.flags = self.flags | flags; `

Is that all it will take?

**Comment by eddyb** [comment]
Sounds correct, yeah.

**Comment by tsandstr** [comment]
Cool great

**Comment by tsandstr** [comment]
Oops, I'm still learning git. Sorry for the spam there. Only 4cdb206 is relevant.
