### ISSUE TITLE
'<' followed by a letter makes cargo doc hang on nightly

### ISSUE THREAD

**Issue by tiby312** [rust-lang/rust#70871]
If I run cargo doc on the below code, it never finishes.

```rust
///<a
fn main() {
    println!("Hello, world!");
}
```

I expected to see it finish.

Problem does not exist on stable

**Comment by jonas-schievink** [comment]
cc @rust-lang/rustdoc

**Comment by tmiasko** [comment]
Fixed upstream in https://github.com/raphlinus/pulldown-cmark/issues/438, but not released yet.

**Comment by GuillaumeGomez** [comment]
Let's hope next version will be released soon then! :)

**Comment by ollie27** [comment]
Unfortunately this also affects 1.43 beta.

**Comment by Mark-Simulacrum** [comment]
Hm so this will hit stable in less than a week then. Do we consider it high priority enough to try to push through a release ourselves? (e.g. we can temporarily fork or whatever, perhaps only on the beta branch).

I personally lean towards no but wouldn't be opposed to doing so if t-rustdoc wanted to.

**Comment by sjackman** [comment]
This issue halted development at our company for a day until we bisected the issue down to the particular line of code (a comment) that was causing `cargo test` to hang indefinitely. 😢

Thank you for all of your hard work on Rust. It is my most favourite language. I've been waiting for a suitable replacement for C++, and it has arrived! 😁

**Comment by Mark-Simulacrum** [comment]
Looks like there's movement on a point release, https://github.com/raphlinus/pulldown-cmark/pull/439.

I would be in favor of backporting this to beta, since it's a really painful bug to hit...

**Comment by sjackman** [comment]
`pulldown-cmark` 0.7.1 has been released.
https://github.com/raphlinus/pulldown-cmark/pull/438
https://github.com/raphlinus/pulldown-cmark/releases/tag/v0.7.1

**Comment by ehuss** [comment]
Yea, PR to update is up at #71682.
