### ISSUE TITLE
`cargo +nightly doc` panics for crates depending on gfx-backend-empty

### ISSUE THREAD

**Issue by grovesNL** [rust-lang/rust#70874]
If I create a new crate with
```bash
cargo new --lib rustdocissue
```

Then add a dependency on gfx-backend-empty version 0.5:
```toml
[dependencies]
gfx-backend-empty = "0.5"
```

Then run `cargo doc` on stable:
```bash
cargo +stable doc --lib --no-deps
```

`cargo doc` succeeds with warnings. I'm not sure if the warnings are relevant, but the warnings in `cargo +stable doc` are for some empty blocks in examples that haven't been populated, such as:
```
/// ```no_run
///
/// ```
```

Now if I run the same command on nightly (`nightly-2020-04-06`):
```bash
cargo +nightly doc --lib --no-deps
```

`cargo doc` panics with the following error:

```
thread 'rustc' panicked at 'could not find markdown in source', src/librustdoc/passes/mod.rs:411:31
```

The panic originates in https://github.com/rust-lang/rust/blob/1ccb0b4a020cac07a9772d0da722869096a46cef/src/librustdoc/passes/mod.rs#L411

Besides `stable` and `nightly`, I tried the `nightly-2020-03-19` toolchain which succeeds with warnings (like `stable`).

I also created a repo which reproduces the issue at https://github.com/grovesNL/rustdocissue if it's convenient to clone that instead of following the steps above.

**Comment by jonas-schievink** [comment]
cc @rust-lang/rustdoc

**Comment by GuillaumeGomez** [comment]
Oh that's bad. We should make a warning about empty code blocks though. I'll send a PR shortly.

**Comment by GuillaumeGomez** [comment]
It's not crashing the last nightly either. Something changed between the two but I really wonder what...

**Comment by eddyb** [comment]
cc @arlosi - we're discussing this on Discord and @GuillaumeGomez has bisected it to #69718.

**Comment by arlosi** [comment]
It seems that before #69718, the hash would not have matched, so the external source would be "not present". After #69718, the external source would be present, but not-normalized. Which I suspect would cause any offsets into it to be incorrect.

I'm not exactly sure how it worked before (given that it would have absent external source).
