### ISSUE TITLE
Rust authentication services are down

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#70885]
Due to the ongoing [GitHub Pages incident](https://www.githubstatus.com/incidents/f3xzj5fgfq5b), the team API is down, which affects many of our services:
 * bors approval/try/etc will not acknowledge users
 * triagebot will not work
 * rust-timer will not work
 * (and possibly more)

We do not have a planned fix in the short-term; hopefully GitHub pages will be back up soon. In the long term we will explore moving the resources to multiple hosting platforms.

**Comment by jonas-schievink** [comment]
It's fixed :tada:
