### ISSUE TITLE
use path and documentation

### ISSUE THREAD

**Issue by montag451** [rust-lang/rust#70880]
Hi,

In the chapter about use declarations in _The Reference_ book (https://doc.rust-lang.org/reference/items/use-declarations.html#use-paths), the book states that:

> Paths in use items must start with a crate name or one of the path qualifiers crate, self, super, or ::.

It then gives a code snippet with examples of what is allowed and what is not. In particular the line:
```rust
//  use example::iter;      // bad: relative paths are not allowed without `self`
```
is commented out because it shouldn't compile but when I tried to compile the snippet on the playground with the line uncommented, the compilation was successful (using 2018 edition).

Am I wrong or the book contains an error?

**Comment by ehuss** [comment]
No, the reference is wrong.  We have a few PRs open to change it (https://github.com/rust-lang/reference/pull/665 and https://github.com/rust-lang/reference/pull/697), but haven't gotten it updated.

I'm going to close, as this is a known issue.  In the future, if you find any problems with the reference, it is best to file against the reference issue tracker at https://github.com/rust-lang/reference/issues.
