### ISSUE TITLE
Add support for GitHub Actions to rust-log-analyzer

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#70890]
https://github.com/rust-lang/rust-log-analyzer will need to be updated to listen for GitHub Actions events before we can migrate.

**Comment by aidanhs** [comment]
From infra meeting today, from @pietroalbini 

> adding support for GHA to RLA is blocked at the moment since there are some missing APIs
i.e. we can't get the information from the actions API after receiving a webhook, and we can't correlate a build with a PR to post the error message
we can workaround the PR correlation if we print the PR number in the build logs
but I wasn't able to came up with a way to get the information after receiving the webhook yet
(granted, I've not spent much time thinking about it)
I have a branch half-done, if someone wants to take it from there I can push it

We will be revisiting the status of the APIs in the infra meeting in two weeks time, to see if we need the workaround or not (we'll have an update on whether the APIs might be incoming at that point).

**Comment by pietroalbini** [comment]
I came up with two workarounds that might unblock us here:

* As I said in the meeting, to correlate builds with PRs we can do the same thing we do today for job names, and write something like this in the build logs:

  ```
  [CI_PR_NUMBER=12345]
  ```

* To get information from the Actions API after receiving a webhook we can [fetch the last 100 builds that happened in the repository](https://developer.github.com/v3/actions/workflow_runs/#list-repository-workflow-runs) and, if any of them have the same Check Suite ID as the webhook, [we fetch all the jobs for that run](https://developer.github.com/v3/actions/workflow_jobs/#list-jobs-for-a-workflow-run) and compare the Check Run ID. It's really API-heavy, but until they provide a proper way to fetch the Actions API information from a webhook I worry it's the only option.

**Comment by Mark-Simulacrum** [comment]
AFAICT, the check suite events should give us what we need: https://developer.github.com/v3/activity/events/types/#checksuiteevent 

I think the PR list there will be empty for bors commits, but in that case we can look at the SHA and fetch that to parse out the commit from the bors commit message.

That doesn't support the PR builds I think directly but in the worst case we can keep track (or re-scan) the commit heads of all open pull requests and compare against those.

**Comment by pietroalbini** [comment]
> AFAICT, the check suite events should give us what we need: developer.github.com/v3/activity/events/types/#checksuiteevent

Not really. To get all the information RLA needs we need to rely on the [GitHub Actions API](https://developer.github.com/v3/actions/) instead of the [Checks API](https://developer.github.com/v3/checks/), but the problem is, the IDs used in the GHA API are different than the IDs used by the Checks API, and those webhooks only include the Checks API IDs.

> I think the PR list there will be empty for bors commits, but in that case we can look at the SHA and fetch that to parse out the commit from the bors commit message.

For auto/try builds [RLA already extracts the PR number from the commit message](https://github.com/rust-lang/rust-log-analyzer/blob/0c6fe7d6c28848eea0253e5ae31743b774f4505a/src/bin/server/worker.rs#L179-L189).

> That doesn't support the PR builds I think directly but in the worst case we can keep track (or re-scan) the commit heads of all open pull requests and compare against those.

Hmm, I think it's still less effort to include the PR number in the log. [RLA already does a similar thing for the job name](https://github.com/rust-lang/rust-log-analyzer/blob/0c6fe7d6c28848eea0253e5ae31743b774f4505a/src/bin/server/worker.rs#L297-L309).

**Comment by Mark-Simulacrum** [comment]
Okay. One hurdle that may not really be surmountable without storing all the logs ourselves is that GitHub doesn't have permanent direct "raw" log URLs -- you need to get a URL that's only valid for a minute I think (https://developer.github.com/v3/actions/workflow_runs/#list-workflow-run-logs).

**Comment by pietroalbini** [comment]
While there is no permanent link available from the API, we can reconstruct the URL the frontend uses:

```
https://github.com/{org}/{repo}/commit/{sha}/checks/{check_id}/logs
```

**Comment by pietroalbini** [comment]
Finished writing the code, I'll test that everything works as expected tomorrow, and then open a PR with the changes.

**Comment by pietroalbini** [comment]
I will also need to change RLA to stop hardcoding rust-lang/rust and support receiving builds from rust-lang-ci/rust as well.
