### ISSUE TITLE
Can we stabilize a function returning an unstable type which uses const generics without stabilizing const generics?

### ISSUE THREAD

**Issue by LukasKalbertodt** [rust-lang/rust#70903]
This question is important for #65819. No need to read that discussion though!

My idea is to discuss and decide on this specific question here, potentially via FCP, to get a clear answer for #65819, but without the iterator-specific concerns from that PR. If you don't think this is a useful approach to this decision, let me know!

### The question

```rust
// Uses const generics, is unstable.
#[unstable]
struct Foo<const N: usize>(...);

// Does not use const generics itself
fn foo() -> Foo<1> { ... }
```

Assuming `Foo` could be implementing *without* const generics (but isn't because of reasons), the question is: **Can we stabilize `foo` before we stabilize const generics without accidentally also stably exposing a part of const generics?**

Users cannot refer to `Foo` on stable, so it also seems like they cannot use the const parameter of that type in any way. But maybe I am missing something and via tricks one could "access" const generics via `Foo` on stable?

### Current state of related things

I think we do not currently have any stable function returning an unstable type in `std` (completely ignoring const generics). If I missed one, please let us know! There are only a couple of unstable traits that are "usable" on stable (like `Try` and `Step`). 

### Related discussion

@SimonSapin:

> I’d be really uncomfortable with a stable API that returns an unstable type. It means that programs on the Stable channel can manipulate values of that type, making it effectively stable in some ways.

@cuviper:

> We would be saying that the type has to exist with such functionality (almost like `impl Trait` if it were allowed in this position), but we wouldn't be committing to its exact generic type signature. IMO that's acceptable, [...]

@Mark-Simulacrum:

> so as long as we avoid stabilizing the specific [type] signature I am not particularly worried about [having a stable method return an unstable type]. If that means the entire type is not stable, that also seems fine.

Also CC @Centril @withoutboats

**Comment by cuviper** [comment]
> Assuming `Foo` could be implementing _without_ const generics (but isn't because of reasons), the question is: **Can we stabilize `foo` before we stabilize const generics without accidentally also stably exposing a part of const generics?**

I think the question is also useful in general, aside from const generics. Suppose we did implement `Foo` without const generics, but didn't want to stabilize that yet, would it be OK for stable `foo()` to return that unstable type?

If the answer is no, then the compiler should probably enforce this, just like the `private-in-public` lint. The existing uses of unstable traits in stable APIs can be explicitly allowed.

**Comment by withoutboats** [comment]
It would be helpful to answer the question to say explicitly what a user can do if we stabilize the function but not the type. My understanding is that they can access trait implementations and stable methods on the type, but not manipulate the signature of the type at all. So if the type path were to change (gaining or losing parameters, changing names, etc) it would not impact stable at all.

Personally, I'm alright with this sort of semistability of a type in some instances, including the one we're concerned about. But we need to confirm exactly what we're stabilizing by doing that in order to build any consensus about whether it's alright.

**Comment by Krantz-XRF** [comment]
> they can access trait implementations and stable methods on the type, but not manipulate the signature of the type at all

What if "whether or not (the yet unstable type) `U` implements trait `T`" is not yet decided? Do we have a mechanism to declare a trait impl itself unstable?

**Comment by lcnr** [comment]
no, all trait impls are instantly stable.

Considering that `min_const_generics` has now been stabilized i think that this question isn't really relevant anymore.
Is there something we still want to do here or can we just close?

**Comment by SimonSapin** [comment]
Agreed.
