### ISSUE TITLE
Tracking Issue for future readiness functions

### ISSUE THREAD

**Issue by yoshuawuyts** [rust-lang/rust#70921]
This is a tracking issue for `core::future::{pending,ready}`.
The feature gate for the issue is `#![feature(future_readiness_fns)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also uses as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [x] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Implementation history

- Initial implementation in https://github.com/rust-lang/rust/pull/70834
- Stabilization PR in https://github.com/rust-lang/rust/pull/74328

**Comment by petertodd** [comment]
Currently we have:

```
pub struct Pending<T> {
    _data: marker::PhantomData<T>,
}
```

That means `Pending<T>` has dropcheck behavior as though it owns a `T` value, which it doesn't. Should we instead change it to:

```
pub struct Pending<T> {
    _data: marker::PhantomData<fn() -> T>,
}
```

I believe that is a strict improvement without any compatibility issues, as the variance is the same.

**Comment by yoshuawuyts** [comment]
@petertodd this was discussed in https://github.com/rust-lang/rust/pull/70834 and decided against. Some of the conversation happened in code comments, so it may require expanding some closed comments to get the full conversation.

With the release of 1.48 these PRs have been stabilized, so it's probably time to close! Any conversation about these APIs should probably happen in their own PRs.

**Comment by petertodd** [comment]
Thanks for the reply! I missed those comments. Anyway, too small a difference to worry about now if it's already been discussed.
