### ISSUE TITLE
Tracking Issue for `fn VecDeque::make_contiguous`

### ISSUE THREAD

**Issue by lcnr** [rust-lang/rust#70929]
This is a tracking issue for `fn make_contiguous` of `VecDeque`.
The feature gate for the issue is `#![feature(deque_make_contiguous)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also uses as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [ ] include a note in the `VecDeque` struct docs recommending `make_contiguous` for sorting.
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr

### Implementation history
- initial implementation in #69425

**Comment by jonhoo** [comment]
Are there any blockers for stabilization of this feature?

**Comment by lcnr** [comment]
Don't think so, don't have the time to push this to stabilization myself though.

**Comment by jonhoo** [comment]
I can push this through if @jonas-schievink and @Dylan-DPC think that a stabilization PR is warranted?

**Comment by jonas-schievink** [comment]
You'll have to ask the libs team; you can find them on Zulip

**Comment by Dylan-DPC** [comment]
Normally we wait for a few months to gain any feedback (though this is small) so i'd wait a bit to see if there are any concerns

**Comment by jonhoo** [comment]
@Dylan-DPC This landed back in April, so it's been three months — how long do you generally want the trial period to run for?

**Comment by 95th** [comment]
Just here to say that I also need this feature in my application.

**Comment by jonhoo** [comment]
@jonas-schievink I pinged the libs team on Zulip now, so we'll see :)
Thread here: https://rust-lang.zulipchat.com/#narrow/stream/122651-general/topic/vecdeque_make_contiguous

**Comment by jonhoo** [comment]
@95th Stabilization PR now up at https://github.com/rust-lang/rust/pull/74559 :tada:

**Comment by jonhoo** [comment]
Will be released in `1.48` :tada:
