### ISSUE TITLE
Hard to read error message with 2D line drawing and multi-line expressions

### ISSUE THREAD

**Issue by steffahn** [rust-lang/rust#70935]
Especially the fact that the lines are broken up seems like a bug.

```rust
use core::future::Future;
use futures::future::{BoxFuture, FutureExt};

async fn baz<T>(_c: impl FnMut() -> T) where T: Future<Output=()> {
}

fn foo(tx: std::sync::mpsc::Sender<i32>) -> BoxFuture<'static, ()>{
    async move {
        baz(|| async{
            foo(tx.clone());
        }).await;
    }.boxed()
}

fn bar(_s: impl Future + Send) {
}

fn main() {
    let (tx, _rx) = std::sync::mpsc::channel();
    bar(foo(tx));
}
```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=5ced1cdea9b2d8b7827d73057b82fa91))

Errors:

```
   Compiling playground v0.0.1 (/playground)
error: future cannot be sent between threads safely
  --> src/main.rs:12:7
   |
12 |     }.boxed()
   |       ^^^^^ future returned by `foo` is not `Send`
   |
   = help: the trait `std::marker::Sync` is not implemented for `std::sync::mpsc::Sender<i32>`
note: future is not `Send` as this value is used across an await
  --> src/main.rs:9:9
   |
9  |            baz(|| async{
   |  __________^___-
   | | _________|
   | ||
10 | ||             foo(tx.clone());
11 | ||         }).await;
   | ||         -      ^- `|| async{
            foo(tx.clone());
        }` is later dropped here
   | ||_________|______|
   | |__________|      await occurs here, with `|| async{
            foo(tx.clone());
        }` maybe used later
   |            has type `[closure@src/main.rs:9:13: 11:10 tx:&std::sync::mpsc::Sender<i32>]`

error: aborting due to previous error

error: could not compile `playground`.

To learn more, run the command again with --verbose.

```

@rustbot modify labels: A-diagnostics, C-bug, D-papercut, T-compiler

**Comment by estebank** [comment]
There are two things here

1. We have a label that has embedded newlines which causes the broken down ASCII art
2. We should find a way to reverse the order in which multiline spans are sorted, but this will require handling multiple labels. The current order is optimized for not having to tweak the label positions, but when no labels are involved, we could do much better.

**Comment by tmandry** [comment]
So, using raw text from the program as part of our label feels like a hack. We should try to come up with another way of getting a name (and falling back to a description like "async block" or something if that doesn't work). Failing a good way of doing that, I guess we can scan the program text for newlines and only use it if there aren't any..

**Comment by estebank** [comment]
Agree, we should never be using snippets in labels. The change needs to happen in

https://github.com/rust-lang/rust/blob/7b005c5fcb743e97b3cafee951b19fe7e51753c8/src/librustc_trait_selection/traits/error_reporting/suggestions.rs#L1400-L1426
