### ISSUE TITLE
"mismatched types" on indexing into trait with two Index subtraits via output type

### ISSUE THREAD

**Issue by fabianschuiki** [rust-lang/rust#70944]
If a trait has two or more `Index` subtraits, and one obtains a reference to something that implements that trait under specific conditions, typeck reports an error for indexing with all but the last `Index`'s key. Seems to happen only if that reference was obtained through another trait's output type.

Consider the following example ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=619415d35b0211d5daffd055f90593ae)):
```rust
use std::ops::Index;

struct KeyA;
struct KeyB;
struct KeyC;

trait Foo: Index<KeyA> + Index<KeyB> + Index<KeyC> {}
trait FooBuilder {
    type Inner: Foo;
    fn inner(&self) -> &Self::Inner;
}

fn do_stuff(foo: &impl FooBuilder) {
    let inner = foo.inner();
    &inner[KeyA];
    //     ^^^^ expected struct `KeyC`, found struct `KeyA`
    &inner[KeyB];
    //     ^^^^ expected struct `KeyC`, found struct `KeyB`
    &inner[KeyC];
}
```

This breaks with the message:
```
error[E0308]: mismatched types
  --> src/lib.rs:15:12
   |
15 |     &inner[KeyA];
   |            ^^^^ expected struct `KeyC`, found struct `KeyA`

error[E0308]: mismatched types
  --> src/lib.rs:16:12
   |
16 |     &inner[KeyB];
   |            ^^^^ expected struct `KeyC`, found struct `KeyB`
```

The issue does not occur if the indexing is performed on a `Foo` directly. That is, the following works just fine ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=ede84fb6ba7fe32eda13633e99a14e68)):
```rust
fn do_stuff(foo: &impl Foo) {
    let inner = foo;
    &inner[KeyA];
    &inner[KeyB];
    &inner[KeyC];
}
```

What I would expect to happen is that all three index operations work. More specifically, I would expect each of the operations to produce the corresponding `Index::Output` type correctly.

### Meta

`rustc --version --verbose`:
```
rustc 1.42.0 (b8cedc004 2020-03-09)
binary: rustc
commit-hash: b8cedc00407a4c56a3bda1ed605c6fc166655447
commit-date: 2020-03-09
host: x86_64-unknown-linux-gnu
release: 1.42.0
LLVM version: 9.0
```

**Comment by fabianschuiki** [comment]
The problem also occurs if `Index::index` is called explicitly ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=4a6f352218029551ab275608a53f1ed0)):
```
fn do_stuff(foo: &impl FooBuilder) {
    let inner = foo.inner();
    inner.index(KeyA);
    //          ^^^^ expected struct `KeyC`, found struct `KeyA`
    inner.index(KeyB);
    //          ^^^^ expected struct `KeyC`, found struct `KeyB`
    inner.index(KeyC);
}
```

Or also when `Index::index` is called explicitly ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=ad54f0054863790a9c12d9d4ed0e5f7c)):
```
fn do_stuff(foo: &impl FooBuilder) {
    let inner = foo.inner();
    Index::index(inner, KeyA);
    //                  ^^^^ expected struct `KeyC`, found struct `KeyA`
    Index::index(inner, KeyB);
    //                  ^^^^ expected struct `KeyC`, found struct `KeyB`
    Index::index(inner, KeyC);
}
```

However, the *problem does not occur* if the key type is specified together with the `Index` trait ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=e68267af1f5394eb371551e22fea29f3)):
```
fn do_stuff(foo: &impl FooBuilder) {
    let inner = foo.inner();
    Index::<KeyA>::index(inner, KeyA);
    Index::<KeyB>::index(inner, KeyB);
    Index::<KeyC>::index(inner, KeyC);
    // works just fine
}
```

**Comment by WaffleLapkin** [comment]
Feels like a duplicate of #72582

**Comment by WaffleLapkin** [comment]
This is fixed on nightly. Presumably by #73905

**Comment by steffahn** [comment]
Bisection points to 08e2d4616613716362b4b49980ff303f2b9ae654, so it is #73905 indeed. I guess we still need @rustbot modify labels to E-needs-test.
