### ISSUE TITLE
ty::print::pretty's p! macro should support string literals.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#70948]
E.g. printing `ty::Slice(ty)` uses:
```rust
p!(write("["), print(ty), write("]"))
```
but we could allow writing it like this, by letting the macro use `$...:literal`:
```rust
p!("[", print(ty), "]")
```

But I'm not sure the macro can handle it easily.

Maybe we should just have `Print` implemented for more types and just make `p!(a, b, c)` print `a`, `b` and `c` (and we can then rename it to `print!`).

This issue has been assigned to @jakevossen5 via [this comment](https://github.com/rust-lang/rust/issues/70948#issuecomment-612538731).

**Comment by Alexendoo** [comment]
Hi @jakevossen5, are you still working on this issue?

**Comment by jakevossen5** [comment]
So sorry for the lack of communication on this. I am, have gotten a bit busy this summer but have some stuff wrapping up and hope to get it done soon. If this is blocking or causing problems, then someone else can take it but if not I would still like to work on this.

**Comment by Alexendoo** [comment]
No problem @jakevossen5, it's not blocking anything I'm just checking claimed issues to see if people are still interested in working on them
