### ISSUE TITLE
ICEs should always print the top of the query stack.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#70953]
E.g. for #70942, instead of:
<pre>
<strong>error: internal compiler error: unexpected panic</strong>

<strong>note: the compiler unexpectedly panicked. this is a bug.</strong>
</pre>

We could print something more like

<pre>
<strong>error: internal compiler error: unexpected panic</strong>
    while const-evaluating `main::{{constant}}#0`
    ... (full query stack hidden, use `RUST_BACKTRACE=1` to enable)

<strong>note: the compiler unexpectedly panicked. this is a bug.</strong>
</pre>

(not super sure about the `RUST_BACKTRACE=1` suggestion message)

This (and the query stack more generally) should allow quicker diagnosis, and there should be no cost to just having this on by default for ICEs.

It could also be useful to users, as they could use it to figure out roughly where in their code they're triggering the ICE (similar to the `Span` from a `span_bug!`), to work around the ICE in the meanwhile or know which error to fix (in case it's a side-effect of an error) to get rid of the ICE.

cc @rust-lang/compiler @rust-lang/wg-diagnostics

**Comment by eddyb** [comment]
Nominating for a vibe check (this should be easy to implement if we agree we want it).

**Comment by Zoxc** [comment]
Getting / printing the query stack may panic, so I'd prefer it to be done after printing the backtrace, but I guess that would be hidden by default anyway.

**Comment by bjorn3** [comment]
I think always enabling backtraces for rustc would be useful, as it ensures that all bug reports contain a backtrace. Even when the issue is not reproducable.

**Comment by pnkfelix** [comment]
discussed in [yesterday's T-compiler meeting](https://zulip-archive.rust-lang.org/131828tcompiler/54835weeklymeeting2020040954818.html#193461875). There was general support for adding information about the query context to the ICE output. 

when we had a second ad hoc triage meeting today, @eddyb [added](https://zulip-archive.rust-lang.org/131828tcompiler/35095adhoctriagemeeting2020041054818.html#193574362) that we had issues in the past with trying to always emit backtraces (but it is possible that they have been fixed).
 * To be honest, I wasn't clear on whether @bjorn3 's suggest was to print out (unconditionally) the call stack backtrace, or the query stack. 

In any case, it seems like we can immediately work on adding a printout for the top of the query stack, and leave the question of whether to add more info beyond that to a later discussion.

**Comment by eddyb** [comment]
> we had issues in the past with trying to always emit backtrace

Not "always emit", but rather issues when enabling it via `RUST_BACKTRACE=1`, such as taking a minute to compute the backtrace or strange crashes. We may have updated/fixed `libbacktrace` since though.

If we ever made the default to emit the backtrace, `RUST_BACKTRACE=0` could be used as an opt-out.

**Comment by bjorn3** [comment]
> To be honest, I wasn't clear on whether @bjorn3 's suggest was to print out (unconditionally) the call stack backtrace, or the query stack.

Both

**Comment by eddyb** [comment]
Something I completely forgot is that the query stack sometimes even has `Span`s (originally added for query cycle errors), so we could also try to show those, which could give even more precision to what part of the user code triggered the query that ICE'd.

**Comment by oli-obk** [comment]
For anyone looking to implement this. The relevant work needs to be done in https://github.com/rust-lang/rust/blob/86c0b85da98a3c69e0fc9014e36e1c88bd3ae8d7/src/librustc_driver/lib.rs#L1156. The query stack is reported in https://github.com/rust-lang/rust/blob/86c0b85da98a3c69e0fc9014e36e1c88bd3ae8d7/src/librustc_driver/lib.rs#L1207, so I think we need another function for printing just the top of the query stack.

**Comment by georgio** [comment]
I'm trying to work on this. Is there some sort of template we are targeting?

My proposed solution is adding something like 
`pub fn try_print_query_stack_head(handler: &Handler) {...}`
somewhere around here https://github.com/rust-lang/rust/blob/86c0b85da98a3c69e0fc9014e36e1c88bd3ae8d7/src/librustc_middle/ty/query/plumbing.rs#L127

**Comment by oli-obk** [comment]
You could also add a `num_frames: Option<usize>` argument to `try_print_query_stack` that makes it stop after that number of elements (if any). This way you can just adjust a few invocation sites instead of having to build a new function that does almost the same.

**Comment by georgio** [comment]
Great idea, thanks. I assumed that we might break a lot of other functions by changing the signature of `try_print_query_stack`, turns out it's only being called twice. Will confirm after running tests.

**Comment by Dylan-DPC** [comment]
@georgio any updates on this?

**Comment by hosseind75** [comment]
guys I am working on it and as @oli-obk recommendation, I want to add num_frames argument to try_print_query_stack function to break while loop when loop counter is equal to num_frames, but I am not sure that is it correct or not?
and also I am not sure that we should ask the user to set an environment variable that determines how much of the query stack should we print or just pass a strict value to this function?

**Comment by oli-obk** [comment]
We can just pass a strict value. This only happens when the compiler panics and is just a single line of information. I don't think this is something we really need to make configurable.

**Comment by hosseind75** [comment]
ok thanks, I will pass f.e 2  to just show two first queries

**Comment by GroteGnoom** [comment]
This should be closed because of
https://github.com/rust-lang/rust/pull/77493
