### ISSUE TITLE
regression on span for panics due to track-caller in cross-crate macros

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#70963]
This example has regressed (including on stable by now): ([playground](
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=d5d1dd7fc4b97a199f8501d9cbabcfa0))
```rust
fn main() {
    std::collections::VecDeque::<String>::with_capacity(!0);
}
```
The location reported is now `<::core::macros::panic macros>:3:10` (or on nightly, `src/libcore/macros/mod.rs:34:9`).
(the choice of `VecDeque::with_capacity` is arbitrary, it just happens to have an `assert!` inside, and it will be codegen'd in the user crate because it's generic)

In general, we don't track enough information to recover the invocation site, when we have to codegen the MIR cross-crate.

A cheap hack we could do is replace the macro span with the invocation one, when serializing `Span`s inside MIR (or `Span`s in general?).

_Originally posted by @eddyb in https://github.com/rust-lang/rust/issues/47809#issuecomment-583784847_

**Comment by Centril** [comment]
cc @anp :)

**Comment by eddyb** [comment]
One way to handle replacing macro spans with invocation ones when serializing spans in MIR would be adding another `Span` to `Terminator` (or even just `TerminatorKind::Call`), that will only be used for the `Location` passed to `#[track_caller]` callees.

Probably the easiest way to handle the custom encoding strategy is a `SpanEncodedAsCallSite` newtype that has a specializable `Encodable` impl, so that the cross-crate encoder can hook it.

**Comment by eddyb** [comment]
cc @Aaron1011 as they have been working on a proper implementation of hygiene serialization (which would make the workaround obsolete)

**Comment by anp** [comment]
Aha, I knew I was forgetting to file something that was ongoing. Is there an issue tracking the span hygeine work that’s ongoing?

**Comment by eddyb** [comment]
> Is there an issue tracking the span hygeine work that’s ongoing?

Oh, there is: #68686.

**Comment by eddyb** [comment]
(Let me know if it's inappropriate to use `regression-from-X-to-Y` labels for runtime behavior)

**Comment by spastorino** [comment]
Assigning `P-medium` as [discussed as part of the Prioritization Working Group process](https://rust-lang.zulipchat.com/#narrow/stream/227806-t-compiler.2Fwg-prioritization/topic/I-prioritize.20.2370963.20regression.20on.20span.20for.20panics.20due.20to.20tra) and removing `I-prioritize`.
