### ISSUE TITLE
Unclear compiler error: "local ambiguity: multiple parsing options"

### ISSUE THREAD

**Issue by spease** [rust-lang/rust#70974]
```
    macro_rules! chain_append {
        ($a:expr, $($b:literal .. $c:literal),* $($d:literal),*) => {{
            $a$(.chain($b..$c))*$(.chain(once($d)))*
        }}
    }
```

```
error: local ambiguity: multiple parsing options: built-in NTs literal ('b') or literal ('d').
  --> rasp_event/src/url_encoding.rs:46:35
   |
46 |         chain_append!(b'A'..b'Z', b'a'..b'z', b'0'..b'9', b'-', b'_', b',', b'~');
   |                                   ^^^^
```

I assume the 'b' comes from the prefix, but I don't understand where the 'd' comes in. This is just a hygienic macro.

**Comment by Patryk27** [comment]
This is a place to report bugs in the Rust compiler - since you have a question, please create a thread e.g. [on Reddit](https://www.reddit.com/r/rust/).

**Comment by Centril** [comment]
This is a fine place to ask for improvements to compiler diagnostics. :)

**Comment by Nicholas-Baron** [comment]
So I have been able to trace down this issue to `bb_items` having two items. https://github.com/rust-lang/rust/blob/14a2fd640e0df9ee8cc1e04280b0c3aff93c42da/compiler/rustc_expand/src/mbe/macro_parser.rs#L706

The only other place `bb_items` is modified (I think) is in `inner_parser_loop`: https://github.com/rust-lang/rust/blob/14a2fd640e0df9ee8cc1e04280b0c3aff93c42da/compiler/rustc_expand/src/mbe/macro_parser.rs#L577

So, the parser is detecting two `TokenTree::MetaVarDecl`s. One covers the `$b:literal .. $c:literal` expansion and the other covers the `$d:literal`, explaining where the `b` and `d` in the error message come from.

**Comment by Nicholas-Baron** [comment]
Effectively, `$($b:literal .. $c:literal),* $($d:literal),*` is ambiguous to the current parser, as it seems the `b'a'..b'z'` range is treated as both.
What would be a way to state this in an error message?

**Comment by Nicholas-Baron** [comment]
The phrase `built-in NTs` (built-in nonterminals) is probably not very understandable to most programmers. Could rewriting this as `macro arguments` be more useful?

**Comment by imor** [comment]
I think errors in macros are in general not as helpful as in other areas of the language. The terminology is inconsistent. I have seen `NT`, `binder`, `variable` or `meta-variable` being used in different errors to refer to the same thing. These should probably be changed to use `meta-variable`. Similarly, sometimes context is missing as pointed out by @stephanemagnenat.

**Comment by Nicholas-Baron** [comment]
That seems to be more intelligible to an end user, as it puts the names `b` and `d` in the context of the macro declaration (`$b` and `$d`, respectively).

**Comment by Dylan-DPC** [comment]
This code now compiles so closing this
