### ISSUE TITLE
Bug. Get doubled error message with impl_trait_in_bindings when no error must be

### ISSUE THREAD

**Issue by DustinByfuglien** [rust-lang/rust#70997]
This example compiling with error message. And it's not obvious:
1. what cycle is this message about?
2. why this error is doubled in output?
3. why error is at all? It seems no error must be.

```rust
#![feature(generator_trait)]
#![feature(generators)]
#![allow(incomplete_features)]
#![feature(impl_trait_in_bindings)]

use std::ops::Generator;

fn main() {
    let mut gen: impl Generator =
        || {
            yield;
        };
    std::pin::Pin::new(&mut gen).resume(());
}
```

([Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=5c2d049da830c650e930300fb6ee7591))

Errors:

```
   Compiling playground v0.0.1 (/playground)
error[E0391]: cycle detected when processing `main::{{opaque}}#0`
  --> src/main.rs:9:18
   |
9  |     let mut gen: impl Generator =
   |                  ^^^^^^^^^^^^^^
   |
note: ...which requires type-checking `main`...
  --> src/main.rs:8:1
   |
8  | fn main() {
   | ^^^^^^^^^
   = note: ...which requires evaluating trait selection obligation `impl std::ops::Generator: std::marker::Unpin`...
   = note: ...which again requires processing `main::{{opaque}}#0`, completing the cycle
note: cycle used when checking item types in top-level module
  --> src/main.rs:1:1
   |
1  | / #![feature(generator_trait)]
2  | | #![feature(generators)]
3  | | #![allow(incomplete_features)]
4  | | #![feature(impl_trait_in_bindings)]
...  |
13 | |     std::pin::Pin::new(&mut gen).resume(());
14 | | }
   | |_^

error[E0391]: cycle detected when processing `main::{{opaque}}#0`
  --> src/main.rs:9:18
   |
9  |     let mut gen: impl Generator =
   |                  ^^^^^^^^^^^^^^
   |
note: ...which requires type-checking `main`...
  --> src/main.rs:8:1
   |
8  | fn main() {
   | ^^^^^^^^^
   = note: ...which again requires processing `main::{{opaque}}#0`, completing the cycle
note: cycle used when checking item types in top-level module
  --> src/main.rs:1:1
   |
1  | / #![feature(generator_trait)]
2  | | #![feature(generators)]
3  | | #![allow(incomplete_features)]
4  | | #![feature(impl_trait_in_bindings)]
...  |
13 | |     std::pin::Pin::new(&mut gen).resume(());
14 | | }
   | |_^

error: aborting due to 2 previous errors
```

May be must tracked by #63065

**Comment by DustinByfuglien** [comment]
Compiler generate error when no error must be.
Woud I propose to add a "C-bug" label?

**Comment by eddyb** [comment]
@DustinByfuglien This is not a bug, but the error doesn't tell you how to fix it
This is the important part:
```
evaluating trait selection obligation `impl std::ops::Generator: std::marker::Unpin`
```

You have to write write `impl Generator + Unpin` if you want to use `Pin::new`, otherwise the compiler tries to figure it out on the spot and ends up in a cyclic dependency during type-checking.

**Comment by DustinByfuglien** [comment]
Thank you.
But what difference is with next example that successfully compiles?

```rust
#![feature(generator_trait)]
#![feature(generators)]

use std::ops::Generator;

fn f()-> impl Generator {
    || {
        yield;
    }
}

fn main() {
    std::pin::Pin::new(&mut f()).resume(());
}
```

([Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=c5a4320a0cd48b6778803b2ae0c41f1b))
```

**Comment by eddyb** [comment]
@DustinByfuglien Generators, like closures, have type-checking/inference done at the same time as the parent function. By moving the generator into a separate function, you break the cycle as `f` can be completely type-checked/inferred before `main` finishes type-checking.

**Comment by estebank** [comment]
Triage: the error still emits, but it is no longer duplicated.

**Comment by kpreid** [comment]
This could probably be closed, because the implementation of `impl_trait_in_bindings` was removed by https://github.com/rust-lang/rust/issues/86729.
