### ISSUE TITLE
Insufficient concurrency in the rust-lang-ci organization

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#70995]
Build times in the [rust-lang-ci](https://github.com/rust-lang-ci) organization are way higher than expected, with [the latest successful build](https://github.com/rust-lang-ci/rust/actions/runs/75242092) clocking at 2 hours and 52 minutes of build time.

To investigate the problem I [created a small script](https://gist.github.com/pietroalbini/fe5358cfd3c6d464ad8905dc3eb0b961) that generates a graph of the duration of each job, and the result for the build I linked earlier is the following (click the image to view in full resolution):

![Screenshot_2020-04-10 Screenshot](https://user-images.githubusercontent.com/2299951/79006730-12266280-7b5a-11ea-8f5d-9da70dc490f0.png)

Looking at the graph it seems that our concurrency is limited to 20 builders running at the same time, while it should be at least 60 parallel builders to account for a full auto build and a couple of try builds running at the same time.

**Comment by nagisa** [comment]
Awesome graph!

**Comment by pietroalbini** [comment]
Github enabled the paid subscription in the `rust-lang-ci` organization midway through this build, and that seems to have solved the problem. I'll close the issue when we have a graph with all the jobs starting at the same time.

![Screenshot_2020-04-16 Screenshot](https://user-images.githubusercontent.com/2299951/79498801-2b338580-802a-11ea-8201-017311358409.png)

**Comment by pietroalbini** [comment]
This was indeed fixed!

![Screenshot_2020-04-17 Screenshot](https://user-images.githubusercontent.com/2299951/79564061-3d570780-80ae-11ea-90f6-9e2f776dbdee.png)
