### ISSUE TITLE
Relocation R_X86_64_32S out of range

### ISSUE THREAD

**Issue by 38569459** [rust-lang/rust#70992]
I tried to link some code to large address using custom linker script but it says `'relocation R_X86_64_32S out of range'`

linker script:
```
SECTIONS
{
  . = 0xffff800000000000;
  .text : { *(.text) }
  .data : { *(.data) }
  .bss : { *(.bss) }
}
```
command: `rustc main.rs -C link-arg='--script=link.ld' -C code-model=large`

### Meta

`rustc --version --verbose`:
```
rustc 1.44.0-nightly (1edd389cc 2020-03-23)
```

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by 38569459** [comment]
I figured it out! The core crate i'm linking with is built with different code-model and relocation-model. After re-build them with same code-model and relocation-model, everything works.

**Comment by polyproline** [comment]
> I figured it out! The core crate i'm linking with is built with different code-model and relocation-model. After re-build them with same code-model and relocation-model, everything works.

Can you share about your resolution step?I have the same question with you.

**Comment by 38569459** [comment]
You must use the same code-model and relocation-model when you building your core crate.

**Comment by polyproline** [comment]
> You must use the same code-model and relocation-model when you building your core crate. The step to building core crate with custom target is quite hard and I still not figure it out, I just copy sysroot from some others project.

Thanke you for your response.
I used cargo-xbuild ,set  env RUSTFLAGS to make crates in  the same code-model and relocation-model then build fail with the same question
But when I used .cargo/config.toml ,set build-std and env RUSTFLAGS then it did well
Is cargo-xbuild question? what are you build command?

**Comment by 38569459** [comment]
About the custom core crate, I can't remember anymore since it too long ago. As i said, I use cargo-xbuild to build the core crate for me and I just copy sysroot folder for private use after that.

```
# prepare some build tool and files
rustup component add rust-src
cargo install cargo-xbuild

cp /path/to/your/rust-toolchain .
cp /path/to/your/custom_target_file.json .
cp /path/to/your/placeholder_main.rs src/main.rs

# build the place holder project to get sysroot
cargo xbuild --target custom_target_file
cp -r target/sysroot /whre/do/you/want/to/save/it
```

**Comment by polyproline** [comment]
> About the custom core crate, I can't remember anymore since it too long ago. As i said, I use cargo-xbuild to build the core crate for me and I just copy sysroot folder for private use after that.
> 
> ```
> # prepare some build tool and files
> rustup component add rust-src
> cargo install cargo-xbuild
> 
> cp /path/to/your/rust-toolchain .
> cp /path/to/your/custom_target_file.json .
> cp /path/to/your/placeholder_main.rs src/main.rs
> 
> # build the place holder project to get sysroot
> cargo xbuild --target custom_target_file
> cp -r target/sysroot/  /where/do/you/want/to/save/it
> ```
> 
> After that, use it as follow:
> 
> ```
> rustc main.rs -o main.elf -g --edition 2018 --target custom_target_file --sysroot /where/do/you/want/to/save/it -C link-args='--script=link.ld'
> ```

Thank you

**Comment by 38569459** [comment]
@polyproline, as some note, you should **back up your sysroot folder** if it works because this is just a work around and cargo-xbuild project can change their way of doing thing **anytime** and it may break everything. This happened to me once until I found out what they had changed and find my way to work around that.
