### ISSUE TITLE
Non-intuitive struct initialization syntax

### ISSUE THREAD

**Issue by jerryajay** [rust-lang/rust#71028]
I have some concerns as to the proper initialization of a `struct`:

```
let point = Point { x: 12, y: 45 }
```

The syntax of using `:` doesn't seem natural since in my mind `:` is associated with a return type that follows. A more natural fit would be to use `=` instead of `:`. However, three `=` symbols may end up being used in the above code which may cause some parsing precedence issues.

Give it a thought. Rust should be more natural rather than memorizing few idioms such as the one above.

**Comment by jonas-schievink** [comment]
Hi! Large additions to the language or standard library need to go through our [RFC process](https://github.com/rust-lang/rfcs). Before an RFC is written, the feature can also be discussed in our [internals forum](https://internals.rust-lang.org/) to find other people interested in it.

Closing in favor of an RFC.
