### ISSUE TITLE
`uuid!()` and `iota!()` (and maybe `random!()`) syntax extensions

### ISSUE THREAD

**Issue by graydon** [rust-lang/rust#7104]
`uuid!()` should generate a UUID (http://en.wikipedia.org/wiki/Universally_unique_identifier). It should take arguments (or there should be multiple variants of the call) to indicate the UUID-variant. The default should just be random. Could possibly defer to a `random!()` syntax extension that generates a random value at compile time.

`iota!()` should do something like what the `iota` expression in Go does: http://golang.org/ref/spec#Iota -- evaluate to a constant integer starting from zero and increment the counter, resetting on some reaosnable boundary such as "per module" or "per scope".

(Nominating for feature complete.)

**Comment by brson** [comment]
Old bug, demand has subsided. I don't think there's any value keeping it around.
