### ISSUE TITLE
`cargo` occasionally fails to detect changed source code files

### ISSUE THREAD

**Issue by icy-ux** [rust-lang/rust#71052]
Normally when I run cargo `build`, `test`, etc then any changes I've made to the code are picked up as expected & it re-compiles those parts of the binary.

Occasionally it does not do so, and I need to run `cargo clean`, then recompile to have my changes recognised.

### Meta

`rustc --version --verbose`:
```
$ rustc --version --verbose
rustc 1.42.0 (b8cedc004 2020-03-09)
binary: rustc
commit-hash: b8cedc00407a4c56a3bda1ed605c6fc166655447
commit-date: 2020-03-09
host: x86_64-unknown-linux-gnu
release: 1.42.0
LLVM version: 9.0
```

Checking whether it happens in nightly isn't currently possible as it's an intermittent issue. I will have to remember to check the next time the issue appears.

**Comment by jonas-schievink** [comment]
Cargo issues should be filed over at https://github.com/rust-lang/cargo

**Comment by icy-ux** [comment]
Done: https://github.com/rust-lang/cargo/issues/8100
