### ISSUE TITLE
Cannot use trait with nested associated type bounds as type bound

### ISSUE THREAD

**Issue by Plecra** [rust-lang/rust#71067]
I'm struggling to name this, so sorry if it's a duplicate of another issue.

When a trait's associated type's associated type (ugh) is bound by a trait, it cannot be used as a type bound on its own. Hopefully this example can clarify what I mean:

```rust
trait Trait
where
    <Self::Type as TryFrom<()>>::Error: Debug,
{
    type Type: TryFrom<()>;
    // #52662: TryFrom<(), Error: Debug>;
}
fn f<T: Trait>() {}
//      ^^^^^
// error[E0277]: `<<T as Trait>::Type as std::convert::TryFrom<()>>::Error` doesn't implement `std::fmt::Debug`
```

Instead, you need to repeat the bound on the function:

```rust
fn f<T: Trait>()
where
    <<T as Trait>::Type as TryFrom<()>>::Error: Debug
{}
```

**Comment by jonas-schievink** [comment]
This is a very old issue https://github.com/rust-lang/rust/issues/20671 where only supertrait bounds on traits are "elaborated" to where the subtrait bound is written. Closing in favor of that.
