### ISSUE TITLE
TAIT: Add a test case using `Sized`

### ISSUE THREAD

**Issue by Centril** [rust-lang/rust#71085]
Note to self (or whoever wants to help out); the following should be added as a test case in `src/test/ui/type-alias-impl-trait`:
```rust
// check-pass

#![feature(type_alias_impl_trait)]

type A = impl Sized;
fn f1() -> A { 0 }

type B = impl ?Sized;
fn f2() -> &'static B { &[0] }

type C = impl ?Sized + 'static;
fn f3() -> &'static C { &[0] }

type D = impl ?Sized;
fn f4() -> &'static D { &1 }
```

This issue has been assigned to @samrat via [this comment](https://github.com/rust-lang/rust/issues/71085#issuecomment-612739030).

**Comment by samrat** [comment]
Hi, I would like to work on this.
