### ISSUE TITLE
T: Clone -> Into<T> for &T and From<&T> for T?

### ISSUE THREAD

**Issue by zero-systems** [rust-lang/rust#71084]
I tried:
```rust
let original: u32 = 123;
	
let reference: &u32 = &original;
	
let result: u32 = Into::into(reference);
```

I got:
```
the trait `std::convert::From<&u32>` is not implemented for `u32`
```

Why there is no `Into` or `From` for T/&T?
My code does not make any sense, but it might be useful when you write function with generics like:
```rust
fn make_string_from_iter<C, I>(i: I) -> String
where
    C: Into<char>,
    I: IntoIterator<Item = C>,
{
    /* code */
}
```
Where I want to put `&[char; 5]` as `i`.
Iterator `[char; 5]` returns items as references: `&char` for both .iter() .into_iter().
I don't want to clone my slice into vec, I wanna to process items just in time, inside my function.

I also made simple custom `into` trait:
```rust
trait CustomInto<T> {
	fn into(s: Self) -> T;
}

impl<T: Clone> CustomInto<T> for &T {
	fn into(s: Self) ->	T {
		s.clone()
	}
}
```
and it works as expected. Should not be there next impls in std:
- `impl<T: Clone> Into<T> for &T`
- `impl<T: Clone> From<T: &T> for T`
?

**Comment by zero-systems** [comment]
But I can't reimpl into for custom into:
```rust
impl<R, F: Into<R>> CustomInto<R> for F {
	fn into(s: Self) -> R {
		Into::into(s)
	}
}

impl<T: Clone> CustomInto<T> for &T {
	fn into(s: Self) ->	T {
		s.clone()
	}
}
```

```
error[E0119]: conflicting implementations of trait `CustomInto<_>` for type `&_`:
  --> src/main.rs:16:1
   |
10 | impl<R, F: Into<R>> CustomInto<R> for F {
   | --------------------------------------- first implementation here
...
16 | impl<T: Clone> CustomInto<T> for &T {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ conflicting implementation for `&_`
```

It looks like compiler wanna say there is already impl I want, but I can't find it and still `Into<T> for &T` not works......

**Comment by jonas-schievink** [comment]
The `From` impl would overlap with existing blanket impls like:

`impl<'_, T: ?Sized + AsRef<OsStr>> From<&'_ T> for OsString`

And the `Into` impl overlaps with the `impl<T, U: From<T>> Into<U> for T ` impl.

It's trivial to work around this by just calling `clone()` manually or dereferencing the reference.
