### ISSUE TITLE
Format string parser does not fail on invalid input

### ISSUE THREAD

**Issue by strega-nil** [rust-lang/rust#71088]
This code:

```rust
struct Foo;

impl Display for Foo {
  fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
    write!(f, "{}", f.fill() as u32)
  }
}

fn main() {
  println!("{:\t}", Foo)
}
```

Compiles, and prints `32`. According to the `std::fmt` docs, 

```
[[fill]align][sign]['#']['0'][width]['.' precision][type]
```

is the syntax of format specifications; however, `\t` does not fulfill any of these elements. I assumed that it might accidentally be implementing the syntax

```
[fill][align][sign]['#']['0'][width]['.' precision][type]
```

however, if that were true, then this should print `9` (and not `32`). I haven't looked into the parsing code, but will after filing this issue.

**Comment by sfackler** [comment]
This is just because the fmt parser ignores whitespace I believe: https://github.com/rust-lang/rust/blob/master/src/libfmt_macros/lib.rs#L397-L406.

**Comment by strega-nil** [comment]
It turns out, it's implementing the syntax

```
[[fill]align][sign]['#']['0'][width]['.' precision][type]ws*
```

due to a bug in this commit from 7 years ago: a447c3ca165dda7aa31d2be76ce1ff35a7884579
