### ISSUE TITLE
Provide better compiler output when using `?` on `Option` in fn returning `Result` or vice-versa?

### ISSUE THREAD

**Issue by alvinhochun** [rust-lang/rust#71089]
It seems that `rustc` should provide a better error message or hint when one tries to use the `?` operator on an `Option` in a function returning a `Result` or vice-versa.

Currently this is the error you get:

```
error[E0277]: `?` couldn't convert the error to `MyErrorType`
  --> src/main.rs:10:19
   |
10 |     let a = foo(i)?;
   |                   ^ the trait `std::convert::From<std::option::NoneError>` is not implemented for `MyErrorType`
   |
   = note: the question mark operation (`?`) implicitly performs a conversion on the error value using the `From` trait
   = note: required by `std::convert::From::from`
```

However, it would be better to suggest the use of `Option::ok_or` or `Option::ok_or_else`, or `Result::ok`, instead of referencing something dependent on the `try_trait` feature (`NoneError`).

This issue has been assigned to @Duddino via [this comment](https://github.com/rust-lang/rust/issues/71089#issuecomment-613575965).

**Comment by estebank** [comment]
This error is emitted here:

https://github.com/rust-lang/rust/blob/8e18e26f12b1e8b3e913b15278bf6185f0f61add/src/librustc_trait_selection/traits/error_reporting/mod.rs#L278-L313

We could look at whether the `trait_ref` is `std::convert::From<std::option::NoneError>`, and if so, provide a more targeted error, including a structured suggestion for `ok_or_else`.

**Comment by Duddino** [comment]
Can I claim this issue?
