### ISSUE TITLE
Reuse installed LLVM during rust compilation

### ISSUE THREAD

**Issue by dilyanpalauzov** [rust-lang/rust#71119]
I download https://static.rust-lang.org/dist/rustc-1.42.0-src.tar.gz and then I want to build rustc. Since I have LLVM on my system, I want to use it, rather than compiling a separate LLVM during the rust build process.

I find no documentation describing how to reuse my installed LLVM for rust.

**Comment by jonas-schievink** [comment]
Both `./configure` and `config.toml` document the options you need to set

**Comment by csmoe** [comment]
`./configure --hep`
