### ISSUE TITLE
Trait where clause issue

### ISSUE THREAD

**Issue by fundon** [rust-lang/rust#71115]
### Ok

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a2950badc52ce239a7ee2b0cef3e4747

### Err
No support? 
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=754771285ea43f8e05580d49660cfad2

<img width="731" alt="Screen Shot 2020-04-14 at 15 05 06" src="https://user-images.githubusercontent.com/27926/79198603-51a8c380-7e66-11ea-8af7-6f21e987a3fd.png">

**Comment by csmoe** [comment]
Duplicated of https://github.com/rust-lang/rust/issues/57923
