### ISSUE TITLE
Account for use of `try!()` in 2018 edition and guide users in the right direction

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#71155]
Old documentation and blogposts will never be updated to not talk about the `try` macro. [The current output of the following code](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=3761918397ede5963c3803f3c3e43201)

```rust
fn foo() -> Result<(), ()> {
    Ok(try!(Ok(())))
    
}
```

is

```
error: expected expression, found reserved keyword `try`
 --> src/main.rs:2:8
  |
2 |     Ok(try!(Ok(())))
  |        ^^^ expected expression
```

It should provide structured suggestions to either use `r#try` or `?`:

```
error: use of deprecated `try` macro
 --> src/main.rs:2:8
  |
2 |     Ok(try!(Ok(())))
  |        ^^^^^      ^
  |        |
  |        deprecated `try` macro
  = note: in the 2018 edition `try` is a reserved keyword, and the `try!()` macro is deprecated
help: you can use the `?` operator instead
  |
2 |     Ok(Ok(())?))
  |        --      ^
help: alternatively, you can still access the deprecated `try!()` macro using the "raw identifier" syntax
  |
2 |     Ok(r#try!(Ok(())))
  |        ^^
```

This request is similar in spirit to #67204 and feels like a subset of #65148.

This issue has been assigned to @Duddino via [this comment](https://github.com/rust-lang/rust/issues/71155#issuecomment-614616832).

**Comment by Duddino** [comment]
Would it be fine if I modified https://github.com/rust-lang/rust/blob/master/src/librustc_parse/parser/diagnostics.rs#L1457-1476 and check if the `try` keyword is used, or is there another way to deprecate a macro
