### ISSUE TITLE
Hint about missing trait method suggests incorrect code (self parameter not named "self").

### ISSUE THREAD

**Issue by steffahn** [rust-lang/rust#71150]
In the error message below, the first argument of  `poll` is not named `self`.

```rust
use core::future::Future;

struct S;
impl Future for S {}
```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=8760b4f73c3bc7e383edf62742ccbac5))

Errors:

```
   Compiling playground v0.0.1 (/playground)
error[E0046]: not all trait items implemented, missing: `Output`, `poll`
 --> src/lib.rs:4:1
  |
4 | impl Future for S {}
  | ^^^^^^^^^^^^^^^^^ missing `Output`, `poll` in implementation
  |
  = help: implement the missing item: `type Output = Type;`
  = help: implement the missing item: `fn poll(_: std::pin::Pin<&mut Self>, _: &mut std::task::Context<'_>) -> std::task::Poll<<Self as std::future::Future>::Output> { unimplemented!() }`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0046`.
error: could not compile `playground`.

To learn more, run the command again with --verbose.

```

@rustbot modify labels: T-compiler, A-diagnostics, C-enhancement, D-papercut, F-arbitrary_self_types.

This issue has been assigned to @Duddino via [this comment](https://github.com/rust-lang/rust/issues/71150#issuecomment-614260066).

**Comment by Duddino** [comment]
I managed to fix this particular issue by just manually checking if the argument is of type `std::pin::Pin<&mut Self>`, and if it is it returns `format!("self: {}", ty);` where ty is the type of the argument (in this case std::pin::Pin<&mut Self>). I'm not sure if there is a better way, I'm going to make a PR tomorrow, if anyone has a better solution, please tell me.

**Comment by steffahn** [comment]
I’m not just interested in a fix for this particular case. Types that allow dispatch can be arbitrarily nested AFAIK and also I didn’t tag `F-arbitrary_self_types` for no reason - these can be extended. Furthermore the correct way to fix this is probably _not_ to just add code but rather to change ~existing logic that must be somewhere already, for example some code currently _does_ make `self`, `&self` and `&mut self` parameters print correctly and differently from non-self parameters that have type `Self` or~...... _let me double-check that...._

_Oh, wow, I’ll expand this bug-report._

## Hint about missing trait method suggests incorrect code (_non_-self parameter _mistakenly_ named "self").

Create a binary crate named “my-crate” with:

**main.rs**
```rust
struct S;
impl my_crate::Tr for S {}

fn main() {
    println!("Hello, world!");
}
```

**lib.rs**
```rust
pub trait Tr {
  fn f(self: &Self, not_self: &Self);
}
```

Error message is:
```
error[E0046]: not all trait items implemented, missing: `f`
 --> src\main.rs:2:1
  |
2 | impl my_crate::Tr for S {}
  | ^^^^^^^^^^^^^^^^^^^^^^^ missing `f` in implementation
  |
  = help: implement the missing item: `fn f(&self, &self) { unimplemented!() }`
```

**Comment by Duddino** [comment]
Makes sense as if I recall correctly (can't link files rn as I am on my phone) the code literally just checks if the type is (&/&mut)Self and if it is it prints (&/&mut)self otherwise it prints _: Type. A potential fix could be printing (&/&mut)self only if it's the first type of the function

**Comment by steffahn** [comment]
Won’t be enough. The first parameter of a trait fn could be of type `Self` without being named `self`. It actually needs to check if it’s a `self` parameter. That information should be retrievable _somewhere_ in the compiler. Furthermore then the rest is easy: First step: check if it’s a `self` parameter. If not: use `_ : {ty}`. If it however is on, then check for the type being `Self` or `&Self` or `&mut Self`, printing `self`, `&self` or `&mut self` respectively; otherwise print `self: {ty}`.

**Comment by Duddino** [comment]
Another issue related to this is when you have a function that has a signature of `fn name(whatever: &Self);` The compiler suggests to implement the function using `fn name(&self){ todo!() };`, but that doesn't work
