### ISSUE TITLE
cargo run get "Segmetation fault" on Debian10

### ISSUE THREAD

**Issue by zoujieorg** [rust-lang/rust#71160]
### What needs to be fixed?
1) my operating system is debian10
$ cat /etc/debian_version 
10.3
$ uname -a
Linux i5debain 4.19.0-8-amd64 rust-lang/www.rust-lang.org#1 SMP Debian 4.19.98-1 (2020-01-26) x86_64 GNU/Linux

2) cargo version 
i5debain:projects/issue/something $ cargo --version
cargo 1.42.0 (86334295e 2020-01-31)

3) cargo run get "Segmentaion fault"
i5debain:projects $ mkdir issue
i5debain:projects $ cd issue/
i5debain:projects/issue $ ls
i5debain:projects/issue $ cargo new something
     Created binary (application) `something` package
i5debain:projects/issue $ cd something/
i5debain:projects/issue/something$ cargo run
   Compiling something v0.1.0 (/home/zoujie/projects/issue/something)
    Finished dev [unoptimized + debuginfo] target(s) in 0.20s
     Running `target/debug/something`
**Segmentation fault**

4) rustc works ok
i5debain:projects/issue/something $ rustc src/main.rs 
i5debain:projects/issue/something $ ./main 
Hello, world!

**Comment by XAMPPRocky** [comment]
Thank you for your issue! Since the issue seems to be with rustc/cargo and not the website I've transferred it to `rust-lang/rust`.

**Comment by csmoe** [comment]
Please file an issue to https://github.com/rust-lang/cargo
