### ISSUE TITLE
Support commonly used markdown extensions

### ISSUE THREAD

**Issue by AlexApps99** [rust-lang/rust#71183]
These include:
- [ ] [Task list items](https://github.github.com/gfm/#task-list-items-extension-)
- [x] [Strikethrough](https://github.github.com/gfm/#strikethrough-extension-)
- [x] [Autolinks](https://github.github.com/gfm/#autolinks-extension-)

The reasoning for all of these extensions is that they all have wide use not just in GitHub, but in many applications of Markdown.

**Comment by joshtriplett** [comment]
I'm not sure if automatically creating `http://` links from domain names is a good idea, so if there's an option to disable that specifically I'd suggest it. The rest all seems fine to me.

**Comment by GuillaumeGomez** [comment]
Just like @joshtriplett said for **Autolinks**. I'm also not sure to see the point of the **task list one**. However, adding **strikethrough** would be nice.

**Comment by AlexApps99** [comment]
Tasklist would be useful for things like this:

## Currently implemented:
- [x] Implemented thing
- [x] Some other implemented thing
- [ ] Unimplemented thing
- [ ] Some other unimplemented thing

or possibly in the crate root

## Supported features
- [x] Webhooks
- [x] Websockets
- [ ] Websites
- [ ] Other

**Comment by AlexApps99** [comment]
Another noteworthy extension to implement is this:
[Disallowed Raw HTML](https://github.github.com/gfm/#disallowed-raw-html-extension-)
This would prevent the following tags for safety reasons
- `<title>`
- `<textarea>`
- `<style>`
- `<xmp>`
- `<iframe>`
- `<noembed>`
- `<noframes>`
- `<script>`
- `<plaintext>`

**Comment by jyn514** [comment]
> Autolinks

We decided in https://github.com/rust-lang/rust/issues/77501 not to add this. Instead rustdoc will now suggest to turn raw links into automatic links (`<http://example.com>`).

So I think the only thing left is adding task list parsing.
