### ISSUE TITLE
Potential performance regression from new LTO effort after export changes

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#71248]
Spawned off of https://github.com/rust-lang/rust/pull/71131#issuecomment-614711139

PR #71131 may have injected a performance regression into incremental compilation.  It certainly seemed like it did on the two try runs we did on the PR itself: 
 * https://github.com/rust-lang/rust/pull/71131#issuecomment-613741977
 * https://github.com/rust-lang/rust/pull/71131#issuecomment-614926099

So this issue is to track the investigation of that potential regression. (Namely, to evaluation whether a regression truly happened; assuming it did, then what its underlying causes were, and whether any of the significant sources of regression are avoidable.)

**Comment by pnkfelix** [comment]
Interesting: I instrumented the first case I was interested in ("is valid cap letter" on `regex`, as noted [here](https://github.com/rust-lang/rust/pull/71131#issuecomment-614710702)), and it reports that in all five of the cases where we are now not reusing the Post-LTO build product, it is because the `exports_all_green` boolean is false; the set comparison test that I was worried about isn't even being run!

I'll have to go back and review the original logic about the all-green flags; I will admit that when I transcribed that part of the code, it was more a blind "well surely this matters" kind of reasoning.

**Comment by pnkfelix** [comment]
(My intuition is that we do need the `exports_all_green` computation, and when it is non-green we do need to re-do LTO. After all, the basis of https://github.com/rust-lang/rust/issues/69798#issuecomment-596856956 was that a global symbol in module A was determined to be unused in module B, and thus the global symbol was demoted to a local to A; then a later change to B injected a use of that global symbol, and so the change to the importing module (B) is significant to the compilation of A.

Another, separate question is whether injecting `{ }` (as the "is valid cap letter" patch does) can be made something that doesn't trigger this code to treat changed module as non-green here...)

**Comment by pnkfelix** [comment]
> (My intuition is that we do need the `exports_all_green` computation, and when it is non-green we do need to re-do LTO. After all, the basis of [#69798 (comment)](https://github.com/rust-lang/rust/issues/69798#issuecomment-596856956) was that a global symbol in module A was determined to be unused in module B, and thus the global symbol was demoted to a local to A; then a later change to B injected a use of that global symbol, and so the change to the importing module (B) is significant to the compilation of A.

Having said that, I did prototype taking out `exports_all_green`, and with it gone, the regression test for #69798 still passes...

**Comment by pnkfelix** [comment]
I suppose if the import map actually reflects the true usage of the symbols in the importing module, then in fact it should not be necessary for us to look at `exports_all_green`.

I'm willing to have a go with a PR that removes it and see how things go.

**Comment by Mark-Simulacrum** [comment]
@pnkfelix Now that https://github.com/rust-lang/rust/pull/71267 has landed, I'm going to go ahead and close this but feel free to reopen if you think there's more to track here.

**Comment by fenollp** [comment]
I've opened https://github.com/rust-lang/rust/issues/71850 which seems related.
