### ISSUE TITLE
TcpStream struct required for reading and writing

### ISSUE THREAD

**Issue by remi-blaise** [rust-lang/rust#71253]
Good evening,

The [TcpStream struct](https://doc.rust-lang.org/std/net/struct.TcpStream.html) requires to use the same object for reading and writing. This is a problem as you can't do that:

```rust
use std::net::TcpListener;
use std::io::prelude::*;
use std::io::BufReader;

fn main() {
    let listener = TcpListener::bind("127.0.0.1:8080").unwrap();
    let mut stream = listener.accept().unwrap().0;
    let mut bufferedStream = BufReader::new(&stream);
    let mut line = String::new();

    loop {
        bufferedStream.read_line(&mut line).unwrap();
        print!("Message received: {}", line);
        stream.write_all(b"Hello from server\n").unwrap();
    }
}
```

gives you the error:
```
error[E0502]: cannot borrow `stream` as mutable because it is also borrowed as immutable
  --> bench/sockets/1.rs:14:9
   |
8  |     let mut bufferedStream = BufReader::new(&stream);
   |                                             ------- immutable borrow occurs here
...
12 |         bufferedStream.read_line(&mut line).unwrap();
   |         -------------- immutable borrow later used here
13 |         print!("Message received: {}", line);
14 |         stream.write_all(b"Hello from server\n").unwrap();
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ mutable borrow occurs here
```

I am missing something or is it a bad design of the language/library?

Thank you for your time,

**Comment by jonas-schievink** [comment]
`Read` and `Write` are also implemented for `&TcpStream`.

**Comment by remi-blaise** [comment]
Good evening @jonas-schievink,
I believe you have closed this issue without giving a satisfying answer.

You say "Read and Write are also implemented for &TcpStream", what I am doing in the example, right? 

The problem I am raising is that given I am giving an immutable borrow to a function to read the stream, I can't write in the stream anymore (the language forbids making an mutable borrow while an immutable borrow is still in usage).

**Comment by Mark-Simulacrum** [comment]
You can do e.g. `(&stream).write_all` or so -- the trait `Write` asks for a `&mut self` so the default is to borrow mutably, but you get the same functionality from a `&TcpStream` in this case.

**Comment by remi-blaise** [comment]
@Mark-Simulacrum thank you very much, it is working indeed.
This makes no sense for me, I would never have found it alone. Could you please explain the logic behind this?

**Comment by Mark-Simulacrum** [comment]
I would recommend asking further on users.rust-lang.org or a similar forum, people there are likely better able to explain this sort of thing.

Generally speaking though -- TcpStream is backed by a kernel primitive, which is internally synchronized (i.e., writing to it is thread safe) so there's no need to have exclusive access to the TcpStream struct to write to it.

**Comment by remi-blaise** [comment]
So does it make sense it require a `&mut self` from the beginning? It would allow to write `stream.write_all` directly.
