### ISSUE TITLE
Pretty serious perf regressions in opt benchmarks

### ISSUE THREAD

**Issue by ljedrz** [rust-lang/rust#71261]
It appears that one of the changes today caused [serious regressions](https://perf.rust-lang.org/compare.html?start=2020-04-16&end=8d67f576b56e8fc98a31123e5963f8d00e40611c&stat=instructions%3Au) in some of the opt benches, mostly patched incremental:

```
regex-opt        | avg: 61.3% | min: -0.0% | max: 330.1%
webrender-opt    | avg: 78.2% | min: -0.0% | max: 312.6%
piston-image-opt | avg: 73.3% | min: -0.4% | max: 293.4%
ripgrep-opt      | avg: 31.3% | min: -0.1% | max: 125.3%
```

**Comment by Mark-Simulacrum** [comment]
868b51be...b2c1a606 is the commit range, but I think this is https://github.com/rust-lang/rust/issues/71248? (That at least seems logical to me).

We should have perf results soonish as they populate in...

**Comment by ljedrz** [comment]
Yes, seems to be the same thing; feel free to close this issue once it's confirmed, I seem to have missed the previous one :stuck_out_tongue: .

**Comment by jonas-schievink** [comment]
New commit range: https://github.com/rust-lang/rust/compare/868b51be6f29d5b43d37c5d65bac1482d3a50ad8...318726b301db2a0718d05f166d3d6c578273189c

Updated perf: https://perf.rust-lang.org/compare.html?start=868b51be6f29d5b43d37c5d65bac1482d3a50ad8&end=318726b301db2a0718d05f166d3d6c578273189c&stat=instructions:u

Closing in favor of #71248
