### ISSUE TITLE
Add dyslexic font and option to enable it

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/rust#71266]
It the last [rust survey](https://blog.rust-lang.org/2020/04/17/Rust-survey-2019.html), it appeared that some an issue with the current documentation was for the dyslexic people. We could improve the reading for them by using fonts optimized for dyslexic readers such as:

 * https://www.dyslexiefont.com/en/typeface/
 * https://www.opendyslexic.org/

I think it'd be a nice improvement to allow people to select it if they need it.

What do you think @rust-lang/rustdoc ?

This issue has been assigned to @nmccarty via [this comment](https://github.com/rust-lang/rust/issues/71266#issuecomment-616847249).

**Comment by pyfisch** [comment]
I think including an optimized font for dyslexic readers is a nice gesture but I think readers are better served by setting their preferred font in the browser settings. Rustdoc does not stand out in any way that would warrant adding an additional font while the rest of the websites don't.

On the other hand i would change the maximum line length. [Typographers](https://practicaltypography.com/summary-of-key-rules.html) recommend 45-90 characters or 2-3 times the alphabet for best legibility. But with rustdoc in a maximized window the alphabet fits around 4 times in a line. An additional change might be to increase the font-size slightly.

**Comment by GuillaumeGomez** [comment]
It could be a good start, indeed!

**Comment by nmccarty** [comment]
I think in this case, it makes more sense to have the entire base style be swappable with a dyslexic friendly version, doing a bit more than just swapping the font, instead substantially modifying the CSS to implement all reasonable accessibility guidelines, like line height, paragraph width, and what not. To get started, I'm just working on swapping the font and increasing the font size.

**Comment by GuillaumeGomez** [comment]
After thinking about it for a while and based on this comment:

> I think including an optimized font for dyslexic readers is a nice gesture but I think readers are better served by setting their preferred font in the browser settings. Rustdoc does not stand out in any way that would warrant adding an additional font while the rest of the websites don't.

I think it's indeed better not to handle it ourselves and let users handle it in their browsers directly. Closing it then and thanks for the answers!
