### ISSUE TITLE
internal compiler error: no entry found for key

### ISSUE THREAD

**Issue by dwrensha** [rust-lang/rust#71297]
I'm seeing an internal compiler error on the following input (found by [fuzz-rustc](https://github.com/dwrensha/fuzz-rustc)):

```rust
async fn a(x | s: String) {}
fn main() {}
```

```
$ rustc --edition=2018 main.rs 
error: an or-pattern parameter must be wrapped in parenthesis
 --> main.rs:1:12
  |
1 | async fn a(x | s: String) {}
  |            ^^^^^ help: wrap the pattern in parenthesis: `(x | s)`

error[E0408]: variable `x` is not bound in all patterns
 --> main.rs:1:16
  |
1 | async fn a(x | s: String) {}
  |            -   ^ pattern doesn't bind `x`
  |            |
  |            variable not in all patterns

error[E0408]: variable `s` is not bound in all patterns
 --> main.rs:1:12
  |
1 | async fn a(x | s: String) {}
  |            ^   - variable not in all patterns
  |            |
  |            pattern doesn't bind `s`

thread 'rustc' panicked at 'no entry found for key', src/librustc_mir_build/build/mod.rs:343:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.44.0-nightly (ce93331e2 2020-04-17) running on x86_64-unknown-linux-gnu

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0408`.
```

**Comment by dwrensha** [comment]
Report from cargo-bisect-rustc:

searched nightlies: from nightly-2020-02-10 to nightly-2020-04-18
regressed nightly: nightly-2020-02-16
searched commits: from https://github.com/rust-lang/rust/commit/433aae93e4ef866a1fdfefad136b32ed89acd3e7 to https://github.com/rust-lang/rust/commit/61d9231ff2604a0467987042d9ebf9ff9ea739b5
regressed commit: https://github.com/rust-lang/rust/commit/19288ddfd6b3448c2c221d75610bff722a6582e8

**Comment by jonas-schievink** [comment]
cc @matthewjasper 

Panic happens here:

https://github.com/rust-lang/rust/blob/52fa23add6fb0776b32cc591ac928618391bdf41/src/librustc_mir_build/build/mod.rs#L342-L344

**Comment by estebank** [comment]
I think that or-patterns should be disallowed in arguments to begin with.

**Comment by Mark-Simulacrum** [comment]
@estebank hm, so at least in principle it seems quite reasonable -- e.g., I might want something like `Result<u32, u32>` to be taken as `Ok(x) | Err(x)`, right?

I don't see why we'd want such an arbitrary restriction; can you elaborate?

**Comment by estebank** [comment]
@Mark-Simulacrum you're right, I hadn't thought of the possibility of different enough variants having the same type binding.

**Comment by LeSeulArtichaut** [comment]
Assigning `P-low` [as discussed as part of the Prioritization-WG process](https://rust-lang.zulipchat.com/#narrow/stream/227806-t-compiler.2Fwg-prioritization/topic/I-prioritize.20.2371297.20internal.20compiler.20error.3A.20no.20entry.20found)
