### ISSUE TITLE
abs/trunc do not exist on float primitives in core

### ISSUE THREAD

**Issue by jhpratt** [rust-lang/rust#71305]
I'm trying to get the following code to compile, and was surprised when it didn't.

```rust
#![no_std]

mod private_euclid_float {
    pub trait Sealed: Sized {}
    impl Sealed for f32 {}
    impl Sealed for f64 {}
}

pub trait EuclidFloat_v1_38: private_euclid_float::Sealed {
    fn rem_euclid(self, rhs: Self) -> Self;
    fn div_euclid(self, rhs: Self) -> Self;
}

#[cfg(std)]
impl EuclidFloat_v1_38 for f32 {
    #[must_use = "method returns a new number and does not mutate the original value"]
    #[inline]
    fn rem_euclid(self, rhs: f32) -> f32 {
        let r = self % rhs;
        if r < 0.0 {
            r + rhs.abs()
        } else {
            r
        }
    }

    #[must_use = "method returns a new number and does not mutate the original value"]
    #[inline]
    fn div_euclid(self, rhs: f32) -> f32 {
        let q = (self / rhs).trunc();
        if self % rhs < 0.0 {
            return if rhs > 0.0 { q - 1.0 } else { q + 1.0 };
        }
        q
    }
}
```

Per the documentation, `f32::abs`, `f32::trunc`, `f64::abs`, and `f64::trunc` all _should_ be able to be used in `#![no_std]` environments. They're implemented via intrinsics, so I can't think of any reason they shouldn't be in core.

rustc: (rustc 1.42.0 (b8cedc004 2020-03-09)

**Comment by Mark-Simulacrum** [comment]
This was changed in 18ab16b5104403ef7a55a2d241c566e35c5ae57a -- at least for abs -- and AFAIK, that's intentional. The underlying support in LLVM isn't present on all platforms I believe at least as of that commit (I don't believe this has since changed either).

**Comment by jhpratt** [comment]
Welp, I suppose it was worth asking! Hopefully this serves as a signpost if someone else runs across this.

Thanks for the quick reply!
