### ISSUE TITLE
When remove the 5 character limit keywords ?

### ISSUE THREAD

**Issue by benjamin-yin001** [rust-lang/rust#71313]
When I first time try rust, I was very angry with these keywords: fn, i8 i16 i32...
Rust is not assembly programming language. A little  long keyword can give more readable semantics.

Why not use Golang-like keywords: func int8 int16 int32... ?

**Comment by memoryruins** [comment]
Those examples are mostly types, and many type names are not as succinct. There is no 5 character limit on [keywords](https://doc.rust-lang.org/stable/reference/keywords.html). It can definitely take time to adjust to different naming between languages! If you would like help while learning, https://users.rust-lang.org/ is a better place to ask.
