### ISSUE TITLE
Implement `From<Cow<'a, B>> for Cow<'static, B>`

### ISSUE THREAD

**Issue by Luro02** [rust-lang/rust#71320]
[`std::borrow::Cow`](https://doc.rust-lang.org/std/borrow/enum.Cow.html) should provide a `From<Cow<'a, B>> for Cow<'static, B>` implementation.

Which could be used to make types independent of lifetimes:

```rust
use std::borrow::Cow;

#[derive(Debug)]
pub struct Uri<'a>(pub Cow<'a, str>);

pub fn create_uri<'a>(input: &'a str) -> Uri<'a> { Uri(Cow::Borrowed(input)) }

fn main() {
    let uri = {
        let base = String::from("https://www.example.com/");

        create_uri(base.as_str())
    }; // errors, because `base` does not live long enough
    
    dbg!(uri);
}
```

this would error with

```
error[E0597]: `base` does not live long enough
  --> src/main.rs:49:20
   |
46 |     let uri = {
   |         --- borrow later stored here
...
49 |         create_uri(base.as_str())
   |                    ^^^^ borrowed value does not live long enough
50 |     };
   |     - `base` dropped here while still borrowed

error: aborting due to previous error
```

In the above case, one could move the `base` variable out of the block, but this is not always possible or desired.

It would be useful if one could do this:

```rust
fn main() {
    let uri = {
        let base = String::from("https://www.example.com/");

        create_uri(base.as_str()).into_owned()
    }; // compiles, because the returned type is Uri<'static>

    dbg!(uri);
}
```

This is another example of how this can be useful:

```rust
use std::borrow::Cow;

#[derive(Debug)]
pub struct Uri<'a>(pub Cow<'a, str>);

impl<'a> Uri<'a> {
    pub fn into_owned(self) -> Uri<'static> {
        Uri(Cow::from_custom(self.0))
    }
}

#[derive(Debug)]
pub struct Request {
    uri: Uri<'static>,
}

impl Request {
    pub fn with_uri<'a>(uri: Uri<'a>) -> Self {
        Self {
            uri: uri.into_owned(),
        }
    }

    pub fn with_uri_2(uri: Uri<'static>) -> Self {
        Self { uri }
    }
}

pub fn create_uri<'a>(input: &'a str) -> Uri<'a> {
    Uri(Cow::Borrowed(input))
}

fn main() {
    let base = String::from("https://www.example.com/");
    let uri = create_uri(base.as_str());

    // let request = Request::with_uri(uri); // works as expected
    let request = Request::with_uri_2(uri); // fails to compile

    dbg!(request);
}
```

----

The implementation looks like this

```rust
impl<'a, B: ?Sized + ToOwned> From<Cow<'a, B>> for Cow<'static, B> {
    fn from(value: Cow<'a, B>) -> Self {
        match value {
            Cow::Borrowed(b) => Cow::Owned(b.to_owned()),
            Cow::Owned(o) => Cow::Owned(o),
        }
    }
}
```

[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&code=use%20std%3A%3Aborrow%3A%3ACow%3B%0A%0A%0Apub%20trait%20From%3CT%3E%20%7B%0A%20%20%20%20fn%20from_custom(_%3A%20T)%20-%3E%20Self%3B%0A%7D%0A%0Aimpl%3C'a%2C%20B%3A%20%3FSized%20%2B%20ToOwned%3E%20From%3CCow%3C'a%2C%20B%3E%3E%20for%20Cow%3C'static%2C%20B%3E%20%7B%0A%20%20%20%20fn%20from_custom(value%3A%20Cow%3C'a%2C%20B%3E)%20-%3E%20Self%20%7B%0A%20%20%20%20%20%20%20%20match%20value%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20Cow%3A%3ABorrowed(b)%20%3D%3E%20Cow%3A%3AOwned(b.to_owned())%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20Cow%3A%3AOwned(o)%20%3D%3E%20Cow%3A%3AOwned(o)%2C%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%7D%0A%0A%23%5Bderive(Debug)%5D%0Apub%20struct%20Example%3C'a%3E%20%7B%0A%20%20%20%20pub%20field%3A%20Cow%3C'a%2C%20str%3E%2C%0A%7D%0A%0Aimpl%3C'a%3E%20Example%3C'a%3E%20%7B%0A%20%20%20%20pub%20fn%20into_owned(self)%20-%3E%20Example%3C'static%3E%20%7B%0A%20%20%20%20%20%20%20%20Example%20%7B%20field%3A%20Cow%3A%3Afrom_custom(self.field)%20%7D%0A%20%20%20%20%7D%0A%7D%0A%0Afn%20main()%20%7B%0A%20%20%20%20let%20example%20%3D%20Example%20%7B%20field%3A%20%22hello%22.into()%20%7D%3B%0A%0A%20%20%20%20dbg!(example.into_owned())%3B%0A%7D)

**Comment by jonas-schievink** [comment]
It cannot provide this implementation as it overlaps with the `From<T> for T` impl
