### ISSUE TITLE
Formatting of strings with ANSI escape sequences

### ISSUE THREAD

**Issue by guigui64** [rust-lang/rust#71335]
The formatting of strings containing ANSI escape sequences does not behave as expected when specifying a fill/alignment width parameter:

```rust
fn main() {
    let normal = "spam eggs";
    let ansi = "spam \x1b[31meggs\x1b[0m";
    println!("|{:>11}|", normal);
    println!("|{:>11}|", ansi);
}
```
Will print:
```text
|  spam eggs|        # all in black
|spam eggs|          # eggs in red
```

I expected the second line to match the first one only with the colors difference.

### Meta

`rustc --version --verbose`:
```
rustc 1.42.0 (b8cedc004 2020-03-09)
binary: rustc
commit-hash: b8cedc00407a4c56a3bda1ed605c6fc166655447
commit-date: 2020-03-09
host: x86_64-unknown-linux-gnu
release: 1.42.0
LLVM version: 9.0
```

**Comment by sfackler** [comment]
The standard library has no knowledge if the thing that eventually displays a string has a special understanding of particular sequences of characters. `\x1b[31` has a width of 4 as far as it knows.
