### ISSUE TITLE
proc_macro does not have a constructor for byte literals

### ISSUE THREAD

**Issue by CAD97** [rust-lang/rust#71358]
We have `Literal::string(&str)` for string literals, `Literal::character(char)` for character literals, and `Literal::byte_string(&[u8])` for byte string literals, but no `Literal::byte_character(u8)` for byte literals.

**Comment by wycats** [comment]
This seems important. Is there something we're missing?

**Comment by wycats** [comment]
@CAD97's comments notwithstanding, I still don't get why this constructor is missing.

**Comment by Emilgardis** [comment]
This has been added as `Literal::byte_character` behind `#![feature(proc_macro_byte_character)]`, tracked in https://github.com/rust-lang/rust/issues/115268
