### ISSUE TITLE
Tracking Issue for `RefCell::take`

### ISSUE THREAD

**Issue by ThinkChaos** [rust-lang/rust#71395]
This is a tracking issue for `#![feature(refcell_take)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also uses as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Implemented in #71398
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr

**Comment by jonas-schievink** [comment]
@ThinkChaos when was this implemented?

**Comment by ThinkChaos** [comment]
@jonas-schievink I'm currently preparing the PR, I needed an issue number for the unstable attribute.

**Comment by jonas-schievink** [comment]
Ah, okay. Normally tracking issues are opened after the PR has a :+1: from the reviewer.

**Comment by ThinkChaos** [comment]
I asked on discord and was told this was ok, I'll know for next time, thanks.

**Comment by jonas-schievink** [comment]
It's okay, I was just missing context

**Comment by KodrAus** [comment]
If anybody would like to open a stabilization PR for this we can kick off a FCP!

**Comment by naiveai** [comment]
Think this issue should probably be closed, since it's now been stabilized!
