### ISSUE TITLE
`unsized_locals` fails to uphold alignment requirements

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#71416]
This is a variant of https://github.com/rust-lang/rust/issues/68304 that was not fixed by https://github.com/rust-lang/rust/pull/71170:
```rust
#![feature(unsized_locals)]

use std::any::Any;

#[repr(align(256))]
#[allow(dead_code)]
struct A {
    v: u8
}

impl A {
    fn f(&self) -> *const A {
        assert_eq!(self as *const A as usize % 256, 0);
        self
    }
}

fn mk() -> Box<dyn Any> {
    Box::new(A { v: 4 })
}

fn main() {
    let x = *mk();
    let dwncst = x.downcast_ref::<A>().unwrap();
    let addr = dwncst.f();
    assert_eq!(addr as usize % 256, 0);
}
```
still fails with 
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `176`,
 right: `0`', align.rs:13:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by RalfJung** [comment]
Given that libcore and liballoc enable this feature, I am rather concerned they could inadvertently use it in a way that is still unsound. Also, unless we can fix this, the feature should probably be added to `INCOMPLETE_FEATURES` to warn people against using it.

**Comment by RalfJung** [comment]
> I am rather concerned they could inadvertently use it in a way that is still unsound.

rustc bootstraps successfully with https://github.com/rust-lang/rust/pull/71417 applied, so at least right now that does not seem to be the case (modulo the part of libstd that rustc never monomorphizes). Of course, that could change any time, there is no check for this.

**Comment by nikomatsakis** [comment]
Yes, thanks for opening this. To be specific, the issue here is centered on this line:

```rust
    let x = *mk();
```

and the fact that we have `x: dyn Any`, and LLVM alloca's don't respect the alignment requirements, right?

I think there may be a separate issue on that. (Link?)

But: one thing we had discussed was separating out the "sound" part and the "unsound" part into distinct feature gates, so that we can enable only the former in libstd. Perhaps that's a good focus for *this* issue?

**Comment by nikomatsakis** [comment]
cc @eddyb, who had discussed the separate feature gate, and @spastorino, who might be interested in doing the follow-up work to create that gate.

**Comment by RalfJung** [comment]
> and the fact that we have x: dyn Any, and LLVM alloca's don't respect the alignment requirements, right?

Yes.

> I think there may be a separate issue on that. (Link?)

Oh, I didn't know that. Let's see if someone finds it.^^

> But: one thing we had discussed was separating out the "sound" part and the "unsound" part into distinct feature gates, so that we can enable only the former in libstd. Perhaps that's a good focus for this issue?

Unlike the other unsound features, this is one where we don't even have a plan for how to soundly implement it. Not sure how much I like keeping that around.

**Comment by nikomatsakis** [comment]
Yes, I see that argument. 

I'm reminded of https://github.com/rust-lang/rust/pull/70193, which limits the max alignment to 4K because of limits in dynamic linkers, though there's no real connection. It's just that part of the challenge here is that the alignment of a `dyn Value` is totally unknown -- it's not like we can conservatively align to 64 bytes or something.

**Comment by RalfJung** [comment]
If https://github.com/rust-lang/rust/pull/70193 lands we could conservatively align to 4k here. :rofl: (no I am not serious)

**Comment by spastorino** [comment]
Assigning `P-high` as [discussed as part of the Prioritization Working Group process](https://rust-lang.zulipchat.com/#narrow/stream/227806-t-compiler.2Fwg-prioritization/topic/I-prioritize.20.2371416.20.60unsized_locals.60.20fails.20to.20uphold.20alignme), removing `I-prioritize` and nominating for discussion on our next weekly meeting.

**Comment by eddyb** [comment]
> Unlike the other unsound features, this is one where we don't even have a plan for how to soundly implement it. Not sure how much I like keeping that around.

Can't we do something dynamic where we allocate `size + (align - 1)` and align it ourselves?
Also, this has been discussed before, hasn't it?

**Comment by nagisa** [comment]
With `Box<dyn FnOnce()>` being stable, this can be observed in stable compiler: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=d6f0aa4af7af2fa82670dcf0958b5199

**Comment by RalfJung** [comment]
> Also, this has been discussed before, hasn't it?

I don't know -- in https://github.com/rust-lang/rust/issues/68304 we mostly talked about how to mitigate the effect on stable Rust.

> Can't we do something dynamic where we allocate size + (align - 1) and align it ourselves?

D'oh, I somehow forgot that one can manually implement "aligned" allocation on top of an unaligned allocator. Of course that would work. That's probably better than killing this part of codegen entirely.^^

**Comment by spastorino** [comment]
[We've discussed this in our last weekly meeting](https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/weekly.20meeting.202020-04-23.20.2354818/near/195068710), leaving the nomination up for now as requested by @pnkfelix. He wants to open some fresh issues about this.

**Comment by pnkfelix** [comment]
Now that I've created more specific issues to track the important sub-tasks identified here, I think we can remove this from the nominated tickets.

**Comment by jackh726** [comment]
Given that this feature has been removed from core/alloc and is unstable, I'm going to downgrade this to P-medium. This should obviously block stabilization of `unsized_locals`, but doesn't need special attention outside of that.
