### ISSUE TITLE
Tracking issue for proc_macro::is_available()

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust#71436]
This is a tracking issue for `proc_macro::is_available()`.
The feature gate for the issue is `#![feature(proc_macro_is_available)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also uses as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Implement -- https://github.com/rust-lang/rust/pull/71400
- [x] Adjust documentation
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide]) -- https://github.com/rust-lang/rust/pull/89735

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr

### Unresolved Questions

none yet

### Implementation history

- Implemented in https://github.com/rust-lang/rust/pull/71400

**Comment by Aaron1011** [comment]
Is anything blocking stabilization of this feature? It seems pretty uncontroversial - if the `proc_macro` crate ever gained the ability to be used outside of a procedural macro, this function could just unconditionally return `true`.

**Comment by dtolnay** [comment]
One non-uncontroversial part is how to react if proc_macro might not be all-or-nothing in the future. For example if the whole token API is made to work outside a proc macro, but the diagnostics API via Span would not be available.

**Comment by jhpratt** [comment]
Wouldn't this feature be covered by `cfg!(accessible(::proc_macro))`? If not, why?

**Comment by bjorn3** [comment]
If the token api is made to work outside a proc macro, but the diagnostics api is not, I think users of proc_macro can just access the token api without checking `is_available` and maybe only check the rustc version. Usage of the diagnostics api should then still be behind a `is_available` check. Basically if it always works, `is_available` shouldn't be used, but if it only works inside a proc macro, `is_available` should be used.

**Comment by bjorn3** [comment]
I would really like for this feature to be stabilized. proc_macro2 is currently unusable with cg_clif outside of proc macros, as it checks if a proc macro function panics when being called. cg_clif doesn't yet support unwinding on panics. Also if the function proc_macro2 checks becomes available outside of a proc macro, that will break proc_macro2 usage outside of proc macros, so the sooner it migrates to `is_available` the better.

**Comment by smklein** [comment]
> I would really like for this feature to be stabilized. proc_macro2 is currently unusable with cg_clif outside of proc macros, as it checks if a proc macro function panics when being called. cg_clif doesn't yet support unwinding on panics. Also if the function proc_macro2 checks becomes available outside of a proc macro, that will break proc_macro2 usage outside of proc macros, so the sooner it migrates to `is_available` the better.

Does the workaround described [here](https://github.com/alexcrichton/proc-macro2/issues/218#issuecomment-622599064) not work for you? I'm running into a similar use-case, but the `force()` function is a sufficient escape-hatch for now

**Comment by bjorn3** [comment]
That doesn't help when you don't control the source. proc-macro2 is used by a dependency of the user's project most of the time. And even if it isn't, I can't except users of cg_clif to always add `proc_macro2::fallback::force()` to their build scripts. I would like something that works out of the box.

**Comment by m-ou-se** [comment]
@rfcbot merge

**Comment by m-ou-se** [comment]
Uhh, I didn't realize three different teams were tagged on this. ^^'

**Comment by m-ou-se** [comment]
@rfcbot cancel

**Comment by m-ou-se** [comment]
@rfcbot merge

**Comment by jhpratt** [comment]
I still share the concern that some APIs may, in the future, be permitted to be used in any context, not just proc macros. Wouldn't `#[cfg(accessible(...))]` encompass this and at the same time be more powerful, flexible, and forward-thinking?

**Comment by bjorn3** [comment]
`#[cfg(accessible(...))]` only tests if the api exists at all in the current rustc version. It doesn't test if you can actually call it.

**Comment by cozyguy** [comment]
use of unstable library feature 'proc_macro_is_available' in nightly-2021-09-14
How can I do to fix it?

**Comment by bjorn3** [comment]
You should update proc-macro2 (if you depend on it) and update to the latest rustc version.
