### ISSUE TITLE
Compiler errors with `associated_type_bounds`

### ISSUE THREAD

**Issue by Plecra** [rust-lang/rust#71443]
A couple minimal examples that cause the compiler to panic when using `associated_type_bounds`

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=b710f545c85c97f070bb6a907d265da1
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=c4f697b2946691a3173aae09399dcc3c

I gotta run, so I can't go into further depth right now. These should probably be split into separate tracking issues

**Comment by JohnTitor** [comment]
Triage: Both examples are no longer ICE with the latest nightly, marking as E-needs-test.
