### ISSUE TITLE
Set `--cfg bootstrap` for `rustdoc` when building docs with bootstrap compiler

### ISSUE THREAD

**Issue by ecstatic-morse** [rust-lang/rust#71455]
Currently, `./x.py doc --stage 0 src/libstd` fails after running into some `#[cfg(not(bootstrap))]` stuff.

I had to do this manually via `RUSTDOCFLAGS`, but I think this should be the default, no?

**Comment by Mark-Simulacrum** [comment]
Yeah, this seems reasonable. I suspect this is just another thing where "stage 0" for most things isn't really natively supported due to lack of testing (in CI, locally, etc.).
