### ISSUE TITLE
Can't install mingw/gcc Rust toolchain on Windows 10

### ISSUE THREAD

**Issue by InnocentusLime** [rust-lang/rust#71460]
Hello!
When I try to install or update mingw/gcc toolchain on Windows 10, it seems like something wrong is going on:
1. After downloading all files `rustup` suddenly says `rolling back changes`
2. He then tries to rename some files which look like backup ones, but fails after 22 attempts

Here is some information about my setup:
* Windows 10
* User folder's name contains non-ascii chars in its name

**Comment by jonas-schievink** [comment]
This should be filed in the rustup repository at https://github.com/rust-lang/rustup

Please include the output of rustup, otherwise it will be hard to understand what's going on.
