### ISSUE TITLE
The primitive type `!` is missing from core::primitive module.

### ISSUE THREAD

**Issue by crlf0710** [rust-lang/rust#71501]
According to reference never type is also primitive, so maybe it makes sense that a reexport be added to the core::primitive module? 

By the way, it seems `pub use !;` in code doesn't work today. Should we fix it as an exception to the rule? Or use something like `pub type never = !` instead?

**Comment by petrochenkov** [comment]
`core::primitive` is only for types with names that can be shadowed, as its documentation says.
`!` is not an identifier and cannot be shadowed, so it doesn't need an entry in `core::primitive`.

**Comment by crlf0710** [comment]
Oh I was reading that as "This module reexports the primitive types" to "allow usage that is not possibly shadowed by other declared types."

By the way, just realized that [std docs](https://doc.rust-lang.org/nightly/std/#primitives) puts `array`,  `pointer`, `reference`, `slice`, `tuple` and `unit` under primitive types list.  This is very different from the [reference](https://doc.rust-lang.org/nightly/reference/types.html) ...

**Comment by Mark-Simulacrum** [comment]
Closing as this is won't fix I believe.
