### ISSUE TITLE
request adding utmpx symvols to libc crate

### ISSUE THREAD

**Issue by sever2806** [rust-lang/rust#71543]
Cabulertion.
I had troubles for compiling some software on musl which using utmpx symvol on x86_64-unknown-linux-musl.
So you can add support for them in libc crate if skarnet-libutmps present in system.

**Comment by lzutao** [comment]
You may want to ask for this in https://github.com/rust-lang/libc/ repo.

**Comment by jonas-schievink** [comment]
Yes, this belongs in https://github.com/rust-lang/libc/
