### ISSUE TITLE
Unsoundness due to variance of trait objects WRT associated types

### ISSUE THREAD

**Issue by trha** [rust-lang/rust#71550]
IIUC currently a trait object is always covariant in its associated types, regardless of their positions.

```rust
trait Foo {
  type A;
  // `A` appears in contravariant position
  fn foo(&self, _: Self::A) {}
}

impl Foo for () {
  type A = &'static ();
}

fn bar<'a>(_: &'a dyn Foo<A = &'a ()>) {}

fn main() {
  let x = ();
  // Let 'x be the lifetime of `&x`
  // 'static <: 'x
  // `dyn Foo` covariant to `Foo::A`
  // `&dyn Foo<A = &'static ()>` <: `&dyn Foo<A = &'x ()>`
  bar(&x);
}
```

This makes it possible to pass a non-static reference to a function expecting a static reference:

```rust
use std::marker::PhantomData;

trait Foo {
    type A;
    type B;
    fn foo(&self, x: Self::A) -> Self::B;
}

struct Bar<T>(PhantomData<T>);

impl<T: 'static> Foo for Bar<T> {
    type A = &'static T;
    type B = &'static T;
    fn foo(&self, x: Self::A) -> Self::B {
        x
    }
}

fn bad<'a, T>(x: &dyn Foo<A = &'a T, B = &'static T>, k: &'a T) -> &'static T {
    x.foo(k)
}

/// Extends the lifetime of an arbitrary reference.
fn extend<'a, T>(x: &'a T) -> &'static T {
    bad(&Bar(PhantomData), x)
}

fn dangle_ref() -> &'static String {
    let x = "hello world".to_string();
    extend(&x)
}

fn main() {
    // This segfaults.
    println!("{}", dangle_ref());
}
```

**Comment by memoryruins** [comment]
Small edit needed:
```diff
-  fn foo(&self, _: Self::A) -> Self::B {
+  fn foo(&self, x: Self::A) -> Self::B {
```
With rustc 1.0.0 ..= 1.16.0, the following error was emitted:
```
error[E0495]: cannot infer an appropriate lifetime for lifetime parameter 'a in function call due to conflicting requirements
  --> <source>:25:5
   |
25 |     bad(&Bar(PhantomData), x)
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^
   |
note: first, the lifetime cannot outlive the lifetime 'a as defined on the body at 24:45...
  --> <source>:24:46
   |
24 |   pub fn extend<'a, T>(x: &'a T) -> &'static T {
   |  ______________________________________________^ starting here...
25 | |     bad(&Bar(PhantomData), x)
26 | | }
   | |_^ ...ending here
note: ...so that reference does not outlive borrowed content
  --> <source>:25:28
   |
25 |     bad(&Bar(PhantomData), x)
   |                            ^
   = note: but, the lifetime must be valid for the static lifetime...
note: ...so that types are compatible (expected &'static T, found &T)
  --> <source>:25:9
   |
25 |     bad(&Bar(PhantomData), x)
   |         ^^^^^^^^^^^^^^^^^

error: aborting due to previous error

Compiler returned: 101
```

**Comment by Mark-Simulacrum** [comment]
@nikomatsakis -- this looks plausibly similar to https://github.com/rust-lang/rust/issues/44454, but I don't know enough to be certain.

**Comment by RalfJung** [comment]
Oh wow how are these not invariant? Cc @eddyb

**Comment by spastorino** [comment]
Assigning `P-high` as [discussed as part of the Prioritization Working Group process](https://rust-lang.zulipchat.com/#narrow/stream/227806-t-compiler.2Fwg-prioritization/topic/I-prioritize.20.2371550.20Unsoundness.20due.20to.20variance.20of.20trait.20obj) and removing `I-prioritize`.

**Comment by spastorino** [comment]
Just in case, in my last action I've removed `I-nominated` by accident and added it back :).

**Comment by nikomatsakis** [comment]
Wait, these are supposed to be invariant. This is definitely a bug. It would be great to figure out just which nightly regressed this, maybe somebody can run cargo bisect?

@rustbot cleanup

**Comment by nikomatsakis** [comment]
Er, I guess I meant this?

@rustbot ping cleanup

**Comment by hellow554** [comment]
searched toolchains nightly-2016-06-01 through nightly-2020-01-01
regression in nightly-2017-03-12

e4eb964dd...824c9ebbd

Previous error message:
```
error[E0495]: cannot infer an appropriate lifetime for lifetime parameter 'a in function call due to conflicting requirements
  --> src/main.rs:25:5
   |
25 |     bad(&Bar(PhantomData), x)
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^
   |
note: first, the lifetime cannot outlive the lifetime 'a as defined on the body at 24:41...
  --> src/main.rs:24:42
   |
24 |   fn extend<'a, T>(x: &'a T) -> &'static T {
   |  __________________________________________^ starting here...
25 | |     bad(&Bar(PhantomData), x)
26 | | }
   | |_^ ...ending here
note: ...so that reference does not outlive borrowed content
  --> src/main.rs:25:28
   |
25 |     bad(&Bar(PhantomData), x)
   |                            ^
   = note: but, the lifetime must be valid for the static lifetime...
note: ...so that types are compatible (expected &'static T, found &T)
  --> src/main.rs:25:9
   |
25 |     bad(&Bar(PhantomData), x)
   |         ^^^^^^^^^^^^^^^^^

error: aborting due to previous error
```

I used a slightly modified variant:

<details>

<summary>Code used</summary>

```
use std::marker::PhantomData;

trait Foo {
    type A;
    type B;
    fn foo(&self, x: Self::A) -> Self::B;
}

struct Bar<T>(PhantomData<T>);

impl<T: 'static> Foo for Bar<T> {
    type A = &'static T;
    type B = &'static T;
    fn foo(&self, x: Self::A) -> Self::B {
        x
    }
}

fn bad<'a, T>(x: &Foo<A = &'a T, B = &'static T>, k: &'a T) -> &'static T {
    x.foo(k)
}

/// Extends the lifetime of an arbitrary reference.
fn extend<'a, T>(x: &'a T) -> &'static T {
    bad(&Bar(PhantomData), x)
}

fn dangle_ref() -> &'static String {
    let x = "hello world".to_string();
    extend(&x)
}

fn main() {
    // This segfaults.
    println!("{}", dangle_ref());
}

```

</details>

**Comment by varkor** [comment]
Most likely candidate seems to be https://github.com/rust-lang/rust/pull/40319, cc @eddyb.

**Comment by nikomatsakis** [comment]
Thanks! Super useful.

**Comment by spastorino** [comment]
After discussing a bit with @nikomatsakis this sounds more like `P-critical` than `P-high`.

**Comment by nikomatsakis** [comment]
Crater run from the fix [suggested 16 non-spurious regressions](https://github.com/rust-lang/rust/pull/71896#issuecomment-626287453) (thanks to @bjorn3 for the analysis). 

I was thinking about that and I realize that it's *plausible* that we could do variance inference on associated types and use that to inform the variance for `dyn` types. It is sensible, for example, that a `dyn Iterator<Item = X>` is covariant with respect to `X` (that is the trait used in one of the affected examples). 

I'm a bit nervous about this though. For one thing, the core operations exposed by a `dyn` type are clearly just its methods, but people can also project out from `dyn` types (though that projection is generally considered invariant over the input types). But for another, it seems to give rise to some asymmetry and complexity around traits and variance that we have thus far avoided (and which I might prefer to continue to avoid).
