### ISSUE TITLE
Long time compiling static array

### ISSUE THREAD

**Issue by CrazyRoka** [rust-lang/rust#71560]
It's very common to use static arrays in C/C++ when doing Competitive Programming like so:
```C++
const int SIZE = 1e4 + 10;
const int STATES = 1e3 + 10;
int dp[SIZE][STATES];
```
I tried the same technique in Rust to save some time at runtime, but there was a problem. Program became compiling too long. From 1-2 seconds using vectors to 30-60 seconds using static memory. Even judge server returned `Compilation timeout` error. Here is same code in Rust:

```Rust
const SIZE: usize = 10010;
const STATES: usize = 1010;
static mut dp: [[bool; STATES]; SIZE] = [[false; STATES]; SIZE];
```
Replacing this code with:
```Rust
let mut dp: Vec<Vec<bool>> = vec![vec![false; STATES]; SIZE];
```
now it compiles 1-2 seconds.

**Comment by leonardo-m** [comment]
For me your code compiles in less than 3.4 seconds. But it's still slow to compile.

On Nightly you have another intermediate option that regains some of the advantages of the arrays (here there's only one heap allocation, and if you pass this matrix to functions you can fully qualify its sides statically):

```
#![feature(box_syntax)]
fn main() {
    const SIZE: usize = 10_010;
    const STATES: usize = 1_010;
    let mut dp = box [[false; STATES]; SIZE];
}
```

**Comment by RalfJung** [comment]
Cc @rust-lang/wg-const-eval looks like a const-eval slowness for big arrays

**Comment by oli-obk** [comment]
@CrazyRoka and @leonardo-m what rust versions are you both on? I remember we fixed some perf thing around arrays a few months ago. But there's still loads of room for improvement. Using a `bool` as the element may be the problem here, as creating that huge array is fairly cheap, but then checking that the constant contains no invalid values (like a `3` in memory where a boolean can only take a `0` or a `1`) that takes quite some time. You can check this by using an integer type instead of a `bool`, because integer types have no invalid values, the checking is skipped.

**Comment by leonardo-m** [comment]
I was using the Nightly of that day, so it's at worst few days old.

**Comment by mati865** [comment]
Both current stable and nightly take less than 3 seconds to build for me, 1.42.0 takes much longer (killed it after 15 seconds).
Can be closed as fixed.

**Comment by CrazyRoka** [comment]
I was using stable 1.42 that time.

**Comment by leonardo-m** [comment]
If you take a look at my message above, I've written it took me about 3.4 seconds to compile it.

**Comment by oli-obk** [comment]
Looks like this is fixed on the latest stable, so closing as I don't think we have anything specific to address here. Please don't hesitate to open more issues if you have examples that are slow on the latest stable (We just released one, so I realize at the time that you were using the latest.)
