### ISSUE TITLE
Suboptimal hint about converting numeric types: Suggests `try_into().unwrap()` when `into()` is possible.

### ISSUE THREAD

**Issue by steffahn** [rust-lang/rust#71580]
```rust
fn main() {
    let a = 1u8;
    let _: i64 = a;
}
```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=45961bca32186db6d4918d8c610315e9))

Errors:

```
   Compiling playground v0.0.1 (/playground)
error[E0308]: mismatched types
 --> src/main.rs:3:18
  |
3 |     let _: i64 = a;
  |            ---   ^ expected `i64`, found `u8`
  |            |
  |            expected due to this
  |
help: you can convert an `u8` to `i64` and panic if the converted value wouldn't fit
  |
3 |     let _: i64 = a.try_into().unwrap();
  |                  ^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
error: could not compile `playground`.

To learn more, run the command again with --verbose.

```

I would’ve expected something like: 
```
help: you can convert an `u8` to `i64`
  |
3 |     let _: i64 = a.into();
  |                  ^^^^^^^^
```
_Edit:_ What actually should happen is the same as currently already with `_: u64`, i.e. it would look like
```
error[E0308]: mismatched types
 --> src/main.rs:3:18
  |
3 |     let _: i64 = a;
  |            ---   ^
  |            |     |
  |            |     expected `i64`, found `u8`
  |            |     help: you can convert an `u8` to `i64`: `a.into()`
  |            expected due to this
```

@rustbot modify labels: A-diagnostics, T-compiler, D-papercut, C-enhancement, E-easy

This issue has been assigned to @samrat via [this comment](https://github.com/rust-lang/rust/issues/71580#issuecomment-620088274).

**Comment by steffahn** [comment]
Well, I should’ve checked nightly first ^^

**Comment by steffahn** [comment]
Okay, lots of cases that already work got me confused into thinking this was fixed in nightly for a moment.

What currently already works is the hint about converting

- `u𝑛` ⟶ `u𝑚` where 𝑛<𝑚
- `i𝑛` ⟶ `i𝑚` where 𝑛<𝑚

What currently suggest `try_into().unwrap()` even though `into()` works

- `u𝑛` ⟶ `i𝑚` where 𝑛<𝑚
- `u8` ⟶ `isize`
- `i𝑛` ⟶ `isize` where 𝑛≤16
- `u𝑛` ⟶ `usize` where 𝑛≤16

**Comment by jonas-schievink** [comment]
I reported a similar issue not long ago. Maybe it would be more robust and also more general to rewrite this suggestion code to actually look for the impl in question instead of having just a hard-coded list?

**Comment by samrat** [comment]
I've created a PR augmenting the existing code to change the suggestions for the cases listed. But I would like to explore the approach @jonas-schievink suggested(perhaps as part of a separate PR?). Any advice on how I could get the code to look for the impl so it can make the appropriate suggestion? Is the `trait_selection` crate the right place to be looking at for this?

**Comment by jonas-schievink** [comment]
> Is the `trait_selection` crate the right place to be looking at for this?

Yeah. I believe you'll need to create an `InferCtxt` and `SelectionContext` and then call `SelectionContext::select`, but there might be other/better ways to do this. You might want to ask for advice on Zulip.
