### ISSUE TITLE
`Cow<'a, B: ToOwned>` is too restritive

### ISSUE THREAD

**Issue by c410-f3r** [rust-lang/rust#71588]
Please, close this issue if it is a duplicate.

Or I rather say that `ToOwned` is too restrictive because of its associated type.
The following snippet can't be implemented because `Cow::Owned(B)` where `B = str` expects only and solely `String` due to `impl ToOwned for str { Owned = String }`.

```rust
use std::borrow::Cow;

struct StackAsciiStr([u8; 32], usize);

impl<'a> From<StackAsciiStr> for Cow<'a, str> {
    fn from(from: StackAsciiStr) -> Self {
        Cow::Owned(from) // Error! `Cow::Owned` expects `String`
    }
}
```

This particular situation becomes really annoying when a third-party API expects `T: Into<Cow<'a, str>>` and the only owned thing that can be passed is a `String`.

Sure, it isn't possible to change any of these signatures but maybe this use-case might be another reason for a more flexible "Cow-like" struct.

**Comment by cuviper** [comment]
Do you have any ideas what that more flexible API would look like? I don't know how you'd pass arbitrary owned types to your 3rd party that accepts `Cow`, unless you hide that like `Box<dyn Borrow<B>>`.

**Comment by c410-f3r** [comment]
Unfortunately, I personally couldn't imagine anything beyond `impl<'a, B, O> NewCow<'a, B, O>` or `impl<'a, B, O> NewCow<'a, B, O> where B: NewToOwned<O>` with `NewToOwned<O> {}`. A bit disappointment though :( 

The `Box<dyn Borrrow<B>>` approach is very interesting.

**Comment by Mark-Simulacrum** [comment]
I think a replacement for `Cow` would need an RFC, it's not a small feature request, so I'm going to go ahead and close. Thanks!
