### ISSUE TITLE
E0599 can refer to placeholder {integer} as a type

### ISSUE THREAD

**Issue by CAD97** [rust-lang/rust#71594]
[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=11909882cbdb0cec5727b3a32e2d4b8c)

```rust
fn main() {
    let int = 42;
    let ones = int.count_ones();
    println!("one(s): {}", ones);
}
```

```
error[E0599]: no method named `count_ones` found for type `{integer}` in the current scope
 --> src/main.rs:3:20
  |
3 |     let ones = int.count_ones();
  |                    ^^^^^^^^^^ method not found in `{integer}`
```

`{integer}` is not a type, it is a placeholder for a real `iN`/`uN` type when a literal hasn't been assigned a concrete type. As such, `{integer}` doesn't have methods, and we shouldn't be looking for them.

This should probably be E0282 (type annotations needed) instead, perhaps with an added note about integer type fallback.

**Comment by estebank** [comment]
[The current beta's output is](https://play.rust-lang.org/?version=beta&mode=debug&edition=2018&gist=63c6c5bf3eef09f6cbdfb12e2f0198a4):

```
error[E0689]: can't call method `count_ones` on ambiguous numeric type `{integer}`
 --> src/main.rs:3:20
  |
3 |     let ones = int.count_ones();
  |                    ^^^^^^^^^^
  |
help: you must specify a type for this binding, like `i32`
  |
2 |     let int: i32 = 42;
  |         ^^^^^^^^
```
