### ISSUE TITLE
Strange JSON output from x.py / rustbuild

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#71613]
Since recently, the following line started to appear in `x.py` output, for example when invoking `./x.py test src/test/ui --stage 1 -j 4 --test-args con`:
```
{"reason":"build-finished","success":true}
```
Showing this between the otherwise human-readable output was presumably not intentional. :)

Cc @Mark-Simulacrum

**Comment by jonas-schievink** [comment]
Duplicate of https://github.com/rust-lang/rust/issues/71561
