### ISSUE TITLE
No longer able to clone the repo cleanly

### ISSUE THREAD

**Issue by Diggsey** [rust-lang/rust#71626]
I don't know if it's due to having reached a certain size, but I've found I can no longer clone this repo cleanly - after a few percentage points of progress, I get the error:

```
fatal: The remote end hung up unexpectedly
```

It does not appear to be a network issue as it happens reliably at the same point. At best, I found this thread which suggests a couple of solutions, neither of which solved the problem for me: https://stackoverflow.com/questions/6842687/the-remote-end-hung-up-unexpectedly-while-git-cloning

If the cause of this is know, it would be worth adding something to the README/CONTRIBUTING. If anyone else has the same issue, the best workaround I've found is to first do a shallow clone, and then convert to a normal clone using `git fetch --unshallow`

**Comment by Mark-Simulacrum** [comment]
Cc @rust-lang/infra 

Can you check that this reproduces on other machines (or ideally git versions I guess)? Also, how are you cloning - ssh, http, or the native git protocol? We clone this repo in CI literally hundreds of times a day, though I think most of those are shallow clones. I believe our GitHub provided stats indicate dozens of unique cloners a day though, so I suspect if this was widespread we'd see more reports... but maybe it's very recent.

**Comment by Diggsey** [comment]
It seems to be an issue with TortoiseGit - when I clone via the command-line it works fine (even though it's running the exact same `git` binary and the exact same command...)
