### ISSUE TITLE
Support overriding the ? behavior locally (by redefining the try! macro)

### ISSUE THREAD

**Issue by stevenroose** [rust-lang/rust#71643]
When [the `?` operator was implemented](https://github.com/rust-lang/rust/pull/31954/), it looks like it was meant to be equivalent to the `try!` macro.

This has the nice property that overriding the `try!` macro in your own project, allows you to capture all the `?` invocations and add additional logic like logging file and line number or wrapping that information into a new error object.

Sadly it seems that the `?` operator is no longer equivalent to the `try!` macro. So overriding `try!` does not change the behavior of `?` in your project. It would be awesome if this would be made possible.

**Comment by jonas-schievink** [comment]
This is covered partially by https://github.com/rust-lang/rust/issues/42327, and anything beyond that would require an RFC, so closing in favor of that.

**Comment by stevenroose** [comment]
How would it work for the trait to know the file and line number where the error was generated?
