### ISSUE TITLE
rustc: error while loading shared libraries: libLLVM-10.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by Evernow** [rust-lang/rust#71650]
Whenever I try to launch rust, I get this error: 

`rustc: error while loading shared libraries: libLLVM-10.so: cannot open shared object file: No such file or directory`

Rust version (had to get it through my package manager, as running rust version results in the same error) 

1:1.43.0-1

I am using LLVM11, not sure why it is looking for LLVM10. 

Manjaro Linux

**Comment by jonas-schievink** [comment]
This seems like a packaging issue. Please check with the toolchain downloaded by rustup.

**Comment by jonas-schievink** [comment]
Rust does not support LLVM 11 yet, so maybe try installing LLVM 10?

**Comment by Evernow** [comment]
> Rust does not support LLVM 11 yet, so maybe try installing LLVM 10?

My setup sadly requires LLVM 11, I'll have to use rust in a VM then, thanks for the response!
