### ISSUE TITLE
Remove the `pref_align_of` intrinsic.

### ISSUE THREAD

**Issue by lcnr** [rust-lang/rust#71666]
Afaict this is never used.

It also seems like the only user of the `pref` field of https://doc.rust-lang.org/nightly/nightly-rustc/rustc_target/abi/struct.AbiAndPrefAlign.html is this intrinsic.

In case this is deemed useful, we should document what it does :sweat_smile:

**Comment by Mark-Simulacrum** [comment]
I agree that the intrinsic doesn't seem to be used outside of tests, but that doesn't seem like reason enough to deprecate it/remove it; it does expose a plausibly useful ABI detail, it's just that most code doesn't care -- I believe preferred alignment (what the intrinsic returns) is something that mostly only codegen/LLVM cares about.

I'm going to close this issue as there are users of the intrinsic -- see https://github.com/rust-lang/rust/blob/a58b1ed44f5e06976de2bdc4d7dc81c36a96934f/src/test/ui/intrinsics/intrinsic-alignment.rs for one.

Personally I don't know that documentation for intrinsics is hugely helpful, especially as in this case it would essentially just say "the preferred alignment for this type" which seems not hugely helpful...
