### ISSUE TITLE
Missing tests for intrinsics.

### ISSUE THREAD

**Issue by lcnr** [rust-lang/rust#71669]
There are a few intrinsics which are not tested.

We also don't test the emitted IR for most intrinsics, e.g. `ctlz_nonzero` could use `ctlz` without being noticed.

- [ ] `pref_align_of`: never used
- [x] `volatile_copy_nonoverlapping_memory`: used in a test for #39827 without checking its output or IR
- [x] `volatile_copy_memory`: ^
- [x] `volatile_set_memory`: ^^
- [x] `unaligned_volatile_load`: both IR and use with unaligned addr never checked
- [x] `unaligned_volatile_store`: ^
- [x] `nearbyintf32`: never used
- [x] `nearbyintf64`: ^

**Comment by lcnr** [comment]
If someone wants to work on this feel free to ask here or on zulip.

See https://github.com/rust-lang/rust/blob/5db778affee7c6600c8e7a177c48282dab3f6292/src/test/codegen/intrinsics/unchecked_math.rs#L1-L11 for how to test an intrinsic.

**Comment by wangtheo** [comment]
I'd like to take a stab at this (if no one else is working on this issue yet).

**Comment by lcnr** [comment]
Doesn't seem like someone else is already looking at this.

@rustbot claim @wangtheo

**Comment by good-praxis** [comment]
#74285 has been merged, so this issue could be closed methinks

**Comment by lcnr** [comment]
We are still missing codegen tests for many intrinsics, but I am not sure how useful this issue is to track that, so I will just go ahead and close this.

@good-praxis in case you were interested in working on this issue, that might be something you can look into
