### ISSUE TITLE
Consider depricating `intrinsics::transmute`.

### ISSUE THREAD

**Issue by lcnr** [rust-lang/rust#71667]
Both `mem::transmute` and `intrinsics::transmute` are stable and have the exact same (quite long) documentation.

IMO we should deprecate `intrinsics::transmute` and shorten its docs to mostly point to `mem::transmute`. I might have missed some previous discussions about this in my quick search.

**Comment by Mark-Simulacrum** [comment]
We cannot really do so with `intrinsics::transmute` as it's not *called* by mem::transmute, it is mem::transmute: https://github.com/rust-lang/rust/blob/d9312a8db30b9eb345baf7ebaba6d92061d49096/src/libcore/mem/mod.rs#L26

In any case, I don't believe that there's strong benefits to deprecating an unstable intrinsic.

**Comment by lcnr** [comment]
@Mark-Simulacrum 

While its good that the documentation is not duplicated I would still like to depricate this intrinsic exactly because it **is** stable.
```rust
use std::intrinsics::transmute;

#[repr(transparent)]
struct A(u8);

fn main() {
    assert_eq!(unsafe { transmute::<_, u8>(A(7)) }, 7);
}
```
This currently works without a warning.

**Comment by Mark-Simulacrum** [comment]
Yes, that's a known stability "hole" but it's intentional, IIRC there's no way to define a re-export as stable when the underlying type/function is unstable so we can't really change this.

**Comment by lcnr** [comment]
We can change this, it is is obv a different question if this is worth it though.

```rust
pub use core::intrinsics::transmute;
// -->
#[inline(always)]
pub fn transmute<T, U>(value: T) -> U {
    core::intrinsics::transmute(value)
}
```
I personally really dislike any stable methods in `intrinsics`, which is why I
want to do this.

`</bikeshed>`

**Comment by Mark-Simulacrum** [comment]
No, you can't just do that -- transmute cannot be called with generic arguments:

```
error[E0512]: cannot transmute between types of different sizes, or dependently-sized types
 --> src/lib.rs:4:5
  |
4 |     core::intrinsics::transmute(value)
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: source type: `T` (this type does not have a fixed size)
  = note: target type: `U` (this type does not have a fixed size)
```
