### ISSUE TITLE
Use of feature flagged functions in std::cfg macro

### ISSUE THREAD

**Issue by dfreese** [rust-lang/rust#71679]
I tried [this code](https://rust.godbolt.org/z/qjXaiH):

```rust
#[cfg(feature = "enabled")]
pub fn conditionally_enabled() -> i64 {
    42
}

pub fn always_enabled() -> i64 {
    9001
}

pub fn integration() -> i64 {
    if cfg!(feature = "enabled") {
        conditionally_enabled()
    } else {
        always_enabled()
    }
}
```

I expected to see this compile based on [the std::cfg macro docs](https://doc.rust-lang.org/std/macro.cfg.html), instead, this it failed to compile.  This was confusing, as I was able to write this, in a slightly less clear way, using cfg attributes.  The documentation calls out the links between the two, saying `The syntax given to this macro is the same syntax as the cfg attribute`.

Should the docs for std::cfg be updated to state that both branches of the if/else need to be valid regardless of the cfg! condition?  Or is this something that would be expected to compile?

### Meta

This was tested on 1.42.0, but from compiler explorer, this shows up in all versions since 1.0.0
`rustc --version --verbose`:
```
rustc 1.42.0 (b8cedc004 2020-03-09)
```

**Comment by Mark-Simulacrum** [comment]
We can update the docs, for sure, but I'm not sure what to say -- maybe something like "this simply evaluates to true/false"? `cfg!` is basically not special to the compiler, it doesn't ever remove code, so everything still needs to compile (unlike `#[cfg(...)]` which will remove code if the expression doesn't evaluate to true).

**Comment by dfreese** [comment]
To rephrase, slightly, how about adding the following to the docs:

`cfg!`, unlike `#[cfg(...)]`, does not remove any code and only evaluates to true or false.  For example, this means all code in an if/else block needs to be valid when `cfg!` is used for the condition, regardless of what `cfg!` is evaluating.
