### ISSUE TITLE
char::try_to_ascii ?

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust#71683]
A simple method that could be useful:
```
char::try_to_ascii() -> Option<u8>;
```
related to char::is_ascii and char::to_ascii_lowercase/uppercase. Its purpose is to avoid some 'as' casts in user code:
```
if let Some(c) = c.try_to_ascii() {
    let order = c.to_ascii_uppercase() - b'A';
```
A simple implementation could be:
```
#[inline]
pub const fn try_to_ascii(&self) -> Option<u8> {
    if *self as u32 <= 0x7F {
        Some(*self as u8)
    } else {
        None
    }
}
```

**Comment by fmease** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/110998 which currently includes [`char::as_ascii`](https://doc.rust-lang.org/nightly/std/primitive.char.html#method.as_ascii) (`fn(self: &str) -> Option<AsciiChar>`).
