### ISSUE TITLE
Add compiler option to strip symbols from generated binaries

### ISSUE THREAD

**Issue by GabrielMajeri** [rust-lang/rust#71757]
There's a long standing Cargo [issue](https://github.com/rust-lang/cargo/issues/3483), requesting the ability to strip symbols from built Rust binaries.

@alexcrichton suggested [here](https://github.com/rust-lang/cargo/pull/8191#issuecomment-622427985) that
> This might be best done as a rust-lang/rust PR first which has access to target information to know what flag should be passed to the linker. For example this could be added as -C strip or something like that. We could then add a profile setting for Cargo to configure that on the Cargo side of things afterwards.

I'm opening this issue to discuss adding such a `-C strip` flag and to track its implementation in the compiler.

Right now, it could be a simple boolean flag, which passes an additional option to the linker (since, AFAIK, most linkers have some sort of flag for stripping symbols from the final binaries).

**Comment by ehuss** [comment]
I'm uncertain, but isn't `-Zstrip-debuginfo-if-disabled` essentially the same?

**Comment by GabrielMajeri** [comment]
> I'm uncertain, but isn't `-Zstrip-debuginfo-if-disabled` essentially the same?

As far as I understand, this will only remove debug symbols, while the issue is about striping all symbol information (this means removing all symbols from an executable, and non-exported symbols for a dynamic library).

This is analogous to the `--strip-all` and `--strip-debug` linker flags. What I am proposing would affect the size of release builds too.

**Comment by petrochenkov** [comment]
https://github.com/rust-lang/rust/pull/71825#issuecomment-626063051 suggests introducing `-Z strip=[none|debuginfo|symbols]`.
