### ISSUE TITLE
[regression] cannot declare non-inline module inside a block

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#71766]
```
[INFO] [stdout] error: Cannot declare a non-inline module inside a block unless it has a path attribute
[INFO] [stdout]  --> src/rcalc/lexer.rs:124:1
[INFO] [stdout]   |
[INFO] [stdout] 4 | mod rcalc;
[INFO] [stdout]   | ^^^^^^^^^^
[INFO] [stdout] 
[INFO] [stdout] error: aborting due to previous error
```

* https://crater-reports.s3.amazonaws.com/beta-1.44-1/beta-2020-04-26/gh/ayazhafiz.rcalc/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.44-1/beta-2020-04-26/gh/ayazhafiz.xela-lang/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.44-1/beta-2020-04-26/reg/rcalc-0.1.2/log.txt

cc @petrochenkov 

Possibly related to changes in rustdoc, I believe both cases are inside doctests?

**Comment by petrochenkov** [comment]
Bisection points to https://github.com/rust-lang/rust/commit/57e1da59cd0761330b4ea8d47b16340a78eeafa9.

**Comment by petrochenkov** [comment]
That's https://github.com/rust-lang/rust/pull/69838 "Expansion-driven outline module parsing".

**Comment by petrochenkov** [comment]
Minimized:
```
/// ```
/// mod nonexistent;
/// ```
pub fn in_library_crate() {}
```
```
cargo test
```
Passes on stable, produces `error: Cannot declare a non-inline module inside a block unless it has a path attribute` on nightly.

**Comment by petrochenkov** [comment]
So, before #69838 `Parser` had this option `recurse_into_file_modules` that silently turned `mod foo;` into `mod foo {}`, and rustdoc happened to use it in doctests, and now the option is removed, and rustdoc no longer turns `mod foo;` into `mod foo {}`, and rustdoc tries to load it from a file and fails.

**Comment by petrochenkov** [comment]
Seems acceptable, the regression can only happen in doctests and making doctests behave more like regular Rust code is good.

**Comment by Mark-Simulacrum** [comment]
To be clear, `mod foo;` was turned into `mod foo {}` in blocks, right?

If so I agree that this seems like a bug fix that we should accept. I'm going to cc @rust-lang/lang just in case there's disagreement but it seems obvious to me that we should rather reject `mod foo;` in blocks than essentially silently ignore it.

**Comment by petrochenkov** [comment]
Everything in doctests is in a block, AFAIK?

However, if it wasn't, rustdoc would still turn `mod foo;` to `mod foo {}` due to the way it called parser for doctests.

**Comment by nikomatsakis** [comment]
I agree this seems like a bug fix, yes.
