### ISSUE TITLE
Tracking issue for associated functions and consts of `std::char`.

### ISSUE THREAD

**Issue by eduardosm** [rust-lang/rust#71763]
The `std::char` module defines functions that could be instead associated methods of the `char` type (e.g., `decode_utf16`). Making them associated to the `char` type allows to use directly `char::method` instead of `std::char::method`. Similarly, the `std::char::MAX` and `std::char::REPLACEMENT_CHARACTER` could also be associated constants (like done with integer constants in https://github.com/rust-lang/rust/pull/68952).

**Comment by eduardosm** [comment]
I can help to implement to do this. This is what I would do:
* Move the functions and constants into `impl char` and make them unstable (with features `assoc_char_funcs` and `assoc_char_consts`).
* Implement the non-associated versions on top of the associated ones.

**Comment by eduardosm** [comment]
> Implement the non-associated versions on top of the associated ones.

Given the module structure inside the `core::char` module, I think it would be better to implement the associated functions on top of the other functions.

**Comment by eduardosm** [comment]
This is currently the issue pointed as tracking issue for the new features added in https://github.com/rust-lang/rust/pull/71854, so this issue should be reopened or a proper tracking issue should be created.

**Comment by kornelski** [comment]
Are there any blockers to stabilizing this?

**Comment by gilescope** [comment]
This would be great to stabilise as it trips new users up that the methods aren't availllable on char in stable rust at the moment.

**Comment by bstrie** [comment]
I'm assuming that no separate RFC is necessary here since, speaking as the author of RFC 2700, it was simple oversight on my part that the wannabe associated items on `char` were overlooked. I'll submit a stabilization PR for consideration.
