### ISSUE TITLE
[regression] typed-html overflows representing Option<&T>

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#71764]
* https://crater-reports.s3.amazonaws.com/beta-1.44-1/beta-2020-04-26/reg/typed-html-0.2.2/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.44-1/beta-2020-04-26/gh/erochest.ff-history-page/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.44-1/beta-2020-04-26/gh/extraymond.game_reviewer/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.44-1/beta-2020-04-26/gh/extraymond.personal_blog.rs/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.44-1/beta-2020-04-26/gh/logankeenan.typed-html-components/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.44-1/beta-2020-04-26/reg/typed-html-0.2.2/log.txt

```
[INFO] [stderr] error: overflow representing the type `std::option::Option<&T>`
[INFO] [stderr] 
[INFO] [stderr] error: aborting due to previous error
[INFO] [stderr] 
[INFO] [stderr] error: could not compile `typed-html`.
```

**Comment by LeSeulArtichaut** [comment]
Duplicate of #71359?

**Comment by Mark-Simulacrum** [comment]
Closing. Seems plausible. I'll leave a comment there too.
