### ISSUE TITLE
rustc_interface should provide a way to get typed diagnostics

### ISSUE THREAD

**Issue by georgewfraser** [rust-lang/rust#71770]
As discussed in the [rust-internals forum](https://internals.rust-lang.org/t/using-the-rustc-interface-crate/11982/22), the only way to intercept the stream of diagnostics is to configure rustc to emit JSON messages to your own buffer:

```rust
let writer: std::io::Write = [..byte buffer of some kind..];
let config = rustc_interface::Config {
    opts: rustc_session::config::Options {
        error_format: rustc_session::config::ErrorOutputType::Json {
            pretty: false,
            json_rendered: rustc_errors::emitter::HumanReadableErrorType::Default(
                rustc_errors::emitter::ColorConfig::Never,
            ),
        },
        [..other things..]
    },
    diagnostic_output: rustc_session::DiagnosticOutput::Raw(Box::from(writer)),
    [..other things..]
};
rustc_interface::run_compiler(config, |compiler| {
    [..do something that triggers diagnostics..]
});
```

This emits diagnostics in JSON format, which you then have to parse back into [Diagnostic](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_errors/json/struct.Diagnostic.html). It seems to me that it should be possible to tap into the stream of diagnostics without having to convert them to JSON and back.

It seems to me the most logical way to accomplish this would be to add another member to [DiagnosticOutput](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_session/enum.DiagnosticOutput.html), something like:

```rust
pub enum DiagnosticOutput {
    Default,
    Raw(Box<dyn Write + Send>),
    Report(Fn<Diagnostic>), // new member
}
```

I would be happy to work on a PR along these lines, if maintainers indicate it would be welcome and give some guidance on the approach.

**Comment by Mark-Simulacrum** [comment]
I looked over the internals thread briefly, but I wasn't able to determine exactly what the use case would be for this. Can you comment on that? Generally speaking we try to avoid APIs that aren't used by the compiler itself as they're extra "bloat" (and the compiler is already not small :).

**Comment by georgewfraser** [comment]
This would be used by tools that interact with rust code and want to display diagnostics. Most obvious scenario is a rust language server. Currently, rust language servers invoke cargo out-of-process and parse the JSON output. This has a bunch of problems, probably the simplest one to explain is that when you write a language server you want to present diagnostics for the version of the file that's in-memory in the editor, which is usually more recent than the version that's on disk.

**Comment by Mark-Simulacrum** [comment]
Hm, I would personally not be sold by that argument :)

In particular, I think keeping this decoupled and having the language server use the existing `DiagnosticOutput::Raw` is better -- it can parse the JSON emitted there.

FWIW, I'd personally love the drop the Default argument from DiagnosticOutput and set things up to always write to the Box, whatever that is.

**Comment by georgewfraser** [comment]
This is a surprising response! It is true that parsing the JSON is a workable solution. But there are serious down sides of serializing the `Diagnostic` type and then parsing it back into essentially the same types:
- It means if there are ever changes to the `Diagnostic` type, they will produce runtime rather than compile-time errors. 
- The API surface of the compiler isn't actually any smaller---it's just hidden in the JSON format.
- Every client of the compiler interface has to redefine the `Diagnostic` type, and all of its members, because the built-in `Diagnostic` is not deserializable.
- The clients are just as coupled to the compiler internals as they would be if the output format was `Diagnostic` rather than `Diagnostic, serialized into JSON`.

I also note that every other major compiler I've ever looked at provides a programmatic diagnostics API: Java, Typescript, Kotlin, F#. "How to make a good external API for a compiler" is fairly well-trod territory---does the rust compiler team have any examples of existing compiler interfaces that they consider especially well-done, that can be considered a precedent to look to for driving these sorts of decisions?

**Comment by Mark-Simulacrum** [comment]
The compiler currently is not really "interested" in external APIs at this level I think, currently we're pursuing sort of "components" like chalk, polonius more so than the high-level API.

On the other hand, since the JSON diagnostic representation *is* intended to be stable I believe, I would personally be open to publishing a crate that parses that (and the compiler could use it internally to generate said JSON, too).

Another reason I'm uncertain about the Diagnostic-taking function is that JSON is inherently less stable. For example, we currently tell Cargo when metadata is built so that dependencies can start compiling earlier -- this is done as a JSON message on stderr, but it's not a diagnostic. More such messages are likely in the future, and I wouldn't want to over promise what the compiler needs as a diagnostic output -- `Box<dyn Write>` is about the level of promise I think we're ready to make at this point :)
