### ISSUE TITLE
rustdoc: core::alloc struct reexports in alloc::alloc have broken [src] links

### ISSUE THREAD

**Issue by NeoRaider** [rust-lang/rust#71789]
The [src] links in alloc::alloc docs incorrectly use a `https://doc.rust-lang.org/nightly/` prefix for reexports from core::alloc (both locally and on doc.rust-lang.org), for example in https://doc.rust-lang.org/alloc/alloc/struct.Layout.html

[src] links in std::alloc are working correctly.

**Comment by jyn514** [comment]
The link you posted works for me. Can you still replicate on nightly?

**Comment by ehuss** [comment]
I believe this is fixed in 1.46 which should go live tomorrow.

**Comment by NeoRaider** [comment]
The [src] links on the page I linked are still absolute links pointing at the nightly docs, but on the nightly doc page [src] links are relative. So unless there is a difference in the stable and nightly doc build process that could explain the difference, it has likely been fixed in nightly.

**Comment by jyn514** [comment]
Oh I see what you mean. Yes, on the beta page this points to /beta and not /nightly: https://doc.rust-lang.org/beta/alloc/alloc/struct.Layout.html and https://doc.rust-lang.org/beta/src/core/alloc/layout.rs.html#26-38.

**Comment by ehuss** [comment]
Just a note: I was a bit confused in my comment above about it fixed in 1.46.  It is actually fixed in 1.47.  I forgot that beta is promoted a few days early, so it will actually be fixed in 6 weeks on the stable URL.
