### ISSUE TITLE
Add a help if implicitly required `Sized` bounds can be relaxed.

### ISSUE THREAD

**Issue by lcnr** [rust-lang/rust#71790]
```rust
trait Trait{
    fn func() -> Struct<Self>;    
}

struct Struct<T>{
    _t: std::marker::PhantomData<*const T>,
}
```
[Currently errors with](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=12430a21f1f1d34ed053953f62f6d993)
```
error[E0277]: the size for values of type `Self` cannot be known at compilation time
 --> src/lib.rs:2:18
  |
2 |     fn func() -> Struct<Self>;    
  |                  ^^^^^^^^^^^^- help: consider further restricting `Self`: `where Self: std::marker::Sized`
  |                  |
  |                  doesn't have a size known at compile-time
...
5 | struct Struct<T>{
  |               - required by this bound in `Struct`
  |
  = help: the trait `std::marker::Sized` is not implemented for `Self`
  = note: to learn more, visit <https://doc.rust-lang.org/book/ch19-04-advanced-types.html#dynamically-sized-types-and-the-sized-trait>
```
This seems to cause at least some confusion (see https://github.com/rust-lang/rust/issues/71788)

When adding the "help: the trait `std::marker::Sized` is not implemented for `Self`",
we can check if the implicit `Sized`  bound is required for `Self` and if not, add
"help: consider relaxing this trait bound" and recommend adding `?Sized` to `T`.

**Comment by lcnr** [comment]
I would actually prefer if we add a lint for structs which implicitly require `Sized` when it is not needed.

i.e.
```rust
struct Struct<T> {
    field: *const T,
}

// Overly strict implicit `Sized` bound, consider making this trait bound explicit:
struct Struct<T: ?Sized> {
    field: *const T,
}
// or
struct Struct<T: Sized> {
    field: *const T,
}

**Comment by estebank** [comment]
#73261 addresses the diagnostics part of this ticket, but won't close it so that we can [track the following](https://github.com/rust-lang/rust/issues/71790#issuecomment-622921581)

> add a lint for structs which implicitly require `Sized` when it is not needed.
