### ISSUE TITLE
Rustdoc: impl block with only associated constants not collapsible

### ISSUE THREAD

**Issue by tspiteri** [rust-lang/rust#71822]
```rust
pub struct S;
impl S {
    pub const C: () = ();
}
impl S {
    pub fn foo() {}
}
```
The first impl block with a constant is not collapsible like the second impl block with a function.

![methods](https://user-images.githubusercontent.com/18604588/80896661-f6ddeb80-8cf0-11ea-8e03-51a136a67dfd.png)

**Comment by GuillaumeGomez** [comment]
As far as I can tell, this is the desired behaviour (not to hide associated impl constant). So unless I'm missing something, there is nothing to fix here?

cc @rust-lang/rustdoc

**Comment by tspiteri** [comment]
Why are they not hidden? It felt surprising to me, as they are part of the impl block. Also because if an impl block contains both constants and methods, both the constants and the methods are hidden when the impl block is collapsed (and this I expected).

**Comment by tspiteri** [comment]
For example [`impl i32`](https://doc.rust-lang.org/1.43.0/std/primitive.i32.html#impl) contains constants, and it is collapsible, with both the constants and the methods hidden on collapse.

**Comment by GuillaumeGomez** [comment]
It seems weird to me as well but I wasn't the one enforcing it and I don't remember the reason. Let's wait to hear from @rust-lang/rustdoc first.

**Comment by kinnison** [comment]
It seems odd to me that they're not treated equivalently.
