### ISSUE TITLE
Tracking Issue for slice::retain

### ISSUE THREAD

**Issue by MarinPostma** [rust-lang/rust#71831]
This proposes to add a `retain` method to slice, that does the same thing as `Vec::retain`.

This tracking issue, and it's ascociated PR(#71832) are heavily influenced by the discussion in #54279

**Comment by KodrAus** [comment]
Since the implementation PR was closed (just due to inactivity) we don't really have a feature to track here. I'll go ahead and close this one now, but if #71832 returns in some form then feel free to re-open!
