### ISSUE TITLE
Cannot mix `impl Trait` and explicit generic arguments

### ISSUE THREAD

**Issue by glandium** [rust-lang/rust#71869]
I tried this code:

```rust
trait Foo {}

impl Foo for usize {}

fn bar<T: Foo>(_t: impl Foo) -> T {
    unimplemented!();
}

fn main() {
    bar::<usize>(42);
}
```

I expected this would give the explicit return value.

Instead, this happened:
```
error[E0632]: cannot provide explicit generic arguments when `impl Trait` is used in argument position
  --> src/main.rs:10:11
   |
10 |     bar::<usize>(42);
   |           ^^^^^ explicit generic argument not allowed
```

**Comment by jonas-schievink** [comment]
This is working as intended, see the impl trait RFCs for details.

**Comment by glandium** [comment]
I don't see anything mentioned in https://github.com/rust-lang/rfcs/blob/master/text/1951-expand-impl-trait.md. There's something about the lack of explicit instantiation for the simple case, but nothing for mixed cases like the example I pasted.

**Comment by jonas-schievink** [comment]
Ah, it looks like this was documented on the tracking issue instead: https://github.com/rust-lang/rust/issues/44721

**Comment by glandium** [comment]
That issue says "for now", which implies it's not the wanted final state.
