### ISSUE TITLE
Conflicting at implement TryInto<Option<V>>

### ISSUE THREAD

**Issue by botika** [rust-lang/rust#71885]
Shouldn't it be possible?

```rust
use std::convert::TryInto;

struct Foo;

impl TryInto<Option<Foo>> for Foo {
    type Error = ();
    fn try_into(i: Option<Foo>) -> Result<Self, Self::Error> {
        Ok(Some(Foo))
    }
}

fn main() {}
```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=8b88ff3cee0e9fe949782ddb8bb54986))

Errors:

```
   Compiling playground v0.0.1 (/playground)
error[E0119]: conflicting implementations of trait `std::convert::TryInto<std::option::Option<Foo>>` for type `Foo`:
 --> src/main.rs:5:1
  |
5 | impl TryInto<Option<Foo>> for Foo {
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: conflicting implementation in crate `core`:
          - impl<T, U> std::convert::TryInto<U> for T
            where U: std::convert::TryFrom<T>;

error: aborting due to previous error

For more information about this error, try `rustc --explain E0119`.
error: could not compile `playground`.

To learn more, run the command again with --verbose.

```

**Comment by jonas-schievink** [comment]
Hi! This issue tracker is mainly meant for bug reports and concrete, small feature requests. Questions like this are better asked in the user forum at https://users.rust-lang.org/ or on [one of the chat platforms](https://www.rust-lang.org/community) used by the Rust community.

**Comment by botika** [comment]
I understand that it is [these lines](https://github.com/rust-lang/rust/blob/master/src/libcore/option.rs#L1358-L1363) that do not allow me to implement any other converter for Option.

The bug is that I can't implement any other converter for `core::option::Option`. 
My question is why? I implemented an evaluator and I have two methods to convert one for Option and one for the other types.

**Comment by dhardy** [comment]
Looks like a poor error message to me: if `std` were to add `impl<T> TryFrom<T> for Option<T>` then there would be a conflict.
