### ISSUE TITLE
MIPS is currently Big Endian only

### ISSUE THREAD

**Issue by jensnockert** [rust-lang/rust#7190]
MIPS is currently only supporting Big Endian, but many modern MIPS devices are little endian, including all Android devices. So there should be some kind of support for setting little-endian for MIPS.

In the future there are probably other platforms with this issue, just to a much smaller degree.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#624
