### ISSUE TITLE
Tracking Issue for `NonNull<[T]>::slice_from_raw_parts`

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#71941]
This is a tracking issue for the `NonNull<[T]>::slice_from_raw_parts` method proposed in PR https://github.com/rust-lang/rust/pull/71940.
The feature gates for the issue are `#![feature(nonnull_slice_from_raw_parts)]`, and `#![feature(const_nonnull_slice_from_raw_parts)]` for using as a `const fn`.

### API

```rust
impl<T> NonNull<[T]> {
  pub const fn slice_from_raw_parts(data: NonNull<T>, len: usize) -> Self;
}
```

Docs: https://doc.rust-lang.org/stable/std/ptr/struct.NonNull.html#method.slice_from_raw_parts

### Steps

- [x] Implementation: https://github.com/rust-lang/rust/pull/71940
- [x] FCP: https://github.com/rust-lang/rust/issues/71941#issuecomment-1065939514
- [ ] Stabilization PR

**Comment by jplatte** [comment]
Tracking issue is actually #71146, though GitHub's git blame does not let me find where it changed (when clicking through on the commit that alledgedly last modified the line with `issue = "71146"`, I get a commit that has `issue = "71941"`).

**Comment by m-ou-se** [comment]
@rfcbot merge

**Comment by yaahc** [comment]
> I'm willing to file the stabilization report for this if the library team is on board for stabilization.

I'd certainly appreciate one!
