### ISSUE TITLE
Add support for DllExport on Windows

### ISSUE THREAD

**Issue by kvanberendonck** [rust-lang/rust#7196]
It currently does not seem to be possible to export a function from a DLL on Windows. It's not done as one would expect when building with --lib.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#826

**Comment by klutzy** [comment]
(Note that [the missing export behavior](https://github.com/rust-lang/rust/issues/7196#issuecomment-44361212) is certainly a bug, which can be fixed without introducing dllexport syntax support. I'll open new issue for the one.)

**Comment by alexcrichton** [comment]
Note that for MSVC targets the compiler now places `dllexport` on all exported functions from a library. It does not, however deal with `dllimport` at all, and in general the situation is unfortunately a bit of a mess.

I've [written up a comment about this](https://github.com/rust-lang/rust/blob/53941be9814f05496b3147da393c639a9d48957e/src/librustc_trans/trans/context.rs#L255-L297), but I'm going to use this bug to track a more proper implementation of using `dllimport` and `dllexport`, many of the concerns of which are outlined in that bug. @klutzy also probably knows enough about this to be a good liason to talk to!

I think this is more concretely actionable in this repo than the RFC repo for now, so I'm going to reopen this.

**Comment by retep998** [comment]
I think we shouldn't indiscriminately put `dllexport` on all exported functions from a library, because if we statically link the library, then those functions still have `dllexport` and are thus exported from the resulting executable, even though the main crate doesn't publicly re-export them. I think this might be why `link` is failing to strip unreferenced functions.
