### ISSUE TITLE
macOS builders randomly stops working on GitHub Actions

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#71988]
We started noticing that occasionally one of our macOS builders stop working, marking the job as either failed or canceled and providing no logs for the build. Examples of such failed builds are:

- #71934 - https://github.com/rust-lang-ci/rust/runs/648528503
- #71951 - https://github.com/rust-lang-ci/rust/runs/649952440
- #71925 - https://github.com/rust-lang-ci/rust/runs/651724911
- #69406 - https://github.com/rust-lang-ci/rust/runs/656100319
- #72083:
  - https://github.com/rust-lang-ci/rust/runs/661212134
  - https://github.com/rust-lang-ci/rust/runs/661326448

**Comment by pietroalbini** [comment]
New one: https://github.com/rust-lang-ci/rust/runs/656100319

**Comment by pietroalbini** [comment]
Two new ones in a row from #72083:

* https://github.com/rust-lang-ci/rust/runs/661212134
* https://github.com/rust-lang-ci/rust/runs/661326448

**Comment by RalfJung** [comment]
This broke the 2nd rollup in a row: https://github.com/rust-lang/rust/pull/72187
Makes it kind of hard to land anything, really.^^

**Comment by pietroalbini** [comment]
We have a call with Github today, if there is no news we'll rollback the gate on GHA.

**Comment by pietroalbini** [comment]
GitHub is going to continue looking into this :heart: 

In the meantime I'll remove the double-gate, to let the queue run more smoothly.

**Comment by pietroalbini** [comment]
Removed the gate on GHA.

**Comment by RalfJung** [comment]
@pietroalbini thanks!
Does this take effect on the already running https://github.com/rust-lang/rust/pull/72202#issuecomment-628845457 ?

**Comment by pietroalbini** [comment]
It should.

**Comment by Aaron1011** [comment]
Possibly related: https://github.com/rust-lang-ci/rust/runs/685622726

**Comment by pietroalbini** [comment]
Just got another two failures related to this (in the same PR):

* https://github.com/rust-lang-ci/rust/runs/834243520
* https://github.com/rust-lang-ci/rust/runs/834243531

**Comment by youknowone** [comment]
I am getting similar experience in other rust project, so happy to see Github is looking into this issue.

**Comment by thejoebourneidentity** [comment]
Thanks to everyone for their patience on this issue, I work on the GitHub Actions compute platform that powers our runners and wanted to share an update.

We're aware of the issue have multiple members of our team across our entire hardware stack actively working on it. We've been able to identify a specific data center that may be the primary failure point. We're rapidly building out additional telemetry and alerting to help us find the root cause. Stay tuned, we want to fix this as soon as possible.

**Comment by matthewmccullough** [comment]
> We're aware of the issue have multiple members of our team across our entire hardware stack actively working on it. We've been able to identify a specific data center that may be the primary failure point. We're rapidly building out additional telemetry and alerting to help us find the root cause. Stay tuned, we want to fix this as soon as possible.

@thejoebourneidentity Thanks for the insight into the bug investigation and reiteration that you and the team are working on it.

**Comment by alepauly** [comment]
@pietroalbini We continue looking at this and I wanted to confirm you are still seeing the exact same symptoms of disconnects. We're been able to curve the cases where the runner disconnects and are now focusing more on perf issues that might be leading to timeouts. I browsed a few workflows and noticed timeouts such as [this](https://github.com/rust-lang-ci/rust/actions/runs/225385358). Is this a good illustration of the current problem are you seeing disconnects at a high rate still?

**Comment by pietroalbini** [comment]
@alepauly thanks for getting back to us! Indeed, it seems like the runner disconnects are not appearing anymore! I'll monitor closely the build results in the coming week to see if they appear.

Regarding the cancelled builds, like the one you mentioned, that's a mistake on our end :sweat_smile:. Since our build matrix is so big [we built an action to cancel builds once a new commit is pushed to the branch](https://github.com/rust-lang/simpleinfra/tree/master/github-actions/cancel-outdated-builds). While this is not a problem normally since our queue bot only pushes a new commit to the test branch when the previous one finishes, we're not gating our builds on the macOS builders yet due to this issue, so the queue bot isn't waiting for them to finish before pushing the new commit (causing the action to cancel the build).

I [opened a PR](https://github.com/rust-lang/rust/pull/75995) to disable the build cancellation for the macOS jobs, so the cancellations should disappear as soon as the PR lands. If we don't see any other spurious failure for a while we'll try to gate our builds on macOS again!

Thanks again for looking into this issue :heart:

**Comment by pietroalbini** [comment]
It seems [a runner disappeared only one time](https://github.com/rust-lang-ci/rust/runs/1062301475) across the whole week, which is definitely an improvement!

I'll propose during the next weekly infrastructure team meeting to try and double-gate macOS on both Azure and GitHub Actions, to see what the impact would be on our queue size.

**Comment by alepauly** [comment]
> It seems [a runner disappeared only one time](https://github.com/rust-lang-ci/rust/runs/1062301475) across the whole week, which is definitely an improvement!
> 
We'll look at it on our end, we expect this to be better but not fully solved yet. Thanks for the report.

**Comment by pietroalbini** [comment]
We didn't see it anymore for months, closing this. Thanks to everyone involved in fixing this! :heart: :
