### ISSUE TITLE
Const generics: Bounds like `T: Foo<{ value }>` don't work

### ISSUE THREAD

**Issue by jplatte** [rust-lang/rust#71986]
This is probably due to lazy normalization not being here yet, but I don't find any issues for this specifically so maybe this is a good additional test case for #71973 or a later PR?

```rust
#![feature(const_generics)]

trait Foo<const B: bool> {}
fn bar<T: Foo<{ true }>>() {}
```

I wouldn't even expect this to work necessarily, since the equivalent thing with an associated constant instead of a const generic argument produces `cannot constrain an associated constant to a value` (although without an error code :slightly_frowning_face:).

**Comment by jplatte** [comment]
Ah, nevermind, the linked PR already has a very similar test case. I guess this still tracks an issue until that PR has been merged, but I will close afterwards.

**Comment by lcnr** [comment]
Its novel enough to be added as an additional test :+1: 

We still need a lot of tests for const generics if we want to ever make them stable.
