### ISSUE TITLE
[mir-opt] optimization idea: bubble `return` terminators to predecessor blocks

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#72022]
cc @rust-lang/wg-mir-opt 

if we have a basic block with no statements and just a return terminator, any other basic block that just `goto`s into that block could just as well call `return` itself. Or do we have some rule that we can only have a single return terminator per `mir::Body`?

Maybe we can generalize this and bubble any terminator of a statement-less block into its predecessor terminators iff that predecessor terminator is a `goto`.

As an example take https://github.com/rust-lang/rust/blob/7b805396bf46dce972692a6846ce2ad8481c5f85/src/test/mir-opt/issue-62289/rustc.test.ElaborateDrops.before.mir#L84 which is a basic block with no statements and just a `return` terminator, and both predecessor blocks have a `goto` to this block.

**Comment by hanna-kruppe** [comment]
> if we have a basic block with no statements and just a return terminator, any other basic block that just `goto`s into that block could just as well call `return` itself. Or do we have some rule that we can only have a single return terminator per `mir::Body`?

I don't know if we have such a rule in (any part of) rustc, but in my experience this is a convenient assumption for some analyses and transforms. So depending on the expected value of "bubbling up" `return`s (at a glance, it seems low to me), I'd be cautious about doing it just because we can.

**Comment by ecstatic-morse** [comment]
The docs for `TerminatorKind::Return` do say that "this should occur at most once". I don't know how many places depend on this, however.

**Comment by matthewjasper** [comment]
The built MIR only contains a single Return terminator. However the generator transform code appears to output MIR with multiple return terminators in `src/test/mir-opt/generator-drop-cleanup/rustc.main-{{closure}}.generator_drop.0.mir`

**Comment by ecstatic-morse** [comment]
I concur with @nagisa. Canonicalizing a mistake made in the generator transform without making a conscious decision is wrongheaded IMO. There's probably code that relies on the fact that only one `Return` terminator exists; we just haven't found those bugs yet.

**Comment by bjorn3** [comment]
Cranelift likes multiple returns better than single returns. It never duplicates `ret` instructions, even when it would decrease the amount of register moves and jumps.

**Comment by oli-obk** [comment]
This was only added under mir-opt-level 3, in case anyone is wondering why this is closed. We haven't finished the discussion on whether we want multiple return terminators per body or whether we should fix generators
