### ISSUE TITLE
TcpSocket broken pipe

### ISSUE THREAD

**Issue by xpepermint** [rust-lang/rust#72028]
I'm using `async-std` but I feel I have to post this issue here. I'm building a proxy that forwards requests from A to B and then responses from B to A. Simple.

Most of the time everything works but randomly it fails with broken pipe error or the response shows only X% of data. I noticed that if I filter the buffer and remove all `0u8` bytes before I write bytes it seems that the problem goes away.

Example:
```rs
loop {
        ...
        let mut bytes = [0u8; 1024];
        let size = match streamB.read(&mut bytes).await.unwrap();
       ...
       let mut bytes: Vec<u8> = bytes.iter().filter(|b| **b != 0u8).cloned().collect(); // FIX
       streamA.write(bytes).await.unwrap();
       ...
}
```

Is this something that is expected or is that a possible bug?

**Comment by sfackler** [comment]
TcpStream does not look at the contents of buffers passed to write. A broken pipe error is returned from the OS when the other end of the connection has been closed.
