### ISSUE TITLE
Rustdoc fails to follow path after re-export.

### ISSUE THREAD

**Issue by gyscos** [rust-lang/rust#72056]
When re-exporting modules from another crate, documentation for this crate does not follow rust paths correctly.

A simple workspace to showcase the issue: 
* A `foo` crate, with a `foo` module and a `Foo` struct in this module. The `foo` module has documentation linking to the `Foo` struct.
* A `bar` crate which depends on `foo` with the line `pub use foo::*;`
From there, compiling documentation will:
* For the crate `foo`, correctly resolve the `Foo` link.
* For the crate `bar`, incorrectly resolve the link in the re-exported `foo` module.

```rust
# foo/src/lib.rs
pub mod foo {
    //! A mod.
    //!
    //! See [`Foo`]

    /// Some struct
    pub struct Foo;
}
```

```rust
# bar/src/lib.rs
pub use ::foo::*;
```

Here is a screenshot from the doc page for the `foo` module from the `foo` crate:
![Screenshot from 2020-05-09 10-45-57](https://user-images.githubusercontent.com/564903/81481075-57ce5d80-91e2-11ea-8801-326802c8d620.png)

And here is the documentation for the `foo` module re-exported in the `bar` crate:
![Screenshot from 2020-05-09 10-46-09](https://user-images.githubusercontent.com/564903/81481077-5866f400-91e2-11ea-8ce3-64f09bfda6d2.png)

Here is a zip with the entire workspace ready to compile: [rustdoc example.zip](https://github.com/rust-lang/rust/files/4604194/rustdoc.example.zip)

I also tried using `self::Foo`, `crate::foo::Foo`, for the same result.

Apart from this simple example, this can happen with "facade" crates that re-export all or a subset of an other crate, and expect documentation to transparently work.

**Comment by ehuss** [comment]
This appears to be a duplicate of #65983.

**Comment by gyscos** [comment]
Arf, missed that, sorry!
The source post from #65983 looks more complex though, with `[Baz]` expected to point back to the source, though that may be just a superficial difference.

**Comment by gyscos** [comment]
Actually in my case I'd be very much fine with local resolution, pointing to the re-exported item as long as the module structure is the same.
