### ISSUE TITLE
Bad error for misplaced & in pattern

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#72050]
I tried this code:

```rust
    let tuples = vec![(1, 2)];
    for (&a, _) in &tuples {
        println!("{}", a);
    }
```

I got this error:

```
error[E0308]: mismatched types
 --> src/main.rs:3:10
  |
3 |     for (&a, _) in &tuples {
  |          ^^        ------- this expression has type `&({integer}, {integer})`
  |          |
  |          expected integer, found reference
  |          help: you can probably remove the explicit borrow: `a`
  |
  = note:   expected type `{integer}`
          found reference `&_`
```

Instead, I expected a suggestion to use `for &(a, _) in &tuples {`. This error message is pretty bad and I make this error pretty often.

### Meta

`rustc --version`: `rustc 1.43.0 (4fb7144ed 2020-04-20)`
The problem is also present on nightly.

**Comment by estebank** [comment]
> This error message is pretty bad and I make this error pretty often.

The machine applicable suggestion to remove the borrow from `&a` addresses all the potential issues in these cases, every since match-ergonomics were introduced. Before then we did suggest the correct pattern, but the current style is indeed to write `for (a, _) in &tuples {` and let the compiler figure out the correct borrows and dereferences.

What is the full output you would have preferred?

**Comment by jyn514** [comment]
Removing the `&` means that the struct is now borrowed, since the `&a` in `for &a in &tuples` means to automatically dereference the value. For example, this example does not compile if you use `for (s, _) in &tuples {`:

```
fn main() {
    let mut tuples = vec![(1, 2)];
    for &(s, _) in &tuples {
        f(s);
    }
    let first = tuples.pop();
}

fn f(u: usize) {
    println!("{}", u);
}
```

[Without the borrow](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=3ad90c4a04d71f17e39db1099ddb6ce4):

```
error[E0308]: mismatched types
 --> src/main.rs:4:11
  |
4 |         f(s);
  |           ^
  |           |
  |           expected `usize`, found `&{integer}`
  |           help: consider dereferencing the borrow: `*s`
```

The output I would have preferred is something like 

```
error[E0308]: mismatched types
 --> src/main.rs:3:10
  |
3 |     for (&s, _) in &tuples {
  |          ^^        ------- this expression has type `&({integer}, {integer})`
  |          |
  |          this is a borrow of a tuple, but you used a borrow of an inner field
  |          help: you can borrow the tuple instead: `&(s, _)`
  |
  = note:   expected type `&({integer}, _)`
          found tuple `(&_, )`
```

**Comment by estebank** [comment]
But we _can't_ know that was the original intent with enough certainty. If we were to suggest this we would have to 1st check that `s`'s type is `Copy` _and_ that it is being used in such a way that needs to be owned, otherwise [we would get the following error after applying the proposed suggestion](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=7a46a47cb5006bfa872b89506fe2b9da):

```
error[E0507]: cannot move out of a shared reference
 --> src/main.rs:4:20
  |
4 |     for &(a, _) in &tuples {
  |         -------    ^^^^^^^
  |         | |
  |         | data moved here
  |         | move occurs because `a` has type `S`, which does not implement the `Copy` trait
  |         help: consider removing the `&`: `(a, _)`
```

**Comment by jyn514** [comment]
> But we can't know that was the original intent with enough certainty

Ok, so the lint will no longer be machine-applicable. Or we can only give the suggestion if `a` is `Copy`. It's still better than the current suggestion which changes the semantics.

**Comment by steveklabnik** [comment]
Triage: this hasn't changed, and I'm personally not convinced it should.

**Comment by estebank** [comment]
Triage: some superficial changes to the presentation, but the same points from the prior conversation apply. I am still of the opinion that the current suggestion is appropriate. Any subsequent borrowing errors will still provide dereferencing suggestions. I don't think we are going to change the current behavior, so I will go ahead and close this ticket. Apologies if this is frustrating, but I do not believe we realistically act on this request, as inferring any further intent for this is quite difficult.
