### ISSUE TITLE
`link_cfg` feature gate is associated to closed issue

### ISSUE THREAD

**Issue by varkor** [rust-lang/rust#72059]
https://github.com/rust-lang/rust/blob/f8b796b10b3282b02a6bb6f5b5be9dc8dc0dbf94/src/librustc_feature/active.rs#L334-L335
Relevant issue: https://github.com/rust-lang/rust/issues/37406.

I'm not sure what the state of this feature is, but we may want to use this issue as a new tracking issue.

**Comment by Elinvynia** [comment]
The linked issue mentions that this feature will never be stable, so I think there isn't a need in tracking it. I see that there is some effort in documenting this behavior here: https://github.com/rust-lang/rust/pull/71586
