### ISSUE TITLE
Make sure empty struct always derives Default

### ISSUE THREAD

**Issue by sergey-melnychuk** [rust-lang/rust#72075]
I was wondering if requiring an explicit derive(Default) for empty struct makes sense. It feels right that *empty* (for whatever reason) struct should derive Default, well, by default :)

This is my first issue in rust-lang, so any feedback is welcome. If such suggestion makes sense, I'd like to implement it with very little guidance from more experienced Rustaceans.

```rust
//#[derive(Default)]
struct X;

fn f<T: Default>(_: T) {
    ()
}

fn main() {
    f(X);
}

```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=c448e349684e8a95e611ddae67595b8f))

Errors:

```
   Compiling playground v0.0.1 (/playground)
error[E0277]: the trait bound `X: std::default::Default` is not satisfied
 --> src/main.rs:9:7
  |
4 | fn f<T: Default>(_: T) {
  |    -    ------- required by this bound in `f`
...
9 |     f(X);
  |       ^ the trait `std::default::Default` is not implemented for `X`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: could not compile `playground`.

To learn more, run the command again with --verbose.

```

**Comment by jonas-schievink** [comment]
Hi! Additions or changes to the language need to go through our [RFC process](https://github.com/rust-lang/rfcs). Before an RFC is written, the feature can also be discussed in our [internals forum](https://internals.rust-lang.org/) to find other people interested in it.

Closing in favor of an RFC.
