### ISSUE TITLE
`Iterator::unzip` not zero cost

### ISSUE THREAD

**Issue by ThouCheese** [rust-lang/rust#72085]
In my attempt to move some code to a more functional style I found that the performance regressed significantly. I have narrowed this regression down to the `Iterator::unzip` function.

I tried this code:
```rust
extern crate test;
use test::{Bencher, black_box};

fn run_functional(l: &Vec<(usize, usize)>) -> (Vec<usize>, Vec<usize>) {
    l.iter().copied().unzip()
}

fn run_imperative(l: &Vec<(usize, usize)>) -> (Vec<usize>, Vec<usize>) {
    let len = l.len();
    let (mut result1, mut result2) = (Vec::with_capacity(len), Vec::with_capacity(len));
    for item in l.iter().copied() {
        result1.push(item.0);
        result2.push(item.1);
    }
    (result1, result2)
}

#[bench]
fn bench_functional(b: &mut Bencher) {
    let list = black_box(vec![(1, 2); 256]);
    b.iter(|| run_functional(&list));
}

#[bench]
fn bench_imperative(b: &mut Bencher) {
    let list = black_box(vec![(1, 2); 256]);
    b.iter(|| run_imperative(&list));
}
```

I expected to see this happen:
I expect these benchmarks to yield the same results, since they both attempt to do the same thing.

Instead, this happened:
The benchmark results are:
```
test bench_functional ... bench:       1,440 ns/iter (+/- 66)
test bench_imperative ... bench:         443 ns/iter (+/- 43)
```
From what I can tell from reading the code in the standard library, there are two reasons why the imperative style loop is so much faster. The imperative version uses `Vec::push` instead of `Extend::extend`. Here push is significantly faster. The rest of the difference comes from the fact that the vectors are initialized using `with_capacity`, whereas the functional variant seems to reallocate. I get the same performance when I change my imperative code to this:
```rust
fn run_imperative(l: &Vec<(usize, usize)>) -> (Vec<usize>, Vec<usize>) {
    let (mut result1, mut result2) = (Vec::new(), Vec::new());
    for item in l.iter().copied() {
        result1.extend(Some(item.0));
        result2.extend(Some(item.1));
    }
    (result1, result2)
}
```
[Link](https://www.reddit.com/r/rust/comments/ggy0fa/unzip_function_slow/) to the Reddit thread, with a faster but hacky implementation from u/SkiFire13
### Meta
I have reproduced this issue on the latest nightly compiler (as of writing):
```
$ rustc --version --verbose
rustc 1.45.0-nightly (bad3bf622 2020-05-09)
binary: rustc
commit-hash: bad3bf622bded50a97c0a54e29350eada2a3a169
commit-date: 2020-05-09
host: x86_64-unknown-linux-gnu
release: 1.45.0-nightly
LLVM version: 9.0
```

**Comment by leo60228** [comment]
Usage of `extend` is irrelevant here, `vec.extend(Some(x))` has the same performance as `vec.push(x)` when it's benchmarked on its own.

**Comment by leo60228** [comment]
Wait, what? `extend` seems to be only *sometimes* worse than `push`...

**Comment by ThouCheese** [comment]
In my experiments i got some significantly different results by _just_ replacing `.push(a)` with `.extend(Some(a))`, so I think that usage of extend is definitely relevant here.

**Comment by cuviper** [comment]
There's no common `push`/`with_capacity` methods -- `unzip` has to work with its constraints:

```rust
fn unzip<A, B, FromA, FromB>(self) -> (FromA, FromB)
where
    FromA: Default + Extend<A>,
    FromB: Default + Extend<B>,
    Self: Iterator<Item = (A, B)>, 
```

However, I'm playing with adding those as optional methods on `Extend`...

**Comment by leo60228** [comment]
@cuviper The root cause seems to be that `vec.extend(Some(x))` has very poor performance in some scenarios. I think we should try to fix that instead of working around it.

**Comment by cuviper** [comment]
@leo60228 Another possibility is to add `SpecExtend` for `option::IntoIter`. That won't help with pre-allocating capacity, but it can at least be streamlined to act like `push`. However, specialization is still unstable, while new `Extend` methods could help any user's collection type.

Quick preview doing it my way, before:

```
test bench_functional ... bench:       1,522 ns/iter (+/- 57)
test bench_imperative ... bench:         408 ns/iter (+/- 15)
```

After:

```
test bench_functional ... bench:         423 ns/iter (+/- 8)
test bench_imperative ... bench:         414 ns/iter (+/- 14)
```

**Comment by leo60228** [comment]
> Another possibility is to add `SpecExtend` for `option::IntoIter`.

I don't believe this is possible. You can't currently specialize on trait generics, only the type the trait is implemented for.

**Comment by cuviper** [comment]
> You can't currently specialize on trait generics, only the type the trait is implemented for.

I don't know why you say that -- if you look at each of the implementations below, they're all `for Vec<T>`, just specializing based on the `I` type parameter.

https://github.com/rust-lang/rust/blob/4802f097c86452cd2e09d44e88dbcb8e08266552/src/liballoc/vec.rs#L2059-L2061
https://github.com/rust-lang/rust/blob/4802f097c86452cd2e09d44e88dbcb8e08266552/src/liballoc/vec.rs#L2090-L2092
https://github.com/rust-lang/rust/blob/4802f097c86452cd2e09d44e88dbcb8e08266552/src/liballoc/vec.rs#L2129

So I'm suggesting:

```rust
impl<T> SpecExtend<T, option::IntoIter<T>> for Vec<T> {
```

**Comment by leo60228** [comment]
I tried that and got coherence errors, and I asked on Discord and that was the answer I got. Perhaps it's just a diagnostics issue: I was using `Option`, not `option::IntoIter`.

**Comment by cuviper** [comment]
Hmm, for coherence I'm guessing that it couldn't _guarantee_ whether or not `Option` overlaps those generic `I` specializations, whereas `option::IntoIter` should be a strict subset.

**Comment by ThouCheese** [comment]
This is resolved on the latest nightly, that you for your efforts @cuviper and others!
