### ISSUE TITLE
Typo in docs for E0307

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#72122]
[We refer to "Arbintrary self types"](https://doc.rust-lang.org/error-index.html#E0307), where it should be "Arbitrary self types".

_CC https://twitter.com/sgrif/status/1259982082417192961_

This issue has been assigned to @Rustin-Liu via [this comment](https://github.com/rust-lang/rust/issues/72122#issuecomment-628360874).

**Comment by hbina** [comment]
`Note: this error code is no longer emitted by the compiler.` So what happened to them? I still consider them to be faulty code, but I assume there's a discussion that led to the removal of this error. There ought to be more information about that on the page.

**Comment by estebank** [comment]
I do not see that note for E0307 (but do see it for others, like E001). We do not remove documentation for error codes because people can use older compilers and might need help when googling for those errors they might see. As to what happened to them, they sometimes get superseded by other, more specific errors, and other times the compiler started accepting the code due to new features.
