### ISSUE TITLE
Rustc file lock not working on WSL

### ISSUE THREAD

**Issue by nbdd0121** [rust-lang/rust#72157]
WSL1 does not support `fcntl`-based advisory locks, therefore the current [src/librustc_data_structures/flock.rs](https://github.com/rust-lang/rust/blob/master/src/librustc_data_structures/flock.rs) implementation does not work.

This issue can be observed by running `cargo doc` on a repository with many crates. The `search-index.js` can miss crates.

According to my test `libc::flock` is working on WSL. We could replace `fcntl` based lock with `flock` based lock for Linux. However this will break lock over NFS for Linux 2.6.11 or earlier, I can author a PR if that's okay.

Related WSL issue: microsoft/WSL#1927

**Comment by cuviper** [comment]
> However this will break lock over NFS for Linux 2.6.11 or earlier

The minimum [platform support](https://forge.rust-lang.org/release/platform-support.html) is Linux 2.6.18, so that seems fine. If we can get away with switching _all_ `unix` hosts to `flock`, even better.

**Comment by nbdd0121** [comment]
> The minimum [platform support](https://forge.rust-lang.org/release/platform-support.html) is Linux 2.6.18, so that seems fine.

Cool.

> If we can get away with switching _all_ `unix` hosts to `flock`, even better.

Sure.
