### ISSUE TITLE
Why does `>>&` compile?

### ISSUE THREAD

**Issue by AlienKevin** [rust-lang/rust#72155]
Hi, I found a weird "operator" that's not listed on the [list of operators](https://doc.rust-lang.org/reference/expressions.html#expression-precedence).

I tried this code:

```rust
fn main() {
    println!("{}", 2 >> & 1);
}
```
the space between `>>` and `&` doesn't matter.

I expected to see this happen:
Compiler error telling me that Rust expects an expression after `>>` or something similar.

Instead, this happened:
It actually compiles and returns `1` for `2 >>& 1`.

Try it on [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=d2b11c687c440e26656ac78adf983d01).

### Meta
```
`rustc --version --verbose`:
rustc 1.43.1 (8d69840ab 2020-05-04)
binary: rustc
commit-hash: 8d69840ab92ea7f4d323420088dd8c9775f180cd
commit-date: 2020-05-04
host: x86_64-unknown-linux-gnu
release: 1.43.1
LLVM version: 9.0
```

**Comment by jonas-schievink** [comment]
There are two operators there. `&` takes a reference, `>>` is a right shift.

**Comment by lcnr** [comment]
note: this is `2 >> (&1)`, which is implemented here: https://doc.rust-lang.org/nightly/std/ops/trait.Shr.html#method.shr-184

**Comment by AlienKevin** [comment]
Thanks for the clarification 🙏 and sorry for bothering.
