### ISSUE TITLE
Add a white glow or background on the favicon.

### ISSUE THREAD

**Issue by FabienTregan** [rust-lang/rust#72165]
Hi,

The Rust favicon is black and transparent. On dark browser themes, it is not easy to see. Since rust book and github also have this particularity, it's hard to find the tab among the other ones.

Not really important, but if it is cheap to fix that would help :)

My tabs right now:
![image](https://user-images.githubusercontent.com/2663407/81784921-e4885c80-94fd-11ea-8f0c-6ce617f7ce7f.png)

**Comment by CryZe** [comment]
GitHub seems to dynamically switch to a white icon for dark mode. Rust could probably do the same thing.

**Comment by FabienTregan** [comment]
Though great, the [prefers-color-scheme media feature](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) is not widely used.
Probably most people don't know they can turn windows into dark mode, and it doesn't work well with every application. I guess lot of people use dark themes instead of default theme with dark os setting, and prefers-color-scheme only work with the later for me.

**Comment by frewsxcv** [comment]
Are all of these used?

- https://github.com/rust-lang/rust/blob/master/src/librustdoc/html/static/favicon.ico
- https://github.com/rust-lang/www.rust-lang.org/blob/master/static/logos/favicon.ico
- https://github.com/rust-lang/www.rust-lang.org/blob/master/static/images/favicon.ico
- https://github.com/rust-lang/www.rust-lang.org/blob/master/static/images/favicon.svg
- https://github.com/rust-lang/www.rust-lang.org/blob/master/static/images/favicon-16x16.png
- https://github.com/rust-lang/www.rust-lang.org/blob/master/static/images/favicon-32x32.png
