### ISSUE TITLE
wrapping_neg generates unnecessary instructions

### ISSUE THREAD

**Issue by falk-hueffner** [rust-lang/rust#72176]
I tried this code:

```rust
pub fn neg(x: i32) -> i32 {
    return -x;
}

pub fn wrapping_neg(x: i32) -> i32 {
    return x.wrapping_neg()
}
```

I expected to see this happen: when optimizing, both compile to the same code of basically one instruction.

Instead, this happened: Starting from 1.42.0, redundant instructions are emitted:

```
example::wrapping_neg:
        mov     eax, edi
        neg     eax
        cmp     edi, -2147483648
        cmove   eax, edi
        ret
```

See here: https://rust.godbolt.org/z/H2YFAV

**Comment by nikic** [comment]
The corresponding IR pattern gets optimized by LLVM 10 (but not LLVM 9): https://llvm.godbolt.org/z/taqx37

So probably this will be fixed by the LLVM 10 upgrade. Assigning myself to keep track.

**Comment by nikic** [comment]
This has indeed been fixed by the LLVM upgrade.
