### ISSUE TITLE
Add an allow-by-default lint against #[no_mangle]

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/rust#72188]
Given that [`#[no_mangle]` is unsafe](https://github.com/rust-lang/rust/issues/28179) there should be a lint that is capable of detecting it (there was a suggestion that `unsafe_code` should also detect it, but it might make sense to be able to lint it individually too).

**Comment by RalfJung** [comment]
So maybe `unsafe_code` should be a lint group, and include this new lint?

I am suggesting that because I think `deny(unsafe_code)` should suffice to trigger the new lint.

**Comment by Nemo157** [comment]
I've got the basic lint working now. @RalfJung do you think it's worth adding it as a separate lint, renaming `unsafe_code` to something else (which I can't think of a name for), and adding them both as lints in an `unsafe_code` group; or better to just integrate it into the current `unsafe_code` lint?

**Comment by RalfJung** [comment]
I'll defer to @rust-lang/wg-diagnostics for that :D

**Comment by estebank** [comment]
I am partial towards having a hard error when encountering multiple `no_mangle` functions with the same name in a given workspace, [as originally suggested](https://github.com/rust-lang/rust/issues/28179#issuecomment-137279496).

Adding this to `unsafe_code` might be problematic in the wild. Let's make a PR that rolls it into `unsafe_code` and see the behavior in the wild with a crater run, but if it causes too much fallout, lets make it an independent lint.

**Comment by Nemo157** [comment]
There's other ways of using `no_mangle` which create UB than just overriding within a workspace, e.g. the example in https://github.com/rust-secure-code/cargo-geiger/issues/104. While adding a hard error for cases that can be detected would be nice, I don't think it's possible in general.

**Comment by jyn514** [comment]
Removing I-prioritize since this is already tracked at https://github.com/rust-lang/rust/issues/28179

**Comment by tarcieri** [comment]
Is there a tracking issue for similar "unsafe attributes" like this? It'd be nice to have a similar lint for all of them.

**Comment by jyn514** [comment]
@tarcieri not that I know of but you could open one :)

**Comment by tarcieri** [comment]
Done #82499
