### ISSUE TITLE
Tracking Issue for const fn `<*T>::is_null`

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#72198]
This is a tracking issue for making the `is_null` method on raw pointers `const fn`
The feature gate for the issue is `#![feature(const_ptr_is_null)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also uses as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [ ] Implement
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

**Comment by RalfJung** [comment]
Cc @rust-lang/wg-const-eval

**Comment by RalfJung** [comment]
Isn't this blocked on https://github.com/rust-lang/rust/issues/53020 ? Right now, `(&0 as *const _).is_null()` will error even with Miri unleashed (and that is good, ptr comparison is a complicated subject).

**Comment by oli-obk** [comment]
yeaaa... I was a bit overexcited about this one. As my implementation quickly exploded to exactly what you're saying there. I'll close this issue again, there's no point in tracking it here. I'll just add it to the skill tree
