### ISSUE TITLE
Tracking issue for Lazy Normalization of Constants

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#72219]
As a subpart of https://github.com/rust-lang/rust/issues/60471, this tracks the work around normalizing constants that began with https://github.com/rust-lang/rust/pull/71973.

## Background and links to reading material

There is a [hackmd](https://hackmd.io/S8cE-e-ORtCqjJzyOU5cLQ) that sketched out some notes and a basic plan, though it's evolved some since then.

## FIXMEs and issues to be resolved

* Detection of illegal regions in opaque types for constants
* Diagnostics for mismatched types
* https://github.com/rust-lang/rust/issues/72129 misc cleanup

**Comment by lcnr** [comment]
cc #72129

**Comment by lcnr** [comment]
Lazy normalization of constants can be experimented with by either using `#![feature(const_generics)]` or just `#![feature(lazy_normalization_consts)]`.

**Comment by lcnr** [comment]
the nature and our understanding of lazy normalization for constants has considerably evolved over the last 2 years and I don't think this issue has a purpose anymore. Going to close this.
