### ISSUE TITLE
[rustdoc] intra-doc links for macros always resolve relative to the crate root

### ISSUE THREAD

**Issue by Lokathor** [rust-lang/rust#72243]
If you have a function defined within a module it will use that module's imports to determine link resolution for intra-doc links in the documentation.

If you do the same with a macro, it seems to "scope" the macro (and thus its intra-doc links) at the crate root only, so the macro's documentation can't benefit from the local imports.

This feels inconsistent, and can it be fixed so that macro intra-links get the local imports for their resolution?

**Comment by jyn514** [comment]
> it seems to "scope" the macro (and thus its intra-doc links) at the crate root only, 

Isn't this expected behavior? Macros are always moved up to the crate root.

**Comment by Lokathor** [comment]
Logically, within the crate's namespace, yes, the macro will appear in the crate root.

However, it makes editing the docs of the macro worse because the macro's actual location is still whatever file it's written in, not always `lib.rs`. Every other item's docs use the local file's imports to determine intra-doc links.

**Comment by jyn514** [comment]
Technically they use the imports of the parent module, not the imports of the current file. I'm sympathetic to this use case but I'm not sure how feasible it is to implement, by the time rustdoc resolves intra-doc links we've lost the lexical scope and we're left with only the DefId (resolution scope): https://github.com/rust-lang/rust/blob/master/src/librustdoc/passes/collect_intra_doc_links.rs#L428

**Comment by Lokathor** [comment]
Well if it can't be done it's ultimately fine, it just hit me as a weird detail on a crate that has many macros which must be kept in many separate files.

**Comment by jyn514** [comment]
> I'm not sure how feasible it is to implement, by the time rustdoc resolves intra-doc links we've lost the lexical scope and we're left with only the DefId 

After #77519 this is no longer true; I don't think we currently store the scope if it's not a re-exports, but it shouldn't be too hard to add. So this changes to a question of whether we _should_ change it.

@Manishearth what do you think?

**Comment by Manishearth** [comment]
@jyn514 I don't have a strong opinion here

**Comment by jhpratt** [comment]
Not sure if this is related, but when reëxporting a macro from another crate, the path isn't always correct _even when explicitly specified_. I have the macros exported through both the `macros` and `prelude` modules, but only have it documented in the former (the latter is a reëxport of the former, but documentation doesn't indicate it as such?). As rustdoc doesn't get the right path during the documentation of the contents of the `macro` module, I added an explicit `` [`time!`]: crate::macros::time `` in an attempt to get it to resolve correctly; unfortunately it still resolves to the already-wrong documentation in the prelude module.

Ultimately this is probably just a problem with macros 1.0 in general, and the newer (unstable) macro syntax and path handling might already have this handled correctly.

**Comment by jyn514** [comment]
@jhpratt I'm not 100% following - can you make an MCVE?

**Comment by jhpratt** [comment]
@jyn514 I'm a bit busy currently, but [this chunk of code](https://github.com/time-rs/time/blob/v0.3/src/lib.rs#L282-L297) is where it's necessary.

**Comment by jyn514** [comment]
> Not sure if this is related, but when reëxporting a macro from another crate, the path isn't always correct _even when explicitly specified_. I have the macros exported through both the `macros` and `prelude` modules, but only have it documented in the former (the latter is a reëxport of the former, but documentation doesn't indicate it as such?). As rustdoc doesn't get the right path during the documentation of the contents of the `macro` module, I added an explicit `` [`time!`]: crate::macros::time `` in an attempt to get it to resolve correctly; unfortunately it still resolves to the already-wrong documentation in the prelude module.
> 
> Ultimately this is probably just a problem with macros 1.0 in general, and the newer (unstable) macro syntax and path handling might already have this handled correctly.

@jhpratt and I found that this was actually https://github.com/rust-lang/rust/issues/77193 and not related to macros at all; it's fixed on nightly.

**Comment by jyn514** [comment]
Since intra-doc links are already stable, and since this is following the same rules of the language, we do not plan to change the behavior here.

**Comment by ChrisDenton** [comment]
In that case, is there a way to force linking to a macro in a specific path instead of resolving to the crate root? I'm finding it makes some docs weird when the text says one thing but the link goes somewhere else.
