### ISSUE TITLE
windows-gnu target compatibility with toolchains providing LLVM tools only

### ISSUE THREAD

**Issue by mati865** [rust-lang/rust#72241]
Rust currently assumes all GNU libraries and tools are present. This is not the case when using LLVM only toolchains like this one: https://github.com/mstorsjo/llvm-mingw

Remaining issues:
- [x] LLD doesn't work with version-scripts (https://github.com/rust-lang/rust/pull/72049)
- [ ] Rust explicitly links `libgcc`, `libgcc_eh`, `libgcc_s`

Opening the issue so interested people can track it easily.

**Comment by mati865** [comment]
cc @petrochenkov for the second issue, we just need possibility of providing custom `late_link_args_dynamic` and `late_link_args_static`.

**Comment by petrochenkov** [comment]
@mati865 
Do you mean ability to pass `-C link-args-dynamic` / `-C link-args-static` on the command line in addition to the target spec, or ability to drop the target spec args and start from scratch with regular `-C link-args`?

**Comment by mati865** [comment]
@petrochenkov in this specific case we need to replace `libgcc` with `compiler-rt` and `libgcc_eh` or `libgcc_s` with `libunwind`. `late_link_args` hopefully could be left intact but I have to verify that.
Adding new target would do the trick but it might be an overkill if things can work with existing target.

**Comment by petrochenkov** [comment]
So, I think this is a job for `#[link(cfg(...))]` (if we want to avoid a new target).

One `cfg` feature is provided by the compiler and allows to discern between the `link_args_dynamic` and `link_args_static` at link time.

Another `cfg` feature is a regular cargo feature of the `src/libunwind` crate which allows to switch between "LLVM toolchain" (`compiler-rt` + `libunwind`) and "GCC toolchain" (`libgcc` + `libgcc_eh`).

Then https://github.com/rust-lang/rust/commit/8e3467c2150eddc636e88346255bec20feb38b3a is reverted and all the linking is done through `#[link]` attributes in `src/libunwind`.

```rust
#[link(name = "gcc_s", cfg(all(rustc_detect_dynamic, gcc_toolchain)))]
#[link(name = "gcc_eh", cfg(all(not(rustc_detect_dynamic), gcc_toolchain)))]
#[link(name = "unwind", cfg(not(gcc_toolchain)))]
extern {}
```
or something.

**Comment by petrochenkov** [comment]
This way we'll eliminate `late_link_args_(dynamic,static)` stuff from target specs which felt like a hack to me since its introduction.

Before https://github.com/rust-lang/rust/commit/8e3467c2150eddc636e88346255bec20feb38b3a `#![no_std]` programs (or rather programs not depending on `src/libunwind`) didn't link to the exception support libraries, which seems like the right thing to me.

With these options moved to the target spec they apply to all programs, even no-std ones.
(In this sense any libraries linked from target specs seem at least suspicious.)

**Comment by mati865** [comment]
I've tried similar approach in https://github.com/rust-lang/rust/pull/71001
That makes i686 executables depend on having `libgcc_s-dw2-1.dll` (or `libunwind.dll`) either in PATH or next to them.

I wanted to avoid new target if possible because we will definitely need new target to allow linking with UCRT instead of MSVCRT since one cannot mix libraries build with UCRT and MSVCRT.
C/C++ toolchains using UCRT already exists in the wild and I'm already being asked when it'll be possible to use Rust built libraries with them.

**Comment by petrochenkov** [comment]
#71001 didn't use `cfg(rustc_detect_dynamic)` proposed in https://github.com/rust-lang/rust/issues/72241#issuecomment-633053281 though.
With it executables won't depend on `gcc_s`.

**Comment by mati865** [comment]
Wait, so we can use features here not only when building std but also when building user code? :open_mouth:

**Comment by petrochenkov** [comment]
@mati865 
Yes, `cfg`s in `#[link]` are serialized into crate metadata "as is" and evaluated only when the final binary is build.
That's how `cfg(target_feature = "crt-static")` works, for example.

**Comment by petrochenkov** [comment]
cc https://github.com/rust-lang/rust/issues/72510

**Comment by nu8** [comment]
I ran into this today, trying to use this:

<https://github.com/alexcrichton/curl-rust>

First it gave me this:

~~~
C:\Rust\lib\rustlib\x86_64-pc-windows-gnu\lib\
libbacktrace_sys-3406edf851ec7a23.rlib(fileline.o):
fileline.c:(.text$snprintf.constprop.0+0x20): undefined reference to
`__ms_vsnprintf'
~~~

Which I solved with:

~~~ps1
$env:RUSTFLAGS = '-lmsvcrt-os'
~~~

Then it gave me this:

~~~
/build/mingw-w64/mingw-w64-crt/build-x86_64/../crt/charmax.c:19: undefined
reference to `__imp___lconv_init'
~~~

Which I solved with:

~~~ps1
$env:RUSTFLAGS = '-lmingw32 -lmsvcrt-os'
~~~

Finally I get this:

~~~
C:\Rust\lib\rustlib\x86_64-pc-windows-gnu\lib\
libbacktrace_sys-3406edf851ec7a23.rlib(fileline.o):
fileline.c:(.text$__rdos_backtrace_pcinfo+0x1a1): undefined reference to
`getpid'
~~~

which I dont know how to solve. It seems this should be something thats possible
as I have personally compiled cURL itself using LLVM-MinGW. So C cURL works, but
not Rust cURL.

**Comment by petrochenkov** [comment]
@nu8 
I've seen the `__ms_vsnprintf` error a few days ago when building rustc using gcc toolchain (https://packages.msys2.org/package/mingw-w64-x86_64-gcc).
So it seems like it isn't specific to LLVM toolchain, some recent changes just broke mingw in general.

**Comment by mati865** [comment]
No it's not specific to LLVM at all.
This error happens when you mix UCRT and MSVCRT and the only solution for it is to never mix different CRTs.
Rust doesn't provide UCRT based toolchain (I mentioned it in https://github.com/rust-lang/rust/issues/72241#issuecomment-633069440). For that to happen we need more recent mingw-w64 and maybe even built to target UCRT by default.

> I've seen the __ms_vsnprintf error a few days ago when building rustc using gcc toolchain (https://packages.msys2.org/package/mingw-w64-x86_64-gcc) (so I had to switch to msvc).

@petrochenkov few days ago MSYS2 upgraded mingw-w64 and it broke winpthreads library. Fix was committed on the next day I think.

Issue described by @nu8 is caused by using toolchain from `llvm-mingw` project.
That toolchain is using LLVM only tools and targets UCRT. either of those can cause build to fail because neither is currently supported by Rust.

**Comment by mati865** [comment]
@petrochenkov I reproduced your issue by upgrading mingw-w64 among the other packages...
That's because MinGW doesn't seem to have stable order of it's linkage.

Currently Rust does it this way: https://github.com/rust-lang/rust/blob/64ad709ad4d2863b7995d8b9e90a1bedb7d0ccf1/src/librustc_target/spec/windows_gnu_base.rs#L20-L38

Now compare it to GCC which adjusts their list as need, last adjustment happened 2 weeks ago in https://github.com/gcc-mirror/gcc/commit/850533ab160ef40eccfd039e1e3b138cf26e76b8.
Interesting parts of `gcc hello.c -###`:
`-lmingw32 -lgcc -lgcc_eh -lmoldname -lmingwex -lmsvcrt -lkernel32 -lpthread -ladvapi32 -lshell32 -luser32 -lkernel32 -lmingw32 -lgcc -lgcc_eh -lmoldname -lmingwex -lmsvcrt -lkernel32`

Clang solves it by using `--start-group` and `--end-group` around mingw-w64 libs.
Interesting parts of `clang hello.c -###`:
`-lmingw32 -lgcc -lgcc_eh -lmoldname -lmingwex -lmsvcrt -lpthread -ladvapi32 -lshell32 -luser32 -lkernel32 -lmingw32 -lgcc -lgcc_eh -lmoldname -lmingwex -lmsvcrt`

At this point I don't know whether Rust should:
- follow GCC by adjusting that list everytime something breaks,
- follow Clang and use `--start-group- and `--end-group` (there is performance hit here)
- say "I'm out of this mess" by setting `no_default_libraries` to `true` and letting the linker handle it

I'm currently looking for workaround to make `stage0` std build...

**Comment by petrochenkov** [comment]
>follow GCC by adjusting that list everytime something breaks

Hmm,  shouldn't it be possible to make a "union" list that would work both pre- and post-https://github.com/gcc-mirror/gcc/commit/850533ab160ef40eccfd039e1e3b138cf26e76b8 by passing some libraries multiple times?
Which would be similar to what linker does with `--(start,end)-group`, except that we would be doing it manually.

`--(start,end)-group` would make it harder to move these libraries to `#[link]` attributes in `libc` or `libstd` crates from the target spec, which would be nice to do because it's more in line with what other targets do.

**Comment by mati865** [comment]
That seems to do the trick for now:
```diff
index f556bf03f02..744f26239ca 100644
--- a/src/librustc_target/spec/windows_gnu_base.rs
+++ b/src/librustc_target/spec/windows_gnu_base.rs
@@ -20,9 +20,9 @@ pub fn opts() -> TargetOptions {
     late_link_args.insert(
         LinkerFlavor::Gcc,
         vec![
+            "-lmsvcrt".to_string(),
             "-lmingwex".to_string(),
             "-lmingw32".to_string(),
-            "-lmsvcrt".to_string(),
             // mingw's msvcrt is a weird hybrid import library and static library.
             // And it seems that the linker fails to use import symbols from msvcrt
             // that are required from functions in msvcrt in certain cases. For example
```
For stage0 to work you can Rust with `RUSTFLAGS_BOOTSTRAP='-C link-arg=-lmsvcrt' ./x.py build`.

Generally GCC passes unnecessary libs like totally empty `-lmoldname`.
It would be nice if there was a tool to create dependency graph for import/static libraries so we could confidently choose the order instead of current "let's see if that order works".

**Comment by nu8** [comment]
> It would be nice if there was a tool to create dependency graph for
> import/static libraries so we could confidently choose the order instead of
> current "let's see if that order works".

With GCC, I always have to mess with the order, to the point I do stuff like
this:

~~~
cc a.c \
-lsunday \
-lmonday \
-DA1 \
-ltuesday \
-DA2 \
-lwednesday
~~~

Where `-DA1` and similar are just dummy markers, so that I know for each group
I can put the items in any order, but not to change the order of the "groups".
However with Clang, at least with this version:

https://github.com/mstorsjo/llvm-mingw

I havent had to do that at all. I think Clang uses this:

https://github.com/Z3Prover/z3

to resolve the Libraries. Maybe that brings some overhead, but Clang seems about
30% faster to me as well.

**Comment by mati865** [comment]
@nu8 

> However with Clang, at least with this version:
>
> mstorsjo/llvm-mingw
>
> I havent had to do that at all.

Maybe it uses `--start-group` and `--end-group` implicitly for user libraries?

> I think Clang uses this:
>
> http://theory.stanford.edu/~nikolaj/programmingz3.html
>
> to resolve the Libraries.

MSYS2 ships LLVM with z3, `llvm-mingw` builds it without that.

> Maybe that brings some overhead, but Clang seems about
30% faster to me as well.

It depends on the use case but Clang is often just faster than GCC.

**Comment by mati865** [comment]
Opened https://github.com/rust-lang/rust/pull/73184 for building Rust.

**Comment by mati865** [comment]
> I wanted to avoid new target if possible because we will definitely need new target to allow linking with UCRT instead of MSVCRT since one cannot mix libraries build with UCRT and MSVCRT.

Okay, seems like this will need separate target (GCC's emutls vs Clang's native TLS is a good example).
Instead we could avoid creating separate MSVCRT vs UCRT targets for each compiler until somebody needs them. Windows-gnu would keep MSVCRT as the default and new MinGW clang toolchain would use UCRT.

Should I close this issue and open another one or MCP for the new target?

**Comment by mstorsjo** [comment]
> > However with Clang, at least with this version:
> > mstorsjo/llvm-mingw
> > I havent had to do that at all.
> 
> Maybe it uses `--start-group` and `--end-group` implicitly for user libraries?

As LLD's COFF backend is modelled after MS link.exe, it handles static libs in the same way as that tool, which means that it looks in all referenced static libs for undefined references - pretty much as if `--start-group`/`--end-group` was wrapped around the full list of arguments. (And Clang passes those arguments around the libs to the linker, to solve that issue when using ld.bfd as well.)

> > I think Clang uses this:
> > http://theory.stanford.edu/~nikolaj/programmingz3.html
> > to resolve the Libraries.
> 
> MSYS2 ships LLVM with z3, `llvm-mingw` builds it without that.

Z3 is entirely unrelated to linking. A quick grep through the source tree would point to it being used by the clang static analyzer, possibly...

> > Maybe that brings some overhead, but Clang seems about
> > 30% faster to me as well.
> 
> It depends on the use case but Clang is often just faster than GCC.

In my experience, Clang isn't that fast in itself any longer, it's often similar to GCC or slower, for compilation. But for linking, LLD is often an order of magnitude faster than ld.bfd. This is especially noticable for large C++ projects - see e.g. https://bugs.llvm.org/show_bug.cgi?id=42217#c17, where a user said "I can finally link my project with lld. This reduces link time from ~26s to ~1s. Amazing!"

**Comment by 89z** [comment]
https://github.com/mstorsjo/llvm-mingw/issues/263

**Comment by kleisauke** [comment]
@mati865 Thanks for adding these `*-pc-windows-gnullvm` targets! I was wondering if there is also interest in the `i686-pc-windows-gnullvm` and `armv7-pc-windows-gnullvm` targets? If so, I could try to upstream these patches:
https://github.com/libvips/build-win64-mxe/blob/4ddf96c4c152f129d320d27fcf11ade9f9f73e65/build/plugins/llvm-mingw/patches/rust-1-fixes.patch
https://github.com/libvips/build-win64-mxe/blob/4ddf96c4c152f129d320d27fcf11ade9f9f73e65/build/patches/librsvg-llvm-mingw.patch#L82-L224

(I'm able to test the (unusual) `armv7-pc-windows-gnullvm` target on my Raspberry Pi 3B with Windows 10 IoT, if necessary)

**Comment by mati865** [comment]
@kleisauke sorry, thought I had already anwsered here.
32-bit LLVM targets are blocked right now on having working unwinding. It doesn't manifest right away when cross-compilling but prevents bootstrapping Rust natively.

**Comment by tschuett** [comment]
LLVM (https://github.com/llvm/llvm-project/blob/main/llvm-libgcc/docs/LLVMLibgcc.rst) hosts theses strange:
libgcc, libgcc_eh, libgcc_s
files.

**Comment by mati865** [comment]
I doubt it helps in any way. Implementation details for Windows Dwarf 2 between libgcc and libunwind differ a lot and that library doesn't seem to take it into account.

**Comment by mstorsjo** [comment]
> LLVM (https://github.com/llvm/llvm-project/blob/main/llvm-libgcc/docs/LLVMLibgcc.rst) hosts theses strange:
> libgcc, libgcc_eh, libgcc_s
> files.

They're not really of any value for this setup. Those files are used for letting libunwind (and compiler-rt) fill the gap where preexisting binaries on Linux have a dependency on e.g. `libgcc_s.so`, to make libunwind and compiler-rt, which provide the same symbols, provide a library interface for ABI compatibility.
