### ISSUE TITLE
No definition of lexicographic order in docs for `Iterator::cmp*`

### ISSUE THREAD

**Issue by brmmm3** [rust-lang/rust#72255]
It seems that the comparison functions are not correctly implemented.

I tried this code:

```rust
use std::cmp::Ordering;

assert_eq!([1].iter().cmp([1, 2].iter()), Ordering::Less);
assert_eq!([1, 2].iter().cmp([1].iter()), Ordering::Greater);
```

I expected to see this happen:
The code above should panic. The reason is: 1 is NOT less than 1 and 1 is NOT greater than 1.
What I'm missing in Ordering are LessOrEqual and GreaterOrEqual. If these 2 objects would exist I could write:

```rust
use std::cmp::Ordering;

assert_eq!([1].iter().cmp([1, 2].iter()), Ordering::LessOrEqual);
assert_eq!([1, 2].iter().cmp([1].iter()), Ordering::GreaterOrEqual);
```

which would correct not panic.

### Meta
I've tried this in Rust Playground with stable and nightly.

**Comment by ecstatic-morse** [comment]
Quoth [the docs](https://en.cppreference.com/w/cpp/algorithm/lexicographical_compare) for the C++ standard library (emphasis mine
> Lexicographical comparison is a operation with the following properties:
> - Two ranges are compared element by element.
> - The first mismatching element defines which range is lexicographically less or greater than the other.
> - **If one range is a prefix of another, the shorter range is lexicographically less than the other.**
> - If two ranges have equivalent elements and are of the same length, then the ranges are lexicographically equal.
> - An empty range is lexicographically less than any non-empty range.
> - Two empty ranges are lexicographically equal. 

We should probably define lexicographical order wherever the term is used in the standard library documentation.

**Comment by ecstatic-morse** [comment]
To resolve this, you can either write a definition of lexicographical order somewhere in the rust documentation or link to an easily understandable source. Then link to that definition wherever "lexicographical" appears in the source.

**Comment by softwaredeveloptam** [comment]
Hi I would like to take this on as a first issue if that's okay. 
@rustbot claim

**Comment by Alexendoo** [comment]
Triage: Hi, are you still working on this issue @softwaredeveloptam?

**Comment by softwaredeveloptam** [comment]
Hey there, @Alexendoo I got pretty busy and it slipped my mind, but will give it a shot this week!

**Comment by Rustin-Liu** [comment]
I am working on this.
@rustbot claim
