### ISSUE TITLE
Eliminate `const_field` query

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#72264]
Followup to https://github.com/rust-lang/rust/pull/67901

I think we only have one use site of `const_field` left: https://github.com/rust-lang/rust/blob/7f65393b9abf5e70d0b9a8080558f17c5625bd40/src/librustc_codegen_ssa/mir/constant.rs#L69 and it iterates over all fields anyway. So we can call `destructure_const` instead and iterate over the resulting fields.

There should be no more results for searching `const_field` in the rust source after this, so some comments may need updating to mentioning `destructure_const` instead of `const_field`.

These mentoring instructions are a bit vague, I do realize that, so if you encounter any hickup of any magnitude, don't hesitate to write here or contact me via discord/zulip.

This issue has been assigned to @rakshith-ravi via [this comment](https://github.com/rust-lang/rust/issues/72264#issuecomment-629656984).

**Comment by RalfJung** [comment]
> `destructure_const`

I don't think "destructure" is a word. The term I have seen for that (and the term that is commonly used for this operation in the theorem prover community) is "destruct".
