### ISSUE TITLE
Unhelpful message for syntax error in pattern bindings

### ISSUE THREAD

**Issue by benschulz** [rust-lang/rust#72298]
When changing a pattern binding from something like

```rust
match some_value {
    SomeEnum::SomeVariant { ref some_field } => { /* do something with some_field */ },
    _ => {}
}
```

to something like

```rust
match some_value {
    SomeEnum::SomeVariant { some_field: ref alias } => { /* do something with alias */ },
    _ => {}
}
```

it's easy to end up with

```rust
match some_value {
    SomeEnum::SomeVariant { ref some_field: alias } => { /* do something with alias */ },
    _ => {}
}
```

which yields an unhelpful syntax error message ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=09095874891f43440d7921d06f3cff2b)). I don't believe it's obvious why `ref some_field` and `some_field: alias` are valid, but `ref some_field: alias` is not. The same holds for `ref mut` bindings, of course.

It would be nice if rustc's parser accepted the invalid syntax and provided one of its helpful "did you mean to write `some_field: ref alias`?" error messages.

**Comment by estebank** [comment]
Current output:

```
error: expected `,`
  --> src/main.rs:13:47
   |
13 |         SomeEnum::SomeVariant { ref some_field: alias } => { /* do something with alias */ }
   |         ---------------------                 ^
   |         |
   |         while parsing the fields for this pattern
```
