### ISSUE TITLE
Tracking Issue for feature `future_poll_fn`

### ISSUE THREAD

**Issue by yoshuawuyts** [rust-lang/rust#72302]
The feature gate for the issue is `#![feature(future_poll_fn)]`.

### Steps

- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR (#99306)

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Unresolved Questions

- Should this be named `future::from_fn` instead?

### Implementation history

- Initial implementation in https://github.com/rust-lang/rust/pull/72303
- ~~Rename from `future::poll_fn` to `future::from_fn` in https://github.com/rust-lang/rust/pull/76789~~
  - closed as it's ambiguous, see the discussion on that PR

**Comment by LukasKalbertodt** [comment]
I have basically no experience with async APIs and don't feel qualified to judge if this rename is good or not. I will reassign to @dtolnay as they reviewed the original PR:

r? @dtolnay

**Comment by RalfJung** [comment]
There are some soundness issues with `poll_fn` as is (not strictly speaking a soundness bug, but we might still want to do a breaking change now before there are too many people relying on this): the fact that `PollFn<F>` is always `Unpin` is a problem. It should require `F: Unpin` for that.

See [IRLO](https://internals.rust-lang.org/t/surprising-soundness-trouble-around-pollfn/17484/14) for details.

**Comment by RalfJung** [comment]
I am proposing to change the `Unpin` impl in https://github.com/rust-lang/rust/pull/102737.
