### ISSUE TITLE
Documentation of the From<String> impl for OsString misleading

### ISSUE THREAD

**Issue by smarnach** [rust-lang/rust#72349]
The [documentation of `From<String>` for `OsString`][1] reads

[1]: https://doc.rust-lang.org/std/ffi/struct.OsString.html#impl-From%3CString%3E

> Converts a `String` into a `OsString`.
>
> The conversion copies the data, and includes an allocation on the heap.

The implementation is platform-specific, but from a quick glance none of the implementations I looked at does seem to actually copy the data.

The [documentation of `From<String>` for `PatBbuf`][2] reads

[2]: https://doc.rust-lang.org/std/path/struct.PathBuf.html#impl-From%3CString%3E

> Converts a `String` into a `PathBuf`
>
> This conversion does not allocate or copy memory.

It is implemented using `OsString::from::<String>`:

    fn from(s: String) -> PathBuf {
        PathBuf::from(OsString::from(s))
    }

So clearly something is off here. Even when all current implementations of the `String` to `OsString` conversion avoid copying, the documentation does not necessarily need to commit to this property, but neither should it state that the implementation allocates and copies if it actually doesn't.

**Comment by ChrisDenton** [comment]
This was fixed by #83700.
