### ISSUE TITLE
Adding AtomicF64, AtomicF32 to std::sync::atomic

### ISSUE THREAD

**Issue by rustrust** [rust-lang/rust#72353]
Currently there is no AtomicF64, AtomicF32, or AtomicF16 type in std::sync::atomic.

Since people will likely increasingly look to write numeric code in rust, as const generics will be arriving, it would probably make sense to include atomic float types.

**Comment by jonas-schievink** [comment]
Can you name a few use cases of atomic operations on floats? Which architectures support them?

(also, `f16` does not exist in the language, so `AtomicF16` seems unimplementable to me)

**Comment by Mark-Simulacrum** [comment]
See also https://github.com/rust-lang/rust/issues/68614 - but I think this isn't really all that feasible today.

**Comment by rustrust** [comment]
Use cases would be various statistics, signal processing, vision, scientific computing, etc applications where you want to have multiple threads have highly random access to a large Vec/array/etc and do a lot of simultaneous writes.

**Comment by dtolnay** [comment]
A use case from my work codebase: a fuzzy matching / scoring element of a search algorithm that needs to update a shared score value from multiple threads using `compare_exchange`.

```rust
let min_score: Arc<AtomicF32>;
```

**Comment by John-Nagle** [comment]
What happened with this? Seemed reasonable.
There is a crate, "atomic-float", but it only has 80 downloads.

**Comment by Amanieu** [comment]
We discussed this on the libs meeting today. Currently, hardware support for float atomics only exists on GPU targets (CUDA & AMDGPU). On all other targets, you can perform atomic operations on floats by using `to_bits` and `from_bits` with `compare_exchange`. Unless there is a compelling use case for exposing float atomic support (e.g. someone is actually using them on GPU targets) then we prefer not adding these for now.

**Comment by Venryx** [comment]
For others looking for a short implementation of the approach mentioned above (of using `AtomicU64` along with `to_bits` and `from_bits`), here is the helper struct I'm using:
```rust
pub struct AtomicF64 {
    storage: AtomicU64,
}
impl AtomicF64 {
    pub fn new(value: f64) -> Self {
        let as_u64 = value.to_bits();
        Self { storage: AtomicU64::new(as_u64) }
    }
    pub fn store(&self, value: f64, ordering: Ordering) {
        let as_u64 = value.to_bits();
        self.storage.store(as_u64, ordering)
    }
    pub fn load(&self, ordering: Ordering) -> f64 {
        let as_u64 = self.storage.load(ordering);
        f64::from_bits(as_u64)
    }
}
```
