### ISSUE TITLE
Why not single executable?

### ISSUE THREAD

**Issue by altaway** [rust-lang/rust#72363]
Golang uses just one executable for everything (`go`, ignoring `gofmt`), whereas rust uses three (`rustup`, `cargo` and `rustc`).

Why not integrate the three? It looks like `cargo` does virtually everything `rustc` does. Why not incorporate `rustup` into `cargo` or something like that?

**Comment by jonas-schievink** [comment]
Hi! This issue tracker is mainly meant for bug reports and concrete, small feature requests. Questions like this are better asked in the user forum at https://users.rust-lang.org/ or on [one of the chat platforms](https://www.rust-lang.org/community) used by the Rust community.

**Comment by altaway** [comment]
Alright, sorry.
