### ISSUE TITLE
Rustdoc doc_cfg feature fails to find items behind a feature flag

### ISSUE THREAD

**Issue by Michael-F-Bryan** [rust-lang/rust#72370]
I'm playing around with rustdoc's [*Documenting platform-/feature-specific information*](https://doc.rust-lang.org/rustdoc/unstable-features.html#documenting-platform-feature-specific-information) feature (`#![feature(doc_cfg)]`) and found `rustdoc` fails to compile when documenting an item which uses something from a dependency which is also behind a feature flag.

The problem is that rustdoc "somehow" needs to know to include a dependency when resolving items, even though it won't actually be compiled in the current build.

Are there any workarounds I can use in the meantime? This also feels like something `rustdoc` could try to resolve itself, seeing as `#[doc(cfg(...))]` is intended for code which will only work with a particular feature flag.

## Steps to Reproduce

This crate has a `special-feature` feature flag which will conditionally pull in
`libc`. When the feature is enabled, it also includes a `platform_specific.rs`
module which uses items from `libc` (`libc::c_int`, to be precise).

The `Cargo.toml`:

```toml
# Cargo.toml

[package]
name = "repro"
version = "0.1.0"
authors = ["Michael Bryan <michaelfbryan@gmail.com>"]
edition = "2018"

[dependencies]
libc = { version = "0.2.70", optional = true }

[features]
default = []
special-feature = ["libc"]
```

The library's entrypoint:

```rust
// src/lib.rs

#[doc(cfg(feature = "special-feature"))]
#[cfg(any(feature = "special-feature", doc))]
pub mod platform_specific;
```

Our platform-specific code:

```rust
// src/platform_specific.rs

use libc::c_int;

pub fn foo(_: c_int) {}
```

The code compiles fine with and without the feature flag.

```command
$ cargo build
   Compiling repro v0.1.0 (C:\Users\mbryan\AppData\Local\Temp\repro)
    Finished dev [unoptimized + debuginfo] target(s) in 0.34s
$ cargo build --features special-feature
   Compiling libc v0.2.70
   Compiling repro v0.1.0 (C:\Users\mbryan\AppData\Local\Temp\repro)
    Finished dev [unoptimized + debuginfo] target(s) in 2.51s
```

However, running `cargo doc` without `--features special-feature` now fails
with an import error.

```command
$ cargo doc
 Documenting repro v0.1.0 (C:\Users\mbryan\AppData\Local\Temp\repro)
error[E0432]: unresolved import `libc`
 --> src\platform_specific.rs:1:5
  |
1 | use libc::c_int;
  |     ^^^^ help: a similar path exists: `std::libc`

error: Compilation failed, aborting rustdoc

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0432`.
error: Could not document `repro`.

Caused by:
  process didn't exit successfully: `rustdoc --edition=2018 --crate-type lib --crate-name repro src\lib.rs -o C:\Users\mbryan\AppData\Local\Temp\repro\target\doc --cfg "feature=\"default\"" --error-format=json --json=diagnostic-rendered-ansi -L dependency=C:\Users\mbryan\AppData\Local\Temp\repro\target\debug\deps` (exit code: 1)
```

Version info:

```console
$ rustc --version --verbose
rustc 1.43.0-nightly (2c462a2f7 2020-02-20)
binary: rustc
commit-hash: 2c462a2f776b899d46743b1b44eda976e846e61d
commit-date: 2020-02-20
host: x86_64-pc-windows-msvc
release: 1.43.0-nightly
LLVM version: 9.0

$ cargo --version --verbose
cargo 1.43.0-nightly (e02974078 2020-02-18)
release: 1.43.0
commit-hash: e02974078a692d7484f510eaec0e88d1b6cc0203
commit-date: 2020-02-18

$ rustdoc --version --verbose
rustdoc 1.43.0-nightly (2c462a2f7 2020-02-20)
binary: rustdoc
commit-hash: 2c462a2f776b899d46743b1b44eda976e846e61d
commit-date: 2020-02-20
host: x86_64-pc-windows-msvc
release: 1.43.0-nightly
LLVM version: 9.0
```

**Comment by Nemo157** [comment]
That looks correct, you are using `cfg(doc)` to include the module when building without the feature active, which means the optional dependency is not available (`cfg(doc)` doesn't have anything to do with `doc(cfg)`, the latter only adds extra metadata to the generated documentation and doesn't affect the "compilation" of the code).

**Comment by Michael-F-Bryan** [comment]
Thanks @Nemo157, that makes sense. Can you think of any workarounds which would let us document an API which relies on items not included in the current compilation?

**Comment by Nemo157** [comment]
The standard solution I see is to use `cargo doc --features special-feature` and not use `cfg(doc)` anywhere (which you can also [configure on docs.rs](https://docs.rs/about/metadata)). Alternatively you could have a "mock" of the dependency defined when using `cfg(all(doc, not(feature = "special-feature")))` providing just enough to allow type-checking to succeed.

**Comment by Michael-F-Bryan** [comment]
I'm closing this ticket because rustdoc is working exactly as intended.
