### ISSUE TITLE
Implement `Sync` for `process::Command`

### ISSUE THREAD

**Issue by jonhoo** [rust-lang/rust#72387]
`std::process::Command` is currently `Send`, but not `Sync`. While `Sync` probably isn't super useful for `Command` itself, it does mean that any type that wraps a `process::Command` _also_ isn't `Sync` even if it might be useful on that type.

`Command` currently has a manual `impl Send` following https://github.com/rust-lang/rust/pull/47760 (issue https://github.com/rust-lang/rust/issues/47751), though from the discussion on [users.r-l.o](https://users.rust-lang.org/t/would-it-be-possible-for-std-process-command-to-be-send/15254/4), it sounds like a manual `impl Sync` would also be sound. @cuviper not sure if that still holds?

If it does, this seems like a worthwhile `impl` to add, simply for the auto-trait implications.

**Comment by jonhoo** [comment]
To give one example of where this crops up: `tokio::process::Command` currently isn't `Sync` because `std::process::Command` isn't `Sync`. This _also_ means that any `async fn` that _uses_ `tokio::process::Command` is not `Sync`. Again, the ramifications of that probably aren't too severe (how important is it that a `Future` is `Sync`?), but it does lead to some annoyance when trying to use that future with libraries that just stick `Send + Sync` bounds wherever to get rid of compiler errors :sweat_smile:

**Comment by cuviper** [comment]
As with `Send`, I think it's just the `argv` that isn't `Sync`, but that should be fine to add.
