### ISSUE TITLE
Cargo hello run for test

### ISSUE THREAD

**Issue by Alirxa** [rust-lang/rust#72418]
```rust


fn main() {
    println!("Hello, world!");
    println!("Hello PIAIC");
}
```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=eda1b9652e8ddeeeaad3e6471f5e6ee7))

Output:

```
Hello, world!
Hello PIAIC

```

Errors:

```
   Compiling playground v0.0.1 (/playground)
    Finished dev [unoptimized + debuginfo] target(s) in 0.40s
     Running `target/debug/playground`

```

**Comment by Elinvynia** [comment]
What is the reported issue here?

**Comment by jonas-schievink** [comment]
I guess someone is holding some online mentorship program and is directing people to the Rust issue tracker to post their solutions again. This is the second time this has happened. Please don't do this.
