### ISSUE TITLE
sort_by_cached_key incorrectly documented as stable sort

### ISSUE THREAD

**Issue by Voultapher** [rust-lang/rust#72420]
The documentation for [`sort_by_cached_key`](https://doc.rust-lang.org/std/primitive.slice.html#method.sort_by_cached_key) claims both it is stable and using pdqsort. My understanding is it can be either one of them. Not both.

**Comment by nikic** [comment]
The documentation is correct. The pdqsort is applied to a vector of key/index pairs, which are never equal (the index distinguishes equal keys), as such the stability of the underlying sort does not matter, the result will always be stable.

**Comment by Voultapher** [comment]
Good to know, might be helpful for future readers to add a note about that to the docs. Closing now, because not a bug.
