### ISSUE TITLE
Stabilize core::panic::Location::caller

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust#72448]
The lang FCP for `#[track_caller]` is happening in https://github.com/rust-lang/rust/pull/72445. This is a libs FCP for https://doc.rust-lang.org/nightly/std/panic/struct.Location.html#method.caller which is under the same feature gate and required for making use of `#[track_caller]` in library code.

Refer to @anp's [stabilization report](https://github.com/rust-lang/rust/pull/72445#issue-421643817) and the [method's example code](https://doc.rust-lang.org/nightly/std/panic/struct.Location.html#method.caller).

In particular:

- The return type is `&'static Location<'static>` which resembles the return type of [std::panic::PanicInfo::location](https://doc.rust-lang.org/nightly/std/panic/struct.PanicInfo.html#method.location) (`Option<&'a Location<'a>>`) but static and non-optional.

- The location points to the outermost call site not inside of a `#[track_caller]` function.

```rust
#[track_caller]
fn f() -> &'static Location<'static> {
    Location::caller()
}

fn g() -> &'static Location<'static> {
    f() /*
    ^ calling g() gives a location whose file()/line()/column() point to here
        */
}
```

@rust-lang/libs

**Comment by dtolnay** [comment]
@rfcbot fcp merge

**Comment by Aaron1011** [comment]
Was a decision ever reached on https://github.com/rust-lang/rust/issues/69977? It's currently impossible to determine which method call in a chain (e.g. `foo.a().b().c()` is the actual caller, since a call from any of them will cause `Location::caller` to point to the beginning of the call chain.

**Comment by Aaron1011** [comment]
> and required for making use of `#[track_caller]` in library code.

That's only true if a library wants to programatically inspect the caller, right? It's possible to use `#[track_caller]` only for its effect on panicking, which doesn't require libraries to use `Location::caller`

**Comment by anp** [comment]
> Was a decision ever reached on https://github.com/rust-lang/rust/issues/69977? It's currently impossible to determine which method call in a chain (e.g. `foo.a().b().c()` is the actual caller, since a call from any of them will cause `Location::caller` to point to the beginning of the call chain.

I don’t think any action was decided upon here. I think we can “enhance” the `Location` type with span end info separately from this feature. I can see an argument for gating stabilization on fixing the underlying issue with spans, but I’m obviously inclined to treat it as a follow up :).

**Comment by anp** [comment]
> > and required for making use of `#[track_caller]` in library code.
> 
> 
> 
> That's only true if a library wants to programatically inspect the caller, right? It's possible to use `#[track_caller]` only for its effect on panicking, which doesn't require libraries to use `Location::caller`

This is correct, for custom error types to get the improved panic messages earlier, we could stabilize the attribute separately from the intrinsic wrapper. This seems like a good option to exercise if there are concerns about this FCP which wouldn’t block the attribute from stabilizing, as it would decouple schedule pressures.

**Comment by Aaron1011** [comment]
>  I think we can “enhance” the `Location` type with span end info separately from this feature.

Does this mean that 'span start' info (currently `Location::{file, line, column}`) will always point to the start of the method chain? If so, I think it should be mentioned in the stabilization report and docs.

**Comment by SimonSapin** [comment]
Why shouldn’t each call in a chain have its own span?

**Comment by anp** [comment]
AIUI there’s a limitation in how MIR propagates spans in method chains but @eddyb should correct me.

**Comment by anp** [comment]
> > I think we can “enhance” the `Location` type with span end info separately from this feature.
> 
> Does this mean that 'span start' info (currently `Location::{file, line, column}`) will always point to the start of the method chain? If so, I think it should be mentioned in the stabilization report and docs.

I would expect that to change if the Location type became aware of span start/ends, or if MIR becomes able to more accurately provide a span start within the middle of the chain. This doesn't seem problematic to me in general but that's operating from the assumption that changes to span reporting wouldn't be breaking changes. Maybe that assumption is in error?

**Comment by Aaron1011** [comment]
Can this issue be closed now that `Location::caller()` has been stabilized?
