### ISSUE TITLE
Simple async wrapper doubles the size of a future

### ISSUE THREAD

**Issue by jimblandy** [rust-lang/rust#72454]
I'm using the following wrapper function:
```
pub async fn log_error<F>(future: F)
where
    F: Future<Output = Result<(), Box<dyn Error + Send + Sync + 'static>>>
{
    if let Err(err) = future.await {
        print_error(err);
    }
}
```

Using `std::mem::size_of_val`, the size of any future returned by this function is a bit more than twice the size of the future passed to it. This is a pretty severe penalty for a simple helper function.

**Comment by jonas-schievink** [comment]
Duplicate of https://github.com/rust-lang/rust/issues/62958
