### ISSUE TITLE
Tracking Issue for peekable_next_if

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#72480]
This is a tracking issue for the feature `peekable_next_if` (https://github.com/rust-lang/rust/pull/72310).
The feature gate for the issue is `#![feature(peekable_next_if)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also uses as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Implement the RFC
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Unresolved Questions

- Should `next_if` be named `consume_if` or `eat_if`?
- Should `next_if_eq` be named `consume` or `eat`?

**Comment by Stupremee** [comment]
I don't think the methods should be renamed to something else, becuase `Iterator` also has a `next` method, and `Peekable`
should use the same name but with the `if` component.

Also, if these questions are resolved and there are no other blockers, I would like to go ahead and stabilize this feature.
