### ISSUE TITLE
try-blocks and label-break-value do not work together.

### ISSUE THREAD

**Issue by jonhoo** [rust-lang/rust#72483]
I've been playing around with `label-break-value` today, and it comes in _super_ handy in `async` blocks. However, it seems to run into issues when combined with the `try_blocks` feature.

I tried this code:

```rust
#![feature(try_blocks, label_break_value)]

fn main() {
    let _: Result<(), ()> = try {
        'foo: {
            Err(())?;
            break 'foo;
        }
    };
}
```

I expected to see this happen: the code should compile just fine.

Instead, this happened:
```
error[E0695]: unlabeled `break` inside of a labeled block
 --> src/main.rs:6:20
  |
6 |             Err(())?;
  |                    ^ `break` statements that would diverge to or through a labeled block need to bear a label

error: aborting due to previous error
```

This is a continuation of the discussion [here](https://github.com/rust-lang/rust/issues/48594#issuecomment-632848996). As @ciphergoth [pointed out](https://github.com/rust-lang/rust/issues/48594#issuecomment-632898706), this code (following the [syntactic sugar](https://rust-lang.github.io/rfcs/2046-label-break-value.html#detailed-design) from the label-break-value RFC) compiles:

```rust
#![feature(try_blocks, label_break_value)]

fn main() {
    let _: Result<(), ()> = try {
        'foo: loop {
            break {
                Err(())?;
                break 'foo;
            }
        }
    };
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.45.0-nightly (a74d1862d 2020-05-14)
```

This issue has been assigned to @samrat via [this comment](https://github.com/rust-lang/rust/issues/72483#issuecomment-633044524).

**Comment by nikomatsakis** [comment]
So the error is generated here

https://github.com/rust-lang/rust/blob/7f940ef5d91b53e889f111f27e00849f2f5ae4a2/src/librustc_passes/loops.rs#L75-L78

if I had to guess, I would assume that this function

https://github.com/rust-lang/rust/blob/7f940ef5d91b53e889f111f27e00849f2f5ae4a2/src/librustc_passes/loops.rs#L200-L205

ought to be modified to check whether the `span.is_desugaring(QuestionMark)` and, if so, not to emit the error. (See [`is_desugaring`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_span/span_encoding/struct.Span.html#method.is_desugaring) rust docs for a bit more info.)

**Comment by nikomatsakis** [comment]
Tagged as E-mentor since there are some instructions above.
