### ISSUE TITLE
Tracking issue for `#![feature(const_float_classify)]`

### ISSUE THREAD

**Issue by ecstatic-morse** [rust-lang/rust#72505]
Tracking issue for the `#![feature(const_float_classify)]` feature gate, which makes the following methods on `f32` and `f64` `const fn`:

- `classify`
- `is_nan`
- `is_infinite`
- `is_finite`
- `is_subnormal`
- `is_normal`
- `is_sign_positive`
- `is_sign_negative`

These require #72447 (`#![feature(const_float_bits_conv)]`), so this is transitively blocked on https://github.com/rust-lang/rust/issues/57241.

**Comment by RalfJung** [comment]
https://github.com/rust-lang/rust/issues/57241 is being [proposed for stabilization](https://github.com/rust-lang/rust/pull/128596), so this feature is also finally (transitively) unblocked. :)

**Comment by dtolnay** [comment]
@rfcbot fcp merge

`const` for these 16 already-stable float methods:

- https://doc.rust-lang.org/nightly/std/primitive.f64.html#method.is_nan
- https://doc.rust-lang.org/nightly/std/primitive.f64.html#method.is_infinite
- https://doc.rust-lang.org/nightly/std/primitive.f64.html#method.is_finite
- https://doc.rust-lang.org/nightly/std/primitive.f64.html#method.is_subnormal
- https://doc.rust-lang.org/nightly/std/primitive.f64.html#method.is_normal
- https://doc.rust-lang.org/nightly/std/primitive.f64.html#method.classify
- https://doc.rust-lang.org/nightly/std/primitive.f64.html#method.is_sign_positive
- https://doc.rust-lang.org/nightly/std/primitive.f64.html#method.is_sign_negative

(and f32 likewise)
