### ISSUE TITLE
x.py has exponental resource usage with no progress

### ISSUE THREAD

**Issue by Kixiron** [rust-lang/rust#72523]
I attempted to use `x.py` with all of the following commands

```sh
$ python x.py --help
$ python x.py build -j1 --stage 1 src/libstd
$ python x.py build -i -j1 --stage 1 src/libstd
$ python x.py build -i --stage 1 src/libstd
```
but instead of doing what it's supposed to do, there was instead zero terminal output and and continuously increasing number of spawned python processes, ranging from 3827 pythons with `x.py --help` to well over 10000 pythons with `python x.py build -j1 --stage 1 src/libstd`. This number was *steadily* increasing though, I just had to kill it before my computer crashed. Killing the builds was also incredibly difficult, `ctrl+c`s do nothing, task manager crashes when it's opened and x'ing the window does nothing. The only semi-reliable way I found to kill the process was to kill every python process that was running, then `x.py` exited with still no output. On the `python x.py build -i --stage 1 src/libstd` command in particular, the spawning was so out of control that I had to restart my entire system in order to regain control.

This was the first build of rustc that I've done, so there were no prior or cached artifacts

#### Arch

Windows 10 Pro version 1909, OS build 18363.836
Python 3.7.3
The results were the same in both Powershell and CMD

#### Git

This occurred on 4774f9b523c942cb5c0236542b5bcac76f6b6b9a, but I haven't attempted to bisect for the root cause yet

#### config.toml

These were the only configuration values that I changed

```toml
[llvm]
assertions = true

[build]
verbose = 1
profiler = true

[rust]
debug = true
codegen-units = 0
debug-assertions = true
backtrace = true
parallel-compiler = true
```

**Comment by bugadani** [comment]
I have no idea if this is relevant, but according to [the book](https://doc.rust-lang.org/rustc/codegen-options/index.html#codegen-units), `codegen-units = 0` is invalid.

**Comment by Kixiron** [comment]
I believe I've found part of the problem, the shebang was doing something really weird and hiding all output. Changing the shebang in `x.py` to `#! /usr/bin/python` fixed the no-output problem perfectly

**Comment by Kixiron** [comment]
This may be partially due to the fact that on my system I have `python` as an alias to `python3`, while both `py` and `python3` both do nothing

**Comment by ratijas** [comment]
> both `py` and `python3` both do nothing

What do you mean?

**Comment by mati865** [comment]
> Changing the shebang in x.py to #! /usr/bin/python fixed the no-output problem perfectly 

That would break building inside MSYS2 (and maybe Git for Windows) shell.

> This may be partially due to the fact that on my system I have python as an alias to python3,

Maybe it doesn't like the alias?

> while both py and python3 both do nothing 

What do you mean? Runinng `python3 x.py` does nothing?

**Comment by Kixiron** [comment]
`python3` and `py` are unbound on my system

**Comment by Kixiron** [comment]
After a little investigation, it seems that `#! /usr/bin/env python` is infinitely recursing!

**Comment by ratijas** [comment]
> After a little investigation, it seems that `#! /usr/bin/env python` is infinitely recursing!

So, ultimately, it's a problem with your setup, and not in x.py or rust itself?

**Comment by Kixiron** [comment]
I guess so, closing for that reason
