### ISSUE TITLE
`x.py test` does not always support `--test-args`

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#72536]
https://github.com/rust-lang/rust/pull/72527 added support for `--test-args` for miri and clippy. But some other tools still do not support this (I am not sure if it would make sense for all of them):
* Linkcheck
* Cargotest
* Cargo
* Rustfmt
* CompiletestTest
* All the Rustdoc ones
* Tidy
* ExpandYamlAnchors
* the book tests
* RustcGuide
* Distcheck

Cc @Mark-Simulacrum

**Comment by jyn514** [comment]
> All the Rustdoc ones

I don't think this is true? `x.py test --stage 1 src/test/rustdoc --test-args intra-links` works fine for me locally.

**Comment by RalfJung** [comment]
Maybe I missed the code that implements that.

**Comment by jyn514** [comment]
I'm going to close this issue, it seems too broad. If you run into a specific tool that isn't respecting --test-args we can open an issue for that.

I do want to refactor all the test code to be consistent at some point; right now we copy paste a bunch of code in various places and it ends up with not all test suites supporting the same arguments. But that's a little different from what you have here.
