### ISSUE TITLE
rustdoc whitespace issue for nested lists

### ISSUE THREAD

**Issue by BartMassey** [rust-lang/rust#72566]
Putting the following as `src/lib.rs` and running `cargo doc --open`

```rust
//! Some text.
//! 
//! * A list.
//! 
//!    * A sublist.
//! 
//!    * Another sublist.
```

produces this render

![incorrect render](https://user-images.githubusercontent.com/117151/82805909-a5310880-9e39-11ea-9ed3-28c8d9d1f76f.png)

while this input

```rust
//! Some text.
//!
//! * A list.
//!
//!    * A sublist.
//!
//!    * Another sublist.
```

produces this render

![correct render](https://user-images.githubusercontent.com/117151/82805972-c09c1380-9e39-11ea-93d4-eb8f9bd25d8d.png)

The difference between these inputs is that the first has a single trailing space at the start of every otherwise blank line.

### Meta

`rustc --version --verbose`:
```
rustc 1.43.1 (8d69840ab 2020-05-04)
binary: rustc
commit-hash: 8d69840ab92ea7f4d323420088dd8c9775f180cd
commit-date: 2020-05-04
host: x86_64-unknown-linux-gnu
release: 1.43.1
LLVM version: 9.0
```

Same behavior with `rustc 1.45.0-nightly (2d03399f5 2020-04-27)`.

**Comment by ayushmishra2005** [comment]
@BartMassey 
I tried both inputs. I am getting same output. Please let me know if I am missing something. 
![image](https://user-images.githubusercontent.com/1575561/82813772-60e24e80-9eb3-11ea-8cfd-d2a6d145ebeb.png)

**Comment by ehuss** [comment]
I'm able to reproduce. @ayushmishra2005, make sure you are preserving the trailing whitespace.

Passing the following Rust string into pulldown-cmark results in the same behavior.
```rust
"
Some text.\n\
\n\
* A list.\n\
 \n\
   * A sublist.\n\
 \n\
   * Another sublist.\n\
\n\
"
```

I would say this is probably an issue for [pulldown-cmark](https://github.com/raphlinus/pulldown-cmark/issues). The commonmark dingus doesn't seem to behave the same.

Regardless, one should be careful with trailing whitespaces in markdown.  It (unfortunately) has semantic meaning of "prevent linebreak".

**Comment by BartMassey** [comment]
@ehuss Thanks!

A single trailing whitespace shouldn't have any semantic meaning in Markdown. In any case, the comment-stripping code should maybe eat it.

Do you want to report the bug against `pulldown-cmark` or shall I?

**Comment by ehuss** [comment]
> A single trailing whitespace shouldn't have any semantic meaning in Markdown.

Ah, indeed, it is two spaces, I forgot.

> Do you want to report the bug against `pulldown-cmark` or shall I?

Go ahead!

**Comment by BartMassey** [comment]
I filed [`pulldown-cmark` issue #443](https://github.com/raphlinus/pulldown-cmark/issues/443). Thanks for isolating this!
