### ISSUE TITLE
Diagnostics for `@ ..` idiom use in tuple and tuple struct patterns is incorrect

### ISSUE THREAD

**Issue by chrissimpkins** [rust-lang/rust#72574]
@estebank and I are working on diagnostics for the `@ ..` rest idiom in slice patterns (#72534) and came across this issue when an attempt is made to use it in tuples and tuple structs.

IIUC, this is allowed:

#### tuple ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=fd26ccb092664465d57a0da45e4b51a3))

```rust
fn main() {
    let x = (1, 2, 3);
    match x {
        (_a, ..) => {}
        _ => {}
    }
}
```

#### tuple struct ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=36bbaac9c00e19fab6f5e9493087523e))

```rust
struct Binder(i32, i32, i32);

fn main() {
    let x = Binder(1, 2, 3);
    match x {
        Binder(_a, ..) => {}
        _ => {}
    }
}
```

and this is not allowed (note the addition of `[id] @`):

#### tuple ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=cc75c579abac2802713c7baed0a85dba))

```rust
fn main() {
    let x = (1, 2, 3);
    match x {
        (_a, _x @ ..) => {}
        _ => {}
    }
}
```

#### tuple struct ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=037263f68c19cdf58aaaec6587212b66))

```rust
struct Binder(i32, i32, i32);

fn main() {
    let x = Binder(1, 2, 3);
    match x {
        Binder(_a, _x @ ..) => {}
        _ => {}
    }
}
```

The error messages for the tuple and tuple struct cases include the following incorrect information:

> error: `..` patterns are not allowed here

This should state that the `@ ..` id binding to rest is not allowed.  `..` patterns **are** allowed.

> note: only allowed in tuple, tuple struct, and slice patterns

`@ ..` is only allowed in slice patterns, not in tuple or tuple struct patterns.  This should state that the idiom is only allowed in slice patterns.

**Comment by chrissimpkins** [comment]
`librustc_ast_lowering` appears to be the site of the `..` check:

https://github.com/rust-lang/rust/blob/f93bb2a50b37bc8bafe4d960e2afd839eaa854ed/src/librustc_ast_lowering/pat.rs#L78-L80

This `LoweringContext` method is called:

https://github.com/rust-lang/rust/blob/f93bb2a50b37bc8bafe4d960e2afd839eaa854ed/src/librustc_ast_lowering/pat.rs#L255-L266

**Comment by leonardo-m** [comment]
Perhaps it's worth supporting "tuple slicing" pattern too in Rust:

> (a, xs @ ..) => {}

**Comment by estebank** [comment]
@leonardo-m that would implicitly create a tuple for `xs` (or a slice?). I don't think it'd be a good addition. We already support `(a, ..)`, which is much more useful in my eyes.

**Comment by leonardo-m** [comment]
That syntax is meant to produce a shorter tuple xs with the omission of the first item of the tuple. lf you think it's an useless idea then let's ignore it :)

**Comment by chrissimpkins** [comment]
https://github.com/rust-lang/rust/pull/72677
