### ISSUE TITLE
Order matters when resolving supertrait

### ISSUE THREAD

**Issue by tavianator** [rust-lang/rust#72582]
This code:

```rust
trait Foo: PartialOrd + PartialOrd<i32> {}

trait Bar {
    type Baz: Foo;

    fn bar(&self) -> Self::Baz;
}

fn baz<T: Bar>(x: T, y: T) -> bool {
    x.bar() < y.bar()
}
```

gives this [error](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=5ecb30b17d55152971227f7ec8e3c5d2):

```
   Compiling playground v0.0.1 (/playground)
error[E0308]: mismatched types
  --> src/lib.rs:10:15
   |
10 |     x.bar() < y.bar()
   |               ^^^^^^^ expected `i32`, found associated type
   |
   = note:         expected type `i32`
           found associated type `<T as Bar>::Baz`
   = note: consider constraining the associated type `<T as Bar>::Baz` to `i32`
   = note: for more information, visit https://doc.rust-lang.org/book/ch19-03-advanced-traits.html
```

which indicates that only the `PartialOrd<i32>` impl is being considered.  It seems like the only way to fix it at the usage site is something like

```rust
<T::Baz as PartialOrd>::partial_cmp(&x.bar(), &y.bar())
```

On the other hand, just swapping the order of the supertraits [fixes](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=ca801ab7bf7a4c19d2727b57cee17a07) it:

```rust
trait Foo: PartialOrd<i32> + PartialOrd {}
```

**Comment by RustyYato** [comment]
Note: This is a problem with associated types specifically, because the following code works (as expected)

```rust
trait Foo: PartialOrd + PartialOrd<i32> {}

fn baz<T: Foo>(x: T, y: T) -> bool {
    x < y
}
```

**Comment by tavianator** [comment]
This is fixed by https://github.com/rust-lang/rust/pull/73905
