### ISSUE TITLE
semantic analysis of code

### ISSUE THREAD

**Issue by delata** [rust-lang/rust#72604]
can rustc prove that this is correct or wrong?

```rust
fn add(a: i64, b: i64) -> i64 {
    a - b
}
```

add the ability analyze identifiers and comments to match with the implementation.

**Comment by csmoe** [comment]
https://internal.rust-lang.org should be a good place to discuss such kind things.

**Comment by delata** [comment]
@csmoe This is a feature request. You can't close a issue this way.

**Comment by delata** [comment]
@nikomatsakis

**Comment by iago-lito** [comment]
> This is a feature request.

@delata I think this is what @csmoe actually meant. Feature requests start with discussions at https://users.rust-lang.org/ or https://internals.rust-lang.org/, then they have to go through the [RFC process](https://rust-lang.github.io/rfcs/) at https://github.com/rust-lang/rfcs. They cannot just be asked here.

**Comment by andrewrk** [comment]
This account is a troll, see https://github.com/cplusplus/draft/issues/4015

(I already deleted the issue it made on the zig issue tracker and banned the account)

**Comment by delata** [comment]
you people sucks. you work on free software ( or you ? ) and don't let people express their thought. 
This is way open source doesn't mean any thing. It just mean the source is available.

**Comment by delata** [comment]
@andrewrk you have banned several of my previous accounts.

**Comment by iago-lito** [comment]
@delata You can express your thoughts at https://users.rust-lang.org/ and https://internals.rust-lang.org/.

Also, there is a [code of conduct](https://www.rust-lang.org/policies/code-of-conduct) to respect to when discussing around open-source projects. You will be banned again if you don't stick to it.

**Comment by delata** [comment]
f*ck your code of conduct.
what you will do. ban me?
