### ISSUE TITLE
Sign seems to be inverted

### ISSUE THREAD

**Issue by antoyo** [rust-lang/rust#72613]
It seems the variable `signed` is inverted in this line:

https://github.com/rust-lang/rust/blob/cb272d5d21c94f9a460d68d76817227a5913fbf7/src/librustc_codegen_ssa/mir/rvalue.rs#L343

LLVM seems to don't care about this, but other backends can.

The reason I think it's inverted it's because it's set from the operand:

https://github.com/rust-lang/rust/blob/cb272d5d21c94f9a460d68d76817227a5913fbf7/src/librustc_codegen_ssa/mir/rvalue.rs#L319-L325

instead of being set from the variable `cast`. I think it should be set from the variable `cast` because the intcast is to the type of `ll_t_out` which is set from `cast`.

If you can confirm this, I can try to fix this issue.

**Comment by GuillaumeGomez** [comment]
Context: @antoyo is building a libgccjit-based backend, this is how he got the issue. He's fixing and testing currently so I'm assigning the issue to him.

**Comment by antoyo** [comment]
I was actually wrong on this one. `signed` is use for the input value, not the output type.
