### ISSUE TITLE
Dropping MPSC Sender after iterating over Receiver causes deadlock

### ISSUE THREAD

**Issue by wwylele** [rust-lang/rust#72662]
I tried this code:

```rust
fn main() {
    let (tx, rx) = std::sync::mpsc::channel::<()>();
    for _ in rx { } // drop(rx); here won't deadlock
    drop(tx)
}
```

I expected to see this happen: the program successfully finishes

Instead, this happened: the program times out on the playground, and never finishes locally. Presumably a deadlock

### Meta

`rustc --version --verbose`:
```
rustc 1.43.1 (8d69840ab 2020-05-04)
binary: rustc
commit-hash: 8d69840ab92ea7f4d323420088dd8c9775f180cd
commit-date: 2020-05-04
host: x86_64-pc-windows-msvc
release: 1.43.1
LLVM version: 9.0
```
Also tried on playground:
Stable 1.43.1 and Nightly 2020-05-26 5239f5c57bb6eb9e8940

Not sure how to get a backtrace on a deadlocked program 😅

**Comment by jonas-schievink** [comment]
You can use GDB (or any native debugger really) to get backtraces for all threads

**Comment by jonas-schievink** [comment]
Ah, this is correct behavior: https://doc.rust-lang.org/std/sync/mpsc/struct.IntoIter.html

> An owning iterator over messages on a Receiver, created by Receiver::into_iter.
>
> This iterator will block whenever next is called, waiting for a new message, and None will be returned if the corresponding channel has hung up.
