### ISSUE TITLE
rustdoc doesn't highlight "&&" properly

### ISSUE THREAD

**Issue by refacto** [rust-lang/rust#72684]
I tried viewing this code with `rustdoc`:

```rust
// Both opts don't make sense
if matches.opt_present("m") && matches.opt_present("a") {
    print_usage(&program, opts);
    return;
}
```

I expected to see this happen: the `&&` operator to be highlighted correctly

Instead, this happened: 
![20200528_10h35m34s_grim](https://user-images.githubusercontent.com/27736383/83119066-88adfe00-a0cf-11ea-955f-fdff4cfe6598.png)

### Meta

`rustc --version --verbose`: (issue also exists with nightly, `2020-05-14`)
```
rustc 1.43.1 (8d69840ab 2020-05-04)
binary: rustc
commit-hash: 8d69840ab92ea7f4d323420088dd8c9775f180cd
commit-date: 2020-05-04
host: x86_64-unknown-linux-musl
release: 1.43.1
LLVM version: 9.0
```
</p>
</details>

This issue has been assigned to @euclio via [this comment](https://github.com/rust-lang/rust/issues/72684#issuecomment-636083062).

**Comment by euclio** [comment]
Looks like this was broken by #63709. cc @matklad 

Not sure what the best course of action is here. Seems like we could move the syntax highlighting to use token trees, but that seems like it doesn't preserve whitespace information?

**Comment by GuillaumeGomez** [comment]
I don't think whitespace is preserved in token trees, indeed. :-/

**Comment by euclio** [comment]
It my be possible to iterate & classify tokens, emit the source as bytes, then iterate the tokens backwards to insert the HTML spans after the fact. That would require reading all the tokens into memory, though.

**Comment by euclio** [comment]
Using token trees won't work because comments are not preserved.
