### ISSUE TITLE
Some missing lossless char => T conversions

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust#72687]
Some char => T lossless conversions are missing:
```rust
fn main() {
    let c: char = 'a';
    let _ = u32::from(c);            // OK
    let _ = u64::from(u32::from(c)); // OK
    let _ = u64::from(c);            // Error
    let _ = i64::from(c);            // Error
    let _ = u128::from(c);           // Error
    let _ = i128::from(c);           // Error
}
```

**Comment by Mark-Simulacrum** [comment]
I don't really think these make a lot of sense? Converting char to u32 in a generic way already feels like it may not have been the right approach, as I can't really see a good case for a function taking either u32 or char. And that seems even more true about the other conversions. Do you have example use cases?

**Comment by leonardo-m** [comment]
I don't. I'll use the u64::from(u32::from(c)) then. I close this down.
