### ISSUE TITLE
Properly handle feature-gated lints

### ISSUE THREAD

**Issue by LeSeulArtichaut** [rust-lang/rust#72694]
At the moment, the `unsafe_op_in_unsafe_fn` lint is the only feature-gated lint. However, feature-gate checks are hard-coded for this lint. If more feature gated lints are be added in the future, having proper handling for feature-gated lint will be useful.

Here is a suggested implementation plan:
- Add a `feature_gate` field of type `Option<Symbol>` for the [`rustc_session::lint::Lint`](https://github.com/rust-lang/rust/blob/45127211566c53bac386b66909a830649182ab7a/src/librustc_session/lint.rs#L57-L88) struct, which has a `Some` value if the lint is feature-gated, `None` otherwise.
- Tweak the [`rustc_session::declare_lint!`](https://github.com/rust-lang/rust/blob/45127211566c53bac386b66909a830649182ab7a/src/librustc_session/lint.rs#L272) macro to allow specifying the feature gate when applicable, akin to `future_incompatible`.
- When registering lints on the command line or for attributes, check if they are feature gated, and report errors accordingly. Basically, re-writing [`check_gated_link`](https://github.com/rust-lang/rust/blob/0e3b31c641217542f02b40527b0d299d9534b920/src/librustc_lint/levels.rs#L389) should be enough.
- As rustdoc allows all lints as if they were passed on the command line, prevent rustdoc from allowing feature gated lints.

This issue has been assigned to @OddCoincidence via [this comment](https://github.com/rust-lang/rust/issues/72694#issuecomment-638628391).

**Comment by nikomatsakis** [comment]
This implementation plan looks good to me -- if you think @LeSeulArtichaut that you'd like to mentor the issue, maybe tag it with E-easy and E-mentor! I'd probably extend the description above with

* some links into the code to help people find the functions in question
* a reference to your existing hard-coded support for `unsafe_op_in_unsafe_fn` lint, which I think is *basically* the model that we want to follow.

**Comment by rajatppn** [comment]
Hi, I would like to take this up if possible. I'm new to contributing to rust

**Comment by LeSeulArtichaut** [comment]
@rajatppn That's great! I edited the original post to give you links to the code you'll need to edit. I'd recommand that you base your work on #71862 so that you can immediately make changes for `unsafe_op_in_unsafe_fn` and use that as a test.

**Comment by LeSeulArtichaut** [comment]
Also, to show that you're working on an issue, you can send `@rustbot claim`, which will assign the issue to you.

**Comment by OddCoincidence** [comment]
@rajatppn Are you still working on this? If not, I'd like to claim it.

**Comment by carsonmyers** [comment]
I'm also interested, looking for a first ticket

**Comment by LeSeulArtichaut** [comment]
I'll assign this to @OddCoincidence (who opened a PR) for triage purposes.
@rustbot assign @OddCoincidence

@carsonmyers Good luck on finding a first issue! If you don't find anything, you can probably go in the Rust Zulip instance and ask for issues, `@DPC` will probably happily to find you one 😄
