### ISSUE TITLE
The documentation for identifier grammar is incomplete

### ISSUE THREAD

**Issue by cor3ntin** [rust-lang/rust#72699]
My understanding is that underscore can appear at the start of a rust identifier. However `_` doesn't have the XID_Start Unicode property so the documentation might be incomplete
 https://doc.rust-lang.org/1.3.0/grammar.html#identifiers

**Comment by jonas-schievink** [comment]
That link is outdated since many years, this is the up-to-date one: https://doc.rust-lang.org/reference/identifiers.html
