### ISSUE TITLE
linking failed in --release

### ISSUE THREAD

**Issue by KarthikNedunchezhiyan** [rust-lang/rust#72725]
Hi team, I am trying to include c file in rust. c files uses `snprintf`

if i compiled with `cargo build --release` i am getting the following error.

>   = note: /workspace/zcatalyst-sparkler/target/x86_64-unknown-linux-musl/release/build/sparklet-e2025d64787d4647/out/libsparklet_tap.a(iptable.o): In function `add_forward_rule':
          iptable.c:(.text.add_forward_rule+0x3a): undefined reference to `__snprintf_chk'
          /workspace/zcatalyst-sparkler/target/x86_64-unknown-linux-musl/release/build/sparklet-e2025d64787d4647/out/libsparklet_tap.a(iptable.o): In function `remove_forward_rule':
          iptable.c:(.text.remove_forward_rule+0x3a): undefined reference to `__snprintf_chk'
          collect2: error: ld returned 1 exit status

but if i compiled with `cargo build` it is working fine.

I am using `build.rs` to include the c code

> cc::Build::new()
>         .compiler("gcc")
>         .file("resource/tap.c")
>         .file("resource/iptable.c")
>         .compile("sparklet_tap");

Any idea why this is happening?

edit:
If i removed the `#include <stdio.h>` from my c file then `cargo build --release` compiled without error but it is throwing below warning

> warning: resource/iptable.c:58:5: warning: implicit declaration of function 'snprintf' [-Wimplicit-function-declaration]

**Comment by Enselic** [comment]
Triage: Thank you for taking the time to report a bug. In this case, important details on how others can reproduce is missing, so I will close as not reproducible. Feel free to reopen after providing a minimal, complete and verifiable example on how to reproduce.
