### ISSUE TITLE
thread '<unnamed>' panicked at 'wanted an rlib: "file too small to be an archive"', src/librustc_codegen_llvm/back/lto.rs:113:27

### ISSUE THREAD

**Issue by ddevault** [rust-lang/rust#72735]
I am building the gles3 branch of https://github.com/cyclopsian/alacritty on an aarch64-linux-musl host running Alpine Linux.

<details>
<summary>Expand for log</summary>
<pre>
   Compiling alacritty v0.4.2-dev (/home/sircmpwn/sources/alacritty/alacritty)
     Running `rustc --crate-name alacritty --edition=2018 alacritty/src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C opt-level=3 -C lto -C debuginfo=1 --cfg 'feature="default"' --cfg 'feature="wayland"' --cfg 'feature="x11"' -C metadata=ba74a16f0b654781 -C extra-filename=-ba74a16f0b654781 --out-dir /home/sircmpwn/sources/alacritty/target/release/deps -L dependency=/home/sircmpwn/sources/alacritty/target/release/deps --extern alacritty_terminal=/home/sircmpwn/sources/alacritty/target/release/deps/libalacritty_terminal-d5cd8e6cd1ede120.rlib --extern clap=/home/sircmpwn/sources/alacritty/target/release/deps/libclap-a646965d0078bf2b.rlib --extern env_logger=/home/sircmpwn/sources/alacritty/target/release/deps/libenv_logger-e1f33cc2ee350815.rlib --extern fnv=/home/sircmpwn/sources/alacritty/target/release/deps/libfnv-bde833a785064608.rlib --extern font=/home/sircmpwn/sources/alacritty/target/release/deps/libfont-72d01aee104e90bb.rlib --extern glutin=/home/sircmpwn/sources/alacritty/target/release/deps/libglutin-242ca257d826639c.rlib --extern image=/home/sircmpwn/sources/alacritty/target/release/deps/libimage-9da9bfe1ea20a0e3.rlib --extern libc=/home/sircmpwn/sources/alacritty/target/release/deps/liblibc-b47f8ad290ca118b.rlib --extern log=/home/sircmpwn/sources/alacritty/target/release/deps/liblog-40fa202730792e35.rlib --extern notify=/home/sircmpwn/sources/alacritty/target/release/deps/libnotify-c150c2f9f0a5c652.rlib --extern parking_lot=/home/sircmpwn/sources/alacritty/target/release/deps/libparking_lot-b8665eb06574e2dd.rlib --extern serde=/home/sircmpwn/sources/alacritty/target/release/deps/libserde-b056d09fc56b173c.rlib --extern serde_json=/home/sircmpwn/sources/alacritty/target/release/deps/libserde_json-44b75d9863d0461f.rlib --extern serde_yaml=/home/sircmpwn/sources/alacritty/target/release/deps/libserde_yaml-5981ffbffdf02949.rlib --extern time=/home/sircmpwn/sources/alacritty/target/release/deps/libtime-e5e9ed17c22308de.rlib --extern unicode_width=/home/sircmpwn/sources/alacritty/target/release/deps/libunicode_width-ce28df3e311c752a.rlib --extern urlocator=/home/sircmpwn/sources/alacritty/target/release/deps/liburlocator-8922a57d70586c2a.rlib --extern x11_dl=/home/sircmpwn/sources/alacritty/target/release/deps/libx11_dl-1b0af0c8e4121492.rlib --extern xdg=/home/sircmpwn/sources/alacritty/target/release/deps/libxdg-edfa46a70f4b8449.rlib -L native=/home/sircmpwn/sources/alacritty/target/release/build/libloading-1abecc6b6869cc80/out -L native=/usr/lib -L native=/lib -L native=/usr/lib -L native=/usr/lib`
warning: use of deprecated item 'std::sync::ONCE_INIT': the `new` function is now preferred
  --> alacritty/src/cli.rs:85:21
   |
85 |             .author(crate_authors!("\n"))
   |                     ^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(deprecated)]` on by default
   = note: this warning originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

warning: use of deprecated item 'std::sync::ONCE_INIT': the `new` function is now preferred
  --> alacritty/src/cli.rs:85:21
   |
85 |             .author(crate_authors!("\n"))
   |                     ^^^^^^^^^^^^^^^^^^^^
   |
   = note: this warning originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

thread '<unnamed>' panicked at 'wanted an rlib: "file too small to be an archive"', src/librustc_codegen_llvm/back/lto.rs:113:27
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.43.1 running on aarch64-alpine-linux-musl

note: compiler flags: -C opt-level=3 -C lto -C debuginfo=1 --crate-type bin

note: some of the compiler flags provided by cargo are hidden

thread 'rustc' panicked at 'src/librustc_codegen_ssa/back/write.rs:1754: panic during codegen/LLVM phase', src/librustc/util/bug.rs:37:26

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.43.1 running on aarch64-alpine-linux-musl

note: compiler flags: -C opt-level=3 -C lto -C debuginfo=1 --crate-type bin

note: some of the compiler flags provided by cargo are hidden

error: could not compile `alacritty`.

Caused by:
  process didn't exit successfully: `rustc --crate-name alacritty --edition=2018 alacritty/src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C opt-level=3 -C lto -C debuginfo=1 --cfg 'feature="default"' --cfg 'feature="wayland"' --cfg 'feature="x11"' -C metadata=ba74a16f0b654781 -C extra-filename=-ba74a16f0b654781 --out-dir /home/sircmpwn/sources/alacritty/target/release/deps -L dependency=/home/sircmpwn/sources/alacritty/target/release/deps --extern alacritty_terminal=/home/sircmpwn/sources/alacritty/target/release/deps/libalacritty_terminal-d5cd8e6cd1ede120.rlib --extern clap=/home/sircmpwn/sources/alacritty/target/release/deps/libclap-a646965d0078bf2b.rlib --extern env_logger=/home/sircmpwn/sources/alacritty/target/release/deps/libenv_logger-e1f33cc2ee350815.rlib --extern fnv=/home/sircmpwn/sources/alacritty/target/release/deps/libfnv-bde833a785064608.rlib --extern font=/home/sircmpwn/sources/alacritty/target/release/deps/libfont-72d01aee104e90bb.rlib --extern glutin=/home/sircmpwn/sources/alacritty/target/release/deps/libglutin-242ca257d826639c.rlib --extern image=/home/sircmpwn/sources/alacritty/target/release/deps/libimage-9da9bfe1ea20a0e3.rlib --extern libc=/home/sircmpwn/sources/alacritty/target/release/deps/liblibc-b47f8ad290ca118b.rlib --extern log=/home/sircmpwn/sources/alacritty/target/release/deps/liblog-40fa202730792e35.rlib --extern notify=/home/sircmpwn/sources/alacritty/target/release/deps/libnotify-c150c2f9f0a5c652.rlib --extern parking_lot=/home/sircmpwn/sources/alacritty/target/release/deps/libparking_lot-b8665eb06574e2dd.rlib --extern serde=/home/sircmpwn/sources/alacritty/target/release/deps/libserde-b056d09fc56b173c.rlib --extern serde_json=/home/sircmpwn/sources/alacritty/target/release/deps/libserde_json-44b75d9863d0461f.rlib --extern serde_yaml=/home/sircmpwn/sources/alacritty/target/release/deps/libserde_yaml-5981ffbffdf02949.rlib --extern time=/home/sircmpwn/sources/alacritty/target/release/deps/libtime-e5e9ed17c22308de.rlib --extern unicode_width=/home/sircmpwn/sources/alacritty/target/release/deps/libunicode_width-ce28df3e311c752a.rlib --extern urlocator=/home/sircmpwn/sources/alacritty/target/release/deps/liburlocator-8922a57d70586c2a.rlib --extern x11_dl=/home/sircmpwn/sources/alacritty/target/release/deps/libx11_dl-1b0af0c8e4121492.rlib --extern xdg=/home/sircmpwn/sources/alacritty/target/release/deps/libxdg-edfa46a70f4b8449.rlib -L native=/home/sircmpwn/sources/alacritty/target/release/build/libloading-1abecc6b6869cc80/out -L native=/usr/lib -L native=/lib -L native=/usr/lib -L native=/usr/lib` (exit code: 101)
</pre>
</details>

```
rustc 1.43.1
binary: rustc
commit-hash: unknown
commit-date: unknown
host: aarch64-alpine-linux-musl
release: 1.43.1
LLVM version: 10.0
```

**Comment by jackh726** [comment]
Link to code is dead, so not possible to reproduce. Closing.
