### ISSUE TITLE
read_exact infinite loops if buffer passed in is bigger than contents of the file

### ISSUE THREAD

**Issue by rizhang2** [rust-lang/rust#72753]
For example:
```
let mut file = get_some_file(); //implements Read trait
write_to_file(&mut file); // writes less than 1024 bytes worth of data
let mut buf: [u8; 1024] = [0; 1024];
reader.read_exact(&mut buf) // It will infinite loop
```
https://github.com/rust-lang/rust/blob/945d110e059ed9d77d04e03829e41c641625e478/src/libstd/io/mod.rs#L785

Is this intended to happen? I can see that it's possible for self.read to return 0 even though there is more to read so this is not trivial to fix. Maybe we can add some kind of timeout?

At the very least the documentation should be updated to reflect this.

**Comment by sfackler** [comment]
That should not happen with any correct implementation of Read. If the file is smaller than the buffer, `read` will return 0, which will break out of the loop: https://github.com/rust-lang/rust/blob/945d110e059ed9d77d04e03829e41c641625e478/src/libstd/io/mod.rs#L788.

**Comment by rizhang2** [comment]
Oh I see, we may have implemented something incorrectly. Sorry about that
