### ISSUE TITLE
Rust is eagerly evaluating range causing inconsistencies

### ISSUE THREAD

**Issue by eloraiby** [rust-lang/rust#72763]
Following this small example:
```
#[cfg(test)]
mod tests {
    #[test]
    fn test_for() {
        let mut v = Vec::new();
        for i in 0..10 {
            v.push(i);
        }

        for i in 0..v.len() {
            if i < 100 {
                v.push(i);
            }
        }

        assert!(v.len() == 110); // Crash! expected 110, count is 20
    }

    #[test]
    fn test_loop() {
        let mut v = Vec::new();
        for i in 0..10 {
            v.push(i);
        }

        let mut i = 0;
        loop {
            if i >= v.len() {
                break;
            }

            if i < 100 {
                v.push(i);
            }

            i += 1;
        }

        assert!(v.len() == 110);
    }

}
```
If that's the normal behaviour, it should be documented in https://doc.rust-lang.org/std/ops/struct.Range.html, in the language references and tutorials.

The behaviour as it stands is in contrast of what other languages implements and is confusing.

**Comment by jonas-schievink** [comment]
Nothing in Rust is lazily evaluated. Evaluation order of language constructs like `for` and the range syntax is in scope of https://github.com/rust-lang/reference/.

**Comment by eloraiby** [comment]
@jonas-schievink you failed to provide where in that reference! - if it's in there -

**Comment by jonas-schievink** [comment]
It isn't documented yet – but this is being tracked in https://github.com/rust-lang/reference/issues/248

**Comment by eloraiby** [comment]
thanks @jonas-schievink
