### ISSUE TITLE
Add support for alternative C libraries

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#7283]
Makes snapshots more compatible. Required for microcontroller Rust. musl is the favorite.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#625
