### ISSUE TITLE
#![feature(arbitrary_enum_discriminant)] is not setting discriminant values consistently

### ISSUE THREAD

**Issue by lcdr** [rust-lang/rust#72892]
Given the following code:

```rust
#![feature(arbitrary_enum_discriminant)]
#![feature(core_intrinsics)]

#[repr(u8)]
enum Enum {
    One(u8) = 1,
}

fn main() {
    dbg!(std::intrinsics::discriminant_value(&Enum::One(99)));
    dbg!(std::intrinsics::discriminant_value(&Enum::One));
    dbg!(Enum::One as u8);
}
```

I would assume the output of all debug prints to be `1`. However, they aren't:

```
[src\main.rs:10] std::intrinsics::discriminant_value(&Enum::One(99)) = 1
[src\main.rs:11] std::intrinsics::discriminant_value(&Enum::One) = 0
[src\main.rs:12] Enum::One as u8 = 160
```

Only the first one is correct. The third one even seems to change between compilations when unrelated other code is changed. For example, adding a non-empty debug print right before the call seems to change the value, and the value is also different when I run the code on the playground.

This is not the case for fieldless enums:

```rust
#![feature(core_intrinsics)]

#[repr(u8)]
enum FieldlessEnum {
    One = 1,
}

fn main() {
    dbg!(std::intrinsics::discriminant_value(&FieldlessEnum::One));
    dbg!(FieldlessEnum::One as u8);
}
```
correctly prints
```
[src\main.rs:9] std::intrinsics::discriminant_value(&FieldlessEnum::One) = 1
[src\main.rs:10] FieldlessEnum::One as u8 = 1
```

**Comment by jonas-schievink** [comment]
You are asking for the discriminant of the *function* `Enum::One` here, not the variant, and for non-enums `discriminant_value` will return 0.

**Comment by jonas-schievink** [comment]
(as for `Enum::One as u8`, that converts the function pointer to a `u8`, not the discriminant)
