### ISSUE TITLE
Convertion of negative f64 to u64.

### ISSUE THREAD

**Issue by aslpavel** [rust-lang/rust#72899]
I tried this code:

```rust
let v: f64 = -10.0;
println!("{}", v as u64);
let v: f32 = -10.0;
println!("{}", v as u64);
```

**I expected to see this happen:**
Should print
```
0
0
```

**Instead, this happened:**
Stable: 1.43.1
```
140731856997200
0
```
Beta channel
Build using the Beta version: 1.44.0-beta.4
(2020-05-23 02c25b359e667d2eba0d)
```
1
0
```
This one is actually correct. Sorry if it has been fixed, I have not found bug report for this, so I've decided to create this one.
Nightly channel
Build using the Nightly version: 1.45.0-nightly
(2020-05-31 5fd2f06e99a985dd8966)
```
0
0
```

**Comment by sfackler** [comment]
This is https://github.com/rust-lang/rust/issues/10184

**Comment by aslpavel** [comment]
I thought #10184 was about NaN, Inf and ect. This one is normal a float as returned by `f64::classify()`

**Comment by sfackler** [comment]
It is about any out of bounds value.

**Comment by ehuss** [comment]
As you've noticed, this has changed in 1.45.  This is part of #71269, so that both values return 0.   The new rules are documented at https://doc.rust-lang.org/nightly/reference/expressions/operator-expr.html#semantics.

**Comment by RalfJung** [comment]
> Plus behavior for f32 is actually correct.

That's just pure chance. Behavior is undefined in both cases (until https://github.com/rust-lang/rust/pull/71269). When behavior is undefined, looking at what the final executable does [is meaningless](https://www.ralfj.de/blog/2019/07/14/uninit.html).

I think this issue should be closed, it is a duplicate of https://github.com/rust-lang/rust/issues/10184.

**Comment by aslpavel** [comment]
I see, Thank you!
