### ISSUE TITLE
Cargo doc test not colored

### ISSUE THREAD

**Issue by pickfire** [rust-lang/rust#72915]
**Problem**

![2020-06-02-203022_1366x768_scrot](https://user-images.githubusercontent.com/4687791/83520206-e4cdb380-a50f-11ea-95b7-15a3279ea318.png)

**Steps**

1. `cargo +nightly t`

**Possible Solution(s)**

Most likely some flags not passed to `rustc`.

**Notes**

Output of `cargo version`: cargo 1.45.0-nightly (9fcb8c1d2 2020-05-25)

```
> uname -a
Linux arch 5.6.15-zen2-1-zen rust-lang/cargo#1 ZEN SMP PREEMPT Thu, 28 May 2020 16:49:25 +0000 x86_64 GNU/Linux
> os/distro
Arch Linux
> rustup --version
rustup 1.21.1 (7832b2ebe 2019-12-20)
# release channel
nightly
```

**Comment by ehuss** [comment]
Thanks for the report.  I have transferred this to rust-lang/rust, because this is a rustdoc issue.  I could have sworn there was already an issue for this, but I can't find it.  I recall investigating this in the past, and the fix wasn't exactly trivial.

**Comment by pickfire** [comment]
Yes, I think this might have been a regression. Maybe we have a regression test this time but I am not sure if the tests are able to check color.
