### ISSUE TITLE
Large arrays cause stackoverflows at runtime when compiled without --release

### ISSUE THREAD

**Issue by MEisebitt** [rust-lang/rust#72922]
Large arrays (_in my case [f64; 1_000_000]_) cause a stackoverflow at runtime if the program is run without --release. For smaller arrays (_[f64; 100_000]_) it works with and without --release.

I used this code:

    fn main() {
        let _values: [f64; 1_000_000] = [3.5; 1_000_000];
    }

When run with

    cargo run --release

everything worked, but when run with

    cargo run

the result was

    thread 'main' has overflowed its stack
    error: process didn't exit successfully: `target\debug\playground.exe` (exit code: 0xc00000fd, STATUS_STACK_OVERFLOW)

Sadly I got no backtrace, even though I enabled it.

**Metadata**
rustc 1.43.1 (8d69840ab 2020-05-04)
binary: rustc
commit-hash: 8d69840ab92ea7f4d323420088dd8c9775f180cd
commit-date: 2020-05-04
host: x86_64-pc-windows-msvc
release: 1.43.1
LLVM version: 9.0

**Comment by jonas-schievink** [comment]
It is expected that optimizations can affect stack usage. We don't generally give guarantees about this. In particular, Windows' default stack size is only 1 MB, which you are easily exceeding by allocating `1_000_000` doubles.
