### ISSUE TITLE
Allow generic types in use statements

### ISSUE THREAD

**Issue by fschutt** [rust-lang/rust#72928]
This works:

```rust
pub enum Generic<T> { B(T) }
pub struct A { }

pub type GenericAType = Generic::<A>;
pub use GenericAType as GenericA;
```

... however this doesn't:

```rust
pub use Generic::<A> as GenericA;
//  error:     ^ expected one of `::`, `;`, or `as`

// or:
pub use Generic<A> as Generic A;
//  error:     ^ expected one of `::`, `;`, or `as`
```

I always have to do this workaround for re-exporting generic types across a C boundary. It would be great if Rust could allow this.

**Comment by Dylan-DPC** [comment]
Closing this as no rfc was created, so it is better to create an rfc if somebody is interested and they'll be a tracking issue created for that
