### ISSUE TITLE
Remove `Option<W>` in `BufWriter`

### ISSUE THREAD

**Issue by Lucretiel** [rust-lang/rust#72925]
https://github.com/rust-lang/rust/blob/eeaf497b2a6bc065874e3d3367b1f3023c5bb3d3/src/libstd/io/buffered.rs#L451

`BufWriter` doesn't really need to hold its inner writer as an `Option`; it seems like the only reason it does so is to make it easier to call `into_inner`, here:

https://github.com/rust-lang/rust/blob/eeaf497b2a6bc065874e3d3367b1f3023c5bb3d3/src/libstd/io/buffered.rs#L648-L653

While it's unfortunate to add `unsafe`, there's already some in `buffered.rs`, and it seems like the better choice here would be to use `ptr::read` and `mem::forget`, especially because this method is probably infrequently used, and making this change would remove the numerous `unwrap`s that litter the `BufWriter` implementation.

**Comment by Lucretiel** [comment]
Just tried to implement this; it turns out to be nontrivial, because you need to `mem::forget(self)` in a way that doesn't leak `self.buf`.

**Comment by Amanieu** [comment]
You can use `ptr::drop_in_place` on `self.buf` before `forget(self)`.
