### ISSUE TITLE
Indexing via `index` method and `[idx]` sugar works differently in `async` blocks/functions 

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#72956]
My co-worker stumbled upon this curious case where failing typecheck can be made to succeed only by making "equivalent" lowerings to code. In particular the following snippet fails to compile because there's a `!Send` type being retained across the yield point:

<details>
<summary>Failing code example</summary>

```rust
use std::ops::Index;

/// A `Send + !Sync` for demonstration purposes.
struct Banana(*mut ());
unsafe impl Send for Banana {}

impl Banana {
    /// Make a static mutable reference to Banana for convenience purposes.
    ///
    /// Any potential unsoundness here is not super relevant to the issue at hand.
    fn new() -> &'static mut Banana {
        static mut BANANA: Banana = Banana(std::ptr::null_mut());
        unsafe {
            &mut BANANA
        }
    }
}

// Peach is still Send (because `impl Send for &mut T where T: Send`)
struct Peach<'a>(&'a mut Banana);

impl<'a> std::ops::Index<usize> for Peach<'a> {
    type Output = ();
    fn index(&self, idx: usize) -> &() {
        &()
    }
}

async fn baz(v: &()) {}

async fn bar() -> () {
    let peach = Peach(Banana::new());
    let r = &peach[0];
    baz(r).await;
    peach.index(0); // make sure peach is retained across yield point
}

fn assert_send<T: Send>(_: T) {}

pub fn main() {
    assert_send(bar())
}
```

</details>

This snippet will fail with the following error ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=7acc400b086472632c1b7489c6bc9e87)):

```
error: future cannot be sent between threads safely
  --> src/main.rs:41:5
```

suggesting that a `&peach` is being retained across the yield point `baz(r).await`. What is curious, however, that lowering the indexing operation to a method call on `Index` will make code build ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=da4a60f1144aa24873f36d97a9de7ebf)):

<details>
<summary>Succeeding code example</summary>

```rust
use std::ops::Index;

/// A `Send + !Sync` for demonstration purposes.
struct Banana(*mut ());
unsafe impl Send for Banana {}

impl Banana {
    /// Make a static mutable reference to Banana for convenience purposes.
    ///
    /// Any potential unsoundness here is not super relevant to the issue at hand.
    fn new() -> &'static mut Banana {
        static mut BANANA: Banana = Banana(std::ptr::null_mut());
        unsafe {
            &mut BANANA
        }
    }
}

// Peach is still Send (because `impl Send for &mut T where T: Send`)
struct Peach<'a>(&'a mut Banana);

impl<'a> std::ops::Index<usize> for Peach<'a> {
    type Output = ();
    fn index(&self, idx: usize) -> &() {
        &()
    }
}

async fn baz(v: &()) {}

async fn bar() -> () {
    let peach = Peach(Banana::new());
    let r = &*peach.index(0);
    baz(r).await;
    peach.index(0); // make sure peach is retained across yield point
}

fn assert_send<T: Send>(_: T) {}

pub fn main() {
    assert_send(bar())
}
```

</details>

I’m not sure quite yet whether its incorrect that we successfully build the latter example or incorrect in that we retain an immutable reference in the former example.

**Comment by tmandry** [comment]
Self-assigning for mentoring (if someone is interested in working on this, please feel free to claim).

**Comment by tmandry** [comment]
May be related to #30127

**Comment by dingxiangfei2009** [comment]
@tmandry I am interested in solving this issue or the related issue that you mentioned. I am still fresh in the desugaring process, so I would like to receive your mentoring instruction, if this issue has not been taken. Thank you!

**Comment by tmandry** [comment]
@dingxiangfei2009 Sorry, I just saw this. You're welcome to pick this up!

I'm going to un-assign myself since I haven't had time to look into it. If you're still interested, say `@rustbot claim`.

**Comment by tmandry** [comment]
We did talk about this issue in a recent meeting about this code. [Notes are here](https://hackmd.io/Qr4rGglfSMGEDItP5YWgtA?view) and should be helpful to anyone interested in picking this up.

**Comment by tmandry** [comment]
@dingxiangfei2009 Are you still planning to work on this?

**Comment by dingxiangfei2009** [comment]
@tmandry Sorry for taking long on this. However, I find it actually harder than I thought. Please allow me to unassign myself first, and propose a concrete plan before working on this.

**Comment by tmandry** [comment]
No problem. It definitely seems challenging. Feel free to drop by the [Zulip stream](https://rust-lang.zulipchat.com/#narrow/stream/187312-wg-async-foundations) if you want to talk something out.

**Comment by osa1** [comment]
@rustbot claim

I started debugging this. The diff of working vs. broken HIR:

```
--- test_works.hir      2021-02-08 20:05:17.375472239 +0300
+++ test_fails.hir      2021-02-08 20:05:17.603469714 +0300
@@ -46,8 +46,8 @@
                                                                        Peach(Banana::new());
                                                                    let r:
                                                                            &() =
-                                                                       &*peach.index(0);
-                                                                   match baz(r)
+                                                                       &peach[0];
+                                                                   match baz(&r)
                                                                        {
                                                                        mut pinned
                                                                        =>
```

The variable `r` has the same type here, but I'm guessing because of the `&*` we copy the value to stack first then move a ref to it to `r`. So that reference tracks to the current closure where in the `[idx]` version it's not copied to stack.

I also checked MIR dumps. I'm not sure which MIR file to look at in this sea of files, but in one of the files I see this in the working version:

```
        _12 = &(*_6);                    // scope 2 at test_works.rs:27:9: 27:10
        _11 = baz(move _12) -> [return: bb3, unwind: bb29]; // scope 2 at test_works.rs:27:5: 27:11
```

which becomes this in the failing version

```
        _13 = &_6;                       // scope 2 at test_fails.rs:27:9: 27:11
        _12 = &(*(*_13));                // scope 2 at test_fails.rs:27:9: 27:11
        _11 = baz(move _12) -> [return: bb3, unwind: bb29]; // scope 2 at test_fails.rs:27:5: 27:12
```

In both cases `_6` is defined as

```
        _8 = <Peach<'_> as Index<usize>>::index(move _9, const 0_usize) -> [return: bb2, unwind: bb31]; // scope 1 at test_fails.rs:26:19: 26:27
...
        _7 = &(*_8);                     // scope 1 at test_fails.rs:26:18: 26:27
        _6 = &(*_7);                     // scope 1 at test_fails.rs:26:18: 26:27
```

Because there's a difference between the HIRs of working vs. broken code, I'm guessing that the bug should be fixed at HIR level, before generating MIR. @tmandry does this make sense?

**Comment by osa1** [comment]
Ignore my comment above, the changes in HIR are following the changes in the original source so they make sense.

**Comment by osa1** [comment]
Sigh.. I just realized that this has nothing to do with MIRs as the error is generated before MIR generation. I was confused because I saw that MIRs are generated for this program, so thought that it should pass type checking etc. and the error is generated after some of the MIR passes. In reality the error is generated in type checking, but we continue with compilation (even with the error) and generate MIR.

So I think the bug should be in lowering (from AST to HIR) or type checking.

(I'm actively, but somewhat slowly, working on this)

**Comment by tmandry** [comment]
Doing triage cleanup.

@rustbot release-assignment

@osa1 if you're still working on this, feel free to re-claim

**Comment by pnkfelix** [comment]
This might have potential:

```diff
compiler/rustc_passes/src/region.rs
--- INDEX/compiler/rustc_passes/src/region.rs
+++ WORKDIR/compiler/rustc_passes/src/region.rs
@@ -676,6 +676,12 @@ fn record_rvalue_scope<'tcx>(
                 | hir::ExprKind::Unary(hir::UnOp::Deref, ref subexpr)
                 | hir::ExprKind::Field(ref subexpr, _)
                 | hir::ExprKind::Index(ref subexpr, _) => {
+                    // rust#72956: do not artificially extend `var` region in `let x = var[i];`.
+                    if let hir::ExprKind::Path(hir::QPath::Resolved(_, path)) = subexpr.kind {
+                        if let hir::def::Res::Local(_) = path.res {
+                            return;
+                        }
+                    }
                     expr = &subexpr;
                 }
                 _ => {
```

(At least, it seems to handle my reduction of the case written on this issue.)

**Comment by compiler-errors** [comment]
This was fixed when we moved coroutine witness computation into MIR.
