### ISSUE TITLE
-Zvalidate-mir: check that all unwind edges go to `cleanup` blocks

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/rust#72959]
Blocks that are part of unwinding code always need to marked as `cleanup`. This seems like an easy thing to check in the validation pass. I believe this would have caught a bug in the generator transform (a pretty long time ago).

This issue has been assigned to @doctorn via [this comment](https://github.com/rust-lang/rust/issues/72959#issuecomment-640562605).

**Comment by RalfJung** [comment]
Good point! Moreover, cleanup block terminators should also only jump to cleanup blocks, and other terminators should only jump to non-cleanup blocks. Basically, unwind edges must be the only ones that cross the "cleanup to non-cleanup" boundary.

(Miri is already checking this.)
