### ISSUE TITLE
"argument never used" in new asm! syntax

### ISSUE THREAD

**Issue by cesarb** [rust-lang/rust#72965]
When trying to use the new `asm!` syntax to implement something similar to `std::hint::black_box`, it fails with an "argument never used" error. For example (https://godbolt.org/z/mG9AMg):

```
#![feature(asm)]

pub fn black_box(dummy: i32) -> i32 {
    unsafe {
        asm!("", in(reg) &dummy, options(nostack));
        dummy
    }
}
```

```
error: argument never used

 --> <source>:5:18

  |

5 |         asm!("", in(reg) &dummy, options(nostack));

  |                  ^^^^^^^^^^^^^^ argument never used


error: aborting due to previous error


Compiler returned: 1
```

This makes it impossible to use the new `asm!` syntax in one of my crates (https://github.com/cesarb/clear_on_drop/commit/43cd2be18076c424437fbdc302bec22853291b27 with CI output at https://travis-ci.org/github/cesarb/clear_on_drop/jobs/694467164).

**Comment by Amanieu** [comment]
Fixed by #73230
