### ISSUE TITLE
-Z profile fails to produce any .gcno/.gcda files for bench target

### ISSUE THREAD

**Issue by mzabaluev** [rust-lang/rust#72974]
I want to generate profiling coverage information for a benchmark in my project. I run this command:

```sh
RUSTFLAGS='-Z profile=yes -Z profile-emit=/tmp/myproject-profile -C codegen-units=1' cargo build --benches -Z unstable-options --profile=bench --target=x86_64-unknown-linux-gnu
```

Neither the build nor running the bench executable creates `.gcno`/`.gcda` files with the coverage information. Also tried without `profile-emit`.

Tried to instrument `cargo test` for comparison, that ~results in a build failure~:

```
     Running `rustc --crate-name chunked_bytes --edition=2018 src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -Cembed-bitcode=no -C debuginfo=2 -C metadata=acf3ef1e1fe2447e -C extra-filename=-acf3ef1e1fe2447e --out-dir /home/mzabaluev/work/rust/chunked-bytes/target/x86_64-unknown-linux-gnu/debug/deps --target x86_64-unknown-linux-gnu -C incremental=/home/mzabaluev/work/rust/chunked-bytes/target/x86_64-unknown-linux-gnu/debug/incremental -L dependency=/home/mzabaluev/work/rust/chunked-bytes/target/x86_64-unknown-linux-gnu/debug/deps -L dependency=/home/mzabaluev/work/rust/chunked-bytes/target/debug/deps --extern bytes=/home/mzabaluev/work/rust/chunked-bytes/target/x86_64-unknown-linux-gnu/debug/deps/libbytes-fcec2a592652b77a.rmeta -Z profile=yes -Z profile-emit=/tmp/chunked-bytes-profile -C codegen-units=1`
error: can't instrument with gcov profiling when compiling incrementally
```

~The `-C incremental=...` option cannot be suppressed by disabling `incremental` in the test profile in `.cargo/config.toml`.~

**Edit:** the cargo test failure was solved, I used a custom target to which config did not apply. That build _does_ try to produce GCDAs and fails in some build script executable, but I guess it's a subject for a different issue.

### Meta

`rustc --version --verbose`:
```
rustc 1.45.0-nightly (56daaf669 2020-06-03)
binary: rustc
commit-hash: 56daaf669ebc3d5083db5cded719f780dc31104e
commit-date: 2020-06-03
host: x86_64-unknown-linux-gnu
release: 1.45.0-nightly
LLVM version: 10.0
```

**Comment by mzabaluev** [comment]
Tracking issue for the feature: #42524

**Comment by ehuss** [comment]
I think profiling requires debuginfo.  Try setting this in `Cargo.toml`:

```toml
[profile.bench]
debug = true

[profile.release]
debug = true
```

I'm not sure how well it will work with an optimized build, though.  You may want to consider using the dev profile instead (and setting incremental=0).

**Comment by mzabaluev** [comment]
The compiler could have put out a warning about the options being incompatible.

**Comment by workingjubilee** [comment]
We no longer support gcov-based profiling.
