### ISSUE TITLE
Namespacing of member in impl

### ISSUE THREAD

**Issue by ldm0** [rust-lang/rust#72980]
`enum namespacing` was introduced in [RFC 390](https://github.com/rust-lang/rfcs/blob/master/text/0390-enum-namespacing.md), which makes the following code compiles:
```rust
enum Emm {
    A,
    B,
}

fn main() {
    use Emm::*;
    let a = A;
    let b = B;
}
```
However:
```rust
struct Emm;
impl Emm {
    const A: usize = 0;
    const B: usize = 1;
}

fn main() {
    // Compiles
    let a = Emm::A;
    let b = Emm::B;

    // Doesn't compile
    use Emm::*;
    let a = A;
    let b = B;
}
```
I think it would be usefule if we have namespacing of member in impl? I met this issue on using `bitflags`, which depends on the feature of declaring const value in an impl block. Without namespacing of impl member we get this result:
```rust
use bitflags::bitflags;
bitflags! {
    struct Flags: u32 {
        const A = 0b00000001;
        const B = 0b00000010;
    }
}

fn main() {
    // Compiles
    let e = Flags::A | Flags::B;

   // Doesn't compile
    use Flags::*;
    let e = A | B;
}
```

**Comment by fmease** [comment]
Closing in favor of https://github.com/rust-lang/rfcs/pull/3591.
Also CC https://github.com/rust-lang/rfcs/pull/3530.
