### ISSUE TITLE
Rust MacOS cross-compile, ld: unknown option: --as-needed

### ISSUE THREAD

**Issue by SzeChuanChilliSauce** [rust-lang/rust#73016]
![image](https://user-images.githubusercontent.com/26214341/83851697-5478b400-a745-11ea-8434-082bd83e3dde.png)
cargo.toml:
![image](https://user-images.githubusercontent.com/26214341/83851804-76723680-a745-11ea-972c-44b6b7e4fbe7.png)
src:
![image](https://user-images.githubusercontent.com/26214341/83851926-9e619a00-a745-11ea-882c-a7d31b15a1ad.png)

**Comment by SzeChuanChilliSauce** [comment]
I want to compile rust as shared library for android.

**Comment by ehuss** [comment]
The linker/ar settings belong in `.cargo/config`, not `Cargo.toml`.
