### ISSUE TITLE
Another semicolon Bug:missing a `semicolon` but rustc told me `call expression requires function`

### ISSUE THREAD

**Issue by Neutron3529** [rust-lang/rust#73013]
I tried this code:

```rust
//first case, the problem is I am missing a semicolon, but compiler thought `if` returns `fn(i32)->_` but actually we need a `i32`
fn main(){
    let a:i32=if 2<3 {
        4
    } else {
        5
    }//missing a `semicolon` here, but rustc thinks I am doing a function call since I'm using parentheses in the latter column. and then told me `call expression requires function`
    ([6]).iter().for_each(|x|println!("{}",x));
    println!("{}",a)
}
```
this strange thing might due to the method to decide what if returns.
If we remove the `let` expression, things are quite different:
```rust
//second case, compiler thought `if` returns `()` but actually we need a fn(i32)->[i32;1]
fn foo1(a:i32)->[i32;1]{[a]}
fn foo2(b:i32)->[i32;1]{[b+1]}
fn main(){
    if 2<3 {
        foo1
    } else {
        foo2
    }(3)//here, I want to sent `3` into either `foo1` or `foo2`, but `rustc` thought the `if` block should return `()` rather than `fn`
    .iter().for_each(|x|println!("{}",x))
}
```
It seems rust will suppose `if` always returns `()` when there is no `=` before `if`
but with a `=` such as `let a=if ...`, the `if` will always returns something.
which is quite strange.
### Meta

`rustc --version --verbose`:
```
rustc 1.45.0-nightly (56daaf669 2020-06-03)
binary: rustc
commit-hash: 56daaf669ebc3d5083db5cded719f780dc31104e
commit-date: 2020-06-03
host: x86_64-unknown-linux-gnu
release: 1.45.0-nightly
LLVM version: 10.0
```

<details><summary>Backtrace</summary>
<p>

```
neutron@Neutron:/me$ RUST_BACKTRACE=1 rustc rust/fuckif.rs 
error[E0618]: expected function, found `{integer}`
 --> rust/fuckif.rs:2:11
  |
2 |        let a=if 2<3 {
  |   ___________^
  |  |___________|
  | ||
3 | ||         4
4 | ||     } else {
5 | ||         5
6 | ||     }
  | ||_____^
7 | |      (1+2).iter().for_each(|x|println!("{}",x));
  | |__________- call expression requires function

error: aborting due to previous error

For more information about this error, try `rustc --explain E0618`.

```

</p>
</details>

**Comment by ayazhafiz** [comment]
The behavior you're seeing has to do with the difference between rust's statements and expressions (and in this case, an [expression statement](https://doc.rust-lang.org/reference/statements.html#expression-statements)). When the `if` block is a context that expects an expression (e.g. an assignment), rustc will expect the `if` block to return some value. When the `if` block is not in a context that expects a value, the `if` block should return no value and so rustc determines that the type of the `if` block is `()`.

**Comment by Neutron3529** [comment]
> The behavior you're seeing has to do with the difference between rust's statements and expressions (and in this case, an [expression statement](https://doc.rust-lang.org/reference/statements.html#expression-statements)). When the `if` block is a context that expects an expression (e.g. an assignment), rustc will expect the `if` block to return some value. When the `if` block is not in a context that expects a value, the `if` block should return no value and so rustc determines that the type of the `if` block is `()`.

Yes, it is. But, report `call expression requires function` while missing a semicolon is quite strange.. Anyway, it is quite confusing with `if expression` and the `if statements` since the syntax of them are almost the same and the results it provide is quite different.
