### ISSUE TITLE
New asm! macro can unexpectedly reorder code

### ISSUE THREAD

**Issue by qwerty19106** [rust-lang/rust#73028]
I am testing a new asm! macro syntax.
I tried this needless code:
```
#![no_std]
#![feature(asm)]
use core::sync::atomic::{compiler_fence, Ordering};

pub extern "C" fn func(r0: usize, r1: usize, r2: usize, r3: usize) -> usize {
    unsafe {
        asm!("
            mov r0, #0
            mov r1, #1
            mov r2, #2
            mov r3, #3
            ",
            out("r0") _,
            out("r1") _,
            out("r2") _,
            out("r3") _,
        );
    }

    compiler_fence(Ordering::SeqCst);

    r0 + r1 + r2 + r3
}
```
It compiles to
```
        push    {r7, lr}
        mov     r7, sp
        add     r0, r1
        add     r0, r2
        add.w   r12, r0, r3

        mov.w   r0, #0
        mov.w   r1, #1
        mov.w   r2, #2
        mov.w   r3, #3

        mov     r0, r12
        pop     {r7, pc}
```

But I was expecting something like this:
```
        push    {r7, lr}
        mov     r7, sp

        push {r0-r3}
        mov.w   r0, #0
        mov.w   r1, #1
        mov.w   r2, #2
        mov.w   r3, #3
        pop {r0-r3}

        add     r0, r1
        add     r0, r2
        add     r0, r3
        pop     {r7, pc}
```

Why rustc reorder code in spite of `compiler_fence`?
cc [Amanieu](https://github.com/Amanieu)

### Meta
rustc 1.45.0-nightly (ad4bc3323 2020-06-01)
Target: thumbv7m-none-eabi
Opt-level: 2
[godbolt](https://godbolt.org/z/azXajM)

**Comment by Amanieu** [comment]
`compiler_fence` only acts as a barrier for *memory accesses*, and only to memory that may potentially be accessed by other threads of execution (so local variables don't count). The compiler is fully allowed to move the addition to the start of the function since it does not perform any externally visible memory accesses.
