### ISSUE TITLE
What about adding `stub!` macro to the `std`?

### ISSUE THREAD

**Issue by XX** [rust-lang/rust#73037]
Currently, we have to write like this:

```rust
fn foo() -> i32 {
    // TODO: need to implement
    0
}
```

It would be convenient to have a special macro to make stubs like `todo!` or `dbg!`:

```rust
fn foo() -> i32 {
    stub!()  // for default value
}

fn bar() -> bool {
    stub!(true)
}

foo();
let bazz = stub!(bar());
```
```
[src/main.rs:2] stub: 0
[src/main.rs:6] stub: true
[src/main.rs:11] stub: bar() = true
```
Additionally, it can be added compiler warnings. What do you think?

**Comment by LingMan** [comment]
The macro [`todo!`](https://doc.rust-lang.org/std/macro.todo.html) already exists, although it doesn't return a default value but panics instead.

**Comment by steveklabnik** [comment]
In general, discussions about ideas for features should go on internals.rust-lang.org, not the bug tracker. Thanks!

**Comment by XX** [comment]
https://internals.rust-lang.org/t/what-about-adding-stub-macro-to-the-std
