### ISSUE TITLE
Unhelpful error message: E0283 ("type annotations needed") when proper solution is to remove where-constraint

### ISSUE THREAD

**Issue by graydon** [rust-lang/rust#73082]
I ran into an issue with serde derive(Deserialize) on a struct that had type parameter that already implemented Deserialize. The error message suggests adding a type annotation to help infer the type of the type parameter; when in fact (as I learned at some length later while experimenting with the macro-expanded code) the correct solution is to _remove_ a redundant where-clause in the generated impl.

The following minimal (not-using-serde) example shows the problem:

```rust
trait Deserialize<'a> {}
trait DeserializeOwned: for<'a> Deserialize<'a> {}
trait Mine : DeserializeOwned {}

// The following line, if un-commented:
//
// impl <'a, M:Mine> Deserialize<'a> for M where M: Deserialize<'a> {}
//
// Gives error message "type annotations needed", whereas the actual
// solution is to _delete_ the redundant where-clause and compile
// the following smaller version:

impl <'a, M:Mine> Deserialize<'a> for M {}

fn main()
{
    
}                                                                                                                                                         
```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=98b2cc1ba54ca42be6b7496fd885f3d3))

rustc 1.44.0-nightly (14061868b 2020-04-10)
binary: rustc
commit-hash: 14061868b3960d8a68a079bd276dde85936970ac
commit-date: 2020-04-10
host: x86_64-unknown-linux-gnu
release: 1.44.0-nightly
LLVM version: 9.0

**Comment by dtolnay** [comment]
The reason the misleading "type annotations needed" error is present in the first place is a longstanding compiler bug: https://github.com/rust-lang/rust/issues/41617. Other than that, what you originally wrote (`impl<'a, M: Mine> Deserialize<'a> for M where M: Deserialize<'a>`) is supposed to compile.

**Comment by graydon** [comment]
Aha, fascinating! Thanks for the information, I guess this can be closed as redundant?

**Comment by jonas-schievink** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/41617 then
