### ISSUE TITLE
Emit error on #![no_std]  + #![no_core]

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rust#73096]
cc https://github.com/thepowersgang/mrustc/issues/145.

@rustbot modify labels: +C-enhancement +P-low +requires-nightly +T-compiler

**Comment by petrochenkov** [comment]
This is some extra logic in the compiler for rejecting a permanently unstable corner case, that already has some reasonable meaning. I'd say wontfix.

**Comment by Mark-Simulacrum** [comment]
I also lean towards won't fix on this sort of thing.

**Comment by oli-obk** [comment]
We've generally not tried to fix anything around no_core. Anything we do here will be severely undertested and mostly unused anyway.
