### ISSUE TITLE
Can `struct` be default open ? like c# partial class, or kotlin open class

### ISSUE THREAD

**Issue by vicobill** [rust-lang/rust#73106]
default open struct is very useful, and can avoid namespace boom.
if struct is default open, we can write code like this :
```rust
struct User(age: i32, name:String);
struct User(phone: String, netadr: String);

// or even use in MVC
struct User { some model staff};
struct User { some view staff };
struct User {some controller staff};

// or use in ECS
struct User {some entity staff};
struct User {some component staff };
struct User {some system staff };
```
we can think, the `mod` is a special `struct` or a `struct` is a special `module`.

when we `impl` a struct, the code block of function can define anywhere, why not the `struct` define not?

**Comment by jonas-schievink** [comment]
Hi! Additions or changes to the language need to go through our [RFC process](https://github.com/rust-lang/rfcs). Before an RFC is written, the feature can also be discussed in our [internals forum](https://internals.rust-lang.org/) to find other people interested in it.

Closing in favor of an RFC.
