### ISSUE TITLE
Assertion failure sometimes shows file+line number of macro, instead of use site

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#73119]
Sometimes, when an assertion fails, the file+line point to the macro in libstd, instead of the place where the macro is used. See for example https://github.com/rust-lang/rust/pull/73007#issuecomment-640111414, and @Mark-Simulacrum said they also saw this happen locally.

Currently, it is unclear how to reproduce this problem.

**Comment by Aaron1011** [comment]
I believe this is a duplicate of https://github.com/rust-lang/rust/issues/70963, and will be fixed by https://github.com/rust-lang/rust/pull/72121

**Comment by RalfJung** [comment]
Sounds plausible, yeah. Closing then, thanks!
