### ISSUE TITLE
Can't borrow a variable that should be borrowable

### ISSUE THREAD

**Issue by vandenheuvel** [rust-lang/rust#73150]
I have a test that is essentially something like
```rust
#[test]
fn test() {
    // ...
    let x = value;
    let result = function(&mut x);
    drop(result);
    let y = x.other_function();
}
```
where `other_function` takes `&self` as argument.

I expected this to compile, because `x` should be free to be borrowed again, it seems to me. I however get the following error `E0502`:
```
error[E0502]: cannot borrow `tableau` as immutable because it is also borrowed as mutable
   --> src/algorithm/simplex/logic.rs:208:19
    |
205 |         let result = primal::<_, _, _, FirstProfitable>(&mut tableau);
    |                                                         ------------ mutable borrow occurs here
...
208 |         let obj = tableau.objective_function_value();
    |                   ^^^^^^^
    |                   |
    |                   immutable borrow occurs here
    |                   mutable borrow later used here
```
Notice the odd error message, indicating an immutable and mutable borrow at the same time.

Unfortunately I was not able to isolate a small reproducing sample. The code can be found [here](https://github.com/vandenheuvel/rust-lp/blob/b8bb058b6094d9324a5902d492a1f3d2b07d3c21/src/algorithm/simplex/logic.rs#L208), running `cargo test` will display the error.

```
rustc 1.46.0-nightly (0262de554 2020-06-07)
binary: rustc
commit-hash: 0262de554b4c4c5af346137bbb1664a3f6cf4df2
commit-date: 2020-06-07
host: x86_64-unknown-linux-gnu
release: 1.46.0-nightly
LLVM version: 10.0
```

**Comment by estebank** [comment]
Could you provide [a minimal repro in the playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=69ee2b44de5d403aee8e65eb3193a584)?

**Comment by vandenheuvel** [comment]
@estebank as mentioned in the issue description, unfortunately not.

**Comment by vandenheuvel** [comment]
The compiler was actually correct: the definition of `function` incorrectly was
```rust
fn function<'a>(
    x: &'a mut Struct<'a, ...>,
) {
    // ...
}
```
which restricted the lifetime of the reference to `x` too much.

**Comment by estebank** [comment]
Reopening as a diagnostic issue. The code is correctly rejected, but the reason is hard to understand.

[Repro](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=ee0e09e9465822111539437917b7bb4e):

```
error[E0499]: cannot borrow `x` as mutable more than once at a time
  --> src/main.rs:12:13
   |
10 |     let result = foo(&mut x);
   |                      ------ first mutable borrow occurs here
11 |     drop(result);
12 |     let _ = x.bar();
   |             ^
   |             |
   |             second mutable borrow occurs here
   |             first borrow later used here
```

This seems like a reasonable category of error to encounter (where the same lifetime is used in an `fn` signature causing non-obvious lifetime bonding), that I believe we should tackle it specifically. I believe it would ideally look closer to the following:

```
error[E0499]: cannot borrow `x` as mutable more than once at a time
  --> src/main.rs:12:13
   |
3  | fn foo<'a>(_: &'a mut S<'a>) {}
   |               ------------- this type requires that the borrow last as long as `S<'a>`
4  | 
5  | impl<'a> S<'a> {
6  |     fn bar(&mut self) {}
   |            --------- this requires a mutable borrow
...
10 |     let result = foo(&mut x);
   |                      ------ first mutable borrow occurs here
11 |     drop(result);
   |     ------------ `x` is no longer accessible after this call
12 |     let _ = x.bar();
   |             ^ --- this call mutably borrows `x` after it is no longer accessible
   |             |
   |             second mutable borrow occurs here
```

**Comment by kpreid** [comment]
I think this is the same as #70274 'Better diagnostics when calling "ouroboros method"'.
