### ISSUE TITLE
Using const struct field as pattern in match expression

### ISSUE THREAD

**Issue by CodeSandwich** [rust-lang/rust#73165]
This snippet doesn't compile ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=1f3e75a979626054fd3fd7b3ef52b7cd)):

```rust
struct Data { data: u8 }

const DATA: Data = Data { data: 0 };

fn fails() {
    match 0 {
        DATA.data => (), // fails
        _ => (),
    }
}
```

I'm getting an error:
```
error: expected one of `=>`, `@`, `if`, or `|`, found `.`
 --> src/lib.rs:7:13
  |
7 |         DATA.data => (), // fails
  |             ^ expected one of `=>`, `@`, `if`, or `|`
```

The workaround works fine:

```rust
fn workaround() {
    const DATA_DATA: u8 = DATA.data;
    match 0 {
        DATA_DATA => (), // works
        _ => (),
    }
}
```

Is it correct behavior? I see no reason why `failing` should not work, especially since `workaround` works exactly the same by const evaluating the value of `DATA.data`.

Tested on 1.44.0 stable.

**Comment by jonas-schievink** [comment]
The pattern grammar does not allow arbitrary expressions, and changing that would require an RFC, so closing as expected behavior.
