### ISSUE TITLE
run-make-fulldeps/c-link-to-rust-va-list-fn test is failing on AArch64

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#73162]
The `src/test/run-make-fulldeps/c-link-to-rust-va-list-fn` test is failing on AArch64 with the following assertion:

```
test: test.c:25: main: Assertion `test_rust(check_list_0, 0x01LL, 0x02, 0x03LL) == 0' failed.
Aborted (core dumped)
```

**Comment by nagisa** [comment]
Is this a regression? This can be an ABI issue, meaning there can be soundness concerns too.

**Comment by pietroalbini** [comment]
I just noted this while running the testsuite on AArch64.

**Comment by pietroalbini** [comment]
cc @Stammark @JamieCunliffe @vigoux @joaopaulocarreiro @raw-bin, this is one of the tests that are failing on AArch64.

**Comment by JamieCunliffe** [comment]
See: https://github.com/rust-lang/rust/issues/56475

**Comment by pietroalbini** [comment]
Closing as a duplicate of #56475.
