### ISSUE TITLE
Figure out a way to keep track of attributes

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#7318]
There are a lot of attributes in use. They are nearly undocumentedand impossible to catalog automatically.

The wiki is out of date: https://github.com/mozilla/rust/wiki/Doc-attributes

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#626
