### ISSUE TITLE
impl `LowerHex` for slices of types that impl `LowerHex`

### ISSUE THREAD

**Issue by yaahc** [rust-lang/rust#73186]
Right now it isn't possible to print a slice of bytes as hex conveniently. Ideally rust should be able to compile the following code:

```rust
fn main() {
    let a: &[u8] = &[0x24, 0x00, 0xFF, 0xDE];
    println!("{:x}", a);
}
```

Right now, work arounds like this are required: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=01a92fb1c4f3e7497f91e0fe756d43d6

There are probably a few other fmt traits that should get similar treatment, and more types than just `&'_ [T]` that could benefit from blanket impls, but at a minimum it would be nice to add the following impl to `std`.

```rust
impl<T> std::fmt::LowerHex for &'_ [T]
where
    T: std::fmt::LowerHex,
{
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        for elem in self.0 {
            write!(f, "{:x}", elem)?;
        }
        
        Ok(())
    }
}
```

**Comment by Lonami** [comment]
This seems useful (I know I've needed it), so why close it?
