### ISSUE TITLE
Different styles between examples that should panic

### ISSUE THREAD

**Issue by JakobDegen** [rust-lang/rust#73196]
I happened to stumble across [this documentation](https://doc.rust-lang.org/std/primitive.char.html#method.is_digit) earlier, and was surprised by the style of the following example of code that should panic:
```rust
use std::thread;

let result = thread::spawn(|| {
    // this panics
    '1'.is_digit(37);
}).join();

assert!(result.is_err());
```

In particular, this does not seem to use the `should_panic` attribute that is used in other places in the documentation (eg [`Option`'s unwrap](https://doc.rust-lang.org/std/option/enum.Option.html#method.unwrap) ). As a result, it seems unnecessarily hard to read especially since this is a method which is likely to be of interest even for very new users. I was going to open a PR fixing this, but first wanted to ask if there is any particular reason for or benefit from this style? It also appears in a number of other places in the documentation for `char` - I have not yet searched elsewhere.

**Comment by poliorcetics** [comment]
@JakobDegen this could be fixed to be shorter and clearer you are right.

Do you want to do it ?

**Comment by JakobDegen** [comment]
@poliorcetics yeah, I'd already written the patch, was just looking for some help with running the doctests (apparently they're partially broken right now). Its all worked out now though, and I'll submit a PR in a couple of minutes.
