### ISSUE TITLE
Rustdoc doesn't document impls within functions

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#73192]
You _probably_ shouldn't be doing this, but given that you can, we should try and support it

```rust
pub struct Foo;

pub fn foo() {
    impl Foo {
        pub fn bar(&self) {
        }
    }
}
```

`bar()` is not documented, despite being usable globally. This might have to do with `--everybody-loops`?.

This works fine for trait implementations.

**Comment by ollie27** [comment]
Duplicate of #53763
