### ISSUE TITLE
possible infinite loop in sys::windows::fill_utf16_buf

### ISSUE THREAD

**Issue by rkuhn** [rust-lang/rust#73212]
Looking at [the code](https://github.com/rust-lang/rust/blob/master/src/libstd/sys/windows/mod.rs#L157) without prior knowledge of Windows system call semantics, I see an infinite loop if the syscall were to fill up the buffer exactly: when k == n on line 195, the loop will be rerun with no changes, which should result in the exact same outcome if the syscall is idempotent.

Even if Windows guarantees in some way that this cannot happen, would it not be clearer to handle this case in an obvious fashion?

**Comment by ChrisDenton** [comment]
My issue with assuming success is that we can't know what a hypothetical Win32 function is doing in this case. For example, it may have truncated the output or it may even be returning an error code, not a size. We can only guess. Best case is we guess right and it works. Worse case is we guess wrong and it causes a bug that only becomes apparent later on, making the source of the bug hard to track down.

Having given more thought to this, I'm leaning towards using `unreachable`. That would clearly document that the case is thought impossible, while also causing a panic if the function is misused.

It might also be good to clearly document the expected return for the `f1` function being passed in. E.g.:

* On success returns the size of the copied string excluding the terminating null.
* On error returns zero unless the last-error code is set to `ERROR_INSUFFICIENT_BUFFER`.
* If the last-error code is `ERROR_INSUFFICIENT_BUFFER` returns the buffer size required, including space for a terminating null.

**Comment by rkuhn** [comment]
Yes, that sounds like a good improvement! Since this Win32 behavior is not generically documented, it might also be good to note the exact syscalls that this function has been tested with. I should probably mention that I don’t have a Windows system to develop or test this on, I was merely perusing the code out of curiosity — otherwise I’d volunteer a PR.
