### ISSUE TITLE
[regression] type inference on parse()

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#73242]
https://play.rust-lang.org/?version=beta&mode=debug&edition=2018&gist=cbe4ae71cf9d88e5c0fdf6d06af3502e as a minimal example.

Unclear whether this is a new trait impl or some regression elsewhere.

**Comment by lcnr** [comment]
`PartialEq<SocketAddr>` has been added in 1.45 which would explain this: https://doc.rust-lang.org/nightly/std/net/struct.SocketAddrV4.html#impl-PartialEq%3CSocketAddr%3E

**Comment by Mark-Simulacrum** [comment]
There were roughly ~15-20 crates that failed in the crater run due to this, mostly in tests. I'm not sure whether we think that's sufficient reasoning to drop the impl, I get that it can be useful...

cc @rust-lang/libs (and relabeling as this is not an inference regression)

**Comment by withoutboats** [comment]
Can we add `PartialEq<str>` to the `SocketAddr` types? That would provide a path to patch the regression.

Being able to easily compare a socketaddr to a string seems pretty valuable for testing, I'd rather see we make it easier than require the turbofish.

**Comment by SimonSapin** [comment]
> Can we add `PartialEq<str>` to the `SocketAddr` types?

I’m not in favor since this would blur the difference between "this string does not parse as a valid socket address" v.s. "it does, but one not equal to that one". Code that doesn’t care about that difference can already use `SocketAddr::to_string` and compare strings.

**Comment by dtolnay** [comment]
#72239 mostly cared about PartialOrd and Ord impls (as you can tell from the PR title). Unlike PartialEq, none existed before on SocketAddr so they won't be problematic. I think the PR included new PartialEq impls only in support of heterogeneous PartialOrd (see https://github.com/rust-lang/rust/pull/72239#issuecomment-631765007) which was ultimately removed from the PR anyway.

I opened #73304 to revert the new PartialEq impls, leaving the PartialOrd and Ord impls from #72239.
