### ISSUE TITLE
[regression] empty shebang parsing

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#73250]
We fail to parse this (admittedly questionable) code as of beta:

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=4fd6b726ceaddf0c06e67761d2276277

```rust
#!

use std::any;

fn main() {}
```

This broke one repository (not crate) in the beta crater run: https://crater-reports.s3.amazonaws.com/beta-1.45-1/beta-2020-06-03/gh/grng3r.rust_todo/log.txt

**Comment by Mark-Simulacrum** [comment]
cc @petrochenkov 

I personally suspect that we may want to ask T-lang if we're good accepting this as expected breakage. Alternatively I guess we can adjust the shebang detection to not require a non-empty shebang.

**Comment by lcnr** [comment]
Assigning `P-medium` [as discussed as part of the Prioritization WG procedure](https://rust-lang.zulipchat.com/#narrow/stream/227806-t-compiler.2Fwg-prioritization/topic/I-prioritize.20.2373250.20.5Bregression.5D.20empty.20shebang.20parsing).

**Comment by petrochenkov** [comment]
For reference, here's the code responsible for parsing shebang in Linux kernel - https://github.com/torvalds/linux/blob/master/fs/binfmt_script.c

(Fully whitespace (including empty) `#!` line isn't considered a shebang.)

**Comment by Mark-Simulacrum** [comment]
I am inclined to close as won't fix; let's cc @grng3r as the author of that repository as well.

I'm going to go ahead and nominate this so that we can get a :+1: (or not) at the T-compiler meeting confirming won't fix status.

**Comment by petrochenkov** [comment]
I made a fix in https://github.com/rust-lang/rust/pull/73596, which also has a benefit of simplifying the rules slightly.

**Comment by grng3r** [comment]
Thanks guys, was more of a spelling mistake/leftover from previous version than unclear explanation of how to use shebang with rust as your previous explanation on how to use it worked fine in something else I was playing around with. But thank you very much for letting me know.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
