### ISSUE TITLE
nightly Cargo fails on missing README.md, breaks `remove_dir_all` crate and all transitive callers

### ISSUE THREAD

**Issue by oconnor663** [rust-lang/rust#73282]
Here's the downstream issue: https://github.com/XAMPPRocky/remove_dir_all/issues/19

This issue began very recently. It repros on `1.46.0-nightly (a37c32e2d 2020-06-11)`, but it did not repro on `rustc 1.46.0-nightly (feb3536eb 2020-06-09)`. Missing components in that latest build mean that I think only people running `rustup set profile minimal` are seeing the break currently, but it will spread with the next complete nightly build.

In this case, it think the `remove_dir_all` crate will be able to publish a new patch version that includes a fix. However, this won't help binary callers that have committed a `Cargo.lock` file. This Cargo behavior change might be a stability hazard.

**Comment by jonas-schievink** [comment]
Duplicate of https://github.com/rust-lang/rust/issues/73279

**Comment by oconnor663** [comment]
Woops, thank you.
