### ISSUE TITLE
Errors reported in `rustc_lint::levels::LintLevelsBuilder::push` occurs multiple times 

### ISSUE THREAD

**Issue by crlf0710** [rust-lang/rust#73301]
It seems errors (validation failures) reported from `rustc_lint::levels::LintLevelsBuilder::push` will occur multiple times. Examples are `E0453` (not covered by tests) and `E0763` (being added in #73300 , unit test reflecting this problem). I'm not sure what's the best way forward.

**Comment by Enselic** [comment]
E0453 is actually covered by tests, it's just that its description contains an outdated error message. If you search for "incompatible with previous forbid" you will find the tests.

(I update the description of E0453 in https://github.com/rust-lang/rust/pull/119388)
