### ISSUE TITLE
Mismatched delimiters recovered incorrectly

### ISSUE THREAD

**Issue by SOF3** [rust-lang/rust#73303]
I tried this code:

```rust
fn main(){
    let x = a.map(|)| s);
}
```
which has a typo `_` -> `)`.

The compiler gives this error:
```
error: unexpected closing delimiter: `}`
 --> src/main.rs:3:1
  |
3 | }
  | ^ unexpected closing delimiter

error: mismatched closing delimiter: `)`
 --> src/main.rs:2:24
  |
1 | fn main(){
  |          - unclosed delimiter
2 |     let x = a.map(|)| s);
  |                        ^ mismatched closing delimiter
```

The first error is not helpful. In fact, `}` is well-paired. This error is misleading as this causes developers to check `{}` pairs instead of `()`. In some more complicated files, there might be more errors related to this issue, so the real error (mismatched `()`) is displayed further in the bottom and confuses developers further.

### Meta

`rustc --version --verbose`:
```
1.46.0-nightly (2020-06-12)
```

**Comment by estebank** [comment]
This happens because the token tree is built before the actual parsing happens. If we were able to start parsing, we would instead emit

```
error: expected `|`, found `)`
 --> file.rs:2:20
  |
2 |     let x = a.map(|)| s}
  |                    ^ expected `|`
```

**Comment by estebank** [comment]
Current output:

```
error: mismatched closing delimiter: `)`
 --> src/main.rs:1:10
  |
1 | fn main(){
  |          ^ unclosed delimiter
2 |     let x = a.map(|)| s);
  |                        ^ mismatched closing delimiter

error: unexpected closing delimiter: `}`
 --> src/main.rs:3:1
  |
2 |     let x = a.map(|)| s);
  |                        - missing open `(` for this delimiter
3 | }
  | ^ unexpected closing delimiter
```

**Comment by SOF3** [comment]
seems that the originally described issue of misplaced diagnostics is no longer the case, feel free to reopen if it's still valid
