### ISSUE TITLE
error: linking with `cc` failed: exit code: 1

### ISSUE THREAD

**Issue by sk-dot-com** [rust-lang/rust#73349]
![s2](https://user-images.githubusercontent.com/57960528/84600066-2d7e5880-ae90-11ea-9547-3df4f673a9fe.png)
![c3](https://user-images.githubusercontent.com/57960528/84600069-32430c80-ae90-11ea-8797-556a7100d9ee.png)

`starizpk@starizpk-HP-EliteBook-Folio-9480m:~/projects/rust/api/diesel_demo$ cargo install diesel_cli --no-default-features --features postgres
    Updating crates.io index
  Installing diesel_cli v1.4.1
   Compiling libc v0.2.71
   Compiling proc-macro2 v1.0.18
   Compiling unicode-xid v0.2.0
   Compiling cfg-if v0.1.10
   Compiling syn v1.0.31
   Compiling autocfg v1.0.0
   Compiling getrandom v0.1.14
   Compiling memchr v2.3.3
   Compiling bitflags v1.2.1
   Compiling byteorder v1.3.4
   Compiling pq-sys v0.4.6
   Compiling unicode-xid v0.0.4
   Compiling gimli v0.21.0
   Compiling ppv-lite86 v0.2.8
   Compiling object v0.19.0
   Compiling lazy_static v1.4.0
   Compiling ucd-util v0.1.8
   Compiling regex v0.2.11
   Compiling matches v0.1.8
   Compiling smallvec v1.4.0
   Compiling serde v1.0.111
   Compiling rustc-demangle v0.1.16
   Compiling quote v0.3.15
   Compiling utf8-ranges v1.0.4
   Compiling unicode-width v0.1.7
   Compiling strsim v0.8.0
   Compiling percent-encoding v1.0.1
   Compiling ansi_term v0.11.0
   Compiling remove_dir_all v0.5.3
   Compiling vec_map v0.8.2
   Compiling synom v0.11.3
   Compiling num-traits v0.2.12
   Compiling num-integer v0.1.43
   Compiling thread_local v0.3.6
   Compiling regex-syntax v0.5.6
   Compiling unicode-bidi v0.3.4
   Compiling unicode-normalization v0.1.12
   Compiling textwrap v0.11.0
   Compiling addr2line v0.12.1
   Compiling syn v0.11.11
   Compiling idna v0.1.5
   Compiling quote v1.0.7
   Compiling backtrace v0.3.48
   Compiling atty v0.2.14
   Compiling time v0.1.43
   Compiling aho-corasick v0.6.10
   Compiling url v1.7.2
   Compiling rand_core v0.5.1
   Compiling error-chain v0.10.0
   Compiling clap v2.33.1
   Compiling rand_chacha v0.2.2
   Compiling derive-error-chain v0.10.1
   Compiling chrono v0.4.11
   Compiling rand v0.7.3
   Compiling tempfile v3.1.0
   Compiling dotenv v0.10.1
   Compiling serde_derive v1.0.111
   Compiling diesel_derives v1.4.1
   Compiling diesel v1.4.5
   Compiling migrations_internals v1.4.1
   Compiling toml v0.4.10
   Compiling diesel_cli v1.4.1
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-Wl,--as-needed" "-Wl,-z,noexecstack" "-m64" "-L" "/home/starizpk/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/tmp/cargo-installae7m0F/release/deps/diesel-862c1f538e923d23.diesel.cr2mo1c0-cgu.0.rcgu.o" "/tmp/cargo-installae7m0F/release/deps/diesel-862c1f538e923d23.diesel.cr2mo1c0-cgu.1.rcgu.o" "/tmp/cargo-installae7m0F/release/deps/diesel-862c1f538e923d23.diesel.cr2mo1c0-cgu.10.rcgu.o" "/tmp/cargo-installae7m0F/release/deps/diesel-862c1f538e923d23.diesel.cr2mo1c0-cgu.11.rcgu.o" "/tmp/cargo-installae7m0F/release/deps/diesel-862c1f538e923d23.diesel.cr2mo1c0-cgu.12.rcgu.o" "/tmp/cargo-installae7m0F/release/deps/diesel-862c1f538e923d23.diesel.cr2mo1c0-cgu.13.rcgu.o" "/tmp/cargo-installae7m0F/release/deps/diesel-862c1f538e923d23.diesel.cr2mo1c0-cgu.14.rcgu.o" "/tmp/cargo-installae7m0F/release/deps/diesel-862c1f538e923d23.diesel.cr2mo1c0-cgu.15.rcgu.o" "/tmp/cargo-installae7m0F/release/deps/diesel-862c1f538e923d23.diesel.cr2mo1c0-cgu.2.rcgu.o" "/tmp/cargo-installae7m0F/release/deps/diesel-862c1f538e923d23.diesel.cr2mo1c0-cgu.3.rcgu.o" "/tmp/cargo-installae7m0F/release/deps/diesel-862c1f538e923d23.diesel.cr2mo1c0-cgu.4.rcgu.o" "/tmp/cargo-installae7m0F/release/deps/diesel-862c1f538e923d23.diesel.cr2mo1c0-cgu.5.rcgu.o" "/tmp/cargo-installae7m0F/release/deps/diesel-862c1f538e923d23.diesel.cr2mo1c0-cgu.6.rcgu.o" "/tmp/cargo-installae7m0F/release/deps/diesel-862c1f538e923d23.diesel.cr2mo1c0-cgu.7.rcgu.o" "/tmp/cargo-installae7m0F/release/deps/diesel-862c1f538e923d23.diesel.cr2mo1c0-cgu.8.rcgu.o" "/tmp/cargo-installae7m0F/release/deps/diesel-862c1f538e923d23.diesel.cr2mo1c0-cgu.9.rcgu.o" "-o" "/tmp/cargo-installae7m0F/release/deps/diesel-862c1f538e923d23" "/tmp/cargo-installae7m0F/release/deps/diesel-862c1f538e923d23.n3sqe04yoa3f9c2.rcgu.o" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-Wl,-O1" "-nodefaultlibs" "-L" "/tmp/cargo-installae7m0F/release/deps" "-L" "/home/starizpk/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/tmp/cargo-installae7m0F/release/deps/liburl-b7024d1a58fb3f4b.rlib" "/tmp/cargo-installae7m0F/release/deps/libpercent_encoding-7398343b6813ca00.rlib" "/tmp/cargo-installae7m0F/release/deps/libidna-d24c004b96398748.rlib" "/tmp/cargo-installae7m0F/release/deps/libunicode_normalization-291fa6cf9c88f0ef.rlib" "/tmp/cargo-installae7m0F/release/deps/libsmallvec-9e4687126cb19303.rlib" "/tmp/cargo-installae7m0F/release/deps/libunicode_bidi-fc8ed7a460849c79.rlib" "/tmp/cargo-installae7m0F/release/deps/libmatches-e6a2d0b63d86a00a.rlib" "/tmp/cargo-installae7m0F/release/deps/libtoml-9552ad0ee77f9f15.rlib" "/tmp/cargo-installae7m0F/release/deps/libtempfile-08f9042d08d86237.rlib" "/tmp/cargo-installae7m0F/release/deps/librand-c33fd28633299f8d.rlib" "/tmp/cargo-installae7m0F/release/deps/librand_chacha-7485f3fddb6ac711.rlib" "/tmp/cargo-installae7m0F/release/deps/libppv_lite86-f09dca72d48e7143.rlib" "/tmp/cargo-installae7m0F/release/deps/librand_core-fc9e166b1752f9ca.rlib" "/tmp/cargo-installae7m0F/release/deps/libgetrandom-8dfba09c0c03cf43.rlib" "/tmp/cargo-installae7m0F/release/deps/libremove_dir_all-3e18ba6fa3887811.rlib" "/tmp/cargo-installae7m0F/release/deps/libserde-130206931746887e.rlib" "/tmp/cargo-installae7m0F/release/deps/libmigrations_internals-a45bf3b7c7041ed1.rlib" "/tmp/cargo-installae7m0F/release/deps/libdotenv-71d813786a14ece7.rlib" "/tmp/cargo-installae7m0F/release/deps/libregex-86b61b799f00287b.rlib" "/tmp/cargo-installae7m0F/release/deps/libutf8_ranges-4d2ee0ec78d54c92.rlib" "/tmp/cargo-installae7m0F/release/deps/libregex_syntax-bc9d6a079e66a5d4.rlib" "/tmp/cargo-installae7m0F/release/deps/libucd_util-595a643dab937453.rlib" "/tmp/cargo-installae7m0F/release/deps/libthread_local-eb29ca6d1abc9cb4.rlib" "/tmp/cargo-installae7m0F/release/deps/liblazy_static-a556dffc0aef092a.rlib" "/tmp/cargo-installae7m0F/release/deps/libaho_corasick-ab791f8d45ee3ca6.rlib" "/tmp/cargo-installae7m0F/release/deps/libmemchr-030847b8dda95d4a.rlib" "/tmp/cargo-installae7m0F/release/deps/liberror_chain-9e2a5214e882f8d6.rlib" "/tmp/cargo-installae7m0F/release/deps/libbacktrace-428a0d4dd1cf3641.rlib" "/tmp/cargo-installae7m0F/release/deps/libobject-ad9f97be855b3f39.rlib" "/tmp/cargo-installae7m0F/release/deps/libaddr2line-43d975931a9ddda4.rlib" "/tmp/cargo-installae7m0F/release/deps/libgimli-a03a057a5c698a01.rlib" "/tmp/cargo-installae7m0F/release/deps/libcfg_if-ed083a6f9c999252.rlib" "/tmp/cargo-installae7m0F/release/deps/librustc_demangle-d012bc8df0fe8fa5.rlib" "/tmp/cargo-installae7m0F/release/deps/libdiesel-88b60a83ee5ec747.rlib" "/tmp/cargo-installae7m0F/release/deps/libpq_sys-891fc5362e37e8bd.rlib" "/tmp/cargo-installae7m0F/release/deps/libbyteorder-7a10dafc85d8f8da.rlib" "/tmp/cargo-installae7m0F/release/deps/libclap-420782f6eab0bb06.rlib" "/tmp/cargo-installae7m0F/release/deps/libvec_map-cc7a044e78c3c39c.rlib" "/tmp/cargo-installae7m0F/release/deps/libtextwrap-9823d75fea8ea6c5.rlib" "/tmp/cargo-installae7m0F/release/deps/libunicode_width-97e35e16e63f6671.rlib" "/tmp/cargo-installae7m0F/release/deps/libstrsim-9dbd6fe4c1d8a635.rlib" "/tmp/cargo-installae7m0F/release/deps/libbitflags-ec60d70301d6ef50.rlib" "/tmp/cargo-installae7m0F/release/deps/libatty-170b443e8a236105.rlib" "/tmp/cargo-installae7m0F/release/deps/libansi_term-a6ebfd34844321a9.rlib" "/tmp/cargo-installae7m0F/release/deps/libchrono-51c34bdfac07bbec.rlib" "/tmp/cargo-installae7m0F/release/deps/libnum_integer-4f48ee879f8f97df.rlib" "/tmp/cargo-installae7m0F/release/deps/libnum_traits-bd36bb10df715b75.rlib" "/tmp/cargo-installae7m0F/release/deps/libtime-7300d07e9dd02e20.rlib" "/tmp/cargo-installae7m0F/release/deps/liblibc-c8342e63185f4809.rlib" "-Wl,--start-group" "/home/starizpk/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-205127404fcba336.rlib" "/home/starizpk/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libpanic_unwind-a657948fb7763780.rlib" "/home/starizpk/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libhashbrown-4af901391177f653.rlib" "/home/starizpk/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_alloc-9bdd51edf637d1e0.rlib" "/home/starizpk/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libbacktrace-df9a9630b2ea2e1e.rlib" "/home/starizpk/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libbacktrace_sys-fddbfe63d5cc9339.rlib" "/home/starizpk/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_demangle-dc1fcc6e43806791.rlib" "/home/starizpk/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libunwind-e2f4bff19e00107e.rlib" "/home/starizpk/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcfg_if-a152d13c1d7ed405.rlib" "/home/starizpk/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liblibc-d92b841792fc008d.rlib" "/home/starizpk/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/liballoc-a64c249515c023f5.rlib" "/home/starizpk/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/librustc_std_workspace_core-57654524b3e40c00.rlib" "/home/starizpk/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcore-72180f1527a726a2.rlib" "-Wl,--end-group" "/home/starizpk/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-990cc8f4a91a3ab4.rlib" "-Wl,-Bdynamic" "-lpq" "-lutil" "-ldl" "-lutil" "-ldl" "-lrt" "-lpthread" "-lgcc_s" "-lc" "-lm" "-lrt" "-lpthread" "-lutil" "-ldl" "-lutil"
  = note: /usr/bin/ld: cannot find -lpq
          collect2: error: ld returned 1 exit status
          

error: aborting due to previous error

error: failed to compile `diesel_cli v1.4.1`, intermediate artifacts can be found at `/tmp/cargo-installae7m0F`

Caused by:
  could not compile `diesel_cli`.
![s1](https://user-images.githubusercontent.com/57960528/84600040-f5771580-ae8f-11ea-8dcc-ea8d0ea03eb7.png)
`

**Comment by jonas-schievink** [comment]
You need to install the PostgreSQL libraries. Please ask for help on https://users.rust-lang.org/, not on the issue tracker.
