### ISSUE TITLE
Code in doc that is supposed to give error runs fine ?

### ISSUE THREAD

**Issue by Teln0** [rust-lang/rust#73348]
On this page : https://doc.rust-lang.org/1.9.0/book/references-and-borrowing.html
This code : 
```
let mut x = 5;
let y = &mut x;

*y += 1;

println!("{}", x);
```
is supposed to give this error : 
```
error: cannot borrow `x` as immutable because it is also borrowed as mutable
    println!("{}", x);
                   ^
```
But it runs fine in the code playground and on my computer. Is this doc outdated ?

**Comment by jonas-schievink** [comment]
You are reading the book for Rust 1.9.0, it is a few years out of date.

**Comment by Teln0** [comment]
Oh ok
