### ISSUE TITLE
Should we fill the "implementors" section in the sidebar?

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/rust#73355]
A good example from https://doc.rust-lang.org/nightly/std/any/trait.Any.html :

![Screenshot from 2020-06-14 21-51-05](https://user-images.githubusercontent.com/3050060/84602645-4a635d80-ae89-11ea-8b05-3f4562e2af6d.png)

cc @rust-lang/rustdoc

**Comment by kinnison** [comment]
If we did, would it risk pushing the methods section way down, or would we reorder the sections too?
