### ISSUE TITLE
`#[repr(align(N))]` should work on struct fields

### ISSUE THREAD

**Issue by Boscop** [rust-lang/rust#73358]
I have a situation where I need several struct fields to be 16-byte aligned.
But `#[repr(align(16))]` is not working for fields right now (`warning: unused attribute`), so I'm wrapping them in this wrapper type:
```rust
#[repr(align(16))]
pub struct Align16<T>(pub T);
```
But it would be more convenient if the align attribute also worked on individual fields.

**Comment by Alexendoo** [comment]
Triage: Hi, are you still working on this issue @maspe36?

**Comment by maspe36** [comment]
No, I've stalled on this. If its still available in a month or two I can resume work, but if someone else wants it - go for it.

**Comment by Alexendoo** [comment]
Thanks for the quick reply, if you find the time to work on it again in the future please claim again

@rustbot release-assignment

**Comment by tklebanoff** [comment]
i have this same use case. is there a way to do this without a wrapper struct?

**Comment by scottmcm** [comment]
We took at look at this in lang backlog bonanza today.  It appears that this was never implemented and never had an RFC, so we're going to close it (and #73557) as not existing.  As a language feature request, if anyone is interested in making a change related to this, you probably want the https://lang-team.rust-lang.org/how_to/propose.html before making any code changes.
