### ISSUE TITLE
-Zvalidate-mir: check that all referenced locals exist

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/rust#73356]
When encountering a `Local`, there must be a corresponding `LocalDecl` in the MIR body. If there isn't, later passes can panic due to indexing out of bounds of the `LocalDecl` array. The validation pass could detect this problem earlier.

**Comment by jonas-schievink** [comment]
Instructions:

Extend the validation pass in `src/librustc_mir/transform/validate.rs` by implementing `visit_local` for the `TypeChecker` MIR visitor:

https://github.com/rust-lang/rust/blob/4fb54ed484e2239a3e9eff3be17df00d2a162be3/src/librustc_mir/transform/validate.rs#L88

The `Visitor` trait is documented [here](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/mir/visit/trait.Visitor.html).

The method should check that the local exists in `self.body.local_decls`, and fail with a descriptive error message if not (by calling `self.fail`, not by panicking directly).

**Comment by jonas-schievink** [comment]
@yerke FYI, the validation pass currently fails on even libcore until https://github.com/rust-lang/rust/pull/73175 is merged, so you need to either wait for that, or cherry-pick some commits from there to get it to work.

You can test your changes by running `RUSTFLAGS_NOT_BOOTSTRAP="-Zvalidate-mir" ./x.py test --stage=1 src/test/ui` (the validator only runs on very little code by default, `-Zvalidate-mir` turns it on for everything).

**Comment by yerke** [comment]
@jonas-schievink I wanted to double check, running `RUSTFLAGS_NOT_BOOTSTRAP="-Zvalidate-mir" ./x.py test --stage=1 src/test/ui` should fail when I run it, right? It actually passed for me after I merged in your branch from https://github.com/rust-lang/rust/pull/73359.
I wonder if I should try clean and build stage 1 again. :\

**Comment by jonas-schievink** [comment]
It should pass with #73359 applied, but fail on current master.

**Comment by yerke** [comment]
@jonas-schievink So you PR fixes this issue (https://github.com/rust-lang/rust/issues/73356) as well?

**Comment by jonas-schievink** [comment]
Ah, no, this issue is just about adding additional validation. It shouldn't actually detect any locals that don't exist. So the command should work both before and after implementing this. If it fails after implementing this, something else is going on that we should look into.

**Comment by pitaj** [comment]
@yerke are you still working on this?

**Comment by yerke** [comment]
No, sorry. Didn’t have time for it. Go ahead.

**Comment by natsukagami** [comment]
Would like to work on this, but it seems there is another check, not on the declaration like this one, but on the memory liveness. This should cover the case that the local is not declared (I think), or would it not? 

https://github.com/rust-lang/rust/blob/1773f60ea5d42e86b8fdf78d2fc5221ead222bc1/compiler/rustc_mir/src/transform/validate.rs#L187-L192
