### ISSUE TITLE
Rename master branch to less discriminating name

### ISSUE THREAD

**Issue by ghost** [rust-lang/rust#73385]
There is currently a strong debate about whether the standard branch should be given a name that has less negative implications than "master". The starting point was apparently this [thread on the Git Mailing List](https://lore.kernel.org/git/CAOAHyQwyXC1Z3v7BZAC+Bq6JBaM7FvBenA-1fcqeDV==apdWDg@mail.gmail.com/), which, as far as I know, brought the topic up for the first time. It is criticized that the term "master" might have a negative connotation for people who were directly or indirectly affected by slavery. 

I think that especially in the light of the fact that the Rust Community is known for its openness towards all ethics and minorities, serious consideration should be given to renaming the master branch correspondingly. The GitHub CEO himself has already expressed his support for the idea (see [this tweet](https://twitter.com/natfriedman/status/1271253144442253312?s=19)), and the official GitHub cli repository has also already been changed accordingly.
Currently, it seems that the following two are the most common alternatives to the term "master":
- trunk
- main

GitHub has chosen the term trunk for the cli repository. Whether the name of the master branch of this repository should be changed accordingly should be discussed. I'm open to any constructive opinions on this topic.

**Comment by trunkensailor** [comment]
I vote for `trunk`, `main` is very confusing as a german speaking hu**man**.

**Comment by xXBuilderBXx** [comment]
Or just don't change anything because this is a dumb idea and noone has complained before because it's not related to racism in any way and the 2 accounts above are just alts.

**Comment by trunkensailor** [comment]
What is an alt? Do you mean the german word for `old`? You're name doesn't seem very old, it seems like a minecraft name.

**Comment by xXBuilderBXx** [comment]
Alt is alternate account or new account and yes i do play minecraft

**Comment by trunkensailor** [comment]
oh good to hear, great game

**Comment by steveklabnik** [comment]
Hi, This user has been deleted. Beyond that, major changes need to go through the RFC process or the compiler team's major change process. As such, I'm going to give this issue a close, as this isn't the right way to pursue this change. Thanks.
