### ISSUE TITLE
run-pass: tag-align-dyn-variants.rs, tag-align-dyn-u64.rs and tag-align-u64.rs fail on 32-bit linux

### ISSUE THREAD

**Issue by thestinger** [rust-lang/rust#7340]

**Comment by frewsxcv** [comment]
*visiting for triage*

As of today, this test is still ignored on 32 bit linux/mac

https://github.com/rust-lang/rust/blob/eaf4c5c784637f3df8bdebc6ec21dbd4bc69420a/src/test/run-pass/tag-align-dyn-u64.rs#L11-L12

**Comment by klutzy** [comment]
tag-align-dyn-u64 still fails on 32-bit linux.
