### ISSUE TITLE
linking with `cc` failed: exit code: 1

### ISSUE THREAD

**Issue by sjMalik** [rust-lang/rust#73429]
I am trying to run a stable cargo project in my new machine where I freshly installed ubuntu18.04, I think have download al dependencies but getting this error `linking with `cc` failed: exit code: 1`. Have tried all solution posted in Github related to issue and tried with rust v1.44 as well as v1.42.

**Comment by jonas-schievink** [comment]
@sjMalik Please post the full error message and the code you're trying to build.

**Comment by Enselic** [comment]
Triage: Closing as not reproducible.
