### ISSUE TITLE
Name of enum variant with fields is suggested in error messages

### ISSUE THREAD

**Issue by Aaron1011** [rust-lang/rust#73427]
The following code:

```rust
enum MyEnum {
    First(bool),
    Second
}

fn main() {
    MyEnum.foo();
}
```

gives the following error message

```
error[E0423]: expected value, found enum `MyEnum`
 --> src/main.rs:7:5
  |
7 |     MyEnum.foo();
  |     ^^^^^^
  |
help: try using one of the enum's variants
  |
7 |     MyEnum::First.foo();
  |     ^^^^^^^^^^^^^
7 |     MyEnum::Second.foo();
  |     ^^^^^^^^^^^^^^
```

`MyEnum::First.foo()` calls `foo` on a *function pointer* (the constuctor function for `MyEnum::First`, which is almost never what you want.

At the very least, we should not be suggesting using enum variants that have associated data. When attempting to call a method on the base enum type, we might want to suggest using `::` instead (e.g. `MyEnum::First::foo()`), which is more likely to be what the user wants.

**Comment by Alexendoo** [comment]
Triage: Hi, are you still working on this issue @doctorn?
