### ISSUE TITLE
bad performance of char literal to_string() vs str literal to_string()

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#73462]
I was quite surprised when I found out that 
```rust
pub fn conv() -> String {
    'a'.to_string()
}
```
generates several times the instruction count of
```rust
pub fn conv() -> String {
    "a".to_string()
}
```
(according to godbold).
Checking the (debug) build size of `println!("{}", "a".to_string());` vs `println!("{}", 'a'.to_string());` revealed the `str` variant being ~20kb lighter.

When doing some quick-and-dirty benchmarks, the `str` variant was more than 2x faster than the char-variant. [benchmark code](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=8695b47b5c9e41313e69eafe0c84855f)

````
test tests::bench_char_to_string ... bench:      39,890 ns/iter (+/- 42,078)
test tests::bench_str_to_string  ... bench:      14,422 ns/iter (+/- 2,427)
````

Is this something that could be optimized?

**Comment by alex** [comment]
The problem seems to be that `char` doesn't directly implement `to_string`, it comes from the blanket impl of `Display`. Adding an impl of `ToString` directly on `char` that looks like:

```rust
    let mut s = String::new();
    s.push(self);
    s
```

is probably the fix

**Comment by lzutao** [comment]
godbolt link: https://rust.godbolt.org/z/aYEaZr
I will add a specialization of `ToString for char`.

**Comment by lzutao** [comment]
Hm. `'1'.to_string()` is slow like `char.to_string()`

**Comment by pickfire** [comment]
Looks like byte and integer runs as slow.

**Comment by pickfire** [comment]
Should we open another issue for byte and int?

**Comment by lzutao** [comment]
yeah, do it.
