### ISSUE TITLE
Clone docs say it can't be derived for function pointers but it can

### ISSUE THREAD

**Issue by martin-t** [rust-lang/rust#73480]
The text is [here](https://doc.rust-lang.org/std/clone/trait.Clone.html#how-can-i-implement-clone):

>An example is a generic struct holding a function pointer. In this case, the implementation of Clone cannot be derived, but can be implemented as:
>
>...

However, it's in fact possible to derive:

```rust
#[derive(Clone)]
struct Generate<T>(fn() -> T);
```
([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=4852033d4260b9cd7fd18e17137eedff))

**Comment by ratijas** [comment]
The wording is incorrect, but the idea is the same: derived implementation will be restricted to `T: Clone` which is not what you'd want when cloning a _function pointer_ to a function which returns `T`.

Consider this:

```rust
#![allow(unused)]

#[derive(Clone)]
struct Generate<T>(fn() -> T);

struct NonClone();

fn non_clone() -> NonClone {
    NonClone()
}

#[derive(Clone)]
struct CanClone();

fn can_clone() -> CanClone {
    CanClone()
}

fn main() {
    let g = Generate(non_clone);
    // g.clone(); // compile error!

    let g = Generate(can_clone);
    g.clone();
}
```

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=c1d1fbcd7e5f09df91378731bdbcf0ff

**Comment by cuviper** [comment]
See #26925 for a long debate about that derived behavior.

**Comment by martin-t** [comment]
Oh, i see what's happening here. There is another weird phrasing in the [Copy docs](https://doc.rust-lang.org/std/marker/trait.Copy.html#how-can-i-implement-copy) which confused me:

>There is a small difference between the two: the derive strategy will also place a Copy bound on type parameters, which isn't always desired.

I interpreted "place Copy bounds" as putting an invisible `T: Copy` on the struct definition itself, instead of just on the impl:

```
#[derive(Clone, Copy)]
struct Derived<T>(T);

#[derive(Clone)]
struct BoundOnStruct<T: Copy>(T);
impl<T: Copy> Copy for BoundOnStruct<T> {}

#[derive(Clone)]
struct BoundOnImpl<T>(T);
impl<T: Copy> Copy for BoundOnImpl<T> {}
```

I thought Derived was equivalent to BoundOnStruct but it's actually like BoundOnImpl. I should have probably known better at this point but at least i am [not the only one mislead by it](https://github.com/rust-lang/rust/issues/26925#issuecomment-645878765) - maybe that should be rephrased too?
