### ISSUE TITLE
Segmentation fault when using rust ffi with release flag

### ISSUE THREAD

**Issue by awh6al** [rust-lang/rust#73505]
I tried this code:
```c++
#include <array>

using namespace std;

extern "C"
array<int, 5> app()
{
    array<int, 5> arr2 = {1,2,3,4,5};
    return arr2;
}

```

```rust
extern "C" {
    fn app() -> *const std::os::raw::c_int;
}

fn main() {
    unsafe { println!("{:?}", *app().wrapping_offset(2)) }
}

```
* cargo run --release
I expected to see : 3
Instead, this happened: 3 with Segmentation fault (core dumped)

** NOT THAT IT WORKS JUST FINE WITHOUT `--release` FLAG **

`rustc --version --verbose`:
```
rustc 1.45.0-nightly (47c3158c3 2020-06-04)
binary: rustc
commit-hash: 47c3158c3d797f75f0f7b2b2a977179668919dab
commit-date: 2020-06-04
host: x86_64-unknown-linux-gnu
release: 1.45.0-nightly
LLVM version: 10.0
```

</p>
</details>

**Comment by sfackler** [comment]
This is undefined behavior. `array<int, 5>` is not a pointer, it is equivalent to a structure containing an `int[5]` array as its only member.
