### ISSUE TITLE
Symbol::intern("cfg_if") changes to "//!" during rustfmt lifetime

### ISSUE THREAD

**Issue by topecongiro** [rust-lang/rust#73518]
In rustfmt, we define `rustc_span::Symbol` like the following:

```rust
lazy_static! {
    static ref CFG_IF: Symbol = Symbol::intern("cfg_if");
}
```

Recently we found out that the value of `CFG_IF` may change to other value (cc https://github.com/rust-lang/rustfmt/issues/4266#issuecomment-646870198).

I was assuming that the value defined inside `Symbol::intern` is immutable within the same process. Is this assumption incorrect?

**Comment by ehuss** [comment]
I believe that the interned symbols are only [scoped per thread](https://github.com/rust-lang/rust/blob/2d8bd9b74dc0cf06d881bac645698ccbcf9d9c5e/src/librustc_span/lib.rs#L87) for the duration of the Globals object.  It looks like rustfmt re-initializes the globals [for each input](https://github.com/rust-lang/rustfmt/blob/5ac191d6451694ba9b5bb10766eb4a7f63353235/src/formatting.rs#L69-L71) it processes.  If the first input triggers the CFG_IF lazy static, it will initialize the Symbol in the first Globals. Then during the next input, there is a fresh Globals, but the CFG_IF lazy static still has a value from the first one.

**Comment by topecongiro** [comment]
@ehuss Thank you for the reply! It seems like we are using the API in a way it wasn't intended.

I will be closing this as it is a rustfmt-side issue; sorry for the noise.
