### ISSUE TITLE
Do not run cargotest on quickcheck/proptest tests

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#73514]
As part of our CI we run "cargotest" on a variety of ecosystem crates, making sure they successfully build and run tests.

Unfortunately, some of use stochastic tests like quickcheck, which means that a crate passing our CI one day may not necessarily mean it passes CI the next. Perhaps we should audit the tests being run and filter out ones like these?

See https://github.com/rust-lang/rust/pull/73511#issuecomment-646829544 and https://github.com/BurntSushi/xsv/issues/227

cc @rust-lang/release

**Comment by Mark-Simulacrum** [comment]
Yeah I think we've discussed this to some extent previously within infra team as part of our "what to do about cargotest" discussions. cc @nellshamrell in particular

Not sure that we came to any conclusions though.

**Comment by XAMPPRocky** [comment]
Related: https://github.com/rust-lang/rust/issues/70659

**Comment by ehuss** [comment]
The `test_cat::prop_cat_rows` test from xsv fails occasionally:

* https://github.com/rust-lang/rust/pull/65342#issuecomment-541349793
* https://github.com/rust-lang/rust/pull/88680#issuecomment-927213601
* https://github.com/rust-lang/rust/pull/92283#issuecomment-1002105142

**Comment by RalfJung** [comment]
This just bit me and took a lot of time as I triple-checked that after bors failing twice (!) in xsv, the same test actually works fine on my system.

**Comment by RalfJung** [comment]
The xsv test suite seems to be full of quickcheck tests, so I think the only way to fix this is to remove xsv from cargotest (or to only run a short list of curated tests).

**Comment by ehuss** [comment]
@RalfJung See #70659 where there is some discussion fo changing the cargotest set.  I think [the last comment](https://github.com/rust-lang/rust/issues/70659#issuecomment-653252631) implies dropping xsv.

**Comment by RalfJung** [comment]
Hm, that discussion seems to have stalled though.

So to fix the immediate problem, I propose we do something like https://github.com/rust-lang/rust/pull/99602.
