### ISSUE TITLE
`extern crate` not quite the same as `--extern`

### ISSUE THREAD

**Issue by adetaylor** [rust-lang/rust#73531]
The [documentation for the `--extern` `rustc` command line flag](https://doc.rust-lang.org/rustc/command-line-arguments.html#--extern-specify-where-an-external-library-is-located) seems to suggest it's functionally identical to `extern crate`.

Specifically:

> The given crate name is added to the extern prelude, which is the same as specifying extern crate within the root module.

However, if there are `#[no_mangle]` symbols in the crate, then consumed into a `staticlib` there's a difference. I don't know if this is intentional, and/or whether I'm misinterpreting the documentation, so I'm raising an issue to ask rather than filing a PR against the documentation.

[Test case here](https://github.com/adetaylor/extern-crate-test-case)

Do this:
1. cd client
2. `./build-a.sh`. This uses `extern crate rlib;` and should successfully build a C executable including a Rust symbol.
3. `./build-b.sh`. This uses `--extern` and instead reports:
```
Undefined symbols for architecture x86_64:
  "_do_some_maths", referenced from:
      _main in test-2e4db9.o
ld: symbol(s) not found for architecture x86_64
```

`rustc 1.45.0-nightly (a08c47310 2020-05-07)`

**Comment by tmiasko** [comment]
Related issues #64731, #64402.

**Comment by adetaylor** [comment]
Ah great, thanks. I regard this as a duplicate of #64731. I may come up with a documentation PR.
