### ISSUE TITLE
Consider add more environment variables in order to get more build infos zero-cost

### ISSUE THREAD

**Issue by Dentrax** [rust-lang/rust#73549]
Today I tried create Python-like initial message:

`Python 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:37:02) [MSC v.1924 64 bit (AMD64)] on win32`

How I am trying to achieve that is simple:

```rust
fn main() {
	println!("{name} {version} ({env}) [{env} {pointer} ({arch}) on {platform}",
		name = env!("CARGO_PKG_NAME"),
		version = env!("CARGO_PKG_VERSION"),
		compile = env!("CARGO_BUILD_DATE"),
		env = env!("CARGO_CFG_TARGET_ENV"),
		pointer = env!("CARGO_CFG_TARGET_POINTER_WIDTH"),
		arch = env!("CARGO_CFG_TARGET_ARCH"),
		platform = env!("CARGO_CFG_TARGET_OS"),
	);
}
```

There are some [Environment variables Cargo sets for crates](https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-sets-for-crates) but we still have to write some [wrapper-like code](https://stackoverflow.com/questions/48182725/how-can-i-compile-a-string-supplied-on-the-command-line-during-compilation-into) or use a [lib ](https://github.com/devolutions/conan-rs)to achieve that, which is not life-saver.

What do you think? Why we have to write [build-scripts](https://doc.rust-lang.org/cargo/reference/build-scripts.html)?

**Comment by jonas-schievink** [comment]
This should be filed at https://github.com/rust-lang/cargo.

Adding `CARGO_BUILD_DATE` jeopardizes reproducible builds, which I don't think is something we should encourage.
