### ISSUE TITLE
Support dividing NonZero integers without zero check

### ISSUE THREAD

**Issue by upsuper** [rust-lang/rust#73545]
Currently for the following function
```rust
fn foo(a: i32, b: i32) -> i32 { a / b }
```
it always checks first that `b` is not zero. It's an unnecessary extra cost when people can logically ensure that the divisor would never be zero.

It would probably be ideal if one can write
```rust
fn foo(a: i32, b: NonZeroI32) -> i32 { a / b }
```
and it doesn't do zero-checking.

**Comment by leonardo-m** [comment]
You need b.get(). This seems a dupe of https://github.com/rust-lang/rust/issues/54868

**Comment by upsuper** [comment]
Yeah, looks like a dupe. Thanks.
