### ISSUE TITLE
Inconsistent behavior with include_str! between stable and nightly

### ISSUE THREAD

**Issue by nightmared** [rust-lang/rust#73551]
Hello,
someone reported on https://github.com/tokio-rs/tracing/issues/755 some weird behavior with include_str! not behaving appropriately (when using async-trait and tokio-rs/tracing), where rustc end up searching for the file to be included in a wrong directory. Turns out this builds on nightly but not on stable.

More precisely: https://github.com/Txuritan/tie is the reproducer, it builds fine any rustc built after 9b2b8a5afa833795b66267684615497c9547878d, but fails on anything before that, including stable, with the following error:
```
error: couldn't read src/text.txt: No such file or directory (os error 2)
 --> src/lib.rs:1:1
  |
1 | / mod example;
2 | |
3 | | #[async_trait::async_trait]
4 | | pub trait Test {
```

According to my nonexistent git-bisect skills, "9b2b8a5afa833795b66267684615497c9547878d is the first bad commit" (where bad is actually good here, it means the crate compiles). So it look like it's some broken span reporting/propagation that was fixed in master since. That's about everything I know, but knowing the precise commit narrow things down a fair bit, I believe.

Hope this can help !

**Comment by ratijas** [comment]
> "9b2b8a5afa833795b66267684615497c9547878d is the first bad commit"

Here: https://github.com/rust-lang/rust/commit/9b2b8a5afa833795b66267684615497c9547878d. Now it behaves like a link.

**Comment by nightmared** [comment]
This really appears to be part of https://github.com/rust-lang/rust/issues/43081, and is fixed by one the commit related to this issue.

**Comment by nightmared** [comment]
Considering there have been multiple stable releases where this issue is fixed since the moment this issue was opened, I'm closing this.
