### ISSUE TITLE
Code that doesn't depend on type fails to build when type is changed

### ISSUE THREAD

**Issue by vadixidav** [rust-lang/rust#73559]
See [this comment](https://github.com/rust-lang/rust/issues/73559#issuecomment-647062643) below for an updated MCVE.

Take a look at this playground link: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=98c74d126cd808ad9512ac2011ec7bca

For some reason, when the minimal example is built, it succeeds. However, when the type alias changes, suddenly the code stops building and terminates with an error. Since the code does not depend on the type in any way, this seems to be a compiler bug.

To provoke the bug switch between these two pieces of code:

```rust
// type A = C;
type A = nalgebra::Vector4<f64>;
```

```rust
type A = C;
// type A = nalgebra::Vector4<f64>;
```

Full code:

```rust
struct C;

// Change which one of the two lines below is commented to error or not error.
// type A = C;
type A = nalgebra::Vector4<f64>;

trait Projective: From<A> {
    fn homogeneous(self) -> A;
}

trait Pose {
    type InputPoint: Projective;
    type OutputPoint: Projective;
    
    fn transform(self, input: Self::InputPoint) -> Self::OutputPoint;
}

fn pose_output<P: Pose>(pose: P, input: P::InputPoint) -> A {
    pose.transform(input).homogeneous()
}
```

**Comment by vadixidav** [comment]
I see this was marked E-needs-mcve. I will try and create a MCVE that doesn't require nalgebra, but it is proving very difficult. I am pulling in the entire definition of `Matrix` currently.

**Comment by vadixidav** [comment]
I was unable to create a MCVE without `nalgebra`. I had pulled in a few thousand lines of code before I realized I would also have to bring in most of `typenum` as well. Does anyone have any suggestions for how I might proceed in creating a MCVE?

**Comment by vadixidav** [comment]
Okay, after some trying, I managed to create the bug without the use of an external crate:

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=9aa9a09fd13a33c2c7bd842c27b7e9e2

I will now work to reduce this (it is currently hundreds of lines).

**Comment by wwylele** [comment]
I reduced it to this
```rust
trait TypeFunc {
    type Output;
}

struct TF;
struct Out;
impl TypeFunc for TF {
    type Output = Out;
}

trait Trait {
    type Assoc: From<<TF as TypeFunc>::Output>;
}

fn foo<T: Trait>(_: T){}
```
```
error[E0277]: the trait bound `<T as Trait>::Assoc: std::convert::From<Out>` is not satisfied
  --> src/lib.rs:33:11
   |
29 | trait Trait {
   |       ----- required by a bound in this
30 |     type Assoc: From<<TF as TypeFunc>::Output>;
   |                 ------------------------------ required by this bound in `Trait`
...
33 | fn foo<T: Trait>(_: T){}
   |           ^^^^^       - help: consider further restricting the associated type: `where <T as Trait>::Assoc: std::convert::From<Out>`
   |           |
   |           the trait `std::convert::From<Out>` is not implemented for `<T as Trait>::Assoc`
```

**Comment by vadixidav** [comment]
I have created the MCVE (playground link: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=ee7b30f9b412b7ec60ec22d284f0f1df):

```rust
struct A;

impl B for A {
    type C = ();
}

pub trait B {
    type C;
}

type D = <A as B>::C;

trait E: From<D> {
    fn e(self) -> D;
}

trait F {
    type O: E;
    
    fn f(self) -> Self::O;
}

fn h<G: F>(g: G) {
    g.f().e();
}
```

**Comment by vadixidav** [comment]
@wwylele Ahh, yours looks even simpler.

**Comment by vadixidav** [comment]
@jonas-schievink Alright, I linked to @wwylele 's MCVE at the top of the original post. The needs MCVE label can be removed now.

**Comment by Dylan-DPC** [comment]
The code (including the simpler version) now compiles without any errors.
