### ISSUE TITLE
Tracking Issue for `#[repr(align(x))` on struct fields

### ISSUE THREAD

**Issue by maspe36** [rust-lang/rust#73557]
The feature gate for the issue is `#![feature(repr_align_struct_fields)]`. The original reported issue is **https://github.com/rust-lang/rust/issues/73358**

   ### About tracking issues

   Tracking issues are used to record the overall progress of implementation.
   They are also uses as hubs connecting to other relevant issues, e.g., bugs or open design questions.
   A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
   Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

   ### Steps
   

   - [ ] Implemented
   - [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
   - [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

   [stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
   [doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

   ### Unresolved Questions
   

   ### Implementation history

**Comment by jonas-schievink** [comment]
This would be the only `#[repr]` that works on individual fields. Seems a bit inconsistent.

**Comment by maspe36** [comment]
Yeah you're right. Are there any other cases where it would make sense to add support for `#[repr]` on fields?

**Comment by maspe36** [comment]
Considering you can add any `#[repr]` to a field by creating a wrapper type like this

```rust
#[repr(align(16))]
pub struct Align16<T>(pub T);

struct Foo {
    a: Align16<i32>,
}
```

I'm fine if we just want to close this issue

**Comment by hanna-kruppe** [comment]
I don't think most other `repr`s (other than `packed` as dual of `align`, lowering alignment) make any sense applied to individual fields in this way. What if it was just spelled `#[align(N)]` on fields?

**Comment by RalfJung** [comment]
(Please add an `### Implementation history` section to the tracking issue with links to the PR(s) that implement the feature.)

**Comment by maspe36** [comment]
Added the section but this feature has not been implemented yet. The way I interpreted the [rustc dev guide instructions ](https://rustc-dev-guide.rust-lang.org/implementing_new_features.html#stability-in-code) was that I open the tracking issue before the implementation.
