### ISSUE TITLE
Remove unused crate imports in 2018 edition crates

### ISSUE THREAD

**Issue by lzutao** [rust-lang/rust#73570]
Unused imports like `use libc;`.
One could use this regex
```regex
^\s*use\s+[a-z][_a-zA-Z0-9]*;
```
or try <https://grep.app/search?q=%5E%5Cs%2Ause%5Cs%2B%5Ba-z%5D%5B_a-zA-Z0-9%5D%2A%3B&regexp=true&case=true&filter[lang][0]=Rust&filter[repo][0]=rust-lang/rust>.

This issue has been assigned to @yuqio via [this comment](https://github.com/rust-lang/rust/issues/73570#issuecomment-647167501).

**Comment by yuqio** [comment]
I'm not sure if the `use` statements in [this file](https://github.com/rust-lang/rust/blob/master/src/test/ui/dep-graph/dep-graph-trait-impl-two-traits.rs) are needed. Specifically the [`use {Foo, Bar}`](https://github.com/rust-lang/rust/blob/62878c20e9ce146123fbac23a98e44dfaae95d69/src/test/ui/dep-graph/dep-graph-trait-impl-two-traits.rs#L20) and [`use y`](https://github.com/rust-lang/rust/blob/62878c20e9ce146123fbac23a98e44dfaae95d69/src/test/ui/dep-graph/dep-graph-trait-impl-two-traits.rs#L38).

Are they needed here for a test or can I remove them?

**Comment by lzutao** [comment]
I'm sorry for being unclear. I changed the issue title to "remove unused crate imports".
