### ISSUE TITLE
RUST String convert to *const i8(c_char) compile to dll,FFI return error string,

### ISSUE THREAD

**Issue by kematy** [rust-lang/rust#73607]
fn convert(data:String)->*const i8
{
	let ptr:*const u8=data.as_ptr();
	let ptr:*const i8=ptr as *const i8;
	//let _s=unsafe{*ptr}; 
	ptr
}
inputstring :"JL/G1A-630/45_A"
outputstring:"JL/G1A-630/45_A8���T"
use data.as_ptr() as *const i8, got JL/G1A-630/45_A�We5�,
each time  different
I wonder know why?

**Comment by jonas-schievink** [comment]
Hi! This issue tracker is mainly meant for bug reports and concrete, small feature requests. Questions like this are better asked in the user forum at https://users.rust-lang.org/ or on [one of the chat platforms](https://www.rust-lang.org/community) used by the Rust community.

**Comment by kematy** [comment]
data.as_ptr()---> must be (data+"\0").as_ptr()
