### ISSUE TITLE
Ship compiletest as part of rustc-dev

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#73603]
(Maybe we should have a meta tracking issue for subtree things, e.g. moving rustfmt and rustdoc over to subtree)

As clippy is fleshing out the subtree model, I wonder if it's worth shipping `compiletest` in `rustc-dev` so that rustc and clippy are always using the same compiletest.

cc @Mark-Simulacrum  @flip1995

**Comment by RalfJung** [comment]
Miri would also be interested in this (though porting it entirely to ui tests could be hard in case compiletest lost support for some of the other modes).

**Comment by euclio** [comment]
This is a great idea! Notably, clippy's compiletest doesn't currently have https://github.com/rust-lang/rust/pull/59408 in it, which causes test output that has backslashes to be pretty confusing: https://github.com/rust-lang/rust-clippy/blob/742706511c9f33c6a0d4380392e513e5249057e3/tests/ui/print_with_newline.stderr#L4

**Comment by Mark-Simulacrum** [comment]
Shipping the binary seems feasible, though it would be a small bump in CI times.

**Comment by tamird** [comment]
This is probably no longer relevant now that clippy is using ui-test?

**Comment by RalfJung** [comment]
Yeah, and Miri too.
