### ISSUE TITLE
ConstProp miscompilation around references

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#73609]
https://github.com/rust-lang/rust/pull/71911 introduced a (nightly-to-nightly) regression in mir-opt-level=3: since that landed, [this assertion](https://github.com/rust-lang/miri/blob/31ad5f6b2b93f78d3366c0654609f4b685043ec9/tests/run-pass/union.rs#L21) fails when running the test in Miri.

**Comment by RalfJung** [comment]
https://github.com/rust-lang/rust/issues/73223 is also still reproducible with mir-opt-level=3, but @oli-obk said there's a plan to hide it behind a flag that better expresses "this can and will break valid code".

**Comment by RalfJung** [comment]
In fact even level 2 is broken.

**Comment by RalfJung** [comment]
... and level 1, for the union issue (so let's treat the other one separately).

**Comment by RalfJung** [comment]
This doesn't require nightly after all, we nave a stable-to-nightly regression when just running this code:
```rust
fn main() {
    #[allow(dead_code)]
    union U {
        f1: u32,
        f2: f32,
    }
    let mut u = U { f1: 1 };
    unsafe {
        let b1 = &mut u.f1;
        *b1 = 5;
    }
    assert_eq!(unsafe { u.f1 }, 5);
}
```

**Comment by RalfJung** [comment]
In fact we don't even need a union, nor an unsafe block:
```rust
fn main() {
    #[allow(dead_code)]
    struct U {
        f1: u32,
        f2: f32,
    }
    let mut u = U { f1: 1, f2: 1.0 };
    let b1 = &mut u.f1;
    *b1 = 5;
    assert_eq!( { u.f1 }, 5);
}
```

**Comment by jonas-schievink** [comment]
Minimized:

```rust
fn main() {
    let mut u = (1,);
    *&mut u.0 = 5;
    assert_eq!( { u.0 }, 5);
}
```

**Comment by oli-obk** [comment]
on it

**Comment by Dylan-DPC** [comment]
giving this p-critical based on our [discussion](https://rust-lang.zulipchat.com/#narrow/stream/227806-t-compiler.2Fwg-prioritization/topic/I-prioritize.20.2373609.20Miscompilation.20with.20mir-opt-level.3D2)

**Comment by wesleywiser** [comment]
Why is this `regression-from-stable-to-beta` when the offending PR only merged last night?

**Comment by Aaron1011** [comment]
@RalfJung: Why didn't the assertion failure cause a Miri toolstate change?

**Comment by RalfJung** [comment]
I think this is stable-to-nightly only... @oli-obk why did you change that?

@Aaron1011 rustc's CI currently only tests Miri with mir-opt-level=0.

**Comment by oli-obk** [comment]
I tested it in the playground and I thought it also happened on beta?

**Comment by oli-obk** [comment]
Hmm... not sure what happened, must have mis-clicked on the playground
