### ISSUE TITLE
error message displayed when i execute 'wasm-pack build'

### ISSUE THREAD

**Issue by lamei1224** [rust-lang/rust#73612]
i dont know how to solve this problem,so i want someone to help me please.the code only can use on the nightly,so i dont try the stable and beta

1、I have installed rust version
2、when i execute 'wasm-pack build' in https://github.com/paritytech/stateless-blockchain on 
     accumulator-client
3、Error Message displays
![error](https://user-images.githubusercontent.com/55862430/85283204-89b03080-b4bf-11ea-8aa8-cb48509cb410.png)

**Comment by jonas-schievink** [comment]
Hi! This issue tracker is mainly meant for bug reports and concrete, small feature requests. Questions like this are better asked in the user forum at https://users.rust-lang.org/ or on [one of the chat platforms](https://www.rust-lang.org/community) used by the Rust community.
