### ISSUE TITLE
[rustdoc] ALIASES[crate] is undefined

### ISSUE THREAD

**Issue by lzutao** [rust-lang/rust#73620]
I loaded the std doc at <https://doc.rust-lang.org/nightly/std/index.html> in Firefox 77.0.1,
then I typed fast for the word "true" (or click this link: <https://doc.rust-lang.org/nightly/std/index.html?search=true>).

*I expected to see this happen*: The search result appears and includes the "true" keyword link.

*Instead, this happened*: No search result was shown.
Also in the Firefox console, this was printed after typing the word "true":
```js
TypeError: ALIASES[crate] is undefined 3 main1.46.0.js:formatted:869
    handleAliases main1.46.0.js:869
    execQuery main1.46.0.js:1110
    execSearch main1.46.0.js:1407
    search main1.46.0.js:1457
```

### Meta

Version of std docs: 1.46.0-nightly (a8cf39911 2020-06-21)

cc @jyn514 in case you interest.

**Comment by lzutao** [comment]
The type error happened along this line:
https://github.com/rust-lang/rust/blob/1a4e2b6f9c75a0e21722c88a0e3b610d6ffc3ae3/src/librustdoc/html/static/main.js#L1021

**Comment by ollie27** [comment]
It looks like it fails when you have a crate filter selected. Almost certainly caused by #71724 (cc @GuillaumeGomez).

**Comment by lzutao** [comment]
> It looks like it fails when you have a crate filter selected

yeah, that's right. I forgot about that detail.

**Comment by ollie27** [comment]
#73644 should fix this.
