### ISSUE TITLE
Boxed recursive async function is forbidden unless a let-binding is used

### ISSUE THREAD

**Issue by jimblandy** [rust-lang/rust#73624]
Rust rejects the following code ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=8213e0f5a7dfc0030d173f391bb38d24)):

```rs
use std::future::Future;
use std::pin::Pin;

async fn recurse(i: usize) {
    if i == 0 {
        println!("Zero!");
        return;
    }
    
    println!("entering {}", i);
    (Box::pin(recurse(i-1)) as Pin<Box<dyn Future<Output=()>>>).await;
    println!("exiting {}", i);
}

fn main() {
    futures::executor::block_on(recurse(10));
}
```
with the error message:
```
error[E0733]: recursion in an `async fn` requires boxing
 --> src/main.rs:4:28
  |
4 | async fn recurse(i: usize) {
  |                            ^ recursive `async fn`
  |
  = note: a recursive `async fn` must be rewritten to return a boxed `dyn Future`
```

But if the central part is changed to this ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=e3f96bb98df7c02cb4e0233f87184e22)):
```rs
    println!("entering {}", i);
    let recursed = Box::pin(recurse(i-1)) as Pin<Box<dyn Future<Output=()>>>;
    recursed.await;
    println!("exiting {}", i);
```
then Rust accepts the program.

[corrected] In neither program is the recursive future unboxed across an await, so there's no reason its size should contribute to the size of the future.

([internals forum thread](https://internals.rust-lang.org/t/recursive-async-function-permitted-but-why/12608))

**Comment by withoutboats** [comment]
> In neither program is the unboxed recursive future live across an await, so there's no reason its size should contribute to the size of the future.

This doesn't seem correct to me.. the future is alive across the await, because it is the argument to the await and so it must necessarily be alive across the await. But you say "unboxed" and of course the future is (as it must be) boxed, so maybe I'm confused by your terminology.

**Comment by jimblandy** [comment]
Sorry - 'live' is definitely not the right word there. Second attempt at that sentence:

In neither program is the recursive future unboxed across an await, so there's no reason its size should contribute to the size of the future.

**Comment by fmease** [comment]
No longer reproducible on stable, beta and nightly. Seems to have been fixed.
