### ISSUE TITLE
Hidden code suggestions are not tested

### ISSUE THREAD

**Issue by SNCPlay42** [rust-lang/rust#73641]
The enum [`SuggestionStyle`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_errors/enum.SuggestionStyle.html) (which is used by `DiagnosticBuilder` functions like [`span_suggestion_short`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_errors/struct.Diagnostic.html#method.span_suggestion_short)) allows for code suggestions to not be displayed in compiler output, but still be made available to tools like IDE quick-fix and `cargo fix`, if it is obvious from the diagnostics what should be done.

But UI tests only check compiler output, so such suggestions are not being tested to see if they are valid/good/etc.

@rustbot modify labels: +A-diagnostics +A-suggestion-diagnostics +A-testsuite

**Comment by estebank** [comment]
All `span_suggestion_short` and `span_suggestion_hidden` cases should have tests using `// run-rustfix` to confirm their successful application. We probably need to audit that we _are_ currently doing so.
