### ISSUE TITLE
NonZeroUsize should implement TryFrom<usize>

### ISSUE THREAD

**Issue by larsluthman** [rust-lang/rust#73664]
```std::num::NonZeroUsize``` does not implement the trait ```std::convert::TryFrom<usize>```, and the same goes for all the other ```NonZero``` types - they don't implement ```TryFrom``` conversions from their inner type. This seems to be exactly the sort of situation that ```TryFrom``` was created for, so they probably should.

The ```NonZeroUsize::new()``` method already does something similar by returning ```None``` if the value is zero, but having ```TryFrom``` would be nice for consistency and for generic code.

**Comment by sfackler** [comment]
https://github.com/rust-lang/rust/pull/72717

**Comment by larsluthman** [comment]
Thanks! I searched the issues before adding this one but didn't think to also search the pull requests. Will do that next time.

**Comment by Mark-Simulacrum** [comment]
Closing as I think this is done?
