### ISSUE TITLE
Documentation page for rustc_middle::ty::List is malformed

### ISSUE THREAD

**Issue by arora-aman** [rust-lang/rust#73676]
Documentation generated for 
```rust
/// trait X<S> { fn f<T>(); }
/// impl<U> X<U> for U { fn f<V>() {} }
``` 
and any code after is all strikethrough because of the `<S>`.

Generated doc: [Here](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/struct.List.html#impl-HashStable%3CStableHashingContext%3C%27a%3E%3E)

Associated src code: [Here](https://github.com/rust-lang/rust/blob/04e589ced8a48818f93d6daff94a4f85e3b07271/src/librustc_middle/ty/subst.rs#L339)

cc: @jyn514

This issue has been assigned to @jyn514 via [this comment](https://github.com/rust-lang/rust/issues/73676#issuecomment-649899453).

**Comment by ehuss** [comment]
This is normal and expected markdown behavior.  

trait X<S> { fn f<T>(); }
impl<U> X<U> for U { fn f<V>() {} }

</S>

It needs to be placed in a code block to avoid that (or use escapes).

**Comment by crlf0710** [comment]
It affecting that specific piece of item doc -  expected behavior
It affecting the rest of page - duplicate of #67799

**Comment by nagisa** [comment]
Duplicate of #67799

**Comment by jyn514** [comment]
I don't think this should be closed until the docs for https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/struct.List.html#impl-HashStable%3CStableHashingContext%3C%27a%3E%3E are changed not to have strikethroughs everywhere.

**Comment by nagisa** [comment]
Sure, adjusted the title to better reflect the scope of the issue.
