### ISSUE TITLE
Looking for help implementing ABI calling code for m68k

### ISSUE THREAD

**Issue by glaubitz** [rust-lang/rust#73685]
Hello!

I'm working on porting the Rust compiler to Motorola M68000 (m68k) [1]. The work is based on a work-in-progress port of LLVM to m68k [2].

While most of the work to add m68k support to Rust is rather trivial, I'm having issues with the ABI calling code and I was wondering whether one of the many Rust experts here could help me with that [3]. Currently, I have just copied the code for powerpc which doesn't work, of course. Thus, I'm asking for help.

Necessary documentation describing the m68k SySV ABI can be found in the Github repository for the M680x0 LLVM project [4].

If posting this request as an issue is inappropriate, please feel free to close it again. I'm very happy for any pointers though.

Thanks,
Adrian

> [1] https://github.com/glaubitz/rust/tree/m68k-linux
> [2] https://github.com/M680x0/M680x0-mono-repo
> [3] https://github.com/glaubitz/rust/blob/m68k-linux/src/librustc_target/abi/call/m68k.rs
> [4] https://github.com/M680x0/Literature

**Comment by nagisa** [comment]
Consider reaching out for assistance in the [#t-compiler/help](https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp) Zulip stream or the #compiler discord channel.

**Comment by glaubitz** [comment]
Thanks. Will do :).

**Comment by glaubitz** [comment]
This has been implemented and Rust already produces working m68k code: https://twitter.com/rickytaylor26/status/1361305806164144128

Sources: https://github.com/glaubitz/rust/commits/m68k-linux

Therefore closing.
