### ISSUE TITLE
Add the possibility to filter the files to instrument for code coverage

### ISSUE THREAD

**Issue by calixteman** [rust-lang/rust#73696]
It's possible with clang and gcc :
 - https://clang.llvm.org/docs/UsersManual.html#gcov-based-profiling
 - https://gcc.gnu.org/onlinedocs/gcc/Instrumentation-Options.html
It'd help to improve speed in instrumenting only the project files.
It's possible to do it in calling the `GCOVProfiler` (https://github.com/llvm/llvm-project/blob/master/llvm/lib/Transforms/Instrumentation/GCOVProfiling.cpp#L91) with `GCOVOptions` (https://github.com/llvm/llvm-project/blob/master/llvm/include/llvm/Transforms/Instrumentation.h#L53-L74).

**Comment by workingjubilee** [comment]
We no longer support gcov-based profiling.
