### ISSUE TITLE
Feature request: Make Mutex::new/RwLock::new const.

### ISSUE THREAD

**Issue by emilio** [rust-lang/rust#73714]
This is useful for the same reason `Mutex::new` being const is (#66806).

Right now `RwLock::new` allocates, which is unfortunate.

The `parking_lot` crate does this: https://amanieu.github.io/parking_lot/parking_lot/struct.RwLock.html#methods

**Comment by RalfJung** [comment]
Since https://github.com/rust-lang/rust/issues/66806 was closed, I am not sure how useful it is to keep this open? At least there should be one issue covering "const synchronization primitive constructors" in general. And that is blocked on using parking_lot.

**Comment by emilio** [comment]
Ah, sorry, I naively thought it was closed as fixed, rather than as "can't fix". I'm happy to close this if the answer is the same (we can't as long as we use the OS primitive), but if using parking lot is on the table I'm happy to morph this into such an issue.

**Comment by RalfJung** [comment]
> we can't as long as we use the OS primitive

AFAIK that applies to `RwLock` as well.

> but if using parking lot is on the table I'm happy to morph this into such an issue.

I don't think there is an issue. It might be worth creating one. There was a PR (https://github.com/rust-lang/rust/pull/56410) but it stalled.

**Comment by jamesmunns** [comment]
I think it may be possible to make RwLock const now, at least from a quick look at Unix and Windows, there doesn't seem to need to be any allocations, and I don't see any data that isn't const-able.

**Comment by dtolnay** [comment]
Closed by #97791; these will be const in 1.63.
