### ISSUE TITLE
split up rustc_middle/mir/mod.rs

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#73723]
https://github.com/rust-lang/rust/pull/73513 moved the file to over 3k LOC, but I didn't fix it there and instead just annotated the file so tidy ignores it. We should probably split the mir types into separate submodules by the way they are used in MIR. I think we can start by pulling out e.g. terminators and all their sub-types to a `terminator` submodule

This issue has been assigned to @aszenz via [this comment](https://github.com/rust-lang/rust/issues/73723#issuecomment-650020594).

**Comment by aszenz** [comment]
@rustbot claim
Will be interesting in picking this up
