### ISSUE TITLE
Invalid equality check result for usizes obtained from function pointers

### ISSUE THREAD

**Issue by Riateche** [rust-lang/rust#73722]
Code:
```rust
fn main() {
    fn x() {}
    fn y() {}

    let a = x as usize;
    let b = y as usize;
    
    assert_eq!(a, b);
}

```
Output in release mode:
```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `94740677858160`,
 right: `94740677858160`', src/main.rs:8:5
```
[Playground](https://play.rust-lang.org/?version=nightly&mode=release&edition=2018&gist=11d1a80991163b871c47ef46a353fbee)

There is a similar issue about [comparing function pointers](https://github.com/rust-lang/rust/issues/54685), but incorrect comparison of `usize` may be more dangerous. For example, if unsafe code checks the equality between `usize` to uphold its invariant, passing values obtained this way may break the invariant, even though the unsafe code itself didn't work with function pointers.

**Comment by RalfJung** [comment]
There's no bug here, this is expected comparing function pointers should behave the same with or without the `usize` cast.

What is more surprising is that they print the same. This indicates that comparison is non-deterministic... which is rather problematic indeed, and could break plenty of LLVM optimizations.

**Comment by RalfJung** [comment]
Indeed this can be turned into a demonstration of non-deterministic comparison:
```rust
#[inline(never)]
fn nop(x: usize) -> usize { x }

fn main() {
    fn x() {}
    fn y() {}

    let a = x as usize;
    let b = y as usize;
    
    assert_eq!(nop(a), nop(b));
    assert_eq!(a, b);
}
```
The second assertion fails, the first passes (in release mode on 1.45.2). That's no good. In principle this could lead to a soundness bug, though I am not sure if that can be actually done in practice.

Cc @rust-lang/wg-unsafe-code-guidelines @rust-lang/lang

**Comment by RalfJung** [comment]
This is an LLVM bug: https://bugs.llvm.org/show_bug.cgi?id=47090

**Comment by RalfJung** [comment]
But MIR optimizations also have to be aware that folding equality tests on functions is subtle (Cc @rust-lang/wg-mir-opt). And @oli-obk recently had to prevent me from making a similar mistake for pointer equality tests in CTFE (Cc @rust-lang/wg-const-eval).

**Comment by RalfJung** [comment]
The LLVM bug has been fixed. @Mark-Simulacrum (pinging you in lieu of there being a way to ping the LLVM WG), do you usually backport such fixes or wait for the next release?

**Comment by Mark-Simulacrum** [comment]
cc @cuviper @nikic @nagisa (pinging LLVM WG)

I suspect we'll want to backport the patch ourselves, and try to nominate it for LLVM 11 (since that's not yet released, and we're currently on a release candidate). https://reviews.llvm.org/D87123 is the thing to backport I think.

**Comment by apiraino** [comment]
Assigning `P-medium` as discussed as part of the [Prioritization Working Group procedure](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/I-prioritize.20.2373722.20Invalid.20equality.20check.20result.20for.20usize.E2.80.A6) and removing `I-prioritize`.

**Comment by cuviper** [comment]
Discussion on the LLVM bug is that it's too late for 11.0.0, but could be added to 11.0.1.

If someone wants to see the fix sooner in rust's fork, I'm happy to review PRs:
https://rustc-dev-guide.rust-lang.org/backend/updating-llvm.html#bugfix-updates
