### ISSUE TITLE
Add missing checks for #[doc(alias = "")]

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/rust#73721]
Now that #72780 has been merged, only a few checks remain to be added in order to stabilize this feature.

First, we need to actually perform those checks in the compiler directly instead of rustdoc.

You mentioned other checks too @ollie27 ?

This issue is part of #50146.

**Comment by ollie27** [comment]
> You mentioned other checks too @ollie27 ?

We should reject `#[doc(alias = "")]` on items that don't actually appear in the search index such as `extern` blocks and `impl`s.

**Comment by GuillaumeGomez** [comment]
Ok, makes sense! Last question: I remember you telling that you'd prefer this check in rustc directly instead of rustdoc. I can move things there, just wanted to check one last time before doing it.

**Comment by ollie27** [comment]
> I remember you telling that you'd prefer this check in rustc directly instead of rustdoc. I can move things there, just wanted to check one last time before doing it.

Yeah, rustc validates some attributes in https://github.com/rust-lang/rust/blob/master/src/librustc_passes/check_attr.rs and it might make sense to validate the `#[doc]` attribute there as well.

**Comment by GuillaumeGomez** [comment]
Since #74148 has been merged, we can close this issue.

**Comment by GuillaumeGomez** [comment]
Ok! Putting #75740 on hold then!
