### ISSUE TITLE
#inline(never) is not respected

### ISSUE THREAD

**Issue by jrmuizel** [rust-lang/rust#73739]
I tried this code:

```rust
#[inline(never)]
fn demo(s: &str) -> &str {
    s
}

pub fn main() -> &'static str {
    demo("input string")
}
```

it compiles to:
```asm
example::main:
        lea     rax, [rip + .L__unnamed_1]
        mov     edx, 12
        ret

.L__unnamed_1:
        .ascii  "input string"
```
which has `demo` inlined into `main`

This worked properly in Rust 1.11 but broke in Rust 1.12 and remains broken.

**Comment by bugadani** [comment]
[godbolt.org](https://godbolt.org/z/MnGVT2)

**Comment by bugadani** [comment]
Also, attribute is respected for public functions: [godbolt.org](https://godbolt.org/z/M6oJaZ)

**Comment by nbdd0121** [comment]
I suspect this is a LLVM bug.

**Comment by jrmuizel** [comment]
Indeed. I've filed https://bugs.llvm.org/show_bug.cgi?id=46463.

**Comment by jyn514** [comment]
@rustbot modify labels: S-blocked A-codegen A-LLVM

Not sure about the codegen one.

**Comment by hanna-kruppe** [comment]
I don't think this is an LLVM bug. The `inline(never)` attribute controls inlining but it does not make the function opaque to other inter-procedural analyses and optimizations, which can appear to have similar effects to inlining, especially in trivial examples like this. In particular, the generated code in this example can be explained by a combination of (1) noticing that `demo()` returns its argument unmodified and (2) noticing `demo()` has no effects other than this return value.

**Comment by nagisa** [comment]
Furthermore any form of the inline attribute it is [just a "hint"](https://doc.rust-lang.org/stable/reference/attributes/codegen.html#the-inline-attribute) and is not required to be honored by the compiler.

**Comment by nikic** [comment]
@hanna-kruppe is correct, this is not a bug on the LLVM side. There was some discussion that this semantic could be covered by a new `noipa` attribute, which is supported by GCC. (Though I haven't really heard *why* one would be interested in this.)

**Comment by workingjubilee** [comment]
@lovely-error You may open a new issue explaining your use-case if you like.

But if it's just for optimization purposes, the problem is not that `#[inline(never)]` does not reduce inlining. It does. It's that you can't hide something in an `#[inline(never)] fn monomorphic` that could change the global state in a way that another instantiation couldn't see. That could provide illogical results if it is instantiated twice.
