### ISSUE TITLE
[ER] const from_bits/to_bits for f32/f64

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust#73736]
This is an enhancement request. I'd like u32::from_bits, u64::from_bits, and f32::to_bits, f64::to_bits usable in const functions. I think today they can be implemented using const_transmute:
```rust
#![feature(const_transmute)]
const fn from_bits(v: u32) -> f32 {
    unsafe { std::mem::transmute(v) }
}
const fn to_bits(v: f32) -> u32 {
    unsafe { std::mem::transmute(v) }
}
fn main() {}

**Comment by Ryan1729** [comment]
Making `two_bits` and `from_bits` usable in const functions was also mentioned as an aside in https://github.com/rust-lang/rust/issues/57241

**Comment by Dylan-DPC** [comment]
Closing this as it will be covered by #57241
