### ISSUE TITLE
Suggest creating a `const` when calling a `const` function in an array initializer

### ISSUE THREAD

**Issue by Aaron1011** [rust-lang/rust#73734]
The following code:

```rust
fn main() {
    let strs: [String; 5] = [String::new(); 5];
}
```

gives the following error:

```
error[E0277]: the trait bound `std::string::String: std::marker::Copy` is not satisfied
 --> src/main.rs:2:29
  |
2 |     let strs: [String; 5] = [String::new(); 5];
  |                             ^^^^^^^^^^^^^^^^^^ the trait `std::marker::Copy` is not implemented for `std::string::String`
  |
  = note: the `Copy` trait is required because the repeated element will be copied

```

However, `String::new()` is a `const fn`, so this code can be made to compile by creating a new `const` item:

```rust
fn main() {
    const EMPTY: String = String::new();
    let strs: [String; 5] = [EMPTY; 5];
}
```

We should suggest this to user when a `const` function is being called in the array initializer.

<strike>Assuming that https://github.com/rust-lang/rfcs/pull/2920 is accepted, we could eventually suggest an inline `const` block.</strike>
On Nightly, we could suggest an inline `const` block.

**Comment by Aaron1011** [comment]
I think this would make a good first issue for someone looking to get started contributing. I'd be happy to mentor anyone who wants to work on this.

**Comment by henryboisdequin** [comment]
@Aaron1011 Is this still an issue that I can work on?

**Comment by Aaron1011** [comment]
@henryboisdequin Yes, assuming that @DavidHusicka is no longer working on this.

**Comment by henryboisdequin** [comment]
Should I claim it?

**Comment by Aaron1011** [comment]
@henryboisdequin: It looks like DavidHusicka hasn't had any activity this month, so I think it would be fine for you to take the issue. Feel free to reach out to me if you have any questions about how to get started implementing this.
