### ISSUE TITLE
Separate --remap-path-prefix for diagnostics and debug info

### ISSUE THREAD

**Issue by betamos** [rust-lang/rust#73740]
> Remap source path prefixes in all output, including compiler diagnostics, debug information, macro expansions, etc.

https://doc.rust-lang.org/rustc/command-line-arguments.html#--remap-path-prefix-remap-source-names-in-output

On Fuchsia, we have set up remapping for the purpose of debug info, which creates path relative to the build directory. However, when these paths are printed as part of compiler messages, CWD is usually a different directory, breaking "clickable" file/line references in e.g. VSCode. Thus, we'd benefit from having a separate path remapping for debug info and diagnostics. Perhaps this generalizes to more than these two cases?

**Comment by pcwalton** [comment]
I've run into this as an annoyance that cost me about an hour of debugging. An alternative would be to simply print the original, unremapped path alongside the remapped one.

**Comment by Urgau** [comment]
We now have [`--remap-path-scope`](https://doc.rust-lang.org/nightly/unstable-book/compiler-flags/remap-path-scope.html) from [trim-paths RFC 3127](https://github.com/rust-lang/rust/issues/111540) to distinguishes diagnostics, debug info and more.

Closing in favour of the [tracking issue](https://github.com/rust-lang/rust/issues/111540).
