### ISSUE TITLE
Confusing error message when not having a variable name

### ISSUE THREAD

**Issue by AZanellato** [rust-lang/rust#73750]
I had a weird error message on the rust compiler when trying to compile something like this:
```
let Struct { name: "a".to_string() }
```

[Here](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=91088bdc0120ad0ab60ee1428b4c66ad) is a playground link that reproduces it better.

This gives out a weird `expected ','` error, which wasn't at all what I was expecting. Certainly because of my sleepy state, but still weird.

**Comment by estebank** [comment]
Btw, the parser was expecting a comma because let doesn't just take identifiers, but patterns, which let's you write `let Struct { name, ..} = struct_val;`.

Would the following have been enough to help you?

```
error: expected `,`
  --> src/main.rs:10:13
   |
 9 |     let Test {
   |         ---- while parsing this pattern
10 |       name: "a".to_owned()
   |             ^^^
```

**Comment by AZanellato** [comment]
I discovered this shortly thereafter! I think that would happen a ton. Maybe something along the lines of "Maybe you missed a name"? 

But that would be awesome already :smile:
