### ISSUE TITLE
Make std::default::Default trait compulsory or rust system by default should allow Default::default() to be assigned to any struct.

### ISSUE THREAD

**Issue by amber-m-o-r-e** [rust-lang/rust#73760]
It will be best and most useful if we will do std::default::Default trait compulsory for every struct declaration or will provide a default value for Default::default() without traits implementation. So the variable can be declared with a default value when it is not known and can be a shadow during the program. There are most of the libraries having Default traits not implemented, so the second solution will be a great choice.

**Comment by Mark-Simulacrum** [comment]
This is backwards incompatible and regardless would need to go through the RFC process as a fairly major change. It's also true that not all types have a default (e.g., a token type representing successful authentication).
