### ISSUE TITLE
`if let` for match arm guard?

### ISSUE THREAD

**Issue by lzutao** [rust-lang/rust#73764]
Does it have any design for `if let` in [match arm guard](https://doc.rust-lang.org/nightly/reference/expressions/match-expr.html#match-expressions)?

```rust
match "foobar" {
    s if let Some(tail) = tail.strip_prefix("bar") => dbg!(tail),
    _ => "barbaz",
}
```

Without `if let`, I have to indent the `if` expression a bit:

```rust
match "foobar" {
    s => {
        if let Some(tail) = tail.strip_prefix("bar") {
            dbg!(tail)
        } else {
            "barbaz"
        }
    }
}
```

**Comment by petrochenkov** [comment]
There's an accepted RFC about this - https://github.com/rust-lang/rfcs/blob/master/text/2294-if-let-guard.md

**Comment by lzutao** [comment]
Thanks. So the `if let` for guard hasn't been implemented.
Should I close this issue for #51114 instead ?

**Comment by nagisa** [comment]
Duplicate of #51114
