### ISSUE TITLE
Type ascription misdiagnosis when trying to use serde_json::json!

### ISSUE THREAD

**Issue by saethlin** [rust-lang/rust#73777]
Hi @estebank I didn't forget about your encouragement on Twitter: https://twitter.com/ekuber/status/1255881826855313409?s=20

I forgot a comma at the end of the first key-value pair:
```rust
fn main() {
    let json = serde_json::json!({
        "domain_name": "redjack.com"
        "passive_provenance": [420, 69],
    });
}
```
On the latest nightly compiler this is explicitly diagnosed as an attempt to use type ascription:
```
error: expected type, found `"redjack.com"`
 --> src/main.rs:3:24
  |
3 |         "domain_name": "redjack.com"
  |                      - ^^^^^^^^^^^^^ expected type
  |                      |
  |                      tried to parse a type due to this type ascription
  |
  = note: `#![feature(type_ascription)]` lets you annotate an expression with a type: `<expr>: <type>`
  = note: see issue #23416 <https://github.com/rust-lang/rust/issues/23416> for more information
```
On stable, it's arguably much worse, the error only makes sense if you know the compiler thinks this is type ascription but feature is not mentioned:
```
error: expected type, found `"redjack.com"`
 --> src/main.rs:3:24
  |
3 |         "domain_name": "redjack.com"
  |                      - ^^^^^^^^^^^^^ expected type
  |                      |
  |                      tried to parse a type due to this
```

**Comment by estebank** [comment]
@dtolnay is this something that could be handled in serde_json? I had a cursory look and saw that there already macro cases exclusively for better diagnostics, but the macro was big enough that I couldn't disentangle how to write a macro case for `($expr : $expr*)`.

Ideally we would handle this in the compiler more gracefully, but [changing the RHS here from a string literal to a type makes the compiler be a bit more helpful](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=a7e400d4f476e486eeb9ab77cee13c9e).

**Comment by dtolnay** [comment]
Yeah I opened a fix in https://github.com/serde-rs/json/pull/688.

```console
error: no rules expected the token `"passive_provenance"`
 --> $DIR/missing_comma.rs:4:9
  |
3 |         "domain_name": "redjack.com"
  |                                     - help: missing comma here
4 |         "passive_provenance": [420, 69],
  |         ^^^^^^^^^^^^^^^^^^^^ no rules expected this token in macro call
```

**Comment by estebank** [comment]
Closing as per the fix in serde and CCing https://github.com/rust-lang/rust/issues/34255 which tracks the work around type ascription more generally.
