### ISSUE TITLE
Printing a large f64 results in incorrect output

### ISSUE THREAD

**Issue by HeroicKatora** [rust-lang/rust#73772]
I tried this code:

```rust
fn main() {
    println!("{} {} {}", 2.0_f64.powi(64), 1u128 << 64, (1u128 << 64) as f64)
}
```

I expected to see this happen: prints three times the same number:
```
18446744073709551616 18446744073709551616 18446744073709551616
```

Instead, this happened: the displayed f64 values are slightly imprecise:
```
18446744073709552000 18446744073709551616 18446744073709552000
```

However, the value can be represented exactly as a `f64` and indeed this appears not to be the issue:

```
println!("{:?}", f64::to_be_bytes(2.0_f64.powi(64)))
// [67, 240, 0, 0, 0, 0, 0, 0]
//  ^^^^^ ^^^^^^^^^^^^^^^
// exponent of 67*16 + 15 = 1087 = 1023 + 64 as expected
//            mantissa of zeroes as expected
```

### Meta

Occurs on:

* stable (1.44.1)
* nightly
* `1.34.2`

A [zulip conversation](https://rust-lang.zulipchat.com/#narrow/stream/122651-general/topic/general.20questions/near/202102983) where this was originally discovered.

**Comment by nbdd0121** [comment]
I don't think it is a bug, because `18446744073709552000f64==18446744073709551616f64`. Node also prints 18446744073709552000 for this number.

**Comment by HeroicKatora** [comment]
They are right, sorry for the noise....
