### ISSUE TITLE
config file for rustc

### ISSUE THREAD

**Issue by nu8** [rust-lang/rust#73784]
In the past I have used something like `C:\Users\Steven\.cargo\config`:

~~~
[target.x86_64-pc-windows-gnu]
linker = "x86_64-w64-mingw32-gcc"
~~~

However now I want to do that, but just for `rustc.exe`, not cargo. I tried
this:

~~~
[target.x86_64-pc-windows-gnu]
linker = "C:/msys2/mingw64/bin/cc.exe"
~~~

but `rustc.exe` doesnt seem to pay attention to that file or folder. Is some
method available to do this?

**Comment by nu8** [comment]
As a workaround, I can create `config`:

~~~
-Clinker=C:\msys2\mingw64\bin\cc.exe
~~~

Then:

~~~
rustc '@config' a.rs
~~~

but this is not ideal

**Comment by jonas-schievink** [comment]
This feature would need to go through a Major Change Proposal, or maybe even a full RFC, so closing in favor of that route.
