### ISSUE TITLE
`std::str::pattern::Pattern` cannot be accessed on stable Rust

### ISSUE THREAD

**Issue by popzxc** [rust-lang/rust#73789]
Standard library publicly exposes [`std::str::pattern::Pattern`](https://doc.rust-lang.org/std/str/pattern/trait.Pattern.html) in stable API, such as [`str::split`](https://doc.rust-lang.org/std/primitive.str.html#method.split), while this trait remains unstable.

This leads to the situation when it's not trivial to implement a method fully compatible with the existing `str` splitting API, e.g. it's impossible to create a function with the following signature:

```rust
fn splitn_exact<'a, P: Pattern<'a>>(input: &'a str, n: usize, pat: P) -> Option<SplitN<'a, P>>
```

Instead, an alternative to the `Pattern` trait must be created manually.

I wonder if it's possible to make this trait safe to import and rely on it, but forbid implementing, so it'll be easier to create new functions using existing abstractions.

**Comment by jonas-schievink** [comment]
The trait will be usable once stabilized, which is tracked in https://github.com/rust-lang/rust/issues/27721, so closing in favor of that.
