### ISSUE TITLE
shorthand addition '+=' . A String and an usize added .. with no error raised from teh compiler 

### ISSUE THREAD

**Issue by olivierEsmieu** [rust-lang/rust#73799]
1)here is the code 
    let acc = 0;
    let x = "1".to_string();
    acc += x;

2)cargo run..error message
error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.

**Comment by jonas-schievink** [comment]
Please provide more info, as I can't reproduce this

**Comment by olivierEsmieu** [comment]
Hi Jonas
No more code than above. Below the complete log.. 
Olivier

error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.
note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports
note: rustc 1.40.0 (73528e339 2019-12-16) running on i686-pc-windows-msvc
note: compiler flags: -C debuginfo=2 -C incremental --crate-type bin
note: some of the compiler flags provided by cargo are hidden
error: could not compile `day-06`.
To learn more, run the command again with --verbose.

**Comment by olivierEsmieu** [comment]
forgot (sorry)..
thread 'rustc' panicked at 'slice index starts at 286862720 but ends at 25118402', src\libcore\slice\mod.rs:2670:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
