### ISSUE TITLE
Generic function instantiation uses VTable instead of actual function

### ISSUE THREAD

**Issue by DaemonSnake** [rust-lang/rust#73801]
### I tried this code:

```rust
trait MyTrait {
    fn action(self);
}

struct ImplementsMyTrait {}
impl MyTrait for ImplementsMyTrait { fn action(self) { }}

fn call_action<T:MyTrait>(item: T) {
     item.action();
}

pub fn main() {
    let a = ImplementsMyTrait{};
    call_action(a)
}
```

### I expected to see this happen:

As the real type of `a` is know at compile time we expect that the instantiation of `call_action` will call `<ImplementsMyTrait::action for MyTrait>` directly with the object.

### Instead, this happened:

Instead in `call_action<ImplementsMyTrait>`'s the compiler reads inside the VTable of the object.
We could expect such a decision if Rust had inheritance but as it's not the case I consider this to be a bug.

This means that projects that don't want to pay such a price (dynamism) will have to drop the usage of traits and won't have a good system to write interfaces. I am currently in such a position.

You can see minimal example in godbolt [here](https://rust.godbolt.org/z/5y2XvJ) and the contrast with what we would expect.

### Meta

`rustc --version --verbose`:
```
rustc 1.44.0 (49cae5576 2020-06-01)

binary: rustc

commit-hash: 49cae55760da0a43428eba73abcb659bb70cf2e4

commit-date: 2020-06-01

host: x86_64-unknown-linux-gnu

release: 1.44.0

LLVM version: 9.0

Compiler returned: 0
```

<details><summary>Backtrace</summary>
<p>

```
```

</p>
</details>

**Comment by jonas-schievink** [comment]
Please provide a working example that reproduces the issue

**Comment by DaemonSnake** [comment]
> Please provide a working example that reproduces the issue

Updated!
You can also follow the godbolt link: https://rust.godbolt.org/z/5y2XvJ

**Comment by hanna-kruppe** [comment]
The godbolt link does not demonstrate "reading the vtable", both examples there use *direct* calls without any vtable reference. The only difference is that the variant using a trait goes through the GOT for those calls, but it's still a direct call, and the GOT is only involved because the functions being called have public linkage. In the other example (without traits), `A::action` and `B::action` get internal linkage, but [if you change that](https://rust.godbolt.org/z/meo67T), then those calls will go through the GOT as well.

**Comment by nbdd0121** [comment]
I guess you are confused by the name `<example::A as example::MyTrait>::action`. This is not vtable, it is the fully qualified syntax for trait methods (previously known as UFCS). It is briefly mentioned in [the rust book](https://doc.rust-lang.org/book/ch19-03-advanced-traits.html?highlight=function,call,qualif#fully-qualified-syntax-for-disambiguation-calling-methods-with-the-same-name).
