### ISSUE TITLE
Outdated `hashbrown` dependency in std is causing duplicated crate

### ISSUE THREAD

**Issue by poliorcetics** [rust-lang/rust#73837]
https://github.com/rust-lang/rust/blob/25687caa2e4e35b31c29e28998710670e9d54ee9/src/libstd/Cargo.toml#L26

Currently `libstd` uses version `0.6.2` for `hashbrown`. This causes a duplication for the `auto-cfg` crate. Here is the relevant output from `cargo tree -d` when ran on `rust-lang/rust`:

```text
autocfg v0.1.7
[build-dependencies]
└── hashbrown v0.6.2
    └── std v0.0.0 (/Users/alexis/Projects/rust/rust/src/libstd)
        ├── proc_macro v0.0.0 (/Users/alexis/Projects/rust/rust/src/libproc_macro)
        ...

autocfg v1.0.0
[build-dependencies]
├── crossbeam-utils v0.7.2
...
```

**Comment by Mark-Simulacrum** [comment]
Is this causing some difficulty? Otherwise it seems like it's not a problem that needs to be solved. There's already active work on updating hashbrown ongoing.

**Comment by poliorcetics** [comment]
That's not directly causing a problem to the best of my knowledge.

Discussion on discord led me to believe opening an issue to notify it was a good idea, I didn't know there was already work being done to update it.

**Comment by mbrubeck** [comment]
For reference (in case anyone else finds this issue while searching for info), the work to upgrade hashbrown is #70052.
