### ISSUE TITLE
A Rust script runner/interpreter.

### ISSUE THREAD

**Issue by metaspook** [rust-lang/rust#73869]
I'll be so cool if can run a .rs script without compile it using 'rust' command 
like we do in bash
```
$ bash hello.sh
Hello World!
$ 
```

for rust it could be
```
$ rust hello.rs
Hello World!
$ 
```

By also adding a shebang:
```
#!/usr/bin/env rust

fn main() {
    println!("Hello, world!");
}
```
We can execute by simply:
```
$ chmod +x main.rs
$ ./main.rs
```

If it's possible plz plz add the 'rust' command for script interpreter like feature like ..... this I do not see any other lacking without having this scripting like feature in Rust it will be sooooo great. 🙏🙏🙏 one day Rust will be everywhere...

**Comment by jonas-schievink** [comment]
https://github.com/DanielKeep/cargo-script handles this use case, so I'll close this issue in favor of that.

**Comment by ratijas** [comment]
Wow, that was hella cringy and fanboy-ish, but hey! Thanks for the link to cargo-script — it looks pretty considerate.
