### ISSUE TITLE
Unable to install Rust using rustup

### ISSUE THREAD

**Issue by YuGiOhJCJ** [rust-lang/rust#73873]
Hello,

Installing Rust using rustup is [the recommended way](https://www.rust-lang.org/tools/install).
However, it does not work on my machine:
```
$ curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
info: downloading installer
sh: line 372: /tmp/tmp.SUeYFJ/rustup-init: No such file or directory
```

I am on a Raspberry Pi 4 with Slackware ARM 14.2.
```
$ uname -a
Linux rpi4 5.4.47-v7l+ #1322 SMP Wed Jun 17 17:58:52 BST 2020 armv7l BCM2711 GNU/Linux
```

Do you know how to fix that please?

Thank you.
Best regards.

**Comment by jonas-schievink** [comment]
Rustup issues should be filed at https://github.com/rust-lang/rustup. Also feel free to ask in the forum at https://users.rust-lang.org/.
