### ISSUE TITLE
Standardize bibliographic citations in docs

### ISSUE THREAD

**Issue by pierwill** [rust-lang/rust#73877]
There are several bibliographic citations in the rustc API docs (examples [here](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_ast_pretty/pp/index.html), [here](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_span/hygiene/index.html), and [here](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_data_structures/graph/dominators/index.html)). I'd like to propose standardizing these references.

Citation styles can inspire strong feelings. The *Chicago Manual of Style* provides a style that is especially flexible and attractive. Example: `Matthew Flatt et al., “Macros That Work Together: Compile-Time Bindings, Partial Expansion, and Definition Contexts,” *Journal of Functional Programming* 22, no. 2 (March 1, 2012): 181–216, doi:10.1017/S0956796812000093.`

**Comment by JohnTitor** [comment]
Closing as fixed by #73881.
