### ISSUE TITLE
failed to run `rustc` to learn about target-specific information

### ISSUE THREAD

**Issue by jcornaz** [rust-lang/rust#73874]
Hello, 

I don't know if it is related, but after deleted `~/.cargo` folder, I can no longer compile any rust project.

```
$ cargo new abc
$ cd abc
$ cargo build
error: failed to run `rustc` to learn about target-specific information

Caused by:
  could not execute process `sccache rustc - --crate-name ___ --print=file-names --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (never executed)

Caused by:
  No such file or directory (os error 2)
```

Some informations:
* I am on linux
* I installed rust via rustup (`curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`)

```
$ rustup show
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/jonathan/.rustup

stable-x86_64-unknown-linux-gnu (default)
rustc 1.44.1 (c7087fe00 2020-06-17)

$ rustc -Vv
rustc 1.44.1 (c7087fe00 2020-06-17)
binary: rustc
commit-hash: c7087fe00d2ba919df1d813c040a5d47e43b0fe7
commit-date: 2020-06-17
host: x86_64-unknown-linux-gnu
release: 1.44.1
LLVM version: 9.0
```

I tried uninstalling rustup, remove `~/.rustup` and reinstall from scratch, but nothing help. I am stuck.

**Comment by jonas-schievink** [comment]
You have somehow set up sccache and presumably deleted the executable. Please ask setup-related questions like this on the user forum at https://users.rust-lang.org/.

**Comment by jcornaz** [comment]
> You have somehow set up sccache and presumably deleted the executable. Please ask setup-related questions like this on the user forum at https://users.rust-lang.org/.

@jonas-schievink Isn't the fact that deleting a user folder (anything in `~/`) can cause a non-recoverable failure a bug of the toolchain?

**Comment by jonas-schievink** [comment]
You have deleted the directory containing sccache, but have still somehow configured Cargo to use it. That is not a toolchain bug.
