### ISSUE TITLE
Error: constant expression depends on a generic parameter

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#73899]
Successor of #61935 and #61383.

This code:

```rust
#![feature(const_generics)]
trait Foo {}

impl<const N: usize> Foo for [(); N]
where
    Self:FooImpl<{N==0}>
{}

trait FooImpl<const IS_ZERO: bool>{}

impl FooImpl<{0u8==0u8}> for [();0] {}

impl<const N:usize> FooImpl<{0u8!=0u8}> for [();N] {}

fn foo<T: Foo>(v: T) {}

fn main() {
    foo([]);
    foo([()]);
}
```

Gives this error message (on nightly):
```
error: constant expression depends on a generic parameter
 --> src/main.rs:6:10
  |
6 |     Self:FooImpl<{N==0}>
  |          ^^^^^^^^^^^^^^^
  |
  = note: this may fail depending on what value the parameter takes
```

It'd be great if this could work so that you can implement a trait differently for different values of type parameters.

cc @lcnr who suggested to open a new issue for this.

**Comment by lcnr** [comment]
background: his error was introduced in #70107 as the previous state was unsound, see https://github.com/rust-lang/rust/pull/70107#issuecomment-643826952:

> unfortunately, without this check, const generic would be unsound. The problem is really that const generics is incomplete and we're missing some critical components that are necessary to get them working properly. Const generics is unstable ("very unstable" in some sense in that it explicitly warns you things may break if you try to use them at the moment). We're grateful to have people testing them so that we can address the flaws before stabilising the feature, but we haven't yet reached the point where we can guarantee any kind of stability. Hopefully that will change before too long :)

**Comment by lcnr** [comment]
With `feature(const_evaluatable_checked)` this test is now working as expected.

Marking as `E-needs-test`.

**Comment by est31** [comment]
@lcnr if I try this:

```Rust
#![feature(const_evaluatable_checked, min_const_generics)]
trait Foo {}

impl<const N: usize> Foo for [(); N]
where
    Self:FooImpl<{N==0}>
{}

trait FooImpl<const IS_ZERO: bool>{}

impl FooImpl<{0u8==0u8}> for [();0] {}

impl<const N:usize> FooImpl<{0u8!=0u8}> for [();N] {}

fn foo<T: Foo>(v: T) {}

fn main() {
    foo([]);
    foo([()]);
}
```

I get this error:
```
error: generic parameters may not be used in const operations
 --> src/main.rs:6:19
  |
6 |     Self:FooImpl<{N==0}>
  |                   ^ cannot perform const operation using `N`
  |
  = help: const parameters may only be used as standalone arguments, i.e. `N`
```

Using the nightly from playground `1.50.0-nightly (2020-11-21 da384694807172f0ca40)`

**Comment by lcnr** [comment]
you need full `const_generics` for this, we should probably add a note here which recommends using `feature(const_generics)` and `feature(const_evaluatable_checked)` here.

**Comment by est31** [comment]
@lcnr alright that works. I'll file a PR
