### ISSUE TITLE
Hiring Rust Developers @ 1Password

### ISSUE THREAD

**Issue by mcichosz** [rust-lang/rust#73901]
Hi There!

I was wondering if its possible to add our job into the newsletter? We are hiring multiple Rust Developers @ 1Password. Here is the link: https://jobs.lever.co/1password/0623888f-0125-41b9-9902-eae8cfeae0c3

Thanks!
Margaret

**Comment by jonas-schievink** [comment]
This Week in Rust lists job postings: https://github.com/emberian/this-week-in-rust

This is the repository for the Rust compiler and standard library though.
