### ISSUE TITLE
New asm! Syntax Misconceptions

### ISSUE THREAD

**Issue by VizorKit** [rust-lang/rust#73934]
I'm new to rust. The new assembly syntax drew me in. I hate inline assembly.

I tried to set up my development environment. I was able to get my program to compile, and generate somewhat the output I was expecting.

>main.rs
```

#![no_main]
#![no_std]
#![feature(asm)]
use core::panic::PanicInfo;

#[no_mangle]
fn _start() {
    unsafe {
        asm!(
            /// "lui sp, 0x80004" // When uncommented, this at least compiles.
            in("sp") 0x80004 /// Error here.
        )
    }
}
```
I'm leaving out my linker file, and config, but the target is for riscv32imac-unknown-none-elf.

The line "lui sp, 0x80004" at least compiles I have problems with it in the .list not actually storing the hex, but converting it to decimal but thats a separate issue.

I get this syntax issue when trying to compile the new syntax.
```
 unsafe {
        asm!(
            in("x2") 0x80004 
        )
    }
```
```
cargo +nightly build
   Compiling vizorkit v0.1.0 (/home/chris/vizorkit)
error: expected expression, found keyword `in`
  --> src/main.rs:11:13
   |
11 |             in("x2") 0x80004
   |             ^^ expected expression
```
weird. So I realized it almost compiles if I put a nop before it!

```
 unsafe {
        asm!(
            "nop",
            in("x2") 0x80004 
        )
    }
```
```
cargo +nightly build
   Compiling vizorkit v0.1.0 (/home/chris/vizorkit)
error: invalid register `x2`: the stack pointer cannot be used as an operand for inline asm
```

So I have 3 questions.
Could I understand why my assembly for "lui sp, 0x80004" converted to 524292? even though I would clearly like the address loaded.
Could I understand why I need to have a do nothing instruction first?
Could I understand why I cant use a stack pointer as an operand?

**Comment by jonas-schievink** [comment]
Hi! This issue tracker is mainly meant for bug reports and concrete, small feature requests. Questions like this are better asked in the user forum at https://users.rust-lang.org/ or on [one of the chat platforms](https://www.rust-lang.org/community) used by the Rust community.
