### ISSUE TITLE
Remove semicolons

### ISSUE THREAD

**Issue by Voodlaz** [rust-lang/rust#73966]
It's really annoys people when they forget to put a semicolon in the end of line. So I think that it would make a syntax more nicer to use, like in Python.

**Comment by jonas-schievink** [comment]
Hi! Additions or changes to the language need to go through our [RFC process](https://github.com/rust-lang/rfcs). Before an RFC is written, the feature can also be discussed in our [internals forum](https://internals.rust-lang.org/) to find other people interested in it.

Closing in favor of an RFC.
