### ISSUE TITLE
Function monomorphization site that causes post-monomorphization errors is never shown

### ISSUE THREAD

**Issue by oli-cosmian** [rust-lang/rust#73961]
The following code does not highlight the `foo::<u32>()` call, even though removing it will remove the error. 

```rust
#[warn(const_err)]

trait ZstAssert: Sized {
    const ASSERT: () = [()][(std::mem::size_of::<Self>() != 0) as usize];
}

impl<T> ZstAssert for T {}

fn foo<T>() {
    #[allow(path_statements)]
    {
        T::ASSERT
    }
}

fn main() {
    foo::<u32>();
}
```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=43f37096b96e839ca8b0da7eeb4922c8))

Errors:

```
   Compiling playground v0.0.1 (/playground)
warning: any use of this value will cause an error
 --> src/main.rs:4:24
  |
4 |     const ASSERT: () = [()][(std::mem::size_of::<Self>() != 0) as usize];
  |     -------------------^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^-
  |                        |
  |                        index out of bounds: the len is 1 but the index is 1
  |
note: the lint level is defined here
 --> src/main.rs:1:8
  |
1 | #[warn(const_err)]
  |        ^^^^^^^^^

error: erroneous constant encountered
  --> src/main.rs:12:9
   |
12 |         T::ASSERT
   |         ^^^^^^^^^

error: aborting due to previous error; 1 warning emitted

error: could not compile `playground`.

To learn more, run the command again with --verbose.

```

**Comment by oli-obk** [comment]
cross post from [zulip](https://rust-lang.zulipchat.com/#narrow/stream/260443-project-const-generics/topic/meeting.202021-04-20/near/235394316)

> I have an idea for how to create a backtrace for post monomorphization errors. It's not great, but better than the status quo: in the monomorphization collector, we already have that stack available, we just can't feed it into any queries or whatever is producing errors. So we wrap all possibly erroring calls with something that checks the error count before and after the call. If the count went up, print the stack mentioning that the last error occurred at this monomorphization stack. To reduce the noise, only do that if the current item is generic

**Comment by oli-obk** [comment]
closing in favour of the more detailed #85155
