### ISSUE TITLE
Direct implementations should take precedence on foreign blanket implementations

### ISSUE THREAD

**Issue by corebreaker** [rust-lang/rust#74004]
Here is an example: [Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=daab4d09fe5141abdc0852a671561570) which does not complie:
```log
error[E0119]: conflicting implementations of trait `std::string::ToString` for type `X`:
  --> src/main.rs:11:1
   |
11 | impl ToString for X {
   | ^^^^^^^^^^^^^^^^^^^
   |
   = note: conflicting implementation in crate `alloc`:
           - impl<T> std::string::ToString for T
             where T: std::fmt::Display, T: ?Sized;

error: aborting due to previous error

For more information about this error, try `rustc --explain E0119`.
error: could not compile `playground`.
```

Here the implementation of the trait `ToString` is more efficient than the implementation:
`impl<T> std::string::ToString for T where T: std::fmt::Display, T: ?Sized`

That's a pity that this version of `ToString` implementation can't be used.

That forces to implements this `to_string` method into another trait or method.

**Comment by jonas-schievink** [comment]
This is covered by specialization, which is currently unstable. Closing in favor of that. Other than that, changes like this need to go through the RFC process.
