### ISSUE TITLE
Range for 64bit integers does not implement ExactSizeIterator

### ISSUE THREAD

**Issue by Soveu** [rust-lang/rust#74013]
I tried this code:

```rust
pub fn solve(n: i32) -> i32 {
    let n = n as u64;
    let mut range = 0..n;
    
    while range.len() != 1 {
        let mid = (range.start + range.end) / 2;
        
        if mid*mid > n {
            range.end = mid;
        } else {
            range.start = mid;
        }
    }
    
    return range.start as i32;
}
```

I expected to see this happen:
Code compiles

Instead, this happened:
Compiler throws error about no `len()` method for `Range<u64>`

### Meta
discovered on rust on [https://binarysearch.io](binarysearch)

[Part of source code responsible for this](https://doc.rust-lang.org/src/core/iter/range.rs.html#269)
</p>
</details>

**Comment by leonardo-m** [comment]
What if usize is 32 bits wide? What can len() return?

**Comment by Soveu** [comment]
1. Just do `(self.end - self.start) as usize` and call it a day
2. Use `#[cfg(target_pointer_width = "64")]` to make usage only possible on 64bit platforms

**Comment by jonas-schievink** [comment]
This is intended behavior, similar to how there's `From<u8>` and `From<u16>` impls for `usize`, but not `From<u32>` and `From<u64>` – they would not work if `usize` was 16 or 32 bits in size.
