### ISSUE TITLE
f64::from(bool) and f32::from(bool)

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust#74015]
I think `f64::from(bool)` and `f32::from(bool)` could be added. Currently I perform that in two steps:

`f64::from(u32::from(bool))`
`f32::from(u16::from(bool))`

**Comment by hellow554** [comment]
Funny enough, the people are aware of this problem:

```
error[E0606]: casting `bool` as `f64` is invalid
 --> src/main.rs:3:20
  |
3 |     println!("{}", true as f64);
  |                    ^^^^^^^^^^^
  |
  = help: cast through an integer first
```

I think there's a valid reason for this, but let's see

**Comment by Mark-Simulacrum** [comment]
Integer casts are essentially no-ops since the bit pattern is the same, but casting to a float would be less obvious/straightforward, IMO.

I guess you expect 1.0 as the result, same as casting through an integer gets you?

**Comment by leonardo-m** [comment]
I expect f64::from(bool) to have about the same semantics of f64::from(u32::from(bool)), yes.

**Comment by workingjubilee** [comment]
Which zero to return?

**Comment by leonardo-m** [comment]
The same as f32::from(0_u8), that should be a +0.0.

**Comment by est31** [comment]
This should be closed now, yes. Implementation PR was #100390.
