### ISSUE TITLE
Strange span in borrow error in nested match.

### ISSUE THREAD

**Issue by ehuss** [rust-lang/rust#74050]
I tried this code:

```rust
fn main() {
    let mut args = std::env::args_os();
    let _arg = match args.next() {
        Some(arg) => {
            match arg.to_str() {
                Some(s) => s,
                None => return,
            }
        }
        None => return,
    };
}
```

Previously, in 1.36 or earlier, it presented an error like this:

```
error[E0597]: `arg` does not live long enough
  --> src/main.rs:7:19
   |
5  |     let _arg = match args.next() {
   |         ---- borrow later stored here
6  |         Some(arg) => {
7  |             match arg.to_str() {
   |                   ^^^ borrowed value does not live long enough
...
13 |     };
   |     - `arg` dropped here while still borrowed
```

Starting with 1.37, the "dropped here while still borrowed" message points to an odd location:

```
error[E0597]: `arg` does not live long enough
  --> src/main.rs:7:19
   |
5  |     let _arg = match args.next() {
   |         ---- borrow later stored here
6  |         Some(arg) => {
7  |             match arg.to_str() {
   |                   ^^^ borrowed value does not live long enough
...
12 |         None => return,
   |            - `arg` dropped here while still borrowed
```

The earlier error looks more correct to me.

Bisected the change to [nightly-2019-05-24](https://github.com/rust-lang/rust/compare/37ff5d388f8c004ca248adb635f1cc84d347eda0...8869ee03d7f258e1b76a11c6fbb01b5708a9f504), I would guess maybe it is #60174.

**Comment by lcnr** [comment]
Without using any methods:
```rust
fn main() {
    let _arg = match Some(()) {
        Some(arg) => {
            match Some(&arg) {
                Some(s) => s,
                None => return,
            }
        }
        None => return,
    };
}
```
results in
```
error[E0597]: `arg` does not live long enough
  --> src/main.rs:6:24
   |
4  |     let _arg = match Some(()) {
   |         ---- borrow later stored here
5  |         Some(arg) => {
6  |             match Some(&arg) {
   |                        ^^^^ borrowed value does not live long enough
...
11 |         None => return,
   |            - `arg` dropped here while still borrowed
```

**Comment by LeSeulArtichaut** [comment]
Assigning `P-medium` [as discussed as part of the Prioritization WG procedure](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/I-prioritize.20.2374050.20Strange.20span.20in.20borrow.20error.20in.20nested.20m).

> Bisected the change to [nightly-2019-05-24](https://github.com/rust-lang/rust/compare/37ff5d388f8c004ca248adb635f1cc84d347eda0...8869ee03d7f258e1b76a11c6fbb01b5708a9f504), I would guess maybe it is #60174.

cc @matthewjasper

**Comment by matthewjasper** [comment]
This should probably be `prev_token`: https://github.com/rust-lang/rust/blob/5d429f384734a3245db8f7862e95b5adb2112705/src/librustc_parse/parser/expr.rs#L1793-L1793
