### ISSUE TITLE
Broken links of `&mut self` in Deref sections

### ISSUE THREAD

**Issue by tesuji** [rust-lang/rust#74083]
In https://doc.rust-lang.org/nightly/std/io/struct.IoSlice.html#method.as_ptr, the link to `as_mut_ptr` is broken.
Even though there is `as_mut_ptr` item in the sidebar.

This maybe one reason make #32129 happens.

**Comment by lzutao** [comment]
Maybe if there are no `DerefMut<Target = U>`  for type T:
* hide `&mut self` methods on sidebar
* Any refs to `&mut self` in U shouldn't be fragment links only.

**Comment by nbdd0121** [comment]
What would be sensible way to deal with `&mut self` ref in `U` though? It doesn't make much sense to point to the doc in `U` as well because without `DerefMut` impl you these methods aren't usable.

**Comment by lolbinarycat** [comment]
triage: such items are now hidden from the "methods from Deref" section, and the link is no longer broken.
