### ISSUE TITLE
Compiler allows #[repr(i/u128)] on structs

### ISSUE THREAD

**Issue by TyPR124** [rust-lang/rust#74082]
I tried this code:

```rust
#[repr(i128)]
#[repr(u128)]
struct Foo;
fn main() {
    println!("{}", std::mem::size_of::<Foo>());
}
```

I expected to see this happen: compilation failure

Instead, this happened: Compiles, outputs "0"

### Meta

`rustc --version --verbose`:
```
rustc 1.44.0 (49cae5576 2020-06-01)
binary: rustc
commit-hash: 49cae55760da0a43428eba73abcb659bb70cf2e4
commit-date: 2020-06-01
host: x86_64-pc-windows-msvc
release: 1.44.0
LLVM version: 9.0
```
Also: [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a62809034300d238de36941eccd094bb)

This issue has been assigned to @nbdd0121 via [this comment](https://github.com/rust-lang/rust/issues/74082#issuecomment-654428556).

**Comment by nbdd0121** [comment]
Should be a easy fix.

@rustbot claim
