### ISSUE TITLE
Forbid generic parameters in the type of const generic parameters

### ISSUE THREAD

**Issue by lcnr** [rust-lang/rust#74152]
e.g. do not allow `fn foo<T, const N: T>()` and `foo<const N: usize, const M: [u8; N]>()`.

While we may want to support this in the future, this should not be part of the MVP and causes a lot of problems
with our current approach. It causes both ICE ICE baby and breaks `foo<const N: [u8; { 1+ 4 }]>()` because `{ 1 + 4 }` contains `N` itself in its substitutions.

What probably has to done here:

- change name resolution to forbid mentions of parameters.
- stop using the parent generics in `generics_of`.

cc @eddyb @varkor @yodaldevoid

**Comment by lcnr** [comment]
note: please ping me on zulip if you want to work on this.

**Comment by varkor** [comment]
I believe we already forbade generic _type_ parameters in const generic types, but may have forgotten about other const generics. I'll review the PR soon.

**Comment by lcnr** [comment]
Afaict we removed that ban for some reason. E0671 is currently unused.
