### ISSUE TITLE
HTML generated for code blocks can be improved (and shortened)

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/rust#74180]
For example, we can have occurrences of:

```
<span class="op">+</span><span class="op">=</span>
```

In this case, we could simply have:

```
<span class="op">+=</span>
```

We also have some weird generation sometimes:

```
</span> <span class="ident">x</span> <span class="kw">in</span> <span class="kw-2">&amp;</span><span class="ident">set</span>
```

In this case, I'm not sure what ``<span class="kw-2">&amp;</span>`` is actually doing...

**Comment by Lonami** [comment]
> I'm not sure what `<span class="kw-2">&amp;</span>` is actually doing...

Knowing nothing about the generation, seems it's just applying a different "keyword" style to `&` (`x in &set`).

**Comment by GuillaumeGomez** [comment]
Thanks for the clarification! Then this span is not an issue. :)

**Comment by Lonami** [comment]
Another question worth raising is whether whitespace should be ignored when merging spans. That is, if:
```html
<span class="op">=</span><span class="op">-</span>
```

could become
```html
<span class="op">= -</span>
```

I think it should be fine as long as the styles do not alter the font size in ways it would change how spaces look (same for tabulators/newlines).

Also, I *think* `class=op` is valid HTML which would save two bytes per span. Maybe not worth doing if gzip compression is used when serving the pages anyway.

**Comment by GuillaumeGomez** [comment]
Normally it depends on the font, so we use the same font in span, it should keep the spaces. Also in the case you showed, they're not directly following each other, but it might be interesting to merge them.

As for `class=op`, I have to admit I never thought about it. The only thing to be checked is if it's working on older browser rustdoc supports.

But this is a lot of good ideas, thanks for bringing them up!

**Comment by ollie27** [comment]
#73807 might fix this.

**Comment by GuillaumeGomez** [comment]
At least improve the situation. I'll take another look once it'll merged to see if there is still weird DOM.

**Comment by GuillaumeGomez** [comment]
https://github.com/rust-lang/rust/pull/100429 and https://github.com/rust-lang/rust/pull/100775 added the finishing touch. I don't think it can be improved much further at this point. Closing then.
