### ISSUE TITLE
error: failed to read `/home/amcap1712/vlc-meson/extras/tools/native/rust/src/tools/clippy/Cargo.toml

### ISSUE THREAD

**Issue by amCap1712** [rust-lang/rust#74187]
Hi! I am trying to build Rust from source. I am downloading the tar.gz release of the source but unable to build it using the instructions provided.
```shell
error: failed to read `/home/amcap1712/vlc-meson/extras/tools/native/rust/src/tools/clippy/Cargo.toml`

Caused by:
  No such file or directory (os error 2)
failed to run: /home/amcap1712/vlc-meson/extras/tools/native/rust/build/x86_64-unknown-linux-gnu/stage0/bin/cargo build --manifest-path /home/amcap1712/vlc-meson/extras/tools/native/rust/src/bootstrap/Cargo.toml
Build completed unsuccessfully in 0:00:00
```
However, cloning the git source and building from it works. I think this is probably because the submodule directories are empty in case of tar.gz source. Is this a known issue ? Is it intended to support building from the tar.gz or .zip sources. ?

**Comment by ehuss** [comment]
Can you say more about which version you downloaded and where you got it from? All the source files linked at https://forge.rust-lang.org/infra/other-installation-methods.html#source-code seem OK to me.

**Comment by mati865** [comment]
I think using archives from Releases page is unsupported because they were automatically created by GitHub and are missing things like submodules and vendored directory.

Please use link from previous comment.

**Comment by amCap1712** [comment]
That makes sense. Thanks for the help.
