### ISSUE TITLE
`VecDeque` implementation creates a slice pointing to possibly uninitialized memory

### ISSUE THREAD

**Issue by ecstatic-morse** [rust-lang/rust#74189]
`VecDeque` has an internal method called [`buffer_as_slice`](https://github.com/rust-lang/rust/blob/34c5cd9a64d8537236626c4ccbed39a924cd38e2/src/liballoc/collections/vec_deque.rs#L204-L207), which returns an `&[T]` containing the entire capacity of the `VecDeque`. This is undefined behavior if the `VecDeque` is not full, since some elements of the backing `RawVec` may be uninitialized. However, this invariant is not documented on `buffer_as_slice` and is not respected in practice. For example, `VecDeque::iter` calls `buffer_as_slice` unconditionally:

https://github.com/rust-lang/rust/blob/34c5cd9a64d8537236626c4ccbed39a924cd38e2/src/liballoc/collections/vec_deque.rs#L959-L962

This one seems so obvious that I'm wondering if I've overlooked something. cc @rust-lang/wg-unsafe-code-guidelines

Found while doing #74172.

**Comment by RalfJung** [comment]
> This one seems so obvious that I'm wondering if I've overlooked something.

This code was probably written before we had a clear understanding of our invariants, and before we had `MaybeUninit` to properly work with uninitialized data.

**Comment by ecstatic-morse** [comment]
> This one seems so obvious that I'm wondering if I've overlooked something.

I need to stop hedging :smile:.

I also had assumed that the question of whether `&T` required `T` to be valid was more settled than the discussion in rust-lang/unsafe-code-guidelines#77 suggests. With that in mind, how do we want to prioritize this? I think it's not unprecedented for the standard library to rely on behavior that is *technically* undefined when there is active discussion about the rules and we aren't relying on that property for optimizations. That seems to be the case here?

**Comment by RalfJung** [comment]
> I think there's precedent for the standard library to rely on behavior that is technically undefined when there is active discussion about the rules and we aren't relying on that property for optimizations. That seems to be the case here?

Yeah, I think we can treat it like that.

**Comment by JmPotato** [comment]
Hi, @ecstatic-morse @RalfJung. After reading the code, it seems that safety is guaranteed by the check of the head and tail index, so there is no implementation that will access these uninitialized memories currently. However, considering the possibility of these codes being modified in the future, we do need to do something to make it be aware. Should I change `&[T]` to something like `&[MaybeUninit<T>]`. or just add some document? Any guidance would be helpful and appreciated!

**Comment by RalfJung** [comment]
The main concern is that this code is violating the rules that are explicitly stated at https://doc.rust-lang.org/reference/behavior-considered-undefined.html. So we have two options, both of which seem reasonable to me:
- Adjust the code to follow the rules.
- **Since this is the standard library**, we could alternatively document that we rely on privileged compiler-internal knowledge saying that violating these particular rules in this particular way is actually fine.

**Comment by JmPotato** [comment]
@ecstatic-morse Hi, I think we can close this issue now since it has been fixed.
