### ISSUE TITLE
tt-munching macro breaks attribute macros

### ISSUE THREAD

**Issue by alecmocatta** [rust-lang/rust#74216]
This is a simplified version of a macro that performs a limited [find and replace](https://github.com/constellation-rs/amadeus/blob/b33568446a9ef351e167cb8a979408e18c50d586/amadeus-core/src/lib.rs#L57-L92
) within its input:

```rust
macro_rules! __rename {
    (@munch [$($done:tt)*] { $($head:tt)* } $($body:tt)*) => (__rename!{@munch [$($done)* { __rename!{$($head)*} }] $($body)*});
    (@munch [$($done:tt)*] $head:tt $($body:tt)*) => (__rename!{@munch [$($done)* $head] $($body)*});
    (@munch [$($done:tt)*]) => ($($done)*);
    ($($body:tt)*) => (__rename!{@munch [] $($body)*});
}

__rename! {
    #[must_use]
    #[async_trait::async_trait]
    trait Foo {
        async fn bar();
    }
}

```

Unfortunately it seems to break procedural macros like `async-trait`:

```
   Compiling playground v0.0.1 (/playground)
error[E0706]: functions in traits cannot be declared `async`
  --> src/lib.rs:12:6
   |
12 |         async fn bar();
   |         -----^^^^^^^^^^
   |         |
   |         `async` because of this
   |
   = note: `async` trait functions are not currently supported
   = note: consider using the `async-trait` crate: https://crates.io/crates/async-trait

error: aborting due to previous error

For more information about this error, try `rustc --explain E0706`.
error: could not compile `playground`.

To learn more, run the command again with --verbose.

```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=1dc28d92df6f6ea34afb4b3199020fbb))

This is surprising as unless I'm missing something the macro isn't dropping any tokens; I would expect `async-trait` to work fine.

**Comment by taiki-e** [comment]
`__rename` macro seems to pass the following input to the async-trait attribute:
```rust
#[must_use]
trait Foo {
    __rename! { async fn bar() ; }
}
```

I'm not sure if that input is what `__rename` macro was intended for, but async-trait does not treat an async method inside macro calls as a method.

**Comment by alecmocatta** [comment]
@taiki-e I see; it hadn't occurred to me that the attribute macro would be evaluated before the inner `__rename`. Closing, thanks!
