### ISSUE TITLE
Tracking Issue for deque_range

### ISSUE THREAD

**Issue by jonhoo** [rust-lang/rust#74217]
This is a tracking issue for the non-RFC change from https://github.com/rust-lang/rust/pull/74099, which adds `range` and `range_mut` methods to `VecDeque`.
The feature gate for the issue is `#![feature(deque_range)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also uses as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Implement the feature (done in https://github.com/rust-lang/rust/pull/74099)
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr

**Comment by dtolnay** [comment]
This was stabilized in #79022 in 1.51.0.
