### ISSUE TITLE
1.35 -> 1.36 regression: && incorrectly considered to be unable to start expressions.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#74233]
This example [compiles on 1.35 but not 1.36 or later](https://godbolt.org/z/9bWe43):
```rust
pub fn foo() -> &'static &'static bool {
    {} // equivalent to {}; or ();
    &&false
}
```
(The example above was reduced from one involving `match ... {...} && false`, found by @digama0)

This regression was likely introduced by #60188, due to the definition of `can_continue_expr_unambiguously`: https://github.com/rust-lang/rust/blob/daecab3a784f28082df90cebb204998051f3557d/src/librustc_ast/util/parser.rs#L209-L232

That function lists all of the operators that *can't* start an expression, but only continue it.
`LAnd` (`&&`) is incorrectly included, as `&&expr` is parsed the same as `& &expr` at the start of an expression.

cc @estebank

**Comment by eddyb** [comment]
I've left some comments on #61500 (a partial fix for a regression that seems similar to this, but more specific), e.g.: https://github.com/rust-lang/rust/pull/61500#issuecomment-656985219
> Looking again at this, I don't think this PR was necessary, it seems to have worked around the bug without fully fixing it.
As per #74233, `can_continue_expr_unambiguously` should've never returned `true` for `LAnd`, preventing the regression.

**Comment by spastorino** [comment]
Assigning `P-high` as [discussed as part of the Prioritization Working Group procedure](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/I-prioritize.20.2374233.201.2E35.20-.3E.201.2E36.20regression.3A.20.26.26.20incorrectly) and removing `I-prioritize`.
