### ISSUE TITLE
ICE when printing paths in modules with non-DefId reexports (e.g. NonMacroAttr(Builtin)).

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#74236]
`dep.rs` (compiled with `--edition=2018`):
```rust
mod private { pub struct Pub; }
// Reexport built-in attribute without a DefId (requires Rust 2018).
pub use cfg_attr as attr;
// This export needs to be after the built-in attribute to trigger the bug.
pub use private::Pub as Renamed;
```
`main.rs`:
```rust
fn main() {
    // Trigger an error that will print the path of dep::private::Pub (as "dep::Renamed").
    let () = dep::Renamed;
}
```
Results in `attempted .def_id() on invalid res: NonMacroAttr(Builtin)` due to the `.def_id()` call in: https://github.com/rust-lang/rust/blob/daecab3a784f28082df90cebb204998051f3557d/src/librustc_middle/ty/print/pretty.rs#L391-L401

The snippet above is searching `dep`'s children for the reexport of `dep::private::Pub` in order to grab its reexported name (`Renamed` here) when it runs into the `pub use cfg_attr as attr;` reexport lacking a `DefId`.

Fix is straight-forward, we can just ignore siblings lacking a `DefId`:
```diff
-         .find(|child| child.res.def_id() == def_id)
+         .find(|child| child.res.opt_def_id() == Some(def_id))
```

<hr/>

But I'm mostly making this issue to point out the fact that it is possible to create strange reexports that could break various parts of the compiler, even if it might be very rare (#74081 appears to be an instance of this).

(as I was writing this I found that @da-x had already tried out the fix - see https://github.com/rust-lang/rust/issues/74081#issuecomment-657012684)

cc @rust-lang/compiler

**Comment by JohnTitor** [comment]
#74240 fixed and added the test for this, closing as fixed.
