### ISSUE TITLE
Change `next_back()` to `rnext()`

### ISSUE THREAD

**Issue by sHaDoW-54** [rust-lang/rust#74248]
Not really an issue, i just thought it would look better if functions that contained `_back` in them, should be changed to have an `r` in front to signify that it does the exact same function, but in reverse. It would be consistent with other functions and keep the  same theme going.

Note: Should also apply to `nth_back`, and anything similar.
Note: I know this is probably too much work for very little gain, but i thought it would look better and be more concise. ¯\\\_(ツ)\_/¯

**Comment by jonas-schievink** [comment]
We cannot rename it since that would be a breaking change.
