### ISSUE TITLE
nightly rustc is dynamically linked to `libz.so.1`

### ISSUE THREAD

**Issue by timothee-haudebourg** [rust-lang/rust#74249]
I've just updated the nightly toolchain using rustup, and now `rustc` crashes because it cannot find `libz.so.1` on my machine:
```
$HOME/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rustc: error while loading shared libraries: libz.so.1: cannot open shared object file: No such file or directory
```

Is that intended? It causes some problems on NixOS where `libz` is not available yet. I've tried it on two NixOS machines and ran into the same issue. The stable toolchain works fine.

**Comment by nagisa** [comment]
Yes, intended. Since you're seeing this problem you are most likely using the [overlay](https://github.com/mozilla/nixpkgs-mozilla), so you want to update to include [this fix](https://github.com/mozilla/nixpkgs-mozilla/pull/227).

Otherwise its a packaging issue in nixpkgs. Closing.
