### ISSUE TITLE
Compiler panic gives a dead bug report link

### ISSUE THREAD

**Issue by vllry** [rust-lang/rust#74253]
A compiler panic gives some information, including a link on filing a bug:
```
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/blob/master/CONTRIBUTING.md#bug-reports

note: rustc 1.44.1 (c7087fe00 2020-06-17) running on armv7-unknown-linux-gnueabihf

note: compiler flags: -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden
```

The link technically resolves, but has no bug-reports anchor, nor the expected content.

The bug report URL is defined here: https://github.com/rust-lang/rust/blob/master/src/librustc_driver/lib.rs#L68

**Comment by ehuss** [comment]
Thanks for the report!  This is being fixed in #74037.
