### ISSUE TITLE
Disagreement between x.py tidy and rustfmt

### ISSUE THREAD

**Issue by Lucretiel** [rust-lang/rust#74273]
https://github.com/rust-lang/rust/blob/master/src/libstd/io/buffered.rs#L1136-L1140

`rustfmt` and `x.py fmt` disagree about the correct formatting of this block. This causes issues with editors configured to "rustfmt-on-save", because you have to keep manually reverting / running tidy. You can see this in the commit log for #72808, which has many commits that unintentionally / accidentally bounce between the two formats:

https://github.com/rust-lang/rust/pull/72808/commits/1bf8ba3546aace5a16852d5f58fd9206934cc829
https://github.com/rust-lang/rust/pull/72808/commits/e89e2e42f9269fe401b1eef0288ff12c7941544f
https://github.com/rust-lang/rust/pull/72808/commits/8df5ae0fffc9de2884e0c916bdcd74cb69949b1c
https://github.com/rust-lang/rust/pull/72808/commits/f7650fe3f955863e810ef7816edbe78f88393d87

**Comment by Mark-Simulacrum** [comment]
Presumably this is because the rustfmt your editor and x.py is using are different? src/stage0.txt should contain the rustfmt version used in tree currently. I'm happy to bump that if it'd be helpful.
