### ISSUE TITLE
Looks like Rust standard library is incompatible with ncurses.

### ISSUE THREAD

**Issue by A1-Triard** [rust-lang/rust#74311]
I tried this code:

main.rs
```rust
#![feature(extern_types)]

use libc::{LC_ALL, setlocale, c_int, c_char};

extern "C" {
    pub type WINDOW;
    pub fn initscr() -> *mut WINDOW;
    pub fn cbreak() -> c_int;
    pub fn noecho() -> c_int;
    pub fn keypad(arg1: *mut WINDOW, arg2: bool) -> c_int;
    pub static mut stdscr: *mut WINDOW;
    pub fn clear() -> c_int;
    #[link_name = "\u{1}move"]
    pub fn move_(arg1: c_int, arg2: c_int) -> c_int;
    pub fn insnstr(arg1: *const c_char, arg2: c_int) -> c_int;
    pub fn getch() -> c_int;
    pub fn endwin() -> c_int;
}

fn main() {
    unsafe {
        Some(()).unwrap();
        setlocale(LC_ALL, b"\0".as_ptr() as _);
        initscr();
        cbreak(); 
        noecho(); 
        keypad(stdscr, true);
        clear();
        move_(10, 10);
        insnstr("П".as_ptr() as _, 2);
        getch();
        endwin();
    }
}
```
with Cargo.toml:
```
[package]
name = "test_ncurses"
version = "0.1.0"
edition = "2018"

[build-dependencies]
pkg-config = "0.3.18"

[dependencies]
libc = "0.2.27"
```

and build.rs:
```rust
fn main() {
    println!("cargo:rerun-if-env-changed=PKG_CONFIG_PATH");
    pkg_config::Config::new()
        .atleast_version("5.0")
        .probe("ncursesw")
        .unwrap();
    println!("cargo:rustc-link-lib=ncursesw");
}
```

When I execute `cargo run` command, I expected to see alone cyrillic letter "П" on screen. Instead I see two letters: "Пc".

If I remove "Some(()).unwrap();" (the only place using Rust `std`) from main program, the effect disappears. If I remove pkg-config invoke from build.rs, the effect disappears also.

`rustc --version --verbose`:
```
rustc 1.46.0-nightly (0c03aee8b 2020-07-05)
binary: rustc
commit-hash: 0c03aee8b81185d65b5821518661c30ecdb42de5
commit-date: 2020-07-05
host: x86_64-unknown-freebsd
release: 1.46.0-nightly
LLVM version: 10.0
```

P.S. You can see more garbage letters with another string:

```rust
let t = "👩Привет, world!👩‍🔬";
insnstr(t.as_ptr() as _, t.len() as _);
 ```

produces
```
👩Привет, world!👩 🔬called `Option::u
```

**Comment by jonas-schievink** [comment]
You're not zero-terminating your C strings. Feel free to ask on https://users.rust-lang.org/ if you need help.

**Comment by bugaevc** [comment]
> `insnstr("П".as_ptr() as _, 2);`

I believe you have to pass "the number of wide characters" (whatever that means), not the number of bytes, to libncursesw's `insnstr()`. In this case, pass 1.

**Comment by jonas-schievink** [comment]
Oh yeah, that sounds more likely.

**Comment by A1-Triard** [comment]
@bugaevc, It does no have any sence, but I am going to look into ncurses sources and check it.

**Comment by A1-Triard** [comment]
Well, I have found more simple way to check it. `insnstr("Привет", 6)` prints 3 characters (`При`), so the second parameter is definitely bytes count.

**Comment by lzutao** [comment]
Byte number of "Привет" is 12.
```python
>>> b = bytes("Привет", 'utf8')
>>> len(b)
12
```

**Comment by bugaevc** [comment]
> Well, I have found more simple way to check it. `insnstr("Привет", 6)` prints 3 characters (`При`), so the second parameter is definitely bytes count.

That prints nothing (or at least nothing visible) for me with `-lncurses`, and all of `Привет` with `-lncursesw`.

In any case, it's a C function that expects a (not necessarily null-terminated) string, and it should behave identically when invoked from Rust and from C (provided you null-terminate, or don't null-terminate, strings the same way in both languages) :slightly_smiling_face:, so what are your reasons to believe that "Rust standard library is incompatible with ncurses"?

**Comment by A1-Triard** [comment]
> and it should behave identically when invoked from Rust and from C

That's the point. They do not behave identically. C version do not print extra characters, but Rust version does.

Of caurse, may be it is nsurses' bug...

**Comment by A1-Triard** [comment]
Ok, now I think it is bug of `pkg-config` package.

**Comment by bugaevc** [comment]
> C version reads 2 bytes from memory, but Rust version reads 4 bytes.

That totally sounds like you're linking the C version to libncurses and the Rust version to libncursesw. Please ensure that everything but the language is the same in both cases :slightly_smiling_face:

**Comment by A1-Triard** [comment]
> That totally sounds like you're linking the C version to libncurses and the Rust version to libncursesw.

No, I don't link libncurses in both cases. Linking with libncurses produces very different result.

**Comment by mati865** [comment]
> C version ouputs "Пx"

It prints `Прx` for me when compiling with `clang curses.c -lcursesw` on Linux.

**Comment by A1-Triard** [comment]
I'm using FreeBSD. Compiles with `cc curses.c -o curses -lncursesw`. Prints `Пx`. Rust with `pkg-config` in build.rs prints `Прx` on same computer.

**Comment by A1-Triard** [comment]
I've posted [SO question about `insnstr` argument meaning](https://stackoverflow.com/questions/62897474/what-is-the-exact-meaning-of-the-second-parameter-of-the-insnstr-ncurses-funct)

Let's see, who is right - Lin*x or FreeBSD.

**Comment by A1-Triard** [comment]
Oops, looks I was right about `insnstr` correct using, and all tales about magic Linux ncurses counting wide chars are just tales. Who would have such thought...

**Comment by A1-Triard** [comment]
https://github.com/rust-lang/pkg-config-rs/issues/108

**Comment by A1-Triard** [comment]
Bad news: we all were wrong about insnstr argument meaning: it is wchar_t count, not char count! Good news: there is no bugs anywhere here (almost).
