### ISSUE TITLE
rust dylib for musl without linked with so

### ISSUE THREAD

**Issue by zerothZone** [rust-lang/rust#74317]
return does not support these crate types use `build with cargo build --target x86_64-unknown-linux-musl --release`
```
cargo build --target x86_64-unknown-linux-musl --release
error: cannot produce dylib for `demo2 v0.1.0 (...plugins/demo2)` as the target `x86_64-unknown-linux-musl` does not support these crate types
```
build success use `RUSTFLAGS='-C target-feature=-crt-static' cargo build --target x86_64-unknown-linux-musl --release`, but linked with other so
```
ldd target/x86_64-unknown-linux-musl/release/libdemo2.so
        linux-vdso.so.1 =>  (0x00007ffcb6dec000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f214660c000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f214623e000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f2146b3d000)
```

how can i build dylib with musl withou linke with linux-vdso.so.1, libgcc_s.so.1, libc.so.6,  /lib64/ld-linux-x86-64.so.2

**Comment by 12101111** [comment]
musl's `dlopen` only works with dynamic link (`target-feature=-crt-static`),It's pointless to compile a dylib with static musl libc.

In addition, the output of `ldd` from you glibc system is quite confusing. You should using musl's `ldd` (just create a symbolic link to musl's `libc.so`)  or `readelf -d` to get real dependences.
