### ISSUE TITLE
Tracking Issue for core::task::yield_now

### ISSUE THREAD

**Issue by yoshuawuyts** [rust-lang/rust#74331]
The feature gate for the issue is `#![feature(task_yield_now)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also uses as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Implementation history

- Initial implementation https://github.com/rust-lang/rust/pull/74335

**Comment by ibraheemdev** [comment]
Should this be closed given that the implementation was never merged?
