### ISSUE TITLE
Compiling to wasm with `link-arg=-s` strips the name section from debug builds

### ISSUE THREAD

**Issue by willemneal** [rust-lang/rust#74338]
I know that this might not be a bug and my own ignorance, but either way would appreciate the help!

Here is an example repo https://github.com/willemneal/example-wasm.
You can see it in action with gitpod in the browser here: https://gitpod.io/#https://github.com/willemneal/example-wasm

I tried used the following code:

```rust
use std::str;


extern "C" {
    fn print_str(ptr: *const u8, len: usize);
}

static HELLO: &'static str = "Hello, World!";


#[no_mangle]
pub extern "C" fn hello_wasm() {
    unsafe {
        print_str(HELLO.as_ptr(), HELLO.len());
    }
}
```

When compiled with:
```
cargo build --target wasm32-unknown-unknown
```
Using the crate `wasm-nm`
```
wasm-nm -p -j target/wasm32-unknown-unknown/debug/example_wasm.wasm 
```

Prints
```
_ZN4core5slice29_$LT$impl$u20$$u5b$T$u5d$$GT$3len17h4959ff48ca0f8bacE
_ZN4core3str21_$LT$impl$u20$str$GT$3len17h0cddd413bca0122fE
_ZN4core3str21_$LT$impl$u20$str$GT$6as_ptr17hecf5f747102529d6E
hello_wasm
```

However if built with
```
RUSTFLAGS='-C link-arg=-s' cargo build --target wasm32-unknown-unknown
```

wasm-nm prints the following:
```
function[0]
function[1]
function[2]
function[3]
```

**Comment by lzutao** [comment]
So what do you expect about compiler behavior?

**Comment by willemneal** [comment]
I expect to keep names when compiling with debug.
