### ISSUE TITLE
Ayu theme search bar color is not quite comfort

### ISSUE THREAD

**Issue by lzutao** [rust-lang/rust#74349]
I was excited to try out the new Ayu them in rustdoc.
But I find that the background color of search bar is quite dark.
I would like to change its background to #424242.
This color is the same as background color of search bar in mdbook Ayu theme .

The expected result after color changed:
![image](https://user-images.githubusercontent.com/15225902/87496252-67a06d00-c67d-11ea-83dc-36409bda2af0.png)

@rustbot modify labels: T-rustdoc

**Comment by lzutao** [comment]
cc @Cldfire, feel free to ignore if you aren't interested.

**Comment by Cldfire** [comment]
Good point, the search bar could probably benefit from a more prominent color.

I'll take a look at it tomorrow 👍

**Comment by lzutao** [comment]
@Aloso is resolving the issue in #74371 .

**Comment by lzutao** [comment]
Closed by #74371 .
