### ISSUE TITLE
rustdoc: theme-dependent logo system

### ISSUE THREAD

**Issue by lzutao** [rust-lang/rust#74350]
The current logo in Ayu theme is difficult to see:
![image](https://user-images.githubusercontent.com/15225902/87498032-11352d80-c681-11ea-922c-b44b1fc0fc03.png)

As noted by @Cldfire in https://github.com/rust-lang/rust/pull/71237#issuecomment-621558929:
> Orange could potentially work, yes, and I agree that the logo will need improvement. However, I would say that this discussion is out of place for this PR; some sort of theme-dependent logo system needs to be added to rustdoc which needs to be discussed and implemented elsewhere, imo.

This issue is served as a tracking issue for that.

@rustbot modify labels: T-rustdoc

**Comment by Cldfire** [comment]
Thanks for making this issue! 😄

**Comment by GuillaumeGomez** [comment]
The best solution would instead to provide a way to change the image border and/or background, which would be much simpler than having a different image for each theme.
