### ISSUE TITLE
post const args in type dependent paths cleanup

### ISSUE THREAD

**Issue by lcnr** [rust-lang/rust#74360]
#74113 has some open FIXMEs

- consider caching `opt_const_param_of` on disk (perf)
- consider first calling `tcx.def_kind(def_id)` in `opt_const_param_of` to improve incremental
- add a helper method for 
```rust
if def.const_param_did.is_none() {
    if let const_param_did @ Some(_) = tcx.opt_const_param_of(def.did) {
        return tcx.query(ty::WithOptConstParam { const_param_did, ..def });
    }
}
```

**Comment by eddyb** [comment]
Copying a couple of comments here:
* https://github.com/rust-lang/rust/pull/74113#discussion_r454926268 (`src/librustc_typeck/collect/type_of.rs` / `fn opt_const_param_of`)
  > I think you can make this cheaper incremental-wise by checking `tcx.def_kind(def_id)` first, because that won't add a dependency to the entire definition pointed to by `def_id`, just the simple `DefKind` enum (but feel free to file this under further experimentation).
* https://github.com/rust-lang/rust/pull/74113#discussion_r454928692 (referring to the `if ... { if let ... { return ... } }` pattern)
  > I just realized that this two-step process could probably be a helper method on `WithOptConstParam` (and do e.g. `if let Some(def) = def.upgrade_with_const_param(tcx)` or something like that, with the method documentation describing this kind of use pattern).
