### ISSUE TITLE
Consider allowing trailing comma in struct update syntax

### ISSUE THREAD

**Issue by Veetaha** [rust-lang/rust#74365]
One downside of prohibiting this little trailing guy is this example:
```rust
#[derive(Default)]
struct S { foo: i32 }

#[tokio::main]
async fn main() {
    S { ..S::default(), };
}
```
If you open it with `rust-analyzer` you'll see the entire file in the fire:
![image](https://user-images.githubusercontent.com/36276403/87556308-2af56580-c6bf-11ea-9b36-04dbb6bae85f.png)

This is because (my wild guess) that trailing comma inside the struct is a syntax error and that's why `#[tokio::main]` proc macro doesn't get expanded and you get an error about the missing main function which has a span of the enire file and hides the trailing comma in an IDE.

<details>
<summary>cargo run output:</summary>

```
~/junk/rust-sandbox $ cargo run
   Compiling crate_foo v0.1.0 (/home/veetaha/junk/rust-sandbox/crate_foo)
error: cannot use a comma after the base struct
 --> crate_foo/src/main.rs:6:9
  |
6 |     S { ..S::default(), };
  |         ^^^^^^^^^^^^^^- help: remove this comma
  |
  = note: the base struct must always be the last field

error: unexpected token
 --> crate_foo/src/main.rs:6:23
  |
6 |     S { ..S::default(), };
  |                       ^

error[E0601]: `main` function not found in crate `crate_foo`
 --> crate_foo/src/main.rs:1:1
  |
1 | / #[derive(Default)]
2 | | struct S { foo: i32 }
3 | |
4 | | #[tokio::main]
5 | | async fn main() {
6 | |     S { ..S::default(), };
7 | | }
  | |_^ consider adding a `main` function to `crate_foo/src/main.rs`

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0601`.
error: could not compile `crate_foo`.

To learn more, run the command again with --verbose.
```
</details>

<details>
<summary>Environment</summary>

```
~/junk/rust-sandbox $ rustc --version --verbose
rustc 1.44.1 (c7087fe00 2020-06-17)
binary: rustc
commit-hash: c7087fe00d2ba919df1d813c040a5d47e43b0fe7
commit-date: 2020-06-17
host: x86_64-unknown-linux-gnu
release: 1.44.1
LLVM version: 9.0
~/junk/rust-sandbox $ cargo --version --verbose
cargo 1.44.1 (88ba85757 2020-06-11)
release: 1.44.1
commit-hash: 88ba8575724c08a50eb265a05f3ff6d0883de1ee
commit-date: 2020-06-11
```
</details>

**Comment by NieDzejkob** [comment]
Trailing comma is only one of the many errors you can make, and the issue with the IDE highlighting the entire file will apply for each of them. I think having the no-main diagnostic be without any span would be a better solution.

**Comment by estebank** [comment]
The entire file is underlined because of `E0601`, not because of the trailing comma. If you add a `main` function the underline will be way more useful. An option would be for `E0601` to only point at the beginning or end of the file.

**Comment by black-puppydog** [comment]
Just to add my two cents: the (unrelated, kinda) error being highlighted is not the main reason I came here to search for this issue.
I'm more concerned with diffs & code review. Allowing a trailing comma will produce shorter, more meaningful and more readable diffs, which in turn reduces mental load on code reviewers.

I thus think that allowing trailing commas (as in function calls for example) would be valuable regardless of OP's concern with their IDE setup.

**Comment by estebank** [comment]
This is the current output:

```
error: cannot use a comma after the base struct
 --> src/main.rs:6:9
  |
6 |     S { ..S::default(), };
  |         ^^^^^^^^^^^^^^- help: remove this comma
  |
  = note: the base struct must always be the last field
```

And we have changed E0601 to point only at the end of the file some time back.
