### ISSUE TITLE
negative impls cause problems with type inference

### ISSUE THREAD

**Issue by lcnr** [rust-lang/rust#74383]
```rust
#![feature(negative_impls)]

struct Foo<T>(T);

impl !Send for Foo<()> {}

fn test<T>() -> T where Foo<T>: Send { todo!() }

fn main() {
    let _: u8 = test();
}
```
Fails with
```
error[E0277]: `Foo<_>` cannot be sent between threads safely
  --> $DIR/fk.rs:10:17
   |
LL | fn test<T>() -> T where Foo<T>: Send { todo!() }
   |                                 ---- required by this bound in `test`
...
LL |     let _: u8 = test();
   |                 ^^^^ `Foo<_>` cannot be sent between threads safely
   |
   = help: the trait `std::marker::Send` is not implemented for `Foo<_>`
```
Explicitly specifying `test::<u8>()` works though.

**Comment by eddyb** [comment]
cc @nikomatsakis @matthewjasper (I suspect this might actually be expected, but I'm not sure)

**Comment by lcnr** [comment]
> Treat negative impls as unimplemented, and reservation impls as ambiguity.

Seems like this is caused by a mixture of 
https://github.com/rust-lang/rust/blob/6ee1b62c811a6eb68d6db6dfb91f66a49956749b/src/librustc_trait_selection/traits/select/candidate_assembly.rs#L137-L141
and https://github.com/rust-lang/rust/blob/6ee1b62c811a6eb68d6db6dfb91f66a49956749b/src/librustc_trait_selection/traits/select/mod.rs#L937-L941

We might be able to deal with this by also updating `candidate_should_be_dropped_in_favor_of`.
Let's see if the current behavior is expected before looking deeper into this.

**Comment by nikomatsakis** [comment]
Hmm I don't think this is expected, though I still don't quite understand how it happens.

**Comment by lcnr** [comment]
closing as intended behavior, see https://github.com/rust-lang/rust/pull/74525#discussion_r457465014 for more details

It looks to me like preventing the impl for `Foo<()>` is directly tracked in #13231.
