### ISSUE TITLE
Add suitable tests for aarch64 for repr-transparent-aggregates-1.rs

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#74396]
The motivation behind the "just ignoring" approach for this PR was based on the fact that I was looking at this as two independent tasks. One of them is to ignore this test for aarch64 (inevitable) and the other is to add suitable tests for the same target. The former is immediate, the latter requires a bit more effort, and is something that should follow.

But if we should proceed in a different way, that's fine too.

_Originally posted by @joaopaulocarreiro in https://github.com/rust-lang/rust/pull/73926#issuecomment-653100300_

This issue has been assigned to @joaopaulocarreiro via [this comment](https://github.com/rust-lang/rust/issues/74396#issuecomment-659465905).

**Comment by joaopaulocarreiro** [comment]
I started taking a look at this. Adding the tests should be straight forward, but I am also interested in finding out why the llvm bitcode is being generated the way it is for aarch64.

**Comment by Enselic** [comment]
Triage: @joaopaulocarreiro: Are you still working on this?
