### ISSUE TITLE
Operator '>' is not usable in const generics argument

### ISSUE THREAD

**Issue by rhysd** [rust-lang/rust#74402]
I tried this code:

```rust
#![feature(const_generics)]

fn f<const N: bool>() {}

fn main() {
  f::<2 > 1>();
}
```

[Playground link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=b5e5d09eb5cd836a39aff1b8edeb0c33)

I expected to see this happen: rustc compiles the code successfully with instantiating `f::<true>`

Instead, this happened: Compilation (syntax) error as follows:

```
error: expected one of `!`, `.`, `::`, `;`, `?`, `{`, `}`, or an operator, found `1`
 --> src/main.rs:6:11
  |
6 |   f::<2 > 1>();
  |           ^ expected one of 8 possible tokens
```

### Meta

`rustc --version --verbose`:
```
rustc 1.46.0-nightly (7e11379f3 2020-07-15)
binary: rustc
commit-hash: 7e11379f3b4c376fbb9a6c4d44f3286ccc28d149
commit-date: 2020-07-15
host: x86_64-apple-darwin
release: 1.46.0-nightly
LLVM version: 10.0
```

### Note

I tried to add comment at https://github.com/rust-lang/rust/issues/44580 but the issue was locked. So I created a new issue.

**Comment by jonas-schievink** [comment]
You need to use `f::<{2 > 1}>();`.

**Comment by rhysd** [comment]
Oh... OK. Thanks for the answer.
