### ISSUE TITLE
Missed optimization: The optimizer forgets that Some(function) is Some(_)

### ISSUE THREAD

**Issue by yvt** [rust-lang/rust#74425]
```rust
#![no_std]

extern "C" {
    fn ext_fn0();
}

pub fn test() {
    test_inner(Some(inner0));
}

#[inline(always)]
fn test_inner(f_maybe: Option<fn()>) {
    if let Some(f) = f_maybe {
        f();
    }
}

#[inline(always)]
fn inner0() {
    unsafe { ext_fn0() };
}
```

I expected to see this happen: The branch in `test_inner` is optimized out and the `test` function compiles down to a single call to `ext_fn0`.

```asm
; expected
example::test:
        b       ext_fn0
```

Instead, this happened: The compiled `test` function includes a branch that checks if `Some(inner0)` is `Some(_)` or not.

```asm
; -Copt-level=3 -Cpanic=abort --target=thumbv7em-none-eabihf -Clto=on
example::test:
        movw    r0, :lower16:example::inner0
        movt    r0, :upper16:example::inner0
        cmp     r0, #0
        it      ne
        bne     ext_fn0
        bx      lr

example::inner0:
        b       ext_fn0
```

Compiler Explorer ([Nightly](https://rust.godbolt.org/z/dxM6za), [1.45.0](https://rust.godbolt.org/z/8TE9ME))

### Meta

`rustc --version --verbose`:
```
rustc 1.46.0-nightly (23744c84d 2020-07-14)
binary: rustc
commit-hash: 23744c84d9c0f8e4e870edb983f1ad6d33449c34
commit-date: 2020-07-14
host: x86_64-unknown-linux-gnu
release: 1.46.0-nightly
LLVM version: 10.0

```

**Comment by MSxDOS** [comment]
The regression starts with Rust 1.38.0

**Comment by nikic** [comment]
IR contains this weirdness: `(i1 icmp ule ({}* bitcast (void ()* @_ZN7example6inner017hec4f5594ccddd419E to {}*), {}* null)` Because it's a constexpr, the `ule null` probably doesn't get folded to `ne null`.

I've seen this super weird pattern emitted by rustc a few times already, wonder where it comes from.

**Comment by nikic** [comment]
Most likely from here: https://github.com/rust-lang/rust/blob/48036804d2bc461b243c5d291b850e44bcca68ef/src/librustc_codegen_ssa/mir/place.rs#L264 The zero case is already special-cased, we should emit IntNE in that case instead of IntULE.
