### ISSUE TITLE
adding #[track_caller] to #[global_allocator] to trace allocation source

### ISSUE THREAD

**Issue by Geal** [rust-lang/rust#74433]
Hello,
I am using a [custom allocator](https://github.com/geal/tracing_allocator) to trace allocations and deallocations when debugging code. I was wondering if adding `#[track_caller]` to the `GlobalAlloc::alloc` and `GlobalAlloc::dealloc` methods could give me the origin of allocations (even if it ends up in libstd), but unfortunately, it only gives me the position of the `#[global_allocator]` attribute.

As an alternative, I am trying to obtain it with the [backtrace crate](https://crates.io/crates/backtrace), but apparently I cannot resolve the symbols for a stackframe (I suspect it would allocate), so I would need to store the instruction address at runtime, and post process the result with [gimli](https://crates.io/crates/gimli).

Making `#[track_caller]` usable from a custom allocator would simplify a lot that use case, since everything returned by `panic::Location::caller()` is `'static`, so there are no allocations.

So I'm not sure if this request fits the use case of `#[track_caller]` but I'm probably not the only one wanting a nice way to track allocations :)

**Comment by anp** [comment]
This would be cool but I'm not sure it can be supported backwards-compatibly (see https://github.com/rust-lang/rust/issues/74763 also). AIUI, it would require adding the attribute to symbols that are exposed as externs which would be a breaking change.

**Comment by Geal** [comment]
I see, it was a fun thought only :)
