### ISSUE TITLE
Peephole optimization: remove `<T as Into::<T>>::into(x)` invocations

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#74435]
We should replace these function calls with a `goto` to the target block and insert an assignment from `x` to the destination (the assignment should be just before the goto).

Leave a comment on the libcore impl mentioning that the optimization should be removed if the libcore impl ever becomes overwriteable via specialization (can't be done right now: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=9a6f68d250162188edb7b4fb545fc9e5, but it may become possible if we mark the libcore impl as `default`)

**Comment by jonas-schievink** [comment]
Wouldn't the inliner make this optimization redundant?

**Comment by oli-obk** [comment]
I'm not sure if the inliner can figure out that there is only ever one implementation of `<T as Into<T>>`, but that's a good point... Maybe we should just focus on the inliner

@rust-lang/wg-mir-opt

**Comment by jonas-schievink** [comment]
IIRC The inliner just uses `Instance::resolve`, which takes specializable impls into account and would succeed and return the blanket impl's function here (but would fail if the impl was made specializable).

**Comment by oli-obk** [comment]
yea... true, let's leave it to the inliner, it's more general
