### ISSUE TITLE
Tracking Issue for fmt::Arguments::as_str()

### ISSUE THREAD

**Issue by m-ou-se** [rust-lang/rust#74442]
Tracking issue for `fmt::Arguments::as_str()` (#74056), gated by `#![feature(fmt_as_str)]`.

**Comment by nikki-nn4** [comment]
I don't quite understand fmt internals, but _Make fmt::Arguments::as_str() return a 'static str._ seems unnecessarily restrictive. And it breaks [runtime-fmt](https://crates.io/crates/runtime-fmt) which depends on hidden apis e.g. Arguments::new_v1

**Comment by lzutao** [comment]
`Arguments` cannot be generated at runtime because it cannot safely be done. So `as_str` returns `&'static str` makes sense.

**Comment by sfackler** [comment]
I'd like to be able to use this in the log crate to correctly implement a codegen optimization that doesn't really work otherwise: https://github.com/rust-lang/log/pull/446

@rfcbot fcp merge

**Comment by BurntSushi** [comment]
This SGTM. One question though. Are we sure that the `'static` bound will always be correct here?

**Comment by m-ou-se** [comment]
`fmt::Arguments` is the result from parsing a formatting string at compile time. In the future, this might not always be a literal but might be a `const` too. But a non-static/constant format string will be a very different beast.

**Comment by BurntSushi** [comment]
That's what I figured, but wanted to make sure it was explicitly addressed.

**Comment by jhpratt** [comment]
Does this make any guarantees about when `Some` is returned? I've been interested in redoing the `format_args!` macro to be much more intelligent (and thus performant), but obviously don't know when it's possible to return something statically knowable.

**Comment by m-ou-se** [comment]
Currently it returns Some for `format_args!("string literal")` only. But my plan is to extend that also to `format_args!("{}", "literal")`, `format_args!("{}", constant)`, and possibly also things like `format_args!("a {} b {} c", const, format_args!("..."))`, etc. See https://github.com/rust-lang/rust/issues/78356

**Comment by jhpratt** [comment]
Yeah, I see that from looking at the source code. I was more inquiring about whether it would be considered breaking to go from returning `Some` to returning `None`. I don't suspect anything would be out-of-reach when reimplementing the macro, but you never know.

**Comment by sfackler** [comment]
@jhpratt I think you'd generally want to use it as an optimization only, but we can probably guarantee that it will return Some for certain cases in particular (e.g. `format_args!("asdf")`).

**Comment by Zoxc** [comment]
This function seems particularly bad for compressed formatting strings and breaks the otherwise clean abstraction.
