### ISSUE TITLE
rust virtual machine  compile /run   rust  code in debug mode. 

### ISSUE THREAD

**Issue by zhuxiujia** [rust-lang/rust#74475]
In some cases with large amounts of code, compilation can take a long time
Even modifying a string takes seconds (Even though my computer is 6 core Cpus)

rust virtual machine(Implemented in pure rust languages)  compile /run   rust  code in debug mode. (we need very fast Develop code)
llvm ir compile in release mode.   (we need very fast Execution speed)

advantage：
- compile fast (may be Less than one second)
- Smart tips fast （less than one second,  for now it takes delay of more than 1 second or more）
- Develop fast （for example developing a website）
- when debug mode runing,Automatically generate the Release mode of LLVM IR (so we compile  release mode code fast!)

disadvantage：
- debug run code may be Slow down.(but release mode fast)
- debug run may be consume more memory

**Comment by csmoe** [comment]
`cargo check` compiles rust code without involvement of llvm cc https://doc.rust-lang.org/edition-guide/rust-2018/cargo-and-crates-io/cargo-check-for-faster-checking.html
