### ISSUE TITLE
`rust-src` component is not self-contained anymore

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#74506]
Since https://github.com/rust-lang/rust/pull/73441 I'm getting a failure while building `libstd`.

```
error: couldn't read /home/oliver/.rustup/toolchains/miri/lib/rustlib/src/rust/src/libstd/../backtrace/src/lib.rs: No such file or directory (os error 2)
   --> /home/oliver/.rustup/toolchains/miri/lib/rustlib/src/rust/src/libstd/lib.rs:519:1
    |
519 | mod backtrace_rs;
    | ^^^^^^^^^^^^^^^^^

error: aborting due to previous error
```

Should we copy the `backtrace` folder into the `rust-src` rustup component or is there a better solution?

cc @alexcrichton

**Comment by RalfJung** [comment]
Yeah I think we need to do that, and we should do it ASAP. We can always find a better version later.
