### ISSUE TITLE
Is the error expected ? 

### ISSUE THREAD

**Issue by BhuwanBhaskar** [rust-lang/rust#74503]
Hi,
I am beginner and learning rust. Not sure if it is the right place to ask such question.
I am seeing error with below code:

```
enum Coin {
    Penny,
    Nickel,
    Dime,
    Quarter(u8),
}

fn value_in_cents(coin: Coin) -> u8 {
    match coin {
        Coin::Penny => {
            println!("Lucky penny!");
            1
        }
        Coin::Nickel => 5,
        Coin::Dime => 10,
        Coin::Quarter(howMany: u8) => {  // throws error when you define param with u8 ie you write howMany:u8 !!
            println!("{} many quarters", howMany);
            howMany
        }
    }
}

```
Error: **expected one of `)`, `,`, `@`, or `|`, found `:`**

This error is coming when I declare type of "howMany" to be "u8" (which is same as defined in the enum).
If I don't declare type of 'howMany', everything works fine. Shouldn't we be able to declare the type?
Is this an expected error message? If yes, why?

**Comment by lzutao** [comment]
The error is expected. The `Coin::Quarter(..)` in `match` expression is a pattern. Remove the `: u8` 
you code will compile.

**Comment by Lonami** [comment]
> if it is the right place to ask such question.

User questions are better suited for https://users.rust-lang.org/ or StackOverflow.

**Comment by BhuwanBhaskar** [comment]
@lzutao thnx...But why not allow declaration of type in param?
@Lonami Thnx for pointing that out ...

**Comment by jonas-schievink** [comment]
Hi! This issue tracker is mainly meant for bug reports and concrete, small feature requests. Questions like this are better asked in the user forum at https://users.rust-lang.org/ or on [one of the chat platforms](https://www.rust-lang.org/community) used by the Rust community.
