### ISSUE TITLE
Intra-doc links do not resolve for value keywords

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#74515]
```rust
warning: `[true]` cannot be resolved, ignoring it.
 --> prim.rs:1:6
  |
1 | /// [`true`] and [`bool`]
  |      ^^^^^^ cannot be resolved, ignoring
```
The bug is here: https://github.com/rust-lang/rust/blob/fe98de2a8e3941bb33d1149c3717d8ea0744e39c/src/librustdoc/passes/collect_intra_doc_links.rs#L1124
It only checks for types, not for values.

I opened an issue because I'm not quite sure how to fix it: `Res` has `PrimTy`  but doesn't seem to have a place for keywords in the value namespace.

_Originally posted by @jyn514 in https://github.com/rust-lang/rust/pull/73618/review_comment/create_

**Comment by jyn514** [comment]
This looks like it might be the same issue as #63351.

**Comment by GuillaumeGomez** [comment]
I think that "true" and "false" are the two only cases for primitives where we should check for values.

**Comment by jyn514** [comment]
Closing as wontfix: https://github.com/rust-lang/rust/pull/75101
