### ISSUE TITLE
nightly-rustc docs no longer document private items

### ISSUE THREAD

**Issue by SNCPlay42** [rust-lang/rust#74511]
Compare [1.45.0 version](https://doc.rust-lang.org/1.45.0/nightly-rustc/rustc_mir/index.html), [nightly version](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_mir/index.html)

* ~~The "This is an internal compiler API." warning has disappeared~~ this was intentional
* Items which are private, like `borrow_check`, have disappeared

**Comment by lzutao** [comment]
The warnings is removed in #74351 .

**Comment by lzutao** [comment]
The `borrow_check` haven't never be public. Not sure if I made it disappeared.

cc @Mark-Simulacrum

**Comment by lzutao** [comment]
Also this page https://doc.rust-lang.org/nightly/nightly-rustc is 404 now.
Before it listed all the crates.

**Comment by Mark-Simulacrum** [comment]
I don't see how your PR could've done that -- cc @jyn514 I think you recently had a PR touching document-private-items?

**Comment by jyn514** [comment]
The PR just changed some warnings around intra-doc-links, nothing to do with `fn href`. My suspicion since the index page is gone is that something changed in bootstrap.

**Comment by jyn514** [comment]
I take it back, I did modify href in https://github.com/rust-lang/rust/pull/72771/files#diff-2e4303616596f7b39dfebcbabb8a49b0R471. That was a few ago now and should have documented strictly more items, though.

**Comment by ollie27** [comment]
This is the issue I pointed out in the second part of https://github.com/rust-lang/rust/pull/71670#discussion_r455875330. I clearly didn't explain the issue well enough.
