### ISSUE TITLE
keyword in's doc uses says it requires an Iterator instead of an IntoIterator

### ISSUE THREAD

**Issue by SkiFire13** [rust-lang/rust#74529]
In the [doc for the keyword in](https://doc.rust-lang.org/std/keyword.in.html) it's stated that "The expression immediately following `in` must implement the `Iterator` trait."
This is not completly right since it can be followed by anything that implements the `IntoIterator` trait. 
The [doc for the keyword for](https://doc.rust-lang.org/std/keyword.for.html) instead correctly cites the `IntoIterator` trait, althouth it could be improved since it just appears out of thin air when the desugared version is showed, without any prior mentioning.

This issue has been assigned to @Nicholas-Baron via [this comment](https://github.com/rust-lang/rust/issues/74529#issuecomment-660720716).

**Comment by Nicholas-Baron** [comment]
PR ready for review. I tried to keep the changes to a minimum. Hopefully, the wording is understandable.

I'll just assign myself. 
@rustbot claim
