### ISSUE TITLE
Missing docs for non-first impl

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#74531]
e.g., https://doc.rust-lang.org/nightly/std/panic/struct.Location.html is missing the file/line/column method docs which *are* present in beta https://doc.rust-lang.org/beta/std/panic/struct.Location.html#impl-1

cc @rust-lang/rustdoc

**Comment by JohnTitor** [comment]
Removing `I-prioritize` as this is `T-rustdoc` issue.

**Comment by Manishearth** [comment]
@JohnTitor Why?

**Comment by Manishearth** [comment]
A quick test indicates that copying the source of std::panic::Location out into a no_std crate doesn't fix the problem

**Comment by Manishearth** [comment]
Oh wait I don't have the latest nightly

**Comment by JohnTitor** [comment]
@Manishearth As mentioned in https://github.com/rust-lang/rust/issues/72340#issuecomment-631482488, I'm not sure this should be prioritized under t-compiler's wg-prioritization. If this label is useful for the rustdoc team as well, we could tweak triagebot not to notify on Zulip.

**Comment by Manishearth** [comment]
@JohnTitor Yeah it seems like it would be useful for us

**Comment by Manishearth** [comment]
Hmm so I am unable to reproduce this bug on a self contained no-core file that contains the exact code of `Location` aside for changes in the body

**Comment by Manishearth** [comment]
Regression range 7e11379f3..5c9e5df3a


5c9e5df3a09 Auto merge of #74408 - Manishearth:rollup-9gxn4od, r=Manishearth
6ee1b62c811 Auto merge of #72481 - marmeladema:duration-consts-2, r=oli-obk
125c58caebc Auto merge of #74202 - oli-obk:mir_const, r=RalfJung
4cd0ee9343d Auto merge of #74388 - Manishearth:rollup-i7iueu8, r=Manishearth
e2e29de5e8a Auto merge of #74375 - Manishearth:rollup-10vbpdh, r=Manishearth

**Comment by Manishearth** [comment]
Works in 6ee1b62

Regressing PR is https://github.com/rust-lang/rust/pull/74408

**Comment by Manishearth** [comment]
Rustdoc PRs in that rollup

fc098170ce8 Rollup merge of #74370 - Manishearth:re-spotlight, r=GuillaumeGomez
61fccf05f90 Rollup merge of #74359 - lzutao:rustdoc-tostring, r=GuillaumeGomez
196243ed9bf Rollup merge of #74325 - GuillaumeGomez:focus-source-file-sidebar, r=kinnison
61a3f6701b5 Rollup merge of #74148 - GuillaumeGomez:doc-alias-check, r=Manishearth
b7008351186 Rollup merge of #73807 - euclio:rustdoc-highlighting, r=ollie27,GuillaumeGomez
a8bb2458e17 Rollup merge of #73771 - alexcrichton:ignore-unstable, r=estebank,GuillaumeGomez
c23f045a8b1 Rollup merge of #73566 - jyn514:name-resolve-first, r=eddyb

**Comment by Manishearth** [comment]
Confirmed, 9ffb7801363cff45dcb56fa2146a48aa0ae433db (try build from #73771) is the culprit

**Comment by Manishearth** [comment]
What's happening is that that code erroneously checks the stability of the impl, which apparently is "unstable if it contains unstable items". The "foreign item" check applies to libstd reexporting libcore. It shouldn't.

The minimal reproduction is two crates, one using stability attrs such that an impl has at least one unstable item, and the second crate reexporting the type.

**Comment by Mark-Simulacrum** [comment]
I'm going to take a stab at fixing this.
