### ISSUE TITLE
Towards faster binary search 

### ISSUE THREAD

**Issue by LifeIsStrange** [rust-lang/rust#74547]
https://doc.rust-lang.org/src/core/slice/mod.rs.html#1497-1502
Could be improved in the same way as rust has switched it's old hashmap to the state of the art hashbrown.

It seems that there is a new state of the art Binary search in town leading up to 25% performance improvement and binary search is a foundational task.
Therefore it would be promising to investigate whether Rust could have a faster binary search implementation, the candidate being 
https://news.ycombinator.com/item?id=23893366
(but maybe there are other new state of the art)

**Comment by lzutao** [comment]
Please edit to use permanent link:  https://github.com/rust-lang/rust/blob/05630b06fdf76c25c6ccf2e9ac3567592eae6c67/src/libcore/slice/mod.rs#L1565-L1570

**Comment by leonardo-m** [comment]
I've just tried a quaternary search and it's slower than the std one

**Comment by jakubadamw** [comment]
Binary search ought to be the most overstudied algorithm in computer science. It's important to keep that in mind when one sees a new revelation about it on Hacker News. 

If one is interested in experimenting with the different n-ary search algorithms in Rust in a crate, that sounds like an idea, but it seems out of scope for the standard library. All the more that the quaternary variant, where they report a “25%” speed-up in their tests and data set, is not even a binary search (though for some reason they call it a “quaternary binary search”, which is funny).

**Comment by LifeIsStrange** [comment]
There is also branchless Binary searches that can benefit from SIMD
https://github.com/ehrmann/branchless-binary-search
