### ISSUE TITLE
CStr::from_bytes_with_nul_unchecked() incorrectly listed as const in docs

### ISSUE THREAD

**Issue by nwn** [rust-lang/rust#74579]
The [documentation](https://doc.rust-lang.org/stable/std/ffi/struct.CStr.html#method.from_bytes_with_nul_unchecked) for `CStr::from_bytes_with_nul_unchecked()` lists it as a `const fn`, but its `const`-ness is still unstable (due to the `rustc_const_unstable` attribute and corroborated by the [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=f3c0a4f1c3eefb6e3334823851513232)).

**Comment by RalfJung** [comment]
Cc @GuillaumeGomez 
We have plenty of stable but const-unstable functions; are they all affected?

**Comment by GuillaumeGomez** [comment]
I guess? If they are under the same attribute, I see no reason for them to not share the same bug.

**Comment by GuillaumeGomez** [comment]
I wrote a fix. I just need to test a few things and then I send the PR.
