### ISSUE TITLE
Casting repr(signed) negative enum inhabitant to an unsigned integer causes an underflow with no panic or warning

### ISSUE THREAD

**Issue by zesterer** [rust-lang/rust#74588]
It seems mighty fishy to me that code such as the following compiles, without warnings, and doesn't crash when run (even with the appropriate over/underflow compiler flags enabled).

```rust
#[repr(i8)]
enum Foo { A = -1 }

fn main() {
    println!("Oh dear = {}", Foo::A as usize);
}
```
([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=1930cf6858d80041122b73c99f412c09))

I would expect one of the following to happen: 

- The compiler does not allow casting between `Foo` and `usize`.
- The compiler warns the user that underflow may occur
- The code panics with an underflow error upon execution

None of these things happened for us: we only became aware of this bug because the aforementioned underflowed value later caused an overflow when using in an unrelated addition operation during a test.

I'm not sure to what extent this represents a soundness issue (it's probably just unspecified behaviour rather than undefined behaviour), but it still strikes me as surprising and potentially dangerous.

Edit: I've just noticed that similar behaviour occurs for all types with integer representation. I'm sure that someone has picked this up before, but not performing any run-time checks for such casts is quite concerning to me.

**Comment by jonas-schievink** [comment]
`as` has always performed a truncating or wrapping cast. In fact, that's its purpose. For lossless conversions there are `From` impls between numeric types in libcore.

IIRC there were some plans to (soft-?)deprecate `as`, but I don't know if they went anywhere. They'd require an RFC regardless.

Closing as expected behavior.

**Comment by lzutao** [comment]
Yeah, `(-1i8) as usize` doesn't warn either.
