### ISSUE TITLE
Trait implementation not found but exists

### ISSUE THREAD

**Issue by toxeus** [rust-lang/rust#74586]
I wanted to implement a mock version of a trait and then share it across crates as a dev-dependency. Unfortunately, the compilation fails and I think that this is a bug.

I've prepared a minimal example:
https://gitlab.com/toxeus/trait_issue

I expected this to compile fine.

Instead, this happened (`cargo test`):
> the trait `Foo` is not implemented for `one::Mock`

**Comment by jonas-schievink** [comment]
`one` is compiled against a previously built version of `two`, so the trait it implements is distinct from the one seen by `two`s test.

**Comment by toxeus** [comment]
Thx @jonas-schievink, are you suggesting that this is "expected behavior"?

**Comment by jonas-schievink** [comment]
yeah

**Comment by toxeus** [comment]
Interesting, I wouldn't have expected that time of build would leak into high-level abstractions like `trait`.
