### ISSUE TITLE
`make check` should use a performance ratchet

### ISSUE THREAD

**Issue by graydon** [rust-lang/rust#7459]
We should have performance tests that are "not allowed to get worse" in the testsuite. The operation should involve reading a .json file with the last run values, comparing to current-run values, failing if any regress, and rewriting the file if any advanced. Buildbot can potentially deposit the .json file before each build if it's missing, and harvest it after for display / plotting, and users can just work with the one(s) in their own workspaces.

This requires either objective performance criteria or fuzzy forms of comparison. Prefer objective when possible. `valgrind --tool=lackey` and `perf stat` can gather number of instructions retired, which tends to be much _more_ stable than clock time.

Probably easier to base this on metrics gathered from #6810

**Comment by steveklabnik** [comment]
Triage: no changes here.

**Comment by aturon** [comment]
Closing for the time being, as this is a pretty open-ended feature request and is unlikely to be prioritized any time soon.
