### ISSUE TITLE
Consts and literals are not completely interchangable despite being very similar

### ISSUE THREAD

**Issue by Xaeroxe** [rust-lang/rust#74607]
Code snippet:

```rust
fn broken_main() {
    const FOO: &str = "foo";
    const BAR: &str = "bar";
    println!(concat!(FOO, BAR)); // This doesn't compile
}

fn main() {
    println!(concat!("foo", "bar"));
}

```

What I expected: Both examples to compile and print string "foobar"

What actually happened: A const can't be used as a literal, this seems silly since both a const and a literal are available at compile time.

I tried to find prior discussion on this but couldn't find any. Please close this issue if it's a duplicate.

**Comment by jonas-schievink** [comment]
Macros are expanded much earlier than when constants are available. This is working as intended.
