### ISSUE TITLE
The rust-src component contains a symlink

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#74624]
Extracting the rust-src component with `rustup-toolchain-install-master` fails because there is a symlink in that component (https://github.com/kennytm/rustup-toolchain-install-master/issues/39). The symlink was introduced some time between 567ad7455d5f25f6b38d2fded1cb621e0c34a48b and 734233d29771869f824d8ddbaddabb90b3b68e03.

The tool should be fixed, but I wonder -- is that expected? Not all filesystems support symlinks (AFAIK this is a problem on Windows), and so far it seems like there were no symlinks.

**Comment by Mark-Simulacrum** [comment]
I think this was fixed in https://github.com/rust-lang/rust/pull/74578.

**Comment by RalfJung** [comment]
It was indeed, thanks!

**Comment by RalfJung** [comment]
This is unfortunate though as it landed after the other PR that broke Miri again recently... making it now 3 days or more straight during which it was impossible to build Miri against rustc master. We keep fixing things but new breakage is landing before the fixes make it through.^^

**Comment by Mark-Simulacrum** [comment]
Yeah we're reverting gimli entirely in a bit (hopefully not rebreaking anything) but next time we land it I plan to do some try-testing to make sure it's not breaking rustup etc.

I also hope to add tests that we don't have symlinks to our dist builders.
