### ISSUE TITLE
ICE: eval_const_to_op: Unexpected ConstKind

### ISSUE THREAD

**Issue by steffahn** [rust-lang/rust#74634]
```rust
#![feature(const_generics)]
#![allow(incomplete_features)]

trait If<const COND: bool> {}
impl If<true> for () {}

trait IsZero<const N: u8> {
    type Answer;
}

struct True;
struct False;

impl<const N: u8> IsZero<N> for ()
where (): If<{N == 0}> {
    type Answer = True;
}

trait Foobar<const N: u8> {}

impl<const N: u8> Foobar<N> for ()
where (): IsZero<N, Answer = True> {}

impl<const N: u8> Foobar<N> for ()
where (): IsZero<N, Answer = False> {}

```

([Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=d6d51bae5e30d80030470d95a6cab2c0))

Errors:

```
   Compiling playground v0.0.1 (/playground)
error: internal compiler error: src/librustc_mir/interpret/operand.rs:569:17: eval_const_to_op: Unexpected ConstKind Const { ty: u8, val: Bound(DebruijnIndex(0), 0) }
  --> src/lib.rs:15:15
   |
15 | where (): If<{N == 0}> {
   |               ^^^^^^

thread 'rustc' panicked at 'Box<Any>', /rustc/f9a3086363f214f2b56bef30f0ac572e1a9127f1/src/libstd/macros.rs:13:23
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.47.0-nightly (f9a308636 2020-07-20) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: aborting due to previous error

error: could not compile `playground`.

To learn more, run the command again with --verbose.

```

Probably related: #72819

Removing (at least) one of the `impl`s for `Foobar` makes the panic go away, and the compiler correctly reports the error:
```
   Compiling playground v0.0.1 (/playground)
error: constant expression depends on a generic parameter
  --> src/lib.rs:15:11
   |
15 | where (): If<{N == 0}> {
   |           ^^^^^^^^^^^^
   |
   = note: this may fail depending on what value the parameter takes

error: aborting due to previous error

error: could not compile `playground`.

To learn more, run the command again with --verbose.
```
@rustbot modify labels: I-ICE, T-compiler, A-const-eval, A-const-generics, C-bug, F-const_generics, requires-nightly

**Comment by RalfJung** [comment]
That's happening here:

https://github.com/rust-lang/rust/blob/06e7b93f6a2a3eeaf80fd6a9a3ef7b180bb5d778/src/librustc_mir/interpret/operand.rs#L567

I don#t think there is a meaningful way to evaluate a polymorphic constant, so either some code earlier screwed up to even get so far, or we need to throw `TooGeneric` here.

Cc @oli-obk @eddyb

**Comment by oli-obk** [comment]
cc @lcnr 

This ICE is totally expected. Using features that emit the `incomplete_features` lint are expected to ICE, otherwise they would not emit said lint. The const evaluator is not at fault here, there's just no way to evaluate this.

**Comment by lcnr** [comment]
hmm, we shouldn't try to evaluate this constant here or at least have it be a `ty::Param` instead of a `ty::Placeholder`.

Not quite sure what's going on here, will have to look at it in more detail soon

**Comment by lcnr** [comment]
So we probably fail here because we call `const_eval_resolve` with a `ConstKind::Infer` which get's canonicalized to a `ConstKind::Bound`.

All of that seems correct to me :thinking: Is it possible that we should treat `ConstKind::Bound` similar to `ConstKind::Param` and "just" return `TooGeneric` here?
