### ISSUE TITLE
impl Deref for EndianSlice appears in std docs

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/rust#74672]
`impl Deref for EndianSlice` appears on the current nightly's[`std::ops::Deref` documentation page](https://doc.rust-lang.org/nightly/std/ops/trait.Deref.html#impl-Deref-for-EndianSlice%3C%27input%2C%20Endian%3E), even though it's not part of the (public) standard libraries. This appears to be [`gimli::read::EndianSlice`](https://docs.rs/gimli/0.22.0/gimli/read/struct.EndianSlice.html), so maybe related to https://github.com/rust-lang/rust/pull/73441, cc @alexcrichton.

Noticed by @rijenkii (assuming they use the same handle here and discord, if not, sorry :flushed:)

**Comment by jyn514** [comment]
Relevant PRs (backtrace isn't really to blame here): https://github.com/rust-lang/rust/pull/73771, https://github.com/rust-lang/rust/pull/74534

**Comment by jyn514** [comment]
https://github.com/rust-lang/rust/pull/74534/files#diff-d50f12822c671ab606392686fa769b98R349-R353

Maybe this should also skip the impl if there is no 'stability' attribute?

**Comment by jyn514** [comment]
> Maybe this should also skip the impl if there is no 'stability' attribute?

This is the default for everything not in the standard library. So it seems like the standard library needs special casing here. Maybe as simple as `|| cx.tcx.crate_name(LOCAL_CRATE) == "core" && stab.is_none()`?

**Comment by bjorn3** [comment]
Doesn't gimli get everything marked as unstable behind the rustc_private feature gate through a rustc flag?

**Comment by lzutao** [comment]
MCVE: https://github.com/lzutao/rustdoc-traits-bugs 
It doesn't require any external deps, just dummy crates included.
The outermost crate is a fake std, realcore is fake core, gimli is fake gimli.
