### ISSUE TITLE
Tracking Issue for tracked access to environment variables from proc macros

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rust#74690]
https://github.com/rust-lang/rust/pull/74653 introduces `proc_macro::tracked_env::var` - a new function that is similar to regular `env::var` called from a proc macro, except that it also adds the accessed variable to depinfo.

This way build system executing the compiler will know that the variable was accessed during compilation, and will be able to rerun the build when the value of that variable changes.

Besides the dependency tracking `tracked_env::var` differs from `env::var` from the standard library by requiring UTF-8 arguments.
See some discussion in https://github.com/rust-lang/rust/pull/71858 for the motivation, non UTF-8 variables were considered unimportant corner cases by the stakeholders, and tracking for them can be introduced later with new depinfo directives like `# env-dep-bytes`.

**Comment by programmerjake** [comment]
This seems really useful, what would it take to stabilize it? Also, this function should be mentioned in the docs for `std`'s environment access functions, since using those from a proc-macro could be considered incorrect.

**Comment by petrochenkov** [comment]
>This seems really useful, what would it take to stabilize it?

Some user experience I guess?
Things are usually stabilized if someone is using them and pushing for them.

**Comment by programmerjake** [comment]
one alternative that might be more useful is to instead add tracking to `std`'s env functions that's only enabled in proc-macros, that way code wouldn't need to change and you can easily catch nearly all env usage. Idk if that's feasible though...

**Comment by petrochenkov** [comment]
This function need to wired into the compiler to affect depinfo files.
In theory it can be added to `std` if `std` gets an analogue of "proc macro bridge" that `proc_macro` uses to talk with the compiler through a stable ABI, although I seriously doubt that it would be a good idea.

**Comment by petrochenkov** [comment]
In https://github.com/rust-lang/rust/pull/84029#discussion_r622603746 @Xanewok has some concerns about the module structure.
It should be somehow harmonized with a similar interface for tracking files (https://github.com/rust-lang/rust/pull/84029).

**Comment by m-ou-se** [comment]
Closing this in favor of this tracking issue, tracking both `path` and `env`: https://github.com/rust-lang/rust/issues/99515
