### ISSUE TITLE
rustc should probably warn on anonymous, unused closure statement

### ISSUE THREAD

**Issue by rphmeier** [rust-lang/rust#74691]
Not quite sure how to name this issue, please change the title to something more accurate!

Recently ran into this issue:

```rust
fn main() {
    let b = false; // dangerous semi-colon
        || true;
        
    println!("{}", b);
}
```

The boolean statement was long, so I broke it out onto a new line. However, I accidentally added the annotated semi-colon. The `|| true` line is interpreted as an anonymous closure statement (no let binding, not even a callable closure) as opposed to a boolean OR. 

When executing this code, it yields `false`. Luckily, someone caught the issue in code review, but a compiler warning noting the unused closure would have been really helpful!

**Comment by rphmeier** [comment]
After playing around a bit, it seems like one way to accomplish this would be to make the anonymous closure types `#[must_use]`. Would that be a reasonable approach? What are the downsides?

**Comment by jyn514** [comment]
must_use is clever, I like that! Closures have some special casing in the compiler though, so I'm not exactly sure how to implement it, it would be a change to rustc and not to libstd.
