### ISSUE TITLE
Don't run allowed lints

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#74704]
First noticed in https://rust-lang.zulipchat.com/#narrow/stream/247081-t-compiler.2Fperformance/topic/Output.20of.20.60collector.20eprintln.60/near/204875468. If a lint is allowed, there is no need to run the lint pass. This could have large performance improvements for any crate where all lints are allowed (e.g. any dependency compiled by cargo, which uses `--cap-lints allow`).

As a first pass this could check for `--cap-lints allow` and run no lints if so. In the future it could skip individual lints. Rustc would have to be careful not to skip lints that are `#![allow]`ed at the crate level but re-enabled for individual items.

The implementation would look similar to what I did in [#73566](https://github.com/rust-lang/rust/pull/73566/files#diff-0de644786a2f1fd88c7d7f44bc3fa4bbR380) - override the query provider for `lint_mod` so that it doesn't run lints at all.

**Comment by jyn514** [comment]
@flip1995 mentioned that this is a hard problem in general:

> one LintPass can have multiple lints (which makes sense for performance and DRY) and only can be skipped, iff **all** lints in the lint pass are allowed. Clippy has a "workaround" for this:

https://github.com/rust-lang/rust-clippy/blob/06f190287848ceeee36be738cbbd8e008f3e7615/clippy_lints/src/utils/mod.rs#L1402
https://github.com/rust-lang/rust-clippy/blob/c493090a8a601baea39a592fdbe199bd64d6db22/clippy_lints/src/wildcard_dependencies.rs#L33

Also, this only works for `LateLintPass`.

**Comment by camsteffen** [comment]
We could put allow-by-default lints into a separate pass. Then disable the whole pass if all those lints are never enabled in the crate?

**Comment by blyxyas** [comment]
[Maybe CC](https://rust-lang.zulipchat.com/#narrow/stream/257328-clippy/topic/Progress.20on.20not.20processing.20allowed.20lints)

**Comment by bjorn3** [comment]
Fixed by https://github.com/rust-lang/rust/pull/125116
