### ISSUE TITLE
Args Iterator doesn't advance

### ISSUE THREAD

**Issue by Master0r0** [rust-lang/rust#74723]
Using args().next() does not advance to the next value in the iterator, just repeatedly returns the exe path.

I tried this code:

```rust
use std::env::args;

fn main() {
    println!("{}, {}", args().next().unwrap(), args().next().unwrap());
}
```

I expected to see this happen:
Using .next() would advance the iterator to the next value.

Instead, this happened: 
Using .next() only returns the first value.

### Meta
`rustc --version --verbose`:
```
rustc 1.46.0-nightly (346aec9b0 2020-07-11)
```

**Comment by lzutao** [comment]
You should store args result to a variable. And use next on it.

**Comment by jonas-schievink** [comment]
Every call to `args()` will return a new iterator, so this behaves as expected.
