### ISSUE TITLE
Passing -W for an unknown lint gives an error without saying why

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#74722]
```
$ rustc -W unknown_blah ~/src/test-rustdoc/test.rs 
error[E0602]: unknown lint: `unknown_blah`
  |
  = note: requested on the command line with `-W unknown_blah`
```

Not sure if this is actually a bug? cc @Mark-Simulacrum

**Comment by Mark-Simulacrum** [comment]
We should at least give a brief blurb about how to silence this. (Does -Wunknown-lints help?)

**Comment by jyn514** [comment]
> (Does -Wunknown-lints help?)

It does not.

```
$ rustc -Aunknown-lints -Alegacy-derive-helpers hello.rs
error[E0602]: unknown lint: `legacy_derive_helpers`
  |
  = note: requested on the command line with `-A legacy_derive_helpers`
```

**Comment by tmandry** [comment]
Copying what I said in #81906:

> Since the same problem that `unknown-lints` solves exists on the command line, I'd argue that this is a bug in the CLI.
>
> As a corollary, it would be nice if we could do something like `-Aunknown-lints -Alegacy-derive-helpers -Dunknown-lints` to prevent misspellings elsewhere in the command line.

**Comment by djkoloski** [comment]
#94274 fixes the issue of `-Aunknown-lints` not applying to subsequent CLI arguments.

**Comment by Herschel** [comment]
I ran into this when adopting [Embark's workaround](https://github.com/EmbarkStudios/rust-ecosystem/issues/22#issuecomment-947011395) for using `.cargo/config.toml` to allow/disable lints for an entire workspace via `rustflags`. I'd like to `-Aunknown_lints` here to squelch certain nightly clippy lints, but subsequent `-Afoobar` still give me errors.

> #94274 fixes the issue of `-Aunknown-lints` not applying to subsequent CLI arguments.

This makes it sound like the above should work correctly, but I guess I'm mistaken? rustc 1.63.0-nightly (9257f5aad 2022-05-21)

**Comment by ComputerDruid** [comment]
I think https://github.com/rust-lang/rust/pull/94274 only helps with _unstable_ lints, not unknown ones, unfortunately.
