### ISSUE TITLE
Remove `log` renamings of `tracing` crate

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#74747]
In https://github.com/rust-lang/rust/pull/74726 I made a dependency import hack to reduce the diff size. We should replace all of these imports with `tracing = "0.1"` and then adjust the crate source by replacing all uses of `log` imports with `tracing` import.

Ideally only a few of these are done at a time to keep conflicts at a minimum and get such PRs merged fast.

Note: do not start working on this until #74726 is merged.

* [ ] [librustc_ast](https://github.com/rust-lang/rust/blob/master/src/librustc_ast/Cargo.toml#L11)
* [x] [librustc_ast_lowering](https://github.com/rust-lang/rust/blob/master/src/librustc_ast_lowering/Cargo.toml#L11)
* [x] [librustc_ast_passes](https://github.com/rust-lang/rust/blob/master/src/librustc_ast_passes/Cargo.toml#L10)
* [x] [librustc_ast_pretty](https://github.com/rust-lang/rust/blob/master/src/librustc_ast_pretty/Cargo.toml#L10)
* [ ] [librustc_builtin_macros](https://github.com/rust-lang/rust/blob/master/src/librustc_builtin_macros/Cargo.toml#L11)
* [ ] [librustc_codegen_llvm](https://github.com/rust-lang/rust/blob/master/src/librustc_codegen_llvm/Cargo.toml#L15)
* [ ] [librustc_codegen_ssa](https://github.com/rust-lang/rust/blob/master/src/librustc_codegen_ssa/Cargo.toml#L14)
* [ ] [librustc_data_structures](https://github.com/rust-lang/rust/blob/master/src/librustc_data_structures/Cargo.toml#L12)
* [ ] [librustc_driver](https://github.com/rust-lang/rust/blob/master/src/librustc_driver/Cargo.toml#L12)
* [ ] [librustc_errors](https://github.com/rust-lang/rust/blob/master/src/librustc_errors/Cargo.toml#L10)
* [ ] [librustc_expand](https://github.com/rust-lang/rust/blob/master/src/librustc_expand/Cargo.toml#L12)
* [ ] [librustc_hir](https://github.com/rust-lang/rust/blob/master/src/librustc_hir/Cargo.toml#L18)
* [ ] [librustc_incremental](https://github.com/rust-lang/rust/blob/master/src/librustc_incremental/Cargo.toml#L11)
* [ ] [librustc_infer](https://github.com/rust-lang/rust/blob/master/src/librustc_infer/Cargo.toml#L11)
* [ ] [librustc_interface](https://github.com/rust-lang/rust/blob/master/src/librustc_interface/Cargo.toml#L11)
* [ ] [librustc_lint](https://github.com/rust-lang/rust/blob/master/src/librustc_lint/Cargo.toml#L9)
* [ ] [librustc_metadata](https://github.com/rust-lang/rust/blob/master/src/librustc_metadata/Cargo.toml#L12)
* [ ] [librustc_middle](https://github.com/rust-lang/rust/blob/master/src/librustc_middle/Cargo.toml#L13)
* [ ] [librustc_mir](https://github.com/rust-lang/rust/blob/master/src/librustc_mir/Cargo.toml#L13)
* [ ] [librustc_mir_build](https://github.com/rust-lang/rust/blob/master/src/librustc_mir_build/Cargo.toml#L11)
* [ ] [librustc_parse](https://github.com/rust-lang/rust/blob/master/src/librustc_parse/Cargo.toml#L11)
* [ ] [librustc_passes](https://github.com/rust-lang/rust/blob/master/src/librustc_passes/Cargo.toml#L9)
* [ ] [librustc_privacy](https://github.com/rust-lang/rust/blob/master/src/librustc_privacy/Cargo.toml#L17)
* [ ] [librustc_query_system](https://github.com/rust-lang/rust/blob/master/src/librustc_query_system/Cargo.toml#L11)
* [ ] [librustc_resolve](https://github.com/rust-lang/rust/blob/master/src/librustc_resolve/Cargo.toml#L12)
* [ ] [librustc_save_analysis](https://github.com/rust-lang/rust/blob/master/src/librustc_save_analysis/Cargo.toml#L9)
* [ ] [librustc_session](https://github.com/rust-lang/rust/blob/master/src/librustc_session/Cargo.toml#L11)
* [ ] [librustc_span](https://github.com/rust-lang/rust/blob/master/src/librustc_span/Cargo.toml#L18)
* [ ] [librustc_symbol_mangling](https://github.com/rust-lang/rust/blob/master/src/librustc_symbol_mangling/Cargo.toml#L10)
* [ ] [librustc_target](https://github.com/rust-lang/rust/blob/master/src/librustc_target/Cargo.toml#L10)
* [ ] [librustc_trait_selection](https://github.com/rust-lang/rust/blob/master/src/librustc_trait_selection/Cargo.toml#L11)
* [ ] [librustc_traits](https://github.com/rust-lang/rust/blob/master/src/librustc_traits/Cargo.toml#L9)
* [ ] [librustc_ty](https://github.com/rust-lang/rust/blob/master/src/librustc_ty/Cargo.toml#L9)
* [ ] [librustc_typeck](https://github.com/rust-lang/rust/blob/master/src/librustc_typeck/Cargo.toml#L12)
* [ ] [compiletest](https://github.com/rust-lang/rust/blob/master/src/tools/compiletest/Cargo.toml#L8)
* [ ] [librustdoc](https://github.com/rust-lang/rust/blob/master/src/librustdoc/lib.rs#L46)

**Comment by bishtpawan** [comment]
Hi @oli-obk I saw your PR of (#74726 ) where you have replaced `log="0.4"` to `log = { package = "tracing", version = "0.1" }` and in this issue, you have mentioned like we have to replace all log imports to tracing imports. My question here is when you have already changed the package from `log` to `tracing` so now what left in it because the import name cannot be changed in files if we have used `log` as a crate name in Cargo.toml? 
Do we need to replace the name of dependency from `log` to `tracing` then we'll clean up the code by replacing the **log imports** with **tracing imports** in the corresponding files? Or is there anything else you want?

Thanks, 
Waiting for your response.

**Comment by oli-obk** [comment]
> Do we need to replace the name of dependency from `log` to `tracing` then we'll clean up the code by replacing the **log imports** with **tracing imports** in the corresponding files? Or is there anything else you want?

Yes, that's exactly it. Replace `log = { package = "tracing", version = "0.1" }` with `tracing = "0.1"` and then fix up the errors by changing the import names. Note that the PR isn't merged yet, so this issue is not yet actionable.

**Comment by bishtpawan** [comment]
Thanks for the response. Yes, I'm waiting for your PR to be merged first.

**Comment by georgio** [comment]
I would like to give this a shot when #74726 is merged

**Comment by oli-obk** [comment]
Once the PR is merged, before you work on anything, please post here which libs you are going to work on so that you don't conflict with others who are doing the same

**Comment by pawanbisht62** [comment]
As they are independent, we can make changes on multiple files right? If yes then I'll work on first 8 libs (librustc_ast
 librustc_ast_lowering
 librustc_ast_passes
 librustc_ast_pretty
 librustc_builtin_macros
 librustc_codegen_llvm
 librustc_codegen_ssa
 librustc_data_structures)
And will raise 2 PRs and will pick new libs accordingly if we will left with some.
Thanks

**Comment by gdhuper** [comment]
If no one else is planning on tackling the following:
- [ ] librustc_session
- [ ] librustc_span
- [ ] librustc_symbol_mangling
- [ ] librustc_target
- [ ] librustc_trait_selection
- [ ] librustc_traits
- [ ] librustc_ty
- [ ] librustc_typeck
- [ ] compiletest
I would like to take a stab. Thanks

**Comment by georgio** [comment]
I could take care of the remaining files:

- [ ]   librustc_ast
- [ ]   librustc_data_structures
- [ ]   librustc_driver
- [ ]   librustc_errors
- [ ]   librustc_expand
- [ ]   librustc_hir
- [ ]   librustc_incremental
- [ ]   librustc_infer
- [ ]   librustc_interface
- [ ]   librustc_lint
- [ ]   librustc_metadata
- [ ]   librustc_middle
- [ ]   librustc_mir
- [ ]   librustc_mir_build
- [ ]   librustc_parse
- [ ]   librustc_passes
- [ ]   librustc_privacy
- [ ]   librustc_query_system
- [ ]   librustc_resolve
- [ ]   librustc_save_analysis

**Comment by georgio** [comment]
Hey everyone, I would like to apologize for not being able to carry this through at the moment. My country was rocked by a massive explosion and I have to be on the ground to help. I wouldn't mind getting back to this as soon as things calm down a bit but if you're short on time I would suggest that someone else takes care of my part of the issue.

**Comment by gdhuper** [comment]
> Hey everyone, I would like to apologize for not being able to carry this through at the moment. My country was rocked by a massive explosion and I have to be on the ground to help. I wouldn't mind getting back to this as soon as things calm down a bit but if you're short on time I would suggest that someone else takes care of my part of the issue.

Hey @georgio, so sorry to hear that. I can take care of the rest.

**Comment by georgio** [comment]
@gdhuper thank you very much. I really appreciate it.

**Comment by 5M1Sec** [comment]
I will take care of `librustdoc`, then every task is claimed if I am not mistaken. 
Stay safe.

**Comment by oli-obk** [comment]
@pawanbisht62 `bors` is a bot, You can just post messages like the one you did in this issue without pinging it. We just need to ping it when giving it commands to merge PRs

**Comment by oli-obk** [comment]
I think we solved all of these
