### ISSUE TITLE
Warn unreachable statement on unreachable!()

### ISSUE THREAD

**Issue by kpp** [rust-lang/rust#74749]
# Code

```rust
fn main() {
    return;
    unreachable!();
}
```

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=00179f4d3027a3d691347e0a5c179934

# Warning

```
warning: unreachable statement
 --> src/main.rs:3:5
  |
2 |     return;
  |     ------ any code following this expression is unreachable
3 |     unreachable!();
  |     ^^^^^^^^^^^^^^^ unreachable statement
  |
  = note: `#[warn(unreachable_code)]` on by default
```

# Meta

```
rustc --version
rustc 1.45.0 (5c1f21c3b 2020-07-13)
```
# Description

I would expect the compiler not to complain at `unreachable!` because it can be really unreachable especially in a generated code.

**Comment by jonas-schievink** [comment]
This is working as expected, since `return` diverges. In generated code the lint could just be allowed if it causes trouble.
