### ISSUE TITLE
Deprecate `non-shorthand-field-patterns` lint in favor of rustfmt's `use_field_init_shorthand`

### ISSUE THREAD

**Issue by rickvanprim** [rust-lang/rust#74768]
Given that rustfmt can be configured to either use or not use `field init shorthand`, it's a bit of an ear flick to potentially have to `allow` a warning based on the preference of the code base.  Ironically rustfmt's config also defaults to the opposite of the lint.

The underlying choice of using or not using `field init shorthand` feels like a style choice not a code quality issue, so rustfmt feels like a more appropriate location than a compiler lint to me.

https://doc.rust-lang.org/rustc/lints/listing/warn-by-default.html#non-shorthand-field-patterns
https://rust-lang.github.io/rustfmt/?version=master&search=shorthand#use_field_init_shorthand

**Comment by jonas-schievink** [comment]
We have plenty of style lint in rustc

**Comment by rickvanprim** [comment]
I apologize if this came off as taking a stance on style lints in general which wasn't my intention.  What I'm bringing up here is that this particular style item is covered in two distinct places, which feels redundant, particularly when their defaults take opposite stances.  If people agree with that assessment, I'm making the case that I think style items (or at least this one) make more sense in rustfmt than in rustc, when possible, as rustfmt will fix the issue instead of just emitting a warning.

**Comment by rickvanprim** [comment]
I just embarrassingly realized these actually target different things, pattern matching versus field initialization.  Oops, closing.
