### ISSUE TITLE
Trait objects missing `#[track_caller]` shims

### ISSUE THREAD

**Issue by anp** [rust-lang/rust#74764]
After reducing a [repro of a potential track_caller bug](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=ab89f4bc0d72027f70546594c7e0747b) from @yaahc, I get a segfault from [this code](https://play.rust-lang.org/?version=beta&mode=debug&edition=2018&gist=5d89066b6706b1a5b3a07aa40212d6c1):

```rust
trait Handler {
    fn handle(&self);
}

impl<T> Handler for T {
    #[track_caller]
    fn handle(&self) {
        assert_eq!(std::panic::Location::caller().file(), file!());
    }
}

fn main() {
    let handler: &(dyn Handler) = &5u8;
    handler.handle();
}
```

This repros for me on my up-to-date checkout as well as for the current beta compiler. I'm not sure whether that makes this a regression from stable to beta, since it's an apparent bug in an API which is first stabilizing in this release.

cc @eddyb

**Comment by lcnr** [comment]
Oh boy, this causes a segfault on stable:
```rust
use std::ops::Index;

fn main() {
    let vec = vec!["String".into()];
    let handler: &dyn Index<usize, Output = String> = &vec;
    handler.index(2);
}
```
results in
```
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 2', Segmentation fault (core dumped)
```

**Comment by anp** [comment]
Oof! I'm looking at the existing tests and I realize what we missed. We test direct calls to tracked trait methods and we test indirect calls to tracked trait functions (i.e. no receivers), but we don't test indirect calls of trait methods with receivers.

**Comment by anp** [comment]
My immediate suspicion is that trait object vtables aren't going through the reification path we added to `Instance::resolve_for_fn_ptr`.

**Comment by anp** [comment]
Thanks to @eddyb for confirming this [doesn't seem to affect self-by-val](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=cc43609e3fcbfc81bfa0c83508157ca0).

**Comment by anp** [comment]
Opened https://github.com/rust-lang/rust/pull/74784 with a fix, thanks again to @eddyb for help finding the missing call!

**Comment by LeSeulArtichaut** [comment]
Assigning `P-critical` [as discussed as part of the Prioritization WG Procedure](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/I-prioritize.20.2374764.20Apparent.20miscompilation.20of.20.60.23.5Btrack_cal.E2.80.A6).
