### ISSUE TITLE
#[track_caller] for allocator APIs?

### ISSUE THREAD

**Issue by anp** [rust-lang/rust#74763]
Apologies if this has been raised before, but I've been playing around with trying to track where allocations happen with something like so:

```Rust
use libc_print::libc_println;
use std::alloc::{GlobalAlloc, Layout};
use std::panic::Location;

pub struct TracedAlloc<T: GlobalAlloc> {
    pub allocator: T,
}

unsafe impl<T> GlobalAlloc for TracedAlloc<T>
where
    T: GlobalAlloc,
{
    #[track_caller]
    unsafe fn alloc(&self, layout: Layout) -> *mut u8 {
        libc_println!("Alloc {:?} at {:?}", layout, Location::caller());
        self.allocator.alloc(layout)
    }

    #[track_caller]
    unsafe fn dealloc(&self, ptr: *mut u8, layout: Layout) {
        libc_println!("Dealloc {:?} at {:?}", layout, Location::caller());
        self.allocator.dealloc(ptr, layout)
    }
}
```

However the caller location is always the line I've put `#[global_allocator]` which makes `#[track_caller]` useless in this context.

_Originally posted by @xd009642 in https://github.com/rust-lang/rust/issues/47809#issuecomment-663910253_

---

note from @anp: I'm not sure how the global allocator hooks in but this might be possible?

**Comment by jdm** [comment]
I'm not sure if this will work, given the indirection in https://github.com/rust-lang/rust/blob/8cb94fc552dc200e19001b40767c0c279572c9de/src/liballoc/alloc.rs#L77-L81.

**Comment by anp** [comment]
Yeah, the only way to carry `#[track_caller]` through an `extern "Rust"` block is if both sides have it declared. It's technically possible but it would be a new (breaking) requirement on *all* allocators so I don't think that's feasible.

**Comment by lqd** [comment]
cc #74433
