### ISSUE TITLE
Ayu: Please don't make comment italic. Instead mark it with different color than doc comment.

### ISSUE THREAD

**Issue by lzutao** [rust-lang/rust#74770]
This is just my personal taste.
I'm never a fan of making comments italic. It is hard to read for me.

Rather, I really enjoy what Dark and Light theme is doing: Mark doc comments with different color than normal comments.

cc @Cldfire @jyn514 @GuillaumeGomez

**Comment by jyn514** [comment]
Can you add a screenshot of what this looks like in both Ayu and Dark themes?

**Comment by lzutao** [comment]
Here in Ayu and Dark theme respectively: 
![image](https://user-images.githubusercontent.com/15225902/88478671-6a9c3700-cf74-11ea-9b7d-682b631ea6d1.png)
![image](https://user-images.githubusercontent.com/15225902/88478681-7c7dda00-cf74-11ea-9c0f-dff33d293b1a.png)

**Comment by lzutao** [comment]
I was searching about the italic comments and found that people prefer both. 
But I think the good choice is default to non-italic and add a rustdoc config to change to italic.

**Comment by GuillaumeGomez** [comment]
> But I think the good choice is to default to non-italic and add a rustdoc config to change to italic.

We will definitely not add a rustdoc config for that (way too specific). :)

**Comment by Cldfire** [comment]
Thanks for your critique of the theme, it's been very helpful :)

I would like to keep the comment style italic because:

* It provides a rustdoc theme with italic comments for those who like it (if one dislike this there are two other themes that don't make this choice)
* The Ayu theme everywhere else has italic comments, example:

![Screen Shot 2020-07-26 at 11 59 14 AM](https://user-images.githubusercontent.com/13814214/88483729-d0b69900-cf37-11ea-8f38-fd2a16ffbb4b.png)

I don't want to break with the standard Ayu look in this regard unless a significant number of people find the italics to be a problem.

As far as the color being different between doc comments and normal comments, I am personally against this. I've never seen an editor highlight doc comments differently from normal comments, nor do I see a reason to do so. The only thing that sets doc comments apart from normal comments is that they are present in the generated rustdoc HTML, and to me this is not a reason to introduce an entirely new color into the mix just for the sake of styling them differently (why would you care about this when reading the comment? What benefit does the color provide?).

Here I would say similar to the above: the Ayu theme provides a choice to view comments with a unified color. If one dislikes this, there are two other themes available with that feature 🙂.

**Comment by GuillaumeGomez** [comment]
@Cldfire I'd like to comment in favour of removing the italic. In here it's important to remember that themes are only supposed to change colors, not presentation. Adding italic on comments is breaking the coherency with the other themes and I think it should be removed, even though the original theme has it (are you sure it's the theme and not the IDE btw?).

**Comment by Cldfire** [comment]
> @Cldfire I'd like to comment in favour of removing the italic. In here it's important to remember that themes are only supposed to change colors, not presentation. Adding italic on comments is breaking the coherency with the other themes and I think it should be removed

That's a fair point, I can agree with that.

> even though the original theme has it (are you sure it's the theme and not the IDE btw?).

Yes it is the theme 😉

**Comment by Mark-Simulacrum** [comment]
> As far as the color being different between doc comments and normal comments, I am personally against this. I've never seen an editor highlight doc comments differently from normal comments, nor do I see a reason to do so. 

I will note that my vim configuration at least does this and I personally quite like it -- I differentiate between regular comments and doc comments when reading. Regular comments are intended for the programmer and doc comments for the end-user of the API; those are at least for me two different mindsets.

![image](https://user-images.githubusercontent.com/5047365/88484123-779c3480-cf3a-11ea-89d8-43abe5502c5a.png)

**Comment by lzutao** [comment]
> I don't want to break with the standard Ayu look in this regard unless a significant number of people find the italics to be a problem.

Thank you. I've never use Ayu theme in editor other than in mdbook and rustdoc. It is great.
This issue (https://github.com/microsoft/vscode/issues/32579) is not related to rustdoc
but it points out a group of people finding a way to disable italic on comments and language keywords.

> I've never seen an editor highlight doc comments differently from normal comments

I wish Sublime Text render they differently. rust.vim already did it.
Mark already posted a reason for the differently: https://github.com/rust-lang/rust/issues/74770#issuecomment-664008738

**Comment by Cldfire** [comment]
> > As far as the color being different between doc comments and normal comments, I am personally against this. I've never seen an editor highlight doc comments differently from normal comments, nor do I see a reason to do so.
> 
> I will note that my vim configuration at least does this and I personally quite like it -- I differentiate between regular comments and doc comments when reading. Regular comments are intended for the programmer and doc comments for the end-user of the API; those are at least for me two different mindsets.
> 
> ![image](https://user-images.githubusercontent.com/5047365/88484123-779c3480-cf3a-11ea-89d8-43abe5502c5a.png)

Interesting! Thanks for chiming in.

Your point about who each type of comment is written for makes sense 👍 I'll look into a color that would make sense to use for doc comments in the theme here.

**Comment by Lokathor** [comment]
I'll throw another vote in favor of not using italics. They are, in general, a poor experience with monospaced fonts.

**Comment by GuillaumeGomez** [comment]
> I will note that my vim configuration at least does this and I personally quite like it -- I differentiate between regular comments and doc comments when reading.

If people are interested, we could use a different color for the doc comments. It sounds like a good add.

**Comment by Cldfire** [comment]
I played around with some colors and I believe `#f9ca89` meshes reasonably well as a doc comment color.

Before:

![image](https://user-images.githubusercontent.com/13814214/88485836-221a5480-cf47-11ea-883c-cf433a72717a.png)

After:

![image](https://user-images.githubusercontent.com/13814214/88485834-1cbd0a00-cf47-11ea-9ecf-b9795fa5206b.png)

Thoughts on this? I'm happy to get a PR in to make this change today.

**Comment by GuillaumeGomez** [comment]
I find the last proposal better, but maybe we should put it into another issue to not lose track of the original issue? ;)

**Comment by Cldfire** [comment]
Opened a new issue :)
