### ISSUE TITLE
Type-based search does not work for primitives since March

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#74780]
searched nightlies: from nightly-2019-05-02 to nightly-2020-07-17
regressed nightly: nightly-2020-03-20
searched commits: from https://github.com/rust-lang/rust/commit/f509b26a7730d721ef87423a72b3fdf8724b4afa to https://github.com/rust-lang/rust/commit/f4c675c476c18b1a11041193f2f59d695b126bc8
regressed commit: https://github.com/rust-lang/rust/commit/f4c675c476c18b1a11041193f2f59d695b126bc8

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.5.2</summary>

Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --script ./search_works.sh --start 2019-05-02 --preserve 
```

search_works.sh:

```
#!/bin/sh
set -eu
rustdoc search_function_type.rs
node ~/rustc/src/tools/rustdoc-js/tester.js --doc-folder doc --crate-name search_function_type --test-file ~/rustc/src/test/rustdoc-js/tmp/search-function-type.js
```

search_function_type.rs:

```
/// f
pub fn f(u: usize) -> usize {
    u
}
```

search-function-type.js:

```js
const QUERY = 'usize -> usize';

const EXPECTED = {
    'in_args': [
        { 'path': 'search_function_type', 'name': 'f' },
    ],
};
```

This requires a git clone of rustc as well as the following modification to `tester.js`:

```
diff --git a/src/tools/rustdoc-js/tester.js b/src/tools/rustdoc-js/tester.js
index 139e6f73f42..8a3ab056f80 100644
--- a/src/tools/rustdoc-js/tester.js
+++ b/src/tools/rustdoc-js/tester.js
@@ -182,7 +182,7 @@ function loadThings(thingsToLoad, kindOfLoad, funcToCall, fileContent) {
         var tmp = funcToCall(fileContent, thingsToLoad[i]);
         if (tmp === null) {
             console.log('unable to find ' + kindOfLoad + ' "' + thingsToLoad[i] + '"');
-            process.exit(1);
+            continue;
         }
         content += tmp;
         content += 'exports.' + thingsToLoad[i] + ' = ' + thingsToLoad[i] + ';';
```

</details>

Originally reported in https://github.com/rust-lang/rust/issues/60485#issuecomment-663900624.

**Comment by jyn514** [comment]
Relevant PR: https://github.com/rust-lang/rust/pull/69402

**Comment by jyn514** [comment]
The function is missing from the search index after that PR. Before:

```js
searchIndex["search_function_type"] = {"doc":"","i":[[5,"f","search_function_type","f",null,[[]]],[0,"m","","",null,null]],"p":[]};
addSearchOptions(searchIndex);initSearch(searchIndex);
```

After:
```js
var N=null,E="",T="t",U="u",searchIndex={};

searchIndex["search_function_type"]={"doc":E,"i":[[5,"f","search_function_type","f",N,[[["usize"]],["usize"]]],[0,"m",E,E,N,N]],"p":[]};
initSearch(searchIndex);addSearchOptions(searchIndex);
```

**Comment by jyn514** [comment]
Actually it looks like the function is still there, it's just missing the types for the arguments and return type!

**Comment by jyn514** [comment]
Maybe this bit of code is skipping it when it wasn't before? https://github.com/rust-lang/rust/pull/69402/files?file-filters%5B%5D=.rs#diff-2b73a40b29f966df2a77a3bbaf34a9f1L234-R246

**Comment by jyn514** [comment]
Yeah, I don't think arguments have def ids.

**Comment by GuillaumeGomez** [comment]
To be exact, the problem seems to come from:

```rust
Primitive(p) => crate::html::render::cache().primitive_locations.get(&p).cloned(),
```

coming from:

```
impl GetDefId for Type {
    fn def_id(&self) -> Option<DefId> {
        ...
    }
}
```

in the `librustdoc/clean/types.rs` file.

**Comment by Manishearth** [comment]
Through some chats in discord it seems like a good approach to this would be to:

 - compute a separate list of primitives before starting the whole cleaning rigmarole. For efficiency it might be worth tagging `std` as `doc(has_primitives)` or something if we'd like, but this wouldn't be a perf loss since this work is being done anyway.
 - use that list in `GetDefId for Type`

Eventually I'd like to stop having the cache be a global parameter and instead passing it around as much as possible so that such problems are easier to avoid.

**Comment by camelid** [comment]
Labeling as `P-high` as per the guidelines for rustdoc regressions.
