### ISSUE TITLE
Style doc comments different from normal comments in the Ayu theme

### ISSUE THREAD

**Issue by Cldfire** [rust-lang/rust#74788]
The point was raised in #74770 that the other themes style doc comments differently from normal comments, and perhaps the Ayu theme should do so as well.

Current appearance:

![image](https://user-images.githubusercontent.com/13814214/88485836-221a5480-cf47-11ea-883c-cf433a72717a.png)

Some potential options:

* `#f9ca89`

![image](https://user-images.githubusercontent.com/13814214/88485834-1cbd0a00-cf47-11ea-9ecf-b9795fa5206b.png)

* `#a1ac88`

![image](https://user-images.githubusercontent.com/13814214/88485894-c13f4c00-cf47-11ea-929d-495c1279e67b.png)

**Comment by GuillaumeGomez** [comment]
Like I said: I prefer the last one.
