### ISSUE TITLE
`#[derive(PartialEq, PartialOrd)]` produces too restrictive implementations for generic structs

### ISSUE THREAD

**Issue by WaffleLapkin** [rust-lang/rust#74795]
This derive:
```rust
#[derive(PartialEq, PartialOrd)]
struct Wrap<T>(T);
```
Currently produces such `impl`s:
```rust
impl<T: PartialEq> PartialEq<Wrap<T>> for Wrap<T> { ... }
impl<T: PartialOrd> PartialOrd<Wrap<T>> for Wrap<T> { ... }
```
Instead of looser:
```rust
impl<T: PartialEq<U>, U> PartialEq<Wrap<U>> for Wrap<T> { ... }
impl<T: PartialOrd<U>, U> PartialOrd<Wrap<U>> for Wrap<T> { ... }
```

In the case of `PartialOrd`, you can fix the issue just by implementing the trait by hand (though if `derive` would do this automatically it would be better). However, in the case of `PartialEq` implementing the trait by hand would remove the [`StructuralEq`](https://doc.rust-lang.org/std/marker/trait.StructuralEq.html) and [`StructuralPartialEq`](https://doc.rust-lang.org/std/marker/trait.StructuralPartialEq.html).

Also, note that this issue also affects core types e.g. [`Option`](https://doc.rust-lang.org/std/option/enum.Option.html#impl-PartialEq%3COption%3CT%3E%3E)

**Comment by jonas-schievink** [comment]
I don't think this is implementable. The derive doesn't know anything about type parameters.

**Comment by Mark-Simulacrum** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/26925 with regard to the derive issue.

With respect to the core types, e.g,. Option, it is currently somewhat desirable to not be fully generic because we lose type inference if we are.

**Comment by WaffleLapkin** [comment]
@Mark-Simulacrum the issue you've linked doesn't seem to fully relate to this issue because th linked one mostly speaks about looking into the type itself (e.g.: removing the bound on some type parameters entirely because it isn't used), whereas to fix _this_ issue you don't need any kind of type inspection - derive can simply duplicate all type parameters:
```rust
#[derive(PartialEq)]
struct Wrap<A, B> { /* doesn't matter */ }
// =>
impl<A, B, ARhs, BRhs> PartialEq<Wrap<ARhs, BRhs>> for Wrap<A, B>
where
    A: PartialEq<ARhs>,
    B: PartialEq<BRhs>,
{ /* ... */ }
```

Though this would be a breaking change so probably needs some flag (e.g.: `#[derive(PartialEq(looser))]` or something)

**Comment by Mark-Simulacrum** [comment]
That falls under the same general concept, so I'm going to leave this closed, but you're not wrong.
