### ISSUE TITLE
Doc: code example of explicit register operand isn't up to date 

### ISSUE THREAD

**Issue by a1trl9** [rust-lang/rust#74805]
On the website, the last line of the code example in this [section](https://doc.rust-lang.org/unstable-book/library-features/asm.html#explicit-register-operands) is:
```rust
(hi as u128) << 64 + lo as u128
```
Snapshot:
![Screenshot from 2020-07-27 10-00-56](https://user-images.githubusercontent.com/11512033/88496557-1c2c7e00-cff0-11ea-941d-304300d45be7.png)

which is lack of parentheses around `(hi as u128) << 64`, as shown in the [source code ](https://github.com/rust-lang/rust/blame/master/src/doc/unstable-book/src/library-features/asm.md#L215).

Not sure if it is because the markdown doc isn't deployed yet. Checked in two network environments, both Chrome and Firefox. Same result.

**Comment by ehuss** [comment]
That URL is for the stable documentation, which is 6-12 weeks behind master.  If you want the latest documentation, add `nightly` to URL like https://doc.rust-lang.org/nightly/unstable-book/library-features/asm.html#explicit-register-operands, which is rebuilt every night.
