### ISSUE TITLE
Docs do not mention that tuple destructing can use the "and the rest" operator

### ISSUE THREAD

**Issue by That3Percent** [rust-lang/rust#74830]
I think it would be useful if on this page: [Destructuring Tuple](https://doc.rust-lang.org/stable/rust-by-example/flow_control/match/destructuring/destructure_tuple.html) it mentioned the "and the rest" operator.

For example: `let (a, b, ..) = (0, 1, 2, 3, 4);` is possible, but the only case I could find something like that was in [Appendix B - Operators and Symbols](https://doc.rust-lang.org/book/appendix-02-operators.html)

**Comment by LeSeulArtichaut** [comment]
This should be reported in the [`rust-lang/rust-by-example`](https://github.com/rust-lang/rust-by-example) repository. Maybe someone (@steveklabnik?) can move this issue?

**Comment by That3Percent** [comment]
Sorry, my bad. I've opened the issue in rust-by-example [here](https://github.com/rust-lang/rust-by-example/issues/1364). Closing this as duplicate.
