### ISSUE TITLE
Rustdoc should link fields/variants to their corresponding section

### ISSUE THREAD

**Issue by Aaron1011** [rust-lang/rust#74849]
Currently, the generated Rustdoc page for a struct/enum just writes out struct fields/enum variants as plain text. It would nice if Rustdoc generated clickable links to the corresponding section for the field/variant - this would make it easy to read the docs for a particular field.

**Comment by GuillaumeGomez** [comment]
It was fixed in https://github.com/rust-lang/rust/pull/90089.
