### ISSUE TITLE
Add Mutex::arc method

### ISSUE THREAD

**Issue by MarinPostma** [rust-lang/rust#74866]
Mutexes are seldom used without an Arc, I propose to add a method `Mutex::arc` that returns an `Arc<Mutex<_>>`. This would make code more readable and compact almost everywhere mutexes are used. It also makes the intent clearer, as we first think about the `Mutex`, not the `Arc` when we use one.

```rust
// this:
let mutex = Arc::new(Mutex::new(Thing { inner: 0 }));
// would turn into this
let mutex = Mutex::arc(Thing { inner: 0 });
```

 This would also mimic what we already have with the `Box::pin` method that return a `Pin<Box<_>>`.

**Comment by LeSeulArtichaut** [comment]
It would also probably make sense to add an `arc` method for `RwLock`?

**Comment by MarinPostma** [comment]
I am preparing a PR

**Comment by Stupremee** [comment]
SInce the original PR was closed, I will open a new PR 

@rustbot claim

**Comment by JohnTitor** [comment]
I'm going to close this as #80007 was also closed. Thanks!
