### ISSUE TITLE
Joining thread in thread local storage destructor never returns on Windows

### ISSUE THREAD

**Issue by emgre** [rust-lang/rust#74875]
The following code never returns on Windows. The console never prints `Done`, and sometimes the `Start thread` and `End thread` are also not even printed. On Linux, it runs as expected.

```rust
use std::thread;
use std::time::Duration;

struct Test {
    thread: Option<thread::JoinHandle<()>>,
}

impl Test {
    fn new() -> Self {
        let thread = std::thread::spawn(move || {
            println!("Start thread");
            thread::sleep(Duration::from_millis(500));
            println!("End thread");
        });

        Self {
            thread: Some(thread),
        }
    }
}

impl Drop for Test {
    fn drop(&mut self) {
        if let Some(thread) = self.thread.take() {
            thread.join().unwrap();
        }
    }
}

fn main() {
    thread_local!(
        static R: Test = Test::new();
    );

    thread::spawn(|| {
        R.with(|_| {});
    })
    .join()
    .unwrap();

    println!("Done");
}

```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=9859cc3e2a58baa583118162986fd457))

Output:

```
Start thread
End thread
Done

```

Errors:

```
   Compiling playground v0.0.1 (/playground)
    Finished dev [unoptimized + debuginfo] target(s) in 1.20s
     Running `target/debug/playground`

```

My guess is that this wizardry is in cause: https://github.com/rust-lang/rust/blob/2c28244cf0fc9868f55070e55b8f332d196eaf3f/library/std/src/sys/windows/thread_local_key.rs#L1-L252

**Comment by RalfJung** [comment]
This is specifically about the TLS destructor of the main thread, right? That one is kind of dubious anyway: https://github.com/rust-lang/rust/issues/28129.

Does this also happen when it's not the main thread's dtors?

**Comment by RalfJung** [comment]
Cc @mati865

**Comment by emgre** [comment]
In my example, the TLS destructor is called from within the spawned thread AFAIK, not the main thread. Even if I move the `thread_local!` inside the spawned thread, it has the same faulty behaviour.

**Comment by emgre** [comment]
I stepped a bit through libstd from my example. The thread spawned from `Test` reaches the end and properly returns. The `join` in `main` then blocks on this `WaitForSingleObject`: https://github.com/rust-lang/rust/blob/1.45.0/src/libstd/sys/windows/thread.rs#L73

It looks like Windows isn't aware that the thread actually ended... 🤔

**Comment by RalfJung** [comment]
Hm good point, the main thread never uses `R`.

**Comment by mati865** [comment]
I can only confirm this hangs with both MinGW and MSVC in the line linked by **emgre**.

@RalfJung you should call Windows WG.

**Comment by retep998** [comment]
`join()` does not return until the thread has actually and completely finished running. If it is still running TLS destructors then the thread is *still* running. Doing a `join()` on the current thread will always deadlock, at least on Windows anyway.

**Comment by RalfJung** [comment]
@retep998 I don't think there's a join on the current thread anywhere here?

**Comment by retep998** [comment]
Hmmm, I'll have to investigate further into what is going on...

**Comment by retep998** [comment]
There's *definitely* race conditions involved as inserting sleeps at certain points changes the behavior.

**Comment by retep998** [comment]
This excerpt from MSDN might be relevant:

> The ExitProcess, ExitThread, CreateThread, CreateRemoteThread functions, and a process that is starting (as the result of a CreateProcess call) are serialized between each other within a process. Only one of these events can happen in an address space at a time. This means the following restrictions hold:
> 
>   * During process startup and DLL initialization routines, new threads can be created, but they do not begin execution until DLL initialization is done for the process.
>   * Only one thread in a process can be in a DLL initialization or detach routine at a time.
>   * ExitProcess does not return until no threads are in their DLL initialization or detach routines.
