### ISSUE TITLE
println! incorrectly prints lines from files using CRLF

### ISSUE THREAD

**Issue by Naxane** [rust-lang/rust#74893]
I tried this code:

```rust
use std::fs::File;
use std::io::prelude::*;
use std::env;

fn main() -> std::io::Result<()> {
	let args: Vec<String> = env::args().collect();

	let mut file = File::open(&args[1])?;
	let mut contents = String::new();

	file.read_to_string(&mut contents)?;

	let lines = contents.split("\n");
	
	for line in lines {
		println!("{}###", line);
	}

	Ok(())
}
```

With file using CRLF:

```
some_function = (argument) {
	
}
```

I expected to see this happen: Console output
```
some_function = (argument) {###
        ###
}###
```
^ This is what I get when the file uses LF

Instead, this happened: Console output
```
###e_function = (argument) {
###
}###
```

### Meta

Issue occurs on both stable (stable-x86_64-pc-windows-msvc) and nightly (nightly-x86_64-pc-windows-msvc)

`rustc --version --verbose`:
```
rustc 1.47.0-nightly (6c8927b0c 2020-07-26)
binary: rustc
commit-hash: 6c8927b0cf80ceee19386026cf9d7fd4fd9d486f
commit-date: 2020-07-26
host: x86_64-pc-windows-msvc
release: 1.47.0-nightly
LLVM version: 10.0
```

</details>

**Comment by nbdd0121** [comment]
Your file uses CRLF as the line ending, and you only split with `\n`, so this is expected behaviour.

**Comment by nbdd0121** [comment]
If you don't want to keep the CR, consider using https://doc.rust-lang.org/std/primitive.str.html#method.lines which trims the CR away for you.

**Comment by Naxane** [comment]
Same issue occurs when splitting with `\r\n`
