### ISSUE TITLE
looks like has 2 mut borrow?? I donnot understand

### ISSUE THREAD

**Issue by 756445638** [rust-lang/rust#74897]
~~~
use futures::executor::block_on;
async fn  xxx<F>(f : F) where F : FnOnce()->() {
        f();
}
fn main(){
    let mut x = 100;
    block_on(xxx( ||{ x+=1;}));
    x -= 1;
    println!("{}" , x);
}

~~~
###############
100

**Comment by jonas-schievink** [comment]
Hi! This issue tracker is mainly meant for bug reports and concrete, small feature requests. Questions like this are better asked in the user forum at https://users.rust-lang.org/ or on [one of the chat platforms](https://www.rust-lang.org/community) used by the Rust community.
