### ISSUE TITLE
Range bound in Vec::drain may overflow and fail to drain the vector

### ISSUE THREAD

**Issue by Shnatsel** [rust-lang/rust#74909]
I tried this code:

```rust
fn main() {
    let mut v = vec![1,2,3];
    v.drain(..=usize::MAX);
}
```

According to the [documentation](https://doc.rust-lang.org/stable/std/vec/struct.Vec.html#method.drain) this should panic, since `usize::MAX` is greater than the length of the vector. Instead, no panic happens and no elements are removed from the vector.

Upon investigation it appears that the increment of the upper range bound silently overflows and the range is interpreted as `0..0`.

I believe using `.saturating_add(1)` instead of `+1` should make this panic, which is what I'd expect to happen.

### Meta
`rustc --version --verbose`:
```
Playground stable (1.45)
```
Found through fuzzing via https://github.com/jakubadamw/rutenspitz

**Comment by Shnatsel** [comment]
I'd appreciate if someone from the libs team could confirm what the expected behavior is in this case.

**Comment by tmiasko** [comment]
#72237 is an existing bug report about overflows in API accepting ranges.

**Comment by Shnatsel** [comment]
Ah thanks, I'll close this in favor of the existing bug.
