### ISSUE TITLE
Clippy toolstate is broken

### ISSUE THREAD

**Issue by mati865** [rust-lang/rust#74911]
https://rust-lang-nursery.github.io/rust-toolstate/ reports Clippy as `test fail` on both platforms but it's passing the tests on `x86_64-gnu-tools` right now.

**Comment by ehuss** [comment]
Clippy toolstate is no longer being recorded because it is required to pass now.  The clippy entry should maybe just be removed from the toolstate tracker?

**Comment by mati865** [comment]
Are the tests required to pass now, I remember Clippy was effectively `build pass` for some time after the migration.

**Comment by Mark-Simulacrum** [comment]
Yeah I'm not actually sure why it's showing up to be honest, but it seems like a bug upstream -- we're not recording it in this repository anymore https://github.com/alexcrichton/rust/blob/2c28244cf0fc9868f55070e55b8f332d196eaf3f/src/bootstrap/toolstate.rs#L281-L286.

I'm moving this to toolstate repo.

**Comment by Mark-Simulacrum** [comment]
https://github.com/rust-lang-nursery/rust-toolstate/issues/19
