### ISSUE TITLE
Tracking Issue for `fn unsigned_abs`

### ISSUE THREAD

**Issue by carbotaniuman** [rust-lang/rust#74913]
This is a tracking issue for `fn unsigned_abs` on signed integral types.
The feature gate for the issue is `#![feature(unsigned_abs)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also uses as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Implementation history
First implemented in #74759

**Comment by jhpratt** [comment]
Are there any outstanding issues with this feature gate? It has a trivial implementation that is unquestionably correct, and it seemed quite clear in the RFC that it was desired.

**Comment by Kixunil** [comment]
One significant issue I see is currently the implementation for `isize` returns `u64` instead of `usize`.

[Documentation of the function](https://doc.rust-lang.org/std/primitive.isize.html#method.unsigned_abs)
[Playground proof that the implementation matches the documentation](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=e49f568a52ae3ba876a9fc87d0c36520)

**Comment by jhpratt** [comment]
Hmm…the behavior [is different](https://github.com/rust-lang/rust/blob/master/library/core/src/num/mod.rs#L130-L155) for different widths (16, 32, or 64). However, usize and u16/32/64 are _not_ the same type. I'll make a modification locally and open a PR shortly.

**Comment by Kixunil** [comment]
Yes, exactly. Good job with the PR!

**Comment by AngelicosPhosphoros** [comment]
Why `unsigned_abs` of `isize` returns `u64` instead of `usize`?
IMHO, it is not valid.
https://doc.rust-lang.org/std/primitive.isize.html#method.unsigned_abs

**Comment by CryZe** [comment]
This is fixed on nightly (that you need anyway to use this for now)

**Comment by AngelicosPhosphoros** [comment]
Nice, thank you!

**Comment by jhpratt** [comment]
Yeah, it just hasn't propagated through to stable yet. Once that happens, I think stabilization should happen relatively quickly.
