### ISSUE TITLE
sort_unstable's random swap is biased

### ISSUE THREAD

**Issue by TheIronBorn** [rust-lang/rust#74928]
The "modulo a power of two" technique used by `sort::break_patterns` is far more biased than modulo or [integer multiplication](https://arxiv.org/abs/1805.10941). (I think that their sort of bias is acceptable here).
https://github.com/rust-lang/rust/blob/584e83dd5ae7a75b8214560c22eafbcfe153caa6/library/core/src/slice/sort.rs#L582-L585

A graph of the techniques for `len = 50` and 8-bit integers using `Mod[Mod[x, 2^Ceiling[Log[2, len]]], len]` (Mathematica) for the power method ([code](https://gist.github.com/TheIronBorn/e31bb13ff32349595eddde20d1c77c99))
![image](https://user-images.githubusercontent.com/7707250/88842000-5489b300-d1ce-11ea-9eb3-a28c6aa389e1.png)

The average standard deviation of the counts of possible outputs for all possible `len` are so ([code](https://gist.github.com/TheIronBorn/71b7b160d604ac5d83c4c847a31c0933)):
|            | pow     | mul  | mod  |
| ---        | ---     | ---  | ---  |
| **8-bit**  | 10.85   | 0.16 | 0.16 |
| **16-bit** | 2776.36 | 0.16 | 0.16 |

For a picture of the real-world effect of this bias, here is an image where darker pixels are outputs, the vertical axis is the three outputs of the `sort.rs` code, and the horizontal axis is each new `len` (32-bit, 50_000 `len` values after `MAX_INSERTION`, shrunk in post-processing to fit, code and full image for this and all below [here](https://gist.github.com/TheIronBorn/3138c91f23122ea68239af7646417bc1))
![Xorshift scaled](https://user-images.githubusercontent.com/7707250/88843777-32456480-d1d1-11ea-8597-d5d7e7c5cbda.png)
There is a clear bias toward lower values even for our limited use.

And here it is using [`rand::thread_rng`](https://docs.rs/rand/0.7.3/rand/fn.thread_rng.html)
![StdRng scaled](https://user-images.githubusercontent.com/7707250/88845515-d0d2c500-d1d3-11ea-96b0-ab534c360d58.png)
Still a clear bias

Using the integer multiplication reduction we get
|`Xorshift`|`thread_rng`|
|---|---|
|![Xorshift mul scaled](https://user-images.githubusercontent.com/7707250/88845635-f790fb80-d1d3-11ea-8276-2afa97c28b40.png)|![ThreadRng mul scaled](https://user-images.githubusercontent.com/7707250/88845648-fc55af80-d1d3-11ea-822a-be8086542435.png)|

Still some clear non-randomness but the bias is more evenly distributed across all values (the picture is uglier in full-size though due to Xorshift's low quality).

To avoid that patterning the main issue is the low entropy of our `len` seed. Iterating the PRNG 2 times before using the output produces:
![XorshiftIterated scaled](https://user-images.githubusercontent.com/7707250/88854913-96702480-d1e1-11ea-8a5e-2c3bb80c29c3.png)
Decent but a little too even.

A better solution is to use an integer hash as a PRNG instead, they are much better at immediately using low entropy "seeds".
["7 shifts"](https://burtleburtle.net/bob/hash/integer.html) by Bob Jenkins
![Jenkins scaled](https://user-images.githubusercontent.com/7707250/88855092-e0590a80-d1e1-11ea-98d2-4246fb7f51d3.png)

**Comment by peteroupc** [comment]
@SubstandardZeal: On an unrelated GitHub issue, @theironborn made charts that are highly related to this topic: https://github.com/rust-lang/rust/issues/74928

**Comment by Mark-Simulacrum** [comment]
Per https://github.com/rust-lang/rust/pull/94401#issuecomment-1071868864, I'm going to go ahead and close this issue as not really a "bug" that we're looking to fix at this time, though if a stronger motivation comes along that perspective could be reconsidered.
