### ISSUE TITLE
Classify themes as light/dark and fallback to the base light/dark theme if theme does not exist

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/rust#74937]
See https://github.com/rust-lang/docs.rs/issues/919 for some context.

When browsing docs within a single Web context (a.k.a. a single instance of `LocalStorage`, mostly based on the domain but also affected by other details) generated from multiple versions of `rustdoc` (or with custom themes) you may set the selected theme to one that does not exist in all the documentation. When loading a page with an unknown theme `rustdoc` will just leave the theme as the default `light` theme, which can result in suddenly been blinded if generally using a dark theme in a dark room.

To avoid the binding effect it would be good to have all builtin (and custom) themes classified into light or dark, and fallback to the base light/dark theme as appropriate when the exact theme requested is unknown. This will have to be implemented something like storing the classification into local-storage alongside the theme itself, since the rustdoc JS loading the theme will not know the theme to classify it itself.

If anyone can think of a plan that is backwards compatible with both pre-ayu rustdoc, and the current nightlies with ayu available, it'd be great if we can get this working across all versions on docs.rs somehow; but I doubt this is possible, so probably best to focus on just getting something that works on documentation generated going forward.

**Comment by pickfire** [comment]
Isn't it better to fallback to the system default theme? If the system uses dark theme I don't know why should it fallback to a light theme. Personally, I wish there is an automatic light/dark theme (can be done using css only), my phone automatically switches the system light/dark setting depending on the time, I bet other phones have this feature too.

**Comment by jyn514** [comment]
Related: #77809

**Comment by GuillaumeGomez** [comment]
As far as I can tell, it was fixed by https://github.com/rust-lang/rust/pull/77809. Don't hesitate to reopen this issue if something from this issue is still missing though!
