### ISSUE TITLE
Can not override previous opt-levels in list of command flags

### ISSUE THREAD

**Issue by sstewartgallus** [rust-lang/rust#7493]
If one passes multiple opt-level flags to the compiler (for example -O, and --opt-level=3) then an error results. Instead, the previous setting should be overridden. This is bad because then makefiles don't work easily. For example, I had to use the command line `make RUSTFLAGS=--opt-level=3 DISABLE_OPTIMIZE=1` instead of the more obvious `make RUSTFLAGS=--opt-level=3` when compiling rust as optimized because of this error.

**Comment by tamird** [comment]
This discussion should probably move to the RFcs repo. cc @steveklabnik

**Comment by brson** [comment]
Visiting for triage. Specifying `-O` twice works, specifying `-C opt-level` twice works. Mixing them does not. I think it should be fixed. This is super easy to do. There is explicit code in `rustc::session::config` that turns this scenario into an error. Instead it should figure out which one appeared list in the argument list and choose it. May require a bit of a hack to make that happen. Add a test case to `src/run-make`.

**Comment by sanxiyn** [comment]
I did this in #32399. The conclusion then was this needs changes to `getopts`.

**Comment by brson** [comment]
Removing easy label because lack of agreement on way forward.
