### ISSUE TITLE
Awkward table on firefox

### ISSUE THREAD

**Issue by gabriel-araujjo** [rust-lang/rust#74944]
The borders of tables seem unaligned on Firefox. I don't know if this bug is in docs.rs or in Firefox, so I have submit it on both.

![Screenshot from 2020-07-30 09-05-42](https://user-images.githubusercontent.com/3980936/88921006-2ba40500-d244-11ea-948e-8caaed59b6d3.png)

The screenshot above is from https://docs.rs/new-home-application-macro/1.0.0/new_home_application_macro/ on Firefox 78.0.2 running on Arch Linux.

**Comment by pickfire** [comment]
What's the difference?

![image](https://user-images.githubusercontent.com/4687791/88944062-da852700-d2be-11ea-908e-07092fed00f3.png)

I am using firefox developer edition 79 but I don't notice anything wrong with the table.

**Comment by nagisa** [comment]
This is a [firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1508033). Closing.
