### ISSUE TITLE
Is RawVec still necessary?

### ISSUE THREAD

**Issue by Plecra** [rust-lang/rust#74962]
While reading the implementation of RawVec, I was struggling to distinguish it from a `Box<[MaybeUninit<T>]>`. Is there a significant difference in the API?

I ask because, if they are interchangeable, I think writing the implementations based on `Box` would be worthwhile:

- I'd expect it to reduce the `unsafe` code in `Vec` etc.
- It'd also make the code much more readable. By using the types to express the combination of properties `RawVec` has, readers are given pointers to help understand what the type is achieving (allocating (`Box`) uninitialized memory (`MaybeUninit`) with a runtime length (`[T]`))

**Comment by nbdd0121** [comment]
Currently `Box<[MaybeUninit<T>]>` is constructed using a RawVec. https://doc.rust-lang.org/1.45.1/src/alloc/boxed.rs.html#277-279

**Comment by Mark-Simulacrum** [comment]
`Box<[MaybeUninit<T>]>` doesn't have a vec-like API, nor should it I think (at least, it feels like the wrong fit to me). RawVec is similar at the low level but conceptually rather different, I wouldn't want to rewrite things from it to `Box<[MaybeUninit<T>]>`, which is much more verbose and IMO clunky.
