### ISSUE TITLE
Implementing fmt::Display for non-existing variant compiles without any error

### ISSUE THREAD

**Issue by ohsayan** [rust-lang/rust#74978]
**I tried this code:**

```rust
use std::fmt;

enum SuperEnum {
  Cyan,
  Magenta,
  Yellow,
}

impl fmt::Display for SuperEnum {
  fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
    use SuperEnum::*;
    Cyan => write!(f, "Cyan"),
    Magenta => write!(f, "Magenta"),
    Yellow => write!(f, "Yellow"),
    Key => write!(f, "Key!!")
  }
}

fn main() {
  // nothing to see here
}
```

**I expected to see this happen:** There should've been a compilation error

**Instead, this happened:** The program compiled successfully

### Meta

Used rustc 1.45.1, on the [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=58d1494c2403e1865fa2ec3f715df6af)

**Comment by jonas-schievink** [comment]
That is a wildcard pattern that binds the value to the variable `Key`. Closing since this is working as expected.

**Comment by ohsayan** [comment]
> That is a wildcard pattern that binds the value to the variable `Key`. Closing since this is working as expected.

So this is an expected outcome?

**Comment by Lonami** [comment]
Yes, it's expected, and the compiler already warns it's unreachable. This is probably an indication that something does not behave as expected.

**Comment by ohsayan** [comment]
@Lonami Right. Makes sense. But this seemed a little ambiguous to me as we already have `_` for wildcards.

**Comment by Lonami** [comment]
Binding it to something (a proper name) will let you use it, while `_` does not, even if both bind to "everything".
