### ISSUE TITLE
Misdocumented `move` keyword: `move` closures are *not* “represented by the FnOnce trait”

### ISSUE THREAD

**Issue by steffahn** [rust-lang/rust#74997]
https://doc.rust-lang.org/std/keyword.move.html states:

> `move` converts any variables captured by reference or mutable reference to owned by value variables. The three [`Fn` trait](https://doc.rust-lang.org/std/ops/trait.Fn.html)'s mirror the ways to capture variables, when `move` is used, the closures _[sic]_ is represented by the `FnOnce` trait.

The second half of the second sentence is plain wrong and [causes confusion](https://users.rust-lang.org/t/move-and-impl-fn/46660).

@rustbot modify labels: T-doc, T-libs, C-enhancement. (Is tagging T-doc [still reasonable](https://blog.rust-lang.org/inside-rust/2020/03/27/goodbye-docs-team.html)?)

This issue has been assigned to @poliorcetics via [this comment](https://github.com/rust-lang/rust/issues/74997#issuecomment-668798798).

**Comment by poliorcetics** [comment]
@rustbot claim

> (Is tagging T-doc still reasonable?)

Yes, it allows for easy searching of doc issue (at least for me), with `label: T-doc`.
