### ISSUE TITLE
LLDB is not able to find default source location

### ISSUE THREAD

**Issue by smallB007** [rust-lang/rust#75002]
https://github.com/rust-lang/rust/issues/33674<< Still happening in 2020!!!

**Comment by jonas-schievink** [comment]
No reason to open a duplicate. You will need to provide more info if you want to see this fixed. 

I also suggest toning down your language a bit, most people working on Rust do this in their free time, and it isn't exactly motivating to have people complain like that.

**Comment by smallB007** [comment]
"most people working on Rust do this in their free time"
And again that crap, I'm doing it for free so don't expect any quality from it.
