### ISSUE TITLE
Tracking issue for dropping python2 support

### ISSUE THREAD

**Issue by lzutao** [rust-lang/rust#75006]
In https://github.com/rust-lang/rust/pull/74905#issuecomment-667528649, @Mark-Simulacrum said that:
> We have not established a minimum minor version for Python 3, we'd need to do some research about what is available on older (linux) systems by default (or through package managers).
> 
> Python 2 is still supported by many distros to my knowledge.

I open this issue to track when we drop python2 support.
<details>
    <summary>Some info about Python versions in some Linux distros</summary>

[![Packaging status](https://repology.org/badge/vertical-allrepos/python.svg)](https://repology.org/project/python/versions)
</details>

---

Current status: https://github.com/rust-lang/rust/issues/75006#issuecomment-667547013

**Comment by jyn514** [comment]
This should be an MCP. I don't think we should drop python2 at all, in many distros `python` still mean python2.

**Comment by lzutao** [comment]
But how long should we support python 2?

**Comment by jyn514** [comment]
That should be part of the MCP.

**Comment by Mark-Simulacrum** [comment]
IMO it is somewhat premature to consider dropping python 2 (or even when to drop it). Right now continuing to support it is essentially painless - we don't have much python code, and the code we do have is relatively rarely edited in a major way (nor would I want to edit it).

**Comment by Mark-Simulacrum** [comment]
I am going to close this -- if someone wants to propose that we drop python 2 sooner, they should file a compiler team MCP.
