### ISSUE TITLE
rustdoc page styles are broken with Waterfox

### ISSUE THREAD

**Issue by ensc** [rust-lang/rust#75011]
https://docs.rs does not work with Waterfox because it relies on the non-standard `disabled=""` Attribute in the theme `<link>` tags:

```html
      <link href="/light-20200726-1.47.0-nightly-6c8927b0c.css" id="themeStyle" rel="stylesheet" type="text/css">
      <link disabled="" href="/dark-20200726-1.47.0-nightly-6c8927b0c.css" rel="stylesheet" type="text/css">
      <link disabled="" href="/ayu-20200726-1.47.0-nightly-6c8927b0c.css" rel="stylesheet" type="text/css">
```

Without "disabled" support (which is the case with Waterfox), all three links will be enabled and will make the (imo unreadable) "ayu" the active one.

Accordingly https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link this attribute requires very recent browsers and is marked as "Deprecated: do not use for new websites"

**Comment by jyn514** [comment]
This is a rustdoc issue, not docs.rs. I transferred to rust-lang/rust.

**Comment by jyn514** [comment]
Can you give an example page where this happens?

**Comment by ensc** [comment]
It happens with every crate on https://docs.rs   E.g. https://docs.rs/griddle/0.3.1/griddle/  (randomly selected by "I'm feeling lucky")

**Comment by jyn514** [comment]
I don't see it on https://docs.rs/postgres/0.17.0-alpha.2/postgres/. So it looks like it might have been introduced as part of the Ayu theme, cc @Cldfire

**Comment by jyn514** [comment]
Would the fix be as simple as changing `disabled=""` to `disabled`?

**Comment by jyn514** [comment]
Hmm, this looks like the relevant code, but it uses `disabled`, not `disabled=""`.

https://github.com/rust-lang/rust/blob/0e89f50f6e937349233db1c52af2b33c683782e6/src/librustdoc/html/layout.rs#L172-L186

**Comment by ensc** [comment]
@jyn514  yes; the postgres link is ok (seems to be generated by rust-1.41).  It affects probably crates which were uploaded recently.

Trying to change `disabled=""` to `disabled` in Webdeveloper does not seem to have any effect.   The `disabled` Attribute is probably not supported at all by Waterfox; the browser is based on Firefox 56 and `disabled` requires version 68 at least.

**Comment by jyn514** [comment]
https://rust-lang.github.io/rfcs/1985-tiered-browser-support.html#supported-browsers

> Goal: Ensure functionality of our web content for 80% of users.
> Browsers:
>  last 1 Firefox version
>  Firefox ESR

The latest ESR of firefox is 68: https://www.mozilla.org/en-US/firefox/68.0esr/releasenotes/

So I'm inclined to close this as wontfix.

**Comment by ensc** [comment]
Accordingly https://developer.mozilla.org/en-US/docs/Web/HTML/Element/link#Browser_compatibility is is not supported by Safari either (which is in your list).

As already noted, page above says about this attribute "Deprecated. Not for use in new websites."

**Comment by Nemo157** [comment]
Changing styles appears to work fine on recent mobile and desktop Safari, so if it's not supported, it's not supported in a way which doesn't break anything.

**Comment by ensc** [comment]
Nevertheless, it is bad to rely on deprecated and proprietary extensions and break websites completely.

**Comment by jyn514** [comment]
@ensc I understand your viewpoint and I realize this is frustrating. However the rustdoc team has limited time and resources, and we have to choose how to spend it. If you have ideas how to fix this feel free to make a PR and I would be happy to review it.

**Comment by Cldfire** [comment]
@ensc I apologize for the problem I created here with my PR! It's never fun to have one's setup broken by changes made elsewhere, and for that I am sorry.

I was actually unaware that the `disabled` attribute on `link` elements is discouraged from use, so thank you for bringing that to our attention here, I appreciate it.

As others in this thread have made clear, the browser support target around here is fairly recent. This is a consequence of that the fact that most of us are unpaid volunteers, and while we do care deeply about the end users of Rust, we are limited in the time and energy we posses to keep things working for older and / or more niche setups, unfortunately.

That being said, I definitely agree that it would be in everyone's best interest to move away from the use of the `disabled` attribute on `link` elements here. I will take a look tomorrow and see if it's feasible to replace it with something better.

In particular, it appears that [the mdbook project](https://github.com/rust-lang/mdBook) uses [StyleSheet.disabled](https://developer.mozilla.org/en-US/docs/Web/API/StyleSheet/disabled) (as seen [here](https://github.com/rust-lang/mdBook/blob/a884c2574e5729a8c0e25e3c5c4302edfba11485/src/theme/book.js#L307-L326)), and that method is not deprecated and appears to have much better browser support.

Using that instead could perhaps improve the situation here for all parties concerned.

**Comment by Cldfire** [comment]
Opened #75063 which will fix this problem for you @ensc :smile:
