### ISSUE TITLE
Build script not using the same target features as the actual binary

### ISSUE THREAD

**Issue by fabianvdW** [rust-lang/rust#75018]
Not sure if this is an actual issue with Rust, it might be cargo's fault.
When I try to cross-compile my binary from Windows to the Linux-musl target the build script does not use bmi2, whereas the binary uses bmi2.
I tried this code:
`src/build.rs`
```rust
use std::fs::File;
use std::io::Write;
use std::path::Path;
pub fn main(){
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let mut file = File::create(Path::new(&out_dir).join("test.rs")).unwrap();
    #[cfg(all(target_arch = "x86_64", target_feature = "bmi2"))]
    {write!(file, "pub const BMI2: bool = true;").unwrap();}
    #[cfg(not(all(target_arch = "x86_64", target_feature = "bmi2")))]
    {write!(file, "pub const BMI2: bool = false;").unwrap();}
}
```
`src/main.rs`
```rust
include!(concat!(env!("OUT_DIR"), "/test.rs"));
fn main() {
    println!("Build bmi2: {}", BMI2);
    #[cfg(all(target_arch = "x86_64", target_feature = "bmi2"))]
    {println!("Actual bmi2: true")}
    #[cfg(not(all(target_arch = "x86_64", target_feature = "bmi2")))]
    {println!("Actual bmi2: false")}
}
```

I expected to see this happen: If no `RUSTFLAGS` specified, output should be false, false. If compilation with bmi2 target-feature enabled, output should be true, true.

Instead, this happened after compilation with
`cargo rustc --target x86_64-unknown-linux-musl -- -C target-cpu=native`
Output in my VirtualBox:
```
fabian@fabian-VirtualBox:~/Schreibtisch$ '/home/fabian/Schreibtisch/Test' 
Build bmi2: false
Actual bmi2: true
```
Issue does not occur with normal target.
### Meta

`rustc --version --verbose`:
```
rustc 1.47.0-nightly (6c8927b0c 2020-07-26)
binary: rustc
commit-hash: 6c8927b0cf80ceee19386026cf9d7fd4fd9d486f
commit-date: 2020-07-26
host: x86_64-pc-windows-msvc
release: 1.47.0-nightly
LLVM version: 10.0
```

**Comment by jonas-schievink** [comment]
The build script is built for and run on the host, so its `target_feature` actually indicates what the build machine supports. `-Ctarget-cpu` will only affect code that is built for the target machine, not the host. Inside the build script, you can use the `CARGO_CFG_x` environment variables that Cargo sets.

**Comment by fabianvdW** [comment]
> The build script is built for and run on the host, so its `target_feature` actually indicates what the build machine supports. `-Ctarget-cpu` will only affect code that is built for the target machine, not the host. Inside the build script, you can use the `CARGO_CFG_x` environment variables that Cargo sets.
`CARGO_CFG_TARGET_FEATURE` does not contain "bmi2" when I try with `target x86_64-unknown-linux-musl`, but it does contain it for normal host target.

**Comment by jonas-schievink** [comment]
That might be a Cargo bug, not sure

**Comment by fabianvdW** [comment]
> That might be a Cargo bug, not sure

Is the correct course of action now for me to open an issue on the cargo repository?

**Comment by jonas-schievink** [comment]
Either that or ask about this on the forum (or on Zulip)

**Comment by fabianvdW** [comment]
For future reference: Reading the env variable was the correct way to go, just make sure to `cargo clean` before ;)
