### ISSUE TITLE
Beginning-of-line detection in pretty-printer isn't reliable

### ISSUE THREAD

**Issue by marijnh** [rust-lang/rust#751]
It only recognizes 'hard' line breaks. Spaces might also cause lines to be broken. This program ends up with an extra blank line above the comment because of this:

```rust
fn main() {
    let x = Foo {x: 10, y: 10000000000,
             // This a comment
             z: 45000000000000000,
             q: 2444444444444444};
}

```

**Comment by brson** [comment]
Nobody is ever going to fix the current pretty-printer. Closing.
