### ISSUE TITLE
Generate intra-doc links for crates in scope

### ISSUE THREAD

**Issue by RDambrosio016** [rust-lang/rust#75128]
Currently its not possible to easily link to a crate which is in scope in rustdoc. Something such as
```
/// See this nice crate: [`cratey`](cratey)`
```
would be nice. It seems rustdoc explicitly does not do this currently. See:
https://github.com/rust-lang/rust/blob/master/src/librustdoc/passes/collect_intra_doc_links.rs#L493

**Comment by jyn514** [comment]
@RDambrosio016 I can't replicate.

```
$ cat src/lib.rs 
/// Link to [hexponent]
pub fn f() {
}
$ tail Cargo.toml -n2
[dependencies]
hexponent = "0.3"
```
![image](https://user-images.githubusercontent.com/23638587/89245261-71f7bc00-d5d6-11ea-9bb8-8126868e2bed.png)

**Comment by RDambrosio016** [comment]
Ah my bad, i did not actually verify that my crate in fact depends on it. And it does not at second glance, that was my fault, i will close this as resolved 🙂
