### ISSUE TITLE
Program crashes with #[track_caller] applied to main()

### ISSUE THREAD

**Issue by flowbish** [rust-lang/rust#75125]
### Code

```Rust
#[track_caller]
fn main() {
    panic!("{}: oh no", std::panic::Location::caller());
}
```

### Meta

Crash occurs in both 1.46.0 beta and in current nightly.

`rustc --version --verbose`:
```
rustc 1.46.0-beta.2 (6f959902b 2020-07-23)
binary: rustc
commit-hash: 6f959902b3103c49ca981fbc01871589c3498489
commit-date: 2020-07-23
host: x86_64-unknown-linux-gnu
release: 1.46.0-beta.2
LLVM version: 10.0
```

```
rustc 1.47.0-nightly (81e754c35 2020-08-02)
binary: rustc
commit-hash: 81e754c359c471f91263813c46c67955071716a7
commit-date: 2020-08-02
host: x86_64-unknown-linux-gnu
release: 1.47.0-nightly
LLVM version: 10.0

```

### Error output

```
memory allocation of 94396265198519 bytes failed
```

**Comment by flowbish** [comment]
I made the false assumption that this was rustc crashing, but it's actually the binary that crashes upon running it.

**Comment by Mark-Simulacrum** [comment]
Cc @anp 

We probably just want to ban track caller on main (and maybe any lang item function?)

**Comment by lcnr** [comment]
Same with `#[naked]`:
```rust
#![feature(naked_functions)]

#[naked]
fn main() {
    println!("hey");
}
```

**Comment by JohnTitor** [comment]
Assigning `P-high` as [discussed as part of the Prioritization Working Group procedure](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/I-prioritize.20.2375125.20Program.20crashes.20with.20.23.5Btrack_caller.5D.20ap.E2.80.A6) and removing `I-prioritize`.
