### ISSUE TITLE
Document type-based search

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#75197]
I find this really useful, but it's very difficult to find information on it anywhere.

Example of type-based search: https://users.rust-lang.org/t/a-year-in-rust-and-i-still-cant-read-the-docs/46872/20

**Comment by jyn514** [comment]
This would be a good first issue. The documentation should go somewhere in https://github.com/rust-lang/rust/tree/master/src/doc/rustdoc/src.

**Comment by ThePuzzlemaker** [comment]
I'll look into any other obscure search features like this, and be sure to document them. (I'll be sure to document at least this one)

**Comment by ThePuzzlemaker** [comment]
![image](https://user-images.githubusercontent.com/12666617/89720862-776d5180-d99c-11ea-8f22-e7d27658d555.png)
@jyn514 I've actually found that this feature is documented in the "Search Tricks" section of the help dialog.

**Comment by ThePuzzlemaker** [comment]
And I don't find that it would really be helpful to document this in the rustdoc book as it's more of an emitted feature rather than a rustdoc feature itself. If it wasn't added to the search tricks already, I would add it there.
@rustbot release-assignment

**Comment by ThePuzzlemaker** [comment]
I feel that the help dialog is already easy to find enough, though the `for more options...` might be disambiguated to `for help...` or something like that.
![image](https://user-images.githubusercontent.com/12666617/89720912-04b0a600-d99d-11ea-8bac-9956bea5864f.png)

**Comment by jyn514** [comment]
Hmm that does seem simple enough but I never found it after a year in rust ... cc @rust-lang/rustdoc, does anyone have ideas how to make this more discoverable?

**Comment by GuillaumeGomez** [comment]
It's true that it's hard to find it, maybe we should add a `?` button that would also show the popup alongside the search input?

**Comment by ThePuzzlemaker** [comment]
That makes sense, as the settings and theme dropdown are triggered by buttons rather than keyboard shortcuts.

**Comment by GuillaumeGomez** [comment]
Ok, I'll send a PR tomorrow to add the button then.

**Comment by jyn514** [comment]
Closing since https://github.com/rust-lang/rust/pull/75366 is merged, hopefully that will make this easier to find.
