### ISSUE TITLE
Tracking Issue for const `core::str::from_utf8_unchecked`

### ISSUE THREAD

**Issue by rodrimati1992** [rust-lang/rust#75196]
This is a tracking issue for `const fn core::str::from_utf8_unchecked`, made const in https://github.com/rust-lang/rust/pull/75157 .
The feature gate for the issue is `#![feature(const_str_from_utf8_unchecked)]`.

### Steps
- [x] Merge the implementation PR https://github.com/rust-lang/rust/pull/75157 
- [x] Final Comment Period (FCP)
- [ ] Stabilization PR (#86213)

**Comment by RalfJung** [comment]
This is an unsafe operation and thus likely also blocked on https://github.com/rust-lang/const-eval/issues/14.
Cc @rust-lang/wg-const-eval

**Comment by m-ou-se** [comment]
Now that rust-lang/rfcs#3016 is merged:

@rfcbot merge

cc @rust-lang/wg-const-eval

**Comment by jhpratt** [comment]
Stabilization PR is already up: #86213
