### ISSUE TITLE
Possible CString eq bug

### ISSUE THREAD

**Issue by mrclean71774** [rust-lang/rust#75216]
Not sure if this is the intended behavior or not.  It definitely is not the behavior I was
expecting.  While they are technically different, I assumed that a type made for foreign
function interface would stop at the first nil.

Sorry for wasting your time if this is not a bug and thank you all for your hard work on
an excellent language.

```rust
use std::ffi::CString;

fn main() {
    let cs1 = CString::new("cstring\0");
    let cs2 = CString::new("cstring\0\0");
    assert_eq!(cs1, cs2);
}

```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=af3b51f11c433f69ee8a9c05e54ee01f))

Errors:

```
   Compiling playground v0.0.1 (/playground)
    Finished dev [unoptimized + debuginfo] target(s) in 0.79s
     Running `target/debug/playground`
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `Err(NulError(7, [99, 115, 116, 114, 105, 110, 103, 0]))`,
 right: `Err(NulError(7, [99, 115, 116, 114, 105, 110, 103, 0, 0]))`', src/main.rs:6:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

```

**Comment by jonas-schievink** [comment]
The docs say:

> This function will consume the provided data and use the underlying bytes to construct a new string, ensuring that there is a trailing 0 byte. This trailing 0 byte will be appended by this function; the provided data should not contain any 0 bytes in it.

So this seems to work as expected

**Comment by mrclean71774** [comment]
Alright then I wasn't sure if the docs meant null bytes 'in' as in ['s', 't', '\0', 'n', 'g'] or at the end
as well.  The offending string came from Vulkan, so I blame my GPU.
