### ISSUE TITLE
Compiles error when call the closure that need type inference with `&mut *b` twice

### ISSUE THREAD

**Issue by Hyuuko** [rust-lang/rust#75242]
I tried this code:

```rust
fn main() {}

fn f1() {
    let mut a = 1;
    let b = &mut a;
    let foo = |i: &mut i32| {};
    foo(b);
    foo(b);
}

fn f2() {
    let mut a = 1;
    let b = &mut a;
    let foo = |i| {};
    foo(&mut *b);
    foo(&mut *b); // error! But I think it should be compiled successfully
}
```

I expected to see this happen:
```
    Finished dev [unoptimized + debuginfo] target(s) in 0.69s
     Running `target\debug\nobug.exe`
```

I modify it to:
```rust
fn main() {}

fn f1() {
    let mut a = 1;
    let b = &mut a;
    let foo = |i: &mut i32| {};
    foo(b);
}

fn f2() {
    let mut a = 1;
    let b = &mut a;
    let foo = |i| {};
    foo(&mut *b);
}
```
Then I type `rustc --emit=mir .\src\main.rs` to generates `main.mir` and found that mir of `f1` and `f2` are exactly the same. The `foo(b);` in `f1` and `foo(&mut *b);` in `f2` both pass the reborrow of `b` into the function. However, the previous code failed to compile.😢

Instead, this happened:
```
error[E0499]: cannot borrow `*b` as mutable more than once at a time
  --> src\main.rs:16:9
   |
15 |     foo(&mut *b);
   |         ------- first mutable borrow occurs here
16 |     foo(&mut *b);
   |     --- ^^^^^^^ second mutable borrow occurs here
   |     |
   |     first borrow later used by call

error: aborting due to previous error; 2 warnings emitted

For more information about this error, try `rustc --explain E0499`.
error: could not compile `learn`.
```

### Meta

`rustc --version --verbose`:
```
rustc 1.45.2 (d3fb005a3 2020-07-31)
binary: rustc
commit-hash: d3fb005a39e62501b8b0b356166e515ae24e2e54
commit-date: 2020-07-31
host: x86_64-pc-windows-msvc
release: 1.45.2
LLVM version: 10.0
```

```
rustc 1.47.0-nightly (6c8927b0c 2020-07-26)
binary: rustc
commit-hash: 6c8927b0cf80ceee19386026cf9d7fd4fd9d486f
commit-date: 2020-07-26
host: x86_64-pc-windows-msvc
release: 1.47.0-nightly
LLVM version: 10.0
```

**Comment by qiujiangkun** [comment]
I tried this code and it works
```rust
    let mut a = 1;
    let b = &mut a;
    {
        let foo = |i| {};
        foo(&mut *b);
    }
    {
        let foo = |i| {};
        foo(&mut *b);
    }
```
- The two code being the same assembly does not mean they have the same semantic meaning.
- It's really a strange bug.

**Comment by nbdd0121** [comment]
This is expected behaviour. `i` is inferred to have the same type as the `&mut *b`, rather than `&mut i32`. Therefore the type of foo becomes `fn(&'a mut i32)` for a concrete `'a`, rather than `for<'a> fn(&'a mut i32)`. Because both calls of `foo` uses the same `'a`, the two borrows must last for the same duration, and therefore is not allowed because you cannot two mutable borrows for the same duration!

Essentially, the loss of HRTB causes the borrowck failure.

**Comment by Hyuuko** [comment]
Thanks your answer! I fully understand it now.

**Comment by TinusgragLin** [comment]
> 

Wait, but adding the type notation to `i` makes the snippet compile, this change makes `foo` become of type `for<'a> fn(&'a mut i32)` ? That seems really weird to me.

**Comment by TinusgragLin** [comment]
> This is expected behaviour. `i` is inferred to have the same type as the `&mut *b`, rather than `&mut i32`. Therefore the type of foo becomes `fn(&'a mut i32)` for a concrete `'a`, rather than `for<'a> fn(&'a mut i32)`. Because both calls of `foo` uses the same `'a`, the two borrows must last for the same duration, and therefore is not allowed because you cannot two mutable borrows for the same duration!
> 
> Essentially, the loss of HRTB causes the borrowck failure.

Wait, but adding the type notation to `i` makes the snippet compile, this change makes `foo` somehow become of type `for<'a> fn(&'a mut i32)` ? That seems really weird to me.
