### ISSUE TITLE
Rename "important traits" to something better

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#75245]
A lot of the feedback on https://internals.rust-lang.org/t/feedback-on-important-traits-rustdoc-feature/12752  had better suggestions for the "important traits" feature.

Some options were:

 - Featured traits
 - Key traits
 - Notable traits

My personal preference is for "notable traits" because "important" is a much stronger value judgement whereas "notable" basically means "we thought you should know this" which is exactly what the feature does.

Thoughts? @rust-lang/rustdoc 

We should pick something and rename.

**Comment by GuillaumeGomez** [comment]
I don't have strong feelings here but I think "Notable traits" is the best proposition out of the three.

**Comment by jyn514** [comment]
I agree 👍 , "featured traits" might be confused with cargo features and "key traits" has different connotations in my mind.

**Comment by camelid** [comment]
I'd be interested in doing this.

@rustbot claim
