### ISSUE TITLE
--pretty=expanded does not include macro definitions

### ISSUE THREAD

**Issue by jgarvin** [rust-lang/rust#75241]
macro_rules macro definitions are not included in the pretty output, they seem to just disappear. I suspect this has something to do with macro_rules technically looking like a macro invocation despite being defined in the compiler, so the "expansion" of a macro_rules definition is to disappear. As you might imagine, macros that generate macros can be one of the more painful things to debug, so the No. 1 macro debugging tool not working in this scenario makes things extra hard :p

**Comment by petrochenkov** [comment]
Could you give a reproduction?
Macro definitions *are* printed, I've just checked on a simple example.

**Comment by jgarvin** [comment]
In creating a test case for this I think I discovered this bug is in cargo expand, not rustc. I filed an issue with them [here](https://github.com/dtolnay/cargo-expand/issues/90). I assumed it had to be rustc because it is allegedly just an alias for a rustc command, but it turns out it has different behavior.
