### ISSUE TITLE
Tracking Issue for const MaybeUninit::as(_mut)_ptr (feature: const_maybe_uninit_as_ptr)

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#75251]
This is a tracking issue for const `MaybeUninit::as(_mut)_ptr`.
The feature gate for the issue is `#![feature(const_maybe_uninit_as_ptr)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also uses as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Implement
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [x] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])
  - https://github.com/rust-lang/rust/pull/90896
  - #130542

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Implementation history

* Added in https://github.com/rust-lang/rust/pull/75250

**Comment by pnkfelix** [comment]
(@m-ou-se pointed out that this is a libs-api team issue, not a libs implementation issue.)

**Comment by m-ou-se** [comment]
@rfcbot merge

**Comment by RalfJung** [comment]
Cc @rust-lang/wg-const-eval but this should be uncontroversial

**Comment by fee1-dead** [comment]
No concerns with this.

**Comment by dtolnay** [comment]
I'm marking @yaahc's box because she has stepped down from T-libs-api after the point that this feature got proposed for FCP.

**Comment by Nilstrieb** [comment]
Status: `as_ptr` has been stabilized. `as_mut_ptr` is blocked on #57349

**Comment by RalfJung** [comment]
@rust-lang/libs-api with https://github.com/rust-lang/rust/issues/57349 no longer being a blocker, are you fine with `MaybeUninit::as_mut_ptr` being const-stabilized under the above FCP?

**Comment by Amanieu** [comment]
We discussed this in the libs-api meeting and we're happy to keep the existing FCP for `as_mut_ptr`.

**Comment by RalfJung** [comment]
This is closed by https://github.com/rust-lang/rust/pull/130542 :)
