### ISSUE TITLE
Use revisions to test `min_const_generics`

### ISSUE THREAD

**Issue by lcnr** [rust-lang/rust#75279]
cc #74878

#74877 implemented `feature(min_const_generics)` which is split off from `feature(const_generics)`.

As these two features have some meaningful differences it is desirable to run try and run all const generics tests with both features.

This can be done using`revisions`. Some tests were already updated in #74877: https://github.com/rust-lang/rust/blob/f9c2177ddc605f9c75ca1a3e6ddb33835b8a178d/src/test/ui/const-generics/issues/issue-56445.rs#L1-L13

If you want to work on this feel free to ask for help here or on zulip.

**Comment by Amjad50** [comment]
I'll work on part of it

**Comment by Amjad50** [comment]
sorry, missed something up

**Comment by Amjad50** [comment]
Are all the tests done? Or is this being closed because of using the workd"fixes" in #76514 ?

**Comment by lcnr** [comment]
because of the keyword fixes. Don't think that all tests have been migrated yet

**Comment by hameerabbasi** [comment]
I migrated all of the relevant tests I could find. I could go back and look.

There are a few that simply didn't need revisions. Examples include things that test for the features being unstable and that `const_generics` and `min_const_generics` cannot be used together.

**Comment by hameerabbasi** [comment]
I missed `type_dependent` and `const_evaluatable_checked`. I apologize for the confusion. PR incoming!
