### ISSUE TITLE
Tracking Issue for {HashMap,BTreeMap}::into_{keys,values}

### ISSUE THREAD

**Issue by canova** [rust-lang/rust#75294]
Feature gate: `#![feature(map_into_keys_values)]`

This is a tracking issue for `{HashMap,BTreeMap}::into_{keys,values}`.

### Public API

```rust
// alloc::collections::btree_map

impl<K, V> BTreeMap<K, V> {
    pub fn into_keys(self) -> IntoKeys<K, V>;
    pub fn into_values(self) -> IntoValues<K, V>;
}

pub struct IntoKeys<K, V>;
pub struct IntoValues<K, V>;

impl<K, V> Iterator for IntoKeys<K, V> { type Item = K; }
impl<K, V> DoubleEndedIterator for IntoKeys<K, V> {}
impl<K, V> ExactSizeIterator for IntoKeys<K, V> {}
impl<K, V> FusedIterator for IntoKeys<K, V> {}
impl<K: Debug, V> Debug for IntoKeys<K, V> {}

impl<K, V> Iterator for IntoValues<K, V> { type Item = V; }
impl<K, V> DoubleEndedIterator for IntoValues<K, V> {}
impl<K, V> ExactSizeIterator for IntoValues<K, V> {}
impl<K, V> FusedIterator for IntoValues<K, V> {}
impl<K, V: Debug> Debug for IntoValues<K, V> {}

// alloc::collections::hash_map

impl<K: Eq + Hash, V, S: BuildHasher> HashMap<K, V, S> {
    pub fn into_keys(self) -> IntoKeys<K, V>;
    pub fn into_values(self) -> IntoValues<K, V>;
}

pub struct IntoKeys<K, V>;
pub struct IntoValues<K, V>;

impl<K, V> Iterator for IntoKeys<K, V> { type Item = K; }
impl<K, V> ExactSizeIterator for IntoKeys<K, V> {}
impl<K, V> FusedIterator for IntoKeys<K, V> {}
impl<K: Debug, V> Debug for IntoKeys<K, V> {}

impl<K, V> Iterator for IntoValues<K, V> { type Item = V; }
impl<K, V> ExactSizeIterator for IntoValues<K, V> {}
impl<K, V> FusedIterator for IntoValues<K, V> {}
impl<K, V: Debug> Debug for IntoValues<K, V> {}
```

### Steps / History

- Requested in #55214.
- [x] Implementation: #75163
- [ ] Final commenting period (FCP)
- [ ] Stabilization PR: #84328

### Unresolved Questions

- None yet.

**Comment by GreenBeard** [comment]
This change will be much appreciated. Could we please also have an into_entries function which returns a tuple of the key, and value will also be added.

**Comment by jplatte** [comment]
@GreenBeard that's what the `into_iter` methods do.

**Comment by GreenBeard** [comment]
@jplatte For some reason the documentation ( https://doc.rust-lang.org/std/collections/struct.BTreeMap.html ) has that as under "Show hidden undocumented items". Does that mean it was intentionally hidden, or is it an oversight/automatic? I didn't find it when using ctrl+f because of that.

**Comment by jplatte** [comment]
@GreenBeard Right, some trait methods are hidden like that. I would generally recommend using the search built into the page rather than the browser's search for rustdoc pages. The method is easy to find if you search for `BTreeMap::into_iter`. But that's off-topic for this tracking issue.

**Comment by m-ou-se** [comment]
@rfcbot merge
