### ISSUE TITLE
Provide auto-fix suggestion for triple equals

### ISSUE THREAD

**Issue by clarfon** [rust-lang/rust#75312]
Been working in JavaScript a lot lately and find myself accidentally typing this a lot. It would be nice to automatically detect this and offer a proper fix. Lots of languages use this syntax in addition to JavaScript so it seems like a reasonable error to make.

Playground example below.

```rust
#![feature(test)]
use std::hint::black_box;
fn main() {
    if 1 === black_box(1) {
        println!("yup!");
    } else if 2 !== black_box(2) {
        println!("nope!");
    }
}
```

([Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=1dd65e329efa94cdb700c6b648f8ebfb))

Errors:

```
   Compiling playground v0.0.1 (/playground)
error: expected expression, found `=`
 --> src/main.rs:4:12
  |
4 |     if 1 === black_box(1) {
  |            ^ expected expression

warning: unused import: `std::hint::black_box`
 --> src/main.rs:2:5
  |
2 | use std::hint::black_box;
  |     ^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

error: aborting due to previous error; 1 warning emitted

error: could not compile `playground`.

To learn more, run the command again with --verbose.

```

**Comment by lzutao** [comment]
I think the current error message is clear enough. 
Also I don't think providing auto-fix suggestion is easy, because the error happened when parsing AST.

**Comment by estebank** [comment]
@lzutao https://github.com/rust-lang/rust/pull/75321 😉

**Comment by lzutao** [comment]
Nice. But I still think the current error message is fine as is.

**Comment by estebank** [comment]
@lzutao don't disagree, but handling it was relatively easy because there's no case where `== =` would be valid.
