### ISSUE TITLE
In `const fn` in a macro call, raw ptr deref does not work even inside `unsafe`

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#75340]
The following code should build, but for some reason it does not:
```rust
#![feature(const_raw_ptr_deref)]
#![feature(raw_ref_macros)]

use std::ptr;

const fn test_fn(x: *const i32) {
    let x2 = unsafe { ptr::raw_const!(*x) };
}
```
Removing the `const` or adding a `const_fn` feature gate makes it build.

Cc @oli-obk @petrochenkov

**Comment by RalfJung** [comment]
Ah, adding the `const_fn` also helps... is that the expected behavior @oli-obk?

**Comment by oli-obk** [comment]
Yes and no. The MIR is `&raw const (*_1)`, where `_1` is `x`. We prevent the `deref` on the raw pointer, even if that's not an actual read. Basically it's a combination of https://github.com/rust-lang/rust/blob/4a86573c6b5c8b1ba179487f06e5f69a6f37e895/src/librustc_mir/transform/check_unsafety.rs#L232 and https://github.com/rust-lang/rust/blob/4a86573c6b5c8b1ba179487f06e5f69a6f37e895/src/librustc_mir/transform/check_unsafety.rs#L355

So... I guess we need to change https://github.com/rust-lang/rust/blob/4a86573c6b5c8b1ba179487f06e5f69a6f37e895/src/librustc_mir/transform/check_unsafety.rs#L231 to `GeneralAndConstFn`

**Comment by mlodato517** [comment]
Has this ticket been picked up by anyone? If not, I'd be happy to hop in (especially if it's as easy as changing that one parameter!)

**Comment by 5M1Sec** [comment]
> Has this ticket been picked up by anyone? If not, I'd be happy to hop in (especially if it's as easy as changing that one argument!)
Hello, can I take this issue? This is my first time trying to make a PR. Thank you.

**Comment by mlodato517** [comment]
That's okay with me (unless someone got here before both of us and took it 😉)

**Comment by 5M1Sec** [comment]
This is the error after the commit. I am also learning the code as I am investigating it.

```
---- [ui] ui/consts/min_const_fn/min_const_fn_unsafe_bad.rs stdout ----
1551
diff of stderr:
1552

1553
34	   = note: see issue #57563 <https://github.com/rust-lang/rust/issues/57563> for more information
1554
35	   = help: add `#![feature(const_fn)]` to the crate attributes to enable
1555
36	
1556
-	error[E0133]: dereference of raw pointer is unsafe and requires unsafe function or block
1557
-	  --> $DIR/min_const_fn_unsafe_bad.rs:1:77
1558
-	   |
1559
-	LL | const fn bad_const_fn_deref_raw(x: *mut usize) -> &'static usize { unsafe { &*x } }
1560
-	   |                                                                             ^^^ dereference of raw pointer
1561
-	   |
1562
-	   = note: raw pointers may be NULL, dangling or unaligned; they can violate aliasing rules and cause data races: all of these are undefined behavior
1563
+	error: aborting due to 4 previous errors
1564
44	
1565
-	error: aborting due to 5 previous errors
1566
-	
1567
-	Some errors have detailed explanations: E0133, E0658, E0723.
1568
-	For more information about an error, try `rustc --explain E0133`.
1569
+	Some errors have detailed explanations: E0658, E0723.
1570
+	For more information about an error, try `rustc --explain E0658`.
1571
49	
```

**Comment by oli-obk** [comment]
From the error I'd guess that setting the `const_fn` feature gate should make it work now. We can work on getting this ready for `min_const_fn` in a separate PR

**Comment by RalfJung** [comment]
> From the error I'd guess that setting the `const_fn` feature gate should make it work now. We can work on getting this ready for `min_const_fn` in a separate PR

`const_fn` already makes it work on master. But my expectation was that when enabling `const_raw_ptr_deref`, that should work even without `const_fn`. Not sure if that is the intention though.

**Comment by oli-obk** [comment]
Ah, now I see, https://github.com/rust-lang/rust/blob/master/src/test/ui/consts/min_const_fn/min_const_fn_unsafe_bad.rs doesn't actually have any of the other feature gates, thus mentioning `const_fn`. I think everything is correct now, you just need to `./x.py test --stage 1 --bless src/test/ui --test-args min_const_fn` to update the `.stderr` files.

**Comment by RalfJung** [comment]
(I think that comment was meant for the PR, not this issue.)

**Comment by RalfJung** [comment]
@5M1Sec  please post PR-specific questions in the PR, not the issue. That just mixes up the discussion about a particular fix and the discussion about the problem in general -- very confusing. Instead, leave a message here to point out that a PR exists, or ping people on the PR.

I hid your comment here to avoid that confusion.

**Comment by RalfJung** [comment]
With https://github.com/rust-lang/rust/pull/75578 having landed, is there anything left to do here?

**Comment by oli-obk** [comment]
depends on whether we want this to work without the `const_raw_ptr_deref` feature gate. It's not actually a deref, it's a raw pointer reborrow of sorts.

**Comment by RalfJung** [comment]
For me, "deref" is the `*` operator. So the gate makes sense for that.

Closing then.
