### ISSUE TITLE
Is it possible to implement **foldmap** function for *Iterator*? 

### ISSUE THREAD

**Issue by zhibo501** [rust-lang/rust#75367]
Hi guys,

Is it possible to implement **foldmap** function for *Iterator*? 

Like this:
```rust
fn funny(v: Vec<i32>) -> Vec<i32> {
	v.iter()
		.foldmap(0, |acc, x| acc + x)
		.collect()
}
```

which is equals to :
```
fn funny(v: Vec<i32>) -> Vec<i32> {
        let mut total = 0;
	v.iter()
		.map(|x| {total = total + x; total})
		.collect()
}
```

Thanks.

**Comment by jonas-schievink** [comment]
Hi! This issue tracker is mainly meant for bug reports and concrete, small feature requests. Questions like this are better asked in the user forum at https://users.rust-lang.org/ or on [one of the chat platforms](https://www.rust-lang.org/community) used by the Rust community.

**Comment by zhibo501** [comment]
@jonas-schievink 

Sorry, I didn't make it clear. I want to make a small requirement for iteration to support foldmap.

In this way, **foldmap** can be composed conveniently than only **map**.

```rust
fn funny(v: Vec<i32>) -> Vec<i32> {
	v.iter()
		.foldmap(0, |acc, x| acc + x)
                .foldmap(1, |acc, x| acc * x)
		.collect()
}
```

**Comment by zhibo501** [comment]
@jonas-schievink 

Sorry, I didn't make it clear. I want to make a small requirement for iteration to support foldmap.

In this way, **foldmap** can be composed conveniently than only **map**.

```rust
fn funny(v: Vec<i32>) -> Vec<i32> {
	v.iter()
		.foldmap(0, |acc, x| acc + x)
                .foldmap(1, |acc, x| acc * x)
		.collect()
}
```

**Comment by zhibo501** [comment]
@jonas-schievink 

Sorry, I didn't make it clear. I want to make a small requirement for iteration to support foldmap.

In this way, **foldmap** can be composed conveniently than only **map**.

```rust
fn funny(v: Vec<i32>) -> Vec<i32> {
	v.iter()
		.foldmap(0, |acc, x| acc + x)
                .foldmap(1, |acc, x| acc * x)
		.collect()
}
```

**Comment by zhibo501** [comment]
@jonas-schievink 

Sorry, I didn't make it clear. I want to make a small requirement for iteration to support foldmap.

In this way, **foldmap** can be composed conveniently than only **map**.

```rust
fn funny(v: Vec<i32>) -> Vec<i32> {
	v.iter()
		.foldmap(0, |acc, x| acc + x)
                .foldmap(1, |acc, x| acc * x)
		.collect()
}
```

**Comment by zhibo501** [comment]
@jonas-schievink 

Sorry, I didn't make it clear. I want to make a small requirement for iteration to support foldmap.

In this way, **foldmap** can be composed conveniently than only **map**.

```rust
fn funny(v: Vec<i32>) -> Vec<i32> {
	v.iter()
		.foldmap(0, |acc, x| acc + x)
                .foldmap(1, |acc, x| acc * x)
		.collect()
}
```

**Comment by zhibo501** [comment]
@jonas-schievink 

Sorry, I didn't make it clear. I want to make a small requirement for iteration to support foldmap.

In this way, **foldmap** can be composed conveniently than only **map**.

```rust
fn funny(v: Vec<i32>) -> Vec<i32> {
	v.iter()
		.foldmap(0, |acc, x| acc + x)
                .foldmap(1, |acc, x| acc * x)
		.collect()
}
```

**Comment by zhibo501** [comment]
@jonas-schievink 

Sorry, I didn't make it clear. I want to make a small requirement for iteration to support foldmap.

In this way, **foldmap** can be composed conveniently than only **map**.

```rust
fn funny(v: Vec<i32>) -> Vec<i32> {
	v.iter()
		.foldmap(0, |acc, x| acc + x)
                .foldmap(1, |acc, x| acc * x)
		.collect()
}
```

**Comment by zhibo501** [comment]
@jonas-schievink 

Sorry, I didn't make it clear. I want to make a small requirement for iteration to support foldmap.

In this way, **foldmap** can be composed conveniently than only **map**.

```rust
fn funny(v: Vec<i32>) -> Vec<i32> {
	v.iter()
		.foldmap(0, |acc, x| acc + x)
                .foldmap(1, |acc, x| acc * x)
		.collect()
}
```

**Comment by zhibo501** [comment]
@jonas-schievink 

Sorry, I didn't make it clear. I want to make a small requirement for iteration to support foldmap.

In this way, **foldmap** can be composed conveniently than only **map**.

```rust
fn funny(v: Vec<i32>) -> Vec<i32> {
	v.iter()
		.foldmap(0, |acc, x| acc + x)
                .foldmap(1, |acc, x| acc * x)
		.collect()
}
```

**Comment by zhibo501** [comment]
@jonas-schievink 

Sorry, I didn't make it clear. I want to make a small requirement for iteration to support foldmap.

In this way, **foldmap** can be composed conveniently than only **map**.

```rust
fn funny(v: Vec<i32>) -> Vec<i32> {
	v.iter()
		.foldmap(0, |acc, x| acc + x)
                .foldmap(1, |acc, x| acc * x)
		.collect()
}
```

**Comment by zhibo501** [comment]
@jonas-schievink 

Sorry, I didn't make it clear. I want to make a small requirement for iteration to support foldmap.

In this way, **foldmap** can be composed conveniently than only **map**.

```rust
fn funny(v: Vec<i32>) -> Vec<i32> {
	v.iter()
		.foldmap(0, |acc, x| acc + x)
                .foldmap(1, |acc, x| acc * x)
		.collect()
}
```

**Comment by zhibo501** [comment]
@jonas-schievink 

Sorry, I didn't make it clear. I want to make a small requirement for iteration to support foldmap.

In this way, **foldmap** can be composed conveniently than only **map**.

```rust
fn funny(v: Vec<i32>) -> Vec<i32> {
	v.iter()
		.foldmap(0, |acc, x| acc + x)
                .foldmap(1, |acc, x| acc * x)
		.collect()
}
```

**Comment by zhibo501** [comment]
@jonas-schievink 

Sorry, I didn't make it clear. I want to make a small requirement for iteration to support foldmap.

In this way, **foldmap** can be composed conveniently than only **map**.

```rust
fn funny(v: Vec<i32>) -> Vec<i32> {
	v.iter()
		.foldmap(0, |acc, x| acc + x)
                .foldmap(1, |acc, x| acc * x)
		.collect()
}
```

**Comment by zhibo501** [comment]
@jonas-schievink 

Sorry, I didn't make it clear. I want to make a small requirement for iteration to support foldmap.

In this way, **foldmap** can be composed conveniently than only **map**.

```rust
fn funny(v: Vec<i32>) -> Vec<i32> {
	v.iter()
		.foldmap(0, |acc, x| acc + x)
                .foldmap(1, |acc, x| acc * x)
		.collect()
}
```

**Comment by zhibo501** [comment]
@jonas-schievink 

Sorry, I didn't make it clear. I want to make a small requirement for iteration to support foldmap.

In this way, **foldmap** can be composed conveniently than only **map**.

```rust
fn funny(v: Vec<i32>) -> Vec<i32> {
	v.iter()
		.foldmap(0, |acc, x| acc + x)
                .foldmap(1, |acc, x| acc * x)
		.collect()
}
```

**Comment by zhibo501** [comment]
@jonas-schievink 

Sorry, I didn't make it clear. I want to make a small requirement for iteration to support foldmap.

In this way, **foldmap** can be composed conveniently than only **map**.

```rust
fn funny(v: Vec<i32>) -> Vec<i32> {
	v.iter()
		.foldmap(0, |acc, x| acc + x)
                .foldmap(1, |acc, x| acc * x)
		.collect()
}
```

**Comment by zhibo501** [comment]
@jonas-schievink 

Sorry, I didn't make it clear. I want to make a small requirement for iteration to support foldmap.

In this way, **foldmap** can be composed conveniently than only **map**.

```rust
fn funny(v: Vec<i32>) -> Vec<i32> {
	v.iter()
		.foldmap(0, |acc, x| acc + x)
                .foldmap(1, |acc, x| acc * x)
		.collect()
}
```

**Comment by zhibo501** [comment]
@jonas-schievink 

Sorry, I didn't make it clear. I want to make a small requirement for iteration to support foldmap.

In this way, **foldmap** can be composed conveniently than only **map**.

```rust
fn funny(v: Vec<i32>) -> Vec<i32> {
	v.iter()
		.foldmap(0, |acc, x| acc + x)
                .foldmap(1, |acc, x| acc * x)
		.collect()
}
```

**Comment by zhibo501** [comment]
@jonas-schievink 

Sorry, I didn't make it clear. I want to make a small requirement for iteration to support foldmap.

In this way, **foldmap** can be composed conveniently than only **map**.

```rust
fn funny(v: Vec<i32>) -> Vec<i32> {
	v.iter()
		.foldmap(0, |acc, x| acc + x)
                .foldmap(1, |acc, x| acc * x)
		.collect()
}
```

**Comment by zhibo501** [comment]
@jonas-schievink 

Sorry, I didn't make it clear. I want to make a small requirement for iteration to support foldmap.

In this way, **foldmap** can be composed conveniently than only **map**.

```rust
fn funny(v: Vec<i32>) -> Vec<i32> {
	v.iter()
		.foldmap(0, |acc, x| acc + x)
                .foldmap(1, |acc, x| acc * x)
		.collect()
}
```

**Comment by zhibo501** [comment]
@jonas-schievink 

Sorry, I didn't make it clear. I want to make a small requirement for iteration to support foldmap.

In this way, **foldmap** can be composed conveniently than only **map**.

```rust
fn funny(v: Vec<i32>) -> Vec<i32> {
	v.iter()
		.foldmap(0, |acc, x| acc + x)
                .foldmap(1, |acc, x| acc * x)
		.collect()
}
```

**Comment by zhibo501** [comment]
@jonas-schievink 

Sorry, I didn't make it clear. I want to make a small requirement for iteration to support foldmap.

In this way, **foldmap** can be composed conveniently than only **map**.

```rust
fn funny(v: Vec<i32>) -> Vec<i32> {
	v.iter()
		.foldmap(0, |acc, x| acc + x)
                .foldmap(1, |acc, x| acc * x)
		.collect()
}
```

**Comment by zhibo501** [comment]
@jonas-schievink 

Sorry, I didn't make it clear. I want to make a small requirement for iteration to support foldmap.

In this way, **foldmap** can be composed conveniently than only **map**.

```rust
fn funny(v: Vec<i32>) -> Vec<i32> {
	v.iter()
		.foldmap(0, |acc, x| acc + x)
                .foldmap(1, |acc, x| acc * x)
		.collect()
}
```

**Comment by zhibo501** [comment]
@jonas-schievink 

Sorry, I didn't make it clear. I want to make a small requirement for iteration to support foldmap.

In this way, **foldmap** can be composed conveniently than only **map**.

```rust
fn funny(v: Vec<i32>) -> Vec<i32> {
	v.iter()
		.foldmap(0, |acc, x| acc + x)
                .foldmap(1, |acc, x| acc * x)
		.collect()
}
```

**Comment by zhibo501** [comment]
@jonas-schievink 

Sorry, I didn't make it clear. I want to make a small requirement for *Iteration* to support foldmap.

In this way, **foldmap** can be composed conveniently than **map**.

```rust
fn funny(v: Vec<i32>) -> Vec<i32> {
	v.iter()
		.foldmap(0, |acc, x| acc + x)
                .foldmap(1, |acc, x| acc * x)
		.collect()
}
```

**Comment by Lonami** [comment]
Is [`Iterator::fold`](https://doc.rust-lang.org/stable/std/iter/trait.Iterator.html#method.fold) not what is being proposed here?
