### ISSUE TITLE
Lint on cfg(token) if a feature "token" exists

### ISSUE THREAD

**Issue by joshtriplett** [rust-lang/rust#75375]
It's easy to make the mistake of writing `cfg(some_feature_name)` when you mean to write `cfg(feature = "some_feature_name")`. The compiler will silently ignore it and treat it as false.

I'd like to suggest a warn-by-default lint for `cfg(some_feature_name)` in the case where the compiler does not know any other meaning for `some_feature_name`, would otherwise ignore it, *and* there's a feature named `some_feature_name`. The warning could also suggest that the user *might* mean `cfg(feature = "some_feature_name")`.

**Comment by fmease** [comment]
Since we now have `--check-cfg` which is also used by Cargo by default, I think this is pretty much addressed. Any other new lint would just be redundant / duplicating efforts.

Of course, `--check-cfg` is *opt-in* if you don't use Cargo. However, judging from the snippet `cfg(feature = "some_feature_name")` I assume Cargo is implied? If so, this is more than fixed:

```rs
// src/main.rs
#[cfg(some_feature_name)] struct Type;
fn main() {}
```

```toml
[package]
name = "pkg"
version = "0.0.0"

[features]
some_feature_name = []
```

```
warning: unexpected `cfg` condition name: `some_feature_name`
 --> src/main.rs:1:7
  |
1 | #[cfg(some_feature_name)]
  |       ^^^^^^^^^^^^^^^^^ help: found config with similar value: `feature = "some_feature_name"`
  |
  = help: expected names are: `clippy`, `debug_assertions`, `doc`, `docsrs`, `doctest`, `feature`, `fmt_debug`, `miri`, `overflow_checks`, `panic`, `proc_macro`, `relocation_model`, `rustfmt`, `sanitize`, `sanitizer_cfi_generalize_pointers`, `sanitizer_cfi_normalize_integers`, `target_abi`, `target_arch`, `target_endian`, `target_env`, `target_family`, `target_feature`, `target_has_atomic`, `target_has_atomic_equal_alignment`, `target_has_atomic_load_store`, `target_os`, `target_pointer_width`, `target_thread_local`, `target_vendor`, `test`, `ub_checks`, `unix`, and `windows`
  = help: consider using a Cargo feature instead
  = help: or consider adding in `Cargo.toml` the `check-cfg` lint config for the lint:
           [lints.rust]
           unexpected_cfgs = { level = "warn", check-cfg = ['cfg(some_feature_name)'] }
  = help: or consider adding `println!("cargo::rustc-check-cfg=cfg(some_feature_name)");` to the top of the `build.rs`
  = note: see <https://doc.rust-lang.org/nightly/rustc/check-cfg/cargo-specifics.html> for more information about checking conditional configuration
  = note: `#[warn(unexpected_cfgs)]` on by default
```

And without Cargo, you get the same behavior when you pass e.g., `--check-cfg 'cfg(feature, values("some_feature_name"))'`.

---

Closing as fixed.
