### ISSUE TITLE
Rustdoc: Help dialog doesn't open when the `?` key is not behind Shift

### ISSUE THREAD

**Issue by runiq** [rust-lang/rust#75386]
I'm using a [weird keyboard layout](https://neo-layout.org) which doesn't put the `?` key behind Shift, which stopped me from ever viewing the help popup in Rustdoc. If I had managed to open the help popup, I would have learned about the incredibly useful [type-based search feature](https://github.com/rust-lang/rust/issues/75197) much sooner. :+1: 

As far as I can tell, the code responsible is [here](https://github.com/rust-lang/rust/blob/master/src/librustdoc/html/static/main.js#L411-L413): It's checking for `ev.shiftKey` unconditionally, but I believe it's only supposed to check when [`ev.key` is undefined](https://github.com/rust-lang/rust/blob/master/src/librustdoc/html/static/main.js#L339).

**Comment by GuillaumeGomez** [comment]
I added a button to show the help yesterday in #75366. However, it shouldn't fail like this. Sending a fix.
