### ISSUE TITLE
Document diverging functions, and ⊥, better

### ISSUE THREAD

**Issue by catamorphism** [rust-lang/rust#7538]
As per discussion on IRC, it's surprising at first that ```return();``` is an expression. What's the result type of this expression? Bottom / _|_ , but since you can't write this type explicitly in Rust, it's confusing.

Likewise, it's tempting to invoke ```fn f() -> !``` when trying to explain ⊥, but that's different -- it means "f definitely diverges".

So, document these clearly and precisely in the manual / tutorial.

**Comment by steveklabnik** [comment]
https://github.com/rust-lang/rust/pull/22275 documents these in the book, and we have info in the reference.
