### ISSUE TITLE
Ident mangling and unicode.

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#7539]
#7488 added a fix to mangle unicode identifiers because the android assembler can't handle them. It is essentially the easiest mangling possible (using `char::escape_unicode` and replacing the leading `\` with a `$`), with no reference to any other compilers that perform unicode mangling.

Presumably, matching any precedent (if there is one) would be best, in terms of tool support etc.

This bug represents the task of researching this and fixing it.

**Comment by BigBoneDaddy** [comment]
@FlaPer87 Yes I too am of agreement that one mangling is best.

**Comment by tromey** [comment]
On Linux the C++ name-mangling scheme is defined by the so-called Itanium C++ ABI.  It doesn't define the encoding for identifiers outside of ASCII.  See http://mentorembedded.github.io/cxx-abi/abi.html#mangling-structure and search for "A-Z":

>  <identifier> is a pseudo-terminal representing the characters in the unqualified identifier for the entity in the source code. This ABI does not yet specify a mangling for identifiers containing characters outside of _A-Za-z0-9.

On most platforms, GCC sets the source charset to be UTF-8.  I think the source charset is used when emitting symbols, and so this will be used.  However, on a system where the host charset is EBCDIC (lol) the source charset will be UTF-EBCDIC.  You probably don't need to worry about this.

GDB and BFD naively read the symbol names as bytes and hope the right thing happens.  The demangler doesn't have any real support for any sort of Unicode mangling -- it does have a mode for Unicode support that was added for gcj, but this is only enabled if the Java demangling option is given, which isn't desirable for Rust.  In this mode, a non-ASCII character is encoded as "__U[...hex digit...]+_" (e.g., "__U3FE_").  (Though, hilariously, the decoding also bails on any result > 256 ... not sure how that makes any sense at all.)  IIRC we added this sort of encoding precisely to work around assembler issues.

I think the best thing to do, on Linux, would be not to share mangling with C++ at all; define a sensible Rust mangling (it could share concepts or whatever but ideally would create distinct names -- basically don't start with "_Z"); and then add a Rust mode to the libiberty demangler and basic Rust demangling support to gdb.  The gdb parts of this are not a large project and were done in recent times for D, so there's even recent patches that can be cribbed from.

**Comment by steveklabnik** [comment]
Triage: not aware of any changes here.

**Comment by Centril** [comment]
Triage: cc https://github.com/rust-lang/rust/issues/55467.

**Comment by michaelwoerister** [comment]
Yes, it would.

**Comment by Mark-Simulacrum** [comment]
I believe this can be closed now as we're eventually looking to switch to the new mangling scheme, and in particular this is already listed as an unresolved problem on the tracking issue (https://github.com/rust-lang/rust/issues/60705); we can open a new bug if there's extensive discussion on the subject in the future.
