### ISSUE TITLE
`match` arm without tail expression diverging type error has non-ideal spans

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#75418]
[Given](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=caad3bdfe7badbe191aad8d8ae5f6246):

```rust
    let _ = match Some(42) {
        Some(x) => {
            x
        }
        None => {
            0;
        }
    };
```
we emit
```
error[E0308]: `match` arms have incompatible types
 --> src/main.rs:6:17
  |
2 |        let _ = match Some(42) {
  |   _____________-
3 |  |         Some(x) => {
4 |  |             x
  |  |             - this is found to be of type `{integer}`
5 |  |         }
6 |  |         None => {
  |  |_________________^
7 | ||             0;
8 | ||         }
  | ||_________^ expected integer, found `()`
9 |  |     };
  |  |_____- `match` arms have incompatible types
```

We should be

* [ ] checking that removing the `;` in the incompatible arm would solve the issue and suggest it
* [ ] point at the last statement in the incompatible arm instead of the whole arm

**Comment by tirr-c** [comment]
I'd like to work on this. I've found a similar logic on reporting if-else type mismatch, maybe this could be done in that way.

**Comment by estebank** [comment]
@tirr-c that would be great! That code would probably work with very little modification. If it does, please extract it to a method called from both places :)
