### ISSUE TITLE
a small requirement for Iteration to support foldmap

### ISSUE THREAD

**Issue by zhibo501** [rust-lang/rust#75410]
Hi guys,

I want to make a small requirement for *Iteration* to support foldmap.

**foldmap** provides an accumulator for mapping like this:

[v0, v1, v2, v3] 

  ->  [v0, v0+v1, v0+v1+v2, v0+v1+v2+v3]

  ->  [v0, v0*(v0+v1), v0*(v0+v1)*(v0+v1+v2), v0*(v0+v1)*(v0+v1+v2+v3)]

In this way, **foldmap** can be composed conveniently than **map**.

```rust
fn funny(v: Vec<i32>) -> Vec<i32> {
	v.iter()
		.foldmap(0, |acc, x| acc + x)
                .foldmap(1, |acc, x| acc * x)
		.collect()
}
```

_Originally posted by @zhibo501 in https://github.com/rust-lang/rust/issues/75367#issuecomment-671466066_

**Comment by bugadani** [comment]
Interesting idea. I think it may be possible to implement this in userland, maybe it would be useful to add to [itertools](https://github.com/rust-itertools/itertools)?

**Comment by cuviper** [comment]
You can do this with [`scan`](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.scan), or even just a regular `map` and captured closure arguments. It's a little more verbose to separate the state update and the item return, but also more flexible.

**Comment by zhibo501** [comment]
@bugadani

OK, that's good.

But it's better if the language supports this function natively.  :)

**Comment by zhibo501** [comment]
@cuviper
Thanks for your reply. 
*scan* only supports to return Option type, and flatten is required.
If we use the regular *map*, we need to define additional variables to store state, like this:
```rust
fn funny(v: Vec<i32>) -> Vec<i32> {
        let mut t1 = 0;
        let mut t2 = 1;
	v.iter()
		.map(|x| {t1 = t1 + x; t1})
		.map(|x| {t2 = t2 * x; t2})
		.collect()
}
```

**Comment by cuviper** [comment]
The `scan` function returns `Option` because you can terminate early with `None`, just like an implementation of `Iterator::next()`. When you return `Some(value)` the next stage of the iterator will get an unwrapped `value`.

```rust
fn funny(v: Vec<i32>) -> Vec<i32> {
    v.iter()
        .scan(0, |acc, x| { *acc += x; Some(*acc) })
        .scan(1, |acc, x| { *acc *= x; Some(*acc) })
        .collect()
}
```

(The dereferencing `*acc` is because the closure gets `&mut St`.)

**Comment by zhibo501** [comment]
@cuviper  It's great. I'm wrong about *scan*. 
However, *scan* is meaning of browsing elements, and it maybe terminate during scanning. In an abstract sense, it is different from fold and map. 
And the code implementation with *foldmap* is more concise and graceful. :)

**Comment by zhibo501** [comment]
@cuviper  It's great. I'm wrong about *scan*. 
However, *scan* is meaning of browsing elements, and it maybe terminate during scanning. In an abstract sense, it is different from fold and map. 
And the code implementation with *foldmap* is more concise and graceful. :)

**Comment by workingjubilee** [comment]
@zhibo501 It is very common for crates to be used to demonstrate a functionality is useful and desired before adding them to rustc itself. There has been a recent push to implement Iterator::join based on it being one of the most popular methods of `itertools`. It is easier and lower friction there, since new features, even methods, only get added as unstable implementations in rustc. That was not a random suggestion, it was your best bet!

**Comment by camelid** [comment]
Should this be closed since it should be in userland first?
