### ISSUE TITLE
Traits for or_else, and_then, then ... etc. methods?

### ISSUE THREAD

**Issue by mankinskin** [rust-lang/rust#75429]
Types like [`Option`](https://doc.rust-lang.org/std/option/enum.Option.html) and [`Result`](https://doc.rust-lang.org/std/result/enum.Result.html) have a kind of binary nature to them, and often I notice that I want to use the same kinds of logical operations on other types than these two (same with `map`, actually). An example would be [`std::poll::Poll`](https://doc.rust-lang.org/std/task/enum.Poll.html).

Option and Result already share this behaviour:
- and
- and_then
- or
- or_else
- map
- map_or
- map_or_else

Option also has:
- xor

Result also has:
- map_err

There are some other common methods, like `iter`, `unwrap` and some more. So this might be a more general question: Is it a good idea to put these methods into traits and implement them through those traits?

_**Why would you need that?**_
Although it will probably not provide a lot of code reuse, it does make these interfaces explicit and will make it more likely for crates to implement complete interfaces. This would discourage crates from implementing only `map` or only `and_then` or something like that. Also it might allow for generic programming against any type providing those methods.
For example `Poll` only implements `map` but not `and_then` or `or`, although these would make sense too.

**Comment by mankinskin** [comment]
So I experimented a bit, and mostly it comes down to mapping all of these types to `Result`. Soany Type that can be converted from and into a `Result`, can be used as a "dual" value, meaning a value that is either one or the other.
Here an incomplete example of the kind of trait I am talking about:
```rust
trait Dual<T, E> : Sized + From<Result<T, E>> + Into<Result<T, E>> {
    fn into_result(self) -> Result<T, E> {
        self.into()
    }
    fn and<U, B: Dual<U, E>>(self, b: B) -> B {
        self.into_result().and(b.into_result()).into()
    }
    fn and_then<U, B: Dual<U, E>, F: FnOnce(T) -> B>(self, f: F) -> B {
        self.into_result().and_then(|r| f(r).into_result()).into()
    }
    fn or<C, B: Dual<T, C>>(self, b: B) -> B {
        self.into_result().or(b.into_result()).into()
    }
    fn or_else<B: Dual<T, E>, F: FnOnce(E) -> B>(self, f: F) -> B {
        self.into_result().or_else(|r| f(r).into_result()).into()
    }
    fn map<U, B: Dual<U, E>, F: FnOnce(T) -> U>(self, f: F) -> B {
        self.into_result().map(|r| f(r)).into()
    }
    fn map_err<C, B: Dual<T, C>, F: FnOnce(E) -> C>(self, f: F) -> B {
        self.into_result().map_err(|e| f(e)).into()
    }
}
```
Now there are other methods which are universally useful for types of this kind, like:
- `unwrap`, `unwrap_err`, `expect`, `expect_err`: but these require `T` and `E` to be `Debug` respectively, even though in practice you might not actually use those functions and the Bounds would be unreasonable
- `not`, `xor`: But these would require `E` and `T` to be `Default` or a default to be provided.

**Comment by workingjubilee** [comment]
If you mean "higher kinded types" that's part of what "generic associated types" ([RFC 1598]) are for. But I agree that this would be a Cool Trait To See at some point.

[RFC 1598]: https://rust-lang.github.io/rfcs/1598-generic_associated_types.html

**Comment by mankinskin** [comment]
I bumped into this when I noticed that `std::poll::Poll` does not implement `and_then`, which seemed weird, because `Poll` is basically an `Option`, structurally and conceptually. But it is nice to know that these kinds of features are already desired and being worked on. I will see if I can contribute something helpful aswell.

**Comment by workingjubilee** [comment]
Oh, I should note since I missed it, ish: Option and Result impl IntoIterator which is slightly more fundamental to iteration than `iter` method itself, which I believe due to various reasons winds up being more per-case implemented instead of Traitful.

`unwrap` will almost certainly be injectable into the concept of a trait abstracting over T(V, N) -> V, !

You also want to pay attention to the existing [Try trait](https://doc.rust-lang.org/std/ops/trait.Try.html).
