### ISSUE TITLE
Labels scoped too highly

### ISSUE THREAD

**Issue by evanrichter** [rust-lang/rust#75433]
Hello, I believe I found a bug in how labels are defined to a scope. The same text `abcd` defines two distinct labels, each inside an anonymous scope using `{ ... }`.

I tried this code:

```rust
fn main() {
    {
        'abcd: loop {
            break 'abcd;
        }
    }
    {
        'abcd: loop {
            break 'abcd;
        }
    }
}
```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=c595115c12fd17130908c4391ef63f81))

Errors:

```
   Compiling playground v0.0.1 (/playground)
warning: label name `'abcd` shadows a label name that is already in scope
 --> src/main.rs:8:9
  |
3 |         'abcd: loop {
  |         ----- first declared here
...
8 |         'abcd: loop {
  |         ^^^^^ lifetime 'abcd already in scope

warning: 1 warning emitted

    Finished dev [unoptimized + debuginfo] target(s) in 0.42s
     Running `target/debug/playground`

```

I expected to see this happen: *code compiles*

Instead, this happened: *labels are identified as the same, but they actually have different scopes*

### Meta
This appears to happen on both nightly and stable.

**Comment by LennyKappa** [comment]
This seems to be intentional, as indicated by tests for this situation in `src/test/compile-fail/loops-reject-duplicate-labels-2.rs`, but I think it would be nice if there was someone else to discuss this with.

(also see #21633)

**Comment by jonas-schievink** [comment]
Yeah, this is working as intended. Feel free to discuss this on https://internals.rust-lang.org/ though.
