### ISSUE TITLE
Struct.field should resolve for intra-doc-links

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#75437]
Found in https://github.com/rust-lang/rust/pull/75432#pullrequestreview-465538679. `std::process::Child.stdout` should resolve to the struct field, but instead gives a resolution error - you have to use `Child::stdout` instead. This is a break from the original RFC: https://github.com/rust-lang/rfcs/blob/68e17ace829e81239fe5020b7a6dbc22550b6d16/text/1946-intra-rustdoc-links.md#linking-to-fields

**Comment by jyn514** [comment]
Relevant code: https://github.com/rust-lang/rust/blob/b11e2f23411ec9aea4aa261c644f2c9e0df9457a/src/librustdoc/passes/collect_intra_doc_links.rs#L256, https://github.com/rust-lang/rust/blob/b11e2f23411ec9aea4aa261c644f2c9e0df9457a/src/librustdoc/passes/collect_intra_doc_links.rs#L369. Treating enum variants and struct fields the same looks very wrong.

**Comment by Manishearth** [comment]
I'm actually kinda iffy on this, I prefer the current behavior and we get to avoid clashes with `foo.com`.

**Comment by jyn514** [comment]
Hmm, I think `struct.field` is more clear though since it's how you'd use it in rust code. But fortunately this only adds new behavior so it doesn't block stabilization, we can always choose to add it later.

**Comment by Manishearth** [comment]
Yeah I'm just worried about the possibilities of ambiguity. It was listed as an optional extension in the rfc and iirc this was part of why.

**Comment by GuillaumeGomez** [comment]
I'm not a big fan of this syntax but it's not a strong position either...

**Comment by camelid** [comment]
`struct.field` is less surprising which is good, but I definitely understand that it's difficult given the potential for clashes (especially with non-`.com`, `.org`, `.net` domains, e.g. `.name`). Maybe rustdoc could assume that it's an intra-doc link, and if it doesn't resolve then link to the equivalent domain? Unfortunately there's potential for minor breaking changes, although the Rust style is to have uppercase struct names and much of the time people link to lowercase domains, so maybe it wouldn't be too much of a clash.

**Comment by jyn514** [comment]
@camelid the concern I think is that there's no way to _detect_ the ambiguity without reaching out and making network requests, which no one wants. So there's the potential that rustdoc could silently link to something other than what you intended, which is against the spirit of intra-doc links.

**Comment by jyn514** [comment]
and as a corrollary, rustdoc couldn't warn if the link failed to resolve, because it would have to assume it was a network link.

**Comment by camelid** [comment]
Yeah, it's too bad that there's not a solution that doesn't involve ambiguity and is unsurprising :(

**Comment by jyn514** [comment]
I think changes in this area should be a change to the intra-doc links RFC, not an implementation issue, so I'm going to close this.
