### ISSUE TITLE
Bad printing of const-eval queries

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#75447]
Evaluating of promoteds currently looks very confusing in the query stack:
```
query stack during panic:
#0 [const_eval_raw] const-evaluating `main`
#1 [const_eval_validated] const-evaluating + checking `main`
#2 [const_eval_validated] const-evaluating + checking `main`
#3 [normalize_generic_arg_after_erasing_regions] normalizing `main::promoted[2]`
#4 [optimized_mir] optimizing MIR for `main`
#5 [collect_and_partition_mono_items] collect_and_partition_mono_items
```
`main` is not a const, so "const-evaluating `main`" is just nonsense.

I presume that this is easy to fix but only @oli-obk would know how. ;)

**Comment by RalfJung** [comment]
Also see https://github.com/rust-lang/rust/pull/75445#issuecomment-672785117

**Comment by ThibsG** [comment]
Let's give a try :wink:

**Comment by RalfJung** [comment]
@ThibsG awesome. :) Let us know if you need any help.

I am not very familiar with that specif code, but can still help with more general questions, and I hope @oli-obk can help with the specifics. :D
