### ISSUE TITLE
debug_assert! does not actually compile out the assert

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#75460]
I tried this code:

```rust
#[cfg(debug_assertions)]
use my_crate::Item;
fn main() {
    debug_assert_ne!(0, Item);
}
```

I expected to see this happen: The crate compiles correctly in release mode.

Instead, this happened: The crate does not compile, because `debug_assert` uses `if cfg!` instead of `#[cfg]`.

https://github.com/rust-lang/rust/blob/2c31b45ae878b821975c4ebd94cc1e49f6073fd0/library/core/src/macros/mod.rs#L183-L185

**Comment by jonas-schievink** [comment]
Pretty sure this is intended

**Comment by jyn514** [comment]
What's the point of compiling it in? It slows down compile times in release mode too because LLVM has to optimize out the branch.

**Comment by jonas-schievink** [comment]
It type-checks the expressions involved

**Comment by Mark-Simulacrum** [comment]
We should be eliminating the IR before it hits LLVM with MIR opts, since it's a trivial case - not sure if that's enabled by default though.

**Comment by jonas-schievink** [comment]
`if false` should get optimized out by `SimplifyBranches`. It is also run after const prop, so many cases should be handled (even at opt-level 0).

**Comment by Mark-Simulacrum** [comment]
Perfect, that's what I had thought.

It would also be backwards incompatible in theory (though unlikely in practice) to change this as you could implement a trait inside the debug_assertion conditions which would then get dropped when moving to `#[cfg()]`.

Closing as won't fix; continued discussion should take place on internals and eventually perhaps a lang-team MCP.

**Comment by timstr** [comment]
A simple workaround is to prepend `#[cfg(debug_assertions)]` to the assertion. This simply skips compiling the entire assertion in release builds.
```
#[cfg(debug_assertions)]
use my_crate::Item;

fn main() {
    #[cfg(debug_assertions)]
    assert_ne!(0, Item);
}
```
