### ISSUE TITLE
`min_const_generics` prevents references to concrete `Self` param

### ISSUE THREAD

**Issue by lcnr** [rust-lang/rust#75486]
👋 I'm trying to understand the limitations of `min_const_generics`. Is it expected that https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=59cca2f3891e9fa921afdcbcda9f2588 compiles ok without `min_const_generics`, but fails with it?

_Originally posted by @alex in https://github.com/rust-lang/rust/issues/74878#issuecomment-673457909_

**Comment by lcnr** [comment]
We should not break stable code and change the `generic parameters must not be used inside of non trivial constant values` check to only run for const parameters.

So this is a bug of the current `min_const_generics` implementation.

**Comment by alex** [comment]
Thank @lcnr! Sorry about the noise on the tracking bug!

**Comment by alex** [comment]
FWIW, I was able to work around this in my own code by replacing `mem::size_of::<Self>()` with `mem::size_of::<what self is>()`: https://github.com/alex/rust-asn1/compare/ee5e5b48b5c765b8d460dc1b44b7716c59325706..bc7be1da41d86e99b602c8df66c320f8edc01f63
