### ISSUE TITLE
Add an option to exclude source code from docs

### ISSUE THREAD

**Issue by kpp** [rust-lang/rust#75497]
**Describe the problem you are trying to solve**

I ship a proprietary cdylib which I build from Rust code. I want to document the API using doc comments. However at the moment `cargo doc` puts the source code into target/doc/src/ which is not an option. I know I can `rm target/doc/src/` however there is `[src](goto source code)` button left in the top right corner of the docs.

**Describe the solution you'd like**

`cargo doc --exclude-source`

**Notes**

**Comment by ehuss** [comment]
This is more of an issue for rustdoc, so moved to rust-lang/rust where its issue tracker resides.

**Comment by ollie27** [comment]
The [`#![doc(html_no_source)]`](https://doc.rust-lang.org/nightly/rustdoc/the-doc-attribute.html#html_no_source) crate level attribute prevents the source files from being emitted. Does that solve this issue?

**Comment by mexus** [comment]
OMG it does! Thanks a lot, @ollie27! Although why don't we make a rustdoc flag for that?

**Comment by GuillaumeGomez** [comment]
Well, let's add one then...

**Comment by jonas-schievink** [comment]
Does it make sense to have both an attribute and a command line flag for this? This doesn't seem like something you'd want to configure on a per-invocation basis, it's more like something that's permanent for a given code base (so the attributes fits better).

**Comment by Lonami** [comment]
I think it fits the use case of being able to produce end-user documentation (without source links if providing binaries only) and internal documentation (with source links that may be helpful in some cases).

**Comment by pickfire** [comment]
Currently the only way to find this is through rustdoc book, which may not be quite discoverable if the users didn't saw that. I wish there is a manpage for rustdoc book but still currently man pages for rust is still not very good yet since we haven't figured out how to get to show the correct man pages for the current directory.

**Comment by mexus** [comment]
@jonas-schievink ,
> This doesn't seem like something you'd want to configure on a per-invocation basis, it's more like something that's permanent for a given code base (so the attributes fits better).

Well, while the attribute is kinda sufficient, it would be also great to have an option to jump-to-source-code during the development phase. On the other hand, the attribute could be disabled/enabled with a feature flag, so having a rustdoc flag is not exactly required.

**Comment by jyn514** [comment]
https://github.com/rust-lang/rust/pull/75522 was closed as won't fix since there are already ways to do this and it's not standard to duplicate attributes as arguments.

**Comment by kyrias** [comment]
Is there currently any way to disable source generation for the current crate and all dependencies on stable?  The suggestion from that PR requires an unstable flag that doesn't appear to have had any stabilization plans since it was added in #52355.

**Comment by jyn514** [comment]
no. i would like to stabilize that flag but i don't think it currently has a tracking issue. i am happy to mentor that work if you're interested in contributing :)

**Comment by kyrias** [comment]
In our case it represents just under 20% of the whole docs directory.
