### ISSUE TITLE
Rust

### ISSUE THREAD

**Issue by hjhk1911** [rust-lang/rust#75493]
```rust
#![allow(unused)]
// All of these print "Hello x    !"
fn main() {
println!("Hello {:5}!", "x");
println!("Hello {:1$}!", "x", 5);
println!("Hello {1:0$}!", 5, "x");
println!("Hello {:width$}!", "x", width = 5);
}
```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=cbc611bdc6f520c43e48e5196e05152f))

**Comment by lzutao** [comment]
What problem do you raise with the code? Also there are issue template to fill in for better bug report.

**Comment by hbina** [comment]
@lzutao I don't wanna call its a troll or whatever but this is the exact code from here https://doc.rust-lang.org/std/fmt/#width 
@hjhk1911  You might want to elaborate.

**Comment by Mark-Simulacrum** [comment]
We try to keep the issue tracker solely for issues, and this does not appear to be one. General discussion belongs on the users.rust-lang.org forum. Thanks!
