### ISSUE TITLE
One more missed bounds check optimization

### ISSUE THREAD

**Issue by bugadani** [rust-lang/rust#75525]
https://godbolt.org/z/3TGbK9

It looks like bounds checks are not eliminated when more than one restriction is applied to the index variable (i.e. when it's range checked from two sides). Late edit: It's also interesting that the issue disappears for certain lower limits. For example `if idx > 2 && idx < 8` is optimized, while `if idx > 5 && idx < 8` is not.

Using assumptions, the bounds checks are removed as expected: https://godbolt.org/z/Ksn8dW
However, if any of the assumptions is a GE or LE instead of a GT or LT, the bounds checks are back: https://godbolt.org/z/YhK1rT

**Comment by lzutao** [comment]
This could be improved by optimizing MIR. But the problem rely on LLVM too.
The C version: https://godbolt.org/z/EvjdTP
Clang trunk has more optimizations than v10.0.1.
GCC is still ahead in these optimizations.

**Comment by the8472** [comment]
Same as #73396?

**Comment by davidbolvansky** [comment]
Posted on llvm bugzilla:
https://bugs.llvm.org/show_bug.cgi?id=47172

**Comment by bugadani** [comment]
Thanks for that report!

I've played some more with my examples and these three cases are particularly interesting for me: https://godbolt.org/z/z6o3Pc
I'm curious if the improvements shown by Clang trunk are caused by clang or llvm, and if llvm, will it fix these as well. I guess time will tell this :)

**Comment by davidbolvansky** [comment]
Since Clang does no optimizations, this is all about about LLVM:)

Also worth to see:
https://reviews.llvm.org/D84547

**Comment by nikic** [comment]
This happens because LLVM canonicalizes `idx > 5 && idx < 8` to `len & -2 == 6`, at which point it fails to reason about the implied value range.

**Comment by nikic** [comment]
Partial fix: https://github.com/llvm/llvm-project/commit/445db89b537e5397a2d4b08e79751edb845b2c2a

**Comment by nikic** [comment]
Partial fix 2: https://github.com/llvm/llvm-project/commit/fe79061be2b2915993b5568cddc6b64ea0a525f6

**Comment by jrmuizel** [comment]
I confirmed that `f2` and `f3` are fixed by #81451

**Comment by bugadani** [comment]
This issue has been fixed by the LLVM 12 update. Note that in the original compiler explorer link, f1 has a bounds check, which is expected there. Other examples are optimized now.
