### ISSUE TITLE
Add more content into rustdoc book

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/rust#75521]
https://doc.rust-lang.org/rustdoc/what-is-rustdoc.html is a very nice introduction, but maybe it's time to go further and provide maybe guidelines, more tips and customization chapters?

**Comment by AndyGauge** [comment]
I'm going to begin working on this.  Many questions to follow :)

**Comment by AndyGauge** [comment]
Is this the kind of info we want to see:
 - https://github.com/rust-lang/rfcs/pull/1687
- https://rust-lang.github.io/api-guidelines/documentation.html

Also, I'd love to get an idea what customization can be done, haven't seen that in the wild.

**Comment by AndyGauge** [comment]
Got started today on this.  Here's a bit of the work:
https://github.com/AndyGauge/rust/pull/1
Is it in the right direction?
