### ISSUE TITLE
Unnecessary assertion inside `while i < *::MAX` loop

### ISSUE THREAD

**Issue by MSxDOS** [rust-lang/rust#75546]
```Rust
pub fn test() {
    let mut i = 1u32;
    while i < u32::MAX {
        assert_ne!(i, 0, "No way...");
        i += 1;
    }
}
```
https://godbolt.org/z/oY5ra8

The assertion disappears when comparing against a non-MAX value for a given type, or with `mir-opt-level` 2 and above.

**Comment by lzutao** [comment]
Another LLVM issue, probably because of wrapping around integers:
C version: https://godbolt.org/z/688dhv
@rustbot modify labels: A-LLVM

**Comment by MSxDOS** [comment]
> The assertion disappears ... with `mir-opt-level` 2 and above

Now it also requires `-Zunsound-mir-opts`

**Comment by MSxDOS** [comment]
The example is fixed on nightly, probably by https://github.com/rust-lang/rust/pull/81451
