### ISSUE TITLE
Bug in borrow checker with check &mut references.

### ISSUE THREAD

**Issue by heckad** [rust-lang/rust#75558]
I tried this code:

```rust
struct A;

impl A {
    pub fn get_something(&self) -> i32 { 12 }
}

struct B;

fn f<T: Into<B>>(v: T) {}

impl From<&mut A> for B {
    fn from(_: &mut A) -> Self { B }
}

fn main() {
    let mut a = A;

    let mut_ref_a = &mut a;

    f(mut_ref_a);
    mut_ref_a.get_something();
}
```

I expected to see this happen: all good

Instead, this happened: compilation error

### Meta

`rustc --version --verbose`:
```
rustc 1.47.0-nightly (8e21bd063 2020-08-14)
binary: rustc
commit-hash: 8e21bd0633b8d970646ee6eb706c9e8acfad19af
commit-date: 2020-08-14
host: x86_64-pc-windows-gnu
release: 1.47.0-nightly
LLVM version: 10.0
```

**Comment by jonas-schievink** [comment]
This is working as expected. Use `f(&mut *mut_ref_a);` to reborrow manually.

**Comment by heckad** [comment]
Why need to do reborrow manually?  Why can't the compiler do this on its own?

**Comment by jonas-schievink** [comment]
Automatic reborrows are performed for method receivers only. Changing this would require an RFC.

**Comment by heckad** [comment]
Do these functions are method revivers?
```
fn reverse(xs: &mut [i32]) {
    xs.reverse()
}

fn do_nothing(xs: &mut [i32]) {
    reverse(xs);
    reverse(xs);
}
``` 
This code works!

**Comment by jonas-schievink** [comment]
Ah, sorry, no, it's not just receivers, but it doesn't work when there are generics involved

**Comment by heckad** [comment]
Because I think this is the bug. May be reopen this?

**Comment by heckad** [comment]
@jonas-schievink, what do you say?

**Comment by jonas-schievink** [comment]
This is a fairly well-known limitation, I don't think we need another issue open for this. The more general problem is that coercions (of which automatic reborrowing is an example) can only apply if both the expected and actual type are known, but that is not the case when calling a generic method (the type parameter is instantiated, turning it into an inference variable).

**Comment by heckad** [comment]
Where did the discussion of this fairly well-known problem take place?

**Comment by jonas-schievink** [comment]
not sure

**Comment by heckad** [comment]
Not sure in what? Sorry, my English is poor.

**Comment by jonas-schievink** [comment]
I can't find the discussion at the moment
