### ISSUE TITLE
Should we use an enum to encode fields?

### ISSUE THREAD

**Issue by tesuji** [rust-lang/rust#75550]
https://github.com/rust-lang/rust/blob/668a34e0f438d4a950b9440239656d6755ad963c/src/librustc_span/lib.rs#L1079-L1088

```rust
enum Name {
    /// The name of the file that the source came from. Source that doesn't 
    /// originate from files has names between angle brackets by convention 
    /// (e.g., `<anon>`). 
    Normal(FileName),
    /// FileName modified by `--remap-path-prefix`. 
    Remapped(FileName),
}

pub struct SourceFile { 
    pub name: Name,
    /// The unmapped path of the file that the source came from. 
    /// Set to `None` if the `SourceFile` was imported from an external crate. 
    pub unmapped_path: Option<FileName>, 
    ...
}
```

**Comment by Nicholas-Baron** [comment]
I started writing a naive implementation.

1. `Name` would have to be `pub` if the `name` field in `SourceFile` is `pub`
2. `Name` has to derive the following at a minimum: Clone, Debug, PartialEq, Eq, Encodable, Decodable, Display
3. There are some places in the current code where whether a file was remapped is not taken into account. Should there be something like `fn unwrap(&self) -> FileName` on `Name`?

PS: I will put a branch up once everything is compiling, unless someone would like to see the code earlier.

**Comment by lzutao** [comment]
Nice, could you open a draft PR?

**Comment by Nicholas-Baron** [comment]
@lzutao Draft PR opened.

**Comment by matklad** [comment]
Super drive by comment, but my gut feeling is that the better fix is to add a type for `(name, name_was_remapped, unmpapped_path)` triple, rather than go for surface level refactoring of eliminated the bool.

Wild-guessing even further, I'd suggest

```rust
pub struct SourceFileName {
    // Note absence of pub
    name: FileName,
    unmapped_name: Option<FileName>
}

impl SourceFileName {
    pub fn name(&self) -> &FileName { &self.name } 
    pub fn unmapped_name(&self) -> &FileName { self.unmpped_name.as_ref().unwrap_or(self.name()) }
}
```

**Comment by petrochenkov** [comment]
Yeah, https://github.com/rust-lang/rust/pull/75616 looks like a regression rather than improvement to me.

**Comment by Nicholas-Baron** [comment]
@petrochenkov @matklad I have started working on the suggestion. The crate itself and some of its dependents compile.

**Comment by Nicholas-Baron** [comment]
@matklad Your wild guess seems to be working.

@petrochenkov I hope now #75616 is not a regression.

**Comment by Nicholas-Baron** [comment]
@rustbot unclaim

I am too distracted to finish the pull request.

**Comment by rossmacarthur** [comment]
Triage looks like this was fixed in https://github.com/rust-lang/rust/pull/83813 :)

**Comment by JohnTitor** [comment]
Closing as fixed.
