### ISSUE TITLE
rustdoc displayed wrongly higher-kind functions generated by macros

### ISSUE THREAD

**Issue by tesuji** [rust-lang/rust#75564]
`rustdoc` displayed wrongly higher-kind functions generated by macros.

For example, in this link to [`rustc_middle::ty::query::Providers`][1]:
![image](https://user-images.githubusercontent.com/15225902/90312678-7e620a00-df30-11ea-9166-ba810f080441.png)

where defined:
![image](https://user-images.githubusercontent.com/15225902/90312686-95086100-df30-11ea-9318-1e62c01faf8c.png)

[1]: https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/query/struct.Providers.html

### Meta

`rustc --version --verbose`:  1.47.0-nightly (8e21bd063 2020-08-14)

**Comment by lzutao** [comment]
rustbot modify labels: T-rustdoc
