### ISSUE TITLE
Compiled program segfaults on Windows with thin LTO.

### ISSUE THREAD

**Issue by XAMPPRocky** [rust-lang/rust#75589]
Compiling Tokei on stable with thin LTO optimisations currently produces a binary which just segfaults at run-time producing a `STATUS_ACCESS_VIOLATION` error. When compiled with no or fat LTO tokei works normally as expected.

### How to reproduce

- Clone [Tokei](https://github.com/XAMPPRocky/tokei)
- `cargo run --release` for ` x86_64-pc-windows-msvc`.

Tokei Issue: https://github.com/XAMPPRocky/tokei/issues/612

**Comment by mati865** [comment]
Commit `d52bc083f9b7f0f9f641dd5f3f585ba97d5fd256` works for me with both `x86_64-pc-windows-gnu` and `x86_64-pc-windows-msvc`.
```
$ rustc -vV
rustc 1.47.0-nightly (9b88e0a86 2020-08-15)
binary: rustc
commit-hash: 9b88e0a8667040452a94fda8548f0f5f0f801f90
commit-date: 2020-08-15
host: x86_64-pc-windows-gnu
release: 1.47.0-nightly
LLVM version: 10.0
```

**Comment by XAMPPRocky** [comment]
Seems like this is resolved in the next release.
