### ISSUE TITLE
Missing Implementors for Join and Pattern trait in rustdoc

### ISSUE THREAD

**Issue by lzutao** [rust-lang/rust#75588]
Missing Implementors for [`std::slice::Join`][1] trait.

Current output:
![image](https://user-images.githubusercontent.com/15225902/90333818-17f1f000-dff3-11ea-949a-0d876dfb67ea.png)

While rustdoc displays [`Borrow`][2] trait implementors.

Expected: 
Display Implementors for Join trait: https://github.com/rust-lang/rust/blob/de32266a1780aa4ef748ce7f6200a1554fad0aca/library/alloc/src/slice.rs#L635-L703

### Meta

`rustc --version --verbose`: 1.47.0-nightly (9b88e0a86 2020-08-15)

[1]: https://doc.rust-lang.org/nightly/std/slice/trait.Join.html
[2]: https://doc.rust-lang.org/nightly/std/borrow/trait.Borrow.html#implementors

@rustbot modify labels: T-rustdoc

**Comment by lzutao** [comment]
This is a regression from stable-to-nightly: https://doc.rust-lang.org/1.45.2/std/slice/trait.Join.html and beta one has Implementors section.

cc @jyn514

**Comment by lzutao** [comment]
It has made it way to beta. Pattern trait is also affected: https://doc.rust-lang.org/beta/std/str/pattern/trait.Pattern.html#implementors

@rustbot modify labels: I-priority

**Comment by LeSeulArtichaut** [comment]
(Btw I think you can use `@rustbot prioritize` as a shorthand)

**Comment by lzutao** [comment]
The Borrow trait still has [Implementors section](https://doc.rust-lang.org/nightly/std/borrow/trait.Borrow.html#implementors), I am not sure if this bug affect crates in ecosystem.

**Comment by lzutao** [comment]
So I think this bug shouldn't affect stable traits, just most unstable traits I saw are affected.

**Comment by lzutao** [comment]
There is high change that #73767 causing the regression, but I cannot prove that.

**Comment by jyn514** [comment]
This is more likely to be https://github.com/rust-lang/rust/pull/73771 than the refactor I think.

**Comment by Mark-Simulacrum** [comment]
Yeah, I suspect that given https://github.com/rust-lang/rust/issues/74672 it might make sense to revert anyway, since it doesn't actually accomplish the goal.

Or someone more experienced with rustdoc may be able to suggest/implement a better patch.

**Comment by lzutao** [comment]
New discovery: So far only trait exported to std affected. For example with Join trait, in alloc it is normal: https://doc.rust-lang.org/nightly/alloc/slice/trait.Join.html

**Comment by lzutao** [comment]
Oh right, I have MCVE, it needs two dummy crates.

**Comment by lzutao** [comment]
searched nightlies: from nightly-2020-06-04 to nightly-2020-07-17
regressed nightly: nightly-2020-07-17
searched commits: from https://github.com/rust-lang/rust/commit/7e11379f3b4c376fbb9a6c4d44f3286ccc28d149 to https://github.com/rust-lang/rust/commit/5c9e5df3a097e094641f16dab501ab1c4da10e9f
regressed commit: https://github.com/rust-lang/rust/commit/5c9e5df3a097e094641f16dab501ab1c4da10e9f

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.5.2</summary>


Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc 2020-06-04 --end 2020-07-17 --script=./test.bash --without-cargo 
```
</details>

**Comment by jyn514** [comment]
That rollup includes both https://github.com/rust-lang/rust/pull/73771 and https://github.com/rust-lang/rust/pull/73566; of the two I think 73771 is the more likely culprit.

**Comment by jyn514** [comment]
Marking as P-high [as discussed by the prioritization WG](https://zulip-archive.rust-lang.org/245100tcompilerwgprioritizationalerts/54163Iprioritize75588MissingImplementorsfortraits.html).

**Comment by johnw42** [comment]
I found another example of what I assume is the same bug: the doc page for `core::iter::FromIterator` is missing most of the implementations, perhaps all the ones outside of `core`; the only ones shown are for `()`, `Result`, and `Option`. For example of what's missing, the doc page for `alloc::borrow::Cow` has 5 `Cow`-related implementations of `FromIterator`.
