### ISSUE TITLE
Error on float printing

### ISSUE THREAD

**Issue by unguest** [rust-lang/rust#75583]
I'm on Ubuntu 20.04 FF and I tried this tinny code : 
```rs
fn main() {
    const cst: f64 = 0.14827398278972343; // max precision allowed by f64
    println!("{}", cst);
}
```
Instead of printing 43 at the very end, it prints 42... => is that a language bug or something related to the hardware/OS ?

Cheers,

**Comment by lzutao** [comment]
Python3 prints the same result, so this might be hardware/rounding rules:
```python
>>> 0.14827398278972343
0.14827398278972342
```

**Comment by unguest** [comment]
Ok, nice ! I'll look at it in details. Thanks.

**Comment by varkor** [comment]
Closing as expected behaviour: this is a precision issue with floating-point, not Rust.
