### ISSUE TITLE
At opt-levels <= 1 the arithmetic operation methods do not get inlined, preventing other optimisations

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#75598]
Consider code like this:

```rust
#![feature(core_intrinsics)]

pub fn method(a: usize, b: usize) -> usize {
    a.wrapping_sub(b)
}

pub fn intrinsic(a: usize, b: usize) -> usize {
    std::intrinsics::wrapping_sub(a, b)
}
```

[compiler explorer](https://godbolt.org/z/5sq1a7)

at `-Copt-level=1` and lower, the generated assembly for versions with the method call will generate a function call, rather than direct operation. Once the inlining fails, other optimisations that could be done are inhibited, especially at -Copt-level=1`.

More generally speaking, I wonder if we might want to make these methods have a special annotation that would make the compiler generate the instructions directly much like it does for intrinsics right now. These seem like basic enough that `#[inline(always)]` might not be good enough (it being just a hint) and also possibly more expensive than necessary (something needs to do the inlining still).

**Comment by alecmocatta** [comment]
Relatedly, https://github.com/rust-lang/rust/issues/74362 is an instance where not inlining a function that wraps an intrinsic inhibits DCE.

**Comment by bugadani** [comment]
My naive assumption is that `inline(always)` would inline shorter functions more eagerly, since the relative cost of a function call is higher and also shorter functions don't contribute as much to binary bloat. Is this not the case?

**Comment by Lokathor** [comment]
Using the compiler explorer link, it seems like simply tagging the `wrapping_` operations as `#[inline(always)]` will make them get inlined even at opt-level=0

**Comment by AngelicosPhosphoros** [comment]
>These seem like basic enough that #[inline(always)] might not be good enough (it being just a hint) and also possibly more expensive than necessary (something needs to do the inlining still).

This is not true for `opt-level=1`, AFAIK. In this mode, LLVM runs [always-inline](https://llvm.org/docs/Passes.html#always-inline-inliner-for-always-inline-functions) which inlines functions without much thinking.
In higher optimization levels this pass doesn't run and `inline(always)` becomes hint.

**Comment by AngelicosPhosphoros** [comment]
Example of prevented optimization.
[godbolt](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(fontScale:14,fontUsePx:'0',j:1,lang:rust,selection:(endColumn:16,endLineNumber:8,positionColumn:16,positionLineNumber:8,selectionStartColumn:16,selectionStartLineNumber:8,startColumn:16,startLineNumber:8),source:'%23!!%5Bfeature(core_intrinsics)%5D%0A%0Apub+fn+method_a(a:+u16)%7B%0A++++let+b+%3D+a+as+u32%3B%0A++++assert_eq!!(b.wrapping_add(1),+b%2B1)%3B%0A%7D%0A%0Apub+fn+method_b(a:+u16)%7B%0A++++let+b+%3D+a+as+u32%3B%0A++++assert_eq!!(std::intrinsics::wrapping_add(b,+1),+b%2B1)%3B%0A%7D'),l:'5',n:'0',o:'Rust+source+%231',t:'0')),k:45.838779956427025,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:nightly,filters:(b:'0',binary:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'1',intel:'1',libraryCode:'1',trim:'1'),fontScale:14,fontUsePx:'0',j:1,lang:rust,libs:!(),options:'-Copt-level%3D1',selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'rustc+nightly+(Editor+%231,+Compiler+%231)+Rust',t:'0')),k:31.619429924200652,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(compiler:1,editor:1,fontScale:14,fontUsePx:'0',wrap:'1'),l:'5',n:'0',o:'%231+with+rustc+nightly',t:'0')),k:22.54179011937233,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4)
