### ISSUE TITLE
Weird interaction between integer literals and traits

### ISSUE THREAD

**Issue by joonazan** [rust-lang/rust#75601]
I changed some code to use usize instead of u8 and it stopped compiling. I tracked the reason down to `let x: usize = 1.into()`.

It gives the error `error[E0277]: the trait bound `u32: std::convert::From<i32>` is not satisfied`.

u8, i8, i64 and i32 work for whatever reason.

Try it here https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=f1d0c42944d9e95fb0cd9ef9b4c3d69f

**Comment by jonas-schievink** [comment]
u32 has several `From` impls that could produce the value, while u8 only has the reflexive one, so this seems to work as expected.
