### ISSUE TITLE
Range and friends don't implement Ord/PartialOrd

### ISSUE THREAD

**Issue by c410-f3r** [rust-lang/rust#75607]
Couldn't find an issue about it. Is there a reason for such limitation?

**Comment by Lonami** [comment]
It's not clear to me how a "range" is comparable to others. One could argue `8..10 < 0..6` because the first has less elements. Is `2..4` less than `0..8`? Or `5..7` greater than `4..9`? I think this would be too confusing, and I can't think of any motivating example for this.

**Comment by c410-f3r** [comment]
If one approach isn't generic enough, then it is possible to create auxiliary methods for each criteria.

```rust
fn partial_cmp_lexicographic(&self, other: &Self) -> PartialOrd;
fn partial_cmp_number_of_elements(&self, other: &Self) -> PartialOrd;
```

But it is very unlikely to be accepted and looks like most ppl don't care about `Ord/PartialOrd` for ranges.
Thanks for your suggestion, it is probably the way to go for now.
