### ISSUE TITLE
--emit=llvm-ir produces code that LLVM can't compile

### ISSUE THREAD

**Issue by bugadani** [rust-lang/rust#75617]
[Example](https://rust.godbolt.org/z/KbjdvG)
[Example with optimizations enabled](https://rust.godbolt.org/z/exn63o)

What I expected: LLVM successfully compiling the IR (which is the same as rustc emits)
What happened: various errors depending on the rustc optimization settings.

**Comment by lzutao** [comment]
Because the IR you copied is incomplete.
![image](https://user-images.githubusercontent.com/15225902/90386405-b98a4780-e0ae-11ea-9561-ad37c3085ec9.png)

**Comment by bugadani** [comment]
Ah, shoot, thanks!
