### ISSUE TITLE
Switch rustdoc from `lexer::StringReader` to rustc_lexer

### ISSUE THREAD

**Issue by matklad** [rust-lang/rust#75619]
In #75528, we would like to tweak the structure of the tokens rustc uses. One of the components which heavily depends on the current structure is `rustdoc` (`html` and `check_code_block_syntax` module use `lexer::StringReader`).

I think, for this issue and in general, it makes sense to switch `rustdoc` over to `rustc_lexer`, which produces lower-level guaranteed lossless tokens, which look like a better fit for the task of syntax highlighting. 

I plan to do this refactor myself, but I want to check with @rust-lang/rustdoc if this is a good idea. 

EDIT: cc https://github.com/rust-lang/rust/issues/63284

**Comment by Manishearth** [comment]
sgtm

**Comment by GuillaumeGomez** [comment]
I'm fine with it as well. :)

**Comment by matklad** [comment]
BTW, is there some chat room for rustdoc team on zulip on discord? I'd like to ask some questions :)

**Comment by GuillaumeGomez** [comment]
There is one on discord (simply called "rustdoc").

**Comment by jyn514** [comment]
It's linked at https://www.rust-lang.org/governance/teams/dev-tools#rustdoc (which is I agree pretty hard to find).

Also the text there is wrong and mentions docs.rs, we should probably fix that.
