### ISSUE TITLE
wasm emscripten tests for std/alloc/core/etc not running

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#75633]
We attempted to re-enable these in #75380 but that failed with a [linker error](https://github.com/rust-lang/rust/pull/75380#issuecomment-672194922).

**Comment by camelid** [comment]
@khionu Do you still want to work on this? If not, you can release your assignment with `@rustbot release-assignment`.

**Comment by khionu** [comment]
@rustbot release-assignment

Sorry about this :/ Had stuff come up. Will try to contribute at a later point.

**Comment by camelid** [comment]
That’s okay! :)

**Comment by pietroalbini** [comment]
We discussed this today in the infrastructure team meeting. Nobody has expressed interest in months to address this, and this is a tier 2 target (which is not required to run tests). Closing the issue.
