### ISSUE TITLE
Can't `as` cast Void to usize 

### ISSUE THREAD

**Issue by digama0** [rust-lang/rust#75647]
```rust
enum Void { }
fn void_as_usize(x: Void) -> usize { x as usize } // fails, non-primitive cast
```
As reported on Zulip: https://rust-lang.zulipchat.com/#narrow/stream/122651-general/topic/void.20as.20usize

This works for simple enums with one or more variants, but for zero it fails, possibly due to interaction with `#[repr(C)]`. This kind of code can come up in macro code.

cc @RalfJung

**Comment by RalfJung** [comment]
I think for zero-variant enums it fails mostly as an oversight. This doesn't even have to generate any MIR as it is unreachable code anyway.

Nominating for lang team discussion.

**Comment by digama0** [comment]
From the head comment at https://github.com/rust-lang/rust/blob/7189ca604ad5d9dfff7d0aeef6a42c89d73cbac7/src/librustc_typeck/check/cast.rs#L10, I infer that this is indeed only designed to work with C-style enums. My proposal would be to add another cast category saying that empty enums can `as` cast to anything, desugaring to `match x {}`.

**Comment by RalfJung** [comment]
No, enum casts have nothing to do with C-style enums. This works:
```rust
pub enum MirPhase {
    Build = 0,
    Const = 1,
    Validated = 2,
}

fn main() {
    let _val = MirPhase::Build as usize;
}
```

**Comment by RalfJung** [comment]
Oh, the comment says "C-like". That's not the same as `repr(C)`.
"C-like" just means that all enum variants have no data. This is satisfied by `Void` -- there are no enum variants, and thus all of them have no data.

**Comment by digama0** [comment]
Here's the offending check:
https://github.com/rust-lang/rust/blob/668ef72f4429059240ee361a2f0f748558a5326f/src/librustc_middle/ty/mod.rs#L2497-L2499

It seems that the "payload-free" check is not just "all variants have no data" but also "it is not empty". I would hesitate to change this definition because it's likely to affect C-like enum handling elsewhere, but maybe `CastTy` can get another class specifically for uninhabited enums.

**Comment by RalfJung** [comment]
I'd argue a no-variant enum is payload-free. But all uses of that function should be carefully checked.

Adding a new case to `CastTy` seems like a hack to me.

**Comment by scottmcm** [comment]
These were historically known as "C-like" enums, and `Void` is not C-like.  From GCC:
```c
<source>:1:12: error: expected unqualified-id at end of input

    1 | enum Void {}

      |            ^

Compiler returned: 1
```

> This kind of code can come up in macro code.

Can you maybe elaborate more on this?

**Comment by RalfJung** [comment]
Sure, C might not permit them, but I don't see how that's a reason to disallow `as` casts in Rust.

**Comment by lzutao** [comment]
I mean, what value does `Void as usize` have that will make sense?

**Comment by Aaron1011** [comment]
It's not actually reachable, so it could just typecheck without actually ever needing to produce a value.

**Comment by digama0** [comment]
@lzutao It can compile the same way as `match x {}`, which is to say, produce no code and mark the remainder of the function as unreachable. Compiling to `0` would also work for all numeric types that this could target, although then `x` appears unused which might cause other unintended behaviors in the compiler.

**Comment by lzutao** [comment]
The compiler marks `match x {}` code as error. What do you mean ?

> It can compile the same way as `match x {}`, which is to say, produce no code and mark the remainder of the function as unreachable

Unreachable is unsafe, does it mean that `Void as usize` is unsafe.

**Comment by digama0** [comment]
@lzutao  This uses no unsafe code:
```rust
fn void_as_usize(x: Void) -> usize {
    match x {}
}
```
Here the code after the match statement (if there was any) would be unreachable, and this requires no unsafe code. Basically `x` is an impossible value, therefore the function cannot be called in the first place and no code need be generated.

**Comment by lzutao** [comment]
Thanks, I got that part now. But the question raised by [Scott still remain](https://github.com/rust-lang/rust/issues/75647#issuecomment-679277980): What is the concrete example of macros that have use cases for `Void as usize` ?

Also, `Void` is a never type, if `Void is usize` allowed, would we want to make any operations on `Void` unreachable?

**Comment by digama0** [comment]
The actual macro where this came up was a safe wrapper that declares an int-like enum and an array indexed by the enum. Roughly, it creates a type `enum Foo { User, Defined }` and `struct FooVec<T>([T; Foo::LEN])`, and then the `Index<Foo>` implementation for `FooVec` uses `vec.0[i as usize]` where `i: Foo`. When `Foo` has zero elements, this causes the macro to produce malformed code.

It is possible to work around this issue by explicitly checking for this case, but I don't really see a reason for it not to work in the first place.

> would we want to make any operations on Void unreachable?

Any operation on Void *is* unreachable. That means that the compiler can do whatever it wants to for codegen here because it doesn't matter, the function is not callable. But from a typing point of view, I think that `(x: Foo) as usize` should have type `usize`, not `!`.

**Comment by RalfJung** [comment]
It's no surprise that macros run into this -- this happens any time that we have special exceptions. "`enum`s without fields can be cast to integers, *except* if the enum has 0 variants" is such a special exception, and from a language design perspective it has no reason to exist.

Not sure what the next step here is -- probably an RFC? This is a language extension after all.

**Comment by nikomatsakis** [comment]
Discussed in the @rust-lang/lang meeting today:

* We agreed that this seems like a harmless extension (specifically: permitting zero variant enums to be `as` to a usize).
* We don't feel an RFC is required and we would recommend somebody creating a PR that fixes this and nominates the PR for lang-team consideration, we can do an FCP directly on the PR.

**Comment by Mark-Simulacrum** [comment]
I have opened https://github.com/rust-lang/rust/pull/76199 to fix this issue.
