### ISSUE TITLE
Intra-doc links should work for deref methods

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#75643]
I tried this code:

```rust
/// [`get`]: std::vec::Vec::get
pub fn f() {}
```

I expected to see this happen: A link to https://doc.rust-lang.org/std/vec/struct.Vec.html#method.get

Instead, this happened: The link wasn't resolved, because `get` is a method on slices, not `Vec` itself.

**Comment by jyn514** [comment]
Note that this currently means `Vec::get` can't be linked to at all because of https://github.com/rust-lang/rust/issues/63351.

**Comment by GuillaumeGomez** [comment]
I need to get back to the fix and understand what changes between the two.

**Comment by jyn514** [comment]
FWIW I don't think this ever worked, it just wasn't implemented.

**Comment by GuillaumeGomez** [comment]
It never did, I was referring to my PR to fix primitive discoverability.

**Comment by Manishearth** [comment]
I'm against this, `Vec::get` does not exist and does not work in code. I think we should maybe just bite the bullet and allow `slice` to exist as a string.

**Comment by jyn514** [comment]
I'm ok with saying we should fix linking to primitives instead, but it's not as simple as 'allow slice to exist as a string', see https://github.com/rust-lang/rust/issues/63351#issuecomment-676760725.

**Comment by camelid** [comment]
> I'm against this, `Vec::get` does not exist and does not work in code. I think we should maybe just bite the bullet and allow `slice` to exist as a string.



> I'm ok with saying we should fix linking to primitives instead, but it's not as simple as 'allow slice to exist as a string', see [#63351 (comment)](https://github.com/rust-lang/rust/issues/63351#issuecomment-676760725).

`slice::get` works now, so should this issue be closed?

**Comment by jyn514** [comment]
Yeah, that seems reasonable.
