### ISSUE TITLE
Improve RFC/Issue browsing and open source project collaboration

### ISSUE THREAD

**Issue by mankinskin** [rust-lang/rust#75650]
Hello, I am very inspired by the whole Rust project, and can see it going a very long way. I would like to contribute, to advance the project further and take influence. As a newcomer, I find it hard to get an overview of the project state. What are the suggestions (RFCs), what state are there in, where can I find the related discussions, what work has been done related to those issues, to give some examples.

To me it seems that there is this github organization (rust-lang), where basically all collaborative work is submitted. RFCs, Issues, code, discussions, all are managed here. However I feel that Github is not an ideal tool to organize open source project work. It is definitely not as good as it could be.

Improving this could lead to an increase in development productivity, community participation and security for the project. That is why I would like to start an initiative to design and build a new platform for open source project collaboration, built originally for the Rust Project, but of course more generally applicable.

To demonstrate more clearly what I mean, I would like to solve the following problems:
- defining project goals: What kind of conditions define the satisfaction of a goal i.e the solution to a problem?
- relating goals to each other: how do goals depend on/relate to each other?
- monitoring work on goals: What goals does a specific resource (code, text, chat post, video, ...) relate to?
- tracking progress on goals: Which work has been done and which sub-goals are still required to satisfy the goal?
- tracking consensus between people: Which goals do people commit to? Where are conflicts/collaborations?
- reducing noise: what are the final results of the discussion? What is the current state of the issue?
- structured knowledge base: Q/A, structured guides/tutorials, parallel to the current resource state of the project.

Most of these problems are currently solved manually, or by using the features Github or other services provide. Any feedback or expansion on the (wish-)list above would be very appreciated.

I am already working on a [project](https://github.com/mankinskin/budget-app), which somewhat encompasses this, but I would like to build something more specialized, which actually satisfies a demand. I personally have had the demand for a more powerful project management platform like this, and I would be glad if people shared their thoughts on this, and if there were a demand for this in the Rust project.

**Comment by Lonami** [comment]
I think this might be better suited for discussion in the https://internals.rust-lang.org forum.

**Comment by mankinskin** [comment]
Sure, right. I wasn't thinking.
