### ISSUE TITLE
Add `Cow::to_borrowed(&self) -> Cow<T>` that creates a Cow::<T>::Borrowed from a Cow

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang/rust#75686]
Via https://twitter.com/blinsay/status/1295767219255869452

Implementation would look something like:

```rust
impl Cow {
    fn to_borrowed(&self) -> Cow<T> {
        match cow {
            Cow::Owned(b) => Cow::Borrowed(b.borrow()),
            Cow::Borrowed(b) => Cow::Borrowed(b),
        }
    }
}
```

Thoughts? I'd be happy to open a PR for this if the Library Team is happy with it

**Comment by blinsay** [comment]
After looking at how [Cow implements Deref](https://github.com/rust-lang/rust/blob/1.45.2/src/liballoc/borrow.rs#L320-L330), it seems like maybe I could have be doing something like this:

```rust
let v = vec![1usize, 2, 3];
let cow  = Cow::from(v);
let also_a_cow = Cow::Borrowed(&*cow);
```
 
If that's preferred over adding a method, it'd be awesome to have an additional example or some documentation pointing this out.

**Comment by lzutao** [comment]
What is the practical use case of this method?

**Comment by Enselic** [comment]
Triage: Closing as won't fix since a relevant question has remained unanswered for 2 years.

**Comment by saethlin** [comment]
Issues like this should be a libs-api ACP: https://github.com/rust-lang/libs-team/issues/new?assignees=&labels=api-change-proposal%2C+T-libs-api&projects=&template=api-change-proposal.md&title=%28My+API+Change+Proposal%29
