### ISSUE TITLE
Replace `once_cell` crate from `librustc_datastructures` with an (unstable) impl from std

### ISSUE THREAD

**Issue by matklad** [rust-lang/rust#75700]
After https://github.com/rust-lang/rust/pull/75648 is merged, usage of `once_cell` in this module:

https://github.com/rust-lang/rust/blob/5b04bbfcbb79ed7325ea2b580458a80d95da6bbb/src/librustc_data_structures/sync.rs

should be replaced by `std::[OnceCell|SyncOnceCell]`. The dependency from corresponding Cargo.toml can be removed afterwards. 

It *might* make sense to request a perf run, as crates.io version uses parking_lot, while the standard one uses std mutex, but I expect the difference to not matter -- fast path is equivalent for both.

**Comment by matklad** [comment]
#75648 is done!

Though, I am not unsure if we maybe should wait until it tickles down to beta? Not sure how bootstraping works with libstd, I guess, we can just try and see if the build fails.

**Comment by matklad** [comment]
ping @marmeladema, this is ready to be implemented.

**Comment by marmeladema** [comment]
I'll start soon! Sorry I got a bit overwhelmed with work. If in the next couple of days I haven't replied feel free to re-assign.

**Comment by marmeladema** [comment]
On it!

**Comment by marmeladema** [comment]
@matklad once this is merged, should other sub-crates that depend on `once_cell` also be updated? Like `librustc_interface` for example. Also, what about `lazy_static`? Some usage can probably be replaced by `Lazy`.

**Comment by matklad** [comment]
We definitely should actively remove once_cell crate from all rustc’s crates, because having two difference sources of the same data structure feels bad.

Replacing lazy_static with std::lazy would also be good!

**Comment by marmeladema** [comment]
> We definitely should actively remove once_cell crate from all rustc’s crates, because having two difference sources of the same data structure feels bad.
> 
> Replacing lazy_static with std::lazy would also be good!

I'll try to take of it once this issue is fixed :+1:
