### ISSUE TITLE
i32::rem_euclid returns negative remainder

### ISSUE THREAD

**Issue by Hakuyume** [rust-lang/rust#75726]
I tried this code:

```rust
fn main() {
    println!("{}", -3_i32.rem_euclid(2));
}
```

I expected to see this happen:
It should print `1` since the documentation (https://doc.rust-lang.org/std/primitive.i32.html#method.rem_euclid) says "Calculates the least *nonnegative* remainder".

Instead, this happened:
It prints `-1`.

### Meta
I used Rust Playground (https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=e8d90ed68a54012341d2e25c8b225da2).
Both stable (1.45.2) and nightly (2020-08-18) have the same behavior.

**Comment by ecstatic-morse** [comment]
Method calls have higher precedence than unary `-`. You want `(-3).rem_euclid(2)`, which returns `1` as expected.

**Comment by Hakuyume** [comment]
I see. Thank you!
