### ISSUE TITLE
Accessing an associated constant with the same name as an enum variant doesn't work

### ISSUE THREAD

**Issue by Aloso** [rust-lang/rust#75724]
The following code works:

```rust
enum Enum {
    Variant {}
}

impl Enum {
    const Variant: Enum = Enum::Variant {};
}
```

However, accessing the associated constant [does not](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=58852435af0d0d9b4e68bd451584be02):

```rust
let _ = Enum::Variant;
// error[E0423]: expected value, found struct variant `Enum::Variant`
```

### Explanation why I think this should work

Most items are in one of three namespaces/universes: The type namespace, the value namespace, and the macro namespace. For example, regular structs are in the type namespace, whereas constants are in the value namespace, so a struct and a constant can share the same name (this is also how unit structs are desugared):

```rust
struct S {}
const S: S = S {};

let _: S = S;
```

I expected the same to work for enum variants as well.

If you don't intend to fix this, please consider changing the error message, as the phrase "struct variant" can be misleading.

### Meta
It can be reproduced on stable, beta and nightly. [See playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=58852435af0d0d9b4e68bd451584be02).

**Comment by Dylan-DPC** [comment]
This code now compiles fine so closing this
