### ISSUE TITLE
`mir-opt/instrument_coverage.rs` test needs profiler support

### ISSUE THREAD

**Issue by tesuji** [rust-lang/rust#75735]
`mir-opt/instrument_coverage.rs` test needs profiler support:
https://github.com/rust-lang/rust/blob/5f6fcad6449aabad3c29c65c1738f8eab89c03ce/src/test/mir-opt/instrument_coverage.rs#L5
However, profiler is disable by default:
https://github.com/rust-lang/rust/blob/5f6fcad6449aabad3c29c65c1738f8eab89c03ce/config.toml.example#L220

So when the test failed I can't notice it in my machine.

P/S: Does profiler need support from LLVM ? I am using local LLVM if that count.

_Originally posted by @lzutao in https://github.com/rust-lang/rust/pull/75670#issuecomment-676844219_

**Comment by Enselic** [comment]
Triage: If the problem is that it's disabled by default, what's the problem with enabling it in your config?

**Comment by tesuji** [comment]
I have no ideal about this issue since then.
I'd close this issue in this case.

**Comment by Enselic** [comment]
Thanks for getting back, let's close as obsolete then.

**Comment by jieyouxu** [comment]
That test no longer has `//@ needs-profiler-suppport`, FTR

https://github.com/rust-lang/rust/blob/3c1e750364012e78dcc46e5c96973fab42c7b295/tests/mir-opt/coverage/instrument_coverage.rs#L6
