### ISSUE TITLE
Pretty-printing adds additional parentheses, breaking the proc-macro reparse check

### ISSUE THREAD

**Issue by Aaron1011** [rust-lang/rust#75734]
The following code:

```rusthttps://github.com/Aaron1011
fn main() {
    &|_: u8| {};
}
```

is pretty-printed as:

```rust
fn main() { &(|_: u8| { }); }
```

The extra parenthesis completely change the structure of the re-parsed `TokenStream` (we now have tokens wrapped in a `TokenTree::Delimited`), breaking the pretty-print and reparse check done during proc-macro expansion. This results in an instance of https://github.com/rust-lang/rust/issues/43081.

This behavior was introduced by https://github.com/rust-lang/rust/pull/43742. The PR description states that is intended to "make pprust easier to use with programmatically constructed ASTs." - however, I can't find a concrete example of code that is affected by this.

I see a few possible ways of fixing this:
1. Try to ignore this type of 'unnecessary' parentheses when we compare the original and re-parsed tokens. This seems extremely difficult, since we can't know which parenthesis are necessary without actually parsing the `TokenStream`.
2. Skip inserting these extra parentheses during pretty-printing for proc-macro expansion, but insert them during all other pretty-printing. This should work correctly, but represents yet another hack needed by the pretty-print/reparsing code.
3. Partially revert https://github.com/rust-lang/rust/pull/43742 - we would still insert parenthesis when pretty-printing the HIR, but we would rely solely on `ExprKind::Paren` when pretty-printing the AST. I'm not exactly certain what the consequences of doing this are. Do we ever end up pretty-printing code-generated AST nodes (e.g. from builtin macros), other than when explicitly requested via `-Z unpretty=expanded`?

If we could get it to work without breaking anything, solution 3 seems like the cleanest way of solving this.

cc @petrochenkov

**Comment by dtolnay** [comment]
Also causes https://github.com/dtolnay/async-trait/issues/118. Rustc inserted unnecessary parentheses around the closure before calling async_trait, then lost all the location information on the source tokens and blamed the user for handwriting those unnecessary parentheses.

**Comment by petrochenkov** [comment]
>If we could get it to work without breaking anything

It would break expressions with "virtual parentheses", like `$expr` in `macro_rules`.
`$expr * 2` where `$expr` is `2 + 2` is not the same thing as `2 + 2 * 2`, which would be the pretty-printing result if it weren't adding parentheses.

**Comment by petrochenkov** [comment]
Cases like this could be caught when comparing the original and re-parsed token streams though, because the "virtual parentheses" (`Delimiter::None`) could still be in place in the original token stream.

So we can print without parentheses -> reparse -> compare, and then re-print with parentheses if the comparison fails.
(This may make sense if failing comparisons are rare and don't affect performance.)
