### ISSUE TITLE
mir-opt diff tests for 64/32 bit targets doesn't render as diff in github

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#75746]
mir-opt tests have a `diff` mode where the changes of a specific optimization are shown as a `.diff` file which is rendered as a diff by most tools. For `32/64` bit tests we ended up adding a postfix to the file name (which comes after the `.diff`), and that breaks the tool support. We should change all these tests file-names so they end with `.diff` again.

We should change both https://github.com/rust-lang/rust/blob/5fff3824bc77cd7052e2515f82259e32f8ad1486/src/tools/compiletest/src/runtest.rs#L3172 and https://github.com/rust-lang/rust/blob/5fff3824bc77cd7052e2515f82259e32f8ad1486/src/tools/compiletest/src/runtest.rs#L3190 to insert the `bitsize` before the `.diff` or `.mir` respectively.

After you've run `--bless` for both 32 bit and 64 bit, you also need to change https://github.com/rust-lang/rust/blob/5fff3824bc77cd7052e2515f82259e32f8ad1486/src/tools/compiletest/src/runtest.rs#L3147 and https://github.com/rust-lang/rust/blob/5fff3824bc77cd7052e2515f82259e32f8ad1486/src/tools/compiletest/src/runtest.rs#L3152 

Do not do the last step before having run `--bless`, otherwise you'll have to figure out what files to rename and do it manually. This way you get `--bless` to do it for you.

cc @rust-lang/wg-mir-opt

**Comment by mati865** [comment]
Maybe it could be handled by https://github.com/rust-lang/rust/blob/master/.gitattributes as an alternative?

**Comment by oli-obk** [comment]
Heh, neat idea, let's try that out first!

**Comment by mati865** [comment]
It did not work 🤷

**Comment by aDotInTheVoid** [comment]
I'm working on this.
