### ISSUE TITLE
Missing suggestion "remove semicolon" for mismatched types compile error

### ISSUE THREAD

**Issue by PrototypeNM1** [rust-lang/rust#75759]
I tried this code:

```rust
fn return_tuple() -> (f32) {
    (3.1415);
}
```

I expected to see this happen:

A error message suggesting to "consider removing this semicolon" with the relevant code highlighted as in prior releases.

Instead, this happened:

```
error[E0308]: mismatched types
 --> src/lib.rs:1:23
  |
1 | fn return_tuple() -> (i32) {
  |    ------------       ^^^ expected `i32`, found `()`
  |    |
  |    implicitly returns `()` as its body has no tail or `return` expression

```

### Meta

`rustc --version --verbose`:
```
1.45.2
1.47.0-nightly (2020-08-19 32c654a9795b0d88541e)
```

Issue likely relates to issue https://github.com/rust-lang/rust/issues/67971 and PR https://github.com/rust-lang/rust/pull/71894.

This is a significant issue as it's a repeat stumbling block for new users of Rust. See https://www.reddit.com/r/rust/comments/i6yqng/hey_rustaceans_got_an_easy_question_ask_here/g28ambz.

**Comment by lzutao** [comment]
If you want to return a tuple of a f32, try:
```rust
fn return_tuple() -> (f32,) {
    (3.1415);
}
```

**Comment by PrototypeNM1** [comment]
I oversimplified the example. [Here](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=33510d330abb8273f7e2f804e5098e7e) is the motivating example.

**Comment by jonas-schievink** [comment]
The suggestion would be incorrect for that playground example. For the original example in the issue, the "help: consider removing this semicolon" *is* emitted.

**Comment by PrototypeNM1** [comment]
> The suggestion would be incorrect for that playground example. For the original example in the issue, the "help: consider removing this semicolon" _is_ emitted.

Ack, thought I had checked that. Sorry for the noise.

**Comment by PrototypeNM1** [comment]
I do wonder if this still warrants investigation. The error message as is is not helpful for people not already familiar with Rust syntax. With the (incorrect) semicolon removal suggestion a new user can start to unravel the error (remove semicolon, identify they're returning the wrong types).

Currently they have to reason through two very nonintuitive things, returning () means nothing is being returned, which means there's an unnecessary semicolon at the end, the normal error that would have popped up is not there because the types are wrong if they did remove the semicolon.
