### ISSUE TITLE
Cargo registry paths are leaked in compiled binary

### ISSUE THREAD

**Issue by danielhuang** [rust-lang/rust#75799]
When compiling a rust program, and inspecting the resulting binary, I can see paths of the form `$HOME/.cargo/registry/...` embedded inside.

## Steps to reproduce:

1. Create a new cargo project: `cargo init --bin`
2. Add a dependency to Cargo.toml, for example `regex = "1"`
3. Add some dummy code that uses this dependency, for example
```
use regex::Regex;

fn main() {
    Regex::new(r"{").unwrap();
}
```
4. Run `cargo build --release`
5. Then run `strings target/release/<name> | grep registry` to inspect the binary.

Note that the crate and code example is completely arbitrary — the same behavior occurs with any combination of crates.

Software versions:

* rustc 1.45.2 (d3fb005a3 2020-07-31)
* OS: Linux

**Comment by danielhuang** [comment]
I want to remove all debug related information from the binary when compiling in release mode

**Comment by NickeZ** [comment]
Could someone label this `A-reproducibility`?

**Comment by jyn514** [comment]
Duplicate of https://github.com/rust-lang/rust/issues/40552.

**Comment by liesauer** [comment]
> I want to remove all debug-related information from the binary when compiling in release mode.

+1

**Comment by jerryshell** [comment]
> I want to remove all debug-related information from the binary when compiling in release mode.

Yep, Rust is "memory-safe" language, but is not "developer-safe" language.

In some highly sensitive projects, registry paths leaked in binary can cause a lot of problems. Because the registry path contains the developer's user name.
