### ISSUE TITLE
Highlight crate links as normal links with --enable-index-page

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#75823]
Rustdoc highlights most links in blue, for example module links:

![image](https://user-images.githubusercontent.com/37223377/90968788-5d0b9b80-e4a5-11ea-9fb8-6fa660beef24.png)

But it does not highlight the links on the docs index page:

![image](https://user-images.githubusercontent.com/37223377/90968798-7ad90080-e4a5-11ea-8054-156631283c01.png)

Generally links are highlighted in blue (or some other color) on websites and the rest of Rustdoc highlights links so it would be more consistent to highlight these links.

**Comment by camelid** [comment]
The index page is https://doc.rust-lang.org/nightly/nightly-rustc/ and the page that shows the modules is https://doc.rust-lang.org/nightly/nightly-rustc/rustc_ast/index.html.

**Comment by camelid** [comment]
@jyn514 Do you know how to get to the index page (https://doc.rust-lang.org/nightly/nightly-rustc/) with docs for other crates? I can't seem to find the "List of all crates" in docs for other projects.

**Comment by jyn514** [comment]
I don't think this is actually generated by rustdoc. This looks like bootstrap is passing `--index-page`.

**Comment by jyn514** [comment]
In which case this should be a feature request for bootstrap, not a bug report for rustdoc.

**Comment by camelid** [comment]
Hmm, but it's generated by Rustdoc here: https://github.com/rust-lang/rust/blob/9d606d939a61c2f4c7bb4d89d959b60a53f50241/src/librustdoc/html/render/mod.rs#L1062-L1072

**Comment by jyn514** [comment]
Oh interesting. It's still not on by default, you need to pass `--enable-index-page`, but it's definitely a rustdoc issue.
