### ISSUE TITLE
Suggest Stream<Item = String> when specifying the item using the trait syntax.

### ISSUE THREAD

**Issue by Darksonn** [rust-lang/rust#75829]
This issue describes a suggestion I wish the compiler made. Given the following code:
```rust
use futures::stream::Stream;

struct Foo<T>
where
    T: Stream,
    <T as Stream>::Item: String,
{
    t: T,
}
```
The compiler produces this error:
```
error[E0404]: expected trait, found struct `String`
    --> src/lib.rs:6:26
     |
6    |       <T as Stream>::Item: String,
     |                            ^^^^^^ help: a trait with a similar name exists: `ToString`
```
It would be nice if the compiler suggested changing it to
```rust
use futures::stream::Stream;

struct Foo<T>
where
    T: Stream<Item = String>,
{
    t: T,
}
```
The same applies to impl blocks, that also don't produce the suggestion.

**Comment by estebank** [comment]
I have a hacky prototype with the following output:

<img width="778" alt="Screen Shot 2020-09-23 at 9 59 01 PM" src="https://user-images.githubusercontent.com/1606434/94103010-55af1900-fde8-11ea-92dc-6959100f761b.png">

Funnily enough, there was no existing test that triggered this.

For the (nightly only) `where <T as Bar>::Baz = String` case, we already provide a suggestion:

<img width="700" alt="Screen Shot 2020-09-23 at 10 06 15 PM" src="https://user-images.githubusercontent.com/1606434/94103283-146b3900-fde9-11ea-8c08-fabba7029af9.png">
