### ISSUE TITLE
Ability to configure cargo run configuration

### ISSUE THREAD

**Issue by Adverg** [rust-lang/rust#75854]
I'm developing a program that is required to pass command line options and set environment variables. I'd like to have the ability to config `cargo run` so it sets the correct environment since running the program otherwise does not make sense and some error will be reported.

Would it be possible to add the abitility to configure cargo run?

**Comment by jonas-schievink** [comment]
Feature requests for Cargo should go here: https://github.com/rust-lang/cargo
