### ISSUE TITLE
min_const_generics allows defining new types in const argument

### ISSUE THREAD

**Issue by Aaron1011** [rust-lang/rust#75864]
I recently discovered that the following code compiles:

```rust
#![feature(min_const_generics)]
struct Bar<const C: bool>;

struct Foo {
    outer: Bar<{
        struct Inner {
            field: bool
        }
        true
    }>,
}
```

It looks like an `AnonConst` is allowed to contain arbitrary expressions (as long as no const or type parameters are used), which means that new types can be defined.

I'm not certain whether this should be allowed or not. However, I haven't seen this discussed before, so I thought it was worth bringing up.

**Comment by scottmcm** [comment]
Feels to me like this, at the very least, shouldn't be **min**_const_generics.

(I'd personally be happy to block it from `const_generics` too, but there are consistency arguments that's it's not unreasonable to allow types in there, since they're allowed in other blocks.)

**Comment by petrochenkov** [comment]
Items were allowed in constants expressions since forever, not sure why const generic arguments should be any different.
```rust
#![allow(unused)]

type A = [u8; { struct S; 1 }]; // OK since 1.0

fn main() {}
```
https://rust.godbolt.org/z/Ts6YT1

**Comment by Aaron1011** [comment]
@petrochenkov: Wow, I didn't realize that we already supported that.

I'm going to close this issue - since we already supprt this in the array repeat position, there's nothing to gain from banning it in other positions.
