### ISSUE TITLE
Ayu theme hover not noticible

### ISSUE THREAD

**Issue by pickfire** [rust-lang/rust#75880]
![image](https://user-images.githubusercontent.com/4687791/91056928-25455500-e659-11ea-8e47-1e965b8cf4d9.png)

Note that "Ayu" is already highlighted, it happens to mdbook too.

CC @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
The contrast is too small indeed. Want to send a fix?

**Comment by pickfire** [comment]
I will pass on this, I sent too many pull requests today, I can do this maybe another day (a few days) or if anyone is interested can take up this task before I do.

**Comment by GuillaumeGomez** [comment]
I'll certainly send a PR tomorrow then.
