### ISSUE TITLE
Unsizing coercion does not normalize associated types in structs.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#75899]
Example code I'd expect to work ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=da6411306c5266f6010ff5172838a2d3)):
```rust
// NOTE: this is only needed for coerce_tuple, you can remove both for a stable version.
#![feature(unsized_tuple_coercion)]

trait Trait {}
impl<T> Trait for T {}

trait Noop {
    type Assoc: ?Sized;
}
impl<T: ?Sized> Noop for T {
    type Assoc = T;
}

// Both of these work:
fn coerce<T: Trait>(x: &<T as Noop>::Assoc) -> &<dyn Trait as Noop>::Assoc { x }
fn coerce_tuple<T: Trait>(x: &(String, <T as Noop>::Assoc)) -> &(String, <dyn Trait as Noop>::Assoc) { x }

// But this doesn't:
struct NoopNewtype<T: ?Sized + Noop>(T::Assoc);
fn coerce_newtype<T: Trait>(x: &NoopNewtype<T>) -> &NoopNewtype<dyn Trait> { x }
```

(in case the example above seems artificial, the [realistic one](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=b3ef269c501b3e6478275335f7922dba) I've reduced this from involves using an associated trait to add `Option` around sized types, but not `dyn Trait`, since `Option<dyn Trait>` wouldn't itself work)

<hr/>

I'd expect `coerce_newtype` to work because `<T as Noop>::Assoc: Unsize<<dyn Trait as Noop>::Assoc>` should hold, after normalization to `T: Unsize<dyn Trait>` (which holds here because `T: Trait`), but nothing performs that normalization before coercion gives up entirely.

Unlike `CoerceUnsized` (where I've been wary of associated types in the past), there should be no weird interactions here, we should be able to largely treat the `struct` as a tuple (and we already ensure the type parameter being changed doesn't show up anywhere else in the `struct`, anyway).

<hr/>

The `coerce` and `coerce_tuple` examples get to normalize *before* asking the trait system about any `CoerceUnsized` or `Unsized` obligations - I wonder if we could just normalize `trait_pred` here? https://github.com/rust-lang/rust/blob/3d6a3ed15823cce765d56952d954e1bd8166dfa7/src/librustc_typeck/check/coercion.rs#L603

But we would have to be careful, because we *are* in a speculative operation, so we would have to use `normalize_associated_types_in_as_infer_ok`, like this other piece of coercion logic: https://github.com/rust-lang/rust/blob/3d6a3ed15823cce765d56952d954e1bd8166dfa7/src/librustc_typeck/check/coercion.rs#L732-L733

cc @mystor (author of the `object-provider` crate where this could be useful) @nikomatsakis

**Comment by eddyb** [comment]
FWIW, this can be worked around [with explicit `Unsize` bounds in the right places](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=b9c7a5f53033f7fe2db73c7c7d5dcb2e) but they're nightly-only and entirely unnecessary if we fix this issue.

**Comment by eddyb** [comment]
Not sure if I should nominate this for compiler team or lang team, but let's try compiler team first.

**Comment by spastorino** [comment]
This [was discussed during today's compiler meeting](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.20meeting.5D.202020-09-03.20.2354818/near/208979165) removing nomination. @eddyb please feel free to keep the discussion going on Zulip or even re-nominating it if you consider a re-discussion important.

**Comment by WaffleLapkin** [comment]
I'd like to work on this. I haven't worked on the compiler yet, so not sure I'll be able to fix this in a reasonable time. But since it's labelled `E-easy` it's worth giving a try, right? Any advice is appreciated :)

@rustbot claim

**Comment by nikomatsakis** [comment]
@WaffleLapkin I'm not sure if that E-easy label is really accurate! That said, you could try to drop by in #wg-traits on Zulip at some point during one of my morning office hours times, if that works for you (9am-10 US Eastern Time, every day but Tuesday), and we could talk it over.

**Comment by SoniEx2** [comment]
is this the same as #50213?

**Comment by WaffleLapkin** [comment]
@SoniEx2 yes, that's the same thing, unsize coercion doesn't properly consider associated types. (maybe it's time for me to return to this 👀 )

**Comment by SoniEx2** [comment]
if there's anything we can do to help, feel free to poke us; we want this for uazu/qcell#37. =^-^=

**Comment by compiler-errors** [comment]
It's been some time this issue was touched, so let me take a look at it.
