### ISSUE TITLE
Can't bound Err for Box<dyn Error>

### ISSUE THREAD

**Issue by heckad** [rust-lang/rust#75920]
```rust
use std::error::Error;

trait MyTrait{
    type Err: std::error::Error;
}

struct S;

impl MyTrait for S{
    type Err = Box<dyn Error>;
}

fn main() {}
```

I expected to see this happen: all good

Instead, this happened: error the size for values of type `(dyn std::error::Error + 'static)` cannot be known at compilation time
It seems that `impl<T: Error> Error for Box<T> {` missed `?Sized` for `T`

**Comment by jonas-schievink** [comment]
Unfortunately it is not possible to fix this (it was attempted multiple times in the past)

**Comment by kennytm** [comment]
> It seems that `impl<T: Error> Error for Box<T> {` missed `?Sized` for `T`

see #75180 for why it is missing (tl;dr: conflicting impl).
