### ISSUE TITLE
Dead link to FromStr from std/string/struct.String.html#method.parse

### ISSUE THREAD

**Issue by rofrol** [rust-lang/rust#75965]
On https://doc.rust-lang.org/std/string/str/trait.FromStr.html there is link `[FromStr]` which prodcues link to

https://doc.rust-lang.org/std/string/str/trait.FromStr.html

but should be

https://doc.rust-lang.org/std/str/trait.FromStr.html

**Comment by ehuss** [comment]
Thanks for the report!  The first link you posted doesn't exist.  Perhaps you meant something like https://doc.rust-lang.org/std/string/struct.String.html#method.parse?  If so, that has been fixed on the beta docs (https://doc.rust-lang.org/beta/std/string/struct.String.html#method.parse) which should reach the stable channel tomorrow.

**Comment by rofrol** [comment]
Yes. Thanks.
