### ISSUE TITLE
Rustdoc show rustc_layout

### ISSUE THREAD

**Issue by pickfire** [rust-lang/rust#75988]
It would be good to be able to understand the size, abi and debug stuff related to `rustc_layout`. Instead of needing users to manually add `#[rustc_layout(debug)]` to `struct` and `enum` on nightly, why not just show it on rustdoc generated pages, this may only be limited to concrete struct and enum, otherwise it may not be as useful since currently `rustc_layout` is not so useful on those.

CC @rust-lang/rustdoc

**Comment by jonas-schievink** [comment]
If this ends up getting implemented, please make sure to clarify that the layout is implementation-defined and unstable unless `#[repr]` is used.

**Comment by pickfire** [comment]
Given that this have been there for quite some time and even rust-analyzer can show type size information on hover, should we stabilize this?
