### ISSUE TITLE
lldb debugging is not working from version 1.46

### ISSUE THREAD

**Issue by douglascorrea** [rust-lang/rust#76006]
I tried this code:

```rust
rust-lldb target/debug/rust-str-vs-string
```

I expected to see this happen: *To be able to use lldb commands as I can if I use lldb directly*

Instead, this happened: *error: file specified in --source (-s) option doesn't exist: 'lldb_commands'*

### Meta

`rustc --version --verbose`:
```
rustc 1.46.0 (04488afe3 2020-08-24)
binary: rustc
commit-hash: 04488afe34512aa4c33566eb16d8c912a3ae04f9
commit-date: 2020-08-24
host: x86_64-unknown-linux-gnu
release: 1.46.0
LLVM version: 10.0
```

The same happens on a macOS machine

---

I saw that `lldb_commands` is on `src/etc/` directory together with `rust-lldb` shell script, and I also saw that script calls it directly, but I'm not sure how it should behaves in my machine since the `lldb_commands` is not there (rustup is not installing it)

I've asked it on Rust users forum, and also in the discord chat, but no answers, so I'm considering it a bug, feel free to close it if it is something wrong with my installation and, if possible, guide me on where should I look to fix it.

**Comment by ehuss** [comment]
cc @ortem who introduced `lldb_commands` in #72357.  I also notice the script references `$RUSTC_SYSROOT` which isn't set anywhere.

**Comment by douglascorrea** [comment]
The issue happens because `rust-lldb` expects `lldb_commands` and its dependencies resides on the current directory.

Just to let you know that I got it working doing this:

- Cloned this repo on `~/repos/rust`:
- then

```shell
# cargo new foobar
# cd foobar
# cargo build -v
# ln -s ~/repos/rust/src/etc/lldb_commands ./
# ln -s ~/repos/rust/src/etc/lldb_providers.py ./
# ln -s ~/repos/rust/src/etc/lldb_lookup.py ./
# ln -s ~/repos/rust/src/etc/lldb_batchmode.py ./
# rust-lldb rust-lldb target/debug/foobar
```

**Comment by douglascorrea** [comment]
Another important highlight, as @ehuss mentioned, this is a recent change, so 1.45 was working fine and the issue appeared only on 1.46
