### ISSUE TITLE
why rust can't infer this type

### ISSUE THREAD

**Issue by oft** [rust-lang/rust#76008]
I tried this code:

```rust
fn foo<F, G>(f: F, g: G)
where
    F: Fn(i32, G) -> i32,
    G: Fn(i32) -> i32
{
    println!{"f(32) = {}", f(32, g)};
}


fn main() {

    foo(|x, f| f(x + 32), |x| x * x)
}
```

```
error[E0282]: type annotations needed
  --> src/main.rs:12:16
   |
12 |     foo(|x, f| f(x + 32), |x| x * x)
   |                ^^^^^^^^^ cannot infer type
   |
   = note: type must be known at this point
```
why rust can't infer this type

[Cannot infer type](https://users.rust-lang.org/t/cannot-infer-type/47902)

I expected to see this happen: *explanation*

Instead, this happened: *explanation*

### Meta

`rustc --version --verbose`:
```
<version>
```

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by jyn514** [comment]
It's something to do with `G`, using `fn(i32) -> i32` instead works fine. https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a44f87df026d79a2d62da356e73be07c

**Comment by oft** [comment]
@jyn514

I know how to resolve it, but i think that rust should infer this type.
