### ISSUE TITLE
Compute `Upvar.span` after typecheck

### ISSUE THREAD

**Issue by Aaron1011** [rust-lang/rust#76005]
In https://github.com/rust-lang/rust/pull/75933, I added code to determine a better upvar span when emitting borrow check errors. This span is stored in `ty::UpvarCapture`.

Ideally, we would return this span from the `upvars_mentioned` query - however, the better span depends on typeck (so we can tell if the upvar is inferred to be by-value), and typeck uses `upvars_mentioned`.

**Comment by arora-aman** [comment]
@Aaron1011 do you think something like this
https://github.com/sexxi-goose/rust/blob/c01f388ed9947cfe537ac7853bb7c255d3b3897f/src/librustc_middle/ty/mod.rs#L747 
meets what you were hoping this to look like?

Plan with that is to do something like `tcx.hir().span(capture_info.expr_id)` to get the span when we need it. 

A very hacky use is here: https://github.com/sexxi-goose/rust/blob/c01f388ed9947cfe537ac7853bb7c255d3b3897f/src/librustc_typeck/check/upvar.rs#L519
(Ignore the excessive duplication in the file)

I'll take into account the `let pat = upvar` comment when as we formalize this
