### ISSUE TITLE
Suggest `async {}` for `async || {}`

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#76011]
This code ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=988c3dd515555a1e28500cb19ca7d303)):
```rust
fn main() {
    let my_future = async || {
        1
    };
}
```
prints out
```
error[E0658]: async closures are unstable
 --> src/main.rs:2:21
  |
2 |     let my_future = async || {
  |                     ^^^^^
  |
  = note: see issue #62290 <https://github.com/rust-lang/rust/issues/62290> for more information

error: aborting due to previous error
```
This is pretty unhelpful for beginners - normally this happens when they try to use `await` in a closure, which tells them they need async:
```
error[E0728]: `await` is only allowed inside `async` functions and blocks
 --> src/main.rs:3:9
  |
2 |     let my_future = || {
  |                     -- this is not `async`
3 |         1.await
  |         ^^^^^^^ only allowed inside `async` functions and blocks
```
But when they do they get an error about async being unstable, which they have no idea how to solve. The fix is to remove the pipe symbols:
```
async { }
```
However, this requires knowledge that async blocks desugar internally into closures, which is not at all clear from the syntax. It would be better for the compiler to suggest it:
```
error[E0658]: async closures are unstable
 --> src/main.rs:2:21
  |
2 |     let my_future = async || {
  |                     ^^^^^^^^^^ help: to use an async block, remove the `||`: `async {`
  |
  = note: see issue #62290 <https://github.com/rust-lang/rust/issues/62290> for more information
```

**Comment by rokob** [comment]
Hey, I saw this and it looked like it might be easy so I took a shot with https://github.com/rust-lang/rust/pull/76580. I haven't fixed the tests yet because I wasn't sure if this approach is reasonable or not. You end up with

```
error[E0658]: async closures are unstable
 --> src/main.rs:2:21
  |
2 |     let my_future = async || {
  |                     ^^^^^
  |
  = note: see issue #62290 <https://github.com/rust-lang/rust/issues/62290> for more information
  = help: to use an async block, remove the `||`: `async

error: aborting due to previous error
```

Re-ordering the note and help, or adding a nested span on `async ||` to put the help would be considerably more involved.

**Comment by taiki-e** [comment]
Given the current `async ||` is equivalent to `|| async {}`, it may be preferable to suggest `|| async {}` instead of `async {}`.

**Comment by jyn514** [comment]
@taiki-e the point of this is that the user *didn't* mean `|| async {}` though. If you add `||` then you can no longer await it: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=083f8dbc81f44245734ff5c7a95e1c69

For context, the original code was something like https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=2f095b1aa4d8d3290b2ab41bed482469, where the user tried to use `await` outside of an async function.

**Comment by taiki-e** [comment]
@jyn514 Thanks for clarifying. What suggestion is preferable seems to depend on the expected return type.
Perhaps it is preferable to have both notes?
```text
   = help: to use an async block, remove the `||`: `async {`
   = help: to use a closure that returns a future, use `|| async {`
```

**Comment by lixinlin** [comment]
peer_connection.on_track(Box::new(async move |track, _, _| {
   ......
   let yy= xxx.await;
   ......
});
if remove ||, how to get the track var?
