### ISSUE TITLE
`Mismatched type` when trying to use async fns with feature(type_alias_impl_trait)

### ISSUE THREAD

**Issue by Dirbaio** [rust-lang/rust#76039]
I've been playing around with this feature and found some surprising behavior. I'm not sure if it's by design or a bug, but it looks like very surprising/counterintuitive behavior for me, so I thought I'd share it here.

Given this:

```rust
type FutureType = impl Future<Output=u32>;
fn consume(_: FutureType) { }
async fn my_future() -> u32 { 123 }
```

why doesn't this compile? [(playground)](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=f5408f83ca35c6600cf993ca248f0f7c)

```rust
//error: could not find defining uses
fn main() {
    consume(my_future()); //error[E0308]: mismatched types
}
```

It seems to me that calling a function taking a `FutureType` with `my_future()` should count as a "defining use", allowing rust to infer that both types are equal. It certainly does for "normal" type inference [(playground)](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=18f883a1cf645f92a7ca4a589562fdc2):

```rust
fn consume(_: impl Future<Output=u32>) { }

fn main() {
    consume(my_future());
}
```

It does compile when telling the compiler the types are the same via a return type: [(playground)](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=ed408497d74a2f1d7674b8d78d2ae857)

```rust
fn create() -> FutureType { my_future() }

fn main() {
    consume(create());
}
```

Also quite surprisingly, after adding this "defining use", you still can't pass `my_future()` directly to `consume`. As I understand it, they should be the same the same type now, but for some reason the compiler is still considering them distinct types.[(playground)](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=adafa7eabb75b21692c550bf7f848152)

```rust
fn main() {
    // ok
    consume(create());
    
    //error[E0308]: mismatched types
    // note: expected opaque type `impl std::future::Future` (opaque type at <src/main.rs:4:19>)
    //          found opaque type `impl std::future::Future` (opaque type at <src/main.rs:6:25>)
    // note: distinct uses of `impl Trait` result in different opaque types
    consume(my_future());
}
```

**Comment by csmoe** [comment]
They're distinct type indeed, the async function desugars to `fn my_future() -> impl Future<Output=u32>`, the compiler generates a hidden type for the return type(let's name it as `AsyncFnReturn`), `AsyncFnReturn` has nothing to do with the `FutureType` you defined. 
for details, checkout https://github.com/rust-lang/rfcs/blob/master/text/2515-type_alias_impl_trait.md

**Comment by Dirbaio** [comment]
@csmoe Why is that the case? 

This function

```rust
fn create() -> FutureType { my_future() }
```

returns the return value of my_future (of type `AsyncFnReturn`) in a function returning `FutureType`. This would allow the compiler to infer that `FutureType` is a type alias for `AsyncFnReturn`, so they should be effectively the same type.

**Comment by Dirbaio** [comment]
ie, desugaring after type inference should give this::

```rust

struct AsyncFnReturn;

type FutureType = AsyncFnReturn;

fn my_future() -> AsyncFnReturn { AsyncFnReturn }
fn consume(_: FutureType) { }
fn create() -> FutureType { my_future() }

fn main() {
    consume(create());
    consume(my_future());
}
```

which does compile fine [(playground)](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=bef14fda1d064278ad3071bfb418bd00)

**Comment by SNCPlay42** [comment]
The purpose of `impl Trait` as a return type or type alias is to *hide* what the actual type is. So code other than the defining use is not allowed to know what the actual type is.
