### ISSUE TITLE
Clean up rustdoc tests

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/rust#76036]
A lot of rustdoc tests are in the middle of the code. I think we should centralize them in one place (like in `librustdoc/test/`) and then organize the tests in there directly (grouping them by what they actually test).

**Comment by petrochenkov** [comment]
@GuillaumeGomez 
What do you mean?
We have a tidy check that forces tests to be in separate files named `tests.rs` rather than in the middle of the code, so all rustdoc tests look like this:
```
src\librustdoc\clean\cfg\tests.rs
src\librustdoc\html\highlight\tests.rs
src\librustdoc\html\markdown\tests.rs
src\librustdoc\html\render\tests.rs
src\librustdoc\html\toc\tests.rs
src\librustdoc\passes\unindent_comments\tests.rs
src\librustdoc\test\tests.rs
src\librustdoc\theme\tests.rs
```

**Comment by GuillaumeGomez** [comment]
I guess it's up to debate but this issue came up recently because a contributor (cc @matklad) needed to add a fixture file, making the whole very messy in my point of view. So what I had in mind was to move the files "out of tree" into something looking like this:

```text
src/librustdoc/tests/clean.rs
src/librustdoc/tests/html_highlight.rs
src/librustdoc/tests/html_markdown.rs
src/librustdoc/tests/html_render.rs
src/librustdoc/tests/html_toc.rs
...
```

Or something like this:

```text
src/librustdoc/tests/clean/cfg.rs
src/librustdoc/tests/html/highlight.rs
src/librustdoc/tests/html/markdown.rs
src/librustdoc/tests/html/render.rs
src/librustdoc/tests/html/toc.rs
...
```

(I have to admit that I prefer the second one.)

**Comment by jyn514** [comment]
I have the same comment as on https://github.com/rust-lang/rust/pull/76223 - I don't think making things public just for testing is helpful or necessary. It's possible to have a `tests/fixtures` directory if you think that would be less 'messy', but I don't think the tests themselves should be moved.
