### ISSUE TITLE
Removing `StringReader::retokenize`

### ISSUE THREAD

**Issue by matklad** [rust-lang/rust#76046]
`StringReader` contains a `retokenize` function, which allows to to, well, retokenize existing span:

https://github.com/rust-lang/rust/blob/d006f5734f49625c34d6fc33bf6b9967243abca8/src/librustc_parse/lexer/mod.rs#L73-L88

There's only caller of this function:

https://github.com/rust-lang/rust/blob/d006f5734f49625c34d6fc33bf6b9967243abca8/src/librustc_save_analysis/span_utils.rs#L46-L61

And there's only one caller of that caller:

https://github.com/rust-lang/rust/blob/d006f5734f49625c34d6fc33bf6b9967243abca8/src/librustc_save_analysis/dump_visitor.rs#L1202-L1212

In other words, the only reason why we need `StringReader::retokenize` is to get the span of `*` from `hir::Use` which happens to be a glob import. 

(
rls needs to know the span of `*` to implement "replace `use foo::*` with explicit list of imported items" code action. This was the first demoed code action and is still [the only one](https://github.com/rust-lang/rls/blob/fe46c95c3f01fbdaca36bdf70739d32062c1f53a/rls/src/actions/requests.rs#L615-L617) that is implemented
)

I'd like to remove the `retokenize` function, as it is one of the few remaining things that requires `StringReader` to be public, and as it is very much a hack anyway. 

Additionally, I believe I've broken this function accidently a while ago: https://github.com/rust-lang/rust/commit/395ee0b79f23b90593b01dd0a78451b8c93b0aa6#diff-d06ad31c547d2d94c8b8770006977767L69. Rather than retokenizing a span, it retokenized file from the begining until the end of the span (whcih, as uses are usually on top, worked correctly most of the times by accident).

What would be the best way to fix this? 

* Add `*` span to `hir::Use` -- this seem to be the "proper" solution here
* Move hack's implementation to where it belongs: in `librutc_save_analysis`, just fetch the text of the file and look for `*`, using `rustc_lexer` or maybe just `.rfind('*')`
* Remove the deglog functionlity from RLS? I don't like this option as it handicaps the RLS before we formally decided to deprecated it. But I don't completely disregard it either, as, as a whole, it seems to be a full-stack one off hack penetrating every layer of abstraction. 

@petrochenkov @Xanewok WDYT?

**Comment by petrochenkov** [comment]
I'd suggest the second alternative (move hack's implementation to in librutc_save_analysis), save analysis is a home of many hacks already and one more until save analysis is deprecated in its entirety won't hurt.
Adding span for `*` would be ok if it were useful for anything else at least.
