### ISSUE TITLE
Add an equivalent of "--check" on rustdoc

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/rust#76040]
In a recent conversation, it came up that `cargo check` wasn't running rustdoc lints. I then realized that there was no easy way to just run an equivalent of `cargo check` with rustdoc to get those lints. So the question is mostly: how should we do it? Extend `cargo`? Add an option on rustdoc and then call it through cargo?

cc @rust-lang/rustdoc 

Also tagging @yaahc who brought up the issue.

**Comment by jyn514** [comment]
Another thing mentioned is that it's not clear which lints belong to rustdoc and which belong to rustc. If we added `doc::` in front it would be more clear the lints are only run with `rustdoc`.

**Comment by jyn514** [comment]
Added in https://github.com/rust-lang/rust/pull/78984
