### ISSUE TITLE
documenting pattern with by-move & by-ref bindings

### ISSUE THREAD

**Issue by Amjad50** [rust-lang/rust#76049]
This is to stabilize #68354.

To be documented in:
- [x] The reference (rust-lang/reference#881)
- [x] Rust by example (rust-lang/rust-by-example#1377)

@rustbot modify labels: T-doc, T-lang, A-patterns, F-move-ref-pattern

**Comment by Mark-Simulacrum** [comment]
Is there a reason for a separate issue tracking this beyond the tracking issue for the feature itself? It looks like upstream PRs have already been filed and maybe we could close this?

**Comment by Amjad50** [comment]
Thought if there is discussion specific to documentation should be here. But closing it will clean things maybe
