### ISSUE TITLE
E0063 should not suggest adding inaccessible private fields

### ISSUE THREAD

**Issue by kornelski** [rust-lang/rust#76077]
This error message could be more helpful:

```rust
pub mod foo {
    pub struct Foo {
        you_cant_use_this_field: bool,
    }
}

fn main() {
    foo::Foo {};
}
```

> error[E0063]: missing field `you_cant_use_this_field` in initializer of `foo::Foo`

It complains about lack of a private field in the initializer, but this problem can't be solved by adding the field. The implied solution is impossible, and will only lead to another dead-end error.

It would be better to explain in general that this struct can't be constructed from a literal syntax here, because it contains private fields. Bonus points for finding methods that return `Self` and suggesting them.

[related forum thread](https://users.rust-lang.org/t/very-new-to-rust-whats-the-missing-base-error/47999)

**Comment by jalcine** [comment]
Thankfully, I landed here from a Web search and then found [https://steveklabnik.com/writing/structure-literals-vs-constructors-in-rust](https://steveklabnik.com/writing/structure-literals-vs-constructors-in-rust) as a way to counteract this. Hope this helps anyone else who comes across this.

(Originally published at: https://v2.jacky.wtf/post/5bf98ed9-e8a1-46ca-9e26-245230276048)
