### ISSUE TITLE
I can see the system file in playground . Not sure that is  an security issue.

### ISSUE THREAD

**Issue by davnav** [rust-lang/rust#76079]
When I did dome directory experiments in rust playground , I can see the system files. I am not sure that is an issue!!

[code](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a08da156eca1ba0b508224870c20f856)

![playrust](https://user-images.githubusercontent.com/1313332/91645260-84f48500-e9f8-11ea-8dd6-18a0118a636b.png)

**Comment by jonas-schievink** [comment]
The playground is sandboxed, so this is not an issue.
