### ISSUE TITLE
error: component 'rust-std' for target 'x86_64-unknown-illumos' is unavailable for download for channel stable

### ISSUE THREAD

**Issue by jhpratt** [rust-lang/rust#76080]
Pretty self explanatory one here: Illumos should be available, at least from my interpretation of the [platform support](https://doc.rust-lang.org/nightly/rustc/platform-support.html) page.

**Comment by jonas-schievink** [comment]
Pretty sure https://github.com/rust-lang/rust/pull/71272 is only on beta, not stable

**Comment by jhpratt** [comment]
Confirming that the target is available on beta. Guess I just jumped the gun on this one.
