### ISSUE TITLE
Validity of get_mut on MaybeUninit

### ISSUE THREAD

**Issue by Dylan-DPC** [rust-lang/rust#76091]
Creating this issue to track the discussion on whether this is valid or not, from this [FIXME note](https://github.com/rust-lang/rust/blob/5e208efaa850efaa97495e81c49cf0f5767e8f49/library/core/src/fmt/float.rs#L21):

> This is calling `get_mut` on an uninitialized
         `MaybeUninit` (here and elsewhere in this file). Revisit this once
         we decided whether that is valid or not.
         We can do this only because we are libstd and coupled to the compiler.
         (FWIW, using `freeze` would not be enough; `flt2dec::Part` is an enum!)

The issue being mentioned when the fixme was closed without addressing this concern, and the new tracking issue doesn't raise it, so created this so that we can discuss it here and link it to the tracking issue 

cc @RalfJung

**Comment by RalfJung** [comment]
Something went wrong and two issues got created, closing in favor of https://github.com/rust-lang/rust/issues/76092.
