### ISSUE TITLE
Clarify docs for "`!` and traits"

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#76094]
The section "[`!` and traits](https://doc.rust-lang.org/std/primitive.never.html#-and-traits)" says:

> When writing your own traits, `!` should have an `impl` whenever there is an obvious `impl` which doesn't `panic!`.

Yet it doesn't explain *why* you should `impl` your traits for `!`. I think it would be good for someone who understands `!` well to write up a sentence or two about why you should `impl` your traits for `!`. I myself don't quite understand what the reason for doing so is ;)

@rustbot modify labels: T-doc C-enhancement

**Comment by jyn514** [comment]
>  I myself don't quite understand what the reason for doing so is ;)

https://github.com/rust-lang/rust/blob/a888b02884883de41d0ce08aa62a6cd6d4790951/src/librustc_interface/util.rs#L575-L582 might shed some light.

**Comment by camelid** [comment]
So does that mean that `!` coerces to any concrete type, but not to an `impl Trait`?

**Comment by jyn514** [comment]
Correct. `!` does not implement all traits, and if it does not implement `impl Trait`, then `unimplemented!()` as the body of a function returning `impl Trait` will be a type error.

**Comment by jyn514** [comment]
See also https://github.com/rust-lang/rust/issues/65863 and related issues linked from there.
