### ISSUE TITLE
Unstable Book: assoc_char features lead to a closed tracking issue

### ISSUE THREAD

**Issue by ArekPiekarz** [rust-lang/rust#76102]
In Unstable Book sections for [assoc_char_consts](https://doc.rust-lang.org/nightly/unstable-book/library-features/assoc-char-consts.html) and [assoc_char_funcs](https://doc.rust-lang.org/nightly/unstable-book/library-features/assoc-char-funcs.html) contain links to tracking issues leading to the same closed issue - https://github.com/rust-lang/rust/issues/71763.

As mentioned there, either that issue should be reopened or a new tracking issue should be created, or these entries should be removed from the Unstable Book if they are stabilized now.

**Comment by jonas-schievink** [comment]
Reopened it, thanks!
