### ISSUE TITLE
Unstable Book: const_caller_location leads to a closed tracking issue

### ISSUE THREAD

**Issue by ArekPiekarz** [rust-lang/rust#76105]
In Unstable Book the section [const_caller_location](https://doc.rust-lang.org/nightly/unstable-book/library-features/const-caller-location.html) leads to a closed tracking issue https://github.com/rust-lang/rust/issues/47809 about a general caller tracking. There is a forked new issue about [tracking callers for closures](https://github.com/rust-lang/rust/issues/74042), but it seems unrelated to working in const functions.

This functionality is still not stabilized, because trying to use it like this:
```rust
#[track_caller]
const fn foo() -> &'static std::panic::Location<'static> {
    std::panic::Location::caller()
}
```
gives error:
```
error: `std::panic::Location::<'a>::caller` is not yet stable as a const fn
 --> src/lib.rs:3:5
  |
3 |     std::panic::Location::caller()
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: add `#![feature(const_caller_location)]` to the crate attributes to enable
```

Thus it looks like `const_caller_location` should have its own tracking issue.

**Comment by lzutao** [comment]
You could make this issue an tracking issue for that feature.
Could you rename the issue and make a PR to change this line ?
https://github.com/rust-lang/rust/blob/b1d092c15942ab2e59152dde6f1af77e888473c8/library/core/src/panic.rs#L235

**Comment by ArekPiekarz** [comment]
Thanks for the suggestion, I'll create another issue as tracking so I don't have to edit this one and so this conversation does not look out of place, then make a PR.
