### ISSUE TITLE
Closures cannot access variables

### ISSUE THREAD

**Issue by zhuxiujia** [rust-lang/rust#76111]
rust version:    1.45.1 

I tried this code:

```rust
    pub fn do_fn(otherwise: fn())  {
        otherwise();
    }
    fn main() {
        let arg = 0;
        do_fn(||{
            let result=arg+1;
        });
    }
```
### cargo run this code：
```rust
error[E0308]: mismatched types
   --> src\wrapper.rs:573:15
    |
573 |           do_fn(||{
    |  _______________^
574 | |             let result=arg+1;
575 | |         });
    | |_________^ expected fn pointer, found closure
    |
    = note: expected fn pointer `fn()`
                  found closure `[closure@src\wrapper.rs:573:15: 575:10 arg:_]`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0308`.
```

**Comment by Aaron1011** [comment]
The closure you're using captures a variable from the enclosing function (`arg`). This prevents it from being cast to a function pointer, since a function pointer cannot store any state. However, the error message should definitely explain this.

You can change `do_fn` to take a `FnOnce` closure, which will allow you to pass in either a closure or a standalone function

**Comment by zhuxiujia** [comment]
> The closure you're using captures a variable from the enclosing function (`arg`). This prevents it from being cast to a function pointer, since a function pointer cannot store any state. However, the error message should definitely explain this.
> 
> You can change `do_fn` to take a `FnOnce` closure, which will allow you to pass in either a closure or a standalone function

maybe ,Should the rust compiler tell me what works?

**Comment by zhuxiujia** [comment]
> The closure you're using captures a variable from the enclosing function (`arg`). This prevents it from being cast to a function pointer, since a function pointer cannot store any state. However, the error message should definitely explain this.
> 
> You can change `do_fn` to take a `FnOnce` closure, which will allow you to pass in either a closure or a standalone function



### can not have two  F:FnOnce  args

```rust
    pub fn do_fn<F>(otherwise: F,w:F) where F:FnOnce()  {
        otherwise();
    }
    fn main() {
        let arg = 0;
        do_fn(||{
            let result=arg+1;
        });
    }
```


```rust
error[E0308]: mismatched types
   --> src\wrapper.rs:547:15
    |
545 |                 |w| w
    |                 ----- the expected closure
546 | 
547 |             , |w| w)
    |               ^^^^^ expected closure, found a different closure
    |
    = note: expected closure `[closure@src\wrapper.rs:545:17: 545:22]`
               found closure `[closure@src\wrapper.rs:547:15: 547:20]`
    = note: no two closures, even if identical, have the same type
    = help: consider boxing your closure and/or using it as a trait object

```
