### ISSUE TITLE
functions that return direct static references to const fns fail to compile

### ISSUE THREAD

**Issue by Cobrand** [rust-lang/rust#76180]
When having a function that returns a static reference, you can return borrows to direct structs such as `A(5)` but not `const fn`s which return the same struct such as `A::new(5)`. It's kind of tricky to explain, the example is easier to understand.

# Example

```rust
#[derive(Copy, Clone)]
pub struct A(i32);

impl A {
    pub const fn new(i: i32) -> A {
        A(i)
    }
}

// comment to make it compile
fn not_good() -> &'static A {
    &A::new(5) // <- this should work since A::new is const fn
}

fn good1() -> &'static A {
    &A(5)
}

fn good2() -> &'static A {
    static THIS_DOES_WORK: &'static A = &A::new(5);
    THIS_DOES_WORK
}

fn main() {}
```

[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=875acd7ddacf56661862f3658420308f)

## Current Behavior (1.46.0 Stable)

```
error[E0515]: cannot return reference to temporary value
  --> src/main.rs:13:5
   |
13 |     &A::new(5)
   |     ^---------
   |     ||
   |     |temporary value created here
   |     returns a reference to data owned by the current function
```

There is a borrow error when there shouldn't be: this error is perfectly valid when `A::new` is not const fn, but if `A::new` is const fn, it shouldn't output an error.

**Comment by jonas-schievink** [comment]
`const fn` calls are deliberately not promoted to statics. Please refer to https://github.com/rust-lang/const-eval/issues/19 for details on why that is. Closing as expected behavior.
