### ISSUE TITLE
rustdoc lint missing_doc_code_examples not working on stable

### ISSUE THREAD

**Issue by JesHansen** [rust-lang/rust#76194]
I wanted to try out the missing_doc_code_examples rustdoc lint, but it seems to 
be bugged.

I tried following the example given in [the book](https://doc.rust-lang.org/rustdoc/lints.html#missing_doc_code_examples).

Steps to reproduce:

Create a new crate: 

```rust
cargo new testmissingdocs
```

Then edit the src/main.rs file:

```rust
#![deny(missing_doc_code_examples)]

//! Top level crate documentation

fn main() {
    println!("Hello, world!");
}

/// This function has no code examples.
pub fn add(i: i32, j: i32) -> i32 {
    i + j
}
```

I would now expect to get a linting error when building the crate, since the add
 function is public, but does not have a code example. However, `cargo build` as
well as `cargo doc` and `cargo test --doc` completes without any errors.

**Comment by ehuss** [comment]
The lint only works on nightly, the docs should probably be updated.

**Comment by jyn514** [comment]
These docs live in https://github.com/rust-lang/rust/blob/master/src/doc/rustdoc/src/lints.md. To fix this, add 'and is **nightly-only**' to the first sentence.

**Comment by JesHansen** [comment]
I created PR #76212 to update the documentation. Thanks for clarifying. :-)
