### ISSUE TITLE
Better error messages for type-errors due to #[deriving].

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#7621]
`#[deriving(Trait)]` normally relies on the constituent types of the `struct` or `enum` also implement `Trait`, and currently, if they don't, the error messages are unclear. e.g. in the following code, the problem is `[f64, .. 3]` doesn't implement `Clone`.

```rust
#[deriving(Clone)]
struct V {
    v : [f64, ..3]
}

fn main() {}
```

```
tmp.rs:1:11: 1:16 error: mismatched types: expected `[f64, .. 3]` but found `&[f64, .. 3]` (expected vector but found &-ptr)
tmp.rs:1 #[deriving(Clone)]
```

(This particular error message is because there is a `Clone` impl for `&T`, and that one is used if there is no `Clone` impl for `T`.)

**Comment by steveklabnik** [comment]
@huonw with https://github.com/rust-lang/rust/pull/11826 merged, is this fixed?

**Comment by huonw** [comment]
Looks like it:

```rust
#[derive(Clone)]
struct V {
    v : [f64; 100]
}

fn main() {}
```

```
<anon>:3:5: 3:19 error: the trait `core::clone::Clone` is not implemented for the type `[f64; 100]`
<anon>:3     v : [f64; 100]
             ^~~~~~~~~~~~~~
note: in expansion of #[derive]
<anon>:1:1: 1:17 note: expansion site
```

Although it was almost certainly https://github.com/rust-lang/rust/pull/18578 that got them to be that clear.
