### ISSUE TITLE
Fixed-length arrays implement no traits

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#7622]
Currently fixed-length arrays (i.e. `[f64, .. 3]`) implement no traits, because each size needs to be implemented separately. It'd be nice to be able to parameterise the length.

One consequence is that `#[deriving]` doesn't work with them (and gives strange error messages):

``` rust
#[deriving(Eq)]
struct SuDoku {
    map: [[uint, .. 9], .. 9]
}
```

```
$ rustc --lib sudoku.rs
sudoku.rs:1:11: 1:14 error: mismatched types: expected `&&[[uint, .. 9]]` but found `&[[uint, .. 9], .. 9]` ([] storage differs: expected & but found 9)
sudoku.rs:1 #[deriving(Eq)]
                       ^~~
sudoku.rs:1:11: 1:14 error: failed to find an implementation of trait core::cmp::Eq for [uint, .. 9]
sudoku.rs:1 #[deriving(Eq)]
                       ^~~
```

**Comment by apasel422** [comment]
It's still a problem that arrays only implement `Clone` when `T: Copy`.

**Comment by amluto** [comment]
This is particularly problematic with rust-bindgen.  rust-bindgen generates things like this:

```
pub struct Union_Unnamed11 {
    pub _bindgen_data_: [u8; 283usize],
}
````

for unions, and the resulting struct cannot be Copy at all and cannot derive Clone.

It looks like this could be very cleanly fixed if https://github.com/rust-lang/rfcs/issues/1038 (types parametrized over numbers) happened.

**Comment by aturon** [comment]
Closing; this issue is really subsumed by the desire for const generics, and we've done all we can until those land. (And when they do come, we'll generalize the current trait impls accordingly.)
