### ISSUE TITLE
Improve diagnostics returning types defined within anon namespaces

### ISSUE THREAD

**Issue by arora-aman** [rust-lang/rust#76239]
For the following code ([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=8b0131faa8c3dc06c622d08e071c8e8a))

```rust
fn f() {
    let c = || { 
        struct Foo{};
        
        Foo{}
    };
    c() // This returns a value
}
```

One of the lints is to put a semicolon and the other is to add a return type `fn f() -> f::{{closure}}#0::Foo `

It is accurate that `f` requires a return type, but the suggested return type is inaccurate. If I do use the lint as is, I get 
```
1 | fn f() -> f::{{closure}}#0::Foo {
  |              ^ expected identifier
```
which seems like a dead end.

**What I expect?**
If I understand correctly we can't actually return a type that was defined within the closure, and I'd expect the error to report something that explains it.

**Comment by estebank** [comment]
```
error[[E0308]](https://doc.rust-lang.org/stable/error_codes/E0308.html): mismatched types
 --> src/main.rs:7:5
  |
7 |     c()
  |     ^^^ expected `()`, found `Foo`
  |
help: consider using a semicolon here
  |
7 |     c();
  |        +
help: try adding a return type
  |
1 | fn f() -> Foo {
  |        ++++++
```
