### ISSUE TITLE
rust ffi link error

### ISSUE THREAD

**Issue by toplinuxsir** [rust-lang/rust#76266]
with rust 1.46

I link c++ libray (libmylib.so ) , with g++ -lmylib , It works ok, and link success,
But with rust ,I have pass the -lmylib, compiles ok, and always link error:
'
/usr/bin/ld: callc.d2qs7r1b-cgu.0:(.text._ZN5callc4main17h70fed83690e9e7b8E+0x106): undefined reference to USB5622E_GetNetCfgA' /usr/bin/ld: callc.d2qs7r1b-cgu.0:(.text._ZN5callc4main17h70fed83690e9e7b8E+0x351): undefined reference to USB5622E_AI_GetRateInfo'
/usr/bin/ld: callc.d2qs7r1b-cgu.0:(.text._ZN5callc4main17h70fed83690e9e7b8E+0x4d0): undefined reference to USB5622E_AI_VerifyParam' /usr/bin/ld: callc.d2qs7r1b-cgu.0:(.text._ZN5callc4main17h70fed83690e9e7b8E+0x4f7): undefined reference to USB5622E_AI_InitTask'
/usr/bin/ld: callc.d2qs7r1b-cgu.0:(.text._ZN5callc4main17h70fed83690e9e7b8E+0x508): undefined reference to USB5622E_AI_StartTask' /usr/bin/ld: callc.d2qs7r1b-cgu.0:(.text._ZN5callc4main17h70fed83690e9e7b8E+0x581): undefined reference to USB5622E_AI_SendSoftTrig'
/usr/bin/ld: callc.d2qs7r1b-cgu.0:(.text._ZN5callc4main17h70fed83690e9e7b8E+0x5a0): undefined reference to USB5622E_AI_ReadBinary' /usr/bin/ld: callc.d2qs7r1b-cgu.0:(.text._ZN5callc4main17h70fed83690e9e7b8E+0x875): undefined reference to USB5622E_DEV_Release'
/usr/bin/ld: callc.d2qs7r1b-cgu.0:(.text._ZN5callc4main17h70fed83690e9e7b8E+0x961): undefined reference

**Comment by jonas-schievink** [comment]
Please provide instructions to reproduce this issue.

**Comment by toplinuxsir** [comment]
@jonas-schievink 

rust link the ffi C++ lib  ( mylib.so ) , It's function name is mangled ,for example , function  USB5622E_AI_SendSoftTrig   name mangled to _Z24USB5622E_AI_SendSoftTrigPv , rustc use gcc to link the lib , But if I use g++ link  no error.

**Comment by Enselic** [comment]
Triage: We need a minimal reproducer to make progress here. Closing until we have one.
