### ISSUE TITLE
Option to output compressed executables

### ISSUE THREAD

**Issue by Timmmm** [rust-lang/rust#76279]
Because Rust links everything statically it can generate rather large executables. One hacky workaround for this is to compress them using [UPX](https://upx.github.io/). For example I have a fairly small Rust program that ends up as an 11.4 MB executable, but is 2.9 MB when compressed with UPX. Startup time is veeery slightly affected (I haven't measure but it feels like around 0.1-0.2s) but the trade-off would easily be worth it for my use case.

**It would be really cool if Rust had a native option to compress executables using a system similar to UPX.**

"Just use UPX!" I hear you screaming. I could but there are a few downsides:

1. It has slightly dubious [license terms](https://upx.github.io/upx-license.html).
2. It's actually impossible to build it from source - they use a closed source compression library. Even using the substitute it is quite difficult to build from source.
3. If you want to build it from source they really don't want to make it easy - they say "If you can't manage to compile it then the sources are probably not for you. Don't email us for help.". Not very welcoming.
4. They don't provide binaries for Mac.
5. It's an extra program to obtain, install & run. "Turn on compression" is a much more valid rebuttal to "Rust executables are too large" than "Install UPX, oh build it from source if you're on a Mac, then add a custom post-build step somehow...".

I realise this is a ton of work but it would be a great feature.

**Comment by jonas-schievink** [comment]
This should not be in the compiler imo. Just use an external packer.

**Comment by lzutao** [comment]
> It's actually impossible to build it from source - they use a closed source compression library. Even using the substitute it is quite difficult to build from source.

Do we have any UPX crates ?

**Comment by the8472** [comment]
> I have a fairly small Rust program that ends up as an 11.4 MB executable

Is that before or after [the usual tricks](https://github.com/johnthagen/min-sized-rust)?

**Comment by Timmmm** [comment]
@jonas-schievink Can you explain why you disagree with the points I made above?

**Comment by Timmmm** [comment]
@the8472 I don't really want to use most of those tricks.

**Comment by jonas-schievink** [comment]
> @jonas-schievink Can you explain why you disagree with the points I made above?

I don't. But the conclusion of that shouldn't be "this must be put in rustc", it should be "UPX has poor UX".

There are many more executable packers than just UPX, and it is no doubt possible to write one in Rust, which would address all but the last of your points.

Given that this change would need to go through a Major Change Proposal anyways, closing in favor of that.

**Comment by Timmmm** [comment]
> There are many more executable packers than just UPX

Maybe for PE but I don't think there are any others for Mach-O or ELF.

> it is no doubt possible to write one in Rust

Sure... But it would be difficult to integrate into Cargo because it doesn't have post-build steps.

Oh well. I imagine this will never get done anyway.
