### ISSUE TITLE
implement an owned rope type

### ISSUE THREAD

**Issue by thestinger** [rust-lang/rust#7628]
This should just be a generic sequence type, and we can build an actual string on top of it later as we do on top of the byte vector representation. Of course, starting off with just sequences of bytes and extending it later would be fine.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#653
