### ISSUE TITLE
Calling line!() in a macro doesn't show the real line number

### ISSUE THREAD

**Issue by Dengjianping** [rust-lang/rust#76323]
I tried to call line!() in a macro, but it doesn't show the real location where line!() is called.

```rust
macro_rules! line_num {
    () => {
        println!("Hello!: {:?}", line!()); // line 3
    };
}

fn main() {
    line_num!(); // line 8
}
```
Just print **8** instead of **3**.

Is this expected or just a duplicated issue, someone reported it already?

Here's the [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=8daa395be2829e938f1383a3217ed7be)

**Comment by jonas-schievink** [comment]
This is expected behavior: `line!()` is expanded after `line_num!()`.
