### ISSUE TITLE
Soundness issue in Drop for SyncOnceCell

### ISSUE THREAD

**Issue by m-ou-se** [rust-lang/rust#76367]
#75648 added `#[may_dangle]` to `T` in the `Drop` implementation of `SyncOnceCell`. This is correct for simple types like `T = &str`, but when `T`'s `Drop` implementation accesses borrowed data, this might lead to accessing already dropped data:

```rust
#![feature(once_cell)]

use std::lazy::SyncOnceCell;

struct A<'a>(&'a str);

impl<'a> Drop for A<'a> {
    fn drop(&mut self) {
        dbg!(self.0);
    }
}

fn main() {
        let cell = SyncOnceCell::new();
        {
            let s = String::from("hello world");
            let _ = cell.set(A(&s));
        }
}
```
```
[src/main.rs:9] self.0 = "\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{0}\u{10}thread 'main' panicked at 'byte index 9 is not a char boundary; it is inside '\u{10}' (bytes 8..9) of `À`', library/core/src/fmt/mod.rs:2043:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by m-ou-se** [comment]
`Vec` and `Box` also use `#[may_dangle]` in their `Drop` impl. But I can't reproduce this problem with either of those instead of `SyncOnceCell`. Not sure why only `SyncOnceCell` seems to have this problem.

**Comment by jonas-schievink** [comment]
I think the problem is that `set` puts no lifetime constraint on `T`, so you can write any arbitrarily short-lived `T` to the cell. It would have to at least outlive the `&self` reference.

**Comment by Mark-Simulacrum** [comment]
Cc @matklad, likely this affects upstream once_cell as well?

**Comment by m-ou-se** [comment]
That's also the case for a Vec:

```rust
fn main() {
        let mut vec = Vec::new();
        {
            let s = String::from("hello world");
            vec.push(&s);
        }
}
```
This compiles fine.

Replacing `&s` with `A(&s)` from above here does give an error though, like it should. Looks like dropck does understand that `Vec`'s `drop` is going to drop `T`s.

Looks like `PhantomData<T>` is what made that work properly for Vec and Box: https://github.com/rust-lang/rust/blob/02fe30971ef397bcff3460a9aaf175e0810c2c90/library/core/src/ptr/unique.rs#L40-L45

**Comment by jonas-schievink** [comment]
Oh, yeah, you're right

**Comment by m-ou-se** [comment]
> likely this affects upstream once_cell as well?

Doesn't look like it. the `once_cell` crate uses `Option<T>` instead of `MaybeUninit<T>`:

https://github.com/matklad/once_cell/blob/af70a46a856d1ff14b9d74cb5a4b14e448a902b7/src/imp_std.rs#L21-L25

https://github.com/matklad/once_cell/blob/af70a46a856d1ff14b9d74cb5a4b14e448a902b7/src/imp_pl.rs#L13
