### ISSUE TITLE
rustdoc: DOS line endings cause extra newlines to show up in source view

### ISSUE THREAD

**Issue by lzutao** [rust-lang/rust#76361]
I tried to document and publish my Windows crate to github pages.
Things went pretty smooth until I opened the source code view.
As you can see below, a newline is appended to each line doc comment,
also no line number for each line:

![image](https://user-images.githubusercontent.com/15225902/92299053-4707db80-ef79-11ea-8f44-223028636484.png)

Here the render page on gh-pages: <https://lzutao.github.io/junction/src/junction/lib.rs.html#1-111>.
Beware that it has no version control for the generated doc. But the link here may work
for a limited time before github purge the cache: <https://github.com/lzutao/junction/tree/6ab9e37b809afdb49fce1accf943250af6aa5dbf>. Also here the the CI script I used:
<https://github.com/lzutao/junction/blob/724dd2e564c76e4f92580629c2f4a1340875e890/.github/workflows/ci.yml#L62-L95>.

*The same code published on https://docs.rs is normal*: https://docs.rs/junction/0.2.0/src/junction/lib.rs.html#1-111

### Meta

`rustc --version --verbose`: x86_64-pc-windows-msvc rustc 1.48.0-nightly (c59199efc 2020-09-04)

@rustbot modify labels: T-rustdoc

**Comment by Nemo157** [comment]
Could be related to `\r\n` normalization depending on the git checkout settings of the runner.

**Comment by lzutao** [comment]
I set `git config --global core.autocrlf false` before `git add`, maybe this is my misconfigure somehow.

**Comment by AndyGauge** [comment]
Try adding `git config --global core.eol lf` and possibly `git add --renormalize .` to make those files end with the right character.

**Comment by lzutao** [comment]
Thanks Andy, I tried https://github.com/lzutao/junction/commit/c8107d054b36adb7bebaa7ea4c90283a6bcef51d as you told but still the issue remains.

**Comment by Nemo157** [comment]
Oh, I meant for the _source_ files, you might need to reconfigure git before checking out the source (and that's likely just a workaround, this seems likely to be a bug in rustdoc's handling of `\r\n` in source files).

**Comment by lzutao** [comment]
Thank you, problem is solved in https://github.com/lzutao/junction/commit/005a79cdb955f70fa19b5b510e0286116167893e .
I am pretty sure this issue is a duplicate of another, but I cannot find it.

You could close this issue if you see fit.

**Comment by Nemo157** [comment]
(keywords cause I keep failing to search for this: dos line endings)

**Comment by jyn514** [comment]
This is a recent regression, it was introduced sometime between `rustdoc 1.47.0 (18bf6b4f0 2020-10-07)` and `rustdoc 1.49.0-nightly (cf9cf7c92 2020-11-10)`. I suspect https://github.com/rust-lang/rust/pull/75775 is related, cc @matklad.

**Comment by jyn514** [comment]
The issue is that `\r` is being marked as a doc-comment:

```
<span class="doccomment">/// Additional docs
</span>
<!-- this next line ends with \r -->
<span class="doccomment">///
</span>
<span class="doccomment">/// [LLVM commit D20468][https://reviews.llvm.org/D20468]
</span>
```

**Comment by jyn514** [comment]
I guess this means `\r` is being marked as a `LineComment`? I don't see why it would.

https://github.com/rust-lang/rust/blob/75042566d1c90d912f22e4db43b6d3af98447986/src/librustdoc/html/highlight.rs#L169-L171

**Comment by jyn514** [comment]
This is only happening for `///` lines, normal source lines are fine.

**Comment by jyn514** [comment]
> The issue is that \r is being marked as a doc-comment:

This is not actually correct - it was a blank line in the original source code. The issue is that rustdoc used to strip `\r` in newlines, but no longer does. Here's 1.47:

```html
<span class="doccomment">/// Additional docs</span>
<span class="doccomment">///</span>
<span class="doccomment">/// [LLVM commit D20468][https://reviews.llvm.org/D20468]</span>
```
and 1.48:
```html
</pre><div class="example-wrap"><pre class="rust ">
<span class="doccomment">/// Additional docs
</span>
<span class="doccomment">///
</span>
<span class="doccomment">/// [LLVM commit D20468][https://reviews.llvm.org/D20468]
</span>
```
