### ISSUE TITLE
`x.py test linkchecker` builds rustc twice

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#76371]
Found in https://rust-lang.zulipchat.com/#narrow/stream/242791-t-infra/topic/tool.20linkchecker.20needs.20stage.202.20compiler.20.3F: Currently, `x.py doc` uses `--stage 0`, but `x.py linkchecker` uses `--stage 2`. This causes enormous recompiles for no reason; the two should match.

**Comment by ehuss** [comment]
I believe `x.py test src/tools/linkchecker` defaults to runs at stage 1 like all other tests. Is there some config or something causing it to run at stage 2?

I'd be slightly concerned running it at stage 0, since some doc tools need to link with the compiler, they would be using an old compiler in that case.  For quick checks, it should be OK, but like running any tests at stage 0, it is incomplete. 

Also, I believe not all docs can be built at stage 0 (for example, if you have compiler-docs enabled), which could cause confusing errors. That should probably have some check to skip or error with compiler docs at stage 0.

**Comment by jyn514** [comment]
Hmm, this is a good point. @lzutao what do you think?

**Comment by jyn514** [comment]
> I'd be slightly concerned running it at stage 0, since some doc tools need to link with the compiler, they would be using an old compiler in that case. For quick checks, it should be OK, but like running any tests at stage 0, it is incomplete.

In particular, they'd be missing recent fixes to intra-doc links which would fix broken links, yeah.

**Comment by lzutao** [comment]
I don't actually recall the stage 2 std or stage 2 compiler was built with linkchecker,
it actually took long enough that I don't want to run it again.

<details><summary>diff between config.toml.example and config.toml</summary>

```diff
--- config.toml.example	2020-08-29 07:57:49.757114990 +0000
+++ config.toml	2020-09-03 12:07:50.115762028 +0000
@@ -36,7 +36,7 @@
 #assertions = false
 
 # Indicates whether ccache is used when building LLVM
-#ccache = false
+ccache = true
 # or alternatively ...
 #ccache = "/path/to/ccache"
 
@@ -50,7 +50,7 @@
 #static-libstdcpp = false
 
 # Whether to use Ninja to build LLVM. This runs much faster than make.
-#ninja = true
+ninja = true
 
 # LLVM targets to build support for.
 # Note: this is NOT related to Rust compilation targets. However, as Rust is
@@ -61,7 +61,7 @@
 # support. You'll need to write a target specification at least, and most
 # likely, teach rustc about the C ABI of the target. Get in touch with the
 # Rust team and file an issue if you need assistance in porting!
-#targets = "AArch64;ARM;Hexagon;MSP430;Mips;NVPTX;PowerPC;RISCV;Sparc;SystemZ;WebAssembly;X86"
+targets = "AArch64;ARM;Mips;X86"
 
 # LLVM experimental targets to build support for. These targets are specified in
 # the same format as above, but since these targets are experimental, they are
@@ -102,7 +102,7 @@
 #use-libcxx = true
 
 # The value specified here will be passed as `-DLLVM_USE_LINKER` to CMake.
-#use-linker = "lld"
+#use-linker = "/home/lzutao/.local/bin/lld"
 
 # Whether or not to specify `-DLLVM_TEMPORARILY_ALLOW_OLD_TOOLCHAIN=YES`
 #allow-old-toolchain = false
@@ -141,11 +141,11 @@
 
 # Instead of downloading the src/stage0.txt version of Cargo specified, use
 # this Cargo binary instead to build all Rust code
-#cargo = "/path/to/bin/cargo"
+cargo = "/home/lzutao/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/cargo"
 
 # Instead of downloading the src/stage0.txt version of the compiler
 # specified, use this rustc binary instead as the stage0 snapshot compiler.
-#rustc = "/path/to/bin/rustc"
+rustc = "/home/lzutao/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rustc"
 
 # Instead of download the src/stage0.txt version of rustfmt specified,
 # use this rustfmt binary instead as the stage0 snapshot rustfmt.
@@ -161,7 +161,7 @@
 #compiler-docs = false
 
 # Indicate whether git submodules are managed and updated automatically.
-#submodules = true
+submodules = false
 
 # Update git submodules only when the checked out commit in the submodules differs
 # from what is committed in the main rustc repo.
@@ -232,7 +232,7 @@
 
 # Indicates that a local rebuild is occurring instead of a full bootstrap,
 # essentially skipping stage0 as the local compiler is recompiling itself again.
-#local-rebuild = false
+local-rebuild = true
 
 # Print out how long each rustbuild step took (mostly intended for CI and
 # tracking over time)
@@ -309,7 +309,7 @@
 # Number of codegen units to use for each compiler invocation. A value of 0
 # means "the number of cores on this machine", and 1+ is passed through to the
 # compiler.
-#codegen-units = 1
+codegen-units = 0
 
 # Sets the number of codegen units to build the standard library with,
 # regardless of what the codegen-unit setting for the rest of the compiler is.
@@ -368,7 +368,7 @@
 #backtrace = true
 
 # Whether to always use incremental compilation when building rustc
-#incremental = false
+incremental = true
 
 # Build a multi-threaded rustc
 #parallel-compiler = false
@@ -432,7 +432,7 @@
 # LLD will not be used if we're cross linking or running tests.
 #
 # Explicitly setting the linker for a target will override this option when targeting MSVC.
-#use-lld = false
+#use-lld = true
 
 # Indicates whether some LLVM tools, like llvm-objdump, will be made available in the
 # sysroot.
@@ -488,30 +488,30 @@
 # C compiler to be used to compiler C code. Note that the
 # default value is platform specific, and if not specified it may also depend on
 # what platform is crossing to what platform.
-#cc = "cc"
+#cc = "clang"
 
 # C++ compiler to be used to compiler C++ code (e.g. LLVM and our LLVM shims).
 # This is only used for host targets.
-#cxx = "c++"
+#cxx = "clang++"
 
 # Archiver to be used to assemble static libraries compiled from C/C++ code.
 # Note: an absolute path should be used, otherwise LLVM build will break.
-#ar = "ar"
+#ar = "/home/lzutao/.local/bin/llvm-ar"
 
 # Ranlib to be used to assemble static libraries compiled from C/C++ code.
 # Note: an absolute path should be used, otherwise LLVM build will break.
-#ranlib = "ranlib"
+#ranlib = "/home/lzutao/.local/bin/llvm-ranlib"
 
 # Linker to be used to link Rust code. Note that the
 # default value is platform specific, and if not specified it may also depend on
 # what platform is crossing to what platform.
 # Setting this will override the `use-lld` option for Rust code when targeting MSVC.
-#linker = "cc"
+#linker = "/home/lzutao/.local/bin/clang"
 
 # Path to the `llvm-config` binary of the installation of a custom LLVM to link
 # against. Note that if this is specified we don't compile LLVM at all for this
 # target.
-#llvm-config = "../path/to/llvm/root/bin/llvm-config"
+llvm-config = "/home/lzutao/.local/bin/llvm-config"
 
 # Normally the build system can find LLVM's FileCheck utility, but if
 # not, you can specify an explicit file name for it.
```

</details>

**Comment by ehuss** [comment]
After looking at this in more detail, I think the issue is that `rustc` is built twice. The second build is due to the error-index-generator, which links to rustc and rustdoc in order to reuse the markdown renderer. I'm not sure if there's a particularly good way to work around that. AFAIK, linking to rustc must use a stage1 build. The only alternative I can think of is using a different renderer (either mdbook, or something custom using pulldown-cmark?). I'm not sure that would be really worth it, but something to consider.

**Comment by Mark-Simulacrum** [comment]
You can definitely link to rustc libraries in any stage - not sure what you mean by stage 1 there.

In the long run I think mdbook is probably a good idea for the error index though.

**Comment by ehuss** [comment]
Yea, I was thinking about it more, and I was mistaken. I was thinking about ABI issues (with stage1-tools built with a stage1 compiler linking against stage0-rustc built with a stage0 compiler).  But I guess it should use the same trick that rustdoc does to handle this (I think error-index-generator would need to replicate [most of this logic](https://github.com/rust-lang/rust/blob/d778203da2157f47af6d1f7ba5f44eb933ee2df1/src/bootstrap/tool.rs#L476-L534) to use stage-1).  

A problem with mdbook is that it can't output to a single file.  The URL https://doc.rust-lang.org/error-index.html might need to change to something like https://doc.rust-lang.org/error-index/index.html, which could be a little disruptive (at least needing a redirect). I'm also curious if it would be better to have each error on a separate page, or continue with one large page. (I'm uncertain about how slow a single page would be, considering mdbook does client-side syntax highlighting.)  I'm also uncertain if anyone ever visits the error-index page at all (seems a bit silly to put effort into something nobody uses).

@Mark-Simulacrum do either of those approaches seem preferable (or neither)?

**Comment by jyn514** [comment]
> I'm also uncertain if anyone ever visits the error-index page at all (seems a bit silly to put effort into something nobody uses).

Maybe a simpler solution would be to make the error-index opt-in instead of opt-out, so that it's only generated by CI? Then you wouldn't have to mess with it to get `x.py test linkchecker --stage 0` working.

**Comment by Mark-Simulacrum** [comment]
I think the redirect shouldn't be too hard, I wouldn't see that as a problem. Distinct pages are a bit annoying, though I imagine that 99% of the time people are looking at just one error of the error index rather than all of them at the same time.

I think personally I'd prefer to make the error index generator not use rustdoc/rustc as a library -- i.e., use mdbook. Maybe an easy way of doing that is to just roll the single file into rustdoc itself behind a forever unstable -Z flag or something, rather than trying to re-engineer a bunch of mdbook stuff.

**Comment by ehuss** [comment]
I posted #81603 to avoid the second build with `--stage=1`.  I think there is still value to re-architect how error-index-generator works, but I wanted to do a smaller change for now rather than invest time in redesigning the tool.

**Comment by jyn514** [comment]
@ehuss this should be fixed since https://github.com/rust-lang/rust/pull/81603, right?

**Comment by ehuss** [comment]
The original issue should be fixed, so I think this can be closed.  I kept it open for the idea of rewriting error-index-generator to use a different technique.  However, I personally have no plans to do that.

**Comment by jyn514** [comment]
Ok, I'll close this issue then - the linkchecker is already somewhat tracked by https://github.com/rust-lang/rust/issues/80096.
