### ISSUE TITLE
rust-gdbgui error

### ISSUE THREAD

**Issue by macalimlim** [rust-lang/rust#76383]
I tried this on the terminal using rust-gdbgui:

```shell
$ rust-gdbgui --gdb-args "--pid 12345"
```

I expected to see this happen: `gdbgui on the browser`

Instead, this happened: `gdbgui: error: unrecognized arguments: --gdb-args`

### Meta

`rustc --version --verbose`:
```
rustc 1.46.0 (04488afe3 2020-08-24)
binary: rustc
commit-hash: 04488afe34512aa4c33566eb16d8c912a3ae04f9
commit-date: 2020-08-24
host: x86_64-unknown-linux-gnu
release: 1.46.0
LLVM version: 10.0
```
The cause was that the latest gdbgui (v0.14.0.0) has removed `--gdb-args` option in favor of `--gdb-cmd`

**Comment by jonas-schievink** [comment]
> The cause was that the latest gdbgui (v0.14.0.0) has removed `--gdb-args` option in favor of `--gdb-cmd`

That sounds like expected breakage then
