### ISSUE TITLE
rustdoc: Way to collapse Deref section

### ISSUE THREAD

**Issue by lzutao** [rust-lang/rust#76405]
For example, [this `Deref` section][1] of `Vec<T>` is long.
I want a way to collapse it.
![image](https://user-images.githubusercontent.com/15225902/92324046-08048380-f068-11ea-845a-b22ca4c608bd.png)

[1]: https://doc.rust-lang.org/nightly/std/vec/struct.Vec.html#deref-methods

@rustbot modify labels: T-rustdoc C-feature-request

**Comment by ollie27** [comment]
Duplicate of #54873
