### ISSUE TITLE
WASM-blob built by rustc fails in binaryen's validator

### ISSUE THREAD

**Issue by lukaslueg** [rust-lang/rust#76404]
Building [this](https://github.com/lukaslueg/macro_railroad_wasm) repo used to work flawlessly using `wasm-pack` and `rustc 1.44.1`. The most recent toolchains (`rustc 1.46.0`, `wasm-pack 0.9.1`, `wasm-opt 96` from `binaryen`) fail to build as `wasm-opt` fails to validate the wasm-blob produced by rustc:

```
[wasm-validator error in module] unexpected true: Exported global cannot be mutable, on 
global$0
Fatal: error in validating input
Error: failed to execute `wasm-opt`: exited with exit code: 1
```

I've tried `wasm-opt` version 90 (bundled with `wasm-pack`) and the more recent version 96, which both fail to validate the wasm-blob. I suspect this is rather a problem with rustc (which went undetected by `wasm-opt` until recently) than `wasm-opt` or `wasm-pack`.

To reproduce: `cargo install wasm-pack`, clone the repo, execute `make` or `wasm-pack build --target web`. The toolchain will build a wasm-blob using `wasm-pack`, which calls `wasm-opt`, which fails to validate the wasm-blob.

**Comment by CryZe** [comment]
Exported mutable globals were not a thing in the MVP but are now part of the spec. So this sounds more like that validator is misconfigured or out of date.

https://github.com/WebAssembly/mutable-global/blob/master/proposals/mutable-global/Overview.md#importexport-mutable-globals

**Comment by lukaslueg** [comment]
This behavior appeared in commit `65170f4`, which bumped some dependencies in the lockfile; commit `39b4520` builds just fine. The lockfile bump introduces `wasi 0.10.0` and bumps `wasm-bindgen` from `0.2.63` to `0.2.67`.

I'm unsure where to report this issue. The regression seem to point towards `wasm-bindgen` or `wasi`. However, rustc should never generate a wasm-blob which fails validation (if validation is correct in the first place).

**Comment by lukaslueg** [comment]
Closing this here due to @CryZe comment, which sounds reasonable.
