### ISSUE TITLE
Unstable Book: "stdsimd" leads to a closed tracking issue

### ISSUE THREAD

**Issue by ArekPiekarz** [rust-lang/rust#76412]
Unstable Book in section about [stdsimd](https://doc.rust-lang.org/nightly/unstable-book/library-features/stdsimd.html) leads to a tracking issue that was closed 2 years ago (!) - https://github.com/rust-lang/rust/issues/48556. Should it be reopened?

**Comment by frewsxcv** [comment]
#48556 has been reopened
