### ISSUE TITLE
Tracking Issue for `Duration` saturating operations

### ISSUE THREAD

**Issue by marmeladema** [rust-lang/rust#76416]
This is a tracking issue for `Duration` saturating operations.
The feature gate for the issue is `#![feature(duration_saturating_ops)]`.

```rust
        impl Duration {
            pub const fn saturating_add(self, rhs: Duration) -> Duration {}
            pub const fn saturating_sub(self, rhs: Duration) -> Duration {}
            pub const fn saturating_mul(self, rhs: u32) -> Duration {}
        }
```

### Steps

- [x] Implement the proposal: https://github.com/rust-lang/rust/pull/76114
- [x] FCP
- [x] Stabilization PR: https://github.com/rust-lang/rust/pull/84090

### Unresolved Questions

* ~~Do we want associated constants similar to the ones that already exist for integer types or associated methods? (ie: `Duration::MIN` or `Duration::min()`?~~
* ~~Should `Duration::MIN` be replaced by `Duration::zero()`? They are currently equivalent but one can image a future where `Duration` is able to hold negative duration and thus making `MIN` different from `zero()`.~~

**Comment by matklad** [comment]
Just needed `saturating_sub` when dealing with time intervals.

Also, unresloved questions seem to be from another tracking issue?

**Comment by m-ou-se** [comment]
@rfcbot merge

**Comment by marmeladema** [comment]
I am very happy to see this stabilized. One thing I wanted to discuss is the documentation: it currently mentions two associated constants:
* https://doc.rust-lang.org/nightly/std/time/struct.Duration.html#associatedconstant.ZERO
* https://doc.rust-lang.org/nightly/std/time/struct.Duration.html#associatedconstant.MAX

But both are currently unstable. Should they be stabilized at the same time? Or should the documentation updated? It seems a bit weird that the documentation for stable methods is mentioning unstable features and therefore the code examples cannot be executed and verified on stable. This is really a newbie question, I don't know what is the correct approach here. I am pretty sure such circumstances have happened before?

**Comment by m-ou-se** [comment]
`ZERO` is being stabilized at the same time: https://github.com/rust-lang/rust/issues/73544#issuecomment-817201305

`MAX` still needs to be stabilized. [Here](https://github.com/rust-lang/rust/issues/57391#issuecomment-717681193) it's suggested that that constant should probably not be part of the same tracking issue as the other constants there (`SECOND`, etc.). Feel free to send a PR that stabilizes just `MAX`, then we can do an FCP on that PR and we'll remove it from that tracking issue.

> Also, once that question is resolved, I would be very glad to do the stabilization PR.

Feel free to make that PR without waiting for `MAX`. In this specific case I don't think it's a problem if this gets stabilized while the docs still refer to something unstable. `MAX` is pretty clear and uncontroversial. Even if it's unstable, it's still the best way we have to refer to the maximum value of a `Duration`.
