### ISSUE TITLE
Error message on casting negative numbers to usize is quite unhelpful

### ISSUE THREAD

**Issue by Disasm** [rust-lang/rust#76413]
Code:
```rust
fn syscall(nr: usize) -> usize {
    match nr {
        1 => (-1) as usize,
        _ => -1 as usize,
    }
}

fn syscall_i(nr: usize) -> isize {
    match nr {
        1 => (-1) as isize,
        _ => -1 as isize,
    }
}

fn main() {
    let rc = syscall(42);
    println!("result: {}", rc);
    
    let rc = syscall_i(42);
    println!("result: {}", rc);
}
```
Playground: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=04afbf8753fe268ea47b7b3fae6f897c

Error message:
```
error[E0600]: cannot apply unary operator `-` to type `usize`
 --> src/main.rs:3:14
  |
3 |         1 => (-1) as usize,
  |              ^^^^ cannot apply unary operator `-`
  |
  = note: unsigned values cannot be negated

error[E0600]: cannot apply unary operator `-` to type `usize`
 --> src/main.rs:4:14
  |
4 |         _ => -1 as usize,
  |              ^^ cannot apply unary operator `-`
  |
  = note: unsigned values cannot be negated
```

Somehow, in one case this `1` in the `-1` expression is unsigned, but in the other case it is signed and everything is fine.

**Comment by leonardo-m** [comment]
For `(-1) as usize` the compiler has to suggest to replace it with `usize::MAX`.

The compiler should also suggest to replace `-1 as usize` with `-1_usize`, to remove some hard "as" casts from the code.

**Comment by euclio** [comment]
> The compiler should also suggest to replace -1 as usize with -1_usize, to remove some hard "as" casts from the code.

I think this is more appropriate as a clippy lint, opened https://github.com/rust-lang/rust-clippy/issues/6116.
