### ISSUE TITLE
Label shadowing warning for undeclared label

### ISSUE THREAD

**Issue by ZettaScript** [rust-lang/rust#76431]
This code:
```
'foo: loop {break 'foo}
'foo: loop {break 'foo}
```
causes a label shadowing warning, but this code:
```
'foo: loop {break 'foo}
break 'foo; // error: use of undeclared label `'foo`
'foo: loop {break 'foo}
```
causes an undeclared label error.

It seems incoherent that a label can be both in scope and undeclared.

### Meta
```
1.48.0-nightly (2020-09-06 73dc675b9437c2a51a97)
```

**Comment by pickfire** [comment]
Isn't this behavior correct? There is no label `'foo` at `break 'foo`.

Note that `break 'foo` does not behaves like `goto`, it just breaks to a previous level.

**Comment by jonas-schievink** [comment]
The warning is intentional and was added for future compatibility. Closing as expected behavior.
