### ISSUE TITLE
Some opt-level 2 optimizations make rustc a *lot* slower

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#76433]
[This Miri testcase](https://github.com/rust-lang/miri/blob/5f1182d04a161915df7b1d001ac7cc77fc7a2047/tests/run-pass/float.rs), when built via rustc, usually only takes a few seconds. With `-Zmir-opt-level=2`, however, it takes at least two minutes (then I aborted compilation).

To reproduce, I did this in a Miri checkout (no need to build Miri, we are just using the example):
```
$ time rustc tests/run-pass/float.rs

real    0m7,099s
user    0m6,219s
sys     0m0,964s
$ time rustc tests/run-pass/float.rs -Zmir-opt-level=2
^C

real    2m12,074s
user    2m10,970s
sys     0m0,985s
```

Cc @rust-lang/wg-mir-opt

**Comment by tmiasko** [comment]
Copy propagation takes most of time here; tracked in #36673. Is this the same source as in #73717?

**Comment by RalfJung** [comment]
*oops* it is... I thought I had reported this before but couldn't find it.^^ Sorry.
