### ISSUE TITLE
Is there a debug version of the compiler available?

### ISSUE THREAD

**Issue by 945188363** [rust-lang/rust#76464]
My team is learning Rust and Rust compiler recently. 
But we do not found a debug version of rust compiler. 
So, is there a debug version of the compiler available? Or some doc?
We would appreciate it if you could give us some guidance on how to build it.

**Comment by jyn514** [comment]
Are you asking how to compile rustc from source with debug symbols? If so there are instructions in https://rustc-dev-guide.rust-lang.org/building/how-to-build-and-run.html (in particular, set `debug = true` as instructed).

**Comment by jyn514** [comment]
If you're trying to learn the Rust language, I don't recommend building the compiler from source - check out https://doc.rust-lang.org/book/ and https://www.rust-lang.org/tools/install instead.

**Comment by 945188363** [comment]
In fact, our team is learning how to implement macro declaration in rust, so we have to go inside the compiler to see how the data structure is modified. Simply using the compile command of rustc can not meet our needs. Is there any documentation or teaching in this section?

**Comment by jyn514** [comment]
I recommend https://doc.rust-lang.org/book/ch19-06-macros.html#macros or https://danielkeep.github.io/tlborm/book/index.html. You don't have to know how the compiler works internally to write a macro.

**Comment by 945188363** [comment]
Okay,got it. thank U.
