### ISSUE TITLE
Show visual bell once compilation is done

### ISSUE THREAD

**Issue by pickfire** [rust-lang/rust#76477]
It would be good for `./x.py` to show visual bell by printing `\a` after compilation is done to notify the users it is done since it may take quite a while. I am not sure about the behavior of printing this on windows.

Current alternative is to `./x.py ...; echo -e '\a'`.

**Comment by xfix** [comment]
This likely makes more sense to configure in an UNIX shell. For zsh check out https://github.com/marzocchi/zsh-notify, for fish shell, check out https://github.com/franciscolourenco/done.

**Comment by pickfire** [comment]
Even though the user may already have notification, it could be possible that the user ssh to somewhere to build and therefore the notification that the user have in place does not work. Similar case for me since I use a compile farm to build rather than building it on my machine (~5 hours -> ~25 minutes), so it does not have any setup. Or maybe we could just have it in `config.toml` to make it configurable?

**Comment by jyn514** [comment]
I don't think this is likely to be accepted even if someone made a PR. I'd encourage you to write your own x.py wrapper, even on a compile farm you can have a little shell script that executes `echo -e '\a'` after.
