### ISSUE TITLE
regression: get_unchecked resolves to unstable feature use

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#76479]
* https://crater-reports.s3.amazonaws.com/beta-1.47-1/beta-2020-08-29/reg/algebraics-0.2.0/log.txt

Unclear if this is a genuine regression or something else is going on, but seems like at least plausibly some change to resolution is involved.

**Comment by lzutao** [comment]
Bisect result:  #73565

searched nightlies: from nightly-2020-04-01 to nightly-2020-09-07
regressed nightly: nightly-2020-08-22
searched commits: from https://github.com/rust-lang/rust/commit/e15510ca33ea15c893b78710101c962b11459963 to https://github.com/rust-lang/rust/commit/de521cbb303c08febd9fa3755caccd4f3e491ea3
regressed commit: https://github.com/rust-lang/rust/commit/d9d4d39612aae0b8398340bd83d592cafad8e4ec

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.5.2</summary>


Host triple: x86_64-unknown-linux-musl
Reproduce with:
```bash
cargo bisect-rustc --start 2020-04-01 --target x86_64-unknown-linux-gnu --host x86_64-unknown-linux-gnu --verbose 
```
</details>

**Comment by Mark-Simulacrum** [comment]
Thanks @lzutao!

Looks like "get_unchecked is now an unstable, hidden method on Iterator" is the cause here, because it means downstream Iterator extensions cannot implement such a method (right?). This didn't cause too much breakage and it feels rare for such a method to be defined as an extension trait rather than inherently, so I'm personally fine with closing this as expected breakage.

It would be good to get an MCVE to get some idea of whether I'm correct here that inherent methods would still work on downstream iterators, and if so then I'm personally fine with closing this.

**Comment by lzutao** [comment]
MCVE: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=d334cb2f4f0a985ddf674012a928abd3
Note: it is just a mvce and doesn't reflect what original code does.
```rust
// #![feature(trusted_random_access)]
pub struct Foo {
    x: usize,
    y: usize
}

impl Foo {
    fn get_unchecked(&self, x: usize, y: usize) -> (usize, usize) {
        unimplemented!()
    }
}
impl Iterator for Foo {
    type Item = (usize, usize);
    fn next(&mut self) -> Option<(usize, usize)> {
        Some(self.get_unchecked(self.x, self.y))
    }
}
```

**Comment by Dylan-DPC** [comment]
Marking this as P-critical based on the [wg-prioritization discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/I-prioritize.20.2376479.20regression.3A.20get_unchecked.20resolves.20to.20u.E2.80.A6)

**Comment by spastorino** [comment]
Implemented this but @matthewjasper already has a solution too, so leaving it up to them and adjusting the assignee properly.

**Comment by spastorino** [comment]
Reopened to track backport of https://github.com/rust-lang/rust/pull/77201

**Comment by spastorino** [comment]
Closing this one as #77201 was already backported.
