### ISSUE TITLE
[std docs] Methods from Deref target have broken links.

### ISSUE THREAD

**Issue by moxian** [rust-lang/rust#76486]
- Go to documentation for `std::string::String` - https://doc.rust-lang.org/std/string/struct.String.html
- Find `as_bytes` method (in `Deref<Target=str>` block)
- Click on `str::from_utf8` linked from within method docs
- Get taken to https://doc.rust-lang.org/std/string/str/fn.from_utf8.html which is a 404

Pic: 
![firefox-20200908-174451](https://user-images.githubusercontent.com/7831163/92510205-03bc9f80-f1fb-11ea-8576-8171bd91a1d2.png)

(This might be a duplicate of https://github.com/rust-lang/rust/issues/32129, but it's hard for me to see what exactly that one is about, as it was filed in 2016, and i assume things changed a lot since then)

**Comment by ehuss** [comment]
Thanks for the report. I believe this has been fixed in the beta channel (https://doc.rust-lang.org/beta/std/string/struct.String.html) which should be released October 8th.

**Comment by jyn514** [comment]
This is now fixed on stable!
