### ISSUE TITLE
rust-lld breaks on i686-pc-windows-gnu

### ISSUE THREAD

**Issue by Keithcat1** [rust-lang/rust#76491]
C:\py\j\hello_rust>rustc -Vv
rustc 1.46.0 (04488afe3 2020-08-24)
binary: rustc
commit-hash: 04488afe34512aa4c33566eb16d8c912a3ae04f9
commit-date: 2020-08-24
host: i686-pc-windows-gnu
release: 1.46.0
LLVM version: 10.0

I ran this command in order to use the included rust-lld linker:
C:\py\j\hello_rust>set CARGO_TARGET_I686_PC_WINDOWS_GNU_LINKER=rust-lld

Then, I tried to build my Cargo hello world project and here are the results:
C:\py\j\hello_rust>cargo build
   Compiling hello_rust v0.1.0 (C:\py\j\hello_rust)
error: linking with `rust-lld` failed: exit code: 1
  |
  = note: "rust-lld" "-flavor" "gnu" "C:\\rust\\rustup\\toolchains\\stable-i686-
pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\self-contained\\crt2.o"
"C:\\rust\\rustup\\toolchains\\stable-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc
-windows-gnu\\lib\\rsbegin.o" "-L" "C:\\rust\\rustup\\toolchains\\stable-i686-pc
-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib" "-L" "C:\\rust\\rustup\\to
olchains\\stable-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\se
lf-contained" "C:\\py\\j\\hello_rust\\target\\debug\\deps\\hello_rust-279abe0508
1936aa.2zw63tsskilccwc6.rcgu.o" "C:\\py\\j\\hello_rust\\target\\debug\\deps\\hel
lo_rust-279abe05081936aa.4dhg8t1cjkw8md0h.rcgu.o" "C:\\py\\j\\hello_rust\\target
\\debug\\deps\\hello_rust-279abe05081936aa.58gt8py3qm1dgrz1.rcgu.o" "C:\\py\\j\\
hello_rust\\target\\debug\\deps\\hello_rust-279abe05081936aa.bginw74pvbx0dl9.rcg
u.o" "C:\\py\\j\\hello_rust\\target\\debug\\deps\\hello_rust-279abe05081936aa.g7
scjmtccrgkrgh.rcgu.o" "C:\\py\\j\\hello_rust\\target\\debug\\deps\\hello_rust-27
9abe05081936aa.pc9r2fex9ayk3br.rcgu.o" "-o" "C:\\py\\j\\hello_rust\\target\\debu
g\\deps\\hello_rust-279abe05081936aa.exe" "C:\\py\\j\\hello_rust\\target\\debug\
\deps\\hello_rust-279abe05081936aa.4dlwa79zjyk7oop1.rcgu.o" "--gc-sections" "-L"
 "C:\\py\\j\\hello_rust\\target\\debug\\deps" "-L" "C:\\rust\\rustup\\toolchains
\\stable-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib" "--start-g
roup" "-Bstatic" "C:\\rust\\rustup\\toolchains\\stable-i686-pc-windows-gnu\\lib\
\rustlib\\i686-pc-windows-gnu\\lib\\libstd-e4e40256d0c086c9.rlib" "C:\\rust\\rus
tup\\toolchains\\stable-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\
lib\\libpanic_unwind-8e02fc67161a7d8f.rlib" "C:\\rust\\rustup\\toolchains\\stabl
e-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\libhashbrown-3380
4d6248981d68.rlib" "C:\\rust\\rustup\\toolchains\\stable-i686-pc-windows-gnu\\li
b\\rustlib\\i686-pc-windows-gnu\\lib\\librustc_std_workspace_alloc-057cb2a83ed8d
602.rlib" "C:\\rust\\rustup\\toolchains\\stable-i686-pc-windows-gnu\\lib\\rustli
b\\i686-pc-windows-gnu\\lib\\libbacktrace-951976a2e108e12f.rlib" "C:\\rust\\rust
up\\toolchains\\stable-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\l
ib\\libbacktrace_sys-91e9eefa1109c155.rlib" "C:\\rust\\rustup\\toolchains\\stabl
e-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\librustc_demangle
-bf0cbd257613d152.rlib" "C:\\rust\\rustup\\toolchains\\stable-i686-pc-windows-gn
u\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\libunwind-c34988a92fa8dc0e.rlib" "C:\
\rust\\rustup\\toolchains\\stable-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-win
dows-gnu\\lib\\libcfg_if-17273c5475206f25.rlib" "C:\\rust\\rustup\\toolchains\\s
table-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\liblibc-fb8ee
cdcaa771961.rlib" "C:\\rust\\rustup\\toolchains\\stable-i686-pc-windows-gnu\\lib
\\rustlib\\i686-pc-windows-gnu\\lib\\liballoc-5cf9e879ba55ea4b.rlib" "C:\\rust\\
rustup\\toolchains\\stable-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gn
u\\lib\\librustc_std_workspace_core-e16b6d2c85c40d6b.rlib" "C:\\rust\\rustup\\to
olchains\\stable-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\li
bcore-b978dcbc96dc6d47.rlib" "--end-group" "C:\\rust\\rustup\\toolchains\\stable
-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\libcompiler_builti
ns-c6570c2846c80c80.rlib" "-Bdynamic" "-ladvapi32" "-lws2_32" "-luserenv" "C:\\r
ust\\rustup\\toolchains\\stable-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windo
ws-gnu\\lib\\rsend.o"
  = note: rust-lld: error: C:\rust\rustup\toolchains\stable-i686-pc-windows-gnu\
lib\rustlib\i686-pc-windows-gnu\lib\self-contained\crt2.o: unknown file type
          rust-lld: error: C:\rust\rustup\toolchains\stable-i686-pc-windows-gnu\
lib\rustlib\i686-pc-windows-gnu\lib\rsbegin.o: unknown file type
          rust-lld: error: C:\py\j\hello_rust\target\debug\deps\hello_rust-279ab
e05081936aa.2zw63tsskilccwc6.rcgu.o: unknown file type
          rust-lld: error: C:\py\j\hello_rust\target\debug\deps\hello_rust-279ab
e05081936aa.4dhg8t1cjkw8md0h.rcgu.o: unknown file type
          rust-lld: error: C:\py\j\hello_rust\target\debug\deps\hello_rust-279ab
e05081936aa.58gt8py3qm1dgrz1.rcgu.o: unknown file type
          rust-lld: error: C:\py\j\hello_rust\target\debug\deps\hello_rust-279ab
e05081936aa.bginw74pvbx0dl9.rcgu.o: unknown file type
          rust-lld: error: C:\py\j\hello_rust\target\debug\deps\hello_rust-279ab
e05081936aa.g7scjmtccrgkrgh.rcgu.o: unknown file type
          rust-lld: error: C:\py\j\hello_rust\target\debug\deps\hello_rust-279ab
e05081936aa.pc9r2fex9ayk3br.rcgu.o: unknown file type
          rust-lld: error: C:\py\j\hello_rust\target\debug\deps\hello_rust-279ab
e05081936aa.4dlwa79zjyk7oop1.rcgu.o: unknown file type
          rust-lld: error: C:\rust\rustup\toolchains\stable-i686-pc-windows-gnu\
lib\rustlib\i686-pc-windows-gnu\lib\rsend.o: unknown file type

error: aborting due to previous error

error: could not compile `hello_rust`.

To learn more, run the command again with --verbose.

I think that this probjem would go away if I used Clang.exe as the linker, but installing clang would be problematic on my end

**Comment by Keithcat1** [comment]
OK, it seems that you need to pass "-m i386pe" to the linker.
Not "-m=i386pe" or "-mi386pe", it has to be "-m i386pe"
Now I'm getting errors like this, I think it's because kernel32 isn't being linked to
C:\py\j\hello_rust>cargo build
   Compiling hello_rust v0.1.0 (C:\py\j\hello_rust)
error: linking with `rust-lld` failed: exit code: 1
  |
  = note: "rust-lld" "-flavor" "gnu" "C:\\rust\\rustup\\toolchains\\stable-i686-
pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\self-contained\\crt2.o"
"C:\\rust\\rustup\\toolchains\\stable-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc
-windows-gnu\\lib\\rsbegin.o" "-L" "C:\\rust\\rustup\\toolchains\\stable-i686-pc
-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib" "-L" "C:\\rust\\rustup\\to
olchains\\stable-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\se
lf-contained" "C:\\py\\j\\hello_rust\\target\\debug\\deps\\hello_rust-279abe0508
1936aa.2zw63tsskilccwc6.rcgu.o" "C:\\py\\j\\hello_rust\\target\\debug\\deps\\hel
lo_rust-279abe05081936aa.4dhg8t1cjkw8md0h.rcgu.o" "C:\\py\\j\\hello_rust\\target
\\debug\\deps\\hello_rust-279abe05081936aa.58gt8py3qm1dgrz1.rcgu.o" "C:\\py\\j\\
hello_rust\\target\\debug\\deps\\hello_rust-279abe05081936aa.bginw74pvbx0dl9.rcg
u.o" "C:\\py\\j\\hello_rust\\target\\debug\\deps\\hello_rust-279abe05081936aa.g7
scjmtccrgkrgh.rcgu.o" "C:\\py\\j\\hello_rust\\target\\debug\\deps\\hello_rust-27
9abe05081936aa.pc9r2fex9ayk3br.rcgu.o" "-o" "C:\\py\\j\\hello_rust\\target\\debu
g\\deps\\hello_rust-279abe05081936aa.exe" "C:\\py\\j\\hello_rust\\target\\debug\
\deps\\hello_rust-279abe05081936aa.4dlwa79zjyk7oop1.rcgu.o" "--gc-sections" "-L"
 "C:\\py\\j\\hello_rust\\target\\debug\\deps" "-L" "C:\\rust\\rustup\\toolchains
\\stable-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib" "--start-g
roup" "-Bstatic" "C:\\rust\\rustup\\toolchains\\stable-i686-pc-windows-gnu\\lib\
\rustlib\\i686-pc-windows-gnu\\lib\\libstd-e4e40256d0c086c9.rlib" "C:\\rust\\rus
tup\\toolchains\\stable-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\
lib\\libpanic_unwind-8e02fc67161a7d8f.rlib" "C:\\rust\\rustup\\toolchains\\stabl
e-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\libhashbrown-3380
4d6248981d68.rlib" "C:\\rust\\rustup\\toolchains\\stable-i686-pc-windows-gnu\\li
b\\rustlib\\i686-pc-windows-gnu\\lib\\librustc_std_workspace_alloc-057cb2a83ed8d
602.rlib" "C:\\rust\\rustup\\toolchains\\stable-i686-pc-windows-gnu\\lib\\rustli
b\\i686-pc-windows-gnu\\lib\\libbacktrace-951976a2e108e12f.rlib" "C:\\rust\\rust
up\\toolchains\\stable-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\l
ib\\libbacktrace_sys-91e9eefa1109c155.rlib" "C:\\rust\\rustup\\toolchains\\stabl
e-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\librustc_demangle
-bf0cbd257613d152.rlib" "C:\\rust\\rustup\\toolchains\\stable-i686-pc-windows-gn
u\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\libunwind-c34988a92fa8dc0e.rlib" "C:\
\rust\\rustup\\toolchains\\stable-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-win
dows-gnu\\lib\\libcfg_if-17273c5475206f25.rlib" "C:\\rust\\rustup\\toolchains\\s
table-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\liblibc-fb8ee
cdcaa771961.rlib" "C:\\rust\\rustup\\toolchains\\stable-i686-pc-windows-gnu\\lib
\\rustlib\\i686-pc-windows-gnu\\lib\\liballoc-5cf9e879ba55ea4b.rlib" "C:\\rust\\
rustup\\toolchains\\stable-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gn
u\\lib\\librustc_std_workspace_core-e16b6d2c85c40d6b.rlib" "C:\\rust\\rustup\\to
olchains\\stable-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\li
bcore-b978dcbc96dc6d47.rlib" "--end-group" "C:\\rust\\rustup\\toolchains\\stable
-i686-pc-windows-gnu\\lib\\rustlib\\i686-pc-windows-gnu\\lib\\libcompiler_builti
ns-c6570c2846c80c80.rlib" "-Bdynamic" "-ladvapi32" "-lws2_32" "-luserenv" "-m" "
i386pe" "-lkernel32" "C:\\rust\\rustup\\toolchains\\stable-i686-pc-windows-gnu\\
lib\\rustlib\\i686-pc-windows-gnu\\lib\\rsend.o"
  = note: error: failed to compute relocation: IMAGE_REL_I386_REL32, Invalid dat
a was encountered while parsing the file
          error: failed to compute relocation: IMAGE_REL_I386_REL32, Invalid dat
a was encountered while parsing the file
          error: failed to compute relocation: IMAGE_REL_I386_REL32, Invalid dat
a was encountered while parsing the file
          error: failed to compute relocation: IMAGE_REL_I386_REL32, Invalid dat
a was encountered while parsing the file
          error: failed to compute relocation: IMAGE_REL_I386_REL32, Invalid dat
a was encountered while parsing the file
          error: failed to compute relocation: IMAGE_REL_I386_REL32, Invalid dat
a was encountered while parsing the file
          lld-link: error: undefined symbol: _mingw_initltsdrot_force
          >>> referenced by C:\rust\rustup\toolchains\stable-i686-pc-windows-gnu
\lib\rustlib\i686-pc-windows-gnu\lib\self-contained\crt2.o:(_pre_c_init)

          lld-link: error: undefined symbol: _mingw_initltsdyn_force
          >>> referenced by C:\rust\rustup\toolchains\stable-i686-pc-windows-gnu
\lib\rustlib\i686-pc-windows-gnu\lib\self-contained\crt2.o:(_pre_c_init)

          lld-link: error: undefined symbol: _mingw_initltssuo_force
          >>> referenced by C:\rust\rustup\toolchains\stable-i686-pc-windows-gnu
\lib\rustlib\i686-pc-windows-gnu\lib\self-contained\crt2.o:(_pre_c_init)

          lld-link: error: undefined symbol: _mingw_initcharmax
          >>> referenced by C:\rust\rustup\toolchains\stable-i686-pc-windows-gnu
\lib\rustlib\i686-pc-windows-gnu\lib\self-contained\crt2.o:(_pre_c_init)

          lld-link: error: undefined symbol: _mingw_app_type
          >>> referenced by C:\rust\rustup\toolchains\stable-i686-pc-windows-gnu
\lib\rustlib\i686-pc-windows-gnu\lib\self-contained\crt2.o:(_pre_c_init)
          >>> referenced by C:\rust\rustup\toolchains\stable-i686-pc-windows-gnu
\lib\rustlib\i686-pc-windows-gnu\lib\self-contained\crt2.o:(___tmainCRTStartup)
          >>> referenced by C:\rust\rustup\toolchains\stable-i686-pc-windows-gnu
\lib\rustlib\i686-pc-windows-gnu\lib\self-contained\crt2.o:(___tmainCRTStartup)
          >>> referenced by C:\rust\rustup\toolchains\stable-i686-pc-windows-gnu
\lib\rustlib\i686-pc-windows-gnu\lib\self-contained\crt2.o:(_WinMainCRTStartup)
          >>> referenced by C:\rust\rustup\toolchains\stable-i686-pc-windows-gnu
\lib\rustlib\i686-pc-windows-gnu\lib\self-contained\crt2.o:(_mainCRTStartup)

          lld-link: error: undefined symbol: __fmode
          >>> referenced by C:\rust\rustup\toolchains\stable-i686-pc-windows-gnu
\lib\rustlib\i686-pc-windows-gnu\lib\self-contained\crt2.o:(_pre_c_init)

          lld-link: error: undefined symbol: ___onexitend
          >>> referenced by C:\rust\rustup\toolchains\stable-i686-pc-windows-gnu
\lib\rustlib\i686-pc-windows-gnu\lib\self-contained\crt2.o:(_pre_c_init)

          lld-link: error: undefined symbol: ___onexitbegin
          >>> referenced by C:\rust\rustup\toolchains\stable-i686-pc-windows-gnu
\lib\rustlib\i686-pc-windows-gnu\lib\self-contained\crt2.o:(_pre_c_init)

          lld-link: error: undefined symbol: __declspec(dllimport) __fmode
          >>> referenced by C:\rust\rustup\toolchains\stable-i686-pc-windows-gnu
\lib\rustlib\i686-pc-windows-gnu\lib\self-contained\crt2.o:(_pre_c_init)

          lld-link: error: undefined symbol: __MINGW_INSTALL_DEBUG_MATHERR
          >>> referenced by C:\rust\rustup\toolchains\stable-i686-pc-windows-gnu
\lib\rustlib\i686-pc-windows-gnu\lib\self-contained\crt2.o:(_pre_c_init)

          lld-link: error: undefined symbol: __newmode
          >>> referenced by C:\rust\rustup\toolchains\stable-i686-pc-windows-gnu
\lib\rustlib\i686-pc-windows-gnu\lib\self-contained\crt2.o:(_pre_cpp_init)

          lld-link: error: undefined symbol: __dowildcard
          >>> referenced by C:\rust\rustup\toolchains\stable-i686-pc-windows-gnu
\lib\rustlib\i686-pc-windows-gnu\lib\self-contained\crt2.o:(_pre_cpp_init)

          lld-link: error: undefined symbol: ___chkstk_ms
          >>> referenced by C:\rust\rustup\toolchains\stable-i686-pc-windows-gnu
\lib\rustlib\i686-pc-windows-gnu\lib\self-contained\crt2.o:(___tmainCRTStartup)

          lld-link: error: undefined symbol: ___native_startup_lock
          >>> referenced by C:\rust\rustup\toolchains\stable-i686-pc-windows-gnu
\lib\rustlib\i686-pc-windows-gnu\lib\self-contained\crt2.o:(___tmainCRTStartup)
          >>> referenced by C:\rust\rustup\toolchains\stable-i686-pc-windows-gnu
\lib\rustlib\i686-pc-windows-gnu\lib\self-contained\crt2.o:(___tmainCRTStartup)

          lld-link: error: undefined symbol: ___native_startup_state
          >>> referenced by C:\rust\rustup\toolchains\stable-i686-pc-windows-gnu
\lib\rustlib\i686-pc-windows-gnu\lib\self-contained\crt2.o:(___tmainCRTStartup)
          >>> referenced by C:\rust\rustup\toolchains\stable-i686-pc-windows-gnu
\lib\rustlib\i686-pc-windows-gnu\lib\self-contained\crt2.o:(___tmainCRTStartup)
          >>> referenced by C:\rust\rustup\toolchains\stable-i686-pc-windows-gnu
\lib\rustlib\i686-pc-windows-gnu\lib\self-contained\crt2.o:(___tmainCRTStartup)
          >>> referenced by C:\rust\rustup\toolchains\stable-i686-pc-windows-gnu
\lib\rustlib\i686-pc-windows-gnu\lib\self-contained\crt2.o:(___tmainCRTStartup)
          >>> referenced by C:\rust\rustup\toolchains\stable-i686-pc-windows-gnu
\lib\rustlib\i686-pc-windows-gnu\lib\self-contained\crt2.o:(___tmainCRTStartup)
          >>> referenced by C:\rust\rustup\toolchains\stable-i686-pc-windows-gnu
\lib\rustlib\i686-pc-windows-gnu\lib\self-contained\crt2.o:(___tmainCRTStartup)
          >>> referenced by C:\rust\rustup\toolchains\stable-i686-pc-windows-gnu
\lib\rustlib\i686-pc-windows-gnu\lib\self-contained\crt2.o:(___tmainCRTStartup)

          lld-link: error: undefined symbol: ___dyn_tls_init_callback
          >>> referenced by C:\rust\rustup\toolchains\stable-i686-pc-windows-gnu
\lib\rustlib\i686-pc-windows-gnu\lib\self-contained\crt2.o:(___tmainCRTStartup)

          lld-link: error: undefined symbol: ___mingw_oldexcpt_handler
          >>> referenced by C:\rust\rustup\toolchains\stable-i686-pc-windows-gnu
\lib\rustlib\i686-pc-windows-gnu\lib\self-contained\crt2.o:(___tmainCRTStartup)

          lld-link: error: undefined symbol: __declspec(dllimport) __acmdln
          >>> referenced by C:\rust\rustup\toolchains\stable-i686-pc-windows-gnu
\lib\rustlib\i686-pc-windows-gnu\lib\self-contained\crt2.o:(___tmainCRTStartup)

          lld-link: error: undefined symbol: __declspec(dllimport) ___initenv
          >>> referenced by C:\rust\rustup\toolchains\stable-i686-pc-windows-gnu
\lib\rustlib\i686-pc-windows-gnu\lib\self-contained\crt2.o:(___tmainCRTStartup)

          lld-link: error: undefined symbol: ___xc_z
          >>> referenced by C:\rust\rustup\toolchains\stable-i686-pc-windows-gnu
\lib\rustlib\i686-pc-windows-gnu\lib\self-contained\crt2.o:(___tmainCRTStartup)

          lld-link: error: too many errors emitted, stopping now (use /errorlimi
t:0 to see all errors)


error: aborting due to previous error

error: could not compile `hello_rust`.

To learn more, run the command again with --verbose.


The only way to fix all this would seemingly be to ship the entire MINGW tool chain along with rust.

**Comment by mati865** [comment]
Limited support for rust-lld has recently landed in nightly: https://github.com/rust-lang/rust/pull/75483

I'll look into it tomorrow, this unformatted log is unreadable on the mobile.

**Comment by mati865** [comment]
Works properly on nightly:
```
$ CARGO_TARGET_I686_PC_WINDOWS_GNU_LINKER=rust-lld cargo +nightly-i686-pc-windows-gnu build
   Compiling hello v0.1.0 (D:\tmp\hello)
    Finished dev [unoptimized + debuginfo] target(s) in 0.66s

$ rustc +nightly-i686-pc-windows-gnu -vV
rustc 1.48.0-nightly (5099914a1 2020-09-08)
binary: rustc
commit-hash: 5099914a16a215794ad243df0cc7a05d91d168e0
commit-date: 2020-09-08
host: i686-pc-windows-gnu
release: 1.48.0-nightly
LLVM version: 11.0
```

**Comment by Keithcat1** [comment]
Ahh thanks, it works for me now that I'm using nightly.
