### ISSUE TITLE
Can't install rust by srcript on i586 os 

### ISSUE THREAD

**Issue by xky0007** [rust-lang/rust#76506]
I may ask one rookie issue but I really wanna know why.  

I have a hardware that come with CPU : `Quark SoC X1000`, which output `i586` when I type `uname -m`.

I also found `i586-unknown-linux-gnu` is supported by check `rustc --print target-list`.

When I try to install rust by `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`

It give me this error `rustup: unknown CPU type: i586`.

Any idea?

**Comment by mati865** [comment]
`i586-unknown-linux-gnu` is available only as the target, it cannot be installed as the host.

**Comment by jonas-schievink** [comment]
Closing as expected behavior.

**Comment by xky0007** [comment]
> `i586-unknown-linux-gnu` is available only as the target, it cannot be installed as the host.

Is there any doc to show which are supported host? Thanks.

**Comment by mati865** [comment]
The doc is here: https://doc.rust-lang.org/nightly/rustc/platform-support.html

**Comment by xky0007** [comment]
> The doc is here: https://doc.rust-lang.org/nightly/rustc/platform-support.html

Thanks:D
