### ISSUE TITLE
#[link_section] is unsound on Harvard architectures

### ISSUE THREAD

**Issue by H2CO3** [rust-lang/rust#76507]
As pointed out in [this thread on URLO](https://users.rust-lang.org/t/is-the-link-section-attribute-unsound-on-avr/), it is possible to read arbitrary memory without `unsafe` using the `link_section` attribute on architectures with separate address spaces for code and data.

To cite OP's code: 
```rust
// Store PROG_BLOB in program space, ".text" would also work
#[link_section = ".progmem"]
static PROG_BLOB: [u8; 128] = [42; 128];

fn main() -> ! {
    let mut serial = /* initialize a serial output */;

    let mut idx = 0;
    loop {
        // This access is illegal, because Rust will emit a normal load
        // instruction, whereas the data is in the program space,
        // requiring a special load instruction.
        let b = PROG_BLOB[idx];

        // Dumping arbitrary RAM data!
        ufmt::uwrite!(&mut serial, "{:?} ", b).void_unwrap();

        idx += 1;
        if idx == BIG_BLOB.len() {
            break
        }
    }
    loop {
        // Just loop forever
    }
}

```

I expected to see this happen: the code should not compile, as it reads OOB memory.

Instead, this happened: The code compiles and outputs incorrect values, indicating UB.

**Comment by Nemo157** [comment]
See also https://github.com/rust-lang/rust/issues/28179 and https://github.com/rust-lang/rust/pull/72209, maybe this attribute could also be pulled under the `unsafe_code` lint (even on non-Harvard architectures it seems plausible that there's some way to cause unsoundness with it depending on the default linker scripts?).

**Comment by apiraino** [comment]
Assigning `P-low` as discussed as part of the [Prioritization Working Group procedure](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/I-prioritize.20.2376507.20.23.5Blink_section.5D.20is.20unsound.20on.20Harvard.20a.E2.80.A6) and removing `I-prioritize`.

**Comment by DemiMarie** [comment]
I’m pretty sure `#[link_section]` is unsafe anyway.  At a minimum I suspect you can segfault by putting a function in non-executable memory, or break assumptions by putting an (immutable) static with a nonzero value in a section that gets zeroed.

**Comment by RalfJung** [comment]
Ideally this concern is documented somewhere with that attribute basically in the safety docs for the attribute.

**Comment by RalfJung** [comment]
Ah, but that's not an I-unsound issue, so maybe let's track adding documentation in https://github.com/rust-lang/rust/issues/123757 instead.
