### ISSUE TITLE
rustdoc renames parameters with `mut` in async fn

### ISSUE THREAD

**Issue by ebkalderon** [rust-lang/rust#76517]
### Original:

```rust
pub struct Foo;

impl Foo {
    pub async fn good(self, first: usize, second: usize) {}
    pub async fn bad(mut self, mut first: usize, mut second: usize) {}
}
```

### Rendered:

<img width="1016" alt="rustdoc output screenshot" src="https://user-images.githubusercontent.com/322831/92597585-32f60e00-f2da-11ea-9a0a-16d51376a5db.png">

This example was tested on Rust 1.46.0, but it has been broken for quite a while. For example, see [`Server::serve()`](https://docs.rs/tower-lsp/0.7.0/tower_lsp/struct.Server.html#method.serve) in `tower-lsp` version 0.7.0 (built with Rust 1.43.0-nightly, see [docs.rs build info](https://docs.rs/crate/tower-lsp/0.7.0/builds)).

**Comment by jyn514** [comment]
Relevant code: https://github.com/rust-lang/rust/blob/c9a48d1d73f71fbe5f2ea72485fd2a8a94e65934/src/librustdoc/html/format.rs#L992
Not sure what's going wrong.

**Comment by ebkalderon** [comment]
Thanks for the helpful hint, @jyn514! However, I'm not convinced this is the root cause because it's happening to all function arguments, not just to `async` functions with `self` as the first argument. For example, this free function emits similar results:

```rust
pub async fn bad(mut first: usize, mut second: usize) {}
```

<img width="1004" alt="Screen Shot 2020-09-15 at 9 56 26 AM" src="https://user-images.githubusercontent.com/322831/93155960-bd56cb80-f739-11ea-8a90-41d93071467b.png">

I think the actual root cause may be deeper than the interpretation of `Self` types, but I can't tell for sure.

**Comment by ebkalderon** [comment]
This example confirms that the behavior appears to be per-argument instead of per-function. It's not like one bad argument ruins the formatting of the entire function.

```rust
pub async fn foo(good: usize, mut bad: usize) {}
```

<img width="983" alt="Screen Shot 2020-09-15 at 10 04 39 AM" src="https://user-images.githubusercontent.com/322831/93156516-e2980980-f73a-11ea-99d1-53aaec1ac015.png">

Perhaps we could investigate where in the code the `__argN` text is being generated and work our way backwards to see what is triggering it?

**Comment by ebkalderon** [comment]
Hmm, the only relevant location I could find through GitHub search is in `rustc_ast_lowering` in `item.rs`:

https://github.com/rust-lang/rust/blob/94b4de0e0793c8921d30e0fb886be712d17db6e5/compiler/rustc_ast_lowering/src/item.rs#L1104

Is `rustdoc` operating on a desugared form of the AST? I don't think this is the case, since `async fn` is being successfully displayed here. Is there something else I'm missing?

**Comment by jyn514** [comment]
Here's the issue: https://github.com/rust-lang/rust/blob/master/compiler/rustc_ast_lowering/src/item.rs#L1096-L1109

Looks like it should use `hir::PatKind::Binding(_, _, ident, _) => {` instead. Are you interested in making a PR?

**Comment by jyn514** [comment]
> Is rustdoc operating on a desugared form of the AST? I don't think this is the case, since async fn is being successfully displayed here. Is there something else I'm missing?

Yes, rustdoc works on an desugared version and has to reconstruct the `async` by hand.

**Comment by ebkalderon** [comment]
Sure, @jyn514! I will prepare one right away. Thanks for investigating with me. 😄
