### ISSUE TITLE
str::split_once is underpowered

### ISSUE THREAD

**Issue by HeroicKatora** [rust-lang/rust#76512]
This nightly feature (#74773) makes it easy to parse key-value pairs or lists.

I could have used this method recently but required the matching character as well. Problematically it would have used a predicate pattern for finding one of several characters. To retrieve it separately is quite awkward with lots of index logic and some unwrap. Should there be a set of alternative method (or this method changed) that returns the separator as well? I'd implement that new set or change the existing methods but wanted to have some feedback on the idea first.

Rough draft of code I wanted to use:

```rust
let key_value: &str = _;
if let Some((lhs, sep, rhs)) = key_value.split_once(|ch| ch == '=' || ch == ':') {
    // handle
}
```

cc:  @matklad

**Comment by Nicholas-Baron** [comment]
Looking at your example, the type signature would be roughly
```rust
fn split_once<'a>(&'a self, p: impl Pattern<'a>) -> Option<(&'a str, &'a str, &'a str)>
```
[`Pattern`](https://doc.rust-lang.org/nightly/std/str/pattern/trait.Pattern.html) already has the ability to take a predicate, so only changing the return type is required.

**Comment by HeroicKatora** [comment]
Right. I think the information already exists in the implementation as well. We only need to squeeze in the middle between `start` and `end` as returned by the pattern. The unknowns for me are:

* Is this sound? I think so as both need to be char boundaries already.
* Is this wanted? As as mentioned there are workarounds so it may be more useful to keep the interface for it being the 'common case'.
* Is it ergonomic? The type signature is harder to read, quite a lot. For three items the order is less obvious.

**Comment by Nicholas-Baron** [comment]
There is a [`split_inclusive`](https://doc.rust-lang.org/nightly/std/primitive.str.html#method.split_inclusive) function that does something akin to what you want. Maybe the function you want is something like a `split_once_inclusive`.

**Comment by HeroicKatora** [comment]
It seems somewhat similar. Curiously it also discards some information, namely the `start` of the pattern match, but it wouldn't be too tragic as the reconstruction is much simpler. One could do `.chars().last().unwrap()`.

**Comment by matklad** [comment]
It's interesting that basically all string APIs are underpowered in this way? Both `find` and `split` don't return the matched pattern.

**Comment by matklad** [comment]
Closing this issue, we stabilized split_once with the same API shape as the rest of string methods.
