### ISSUE TITLE
Incorrect suggestion if T implements Add but not &T

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#76539]
Consider the following code ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=fc50567da4e356940fbf945ab1f8b53d)):
```rust
use core::ops::Add;

fn sum<T: Add<usize, Output = usize>>(list: &[T]) -> usize {
    let mut counter: usize = 0;
    for number in list {
        counter = number + counter;
    }
    return counter;
}
```
```
error[E0369]: cannot add `usize` to `&T`
 --> src/lib.rs:6:26
  |
6 |         counter = number + counter;
  |                   ------ ^ ------- usize
  |                   |
  |                   &T
  |
help: consider further restricting this bound
  |
3 | fn sum<T: Add<usize, Output = usize> + std::ops::Add<Output = usize>>(list: &[T]) -> usize {
  |                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
This error is spectacularly unhelpful. `T` already implements the suggested trait, so there's no need to add it again. It should instead suggest to add a dereference:
```rust
        counter = *number + counter;
```

**Comment by lcnr** [comment]
wouldn't this also require `T` to be copy. I would expect a help message recommending `where &T: Add<usize, Output = usize>` here

**Comment by jyn514** [comment]
Yes, that seems fine :) it's at least showing the `T` vs `&T` distinction.
