### ISSUE TITLE
More Self usage in PartialOrd trait docs example

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust#76542]
In this docs page:
https://doc.rust-lang.org/nightly/std/cmp/trait.PartialOrd.html

There's this code:

```rust
use std::cmp::Ordering;

#[derive(Eq)]
struct Person {
    id: u32,
    name: String,
    height: u32,
}

impl PartialOrd for Person {
    fn partial_cmp(&self, other: &Person) -> Option<Ordering> {
        Some(self.cmp(other))
    }
}

impl Ord for Person {
    fn cmp(&self, other: &Person) -> Ordering {
        self.height.cmp(&other.height)
    }
}

impl PartialEq for Person {
    fn eq(&self, other: &Person) -> bool {
        self.height == other.height
    }
}
```

But I think docs must show the best and up to date idioms, so I think it should be replaced with (some `Person` replaced by more DRY `Self`):

```rust
use std::cmp::Ordering;

#[derive(Eq)]
struct Person {
    id: u32,
    name: String,
    height: u32,
}

impl PartialOrd for Person {
    fn partial_cmp(&self, other: &Self) -> Option<Ordering> {
        Some(self.cmp(other))
    }
}

impl Ord for Person {
    fn cmp(&self, other: &Self) -> Ordering {
        self.height.cmp(&other.height)
    }
}

impl PartialEq for Person {
    fn eq(&self, other: &Self) -> bool {
        self.height == other.height
    }
}
```

**Comment by leonardo-m** [comment]
Something similar could be done for Sub:
https://doc.rust-lang.org/nightly/std/ops/trait.Sub.html

**Comment by leonardo-m** [comment]
This needs a enhancement_request tag, I can't add it.

**Comment by LeSeulArtichaut** [comment]
@leonardo-m You can use the Rustbot to set labels for you:

@rustbot modify labels: C-enhancement T-doc

**Comment by jyn514** [comment]
@leonardo-m are you interested in making this enhancement yourself? ;) There are instructions at https://rustc-dev-guide.rust-lang.org/, although for something this simple you could probably get away with just web edits or `x.py check`.

**Comment by poliorcetics** [comment]
@rustbot claim

I'll start on that today, some crude regexes and `ripgrep` should help a lot.
