### ISSUE TITLE
Error or warn on links that start with `#` and recommend `self#` or `Self#` instead

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#76545]
Rustdoc should error or warn on links that start `#` and recommend `self#` for a module or `Self#` for a type.

_Originally posted [here](https://github.com/rust-lang/rust/pull/76497#discussion_r485908548) and [here](https://github.com/rust-lang/rust/pull/76497#discussion_r485968957)._

---

Cc @jyn514

@rustbot modify labels: A-intra-doc-links T-rustdoc

**Comment by jyn514** [comment]
Oops, we raced to open the issue. Closing in favor of https://github.com/rust-lang/rust/issues/76546 which has more details.

**Comment by camelid** [comment]
I thought Rust protected against races! 😉
