### ISSUE TITLE
rustup-init.exe install on windows 10 crash

### ISSUE THREAD

**Issue by zyc801208** [rust-lang/rust#76592]
PS E:\chrome_download> & '.\rustup-init (1).exe'

Welcome to Rust!

This will download and install the official compiler for the Rust
programming language, and its package manager, Cargo.

Rustup metadata and toolchains will be installed into the Rustup
home directory, located at:

  C:\Users\zhangyongcheng\.rustup

This can be modified with the RUSTUP_HOME environment variable.

The Cargo home directory located at:

  e:\rust\.cargo

This can be modified with the CARGO_HOME environment variable.

The cargo, rustc, rustup and other commands will be added to
Cargo's bin directory, located at:

  e:\rust\.cargo\bin

This path will then be added to your PATH environment variable by
modifying the HKEY_CURRENT_USER/Environment/PATH registry key.

You can uninstall at any time with rustup self uninstall and
these changes will be reverted.

Current installation options:
   default host triple: x86_64-pc-windows-msvc
     default toolchain: stable (default)
               profile: default
  modify PATH variable: yes

1) Proceed with installation (default)
2) Customize installation
3) Cancel installation
>1

info: profile set to 'default'
info: default host triple is x86_64-pc-windows-msvc
info: syncing channel updates for 'stable-x86_64-pc-windows-msvc'
thread 'main' panicked at 'byte index 64 is out of bounds of ``', /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7\src\libcore\str\mod.rs:1920:47
stack backtrace:
   0:     0x7ff61bd1b43b - <unknown>
   1:     0x7ff61b8b96cb - <unknown>
   2:     0x7ff61bd1a69e - <unknown>
   3:     0x7ff61bd19cfd - <unknown>
   4:     0x7ff61bd19127 - <unknown>
   5:     0x7ff61bd18a78 - <unknown>
   6:     0x7ff61bd20445 - <unknown>
   7:     0x7ff61b8b6ff0 - <unknown>
   8:     0x7ff61b8b8e52 - <unknown>
   9:     0x7ff61bd8a6d0 - <unknown>
  10:     0x7ff61bbcf9a7 - <unknown>
  11:     0x7ff61bbb8f0d - <unknown>
  12:     0x7ff61bbb02b8 - <unknown>
  13:     0x7ff61bbad118 - <unknown>
  14:     0x7ff61bbab859 - <unknown>
  15:     0x7ff61bcf5086 - <unknown>
  16:     0x7ff61bd04c44 - <unknown>
  17:     0x7ff61b8271d5 - <unknown>
  18:     0x7ff61bd3d6a6 - <unknown>
  19:     0x7ff61b82a4b7 - <unknown>
  20:     0x7ff61bddbbb0 - <unknown>
  21:     0x7ff861094034 - BaseThreadInitThunk
  22:     0x7ff863853691 - RtlUserThreadStart

**Comment by lzutao** [comment]
Hi, please move this issue into rustup repo at https://github.com/rust-lang/rustup/ .
Also please be aware of firewall might block connection to rustup server.

**Comment by zyc801208** [comment]
RUST_DIST_HOME
RUSTUP_UPDATE_ROOT

It's ok after set these two env var.
