### ISSUE TITLE
Rustdoc book not updated with latest changes

### ISSUE THREAD

**Issue by arijit79** [rust-lang/rust#76596]
I recently opened up a PR to add info about Inner and outer level documentation support available in `rustdoc` in the rustdoc book. Yesterday, It was merged to the master branch. See #76289. But I still couldn't see the changes in the [Rustdoc book](https://doc.rust-lang.org/rustdoc/index.html)

**Comment by jonas-schievink** [comment]
https://doc.rust-lang.org/nightly/rustdoc/index.html

**Comment by arijit79** [comment]
So when is it going to land in the stable rustdoc book

**Comment by jonas-schievink** [comment]
All content follows the release trains. Your PR was marked with the 1.48.0 milestone, so that's when it will land on stable.

**Comment by arijit79** [comment]
Ok. Thanks for your great help
