### ISSUE TITLE
rustdoc generates "Notable traits" that are impossible

### ISSUE THREAD

**Issue by cuviper** [rust-lang/rust#76590]
I just noticed that the [documentation](https://doc.rust-lang.org/nightly/std/vec/struct.Vec.html#method.spare_capacity_mut) on `Vec::spare_capacity_mut(&mut self) -> &mut [MaybeUninit<T>]` has a hover icon with "Notable traits for `&'_ [u8]`". `MaybeUninit<T>` can never be a `u8` (though it could be `MaybeUninit<u8>`), so this information is irrelevant.

![image](https://user-images.githubusercontent.com/36186/92832920-1b2b9200-f38d-11ea-9d15-dcaf3a9b3269.png)

I saw that on documentation for "Version 1.48.0-nightly (a1947b3f9 2020-09-10)".

**Comment by scottmcm** [comment]
Related: https://github.com/rust-lang/rust/issues/55082

**Comment by notriddle** [comment]
This was a duplicate of #91347, and was fixed by #91366.

**Comment by cuviper** [comment]
Thanks, I've confirmed that it's gone in current nightly docs.
