### ISSUE TITLE
Transient segfault in libstd on Github Actions

### ISSUE THREAD

**Issue by Aaron1011** [rust-lang/rust#76594]
The `x86_64-gnu-distcheck` job segfaulted while running a libstd test in this PR: https://github.com/rust-lang/rust/pull/75800#issuecomment-690827038

Full log: https://gist.github.com/Aaron1011/22e231f0910700469a93c03953e68219

After a retry, the job succeeded. I'm not sure what caused this segfault, as it seems completely unrelated to my PR.

**Comment by Enselic** [comment]
Triage: Have you seen this in recent years?

**Comment by jieyouxu** [comment]
Triage: closing due to lack of recent repros, feel free to open a new issue if this is still happening.
