### ISSUE TITLE
Allow `--set path.to.field=value` in x.py itself

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#76616]
Right now, several options are duplicated between `config.toml` and CLI arguments to x.py itself (e.g. `-i` and `incremental = true`). It would be great make this consistent, so that *all* options can be either TOML options or CLI arguments. All existing arguments would still be present as aliases for the new behavior (so `-i` would alias to `--set incremental=true`).

**Comment by jyn514** [comment]
@Mark-Simulacrum do you still think this would be useful?

**Comment by Mark-Simulacrum** [comment]
Seems plausible to be helpful. No particular opinion; if it complicates the implementation quite a bit I wouldn't do it I suspect.

**Comment by jyn514** [comment]
I don't think this is super useful.
