### ISSUE TITLE
Add default configuration files for `x.py`

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#76619]
Currently, the options are 'use the defaults' or 'read the 600 line `config.toml.example`. Even with recommended defaults from rustc-dev-guide, this is not really ideal for new contributors. As an alternative, there could be different config files for each type of user:

- distro maintainers and people compiling from source
- contributors to the standard library or documentation
- contributors to the compiler
- contributors to the compiler + llvm

To avoid these getting out of date, they could be included instead of copied: `include = "maintainer"` in `config.toml` or something like that. This would also make it clear which changes are automatic and which were made by the user: the automatic changes are not in the same file.

I'm imaging that the files live in `src/bootstrap/config.toml.maintainer` or similar.

**Comment by jyn514** [comment]
This will be annoying to implement by hand because of all the nested structs ... @Mark-Simulacrum do you mind if I use https://docs.rs/merge/0.1.0/merge/ or similar to implement it?

**Comment by est31** [comment]
Another use case: contributions to documentation.

**Comment by jyn514** [comment]
@est31 hmm, when writing this I lumped that together with 'contributors to the standard library' in my mind - do you expect the defaults to be different between them? I guess one difference is that writing docs would _only_ run `x.py doc`, not any other command, but that seems more like something to suggest in #76503 rather than having a different config file.

**Comment by est31** [comment]
Good point, they fit into that category really well.
