### ISSUE TITLE
pc-windows-msvc and apple-darwin targets missing from nightly

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#76638]
Several tier 1 targets seem to be missing from the last nightly and also from what `rustup-toolchain-install-master` installs:
* https://rust-lang.github.io/rustup-components-history/i686-pc-windows-msvc.html
* https://rust-lang.github.io/rustup-components-history/x86_64-pc-windows-msvc.html
* https://rust-lang.github.io/rustup-components-history/x86_64-apple-darwin.html

Cc @rust-lang/infra

**Comment by RalfJung** [comment]
GH actions show [many skipped jobs](https://github.com/rust-lang/rust/runs/1105272140), not sure if that's normal... and no idea how to access the actual CI build for these commits.

**Comment by RalfJung** [comment]
And what's up with the [auto branch](https://github.com/rust-lang/rust/commits/auto) having its latest commit from March?!?

**Comment by RalfJung** [comment]
Ah, looks like that branch was [moved](https://github.com/rust-lang-ci/rust/tree/auto) but the old one not deleted or so...

**Comment by Mark-Simulacrum** [comment]
Fixed in https://github.com/rust-lang/rust/pull/76639, hopefully.

**Comment by jyn514** [comment]
Regressed in https://github.com/rust-lang/rust/pull/76415

**Comment by RalfJung** [comment]
Indeed fixes by https://github.com/rust-lang/rust/pull/76639, thanks!
