### ISSUE TITLE
Excessive memory usage on old packed-simd version

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rust#76647]
I tried this code:

https://github.com/rust-lang/rustc-perf/tree/6906bc305feb0d9dc52aff6a1700effd87c282db/collector/benchmarks/packed-simd

I expected to see this happen: Compilation using `cargo check --all-targets` runs with a reasonable memory usage.

Instead, this happened: More than 7GB of memory was used

### Meta

`rustc --version --verbose`:
```
rustc 1.48.0-nightly (99111606f 2020-09-11)
binary: rustc
commit-hash: 99111606fcda4fdb0646e4f7ee0f6cbcb76fb84a
commit-date: 2020-09-11
host: x86_64-unknown-linux-gnu
release: 1.48.0-nightly
LLVM version: 11.0
```

The last few lines of `-Ztime-passes` before it uses way too much memory are:

```
time: 0.000; rss: 164MB pre_AST_expansion_lint_checks
time: 0.000; rss: 164MB pre_AST_expansion_lint_checks
time: 0.000; rss: 164MB pre_AST_expansion_lint_checks
time: 0.000; rss: 164MB pre_AST_expansion_lint_checks
time: 17.172; rss: 3106MB       expand_crate
time: 0.000; rss: 3106MB        check_unused_macros
time: 17.172; rss: 3106MB       macro_expand_crate
time: 0.095; rss: 3106MB        maybe_building_test_harness
time: 0.082; rss: 3106MB        AST_validation
time: 0.000; rss: 3106MB        maybe_create_a_macro_crate
```

**Comment by jyn514** [comment]
> time: 0.000; rss: 164MB pre_AST_expansion_lint_checks
> time: 17.172; rss: 3106MB       expand_crate

Wow, that's a big jump! Might be related to macro expansion?

**Comment by bjorn3** [comment]
The old packed-simd no longer compiles with current rustc versions.
