### ISSUE TITLE
Tracking issue for const `Pin` methods

### ISSUE THREAD

**Issue by CDirkx** [rust-lang/rust#76654]
Constify methods of `core::pin::Pin` under the feature `const_pin`.

Implementation: #76655

Methods in `const_pin` (stable since https://github.com/rust-lang/rust/pull/130136):
- `new`
- `new_unchecked`
- `get_ref`
- `into_ref`
- `get_mut`
- `get_unchecked_mut`
- `static_ref`
- `static_mut`

Methods in `const_pin2`:
- `into_inner`
- `into_inner_unchecked`

The `const_pin2` methods will need `#[rustc_allow_const_fn_unstable(const_precise_live_drops)]` but that has been approved [here](https://github.com/rust-lang/rust/pull/130136#issuecomment-2395125534).

**Comment by ecstatic-morse** [comment]
As you mention in #76655 PR, the implementation of some of these methods depends on the unstable `const_precise_live_drops` feature. Future readers should check the status of that feature before attempting to stabilize these. #76618 will ensure that this does not happen by accident.

**Comment by RalfJung** [comment]
@dtolnay [wrote](https://github.com/rust-lang/rust/pull/130136#issuecomment-2420025735)
> I'd be happy to take a separate PR for the const-stabilizing of into_inner + into_inner_unchecked. Procedurally I think a fresh FCP would be required.

So, let's get that train rolling -- @rust-lang/libs-api can we const-stabilize `Pin::into_inner` and `Pin::into_inner_unchecked` (already stable outside const)?

**Comment by dtolnay** [comment]
@rfcbot fcp merge

**Comment by tgross35** [comment]
> can we const-stabilize the `const_pin2` feature gate, which guards `Pin::into_inner` and `Pin::into_inner_unchecked`

Since this will likely be the same release cycle, the `const_pin2` items can probably just be grouped back into `const_pin`.

**Comment by RalfJung** [comment]
Stabilization PR is up at https://github.com/rust-lang/rust/pull/133127

**Comment by RalfJung** [comment]
This got closed by https://github.com/rust-lang/rust/pull/131904
