### ISSUE TITLE
Support `./x.py run miri`

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#76666]
It would be great to have a way to run the in-tree Miri on a given file (similar to `./miri run` in the Miri repo). That should even work with the stage 0 Miri, given that Miri's test suite also passes for stage 0.

However, I am not sure what the best `x.py` interface for this would look like, and how to integrate it. Cc @Mark-Simulacrum

**Comment by Mark-Simulacrum** [comment]
Can you point me to documentation or explain what exactly is being asked for here, in particular, I presume `cargo miri run` and `cargo miri test` are what we want to do, but I am not sure what those two commands do. Should I just read https://github.com/rust-lang/miri/blob/master/cargo-miri/bin.rs?

**Comment by jyn514** [comment]
`./x.py run rustdoc f.rs` would also be nice as an alias for `x.py build src/tools/rustdoc library/std && rustdoc +stage1 f.rs`.

**Comment by RalfJung** [comment]
@Mark-Simulacrum basically, it should do the equivalent of [this](https://github.com/rust-lang/miri/blob/2249c10507cdf80394e6fd73cb602ded86b275db/miri#L149). Up until [here](https://github.com/rust-lang/rust/blob/17d32770649fefe8efe6510f7dbff6123f544ba6/src/bootstrap/test.rs#L431), it's basically the same as what happens for testing, but then the final step "Run `cargo test`" needs to be replaced by running the Miri driver binary instead. I'm happy to help with that part.

**Comment by camelid** [comment]
It would be nice if we had this for rustdoc, which would let you get around the issue described [here](https://github.com/rust-lang/rust/issues/81930#issuecomment-817373384). Something like `./x.py run rustdoc`.
