### ISSUE TITLE
rustdoc: Update pulldown-cmark to 0.8

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#76687]
Thanks to @marcusklaas's great work, pulldown-cmark now supports smart punctuation! This means that rustdoc can now have smart apostrophes, dashes, etc.

---

@rustbot modify labels: T-rustdoc C-enhancement

**Comment by camelid** [comment]
It looks like there are a few breaking changes in the API:

```console
$ ./x.py build --stage 1
error[E0308]: mismatched types
   --> src/librustdoc/html/markdown.rs:942:72
    |
934 |           let replacer = |_: &str, s: &str| {
    |  ________________________-
935 | |             if let Some(link) = links.iter().find(|link| &*link.original_text == s) {
936 | |                 Some((link.href.clone(), link.new_text.clone()))
937 | |             } else {
938 | |                 None
939 | |             }
940 | |         };
    | |_________- the found closure
941 | 
942 |           let p = Parser::new_with_broken_link_callback(md, opts(), Some(&replacer));
    |                                                                          ^^^^^^^^^ types differ in mutability
    |
    = note: expected mutable reference `&mut dyn for<'r> std::ops::FnMut(pulldown_cmark::BrokenLink<'r>) -> std::option::Option<(pulldown_cmark::CowStr<'_>, pulldown_cmark::CowStr<'_>)>`
                       found reference `&[closure@src/librustdoc/html/markdown.rs:934:24: 940:10 links:_]`

error[E0308]: mismatched types
    --> src/librustdoc/html/markdown.rs:1023:18
     |
1012 |           let replacer = |_: &str, s: &str| {
     |  ________________________-
1013 | |             if let Some(link) = links.iter().find(|link| &*link.original_text == s) {
1014 | |                 Some((link.href.clone(), link.new_text.clone()))
1015 | |             } else {
1016 | |                 None
1017 | |             }
1018 | |         };
     | |_________- the found closure
...
1023 |               Some(&replacer),
     |                    ^^^^^^^^^ types differ in mutability
     |
     = note: expected mutable reference `&mut dyn for<'r> std::ops::FnMut(pulldown_cmark::BrokenLink<'r>) -> std::option::Option<(pulldown_cmark::CowStr<'_>, pulldown_cmark::CowStr<'_>)>`
                        found reference `&[closure@src/librustdoc/html/markdown.rs:1012:24: 1018:10 links:_]`

error[E0308]: mismatched types
    --> src/librustdoc/html/markdown.rs:1091:72
     |
1087 |           let push = |_: &str, s: &str| {
     |  ____________________-
1088 | |             shortcut_links.borrow_mut().push((s.to_owned(), locate(s)));
1089 | |             None
1090 | |         };
     | |_________- the found closure
1091 |           let p = Parser::new_with_broken_link_callback(md, opts(), Some(&push));
     |                                                                          ^^^^^ types differ in mutability
     |
     = note: expected mutable reference `&mut dyn for<'r> std::ops::FnMut(pulldown_cmark::BrokenLink<'r>) -> std::option::Option<(pulldown_cmark::CowStr<'_>, pulldown_cmark::CowStr<'_>)>`
                        found reference `&[closure@src/librustdoc/html/markdown.rs:1087:20: 1090:10 shortcut_links:_, locate:_]`

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0308`.
error: could not compile `rustdoc`.
```

**Comment by marcusklaas** [comment]
Yup, the broken link callback type changed. Instead of two strings, you are now passed a [`BrokenLink`](https://docs.rs/pulldown-cmark/0.8.0/pulldown_cmark/struct.BrokenLink.html), which contains the reference that was previously passed, amongst other things. It also expects you to return [`CowStr`](https://docs.rs/pulldown-cmark/0.8.0/pulldown_cmark/enum.CowStr.html)s, which can be created by calling `Into::into` on `char`s, `&str`s or `String`s. Finally, we now accept `FnMut`s, which means that we need a mutable reference to the callback instead of a regular reference.

Fundamentally, it works the same way as before. It should be relatively straightforward to make the changes. Hope the above helps!

**Comment by camelid** [comment]
Okay, thanks!

**Comment by camelid** [comment]
Hmm, I fixed the breaking changes, but it doesn't seem to be working:

![image](https://user-images.githubusercontent.com/37223377/93031171-9f745400-f5dd-11ea-824e-6b57a961775d.png)

That was generated by `build/x86_64-apple-darwin/stage1/bin/rustdoc` after I built it from this Markdown:

```markdown
# Test of "smart punctuation"

Hello there -- this is "smart punctuation"!
```

**Comment by marcusklaas** [comment]
I can't see the PR, but did you remember to enable the smart punctuation option? It's not enabled by default.

**Comment by camelid** [comment]
I haven't pushed it up yet, so that's why :)

Ah, I didn't realize it was a parser option, I thought it was enabled by default or a crate-level feature. Thanks!

**Comment by camelid** [comment]
That worked, but it looks like smart punctuation doesn't work in headers, is that intentional?

![image](https://user-images.githubusercontent.com/37223377/93031561-b10b2b00-f5e0-11ea-97c4-d4e3f1a4ce29.png)

**Comment by marcusklaas** [comment]
Erm, not that I know. I will investigate for a bit.

**Comment by marcusklaas** [comment]
I cannot reproduce this on pulldown itself -- seems to be working in titles there. Maybe rustdoc is doing something to titles? (I know nothing of rustdoc)

**Comment by camelid** [comment]
Okay, thanks for looking into it! Maybe rustdoc has some kind of custom header renderer.

**Comment by Dylan-DPC** [comment]
cc @GuillaumeGomez

**Comment by jyn514** [comment]
Oops, I made the same PR without noticing you were working on this: https://github.com/rust-lang/rust/pull/76689

**Comment by camelid** [comment]
Your PR does not seem to enable the smart punctuation option though. How about we keep your PR for upgrading, and then I'll work on enabling smart punctuation (there seem to be some issues with how rustdoc handles headers)?

**Comment by camelid** [comment]
Are you the new rustbot ;)
