### ISSUE TITLE
Cannot write doc-tests in markdown files

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#76709]
Currently, it gives this error:
```
error[E0585]: found a documentation comment that doesn't document anything
 --> /checkout/src/doc/rustdoc/src/what-to-include.md:68:1
  |
7 | /// ```
  | ^^^^^^^
  |
  = help: doc comments must come before what they document, maybe a comment was intended with `//`?
```
Rustdoc should _always_ run doctests in markdown, since there's no code to document.

_Originally posted by @jyn514 in https://github.com/rust-lang/rust/pull/75778#r475234292_

**Comment by GuillaumeGomez** [comment]
I tested with:

``````text
# hello

This is test time!

```rust
let x = 12;
```
``````

And ran it without issues:

```bash
$ rustdoc --test foo.md 

running 1 test
test foo.md - hello (line 5) ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

**Comment by GuillaumeGomez** [comment]
Just like @steveklabnik pointed out, a bit more context would be welcome. :)

**Comment by jyn514** [comment]
Hmm, I can no longer reproduce this. @AndyGauge do you happen to have a copy of the code that caused this failure? The error message in https://github.com/rust-lang/rust/pull/75778/commits/e9e5b2a324c2063a0c5f9b74bf8a596a3d50f18e#r475216718 doesn't match up with the code you have.
