### ISSUE TITLE
Add docs for `mir::BasicBlock`

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#76715]
@rustbot modify labels: A-mir T-doc C-enhancement E-easy

**Comment by camelid** [comment]
I would be interested in doing this :)

@rustbot claim

**Comment by jyn514** [comment]
Should this be on rustc-dev-guide?

**Comment by camelid** [comment]
I'm not sure if it's covered there, but I meant in terms of a doc comment on the struct.

**Comment by jyn514** [comment]
Ok, take a look around https://rustc-dev-guide.rust-lang.org/mir/index.html?highlight=basicblock#mir-data-types then. But you might want to discuss around Zulip what the convention is for doc-comments.

**Comment by camelid** [comment]
Hmm, I think most of the items in MIR have doc comments. I can ask on Zulip though.
