### ISSUE TITLE
cargo run:Error finalizing incremental compilation session directory ... Permission denied (os error 13)

### ISSUE THREAD

**Issue by SJanJan** [rust-lang/rust#76727]
what is the probrem? How to solve it？thank you.

**Comment by lzutao** [comment]
I recommend opening a topic in https://users.rust-lang.org/ first.
It is also very helpful to include a reproduce, if not the command you run,
OS version, filesystem type, Rust version, etc...
It's nothing we can do without those information.

**Comment by SJanJan** [comment]
> I recommend opening a topic in https://users.rust-lang.org/ first.
> It is also very helpful to include a reproduce, if not the command you run,
> OS version, filesystem type, Rust version, your network/firewalll conditions, etc...
> It's nothing we can do without those information.

en,than you.

**Comment by Guozhanxin** [comment]
### os
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
### kernel
Linux LAPTOP-HGRKL30R 4.4.0-18362-Microsoft #1049-Microsoft Thu Aug 14 12:01:00 PST 2020 x86_64 x86_64 x86_64 GNU/Linux
### rust
rustc --version
rustc 1.50.0 (cb75ad5db 2021-02-10)
cargo --version
cargo 1.50.0 (f04e7fab7 2021-02-04)
### filesystem
mount
rootfs on / type wslfs (rw,noatime)
none on /dev type tmpfs (rw,noatime,mode=755)
sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,noatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,noatime)
devpts on /dev/pts type devpts (rw,nosuid,noexec,noatime,gid=5,mode=620)
none on /run type tmpfs (rw,nosuid,noexec,noatime,mode=755)
none on /run/lock type tmpfs (rw,nosuid,nodev,noexec,noatime)
none on /run/shm type tmpfs (rw,nosuid,nodev,noatime)
none on /run/user type tmpfs (rw,nosuid,nodev,noexec,noatime,mode=755)
binfmt_misc on /proc/sys/fs/binfmt_misc type binfmt_misc (rw,relatime)
tmpfs on /sys/fs/cgroup type tmpfs (rw,nosuid,nodev,noexec,relatime,mode=755)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices)
C:\ on /mnt/c type drvfs (rw,noatime,uid=1000,gid=1000,case=off)
D:\ on /mnt/d type drvfs (rw,noatime,uid=1000,gid=1000,case=off)
E:\ on /mnt/e type drvfs (rw,noatime,uid=1000,gid=1000,case=off)
### log
![image](https://user-images.githubusercontent.com/25633294/112705835-6e090900-8edb-11eb-8597-9fab225a89e4.png)
