### ISSUE TITLE
Don't discourage people from using `std::fmt::Write`

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#76729]
The [docs for `std::fmt::Write`](https://doc.rust-lang.org/std/fmt/trait.Write.html) discourage using it outside of the standard library:

> […] This is similar to the standard library's io::Write trait, but it is only intended for use in libcore.
>
> This trait should generally not be implemented by consumers of the standard library. The `write!` macro accepts an instance of `io::Write`, and the `io::Write` trait is favored over implementing this trait.

Yet it is relatively often that one needs a trait for writing Unicode to a stream. For example, `pulldown-cmark` has a trait very similar to this one called [`StrWrite`](https://docs.rs/pulldown-cmark/0.8.0/pulldown_cmark/escape/trait.StrWrite.html).

When I [asked in Zulip](https://rust-lang.zulipchat.com/#narrow/stream/122651-general/topic/equivalent.20of.20.60io.3A.3AWrite.60.20that's.20string-oriented.3F), nobody seemed to know why that comment is there.

It would be good to have a standard that every library can use for this.

---

@rustbot modify labels: A-fmt T-libs T-doc

**Comment by joshtriplett** [comment]
@camelid I think there should be a more nuanced explanation there. It seems fine to impl `std::fmt::Write` if you *only* want to accept Unicode. If you can accept either raw bytes *or* Unicode, you should always prefer to implement `std::io::Write`, which works fine for UTF-8 bytes too.
