### ISSUE TITLE
compiler-docs: Missing trait impls for type

### ISSUE THREAD

**Issue by tesuji** [rust-lang/rust#76736]
This is a regression from stable to beta, although this issue will be P-low.
The problem is #73771 ignored documenting unstable traits for non-local types,
 #76571 fixes some regressions caused by it but the regression 
in nightly-rustc / compiler docs still opens.

For example: Compare https://doc.rust-lang.org/nightly/nightly-rustc/rustc_expand/base/struct.ExtCtxt.html#blanket-implementations and https://doc.rust-lang.org/1.46.0/nightly-rustc/rustc_expand/base/struct.ExtCtxt.html#blanket-implementations .

The doc in 1.46.0 has `MaybeResult` impl, while on nightly it doesn't have.

A way to fix this issue is ignoring this check when the compiling-crates 
are being passed `-Zforce-unstable-if-unmarked` flag or the crate/module has `rustc_private` feature: https://github.com/rust-lang/rust/blob/c743fc43420ff09a79cc23316e484631842556dc/src/librustdoc/clean/inline.rs#L345-L374

### Meta
`rustc --version --verbose`: Version 1.48.0-nightly (9b4154193 2020-09-14)

**Comment by jakevossen5** [comment]
Hey! I would like to check this out if that is okay

**Comment by camelid** [comment]
Is this actually a regression?

**Comment by Mark-Simulacrum** [comment]
Dropping regression label. nightly-rustc docs are, well, not really important on non-nightly channels, as they cannot be used by normal consumers.

**Comment by jyn514** [comment]
@jakevossen5 if you're still interested in working on this we'd love to have the help! 
If you have trouble, feel free to ask for help in [the rustdoc channel](https://discord.gg/4yEYPuT) or [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp) :)

**Comment by jakevossen5** [comment]
Thanks! Yes, I am still interested, I have been busy that past few weeks. I will give it a shot this weekend and will reach out if I can't figure it out!

**Comment by lzutao** [comment]
@jakevossen5 Since zulip is lag in my region at night, I post a respond here. 
You could use `self.sess.opts.debugging_opts.force_unstable_if_unmarked` to check for 
`-Zforce-unstable-if-unmarked` flag passed during compilation.

**Comment by leokhachatorians** [comment]
I think I'll hop onto this if that's OK. I've always wanted to contribute :)

**Comment by jakevossen5** [comment]
Go for it!

**Comment by ShoyuVanilla** [comment]
It doesn't seem to be fixed by #121218 😢 I'll check the cause
