### ISSUE TITLE
min-LLVM: Can only use x86 asm ATT syntax for LLVM < 10 in new `asm!`

### ISSUE THREAD

**Issue by tesuji** [rust-lang/rust#76738]
This is a tracking issue to remind when using `asm!` macro in Rust repo and its direct dependencies
like stdarch, we can only use x86 ATT syntax for LLVM < 10. That's because older LLVM versions 
don't support operand modifiers in intel syntax. Although as long as we stick to AT&T syntax 
and stick to general-purpose registers it should be fine.

@rustbot modify labels: A-LLVM F-asm T-compiler requires-nightly O-x86 

Some related discussions:
* https://github.com/rust-lang/rust/pull/76669#issuecomment-691673731

**Comment by bstrie** [comment]
As of this writing the minimum supported LLVM version is 8, correct? (I'm not sure precisely where this is documented.) Given that LLVM produces a new major release twice a year, might we reasonably expect the minimum supported LLVM version to increase to 10 by this time next year?

**Comment by steveklabnik** [comment]
As of Rust 1.49.0, the minimum LLVM version is 9 https://github.com/rust-lang/rust/blob/master/RELEASES.md#compiler-1

**Comment by nikic** [comment]
I believe our policy is to support the last 3 LLVM releases, so it should be fine to drop support for LLVM 9 now that we support LLVM 12.

**Comment by Amanieu** [comment]
Note that the LLVM patches needed to support Intel syntax for `asm!` were only merged in 10.0.1, not 10.0.0.

**Comment by Amanieu** [comment]
I've added a version check for LLVM 10.0.1 in #83889.

**Comment by Amanieu** [comment]
It turns out this check is not needed, intel syntax works fine on 10.0.0.
