### ISSUE TITLE
Miscompilation introduced by CopyPropagation

### ISSUE THREAD

**Issue by tmiasko** [rust-lang/rust#76740]
To reproduce the issue:
* Checkout 41dc3942eb33e8e882b6e4782a9bd9d2b8970647 (for reproducibility, but might be unnecessary).
* Enable copy propagation so that it runs on mir-opt-level=1.
* ./x.py test --stage 2 src/test/ui (disable incremental compilation, so that rustc is rebuild completely).
* Observe tests failures: "not all trait items implemented, missing ...".

**Comment by tmiasko** [comment]
The copy propagation incorrectly assumes that a use of a local in `Operand::Move` will not mutate it.

**Comment by jonas-schievink** [comment]
https://github.com/rust-lang/rust/pull/72632 has landed now, so we could remove CopyPropagation and focus on that instead
