### ISSUE TITLE
Rustdoc displays `macro`s as `macro_rules!`s

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#76761]
See for [`std::marker::Copy`]:

![image](https://user-images.githubusercontent.com/37223377/93266586-1dac3400-f75f-11ea-9495-0e23a79816af.png)

But when you click on `[src]`:

```rust
pub macro Copy($item:item) {
    /* compiler built-in */
}
```

---

Or for [`proc_macro::quote!`]:

![image](https://user-images.githubusercontent.com/37223377/93266783-724faf00-f75f-11ea-8a92-4d07886114a4.png)

With source:

```rust
pub macro quote($($t:tt)*) {
    /* compiler built-in */
}
```

---

Or for [`core::ready!`], which is **not** a built-in:

![image](https://user-images.githubusercontent.com/37223377/93266890-a75c0180-f75f-11ea-9b91-07ccbbc64f18.png)

```rust
pub macro ready($e:expr) {
    match $e {
        $crate::task::Poll::Ready(t) => t,
        $crate::task::Poll::Pending => {
            return $crate::task::Poll::Pending;
        }
    }
}
```

[`std::marker::Copy`]: https://doc.rust-lang.org/std/marker/macro.Copy.html
[`proc_macro::quote!`]: https://doc.rust-lang.org/proc_macro/macro.quote.html
[`core::ready!`]: https://doc.rust-lang.org/nightly/core/macro.ready.html

---

@rustbot modify labels: T-rustdoc C-bug

**Comment by jyn514** [comment]
Related: https://github.com/rust-lang/rust/issues/74355

**Comment by camelid** [comment]
I have a hunch that `macro_rules!` and `macro` are both represented as [`rustdoc::doctree::Macro`](https://doc.rust-lang.org/nightly/nightly-rustc/rustdoc/doctree/struct.Macro.html), and then serialized to `macro_rules!` in [`rustdoc::clean`](https://github.com/rust-lang/rust/blob/master/src/librustdoc/clean/mod.rs) and/or [`rustdoc::clean::inline`](https://github.com/rust-lang/rust/blob/master/src/librustdoc/clean/inline.rs).

**Comment by RalfJung** [comment]
Cc @GuillaumeGomez

**Comment by camelid** [comment]
I would experiment to see if that is what's causing it, but I'm waiting on a build for something else 😄

**Comment by jyn514** [comment]
> I would experiment to see if that is what's causing it, but I'm waiting on a build for something else 😄

https://rustc-dev-guide.rust-lang.org/building/suggested.html#working-on-multiple-branches-at-the-same-time

**Comment by camelid** [comment]
Wow, I never noticed that! That's so cool :)

**Comment by camelid** [comment]
Indeed, changing `rustdoc::clean` changed the output. See if you can notice my experimental change ;)

![image](https://user-images.githubusercontent.com/37223377/94205201-a588f100-fe77-11ea-8051-a0e38fe539c4.png)
