### ISSUE TITLE
library syntex_syntax doesn't parse "use crate::" statement.

### ISSUE THREAD

**Issue by 10ca1h0st** [rust-lang/rust#76779]
**I have a binary project.
Its src directory is like this:
src
 |-main.rs
 |-types.rs**

And the types.rs :
```
pub struct S1{
    m1: u64
}
```
the main.rs : 
```
mod types;
use crate::types::S1;

fn main() {
    //do something...
}
```

when i use syntex_syntax parse main.rs, error occurs.
But when main.rs is like this : 
```
mod types;
use types::S1;

fn main() {
    //do something...
}

```
error doesn't occur.

Why?

**Comment by lzutao** [comment]
It is a third party Rust crate and deprecated. You should switch to other crates.

**Comment by 10ca1h0st** [comment]
could you recommend some crates like syntex_syntax？I need to manipulate the rust AST.

**Comment by 10ca1h0st** [comment]
> could you recommend some crates like syntex_syntax？I need to manipulate the rust AST.



> It is a [third party Rust crate and deprecated](https://github.com/serde-deprecated/syntex). You should switch to other crates.

could you recommend some crates like syntex_syntax？I need to manipulate the rust AST.

**Comment by crlf0710** [comment]
docs.rs/syn
