### ISSUE TITLE
Diagnostic: suggest removing &mut instead of making the function argument mutable

### ISSUE THREAD

**Issue by BinAlyan** [rust-lang/rust#76793]
For the following code:

```
fn main() {
    let mut borrowed = 843;
    example(&mut borrowed);
}

fn example(borrowed: &mut usize) {
    example2(&mut borrowed);
}

fn example2(_: &mut usize) {}
```

The compiler provide the following error message:

```
 --> src/main.rs:7:14
  |
6 | fn example(borrowed: &mut usize) {
  |            -------- help: consider changing this to be mutable: `mut borrowed`
7 |     example2(&mut borrowed);
  |              ^^^^^^^^^^^^^ cannot borrow as mutable
```

Although the suggestion actually work. (Because of type coercion). I think it would be a little nicer to suggest removing &mut when calling the function.

My friend who is new to Rust got a similar suggestion (and misunderstood it) which made him confused.

**Comment by lzutao** [comment]
Duplicate of #75871.

**Comment by jyn514** [comment]
Closing as duplicate.
