### ISSUE TITLE
bootstrap: `--warnings warn` doesn't apply to bootstrap itself

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#76805]
Bootstrapping with `RUSTFLAGS="-Wsomething that warns ./x.py check  --warnings warn ` does not work; a warning inside bootstrap will still abort the compilation process:

````
error: trivial numeric cast: `u32` as `u32`
   --> src/bootstrap/lib.rs:156:31
    |
156 |             libc::setpriority(libc::PRIO_PGRP as _, 0, 10);
    |                               ^^^^^^^^^^^^^^^^^^^^
    |
    = note: `-D trivial-numeric-casts` implied by `-D warnings`
    = help: cast can be replaced by coercion; this might require a temporary variable

error: aborting due to previous error

error: could not compile `bootstrap`.

````

EDIT: well, putting `--cap-lints warn` into `RUSTFLAGS` works but it seems very unintuitive.

**Comment by Mark-Simulacrum** [comment]
x.py doesn't check the warnings flag, but you can set deny-warnings in config.toml to false to patch around this.

**Comment by jyn514** [comment]
Mentoring instructions: Add a `--warnings` flag to `bootstrap.py` around https://github.com/rust-lang/rust/blob/043c634a9cbe6ee303eadd0a31b11203b9ef9386/src/bootstrap/bootstrap.py#L833-L842 and check it when building bootstrap, around https://github.com/rust-lang/rust/blob/043c634a9cbe6ee303eadd0a31b11203b9ef9386/src/bootstrap/bootstrap.py#L778-L788
