### ISSUE TITLE
Use diagnostic_item instead of match_def_path in lints

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#76813]
In multiple lints we currently use `match_def_path` to perform checks for specific paths. We should be using `is_diagnostic_item` instead (which is newer than those lints).

**Comment by RalfJung** [comment]
See https://github.com/rust-lang/rust/issues/66075 for some more things that could be turned into diagnostic items.

**Comment by JohnTitor** [comment]
Looks like there's no use of `match_def_path` in the `rustc` (the work has been finished by #76910, clippy still uses it though), closing as completed.
