### ISSUE TITLE
Consider making RUSTC_LOG=warn the default (instead of just error).

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#76824]
We don't use `error!`/`warn!`/`info!` a lot, but they come in handy for "debugging `rustc` without a `debug-assertions` build" situations, e.g. we use `info!` to show the function being codegen'd (as it's low-overhead and really helpful for e.g. LLVM crashes).

While `info!` makes sense for off-by-default debugging helpers like that, `error!`/`warn!` seem closer to user-facing diagnostics, where the main difference is them being usable outside of code which has access to a `Session` (either due to running before the `Session` is created, or just in dependencies that have access to `log`/`tracing` but not any `rustc`-specific diagnostics APIs).

However, one surprising aspect is *only* `error!` is enabled by default, while `warn!` *is not*, meaning that, with the current defaults, one is forced to choose between `error!` (which would output the word "error" which sounds more dire than "warning") or `warn!` (which may never be seen by an user).

<hr/>

My usecase for `warn!` is in the upcoming `-Z self-profile` support for using hardware performance counters (which needs to be implemented in the separate `measureme` project), e.g. [this `warn!` instructs the user to open an issue](https://gist.github.com/eddyb/269491b0b59605f39f1d0a9dcf535c4a/025ee76590ad4e24a7dce9754080fb7c2b30df85#file-rdpmc-bench-rs-L565-L570) if they have an unrecognized (newer) CPU, but there's nothing preventing `-Z self-profile` from working (if the newer CPUs aren't drastically different), so showing "error" seems quite inappropriate.

Sadly, I don't think ~~`log`~~ `env_logger` itself will change this behavior, so even if we change `RUSTC_LOG`'s default, `measureme` might still have to use the less-appropriate `error!` if it wants to account for being used in other projects.

cc @Mark-Simulacrum @gdhuper @hawkw

**Comment by eddyb** [comment]
> Sadly, I don't think ~~`log`~~ `env_logger` itself will change this behavior, so even if we change `RUSTC_LOG`'s default, `measureme` might still have to use the less-appropriate `error!` if it wants to account for being used in other projects.

This might not as big of a problem as I thought, @m-ou-se suggested checking if `warn!` is enabled (either by the user, or `rustc`'s default if we change that) and emit `error!` if it's not (and say "warning" in the message).
For convenience I could wrap this in a `really_warn!` macro.

**Comment by Mark-Simulacrum** [comment]
warn! then seems not significantly better than just an eprintln - am I missing something there?

**Comment by eddyb** [comment]
Perhaps, but I would prefer using `log`/`tracing` macros for consistency of output, and more generally the ability for consumers of a library to choose where to direct the messages.

This is even more important with `tracing`, where there is a nesting structure, not just individual messages.

**Comment by oli-obk** [comment]
Since [we use `max_level_info`](https://github.com/rust-lang/rust/search?q=max_level_info) for tracing, `error!` `warn!` and `info!` should all show up in regular builds.

**Comment by eddyb** [comment]
This has gotten worse with `tracing`, where even `error!` isn't enabled by default (see https://github.com/rust-lang/rust/pull/78781#discussion_r723720391).

**Comment by hawkw** [comment]
> Since [we use `max_level_info`](https://github.com/rust-lang/rust/search?q=max_level_info) for tracing, `error!` `warn!` and `info!` should all show up in regular builds.

This is not correct. `max_level_info` means that info and below will not be _statically_ disabled (compiled out). Because you are _also_ using `EnvFilter` to filter the spans and events that are enabled, `error!`, `warn!`, and `info!` will only be enabled if the `EnvFilter` is configured to enable them. What `max_level_info` means is that anything _below_ `INFO` will be disabled at compile time, and _cannot_ be enabled by the filter configuration.

**Comment by eddyb** [comment]
Do you know more details? There aren't that many non-`debug!`/`trace!` calls and they mainly exist in places that cannot easily get access to the rustc diagnostics infrastructure.

So the perf impact should be minimal, while offering a valuable infrastructure for miscellanea that has no other way to interface with the user.

For something like `measureme`, we can probably alleviate it by having a fallback to `eprintln!`, especially since it may be used without any logging infrastructure.

Or maybe the warnings could be returned by value but that's an easy to misuse API, unlike `Result` for errors.
