### ISSUE TITLE
slice binary_search_by always does log2(n) comparisons

### ISSUE THREAD

**Issue by flumm** [rust-lang/rust#76831]
looking at the code in core/slice/mod.rs: https://github.com/rust-lang/rust/blob/95386b656e91168bf53e2ab63c6b992cae591fe7/library/core/src/slice/mod.rs#L1924-L1947

binary_search_by always makes log2(n) comparisons, even it found a match already
the only issues i found regarding binary search were #54096 and #57935 but both seem to not really answer this

is there any reason why the code does not return immediately when it finds an element?

**Comment by the8472** [comment]
There's an open PR for that, #74024

**Comment by flumm** [comment]
oh, great that someone works on that. if you want i can close this issue. (or should i leave it open?)

**Comment by the8472** [comment]
Note that the PR may not be accepted. The current binary search is implemented to be branchless to avoid misprediction costs, so early termination in the ideal case might not be worth it in the average case. So if you have a particular case that benefits a lot from early termination you might want to bring that up or roll your own binary search optimized for that case.

**Comment by m-ou-se** [comment]
This is now solved by https://github.com/rust-lang/rust/pull/74024. Thanks for the report!
