### ISSUE TITLE
README.md: remove language identifier from code blocks or prompts

### ISSUE THREAD

**Issue by qlcom** [rust-lang/rust#76863]
code blocks on Readme are marked with `sh` or `batch`. but each line begins with `$ ` or `> `,which are the prompts.

if someone copy the line and run it, it will fail with a message like `zsh: command not found: $`( on `zsh`)

so either the language identifiers or the prompts should be removed.

**Comment by qlcom** [comment]
i think prompts should be removed.

**Comment by lzutao** [comment]
I agree the prompts (`$` or `>`) aren't always needed in case we don't have sample command output.
Pull requests welcomed to remove them.

@rustbot modify labels: T-doc C-enhancement E-easy

**Comment by whizsid** [comment]
I like to work on this issue.

**Comment by lzutao** [comment]
Sorry, there's already an open PR: #76883
