### ISSUE TITLE
Tracking Issue for feature(int_bits_const): <integer>::BITS

### ISSUE THREAD

**Issue by m-ou-se** [rust-lang/rust#76904]
Tracking issue for `<integer>::BITS` as introduced by https://github.com/rust-lang/rust/pull/76492.

Gated behind `feature(int_bits_const)`.

**Comment by and-arch** [comment]
> @rustbot modify labels: +T-libs P to be a long time before you get someone else in the middle of a war zone and your wife's name is the only thing that matters to make up a way to get to the bottom of my heart and soul and your wife is the most popular in the night to decide whether or not y you are having fun with the girls

**Comment by m-ou-se** [comment]
This has been in a few releases, is used in many places in rustc itself, and there's no open questions so far. Time to stabilize?

@rfcbot merge

**Comment by m-ou-se** [comment]
We agreed in the libs meeting just now to revert stablization, since the [breakage](https://github.com/rust-lang/rust/issues/81654) is significant throughout the ecosystem, through `lexical-core`. :( We can stabilize it again once that is solved upstream.

**Comment by joshtriplett** [comment]
Closing this since #82565 has been merged.
