### ISSUE TITLE
Simplify error message with removing lifetime and reference information

### ISSUE THREAD

**Issue by tronta** [rust-lang/rust#76903]
The following code provides the following error message:
``` rust
fn main() {
    "jjj".to_de();
}
```

``` rust
error[E0599]: no method named `to_de` found for reference `&'static str` in the current scope
 --> src/main.rs:2:11
  |
2 |     "jjj".to_de();
  |           ^^^^^ method not found in `&'static str`
```
this could be reduced to
``` rust
error[E0599]: no method named `to_de` found for `str` in the current scope
 --> src/main.rs:2:11
  |
2 |     "jjj".to_de();
  |           ^^^^^ method not found in `str`
```
as `.` is automatically dereferencing and the lifetime also does not matter for this error.

**Comment by Aaron1011** [comment]
If the method is missing, we cannot know what components of the type may or not matter. For example, the user could have typo'd the following hypothetical method:

```rust
impl &'static str {
	fn to_df(self) {}
}
```

**Comment by tronta** [comment]
Maybe I just don't get what exactly you mean, but what exactly is missing if I just see the error
```
error[E0599]: no method named `to_de` found for `str` in the current scope
 --> src/main.rs:2:11
  |
2 |     "jjj".to_de();
  |           ^^^^^ method not found in `str`
```
I personally don't miss `&'static`

**Comment by Aaron1011** [comment]
I don't think we should be displaying a 'simplified' version of the actual type of the method receiver, based on where we think the actual method will be defined.

Also, using `#![feature(unsized_locals)]` allows you to actually have a local variable of type `str` (see https://github.com/rust-lang/rust/issues/48055). If we 'simplify' the error message, the user can no longer tell if the local has type `str` or `&'static str`.

**Comment by tronta** [comment]
Ah. So maybe add that this is a type:
```
error[E0599]: no method named `to_de` found for type `str` in the current scope
 --> src/main.rs:2:11
  |
2 |     "jjj".to_de();
  |           ^^^^^ method not found for type `str`
```

**Comment by tronta** [comment]
Ok, so I close it.
