### ISSUE TITLE
Tracking Issue for feature(string_drain_as_str) - string::Drain::as_str()

### ISSUE THREAD

**Issue by m-ou-se** [rust-lang/rust#76905]
Tracking Issue for `string_drain_as_str` as introduced by https://github.com/rust-lang/rust/pull/76525.

Api:
 - `Drain::as_str()`
 - `AsRef<str> for Drain`
 - `AsRef<[u8]> for Drain`

The first one is now gated behind `feature(string_drain_as_str)`. The other two are not available yet, as trait implementations cannot be unstable. These should be added (uncommented) when this feature is stabilized.

**Comment by JohnTitor** [comment]
Seems there's no blocker, could I ask you to kick off FCP to stabilize it?

**Comment by JohnTitor** [comment]
cc @rust-lang/libs-api If it's reasonable, it'd be great if someone starts FCP :)

**Comment by joshtriplett** [comment]
Do we have any confirmation of usage in the ecosystem? I don't see any problem with the method as designed, but can we confirm that it's being used?

**Comment by JohnTitor** [comment]
Oh sorry, I don't have the real world use case, unfortunately. I just thought this is straightforward and makes the conversion around `.drain(..)` easier. And we cannot make any use that requires `AsRef` because it's hidden until we stabilize the feature.

**Comment by m-ou-se** [comment]
@rfcbot merge
