### ISSUE TITLE
The default overflow behavior of u128 arithmetic operation is not panic for wasm32 target.

### ISSUE THREAD

**Issue by laizy** [rust-lang/rust#76954]
Our team use rust to develop Wasm smart contract, and use u128 heavily. but we find out arithmetic operations of generated Wasm code overflow silently without panic, which put the contract at great security risk. We have to urgently replace all u128 usage with our wrapped type. And I think this should be fixed in rustc to make the behavior consistent with other non-Wasm target.

**Comment by lukaslueg** [comment]
Unsigned [integers are documented](https://doc.rust-lang.org/book/ch03-02-data-types.html#integer-overflow) to silently overflow when code compiled in release mode.

**Comment by jonas-schievink** [comment]
Cannot reproduce

```rust
fn main() {
    let x = u128::MAX;

    x + one();
}

fn one() -> u128 { 1 }
```

```
$ rustc +nightly main.rs --target wasm32-wasi
$ wasmtime main.wasm
thread 'main' panicked at 'attempt to add with overflow', main.rs:4:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
...
```

@laizy please provide information for how to reproduce your issue

**Comment by laizy** [comment]
@jonas-schievink open https://webassembly.studio/ ， select "empty rust project" and click "create".  copy the following code to "main.rs", and click "build & run": 
```rust
#[no_mangle]
pub extern "C" fn add_one(x: i32) -> i32 {
  let y = u128::max_value();
   let add = overflow_u128(x as u128, y);
  // let add = overflow_checked_u128(x as u128, y);
  add as i32
}

#[inline(never)]
fn overflow_u128(a: u128, b: u128) -> u128 {
  a + b
}

#[inline(never)]
fn overflow_checked_u128(a: u128, b: u128) -> u128 {
  a.checked_add(b).unwrap()
}
```

@lukaslueg  thanks for your link. I didn't notice the difference between debug and release. I may need close this and keep using our own wrapped type then.

**Comment by jonas-schievink** [comment]
Closing as expected behavior then. WebAssembly Studio uses release builds by default.
