### ISSUE TITLE
Division by NonZero* checks for zero

### ISSUE THREAD

**Issue by bugadani** [rust-lang/rust#76960]
https://rust.godbolt.org/z/eTPzE6

Technically, NonZero* types are not meant to be used for optimizing arithmetic, but people (like myself) may or may not know that or may assume otherwise.

It is possible to create a NonZero* object with 0 inner value, but since that is a misuse of the type and deliberate violation of the safety guarantees, I think it would make sense to teach the compiler that `get()` can't return 0.

Edit: unfortunately, since NonZero* methods are const, it's not as simple as adding an assume.

**Comment by oli-obk** [comment]
> since NonZero* methods are const, it's not as simple as adding an assume.

we can make `assume` const, it's a no-op in const eval anyway (though we use it to assert that the assumption holds in miri)

**Comment by lzutao** [comment]
I'm preparing a PR for that.

**Comment by bugadani** [comment]
I can add the assume after that's done.

**Comment by bugadani** [comment]
Duplicate of #49572
