### ISSUE TITLE
Tracking Issue for `const_assume` feature

### ISSUE THREAD

**Issue by tesuji** [rust-lang/rust#76972]
The feature gate for the issue is `#![feature(const_assume)]`.
It makes `core::intrinsics::assume` usable in const contexts.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Implemented in #76973
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

**Comment by AngelicosPhosphoros** [comment]
@tesuji Do you want to stabilize the feature?
I was asked to use `assume` in const context here: https://github.com/rust-lang/rust/pull/119452

**Comment by Nilstrieb** [comment]
WG-const-eval has confirmed that this is fine: https://github.com/rust-lang/rust/pull/119452#discussion_r1439059151

Feel free to send in a PR flipping the stability attribute. It's an unstable intrinsic so we aren't really committing to anything.
