### ISSUE TITLE
tcpStream error

### ISSUE THREAD

**Issue by Karatla** [rust-lang/rust#76989]
```
fn main(){
    let url: Url = "http://url.com".parse().unwrap();
    let url2 = url.clone();
    let host = url2.host_str().unwrap();
    let port = url2.port_or_known_default().unwrap();
    

    let mut i = 0;
    let mut a = Vec::new();

    while i < 300 {

        println!("{}",i);

        let mut stream =  TcpStream::connect((host,port)).unwrap(); 
        stream.flush().unwrap();
        a.push(stream);
        i+=1;
        
    }
    
            println!("finish")
}
```
Hi i am New in rust. I an using standard v1.46 rust and i have a error can not fix it. please help me!

My code above.

I don't know why when i use _cargo run_ in vscode terminal It works good . but when i _cargo run_ in mac os terminal It has error.
I discover that as long as tcpStream amount below  250 It would no error. 
![mmexport1600650224313.jpg](https://user-images.githubusercontent.com/55880954/93726574-634a8000-fbe9-11ea-8d4b-e094c7e416bb.jpg)

![mmexport1600650207229.jpg](https://user-images.githubusercontent.com/55880954/93726581-6d6c7e80-fbe9-11ea-8b5a-0f4b8b08dfc8.jpg)

**Comment by lzutao** [comment]
Is url.com a valid address ?
Also, this is not a compiler bug. Issues like this could be asked in forum users.rust-lang.org/
or discord.

**Comment by Karatla** [comment]
url just is example.

**Comment by lzutao** [comment]
The error said it cannot connect to url.com. Try another valid address.
Also like I said, this should be asked in the forum.

**Comment by Karatla** [comment]
OK . Thank you
