### ISSUE TITLE
#[cfg(feature = "f")] not correctly evaluating inside macro with feature set on MacOS

### ISSUE THREAD

**Issue by rybertm** [rust-lang/rust#77007]
I tried this code:

`test_cfg_bin/main.rs` with `test_cfg_lib` as dependency and feature `f` set:
```rust
fn main() {
    test_cfg_lib::test_fn();
    test_cfg_lib::test_macro!()
}
```
`test_cfg_lib/lib.rs`:
```rust
pub fn test_fn() {
    #[cfg(feature = "f")]
    println!("test fn")
}

#[macro_export]
macro_rules! test_macro {
    () => {
        // Doesn't print
        if cfg!(feature = "f") {
            println!("test macro")
        }
    };
}
```

I expected to see this happen: "test fn" and "test macro" to be printed

Instead, this happened: only "test fn" got printed

### Meta

`rustc --version --verbose`:
```
rustc 1.48.0-nightly (1fd5b9d51 2020-09-20)
binary: rustc
commit-hash: 1fd5b9d516c035a898dcb437b2f982bea5d4bc88
commit-date: 2020-09-20
host: x86_64-apple-darwin
release: 1.48.0-nightly
LLVM version: 11.0
```

This happens in the stable version as well.

**Comment by jonas-schievink** [comment]
This is working as expected. The `cfg!` macro is expanded inside the binary crate, in which `cfg(feature = "f")` is not set.
