### ISSUE TITLE
crashed when list dynlib metadata

### ISSUE THREAD

**Issue by oldoldman** [rust-lang/rust#77048]
rustc crashed when listing metadata of a dynlib , this is the stack trace
<pre>
thread 'rustc' panicked at 'index out of bounds: the len is 0 but the index is 0', /rustc/0f91f5c284c72e69bb7115586b7756874c59cbbe\src\librustc_serialize\leb128.rs:50:1
stack backtrace:
   0:     0x7ffd42b59f69 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h821f4dd582550bfb
   1:     0x7ffd42b86f7b - core::fmt::write::h312876c93103ed54
   2:     0x7ffd42b4bae4 - <std::io::IoSlice as core::fmt::Debug>::fmt::hfb43901216eaeee2
   3:     0x7ffd42b5f5cb - std::panicking::take_hook::h52d1f68705bfe58e
   4:     0x7ffd42b5f209 - std::panicking::take_hook::h52d1f68705bfe58e
   5:     0x7ffd1ed4f8da - rustc_driver::report_ice::h73e31dd3f37a0050
   6:     0x7ffd42b5ff60 - std::panicking::rust_panic_with_hook::heea127619d634446
   7:     0x7ffd42b5fa95 - rust_begin_unwind
   8:     0x7ffd42b5a84f - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h821f4dd582550bfb
   9:     0x7ffd42b5fa49 - rust_begin_unwind
  10:     0x7ffd42b837b0 - core::panicking::panic_fmt::h2bc3ab32a0a7113d
  11:     0x7ffd42b83777 - core::panicking::panic_bounds_check::h1c658c231e70b3ce
  12:     0x7ffd224eb48e - rustc_metadata::rmeta::decoder::DecodeContext::cdata::h0e110cc5f7767b18
  13:     0x7ffd224b12f5 - ZN14rustc_metadata5rmeta67_DERIVE_rustc_serialize_Decodable_DecodeContext_a_tcx_FOR_CrateRoot153_$LT$impl$u20$rustc_serialize..serialize..Decodable$LT$rustc_metadata..rmeta..decoder..DecodeContext$GT$$u20$for$u20$rustc_metadata..rmeta..CrateRoot$GT$6decod
  14:     0x7ffd224ebe0f - <rustc_metadata::rmeta::decoder::DecodeContext as rustc_data_structures::fingerprint::FingerprintDecoder>::decode_fingerprint::h8e4bb3ac72fb676e
  15:     0x7ffd224ebfce - <rustc_metadata::rmeta::decoder::DecodeContext as rustc_data_structures::fingerprint::FingerprintDecoder>::decode_fingerprint::h8e4bb3ac72fb676e
  16:     0x7ffd2237a17b - rustc_metadata::locator::list_file_metadata::h8206737b8efc31f8
  17:     0x7ffd1ed48d9a - rustc_driver::RustcDefaultCalls::list_metadata::hcf3e2d0dd8e80c92
  18:     0x7ffd1ed48608 - rustc_driver::run_compiler::h99570fc4428f7813
  19:     0x7ffd1ed04ca0 - <rustc_driver::args::Error as core::fmt::Debug>::fmt::h4d767eacfb9c0d6b
  20:     0x7ffd1ed7082b - <rustc_driver::DEFAULT_HOOK as core::ops::deref::Deref>::deref::h3fbcde42f915cc45
  21:     0x7ffd1ed5d280 - <rustc_driver::DEFAULT_HOOK as core::ops::deref::Deref>::deref::h3fbcde42f915cc45
  22:     0x7ffd1ed63e3f - <rustc_driver::DEFAULT_HOOK as core::ops::deref::Deref>::deref::h3fbcde42f915cc45
  23:     0x7ffd1ecfd0f3 - <rustc_middle::ty::SymbolName as core::fmt::Debug>::fmt::h56077a367631f1cb
  24:     0x7ffd42b6fcca - std::sys::windows::thread::Thread::new::ha9abef9832621dc4
  25:     0x7ffd9edc8394 - BaseThreadInitThunk
  26:     0x7ffd9fea262b - RtlUserThreadStart

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.47.0-beta.1 (0f91f5c28 2020-08-25) running on x86_64-pc-windows-msvc

note: compiler flags: -Z ls

query stack during panic:
end of query stack
</pre>

**Comment by lzutao** [comment]
Please try a newest nightly.

**Comment by Enselic** [comment]
Triage: Since there currently is no known way to reproduce this ICE, I will close this issue. Without a way to reproduce, not much can be done. Feel free to re-open if a way to reproduce is found.
