### ISSUE TITLE
non-exhaustive pattern static analysis 

### ISSUE THREAD

**Issue by Peperud** [rust-lang/rust#77043]
```rust
// code fragment
    let mut another: u32;
    for x in 1..4 {
        match x {
            1 => another = 10,
            2 => another = 20,
            3 => another = 30,
        }
    }
```

Within the loop **x** can only be 1,2 or 3, yet the compiler complains with ```non-exhaustive patterns: `i32::MIN..=0_i32` and `4_i32..=i32::MAX` not covered```.
Adding a "catch all" case makes it compile of course, but it seems it should not be necessary. 
All the info for the compiler to make the right decision is available at compile time.

**Comment by leonardo-m** [comment]
This is a known limitation of the current compiler. Another example of this known limitation, here rustc gives a similar error:

    fn foo(x: u32) -> char {
        match x % 3 {
            0 => 'a',
            1 => 'b',
            2 => 'c',
        }
    }

We have good compiler developers, perhaps eventually this will be worked on.

**Comment by jonas-schievink** [comment]
This is working as expected. Exhaustiveness is checked purely based on the type of the matched expression. Changes to this would require an RFC, so closing in favor of that.
