### ISSUE TITLE
--remap-path-prefix broken in rustc version >= 1.46.0

### ISSUE THREAD

**Issue by Bargsteen** [rust-lang/rust#77046]
When compiling a rust program with `--remap-path-prefix` in 1.46.0, (and nightlies 1.47.0, 1.48.0) the specified prefixes in the binary are unaltered. I expected them to be changed. 

When using 1.45.2 and 1.43.0, it works as expected.

## Steps to reproduce
0. Make sure you are using rustc >=1.46.0, check via `rustc --version`
1. Create a new cargo project: `cargo new --bin foo`
2. Add a dependency to Cargo.toml, for example `regex = "1"`
3. Add code that uses this dependency, for example:

```rust
use regex::Regex;

fn main() {
    Regex::new(r"{").unwrap();
}
```
4. Run `RUSTFLAGS=--remap-path-prefix=/home/kasper=bar cargo build --release`, where `/home/kasper/` is the prefix you want to change, for example your `$HOME`.
5. Inspect the binary using: `strings target/release/foo | grep kasper` (where `kasper` is something contained in the prefix), and see that it returns several lines.

If the same steps are taken on 1.45.2, step 5 returns no results, as expected.

## Notes
The crate and code example is arbitrary, and the same behavior is observed for any combination of crates.

Software versions:
- rustc 1.46.0 (04488afe3 2020-08-24)
- OS: Linux (Ubuntu 20.04.1 LTS)

The following nightly versions also fail:
- rustc 1.47.0-nightly (f44c6e4e2 2020-08-24)
- rustc 1.48.0-nightly (1fd5b9d51 2020-09-20)

**Comment by ehuss** [comment]
I believe this is essentially a duplicate of #73167.  The paths should only appear if you have the `rust-src` component installed. Can you confirm that removing that component resolves what you are seeing?

**Comment by Bargsteen** [comment]
> I believe this is essentially a duplicate of #73167. The paths should only appear if you have the `rust-src` component installed. Can you confirm that removing that component resolves what you are seeing?

Yes, I can confirm that removing the `rust-src` component essentially fixes the problem.
Closing this issue as it is a duplicate of #73167.
