### ISSUE TITLE
building rust package using custom toolchain.

### ISSUE THREAD

**Issue by Galadrin** [rust-lang/rust#77059]
Hi, we encountered an issue when building some package using custom toolchain.

We discovered the issue when building the [bat](https://github.com/sharkdp/bat) program with buildroot project.

cargo/rust is in trouble when the toolchain prefix is not listed in [supported_targets](https://github.com/rust-lang/rust/blob/c367798cfd3817ca6ae908ce675d1d99242af148/src/librustc_target/spec/mod.rs#L491), the toolchain prefix is "lost" when building some VENDOR dependencies and the default prefix is used:

--- stdout
TARGET = Some("aarch64-unknown-linux-gnu")
OPT_LEVEL = Some("3")
HOST = Some("x86_64-unknown-linux-gnu")
CC_aarch64-unknown-linux-gnu = None
CC_aarch64_unknown_linux_gnu = None
TARGET_CC = None
CC = None
CROSS_COMPILE = None
CFLAGS_aarch64-unknown-linux-gnu = None
CFLAGS_aarch64_unknown_linux_gnu = None
TARGET_CFLAGS = None
CFLAGS = None
CRATE_CC_NO_DEFAULTS = None
DEBUG = Some("false")
CARGO_CFG_TARGET_FEATURE = None

What is the best practice to follow for this case ?

You can find more informations following the mailing list in [thread](http://lists.busybox.net/pipermail/buildroot/2020-July/288233.html)

**Comment by Dylan-DPC** [comment]
Closing this to clear up the issue tracker. If you or anyone reading this still needs help you can consult the forums, discords, etc for help. Thanks
