### ISSUE TITLE
Use dynamic linking and download LLVM from CI for rustc across platforms

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#77084]
From https://github.com/rust-lang/rust/pull/76810:

> Longer-term I do think it's best to get back to a point where we're consistently doing the same thing for LLVM across all our platforms. It's been the case for quite some time that LLVM is built with ThinLTO on Linux but nowhere else. Differing in linkage is also unfortunate across the major platforms too.

> I've given up on trying to make link-shared work well across the board -- see PR description and the last few CI failures -- it seems link LLVM is just not ready for a shared link on macOS or when cross-compiling, which excludes almost all of our builders.

Switching to static linking would preclude any of the improvements from https://github.com/rust-lang/rust/pull/76349, so it would be better to use dynamic linking instead which would allow any contributor to get started without building LLVM from source or using system LLVM. That said, it sounds like dynamic linking will be very hard to do on other platforms.

cc @Mark-Simulacrum

**Comment by Mark-Simulacrum** [comment]
Cc @cuviper @nikic @nagisa - do we know what the right way to bring the issues (bugs?) I found to LLVM developers? Are there active maintainers of LLVMs build system?

**Comment by nagisa** [comment]
LLVM’s bugzilla is pretty much the only place for bug reports. If its something less defined than a precise bug report, talking it out on the mailing lists is the way to go.

**Comment by est31** [comment]
> Switching to static linking would preclude any of the improvements from #76349, so it would be better to use dynamic linking instead

In which way is static linking making downloaded LLVM impossible?

**Comment by Mark-Simulacrum** [comment]
I don't think it's impossible to download/ship the statically linked LLVM, it's something I want to explore. That said, we want to move to dynamically linking LLVM because we ideally want to be applying ThinLTO to LLVM everywhere, not just on x86_64-unknown-linux-gnu, and since LTO happens at link-time, we want that to happen once, not on the multiple LLVM links occurring during CI.
