### ISSUE TITLE
`allow_internal_unstable` attr only allowed once per function

### ISSUE THREAD

**Issue by lzutao** [rust-lang/rust#77088]
Discussed in zulip: https://rust-lang.zulipchat.com/#narrow/stream/219381-t-libs/topic/Using.20const.20unreachable.20in.20libcore/near/210673352

The problem is that compiler doesn't accept code like this:
```rust
    #[allow_internal_unstable(const_fn)]
    #[allow_internal_unstable(const_unreachable_unchecked)]
    pub const fn len(&self) -> usize {
        // SAFETY: this is safe because `&[T]` and `FatPtr<T>` have the same layout.
        // Only `std` can make this guarantee.
        let raw_len = unsafe { crate::ptr::Repr { rust: self }.raw.len };

        match mem::size_of::<T>() {
            0 => {}
            // SAFETY: this branch taken if mathematically `isize::MAX < raw_len * N`.
            // But references must point to one allocation with size at most isize::MAX.
            N if (isize::MAX as usize) / N < raw_len => unsafe { hint::unreachable_unchecked() },
            _ => {}
        }

        raw_len
    }
```

But it accepts code when merging mutiple `allow_internal_unstable` annotations into one:  #77023

### Meta

`rustc --version --verbose`: Version 1.48.0-nightly (0da580074 2020-09-22)

cc #76807 which modified some const stability checks.

@rustbot modify labels: E-mentor

**Comment by ecstatic-morse** [comment]
#77023 just refactored a few individual calls to `rustc_attr::allow_internal_unstable` into a single helper function.

https://github.com/rust-lang/rust/blob/6d3acf5129767db78a3d9d62e814ec86b8870d75/compiler/rustc_mir/src/transform/check_consts/mod.rs#L61-L65

`rustc_attr::allow_internal_unstable` only looks for the first attribute it seems. Shouldn't be hard to fix.

https://github.com/rust-lang/rust/blob/6d3acf5129767db78a3d9d62e814ec86b8870d75/compiler/rustc_attr/src/builtin.rs#L1023-L1041

**Comment by oli-obk** [comment]
The PR did not actually fix the issue. The test case added to the PR also works without the PR.

**Comment by bugadani** [comment]
It doesn't hurt to double check, just takes some time :)
