### ISSUE TITLE
Regression in nightly-2020-09-23: "missing `as_flags` in implementation" of OpenOptionsExt

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust#77089]
The following code compiles fine with nightly-2020-09-22 (and stable rustc since 1.10.0) but not nightly-2020-09-23.

```rust
use std::os::unix::fs::OpenOptionsExt;

struct MyOpenOptions;

impl OpenOptionsExt for MyOpenOptions {
    fn mode(&mut self, _mode: u32) -> &mut Self {
        unimplemented!()
    }

    fn custom_flags(&mut self, _flags: i32) -> &mut Self {
        unimplemented!()
    }
}
```

```console
error[E0046]: not all trait items implemented, missing: `as_flags`
 --> src/lib.rs:5:1
  |
5 | impl OpenOptionsExt for MyOpenOptions {
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ missing `as_flags` in implementation
  |
  = help: implement the missing item: `fn as_flags(&self) -> std::result::Result<i32, std::io::Error> { todo!() }`
```

This is minimized from https://github.com/async-rs/async-std/blob/e8126633a89aafea23259eb9faddb70b89f94423/src/fs/open_options.rs#L303-L313.

Mentioning #76110, #76801, @FedericoPonzi, @joshtriplett.

**Comment by jyn514** [comment]
Whoops, I didn't realize the trait itself was stable. Probably the PR should either be reverted or add a default implementation for `as_flags()`.

**Comment by Stupremee** [comment]
Assigning P-critical as [discussed](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/I-prioritize.20.2377089.20Regression.20in.20nightly-2020-09-23.3A.20.22miss.E2.80.A6/near/210955212) as part of the Prioritization Working Group procedure and removing I-prioritize.

**Comment by yoshuawuyts** [comment]
`async-std` is now broken on nightly as well: https://github.com/async-rs/async-std/issues/883

**Comment by ollie27** [comment]
I was under the impression that the `*Ext` traits were not intended to be implemented outside of `std` which means this is really an issue with `async-std` which shouldn't have implemented `OpenOptionsExt` at all.

[`std::os::unix::process::CommandExt`](https://doc.rust-lang.org/nightly/std/os/unix/process/trait.CommandExt.html) for example has had several methods added to it since 1.0. Is there something different with `OpenOptionsExt` or is this just that it was implemented by a popular crate?

**Comment by dtolnay** [comment]
The trait likely should have been [sealed](https://rust-lang.github.io/api-guidelines/future-proofing.html#c-sealed), but I think sealed traits were not invented until after 1.0.0.

**Comment by jonas-schievink** [comment]
Can we retroactively seal `CommandExt`? It seems like we should, if we keep adding methods like in https://github.com/rust-lang/rust/pull/72160.

**Comment by jyn514** [comment]
Wouldn't that be a breaking change?

**Comment by jonas-schievink** [comment]
Yes, just like adding more methods to it (which has been done several times)

**Comment by joshtriplett** [comment]
We could do a crater run to see if sealing it would break anything.

**Comment by jyn514** [comment]
Well clearly it would - it would break async-std the same way `as_flags()` broke async std. We need to get them not to use `OpenOptionsExt` before we can change anything here.

**Comment by joshtriplett** [comment]
@jyn514 My comment was in reference to sealing `CommandExt`, not `OpenOptionsExt`.
