### ISSUE TITLE
rust/RELEASES.md doesn't mention that 1.42 allows custom attributes on modules

### ISSUE THREAD

**Issue by Emoun** [rust-lang/rust#77098]
Pre-1.42, applying an attribute procedural macro to a module was disallowed with the following message:
```
error[E0658]: custom attributes cannot be applied to modules
...
 = note: for more information, see https://github.com/rust-lang/rust/issues/54727
```
As an example, see [this build](https://travis-ci.org/github/Emoun/duplicate/jobs/729555594) using rust 1.34 that exhibits this.

From rust 1.42 and onward this error does not occur, however, this is not detailed in [the release notes](https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1420-2020-03-12).

**Comment by bsikar** [comment]
Does this still need to be done?

**Comment by Emoun** [comment]
I tried looking for update to the release notes that #78690 did but I cannot seem to find it on current master. 
Was that PR not merged?
