### ISSUE TITLE
Oudated html_root_url for compiler crates

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rust#77103]
https://doc.rust-lang.org/nightly/ should be https://doc.rust-lang.org/nightly/nightly-rustc/

**Comment by jyn514** [comment]
Mentoring instructions: for each crate in `compiler/`, change https://github.com/rust-lang/rust/blob/9e5f7d5631b8f4009ac1c693e585d4b7108d4275/compiler/rustc_apfloat/src/lib.rs#L33
to say `#![doc(html_root_url = "https://doc.rust-lang.org/nightly/nightly-rustc")]` instead. You can probably automated this with `fd` and `sed.
