### ISSUE TITLE
[docs] `core::global_allocator` should link to `std::alloc::GlobalAlloc`

### ISSUE THREAD

**Issue by yoshuawuyts** [rust-lang/rust#77100]
Seaching for `global_allocator` in the docs only surfaces [`core::global_allocator`](https://doc.rust-lang.org/core/macro.global_allocator.html). This surfaces no information on how to use it, since all that info is part of [`std::alloc::GlobalAlloc`](https://doc.rust-lang.org/std/alloc/trait.GlobalAlloc.html).

The solution seems to link from `global_allocator` to `GlobalAlloc` so people can read more. However I'm not sure how to create a link between these since they live in separate crates. What's the right way to go about this?

__edit:__ if someone wants to pick this up, please do. This is probably a "good first issue" once we figure out how to link between the two.

## Screenshots

![Screenshot_2020-09-23 core global_allocator - Rust](https://user-images.githubusercontent.com/2467194/94001791-510f4400-fd99-11ea-9360-28198be6db6c.png)

## References
- [2018 guide on allocators](https://doc.rust-lang.org/edition-guide/rust-2018/platform-and-target-support/global-allocators.html) -- this is how I eventually learned about `GlobalAlloc`; ideally it'd be easier to find.

**Comment by jyn514** [comment]
> The solution seems to link from global_allocator to GlobalAlloc so people can read more. However I'm not sure how to create a link between these since they live in separate crates. What's the right way to go about this?

These can't use intra-doc links, so you need to use relative links. I think `../std/alloc/trait.GlobalAlloc.html` would work.

**Comment by jyn514** [comment]
Mentoring instructions: At https://github.com/rust-lang/rust/blob/383da5e1e670c5028731aa3e477578e5e97c6e52/library/core/src/macros/mod.rs#L1367
add a link to `../std/alloc/trait.GlobalAlloc.html`.

**Comment by mightyiam** [comment]
Could I take this on as my first issue?

**Comment by yoshuawuyts** [comment]
@mightyiam please do!

**Comment by LeSeulArtichaut** [comment]
Feel free to use the `@rustbot claim` command to assign the issue to yourself and show you're working on it

**Comment by yoshuawuyts** [comment]
yay; thanks for landing this @mightyiam!
