### ISSUE TITLE
Rustdoc feature idea: Documentation comment blocks

### ISSUE THREAD

**Issue by bdashore3** [rust-lang/rust#77108]
Hello all,

I've been using Rust for a long time and really like using Rustdoc. It's a well-made documentation system. However, adding to the documentation from code can be difficult. Here's an example.

```rust
/// Here's my documentation.
/// It looks very cool.
```

As you can see, really long documentation pages can be borderline unreadable in the source code. Instead, I would like to propose the addition of comment blocks for documentation. From a personal standpoint, block comments are easier to read in source when there's a multi-line comment. Here's an example using `//*`

```rust
//*
   * Here's my documentation.
   * It looks very cool.
*//
```

Even though most IDEs already auto-format `///` for comments, I'd at least like the option to add a doc comment block for editors that do not auto-add `///` rather than being forced to type out single-line comments.

I'd appreciate feedback as needed and if you are not keen on using block comments, can you please tell me why? Thank you.

**Comment by euclio** [comment]
Block syntax is already supported as `/**`: https://doc.rust-lang.org/stable/reference/comments.html#doc-comments

**Comment by bdashore3** [comment]
Thank you!
