### ISSUE TITLE
trait selection arbitrarily resolves projection ambiguities

### ISSUE THREAD

**Issue by benjaminp** [rust-lang/rust#77112]
```rust
trait Print<T> {
    fn print(self);
}

impl Print<char> for () {
    fn print(self) {
        println!("char");
    }
}

impl Print<usize> for () {
    fn print(self) {
        println!("usize")
    }
}

fn make1() -> impl Print<char> + Print<usize> {}

fn make2() -> impl Print<usize> + Print<char> {}

fn main() { 
    make1().print();
    make2().print();
}
```
The above program (https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=2e211dacba7209200273bf1bc6a2b77f) prints
```
usize
char
```
Not only does rustc pick without guidance between ``Print<char>::print`` and ``Print<usize>::print``, but it depends on the ordering of the predicates in the impl traits!

This problem happens because trait selection wants to prove that `make1()` implements `Print`. To do that, it arbitrarily selects `Print<usize>` even though the `Print<char>` bound would also suffice at the time of inference. It makes the opposite eager selection for `make2()`.

The same problem underlies #66057, where eager selection of projection bounds prevents further inference from removing the ambiguity.

Analogous problems exist for associated traits with multiple predicates as they go through the same trait selection code path.

**Comment by jonas-schievink** [comment]
Seems like this code maybe shouldn't compile without using fully-qualified function syntax `<_ as Print<char>>::print(make1())`, so marking for prioritization

**Comment by apiraino** [comment]
Assigning `P-medium` as discussed as part of the [Prioritization Working Group procedure](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/I-prioritize.20.2377112.20trait.20selection.20arbitrarily.20resolves.20pr.E2.80.A6) and removing `I-prioritize`.

**Comment by Aaron1011** [comment]
The issue occurs here: https://github.com/rust-lang/rust/blob/c0b15cc6ed37e626b2b5b324bbb0fdbf6688650a/compiler/rustc_trait_selection/src/traits/select/mod.rs#L1343-L1353

We pick the first matching predicate from the projection predicates of the opaque type, without checking if multiple match.

**Comment by benjaminp** [comment]
#73905 turned this into a compiler error.
