### ISSUE TITLE
Presence of Add impl for unrelated type prevents compilation

### ISSUE THREAD

**Issue by djc** [rust-lang/rust#77143]
Simplified version of https://github.com/bodil/smartstring/issues/7.

I tried this code:

```rust
fn main() {
    println!("{}", "Hello".to_string() + &(" World".to_string()));
}

struct FakeString {}

impl std::ops::Add<FakeString> for String {
    type Output = Self;
    fn add(mut self, rhs: FakeString) -> Self::Output {
        unreachable!()
    }
}
```

I expected to see this happen: this should compile correctly.

Instead, it fails like this:

```rust
error[E0277]: cannot add `&std::string::String` to `std::string::String`
 --> src/main.rs:2:40
  |
2 |     println!("{}", "Hello".to_string() + &(" World".to_string()));
  |                                        ^ no implementation for `std::string::String + &std::string::String`
  |
  = help: the trait `std::ops::Add<&std::string::String>` is not implemented for `std::string::String`
```

Removing the `Add` impl makes it work.

### Meta

This is on current stable, 1.46.0.

**Comment by jonas-schievink** [comment]
This seems like expected behavior

**Comment by djc** [comment]
I'm confused -- why would `String + &String` start failing in the presence of an impl for `String + FakeString`?

**Comment by jonas-schievink** [comment]
Because the trait system then has two impls available to select from, `impl Add<&str> for String` and `impl Add<FakeString> for String`, which means that it doesn't know to apply autoderef to the `&String` argument to get the `&str`.

**Comment by djc** [comment]
Hmm, okay. So I guess this is a duplicate for #44619.

**Comment by andy128k** [comment]
@jonas-schievink It doesn't compile even if a `FakeString` and an `Add` implementation are in a separated private module.

```rust
mod x {
    struct FakeString {}

    impl std::ops::Add<FakeString> for String {
        type Output = Self;
        fn add(mut self, rhs: FakeString) -> Self::Output {
            unreachable!()
        }
    }
}

mod y {
    pub fn hw() {
        println!("{}", "Hello".to_string() + &(" World".to_string()));
    }
}
```

**Comment by jonas-schievink** [comment]
Yeah, that doesn't affect trait selection to my knowledge

**Comment by erenon** [comment]
Is there a workaround for this issue, short of removing the offending Add implementations? (as they can be in dependencies. e.g: I'm unable to add prometheus_client, as it breaks other code in the project)

**Comment by mattfbacon** [comment]
Deref manually. https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=7c82ca60a0948542d77fde6431e40643
