### ISSUE TITLE
Adding Op<&T> bound breaks code depending on Op<T> bound

### ISSUE THREAD

**Issue by WaffleLapkin** [rust-lang/rust#77159]
I tried this code:

```rust
trait Op<Arg> { 
    fn op (_: Arg); 
}

trait Trait<'lt>: 'lt + Sized + Op<Self> + Op<&'lt Self> {}

trait WithAssoc<'lt> { type Assoc: Trait<'lt>; }

fn test<'lt, T: WithAssoc<'lt>> (it: T::Assoc) {
    <T::Assoc as Op<_>>::op(it)
}
```

I expected to see this happen: code compiles

Instead, this happened: code doesn't compile with the following error:

```
error[E0308]: mismatched types
  --> src/lib.rs:10:29
   |
10 |     <T::Assoc as Op<_>>::op(it)
   |                             ^^ expected reference, found associated type
   |
   = note:    expected reference `&'lt <T as WithAssoc<'lt>>::Assoc`
           found associated type `<T as WithAssoc<'lt>>::Assoc`
help: consider constraining the associated type `<T as WithAssoc<'lt>>::Assoc` to `&'lt <T as WithAssoc<'lt>>::Assoc`
   |
9  | fn test<'lt, T: WithAssoc<'lt, Assoc = &'lt <T as WithAssoc<'lt>>::Assoc>> (it: T::Assoc) {
   |                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
help: consider borrowing here
   |
10 |     <T::Assoc as Op<_>>::op(&it)
   |                             ^^^
```

1) `T::Assoc` should implement `Op<T::Assoc>` so the error shouldn't happen
2) Compiler suggests using `T: WithAssoc<'lt, Assoc = &'lt <T as WithAssoc<'lt>>::Assoc>` which is reccursion
3) The code works if
   1. you'll remove `+ Op<&'lt Self>`
   2. you'll use op with explicit type `<T::Assoc as Op<T::Assoc>>::op(it)`
4) There is a weird spacing between `= note:` and `expected reference ...` though this is unrelated to the problem
   
Playground: [[link]](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=59c0e7831b439a5f6d13eedf73912c18)

### Meta

tested on `1.46.0` and `1.48.0-nightly` (2020-09-23 8b4085359ae798dedb05)

**Comment by tavianator** [comment]
This "fixes" it:

```
trait Trait<'lt>: 'lt + Sized + Op<&'lt Self> + Op<Self> {}
```

so I think this is the same issue as https://github.com/rust-lang/rust/issues/72582

**Comment by tavianator** [comment]
This is fixed by https://github.com/rust-lang/rust/pull/73905
