### ISSUE TITLE
Unused variables lint does not work inside an array length expression

### ISSUE THREAD

**Issue by ecstatic-morse** [rust-lang/rust#77169]
Array length expressions can can do anything that a `const` initializer can. However, the unused variables lint does not work inside an array length expression. For example,

```rust
fn main() {
    let _ = [(); {
        let x = 42;
        35
    }];
}
```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=d049315166724f100c266cdfda761e89))

...compiles with no warnings:

```
   Compiling playground v0.0.1 (/playground)
    Finished dev [unoptimized + debuginfo] target(s) in 0.51s
     Running `target/debug/playground`

```

**Comment by lzutao** [comment]
Seems like the liveness of `x` is over the block contains it, if I read the log right.
https://gist.github.com/lzutao/2053546ae057353af4f31cddc4676f58
