### ISSUE TITLE
Vec does not implement ExactSizeIterator

### ISSUE THREAD

**Issue by josephg** [rust-lang/rust#77214]
Vec implements `Iterator` but for some reason it does not implement `ExactSizeIterator`. Strangely, `vec.iter()` does.

[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a49025500ec8d61918c33e222d0ac493)

```rust
fn iter_len<I: ExactSizeIterator<Item=Item>, Item>(iter: I) {
    println!("size {}", iter.len());
}

fn main() {
    let v: Vec<u8> = vec![1,2,3];

    // iter_len(v); // Error: the trait `std::iter::ExactSizeIterator` is not implemented for `std::vec::Vec<u8>`

    iter_len(v.iter()); // ok
}
```

**Comment by ishitatsuyuki** [comment]
`Vec` does not implement `Iterator`. What you want is `IntoIterator`.

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=5db4f1ebd4cae732ef7d20e197a8f645

```rust
fn iter_len<
    I: IntoIterator<IntoIter = Iter, Item = Item>,
    Iter: Iterator<Item = Item> + ExactSizeIterator,
    Item,
>(
    iter: I,
) {
    println!("size {}", iter.into_iter().len());
}

fn main() {
    let v: Vec<u8> = vec![1, 2, 3];
    iter_len(v.iter()); // ok
    iter_len(v);
}
```

The syntax is pretty annoying though, not sure if this can be simplified.

**Comment by oli-obk** [comment]
A bit less verbose:

```rust
fn iter_len<I: IntoIterator>(iter: I)
where
    I::IntoIter: ExactSizeIterator,
{
    println!("size {}", iter.into_iter().len());
}
```

I don't think there's any action we can take on our end except maybe make the diagnostic report a suggestion for a method call

**Comment by josephg** [comment]
Ah cool beans. Happy to close this.
