### ISSUE TITLE
Rebranding Rust compiler is extremely unpractical -- can't easily exercise freedom 3

### ISSUE THREAD

**Issue by mimi89999** [rust-lang/rust#77234]
Hello,

[Rust trademark policy](https://www.rust-lang.org/policies/media-guide) states that:
> Distributing a modified version of the Rust programming language or the Cargo package manager and calling it Rust or Cargo requires explicit, written permission from the Rust core team. We will usually allow these uses as long as the modifications are (1) relatively small and (2) very clearly communicated to end-users.

While Rust license allows to distribute modified copies and grants freedom 3, Rust trademark policy prohibits that. This makes it very impractical to exercise freedom 3. Even if somebody makes minor changes, they will need to rebrand the entire compiler and build tools. That's a huge work. Some distributions have issues with that: https://wiki.hyperbola.info/doku.php?id=en:main:rusts_freedom_flaws. The free software community has doubts if Rust compiler and Cargo can be considered free software or not because it's ND by rebranding impracticability.

I think that all branding should be defined in one file or folder making it easy for somebody who wants to distribute modified copies to rebrand. Firefox has the same trademark policy as Rust, but they at least make it relatively easy to rebrand the browser: https://searchfox.org/mozilla-central/source/browser/branding/unofficial

**Comment by est31** [comment]
The trademarks `rust` and `cargo` also appear in many places in the interface, like through `Cargo.toml` or `rustc` and `cargo` binary names, or in `RUST_BACKTRACE`, various env vars that [cargo sets](https://doc.rust-lang.org/cargo/reference/environment-variables.html#environment-variables-cargo-reads) etc.

IMO once a foundation is set up, the trademark policy should be changed to be more tolerant towards this.

**Comment by marmeladema** [comment]
`The free software community has doubts`
Could you be more explicit and describe precisely who you are speaking for?
The free software community is large and etherogeneous group with individuals that might not recognize themselves in your saying.

**Comment by FrostKnight** [comment]
I would also like this trademark issue resolved, as it is too restrictive to include in some linux distros. :/

Please fix! :)

**Comment by Semisol** [comment]
Bump on this.

**Comment by programmerjake** [comment]
ping

**Comment by Dylan-DPC** [comment]
Closing this as the trademark policy is being tracked in another issue and it's better there than leaving an old issue open hoping someöne spots it.

**Comment by FrostKnight** [comment]
> Closing this as the trademark policy is being tracked in another issue and it's better there than leaving an old issue open hoping someöne spots it.

Can you tell me which issue it is being tracked on? I am curious to follow the progress of it. To know if it will be fixed.

**Comment by FrostKnight** [comment]
I just wonder why the rust foundation has to make rebranding rust compiler so hard. That's not solving anything nor is it a solution to anything. It just seems like trademark bullying to prevent modified versions out of sheer megalomaniacal desires . I hope that irelativism turns out to be wrong about what is happening. But i have my doubts. I hope to be wrong though.

**Comment by irelativism** [comment]
Also there is claims of "speculation" when the valid argument and explanation would be shared this would just be deleted or censored, not to speak on issue #93157  everything is explained in great detail, the issue remains has allways with the obnoxious commercial clause that has its root on the mozzila media guide.
