### ISSUE TITLE
Additional docs on pub re-exports resolve intra-doc links relative to the original module

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#77254]
I tried this code:

```rust
/// I want to show [with_code]
pub use std::string::String;

pub fn with_code() {}
```

I expected to see this happen: Rustdoc links all the original documentation relative to `std::string`, and all the new documentation relative to the current crate, so `with_code` resolves properly.

Instead, this happened: Rustdoc links all the original documentation relative to `std::string`:

```
Sep 26 22:41:10.388  INFO rustdoc::passes::collect_intra_doc_links: ignoring warning from parent crate: unresolved link to `with_code`
```

This hits proc-macros especially hard because they're forced to be in a separate crate and can't link to _anything_ in the main crate.

### Meta

`rustdoc --version`: rustdoc 1.48.0-nightly (f68e08933 2020-09-19), but also present on master (https://github.com/rust-lang/rust/commit/1ec980d225fff2346a1a631a7ffc88b37e9e18af)

**Comment by jyn514** [comment]
Originally I thought this would need pulldown support, but I might be able to hack it by using the span of the link.

**Comment by jyn514** [comment]
I'm not sure it's possible to go from a `Span` to the module it's defined in :/

**Comment by jyn514** [comment]
Another possible approach is to use the `DefId` of the use statement itself, but that requires fixing https://github.com/rust-lang/rust/issues/77230 first.

**Comment by jyn514** [comment]
> Originally I thought this would need pulldown support, but I might be able to hack it by using the span of the `BrokenLink` pulldown returns.

It turns out pulldown [already has this support](https://github.com/raphlinus/pulldown-cmark/issues/486) in the form of [`into_offset_iter`](https://docs.rs/pulldown-cmark/0.8.0/pulldown_cmark/struct.Parser.html#method.into_offset_iter).

**Comment by jyn514** [comment]
So I don't forget, this is my current progress:

- Refactor `DocFragments`; this was simple and needed to add the `HirId` for the docs (https://github.com/rust-lang/rust/pull/77513)
- Require a `HirId` for `try_inline`. This was not too painful but not very useful in itself. It does not currently handle multiple re-exports, I just have an `unimplemented!()` (not published).
- Take an optional `HirId` in `merge_attrs`. This is necessary but not sufficient for keeping track of the HirId for the attrs.
- Take an optional `HirId` in `Attributes::from_ast`; again, necessary but not sufficient.

The issue I currently have is that attributes are combined _before_ calling `from_ast`, and I'm not sure how to work merging attrs into `from_ast`. Maybe it could take `attrs: &[ast::Attribute]` and `other_attrs: &[...]`, plus a HirId for both? That seems not _too_ painful; I'll need to slightly refactor `from_ast` to allow doing the same inner actions for two different lists. I have no idea how to generalize this to arbitrary re-exports - maybe `Vec<(&[ast::Attribute], HirId)>`?

**Comment by jyn514** [comment]
The painful thing is going to be working this into `impl Clean<Attributes> for [ast::Attribute]` - `Clean` doesn't allow taking any additional parameters and turning it into a free function instead causes about 30 non-trivial errors.

**Comment by jyn514** [comment]
Actually this might work - the original `HirId` will always correspond to the `DefId`, so it can just be none. Then any following attributes will make the HirId mandatory. 🤞

**Comment by jyn514** [comment]
A new problem: `collapse_docs` turns all attributes into one giant attribute 🤦 @GuillaumeGomez do you know what that's for? Is it safe to just get rid of it and insert newlines between docs instead?

**Comment by GuillaumeGomez** [comment]
I think it's to merge both `#[doc = "..."]` and `///` attributes.
