### ISSUE TITLE
case-related lints (non_snake_case, non_camel_case_types, …) did not suggest actual case-changed characters with Mathematical Alphanumeric Symbols

### ISSUE THREAD

**Issue by kennytm** [rust-lang/rust#77273]
This example code:

```rust
let 𝓢𝓝𝓐𝓐𝓐𝓐𝓚𝓔𝓢 = 1;
```

Produced a useless conversion suggestion:

```
warning: variable `𝓢𝓝𝓐𝓐𝓐𝓐𝓚𝓔𝓢` should have a snake case name
 --> src/main.rs:4:9
  |
4 |     let 𝓢𝓝𝓐𝓐𝓐𝓐𝓚𝓔𝓢 = 1;
  |         ^^^^^^^^^ help: convert the identifier to snake case: `𝓢𝓝𝓐𝓐𝓐𝓐𝓚𝓔𝓢`
  |
  = note: `#[warn(non_snake_case)]` on by default
```

The problem here is that while these characters are in the Uppercase Letter (Lu) general category, they do not have a proper lowercase mapping: the lowercase of [𝓐](https://util.unicode.org/UnicodeJsps/character.jsp?a=1D4D0) is still [𝓐](https://util.unicode.org/UnicodeJsps/list-unicodeset.jsp?a=[:Lowercase_Mapping=%F0%9D%93%90:]), not 𝓪 (thus Rust cannot suggest `𝓼𝓷𝓪𝓪𝓪𝓪𝓴𝓮𝓼`).

This is the same for the other direction:

```
warning: type `𝕟𝕠𝕥_𝕒_𝕔𝕒𝕞𝕖𝕝` should have an upper camel case name
 --> src/lib.rs:3:8
  |
3 | struct 𝕟𝕠𝕥_𝕒_𝕔𝕒𝕞𝕖𝕝;
  |        ^^^^^^^^^^^ help: convert the identifier to upper camel case: `𝕟𝕠𝕥𝕒𝕔𝕒𝕞𝕖𝕝`
  |
  = note: `#[warn(non_camel_case_types)]` on by default
```

It shouldn't produce the suggestion at all if the conversion result is not changed, but I'm not sure about cases involving adding or removing underscores.

### Meta

rustc on playground, 1.48.0-nightly (2020-09-26 623fb90b5a1f324e0ec4).

**Comment by 3nt3** [comment]
I'd like this reopened because it seems like variables like `Δφ` still result in a suggestion that is identical to the variable name.

(rustc 1.68.0-nightly (52372f9c7 2023-01-21))
