### ISSUE TITLE
`async` blocks in a const-context error on nightly, but not on stable

### ISSUE THREAD

**Issue by DutchGhost** [rust-lang/rust#77361]
The following code compiles on stable, but not on nightly. I know this is realy bogus code, and I'm not sure it should be rejected:
```Rust
fn regress() -> [(); { core::mem::ManuallyDrop::new(async { 0 }); 4 }] {
    todo!()
}
```

On nightly, the error message is:
```
error: `from_generator` is not yet stable as a const fn
 --> src/lib.rs:2:60
  |
2 | fn regress() -> [(); { core::mem::ManuallyDrop::new(async { 0 }); 4 }] {
  |                                                            ^^^^^^^^^
  |
  = help: add `#![feature(gen_future)]` to the crate attributes to enable

error: aborting due to previous error

error: could not compile `playground`

To learn more, run the command again with --verbose.
```

**Comment by lcnr** [comment]
cc @ecstatic-morse in case this is related to what you were doing recently

**Comment by lzutao** [comment]
searched nightlies: from nightly-2020-08-20 to nightly-2020-09-30
regressed nightly: nightly-2020-09-24
searched commits: from https://github.com/rust-lang/rust/commit/0da58007451a154da2480160429e1604a1f5f0ec to https://github.com/rust-lang/rust/commit/8b4085359ae798dedb05c95ad42520557bd25320
regressed commit: https://github.com/rust-lang/rust/commit/f6d59207ad56e24a2bfefa3544de48a0f6491363

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.5.2</summary>


Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc 2020-08-20 --end 2020-09-30 --preserve --regress=error --without-cargo 
```
</details>

---

That's #76850

**Comment by ecstatic-morse** [comment]
cc @rust-lang/wg-const-eval This code was allowed erroneously; async-await has not been stabilized in a const-context. I believe we have exceptions to the backwards compatibility rules for cases like this? Actually *doing* anything with the `async` block (`.await`, dropping it) will cause an error during const-checking, so this is useless as far as I know.

This also works in a regular const initializer:

```
const _: i32 = { core::mem::ManuallyDrop::new(async { 0 }); 4 };
```

**Comment by camelid** [comment]
Hmm, the span in the error shown above seems wrong:

```
error: `from_generator` is not yet stable as a const fn
 --> src/lib.rs:2:60
  |
2 | fn regress() -> [(); { core::mem::ManuallyDrop::new(async { 0 }); 4 }] {
  |                                                            ^^^^^^^^^
  |
  = help: add `#![feature(gen_future)]` to the crate attributes to enable
```

It's pointing at the section from the space before the `0` to the space after the `4`? But the error from the playground looks correct:

```
error: `from_generator` is not yet stable as a const fn
 --> src/lib.rs:1:53
  |
1 | fn regress() -> [(); { core::mem::ManuallyDrop::new(async { 0 }); 4 }] {
  |                                                     ^^^^^^^^^^^
  |
  = help: add `#![feature(gen_future)]` to the crate attributes to enable
```

@DutchGhost is that how the error appeared to you when you ran into it?

**Comment by camelid** [comment]
Temporarily assigning `P-medium` per the prioritization working group [discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/I-prioritize.20.2377361.20Compilation.20succeeds.20on.20stable.2C.20but.20not.E2.80.A6).

**Comment by oli-obk** [comment]
Yea this was never intended to get stabilized and since it's only possible in code that doesn't actually do anything, this is unlikely to occur in practice. I don't see a reasonable way to allow this. Note the same effect is possible with `std::mem::forget`.

**Comment by camelid** [comment]
So should we remove `regression-from-stable-to-nightly`? It sounds like it's not a regression; it's a bug fix.

**Comment by RalfJung** [comment]
I think this falls under "accidental stabilization".

> This also works in a regular const initializer:

Still works, or used to work? If it still works that arguably is a bug,

**Comment by ecstatic-morse** [comment]
The second. You can try it in the playground.

I'm assigning myself to give a better error message in these cases.

**Comment by DutchGhost** [comment]
Since the PR improving the error message for cases like this has been merged, this issue can be closed?
