### ISSUE TITLE
rustc_metadata: Deduplicate code between `encode_info_for_item` and `encode_info_for_foreign_item`

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rust#77393]
The set of data to record for regular items and foreign items is pretty similar, but slightly different.
When metadata encoding is done independently for them, issues like https://github.com/rust-lang/rust/pull/77375 arise.

`encode_info_for_trait_item` and `encode_info_for_impl_item` are also similar, and also slightly different (all in different directions), so they may be included into the refactoring as well.

**Comment by jyn514** [comment]
Relevant code:
https://github.com/rust-lang/rust/blob/d902752866cbbdb331e3cf28ff6bba86ab0f6c62/compiler/rustc_metadata/src/rmeta/encoder.rs#L1223
https://github.com/rust-lang/rust/blob/d902752866cbbdb331e3cf28ff6bba86ab0f6c62/compiler/rustc_metadata/src/rmeta/encoder.rs#L1725
https://github.com/rust-lang/rust/blob/d902752866cbbdb331e3cf28ff6bba86ab0f6c62/compiler/rustc_metadata/src/rmeta/encoder.rs#L965
https://github.com/rust-lang/rust/blob/d902752866cbbdb331e3cf28ff6bba86ab0f6c62/compiler/rustc_metadata/src/rmeta/encoder.rs#L1054

**Comment by 1c3t3a** [comment]
I'd like to give this a try if mentoring is available!

**Comment by 1c3t3a** [comment]
Is it 'just' refactoring the methods all together?

**Comment by petrochenkov** [comment]
The goal is to make the code nicer and less error-prone, but I'm not sure which exactly refactoring to apply to do that.
As I mentioned above all the methods are slightly different. Perhaps some of the called `encode_*` functions can be tweaked to accommodate for the differences.
The issue is `E-easy` in the sense that the changes will certainly be easy to implement, but what those changes should be is a question.
It needs experimentation.

**Comment by pitaj** [comment]
Hi I'd like to try my hand at this so I [made a small change](https://github.com/pitaj/rust/commit/1ed9248c5fde9f10bb689d9741680743e3a30afa) to align the contents of `encode_info_for_item` and `encode_info_for_foreign_item`. I created new conditional helper methods and rearranged things to both have the following calls:
```rust
        self.encode_ident_span(def_id, ...);
        record!(self.tables.visibility[def_id] <-
            ty::Visibility::from_hir(...));
        record!(self.tables.attributes[def_id] <- ...);
        self.encode_stability(def_id);
        self.encode_const_stability(def_id);
        self.encode_deprecation(def_id);
        self.encode_item_type_when(def_id, ...);
        self.encode_inherent_implementations(def_id);
        self.encode_function_signature_when(
            def_id,
            matches!(...),
        );
        self.encode_generics(def_id);
        self.encode_variances_when(def_id, matches!(...));
        self.encode_explicit_predicates(def_id);
        self.encode_generics_explicit_predicates_inferred_outlives_when(def_id, ...);
```

I'd then pull those calls out into a single helper method. Am I headed in the right direction? If so I'll keep going. My strategy is to dedupe `_item` and `_foreign_item`, then dedupe `_trait_item` and `_impl_item`, then dedupe the result of those if it makes sense to.

Couple questions:

- What is the difference between [`tcx.def_span` and `item.span`](https://github.com/pitaj/rust/commit/1ed9248c5fde9f10bb689d9741680743e3a30afa#diff-72bf3e63aae0c5f24a5ce78a560db321ac6ead9df5ada3e33462a7f7d6218a55R1422)?
- Does the order of `record!`s matter?

**Comment by petrochenkov** [comment]
@pitaj 
>Does the order of `record!`s matter?

No, it shouldn't matter.
(And if it does you'll get test suit failures anyway.)

>What is the difference between `tcx.def_span()` and `item.span`?

For functions `def_span` returns the span of its header, not the whole function with body, for other items it will return `item.span`.
`def_span` is preferable by default.

**Comment by petrochenkov** [comment]
This is no longer relevant with the recent metadata encoding changes in #80347 and related PRs.
