### ISSUE TITLE
Make all mir optimizations respect the optimization fuel

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#77402]
Right now only inlining actually uses optimization fuel (`-Zfuel=42`). We should start adding it to all of our optimizations and requiring new optimizations to use it.

cc @rust-lang/wg-mir-opt

**Comment by jonas-schievink** [comment]
It is also used by:

* Layout computation (the original use case)
* Destination propagation

**Comment by ecstatic-morse** [comment]
Adding a paragraph to the MIR optimizations part of the `rustc-dev-guide` would help I think.

**Comment by cjkenn** [comment]
Is there still interest in this? I'm new to this section of the compiler but this seems like a nice introduction to some mir passes. If I understand correctly, we need to add calls to `tcx.consider_optimizing(...)` in the appropriate places (ie. before the optimization is performed, not necessarily right at the start of the pass) for each pass in the `transform` crate? Or is there a different way to implement this?

**Comment by oli-obk** [comment]
Sorry about the late response.

Yes, we still want this. I personally haven't used it before, so your guess is as good as mine, but what you wrote sounds reasonable. Ideally look at how other passes use it and then try to apply it to some pass that seems expensive
