### ISSUE TITLE
Tracking Issue for `#![feature(const_impl_trait)]`

### ISSUE THREAD

**Issue by ecstatic-morse** [rust-lang/rust#77463]
This allows argument and return position `impl Trait` in the signature of a `const fn`. It also allows `impl Trait` in other const-contexts, although this is only possible with additional feature gates (see #63065).

Formerly, this was gated under [`#![feature(const_fn)]`](https://github.com/rust-lang/rust/issues/57563).

**Comment by jhpratt** [comment]
What are the blockers on this?

**Comment by memoryruins** [comment]
This has been stabilized last month in https://github.com/rust-lang/rust/pull/93827 and will likely be in the next release, 1.61.

**Comment by pnkfelix** [comment]
This is done! Closing.
