### ISSUE TITLE
Add #[track_caller] support to `?`

### ISSUE THREAD

**Issue by yaahc** [rust-lang/rust#77474]
Right now if you construct an error via its `Into` implementation as provided by the blanket implementation in `std` it gives the following location.

```
Location:
   /home/jlusby/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/convert/mod.rs:545
```

We should add `#[track_caller]` to this trait and possibily some of the `Try` trait implementations so that errors that attempt to track their construction point can correctly point to user code.

cc @anp

**Comment by c410-f3r** [comment]
Is anything preventing this addition? If not, then I can create a PR

**Comment by BGR360** [comment]
@c410-f3r Since my last comment in August, there has been further discussion about this in various places. IIRC, @yaahc resolved to add `#[track_caller]` to something, I think it was `Into`? That change might already be in. I'll go hunting in my notification history to see if I can find what I'm talking about.

**Comment by BGR360** [comment]
It was to `from_residual` and it has been merged: https://github.com/rust-lang/rust/pull/91752

Unless it has been since removed again, I think that means this issue can be closed?

**Comment by c410-f3r** [comment]
Thanks @BGR360

Unfortunately, such change did not prevent an error I am currently facing that also points stuff to `... library/core/src/convert/mod.rs`.

![Capture d’écran de 2022-03-21 19-05-04](https://user-images.githubusercontent.com/17877264/159371865-88aa9252-2a1d-41ac-9d97-8c53e446e3bd.png)

But this can be reported in another issue with an appropriated reproducible snippet

**Comment by yaahc** [comment]
I was worried it would still be broken, I remember in the past it losing the location when it went through `Into` and I thought I remembered `?` desugaring to use `Into` but it looks like it uses `From`, so it seems to work fine for my small snippet using eyre.

:+1: @c410-f3r for opening a new issue for this specific issue. I'm gonna go ahead and close this one for now.
