### ISSUE TITLE
compiletest should remove `.stderr` for nonexistent revisions

### ISSUE THREAD

**Issue by varkor** [rust-lang/rust#77498]
I added a normal `ui` test, generated a `.stderr`, then later added revisions to the test so that `revA.stderr` and `revB.stderr` files were generated. I forgot to manually remove the old `.stderr` file, and so I ended up committing it, despite it now being unused. It would be nice if compiletest automatically caught this situation (it probably also applies to when the list of revisions is changed).

**Comment by jyn514** [comment]
It might be easier to make this a tidy check.
