### ISSUE TITLE
x86 instrinsic _mm_insert_epi8 is not being inlined

### ISSUE THREAD

**Issue by eduardosm** [rust-lang/rust#77507]
I tried this code:

```rust
use std::arch::x86_64::*;

pub fn f(src: *const u8, dst: *mut u8) {
    unsafe {
        let v = _mm_loadu_si128(src as *const _);
        let v = _mm_insert_epi8(v, 0xFF, 0);
        _mm_storeu_si128(dst as *mut _, v);
    }
}
```

[Playground](https://play.rust-lang.org/?version=stable&mode=release&edition=2018&gist=d6d35edae2793e9c0e76e6f3d9efd418)

I expected to see this happen:

In release mode, assembly like this:
```asm
playground::f:
	movups	xmm0, xmmword ptr [rdi]
	mov eax, 255
	pinsrb	xmm0, eax, 0
	movups	xmmword ptr [rsi], xmm0
	ret
```

Instead, this happened:

The `_mm_insert_epi8` instrinsic did not get inlined, producing the following assembly:
```asm
core::core_arch::x86::sse41::_mm_insert_epi8:
	movdqa	xmm0, xmmword ptr [rsi]
	mov	eax, 255
	pinsrb	xmm0, eax, 0
	movdqa	xmmword ptr [rdi], xmm0
	ret

playground::f:
	push	rbx
	sub	rsp, 32
	mov	rbx, rsi
	movups	xmm0, xmmword ptr [rdi]
	movaps	xmmword ptr [rsp + 16], xmm0
	mov	rdi, rsp
	lea	rsi, [rsp + 16]
	call	core::core_arch::x86::sse41::_mm_insert_epi8
	movaps	xmm0, xmmword ptr [rsp]
	movups	xmmword ptr [rbx], xmm0
	add	rsp, 32
	pop	rbx
	ret
```

### Meta

I tried stable (1.46.0) and nightly from playground.

**Comment by jonas-schievink** [comment]
This is working as intended, you need to use `#[target_feature(enable = "sse4.1")]` on the function (or build with the right `-Ctarget-feature`)

**Comment by eduardosm** [comment]
https://doc.rust-lang.org/reference/attributes/codegen.html

> Functions marked with target_feature are not inlined into a context that does not support the given features. The #[inline(always)] attribute may not be used with a target_feature attribute.

Thanks for pointing it out. Indeed `#[target_feature(enable = "sse4.1")]` makes the inlining work.
