### ISSUE TITLE
Improve borrow checking

### ISSUE THREAD

**Issue by heckad** [rust-lang/rust#77505]
I tried this code:

```rust
fn main() {
    let mut v = vec![1, 2, 3];

    let head = {
        std::mem::replace(&mut v, v.split_off(1))
    };
}
```

I expected to see this happen: all good.

Instead, this happened: error: `cannot borrow `v` as mutable more than once at a time`

If I rewrite this code onto

```rust
fn main() {
    let mut v = vec![1, 2, 3];

    let head = {
        let t = v.split_off(1);
        std::mem::replace(&mut v, t)
    };
}
```
then all be nice.

**Comment by jonas-schievink** [comment]
This is covered by the work on generalized two-phase borrows, which is tracked in https://github.com/rust-lang/rust/issues/49434. Possibly an RFC amendment would be required to make this case work, since I'm not sure if that is covered by the existing design work.
