### ISSUE TITLE
rustdoc: Suggest to turn 'http...' into an automatic link

### ISSUE THREAD

**Issue by HackAttack** [rust-lang/rust#77501]
It would be nice if a raw hyperlink (with no markup) in a doc comment were rendered out as an anchor tag, à la GitHub. Otherwise you have to write
```rust
/// Check out this link: [https://example.com](https://example.com)
fn foo();
```
This would maximize readability in the code while slightly improving the generated HTML.

**Comment by jyn514** [comment]
You can write `<https://example.com>` instead. I don't think rustdoc should add more custom markdown extensions.

**Comment by jonas-schievink** [comment]
You can also use `<https://example.com>`, which imo is the proper way to do raw URLs in markdown.

**Comment by HackAttack** [comment]
Well how about that…this was not clear from any documentation I found. Thanks, this is certainly good enough, though I will note that GitHub, Bitbucket, and the IntelliJ Rust plugin all auto-link in this way, so it might still be worth considering from a least-surprise perspective.

**Comment by jyn514** [comment]
It's documented here: https://www.markdownguide.org/basic-syntax#urls-and-email-addresses

Maybe rustdoc should link to a markdown guide? I don't think it necessarily needs to document all of markdown though.

**Comment by estebank** [comment]
It would be reasonable to have a warm by default lint for this with a structured suggestion.

**Comment by GuillaumeGomez** [comment]
Adding a lint for this then!
