### ISSUE TITLE
Spurious linker OOM in CI

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/rust#77510]
The MSVC builder occasionally fails with

> `   = note: LINK : fatal error LNK1102: out of memory`

Seen in:

* https://github.com/rust-lang/rust/pull/72079#issuecomment-627269191
* https://github.com/rust-lang/rust/pull/76186#issuecomment-684173315
* https://github.com/rust-lang/rust/pull/76313#issuecomment-689271569
* https://github.com/rust-lang/rust/pull/77369#issuecomment-702832400
* https://github.com/rust-lang/rust/pull/77080#issuecomment-703051095

**Comment by bjorn3** [comment]
Does this still happen?

**Comment by jieyouxu** [comment]
Triage: have not seen this for a good while, closing in favor of a new issue if this is still a problem.
