### ISSUE TITLE
Render Markdown for error code explanations in `rustc --explain`

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#77536]
This would be really nice to have, but it might be a lot of work.

When I say "render Markdown", I mean to style it somewhat in the terminal: styling with bold or italic, showing links in a different color, syntax highlighting code snippets, etc. See [`gh`](https://cli.github.com), the GitHub CLI, for some examples of how we could do this.

**Comment by Mark-Simulacrum** [comment]
I don't think anything has changed since https://github.com/rust-lang/rust/issues/63128; I am still inclined to say this is out of scope.

**Comment by camelid** [comment]
Ah, I tried searching for other issues but didn't find that one. Closing for now.
