### ISSUE TITLE
AVR: interrupt code broken by optimization flags

### ISSUE THREAD

**Issue by no111u3** [rust-lang/rust#77541]
I've run into an issue with code that uses interrupts on AVR. I'm not sure if this applies to any other platform.
This issue has same behavior as #75504 but It can't resolved after update compiler to current nightly version.
This issue reproduce on everything nightly rust compiler with AVR target support (I trying to compile it every nightly compiler updates).

I create minimal reproduce project for this issue - https://github.com/no111u3/m328p_robo_rust. Than I change optimization flags to size optimization level `opt-level="z"` or `opt-level="s"` upper code doesn't work correctly, there has two options:
 - for release build there is broken in interrupt handler code
 - for debug build there is broken fully, code run stopped and mcu looks halted.

I run upper code on two different mcu's that I have: on Atmega48 and Atmega328p, if we use same flags we have same behavior for run. For optimization level 2 I can use huge code in interrupt such as - https://github.com/no111u3/m48_robo_rust/blob/master/examples/dynamic_indication.rs#L119 but If I use `z` or `s` optimization interrupt works only for short code such as - https://github.com/no111u3/m48_robo_rust/blob/master/examples/pwm_int.rs#L39

**Comment by couchand** [comment]
@no111u3 would you mind pasting in the assembler output for the builds?  You can get that by compiling with the RUSTFLAGS environment variable: `RUSTFLAGS='--emit asm'`.  Thanks!

**Comment by no111u3** [comment]
> @no111u3 would you mind pasting in the assembler output for the builds? You can get that by compiling with the RUSTFLAGS environment variable: `RUSTFLAGS='--emit asm'`. Thanks!

This is not possible because:
`Caused by:
  process didn't exit successfully: rustc --crate-name core --edition=2018 /Users/nis/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=2 -C panic=abort -C linker-plugin-lto -C debuginfo=2 -C debug-assertions=on -C metadata=bb7c8a4bc5fd3810 -C extra-filename=-bb7c8a4bc5fd3810 --out-dir /Users/nis/Develop/m328p_robo_rust/target/avr-atmega328p/debug/deps --target /Users/nis/Develop/m328p_robo_rust/avr-atmega328p.json -Z force-unstable-if-unmarked -L dependency=/Users/nis/Develop/m328p_robo_rust/target/avr-atmega328p/debug/deps -L dependency=/Users/nis/Develop/m328p_robo_rust/target/debug/deps --cap-lints allow --emit asm (signal: 11, SIGSEGV: invalid memory reference)
warning: build failed, waiting for other jobs to finish...
error: build failed`

**Comment by Patryk27** [comment]
fwiw, I think this was solved after https://github.com/rust-lang/rust/pull/96845, too 🙂

**Comment by workingjubilee** [comment]
This reproducer uses crates that depend on nightly features that are no longer enabled by the compiler and patches against unmarked git repos without reference to a revision or even branch. If you can remake this with updated dependencies, or without dependencies at all, we can look into this. However, until then, I am going to close this. Sorry!
