### ISSUE TITLE
x.py fails to update src/llvm-project submodule

### ISSUE THREAD

**Issue by thomcc** [rust-lang/rust#77556]
I tried this code:

```
$ git pull
$ ./x.py --help
```

Usually this is enough to get x.py to fixup all the submodules so that I don't have to worry about them. This time, it did most of them, but left the `src/llvm-project` submodule.

`git submodule update` did fix src/llvm-project, but I try not to manually manage the submodules, for fear that it will interact poorly with x.py's automatic handling of it. So, this is some bug in the automatic handling of submodules, maybe.

Note: This was my first update in quite a while, maybe 3 weeks.

P.S. Sorry for the spam prior to the edit, I accidentally hit ctrl+enter before even finishing typing the basics of the issue *sigh*

**Comment by Mark-Simulacrum** [comment]
Can you paste your config.toml?

**Comment by thomcc** [comment]
At the time it would have been https://gist.github.com/thomcc/9e2bf1e9446148489dbda60a3e4cf903.

**Comment by pnkfelix** [comment]
I think I just saw something similar. At least, I had to manually do a `git submodule update --init` to get around an LLVM build issue I kept hitting at bootstrap time.

And this occurred with no config.toml at all.

I'll see if I can reproduce it, now that I have confirmed that a manual `git submodule update --init` seemed to allow progress.

**Comment by pnkfelix** [comment]
Ugh, can't reproduce now. Should have checkpointed my directory state before doing `git submodule update --init`... thought I could backtrack via `git reflog` but that is not sufficing in this case...

**Comment by jyn514** [comment]
I think it probably makes sense to close this as unactionable, since there's no clear reproduction conditions and it's very rare. It should be less and less necessary to update llvm anyway, since bootstrap is getting smarter about not cloning it in the first place.
