### ISSUE TITLE
Adding a doc comment talking about performance impacts of `assume`

### ISSUE THREAD

**Issue by tesuji** [rust-lang/rust#77561]
So LLVM hasn't changed much since nagisa wrote <https://github.com/rust-lang/rust/pull/54995#issuecomment-429302709>.
Here the link to related regression caused by using constly assume intrinsic in const fn: <https://github.com/rust-lang/rust/pull/77023#issuecomment-703378483>

I think we could include a warning for assume intrinsic about using it in const fn and should run a perf for PR using it.

https://github.com/rust-lang/rust/blob/ced813fec0fb9e883906f18b76d618baf9f5bc08/library/core/src/intrinsics.rs#L735-L737

cc @oli-obk

**Comment by RalfJung** [comment]
Is there anything specific about `const` here? Seems like what @nagisa wrote applies equally to `fn` and `const fn`.

**Comment by lolbinarycat** [comment]
triage: there is now a note about optimizations, and `assert_unchecked` also has much more explanatory documentation
