### ISSUE TITLE
Better way to store command line arguments?

### ISSUE THREAD

**Issue by catamorphism** [rust-lang/rust#7756]
As per XXXes (now FIXMEs) in std::rt::args: "Would be nice for this not to exist"

**Comment by nagisa** [comment]
> We can read /proc/self/cmdline on Linux.

This won’t work if the procfs is not mounted which can easily happen in a sandboxed environment. Not a satisfactory solution.

**Comment by steveklabnik** [comment]
Triage: fixme is still there. It's not totally clear to me that this will ever be removed.

**Comment by alexcrichton** [comment]
Ah yeah this is basically not relevant, we're as done here as we're ever gonna get basically

**Comment by steveklabnik** [comment]
RIP a 4 digit bug. an endangered species at this point.

**Comment by leo60228** [comment]
It’s strange that `std::env::args` works from a `cdylib` on basically everything except Linux. Should procfs be used as a fallback for when the runtime doesn’t initialize the arguments?
