### ISSUE TITLE
macro_rules-wrapped asm! fails on att_syntax

### ISSUE THREAD

**Issue by cuviper** [rust-lang/rust#77584]
The [`probe`](https://github.com/cuviper/rust-libprobe) crate uses `asm!` with `att_syntax`, because SDT operands are written in ELF notes, to be read by third-party tools expecting that syntax. Recently this has [regressed](https://github.com/cuviper/rust-libprobe/runs/1204132986?check_suite_focus=true):

```
~/rust/probe$ cargo check --examples
    Checking probe v0.2.1 (/home/jistone/rust/probe)
error: expected one of `)`, `att_syntax`, `nomem`, `noreturn`, `nostack`, `preserves_flags`, `pure`, or `readonly`, found `att_syntax`
 --> examples/loop.rs:4:5
  |
4 |     probe!(foo, begin);
  |     ^^^^^^^^^^^^^^^^^^^ expected one of 8 possible tokens
  |
  = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: expected one of `)`, `att_syntax`, `nomem`, `noreturn`, `nostack`, `preserves_flags`, `pure`, or `readonly`, found `att_syntax`
 --> examples/loop.rs:8:9
  |
8 |         probe!(foo, loop, i, total);
  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected one of 8 possible tokens
  |
  = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: expected one of `)`, `att_syntax`, `nomem`, `noreturn`, `nostack`, `preserves_flags`, `pure`, or `readonly`, found `att_syntax`
  --> examples/loop.rs:11:5
   |
11 |     probe!(foo, end);
   |     ^^^^^^^^^^^^^^^^^ expected one of 8 possible tokens
   |
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to 3 previous errors

error: could not compile `probe`

To learn more, run the command again with --verbose.
```

`cargo bisect-rustc` pointed me to #77275 -- cc @petrochenkov. I see that there were regressions with `asm!` during that review, but not exactly like what I'm seeing here.

### Meta

searched nightlies: from nightly-2020-09-28 to nightly-2020-10-04
regressed nightly: nightly-2020-09-30
searched commits: from https://github.com/rust-lang/rust/commit/fc2daaae610b5515438b551a2f3706196a997f35 to https://github.com/rust-lang/rust/commit/381b445ff5751f9f39ec672b623372dff09c276e
regressed commit: https://github.com/rust-lang/rust/commit/26373fb4baa9c5b8a7a1e2821fcfa930a85d327d

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.5.2</summary>

Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --access github -- check --examples
```
</details>

**Comment by cuviper** [comment]
It's probably relevant that the actual `att_syntax` token is passed as an arch-conditional `$opt:ident` parameter here:
https://github.com/cuviper/rust-libprobe/blob/ae1286b26693cc29775d71be40f09245031c8a2e/src/platform/systemtap.rs#L83

**Comment by petrochenkov** [comment]
>`cargo bisect-rustc` pointed me to #77275

Yes, I've missed this case, sorry.
Will fix soon.

**Comment by petrochenkov** [comment]
Fixed in https://github.com/rust-lang/rust/pull/77595.

**Comment by cuviper** [comment]
Works for me, thanks!
