### ISSUE TITLE
cleanup: Revert all hacks added in #39234 to avoid feeding untrusted data to libbacktrace

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rust#77622]
https://github.com/rust-lang/rust/pull/39234 is the PR that provided libbacktrace with the name of the current executable when libbacktrace was used for generating backtraces in the standard library.

libbacktrace had a history of crashes and buffer overruns, so https://github.com/rust-lang/rust/pull/39234 had to apply some logic to ensure that the passed executable is right and doesn't get replaced or go away while the current process is running, all to avoid passing untrusted data to libbacktrace.

Now we use gimli instead of libbacktrace, and gimli is more reliable, and we can feed untrusted data to it.
In the worst case the backtrace will be incorrect or absent as a result.

So all hacks that were introduced https://github.com/rust-lang/rust/pull/39234 and weren't removed in https://github.com/rust-lang/rust/pull/74682 can be removed now.

**Comment by mati865** [comment]
I can look into it this week if you don't have time.

**Comment by petrochenkov** [comment]
@mati865 
That would be great.
I'll clean this up myself next or this weekend if nobody gets to this earlier.
This should be a fast and easy task.
