### ISSUE TITLE
[ER] Wrapping::get ?

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust#77643]
For code clarity it could be a good idea to add to std::num::Wrapping a simple get method like in NonZeroU32::get.

**Comment by leonardo-m** [comment]
On the other hand NonZeroU32 contains a value that has to be zero, so it was tested in the constructor, while Wrapping could contain any value, it's just a wrapper. So perhaps accessing its value with .0 is OK.

**Comment by lzutao** [comment]
Wrapping inner type is pub. It is free to access it.

**Comment by Dylan-DPC** [comment]
closing this as the inner member is public so can be accessed directly. If anyone feels like it should have a function, you can submit an ACP directly
