### ISSUE TITLE
Very long monospace words cause rustdoc to look strange

### ISSUE THREAD

**Issue by WaffleLapkin** [rust-lang/rust#77652]
I tried this code:

```rust
/// `vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv`
pub struct Item;
```

I expected to see some kind of wrapping in rendered docs, but instead, this adds a horizontal ruler. The ruler allows moving docs 
below left panel:

<details><summary>GIF that shows the problem</summary>
<p>

![Peek 2020-10-07 16-49](https://user-images.githubusercontent.com/38225716/95342721-69667f00-08c0-11eb-8926-2e8c78820f60.gif)

</p>
</details>

### Meta

`rustdoc 1.48.0-nightly (1fd5b9d51 2020-09-20)`

cc @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
Thanks for opening the issue! I'll fix it tomorrow.
