### ISSUE TITLE
DirEntry should mention it uses a file descriptor until closed

### ISSUE THREAD

**Issue by ChrisJefferson** [rust-lang/rust#77658]
I tried this code:

```rust
use std::fs;

fn main() -> std::result::Result<(),std::io::Error> {
    let mut v : Vec<std::fs::DirEntry> = Vec::new();

    for _i in 1..10000 {
        for entry in  fs::read_dir(".")? {
        v.push(entry?); // <- this line causes problem
        }
    }
    Ok(())
}

```

I get (on linux) "Too many open files". The problem (at the POSIX level) is (I think) that DirEntry keeps a reference to the underlying directory (or file?) open, so gathering up DirEntry objects makes us run out of file descriptors.

I don't know if it's reasonable to fix this, but I feel it should be mentioned in the documentation that there is an operating-system specific limit on how many DirEntry objects can exist at any one time, so they should not be stored?

**Comment by cuviper** [comment]
Every `DirEntry` from the same `read_dir` will share that handle (via `Arc`), so it's not exactly a limit in `DirEntry` objects. For your example of `1..10000`, I would expect exactly 9999 file descriptors kept open, no matter how many entries that finds in the inner loop. That's still probably more than your default resource limit though.

**Comment by Dylan-DPC** [comment]
Closing this as it this looks to be intended and there's not much we can do since there's no limit theoretically.
