### ISSUE TITLE
make benchmarks more stable

### ISSUE THREAD

**Issue by GopherJ** [rust-lang/rust#77661]
**Describe the problem you are trying to solve**

currently cargo bench isn't so stable, it doesn't run long enough, and the data can vary a lot (20-30%), which makes it hard to know if there is really a regression or not.

**Describe the solution you'd like**
no sorry

**Notes**

**Comment by ehuss** [comment]
Transferred to the rust-lang/rust repository, as that is where the libtest harness lives.  Unfortunately, I don't think it is likely there will be much work done on libtest's benchmarking, as the future is currently uncertain (see #29553 and #66287). You will likely have better support for external benchmarking frameworks like criterion.

**Comment by the8472** [comment]
`#[bench]` measures iterations per walltime interval, more or less.
So if you don't want to switch to a different benchmark crate that supports instruction counting or does more sophisticated analysis you'll have to bring your system into a state that causes less variance. I.e. shut down background tasks, disable CPU clock boosting and check for thermal throttling which often is a problem when benching on laptops.

**Comment by GopherJ** [comment]
@the8472 even with that the results can change a lot:)

**Comment by the8472** [comment]
At least in `Vec`-related things I have been working on recently I have seen variances for a null run in the 2-10% range with two outliers around 20% (among dozens of benchmarks). But that's pure CPU/memory throughput benchmarks. If you start doing syscalls or even randomized allocations things will become noisier.

**Comment by Mark-Simulacrum** [comment]
I'm going to go ahead and close this issue, as it seems to me that it's largely a consequence of the overall bench design (wall time, not instruction counts, for example) which seems unlikely to get much more sophisticated inside the standard library. And, realistically, unless you're doing software emulation of some kind, most larger benchmarks will have some amount of uncertainty, especially if they have syscalls or the like.
