### ISSUE TITLE
Typo in ‘A-suggestion-diagnostics’ tooltip.

### ISSUE THREAD

**Issue by steffahn** [rust-lang/rust#77676]
“Area: suggestions generated by the compiler appplied by cargo fix”

@rustbot modify labels: A-meta, T-infra, C-enhancement.

**Comment by jonas-schievink** [comment]
Thanks! Fixed it.

**Comment by steffahn** [comment]
@jonas-schievink While you’re at it, these tooltips tend to have the first word capitalized.

Also they tend to have periods, (at least when it’s a full sencence). I’m noticing periods badly missing for I-prioritize and E-needs-mcve (both full sentences) and I feel like ICEBreaker-Cleanup-Crew would also deserve a period.
