### ISSUE TITLE
Rustdoc reports intradoc link errors twice if there are multiple links

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#77681]
I tried this code:

```rust
/// Links to [a] [twice][a]
///
/// [a]: not_found
pub fn f() {}
```
I expected to see this happen: Rustdoc warns once, because there is only one reference link.

Instead, this happened: Rustdoc warns twice, because there are multiple uses of the reference link.

```
warning: unresolved link to `not_found`
 --> tmp.rs:3:10
  |
3 | /// [a]: not_found
  |          ^^^^^^^^^ the module `tmp` contains no item named `not_found`
  |
  = note: `#[warn(broken_intra_doc_links)]` on by default
  = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`

warning: unresolved link to `not_found`
 --> tmp.rs:3:10
  |
3 | /// [a]: not_found
  |          ^^^^^^^^^ the module `tmp` contains no item named `not_found`
  |
  = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`
```

### Meta

`rustdoc +nightly --version`: rustdoc 1.48.0-nightly (8fe73e80d 2020-10-01)

**Comment by jyn514** [comment]
This is part of a larger ~iffy approach that rustdoc is taking: it looks at each link over and over again even if it doesn't need to. Instead it could cache the links per-module, which would not only fix this error but speed up the pass quite a bit.

**Comment by bugadani** [comment]
Ah this issue is fun!

If I place the error marker on the link resolution, it's no longer considered an intra-doc link, because it contains a `/`.

**Comment by bugadani** [comment]
Something that may not be obvious at first:
- If there are multiple reference style links, the first one always has a link type of `Shortcut`, and the rest has `Reference`.
- Which currently means that caching resolution failures for only the `Reference` link type emits at most 2 errors.
