### ISSUE TITLE
`rustc_hir::lang_items::LangItem` doesn't contain `Send`

### ISSUE THREAD

**Issue by JOE1994** [rust-lang/rust#77689]
I found that while `rustc_hir::lang_items::LanguageItems` has the API [`sync_trait()`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_hir/lang_items/struct.LanguageItems.html#method.sync_trait),
there is no API `send_trait()`.

I also found that [`rustc_hir::lang_items::LangItem`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_hir/lang_items/enum.LangItem.html) doesn't contain `Send` as one of the enum variants,
although the description for module `rustc_hir::lang_items` mentions `Send` as one of the language items.
Is there a reason to exclude `Send` from the enum `LangItem`?

May I ask what changes I can make to have `LanguageItems` have an API like `fn send_trait()` ?
[I tried making some changes in my fork](https://github.com/JOE1994/rust/commit/f7d15d5a14d9e1ed824e9dbcf8a3b769d0d561ee), but making such changes wasn't enough to achieve my objective :crying_cat_face: 

Thank you for checking out this issue :smile_cat:

**Comment by jonas-schievink** [comment]
Generally things shouldn't be language items unless required, so if `Send` isn't one, then it probably shouldn't be made into one unless there's a change that requires it.

**Comment by JOE1994** [comment]
I was able to get help from the Zulip chat ! :)
(https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp/topic/how.20to.20get.20DefId.20of.20'Send'.20trait),

I'll close this issue in favor of @jonas-schievink 's comment and @jyn514 's comment from Zulip.
