### ISSUE TITLE
Derived PartialEq cannot be used in a `const` function

### ISSUE THREAD

**Issue by mbartlett21** [rust-lang/rust#77695]
The derived PartialEq implementation cannot be used in a `const` context.

The code below gives error `E0015`
```rust
#[derive(PartialEq)]
struct A(u8);

const fn is_eq(left: &A, right: &A) -> bool {
    left == right
}
```

```
error[E0015]: calls in constant functions are limited to constant functions, tuple structs and tuple variants
 --> derive_eq_partialeq.rs:5:2
  |
5 |     left == right
  |     ^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0015`.
```

### Meta

`rustc --version --verbose`:
```
rustc 1.49.0-nightly (91a79fb29 2020-10-07)
binary: rustc
commit-hash: 91a79fb29ac78d057d04dbe86be13d5dcc64309a
commit-date: 2020-10-07
host: x86_64-pc-windows-msvc
release: 1.49.0-nightly
LLVM version: 11.0
```

**Comment by jonas-schievink** [comment]
I'm not sure this will ever work. It would require the macro to generate a `const impl` (https://github.com/rust-lang/rust/issues/67792), but there is no way it can know that that is possible at expansion time.

**Comment by leonardo-m** [comment]
What's the solution? A `#[derive(ConstPartialEq)]`? :-)

**Comment by am-1t** [comment]
`#[derive(PartialEq)]
struct A(u8);

const fn is_eq(left: &A, right: &A) -> bool {
    left.0 == right.0
}
`
this seems to fix the issue

**Comment by am-1t** [comment]
this seems to fix the issue:
```
#[derive(PartialEq)]
struct A(u8);

const fn is_eq(left: &A, right: &A) -> bool {
    left.0 == right.0
}

fn main() {}
```

**Comment by mbartlett21** [comment]
What I may have to do for the moment is make a `const fn` on the struct.

I had previously implemented `const PartialEq` manually, but when I tried to use it a `const_generic` parameter, it said that they had to be derived.

**Comment by oli-obk** [comment]
yea, this will require opt-in, so schemes like `#[derive(const PartialEq)]` could be possible.

**Comment by eminence** [comment]
Now that #102049 has landed, it's possible to do const derive PartialEq in the latest nightly:

```rust
#![feature(const_cmp)]
#![feature(const_trait_impl)]
#![feature(derive_const)]

#[derive_const(PartialEq)]
struct A(u8);

const fn is_eq(left: &A, right: &A) -> bool {
    left == right
}
```
