### ISSUE TITLE
Write exactly once attribute.

### ISSUE THREAD

**Issue by cheako** [rust-lang/rust#77714]
Write exactly once attribute?
```rust
    impl From<PrivKey> for [u8; 73] {
        fn from(d: PrivKey) -> Self {
            let mut ret = [0; 32 * 2 + 9];
            ret[0] = d.history.depth;
            ret[1..5].copy_from_slice(&d.history.parent_fingerprint);
            ret[5..9].copy_from_slice(&d.history.child_number.to_be_bytes());
            ret[9..32 + 9].copy_from_slice(&d.chain_code);
            ret[32 + 9..32 * 2 + 9].copy_from_slice(&d.d.to_bytes_be());
            ret
        }
    }
```

If I'm not mistaken this is the correct way to serialize a struct into a u8 array.  However there are two things I think are important to guard against.  Overlapping writes and gaps between writes.  I believe being able to set an attribute, like `must_use` would allow this guarantee.

**Comment by jonas-schievink** [comment]
Hi! Additions or changes to the language need to go through our [RFC process](https://github.com/rust-lang/rfcs). Before an RFC is written, the feature can also be discussed in our [internals forum](https://internals.rust-lang.org/) to find other people interested in it.

Closing in favor of an RFC.
