### ISSUE TITLE
I don't understand nightly-2020-10-08

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust#77736]
If I try to compile with the latest Nightly (nightly-2020-10-08-x86_64-pc-windows-gnu), rustc acts a bit like rustup, and it tries to download another compiler somewhere. This is the strangest Nightly problem I've seen so far.

An example:
```rust
...>rustc -vV
info: syncing channel updates for 'nightly-2020-10-08-x86_64-pc-windows-gnu'
info: latest update on 2020-10-08, rust version 1.49.0-nightly (91a79fb29 2020-10-07)
info: downloading component 'cargo'
info: downloading component 'clippy'
info: downloading component 'rust-docs'
info: downloading component 'rust-mingw'
info: downloading component 'rust-std'
info: downloading component 'rustc'
info: downloading component 'rustfmt'
info: installing component 'cargo'
info: Defaulting to 500.0 MiB unpack ram
info: installing component 'clippy'
info: installing component 'rust-docs'
^C
```

**Comment by lzutao** [comment]
try to find rust-toolchain file or so.

**Comment by wesleywiser** [comment]
If you installed Rust via rustup, then `rustc` and `cargo` are links to a wrapper program that inspects the current working directory, decides which toolchain to invoke and then invokes that toolchain forwarding the arguments along. As such, this looks like some kind of issue with rustup and not rustc.

**Comment by jonas-schievink** [comment]
Yeah, this doesn't seem like a Rust bug
