### ISSUE TITLE
types_escaping_snapshot is unused

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#77740]
I'm not familiar enough with the code to know what the purpose of `types_escaping_snapshot` is, but it seems unused.

https://github.com/rust-lang/rust/blob/d2454643e137bde519786ee9e650c455d7ad6f34/compiler/rustc_infer/src/infer/type_variable.rs#L349-L397

I'd just have removed it in #77739 but there are two comments mentioning it in the file and I'm not sure what to do about those.

**Comment by JohnTitor** [comment]
#83185 removed it and #84570 tracks remaining tasks, closing.
