### ISSUE TITLE
Rust 1.47.0 snapshot binaries not working with pypa/manylinux1

### ISSUE THREAD

**Issue by n1t0** [rust-lang/rust#77760]
I have a CI automatic deployment that builds wheels for a Python package built with Rust. Everything used to work fine until the 1.47.0 stable. Now I can't get rust installed on the `pypa/manylinux1` docker image which is based on CentOS5 (cf https://github.com/pypa/manylinux)

Here is the output while trying to install rust:
```
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: latest update on 2020-10-08, rust version 1.47.0 (18bf6b4f0 2020-10-07)
info: downloading component 'cargo'
info: downloading component 'clippy'
info: downloading component 'rust-docs'
info: downloading component 'rust-std'
info: downloading component 'rustc'
info: downloading component 'rustfmt'
info: installing component 'cargo'
info: Defaulting to 500.0 MiB unpack ram
info: installing component 'clippy'
info: installing component 'rust-docs'
info: installing component 'rust-std'
info: installing component 'rustc'
info: installing component 'rustfmt'
/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc: error while loading shared libraries: /root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/../lib/librustc_driver-ff4ec557f69b94a7.so: ELF file OS ABI invalid
```

Related to #1345

**Comment by Mark-Simulacrum** [comment]
cc @cuviper 

My guess this is "linux-gnu targets now require minimum kernel 2.6.32 and glibc 2.11." and is unlikely to be fixed.

**Comment by cuviper** [comment]
Yes, this is expected. It looks like manylinux acknowledges the support state too:

> PEP 513 defined `manylinux1_x86_64` and `manylinux1_i686` platform tags and the wheels were built on Centos5. Centos5 reached End of Life (EOL) on March 31st, 2017 and thus PEP 571 was proposed.

... where [PEP 571](https://www.python.org/dev/peps/pep-0571/) defines `manylinux2010` based on CentOS 6. Even that will be done with maintenance support soon (November 30), but I expect to keep Rust support for a while yet.

**Comment by n1t0** [comment]
Got it, thank you! Guess it's time to migrate to `manylinux2010` then :smile:

**Comment by cuviper** [comment]
OK, great, hope that goes well for you!
