### ISSUE TITLE
rustdoc links to primitives hardcode /nightly

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#77775]
I tried this code on the stable channel:

```rust
pub fn f() -> bool {
    true
}
```

I expected to see this happen: Rustdoc links bool to https://doc.rust-lang.org/std/primitive.bool.html

Instead, this happened: Rustdoc links bool to https://doc.rust-lang.org/nightly/std/primitive.bool.html

This also affects intra-doc links.

### Meta

`rustdoc --version`: `rustdoc 1.47.0 (18bf6b4f0 2020-10-07)`

**Comment by MouseProducedGames** [comment]
I can confirm this happens on the crates I've checked, which are crates known to build on the standard, non-nightly compiler.

I see two problems with this default behaviour:
1) It can confuse users on whether a crate was compiled with +nightly or the standard compiler.
2) More importantly, the behaviour described in the nightly documentation might not match the behaviour of the standard library linked to by a crate.
