### ISSUE TITLE
Use CLOCK_MONOTONIC_RAW instead of CLOCK_MONOTONIC for Instant

### ISSUE THREAD

**Issue by maxbla** [rust-lang/rust#77807]
According to [man pages](https://linux.die.net/man/2/clock_gettime), `CLOCK_MONOTONIC_RAW` doesn't get adjustments from NTP or `adjtime`, whereas `CLOCK_MONOTONIC` does. This seems ideal for `Instant`. CLOCK_MONOTONIC_RAW appears to prevent slewing or jumping, closer matching user expectations about `Instant` (despite the fact that Instant is explicitly allowed to jump forward and slew)

This wasn't done earlier due to Rust's minimum supported Linux kernel version (now 2.6.32) since CLOCK_MONOTONIC_RAW was added in 2.6.28. See also #37902

I'd also like to change thread::sleep's implementation to use clock_nanosleep(`CLOCK_MONOTONIC_RAW`) from it's current `nanosleep()`. Note that

> POSIX.1 specifies that nanosleep() should measure time against the CLOCK_REALTIME clock. However, Linux measures the time using the CLOCK_MONOTONIC clock.

from [linux.die](https://linux.die.net/man/2/nanosleep). This has negative implications for the implementation of thread::sleep on BSD, which should probably use CLOCK_MONOTONIC.

Of course, CLOCK_MONATONIC_RAW is Linux-specific, so other Unix platforms will still use CLOCK_MONATONIC

**Comment by sfackler** [comment]
The kernel version is not the only reason to use CLOCK_MONOTONIC:

> We probably don't want to use CLOCK_MONOTONIC_RAW for Instant since it is not guaranteed to follow real time (e.g. 1 second on CLOCK_MONOTONIC_RAW can be shorter/longer than 1 real second). CLOCK_MONOTONIC is sped up/slowed down by the kernel as necessary to match real time (through NTP).
https://github.com/rust-lang/rust/issues/37902#issuecomment-261859649

**Comment by maxbla** [comment]
> The kernel version is not the only reason to use CLOCK_MONOTONIC: ...

Sorry, I managed to not read that part of that issue.

That said, CLOCK_MONOTONIC is not guaranteed to follow real time either. For example, if NTP is significantly different from your hardware clock, [it jumps](https://stackoverflow.com/questions/33746324/ntp-questions-slewing-versus-jumping-the-time). Also, if you don't use NTP, or adjtime, I suspect the two clocks are equivalent. But I'm not hell-bent on changing it.

I am convinced that thread::sleep should use clock_nanosleep() instead of nanosleep, as this will make the BSDs behave nicer.

**Comment by maxbla** [comment]
thread::sleep() cannot use clock_nanosleep() because clock_nanosleep is not currently exposed by libc on bsd (see https://github.com/rust-lang/libc/pull/1922). Further, FreeBSD 10 didn't even have `clock_nanosleep`.
