### ISSUE TITLE
rust doesn't recognize libressl 3.2.1

### ISSUE THREAD

**Issue by Grommish** [rust-lang/rust#77814]
Similar to the issue with https://github.com/rust-lang/rust/commit/86df2f6737d8c76d5dd577ebef1842f8657a59fb

LibreSSL is at version 3.2.1 and Rust/Cargo fails to compile because it maxes out looking for 3.2.0

Built from source, pulled from github.com/rust-lang/rust.git @ fc2daaae610b5515438b551a2f3706196a997f35

**Comment by mati865** [comment]
Try updating `openssl*` crates in Rust checkout, if it helps you can open PR with those changes.

**Comment by Grommish** [comment]
Can you direct me to the docs on how?  I see the sha256 and versions changing in Cargo.lock, but I don't know what they reference :)

**Comment by mati865** [comment]
Run `cargo update -p <crate-name>` for all `openssl*` crates in https://github.com/rust-lang/rust/blob/c38f001db5e16f1e0db47c5aed80394e9df5430a/Cargo.lock#L2160-L2201

**Comment by Grommish** [comment]
I'm building rustc from source, so I don't have a viable cargo (very long story) and I can't use rustup.  I'll see what I can do.

**Comment by mati865** [comment]
Upon closer look it's blocked on openssl-sys crate https://github.com/sfackler/rust-openssl/pull/1333

**Comment by camelid** [comment]
Just to be clear, is this an issue when compiling Rust or when compiling something else?

**Comment by Grommish** [comment]
This was an issue, yes.  Since building from c71248b70870960af9993de4f31d3cba9bbce7e8 it seems to have cleared up.  Perhaps whatever was changed in the crates?  I'm not entirely sure how that system works.  

Needless to say, I'm getting everything to build out now and am just working through cross compile issues (https://github.com/rust-lang/rust/issues/77352), but those are separate issues.

I'm going to close this as it seems to no longer be an issue.
