### ISSUE TITLE
HIR and TyCtxt disagree about the parents of decl macros

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#77828]
I tried this code:

https://github.com/rust-lang/rust/blob/8cc82ee340ed96099680ec1165cf5e192d658d0f/library/core/src/ptr/mod.rs#L1487-L1492

I expected to see this happen: `tcx.hir().parent_module(raw_const_hir_id)` and `tcx.parent(raw_const_def_id).unwrap()` are both the module `core::ptr`.

Instead, this happened: `tcx.hir().parent_module(raw_const_hir_id)` is `core` and `tcx.parent(raw_const_def_id).unwrap()` is `core::ptr`. I think `core::ptr` is correct.

### Meta

`rustc --version`: HEAD (https://github.com/rust-lang/rust/commit/8cc82ee340ed96099680ec1165cf5e192d658d0f)

**Comment by jyn514** [comment]
This is one of the problems causing https://github.com/rust-lang/rust/issues/74355.

**Comment by RalfJung** [comment]
Curious, and good catch!

Who would be a HIR expert we could ask about this?

**Comment by jyn514** [comment]
I don't know. Maybe @ecstatic-morse?

**Comment by danielhenrymantilla** [comment]
Hmm, this is still the case when the `macro` is defined inside a value-namespace-inhabiting scope:

```rust
const __: () = {
    pub macro m() {}
};
```

now yields:

```text
[src/librustdoc/visit_ast.rs:86] self.cx.tcx.parent_module(def.hir_id) = DefId(0:0 ~ core[8787])
[src/librustdoc/visit_ast.rs:87] {
    use rustc_middle::ty::DefIdTree;
    self.cx.tcx.parent(self.cx.tcx.hir().local_def_id(def.hir_id).to_def_id()).unwrap()
} = DefId(0:16466 ~ core[8787]::__)
```

Should a new issue be opened, or this one be re-opened?

**Comment by jyn514** [comment]
@danielhenrymantilla which case did https://github.com/rust-lang/rust/pull/80415 fix? Is the bug fixed for things in modules, but not in other contexts?

**Comment by danielhenrymantilla** [comment]
It looks like it: it definitely fixes it for macros inside `mod`ules, and the whole re-export ordeal works. Basically, in my PR, the only tests to fail were those involving a macro defined within a function or within a constant.

**Comment by cjgillot** [comment]
> Hmm, this is still the case when the `macro` is defined inside a value-namespace-inhabiting scope:
> 
> ```rust
> const C: () = {
>     pub macro m() {} // <- `def.hir_id()`
> };
> ```
> 
> now yields:
> 
> ```
> [src/librustdoc/visit_ast.rs:86] self.cx.tcx.parent_module(def.hir_id) = DefId(0:0 ~ core[8787])
> [src/librustdoc/visit_ast.rs:87] {
>     use rustc_middle::ty::DefIdTree;
>     self.cx.tcx.parent(self.cx.tcx.hir().local_def_id(def.hir_id).to_def_id()).unwrap()
> } = DefId(0:16466 ~ core[8787]::C)
> ```
> 
> Should a new issue be opened, or this one be re-opened?

I don't think this is an issue any more.
The second output `core[8787]::C` is not a module, so `parent_module` will not return it.
#80415 allows to compute the correct parent module (ie. not crate root) when the macro is inside a module.

**Comment by danielhenrymantilla** [comment]
Interesting, so it's intended that `.parent()` and `.parent_module()` not always agree. I think we can close this again (and maybe submit a PR clarifying that in the documentation), and I'll adapt my PR accordingly 🙂
