### ISSUE TITLE
Add error help to "cannot borrow ... as mutable more than once at a time" error that recommends assigning to a variable first

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#77834]
A newcomer to Rust may have some code that looks like this ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=b44d0e3b2a0464c662499b2d6cc2a0e1)):

```rust
struct Foo;

impl Foo {
  fn foo(&mut self, _: f32) -> i32 { todo!() }
  fn bar(&mut self) -> f32 { todo!() }
  fn baz(&mut self) {
    self.foo(self.bar());
  }
}
```

Which you would think would work, since the call to `self.foo()` happens after `self.bar()` returns, and so they have unique access to `self`. However, this desugars into something like this:

```rust
struct Foo;

impl Foo {
  fn foo(&mut self, _: f32) -> i32 { todo!() }
  fn bar(&mut self) -> f32 { todo!() }
  fn baz(&mut self) {
    Self::foo(&mut self, Self::bar(&mut self));
  }
}
```

Which, due to something else in the Rust aliasing rules that can be confusing, means that there are actually two unique borrows of `self` live at the same time, and produces this error:

```
   Compiling playground v0.0.1 (/playground)
error[E0499]: cannot borrow `*self` as mutable more than once at a time
 --> src/lib.rs:7:14
  |
7 |     self.foo(self.bar());
  |     ---- --- ^^^^ second mutable borrow occurs here
  |     |    |
  |     |    first borrow later used by call
  |     first mutable borrow occurs here
```

However, this error is confusing because the error is only visible when the code is desugared. Because of how the code is desugared, this code – which is functionally equivalent – compiles fine ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=733e234866dbee7a1714f561940039d6)):

```rust
struct Foo;

impl Foo {
  fn foo(&mut self, _: f32) -> i32 { todo!() }
  fn bar(&mut self) -> f32 { todo!() }
  fn baz(&mut self) {
    let temp = self.bar();
    self.foo(temp);
  }
}
```

Therefore I propose adding a help message to the error that suggests extracting the result into a temporary. Something like this:

```
error[E0499]: cannot borrow `*self` as mutable more than once at a time
 --> src/lib.rs:7:14
  |
7 |     self.foo(self.bar());
  |     ---- --- ^^^^ second mutable borrow occurs here
  |     |    |
  |     |    first borrow later used by call
  |     first mutable borrow occurs here
  |
  = help: try assigning `self.bar()` to a variable and then call `self.foo()` with that variable
```

Cc @jyn514

**Comment by camelid** [comment]
I would like to attempt implementing this too :)

**Comment by jyn514** [comment]
This is basically the same as https://github.com/rust-lang/rust/issues/77826 (but much more detailed, thanks :)

**Comment by camelid** [comment]
Wow, the timing is so funny :)

I thought of opening this last night, but wanted to write something more in-depth so waited until today.

**Comment by camelid** [comment]
I'm hoping to get to this at some point soon!
