### ISSUE TITLE
Feature requests： add macro_proc!

### ISSUE THREAD

**Issue by zhuxiujia** [rust-lang/rust#77842]
Using Macro_rules was painful and limited in terms of providing code performance. It seems like it can only generate code, but it can't be easily modified. I want a procedure macro that declares simple but easy to use like macro_rules!
for example:
```rust
    macro_proc! proc_macro{
        //input any rust code
        (token_stream) => {
            //you can use quote or syn to rewrite、parse this code stream
            token_stream= quote!{
               "hello".to_string()
            };
            return token_stream;
        }
    }

fn main(){
      let s =  proc_macro!(String::new());
     println!("s:{}",s); //   print  'hello'
}

```

**Comment by jonas-schievink** [comment]
Hi! Additions or changes to the language need to go through our [RFC process](https://github.com/rust-lang/rfcs). Before an RFC is written, the feature can also be discussed in our [internals forum](https://internals.rust-lang.org/) to find other people interested in it.

Closing in favor of an RFC.
