### ISSUE TITLE
-Zno-link is broken

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rust#77857]
I tried this command:

```
$ echo "fn main() {}" | rustc -Zno-link -
```

I expected to see this happen: An `.rlink` file is generated.

Instead, this happened:
```
thread 'rustc' panicked at 'cannot encode `DefIndex` with `rustc_serialize::json::Encoder`', /rustc/381b445ff5751f9f39ec672b623372dff09c276e/compiler/rustc_span/src/def_id.rs:135:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/381b445ff5751f9f39ec672b623372dff09c276e/library/std/src/panicking.rs:483
   1: std::panicking::begin_panic_fmt
             at /rustc/381b445ff5751f9f39ec672b623372dff09c276e/library/std/src/panicking.rs:437
   2: <rustc_span::def_id::DefIndex as rustc_serialize::serialize::Encodable<E>>::encode
   3: <rustc_serialize::json::Encoder as rustc_serialize::serialize::Encoder>::emit_struct
   4: <rustc_serialize::json::Encoder as rustc_serialize::serialize::Encoder>::emit_struct
   5: <rustc_serialize::json::Encoder as rustc_serialize::serialize::Encoder>::emit_seq
   6: <rustc_serialize::json::Encoder as rustc_serialize::serialize::Encoder>::emit_map
   7: <rustc_serialize::json::Encoder as rustc_serialize::serialize::Encoder>::emit_struct
   8: <rustc_serialize::json::Encoder as rustc_serialize::serialize::Encoder>::emit_struct
   9: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::link
  10: rustc_interface::queries::Linker::link
  11: rustc_span::with_source_map
  12: rustc_interface::interface::create_compiler_and_run
  13: scoped_tls::ScopedKey<T>::set
```

### Meta

`rustc --version --verbose`:
```
rustc 1.48.0-nightly (381b445ff 2020-09-29)
binary: rustc
commit-hash: 381b445ff5751f9f39ec672b623372dff09c276e
commit-date: 2020-09-29
host: x86_64-unknown-linux-gnu
release: 1.48.0-nightly
LLVM version: 11.0
```

_Originally posted by @bjorn3 in https://github.com/rust-lang/rust/pull/77795#discussion_r503330079_

cc @0dvictor (original implementer of `-Zno-link`

**Comment by 0dvictor** [comment]
PR #73851 changed the encode/decode method of [`DefId`](https://github.com/0dvictor/rust/blob/e82584a77d019bd5ee4254b5870270b1493763a6/compiler/rustc_span/src/def_id.rs#L182-L201) to call the encode/decode method of its field `pub index: DefIndex`; however, `DefIndex` is only encodable in metadata. [It panics if encoded anywhere else](https://github.com/0dvictor/rust/blob/e82584a77d019bd5ee4254b5870270b1493763a6/compiler/rustc_span/src/def_id.rs#L119-L143).

When `no-link` was implemented, the encode/decode of `DefId` was purposely crafted to avoid calling the encode/decode method of `DefIndex`. The most straightforward fix is to implement `Encodable`/`Decodable` for `DefIndex` to allow it be serialized outside of metadata.

After that, may be now it is the time to re-think the way we store data in the `rlink` file.

What do you think @bjorn3 ?

**Comment by bjorn3** [comment]
I think `DefId` should completely be avoided in the input of the linker function. One of the uses if `NativeLib` in it's `foreign_module` field. This field doesn't seem to be used by the linking code.

**Comment by 0dvictor** [comment]
Good suggestion, let me look into it.

**Comment by bjorn3** [comment]
@0dvictor are you still working on this?

**Comment by 0dvictor** [comment]
Thank you for reminding and apologize for the delay. I did create a prototype but haven't got a chance polish it yet. I'll create the PR this week.

**Comment by 0dvictor** [comment]
Sorry again about the delay. I've created PR #80187, which fixes this issue.
