### ISSUE TITLE
the trait `core::default::Default` is not implemented for `*mut core::ffi::c_void`

### ISSUE THREAD

**Issue by lygstate** [rust-lang/rust#77883]
```
    |
173 |     pub iov_base: *mut c_void,
    |     ^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `core::default::Default` is not implemented for `*mut core::ffi::c_void`
    |
```

Suggest, add Default for c_void*

```
impl Default for *c_void {
    fn default() -> Self {  0 as *c_void }
}

impl Default for *mut c_void {
    fn default() -> Self {  0 as *mut c_void }
}

```

**Comment by lzutao** [comment]
playground: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=f67487318583660df41296a495c32f9a

I don't know if it is useful to implement `Default` trait for pointers.

**Comment by lygstate** [comment]
> playground: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=f67487318583660df41296a495c32f9a
> 
> I don't know if it is useful to implement `Default` trait for pointers.

Not implement it is for safety concern?

**Comment by ollie27** [comment]
This has been requested before: #43722

**Comment by lygstate** [comment]
gocha, close it
