### ISSUE TITLE
const initializer is not considered a "defining use" for type_alias_impl_trait

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/rust#77898]
I tried [this code](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=5c5e46192c11b3133fccc109885d9d3a):

```rust
#![feature(type_alias_impl_trait)]

pub type Foo = impl std::fmt::Debug;
pub const FOO: Foo = 5usize;
```

I expected to see this happen: successful compilation

Instead, this happened:

```
error[E0308]: mismatched types
 --> src/lib.rs:4:22
  |
3 | pub type Foo = impl std::fmt::Debug;
  |                -------------------- the expected opaque type
4 | pub const FOO: Foo = 5usize;
  |                      ^^^^^^ expected opaque type, found `usize`
  |
  = note: expected opaque type `impl Debug`
                    found type `usize`

error: could not find defining uses
 --> src/lib.rs:3:16
  |
3 | pub type Foo = impl std::fmt::Debug;
  |                ^^^^^^^^^^^^^^^^^^^^
```

### Meta
`1.49.0-nightly (2020-10-12 8dae8cdcc8fa879cea6a)`

**Comment by jackh726** [comment]
This works now with `min_type_alias_impl_trait`, but also requires `impl_trait_in_bindings`

**Comment by jplatte** [comment]
`min_type_alias_impl_trait` has been removed in #87501, what does that mean for this issue?

**Comment by jackh726** [comment]
This is something we probably want `type_alias_impl_trait` to do, so this can stay open.

Also, not sure why I said this requires `impl_trait_in_bindings`...

**Comment by oli-obk** [comment]
This has been fixed in https://github.com/rust-lang/rust/pull/94081 which also has tests that pass with it
