### ISSUE TITLE
Rustdoc closes sidebar when window is resized

### ISSUE THREAD

**Issue by Koxiaet** [rust-lang/rust#77942]
On a small viewport where the sidebar is hidden by default, if the sidebar is opened and then the window is resized the sidebar closes.

This makes rustdoc pages practically unusable on Android Firefox as scrolling down hides the top bar and resizes the window.

**Comment by GuillaumeGomez** [comment]
I don't see how you can resize a browser on a phone. Do you have a video of this behavior by any chance? I have to admit that I'm a bit lost here...

**Comment by lzutao** [comment]
Do they mean zoom instead ?

**Comment by Koxiaet** [comment]
Here's an image of the problem:

![rustdoc](https://user-images.githubusercontent.com/38139193/96143506-0e094200-0efb-11eb-8c29-ce7fcf46a95a.gif)
