### ISSUE TITLE
No "multiple applicable items in scope" error when calling `fmt` inside a `Display` or `Debug` impl

### ISSUE THREAD

**Issue by benediktwerner** [rust-lang/rust#77966]
**Edit: This description is incorrect. See the discussion below for the actual bug.**

```rust
struct S(Box<dyn std::error::Error>);

impl std::fmt::Display for S {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.0.fmt(f)
    }
}
```

I would expect this code to cause a "multiple applicable items in scope" compiler error since `self.0` in the impl has two `fmt` methods, one from `Debug` and one from `Display` (both required for `Error`). However, this code compiles perfectly fine and selects `Display::fmt`. When implementing `Debug` the `Debug::fmt` method is chosen instead, as can be seen in [this playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=50692c04a71a6958b701a6e68e5b1b32).

This behavior does not occur when using generics instead of a trait object, when the unused trait is brought into scope by a `use`-declaration, or when trying to replicate the same behavior with custom traits. So the following all trigger the "multiple applicable items in scope" error:

```rust
// No trait objects
struct S<T>(T);

impl<T: std::error::Error> std::fmt::Display for S<T> {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.0.fmt(f)
    }
}
```
```rust
// Bring Debug into scope
use std::fmt::Debug;

struct S(Box<dyn std::error::Error>);

impl Display for S {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.0.fmt(f)
    }
}
```
```rust
// Same setup but with custom traits
trait A { fn f(&self); }
trait B { fn f(&self); }

trait C: A + B {}

struct S(Box<dyn C>);

impl A for S {
    fn f(&self) {
        self.0.f();
    }
}
```

I also wasn't able to replicate this with custom traits by placing the traits in another crate or in separate modules, no matter if I used complete paths or `use`-declarations. Adding a `&mut Formatter<'_>` parameter or a return type to the methods also doesn't make a difference.

However, the error is again absent when replacing `Error` with a custom trait depending on `Display` and another trait with the same method or when using other std-lib traits like `Read`:

```rust
trait LikeDisplay { fn fmt(&self, fmt: &mut std::fmt::Formatter<'_>) -> std::fmt::Result; }

trait T: LikeDisplay + std::fmt::Display {}

struct S(Box<dyn T>);

impl std::fmt::Display for S {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        self.0.fmt(f)
    }
}
```
```rust
trait LikeRead { fn read(&mut self, buf: &mut [u8]) -> std::io::Result<usize>; }

trait T: LikeRead + std::io::Read {}

struct S(Box<dyn T>);

impl std::io::Read for S {
    fn read(&mut self, buf: &mut [u8]) -> std::io::Result<usize> {
        self.0.read(buf)
    }
}
```

However even in this case, only the implementation for `Display` or `Read` is ok. When implementing `LikeDisplay` or `LikeRead` instead it produces the error again.

The behavior also seems to be the same on nightly, 1.46, and 1.47.

It's not quite clear to me what exactly causes the issue but at least it only seems to happen when std-lib types are involved.

**Comment by GoldsteinE** [comment]
It's possible to trigger this behaviour for custom traits:
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=09e5fc208def46725fcdf068145bae40

I'm not quite sure this is a bug: rustc seems to explicitly add current trait to the scope for method resolution:
https://github.com/rust-lang/rust/blob/4253153db205251f72ea4493687a31e04a2a8ca0/compiler/rustc_resolve/src/lib.rs#L1489-L1494

**Comment by GoldsteinE** [comment]
If anything, "multiple applicable items in scope" error when there's no explicit impl for Box seems to be a bug: there's clearly no applicable items in scope (possibly save for the current trait).

**Comment by benediktwerner** [comment]
Yes, you are right, there are some very confusing mechanisms at play here and I clearly didn't understand trait scopes as well as I thought (although to be fair there is also very little information on this topic and as far as I can tell none of these things are explained in the reference).

I just went through all my examples again and although it took me a while I now figured out why all of them are correct:

1. Initial example: Only `Display` is in scope since we are in a `Display` impl so there is no conflict.
2. "No trait objects" example: The trait bound `T: std::error::Error` brings `Error` and all super-traits (i.e. both `Display` and `Debug`) "into scope" but only for objects of type `T`. So it makes sense that there is a conflict.
3. "Bring Debug into scope" example: Obviously both traits are in scope so there is a conflict.
4. "Same setup but with custom traits" example: Same thing, both are obviously in scope so there is an obvious conflict.

In my last two examples, there is no error, even though both `LikeDisplay` and `Display` are in scope. The reason for that is because `Box<T>` has a generic `Display`-impl for `T: Display`. There is no such impl for `LikeDisplay` so there is no conflict. Without the impl the box would get auto-derefed and the resulting trait object reference implements both traits which would result in a conflict but since the box itself already and only implements one trait this never happens.

And lastly, if we instead implement `LikeDisplay` we *do* get the error even though only `LikeDisplay` should be in scope, meaning there shouldn't actually be a conflict. The reason for this is that we now *do* auto-deref the box since there is no generic `LikeDisplay`-impl for `Box` and on trait objects, the trait and all its super-traits are again automatically "in scope" just for the trait object.

The last two things actually also both apply to the first example. On an `Error` trait object there should be a conflict because both traits are automatically in scope on the object but because we are working on a `Box` and only one trait is actually in scope and also implemented on that `Box` there is no conflict.

**Comment by GoldsteinE** [comment]
So bringing supertraits of trait objects into scope is a desired behaviour? If so, error message about "multiple applicable items in scope" should be fixed. I'm willing to do that, but will probably need some guidance since it's my first contribution to the rustc.

**Comment by benediktwerner** [comment]
It's honestly hard to say if that is desired behavior since as I said this stuff is not yet mentioned anywhere in the reference as far as I can tell but I think it's probably intended. I think you most likely won't get a good response or much guidance here though. It's probably better to ask somewhere more visible (maybe on zulip, internals.rust-lang.org, the official Discord, or something like that).

Although I think changing the error message probably isn't too hard. You probably can find what you need if you search for the error text.
