### ISSUE TITLE
move `download-ci-llvm` logic from bootstrap.py to rustbuild

### ISSUE THREAD

**Issue by alarsyo** [rust-lang/rust#77977]
As discussed a bit in the comments of #77756 , it'd be great if the logic handling LLVM setup / download was integrated with rustbuild directly. The main blocker being that rustbuild would need to depend on an http client library.

Currently, the python script does system calls [to `curl` or to Powershell's `WebClient`](https://github.com/rust-lang/rust/blob/7f587168102498a488abf608a86c7fdfa62fb7bb/src/bootstrap/bootstrap.py#L81-L98) depending on the platform.

**Comment by est31** [comment]
rustbuild doesn't *have* to depend on a http client library, it can just shell out to curl or WebClient as well. I think that's perfectly fine for anything for which http downloads are not the main purpose.

**Comment by Mark-Simulacrum** [comment]
It looks like Python is already doing that -- interesting -- in that case it definitely seems fine to do so. It would be great if we could avoid duplicating the curl invocations but I wouldn't bend over backwards to do so.

**Comment by jyn514** [comment]
Done in https://github.com/rust-lang/rust/pull/95170.
