### ISSUE TITLE
Type mismatch when using constant with type_alias_impl_trait

### ISSUE THREAD

**Issue by joshlf** [rust-lang/rust#77989]
I tried this code ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=80748165b06638dee0a936f2199625a5)):

```rust
#![feature(type_alias_impl_trait)]

pub type IntoUnit = impl Into<()>;

pub const _: IntoUnit = ();

pub fn infer() -> IntoUnit {
    ()
}
```

I expected to see this happen: Successful compilation

Instead, this happened: While `infer` compiled successfully, the anonymous constant did not:

```text
error[E0308]: mismatched types
 --> src/lib.rs:5:25
  |
3 | pub type IntoUnit = impl Into<()>;
  |                     ------------- the expected opaque type
4 | 
5 | pub const _: IntoUnit = ();
  |                         ^^ expected opaque type, found `()`
  |
  = note: expected opaque type `impl Into<()>`
               found unit type `()`
```

### Meta

Rust playground version: 1.49.0-nightly (2020-10-14 e160e5cb80652bc2afe7)

cc @jswrenn

**Comment by jonas-schievink** [comment]
cc https://github.com/rust-lang/rust/issues/77898, a similar issue

**Comment by jackh726** [comment]
This actually works now, even with `min_type_alias_impl_trait` (though it shouldn't)

**Comment by nikomatsakis** [comment]
We should decide whether `const X: Foo` is a "defining use" for TAIT. I think my rule is roughly "if `impl Trait` can be used there to mean "existential type", it is a defining use". Presently this [does not include](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=eea4f69a1e416659aadf931e73c18a3c) const, so this should not be accepted by `min_type_alias_impl_trait`. 

However, I would eventually expect this code to compile, yes.

**Comment by oli-obk** [comment]
This works now, and I expect this to keep working, as there's no implementation reason to forbid it and no language reason that I know of. Theoretically all functions could just be constants that return an `impl Fn()` type 😆

**Comment by nikomatsakis** [comment]
Huzzah! @oli-obk is awesome. Closing.
