### ISSUE TITLE
For a better extra::future

### ISSUE THREAD

**Issue by NawfelBengherbia** [rust-lang/rust#7798]
Helo, I am new to Rust and i don't have time to touch it now. But i want to contribute to the project even with ideas.
1) Extend `extra::future` with helpful methods
2) Extend `extra::timer` with helpful methods

1) The future abstraction is very similar to "Promise" if not the same. I like if someone implements promise features for futures like the following methods/functions witch allow one them to compose better.

```rust
fn when(a: Future<A>, b: Future<B>) -> Future<(A, B)>
fn join(futures_array: [Future<A>]) -> Future<[A]>
```

method:

```rust
fn then(self: Future<A>, &fn (A) -> Future<B>) -> Future<B>
```

2) in `extra::timer` The folowing function is useful

```rust
fn wait(time: int) -> Future<()>
```

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#842
