### ISSUE TITLE
path.ends_with can't work exactly. rust version 1.47 in windows

### ISSUE THREAD

**Issue by flyinmind** [rust-lang/rust#78012]
I tried following code， it can't work,  returns false :

    let path = Path::new("/etc/resolv.conf");
    println!("path:{:?}", &path);
    if path.ends_with(".conf") {
        println!("aa ok");
    } else {
        println!("aa nok");
    }
    let s = path.to_str().unwrap();
    if s.ends_with(".conf") {
        println!("ok");
    } else {
        println!("nok");
    }

print following contents:
path:"/etc/resolv.conf"
**aa nok**
ok

Thanks!

**Comment by jonas-schievink** [comment]
`Path::ends_with` checks *path components*, not substrings, so it will only return `true` if the argument is the last segment in the path. In your example, the last component is `resolv.conf`, not `.conf`.

Therefore, closing as expected behavior.

**Comment by flyinmind** [comment]
ok， i see now，thanks a lot.
