### ISSUE TITLE
Rustc panic at 'Box<Any>'

### ISSUE THREAD

**Issue by lotabout** [rust-lang/rust#78034]
Here's the playground to reproduce the issue:

Edit: provide a more compact minimal example
- compact link: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=40e467ee075d45b61e0b3f0d920c02c5
- orig link: https://play.rust-lang.org/?version=stable&mode=debug&edition=2015&gist=1b41b43d417748111c5bd267b932fb8b

And here is the code:

```rust
pub struct DefaultSkimSelector {
    first_n: usize,
}

impl DefaultSkimSelector {
    fn should_select(&self, index: usize) -> bool {
        if self.first_n > index {
            true
        } else {
            false
        }
    }
}

pub fn main() {
    let selector = DefaultSkimSelector { first_n: 10 };
    assert!(selector.should_select(0), true);    // <-- this line works
    assert!(selector.should_select(10), false);  // <-- this line panic
}
```

It panics when run while the expected behavior is finishing correctly.

### Meta

This issue happens on stable(1.46.0) and nightly(1.49.0-nightly 2020-10-15 dd7fc54ebdca419ad9d3). Here's the information on my local machine, but can also be reproduced on the playground.

```
$ rustc --version --verbose
rustc 1.46.0 (04488afe3 2020-08-24)
binary: rustc
commit-hash: 04488afe34512aa4c33566eb16d8c912a3ae04f9
commit-date: 2020-08-24
host: x86_64-apple-darwin
release: 1.46.0
LLVM version: 10.0
```

Backtrace:
```
   Compiling playground v0.0.1 (/playground)
    Finished dev [unoptimized + debuginfo] target(s) in 0.85s
     Running `target/debug/playground`
thread 'main' panicked at 'Box<Any>', src/main.rs:18:5
stack backtrace:
   0: std::panicking::begin_panic
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:497
   1: playground::main
             at ./src/main.rs:18
   2: core::ops::function::FnOnce::call_once
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/ops/function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by camelid** [comment]
This does not appear to be a regression based on testing with Godbolt.

**Comment by SNCPlay42** [comment]
```rust
assert!(selector.should_select(10), false);  // <-- this line panic
```

`assert!` is not `assert_eq!`. This is effectively `panic!(false)`, which is [apparently](https://doc.rust-lang.org/stable/std/macro.panic.html) valid.

**Comment by SNCPlay42** [comment]
At any rate this is the code panicking at run time, not a panic in rustc.

@rustbot modify labels: -I-ICE

**Comment by lzutao** [comment]
This doesn't seems like a compiler bug
@rustbot modify labels: -C-bug -E-needs-mcve

**Comment by lotabout** [comment]
@SNCPlay42 My bad. Gonna close the issue. Was misled by the error message.

**Comment by camelid** [comment]
Oops, sorry about the incorrect labels; I guess I scanned the issue too fast.
