### ISSUE TITLE
Document the "as _" (as-underscore) syntax for value coercion / type casting

### ISSUE THREAD

**Issue by cher-nov** [rust-lang/rust#78042]
I'm pretty sorry if I've somehow missed that somewhere in the official docs.
But that really stumbled me for a hour just now.

This syntax is mentioned there in the opening post, for example:
https://github.com/rust-lang/rust/issues/45480

**Comment by jonas-schievink** [comment]
`as` is documented here: https://doc.rust-lang.org/std/keyword.as.html

It could explicitly mention that the destination type can be an `_` placeholder.

**Comment by cher-nov** [comment]
> It could explicitly mention that the destination type can be an `_` placeholder.

I think, it would be also nice to clarify similarities and differences between `as` / `From::` and `as _` / `.into()`.

**Comment by poliorcetics** [comment]
@rustbot claim

> as / From:: and as _ / .into().

I don't think I understand what you want to say with this part. `From` and `Into` are (to me) two halves of the same coin, no ?

**Comment by cher-nov** [comment]
> I don't think I understand what you want to say with this part. `From` and `Into` are (to me) two halves of the same coin, no ?

They are. But `From::` requires type to be explicitly specified, while `.into()` inferences it, don't they?
Which is like specifying type in `as T` and omitting it in `as _`.
