### ISSUE TITLE
Trait are not implemented for Trait object with marker trait

### ISSUE THREAD

**Issue by Piroro-hs** [rust-lang/rust#78054]
I tried this code:

```rust
trait Foo {}
trait Bar {
    fn bar(&self) {}
}

struct A {}

impl Foo for A {}
impl Bar for &dyn Foo {}

fn func<T>(bar: T) where T: Bar {}

fn main() {
    let a = A {};
    // let a_as_foo = &a as &dyn Foo;
    let a_as_foo = &a as &(dyn Foo + Send);
    a_as_foo.bar(); // E0599
    func(a_as_foo); // E0277
}
```

I expected to see this happen: Bar is implemented for a_as_foo by `impl Bar for &dyn Foo {}` and code compiles.

Instead, this happened: It doesn't. Are `&dyn Foo` and `&dyn Foo + Send` considered as completely different type?

**Comment by jonas-schievink** [comment]
> Are `&dyn Foo` and `&dyn Foo + Send` considered as completely different type?

Yes. This is working as intended.
