### ISSUE TITLE
`rustc_mir_build::build::unpack!` macro does not appear in docs

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#78090]
The `rustc_mir_build::build::unpack!` macro does not appear in the online rustc API docs. I tried searching for it and also typing in different URLs.

Yet the `rustc_apfloat::unpack!` macro _does_ appear in the API docs. I'm not sure why one is showing up and one is not.

Not sure if this is a rustdoc bug.

**Comment by nagisa** [comment]
The `rustc_mir_build::build::unpack!` is private, `rustc_apfloat` one is exported. I believe we don't build our documentation with private items documented, so that'd be working as intended.

Closing, but feel free to reopen if you feel its a bug still.

**Comment by camelid** [comment]
Ah, I was wondering if that could be it, but I missed the `#[macro_export]` since rustdoc scrolls so the top of the page is the top of the declaration, not the attributes.

**Comment by camelid** [comment]
Hmm, that's weird: other items that _are_ private show up in the documentation. Do non-exported `macro_rules!` not count as ordinary "private items"?

**Comment by camelid** [comment]
E.g. [`rustc_mir_build::build::mir_build`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_mir_build/build/fn.mir_build.html), which is private.

**Comment by camelid** [comment]
Actually it looks we do document private items for the compiler:

https://github.com/rust-lang/rust/blob/44ae0b8b2def2a26b82e0a93f8c8c2c523cc3643/src/bootstrap/doc.rs#L525-L530

**Comment by camelid** [comment]
This occurs in non-compiler code too, so I opened a rustdoc issue: #78091.
