### ISSUE TITLE
A problem with inline_const feature in ranges

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust#78108]
As soon as I've seen the new inline_const feature, I've tried to find some use cases for it in my code, and I did find only very few of them, unfortunately, and one of the two uses cases could be reduced to this:

```rust
#![allow(incomplete_features)]
#![feature(inline_const)]
fn main() {
    const N: u32 = 10;
    let x: u32 = 3;

    match x {
        1 .. const { N - 1 } => {},
        _ => {},
    }
}
```
That gives errors:
```rust
error: expected one of `=>`, `if`, or `|`, found keyword `const`
 --> ...\temp.rs:9:14
  |
9 |         1 .. const { N - 1 } => {},
  |              ^^^^^ expected one of `=>`, `if`, or `|`

error[E0658]: half-open range patterns are unstable
 --> ...\temp.rs:9:9
  |
9 |         1 .. const { N - 1 } => {},
  |         ^^^^
  |
  = note: see issue #67264 <https://github.com/rust-lang/rust/issues/67264> for more information
  = help: add `#![feature(half_open_range_patterns)]` to the crate attributes to enable
```

So I am not sure if this is a bug report or an enhancement request.

**Comment by camelid** [comment]
Note that this _does_ work in expressions ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=236dfeb44259eba38eac59690d6f24f3)):

```rust
#![allow(incomplete_features)]
#![feature(inline_const)]
fn main() {
    const N: u32 = 10;

    let range = 1 .. const { N - 1 };
    println!("{:?}", range);
}
```

**Comment by petrochenkov** [comment]
Support for ranges in patterns (`1 .. const { 2 }` or `const { 1 } .. 2`) needs to be added separately, to `fn parse_pat_range_end` and `fn parse_pat_with_range_pat` respectively.
