### ISSUE TITLE
Feature request: Custom destructuring

### ISSUE THREAD

**Issue by LoganDark** [rust-lang/rust#78154]
Let's say I have this struct, `Vec2`:

```rust
#[derive(Copy, Clone, PartialEq, Debug)]
pub struct Vec2 {
	x: f32,
	y: f32
}
```

And I also a tuple containing two `Vec2`s:

```rust
let t: (Vec2, Vec2) = ...;
```

Right now, I have to do this to destructure it, which is really long and cumbersome to type:

```rust
let (Vec2 { x: mut x1, y: mut y1 }, Vec2 { x: mut x2, y: mut y2 }) = t;
```

I thought it would be a lot nicer if I could do this instead:

```rust
let ((mut x1, mut y1), (mut x2, mut y2)) = t;
```

But after asking for help in the Rust Discord, it looks like this is impossible!

Should support for custom destructuring like this be added? Is it even possible?

It could work like this:

```rust
impl Destructure<(f32, f32)> for Vec2 {
	fn destructure(self) -> (f32, f32) {
		(self.x, self.y)
	}
}

impl DestructureRef<(&f32, &f32)> for Vec2 {
	fn destructure_ref(&self) -> (&f32, &f32) {
		(self.x, self.y)
	}
}

impl DestructureMut<(&mut f32, &mut f32)> for Vec2 {
	fn destructure_mut(&mut self) -> (&mut f32, &mut f32) {
		(self.x, self.y)
	}
}
```

Or it could use the existing `Into`/`AsRef`/`AsMut` traits instead, thoughts?

**Comment by jonas-schievink** [comment]
Hi! Additions or changes to the language need to go through our [RFC process](https://github.com/rust-lang/rfcs). Before an RFC is written, the feature can also be discussed in our [internals forum](https://internals.rust-lang.org/) to find other people interested in it.

Closing in favor of an RFC.

**Comment by LoganDark** [comment]
This is meant to be that discussion. Other feature requests are being discussed on GitHub, like this one, which has not been closed for not being on the forum: https://github.com/rust-lang/rust/issues/78064

**Comment by Lonami** [comment]
It depends on the magnitude of the feature request, and the team decides what requests are too large to be discussed here. #78161 should help future users find IRLO for largeish requests.

**Comment by LoganDark** [comment]
So that is the issue then, this request is too large? Could you please elaborate more on why?

**Comment by jonas-schievink** [comment]
> Why can't the discussion be here?

The RFCs repo and internals forum were deliberately created to house design work and discussion. This issue tracker is meant mostly for bugs.

> Other feature requests are already being discussed on GitHub, like #78064, which is only two days old (and also does not have an RFC yet).

We sometimes don't consistently apply rules to the issue tracker, because they aren't written down anywhere and people often miss things (since it is almost impossible to keep up with every issue that is filed here).

**Comment by LoganDark** [comment]
> We sometimes don't consistently apply rules to the issue tracker, because they aren't written down anywhere and people often miss things (since it is almost impossible to keep up with every issue that is filed here).

That sounds a little unfair, then. Fine, I will go post a duplicate on the forum. Eventually.

**Comment by Lonami** [comment]
> this request is too large? Could you please elaborate more on why?

I have no authority here, it's just how I see things normally work :P but probably the main reason is, as jonas pointed out, that it's hard to keep up and it's all subjective. In any case don't take this personally, [a quick search for the text above](https://github.com/rust-lang/rust/issues?q=is%3Aissue+Additions+or+changes+to+the+language+need+to+go+through+our+RFC+process) reveals more issues closed with the same reasoning.

**Comment by LoganDark** [comment]
A few of those issues were obviously joke requests (like "remove semicolons" begging Rust to be more like python). Most likely the comment was used there to close the issue more professionally than "not in a million years". I don't see how my issue fits into that category, but in any case there's no point in arguing about it here. I'll move to the forum.
