### ISSUE TITLE
Syntax error when using multiple `cfg` attributes

### ISSUE THREAD

**Issue by lamafab** [rust-lang/rust#78175]
I encountered a weird behavior when using `cfg(test)` and `cfg(not(test))`.

I tried this code:

```rust
fn does_not_work() -> usize {
    #[cfg(not(test))]
    0

    #[cfg(test)]
    1
}
```

Results in:

```bash
   Compiling playground v0.0.1 (/playground)
error: expected one of `.`, `;`, `?`, `}`, or an operator, found `#`
 --> src/lib.rs:6:5
  |
4 |     0
  |      - expected one of `.`, `;`, `?`, `}`, or an operator
5 | 
6 |     #[cfg(test)]
  |     ^ unexpected token

error: aborting due to previous error

error: could not compile `playground`.

To learn more, run the command again with --verbose.
```

**Workaround**

```rust
fn does_work() -> usize {
    #[cfg(not(test))]
    return 0; // `return` including a semicolon

    #[cfg(test)]
    1
}
```

### Meta

Rust stable version 1.47.0

Playground: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=f7f7eb30327396c209b0f358b1a3072b

**Comment by lzutao** [comment]
This is not a bug: @rustbot modify labels: -C-bug

**Comment by lamafab** [comment]
@lzutao Would you mind clarifying?

**Comment by lzutao** [comment]
Disclaimer: I'm not the best person to explain this.

Rust doesn't have whitespace sensitive syntax. This means that your example can be written as
```rust
#[cfg(not(test))] 0 #[cfg(test)] 1
```
Which mean that `#[cfg(not(test))]` could control not only `0` but also  `0 #[cfg(test)] 1`.
`0 #[cfg(test)] 1` is not a valid syntax.

**Comment by LeSeulArtichaut** [comment]
The diagnostics could probably be improved however
