### ISSUE TITLE
Nonsensical error when trying to use associated const in array

### ISSUE THREAD

**Issue by Aaron1011** [rust-lang/rust#78189]
The following code:

```rust
trait ConstN {
    const N: usize;
}

trait Array: ConstN {
    fn array() -> [(); Self::N];
}
fn main() {}
```

produces the following error:

```
error[E0599]: no associated item named `N` found for type parameter `Self` in the current scope
 --> src/main.rs:6:30
  |
6 |     fn array() -> [(); Self::N];
  |                              ^ associated item not found in `Self`
  |
  = help: items from traits can only be used if the type parameter is bounded by the trait
help: the following trait defines an item `N`, perhaps you need to add another supertrait for it:
  |
5 | trait Array: ConstN + ConstN {
  |                     ^^^^^^^^

error: aborting due to previous error
```

The error claims that `Self::N` doesn't exist, but then suggests adding a duplicate bound for the trait that defines it.

With `#![feature(const_generics)]`, we get a more meaningful error:

```
error: constant expression depends on a generic parameter
 --> src/main.rs:8:19
  |
8 |     fn array() -> [(); Self::N];
  |                   ^^^^^^^^^^^^^
  |
  = note: this may fail depending on what value the parameter takes
```

We should try to emit this diagnostic (or something like it) regardless of whether or not `#![feature(const_generics)]` is enabled.

**Comment by varkor** [comment]
Hopefully `min_const_generics` will be stabilised in the not-too-distant future, so it's probably reasonable to leave this for now.

**Comment by estebank** [comment]
I'm pretty sure there was an existing ticket for this 😅 but yeah, unless anyone has spare cycles it will become moot once min_const_generics is stabilized. Do not close the ticket though.

**Comment by Aaron1011** [comment]
On Nightly, this now produces the following output:

```
error: generic parameters may not be used in const operations
 --> src/main.rs:8:24
  |
8 |     fn array() -> [(); Self::N];
  |                        ^^^^^^^ cannot perform const operation using `Self`
  |
  = note: type parameters may not be used in const expressions
  = help: use `#![feature(const_generics)]` and `#![feature(const_evaluatable_checked)]` to allow generic const expressions
```

So, this issue just needs a test.

**Comment by varkor** [comment]
There are already existing tests for this situation, so I think it's safe to just close.
