### ISSUE TITLE
rust missing features like powerful text formatting

### ISSUE THREAD

**Issue by anshul-birajdar** [rust-lang/rust#78215]
rust doesn't have printf or scanf function so we can specify the %4d or %5.4f (to format the text) and do like:
```c
int main(void){
char c='d';
printf("%d",c);
}
```
which would print the char as the ASCII value
and allow all sorts of text manipulation

**Comment by workingjubilee** [comment]
```rust
fn main() {
    let ch = 'd';
    println!("{}", ch as u32);
}
```
Try it on the [Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=b46bd65449900f905e033c5eaba44aa1).

**Comment by anshul-birajdar** [comment]
but
 ```c
printf("%3.4f");
```
is not there

so lets take a classic example from the book "THE C PROGRAMMING LANGUAGE by K&R"

```c
 printf("%3.1f\t%6.1f\n", fahr, celsius);
```
This is printed in the first chapter.
What it does it prints 3 digits of fahr (one after the decimal) then it prints a \t tab charachter then ....

**Comment by estebank** [comment]
You can also [try out C/Python style format strings](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=d524bb9d26904622ddf63e4dda83e2b2) and rustc will show you the Rust way to represent the same formatting string.

You have to use `println!("format str", args);` in Rust.

I would advice you read the freely available [Rust Book](https://doc.rust-lang.org/book/) and visit https://users.rust-lang.org/ for support. This issue tracker is for bug reporting and feature requests.
