### ISSUE TITLE
Discussion about when to quote word with backtick

### ISSUE THREAD

**Issue by tesuji** [rust-lang/rust#78230]
https://github.com/rust-lang/rust/issues/78230#issuecomment-714463196

-- -

*Original post*

The "struct" word doesn't need to be quote by backtick, let's remove it.

https://github.com/rust-lang/rust/blob/6b9fbf212a06944ff23325d2d63215805dc3c6c3/library/core/src/iter/adapters/mod.rs#L2226
![image](https://user-images.githubusercontent.com/15225902/96866350-63ae9300-1495-11eb-96df-010ebb77f5c1.png)

@rustbot modify labels: C-discussion

**Comment by GuillaumeGomez** [comment]
Why should it be removed here?

**Comment by lzutao** [comment]
Backtick could be used to mark code snippet.
But here struct alone is a noun, not a code snippet to me.

**Comment by GuillaumeGomez** [comment]
It's a keyword, not a noun. Therefore, the backticks seem in the right place.

**Comment by lzutao** [comment]
It's [both](https://en.wiktionary.org/wiki/struct): a noun and a keyword. However, if we insist on using backtick around "struct",
which makes it a keyword in the cited doc context,
we might want to link to documentation of keyword struct.

**Comment by GuillaumeGomez** [comment]
Well, no. "struct" is a shorthand for "structure". In here, this is explicitly the keyword form which is being used. Also, we can link to the struct documentation, but is it worth it? (open question it is!)

**Comment by lzutao** [comment]
From doc context, "struct" is talk about `Skip` - which is a name/type/nount - not about keyword "struct" itself.

**Comment by GuillaumeGomez** [comment]
Still remains a reference to "structure" which a noun through the keyword "struct". So either you change the text from "struct" to "structure", or let it as is. :)

**Comment by lzutao** [comment]
There are some more places in std not use quote "struct" by a backtick pair,
for example <https://doc.rust-lang.org/nightly/std/slice/struct.IterMut.html>.
If we insist on quote "struct" as code snippet, there should be a guideline 
for this documentation type.

I'd like inputs from other docs people: @jyn514 .

**Comment by GuillaumeGomez** [comment]
If the guideline lacks this information, then it should be added indeed. Let's see what @jyn514 thinks about it.

**Comment by jyn514** [comment]
It seems like too much work to change this either way.
```
~/rustc/library $ rg '`struct`' | wc -l
110
~/rustc/library $ rg '^struct|^[`]struct' | wc -l
255
```
Is this really worth arguing about? I don't think it has a great impact on the readability of the docs either way.

**Comment by lzutao** [comment]
We're all agree this is bike-shredding. However, if there is no guideline
then the same question/argument will be bring up all over again.

**Comment by varkor** [comment]
I agree that "struct" is a noun distinct from "structure", though "structure" is obviously the etymology. A struct in Rust is an algebraic data type. Putting it in backticks is no more correct, and is less readable.

**Comment by steveklabnik** [comment]
The canonical resource for this is https://github.com/rust-lang/rfcs/blob/master/text/1574-more-api-documentation-conventions.md

It says:

> Use graves (`) to denote a code fragment within a sentence.

and

> When talking about a type, use its full name. In other words, if the type is generic, say Option<T>, not Option. An exception to this is bounds. Write Cow<'a, B> rather than Cow<'a, B> where B: 'a + ToOwned + ?Sized.
> 
> Another possibility is to write in lower case using a more generic term. In other words, ‘string’ can refer to a String or an &str, and ‘an option’ can be ‘an Option<T>’.

So really, this is about two competing interpretations of these guidelines: is "struct" more similar to "string" or "an option", or to the literal code fragment? I think you can see it either way, which is why it's done in either way. I don't personally have a really strong opinion here.

**Comment by Dylan-DPC** [comment]
Closing this as there isn't much reason to have this change
