### ISSUE TITLE
Incorrectly typed `for` expression when into_iter expression diverges.

### ISSUE THREAD

**Issue by adlerd** [rust-lang/rust#78240]
I tried this code:

```rust
fn test_diverging_into_iter() -> ! {
    for _ in { panic!(); 0.. } {}
}
```

I expected to see this happen: This should compile successfully. Moreover, the `for` expression should be assignable to any type and this should work for any function return type. In short, the `for` expression should be typed at `!` not `()`. As a general rule, `for _ in b { c }` should be typed like `{ b; () }`, not `()`.

Instead, this happened:
```
error[E0308]: mismatched types
 --> src/lib.rs:2:5
  |
1 | fn test_iter_position() -> ! {
  |                            - expected `!` because of return type
2 |     for _ in { panic!(); 0.. } {}
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `!`, found `()`
  |
  = note:   expected type `!`
          found unit type `()`
```

Version: playground, nightly 2020-10-18

See also #77156

**Comment by adlerd** [comment]
Also, for the hat trick:

```rust
fn test_while() -> ! {
    while { panic!(); false } {}
}
```

is incorrectly typed. I'll defer an additional bug since it's similar enough to the `for` issue.

**Comment by camelid** [comment]
I don't think this is a bug.

**Comment by camelid** [comment]
Here's my reasoning:

This code

```
for _ in { panic!(); 0.. } {}
```

is equivalent to

```rust
let iter: RangeTo = { panic!(); 0.. };
for _ in iter {}
```

. The type of `iter` is `RangeTo`, and the type of the `for` expression should not depend on the type of the value it is iterating over.

And the same for `while { panic!(); false } {}`.

**Comment by varkor** [comment]
I have mixed feelings about this. I think this should work if and only if the following works:
```rust
fn foo() -> ! {
    return panic!();
    ()
}
```
which currently does not work. We tend not to use `!` to determine control flow, but I'm not sure if that is a deliberate decision.

**Comment by camelid** [comment]
@varkor Do you want to move this to #t-lang on Zulip or to some kind of T-lang proposal?

**Comment by adlerd** [comment]
It was always my understanding that `{ a; }` is supposed to be the same thing as `{ a; () }` yet now I see a number of simple tests show that when `a : !`, these are not at all equivalent! Namely, `{ panic!(); }` can be typed `!` but `{ panic!(); () }` can't. It's the same situation when you get rid of `panic!()` altogether and use `return 0`.

**Comment by camelid** [comment]
> yet now I see a number of simple tests show that when `a : !`, these are not at all equivalent! Namely, `{ panic!(); }` can be typed `!` but `{ panic!(); () }` can't.

Hmm, that does seem confusing. I still don't think

```rust
for _ in { panic!(); 0.. } {}
```

should be typed as `!`, but I think the behavior you described should be changed so the types are as follows:

```rust
let x: ! = panic!();
let x: ! = { panic!() };
let x: () = { panic!(); };
let x: () = { panic!(); () };
```

**Comment by adlerd** [comment]
I see where you're coming from, but unless you want to treat function bodies as different than other blocks, you will break every program like this:
```rust
fn rand() -> u32 {
    return 4;
}
```

**Comment by varkor** [comment]
My suspicion is as you say, @adlerd: that people often write `return x;` and this would break existing code if it was no longer inferred to be `!`. This must be special-cased somewhere, though I'm not sure where off the top of my head. If there are other inconsistencies, I'd be tempted to change something, but if this is a single special-case, that's probably okay.

**Comment by varkor** [comment]
The special case is described here:
https://github.com/rust-lang/rust/blob/d415fae8b76cddbcd7825cb6642186a833453b3c/compiler/rustc_typeck/src/check/fn_ctxt/checks.rs#L598-L613
