### ISSUE TITLE
Tracking Issue for RFC 2959: Promote aarch64-unknown-linux-gnu to a Tier-1 Rust target

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#78251]
This is a tracking issue for the RFC "Promote aarch64-unknown-linux-gnu to a Tier-1 Rust target" (rust-lang/rfcs#2959).

**Steps:**

- [x] Tier Promotion PR
  - PR: https://github.com/rust-lang/rust/pull/78228
- [ ] Implement stack probes for the `aarch64-unknown-linux-gnu` target
  - Tracking issue: https://github.com/rust-lang/rust/issues/77071

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

**Comment by pietroalbini** [comment]
The PR promoting the target to Tier 1 was just merged! The target is on track to be Tier 1 in Rust 1.49.0!

**Comment by wesleywiser** [comment]
Visited during the compiler team tracking issue triage. We're closing this issue since `aarch64-unknown-linux-gnu` is already Tier 1 and advertised as such. The open issue regarding stack probe support has its own dedicated tracking issue so there's nothing left to do here.
