### ISSUE TITLE
How can i transform Box<dyn Any> to Box<dyn Test> by unsafe?

### ISSUE THREAD

**Issue by Silentdoer** [rust-lang/rust#78261]
let obj: Box<dyn Any> = Box::new(Foo {});
// Foo has impl Test trait
// the following code is error, how can i do this transform?
let obj2: Box<dyn Test> = unsafe {obj as Box<dyn Test>};

**Comment by mbartlett21** [comment]
@Silentdoer 
Transforming `dyn` types is undefined behaviour, since the vtables for the functions will be different.
How you would need to do it is downcast it to a concrete type, then turn that into a `Box<dyn Test>`.

In the `Any` documentation, it states:
> Note that `&dyn Any` is limited to testing whether a value is of a specified concrete type, and cannot be used to test whether a type implements a trait.

**Comment by jonas-schievink** [comment]
Hi! This issue tracker is mainly meant for bug reports and concrete, small feature requests. Questions like this are better asked in the user forum at https://users.rust-lang.org/ or on [one of the chat platforms](https://www.rust-lang.org/community) used by the Rust community.
