### ISSUE TITLE
rustc doesnt correctly optimise trivial multliplication with 0.0 for float types

### ISSUE THREAD

**Issue by TheVova** [rust-lang/rust#78269]
Noticed this while profiling some code.
I compiled this code with release and checked the asm generated.
```rust

pub fn times_zerof(f: f32)->f32 {
    f*0.0
}

pub fn times_onef(f: f32)->f32 {
    f*1.0
}

pub fn times_zerod(f: f64)->f64 {
    f*0.0
}

pub fn times_oned(f: f64)->f64 {
    f*1.0
}


pub fn times_oneu(f: usize)->usize {
    f*1
}
pub fn times_zerou(f: usize)->usize {
    f*0
}

pub fn times_oneu32(f: u32)->u32 {
    f*1
}
pub fn times_zerou32(f: u32)->u32 {
    f*0
}


```
[playground link](https://play.rust-lang.org/?version=stable&mode=release&edition=2018&gist=d9134199b5ea499d88de60aa27942b70)
I expected to see this happen:
for float types, `foo*0.0` should trivially return 0, and for `foo*1.0` it should trivially return foo.

Instead, this happened: 
```rust
playground::times_zerof:
	xorps	%xmm1, %xmm1
	mulss	%xmm1, %xmm0
	retq

playground::times_onef:
	retq

playground::times_zerod:
	xorpd	%xmm1, %xmm1
	mulsd	%xmm1, %xmm0
	retq

playground::times_oned:
	retq

```
seems that for mult with 1, it gets correctly optimized to just a retq, but in the case of mult with 0 there still seems to be a mult instruction there. im not the best with x86 assembly, but i think that shouldnt happen.
for integers this seems to behave correctly.

### Meta
tested on the playground with stable,beta and nightly.

**Comment by jonas-schievink** [comment]
`inf * 0.0 = NaN`, so this optimization would be incorrect

**Comment by lzutao** [comment]
Same optimizations as C++: <https://rust.godbolt.org/z/4YveEs>.
I think the generated asm is appropriate.
