### ISSUE TITLE
Unable to do anything with ./x.py <command> in Windows

### ISSUE THREAD

**Issue by hbina** [rust-lang/rust#78281]
```
PS C:\Users\Hanif\git\rust> python .\x.py check
Updating only changed submodules
Submodules updated in 0.21 seconds
args:['C:\\Users\\Hanif\\git\\rust\\build\\x86_64-pc-windows-msvc\\stage0\\bin\\cargo.exe', 'build', '--manifest-path', 'C:\\Users\\Hanif\\git\\rust\\src/bootstrap/Cargo.toml']
    Finished dev [unoptimized + debuginfo] target(s) in 0.40s
args:['C:\\Users\\Hanif\\git\\rust\\build\\bootstrap\\debug\\bootstrap', 'check']
Traceback (most recent call last):
  File "C:\Users\Hanif\git\rust\x.py", line 11, in <module>
    bootstrap.main()
  File "C:\Users\Hanif\git\rust\src\bootstrap\bootstrap.py", line 1080, in main
    bootstrap(help_triggered)
  File "C:\Users\Hanif\git\rust\src\bootstrap\bootstrap.py", line 1066, in bootstrap
    run(args, env=env, verbose=build.verbose)
  File "C:\Users\Hanif\git\rust\src\bootstrap\bootstrap.py", line 149, in run
    ret = subprocess.Popen(args, **kwargs)
  File "C:\Users\Hanif\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Hanif\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1416, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
OSError: [WinError 193] %1 is not a valid Win32 application
PS C:\Users\Hanif\git\rust> git diff
diff --git a/src/bootstrap/bootstrap.py b/src/bootstrap/bootstrap.py
index 7d3b4b13503..aa1e7a54753 100644
--- a/src/bootstrap/bootstrap.py
+++ b/src/bootstrap/bootstrap.py
@@ -145,6 +145,7 @@ def run(args, verbose=False, exception=False, **kwargs):
     sys.stdout.flush()
     # Use Popen here instead of call() as it apparently allows powershell on
     # Windows to not lock up waiting for input presumably.
+    print('args:{}'.format(args))
     ret = subprocess.Popen(args, **kwargs)
     code = ret.wait()
     if code != 0:
PS C:\Users\Hanif\git\rust>
```

For whatever reason it says that the executable is not a valid Win32 application. I added a print statement in the script to show what arguments are being passed.

**Comment by JohnTitor** [comment]
Just checked on my Windows(msvc) with Python 3.9.0 and it works fine. Have you ever installed Python in the past? If so, the path or something else may be messed up. Try to re-install it.

**Comment by hbina** [comment]
Yes, I have tried both 3.8 and 3.9 to no avail.

**Comment by JohnTitor** [comment]
> Yes, I have tried both 3.8 and 3.9 to no avail.

Then something should be mixed up, I think. Since there's no reproducible step, we cannot do anything here :/ I'd be in favor of closing for now until someone could provide it.

**Comment by jyn514** [comment]
> C:\\Users\\Hanif\\git\\rust\\build\\bootstrap\\debug\\bootstrap

This should have an .exe on the end, I think. I don't know why it's missing.

**Comment by jyn514** [comment]
Python is not relevant, something is going wrong with x.py's logic. Either `bootstrap` should be renamed to `bootstrap.exe`, or `bootstrap` doesn't exist and x.py needs add `.exe` to the end.

**Comment by JohnTitor** [comment]
> This should have an .exe on the end, I think. I don't know why it's missing.

I don't think so. It's missing on my local as well but my bootstrapping works fine.

**Comment by jyn514** [comment]
@hbina if you run `x.py clean` first then try again, does it fix the issue?

**Comment by rylev** [comment]
If we don’t have a repro we should probably close this issue. This also works without issue on my machine.
