### ISSUE TITLE
catch_unwind not working with opt-level > 1

### ISSUE THREAD

**Issue by snx90** [rust-lang/rust#78290]
In Windows (Rust nightly version), running the following code in release mode (default options):

```rust
extern crate libc;

use std::panic;
use libc::*;

#[cfg(all(windows, target_arch = "x86_64"))]
unsafe fn segfault_handler(_signum: c_int) {
    panic!("I got you");
}

#[cfg(all(windows, target_arch = "x86_64"))]
fn main() {
    let f = segfault_handler as *const fn(c_int);
    unsafe { signal(SIGSEGV, f as size_t); }

    let mut pointer: *mut u64 = std::ptr::null_mut();
    unsafe{
        let result = panic::catch_unwind(|| {
            core::ptr::write_volatile(pointer, 1);
        });
        assert!(result.is_err());
    }

    print!("hello again!\n");
}
```

results in the following (unexpected) behavior:

```
thread 'main' panicked at 'I got you', src\main.rs:8:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `C:\Users\test\temp\panics\target\release\panics.exe` (exit code: 101)
```

However, running the same example in development mode (default options) does produce the expected output (i.e., the signal is handled and the process successfully exits):

```
thread 'main' panicked at 'I got you', src\main.rs:8:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
hello again!
```

I have noticed that this issue happens whenever the opt-level > 1.

**Comment by jonas-schievink** [comment]
Pretty sure unwinding out of a signal handler is UB

**Comment by jyn514** [comment]
And even more than that, derefencing the null pointer in the first place is UB.

**Comment by snx90** [comment]
@jyn514 That was to trigger the segmentation fault, but the same behavior is observed regardless what triggered it.

**Comment by sfackler** [comment]
This is undefined behavior for multiple reasons:

1. `signal` requires a function pointer with the C ABI (i.e. `extern "C" fn(c_int)`), not a function pointer with a Rust ABI.
2. As @jonas-schievink noted, it is undefined behavior to unwind through a signal handler. The Windows documentation for the signal function talks about the (very few) things you are allowed to do in a signal handler: https://docs.microsoft.com/en-us/previous-versions/xdkz3x12(v=vs.140).

The fact that it happens to work when optimizations are disabled doesn't really mean anything.

**Comment by jonas-schievink** [comment]
Closing as not-a-bug
