### ISSUE TITLE
Can not get the span of `Mutability` from ast 

### ISSUE THREAD

**Issue by whizsid** [rust-lang/rust#78315]
Currently we can not get the span of `mut` keyword. 

Example:-
```rust
fn foo(file:`& /* Some comment */ mut /* Another Comment */ File`) {}
```
I like to work on this issue. But I need an advice. If I store the span in an enum field like `Mutability::Mut(Span)` I can not implement the invert function. https://github.com/rust-lang/rust/blob/7bade6ef730cff83f3591479a98916920f66decd/compiler/rustc_ast/src/ast.rs#L752 .

**Comment by jyn514** [comment]
@whizsid for questions about compiler internals, I recommend asking on the Zulip instead: https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp. This isn't really a bug in rustc, and the issue tracker isn't checked as frequently as the Zulip.
