### ISSUE TITLE
Implement constant folding in the frontend

### ISSUE THREAD

**Issue by pcwalton** [rust-lang/rust#7834]
We should be able to do constant folding in the frontend to eliminate "if" conditions that are never executed. It would also be nice to be able to call `size_of` at compile time in constants. (This latter part is an RFC.)

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#685
