### ISSUE TITLE
Prefer new associated numeric consts in float error messages

### ISSUE THREAD

**Issue by bstrie** [rust-lang/rust#78382]
This program:

```rust
fn main() {
    let _ =  3.40282357e+38_f32;
    let _ =  1.7976931348623159e+308_f64;
}
```

Produces this output:

```
error: literal out of range for `f32`
 --> src/main.rs:2:14
  |
2 |     let _ =  3.40282357e+38_f32;
  |              ^^^^^^^^^^^^^^^^^^
  |
  = note: `#[deny(overflowing_literals)]` on by default
  = note: the literal `3.40282357e+38_f32` does not fit into the type `f32` and will be converted to `std::f32::INFINITY`

error: literal out of range for `f64`
 --> src/main.rs:3:14
  |
3 |     let _ =  1.7976931348623159e+308_f64;
  |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: the literal `1.7976931348623159e+308_f64` does not fit into the type `f64` and will be converted to `std::f64::INFINITY`
```

Note the references to `std::{f32, 64}::INFINITY`; these symbols have been superseded by associated consts at `{f32,f64}::INFINITY` (https://github.com/rust-lang/rust/issues/68490).

1. Update the error message to suggest the new symbols

2. Determine if any of the other old symbols are contained in any error messages.

**Comment by bstrie** [comment]
See also #73194.

**Comment by Rustin-Liu** [comment]
I am working on this.
@rustbot claim

**Comment by bstrie** [comment]
@estebank : 

> I think there are other cases where we still use the old mod consts.

I've gone and grepped through `compiler/` for `std::i8`, `std::f32`, etc. and found no accidental uses there. I also grepped for `std::{}` (as seen in this issue) and found only a hint message for things like `f32::consts::PI` etc which only triggers when an item isn't found at all, which won't trigger for any of the new consts. Probably safe to close this once #78431 merges.

**Comment by bstrie** [comment]
Yeah, that's the aforementioned case that only shows up in the event of an error, so (AFAICT) that path won't be taken for the new constants since they resolve successfully.
