### ISSUE TITLE
Copy command in "The book" copies the $ character too

### ISSUE THREAD

**Issue by deepdmistry** [rust-lang/rust#78427]
Minor inconvenience, while going through the first chapter of [the book, ](https://doc.rust-lang.org/book/ch01-01-installation.html) the copy button copies the `$` sign too, causing terminal error.

**Comment by arijit79** [comment]
Yeah! I looked into it and it happened to me too

**Comment by lzutao** [comment]
Can someone move this issue to <https://github.com/rust-lang/book> ?

**Comment by deepdmistry** [comment]
Apologies, didn't realize the book was a separate repo. Should i close this and open a new one there ?

**Comment by deepdmistry** [comment]
Closing this because I opened rust-lang/book#2488
