### ISSUE TITLE
Intra-doc links do not use dev-dependencies

### ISSUE THREAD

**Issue by Evian-Zhang** [rust-lang/rust#78468]
I tried this code:

```rust
// In crate foo
pub struct MyStruct {}
```

```rust
// in crate bar
//! A link to [`foo::MyStruct`]
```

If I put `foo` in `bar`'s dev-dependencies, the intra-doc links do not generate, and a warning

```
no item named `foo::MyStruct` in scope
```

turns out. If I put `foo` in `bar`'s dependencies instead, there is no warning and the intra-doc links are generated correctly.

This situation is quite common when we are writing a proc macro crate `a`, which provides derive macros for another crate `b`. We put `a` in `b`'s dependencies, and put `b` in `a`'s dev-dependencies for writing docs for `a`.

### Meta

`rustc --version --verbose`:
```
rustc 1.49.0-nightly (a1dfd2490 2020-10-05)
binary: rustc
commit-hash: a1dfd2490a6cb456b92e469fa550dc217e20ad6d
commit-date: 2020-10-05
host: x86_64-unknown-linux-gnu
release: 1.49.0-nightly
LLVM version: 11.0
```

**Comment by jyn514** [comment]
Cyclic dependencies are not really supported. I'd suggest putting the documentation on the re-export instead, like this:

```
// proc-macro crate
pub fn my_proc_macro() { ... }

// main crate
/// Here are [intra-doc links](my_function) for my_proc_macro
pub use proc_macro_crate::my_proc_macro;
```

**Comment by Evian-Zhang** [comment]
> Cyclic dependencies are not really supported. I'd suggest putting the documentation on the re-export instead

Yes, this is a feasible workaround. But it is strange that doc test uses dev-dependencies, but intra-doc links use dependencies.

**Comment by jyn514** [comment]
Doc tests are a completely separate mechanism: they're compiling a _new crate_ that links to the current one, so it doesn't end up as a cyclic dependency.

Anyway, rustdoc can't do anything about this: cargo is what provides dependencies and it doesn't provide dev dependencies when documenting. So the issue should be moved there.
