### ISSUE TITLE
The release notes for 1.45.0 don't mention the LLVM upgrade

### ISSUE THREAD

**Issue by glandium** [rust-lang/rust#78464]
I'll leave my story here because it shows how important the information can be:

We recently upgraded from rustc 1.43 to 1.47 to build Firefox (we got stuck on 1.43 for a large number of complicated reasons, and would still be stuck if we hadn't found workarounds). Anyways, consequently, we've had a bunch of regressions, one of which was performance-related and I was bisecting it. The first thing I did was to compare each rust release, and it turned out the regression started between 1.44 and 1.45. So I went to the 1.45 release notes suspecting LLVM could have been involved and saw nothing there.
Now, several hours later bisecting through nightlies (because PGO and LTO being involved, testing one version takes a while), the regression appears to have started between
  rustc 1.45.0-nightly (9310e3bd4 2020-05-21)
and
  rustc 1.45.0-nightly (0aa6751c1 2020-05-20)

So I take my git, type `git log 0aa6751c1..9310e3bd4 --author=bors --oneline` and lo and behold, there it is:
```
9310e3bd4f4 Auto merge of #71930 - Nadrieril:exhaustiveness-remove-tyerr, r=varkor
148c125b1bf Auto merge of #71718 - NeoRaider:ffi_const_pure, r=Amanieu
06c9fef822b Auto merge of #72422 - RalfJung:rollup-u81z4mw, r=RalfJung
7f79e98c035 Auto merge of #72205 - ecstatic-morse:nrvo, r=oli-obk
963bf528292 Auto merge of #70705 - lcnr:generic_discriminant, r=nikomatsakis
82911b3bba7 Auto merge of #67759 - nikic:llvm-10, r=Mark-Simulacrum
```
I'm still waiting on the results actually confirming LLVM is involved (it likely is), but it would have saved me a lot of time if the LLVM upgrade had been mentioned (which it is for LLVM 11 in 1.47, BTW, but OTOH, now that I look, it appears the last upgrade mentioned is to LLVM 6 in 1.25...)

**Comment by jyn514** [comment]
FWIW, the LLVM 11 upgrade in 1.47 got back a lot of the performance LLVM 10 lost: https://perf.rust-lang.org/compare.html?start=e482c86b9de32c6392cb83aa97d72e22425163f9&end=7ce71c362be9a89e7897ac066aba6e3e6f747800&stat=wall-time.

**Comment by glandium** [comment]
Not for the testcase I'm bisecting, but that's OT.

**Comment by Mark-Simulacrum** [comment]
I agree we should be mentioning this; thank you for noting it. I would be happy to accept a PR adding those in to the release notes (just 1.45 and 1.47, or more if you have the time).

**Comment by joshtriplett** [comment]
@glandium:
> Not for the testcase I'm bisecting, but that's OT.

Do you have an issue for that regression?

**Comment by glandium** [comment]
> @glandium:
> Do you have an issue for that regression?

Will have when I have more information to feed into one.
