### ISSUE TITLE
Code bloat from RawVec::grow_amortized

### ISSUE THREAD

**Issue by glandium** [rust-lang/rust#78471]
The change in #72227 made non-PGO builds of Firefox's libxul.so's .text section grow by close to 1MB. libxul.so has a ~89MB section, which makes it a > 1% size increase in a library where about only 16% of the code is rust, which makes it a > 7% (!) increase in size. This comes from the fact that essentially all uses of Vec::push inline this all for some reason, and it's used all across the place.

**Comment by lcnr** [comment]
inling `grow_amortized` seems to have a noticable performance benefit, so not doing so is probably not desirable, see #78483

Not sure how else we would be able to directly remedy this issue.

**Comment by spastorino** [comment]
Assigning `P-medium` as [discussed as part of the Prioritization Working Group procedure](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/I-prioritize.20.2378471.20Code.20bloat.20from.20RawVec.3A.3Agrow_amortized) and removing `I-prioritize`.
