### ISSUE TITLE
rustdoc doesn't render HRTBs

### ISSUE THREAD

**Issue by WaffleLapkin** [rust-lang/rust#78482]
I tried this code:

```rust
pub fn test<T>() 
where
    for<'a> &'a T: Iterator,
{}
```

I expected `rustdoc` to render HRTB (`for<'a>`), but it doesn't:

![image](https://user-images.githubusercontent.com/38225716/97434563-3c8e1080-1930-11eb-9f8d-82d856c62154.png)

Originally find while viewing [keyberon docs](https://docs.rs/keyberon/0.1.1/keyberon/matrix/struct.Matrix.html).

### Meta

`rustdoc --version --verbose`:
```
rustdoc 1.49.0-nightly (ffa2e7ae8 2020-10-24)
binary: rustdoc
commit-hash: ffa2e7ae8fbf9badc035740db949b9dae271c29f
commit-date: 2020-10-24
host: x86_64-unknown-linux-gnu
release: 1.49.0-nightly
LLVM version: 11.0
```

**Comment by jyn514** [comment]
Hmm, rustdoc should already handle this in https://github.com/rust-lang/rust/blob/6bea76f175f1a565320a1a93a174fb80567dda7c/src/librustdoc/html/format.rs#L334, which includes generic lifetimes: [`PolyTrait`](https://doc.rust-lang.org/nightly/nightly-rustc/rustdoc/clean/types/struct.PolyTrait.html), [`GenericParamDef`](https://doc.rust-lang.org/nightly/nightly-rustc/rustdoc/clean/types/struct.GenericParamDef.html). Someone would need to investigate why that isn't showing up - I suspect somewhere in `clean` isn't handling it properly: https://github.com/rust-lang/rust/blob/6bea76f175f1a565320a1a93a174fb80567dda7c/src/librustdoc/clean/mod.rs#L291

**Comment by hi-rustin** [comment]
@jyn514  Can I working on this? I want to have a try.

**Comment by jyn514** [comment]
@hi-rustin absolutely! If you have trouble, feel free to ask in [the rustdoc channel](https://discord.gg/4yEYPuT) or [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp) :)

**Comment by hi-rustin** [comment]
I started to try it.

**Comment by hi-rustin** [comment]
> Hmm, rustdoc should already handle this in
> 
> https://github.com/rust-lang/rust/blob/6bea76f175f1a565320a1a93a174fb80567dda7c/src/librustdoc/html/format.rs#L334
> , which includes generic lifetimes: [`PolyTrait`](https://doc.rust-lang.org/nightly/nightly-rustc/rustdoc/clean/types/struct.PolyTrait.html), [`GenericParamDef`](https://doc.rust-lang.org/nightly/nightly-rustc/rustdoc/clean/types/struct.GenericParamDef.html). Someone would need to investigate why that isn't showing up - I suspect somewhere in `clean` isn't handling it properly:
> 
> https://github.com/rust-lang/rust/blob/6bea76f175f1a565320a1a93a174fb80567dda7c/src/librustdoc/clean/mod.rs#L291

Do you mean that we are missing generic_params? I tried constructing generic_params, but it still doesn't seem to work.

**Comment by jyn514** [comment]
@hi-rustin I don't know, that's what I mean by investigate. You could start by checking if `generic_params` is empty or not, or whether this code path is being taken at all.
