### ISSUE TITLE
Possible regression with #[rustfmt::skip]

### ISSUE THREAD

**Issue by steveklabnik** [rust-lang/rust#78488]
Hi folks! I am getting users reporting a regression in the semver crates, see:

* https://github.com/steveklabnik/semver-parser/issues/52
* https://github.com/steveklabnik/semver/issues/218

It appears that the rustfmt attributes are no longer considered "built-in"? Or am I completely mis-remembering this?

Sorry for not being 100% sure about the regression here, but I don't want this to get lost.

@rustbot modify labels: +regression-from-stable-to-stable -regression-untriaged

**Comment by ehuss** [comment]
@steveklabnik I believe this was changed in 1.44 probably via #69838. Do you happen to know which version the reporter was using? 1.44 or newer should build ok.

There are still some oddities with inner tool attributes like #74087, so it is possible it could be that.

**Comment by steveklabnik** [comment]
I don't know, but let's see if they can tell us: @dwarburt and @tarcieri (as well as @krisfris, who gave a 👍 on tony's issue), what Rust versions are you using?

**Comment by tarcieri** [comment]
The main failure I have handy is 1.41.0:

https://github.com/RustSec/rustsec-crate/runs/1318970855?check_suite_focus=true

**Comment by dwarburt** [comment]
I'm using the toolchain that the brave-browser build scripts downloads
```
✔ ~/git/fork/brave-browser [master|✚ 1]$ ./src/brave/build/rustup/0.1.4/bin/rustc --version
rustc 1.47.0 (18bf6b4f0 2020-10-07)
✔ ~/git/fork/brave-browser [master|✚ 1]$ 
```

**Comment by djc** [comment]
I ran into this with 1.34.0 (which is the MSRV for err-derive, which used to depend on semver-parser via rustc-version).

**Comment by steveklabnik** [comment]
It appears this is actually my fault: https://github.com/steveklabnik/semver-parser/issues/52#issuecomment-719419614

sorry about the noise.
