### ISSUE TITLE
ERROR - exit code: 101

### ISSUE THREAD

**Issue by NSH531** [rust-lang/rust#78495]
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: IoError(Os { code: 10061, kind: ConnectionRefused, message: "No connection could be made because the target machine actively refused it." })', src\main.rs:11:91
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\chatBBBS.exe` (exit code: 101)

**Comment by jonas-schievink** [comment]
This is an error in your code.
