### ISSUE TITLE
Regression parsing closing angle brackets near function ptr return type

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust#78507]
*Alternate title: "Rust is literally C++"　https://wg21.link/N1757*

As of nightly-2020-10-29, rustc fails to parse the following code. The previous nightly and all past stable releases since 1.0.0 are not affected.

```rust
pub fn f() -> Option<fn() -> Option<bool>> {
    None
}
```

```console
error: unmatched angle bracket
 --> src/main.rs:1:42
  |
1 | pub fn f() -> Option<fn() -> Option<bool>> {
  |                                          ^^ help: remove extra angle bracket

error: expected one of `,` or `>`, found `{`
 --> src/main.rs:1:44
  |
1 | pub fn f() -> Option<fn() -> Option<bool>> {
  |                                            ^ expected one of `,` or `>`
```

The relevant commit range is https://github.com/rust-lang/rust/compare/07e968b640e8ff76fa8be4b48b70ab80ea577800...31ee872db5aae4750e3da1ca4ed1523c4356947f.

**Comment by dtolnay** [comment]
Mentioning @estebank @varkor because #78379 "Tweak invalid \`fn\` header and body parsing" sounds extremely relevant.

**Comment by camelid** [comment]
Assigning `P-critical` and removing `I-prioritize` as [discussed](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/I-prioritize.20.2378507.20Regression.20parsing.20closing.20angle.20bracke.E2.80.A6) in the prioritization working group.

**Comment by camelid** [comment]
searched nightlies: from nightly-2020-10-27 to nightly-2020-10-29
regressed nightly: nightly-2020-10-29
searched commits: from https://github.com/rust-lang/rust/commit/07e968b640e8ff76fa8be4b48b70ab80ea577800 to https://github.com/rust-lang/rust/commit/31ee872db5aae4750e3da1ca4ed1523c4356947f
regressed commit: https://github.com/rust-lang/rust/commit/db241bb0c8d257e13c1560f6250e49879477039e

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.0</summary>


Host triple: x86_64-apple-darwin
Reproduce with:
```bash
cargo bisect-rustc --preserve --regress=error --start=2020-10-27 
```
</details>

**Comment by estebank** [comment]
Yep, this was me :-/
