### ISSUE TITLE
`x.py setup` creates config.toml in root directory, even if one is running in a different directory

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#78509]
If you run `x.py build` in a directory with no config.toml, it suggests you run `x.py setup` first.

I did that.

Then I ran `x.py build` again. And it made the same suggestion.

The suggestion wasn't wrong, since there was no config.toml in my current directory, even after running `x.py setup`; the problem was that running `x.py setup` is generating the `config.toml` in the source root, rather than in the current directory.

**Comment by jyn514** [comment]
@pnkfelix are you using different `config.toml` files depending on the directory? Or did you intend to run `x.py` from the top-level directory?

**Comment by jyn514** [comment]
Or did you intend to run x.py from the current directory but use the top-level config.toml?

**Comment by cuviper** [comment]
Normally `x.py` uses the config from the current directory, so I would expect `x.py setup` to create the same. I don't know about pnkfelix, but I often want to try a single source tree with multiple configs (bundled vs system LLVM, alt debug settings, etc.).

**Comment by jyn514** [comment]
This was fixed in https://github.com/rust-lang/rust/pull/78550.
