### ISSUE TITLE
compiletest: show affected architecture in error summary

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#78517]
When compiletest fails, it prints an error summary like this at the end:
```
failures:
    [mir-opt] mir-opt/issue-73223.rs

test result: FAILED. 139 passed; 1 failed; 3 ignored; 0 measured; 0 filtered out
```
However, there is one very important bit of information that I cannot gleam from this information: what are the host and target architectures that were tested! Figuring this out requires scrolling up quite a bit to where this test beings (and carefully not scrolling up too far because then one might look at the wrong test).

See https://github.com/rust-lang/rust/pull/78343 for an example where this confused people. I have also been confused by this multiple times in the past, e.g. using the name of the CI runner to incorrectly deduce what the architecture(s) are (and not realizing that some of our runners run tests for quite a few different targets).

So I think in case of a failure, that summary at the end should repeat the important information that is printed at the top of the test run:
> compiletest suite=mir-opt mode=mir-opt (x86_64-unknown-linux-gnu -> armv5te-unknown-linux-gnueabi)

**Comment by RalfJung** [comment]
Cc @Mark-Simulacrum

**Comment by camelid** [comment]
And also it would be nice if when it ignored a test because it was the wrong platform, it showed some indication of that, because otherwise it looks like it ran the test and it passed. Perhaps show a question mark (`?`)? (We already use `i` for tests that were ignored because they were already run and passed.)

**Comment by RalfJung** [comment]
AFAIK `i` should already be used for all kinds of "ignored", including `// ignore-XX` directives.

**Comment by RalfJung** [comment]
Turns out these messages are printed by bootstrapm not compiletest:
