### ISSUE TITLE
[ER] likely() for match arms too?

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust#78518]
Inspired by this discussion:
https://old.reddit.com/r/programming/comments/jjtobp/fast_programming_languages_c_c_rust_and_assembly/

We may consider introducing some way to hint what the likely/unlikely arms of a match are. Using an intrinsic (working as a const identity function) like this gives a syntax that looks like a kludge, a better syntax is welcome:

```rust
#![feature(core_intrinsics)]

use std::intrinsics::{likely, unlikely, likely_arm, unlikely_arm};

fn foo(x: u32) {
    if likely(x == 5) {
        println!("A");
    } else {
        println!("B");
    }
}

fn bar(x: u32) {
    match x {
        likely_arm(5) => println!("A"),
        unlikely_arm(_) => println!("B"),
    }
}

fn main() {
    foo(5);
    bar(5);
}
```

**Comment by steveklabnik** [comment]
In general, big changes like this go through the RFC process, and aren't tracked by bug reports filed on this repo. Thanks!

**Comment by gilescope** [comment]
FYI this is being discussed at #26179
