### ISSUE TITLE
VecDeque from Vec fails with ZST

### ISSUE THREAD

**Issue by alecmocatta** [rust-lang/rust#78532]
This code panics under Miri, and also when I compile to WASM, though not when running normally.

```rust
use std::collections::VecDeque;

fn main() {
    let _: VecDeque<()> = vec![()].into();
}
```

[Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=d709dae58894f45e7c866df3f98bac60)

```text
thread 'main' panicked at 'attempt to add with overflow', /playground/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/alloc/src/collections/vec_deque.rs:3236:36
```

The overflow is here: https://github.com/rust-lang/rust/blob/a53fb30e3bf2655b0563da6d561c23cda5f3ec11/library/alloc/src/collections/vec_deque.rs#L3236

**Comment by camelid** [comment]
I can reproduce when using Miri, but it works fine for me with WASM:

```console
$ cargo +stable build --target=wasm32-unknown-unknown
   Compiling rust-issue-78532 v0.1.0 (/Users/user/rust-issue-78532)
    Finished dev [unoptimized + debuginfo] target(s) in 0.17s
```

**Comment by lcnr** [comment]
```rust
use std::collections::VecDeque;

fn main() {
    let v = vec![(); 100];
    let queue = VecDeque::from(v);
    println!("{:?}", queue);
}
```
panics with
```
thread 'main' panicked at 'capacity overflow', library/alloc/src/raw_vec.rs:542:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

*it always fails here because `len` is greater than `MINIMUM_CAPACITY` so `cap - len` underflows.*

**Comment by camelid** [comment]
Why is this specific to ZSTs?

**Comment by lcnr** [comment]
`Vec` does not allocate for `ZST` and starts out with capacity `usize::MAX` which overflows when converting to a deque which does not expect this

**Comment by camelid** [comment]
Assigning `P-high` and removing `I-prioritize` as [discussed](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/I-prioritize.20.2378532.20VecDeque.20from.20Vec.20fails.20with.20ZST) in the prioritization working group.

**Comment by RalfJung** [comment]
> This code panics under Miri, and also when I compile to WASM, though not when running normally.

Currently on playground it seems to work fine both under Miri and regular rustc? Indeed something would be very wrong if it only panicked on Miri...

@lcnr's version panics both with rustc and Miri. Maybe the example in the OP should be updated.

**Comment by alecmocatta** [comment]
> Currently on playground it seems to work fine both under Miri and regular rustc? Indeed something would be very wrong if it only panicked on Miri...

Yes, though at time of posting it did fail under miri (and only under miri) on the playground.

> I can reproduce when using Miri, but it works fine for me with WASM

Sorry if I was unclear; I meant that I got the same panic when *running* the built WASM.

**Comment by RalfJung** [comment]
> Yes, though at time of posting it did fail under miri (and only under miri) on the playground.

My guess is that something in libstd changed to fix the panic for your case (but not for @lcnr's), and when you tested this, Miri was broken in the latest toolchain so playground had an older version of Miri. When this happens again, please note down the exact versions of every component involved.

**Comment by tmiasko** [comment]
The originally reported panic is an overflow check and one of those that is not inherited cross-crate. To observe it the standard library must be built with overflow checks. It still an issue right now.

**Comment by RalfJung** [comment]
Ah, so this stopped to fail in Miri when we recently stopped building libstd with debug assertions.
