### ISSUE TITLE
Better diagnostics for missing iterator in for-loop

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#78537]
Spot the bug:
```rust
fn f() -> usize {
    for i in {
        println!("{}", i);
    }
    1
}
```
Unfortunately, instead of pointing to the missing iterator, rust points to the 1:
```
error: expected `{`, found `1`
 --> src/lib.rs:5:5
  |
5 |     1
  |     ^
  |     |
  |     expected `{`
  |     help: try placing this code inside a block: `{ 1 }`
```
I'd love it to instead say 'missing iterator for loop':
```
error: expected iterator, found block
 --> src/lib.rs
  |
2 |    for i in {
  |             ^ this starts a block expression ...
5 |     1
  |     ^ ... so there is no body for the loop
  =     help: try adding an iterator to the for-loop: `for i in iter {`
```

Other variants of this with less than ideal errors:
```rust
fn f() {
    for i in {
        println!("{}", i);
    }
}
```
```
error: expected `{`, found `}`
 --> src/lib.rs:5:1
  |
5 | }
  | ^ expected `{`
```
```rust
fn f() -> usize {
    for i in {
        println!("{}", i);
    }
    return 1;
}
```
```
error: expected `{`, found keyword `return`
 --> src/lib.rs:5:5
  |
5 |     return 1;
  |     ^^^^^^---
  |     |
  |     expected `{`
  |     help: try placing this code inside a block: `{ return 1; }`
```

**Comment by camelid** [comment]
> I'd love it to instead say 'missing iterator for loop':
> 
> ```
> error: expected iterator, found block
>  --> src/lib.rs
>   |
> 2 |    for i in {
>   |             ^ this starts a block expression ...
> 5 |     1
>   |     ^ ... so there is no body for the loop
>   =     help: try adding an iterator to the for-loop: `for i in iter {`
> ```

Well, it thinks the block *is* the iterator.

**Comment by camelid** [comment]
Yes, I just wanted to make sure we were on the same page :)

**Comment by estebank** [comment]
I could have sworn there was an old `[A-diagnostics]` ticket for this already but I can't find it 😅
