### ISSUE TITLE
`./x.py build --stage 2` does not build stage 1 rustdoc

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#78555]
```console
$ ./x.py build --stage 2
$ rustdoc +r2stage1 somefile.rs
error: 'rustdoc' is not installed for the toolchain 'r2stage1'
To install, run `rustup component add rustc --toolchain r2stage1`
$ ./x.py build
...
Copying stage1 std from stage1 (x86_64-apple-darwin -> x86_64-apple-darwin / x86_64-apple-darwin)
Building rustdoc for stage1 (x86_64-apple-darwin)
   Compiling rustdoc v0.0.0 (/Users/user/rust2/src/librustdoc)
   Compiling rustdoc-tool v0.0.0 (/Users/user/rust2/src/tools/rustdoc)
    Finished release [optimized + debuginfo] target(s) in 2m 13s
Build completed successfully in 0:02:18
$ rustdoc +r2stage1 somefile.rs
# works fine
```

Cc @jyn514 -- you know rustdoc *and* `x.py` :)

**Comment by jyn514** [comment]
@camelid I'm pretty sure it builds stage2 rustdoc, just not stage1 rustdoc. Do you have a binary at `build/x86_64-apple-darwin/stage2/bin/rustdoc`?

**Comment by camelid** [comment]
You're probably right 🤦 

I'm so used to using `+stage1` that I forgot it's only for stage1.

**Comment by jyn514** [comment]
That said, there shouldn't be any difference between stage1 and stage2 other than the compiler it's linked to and built by. `stage1/rustdoc` and `stage2/rustdoc` should always do the same thing, perhaps with varying levels of efficiency.

**Comment by camelid** [comment]
Yeah, it's just because I'm testing stuff with Miri :)
