### ISSUE TITLE
rust how to call the dynamic library (dylib / cdylib) generated by rust?

### ISSUE THREAD

**Issue by gaojunjie03** [rust-lang/rust#78557]
rust how to call the dynamic library (dylib / cdylib) generated by rust?

**Comment by jyn514** [comment]
@gaojunjie03 for help with rust I recommend asking on [the Discord](https://discord.gg/rust-lang) or [Discourse](https://users.rust-lang.org/). Github issues is meant as a bug tracker, not a support forum.
