### ISSUE TITLE
rustdoc: Downstream implementors are not linked to

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#78615]
Rustdoc doesn't link to implementors of a trait where the implementors are in a downstream crate; e.g., [`rustc_middle::mir::visit::Visitor`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/mir/visit/trait.Visitor.html#implementors):

![image](https://user-images.githubusercontent.com/37223377/97792101-1fa74680-1b97-11eb-8f87-2807184a07d9.png)

I would think this is a limitation related to #74481, but the implementors *are* listed, they just aren't linked to, so I'm not sure what the cause is.

**Comment by jyn514** [comment]
I think this is a duplicate of https://github.com/rust-lang/rust/issues/76736.

**Comment by jyn514** [comment]
If you can reproduce outside of rustc, that's a bug though.

**Comment by camelid** [comment]
I can reproduce it in a private project, but I'd rather not share the sources. I'll see if I can get an MCVE.

**Comment by camelid** [comment]
MCVE: https://github.com/camelid/rust-issue-78615

**Comment by jyn514** [comment]
The code from that crate:
```rust
// crate a
pub trait MyTrait {}

// crate b
use crate_a::MyTrait;

struct MyStruct;

impl MyTrait for MyStruct {}
```

**Comment by camelid** [comment]
Yeah, I just wanted to provide a repo that you can just clone and build to reproduce :)

**Comment by camelid** [comment]
Weirdly, the issue seems to be spurious: Sometimes I see `impl MyTrait for MyStruct` in the "Implementors" list, sometimes I see nothing.

**Comment by camelid** [comment]
The output for camelid/rust-issue-78615@3dfc5ea:

![image](https://user-images.githubusercontent.com/37223377/97793426-fa233880-1ba8-11eb-875f-7642a8189517.png)

**Comment by camelid** [comment]
This partially worked as of nightly-2020-04-08:

![image](https://user-images.githubusercontent.com/37223377/97793441-2b9c0400-1ba9-11eb-83cf-f21b70fe2982.png)

Note that `MyTrait` is linked to for the `MyStruct` impl, but not for the `MyLocalStruct` impl. Also note that there is only a source link for `MyLocalStruct`.

**Comment by camelid** [comment]
searched nightlies: from nightly-2019-01-01 to nightly-2020-11-01
regressed nightly: nightly-2020-07-31
searched commits: from https://github.com/rust-lang/rust/commit/db0492ace429cfeb3567e2c04e300be7df9972ff to https://github.com/rust-lang/rust/commit/cfc572cae2d1fc381cce476b5c787fd7221af98c
regressed commit: https://github.com/rust-lang/rust/commit/6b269e44322cfca727fd0e793d3a60bd371cbcae

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.0</summary>


Host triple: x86_64-apple-darwin
Reproduce with:
```bash
cargo bisect-rustc --preserve --prompt --start=2019-01-01 -- doc 
```
</details>

-----

This was caused by #73767.

**Comment by camelid** [comment]
I think this is unrelated, but I want to note that running `cargo doc` after making `MyStruct` private still shows it as an implementor. You have to run `cargo clean` to get it to go away.

I'm guessing this is because rustdoc isn't re-documenting `crate_a` when `crate_b` changes and thus it has stale data?

**Comment by camelid** [comment]
cc @rust-lang/rustdoc

**Comment by camelid** [comment]
This appears to be fixed now, both in the rustc API docs and my MCVE! 🎉
