### ISSUE TITLE
Type expectation appears to be reversed

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#78656]
The expected type and the found type seem to be reversed here. The error says it expected `()` and found `i32`, but it seems to me that it expected `i32` and found `()`.

```rust
fn do_stuff(x: i32) -> i32 {
    if x < 0 {
        return 0;
    } else {
        if 1 == 1 {
            return 1;
        }
    }
}
```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=9c11a313cecfe8dcab968c016e1b65cc))

Errors:

```
   Compiling playground v0.0.1 (/playground)
error[E0317]: `if` may be missing an `else` clause
 --> src/lib.rs:5:9
  |
5 | /         if 1 == 1 {
6 | |             return 1;
7 | |         }
  | |_________^ expected `()`, found `i32`
  |
  = note: `if` expressions without `else` evaluate to `()`
  = help: consider adding an `else` block that evaluates to the expected type

error: aborting due to previous error

For more information about this error, try `rustc --explain E0317`.
error: could not compile `playground`.

To learn more, run the command again with --verbose.

```

**Comment by JohnTitor** [comment]
The diagnostics look correct to me, actually, the note points out why the error happens.
```
note: `if` expressions without `else` evaluate to `()`
```

**Comment by camelid** [comment]
But then it says:

> ``expected `()`, found `i32```

What does that mean? Where's the `i32` coming from?

**Comment by JohnTitor** [comment]
> What does that mean? Where's the `i32` coming from?

Note that the error talks about the `if` expression, not the function!
`if` expressions without `else` evaluate to `()`, we **expect** the body returns `()`. But when rustc looked at it, they **found** `i32` (i.e. `1`). Does this make sense for you?

**Comment by camelid** [comment]
I understand that it evaluates to `()`, but where did rustc find `i32`? In the function return type? That would seem like an expectation to me.

**Comment by JohnTitor** [comment]
> 
> 
> I understand that it evaluates to `()`, but where did rustc find `i32`? In the function return type? That would seem like an expectation to me.

Yep, rustc infers `1`'s type following the return type. You could change it to `u32`, for example, and see the message :)

**Comment by camelid** [comment]
But then shouldn't the message be "expected `i32` [because of the return type], found `()` [because if without else has type `()`]", which is the reverse of the current message? I still feel confused :/

**Comment by JohnTitor** [comment]
Rustc only talks about line 5-7 in that error. In that scope, we **expect** to be returned `()` from the `if` expression since it doesn't have `else`.
If you add `else` with a wrong return type (https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=f4df73521f639fcf5939d8051207a3fe), now rustc looks at the entire function and finds the `bool` is incorrect.

**Comment by camelid** [comment]
> In that scope, we **expect** to be returned `()` from the `if` expression since it doesn't have `else`.

So why *doesn't* the `if` expression return `()` here?

**Comment by estebank** [comment]
This occurs because the if without else is always (), but from the return type, through the tail expression of the outermost if/else, the type system expects an i32. The first branch is of type !, which coerces to i32, but the second one is of type () which doesn't.

**Comment by estebank** [comment]
Current output:

```
error[E0317]: `if` may be missing an `else` clause
 --> src/lib.rs:5:9
  |
5 | /         if 1 == 1 {
6 | |             return 1;
7 | |         }
  | |_________^ expected `i32`, found `()`
  |
  = note: `if` expressions without `else` evaluate to `()`
  = help: consider adding an `else` block that evaluates to the expected type
```
```
error[E0308]: mismatched types
 --> src/lib.rs:8:20
  |
1 | fn do_stuff(x: i32) -> i32 {
  |                        --- expected `i32` because of return type
...
8 |             return true;
  |                    ^^^^ expected `i32`, found `bool`
```
