### ISSUE TITLE
rustdoc: Only show the original item for re-exported items in search results

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#78719]
Currently rustdoc will show all items that match the query string, even re-exported ones, which can be kind of frustrating when I get a bunch of results that are actually all the same thing:

![image](https://user-images.githubusercontent.com/37223377/98065927-75cff000-1e0a-11eb-932a-d9ce4f750f53.png)

I propose that instead we only index the original item, not any of the re-exports. I am **not** saying that we don't inline documentation from the original, just that we only store the original in the search index.

_See also: #15723, #24305_

**Comment by jyn514** [comment]
The original is not usually the canonical one, though :/ consider [`std::collections::HashMap`](https://doc.rust-lang.org/std/collections/struct.HashMap.html#), which is actually defined in std::collections::hash::map::HashMap.

I've been wanting `#[canonical]` for a while now and I think this would fit, see https://discord.com/channels/442252698964721669/459149231702278154/771465736190558258 for some discussion. Sorry I don't have a write-up anywhere.

**Comment by jyn514** [comment]
@camelid why did you open a new issue instead of using https://github.com/rust-lang/rust/issues/15723? Is there something else going on?

**Comment by camelid** [comment]
My understanding was that this issue is a subset of what's talked about in #15723, and this way we have a way to track just this part of it. It looks like QuietMisdreavus commented about this at https://github.com/rust-lang/rust/issues/15723#issuecomment-435426599, but it was long enough that I hadn't fully read it before :)

**Comment by jyn514** [comment]
I don't think there's anything in #15723 _not_ covered here. The things listed in the issue are just suggestions for fixing it, but after the discussion in the issue it looks like they won't be the way it ends up being fixed.
