### ISSUE TITLE
Broken links in rustdoc search results

### ISSUE THREAD

**Issue by arora-aman** [rust-lang/rust#78724]
I searched for [`visit_with`](https://doc.rust-lang.org/stable/nightly-rustc/rustc_middle/ty/struct.Binder.html?search=visit_with) and when I select the first result [`rustc_middle::Ty::visit_with`](https://doc.rust-lang.org/stable/nightly-rustc/rustc_middle/type.Ty.html#method.visit_with) I get  the Not Found page.

I expected to see a page containing the method `visit_with`. 

Note: not all links are broken, just some.

**Comment by jyn514** [comment]
The correct url is `rustc_middle/ty/type.Ty.html`, but the search page shows `rustc_middle/type.Ty.html#method.visit_with`. Not sure why.

**Comment by camelid** [comment]
Seems like it might be a bug with type aliases.

**Comment by camelid** [comment]
Note that the URL is wrong *and* the path is wrong. There's no such thing as `rustc_middle::Ty::visit_with` since it's not re-exported. So somewhere there's something awry with the path handling.

**Comment by camelid** [comment]
Note that the links to `Ty` in the trait implementations section on the `Ty` page are correct.

**Comment by apiraino** [comment]
@rustbot ping cleanup

It would be interesting to investigate this issue a bit more in deep to isolate the issue better

**Comment by camelid** [comment]
Prioritized as P-medium for now: it seems people are only running into this in compiler docs and it's not catastrophic.

**Comment by jackh726** [comment]
Going to close this, since it's been 3 years without an MCVE.

Searching `visit_with` doesn't have Ty::visit_with as the first result. Searching directly for that though does not result in a 404.
