### ISSUE TITLE
Nightly 2020-11-04 is missing

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#78732]
https://rust-lang.github.io/rustup-components-history/ and my `rustup update` both indicate that 2020-11-04, which should have been created this morning, is missing.

Cc @rust-lang/infra

**Comment by pietroalbini** [comment]
Should be fixed by https://github.com/rust-lang/promote-release/pull/28.

**Comment by pietroalbini** [comment]
This is fixed for tomorrow's nightly.
