### ISSUE TITLE
Spurious failure trying to checkout the repository

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#78743]
We're experiencing spurious failures trying to checkout repositories on GitHub Actions:

```
Getting action download info
Download action repository 'actions/checkout@v1'
Warning: Failed to download action 'https://api.github.com/repos/actions/checkout/zipball/50fbc622fc4ef5163becd7fab6573eac35f8462e'. Error: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
Warning: Back off 27.717 seconds before retry.
Warning: Failed to download action 'https://api.github.com/repos/actions/checkout/zipball/50fbc622fc4ef5163becd7fab6573eac35f8462e'. Error: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
Warning: Back off 27.21 seconds before retry.
Error: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
```

* https://github.com/rust-lang-ci/rust/runs/1354000264
* https://github.com/rust-lang-ci/rust/runs/1352438239
* https://github.com/rust-lang-ci/rust/runs/1353148003
* https://github.com/rust-lang-ci/rust/runs/1354742853
* https://github.com/rust-lang-ci/rust/runs/1355418041

cc @rust-lang/infra

**Comment by pietroalbini** [comment]
Contacted GitHub Support on this, I see no way for us to mitigate the problem on our end.

**Comment by pietroalbini** [comment]
Another failure: https://github.com/rust-lang-ci/rust/runs/1354742853

**Comment by pietroalbini** [comment]
Another failure: https://github.com/rust-lang-ci/rust/runs/1354742853 (added it to the top issue too).

Enabled debug logging on `rust-lang-ci/rust` and opened https://github.com/rust-lang/rust/pull/78754 as recommended by GitHub Support. Once another build fails we'll probably be able to drill down more into the cause. There is also another report of the same issue available at https://github.com/actions/checkout/issues/376.

**Comment by ohsayan** [comment]
Following on from your comment in https://github.com/actions/checkout/issues/376#issuecomment-722021339 the worst part about this is that it's impossible to repro this

**Comment by pietroalbini** [comment]
Since we didn't see any new error since the last comment, and because debug logging is noisy, I'm disabling debug logging. If the error happens again, someone on the infra team will need to set the `ACTIONS_RUNNER_DEBUG` and `ACTIONS_STEP_DEBUG` secrets to `true` in the [rust-lang-ci/rust](https://github.com/rust-lang-ci/rust/settings/secrets/actions) repository.

**Comment by pietroalbini** [comment]
We haven't seen this in a while, closing the issue.

**Comment by ohsayan** [comment]
@pietroalbini Pretty much the same; we haven't seen this happen lately either
