### ISSUE TITLE
println!() does not panic when STDOUT returns ENOSPC

### ISSUE THREAD

**Issue by GoldsteinE** [rust-lang/rust#78753]
I tried this code:

```rust
fn main() {
    println!("Hello, world!")
}
```

running it as `cargo run > /dev/full` or equivalent.

I expected to see this happen: as STDOUT is now "full" and `write()` syscall returns ENOSPC, `println!()` should panic, as per documentation.

Instead, this happened: `println!()` silently did nothing. Process returned 0 exit code.

### Meta

Bug happens on stable, but is (probably) fixed on nightly
`rustc --version --verbose`:
```
rustc 1.47.0 (18bf6b4f0 2020-10-07)
binary: rustc
commit-hash: 18bf6b4f01a6feaf7259ba7cdae58031af1b7b39
commit-date: 2020-10-07
host: x86_64-unknown-linux-gnu
release: 1.47.0
LLVM version: 11.0
```

**Comment by GoldsteinE** [comment]
Also, as a kinda-unrelated note checking for EBADF in stdio_raw methods (introduced in #26168) not only prevents `println!()` from panicking on closed fd, but also prevents user of `io::stdout()` methods from handling errors.

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=d125440454e0485ef8566428bc404624
IMO, this code should panic, as it explicitly panics on I/O error and I/O error occurs here.

**Comment by sfackler** [comment]
I can confirm that it's fixed on nightly, though I'm not sure from looking at the code what was actually going wrong on 1.47.0.

**Comment by masklinn** [comment]
ENOSPC definitely triggers on 1.52 stable, so this can probably be closed.
