### ISSUE TITLE
Typo in error message: explicitely

### ISSUE THREAD

**Issue by mk12** [rust-lang/rust#78787]
This error message is spelled incorrectly:

https://github.com/rust-lang/rust/blob/5ded394553296d56bb66e925d7001ab3271979ce/compiler/rustc_typeck/src/check/pat.rs#L1503

It should be _explicitly_, not _explicitEly_.

**Comment by ankushduacodes** [comment]
@jonas-schievink I have just made a pull request for this issue.

**Comment by JohnTitor** [comment]
Fixed by #78798.
