### ISSUE TITLE
Rustdoc keeps around documentation for crates that have been renamed or deleted

### ISSUE THREAD

**Issue by RDambrosio016** [rust-lang/rust#78796]
I am working on a decently sized workspace, and i used to have a crate, i have since deleted it, but its documentation stays around because rustdoc does not seem to delete the folders in `target/doc` if the actual crate has been deleted. Rustdoc should check if a dependency/crate actually exists before using its cache in the documentation process and delete it if it isn't.

### Meta

`rustc --version --verbose`:
```
rustc 1.48.0-nightly (f68e08933 2020-09-19)
binary: rustc
commit-hash: f68e08933d8f519a9655934fedebbc509661b219
commit-date: 2020-09-19
host: x86_64-pc-windows-msvc
release: 1.48.0-nightly
LLVM version: 11.0
```

### Reproducing 

1: `cargo init --lib test`
2: `cargo doc`
3: *rename the crate to anything else in Cargo.toml*
4: `cargo doc --open`

**Comment by jyn514** [comment]
I don't think the workspace is related, you'd have the same issue if you renamed the crate.

**Comment by RDambrosio016** [comment]
Yup, can confirm thats the case, it works with renaming too

**Comment by jyn514** [comment]
I'm going to close this in favor of https://github.com/rust-lang/cargo/issues/6783; I don't think rustdoc should be clearing documentation or keep track of state between runs. I'm happy to collaborate with cargo on a fix for this, but I don't think rustdoc can fix it in isolation.
