### ISSUE TITLE
Add a lint for unnecessary by-ref pattern

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#7880]
There are several (many?) instances in rust/src where one has, for example,

```rust
match a_function_returning_option() {
    Some(ref a) => { move_a(a.clone()) }
    None => { do_whatever() }
}
```

The `ref a` is entirely unnecessary; `a` could be moved out in the pattern, saving a clone.

(This would have to be careful to not lint when e.g. `a` is used as a reference in the body, and probably other situations.)

**Comment by steveklabnik** [comment]
Triage: don't think much has changed here.

**Comment by steveklabnik** [comment]
Triage: still no change. Runnable:

```
fn returns_option() -> Option<i32> {
    Some(5)
}

fn do_things(_x: &Option<i32>) {
}

fn main() {
    let foo = returns_option();
    do_things(&foo);
    match foo {
            Some(ref a) => { /* use a */ }
                None => {}
    }
}
```

Given that there are good reasons to use this, and nobody has been clamoring for this lint, I think that we can give this one a close.
