### ISSUE TITLE
On docs search results page, make down/up arrows select search results by auto focusing search field

### ISSUE THREAD

**Issue by Boscop** [rust-lang/rust#78824]
Before, when you opened a rust doc page by a url containing a search query, after the page loaded, you could navigate with down/up arrows through the matched symbols.
Now it doesn't work anymore, you have to use the mouse to click! 
E.g. an url like https://doc.rust-lang.org/nightly/std/?search=scan or https://docs.rs/imgui/0.4.0/imgui/struct.Ui.html?search=set

Maybe the fix is as simple as putting the `autofocus` attribute on the search input, so that the first down arrow press selects the first search result.

CC @jyn514 
@rustbot modify labels: +T-rustdoc

**Comment by camelid** [comment]
I couldn't get `autofocus` to work, so I'm unassigning myself.

**Comment by GuillaumeGomez** [comment]
It was rejected in https://github.com/rust-lang/rust/pull/77333. Closing it then.
