### ISSUE TITLE
macro_rules expansion of `:expr` depends on content (can expand to a statement)

### ISSUE THREAD

**Issue by thepowersgang** [rust-lang/rust#78829]
The following code compiles, despite the macro specifing `$e` to be an expression (and not a statement).

```rust
macro_rules! test_mac {
	// It seems that :expr is parsed as a statement if it starts one?
	(@one $e:expr) => {{
		$e
		0
		}};
}

fn main() {
	let _ = test_mac!(@one if false {} );	//< Allowed
	//let _ = test_mac!(@one ());	//< Errors
}
```

It appears that the contents of an interpolated expression (`:expr` capture) changes how the rest of the expanded macro is parsed.

Not sure if this is a big issue, but is something I noticed while implementing mrustc (see `rustc-1.39.0-src\vendor\indexmap\src\map.rs:342`) for this behaviour in the wild.

### Meta
`rustc --version --verbose`: 
```
rustc 1.47.0 (18bf6b4f0 2020-10-07)
binary: rustc
commit-hash: 18bf6b4f01a6feaf7259ba7cdae58031af1b7b39
commit-date: 2020-10-07
host: x86_64-pc-windows-msvc
release: 1.47.0
LLVM version: 11.0
```

**Comment by jonas-schievink** [comment]
Isn't this just caused by `if` not needing a trailing `;` to be a statement? If you expand the macro manually it behaves the same way:

```rust
fn main() {
	let _ = { if false {} 0 };	//< Allowed
	let _ = { () 0 };	//< Errors
}
```

```
error: expected one of `.`, `;`, `?`, `}`, or an operator, found `0`
  --> src/main.rs:11:15
   |
11 |     let _ = { () 0 };    //< Errors
   |                  ^ expected one of `.`, `;`, `?`, `}`, or an operator
```

**Comment by thepowersgang** [comment]
Maybe it's just my assumption that `:expr` fragments are completely pre-parsed and are always expanded as (effectively) parenthesised expressions.
