### ISSUE TITLE
Tracking Issue for `#![feature(extended_key_value_attributes)]`

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rust#78835]
Implemented in https://github.com/rust-lang/rust/pull/78837.

With this feature arbitrary expressions are supported in values of key-value attributes at parse time.
```
#[my_attr = EXPR]
```
Previously only unsuffixed literals and interpolated expressions (`$expr`) were accepted.

If the attribute in question survives expansion, then the value is still restricted to unsuffixed literals by a semantic check. This restriction may also be relaxed in the future.

**Comment by jyn514** [comment]
On the next bootstrap bump, I plan to switch the standard library from using `doc(include)` to `doc = include_str!`. Unfortunately it does need the bump to test since the syntax changed:

```
error: unexpected token: `include_str`
 --> library/std/src/macros.rs:7:34
  |
7 | #[cfg_attr(not(bootstrap), doc = include_str!("../../core/src/macros/panic.md"))]
  |                                  ^^^^^^^^^^^
  |
  = help: the valid syntax is `#[cfg_attr(condition, attribute, other_attribute, ...)]`
  = note: for more information, visit <https://doc.rust-lang.org/reference/conditional-compilation.html#the-cfg_attr-attribute>
```

**Comment by GuillaumeGomez** [comment]
It doesn't work for "sub attributes". For example:

```
#[doc(alias = $some_expr)]
// or:
#[doc(alias = stringify!(ident))]
```

I'm sending a little fix so it is supported as well.

**Comment by alexschrod** [comment]
I'm having a bit of a weird issue. If I compile the project with [this file](https://github.com/alexschrod/doryen-extra/blob/master/src/base/def_macro.rs) on Windows, everything is fine. But if I compile it on Ubuntu, I get this:
```
$ cargo build
   Compiling doryen-extra v0.1.0 (/home/alex/doryen-extra)
error[E0658]: arbitrary expressions in key-value attributes are unstable
  --> src/base/def_macro.rs:35:77
   |
35 | ...   define_two_property_arithmetic_struct!(@IMPL $name, $uname, $fname, stringify!($name), $field1, $field2, stringify!($field1), strin...
   |                                                                           ^^^^^^^^^^^^^^^^^
   |
  ::: src/base.rs:39:1
   |
39 | define_two_property_arithmetic_struct!(Position, UPosition, FPosition, x, y, ORIGIN, "({}, {})");
   | ------------------------------------------------------------------------------------------------- in this macro invocation
   |
   = note: see issue #78835 <https://github.com/rust-lang/rust/issues/78835> for more information
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0658]: arbitrary expressions in key-value attributes are unstable
  --> src/base/def_macro.rs:35:77
   |
35 | ...   define_two_property_arithmetic_struct!(@IMPL $name, $uname, $fname, stringify!($name), $field1, $field2, stringify!($field1), strin...
   |                                                                           ^^^^^^^^^^^^^^^^^
   |
  ::: src/base.rs:40:1
   |
40 | define_two_property_arithmetic_struct!(Size, USize, FSize, width, height, ZERO, "{}x{}");
   | ----------------------------------------------------------------------------------------- in this macro invocation
   |
   = note: see issue #78835 <https://github.com/rust-lang/rust/issues/78835> for more information
   = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

I don't understand

1) why it's only unstable on Ubuntu and
2) what I'm supposed to do instead. I made my macro that way so that I could do `#[doc = $name_str]` on the value from the `stringify!($name)` invocation, and it was hard enough to get this working as is (`#[doc = stringify!($name)]` did not work), but now my workaround seems to have been made invalid, too, and I honestly don't know where to go from here...

**Comment by petrochenkov** [comment]
@alexschrod 
Could you make a minimized reproduction and build it with `-Z macro-backtrace` as the message suggests? (It will work on stable with env var `RUSTC_BOOTSTRAP=1` set.)

**Comment by petrochenkov** [comment]
I suspect that maybe `paste::item!` turns `stringify!($name)` back into tokens causing the reparsing or something.
The Windows vs Ubuntu difference is entirely unclear to me, I don't see any relevant `#[cfg]`s in the linked file, but maybe they exist somewhere else?

**Comment by alexschrod** [comment]
@petrochenkov You are right that it has to do with `paste::item!`. When I make the macro just
```rust
#[doc = $name_str]
pub struct $name {
}
```
it works fine, but if I make it 
```rust
paste::item! {
    #[doc = $name_str]
    pub struct $name {
    }
}
```
I get the error. Unfortunately, `-Z macro-backtrace` doesn't add anything new:
```
$ RUSTFLAGS="-Z macro-backtrace" cargo check
    Checking bloop v0.1.0 (/home/alex/bloop)
error[E0658]: arbitrary expressions in key-value attributes are unstable
  --> src/main.rs:3:61
   |
1  | / macro_rules! define_two_property_arithmetic_struct {
2  | |     ($name:ident) => {
3  | |         define_two_property_arithmetic_struct!(@IMPL $name, stringify!($name));
   | |                                                             ^^^^^^^^^^^^^^^^^
4  | |     };
...  |
12 | |     };
13 | | }
   | |_- in this expansion of `define_two_property_arithmetic_struct!`
14 |
15 |   define_two_property_arithmetic_struct!(Position);
   |   ------------------------------------------------- in this macro invocation
   |
   = note: see issue #78835 <https://github.com/rust-lang/rust/issues/78835> for more information
   = help: add `#![feature(extended_key_value_attributes)]` to the crate attributes to enable
```
I'm guessing it's because `paste::item` is a proc macro.

**Comment by alexschrod** [comment]
I just had a hunch, and it turns out, this is caused by changes to `paste`. My version on Windows was an old one, and after doing `cargo update`, the behavior was the same on both. I also discovered by trying all versions of `paste` from when it worked to when it didn't that it broke in `paste` v0.1.15 onwards, except for v1.0.3, where it works again, but then breaks in v1.0.4, which is the latest one.

Sorry about the noise.

**Comment by pksunkara** [comment]
What's the path to stabilise this? Just waiting for bug reports? I don't see any blockers.

**Comment by jyn514** [comment]
> What's the path to stabilise this? Just waiting for bug reports? I don't see any blockers currently listed out.

See https://github.com/rust-lang/rust/pull/83366.

**Comment by Nemo157** [comment]
> It doesn't work for "sub attributes". For example:
> 
> ```
> #[doc(alias = $some_expr)]
> // or:
> #[doc(alias = stringify!(ident))]
> ```
> 
> I'm sending a little fix so it is supported as well.

@GuillaumeGomez was there any followup to this? I just encountered a usecase for this and was wondering if it was determined as impossible to support, or might need an RFC?

```rust
#![doc(html_logo_url = ::embed_doc_image::generate_inline_data_url("path/to/image.png"))]
```

**Comment by GuillaumeGomez** [comment]
@petrochenkov said that they'd prefer not to add this on nested attributes. You can always try an RFC though.

**Comment by jyn514** [comment]
@Nemo157 see https://zulip-archive.rust-lang.org/182449tcompilerhelp/24698Allowexpressionfordocaliastoo.html for more discussion
