### ISSUE TITLE
#[track_caller] does nothing on async fns

### ISSUE THREAD

**Issue by ghost** [rust-lang/rust#78840]
I tried:
```rust
#[track_caller]
async fn panic() -> ! {
    panic!();
}

fn main() {
    futures::executor::block_on(async { panic().await });
}
```
I expected the seventh line to be the panic location, but I got this:
```
thread 'main' panicked at 'explicit panic', src/main.rs:3:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
<details>
<summary>With <code>RUST_BACKTRACE=1</code></summary>

```
thread 'main' panicked at 'explicit panic', src/main.rs:3:5
stack backtrace:
   0: std::panicking::begin_panic
             at /rustc/a601302ff0217b91589b5a7310a8a23adb843fdc/library/std/src/panicking.rs:521:12
   1: playground::panic::{{closure}}
             at ./src/main.rs:3:5
   2: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/a601302ff0217b91589b5a7310a8a23adb843fdc/library/core/src/future/mod.rs:80:19
   3: playground::main::{{closure}}
             at ./src/main.rs:7:41
   4: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/a601302ff0217b91589b5a7310a8a23adb843fdc/library/core/src/future/mod.rs:80:19
   5: futures_executor::local_pool::block_on::{{closure}}
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.6/src/local_pool.rs:317:23
   6: futures_executor::local_pool::run_executor::{{closure}}
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.6/src/local_pool.rs:87:37
   7: std::thread::local::LocalKey<T>::try_with
             at /rustc/a601302ff0217b91589b5a7310a8a23adb843fdc/library/std/src/thread/local.rs:272:16
   8: std::thread::local::LocalKey<T>::with
             at /rustc/a601302ff0217b91589b5a7310a8a23adb843fdc/library/std/src/thread/local.rs:248:9
   9: futures_executor::local_pool::run_executor
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.6/src/local_pool.rs:83:5
  10: futures_executor::local_pool::block_on
             at ./.cargo/registry/src/github.com-1ecc6299db9ec823/futures-executor-0.3.6/src/local_pool.rs:317:5
  11: playground::main
             at ./src/main.rs:7:5
  12: core::ops::function::FnOnce::call_once
             at /rustc/a601302ff0217b91589b5a7310a8a23adb843fdc/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
</details>

[Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&code=%23%5Btrack_caller%5D%0Aasync%20fn%20panic()%20-%3E%20!%20%7B%0A%20%20%20%20panic!()%3B%0A%7D%0A%0Afn%20main()%20%7B%0A%20%20%20%20futures%3A%3Aexecutor%3A%3Ablock_on(async%20%7B%20panic().await%20%7D)%3B%0A%7D%0A) (tried using nightly 2020-11-06 a601302ff0217b91589b)

I can achieve the result I expected by implementing a `Future` manually:
```rust
#![feature(never_type)]

use std::{
    future::Future,
    pin::Pin,
    task::{Context, Poll},
};

struct Panic;

impl Future for Panic {
    type Output = !;

    #[track_caller]
    fn poll(self: Pin<&mut Self>, _: &mut Context<'_>) -> Poll<Self::Output> {
        panic!()
    }
}

fn main() {
    futures::executor::block_on(async { Panic.await });
}
```
Output:
```
thread 'main' panicked at 'explicit panic', src/main.rs:21:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
[Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&code=%23!%5Bfeature(never_type)%5D%0A%0Ause%20std%3A%3A%7B%0A%20%20%20%20future%3A%3AFuture%2C%0A%20%20%20%20pin%3A%3APin%2C%0A%20%20%20%20task%3A%3A%7BContext%2C%20Poll%7D%2C%0A%7D%3B%0A%0Astruct%20Panic%3B%0A%0Aimpl%20Future%20for%20Panic%20%7B%0A%20%20%20%20type%20Output%20%3D%20!%3B%0A%0A%20%20%20%20%23%5Btrack_caller%5D%0A%20%20%20%20fn%20poll(self%3A%20Pin%3C%26mut%20Self%3E%2C%20_%3A%20%26mut%20Context%3C%27_%3E)%20-%3E%20Poll%3CSelf%3A%3AOutput%3E%20%7B%0A%20%20%20%20%20%20%20%20panic!()%0A%20%20%20%20%7D%0A%7D%0A%0Afn%20main()%20%7B%0A%20%20%20%20futures%3A%3Aexecutor%3A%3Ablock_on(async%20%7B%20Panic.await%20%7D)%3B%0A%7D%0A)

I noticed that (in the backtrace) the compiler generated a closure (`Generator`?) for the `async fn`, so #74042 may be related.

@rustbot modify labels: A-async-await A-attributes

**Comment by jonas-schievink** [comment]
This seems to be working correctly. The call to `panic` does not actually panic, so the `#[track_caller]` does nothing. `panic` just returns a future that, when polled, will panic.

**Comment by hyd-dev** [comment]
> This seems to be working correctly. The call to `panic` does not actually panic, so the `#[track_caller]` does nothing. `panic` just returns a future that, when polled, will panic.

But I expect it to work better: automatically generates the `Future` I implemented manually.

**Comment by hyd-dev** [comment]
@jonas-schievink Sorry for my wrong interpretation of this issue. But currently `#[track_caller]` on `async fn`s does nothing and compiles without warning, so maybe this is also a `C-enhancement`?

**Comment by Aaron1011** [comment]
Since the call to an `async fn` can never panic (it always returns an `impl Future`), I think forwarding the attribute to the returned `async` closure would make sense.

This would require impementing https://github.com/rust-lang/rust/issues/74042 (if only on nightly), so that the desugaring can forward `#[track_caller]` as needed.

**Comment by hyd-dev** [comment]
Since this issue was classified as a feature request, I edited the title to make it clear.

**Comment by tmandry** [comment]
Forwarding to the poll function does seem reasonable to me.

@anp any thoughts on this?

**Comment by anp** [comment]
Forwarding to the generated future SGTM.
