### ISSUE TITLE
Path has no Default

### ISSUE THREAD

**Issue by Nicholas-Baron** [rust-lang/rust#78858]
Ran into this doing a [pull request](https://github.com/rust-lang/rust/pull/78825).

The `Path` struct has no `impl Default` [documented](https://doc.rust-lang.org/stable/std/path/struct.Path.html), but a value of `Path::new("")` seems to be a good default in my mind. (Update: it is not, I have been corrected)

This may be the incorrect way to ask for such a thing, but I would like to know why there is no `impl Default for Path` and whether there could be one in the near future.

**Comment by jonas-schievink** [comment]
What does an empty path mean? Does it refer to the current directory?

**Comment by Nicholas-Baron** [comment]
@jonas-schievink Currently, the empty path refers to (at least on Linux) a nonexistent file or directory.
Code to test this
```rust
use std::path::Path;

fn main() {
    let path = Path::new("");

    println!("Empty string path");
    println!("{}", path.display());
    println!("Exists: {}", path.exists());
    match path.canonicalize() {
        Ok(p) => println!("{}", p.display()),
        Err(e) => println!("error {}", e),
    }
}
```

**Comment by jonas-schievink** [comment]
Hmm, I'm not sure why it would be a good default then

**Comment by Nicholas-Baron** [comment]
So the question shifts from "is `""` a good default" to "is there any *good* default for `Path`". (Second part of initial issue)
Even if there are multiple candidates, we can simply select the best of them and make that be the `impl Default for Path`.

**Comment by CryZe** [comment]
If there's no clear default, then it probably should not have a Default impl at all.

**Comment by Nicholas-Baron** [comment]
This issue seems to have been just me exploring why there is no `impl Default for Path`.
In summary,
1. `""` is an invalid path.
2. The current directory can be accessed differently (see [std::env::current_dir()](https://doc.rust-lang.org/stable/std/env/fn.current_dir.html)).
3. The root directory is unsuitable (Windows does not have a concept of "root", usually protected).
4. Any other directory would be arbitrary and should use `Path::new`

I thank everyone for their contributions and apologize for wasting time.
