### ISSUE TITLE
Add support for --nocapture to compiletest

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#78850]
Right now, the only way to get output from a test that succeeds _or_ fails is to use `-vv`. It would be nice to have a way to show all output from a test for help debugging, without having to look at hundreds of logs about rustbuild caching.

**Comment by ehuss** [comment]
You can set the environment variable `RUST_TEST_NOCAPTURE` which is the equivalent of `--nocapture`.  I think a CLI option would be pretty easy to add.

**Comment by jyn514** [comment]
RUST_TEST_NOCAPTURE is not printing the debug logging :/

**Comment by clubby789** [comment]
Closing as `--nocapture` has been supported for some time
