### ISSUE TITLE
Add #[track_caller] to slice::copy_from_slice

### ISSUE THREAD

**Issue by daniel5151** [rust-lang/rust#78900]
In this trivial case:

```rust
fn main() {
    let mut buf = [0; 16];
    buf.copy_from_slice(&[1, 2, 3]);
}
```

The current panic message is: `thread 'main' panicked at 'source slice length (3) does not match destination slice length (16)', /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/slice/mod.rs:2517:13`

If `#[track_caller]` is added to `slice::copy_from_slice`, the panic message could instead be: `thread 'main' panicked at 'source slice length (3) does not match destination slice length (16)', example/src/main.rs:3:9`

On a related note, `slice::clone_from_slice` would also benefit from a `#[track_caller]` annotation as well.

### Meta

`rustc --version --verbose`:
```
rustc 1.49.0-nightly (1eaadebb3 2020-10-21)
binary: rustc
commit-hash: 1eaadebb3dee31669c7649b32747381d11614fae
commit-date: 2020-10-21
host: x86_64-unknown-linux-gnu
release: 1.49.0-nightly
LLVM version: 11.0
```

<details><summary>Backtrace</summary>
<p>

```
stack backtrace:
   0: rust_begin_unwind
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:475
   1: core::panicking::panic_fmt
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/panicking.rs:85
   2: core::slice::<impl [T]>::copy_from_slice::len_mismatch_fail
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/slice/mod.rs:2510
   3: core::slice::<impl [T]>::copy_from_slice
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/slice/mod.rs:2517
   4: playground::main
             at ./src/main.rs:3
   5: core::ops::function::FnOnce::call_once
             at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/ops/function.rs:227
```

</p>
</details>

**Comment by Nugine** [comment]
This issue has been solved by
+ https://github.com/rust-lang/rust/pull/90306

**Comment by daniel5151** [comment]
Ah, so it has!

Well, as OP, I'll just go ahead and close the issue as resolved then :)
