### ISSUE TITLE
Fix cause of link failures in CI that necessitates ignore-32bit in run-make tests

### ISSUE THREAD

**Issue by tgnottingham** [rust-lang/rust#78911]
Some run-make tests require an `ignore-32bit` directive as a workaround for link failures that occur during CI. #76256 and #77901 added or modified tests to include this directive in order to avoid at least this error: `arm-none-eabi-gcc: error: unrecognized command line option '-m64'`.

I assume that this shouldn't be necessary, and that there is actually some deficiency in our CI build system that we can fix.

**Comment by tblah** [comment]
This also affects 64-bit RISC-V
