### ISSUE TITLE
What does compare-mode=nll do these days?

### ISSUE THREAD

**Issue by guswynn** [rust-lang/rust#78915]
See https://github.com/rust-lang/rust/pull/76765#issuecomment-724395274

what does compare-mode=nll actually represent these days? I thought nll was long-since stable

cc @tmandry

**Comment by bjorn3** [comment]
I could find two differences:

```
$ rg "BorrowckMode::Mir|\.migrate|suppress_errors" compiler
compiler/rustc_middle/src/ty/context.rs
1336:        self.borrowck_mode().migrate()
1365:            return BorrowckMode::Mir;

compiler/rustc_infer/src/infer/lexical_region_resolve/mod.rs
45:        RegionckMode::Erase { suppress_errors: false } => {
56:        RegionckMode::Erase { suppress_errors: true } => {

compiler/rustc_infer/src/infer/mod.rs
105:        suppress_errors: bool,
124:            BorrowckMode::Migrate => RegionckMode::Erase { suppress_errors: false },
127:            BorrowckMode::Mir => RegionckMode::Erase { suppress_errors: true },

compiler/rustc_mir/src/borrow_check/mod.rs
1118:                ) if { tcx.migrate_borrowck() && this.borrow_set.contains(&location) } => {

compiler/rustc_data_structures/src/sso/map.rs
528:        self.ssomap.migrate_if_full();

compiler/rustc_session/src/config.rs
483:            BorrowckMode::Mir => false,
1568:        "mir" => BorrowckMode::Mir,
```

First regionck being skipped instead of given the opportunity to report errors:

https://github.com/rust-lang/rust/blob/85fbf49ce0e2274d0acf798f6e703747674feec3/compiler/rustc_infer/src/infer/lexical_region_resolve/mod.rs#L45-L59

Second a fix for https://github.com/rust-lang/rust/issues/56254 ([NLL] prohibit "two-phase borrows" with existing borrows?)

https://github.com/rust-lang/rust/blob/c4fe25d8613a32dcd71e5258c22ff5685f12d4c3/compiler/rustc_mir/src/borrow_check/mod.rs#L1118-L1134

**Comment by guswynn** [comment]
@bjorn3 interesting, in https://github.com/rust-lang/rust/pull/76765, `src/test/ui/issues/issue-76547.nll.stderr` is materially different (and worse!) output in 'mir' instead of 'migrate'. I am inclined to think that, because nll is quite old at this point, and migrate is the default, we should perhaps get rid of the 2 modes and just use whatever codepaths are triggered by Migrate?(well, compare-mode=polonious usually sets -Zpolonious AND -borrowck=mir so perhaps we can just trigger the non-migrate paths with -Zpolonius?)

**Comment by bjorn3** [comment]
Regionck is an artifact of the fact that the old ast borrowck used lexical lifetimes. With polonius it doesn't even make sense to talk about regions anymore.

**Comment by guswynn** [comment]
@bjorn3 should we get rid of the distinction between "migrate" and "nll", it may say ci time and also will eventually be entirely replaced by polonious, as far as i can tell

**Comment by bjorn3** [comment]
Migrate is the current behavior and nll is what it should become I think.

**Comment by jackh726** [comment]
Going to close this since NLL is tracked elsewhere.
