### ISSUE TITLE
RUSTC_LOG shows output prefixed with `2:rustc`

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#78931]
For example:

```
$ RUSTC_LOG=rustc_interface=info rustc +stage1 tcp.rs --crate-type lib
2:rustc INFO rustc_interface::passes 0 parse sess buffered_lints
2:rustc INFO rustc_interface::passes Pre-codegen
2:rustcTy interner             total           ty lt ct all
2:rustc    Adt               :   1078 81.3%,  0.0%   0.0%  0.0%  0.0%
2:rustc    Array             :      1  0.1%,  0.0%   0.0%  0.0%  0.0%
2:rustc    Slice             :      1  0.1%,  0.0%   0.0%  0.0%  0.0%
2:rustc    RawPtr            :      2  0.2%,  0.0%   0.0%  0.0%  0.0%
2:rustc    Ref               :      4  0.3%,  0.1%   0.1%  0.0%  0.0%
2:rustc    FnDef             :      0  0.0%,  0.0%   0.0%  0.0%  0.0%
2:rustc    FnPtr             :     76  5.7%,  0.0%   0.0%  0.0%  0.0%
2:rustc    Placeholder       :      0  0.0%,  0.0%   0.0%  0.0%  0.0%
2:rustc    Generator         :      0  0.0%,  0.0%   0.0%  0.0%  0.0%
2:rustc    GeneratorWitness  :      0  0.0%,  0.0%   0.0%  0.0%  0.0%
2:rustc    Dynamic           :      3  0.2%,  0.0%   0.0%  0.0%  0.0%
2:rustc    Closure           :      0  0.0%,  0.0%   0.0%  0.0%  0.0%
2:rustc    Tuple             :     13  1.0%,  0.0%   0.0%  0.0%  0.0%
2:rustc    Bound             :      0  0.0%,  0.0%   0.0%  0.0%  0.0%
2:rustc    Param             :    146 11.0%,  0.0%   0.0%  0.0%  0.0%
2:rustc    Infer             :      2  0.2%,  0.1%   0.0%  0.0%  0.0%
2:rustc    Projection        :      0  0.0%,  0.0%   0.0%  0.0%  0.0%
2:rustc    Opaque            :      0  0.0%,  0.0%   0.0%  0.0%  0.0%
2:rustc    Foreign           :      0  0.0%,  0.0%   0.0%  0.0%  0.0%
2:rustc                  total   1326         0.2%   0.1%  0.0%  0.0%
2:rustcInternalSubsts interner: #437
2:rustcRegion interner: #355
2:rustcStability interner: #1
2:rustcConst Stability interner: #0
2:rustcAllocation interner: #0
2:rustcLayout interner: #0
```

There are two issues here:
1. Is `2:rustc` actually helpful? All the code runs in the same thread with the same name, so it doesn't add any more info
2. There's no space between the output and the header, so it's hard to read the logs.

cc @hawkw, @oli-obk

**Comment by hawkw** [comment]
I believe the `tracing-tree` crate, which `rustc` is using, provides methods for [disabling thread IDs](https://docs.rs/tracing-tree/0.1.6/tracing_tree/struct.HierarchicalLayer.html#method.with_thread_ids) and [thread names](https://docs.rs/tracing-tree/0.1.6/tracing_tree/struct.HierarchicalLayer.html#method.with_thread_names) when constructing its layer, so it should be possible to turn this off. 

I _believe_ the missing space is probably a bug in that crate, so I'd [report it upstream](https://github.com/davidbarsky/tracing-tree/issues). It's _possible_ this was the intended formatting, you'd probably need to ask @davidbarsky to be sure.

**Comment by jyn514** [comment]
> I believe the tracing-tree crate, which rustc is using, provides methods for disabling thread IDs and thread names when constructing its layer, so it should be possible to turn this off.

Thanks, I'll do that :)
