### ISSUE TITLE
Doc-examples using `#[doc]` do not have triple backticks stripped before being compiled

### ISSUE THREAD

**Issue by Nezeky** [rust-lang/rust#78964]
Nightly code fails to compile.

### Code

I tried this code:

```rust
#![cfg_attr(
    feature = "std",
    doc = r#"
        ```rust,no_run
        // Lots of rust code
        ```
    "#
)]
```

I expected to see this happen: Compiling and working like it does on stable.

Instead, compiler says:

```
error: unknown start of token: `
   |
24 |     ```
   |     ^
   |
help: Unicode character '`' (Grave Accent) looks like ''' (Single Quote), but it is not
   |
24 |     '``
   |     ^
```

### Version it worked on
It most recently worked on: rustc 1.49.0-nightly (ffa2e7ae8 2020-10-24)

### Version with regression

`rustc --version --verbose`:
```
rustc 1.49.0-nightly (cf9cf7c92 2020-11-10)
binary: rustc
commit-hash: cf9cf7c923eb01146971429044f216a3ca905e06
commit-date: 2020-11-10
host: x86_64-unknown-linux-gnu
release: 1.49.0-nightly
```

<!--
If you know when this regression occurred, please add a line like below, replacing `{channel}` with one of stable, beta, or nightly.

@rustbot modify labels: +regression-from-stable-to-{channel} -regression-untriaged
-->

**Comment by jyn514** [comment]
cc @GuillaumeGomez , I think https://github.com/rust-lang/rust/pull/76154 broke this.

**Comment by GuillaumeGomez** [comment]
Absolutely!

@Nezeky: Since #76154, we don't allow to "align" comments anymore. You might want to take a look at this [blog post](https://blog.guillaume-gomez.fr/articles/2020-11-11+New+doc+comment+handling+in+rustdoc).

I'll close this issue and add the label "wont-fix" then.

**Comment by juliankrieger** [comment]
@GuillaumeGomez How is one sup[posed to combine `#![cfg_attr(not(feature = "xxx"), doc = r#"` with `no_run` when backtick compilation no longer works in that case?

**Comment by juliankrieger** [comment]
I'm afraid I don't quite understand, can you provide a tiny example that works with `no_run`? Thanks!

**Comment by jyn514** [comment]
@juliankrieger
```
#![doc = r#"
```rust,no_run
// Lots of rust code
```
"#]
```
