### ISSUE TITLE
Tracking Issue for {BTreeMap,BTreeSet}::retain

### ISSUE THREAD

**Issue by mbrubeck** [rust-lang/rust#79025]
This is a tracking issue for `BTreeMap::retain` and `BTreeSet::retain` (part of rust-lang/rfcs#1338).
The feature gate for the issue is `#![feature(btree_retain)]`.

### Unstable API

```rust
impl<T: Ord> BTreeSet<T> {
    pub fn retain<F>(&mut self, mut f: F) where F: FnMut(&T) -> bool;
}

impl<K: Ord, V> BTreeMap<K, V> {
    pub fn retain<F>(&mut self, mut f: F) where F: FnMut(&K, &mut V) -> bool;
}
```

### Steps

- [x] Implement the RFC
- [x] FCP
- [ ] Adjust documentation
- [ ] Stabilization PR

### Unresolved Questions

* Is the performance of the current implementation (based on `drain_filter`) good enough to be useful?  Concern raised in [this comment](https://github.com/rust-lang/rust/issues/70530#issuecomment-726983033).

### Implementation history

* Initial implementation: #79026

**Comment by joshtriplett** [comment]
We discussed this in today's @rust-lang/libs meeting. We'd like to see a comment added documenting the performance characteristics of this (as well as a corresponding update to `drain_filter`), and suggesting that this might not be what you want if you're removing a substantial number of elements.

Beyond that documentation, though, we'd be happy to see this stable.

@rfcbot merge
