### ISSUE TITLE
Incorrect "unreachable pattern" warning on nightly

### ISSUE THREAD

**Issue by alex** [rust-lang/rust#79048]
I tried this code:

```rust
pub fn parse_data(data: &[u8]) -> u32 {
    match data {
        b"" => 1,
        _ => 2,
    }
}

fn main() {
    println!("{}", parse_data(b"asd"))
}
```

It produces the following, incorrect, warning:

```
warning: unreachable pattern
 --> src/main.rs:4:9
  |
4 |         _ => 2,
  |         ^
  |
  = note: `#[warn(unreachable_patterns)]` on by default
```

however, the output is `2` so it's clearly incorrect

### Meta

`rustc --version`:
```
1.50.0-nightly (2020-11-13 74f7e32f43b5fb0f8389)
```

**Comment by jonas-schievink** [comment]
Segfault:

```rust
fn parse_data(data: &[u8]) -> u32 {
    match data {
        b"" => 1,
    }
}

fn main() {
    let val = parse_data(b"oops");
    
    println!("{}", val);
}
```

**Comment by jonas-schievink** [comment]
cc @Nadrieril

**Comment by sfackler** [comment]
Fails to compile on both stable and beta:

```
error[E0004]: non-exhaustive patterns: `&[_, ..]` not covered
 --> src/main.rs:2:11
  |
2 |     match data {
  |           ^^^^ pattern `&[_, ..]` not covered
  |
  = help: ensure that all possible cases are being handled, possibly by adding wildcards or more match arms
  = note: the matched value is of type `&[u8]`
```

**Comment by alex** [comment]
I'm bisecting now.

**Comment by alex** [comment]
f58ffc93815f76576eb56df4bdeec2fe8f12b766 is the regressing commit.

**Comment by jyn514** [comment]
Might be https://github.com/rust-lang/rust/pull/78072 ?

**Comment by alex** [comment]
I'm far from a `rustc` expert, but based on the PR title and the fact that the changes to `compiler/rustc_mir_build/src/thir/pattern/const_to_pat.rs` specifically impact a special-case for bytes literals, I think that's   a very likely candidate.

**Comment by estebank** [comment]
Purely based of the description, https://github.com/rust-lang/rust/pull/78072 seems like a likely culprit. CC @Nadrieril, would you be able to take a look?

**Comment by LeSeulArtichaut** [comment]
Assigning `P-critical` [as discussed as part of the Prioritization WG procedure](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/I-prioritize.20.2379048.20Incorrect.20.22unreachable.20pattern.22.20warning.E2.80.A6)

**Comment by Nadrieril** [comment]
Ok, I can comfirm it's the `const_to_pat` expansion that's the problem, because it affects both exhaustiveness checking and codegen. I however am not familiar at all with `const_to_pat`. The linked PR was based on https://github.com/rust-lang/rust/pull/77390 by @oli-obk, who is the one who wrote the `const_to_pat` bit.

**Comment by Nadrieril** [comment]
I'm confused. The comment in `const_to_pat` says:
> The typechecker has a special case for byte string literals, by treating them as slices. `b"foo"` produces a `&[u8; 3]`.

If that's the case then the `b""` pattern should behave exactly like `&[]`. But it doesn't: if I replace one by the other then the match behaves correctly. Since there's no special-casing of `u8` anywhere in `rustc_mir_build` I would think the problem occurs before `const_to_pat` :/

**Comment by Nadrieril** [comment]
Oh I know, the pattern gets assigned type `&[u8; 0]`, which has a single element so is found exhaustive:
```
Pat {
    ty: &[u8],
    span: src/test/ui/pattern/usefulness/guards-not-exhaustive.rs:7:9: 7:12 (#0),
    kind: Deref {
        subpattern: Pat {
            ty: [u8; 0],
            span: src/test/ui/pattern/usefulness/guards-not-exhaustive.rs:7:9: 7:12 (#0),
            kind: Slice {
                prefix: [],
                slice: None,
                suffix: [],
            },
        },
    },
},

```

**Comment by Nadrieril** [comment]
So, I think there's nothing that can be done in `const_to_pat`. The reason is that the following needs to be accepted:
```rust
fn parse_data(data: &[u8; 0]) -> u8 {
    match data {
        b"" => 1,
    }
}
```
And the following rejected:
```rust
fn parse_data(data: &[u8]) -> u8 {
    match data {
        b"" => 1,
    }
}
```
Thus we need to know the type of `data`. So we need to drop the assumption I mentioned above I'm afraid :(. That's a problem because this assumption is quite pervasively used in `_match` :/

**Comment by Nadrieril** [comment]
Actually I want to blame typechecking here. If you have some magic hidden polymorphism where a pattern can have two different types, it would be cool if tck could hide it from the rest of the compiler and assign a consistent type to things. I have zero idea how to go about doing that.

**Comment by oli-obk** [comment]
typeck has magic, I found it when I was doing the PR you linked. Looking for it right now. Will have a link in a second

**Comment by oli-obk** [comment]
https://github.com/rust-lang/rust/blob/30e49a9ead550551e879af64ba91a0316da1c422/compiler/rustc_typeck/src/check/pat.rs#L393-L404

has seriously thrown me off before. I tried to figure out a general solution not specific to literals (so we could also allow this for constants), but all of this is extremely subtle. Maybe we can indeed make `const_to_pat` figure out this situation and add a special case to handle this

**Comment by Nadrieril** [comment]
It shouldn't be the responsibility of `const_to_pat`. `b"x"` is a pattern of a polymorphic type; type inference should decide which and tell us, but currently it tells us the wrong one sometimes.
If `const_to_pat` wants to handle that, it will essentially have to redo a bit of type inference: probably pass around the type of the scrutinee and use that to decide which type the `b""` pattern should get.

**Comment by oli-obk** [comment]
So... typeck can't modify the type of `lt` here. One solution would be to put this information into the [`TypeckResults`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/context/struct.TypeckResults.html) and then have `const_to_pat` pick it up.

**Comment by Nadrieril** [comment]
Btw it's not just size 0, here's another fun one:
```rust
fn parse_data(data: &[u8]) -> u8 {
    match data {
        b"aaa" => 1,
        &[_, _, _] => 1,
    }
}
```
This is also detected exhaustive, and segfaults on `parse_data(b"x")`.

**Comment by oli-obk** [comment]
yea, this is for all sizes, but only for byte string literals. Let's move this chat to zulip? https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/exhaustiveness.20is.20broken.20.2379048/near/216744730
