### ISSUE TITLE
Can't use download-ci-llvm any more

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#79071]
Enabling download-ci-llvm used to work just fine for me, until today.

After rebasing on top of 75042566d1c90d912f22e4db43b6d3af98447986 , doing anything with rustc beyond stage 1 fails:

```
$ ./x.py build
[...]
Building stage1 std artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
[...]
error while loading shared libraries: libLLVM-11-rust-1.49.0-nightly.so: cannot open shared object file: No such file or directory
```

To verify it's not due to some caching issue caused by my experiments in #79043 that temporarily turned the feature off I deleted the entire build directory. It correctly downloaded the stage0 and llvm artifacts, but still failed when trying to run stage1 rustc.

**Comment by est31** [comment]
The last commit I was on was 361c4ea22486557ec50c4fc6a93d60e7476ecbea

So the regression is somewhere in this range: 361c4ea22486557ec50c4fc6a93d60e7476ecbea...75042566d1c90d912f22e4db43b6d3af98447986

**Comment by est31** [comment]
cc @Mark-Simulacrum maybe cause was #78986 ?

**Comment by Mark-Simulacrum** [comment]
Indeed. Posted https://github.com/rust-lang/rust/pull/79074 to fix this.
