### ISSUE TITLE
[Question] Miri is in "test pass" state but not available in latest nightly

### ISSUE THREAD

**Issue by hyd-dev** [rust-lang/rust#79129]
Miri is in "test pass" state in https://rust-lang-nursery.github.io/rust-toolstate/ since rust-lang/rust#78990 and rust-lang/rust#78937 has been closed. Also I didn't found [any new issue from **`@rust-highfive`** about Miri in `rust-lang/rust`](https://github.com/rust-lang/rust/issues/created_by/rust-highfive), so I assume Miri should build from the `master` branch of it.
However, Miri [is not available](https://rust-lang.github.io/rustup-components-history/) in the latest nightly (`nightly-2020-11-17`, rust-lang/rust@f5230fbf76bafd86ee4376a0e26e551df8d17fec) from `rustup`. rust-lang/rust@f5230fbf76bafd86ee4376a0e26e551df8d17fec already contains rust-lang/rust#78990. Actually Miri is missing since `nightly-2020-11-10`, and is still missing even rust-lang/rust#78990 has been merged.

I can't find any additional information about Miri in the latest nightly. What's going on with it?

*Edit: I mentioned the wrong PR. It should be #78990 instead of `#78890`.*

**Comment by RalfJung** [comment]
Cc @rust-lang/infra any idea why Miri is missing from `rustup`?

**Comment by RalfJung** [comment]
The log at https://github.com/rust-lang-ci/rust/runs/1410170664 looks good in terms of tests, but one thing is strange:

> {"nomicon":"test-pass","edition-guide":"test-pass","cargo-miri":"test-fail","book":"test-pass","embedded-book":"test-pass","rust-by-example":"test-pass","miri":"test-pass","reference":"test-pass","rustbook":"test-fail","rls":"test-pass","rustfmt":"test-pass"}[master beb7213] (linux CI update)

Notice the "test-fail" for "cargo-miri". However, I don't think anything actually cares about that test state, so I am not sure if this is actually a problem.

I guess something is going wrong when doing the nightly release (Miri has special logic there to avoid shipping when tests fail), but I do not know how to access the logs for that.

**Comment by pietroalbini** [comment]
Thanks for the report! This is a bug in our release process: https://github.com/rust-lang/promote-release/issues/30

> I guess something is going wrong when doing the nightly release (Miri has special logic there to avoid shipping when tests fail), but I do not know how to access the logs for that.

Release process logs are not available publicly unfortunately :(

**Comment by hyd-dev** [comment]
rust-lang/promote-release#30 has been closed, but Miri is still not available due to #79176. Maybe Miri will be available tomorrow and this can be closed then.
