### ISSUE TITLE
Enum type aliases don't work with default parameter

### ISSUE THREAD

**Issue by marcospb19** [rust-lang/rust#79136]
Hi! I'm writing a custom `File` and `FileType` representation. It has a generic field called `extra`, so that users can attach any data into this recursive structure.

For example, you might want to attach a `String` to represent each file contents, maybe custom flags, open options, mode options, really anything that might match your needs.

I needed this generic field for some projects of mine, but I expect that usually users won't need it, so `T` (generic type) will be `()`.

Then I thought to myself, I should use type aliases with default parameters! Tried [this](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=79c49d5dd55a5df17aa15e32489d40f4):

```rust
#[allow(dead_code)]
mod my_crate {
    mod module {
        pub struct File<T> {
            path: std::path::PathBuf,
            file_type: FileType<T>,
            extra: T,
        }

        pub enum FileType<T> {
            Regular,
            Directory(Vec<File<T>>),
            Symlink,
        }
    }
    pub type FileType<T = ()> = module::FileType<T>;
    pub type File<T = ()> = module::File<T>;
}

// Crate user code, fails
fn main() {
    use my_crate::FileType::*;

    let var = Regular;
    if let Regular = var {
        println!("ok");
    }
}
```

Expected it to work and assume `T = ()`, but got a compile error inside of `main` function:
```
error: src/main.rs:21: unresolved import `my_crate::FileType`
error: src/main.rs:21: `FileType` is a type alias, not a module
```

[Here](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=8e49b5162d1baa7948fcd5c2536b9eac) are some alternatives to compile that `main` function:

```rust
fn main() {
    // Explicit
    let _file = my_crate::FileType::<()>::Regular;

    // Another type alias
    type OtherFileType = my_crate::FileType<()>;
    let _file = OtherFileType::Regular;

    // Type anotations
    let _file: my_crate::FileType<()> = my_crate::FileType::Regular;
}
```

Although this compiles, the user needed to specify explicitly the the unit type `()`, so my default parameter didn't helped at all.

I expected `()` to be "automatically infered".

#### Meta
Confirmed in 1.47 stable, 1.48 beta and 1.50 nightly.

**Comment by marcospb19** [comment]
Maybe a more reasonable example:

```rust
fn main() {
    use my_crate::FileType;
    let var = FileType::Regular;
}
```
Which fails for the same reason, but I think that it should work! Is this expected?

**Comment by dzmitry-lahoda** [comment]
@marcospb19 is it still not solved with current rust?

**Comment by marcospb19** [comment]
@dzmitry-lahoda unfortunately no, I expected type aliases to work like this, but maybe it doesn't have this feature.

So I think that this ""bug report"" turned into a ""feature suggestion"" because maybe there's no bug here, it's just the expected.

**Comment by marcospb19** [comment]
I'm closing this because my description about the "issue" was SUPER confusing and innacurate.

**Comment by dzmitry-lahoda** [comment]
@marcospb19 so you cannot read above rust code to be clear what issue is and closing issue is way to ask simpler example you can comprehend?

**Comment by marcospb19** [comment]
@dzmitry-lahoda I saw you deleted an comment, here's a better example:

```rust
fn main() {
    type MyOption<T = i32> = Option<T>;
    // Does not compile, requires type hint
    let _ = MyOption::default();
}
```

I will ask on Zulip about if this was expected to work, maybe I got type aliases wrong all this time, then I'll open another issue, as this one could be resumed to 4 lines of code.
