### ISSUE TITLE
variant_count intrinsic is evaluated incorrectly in generic code

### ISSUE THREAD

**Issue by tmiasko** [rust-lang/rust#79137]
For example:

```rust
#![feature(variant_count)]

fn a<T>() -> usize {
    let v = [0u8; std::mem::variant_count::<T>()];
    std::mem::size_of_val(&v)
}

fn b() -> usize {
    let v = [0u8; std::mem::variant_count::<Result<(), ()>>()];
    std::mem::size_of_val(&v)
}

fn main() {
    println!("{}", a::<Result<(), ()>>());
    println!("{}", b());
}
```

```console
$ rustc a.rs
warning: cannot use constants which depend on generic parameters in types
 --> a.rs:4:19
  |
4 |     let v = [0u8; std::mem::variant_count::<T>()];
  |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(const_evaluatable_unchecked)]` on by default
  = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
  = note: for more information, see issue #76200 <https://github.com/rust-lang/rust/issues/76200>

warning: 1 warning emitted

$ ./a
0
2
```

Similar to #73976, but with a different intrinsic.

**Comment by lcnr** [comment]
We can probably just put `ensure_monomorphic` call in form if that if statement.

https://github.com/rust-lang/rust/blob/e0ef0fc392963438af5f0343bf7caa46fb9c3ec3/compiler/rustc_mir/src/interpret/intrinsics.rs#L79

A more precise way to implement this would be to exhaustively match on `tp_ty` and forbid `ty::Projection`, `ty::Opaque`, `ty::Param`, `ty::Bound`, `ty::Placeholder` and `ty::Infer` here. This way we the intrinsic can still be evaluated for `Option<T>` which is probably desirable.

**Comment by wusyong** [comment]
@lcnr Hello, I'm interested in taking the desirable approach. How is the arm for variants like `ty::Projection` should be handled? Which macro is more appropriate for this situation?

**Comment by lcnr** [comment]
I quickly grepped for `throw.*TooGeneric` and ended up with `throw_inval!(TooGeneric)` here.
That only helps once you know what to search for though.
