### ISSUE TITLE
Rustc hangs on recursive traits

### ISSUE THREAD

**Issue by DutchGhost** [rust-lang/rust#79168]
I tried this code:

```rust
#![feature(optin_builtin_traits)]

mod sealed {
    pub
    auto trait Trait
    where
        [&'static Self; 0]: Trait
    {}
}
```

I expected to see this happen: When compiling with stable, it should tell me I need to use a nightly version of the compiler as Im using a `#![feature]`, and then abort compilation. When compiling with nightly, I expect some to see some overflow in the requirements, or hitting the recursion limits.

Instead, this happened: Rustc never stops compilation, instead it hangs and increasingly consumes memory.

### Meta

`rustc --version --verbose`:
```
rustc 1.47.0 (18bf6b4f0 2020-10-07)
rustc 1.49.0-nightly (1773f60ea 2020-11-08)
```

<details><summary>Backtrace</summary>
<p>

```
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> src\main.rs:1:1
  |
1 | #![feature(optin_builtin_traits)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

^C  Building [                                                           ] 0/1:
```

</p>
</details>

**Comment by DutchGhost** [comment]
Edit:
The can be achieved _without_ auto traits:
```
pub trait Trait<A: ?Sized = Self>
where
    for<'a> A: Trait<&'a Self>,
    for<'a> [&'a Self; 0]: Trait<Self>
{
}

impl <U, T> Trait<U> for T
where
    for<'a> T: Trait<&'a U>,
    for<'a> [&'a Self; 0]: Trait<U>
{}
```

**Comment by apiraino** [comment]
Assigning `P-high` as discussed as part of the [Prioritization Working Group procedure](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/I-prioritize.20.2379168.20Rustc.20hangs.20on.20recursive.20traits) and removing `I-prioritize`.

**Comment by ThePuzzlemaker** [comment]
The regression happened between nightly 2019-01-04 and 2019-01-03. I don't currently have the means to search further than that, though I'm thinking it's probably between a602f13f02a and ae167c91aa9.

**Comment by Dylan-DPC** [comment]
The compilation doesn't hang any more and it compiles as expected
