### ISSUE TITLE
Chained comparison error doesn't distinguish between `<` and `>`

### ISSUE THREAD

**Issue by varkor** [rust-lang/rust#79161]
```rust
fn main() {
    foo<<S as T>::V>();
}
```
produces the help message:
```
help: use `::<...>` instead of `<...>` to specify type or const arguments
   |
16 |     foo<<S as T::>::V>();
   |                ^^
```
This is clearly invalid: we should be distinguishing between `<` and `>` when making this suggestion.

**Comment by estebank** [comment]
the `<S as T>` confuses the parser as it doesn't account for `as` for recovery, I think it is being parsed as `(foo << S) as <TYPE HERE>`.
