### ISSUE TITLE
thread 'rustc' panicked at [...] src/librustc_codegen_llvm/metadata.rs:75:22 (FromUtf8Error)

### ISSUE THREAD

**Issue by gendx** [rust-lang/rust#79197]
### Code

I simply have a `Cargo.toml` file which transitively depends on the `futures-util v0.3.8` crate. That crate failed to compile before my code even started to be compiled.

Extract of my `Cargo.toml` (including only crates that might be relevant to `futures-util`).

```
...

[dependencies]
futures = "0.3.4"
hyper = "0.13.7"
reqwest = { version = "0.10.7", features = ["cookies"] }
tokio = { version = "0.2.22", features = ["macros", "signal", "time"] }
...
```

### Meta

`rustc --version --verbose`:
```
$ rustc --version --verbose
rustc 1.47.0 (18bf6b4f0 2020-10-07)
binary: rustc
commit-hash: 18bf6b4f01a6feaf7259ba7cdae58031af1b7b39
commit-date: 2020-10-07
host: x86_64-unknown-linux-gnu
release: 1.47.0
LLVM version: 11.0
```

### Error output

```
$ cargo check --release --jobs 6
    Updating crates.io index
[...]
    Checking futures-util v0.3.8
thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: FromUtf8Error { bytes: [0, 4, 154, 49, 168, 10, 66, 36], error: Utf8Error { valid_up_to: 2, error_len: Some(1) } }', src/librustc_codegen_llvm/metadata.rs:75:22
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.47.0 (18bf6b4f0 2020-10-07) running on x86_64-unknown-linux-gnu

note: compiler flags: -C opt-level=3 -C embed-bitcode=no --crate-type lib

note: some of the compiler flags provided by cargo are hidden

error: could not compile `futures-util`.
```

<details><summary><strong>Backtrace</strong></summary>
<p>

I unfortunately couldn't reproduce the bug, likely due to the fact that crates were compiled in parallel (`--jobs 6`) and in a non-deterministic order.
Simply running `cargo check --release --jobs 6` again succeeded.

```
N/A
```

</p>
</details>

**Comment by jyn514** [comment]
@gendx are you in an unusual locale? You can check on Linux/Mac with `echo $LC_ALL` in a terminal, not sure about windows.

**Comment by gendx** [comment]
> @gendx are you in an unusual locale? You can check on Linux/Mac with `echo $LC_ALL` in a terminal, not sure about windows.

The `LC_ALL` variable isn't set in my environment.

FWIW I was building from within a Docker container on Linux, so not many environment variables are set (but I don't have `LC_ALL` set either on my host Linux system).

**Comment by gendx** [comment]
Regarding the locale (or lack thereof), could this be related to https://github.com/kellpossible/cargo-i18n/issues/49, i.e. when `$LANG` is unset in this minimalist Docker environment (as shown by running `env` in a shell)?

**Comment by jyn514** [comment]
I wouldn't expect that to affect the emitted code - my idea was that a string constant was being serialized that wasn't utf8, but now that I think about it more that doesn't really make sense, since rust requires source files to be valid unicode.

**Comment by jackh726** [comment]
I'm going to close this since there aren't clear steps to reproduce.
