### ISSUE TITLE
x.py dist shouldn’t require network access

### ISSUE THREAD

**Issue by Keruspe** [rust-lang/rust#79218]
Since #78790 we run cargo vendor unconditionally to vendor libtest in libstd.
We should either pass it '--offline' or add a way to conditionally do so to avoid using network when unnecessary

**Comment by Mark-Simulacrum** [comment]
I am happy to accept a patch for this; if it is not small (e.g., just adding offline) we will likely end up wanting to revert #78790 on beta.

**Comment by camelid** [comment]
Is this really P-critical? I would think this is P-high since P-critical is usually reserved for severe user-facing bugs.

**Comment by Mark-Simulacrum** [comment]
I consider inability for distros to build a particular version of Rust to be a release blocker.

**Comment by Keruspe** [comment]
Here what i've tried so far:

- `cargo vendor --offline`
- `cargo vendor --locked`
- `cargo generate-lockfile --offline && cargo vendor --locked`
- `cargo generate-lockfile --offline && cargo vendor --locked --offline`

None of those worked out, last failure:

```
running: "/usr/x86_64-pc-linux-gnu/bin/cargo-beta" "generate-lockfile" "--offline"
running: "/usr/x86_64-pc-linux-gnu/bin/cargo-beta" "vendor" "--offline" "--locked" "/var/tmp/paludis/build/dev-lang-rust-1.49.0-scm/work/rust-1.49.0-scm/build/tmp/dist/rust-src-beta-image/lib/rustlib/src/rust/vend
or"
                                                                                                 
command did not execute successfully: "/usr/x86_64-pc-linux-gnu/bin/cargo-beta" "vendor" "--offline" "--locked" "/var/tmp/paludis/build/dev-lang-rust-1.49.0-scm/work/rust-1.49.0-scm/build/tmp/dist/rust-src-beta-im
age/lib/rustlib/src/rust/vendor"
expected success, got: exit code: 101                                                                              
error: failed to sync            
Caused by:                   
  failed to download packages                                                               
Caused by:               
  failed to download `rustc-std-workspace-alloc v1.0.0`
Caused by:                                                                                                                                                                                                           
  can't make HTTP request in the offline mode   
```

**Comment by Keruspe** [comment]
With just the `cargo vendor --locked --offline` (without the generate-lockfile):

```
Caused by:
  failed to load pkg lockfile                                                                                                                                   
Caused by:                                                                                                
  can't update in the offline mode
```

**Comment by camelid** [comment]
> I consider inability for distros to build a particular version of Rust to be a release blocker.

Ah, I didn't realize it was that bad! Sorry about that.

**Comment by Mark-Simulacrum** [comment]
cc @rust-lang/cargo -- do we expect cargo vendor to work without network when vendoring a subset of a workspace? It looks like we're running into some trouble here to get it working, though I've not personally had time yet to test.

cc @Gankra as well

**Comment by alexcrichton** [comment]
I believe Cargo is working as intended here, when you run `cargo vendor` in the workspace root it doesn't actually vendor the `rustc-std-workspace-*` crates from crates.io because they're patched locally to the in-tree versions. Then when Cargo later vendors for libtest, it doesn't see the `[patch]` annotations so it tries to download them from the network. If you've passed `--offline` and you're using a vendor directory that means Cargo can't download any more packages, so it provides this error.

I think the fix here is to either get Cargo to see the `[patch]` for these crates during the libtest vendoring process or somehow get those crates vendored in whatever does the original vendor.

**Comment by Keruspe** [comment]
Will give the `[patch]` approach a try, thanks a lot for the explanation

**Comment by ehuss** [comment]
I have posted a revert for the current release (#80082) since there were several issues on the Cargo side, too.  Hopefully we'll try to avoid these issues when we try again.
