### ISSUE TITLE
`std::io::Error::description()` is deprecated, but its recommended replacement gives a different result

### ISSUE THREAD

**Issue by mooli** [rust-lang/rust#79230]
I would like my shell utilities written in Rust to print the same style of error messages as their traditional C brethren which use e.g. `perror` to give error messages of the form "foo: can't read "bar": permission denied".

There is therefore a need to turn an `io::Error` into the text "permission denied" and the like. `io::Error::description()` does this, but it is marked as deprecated and causes a compiler warning to "use the Display impl or to_string()". However, the `Display` impl on `io::Error` formats the `Repr::Os` (i.e. errno-like) variant using `write!(fmt, "{} (os error {})", detail, code)` which produces the text "Operation not permitted (os error 1)". The integer value of errno is an implementation detail which just adds visual clutter.

(Right now, I just add `#allow(deprecated)` to the call to `description()`, but this is a code smell that I'd like to get rid of.)

To fix this, simply remove the error number from the `Display` impl since ["`Display` is for user-facing output"](https://doc.rust-lang.org/nightly/core/fmt/trait.Display.html) and this kind of noise does not belong there. It is still in the `Debug` output for anybody who wants it. Alternatively, if the `Display` format is frozen (why?) then another method which gets at just the error text would be helpful. `ErrorKind::as_str()` could be made public, for example.

**Comment by jonas-schievink** [comment]
If you need the output of `perror`/`strerror`, you should use [`Error::raw_os_error`](https://doc.rust-lang.org/std/io/struct.Error.html#method.raw_os_error) and call `strerror` with that

**Comment by Plecra** [comment]
This makes sense to me. Though I hadn't considered it before, the os error doesn't belong in the default `Display` output. Custom implementations would still be free to append it to their own output (in a way they can't today)

```rust
fn print_error_with_code(err: io::Error) {
    match err.raw_os_error() {
        Some(code) => println!("{} (os error {})", err, code),
        None => println!("{}", err),
    }
}

**Comment by mooli** [comment]
> If you need the output of `perror`/`strerror`, you should use [`Error::raw_os_error`](https://doc.rust-lang.org/std/io/struct.Error.html#method.raw_os_error) and call `strerror` with that

What a ridiculous workaround! So I have to pull in `libc`, use `unsafe` (thus tainting my crate), and then jump through C FFI hoops just so user-facing error messages don't contain weird "(os error 42)" cruft which adds no useful information?

If that was a cryptic way of saying WONTFIX, I'll stick with the deprecated `description()` as a least-worst solution.

**Comment by LunarLambda** [comment]
Perhaps, if backwards compatibility was a concern (it shouldn't be?), the alternate flag `#` could be used?

```rs
// prints error without os code
println!("{}: {:#}", my_app_name, the_error);
```

**Comment by Enselic** [comment]
Triage: Closing as won't fix because
* it will be impossible to `Display` `io::Error` in a way that makes everyone happy
* because of the above, it will be a lot of work to change how `io::Error` is `Display`ed
* the benefits are small
* it is easy for apps to customize what is printed for a given [`Error::kind()`](https://doc.rust-lang.org/std/io/struct.Error.html#method.kind)
