### ISSUE TITLE
Performance regression in `1.48.0`

### ISSUE THREAD

**Issue by marmeladema** [rust-lang/rust#79246]
Hello everyone!

We detected a performance regression on a closed-source project after an upgrade of rust from version `1.47.0` to version `1.48.0`.
The benchmark we run internally are using the low-level `perf_event_open` Linux API to measure various hardware performance counters on specific code section.
The most stable and reliable counter we care about is the number of retired instructions, corresponding to `instructions:u` in classic `perf` output.

On certain datasets, the regressions are up to +16% in the number of instructions executed.

I used `cargo-bisect-rustc` as instructed on https://rust-lang.zulipchat.com/#narrow/stream/122651-general/topic/Performance.20regressions.20in.201.2E48.2E0 in order to search for the commit that introduced the regression:

> searched nightlies: from nightly-2020-09-03 to nightly-2020-11-20
> regressed nightly: nightly-2020-09-04
> searched commits: from https://github.com/rust-lang/rust/commit/80fc9b0ecb29050d45b17c64af004200afd3cfc2 to https://github.com/rust-lang/rust/commit/0d0f6b113047b2cf9afbde990cee30fd5b866469
> regressed commit: https://github.com/rust-lang/rust/commit/0d0f6b113047b2cf9afbde990cee30fd5b866469
> 

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.0</summary>

Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --script=./bisect.sh 
```
</details>

The bisection points to https://github.com/rust-lang/rust/pull/70793

I was able to reproduce the regression on two different machines.
I will also try to provide a minimized code example to reproduce the issue but that will take some time as the code being measured is quite big.

If anyone else has noticed this regression and could help me towards tools / ideas / whatever that could be of help to reproduce the issue would greatly appreciated!

EDIT:
MCVE at https://github.com/marmeladema/bitvec-perf-regression

**Comment by Mark-Simulacrum** [comment]
I suspect a good next step would be to try to narrow down the code being regressed -- maybe with something like a cachegrind diff -- to attempt to isolate the problem, and perhaps propose a fix.

**Comment by JulianKnodt** [comment]
Just curious, are you using LTO when you notice the regression? I was looking at the code in the PR and there are a lot of small methods which aren't marked with `#[inline]`, which from my experience would cause slowdown.

**Comment by marmeladema** [comment]
> Just curious, are you using LTO when you notice the regression? I was looking at the code in the PR and there are a lot of small methods which aren't marked with `#[inline]`, which from my experience would cause slowdown.

Yes, LTO is enabled for release builds which what is being measured here.

**Comment by the8472** [comment]
If it helps narrowing down which code to test: The changes should only affect code using `into_iter()` on `Vec`, `Box<[]>` or `BinaryHeap` and then `collect`ing into one of those types again, optionally involving some of the iterator adapters from the core crate. Anything else would be unintended.

The primary goal of that PR is to reduce malloc/free traffic by reusing allocations where possible. I only measured with the system allocator. Do you use that or a custom one?

Part of that optimization also involves switching from loops over `next()` to a `try_fold()` for. That might affect vectorization. But most of the microbenchmarks that I ran under `perf` seemed to vectorize fine even with iterators involving several adapters.

There also are a bunch of smaller tweaks relating to allocations in various `Vec` iteration/collection methods such as changing a memcpy between allocations to an internal memmove.

>  I was looking at the code in the PR and there are a lot of small methods which aren't marked with #[inline]

Afaiu inline annotations are only needed on non-generic methods and the whole SourceIter methods are generic.

**Comment by the8472** [comment]
>  The changes should only affect code using `into_iter()` on `Vec`, `Box<[]>` or `BinaryHeap` and then `collect`ing into one of those types again

Small correction, it may also affect some iterators involving `Vec.into_iter()` and `zip` without `collect`ing into one of the above types again.

**Comment by marmeladema** [comment]
> If it helps narrowing down which code to test: The changes should only affect code using `into_iter()` on `Vec`, `Box<[]>` or `BinaryHeap` and then `collect`ing into one of those types again, optionally involving some of the iterator adapters from the core crate. Anything else would be unintended.

Ok thanks! That is valuable information. FYI the measured code has some (maybe heavy?) use of `Vec`/`Box<[]>` and iterating/collecting from those but no usage of `BinaryHeap`

**Comment by marmeladema** [comment]
I continued my investigation and did a `perf diff` between two run of the crate comparing stable 1.47.0 to 1.48.0:

* with rust 1.47.0, most of the time is spent in:
```
itvec::vec::iter::<impl core::iter::traits::collect::Extend<bool> for bitvec::vec::BitVec<O,T>>::extend
```

* whereas with rust 1.48.0, most of the time is spent in:
```
bitvec::vec::api::<impl bitvec::vec::BitVec<O,T>>::push
```

This led me to focus on the `bitvec` crate itself and more especially the `BitVec::extend` method which seems to be the one being severely impacted by the regression. 
The `bitvec` version being tested was `0.17.4` and after updating to version `1.19.4`, I could not trigger the regression anymore.

I managed to provide a self-contained and (relatively) minimized example on https://github.com/marmeladema/bitvec-perf-regression

I run the bisection again and it failed with:
```
********************************************************************************
Regression in nightly-2020-09-02
********************************************************************************

fetching https://static.rust-lang.org/dist/2020-09-01/channel-rust-nightly-git-commit-hash.txt
ERROR: Tarball not found at https://static.rust-lang.org/dist/2020-09-01/channel-rust-nightly-git-commit-hash.txt
```

but this time it seems to point to `nightly-2020-09-02` instead of `nightly-2020-09-04` ...
Not sure exactly which one is the culprit?

I have also bisected the `bitvec` crate itself and the regression disappears at https://github.com/myrrlyn/bitvec/commit/f82112243707923a380e5091deab51c29b4f2948 which is basically a rewrite of the crate

**Comment by marmeladema** [comment]
I managed to manually bisect rustc and it *seems* the `bitvec` regression has been introduced by commit https://github.com/rust-lang/rust/commit/1d22f75c9f75cad2e408a145861904898ac982dd which corresponds to the merge of https://github.com/rust-lang/rust/pull/76030

**Comment by marmeladema** [comment]
I can confirm that reverting #76030:
<details>
<summary>patch</summary>

```patch
diff --git a/compiler/rustc_codegen_llvm/src/type_of.rs b/compiler/rustc_codegen_llvm/src/type_of.rs
index 8ea4768f77d..0876907e119 100644
--- a/compiler/rustc_codegen_llvm/src/type_of.rs
+++ b/compiler/rustc_codegen_llvm/src/type_of.rs
@@ -40,9 +40,7 @@ fn uncached_llvm_type<'a, 'tcx>(
         // FIXME(eddyb) producing readable type names for trait objects can result
         // in problematically distinct types due to HRTB and subtyping (see #47638).
         // ty::Dynamic(..) |
-        ty::Adt(..) | ty::Closure(..) | ty::Foreign(..) | ty::Generator(..) | ty::Str
-            if !cx.sess().fewer_names() =>
-        {
+        ty::Adt(..) | ty::Closure(..) | ty::Foreign(..) | ty::Generator(..) | ty::Str => {
             let mut name = with_no_trimmed_paths(|| layout.ty.to_string());
             if let (&ty::Adt(def, _), &Variants::Single { index }) =
                 (layout.ty.kind(), &layout.variants)
@@ -58,12 +56,6 @@ fn uncached_llvm_type<'a, 'tcx>(
             }
             Some(name)
         }
-        ty::Adt(..) => {
-            // If `Some` is returned then a named struct is created in LLVM. Name collisions are
-            // avoided by LLVM (with increasing suffixes). If rustc doesn't generate names then that
-            // can improve perf.
-            Some(String::new())
-        }
         _ => None,
     };
 
```
</details>

fixes the regression.

I am not sure what to do from there.

cc @eddyb @davidtwco

**Comment by eddyb** [comment]
Ugh, choice of names shouldn't cause perf changes. At a glance, this looks like a LLVM bug.

I was going to suggest testing with `-Z fewer-names=off`, but that doesn't actually do anything (the lack of `--emit=llvm-ir` means it's forced to "fewer names", we should maybe fix that).
And you tested the revert *anyway*, so that's confirmation enough.

@marmeladema if you have the time, one thing you could try is "bisecting" for the name (i.e. choose between `Some(name)` and `Some(String::new())` based on some property, such as `name.len()` or `name.contains("...")` etc.). Presumably the exact type that needs a name to not cause the perf regression, could be determined.

Then you pretty much want to diff the output of `-Z no-parallel-llvm -C llvm-args=-print-after-all` runs with and without names for *that one type*, and see where optimizations diverge. Or you can start with that kind of diff, if you can figure out a way to ignore most of the differences from having named vs numbered types.

**Comment by marmeladema** [comment]
I have managed to isolate the precise name that needs to be generatee to not cause the performance regression:
* `bitvec::prelude::BitVec` (exactly)

**Comment by marmeladema** [comment]
I have tried to decompile `BitVec::extend` with ghidra but it's the first time i've used that tool and I am not really sure of what I did, nor if it's really useful :smile: The only difference I can see in the decompiled code is an additional endless loop when unwrapping the `Option<bool>`:

```patch
--- bitvec.extend.slow.decompiled.c     2020-11-23 23:19:02.971052349 +0000
+++ bitvec.extend.fast.decompiled.c     2020-11-23 23:10:45.442938517 +0000
@@ -99,11 +99,13 @@
   do {
     bVar2 = *param_2;
     if (bVar2 == 2) {
-                    /* WARNING: Subroutine does not return */
       core::panicking::panic
                 (
                  "called `Option::unwrap()` on a `None`valuelibrary/std/src/panicking.rslibrary/std/src/env.rsfailed to get environmentvariable ``: already mutablyborrowedlibrary/std/src/sys_common/thread_info.rsassertion failed:c.borrow().is_none()Rust panics must be rethrownRust cannot catch foreignexceptionslibrary/std/src/sys/unix/rwlock.rs<unnamed>note: run with`RUST_BACKTRACE=1` environment variable to display a backtrace\n\' panicked at\'\', rwlock maximum reader count exceededrwlock read lock would result indeadlockthread panicked while panicking. aborting.\nthread panicked whileprocessing panic.aborting.\n.debug_library/std/src/../../backtrace/src/symbolize/gimli/elf.rs/home/adema/code/rust/library/alloc/src/vec.rslibrary/std/src/path.rsinternal error:entered unreachable code"
                  ,0x2b,&PTR_UINT_0014f3c8);
+      do {
+        invalidInstructionException();
+      } while( true );
     }
     pointer::BitPtr<T>::into_bitslice(*param_1,param_1[1]);
     pointer::BitPtr<T>::into_bitslice(*param_1);

```

Does that help at all, or am I not looking in the right place?

**Comment by the8472** [comment]
Are you sure you're looking at the right method? Previously said most of the time is spent in `bitvec::vec::api::<impl bitvec::vec::BitVec<O,T>>::push`, not extend.

**Comment by marmeladema** [comment]
I decompiled this one because that's actually the method that is called in my reproducible code. `push` shows up in the perf diff but because it must be called at some point during `extend`. At least that how I understand it but again, I might be wrong.
@the8472 have you had a chance to look at the mcve yet?

**Comment by spastorino** [comment]
This [was discussed during today's compiler meeting](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.20meeting.5D.202020-12-17.20.2354818/near/220260955)

**Comment by tmiasko** [comment]
LLVM bug report https://bugs.llvm.org/show_bug.cgi?id=51667 and proposed patch https://reviews.llvm.org/D109294.

**Comment by marmeladema** [comment]
@tmiasko I see the llvm bug has been resolved. Has our llvm fork been updated with the fix? If so should this be closed?

**Comment by nikic** [comment]
@marmeladema No, the fix will be pulled in with the LLVM 14 upgrade.

**Comment by marmeladema** [comment]
Closing this issue now that we are at LLVM 15.
