### ISSUE TITLE
Documentation for Vec::leak doesn't ackowledge dropping of excess capacity

### ISSUE THREAD

**Issue by TheOnlyMrCat** [rust-lang/rust#79240]
When using one of the functions to convert a `Vec<T>` to a `[T]`, excess capacity of the vector is dropped, leaving the slice with only the elements which have been initialised in memory.

This behaviour is acknowledged in the documentation for `Vec::into_boxed_slice`, but not in the documentation for `Vec::leak`.

**Comment by chansuke** [comment]
I'd like to work on this.

@rustbot claim

**Comment by yaymukund** [comment]
As per [this comment by m-ou-se in chansuke's PR](https://github.com/rust-lang/rust/pull/79257#discussion_r586447615):

> This example doesn't demonstrate any leaking. .into_boxed_slice() returns a Box, which the slice variable will own.
>
> The issue this PR was originally trying to fix is that the documentation doesn't promise this function drops excess capacity. However, I don't think that's something we want to fix. Instead, I think it'd be better if leak explicitly does not drop the excess capacity. But for that, there's an RFC which has been standing still for a while: rust-lang/rfcs#2969

Should this be closed in favor of the linked RFC?

**Comment by JohnTitor** [comment]
Hm, makes sense, though the RFC PR has been closed. I think it'd be great if we could provide some explanation for it but it seems it's not time to do right now. Okay, I'm going to close this for now, thanks for pointing out!
