### ISSUE TITLE
I'm getting  errors 'error: command failed: 'rust' error: caused by: No such file or directory (os error 2)' 

### ISSUE THREAD

**Issue by corvinux** [rust-lang/rust#79268]
**cat /proc/cpuinfo**
Processor	: AArch64 Processor rev 4 (aarch64)
processor	: 0
processor	: 1
processor	: 2
processor	: 3
processor	: 4
processor	: 5
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 wp half thumb fastmult vfp edsp neon vfpv3 tlsi vfpv4 idiva idivt
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x0
CPU part	: 0xd03
CPU revision	: 4

Hardware	: Qualcomm Technologies, Inc MSM8956

**uname -a**
Linux XperiaX 3.10.84 #1 SMP PREEMPT Sun Jul 12 19:46:59 UTC 2020 aarch64 GNU/Linux

**ldd .cargo/bin/rustc**
/usr/lib/libpreloadpatchmanager.so (0xf6f68000)
	libdl.so.2 => /lib/libdl.so.2 (0xf6f48000)
	librt.so.1 => /lib/librt.so.1 (0xf6f32000)
	libpthread.so.0 => /lib/libpthread.so.0 (0xf6f0b000)
	libgcc_s.so.1 => /lib/libgcc_s.so.1 (0xf6ef2000)
	libc.so.6 => /lib/libc.so.6 (0xf6dd9000)
	libm.so.6 => /lib/libm.so.6 (0xf6d6f000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0xf6c5d000)
	/lib/ld-linux-armhf.so.3 (0xaab87000)

```
$ curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
info: downloading installer

Welcome to Rust!

This will download and install the official compiler for the Rust
programming language, and its package manager, Cargo.

Rustup metadata and toolchains will be installed into the Rustup
home directory, located at:

  /home/defaultuser/.rustup

This can be modified with the RUSTUP_HOME environment variable.

The Cargo home directory located at:

  /home/defaultuser/.cargo

This can be modified with the CARGO_HOME environment variable.

The cargo, rustc, rustup and other commands will be added to
Cargo's bin directory, located at:

  /home/defaultuser/.cargo/bin

This path will then be added to your PATH environment variable by
modifying the profile files located at:

  /home/defaultuser/.profile
  /home/defaultuser/.bash_profile

You can uninstall at any time with rustup self uninstall and
these changes will be reverted.
Current installation options:


   default host triple: aarch64-unknown-linux-gnu
     default toolchain: stable
               profile: default
  modify PATH variable: yes

1) Proceed with installation (default)
2) Customize installation
3) Cancel installation
>1

info: profile set to 'default'
info: setting default host triple to aarch64-unknown-linux-gnu
info: syncing channel updates for 'stable-aarch64-unknown-linux-gnu'
info: latest update on 2020-11-19, rust version 1.48.0 (7eac88abb 2020-11-16)
info: downloading component 'cargo'
info: downloading component 'clippy'
info: downloading component 'rust-std'
 25.0 MiB /  25.0 MiB (100 %)   5.9 MiB/s in  4s ETA:  0s
info: downloading component 'rustc'
 61.8 MiB /  61.8 MiB (100 %)   6.3 MiB/s in 10s ETA:  0s
info: downloading component 'rustfmt'
info: installing component 'cargo'
info: Defaulting to 500.0 MiB unpack ram
  4.6 MiB /   4.6 MiB (100 %)   3.5 MiB/s in  1s ETA:  0s
info: installing component 'clippy'
info: installing component 'rust-std'
 25.0 MiB /  25.0 MiB (100 %)   4.6 MiB/s in  5s ETA:  0s
info: installing component 'rustc'
 61.8 MiB /  61.8 MiB (100 %)   5.9 MiB/s in 10s ETA:  0s
info: installing component 'rustfmt'
info: default toolchain set to 'stable'

  stable installed - (error reading rustc version)


Rust is installed now. Great!

To get started you need Cargo's bin directory ($HOME/.cargo/bin) in your PATH
environment variable. Next time you log in this will be done
automatically.

To configure your current shell run source $HOME/.cargo/env
```

I tried this code:

```

rustc -V
```

I expected to see this happen: *rustc 1.48.0 (7eac88abb 2020-11-16)*

Instead, this happened: `error: command failed: 'cargo' error: caused by: No such file or directory (os error 2)'`

### Meta

There is the same in the beta or nightly versions.

`rustc --version --verbose`:
```
error: command failed: 'rustc'
error: caused by: No such file or directory (os error 2)
```

<details><summary>RUST_BACKTRACE=1 rustc -V --verbose</summary>
error: backtrace:

0: backtrace::capture::Backtrace::new_unresolved

1: error_chain::backtrace::imp::InternalBacktrace::new

2: rustup_init::main

3: std::rt::lang_start_internal::{{closure}}::{{closure}}
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/rt.rs:52
      std::sys_common::backtrace::__rust_begin_short_backtrace
             at /rustc/c7087fe00d2ba919df1d813c040a5d47e43b0fe7/src/libstd/sys_common/backtrace.rs:130

4: main

5: __libc_start_main
<p>

```
<backtrace>
```

</p>
</details>

**Comment by jyn514** [comment]
This looks like a rustup issue, can you report it on https://github.com/rust-lang/rustup/issues instead?

**Comment by corvinux** [comment]
Hi,
@jyn514  I've also reported it on rust-lang/rustup.

**Comment by jyn514** [comment]
Thanks, I'll close this in favor of https://github.com/rust-lang/rustup/issues/2565.
