### ISSUE TITLE
Tracking issue: fNN::is_subnormal

### ISSUE THREAD

**Issue by clarfonthey** [rust-lang/rust#79288]
The feature gate for the issue is `#![feature(is_subnormal)]`.

### Implementation history
- [x] Initial implementation: #76941
- [x] FCP
- [ ] Stabilization PR

### Unresolved Questions
None currently.

**Comment by m-ou-se** [comment]
@rfcbot merge

**Comment by JohnTitor** [comment]
Closing as it has been stabilized.
