### ISSUE TITLE
rustdoc: Derived trait impl shows lifetime as `'__a`

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#79283]
I saw this in the [rustc rmeta API docs](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_metadata/rmeta/struct.CrateRoot.html#trait-implementations):

![image](https://user-images.githubusercontent.com/37223377/99890193-98874480-2c11-11eb-824f-ff567354f1cc.png)

I'm guessing this is caused by somewhere here?

```console
❯ rg "'__a" compiler/
compiler/rustc_macros/src/serialize.rs
20:    s.add_impl_generic(parse_quote! { '__a });
21:    let decoder_ty = quote! { DecodeContext<'__a, 'tcx> };
153:    s.add_impl_generic(parse_quote! { '__a });
154:    let encoder_ty = quote! { EncodeContext<'__a, 'tcx> };
```

**Comment by jyn514** [comment]
I don't think this is a bug, this is the actual lifetime being generated by the macro.

**Comment by camelid** [comment]
Ah, I think you're right :)
