### ISSUE TITLE
Missing "unreachable pattern" warning on char ranges

### ISSUE THREAD

**Issue by Nadrieril** [rust-lang/rust#79307]
I tried this code ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=b896532d569bb349a8be86d21ab80231)):

```rust
match 'a' {
    '\u{0}'..='\u{D7FF}' | '\u{E000}'..='\u{10_FFFF}' => {},
    '\u{D7FF}'..='\u{E000}' => {}, // should be unreachable
}
```

The first pattern by itself is exhaustive, because it covers all the valid chars. The second pattern looks like it includes more chars than the first, but it doesn't, because those extra chars are all invalid. So the second pattern should be marked unreachable.

This fails on all rust versions on the playground, and I think it's been that way since we implemented `exhaustive_integer_patterns`. I discovered it while working on the exhaustiveness algorithm.

@rustbot modify labels: +A-exhaustiveness-checking

**Comment by leonardo-m** [comment]
Are such intervals ever going to change in the UNICODE world?

**Comment by Nadrieril** [comment]
Hm, good question, I have no idea. But they are already hardcoded in the compiler since the following is exhaustive:
```rust
match 'a' {
    '\u{0}'..='\u{D7FF}' | '\u{E000}'..='\u{10_FFFF}' => {}
}
```
So this issue is more about making the two consistent. If unicode changes it would change the above too.

**Comment by Dylan-DPC** [comment]
Current error:
```
warning: multiple patterns overlap on their endpoints
 --> src/main.rs:4:5
  |
3 |     '\u{0}'..='\u{D7FF}' | '\u{E000}'..='\u{10_FFFF}' => {},
  |     --------------------   -------------------------- this range overlaps on `'\u{e000}'`...
  |     |
  |     this range overlaps on `'\u{d7ff}'`...
4 |     '\u{D7FF}'..='\u{E000}' => {}, // should be unreachable
  |     ^^^^^^^^^^^^^^^^^^^^^^^ ... with this range
  |
  = note: you likely meant to write mutually exclusive ranges
  = note: `#[warn(overlapping_range_endpoints)]` on by default
  ```

**Comment by Dylan-DPC** [comment]
Closing this as the warning message now indicates that the 2nd arm is unreachable.

**Comment by Nadrieril** [comment]
That's an unrelated lint, it does not indicate that the 2nd arm is unreachable (only my comment in the code does). [This](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=36f7f3b2235d6df36a56cb537ecb9176) still shows the issue
