### ISSUE TITLE
Specify layout of `Cell` and `UnsafeCell`

### ISSUE THREAD

**Issue by Kestrer** [rust-lang/rust#79303]
Currently, `Cell<T>` and `UnsafeCell<T>` are both `#[repr(transparent)]`. However, it is unclear whether this is stable or just an implementation detail. This [line in the implementation of UnsafeCell](https://github.com/rust-lang/rust/blob/master/library/core/src/cell.rs#L1713-L1714) notes that "there is no guarantee for user code that this [casting a `*const UnsafeCell<T>` to `*mut T`] will work in future versions of the compiler"; but it is unclear whether this applies to the casting of `*const UnsafeCell<T>` to `*const T` or the casting of `*const T` to `*mut T`. [`as_slice_of_cells`](https://doc.rust-lang.org/stable/std/cell/struct.Cell.html#method.as_slice_of_cells) also relies on the layout of `UnsafeCell`, but makes no mention of it being exclusive to std.

Even if they do stably have a transparent layout, there are also some questions to be resolved around whether _creating_ `UnsafeCell`s from references is UB; conversions like `*const T` to `*const UnsafeCell<T>`, `&T` to `&UnsafeCell<T>`, `&mut T` to `&UnsafeCell<T>`, `&[UnsafeCell<T>]` to `&UnsafeCell<[T]>` should all probably be specified.

**Comment by steffahn** [comment]
@rustbot modify labels to T-doc, T-lang, C-enhancement.

Also, here’s the link to [the relevant URLO discussion](https://users.rust-lang.org/t/interior-mutable-sliceable-boxed-slice/51785).

**Comment by sfackler** [comment]
From a libs perspective, a `#[repr(transparent)]` annotation on a public type is a stable guarantee. I think that warning has more to due with the unsafe code guidelines decisions around what exactly is UB or not in relation to the "specialness" of `UnsafeCell` than just if the type is transparent.

**Comment by the8472** [comment]
> From a libs perspective, a #[repr(transparent)] annotation on a public type is a stable guarantee.

What does that tell a user though though? Its field is not part of the public API thus one can't know in relation to what it is transparent. In other words there could in theory be yet another wrapper inside and the `repr(transparent)` only gives us the wrapper's ABI and not T's.
