### ISSUE TITLE
Compiler suggesting unstable or-pattern in for loop

### ISSUE THREAD

**Issue by ritobanrc** [rust-lang/rust#79357]
When forgetting to include parenthesis around a tuple pattern in a for loop, the compiler gives a suggestion to use an or pattern. I would expect this, a. because it's not what most would expect if you use a comma to separate two values in a pattern, and b. because or patterns in for loops are still an unstable feature. 

I tried this code:

```rust
    let a = vec![1, 2, 3];
    let b = vec![3, 4, 5];
    
    for foo, bar in a.into_iter().zip(b) {    }
```
As expected, the compiler gives an `unexpected `,` in pattern` error, because I forgot the parenthesis around `(foo, bar)`. However, the compiler also suggests that I add a "vertical bar to match on multiple alternatives". 

```
error: unexpected `,` in pattern
 --> src/main.rs:5:13
  |
5 |     for foo, bar in a.into_iter().zip(b) {
  |             ^
  |
help: try adding parentheses to match on a tuple...
  |
5 |     for (foo, bar) in a.into_iter().zip(b) {
  |         ^^^^^^^^^^^
help: ...or a vertical bar to match on multiple alternatives
  |
5 |     for foo | bar in a.into_iter().zip(b) {
  |         ^^^^^^^^^^
```

[Playground Link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=6afbf2156c50598a9a04f64f9e1bce8c)

While it does provide the correct answer (adding parenthesis), it also provides the vertical bar option, which is an unstable feature in this [RFC](https://github.com/rust-lang/rfcs/blob/master/text/2535-or-patterns.md). 

While the RFC does not explicitly single out for loops as a situation where this is necessary, I believe it does apply here, because in [this situation](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=fe1b2f314c93af2c559cb4446d47d2db) (credit /u/ehuss for the example, which is a situation where the or pattern syntax is being used correctly, I get a `or-patterns syntax is experimental` error, as expected, and including `#![feature(or_patterns)]` resolves the error. 

### Meta

I tested this on stable, beta, and nightly in the rust playground. The output is identical for all 3 of them.

**Comment by nico-abram** [comment]
I would like to work on this, if possible

Would it just be gating [this suggestion](https://github.com/rust-lang/rust/blob/40624dde6cdfad2576b4d795c97583188a814884/compiler/rustc_parse/src/parser/pat.rs#L218-L223) on `self.sess.gated_spans.is_ungated(sym::or_patterns)` like [here](https://github.com/rust-lang/rust/blob/40624dde6cdfad2576b4d795c97583188a814884/compiler/rustc_parse/src/parser/pat.rs#L58-L60)?

**Comment by jyn514** [comment]
@nico-abram that seems like the right approach :)

**Comment by nico-abram** [comment]
Looking at this more closely I'm not sure the fix is that simple, since [some top level or patterns are stable](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=9fae3f8136748b0b78f318fe498ad33f) and [the suggestion is correct (And given) for those](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=c31c1ab7f319597ed925a3b0c891957d)

[The nested case](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=c31c1ab7f319597ed925a3b0c891957d) seems to [not get the suggestion](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=fc9d350c9069c4afa787dc1d97d41b96) (Which matches the comment for `maybe_recover_unexpected_comma`)

**Comment by nico-abram** [comment]
Looking at usages of GateOr::{Yes, No}, it looks like the only top level things (Which are the only ones that give the suggestion AIUI) that are GateOr::Yes are local variable declaration patterns and for patterns
