### ISSUE TITLE
Don't prefix full path specification when suggesting changing & to &mut.

### ISSUE THREAD

**Issue by iago-lito** [rust-lang/rust#79405]
(moved from https://github.com/rust-analyzer/rust-analyzer/issues/6626)

With the following code:
```rust
fn f(vec: &Vec<usize>) {
    vec.push(5);
}
```
I get a suggestion to "change this to a mutable reference", but if I do, I get:
```rust
fn f(vec: &mut std::vec::Vec<usize>) {
    vec.push(5);
}
```

That's a bit overkill, right? I would rather expect
```rust
fn f(vec: &mut Vec<usize>) {
    vec.push(5);
}
```

It actually becomes worse. I've decided to file this bug report after my argument:
```rust
shells: &LocatedShells,
```
was changed to
```rust
shells: &mut topology::located_slice::LocatedBoxedSlice<std::collections::HashMap<usize, shell::Shell, std::hash::BuildHasherDefault<fnv::FnvHasher>>>,
```
instead of just
```rust
shells: &mut LocatedShells,
```

That's definitely overkill, so I end up changing the `&` to `&mut` by hand.
Is this something expected? Or something I can configure not to happen?

**Comment by ThePuzzlemaker** [comment]
This does not appear to be from rustc (nightly and stable output the same thing):
```
error[E0596]: cannot borrow `*vec` as mutable, as it is behind a `&` reference
 --> src/lib.rs:2:5
  |
1 | pub fn f(vec: &Vec<usize>) {
  |               ----------- help: consider changing this to be a mutable reference: `&mut Vec<usize>`
2 |     vec.push(5);
  |     ^^^ `vec` is a `&` reference, so the data it refers to cannot be borrowed as mutable
```
It's not even present with `--message-format json` (excerpt):
```
"suggested_replacement":"&mut Vec<usize>"
```

**Comment by iago-lito** [comment]
@ThePuzzlemaker Oh, well I'm confused then. Where could this suggestion come from if neither `rust-analyzer` nor `rustc`? :\ Clippy maybe?

**Comment by xFrednet** [comment]
I couldn't find the error message in the clippy code. It's interesting that @ThePuzzlemaker example output contains the type without a specific path. The [Rust Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=855611f02ad974c54ab621de0041c2aa) produced a message with a full path specification like this:

```rust
error[E0596]: cannot borrow `*me` as mutable, as it is behind a `&` reference
 --> src/main.rs:3:5
  |
2 | fn not_using_mut(me: &Vec<u8>) {
  |                      -------- help: consider changing this to be a mutable reference: `&mut Vec<u8>`
3 |     me.push(4);
  |     ^^ `me` is a `&` reference, so the data it refers to cannot be borrowed as mutable

error: aborting due to previous error
```

I found the error message from the output in [diagnostics/mutability_errors.rs line 390.](https://github.com/rust-lang/rust/blob/3525087ada7018ef227b10846648660b7f07b6d1/compiler/rustc_mir/src/borrow_check/diagnostics/mutability_errors.rs#L390). 

Could this maybe be a mismatch between the OS or something? I had a similar problem where the CI of GitHub produced an output without a specific path while my local compiler produced an output with a specific path. I believe that the GitHub CI runs on Linux while I'm currently using a windows 10 PC.

**Comment by iago-lito** [comment]
@xFrednet Hm, well, I can't read a full type spec in the error you are showing. See https://github.com/rust-lang/rust-clippy/issues/6385#issuecomment-739766923 ;)
