### ISSUE TITLE
[ER] cartesian_product_array, permutations_array, combinations_array

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust#79426]
Now Rust is powerful enough to implement a generator like a (simplified version of) Python itertools.product:
https://docs.python.org/3/library/itertools.html#itertools.product

You may want to add to Rust stdlib something like this, that has an API similar to that Python itertool function:

```rust
#![feature(min_const_generics, generator_trait, generators, array_map)]

use std::ops::{Generator, GeneratorState};
use std::pin::Pin;

fn generator_to_iterator<G>(g: G) -> impl Iterator<Item = G::Yield>
where G: Generator<Return = ()> + Unpin {
    struct It<G>(G);

    impl<G: Generator<Return = ()> + Unpin> Iterator for It<G> {
        type Item = G::Yield;

        fn next(&mut self) -> Option<Self::Item> {
            match Pin::new(&mut self.0).resume(()) {
                GeneratorState::Yielded(y) => Some(y),
                GeneratorState::Complete(()) => None,
            }
        }
    }

    It(g)
}


fn cartesian_product_array<T, const N: usize, const REPEAT: usize>
                          (data: &[T; N]) -> impl Iterator<Item=[&T; REPEAT]> + '_ {
    generator_to_iterator(move || {
        if N == 0 { return; }
        let mut indexes = [0; REPEAT];

        loop {
            yield indexes.map(|i| &data[i]);
            let mut j = REPEAT - 1;
            loop {
                indexes[j] += 1;
                if indexes[j] < N { break; }
                indexes[j] = 0;
                if j == 0 { return; }
                j -= 1;
            }
        }
    })
}


fn permutations_array<T, const N: usize>
                     (data: &[T; N]) -> impl Iterator<Item=[&T; N]> {
    generator_to_iterator(move || {
        if N == 0 { return; }

        let mut perm = [0_usize; N];
        (0 .. N).for_each(|i| perm[i] = i);

        loop {
            let mut i = N - 1;

            while perm[i - 1] >= perm[i] {
                i -= 1;
                if i < 1 { return; }
            }

            let mut j = N;
            while perm[j - 1] <= perm[i - 1] { j -= 1; }

            perm.swap(i - 1, j - 1);
            i += 1;
            j = N;
            perm[i - 1 .. j].reverse();
            yield perm.map(|i| &data[i]);
        }
    })
}


fn combinations_array<T, const N: usize, const K: usize>
                     (data: &[T; N]) -> impl Iterator<Item=[&T; K]> {
    generator_to_iterator(move || {
        if N == 0 { return; }

        let mut comb = [0_usize; K];
        (0 .. K).for_each(|i| comb[i] = i);

        while comb[K - 1] < N {
            yield comb.map(|i| &data[i]);

            let mut t = K - 1;
            while t != 0 && comb[t] == N - K + t {
                t -= 1
            }
            comb[t] += 1;
            for i in t + 1 .. K {
                comb[i] = comb[i - 1] + 1;
            }
        }
    })
}


fn main() {
    for [&c0, &c1, &c2, &c3, &c4] in cartesian_product_array(&['A', 'B', 'C', 'D']) {
        println!("{:?}", [c0, c1, c2, c3, c4]);
    }
    println!();

    for [&p0, &p1, &p2] in permutations_array(&[10, 20, 30]) {
        println!("{:?}", [p0, p1, p2]);
    }
    println!();

    for [&p0, &p1, &p2] in combinations_array(&['a', 'b', 'c', 'd', 'e']) {
        println!("{:?}", [p0, p1, p2]);
    }
}
```

This is isn't maximally flexible because REPEAT is a compile-time value and probably it's not maximally fast. But from my experience the size of windows and chunks are most times compile-time constants. And this has a very handy usage syntax, and it avoids heap usage.

The Python API allows to use one or more input sequences, instead of REPEAT, but for simplicity this takes only one slice and always use REPEAT.

Edit: added permutations and combinations. Modified the input, now it's always an array instead of a slice. This makes the code a little less flexible but it helps type inference.

**Comment by the8472** [comment]
Are you aware of the itertools crate, which does have a [cartesian product](https://docs.rs/itertools/0.9.0/itertools/trait.Itertools.html#method.cartesian_product) implementation?

**Comment by leonardo-m** [comment]
Itertools crate has a cartesian product between two sets. My code above is more like a "power". So they are quite different.

**Comment by NieDzejkob** [comment]
Still, consider contributing this to `itertools`. If the community decides that it's immensely useful, we can always uplift it into `std` later.

**Comment by leonardo-m** [comment]
This code has no heap allocations, it's cute, and it works in iterator chains, but in practice there's enough memory traffic that LLVM doesn't optimize away enough. So while this code is much faster than various naive implementations, it's still rather slower than a C++-STL-style function like next_permutation (that can't be used in iterator chains) that could be implemented just with a swap and some index twiddling. So I sadly close this issue down.
