### ISSUE TITLE
#[cfg(version)] ignores invalid version literal

### ISSUE THREAD

**Issue by taiki-e** [rust-lang/rust#79436]
I tried this code:

```rust
#![feature(cfg_version)]

#[cfg(version("aa.0"))]
mod foo {}
```

I expected to see this happen: error or warning about invalid version literal

Instead, this happened: no error or warning 
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=3f14787508e791c693ac85bf41973b97

Mentioning @mibac138 who implemented `#[cfg(version)]` in #71314.

**Comment by taiki-e** [comment]
It seems that this feature is currently using an external crate for version analysis, but IIUC, what this feature really needs is a simple parser like this, right?

```rust
// based on https://github.com/cuviper/autocfg/blob/1.0.1/src/version.rs#L7
// can be compare by using `>=`: https://github.com/cuviper/autocfg/blob/1.0.1/src/lib.rs#L218
#[derive(Clone, Debug, PartialEq, Eq, PartialOrd, Ord)]
struct Version {
    major: usize,
    minor: usize,
    patch: usize,
}

fn parse_version(s: &str) -> Result<Version, Box<dyn std::error::Error + Send + Sync>> {
    let mut digits = s.splitn(3, '.');
    let major = digits.next().ok_or("missing major version")?.parse()?; // using `.trim()` before `.parse()` is may be prefer? https://github.com/rust-lang/rust/issues/64796#issuecomment-622984135
    let minor = digits.next().ok_or("missing minor version")?.parse()?;
    let patch = digits.next().unwrap_or("0").parse()?;
    Ok(Version {
        major,
        minor,
        patch,
    })
}

```

**Comment by petrochenkov** [comment]
I agree that we need a custom simplified but fully controlled version parser for this instead of relying on `version_check`.

**Comment by est31** [comment]
Filed a PR: #81259
