### ISSUE TITLE
`impl const` wrongly accepts impl with non-const provided methods

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/rust#79450]
This prints no error, but `prov` is not `const`-safe, so the `impl const Tr` should not be accepted:

```rust
#![feature(const_trait_impl)]

trait Tr {
    fn req(&self);
    
    fn prov(&self) {
        println!("lul");
        self.req();
    }
}

struct S;

impl const Tr for S {
    fn req(&self) {}
}
```

**Comment by oli-obk** [comment]
I guess for `impl const` blocks we need to enforce that no defaulted fallbacks are used at all. This is discussed a bit in the RFC, but for now we should just disallow this entirely

**Comment by kadiwa4** [comment]
This issue applies again, it seems that the part of the test that checked this was removed in #96964.

Or is this intentionally accepted without an error now?

**Comment by kadiwa4** [comment]
This has been fixed again (<https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=aea283ceefe384376052b1cde86373cb>)
