### ISSUE TITLE
Incorrect "unreachable pattern" warning

### ISSUE THREAD

**Issue by psychon** [rust-lang/rust#79498]
Hi,

the following program builds without warnings on stable and nightly, but prints an (IMHO incorrect) warning on beta:
```rust
fn foo() -> (Result<u8, ()>, &'static [u8]) {
    (Err(()), b"1")
}

fn main() {
    match foo() {
        (Ok(_), _) => panic!("1"),
        (Err(_), b"") => panic!("2"),
        (Err(_), _) => panic!("3"),
    }
}
```

([Playground](https://play.rust-lang.org/?version=beta&mode=debug&edition=2018&gist=b537888176e15e0cbb8b9c4aa2a3cda6))

Errors:

```
   Compiling playground v0.0.1 (/playground)
warning: unreachable pattern
 --> src/main.rs:9:9
  |
9 |         (Err(_), _) => panic!("3"),
  |         ^^^^^^^^^^^
  |
  = note: `#[warn(unreachable_patterns)]` on by default

warning: 1 warning emitted

    Finished dev [unoptimized + debuginfo] target(s) in 1.46s
     Running `target/debug/playground`
thread 'main' panicked at '3', src/main.rs:9:24
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
The panic shows that the supposedly unreachable pattern was, well, reached.

Originally discovered in https://github.com/psychon/x11rb/pull/561 and surprisingly my attempt at reducing the example succeeded on the first try.

**Comment by sfackler** [comment]
This seems like #79048. It looks like the fix for that didn't make it into the beta branch.

**Comment by jyn514** [comment]
https://github.com/rust-lang/rust/pull/79072 was beta nominated, I think there just hasn't been a compiler meeting since because of the US holiday.

**Comment by Mark-Simulacrum** [comment]
Closing as fixed on master/beta.
