### ISSUE TITLE
What's the usage .rustc section in dylib

### ISSUE THREAD

**Issue by Eulogizethesun** [rust-lang/rust#79493]
I use cargo to build a dylib type library, but the size is larger than I expected.
We find that there is a .rustc section in the dylib, and it takes much space, almost 65 percent of the dylib.(The no.29 section in the picture). But when I use strip to remove this section, the dylib still  works correctly.
So, what's the usage of .rustc section? Can it be removed by strip?
![7E9BA23E-546D-4997-A5C4-A958570CDEFE](https://user-images.githubusercontent.com/38456859/100498993-106ce600-31a1-11eb-9c4d-3cd70a541cec.png)

**Comment by jonas-schievink** [comment]
Questions about rustc are better asked on [Zulip](https://rust-lang.zulipchat.com) or the [internals forum](https://internals.rust-lang.org/), as we try to keep the issue tracker only for bug reports.
