### ISSUE TITLE
Clap derive expansion no longer works on stable

### ISSUE THREAD

**Issue by pksunkara** [rust-lang/rust#79503]
### Code

[Clap](https://github.com/clap-rs/clap) has the following test at `clap_derive/tests/nested.rs`:

```rust
use clap::Clap;

#[test]
fn use_option() {
    macro_rules! expand_ty {
        ($name:ident: $ty:ty) => {
            #[derive(Clap)]
            struct Outer {
                #[clap(short, long)]
                #[allow(dead_code)]
                $name: $ty,
            }
        };
    }

    expand_ty!(my_field: Option<String>);
}
```

As you can see from the latest [master CI](https://github.com/clap-rs/clap/actions/runs/388643619), it fails to compile on [stable](https://github.com/clap-rs/clap/runs/1467319265?check_suite_focus=true)

### Version it worked on

It most recently worked on: Successfully compiles and runs on [1.46.0](https://github.com/clap-rs/clap/runs/1467319100?check_suite_focus=true)

### Version with regression

`rustc --version --verbose`:
```
rustc 1.48.0 (7eac88abb 2020-11-16)
```

**Comment by pksunkara** [comment]
Weirdly, when I use my mac to test this locally, it works.

```
→ rustup show active-toolchain
stable-x86_64-apple-darwin (default)
→ cargo test -p clap_derive --test nested --features "wrap_help yaml regex"
    Finished test [unoptimized + debuginfo] target(s) in 0.47s
     Running target/debug/deps/nested-55411ec307e7b9f1

running 1 test
test use_option ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
```

**Comment by pksunkara** [comment]
Pinging @petrochenkov because I suspect this is an issue with macro expansion. I tried `cargo expand` on the EC2 instance to check the output, but the code it had generated had no issues at all.

**Comment by jyn514** [comment]
This works on 1.47 and breaks on 1.48.

**Comment by jyn514** [comment]
searched nightlies: from nightly-2020-07-11 to nightly-2020-11-28
regressed nightly: nightly-2020-09-12
searched commits: from https://github.com/rust-lang/rust/commit/a1947b3f9e2831e2060bc42f0c78e4a2bb67930a to https://github.com/rust-lang/rust/commit/99111606fcda4fdb0646e4f7ee0f6cbcb76fb84a
regressed commit: https://github.com/rust-lang/rust/commit/94b4de0e0793c8921d30e0fb886be712d17db6e5

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.5.2</summary>


Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc -v --script ./test.sh --preserve --start 2020-07-11 
```

where test.sh is
```sh
#!/bin/sh
cargo test -p clap_derive --test nested
```

</details>

**Comment by jyn514** [comment]
cc @Aaron1011 - https://github.com/rust-lang/rust/pull/75800 broke clap too.

**Comment by Aaron1011** [comment]
This is due to a bug in how clap uses `quote_spanned!`. When https://github.com/rust-lang/rust/pull/75800 was merged, we started preserving hygiene information in more cases, exposing the bug,

I've opened https://github.com/clap-rs/clap/pull/2231 to fix the issue

**Comment by Aaron1011** [comment]
@pksunkara: Do you know if this test was failing on nightlies prior to the stable release that broke this?

**Comment by jyn514** [comment]
@Aaron1011 no, it was broken in https://github.com/rust-lang/rust/pull/75800: https://github.com/rust-lang/rust/issues/79503#issuecomment-735247581. That searched nightlies, not stable releases.

**Comment by Aaron1011** [comment]
I mean, did the Clap CI tests start failing on nightly after that rust PR was merged?

**Comment by pksunkara** [comment]
Doesn't look like it. See this job, https://github.com/clap-rs/clap/pull/2211/checks?check_run_id=1399409188

**Comment by pksunkara** [comment]
To see a passing nightly CI run, check this, https://github.com/clap-rs/clap/runs/1393825395

**Comment by pksunkara** [comment]
I am closing this since the regression is not one. It looks like the original PR did a crater run, but the bugged code was in a test file.

I am not sure why one of the nightlies wasn't failing, but that's a separate issue altogether.
