### ISSUE TITLE
expose c api, get a wrong value when return type is integer pointer type

### ISSUE THREAD

**Issue by chenzww** [rust-lang/rust#79512]
Environment:
OS: macOS Catalina 10.15.7
Rust Version: rustc 1.48.0 (7eac88abb 2020-11-16) // stable
FFI Caller: Objective-C

Summary:
I have a problem when I use rust to expose c api. When return type is int pointer, the only way to get correct value from raw pointer is make integer literal convert to const raw pointer. Otherwise, it will get a ramdon value.

```rust
pub extern "C" fn multiply(a: i32, b: i32) -> *const i32 { &(a*b) as *const i32 } // => ❌
pub extern "C" fn multiply(a: i32, b: i32) -> *const i32 { &100 as *const i32 } // => ⭕️
pub extern "C" fn multiply(a: i32, b: i32) -> *mut i32 { &100 as *mut i32 } // => ❌
pub extern "C" fn multiply(a: i32, b: i32) -> *mut i32 { &mut (a*b) as *mut i32 } // => ❌
```

**Comment by jonas-schievink** [comment]
You're returning a pointer to a local variable, which is deallocated when the function returns. Closing as not-a-bug.
