### ISSUE TITLE
[ER] Suboptimal error message in a case of min_const_generics inference failure

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust#79557]
This code:

```rust
#![feature(min_const_generics)]
fn foo<const N: usize, const K: usize>(data: [u32; N]) -> [u32; K] {
    [0; K]
}
fn main() {
    let a = foo::<_, 2>([0, 1, 2]);
}
```

Gives (with rustc 1.50.0-nightly 349b3b324 2020-11-29):

```rust
error[E0747]: type provided when a constant was expected
 --> ...\test.rs:6:19
  |
6 |     let a = foo::<_, 2>([0, 1, 2]);
  |                   ^
```

Two problems:
1) In the code I've used the underscore hoping rustc to infer the value of N, but for some reason it failed.
2) Beside the type inference failure, the error message is not the best possible. I didn't provide a type. A better error message could say "unable to infer the const argument N, please specify".

**Comment by lcnr** [comment]
Using `_` for a const parameter is currently not possible, though that seems both like something we are able to support and probably should.

Until we implement this we probably want to add a help here which says that `_` is not allowed for const arguments, only for types. Will open a topic on zulip about this https://rust-lang.zulipchat.com/#narrow/stream/260443-project-const-generics/topic/.60_.60.20as.20const.20param.20help.20msg

**Comment by varkor** [comment]
Fixing this requires essentially the same strategy as fixing https://github.com/rust-lang/rust/issues/66615 (and, to a lesser extent, https://github.com/rust-lang/rust/issues/77773).

**Comment by leonardo-m** [comment]
Now (rustc 1.51.0-nightly 158f8d034 2020-12-29) this code:
```rust
fn main() {
    fn init<const N: usize, const M: usize>(sieve: &mut [bool; M]) {}
    const N: usize = 5;
    let mut foos = [false; 10];
    init::<N, _>(&mut foos);
}
```
Gives:
```rust
error[E0747]: type provided when a constant was expected
 --> ...\test.rs:5:15
  |
5 |     init::<N, _>(&mut foos);
  |               ^
  |
  = help: const arguments cannot yet be inferred with `_`
  = note: type arguments must be provided before constant arguments
  = help: reorder the arguments: consts: `<N, M>`
  ```
  
  The last two lines (the note and the second help) seem off to me.

**Comment by varkor** [comment]
Opened https://github.com/rust-lang/rust/issues/80528 for actually supporting this feature, rather than diagnostics suggesting it to be invalid.
