### ISSUE TITLE
Internal Compiler Error while compiling diesel

### ISSUE THREAD

**Issue by weiznich** [rust-lang/rust#79560]
### Code

[Diesel master](https://github.com/diesel-rs/diesel/commit/91493fe47175076f330ce5fc518f0196c0476f56)

### Meta

`rustc --version --verbose`:
```
rustc 1.50.0-nightly (349b3b324 2020-11-29)
binary: rustc
commit-hash: 349b3b324dade7ca638091db93ba08bbc443c63d
commit-date: 2020-11-29
host: x86_64-unknown-linux-gnu
release: 1.50.0-nightly
```

Last known working version: `rust 1.50.0-nightly (b48cafd9e 2020-11-25)` (Haven't tried the nightlies in between yet)

### Error output

```
thread 'rustc' panicked at 'forcing query with already existing `DepNode`
- query-key: (DefId(0:1086 ~ diesel[f0f0]::expression::ValidGrouping), Some(IsAggregate#1483))
- dep-node: super_predicates_that_define_assoc_type(67abfa33ab7d90da-56b8cbe8d1ca79a9)', /rustc/349b3b324dade7ca638091db93ba08bbc443c63d\compiler\rustc_query_system\src\query\plumbing.rs:586:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic
Error: internal compiler error: unexpected panic
note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.50.0-nightly (349b3b324 2020-11-29) running on x86_64-pc-windows-msvc

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [explicit_predicates_of] computing explicit predicates of `type_impls::tuples::_::_::<impl expression::ValidGrouping<__GroupByClause> for (A, B, C)>`
#1 [predicates_defined_on] computing predicates of `type_impls::tuples::_::_::<impl expression::ValidGrouping<__GroupByClause> for (A, B, C)>`
end of query stack
error: could not compile `diesel`
Error: could not compile `diesel`
To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
Warning: thread 'rustc' panicked at 'forcing query with already existing `DepNode`
- query-key: (DefId(0:1098 ~ diesel[8909]::expression::ValidGrouping), Some(IsAggregate#3574))
- dep-node: super_predicates_that_define_assoc_type(10b7a81c445a7cf0-f4bea10f7f9b919e)', /rustc/349b3b324dade7ca638091db93ba08bbc443c63d\compiler\rustc_query_system\src\query\plumbing.rs:586:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
As this is the second regression for diesel in less then a week: Would it possible to add diesel to the compiler test suite to prevent breaking diesel again and again. I would like to use my free time for something else than reporting regression bugs every day :wink:

@rustbot modify labels: +regression-from-beta-to-nightly

**Comment by matthiaskrgr** [comment]
>I would like to use my free time for something else than reporting regression bugs every day
Have you considered switching to the beta toolchain?

**Comment by weiznich** [comment]
@matthiaskrgr As I'm the maintainer of diesel that's not an option for me. I think it's obvious that our users expect that diesel will work on any version of rustc + issues occurring on nightly will be in beta in max. 6 weeks + in stable in max. 12 weeks, therefore that wouldn't help in any way.

**Comment by matthiaskrgr** [comment]
According to my bisection, 349b3b324dade7ca638091db93ba08bbc443c63d is the cause. cc @spastorino 

````

searched toolchains 1c389ffeff814726dec325f0f2b0c99107df2673 through 28b86e0860f0593b85cda6c2c7b03ae8a582962f


********************************************************************************
Regression in 349b3b324dade7ca638091db93ba08bbc443c63d
********************************************************************************
````

**Comment by hameerabbasi** [comment]
Relevant PR is #79209.

**Comment by hameerabbasi** [comment]
Labelling `P-critical` according to the Zulip [discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/I-prioritize.20.2379560.20Internal.20Compiler.20Error.20while.20compiling.E2.80.A6). Many of the reasons were already outlined above.

**Comment by jyn514** [comment]
@weiznich you could make a PR to cargotest adding diesel. I don't think it would be a very controversial add, it exercises a lot more of the compiler than something like `regex`.

**Comment by spastorino** [comment]
@rustbot ping cleanup

Would be nice to get an MCVE for this one.

**Comment by kvark** [comment]
Same issue affects gfx-rs repo. Looking forward to a fix!

**Comment by SNCPlay42** [comment]
Small repro crate:

```rust
#[macro_use]
extern crate serde; //1.0.117
macro_rules! formats {
    {
        $($name:ident,)*
    } => {
        $(
            #[derive(Deserialize)]
            pub struct $name;
        )*
    }
}
formats! { Foo, Bar, }
```

Expanding the `formats!` macro doesn't repro the ICE, nor does expanding the `Deserialize` derive. Also I can't repro on playground.

**Comment by jyn514** [comment]
<details><summary>Backtrace</summary>

```
thread 'rustc' panicked at 'forcing query with already existing `DepNode`
- query-key: (DefId(18:1213 ~ serde[392b]::de::Deserializer), Some(Error#12))
- dep-node: super_predicates_that_define_assoc_type(f061438f2a3ccf95-d48f0f966cfa452)', /rustc/349b3b324dade7ca638091db93ba08bbc443c63d/compiler/rustc_query_system/src/query/plumbing.rs:586:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/349b3b324dade7ca638091db93ba08bbc443c63d/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/349b3b324dade7ca638091db93ba08bbc443c63d/library/std/src/panicking.rs:435:5
   2: rustc_query_system::query::plumbing::get_query_impl
   3: rustc_infer::traits::util::transitive_bounds_that_define_assoc_type
   4: <dyn rustc_typeck::astconv::AstConv>::associated_path_to_ty
   5: <dyn rustc_typeck::astconv::AstConv>::ast_ty_to_ty_inner
   6: <<dyn rustc_typeck::astconv::AstConv>::create_substs_for_ast_path::SubstsForAstPathCtxt as rustc_typeck::astconv::CreateSubstsForGenericArgsCtxt>::provided_kind
   7: <dyn rustc_typeck::astconv::AstConv>::create_substs_for_ast_path
   8: <dyn rustc_typeck::astconv::AstConv>::ast_path_substs_for_ty
   9: <dyn rustc_typeck::astconv::AstConv>::res_to_ty
  10: <dyn rustc_typeck::astconv::AstConv>::ast_ty_to_ty_inner
  11: <dyn rustc_typeck::astconv::AstConv>::ty_of_fn
  12: rustc_typeck::collect::fn_sig
  13: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::fn_sig>::compute
  14: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  15: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
  16: rustc_data_structures::stack::ensure_sufficient_stack
  17: rustc_query_system::query::plumbing::get_query_impl
  18: rustc_query_system::query::plumbing::ensure_query_impl
  19: <rustc_typeck::collect::CollectItemTypesVisitor as rustc_hir::intravisit::Visitor>::visit_impl_item
  20: rustc_middle::hir::map::Map::visit_item_likes_in_module
  21: rustc_typeck::collect::collect_mod_item_types
  22: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::collect_mod_item_types>::compute
  23: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  24: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task
  25: rustc_data_structures::stack::ensure_sufficient_stack
  26: rustc_query_system::query::plumbing::get_query_impl
  27: rustc_query_system::query::plumbing::ensure_query_impl
  28: rustc_typeck::check_crate
  29: rustc_interface::passes::analysis
  30: rustc_middle::ty::query::<impl rustc_query_system::query::config::QueryAccessors<rustc_middle::ty::context::TyCtxt> for rustc_middle::ty::query::queries::analysis>::compute
  31: rustc_middle::dep_graph::<impl rustc_query_system::dep_graph::DepKind for rustc_middle::dep_graph::dep_node::DepKind>::with_deps
  32: rustc_query_system::dep_graph::graph::DepGraph<K>::with_eval_always_task
  33: rustc_data_structures::stack::ensure_sufficient_stack
  34: rustc_query_system::query::plumbing::get_query_impl
  35: rustc_interface::passes::QueryContext::enter
  36: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  37: rustc_span::with_source_map
  38: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.50.0-nightly (349b3b324 2020-11-29) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental -C link-arg=-fuse-ld=lld --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [fn_sig] computing function signature of `_::<impl serde::Deserialize<'de> for Bar>::deserialize`
#1 [collect_mod_item_types] collecting item types in top-level module
#2 [analysis] running analysis passes on this crate
end of query stack
```

</details>

**Comment by spastorino** [comment]
@SNCPlay42 nice!, it would be nice to reduce this further without any external deps.

**Comment by SNCPlay42** [comment]
Single crate repro:

```rust
trait Deserializer {
    type Error;
}

trait Deserialize {
    fn deserialize<D>(_: D) -> D::Error
    where D: Deserializer;
}

macro_rules! impl_deserialize {
    ($name:ident) => {
        impl Deserialize for $name {
            fn deserialize<D>(_: D) -> D::Error
            where D: Deserializer
            {
                loop {}
            }
        }
    }
}

macro_rules! formats {
    {
        $($name:ident,)*
    } => {
        $(
            pub struct $name;

            impl_deserialize!($name);
        )*
    }
}
formats! { Foo, Bar, }
```

It seems incremental compilation has to be enabled to repro the ICE, which is why it doesn't repro on playground.

**Comment by workingjubilee** [comment]
Chiming in with "this hit stdsimd as well".

**Comment by spastorino** [comment]
We've just reverted the PR that's causing this issue. Can you confirm if this is still a problem?.
Gonna downgrade the priority but keep it open to track the long term problem we have here.

**Comment by matthiaskrgr** [comment]
Can't speak for diesel or stdsimd, but the ICE we saw in clippys CI (ice while checking `marwes/combine` was gone after the revert.

**Comment by workingjubilee** [comment]
Can confirm that nightly now compiles the library with its test suite. The immediate problem appears to be fixed for now.

**Comment by michaelwoerister** [comment]
Working with @SNCPlay42's great repro, I think I found the culprit. The clash happens because two `Ident`s have the same StableHash value, but are considered different by `Eq` and `Hash`. In particular `Error#7` and `Error#8` have different `SyntaxContexts` (i.e. #7 and #8) but StableHash computes the same hash for both of them.

The problem is that the two `ExpnData` values that those `SyntaxContexts` refer to only differ in their `orig_id` field, but that exactly this field is ignored by `StableHash`:

https://github.com/rust-lang/rust/blob/e6225434fff7d493baac0aa91c57f2da923ea196/compiler/rustc_span/src/hygiene.rs#L703-L710

Unfortunately, I don't know enough about this for proposing a solution.

**Comment by jyn514** [comment]
@petrochenkov , @Aaron1011, do you have suggestions for the correct fix?

**Comment by Aaron1011** [comment]
This results from the fact that the `HashStable` implementation for `SyntaxContext` ignores ids (`SyntaxContext` and `ExpnId`), instead (recursively) looking at `SyntaxContextData` and `ExpnData`. This allows the stable hash to remain stable across compilation sessions (where we may end up with different `SyntaxContext`/`ExpnId` values, due to importing hygiene information from other crates).

Unfortunately, it turns out that we can have two distinct `SyntaxContext`s that end up having equivalent `SyntaxContextData`/`ExpnData` (ignoring `orig_id`). This is demonstrated by @SNCPlay42's example - the repetition expansion in `formats!` generates two distinct `ExpnId`s that have the same `ExpnData` (since they are both invoked from the same location in the source).

I'll need to think about how to adjust stable hashing to take this into account

**Comment by petrochenkov** [comment]
`DefPath`s have a `disambiguator` counter for this purpose, perhaps such counter can be added to `ExpnData` as well, using `orig_id` to detect differences, for example.

**Comment by spastorino** [comment]
@weiznich @kvark @workingjubilee @matthiaskrgr can you try #80732? where I'm re-introducing the thing that undercover this problem that ended affecting your code bases.

**Comment by camelid** [comment]
(See https://github.com/rust-lang/rust/pull/80732#issuecomment-754879677 for how to try out the PR.)

**Comment by weiznich** [comment]
@spastorino Diesel builds fine for me using the toolchain build from c963187c6f959417cbb13a33e9eaea4607696fc4.

**Comment by pnkfelix** [comment]
main remaining work item we've identified is to consider adding a build of diesel to CI. I'll follow up on that.

**Comment by weiznich** [comment]
@pnkfelix I've already opened https://github.com/rust-lang/rust/pull/79599 for that a while ago. Maybe it's as simple as just reopen and merge that one.

**Comment by spastorino** [comment]
The original issue is now fixed and if I'm not wrong @pnkfelix wants to keep this issue open to add a build of diesel to CI.

**Comment by weiznich** [comment]
This likely can be closed as diesel is part of the rustc test suite since 99a33b3

**Comment by spastorino** [comment]
Thanks @weiznich, closing this issue then.
