### ISSUE TITLE
Don't use RUST_BACKTRACE for std::backtrace

### ISSUE THREAD

**Issue by antoyo** [rust-lang/rust#79561]
Hi.
It can be very useful in a production environment to know where a `panic` comes from, which you can know by enabling `RUST_BACKTRACE`.
However, using the same [environment variable](https://github.com/rust-lang/rust/blob/43bfbb10bf52d1cf6bd90ae2e19bcd357d38be4d/library/std/src/backtrace.rs#L254) for error backtrace could lead to performance regression: your production service might require good performance and collecting a backtrace is very expansive.
Since errors are more often recovered than panics, you might not want to pay the cost of collecting backtraces for errors, while still might want to know the path which lead to a panic.
So I suggest you don't use `RUST_BACKTRACE` for error backtraces, to have the possibility to only get backtraces on panics, not on normal errors.
Thanks.

**Comment by Nemo157** [comment]
It's possible to configure panic-only backtraces with `RUST_BACKTRACE=1 RUST_LIB_BACKTRACE=0`.

**Comment by yaahc** [comment]
We discussed this issue in our last Library API meeting and concluded that we don't have any intention of changing the current behavior. You should be able to get the configuration you want with @Nemo157's suggestion, so for now we're closing this issue. Let me know if there are any issues still that can't be resolved.
