### ISSUE TITLE
What's the current state of cross-compilation from Linux -> Windows with (i686|x86_64)-pc-windows-gnu?

### ISSUE THREAD

**Issue by LunarLambda** [rust-lang/rust#79577]
I'm currently trying to somehow build a 32-bit Windows cdylib on Linux (although this should apply to *any* crate type, not just cdylibs), and after hours of intense rabbitholing through multiple years-old GitHub issues, I wanna compile what I've gathered.

i686-pc-windows-gnu:

1) requires an externally-installed mingw compiler toolchain.
2) will only work if said toolchain uses dw2 exception handling, since that's what Rust expects
3) with few exceptions, most distributions only provide mingw packages which use sjlj exceptions.
4) there were multiple attempts to resolve this, all of them more or less fruitless
5) if you can't easily obtain a dw2 toolchain, you have the following options:
5.1 use xargo (and thus nightly) to compile `std` and your code with `panic=abort`
5.2 use cross, which has a docker image that will build a dw2 toolchain for you, incurring *significant* build time overhead.

x86_64-pc-windows-gnu:

1) still requires an externally-installed mingw toolchain.
2) sort of just works? most distros provide packages that use SEH, rust expects SEH, all is well in the world<sup>[citation extremely needed]</sup>
(unfortunately, this does not help me, as I don't think 32-bit programs can load 64-bit libraries.)

questions I couldn't answer:
1) is there any (current) work happening to improve the situation around `i686-pc-windows-gnu`, or is it officially 'abandon all hope, ye who enter here' territory?
2) what is the situation regarding threads? mingw comes in posix and win32-threads flavours, and this has in the past been an additional source of problems, I'm not sure if this has been fixed? (https://github.com/rust-lang/rust/pull/71023)

update 21:43 2020-11-30: The docker image cross provides seems to have worked. I could build the cdylib, load it, and call a function in it. this is still far from ideal, as the docker image took significant amounts of time to prepare, and consumes significant amounts of disk space..

**Comment by mati865** [comment]
> with few exceptions, most distributions only provide mingw packages which use sjlj exceptions.

Most of the common distributions already use Dwarf-2 (Arch Linux, Fedora) or are in progress to switch ([Debian](https://salsa.debian.org/mingw-w64-team/gcc-mingw-w64/-/commit/8da432fefb792fbe2f9fec2f15278d02e86e6281)) soon.

**Comment by LunarLambda** [comment]
Arch does not package DWARF-2 compilers.

**Comment by mati865** [comment]
I'll try on my Arch later today but GCC is definitely built with Dwarf-2: https://github.com/archlinux/svntogit-community/blob/863707d772cb9d3b8d67c060dd7b48a20fa7b33a/trunk/PKGBUILD#L54

**Comment by LunarLambda** [comment]
related issue:

https://github.com/rust-lang/rust/issues/79609

**Comment by LunarLambda** [comment]
> I'll try on my Arch later today but GCC is definitely built with Dwarf-2: https://github.com/archlinux/svntogit-community/blob/863707d772cb9d3b8d67c060dd7b48a20fa7b33a/trunk/PKGBUILD#L54

Thank you for pointing me towards the PKGBUILD.
I decided to investigate and realised my compiler package outdated due to what looks like an improper package renaming.

After this re-install, it works fine. Closing this.

![image](https://user-images.githubusercontent.com/38919842/100904848-b8e3b880-34c7-11eb-93fb-862bbc94cffa.png)
