### ISSUE TITLE
Diagnostic regression (1.47 -> 1.48): public enum fields incorrectly described as "inaccessible fields".

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#79593]
Test example ([try on playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a0d6db204597d38ebd9bdfd3e104e669)):
```rust
mod foo {
    pub struct Pub { private: () }

    pub enum Enum {
        Variant { x: (), y: () },
        Other
    }
    
    fn correct() {
        Pub {};
        Enum::Variant { x: () };
    }
}

fn correct() {
    foo::Pub {};
}

fn wrong() {
    foo::Enum::Variant { x: () };
}
```

Only `foo::Pub {}` in the top level `correct` should say "cannot construct ... due to inaccessible fields", the other 3 errors should be "missing field ... in initializer", but it seems like it's treating the `enum` field as private (even though it inherits `pub` from the `enum`).

The "cannot construct ... due to inaccessible fields" error seems to be new in 1.48, as part of #76524, and unmodified since.

It's using `field.vis.is_accessible_from(...)` which seems correct, but it's possible `enum` fields are incapable of giving the right result, if they don't track the `enum`'s own privacy (and they only know they inherit it, whatever *it* is).

cc @davidtwco @estebank

**Comment by jyn514** [comment]
I would also suspect https://github.com/rust-lang/rust/pull/78077.

**Comment by camelid** [comment]
I ran into this too, but I couldn't make a repro. Thanks eddyb!

**Comment by camelid** [comment]
P-high: I've run into this a bunch of times and I imagine others have too. It's really annoying and confusing, likely even more so for newcomers!

**Comment by camelid** [comment]
searched nightlies: from nightly-2020-08-01 to nightly-2020-10-15
regressed nightly: nightly-2020-09-11
searched commits: from https://github.com/rust-lang/rust/commit/e2be5f568d1f60365b825530f5b5cb722460591b to https://github.com/rust-lang/rust/commit/a1947b3f9e2831e2060bc42f0c78e4a2bb67930a
regressed commit: https://github.com/rust-lang/rust/commit/ad3a6f70ac9457173aa1f3f3af372aadec915f8d

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.0</summary>


Host triple: x86_64-apple-darwin
Reproduce with:
```bash
cargo bisect-rustc --preserve --prompt --start=2020-08-01 --end=2020-10-15 
```
</details>

**Comment by camelid** [comment]
Seems very likely that this is due to #76524, as eddyb said.

**Comment by camelid** [comment]
Update: I've been reading the source code and print-debugging and I think the issue was not introduced in either of those two PRs, but rather that they surfaced a pre-existing issue.

**Comment by camelid** [comment]
Well, it took a while, but I think I fixed it!

**Comment by hussamT** [comment]
Does this necessitate a 1.48.1 release or shall I wait for 1.49?

**Comment by jyn514** [comment]
@hussamT it will be in 1.50 unless backported: https://doc.rust-lang.org/book/appendix-07-nightly-rust.html#choo-choo-release-channels-and-riding-the-trains

**Comment by hussamT** [comment]
On Sun, 2020-12-13 at 11:04 -0800, Joshua Nelson wrote:
> @hussamT it will be in 1.50 unless backported:
> https://doc.rust-lang.org/book/appendix-07-nightly-rust.html#choo-choo-release-channels-and-riding-the-trains
>

Ok. Thank you for the quick reply.
