### ISSUE TITLE
Rust package does not compile if openssl is upgraded to 3.0.0 alpha release

### ISSUE THREAD

**Issue by satya-rajesh** [rust-lang/rust#79592]
Version of openssl: openssl 3.0.0 alpha6
Version of rust: 1.46.0

CARGO_CFG_TARGET_FEATURE = Some("fxsr,mmx,sse,sse2")
running: "cc" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "/usr/include" "-E" "build/expando.c"
cargo:warning=build/expando.c:4:24: error: pasting "RUST_VERSION_OPENSSL_" and "(" does not give a valid preprocessing token
cargo:warning= #define VERSION2(n, v) RUST_VERSION_##n##_##v
cargo:warning=                        ^~~~~~~~~~~~~
cargo:warning=build/expando.c:5:23: note: in expansion of macro 'VERSION2'
cargo:warning= #define VERSION(n, v) VERSION2(n, v)
cargo:warning=                       ^~~~~~~~
cargo:warning=build/expando.c:10:1: note: in expansion of macro 'VERSION'
cargo:warning= VERSION(OPENSSL, OPENSSL_VERSION_NUMBER)
cargo:warning= ^~~~~~~
exit code: 1

--- stderr
thread 'main' panicked at '
Header expansion error:
Error { kind: ToolExecError, message: "Command \"cc\" \"-O3\" \"-ffunction-sections\" \"-fdata-sections\" \"-fPIC\" \"-m64\" \"-ffunction-sections\" \"-fdata-sections\" \"-fPIC\" \"-m64\" \"-I\" \"/usr/include\" \"-E\" \"build/expando.c\" with args \"cc\" did not execute successfully (status code exit code: 1)." }

Please start adding the support of openssl 3.0.0 (it is in alpha stage)

**Comment by jyn514** [comment]
@satya-rajesh what project are you trying to compile? That doesn't look like the rust compiler itself. If you want a project using rust to support openssl, you should report it to that project, not to the rust compiler.

**Comment by satya-rajesh** [comment]
Project: https://github.com/vmware/photon/tree/dev/

I am using:
https://github.com/rust-lang/rust/archive/%{name}-%{version}.tar.gz
package name: rust
version: 1.46.0

Build command:
sh ./configure --prefix=%{_prefix} --enable-extended --tools="cargo"
make

**Comment by sfackler** [comment]
OpenSSL 3.0.0 will be supported when it is actually released: https://github.com/sfackler/rust-openssl/pull/1264
