### ISSUE TITLE
Large allocations in const eval can OOM crash the compiler

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#79601]
I tried this code:

```rust
const FOO: () = {
    let x = [0_u8; 1000*1000*1000];  
};
```

I expected to see this happen: An error about the constant evaluation using more memory than the compiler having available

Instead, this happened: The compiler triggered an `abort`

### Meta

`rustc --version --verbose`:
```
1.48.0
```

<details><summary>Backtrace</summary>
<p>

* somewhere in the `Vec` machinery...
* https://github.com/rust-lang/rust/blob/0fa9d31c41cfa5f60dbce1204104eb8d8261be5f/compiler/rustc_middle/src/mir/interpret/allocation.rs#L110
* https://github.com/rust-lang/rust/blob/0fa9d31c41cfa5f60dbce1204104eb8d8261be5f/compiler/rustc_mir/src/interpret/memory.rs#L197

</p>
</details>

I think we'll need to stop using `Vec` and move to manually using `AllocRef::alloc` (and maybe `Box<[u8]>`? in order to allow bubbling up allocation errors during const eval back to the user via error messages.

cc @rust-lang/wg-const-eval 

related: https://github.com/rust-lang/rust/issues/23600

**Comment by RalfJung** [comment]
IIRC the plan of the allocator WG was to have a form of `Vec::try_reserve` that could be used in such situations?
Cc @TimDiekmann @Amanieu

**Comment by lcnr** [comment]
even if we use `try_reserve` here if the allocation is big enough but doesn't quite hit the limit by itself we will end up aborting somewhere else instead. It might make sense to add something like `#[const_allocation_size_limit = 1_000_000]` which restricts the total size of all heap allocations during const eval.
