### ISSUE TITLE
Document no-op pass-through attributes

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#7961]
For example, `license`, and there are probably a bunch more.

We need to list them explicitly because the manual currently says that all attribute names are currently reserved, so if someone is going to use attributes like `license`, we need to provide an assurance that rustc will not start interpreting it.

Sub-bug of #6444.

**Comment by steveklabnik** [comment]
After pinging @pnkfelix this morning, we're not sure there are any more of these, and since I'm knocking out the rest of #6444, anything missing will get covered there.
