### ISSUE TITLE
Intra-doc links for Self do not resolve with raw identifiers in module name

### ISSUE THREAD

**Issue by nickelc** [rust-lang/rust#79633]
### Code

I tried this code:

```rust
pub mod r#impl {
    pub struct S;

    impl S {
        /// See [`b`]
        ///
        /// [`b`]: Self::b
        pub fn a() {
        }

        pub fn b() {
        }
    }
}
```

I expected to see this happen: The link resolves to `S::b`.

Instead, this happened: rustdoc can't resolve the link
```
$ cargo +nightly-2020-12-01 doc
 Documenting intra-doc-raw-identifier v0.1.0 (/projects/rust/intra-doc-raw-identifier)
warning: unresolved link to `crate::r#impl::S::b`
 --> src/lib.rs:7:20
  |
7 |         /// [`b`]: Self::b
  |                    ^^^^^^^ no item named `r#impl` in module `intra_doc_raw_identifier`
  |
  = note: `#[warn(broken_intra_doc_links)]` on by default
```

### Version it worked on

It most recently worked on: `stable` and `<=nightly-2020-11-30`

### Version with regression

`rustdoc +nightly-2020-12-01 --version --verbose`:
```
rustdoc 1.50.0-nightly (b7ebc6b0c 2020-11-30)
binary: rustdoc
commit-hash: b7ebc6b0c1ba3c27ebb17c0b496ece778ef11e18
commit-date: 2020-11-30
host: x86_64-unknown-linux-gnu
release: 1.50.0-nightly
```

**Comment by jyn514** [comment]
Maybe I shouldn't have used pretty printing after all ... I'll try reverting https://github.com/rust-lang/rust/pull/76467/commits/aa8c9b0d294717a566b0d69721e8c7648309667c and see if it helps.

**Comment by camelid** [comment]
Assigning `P-medium` and removing `I-prioritize` as [discussed](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/I-prioritize.20.2379633.20Intra-doc.20links.20for.20Self.20do.20not.20resolve.E2.80.A6) in the prioritization working group.
