### ISSUE TITLE
Unclear compiler output for move async -> async move

### ISSUE THREAD

**Issue by diondokter** [rust-lang/rust#79694]
I tried this code:

```rust
fn main() {
    move async {
        
    };
}
```

This should give a suggestion to reorder the keywords to `async move`, something like:

```
`move async` is not a valid order for these keywords. Did you mean `async move`?
```

Right now it gives this error, which is not very helpful:

```
   Compiling playground v0.0.1 (/playground)
error: expected one of `|` or `||`, found keyword `async`
 --> src/main.rs:2:10
  |
2 |     move async {
  |          ^^^^^ expected one of `|` or `||`

error: aborting due to previous error

error: could not compile `playground`

To learn more, run the command again with --verbose.
```

[Playground link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=69e56d0bb1e6bcf069f0f13e4a66f7a8)

Tested on 1.48.0 and 1.50.0-nightly (2020-12-03 5be3f9f10e9fd59ea038)

**Comment by ThePuzzlemaker** [comment]
Releasing assignment as I'm not really sure how to fix this at the moment.
@rustbot release-assignment

**Comment by tmandry** [comment]
This could be handled directly in the parser code which generates the above diagnostic.
