### ISSUE TITLE
Update Unstable Book docs for `const_fn`

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#79691]
The docs currently say:

> The `const_fn` feature allows marking free functions and inherent methods as `const`, enabling them to be called in constants contexts, with constant arguments.

But that part of `const_fn` is already stable: `#![feature(const_fn)]` enables *additional* functionality.

cc https://github.com/rust-lang/rust/issues/79674#issuecomment-738578690

**Comment by sasurau4** [comment]
I'll work on this.
@rustbot claim
