### ISSUE TITLE
Tracking Issue for IntoInnerError::into_parts etc. (io_into_inner_error_parts)

### ISSUE THREAD

**Issue by ijackson** [rust-lang/rust#79704]
This is a tracking issue for `std::io::IntoInnerError::into_parts` and `::into_error`.
The feature gate for the issue is `#![feature(io_into_inner_error_parts)]`.

### Public API

- https://doc.rust-lang.org/nightly/std/io/struct.IntoInnerError.html#method.into_parts
- https://doc.rust-lang.org/nightly/std/io/struct.IntoInnerError.html#method.into_error

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Implement these methods - see #79673
- [x] Adjust documentation
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Unresolved Questions

These new methods are being introduced as an unstable feature to give time to validate their names, types, and documentation, before stabilisation.

### Implementation history

Implementation (with docs) is in #79673, currently in review/rework.

**Comment by dtolnay** [comment]
@rust-lang/libs
@rfcbot fcp merge

Check out @ijackson's recap of this API in https://github.com/rust-lang/rust/pull/84770#issue-628289300.
