### ISSUE TITLE
Miscompilation root-caused to llvm bug

### ISSUE THREAD

**Issue by jsgf** [rust-lang/rust#79708]
We have some internal code which crashes with a segmentation fault. There was no unsafe code anywhere near the calling site, so this was unexpected. When analyzed it turned out to be an invalid stack access in the generated code. Unfortunately we could not reduce this to a compact reproducer. So far as we know there's only one instance of this bug affecting generated code in our codebase, but we haven't yet eliminated the possibility of a non-faulting manifestation.  Using new-pass-manager eliminates the problem in this case.

It turned out to be a bug with llvm's alias analysis. Upstream proposed fix and discsussion: https://reviews.llvm.org/D91576

I'm filing this mostly as a heads up to wg-llvm to make sure that once the fix has landed in llvm it gets picked up in the next Rust release.

cc @mjhostet, @dtolnay 

### Meta

`rustc --version --verbose`:
```
rustc 1.47.0-dev
LLVM Version: 9.0
```
We are building this against an in-house version of llvm 9.0 with some local modifications. It's not clear why this problem started manifesting in 1.47.0.

**Comment by modiking** [comment]
FYI I have it reduced to the newly added test case here: https://reviews.llvm.org/differential/changeset/?ref=2303082. It's a latent bug that has existed since https://reviews.llvm.org/D7490 so most likely 1.47.0 just exposed inputs that trigger it.

**Comment by jsgf** [comment]
@modiking 2015!

**Comment by modiking** [comment]
Yeah haha. As https://github.com/rust-lang/rust/issues/54878 and other bugs have shown the !noalias attribute on arguments only manifests in C++ via `restrict` pointers. So optimizations and analysis here are not heavily stressed in C++. However, from what I can tell based on rust safe code 'restrict' is implied for all arguments which is exposing this to production scale effects.

**Comment by LeSeulArtichaut** [comment]
Removing prioritization request since the bug is fixed on LLVM upstream, and nominating for `T-compiler` to discuss if a cherry-pick of the fix is warranted, [as discussed as part of the Prioritization WG procedure](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/I-prioritize.20.2379708.20Miscompilation.20root-caused.20to.20llvm.20bug).

**Comment by modiking** [comment]
FYI for a cherry-pick you'll want the fix:
1. https://reviews.llvm.org/rG18603319321a6c1b158800bcc60035ee01549516
and a small fixup to the solution
2. https://reviews.llvm.org/rG756fa8b9be0ca3458073952495c323ba9d04036d

**Comment by spastorino** [comment]
This [was discussed during today's compiler meeting](https://rust-lang.zulipchat.com/#narrow/stream/238009-t-compiler.2Fmeetings/topic/.5Bweekly.20meeting.5D.202020-12-17.20.2354818/near/220261638)

**Comment by nikic** [comment]
We're now on LLVM 12, which includes this fix. Would you be able to confirm that the issue has been resolved?

**Comment by modiking** [comment]
1.5.0 looks like it cut-off just before but current rust master does have these LLVM commits in. Internally we've been running with this patch on LLVM 9.0 and I verified the codegen on the once failing program is now correct. I'd say we're good with the move to 12 unless there's backport requests. @jsgf to confirm.
