### ISSUE TITLE
Tracking Issue for `const_cell_refs`

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#79703]
This is a tracking issue for the feature gate `#![feature(const_cell_refs)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [ ] Implement
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Unresolved Questions

* How do we get the static checks back that ensure `const FOO: &Cell<i32> = &Cell::new(42);` does not compile successfully?
    * With the feature gate only dynamic checks (post-monomorphization during CTFE) catch it.

**Comment by RalfJung** [comment]
@oli-obk there was an implementation PR for this, right? Could you add a link to the issue description?

Currently this issue says nothing about what the feature even does.

**Comment by oli-obk** [comment]
This is a leftover of my failed attempt for https://github.com/rust-lang/rust/issues/80384

The feature gate does not actually exist
