### ISSUE TITLE
rustc hangs and leaks memory

### ISSUE THREAD

**Issue by is8ac** [rust-lang/rust#79714]
In stable, `rustc 1.48.0 (7eac88abb 2020-11-16)`, `rustc demo.rs` promptly returns `overflow evaluating the requirement` and exits. This is expected behavior.

In nightly, `rustc 1.50.0-nightly (5be3f9f10 2020-12-03)`, `rustc demo.rs` hangs indefinitely, using 100% of one core. Memory usage fluctuates but tends to grow over time at ~800 MB per minute on my machine.

### Source 

```rust
pub trait Baz {}
impl Baz for () {}
impl<T> Baz for [T; 3] {}

pub trait Fiz {}
impl Fiz for bool {}

pub trait Corge<S> {
    type Foo;
}

impl<W: Corge<()>> Corge<[(); 3]> for W {
    type Foo = [<W as Corge<()>>::Foo; 3];
}

pub trait Grault
where
    Self::B: Fiz,
{
    type A;
    type B;
}

impl<T: Grault> Grault for [T; 3]
where
    Self::A: Baz,
    Self::B: Fiz,
{
    type A = [T::A; 3];
    type B = T::B;
}

pub trait Quaks<S, W> {
    fn bar() {}
}

impl<S> Quaks<S, bool> for u8
where
    bool: Corge<S>,
    <bool as Corge<S>>::Foo: Grault,
{
}

fn main() {
    <u8 as Quaks<[(); 3], bool>>::bar();
}
```

`rustc --version --verbose`:
```
rustc 1.50.0-nightly (5be3f9f10 2020-12-03)
binary: rustc
commit-hash: 5be3f9f10e9fd59ea03816840a6051413fbdefae
commit-date: 2020-12-03
host: x86_64-unknown-linux-gnu
release: 1.50.0-nightly
```

**Comment by JohnTitor** [comment]
This happens on beta as well.

**Comment by JohnTitor** [comment]
The regression introduced between `nightly-2020-10-06` (a1dfd2490a6cb456b92e469fa550dc217e20ad6d) and `nightly-2020-10-07` (98edd1fbf8a68977a2a7c1312eb1ebff80515a92)

Possible culprit PRs: #77606, #73905 (likely the latter?)

**Comment by camelid** [comment]
Assigning `P-high` and removing `I-prioritize` as [discussed](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/I-prioritize.20.2379714.20rustc.20nightly.20hangs.20and.20leaks.20memory) in the prioritization working group.

**Comment by Mark-Simulacrum** [comment]
I am going to move this to P-low as this isn't breaking working code, we have more urgent fall out from #73905 that needs to be fixed first.
