### ISSUE TITLE
Unhygenic Rust macros with const

### ISSUE THREAD

**Issue by GreenBeard** [rust-lang/rust#79715]
The following compiles when I believe that it shouldn't.

```rust
macro_rules! do_little {
    ($arg: expr) => {
        const A: i32 = $arg;
    };
}

fn main() {
  do_little!(1);
  print!("Hello world {}!\n", A);
}
```

The following fails to compile when I believe that it should.

```rust
macro_rules! do_little {
    ($arg: expr) => {
        const A: i32 = $arg;
    };
}

fn main() {
  do_little!(1);
  do_little!(1);
}
```

Edit: Occurs in both Stable, and Nightly.

**Comment by jonas-schievink** [comment]
Only local variable bindings are hygienic, so this is expected behavior.

**Comment by GreenBeard** [comment]
@jonas-schievink So it is intentional that they are accessible? Is this listed anywhere in the documentation? I had that consts were limited to the scope declared as the following example doesn't work. If you insist it is intentional I find myself perplexed as to why, although I guess I will just add extra braces in my macro as I would in C. *shrug*

```
fn main() {
  {
    const A: i32 = 0;
  }
  print!("Hello world {}!\n", A);}
```

**Comment by jonas-schievink** [comment]
Hmm, it seems that it is neither documented in the Rust Book nor the Reference, weird. There's some third-party documentation though: https://veykril.github.io/tlborm/macros/minutiae/hygiene.html

It is very much working as intended for now though. Macros 2.0 will be *fully* hygienic.
