### ISSUE TITLE
Not clear what Item and IntoIter are referring to

### ISSUE THREAD

**Issue by alper** [rust-lang/rust#79726]
![slice - Rust 2020-12-05 11-11-10](https://user-images.githubusercontent.com/72429/101239778-ac8b7580-36ea-11eb-88dc-8003322b30b4.jpg)

Beginner here. This seems to be a core piece of documentation when using iterators and for-loops.

It's unclear what Item refers to here.

Also, it seems that this is the case:
> The IntoIterator implementation for &[T] produces items of type &T .

But there is no way to glean that from the documentation.

**Comment by SkiFire13** [comment]
> It's unclear what Item refers to here.

It's written in the line below:

> The type of the elements being iterated over.

Do you have any suggestion to make it more clear?

**Comment by camelid** [comment]
> Also, it seems that this is the case:
> 
> > The IntoIterator implementation for &[T] produces items of type &T .
> 
> But there is no way to glean that from the documentation.

What do you mean? That's why `Item` is equal to `&'a T`: the *item*s being produced are of type `&'a T`.

**Comment by frewsxcv** [comment]
The Rust book has more information on a trait's "associated types":

- https://doc.rust-lang.org/book/ch19-03-advanced-traits.html#specifying-placeholder-types-in-trait-definitions-with-associated-types

If you have any more questions, let us know!
