### ISSUE TITLE
[ER] Add warnings on Nightly for unused features

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust#79733]
This is a diagnostic enhancement request. This code compiles with no warnings on Nightly:

```rust
#![feature(min_const_generics)]
fn main() {}
```

But I'd like rustc to give a warning that the min_const_generics feature is unnecessary for this program. (Not even Clippy seems to give a warning). The same for all the other unused features.

**Comment by ehuss** [comment]
I believe this is a known issue, see #44232.

**Comment by leonardo-m** [comment]
OK, thank you, I suspected that.
