### ISSUE TITLE
#[should_panic(expected = "")] test passes regardless of panic message

### ISSUE THREAD

**Issue by kpreid** [rust-lang/rust#79743]
I was writing a `#[should_panic]` test and I wanted to fill in the specific panic message by using the actual panic, so I wrote code equivalent to

```rust
#[test]
#[should_panic(expected = "")]
fn a_test() {
    panic!("this is not the empty string");
}
```

I expected this to fail with an expected message mismatch. Instead, it passed. Apparently, `#[should_panic(expected = "")]` is treated equivalently to `#[should_panic]`.

### Meta

`rustc --version --verbose`:
```
rustc 1.48.0 (7eac88abb 2020-11-16)
binary: rustc
commit-hash: 7eac88abb2e57e752f3302f02be5f3ce3d7adfb4
commit-date: 2020-11-16
host: x86_64-apple-darwin
release: 1.48.0
LLVM version: 11.0
```

Also reproduces [on Rust Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=1500be3d655d507fd322438c782c3bb9) using stable or `1.50.0-nightly (2020-12-03 5be3f9f10e9fd59ea038)`

**Comment by jonas-schievink** [comment]
`expected` specifies a *substring* that should be present in the panic message. The empty string is a subset of every string, so this is working as expected.

**Comment by kpreid** [comment]
Thank you for the clarification. Hopefully the next person confused finds this issue if they didn't check the documentation!
