### ISSUE TITLE
Integer mismatch incorrectly suggests `T::from()` as LHS of assignment

### ISSUE THREAD

**Issue by Reconcyl** [rust-lang/rust#79756]
I tried the following code ([playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=55fcd9c90df541cf79fa5883f3676d9b)):

```rust
fn main() {
    let mut a: u8 = 0;
    let b: u32 = 0;
    a = b;
}
```

I expected the compiler to recommend using `b.try_into().unwrap()` to convert it into a `u8`. This seems to have been the case [in version 1.37.0](https://tio.run/##S0oszvj/v6i0uCRZQVe3LLWoODM/jys5sUTBxsbV303BLjcxM0@vqJgrLU8BxNTQVKjmUgCCnNQShdzSEoVEK4VSCwVbBQNruHASUMjYCCGWCGQmWXPVcgEN5IJYBTX1/38A). Instead, it produces the following error message on stable, beta, and nightly:

```
error[E0308]: mismatched types
 --> src/main.rs:4:9
  |
4 |     a = b;
  |         ^ expected `u8`, found `u32`
  |
help: you can convert `a` from `u8` to `u32`, matching the type of `b`
  |
4 |     u32::from(a) = b;
  |     ^^^^^^^^^^^^
```

The suggestion is incorrect, as the return value of a function call is not assignable.

**Comment by camelid** [comment]
Fixed in #81325.
