### ISSUE TITLE
Cargo Test on Apple Macbook M1 does not compile and run

### ISSUE THREAD

**Issue by Yepez1997** [rust-lang/rust#79761]
Hi all, for some reason whenever I run cargo test:

**I receive the following compiler message**:

`error: test failed, to rerun pass '--lib'

Caused by:
  process didn't exit successfully: `/Users/xxxxxxxx/Desktop/rustDistributedSytems/kvs/target/debug/deps/kvs-398349f28eabd5b2` (signal: 9, SIGKILL: kill)`

I expect to see the tests show up; however, nothing shows up and rather I get a SIGKILL message thrown at my terminal. I am running on the **MacBook M1 with Big Sur OS**. After looking all over to fix the issue I initially thought this was an OOM issue, but the only programs I am running are on my terminal (all my other applications on the Mac are closed). 

**I expect to see this:**

`failures:
    cli_get
    cli_invalid_get
    cli_invalid_rm
    cli_invalid_set
    cli_invalid_subcommand
    cli_no_args
    cli_rm
    cli_set
    cli_version
    get_non_existent_value
    get_stored_value
    overwrite_value
    remove_key

test result: FAILED. 0 passed; 13 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s`

`rustup --version --verbose`:
```
rustup 1.23.1 (3df2264a9 2020-11-30)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.50.0-nightly (1c389ffef 2020-11-24)`
```

`cargo --version --verbose`:
```
nightly-aarch64-apple-darwin
rustc 1.50.0-nightly (e792288df 2020-12-05)
cargo 1.50.0-nightly (63d0fe434 2020-12-02)
```

I was not able to figure out the issue at first; however after reinstalling rust (following this https://dev.to/redhoodjt1988/how-to-setup-development-environment-on-new-macbook-pro-m1-3kh) I was able to properly run **cargo test**. HOWEVER, the moment _**I added a new crate to my Cargo.toml**_, and ran cargo build then cargo test, I received the same message: (signal: 9, SIGKILL: kill). The moment I took off that crate, my tests are able to compile and run. It is almost as if everytime I **add** a new crate I have to reinstall rust to make my tests compile and run ? Here is the code I used: https://github.com/Yepez1997/rustDSSCourse/tree/master

In addition, whenever I run **cargo run** after adding a new crate:

`    Finished dev [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/kvs`
zsh: killed     cargo run`

zshell terminal gets killed

**Comment by ElliotSis** [comment]
Experiencing the same issue here. Running `cargo clean` to do a fresh build after adding a new crate fixes it.

Visual Studio Code with rust-analyzer also wasn’t working, I had to replace the `cargo` command with the following in `settings.json`:
```
"rust-analyzer.runnables.overrideCargo": "arch -arm64 cargo",
```

I think this happens when attempting to run an ARM binary from Rosetta x86 emulation

**Comment by nagisa** [comment]
The SIGKILL is coming from mac's codesigning and verification. This is not a Rust or Cargo bug, hence closing.

See [this thread](https://rust-lang.zulipchat.com/#narrow/stream/242906-t-compiler.2Farm/topic/macOS.20build.20scripts.20and.20SIGKILL) and especially [this message](https://rust-lang.zulipchat.com/#narrow/stream/242906-t-compiler.2Farm/topic/macOS.20build.20scripts.20and.20SIGKILL/near/218462817). If you continue to have issues with getting your macOS run binaries, I suggest creating a new thread on Zulip where the issue with your mac can be debugged more quickly.

**Comment by Yepez1997** [comment]
removing the potentially old binaries x86_64 using rustup self uninstall + reinstalling from scratch  + running cargo clean fixed the issue
