### ISSUE TITLE
find at fmt code

### ISSUE THREAD

**Issue by SmiteWindows** [rust-lang/rust#79763]
thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', compiler\rustc_middle\src\ty\query\mod.rs:235:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust-clippy/issues/new

note: Clippy version: clippy 0.0.212 (e792288d 2020-12-05)

**Comment by jonas-schievink** [comment]
Duplicate of https://github.com/rust-lang/rust/issues/79661, presumably
