### ISSUE TITLE
rustdoc -D warnings doesn't fail for all warnings

### ISSUE THREAD

**Issue by cmichi** [rust-lang/rust#79792]
#### I tried this code:

```bash
/// See [`foo:Foo`].
/// ```rust
fn main() {}

```

#### I expected to see this happen:
The env variable `-Dwarnings` is supposed to make rustdoc treat warnings as errors. For `export RUSTDOCFLAGS=""` the run below outputs only warnings, no errors. For `RUSTDOCFLAGS="-Dwarnings"` I would have expected both warnings to now be errors.

```
$ export RUSTDOCFLAGS="-Dwarnings"
$ cargo doc
 Documenting rustdoc-bug v0.1.0 (/tmp/bug/rustdoc-bug)
error: unresolved link to `foo:Foo`
 --> src/main.rs:1:10
  |
1 | /// See [`foo:Foo`].
  |          ^^^^^^^^^ no item named `foo:Foo` in scope
  |
  = note: `-D broken-intra-doc-links` implied by `-D warnings`
  = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`

error: Rust code block is empty
 --> src/main.rs:2:5
  |
2 | /// ```rust
  |     ^^^^^^^

error: aborting due to previous error; 1 warning emitted```
```

#### Instead, this happened:
Only one of the warnings is switched to an error.

```
$ export RUSTDOCFLAGS="-Dwarnings"
$ cargo doc
 Documenting rustdoc-bug v0.1.0 (/tmp/bug/rustdoc-bug)
error: unresolved link to `foo:Foo`
 --> src/main.rs:1:10
  |
1 | /// See [`foo:Foo`].
  |          ^^^^^^^^^ no item named `foo:Foo` in scope
  |
  = note: `-D broken-intra-doc-links` implied by `-D warnings`
  = help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`

warning: Rust code block is empty
 --> src/main.rs:2:5
  |
2 | /// ```rust
  |     ^^^^^^^

error: aborting due to previous error; 1 warning emitted```
```

This is also problematic because for warnings the exit code is still `0`, so a CI setup might not detect the failure:

```
$ cat src/main.rs 
/// ```rust
fn main() {}
$ RUSTDOCFLAGS="-Dwarnings" cargo doc
warning: Rust code block is empty
 --> src/main.rs:1:5
  |
1 | /// ```rust
  |     ^^^^^^^

warning: 1 warning emitted

    Finished dev [unoptimized + debuginfo] target(s) in 0.00s
$ echo $?
0
```

### Meta

`rustc --version --verbose`:
```
rustc 1.50.0-nightly (1c389ffef 2020-11-24)
```

**Comment by jyn514** [comment]
This happens because the rustdoc warning isn't emitted as a lint, so it isn't subject to lint levels. I don't think there was any reason for not making it a lint, so the fix is probably to use `struct_span_lint` instead of the current hard-coded warning: https://github.com/rust-lang/rust/blob/b5ff9c3d052c2c3d5f26076362f38643f6e48680/src/librustdoc/passes/check_code_block_syntax.rs#L60
