### ISSUE TITLE
Unable to build rust on RHEL7 due to GLIBC version

### ISSUE THREAD

**Issue by lewis6991** [rust-lang/rust#79800]
I can't manage to get rust built on Red Hat 7 (which has `GLIBC==2.17`). I tried installing `GLIBC` from Homebrew/Linuxbrew however the build scripts don't seem to pick it up. 

Note: I also get the same error when running `brew install rust` but I don't think it is a brew issue.

```
brew install glibc
git clone https://github.com/rust-lang/rust.git
./x.py build
```

However I got this error:
```
...
extracting .../rust/build/cache/2020-11-19/rustfmt-nightly-x86_64-unknown-linux-gnu.tar.gz
  Downloaded proc-macro-error-attr v1.0.4
  Downloaded proc-macro-error v1.0.4
  Downloaded serde_json v1.0.59
  Downloaded version_check v0.9.1
  Downloaded toml v0.5.7
  Downloaded merge v0.1.0
  Downloaded cc v1.0.60
  Downloaded merge_derive v0.1.0
  Downloaded libc v0.2.79
  Downloaded num-traits v0.2.12
  Downloaded 10 crates (842.5 KB) in 2.36s
   Compiling proc-macro2 v1.0.19
   Compiling unicode-xid v0.2.1
   Compiling syn v1.0.38
   Compiling version_check v0.9.1
   Compiling autocfg v1.0.0
   Compiling memchr v2.3.3
   Compiling lazy_static v1.4.0
   Compiling serde_derive v1.0.115
   Compiling cfg-if v0.1.10
   Compiling libc v0.2.79
   Compiling serde v1.0.115
   Compiling log v0.4.11
   Compiling ryu v1.0.5
   Compiling regex-syntax v0.6.18
   Compiling same-file v1.0.6
   Compiling fnv v1.0.7
   Compiling serde_json v1.0.59
   Compiling cc v1.0.60
   Compiling unicode-width v0.1.8
   Compiling itoa v0.4.6
   Compiling bootstrap v0.0.0 (.../rust/src/bootstrap)
   Compiling opener v0.4.1
   Compiling build_helper v0.1.0 (.../rust/src/build_helper)
   Compiling proc-macro-error-attr v1.0.4
   Compiling proc-macro-error v1.0.4
   Compiling thread_local v1.0.1
   Compiling crossbeam-utils v0.7.2
   Compiling num-traits v0.2.12
   Compiling walkdir v2.3.1
   Compiling getopts v0.2.21
   Compiling cmake v0.1.44
   Compiling quote v1.0.7
   Compiling aho-corasick v0.7.13
   Compiling bstr v0.2.13
   Compiling time v0.1.43
   Compiling filetime v0.2.12
   Compiling num_cpus v1.13.0
   Compiling regex v1.3.9
   Compiling globset v0.4.5
   Compiling ignore v0.4.16
error: /lib64/libc.so.6: version `GLIBC_2.18' not found (required by .../rust/build/bootstrap/debug/deps/libproc_macro_error_attr-6113814084e74210.so)
   --> /home/lewrus01/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro-error-1.0.4/src/lib.rs:284:9
    |
284 | pub use proc_macro_error_attr::proc_macro_error;
    |         ^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: could not compile `proc-macro-error`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
failed to run: .../rust/build/x86_64-unknown-linux-gnu/stage0/bin/cargo build --manifest-path .../rust/src/bootstrap/Cargo.toml
Build completed unsuccessfully in 0:13:55
```

### Meta

<details>
  <summary> `lsb_release -a`` </summary>

```
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: RedHatEnterpriseServer
Description:    Red Hat Enterprise Linux Server release 7.4 (Maipo)
Release:        7.4
Codename:       Maipo
```
</details>

<details>
  <summary> `ldd --version` </summary>

```
ldd (GNU libc) 2.23
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.
```
</details>

<details>
  <summary> `/devtools/linuxbrew/lib/libc.so.6 --version` </summary>

```
GNU C Library (GNU libc) stable release version 2.23, by Roland McGrath et al.
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
Compiled by GNU CC version 4.8.5 20150623 (Red Hat 4.8.5-16).
Available extensions:
        crypt add-on version 2.1 by Michael Glad and others
        GNU Libidn by Simon Josefsson
        Native POSIX Threads Library by Ulrich Drepper et al
        BIND-8.2.3-T5B
libc ABIs: UNIQUE IFUNC
For bug reporting instructions, please see:
<http://www.gnu.org/software/libc/bugs.html>.
```
</details>

<details>
  <summary> `/lib/libc.so.6 --version` </summary>

```
GNU C Library (GNU libc) stable release version 2.17, by Roland McGrath et al.
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
Compiled by GNU CC version 4.8.5 20150623 (Red Hat 4.8.5-16).
Compiled on a Linux 3.10.0 system on 2017-11-22.
Available extensions:
        The C stubs add-on version 2.1.2.
        crypt add-on version 2.1 by Michael Glad and others
        GNU Libidn by Simon Josefsson
        Native POSIX Threads Library by Ulrich Drepper et al
        BIND-8.2.3-T5B
        RT using linux kernel aio
libc ABIs: UNIQUE IFUNC
For bug reporting instructions, please see:
<http://www.gnu.org/software/libc/bugs.html>.
```
</details>

<details>
  <summary> `/lib64/libc.so.6 --version` </summary>

  ```
  GNU C Library (GNU libc) stable release version 2.17, by Roland McGrath et al.
  Copyright (C) 2012 Free Software Foundation, Inc.
  This is free software; see the source for copying conditions.
  There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
  PARTICULAR PURPOSE.
  Compiled by GNU CC version 4.8.5 20150623 (Red Hat 4.8.5-16).
  Compiled on a Linux 3.10.0 system on 2017-11-22.
  Available extensions:
          The C stubs add-on version 2.1.2.
          crypt add-on version 2.1 by Michael Glad and others
          GNU Libidn by Simon Josefsson
          Native POSIX Threads Library by Ulrich Drepper et al
          BIND-8.2.3-T5B
          RT using linux kernel aio
  libc ABIs: UNIQUE IFUNC
  For bug reporting instructions, please see:
  <http://www.gnu.org/software/libc/bugs.html>.
  ```
</details>

The issue [here](https://users.rust-lang.org/t/why-would-rust-ran-in-linuxbrew-try-to-link-to-system-libc/37435) looks identical to this one, however that has been closed with no updates.

**Comment by jyn514** [comment]
@lewis6991 is there a reason you're installing from source instead of using rustup or a package manager?

**Comment by lewis6991** [comment]
I originally tried to use homebrew but I'm getting this error. Homebrew is installing from source because it is installed to a non-standard prefix so won't use the bottled rust.

**Comment by 12101111** [comment]
You need `patchelf` to edit the interpreter path of snapshot toolchain to the prefix one ( maybe `/devtools/linuxbrew/lib/ld-linux-x86-64.so.2`)

**Comment by mati865** [comment]
Sounds like more brew issue than Rust one?
I have no idea what brew is but for me seems it makes Rust link to brew shipped glibc. Then binaries are ran outside of brew with system glibc which is older.

**Comment by lewis6991** [comment]
> You need `patchelf` to edit the interpreter path of snapshot toolchain to the prefix one ( maybe `/devtools/linuxbrew/lib/ld-linux-x86-64.so.2`)

Thanks, I think I've got it to work (TBD), but one issue is that `bootstrap.py` has no option (AFAIK) to fetch stage0 without building. Are there any potential workarounds to this or do we need to modify `bootstrap.py` to make this work?

> Sounds like more brew issue than Rust one?
> I have no idea what brew is but for me seems it makes Rust link to brew shipped glibc. Then binaries are ran outside of brew with system glibc which is older.

Brew is just a package manager that builds tools locally without modifying system directories. It's pretty useful for working on machines that don't have root.

I think it's a rust issue because the issue is that the snapshot builds used to bootstrap link to system libs, so the solution is to modify these snapshot builds so they can use brew's libs. If a snapshot wasn't used and was built from source instead then this wouldn't be an issue. (Someone correct me if I'm wrong)

**Comment by mati865** [comment]
> I think it's a rust issue because the issue is that the snapshot builds used to bootstrap link to system libs, so the solution is to modify these snapshot builds so they can use brew's libs. If a snapshot wasn't used and was built from source instead then this wouldn't be an issue. (Someone correct me if I'm wrong)

Bootstrap compiler you are talking about is linked to glibc 2.11 (for increased compatibility). Since your OS provides glibc 2.17 the only place where glibc 2.18 can come from is brew.

**Comment by lewis6991** [comment]
Hmm ok, but FWIW I get this issue when building directly from source (no brew). I can try building with brew packages stripped from `PATH` just to be sure.

The build seems to work when using patchelf:
```
patchelf --set-interpreter $BREW_PREFIX/lib/ld-linux-x86-64.so.2 \
    build/x86_64-unknown-linux-gnu/stage0/bin/rustc

patchelf --set-rpath $(pwd)/build/x86_64-unknown-linux-gnu/stage0/lib/:$BREW_PREFIX/lib \
    build/x86_64-unknown-linux-gnu/stage0/lib/*.so 

make
```

**Comment by lewis6991** [comment]
After lots of debugging and headaches I can confirm **this is an issue with brew**. Still working out the specifics but stripping brew packages from my `PATH` resolved the issue.

Many thanks for the help.
