### ISSUE TITLE
pointer do not get auto dereferenced 

### ISSUE THREAD

**Issue by chandreshpatel16** [rust-lang/rust#79802]
### Code

```rust
fn main() {
  let x = 10;
  let r = &x;
  let rr = &r; // `rr` is a `&&x`

  if is_ten(rr) {
    println!("Same!");
  }
}

fn is_ten(val: &&i32) -> bool { //If we change this to &i32  this works, but contracts type check that is required &i32 but send &&i32
  *val == 10                    //if we keep as it is compiler give error on *val ....
}
```

### Meta

`rustc --version --verbose`:

localhostl:rust chandreshpatel$ rustc -V
rustc 1.46.0 (04488afe3 2020-08-24)

### Error output

```
  Compiling playground v0.0.1 (/playground)
error[E0277]: can't compare `&i32` with `{integer}`
  --> src/main.rs:12:8
   |
12 |   *val == 10                    //if we keep as it is compiler give error on *val ....
   |        ^^ no implementation for `&i32 == {integer}`
   |
   = help: the trait `PartialEq<{integer}>` is not implemented for `&i32`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by jyn514** [comment]
@chandreshpatel16 it works if you use `**val == 10` instead. Is there a reason you think this is a bug?

**Comment by chandreshpatel16** [comment]
There are two things i need to know  
1. when we say  rust check argument in function invocation then ...  in above case we are passing  let x = 10; let r = &x; let rr = &r;  fn is_ten(val: &i32) -> bool { *val == 10  }  val is of type  &i32 and we call func with  is_ten(rr) where rr is of type &&i32.
is &i32 same type as &&i32 ?? ....  ///Note this compiles , no error

2.In rust  pointer gets dereferenced by compiler(As above why not get auto dereferencing ?)..  like   let x = 10; let r = &x; let rr = &r;  fn is_ten(val: &&i32) -> bool { *val == 10  }   and we call func with  is_ten(rr) where both val and rr is of type &&i32 
i.e both are same  while dereferencing  we get error type different...

**Comment by jyn514** [comment]
well, `rr` and `val` are both `&&i32`, yes, but `10` is not. The type error isn't where you call the function, it's in the function body.

**Comment by chandreshpatel16** [comment]
thx ...i got it... my mistake i am comparing two two diff types......
