### ISSUE TITLE
Empty `TokenStream` is provided to attribute procedural macro on trait alias

### ISSUE THREAD

**Issue by hyd-dev** [rust-lang/rust#79825]
I tried this code:

```rust
use proc_macro::TokenStream;

#[proc_macro_attribute]
pub fn give_me_trait_alias(_: TokenStream, input: TokenStream) -> TokenStream {
    assert!(!input.is_empty());
    Default::default()
}
```
and
```rust
#[give_me_trait_alias]
trait Alias = Sized;
```

I expected to see this happen: the compiler complained `#![feature(trait_alias)]` was missing, or on nightly, after adding `#![feature(trait_alias)]`, compiled successfully, just like [built-in `#[allow]` on trait alias](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=4de7ef170b4c0622f5a6e6b081250a6d).

Instead, this happened: the assertion failed. The compiler gave an empty `TokenStream` as `input` to the procedural macro:
```
error: custom attribute panicked
 --> tests/trait_alias.rs:3:1
  |
3 | #[give_me_trait_alias]
  | ^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: message: assertion failed: !input.is_empty()
```

**Edit:** I found this in the compiler's log:
```
INFO rustc_parse cached tokens found, but they're not "probably equal", going with stringified version
INFO rustc_parse cached   tokens: trait Alias = Sized ;
INFO rustc_parse reparsed tokens: 
INFO rustc_parse cached   tokens debug: TokenStream([(Token(Token { kind: Ident("trait", false), span: tests/trait_alias.rs:4:1: 4:6 (#0) }), Alone), (Token(Token { kind: Ident("Alias", false), span: tests/trait_alias.rs:4:7: 4:12 (#0) }), Alone), (Token(Token { kind: Eq, span: tests/trait_alias.rs:4:13: 4:14 (#0) }), Alone), (Token(Token { kind: Ident("Sized", false), span: tests/trait_alias.rs:4:15: 4:20 (#0) }), Joint), (Token(Token { kind: Semi, span: tests/trait_alias.rs:4:20: 4:21 (#0) }), Alone)])
INFO rustc_parse reparsed tokens debug: TokenStream([])
```
https://github.com/rust-lang/rust/blob/8080f54677e57ca56f20f514f14affc64827d66b/compiler/rustc_parse/src/lib.rs#L372-L375

### Meta
I tried this with:
- nightly-2020-12-08 (3d6705aa5abffe94c83bf09af8c3ba3c599845fc)
- nightly-2020-12-07 (0f6f2d681b39c5f95459cd09cb936b6ceb27cd82)
- beta (bd26e4e544992e52f2080906f71b2f1e6dc1b14a)
- stable (7eac88abb2e57e752f3302f02be5f3ce3d7adfb4)

cc #41517

**Comment by Aaron1011** [comment]
The pretty-print/reparse has been removed, so this should hopefully be fixed on the latest nightly.

**Comment by hyd-dev** [comment]
Confirmed that this is fixed in latest nightly, thanks! :heart: Do I need to leave this issue open (possibly for a regression test)?

**Comment by Aaron1011** [comment]
That sounds like a good idea.
