### ISSUE TITLE
rustc does not accept object files as input

### ISSUE THREAD

**Issue by Subsentient** [rust-lang/rust#79821]
Hi, so apparently rustc does not provide a means to use raw object files (.o) as input without creating a static library.

For interoperability, debugging, etc,  it can be very useful to just link in an object compiled with .e.g. "gcc -c", without having to run ar and ranlib to create a static library, and whatever mess might be needed in MSVC-land. As rustc allows only one source input file and only provides methods to link, not to add objects, there's currently no way to do this without extra work.

I think this is probably a bug, as almost all other systems programming languages provide simple methods of doing this, and I don't imagine it would be difficult to implement. Perhaps an "-io myobj.o" type syntax?

**Comment by jonas-schievink** [comment]
rustc is not a linker, but you can use `-Clink-arg(s)` to pass arbitrary arguments to the linker, so this already works.
