### ISSUE TITLE
Method recv() of UdpSocket don't have any response and blocking.

### ISSUE THREAD

**Issue by efikarl** [rust-lang/rust#79823]
I try to write a tftp client on Windows OS  10.0.19042 Build 19042. UdpSocket don't works for me when I send a WRQ, but no ACK is received.

I tried this code:

```rust
use std::net::UdpSocket;

fn main() -> std::io::Result<()> {
    let socket = UdpSocket::bind(("localhost", 0xffff))?;
    socket.connect("localhost:69")?;

    let wrq: Vec<u8> = vec![0, 2,
    'a' as u8, 'z' as u8, 'A' as u8, 'Z' as u8, '0' as u8, '9' as u8, '-' as u8, '0' as u8, '.' as u8, 't' as u8, 'x' as u8, 't' as u8, 0,
    'N' as u8, 'E' as u8, 'T' as u8, 'A' as u8, 'S' as u8, 'C' as u8, 'I' as u8, 'I' as u8, 0 ];
    socket.send(&wrq)?;

    let mut buf: Vec<u8> = Vec::new();
    socket.recv(&mut buf)?;

    Ok(())
}
```

I expected to see this happen: *socket.recv(&mut buf) works*

Instead, this happened: *socket.recv(&mut buf) didn't receive any thing and blocking from TFTP server.*

### Meta

`rustc --version --verbose`:
```
rustc 1.47.0 (18bf6b4f0 2020-10-07)
binary: rustc
commit-hash: 18bf6b4f01a6feaf7259ba7cdae58031af1b7b39
commit-date: 2020-10-07
host: x86_64-pc-windows-msvc
release: 1.47.0
LLVM version: 11.0
```

<details><summary>Not crash, so no backtrace</summary>
<p>

```
<NA>
```

</p>
</details>

**Comment by camelid** [comment]
From the docs:

> The function must be called with valid byte array buf of sufficient size to hold the message bytes. If a message is too long to fit in the supplied buffer, excess bytes may be discarded.

Passing an empty `Vec`, which is what you're doing, is equivalent to passing an empty slice. So, all the bytes are discarded. Does initializing `buf` to have more elements with `vec![0; N]` fix this?

**Comment by camelid** [comment]
Also see https://stackoverflow.com/questions/60402414/why-does-u8-work-as-a-buffer-for-udpsocket-when-vec-doesnt.

**Comment by camelid** [comment]
I'm closing this. Reopen if you still think there is a bug.
