### ISSUE TITLE
asm!() truncates $'s in AT&T syntax with local label

### ISSUE THREAD

**Issue by carado** [rust-lang/rust#79837]
I am trying to run the asm!() instruction `mov [rsp], 3f` (move the forward local label `3` into the memory pointed to by register rsp).
My general template is:
```rust
#![feature(asm)]

fn main() {
  unsafe {
    asm!(
      ".intel_syntax", // can be changed to .att_syntax for cases below
      "mov [rsp], 3f",
      "3:",
    );
  }
}
```

(as well as
```c
int main() {
  __asm__ volatile (
    ".intel_syntax\n"
    "mov [rsp], 3f\n"
    "3:"
  );
}
```
for testing in clang C)

Here are the results I get for various instructions under both syntaxes (Intel and AT&T) and in both languages:
1. `mov [rsp], 3f` (Intel, C & Rust) → "invalid operand for instruction"
2. `mov [rax], 3f` (Intel, C & Rust) → "invalid operand for instruction"
3. `movabsq 3f, [%rsp]` (AT&T, C & Rust) → "invalid operand for instruction"
4. `movabsq 3f, [%rax]` (AT&T, C & Rust) → compiles (shouldn't; `3f` should be `$3f`)
5. `movabsq $3f, [%rsp]` (AT&T, C) → compiles
6. `movabsq $3f, [%rsp]` (AT&T, Rust) → "invalid operand for instruction" (this is the weird one!)
7. `movabsq $3f, [%rax]` (AT&T, C & Rust) → compiles
8. `movabsq $$$$$$3f, [%rsp]` (AT&T, C) → "invalid token in expression"
9. `movabsq $$$$$$3f, [%rsp]` (AT&T, Rust)→ "invalid operand for instruction"
10. `movabsq $$$$$$3f, [%rax]` (AT&T, C) → "invalid token in expression"
11. `movabsq $$$$$$3f, [%rax]` (AT&T, Rust) → compiles (??)

1 and 2 are unfortunate quirks of LLVM assembly, I guess; and so must be 4. The weird part is the inconsistencies between C and Rust, which leads me to think that Rust is just removing all `$`'s from asm!(). Indeed, if you remove all `$`'s, Rust becomes fully consistent with clang C:
* cases 6 and 9 is being treated like case 3 and fail
* cases 7 and 11 are being treated like case 4 and weirdly compile (as per an apparent LLMV quirk)

Thus, unless cases 1 and 2 are my own fault for not knowing how to do the operation in question in Intel LLVM assembly (definitely a possiblity!), I'm out of options to do the operation I originally wanted.
Sorry for the long post, I wanted to be as clear as possible about why I think there is some amount of bug in rust that makes some operations impossible (save for, say, working out instruction offsets manually, or assembling some machine code separately).

(of possible note: https://github.com/rust-lang/rust/issues/74558 mentions the workaround of not using local labels 0 and 1, but as you can see those don't seem to work here)

(the #llvm IRC mentioned using `lea` in place of `mov` but I can't get that working either)

### Meta

`rustc --version --verbose`:
```
rustc 1.50.0-nightly (0f6f2d681 2020-12-06)
binary: rustc
commit-hash: 0f6f2d681b39c5f95459cd09cb936b6ceb27cd82
commit-date: 2020-12-06
host: x86_64-unknown-linux-gnu
release: 1.50.0-nightly
```

**Comment by joshtriplett** [comment]
@carado Please don't use `.intel_syntax` or `.att_syntax` inside the asm string. `asm!` already uses Intel syntax (with the "noprefix" option) by default, and if you want to switch to AT&T syntax, you should use the `asm!` option `att_syntax` (like this: `asm!("...", other, params, att_syntax)`). LLVM understands assembly syntax, and needs to know what syntax it's using to do substitutions properly.

This may be part of why you ran into issues and discrepancies in the syntax the compiler supports. Can you give it a try with those options, and see how that affects the results?

You also need to either declare an operand or make some space on the stack (that you clean up afterwards), rather than just overwriting the stack.

**Comment by carado** [comment]
Thank you for taking the time to answer.
> @carado Please don't use `.intel_syntax` or `.att_syntax` inside the asm string.

The reason I wanted to do that is because I would actually like to use intel syntax for everything, but as I cannot get `mov [rsp], 3f` to work in Intel, I thought I'd do something like
```rust
asm!(
   // intel asm…
   ".att_syntax", "my one instruction in at&t syntax", ".intel_syntax",
   // intel asm again…
);
```
(which seems to work okay with various other instructions; just not ones that have a `$` in them)

> if you want to switch to AT&T syntax, you should use the `asm!` option `att_syntax` (like this: `asm!("...", other, params, att_syntax)`)

When I do this even with simple asm, I get:
```
   Compiling rust29 v0.1.0 (/home/carado/tmp/rust29)
error: expected operand, options, or additional template string
 --> src/main.rs:5:27
  |
5 |         asm!("xorq %rax, %rax", att_syntax);
  |                                 ^^^^^^^^^^ expected operand, options, or additional template string
```
(and the `RUSTFLAGS='-C llvm-args=-x86-asm-syntax=att' cargo build` I've seen floating around doesn't seem to affect how the asm is parsed, either)

> You also need to either declare an operand or make some space on the stack (that you clean up afterwards), rather than just overwriting the stack.

Sure, in my actual code rather than test code I am indeed taking care to do that. At the moment I'm just trying to get the instruction I want to compile at all in simple testing code.

**Comment by joshtriplett** [comment]
@carado Sorry, that should be `options(att_syntax)`, not just `att_syntax`: `asm!("...", other, params, options(att_syntax))`.

**Comment by joshtriplett** [comment]
Here's an example of how to accomplish what you want using the default Intel syntax: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=fea104d10cf74d216e38b69bcb76052a

```rust
#![feature(asm)]

fn main() {
    let mut addr1: u64;
    let mut addr2: u64;
    unsafe {
        asm!(
            "lea {addr1}, 1f[rip]",
            "1:",
            "lea {addr2}, 2f[rip]",
            "2:",
            addr1 = out(reg) addr1,
            addr2 = out(reg) addr2,
        );
    }
    println!("{:?}\n{:#x}\n{:#x}", main as *const (), addr1, addr2);
}
```

**Comment by carado** [comment]
Thanks! `asm!("movabsq $3f, [%rax]", "3:", options(att_syntax));` does compile, so I guess I can just use that and convert the rest of my asm to AT&T if I can't get Intel to work.

As for `lea {addr1}, 1f[rip]`, this is syntax I'm unfamiliar with. It does compile, though `lea [rsp], 1f[rip]` doesn't (I'm not sure what `[rip]` does here ? The `rip` register shouldn't need to be accessed to just insert the address of the label `1f` as a value)

**Comment by joshtriplett** [comment]
@carado These days, many programs use position-independent code (for many reasons including the use of ASLR for security), so they do all addressing relative to the instruction pointer. You need that syntax to obtain the appropriate address when you're in position-independent code. If you're compiling position-dependent code (which you usually shouldn't), you can just directly move `1f`, but if you try that in position-independent code you'll get a link error about an invalid relocation. (Try playing with that starting from the playground example I linked to.)

**Comment by joshtriplett** [comment]
@carado As for loading into `[rsp]`, the reason that doesn't compile has nothing to do with AT&T or Intel syntax; you can't `lea` directly into a memory location, you have to do it into a register first. (Most x86 instructions don't accept two memory addresses; you have to do memory-to-register and then register-to-memory.)

**Comment by carado** [comment]
Thank you again for the help.

I don't get a linking error when compiling
```rust
asm!(
  "movabsq $3f, %rax",
  "3:",
  "jmp *%rax",
  options(att_syntax),
);
```
in fact, this code works fine, and gdb confirms that the correct absolute address of `3:` is loaded into `rax`
```
(gdb) disassemble
Dump of assembler code for function _ZN6rust294main17h0036c8f76f3b37ddE:
   0x0000555555559160 <+0>:	push   %rax
   0x0000555555559161 <+1>:	movabs $0x55555555916b,%rax
=> 0x000055555555916b <+11>:	jmp    *%rax
   0x000055555555916d <+13>:	pop    %rax
   0x000055555555916e <+14>:	ret
End of assembler dump.
(gdb) p/x $rax
$3 = 0x55555555916b
```
I am merely trying to write the Intel equivalent of `movabsq $3f, [%rsp]`.

**Comment by carado** [comment]
Oh, apparently it just isn't possible to move a 64-bit immediate to memory pointed to by a register.
I guess `movabsq $3f, [%rsp]` must truncate it (and thus be indeed incorrect).

**Comment by joshtriplett** [comment]
@carado The intel-syntax equivalent would be `mov rax, offset 3f`, but it looks like LLVM doesn't accept that, though GCC does. I'll file bugs on that.

**Comment by joshtriplett** [comment]
Filed as https://github.com/rust-lang/rust/issues/79874

**Comment by joshtriplett** [comment]
Until that issue is fixed (which will likely require fixing LLVM first), you have three options: use AT&T syntax, use an `lea` instruction (`lea rax, 3f`), or use position-independent code and an `lea` instruction. A worked example of the latter:

```rust
#![feature(asm)]

fn main() {
    let mut value: u64;
    unsafe {
        asm!(
          "mov {value}, 1",
          "lea rax, 3f[rip]",
          "jmp rax",
          "mov {value}, 2",
          "3:",
          value = out(reg) value,
          out("rax") _,
        );
    }
    dbg!(value);
}
```

This loads the address of label `3f`, jumps to it, and uses `value` to prove that the jump worked; the program will print `1`.
