### ISSUE TITLE
some buttons on the rustdoc search results page aren't properly marked up

### ISSUE THREAD

**Issue by sersorrel** [rust-lang/rust#79859]
on the rustdoc search results page, it's not possible to focus the tabs with <kbd>tab</kbd> or activate them with vimium:

![image](https://user-images.githubusercontent.com/9433472/101664538-dffc3600-3a43-11eb-8029-bb7e479393fc.png)

in addition, the "help" button beside the search field is just a plain `<span>`, so you can't focus it with <kbd>tab</kbd>. (the "settings" button is an `<a>`, so that one is focusable.)

see also #65212

**Comment by jyn514** [comment]
cc https://github.com/rust-lang/rust/issues/65212

**Comment by GuillaumeGomez** [comment]
So replacing that with `<a>` would fix them? Well, I'll make the PR tomorrow then!

**Comment by sersorrel** [comment]
i think so, though you'd also need to specify a `href` to get them to be tab-focusable, i think (imo `<button>` might be more semantically correct, though i'm no expert; that also comes with more potential styling issues). there are also [a couple of css rules](https://github.com/rust-lang/rust/blob/c16d52db7778fba1c8b6c07b06510cfd6c32ae4f/src/librustdoc/html/static/rustdoc.css#L1270) specific to the settings button that maybe should also apply to the help button (particularly the `outline: none`).

**Comment by GuillaumeGomez** [comment]
I'll find a way, don't worry. ;)
