### ISSUE TITLE
asm! should catch attempts to use `.intel_syntax` or `.att_syntax` and suggest appropriate options instead

### ISSUE THREAD

**Issue by joshtriplett** [rust-lang/rust#79869]
People used to gcc/clang inline assembly may try using the `.intel_syntax` or `.att_syntax` directives directly in the assembly string, which can cause issues. Ideally, we should detect attempts to use those directives. Attempting to use `.intel_syntax` should generate an error stating that that's the default. Attempting to use `.att_syntax` should generate an error and point to the `att_syntax` option, ideally with a rustfix-applicable suggestion.

**Comment by asquared31415** [comment]
Is anyone currently working on this?  I would like to do it if not.

**Comment by joshtriplett** [comment]
@asquared31415 Not to my knowledge, no.
