### ISSUE TITLE
impl blocks in private modules visible on a public struct

### ISSUE THREAD

**Issue by Subsentient** [rust-lang/rust#79876]
It seems that if the type is visible, an impl's pub methods can be used, even if such an impl is encased in multiple private modules.

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2015&gist=bf21f358b4b57075d1243a3b07d93da9

**Comment by jonas-schievink** [comment]
This is working as expected, `impl`s are always as public as the type/trait they're for.

**Comment by Subsentient** [comment]
Is there anywhere this is documented? I've been looking, I can't find that behaviour listed anywhere.

**Comment by jonas-schievink** [comment]
Doesn't look like it

**Comment by Subsentient** [comment]
> Doesn't look like it

Then that's obviously an issue in and of itself.
