### ISSUE TITLE
rustdoc: Don't override system keyboard shortcuts for search results tab-switcher

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#79872]
Once #79862 is merged, rustdoc will be overriding the macOS system keyboard
shortcuts <kbd>Ctrl-↑</kbd> and <kbd>Ctrl-↓</kbd> (Control–Up Arrow and Control–Down Arrow).

Personally, I don't use these shortcuts, but I imagine others do. We should find
different key combinations that won't override system shortcuts.

*See the discussion around <https://github.com/rust-lang/rust/pull/79862#issuecomment-742118057>.*

cc @GuillaumeGomez @Manishearth

**Comment by Manishearth** [comment]
Not a fan of overriding system shortcuts, but I do think this is less pressing than the tab issue. Wondering what suggestions people have.

**Comment by GuillaumeGomez** [comment]
Wouldn't replace `ctrl` with `cmd` on mac be enough? It's generally what's done for most shortcuts. I just need a confirmation before making the fix.

**Comment by Manishearth** [comment]
I believe cmd-up/down is also a system shortcut? If it's not that would work.

**Comment by GuillaumeGomez** [comment]
To be checked then! I'll try to do that this evening or tomorrow.

**Comment by camelid** [comment]
Command–Up Arrow and Command–Down Arrow are used for scrolling to the top and bottom of the page in many browsers, including Safari and Firefox (and I assume Google Chrome). I don't think we should override that if we're looking to be as accessible as possible.

Unfortunately, many of the keyboard shortcut options are already taken :/

**Comment by GuillaumeGomez** [comment]
Arf. :-/

**Comment by jsha** [comment]
What about using keys without modifiers? E.g. `t` to cycle through the tabs, or `<-` and `->`. This would mean you'd need to hit down or tab to take focus out of the search box, but I think that's an okay tradeoff.

**Comment by GuillaumeGomez** [comment]
I'd personnally prefer that those events are only handled when we have the focus on the search input.

**Comment by Manishearth** [comment]
I think using keys for navigation when you're in a search view but outside the search box makes sense.

**Comment by GuillaumeGomez** [comment]
That could work. I don't know how many of our users have their own letter keys bound to something, not sure if that would be a problem?
