### ISSUE TITLE
I-labels should have 'Issue' in the description

### ISSUE THREAD

**Issue by pickfire** [rust-lang/rust#79887]
I noticed that `I-slow` and friends labels does not have `Issue: ` as part of the description, having it would make it more consistent with the rest and being clearer what is `I`.

**Comment by jyn514** [comment]
This one is a little odd because not all `I-` labels are actually about issues. `I-compilemem` and `I-slow` get used a lot for PRs, for instance. Maybe they shouldn't be marked `I-`? Not sure what would replace that, though.

**Comment by jyn514** [comment]
I added `Issue:` to everything that didn't have either 'problems and improvements' or 'issue' already.

**Comment by pickfire** [comment]
But 'problems and improvements` is still `Issue` right?

**Comment by jyn514** [comment]
@pickfire no, that also describes PRs fixing an issue, and PRs are not themselves issues.

**Comment by pickfire** [comment]
A few more

- `I-compilemem` - `Issue: Compile memory usage problems and improvements.` (I wonder if these should be `Area`)
- `I-compiletime` - `Issue: Compile time problems and improvements.`
- `I-needs-decision` - I wonder if this can be changed to `needs-decision` (yellow color) which is similar to `needs-fcp`?
- `I-slow` - `Issue: Generated code performance problems and improvements.`
- `I-heavy` - `Issue: Generated binary size problems and improvements.`
- `I-prioritize` - The "issue" here is different from the others
- `I-nominated` - The "issue" here is different from the others

We could probably drop those "problems and improvements".

**Comment by jyn514** [comment]
I am loath to make those changes unilaterally. If you want to chat about this on Zulip, that might be a better approach so we get more opinions, but I don't want to rename `I-` labels without knowing why they were chosen in the first place.

**Comment by Mark-Simulacrum** [comment]
I don't think there's any need to say "Issue: " -- I'm still not sure what the point of labeling PRs with anything other than S or T labels is, but there's no reason to limit these. I believe (though wasn't around) that I stands for "importance" or something like that; I wouldn't try to read more into it though. I am strongly opposed to changing it though -- it seems not worth the hassle for everyone to relearn, and ultimately the meaning of the prefix just don't matter I think?

I also personally would be happy to drop "Issue: " if we have it on descriptions.

**Comment by pickfire** [comment]
I suggest that because we could easily search for it, we search for "issue" but all tons of others pop up.
