### ISSUE TITLE
Error while calling method on generic const fn in impl block when using `const_trait_impl`

### ISSUE THREAD

**Issue by vn-ki** [rust-lang/rust#79898]
Methods on generic parameters cannot be called inside const fns which are inside an `impl` block.

[playground link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=5672d548cbd29b95657c28dab53b3036)

```rust
#![feature(const_refs_to_cell)]
#![feature(const_fn)]
#![feature(const_precise_live_drops)]
#![feature(const_trait_impl)]
#![allow(incomplete_features)]

trait TestTrait {
    fn test_fn(&self);
}

struct Boo<T> {
    t: T
}

impl<T: TestTrait> Boo<T> {
    const fn foo(t: T) {
        t.test_fn();
        std::mem::forget(t);
    }
}

const fn foo<T: TestTrait>(t: T) {
    t.test_fn();
    std::mem::forget(t);
}

fn main() {}
```

Stderr:

```
error[E0015]: calls in constant functions are limited to constant functions, tuple structs and tuple variants
  --> src/main.rs:17:9
   |
17 |         t.test_fn();
   |         ^^^^^^^^^^^

error: aborting due to previous error
```

Related to: #67792

**Comment by leonardo-m** [comment]
I've just hit this :)

**Comment by jonas-schievink** [comment]
I guess this happens because `impl`s can contain non-const `fn`s, so their trait bounds aren't marked const by astconv. To fix this, we have to change the parameter environment that a `const fn` in an impl sees, even if it does not have any type parameters itself.

**Comment by fee1-dead** [comment]
This is fixed.
