### ISSUE TITLE
regression: reached recursion limit while instantiating

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#79909]
* https://crater-reports.s3.amazonaws.com/beta-1.49-1/beta-2020-11-26/gh/hiratara.toy-linear-type-system/log.txt

Would be great to see if this is expected -- I think we've previously seen some issues with combine, so maybe just an old version.

cc @matthewjasper @nikomatsakis

**Comment by dillona** [comment]
searched nightlies: from nightly-2020-10-23 to nightly-2020-12-12
regressed nightly: nightly-2020-10-28
searched commits: from https://github.com/rust-lang/rust/commit/fd542592f08ca0d1f7255600115c2eafdf6b5da7 to https://github.com/rust-lang/rust/commit/07e968b640e8ff76fa8be4b48b70ab80ea577800
regressed commit: https://github.com/rust-lang/rust/commit/a4d30a7b490065f0aa56f58e508a11546445aea9

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.0</summary>


Host triple: aarch64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc
```
</details>

**Comment by Mark-Simulacrum** [comment]
cc @tmiasko -- any idea how #77876 could cause that? It seems quite unexpected to me but maybe I'm missing something

**Comment by tmiasko** [comment]
Underneath the recursion limit error lies a success story. The combine crate generates a lot of dead code and a new implementation is much better at removing it. The most significant aspect is removal of dead dyn casts, since without them there are fewer codegen items.

The crate has a configured recursion limit 67, which is exactly what is necessary. Since the codegen item collector uses memoization, removal of dyn cast might increase required recursion depth, which after changes it is at 71.

**Comment by Mark-Simulacrum** [comment]
Hm, and 67 is lower than the default? I am a bit worried at us exposing such low level details, but it sounds like this should be won't fix.

**Comment by apiraino** [comment]
Discussed on [Zulip](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/I-prioritize.20.2379909.20regression.3A.20reached.20recursion.20limit.20whi.E2.80.A6) and removing `I-prioritize`

**Comment by Mark-Simulacrum** [comment]
I am inclined to agree that this is not readily fixable. I am not sure whether we made the right call exposing such internal implementation details to end users - it feels like recursion limits are always going to be error prone for people to configure. However, the limit of 67 configured by this crate is below the minimum Rust by default sets (128 currently) so I am not inclined to be too worried.

cc @hirartara as the author of this regressed crate

**Comment by wesleywiser** [comment]
@Mark-Simulacrum I think you meant to cc @hiratara

**Comment by hiratara** [comment]
Hello,

I made that crate before only to practice Rust, and it has almost no content. Therefore, we don't need to worry at all if we can't build this crate.

Moreover, as far as I remember, the default value of `recursion_limit` was `64` when I created this crate. Now, I can build the crate if I delete the `recursion_limit` annotation.

**Comment by Mark-Simulacrum** [comment]
Closing as won't fix.
