### ISSUE TITLE
regression 1.49: unexpected unsized tail ICE

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#79902]
https://crater-reports.s3.amazonaws.com/beta-1.49-1/beta-2020-11-26/gh/folex.libp2p-multilang/log.txt

@rustbot modify labels: +regression-from-stable-to-beta I-ICE

**Comment by dillona** [comment]
searched nightlies: from nightly-2020-09-24 to nightly-2020-12-11
regressed nightly: nightly-2020-10-07
searched commits: from https://github.com/rust-lang/rust/commit/a1dfd2490a6cb456b92e469fa550dc217e20ad6d to https://github.com/rust-lang/rust/commit/98edd1fbf8a68977a2a7c1312eb1ebff80515a92
regressed commit: https://github.com/rust-lang/rust/commit/08e2d4616613716362b4b49980ff303f2b9ae654

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.0</summary>


Host triple: aarch64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc
```
</details>

**Comment by Mark-Simulacrum** [comment]
cc @matthewjasper -- seems like this one might be an actual bug  #73905

**Comment by matthewjasper** [comment]
Small case that I think shows this issue, it incorrectly fails to compile on beta/nightly.

```rust
trait A {
    type B;
}
trait M {}

struct G<T, U>(*const T, *const U);

impl<T, U> Clone for G<T, U> {
    fn clone(&self) -> Self {
        G { ..*self }
    }
}

impl<T, U> Copy for G<T, U::B>
where 
T: A<B = U>,
U: A
{}

impl A for () {
    type B = ();
}

fn is_m<T: M>(_: T) {}

fn main() {
    let x = G(&(), &());
    drop(x);
    drop(x);
}
```

**Comment by fanninpm** [comment]
[Playground link of previous example](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=421165a84674e3449b10f19ee18d3931)

N.B. I haven't gotten it to ICE, so I can't add it to the [glacier.](https://github.com/rust-lang/glacier)
