### ISSUE TITLE
'attempt to use non-constant in a constant' should point to the constant

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#79919]
([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=3ae11bd57f4d5bd285c4ded6d860d7cd))

```rust
extern crate reqwest; // 0.10.9

fn main() {
    let s = String::from("http://example.com");
    const response = reqwest::get(&s);
}
```
```
error[E0435]: attempt to use a non-constant value in a constant
 --> src/main.rs:5:36
  |
5 |     const response = reqwest::get(&s);
  |                                    ^ non-constant value
```
> I had `const response = self.request(...)` when I should have had `let response = self.request(...)` ... too much Javascript.
> I don't think I equated "a constant" with const foo = ... in my head, because I'm used to doing const foo = bar(...) in Javascript all the time

It would be nice for the error to point to `response` as the constant:
```
5 |     const response = reqwest::get(&s);
  |           ^^^^^^^^ constant        ^ non-constant value
```

**Comment by sasurau4** [comment]
I'll try it
@rustbot claim

**Comment by estebank** [comment]
My position,[from my comment in the PR](https://github.com/rust-lang/rust/pull/80012#issuecomment-748297783):

> The code changes themselves look reasonable. The ui change I'm ambivalent about. I see in the original report why this might be a problem for people coming from JS, but I don't know that _this_ change will be a solution. I can see other possibilities, like detecting that the `const` is in an item body (in other words, inside an `fn`) and _then_ potentially suggest `let` instead of `const`. For other cases (like the one mentioned in [the help for E0435](https://doc.rust-lang.org/error-index.html#E0435), we could emit a label pointing at the _definition of the non-`const` binding_ and suggesting turning _that_ into a `const` (if the value _can_ be `const`). If none of these cases fit, I think that the current output is reasonable enough, but could be expanded by saying "this binding can't be `const`, consider using a literal of the appropriate type" or something along those lines.
