### ISSUE TITLE
rustdoc search results heading illegible colour scheme

### ISSUE THREAD

**Issue by ijackson** [rust-lang/rust#79961]
The rustdoc search results page has three tabs of results: "In Names", "In Parameters", and "In Return Types".

In my browser with the default theme, the selected tab heading is drawn in black on black.

![screenshot](https://user-images.githubusercontent.com/2090772/101983576-ea9d1200-3c73-11eb-945f-726f3586e21e.png)

**Comment by camelid** [comment]
Yes, I've been having this too. You beat me to reporting this bug and #79960; thank you for making good reports!

**Comment by camelid** [comment]
I did some bisection and it seems the most likely cause is #79896.

**Comment by camelid** [comment]
Ah, I think I know what the issue is.

**Comment by camelid** [comment]
Labeled as P-medium since I made the fix and it's in the bors queue.
