### ISSUE TITLE
rustdoc help popup appears in every new tab when no web local storage

### ISSUE THREAD

**Issue by ijackson** [rust-lang/rust#79960]
In current Rust nightly, the std docs search function does a very annoying thing for me: every time I open a new tab onto the rust std docs, I get once again the popup with the keybindings which I then have to dismiss.

I conjecture that this is because I am looking at locally built docs via a `file://` URL.  Presumably the same thing would occur for a user who has sensibly disabled cookies in their web browser, resulting in the same horrible "stupid popup" user experience.

Given that without web local storage it is not possible to make a thing that is shown to each user once, it would be better not to show this popup at all when local storage is not available.

I'm not sure if it is possible to determine easily whether local storage is available.  I think there may be browsers which silently discard local storage writes rather than explicitly saying it's not available.  Until we know the answer to this question, I suggest that the new popup should be disabled :-(.

**Comment by camelid** [comment]
I've been having a different version of this happen on https://doc.rust-lang.org/nightly/std (and `/nightly-rustc`) too. Whenever I press <kbd>Enter</kbd> after typing in the search field, the Help popup momentarily appears. I don't think mine is a cookies issue; I think rustdoc is handling events wrong.

**Comment by camelid** [comment]
cc @rust-lang/rustdoc – this is a pretty severe usability bug, and we should fix it as soon as possible

**Comment by jyn514** [comment]
Might be related to https://github.com/rust-lang/rust/pull/78921 or https://github.com/rust-lang/rust/pull/78876 ?

**Comment by camelid** [comment]
I'll try to bisect.

**Comment by GuillaumeGomez** [comment]
I'll send a fix shortly.

**Comment by Qwaz** [comment]
Will the affected documentations on docs.rs be rebuilt?

**Comment by GuillaumeGomez** [comment]
Unfortunately no. It'll require to rebuild the impacted crates.
