### ISSUE TITLE
Can't document compiler crates with --stage 0

### ISSUE THREAD

**Issue by Nadrieril** [rust-lang/rust#79980]
When I try to run `./x.py doc` with `compiler-docs = true` in config.toml, I get several errors. I started discussing this [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp/topic/Can't.20document.20compiler.20crate). I am trying this on latest `master` and a clean `build/` directory.

First I got errors related to `-Znormalize-docs`. https://github.com/rust-lang/rust/pull/79954 fixed those.
Then I got a `'Unable to resolve external crate proc_macro2'` panic. https://github.com/rust-lang/rust/pull/79984 fixed that.

Finally I got this (even after clearing `build/`):
```
error[E0460]: found possibly newer version of crate `std` which `synstructure` depends on
 --> compiler/rustc_macros/src/lib.rs:5:5
  |
5 | use synstructure::decl_derive;
  |     ^^^^^^^^^^^^
  |
  = note: perhaps that crate needs to be recompiled?
  = note: the following crate versions were found:
          crate `std`: /home/nadrieril/wip/forks/rust/build/x86_64-unknown-linux-gnu/stage0-sysroot/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd
-2624c88e637295f4.rlib
          crate `std`: /home/nadrieril/wip/forks/rust/build/x86_64-unknown-linux-gnu/stage0-sysroot/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd
-2624c88e637295f4.so
          crate `synstructure`: /home/nadrieril/wip/forks/rust/build/x86_64-unknown-linux-gnu/stage0-rustc/release/deps/libsynstructure-3b73f5ee64fee340.rmeta

error: aborting due to previous error

error: could not document `rustc_macros`
```
And at that point I thought I'd open an issue because I have no idea what's happening.
EDIT: that error is the same as was found in https://github.com/rust-lang/rust/issues/74976, which seemed to have vanished spontaneously(?).

EDIT: here's my `config.toml` without the comments:
```toml
changelog-seen = 2
[llvm]
download-ci-llvm = true
assertions = true
[build]
compiler-docs = true
[rust]
debug-logging = true
debuginfo-level-rustc = 1
incremental = true
deny-warnings = false
```
EDIT: tried with `incremental = false` and got the same error

**Comment by jyn514** [comment]
@Mark-Simulacrum and I think this is the same root cause as https://github.com/rust-lang/rust/issues/74976#issuecomment-667265945: `--target` is getting passed to `rustdoc` but not to rustc, so they use different sysroots. I don't know how to fix this :(

**Comment by camelid** [comment]
Noting that it seems #79540 should fix this! See the [discussion on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/122651-general/topic/Generating.20compiler.20docs/near/221080367).

**Comment by jyn514** [comment]
@camelid well, it will still be broken if you don't have `download-stage1` turned on. So I think that part might be worth tracking.

**Comment by JakobDegen** [comment]
Has anything changed since this was last looked at to make this easier to fix? I'm running into this issue
