### ISSUE TITLE
`async` and other Rust 2018+ keywords not recognized as so in Rustdoc highlighting

### ISSUE THREAD

**Issue by ThePuzzlemaker** [rust-lang/rust#80004]
I tried this code:

```rust
/// ```rust ignore
/// fn foo(bar: &dyn Baz);
/// async fn quux() {
///     qaz.frobnify().await;
/// }
/// fn bar() {
///     let mut a = 0;
///     abstract blah; /// is a reserved keyword
/// }
/// ```
fn foo() {}
```

I expected to see this happen: `async` and other Rust 2018+ keywords are highlighted as my project is set to `edition = "2018"` in its `Cargo.toml`

Instead, this happened: They were not highlighted, but regular keywords (including reserved ones) were.
![image](https://user-images.githubusercontent.com/12666617/102008415-d00b7d00-3cf5-11eb-8981-d1b219c03292.png)

I believe that the reason why this is happening is this snippet in librustdoc: https://github.com/rust-lang/rust/blob/eb4fc71dc9024f15a0c9cc44bcc10c861e9d585e/src/librustdoc/html/highlight.rs#L292-L305

In this case, `Ident::from_str` will only create a dummy span (which isn't set to 2018 edition), so `is_reserved` does not include 2018+ keywords.

I would be willing to try to work on a PR to fix this issue if it is deemed worthy.

### Meta
Tested 

`rustc --version --verbose`:
stable:
```
rustc 1.48.0 (7eac88abb 2020-11-16)
binary: rustc
commit-hash: 7eac88abb2e57e752f3302f02be5f3ce3d7adfb4
commit-date: 2020-11-16
host: x86_64-unknown-linux-gnu
release: 1.48.0
LLVM version: 11.0
```
nightly:
```
rustc 1.50.0-nightly (7efc097c4 2020-12-12)
binary: rustc
commit-hash: 7efc097c4fe6e97f54a44cee91c56189e9ddb41c
commit-date: 2020-12-12
host: x86_64-unknown-linux-gnu
release: 1.50.0-nightly
```

Backtrace is not applicable.

**Comment by ThePuzzlemaker** [comment]
@rustbot label +T-rustdoc +A-rustdoc-ui +A-async-await
Hope these labels are accurate and helpful.

**Comment by tmandry** [comment]
@ThePuzzlemaker I think you have the right idea, though someone from the Rustdoc team might also be able to help with the details (cc @jyn514).

A PR would be welcome! Feel free to claim the issue with `@rustbot claim`. If you have questions, I'm also available to help here or on Zulip or DIscord, but my availability may be spotty over the next week.

**Comment by jyn514** [comment]
Yup, that looks right, good catch! The only tricky thing will be passing in a span in to `Classifier::new`, but I think all the callsites have access to at least a `Session`, and you can get an [`edition`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_session/session/struct.Session.html#method.edition) from there.

**Comment by ThePuzzlemaker** [comment]
@rustbot release-assignment
I'm going to release assignment as I'm still not quite sure how this could be achieved even after looking through a bit of code.

**Comment by jyn514** [comment]
@ThePuzzlemaker where did you get stuck? I might be able to help.

**Comment by ThePuzzlemaker** [comment]
@jyn514 I couldn't find a way to get access to a `Session` or how I even get a `Span` from the lexer. I guess I'll reclaim though.
@rustbot claim

**Comment by jyn514** [comment]
@ThePuzzlemaker you need to follow the call chain up until you get to somewhere that has a Session. If nothing else, run_renderer has one, but I bet you can get it a lot more easily if you find a function with a context of some kind; then just pass the session as an argument until it gets to where it needs to be. (Alternatively, you could just pass the edition instead.)

**Comment by ThePuzzlemaker** [comment]
I guess if I just add it to the `Session::new` function then I can just follow the errors up.

**Comment by jyn514** [comment]
Wait, I'm confused - `Session::new` isn't part of rustdoc, and the code constructing a session will not be in rustdoc code. I recommend using rust-analyzer and go-to-definition to find all the callers of a function

**Comment by ThePuzzlemaker** [comment]
I mean `Classifier::new` or whatever

**Comment by ThePuzzlemaker** [comment]
It looks like you can change the edition of a code block so I'll just do something like this:
- Highlight 2018 keywords if edition is explicitly set to 2018, don't if it's explicitly set to not 2018
- Highlight 2018 keywords if edition is set to 2018 for a crate and it's not explicitly set in the code block

**Comment by ThePuzzlemaker** [comment]
Hm, looks like I'm stuck again. I was able to pass an `Edition` to the `Classifier` but I don't know how to check `Ident.is_reserved` with an arbitrary edition (as to change the edition you'd have to make a `Span`, but I don't know how to get one).

**Comment by ThePuzzlemaker** [comment]
I guess I could make a function `Ident.is_reserved_for_edition` and then have `Ident.is_reserved` just call that with the `edition` of the span in the ident

**Comment by ThePuzzlemaker** [comment]
:) my changes worked, now to test and make sure they didn't bork anything else
`edition = "2015"`:
![image](https://user-images.githubusercontent.com/12666617/102707730-1ff0c380-4263-11eb-81f7-53f4555a2c10.png)
`edition = "2018"`:
![image](https://user-images.githubusercontent.com/12666617/102707744-35fe8400-4263-11eb-9b61-8d3ba8507769.png)
