### ISSUE TITLE
Rename LangString::all_false() to default()

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#80015]
`LangString::all_false` is not actually all_false - `rust` will return `true`. It would be nice to rename it to `default()` at some point (and maybe add `impl Default for LangString` while we're at it).

cc @poliorcetics

_Originally posted by @jyn514 in https://github.com/rust-lang/rust/issues/80013#issuecomment-744045253_

**Comment by poliorcetics** [comment]
@rustbot claim

I'll either get to it before next week is over or when #79454 is merged, whichever comes first
