### ISSUE TITLE
compiletest: Not all `diff` installations have `--color`

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#80037]
There is some rustdoc-related code in compiletest that uses the `diff` command-line tool; however, it passes the `--color` flag to `diff`, which `diff` does not accept on my system (macOS). We should probably use `git diff --no-index` instead of `diff` since it will have colors and will automatically use a pager. We may also want to pass the `--minimal` flag to `diff`/`git diff`; the manual page says:

> **--minimal**
> Spend extra time to make sure the smallest possible diff is produced.

*See also https://github.com/rust-lang/rust/pull/79991#discussion_r542065935.*

cc @jyn514

**Comment by jyn514** [comment]
@camelid was this fixed by https://github.com/rust-lang/rust/pull/82469 ?

**Comment by notriddle** [comment]
```
rust/src/tools/compiletest$ rg -- '--color'
src/main.rs
191:        Some(x) => panic!("argument for --color must be auto, always, or never, but found `{}`", x),
```

Yeah, it looks like it's fixed.
