### ISSUE TITLE
Binary formatter outputs wrong number of characters for 0

### ISSUE THREAD

**Issue by AlexEne** [rust-lang/rust#80030]
I tried this code:

```rust
fn main() {
    let value_1: u64 = !0;
    let value_0: u64 = 0;
    
    println!("{:#064b}", value_1);
    println!("{:#064b}", value_0);
}
```

I expected to see this happen: Both outputs to have 64 characters in addition to the `0b`.

Instead, this happened: the 1 has 64 characters, but value_0 displays 62 characters.

So the output looks like this:
```
0b1111111111111111111111111111111111111111111111111111111111111111
0b00000000000000000000000000000000000000000000000000000000000000
```

### Meta
`rustc --version --verbose`:
```
rustc 1.48.0 (7eac88abb 2020-11-16)
```

Here's the rust playground link for this: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=ad163499a4e9c2ee28604245bcf18d01

**Comment by malaire** [comment]
Few additional examples:
```rust
fn main() {
    println!("{:#064b}", 0xFFFF_FFFF_FFFF_FFFFu64);
    println!("{:#064b}", 0x7FFF_FFFF_FFFF_FFFFu64);
    println!("{:#064b}", 0x3FFF_FFFF_FFFF_FFFFu64);
    println!("{:#064b}", 0x1FFF_FFFF_FFFF_FFFFu64);
    println!("{:#064b}", 0x0FFF_FFFF_FFFF_FFFFu64);
}
```
outputs
```
0b1111111111111111111111111111111111111111111111111111111111111111
0b111111111111111111111111111111111111111111111111111111111111111
0b11111111111111111111111111111111111111111111111111111111111111
0b01111111111111111111111111111111111111111111111111111111111111
0b00111111111111111111111111111111111111111111111111111111111111
```

**Comment by jonas-schievink** [comment]
The `0b` prefix is included in the count

**Comment by seritools** [comment]
This behavior is [specified/documented](https://doc.rust-lang.org/std/fmt/index.html#sign0):

> When used together with the # flag, a similar rule applies: padding zeros are inserted after the prefix but before the digits. The prefix is included in the total width.

You specify the *minimum* length of the resulting string. `0b0` is shorter than 64 characters, so it gets padded to that with zeros.

`0b1...` needs 64 chars for the bits alone, and then two additional ones for the `0b`, so no padding occurs since the string already is longer than the specified minimum.

**Comment by AlexEne** [comment]
Yes, it does seem documented, I've followed the examples presented here where it's not as documented, and counting the characters is kind of hard :D: https://doc.rust-lang.org/std/fmt/trait.Binary.html#examples

**Comment by AlexEne** [comment]
Closing this as it's not a bug.
