### ISSUE TITLE
Optimization for bool's PartialOrd impl

### ISSUE THREAD

**Issue by ChayimFriedman2** [rust-lang/rust#80034]
#66780 suggested an optimization for `impl Ord for bool`, and it was implemented in #66881.

However, for some reason, `impl PartialOrd for bool` was not optimized the same way:
https://github.com/rust-lang/rust/blob/1f7762b4fcf47d36bf0718d5265a5c6ca7f33687/library/core/src/cmp.rs#L1286-L1300
https://github.com/rust-lang/rust/blob/1f7762b4fcf47d36bf0718d5265a5c6ca7f33687/library/core/src/cmp.rs#L1236-L1241

It can be implemented in terms of `Ord`:
```rust
    impl PartialOrd for bool {
        #[inline]
        fn partial_cmp(&self, other: &bool) -> Option<Ordering> {
            Some(self.cmp(other))
        }
    }
```
Is this deliberate or just something that no-one noticed?

**Comment by camelid** [comment]
By the way, you don't need to open an issue if you're about to open a PR. Just include what you would put in the issue in the PR!
