### ISSUE TITLE
check_attr doesn't check every HIR node type that can carry attributes.

### ISSUE THREAD

**Issue by eddyb** [rust-lang/rust#80048]
The `check_attr` visitor here is missing several methods: https://github.com/rust-lang/rust/blob/e261649593cf9c2707f7b30a61c46c4469c67ebb/compiler/rustc_passes/src/check_attr.rs#L866-L936

A quick search (for `attrs:`) in the HIR definition finds these additional types that can contain attributes (they're also missing from the `hir::Target` `enum`, which should probably be renamed to `AttrTarget` but that's besides the point):
<details>
<summary>(click to see definition code snippets)

(summary: `GenericParam`, `MacroDef`, `Arm`, `Param`, `StructField`)
</summary>

* `GenericParam` https://github.com/rust-lang/rust/blob/e261649593cf9c2707f7b30a61c46c4469c67ebb/compiler/rustc_hir/src/hir.rs#L425-L428
* `MacroDef` (is this handled elsewhere?) https://github.com/rust-lang/rust/blob/e261649593cf9c2707f7b30a61c46c4469c67ebb/compiler/rustc_hir/src/hir.rs#L722-L725
* `Arm` https://github.com/rust-lang/rust/blob/e261649593cf9c2707f7b30a61c46c4469c67ebb/compiler/rustc_hir/src/hir.rs#L1147-L1151
* `Param` https://github.com/rust-lang/rust/blob/e261649593cf9c2707f7b30a61c46c4469c67ebb/compiler/rustc_hir/src/hir.rs#L2183-L2184
* `StructField` https://github.com/rust-lang/rust/blob/e261649593cf9c2707f7b30a61c46c4469c67ebb/compiler/rustc_hir/src/hir.rs#L2390-L2397
</details>

This isn't necessary a bug for some of them, as there is special validation elsewhere, e.g.: https://github.com/rust-lang/rust/blob/e261649593cf9c2707f7b30a61c46c4469c67ebb/compiler/rustc_ast_passes/src/ast_validation.rs#L377-L378

But it's not as uniform and future-proof as it *could* be. It might even be worth having a contextual attribute `Target`, and handling all attributes on `visit_attr`, or a hybrid solution that ICEs when `visit_attr` comes across an attribute not already handled.

And I did end up finding *at least* one bug, this *compiles without any warnings* ([try on playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=241a98fd10725f30b6e4ba29088bb866)):
```rust
fn main() {
    match 5 {
        #[inline] _ => {}
    }
}
```

cc @varkor @davidtwco @petrochenkov

**Comment by eddyb** [comment]
After #80641 and #80920, what's left? cc @oli-obk

**Comment by oli-obk** [comment]
Looked over those PRs, yea, this is fixed now.
