### ISSUE TITLE
suboptimal diagnostics for fn-item keywords in wrong order (extern unsafe, unsafe pub)

### ISSUE THREAD

**Issue by comex** [rust-lang/rust#80070]
Before `fn`, the keywords `pub`, `unsafe`, and `extern` may appear but only in that order.  That's fine, but if you get the order wrong, the diagnostics aren't as helpful as they could be:

```
error: expected `fn`, found keyword `unsafe`
 --> src/lib.rs:1:8
  |
1 | extern unsafe fn foo() {}
  |        ^^^^^^ expected `fn`
```
```
error: expected item, found keyword `unsafe`
 --> src/lib.rs:1:1
  |
1 | unsafe pub fn foo() {}
  | ^^^^^^ expected item
```

**Comment by camelid** [comment]
Ideally we would be able to recover and suggest switching the order (like with lifetime and type parameters).

**Comment by Rageking8** [comment]
Already fixed

**Comment by Dylan-DPC** [comment]
Closing this as fixed and there is a [testcase](https://github.com/rust-lang/rust/blob/master/src/test/ui/parser/issues/issue-87217-keyword-order/wrong-unsafe.rs) for it
