### ISSUE TITLE
Manual doesn't document the meaning of various single quote lifetime

### ISSUE THREAD

**Issue by ozten** [rust-lang/rust#8007]
[NOTE: I misread `'` as a backtick ]
I've come across types with backticks aka `.

Examples (from memory, could be wrong):

    &`a
    `static

From reading [a presentation on memory](http://smallcultfollowing.com/babysteps/pubs/2013.07.17-NEU.pdf) I guess one use is to denote lifetype scope (???).

Since the compiler gives type errors that use backtick, it would be great to have a section on them.

**Comment by steveklabnik** [comment]
There's been zero discussion here, and we do have the aforementioned sentence. If we have additional specific improvements that can be made, I'm open to it, but I think this can be closed.
