### ISSUE TITLE
rustc infinite loop on unbounded type recursion

### ISSUE THREAD

**Issue by talchas** [rust-lang/rust#80098]
On rustc 1.50.0-nightly (f76ecd066 2020-12-15), 1.49.0-beta.4 (877c7cbe1 2020-12-10), 1.48.0 or 1.47.0 

```rust
fn main() {
    f(Vec::<usize>::new().iter());
}

fn f<'a, T: Clone + Iterator<Item = &'a usize>>(s: T) {
    f(s.clone().enumerate().map(|(_, x)| x));
}
```

Appears to somehow dodge the type-length limits and compiler recursion limits, as it has been compiling for several minutes without hitting either (or changing memory usage). Oddly, on the old 1.48.0-nightly (285fc7d70 2020-09-16) I had installed, this gave a proper type-length limit error message.

**Comment by camelid** [comment]
This is actually a stable-to-stable regression.

**Comment by camelid** [comment]
Based on testing with Godbolt, the hang was introduced between 1.46 and 1.47.

**Comment by apiraino** [comment]
Assigning `P-medium` as discussed as part of the [Prioritization Working Group procedure](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/I-prioritize.20.2380098.20rustc.20infinite.20loop.20on.20unbounded.20type.20r.E2.80.A6) and removing `I-prioritize`.

**Comment by smmalis37** [comment]
As of the latest nightly this no longer hangs, and now errors.

**Comment by camelid** [comment]
I've also confirmed that a project of mine that was hanging is now errorring 🎉

**Comment by camelid** [comment]
(Would be nice to bisect to the PR that fixed it, but might be tricky to do because it's a hang.)
