### ISSUE TITLE
Feature request: Blanket Impl's for a trait should be included in that trait's documentation

### ISSUE THREAD

**Issue by rbalicki2** [rust-lang/rust#80102]
# Feature request:

If a trait (like `ToString`) is implemented for all types that implement another trait (like `fmt::Display`), that blanket impl should show up in the `fmt::Display` documentation.

This came up for me, as I was wondering how a particular type's `to_string` method was implemented. I figured it had something to do with `fmt::Display`, but the docs for `fmt::Display` were not helpful in that case.

**Comment by jyn514** [comment]
For what it's worth, it is shown on the type, just not on the trait: https://doc.rust-lang.org/std/primitive.u16.html#impl-ToString.

**Comment by ThePuzzlemaker** [comment]
It does look like they are shown [on the trait](https://doc.rust-lang.org/std/string/trait.ToString.html#impl-ToString-4), just not in a separate blanket impls section

**Comment by rbalicki2** [comment]
Thanks! I don't know how I missed these. I appreciate the wonderful documentation, and apologize for wasting your time :)

**Comment by jyn514** [comment]
@ThePuzzlemaker those are shown on ToString, not on Display itself. @rbalicki2 I interpreted the issue as showing the impls on Display, is that what you meant?
