### ISSUE TITLE
rustdoc: Private function is rendered with a verbose visibility

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#80101]
If I run `cargo +nightly doc --document-private-items` on this code:

```rust
mod foo {
    struct S;
    impl S {
        fn new() -> S { S }
    }
}
```

then the output looks like this:

![image](https://user-images.githubusercontent.com/37223377/102423964-07f91580-3fbf-11eb-8269-642f71698347.png)

Note that the visibility is verbose – it says `pub(in foo)` when it should show nothing (and used to show nothing).

This bug only occurs when the function is private and `--document-private-items` is passed (of course, the docs are not generated without that flag).

**Comment by camelid** [comment]
searched nightlies: from nightly-2020-11-17 to nightly-2020-11-20
regressed nightly: nightly-2020-11-19
searched commits: from https://github.com/rust-lang/rust/commit/c919f490bbcd2b29b74016101f7ec71aaa24bdbb to https://github.com/rust-lang/rust/commit/8256379832b5ecb7f71e8c5e2018446482223c12
regressed commit: https://github.com/rust-lang/rust/commit/7d747db0d5dd8f08f2efb073e2e77a34553465a7

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.0</summary>


Host triple: x86_64-apple-darwin
Reproduce with:
```bash
cargo bisect-rustc --preserve --prompt --start=2020-11-17 --end=2020-11-20 -- doc --document-private-items 
```
</details>

-----

I'm not sure if the commit it thinks has the regression is correct though. `cargo-bisect-rustc` printed out this during bisection:

```
installing c4f836ad1aceb83507810d9499f56988fd24578d
installing 87776d7d5322422e5239e153e793b687f7f9c379
installing 7d747db0d5dd8f08f2efb073e2e77a34553465a7
testing...
```

and then after that it asked me again about c919f490bbcd2b29b74016101f7ec71aaa24bdbb, even though it asked me about it at the start of bisection.

**Comment by jyn514** [comment]
> the visibility is verbose – it says pub(in foo) when it should show nothing

This is probably the same cause as https://github.com/rust-lang/rust/issues/79139, although the fix may be slightly different.

> cargo bisect-rustc --preserve --prompt --start=2020-11-17 --end=2020-11-20 -- doc --document-private-items 

The 'prompt' there makes me think you might have hit the wrong 'good/bad' option at some point.

**Comment by camelid** [comment]
I did the bisection twice though and both times it had the same result. I wish `cargo-bisect-rustc` could do this automatically somehow.

**Comment by jyn514** [comment]
@camelid you could write a script that does an xpath query on the generated documentation, maybe.

**Comment by camelid** [comment]
At that point it's faster to do it manually.

**Comment by camelid** [comment]
@jyn514 Did the formatting change happen as part of #77820?

**Comment by jyn514** [comment]
@camelid I wouldn't expect it to but I don't know without bisecting.

**Comment by camelid** [comment]
I bisected a third time, and again I got the same result. I think it might be a bug in cargo-bisect-rustc.

**Comment by jyn514** [comment]
Well I can at least confirm that the bug is not present in beta, so this is a nightly regression.

**Comment by jyn514** [comment]
These are the PRs merged between the 17th and 18th (the 18th also has this bug): https://github.com/rust-lang/rust/pulls?q=is%3Amerged+is%3Apr+label%3AT-rustdoc+merged%3A2020-11-17..2020-11-18. `fn new() {}` doesn't have the weird formatting so I suspect either https://github.com/rust-lang/rust/pull/79125 or https://github.com/rust-lang/rust/pull/77820.

**Comment by camelid** [comment]
Based on manually installing toolchains, I've confirmed that the issue was introduced in nightly-2020-11-19, so that's c919f490b...825637983.

**Comment by camelid** [comment]
Based on yet more manual testing by installing CI toolchains, I've confirmed that the issue was introduced in c4f836ad1aceb83507810d9499f56988fd24578d (#77820). Phew!

**Comment by camelid** [comment]
I figured out that the reason it has weird formatting is that rustdoc will render functions like

```rust
fn foo(
    x: ...,
    y: ...
)
```

if the one-line version would be over 80 characters.

This is the code that does that conditional formatting:

https://github.com/rust-lang/rust/blob/969b42d8c0e44c6b895ab4582b5ae0a0ce319fdf/src/librustdoc/html/format.rs#L1064

**Comment by camelid** [comment]
Closing as duplicate of #79139.
