### ISSUE TITLE
Test "mem::uninit_write_slice_cloned_no_drop" leaks memory

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#80116]
The test `mem::uninit_write_slice_cloned_no_drop` added in https://github.com/rust-lang/rust/pull/79607 leaks memory, which makes a Miri run of the test suite fail:

```
running 1 test
test mem::uninit_write_slice_cloned_no_drop ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 1176 filtered out

The following memory was leaked: alloc1884656 (Rust heap, size: 16, align: 8) {
    01 00 00 00 00 00 00 00 01 00 00 00 00 00 00 00 │ ................
}
```

Running Miri on the test suite is helpful to find bugs, so we should avoid deliberate leaks to still be able to detect accidental ones. Can the test be changed to use some other means of ensuring that `drop` is not called, e.g. with a `Bomb` type?
```rust
struct Bomb;

impl Drop for Bomb {
  fn drop(&mut self) { panic!(); }
}
```

Cc @DrMeepster

**Comment by DrMeepster** [comment]
@rustbot claim

I made the test I should fix it

**Comment by RalfJung** [comment]
@DrMeepster thanks. :-) Let me know if you need any help.
