### ISSUE TITLE
Unsoundness with subtyping of function types

### ISSUE THREAD

**Issue by jhjourdan** [rust-lang/rust#80110]
Consider this piece of Rust code:

```rust
fn f<'a, 'b>(_ : &'b &'a (), r : &'a i32) -> &'b i32 {
    r
}

const R : &'static () = &();

fn evil<'a, 'b>(x : &'a i32) -> &'b i32 {
    let f2 : fn(&'b &'static (), &'a i32) -> &'b i32 = f;

    // variant :
    // let f2 : for<'fa, 'fb> fn(&'fb &'static (), &'fa i32) -> &'fb i32 = f;

    f2(&R, x)
}

fn main() {}

```

The function evil let's us change the lifetime of a borrow /without/ any constraint of the old and new lifetimes. This is clearly unsound. I tried with the current nightly version of Rust, which compiles this piece of code without error (only warnings).

The core idea of the bug is that the function `f` coerces the borrow r using the implicit constraint `'a : `'b` coming from the type of the other parameter. When coercing the type of the function `f` to `f2`, this implicit constraint is lost, so that we can call it with two unrelated lifetimes.

I found this bug while trying to properly formalize subtyping for function types in the context of the RustBelt project.

Cc @RalfJung

**Comment by RalfJung** [comment]
Is this an instance of https://github.com/rust-lang/rust/issues/25860, or a different bug?

**Comment by jhjourdan** [comment]
No, you are right. That's a duplicate of #25860. I just did not remembered of this issue. Closing that one, sorry for the noise.
