### ISSUE TITLE
Compiler is not able to infer the type of a HashMap, when all types should be known

### ISSUE THREAD

**Issue by DzenanJupic** [rust-lang/rust#80137]
I'm currently porting pytube to Rust and encountered a situation where the compiler requires me to specify the type of a `HashMap`s Value, even though all types are known.

## I tried this code:
[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&code=use%20std%3A%3Acollections%3A%3AHashMap%3B%0A%0Apub(crate)%20fn%20parse_qs(qs%3A%20%26str)%20-%3E%20Result%3CHashMap%3CString%2C%20Vec%3CString%3E%3E%2C%20()%3E%20%7B%0A%20%20%20%20let%20mut%20parsed_results%20%3D%20HashMap%3A%3Anew()%3B%0A%20%20%20%20%2F%2Flet%20mut%20parsed_results%20%3D%20HashMap%3A%3A%3C_%2C%20Vec%3C_%3E%3E%3A%3Anew()%3B%0A%20%20%20%20let%20pairs%3A%20Vec%3C(String%2C%20String)%3E%20%3D%20parse_qsl(qs)%3F%3B%0A%20%20%20%20%0A%20%20%20%20for%20(name%2C%20value)%20in%20pairs%20%7B%0A%20%20%20%20%20%20%20%20match%20parsed_results.get_mut(name.as_str())%20%7B%0A%20%20%20%20%20%20%20%20%20%20%20%20Some(result)%20%3D%3E%20result.push(value)%2C%0A%20%20%20%20%20%20%20%20%20%20%20%20None%20%3D%3E%20%7B%20parsed_results.insert(name%2C%20vec!%5Bvalue%5D)%3B%20%7D%0A%20%20%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%20%20%0A%20%20%20%20Ok(parsed_results)%0A%7D%0A%0Apub(crate)%20fn%20parse_qsl(qs%3A%20%26str)%20-%3E%20Result%3CVec%3C(String%2C%20String)%3E%2C%20()%3E%20%7B%0A%20%20%20%20unimplemented!()%3B%0A%7D)

```rust
use std::collections::HashMap;

fn parse_qs(qs: &str) -> Result<HashMap<String, Vec<String>>, ()> {
    let mut parsed_results = HashMap::new();
    let pairs: Vec<(String, String)> = parse_qsl(qs)?;
    
    for (name, value) in pairs {
        match parsed_results.get_mut(name.as_str()) {
            Some(result) => result.push(value),
            None => { parsed_results.insert(name, vec![value]); }
        }
    }
    
    Ok(parsed_results)
}

fn parse_qsl(qs: &str) -> Result<Vec<(String, String)>, ()> {
    unimplemented!();
}
```

## I expected to see this happen:
Since all types are known, and `parsed_result` is even being returned, I think it's safe to assume that the compiler can correctly infer the types. (My IDE can)

## Instead, this happened: 
The compiler requires me to use turbofish syntax:
```rust
let mut parsed_results = HashMap::<_, Vec<_>>::new();
```
otherwise it tells me:
```
error[E0282]: type annotations needed for `HashMap<K, V>`
 --> src/lib.rs:9:30
  |
4 |     let mut parsed_results = HashMap::new();
  |         ------------------ consider giving `parsed_results` the explicit type `HashMap<K, V>`, where the type parameter `V` is specified
...
9 |         match parsed_results.get_mut(name.as_str()) {
  |                              ^^^^^^^ cannot infer type for type parameter `V`
  |
  = note: type must be known at this point
```

### Meta
- stable 1.48.0
- beta 1.49.0-beta.2
- nightly 1.50.0-nightly

**Comment by jonas-schievink** [comment]
This is working as expected. When invoking a method defined in an inherent impl, all relevant types must be known at that point in the program.
