### ISSUE TITLE
unclear diagnostic with invalid suggestion for lifetime error involving an opaque type

### ISSUE THREAD

**Issue by ben0x539** [rust-lang/rust#80150]
This code is invalid because it returns a reference to a local:
```rust
fn foo<T: 'static>() -> Option<impl Iterator<Item = T>> {
    let mut n = None.into_iter();
    let i: &mut dyn Iterator<Item=T> = &mut n;
    Some(i)
}
```

It produces this diagnostic:

```
error[E0597]: `n` does not live long enough
 --> src/lib.rs:3:40
  |
1 | fn foo<T: 'static>() -> Option<impl Iterator<Item=T>> {
  |                         ----------------------------- opaque type requires that `n` is borrowed for `'static`
2 |     let mut n = None.into_iter();
3 |     let i: &mut dyn Iterator<Item=T> = &mut n;
  |                                        ^^^^^^ borrowed value does not live long enough
4 |     Some(i)
5 | }
  | - `n` dropped here while still borrowed
  |
help: you can add a bound to the opaque type to make it last less than `'static` and match `'static`
  |
1 | fn foo<T: 'static>() -> Option<impl Iterator<Item=T>> + 'static {
  |                                                       ^^^^^^^^^
```

1) I don't understand what "help: you can add a bound to the opaque type to make it last less than `'static` and match `'static`" means
2) The suggestion(?) of `Option<impl Iterator<Item=T>> + 'static` isn't valid

It's probably trying to say `Option<impl Iterator<Item=T> + 'static>`, if we try that, we get a more straightforward error message.

I'm not sure if this is just #69982, but that one seems to want a closure-specific other diagnostic rather than being generally confused like me.

(tried this on playground with stable 1.48 and nightly)

**Comment by camelid** [comment]
Assigning `P-medium` and removing `I-prioritize` as [discussed](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2380150.20unclear.20diagnostic.20with.20invalid.20suggestion.20for.20lifet.E2.80.A6) in the prioritization working group.

**Comment by estebank** [comment]
Current output:

```
error[[E0597]](https://doc.rust-lang.org/stable/error_codes/E0597.html): `n` does not live long enough
 --> src/lib.rs:3:40
  |
2 |     let mut n = None.into_iter();
  |         ----- binding `n` declared here
3 |     let i: &mut dyn Iterator<Item=T> = &mut n;
  |                                        ^^^^^^ borrowed value does not live long enough
4 |     Some(i)
  |     ------- opaque type requires that `n` is borrowed for `'static`
5 | }
  | - `n` dropped here while still borrowed
```
