### ISSUE TITLE
VecDeque from Vec with ZST elements breaks internal invariants 

### ISSUE THREAD

**Issue by tmiasko** [rust-lang/rust#80167]
```rust
fn main() {
    let n = 1 << (core::mem::size_of::<usize>() * 8 - 1);

    let mut v = Vec::<()>::new();
    assert!(v.capacity() >= n);
    unsafe { v.set_len(n) };

    let d = std::collections::VecDeque::from(v);
    assert_eq!(d.len(), n, "unexpected len");
}
```

I expected VecDeque constructed from Vec to either work correctly or construction to panic if it is not possible. Instead:

```console
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `2147483648`: unexpected len', a.rs:9:5
```

Introduced by #80003.

**Comment by camelid** [comment]
cc #78532

**Comment by camelid** [comment]
Not sure how severe this is, but figured that it's worth prioritizing.

**Comment by camelid** [comment]
Assigning `P-high` and removing `I-prioritize` as [discussed](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/I-prioritize.20.2380167.20VecDeque.20from.20Vec.20with.20ZST.20elements.20bre.E2.80.A6) in the prioritization working group.

**Comment by cuviper** [comment]
#83244 should fix this -- written before I saw this issue and @Stupremee's claim, so I'm sorry if you were still working on it.
