### ISSUE TITLE
Ship standard library with embedded bitcode.

### ISSUE THREAD

**Issue by In-line** [rust-lang/rust#80195]
This would allow to do LTO with standard library, reducing sizes of simple CLI applications.

**Comment by ehuss** [comment]
Bitcode should be included in the precompiled binaries:

```
readelf -WS std-25c6acf8063a3802.std.7uelo83d-cgu.0.rcgu.o  | grep llvmbc
  [ 3] .llvmbc           PROGBITS        0000000000000000 000040 36b6cc 00   E  0   0 16
```

Can you explain why you think it isn't, or what problem you are running into?
