### ISSUE TITLE
`!Sized` return type error panics with 'no errors encountered even though `delay_span_bug` issued'

### ISSUE THREAD

**Issue by QuineDot** [rust-lang/rust#80207]
### Code

```Rust
use std::ops::BitOr;

pub trait IntWrapper {
    type InternalStorage;
}

impl<T> BitOr for dyn IntWrapper<InternalStorage = T>
where
    Self: Sized,
    T: BitOr + BitOr<Output = T>,
{
    type Output = Self;
    fn bitor(self, _other: Self) -> Self {
        todo!()
    }
}
```

### Meta
Via [the playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=9957462c94dc83db6ebe95aa9f408f62) on all of stable, beta, and nightly.

> note: rustc 1.48.0 (7eac88abb 2020-11-16) running on x86_64-unknown-linux-gnu
> note: compiler flags: -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2 --crate-type lib
> note: some of the compiler flags provided by cargo are hidden

### Error output

```
   Compiling playground v0.0.1 (/playground)
error: internal compiler error: `!Sized` return type
  --> src/lib.rs:13:37
   |
13 |     fn bitor(self, _other: Self) -> Self {
   |                                     ^^^^
   |
   = note: delayed at compiler/rustc_typeck/src/check/check.rs:154:18

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:961:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.
```

### Credit
[Discovered by rectang as reported on the user forum](https://users.rust-lang.org/t/bounds-when-implementing-a-trait-for-a-trait/52972).

**Comment by rectang** [comment]
A further [reduction](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=ae8ef2bff4260d2aee0a6118c129e455) clarifies that the bug has nothing to do with std::ops::BitOr.

```rust
pub trait Foo {
    fn do_stuff() -> Self;
}

pub trait Bar {
    type Output;
}

impl<T> Foo for dyn Bar<Output = T>
where
    Self: Sized,
{
    fn do_stuff() -> Self {
        todo!()
    }
}
```

**Comment by SNCPlay42** [comment]
This code compiled successfully in 1.44 and earlier. The delay_span_bug it's hitting was added in #70998 [(here)](https://github.com/rust-lang/rust/pull/70998/files#diff-b65997b61ccd8d8e08238c925d631207671aca506e93ce7c5cfa0bec134c0a8eR1376).

@rustbot label regression-from-stable-to-stable A-dst

**Comment by camelid** [comment]
Assigning `P-high` and removing `I-prioritize` as [discussed](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/I-prioritize.20.2380207.20.60!Sized.60.20return.20type.20error.20panics.20with.20.E2.80.A6) in the prioritization working group.

**Comment by osa1** [comment]
The `delay_span_bug` in this ICE is this one: https://github.com/rust-lang/rust/blob/742c972c4f92a8f213d05b82ba04797f251f125a/compiler/rustc_typeck/src/check/check.rs#L182-L195

It was added in e53625706106e0227656ddd2fa4d7df54ae2b90e.

I think the problem with this program is that we have `Self: Sized` but the self is actually `dyn <trait>` which is not `Sized`, right? So we don't expect to compile it, we should just reject it with a good error message?

CCing @estebank as he is the author of the commit above.

**Comment by estebank** [comment]
It would be nice if we could come up with _more_ repro cases that don't involve `Self`. It'd be easy to fix _only_ this one case but I'm struggling to see what other cases could trigger this.

**Comment by estebank** [comment]
As mentioned in the pr fixing this, the `delay_span_bug` was incorrect. It should have never been added.

**Comment by estebank** [comment]
Reopening for the backport.
