### ISSUE TITLE
Idea: Import `std::iter` in the prelude

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#80216]
Idea: Import `std::iter` in the prelude so that you don't have to add `use std::iter;` to the top of the file in order to use `iter::once`, `iter::empty`, etc.

`Iterator` is already in the prelude, so things like `vec![1, 2, 3].into_iter().chain(vec![4, 5, 6].into_iter())` "just work", but to do `iter::once(1).chain(vec![2, 3].into_iter())` requires adding an import. Iterators are a fairly core language feature and having to add an import in order to create a single-element iterator is annoying.

I'm not sure if this makes sense to do however. The name would shadow any crates named `iter`, though the `iter` crate on crates.io [is a namesquat](https://crates.io/crates/iter).

**Comment by jhpratt** [comment]
How would this interact if there were a local `mod iter`?

**Comment by camelid** [comment]
I’m not sure, but I _think_ local items take precedence over prelude imports.

**Comment by SimonSapin** [comment]
What’s wrong with calling `std::iter::once(1)`? That also doesn’t need an import.

**Comment by camelid** [comment]
It adds noise and is verbose in my opinion. In my experience, it's almost always used as part of a chain with a bunch of other things and looks weird with the `std::` prefix:

```rust
std::iter::once(self.do_something(xyz))
        .chain(vec![1, 2, 3].into_iter())
        .chain(std::iter::once(self.my_function()))
```

vs.


```rust
iter::once(self.do_something(xyz))
        .chain(vec![1, 2, 3].into_iter())
        .chain(iter::once(self.my_function()))
```

I also generally find `std::`-prefixed paths to be somewhat ugly. But `iter::once` is just my personal preference :)

**Comment by scottmcm** [comment]
I'm not seeing what makes `iter` special enough to be worth doing this.  I could easily also argue for `mem` for `mem::replace`, or `fs` for `fs::read_to_string`, or ...

On `.chain(iter::once(x))` specifically, note that it can also be written as `.chain(Some(x))` if one wants to save an import.  So if that's not happening already, then maybe the import isn't all that annoying in practice.  (And one day will be writable as `.chain([x])`, though that one produces a slightly-larger iterator.)

**Comment by camelid** [comment]
> I'm not seeing what makes `iter` special enough to be worth doing this. I could easily also argue for `mem` for `mem::replace`, or `fs` for `fs::read_to_string`, or ...

Yeah, adding those imports bothers me too ;)

Maybe the solution is for me to switch to rust-analyzer 😄. The annoying part for me is having to go to the top of the file and add the import in every file where I use `iter::once`. RLS has auto-imports, but they tend to be buggy – e.g., they'll be put between a `#[derive]` and the struct it's applied to.

**Comment by camelid** [comment]
> On `.chain(iter::once(x))` specifically, note that it can also be written as `.chain(Some(x))` if one wants to save an import. So if that's not happening already, then maybe the import isn't all that annoying in practice. (And one day will be writable as `.chain([x])`, though that one produces a slightly-larger iterator.)

That day has arrived! 🎉 

```rust
fn main() {
    let v: Vec<_> = std::iter::empty().chain([42]).collect();
    println!("{:?}", v); // prints [42]
}
```

I've changed my mind, and I agree that adding `std::iter` to the prelude wouldn't be so good. I'll close this issue then.
