### ISSUE TITLE
Tracking Issue for `std::io::read_to_string`

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#80218]
Feature gate: `#![feature(io_read_to_string)]`

This is a tracking issue for the `std::io::read_to_string` function.

The equivalent of `std::fs::read_to_string`, but generalized to all
`Read` impls.

As the documentation on `std::io::read_to_string` says, the advantage of
this function is that it means you don't have to create a variable first
and it provides more type safety since you can only get the buffer out
if there were no errors. If you use `Read::read_to_string`, you have to
remember to check whether the read succeeded because otherwise your
buffer will be empty.

It's friendlier to newcomers and better in most cases to use an explicit
return value instead of an out parameter.

### Public API

```rust
pub fn read_to_string<R: Read>(reader: R) -> Result<String>;
```

### Steps / History

- [x] Implementation: #80217
- [x] FCP
- [ ] Stabilization PR (#100337)

### Unresolved Questions

- [x] Function signature (#92863)

**Comment by DesmondWillowbrook** [comment]
Is this stabilized? Implementation PR looks like it has been merged in 1.51, but I'm getting an error from `cargo check` that this hasn't been stabilized.

rustc version: `rustc 1.52.1 (9bc8c42bb 2021-05-09)`

**Comment by DesmondWillowbrook** [comment]
What is the status on stabilizing this addition to the library?

**Comment by fee1-dead** [comment]
@rust-lang/libs

Can we start an FCP?

**Comment by m-ou-se** [comment]
Thinking a bit about the signature: Considering `Read` is already implemented for `&mut impl Read`, shouldn't this function just take an `R` instead of `&mut R`?

**Comment by camelid** [comment]
> Thinking a bit about the signature: Considering `Read` is already implemented for `&mut impl Read`, shouldn't this function just take an `R` instead of `&mut R`?

I modeled it after `Read::read_to_string`, which takes an `&mut self`, but that has to use `&mut self` because it's defined as part of the trait. I don't know enough about the idiom for `std` here, so if that works it seems fine to me.

**Comment by jkugelman** [comment]
I'm working on a related PR https://github.com/rust-lang/rust/pull/89582 to have `File::read_to_string` enlarge the string buffer before reading to accommodate the full file size. A nice side effect is that it will make `io::read_to_string` more performant when the reader is a file.

If it lands do you think there's anything in [this comment](https://doc.rust-lang.org/std/io/fn.read_to_string.html#performance) that should be updated?

> #### Performance
>
> The downside of this function's increased ease of use and type safety is that it gives you less control over performance. For example, you can't pre-allocate memory like you can using `String::with_capacity` and `Read::read_to_string`. Also, you can't re-use the buffer if an error occurs while reading.
>
> In many cases, this function's performance will be adequate and the ease of use and type safety tradeoffs will be worth it. However, there are cases where you need more control over performance, and in those cases you should definitely use `Read::read_to_string` directly.

**Comment by camelid** [comment]
> I'm working on a related PR #89582 to have `File::read_to_string` enlarge the string buffer before reading to accommodate the full file size. A nice side effect is that it will make `io::read_to_string` more performant when the reader is a file.

That's great; thanks for working on this!

> If it lands do you think there's anything in [this comment](https://doc.rust-lang.org/std/io/fn.read_to_string.html#performance) that should be updated?

Perhaps we could add another paragraph at the end like this:

> Note that in some special cases, such as when reading files, this function will pre-allocate memory based on the size of the input is reading. In those cases, the performance should be as good as if you had used `Read::read_to_string()` with a manually pre-allocated buffer.

**Comment by jkugelman** [comment]
It seems like this should be paired with a `std::io::read_to_end` method to match the other pairings in the standard library:

* [`Read::read_to_end`](https://doc.rust-lang.org/std/io/trait.Read.html#method.read_to_end) + [`Read::read_to_string`](https://doc.rust-lang.org/std/io/trait.Read.html#method.read_to_string)
* [`fs::read`](https://doc.rust-lang.org/std/fs/fn.read.html) + [`fs::read_to_string`](https://doc.rust-lang.org/std/fs/fn.read_to_string.html)

Would it be `read` or `read_to_end`? I'd say `read_to_end` to match the `Read` trait since the reader might not be at the beginning.

**Comment by camelid** [comment]
Now that the PR to remove the `&mut` from the signature is in the merge queue, should an FCP be proposed?

**Comment by camelid** [comment]
I will open a stabilization PR next week or so.

**Comment by camelid** [comment]
Actually, I think a libs team FCP needs to be completed first. @m-ou-se could you kick that off? (Or do I need to do something before that?)

**Comment by joshtriplett** [comment]
@rfcbot merge
