### ISSUE TITLE
Rust-LLDB can't pretty print &mut [T] and &mut Vec<T> both in OS X.

### ISSUE THREAD

**Issue by ZPTX4869** [rust-lang/rust#80214]
I want to see the slice value in the debug window of vscode. however, it only gave me an address of a referenced vector variable. It's very inconvenient to debug, how can I solve this problem. I also tried terminal use of rust-lldb, it didn't work too.
<img width="449" alt="iShot2020-12-20 02 35 36" src="https://user-images.githubusercontent.com/32222479/102704253-09268d00-42b4-11eb-8e6e-17256dbe8694.png">
![image](https://user-images.githubusercontent.com/32222479/102704266-47bc4780-42b4-11eb-99a9-7010056383db.png)
![image](https://user-images.githubusercontent.com/32222479/102704278-5efb3500-42b4-11eb-8f3a-e0989b80f4e1.png)

**Comment by ZPTX4869** [comment]
![image](https://user-images.githubusercontent.com/32222479/102704681-9b7d5f80-42b9-11eb-9940-2fa3dc832e2c.png)

**Comment by camelid** [comment]
In the future, please include the version of `rustc` etc. as text, not as screenshots.

**Comment by camelid** [comment]
> ![image](https://user-images.githubusercontent.com/32222479/102704681-9b7d5f80-42b9-11eb-9940-2fa3dc832e2c.png)

I'm not sure why you are including this image. Can you please explain?

**Comment by camelid** [comment]
`&[T]` (a slice) is just a pointer combined with a length. Quoting [the docs](https://doc.rust-lang.org/nightly/std/primitive.slice.html):

> Slices are a view into a block of memory represented as a pointer and a length.

Similarly, a `Vec` is just a pointer and a length and capacity.

I'm not sure if there's anything we can do to pretty print these in a debugger.

**Comment by ZPTX4869** [comment]
Cause It also can't show in vsc debug window, but it should be the same problem. I got, I will replace screenshot to text.

**Comment by ZPTX4869** [comment]
> `&[T]` (a slice) is just a pointer combined with a length. Quoting [the docs](https://doc.rust-lang.org/nightly/std/primitive.slice.html):
> 
> > Slices are a view into a block of memory represented as a pointer and a length.
> 
> Similarly, a `Vec` is just a pointer and a length and capacity.
> 
> I'm not sure if there's anything we can do to pretty print these in a debugger.

Please look at this https://users.rust-lang.org/t/debug-in-vscode-cant-show-the-slice-value/53009/10 The bro works fine when he use rust-gdb, when he use 'p' command it gives detail info of vector. But when I debug, I want to see the actual value contained in vec, what should I do?

**Comment by camelid** [comment]
Ah, I didn't know it worked in GDB. Thanks for including that link!

**Comment by camelid** [comment]
@ZPTX4869 I'm not sure why you closed this. It seems likely this is a bug that needs to be fixed.

**Comment by camelid** [comment]
I think this issue still needs to be fixed, right? Let me know if it's fixed :)

**Comment by ZPTX4869** [comment]
Yes, it has been fixed :)

发自我的iPhone

**Comment by camelid** [comment]
Great, thanks!
