### ISSUE TITLE
Check rustc_middle docs for method return type

### ISSUE THREAD

**Issue by pierwill** [rust-lang/rust#80287]
Looking at the following method:

https://github.com/rust-lang/rust/blob/9310aff66c3a9d79c92f621c7f7ca3f87ea9f7de/compiler/rustc_middle/src/middle/region.rs#L451-L457

Are the docs here correct that this "returns `Some((span, expr_count))`"? From the code, it looks like the Some case returns a `Some(YieldData)`. Looks like the docs should be updated to reflect the `YieldData` type.

**Comment by LeSeulArtichaut** [comment]
I think this doc comment is just outdated, feel free to file a PR updating it
