### ISSUE TITLE
"rustc -Z unstable-options --pretty=expanded or.rs" does not create binary

### ISSUE THREAD

**Issue by tivrfoa** [rust-lang/rust#80292]
Hi,

Using `--pretty=expanded` does not create a binary.
This is probably already known, but I think it's bit strange.
I thought that if I'm using `rustc`, then it would create a binary.

**Comment by jonas-schievink** [comment]
I think this is working as intended. `--pretty` tells the compiler to produce a different kind of output, similar to `--emit`.

**Comment by tivrfoa** [comment]
> I think this is working as intended. `--pretty` tells the compiler to produce a different kind of output, similar to `--emit`.

Hi jonas,

I think `--emit` is a clear command of what should be generated, while `--pretty` it's more like a verbose output.

**Comment by jonas-schievink** [comment]
`-v` is for verbose output. Both `--pretty` and `-Zunpretty` output the input source in a different format.

**Comment by tivrfoa** [comment]
> > I think this is working as intended. `--pretty` tells the compiler to produce a different kind of output, similar to `--emit`.
> 
> Hi jonas,
> 
> I think `--emit` is a clear command of what should be generated, while `--pretty` it's more like a verbose output.

I think the behavior of `--pretty` is not what most users would expect, but we get used to it.

One thing that maybe could be done is generate a warn in the end if there's already a binary.
Because people might run the old code thinking it's the new code.

**Comment by tivrfoa** [comment]
> > > I think this is working as intended. `--pretty` tells the compiler to produce a different kind of output, similar to `--emit`.
> > 
> > 
> > Hi jonas,
> > I think `--emit` is a clear command of what should be generated, while `--pretty` it's more like a verbose output.
> 
> I think the behavior of `--pretty` is not what most users would expect, but we get used to it.
> 
> One thing that maybe could be done is generate a warn in the end if there's already a binary.
> Because people might run the old code thinking it's the new code.

But of course it's just a suggestion.
Feel free to close the issue.
Thanks for your attention. =)
