### ISSUE TITLE
VecDeque iter+collect causes an infinite loop (1.48.0)

### ISSUE THREAD

**Issue by matled** [rust-lang/rust#80293]
I discovered that `VecDeque` can produce an infinite loop in an iterator when using iter+collect.

[code demonstrating the issue](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=ac094612a9272cbf61eb28dedc5159c0):
```rust
use std::collections::VecDeque;
use std::iter::FromIterator;

fn main() {
    let mut v = VecDeque::from_iter(0..6);
    v.pop_front();
    v.pop_front();
    v.push_back(6);
    v.push_back(7);
    v.push_back(8);
    v.make_contiguous();
    // `v.iter().collect()` does not terminate at this point.
    // Limit `collect` to `v.len() * 3` to avoid the inifinite iteration.
    let collected: Vec<_> = v.iter().copied().take(v.len() * 3).collect();
    assert_eq!(v.as_slices(), (&collected[..], &[] as &[_]));
    // Result on stable 1.48.0 (7eac88abb 2020-11-16)
    // thread 'main' panicked at 'assertion failed: `(left == right)`
    //   left: `([2, 3, 4, 5, 6, 7, 8], [])`,
    //  right: `([2, 3, 4, 5, 6, 7, 8, 8, 2, 3, 4, 5, 6, 7, 8, 8, 2, 3, 4, 5, 6], [])`', src/main.rs:15:5
}
```

This happens with stable (1.48.0, 7eac88abb). I could not reproduce the issue on 1.50.0-nightly 11c94a197 or 1.49.0-beta.4 877c7cbe1.

I think this may be related/a duplicate of #79808. Particularly 527934d15cf looks highly related to this issue (@lcnr).

I'm filing this bug as I'm not super familiar with Rust and think it may be worth to confirm that this is caused by the same underlying issue and appropriately fixed already.

**Comment by lcnr** [comment]
Yeah, this looks like the same bug to me :+1: Thanks

marking as `E-needs-test`.

**Comment by SmedbergM** [comment]
Very nice MWE, significantly simpler than the one in https://github.com/rust-lang/rust/issues/79808.
