### ISSUE TITLE
rustc is distributed with unnecessary? procedural macros ~60 MB

### ISSUE THREAD

**Issue by tmiasko** [rust-lang/rust#80294]
```console
$ cd ~/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib
$ ls -s -S --si 
total 282M
121M librustc_driver-54c3daf069bcd3f6.so
 94M libLLVM-11-rust-1.50.0-nightly.so
 15M libserde_derive-026483cb77a7c305.so
 15M librustc_macros-5f0ec4a119c6ac86.so
 15M libchalk_derive-0685d79833dc9b2b.so
 14M libtracing_attributes-e4be92c35ab2a33b.so
8,3M libstd-25c6acf8063a3802.so
2,6M libtest-57470d2aa8f7aa83.so
4,1k rustlib/

$ rm libserde_derive-*.so librustc_macros-*.so libchalk_derive-*.so libtracing_attributes-*.so
$ ls -s -S --si
total 224M
...
```

**Comment by jyn514** [comment]
@tmiasko do you have the `rustc-dev` component installed? That adds a bunch more crates to the sysroot.

**Comment by ehuss** [comment]
I believe these are required in rustc-dev as part of the need for `-Z dual-proc-macros` (#64671).  I'll admit, I still don't fully understand the need for that, as it is quite mind-bending.

**Comment by tmiasko** [comment]
They are included in both rustc component and rustc-dev component. The latter are definitely used by for example to build clippy, but I don't see reason for inclusion in rustc.
