### ISSUE TITLE
nightly-rustc docs don't include rustdoc in the index

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#80307]
https://doc.rust-lang.org/nightly/nightly-rustc/ doesn't have a link to https://doc.rust-lang.org/nightly/nightly-rustc/rustdoc/.

### Meta

HEAD is currently at https://github.com/rust-lang/rust/commit/353f3a38460d3c2222d2ab29143f48595b1a32a9.

This is generated with `--enable-index-page`: https://github.com/rust-lang/rust/blob/353f3a38460d3c2222d2ab29143f48595b1a32a9/src/bootstrap/doc.rs#L528

So this is either a bug in rustdoc or bootstrap. Maybe rustdoc needs to be added to https://github.com/rust-lang/rust/blob/353f3a38460d3c2222d2ab29143f48595b1a32a9/src/bootstrap/doc.rs#L541 ?

**Comment by ehuss** [comment]
Sorry, I neglected to include the flag for both invocations.  Posted #80316 with a fix.
