### ISSUE TITLE
API soundness issue in join() implementation of [Borrow<str>]

### ISSUE THREAD

**Issue by Qwaz** [rust-lang/rust#80335]
A weird `Borrow` implementation that returns a different result for each call can create a string with uninitialized bytes with [join()](https://doc.rust-lang.org/std/primitive.slice.html#impl-Join%3C%26%27_%20str%3E) implementation of `[Borrow<str>]` type.

The problem is in [`join_generic_copy`](https://github.com/rust-lang/rust/blob/3ffea60dd5a2260004cc4f487401ae7c7db1aa0e/library/alloc/src/str.rs#L137) function.

1. The borrow result is first used for the length calculation.
https://github.com/rust-lang/rust/blob/3ffea60dd5a2260004cc4f487401ae7c7db1aa0e/library/alloc/src/str.rs#L152-L161

2. Then, inside `spezialize_for_lengths` macro, the user-provided slice is borrowed again and the content is copied.
https://github.com/rust-lang/rust/blob/3ffea60dd5a2260004cc4f487401ae7c7db1aa0e/library/alloc/src/str.rs#L110-L114

3. Finally, the length of the slice is set to the length calculated in step 1.
https://github.com/rust-lang/rust/blob/3ffea60dd5a2260004cc4f487401ae7c7db1aa0e/library/alloc/src/str.rs#L179

[Playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=7432c762775696504c2fb19439fc091a), which demonstrates creating a non-UTF-8 string by only using safe Rust.

**Comment by LeSeulArtichaut** [comment]
Assigning `P-high` [as discussed as part of the Prioritization WG procedure](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2380335.20API.20soundness.20issue.20in.20join().20implementation.20of.20.5BBor.E2.80.A6).

**Comment by steffahn** [comment]
I guess all that’s needed is an `assert!(target.is_empty())` at the end of the body of the `spezialize_for_lengths` macro? Perhaps the typo in its name could be fixed, too. It might also be beneficial to avoid the unnecessary third(!) call to `borrow()` that’s due to `copy_slice_and_advance` using its second argument twice.
