### ISSUE TITLE
`rustc_macros` is not in rustc API docs

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#80345]
Maybe because it's a proc-macro crate? It's not on the crate index list, nor is it in the search index, and https://doc.rust-lang.org/nightly/nightly-rustc/rustc_macros doesn't exist.

**Comment by ehuss** [comment]
Proc-macro documentation is stored in a different directory when `--target` is used.  There is a little more discussion of this at https://github.com/rust-lang/cargo/issues/7677.  It is not clear how feasible that is to fix.

**Comment by jyn514** [comment]
Bootstrap can work around this the same way docs.rs does, by moving `compiler-doc/x86_64-unknown-linux-gnu/rustc_macros` to `compiler-doc/rustc_macros` manually.
