### ISSUE TITLE
Consider returning `&mut T` from `Vec::push` and `insert`

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#80359]
I just reviewed some code that would look like this:

```rust
if vec.is_empty() {
  vec.push(0);
}
let last_element = vec.last().unwrap();
```

It would be nice for `push` to return a `&mut T` so that we can avoid the unwrap:

```rust
let last_element = match vec.last() {
  Some(last) => last,
  None => vec.push(0),
};
```

I think this should be backwards compatible? I guess it could break things like
```rust
fn f() -> () {
  vec![].push(1)
}
```
but that seems like pretty strange code to write.

> This isn't a significant concern in practice. Mostly it just stinks because it's dynamic and Rust users Want Static Verification.

https://gankra.github.io/blah/linear-rust/#must-be-used-at-least-once

**Comment by steffahn** [comment]
This would also break very reasonable code. Some "realistic" example:
```rust
pub fn negative_then_positive(input: &[i32]) -> Vec<i32> {
    let mut negative = vec![];
    let mut positive = vec![];
    for x in input {
        match x.cmp(&0) {
            Less => negative.push(*x),
            Equal => panic!("expecting nonzero values"),
            Greater => positive.push(*x),
        }
    }
    negative.extend(positive);
    negative
}
```

Furthermore by giving access to a `&mut T`, users could be encouraged to use that `&mut T` in cases where they only need a `&T`, _including your own example_. Then imagine the confusion of all the people wondering why the compiler complains about the vec still being borrowed mutable when they only kept an immutable reference `&T`.
```rust
if vec.is_empty() {
  vec.push(0);
}
let last_element = vec.last().unwrap();
// vec is borrowed immutable so that further, immutable access
// to vec is still possible while last_element is used
```
vs
```rust
let last_element = match vec.last() {
  Some(last) => last,
  None => vec.push(0),
};
// vec is borrowed mutably so that further access
// to vec is impossible until last_element is no longer used
```

**Comment by jyn514** [comment]
> Furthermore by giving access to a &mut T, users could be encouraged to use that &mut T in cases where they only need a &T, including your own example. Then imagine the confusion of all the people wondering why the compiler complains about the vec still being borrowed mutable when they only kept an immutable reference &T.

Oh, this is a good point :( and adding `insert_ref` and `insert_mut` seems silly. Fair enough.

**Comment by steffahn** [comment]
An `insert_ref` is not even possible, since the insertion itself needs mutable access.
