### ISSUE TITLE
Add `Debug` and `Display` to the prelude

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#80360]
They are very frequently used, and shouldn't conflict with any local types. Plus, it seems that local items take precedence over prelude imports for name resolution.

**Comment by bjorn3** [comment]
A disadvantage of this is that it is much easier to write `self.foo.fmt(f)` inside a `Debug` or `Display` implementation when `self.foo` only implements one of the traits and then have it break when someone decides to implement the other trait. Currently it is easier to only import one of the traits or use `fmt::Debug::fmt(&self.foo, f)`.

**Comment by camelid** [comment]
Just to be clear, when you say “someone” you mean someone else working on the same crate. The orphan rule would prevent another crate from implementing display or debug.

**Comment by bjorn3** [comment]
I mean when the in the crate that defined the type of `self.foo` an extra implementation is added (possibly a dependency), the current crate could fail to compile.

**Comment by camelid** [comment]
What does "possibly a dependency mean"? I just want to be extra clear so we're not miscommunicating :)

**Comment by bjorn3** [comment]
Something like

```rust
//- dep/lib.rs
struct Foo;
impl Debug for Foo { /* ... */ }
impl Display for Foo { /* ... */ } // <- this is added

//- my/lib.rs
struct Bar {
    foo: Foo
}
impl Debug for Bar {
    fn fmt(&self, f: &mut Formatter) -> Result {
        self.foo.fmt(f) // <- and now this fails to compile
    }
}

**Comment by camelid** [comment]
Yeah, that does seem unfortunate :/

**Comment by camelid** [comment]
Maybe we should only add `Debug` to the prelude?

**Comment by djc** [comment]
I'd prefer just adding `fmt` to the prelude.

**Comment by camelid** [comment]
> I'd prefer just adding `fmt` to the prelude.

It might be nice to have all three, but perhaps just adding `fmt` is a good start and something that can be agreed upon in time.

**Comment by camelid** [comment]
I'll close this issue because as bjorn3 described, adding `Debug` and `Display` to the prelude would probably be more trouble than it's worth.
