### ISSUE TITLE
rustc_trait: Code snippet ignore problem

### ISSUE THREAD

**Issue by pierwill** [rust-lang/rust#80369]
When running `cargo doc` in `compiler/rustc_passes/`, I got the following:

```
warning: could not parse code block as Rust code
  --> compiler/rustc_trait_selection/src/opaque_types.rs:45:9
   |
45 |       /// ```ignore (incomplete snippet)
   |  _________^
46 | |     /// type Foo = impl Baz;
47 | |     /// fn bar() -> Foo {
48 | |     /// //          ^^^ This is the span we are looking for!
49 | |     /// ```
   | |___________^
   |
   = note: error from rustc: this file contains an unclosed delimiter
```

The code is here:

https://github.com/rust-lang/rust/blob/bb178237c5539c75e1b85ab78a8ab902b1f333d5/compiler/rustc_trait_selection/src/opaque_types.rs#L45-L49

**Comment by jyn514** [comment]
@pierwill this particular one should be fixed by https://github.com/rust-lang/rust/pull/79816.
