### ISSUE TITLE
Tracking Issue for const_ptr_read

### ISSUE THREAD

**Issue by usbalbin** [rust-lang/rust#80377]
Feature gate: `#![feature(const_ptr_read)]`

This is a tracking issue for making the functions `ptr::read` and `ptr::read_unaligned`, and the same methods on `*const T` and `*mut T`, `const fn`. This unlocks things like moving values out of arrays in const context.

### Public API

```rust
mod ptr {
    pub const unsafe fn read<T>(src: *const T) -> T;
    pub const unsafe fn read_unaligned<T>(src: *const T) -> T;
}

impl<T> *const T {
    pub const unsafe fn read(self) -> T;
    pub const unsafe fn read_unaligned(self) -> T;
}

impl<T> *mut T {
    pub const unsafe fn read(self) -> T;
    pub const unsafe fn read_unaligned(self) -> T;
}
```

### Steps / History

- [x] Implementation: #79684
- [x] FCP
- [x] Stabilization PR: #97320

#### Related
* const_ptr_write #86302

### Unresolved Questions

Inorder to make `intrinsics::copy` and `intrinsics::copy_nonoverlapping` compile as `const fn`, some checks were removed.
See [comment](https://github.com/rust-lang/rust/pull/79684#discussion_r546257825) for some more info
> For this PR, I see two options:
>
>* Leave it as "something we can do once we have a story for const-dependent dispatch".
>* Comment out the debug assertions for now. Their usefulness is anyway limited since the libstd everyone uses is compiled without debug assertions.
>
>I guess the question is one of evaluating the relative usefulness of these new const operations vs the assertions.

(#79684 did the `Comment out the debug assertions for now.`-thing).

So the question is, how do we bring them back?

**Comment by mbartlett21** [comment]
Should this be mentioned in #57563?

**Comment by usbalbin** [comment]
Perhaps #80697 is a better place to discuss the `Comment out the debug assertions for now`-question? Since #80697 is specifically for `copy[_nonoverlapping]`

**Comment by c410-f3r** [comment]
Are `write` variants also on the track for "constification"?

> - [ ] Implementation: #79684

I guess it can be checked now

**Comment by RalfJung** [comment]
> Are write variants also on the track for "constification"?

Let's say they are on the wish list. ;) With https://github.com/rust-lang/rust/pull/80290, making them `const` should actually be pretty easy now.

**Comment by usbalbin** [comment]
Do we need to wait for #80418 to hit beta before `write` can be implemented without multiple implementations behind `#[cfg(bootstrap)]` or is there any other (not too ugly) way? :) 

Also `intrinsics::forget` seems to be not const while `mem::forget` is const but internally calls `ManuallyDrop::new`. So how would one best solve that without undoing the "inlining" in #80290?

**Comment by RalfJung** [comment]
> Do we need to wait for #80418 (for allowing borrowing) to hit beta before write can be implemented without multiple implementations behind #[cfg(bootstrap)] or is there any other (not too ugly) way? :)

Well... you could use `&mut`. :laughing: 
Probably it's better to wait, though.

> mem::forget is const but internally calls ManuallyDrop::new

This is supposed to be changed in https://github.com/rust-lang/rust/pull/79989.

**Comment by c410-f3r** [comment]
Thank you, @RalfJung !

**Comment by slightlyoutofphase** [comment]
Just popping in to say that I _just_ found out that this and `const_ptr_write` exist and it's like Christmas TBH. The next version I release of my crate `staticvec` is going to be absolutely nuts thanks to these, with const `push`, const `pop`, const `insert`, and various other things.

One thing I'd ask though is if there are plans to make `some_ptr.copy_to()`, `some_ptr.copy_from()` and so on also const-compatible? It seems like there's nothing blocking it, as all of those functions just directly call these intrinsic ones IIRC, and it would be a nice addition on top of this from an ergonomics standpoint.

**Comment by RalfJung** [comment]
> One thing I'd ask though is if there are plans to make some_ptr.copy_to(), some_ptr.copy_from() and so on also const-compatible?

Yeah, those could all easily be made `const fn` as well, I think.

**Comment by usbalbin** [comment]
Perhaps something like this #83091

**Comment by slightlyoutofphase** [comment]
> Perhaps something like this #83091

That looks great if it all works! Didn't even think about `replace`, but I think that would allow me to make even more things `const` too, actually.

Here's an example snippet taking advantage of what's been implemented so far that I'll be including in the demo program for my crate with the next release, by the way:

```rust
// More complex compile-time initialization functions are also possible to write.
const fn build<T: Copy, const N: usize>(x: [T; N]) -> StaticVec<T, N> {
  // StaticVec implements `Drop`, and so can't *directly* be returned from a `const fn` yet,
  // even when `T` is `Copy`.
  let mut mu = MaybeUninit::new(StaticVec::new());
  // Not actually unsafe here: `sv` is just a mutable reference to a normal empty StaticVec.
  let sv = unsafe { mu.assume_init_mut() };
  // `StaticVec::push` is a `const fn`.
  let mut i = 0;
  while i < N {
    sv.push(x[i]);
    i += 1;
  }
  // So is `StaticVec::pop`, so we can also do this...
  while sv.pop().is_some() {}
  // And put everything back in like this...
  sv.insert_from_slice(0, &x);
  // Not actually unsafe here, for the same reasons stated above.
  unsafe { mu.assume_init() }
}
```

Possibly worth noting that the `pop()` part of that required adding a feature flag called `const_refs_to_cell`, which I'd never even heard of. Based on the name of it I'm not sure if that's 100% intentional, so I figured I'd point it out at least.

**Comment by RalfJung** [comment]
These functions got un-`const`ed again to fix https://github.com/rust-lang/rust/issues/84297.

@pnkfelix I don't think I quite understand why you removed all that `const`ness, that seems orthogonal to https://github.com/rust-lang/rust/pull/81238?

**Comment by RalfJung** [comment]
Sorry, I misread, this feature gate is not affected (but some others are).

**Comment by jhpratt** [comment]
@RalfJung @oli-obk any blockers here?

**Comment by Lokathor** [comment]
The item that Oli linked was approved and merged. Does this mean we're ready to move forward, or have other blockers come up in the past few months?

**Comment by oli-obk** [comment]
Nope, a PR assigned to T-libs-api should be uncontroversial now

**Comment by m-ou-se** [comment]
@rfcbot merge

**Comment by RalfJung** [comment]
Is there anything left here? https://github.com/rust-lang/rust/pull/97320 should have closed this issue, no?
