### ISSUE TITLE
Rustdoc renders Vec's new allocator type parameter even when set to the default

### ISSUE THREAD

**Issue by sfackler** [rust-lang/rust#80379]
For example, the docs for this type use `Vec<String, Global>` rather than just `Vec<String>`: https://docs.rs/tokio-postgres/0.7.0/tokio_postgres/types/enum.Kind.html. The definition of the type does not specify the allocator parameter if that matters.

The same is not true for e.g. `HashMap`'s hasher type parameter, so I'm not sure what's different in this case.

**Comment by jyn514** [comment]
The difference is that this is a cross-crate re-export. MCVE:

```rust
// crate1
use std::collections::*;

pub enum Types {
  Map(HashMap<usize, usize>),
  List(Vec<usize>),
  Pointer(Box<usize>),
}

// crate2
pub use crate1::Types;
```
![image](https://user-images.githubusercontent.com/23638587/103156849-20192380-477b-11eb-8285-f14af4f294d8.png)

**Comment by jyn514** [comment]
This is a bug at least back to 1.22.0.

**Comment by jyn514** [comment]
In the inner crate, the params never get passes to `render` in the first place:
```
DEBUG rustdoc::html::format fmt_type(t=ResolvedPath { path: Path { global: false, res: Def(Struct, DefId(4:4837 ~ alloc[4799]::vec::Vec)), segments: [PathSegment { name: "Vec", args: AngleBracketed { args: [Type(Primitive(Usize))], bindings: [] } }] }, param_names: None, did: DefId(4:4837 ~ alloc[4799]::vec::Vec), is_generic: false }
```
but in the outer one they do show up:
```
DEBUG rustdoc::html::format fmt_type(t=ResolvedPath { path: Path { global: false, res: Err, segments: [PathSegment { name: "Vec", args: AngleBracketed { args: [Type(Primitive(Usize)), Type(ResolvedPath { path: Path { global: false, res: Err, segments: [PathSegment { name: "Global", args: AngleBracketed { args: [], bindings: [] } }] }, param_names: None, did: DefId(5:5465 ~ alloc[4799]::alloc::Global), is_generic: false })], bindings: [] } }] }, param_names: None, did: DefId(5:4837 ~ alloc[4799]::vec::Vec), is_generic: false }
```
I expect this has to do with some difference between HIR and metadata loading.

**Comment by jyn514** [comment]
I thought this might be related to inlining, but using `doc(inline)` within the same crate works fine:
![image](https://user-images.githubusercontent.com/23638587/103158005-2ad9b580-4787-11eb-98b0-42e5123cd269.png)

**Comment by jyn514** [comment]
The issue is that metadata types, unlike HIR types, go through `external_path`: https://github.com/rust-lang/rust/blob/89524d0f8e28080197a85e06d143b7d6f131b67e/src/librustdoc/clean/mod.rs#L1584
and external_path doesn't pay any attention to the type defaults: https://github.com/rust-lang/rust/blob/89524d0f8e28080197a85e06d143b7d6f131b67e/src/librustdoc/clean/utils.rs#L103
So rustdoc needs to know which of the generic arguments were added by the user and which are just defaults.

**Comment by jyn514** [comment]
cc https://rust-lang.zulipchat.com/#narrow/stream/266220-rustdoc/topic/What.20is.20the.20difference.20between.20AssocTypeItem.20and.20TypedefItem/near/221461855

**Comment by jyn514** [comment]
> I came across another instance of this recently (#89712), but with a twist. The type that was re-exported also contained a type alias, which was expanded in the re-exported version. Is that the same bug or slightly different?

I suspect they're both caused by using metadata loading instead of HIR, if that's what you're asking, but the fix for the two will likely look different.
