### ISSUE TITLE
Iterating over a range of floats produces discrepancies 

### ISSUE THREAD

**Issue by tuxiqae** [rust-lang/rust#80388]
I tried running [this code](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=b1a3f474bbde1333e0b5ee1a3d5af28f):

```rust
use num::range;

fn main() {
    let (start, end) = (0.01, 128.99);

    for n in range(start, end) {
        println!("{}", n);
    }
}

```

I expected to see this happen: 
I expected to... well, I'm not too sure.
If I would've used `start = 0.1` instead of `start = 0.01` it would've printed all numbers, beginning in `start`, in increments of 1.0, up until `end` (non-inclusive range).
Using `let (start, end) = (0.1, 128.99);` I get:

```
  ⋮
13.01
14.01
15.01
16.01
17.01
18.01
  ⋮
```

I guess I would've expected it to perform the same, even though floats are known to be wonky.
 
Instead, this happened:
As you can see, it just prints the list of numbers but the accuracy after the decimal point differs on 2^x:
- 0-15 end with `.01`
- 16-31 end with `.009999999999998`
- 32-63 end with `.01`
- 64-127 end with `.009999999999998`

### Meta
It behaves the same in both `Stable` and `Nightly`.
I'm not sure whether it's a bug, and if it is, I am not sure whether it's in `rustc` or rather in the `num` crate. 

`rustc --version --verbose`:
```
rustc 1.50.0-nightly (bb178237c 2020-12-25)
binary: rustc
commit-hash: bb178237c5539c75e1b85ab78a8ab902b1f333d5
commit-date: 2020-12-25
host: x86_64-unknown-linux-gnu
release: 1.50.0-nightly
```

<details><summary>Backtrace</summary>
<p>

```
❯ RUST_BACKTRACE=1 cargo build
    Finished dev [unoptimized + debuginfo] target(s) in 0.01s

```

</p>
</details>

**Comment by Mark-Simulacrum** [comment]
This is presumably not a Rust bug, or at least would need a different, more minimal example to be seen as such - I would recommend filing at https://github.com/rust-num/num.

**Comment by tuxiqae** [comment]
Thanks @Mark-Simulacrum :)
