### ISSUE TITLE
Make `RwLockReadGuard` covariant over its type parameter

### ISSUE THREAD

**Issue by Kestrer** [rust-lang/rust#80392]
Currently `RwLockReadGuard` is invariant over its type parameter, meaning that for instance this sound code:

```rust
use std::sync::{RwLock, RwLockReadGuard};

fn do_stuff<'a>(_: RwLockReadGuard<'_, &'a i32>, _: &'a i32) {}

fn main() {
    let j: i32 = 5;
    let lock = RwLock::new(&j);
    {
        let i = 6;
        do_stuff(lock.read().unwrap(), &i);
    }
    drop(lock);
}
```
Will not compile. However, since `RwLockReadGuard` does not allow for mutation of the inner value, it would be sound to make it covariant, and it would be useful in some circumstances.

See also the [same issue in parking_lot](https://github.com/Amanieu/parking_lot/issues/271).

**Comment by sobolevn** [comment]
I would love to give this a try! 👍 
This is my first contribution to `rust`, so I might ask some questions 🙂

**Comment by sobolevn** [comment]
First steps:
- `RwLockReadGuard`'s second type argument is defined here: https://github.com/rust-lang/rust/blob/5d6ee0db96aada145725838379f909bbb8aa2312/library/std/src/sync/rwlock.rs#L102-L104 It is only used for `lock: &'a RwLock<T>`
- `RwLock` is defined here: https://github.com/rust-lang/rust/blob/5d6ee0db96aada145725838379f909bbb8aa2312/library/std/src/sync/rwlock.rs#L78-L82 Its type argument is only used for `data: UnsafeCell<T>` which is the source of invariance according to [these rules](https://doc.rust-lang.org/nomicon/subtyping.html#variance)
