### ISSUE TITLE
Inline `asm!` only checked when used

### ISSUE THREAD

**Issue by phil-opp** [rust-lang/rust#80440]
I tried this code:

```rust
#![feature(asm)]

fn main() {
    // errors if the following line is uncommented
    // foo()
}

pub fn foo() {
    unsafe {
        asm!("xchgfoobarbaz bx, bx");
    }
}
```

([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=30415b442984b78bc23fd2532e6d6dec))

I expected to see this happen: Compilation error because `xchgfoobarbaz` is not a valid assembly instruction.

Instead, this happened: The code compiles without errors or warnings. A compile error only occurs if the `foo()` call is uncommented in `main`.

### Meta

Nightly version on playground: 2020-12-22 bb1fbbf84455fbad9afd

Originally reported by @tomaka in https://github.com/rust-osdev/x86_64/pull/218.

**Comment by Aaron1011** [comment]
In general, I don't think it's possible to solve this. The 'invalid instruction mnemonic' error comes from LLVM - if the `asm!` call occurs in a generic function, then we have no way of generating LLVM IR if it's not called (and therefore monomorphized) at least once.

**Comment by Amanieu** [comment]
Closing as duplicate of #36718.
