### ISSUE TITLE
E0562 should mention impl Trait in argument position

### ISSUE THREAD

**Issue by kpreid** [rust-lang/rust#80476]
`impl Trait` as a type is permitted in function parameter lists. However, the error message E0562 incorrectly states that it is only permitted in function or inherent method _return_ positions.

```rust
/// OK
fn a(x: impl Into<String>) {}
/// OK
fn b() -> impl Into<String> { "bees" }
/// Error
struct C {
    x: impl Into<String>,
}
```
```
error[E0562]: `impl Trait` not allowed outside of function and inherent method return types
 --> src/lib.rs:4:8
  |
4 |     x: impl Into<String>,
  |        ^^^^^^^^^^^^^^^^^
```

Being precise in this message will assist beginners (such as myself a few months ago) in understanding the boundaries of the language. Particularly, one might reasonably imagine equivalence between a function's parameter list and a single parameter whose type is a `struct` bundling several parameters, but `impl Trait` is available in the former and not the latter — whereas the error message implies that it is allowed in _neither_ of those places.

Tangentially, it would be neat if the compiler gave suggestions to rewrite disallowed `impl Trait` as either an explicit parameter,`struct C<S: impl Into<String>> { x: S }`, or (especially in the case of `impl Into`) a constructor function, but that's much more work and more dependent on the context and perhaps even the specific trait.

### Meta

This occurs on both stable `1.48.0` and nightly `1.50.0-nightly (2020-12-22 bb1fbbf84455fbad9afd)`, and the message is present in the same form in [the current source code](https://github.com/rust-lang/rust/blob/c9228570668803e3e6402770d55f23a12c9ae686/compiler/rustc_ast_lowering/src/lib.rs#L1365).

**Comment by Dylan-DPC** [comment]
Current output:
```
error[[E0562]](https://doc.rust-lang.org/nightly/error_codes/E0562.html): `impl Trait` only allowed in function and inherent method return types, not in field types
 --> src/lib.rs:7:8
  |
7 |     x: impl Into<String>,
  |        ^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0562`.
error: could not compile `playground` (lib) due to previous error
```
