### ISSUE TITLE
Derive breaks wildcard import

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust#80490]
```rust
#![allow(unused_imports, dead_code)]

//use crate::a::Type;  // <-- uncommenting makes it work
use crate::a::*;

pub type Repro = Type;

mod a {
    use crate::b::*;

    #[derive(Clone)]  // <-- commenting makes it work
    pub struct Type;
}

mod b {
    pub struct Type;
}

fn main() {}
```

```console
$ rustc src/lib.rs --edition=2018
error[E0412]: cannot find type `Type` in this scope
 --> src/lib.rs:6:18
  |
6 | pub type Repro = Type;
  |                  ^^^^ not found in this scope
  |
help: consider importing one of these items
  |
4 | use crate::a::Type;
  |
4 | use crate::b::Type;
  |
```

<br>

#### Observations:

- Changing `use crate::a::*` to `use crate::a::Type` makes it work. My expectation would be that `*` includes `Type`.
- Removing the derive on `Type` makes the wildcard import work.
- Also reproduces with a proc macro derive in place of standard library builtin derive. Tested with `derive(serde::Serialize)`.
- Does not reproduce with handwritten Clone impl, only with derive.
- Reproduces on every compiler since 1.15.0 through most recent nightly.

**Comment by dtolnay** [comment]
Mentioning @petrochenkov @davidhewitt since you have been active in name resolution recently. (This is not a new bug but you might have insight.)

**Comment by petrochenkov** [comment]
Looks similar to https://github.com/rust-lang/rust/issues/56593, this is a long standing issue.

**Comment by dtolnay** [comment]
Thanks, good call. I failed to find that one searching for variations of "wildcard" and "derive".
