### ISSUE TITLE
Keyword doc of `self` and `Self` points to the same file on windows.

### ISSUE THREAD

**Issue by crlf0710** [rust-lang/rust#80504]
Since windows filesystem is case insensitive, when installing rust-docs on windows, the `self` and `Self` pages conflicts, leaving only one of them accessible.

This is a specific case of #25879, but since it's in rust standard library. I think it deserves its own issue (and priority).

**Comment by GuillaumeGomez** [comment]
There was a first attempt to fix this issue [here](https://github.com/rust-lang/rust/pull/59785), but not sure if this is the right approach.

**Comment by rbtcollins** [comment]
For completeness - they point to the same file on MacOS X as well.
