### ISSUE TITLE
Suggestion to reorder generic parameters ignores type defaults

### ISSUE THREAD

**Issue by varkor** [rust-lang/rust#80512]
```rust
struct S<T = (), 'a>(&'a T);
```
results in:
```
error: lifetime parameters must be declared prior to type parameters
 --> src/lib.rs:1:18
  |
1 | struct S<T = (), 'a>(&'a T);
  |         ---------^^- help: reorder the parameters: lifetimes, then types, then consts: `<'a, T>`
```
when it should be:
```
help: reorder the parameters: lifetimes, then types, then consts: `<'a, T = ()>`
```
This should be easy to fix: just replace `ident` in the following line with an appropriate format string.
https://github.com/rust-lang/rust/blob/d107a87d34c1fc3521aaab7a2576ffbaf59cb2cb/compiler/rustc_ast_passes/src/ast_validation.rs#L1157

**Comment by max-heller** [comment]
> This should be easy to fix: just replace `ident` in the following line with an appropriate format string.
> https://github.com/rust-lang/rust/blob/d107a87d34c1fc3521aaab7a2576ffbaf59cb2cb/compiler/rustc_ast_passes/src/ast_validation.rs#L1157

For the record, it's not quite this simple, as doing so results in incorrect output when the parameter also has bounds. For example, it would render `T: 'a = ()` as `T = (): 'a` because bounds are printed after the `ident`
