### ISSUE TITLE
Rustdoc treats primitive disambiguators incorrectly

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#80559]
I tried this code:

```rust
//! [str::trim()]
```

I expected to see this happen: Rustdoc links to https://doc.rust-lang.org/nightly/std/primitive.str.html#method.trim.

Instead, this happened: Rustdoc gets confused that `()` means a function and thinks that the link is a primitive.

```
error: incompatible link kind for `str::trim`
   |
   |
57 | /// Using the [`str::trim()`] method ensures that no whitespace remains before parsing.
   |                ^^^^^^^^^^^^^ help: to link to the builtin type, prefix with `prim@`: ``prim@str::trim``
   |
   = note: `-D broken-intra-doc-links` implied by `-D warnings`
   = note: this link resolved to a builtin type, which is not a function
```

### Meta

`rustdoc --version`:
```
rustdoc 1.50.0-beta.1 (05b602367 2020-12-29)
```

Relevant code: https://github.com/rust-lang/rust/blob/a6bd5246da7806786b5c1f61d05a957c9ae68903/src/librustdoc/passes/collect_intra_doc_links.rs#L1181

I think the fix is just to add `if self.kind_side_channel.is_none()` as a match guard.

**Comment by jyn514** [comment]
This is blocking https://github.com/rust-lang/rust/pull/75807 and made https://github.com/rust-lang/rust/pull/77875#discussion_r503583103 unnecessarily difficult.

**Comment by max-heller** [comment]
@jyn514 which arm do you mean to add the match guard to?

**Comment by jyn514** [comment]
@max-heller the one for telling if the resolved item is a primitive: https://github.com/rust-lang/rust/blob/a6bd5246da7806786b5c1f61d05a957c9ae68903/src/librustdoc/passes/collect_intra_doc_links.rs#L1176

**Comment by max-heller** [comment]
@jyn514 It looks like `self.kind_side_channel` is in fact `None` for `str::trim()`

**Comment by jyn514** [comment]
Oh hmm - the issue is that for primitives, rustdoc generates the anchor manually: https://github.com/rust-lang/rust/blob/a6bd5246da7806786b5c1f61d05a957c9ae68903/src/librustdoc/passes/collect_intra_doc_links.rs#L401-L402. I would try storing the `def_id` of the associated item in `kind_side_channel` instead, so you know later whether the anchor is a manual link (`str#method.trim`) or whether it was generated by rustdoc.

**Comment by max-heller** [comment]
Adding `self.kind_side_channel.set(Some((item.kind.as_def_kind(), item.def_id)));` in here
https://github.com/rust-lang/rust/blob/a6bd5246da7806786b5c1f61d05a957c9ae68903/src/librustdoc/passes/collect_intra_doc_links.rs#L394-L398
and adding the match guard seems to fix things, but also feels like a hack.

**Comment by jyn514** [comment]
I mean, all of `kind_side_channel` is a hack because other parts of rustdoc break when you store the associated item instead: https://github.com/rust-lang/rust/commit/0c99d806eabd32a2ee2e6c71b400222b99c659e1. If you can figure out a way to get rid of it, I'd love to do that, but it will require some pretty major refactors I think.
