### ISSUE TITLE
Compilation succeeds even if there is #[inline] in the structure field.

### ISSUE THREAD

**Issue by Danue1** [rust-lang/rust#80564]
I tried this code:

```rust
struct Foo {
    #[inline]
    bar: String,
}
```

I expected to see this happen: Failing complilation.

Instead, this happened: Compilation success.

### Meta

`rustc --version --verbose`:
```
rustc 1.49.0-beta.4 (877c7cbe1 2020-12-10)
binary: rustc
commit-hash: 877c7cbe142a373f93d38a23741dcc3a0a17a2af
commit-date: 2020-12-10
host: x86_64-apple-darwin
release: 1.49.0-beta.4
```

**Comment by ehuss** [comment]
Some validation was added in #73461, but it looks like there are a few places that are missing.  The ones I can see are struct fields and match arms:

```rust
struct Foo {
    #[inline]
    bar: String,
}

match foo {
    #[inline]
    _ => {}
}
```

I believe that [`CheckAttrVisitor`](https://github.com/rust-lang/rust/blob/44e3daf5eee8263dfc3a2509e78ddd1f6f783a0e/compiler/rustc_passes/src/check_attr.rs#L866-L948) needs to include visitor methods for `visit_arm` and `visit_struct_field`.

**Comment by Danue1** [comment]
Hmm, I think I can do it, so I'll try it.

**Comment by Danue1** [comment]
solved!
