### ISSUE TITLE
`mod Keyword {}` should suggest `r#keyword` instead of `keyword`

### ISSUE THREAD

**Issue by Havvy** [rust-lang/rust#80575]
When you write a mod with a capital name of a keyword, we suggest changing it to the lowercase version of the keyword, which is, well, a keyword and not going to work. We should suggest converting the identifier to snake case and making it a raw identifier, or maybe suggest switching to an altogether separate name?

```
  |
1 | mod Impl {}
  |     ^^^^ help: convert the identifier to snake case (notice the capitalization): `impl`
  |
  = note: `#[warn(non_snake_case)]` on by default
```

**Comment by hencrice** [comment]
Hey @Skynoodle, you might want to comment `@rustbot claim` here to claim this issue :)
