### ISSUE TITLE
make: metabug for make issues

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#8058]
Will add issues to this by referring to it from the other bugs (so that their open/closed status is updated accordingly).

Can close when either all make bugs are fixed (hah) or when we move to rustpkg (permanently).

**Comment by steveklabnik** [comment]
Triage: this is a metabug issue, so no change.

**Comment by steveklabnik** [comment]
Triage: only change is that hopefully `make` will be replaced by `rustbuild` in a near-ish timeframe.

**Comment by alexcrichton** [comment]
Make's gone, so closing.
