### ISSUE TITLE
Type names are difficult to select in rustdoc.

### ISSUE THREAD

**Issue by bhickey** [rust-lang/rust#80582]
It's difficult to select a typename in rust doc. Most of the time I end up selecting `Enum ... [-] src` or `Struct ... [-] src`. Can you make it easy to select the thing that users probably want to select?

<img width="1016" alt="Screen Shot 2021-01-01 at 10 35 35 AM" src="https://user-images.githubusercontent.com/136625/103441602-167d3900-4c1d-11eb-9611-5bbdb5d832c4.png">

**Comment by GuillaumeGomez** [comment]
Will do it in the next days!

**Comment by GuillaumeGomez** [comment]
Just by curiosity: do you have the same issue on doc.rust-lang.org/nightly/std ? Because I don't have any issue to select the type name, so maybe it was something specific to older versions?

**Comment by camelid** [comment]
Closing in favor of #82042 since it has more activity.
