### ISSUE TITLE
https://renproject.io/developers

### ISSUE THREAD

**Issue by syncing0x** [rust-lang/rust#80606]
### Code

I tried this code:

```rust
<code>
```

I expected to see this happen: *explanation*

Instead, this happened: *explanation*

### Version it worked on

It most recently worked on: 

### Version with regression

`rustc --version --verbose`:
```
<version>
```

### Backtrace

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by syncing0x** [comment]
https://renproject.io/developers

**Comment by camelid** [comment]
Spam.

**Comment by syncing0x** [comment]
https://renproject.io/developers

**Comment by syncing0x** [comment]
https://renproject.io/developers
