### ISSUE TITLE
Tracking Issue for infallible promotion

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#80619]
This is a tracking issue for the RFC "3027" (rust-lang/rfcs#3027).
The RFC does not have a feature gate.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Implement the RFC
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Unresolved Questions

* What should we do about promoting `const fn` calls in `const`/`static` initializers? See [this crater analysis](https://github.com/rust-lang/rust/pull/80243#issuecomment-751885520) and [this Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/213817-t-lang/topic/Promotion.20of.20const.20fn.20calls.20in.20const.2Fstatic.20initializers/near/221361952).

### Implementation history

* https://github.com/rust-lang/rust/pull/77526
* https://github.com/rust-lang/rust/pull/78363
* https://github.com/rust-lang/rust/pull/80579

**Comment by RalfJung** [comment]
In https://github.com/rust-lang/rust/pull/80243 we learned that there is at least some code that relies in non-trivial ways on `const fn` calls being promoted in a `const`/`static` initializer. We need to figure out how to move forward with such code.  I see these options:
* Live with the fact that promoteds in const/static initializers can fail even if they are not required for said initializer. This means no breaking change here, but it will require care in MIR optimizations, MIR printing, maybe more.
* Make sure that all potentally-failing promoteds in const/static initializers are required to compute the value of the const. This will require some break change. There are different alternatives here:
  - Never promote anything that might fail -- this breaks some real code (no idea how much, it's only 2 crates in crater), but leads to a rather clean situation.
  - Only promote things that fail if they are in parts of the CFG that will definitely be evaluated -- that will however be rather surprising behavior, so maybe we want to do this only for old editions. In particular, a proper post-dominance analysis might be too expensive, so we might just check if the *entire* CFG is linear, or we only promote on the "linear head" of the CFG; in either case, adding a conditional somewhere in the code will stop promotion of things further down that code, which is rather odd.

**Comment by Aaron1011** [comment]
> Never promote anything that might fail -- this breaks some real code (no idea how much, it's only 2 crates in crater), but leads to a rather clean situation.

Can that code be made to compile with inline `const` blocks?

**Comment by RalfJung** [comment]
@Aaron1011 yes it can, but only once inline const blocks can use generics of the surrounding context.

**Comment by RalfJung** [comment]
I think this is probably the best option:

> Live with the fact that promoteds in const/static initializers can fail even if they are not required for said initializer. This means no breaking change here, but it will require care in MIR optimizations, MIR printing, maybe more.

https://github.com/rust-lang/rust/pull/85112 ensures that at least a normal build handles this correctly. @oli-obk any idea how to check other MIR consumers such as MIR printing for this?

**Comment by oli-obk** [comment]
MIR printing should just print the path to unevaluated constants and not eval them at all. The only other thing would be optimizations, but these aren't run for constants' bodies

**Comment by RalfJung** [comment]
> MIR printing should just print the path to unevaluated constants and not eval them at all.

As in, it already does that, or it should be changed to do that?

**Comment by oli-obk** [comment]
I believe it does that. At least I specifically remember seeing paths being printed for things that could have been evaluated.

**Comment by RalfJung** [comment]
If we end up deciding we are okay with promoting `const fn` calls in `const/`static` bodies, we might then also accept other things like general array indexing or division -- we could accept basically everything that qualifies syntactically, i.e., anything that does not depend on surrounding variables. I am not sure what is the better choice -- this makes the rules even more inconsistent, but the rules already *are* wildly inconsistent to the extend that people do get confused by it (e.g., https://github.com/rust-lang/rust/issues/85181).

**Comment by joshtriplett** [comment]
What items from RFC 3027 remain to be implemented?

We talked about this in today's @rust-lang/lang meeting, and we know that `const { ... }` still needs further implementation, but we weren't sure if that was a blocker for this or if all the work specified by the RFC was complete.

**Comment by RalfJung** [comment]
@joshtriplett the main open question is what is listed as unresolved question in the issue:

> What should we do about promoting const fn calls in const/static initializers? See [this crater analysis](https://github.com/rust-lang/rust/pull/80243#issuecomment-751885520) and [this Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/213817-t-lang/topic/Promotion.20of.20const.20fn.20calls.20in.20const.2Fstatic.20initializers/near/221361952).

Basically we still promote arbitrary function calls inside const/static initializers. We need to decide whether we want to
- Live with this technical debt
- Try to slowly phase it out in favor of `const` blocks (once those are stable)

This is a MIR building thing so it could potentially be done at an edition boundary. However, as long as *any* edition promotes arbitrary fn calls, MIR optimizations need to be careful and not overeagerly evaluate constants they find to determine their value. So the technical debt does not become any better by making this an edition thing. I am not sure whether doing this only for the sake of "rules of the latest edition are easier to explain" is worth it.

**Comment by RalfJung** [comment]
Looks like inline_const will be stabilized soon. :D
https://github.com/rust-lang/rust/pull/104087

I wonder if that could let us move towards deprecating promotion more?
- Entirely stop promoting function calls in a future edition (only promoting trivial things like `&3`)
- I guess we can't remove this for older editions but maybe we can desugar it to const blocks somewhere early, and thus simplify the promotion machinery?

**Comment by RalfJung** [comment]
I'd really like to explain promotion entirely as "implicitly inserting `const` blocks" -- and ideally even implement it like that. So here's a plan:
- Get inline_const stabilized, actually, soon, maybe, finally, eventually?
- On all editions, promote (via implicit inline consts) the things that we currently promote in runtime code (in particular, these are all infallible)
- On old editions, additionally promote (via implicit inline consts) const function calls. Show a warning that suggests to use inline consts instead; this is how we get compatibility with the newer edition.

This *is* a breaking change, for code like that:
```rust
const fn panic() { panic!(); }

const C: () = {
  if false { let x = &panic(); }
}
```
We'd start rejecting such code, on all editions, because the promoted becomes a required_const. But I hope such code to be rare...
Specifically this affects constants that have unreachable branches that contain an `&call()` that fails to evaluate. (If the branch is inside a `const fn` it's fine, only directly in the `const` does it become a problem.)

To get the desired compiler model changes, there's not really any non-breaking path -- the goal is to make it so that any `const` we can find in the body of an item can be evaluated and we know doing so will never cause new compilation failures.

**Comment by oli-obk** [comment]
To do that we'll have to move promotion checks to THIR or even HIR, right?

Tho I guess we could do it in MIR if we figure out https://github.com/rust-lang/rust/pull/115613 and thus can land https://github.com/rust-lang/rust/pull/111693 without a perf regression

**Comment by RalfJung** [comment]
I think it'd be better to do it in THIR/HIR, yes.

**Comment by RalfJung** [comment]
Specifically, here's a possible plan:
- step 1: get rid of "constants that may fail". This means adding all promoteds to `required_consts`. This is a breaking change for code like [this](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=679640f7a9f3ba43e06f6783f8772904). The work-around is to write it like [this](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=c8df7f37954e3fb048985086cd2fd235) instead.
    If we can do this it would afford us not having to worry about which const is evaluated when when working on any MIR. That seems valuable, so I very much hope that this doesn't break any actual code out there.
    Ideally we'd start with some sort of forward-compat lint. But I'm not sure how to best do that. We cannot run const-eval and then if it fails take back the hard error -- that was the entire point of the "const-eval is a hard error" refactoring. One could of course add a new query that just starts the interpreter and returns whether there was any error, but that's terrible for performance. However, this can only be a breaking change for *pure-const MIR (i.e., not a `fn`/`const fn`) when a function call got promoted in a block that does not dominate the return block*. So maybe we can detect that case, and then either lint directly, or fire off the magic test-if-fail interpreter query only for those promoteds?
    The good part is that this step is not blocked on inline const. Also if we can complete this transition we can remove the hacky code again. For diagnostics we just need a bit of information somewhere that the thing that failed was a promoted, and maybe you want to apply the ugly work-around to prevent it from being promoted.
- step 2: clean up promotion rules. In a future edition, no longer promote function calls (except for the few allowlisted ones). This is also hard to have a future-incompat lint for -- we could lint against any `&call()` inside pure-const MIR, but many of those are likely fine without promotion, and not all of them will even build as `&const { call() }`. We'd have to not promote, run borrowck, and then if it fails promote, run borrowck again, and if that helped then lint... that sounds terrible, right?^^ And this is code we'd have to keep around forever to support old editions and help code to transition to the new edition. The only alternative I can think of is to just not have a transition or a lint, run crater, file PRs, repeat until crater is green, and hope for the best... we used to get away with that for some of the other promotion changes, but its' been a few years and Rust has grown and that time might be over.

Maybe someone has a better idea for step 2. But at least step 1 seems doable?

**Comment by RalfJung** [comment]
Regarding the chance to entirely get rid of promotion of function calls -- currently, that breaks the build of cargo, due to [this](https://github.com/time-rs/time/blob/26652611d5d3db618d01aeeeeacbce33b65b3102/time/src/serde/mod.rs#L405) constant in `time`:
```rust
const UTC_OFFSET_FORMAT: &[FormatItem<'_>] = &[
    FormatItem::Component(Component::OffsetHour({
        let mut m = modifier::OffsetHour::default();
        m.sign_is_mandatory = true;
        m
    })),
    FormatItem::Optional(&FormatItem::Compound(&[
        FormatItem::Literal(b":"),
        FormatItem::Component(Component::OffsetMinute(modifier::OffsetMinute::default())),
        FormatItem::Optional(&FormatItem::Compound(&[
            FormatItem::Literal(b":"),
            FormatItem::Component(Component::OffsetSecond(modifier::OffsetSecond::default())),
        ])),
    ])),
];
```
The `default()` calls here are function calls which are being promoted.

This could easily be fixed by using associated consts instead of functions. But who knows what we'd run into next...

**Comment by RalfJung** [comment]
https://github.com/rust-lang/rust/pull/121557 landed. So we have finally achieved ~~Elysium~~ the property that all potentially failing consts are captured by required_consts. :)

I think we can consider the RFC to be fully implemented now. :tada: 
I have opened https://github.com/rust-lang/rust/issues/124328 to track cleaning up the "hacks" we had to add to get here.
