### ISSUE TITLE
Wrong drop order with final match expression

### ISSUE THREAD

**Issue by Jarcho** [rust-lang/rust#80640]
I tried this code:

```rust
struct X(&'static str);
impl Drop for X {
    fn drop(&mut self) {
        println!("dropped {}", self.0);
    }
}

fn main() {
    let x = X("1");
    match X("2") {
        _ => (),
    }
}
```

([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=3b51fdd9183ef26419036ed0a7e6e647))

Expected output:

```
dropped 2
dropped 1
```

Actual output:

```
dropped 1
dropped 2
```

If a semicolon is added after the match expression then the drop order is as expected.

Tested on stable 1.49 on the playground.

**Comment by jonas-schievink** [comment]
This is working as intended. `match` drops the scrutinee only after the whole `match` is evalutated, and the trailing expression in a block is dropped after all locals.
