### ISSUE TITLE
Explain "It is a logic error ... " in HashMap, BTreeMap and others

### ISSUE THREAD

**Issue by ChrisJefferson** [rust-lang/rust#80657]
In various pieces of the documentation that talk about "It is a logic error ...", mostly to change the keys of HashMap/Sets and BTreeMap/Sets, using RefCells or hashing functions which change their behaviour based on global variables.

What does "it is a logic error ... " mean? With some brief playing it appears (to me) that it puts the datastructure in an inconsistent state, where future calls to any member function can return nonsense values.

It appears (from what I can tell) there is no unsafe behaviour, and it isn't possible to make the datastructures call `panic`, but I would be happy to say they could panic (saying they won't means checking they can't when someone has already done something stupid).

So, I suggest a short extra sentence which just says "These logic errors can lead to incorrect results and panics but not unsafe behaviour"

**Comment by camelid** [comment]
By "unsafe behavior" I assume you mean "Undefined Behavior"?

**Comment by Mark-Simulacrum** [comment]
We must guarantee that there is no UB as a result of nonsense Ord/Hash/PartialEq etc impls, but I do not think we should guarantee anything beyond that. I would be open to a PR making a change improving the wording here.
