### ISSUE TITLE
Default target regression since 1.48

### ISSUE THREAD

**Issue by rxrbln** [rust-lang/rust#80663]
When bootstrapping Rustc from source, e.g. for embedded use cross compiling for another architecture, e.g. i586, arm, mips, etc. rustc since 1.48 no longer defaults to the configured target tripplet.

Configured with:
./configure --prefix=/usr/src/t2-clean/build/x86-20.12-generic-x86-i586-cross-linux/TOOLCHAIN/tools.cross/usr --libdir=/usr/src/t2-clean/build/x86-20.12-generic-x86-i586-cross-linux/TOOLCHAIN/tools.cross/usr/lib --llvm-config=/usr/src/t2-clean/build/x86-20.12-generic-x86-i586-cross-linux/TOOLCHAIN/tools.cross/usr/bin/llvm-config --release-channel=stable --disable-codegen-tests --target= i586-unknown-linux-gnu --build=x86_64-unknown-linux-gnu --host=x86_64-unknown-linux-gnu

I expected to yield a compiler defaulting to i586.

Instead since 1.48 it defaults to the host: # rustc --print cfg
debug_assertions
target_arch="x86_64"
target_endian="little"
target_env="gnu"
target_family="unix"
target_feature="fxsr"
target_feature="sse"
target_feature="sse2"
target_os="linux"
target_pointer_width="64"
target_vendor="unknown"
unix

The std is however correctly build for i586 (or arm, mips, ...) and does work when manually requested thru --target or cargo. However, for integration we need the default to work correctly to avoid nightmarish complexity building other large projects, such as Firefox. The end of the build log includes:

install: installing component 'rust-std-i586-unknown-linux-gnu'

    std is standing at the ready.

Dist rustc stage2 (x86_64-unknown-linux-gnu)
        finished in 15.071
Install rustc stage2 (Some(TargetSelection { triple: "x86_64-unknown-linux-gnu", file: None }))

In any case, this used to work for quite a while, and regressed since Rustc 1.48.0 and is still broken in 1.49.0

**Comment by jyn514** [comment]
cc @Mark-Simulacrum - I think I remember hearing that this change was intentional, but I can't remember which PR changed it.

**Comment by Mark-Simulacrum** [comment]
Would be great to get a bisection; I don't recall this being intentional.

**Comment by rxrbln** [comment]
On further investigation it looks like the default target was already the host with 1.47.0 I'm still investigating why 1.48 and 1.49 regress with Firefox in our embedded builds. Maybe there is something else going on. However, maybe the default target should be the configured cross target?
