### ISSUE TITLE
Erroneous suggestion for uninferred const generic

### ISSUE THREAD

**Issue by Armavica** [rust-lang/rust#80687]
Hello, I noticed that the error message for an uninferred const generic proposes an erroneous suggestion in this case:

I tried this code:

```rust
struct Foo<const N: usize>;
impl<const N: usize> Foo<N> {
    fn new() -> Self {
        Foo {}
    }
}
fn main() {
    let foo = Foo::new();
    //~^ ERROR type annotations needed
}
```

I expected to see this happen:
```
error[E0282]: type annotations needed for `Foo<{_: usize}>`
  --> $DIR/uninferred-consts-paths.rs:14:15
   |
LL |     let foo = Foo::new();
   |         ---   ^^^ cannot infer the value of const parameter `N` declared on the struct `Foo`
   |         |
   |         consider giving `foo` the explicit type `Foo<{_: usize}>`, where the type parameter `N` is specified
   |
help: consider specifying the const argument
   |
LL |     let foo = Foo::<N>::new();
   |               ^^^^^^^^

```

Instead, this happened: 
```
error[E0282]: type annotations needed for `Foo<{_: usize}>`
  --> $DIR/uninferred-consts-paths.rs:14:15
   |
LL |     let foo = Foo::new();
   |         ---   ^^^^^^^^ cannot infer the value of const parameter `N` declared on the struct `Foo`
   |         |
   |         consider giving `foo` the explicit type `Foo<{_: usize}>`, where the type parameter `N` is specified
   |
help: consider specifying the const argument
   |
LL |     let foo = Foo::<N>();
   |               ^^^^^^^^

```

### Meta
`rustc --version --verbose`:
```
rustc 1.51.0-nightly (80184183b 2021-01-03)
binary: rustc
commit-hash: 80184183ba0a53aa4f491753de9502acd3d6920c
commit-date: 2021-01-03
host: x86_64-unknown-linux-gnu
release: 1.51.0-nightly
```

**Comment by Armavica** [comment]
I would be interested in tackling this bug, but I am unfamiliar with the compiler internals and would be grateful for some guidance. As far as I understand, [this span](https://github.com/rust-lang/rust/blob/master/compiler/rustc_infer/src/infer/error_reporting/need_type_info.rs#L636) is too large (corresponds to `Foo::new` instead of just `Foo`), which causes the error. So my plan is to find a way to restrict it to just `Foo` in this case. Is this a good approach?

**Comment by varkor** [comment]
@Armavica: I think you're on the right lines. The simplest solution might be to collapse the span to the end with `shrink_to_hi` (so it points in between the method name and the parentheses) and replace `format!("{}::<{}>", parent, arg_data.name))` with `format!("::<{}>", arg_data.name))`. Some of the preceding lines can then be simplified.

**Comment by Armavica** [comment]
Thank you for your advice! However, I am not sure how to solve this any more. If I understand correctly, `shrink_to_hi` is not sufficient to solve the issue, because in this case, the span is `Foo::new` and we don't want to insert the const parameter between the method name and the parentheses, but rather between the struct and the method names.

I think that the span in the [origin](https://github.com/rust-lang/rust/blob/68ec33261183ffc21de96d6f825b02373e22e835/compiler/rustc_infer/src/infer/error_reporting/need_type_info.rs#L278) of the const parameter is incorrect, because it covers `Foo::new` rather than just `Foo`. If I understand correctly, this struct (`ConstVariableOrigin`) gets created in the function [`var_for_def`](https://github.com/rust-lang/rust/blob/68ec33261183ffc21de96d6f825b02373e22e835/compiler/rustc_infer/src/infer/mod.rs#L1094), called by [`ct_infer`](https://github.com/rust-lang/rust/blob/68ec33261183ffc21de96d6f825b02373e22e835/compiler/rustc_typeck/src/check/fn_ctxt/mod.rs#L236), at which point I am getting lost… Should I push further to identify where the incorrect span comes from, or I am completely misguided?

**Comment by varkor** [comment]
@Armavica: ah, you're right, sorry! I'm not sure the origin of the const parameter is necessary incorrect, but I think we could be including more data in `InferenceDiagnosticsData`, namely a `parent_span: Option<Span>`.
https://github.com/rust-lang/rust/blob/b63a7a2c6cd809e3eb3765bdcfc4236a04dcea64/compiler/rustc_infer/src/infer/error_reporting/need_type_info.rs#L216-L222
After we get the parent `DefId`, we should be able to get its span, e.g. with `span_if_local`.
https://github.com/rust-lang/rust/blob/b63a7a2c6cd809e3eb3765bdcfc4236a04dcea64/compiler/rustc_infer/src/infer/error_reporting/need_type_info.rs#L293
We should then be able to replace `span` with `arg_data.parent_span` here:
https://github.com/rust-lang/rust/blob/3b63e16552bbc3bfdddad67ba219455a2a3ac03c/compiler/rustc_infer/src/infer/error_reporting/need_type_info.rs#L626

**Comment by Armavica** [comment]
Thank you for your very detailed answer. However, unless I am doing it wrong, I don't think that this works, because `parent_def_id` refers to the structure definition (`struct Foo<const N: usize>`), and not to the `Foo` part of the path `Foo::new()`. This is what made me think that it is `origin` that is to blame. Did I misunderstand something?

**Comment by varkor** [comment]
@Armavica: ah, my mistake, that does sound right 😓  Sorry for wasting your time. The origin span is coming from
https://github.com/rust-lang/rust/blob/b63a7a2c6cd809e3eb3765bdcfc4236a04dcea64/compiler/rustc_typeck/src/astconv/mod.rs#L492
Let's see whether changing that span fixes the issue (and doesn't regress any other diagnostics). Otherwise, we might need a more sophisticated solution like for type parameters (below).
https://github.com/rust-lang/rust/blob/b63a7a2c6cd809e3eb3765bdcfc4236a04dcea64/compiler/rustc_infer/src/infer/error_reporting/need_type_info.rs#L502-L596

**Comment by Dylan-DPC** [comment]
Closing this as complete and the current output suggests what's exepcted

**Comment by varkor** [comment]
@Dylan-DPC: do we have a test for this already? If not, it would be better to mark as E-needs-test instead.
