### ISSUE TITLE
Invalid feature suggestion: #[feature(const_generics)]

### ISSUE THREAD

**Issue by DutchGhost** [rust-lang/rust#80702]
When writing a const generic that uses a type other than `bool`, `char` or `integer`, the compiler generates the following error message:

```
error: `std::sync::atomic::Ordering` is forbidden as the type of a const generic parameter
 --> src/lib.rs:5:21
  |
5 | struct Bug<const O: atomic::Ordering>;
  |                     ^^^^^^^^^^^^^^^^
  |
  = note: the only supported types are integers, `bool` and `char`
  = help: more complex types are supported with `#[feature(const_generics)]`
```

However, this error message is wrong, as its missing a `!` in the feature suggestion.
It should be `#![feature(const_generics)]` rather than `#[feature(const_generics)]`

**Comment by lzutao** [comment]
One just need to change this line: https://github.com/rust-lang/rust/blob/61f5a0092364061ec5649ca98d5e3e9b927880fe/compiler/rustc_typeck/src/check/wfcheck.rs#L333

**Comment by varkor** [comment]
> then bless respective stderr files.

One doesn't even need to build the compiler: a search and replace for `#[feature(const_generics)]` in `src/test` would be enough.

**Comment by jakevossen5** [comment]
I can do this quick if that's okay.
