### ISSUE TITLE
rust-toolchain toml file does not work

### ISSUE THREAD

**Issue by Luis-Hebendanz** [rust-lang/rust#80719]
I tried to use the `rust-toolchain` file in toml format like described here: https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file.
However on cargo run I get the error:
```
error: invalid channel name '[toolchain]' in 'svm_kernel/rust-toolchain'
error: caused by: invalid toolchain name: '[toolchain]'
```

Then I tried to rename the file to `rust-toolchain.toml` that did not help either.
```bash
$ cargo --version
cargo 1.50.0-nightly (75d5d8cff 2020-12-22)
```

**Comment by jonas-schievink** [comment]
You need to update rustup
