### ISSUE TITLE
error: 'sysinfo not supported on this platform' in FreeBSD

### ISSUE THREAD

**Issue by wisonye** [rust-lang/rust#80739]
Hi there, there is some problems when installing and running `Rust` in `FreeBSD`. 
I've already tried that on my son's laptop.

When installing `rust` via the command show in official website:

```bash
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
```

It prints out many `error: 'sysinfo not supported on this platform' in FreeBSD`. When I add some components, it also show that error like below:

![screenshot-2021-01-06_12:58:20](https://user-images.githubusercontent.com/3477321/103714185-ed94e380-5022-11eb-824d-d6a32070dd97.png)

<hr>

After installing, can compile and run rust code with no any problem. But I installed `cargo-watch` as well,
and it delay a few seconds to detect the file change, no sure relate the above error or not :)

</br>

`uname -a` output in his laptop:

```
FreeBSD mike-bsd 13.0-CURRENT FreeBSD 13.0-CURRENT #0 main-c255460-g282381aa53a: Thu Dec 31 06:08:47 UTC 2020     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/amd64.amd64/sys/GENERIC  amd64
```

**Comment by jonas-schievink** [comment]
rustup issues should be filed at https://github.com/rust-lang/rustup
