### ISSUE TITLE
Relax the lifetime bound on references

### ISSUE THREAD

**Issue by Koxiaet** [rust-lang/rust#80731]
Currently Rust requires that `T: 'a` in order for `&'a T` to be a valid type. However, I don't think this restriction is technically necessary - it can be enforced at creation instead of in the type itself. [Here is an example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=f977d6bd76f837b374ab77af6165389b) of code that doesn't compile because of this restriction (and [GATs are also affected by this](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=3761dfc0457a0dee9fc8564bd272533d)). That playground also contains a compiling version that works by erasing the types, which is especially silly because they do the exact same thing internally. I've run into this several times in the past and would love to see it fixed.

**Comment by jyn514** [comment]
I think this would probably need an RFC.

**Comment by Koxiaet** [comment]
Nevermind, I found a different solution to the problem making this change unnecessary. The solution was add `where Self: 'a` to the trait bound.
