### ISSUE TITLE
rustdoc renders stability attribute for trait implementations on type pages, but not trait pages

### ISSUE THREAD

**Issue by jplatte** [rust-lang/rust#80777]
For example, `impl BitOr<NonZeroU128> for NonZeroU128` being stable since 1.45.0 is visible [on the page for `NonZeroU128`](https://doc.rust-lang.org/core/num/struct.NonZeroU128.html#impl-BitOr%3CNonZeroU128%3E):

![Screenshot_2021-01-07 core num NonZeroU128 - Rust](https://user-images.githubusercontent.com/951129/103884049-52f9da80-50de-11eb-8775-f39f2795b010.png)

but not [on the page for `BitOr`](https://doc.rust-lang.org/core/ops/trait.BitOr.html#impl-BitOr%3CNonZeroU128%3E):

![Screenshot_2021-01-07 core ops BitOr - Rust](https://user-images.githubusercontent.com/951129/103884068-57be8e80-50de-11eb-817d-8444c146abf0.png)

(also the latter doesn't have `BitOr` linkified while the former has `NonZeroU128` linkified, but self-links seem less important)

**Comment by jyn514** [comment]
> (also the latter doesn't have BitOr linkified while the former has NonZeroU128 linkified, but self-links seem less important)

I would guess the same bug is causing both issue.

**Comment by LeSeulArtichaut** [comment]
I'll try to investigate and see if I can find something interesting :)

**Comment by LeSeulArtichaut** [comment]
MCVE:

```rust
#![feature(staged_api)]

pub trait Foo {}

pub struct Bar;

#[stable(feature = "foobar", since = "1.0.0")]
impl Foo for Bar {}
```

**Comment by LeSeulArtichaut** [comment]
> > (also the latter doesn't have BitOr linkified while the former has NonZeroU128 linkified, but self-links seem less important)
> 
> I would guess the same bug is causing both issues.

Not self-linking seems to be expected behavior, this was made in #32558 back in 2016. What is inconsistent however is that "Implementations on Foreign Types" do self-link.
