### ISSUE TITLE
--remap-path-prefix not remapping out_dir in debug info on Wasm

### ISSUE THREAD

**Issue by alecmocatta** [rust-lang/rust#80776]
I'm seeing an un-remapped path in a Wasm bin compiled with `--target=wasm32-unknown-unknown` `--release` `debug = 1` `--remap-path-prefix=$CARGO_MANIFEST_DIR=` on `nightly-2021-01-02`. Here's a snippet of it and a couple of preceding strings that help contextualise:

```
\0clang LLVM (rustc version 1.51.0-nightly (17eec1433 2021-01-01))\0frontend/src/lib.rs\0/Users/alec/Documents/frontend/target/wasm32-unknown-unknown/release/deps\0
```

It looks like it's the out_dir that's not getting remapped: https://github.com/rust-lang/rust/blob/dfdfaa1f0442dac516ba87d274d832c00464b3c2/compiler/rustc_codegen_llvm/src/debuginfo/metadata.rs#L970-L1109

**Comment by nagisa** [comment]
Are you passing `$CARGO_MANIFEST_DIR` as an argument verbatim (that probably won't work, rustc won't expand arguments)? Can you post the arguments that the invocation of rustc receives?

(Doing so may involve suspending the execution of rustc and then obtaining the CLI through operating system; e.g. on Linux via `cat /proc/<PID>/cmdline`)

**Comment by alecmocatta** [comment]
<details><summary><code>RUSTFLAGS='--remap-path-prefix=/Users/alec/Documents/frontend= --remap-path-prefix=/Users/alec/.rustup/toolchains/nightly-x86_64-apple-darwin= --remap-path-prefix=/Users/alec/.cargo/registry/src='</code>:</summary>

`rustc --crate-name frontend --edition=2018 frontend/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type cdylib --emit=dep-info,link -C opt-level=3 -C panic=abort -C embed-bitcode=no -C debuginfo=1 -C overflow-checks=on -C metadata=d690439610fd46ff --out-dir /Users/alec/Documents/frontend/target/wasm32-unknown-unknown/release/deps --target wasm32-unknown-unknown -L dependency=/Users/alec/Documents/frontend/target/wasm32-unknown-unknown/release/deps -L dependency=/Users/alec/Documents/frontend/target/release/deps --extern 'noprelude:alloc=/Users/alec/Documents/frontend/target/wasm32-unknown-unknown/release/deps/liballoc-21064f837a6ce201.rlib' --extern base64=/Users/alec/Documents/frontend/target/wasm32-unknown-unknown/release/deps/libbase64-d1417908bb5c991a.rlib --extern borsh=/Users/alec/Documents/frontend/target/wasm32-unknown-unknown/release/deps/libborsh-3a9a2179b6181e6f.rlib --extern bytesize=/Users/alec/Documents/frontend/target/wasm32-unknown-unknown/release/deps/libbytesize-ff41001dae3d81ae.rlib --extern common=/Users/alec/Documents/frontend/target/wasm32-unknown-unknown/release/deps/libcommon-120bd5d92e90e191.rlib --extern 'noprelude:compiler_builtins=/Users/alec/Documents/frontend/target/wasm32-unknown-unknown/release/deps/libcompiler_builtins-cc4855d60cdc44b7.rlib' --extern 'noprelude:core=/Users/alec/Documents/frontend/target/wasm32-unknown-unknown/release/deps/libcore-4ca9d146743d88a5.rlib' --extern derive_new=/Users/alec/Documents/frontend/target/release/deps/libderive_new-0a543881a2243fda.dylib --extern either=/Users/alec/Documents/frontend/target/wasm32-unknown-unknown/release/deps/libeither-cda7cc04043eb3d8.rlib --extern futures=/Users/alec/Documents/frontend/target/wasm32-unknown-unknown/release/deps/libfutures-7fb6fe532f8cdb65.rlib --extern futures_intrusive=/Users/alec/Documents/frontend/target/wasm32-unknown-unknown/release/deps/libfutures_intrusive-ec48330797918ba3.rlib --extern instant=/Users/alec/Documents/frontend/target/wasm32-unknown-unknown/release/deps/libinstant-8208dddaac005592.rlib --extern js_sys=/Users/alec/Documents/frontend/target/wasm32-unknown-unknown/release/deps/libjs_sys-000cf2ac132253e4.rlib --extern maplit=/Users/alec/Documents/frontend/target/wasm32-unknown-unknown/release/deps/libmaplit-69a523e37d42b692.rlib --extern num=/Users/alec/Documents/frontend/target/wasm32-unknown-unknown/release/deps/libnum-f3858087148fee1b.rlib --extern 'noprelude:panic_abort=/Users/alec/Documents/frontend/target/wasm32-unknown-unknown/release/deps/libpanic_abort-6540aba0ce5a9639.rlib' --extern 'noprelude:panic_unwind=/Users/alec/Documents/frontend/target/wasm32-unknown-unknown/release/deps/libpanic_unwind-72b206be10100e2c.rlib' --extern pin_cell=/Users/alec/Documents/frontend/target/wasm32-unknown-unknown/release/deps/libpin_cell-a19be411f419a79a.rlib --extern pin_project=/Users/alec/Documents/frontend/target/wasm32-unknown-unknown/release/deps/libpin_project-88db610adffc8c4d.rlib --extern pin_weak=/Users/alec/Documents/frontend/target/wasm32-unknown-unknown/release/deps/libpin_weak-a31cc3784bfeaa2a.rlib --extern 'noprelude:proc_macro=/Users/alec/Documents/frontend/target/wasm32-unknown-unknown/release/deps/libproc_macro-4786600990539276.rlib' --extern pulldown_cmark=/Users/alec/Documents/frontend/target/wasm32-unknown-unknown/release/deps/libpulldown_cmark-b92e78ac485ec452.rlib --extern replace_with=/Users/alec/Documents/frontend/target/wasm32-unknown-unknown/release/deps/libreplace_with-2ef477612fd10f0d.rlib --extern 'noprelude:std=/Users/alec/Documents/frontend/target/wasm32-unknown-unknown/release/deps/libstd-ead026bacacd2c67.rlib' --extern wasm_bindgen=/Users/alec/Documents/frontend/target/wasm32-unknown-unknown/release/deps/libwasm_bindgen-7ae4d872bfb78bb4.rlib --extern wasm_bindgen_futures=/Users/alec/Documents/frontend/target/wasm32-unknown-unknown/release/deps/libwasm_bindgen_futures-f94a2d9aa3aa1b5b.rlib --extern wasm_timer=/Users/alec/Documents/frontend/target/wasm32-unknown-unknown/release/deps/libwasm_timer-33965abb275568e6.rlib --extern web_sys=/Users/alec/Documents/frontend/target/wasm32-unknown-unknown/release/deps/libweb_sys-827dafb5b53a5b12.rlib -Z unstable-options --remap-path-prefix=/Users/alec/Documents/frontend= --remap-path-prefix=/Users/alec/.rustup/toolchains/nightly-x86_64-apple-darwin= --remap-path-prefix=/Users/alec/.cargo/registry/src=`

</details>


 All other paths are successfully remapped so I'm not sure it's related to the argument getting to rustc? It's literally just `/Users/alec/Documents/frontend/target/wasm32-unknown-unknown/release/deps` that is not remapped.

**Comment by nagisa** [comment]
Yeah, I just wanted to make sure it is not something obviously wrong with how arguments get to rustc, especially as you mentioned use of environment variables, that are typically set inside cargo.

**Comment by nagisa** [comment]
This might be fixed by https://github.com/rust-lang/rust/pull/82102 as well.

**Comment by jyn514** [comment]
https://github.com/rust-lang/rust/pull/82102 was merged, are you still running into this?

**Comment by alecmocatta** [comment]
Confirmed I'm no longer seeing this bug. Thanks both, closing!
