### ISSUE TITLE
Add 'language' tag to repo

### ISSUE THREAD

**Issue by clmay** [rust-lang/rust#80770]
It would be great to see Rust represented in the [Languages topic](https://github.com/topics/language). My understanding is that this can be accomplished trivially by adding the tag `language` to the repo's tags.

Sorry for opening an issue for this. I just get sad every time I am browsing topics and don't see Rust listed in the Languages topic. I think it deserves to be showcased as one of the top langs which have their development hosted on GitHub.

**Comment by lzutao** [comment]
That maybe useful. Do you know how could we do that in our side?

**Comment by jplatte** [comment]
Sbd. with owner permission has to do it AFAIK.

**Comment by lzutao** [comment]
So you mean add topic tags just like golang repo:
![image](https://user-images.githubusercontent.com/15225902/103901857-48663200-512c-11eb-9744-851e4010e543.png)

**Comment by jplatte** [comment]
I think that's what OP meant, yes. Rust has two of those too right no: `rust` and `compiler`.

**Comment by clmay** [comment]
Yes, that's exactly what I mean, and yes, someone with access to repo settings must make the change.

**Comment by lzutao** [comment]
cc @Mark-Simulacrum if this issue would slip from the core team's eyes.

**Comment by Mark-Simulacrum** [comment]
Done. I don't think we want to add all the tags that might possibly apply (seems unclear as to why it's good), but this seems fine.
