### ISSUE TITLE
Types pass through generic functions in 1.49 on

### ISSUE THREAD

**Issue by chrysn** [rust-lang/rust#80821]
The following code compiles in 1.49 and newer (tested1.49 and two recent nightlies) but does not in 1.48 or older (easily testable with [godbolt](https://gcc.godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(fontScale:14,j:1,lang:rust,selection:(endColumn:1,endLineNumber:22,positionColumn:1,positionLineNumber:22,selectionStartColumn:1,selectionStartLineNumber:22,startColumn:1,startLineNumber:22),source:'fn+x%3CA,+E%3E(_a:+A)+-%3E+Result%3C(),+E%3E%0Awhere%0A+++A:+T%3CE+%3D+E%3E%0A%7B%0A++++Ok(())%0A%7D%0A%0Astruct+X%3B%0A%0Atrait+T+%7B%0A++++type+E:+core::fmt::Debug%3B%0A%7D%0A%0Aimpl+T+for+X+%7B%0A++++type+E+%3D+()%3B%0A%7D%0A%0Apub+fn+main()+%7B%0A++++let+a+%3D+X%3B%0A++++%0A++++x(a).expect(%22Practically+it+will+work,+but+how+might+it+fail%3F%22)%3B%0A%7D'),l:'5',n:'0',o:'Rust+source+%231',t:'0')),k:53.846153846153854,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:r1480,filters:(b:'0',binary:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'1'),fontScale:14,j:1,lang:rust,libs:!(),options:'',selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:1),l:'5',n:'0',o:'rustc+1.48.0+(Editor+%231,+Compiler+%231)+Rust',t:'0')),k:12.820512820512821,l:'4',n:'0',o:'',s:0,t:'0'),(g:!((h:output,i:(compiler:1,editor:1,fontScale:14,wrap:'1'),l:'5',n:'0',o:'%231+with+rustc+1.48.0',t:'0')),k:33.33333333333333,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4))

```rust
fn x<A, E>(_a: A) -> Result<(), E>
where
   A: T<E = E>
{
    Ok(())
}

struct X;

trait T {
    type E: core::fmt::Debug;
}

impl T for X {
    type E = ();
}

pub fn main() {
    let a = X;
    
    x(a).expect("Practically it will work, but how might it fail?");
}
```

with older versions giving "`E` doesn't implement `Debug`". It seems that in 1.49, the concrete E used as a consequence of how the X in a implements T is inferred by this version and used to satisfy the `expect`'s requirement of implementing `Debug`.

I've gone through the change logs between 1.48 and 1.49, and nothing there hints at such behavior. If the change is unintentional, it should be known as a bug (because it'd produce regressions once it's flipped back). If it is intentional, it should be documented in the change log (can that be amended later on?) to make users with a keen eye for MSRVs aware it's there and compatibility with older versions can suffer (or I should get better at reading change logs).

**Comment by Aaron1011** [comment]
I think this is related to https://github.com/rust-lang/rust/issues/78893

**Comment by chrysn** [comment]
I had discarded that possibility when I saw that it happened after
1.48.0-beta.8, but looking at the dates now, it might easily just have
been the latest version at that point and they may indeed coincide.

**Comment by chrysn** [comment]
Closing as duplicate, see also https://github.com/rust-lang/rust/issues/78893#issuecomment-757111216
