### ISSUE TITLE
E0121 suggests the use of the unique type of a generator

### ISSUE THREAD

**Issue by PatchMixolydic** [rust-lang/rust#80844]
cc #80179

This still fails on generators ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=7ac611ca1bd560116d4b9a804817ad20)):

```rust
#![feature(generators)]

fn foo() -> _ {
    || yield 4i32
}
```

```
error[E0121]: the type placeholder `_` is not allowed within types on item signatures
 --> src/lib.rs:3:13
  |
3 | fn foo() -> _ {
  |             ^
  |             |
  |             not allowed in type signatures
  |             help: replace with the correct return type: [generator@src/lib.rs:4:5: 4:18 {i32, ()}]
```

Tested on:
```
cargo 1.50.0-nightly (75d5d8cff 2020-12-22)
release: 1.50.0
commit-hash: 75d5d8cffe3464631f82dcd3c470b78dc1dda8bb
commit-date: 2020-12-22
```

I'm working on a PR to fix this as well as making this suggestion and E0308's `try adding a return type` suggestion use the same mechanism for checking if a type is suggestable directly.

@rustbot claim
@rustbot modify labels: +A-diagnostics +D-invalid-suggestion +F-generators +T-compiler

**Comment by camelid** [comment]
@PatchMixolydic By the way, you don't need to open an issue if you're immediately going to open a PR.

**Comment by PatchMixolydic** [comment]
My mistake :sweat_smile:

**Comment by camelid** [comment]
Don't worry about it! It's not a problem; I was just letting you know that you shouldn't feel obliged to do it :)

**Comment by PatchMixolydic** [comment]
Status update: I'm not certain I'm the right person for the job due to my warped schedule, among other things. You can find the progress I made at #80847, but note that a rebase caused important tests to fail. These might be usable as a basis for a new PR, but they're probably useless directly. I might come back to this when I have more time/control over my life.

@rustbot release assignment

**Comment by compiler-errors** [comment]
This seems to be resolved on nightly.
