### ISSUE TITLE
core::panic!() cannot be used everywhere std::panic!() can.

### ISSUE THREAD

**Issue by m-ou-se** [rust-lang/rust#80846]
This compiles:

```rust
fn main() {
    let x = &5;
    x = &std::panic!()
}
```

This does not:

```rust
fn main() {
    let x = &5;
    x = &core::panic!()
}
```
```
error[E0308]: mismatched types
 --> src/main.rs:3:9
  |
3 |     x = &core::panic!()
  |         ^^^^^^^^^^^^^^^ expected integer, found `!`
  |
  = note: expected reference `&{integer}`
             found reference `&!`
```

The cause seems to be that `std::panic!()` expands to `{ some_function(..) }` while `core::panic!()` expands to `some_function(..)`, without `{ .. }`. Adding `{ .. }` in the `core::panic!()` `macro_rules` 'fixes' it.

**Comment by m-ou-se** [comment]
#80848 is an attempt at fixing this, by adding `{ .. }` in the `macro_rules! panic` in `core`.

But as mentioned in https://github.com/rust-lang/rust/pull/80848#issuecomment-757348656, the braces were not added in `std::panic!()` for this purpose, and seem to be left there by accident.

Is this a bug? Should this behave the same with and without those braces?

**Comment by eddyb** [comment]
The never type never ceases to surprise, does it? cc @nikomatsakis

I'd be worried about changing typeck behavior here, personally, I'm not even sure it would survive crater, and could have subtler implications still. Adding the braces to `core::panic!` should be fine.

**Comment by bstrie** [comment]
I see that https://github.com/rust-lang/rust/issues/80162, which listed this issue as a blocker, has been closed. Does that mean this can be closed too?

**Comment by m-ou-se** [comment]
For that PR we decided to just change it for edition 2021, but this problem still exists in the current editions. It's not a big problem, but it'd be good to figure out why this difference exists.

**Comment by m-ou-se** [comment]
Closing this issue because I don't care enough, especially since this problem is no longer there in edition 2021.

If anyone does care about this issue in edition 2015/2018, feel free to re-open.
