### ISSUE TITLE
"call expression requires function" error points to wrong definition

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#80853]
```rust
struct S;

fn repro_ref(thing: S) {
    thing();
}
```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=3a0a4eb8cb5c7c139b4637c2df4febf1))

It should either point to the definition of `S` or it should say "`thing` defined here":

```
   Compiling playground v0.0.1 (/playground)
error[E0618]: expected function, found `S`
 --> src/lib.rs:4:5
  |
3 | fn repro_ref(thing: S) {
  |              ----- `S` defined here
4 |     thing();
  |     ^^^^^--
  |     |
  |     call expression requires function

error: aborting due to previous error

For more information about this error, try `rustc --explain E0618`.
error: could not compile `playground`

To learn more, run the command again with --verbose.
```

**Comment by camelid** [comment]
Relevant code:

https://github.com/rust-lang/rust/blob/ef589490a709984d3be80c9b59a1a10a4dd05e3c/compiler/rustc_typeck/src/check/callee.rs#L335-L383

**Comment by henryboisdequin** [comment]
Would it be helpful if the compiler said `expected function, found struct S` and then emitted a note which said `S` is not a function in this case?

**Comment by camelid** [comment]
Perhaps, but the bug this issue is about is this:

```
3 | fn repro_ref(thing: S) {
  |              ----- `S` defined here
```

It says "`S` defined here", but actually it's *`thing`* that's defined there. Instead it should point to the definition of `S`.

**Comment by henryboisdequin** [comment]
@camelid I've been working on this for a bit and don't really know how to approach it. Since the code is calling `thing` as a function, an error happens. The definition of `thing` is as an argument to `repro_ref`. Would I need to detect whether it's an argument and then, if so, finding the root definition, or is there a better way to do this?

**Comment by camelid** [comment]
@henryboisdequin 

> Would I need to detect whether it's an argument and then, if so, finding the root definition, or is there a better way to do this?

I thought about this a bit more and realized that my original suggestion of pointing to the definition of the struct `S` is probably not that helpful and would not generalize. Probably a good approach is to:

- Do you what you suggested in https://github.com/rust-lang/rust/issues/80853#issuecomment-776359333
- Fix the note so it says "`thing` defined here" instead of "`S` defined here"

I am not super familiar with the type-checker, but I can try to help you with what knowledge I have. You can also ask on Zulip if you need more help.
