### ISSUE TITLE
is there a way to disable seeing warnings if there are errors blocking compilation?

### ISSUE THREAD

**Issue by alok** [rust-lang/rust#80863]
most of the time, if i have compile error(s), i want to see only that error. warnings take up my attention needlessly.

could this be a command line flag or an option to how error format is set now?

**Comment by gyfis** [comment]
@alok it seems using `RUSTFLAGS=-Awarnings` with `cargo build` hides warnings. Not conditionally, and it [leads to recompile](https://users.rust-lang.org/t/suppress-warnings-from-the-cargo-command/10536/2) it seems, but maybe that's enough for you.

**Comment by jyn514** [comment]
You could also use `cargo rustc -- -Awarnings` which doesn't recompile, but can only build one crate.

**Comment by alok** [comment]
i’m actually looking for the conditional behavior since it automates a common workflow: first make it work (no errors), then make it work well (no warnings).

**Comment by jyn514** [comment]
@alok you may be interested in https://github.com/Canop/bacon/

**Comment by rcolomina** [comment]
`RUSTFLAGS=-Awarnings` flag works for me removing all the warnings. I am most interested on errors rather than warnings.  When you provide this a flag, all cranes are re-complied.

**Comment by blueForestIcarus** [comment]
Whether or not warnings are printed should have nothing to do with whether you need to recompile smh

**Comment by SamB** [comment]
You don't think that you might end up missing out on warning messages that actually explain the circumstances that lead to the error? Say, a warning on a likely-problematic declaration and an error on the attempt to use whatever was declared?

**Comment by Dylan-DPC** [comment]
Closing this as i'm not sure there's much to be done here in a way that doesn't have concerns  and there are alternatives present as listed above.
