### ISSUE TITLE
implementing From<AsRef<LocalStruct>> for a foreign type

### ISSUE THREAD

**Issue by vjancik** [rust-lang/rust#80877]
I tried this code:

```rust
impl<T: AsRef<Header>> From<T> for [u8; 20] {
    fn from(header: T) -> [u8; 20] {
        let mut buf = [0u8; 20];
        unimplemented!();
    }
}
```
where `Header` is a local struct.

I expected to see this happen:
It should work in Rust 1.41+

Instead, this happened: 
```
type parameter `T` must be used as the type parameter for some local type (e.g., `MyStruct<T>`)

type parameter `T` must be used as the type parameter for some local type

note: implementing a foreign trait is only possible if at least one of the types for which it is implemented is local
note: only traits defined in the current crate can be implemented for a type parameter
```

**Expectation:**

`T: AsRef<Header>` should be considered a local type because it's trait specification is relying on a local type.
The alternative is having to use `.into()` for types that implement `Into<&Header>`

Unless I shouldn't use `AsRef` in the first place?

It also forces me to write
```rust
let buf: [u8; 20] = (&header).into();
```
instead of
```rust
let buf: [u8; 20] = header.into();
```
assuming a `From<&Header>` implementation.

### Meta

`rustc --version --verbose`:
```
rustc 1.51.0-nightly (6184f2395 2021-01-09)
binary: rustc
commit-hash: 6184f23950fb4aa14884ce310d948dc6fca269a3
commit-date: 2021-01-09
host: x86_64-unknown-linux-gnu
release: 1.51.0-nightly
```

**Comment by SkiFire13** [comment]
The problem with allowing this implementations is that implementing traits for [u8; 20] becomes a breaking change. Yes, you know the stdlib won't `impl<T> From<T> for [u8; 20]`, however you can't say the same thing for other libraries, and this rule has to be universal.

I don't think there's a way to do this with `AsRef`, you're better off just writing `impl From<&Header> for [u8; 20]`

**Comment by vjancik** [comment]
No they couldn't (the other libraries), for the same reason I can't implement `From<ForeignStruct> for ForeignStruct`.

But it should be possible to allow "foreign trait restricted" type implementations, as long as those traits are "local type specified". That way you can guarantee a downstream library won't implement a foreign trait on an upstream type.

**Comment by vjancik** [comment]
Specifically:
`impl ForeignTrait<LocalType> for ForeignStruct` is non-breaking and works from Rust 1.41+ and 
` impl<T: ForeignTrait<LocalType> ForeignTrait<T> for ForeignStruct` falls into the same category, just with an extra layer of indirection. It should also be non-breaking...

Am I missing anything?

**Comment by dylni** [comment]
This is annoying, but another crate could have a similar impl:

```rust
impl<T: AsRef<Header2>> From<T> for [u8; 20] {
    fn from(header2: T) -> [u8; 20] {
        let mut buf = [0u8; 20];
        unimplemented!();
    }
}
```

where `Header2` is a local struct and `String` implements `AsRef<Header>` and `AsRef<Header2>`. The compiler wouldn't know which to use.

**Comment by jonas-schievink** [comment]
Closing as expected behavior
