### ISSUE TITLE
 Is there an official semaphore api?

### ISSUE THREAD

**Issue by hongliang5316** [rust-lang/rust#80903]
I found one, but I found it is not too mature
https://docs.rs/semaphore/0.4.0/semaphore/

**Comment by jonas-schievink** [comment]
Hi! This issue tracker is mainly meant for bug reports and concrete, small feature requests. Questions like this are better asked in the user forum at https://users.rust-lang.org/ or on [one of the chat platforms](https://www.rust-lang.org/community) used by the Rust community.
