### ISSUE TITLE
Use `atty` crate in libtest instead of rolling our own

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#80937]
cc #80888
cc @jyn514

This issue has been assigned to @mattwilkinsonn via [this comment](https://github.com/rust-lang/rust/issues/80937#issuecomment-1079303047).

**Comment by jyn514** [comment]
@camelid what happened to https://github.com/rust-lang/rust/pull/42732#discussion_r125191880 ?

**Comment by nagisa** [comment]
winapi has since been improved to no longer imply long build times at the very least.

**Comment by camelid** [comment]
But I think we should probably use `atty` since it's so widely used.

**Comment by artorias111** [comment]
Hey! Is this a good issue if I'm just getting used to contribute to various projects. Not really familiar with the rust codebase but would like to try if I can contribute.

**Comment by jyn514** [comment]
@artorias111 yes, this would be a good first issue I think. I'm not 100% convinced we should make the change, but the implementation is easy, just add `atty` as a dependency and use it in libtest: https://github.com/rust-lang/rust/pull/80897#discussion_r554689224

**Comment by artorias111** [comment]
@jyn514 sure, I'll give it a try then

**Comment by vramana** [comment]
@diohabara Are you still interested to work on this? Or can I claim it?

**Comment by jyn514** [comment]
https://github.com/rust-lang/rust/pull/91121 is making good progress; I don't think it makes sense to duplicate work.

**Comment by joshtriplett** [comment]
https://github.com/rust-lang/rust/pull/98033 just merged.

**Comment by saethlin** [comment]
@joshtriplett Should this have been closed by https://github.com/rust-lang/rust/pull/98033?

**Comment by ChrisDenton** [comment]
I believe so.
