### ISSUE TITLE
Rename `doc(spotlight)` to `doc(notable_trait)`

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#80936]
Leaving this as a todo for myself:

We should probably rename this flag to `notable_trait` since (a) it's clearer and (b) that's what the popup that it triggers is called. We should probably do it in another PR though; I'll try to do that soon.

_Originally posted by @camelid in https://github.com/rust-lang/rust/pull/80914#discussion_r555491002_

@rustbot claim

**Comment by jyn514** [comment]
This is a user-facing change. I know doc(spotlight) is nightly only, but is the improvement worth it? I think `spotlight` is reasonably clear.

cc @Manishearth

**Comment by camelid** [comment]
I don't think it's that clear of a name. "spotlight" could mean many things, but `doc(spotlight)` means a very specific thing. For example, I could imagine "spotlight" meaning that rustdoc puts it at the top of the module page and highlights it.

**Comment by GuillaumeGomez** [comment]
Also cc @Manishearth

**Comment by Manishearth** [comment]
Yeah, I feel like we should call it `notable_trait` or something since most users won't know the name "spotlight".
