### ISSUE TITLE
regression 1.50: Code breaks due to newly stabalized std lib methods `Ord::clamp` and `bool::then`

### ISSUE THREAD

**Issue by rylev** [rust-lang/rust#80950]
Two newly stabalized APIs (`Ord::clamp` and `bool::then`) caused regressions in crates due to their stabalization in the [latest crater run](https://crater-reports.s3.amazonaws.com/beta-1.50-1/index.html). In total 4 crates were impacted by this. 

This is likely to be closed with `wont-fix`, but I wanted to ensure it was noted somewhere. 

@rustbot modify labels: +regression-from-stable-to-beta

**Comment by apiraino** [comment]
Issue has been mentioned and noted in the latest crater run, so it will tracked there.

**Comment by scottmcm** [comment]
`clamp` is almost certainly `wont-fix` as being expected -- `Ord::clamp` was [backed out back in 2017](https://github.com/rust-lang/rust/pull/44438) for breakage, so it finally stabilizing now seems like acceptance of this (allowed) breakage.

**Comment by Mark-Simulacrum** [comment]
Closing as expected and acceptable breakage.
