### ISSUE TITLE
Missed optimization: computing smaller index than length does not elliminate bound check

### ISSUE THREAD

**Issue by newpavlov** [rust-lang/rust#80963]
Code:
```rust
pub fn foo(buf: &[u8]) -> Option<&[u8]> {
    // guard against potential overflow
    if buf.len() > usize::MAX/3 {
        return None;
    }
    let n = (3*buf.len())/4;
    Some(&buf[..n])
}
```
[godbolt](https://rust.godbolt.org/z/Grvvs3)

Even replacing `usize::MAX/3` with any non-zero small number (even 1) does not result in removal of the bound check.

This behavior can be reproduced on current Nightly and previous stable compiler versions.

**Comment by the8472** [comment]
Workaround:


```rust
pub fn foo(buf: &[u8]) -> Option<&[u8]> {
    if buf.len() > usize::MAX/3 {
        return None;
    }
    let n = (3*buf.len())/4;
    let n = std::cmp::min(n, buf.len());
    Some(&buf[..n])
}
```

**Comment by nikic** [comment]
https://bugs.llvm.org/show_bug.cgi?id=48744

**Comment by nikic** [comment]
Upstream fix: https://github.com/llvm/llvm-project/commit/a13c0f62c38131ef2656b06de02d82110abaf272

**Comment by MSxDOS** [comment]
Fixed on the latest nightly by https://github.com/rust-lang/rust/pull/81451

**Comment by newpavlov** [comment]
I confirm the fix.
