### ISSUE TITLE
ICE in github build

### ISSUE THREAD

**Issue by xoviat** [rust-lang/rust#80998]
See below:

https://github.com/akiles/embassy/runs/1699580405?check_suite_focus=true

**Comment by hellow554** [comment]
Reduced to only use the task proc-macro:

```
use embassy::executor::task;

#[task]
async fn run() {
    let a = Foo ;
}
```

It seems important, that Foo isn't defined, if I define a `struct Foo`, the ICE goes away.

**Comment by hellow554** [comment]
searched nightlies: from nightly-2020-06-01 to nightly-2021-01-01
regressed nightly: nightly-2020-10-27
searched commits: from https://github.com/rust-lang/rust/commit/4760b8fb886a3702ae11bfa7868d495b2675b5ed to https://github.com/rust-lang/rust/commit/fd542592f08ca0d1f7255600115c2eafdf6b5da7
regressed commit: https://github.com/rust-lang/rust/commit/b9a94c919b8cb09c186ff253360df91f223f6ef3

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.0</summary>


Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc 2020-06-01 --regress ice --access github -- check
```
</details>

---

I'm pretty sure that #78324 isn't at fault here, but instead it just uncovers the problem.

**Comment by hellow554** [comment]
MCVE:

```
#![feature(type_alias_impl_trait)]

use std::future::Future;

pub struct Task<F: Future>(F);
impl<F: Future> Task<F> {
    fn new() -> Self {
        todo!()
    }
    fn spawn(&self, _: impl FnOnce() -> F) {
        todo!()
    }
}

fn main() {
    async fn cb() {
        let a = Foo;
    }

    type F = impl Future;
    static POOL: Task<F> = Task::new();
    Task::spawn(&POOL, || cb());
}
```

**Comment by jonas-schievink** [comment]
Panic location:

https://github.com/rust-lang/rust/blob/a4f022e1099c712fdcc8555fd10caccb1a631877/compiler/rustc_middle/src/ty/mod.rs#L3071-L3073
