### ISSUE TITLE
flatten() breaks size_hint()

### ISSUE THREAD

**Issue by cargodog** [rust-lang/rust#81001]
Using the `flatten()` iterator adapter, causes broken size hints. Consider the following small example:
```
// Construct a simple nested iterator: 10 x 10
let t = (0..10).map(|_| (0..10));

// Flatten and get its size hint
println!("flat_size_hint = {:?}", t.flatten().size_hint());
```
I expected to see:
```
flat_size_hint = (100, Some(100))
```

Instead, I see:
```
flat_size_hint = (0, None)
```

My Rust version is:
```
$ rustup -V
rustup 1.23.1 (3df2264a9 2020-11-30)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.48.0 (7eac88abb 2020-11-16)`
```

**Comment by cargodog** [comment]
I believe the error is in this impl: https://github.com/rust-lang/rust/blob/c7b0ddbffebee1cb06f184e815ca637706c53053/library/core/src/iter/adapters/flatten.rs#L275

**Comment by taiki-e** [comment]
I think this is working as intended. `flatten` cannot know the actual size until the closure is actually executed.

**Comment by hellow554** [comment]
But isn't it at least as long as the old iterator, e.g. `flatten` can't remove elements, it just can add more? So a lower limit should be possible, which would help.

**Comment by PatchMixolydic** [comment]
`iter::Flatten` seems to be a general wrapper produced by `Iterator::flatten`. Since [it appears that the return type of `Iterator::flatten` is fixed][flat], I'm not sure if accurate size hints could be provided in the case of a slice.

[flat]: https://github.com/rust-lang/rust/blob/0506789014f9aef9ffac7d7d1e22fa72c7b85ab7/library/core/src/iter/traits/iterator.rs#L1374-L1382

Also, just a tiny nitpick:

> Using the flatten() iterator adapter, causes broken size hints.

The size hints aren't really broken; they're just unhelpful. `(0, None)` fits [the definition of a valid `size_hint`][size_hint]: an iterator produced by `Iterator::flatten` will have at least zero elements and may be infinite.

[size_hint]: https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.size_hint

**Comment by jonas-schievink** [comment]
What's the intended behavior of that `size_hint` impl? It seems like it's estimating the number of total iterators it will flatten, which doesn't really relate to the number of elements. Should it be removed instead?

**Comment by cargodog** [comment]
> `iter::Flatten` seems to be a general wrapper produced by `Iterator::flatten`. Since [it appears that the return type of `Iterator::flatten` is fixed](https://github.com/rust-lang/rust/blob/0506789014f9aef9ffac7d7d1e22fa72c7b85ab7/library/core/src/iter/traits/iterator.rs#L1374-L1382), I'm not sure if accurate size hints could be provided in the case of a slice.
> 
> Also, just a tiny nitpick:
> 
> > Using the flatten() iterator adapter, causes broken size hints.
> 
> The size hints aren't really broken; they're just unhelpful. `(0, None)` fits [the definition of a valid `size_hint` result](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.size_hint): an iterator produced by `Iterator::flatten` will have at least zero elements and may be infinite.

Sure, its not technically broken, but I would expect a precise result in this case.

Looking at [this](https://github.com/rust-lang/rust/blob/c7b0ddbffebee1cb06f184e815ca637706c53053/library/core/src/iter/adapters/flatten.rs#L275) implementation, I believe the intent was for `size_hint()` to return the sum of minimum and sum of maximum sizes recursively for the iterators in the `Flatten` struct, but there is an odd requirement that the initial state is `(0, Some(0))` which I think causes the `match` to always fail.

I see no reason why a case like this (a simple exact sized iterator, nested within another simple exact sized iterator) cannot be precisely given by `size_hint()`.

**Comment by cargodog** [comment]
> I think this is working as intended. `flatten` cannot know the actual size until the closure is actually executed.

I think you may be right. I forgot that the `map()` adapter depends on a closure, which indeed cannot be known before execution. Thanks for your reply.
