### ISSUE TITLE
partialOrd

### ISSUE THREAD

**Issue by tj-yazman** [rust-lang/rust#81010]
```rust
//use std::cmp::PartialOrd;
fn largest<T :std::cmp::PartialOrd>(list: &[T]) -> &T {
    let mut largest = &list[0];

    for item in list {
        if item > largest {
            largest = item;
        }
    }

    largest
}

fn main() {
    let number_list = vec![34, 50, 25, 100, 65];

    let result = largest(&number_list);
    println!("The largest number is {}", result);

    let char_list = vec!['y', 'm', 'a', 'q'];

    let result = largest(&char_list);
    println!("The largest char is {}", result);
}
```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=e752f8f7b1fd256a9ddf1ed61ea50c8c))

Output:

```
The largest number is 100
The largest char is y

```

Errors:

```
   Compiling playground v0.0.1 (/playground)
    Finished dev [unoptimized + debuginfo] target(s) in 1.19s
     Running `target/debug/playground`

```

**Comment by rylev** [comment]
@tj-yazman Can you please describe the error you're seeing in more detail. This code looks correct to me.

**Comment by nagisa** [comment]
Code seems to be broadly copied from https://doc.rust-lang.org/book/ch10-02-traits.html#fixing-the-largest-function-with-trait-bounds and there are various signals indicating this might be a spam, similar to https://github.com/rust-lang/rust/issues/80773. Closing for now, but if the author does provide more explanation, we can reopen.
