### ISSUE TITLE
x.py build: error: XZ support is required to download LLVM

### ISSUE THREAD

**Issue by Walther** [rust-lang/rust#81026]
Steps:
- Follow instructions at https://rustc-dev-guide.rust-lang.org/getting-started.html
- `git clone https://github.com/rust-lang/rust.git` (at commit e38fb306b7f5e65cca34df2dab1f0db15e1defb4 )
- `git submodule update --init --recursive`
- `./x.py setup`, select `b) compiler: Contribute to the compiler or rustdoc`
- `./x.py build`

```
./x.py build
Updating only changed submodules
Submodules updated in 0.14 seconds
error: XZ support is required to download LLVM
help: consider disabling `download-ci-llvm` or using python3
Build completed unsuccessfully in 0:00:00
```

Both `python` and `python3` exist
```
which python
/usr/bin/python

which python3
/usr/bin/python3
```

Note: https://github.com/rust-lang/rust/blob/e38fb306b7f5e65cca34df2dab1f0db15e1defb4/x.py#L1

```
# Running the same command defaults to python 2 on the OS
/usr/bin/env python
Python 2.7.16 (default, Oct 10 2019, 22:02:15)
[GCC 8.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
```

Environment: WSL2 Debian 10 buster

```
cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

uname -a
Linux matcha 4.4.0-19041-Microsoft #488-Microsoft Mon Sep 01 13:43:00 PST 2020 x86_64 GNU/Linux
```

Workaround:

```
python3 x.py build
```

---

Three thoughts:
- Should `x.py` be smarter about `python` vs `python3` detection & execution, to fix this without user action?
- Should the error message be improved, in a way that helps a user to work around this? (for example, "python3 detected, edit x.py to use python3 instead" or other suggestion)
- Should the contribution guide have an updated mention of `python3` requirement? Currently: "Most notably, you will need Python 2 or 3 to run x.py."

**Comment by Walther** [comment]
Additional note:

```
./x.py setup
/usr/bin/env: ‘python’: No such file or directory
```

on a server with a Ubuntu 20.04 focal fossa installation, where `python` is not even be present:
```
/usr/bin/env python
/usr/bin/env: ‘python’: No such file or directory

which python
python not found

which python3
/usr/bin/python3
```

**Comment by cuviper** [comment]
See also #71818 and #80625 -- cc @jyn514

**Comment by Walther** [comment]
Ah my bad, was searching with the full error and didn't find those two. Closing as duplicate 👍

**Comment by jyn514** [comment]
There is not a good way to fix https://github.com/rust-lang/rust/issues/71818 (see https://rust-lang.zulipchat.com/#narrow/stream/122651-general/topic/x.2Epy.20.2B.20download-ci-llvm.20-.3E.20explicit.20python3.20needed.3F/near/221414355 for more discussion). https://github.com/rust-lang/rust/pull/80625 should be merged as soon as I rebase it.

**Comment by willus10245** [comment]
I'm getting this error, even when calling `python3 ./x.py check`

**Comment by jyn514** [comment]
@willus10245 it's unlikely it's the same error - can you open a new issue with the full output of x.py?

**Comment by willus10245** [comment]
The error is identical to the original post on this issue

```
$ python3 x.py check
Updating only changed submodules
Submodules updated in 0.06 seconds
error: XZ support is required to download LLVM
help: consider disabling `download-ci-llvm` or using python3
Build completed unsuccessfully in 0:00:00
```

**Comment by willus10245** [comment]
@jyn514 do you mean the contents of `x.py`?

**Comment by willus10245** [comment]
@jyn514 opened https://github.com/rust-lang/rust/issues/85476
