### ISSUE TITLE
Windows PathBuf/Path

### ISSUE THREAD

**Issue by pderouen** [rust-lang/rust#81045]
A Path derived from a canonicalized PathBuf and then joined to another Path that includes ".\\" in the path cannot be resolved correctly (Windows os error). Removing the leading ".\\" or starting from a PathBuf that hasn't been canonicalized will allow the path to resolve correct (Windows finds the file).

I tried this code:

```rust
use std::path::{Path, PathBuf};

fn main() {
    let p0 = PathBuf::from(".\\empty_file.txt");
    let p0_canon = p0.canonicalize().unwrap();
    // using this instead will work
    // let p0_canon = PathBuf::from("c:\\full\\path\\to\\the\\file");
    if let Some(p1) = p0_canon.parent() {
        let append = Path::new(".\\target\\debug\\testfile");
        println!("{:#?}", p1);
        println!("{:#?}", append);
        let p2 = p1.join(append);
        println!("{:#?}", p2);
        let canonicalize = p2.canonicalize();
        println!("{:#?}", canonicalize);
    }
}
```

I expected to see this happen: I expect the final prinln to show Ok(<path to the file>)

Instead, this happened: I get Err. The system cannot find the path specified.

`rustc --version --verbose`:
```
rustc 1.49.0 (e1884a8e3 2020-12-29)
binary: rustc
commit-hash: e1884a8e3c3e813aada8254edfa120e85bf5ffca
commit-date: 2020-12-29
host: x86_64-pc-windows-gnu
release: 1.49.0
```

<details><summary>Backtrace</summary>
<p>

```
no back trace
```

</p>
</details>

**Comment by ehuss** [comment]
This is a fairly well known problem where `canonicalize` returns a `\\?\` device path which does not support relative paths or normalization.  See #59117 and #42869 and all the linked issues.

**Comment by pderouen** [comment]
thank you
