### ISSUE TITLE
Tracking Issue for NonZeroUn::is_power_of_two (feature nonzero_is_power_of_two)

### ISSUE THREAD

**Issue by scottmcm** [rust-lang/rust#81106]
Feature gate: `#![feature(nonzero_is_power_of_two)]`

This is a tracking issue for `NonZeroUsize::is_power_of_two` (and friends for the other unsigned types).

Like `NonZeroUsize::leading_zeros` (#79143), this generates simpler code than the underlying integer type because it can avoid a separate zero check.

### Public API

```rust
impl NonZeroUsize {
    pub fn is_power_of_two(self) -> bool;
}

// And also for NonZeroU8, NonZeroU16, ...
```

### Steps / History

- [x] Implementation: #81107
- [ ] Final commenting period (FCP)
- [ ] Stabilization PR

### Unresolved Questions

- None yet.

**Comment by raphaelcohn** [comment]
Great, something else that just breaks my code. Sigh.

**Comment by scottmcm** [comment]
With `NonZeroU##::leading_zeros` [stabilized](https://github.com/rust-lang/rust/issues/79143#issuecomment-811416368), I would like to propose [`NonZeroU##::is_power_of_two`](https://doc.rust-lang.org/nightly/std/num/struct.NonZeroU32.html#method.is_power_of_two) for stabilization as well.

(I think this in the tracking issue is the right thing to do now, rather than filing a PR?)

**Comment by joshtriplett** [comment]
@rust-lang/libs-api, shall we stabilize `NonZeroU*::is_power_of_two`?

@rfcbot merge
