### ISSUE TITLE
[docs] pointer::wrapping_sub has typo

### ISSUE THREAD

**Issue by Lokathor** [rust-lang/rust#81109]
The docs for pointer::wrapping_sub say

> Calculates the offset from a pointer using wrapping arithmetic. (convenience for .wrapping_offset((count as isize).wrapping_sub()))

but they should say `.wrapping_neg()` instead

**Comment by jyn514** [comment]
@Lokathor are you interested in making a PR to fix it?

**Comment by Lokathor** [comment]
Josh you know I don't ever dare PR to rust-lang/rust ;3

**Comment by soniasingla** [comment]
@jyn514 can i take this bug? :)

**Comment by jyn514** [comment]
Go for it! The docs for this will be somewhere in library/, you can find them by hitting `[src]` in the docs. There are instructions for building at rustc-dev-guide.rust-lang.org/, the main command is `x.py doc library/std`.
