### ISSUE TITLE
String::replace_range is unsound

### ISSUE THREAD

**Issue by xfix** [rust-lang/rust#81138]
It's possible to use `String::replace_range` to create invalid strings containing broken Unicode. This happens because `replace_range` checks range bounds twice - first time to check parameter validity and second time for actually doing the splice.

```rust
use std::cell::Cell;
use std::ops::{Bound, RangeBounds};
use std::str;

struct EvilRange(Cell<bool>);

impl RangeBounds<usize> for EvilRange {
    fn start_bound(&self) -> Bound<&usize> {
        Bound::Included(if self.0.get() {
            &1
        } else {
            self.0.set(true);
            &0
        })
    }
    fn end_bound(&self) -> Bound<&usize> {
        Bound::Unbounded
    }
}

fn main() {
    let mut s = String::from("🦀");
    s.replace_range(EvilRange(Cell::new(false)), "");
    println!("{:?}", str::from_utf8(s.as_bytes()));
}
```

This will print `Utf8Error` showing that a string is not valid UTF-8.

**Comment by rylev** [comment]
Assigning P-high as [discussed as part of the Prioritization Working Group procedure](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2381138.20String.3A.3Areplace_range.20is.20unsound) and removing I-prioritize.
