### ISSUE TITLE
Vec::drain is unsound with range_bounds_assert_len feature

### ISSUE THREAD

**Issue by xfix** [rust-lang/rust#81157]
Manually implementing `assert_len` can cause unsoundness in `Vec::drain`. This only happens in nightly, as overriding `assert_len` is only possible in nightly releases.

The following program will segfault.

```rust
#![feature(range_bounds_assert_len)]

use std::cell::Cell;
use std::ops::{Bound, Range, RangeBounds};

struct EvilRange(Cell<bool>);

impl RangeBounds<usize> for EvilRange {
    fn start_bound(&self) -> Bound<&usize> {
        unimplemented!()
    }
    fn end_bound(&self) -> Bound<&usize> {
        unimplemented!()
    }
    fn assert_len(self, _len: usize) -> Range<usize> {
        0..42
    }
}

fn main() {
    vec![1, 2, 3].drain(EvilRange(Cell::new(false)));
}
```

Related issues: #76393, #81154.

**Comment by dylni** [comment]
Thanks for noticing this. I think the best fix is to define the method on `Range` instead. I'll update [this PR](https://github.com/rust-lang/rust/pull/81154) with that change unless anyone has a better idea.

**Comment by RalfJung** [comment]
Good catch!
