### ISSUE TITLE
dbg! on Ipv6Addr should not show leading '0x'

### ISSUE THREAD

**Issue by KSXGitHub** [rust-lang/rust#81182]
[prior discussion](https://users.rust-lang.org/t/why-does-dbg-of-ipv6addr-show-leading-0x/54364)
[playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=385e6c132ab24c4e7086f9f52332badb)

---

I tried this code:

```rust
let ip = Ipv6Addr::new(123, 0, 3, 0, 0, 0, 36, 2);
dbg!(&ip);
```

I expected to see this happen: It prints `7b:0:3::24:2`

Instead, this happened: It prints `0x7b:0x0:0x3::0x24:0x2`

### Meta

`rustc --version --verbose`:
```
rustc 1.48.0 (7eac88abb 2020-11-16)
binary: rustc
commit-hash: 7eac88abb2e57e752f3302f02be5f3ce3d7adfb4
commit-date: 2020-11-16
host: x86_64-unknown-linux-gnu
release: 1.48.0
LLVM version: 11.0
```

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by jyn514** [comment]
@KSXGitHub are you interested in fixing this yourself? I think the relevant code is https://github.com/rust-lang/rust/blob/f09fb488f70c5965ec4f64453a6e681fbfcff56c/library/std/src/net/ip.rs#L1614

**Comment by KSXGitHub** [comment]
@jyn514 Nope, I'm not interested spending half a day compiling this repo.
