### ISSUE TITLE
Missing links to src of implementors in docs of hir and ast visitors

### ISSUE THREAD

**Issue by b-naber** [rust-lang/rust#81190]
In the docs for the compiler no links to the source code of the implementors of the [ast::Visitor](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_ast/visit/trait.Visitor.html#implementors) and the [hir::Visitor](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_hir/intravisit/trait.Visitor.html#implementors) are provided. @jyn514 said that this is likely a bug.

**Comment by jyn514** [comment]
Related: https://github.com/rust-lang/rust/issues/76736

**Comment by camelid** [comment]
I believe this is a duplicate of #78615.

**Comment by jyn514** [comment]
Good catch, it is indeed a duplicate.
