### ISSUE TITLE
write_mir_pretty no longer works for non local def_ids

### ISSUE THREAD

**Issue by hermanventer** [rust-lang/rust#81200]
The expect_local call here means that write_mir_pretty no longer works for non local def_ids. The ability to print out MIR for non local functions this way is critical for the MIRAI project.

_Originally posted by @hermanventer in https://github.com/rust-lang/rust/pull/78407#r560551603_

**Comment by RalfJung** [comment]
Cc @oli-obk

**Comment by oli-obk** [comment]
I think what we can do is to check `is_const_fn_raw` for the `const fn` path, and use `tcx.instance_mir(ty::InstanceDef::Item(def_id))` if it is not a const fn, as `instance_mir` already does the correct dispatching for anything that is not a const fn.

**Comment by hi-rustin** [comment]
Can I working on this?

**Comment by hermanventer** [comment]
That would be great. This is a blocker for me.

**Comment by oli-obk** [comment]
It's all yours! You can use `@rustbot claim` to have the bot assign it to you

**Comment by oli-obk** [comment]
If you need any help, don't hesitate to ask here or ping me on zulip. I'll respond whenever I have time (which is a bit flaky this week, but you should definitely get a response once a day)

**Comment by hi-rustin** [comment]
Sorry, I haven't had time to finish it lately. Let's see if others can help.

**Comment by osa1** [comment]
Do we have a reproducer for this issue? I have some idea of what needs to be done here, but I don't know how to check if it really works.

**Comment by hermanventer** [comment]
The only way I know of how to do this is to write something that uses the compiler driver, see for example: https://github.com/rust-lang/rustc-dev-guide/tree/master/examples. That seems like quite a lot of trouble to go to. More ideal would be some kind of unit test, but I have no idea of how that may be accomplished.

Perhaps the easiest way to do an ad hoc test would be to build MIRAI with the latest nightly (I'd have to put up a branch that has been ported to it) and then run its tests.

**Comment by hermanventer** [comment]
I've uploaded a draft PR to https://github.com/facebookexperimental/MIRAI/pull/754. If you build that with a recent nightly and then run cargo test, you should see failures. If your fix is good, then all tests should pass.

**Comment by osa1** [comment]
Thanks @hermanventer, that's very helpful. I was able to run the tests successfully using the master branch, but if I use my stage 1 build with your branch some of the tests fail, and the backtraces include `write_mir_pretty` so I'm guessing those failing tests are reproducers for this issue.
