### ISSUE TITLE
When field isn't found, see if any of the available fields has it

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#81220]
I just encountered this output:

```
error[E0609]: no field `span` on type `Label`
   --> compiler/rustc_passes/src/loops.rs:127:43
    |
127 | ...                   label.span,
    |                             ^^^^ unknown field
    |
    = note: available fields are: `ident`
```

We currently mention available fields when the field used isn't found. It would be nice if we peeked at the types for the available fields to see if any of them has any fields (including through deref) of the name we originally wanted. In this case, I would love to see the following output:

```
error[E0609]: no field `span` on type `Label`
   --> compiler/rustc_passes/src/loops.rs:127:43
    |
127 | ...                   label.span,
    |                             ^^^^ unknown field
    |
help: the field `span` is available on field `ident` of type `Ident`:
    |
127 | ...                   label.ident.span,
    |                             ^^^^^^
    |
```

**Comment by matsujika** [comment]
I'll work on this.
@rustbot claim

**Comment by b-naber** [comment]
@matsujika I was just about to open a PR when I saw that you claimed the issue. It's my fault for not claiming this issue myself obviously, so if you've already been investing time into this the issue is still yours, but if you haven't can I open a PR for this?

**Comment by matsujika** [comment]
@b-naber I've done nothing yet as I planned to work on this tomorrow morning, so it's yours :)

**Comment by estebank** [comment]
@matsujika if you're still interested in contributing, it seems to me that https://github.com/rust-lang/rust/issues/81222 might be similar in scope and section of the codebase you could work in.

**Comment by b-naber** [comment]
@matsujika Thank you.
