### ISSUE TITLE
A third of the time rustdoc takes to document windows-rs is `<unknown>`

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#81251]
I tried this code: https://github.com/microsoft/windows-docs-rs/commit/3371c03c6ad79e7fe22f7b0c44db43a4175a72ec

I expected to see this happen: `cargo rustdoc -- -Z self-profile` shows where the 50 minutes are being spent.

Instead, this happened: Rustdoc completely loses 20 of the 50 minutes and gives up.

Here's the top 6 items from `summarize summarize`:

```
+-------------------------------------------------+-----------+-----------------+----------+------------+
| Item                                            | Self time | % of total time | Time     | Item count |
+-------------------------------------------------+-----------+-----------------+----------+------------+
| <unknown>                                       | 653.09s   | 36.998          | 1336.82s | 24718096   |
+-------------------------------------------------+-----------+-----------------+----------+------------+
| resolve_crate                                   | 540.19s   | 30.602          | 540.19s  | 1          |
+-------------------------------------------------+-----------+-----------------+----------+------------+
| render_html                                     | 384.93s   | 21.807          | 386.88s  | 1          |
+-------------------------------------------------+-----------+-----------------+----------+------------+
| get_blanket_impls                               | 66.06s    | 3.742           | 76.22s   | 45080      |
+-------------------------------------------------+-----------+-----------------+----------+------------+
| expand_crate                                    | 30.12s    | 1.706           | 30.13s   | 1          |
+-------------------------------------------------+-----------+-----------------+----------+------------+
```

Note that `<unknown>` is at the top.
cc https://github.com/microsoft/windows-rs/issues/420, https://github.com/rust-lang/rust/pull/74590#issuecomment-674590936

### Meta

`rustdoc --version`: `rustdoc 1.51.0-nightly (a4cbb44ae 2021-01-20)`

**Comment by jyn514** [comment]
I am still baffled what this could be. `item_types_checking` is clearly being measured, and the only places I see `<unknown>` are
- https://github.com/rust-lang/rust/blob/65767e56537e20903b54ecde7c371cbfb1b201b0/compiler/rustc_codegen_cranelift/example/std_example.rs#L24 (clearly not it)
- https://github.com/rust-lang/rust/blob/65767e56537e20903b54ecde7c371cbfb1b201b0/compiler/rustc_codegen_llvm/src/debuginfo/metadata.rs#L795 - seems like a stretch, rustdoc should never be calling codegen
- https://github.com/rust-lang/rust/blob/65767e56537e20903b54ecde7c371cbfb1b201b0/compiler/rustc_interface/src/passes.rs#L1021, which seems plausible, but I never see `self_profile_alloc_query_strings` show up in the output :/

So I don't know what this could possibly be.

**Comment by jyn514** [comment]
I can also reproduce on https://github.com/rust-lang/cargo/commit/4de00d2c7fdd961e72eb189a31f8ae677833ed99, which works on linux and is overall easier to build.

**Comment by jyn514** [comment]
This is definitely not from https://github.com/rust-lang/rust/blob/65767e56537e20903b54ecde7c371cbfb1b201b0/compiler/rustc_interface/src/passes.rs#L1021 because `RUSTC_LOG=rustc_interface` doesn't show "Post-codegen" anyway.

**Comment by jyn514** [comment]
The only places this is emitted in measureme are for https://github.com/rust-lang/measureme/blob/16688a5da98f403b2b7f1942564adf3361c99cff/analyzeme/src/stringtable.rs#L48 and https://github.com/rust-lang/measureme/blob/16688a5da98f403b2b7f1942564adf3361c99cff/analyzeme/src/stringtable.rs#L95.

@michaelwoerister do you have any idea what could be going wrong here?

**Comment by jyn514** [comment]
> I've only skimmed the PR but I think we should not block merging this with resolving the `unknown` issue. We've seen that before in other profiles so it's probably another instance of the existing issue. I hope to have some time this week to look into it.

@wesleywiser do you remember where you've seen this before?

**Comment by wesleywiser** [comment]
I had an theory that I ran by @jyn514 and they're testing it out: rustdoc never calls `start_codegen()` and therefore `alloc_self_profile_query_strings()` is never called which means the `<unknown>` events are actually *every query in rustc*! 

This seems to hold if we look at the `summarize` output for a rustdoc self-profile like [this one](https://gist.github.com/rylev/498bd19539dcff01c7be08e0ac7459f7). As far as I can tell, the only events listed are ones timed using the `generic_activity()` API which uses a different code path to store the event label. From what I can tell, there are no queries at all listed.

**Comment by jyn514** [comment]
@wesleywiser that did it! `unknown` doesn't show up at all any more :)

```
+-------------------------------------------------+-----------+-----------------+----------+------------+
| Item                                            | Self time | % of total time | Time     | Item count |
+-------------------------------------------------+-----------+-----------------+----------+------------+
| expand_crate                                    | 697.97ms  | 15.614          | 711.88ms | 1          |
+-------------------------------------------------+-----------+-----------------+----------+------------+
| get_blanket_impls                               | 615.38ms  | 13.766          | 707.27ms | 472        |
+-------------------------------------------------+-----------+-----------------+----------+------------+
| render_item                                     | 499.50ms  | 11.174          | 503.16ms | 510        |
+-------------------------------------------------+-----------+-----------------+----------+------------+
| build_extern_trait_impl                         | 415.08ms  | 9.286           | 714.64ms | 22356      |
+-------------------------------------------------+-----------+-----------------+----------+------------+
| get_auto_trait_impls                            | 272.80ms  | 6.103           | 314.81ms | 472        |
+-------------------------------------------------+-----------+-----------------+----------+------------+
```
