### ISSUE TITLE
interrupted by signal 4: SIGILL

### ISSUE THREAD

**Issue by 742362144** [rust-lang/rust#81256]
i try to use generator_trait and build rust project as dylib,like this:
lib.rs
```rust
#![crate_type = "dylib"]
#![forbid(unsafe_code)]
#![feature(generators, generator_trait)]
// #![allow(bare_trait_objects)]
extern crate redis;

use std::ops::Generator;
use std::pin::Pin;

// use mylib::print_hello;

// use bytes::{Bytes, BytesMut, BufMut, Buf};

// use redis_module::{ThreadSafeContext, DetachedFromClient};
use std::sync::{Arc, Mutex};
use std::sync::mpsc::{Sender, Receiver};
use runtime::policy::Policy;
use std::thread;
use std::time::Duration;
// use redismodule::executor::Policy;
// use log::{info, trace, warn};


#[no_mangle]
#[allow(unreachable_code)]
#[allow(unused_assignments)]
pub fn init(policy: Arc<Mutex<String>>) -> Pin<Box<Generator<Yield=u64, Return=u64> + 'static>> {
// pub fn init() -> Pin<Box<Generator<Yield=u64, Return=u64> + 'static>> {
//     print_hello();
//     println!("{}", "enter");
    // let ctx = tctx.clone();
    // let tx = ctx.lock();

    // println!("{}", "gen init");
    // let mut p = policy.clone();
    Box::pin(move || {
        let i:u64 = 1;
        // p.lock().unwrap().set("A", "111");
        // println!("{}", "compute step 1 running");
        thread::sleep(Duration::from_millis(1000));
        // tx.call("SET", &["A", "1"]).unwrap();
        yield i;
        // tx.call("SET", &["B", "2"]).unwrap();
        // println!("{}", "compute step 2 running");
        thread::sleep(Duration::from_millis(1000));
        yield i;
        // tx.call("SET", &["B", "2"]).unwrap();
        // println!("{}", "compute step 3 running");
        thread::sleep(Duration::from_millis(1000));
        yield i;
        // tx.call("SET", &["B", "2"]).unwrap();
        // println!("{}", "compute step 4 running");
        thread::sleep(Duration::from_millis(1000));
        yield i;
        // tx.call("SET", &["B", "2"]).unwrap();
        // println!("{}", "compute step 5 running");
        thread::sleep(Duration::from_millis(1000));
        1111
    })
}
```

main.rs

```rust
#![feature(generators)]
#![feature(generator_trait)]
use std::ops::{GeneratorState, Generator};
use std::pin::Pin;
use libloading::os::unix::{Library, Symbol};
use runtime::policy::Policy;
use std::sync::{Mutex, Arc};


fn main() {
    type Proc = unsafe extern "C" fn(Arc<Mutex<String>>) -> Pin<Box<Generator<Yield=u64, Return=u64>>>;
    let library_path = String::from("/home/coder/IdeaProjects/add/target/debug/libadd.so");
    println!("Loading add() from {}", library_path);

    let lib = Library::new(library_path).unwrap();


    println!("{}", "1");
    unsafe {
        println!("{}", "2");
        let func: Symbol<Proc> = lib.get(b"init").unwrap();
        println!("{}", "3");
        let mut generator = func(Arc::new(Mutex::new(String::from("hello"))));
        println!("{}", "4");

        // println!("1");
        // Pin::new(&mut generator).resume(());
        // println!("3");
        // let Some(GeneratorState<res1, res2>) = Pin::new(&mut generator).resume(());
        // println!("5");

        // db.set(String::from("c"), Bytes::from("dadada"), None);
        match generator.as_mut().resume(()) {
            GeneratorState::Yielded(1) => println!("Yielded"),
            _ => panic!("unexpected return from resume"),
        }
        match generator.as_mut().resume(()) {
            GeneratorState::Complete(1111) => println!("Completed"),
            _ => panic!("unexpected return from resume"),
        }
    }
    assert!(1 != 2, "true");
}
```

when i try to load dylib use libloading crate, error occur：

thread panicked while processing panic. aborting.

Process finished with exit code 132 (interrupted by signal 4: SIGILL)

-----------------gdb-------------------------------
(gdb) run
Starting program: /home/coder/IdeaProjects/add/target/debug/main 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
thread panicked while processing panic. aborting.

Program received signal SIGILL, Illegal instruction.
0x0000555555581f42 in std::panicking::rust_panic_with_hook () at /rustc/bc39d4d9c514e5fdb40a5782e6ca08924f979c35/library/core/src/fmt/mod.rs:314
314     /rustc/bc39d4d9c514e5fdb40a5782e6ca08924f979c35/library/core/src/fmt/mod.rs: No such file or directory.

--------------------rust version------------------
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/coder/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu
nightly-x86_64-unknown-linux-gnu (default)

active toolchain
----------------

nightly-x86_64-unknown-linux-gnu (default)
rustc 1.51.0-nightly (bc39d4d9c 2021-01-15)

what happened? i try to use other rust version, error still have.
 plz help me, very thanks.

**Comment by nagisa** [comment]
Your code has a number of undefined behaviour. ABI mismatch between caller and callee and panicking across FFI boundary are the two most obvious issues.

rust-lang/rust issue tracker is intended for tracking issues that concern specifically the rust compiler and the language, as thus I'm going to close this issue. You are welcome to ask this to be reopened and/or file a new issue when you encounter these kinds of problems with well-formed code. You should consider posting your question on [users.rlo](https://users.rust-lang.org/), [stackoverflow](https://stackoverflow.com/), [reddit](https://www.reddit.com/r/rust/), or asking for support on one of the chat platforms: [discord](https://discordapp.com/invite/aVESxV8) or [zulip](https://rust-lang.zulipchat.com/#) instead.
