### ISSUE TITLE
Accessing the crate's version and name from within

### ISSUE THREAD

**Issue by Seldaek** [rust-lang/rust#8129]
It would be great to have a way to access the values in:

`#[link(name = "blob", vers = "1.0", author = "foo")];`

To print usage info in executables without duplicating this info.

**Comment by steveklabnik** [comment]
@alexcrichton couldn't the `Cargo.toml` entry for `name` be exposed just like the version ones are?

**Comment by alexcrichton** [comment]
@steveklabnik yes that's just passed in through `--crate-name` which is what the compiler would expose.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#782
