### ISSUE TITLE
Deprecate the `expr_method_call` function entirely in favour of ufc

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#81295]
Using method calls in built in derives keeps causing problems due to different imports in the surrounding scope.

Maybe we should just remove the `expr_method_call` function entirely (or perma-deprecate it so ppl searching for it get an explanation of why they should use ufcs)

_Originally posted by @oli-obk in https://github.com/rust-lang/rust/pull/81294#discussion_r563043413_

**Comment by Skgland** [comment]
`expr_method_call` has been removed in 441dc3640a408e612064464b0c6308bdca6c16ce
