### ISSUE TITLE
Span is too large for unused `rest @ ..` pattern warning

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#81314]
The compiler suggests replacing `rest @ ..` with `_rest`, when in fact it should suggest `_rest @ ..`:

```rust
fn main() {
    let [rest @ ..] = [1, 2, 3];
}
```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=f93b0149de57c3fd50ccc0cc26ce89be))

Errors:

```
   Compiling playground v0.0.1 (/playground)
warning: unused variable: `rest`
 --> src/main.rs:2:10
  |
2 |     let [rest @ ..] = [1, 2, 3];
  |          ^^^^^^^^^ help: if this is intentional, prefix it with an underscore: `_rest`
  |
  = note: `#[warn(unused_variables)]` on by default

warning: 1 warning emitted

    Finished dev [unoptimized + debuginfo] target(s) in 0.73s
     Running `target/debug/playground`
```

The span should point to just `rest`.

**Comment by ankushduacodes** [comment]
Hi @camelid, Where do look for to fix this `invalid suggestion`?

**Comment by camelid** [comment]
This is where the suggestion is emitted:

https://github.com/rust-lang/rust/blob/4d0dd02ee07bddad9136f95c9f7846ebf3eb3fc5/compiler/rustc_passes/src/liveness.rs#L1536-L1583

However, I think the issue is in the `hir_ids_and_spans` argument. That argument is passed in here:

https://github.com/rust-lang/rust/blob/4d0dd02ee07bddad9136f95c9f7846ebf3eb3fc5/compiler/rustc_passes/src/liveness.rs#L1503-L1511

You might have to hunt around a bit to find the spot where the spans are created.

**Comment by camelid** [comment]
Feel free to ask in `#t-compiler/help` on Zulip if you have any questions! You may also want to look through the [rustc-dev-guide](https://rustc-dev-guide.rust-lang.org/).

**Comment by ankushduacodes** [comment]
@camelid I was following the rustc-dev-guide but I am having some issues, the issue is with the following step:
[Creating a rustup toolchain](https://rustc-dev-guide.rust-lang.org/building/how-to-build-and-run.html#creating-a-rustup-toolchain) I didn't create build/<platform>/stage2/ directory for me.

**Comment by estebank** [comment]
For working on this you won't need stage 2, stage 1 will suffice.

**Comment by sladyn98** [comment]
I guess I can give this issue a shot I have the setup ready and stage one works fine. I am new to rust so forgive me for asking too many questions

**Comment by SkiFire13** [comment]
Since it has been more than 2 weeks since the last update I guess this is free to pick? In case someone is still working on this let me know

@rustbot claim
