### ISSUE TITLE
Tracking Issue for `result_swap`

### ISSUE THREAD

**Issue by gymore-io** [rust-lang/rust#81322]
Feature gate: `#![feature(result_swap)]`

This is a tracking issue for `result_swap`

I propose the addition of a `swap` method for the `Result` type that would basically turn an `Ok` into an `Err` and the other way around.

### Motivation

This would obviously allow more straightforward code when one need to propagate the success type of a function as an error.

```rust
fn my_function(vec: &mut Vec<u8>) -> Result<usize, usize> {
    // The value should not be found in the given vector.
    let b = vec.binary_search(&10).swap()?;
    vec.insert(b, 10);

    Ok(b)
}
```

Used with the `Result` constructors that are present on `Option`, this method also can come in handy.

```rust
fn expect_none(o: Option<u8>) -> Result<(), u8> {
    o.ok_or(()).swap()
}
```

Note that this second case could also be fixed with something like `err_or` (being discussed here #80190).

### Steps

- [x] Initial implementation (PR #81323)
- - [x] Write tests
- [ ] Adjust documentation
- [ ] Stabilization PR

### Unresolved Questions

- The name `swap` may be confused with the already-used semantic of `mem::swap` or `slice::swap` which both have a slightly different meaning. The alternative I had for this matter was the name `not` (the function basically inverts the meaning of the `Result`) but I think it makes it even more confusing.
- Do we want an `Option::swap` equivalent that would map `Some(old_value)` to `None` and `None` to `Some(new_value)` where `new_value` is a parameter of `Option::swap`? Such a function would probably require a `Option::swap_with` counterpart that takes a `FnOnce() -> T`.

**Comment by egilburg** [comment]
Bikeshed: Would something like `and_err` be more clear or similar to existing chaining like `ok_or`?

**Comment by gymore-io** [comment]
@egilburg I'm not sure to understand very well what you think meant about `and_err`. Regarding `Option::swap`, I think it maps pretty well to `Result::swap` (assuming you wanted to say that it would map `None` to `Some` and `Some` to `None`). In my opinion however, I find it a bit more confusing because it is giving a slightly different semantic to `swap`. That may or may not be something we want to pay attention to.

I'm editing the issue to consider `Option::swap` either way.

**Comment by Veykril** [comment]
Is this addition pulling its weight though? This Result-swapping can already be done via `result.map_or_else(Ok, Err)`. Result already has quite a lot of methods as is.

For the Option version this doesn't work as nicely as `Option::None` isn't considered a callable, `result.map_or_else(|| None, Some)`.

**Comment by gymore-io** [comment]
Righteously pointed by [this comment](https://github.com/rust-lang/rust/pull/81323#issuecomment-766361396), this whole `Result::swap` thing is basically a less clear version of what [`try_trait_v2`](https://github.com/rust-lang/rfcs/pull/3058) aims to achieve with some of its traits/structures. I'm closing this issue.
