### ISSUE TITLE
[rustdoc] Remove query component from URL by pressing ESC

### ISSUE THREAD

**Issue by tesuji** [rust-lang/rust#81330]
mdbook v4.6+ has a feature that pressing ESC removes query components from URLs (for example `?highlight=...`).
The feature was implemented in rust-lang/mdBook#1427.

 It would be nice if rustdoc offers the same kind of that feature.

This is, for example, an URL that contains query components in rustdoc: https://doc.rust-lang.org/nightly/std/time/struct.Duration.html?search=asdfasdf.

### What's the benefit of this feature?

When users share URLs to an API, they don't have to remove the query manually.

**Comment by lzutao** [comment]
@GuillaumeGomez, could you share some thoughts about this feature request?
If possible, could you mentor contributors how to implement this ?

**Comment by GuillaumeGomez** [comment]
I think it's a good idea. Gonna take a look at how to do it.

**Comment by lzutao** [comment]
Can we reopen this issue ?
I think #81379 only removes the query component when we remove keywords in search bar.
This issue is about adding a keyboard shortcut.

**Comment by GuillaumeGomez** [comment]
Oh I see, my bad. Reopening!
