### ISSUE TITLE
Argument lifetimes appear to not be automatically shortened to those of a local variable

### ISSUE THREAD

**Issue by LHolten** [rust-lang/rust#81336]
I tried this code:
```rust
fn test(mut vec: Vec<&u64>, val: u64) {
    vec.push(&val);
}
```
And this code:
```rust
fn test(mut vec: Vec<&u64>, val: u64) {
    let mut vec = vec;
    vec.push(&val);
}
```

I expected both snippets to be equivalent and compile.
Instead, only the second snippet compiles and the first one complains that `val` does not live long enough:
```rust
error[E0597]: `val` does not live long enough
  --> src\tree.rs:41:14
   |
40 | fn test(mut vec: Vec<&u64>, val: u64) {
   |                      - let's call the lifetime of this reference `'1`
41 |     vec.push(&val);
   |     ---------^^^^-
   |     |        |
   |     |        borrowed value does not live long enough
   |     argument requires that `val` is borrowed for `'1`
42 | }
   | - `val` dropped here while still borrowed
```

It seems as if the lifetimes of arguments are not shortened to those of a local variable.

To me this seems to be a compiler bug, because intuitively arguments are a subset of the local variables.

### Meta

`rustc --version --verbose`:
```
rustc 1.51.0-nightly (4d0dd02ee 2021-01-23)
binary: rustc
commit-hash: 4d0dd02ee07bddad9136f95c9f7846ebf3eb3fc5
commit-date: 2021-01-23
host: x86_64-pc-windows-gnu
release: 1.51.0-nightly
LLVM version: 11.0.1
```

**Comment by jyn514** [comment]
This looks correct to me actually - if you pass in a `&u64` it by definition must live longer than the lifetime of the function. So when you try to push the local variable, it has a shorter lifetime than the arguments already in the vec and the compiler gives an error. When you set the vec to a local variable, the compiler can assume the lifetimes of the &u64 it contains don't have to live longer than the function.

**Comment by jonas-schievink** [comment]
This is expected behavior and happens due to the destructor order. Local variables are dropped before arguments, and arguments are dropped from right to left, so in the first function, `val` is dropped before `vec`, which would create a dangling pointer, so it doesn't compile. In the second snippet, the local variable `vec` is dropped first, so it compiles.
