### ISSUE TITLE
Accessing fields through a `Deref` impl leads to confusing error messages

### ISSUE THREAD

**Issue by Aaron1011** [rust-lang/rust#81365]
The following code:

```rust
use std::ops::Deref;

struct DerefTarget {
    target_field: bool
}
struct Container {
    target: DerefTarget,
    container_field: bool,
}

impl Deref for Container {
    type Target = DerefTarget;
    fn deref(&self) -> &Self::Target {
        &self.target
    }
}

impl Container {
    fn bad_borrow(&mut self) {
        let first = &self.target_field;
        self.container_field = true;
        first;
    }
}
```

causes the following error message:

```
error[E0506]: cannot assign to `self.container_field` because it is borrowed
  --> src/lib.rs:21:9
   |
20 |         let first = &self.target_field;
   |                      ---- borrow of `self.container_field` occurs here
21 |         self.container_field = true;
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^ assignment to borrowed `self.container_field` occurs here
22 |         first;
   |         ----- borrow later used here

```

This error is caused by the fact that `&self.target_field` does through the `Deref` impl on `Container`. As a result, `&self` is borrowed, not just the desired field. Changing this line to `let first = &self.target.target_field` makes the code compile.

However, the error message doesn't explain any of this. It claims that the usage of `self` is a borrow of `self.container_field`, without noting that this is due to the `Deref` impl.

We should do something similar to https://github.com/rust-lang/rust/pull/75304 for borrows, and make it clear when lifetimes are being affected by implicit `Deref` calls.

**Comment by 1000teslas** [comment]
@Aaron1011 How can I check if a `Deref` in the list of projections of a place is implicitly inserted?

**Comment by Aaron1011** [comment]
@1000teslas: You should be able to adapt this code: https://github.com/rust-lang/rust/blob/0677d9729318441a1cdb0c74812ec4140fa4d35f/compiler/rustc_mir/src/borrow_check/diagnostics/mod.rs#L798-L893

and re-use the `FnSelfUse` code. The actual check for a non-user-supplied `Deref` call is done by: https://github.com/rust-lang/rust/blob/0677d9729318441a1cdb0c74812ec4140fa4d35f/compiler/rustc_mir/src/borrow_check/diagnostics/mod.rs#L835

**Comment by 1000teslas** [comment]
@Aaron1011 It doesn't look like `from_hir_call` distinguishes between `issue-81365.rs`, where the deref in `self.target_field` is implicit and `issue-81365-8.rs`, where the deref is explicit.
