### ISSUE TITLE
Feature request: show rustc_const_unstable in generated documentation

### ISSUE THREAD

**Issue by ChaiTRex** [rust-lang/rust#81371]
**Describe the problem you are trying to solve**

I looked at [the documentation for `core::mem::variant_count`](https://doc.rust-lang.org/core/mem/fn.variant_count.html). It does mention that the function is nightly-only:

> 🔬 This is a nightly-only experimental API.  
(`variant_count` [#73662](https://github.com/rust-lang/rust/issues/73662))

It misleadingly doesn't mention that `const fn` can also be enabled on nightly, which requires opening [the `[src]` link](https://doc.rust-lang.org/src/core/mem/mod.rs.html#1038-1040) and noticing:

    #[rustc_const_unstable(feature = "variant_count", issue = "73662")]

**Describe the solution you'd like**

When the `rustc_const_unstable` attribute is applied to a function, show that, much like nightly-only functions are shown in the documentation.

**Comment by ehuss** [comment]
Transferred to rust-lang/rust, as that is where rustdoc lives (which generates the documentation).

**Comment by jyn514** [comment]
It would be nice to show something like `(const: unstable)` to mirror how shows rustdoc shows stable annotations like `(const: 1.50)`.

**Comment by steffahn** [comment]
Looks like [in beta](https://doc.rust-lang.org/beta/std/primitive.pointer.html#method.is_null) it shows `const` for method (at least for [pointer](https://doc.rust-lang.org/beta/std/primitive.pointer.html)’s methods) unconditionally, without much or any indication that a function may only be stable without the const.

**Comment by jyn514** [comment]
Added in https://github.com/rust-lang/rust/pull/86473
