### ISSUE TITLE
Derived PartialOrd is incorrect when inner values are unordered

### ISSUE THREAD

**Issue by tmiasko** [rust-lang/rust#81373]
In the derived `partial_cmp` the comparisons stops when inner `partial_cmp` returns
`None`. The implementation for `lt`, `le`, `gt`, `ge` are also provided, but they
continue the comparisons instead as if compared values were considered equal.

This behaviour is also inconsistent with the implementation for tuples / slices:

```rust
#[derive(PartialEq, PartialOrd)]
struct P(f64, f64);

fn main() {
    let a = (f64::NAN, 0.0);
    let b = (f64::NAN, 1.0);

    // Tuples:
    assert_eq!(PartialOrd::partial_cmp(&a, &b), None);
    assert!(!(a < b));

    // Arrays:
    let a = [f64::NAN, 0.0];
    let b = [f64::NAN, 1.0];
    assert_eq!(PartialOrd::partial_cmp(&a, &b), None);
    assert!(!(a < b));

    // Derived:
    let a = P(f64::NAN, 0.0);
    let b = P(f64::NAN, 1.0);
    assert_eq!(PartialOrd::partial_cmp(&a, &b), None);
    assert!(!(a < b)); // fails
}
```

**Comment by hameerabbasi** [comment]
Assigning `P-high` as discussed [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2381373.20Derived.20PartialOrd.20is.20incorrect.20when.20inner.20values.20ar.E2.80.A6).
