### ISSUE TITLE
Breaking change in wasm32-unknown-unknown's ABI on nightly

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#81386]
Some tests in the wasm-bindgen project have started failing in nightly, and bisection points to https://github.com/rust-lang/rust/pull/80594 as the culprit. The minimization of this looks like:

```rust
#[repr(C)]
pub struct Foo {
    pub a: u32,
    pub b: u32,
    pub c: u32,
}

#[no_mangle]
pub extern "C" fn foo(a: Foo) {}
```

where before this compiles as:

```
$ rustc +before foo.rs --crate-type cdylib --target wasm32-unknown-unknown -O && wasm2wat foo.wasm | grep 'func..foo'
  (func $foo (type 0) (param i32 i32 i32))
  (export "foo" (func $foo))
$ rustc +after foo.rs --crate-type cdylib --target wasm32-unknown-unknown -O && wasm2wat foo.wasm | grep 'func..foo'
  (func $foo (type 0) (param i32))
  (export "foo" (func $foo))
```

**Comment by bjorn3** [comment]
That must have been a93dace55c588badca5475de570e45063deaf0be. This all types with `Abi::Aggregate` to become `PassMode::Indirect`. Later abi adjustments could then turn it into `PassMode::Cast` as necessary. I thought abi adjustments would never leave the dummy `PassMode::Direct` in place for `Abi::Aggregate`, but it seems not for wasm. I don't think this should ever happen as it will cause LLVM to do it's own abi adjustments. The whole point of that PR was to make it easier for Cranelift to match the abi of LLVM, which those abi adjustments would make harder.

I think there will need to be an `arg.cast_to(...)` call inserted in the abi handling of wasm. What kind of types does wasm-bindgen produce?

```rust
#[repr(C)]
pub struct Bar {
    pub foo: u8,
}

#[repr(C)]
pub struct Foo {
    pub a: Bar,
    pub b: u32,
    pub c: u32,
}

#[no_mangle]
pub extern "C" fn foo(a: Foo) {}
```

produces `(func $foo (type 0) (param i32 i32 i32 i32 i32 i32))`, so I can't think of a clear rule describing what is used by LLVM. The easiest fix is maybe to special case `wasm32-unknown-unknown` at https://github.com/rust-lang/rust/blob/84864bfea9c00fb90a1fa6e3af1d8ad52ce8f9ec/compiler/rustc_middle/src/ty/layout.rs#L2754 to use `PassMode::Direct`. This only affects wasm, which isn't supported by cg_clif anyway.

**Comment by bjorn3** [comment]
#81388 will hopefully fix this.

**Comment by hameerabbasi** [comment]
Assigning `P-high` as discussed [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2381386.20Breaking.20change.20in.20wasm32-unknown-unknown's.20ABI.20on.20n.E2.80.A6).

**Comment by Manishearth** [comment]
@alexcrichton do you remember which of the tests were failing here? I was under the impression wasm-bindgen _didn't_ support passing structs as arguments, and instead passed them by-reference.


I'm working with passing structs by-value over Wasm and am dealing with similar ABI weirdnesses (https://github.com/rust-diplomat/diplomat/issues/657), and was curious if wasm-bindgen had already solve the problem somewhere but I can't get it to ever pass any aggregate by-value.

**Comment by alexcrichton** [comment]
Alas this is too far back for me, I don't remember :(
