### ISSUE TITLE
[small issue] gen_range can compile in empty range but doesn't run

### ISSUE THREAD

**Issue by Salah-Eddine-Harnoufi** [rust-lang/rust#81410]
Hi, I'm in new at using rust, so my submit maybe irrelevant, so I was curious to try gen_range method in empty range 1..1 for example and the program compiled correctly.

But when I wanted to run it, it wasn't working with the message error "thread 'main' panicked at 'cannot sample empty range', C:\Users\me\.cargo\registry\src\github.com-1ecc6299db9ec823\rand-0.8.3\src\rng.rs:132:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\test.exe` (exit code: 101)"

There is my code:

`
use rand::Rng;

fn main() {
    let number = rand::thread_rng().gen_range(1..1);
}
`
"If It's compile It's work" not here -> I wonder if it's because I'm using an extarnal library (rand 0.8.3) but maybe, I'm just posting this.

rust 1.49.0. [dependencies]  rand = "0.8.3"

**Comment by jonas-schievink** [comment]
This is an issue in the `rand` crate, not in Rust itself, so please file it at https://github.com/rust-random/rand
