### ISSUE TITLE
Allow leading | anywhere we allow or-patterns

### ISSUE THREAD

**Issue by joshtriplett** [rust-lang/rust#81415]
See https://github.com/rust-lang/rust/issues/54883#issuecomment-742802350 for details.

Filing this issue to check lang-team consensus on this: do we want to allow leading `|` everywhere we allow or-patterns?

**Comment by joshtriplett** [comment]
@rfcbot merge

**Comment by scottmcm** [comment]
Somehow to me they feel a little weirder in something like `matches!(foo, | Bar(_) | Baz(_))`, but regardless I think allowing them is the right thing to do for consistency and the overall grammar.

**Comment by joshtriplett** [comment]
@scottmcm In that use case, they'd likely look like this:

```rust
    matches!(
        some_long_expression,
        | SomeLongPattern
        | SomeOtherLongPattern
    )
```

**Comment by nikomatsakis** [comment]
@rfcbot reviewed

**Comment by joshtriplett** [comment]
Checking box for boats per https://github.com/rust-lang/team/pull/526 .

**Comment by mark-i-m** [comment]
This is what the grammar would look like after this change: https://github.com/rust-lang/reference/pull/957/files?short_path=cc629f1#diff-cc629f15712821139bc706c63b3845ab59a008e2a998e08ffad42e3aebcbcbe2

**Comment by mark-i-m** [comment]
Implementation: https://github.com/rust-lang/rust/pull/81869

**Comment by lukechu10** [comment]
I think rustfmt should add a leading `|` when the pattern is on multiple lines but remove it when it's on a single line:
```rust
matches!(foo, Bar | Baz);

matches!(
    some_really_long_expression,
    | Bar
    | Baz
)

match foo {
    Bar | Baz => {},
    _ => {}
}

match foo {
    | Bar
    | Baz => {},
    _ => {}
}
```
Just for consistency

**Comment by jplatte** [comment]
@lukechu10 Formatting is not something the compiler does. IIRC there is an issue about this on https://github.com/rust-lang/rustfmt somewhere.

**Comment by WiSaGaN** [comment]
Should this be closed now that the implementation is merged?

**Comment by nikomatsakis** [comment]
Sounds good.
