### ISSUE TITLE
rustc_arena::coldpath shouldn't be `pub`

### ISSUE THREAD

**Issue by zserik** [rust-lang/rust#81429]
https://github.com/rust-lang/rust/blob/1d517afcd0929450ded8f644fa8e8da3776db68b/compiler/rustc_arena/src/lib.rs#L33-L37
The function isn't used anywhere outside of that crate (there is a copy of that function in `rustc_datastructures`, which is used elsewhere). It shouldn't be pub at all because it is only used in the same file in which it is defined.

**Comment by homersimpsons** [comment]
Should not we `use rustc_datastructures::cold_path` instead of duplicating the function ?

**Comment by zserik** [comment]
`rustc_arena` doesn't depend on `rustc_datastructures`, and it would be a really heavyweight dependency. I don't think that's worth it as the function is extremely trivial.
