### ISSUE TITLE
Prohibit specialized drops

### ISSUE THREAD

**Issue by sstewartgallus** [rust-lang/rust#8142]
**UPDATE:**

The plan for drops, as I recall, was to prohibit "specialized" drops, but this never got implemented. The idea is to require that impls of `Drop` meet special criteria such that the `Self`parameter must (a) be a nominal type (struct or enum); (b) have fresh type parameters for each type parameter of the type with (c) no additional bounds beyond those declared in the type declaration. Note that we will have to permit type bounds in type declarations, as well, which is to some extent a separate issue (also required for DST).

For example, this is legal:

```
struct Foo<T> { ... }

impl<T> Drop for Foo<T> { ... }
```

but this is not

```
impl<T:Send> Drop for Foo<T> { ... }
```

nor the example below.

**ORIGINAL:**

The following code prints `Dropping!`. This is wrong.
~~~rust
struct Foo<T>;

#[unsafe_destructor]
impl Drop for Foo<bool> {
    fn drop(&self) {
        println("Dropping!")
    }
}

fn main() {
    let _foo: Foo<()> = Foo;
}
~~~

**Comment by steveklabnik** [comment]
re-nominating, since `unsafe_destructor` may go away.

**Comment by pnkfelix** [comment]
Ah, this appears to be a more thorough version of  #21201.  

(Subtask of #8861)

**Comment by pnkfelix** [comment]
This blocks removing the `unsafe_destructor` feature gate.

calling 1.0 polish unless discussion of #22196 changes my opinion.

**Comment by pnkfelix** [comment]
okay I think this is the last thing I think is blocking #22196, so while it is categorized as "1.0 polish", it really would be good to get it in for the beta.  Looking at it now.

**Comment by pnkfelix** [comment]
I have something plausible put together; the main thing remaining is dealing with the fallout of either adding or removing the appropriate bounds everywhere in `libstd` in order to placate the pass.

**Comment by pnkfelix** [comment]
The pass I have put together seems to handle type-constraints properly, but it does not yet properly deal with region constraints.

For a little while I was not sure if this would be a problem, but I did eventually come up with a test case illustrating why one must ensure region constraints are indeed dealt with properly:

```rust
#![feature(unsafe_destructor)]

use std::cell::Cell;

struct InvalidateOnDrop {
    orig_value: &'static str,
    value: &'static str
}

// Note: Definition has no constraint relating 'b and 'a ...
struct P<'c, 'b:'c, 'a> {
    x: &'c Cell<&'b InvalidateOnDrop>,
    y: &'a InvalidateOnDrop
}

// ... but the Drop impl says 'a outlives 'b, and thus is
// able to copy `self.y` into `self.x`.  Havoc ensues below.
#[unsafe_destructor]
impl<'c, 'b:'c, 'a:'b> Drop for P<'c, 'b, 'a> {
    fn drop(&mut self) {
        self.x.set(self.y);
    }
}

#[allow(non_snake_case)]
fn InvalidateOnDrop(s: &'static str) -> InvalidateOnDrop {
    InvalidateOnDrop {
        orig_value: s,
        value: s,
    }
}

impl Drop for InvalidateOnDrop {
    fn drop(&mut self) {
        self.value = "invalidated";
    }
}

struct Loud<'l1, 'l2:'l1> {
    name: &'static str,
    value: &'l1 Cell<&'l2 InvalidateOnDrop>
}

#[unsafe_destructor]
impl<'l1, 'l2> Drop for Loud<'l1, 'l2> {
    fn drop(&mut self) {
        let orig = self.value.get().orig_value;
        let val = self.value.get().value;
        if orig == val {
            println!("dropping Loud {} pointing to {}", self.name, val);
        } else {
            println!("dropping Loud {} pointing to {} (orig: {})", self.name, val, orig);

        }
    }
}



fn main() {
    let b = InvalidateOnDrop("b");
    let c = Cell::new(&b);
    let _l1 = Loud { name: "l1", value: &c };
    let a = InvalidateOnDrop("a");
    let _p = P { x: &c, y: &a };

    let _l2 = Loud { name: "l2", value: &c };
    println!("Hello World");
}
```
[playpen](http://is.gd/g7Qh8s)

The above prints out (if you are lucky and other data corruption does not happen first):
```
Hello World
dropping Loud l2 pointing to b
dropping Loud l1 pointing to invalidated (orig: a)
```

thus illustrating that the `Loud` destructor observed a value in a post-drop state.  badness.

**Comment by pnkfelix** [comment]
ah sweet, I think I actually figured out how to do this (thank goodness I have `compare_method.rs` to look at).

And it took me way less time that it did for me to come up with above example -- I just needed the motivation!
