### ISSUE TITLE
ICE running druid examples (unwrap `JoinHandle::join`)

### ISSUE THREAD

**Issue by derekdreery** [rust-lang/rust#81439]
I suspect that something major has gone wrong with my OS (e.g. spawning threads isn't working), but since I got an ICE I thought I'd report it here. It might be worth handling thread spawn failure gracefully.

### Code

Download [`druid`](https://github.com/linebender/druid) and run `cargo run --example svg2`

### Meta

`rustc --version --verbose`:
```
rustc 1.49.0 (e1884a8e3 2020-12-29)
binary: rustc
commit-hash: e1884a8e3c3e813aada8254edfa120e85bf5ffca
commit-date: 2020-12-29
host: x86_64-unknown-linux-gnu
release: 1.49.0
```

### Error output

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/thread/mod.rs:1245:48
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
stack backtrace:
   0: rust_begin_unwind
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:495:5
   1: core::panicking::panic_fmt
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/panicking.rs:50:5
   3: std::thread::JoinHandle<T>::join
   4: rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals
   5: rustc_driver::RunCompiler::run
   6: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
   7: rustc_driver::catch_with_exit_code
   8: rustc_driver::main
   9: rustc_main::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.49.0 (e1884a8e3 2020-12-29) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
```

</p>
</details>

**Comment by Enselic** [comment]
Getting rustc to do something sensible on an OS where e.g. spawning threads does not work would be a gigantic undertaking, with microscopic benefit. There is 0% chance this will ever get fixed. Even if someone wanted to make a fix, how would they verify that their fix works?

@rustbot label P-low

**Comment by Enselic** [comment]
Closing for now (see https://github.com/rust-lang/rust/issues/81439#issuecomment-1650546457). Feel free to re-open if you get problems also in an OS where spawning threads works. In that case also please double-check that the step-by-step instructions on how to reproduce are still valid.
