### ISSUE TITLE
`cargo fmt` and other tools don't work for a linked toolchain.

### ISSUE THREAD

**Issue by vext01** [rust-lang/rust#81431]
This is derived from [this issue](https://github.com/rust-lang/rustup/issues/2548), in which we concluded that the bug should be filed against rustc, as it's an `x.py` problem.

In rustc:
```
$ ./x.py build --stage 1 src/tools/rustfmt/
...
$ find 'build' -name rustfmt
build/x86_64-unknown-linux-gnu/stage1-tools/x86_64-unknown-linux-gnu/release/rustfmt
build/x86_64-unknown-linux-gnu/stage1-tools-bin/rustfmt
build/x86_64-unknown-linux-gnu/stage0/share/doc/rustfmt
build/x86_64-unknown-linux-gnu/stage0/bin/rustfmt
build/tmp-rustbuild-tests/main/tmp/tarball/rustfmt
build/tmp-rustbuild-tests/main/tmp/tarball/rustfmt/B/image/share/doc/rustfmt
```

Then in a project using this toolchain via a rustup link:
```
$ cargo fmt
error: 'cargo-fmt' is not installed for the toolchain 'yk-stage1'
note: this is a custom toolchain, which cannot use `rustup component add`
help: if you built this toolchain from source, and used `rustup toolchain link`, then you may be able to build the component with `x.py`                                                                           
```

But note that `cp build/x86_64-unknown-linux-gnu/stage1-tools-bin/rustfmt build/x86_64-unknown-linux-gnu/stage1/bin/rustfmt` does not make this work either, so there is probably more to it?

Thanks

**Comment by vext01** [comment]
A load of comments from me. Hopefully all small.

In the interest of moving on, your next PR could add more tests?

**Comment by camelid** [comment]
(I think you posted that comment in the wrong place.)

**Comment by vext01** [comment]
Oops, yes.

**Comment by vext01** [comment]
Can anyone comment on what the correct fix for this might be?

I notice that if I copy `cargo-clippy` and `clippy-driver` from `stage1-tools-bin/` into `stage1/bin` then I'm able to run `cargo clippy` via the linked toolchain.

I initially considered changing rustup to add `stage1-tools-bin` to the PATH, but that seems incorrect as we would be adding something outside of the toolchain root to PATH.

So should x.py copy or move the binaries from `stage1-tools-bin` into `stage1/bin`?

I'm willing to (attempt to) do the work if we can agree on what the correct fix is.

**Comment by camelid** [comment]
> Can anyone comment on what the correct fix for this might be?

I'm not really knowledgeable about `x.py`. You might want to ask in `#t-compiler` on Zulip.

**Comment by jyn514** [comment]
> So should x.py copy or move the binaries from `stage1-tools-bin` into `stage1/bin`?

Yes, it should copy the binaries from stage1-tools-bin to stage1/bin.

**Comment by jyn514** [comment]
Mentoring instructions: Add a new argument to the `bootstrap_tool` macro that says whether the tool should be added to the sysroot, then copy it into the sysroot in https://github.com/rust-lang/rust/blob/4a7e2fbb7bfdb7ddcb65b6fcf23bb5b272e66d42/src/bootstrap/tool.rs#L223-L224

**Comment by WaffleLapkin** [comment]
I believe this will be fixed by https://github.com/rust-lang/rust/pull/102010, once we figure out some problems with clippy/fmt builds.
