### ISSUE TITLE
It's not possible to get the size of the offset from an arbitrary structure to it's field.

### ISSUE THREAD

**Issue by sstewartgallus** [rust-lang/rust#8144]
I have the following code at http://gitorious.org/p-x/p-x/blobs/master/src/gl.rs#line465 but it is very ugly. I have to create a data structure so I can calculate the offset from the structure to it's field, and pass it to the low level OpenGL code. To understand the issue better the documentation at http://www.khronos.org/opengles/sdk/docs/man/xhtml/glVertexAttribPointer.xml for the `glVertexAttribPointer` function may be useful.

~~~rust
impl <'self, S: Zero, T: AttributeValue> DisabledAttribute<'self, T> {
    pub fn vertex_pointer<C: Component<S, T>, State>(
        &self,
        _: &BufferTarget<'self, State, S>,    // Not used just needs to be bound
        normalized: bool,
        component: &C
    ) {
        let handle = self.raw_attribute;

        // Compute the stride, and offset
        let s = &Zero::zero();
        let t = component.access(s);
        let offset = borrow::to_uint(t) - borrow::to_uint(s);

        do self.linked_program.raw_program.context.send_and_recv {
            AttributeValue::vertex_attrib_pointer::<T>(
                handle,
                normalized,
                sys::size_of::<S>(),
                offset
            )
        }
    }
}
~~~
The definition of `Component`:
~~~rust
pub trait Component<S, T> {
    fn access<'r>(&self, &'r S) -> &'r T;
}
~~~
A sample implementation:
~~~rust
struct Positions;
impl Component<assets::Vertex, [f32, ..3]> for Positions {
    fn access<'r>(&self, s: &'r assets::Vertex) -> &'r [f32, ..3] {
        &s.position
    }
}
~~~

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#710
