### ISSUE TITLE
Do not append .lib extension to .res file on `cargo:rustc-link-lib=dylib=stuff.res`

### ISSUE THREAD

**Issue by rodrigocfd** [rust-lang/rust#81488]
In Windows, when trying to pass a [compiled resource script](https://docs.microsoft.com/en-us/windows/win32/menurc/about-resource-files) to the linker (I have MSVC build tools properly installed), I'm using the following line in my `build.rs`:

```
println!("cargo:rustc-link-lib=dylib=stuff.res");
```

The problem is that `stuff.res` is being renamed to `stuff.res.lib`, and since this file does not exist, the build fails. If I manually rename my file to `stuff.res.lib`, then it works.

Is it possible to handle this situation, maybe by identifying the provided extension and letting `.res` to pass?

Note: this feature request originated [from here](https://github.com/nabijaczleweli/rust-embed-resource/issues/28).

**Comment by ehuss** [comment]
Transferred to rust-lang/rust repository.  The naming convention is done by `rustc`.  (Unfortunately I'm not familiar with compiled resource scripts, so I am uncertain on how they should be integrated.)

**Comment by petrochenkov** [comment]
I think https://github.com/rust-lang/rfcs/pull/2951 (which is an accepted, but not yet implemented RFC) should help with this, through `verbatim` modifier specifically.

**Comment by petrochenkov** [comment]
Closing this issue, the `verbatim` modifier was implemented about 9 months ago, and https://github.com/rust-lang/rust/issues/81490 tracks its stabilization.

**Comment by rodrigocfd** [comment]
@petrochenkov I just tried to link a `.res` file and it still didn't work.

Build script:

```rust
fn main() {
	println!("cargo:rustc-link-lib=dylib=resources/resources.res");
}
```

Error message:

```
error: linking with `link.exe` failed: exit code: 1181
  |
  = note: LINK : fatal error LNK1181: cannot open input file 'resources\resources.res.lib'
```

It's still searching for `resources.res.lib`, instead of simply using `resources.res`.

What am I missing?

**Comment by petrochenkov** [comment]
@rodrigocfd 
> What am I missing?

The `+verbatim` modifier, I guess?
```rust
println!("cargo:rustc-link-lib=dylib:+verbatim=resources/resources.res");
```

**Comment by rodrigocfd** [comment]
> The `+verbatim` modifier, I guess?

Exactly that. It works now, thank you @petrochenkov.
