### ISSUE TITLE
std::collections provides a complexity for BTreeMap::predecessor but the function is not available

### ISSUE THREAD

**Issue by jbreitbart** [rust-lang/rust#81548]
I was just through https://doc.rust-lang.org/std/collections/#maps and noticed that it gives a complexity for the `predecessor` operation for BTreeMap, but that operation seems not to be available. I checked the map itself and its iterator. Is this a documentation bug or am I missing something?

**Comment by xfix** [comment]
This looks a lot like a cursor method, but cursor API for `BTreeMap` is long gone. I think we could write `range` instead of `predecessor` here.
