### ISSUE TITLE
ICE (Missing tokens for nt) on nightly with `stmt_expr_attributes` and `proc_macro_hygiene`

### ISSUE THREAD

**Issue by hyd-dev** [rust-lang/rust#81555]
I tried this code:
```rust
use proc_macro::TokenStream;

#[proc_macro_attribute]
pub fn breaks_rust(_: TokenStream, input: TokenStream) -> TokenStream {
    input
}
```
```rust
#![feature(stmt_expr_attributes, proc_macro_hygiene)]

use the_proc_macro_crate::breaks_rust;

#[breaks_rust]
fn main() {
    let _break;
    let rust = ();
    #[breaks_rust]
    _break = rust; // line 10
}
```

I expected the code to compile sucessfully, but got an ICE instead:
```
thread 'rustc' panicked at 'Missing tokens for nt at tests/ice.rs:10:5: 10:11 (#0): "_break"', compiler/rustc_parse/src/lib.rs:295:9
```

(This is procedural-macro-related. I can't reproduce without a procedural macro.)

This used to work and regressed in #79472.

<details><summary>Backtrace</summary>
<p>

```
   0: rust_begin_unwind
             at /rustc/b122908617436af187252572ed5db96850551380/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/b122908617436af187252572ed5db96850551380/library/std/src/panicking.rs:435:5
   2: rustc_parse::nt_to_tokenstream
   3: rustc_expand::base::Annotatable::into_tokens
   4: rustc_expand::expand::MacroExpander::fully_expand_fragment
   5: rustc_expand::expand::MacroExpander::expand_crate
   6: rustc_interface::passes::configure_and_expand_inner
   7: rustc_interface::passes::configure_and_expand::{{closure}}
   8: rustc_data_structures::box_region::PinnedGenerator<I,A,R>::new
   9: rustc_interface::passes::configure_and_expand
  10: rustc_interface::queries::Queries::expansion
  11: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  12: rustc_span::with_source_map
  13: rustc_interface::interface::create_compiler_and_run
```
</p>
</details>

cc #15701 #54727

**Comment by camelid** [comment]
If this code only works on nightly, then I don't think it's a `regression-from-stable-to-nightly`. However, we don't have a `regression-from-nightly-to-nightly` label, so ...

**Comment by Aaron1011** [comment]
This will be fixed by https://github.com/rust-lang/rust/pull/81286, which handles attributes on expressions in a more systematic way.

As a side now, `#[breaks_rust] _break = rust;` is currently parsed as  `<#[breaks_rust _break> = rust;`

**Comment by camelid** [comment]
> This will be fixed by #81286, which handles attributes on expressions in a more systematic way.

Do you want to add `Fixes #81555` to that PR then?

**Comment by Aaron1011** [comment]
We'll still need to add a regression test.

**Comment by rylev** [comment]
Assigning P-high as [discussed as part of the Prioritization Working Group procedure](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2381555.20ICE.20(Missing.20tokens.20for.20nt).20on.20nightly.20with.20.60stmt_ex.E2.80.A6) and removing I-prioritize.
