### ISSUE TITLE
Doc comments for TyCtxt has extra query description in brackets

### ISSUE THREAD

**Issue by JulianKnodt** [rust-lang/rust#81579]
The doc comments for some queries have extra bracketed info which should not be present:
![image](https://user-images.githubusercontent.com/7675847/106372112-72310400-633a-11eb-9ff2-0e3537b44450.png)

**Comment by jyn514** [comment]
@Julian-Wollersberger this is intentional - those docs are autogenerated from the query description, not written by a human.

**Comment by JulianKnodt** [comment]
ah ok, I just assumed that since they had a description and the brackets it was unintentional, I'll close this then
