### ISSUE TITLE
chrono panics on a valid input string

### ISSUE THREAD

**Issue by omayerg** [rust-lang/rust#81587]
```rust
 use chrono::format;

fn main() {
    let p = &mut format::Parsed::new();
    format::parse(p, "MONYAŽA Šander`",
    format::StrftimeItems::new("%A, %e-%h-%y %H:%M:%S"));
    
    println!("No panic");
}
```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=c6a8ef89067d6e6c1b87937c60b0a04c))

Expected null result, but actually it panics.
It seems chrono parser misses the case where a string starts with a valid datetime part, e.g. SUN, MON, TUE... but then have non-ascii characters. For example, running the above string without letting it start with any three letters that represents a day of week doesn't panic.

**Comment by ivan770** [comment]
Is this issue related to Rust compiler itself? You might want to re-open it in https://github.com/chronotope/chrono.
