### ISSUE TITLE
Detect iterators going out of scope and suggest collecting

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#81584]
Given a situation where an iterator is [constructed inside of a scope where the data is being returned, we currently emit](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=3ca34625b7eaf1c44d9ddb7b3840a69e):

```
error[E0515]: cannot return value referencing function parameter `y`
 --> src/main.rs:4:18
  |
4 |         .map(|y| y.iter().map(|x| x + 1))
  |                  -^^^^^^^^^^^^^^^^^^^^^^
  |                  |
  |                  returns a value referencing data owned by the current function
  |                  `y` is borrowed here
```

We should suggest using `.collect()` in these cases.

**Comment by leonardo-m** [comment]
Or flatten/flat_map?

**Comment by estebank** [comment]
I want for us to detect cases of trying to operate on iterators of iterators because the only option then is to allocate or completely rework the logic. The former will help newcomers, experts will know enough to try the later.

**Comment by the8472** [comment]
Couldn't we still recommend both? Recommending bad practices seems suboptimal.
