### ISSUE TITLE
Rustdoc title off in mobile

### ISSUE THREAD

**Issue by pickfire** [rust-lang/rust#81597]
![image](https://user-images.githubusercontent.com/4687791/106385022-05d10600-6409-11eb-9b21-ca18015c2020.png)

The nightly title text looks off in small phones.

https://github.com/rust-lang/rust/pull/81592#issuecomment-770380620

cc @GuillaumeGomez

**Comment by Nemo157** [comment]
1.49 is actually stable :wink:

**Comment by pickfire** [comment]
@Nemo157 Ah, haha. It doesn't matter either way, I am talking about the title.
