### ISSUE TITLE
telemetry service that tabulates top warnings, complaints

### ISSUE THREAD

**Issue by graydon** [rust-lang/rust#8161]
This is a bit of a weird / wishlist item, but it would be nice to be able to gather statistics on how often our users hit which errors, and how much they like them vs. loathe them.

This would be a relative of #2092 in which we have a code reserved for each warning/error/lint message (which we never reuse). Rustc would be configured to keep local tabulation in your homedir while you work of a few basic statistics (codebase size, number of unique files processed, number of runs of the compiler, resource usage) and the number of occurrences of a given message, along with a pair of commands (say: `rustc yay` and `rustc boo`) that mark your approval or disapproval of the most recent error message. Periodically, or on demand, you could submit your tabulated set to a telemetry service. This way we could get directed feedback of the sorts of problems people are having while using the compiler as well as whether they appreciate or feel annoyed by various forms of error message.

(Other suggestions welcome; was thinking `win` vs. `fail`, or perhaps some variant of `derp`, `wat` or `fuuuuuu` but couldn't think of suitable paired positive-affirmation phrases, and in any case they seem a little unkind.)

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#629
