### ISSUE TITLE
Non-unit variant of an enum type casts to a random number

### ISSUE THREAD

**Issue by worldmaker18349276** [rust-lang/rust#81616]
I tried this code:

```rust
enum Enum {
    X(bool),
}

fn main() {
    println!("{:x}", Enum::X as i32);
}
```

I get random numbers every time I run.

### Meta
`rustc --version --verbose`:
```
rustc 1.45.1 (c367798cf 2020-07-26)
binary: rustc
commit-hash: c367798cfd3817ca6ae908ce675d1d99242af148
commit-date: 2020-07-26
host: x86_64-unknown-linux-gnu
release: 1.45.1
LLVM version: 10.0
```
It also works in the latest nightly version:
```
rustc 1.51.0-nightly (04caa632d 2021-01-30)
binary: rustc
commit-hash: 04caa632dd10c2bf64b69524c7f9c4c30a436877
commit-date: 2021-01-30
host: x86_64-unknown-linux-gnu
release: 1.51.0-nightly
LLVM version: 11.0.1
```

**Comment by jfrimmel** [comment]
This is due to the fact, that `Enum::X` is a kind of function pointer, which you take the address of (which isindeed kind of random).

If you try `Enum::X(false) as u32` it fails to compile as expected.

**Comment by worldmaker18349276** [comment]
So this is intentional behavior?
The compiler tries to prevent conversion between non-primitive types, but this is okay?

**Comment by jonas-schievink** [comment]
Yes, function pointers can be cast to integers
