### ISSUE TITLE
Small error in "introduce explicit lifetime bound" suggestion

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#81650]
[We currently give the following output](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=81c95ddcd1e232876d21dac767919959):

```
error[E0311]: the parameter type `T` may not live long enough
  --> src/main.rs:25:11
   |
25 |     scope.spawn(move |_| {
   |           ^^^^^
   |
note: the parameter type `T` must be valid for the anonymous lifetime #2 defined on the function body at 24:1...
  --> src/main.rs:24:1
   |
24 | fn play_with<T: Animal + Send>(scope: &Scope, animal: T) {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
note: ...so that the type `[closure@src/main.rs:25:17: 27:6]` will meet its required lifetime bounds
  --> src/main.rs:25:11
   |
25 |     scope.spawn(move |_| {
   |           ^^^^^
help: consider introducing an explicit lifetime bound
   |
24 | fn play_with<'a, T: 'a + Animal + Send>(scope: &Scope, animal: T) {
25 |     scope.spawn + 'a(move |_| {
   |
```

The suggestion has a spurious extra `+ 'a` in line 25 that shouldn't be there.

**Comment by 0yoyoyo** [comment]
Should I just remove wrong `+ 'a` in the suggestion? In this case, we have to add explicit lifetime to `Scope` to resolve the error.
like this:

```rust
fn play_with<'a, T: 'a + Animal + Send>(scope: &Scope<'a>, mut animal: T) {
    scope.spawn(move |_| {
        animal.sleep();
    });
}
```

Just removing `+ 'a` is a little confusing?

**Comment by estebank** [comment]
@0yoyoyo ideally we would indeed suggest what you're proposing, but I can see how it might be hard. If the best we can do is change the structured suggestion with just a `help` note, let's leave this ticket open to eventually deal with the full  suggestion. In order to do the right suggestion you might have to look for all types in the parameter list and look for structs and traits with implicit (not written out) lifetimes and point them out.

**Comment by 0yoyoyo** [comment]
@estebank I agree it is difficult. And I think just removing `+ 'a` is enough in the scope of this issue. (I wanted to make sure whether you expect for me to make full suggestion.)
I'll create PR to remove wrong `+ 'a`.

**Comment by 0yoyoyo** [comment]
@estebank Can this issue be closed?
