### ISSUE TITLE
Tracking Issue for vec_extend_from_within

### ISSUE THREAD

**Issue by KodrAus** [rust-lang/rust#81656]
Feature gate: `#![feature(vec_extend_from_within)]`

This is a tracking issue for `Vec::vec_extend_from_within`, which allows copying elements from a range to the end: 

```rust
#![feature(vec_extend_from_within)]

let mut vec = vec![0, 1, 2, 3, 4];

vec.extend_from_within(2..);
assert_eq!(vec, [0, 1, 2, 3, 4, 2, 3, 4]);

vec.extend_from_within(..2);
assert_eq!(vec, [0, 1, 2, 3, 4, 2, 3, 4, 0, 1]);

vec.extend_from_within(4..8);
assert_eq!(vec, [0, 1, 2, 3, 4, 2, 3, 4, 0, 1, 4, 2, 3, 4]);
```

### Public API

```rust
impl<T: Clone, A: Allocator> Vec<T, A> {
    pub fn extend_from_within<R>(&mut self, src: R)
    where
        R: RangeBounds<usize>;
}
```

### Steps / History

- [x] Implementation: #79015
- [x] Final commenting period (FCP)
- [ ] Stabilization PR

### Unresolved Questions

- None yet.

**Comment by Amanieu** [comment]
@rfcbot merge
