### ISSUE TITLE
rustdoc: Include attributes in item `[src]` destination?

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#81691]
Currently when you click on the `[src]` link for an item, you are taken to the first line of the item after its attributes. For example, the `[src]` button for [`Box::new()`](https://doc.rust-lang.org/std/boxed/struct.Box.html#method.new) goes to [here](https://doc.rust-lang.org/src/alloc/boxed.rs.html#177-179):

```rust
    pub fn new(x: T) -> Self {
        box x
    }
```

Is this preferable, or would we rather link to [here](https://doc.rust-lang.org/src/alloc/boxed.rs.html#166-179)?

```rust
    /// Allocates memory on the heap and then places `x` into it.
    ///
    /// This doesn't actually allocate if `T` is zero-sized.
    ///
    /// # Examples
    ///
    /// ```
    /// let five = Box::new(5);
    /// ```
    #[stable(feature = "rust1", since = "1.0.0")]
    #[inline(always)]
    pub fn new(x: T) -> Self {
        box x
    }
```

**Comment by camelid** [comment]
I think in some situations, like for type definitions, it would be better to include the attributes so you can see any `#[derive]`s, but for other situations it might be overwhelming (especially in `std`) to show all the attributes and docs.

**Comment by GuillaumeGomez** [comment]
I personally think it's fine. :)

**Comment by camelid** [comment]
Fine the way it is now or fine to include the attributes?

**Comment by GuillaumeGomez** [comment]
To not include the attributes into the line numbers for the `[src]` link.

**Comment by camelid** [comment]
Yeah, it's not a big deal but I think it would be better overall to include the attributes since they are part of the definition (e.g., `derive`s).

**Comment by Manishearth** [comment]
I think it's fine as is, because the full list of attributes usually includes docs (you can ignore them, but they're sometimes _above_ docs), and _you just came there from docs_. When I click src I want to see the actual code and scroll around.

**Comment by jyn514** [comment]
If there's a way to include the span of attributes *following doc-comments*, that might be useful. But it sounds more complicated than it needs to be.

**Comment by Manishearth** [comment]
> If there's a way to include the span of attributes _following doc-comments_, that might be useful. But it sounds more complicated than it needs to be.

idk, this feels like a half measure, since sometimes i've seen attributes on _both sides_, so now you _think_ you have all the attributes but you don't. I'm not a fan, better to scope on the item def only and everyone knows they can scroll up

**Comment by camelid** [comment]
Should this be closed? It seems unlikely that we'll end up changing this.
