### ISSUE TITLE
Static libraries fail to build with x86_64-pc-windows-gnu with choco mingw installed (with cause of bug)

### ISSUE THREAD

**Issue by pmeredit** [rust-lang/rust#81731]
We are building a static library on x86_64-pc-windows-gnu on a system that has a choco installed mingw using
cargo 1.49.0 (d00d64df9 2020-12-05). 

I expected to see this happen: We expect it to build

Instead, this happened: we get a missing library libgcc_eh. We have seen other examples of this issue through web search, but here is the actual output from gcc:

```
"x86_64-w64-mingw32-gcc" "-fno-use-linker-plugin" "-Wl,--nxcompat" "-m64" "C:\\Users\\Administrator\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\rsbegin.o" 
"-L" "C:\\Users\\Administrator\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib" "C:\\cygwin\\home\\Administrator\\mongosql-rs\\target\\debug\\build\\winapi-x86_64-pc-windows-gnu-62a1eb56e014856f\\build_script_build-62a1eb56e014856f.build_script_build.d37nv6y6-cgu.0.rcgu.o" "C:\\cygwin\\home\\Administrator\\mongosql-rs\\target\\debug\\build\\winapi-x86_64-pc-windows-gnu-62a1eb56e014856f\\build_script_build-62a1eb56e014856f.build_script_build.d37nv6y6-cgu.1.rcgu.o" "C:\\cygwin\\home\\Administrator\\mongosql-rs\\target\\debug\\build\\winapi-x86_64-pc-windows-gnu-62a1eb56e014856f\\build_script_build-62a1eb56e014856f.build_script_build.d37nv6y6-cgu.10.rcgu.o" "C:\\cygwin\\home\\Administrator\\mongosql-rs\\target\\debug\\build\\winapi-x86_64-pc-windows-gnu-62a1eb56e014856f\\build_script_build-62a1eb56e014856f.build_script_build.d37nv6y6-cgu.11.rcgu.o" "C:\\cygwin\\home\\Administrator\\mongosql-rs\\target\\debug\\build\\winapi-x86_64-pc-windows-gnu-62a1eb56e014856f\\build_script_build-62a1eb56e014856f.build_script_build.d37nv6y6-cgu.12.rcgu.o" "C:\\cygwin\\home\\Administrator\\mongosql-rs\\target\\debug\\build\\winapi-x86_64-pc-windows-gnu-62a1eb56e014856f\\build_script_build-62a1eb56e014856f.build_script_build.d37nv6y6-cgu.13.rcgu.o" "C:\\cygwin\\home\\Administrator\\mongosql-rs\\target\\debug\\build\\winapi-x86_64-pc-windows-gnu-62a1eb56e014856f\\build_script_build-62a1eb56e014856f.build_script_build.d37nv6y6-cgu.14.rcgu.o" "C:\\cygwin\\home\\Administrator\\mongosql-rs\\target\\debug\\build\\winapi-x86_64-pc-windows-gnu-62a1eb56e014856f\\build_script_build-62a1eb56e014856f.build_script_build.d37nv6y6-cgu.15.rcgu.o" "C:\\cygwin\\home\\Administrator\\mongosql-rs\\target\\debug\\build\\winapi-x86_64-pc-windows-gnu-62a1eb56e014856f\\build_script_build-62a1eb56e014856f.build_script_build.d37nv6y6-cgu.2.rcgu.o" "C:\\cygwin\\home\\Administrator\\mongosql-rs\\target\\debug\\build\\winapi-x86_64-pc-windows-gnu-62a1eb56e014856f\\build_script_build-62a1eb56e014856f.build_script_build.d37nv6y6-cgu.3.rcgu.o" "C:\\cygwin\\home\\Administrator\\mongosql-rs\\target\\debug\\build\\winapi-x86_64-pc-windows-gnu-62a1eb56e014856f\\build_script_build-62a1eb56e014856f.build_script_build.d37nv6y6-cgu.4.rcgu.o" "C:\\cygwin\\home\\Administrator\\mongosql-rs\\target\\debug\\build\\winapi-x86_64-pc-windows-gnu-62a1eb56e014856f\\build_script_build-62a1eb56e014856f.build_script_build.d37nv6y6-cgu.5.rcgu.o" "C:\\cygwin\\home\\Administrator\\mongosql-rs\\target\\debug\\build\\winapi-x86_64-pc-windows-gnu-62a1eb56e014856f\\build_script_build-62a1eb56e014856f.build_script_build.d37nv6y6-cgu.6.rcgu.o" "C:\\cygwin\\home\\Administrator\\mongosql-rs\\target\\debug\\build\\winapi-x86_64-pc-windows-gnu-62a1eb56e014856f\\build_script_build-62a1eb56e014856f.build_script_build.d37nv6y6-cgu.7.rcgu.o" "C:\\cygwin\\home\\Administrator\\mongosql-rs\\target\\debug\\build\\winapi-x86_64-pc-windows-gnu-62a1eb56e014856f\\build_script_build-62a1eb56e014856f.build_script_build.d37nv6y6-cgu.8.rcgu.o" "C:\\cygwin\\home\\Administrator\\mongosql-rs\\target\\debug\\build\\winapi-x86_64-pc-windows-gnu-62a1eb56e014856f\\build_script_build-62a1eb56e014856f.build_script_build.d37nv6y6-cgu.9.rcgu.o" "-o" "C:\\cygwin\\home\\Administrator\\mongosql-rs\\target\\debug\\build\\winapi-x86_64-pc-windows-gnu-62a1eb56e014856f\\build_script_build-62a1eb56e014856f.exe" "C:\\cygwin\\home\\Administrator\\mongosql-rs\\target\\debug\\build\\winapi-x86_64-pc-windows-gnu-62a1eb56e014856f\\build_script_build-62a1eb56e014856f.4b2qgyy9xymnw0fg.rcgu.o" "-Wl,--gc-sections" "-nodefaultlibs" "-L" "C:\\cygwin\\home\\Administrator\\mongosql-rs\\target\\debug\\deps" "-L" "C:\\Users\\Administrator\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib" "-Wl,--start-group" "-Wl,-Bstatic" "C:\\Users\\Administrator\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libstd-8394c9398cbadee5.rlib" "C:\\Users\\Administrator\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libpanic_unwind-886e4f572a6d227c.rlib" "C:\\Users\\Administrator\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libobject-17cf826d0f7d2ed3.rlib" "C:\\Users\\Administrator\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libaddr2line-0dad5a98c26b9739.rlib" "C:\\Users\\Administrator\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libgimli-dfab679e0565d217.rlib" "C:\\Users\\Administrator\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\librustc_demangle-9f6866b4336a1d1c.rlib" "C:\\Users\\Administrator\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libhashbrown-81ade66b9e4c9cd5.rlib" "C:\\Users\\Administrator\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\librustc_std_workspace_alloc-4149a301273ebf0c.rlib" "C:\\Users\\Administrator\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libunwind-738a3de7ad0cd3a3.rlib" "C:\\Users\\Administrator\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcfg_if-06d418ce9254f841.rlib" "C:\\Users\\Administrator\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\liblibc-7c3291a8d67347b3.rlib" "C:\\Users\\Administrator\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\liballoc-9f2b7229edc9025e.rlib" "C:\\Users\\Administrator\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\librustc_std_workspace_core-4ae0cac901a4e3c1.rlib" "C:\\Users\\Administrator\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcore-9e39cfd0b85a4b6e.rlib" "-Wl,--end-group" "C:\\Users\\Administrator\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcompiler_builtins-de70f57e5c136950.rlib" "-Wl,-Bdynamic" "-ladvapi32" "-lws2_32" "-luserenv" "-lgcc_eh" "-l:libpthread.a" "-lmsvcrt" "-lmingwex" "-lmingw32" "-lgcc" "-lmsvcrt" "-luser32" "-lkernel32" "C:\\Users\\Administrator\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\rsend.o"
  = note: c:/programdata/chocolatey/lib/mingw/tools/install/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lgcc_eh
```

The actual problem here is that only `-L" "C:\\Users\\Administrator\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib"` is specified, when libgcc_eh is actually in 
`-L" "C:\\Users\\Administrator\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\self-contained"`

Setting the LD_LIBRARY_PATH to contain self-contained fixes this:

`export LIBRARY_PATH=$(cygpath -w /cygdrive/c/Users/Administrator/.rustup/toolchains/stable-x86_64-pc-windows-gnu/lib/rustlib/x86_64-pc-windows-gnu/lib/self-contained/)`

(on cygwin)

The problem is it is picking up the libraries for the newer installed mingw, which no longer has libgcc_eh

### Meta

`rustc --version --verbose`:
```
rustc 1.49.0 (e1884a8e3 2020-12-29)
binary: rustc
commit-hash: e1884a8e3c3e813aada8254edfa120e85bf5ffca
commit-date: 2020-12-29
host: x86_64-pc-windows-gnu
release: 1.49.0
```

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by pmeredit** [comment]
A further question would be how to get cargo to use the choco mingw toolchain. We want to link this library into a go program, which expects a far newer version of mingw than 6.3.0 (the self-contained version used by rust).

**Comment by mati865** [comment]
> The problem is it is picking up the libraries for the newer installed mingw, which no longer has libgcc_eh

Newer DWARF/SEH mingw-w64 toolchains still do use `libgcc_eh`.
Sounds like you have SJLJ in `PATH? In that case you can use `RUSTFLAGS='-C link-self-contained=true'` to force Rust shipped mingw-w64 toolchain.

> A further question would be how to get cargo to use the choco mingw toolchain.

Rust will use `{i686,x86_64}-w64-mingw32-gcc` from `PATH` as the first choice and fallback to shipped one as second choice.
You can force system toolchain with `RUSTFLAGS='-C link-self-contained=false'.

**Comment by pmeredit** [comment]
@mati865 Yes, we definitely have SJLJ in path, the libgcc.a file being picked up is all SJLJ symbols.

**Comment by pmeredit** [comment]
@mati865 I'm still getting undefined reference to `_Unwind_Resume` here. Can we just not build against SJLJ?

**Comment by mati865** [comment]
@pmeredit only Dwarf-2 (i686) and SEH (x86_64) exceptions are supported for windows-gnu toolchains. You can try with `RUSTFLAGS='-C panic=abort'` but it might not help.

**Comment by pmeredit** [comment]
@mati865 Thanks for the info. We'd already tried `panic=abort`, it still left a few references to `_Unwind_Resume`

**Comment by rychipman** [comment]
> Rust will use {i686,x86_64}-w64-mingw32-gcc from PATH as the first choice and fallback to shipped one as second choice.
You can force system toolchain with RUSTFLAGS='-C link-self-contained=false'.

Are there flags that can be set to print out all of the invocations for binaries exec'ed during compilation? I'm compiling my `staticlib` project with `RUSTFLAGS='-C link-self-contained=yes -Z print-link-args' cargo build`, but it's not showing any linker invocations for my crate (only dependencies).

**Comment by mati865** [comment]
@rychipman static libraries aren't linked together from objects like dynamic libraries. Instead they are just an archive that contains files assembled by the compiler.

**Comment by rychipman** [comment]
Ah, ok; I saw that the `ar` to use is configurable, and assumed (perhaps incorrectly) that this was its purpose.

- Does cargo not use `ar` to assemble static libraries?
- If `ar` isn't used for assembling static libs, then what is it used for?
- Are the static libs (`.a` files) from the `winapi` crate included in the static lib generated by my crate? If so, is `rustc` responsible for putting them there?

I have a few different MinGW installations on my machine (Rust's self-contained version, one that is installed when the host is provisioned, and one installed via chocolatey), and my end goal is to verify that all of the MinGW stuff being used (compiler, libraries, linker, etc) are coming from the same MinGW installation.

**Comment by mati865** [comment]
> Does cargo not use ar to assemble static libraries?

AFAIK rustc uses LLVM to do it.

> * If `ar` isn't used for assembling static libs, then what is it used for?

From docs: `This option is deprecated and unused`.

> 
> * Are the static libs (`.a` files) from the `winapi` crate included in the static lib generated by my crate? If so, is `rustc` responsible for putting them there?

I don't know how winapi crate works.

---
I also don't see how these questions are related to the original issue here.

**Comment by ChrisDenton** [comment]
It's been a few years since anyone commented on this. Is there still an issue here?

**Comment by mati865** [comment]
Dunno if there is anything to act on, the user was trying to use unsupported toolchain (different exceptions handling model).
