### ISSUE TITLE
Soundness issue in `Zip::next()` specialization

### ISSUE THREAD

**Issue by Qwaz** [rust-lang/rust#81740]
https://github.com/rust-lang/rust/blob/e708cbd91c9cae4426d69270248362b423324556/library/core/src/iter/adapters/zip.rs#L191-L211

https://github.com/rust-lang/rust/blob/e708cbd91c9cae4426d69270248362b423324556/library/core/src/iter/adapters/zip.rs#L395-L396

There is a panic safety issue in `Zip::next()` that allows to call `__iterator_get_unchecked()` to the same index twice. `__iterator_get_unchecked()` is called at line 204 and the `index` is updated at line 206. If line 204 panics, the index is not updated and the subsequent `next()` call will use the same index for `__iterator_get_unchecked()`. This violates the second safety requirement of `TrustedRandomAccess`.

Here is a [playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=4634eb8e3ba2ea945e7eebe76f387ae0) that demonstrates creating two mutable references to the same memory location without using unsafe Rust.

**Comment by Qwaz** [comment]
The bug fixed by this PR seems to have the same consequence, but it didn't get the unsound label.
https://github.com/rust-lang/rust/pull/80670

**Comment by sdroege** [comment]
Seems like this would be fixed by simply doing the same as in the first branch of the `if` and incrementing the `self.index` beforehand. Are you creating a PR for this?

**Comment by Qwaz** [comment]
> Seems like this would be fixed by simply doing the same as in the first branch of the `if` and incrementing the `self.index` beforehand.

Agreed :)

> Are you creating a PR for this?

Not in the meantime. Fill free to work on a PR if you are interested.

**Comment by sdroege** [comment]
> Not in the meantime. Fill free to work on a PR if you are interested.

Sure, why not :)

**Comment by apiraino** [comment]
Assigning `P-high` as discussed as part of the [Prioritization Working Group procedure](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2381740.20Soundness.20issue.20in.20.60Zip.3A.3Anext().60.20specialization) and removing `I-prioritize`.
