### ISSUE TITLE
Tracking Issue for Add Result<Result<T, E1>, E2>::transpose_err -> Result<Result<T, E2>, E1>

### ISSUE THREAD

**Issue by yshui** [rust-lang/rust#81750]
Feature gate: `#![feature(transpose_err)]`

This is a tracking issue for adding Result<Result<T, E1>, E2>::transpose_err which transpose the error type in a nested Result type.

### Public API

```rust
impl<T, E1, E2> Result<Result<T, E1>, E2> {
    pub fn transpose_err(self) -> Result<Result<T, E2>, E1>;
}
```

### Steps / History

- [x] Implementation: #81749
- [ ] Final commenting period (FCP)
- [ ] Stabilization PR

### Unresolved Questions

- None yet.

**Comment by jyn514** [comment]
This feature was rejected, so I don't think it makes sense to keep a tracking issue for it. https://github.com/rust-lang/rust/pull/81749#pullrequestreview-584744664
