### ISSUE TITLE
Cannot bootstrap rustfmt in-tree: unknown feature `array_value_iter_slice`

### ISSUE THREAD

**Issue by rkowalewski** [rust-lang/rust#81787]
Bootstrapping rust nightly fails when building `rustfmt`. I suppose this results from merging #80470, where the [rustc-ap-rustc_arena](https://libraries.io/cargo/rustc-ap-rustc_arena) crate has been modified (remove some features).

Cargo.lock still uses an old version (v697.0.0). However, it should be v702.0.0.

I build on OpenBSD current. For reference, I attached my [build.log](https://github.com/rust-lang/rust/files/5932422/build.log).

**Comment by jyn514** [comment]
I think this is expected behavior in some sense - rustfmt is maintained in a submodule and breaks occasionally, that's why it's not available on all nightlies. https://forge.rust-lang.org/infra/docs/rustc-ci.html#toolstate-to-support-allowed-failures

**Comment by rkowalewski** [comment]
OK, since I am not yet very familiar with the toolchain of Rust. Is there a simple workaround if I build rust nightly in-tree?

**Comment by jyn514** [comment]
You can exclude rustfmt from being built (`--exclude rustfmt` or just don't add it to the list of tools in config.toml).

**Comment by rkowalewski** [comment]
Thank you that solved the issue for me. Feel free to close the issue.
