### ISSUE TITLE
rustc attempts to use old version of msvc for linking instead of new version of msvc

### ISSUE THREAD

**Issue by lvyitian** [rust-lang/rust#81796]
error: linking with `link.exe` failed: exit code: 0xc0000135
  |
  = note: "E:\\Microsoft Visual Studio 2012 Express\\VC\\bin\\link.exe" "/NOLOGO" "/NXCOMPAT" "/LARGEADDRESSAWARE" "/SAFESEH" "/LIBPATH:C:\\Users\\***\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib" "C:\\Users\\***\\IdeaProjects\\rtpwq\\target\\debug\\deps\\rtpwq.17opqmq9sse2tn3p.rcgu.o" "C:\\Users\\***\\IdeaProjects\\rtpwq\\target\\debug\\deps\\rtpwq.1jtiv0ygahdzq8w.rcgu.o" "C:\\Users\\***\\IdeaProjects\\rtpwq\\target\\debug\\deps\\rtpwq.2k16ialdiq4341ce.rcgu.o" "C:\\Users\\***\\IdeaProjects\\rtpwq\\target\\debug\\deps\\rtpwq.2mpu8qkpa0663us0.rcgu.o" "C:\\Users\\***\\IdeaProjects\\rtpwq\\target\\debug\\deps\\rtpwq.3i79iat844wb4d92.rcgu.o" "C:\\Users\\***\\IdeaProjects\\rtpwq\\target\\debug\\deps\\rtpwq.4cqvr3khgv3ngc86.rcgu.o" "C:\\Users\\***\\IdeaProjects\\rtpwq\\target\\debug\\deps\\rtpwq.fayy42ndo76p90d.rcgu.o" "C:\\Users\\***\\IdeaProjects\\rtpwq\\target\\debug\\deps\\rtpwq.s5yo54eqoh9m6fh.rcgu.o" "/OUT:C:\\Users\\***\\IdeaProjects\\rtpwq\\target\\debug\\deps\\rtpwq.exe" "C:\\Users\\***\\IdeaProjects\\rtpwq\\target\\debug\\deps\\rtpwq.4mi7froypijx0bqz.rcgu.o" "/OPT:REF,NOICF" "/DEBUG" "/NATVIS:C:\\Users\\***\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\etc\\intrinsic.natvis" "/NATVIS:C:\\Users\\***\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\etc\\liballoc.natvis" "/NATVIS:C:\\Users\\***\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\etc\\libcore.natvis" "/NATVIS:C:\\Users\\***\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\etc\\libstd.natvis" "/LIBPATH:C:\\Users\\***\\IdeaProjects\\rtpwq\\target\\debug\\deps" "/LIBPATH:C:\\Users\\***\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib" "C:\\Users\\***\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\libstd-8b40e152c52992e1.rlib" "C:\\Users\\***\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\libpanic_unwind-4a6ee51bbae925af.rlib" "C:\\Users\\***\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\librustc_demangle-be5ccab3cb59166b.rlib" "C:\\Users\\***\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\libhashbrown-69685422dfc583ce.rlib" "C:\\Users\\***\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\librustc_std_workspace_alloc-e94f6f6a978c60e4.rlib" "C:\\Users\\***\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\libunwind-cde31c6636f0e123.rlib" "C:\\Users\\***\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\libcfg_if-f983ad93140dc0ce.rlib" "C:\\Users\\***\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\liblibc-54ada1839c8a8aba.rlib" "C:\\Users\\***\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\liballoc-ea319ffba04490ef.rlib" "C:\\Users\\***\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\librustc_std_workspace_core-d136065bdcb41c1c.rlib" "C:\\Users\\***\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\libcore-92dacfe5bc78ffb7.rlib" "C:\\Users\\***\\.rustup\\toolchains\\stable-i686-pc-windows-msvc\\lib\\rustlib\\i686-pc-windows-msvc\\lib\\libcompiler_builtins-6f156deae1488988.rlib" "advapi32.lib" "ws2_32.lib" "userenv.lib" "msvcrt.lib"
  = note: 

note: `link.exe` returned an unexpected error

note: the Visual Studio build tools may need to be repaired using the Visual Studio installer

note: or a necessary component may be missing from the "C++ build tools" workload

error: aborting due to previous error

I have already installed Visual Studio 2017 C++ build tools but it attempts to use 2012

**Steps**
1.Install VS2012 and VS2017
2.cargo run

**Notes**

Output of `cargo version`: cargo 1.49.0 (d00d64df9 2020-12-05)

**Comment by ehuss** [comment]
Transferred to the rust-lang/rust repository, since this is a rustc issue (or more specifically with `cc`), or your installation of visual studio may be incomplete.  Unfortunately beyond the `VCINSTALLDIR`, it may be difficult to diagnose because it uses COM to discover the location of visual studio version 15+.  It also looks like you are using i686, which is fairly rare, and I'm uncertain if you need to do something special to install i686 support in visual studio.  You may also get more traction on one of the user forums.

**Comment by lvyitian** [comment]
> Transferred to the rust-lang/rust repository, since this is a rustc issue (or more specifically with `cc`), or your installation of visual studio may be incomplete. Unfortunately beyond the `VCINSTALLDIR`, it may be difficult to diagnose because it uses COM to discover the location of visual studio version 15+. It also looks like you are using i686, which is fairly rare, and I'm uncertain if you need to do something special to install i686 support in visual studio. You may also get more traction on one of the user forums.

rustc -C linker=xxx source can work properly.

**Comment by lvyitian** [comment]
> Transferred to the rust-lang/rust repository, since this is a rustc issue (or more specifically with `cc`), or your installation of visual studio may be incomplete. Unfortunately beyond the `VCINSTALLDIR`, it may be difficult to diagnose because it uses COM to discover the location of visual studio version 15+. It also looks like you are using i686, which is fairly rare, and I'm uncertain if you need to do something special to install i686 support in visual studio. You may also get more traction on one of the user forums.

I manually create a environment variable called `VCINSTALLDIR` and set it to the new install directory but now there is a new error:
`
= note: Non-UTF-8 output: LINK : fatal error LNK1181: \xce\xde\xb7\xa8\xb4\xf2\xbf\xaa\xca\xe4\xc8\xeb\xce\xc4\xbc\xfe\xa1\xb0advapi32.lib\xa1\xb1\r\n

error: aborting due to previous error
`

**Comment by lvyitian** [comment]
> Transferred to the rust-lang/rust repository, since this is a rustc issue (or more specifically with `cc`), or your installation of visual studio may be incomplete. Unfortunately beyond the `VCINSTALLDIR`, it may be difficult to diagnose because it uses COM to discover the location of visual studio version 15+. It also looks like you are using i686, which is fairly rare, and I'm uncertain if you need to do something special to install i686 support in visual studio. You may also get more traction on one of the user forums.

link.exe cannot find advapi32.lib.

**Comment by lvyitian** [comment]
After installing Windows SDK and deleting environment variable `VCINSTALLDIR`, the problem solved.
