### ISSUE TITLE
[ER] Iterator::reduce docs example code

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust#81819]
I think it's better in general for the standard docs to contain examples that are easy to understand, but are also realistic usages of functions and features. An example of this is in slice::binary_search that shows how to insert an item to a sorted vector while maintaining sort order.

So I think the docs of Iterator::reduce could be improved with a more real usage example (to replace the current find_max example). And I think such docs should also say that reduce is useful when your binary operation doesn't have an identity element (or when you don't want to use it for some reason, like efficiency, etc).

**Comment by bstrie** [comment]
Given the close similarity to `Iterator::fold` it should also show an example that demonstrates when they are equivalent, so that people who understand one can understand the other (and hopefully understand the situations in which to use each).
```rust
let folded: i32 = (1..10).fold(0, |acc, e| acc + e);
let reduced: Option<i32> = (1..10).reduce(|acc, e| acc + e);
assert_eq!(Some(folded), reduced);
```
