### ISSUE TITLE
[ER] std::ops::Shr docs example

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust#81820]
In std::ops::Shr the implementation of SpinVector could be improved using `spun_vector.rotate_right(rhs);`.

**Comment by Nicholas-Baron** [comment]
@rustbot label: +T-doc.
I was wondering where this `SpinVector` was, and I found it tucked away in a [doctest](https://github.com/rust-lang/rust/blob/8e54a21139ae96a2aca3129100b057662e2799b9/library/core/src/ops/bit.rs#L523).

**Comment by Dylan-DPC** [comment]
Closing this as the example given was just for illustrative purposes for the >> operator and changing this would defeat that purpose
