### ISSUE TITLE
Suggest async_recursion crate when writing a recursive async fn

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#81907]
We should suggest the use of https://docs.rs/async-recursion/0.3.2/async_recursion/ when writing

```rust
async fn fib(n : u32) -> u64 {
   match n {
       0     => panic!("zero is not a valid argument to fib()!"),
       1 | 2 => 1,
       3     => 2,
       _ => fib(n-1).await + fib(n-2).await
   }
}
```

[which currently only says](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=7dbe0a16fa7b06e7b22a27161d66977e):

```
error[E0733]: recursion in an `async fn` requires boxing
 --> src/lib.rs:1:26
  |
1 | async fn fib(n : u32) -> u64 {
  |                          ^^^ recursive `async fn`
  |
  = note: a recursive `async fn` must be rewritten to return a boxed `dyn Future`
```

**Comment by Aaron1011** [comment]
Is there any precedent for the compiler suggesting an external crate?

**Comment by thomaseizinger** [comment]
> Is there any precedent for the compiler suggesting an external crate?

Yes, for async traits the compiler suggests to use `async_trait`: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=b80e16a6aadbc2c76a3ce4c2296af1bd

**Comment by estebank** [comment]
As @thomaseizinger pointed out, we do for `async-trait`. We normally wouldn't recommend one crate over another ("don't play favorites"), but for small, single use, specialized crates that fill a common language "hole" that we might be working towards "plugging", I think it is a much better experience to immediately unblock newcomers than send them to a user forum to ask how to get around the limitation. The current error gives _some_ idea of how to fix this, but not nearly enough for an even moderately knowledgeable Rust user to fix the problem without some searching.
