### ISSUE TITLE
rustdoc JS does not handle NO_DEVICE_SPACE error

### ISSUE THREAD

**Issue by lovasoa** [rust-lang/rust#81928]
**Problem**

No documented item appear in documentation pages anywhere after a localStorage error.

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/552629/107378750-91732280-6aec-11eb-90a1-aba34678be97.png">

(the page should render [like that](https://docs.rs/serde/1.0.123/serde/ser/trait.Serializer.html) instead)

After localStorage raises a `NS_ERROR_FILE_NO_DEVICE_SPACE` error, all documentation page appear entirely blank. Freeing up space doesn't solve the isssue.

The following appears in the browser console : 

```
Uncaught 
Exception
​
columnNumber: 0
​
data: null
​
filename: "https://docs.rs/storage-20210124-1.51.0-nightly-1d0d76f8d.js"
​
lineNumber: 1
​
message: ""
​
name: "NS_ERROR_FILE_NO_DEVICE_SPACE"
​
result: 2152857616
​
stack: "getCurrentValue@https://docs.rs/storage-20210124-1.51.0-nightly-1d0d76f8d.js:1:1802\ngetSettingValue@https://docs.rs/storage-20210124-1.51.0-nightly-1d0d76f8d.js:1:490\n@https://docs.rs/storage-20210124-1.51.0-nightly-1d0d76f8d.js:1:711\n"
​
<prototype>: ExceptionPrototype { toString: toString(), name: Getter, message: Getter, … }
storage-20210124-1.51.0-nightly-1d0d76f8d.js:1
    getCurrentValue https://docs.rs/storage-20210124-1.51.0-nightly-1d0d76f8d.js:1
    getSettingValue https://docs.rs/storage-20210124-1.51.0-nightly-1d0d76f8d.js:1
    <anonymous> https://docs.rs/storage-20210124-1.51.0-nightly-1d0d76f8d.js:1
```

**Steps**

1. Fill the disk firefox uses for localStorage
2. open any documentation page on docs.rs : the documentation doesn't appear
3. Free up space
4. open any documentation page on docs.rs : the documentation still doesn't appear

**Possible Solution(s)**

Opening the docs in a private browsing window works.

**Comment by lovasoa** [comment]
Where is the JavaScript source for the the cargo documentation ? Maybe I can attempt a PR myself?

**Comment by Eh2406** [comment]
The only reference to localStorage is in: https://github.com/rust-lang/rust/blob/c4e33b51c1a2d5e599b949fa3006467b88df253a/src/librustdoc/html/static/storage.js

**Comment by lovasoa** [comment]
Thanks !
