### ISSUE TITLE
Use consistent names for locking primitives in std::sys_common

### ISSUE THREAD

**Issue by m-ou-se** [rust-lang/rust#81934]
The methods of `StaticMutex`, `Mutex` and `RWLock` have names that are a bit inconsistent and can be confusing. Some of these methods return guards, but others just return `()` or `bool`. It's not always clear from the name which is what.

**Comment by m-ou-se** [comment]
`RWLock` should be renamed to `RwLock`.

**Comment by joboet** [comment]
This was fixed as part of #93740.
