### ISSUE TITLE
[LLVM 11] link failure when using ASAN and cdylib together with LLD

### ISSUE THREAD

**Issue by kamulos** [rust-lang/rust#81948]
System: Arch Linux
Rust: rustc 1.52.0-nightly (0fc6756b4 2021-02-08)
Linker: LLD 11.0.1 (compatible with GNU linkers)

## Reproduction
Create a new library

lib.rs:
```
#[derive(Debug)]
enum A {
    B,
}
```

Cargo.toml:
```
[lib]
crate-type = ["lib", "cdylib"]
```

Compile using:
```
RUSTFLAGS="-Zsanitizer=address -Clink-arg=-fuse-ld=lld" cargo +nightly build --target=x86_64-unknown-linux-gnu
```

## Result

```
  = note: ld.lld: error: undefined hidden symbol: __start_asan_globals
          >>> referenced by 2icvwuxjky13p126
          >>>               /xxx/bug/target/x86_64-unknown-linux-gnu/debug/deps/bug.2icvwuxjky13p126.rcgu.o:(asan.module_ctor)
          >>> referenced by 2icvwuxjky13p126
          >>>               /xxx/bug/target/x86_64-unknown-linux-gnu/debug/deps/bug.2icvwuxjky13p126.rcgu.o:(asan.module_dtor)

          ld.lld: error: undefined hidden symbol: __stop_asan_globals
          >>> referenced by 2icvwuxjky13p126
          >>>               /xxx/bug/target/x86_64-unknown-linux-gnu/debug/deps/bug.2icvwuxjky13p126.rcgu.o:(asan.module_ctor)
          >>> referenced by 2icvwuxjky13p126
          >>>               /xxx/bug/target/x86_64-unknown-linux-gnu/debug/deps/bug.2icvwuxjky13p126.rcgu.o:(asan.module_dtor)
          collect2: error: ld returned 1 exit status
```

**Comment by ehuss** [comment]
Transferred to rust-lang/rust.  Linking and sanitizers are handled by rustc.

**Comment by kamulos** [comment]
To make this even more confusing:
- The `cc` linker invocation that fails with above error message is displayed by rustc
- When I manually copy it and try to repeat it I get the message `ld.lld: error: cannot find version script /tmp/rustcloZBIX/list`
- I then delete the `"-Wl,--version-script=/tmp/rustcloZBIX/list"` from the arguments and it compiles fine

**Comment by kamulos** [comment]
good: nightly-2020-08-23
bad: nightly-2020-08-24

**Comment by kamulos** [comment]
636ca7a4129d0e46483a41fc2687999067b45f8f is the first bad commit
```
commit 636ca7a4129d0e46483a41fc2687999067b45f8f
Author: Josh Stone <jistone@redhat.com>
Date:   Tue Jul 28 12:16:41 2020 -0700

    Upgrade to LLVM 11 (rc2)

 .gitmodules      | 2 +-
 src/llvm-project | 2 +-
 2 files changed, 2 insertions(+), 2 deletions(-)
```

LLVM issue? I am not sure how to get further

**Comment by kamulos** [comment]
Tried upgrading `src/llvm-project` to `rustc/12.0-2021-02-03` and it still happens.

**Comment by tmiasko** [comment]
* Most likely related to https://github.com/rust-lang/llvm-project/commit/d76e62fdb7a93d9a33f642b6b528f2562cc3c3f4, but in that case version bump should help since it includes a revert.
* `-Cllvm-args=--asan-globals-live-support=false` should help as a workaround.

**Comment by kamulos** [comment]
Thanks, that was really helpful:

- I might have made a mistake and not bumped the version properly. Now if I try to build it, the compilation just fails (which is not unexpected at this stage I guess)
- Great this worked perfectly. All the other workarounds I had thought of were pretty bad.

I'll close this now and check back, when LLVM12 is officially included in rustc

**Comment by nikic** [comment]
@kamulos FWIW, you can test LLVM 12 using `cargo install rustup-toolchain-install-master && rustup-toolchain-install-master cdf4d8eebff783a7bf3da9267accea75dcf6938f` and then using `cargo +cdf4d8eebff783a7bf3da9267accea75dcf6938f`. This fetches CI artifacts from #81451.

**Comment by tmiasko** [comment]
`cdf4d8eebff783a7bf3da9267accea75dcf6938f` does resolve the issue for me. It also might be the case that the default value of `UseGlobalsGC = true` used now is not always appropriate, but I didn't have time to investigate yet.

**Comment by kamulos** [comment]
Thanks @nikic I can confirm this CI version works flawlessly in my full project.
