### ISSUE TITLE
Safe code (ui/issues/issue-69225-SCEVAddExpr-wrap-flag.rs) miscompiles under llvm9 + codegen-units=1

### ISSUE THREAD

**Issue by the8472** [rust-lang/rust#81946]
```
---- [ui] ui/issues/issue-69225-SCEVAddExpr-wrap-flag.rs stdout ----

error: error pattern ' index out of bounds: the len is 0 but the index is 16777216' not found!
status: signal: 11
command: "/checkout/obj/build/x86_64-unknown-linux-gnu/test/ui/issues/issue-69225-SCEVAddExpr-wrap-flag/a"
```

Current reproducer: #81945

Original issue: #69225. According to https://github.com/rust-lang/rust/issues/69225#issuecomment-590161333  the testcase originally did work fine for any number of codegen units. Seems like a regression.

**Comment by Stupremee** [comment]
Assigning `P-medium` as [discussed as part of the Prioritization Working Group procedure](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2381946.20Safe.20code.20%28ui.2Fissues.2Fissue-69225-SCEVAddExpr-wrap-fl.E2.80.A6/near/225825784) and removing `I-prioritize`.

**Comment by nagisa** [comment]
I believe we use unpatched/upstream LLVM in for the llvm-9 CI jobs, which would make this technically a not-a-rustc-issue, given that the original fix relied on patching LLVM (10 &later)

**Comment by nikic** [comment]
Right, I don't think there's anything we can really do here, as it's a bug in external LLVM. I think simply adding a `min-llvm-version` to the test would be fine.
