### ISSUE TITLE
Bootstrap assumes llvm-dwp is sibling of llvm-config instead of inside bindir

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust#81949]
The incorrect way: assuming `llvm-dwp` exists in the parent directory of [the path provided for `llvm-config`](https://github.com/rust-lang/rust/blob/87bacf22ec93a9479dbd829de5d1917c16b17255/config.toml.example#L599). In general these two paths cannot be assumed to have any relationship to one another.

https://github.com/rust-lang/rust/blob/87bacf22ec93a9479dbd829de5d1917c16b17255/src/bootstrap/compile.rs#L1075-L1079

<br>

The correct way: run `llvm-config --bindir` using the provided llvm-config, and pick `llvm-dwp` inside of the directory that it returns. Bootstrap does this correctly elsewhere, such as for FileCheck:

https://github.com/rust-lang/rust/blob/87bacf22ec93a9479dbd829de5d1917c16b17255/src/bootstrap/lib.rs#L669-L671

**Comment by Mark-Simulacrum** [comment]
Good catch! I wish we had tools to lint for this kind of thing in bootstrap, or at least some kind of testing; we consistently get this wrong quite often unfortunately.

I'd be happy to see a PR to fix this. Otherwise it'll likely take some time for me to get to it.

**Comment by cuviper** [comment]
I think this is also something that dist should ignore when building with external LLVM, although I suspect rust's support for split DWARF won't handle that well as-is.
