### ISSUE TITLE
[1.50] `./x.py install doc` changed its default location

### ISSUE THREAD

**Issue by cuviper** [rust-lang/rust#81967]
I tried this command:

```text
DESTDIR=foo ./x.py install doc
```

I expected to see files installed to `foo/usr/local/share/doc/rust/html`

Instead, I see files installed to `foo/usr/local/share/doc/html`

This worked on Rust 1.49, and I noticed the change in testing the Rust 1.50 pre-release.

I'm going ahead to call this stable-to-stable since 1.50 is imminent.
@rustbot modify labels: +regression-from-stable-to-stable -regression-untriaged

---

The specific change appears to be commit 4050e2796e1cf from #81151, a backport of 2caf9bcb33b7 from #80797, where the default install `docdir` changed from "share/doc/rust" to just "share/doc". cc @pietroalbini 

Also note that `config.toml` still documents that the default is "share/doc/rust".

**Comment by apiraino** [comment]
labeling to `T-infra` as per sibling PR #80797
