### ISSUE TITLE
std docs settings page logo link goes to `test` crate

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#81986]
I've just noticed a rather bizarre bug:

- Go to [doc.rust-lang.org/std](https://doc.rust-lang.org/std)
- Click the Settings gear
- Then click the Rust logo in the top-left of the page
- Observe that you have been taken to [doc.rust-lang.org/test](https://doc.rust-lang.org/test)
  (the docs for the `test` crate)

I'm guessing the issue is that the settings page is at `/settings.html` (because
the settings are global across all of the standard library crates), so it's
picking arbitrarily. But it's a bit of a weird choice: why the `test` crate?
Maybe because it's the last crate alphabetically?

I think ideally it would go to `/std` instead.

-----

This may be somewhat unrelated, but I also noticed that the compiler API docs
(at `/nightly/nightly-rustc`) have a weird logo link target even when not on the
settings page: it goes to the `rustdoc` API docs. This one I really don't
understand because the last crate alphabetically is `rustdoc_json_types`, not
`rustdoc`.

**Comment by jyn514** [comment]
>  But it's a bit of a weird choice: why the test crate?
Maybe because it's the last crate alphabetically?

Because it's the last crate documented. `test` depends on `std`.

**Comment by jyn514** [comment]
Is this worth fixing?

**Comment by camelid** [comment]
It's certainly not high-priority, but I figure that we might as well track it so if someone wants to fix it they'll know about it :)

**Comment by GuillaumeGomez** [comment]
I don't see how it can be fixed properly speaking... Well, I see a few options:
 * Re-documenting `std` afterwards
 * Creating a new option to enforce that `std` is the "main" crate
 * Changing the link by hand once the `std` documentation has been generated.

**Comment by camelid** [comment]
> - Creating a new option to enforce that `std` is the "main" crate

That seems like a potentially viable option.

**Comment by Dylan-DPC** [comment]
Closing this as it's no longer an issue, since settings now doesn't open on another page
