### ISSUE TITLE
Update Rust String Documentation Regarding Unicode Scalar Value equivalence to Unicode Code Point (in UTF-8)

### ISSUE THREAD

**Issue by logannc** [rust-lang/rust#82008]
Apologies if this is the wrong place to file this bug.

It is well documented that [Rust Strings are _valid_ UTF-8 built off of Unicode Scalar Values](https://github.com/rust-lang/reference/blob/master/src/types/textual.md).

Something that is not obvious but true (I think - see *not obvious*), is that UTF-8 [does not allow surrogate code points](https://www.unicode.org/versions/Unicode13.0.0/ch03.pdf#G31703), therefore the Unicode Scalar Values produced from Rust Strings are a strict subset of *Unicode* code points but equivalent to the set of *UTF-8*-encodeable code points.

> Because surrogate code points are not Unicode scalar values, any UTF-8 bytesequence  that  would  otherwise  map  to  code  points  U+D800..U+DFFF  is  ill-formed.

I propose updating the documentation where the distinction about USVs are made. The current text is technically correct but is misleading as it can be easily incorrectly inferred that USVs are meaningfully different from code points (in the context of UTF-8 strings). While `char` documentation cannot claim this because it is absent the context of being UTF-8 encoded, we can make it more clear that USVs produced from strings are not different from UTF-8 code point sequences.

Unicode strings are hard enough, I think this will remove a source of confusion for developers who haven't gone reading Unicode glossaries/specs. Developers are already often familiar with the concept of code points as opposed to raw bytes (but not necessarily the details), so if we can speak to what is already well known without losing technical accuracy, I think that is a win for productivity and developer accessibility.

--- 

I do plan to take a look at making the documentation changes myself, though I think they're spread out across a few different repos.

**Comment by workingjubilee** [comment]
[current docs for char](https://doc.rust-lang.org/1.77.1/std/primitive.char.html):
> A char is a ‘[Unicode scalar value](https://www.unicode.org/glossary/#unicode_scalar_value)’, which is any ‘[Unicode code point](https://www.unicode.org/glossary/#code_point)’ other than a [surrogate code point](https://www.unicode.org/glossary/#surrogate_code_point). This has a fixed numerical definition: code points are in the range 0 to 0x10FFFF, inclusive. Surrogate code points, used by UTF-16, are in the range 0xD800 to 0xDFFF.

Seems resolved. Closing.
