### ISSUE TITLE
Don't return a `bool` from `get_word_attr`

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#82016]
[`get_word_attr`](https://doc.rust-lang.org/nightly/nightly-rustc/rustdoc/clean/types/trait.NestedAttributesExt.html#tymethod.get_word_attr) returns both an `Option` and whether the option is `Some`. This is grossly redundant, it should just return an option.

**Comment by magurotuna** [comment]
I'm interested in working on it :)
@rustbot claim
