### ISSUE TITLE
Unnecessary "{}" suggestion for panic with const string

### ISSUE THREAD

**Issue by ldm0** [rust-lang/rust#82026]
#78088 implements suggestion for panic with first argument not literal, but forget to handle such code:
```rust
const ICE: &str = "Internal compiler error";
fn main() {
    panic!(ICE);
}
```
This code is actually legit., but `non_fmt_panic` suggestion is emitted.
Check:  https://gist.github.com/6002a4f7fedfda0e615d0b1158015eee

**Comment by SNCPlay42** [comment]
This isn't #78088's warning, it's #81645's.

And I don't think it's incorrect; only literals, not expressions can be used as format strings, even if the expression is evaluable at compile time. e.g. [this](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=44b71ac38f89cad11aa6403c9aa25b55) doesn't work:

```rust
const FORMAT: &str = "{}";
fn main() {
    panic!(FORMAT, "Hello");
}
```

And indeed the code given [does not compile](https://rust.godbolt.org/z/TEhYEd) in the 2021 edition.

**Comment by ldm0** [comment]
@SNCPlay42 Thanks!
