### ISSUE TITLE
Add x86-64-v2, x86-64-v3, and x86-64-v4 as available target_cpus

### ISSUE THREAD

**Issue by hsivonen** [rust-lang/rust#82024]
Page 14 of the [2020-08-31 version of the AMD64 supplement to the System V ABI](https://gitlab.com/x86-psABIs/x86-64-ABI/-/jobs/711608198/artifacts/raw/x86-64-ABI/abi.pdf?inline=false) defines new microarchitecture levels that bundle instruction set extensions: `x86-64-v2`, `x86-64-v3`, and `x86-64-v4`. According to a [Red Hat blog post](https://developers.redhat.com/blog/2021/01/05/building-red-hat-enterprise-linux-9-for-the-x86-64-v2-microarchitecture-level/), LLVM 12 will support these.

`rustc` should support these as `target_cpu` values, enable the right `target_feature`s, and pass them appropriately to LLVM.

[Internals thread](https://internals.rust-lang.org/t/x86-64-v2-and-x86-64-v3-targets-for-linux-and-windows/14030)

**Comment by IsaacWoods** [comment]
The link to the internals thread also points to RedHat's blog. I'm guessing [this](https://internals.rust-lang.org/t/x86-64-v2-and-x86-64-v3-targets-for-linux-and-windows/14030) is the internals thread.

**Comment by hsivonen** [comment]
Oops. Updated the link. Thanks.

**Comment by ojeda** [comment]
`rustc` does not manage these options, LLVM does. Thus when we move to LLVM 12, we will get these.

**Comment by est31** [comment]
LLVM commit for reference: https://github.com/llvm/llvm-project/commit/012dd42e027e

**Comment by est31** [comment]
Also I confirm what @ojeda said. In #79043, all I had to do was patch LLVM to add availability of these target_cpus. No changes in rustc were neccessary.

**Comment by jyn514** [comment]
The compiler is now using LLVM 12.0.1, so this might be fixed?

**Comment by hsivonen** [comment]
Indeed, [this is now fixed](https://rust.godbolt.org/z/oM4nPbnvT). Thanks.
