### ISSUE TITLE
rustdoc: attempting to select item name selects whole line (on Chrome)

### ISSUE THREAD

**Issue by jsha** [rust-lang/rust#82042]
Steps to reproduce:

1. Visit the rustdoc page for any item (function, struct, etc).
2. Attempt to highlight the item name at the top of the page by using a mouse (for instance, you might want to copy the item name). Specifically: click to the right of the item name, and drag to the left of the item name.

Expected result:

Item name is highlighted.

Actualy result:

Entire line is highlighted, including `[+] [src]` links.

Screencast attached.

https://user-images.githubusercontent.com/220205/107821611-9ffe4b80-6d31-11eb-8759-ba4e71d282c1.mp4

**Comment by TaKO8Ki** [comment]
I'm interested in working on this issue.
@rustbot claim

**Comment by camelid** [comment]
Duplicate of #80582?

**Comment by camelid** [comment]
cc @GuillaumeGomez (https://github.com/rust-lang/rust/issues/80582#issuecomment-753360571)

**Comment by TaKO8Ki** [comment]
I think this is duplicate of #80582 too. So I'm going to work on it.

**Comment by jyn514** [comment]
@jsha I can't replicate this on doc.rust-lang.org. What version of rustdoc are you using, and do you have the same problem on nightly?

**Comment by jsha** [comment]
My testing is on doc.rust-lang.org (and also docs.rs), using Chrome 88.

**Comment by camelid** [comment]
@jsha can you reproduce with `/beta/std` in Chrome? I can only reproduce in Chrome with `/stable/std` (which is currently 1.50).

**Comment by camelid** [comment]
As I understand it, this bug is only present in Chrome (maybe Edge etc. too) with rustdoc 1.50.0 or older. So if `@jsha` cannot reproduce with beta and nightly, I think this should probably just be closed.

**Comment by jsha** [comment]
Indeed, this does not reproduce for me in `/beta/std` and `/nightly/std`. Closing, thanks!
