### ISSUE TITLE
Unable to mark ARM32's `r14` register as clobbered in `asm!`

### ISSUE THREAD

**Issue by jrvanwhy** [rust-lang/rust#82052]
I attempted to compile a crate containing the following expression:

```rust
unsafe { asm!("svc 0", lateout("r14") _); }
```

I expected it to compile successfully.

Instead, I received this error:

```rust
error: couldn't allocate output register for constraint '{r14}'
```

`rustc --version --verbose`:
```
rustc 1.52.0-nightly (3f5aee2d5 2021-02-12)
binary: rustc
commit-hash: 3f5aee2d5241139d808f4fdece0026603489afd1
commit-date: 2021-02-12
host: x86_64-unknown-linux-gnu
release: 1.52.0-nightly
LLVM version: 11.0.1
```

`RUST_BACKTRACE=1` omitted, it did not produce anything else.

@Amanieu diagnosed the cause and offered a solution [here](https://github.com/rust-lang/rust/issues/81092#issuecomment-778567688).

**Comment by jrvanwhy** [comment]
While I try to spin up a rustc development environment, can someone point me to the tests for this code? I don't see any tests in the crate.

https://github.com/rust-lang/rust/blob/21cbbdc44de84e3ea99bca239091e5d1c49af654/compiler/rustc_codegen_llvm/src/asm.rs#L487-L490

**Comment by Amanieu** [comment]
https://github.com/rust-lang/rust/blob/21cbbdc44de84e3ea99bca239091e5d1c49af654/src/test/assembly/asm/aarch64-types.rs#L99-L108

**Comment by jrvanwhy** [comment]
I think I have a working `rustc` development environment now. I'll try to fix this -- thank you @Amanieu for making this easy for me!
