### ISSUE TITLE
Type inside Option cannot be infered when passing None

### ISSUE THREAD

**Issue by szdytom** [rust-lang/rust#82054]
I tried this code:

```rust
fn output<T: std::fmt::Debug>(val: Option<&T>) {
    if let Some(x) = val {
        println!("{:?}\n", x);
    }
}

fn main() {
    output(None);
}
```

I expected to see this happen: The code passes compile-time check.
I'm passing `None` into the function so I expect that the type of T is not important.

Instead, this happened: 
```
error[E0282]: type annotations needed
 --> src/main.rs:8:5
  |
8 |     output(None);
  |     ^^^^^^ cannot infer type for type parameter `T` declared on the function `output`

error: aborting due to previous error
```

### Meta

I've created a playground of this code: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=813fd59ceb3fb1e41d65ff05092ef40d

**Comment by hbina** [comment]
Will this _ever_ compile? I assume the compiler have to monomorphize (or whatever its called) to _some_ type before compiling down to assembly.

**Comment by jonas-schievink** [comment]
This is working as expected. All generic parameters need to be known at compile time, even if they don't affect program semantics.
