### ISSUE TITLE
cargo how to disable unused waring  i?

### ISSUE THREAD

**Issue by sstudioer** [rust-lang/rust#82070]
` rustc ./src/main.rs -A unused  // this is rustc 
`
I want disable  unused waring in **cargo build**,  how to do?

**Comment by jonas-schievink** [comment]
Hi! This issue tracker is mainly meant for bug reports and concrete, small feature requests. Questions like this are better asked in the user forum at https://users.rust-lang.org/ or on [one of the chat platforms](https://www.rust-lang.org/community) used by the Rust community.
