### ISSUE TITLE
`str::as_bytes` and friends have incorrect const stabilization version annotation

### ISSUE THREAD

**Issue by tbu-** [rust-lang/rust#82085]
https://github.com/rust-lang/rust/blob/8e54a21139ae96a2aca3129100b057662e2799b9/library/core/src/str/mod.rs#L220

These were stabilized in https://github.com/rust-lang/rust/commit/7767e7fb165d527f1991175809a361f2d2313b80 as part of https://github.com/rust-lang/rust/pull/63770 which was only included in **1.39.0** and up (GitHub displays this in the commit link).

The attribute was added in https://github.com/rust-lang/rust/commit/5e17e3988165d3245e38af0b1c40cde47699f6a7 as part of https://github.com/rust-lang/rust/pull/67136, one could presumably check the other version attributes as well.

Affects:
- `str::as_bytes`
- `str::is_empty`
- `str::len`

**Comment by m-ou-se** [comment]
cc @oli-obk

**Comment by oli-obk** [comment]
I just copy pasted these everywhere and forgot to check the versions on some of these. I guess I'll have to go through all of them to find out which ones I missed.
