### ISSUE TITLE
repr(C) on enums is unsound on hexagon-unknown-linux-gnu

### ISSUE THREAD

**Issue by mahkoh** [rust-lang/rust#82100]
Enums on hexagon-unknown-linux-gnu are packed by default: https://godbolt.org/z/q49s5v

This is not implemented in rustc atm https://github.com/rust-lang/rust/blob/b86674e7cc8ac9c846ed5aca84aaefc2d0d12e4a/compiler/rustc_middle/src/ty/layout.rs#L131-L140

**Comment by RalfJung** [comment]
This looks like an incorrect ABI implementation then, but as long as Rust is self-consistent, "unsound" is the wrong term here I think?
