### ISSUE TITLE
Remove unnecessary `tcx` parameter to `param_env_to_generics`

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#82137]
You can get a tcx from `self.cx.tcx`, there's no need to pass it separately.

Note that this will conflict with https://github.com/rust-lang/rust/pull/82020/ so you may want to wait a day or two (or not, if you don't mind rebasing).

**Comment by camelid** [comment]
I think there are also a couple of other functions that unnecessarily take `tcx` in the same area of the code.
