### ISSUE TITLE
[rustdoc] Search results: Make fuzzy search less wild for small words

### ISSUE THREAD

**Issue by ojeda** [rust-lang/rust#82131]
Fuzzy search is matching too many things [*], e.g.:

- `FRom` due to `FRee`
- `REm` due to `fREe`

It could be improved restricting matches for small words, e.g. for words < 4 in size, match only if 3 characters or more match.

[*]
![image](https://user-images.githubusercontent.com/23638587/107890698-468c4d00-6ee8-11eb-85ed-ea2428ec6d1d.png)

**Comment by lucas-deangelis** [comment]
Can I claim this one?
