### ISSUE TITLE
Misleading "slices are iterators" hint

### ISSUE THREAD

**Issue by mendess** [rust-lang/rust#82168]
[Given this code](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=bf624fa2e446f0a81a094ad8e4cca971)

```rust
fn main() {
    let a = [1,2,3];
    for i in a {}
}
```

One of the notes in error message says

```
note: arrays are not iterators, but slices like the following are: `&[1, 2, 3]`
```

However slices are also not iterators, but can be converted to an iterator as indicated by another note in the same message as the requirement that isn't met

```
note: required because of the requirements on the impl of `IntoIterator` for `[{integer}; 3]`
```
The full error message is:
```
error[E0277]: `[{integer}; 3]` is not an iterator
 --> r.rs:3:14
  |
3 |     for i in a {}
  |              ^ borrow the array with `&` or call `.iter()` on it to iterate over it
  |
  = help: the trait `Iterator` is not implemented for `[{integer}; 3]`
  = note: arrays are not iterators, but slices like the following are: `&[1, 2, 3]`
  = note: required because of the requirements on the impl of `IntoIterator` for `[{integer}; 3]`
  = note: required by `into_iter`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
```

This came up while helping someone learn the language and was rather confusing.

### Meta

`rustc --version --verbose`:
```
rustc 1.50.0 (cb75ad5db 2021-02-10)
binary: rustc
commit-hash: cb75ad5db02783e8b0222fee363c5f63f7e2cf5b
commit-date: 2021-02-10
host: x86_64-unknown-linux-gnu
release: 1.50.0
```

**Comment by jyn514** [comment]
@mendess for loops accept either `Iterator` or `IntoIterator`, that's not the issue. The problem is that the compiler isn't smart enough to make the reference to an array decay to a slice:

>   = help: the trait `Iterator` is not implemented for `[{integer}; 3]`

You can work around it with `let a: &[_] = &[1, 2, 3]` or with `for i in &[1, 2, 3] {`.

However I'm not sure how you got to this error - this code works fine for me:

```rust
fn main() {
    let a = &[1,2,3];
    for i in a {}
}
```
Can you please post a minimal reproducible example?

**Comment by mendess** [comment]
@jyn514 
> However I'm not sure how you got to this error - this code works fine for me:
> 
> ```rust
> fn main() {
>     let a = &[1,2,3];
>     for i in a {}
> }
> ```
> 
> Can you please post a minimal reproducible example?

In the code I wrote `a` is an array and not a reference to an array. Hence the error message, saying
```
not implemented for `[{integer}; 3]`
```

**Comment by estebank** [comment]
The incorrect suggestion is because `[T; N]` indeed used _not_ to implement `IntoIterator`.

**Comment by mendess** [comment]
> The incorrect suggestion is because `[T; N]` indeed used _not_ to implement `IntoIterator`.

[It still doesn't](https://doc.rust-lang.org/std/primitive.array.html#impl-IntoIterator) :thinking: and what I think is misleading is saying "slices are iterators"

**Comment by frewsxcv** [comment]
Would it be more clear if the help message also called out `IntoIterator`? For example:

```
  = help: neither `Iterator` nor `IntoIterator` are implemented for `[{integer}; 3]`
```

**Comment by camsteffen** [comment]
```text
error[E0277]: `[{integer}; 3]` is not an iterator
```
This is bad for beginners because it promotes a misconception that for loops require an `Iterator` rather than `IntoIterator`.

```text
  = note: required by `into_iter`
```

This is confusing because it seems to refer to desugared code, which is a compiler implementation detail.

Suggestion:

```text
error[E0277]: `[{integer}; 3]` does not implement `IntoIterator`
 --> r.rs:3:14
  |
3 |     for i in a {}
  |              ^ borrow the array with `&` or call `.iter()` on it to iterate over it
  |
  = help: the trait `IntoIterator` is required for the target of a for loop
  = note: borrowing the array will allow it to be coerced to a slice
```

**Comment by frewsxcv** [comment]
The tricky bit is `IntoIterator` has a generic implementation for `Iterator`:

```rust
#[stable(feature = "rust1", since = "1.0.0")]
impl<I: Iterator> IntoIterator for I {
    type Item = I::Item;
    type IntoIter = I;

    fn into_iter(self) -> I {
        self
    }
}
```

So saying it requires an "iterator" is not inaccurate, but it's not the whole truth. So your suggestion is an improvement in that it's more accurate, but also comes at the cost of throwing this `IntoIterator` thing at new users, which might be fine but just calling that out as something to consider.

-----

Separate thought. Looking at:

```
note: arrays are not iterators, but slices like the following are: `&[1, 2, 3]`
```

and

```
= note: borrowing the array will allow it to be coerced to a slice
```

My understanding is that the type of `&[1, 2, 3]` is not a slice, but a reference to an array ([`&[{integer}; 3]`](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=c5ba0708fdb3e5c045424f8679463fab)). If one wanted to create a slice, you'd need to do `&[1, 2, 3][..]` ([`&[{integer}]`](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=a772aef24979219239cc634fa55df3b3)). I may be being overly pedantic, but we also don't want to mislead users about what's happening here.

**Comment by camsteffen** [comment]
My personal experience is that, when I learned that for loops take `IntoIterator`, I felt late to the party. And it also was easier to understand that way, not harder.

> is not a slice

That is precisely why I worded it the way I did.

**Comment by frewsxcv** [comment]
> My personal experience is that, when I learned that for loops take `IntoIterator`, I felt late to the party. And it also was easier to understand that way, not harder.

Yeah that's fair! 

> > is not a slice
> 
> That is precisely why I worded it the way I did.

Since there's an implementation of [`IntoIterator` for `&[T; N]`](https://github.com/rust-lang/rust/blob/98f8cce6db6c6c6660eeffee2b3903104e547ecf/library/core/src/array/mod.rs#L194-L202), my assumption is there's no coercion to a slice happening here.

**Comment by camsteffen** [comment]
Ah I see. In that case I'd remove the part about slices. So then my suggested output is pretty short! I also realized `required by into_iter` would seem less out of place if that came after mentioning that `IntoIterator` is required for a for loop.

**Comment by frewsxcv** [comment]
Also worth mentioning that we can remove this error message altogether once arrays implement `IntoIterator`: https://github.com/rust-lang/rust/pull/65819

**Comment by ibraheemdev** [comment]
The code now compiles, this should be closed.
