### ISSUE TITLE
rustdoc: Confusing intra-doc handling of `Self` in enum

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#82209]
This code works fine:

```rust
pub enum Foo {
    /// [Self::Bar::abc]
    Bar {
        abc: i32,
        xyz: i32,
    },
}
```

But this code's intra-doc link doesn't resolve:

```rust
pub enum Foo {
    Bar {
        abc: i32,
        /// [Self::Bar::abc]
        xyz: i32,
    },
}
```

```
warning: unresolved link to `Bar::Bar::abc`
 --> foo.rs:4:14
  |
4 |         /// [Self::Bar::abc]
  |              ^^^^^^^^^^^^^^ no item named `Bar` in scope
  |
  = note: `#[warn(broken_intra_doc_links)]` on by default
```

Doesn't `Self` usually only refer to types, not enum variants? (Barring the proposed RFC to make enum variant types.)

**Comment by camelid** [comment]
Yeah, this definitely seems like a bug. I have to use `Foo::Self::abc` (or `Foo::Bar::abc`). `Self::abc` doesn't work because it looks for the enum variant as if it's a free-floating type:

```
warning: unresolved link to `Bar::abc`
 --> foo.rs:4:14
  |
4 |         /// [Self::abc]
  |              ^^^^^^^^^ no item named `Bar` in scope
  |
  = note: `#[warn(broken_intra_doc_links)]` on by default
```

**Comment by jyn514** [comment]
@camelid do you know if this ever worked? I might have broken it in https://github.com/rust-lang/rust/pull/76467.

**Comment by jyn514** [comment]
But also I agree that this seems like a misfeature, I'd be ok with getting rid of it. To do that, just delete [`variant_field`](https://github.com/rust-lang/rust/blob/master/src/librustdoc/passes/collect_intra_doc_links.rs#L462-L844) and all references to it.

**Comment by hellow554** [comment]
hey @jyn514 

you are correct. Bisecting this leads to https://github.com/rust-lang/rust/commit/b7ebc6b0c1ba3c27ebb17c0b496ece778ef11e18

So the fix is to get rid of the `variant_field` method completly (and of course delete any code that calls it)? Or am I misreading it?

**Comment by jyn514** [comment]
Yes, I think so. No one noticed this breaking for 12 weeks and `Self` always refers to the type in normal code, not the variant: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=9655fe188d99f728e90e65a08164e825

**Comment by lucas-deangelis** [comment]
Hi, I don't know if anyone is already planning to work on it, but if not, would it be a good first issue? I'm still new to the language but I'd like to start contributing.

**Comment by camelid** [comment]
Yes, this should be a good first issue. You can claim it with `@rustbot claim`. Post here or [on Zulip](rust-lang.zulipchat.com/) if you have any questions :)

**Comment by lucas-deangelis** [comment]
Thanks! I'll have a look at it. @rustbot claim

**Comment by lucas-deangelis** [comment]
I've taken a deeper look at the issue, and at the doc on contributions to Rust. Correct me if I'm wrong, but I think I'm supposed to start with making a failing test case. I made a `issue-82209.rs` file in `src/test/rustdoc/`. Here's the file:

```rust
#![deny(broken_intra_doc_links)]
pub enum Foo {
    Bar {
        abc: i32,
        /// [Self::Bar::abc]
        xyz: i32,
    },
}

```

I'm not sure about the `#![deny(broken_intra_doc_links)]`, but I couldn't get the test to fail without something like that, and it's more precise than the `#![deny(warnings)]` that I used at first. Does this look okay to you?

**Comment by jyn514** [comment]
@lucas-deangelis yes, that looks fine. I have a couple nits but they can wait until you make a PR to review, that test is enough to what's going wrong.

**Comment by lucas-deangelis** [comment]
Thanks! I'll start working on the fix now.

**Comment by camelid** [comment]
Assigning `P-medium` and removing `I-prioritize` as [discussed](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2382209.20rustdoc.3A.20Confusing.20intra-doc.20handling.20of.20.60Self.60.20in.20e.E2.80.A6) in the prioritization working group.

**Comment by lucas-deangelis** [comment]
I've tried removing `variant_field` and all references to it as @jyn514 suggested, however I still had the same behavior as before. There's a part of `resolve` with `FIXME(jynelson): why is this different from variant_field?`, but even after removing it, the link is still resolved to `Bar::Bar::abc`. I think some of the logic is somewhere else.

**Comment by jyn514** [comment]
Hmm, if that doesn't fix it the bug might be in the `Self` handling: https://github.com/rust-lang/rust/blob/15598a83db88ec7a32ea18a44dd6309f32edc07e/src/librustdoc/passes/collect_intra_doc_links.rs#L870
You could try extending https://github.com/rust-lang/rust/blob/15598a83db88ec7a32ea18a44dd6309f32edc07e/src/librustdoc/passes/collect_intra_doc_links.rs#L837-L845 to also use the parent item for `DefKind::Ctor` or `DefKind::Variant`?

**Comment by lucas-deangelis** [comment]
This alone doesn't seem to fix it, however I've found that after adding `DefKind::Variant`, modifying the following part modify the error message for the resolved link:

https://github.com/rust-lang/rust/blob/15598a83db88ec7a32ea18a44dd6309f32edc07e/src/librustdoc/passes/collect_intra_doc_links.rs#L1016-L1026

The problem here seems to be that `name` refers to the kind and not the enum.

**Comment by camelid** [comment]
> This alone doesn't seem to fix it, however I've found that after adding `DefKind::Ctor` on the match

Did you try matching both `DefKind::Ctor` and `DefKind::Variant`?

**Comment by lucas-deangelis** [comment]
This is my naive attempt:

```rust
} else if matches!(
            self.cx.tcx.def_kind(item.def_id),
            DefKind::AssocConst
                | DefKind::AssocFn
                | DefKind::AssocTy
                | DefKind::Variant
                | DefKind::Field
                | DefKind::Ctor(_, _)
        ) {
            self.cx.tcx.parent(item.def_id)
```

I didn't add `DefKind::Variant` because it is already in the match, however, I think there's something here that I don't understand since you said "matching both", and here I'm matching either of them.

**Comment by camelid** [comment]
> I didn't add `DefKind::Variant` because it is already in the match, however, I think there's something here that I don't understand since you said "matching both", and here I'm matching either of them.

What you wrote is what I meant :)

I meant match either `Ctor` or `Variant` (as in `DefKind::Ctor(..) | DefKind::Variant`), but I didn't realize that `Variant` was already in the match.

Does your attempt work?

**Comment by lucas-deangelis** [comment]
> What you wrote is what I meant :)

Nice, thanks for confirming. 

> I meant match either Ctor or Variant (as in DefKind::Ctor(..) | DefKind::Variant), but I didn't realize that Variant was already in the match.
>
> Does your attempt work?

My attempt doesn't work. 

Right now I'm looking at [`resolve_link`](https://github.com/rust-lang/rust/blob/15598a83db88ec7a32ea18a44dd6309f32edc07e/src/librustdoc/passes/collect_intra_doc_links.rs#L920), since it's the part where the link is created. I think that by trying to understand more `resolve_link`, I can figure out from where exactly does the path comes from, and why in that case it gets resolved to `Bar::Bar::abc` instead of `Foo::Bar::abc`.

**Comment by jyn514** [comment]
@lucas-deangelis all the "preprocessing" of the link (turning `Self` into a path) happens before resolve_link is called, in https://github.com/rust-lang/rust/blob/a8486b64b0c87dabd045453b6c81500015d122d6/src/librustdoc/passes/collect_intra_doc_links.rs#L858.

**Comment by camelid** [comment]
Aha, I bet this is the issue:

https://github.com/rust-lang/rust/blob/a8486b64b0c87dabd045453b6c81500015d122d6/src/librustdoc/passes/collect_intra_doc_links.rs#L837-L845

For fields in enum variants, the parent is the variant, not the enum.

**Comment by lucas-deangelis** [comment]
> @lucas-deangelis all the "preprocessing" of the link (turning Self into a path) happens before resolve_link is called, in

Thanks for the clarification.

> For fields in enum variants, the parent is the variant, not the enum.

So if I understand correctly, if we encounter a variant, we should return the parent of the parent of  `item.def_id`?

**Comment by jyn514** [comment]
> So if I understand correctly, if we encounter a variant, we should return the parent of the parent of item.def_id?

If you encounter a *field* that's in a variant. Basically make the check recursive (since fields may not be in a variant, e.g. `struct S { x: usize }`

**Comment by lucas-deangelis** [comment]
Thanks, I'll try that.

**Comment by lucas-deangelis** [comment]
I think I'm making some progress. I added a new condition to check if we encounter a field that's in a variant before the `matches!` line 837:

```rust
else if (matches!(self.cx.tcx.def_kind(item.def_id), DefKind::Field) && matches!(self.cx.tcx.def_kind(self.cx.tcx.parent(item.def_id).unwrap()), DefKind::Variant)) {
            self.cx.tcx.parent(item.def_id).and_then(|item_id| self.cx.tcx.parent(item_id))
} else if matches!(
            self.cx.tcx.def_kind(item.def_id),
            DefKind::AssocConst
                | DefKind::AssocFn
                | DefKind::AssocTy
                | DefKind::Field
                | DefKind::Variant
) {
```

I'll have to find a way to handle the call to `.unwrap()` better once I get this working. Now the error I get is:

```bash
error: unresolved link to `Foo::Bar::abc`
 --> rust/src/test/rustdoc/issue-82209.rs:5:14
  |
5 |         /// [Self::Bar::abc]
  |              ^^^^^^^^^^^^^^ the enum `Foo` has no variant or associated item named `abc`
  |
```

Am I correct in assuming that this is now an error in the link resolution?

**Comment by jyn514** [comment]
Hmm, is this still with the calls to `variant_field` removed? Try adding those back.

**Comment by lucas-deangelis** [comment]
> Hmm, is this still with the calls to `variant_field` removed? Try adding those back.

It was, and now with it back it works. Thanks. Should I make a pull request now?

**Comment by jyn514** [comment]
That would be great, thanks!

**Comment by lucas-deangelis** [comment]
And it's merged! Thank you @jyn514 and @camelid for the help on the issue, @hellow554 for some of the initial work and @Dylan-DPC for the rollups.

**Comment by jyn514** [comment]
You're very welcome! Thank you for tackling the fix :)
