### ISSUE TITLE
the trait `Foo` is not implemented for `Bar`

### ISSUE THREAD

**Issue by tschuett** [rust-lang/rust#82237]
I often get these errors. A more actionable error message would be helpful.
- Bar has no implemented function Braz.
- the signature of function Braz differs in the number of arguments
- ...

**Comment by jonas-schievink** [comment]
The error generally already tells you what is missing: a trait implementation of `Foo` for the type `Bar`. If you have a concrete case where this error is unclear, please open another issue that includes a code example to reproduce the issue.
