### ISSUE TITLE
Rustdoc book mistake

### ISSUE THREAD

**Issue by zarix908** [rust-lang/rust#82266]
This page https://doc.rust-lang.org/rustdoc/what-is-rustdoc.html give instruction to create binary crate, but later use src/lib.rs file for example. Need to use src/main.rs file or create lib crate with --lib flag.

**Comment by jyn514** [comment]
Good catch, thanks! Are you interested in adding the `--lib` flag? You'd modify `src/doc/rustdoc/src/what-is-rustdoc.md`.

**Comment by jeanlucthumm** [comment]
@jyn514 May I grab this?

**Comment by jyn514** [comment]
@jeanlucthumm go for it!

**Comment by jeanlucthumm** [comment]
The [md file from the repo](https://github.com/rust-lang/rust/blob/master/src/doc/rustdoc/src/what-is-rustdoc.md) has the `--lib` flag but I don't see it on the [webpage](https://doc.rust-lang.org/rustdoc/what-is-rustdoc.html) are the two out of sync?

**Comment by jyn514** [comment]
Oh, this is fixed on nightly: https://doc.rust-lang.org/nightly/rustdoc/what-is-rustdoc.html#basic-usage
