### ISSUE TITLE
rustdoc: improve web search snippets

### ISSUE THREAD

**Issue by jsha** [rust-lang/rust#82283]
## Boilerplate

Some (but not all) search result snippets for rust items include the boilerplate "1.0.0[−][src]". Example screenshots below are linked to the Google search results page they are taken from.

Search results for "rust slice" show the boilerplate:
[![image](https://user-images.githubusercontent.com/220205/108453509-78225280-721f-11eb-8f38-ac9a8ee8c937.png)](https://www.google.com/search?q=rust+slice)

Search results for "rust slice" omit the boilerplate:
[![image](https://user-images.githubusercontent.com/220205/108453560-91c39a00-721f-11eb-9144-aa82142a8678.png)](https://www.google.com/search?q=rust+error)

Per https://developers.google.com/search/docs/advanced/appearance/good-titles-snippets and https://developers.google.com/search/docs/advanced/crawling/special-tags#data-nosnippet, we can wrap this particular piece of boilerplate in `<span data-nosnippet>` to omit it from snippets.

## Low-information meta descriptions

Also, search engines commonly make snippets from the `<meta name="description" value="...">` tag. The tag rustdoc currently generates is very low-information. For instance:

> API documentation for the Rust `slice` mod in crate `std`

> API documentation for the Rust `Error` trait in crate `std`.

It would be much better to fill this tag with the first sentence (or two) of actual documentation. For instance:

> A dynamically-sized view into a contiguous sequence, [T]. Slices are a view into a block of memory represented as a pointer and a length.

> Error is a trait representing the basic expectations for error values, i.e., values of type E in Result<T, E>.

**Comment by jyn514** [comment]
> It would be much better to fill this tag with the first sentence (or two) of actual documentation.

Rustdoc already does this for searches, it can use the same summaries for the title.

**Comment by jyn514** [comment]
This shouldn't have been closed, sorry, #82351 only addressed the "low information" part of the issue, not the "boilerplate" part.

**Comment by jsha** [comment]
I think Google must have rolled out some changes to their snippet algorithm. I can no longer reproduce the issue of snippets showing the `[-][src]` boilerplate. Closing.
