### ISSUE TITLE
warning of unreachable code which should be reachable

### ISSUE THREAD

**Issue by drahnr** [rust-lang/rust#82293]
I tried this code:

https://github.com/paritytech/sccache/pull/31/files#diff-f0fe090c387c4c299e2af7120bb7b6c0be1e2269a7a7215dbdec6975b66bfe0cR992-R1060

```rust
    let stdout = match str::from_utf8(&output.stdout) {
        Ok(s) => s,
        Err(_) => bail!("Failed to parse output"),
    };
    for line in stdout.lines() {
        //TODO: do something smarter here.
        match line {
            "clang" | "clang++" => {
                debug!("Found {}", line);
                return CCompiler::new(
                    Clang {
                        clangplusplus: line == "clang++",
                    },
                    executable,
                    &pool,
                )
                .await
                .map(|c| Box::new(c) as BoxDynCompiler<T>);
            }
            "nvcc" => {
                debug!("Found NVCC");
                return CCompiler::new(NVCC, executable, &pool)
                    .await
                    .map(|c| Box::new(c) as BoxDynCompiler<T>);
            }
            _ => {}, //continue,
        }

        let stderr = String::from_utf8_lossy(&output.stderr);
        debug!("nothing useful in detection output {:?}", stdout);
        debug!("compiler status: {}", output.status);
        debug!("compiler stderr:\n{}", stderr);
```

```
warning: unreachable statement
    --> src/compiler/compiler.rs:1057:9
     |
994  | /         match line {
995  | |             "clang" | "clang++" => {
996  | |                 debug!("Found {}", line);
997  | |                 return CCompiler::new(
...    |
1054 | |             _ => continue,
1055 | |         }
     | |_________- any code following this `match` expression is unreachable, as all arms diverge
1056 | 
1057 |           let stderr = String::from_utf8_lossy(&output.stderr);
     |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ unreachable statement
     |
     = note: `#[warn(unreachable_code)]` on by default
```

I expected to see this happen: *explanation*

No warning about unreachable statement, since the for loop is bounded.

Instead, this happened: *explanation*

Observerd a warning.

### Meta

`rustc --version --verbose`:
```
rustc 1.49.0 (e1884a8e3 2020-12-29)
binary: rustc
commit-hash: e1884a8e3c3e813aada8254edfa120e85bf5ffca
commit-date: 2020-12-29
host: x86_64-unknown-linux-gnu
release: 1.49.0
```

**Comment by drahnr** [comment]
Note that a simplified (sync) example does not exhibit the issue https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=6cd51605d7b8b31d9d519ac288d9217a so I would assume this is async only issue.

**Comment by jonas-schievink** [comment]
The unreachable code is *inside* the for loop, following the match. Since every arm of the match expression diverges, the code is indeed unreachable.

**Comment by SkiFire13** [comment]
Your posted code has `continue` commented out, while the one that gives the warning has it in the actual code.

The simplified example doesn't have a warning because the reachable part is outside the loop, while in the one that gives the warning is inside the loop but after the match. In fact [this code](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=9bb09682a8e92b9eeb9fa0d08bcf4338) shows the same warning.

The warning is actually right. In each branch you either `return` (and nothing else of that function is executed) or `continue` the loop (and nothing else in the loop but after the match is executed). This means that anything inside the loop but after the match is never executed.

**Comment by drahnr** [comment]
You are correct :facepalm: mea culpa.
