### ISSUE TITLE
rustdoc renders items synchronously 

### ISSUE THREAD

**Issue by rylev** [rust-lang/rust#82294]
Currently `rustdoc` is [rendering every item synchronously](https://github.com/rust-lang/rust/blob/8599bff5a3556059817503030e248507706e96b4/src/librustdoc/formats/renderer.rs#L84-L109) meaning that when there are many, many items, it takes longer than it would if these items could be processed in parallel. Moving this to being parallel won't be easy as `clean::Item` and `html::rendered::Context` are not `Send` for many different reasons some of which include the fact that they use datastructures from `rustc` that are not `Send` (which will rely on turning on parallel compilation to get working). 

First steps to improving this is to find out where most of the time in rendering is being spent and improving that.

**Comment by jyn514** [comment]
This and https://github.com/rust-lang/rust/issues/82741 are basically the same issue, but https://github.com/rust-lang/rust/issues/82741 has more detail, so closing this as a duplicate.
