### ISSUE TITLE
Rustdoc does not apply cfg(parallel_compiler) when bootstrapping

### ISSUE THREAD

**Issue by cjgillot** [rust-lang/rust#82301]
Found while testing #70951.

I tried this code:

In rustc_middle:
```rust
pub trait QueryEngine {
  #[cfg(parallel_compiler)]
  unsafe fn deadlock();
}
```

In downstream crate rustc_query_system:
```rust
impl QueryEngine for QueryCtxt {
  #[cfg(parallel_compiler)]
  unsafe fn deadlock() {}
}
```

I expected to see this happen: rustdoc run successfully.

Instead, this happened: rustdoc complains of missing impl-item `deadlock`.

My understanding is that `./x.py check` compiles with `parallel_compiler = true` and
puts the trait with `deadcode` in its metadata.
Rustdoc tries to document ignoring `parallel_compiler`,
so the function `deadcode` is missing.

### Meta
master at 8599bff5a355

**Comment by jyn514** [comment]
My understanding is that `cfg(parallel_compiler)` applies to rustdoc itself just fine, the issue is that rustdoc ignores the cfg when *documenting*. Is that correct?

**Comment by jyn514** [comment]
@cjgillot I can't reproduce this. I ran the following locally:
```
git checkout b52769b804a12b7045ee1bce893a64045cdb974a  # current HEAD
git revert 9823c2cc700fea541bf2670fcee93af662b63022.
x.py doc compiler/rustc
```
and all the commands succeeded.

**Comment by jyn514** [comment]
Oh, I forgot to set `parallel-compiler = true`. Yes, with that I can reproduce.
