### ISSUE TITLE
x86 `asm!` accepts "lock" as a standalone instruction

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/rust#82314]
```rust
#![feature(asm)]

#[no_mangle]
pub fn aaaaaaaaaaaaaaaaaa(x: &mut u32) {
    unsafe { asm!("lock"); }
    *x += 1;
}
```

This is not rejected, and, according to objdump, results in the following assembly (when optimizations are on):

```
0000000000000000 <aaaaaaaaaaaaaaaaaa>:
   0:	48 83 ec 08          	sub    $0x8,%rsp
   4:	f0 83 07 01          	lock addl $0x1,(%rdi)
   8:	58                   	pop    %rax
   9:	c3                   	ret    
```

I'd expect this to result in an error, since `lock` by itself isn't a valid instruction (it doesn't really seem desirable to let `asm!()` affect how rustc-produced instructions are decoded).

**Comment by thomcc** [comment]
It seems like a pretty esoteric case, and also hard to prevent in the general case.
