### ISSUE TITLE
`force-frame-pointers` on Windows does not allow directly unwinding

### ISSUE THREAD

**Issue by Swatinem** [rust-lang/rust#82333]
As a learning excercise, I’m trying to build my own stack unwinder, where I first read the `rsp` and `rbp` registers, and later on unwinding from them. (using `-Cforce-frame-pointers=yes` to get base pointers)

```rust
#![feature(asm)]

fn main() {
    never()
}

fn never() {
    gonna()
}
fn gonna() {
    give()
}
fn give() {
    you()
}
fn you() {
    up()
}
fn up() {
    let sp: usize;
    let bp: usize;
    let ip: usize;
    unsafe {
        asm!(
            "mov {sp}, rsp",
            "mov {bp}, rbp",
            "lea {ip}, [rip]",
            sp = out(reg) sp,
            bp = out(reg) bp,
            ip = out(reg) ip,
        );
    }
    trace_stack()
}

fn trace_stack() {
    let sp: usize;
    let bp: usize;
    let ip: usize;
    unsafe {
        asm!(
            "mov {sp}, rsp",
            "mov {bp}, rbp",
            "lea {ip}, [rip]",
            sp = out(reg) sp,
            bp = out(reg) bp,
            ip = out(reg) ip,
        );
    }

    let mut ip = ip;
    let mut bp = bp;
    for _ in 0..=5 {
        ip = unsafe { (bp as *const usize).offset(1).read() };
        bp = unsafe { (bp as *const usize).offset(0).read() };
    }
}
```

When compiling this on linux, or in the compiler explorer, I do get the following expected assembly:

```
example::up:
        push    rbp
        mov     rbp, rsp
        sub     rsp, 32

        mov     rax, rsp
        mov     rcx, rbp
        lea     rdx, [rip]
[...]
example::trace_stack:
        push    rbp
        mov     rbp, rsp
        sub     rsp, 160

        mov     rax, rsp
        mov     rcx, rbp
        lea     rdx, [rip]
```

However, compiling this on Windows gives me the following disassembly:

```
example::up:
        push    rbp
        sub     rsp, 64
        lea     rbp, [rsp + 64]

        mov     rax, rsp
        mov     rcx, rbp
        lea     rdx, [rip]
[...]
example::trace_stack:
        push    rbp
        sub     rsp, 192
        lea     rbp, [rsp + 128]

        mov     rax, rsp
        mov     rcx, rbp
        lea     rdx, [rip]
```

Notice how the `trace_stack` fn uses different offsets in the `sub` and `lea`. Also surprising that it is using `sub/lea` instead of the `mov/sub` that is generated on linux.

Not quite sure if this is really a miscompilation, or if I’m doing anything wrong here.

rustc:
```
rustc 1.52.0-nightly (07194ffcd 2021-02-10)
binary: rustc
commit-hash: 07194ffcd25b0871ce560b9f702e52db27ac9f77
commit-date: 2021-02-10
host: x86_64-pc-windows-msvc
release: 1.52.0-nightly
LLVM version: 11.0.1
```

**Comment by Kobata** [comment]
This appears to generally just be differences in calling conventions: The form for Windows matches the [Microsoft documentation](https://docs.microsoft.com/en-us/cpp/build/prolog-and-epilog)

Specifically, the frame pointer if used on Windows *does not* always equal the initial entry value of `rsp`, but is offset (by an amount that can be specific to each function, it can be anywhere from 0-240 and still be representable in [unwind info tables](https://docs.microsoft.com/en-us/cpp/build/exception-handling-x64)) with the reasoning given being that doing so allows for more offsets to be represented in one byte.

In general it's probably difficult to completely infeasible to properly unwind functions on x64 Windows without using the tables.

**Comment by Swatinem** [comment]
@Kobata Thanks for pointing me to this. I think this is really what is happening according to the examples given in the [exception handling docs](https://docs.microsoft.com/en-us/cpp/build/exception-handling-x64). From that perspective it makes total sense, just unfortunate that you can’t really use the `force-frame-pointers` option to use just reg/stack-based unwinding without consulting any side tables.

Anyhow, I think this issue should then be closed?

Or rather, the docs should be updated to reflect that the notion of "what is the frame pointer / base pointer" is actually platform dependant, with links that further explain those differences.
Alternatively, but I don’t think thats desirable? is if Rust itself defines "what is a frame pointer" that is consistent across platforms?

**Comment by nagisa** [comment]
Given the Kobata's comment, removed the unsound flag.

**Comment by Amanieu** [comment]
We don't make any guarantees about the contents of the frame pointer register in `asm!` blocks. The only thing we guarantee (unless `nostack` is used) is that the stack pointer can be used to allocate temporary stack memory for the duration of the `asm!` (the stack pointer must be restored to its original value on exit).
