### ISSUE TITLE
Rustdoc: emit hidden sections of doctest as <span hidden>

### ISSUE THREAD

**Issue by SoniEx2** [rust-lang/rust#82342]
It would be nice if rustdoc would emit hidden sections as `<span hidden>`, as those could be used to reconstruct the full doctests from the raw HTML. The rest of the docs are unimportant but having the doctests be easily machine-readable, even from the HTML, would be nice. (It somewhat easier to parse HTML than parse docs from source, after all. Mostly because HTML is ubiquitous so everyone has libs for it.)

**Comment by jyn514** [comment]
Parsing rustdoc HTML isn't really supported. I'd encourage you to use `--output-format json`; or if that doesn't work for your use case, open an issue as to why.

**Comment by SoniEx2** [comment]
The json format is too rustdoc-specific whereas HTML code blocks just work with general-purpose tools.

(... if only rustdoc would emit them as `<pre><code>` instead of just `<pre>`, that is)

**Comment by jyn514** [comment]
I'm going to close this, parsing the output HTML is not supported.
