### ISSUE TITLE
Standard streams hold a lock while executing arbitrary user code

### ISSUE THREAD

**Issue by tmiasko** [rust-lang/rust#82344]
The implementation of `Write::write_fmt` for `&Stdout` & `&Stderr` holds an
internal lock while executing an arbitrary user code. As a result, it might
introduce a lock order inversion and a deadlock, either between themselves or
another user held lock. For example:

```rust
use std::fmt::*;

#[derive(Copy, Clone)]
enum Print { Out, Err }

impl Display for Print {
    fn fmt(&self, _f: &mut Formatter) -> Result {
        match self {
            Print::Out => print!(""),
            Print::Err => eprint!(""),
        }
        Ok(())
    }
}

fn run() {
    for _ in 0..1000 {
        print!("{}", Print::Err);
        eprint!("{}", Print::Out);
    }
}

fn main() {
    let t = std::thread::spawn(run);
    run();
    t.join().unwrap();
}
```

**Comment by the8472** [comment]
https://doc.rust-lang.org/std/io/fn.stdout.html

> Each handle returned is a reference to a shared global buffer whose access is synchronized via a mutex. If you need more explicit control over locking, see the Stdout::lock method.

**Comment by tmiasko** [comment]
Let me clarify if existing description wasn't enough:

The synchronization could be at the level of write call (which doesn't execute
arbitrary user code) rather than formatting call (which does execute arbitrary
user code), avoiding deadlock in this situation.

In the case user takes the lock manually, I would expect them to have
responsibility to avoid such problems.

**Comment by the8472** [comment]
> The synchronization could be at the level of write call

Wouldn't that require additional buffering to maintain the no-tearing properties that the lock offers?

**Comment by m-ou-se** [comment]
There's no limit to the amount of data the user-provided formatting code might write, so we can't buffer it all and might have to write it in multiple bursts while the formatting code is still running. As @the8472 said, we'll have to keep the lock around during that time to make sure the output doesn't interleave with that of other threads.

So, I don't think this issue is actionable.
