### ISSUE TITLE
Using a const generic enum on stable links to `min_const_generics` issue which is closed.

### ISSUE THREAD

**Issue by alercah** [rust-lang/rust#82386]
Given the following code: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=8954b7837e80fbfce7d6a1d3d1ad0f89

The current output is:

```
error[E0658]: const generics are unstable
  --> src/main.rs:10:30
   |
10 |     pub struct Machine<const S: State> {
   |                              ^
   |
   = note: see issue #74878 <https://github.com/rust-lang/rust/issues/74878> for more information
```

But issue 74878 is closed and represents a feature released on stable. This link needs to be updated.

**Comment by ehuss** [comment]
The error message has already been updated as part of stabilizing the feature.  Issues are closed as soon as they land on master/nightly, and it may take 6 to 12 weeks for that to reach the stable release.

The current beta channel message is:

```
error: `State` is forbidden as the type of a const generic parameter
  --> src/main.rs:10:33
   |
10 |     pub struct Machine<const S: State> {
   |                                 ^^^^^
   |
   = note: the only supported types are integers, `bool` and `char`
   = help: more complex types are supported with `#![feature(const_generics)]`
```

**Comment by JohnTitor** [comment]
Closing in favor of the above comment.
