### ISSUE TITLE
crate or mod  need init(), like golang;

### ISSUE THREAD

**Issue by sstudioer** [rust-lang/rust#82384]
crate or mod  need init(), like golang;

example:  rand package  need set a dynamic seed with timestamp,  at init() ;

**Comment by tesuji** [comment]
In general, Rust doesn't favor global states like `srand` in C.
You should open an issue with rand crate.
Also, I think rand crate works well enough in most cases. 
What are your problems with how rand works?

**Comment by thomcc** [comment]
You can use crates like [`ctor`](https://crates.io/crates/ctor)` or [`startup`](https://crates.io/crates/startup) to get this. Note that it comes with caveats.

**Comment by jonas-schievink** [comment]
Hi! Additions or changes to the language need to go through our [RFC process](https://github.com/rust-lang/rfcs). Before an RFC is written, the feature can also be discussed in our [internals forum](https://internals.rust-lang.org/) to find other people interested in it.

Closing in favor of an RFC.
