### ISSUE TITLE
【1.45.2】 More error information is provided when the bottom-layer commands of the operating system fail to be invoked.

### ISSUE THREAD

**Issue by silence-coding** [rust-lang/rust#82388]
There is too little confidence in this mistake, why not return to errno. The mmap interface provides the errno, such as the ENOMEM and SIGSEGV interfaces.

/rust/src/libstd/sys/unix/stack_overflow.rs:150
panic!("failed to allocate an alternative stack")

**Comment by silence-coding** [comment]
![image](https://user-images.githubusercontent.com/32766901/108670875-95ef0080-751a-11eb-81d3-8b72b9ef2c6d.png)

**Comment by tesuji** [comment]
Please try again your code latest nightly Rust version. Also could you paste the ICE backtrace?

@rustbot label E-needs-mcve I-ICE

**Comment by 12101111** [comment]
@tesuji This is not a ICE
This issue propose printing errno on this `panic`: https://github.com/rust-lang/rust/blob/e952db8fd02090a10024ae63ba9d34e3b9cef898/library/std/src/sys/unix/stack_overflow.rs#L142-L153

**Comment by thomcc** [comment]
Probably we want this then:

@rustbot label: -I-ICE, -T-compiler, +T-libs
