### ISSUE TITLE
cannot publish crates under CAL-1.0 license

### ISSUE THREAD

**Issue by thedavidmeister** [rust-lang/rust#82390]
I cannot publish crates using the `CAL-1.0` license

```
error: api errors (status 200 OK): unknown license or other term: CAL-1.0; see http://opensource.org/licenses for options, and http://spdx.org/licenses/ for their identifiers
```

here is the link to the `CAL-1.0` on opensource.org: https://opensource.org/licenses/CAL-1.0

I tried this code:

```rust
cargo publish --all-features
```

I expected to see this happen: published crate to crates.io

Instead, this happened: error about license

### Meta

`rustc --version --verbose`:
```
[nix-shell:~/holochain/crates/fixt]$ rustc --version --verbose
rustc 1.48.0 (7eac88abb 2020-11-16)
binary: rustc
commit-hash: 7eac88abb2e57e752f3302f02be5f3ce3d7adfb4
commit-date: 2020-11-16
host: x86_64-unknown-linux-gnu
release: 1.48.0
LLVM version: 11.0
```

**Comment by thomcc** [comment]
I think this might belong in https://github.com/rust-lang/crates.io

**Comment by est31** [comment]
I think it belongs not there but https://github.com/rust-lang-nursery/license-exprs

**Comment by est31** [comment]
In particular, see https://github.com/rust-lang-nursery/license-exprs/pull/34

**Comment by thedavidmeister** [comment]
sure

**Comment by nickbp** [comment]
Does anyone own that license-exprs repo? It's had an update PR waiting since early September
