### ISSUE TITLE
Diff on rustdoc test failure does not work on Windows

### ISSUE THREAD

**Issue by rylev** [rust-lang/rust#82409]
When running `x .py test .\src\test\rustdoc` on Linux and a failure happens, a really nice diff of the output vs rustdoc-nightly is produced which very clearly shows the issue. This does not work on Windows for multiple reasons. 

One the call to `diff` fails:
```powershell
info: generating a diff against nightly rustdoc
warning: no pager configured, falling back to `diff --color`
help: try configuring a git pager (e.g. `delta`) with `git config --global core.pager delta`
thread '[rustdoc] rustdoc\sidebar-link-generation.rs' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "The system cannot find the file specified." }', src\tools\compiletest\src\runtest.rs:2467:55
```

Second, the output from rustdoc-nightly seems to exactly match that from the local compiler making it not possible to do manual diffs.

**Comment by jyn514** [comment]
> One the call to diff fails:

How do you diff directories recursively on Windows? On Linux I would be very surprised for `diff` not to be installed.

> The output from rustdoc-nightly seems to exactly match that from the local compiler

Oh I just thought of something - do you have a rustup overide that defaults to your local toolchain? Right now compiletest assumes the default is nightly, I've been meaning to change it.

**Comment by rylev** [comment]
>  do you have a rustup overide that defaults to your local toolchain? 

No, I only set overrides on specific projects (and rust-lang/rust is not one of them). My default is the stable compiler.

**Comment by mati865** [comment]
Git for Windows provides `diff`:
```
$ which diff
/usr/bin/diff
```
Are you building Rust using Git Bash prompt?

**Comment by rylev** [comment]
I don't think it'd be a good idea to require testing rustdoc in the Git for Windows bash shell. I'd like for this to work in cmd.exe and PowerShell if possible.
