### ISSUE TITLE
Module is private even when marked as public.

### ISSUE THREAD

**Issue by limchiahau** [rust-lang/rust#82444]
In my binary crate, I called a function within a public module but the compiler says that the module could not be found. 

A sample of the code is as below:

In main.rs:
```
extern crate communicator;

fn main() {
    communicator::client::connect();
}
```

In my lib.rs:
```
#[cfg(test)]
pub mod client;

mod network;
```

The strange thing is that if I reverse the order in lib.rs, the client module is now correctly public. Something like this:

```
#[cfg(test)]
mod network;

pub mod client;
```

I believe this is a bug.

**Comment by jonas-schievink** [comment]
`#[cfg(test)]` is only active when building the library for unit testing

**Comment by limchiahau** [comment]
Am able to verify that `#[cfg(test)]` is the thing that's causing my issue.

Note: The example code in the book "The Rust Programming Language" 2018 version doesn't work as expected because of this.
