### ISSUE TITLE
confusing diagnostic about allocator_api feature

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#82452]
````rust
struct Stats {
    list: Vec<String, String>,
}
````
The Strings were supposed to be inside a tuple, 
````rust
struct Stats {
    list: Vec<(String, String)>,
}
````
but instead of a some kind of a mismatched argument number message, I got a warning about `allocator_api` :sweat_smile: 

````

  Compiling playground v0.0.1 (/playground)
error[E0658]: use of unstable library feature 'allocator_api'
 --> src/lib.rs:2:23
  |
2 |     list: Vec<String, String>,
  |                       ^^^^^^
  |
  = note: see issue #32838 <https://github.com/rust-lang/rust/issues/32838> for more information
  ````

**Comment by jyn514** [comment]
Hmm, I'm not sure how the compiler could improve here - it's correct, Vec has two type parameters, one of which defaults to the global allocator: https://doc.rust-lang.org/stable/src/alloc/vec.rs.html#301-304.

**Comment by TaKO8Ki** [comment]
#90856 has already solved this problem.
