### ISSUE TITLE
rustdoc drops impl Foreign<Local> for Foreign

### ISSUE THREAD

**Issue by guswynn** [rust-lang/rust#82465]
I tried this code:

```rust
use std::convert::AsRef;
pub struct Gus;

impl AsRef<str> for Gus {
    fn as_ref(&self) -> &str {
        todo!()
    }
}

impl AsRef<Gus> for str {
    fn as_ref(&self) -> &Gus {
        todo!()
    }
}
```

with `cargo doc` I get:
![image](https://user-images.githubusercontent.com/5404303/108947539-84d6ea00-7615-11eb-9d70-c275910f9152.png)

with `cargo +nightly` I get:
![image](https://user-images.githubusercontent.com/5404303/108947620-acc64d80-7615-11eb-88c8-ba5021b19964.png)

### Meta

stable: `rustc 1.50.0 (cb75ad5db 2021-02-10)`
nightly: `rustc 1.52.0-nightly (d1206f950 2021-02-15)` but this also affects whatever nightly docs.rs is on (https://docs.rs/camino/1.0.0/camino/struct.Utf8Path.html#impl-AsRef%3Cstr%3E is missing the `for str` impl

(separately, I hit https://github.com/rust-lang/cargo/issues/6783 when testing this, where `cargo +stable doc --open` still used the nightly generated code)

**Comment by guswynn** [comment]
this also appears to affect beta: 
![image](https://user-images.githubusercontent.com/5404303/108948145-c4520600-7616-11eb-8c0f-065bd5ff8463.png)

**Comment by jyn514** [comment]
>  nightly: rustc 1.52.0-nightly (d1206f950 2021-02-15) but this also affects whatever nightly docs.rs is on (https://docs.rs/camino/1.0.0/camino/struct.Utf8Path.html#impl-AsRef%3Cstr%3E is missing the for str impl

That's `rustc 1.52.0-nightly (a15f484b9 2021-02-22)`, so your nightly is actually earlier.

**Comment by apiraino** [comment]
Assigning `P-high` as discussed as part of the [Prioritization Working Group procedure](#) and removing `I-prioritize`.

@rustbot label -I-prioritize +P-high

**Comment by GuillaumeGomez** [comment]
The commit responsible is this one: https://github.com/rust-lang/rust/commit/937f629535f38c655267f1ed21ce6830f592f5df from https://github.com/rust-lang/rust/pull/80653

**Comment by GuillaumeGomez** [comment]
Actually, I'm wondering about something: why should we see `impl AsRef<Gus> for str` on the `Gus` page? It's not implemented on `Gus` after all...

**Comment by guswynn** [comment]
@GuillaumeGomez because it's both 1. An api that the crate creates (the way I found this was I saw a str.as_ref call in some code I was reading in the camino crate imma fn that returned a &Utf8Path, that public api was not exposed on doc.rs) and 2. Can't be on the docs for the foreign type (as this impl is in the local crate) 

This is definitely a really specific case of coherence, but it would be a downgrade to lose this in docs

**Comment by pnkfelix** [comment]
Discussed in [T-compiler triage meeting](https://zulip-archive.rust-lang.org/238009tcompilermeetings/19557weekly2021042954818.html#236680594). We're going to revert PR #80653 as a way to fix this in the short-term, while the kinks get worked out in the appropriate fix to get this all working (with #80653) again.

**Comment by pietroalbini** [comment]
A revert for this was backported in both stable 1.52.0 and beta 1.53.0, so it only affects nightly 1.54.0 now. Updating the labels accordingly.

**Comment by jyn514** [comment]
>  it only affects nightly 1.54.0 now

The revert should also have been applied to nightly - is https://github.com/rust-lang/rust/pull/84867 only landing on 1.53? It should land on 1.54 too if so.

**Comment by pietroalbini** [comment]
@jyn514 well that PR didn't land on 1.54 *yet* :)

**Comment by pietroalbini** [comment]
This has been fixed by https://github.com/rust-lang/rust/pull/84867 on 1.54 too.
