### ISSUE TITLE
proc macro (derive) does not recognized as ambiguous intra doc link

### ISSUE THREAD

**Issue by pickfire** [rust-lang/rust#82478]
I tried this code:

```rust
/// [`Dummy`] should be ambiguous. But it works.
pub trait Dummy<T>: Sized {
}

#[cfg(feature = "derive")]
pub use dummy::Dummy; // this is a derive macro
```

Try doing that on https://github.com/cksac/fake-rs crate or serde

I expected to see this happen: ambiguous `Dummy` link found, use explicit `macro@Dummy`.

Instead, this happened: It compiles

**Comment by jyn514** [comment]
This is intentional: https://github.com/rust-lang/rust/blob/6b56603e35b39c9f6cc76782330e5e415f9e43d5/src/librustdoc/passes/collect_intra_doc_links.rs#L808. Otherwise every time you linker to Copy or Debug you'd get an ambiguity error.

**Comment by pickfire** [comment]
>  Otherwise every time you link to Copy or Debug you'd get an ambiguity error.

But what about other crates? It would be weird that users does not know about that? Should we make `Copy` and `Debug` special case that we can ignore for warning? Otherwise users can easily link to the wrong link. Or maybe we should just warn after all.

**Comment by jyn514** [comment]
This was documented in https://github.com/rust-lang/rust/pull/110328. I'm going to close this since we're not planning to change the behavior.
