### ISSUE TITLE
rustdoc: "List of all items" title shown twice

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#82477]
As can be seen when going to https://doc.rust-lang.org/nightly/std/all.html, the "List of all items" page generated by rustdoc has a header saying "List of all items List of all items":
![Screenshot_2021-02-24 List of all items in this crate](https://user-images.githubusercontent.com/330628/109009669-18102e00-76af-11eb-957f-8ff1112ad2c0.png)

**Comment by jyn514** [comment]
Mentoring instructions: remove this line: https://github.com/rust-lang/rust/blob/6b56603e35b39c9f6cc76782330e5e415f9e43d5/src/librustdoc/html/render/mod.rs#L1346

**Comment by jyn514** [comment]
I think this regressed in https://github.com/rust-lang/rust/pull/81398. cc @bugadani, do you have time to take a look?

**Comment by bugadani** [comment]
How did that happen... Whoops, I'll fix asap

@rustbot claim
