### ISSUE TITLE
[rustdoc]: Explain what ESC does in the help box

### ISSUE THREAD

**Issue by tesuji** [rust-lang/rust#82474]
I think we could include a text to explain what ESC does after #82234 merged.
![image](https://user-images.githubusercontent.com/15225902/109003573-30e20900-76da-11eb-8b09-dc6f378f3977.png)

This helps increasing popularity of the feature. Also, should we need to tag relnotes for the above PR ?

**Comment by jyn514** [comment]
Mentoring instructions: Add an entry for `esc` in https://github.com/rust-lang/rust/blob/6b56603e35b39c9f6cc76782330e5e415f9e43d5/src/librustdoc/html/static/main.js#L2906.

**Comment by TaKO8Ki** [comment]
I'm interested in working on this issue!
@rustbot claim

**Comment by TaKO8Ki** [comment]
close this issue because esc doesn't do anything out of the ordinary. ref https://github.com/rust-lang/rust/pull/82522#issuecomment-786868292

**Comment by TaKO8Ki** [comment]
@jyn514 
Could you close this issue?
