### ISSUE TITLE
Tracking Issue for `#![feature(const_socketaddr)]`

### ISSUE THREAD

**Issue by CDirkx** [rust-lang/rust#82485]
Feature gate: `#![feature(const_socketaddr)]`

This is a tracking issue for constifying methods of `std::net::SocketAddr`, `SocketAddrV4` and `SocketAddrV6`.

### Public API

```rust
// std::net

impl SocketAddr {
   pub const fn new(ip: IpAddr, port: u16) -> Self;
    pub const fn ip(&self) -> IpAddr;
    pub const fn port(&self) -> u16;
    pub const fn is_ipv4(&self) -> bool;
    pub const fn is_ipv6(&self) -> bool;
}

impl SocketAddrV4 {
    pub const fn new(ip: Ipv4Addr, port: u16) -> Self;
    pub const fn ip(&self) -> IpAddr;
    pub const fn port(&self) -> u16;
}

impl SocketAddrV6 {
    pub const fn new(ip: Ipv6Addr, port: u16, flowinfo: u32, scope_id: u32) -> Self;
    pub const fn ip(&self) -> IpAddr;
    pub const fn port(&self) -> u16;
    pub const fn flowinfo(&self) -> u32;
    pub const fn scope_id(&self) -> u32;
}
```

### Steps / History

- [x] Implementation:  #82487
- [x] Final commenting period (FCP)
- [ ] Stabilization PR

### Unresolved Questions

~~The methods `new` on all of the address could potentially also be made const, however there are two complications: getting the inner C representation of an IP address, and adding trailing zero bytes on windows.~~ Resolved by https://github.com/rust-lang/rust/pull/78802

**Comment by a1ien** [comment]
What about SocketAddr::new? If we make const `ip`, `port` and and so on how we create const `SocketAddr` it self

**Comment by faern** [comment]
This feature gate is soon also used for the unstably constified methods `SocketAddr::new`, `SocketAddrV4::new`, `SocketAddrV6::new` if #78802 is merged.

**Comment by maxwase** [comment]
I guess there are no blockers for this stabilization?

**Comment by faern** [comment]
Probably not. Try submitting a stabilization PR.

**Comment by m-ou-se** [comment]
The API overview above seems incomplete. At least [SocketAddr::new()](https://doc.rust-lang.org/stable/std/net/enum.SocketAddr.html#method.new) also refers to this issue. Are there any other methods missing?

**Comment by m-ou-se** [comment]
Looks like it's only the three new methods. The issue with those has been resolved by https://github.com/rust-lang/rust/pull/78802

**Comment by m-ou-se** [comment]
@rfcbot merge

**Comment by dtolnay** [comment]
I'm marking @yaahc's box because she has stepped down from T-libs-api after the point that this feature got proposed for FCP.
