### ISSUE TITLE
"error: unresolved import xxx” when compiling with the #![no_std] flag

### ISSUE THREAD

**Issue by Rynibami** [rust-lang/rust#82505]
Long story short: I tried to compile my code (as shown below) into machine code for an AVR Microcontroller (atmega2560), but I got an errors that should not be there: “error: unresolved import pins” and “no external crate pins".

```rust
// main.rs
#![no_std]
#![no_main]

use core::panic::PanicInfo;
use pins;

const PORTB : Port = Port::new_from_index(0x23);

#[no_mangle]
pub extern "C" fn main(_argc: isize, _argv: *const *const u8) -> ! {
    PORTB.init(0b_1111_1111, 0b_1111_1111);
    loop{}
}


#[panic_handler]
fn handle_panic(_info: &PanicInfo) -> ! {
    loop {}
}
```

```rust
// pins.rs
#[repr(C)]
pub struct Port {
    pin     : *mut u8,  // the input pin register
    ddr     : *mut u8,  // the data director register
    port    : *mut u8,  // the data register
}

impl Port {

    /// creates a new instance of port
    pub const fn new(pin: u8, ddr: u8, port: u8) -> Port {
        Port { 
            pin:    pin as *mut u8, 
            ddr:    ddr as *mut u8,
            port:   port as *mut u8,
        }
    }

    /// creates a new instance of port from a starting address
    pub const fn new_from_index(pin: u8) -> Port {
        Port { 
            pin:    (pin + 0) as *mut u8, 
            ddr:    (pin + 1) as *mut u8,
            port:   (pin + 2) as *mut u8,
        }
    }

    /// initialized the value of the port
    pub fn init(&self, ddr: u8, port: u8) {
        unsafe {
            core::ptr::write_volatile(self.ddr, ddr);
            core::ptr::write_volatile(self.port, port);
        }
    }
    
    #[inline(always)]
    pub fn read_pin_raw(&self) -> u8 {
        unsafe { core::ptr::read_volatile(self.pin) }
    }

    #[inline(always)]
    pub fn read_ddr_raw(&self) -> u8 {
        unsafe { core::ptr::read_volatile(self.ddr) }
    }

    #[inline(always)]
    pub fn read_port_raw(&self) -> u8 {
        unsafe { core::ptr::read_volatile(self.port) }
    }

    #[inline(always)]
    pub fn read_port(&self) -> u8 {
        let ddr = self.read_ddr_raw();
        ddr & self.read_pin_raw()
    }

    #[inline(always)]
    pub fn write_raw(&self, value: u8) {
        unsafe { core::ptr::write_volatile(self.port, value) }
    }

    #[inline(always)]
    pub fn write(&self, value: u8) {
        let ddr = self.read_ddr_raw();
        self.write_raw(value & ddr);
    }
}
```

I expected to see my file being imported so I could work with the pins. After looking for hours, I just removed the `#![no_std]` to see if that would change anything to my errors and they disappeared. I think the `#![no_std]` flag somehow corrupts the `use` keyword on non-pre-included modules.

### Meta

I could only check this bug in the current version (displayed below), because another bug of all newer versions prevented me from even being able to compile my code.

`rustc --version --verbose`:
```
rustc 1.51.0-nightly (c2de47a9a 2021-01-06)
binary: rustc
commit-hash: c2de47a9aa4c9812884f341f1852e9c9610f5f7a
commit-date: 2021-01-06
host: x86_64-apple-darwin
release: 1.51.0-nightly
```

I cannot add a backtrace, because I’m cross compiling this small program and I’m not that experienced to write my own backtrace.

[project.zip](https://github.com/rust-lang/rust/files/6039932/project.zip)

</details>

**Comment by ehuss** [comment]
It's a common point of confusion.  It needs to have `mod pins;`, not `use pins;`.  `mod` is used to define a module.  `use` is if you want a short alias for something.

More information can be found in the [chapter of the book on modules](https://doc.rust-lang.org/book/ch07-02-defining-modules-to-control-scope-and-privacy.html), or [this blog post](http://www.sheshbabu.com/posts/rust-module-system/) has also helped people.
