### ISSUE TITLE
Rustc cross-compiling to aarch64-unknown-linux-gnu uses wrong compiler

### ISSUE THREAD

**Issue by caverym** [rust-lang/rust#82519]
Cross compiling from x86_64 to aarch64 uses `/usr/bin/ld` instead of `/usr/bin/aarch64-linux-gnu-ld`
This happens using stable and nightly version of rust toolchians/targets

### Code
any simple code 
```Rust
fn main() {
    println!("a message");
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.52.0-nightly (a15f484b9 2021-02-22)
binary: rustc
commit-hash: a15f484b918a4533ad633ea903ccce82910af342
commit-date: 2021-02-22
host: x86_64-unknown-linux-gnu
release: 1.52.0-nightly
LLVM version: 11.0.1
```

### Error output
`RUST_BACKTRACE=1 cargo build --target aarch64-unknown-linux-gnu`

```
  = note: /usr/bin/ld: /home/avery/Documents/git/plage/target/aarch64-unknown-linux-gnu/debug/deps/plage-7843fadef320354a.1115kt21cxrb61jx.rcgu.o: Relocations in generic ELF (EM: 183)
          /usr/bin/ld: /home/avery/Documents/git/plage/target/aarch64-unknown-linux-gnu/debug/deps/plage-7843fadef320354a.1115kt21cxrb61jx.rcgu.o: Relocations in generic ELF (EM: 183)
          /usr/bin/ld: /home/avery/Documents/git/plage/target/aarch64-unknown-linux-gnu/debug/deps/plage-7843fadef320354a.1115kt21cxrb61jx.rcgu.o: Relocations in generic ELF (EM: 183)
          /usr/bin/ld: /home/avery/Documents/git/plage/target/aarch64-unknown-linux-gnu/debug/deps/plage-7843fadef320354a.1115kt21cxrb61jx.rcgu.o: Relocations in generic ELF (EM: 183)
          /usr/bin/ld: /home/avery/Documents/git/plage/target/aarch64-unknown-linux-gnu/debug/deps/plage-7843fadef320354a.1115kt21cxrb61jx.rcgu.o: Relocations in generic ELF (EM: 183)
          /usr/bin/ld: /home/avery/Documents/git/plage/target/aarch64-unknown-linux-gnu/debug/deps/plage-7843fadef320354a.1115kt21cxrb61jx.rcgu.o: Relocations in generic ELF (EM: 183)
          /usr/bin/ld: /home/avery/Documents/git/plage/target/aarch64-unknown-linux-gnu/debug/deps/plage-7843fadef320354a.1115kt21cxrb61jx.rcgu.o: Relocations in generic ELF (EM: 183)
          /usr/bin/ld: /home/avery/Documents/git/plage/target/aarch64-unknown-linux-gnu/debug/deps/plage-7843fadef320354a.1115kt21cxrb61jx.rcgu.o: Relocations in generic ELF (EM: 183)
          /usr/bin/ld: /home/avery/Documents/git/plage/target/aarch64-unknown-linux-gnu/debug/deps/plage-7843fadef320354a.1115kt21cxrb61jx.rcgu.o: Relocations in generic ELF (EM: 183)
          /usr/bin/ld: /home/avery/Documents/git/plage/target/aarch64-unknown-linux-gnu/debug/deps/plage-7843fadef320354a.1115kt21cxrb61jx.rcgu.o: Relocations in generic ELF (EM: 183)
          /usr/bin/ld: /home/avery/Documents/git/plage/target/aarch64-unknown-linux-gnu/debug/deps/plage-7843fadef320354a.1115kt21cxrb61jx.rcgu.o: Relocations in generic ELF (EM: 183)
          /usr/bin/ld: /home/avery/Documents/git/plage/target/aarch64-unknown-linux-gnu/debug/deps/plage-7843fadef320354a.1115kt21cxrb61jx.rcgu.o: error adding symbols: file in wrong format
          collect2: error: ld returned 1 exit status
```

`file plage-7843fadef320354a.1115kt21cxrb61jx.rcgu.o`
```
plage-7843fadef320354a.1115kt21cxrb61jx.rcgu.o: ELF 64-bit LSB relocatable, ARM aarch64, version 1 (SYSV), with debug_info, not stripped
```

</p>
</details>

**Comment by caverym** [comment]
The issue comes from it using the wrong `cc` compiler. It prints out a very long command before the errors using "cc", copying it and chaning `cc` to `aarch64-linux-gnu-gcc` it works without any errors. This means `rustc` is calling the wrong compiler.

**Comment by nagisa** [comment]
rustbuild may use heuristics to figure out some default, but ultimately these are heuristics. Those can be infinitely improved, but AFAIK its ultimately the responsibility of the users who are cross-compiling to specify the toolchain to use. In particular the `target.{target}.linker` variable for what `linker` to use.

**Comment by nagisa** [comment]
Ah, my bad, I missed that this is not about rustbuild, but about using rustc in crosscompiling regular programs.

As far as I know there are no such heuristics when invoking plain rustc. It _is_ a responsibility of the user to specify the linkers etc to use (via e.g. `-Clinker` when invoking rustc directly and via corresponding configuration in cargo when building via cargo).

**Comment by caverym** [comment]
```
  [target.aarch64-unknown-linux-gnu]
  linker = "aarch64-linux-gnu-ld"
```

`cargo +nightly b --target aarch64-unknown-linux-gnu`

still uses the incorrect compiler and linker (`cc` & `/usr/bin/ld`)

**Comment by nagisa** [comment]
That would mean its either a bug in cargo, or cargo can't find your cargo config (as documented [here](https://doc.rust-lang.org/cargo/reference/config.html)). Where did you put the file with these contents?

Another caveat is that you want to use `aarch64-linux-gnu-cc` as your `linker`, rather than the bare `ld` – there is a way to use `ld` (`-Clinker-flavor=ld`), but by default we rely on `cc` to do the job of finding the libraries, etc.

**Comment by caverym** [comment]
Cargo.toml works now. Thank you for the help.
