### ISSUE TITLE
`extend_from_within` leaks elements on panic

### ISSUE THREAD

**Issue by LeonineKing1199** [rust-lang/rust#82533]
https://github.com/rust-lang/rust/blob/98f8cce6db6c6c6660eeffee2b3903104e547ecf/library/alloc/src/vec/mod.rs#L2163-L2182

Looking here, the internal length of the vector is only adjusted at the end of the loop

This has the caveat that if cloning panics, the Vec will start to unwind and only drop the first `len` elements which doesn't include the most recently appended ones.

Something more in line with how the stdlib does things might look like this:
https://github.com/LeonineKing1199/minivec/blob/424354dfababae7101aacf70fa9332a87e9cdb15/src/lib.rs#L1612-L1700

**Comment by jyn514** [comment]
> This has the caveat that if cloning panics, the Vec will start to unwind and only drop the first len elements which doesn't include the most recently appended ones.

This is not unsafe, leaking items is safe: https://github.com/rust-lang/rust/issues/24456.

**Comment by LeonineKing1199** [comment]
> This is not unsafe, leaking items is safe: #24456.

Sure; never said it was unsafe.

This is more about making sure programs who gracefully handle panics don't wind up eventually exhausting resources.

**Comment by hameerabbasi** [comment]
Assigning `P-medium` as part of the [`WG-prioritization` discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2382533.20No.20Panic.20Safety.20in.20.60extend_from_within.60).

**Comment by WaffleLapkin** [comment]
I would like to fix this

@rustbot claim

**Comment by LeonineKing1199** [comment]
The fix seems pretty straight-forward. 

The Clone specialization just needs a RAII type that handles adjusting the Vec's new len in its Drop implementation, as I've linked in my MiniVec.

Copy can't fail so there's no need to adjust that specialization. The only thing that could theoretically panic in that case would be reallocating and in that case, there's no need to worry about the len.
