### ISSUE TITLE
why executes two times this code "match self.inner.mkdir(path)" in function create_dir_all of std/src/fs.rs ?

### ISSUE THREAD

**Issue by magj2006** [rust-lang/rust#82555]
Hello, 

why executes two times this code "match self.inner.mkdir(path)" in function create_dir_all of std/src/fs.rs as shown below ?

<img width="727" alt="屏幕快照 2021-02-26 下午9 49 28" src="https://user-images.githubusercontent.com/8394789/109330972-15176800-787e-11eb-92f3-01ad0542cc85.png">

**Comment by the8472** [comment]
It's a fast path in the case the directory already exists.

**Comment by osa1** [comment]
I wonder if it might make sense to add a line of comment here, something like `// Fast path when the parent directory already exists`.

**Comment by magj2006** [comment]
I just thought the second mkdir is not must necessary, yes ?

**Comment by the8472** [comment]
`/A/B/C/D/E`

A-B exist
C-E do not exist

1st block tries to create E as the fast path but fails since the parent doesn't exist either.
Middle part recursively tries to create A-D, will actually create C, D since A and B already exist.
Last part finally creates E.

**Comment by magj2006** [comment]
@the8472 so appreciate.
