### ISSUE TITLE
Bad diagnostics when using associated const on type without turbofish 

### ISSUE THREAD

**Issue by BoxyUwU** [rust-lang/rust#82566]
Given the following code: [here](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=f95f5712fc22fdf85aa2a28b4eaf3e7a)

```rust
struct Add<const N1: usize, const N2: usize>;
impl<const N1: usize, const N2: usize> Foo<N1, N2> {
    const SUM: usize = N1 + N2;
}
fn foo() -> [(); Add<10, 12>::SUM] {
    todo!()
}
```

The current output is:

```
error: expected one of `.`, `?`, `]`, or an operator, found `,`
 --> src/lib.rs:5:24
  |
5 | fn foo() -> [(); Add<10, 12>::SUM] {
  |                        ^ expected one of `.`, `?`, `]`, or an operator

error: aborting due to previous error

error: could not compile `playground`
```

Ideally the output should mention that the user needs to use a turbofish here:
`Add::<10, 12>::SUM`

cc @lcnr

**Comment by lcnr** [comment]
the help message seems to only be missing if there are 2 const arguments:
```rust
struct Foo<const N: usize, const M: usize>;
impl Foo<3, 4> {
    const SUM: () = ();
}

fn main() {
    Foo<3, 4>::SUM
}
```
using type parameters or just one const param causes a useful help message
```rust
struct Foo<const N: usize>;
impl Foo<3> {
    const SUM: () = ();
}

fn main() {
    Foo<3>::SUM
}
```

**Comment by osa1** [comment]
It turns out @lcnr 's repro is different than the original repro. My PR fixes @lcnr 's examples but not the original one. I'll update it to fix the original one too.

**Comment by osa1** [comment]
All fixed.
