### ISSUE TITLE
Diagnostics: suggest using `array::IntoIter::new` to iterate over arrays

### ISSUE THREAD

**Issue by yoshuawuyts** [rust-lang/rust#82602]
When following [the const-generics beta MVP blog post](https://blog.rust-lang.org/2021/02/26/const-generics-mvp-beta.html#by-value-array-iterator) we ran into this diagnostics error. The blog post specifically requests filing const-generics related diagnostics issues, so here goes!

- Rust 1.51.0-beta.3 (2021-02-24)

Given [the following code](https://play.rust-lang.org/?version=beta&mode=debug&edition=2018&gist=7e363f7458363ff7285eb8192add8922):

```rust
use std::array;
fn needs_vec(v: Vec<i32>) {
    // ...
}

let arr = [vec![0, 1], vec![1, 2, 3], vec![3]];
for elem in arr {
    needs_vec(elem);
}
```

The current output is:

```
error[E0277]: `[Vec<{integer}>; 3]` is not an iterator
 --> src/main.rs:8:17
  |
8 |     for elem in arr {
  |                 ^^^ borrow the array with `&` or call `.iter()` on it to iterate over it
  |
  = help: the trait `Iterator` is not implemented for `[Vec<{integer}>; 3]`
  = note: arrays are not iterators, but slices like the following are: `&[1, 2, 3]`
  = note: required because of the requirements on the impl of `IntoIterator` for `[Vec<{integer}>; 3]`
  = note: required by `into_iter`
```

Ideally the output should look like:

```
error[E0277]: `[Vec<{integer}>; 3]` is not an iterator
 --> src/main.rs:8:17
  |
8 |     for elem in arr {
  |                 ^^^ call `array::IntoIter::new(arr)` to iterate over the array
  |
  = help: the trait `Iterator` is not implemented for `[Vec<{integer}>; 3]`
```

**Comment by leonardo-m** [comment]
Isn't it better to wait for shorter ways to iterate an array by value?

**Comment by yoshuawuyts** [comment]
@leonardo-m it's unclear when, or even *if* such a method will land (though I certainly hope it will). With const generics scheduled to be stable on Rust 1.51.0 (four weeks from now) this seems like a diagnostics improvement which will have a material impact on people's use of Rust.
