### ISSUE TITLE
Remove `everybody_loops`?

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#82618]
Based on a quick ripgrep, `everybody_loops` seems to only be used for the `-Z unpretty=everybody_loops` CLI option. (#73566 removed rustdoc's use of `everybody_loops`.)

Does anyone use `-Z unpretty=everybody_loops`? If not, I think we should remove the pass.

cc #82617
cc @jyn514

**Comment by camelid** [comment]
Not sure if this requires an MCP, but thought I'd start with an issue.

**Comment by camelid** [comment]
It looks like this has been discussed before: https://github.com/rust-lang/rust/pull/73566#r445603609

If we can't remove it because people still use it, maybe it's worth adding documentation to #82617 saying that it's only there for the flag and you shouldn't use it in real code?

**Comment by jyn514** [comment]
Closing this since at least @pnkfelix still uses the option.
