### ISSUE TITLE
Per-commit CI artifacts seemingly missing starting 2021-02-23

### ISSUE THREAD

**Issue by moxian** [rust-lang/rust#82625]
I was looking for a per-commit builds that used to be published to S3 bucket (and that are used by https://github.com/rust-lang/cargo-bisect-rustc among other things), and it appears that those are not published any more? The last one in the [rust-lang-ci2 bucket](https://s3-us-west-1.amazonaws.com/rust-lang-ci2) is from 2021-02-23 - commit 019610754363d1d92a8d0f364d2c0909d6f53dfd . The artifacts for the following commit (fe1bf8e05c3) are seemingly absent.

This is weird, because neither the last present, nor the first absent commits have anything to do with the CI.

I've tried searching through the issues, but the only related one seems to be https://github.com/rust-lang/rust/issues/80753, which hasn't seen any action since 2021-02-16 AFAICT.

(I can see this being a conscious decision to stop producing per-commit builds - that's probably fine as well, but in that case I'd just like to get a confirmation that this was a done deliberately)

**Comment by ehuss** [comment]
The artifacts for fe1bf8e05c39bdcc73fc09e246b7209444e389bc seem to exist for me: https://s3-us-west-1.amazonaws.com/rust-lang-ci2/rustc-builds/fe1bf8e05c39bdcc73fc09e246b7209444e389bc/rustc-nightly-x86_64-unknown-linux-gnu.tar.xz

Perhaps you are looking for alt builds?  Those were recently discontinued, see https://internals.rust-lang.org/t/update-on-rust-ci-removing-rustc-builds-alt/14031

Is there a specific URL that you can give as an example?

**Comment by moxian** [comment]
Oh i see, that's great news!

Yes, I was looking at -alt builds, since those are the only one that show in the listing (https://s3-us-west-1.amazonaws.com/rust-lang-ci2/ - plenty of `rustc-builds-alt/` keys, zero `rustc-builds/`). But now I realize that's simply because the listing is truncated to first 1000 items (and there's no easy way to increase that limit in the web view).

Out of curiosity, how did you get the link for `fe1bf8e`? I now understand how I can craft these myself, but it'd be nice if there was a dashboards or similar.

**Comment by ehuss** [comment]
I think I had the base URL from the cargo-bisect-rustc source, and then I just tacked on the sha from a recent commit.
