### ISSUE TITLE
E0277: wrong span (doesn't have a size known at compile-time)

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#82631]
Given the following code: 

```rust
pub fn main() {
    let _s: String = format!("{}", *"hello");
}
```

The current output is:

```
error[E0277]: the size for values of type `str` cannot be known at compilation time
   --> src/main.rs:2:22
    |
2   |     let _s: String = format!("{}", *"hello");
    |                      ^^^^^^^^^^^^^^^^^^^^^^^ doesn't have a size known at compile-time
    |
    = help: the trait `Sized` is not implemented for `str`
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

I think the span should only cover the `*"hello"`?

Ideally the output should look like:

```
error[E0277]: the size for values of type `str` cannot be known at compilation time
   --> src/main.rs:2:22
    |
2   |     let _s: String = format!("{}", *"hello");
    |                                    ^^^^^^^^ doesn't have a size known at compile-time
    |
    = help: the trait `Sized` is not implemented for `str`
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
```
The `format!()` returns a String and we know the size of that.

**Comment by SNCPlay42** [comment]
The span on the [expanded](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=40bd7d8c85e0de6c887bb86d59a69517) code is:

```
error[E0277]: the size for values of type `str` cannot be known at compilation time
   --> src/main.rs:12:29
    |
12  |                 (arg0,) => [::std::fmt::ArgumentV1::new(arg0, ::core::fmt::Display::fmt)],
    |                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^ doesn't have a size known at compile-time
    |
    = help: the trait `Sized` is not implemented for `str`
```

I think the error message in general could be changed to highlight the argument, not the call. (And I imagine `arg0` might already have its span set to that of the format argument.)

**Comment by SNCPlay42** [comment]
The difficulty with that approach would be that `ArgumentV1::new` is generic and the compiler would have to find a span for what caused it to infer `T=str`.

**Comment by Aaron1011** [comment]
This already works in the case of a single argument:

```rust
fn sized_ref<T>(_: &T) {}

fn main() {
    sized_ref("First");
}
```

produces:

```
error[E0277]: the size for values of type `str` cannot be known at compilation time
 --> src/main.rs:4:15
  |
1 | fn sized_ref<T>(_: &T) {}
  |              - required by this bound in `sized_ref`
...
4 |     sized_ref("First");
  |               ^^^^^^^ doesn't have a size known at compile-time
  |
  = help: the trait `Sized` is not implemented for `str`
help: consider relaxing the implicit `Sized` restriction
  |
1 | fn sized_ref<T: ?Sized>(_: &T) {}
  |               ^^^^^^^^
```

However, when the type parameter is used by multiple arguments, the span switches to point the function call:

```rust
fn sized_ref<T>(_: &T, _: &T) {}

fn main() {
    sized_ref("First", "Second");
}
```

produces:

```
error[E0277]: the size for values of type `str` cannot be known at compilation time
 --> src/main.rs:4:5
  |
1 | fn sized_ref<T>(_: &T, _: &T) {}
  |              - required by this bound in `sized_ref`
...
4 |     sized_ref("First", "Second");
  |     ^^^^^^^^^ doesn't have a size known at compile-time
  |
  = help: the trait `Sized` is not implemented for `str`
help: consider relaxing the implicit `Sized` restriction
  |
1 | fn sized_ref<T: ?Sized>(_: &T, _: &T) {}
  |               ^^^^^^^^
```

**Comment by jessa0** [comment]
Looks like this is intentional, but for reasons I couldn't find documented:

https://github.com/rust-lang/rust/blob/23fa5360502be2554382c9d860e6438d3b822858/compiler/rustc_typeck/src/check/fn_ctxt/checks.rs#L962-L967

I'm guessing this is because we have to choose exactly one span to point to for the error? It's unclear to me, when more than one parameter references the type variable, which one to point to; though, by my experimentation, it seems that the first parameter referencing a type variable always determines the type, but I could be wrong..

**Comment by jessa0** [comment]
Following the git blame, looks like @estebank added support for pointing to a single argument causing an item obligation failure in 02e3fb8, so this issue would be expanding that to figure out which out of multiple parameters referencing a type variable caused the obligation failure.

Another note: it doesn't look possible to change the span of the `::std::fmt::ArgumentV1::new` to the format argument, since doing so cause the format parameter to fail the stability checker for referencing format internals.

**Comment by estebank** [comment]
The code pointing at the arg is a _hack_. We don't keep good enough tracking of obligations as they propagate to be able to point at specific type parameters or arguments. I would love to see that change. If we fixed the general case, this ticket would also get resolved.

**Comment by estebank** [comment]
Current output:

```
error[E0277]: the size for values of type `str` cannot be known at compilation time
  --> src/main.rs:2:36
   |
2  |     let _s: String = format!("{}", *"hello");
   |                               --   ^^^^^^^^ doesn't have a size known at compile-time
   |                               |
   |                               required by a bound introduced by this call
   |
   = help: the trait `Sized` is not implemented for `str`
note: required by a bound in `core::fmt::rt::Argument::<'a>::new_display`
  --> /playground/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/fmt/rt.rs:96:28
   |
96 |     pub fn new_display<'b, T: Display>(x: &'b T) -> Argument<'_> {
   |                            ^ required by this bound in `Argument::<'a>::new_display`
   = note: this error originates in the macro `$crate::__export::format_args` which comes from the expansion of the macro `format` (in Nightly builds, run with -Z macro-backtrace for more info)
```
