### ISSUE TITLE
`pub` on `macro_rules!` not supported in rustfmt

### ISSUE THREAD

**Issue by JulianKnodt** [rust-lang/rust#82640]
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=71be237d1aed61df9bbdb665bbd5a056`

I expected to be able to format it with rustfmt,

but when running rustfmt there is an error despite compilation succeeding.

The implementation PR is #82296, but unsure if there's a RFC for the original idea.

**Comment by jyn514** [comment]
@JulianKnodt this should be reported to https://github.com/rust-lang/rustfmt.

**Comment by jyn514** [comment]
Also, this is probably just waiting on a submodule update.

**Comment by JulianKnodt** [comment]
my b, didn't realize that rustfmt wasn't in the compiler repo
