### ISSUE TITLE
Compile error with const generics

### ISSUE THREAD

**Issue by usbalbin** [rust-lang/rust#82647]
Sorry in advance, might just be me missing something but it feels like this should not happen. I tried the following code in both [tests/test.rs](https://github.com/usbalbin/iter_fixed/blob/wonkyness/tests/test.rs#L37) and [src/lib.rs](https://github.com/usbalbin/iter_fixed/blob/wonkyness/src/lib.rs#L12) and get different results: 

```rust
let res: [_; 2] = [1u32, 2, 3, 4]
    .into_iter_fixed()
    .zip([4u32, 3, 2, 1])
    .map(|(a, b)| a + b)
    .skip::<1>()
    .take::<2>()
    .collect();
```

I expected everything to compile fine.

Instead, `cargo build` succeeds however running `cargo test` fails compile [tests/test.rs](https://github.com/usbalbin/iter_fixed/blob/wonkyness/tests/test.rs#L37) 

The errors started after I updated my compiler. I unfortunately do not remember the old version. However after I updated I know I started getting warnings about `array::IntoIter` now being stabilized as well as warning about [private_in_public](https://github.com/rust-lang/rust/issues/34537):

<details><summary>private_in_public warning </summary>
<p>

```
warning: private type `fn(usize, usize) -> usize {min}` in public interface (error E0446)
  --> src/lib.rs:63:5
   |
63 |     pub fn take<const TAKE: usize>(self) -> IteratorFixed<iter::Take<I>, { min(TAKE, N) }> {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(private_in_public)]` on by default
   = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
   = note: for more information, see issue #34537 <https://github.com/rust-lang/rust/issues/34537>
```

</p>
</details>

The warning about `private_in_public` disappeared after making the const functions used for computing the const generics public.

### Meta

`rustc --version --verbose`:
```
rustc 1.52.0-nightly (94736c434 2021-02-27)
binary: rustc
commit-hash: 94736c434ee154b30e2ec22ec112b79e3f6c5884
commit-date: 2021-02-27
host: x86_64-unknown-linux-gnu
release: 1.52.0-nightly
LLVM version: 11.0.1
```

<details><summary>Compile error</summary>
<p>

```
error[E0277]: the trait bound `[_; 2]: FromIteratorFixed<std::iter::Take<Skip<Map<Zip<std::array::IntoIter<u32, 4_usize>, std::array::IntoIter<u32, 4_usize>>, [closure@tests/test.rs:40:14: 40:28]>>>, {_: usize}>` is not satisfied
  --> tests/test.rs:43:10
   |
43 |         .collect();
   |          ^^^^^^^ the trait `FromIteratorFixed<std::iter::Take<Skip<Map<Zip<std::array::IntoIter<u32, 4_usize>, std::array::IntoIter<u32, 4_usize>>, [closure@tests/test.rs:40:14: 40:28]>>>, {_: usize}>` is not implemented for `[_; 2]`
   |
   = help: the following implementations were found:
             <[<I as Iterator>::Item; N] as FromIteratorFixed<I, N>>

error: aborting due to previous error
```

</p>
</details>

**Comment by ehuss** [comment]
It looks like `test.rs` is missing `#![feature(const_generics)]`

**Comment by usbalbin** [comment]
Oh sorry 🤦.

Thank you so much :)
