### ISSUE TITLE
Mostly, code for installation to other place is NOT FINISHED.

### ISSUE THREAD

**Issue by quarkjuggler** [rust-lang/rust#82649]
I've been trying for 3 or 4 days to install.  My name is /home/pi, but I wanted to install to /home/production so that everyone could use it.  Here are problems that I encountered:
1. I put '/' at the end of directory names in RUSTUP_HOME and CARGO_HOME.  This was reasonable.  You folks didn't check for it.
2. The install died because etc library wasn't found.  You folks should create it if not found.
3. After failing, I tried to "rustup self uninstall", and it said the package wasn't installed to ~/.cargo.  Of course not!
4. You should not assume that if someone is uninstalling, that all directories and files are right where you put them.
5. If allowing library to be installed elsewhere, the updates to .bashrc and .profile should be allowed to be global.
6.  The compiler kept giving "illegal instruction".  --Probably because of installing to unfamiliar territory.

**Comment by jonas-schievink** [comment]
Please file rustup issues at https://github.com/rust-lang/rustup and ask questions about the installation process at https://users.rust-lang.org/
