### ISSUE TITLE
regression: inline, used attr no longer accepted in more places

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#82668]
inline:
* https://crater-reports.s3.amazonaws.com/beta-1.51-1/beta-2021-02-14/reg/debug_iterator-0.1.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.51-1/beta-2021-02-14/gh/museun.debug_iterator/log.txt

used:
* https://crater-reports.s3.amazonaws.com/beta-1.51-1/beta-2021-02-14/gh/nickyc975.RustWebServer/log.txt

Filing primarily so that we can get this documented in release notes as a compatibility note (if it isn't already); cc @XAMPPRocky

**Comment by lcnr** [comment]
That's surprising, iirc the crater runs we did during the PRs didn't notice any regressions :thinking:

**Comment by lcnr** [comment]
inline PR is #77015

**Comment by apiraino** [comment]
(removing `I-prioritize` autolabel added from bot)

**Comment by Mark-Simulacrum** [comment]
Closing - this was expected/accepted breakage.
