### ISSUE TITLE
regression: unsigned_abs inherent method conflict

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#82666]
One crate regressed as a result of the stabilization of https://github.com/rust-lang/rust/pull/80959.

* https://crater-reports.s3.amazonaws.com/beta-1.51-1/beta-2021-02-14/reg/geod-0.1.0/log.txt

**Comment by apiraino** [comment]
The published crate for `geod` contains code that has been updated in the meanwhile. As of today I can successfully compile the `master` branch of that crate on stable, beta and latest nightly.

[Prioritization Working Group thread on zulip](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2382666.20regression.3A.20unsigned_abs.20inherent.20method.20conflict) and removing `I-prioritize`.

@rustbot label -I-prioritize -I-nominated

**Comment by apiraino** [comment]
I think we can close this issue (but feel free to reopen in case I've missed something)

**Comment by Mark-Simulacrum** [comment]
I'll just ping @tsionyx to suggest they make a point release, but otherwise I agree we can likely close.

**Comment by tsionyx** [comment]
@Mark-Simulacrum Thank you for pointing it out, but worry not, this crate is just my pet project. I had already noticed the described name conflict before and [renamed](https://github.com/tsionyx/geod/commit/2f7ead093b1eba883c8fefa972a8c0a857e19bcd#diff-23af5356f6001cd3993cd3c801fb7716ea02d1e504081b9fb569332db6107e80L25) `unsigned_abs` to `abs_and_sign`.

**Comment by tsionyx** [comment]
Also, I published fixed version 0.1.1 on [crates.io](https://crates.io/crates/geod/versions) and yanked the broken one 0.1.0.
