### ISSUE TITLE
regression: reduce on iterator conflicts

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#82664]
https://github.com/rust-lang/rust/pull/79805 stabilized Iterator::reduce, which conflicts with a similar method in the [reduce crate](https://docs.rs/reduce/0.1.4/reduce/trait.Reduce.html).

This caused a number of regressions, as detected by the beta crater run:
* https://crater-reports.s3.amazonaws.com/beta-1.51-1/beta-2021-02-14/gh/7e11.FullTextSearch/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.51-1/beta-2021-02-14/gh/ChrisMacNaughton.euler-rs/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.51-1/beta-2021-02-14/gh/Tismas.aoc2020/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.51-1/beta-2021-02-14/gh/akuraj.gomoku/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.51-1/beta-2021-02-14/gh/davidszotten.advent-of-code-2020/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.51-1/beta-2021-02-14/gh/guilgaly.advent-of-code-2020/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.51-1/beta-2021-02-14/gh/guillermomuntaner.AdventOfCode2020-Rust/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.51-1/beta-2021-02-14/gh/ptrkalm.AoC2020/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.51-1/beta-2021-02-14/gh/reline.AdventOfCode2020/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.51-1/beta-2021-02-14/gh/rklaehn.tag-index/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.51-1/beta-2021-02-14/gh/tqdv.switchable/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.51-1/beta-2021-02-14/reg/csvsc-1.4.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.51-1/beta-2021-02-14/reg/fp_rust-0.1.39/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.51-1/beta-2021-02-14/reg/reduce-0.1.4/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.51-1/beta-2021-02-14/reg/switchable-0.1.0/log.txt

I suspect that we'll be inclined to accept this breakage, but wanted to file an issue to get a :+1: from T-libs, hopefully; we should also likely ping the authors of these crates. Many of them appear to be Advent of Code repositories where breakage is actually somewhat unlikely to even get noticed.

**Comment by apiraino** [comment]
@Mark-Simulacrum  excluding the advent of code crates (I wonder if they should stay in the crater run), I've tried compiling the other failing ones from their respective master branch:

- [gomoku](https://github.com/akuraj/gomoku) compiles on stable with just a lint warning, fails on beta+nightly  => will regress
- [tag-index](https://github.com/rklaehn/tag-index): same as above
- [switchable](https://github.com/tqdv/switchable): same as above
- [reduce](https://github.com/dtolnay/reduce): compiles on nightly,beta, stable => no regression
- [csvsc](https://gitlab.com/categulario/csvsc): same as above

hope this helps!

**Comment by Mark-Simulacrum** [comment]
The master branch not compiling or continuing to compile matters more for git repositories, but for published crates it's encouraging sign if things have been fixed; we ultimately need a point release if we want to streamline upgrade paths.

**Comment by m-ou-se** [comment]
> to get a :+1: from T-libs

We briefly discussed this in the libs meeting just now. Here it is: :+1:

**Comment by Mark-Simulacrum** [comment]
Ok, closing in that case.
