### ISSUE TITLE
regression?: llvm version error

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#82671]
* https://crater-reports.s3.amazonaws.com/beta-1.51-1/beta-2021-02-14/gh/moparisthebest.sendxmpp-rs/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.51-1/beta-2021-02-14/reg/sendxmpp-2.0.0/log.txt

potentially related, but if not good to file another issue:
* https://crater-reports.s3.amazonaws.com/beta-1.51-1/beta-2021-02-14/gh/Hoverbear.rust-rosetta/log.txt

**Comment by jyn514** [comment]
This looks like https://docs.rs/rustc_version/0.3.3/rustc_version/enum.Error.html#variant.LlvmVersionError (note that the crate has a dependency on `rustc_version 0.3.2`). It was fixed in 0.3.2, so I think this can be closed: https://github.com/Kimundi/rustc-version-rs/compare/v0.3.2...v0.3.3.

**Comment by jyn514** [comment]
> potentially related

```
[INFO] [stderr] thread 'rustc' panicked at 'called `Result::unwrap()` on an `Err` value: FromUtf8Error { bytes: [128, 0, 2, 8, 0, 12, 5, 4], error: Utf8Error { valid_up_to: 0, error_len: Some(1) } }', compiler/rustc_codegen_llvm/src/metadata.rs:75:22
```

This looks like a different issue.

**Comment by apiraino** [comment]
removing the prioritize label @rustbot label -I-prioritize

**Comment by apiraino** [comment]
Seems that the master branch of this crate compiles on stable, beta and nightly, I guess the crate used in the crater run is not updated to the latest version (or there's no more recent release of xmpp-rs.

Therefore I would close this issue, what do you think @Mark-Simulacrum ?

Perhaps worth mentioning that `xmpp-rs` fails to compile on nightly+beta (on stable is fine) for another reason, a linting warning on another dependency ([xml4ever](https://github.com/servo/html5ever/tree/HEAD/xml5ever)):

<details><summary>Compiling xml5ever v0.16.1</summary>

```
   Compiling xml5ever v0.16.1
error: field is never read: `ns`
   --> tokio-xmpp/src/xmpp_codec.rs:183:5
    |
183 |     ns: Option<String>,
    |     ^^^^^^^^^^^^^^^^^^
    |
note: the lint level is defined here
   --> tokio-xmpp/src/lib.rs:3:22
    |
3   | #![deny(unsafe_code, unused, missing_docs, bare_trait_objects)]
    |                      ^^^^^^
    = note: `#[deny(dead_code)]` implied by `#[deny(unused)]`

error: aborting due to previous error

error: could not compile `tokio-xmpp`
```
</details>

worth opening an issue?

**Comment by jyn514** [comment]
> Perhaps worth mentioning that xmpp-rs fails to compile on nightly+beta (on stable is fine) for another reason, a linting warning on another dependency (xml4ever):

Is `crater` running without `--cap-lints warn`? That seems bad. Anyway, I don't think making lints more accurate should *ever* be considered a breaking change, the author opted-in to the breakage with `deny(unused)`.

**Comment by Mark-Simulacrum** [comment]
crater usually caps lints at forbid, as we want to know if we've added regressions in lints too. This seems reasonable to me. (I might even want --force-lints = deny or something).

But yes it sounds like this is not a rust regression at least.
