### ISSUE TITLE
--enable-valgrind succeeds if valgrind is not installed. mac bots are not valgrinding

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#8267]
The configure script does not error if `--enable-valgrind` is specified but valgrind does not exist. This is resulting in situations where our mac valgrind bots are not actually valgrinding:

http://buildbot.rust-lang.org/builders/auto-mac-64-opt-vg/builds/712/steps/configure/logs/stdio

I *have* seen valgrind errors on the mac valgrind builder though, so presumably some of the slaves do have valgrind.

**Comment by alexcrichton** [comment]
This has been fixed as the tests will error if they don't find valgrind by default. This is enabled for the valgrind tests.
