### ISSUE TITLE
regression: read_to_string import error

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#82670]
* https://crater-reports.s3.amazonaws.com/beta-1.51-1/beta-2021-02-14/gh/PragmaTwice.ichigo-lang/log.txt

I suspect this is a change in behavior for the resolver, cc @petrochenkov  -- probably fixing a bug in practice, but in case it was unintentional seems good to flag.

**Comment by petrochenkov** [comment]
This is not a resolver change, but a library addition of `std::io::read_to_string` (https://github.com/rust-lang/rust/pull/80217).

Resolver tries pretty hard to resolve ambiguities like this arising from library additions (e.g. single import wins over glob import, two glob imports do not conflict unless the ambiguous name is actually used), but in case of two glob imports and an actually used ambiguous name we truly cannot do anything.

Addition of any new item to any library has a potential to cause breakage like this, so it is considered an acceptable breakage.

**Comment by Mark-Simulacrum** [comment]
Sounds good. I missed that merged in 1.51, re-tagging libs.

**Comment by JohnTitor** [comment]
Triage: Closing this as an acceptable breakage.
