### ISSUE TITLE
read_volatile/write_volatile uses ldrb/strb only for structs on aarch64

### ISSUE THREAD

**Issue by Trolldemorted** [rust-lang/rust#82701]
I am writing low-level code targeting ARMv8 (aarch64), and I have noticed that [read_volatile](https://doc.rust-lang.org/std/ptr/fn.read_volatile.html) and [write_volatile](https://doc.rust-lang.org/std/ptr/fn.write_volatile.html) are emitting unexpected bytecode.

When I use `read_volatile` on a `*const u32`, rustc generates the expected `ldr`:
```rust
#[no_mangle]
#[inline(never)]
pub fn volatile_read_u32(address: u64) -> u32 {
    let ptr = address as *const u32;
    unsafe {
        ptr
            .offset(0x42)
            .read_volatile()
    }
}
```
```asm
00000000400855ec <volatile_read_u32>:
    400855ec:	b9410800 	ldr	w0, [x0, #264]
    400855f0:	d65f03c0 	ret
```

However, if I do that on a struct (even packed ones with only one u32 member), rustc generates separate `ldrb` instructions whose results are shifted to yield the original result:
```rust
#[repr(packed)]
struct Foo {
    a: u32,
}

#[no_mangle]
#[inline(never)]
pub fn volatile_read(address: u64) -> u32 {
    let ptr = address as *const Foo;
    unsafe {
        ptr
            .offset(0x43)
            .read_volatile()
    }.a
}
```
```asm
00000000400855f4 <volatile_read>:
    400855f4:	39443c08 	ldrb	w8, [x0, #271]
    400855f8:	39443809 	ldrb	w9, [x0, #270]
    400855fc:	3944340a 	ldrb	w10, [x0, #269]
    40085600:	39443000 	ldrb	w0, [x0, #268]
    40085604:	33181d09 	bfi	w9, w8, #8, #8
    40085608:	33181d40 	bfi	w0, w10, #8, #8
    4008560c:	33103d20 	bfi	w0, w9, #16, #16
    40085610:	d65f03c0 	ret
```

The same thing happens with `write_volatile`:
```rust
#[no_mangle]
#[inline(never)]
pub fn volatile_write(address: u64) {
    let ptr = address as *mut Foo;
    unsafe {
        ptr
            .offset(0x44)
            .write_volatile(Foo {
                a: 1,
            })
    };
}
```
```asm
0000000040085614 <volatile_write>:
    40085614:	d10043ff 	sub	sp, sp, #0x10
    40085618:	52800028 	mov	w8, #0x1                   	// #1
    4008561c:	b9000fe8 	str	w8, [sp, #12]
    40085620:	b9400fe8 	ldr	w8, [sp, #12]
    40085624:	39044008 	strb	w8, [x0, #272]
    40085628:	53187d09 	lsr	w9, w8, #24
    4008562c:	53107d0a 	lsr	w10, w8, #16
    40085630:	53087d08 	lsr	w8, w8, #8
    40085634:	39044c09 	strb	w9, [x0, #275]
    40085638:	3904480a 	strb	w10, [x0, #274]
    4008563c:	39044408 	strb	w8, [x0, #273]
    40085640:	910043ff 	add	sp, sp, #0x10
    40085644:	d65f03c0 	ret
```

The generated bytecode has several problems:
- MMIO devices do not appreciate if their registers are read from or written to byte-wise
- Verification of the binary is impaired because of unnecessary instructions and expressions on symbols
- This can't be good for performance, can it?

For me it was very unexpected that a read from an u32 causes different instructions than a read from a packed struct with only one (u32) member.

### Meta

`rustc --version --verbose`:
```
rustc 1.49.0-nightly (ffa2e7ae8 2020-10-24)
binary: rustc
commit-hash: ffa2e7ae8fbf9badc035740db949b9dae271c29f
commit-date: 2020-10-24
host: x86_64-unknown-linux-gnu
release: 1.49.0-nightly
LLVM version: 11.0
```
.cargo/config:
```
[build]
target = "aarch64-unknown-none-softfloat.json"
```
aarch64-unknown-none-softfloat.json:
```
{
  "pre-link-args": {
    "ld.lld": ["-Taarch64-qemu.ld"]
  },
  "arch": "aarch64",
  "data-layout": "e-m:e-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128",
  "disable-redzone": true,
  "env": "",
  "executables": true,
  "features": "+strict-align,-neon,-fp-armv8",
  "is-builtin": true,
  "linker": "rust-lld",
  "linker-flavor": "ld.lld",
  "linker-is-gnu": true,
  "llvm-target": "aarch64-unknown-none",
  "max-atomic-width": 128,
  "os": "none",
  "panic-strategy": "abort",
  "relocation-model": "static",
  "target-c-int-width": "32",
  "target-endian": "little",
  "target-pointer-width": "64",
  "unsupported-abis": [
    "stdcall",
    "fastcall",
    "vectorcall",
    "thiscall",
    "win64",
    "sysv64"
  ],
  "vendor": ""
}
```
All instructions above were disassembled by objdump, and the binary was built with `cargo xbuild --release`.

**Comment by jonas-schievink** [comment]
`#[repr(packed)]` intentionally works like that, it removes all alignment requirements on the struct, so all reads have to assume that the pointer is unaligned. What's the output if you remove that?

**Comment by Trolldemorted** [comment]
>What's the output if you remove that?

Then the output is as expected:
```asm
00000000400855ec <volatile_read_u32>:
    400855ec:	b9410800 	ldr	w0, [x0, #264]
    400855f0:	d65f03c0 	ret

Disassembly of section .text.volatile_read:

00000000400855f4 <volatile_read>:
    400855f4:	b9410c00 	ldr	w0, [x0, #268]
    400855f8:	d65f03c0 	ret

Disassembly of section .text.volatile_write:

00000000400855fc <volatile_write>:
    400855fc:	52800028 	mov	w8, #0x1                   	// #1
    40085600:	b9011008 	str	w8, [x0, #272]
    40085604:	d65f03c0 	ret
```

>#[repr(packed)] intentionally works like that, it removes all alignment requirements on the struct, so all reads have to assume that the pointer is unaligned

Thanks for shedding some light on this! Is that behavior desirable?

I thought the primary purpose of `repr(packed)` was to allow iterop with packed C structs (e.g. by gcc's `__attribute__((__packed__))`) or devices whose registers are defined by packed C structs. gcc's [documentation says](https://gcc.gnu.org/onlinedocs/gcc-4.0.2/gcc/Type-Attributes.html) their `packed` attribute means only "a member field has the smallest possible alignment", and to be honest I was genuinely surprised that rust removes the alignment requirements on the struct, instead of on the members.

Does this mean I must not pass a pointer to a Rust `packed` struct to a C function, because the C function assumes that the pointer is aligned, but rustc does not guarantee that the type is aligned?

Does Rust have something that matches the definition from the C compilers?

**Comment by jonas-schievink** [comment]
Hmm, those are good questions that I can't really answer. Maybe ask on https://users.rust-lang.org/ or on Zulip? People there probably know.

Since `#[repr(packed)]` is working as [intended](https://doc.rust-lang.org/reference/type-layout.html#the-alignment-modifiers) though, I'll close this issue.
