### ISSUE TITLE
FloatToInit docs incorrect symbol: round_unchecked_to - should be to_int_unchecked

### ISSUE THREAD

**Issue by peter-kehl** [rust-lang/rust#82709]
https://doc.rust-lang.org/nightly/std/convert/trait.FloatToInt.html mentions a non-existing symbol: `round_unchecked_to`. The correct one is: `to_int_unchecked`. (There is no word `round` anywhere in `library/core/src/convert/num.rs`.)

Notes
- Even though this is a Docs defect, I'm not mentioning steveklabnik, since I don't believe this needs his attention.
- based on my grep search, the current master doesn't refer to the incorrect reference anywhere else.
- I'll provide a PR.

**Comment by JohnTitor** [comment]
Fixed by #82710.
