### ISSUE TITLE
Error in rust syntax

### ISSUE THREAD

**Issue by Jzow** [rust-lang/rust#82716]
I'm a rookie of rust. I used to do java ，Error in the syntax of trust, I wrote it according to the example of the official website，mutable = true;
```
let mut mutable = 12;
mutable = 21;
// This line of syntax compilation error
mutable = true;
```

I tried this code:

```
use std::io;

fn main() {
    let logical : bool = true;
    let a_flat : f64 = 23.0;
    let a_integer = 5i32;
    let default_integer = 7;
    let mut inferrd_type =  4299988123213;
    let mut mutable = 12;
    mutable = 21;

    mutable = true;

    let mutable = true;
}
```

### Reference URL
[https://doc.rust-lang.org/stable/rust-by-example/primitives.html](https://doc.rust-lang.org/stable/rust-by-example/primitives.html)

### Meta

windows X64 
```
rustc 1.50.0 (cb75ad5db 2021-02-10)
```

</p>
</details>

**Comment by jonas-schievink** [comment]
Hi! This issue tracker is mainly meant for bug reports and concrete, small feature requests. Questions like this are better asked in the user forum at https://users.rust-lang.org/ or on [one of the chat platforms](https://www.rust-lang.org/community) used by the Rust community.
