### ISSUE TITLE
Raw strings don't preserve carriage return + newline sequences

### ISSUE THREAD

**Issue by Count-Count** [rust-lang/rust#82721]
According to the _Raw string literals_ section in the [reference](https://doc.rust-lang.org/reference/tokens.html#literals) the "raw string body can contain any sequence of Unicode characters" and "[a]ll Unicode characters contained in the raw string body represent themselves". However in such a raw string carriage return + newline sequences (`U+000D` `U+000A`) are replaced by a single newline char  (`U+000A`).

This is probably a sensible choice but if so should be documented thus.

[Testcase](https://github.com/rust-lang/rust/files/6075822/crtest.tar.gz)

**Comment by ehuss** [comment]
Thanks for the report!   Issues for the reference go in the https://github.com/rust-lang/reference repository, and this is a known issue where the reference needs to be updated, see https://github.com/rust-lang/reference/issues/626.

**Comment by Count-Count** [comment]
@ehuss Thanks for the comment! I am closing this as duplicate.
