### ISSUE TITLE
Tracking Issue for `invalid_doc_attributes` lint

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#82730]
### What is this lint about

The `invalid_doc_attributes` lint detects incorrect uses of `#[doc(...)]` attributes or uses of non-existent `#[doc(...)]` attributes. For example, `#[doc(alias = 42)]` will trigger this lint, since `42` is not a string. Also, `#[doc(foobar)]` will trigger this lint.

If you are here because of a warning about `doc(primitive)`, see https://github.com/rust-lang/rust/issues/88070 instead.

---

#### Original issue

From https://github.com/rust-lang/rust/pull/82702: Currently the warning reuses the existing `unknown_attributes` lint, but to properly do future incompatibility we need to use the special infrastructure that exists for it.

We should also consider sticking this into the edition (see https://github.com/rust-lang/rust/issues/80165), though I'm not sure if it can be automatically upgraded. This might be one of the cases where it doesn't matter.

**Comment by GuillaumeGomez** [comment]
I think the most important thing is to at least prevent non-functioning code to go unnoticed. So at least having warnings seems good enough. Then we can always discuss if we want to make it into a hard error or not when a new edition comes up.

**Comment by Manishearth** [comment]
Yep! I think using the future incompat architecture for this is great, because we can declare as early as possible that we're hoping to make this a hard error.

And then as things settle, someone can eventually have the proper discussion about how best to actually remove it.

**Comment by camelid** [comment]
It looks like this was implemented in #82708? Should we repurpose this as a tracking issue since it is linked to from the lint?

**Comment by Manishearth** [comment]
I believe that creates the lint but does not make it lint on all cases. That was written in the interest of fixing a nightly regression, so doesn't address the issue in this thread.

**Comment by camelid** [comment]
> I believe that creates the lint but does not make it lint on all cases.

That lint is used for the ``unknown `doc` attribute`` warning: https://github.com/rust-lang/rust/blob/e7e1dc158c3de232750b568163f6941a184ee8be/compiler/rustc_passes/src/check_attr.rs#L588-L599

**Comment by jonas-schievink** [comment]
This issue is still linked today from the compiler warning you get for invalid doc attributes like `#[doc(bla)]`. Since this is a future-incompat lint, where is turning this into a hard error actually tracked?

**Comment by camelid** [comment]
Hmm... I'm guessing nowhere? Good catch, I'll reopen (and rename) this issue for now.
