### ISSUE TITLE
Create safe LLVM bindings

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#8274]
rustc's LLVM bindings are a bit of a hodgepodge. Some abstractions have been added on top of the C bindings, but not consistently. It would be nice to do some serious cleanup here so that rustc is using only safe, high-level bindings.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#644
