### ISSUE TITLE
rustdoc: Get rid of `CURRENT_DEPTH` thread-local variable

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#82742]
It turns out `CURRENT_DEPTH` has been around as a thread-local [since the beginning of the rustdoc HTML backend](https://github.com/rust-lang/rust/blob/4fd061c426902b0904c65e64a3780b21f9ab3afb/src/rustdoc_ng/html/render.rs#L82), so it's *very* hard to get rid of it. The issue is that it turns out so many places in rustdoc implicitly depend on it, so threading (haha, get it?) it through all the functions is very tedious.

cc https://rust-lang.zulipchat.com/#narrow/stream/266220-rustdoc/topic/what.20is.20CURRENT_DEPTH

**Comment by jyn514** [comment]
This is tedious, but I don't expect it to be particularly hard.

@rustbot label: -E-hard +E-medium
