### ISSUE TITLE
On RISC-V, `tp` register cannot be used in Rust's inline assembly

### ISSUE THREAD

**Issue by luojia65** [rust-lang/rust#82753]
I am developing my own operating system kernel on RISC-V. In RISC-V, `tp` and `gp` registers are not often used by user level application, but is significant in developing kernels. 

I tried this code:

```rust
asm!("", lateout("tp") tp);
```

I expected to see the `tp` register is read, but instead, this error happened:

```
error: invalid register `tp`: the thread pointer cannot be used as an operand for inline asm
  --> tornado-kernel\src\hart.rs:32:26
   |
32 |                 asm!("", lateout("tp") tp);
   | 
```

The `tp` and `gp` register is significantly useful when we develop kernels that interacts to user applications with shared memory blocks. Register values in `tp` and `gp` can act as a hint to what address space and resources the current task uses.

Maybe we should allow to use these two registers by writing and reading `tp`, `gp` register in new inline assembly, so that we can use them in operating system development. This can benefit operating system kernel design, and user level applications can use them to design runtimes and shared buffers.

### Meta

`rustc --version --verbose`:
```
rustc 1.52.0-nightly (4f20caa62 2021-03-01)
binary: rustc
commit-hash: 4f20caa6258d4c74ce6b316fd347e3efe81cf557
commit-date: 2021-03-01
host: x86_64-pc-windows-msvc
release: 1.52.0-nightly
LLVM version: 11.0.1
```

**Comment by Amanieu** [comment]
You need to use a `mv` instruction to read the register. Here is the code that I am using:
```rust
asm!("mv {}, tp", out(reg) tp, options(nomem, nostack));
```

**Comment by Amanieu** [comment]
Similarly here is the code to write to the register:
```rust
asm!("mv tp, {}", in(reg) tp, options(nostack));
```

Note that the restriction is that you cannot use `tp` and `gp` as inputs or outputs. But you can still use them within the assembly code itself.

**Comment by luojia65** [comment]
Thank you for clarify! That's the perfect solution to my problem. :)
