### ISSUE TITLE
Move LLVM bindings to their own crate

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#8275]
Right now our LLVM bindings are tightly integrated into trans. Would be good for abstraction sake to fence LLVM off into its own crate. It would also make LLVM more available to other Rust projects - Rust is a good language for writing compilers.

cc #8274

**Comment by steveklabnik** [comment]
I think this is about as addressed as it's going to get. We have the `rustc_llvm` crate for internal use, and people can use Cargo if they want to make better / nonrustc specific bindings.

@brson, if you disagree, feel free to re-open :)
