### ISSUE TITLE
print! will panic when  No space left on device

### ISSUE THREAD

**Issue by silence-coding** [rust-lang/rust#82791]
The full log disk space is a possible problem during the running of the entire system. However, redirecting the output stream of the print to the log directory causes panic. In order to better locate the problem in the production environment, it is necessary to store the redirected content.

**Comment by silence-coding** [comment]
Redirection is used to print the panic stack (we do not want to introduce the third-party backtrace) and print possible output information in the third-party software.

**Comment by jyn514** [comment]
If you want to handle the error, you can use `write!` instead: https://doc.rust-lang.org/std/io/struct.Stdout.html#examples. `println!` is not meant to be used when you need error-handling.

**Comment by scottmcm** [comment]
It's documented behaviour that `print!` panics if writing to stdout fails: https://doc.rust-lang.org/std/macro.print.html#panics

As such, this would be a substantial change that needs an RFC, not just a bug: https://github.com/rust-lang/rfcs/blob/master/libs_changes.md
