### ISSUE TITLE
Tracking Issue for const `Result` methods

### ISSUE THREAD

**Issue by jhpratt** [rust-lang/rust#82814]
Feature gate: `#![feature(const_result)]`

This is a tracking issue for making a number of `Result` methods `const fn`.

### Public API

NB: Many of these methods will need `~const Drop`. They're omitted here for brevity.

```rust
impl<T, E> Result<T, E> {
    pub const fn as_mut(&mut self) -> Result<&mut T, &mut E>;
}

impl<T, E> Result<Option<T>, E> {
    pub const fn transpose(self) -> Option<Result<T, E>>;
}

impl<T, E> Result<&T, E> {
    pub const fn copied(self) -> Result<T, E>
    where
        T: Copy;
}

impl<T, E> Result<&mut T, E> {
    pub const fn copied(self) -> Result<T, E>
    where
        T: Copy;
}
```

Note some things are missing compared with `Option` (https://github.com/rust-lang/rust/issues/67441):
- `unwrap`, `expect`: drops the error, so cannot be done in const.
- `flatten`: is not stable yet on `Result`, even outside const.
- `take`, `replace`: does not exist on `Result`.

See also #57563.

Please post a comment in this issue if you're submitting a PR that changes any of the above!

**Comment by netsutetsu** [comment]
Why aren't there `unwrap_unchecked` and `unwrap_err_unchecked` while `Option::unwrap_unchecked()` is going to be `const` in #91930?

**Comment by jhpratt** [comment]
The methods probably didn't exist when this issue was created. I'll add them when I'm on my laptop.

**Comment by netsutetsu** [comment]
Could you also add `contains` and `contains_err`, introduced in #62358, as `Option::contains()` will be `const` in that issue?

**Comment by netsutetsu** [comment]
Could you also add `contains`, `contains_err` (introduced in #62358), and `copied` since `Option::contains()` and `Option::copied()` will be `const` in #91930 and #67441?

**Comment by jhpratt** [comment]
Going through the full list now. I'm only going to be adding methods that are already stable, as the unstable methods are tracked in their associated issues.

**Comment by pitaj** [comment]
@jhpratt PR #104407 for Result::{map, map_or, map_or_else, map_err, as_deref, as_deref_mut, unwrap_or_default, and_then, or_else, unwrap_or_else, unwrap_unchecked, unwrap_err_unchecked, copied, cloned}

**Comment by jhpratt** [comment]
@pitaj Thanks. I was already subscribed to the issue, but there's nothing actionable in this tracking issue at the moment.

**Comment by Pzixel** [comment]
What happened to `const_result`? About a week ago everything was fine and now feature gate is gone and with it some of my code started to fail. I understand it's nightly and things change but I don't see any motivation/discussion why this happened. Does anyone have any insights?

**Comment by c410-f3r** [comment]
https://github.com/rust-lang/rust/pull/110393

Looks like any stuff related to constant bounds will take a considerable amount of time to be resolved.

**Comment by RalfJung** [comment]
Yeah, most of the things that were in this feature gate unfortunately depend on "const traits" and that's still very experimental.

The remaining methods listed here, however, can probably be stabilized fairly soon. :)

**Comment by RalfJung** [comment]
@rust-lang/libs-api matching `Option`, some long-stable `Result` methods can be const-stabilized now as well. :)
However, sadly it's much fewer than with `Option`, because methods like `unwrap` would drop the error and we can't drop things in `const fn`.

**Comment by dtolnay** [comment]
@rfcbot fcp merge
