### ISSUE TITLE
Catch_unwind example in docs is not working

### ISSUE THREAD

**Issue by aetelani** [rust-lang/rust#82818]
```rust
#![allow(unused)]
fn main() {
use std::panic;

let result = panic::catch_unwind(|| {
    println!("hello!");
});
assert!(result.is_ok());

let result = panic::catch_unwind(|| {
    panic!("oh no!");
});
assert!(result.is_err());
}
```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=27589bcdcdbef351a2fd80475bf4320a))

**Comment by aetelani** [comment]
Doc link https://doc.rust-lang.org/std/panic/fn.catch_unwind.html

I believe it needs the hook as well
https://stackoverflow.com/questions/35559267/suppress-panic-output-in-rust-when-using-paniccatch-unwind

**Comment by sfackler** [comment]
In what way is it not working?

**Comment by aetelani** [comment]
> In what way is it not working?

It's panicin instead of result/assert. Stackoverflow says it would need the hook as well.

**Comment by sfackler** [comment]
The purpose of catch_unwind is not to suppress a panic message, it is to stop the panic during unwinding.

**Comment by aetelani** [comment]
Actually it works. Just prints the panic. My bad. Closing
