### ISSUE TITLE
Type inference bug with operator || or &&

### ISSUE THREAD

**Issue by dovreshef** [rust-lang/rust#8283]
The following code:

    use std::rand; 
    
    fn main() { 
        if rand::random() && 1 != 2 { } 
    }

fail with errors:

    $ rustc test.rs
    test.rs:4:7: 4:24 error: the type of this value must be known in this context
    test.rs:4     if rand::random() && 1 != 2 { }
                     ^~~~~~~~~~~~~~~~~
    test.rs:4:7: 4:19 error: failed to find an implementation of trait std::rand::Rand for [type error]
    test.rs:4     if rand::random() && 1 != 2 { }
                     ^~~~~~~~~~~~

But works after switching the conditions:

    use std::rand; 
    
    fn main() { 
        if 1 != 2 && rand::random() { } 
    }

The same error occurs also with the || operator.

**Comment by arielb1** [comment]
This type-checks at 1.0.0
