### ISSUE TITLE
LLVM Coverage and "assert_eq!"

### ISSUE THREAD

**Issue by scole66** [rust-lang/rust#82853]
When using `-Zinstrument-coverage`, my coverage reports often (but not always), report things like:
```
res::strings::tests::iterator_test_01:
  253|      1|    fn iterator_test_01() {
  254|      1|        let mystr = "blue\u{E00E}";
  255|      1|        let i = CharToU16Iterator::new(mystr);
  256|      1|        let res: Vec<u16> = i.collect();
  257|      0|        assert_eq!(res, &[98, 108, 117, 101, 0xe00e]);
  258|      1|    }
```
I.e.: the `assert_eq!` is marked with no coverage. (Now, it's a whole other can of worms for why my testcases themselves should be included in coverage, but I think that's a question for the llvm people, not the rust people.)

Naturally, my expectation is that all the lines of this non-branching testcase have the same execution counts.

I've changed things around, on occasion, to `assert!(a == b)` instead, and that seems to resolve things, but I'd really rather not have to go to that step.

### Meta

`rustc --version --verbose`:
```
rustc 1.52.0-nightly (caca2121f 2021-03-05)
binary: rustc
commit-hash: caca2121ffe4cb47d8ea2d9469c493995f57e0b5
commit-date: 2021-03-05
host: x86_64-unknown-linux-gnu
release: 1.52.0-nightly
LLVM version: 12.0.0
```

**Comment by richkadel** [comment]
@scole66 PR #84582 was merged this morning. I believe the change also resolves this issue.

The commits from that PR should be available in the next nightly (tonight or tomorrow).

If possible, can you verify this next week and update/close this issue?

Thanks!

**Comment by scole66** [comment]
I've been eagerly typing `rustup update` all week long. ;) As soon as it's in the nightly channel, I'll give it a look.

**Comment by scole66** [comment]
... hits the nightly channel along with rls and rustfmt, anyway...
```
info: latest update on 2021-05-03, rust version 1.54.0-nightly (6b5de7aae 2021-05-02)
info: skipping nightly which is missing installed components 'rls', 'rustfmt'
```

**Comment by richkadel** [comment]
`rustup update --force` is what I've used to bypass this.

**Comment by scole66** [comment]
Nice. Didn't know about that. Seems like `matches!` needs your marker:
```
  414|      1|        assert!(matches!(&*node, AssignmentExpression::OpAssignment(..)));
                              ^0
```

But it does seem like all the `assert_eq!` are fixed now.

**Comment by richkadel** [comment]
Awesome (mostly 😉 ) 

Please feel free to update the issue title for the specific issue with `matches!` or close this and open a new one.

Thanks so much for the feedback!

**Comment by scole66** [comment]
Ticket for new coverage issue: #84892.

_This_ issue (i.e. `assert_eq!()`) is done.
