### ISSUE TITLE
Sporadic test failure for srcloc assembly test (non-optimized)

### ISSUE THREAD

**Issue by ehuss** [rust-lang/rust#82886]
The [srcloc.rs](https://github.com/rust-lang/rust/blob/76c500ec6c36fa8287317d6dc342a64c079301de/src/test/ui/asm/srcloc.rs) test has seen a couple sporadic failures on CI with the `x86_64-gnu-nopt` job.

* https://github.com/rust-lang/rust/pull/82877#issuecomment-792376764
* https://github.com/rust-lang/rust/pull/82847#issuecomment-792129983

The error is that it is not always emitting all 23 errors. Sometimes I see it report anywhere from 3 to 15 errors.

I'm able to reproduce locally with `rust.optimize-tests = false`, and running in a loop. The failure rate isn't high, but I can repro within a few seconds.

cc @Amanieu

**Comment by Amanieu** [comment]
This doesn't seem to happen with `Ccodegen-units=1`. However that doesn't make sense: all the `asm!`s are in a single function, there's no way they could be split over multiple codegen units, right?

**Comment by tmiasko** [comment]
AFAIK, the channel used for emitting diagnostic from codegen threads is not guaranteed to be fully drained when compilation session is aborted.

**Comment by Amanieu** [comment]
@tmiasko Is this issue considered fixed by #83328?

**Comment by tmiasko** [comment]
@Amanieu I left this open in the case there is an interest in fixing the underlying cause, if not feel free to close.

**Comment by jieyouxu** [comment]
Triage: closing in favor of a new issue to address the underlying problem.
