### ISSUE TITLE
Add a `parse_sess_created` callback to `rustc_interface::interface::Config`

### ISSUE THREAD

**Issue by hyd-dev** [rust-lang/rust#82900]
> imo this is fine, but we should look into figuring out the story around adding custom things to the depinfo in general. This seems like a larger topic (that may want to include proc macros and similar).
>
> I think we should merge this as it is and then (once clippy is synced into the rustc repo) consider doing a change there that adds a `parse_sess_created` callback that allows you to modify the session right after it was created.

_Originally posted by @oli-obk in https://github.com/rust-lang/rust-clippy/pull/6834#discussion_r589379372_

cc @flip1995

@rustbot label A-clippy

**Comment by jyn514** [comment]
cc #82763 (which has the benefit of being in-tree and can just hardcode the things it wants to do in `rustc_session`)

**Comment by hyd-dev** [comment]
> once clippy is synced into the rustc repo

It has been [synced](https://github.com/rust-lang/rust/pull/83012) now.
@rustbot claim
