### ISSUE TITLE
Rust is linking frankenstein binaries when static linking

### ISSUE THREAD

**Issue by richfelker** [rust-lang/rust#82912]
This report comes as a result of a user reporting a segfault on call to `sqlite3_open` in code using the `libsqlite3-sys` crate with musl libc, where Rust is currently defaulting to static linking. Analysis of the backtrace showed a call to address 0. The issue was speculated and later [reproduced on Twitter](https://twitter.com/remmyfoo/status/1369004378200367108?s=20) as Rust's link process emitting `DT_NEEDED` references to dynamic libraries in a static linked program (where symbolic runtime relocations are never processed and thereby end up evaluating to 0).

I don't understand the mechanism of Rust's linker invocation well enough to know exactly how this is happening, but I assume it's the equivalent of passing `-Wl,-Bdynamic` in the middle of the link command line to a C compiler driver invoking the linker.

If targeting a static binary, the linker should never be instructed to search dynamic libraries; it should only link static ones, and fail to link if they are not present.

This issue is related to, but orthogonal to, the issue of Rust currently defaulting to static linking with musl libc target. As far as I can tell, it would affect any target with static linking.

**Comment by petrochenkov** [comment]
See https://github.com/rust-lang/rust/pull/71586#issuecomment-626328134 for the catalogue of issues related to static linking.
This one looks similar to https://github.com/rust-lang/rust/issues/39998 or https://github.com/rust-lang/rust/issues/71647.

**Comment by Amanieu** [comment]
This is fixed by #111698.
