### ISSUE TITLE
core::mem::zeroed broke backward compatibility regarding treatment of C function pointers

### ISSUE THREAD

**Issue by DoumanAsh** [rust-lang/rust#82915]
If you do not want consider it a bug, then please consider it a regression
https://github.com/rust-lang/rust/issues/82914

Why we're breaking previously valid code?
Do you think it is fine to compile code just to panic later?
I do not appreciate such jokes

**Comment by CraftSpider** [comment]
I am not a Rust team member, but my understanding is:

As mentioned in the linked issue, function pointers in Rust may not be null. This behavior is guaranteed, so any code initializing them to null would be undefined behavior. As such, even if the code appeared to work, an optimization or even different computer or different memory situation, etc, may have caused it to stop working at any time. `core::mem::zeroed` is unsafe, meaning it is up to you to uphold its invariants, of which this is one. The error is not a regression, but revealing already-broken uses.

**Comment by DoumanAsh** [comment]
This is for me to decide whether it is safe or not.
Being `unsafe` `zeroed` should not impose restrictions outside of compilation time.
If we want to have function that panics on invalid zeroing, we should create safe function that would only work for types that are safe to be zeroed.

I do not understand reasoning introducing panic, hence making code that was previously working correctly panic.
If we want `zeroed` to panic then we should make it safe, otherwise there is no point in it being `unsafe`

**Comment by berkus** [comment]
> This is for me to decide whether it is safe or not.

Probably, but you cannot decide what form will this UB take on somebody else's machine. Safe or unsafe, it has to uphold invariants.

>  that was previously working correctly panic.

It was, or it wasn't. That was undefined.

**Comment by CryZe** [comment]
> This is for me to decide whether it is safe or not.

It is UB for a type to have a value that it is not allowed to have. That's one of the biggest reasons why MaybeUninit was introduced. UB is not for you to decide.

**Comment by nagisa** [comment]
> Why we're breaking previously valid code?

As per [the reference](https://doc.rust-lang.org/stable/reference/behavior-considered-undefined.html) even just producing a function pointer with invalid value (such as what `zeroed` would do) invokes undefined behaviour:

> Producing an invalid value, even in private fields and locals. "Producing" a value happens any time a value is assigned to or read from a place, passed to a function/primitive operation or returned from a function/primitive operation. The following values are invalid (at their respective type):
> * <snip...>
> * A null `fn` pointer.

The compiler could, can and will utilize this restriction.

**Comment by DoumanAsh** [comment]
If these values are invalid, `mem::zeroed` should not compile code.
Otherwise do not change runtime behavior of it and create safe alternative to it.

**Comment by nagisa** [comment]
A sounder alternative exists in the form of [`MaybeUninit`](https://doc.rust-lang.org/stable/std/mem/union.MaybeUninit.html). You can also choose to allow the function pointers to gain a nullable value by wrapping them into an `Option`.

> Otherwise do not change runtime behavior of it

But the entire point _is_ in that the behaviour of such code was always specified to be [undefined](https://en.wikipedia.org/wiki/Undefined_behavior). The runtime behaviour did not really change at all in that respect, only its manifestation. 

> If these values are invalid, mem::zeroed should not compile code.

It is linted against, you can make the compilation fail with the `#[deny(invalid_value)]` attribute or `-Dinvalid-value` flag.

**Comment by CryZe** [comment]
> It is linted against, you can make the compilation fail with the #[deny(invalid_value)] attribute or -Dinvalid-value flag.

Would it make sense for this to by deny by default in Rust 2021 maybe?

**Comment by nagisa** [comment]
I think we can probably make it deny-by-default much earlier… given it only(?) affects code that exhibits UB.

**Comment by DoumanAsh** [comment]
We're already fine with breaking code between epoch, stop doing unnecessary things like making warning a error by default within current epoch.
Seriously, respect us plebs who use UB and don't break code just because you want to feel good about yourself

**Comment by CryZe** [comment]
You seem to still have a misunderstanding: Unsafe code and undefined behavior are two different things. Undefined Behavior was never allowed and was never guaranteed to not break your code. You were just lucky that the code seemingly worked regardless. It's even in the named ">Undefined< Behavior". You have absolutely zero guarantee what the compiler does with your code. And any subsequent compiler may do something completely different, including throwing a warning and failing to compile. Now what you are thinking of is unsafe code. Yes, in unsafe code you can do a lot more than in safe code. Only in safe code does the compiler protect you from Undefined Behavior. You are however still not allowed to use Undefined Behavior anywhere in unsafe code. That's the promise you make when using an unsafe block: The compiler is unable to protect you from UB, so you promise that you ensured that yourself. However while the compiler can't promise to protect you from UB in unsafe code, it may still be able to detect UB and protect you regardless. And that's what happened here. The compiler just got smarter and helped you out.

**Comment by Mark-Simulacrum** [comment]
Linting isn't feasible, at least by rustc - it would likely have many false positives, because for example `if false { std::mem::zeroed::<&T>(); }` is sound. UB is a dynamic, not static property.
