### ISSUE TITLE
Prepare Edition Guide for Rust 2021

### ISSUE THREAD

**Issue by rylev** [rust-lang/rust#82940]
With https://github.com/rust-lang/rfcs/pull/3085, there will be a new edition of Rust. This means we'll need to update the edition guide to handle the 2021 edition as well as any changes to edition process as whole. Concretely, this means the following subtasks:
*  ~~[ ] Add machinery for handling more than just the Rust 2018 edition~~ No machinery needed.
*  [x] Add content specific to the Rust 2021 edition https://github.com/rust-lang/edition-guide/pull/232
*  [x] Rework the 2018 guide to only include edition relevant content. https://github.com/rust-lang/edition-guide/pull/232
  * According to https://github.com/rust-lang/rfcs/pull/3085, editions are no longer thought of as large marketing events for all the changes since the last edition. This is a change from how editions were originally conceived and edition guide should reflect the new reality. 
  * For example, the edition guide includes things like [loops being able to break with values](https://doc.rust-lang.org/edition-guide/rust-2018/control-flow/loops-can-break-with-a-value.html). This change was backported to Rust 2015 and so it is not relevant to the edition and should be removed. 
* [ ] Finish 2021 documentation: https://github.com/rust-lang/edition-guide/issues?q=is%3Aissue+is%3Aopen+label%3AEdition-2021

**Comment by ehuss** [comment]
Do you mind clarifying a few things?

* What machinery are you referring to?
* If the guide is modified to only include edition-specific changes, that would shrink it considerably.  Am I understanding the intent correctly?  I think that would leave about 3 of the existing 80 pages.
    * If that is true, there is a lot of content that only exists in the edition-guide that would be good to *move* to other books.  I think it would also be good to discuss if there should be better "what's new" documentation somewhere.

**Comment by rylev** [comment]
> What machinery are you referring to?

This is indeed a very vague way to refer to it. I'm unfamiliar with if the edition guide is set up to refer to multiple editions, though it looks like it already refers to Rust 2015. We simply need to add references to Rust 2021 were appropriate. Hopefully this is very little work.

>  Am I understanding the intent correctly? 

Yes, this is due to https://github.com/rust-lang/rfcs/pull/3085 changing the intent of editions to be less about marketing *all* changes since the previous edition and more about just allowing breaking changes. Indeed, having some sort of more stylized change log would be helpful. Where this should go is a good question.

**Comment by nikomatsakis** [comment]
See https://github.com/rust-lang/edition-guide/pull/232. This lays a lot of the groundwork for this issue.

**Comment by nikomatsakis** [comment]
This seems to be largely done, and there are specific issues for each piece. Going to close.
