### ISSUE TITLE
Warn when a higher-ranked trait bound variable is unused

### ISSUE THREAD

**Issue by SNCPlay42** [rust-lang/rust#82998]
This use of HRTB currently compiles without any warnings:

```rust
pub fn foo<T>() where for<'a> T: Sized {}
```

It would be helpful for the compiler to warn that the `'a` lifetime is unnecessary.

@rustbot label A-lint A-lifetimes C-feature-request

**Comment by Aaron1011** [comment]
This produces a warning with `#![warn(unused_lifetimes)]`. See https://github.com/rust-lang/rust/issues/41960

**Comment by Mark-Simulacrum** [comment]
Going to go ahead and close this in favor of https://github.com/rust-lang/rust/issues/94038 since this is otherwise working as intended (just needs that to be enabled).
