### ISSUE TITLE
Remove `PartialOrd`/`Ord` impls for `DefId` and `CrateNum`

### ISSUE THREAD

**Issue by Aaron1011** [rust-lang/rust#83006]
Both `DefId` and `CrateNum` are not stable across compilation sessions - the associated `DefPathHash` is a stable cross-session ID. However, both `DefId` and `CrateNum` have `Ord` impls, which makes it easy to accidentally sort something by the unstable `DefID`/`CrateNum` value. If this sorted result makes its way into a query result, it can lead to unstable hash values across compilation sessions. See https://github.com/rust-lang/rust/issues/82920 for an example of this occuring.

My initial attempt to remove these impls encountered a large number of usages across multiple crates.

**Comment by JohnTitor** [comment]
#85829 refactored `CrateNum` so `DefId` is the only item here.

> My initial attempt to remove these impls encountered a large number of usages across multiple crates.

Hmm, yes, for example, we use `DefId` within `BTreeMap` or `FxHashMap`. So, is the rough fix to store `DefPathHash` instead of it?

**Comment by pierwill** [comment]
This issue is part of https://github.com/rust-lang/rust/issues/90317.

**Comment by pierwill** [comment]
@Aaron1011 Looks like we can close this in favor of https://github.com/rust-lang/rust/issues/90317, yes?
