### ISSUE TITLE
rustdoc: "Show declaration" causes layout shift during page load

### ISSUE THREAD

**Issue by jsha** [rust-lang/rust#83075]
The top of a rustdoc page for a struct or trait always has `[+] Show declaration` at the top. This text is generated by main.js as part of building all the open/close toggles. Because it's built by JS, it comes in very late in the page load, which generates a noticeable layout shift.

This is particularly noticeable on mobile, here the "Show declaration" text takes up a significant fraction of the screen.

One solution would be to render this text as part of the HTML, so it doesn't have to be generated by JS.

However, I'd like to propose a different fix: For structs and traits, remove "Show declaration" text, and the declaration behind it entirely. The same content is provided in more readable form in the "Fields", "Required methods," and "Provided methods" sections. For the user who wants a link near the top of the document to see the actual declaration as it would be written out in Rust, there's already the `[src]` link.

This fix has the added advantage that besides removing a layout shift, it also reclaims some above-the-fold space for the documentation.

![image](https://user-images.githubusercontent.com/220205/111017175-a0a4f480-8366-11eb-8d4a-8fca38bbce8e.png)

![image](https://user-images.githubusercontent.com/220205/111017283-55d7ac80-8367-11eb-8ba8-df1937c4d7df.png)

![Profile-20210312T190703](https://user-images.githubusercontent.com/220205/111017130-66d3ee00-8366-11eb-9f41-fed608fba7d9.gif)

**Comment by taylordotfish** [comment]
A few issues with getting rid of the declaration:

* rustdoc doesn't generate a “Fields” section for tuple-like structs. The declaration is the only place where tuple-like struct fields appear, unless they're documented manually.

* Without the declaration, it's not clear whether a struct has any private fields, which determines whether users of that struct can directly create instances of it, or whether they have to use constructor functions.

* It's not clear what the type parameters of a generic type are without the declaration. Often, you can piece together this information by looking at the various inherent and trait impls, but not always. For example, given this struct:

  ```rust
  pub struct Test<T: Copy = u8>(pub T);
  ```

  aside from the declaration, the only place where the type parameter `T` appears is in the auto-generated impls of `Send`, `Sync`, and `Unpin`, and it seems non-ideal to have to rely on those. The biggest issue, though, is that the `Copy` bound on `T` and the default value of `u8` don't appear anywhere except in the declaration.

The “[src]” link doesn't always provide this information in an easily accessible format either—if the struct/trait/etc. was generated by a macro, the “[src]” link simply goes to the outermost macro invocation.

**Comment by jsha** [comment]
This has been resolved by #83337
