### ISSUE TITLE
WSL rustc doc

### ISSUE THREAD

**Issue by makuzaverite** [rust-lang/rust#83078]
Hello I'm currently running windows 10 and wsl with ubuntu `20.04`, but running `rustup doc` seems todo nothing, I have researched over the internet and people suggested to install `xdg-utils`  and nothing seem to have worked

**Comment by kinnison** [comment]
This is an issue ultimately with the `opener` crate.  it's tracked for `rustup` here - https://github.com/rust-lang/rustup/issues/2206 and in `opener` here - https://github.com/Seeker14491/opener/issues/8

**Comment by jonas-schievink** [comment]
closing in favor of those
