### ISSUE TITLE
Rustdoc doctest fails to compile tests with #![no_std]

### ISSUE THREAD

**Issue by lgarczyn** [rust-lang/rust#83073]
I tried this code in a rust library:

````rust
/*!
```
#![no_std]
fn main(){}
```
*/
````

I expected to see this happen:

```sh
cargo test
#test src/lib.rs - (line 1) ... ok
```

Instead, this happened:

```
failures:

---- src/lib.rs - (line 1) stdout ----
error: language item required, but not found: `eh_personality`

error: `#[panic_handler]` function required, but not found

error: aborting due to 2 previous errors

Couldn't compile the test.

failures:
    src/lib.rs - (line 1)
```

Note: the failure doesn't happen in the main.rs of a non-lib rust project. But it happens in any rust file that I've tried in a rust lib project.

### Meta
```
rustc 1.52.0-nightly (234781afe 2021-03-07)
binary: rustc
commit-hash: 234781afe33d3f339b002f85f948046d8476cfc9
commit-date: 2021-03-07
host: x86_64-unknown-linux-gnu
release: 1.52.0-nightly
LLVM version: 12.0.0
```

[doctestfail.zip](https://github.com/rust-lang/rust/files/6133999/doctestfail.zip)

**Comment by jonas-schievink** [comment]
This happens for all binary crates and is expected behavior. You can read https://doc.rust-lang.org/nomicon/beneath-std.html for more information.
