### ISSUE TITLE
Archiving an iOS app that links against code built with 1.52-nightly yields an LLVM ld error

### ISSUE THREAD

**Issue by dcow** [rust-lang/rust#83106]
Rust C-FFI libraries built with 1.52-nightly are not able to be archived into an iOS application using the Xcode Version 12.4 (12D4e):
```
ld: could not reparse object file in bitcode bundle: 'Unknown attribute kind (68) (Producer: 'LLVM12.0.0-rust-1.52.0-nightly' Reader: 'LLVM APPLE_1_1200.0.32.29_0')', using libLTO version 'LLVM version 12.0.0, (clang-1200.0.32.29)' for architecture arm64
```
For more detailed context and steps to reproduce, see discussion on: https://github.com/rust-lang/rust/issues/79408. Building with the previous "release" `nightly 2020-12-31` resolves the issue.

I'm not sure whether there's anything for rust to do here of if we just have to wait for Xcode to update.

**Comment by dcow** [comment]
Attempting to archive using Xcode Version 12.5 beta 3 (12E5244e):
```
ld: could not reparse object file in bitcode bundle: 'Unknown attribute kind (104) (Producer: 'LLVM12.0.0-rust-1.52.0-nightly' Reader: 'LLVM APPLE_1_1205.0.22.6_0')', using libLTO version 'LLVM version 12.0.5, (clang-1205.0.22.6)' for architecture arm64
```

**Comment by dcow** [comment]
I tested 1.55 nightly with the new Xcode 13 beta (which uses llvm 12+). I no longer have an issue building or archiving.

**Comment by dcow** [comment]
Just going to put a table here for reference

| rust version | llvm version | Xcode version |
| --- | --- | --- |
| 1.51 | 11 | 12 |
| 1.52 | 12 | 13 |
| 1.53 | 12 | 13 |
| 1.54 | 12 | 13 |
| 1.55 | 12 | 13 |
| 1.56 | 13 | (none) |

**Comment by xcarpentier** [comment]
Also put a link with the match xcode / lvvm versions: https://en.wikipedia.org/wiki/Xcode#Xcode_11.x_-_13.x_(since_SwiftUI_framework)_2

**Comment by screenzen** [comment]
Hey, I'm getting this error still when trying to archive. Any ideas how to resolve? Thanks!
Invalid value (Producer: 'LLVM13.0.0-rust-1.57.0-stable' Reader: 'LLVM APPLE_1_1300.0.29.3_0') for architecture arm64

**Comment by workingjubilee** [comment]
Bitcode is now deprecated by Apple going forward, and this seems to be a bug related to bitcode, and was expressed as fixed by at least one person, so I am closing this on the assumption that this is not actually a problem today.

**Comment by dcow** [comment]
> Bitcode is now deprecated by Apple going forward, and this seems to be a bug related to bitcode, and was expressed as fixed by at least one person, so I am closing this on the assumption that this is not actually a problem today.

I don't believe this was a bitcode error, strictly. I believe this is an unfortunate but probably unavoidable consequence of building with bleeding edge Rust on and targeting Apple devices. Rust was generating binaries using llvm 13 and Xcode was trying to parse them with llvm 12. Essentially Rust was writing a newer format than Xcode thought it understood (in practice everything worked fine when executing, Xcode would just barf when running "validations" at the time of packaging and uploading to Apple). If this version miss-match is only limited to bitcode's binary format (I'm not 100% on the details of the mechanics here and what the scope of libLTO is) and not generally applicable to link-time optimizations, then yes it's more or less a bitcode error and hopefully won't pop up in the future.
