### ISSUE TITLE
rustdoc: it should be possible to leave "Methods From Deref" empty, as was previously the default behaviour

### ISSUE THREAD

**Issue by slightlyoutofphase** [rust-lang/rust#83133]
For example, I would much rather have the documentation for my crate Staticvec look [as it did here](https://docs.rs/staticvec/0.10.5/staticvec/struct.StaticVec.html#deref-methods), as opposed to pulling in the docs for every single slice method [as it does now.](https://docs.rs/staticvec/0.10.6/staticvec/struct.StaticVec.html#deref-methods)

**Edit:** Some additional thoughts:
- even if this isn't possible for some reason, it would almost certainly be better to have the crate-native "Trait Implementations" section appear before the "Methods From Deref" section does, since "Trait Implementations" will pretty much always be describing things that are unique to the crate being documented and so actually directly relevant
- a good idea might also be to have the "Methods From Deref" header amount to a clickable link that redirects to the actual primary docs for whatever is being derefed to in any case where it is being left empty, if that *is* still possible

**Comment by slightlyoutofphase** [comment]
Are there any details on when precisely this changed, also? I've noticed that even though the auto-generated docs on `docs.rs` previously left the `Methods From Deref` section empty, it was seemingly always there in stuff like the official `libstd` docs for `Vec`, so presumably there has always been some kind of way of controlling `rustdoc`'s behaviour in this regard, unless I'm missing something.

**Comment by jyn514** [comment]
> Are there any details on when precisely this changed, also?

Yes, it was changed intentionally in https://github.com/rust-lang/rust/pull/80653 and mentioned in the release notes: https://github.com/rust-lang/rust/blob/master/RELEASES.md#rustdoc.

> I've noticed that even though the auto-generated docs on docs.rs previously left the "Methods From Deref" section empty for user-submitted crates, it was seemingly always filled out for stuff like the official libstd docs for Vec, so presumably there has always been some kind of way of controlling rustdoc's behaviour in this regard, unless I'm missing something.

Vec derefs directly to slice - maybe the user crates you're talking about always deref to Vec?

**Comment by jyn514** [comment]
> even if this isn't possible for some reason, it would almost certainly be better to have the crate-native "Trait Implementations" section appear before the "Methods From Deref" section does, since "Trait Implementations" will pretty much always be describing things that are unique to the crate being documented and so actually directly relevant

:+1: I like this idea.

> a good idea might also be to have the "Methods From Deref" header amount to a clickable link that redirects to the actual primary docs for whatever is being derefed to in any case where it is being left empty, if that is still possible

Hmm, I'm a little concerned the methods will be harder to find that way. We get a lot of complaints that the "Trait Implementations" section is hard to read because you have to click on the name of the trait to see what methods are available.

**Comment by slightlyoutofphase** [comment]
> Hmm, I'm a little concerned the methods will be harder to find that way. We get a lot of complaints that the "Trait Implementations" section is hard to read because you have to click on the name of the trait to see what methods are available.

Yeah, that makes sense. Honestly just showing `Trait Implementations` before `Methods From Deref` in any case where both exist would likely pretty much cover the kind of thing I was mostly concerned about by itself anyways.

**Comment by slightlyoutofphase** [comment]
Sure, I'll take a look at it tomorrow.

**Comment by slightlyoutofphase** [comment]
Got busy with some other stuff, but I've now opened a PR that make those changes, which do accomplish what you thought they would.
