### ISSUE TITLE
Intrinsics not inlined despite cfg.

### ISSUE THREAD

**Issue by human-0** [rust-lang/rust#83137]
### Code

I tried this code:

```rust
#[cfg(
    all(
        any(target_arch = "x86", target_arch = "x86_64"),
        target_feature = "sse2"
    )
)]
fn some_fn(...) -> Something {
    #[cfg(target_arch = "x86")]
    use std::arch::x86::*;
    #[cfg(target_arch = "x86_64")]
    use std::arch::x86_64::*;
    unsafe {
        some_sse2_code
    }
}

```

I expected to see this happen: The SSE2 intrinsics would be inlined. The `target_arch` was native (skylake).

Instead, this happened: The intrinsics were not inlined, and required a function call each time. Some of the functions were just two moves and the operation, others had _ZN4core9core_arch3x868m128iExt8 in them.
e.g. `_mm_or_si128` was just
```
vmovaps	xmm0, xmmword ptr [r8]
vxorps	xmm0, xmm0, xmmword ptr [rdx]
vmovaps	xmmword ptr [rcx], xmm0
ret
```
but `_mm_sub_epi64` was more complex. Both intrinsics should have been inlined.

### Version it worked on

It most recently worked on: rustc 1.50

### Version with regression

`rustc --version --verbose`:
```
rustc 1.52.0-nightly (d6eaea1c8 2021-03-14)
binary: rustc
commit-hash: d6eaea1c8860adb5302d2fbaad409e36585ab217
commit-date: 2021-03-14
host: x86_64-pc-windows-msvc
release: 1.52.0-nightly
LLVM version: 12.0.0
```

**Comment by nikic** [comment]
Probably a duplicate of #83027.

**Comment by human-0** [comment]
Indeed it is.
