### ISSUE TITLE
Inclusion of gcc_s for static builds results in unsatisfied link

### ISSUE THREAD

**Issue by cromefire** [rust-lang/rust#83143]
Related to xiph/rav1e#2690

If you run on a crate with staticlib the following:
```
cargo rustc --lib -- --print native-static-libs
```

You'd get:
```
note: Link against the following native artifacts when linking against this static library. The order and any duplication can be significant on some platforms.

note: native-static-libs: -lutil -lutil -lgcc_s -lutil -lrt -lpthread -lm -ldl -lc
```

I expected to see this happen: I'd expect it to be possible to just build a static binary from this, e.g. it only includes libraries that have static libs available

Instead, this happened: It includes `gcc_s`, which only has a shared object available and outside of mingw no static library. This results in a build error, because in a static build the library can't be resolved.

### Meta

`rustc --version --verbose`:
```
rustc 1.50.0 (cb75ad5db 2021-02-10)
binary: rustc
commit-hash: cb75ad5db02783e8b0222fee363c5f63f7e2cf5b
commit-date: 2021-02-10
host: x86_64-unknown-linux-gnu
release: 1.50.0
```

<details><summary>Backtrace</summary>
<p>

N/A

</p>
</details>

### Additional context
Initial Ideas included that this is because of the unwinder, although there seems to be something else.

Ideas for fixing it would maybe be either providing some alternative dependencies or using either `libgcc` or `libgcc_eh`, which have static counterparts available.

https://github.com/xiph/rav1e/issues/2690#issuecomment-799347663

**Comment by nagisa** [comment]
Did you specify the `+static-crt` target feature?

**Comment by cromefire** [comment]
I sadly don't have any idea where to specify that (so I'd probably say no, but as I understand it, it's implicitly called by `cargo-c` so I have no idea).

@lu-zero you probably know more about this

**Comment by lu-zero** [comment]
You may try setting the environment with `RUSTFLAGS="-C target-feature=+crt-static"` and report back.

**Comment by cromefire** [comment]
This results in:
```
Error: CliError { error: Some(cannot produce proc-macro for `arg_enum_proc_macro v0.3.0` as the target `x86_64-unknown-linux-gnu` does not support these crate types), exit_code: 101 }
```

**Comment by lu-zero** [comment]
You have to pass --target <your architecture> as workaround to a known cargo limitation.

**Comment by cromefire** [comment]
That fixes the build, but the original problem still persists. It's still emitting `gcc_s`

**Comment by cromefire** [comment]
That seems to work, it no longer links to `gcc_s`.
You seem to have to do a full clean build though, it seems like something's off with the caching, removing the `target` folder makes it work.
