### ISSUE TITLE
Separate definitions and HIR owners in the type system

### ISSUE THREAD

**Issue by cjgillot** [rust-lang/rust#83158]
Both definitions and HIR owners are represented by a LocalDefId,
but they don't have the same semantics.

HIR owners are the `owner` field of a `HirId`,
and the argument passed to the `hir_owner*` queries.
HIR owners contain the following HIR nodes: Item, TraitItem, ImplItem, ForeignItem, MacroDef,
and `GenericParam`s which come from `impl Trait` desugaring.

LocalDefId enumerate definitions in the local crate.
Definitions are a broader concept than HIR owners.
For instance, closures are definitions but not HIR owners.

On the other hand, all HIR owners are definitions.

We need to introduce a new type `HirOwner` type (name to bikeshed),
whose usage will be the following:
- `HirOwner` is defined as `struct HirOwner { def_id: LocalDefId }`;
- `HirId` becomes `{ owner: HirOwner, local_id: ItemLocalId }`;
- Item, TraitItem, ImplItem, ForeignItem, MacroDef have a `HirOwner` as their `def_id` field;
- `hir_owner*` queries take a `HirOwner` as argument;
- the passage between `HirOwner` and `LocalDefId` happens through
  the `local_def_id_to_hir_id: LocalDefId -> HirId`
  and `local_def_id: HirId -> LocalDefId` methods.

I am available on Zulip for further information.

**Comment by osa1** [comment]
@rustbot claim

I'd like to do this. @cjgillot I'll ping you on Zulip with questions.

**Comment by osa1** [comment]
I don't understand HIR ownership and I'm working on other issues currently. I'm hoping to come back to this but if anyone wants to do it in the meantime please feel free to pick this up.

**Comment by kckeiks** [comment]
@ABouttefeux Are you still working on this? I would like to pick this up.

**Comment by ABouttefeux** [comment]
@kckeiks I am not working on that please go ahead. Sorry for not responding sooner.
