### ISSUE TITLE
`const` operands in `asm!` should use inline consts rather than const promotion

### ISSUE THREAD

**Issue by bstrie** [rust-lang/rust#83169]
Elevating an item from [the `asm!` progress report](https://github.com/rust-lang/rust/issues/72016#issuecomment-761616910) from a comment to an issue so that it can be tracked:

---
`const` operands should switch to using the new inline consts instead of explicit promotion. In theory this should have no impact on existing code, but it requires inline consts to support references to generic paramters of the surrounding function, which is not supported yet.

> One aspect of asm! that I think needs further scrutiny before stabilization is const arguments, which currently are one of the few syntactic constructs that trigger promotion. Promotion is about turning a part of a function into an anonymous const (the "promoted") and using that instead of the ripped-out part of the function body. This has all sorts of "interesting" consequences (see e.g. rust-lang/rfcs#3027).
> 
> Similar to the situation for array repeat expressions in #49147, there is an alternative: we could avoid having to deal with promotion here by requiring that the const argument be either a literal (4), a named constant (CONST), or an explicit inline const (const { arbitrary_const_expr }). If that would be acceptable to y'all, I think it would be better to only support this subset upon initial stabilization. This is forward compatible with supporting more expressions by performing promotion later. The only difference this would make is one of convenience -- one could avoid having to type const { ... }.

**Comment by RalfJung** [comment]
(The syntax I suggested in the quote above is up for bikeshedding of course; the key point is that the const expression is trreated separately from the start and we don't have to hot-fix the MIR later via promotion.)

**Comment by bstrie** [comment]
> The syntax I suggested in the quote above is up for bikeshedding of course

Surely it would just use the same syntax as inline `const` in general, yes? https://github.com/rust-lang/rust/issues/76001 suggests that `const { $expr }` is the chosen syntax for this feature, but is there any reason to suspect that this is incompatible with the syntax of the `asm!` macro?

**Comment by RalfJung** [comment]
`asm!` being a macro can do almost whatever it wants. ;)
So we'd end up with something like this?
```rust
    asm!(
        "mov {0}, {1}",
        "add {0}, {number}",
        out(reg) o,
        in(reg) i,
        number = const { 5 },
    );
```

**Comment by bstrie** [comment]
Sure, although just as you say in your comment it should also be possible to elide the explicit const for the case of literals and named consts. I believe this exactly mirrors your plan for `const` array repeat expressions, yes? I.e. `[5; 2]`, `[FOO; 2]`, `[const { foo() }; 2]`?

**Comment by RalfJung** [comment]
Well, the `asm!` RFC says `const` is a required keywork here, it just does not use curly braces.

For arrays, there's not much of a "plan", but `[5; 2]` already works so we'll certainly continue supporting it. In `[expr; COUNT]`, `expr` is a normal expression syntactically, so the `const` keyword here is nothing sepcific to arrays but just the same keyword as in `let x = const { 1+2 };`. In contrast, `asm!` has a `const` keyword built-in (in the RFC).

**Comment by Amanieu** [comment]
I made an attempt at switching `const` operands to use inline consts (well, `AnonConst` to be precise) in #83916.
