### ISSUE TITLE
Tracking Issue for const_transmute_copy

### ISSUE THREAD

**Issue by usbalbin** [rust-lang/rust#83165]
Feature gate: `#![feature(const_transmute_copy)]`

This is a tracking issue for making the function `mem::transmute_copy` `const fn`.

### Public API

```rust
mod mem {
    pub const unsafe fn transmute_copy<T, U>(src: &T) -> U;
}
```

### Steps / History

- [x] Implementation: #83091
- [ ] Final commenting period (FCP)
- [ ] Stabilization PR

### Unresolved Questions

- None yet.

**Comment by RalfJung** [comment]
This got reverted again by #86003, but hopefully we can re-land it soon.

**Comment by RalfJung** [comment]
Sorry, I misread, this feature gate is not affected (but some others are).

**Comment by Finomnis** [comment]
Any news on this? I don't see anything holding it back; especially now that transmute itself is const.

**Comment by RalfJung** [comment]
Since `ptr.read()` is const-stable nowadays, I think this can be stabilized as well. Feel free to open a PR. :)

Cc @rust-lang/wg-const-eval

**Comment by Finomnis** [comment]
@RalfJung I didn't do this before, I am reading the docs for how to do this, and there's an rfcbot final commenting period thing. Should this be done? If yes, how? I probably don't have the rights to do it.

**Comment by RalfJung** [comment]
You just need to prepare a PR. I can help get the FCP process started in the PR.

**Comment by Finomnis** [comment]
@RalfJung Like this?
