### ISSUE TITLE
Formatter takes two runs to fully format comment after match arm

### ISSUE THREAD

**Issue by r00ster91** [rust-lang/rust#83173]
```rust
fn main() {
    match 1 {
        _ => {},
        // hello!
    }
}
```
A `cargo fmt` turns this into:
```rust
fn main() {
    match 1 {
        _ => {}
        // hello!
    }
}
```
and now another `cargo fmt` turns this into:
```rust
fn main() {
    match 1 {
        _ => {} // hello!
    }
}
```
This means that the formatter needs multiple runs to fully finish formatting the code. That does not seem right. I want to be able to trust the formatter in that it will do it all in one run so that I never get into the habit of running it twice each time just to be 100% sure. Therefore I report this as a bug.

**Comment by nagisa** [comment]
The issue tracker for rustfmt is at https://github.com/rust-lang/rustfmt. Hopefully somebody will transfer the issue soon, but if not you should open an issue there yourself.

**Comment by r00ster91** [comment]
Oh, right! Excuse me.
