### ISSUE TITLE
Get rid of fake DefIds in rustdoc

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#83183]
Right now, rustdoc has a whole mess of awful hacks to be able to add DefIds for things that aren't definitions: https://github.com/rust-lang/rust/blob/4c10c84c63bb31d98afad757107970150d691c1e/src/librustdoc/core.rs#L131-L140
It's unfortunate that these are needed at all, but it's *really* unfortunate that these have the same type as normal `DefId`s - they are *not* valid and *cannot* be passed to rustc APIs; trying to do so will usually panic. It also leads to lots of other hacks, like giving primitives DefIds: https://github.com/rust-lang/rust/issues/83083#issuecomment-798841595

A better alternative is to add a new wrapper type, something like
```rust
// clean/type.rs
enum DefId {
  Real(rustc_span::def_id::DefId),
  Fake(usize),
}
```
That makes it clear that the two are very different, and doesn't require hacks in rustdoc or rustc.

Things that can be removed once this is implemented:
- https://github.com/rust-lang/rust/blob/4c10c84c63bb31d98afad757107970150d691c1e/src/librustdoc/core.rs#L68
- https://github.com/rust-lang/rust/blob/4c10c84c63bb31d98afad757107970150d691c1e/src/librustdoc/core.rs#L145
- https://github.com/rust-lang/rust/blob/4c10c84c63bb31d98afad757107970150d691c1e/src/librustdoc/core.rs#L172
- https://github.com/rust-lang/rust/blob/4c10c84c63bb31d98afad757107970150d691c1e/src/librustdoc/clean/types.rs#L98 (it can just be a derive)
- https://github.com/rust-lang/rust/blob/4c10c84c63bb31d98afad757107970150d691c1e/src/librustdoc/clean/types.rs#L316
- https://github.com/rust-lang/rust/blob/4c10c84c63bb31d98afad757107970150d691c1e/compiler/rustc_hir/src/definitions.rs#L90
- https://github.com/rust-lang/rust/blob/4c10c84c63bb31d98afad757107970150d691c1e/compiler/rustc_metadata/src/rmeta/decoder/cstore_impl.rs#L468

**Comment by camelid** [comment]
Maybe a better solution would be to just get rid of fake IDs altogether? It seems like they're only used for creating monomorphized blanket impls and auto trait impls? Maybe we could remove fake IDs and instead use a new wrapper around `ItemKind` that doesn't require a DefId or something like that.

**Comment by jyn514** [comment]
@camelid I don't have any clear idea of what that could look like - I don't mind you experimenting with it, but I think it would be much harder than just making 'fake DefId' part of the type system.

**Comment by camelid** [comment]
> I don't have any clear idea of what that could look like

Yeah, I don't have a clear idea either ;)

> I think it would be much harder than just making 'fake DefId' part of the type system.

Maybe, though I think both would be very hard. At some point I think there's not much of a difference between "very hard" and "harder than very hard".
