### ISSUE TITLE
Can rust web development be mixed with Java programming?

### ISSUE THREAD

**Issue by Jzow** [rust-lang/rust#83187]
I am writing a microservice architecture project, but I personally think Java is not as good as rust in some aspects. I want to develop some API rust

So far I know about Actix web

**Comment by r00ster91** [comment]
Can this be seen as a feature suggestion for Rust to run on the JVM? I'd love to see the compiler have inbuilt support to compile for the JVM.

**Comment by jonas-schievink** [comment]
Hi! This issue tracker is mainly meant for bug reports and concrete, small feature requests. Questions like this are better asked in the user forum at https://users.rust-lang.org/ or on [one of the chat platforms](https://www.rust-lang.org/community) used by the Rust community.
