### ISSUE TITLE
Specialized slice::fill implementations are not inlined

### ISSUE THREAD

**Issue by steffahn** [rust-lang/rust#83235]
Specialized slice::fill implementations are not inlined even though they would compile down to pretty much just a single memset-call.

The `bar` function below represents manual inlining of [the implementation of fill](https://github.com/rust-lang/rust/blob/04ae50179a802d1d18bb780baa85f55864f56616/library/core/src/slice/specialize.rs#L27-L36). 

```rust
use core::ptr::write_bytes;

pub fn foo(slice: &mut [u8]) {
    slice.fill(42);
}

pub fn bar(slice: &mut [u8]) {
    unsafe {
        let ptr = slice.as_mut_ptr();
        let len = slice.len();
        write_bytes(ptr, 0_u8, len);
    }
}
```

([Playground](https://play.rust-lang.org/?version=nightly&mode=release&edition=2018&gist=316d4de4d85a594bd2f3482160f8af29))
```
    Finished release [optimized] target(s) in 0.83s
   
---------- Result ----------

playground::foo: # @playground::foo
# %bb.0:
	movl	$42, %edx
	jmpq	*<[u8] as core::slice::specialize::SpecFill<u8>>::spec_fill@GOTPCREL(%rip) # TAILCALL
                                        # -- End function

playground::bar: # @playground::bar
# %bb.0:
	movq	%rsi, %rdx
	xorl	%esi, %esi
	jmpq	*memset@GOTPCREL(%rip)          # TAILCALL
                                        # -- End function
```

I haven’t tested it in any way, but I suspect that this can be fixed by marking [the `fill` specialized implementations for `u8`, `i8`, and `bool`](https://github.com/rust-lang/rust/blob/04ae50179a802d1d18bb780baa85f55864f56616/library/core/src/slice/specialize.rs#L27-L58) as `#[inline]`.

**Comment by slightlyoutofphase** [comment]
Don't you need at the very least `#[inline]` (but not necessarily #[inline(always)]) to actually _guarantee_ cross-crate-inlining eligibility with the default no-LTO `release` profile? It'd certainly make sense to add that to all of the impls in [this file](https://github.com/rust-lang/rust/blob/04ae50179a802d1d18bb780baa85f55864f56616/library/core/src/slice/specialize.rs#L27-L36) IMO.

**Comment by the8472** [comment]
It being generic is sufficient for being _eligible_ because the monomorphized function is only created in the consuming crate once all the generics have been filled in. Adding `#[inline]` on top just encourages it further.
