### ISSUE TITLE
irrelevant variable mentioned in E0759 "needs to satisfy a `'static` lifetime requirement"

### ISSUE THREAD

**Issue by comex** [rust-lang/rust#83243]
Given: [(playground link)](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=cb8c7ec42ae05b95b6f05857c6fcacbe)
```rust
fn test1<'a>(x: &'a ()) {
    let z: Option<&'a ()> = None;
    let _: &'static () = z.unwrap();
}

fn test2<'a>(x: &'a (), y: &'a ()) {
    let _: Option<&'static ()> = Some(y);
}
```

In each function, there is a lifetime mismatch because we try to convert `&'a ()` to `&'static ()`.  However, in each, the diagnostic mentions `x`, even though `x` is completely unused:

```
error[E0759]: `x` has lifetime `'a` but it needs to satisfy a `'static` lifetime requirement
 --> src/lib.rs:3:28
  |
1 | fn test1<'a>(x: &'a ()) {
  |                 ------ this data with lifetime `'a`...
2 |     let z: Option<&'a ()> = None;
3 |     let _: &'static () = z.unwrap();
  |                            ^^^^^^ ...is captured here, requiring it to live as long as `'static`

error[E0759]: `x` has lifetime `'a` but it needs to satisfy a `'static` lifetime requirement
 --> src/lib.rs:7:34
  |
6 | fn test2<'a>(x: &'a (), y: &'a ()) {
  |                 ------ this data with lifetime `'a`...
7 |     let _: Option<&'static ()> = Some(y);
  |                                  ^^^^^^^ ...is captured and required to live as long as `'static` here
```

`x` seems to be chosen as an arbitrary variable whose type contains the lifetime at issue, `'a`.  But contrary to the diagnostic text, we're not actually "captur[ing]" "data" from it, except perhaps in the loosest metaphorical sense.  And if this were to arise in real code (as it did for me), whatever fix is needed, it's probably not to change `x`.

**Comment by pwnorbitals** [comment]
Just faced this error, that's confusing !
