### ISSUE TITLE
hint for global use of let instead of const or static 

### ISSUE THREAD

**Issue by hkBst** [rust-lang/rust#83265]
Given the following code: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=ffbf1151b3ceaee128b58616565c8774

```rust
let global_variable = 0;
```

The current output is:

```
error: expected item, found keyword `let`
 --> src/lib.rs:1:1
  |
1 | let global_variable = 0;
  | ^^^ expected item
```

Ideally the output should look like:

```
Something about Rust not supporting this syntax and to try to use either static or const instead.
```

Since this is the syntax for writing local variables, I often try to use this same syntax at global scope and get an unhelpful error message.

**Comment by hkBst** [comment]
Proof that I am not alone in this: https://users.rust-lang.org/t/a-friendly-challenge-for-rust/23197/12

**Comment by kornelski** [comment]
Another case: https://users.rust-lang.org/t/module-to-encapsulate-a-communication/68382/3
