### ISSUE TITLE
llvm-project: can't update past 5de2d189e6ad due to setInlineAsmDiagnosticHandler being gone

### ISSUE THREAD

**Issue by durin42** [rust-lang/rust#83261]
https://reviews.llvm.org/D97449 deleted this function, and I'm not familiar enough with either LLVM or Rust to know how I should patch around this. I figured I should let y'all know sooner rather than later.

Thanks!

**Comment by tmandry** [comment]
From the diff summary, it looks like this functionality got moved from LLVMContext to MCContext.

**Comment by nagisa** [comment]
From the code it appears to be going through regular `DiagnosticHandler` rather than one specific to inline asm.

**Comment by durin42** [comment]
This has been fixed for a while.
