### ISSUE TITLE
Rustdoc unhelpful error message on missing whitespace after #

### ISSUE THREAD

**Issue by nonnominandus** [rust-lang/rust#83284]
I made some documentation tests for my crate, but forgot to add a space after the pound sign (`#`) like the following example:

```rust
//! ...
//! ## Iterating over the PDB Hierarchy
//!
//! ```rust
//! #use pdbtbx;
//! #let (mut pdb, _errors) = pdbtbx::open("example-pdbs/1ubq.pdb", pdbtbx::StrictnessLevel::Medium).unwrap();
//! // Iterating over all levels
//! for model in pdb.models() {
//! ...
```

I was unaware that there should be a space after the pound sign, so I was quite startled by the resulting error message (other passed tests excluded):

```
   Doc-tests pdbtbx

running 2 tests
test src\lib.rs - (line 64) ... FAILED
test src\lib.rs - (line 26) ... ok

failures:

---- src\lib.rs - (line 64) stdout ----
error: expected one of `!` or `[`, found keyword `use`
 --> src\lib.rs:65:2
  |
4 | #use pdbtbx;
  |  ^^^ expected one of `!` or `[`

error: aborting due to previous error
```

After looking up the correct syntax in the rustdoc book I could easily solve it. But I assume this is not the best error message to provide to users.

### Meta
`rustc --version --verbose`:
```
rustc 1.50.0 (cb75ad5db 2021-02-10)
binary: rustc
commit-hash: cb75ad5db02783e8b0222fee363c5f63f7e2cf5b
commit-date: 2021-02-10
host: x86_64-pc-windows-msvc
release: 1.50.0
```

I am not entirely sure this is supposed to be a `Bug Report` but it did not really fit into any of the other categories as well. If I can do anything more to help please let me know.

</p>
</details>

**Comment by camelid** [comment]
I'm not sure if we can do much about this because the user may be using `#![feature(foo)]`, which starts with a `#`. (Note that `# ![feature(foo)]` [with a space] is valid Rust but has a different meaning in doctests.)

I guess we could give a warning if `#` is followed by anything other than `[` or `!`?

**Comment by nonnominandus** [comment]
I totally get that it is hard to do something about this. A warning like the proposed could help. In the best case (disregarding implementation details) the warning given specifically when running code in a doctest, would include the option of having a space after the pound sign. This warning could then possibly link to the different uses of this sign.

But I get that this is quite hard to achieve, and maybe if no-one else makes this mistake it is a misuse of time to build something like this.
