### ISSUE TITLE
Unify `download-*` settings in config.toml

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#83369]
Right now, there are two different download settings: `download-ci-llvm` and `download-rustc`. They are pretty similar and I imagine the knobs we'll want to tweak will be the same for both (e.g. it seems reasonable to add `"if-unchanged"` to `download-ci-llvm` now that download-rustc has it: https://github.com/rust-lang/rust/pull/83368). Additionally, this could be extended without *too* much trouble to other tools and components, like rustdoc, clippy, etc. It would be nice to combine these together in to one option (maybe `download-component`). I'd expect the old options to work but give a warning to use the new syntax.

Another feature could be to support multiple requirements, or individual components:
- `download-component = "clippy,llvm"`
- `download-component = "rustc=if-unchanged,llvm=if-available"`
- `download-component = "if-unchanged,if-available"`

cc @Mark-Simulacrum, https://github.com/rust-lang/rust/issues/81930

**Comment by Mark-Simulacrum** [comment]
I think unifying the backend implementation is OK. I don't care much about avoiding multiple options in the frontend; I think it's not necessarily bad but also seems like there's not much purpose to it - I guess I'm wondering why multiple options would be all that bad.

**Comment by camelid** [comment]
Semi-related: There's some inconsistency in naming because there's `download-ci-llvm` but also `download-rustc`. Not a big deal, but it seems like `-ci-` should be added to the latter or removed from the former.

**Comment by jyn514** [comment]
I don't think this is a very useful change.
