### ISSUE TITLE
`split_at_mut` should `#[track_caller]`

### ISSUE THREAD

**Issue by ruza-net** [rust-lang/rust#83378]
When `split_at_mut` is called with `mid > len`, an internal assertion fails. However, it doesn't track its caller, so `RUST_BACKTRACE=1` is required to determine the call site.

I tried this code:

```rust
fn main() {
    let mut x = [1];
    
    x.split_at_mut(2);
}
```

#### I expected to see this happen:

An error of the form `thread 'main' panicked at 'split index (is 2) should be <= len (is 1)'`.

#### Instead, this happened:

`thread 'main' panicked at 'assertion failed: mid <= self.len()', /rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/core/src/slice/mod.rs:1279:9`

### Meta
This occurs on stable (1.50.0), beta (1.51.0-beta.8) and nightly (1.53.0-nightly 2021-03-21).

Tested on playground.

**Comment by jyn514** [comment]
@ruza-net are you interested in adding this yourself? It should be pretty simple :) just add it to library/core/src/slice/mod.rs like it says in the panic.

**Comment by hi-rustin** [comment]
@rustbot claim

I would like to try this.

**Comment by slightlyoutofphase** [comment]
I think you need to alter the actual assertion to produce formatted output to truly get what you stated as "expected" though, don't you? Something like this:

```rust
let len = self.len();
assert!(
    mid <= len,
    "split index (is {}) should be <= len (is {}))",
    mid,
    len
);
```

**Comment by Nugine** [comment]
This issue has been solved by
+ https://github.com/rust-lang/rust/pull/91961
