### ISSUE TITLE
Tracking Issue for `Duration::try_from_secs_{f32, f64}`

### ISSUE THREAD

**Issue by mbartlett21** [rust-lang/rust#83400]
Feature gate: `#![feature(duration_checked_float)]`

This is a tracking issue for checked methods to construct a duration from a floating-point value of seconds without panicking.

### Public API

```rust
// core::time

impl Duration {
    pub const fn try_from_secs_f32(secs: f32) -> Result<Duration, FromFloatSecsError>;
    pub const fn try_from_secs_f64(secs: f64) -> Result<Duration, FromFloatSecsError>;
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FromFloatSecsError { ... }

impl core::fmt::Display for FromFloatSecsError { ... }
```

```rust
// std::error

impl std::error::Error for FromFloatSecsError { ... }
```

### Steps / History

- [x] Implementation
    - #82179
    - #90247
    - #96051
- [x] Final commenting period (FCP)
    - https://github.com/rust-lang/rust/pull/102271#issuecomment-1265324525
- [x] Stabilization PR
    - #102271

### Unresolved Questions

 - What should the error type be called?
    - Originally `FromSecsError`.
    - Changed to `FromFloatSecsError` in #90247
    - Changed and finalised as `TryFromFloatSecsError` in #102271

**Comment by workingjubilee** [comment]
This needs more testing to vet its behavior in the face of various interesting floating point values.
In particular, subnormal values and values close to the limit of f32 and f64's upper range.

**Comment by mbartlett21** [comment]
> This needs more testing to vet its behavior in the face of various interesting floating point values.
> In particular, subnormal values and values close to the limit of f32 and f64's upper range.

This just currently checks what the othee panicking methods for the same thing do.

**Comment by nvzqz** [comment]
What is left to stabilize this? It is important to me that time conversions I'm using don't panic.

**Comment by mbartlett21** [comment]
There is still an unresolved question:

### What should the error type be called?

- In the original PR, I called it `FromSecsError`.
- In #90247, @newpavlov updated the error type to `FromFloatSecsError`.

- It is still unclear whether a different name would be better.


Once that is resolved, we'll need a stabilisation PR and then, once that gets approved, it will be a month or two until it appears in stable

**Comment by arniu** [comment]
Why not just `impl TryFrom<f32 | f64> for Duration`?

**Comment by mbartlett21** [comment]
Because it isn't clear from `TryFrom` that it is meant to be seconds. It could be milliseconds or hours or days or some other reasonable measurement.
This is the same reason why `Duration` doesn't impl `From<u128>` or something. It could likewise be a lot of other units.

**Comment by lopopolo** [comment]
I came across this unstable API when debugging a panic in a time crate I maintain:

- https://github.com/artichoke/artichoke/issues/2194

I will prepare a stabilization PR shortly and hope we can resolve the open question on error type naming in the context of an FCP.

**Comment by lopopolo** [comment]
I have pushed a stabilization PR and stabilization report here: https://github.com/rust-lang/rust/pull/102271.

The stabilization PR renames the error type to `TryFromFloatSecs` to indicate the fallibility of the method like `Vec::try_reserve` and `TryReserveError`.

**Comment by Dylan-DPC** [comment]
This is stabilised already in https://github.com/rust-lang/rust/pull/102271
