### ISSUE TITLE
Incomplete documentation for IntoIterator

### ISSUE THREAD

**Issue by ChrisJefferson** [rust-lang/rust#83414]
The documentation for implementing IntoIterator talks about implementing `impl IntoIterator for MyCollection`. However, without also implementing `impl IntoIterator for &MyCollection` and `impl IntoIterator for &mut MyCollection`, users won't end up with an `into_iter`, and for loops, which most guides talk about.

I just hit this, I was very confused why my `into_iter()` was always moving, until I realised I had to implement move overloads of IntoIterator.

**Comment by the8472** [comment]
Note that having multiple `IntoIterator` implementations can lead to type inference changes, it's often clearer to use the inherent methods `.iter()` or `.iter_mut()` to get less ambiguous types. So while having those implementations may be useful it's not actually encouraged to use `.into_iter()` everywhere.

**Comment by ChrisJefferson** [comment]
(sorry for slow reply), so what is the best thing to implement if I want my container to work in for loops, for values, refs and mutable refs?

**Comment by the8472** [comment]
Take a look at `Vec` for example. Besides its [IntoIterator implementations](https://doc.rust-lang.org/std/vec/struct.Vec.html#impl-IntoIterator) it also has (by dereferencing to a slice) [iter()](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.iter) and [iter_mut()](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.iter_mut) for `Item=&T` and `Item=&mut T` iterators.

**Comment by Dylan-DPC** [comment]
Closing this to clear up the issue tracker. If you or anyone reading this still needs help you can consult the forums, discords, etc for help. Thanks
