### ISSUE TITLE
`Foo<T>: Trait` bounds (`T` is a type param) are allowed in `const fn`s

### ISSUE THREAD

**Issue by rodrimati1992** [rust-lang/rust#83452]
I tried this code:

```rust
pub trait Const {
    const C: u8;
}

impl Const for u8 {
    const C: u8 = 3;
}
pub struct Wrapper<T>(T);
impl<T: Const> Const for Wrapper<T> {
    const C: u8 = T::C;
}

const fn foo<T>() -> u8 
where
    Wrapper<T>: Const,
{
    <Wrapper<T>>::C
}

fn main(){
    const D: u8 = foo::<u8>();
    dbg!(D);
}
```

I expected to see this code not compile, because it bounds types by non-auto traits in `const fn`s.

Instead, this happened: The code compiles without errors, and prints `3`
This does error with `T: Const` bounds as expected.

### Meta

`rustc --version --verbose`:
```
rustc 1.53.0-nightly (673d0db5e 2021-03-23)
binary: rustc
commit-hash: 673d0db5e393e9c64897005b470bfeb6d5aec61b
commit-date: 2021-03-23
host: i686-unknown-linux-gnu
release: 1.53.0-nightly
LLVM version: 12.0.0
```

**Comment by slightlyoutofphase** [comment]
It's not clear to me why this would be expected not to work. The bounds are upheld correctly by the compiler in precisely the same way as they are for non-`const` fns. For example if you do `const D: usize = foo::<usize>();`, you properly get `error[E0277]: the trait bound `usize: Const` is not satisfied`. Same thing if you call `foo` in a runtime context, like `let D: usize = foo::<usize>();`, since every `const fn` is also by default a regular `fn` if called in a non-`const` context. I cannot personally think of any "upsides" of the particular trait bound restriction on `const fns` you're talking about actually existing.

**Comment by rodrimati1992** [comment]
@slightlyoutofphase That's an argument for allowing all bounds in `const fn`s

**Comment by slightlyoutofphase** [comment]
> @slightlyoutofphase That's an argument for allowing all bounds in `const fn`s

I guess my overall point is that I'm not personally aware of anywhere it's been specifically stated that this shouldn't work, and why it shouldn't work.

**Comment by rodrimati1992** [comment]
> Your `Const` trait has no methods though

It doesn't matter, you're allowed to add defaulted methods and that shouldn't break downstream users, which is why `impl const Const` needs to be required.

**Comment by slightlyoutofphase** [comment]
>It doesn't matter, you're allowed to add defaulted methods and that shouldn't break downstream users, which is why impl const Const needs to be required.

It doesn't need to be "required". The only limitation currently is that a user cannot directly write:

`fn foo<T: const Const>()`

meaning `T` has to specifically be something that implements `Const` _as_ `const`. However, as far as I'm aware, some way of writing that (even if not with the exact syntax I just used) is planned, but just not implemented yet.

>This isn't allowed now:

Yeah it is, if you use the `#![feature(const_fn)]` flag. Which anyone trying to do anything complex with `const fn` functionality specifically on the nightly compiler will be.

**Comment by jonas-schievink** [comment]
The problem is that the code posted above is accepted on stable, but the intention of the `const_trait_impl` feature is that all trait bounds on `const fn`s will require an `impl const Trait`, unless you use `T: ?const Trait` syntax to opt out, which would cause the code to no longer be accepted.

**Comment by slightlyoutofphase** [comment]
> The problem is that the code posted above is accepted on stable, but the intention of the `const_trait_impl` feature is that all trait bounds on `const fn`s will require an `impl const Trait`, unless you use `T: ?const Trait` syntax to opt out, which would cause the code to no longer be accepted.

This makes more sense if they're specifically talking about stable, where literally no feature flags can be used (meaning `const_trait_impl` and numerous other things don't actually exist there currently). They stated that they're using nightly in the initial comment, though, which is what I was going off of.

**Comment by rodrimati1992** [comment]
@slightlyoutofphase The code isn't using any features at all(so it shouldn't matter that my initial comment used nightly), and yes this works on stable in every version I tried back to Rust 1.31.0 https://rust.godbolt.org/z/7TnxfPP3W

**Comment by slightlyoutofphase** [comment]
> @slightlyoutofphase The code isn't using any features at all(so it shouldn't matter that my initial comment used nightly), and yes this works on stable in every version I tried back to Rust 1.31.0 https://rust.godbolt.org/z/7TnxfPP3W

I still don't understand how there's any kind of "forward compatibility" concern. You cannot write `const fn` code on stable that relies on anything related to `const_trait_impl` in a way that could be broken by the _compiler_ in the future, because you cannot actually implement traits as `const` on stable or call the methods of any trait in a `const fn` on stable. 

Your original example could only be broken if the maintainer of the `Wrapper` crate went ahead and changed the associated `C` constant to something completely different, which would be a breaking change entirely on their part that isn't really related to `const_fn` or `const_trait_impl` at all. An associated constant `u8` is just like any other valid constant in Rust.

**Comment by rodrimati1992** [comment]
> > [](https://rust.godbolt.org/z/7TnxfPP3W)
> 
> I still don't understand how there's any kind of "forward compatibility" concern.

SImple, the code compiles now, and it'll break whenever const impls and bounds are fully implemented.

It''ll be required to be a `const Const` impl in the `const D: u8 = foo::<u8>();` line, and the error will be "Expected implementation of `const Const` for `Wrapper<u8>`, found (non-const)`Const` impl"

I repeat, no code at all in https://github.com/rust-lang/rust/issues/83452#issue-840149353 needs to change for that to break.

**Comment by slightlyoutofphase** [comment]
> It''ll be required to be a `const Const` impl in the `const D: u8 = foo::<u8>();` line, and the error will be "Expected implementation of `const Const` for `Wrapper<u8>`, found (non-const)`Const` impl"

Again, my point is that it's not clear to me that this is actually the case for something that strictly involves nameable integral constants with known primitive types. It doesn't make any sense, and has none of the same actual stability concerns that calling const trait methods (which you cannot do currently on stable) does.

Consider something like the following, also, that does work on stable today as well:

trait Trait {
    const F: usize = 99;
}

struct X;

impl Trait for X {}

const fn foo() -> usize {
    X::F
}

What it actually does is ultimately the same thing as your example. It's just accessing the constant indirectly. Which is fine, because if someone changes `F` or removes `F` from `Trait` entirely it'd be equally as breaking of a change in both const and runtime contexts.

**Comment by rodrimati1992** [comment]
> Intentionally "dumbing it down" in the particular way you're suggesting would be very strange IMO.

No, it'd make the most sense, because you don't have to look into the function or the trait definitions to figure out whether a const impl is requried. What you're asking is that const bounds are inferred from the function definition.

**Comment by slightlyoutofphase** [comment]
> No, it'd make the most sense, because you don't have to look into the function or the trait definitions to figure out whether a const impl is requried. What you're asking is that const bounds are inferred from the function definition.

Who doesn't have to "look into" what, exactly, in what specific context? I don't understand what you mean.

**Comment by rodrimati1992** [comment]
> > No, it'd make the most sense, because you don't have to look into the function or the trait definitions to figure out whether a const impl is requried. What you're asking is that const bounds are inferred from the function definition.
> 
> Who doesn't have to "look into" what, exactly, in what specific context? I don't understand what you mean.

Imagine that function definitions are opaque, what is the constness of the bounds?

**Comment by slightlyoutofphase** [comment]
Can you give an example of what you're referring to?

**Comment by rodrimati1992** [comment]
This gives you an error, it doesn't implicitly add a Clone bound to the function
```rust
fn clone_something<T>(x: &T) -> T {
     <T as std::clone::Clone>::clone(x)
}
```
what you're proposing is analogous to inferring the `T: Clone` bound in `clone_something` and erroring at the call site, ie:
```rust
{
    struct Unclonable;
    clone_something(&Unclonable); // Erroring at this line
}
```

**Comment by slightlyoutofphase** [comment]
I'm not "proposing" anything at all. I've continuously just tried to make the point that the only possible way to use traits in `const fn` on stable currently is a way that is unrelated to and unimpacted by `const_trait_impl` (that is, by using numeric associated constants).

Also, I don't think your example all that similar to something to something like:

```

**Comment by rodrimati1992** [comment]
@slightlyoutofphase 
You don't seem to understand that Rust doesn't change what functions require of callers(at the type level) just because the body of the function changed, which is what you keep proposing should be kept about the **experimental** feature flag you're using (`#![feature(const_trait_impl)]`).

> I've continuously just tried to make the point that the only possible way to use traits in `const fn` on stable currently is a way that is unrelated to and unimpacted by `const_trait_impl` (that is, by using numeric associated constants).

I agree with that, so long as we're talking about cases that don't require trait bounds being added to the function. The example in my first comment is wrong *because* of the trait bound.

Here is a case that isn't problematic:
```rust
trait Foo {
    const X: u8;
}

struct Generic<T>(T);

impl<T> Foo for Generic<T> {
    const X: u8 = 10;
}

const fn hello<T>() -> u8 {
    Generic::<T>::X
}
```
The reason this isn't problematic is because no bound needs to be added to `hello` either explicitly or implicitly.

**Comment by slightlyoutofphase** [comment]
> You don't seem to understand that Rust doesn't change what functions require of callers(at the type level) just because the body of the function changed.

I understand that perfectly, just as I understand these are experimental features and everything else. I don't agree it's an accurate description of what we're talking about here though, particularly in the presence of stuff like the language-level syntactic use cases for `const_trait_impl` such as the `Deref` example I included above.

Your `hello` example to me has just as many standard ways of going wrong as anything else, const or not, though. It uses `Generic` internally, which still isn't "known" at all as a caller if you haven't read the source, and if the person who is writing the `hello` function is not the same person who maintains `Generic` then `Generic` could itself be altered at any time such that the way it's being used in `hello` no longer compiles.

**Comment by rodrimati1992** [comment]
@slightlyoutofphase Your const Deref example is not incompatible with anything I said.

**Comment by slightlyoutofphase** [comment]
> @slightlyoutofphase Your const Deref example is not incompatible with anything I said.

I meant it as an example of something that technically presents the same scenario you're describing as being the overall issue here, where any struct at all may or may not be validly dereferenceable with `*` in a const context. So as a "caller" of `*` you either have to rely on documentation, or "just try it".

>eg: not being able to prove that the code that initializes associated constants terminates

That certainly wasn't my point. And I still disagree that any bounds are being "changed" overall even currently. Everything we're talking about here is a matter of "is or is not an explicit compile-time error".

**Comment by rodrimati1992** [comment]
> Everything we're talking about here is a matter of "is or is not an explicit compile-time error".

What I'm talking about is *exclusively* about whether a `const fn` requires an impl of a  `const Trait` when called in a `const` context (including inside of `const fn`s that call them).

I'm saying that this is how it should work in generic contexts:
```rust
use std::ops::Add;

const fn foo<T: Add>() {
    // The function definition doesn't matter WRT its bounds, so I'm not writing it.
}

const fn bar<T: ?const Add> (l: T, r: T) {
    foo::<T>()
}
```
which should eventually error at the `foo::<T>()` line when `bar` is defined, with this error:
```
error[E0277]: cannot add `T` to `T` in const contexts
 --> src/lib.rs:6:11
  |
1 | const fn foo<T: std::ops::Add>() {
  |                 ------------- required by this bound in `foo`
...
6 |     foo::<T>()
  |           ^ no implementation for `T + T` usable in const contexts
  |
help: consider changing the `?const Add` bound for the type parameter `T` to `Add`
  |
5 | const fn bar<T: Add> (l: T, r: T) {
  |                         ^^^^^
```
`bar` should never need to be called for this error to happen.


That code above is analogous to this:
```rust
fn foo<T: std::ops::Add>() {
    // The function definition doesn't matter
}

fn bar<T> (l: T, r: T) {
    foo::<T>()
}
```
which errors at the `foo::<T>()` line when `bar` is defined:
```
error[E0277]: cannot add `T` to `T`
 --> src/lib.rs:6:11
  |
1 | fn foo<T: std::ops::Add>() {
  |           ------------- required by this bound in `foo`
...
6 |     foo::<T>()
  |           ^ no implementation for `T + T`
  |
help: consider restricting type parameter `T`
  |
5 | fn bar<T: Add> (l: T, r: T) {
  |         ^^^^^
```
`bar` never needs to be called for this error to happen.

**Comment by slightlyoutofphase** [comment]
Yeah, that makes sense as far as how the opt-out should interact with everything else. I wasn't arguing that.

**Comment by jonas-schievink** [comment]
Previous discussion: https://rust-lang.zulipchat.com/#narrow/stream/146212-t-compiler.2Fconst-eval/topic/Bounds.20on.20non-type-parameters.20work.2C.20is.20that.20on.20purpose.3F/near/222214631

**Comment by rodrimati1992** [comment]
> Yeah, that makes sense as far as how the opt-out should interact with everything else. I wasn't arguing that.

How, this clearly looks like you're arguing that the required constness of bounds should be essentially compile-time duck typing, where the contents of the function determines what constness is required of the caller:
```rust
const fn do_add<T: Copy + Add<Output = T>>(a: T) -> T {
    // Don't use Add
    a
}

const fn really_do_add<T: Copy + Add<Output = T>>(a: T) -> T {
    // Do use Add
    a + a
}

// Works.
const A: NotConstAdd = do_add(NotConstAdd {});

// Does not work.
const B: NotConstAdd = really_do_add(NotConstAdd {});
```
My argument is that neither should work, because it makes is a breaking change to use `+` inside the function.

**Comment by rodrimati1992** [comment]
> > eg: not being able to prove that the code that initializes associated constants terminates
>
> That certainly wasn't my point. 

What was your point then, the only thing that could break in [`Generic::<T>::X`](https://github.com/rust-lang/rust/issues/83452#issuecomment-806318421) that would reach callers of `hello` is if there's a panic inside of the expression that initializes the `X` associated constant. The alternatives all get triggered when `hello` is defined, without being called by anyone.

**Comment by slightlyoutofphase** [comment]
> > Yeah, that makes sense as far as how the opt-out should interact with everything else. I wasn't arguing that.
> 
> How, this clearly looks like you're arguing that the required constness of bounds should be essentially compile-time duck typing, where the contents of the function determines what constness is required of the caller:
> 
> ```rust
> const fn do_add<T: Copy + Add<Output = T>>(a: T) -> T {
>     // Don't use Add
>     a
> }
> 
> const fn really_do_add<T: Copy + Add<Output = T>>(a: T) -> T {
>     // Do use Add
>     a + a
> }
> 
> // Works.
> const A: NotConstAdd = do_add(NotConstAdd {});
> 
> // Does not work.
> const B: NotConstAdd = really_do_add(NotConstAdd {});
> ```
> 
> My argument is that neither should work, because it makes is a breaking change to use `+` inside the function, even for a no-op (eg: `if false { a + a }`). If you think that dynamically unreached code inside a function shouldn't trigger this error, it's even worse of an idea.
> Your argument is that it should be _easier_ for code to break due to changes in implementation details, and I don't see a good motivation.



> Previous discussion: https://rust-lang.zulipchat.com/#narrow/stream/146212-t-compiler.2Fconst-eval/topic/Bounds.20on.20non-type-parameters.20work.2C.20is.20that.20on.20purpose.3F/near/222214631

@jonas-schievink: thanks for the link, that's helpful info to have. I guess I'm still a bit unclear about how something that is not _itself_ a trait impl, but rather a free function (or non-trait inherent method) is ultimately intended to behave, though. E.G:

```rust
// Say this is just a regular inherent struct method
pub const fn get_usize(self) -> usize {
    NonSelfConcreteImplementerOfSomeTrait::USIZE
}
```

or for a more complex example:

```rust
trait Trait {
    const VALUE: usize = 999;
}

struct Struct {}

impl Trait for Struct {}

impl Struct {
    const fn get_usize(&self) -> usize {
        1
    }
}

// Does not refer to `Trait` externally at all.
const fn get_usize(s: &Struct) -> usize {
    // Technically, either side of the addition operation below could become
    // invalid code if the person who maintains `Struct` changes it, assuming
    // that's not the same person who maintains this `get_usize` free function.
    s.get_usize() + <Struct as Trait>::VALUE
}

const STRUCT: Struct = Struct {};

const U: usize = get_usize(&STRUCT);

fn main() {
    println!("{}", U);
}
```

@rodrimati1992
Every single code example I've given in this entire thread was examples of things that currently produce very explicit, easy-to-understand **compile-time** errors if used incorrectly. Each time I said "does not work" in the comments, I meant "rustc errors on this while compiling it."

Why would I be talking about runtime errors as far as your `hello` example? I was talking about the numerous things that could be done to make `hello` also produce compile-time errors, such as `X` no longer being `u8`, or `Generic` no longer implementing `Foo`, and so on.

**Comment by rodrimati1992** [comment]
> Every single code example I've given in this entire thread was examples of things that currently produce very explicit, easy-to-understand compile-time errors if used incorrectly

That's missing my point entirely, it doesn't matter if it **eventually** errors, read my point about guarantees.

**Comment by rodrimati1992** [comment]
If you keep saying that it happens to work now, you are making the mistake of assuming the current semantics is likely what will go to stable, so *obviously* it's not a bug that the code in my original comment is accepted.

**Comment by rodrimati1992** [comment]
You might think you're making a point by showing const fns that panic, you're not, all you're doing is showing limitations in Rust that should be avoided (in the design of the language) whenever there's a good alternative.

**Comment by rodrimati1992** [comment]
This is intentionally allowed now, so no point in leaving this open.
