### ISSUE TITLE
Prestaging for air-gapped bootstrap

### ISSUE THREAD

**Issue by smijolovic** [rust-lang/rust#83455]
Is there a way to pull the three tar files (rust-std, rustc, cargo) prior to the build stage for bootstrapping in an environment without connectivity?

In bootstrap.py,:
download_stage0

Pulls the three tar files and extracts them.  I see that ./x.py accepts stage builds...but is there a way to call download_stage0 to package the tar files for packaging?

**Comment by jyn514** [comment]
This is pretty easy to add if someone wants to tackle it - add a new argument to bootstrap.py and exit early after https://github.com/rust-lang/rust/blob/10f4ce324baf7cfb7ce2b2096662b82b79204944/src/bootstrap/bootstrap.py#L1058 if it's set.

@rustbot label +E-easy +E-mentor

**Comment by RoryNickolls** [comment]
I can pick this up. It'd be my first contribution here.

@rustbot claim

**Comment by jyn514** [comment]
I'm going to close this until I hear back about whether `make prepare` does what you want. https://github.com/rust-lang/rust/pull/98464#issuecomment-1166449013
