### ISSUE TITLE
Always got the ServerSelectionError:  Server selection timeout: No available servers

### ISSUE THREAD

**Issue by Eric-Chen** [rust-lang/rust#83464]
After I test the example almost the same as the code in README, but I always got errors like:
{ kind: ServerSelectionError { message: "Server selection timeout: No available servers. Topology: { Type: Unknown, Servers: [ { Address: alicloud_mongodb_pub_url, Type: Unknown }, ] }" }, labels: [] }

code:
`
my main function:
fn main() -> mongodb::error::Result<()> {

    let mut options = ClientOptions::builder()
    .hosts(vec![
        StreamAddress {
            hostname: "aliyun_key.mongodb.rds.aliyuncs.com".into(),
            port: Some(myport),
        }
    ])
    .direct_connection(Some(true))
    .credential(Some(Credential::builder().username(Some(String::from("myusername"))).password(Some(String::from("mypassword"))).build()))
    .build();

    let client = Client::with_options(options)?;
    let db = client.database("mydb");
    let collections = db.list_collections(None, None)?;
    for collection in collections {
        match collection {
            Ok(col_obj) => {
                println!("{:?}", col_obj);
            }
            _ => {
                println!("nothing")
            }
        }
    }

    Ok(())
}
`

I've tested the readonly standalone aliyun instance and also the replicaset, but it's been all the same.
After debug track, I found the topology attempt_to_select_server returned the empty selected servers, and the call is:
topology_description.suitable_servers_in_latency_window(criteria). the parameter here should be as follows, in fn Client::get_session_support_status:
let criteria = SelectionCriteria::Predicate(Arc::new(move |server_info| {
                    server_info.server_type().is_data_bearing()
                }));
Finally, I tried the local mongo server, and it worked.

So is there any advice on configuration? did i miss something? Thanks

**Comment by jonas-schievink** [comment]
Hi! This issue tracker is mainly meant for bug reports and concrete, small feature requests. Questions like this are better asked in the user forum at https://users.rust-lang.org/ or on [one of the chat platforms](https://www.rust-lang.org/community) used by the Rust community.
