### ISSUE TITLE
ICE: wrong const argument causes a couple of ICE

### ISSUE THREAD

**Issue by JohnTitor** [rust-lang/rust#83466]
This is ICE since 1.50.0, error -> ICE.

[playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=cf3974bbf1f60582855f2de6df86ffc8)

```rust
struct S;
impl S {
    fn func<'a, U>(self) -> U {
        todo!()
    }
}
fn dont_crash<'a, U>() {
    S.func::<'a, dont_crash>()
}

fn main() {}
```

_Originally posted by @chengniansun in https://github.com/rust-lang/rust/issues/82792#issuecomment-792102995_

**Comment by hameerabbasi** [comment]
Bisected:

searched nightlies: from nightly-2020-01-01 to nightly-2021-03-17
regressed nightly: nightly-2020-11-18
searched commits: from https://github.com/rust-lang/rust/commit/f5230fbf76bafd86ee4376a0e26e551df8d17fec to https://github.com/rust-lang/rust/commit/c919f490bbcd2b29b74016101f7ec71aaa24bdbb
regressed commit: https://github.com/rust-lang/rust/commit/c6a6105bccd5599daf0ecef40c4b5ffa175fc1c1

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.0</summary>

Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --test-dir=. --start=2020-01-01 --regress=ice
```
</details>

**Comment by JohnTitor** [comment]
Thanks for bisecting, @hameerabbasi! I believe #79032 is the cause.

**Comment by lcnr** [comment]
Assigning `P-medium` and removing `I-prioritize` as [discussed](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2383466.20ICE.3A.20wrong.20const.20argument.20causes.20a.20couple.20of.20ICE) in the prioritization working group.

@rustbot label: +P-medium -I-prioritize
