### ISSUE TITLE
Add diagnostic for ++ and -- usages

### ISSUE THREAD

**Issue by dbofmmbt** [rust-lang/rust#83502]
Given the following code [in the playground:](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=14fc6b865440a61afb2d57546fe99d35)

```rust
fn main() {
    let i = 0;
    i++;
}
```

The current output is:

```
   Compiling playground v0.0.1 (/playground)
error: expected expression, found `+`
 --> src/main.rs:3:7
  |
3 |     i++;
  |       ^ expected expression

error: aborting due to previous error

error: could not compile `playground`

To learn more, run the command again with --verbose.
```

I think the message for errors involving `++` or `--` should understand that the user is trying to use an operator which doesn't exist in Rust and suggest an idiomatic way to do the increment/decrement operation.

# Explanation

Languages like C, Java or Javascript use `++` and `--` to increment or decrement integer variables, respectively. As Rust does not support them, it may be good to add an specific diagnostic for those cases, suggesting the user to use something like `i += 1` instead.

**Comment by camelid** [comment]
`--` is trickier because `i--2` is a valid expression, so by the time we realize there's a problem (e.g. when we reach a semicolon), we've lost the context that it's two `-`s in a row.

**Comment by leonardo-m** [comment]
See also #82987

**Comment by estebank** [comment]
> -- is trickier because i--2 is a valid expression, so by the time we realize there's a problem (e.g. when we reach a semicolon), we've lost the context that it's two -s in a row.

This is not uncommon. Small typos end up with errors in the parser or name resolution or the type checker depending on small variations 🙂

I think #82987 covers the "it was parsed as `neg (neg (val) )`" case.

**Comment by camelid** [comment]
> I think #82987 covers the "it was parsed as `neg (neg (val) )`" case.

Though I don't think it will handle the `i--;` case, since that's a syntax error.
