### ISSUE TITLE
Error message doesn't give full path in suggestion.

### ISSUE THREAD

**Issue by Lokathor** [rust-lang/rust#83513]
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=d854c189b0a198c091da3ccf429e0ec9

It suggests adding `Sum` to the bounds, but `Sum` is *not* in scope, so typing directly what it says just leads to another error.

Interestingly, Mul was suggested as std::ops::Mul.

So it should likely suggest the correct prefix for the Sum trait.

**Comment by hi-rustin** [comment]
@estebank I've found the corresponding suggest and trait_ref, but I don't know how to get its prefix, do you have any suggestions?

**Comment by estebank** [comment]
@hi-rustin you'll want to use this function where the suggestion is being created

https://github.com/rust-lang/rust/blob/72ebebe474aae7203a27fdc1296617edd01321f1/compiler/rustc_middle/src/ty/print/pretty.rs#L102-L112
