### ISSUE TITLE
Suggest and link grcov for source-based-code-coverage

### ISSUE THREAD

**Issue by elshize** [rust-lang/rust#83520]
Hi, I think it might be beneficial to mention `grcov` here: [source-based-code-coverage](https://doc.rust-lang.org/nightly/unstable-book/compiler-flags/source-based-code-coverage.html).

I'm not suggesting replacing the current documentation, but an additional mention of that would be good. I'm speaking from experience, I first tried following the docs, but it turned out to be quite difficult to understand (the tools, not the docs), while `grcov` simplifies it a lot, but at first I didn't know about it, only found out about it recently from this blog post: [link](https://www.collabora.com/news-and-blog/blog/2021/03/24/rust-integrating-llvm-source-base-code-coverage-with-gitlab/).

So I just wanted to suggest that, maybe it could be helpful for others.

I could even add a section myself, but I want to first make sure the doc team is on board.

**Comment by clubby789** [comment]
@rustbot label +A-docs

The given link is currently dead

**Comment by Dylan-DPC** [comment]
Closing this as the page no longer exists on unstable book and this is briefly mentioned on the rust reference (though not much) and if needs to be improved, it's better creating an issue there
