### ISSUE TITLE
Rustc suggests both std and core imports at times

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust#83564]
rustc often offers a help to import something from std and core:

```rust
error[E0433]: failed to resolve: use of undeclared type `NonZeroU32`
  --> ...\test.rs:20:33
   |
20 | ...                   NonZeroU32::new(5).unwrap(),
   |                       ^^^^^^^^^^ not found in this scope
   |
help: consider importing one of these items
   |
6  | use core::num::NonZeroU32;
   |
6  | use std::num::NonZeroU32;
   |
```

Perhaps in such situations rustc could use an heuristic to suggest only one of the two imports.

**Comment by Manishearth** [comment]
cc @estebank feels like we should _at least_ show `std` first here?

**Comment by leonardo-m** [comment]
> feels like we should _at least_ show `std` first here?

This is quite useful in situations like the rust playground because there sometimes there are many different sources for a function, and sometimes the std one (that's most times the one you really want) gets elided in the "others" sources.

**Comment by estebank** [comment]
We already have a couple of hacks for these kind of suggestions, so I'd be fine with just modifying the code here to push any `use` suggestion that starts with `core::` to the end of the list, or at the very least, after `std::`.

https://github.com/rust-lang/rust/blob/ee0357af3b57379153e023bbc91975e26301e40c/compiler/rustc_resolve/src/diagnostics.rs#L1640
