### ISSUE TITLE
Tracking Issue for `#![feature(const_slice_first_last)]`

### ISSUE THREAD

**Issue by a1phyr** [rust-lang/rust#83570]
This is a tracking issue for  `#![feature(const_slice_first_last)]`.

New `const` functions are:
- `slice::first`
- `slice::split_first`
- `slice::last`
- `slice::split_last`

Blocking on `#![feature(const_mut_refs)]`:
- `slice::first_mut`
- `slice::split_first_mut`
- `slice::last_mut`
- `slice::split_last_mut`

### Steps

- [x] Implementation: #83571
- [x] Stabilization PR (non-mut part): #86593 
- [ ] Stabilization PR (mut part)

**Comment by jhpratt** [comment]
Partial stabilization up as #86593.

**Comment by RalfJung** [comment]
@rust-lang/libs-api we're finally ready to const-stabilize the `mut` parts of this as well, I think. :)

**Comment by dtolnay** [comment]
@rfcbot fcp merge

`const` for these already-stable functions:

- https://doc.rust-lang.org/nightly/core/primitive.slice.html#method.first_mut
- https://doc.rust-lang.org/nightly/core/primitive.slice.html#method.split_first_mut
- https://doc.rust-lang.org/nightly/core/primitive.slice.html#method.last_mut
- https://doc.rust-lang.org/nightly/core/primitive.slice.html#method.split_last_mut
