### ISSUE TITLE
Tracking Issue for `core::iter::zip`

### ISSUE THREAD

**Issue by cuviper** [rust-lang/rust#83574]
Feature gate: `#![feature(iter_zip)]`

This is a tracking issue for `core::iter::zip`, a function that combines two `IntoIterator` arguments into a `Zip` iterator.

### Public API

```rust
// core::iter
pub fn zip<A, B>(a: A, b: B) -> Zip<A::IntoIter, B::IntoIter>
where
    A: IntoIterator,
    B: IntoIterator,
```

### Steps / History

- [x] Implementation: #82917
- [x] Final commenting period (FCP) https://github.com/rust-lang/rust/issues/83574#issuecomment-991151625
- [ ] Stabilization PR #91881

### Unresolved Questions

- None yet.

**Comment by joshtriplett** [comment]
This has been around for a while, and I haven't seen any issues reported with it. Shall we stabilize this?

@rfcbot fcp merge

**Comment by scottmcm** [comment]
Ah, the reason it's worth having instead of encouraging `Iterator::zip(a, b)` is that it has different bounds?

**Comment by BurntSushi** [comment]
The [current docs](https://doc.rust-lang.org/core/iter/fn.zip.html) seem to indicate that this is equivalent to `Iterator::zip` by referencing its docs, but doesn't call out why the free function `zip` exists. What is the motivation of stabilizing this?

**Comment by thepheer** [comment]
The motivation is explained in #82917.

**Comment by ibraheemdev** [comment]
I realize that this has already merged, but it might have been nicer as a `zip!` macro that flattens nested tuples.


```rust
for (((a, b), c), d) in ia.zip(ib).zip(ic).zip(id) {
   // ...
}

for (a, b, c, d) in iter::zip!(ia, ib, ic, id) {
   // ...
}
```

**Comment by scottmcm** [comment]
@ibraheemdev that's available in https://docs.rs/itertools/latest/itertools/macro.izip.html if you'd like.

It's not clear whether `core` wants such macros.  Like it waited for const generics before getting a bunch of array stuff, it might be waiting for variadic generics to let that be just `zip(ia, ib, ic, id)` eventually.
