### ISSUE TITLE
Convert 'may not' to either 'must not' or 'might not' in the standard library documentation

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#83584]
"may not" has two possible meanings:
1. A command: "You may not stay up past your bedtime."
2. A fact that's only sometimes true: "Some cities may not have bike lanes."

In some cases, the meaning is ambiguous: "Some cars may not have snow
tires." (do the cars *happen* to not have snow tires, or is it
physically impossible for them to have snow tires?)

It would be better to change places where the standard library uses the "description of
fact" meaning to say "might not" instead, and change the "command" meaning to "must not".

You can find places where "may not" is used like so:

```
fd '.*' library/ | rg -v 'LICENCE|backtrace|stdarch' | xargs rg --glob '!library/backtrace/crates/backtrace-sys/**' 'may not'
```
_Originally posted by @jyn514 in https://github.com/rust-lang/rust/pull/83582_

**Comment by jyn514** [comment]
@amalik18 FYI a lot of the changes were already done in https://github.com/rust-lang/rust/pull/83614, you could start from there :)

**Comment by amalik18** [comment]
Oh......I completely forgot about that hahahah

**Comment by amalik18** [comment]
I'm trying to create a new branch but i'm getting a `ERROR: Permission to rust-lang/rust.git denied to amalik18.` Any pointers?

**Comment by jyn514** [comment]
@amalik18 are you trying to download using SSH? Use HTTP instead: `git set-url origin https://github.com/rust-lang/rust.git`.

**Comment by amalik18** [comment]
Yep using HTTPS. I even generated a public access token. Still getting the error:
```
remote: Permission to rust-lang/rust.git denied to amalik18.
fatal: unable to access 'https://github.com/rust-lang/rust.git/': The requested URL returned error: 403
```

**Comment by jyn514** [comment]
@amalik18 can you join the Zulip so I can help you debug this without spamming the issue tracker? https://rust-lang.zulipchat.com/

**Comment by amalik18** [comment]
https://github.com/rust-lang/rust/pull/87445

**Comment by amalik18** [comment]
The PR has been merged. https://github.com/rust-lang/rust/pull/87445 @jyn514  you can go ahead and close if you'd like.

**Comment by jyn514** [comment]
Thanks for working on this!
