### ISSUE TITLE
Cross-compiling to s390x musl is missing __rdl_alloc when `codegen-units-std` is not set to 1

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#83600]
I do not have the time or hardware to replicate this. The original error came up in zulip: https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/bootstrapping.20on.20s390x.2Fmips.20for.20musl/near/227436553

cc @Mark-Simulacrum @kaniini @nagisa

**Comment by kaniini** [comment]
This is because of musl actually.  It’s because libc needed to be adapted for musl s390x i believe.

**Comment by jyn514** [comment]
> This is because of musl actually. It’s because libc needed to be adapted for musl s390x i believe.

Does that mean you can replicate this on x86_64-musl? What changes does libc need?

**Comment by kaniini** [comment]
The libc crate did not have definitions for musl on s390x.  I think the latest libc crate will be fine.  And yes, it is reproducible when building a cross compiler.

**Comment by jyn514** [comment]
> The libc crate did not have definitions for musl on s390x. I think the latest libc crate will be fine. And yes, it is reproducible when building a cross compiler.

I think this is fixed then? Or at least, this issue isn't tracking anything useful.
