### ISSUE TITLE
Explicitly specifying the type of self using the syntax `self: Box<Self>` is sort of vestigial.  The feature of allowing `Box<Self>` as the type of `self`, along with the syntax for explicitly writing out the type of `self`, sort of slipped into 1.0 without anyone really considering the issue.  The other syntax is strongly preferred.

### ISSUE THREAD

**Issue by haaami01** [rust-lang/rust#83616]
Explicitly specifying the type of self using the syntax `self: Box<Self>` is sort of vestigial.  The feature of allowing `Box<Self>` as the type of `self`, along with the syntax for explicitly writing out the type of `self`, sort of slipped into 1.0 without anyone really considering the issue.  The other syntax is strongly preferred.

The explicit type syntax will probably be deprecated at some point.

_Originally posted by @eefriedman in https://github.com/rust-lang/rust/issues/27941#issuecomment-133752819_

**Comment by jonas-schievink** [comment]
Looks like this was opened accidentally.
