### ISSUE TITLE
Move primitive docs to `core`

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#83624]
Rust primitives are currently documented in `std`, but in some cases we want to link to primitives from `core` (cc #83577). Also, `core` seems like it would be a better place to document primitives since they are available in programs that are `no_std` (yes, they're also available in `no_core` programs, but we have to put the docs *somewhere*).

We would probably have to re-export the primitives in `std` (and `alloc` too?) so as not to break links.

What do you (`T-rustdoc`, `T-libs`) think?

cc @rust-lang/rustdoc

**Comment by jyn514** [comment]
This has been discussed before in https://github.com/rust-lang/rust/issues/73423, I would rather keep discussion in one issue.

**Comment by camelid** [comment]
Sounds good, I didn't know if there was a previous issue.
