### ISSUE TITLE
Downloaded llvm doesn't include `link-type.txt`

### ISSUE THREAD

**Issue by Lucretiel** [rust-lang/rust#83625]
I tried this:

```rust
python3 x.py test library/std
```

I expected to see this happen: A successful built & test of the standard library

Instead, this happened:

```
Updating only changed submodules
Submodules updated in 0.04 seconds
    Finished dev [unoptimized + debuginfo] target(s) in 0.19s
thread 'main' panicked at 'std::fs::read_to_string(ci_llvm.join("link-type.txt")) failed with No such file or directory (os error 2)', src/bootstrap/config.rs:834:33
stack backtrace:
   0: rust_begin_unwind
             at /rustc/14b27555a03f4abf9b8d80ea34f59144e2ded5e4/library/std/src/panicking.rs:493:5
   1: std::panicking::begin_panic_fmt
             at /rustc/14b27555a03f4abf9b8d80ea34f59144e2ded5e4/library/std/src/panicking.rs:435:5
   2: bootstrap::config::Config::parse
             at ./src/bootstrap/config.rs:834:33
   3: bootstrap::main
             at ./src/bootstrap/bin/main.rs:14:18
   4: core::ops::function::FnOnce::call_once
             at /rustc/14b27555a03f4abf9b8d80ea34f59144e2ded5e4/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
failed to run: /home/nathan/rust/build/bootstrap/debug/bootstrap test library/std
Build completed unsuccessfully in 0:00:00
```

The file it wants is `./build/x86_64-unknown-linux-gnu/ci-llvm/link-type.txt`. The only files in this directory are `bin/`, `lib/`, `include/`, and `manifest.in`.

I suspect this has something to do with `download-ci-llvm = "if-available"`, which is the recommended setting for standard library contributors.

This error occurred on WSL2 running Ubuntu: `Linux LAPTOP-HR7UF1BP 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`.

### Meta

This is on a recent master branch: 4a20eb6a9da36c88ee929826c4f1eb8d7ea393b2.

**Comment by Mark-Simulacrum** [comment]
Hm, this seems unexpected - the llvm package *should* always contain that file as of late. Could you provide the commit hash rustbuild is trying to download? It should be in the full log after an rm -rf build or so. (The full log may also be useful).

Additionally, can you say if this was previously working for you?

**Comment by Lucretiel** [comment]
It was previously working for me several months ago; I'm sorry that I don't remember when that was. I've been working on other things and haven't tried to run `x.py` since at *least* January and maybe not even then.

**Comment by Lucretiel** [comment]
Seems to be fine now 😑 I wish I had more to offer. I ran it several times last night with different configurations and `rm -rf build target` and it kept happening, but now it's fine (and the file is present). I'll reopen this issue if it happens again.
