### ISSUE TITLE
`--remap-path-prefix` does not remap all path prefixes

### ISSUE THREAD

**Issue by ChrisDenton** [rust-lang/rust#83635]
I'm using the `x86_64-pc-windows-msvc` toolchain and target.

My system environment variables:

`CARGO_HOME` = `C:\Users\Chris\AppData\Local\Programs\Cargo`
`RUSTUP_HOME` = `C:\Users\Chris\AppData\Local\Programs\Rust`
`CARGO_TARGET_DIR` = `Z:\target`

Without setting `--remap-path-prefix` the final binary has source paths from `CARGO_HOME` and `RUSTUP_HOME`. It also has a `.pdb` file (Windows debug file) in `CARGO_TARGET_DIR`.

When setting `--remap-path-prefix` I had to be careful with path separators as the replacement is documented as being "purely textual" (which is honestly a bit scary considering Rust will freely mix path separators on Windows, though hopefully it's not an issue in this case).

Ok so I set `RUSTFLAGS`:

    $env:RUSTFLAGS = "--remap-path-prefix=C:\Users\Chris\AppData\Local\Programs\Cargo\=src --remap-path-prefix=C:\Users\Chris\AppData\Local\Programs\Rust\=rsrc --remap-path-prefix=Z:\target\=target"

Then, after cleaning the target directory, I built [ripgrep](https://github.com/BurntSushi/ripgrep) (as a presumably representative project). I used the command:

    git clone https://github.com/BurntSushi/ripgrep
    cd ripgrep
    cargo +nightly build --release

As expected, this replaced the `CARGO_HOME` prefix in the final binary. However it did not replace all the `RUSTUP_HOME` path prefixes. Specifically with this prefix:

`C:\Users\Chris\AppData\Local\Programs\Rust\toolchains\nightly-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\`

It also didn't remap the path to the `.pdb` file. This is somewhat expected as changing that requires setting [a linker argument](https://docs.microsoft.com/en-us/cpp/build/reference/pdbaltpath-use-alternate-pdb-path?view=msvc-160).

### Meta

`rustc --version --verbose`:
```
rustc 1.53.0-nightly (07e0e2ec2 2021-03-24)
binary: rustc
commit-hash: 07e0e2ec268c140e607e1ac7f49f145612d0f597
commit-date: 2021-03-24
host: x86_64-pc-windows-msvc
release: 1.53.0-nightly
LLVM version: 12.0.0
```

### Notes

* Changing `--remap-path-prefix` to a single common base directory didn't help.
* Stable (1.51) has the same issue.

**Comment by chemsaf3** [comment]
will this also help with similar cargo issue https://github.com/rust-lang/cargo/issues/9311 ?

**Comment by ChrisDenton** [comment]
@chemsaf3 Could you try setting `--remap-path-prefix` and see if it works for you? You can do so by setting the `RUSTFLAGS` environment variable to something like this:

`--remap-path-prefix=D:\REDACTED\.cargo\registry=registry`

Then do:

    cargo clean
    cargo build --release

**Comment by chemsaf3** [comment]
i tried that and in my case it did not work

**Comment by ehuss** [comment]
Do you maybe have the rust-src component installed?  There's a known issue with it (#73167).

**Comment by ChrisDenton** [comment]
Ah, that would be it then. I somehow missed that when searching for issues. I'll close this in favour of that issue.

**Comment by chemsaf3** [comment]
> 
> 
> Do you maybe have the rust-src component installed? There's a known issue with it (#73167).

i do not have rust-src installed via rustup when i list components

**Comment by chemsaf3** [comment]
@ehuss can you reopen please? i dont have rust-src installed and have this issue

**Comment by ehuss** [comment]
@chemsaf3 I recommend opening a new issue. Please try to include very exact steps on how to reproduce.

**Comment by chemsaf3** [comment]
@ehuss @ChrisDenton already provide exact steps

**Comment by ChrisDenton** [comment]
@chemsaf3 I'm an unable to reproduce this issue without the `rust-src` component installed. It would help if you could create your own issue with the exact steps you've taken so I can try to reproduce that.
