### ISSUE TITLE
Tracking Issue for `alloc::collections::BinaryHeap::as_slice`

### ISSUE THREAD

**Issue by frol** [rust-lang/rust#83659]
Feature gate: `#![feature(binary_heap_as_slice)]`

This is a tracking issue for `std::collections::BinaryHeap::as_slice`, a method that returns a slice of the data that is stored in the BinaryHeap (the order is arbitrary).

### Public API

```rust
impl BinaryHeap<T> {
    pub fn as_slice(&self) -> &[T]
}
```

### Steps / History

- [x] Implementation: #82331
- [ ] Final commenting period (FCP)
- [ ] Stabilization PR

### Unresolved Questions

- None yet.

**Comment by saolof** [comment]
If this is added, it means that the order of the underlying slice is added to the API, which is useful for some purposes. In that case, is it possible to add a .sort_slice() method, for when you want that slice to be sorted?

**Comment by dspyz-matician** [comment]
This seems useful for efficiently selecting a uniform random element.

**Comment by SmnTin** [comment]
Can we stabilize it?

**Comment by dtolnay** [comment]
@SmnTin would you be able to share a link or an explanation of a real-world use case?

@dspyz-matician is this a real use case? In what scenario would you be keeping elements in a `BinaryHeap` when needing to randomly select among them?

**Comment by dspyz-matician** [comment]
@dtolnay I have a RRT-like stochastic search algorithm that continually keeps the top N strategies it's found. It randomly selects one of these strategies, clones it, performs a random modification to get a new strategy, then if the new strategy is better than the current worst, it inserts it and pops the current worst one off the top.

**Comment by dtolnay** [comment]
Thanks!

@rust-lang/libs-api:
@rfcbot fcp merge

`BinaryHeap::as_slice` returns `&[T]` containing the heap elements in arbitrary order. Regarding whether we should be concerned that exposing the elements in some unspecified order will be problematic, there is already a stable `into_vec` that returns the heap elements as `Vec<T>`, also documented as returning them in arbitrary order. (There is also `into_sorted_vec`, which does a heapsort.)
