### ISSUE TITLE
One can put repr(align) into repr(packed) with generics

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#83672]
Usually, one cannot put `repr(align)` fields into `repr(packed)` structs:
```rust
#[repr(align(8))]
struct Align8(u32);

#[repr(packed)]
struct Packed(Align8); // error
```

However, this check can be circumvented using generics:
```rust
#[repr(align(8))]
pub struct Align8(u32);

#[repr(packed)]
pub struct Packed<T>(T);

pub type PackedAlign8 = Packed<Align8>;

pub fn foo(_x: PackedAlign8) {}
```

I don't know why this restriction exists in the first place, but I think we have one of two situations here:
* The restriction is truly needed, as parts of the compiler rely on it, and we have a problem here.
* The restriction is not really needed, and we could relax this check.

Cc @eddyb @nagisa

**Comment by RalfJung** [comment]
This is the exact same problem we had with `repr(transparent)` where we also had a check that could be circumvented with generics... we should probably do a proper audit of all these checks as that seems to be a weak spot.

Cc @nikomatsakis

**Comment by hyd-dev** [comment]
Is this a duplicate of #80926?

**Comment by RalfJung** [comment]
It is, good point, thanks!
