### ISSUE TITLE
newly added next_if uses impl Trait

### ISSUE THREAD

**Issue by leshow** [rust-lang/rust#83688]
https://doc.rust-lang.org/std/iter/struct.Peekable.html#method.next_if

Shouldn't this use a type param with a bound? With impl trait it's not possible to use turbofish. I'm assuming this is why type params are used everywhere in the std lib (ignoring legacy reasons)
```
pub fn next_if<F>(
    &mut self,
    func: F
) -> Option<<I as Iterator>::Item>
where
   F:  FnOnce(&<I as Iterator>::Item) -> bool
```

If this is undesirable feel free to close, if it's a change that would accepted, I can submit a PR.

**Comment by jyn514** [comment]
@leshow you can't name the types of closures or functions. When would turbofish be useful here?

**Comment by bluss** [comment]
Custom-implementing `FnOnce` is an experimental feature, but that allows implementing it for any of your own named types. Another example is to name function pointer types that also implement `FnOnce`.

This method is stable now, so it's something that should have been discussed in stabilization.

**Comment by leshow** [comment]
I'm not claiming it's super useful, it's just something I noticed when looking through the docs. Like @bluss said there are some edge cases where it's possible to try to use it and it won't work. To be safe, it seems like using type params in std is a good idea.

```
  let mut iter = (0..5).peekable();
  while iter.next_if::<fn(&usize) -> bool>(pred).is_some() {}

fn pred(item: &usize) -> bool {
    todo!()
}
```

This doesn't compile, for example, although it's obviously not necessary.

**Comment by Enselic** [comment]
> If this is undesirable feel free to close

> This method is stable now, so it's something that should have been discussed in stabilization.

Triage: Closing as won't fix.
