### ISSUE TITLE
Have `for pattern in iter` not borrow the iterator

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#8372]
Test case:

    let mut iter = range(1, 10);
    for i in iter {
        printfln!(i);
        // error: cannot borrow `iter` as mutable more than once at a time
        printfln!(iter.next());
    }

The above currently fails, but I think it should be valid and equivalent to:

    let mut iter = range(1, 10);
    loop { match iter.next() { None => break, Some(i) => {
        printfln!(i);
        printfln!(iter.next());
    }}

In other words, the for loop should only borrow the iterator long enough to call `next()`, leaving the loop body free to use it.

I understand that this might not be possible when a more complex expression is used as the iterator. The for loop needs to evaluate the expression once and keep the result in an anonymous variable, thus borrowing. Maybe there could be a special case when the iterator expression is "simple" enough: a variable, struct field access, etc?

**Comment by japaric** [comment]
#20790 implemented the new for-loops that take the iterator by value, so this issue can't be fixed (without changing the semantics in a backwards incompatible way). This should be closed.

**Comment by SimonSapin** [comment]
Fair enought. I’m happy with the `while let Some(value) = iterator.next() {` trick.
