### ISSUE TITLE
No-op function call affects overflow error below

### ISSUE THREAD

**Issue by r00ster91** [rust-lang/rust#83808]
I tried this code (https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=202f73e993354404bc266b817d665469):

```rust
fn function() { }

fn main() {
    let size = 1_u8;
    // function();
    0 - size;
}
```
It results in:
```
   Compiling playground v0.0.1 (/playground)
warning: function is never used: `function`
 --> src/main.rs:1:4
  |
1 | fn function() {}
  |    ^^^^^^^^
  |
  = note: `#[warn(dead_code)]` on by default

warning: unused arithmetic operation that must be used
 --> src/main.rs:6:5
  |
6 |     0 - size;
  |     ^^^^^^^^
  |
  = note: `#[warn(unused_must_use)]` on by default

error: this arithmetic operation will overflow
 --> src/main.rs:6:5
  |
6 |     0 - size;
  |     ^^^^^^^^ attempt to compute `0_u8 - 1_u8`, which would overflow
  |
  = note: `#[deny(arithmetic_overflow)]` on by default

error: aborting due to previous error; 2 warnings emitted

error: could not compile `playground`

To learn more, run the command again with --verbose.
```
This is what I expect to happen. But if I uncomment the line, i.e. run this:
```rust
fn function() {}

fn main() {
    let size = 1_u8;
    function();
    0 - size;
}
```
Instead, this happens:
```
   Compiling playground v0.0.1 (/playground)
warning: unused arithmetic operation that must be used
 --> src/main.rs:6:5
  |
6 |     0 - size;
  |     ^^^^^^^^
  |
  = note: `#[warn(unused_must_use)]` on by default

warning: 1 warning emitted

    Finished dev [unoptimized + debuginfo] target(s) in 1.56s
     Running `target/debug/playground`
thread 'main' panicked at 'attempt to subtract with overflow', src/main.rs:6:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I don't know but this doesn't seem right. This empty function call without any meaning has an effect on whether I will get a compile time error or a runtime error.
It's very simplified here but on a high level in my abstracted code it was very confusing.
I don't think the function call should have an effect on the line below it. 

### Meta

This happens on the stable (1.51.1), beta and nightly channel.

**Comment by jonas-schievink** [comment]
This is working as expected. The lint is best-effort and is driven by constant propagation, which does not currently propagate past function calls.

**Comment by r00ster91** [comment]
> This is working as expected. The lint is best-effort and is driven by constant propagation, which does not currently propagate past function calls.

I see. Does currently mean it might change in the future? Is there an issue tracking this? Otherwise maybe this one can be used to track it?

**Comment by eggyal** [comment]
In the general case, it is of course impossible to statically check (at compile-time) for overflow: the exceptions are where operations involve only const expressions: which is of course what's happening here.  It's nice that the compiler is able to spot many of those cases and provide a compile-time error, but if your arithmetic might overflow you really ought to be using checked operations anyway.

**Comment by r00ster91** [comment]
Fair enough! Rust already does a nice enough job anyway.
