### ISSUE TITLE
"Useless comparison" warnings should be squelchable in generic code

### ISSUE THREAD

**Issue by dhardy** [rust-lang/rust#83802]
See: https://github.com/kas-gui/easy-cast/pull/16

This macro is supposed to handle type conversions for any integer type and compile down to sensible code in each case; these comparisons should never be evaluated when useless (assuming appropriate optimisations).

**Comment by eggyal** [comment]
This is the `unused_comparisons` lint.  You could just apply a `#[allow(unused_comparisons)]` attribute?

**Comment by dhardy** [comment]
... sure.

I was used to printing the lint name alongside warnings.

**Comment by eggyal** [comment]
> I was used to printing the lint name alongside warnings.

...and [it did](https://github.com/kas-gui/easy-cast/runs/2258749287#step:5:17), but only on the first such warning.

**Comment by eggyal** [comment]
Perhaps when a macro causes triggers a lint, it would be more helpful if the error/warning was (by default) shown only once but with a note along the lines of "repeated n times"?

**Comment by dhardy** [comment]
Yes, it would be very helpful to omit repeated warnings and errors if they are identical to previous ones (including same line number). It's quite easy with macros to get *many* pages of identical reports.
