### ISSUE TITLE
Add lint to detect dereferencing of NULL pointers

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#83856]
I propose we add a lint that detects code like
```rust
*(0 as *const i32)
*ptr::null()
*ptr::null_mut()
```
Some people seem to think that this is okay in contexts like `&*(0 as *const i32)` or `addr_of!(*(0 as *const i32))`, but that is not the case -- `*` on a NULL pointer is UB even as a place expression.

To implement this, you can use the `invalid_value` lint as a template:

https://github.com/rust-lang/rust/blob/9d8f833e0587b9c3991f94b227369f38ee48613a/compiler/rustc_lint/src/builtin.rs#L2360

`check_expr` should check for [`Unary`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_hir/hir/enum.ExprKind.html#variant.Unary) expressions with a `Deref` operator, and then check the operand to be either a cast of `0` to a pointer type, or a call to one of the `null` methods. To detect the methods, make them "diagnostic items"; the `invalid_value` lint does that e.g. for `mem::zeroed` so it can again serve as a template here.

**Comment by RalfJung** [comment]
Ah, turns out clippy already has a lint for this `zero_ptr`, so maybe we should just move that to rustc? Cc @rust-lang/clippy

**Comment by ABouttefeux** [comment]
Thanks :)

**Comment by slightlyoutofphase** [comment]
@RalfJung 

Did you mean something slightly different with your "okay in contexts like" examples, perhaps? Neither of those two actually compile as written, since they're just attempts to deference something that isn't even a pointer. You get:

`error[E0614]: type `usize` cannot be dereferenced`

in both cases.

**Comment by RalfJung** [comment]
*oops* I screwed up the casts, should be fixed now.

**Comment by Manishearth** [comment]
Yeah, happy to have Clippy lints upstreamed to rust, let us know when it's done so we can deprecate it on our end

**Comment by ABouttefeux** [comment]
@RalfJung for detecting a call like `ptr::null()` you said to use [`TyCtxt::is_diagnostic_item`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/context/struct.TyCtxt.html#method.is_diagnostic_item). However I do not know what to use for the symbol argument. There is `compiler\rustc_span\src\symbol.rs` that defines symbol but nothing looks like creating a null ptr. Should I add one what should it look like ?

**Comment by RalfJung** [comment]
You first need to add the diagnostic item attribute to the relevant function inside `library`, like so:

https://github.com/rust-lang/rust/blob/58e71896506edb701f276158bd2f47e8788a1133/library/core/src/mem/mod.rs#L621

This name must be globally unique, e.g. `ptr_null` and `ptr_null_mut`.

Then you add those names to the list in `compiler\rustc_span\src\symbol.rs` (please keep it alphabetically sorted), and then you can use them for `is_diagnostic_item`.
