### ISSUE TITLE
E0658 should suggest `if Some(foo) == expr`

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#83860]
The following output should have emitted a single error and suggested an equality check instead:

```
error[E0658]: destructuring assignments are unstable
   --> compiler/rustc_trait_selection/src/traits/wf.rs:287:35
    |
287 |         if Some(trait_ref.def_id) = tcx.lang_items().fn_once_trait() {
    |            ---------------------- ^
    |            |
    |            cannot assign to this expression
    |
    = note: see issue #71126 <https://github.com/rust-lang/rust/issues/71126> for more information
    = help: add `#![feature(destructuring_assignment)]` to the crate attributes to enable

error[E0308]: mismatched types
   --> compiler/rustc_trait_selection/src/traits/wf.rs:287:12
    |
287 |         if Some(trait_ref.def_id) = tcx.lang_items().fn_once_trait() {
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `bool`, found `()`
```

**Comment by eggyal** [comment]
I think you must mean for `E0308`(not `E0658`) to suggest `==` whenever a `bool` is expected but an assignment expression found instead?

**Comment by estebank** [comment]
I meant on the first one and silencing the second one, but if we only keep the second one and silence the first, that'd be fine with me too, and probably better long term.

**Comment by torhovland** [comment]
A similar fix is here:
https://github.com/rust-lang/rust/commit/ea7e885204e1ed6b18406e84708abef748925ec5

I had a look, but couldn't figure out an easy way to detect from one of the error conditions whether or not the other is also triggered.

**Comment by estebank** [comment]
[Current output](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=86909aaf4cba2d27f56ef16a57f93665):

```
error[E0308]: mismatched types
 --> src/main.rs:7:8
  |
7 |     if Some(x.a) = foo {}
  |        ^^^^^^^^^^^^^^^ expected `bool`, found `()`
  |
help: consider adding `let`
  |
7 |     if let Some(x.a) = foo {}
  |        +++
```
