### ISSUE TITLE
Rustdoc ignores -W help

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#83883]
I tried this code: `rustdoc -W help`
I expected to see this happen: Rustdoc prints a list of all lints, the same way rustc does.
Instead, this happened: Rustdoc ignored the flag.

### Meta

`rustdoc --version`: rustdoc 1.53.0-nightly (0b417ab5c 2021-04-03)

**Comment by eggyal** [comment]
`-W help` option is parsed into `librustdoc::config::Options::describe_lints`, but is then ignored:

https://github.com/rust-lang/rust/blob/39eee173fbcc21462d255b364b87715cd33b62db/src/librustdoc/config.rs#L100-L102

It should be pretty straightforward to instead call `rustc_driver::describe_lints` when this flag is set.

@rustbot claim

**Comment by jyn514** [comment]
Make sure you call init_lints first, or it will be missing rustdoc's own lints.

**Comment by eggyal** [comment]
Re adding a test for this... is there any way to have `compiletest` check only for whether some substring appears within stderr?   Else every time a lint is added/removed, or its level modified, the test will need updating—which seems far too brittle to me?

**Comment by jyn514** [comment]
> Else every time a lint is added/removed, or its level modified, the test will need updating—which seems far too brittle to me?

I mean, personally that seems ok to me as long as you can update it with `--bless`. But if you think it's a hassle you could use `--error-pattern`.
