### ISSUE TITLE
Reenable the mac valgrind bot

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#8389]
With the new runtime using lots of stack it looks like valgrind needs to be recompiled to support the amount of memory we're mapping:

http://buildbot.rust-lang.org/builders/auto-mac-64-opt-vg/builds/819/steps/test/logs/stdio

cc #8267

**Comment by steveklabnik** [comment]
Triage: @brson, what's up with this one?

**Comment by steveklabnik** [comment]
We no longer have bots with `-vg` in the name, but I'm not sure if we run valgrind tests on the regular bots, and if so, if they're still disabled on the mac bots.

**Comment by alexcrichton** [comment]
Unless we get valgrind working on OSX this isn't really actionable, so closing.
