### ISSUE TITLE
High memory use on Rust 1.51.0 with thin LTO and debuginfo

### ISSUE THREAD

**Issue by jonasmalacofilho** [rust-lang/rust#83911]
Rust 1.50.0 is able to link the example bellow using a few GB of memory, but 1.51.0/nightly needs at least 30 GB, at which point either I or the OOM killer has to abort it.

```rust
// src/main.rs

use actix_web::{web, App, HttpServer, Responder};
use std::net::TcpListener;

async fn greet() -> impl Responder {
 "Hello, World!"
}

#[actix_web::main]
async fn main() -> std::io::Result<()> {
    let listener = TcpListener::bind("127.0.0.1:8080")?;

    HttpServer::new(|| App::new().route("/", web::get().to(greet)))
        .listen(listener)?
        .run()
        .await?;

    Ok(())
}
```

```toml
# Cargo.toml

[package]
name = "example"
version = "0.1.0"
authors = ["Jonas Malaco <jonas@protocubo.io>"]
edition = "2018"

[dependencies]
actix-web = "3.3"
reqwest = "0.10"

[profile.release]
lto = "thin"
debug = true
```

I wasn't able to reduce it beyond this, at least for now.  Removing the _unused_ dependency to reqwest, changing the LTO setting to false or fat, disabling debuginfo, or using `-Clinker-plugin-lto` are, each, enough to bring back the memory consumption to manageable levels.

After being aborted by the OOM killer, this is the error message:

```
$ cargo build --release
   [ ... ]
   Compiling example v0.1.0 (/home/jonas/Code/issues/rust/1.51-explosive-lto)
error: could not compile `example`

Caused by:
  process didn't exit successfully: `rustc --crate-name example --edition=2018 src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C opt-level=3 -C lto=thin -C debuginfo=2 -C metadata=576df4506149e7e2 -C extra-filename=-576df4506149e7e2 --out-dir <pwd>/target/release/deps -L dependency=<pwd>/target/release/deps --extern actix_web=<pwd>/target/release/deps/libactix_web-e15a9d0e8b71dcac.rlib --extern reqwest=<pwd>/target/release/deps/libreqwest-953a39d56f962952.rlib -L native=<pwd>/target/release/build/brotli-sys-7accbad0b10c603b/out` (signal: 9, SIGKILL: kill)
```

### Meta

`rustc --version --verbose` (stable):
```
rustc 1.51.0 (2fd73fabe 2021-03-23)
binary: rustc
commit-hash: 2fd73fabe469357a12c2c974c140f67e7cdd76d0
commit-date: 2021-03-23
host: x86_64-unknown-linux-gnu
release: 1.51.0
LLVM version: 11.0.1
```

`rustc --version --verbose` (nightly):
```
rustc 1.53.0-nightly (07e0e2ec2 2021-03-24)
binary: rustc
commit-hash: 07e0e2ec268c140e607e1ac7f49f145612d0f597
commit-date: 2021-03-24
host: x86_64-unknown-linux-gnu
release: 1.53.0-nightly
LLVM version: 12.0.0
```

**Comment by apiraino** [comment]
Assigning priority as discussed as part of the [Prioritization Working Group procedure](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2383911.20High.20memory.20use.20on.20Rust.201.2E51.2E0.20with.20thin.20LTO.20and.20deb.E2.80.A6) and removing `I-prioritize`.

@rustbot label -I-prioritize +P-high

**Comment by jonasmalacofilho** [comment]
Bisected:

searched nightlies: from nightly-2021-01-01 to nightly-2021-03-24
regressed nightly: nightly-2021-02-06
searched commits: from https://github.com/rust-lang/rust/commit/4f4656d46d84a488ae3df34b08f362d7071036a0 to https://github.com/rust-lang/rust/commit/23adf9fd843da7a3394c824b056f93151aaa40ad
regressed commit: https://github.com/rust-lang/rust/commit/5605b5d693ac0aba5b506923e3e99ec927969d04

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.0</summary>


Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --start 2021-01-01 --end 2021-03-24 -- build --release 
```
</details>

---

That said, this is no longer reproduceable starting<sup>1</sup> with nightly-2021-04-02.

<sup>1</sup> I wasn't able to get nightly-2021-04-01 with rustup; nightly-2021-03-31 still shows the behavior described above.

**Comment by pnkfelix** [comment]
Based on [previous comment](https://github.com/rust-lang/rust/issues/83911#issuecomment-816359753), namely:

> That said, this is no longer reproduceable starting1 with nightly-2021-04-02.

I'm going to close this as fixed.
