### ISSUE TITLE
Non-ASCII identifiers should be restricted within extern blocks.

### ISSUE THREAD

**Issue by crlf0710** [rust-lang/rust#83923]
It was mentioned in https://github.com/rust-lang/reference/pull/999 that in the original RFC text, there's text that said the 
non-ASCII identifiers should be disallowed within extern blocks.

This is a niche use-case and i believe this doesn't need to block stablization. Creating this issue here to track it.

**Comment by jonas-schievink** [comment]
What will something like

```rust
extern {
    fn ö();
}
```

actually link against? This seems like it might be a forward-compatiblity hazard when linking to external code, since the precise mangling/encoding isn't clear

**Comment by Manishearth** [comment]
I think we should just disallow for now; and later check out what C does and match that.

**Comment by Manishearth** [comment]
@crlf0710 do you want to implement this?

**Comment by crlf0710** [comment]
@Manishearth Sure, let me give it a try.

**Comment by crlf0710** [comment]
Implemented in #83936 .

**Comment by tmiasko** [comment]
On the other hand the use of non-ASCII symbol names is already stable through link_name attribute.

**Comment by ogoffart** [comment]
Out of curiosity, I checked how Clang and GCC mangle the symbol: they simply use UTF-8.
MSVC doesn't seem to allow non-ascii in identifier.

```c++
extern "C" void héllo() {} // Mangle to "h\C3\A9llo"
void hélla() {} // mangle to "?h\C3\A9lla@@YAXXZ" or "_Z6h\C3\A9llav"
```
(Notice how the byte-length encoding in C++ is using the UTF-8 byte count, and not the code point count, as I would expect)
https://godbolt.org/z/bK8P71P46

**Comment by Manishearth** [comment]
Yeah I feel like the functionality can be re-added with an FCP without much work, there just needs to be some research on how stable those mangling schemes are around this.

**Comment by Manishearth** [comment]
As for `link_name`, my take on that is that once you're using that you're trying something weird and know what you're doing; there is no point restricting it further since it's very easy to accidently block out legit use cases.

**Comment by danielhenrymantilla** [comment]
Inversely, I've just noticed that despite usage of properly-ASCII `link_name`, if the "Rust name" is non-ASCII then it is still rejected:

```rs
extern {
    #[link_name = "cat"]
    fn ᓚᘏᗢ();
}
```

😿
