### ISSUE TITLE
`#[doc(hidden)]` doesn't work on module or crate re-exports

### ISSUE THREAD

**Issue by jplatte** [rust-lang/rust#83939]
Minimal reproduction:

```rust
mod foo {
    pub mod bar {}
}

#[doc(hidden)]
pub use foo::bar;

#[doc(hidden)]
pub use std as _std;
```

I expected to see this happen: No docs for the `#[doc(hidden)]` re-exports

Instead, this happened: Both re-exports show up in the generated doc page

### Meta

<summary> <details>

`rustc --version --verbose`:
```
rustc 1.51.0 (2fd73fabe 2021-03-23)
binary: rustc
commit-hash: 2fd73fabe469357a12c2c974c140f67e7cdd76d0
commit-date: 2021-03-23
host: x86_64-unknown-linux-gnu
release: 1.51.0
LLVM version: 11.0.1
```

`rustc +nightly --version --verbose`:
```
rustc 1.53.0-nightly (07e0e2ec2 2021-03-24)
binary: rustc
commit-hash: 07e0e2ec268c140e607e1ac7f49f145612d0f597
commit-date: 2021-03-24
host: x86_64-unknown-linux-gnu
release: 1.53.0-nightly
LLVM version: 12.0.0
```

</details></summary>

**Comment by jplatte** [comment]
Luckily, there is an easy workaround: a `#[doc(hidden)]` module containing `pub use thing_to_be_reexported::*;`.

**Comment by jyn514** [comment]
@jplatte your example doesn't compile:
```rust
error[E0365]: `foo` is private, and cannot be re-exported
 --> inline.rs:6:9
  |
6 | pub use foo as bar;
  |         ^^^^^^^^^^ re-export of private `foo`
  |
  = note: consider declaring type or module `foo` with `pub`

error: extern crate `std` is private, and cannot be re-exported (error E0365), consider declaring with `pub`
 --> inline.rs:9:9
  |
9 | pub use std as _std;
  |         ^^^^^^^^^^^
  |
  = note: `#[deny(pub_use_of_private_extern_crate)]` on by default
  = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
  = note: for more information, see issue #34537 <https://github.com/rust-lang/rust/issues/34537>
```

**Comment by jplatte** [comment]
Sorry, fixed the module part of the example. But re-exporting an external crate should always work, no?

**Comment by jyn514** [comment]
@jplatte now it compiles, but rustdoc hides all the examples as I'd expect: 
![image](https://user-images.githubusercontent.com/23638587/113767223-6cfe8580-96ec-11eb-957c-365754428937.png)
```
$ rustdoc --version
rustdoc 1.53.0-nightly (138fd56cf 2021-04-02)
```

> But re-exporting an external crate should always work, no? Is that error new?

See https://github.com/rust-lang/rust/issues/34537, I don't have opinions. Rustdoc doesn't emit that lint which I consider a bug, working on a PR for that now.

**Comment by jyn514** [comment]
> See #34537, I don't have opinions. Rustdoc doesn't emit that lint which I consider a bug, working on a PR for that now.

Oh, it turns out this is already a hard error on nightly: https://github.com/rust-lang/rust/pull/80763

**Comment by jplatte** [comment]
Okay, found out why my minimum example is wrong: This bug needs another re-export level to trigger. So I guess it's a duplicate of #53417.
