### ISSUE TITLE
A tutorial to demonstrate practical alternatives to unsafe shared mutable state

### ISSUE THREAD

**Issue by bstrie** [rust-lang/rust#8395]
Rust deliberately restricts the use of shared mutable state out of concern for safety. However, this is no solace to users coming from other languages who are used to making effective use of shared mutable state to Get Things Done. We need a document that describes practical approaches used in rustc and Servo to safely work around this restriction.

**Comment by steveklabnik** [comment]
Yes, this is basically subsumed by 'write a better threads guide', which is already an open bug. comparing and contrasting different ways of dealing with shared state belongs there.
