### ISSUE TITLE
rustdoc: improve src link/add edit link

### ISSUE THREAD

**Issue by djc** [rust-lang/rust#83959]
If I read documentation on docs.rs and find a typo or some other small issue in documentation, the number of steps involved in sending a PR for a fix feels not worth it (for projects where I don't already have a contributing role). It would be great if there was maybe an `[edit]` link next to `[src]` that would link to the proper place, for example

https://docs.rs/tonic/0.4.1/tonic/transport/struct.Channel.html#method.builder

might link to

https://github.com/hyperium/tonic/blob/master/tonic/src/transport/channel/mod.rs#L80

or even

https://github.com/hyperium/tonic/edit/master/tonic/src/transport/channel/mod.rs#L80

(In fact, maybe the `src` link should change to point to GitHub where possible?)

**Comment by jyn514** [comment]
I think this is a duplicate of https://github.com/rust-lang/docs.rs/issues/1007.

**Comment by djc** [comment]
Yup, that's fair.
