### ISSUE TITLE
Fish shell error while sourcing ~/.cargo/env

### ISSUE THREAD

**Issue by 72siddharth** [rust-lang/rust#83958]
I recently switched to Arch and decided to download Rust. Rustup and Cargo commands seem to work fine, but everytime I start Fish this message pops up:
```~/.cargo/env (line 4): 'case' builtin not inside of switch block
case ":${PATH}:" in
^
from sourcing file ~/.cargo/env
	called on line 8 of file ~/.profile
from sourcing file ~/.profile
	called on line 14 of file ~/.config/fish/config.fish
from sourcing file ~/.config/fish/config.fish
	called during startup
source: Error while reading file “/home/sid/.cargo/env”
```
Fish Version --> 3.2.1
Rustup Version --> 1.23.1
I'm kind of a newbie to Linux so I would be grateful for any help.

**Comment by jonas-schievink** [comment]
That's a bash script, you cannot use it with fish

**Comment by Stef16Robbe** [comment]
For anyone coming from Google, this worked perfectly for me: 

https://github.com/rust-lang/rustup/issues/478#issuecomment-330467741
