### ISSUE TITLE
Take doc(alias) into account when providing typo suggestions

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#83968]
Given the following code: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a5d74dbaa80fd7833c2b937fc94f58fa

```rust
fn main() {
    let x = [1, 2, 3].length();
}
```

The current output is:

```
error[E0599]: no method named `length` found for array `[{integer}; 3]` in the current scope
 --> src/main.rs:2:23
  |
2 |     let x = [1, 2, 3].length();
  |                       ^^^^^^ method not found in `[{integer}; 3]`
```

Ideally the output should look like:

```
error[E0599]: no method named `length` found for array `[{integer}; 3]` in the current scope
 --> src/main.rs:2:23
  |
2 |     let x = [1, 2, 3].length();
  |                       ^^^^^^ help: a function with an alias to `length` exists: `len`
```

Searching for `length` will already bring up `len` in the docs: https://doc.rust-lang.org/std/?search=length
It would be nice if the CLI errors had feature parity.

## Meta

`rustc --version`: 1.51.0

**Comment by Badel2** [comment]
> Searching for length will already bring up len in the docs: https://doc.rust-lang.org/std/?search=length

Not anymore?

**Comment by amab8901** [comment]
I think this issue should be closed. The solution has already been implemented. 

```
fn main() {
    let x = [1, 2, 3].length();
}
``` in playground (https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a5d74dbaa80fd7833c2b937fc94f58fa)
yields the following output:

```
Compiling playground v0.0.1 (/playground)
error[[E0599]](https://doc.rust-lang.org/stable/error-index.html#E0599): no method named `length` found for array `[{integer}; 3]` in the current scope
 --> src/main.rs:2:23
  |
2 |     let x = [1, 2, 3].length();
  |                       ^^^^^^ help: there is a method with a similar name: `len`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `playground` due to previous error
```

**Comment by jyn514** [comment]
@Badel2 @amab8901 this specific issue with `len` has been fixed, but the underlying problem that `doc(alias)` is ignored has not been fixed. https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=2aecfff005336e11136e0d063fd93ff8
```
error[E0425]: cannot find function `memcpy` in this scope
 --> src/main.rs:5:5
  |
5 |     memcpy(&dst, &src[2..]);
  |     ^^^^^^ not found in this scope
  |
help: consider importing one of these items
  |
1 | use libc::memcpy;
  |
1 | use openssl_sys::memcpy;
  |

error[E0599]: no method named `memcpy` found for array `[{integer}; 2]` in the current scope
 --> src/main.rs:6:9
  |
6 |     dst.memcpy(&src[2..]);
  |         ^^^^^^ method not found in `[{integer}; 2]`
```

**Comment by jyn514** [comment]
Mentoring instructions: change https://github.com/rust-lang/rust/blob/9644684dec97fb5353c1911dc3ca616a76fc977e/compiler/rustc_hir_typeck/src/method/probe.rs#L1923-L1938 to also consider `doc(alias)`, not just the names themselves.

**Comment by sulami** [comment]
This looks doable.

@rustbot claim
