### ISSUE TITLE
Missing f32/f64 euclidean remainder with integral divisor

### ISSUE THREAD

**Issue by mqudsi** [rust-lang/rust#83973]
I was writing some machine learning code and found that I was severely bottlenecked by some of the limitations of the available floating point operations in the rust standard library. In particular, rust currently only affords a euclidean remainder operation where both the dividend and the divisor are floating point values, however it is often the case that one has a floating point dividend but an integral divisor, the result of which can be calculated significantly faster and without using the floating point registers.

I believe the following function is equivalent to `f64::rem_euclid()` for normal `f32`/`f64` values *where the truncated value of `self` can fit in an i64 value*:

```rust
#[inline]
fn rem_i64(&self, divisor: i64) -> f64 {
    let x = *self as i64;
    if self.is_sign_positive() {
        (x % divisor) as f64 + self.fract()
    } else {
        (x % divisor + divisor.abs()) as f64 + self.fract()
    }
}
```

The compiler [optimizes the branch into a conditional move](https://godbolt.org/z/fM1GjjhMn). It can also be done explicitly via the one-liner:
`(x % divisor + if self.is_sign_positive() { 0 } else { 1 } * divisor.abs()) as f64 + self.fract()`.

Without any parallelism increasing the contention for the limited floating point registers, `rem_i64` is approximately 35x faster than the default `rem_euclid()` calculation, so it's a very meaningful gain. The screenshots below show the result of a criterion benchmark comparing the calculation of `rem_i64()` to `rem_euclid()` on (identical) arrays of 2048 pre-generated random floating point values modulo a fixed integral value (360) on an AMD 1950X (similar results were observed on a Haswell Xeon):

![image](https://user-images.githubusercontent.com/606923/113900569-91fa0380-9793-11eb-9dc0-40ea5972ba7a.png)
![image](https://user-images.githubusercontent.com/606923/113900591-99b9a800-9793-11eb-834f-5b01477838bb.png)

I *would* suggest having the compiler convert `f64::rem_euclid(foo, xxx.0)` to the above, but that is only possible if you can guarantee that `foo` is less than or equal to `i64::MAX`. It's probably still a win even if that requires a runtime conditional/branch (except in case of const operations) but it would obviously be desirable to explicitly opt into an i64 modulo operation and bypass that check for anyone that's saturating their processor's floating point capabilities, so there would have to be a separate method even if `f64::rem_euclid()` sometimes did also take the fast path depending on the values of `self` and `divisor`.

Sidenote: I'm not sure if directly composing an IEEE754 value from the integral and fractional components would be any faster than casting the integral value to an `f64` and adding the fractional component afterwards. If so, then possibly we need an `f64::from_parts(integral, fractional)` method?

---

Just for posterity/reference, this is what the same benchmark shows when using an equivalent `rem_i128()` method, in case you *did* want to add a conditional fast path to the existing `rem_euclid()` routine for values of `self` that were greater than `i64::MAX` but less than `i128::MAX`:

![image](https://user-images.githubusercontent.com/606923/113902083-23b64080-9795-11eb-8dd3-6602f4fad818.png)

**Comment by workingjubilee** [comment]
This would be easier to study further if the complete test code you used was available. However I do not think that the `rem_i64` you provided is appropriate for `std` because of the harder-to-use precondition that whiffs on farther-out values.

**Comment by mqudsi** [comment]
fast_float.rs:
```rust
pub trait FastFloat {
    fn rem_i32(&self, divisor: i32) -> f64;
    fn rem_i64(&self, divisor: i64) -> f64;
    fn rem_i128(&self, divisor: i128) -> f64;
}

impl FastFloat for f64 {
    #[inline]
    fn rem_i32(&self, divisor: i32) -> f64 {
        let x = *self as i32;
        if self.is_sign_positive() {
            // eprintln!("{} % {} = {}", x, divisor, x % divisor);
            (x % divisor) as f64 + self.fract()
        } else {
            // eprintln!("{} % {} = {}", x, divisor, x % divisor);
            (x % divisor + divisor.abs()) as f64 + self.fract()
        }
    }

    #[inline]
    fn rem_i64(&self, divisor: i64) -> f64 {
        let x = *self as i64;
        if self.is_sign_positive() {
            // eprintln!("{} % {} = {}", x, divisor, x % divisor);
            (x % divisor) as f64 + self.fract()
        } else {
            // eprintln!("{} % {} = {}", x, divisor, x % divisor);
            (x % divisor + divisor.abs()) as f64 + self.fract()
        }
    }

    #[inline]
    fn rem_i128(&self, divisor: i128) -> f64 {
        let x = *self as i128;
        if self.is_sign_positive() {
            // eprintln!("{} % {} = {}", x, divisor, x % divisor);
            (x % divisor) as f64 + self.fract()
        } else {
            // eprintln!("{} % {} = {}", x, divisor, x % divisor);
            (x % divisor + divisor.abs()) as f64 + self.fract()
        }
    }
}

#[test]
fn cmp_rem_i32() {
    let x: f64 = 47.76;
    assert_eq!(x.rem_euclid(16.0), x.rem_i32(16));
}

#[test]
fn cmp_rem_i32_neg() {
    let x: f64 = -47.76;
    assert_eq!(x.rem_euclid(16.0), x.rem_i32(16));
}
```

math.rs:

```rust
#![feature(test)]

use criterion::*;
use rand::prelude::*;

include!("../src/fast_float.rs");

fn mod360_u32(vals: &[f64]) -> () {
    #[inline(always)]
    fn mod360(x: f64) -> f64 {
        let ans = ((x as u32) % 360) as f64 + x.fract();
        core::hint::black_box(ans);
        ans
    }

    for x in vals {
        mod360(*x);
    }
}

fn mod360_i32(vals: &[f64]) -> () {
    #[inline(always)]
    fn mod360(x: f64) -> f64 {
        // let ans = (x as i32).rem_euclid(360) as f64 + x.fract();
        let ans = x.rem_i32(360);
        core::hint::black_box(ans);
        ans
    }

    for x in vals {
        mod360(*x);
    }
}

fn mod360_i64(vals: &[f64]) -> () {
    #[inline(always)]
    fn mod360(x: f64) -> f64 {
        // let ans = (x as i32).rem_euclid(360) as f64 + x.fract();
        let ans = x.rem_i64(360);
        core::hint::black_box(ans);
        ans
    }

    for x in vals {
        mod360(*x);
    }
}

fn mod360_i128(vals: &[f64]) -> () {
    #[inline(always)]
    fn mod360(x: f64) -> f64 {
        // let ans = (x as i32).rem_euclid(360) as f64 + x.fract();
        let ans = x.rem_i128(360);
        core::hint::black_box(ans);
        ans
    }

    for x in vals {
        mod360(*x);
    }
}

fn mod360_f64(vals: &[f64]) -> () {
    fn mod360(x: f64) -> f64 {
        let ans = x % 360.0;
        core::hint::black_box(ans);
        ans
    }

    for x in vals {
        mod360(*x);
    }
}

fn gen_f64(rng: &mut ThreadRng) -> f64 {
    const MIN: i64 = u32::MIN as i64 * 1000;
    const MAX: i64 = u32::MAX as i64 * 1000;
    const RANGE: u64 = (MAX - MIN) as u64;

    let rand = rng.gen_range(0, RANGE);
    // Convert back into the expected range
    let rand = MIN + (rand as i64);
    // Convert from thousands of a degree to float
    rand as f64 / 1000.0
}

const COUNT: usize = 2048;
fn bench_mod360(c: &mut Criterion) {
    let mut group = c.benchmark_group("mod360");
    let mut rng = rand::thread_rng();
    let mut inputs = Vec::with_capacity(COUNT);
    for _ in 0..COUNT {
        inputs.push(gen_f64(&mut rng));
    }

    group.bench_with_input(
        BenchmarkId::new("mod360 via u32", "2048 rand"),
        &inputs,
        |b, vals| {
            b.iter(|| mod360_u32(&vals));
        },
    );
    group.bench_with_input(
        BenchmarkId::new("mod360 f64", "2048 rand"),
        &inputs,
        |b, vals| {
            b.iter(|| mod360_f64(&vals));
        },
    );
    group.bench_with_input(
        BenchmarkId::new("mod360 via i32", "2048 rand"),
        &inputs,
        |b, vals| {
            b.iter(|| mod360_i32(&vals));
        },
    );
    group.bench_with_input(
        BenchmarkId::new("mod360 via i64", "2048 rand"),
        &inputs,
        |b, vals| {
            b.iter(|| mod360_i64(&vals));
        },
    );
    group.bench_with_input(
        BenchmarkId::new("mod360 via i128", "2048 rand"),
        &inputs,
        |b, vals| {
            b.iter(|| mod360_i128(&vals));
        },
    );
}

criterion_group!(benches, bench_mod360);
criterion_main!(benches);
```

**Comment by Dylan-DPC** [comment]
Closing this as it's niche enough that probably better for a crate
