### ISSUE TITLE
RELEASE.md does not mention the change to allow adding docs to reexported items

### ISSUE THREAD

**Issue by rodrimati1992** [rust-lang/rust#84007]
At some point between Rust 1.34.0 and 1.39.0, the ability to add documentation to reexported items was added, but I can't find it mentioned in either [the RELEASE notes](https://github.com/rust-lang/rust/blob/master/RELEASES.md) or the rust-lang.org blog posts.

Maybe this should be mentioned in the RELEASE notes for the version that added that feature?

I have a `foo` crate that I use to test stuff, and used `cargo +1.39.0 doc` to document this:
```rust
/// Ooooh, ghost!
pub use std::marker::PhantomData;
```

![image](https://user-images.githubusercontent.com/18036327/114076660-4754b600-987d-11eb-8f2f-333dd65893e5.png)

**Comment by jyn514** [comment]
This was changed in 1.38 (coincidentally also the release rust-std spiked from a 61.2 MB to 173.3 MB download).

@rodrimati1992 are you interested in making a PR?

**Comment by rodrimati1992** [comment]
@jyn514 Sure, what are PRs that made this possible?

**Comment by jyn514** [comment]
Oh I have no idea :laughing: I found it by bisecting.

**Comment by rodrimati1992** [comment]
Looks like #63048 is it
