### ISSUE TITLE
Wide characters in rustdoc: Fall-back to default CJK serif font on Windows is ugly

### ISSUE THREAD

**Issue by konan8205** [rust-lang/rust#84035]
In Windows, browsers like Chrome and Firefox use legacy fonts as default serif font to render.
rustdoc uses its custom serif fonts, but these do not support CJK glyph, so the browser renders CJK characters as default one.

The problem is that **the default serif font in Windows is so ugly and not clear**.
The default sans-serif font looks just ok.

Take a look at this screenshot after matching the pixels on the monitor.

**Why don't we just use sans-serif font for rustdoc?** Or, we can use sans-serif fonts that look like serif font.

With Windows default serif font (`batang.ttc`):
![Screenshot_2021-04-09 xingapi - Rust](https://user-images.githubusercontent.com/11029378/114196861-ba991d80-998c-11eb-9d1c-2beab6838a1e.png)

With Noto Sans font (not serif):
![Screenshot_2021-04-09 xingapi - Rust(2)](https://user-images.githubusercontent.com/11029378/114197015-e74d3500-998c-11eb-8917-f33278acbc3c.png)

**Comment by konan8205** [comment]
I'm using Windows 10 20H2, Firefox 87.0, with clean installation.

**Comment by konan8205** [comment]
label would be `A-doc`, but I cannot add it.

**Comment by konan8205** [comment]
The label would be `T-rustdoc`, but I cannot add it.

**Comment by workingjubilee** [comment]
> In Windows, browsers like Chrome and Firefox use legacy fonts as default serif font to render.
> rustdoc uses its custom serif fonts, but these do not support CJK glyph, so the browser renders CJK characters as default one.
> 
> The problem is that **the default serif font in Windows is so ugly and not clear**.
> The default sans-serif font looks just ok.
> 
> Take a look at this screenshot after matching the pixels on the monitor.
> 
> **Why don't we just use sans-serif font for rustdoc?** Or, we can use sans-serif fonts that look like serif font.

Huh. I have a recently installed Windows, and on both Firefox and Edge, I see:
![image](https://user-images.githubusercontent.com/46493976/114226954-2e094380-9929-11eb-8b65-7d0cd94c5451.png)

This looks much more similar to your second image. I wonder if #83156 or #82315 affected this? Or maybe it is because I do not have `batang.ttc` installed? Windows says the only Korean font I have is "Malgun Gothic". Having a good CJK default is ideal, so I am very interested in finding out exactly what is going on here.

**Comment by konan8205** [comment]
Legacy fonts like `batang.tcc` maybe installed on Korean Windows.

**Comment by konan8205** [comment]
"Malgun Gothic" is default non-legacy sans-serif font, so your browser maybe render that font instead of `batang.tcc`.

**Comment by workingjubilee** [comment]
Oh I see, that makes sense. So because it can't find a Korean serif font, it might have used a Korean sans serif font.
Checking... yep, Firefox says that it is using Malgun Gothic instead on https://docs.rs/xingapi/0.2.6/xingapi/, and obviously "have no meh-looking Korean serif fonts" is not really a reasonable expectation.
![image](https://user-images.githubusercontent.com/46493976/114229355-8ee64b00-992c-11eb-8477-be6a2899fbb7.png)

**Comment by konan8205** [comment]
![화면 캡처 2021-04-10 042344](https://user-images.githubusercontent.com/11029378/114230818-918c8300-99b4-11eb-92dd-5d0e19e8f2c8.png)
![화면 캡처 2021-04-10 042738](https://user-images.githubusercontent.com/11029378/114231233-1f686e00-99b5-11eb-9799-2422267df6ee.png)

**Comment by konan8205** [comment]
BTW, user-defined custom theme can solve this issue for crate-level. Pass `--extend-css` argument to rustdoc with custom css.

For example,
```css
@import url("https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300&display=swap");

body {
  font-family: "Noto Sans KR", sans-serif;
  line-height: 1.5;
}

pre.rust.rust-example-rendered {
  line-height: 1.4;
}
```

**Comment by jsha** [comment]
Would it work to add [Noto Sans CJK](https://www.google.com/get/noto/help/cjk/) as a custom font-face, and then include it in the fallback list, like:

```
body {
	font: 16px/1.4 "Source Serif 4", "Noto Sans CJK", serif;
	...
}
```

**Comment by konan8205** [comment]
@jsha Noto sans fonts that support CJK exist only for OpenType. Also its size is too big ;)

So we need to provide webfonts for each language. For example, Noto Sans HK, JP, KR, SC, TC...

**Comment by workingjubilee** [comment]
Noto Sans is quite adequate on a local installation, but that is indeed a fair amount of MB to transfer.

My understanding is that most docs in KR are going to be almost 100% using Hangul characters and very rarely if ever use characters from the rest of the CJK character set, is that correct? There would most certainly be a huge difference between that and a font that loads Japanese characters, which I would expect to cover 2000~3000 kanji, and the SC or TC fonts which would have to cover as many as 5000 hanzi.

**Comment by konan8205** [comment]
@workingjubilee Yes, norwadays chinese characters are rarely used in korean. I had never seen chinese characters in software docs so they are not necessary for rustdoc.

**Comment by konan8205** [comment]
> 
> 
> @jsha Noto sans fonts that support CJK exist only for OpenType. Also its size is too big ;) (20MB)
> 
> So we should provide webfonts for each language instead of providing a CJK OpenType font.
> For example, Noto Sans HK, JP, KR, SC, TC...

This does not work on docs.rs. Maybe for security reason?

`Cargo.toml`:
```toml
[package.metadata.docs.rs]
rustdoc-args = ["--extend-css=theme.css"]
```


`theme.css`:
```
@import url("https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap");

body {
  font-family: "Noto Sans KR", sans-serif;
  line-height: 1.5;
}

pre.rust.rust-example-rendered {
  line-height: 1.4;
}
```

**Comment by konan8205** [comment]
> 
> 
> BTW, user-defined custom theme can solve this issue for crate-level. Pass `--extend-css` argument to rustdoc with custom css.
> 
> For example,
> 
> ```css
> @import url("https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300&display=swap");
> 
> body {
>   font-family: "Noto Sans KR", sans-serif;
>   line-height: 1.5;
> }
> 
> pre.rust.rust-example-rendered {
>   line-height: 1.4;
> }
> ```

This does not work on docs.rs. Maybe for security reason?

`Cargo.toml`:
```toml
[package]
include = ["/src/**/*.rs", "/theme.css"]

[package.metadata.docs.rs]
rustdoc-args = ["--extend-css=theme.css"]
```
