### ISSUE TITLE
rustdoc: Use CSS to "merge" sequential inline code spans

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#84043]
This is essentially an issue to track https://github.com/rust-lang/rust/pull/80733#issuecomment-770297395.

I seem to recall an issue being opened a while ago about this (maybe by
@Nemo157?), but I can't find it, so I'm opening a new one.

**Comment by Nemo157** [comment]
Probably https://github.com/rust-lang/rust/issues/62867

**Comment by camelid** [comment]
Ah, that's it! Thanks :)
