### ISSUE TITLE
[Invalid accepted] E0568 can be bypassed by `where Self`

### ISSUE THREAD

**Issue by codehz** [rust-lang/rust#84075]
I tried this code:

```rust
#![feature(auto_traits)]

auto trait CanCopy where Self: Copy {}
```

I expected to see this happen: got E0568 because the unstable book say supertraits for auto trait are unsound

Instead, this happened: Compiler accepted those code

Playground link:
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=57126ad5d71bd5bbaa913416b70fae67

### Meta

`rustc --version --verbose`:
```
1.53.0-nightly

(2021-04-09 dae9d6ac3e9a8fb389cf)
(rust playground)
```

nightly feature tracking issue: #13231

**Comment by nbdd0121** [comment]
A slight tweak with the example in #29859, this is indeed unsound.
```rust
#![feature(auto_traits)]

auto trait Magic where Self: Copy {}
impl<T: Magic> Magic for T {}

fn copy<T: Magic>(x: T) -> (T, T) { (x, x) }

#[derive(Debug)]
struct NoClone;

fn main() {
    let (a, b) = copy(NoClone);
    println!("{:?} {:?}", a, b);
}
```

This compiles while it shouldn't.

@rustbot label: +I-unsound 💥 +requires-nightly

**Comment by apiraino** [comment]
Assigning priority as discussed as part of the [Prioritization Working Group procedure](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2384075.20.5BInvalid.20accepted.5D.20E0568.20can.20be.20bypassed.20by.20.60where.20S.E2.80.A6) and removing `I-prioritize`.

@rustbot label -I-prioritize +P-medium
