### ISSUE TITLE
SIGBUS has to be sent twice before the rust runtime exits

### ISSUE THREAD

**Issue by silence-coding** [rust-lang/rust#84118]
Why Does the Rust Not Occur When the SIGBUS Is Killed Once?

**Comment by jyn514** [comment]
@silence-coding I'm not sure what you're trying to say. Could you post more info about the problem you're running into?

**Comment by silence-coding** [comment]
I tried to generate a coredump file, but have to execute twice `kill SIGBUS pid ` to make the process core. My question is why the coredump file is not generated after the kill is performed.

**Comment by jyn514** [comment]
It looks like the standard library installs a signal handler:
```
(gdb) run
Starting program: /home/joshua/.local/lib/cargo/target/debug/hello-world 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Program received signal SIGBUS, Bus error.
0x00007ffff7e3e334 in __GI___clock_nanosleep (clock_id=<optimized out>, 
    clock_id@entry=0, flags=flags@entry=0, req=0x7fffffffdec0, rem=0x7fffffffdec0)
    at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:78
78	../sysdeps/unix/sysv/linux/clock_nanosleep.c: No such file or directory.
(gdb) step
std::sys::unix::stack_overflow::imp::signal_handler ()
    at library/std/src/sys/unix/stack_overflow.rs:93
93	library/std/src/sys/unix/stack_overflow.rs: No such file or directory.
```
https://github.com/rust-lang/rust/blob/6df26f897cffb2d86880544bb451c6b5f8509b2d/library/std/src/sys/unix/stack_overflow.rs#L93
I think it needs to re-raise the same signal it receives after unregistering itself as the signal handler.

@alexcrichton you were the author of https://github.com/rust-lang/rust/pull/27338 - does that sound about right to you?

**Comment by alexcrichton** [comment]
Well https://github.com/rust-lang/rust/pull/27338 is 6+ years old so I only remember but so much. SIGBUS IIRC needs to be installed to catch some out-of-stack conditions at least at the time (it may no longer be the case). We assume SIGBUS signals are generated in-process so by unregistering the signal handler and returning the expectation is that the process will exit immediately.

**Comment by silence-coding** [comment]
Is there a follow-up plan for this issue?

**Comment by Amanieu** [comment]
For a normal SIGBUS there is no need to re-raise the signal since simply returning from the signal handler will cause the instruction that triggered the signal to execute again and re-trigger the signal.

This only happens because you are sending an "artificial" SIGBUS using kill, which is not caused by an instruction. I don't think this is something we need to support.

As a workaround you can use a different signal that generates a core dump like SIGABRT.
