### ISSUE TITLE
--remap-path-prefix doesn't work in debug mode?

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#84125]
I tried the following code:

```
$ cargo new hello-world
$ cd hello-world
```
In release mode, `--remap-path-prefix` works correctly:
```
$ RUSTFLAGS="--remap-path-prefix=$(realpath .)=src --remap-path-prefix=$CARGO_HOME=cargo-home --remap-path-prefix=$RUSTUP_HOME=rustup-home" cargo run --release -q
Hello, world!
$ strings target/release/hello-world | grep joshua | wc -l
0
```

but the same thing without --release (and without incremental) does not:
```
$ CARGO_INCREMENTAL=0 RUSTFLAGS="--remap-path-prefix=$(realpath .)=src' --remap-path-prefix=$CARGO_HOME=cargo-home --remap-path-prefix=$RUSTUP_HOME=rustup-home" cargo run
Hello, world!
$ strings target/debug/hello-world | grep joshua | wc -l
8
```

Note this is unrelated to https://github.com/rust-lang/rust/issues/66955 because incremental is disabled.

_Originally posted by @jyn514 in https://github.com/rust-lang/rust/issues/75263#issuecomment-817305060_

**Comment by nagisa** [comment]
Do you have the `rust-src` component installed?

**Comment by jyn514** [comment]
Yes I do, and the issue only shows up with `-C debuginfo=2`. Thanks, this is a duplicate of https://github.com/rust-lang/rust/issues/73167 then.
