### ISSUE TITLE
disallow `|` from the follow-set of `pat2021`

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#84138]
In Edition 2021, the following should error:

```rust
macro_rules! foo {
    ($x:pat | $y:pat) => { }
}

fn main() { }
```

for the same reason that the following already errors:

```rust
macro_rules! foo {
    ($x:expr | $y:expr) => { }
}

fn main() { }
```

cc @rust-lang/project-edition-2021

**Comment by nikomatsakis** [comment]
@hi-rustin I was wondering if you were interested in fixing this as a follow-up to https://github.com/rust-lang/rust/pull/83468 -- I don't think you included it in that PR, right?

**Comment by hi-rustin** [comment]
I think the problem is here: https://github.com/rust-lang/rust/blob/36bcf4069717b9dff90270d13b53a3b130329960/compiler/rustc_expand/src/mbe/macro_rules.rs#L1098, but if we allow `|`, then 
```rust
macro_rules! foo {
    ($x:expr |) => { }
} 
```
will also be allowed. This does not seem right. But in the current function we can't yet tell what token comes next in `|`. Do you have any suggestions?

**Comment by nikomatsakis** [comment]
Actually, the code may already be correct? It appears that `|` is not allowed for `pat2021`, which is the goal:

https://github.com/rust-lang/rust/blob/36bcf4069717b9dff90270d13b53a3b130329960/compiler/rustc_expand/src/mbe/macro_rules.rs#L1119-L1129

[Note that `|` *is* allowed for `pat2015`.](https://github.com/rust-lang/rust/blob/36bcf4069717b9dff90270d13b53a3b130329960/compiler/rustc_expand/src/mbe/macro_rules.rs#L1112) Maybe we just need a test -- or maybe there already is one!

**Comment by hi-rustin** [comment]
> Actually, the code may already be correct? It appears that `|` is not allowed for `pat2021`, which is the goal:
> 
> https://github.com/rust-lang/rust/blob/36bcf4069717b9dff90270d13b53a3b130329960/compiler/rustc_expand/src/mbe/macro_rules.rs#L1119-L1129
> 
> [Note that `|` _is_ allowed for `pat2015`.](https://github.com/rust-lang/rust/blob/36bcf4069717b9dff90270d13b53a3b130329960/compiler/rustc_expand/src/mbe/macro_rules.rs#L1112) Maybe we just need a test -- or maybe there already is one!


Yes this part of the logic I have added, but my question is about `($x:expr | $y:expr) => { }`. I will add an additional test for pat2021.

**Comment by nikomatsakis** [comment]
@hi-rustin I expect `$x:expr | $y:expr` to be an error -- it is, right?

**Comment by hi-rustin** [comment]
> @hi-rustin I expect `$x:expr | $y:expr` to be an error -- it is, right?

Yes. I see what you mean. I misunderstood your description in the issue.
