### ISSUE TITLE
Opening a window from a test prevents libtest from outputting the test result

### ISSUE THREAD

**Issue by dzfranklin** [rust-lang/rust#84137]
**Problem**
If I spawn a window in a test I don't see the line `test tests::foo ... ok`. I know the test runs because it is included in the number of passed tests.

**Steps**
- Spawn a window in a test
- Run `cargo test`

Actual result:
```
running 2 tests
test tests::without_winit ... ok
   Doc-tests cargo_test_winit_repro

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

Expected result:
```
running 2 tests
test tests::with_winit ... ok
test tests::without_winit ... ok
   Doc-tests cargo_test_winit_repro

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

I've created [a minimal crate](https://github.com/danielzfranklin/cargo_test_winit_repro) that reproduces this issue.

**Notes**

Output of `cargo version`: `cargo 1.52.0-nightly (90691f2bf 2021-03-16)`
I've seen this result on Linux & Windows.

**Comment by ehuss** [comment]
Transferred to rust-lang/rust as this is an issue with libtest. libtest is the test harness which is responsible for running and reporting tests.

I don't have any specific ideas what could cause this.  I imagine `winit` may be interfering somehow with stdout, though it is hard to say.

**Comment by hyd-dev** [comment]
I think this is because [`EventLoop::run`](https://docs.rs/winit/0.24.0/winit/event_loop/struct.EventLoop.html#method.run) returns `!` -- it exits the process directly.

**Comment by danielzfranklin** [comment]
That makes sense. I had assumed the same thread printed all the output lines. I suppose this is a wontfix then?

**Comment by Enselic** [comment]
Triage: let's close as duplicate to https://github.com/rust-lang/rust/issues/67650 which is a about running each test in its own process, which in practice fixes this issue.
