### ISSUE TITLE
exploration: ignoring arrays in method dispatch

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#84133]
In #65819, we are considering adding an impl of `IntoIterator` for `[T; N]` for all `N`. However, this breaks existing code that relies on method dispatch:

```rust
let array = [true; 3];
for x in array.into_iter() {
    let _ = *x; // x is a reference
}
```

In this code, `array.into_iter()` winds up unsizing to a slice and hence resolving to `<&[bool] as IntoIterator>::into_iter` (and thus executing on refs to booleans). This issue describes a possible modification to older Rust editions that would allow us to add the impl without breaking existing code or compromising our edition guarantees.

**Comment by nikomatsakis** [comment]
### Proposal summary

Allow traits to be annotated with `#[rustc_skip_array_during_method_dispatch]`. This is a perma-unstable annotation and it has the effect that we will ignore a trait method match during method dispatch, but only if the receive is a `[T; N]` type. 

### To use in this case

```rust
#[rustc_skip_array_during_method_dispatch]
trait IntoIterator { ... }
```

Voila.

**Comment by cuviper** [comment]
Should that attribute have a parameter for the edition? Or just hard-code that it only applies before 2021?

I also wonder if it makes more sense on the `impl` for arrays, rather than the trait itself, but I don't know what that looks like from the perspective of method resolution.

**Comment by Mark-Simulacrum** [comment]
Notably we'll also need to decide what to read the edition from - I'd suggest the `.` but don't feel strongly.

**Comment by nikomatsakis** [comment]
### Mentoring instructions

We will modify 

https://github.com/rust-lang/rust/blob/5e73bd1040138f49200ce292eb109d3c8fd9a9cc/compiler/rustc_typeck/src/check/method/probe.rs#L1463

so that -- in older editions -- we look for this attribute on the trait. If that attribute is present, then we check the  `self_ty` variable and see whether it is a `[T; N]` array type. If so, we return `ProbeResult::NoMatch`.

As @Mark-Simulacrum notes, we need to decide what span to use to check the edition. I would propose we use the span from the method name. We can get the span from the `method_name` field, since it is an [`Ident`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_span/symbol/struct.Ident.html) and those contain a [span](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_span/symbol/struct.Ident.html#structfield.span). One can then invoke the [`edition`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_span/span_encoding/struct.Span.html#method.edition) method -- or just [`rust_2021`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_span/span_encoding/struct.Span.html#method.rust_2021).

**Comment by nikomatsakis** [comment]
@cuviper take a look at those brief mentoring instructions -- that may explain why I chose to put the attribute on the trait. In short, that's the easiest thing we have available to us.

**Comment by nikomatsakis** [comment]
I nominated this for @rust-lang/lang discussion to see how people react to the idea of an edition-related hack of this magnitude. It's worth noting that we could move this to a future-compatibility warning fairly easily and eventually remove it.

**Comment by cuviper** [comment]
OK -- I am interested in working on this, but should I wait for that discussion?

**Comment by nikomatsakis** [comment]
@cuviper I don't think that's necessary. My guess is that the main question would be whether this is something we eventually phase out and remove, or something we keep forever. Given how small the edits are, I don't see much of an argument for breaking folks immediately when warnings and a transition period are an option. 

I can see an argument for not wanting to keep this change permanently, there is a kind of trade-off there. For example, it is a bit confusing that I can write `<[T; N] as IntoIterator>::into_iter(foo)` but I can't write `foo.into_iter()`.

**Comment by joshtriplett** [comment]
This seems like a great solution to me.
I wouldn't want to keep this indefinitely; in a new edition, I think we do want into_iter to give an iterator over type T.

**Comment by nikomatsakis** [comment]
@joshtriplett note that Rust 2021 would work immediately. The question is only whether Rust 2018 *eventually* makes `foo.into_iter()` consider `[T; N]` as a possible self type or not.

**Comment by joshtriplett** [comment]
@nikomatsakis Ah, I see. I don't think there's enough value in making that transition in previous editions, and making people deal with the breakage. I think it'll be easier if we just make it a 2021 edition change.

**Comment by nikomatsakis** [comment]
@joshtriplett I'm inclined to agree

**Comment by cramertj** [comment]
I think this hack is a good idea, and I think we should do it in this case, but I am worried that we're using our power as language maintainers to sidestep an issue that regularly affects end-users of the language. That is, it is effectively a breaking change to add new methods or trait impls, even though our semantic versioning rules do not consider it to be one. crate maintainers may find that they break downstream users when adding new features that should otherwise not be semver-impacting. I'd love to see steps towards a solution, though admittedly I don't have a great idea what a solution might look like. `cfg(version/accessible)` is one good step that helps commonly used utility libraries like `futures-util` and `itertools` adapt to known overlap issues. For the case of preventing unknown overlap issues, I think there are fewer tools available.

**Comment by nikomatsakis** [comment]
@cramertj that sounds quite reasonable to me.

**Comment by Nichts** [comment]
@cramertj  Issues like this seem like the prime example why python has _from \_\_future\_\_ import_. Could allow us to opt into the new behavior now and make the transition into the next edition easier.

**Comment by nikomatsakis** [comment]
The PR is merged, I'm going to close this issue.
