### ISSUE TITLE
regression 1.52 - failed to resolve crate/module

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#84139]
Source: https://github.com/tchx84/tg-rs-upvote-bot/blob/9b725fd100028d6159380866c92bd1e53445f6fd/src/main.rs#L180

Log: https://crater-reports.s3.amazonaws.com/beta-1.52-1/beta-2021-03-27/gh/tchx84.tg-rs-upvote-bot/log.txt

Not sure what's causing this, but bson seems defined in that module - https://github.com/tchx84/tg-rs-upvote-bot/blob/9b725fd100028d6159380866c92bd1e53445f6fd/src/main.rs#L8

cc @petrochenkov 

a few more cases:

* https://crater-reports.s3.amazonaws.com/beta-1.52-1/beta-2021-03-27/gh/wotmshuaisi.Clipboard/log.txt

**Comment by petrochenkov** [comment]
This is an expected result of https://github.com/rust-lang/rust/pull/80763.
I sent PRs to affected crates, but not all of them were merged.

**Comment by Mark-Simulacrum** [comment]
OK, sounds good. Tagging relnotes and removing prioritize; we'll mention this in release notes but no further work likely.

**Comment by jyn514** [comment]
The error message seems not great - shouldn't it error when you import `bson`, not when you use it?

**Comment by petrochenkov** [comment]
IIRC, there are two `bson`s - one in type namespace (this is the private crate item which we are no longer importing), and another public one in value or macro namespace - that's why the import itself doesn't fail.

**Comment by pietroalbini** [comment]
This regression will unfortunately be included in 1.52.0 stable. Updating the labels.

**Comment by Mark-Simulacrum** [comment]
Closing as "expected breakage"; I don't think we plan to take further action here.
