### ISSUE TITLE
regression 1.52 - proc-macro-hack panic

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#84136]
proc-macro-hack is panicking[1] on beta 1.52 in some cases where it wasn't before:

* [base](https://crater-reports.s3.amazonaws.com/beta-1.52-1/1.51.0/gh/FIL1994.expense-tracker/log.txt) vs. [beta](https://crater-reports.s3.amazonaws.com/beta-1.52-1/beta-2021-03-27/gh/FIL1994.expense-tracker/log.txt)
* [base](https://crater-reports.s3.amazonaws.com/beta-1.52-1/1.51.0/gh/FIL1994.tower-web-app/log.txt) vs. [beta](https://crater-reports.s3.amazonaws.com/beta-1.52-1/beta-2021-03-27/gh/FIL1994.tower-web-app/log.txt)

My guess is this might have something to do with the usize-suffixed tuple indices, but I'm not sure. It seems to be new behavior on beta; I don't know whether this is caused by any of the recently landed macro-related patches, but it seems not impossible.

[1]: This is my belief, as it's the only repository in the dependency tree to contain the 'source.starts_with(prefix)' string in its source code (based on cargo vendor).

cc @Aaron1011 @petrochenkov @dtolnay 

edit - some more cases:

* https://crater-reports.s3.amazonaws.com/beta-1.52-1/beta-2021-03-27/gh/bryanburgers.connectbot/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.52-1/beta-2021-03-27/gh/guillepb10.performance_test_rust/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.52-1/beta-2021-03-27/gh/marekm1844.user-tower/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.52-1/beta-2021-03-27/gh/mindriot101.gitlab-hook-deploy/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.52-1/beta-2021-03-27/gh/victorinno.tower_web_dummy_service/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.52-1/beta-2021-03-27/gh/vizitiuRoman.notifier-service/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.52-1/beta-2021-03-27/gh/vizitiuRoman.rust-notification-service/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.52-1/beta-2021-03-27/reg/tower-web-protobuf-0.1.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.52-1/beta-2021-03-27/reg/rustiful-0.1.0/log.txt

**Comment by Aaron1011** [comment]
It looks like the pretty-printing assumptions made by an older version of `proc-macro-back` have stopped holding. Running `cargo update -p proc-macro-hack` in one of the failing crates fixed the panic for me.

**Comment by Mark-Simulacrum** [comment]
This seems pretty widespread - I found at least 5-6 more repositories in crater, though not too many actual crates. Is there an easy way for us to continue having the same pretty printing? I know we don't generally guarantee stability there, and it looks like there's a pretty easy upgrade path, so if not that seems OK (but we'll want to mention it in release notes).

**Comment by dtolnay** [comment]
https://github.com/dtolnay/proc-macro-hack/commit/4df5a94a806cf21a0e478bf8f1cef7fb26192917 fixed the whitespace sensitivity for 0.4.3. I have not looked at the build logs but it sounds like the failures are things pinned to an old patch version of 0.4? If so, I would be inclined to close this.

**Comment by Mark-Simulacrum** [comment]
Yeah, things using 0.4.1 - 57 repositories is not small, and most of these are just tiny self-projects I suspect, so I agree that we can likely close if there's not a trivial fix (probably not, based on the scope of the breakage).

**Comment by petrochenkov** [comment]
I remember fixing this in the past by tweaking pretty-printing (https://github.com/rust-lang/rust/pull/63897), not sure what change caused pretty-printing to change again.

**Comment by apiraino** [comment]
Removing I-prioritize as these panics seems to be solved by upgrading the library (but in case it helps, let's assign a priority).

@rustbot label -I-prioritize

**Comment by pietroalbini** [comment]
This regression will unfortunately be included in 1.52.0 stable. Updating the labels.

**Comment by Mark-Simulacrum** [comment]
Closing as "expected breakage"; I don't think we plan to take further action here.
