### ISSUE TITLE
Compiling Rust on PPC Linux error building proc-macro2

### ISSUE THREAD

**Issue by mzryz** [rust-lang/rust#84142]
On Lubuntu 12 PPC
Kernel 3.2.0-126-powerpc-smp
gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3

Advice much appreciated.

```
Compiling proc-macro2 v1.0.24
error: could not compile `proc-macro2`

Caused by:
  process didn't exit successfully: `/home/me/rust/build/powerpc-unknown-linux-gnu/stage0/bin/rustc --crate-name build_script_build --edition=2018 /home/me/.cargo/registry/src/github.com-b420f105fcaca6de/proc-macro2-1.0.24/build.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="proc-macro"' -C metadata=6dced1cd75b14157 -C extra-filename=-6dced1cd75b14157 --out-dir /home/me/rust/build/bootstrap/debug/build/proc-macro2-6dced1cd75b14157 -L dependency=/home/me/rust/build/bootstrap/debug/deps --cap-lints allow -Cdebuginfo=2 -Wrust_2018_idioms -Wunused_lifetimes -Dwarnings` (signal: 4, SIGILL: illegal instruction)
failed to run: /home/me/rust/build/powerpc-unknown-linux-gnu/stage0/bin/cargo build --manifest-path /home/me/rust/src/bootstrap/Cargo.toml
Build completed unsuccessfully in 0:04:00 
```

**Comment by Aaron1011** [comment]
@mzryz: Can you provide a backtrace from the core dump (assuming one was generated)?

**Comment by mzryz** [comment]
> @mzryz: Can you provide a backtrace from the core dump (assuming one was generated)?

Hi Aaron, for some reason my system isn't providing a core dump. It's a sysv lubuntu. I made sure apport and gdb are installed and enabled. No core inside the build sir or in /proc/kernel etc. Not sure why.

**Comment by glaubitz** [comment]
Most likely the same as  #81334 (due to the SIGILL).

Also, you might want to update to a more modern Linux distribution for 32-bit PowerPC: https://cdimage.debian.org/cdimage/ports/snapshots/2021-04-17/

**Comment by glaubitz** [comment]
Regression was introduced by 0328e69287b083af4d5d4b49cfc9175e9c82c88e

See #81334

**Comment by mzryz** [comment]
closing issue as do not have the system anymore.

**Comment by glaubitz** [comment]
> closing issue as do not have the system anymore.

That's okay, the issue has been fixed in the meantime. https://github.com/rust-lang/rust/pull/85807 ;)
