### ISSUE TITLE
Dividing by NonZeroU64 does not optimize out check that the denominator != 0

### ISSUE THREAD

**Issue by redzic** [rust-lang/rust#84151]
`rustc 1.51` (and nightly) compiles this code:

```rust
use std::num::NonZeroU64;

pub fn foo(x: u64, y: NonZeroU64) -> u64 {
    x / y.get()
}
```

with this assembly output (compiler flags: `-C opt-level=3`):

```assembly
example::foo:
        test    rsi, rsi
        je      .LBB0_5
        mov     rax, rdi
        or      rax, rsi
        shr     rax, 32
        je      .LBB0_2
        mov     rax, rdi
        xor     edx, edx
        div     rsi
        ret
.LBB0_2:
        mov     eax, edi
        xor     edx, edx
        div     esi
        ret
.LBB0_5:
        sub     rsp, 8
        lea     rdi, [rip + str.0]
        lea     rdx, [rip + .L__unnamed_1]
        mov     esi, 25
        call    qword ptr [rip + core::panicking::panic@GOTPCREL]
        ud2

.L__unnamed_2:
        .ascii  "/app/example.rs"

.L__unnamed_1:
        .quad   .L__unnamed_2
        .asciz  "\017\000\000\000\000\000\000\000\004\000\000\000\005\000\000"

str.0:
        .ascii  "attempt to divide by zero"
```

This assembly is definitely sub optimal, as it checks for an invariant that is guaranteed to never exist, and theoretically it should remove the branch completely.

If you manually call `unreachable_unchecked()`, then the branch gets eliminated. Here's what that would look like:

```rust
use std::num::NonZeroU64;

pub fn bar(x: u64, y: NonZeroU64) -> u64 {
    if y.get() == 0 {
        unsafe { std::hint::unreachable_unchecked() }
    }

    x / y.get()
}
```

And here's the codegen (on rust 1.51 and nightly):
```assembly
example::bar:
        mov     rax, rdi
        mov     rcx, rdi
        or      rcx, rsi
        shr     rcx, 32
        je      .LBB0_1
        xor     edx, edx
        div     rsi
        ret
.LBB0_1:
        xor     edx, edx
        div     esi
        ret
```

This is really strange, because if you compile the exact same code, but pass in `-C target-cpu=znver2`, then the code gets optimized further into just this:

```assembly
example::bar:
        mov     rax, rdi
        xor     edx, edx
        div     rsi
        ret
```

This seems like a bug in LLVM itself. It doesn't make sense why it would compile the code into the most optimized version only if you pass in `-C target-cpu=znver2` (znver1 also seems to work), but not if you pass in for example `-C target-cpu=haswell` or just use the default x86 target. It's not like it's generating AVX2 code or something that isn't supported on Rust's default x86 target, it's just using very simple instructions that are basically universal.

Not only that, but it really seems like it's a regression in LLVM itself. If you compile `bar` on Rust 1.46, then even on the default x86 target it generates the 3 instruction version. However, any version after this seems to generate the other version with more instructions and conditional jumps.

And there's one more thing that seems to suggest it's an LLVM regression. `clang` also has this issue in the latest version (11.0.1), but not in version 10.0.1.

Consider the following C++ code:
```cpp
#include <cstdint>

std::uint64_t div(std::uint64_t x, std::uint64_t y) {
    return x / y;
}
```

On clang 11.0.1, you get the exact same codegen as `bar`, even down to the same odd behaviors of it sometimes optimizing further depending on the target CPU specified through `-march`. This issue doesn't exist on clang 10.0.1 though, as it optimizes correctly even on the default x86 target. `gcc` doesn't seem to have this issue, as it optimizes the same as the clang 3 instruction version for any target CPU.

**Comment by scottmcm** [comment]
This is generally true for all uses of `.get()`: https://github.com/rust-lang/rust/issues/49572

Note, BTW, that as of 1.51 it's possible to [divide by NonZeroU64 directly](https://doc.rust-lang.org/nightly/std/primitive.u64.html#impl-Div%3CNonZeroU64%3E):
```rust
use std::num::NonZeroU64;

pub fn foo(x: u64, y: NonZeroU64) -> u64 {
    x / y
}
```

As for the ASM difference for different targets, that appears to be the case for the `intrinsics::unchecked_div` version (which is what that `Div` uses internally) as well: https://rust.godbolt.org/z/P1qxoPbqG 

Which implies to me that it's very much intentional by LLVM, as it's the code that comes out of just a raw `udiv`.  Perhaps it's common enough that a *full* 64-bit division is particularly slow that checking to see whether it can be done as 32-bit instead is worth it -- but on something new (like znver2) it knows that the chip is fast enough at 64-bit divisions that it's not worth doing the extra check, and thus can just always use the 64-bit version.

**Comment by redzic** [comment]
That actually makes sense. I'm going to close this issue because of the ability to directly divide by a `NonZeroU64`, and the checking if it's worth it to use a full 64-bit div instruction on possibly older CPUs also makes sense.
