### ISSUE TITLE
Promote aarch64-unknown-freebsd to Tier 2

### ISSUE THREAD

**Issue by fundon** [rust-lang/rust#84181]
https://www.freebsd.org/releases/13.0R/announce/

> The 64-bit ARM architecture known as arm64 or AArch64 is promoted to Tier-1 status for FreeBSD 13.

**Comment by workingjubilee** [comment]
Our support for *BSDs in general is somewhat lacking: https://github.com/rust-lang/libc/issues?q=is%3Aissue+is%3Aopen+label%3AO-bsd

**Comment by workingjubilee** [comment]
An established process for promoting targets now exists, please file an MCP if you desire this:
https://doc.rust-lang.org/nightly/rustc/target-tier-policy.html
