### ISSUE TITLE
Support trailing commas in macros by default

### ISSUE THREAD

**Issue by dannykomo** [rust-lang/rust#84211]
When declaring a makro, I often do this mistake of typing a comma after the last argument, since this is my style of coding that is OK for any programming language I know. In regular rust code it is fine as well:
```rust
fn foo(
    first_parameter: FirstParameterType,
    second_parameter: SecondParameterType,
    third_parameter: ThirdParameterType,
) -> &[usize] {
   // DO SOMETHING
}
```
However in makros, it does not work:

```rust
macro_rules! foo {
    (
        $first_parameter: expr,
        $second_parameter: expr,
        $third_parameter: expr,
    ) => {
         // DO SOMETHING
    }
}
```
This decralaration is incorrect due to the comma after `$third_parameter: expr`.

I think that the best solution is to allow this comma, however at least the comment should be fixed since it points at the place the makro is used instead at the declaration and says: `missing tokens in macro arguments` which is missleading

**Comment by jhpratt** [comment]
If you would like to have an optional comma, you can use the `$(,)?` matcher. As written, the comma is required.

@rustbot labels -C-bug.

**Comment by ModProg** [comment]
> If you would like to have an optional comma, you can use the `$(,)?` matcher. As written, the comma is required.

While in the OP's case I would expect the comma to be required as it is explicitly written, there is a case where an "auto-optional-trailing-seperator" would make sense IMO and that is with repetitions `$(...),*` the current way to support it would be `$($(...),+ $(,)?)?` or, if you do not care about allowing just a comma without an actual repetition, `$(...),* $(,)?)`.

Maybe it would make sense to allow specifying a trailing comma for macros using `$(...),*` ? parsing should probably be non-greedy and only consume the trailing separator if it is not consumed by the following rules to be backward compatible and only add new "working" cases but not break existing usages.

I had a quick look here and in rfcs but didn't find any discussion concerning this, was there already something I didn't find?

**Comment by Dylan-DPC** [comment]
Closing this as there's already a way to do this and I'm not sure we can change this
