### ISSUE TITLE
Tracking Issue for const-initialized thread locals

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#84223]
Feature gate: `#![feature(thread_local_const_init)]`

This is a tracking issue for the `const`-initialization of thread locals in the standard library added in https://github.com/rust-lang/rust/pull/83416. 

### Public API

```rust
use std::cell::Cell;
std::thread_local!(static KEY: Cell<u32> = const { Cell::new(0) });

// ... same APIs as before with thread locals
```

The API here is intended to be exclusively within the syntax of the preexisting `thread_local!` macro. The initialization expression for thread local keys can now be surrounded with `const { ... }` to indicate that the value should be const-evaluated and initialized.

Note that this also supports the multi-definition form:

```rust
use std::cell::Cell;
std::thread_local! {
    static KEY1: Cell<u32> = const { Cell::new(0) };
    static KEY2: Cell<u32> = const { Cell::new(0) };
}
```

### Steps / History

- [x] Implementation: #83416
- [ ] Final commenting period (FCP)
- [ ] Stabilization PR

### Unresolved Questions

- Syntax bikeshed - is the use of what is likely to be a future-feature, `const` blocks, ok here? Are there other options for syntax?

**Comment by alexcrichton** [comment]
I've requested this be tagged `I-nominated` for discussion for stabilization, but I figured I'd want to paste some background here as well. My personal main motivation for this is optimizing the pieces of Wasmtime where a host calls into a WebAssembly module. Part of that is frobbing some TLS values as we enter into wasm, and this frobbing is actually marked `#[inline(never)]` for the poor cross-crate codegen that TLS has otherwise. This outlining plus  the extra checks for whether or not TLS is initialized is what I'm trying to optimize.

In benchmarks locally the call overhead of host->wasm decreases from 20ns to 18ns (10% reduction) with the usage of const-initialized-thread-locals (which are also `#[inline]`'d since they have good codegen). This isn't really gonna make or break anyone's day since it's a pretty small difference, but nevertheless I'd love to get it out of the way so I don't have to worry about it again.

Another data point I see linked here is that [rustc is using `const`-initialized thread locals](https://github.com/rust-lang/rust/pull/84833) for some [moderate gains across the board](https://perf.rust-lang.org/compare.html?start=e10cbc33c1fd2fcd446cab5cdcc57332d154721c&end=d001198a19b8608565f98c76c5700d69176acd3e). 

There was some [brief discussion on Zulip about the syntax](https://rust-lang.zulipchat.com/#narrow/stream/219381-t-libs/topic/Stabilizing.20.60thread_local_const_init.60.3F) when I originally asked to stabilize. One thing I'll clarify is that this doesn't literally use `const { .. }` blocks in the expanded code, the macro is simply recognizing it as input syntax. I believe one gotcha of this is that if you have `$e:expr` in a macro and in the future `$e` is something like `const { 1 }` I don't think that it will use the const-initialized version of `thread_local!` were you to do something like `thread_local!(static X: i32 = $e)` since I don't think that rustc splits apart tokens to match sub-patterns in a macro. This will, however, work for literal declarations like `thread_local!(static X: i32 = const { 1 });`

Overall the biggest thing to decide here I think is the syntax. One alternative is a whole new macro, but I think that it'd be ideal if we could keep it in one macro to not have to worry about multiple. Otherwise though I'm happy to implement whatever syntax.

**Comment by m-ou-se** [comment]
Discussed in the library api team meeting. We'd like @rust-lang/lang to sign off on this.

**Comment by nikomatsakis** [comment]
This seems like a fine thing to stabilize; however, just to be clear, is this feature any use without `const` blocks? I guess that one can still stabilize to other constants (e.g., simple integer values)?

**Comment by cramertj** [comment]
It seems a little funky to me to stabilize a syntax that, at a surface level, matches that of a pre-existing unstable feature (const blocks). Even though it may not require const blocks under the hood, in the long-term I think users would expect that the set of things allowed inside `thread_local!(static X: Y = const { <code here> };` would match the rules for what could be present in `static X: Y = const { ... };`.

That is, if we decided that some surface syntax or semantics should be different inside `const` blocks, I'd also want it to be different in these not-const-blocks. Are we confident that we'll be able to provide matching semantics in each of these contexts in the future? That is, that the not-const-block in `thread_local!` doesn't allow anything that a `const` block wouldn't allow?

**Comment by yaahc** [comment]
>     * If the set of expressions accepted as initial value for a static diverged from set that can appear in `const { ... }` this would be weird, but we consider this unlikely.

If this happened I think we could fix the inconsistency at an edition boundary the same way we did for `panic!`, so I don't think this is a particularly large risk.

**Comment by m-ou-se** [comment]
@rfcbot concern LocalKey type

A variable defined with `thread_local!{}` is of the type `LocalKey<T>`. I'm wondering if we should use a different type for `const`-initialized thread locals.

Right now, reusing the same type works fine, as it just a wrapped function pointer. But I can imagine that a thread local key without lazy initializer might have a different implementation or even api than the one with. (E.g. `THREAD_LOCAL.is_initialized()` or `THREAD_LOCAL.initialize_with(|| ..)`.)

**Comment by m-ou-se** [comment]
@rfcbot resolve LocalKey type

A `thread_local_const_init` or something like that would probably not only require the initialization expression to be const, but also forbid the type from needing Drop. If the type needs drop, it'll need to keep track of its initialization state anyway.

The only thing to note is that if we do ever add a `.is_initialized()` or anything similar to `LocalKey`, [the current optimization](https://github.com/rust-lang/rust/blob/d914f17ca71a33a89b2dc3436fca51b1a091559e/library/std/src/thread/local.rs#L189-L195) might no longer work, since it'll need to track the 'initialization' state even when it doesn't need drop.

**Comment by veber-alex** [comment]
If this is a pure performance optimization, can the macro just "do the right thing" without any user facing syntax?
It will require some compiler magic but maybe it's worth it in this case?
This way also avoids any breaking changes in the future as what is optimized and what isn't is internal.

**Comment by alexcrichton** [comment]
I've posted a stabilization PR for this at https://github.com/rust-lang/rust/pull/91355

**Comment by Darksonn** [comment]
This has had a stabilization PR merged, but the todo list still lists the stabilization PR as missing.

**Comment by ahicks92** [comment]
I'm also not able to find docs on this other than that the macro now lists these patterns in the declaration: https://doc.rust-lang.org/std/macro.thread_local.html

(that is nothing says "and by the way..." but maybe I'm missing it?)

Nor can i find anything in the release notes or via Google.  The only thing that seems to exist as to this being stable is that the PR merged a long time ago.  What's the actual status?  I haven't tried to use this yet on stable but presumably I can?

**Comment by Nilstrieb** [comment]
@ahicks92 you're right, I opened #110620

**Comment by ahicks92** [comment]
Cool!  thanks.  TLS doesn't come up super often but there was at least one case not that long ago where we were nightly for the attribute version of this in perf sensitive code.
