### ISSUE TITLE
Odd behaviour coming from macros

### ISSUE THREAD

**Issue by InnocentusLime** [rust-lang/rust#84259]
I tried this code:

```rust
struct T(i32);

#[macro_export]
macro_rules! test {
  ($array_type:ty => $($elem:expr),+ $(,)?) => {};
  ($($elem:expr),+) => {};
}

fn main() {
    test!(T(2));
}
```

I expected it to compile, since `T(2)` is obviously an expression.

Instead I received the following compiler error:

> error: expected type, found `2`

The compiler seems to forcefully parse the string with the first rule (although it is clearly inapplicable here), fails and terminates with an error.

What is more surprising is that the following code compiles just fine

```rust
struct T;

#[macro_export]
macro_rules! test {
  ($array_type:ty => $($elem:expr),+ $(,)?) => {};
  ($($elem:expr),+) => {};
}

fn main() {
    test!(T);
}
```

Even the right branch gets picked (the second one)!

Moreover, reordering the branches breaks the following example (which **compiles** if you swap the `test`'s arms back)

```rust
struct T(i32);

#[macro_export]
macro_rules! test {
  ($($elem:expr),+) => {};
  ($array_type:ty => $($elem:expr),+ $(,)?) => {};
}

fn main() {
    test!([&'static T; 2] => T(2));
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.51.0 (2fd73fabe 2021-03-23)
binary: rustc
commit-hash: 2fd73fabe469357a12c2c974c140f67e7cdd76d0
commit-date: 2021-03-23
host: x86_64-unknown-linux-gnu
release: 1.51.0
LLVM version: 11.0.1
```

Beta and nightly struggle with this code too.

**Comment by ehuss** [comment]
I believe this is working as intended (for now). Non-terminal metavariables are parsed as a whole, and if it fails, the whole macro is rejected. macro_rules does not support backtracking (see #42838 and some of the issues linked there).

**Comment by InnocentusLime** [comment]
It is quite upsetting... Some libs could benefit a lot from the backtracking feature,. `tinyvec` being one of them.

**Comment by InnocentusLime** [comment]
I, however, feel like it doesn't have much to do with backtracking. Because 'test!(T)` doesn't get rejected. Despite being more ambiguous than `T(2)`. 

Moreover `T(2)` **clearly** belongs to expression category! Why should the macro eagerly ignore the parentheses after `T`?

**Comment by SkiFire13** [comment]
> From the reference one can infer that types don't have any syntax like T(U)

That's not true, a `Type` can match a `PathIdentSegment` optionally followed by a `TypePathFn` which starts with parenthesis. In fact `Fn(T)` is a valid type.

**Comment by InnocentusLime** [comment]
Hm... Indeed... But why does it match if you declare

```
struct T;
```

And call `test!(T)`? As I said, it matches the type grammar too...

**Comment by ehuss** [comment]
`test!(T)` works because it successfully parses `T` as a type, and then the `=>` isn't found, so it moves on to the next arm.

It only fails when there is an error matching a *nonterminal* matching fragment.

**Comment by InnocentusLime** [comment]
So Rust refusing to try other branches if some terminal fragment is not satisfied is the intended behaviour and is **directly** related to backtracking (how?)? Is it going to get changed in the nearest future?

**Comment by ehuss** [comment]
I'm not aware of anyone working on it.  https://github.com/rust-lang/rust/pull/33840#issuecomment-224869252 discusses some of the complexity involved in solving it.

**Comment by InnocentusLime** [comment]
Yeah... Seems like the feature isn't going to be added at least for backtracking and trying other macro arms... Guess I'll look for other ways to solve the issue in the `tinyvec`
