### ISSUE TITLE
Test Windows configuration with Valgrind using Wine, or Winelib

### ISSUE THREAD

**Issue by sstewartgallus** [rust-lang/rust#8426]
Valgrind does not run under Windows so there are two options for testing the Windows configuration of Rust with Valgrind: on a Valgrind supported platform; cross-compile to Windows, and then run the build using Wine, or compile under the Windows configuration using Winelib.

I'm not really sure which approach would be easiest. I have struggled for a while with both approaches. Personally, I think it is most logical to compile using Winelib though.

I would really appreciate if some who are more knowledgeable about the build system like @graydon, or @pnkfelix could give me some help with this.

Also, I do not know how best to expose these option to configuration.

**Comment by steveklabnik** [comment]
@retep998 what do you think here? What's the current state of this, and shouldn't we be using some sort of windows-native tooling rather than valgrind?

**Comment by retep998** [comment]
What Windows native tooling? The only thing I know of is LLVM's sanitizers.

**Comment by steveklabnik** [comment]
> The only thing I know of is LLVM's sanitizers.

Question answered :)

**Comment by alexcrichton** [comment]
This is a pretty ancient bug, and now that we have a ton of Windows automation set up, I doubt we're going to do this. We barely even run valgrind on Linux, much less OSX, much less Windows, so I don't think that this is particularly pressing.
