### ISSUE TITLE
The calcs with u32 are generating wrong results! 

### ISSUE THREAD

**Issue by arthurguedes375** [rust-lang/rust#84263]
I tried this code:

```rust
println!("{}", 125 * (40 / 100));
println!("{}", 125 * (20 / 100));

```

I expected to see this happen: The output to be right.

Instead, this happened: It Returns 0 every time.

### Meta
`rustc --version --verbose`:
```
rustc 1.50.0 (cb75ad5db 2021-02-10)
binary: rustc
commit-hash: cb75ad5db02783e8b0222fee363c5f63f7e2cf5b
commit-date: 2021-02-10
host: x86_64-unknown-linux-gnu
release: 1.50.0
```

###  I ran with the command: ``` RUST_BACKTRACE=1 cargo build --release ```

<details><summary></summary>
<p>

```
Compiling abc v0.1.0 (/var/rust/games/abc)
    Finished release [optimized] target(s) in 0.19s
```

</p>
</details>

**Comment by jonas-schievink** [comment]
`40 / 100` is zero, because that performs integer division, so the results are correct
