### ISSUE TITLE
Aggressive loop unrolling causes codegen to stall

### ISSUE THREAD

**Issue by mrene** [rust-lang/rust#84276]
I stumbled upon this while benchmarking some code with criterion, by increasing the size of the array, rustc will take exponentially more time to complete.

This seems triggered by their `black_box` function which prevents constants from being propagated into the benchmark code.

In this example, the generated llvm-ir shows the loop as being completely unrolled, so that the number of instructions grows linearly with the number of elements in the array (on my machine, a size of 5120 takes 1 second to compile, with 51200 takes 74 seconds).

Here is the number of lines in the generated llvm ir:
with 512: 
2212 target/release/deps/willitstall-735ef376f151c6b8.ll
with 5120: 
15724 target/release/deps/willitstall-735ef376f151c6b8.ll
with 51200: 
153964 target/release/deps/willitstall-735ef376f151c6b8.ll

### Code

```Rust
/// This is the black_box function from criterion
/// https://docs.rs/criterion/0.3.4/src/criterion/lib.rs.html#174-180
pub fn black_box<T>(dummy: T) -> T {
    unsafe {
        let ret = std::ptr::read_volatile(&dummy);
        std::mem::forget(dummy);
        ret
    }
}

fn main() {
    let x = black_box([1f32; 51200]);
    let dist: f32 = x.iter().zip(x.iter()).map(|(&xe, &ye)| xe * ye).sum();
    dbg!(dist);
}
```

### Investigation
Recording the execution with `perf` shows the time is mostly spent inside `llvm::X86TargetLowering::PerformDAGCombine` and `(anonymous namespace)::DAGCombiner::visitSTORE` 

Running (this example) with `-Z time-passes` yields:
```
time:   0.004; rss:  130MB ->  130MB (   +1MB)  serialize_dep_graph
time:   0.002; rss:  130MB ->   93MB (  -38MB)  free_global_ctxt
time:  74.582; rss:  117MB ->  192MB (  +74MB)  LLVM_passes(crate)
time:   0.000; rss:  191MB ->  191MB (   +0MB)  join_worker_thread
time:   0.002; rss:  191MB ->  162MB (  -30MB)  copy_all_cgu_workproducts_to_incr_comp_cache_dir
time:  74.561; rss:   93MB ->  160MB (  +67MB)  finish_ongoing_codegen
time:   0.000; rss:  155MB ->  155MB (   -1MB)  llvm_dump_timing_file
time:   0.000; rss:  155MB ->  153MB (   -1MB)  serialize_work_products
time:   0.000; rss:  153MB ->  147MB (   -6MB)  incr_comp_finalize_session_directory
time:   0.000; rss:  146MB ->  143MB (   -3MB)  link_binary_check_files_are_writeable
time:   0.155; rss:  133MB ->   85MB (  -48MB)  run_linker
time:   0.001; rss:   85MB ->   85MB (   +0MB)  link_binary_remove_temps
time:   0.157; rss:  146MB ->   85MB (  -61MB)  link_binary
time:   0.157; rss:  146MB ->   85MB (  -61MB)  link_crate
time:  74.719; rss:   93MB ->   85MB (   -8MB)  link
time:  74.822; rss:   35MB ->   70MB (  +35MB)  total
    Finished dev [unoptimized + debuginfo] target(s) in 1m 15s
```

### Meta
rustc 1.51.0 (2fd73fabe 2021-03-23)
rustc 1.52.0-beta.3 (215738137 2021-04-06)
rustc 1.53.0-nightly (b0c818c5e 2021-04-16)

```
$ rustc --print cfg
target_arch="x86_64"
target_endian="little"
target_env="gnu"
target_family="unix"
target_feature="fxsr"
target_feature="sse"
target_feature="sse2"
target_os="linux"
target_pointer_width="64"
target_vendor="unknown"
unix
```

**Comment by nagisa** [comment]
Err, https://github.com/rust-lang/rust/issues/74384.
