### ISSUE TITLE
Writing to file doesn't error even when file has been removed from disk

### ISSUE THREAD

**Issue by ohsayan** [rust-lang/rust#84307]
**I tried this code:** [See this MCVE](https://github.com/ohsayan/errfile-mcve-rs/blob/next/src/main.rs)

**I expected to see this happen:** The call to write() should have errored

**Instead, this happened:** No panic at all

### Meta
`rustc --version --verbose`:
```
rustc 1.51.0 (2fd73fabe 2021-03-23)
binary: rustc
commit-hash: 2fd73fabe469357a12c2c974c140f67e7cdd76d0
commit-date: 2021-03-23
host: x86_64-unknown-linux-gnu
release: 1.51.0
LLVM version: 11.0.1
```

@rustbot label: +A-io, +C-bug, +T-libs

**Comment by jonas-schievink** [comment]
This is working as expected. Linux doesn't delete a file from disk when removing it, it just unlinks it from the directory structure.

**Comment by ohsayan** [comment]
> This is working as expected. Linux doesn't delete a file from disk when removing it, it just unlinks it from the directory structure.

As I had expected; thanks for the clarification!
