### ISSUE TITLE
rustdoc: Make expand all / collapse all ephemeral

### ISSUE THREAD

**Issue by jsha** [rust-lang/rust#84318]
Each rustdoc page has a `[+]` icon in the top right, which can be used to expand all / collapse all docs:

<img src="https://user-images.githubusercontent.com/220205/115156110-a497f680-a037-11eb-9620-8f0bb7720924.png" width=150>

It also has a series of toggles along the left edge, to expand and collapse specific sections:

<img src="https://user-images.githubusercontent.com/220205/115156185-e3c64780-a037-11eb-8fb9-496c3b55ef79.png" width=450>

And a settings page to set which types of things are collapsed and expanded by default:

![image](https://user-images.githubusercontent.com/220205/115156229-0fe1c880-a038-11eb-8326-f6fe0aeea92c.png)

The left-hand toggles are ephemeral - they aren't remembered across page loads. The settings page settings are durable - they are remembered across page loads. Right now the `[+]` in the upper right is durable. That's surprising, since it looks the same as the non-durable left hand toggles, and isn't visible in the settings page. Also, it can be used via the `+` / `-` keyboard shortcuts, where it might not be as clear that someone is triggering a settings change.

I think we should change the `[+]` in the upper right to be ephemeral. If someone wants to durably hide all docs (or durably show all docs), the settings page settings should accomplish that.

/cc @GuillaumeGomez @jyn514

**Comment by jyn514** [comment]
Sure, that seems reasonable. I expected it to be ephemeral actually :sweat_smile:
