### ISSUE TITLE
install rust with configure,fail to build musl target on aarch64

### ISSUE THREAD

**Issue by lee128** [rust-lang/rust#84329]
Hello, I git clone the rust source code, and use the following configure:
`./configure --musl-root-aarch64=/usr/local/musl --build=aarch64-unknown-linux-gnu --host=aarch64-unknown-linux-gnu --target=aarch64-unknown-linux-gnu,aarch64-unknown-linux-musl --enable-extended --tools=analysis,cargo,clippy,rls,rustfmt,src`

the install is success

![image](https://user-images.githubusercontent.com/19389287/115201043-742f8580-a127-11eb-99bc-7143cc4d279c.png)

but when I try to cargo build with musl target, it report a error.
`cargo build --target aarch64-unknown-linux-musl`

![image](https://user-images.githubusercontent.com/19389287/115201197-a04b0680-a127-11eb-8c41-e36284e041c6.png)

I didn't use rustup tools for this.

**Comment by 12101111** [comment]
You need `--enable-lld`

**Comment by lee128** [comment]
> You need `--enable-lld`

I add this option, but still fail to build, the error is the same.

I checked the compiled musl lib
![1](https://user-images.githubusercontent.com/19389287/115334874-beb80d00-a1ce-11eb-8ff8-c8bb2d85d226.png)

And compare with musl lib which id download from rust static site
![2](https://user-images.githubusercontent.com/19389287/115334877-bfe93a00-a1ce-11eb-838c-c2a2e7a95197.png)

The size of these two are quite different. I dnon't konw why is that?

**Comment by Dylan-DPC** [comment]
Closing this to clear up the issue tracker. If you or anyone reading this still needs help you can consult the forums, discords, etc for help. Thanks
