### ISSUE TITLE
Add an allow-by-default lint that triggers on reachable catch-all / rest patterns

### ISSUE THREAD

**Issue by jplatte** [rust-lang/rust#84332]
syn currently allows users to [opt into having their tests fail](https://docs.rs/syn/1.0.69/src/syn/expr.rs.html#227-251) if a match of one of the enums it defines is non-exhaustive:

```rust
match expr {
    Expr::Array(e) => {...}
    Expr::Assign(e) => {...}
    ...
    Expr::Yield(e) => {...}

    #[cfg(test)]
    Expr::__TestExhaustive(_) => unimplemented!(),
    #[cfg(not(test))]
    _ => { /* some sane fallback */ }
}
```

In [the tracking issue for the `#[non_exhaustive]` attribute](https://github.com/rust-lang/rust/issues/44109), it was discussed to allow this in a less hacky way, for truly non-exhaustive enums, with dtolnay suggesting a lint (https://github.com/rust-lang/rust/issues/44109#issuecomment-521781237) like this:

```rust
match expr {
    Expr::Array(e) => {...}
    Expr::Assign(e) => {...}
    ...
    Expr::Yield(e) => {...}

    #[cfg_attr(test, deny(reachable))]
    _ => { /* some sane fallback */ }
}
```

Later, [a clippy issue](https://github.com/rust-lang/rust-clippy/issues/5557) was opened about the same thing and [a PR](https://github.com/rust-lang/rust-clippy/pull/6328) opened to address it. However, that PR was closed because

> the thing is that rustc already has exhaustiveness checks, and this is a lint that was proposed in a Rust RFC, so it would both be _easy_ to implement in rustc and _make sense_. It feels weird to reimplement exhaustiveness checking in a partial way outside of rustc when we can have a perfect version of this lint in rustc.
>
> — https://github.com/rust-lang/rust-clippy/pull/6328#issuecomment-770460622

**Comment by jplatte** [comment]
Unresolved questions:

* Should this be an attribute on the match expression like the clippy lint from the PR, e.g. `not_exhaustive_enough` or an attribute on the rest pattern, e.g. `reachable`? The former would also make sense to be used in a larger context, e.g. warn on all `match`es with reachable catch-alls in an entire module, or even crate. IMHO, the former could easily be a footgun, so I favor the latter.
* Should this attribute also be supported on `struct` matches? I actually have a use case for this¹, so would be happy to see this supported. If the lint is decided to be `reachable`rather than `not_exhaustive_enough`, this would first require the ability to use attributes on `..` in struct patterns, which currently don't produce an error, but don't do anything (#81282).

I would be happy to work on this if somebody can give me some pointers.

¹ allowing one crate to closely replicate a non-exhaustive struct from another crate, with some specific adjustments

**Comment by Nadrieril** [comment]
Is this covered by the discussion on issue https://github.com/rust-lang/rust/issues/69930 or is it distinct?

**Comment by jplatte** [comment]
No, I don't think so. That issue (and the surrounding discussion) is only about non-exhaustive types in the current crate, while this one is about non-exhaustive types in external crates, where a catch-all branch can't be avoided but where it's still sometimes useful to know when it becomes reachable with a depedency upgrade.

**Comment by Nadrieril** [comment]
There's a subtlety I wanted to point out if someone finds this issue: `deny(reachable)` is subtly different from what I gather to be the intention of this issue. In the following example, the wildcard is reachable, so `deny(reachable)` on the wildcard would trigger. But I think the intent of this issue is that we shouldn't trigger on this match since all variants of the enum are mentioned.
The lint about to be merged in https://github.com/rust-lang/rust/pull/86809 does the other thing, namely only triggers if some variant is not mentioned. It would not trigger on this example.
```rust
#[non_exhaustive]
enum Foo {
  A(bool),
  B
}
match foo {
  Foo::A(true) => {}
  Foo::B => {}
  _ => {}
}
```
