### ISSUE TITLE
closure on struct usability

### ISSUE THREAD

**Issue by caperaven** [rust-lang/rust#84369]
consider the following code

```
fn run<F>(f: F) where F: Fn() {
    f();
}

struct A <F: Fn()> {
    f: F
}

fn main() {
    let p = || println!("hello world");
    let a = A{f: p};

    // works
    run(a.f);

    // does not work
    a.f();
}
```

p is a closure that can is set on struct A.  
you can't call a.f() as it tells you that it must be a method.
you have to wrap a.f in brackets (a.f)().

if you consider the run function it just uses the closer as a function and runs it.
I feel that the brackets around a.f should not be a required syntax. 
The compiler (not that i know how to write compilers) should be clever enough to realize that you set a closure on the struct and thus it behaves like one.

if I can call p(); I should be able to use a.f().

**Comment by jonas-schievink** [comment]
Hi! Additions or changes to the language need to go through our [RFC process](https://github.com/rust-lang/rfcs). Before an RFC is written, the feature can also be discussed in our [internals forum](https://internals.rust-lang.org/) to find other people interested in it.

Closing in favor of an RFC.

**Comment by PatchMixolydic** [comment]
Allowing the closure to be called as `a.f()` would lead to an ambiguity ((playground)[https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=29137cd3d5ff392a7ff4f46ad76127e2]):

```rust
struct A<F: Fn()> {
    f: F
}

impl<F: Fn()> A<F> {
    fn f(&self) {
        println!("`A::f` called");
    }
}

fn main() {
    let a = A { f: || println!("closure called")};
    a.f(); // `A::f` called
    (a.f)(); // closure called
}
```

`A` has a field `f`, which is a closure, and a method `f`. If the compiler accepted `a.f()` as calling the closure, this might be surprising to programmers who wish to call the method `A::f`. To avoid this, `rustc` simply requires this syntactic quirk to reduce confusion.
