### ISSUE TITLE
rustdoc: [src] button in keyword pages takes to end of keyword documentation

### ISSUE THREAD

**Issue by tatami4** [rust-lang/rust#84372]
Clicking src button in docs for language keyword takes you to the end of the keyword documentation.

For example, clicking src button here:
![Screenshot_20210420_203706](https://user-images.githubusercontent.com/54238857/115440524-7de4e600-a218-11eb-9677-daf92579c018.png)

takes you here:
![Screenshot_20210420_203809](https://user-images.githubusercontent.com/54238857/115440512-7ae9f580-a218-11eb-849f-0c5bb19c0f7e.png)

instead of here:
![Screenshot_20210420_204341](https://user-images.githubusercontent.com/54238857/115441070-2004ce00-a219-11eb-93fa-ee1b3b645dcb.png)

**Comment by jyn514** [comment]
Duplicate of https://github.com/rust-lang/rust/issues/81691.
