### ISSUE TITLE
Rustdoc: building docs with 3rd party lib - "serde_json" results in compilation error

### ISSUE THREAD

**Issue by pm5k** [rust-lang/rust#84381]
Hello,

Allow me to preface this with a disclaimer that I am very new to Rust, so it may be likely this is a self-induced problem rather than a `rustdoc` bug. I will try to explain as best I can:

## TL:DR;
Using `cargo run` in the root of my project results in a normal run and outputs the following:
```bash
Object({"age": Number(43), "name": String("John Doe")})
```

However running `rustdoc src/main.rs && cargo doc` from the root of my project has this output:
```bash
error[E0433]: failed to resolve: use of undeclared crate or module `serde_json`
  --> src/utils/parser.rs:32:42
   |
32 | pub fn parse_unknown_json(data: &str) -> serde_json::Value {
   |                                          ^^^^^^^^^^ use of undeclared crate or module `serde_json`

error: Compilation failed, aborting rustdoc

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0433`.
```
## Project layout
```
src/
|__utils/
|  |__parser.rs
|  |__mod.rs
|__main.rs
```

## Project files
<details><summary>Cargo.toml</summary>
<p>

```toml
[package]
name = "parsing-prog"
# ...
edition = "2018"
# ...

[[bin]]
name = "main"
path = "./src/main.rs"
doc = true

[dependencies]
serde = { version = "1.0.125", features = ["derive"] }
serde_json = "1.0.64"
```

</p>
</details>

<details><summary>main.rs</summary>
<p>

```rust
mod utils;
fn main() {
  let data = r#"
    {
      "name": "John Doe",
      "age": 43
    }"#;
  println!("{:?}", utils::parser::parse_unknown_json(data));
}
```

</p>
</details>

<details><summary>utils/mod.rs</summary>
<p>

```rust
pub mod parser;
```

</p>
</details>

<details><summary>utils/parser.rs</summary>
<p>

```rust
pub fn parse_unknown_json(data: &str) -> serde_json::Value {
    let unknown: serde_json::Value = serde_json::from_str(data).unwrap();
    return unknown;
}
```

</p>
</details>

### In `main.rs`  I tried to include the following at the top:

`use serde_json;` -- Same error

`extern crate serde_json;` -- Error changes to: 
<details><summary>Backtrace</summary>
<p>

```bash
error[E0463]: can't find crate for `serde_json`
 --> src/aggregator.rs:1:1
  |
1 | extern crate serde_json;
  | ^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
```

</p>
</details>

### In `parser.rs` I tried to include:
`use serde_json;`
<details><summary>Backtrace</summary>
<p>

```bash
error[E0432]: unresolved import `serde_json`
 --> src/utils/parser.rs:7:5
  |
7 | use serde_json;
  |     ^^^^^^^^^^ no `serde_json` in the root

error: Compilation failed, aborting rustdoc

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0432`.
```

</p>
</details>

`use crate::serde_json;`
<details><summary>Backtrace</summary>
<p>

```bash
error[E0432]: unresolved import `crate::serde_json`
 --> src/utils/parser.rs:7:5
  |
7 | use crate::serde_json;
  |     ^^^^^^^^^^^^^^^^^ no `serde_json` in the root

error: Compilation failed, aborting rustdoc

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0432`.
```

</p>
</details>

`extern crate serde_json;`
<details><summary>Backtrace</summary>
<p>

```bash
error[E0463]: can't find crate for `serde_json`
 --> src/utils/parser.rs:7:1
  |
7 | extern crate serde_json;
  | ^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
```

</p>
</details>

## I also recreated a project which uses a path dependency instead of `serde_json`:

The top-level package remains the same, the nested dependency's main folder is in the root of the main project (next to the `src/` folder. It has a toml file like so:

```toml
[package]
name = "rdtd"
version = "0.1.0"
edition = "2018"

[lib]
name = "rdtd"
path = "./src/lib.rs"

[dependencies]
```

..And a `lib.rs` file with the method the main package imports:
```rust
pub fn test(data: &str) -> String {
    return format!("Someprefix-{}", data);
}

fn main() {}
```

Finally - in the top-level project I am importing it as:
```toml
[dependencies]
rdtd = { path = "rdtd/" }
```

And using it in `utils::parser.rs` like so:
```rust
// Notice that no import is even specified here or attempted to be specified..
pub fn prefix_data(data: &str) -> String {
    let prefixed = rdtd::test(data);
    return prefixed;
}
```

And this not only runs fine, but `rustdoc src/main.rs && cargo doc` runs just fine too. No errors. At all.
So either I am introducing some strange behaviour or `serde_json` is a very special case...

## Meta
`rustc --version --verbose`:
```
rustc 1.51.0 (2fd73fabe 2021-03-23)
binary: rustc
commit-hash: 2fd73fabe469357a12c2c974c140f67e7cdd76d0
commit-date: 2021-03-23
host: x86_64-apple-darwin
release: 1.51.0
LLVM version: 11.0.1
```

**Comment by jyn514** [comment]
@pm5k you don't need to run `rustdoc src/main.rs`, just `cargo doc`. rustdoc itself doesn't know what your dependencies are.
