### ISSUE TITLE
Type annotations needed error on definition site

### ISSUE THREAD

**Issue by vorner** [rust-lang/rust#84398]
Hello

After upgrading nightly rustc, I'm getting a lot of type inference errors on code that was compiling fine previously. Moreover, these are not at the call site, but at the definition site, so there doesn't seem to be any place to put any type annotations, like this:

```
    --> src/spirit.rs:996:1
     |
996  | / impl<O, C> SpiritBuilder for Builder<O, C>
997  | | where
998  | |     Self::Config: DeserializeOwned + Send + Sync + 'static,
999  | |     Self::Opts: StructOpt + Sync + Send + 'static,
...    |
1108 | |     }
1109 | | }
     | |_^ cannot infer type for type parameter `C`
```

It spills more kinds of errors that make little sense, but I have the impression these will have a common cause:

```
error[E0277]: `C` cannot be shared between threads safely
   --> src/spirit.rs:998:45
    |
998 |     Self::Config: DeserializeOwned + Send + Sync + 'static,
    |                                             ^^^^ `C` cannot be shared between threads safely
```

The problematic code is both released on crates.io (crate spirit, version 0.4.16, but I expect that to be happening through most of the history of the crate), and in master (https://github.com/vorner/spirit/commit/1495c1cdef17663e8f847f037abeceb37f310fad).

I think this is a regression, as it was compiling previously.

It compiles fine with older nightly (and stable is fine way back, this particular code is looking mostly the same for some 2 years or more):

```
rustc 1.53.0-nightly (07e0e2ec2 2021-03-24)
```

Breaks with

```
rustc 1.53.0-nightly (6df26f897 2021-04-20)
binary: rustc
commit-hash: 6df26f897cffb2d86880544bb451c6b5f8509b2d
commit-date: 2021-04-20
host: x86_64-unknown-linux-gnu
release: 1.53.0-nightly
LLVM version: 12.0.0
```

(Unfortunately, I haven't been keeping fully up to date recently, so I don't have a smaller range).

**Comment by hameerabbasi** [comment]
Bisected:

searched nightlies: from nightly-2021-01-01 to nightly-2021-04-20
regressed nightly: nightly-2021-04-01
searched commits: from https://github.com/rust-lang/rust/commit/74874a690bc95443292496ff5df5cc5c8cb56e0b to https://github.com/rust-lang/rust/commit/4fdac23f3171e2f8864d359a21da600dd3faafc9
regressed commit: https://github.com/rust-lang/rust/commit/4fdac23f3171e2f8864d359a21da600dd3faafc9

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.0</summary>


Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --test-dir=. --start=2021-01-01
```
</details>

Regressed PR is #76814, cc @jackh726.

**Comment by jackh726** [comment]
An MCVE would be exceptionally helpful here.

**Comment by hameerabbasi** [comment]
@rustbot ping icebreakers-cleanup-crew

I've tried without success to reduce this, it's buried in layers of crates. Maybe one of you will have better luck.

**Comment by SNCPlay42** [comment]
Reduced:

```rust
pub trait Deserialize<'de>: Sized {}
pub trait DeserializeOwned: for<'de> Deserialize<'de> {}

pub trait Extensible {
    type Config;
}

pub trait Installer<C> {
    fn init<B: Extensible<Config = C>>(&mut self) -> ()
    where
        B::Config: DeserializeOwned,
    {
    }
}
```

**Comment by apiraino** [comment]
Assigning priority as discussed as part of the [Prioritization Working Group https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2384398.20Type.20annotations.20needed.20error.20on.20definition.20site) and removing `I-prioritize`.

@rustbot label -I-prioritize +P-high

**Comment by b-naber** [comment]
I can try to look into this over the weekend.

**Comment by jackh726** [comment]
So, a bit of info: We end up trying to prove `C: Sized`. We end up with two candidates:
```
ParamCandidate(ConstnessAnd { constness: NotConst, value: Binder(<C as std::marker::Sized>, [Region(BrNamed(DefId(0:6 ~ issue_84398[317d]::DeserializeOwned::'de), 'de))]) })
```
and
```
ParamCandidate(ConstnessAnd { constness: NotConst, value: Binder(<C as std::marker::Sized>, []) })
```
that both evaluate to okay. This is ambiguous and WF checking fails.

**Comment by pietroalbini** [comment]
This regression now slipped into beta 1.53.0.
