### ISSUE TITLE
When `std` is missing the error message is very poor

### ISSUE THREAD

**Issue by Lokathor** [rust-lang/rust#84418]
A newbie Rustacean was trying to use the `gba` crate and they forgot to put `#![no_std]` in the `lib.rs` of their downstream project. The GBA uses a Tier 3 target with `build-std`, and so they landed on this error:
```
error[E0463]: can't find crate for `std`
  |
  = note: the `thumbv4t-none-eabi` target may not be installed

error: aborting due to previous error

For more information about this error, try `rustc --explain E0463`.
error: could not compile `gba-rust`
```

This is a poor experience. It's pretty vague about what went wrong, and has no suggestion of what the person can do to try and fix it.

Ideally, the error message should say something like:

> `std` is required by `cratenamehere` because it does not declare `#![no_std]`

And then the user can have at least an idea of what to investigate.

**Comment by jonas-schievink** [comment]
related: https://github.com/rust-lang/rust/issues/32663
