### ISSUE TITLE
Dynamic link error in stable Rust, not in nightly rust

### ISSUE THREAD

**Issue by qiujiangkun** [rust-lang/rust#84423]
I encountered this error in my project. Basically I'm writing a plugin system and use libloading to load .so files. However, I met this mysterious linkage error.
```log
Apr 22 08:14:16.930  INFO main backtesting::loader: Loading strategy strategy_example
Apr 22 08:14:16.930  INFO main backtesting::loader: Loading library "./strategy_example/libstrategy_example.so"
thread 'main' panicked at 'Cannot load library: DlOpen { desc: "./strategy_example/libstrategy_example.so: undefined symbol: _ZN3std5error5Error6source17h59fb627c0118f46bE" }', backtesting/src/loader.rs:73:58
```
Upon futher investigation, I found that this problem only occures in stable rust. When I compile my code with nightly rust, everything goes well.

Sorry that I couldn't reproduce it with simpler examples.
```log
                          ./+o+-       ubuntu@ubuntu
                  yyyyy- -yyyyyy+      OS: Ubuntu 20.04 focal
               ://+//////-yyyyyyo      Kernel: x86_64 Linux 5.8.0-48-lowlatency
           .++ .:/++++++/-.+sss/`      Uptime: 6d 2h 20m
         .:++o:  /++++++++/:--:/-      Packages: 864
        o:+o+:++.`..```.-/oo+++++/     Shell: zsh 5.8
       .:+o:+o/.          `+sssoo+/    Disk: 11G / 32G (35%)
  .++/+:+oo+o:`             /sssooo.   CPU: Intel Xeon Platinum 8124M @ 2x 3.414GHz
 /+++//+:`oo+o               /::--:.   RAM: 2502MiB / 3695MiB
 \+/+o+++`o++o               ++////.  
  .++.o+++oo+:`             /dddhhh.  
       .+.o+oo:.          `oddhhhh+   
        \+.++o+o``-````.:ohdhhhhh+    
         `:o+++ `ohhhhhhhhyo++os:     
           .o:`.syhhhhhhh/.oo++o`     
               /osyyyyyyo++ooo+++/    
                   ````` +oo+++o\:    
                          `oo++.    


rustc --version
rustc 1.51.0 (2fd73fabe 2021-03-23)

```
You should remove `.zip` in `lib.z??.zip` before extracting.
[lib.z01.zip](https://github.com/rust-lang/rust/files/6356733/lib.z01.zip)
[lib.z02.zip](https://github.com/rust-lang/rust/files/6356734/lib.z02.zip)
[lib.z03.zip](https://github.com/rust-lang/rust/files/6356735/lib.z03.zip)
[lib.z04.zip](https://github.com/rust-lang/rust/files/6356736/lib.z04.zip)
[lib.zip](https://github.com/rust-lang/rust/files/6356738/lib.zip)

**Comment by nagisa** [comment]
Make sure the libraries you're using as plugins are either compiled with _exactly_ the same version of the compiler as the application that's loading them or that the libraries are `cdylib`s rather than `dylib`s.

**Comment by qiujiangkun** [comment]
Maybe it's because my weird project structure. After some workaround, the problem disappeared. I'd close this issue for now since I can't reproduce it with simpler examples.
