### ISSUE TITLE
Bad suggestion when encountering `type Foo<T>` in `trait`

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#84439]
[Incorrect suggestion](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=92030954d8e9637d4d93864d70591fdf):

```
error[E0658]: generic associated types are unstable
 --> src/lib.rs:2:5
  |
2 |     type Member<T>;
  |     ^^^^^^^^^^^^^^^
  |
  = note: see issue #44265 <https://github.com/rust-lang/rust/issues/44265> for more information

error[E0107]: missing generics for associated type `CollectionFamily::Member`
 --> src/lib.rs:2:10
  |
2 |     type Member<T>;
  |          ^^^^^^ expected 1 type argument
  |
note: associated type defined here, with 1 type parameter: `T`
 --> src/lib.rs:2:10
  |
2 |     type Member<T>;
  |          ^^^^^^ -
help: use angle brackets to add missing type argument
  |
2 |     type Member<T><T>;
  |                ^^^
```

We need to correctly track the span for the obligation to [suggest somewhat reasonable code](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=47cc880f652a7326f74cdfd8a02fb962).

Taken from https://github.com/rust-lang/rust/issues/78671

**Comment by jackh726** [comment]
Well, it actually literally is except this uses a type instead of a lifetime. Fixed by #82272. I'm going to go ahead and close this.
