### ISSUE TITLE
Last Statement does not require semicolon.

### ISSUE THREAD

**Issue by gdinesh-software** [rust-lang/rust#84505]
When we have some functions with the last statement without the semicolon, the source code gets compiled without any problems.
If it's feature like lisp where the last statement is returned explicitly, I am extremely sorry! I am just learning rust.
![Screenshot (2)](https://user-images.githubusercontent.com/76434436/115952817-ddd3d900-a505-11eb-9653-30244d6a5124.png)

**Comment by marmeladema** [comment]
This is not a bug, but indeed a feature of the rust language. You can find documentation about functions at https://doc.rust-lang.org/rust-by-example/fn.html
