### ISSUE TITLE
Parenthesizing the end of a range pattern gives misleading "no end" error

### ISSUE THREAD

**Issue by scottmcm** [rust-lang/rust#84528]
Given the following code: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=a282d34ca0fc43a742e35a6179ffad80

```rust
fn main() {
    match 4 {
        0..=(10) => (),
        _ => (),
    }
}
```

The current output is:

```
error[E0586]: inclusive range with no end
 --> src/main.rs:3:10
  |
3 |         0..=(10) => (),
  |          ^^^ help: use `..` instead
  |
  = note: inclusive ranges must be bounded at the end (`..=b` or `a..=b`)

error: expected one of `=>`, `if`, or `|`, found `(`
 --> src/main.rs:3:13
  |
3 |         0..=(10) => (),
  |             ^ expected one of `=>`, `if`, or `|`

error[E0658]: half-open range patterns are unstable
 --> src/main.rs:3:9
  |
3 |         0..=(10) => (),
  |         ^^^^
  |
  = note: see issue #67264 <https://github.com/rust-lang/rust/issues/67264> for more information
  = help: add `#![feature(half_open_range_patterns)]` to the crate attributes to enable
```

But it's pretty clear that the user was *trying* to provide an end, so the "inclusive range with no end" error seems suboptimal.

Perhaps it could mention that literals can't be parenthesized?  Or parse the parens and give an error about not being able to use them there?  Or even a grammar change to just allow it...

**Comment by Nadrieril** [comment]
That shouldn't be too hard to fix. I'd grep the `compiler` folder to see which code emits "inclusive range with no end". That would be code in the parser that just parsed `..=` and is now expecting a number. In the case where it couldn't parse a number, we can try to recover by checking if there's instead a parenthesis followed by a number. We would then emit a better error.

**Comment by tianyaochou** [comment]
Now the compiler correctly reports:

```
Compiling playground v0.0.1 (/playground)
error: range pattern bounds cannot have parentheses
 --> src/lib.rs:3:13
  |
3 |         0..=(10) => (),
  |             ^  ^
  |
help: remove these parentheses
  |
3 -         0..=(10) => (),
3 +         0..=10 => (),
  |

error: could not compile `playground` (lib) due to 1 previous error
```

**Comment by Nadrieril** [comment]
Wonderful
