### ISSUE TITLE
LTO is enabled at opt-level=2 even with lto=false

### ISSUE THREAD

**Issue by Rua** [rust-lang/rust#84527]
My project has the following profile settings in the `Cargo.toml`:

```toml
[profile.dev]
opt-level = 2
incremental = true
lto = false

[profile.release]
incremental = true
lto = true
```

I profiled the building of my project using `cargo +nightly rustc -- -Zself-profile`. There's no `--release` so I assume it's going to do a dev build. Then, I run `summarize summarize` on the profiling file that was produced, and it lists as the very first item, therefore taking the most time:

```
+--------------------------------------------------+-----------+-----------------+----------+------------+
| Item                                             | Self time | % of total time | Time     | Item count |
+--------------------------------------------------+-----------+-----------------+----------+------------+
| LLVM_lto_optimize                                | 172.31s   | 23.797          | 172.31s  | 256        |
+--------------------------------------------------+-----------+-----------------+----------+------------+
```
This is unexpected, because LTO is explicitly disabled in the dev profile. I'm assuming that `opt-level = 2` simply includes LTO by default, but then why am I not able to override it?

`rustc --version --verbose`:
```
rustc 1.53.0-nightly (bb491ed23 2021-04-23)
binary: rustc
commit-hash: bb491ed23937aef876622e4beb68ae95938b3bf9
commit-date: 2021-04-23
host: x86_64-unknown-linux-gnu
release: 1.53.0-nightly
LLVM version: 12.0.0
```

**Comment by ehuss** [comment]
Hi!  The profile setting `lto = false` still does "thin local LTO" when the opt-level is not zero, which is LTO on the local crate across codegen units. To fully disable LTO, the setting needs to be `lto = "off"`.  There's more info in the [docs](https://doc.rust-lang.org/cargo/reference/profiles.html#lto).  I realize that might be a little confusing (there is https://github.com/rust-lang/cargo/issues/7491 filed for this), but that is how things evolved over time.

**Comment by Rua** [comment]
`false` and `"off"` are different things? Yes, that is rather confusing indeed! But thanks for the explanation.

**Comment by weihanglo** [comment]
Close in favor of <https://github.com/rust-lang/cargo/issues/7491>.
