### ISSUE TITLE
rustdoc: clarify theme settings

### ISSUE THREAD

**Issue by jsha** [rust-lang/rust#84539]
Right now, you can set theme options in two places, the paintbrush icon, and the settings page:

![image](https://user-images.githubusercontent.com/220205/115977816-391ac100-a530-11eb-9937-54c7433c6503.png)

It's not clear how these are related. Does one override the other? Also, what is the "system theme"?

I propose that we move the paintbrush icon's functionality into the settings page, and overhaul the settings available there.

GitHub has put a lot of attention into their "dark mode" implementation and might make a good example for verbiage:

---

![image](https://user-images.githubusercontent.com/220205/115978077-070a5e80-a532-11eb-8d19-f3f7f6ab3608.png)

---

![image](https://user-images.githubusercontent.com/220205/115978084-125d8a00-a532-11eb-88ed-8b00b0e46020.png)

---

Following that example, the settings page should have a choice between "single theme" and "sync with system", with a single dropdown visible if you pick "single theme," and two dropdowns (for light/dark) visible if you pick "sync with system."

Prior work:

https://github.com/rust-lang/rust/pull/77213
https://github.com/rust-lang/rust/pull/79642
https://github.com/rust-lang/rust/pull/77809
https://github.com/rust-lang/rust/pull/77213

**Comment by GuillaumeGomez** [comment]
That would be problematic when browsing documentation from the filesystem and not with a server because then, it'd not be possible to change the theme because the local storage is stored at a folder level.

**Comment by jsha** [comment]
One way we could address that issue would be to make the settings page rendered by JS instead of a standalone HTML page. That would also allow all the other settings to be applied in the file:/// context. Another way would be to decide that certain features (like theme switching) only work locally if you use, e.g. `python -m http.server' so you can access the files at an HTTP URL.

**Comment by GuillaumeGomez** [comment]
That could work I guess... I'm not super happy about adding more JS. Also, currently it's very easy to change the current theme, putting it into the setting page would make this more confusing I think.

**Comment by jsha** [comment]
> To be more precise, on firefox it's per-folder and not per-file.

In my local tests (Firefox 93.0, Linux), it's per-file. Steps to reproduce:

1. Navigate to build/x86_64-unknown-linux-gnu/doc/std/string/struct.String.html
2. Set theme to dark
3. Navigate to build/x86_64-unknown-linux-gnu/doc/std/string/struct.Drain.html
4. Notice theme is not dark. But hitting back and reload shows the theme is still dark on the String page.

So is it okay by you moving the theme setting onto the settings page? Things would continue to work as they do today on Chrome. On Firefox, you would stop being able to set the theme page-at-a-time, but I think the current page-at-a-time functionality on Firefox is not very useful.

**Comment by GuillaumeGomez** [comment]
I'm pretty sure that if we do that, people will simply complain because they can't change the theme anymore. And that would also prevent to have theme change which I quite enjoy locally.

As for your scenario, I tried it locally but it worked fine. Weird... I don't seem to have any specific customization though...

**Comment by GuillaumeGomez** [comment]
From [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage):

> For documents loaded from file: URLs (that is, files opened in the browser directly from the user’s local filesystem, rather than being served from a web server) the requirements for localStorage behavior are undefined and may vary among different browsers.

Undefined, great.

**Comment by jsha** [comment]
@GuillaumeGomez and I discussed via PM on Zulip, and came to a compromise solution: We'll show the theme picker icon only when visiting a file:/// URL. That way we get a nice uncluttered UI on doc.rust-lang.org and docs.rs, but we don't lose the theme-picking functionality on local files.
