### ISSUE TITLE
rustdoc-gui test suite not run on CI?

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/rust#84550]
It seems like the rustdoc-gui test suite isn't run on CI because it fails when run locally (as it should) because recent changes modified DOM, making the `nojs-attr-pos` fail.

cc @Mark-Simulacrum

**Comment by jyn514** [comment]
@GuillaumeGomez this happens because you never installed `node` in the CI environment:
```
Set({"src/test/rustdoc-gui"}) not skipped for "bootstrap::test::RustdocGUI" -- not in ["src/tools/tidy"]
Set({"src/tools/rustdoc-themes"}) not skipped for "bootstrap::test::RustdocTheme" -- not in ["src/tools/tidy"]
No nodejs found, skipping "src/test/rustdoc-gui" tests
```
This makes me even more certain that both this testsuite and https://github.com/rust-lang/rust/pull/84480 should be run unconditionally in CI.

**Comment by GuillaumeGomez** [comment]
But I did install node: https://github.com/rust-lang/rust/pull/79979/files#diff-855904217a51ab471ca6d49c7ecaa231a5a3812d10dc110c4d40dfb8e24bc708R33

**Comment by jyn514** [comment]
That only runs on x86_64-gnu-aux, which I think isn't run on PRs. I can't find any mentions of it at all except this one: https://github.com/rust-lang/rust/blob/06f0adb34570ba83fee391abeb0bec0eec28a234/src/ci/github-actions/ci.yml#L406-L407
Which job do you think it runs on?

**Comment by GuillaumeGomez** [comment]
The one that is run by github actions (one of the 3 checks that is run when you open a PR).

**Comment by jyn514** [comment]
No, none of those jobs are `x86_64-gnu-aux`. You need to move it to `job-linux-xl` or `x86_64-gnu-llvm-10` if you want it to run on PRs.

**Comment by jyn514** [comment]
And again, I *really* think this is the wrong approach and it should be run unconditionally. Otherwise it will break again in the future.

**Comment by GuillaumeGomez** [comment]
I agree with you. The problem here is that installing puppeteer is quite tricky (because it requires a specific chrome instance). And I have no idea how to handle node/npm install on non-linux targets.

**Comment by jyn514** [comment]
Ok, can you instead add an assert to bootstrap that makes sure the tests aren't skipped on any linux platform? That should be easier than trying to get this to work on all tier 1 targets.

**Comment by Mark-Simulacrum** [comment]
Please don't do that, we're explicitly requesting it on one of the builders, so we can simply avoid marking the job as default and change the nodejs conditional to a requirement.

**Comment by GuillaumeGomez** [comment]
@Mark-Simulacrum Any tip/example on how to do that?

**Comment by jyn514** [comment]
@GuillaumeGomez toggle this constant: https://github.com/rust-lang/rust/blob/58bdb08947f5b3c18a2fbafc5cf36af7b5677d83/src/bootstrap/test.rs#L772
and give a hard error here: https://github.com/rust-lang/rust/blob/58bdb08947f5b3c18a2fbafc5cf36af7b5677d83/src/bootstrap/test.rs#L797-L800

**Comment by jyn514** [comment]
Actually it might even be nicer to leave DEFAULT on but add a `default_condition` that npm is installed - @Mark-Simulacrum how does that sound? https://github.com/rust-lang/rust/blob/58bdb08947f5b3c18a2fbafc5cf36af7b5677d83/src/bootstrap/test.rs#L775-L777

**Comment by Mark-Simulacrum** [comment]
That seems reasonable too.

**Comment by GuillaumeGomez** [comment]
Ok, gonna send a PR for it tomorrow then!

**Comment by dns2utf8** [comment]
Quick question: Is it documented already that node with some version is one of the optional requirements?

**Comment by GuillaumeGomez** [comment]
I didn't put a requirement for the node version. And it's in the README in `src/test/rustdoc-gui`. :)

**Comment by jyn514** [comment]
This was fixed by https://github.com/rust-lang/rust/pull/84586.
