### ISSUE TITLE
`fn_sig` query panicks for specific malformed program.

### ISSUE THREAD

**Issue by crlf0710** [rust-lang/rust#84569]
During implementation of #84401, i found that `fn_sig` query panicks for a specific malformed test case:
`test/ui/proc-macro/issue-59191-replace-root-with-fn.rs`

In #84401 I plan to make the compilation abort after the error is raised, but it would be nice to allow it to continue.

**Comment by crlf0710** [comment]
Now #84401 is ready to land, let me think more about this.
The current process is this:
1. `rustc_expand` properly detected this case, and emitted the error.
2. However a `DefId` is still allocated for this malformed structure. But a `HirId` is never did.
3. `rustc_resolve` is able to give this `DefId` as resolution output, despite it's malformed.
4. #84401 Sent it to `fn_sig` and other queries
5. These queries tries to access the hir data with the assumption that every input local def id has corresponding hir data, leading to a index out of range.

It seems i need to break this chain somewhere in the list. Do you have any mentoring advice here, @petrochenkov?

**Comment by crlf0710** [comment]
@jyn514 Thanks! Let me give it a try.

**Comment by Nilstrieb** [comment]
The linked PR was merged and I'm not aware of any bugs, they should be tracked separately anyways.
