### ISSUE TITLE
Blog post announcing Rust 2021 feature set

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#84593]
We plan a blog post announcing the Rust 2021 Feature Set and introducing the key ideas of the edition. This issue is a placeholder to track that work item on the [Rust 2021 Project Board](https://github.com/orgs/rust-lang/projects/7).

**Comment by m-ou-se** [comment]
https://github.com/rust-lang/blog.rust-lang.org/pull/825
