### ISSUE TITLE
can't invoke sin() on a &{float}

### ISSUE THREAD

**Issue by TsuITOAR** [rust-lang/rust#84607]
I tried this code:

```rust
let s=&2.;
s.sin();
```

I expected to see this happen: s.sin() converted to (*s).copy().sin()

Instead, this happened: no method named `sin` found for reference `&{float}` in the current scope

### Meta

`rustc --version --verbose`:
```
rustc 1.51.0 (2fd73fabe 2021-03-23)
binary: rustc
commit-hash: 2fd73fabe469357a12c2c974c140f67e7cdd76d0
commit-date: 2021-03-23
host: x86_64-pc-windows-msvc
release: 1.51.0
LLVM version: 11.0.1
```

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by In-line** [comment]
[Playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=f8d962c2a867b3aaa84440074875a57f)

**Comment by In-line** [comment]
But this [this](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=9170cd83e3f2733dab4d7bf2dd4db5b5) works

```rust
fn main() {
    let s=&2.0f32;
    s.sin();
}

```

**Comment by TsuITOAR** [comment]
> But this [this](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=9170cd83e3f2733dab4d7bf2dd4db5b5) works
> 
> ```rust
> fn main() {
>     let s=&2.0f32;
>     s.sin();
> }
> ```

thx :)
rust-analyzer told me it's f64, but indeed it's {float}. now it works
