### ISSUE TITLE
Docs: Arguments are described in the reverse order for map_or and map_or_else

### ISSUE THREAD

**Issue by lefth** [rust-lang/rust#84608]
[Result](https://doc.rust-lang.org/std/result/enum.Result.html#method.map_or) and [Option](https://doc.rust-lang.org/std/option/enum.Option.html#method.map_or) have map_or and map_or_else functions. In each case, the first parameter is used when the struct contains no value (or contains an error), while the second parameter is used when there is a value in the struct. The documentation mentions there parameters in the reverse order. This is confusing, as programmers expect parameter names to be documented in order.

I suggest reversing the wording.

I'll be submitting a PR with the change. If there are other classes or functions that have this issue, please leave a comment and I will change them as well.

**Comment by jyn514** [comment]
Fixed in https://github.com/rust-lang/rust/pull/84609.
