### ISSUE TITLE
refactor lint mechanism to support "error in new edition, lint in older editions" pattern

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#84625]
We've been adding lints that, in newer editions, become hard errors. Right now we do this by manually creating either an error or a lint. (see e.g. https://github.com/rust-lang/rust/pull/83213/). We should introduce an API where we write one specification and the compiler decides, based on the edition of a particular span, whether to introduce a hard error or not.

**Comment by nikomatsakis** [comment]
I've marked this as E-mentor. I'm game to help someone with it!

Some mentoring notes:

* [rustc-dev-guide section on errors](https://rustc-dev-guide.rust-lang.org/diagnostics.html)
* Check out #83213 to see some examples of how the code to be cleaned up looks.

**Comment by petrochenkov** [comment]
`BARE_TRAIT_OBJECT` is not a good case for using such mechanism - https://github.com/rust-lang/rust/pull/83213#issuecomment-800603507.

**Comment by nikomatsakis** [comment]
OK; the mechanism may not be used enough to warrant existing =)

**Comment by nikomatsakis** [comment]
After some discussion, decided this is premature.
