### ISSUE TITLE
rustdoc: "copy path" icon should have a title attribute

### ISSUE THREAD

**Issue by jsha** [rust-lang/rust#84639]
To indicate what it does, i.e. "Copy use declaration to clipboard." Also, right now the action is triggered by an `onclick=` attribute in the HTML. It would be slightly nicer to use `addEventListener` in main.js, so it's easy to see in one place where all handlers are added.

**Comment by rukai** [comment]
Another observation to hopefully improve UX a bit, as I was very confused as to what this new feature did at first.
On crates.io the copy crate name icon looks like this:
![image](https://user-images.githubusercontent.com/5120858/116781131-59182a80-aac4-11eb-80e9-e9480d50cbc8.png)

Whereas the copy button looks like this:
![image](https://user-images.githubusercontent.com/5120858/116781240-10ad3c80-aac5-11eb-8af1-ce02325e1a02.png)
Maybe its just how ⎘ displays on my machine?
But the crates.io copy is immediately obvious to me while with the docs copy I would need to look at the proposed title attribute to figure out whats going on.

**Comment by ChrisDenton** [comment]
crates.io also shows a message when you click the button that tells you it copied something to the clipboard:

![copied](https://user-images.githubusercontent.com/4459874/117296709-478ca500-ae6d-11eb-8857-5332f4c5d066.png)

**Comment by jsha** [comment]
Fixed!
