### ISSUE TITLE
Tracking Issue for rustdoc `--test-run-directory`

### ISSUE THREAD

**Issue by ehuss** [rust-lang/rust#84674]
### Summary

This is a tracking issue for the `--test-run-directory` flag in rustdoc.  This flag changes the directory where doctests are run. This was added to support changing the directory used while running `rustdoc --test` in a Cargo workspace. See https://github.com/rust-lang/cargo/issues/9427 for more information.

### Unresolved Questions

None at this time.

### Implementation history

* #81264 — Initial PR.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

cc @Swatinem

**Comment by Swatinem** [comment]
# Request for Stabilization

I opened https://github.com/rust-lang/rust/pull/103682 with the aim to stabilize this rustdoc flag, primarily to facilitate the cargo `doctest-in-workspace` flag, and to eventually making it the default.

## Summary

The `--test-run-directory` flag in combination with `--test` allows specifying an explicit directory in which rustdoc will *run* the compiled doctests. The default, without this explicit flag, is to run the resulting doctest binaries in the same current working directory as rustdoc itself.

This flag is primarily the building block for the `doctest-in-workspace` cargo flag (See https://github.com/rust-lang/cargo/issues/9427).

With that flag, doctests are handled consistently to unit- and integration tests: They will be *compiled* relative to the cargo workspace root, but they are *run* in the crate directory.

## Documentation

The flag is currently *not* documented as part of the [unstable rustdoc features](https://doc.rust-lang.org/rustdoc/unstable-features.html).

## Tests

- [src/test/rustdoc-ui/run-directory.rs](https://github.com/rust-lang/rust/blob/a9ef10019fd3be6e03afb4b213368f4af1917f9b/src/test/rustdoc-ui/run-directory.rs) -- highlights usage with cwd-sensitive `std::fs` functions inside doctests.
- [cargo tests/testsuite/doc.rs](https://github.com/Swatinem/cargo/blob/6c1bc24b8b49d4bc965f67d7037906dc199c72b7/tests/testsuite/doc.rs#L1845-L1919) -- shows indirect usage via the cargo `doctest-in-workspace` flag.

## Unresolved questions

- Similar flags that allow hooking into or observing the side effects of rustdoc test compilation, such as [`--run-tool`](https://github.com/rust-lang/rust/issues/64245) or [`--persist-doctests`](https://github.com/rust-lang/rust/issues/56925) are not stable yet, and there does not seem to be a push to stabilization either.
- The usefulness of this flag when invoking `rustdoc` manually might be limited. But it is a requirement for the cargo `doctest-in-workspace` flag.
- ☝🏻 Is there maybe a better alternative to solve the compile/run directory inconsistency that exists in cargo workspaces today?

**Comment by Swatinem** [comment]
@ehuss over in https://github.com/rust-lang/cargo/issues/9427#issuecomment-1296326215 expressed agreement to make the `doctest-in-workspace` cargo flag the default, considering it rather a bugfix for the current inconsistent behavior.

However, stabilizing `--test-run-directory` is a requirement for that, and there does not seem to be a better alternative to it.

@GuillaumeGomez is there anything I can do to move stabilization (https://github.com/rust-lang/rust/pull/103682) forward?

**Comment by GuillaumeGomez** [comment]
Next step is the FCP. I'll start on the PR.

**Comment by DXist** [comment]
cargo test runs doc tests by default and doesn't allow to specify `--test-run-directory`.

My project uses sqlx which tries to create `target/sqlx/<crate_name>/` directory. But if fails because I run the build inside a container against immutable source.

Instead I expect that the test should stay in the workspace directory and use `<workspace_roo>/target` which is mounted as a build cache volume.
