### ISSUE TITLE
Debuginfo for niche-layout enums can be corrupted due to duplicate type names

### ISSUE THREAD

**Issue by wesleywiser** [rust-lang/rust#84670]
Niche layout enum variants do not get distinct type names that include type parameters which can cause duplicate type names for variants like `Option::Some`. This in turn will causes debugger to randomly pick one of the various type layouts when inspecting values which can cause invalid results.

```rust
fn main() {
    let a = Some(&1u8);
    let b = Some(&2u16);
    let c = Some(&3u32);
    let d = Some(&4u64);
    let e = Some(&5i8);
    let f = Some(&6i64);
    
    std::process::exit(0); // bp here
}
```

![image](https://user-images.githubusercontent.com/831192/116471920-3c20f480-a843-11eb-91dd-9073e78668a9.png)

Notice the values for `a`, `b` and `c` are totally wrong because they are using the layout for `Option<&i64>::Some`.  The types for the other variables are also wrong but that doesn't happen to cause issues in this particular instance.

**Comment by vadimcn** [comment]
@wesleywiser Could you please explain why duplicate names cause this confusion?  Aren't PDB types identified by record ids?

**Comment by wesleywiser** [comment]
@vadimcn I thought that as well but experimentally, the debugger seems to look up the types by name not record id. I've also seen warnings from cvdump related "duplicate/conflicting type definitions" even though the ids are different. 

I'll post the cvdump results when I get back into the office on Monday.

**Comment by wesleywiser** [comment]
For example, cvdump outputs this:

```
0x1015 : Length = 18, Leaf = 0x1203 LF_FIELDLIST
    list[0] = LF_MEMBER, public, type = T_64PUSHORT(0621), offset = 0
        member name = '__0'

0x1016 : Length = 78, Leaf = 0x1505 LF_STRUCTURE
    # members = 1,  field list type 0x1015, 
    Derivation list type 0x0000, VT shape type 0x0000
    Size = 8, class name = core::option::Some, unique name = 614d2e1de3c5e373cf909c161e5f6384::Some, UDT(0x00001037)

0x1035 : Length = 18, Leaf = 0x1203 LF_FIELDLIST
    list[0] = LF_MEMBER, public, type = T_64PQUAD(0613), offset = 0
        member name = '__0'

0x1037 : Length = 78, Leaf = 0x1505 LF_STRUCTURE
    # members = 1,  field list type 0x1035, 
    Derivation list type 0x0000, VT shape type 0x0000
    Size = 8, class name = core::option::Some, unique name = 2dfef4176b9038163574c2ab2dbdc08f::Some, UDT(0x00001037)

WARNING: UDT mismatch for core::option::Some
<<<<<<
0x1016 : Length = 78, Leaf = 0x1505 LF_STRUCTURE
    # members = 1,  field list type 0x1015, 
    Derivation list type 0x0000, VT shape type 0x0000
    Size = 8, class name = core::option::Some, unique name = 614d2e1de3c5e373cf909c161e5f6384::Some, UDT(0x00001037)

******
0x1037 : Length = 78, Leaf = 0x1505 LF_STRUCTURE
    # members = 1,  field list type 0x1035, 
    Derivation list type 0x0000, VT shape type 0x0000
    Size = 8, class name = core::option::Some, unique name = 2dfef4176b9038163574c2ab2dbdc08f::Some, UDT(0x00001037)

>>>>>>
```
