### ISSUE TITLE
`std::io::Error::get_ref()` return value changed in Nightly

### ISSUE THREAD

**Issue by antonok-edm** [rust-lang/rust#84678]
### Code

[Three tests](https://github.com/brave/adblock-rust/blob/94b377ca106dda88d301d6089639271daea1117a/src/engine.rs#L399-L460) for the `adblock` crate have begun failing in Nightly. At the [core](https://github.com/brave/adblock-rust/blob/master/src/data_format.rs#L112-L123) of these tests, a backward-compatible data format is deserialized by `rmp_serde` from a buffer:

```rust
impl DeserializeFormat {
    pub fn deserialize(serialized: &[u8]) -> Result<Self, DeserializationError> {
        let mut gz = GzDecoder::new(serialized);
        let part1: DeserializeFormatPart1 = rmps::decode::from_read(&mut gz)?;
        let rest = match rmps::decode::from_read(&mut gz) {
            Ok(rest) => rest,
            Err(ref e) if dbg!(is_eof_error(e)) => Default::default(),
            Err(e) => return Err(DeserializationError::RmpSerdeError(e)),
        };
        Ok(Self { part1, rest })
    }
}
```

The second branch of the `match` statement above calls [`is_eof_error`](https://github.com/brave/adblock-rust/blob/94b377ca106dda88d301d6089639271daea1117a/src/utils.rs#L162-L173) to determine whether or not an error reported by `rmp_serde` is an EOF error:

```rust
pub(crate) fn is_eof_error(e: &rmp_serde::decode::Error) -> bool {
    if let rmp_serde::decode::Error::InvalidMarkerRead(e) = e {
        if e.kind() == std::io::ErrorKind::UnexpectedEof {
            if let Some(e) = e.get_ref() {          // <-- Changed in Nightly
                if format!("{}", e) == "failed to fill whole buffer" {
                    return true;
                }
            }
        }
    }
    false
}
```

Up until I recently updated my Nightly Rust toolchain, these tests have been passing for a long time.

Now, the tests fail because the [`e.get_ref()` line](https://github.com/brave/adblock-rust/blob/94b377ca106dda88d301d6089639271daea1117a/src/utils.rs#L165) has started to return `None`.

The tests in question can be run directly by cloning [this repo](https://github.com/brave/adblock-rust), selecting a commit _before_ https://github.com/brave/adblock-rust/commit/6d1c02d56675a659e6f850b76c8ead20ff0a7700 and running:

```
cargo test engine::tests::deserialization_backwards_compatible
```

### Version it worked on

It most recently worked on: Rust 1.52.0-beta (69767412a 2021-04-21)

### Version with regression

`rustc --version --verbose`:
```
rustc 1.53.0-nightly (b84932674 2021-04-21)
binary: rustc
commit-hash: b849326744a8eec939e592f0ab13bff85cc865d3
commit-date: 2021-04-21
host: x86_64-unknown-linux-gnu
release: 1.53.0-nightly
LLVM version: 12.0.0
```

@rustbot modify labels: +regression-from-stable-to-nightly -regression-untriaged

**Comment by jonas-schievink** [comment]
The exact chain of I/O errors the standard library produces are not really part of our stability guarantees. It also is not a very good idea to check the string representation of the error, since that can also freely change between Rust versions.

**Comment by antonok-edm** [comment]
> The exact chain of I/O errors the standard library produces are not really part of our stability guarantees.

Gotcha. I wasn't sure, but I figured it was worth raising just in case the change wasn't intentional.

> It also is not a very good idea to check the string representation of the error, since that can also freely change between Rust versions.

Totally agree; unfortunately it looks like that particular error is represented internally as a string (`Repr::SimpleMessage`), and the only non-deprecated way of retrieving it is through the `Display` and `Debug` implementations on `std::io::Error`...

**Comment by jyn514** [comment]
> Totally agree; unfortunately it looks like that particular error is represented internally as a string (Repr::SimpleMessage), and the only non-deprecated way of retrieving it is through the Display and Debug implementations on std::io::Error...

Is there a reason you needed to look at the string in the first place? Looking at the implementation, it seems like it's *only* used for display, it doesn't change depending on why the error happened:
```
> rg 'UnexpectedEof, ' library/
library/std/src/sys/unix/ext/fs.rs
112:            Err(io::Error::new_const(io::ErrorKind::UnexpectedEof, &"failed to fill whole buffer"))

library/std/src/sys/wasi/ext/fs.rs
88:            Err(io::Error::new_const(io::ErrorKind::UnexpectedEof, &"failed to fill whole buffer"))

library/std/src/io/mod.rs
432:        Err(Error::new_const(ErrorKind::UnexpectedEof, &"failed to fill whole buffer"))

library/std/src/io/impls.rs
266:            return Err(Error::new_const(ErrorKind::UnexpectedEof, &"failed to fill whole buffer"));
```
```

**Comment by jyn514** [comment]
> If the string message is really only for display and is invariant for a given ErrorKind, it'd be great to call it out in the docs (short of making breaking type changes, of course smile).

Ok great, that sounds like a good PR if you want to make one :) I'm going to close this in the meanwhile since the exact chain of errors isn't covered by the stability guarantee.
