### ISSUE TITLE
Tracking Issue for feature(unix_chroot)

### ISSUE THREAD

**Issue by joshtriplett** [rust-lang/rust#84715]
Feature gate: `#![feature(unix_chroot)]`

This is a tracking issue for the `unix_chroot` feature, which adds `std::os::unix::fs::chroot` to change the root directory of the current process.

### Public API

```rust
// std::os::unix::fs
pub fn chroot<P: AsRef<Path>>(dir: P) -> io::Result<()>
```

### Steps / History

- [x] Implementation: #84716
- [x] Final commenting period (FCP): https://github.com/rust-lang/rust/pull/88177#issuecomment-902430723
- [x] Stabilization PR: https://github.com/rust-lang/rust/pull/88177

**Comment by jplatte** [comment]
Boxes can be ticked and tracking issue closed :)
