### ISSUE TITLE
Index out of bounds when running `cargo doc` in `rustc_metadata/src/creader.rs`

### ISSUE THREAD

**Issue by XAMPPRocky** [rust-lang/rust#84738]
EDIT(camelid): This issue is now being used to track a different, but related, bug. The discussion starting [here](https://github.com/rust-lang/rust/issues/84738#issuecomment-950370740) is current.

### Steps

- Clone [`rust-gpu`](https://github.com/EmbarkStudios/rust-gpu/tree/2f451ee9939c021b54214d2aeb986ecb7a6d7382).
- `cargo doc -p spirv-std --no-deps`

### Meta

`rustc --version --verbose`:
```
rustc 1.53.0-nightly (42816d61e 2021-04-24)
binary: rustc
commit-hash: 42816d61ead7e46d462df997958ccfd514f8c21c
commit-date: 2021-04-24
host: x86_64-apple-darwin
release: 1.53.0-nightly
LLVM version: 12.0.0
```

### Error output

```
thread 'rustc' panicked at 'index out of bounds: the len is 8 but the index is 8', compiler/rustc_metadata/src/creader.rs:137:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

error: Unrecognized option: 'crate-version'

error: could not document `spirv-std`

Caused by:
  process didn't exit successfully: `rustdoc --edition=2018 --crate-type lib --crate-name spirv_std crates/spirv-std/src/lib.rs -o /Users/erin.power/src/rust-gpu2/target/doc --cfg 'feature="default"' --error-format=json --json=diagnostic-rendered-ansi -L dependency=/Users/erin.power/src/rust-gpu2/target/debug/deps --extern bitflags=/Users/erin.power/src/rust-gpu2/target/debug/deps/libbitflags-7c13a8e06c86cae3.rmeta --extern num_traits=/Users/erin.power/src/rust-gpu2/target/debug/deps/libnum_traits-226168b7b64579d8.rmeta --extern spirv_std_macros=/Users/erin.power/src/rust-gpu2/target/debug/deps/libspirv_std_macros-63f1f4de237cb2bc.dylib --extern spirv_types=/Users/erin.power/src/rust-gpu2/target/debug/deps/libspirv_types-7559b6c8fd9bbf59.rmeta --crate-version 0.4.0-alpha.7` (exit status: 1)
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic_bounds_check
   3: rustc_metadata::rmeta::decoder::cstore_impl::provide_extern::crate_name
   4: rustc_query_system::dep_graph::graph::DepGraph<K>::with_task_impl
   5: rustc_data_structures::stack::ensure_sufficient_stack
   6: rustc_query_system::query::plumbing::force_query_with_job
   7: rustc_query_system::query::plumbing::get_query_impl
   8: <rustc_query_impl::Queries as rustc_middle::ty::query::QueryEngine>::crate_name
   9: rustdoc::clean::inline::record_extern_fqn
  10: rustdoc::clean::utils::register_res
  11: rustdoc::passes::collect_intra_doc_links::LinkCollector::resolve_link
  12: <rustdoc::passes::collect_intra_doc_links::LinkCollector as rustdoc::fold::DocFolder>::fold_item
  13: alloc::vec::source_iter_marker::<impl alloc::vec::spec_from_iter::SpecFromIter<T,I> for alloc::vec::Vec<T>>::from_iter
  14: rustdoc::fold::DocFolder::fold_inner_recur
  15: rustdoc::fold::DocFolder::fold_item_recur
  16: <rustdoc::passes::collect_intra_doc_links::LinkCollector as rustdoc::fold::DocFolder>::fold_item
  17: rustdoc::passes::collect_intra_doc_links::collect_intra_doc_links
  18: rustdoc::core::run_global_ctxt
  19: rustc_interface::passes::QueryContext::enter
  20: rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter
  21: rustc_span::with_source_map
  22: rustc_interface::interface::create_compiler_and_run
  23: rustdoc::main_options
  24: scoped_tls::ScopedKey<T>::set
```

</p>
</details>

**Comment by jyn514** [comment]
@XAMPPRocky this is probably related to #83761 somehow. I don't plan to investigate any of the proximate issues until the underlying problem is fixed. Feel free to take a look yourself if this is blocking your work, but it won't be easy.

**Comment by jyn514** [comment]
Oh, I guess this could also be a missed case from https://github.com/rust-lang/rust/pull/83738. That should be easier to fix.

**Comment by jyn514** [comment]
If you can come up with an MCVE it would be easier to tell which of the two issues it is.

**Comment by mautamu** [comment]
Not exactly an MCVE, but I think I'm able to reproduce this with only a handful of files @jyn514. The line 
```thread 'rustc' panicked at 'index out of bounds: the len is 8 but the index is 8', compiler/rustc_metadata/src/creader.rs:137:21```
 does change slightly though:
```thread 'rustc' panicked at 'index out of bounds: the len is 20 but the index is 20', compiler/rustc_metadata/src/creader.rs:137:21```

https://github.com/mautamu/spirv-std-3

(Same rustc version output as above).

**Comment by jyn514** [comment]
> DEBUG rustdoc::passes::collect_intra_doc_links combined_docs=[`ImageFormat`]: spirv_types::image_params::ImageFormat
> DEBUG rustdoc::passes::collect_intra_doc_links resolving spirv_types::image_params::ImageFormat as a macro in the module DefId(19:0 ~ spirv_std_macros[a0e2])

I think the issue is that the crate is first used in a dependency, so it isn't loaded in https://github.com/rust-lang/rust/blob/e327a823d8b64e294e490efeca7829f383aa119d/src/librustdoc/passes/collect_intra_doc_links/early.rs#L30-L31

Maybe a fix is to recursively traverse the docs of re-exports? That sounds kind of expensive, but the only other option (besides fixing #83761) is to revert and re-open https://github.com/rust-lang/rust/issues/68427.

**Comment by jyn514** [comment]
An easy workaround is to link to `spirv_types` somewhere in the crate re-exporting the docs, even something like this would work:

```diff
diff --git a/src/lib.rs b/src/lib.rs
index d4de24e..81c278f 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -1 +1,5 @@
 pub use spirv_std_macros::Image;
+
+#[doc(hidden)]
+/// [spirv_types]
+pub fn workaround_rustdoc_ice_84738() {}
```

**Comment by jyn514** [comment]
Hmm, this setup didn't reproduce the issue, not sure why:
```
inner/src/lib.rs:
/// Some docs from original crate
pub fn bar() {}
outer/src/lib.rs:
/// [inner::bar]
pub fn foo() {}
re_export/src/lib.rs:
pub use outer::foo;
```

**Comment by jyn514** [comment]
Maybe the proc macro is related somehow?

**Comment by hameerabbasi** [comment]
********************************************************************************
Regression in 640ce99bfe70375a24c6775a937d6a258b40398b
********************************************************************************

searched nightlies: from nightly-2021-01-01 to nightly-2021-04-24
regressed nightly: nightly-2021-04-04
searched commits: from https://github.com/rust-lang/rust/commit/138fd56cf9598b4bf016634c768dca128a83a5d7 to https://github.com/rust-lang/rust/commit/0b417ab5cdfdedffd74fb22cf22d27033c851304
regressed commit: https://github.com/rust-lang/rust/commit/640ce99bfe70375a24c6775a937d6a258b40398b

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.0</summary>


Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --test-dir=. --start=2021-01-01 --script=./script.sh
```
</details>

That's #83738, good guess, @jyn514.

**Comment by pietroalbini** [comment]
This regression now slipped into beta 1.53.0.

**Comment by jyn514** [comment]
@Aaron1011 came up with a slightly smaller reproduction, the proc macro wasn't related: https://github.com/Aaron1011/spirv-std-3/tree/no-macro

**Comment by TheBlueMatt** [comment]
We've also run into this recently with a rather trivial crate https://docs.rs/crate/lightning-background-processor/0.0.98

**Comment by Mark-Simulacrum** [comment]
This is likely to hit stable, as no beta-accepted patch appears available at this time.

**Comment by TheBlueMatt** [comment]
Is there an easy way to help bisect to figure out which PR to revert, or otherwise help along this issue? It’d be somewhat sad for our five-method create to not have docs even on stable.

**Comment by jyn514** [comment]
@TheBlueMatt you can use the workaround I mentioned at the top: https://github.com/rust-lang/rust/issues/84738#issuecomment-831249933

https://github.com/rust-lang/rust/pull/83738 is the PR to revert; I'm not wholly opposed to doing so but it means reintroducing other regressions.

**Comment by TheBlueMatt** [comment]
This now occurs on stable and should likely be tagged `regression-from-stable-to-stable`, I assume.

**Comment by jonhoo** [comment]
A note to others who stumble upon this, the workaround in https://github.com/rust-lang/rust/issues/84738#issuecomment-831249933 works great; to figure out which crate(s) you need to list, run:

```
env RUSTDOC_LOG=info cargo doc --no-deps
```

Look for the last log message before the panic — in my case, that was:

```
INFO rustc_metadata::creader resolving crate `bytes`
```

Adding `/// [bytes]` fixed the problem.

**Comment by jyn514** [comment]
`RUSTDOC_LOG=rustc_metadata::creader=info` should give you a lot less logging.

**Comment by petrochenkov** [comment]
Further minimized from https://github.com/rust-lang/rust/issues/84738#issuecomment-850989199 and turned into a rustdoc test form:
```rust
// src\test\rustdoc\auxiliary\proc-macro-dep.rs

pub struct SomeStruct;
```
```rust
// src\test\rustdoc\proc-macro-with-external-link.rs

// force-host
// no-prefer-dynamic
// compile-flags: --crate-type proc-macro --extern proc_macro_dep
// aux-build:proc-macro-dep.rs

extern crate proc_macro;

/// [`SomeStruct`]
///
/// [`SomeStruct`]: proc_macro_dep::SomeStruct
#[proc_macro]
pub fn the_macro(input: proc_macro::TokenStream) -> proc_macro::TokenStream {
    input
}
```
```
stdout:
------------------------------------------

------------------------------------------
stderr:
------------------------------------------
thread 'rustc' panicked at 'index out of bounds: the len is 18 but the index is 18', compiler\rustc_metadata\src\creader.rs:146:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.56.0-dev running on x86_64-pc-windows-gnu

note: compiler flags: --crate-type proc-macro

query stack during panic:
#0 [crate_name] fetching what a crate is named
end of query stack

------------------------------------------
```

**Comment by jyn514** [comment]
@petrochenkov thanks for the reduction, that helped a lot. The problem is that rustdoc is considering each line on its own, when it should be considering the whole documentation for the item at once:
```
[src/librustdoc/passes/collect_intra_doc_links/early.rs:31] &doc.as_str() = " [SomeStruct]"
```
When there's a reference link, rustdoc will see the link text instead of the link target:
```
[src/librustdoc/passes/collect_intra_doc_links/early.rs:32] &link = MarkdownLink {
    kind: ShortcutUnknown,
    link: "SomeStruct",
    range: 2..12,
}
```
The fix is to use `item.attrs.collapsed_doc_value_by_module_level()` in `visit_item` instead of visiting each attribute one by one.

**Comment by drewcrawford** [comment]
Also seeing this in another project in 1.56 stable.  Would put together a reproducer but there already is one.

**Comment by jyn514** [comment]
@drewcrawford If you could minimize the crash that would be helpful, the one at the top was already fixed by https://github.com/rust-lang/rust/pull/88215

**Comment by drewcrawford** [comment]
I've reduced it to https://github.com/drewcrawford/rustc-84738.  Still seems a bit large but having trouble getting it any smaller.

This reproducer involves https://github.com/rust-lang/cargo/issues/6313. I suspect that is the root cause in this case, not sure if that tracks with the other reports.

**Comment by jyn514** [comment]
@drewcrawford how can I build that package? running `cargo doc` gives me
```
warning: gcc: error: src/hard-exception.m: Objective-C compiler not installed on this system

error: failed to run custom build command for `objr v0.1.0 (https://github.com/drewcrawford/objr#84d444b4)`
```
even though I have gcc installed.

**Comment by drewcrawford** [comment]
The dependency is macOS only. GitHub runners can do it. 

There is probably a way to shrink the dependency enough to build on some other platform, can look into it a bit more

**Comment by drewcrawford** [comment]
@jyn514 Updated to ICE on windows, which I suspect is enough for linux as well.  May require `cargo clean` or `cargo update`

**Comment by jyn514** [comment]
Hmm, so something strange is going on here - I [minimized](https://github.com/jyn514/objr) @drewcrawford's example a little more, down to four local crates:
```
$ fd --maxdepth 1 .
README.md
REPRODUCE.sh
coregraphicsr
corevideor
objr
objr-upstream
```
If `objr-upstream` has the contents of https://github.com/drewcrawford/objr/tree/winbuild, then the issue reproduces correctly, but if it's anything smaller, then `coregraphicsr` documents fine. At first I suspected the crate hash was different or something, but cargo is passing different `-C metadata` hashes even when `objr` and `objr-upstream` are identical, so that's not it.

**Comment by jyn514** [comment]
@drewcrawford FWIW you can work around the ICE with this diff:
```diff
diff --git a/src/objcinstance.rs b/src/objcinstance.rs
index f876cd5..1264f19 100644
--- a/src/objcinstance.rs
+++ b/src/objcinstance.rs
@@ -126,7 +126,7 @@ pub trait ObjcInstanceBehavior {
     ///Safely casts the object to an `Option<NonNullImmutable>`.  Suitable for implementing nullable functions.
     fn nullable(ptr: *const Self) -> Option<NonNullImmutable<Self>>;
 
-    ///Allows you to call [objr::bindings::PerformsSelector::perform] from a nonmutating context.
+    ///Allows you to call [crate::bindings::PerformsSelector::perform] from a nonmutating context.
     ///
     /// This function should not be used for general-purpose pointer casting.
     ///
```

**Comment by drewcrawford** [comment]
Really interesting workaround!  Those ought to be the same due to https://github.com/rust-lang/rust/issues/56409, maybe there’s some interaction there?

**Comment by jyn514** [comment]
@drewcrawford see https://github.com/rust-lang/rust/issues/83761

**Comment by jyn514** [comment]
MCVE: https://github.com/rust-lang/rust/pull/90489#issuecomment-962858127
