### ISSUE TITLE
`clone_from_slice` doc can be updated after specialization

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#84736]
Current `clone_from_slice` doc says that the user might prefer to use `copy_from_slice` for `Copy` types, but since #81854 we automatically take care of this with specialization. We can consider to clarify docs.

The most careful action would be to let the current docs stand, if we don't want to say anything about the implementation details. I would prefer to remove the sentence about `copy_from_slice`, or something similar.

**Comment by the8472** [comment]
Do the docs currently admit any optimizations that happen through specialization? The only one that I can think of is the zero-optimization in `vec!`, and even that hedges with a "may be".
