### ISSUE TITLE
Can't create a package for a library

### ISSUE THREAD

**Issue by abdelmonem17** [rust-lang/rust#84773]
I have compiler errors when I try to call a 'cargo package' and this is because I use a build script in this library to generate rust code using tonic-build  so I there a way to solve this problem to run build.rs when using 'cargo package'.
Thank you in advance.

**Comment by jonas-schievink** [comment]
Hi! This issue tracker is mainly meant for bug reports and concrete, small feature requests. Questions like this are better asked in the user forum at https://users.rust-lang.org/ or on [one of the chat platforms](https://www.rust-lang.org/community) used by the Rust community.
