### ISSUE TITLE
rustdoc: implementations are starting contracted

### ISSUE THREAD

**Issue by AaronKutch** [rust-lang/rust#84798]
I updated Rust nightly to `rustc 1.53.0-nightly (42816d61e 2021-04-24)` after a long break and found that some recent change to rustdoc is making all my documentation start contracted. I have this complicated crate with several impl blocks spread across several files, and previously the documentation would look like this:
![image](https://user-images.githubusercontent.com/32419308/116796211-763b0200-aaa0-11eb-82ae-22e6207b3d5f.png)

but now looks like this:
![image](https://user-images.githubusercontent.com/32419308/116796246-9965b180-aaa0-11eb-8348-c644c25cb96f.png)

If I want to quickly scan through all the sections, I have to click every single section and expand them every time I open up that documentation page. I think I could see a reason for changing the non-trait impls to also start contracted as default, but now there are no bold titles delimiting the different sections (`Miscellanious`, `Multiplication`, `Division`, etc). I think there needs to be some kind of attribute to make impls expanded by default and/or some way to hoist the impl titles on the different impls.

**Comment by jyn514** [comment]
Fixed by #84552
