### ISSUE TITLE
Rust Learning Zone (weekly competitions)

### ISSUE THREAD

**Issue by arekbulski** [rust-lang/rust#84807]
Hello everyone. On behalf of Hackerspace Lodz Poland I would like to invite you all to our two new channels, Rust Learning Zone (and also Python Learning Zone). We are learning together and regularly do competitions (every week, from Monday to Friday). This week has the 7th competition.

(Telegram chats)
RUST ZONE: https://t.me/joinchat/MMF-5_t8Nes4ODNk
PYTHON ZONE: https://t.me/joinchat/WHE7gcaUj4lhMzA0

**Comment by jonas-schievink** [comment]
This is an issue tracker
