### ISSUE TITLE
ICE: "Missing span for DefIndex" on `pub macro_rules`

### ISSUE THREAD

**Issue by Lokathor** [rust-lang/rust#84810]
Compiling gba v0.4.0 (D:\dev\gba)
thread 'rustc' panicked at 'Missing span for DefIndex(967)', compiler\rustc_metadata\src\rmeta\decoder.rs:715:32
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.53.0-nightly (42816d61e 2021-04-24) running on x86_64-pc-windows-msvc

note: compiler flags: -Z unstable-options -C panic=abort -C embed-bitcode=no -C debuginfo=2 -C incremental -C link-arg=-Tlinker.ld --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `gba`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: build failed
[Finished running. Exit status: 0]

Repo state when the ICE happened: <https://github.com/rust-console/gba/tree/8f4847306d2ced104f7e59b7bd932c40e0ba6a48>

**Comment by Lokathor** [comment]
This is *very likely* related to [pub macro rules](https://github.com/rust-lang/rust/issues/78855), because it's what i most recently added before the ICE, and when I take it out the ICE goes away.

**Comment by jyn514** [comment]
@Lokathor can you paste a backtrace of the ICE?

**Comment by crlf0710** [comment]
That functionality is reverted in #83713 .

**Comment by jyn514** [comment]
Closing this since the feature is no longer part of the compiler.
