### ISSUE TITLE
rustdoc pub trait definition source

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#84825]
e.g., the Hasher trait definition source, when expanded, contains "pub" in front of each function. This is not valid Rust, so likely is a bug somewhere.

Appears to have been a regression introduced between 1.49.0 and 1.50.0, based on the Hasher trait docs - https://doc.rust-lang.org/1.50.0/std/hash/trait.Hasher.html.

**Comment by Stupremee** [comment]
This seems to be the same error as #81274

**Comment by Mark-Simulacrum** [comment]
Indeed, closing as duplicate.
