### ISSUE TITLE
Adjust OR_PATTERNS_BACK_COMPAT lint level

### ISSUE THREAD

**Issue by ehuss** [rust-lang/rust#84869]
The [OR_PATTERNS_BACK_COMPAT](https://github.com/rust-lang/rust/blob/c825bc431ee5b815847b9bab693c59c43986fc4b/compiler/rustc_lint_defs/src/builtin.rs#L3177-L3209) lint level should be adjusted for the 2021 edition.  Either the lint should be warn-by-default always, or it should be a 2021 future-incompatible lint.  This is needed to smoothly migrate projects to 2021.

There is some appeal to making it always warn for less confusion, as long as the lint works well.  I think this course needs to be overridable via 2021 migration (see https://github.com/orgs/rust-lang/projects/7#card-59862192), and be aware that projects which support a wide range of rustc versions may be forced to `allow` it.

**Comment by hi-rustin** [comment]
@rustbot claim

Maybe it it should be a 2021 future-incompatible lint?
