### ISSUE TITLE
rustdoc computes array constants but not const generics

### ISSUE THREAD

**Issue by clarfonthey** [rust-lang/rust#84891]
Minimal example, a new crate with `src/lib.rs` set to the below. Run `cargo doc` and then open the page for `Test`.

```rust
pub trait Test {}
pub struct Array<T, const N: usize>([T; N]);

impl Test for [u8; 1 + 1] {}
impl Test for Array<u8, {1 + 1}> {}
```

In the list of implementations of `Test`, it will simplify `[u8; 1 + 1]` to just `[u8; 2]`, but it will leave `Array<u8, {1 + 1}>` as-is instead of converting it to `Array<u8, 2>`, as shown below:

![Screenshot from 2021-05-03 22-04-07](https://user-images.githubusercontent.com/15850505/116953578-a11d8580-ac5b-11eb-88bc-d602c6c138cf.png)

**Comment by jyn514** [comment]
This is https://github.com/rust-lang/rust/issues/82852 I think.

**Comment by clarfonthey** [comment]
Ah, it appears so. This was hard to search for.

**Comment by jyn514** [comment]
No worries, it's hard to find rustdoc issues because they're buried in everything else. Filtering for A-rustdoc usually helps.
