### ISSUE TITLE
Reported patterns not covered in non-exhaustive pattern error (E0004) are incorrect

### ISSUE THREAD

**Issue by QuineDot** [rust-lang/rust#84895]
Given the following code ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=0422011b7f957ede7bbbcd6f8083d24a)):
```rust
fn incorrect_error_message(b: u8) {
    match b {
        1 => {}
        c if c < 1 || c > 4 => {}
    }
}
```

The current output is:
```
error[E0004]: non-exhaustive patterns: `0_u8` and `2_u8..=u8::MAX` not covered
 --> src/lib.rs:2:11
  |
2 |     match b {
  |           ^ patterns `0_u8` and `2_u8..=u8::MAX` not covered
  |
  = help: ensure that all possible cases are being handled, possibly by adding wildcards or more match arms
  = note: the matched value is of type `u8`
```

Ideally the output should look like:
```
error[E0004]: non-exhaustive patterns: `2_u8..=4` not covered
```

Tested via playground on stable, beta, and nightly.

**Comment by hellow554** [comment]
if guards are not directly part of the match pattern, therefore it isn't considered when doing a covered check, as the following example shows:

```
fn foo(a: bool) {
    match a {
        x if x => {}
        false => {}
    }
}
```

```
error[E0004]: non-exhaustive patterns: `true` not covered
 --> src/lib.rs:2:11
  |
2 |     match a {
  |           ^ pattern `true` not covered
  |
  = help: ensure that all possible cases are being handled, possibly by adding wildcards or more match arms
  = note: the matched value is of type `bool`
```

This was always the case and I think there's an issue for that, but I can't find it right now :/ Maybe someone smarter than me finds it and can link it to you.

**Comment by QuineDot** [comment]
Thanks.  Duplicate of issue 72377 or issue 74277 then I guess.  I'll let someone else decide for sure though, as arguably this could be pivoted to an RFE: Make [E0004](https://doc.rust-lang.org/stable/error-index.html#E0004) more explicit regarding match guards.

**Comment by QuineDot** [comment]
After pondering why I thought this would work for a little bit, I realized I was thinking of this:
```
fn expected_error_message(b: u8) {
    match b {
        1 => {}
        0 | 5..=u8::MAX => {}
    }
}
```
Which indeed gives the expected error.  See also issue 67264.  Not sure if it's feasible to make this a compiler hint though.

**Comment by hellow554** [comment]
What do you mean by "this"? Trying to convince the user to convert the `if guard` into a match pattern directly? I don't think that that is feasible, because if guards can be arbitrary complex and I don't think it's worth the time to investigate the expression.

That being said: maybe it would be a good candidate for a clippy lint? E.g. `simple_if_guard_that_could_be_converted_to_match_expression` 😬 You could open a ticket at https://github.com/rust-lang/rust-clippy but I don't think that this issue should be still open. If you have any more questions, please ask them though :)
