### ISSUE TITLE
FCP poll for ErrorKind::OutOfMemory

### ISSUE THREAD

**Issue by joshtriplett** [rust-lang/rust#84916]
I unintentionally merged https://github.com/rust-lang/rust/pull/84744 without first starting an FCP. We'd previously discussed adding more ErrorKind values, but nonetheless this specific change should have gone through FCP. I've opened this issue to check consensus on this change; if there's any issue with it, I'll post a revert.

**Comment by joshtriplett** [comment]
@rfcbot merge

**Comment by BurntSushi** [comment]
One question I had is, other than #84744, where might we use this?

**Comment by joshtriplett** [comment]
@BurntSushi Anywhere that calls `last_os_error()` when `errno` is `ENOMEM` (or the equivalent on Windows). While on Linux it's common to invoke the OOM killer rather than return `ENOMEM`, it's possible to disable that (and some systems do), and other systems *do* return `ENOMEM`. And even on Linux with overcommit and OOM, there are ways to get ENOMEM; for instance, you could get this from `fork()` of a process using a substantial amount of the system's memory, so it could bubble up from `Command`.

**Comment by BurntSushi** [comment]
@joshtriplett Understood. Thanks for explaining that! This SGTM then.
