### ISSUE TITLE
python x.py setup complains about missing ninja

### ISSUE THREAD

**Issue by lopopolo** [rust-lang/rust#84938]
Hi, I'm setting up a checkout of the Rust repository on a Windows machine. I would like to run `x.py setup` to generate a `config.toml` file with the `library` profile. `x.py` aborts due to ninja not being installed, even though this does not appear to be necessary for the library profile because `x.py` fetches pre-built copies of LLVM.

To work around this I had to copy the example config and manually modify the ninja setting to false. Running `x.py setup` again returns an error since the config file already exists, although it does suggest setting a top-level `profile` key.

This is a speedbump on the road to contributing.

**Comment by jyn514** [comment]
Note: to reproduce this, run `x setup library` (the error only occurs after the prompt for which profile).

**Comment by kornelski** [comment]
I've ran into this too. It'd be nice if setup could put ninja=false in config.toml automatically. Otherwise it's a funny situation where it requires config.toml in order to create the config.toml.

**Comment by kornelski** [comment]
The error message doesn't say in which section to put `ninja=false` in! Just `ninja=false` alone in the file causes a TOML parse error. I've tried putting it in a `[build]` section, but it didn't like it either.

**Comment by jyn514** [comment]
@kornelski it goes in the llvm section
