### ISSUE TITLE
Unhelpful error message and cycles with `const_evaluatable_checked`

### ISSUE THREAD

**Issue by WorldSEnder** [rust-lang/rust#84971]
Given the following code: [playground link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=7d1e0970edea37e3b65923ecc8a81a57)

```rust
#![feature(const_generics, const_evaluatable_checked)]

trait FiniteGroup : Sized {
    const group_size: usize;
    const elems: [Self; Self::group_size];
}

impl FiniteGroup for () {
    const group_size: usize = 1;
    const elems: [Self; Self::group_size] = [()];
}
```

Currently the compiler complains

```
error: unconstrained generic constant
 --> src/lib.rs:5:5
  |
5 |     const elems: [Self; Self::group_size];
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: try adding a `where` bound using this expression: `where [(); Self::group_size]:`
```

This is problematic:
- it is not clear where to put the suggested `where` bound. The parser errors when put behind `elems:` or before the final `;`. Maybe I'm missing something obvious?
- the suggested expression is incomplete, and most likely missing a `: Sized`

Possible related to #80976, #82934 and #82509 but additionally, the bound is required on the trait's *own* associated constant, not in an impl, a struct or construction related to the trait.

Note: I believe correct code would look like

```rust
trait FiniteGroup : Sized where [Self; Self::group_size]: Sized {
    const group_size: usize;
    const elems: [Self; Self::group_size];
}
```
but this leads to
```
cycle detected when building an abstract representation for FiniteGroup::{constant#0}

note: ...which requires processing MIR for `FiniteGroup::{constant#0}`...
note: ...which requires unsafety-checking `FiniteGroup::{constant#0}`...
note: ...which requires building MIR for `FiniteGroup::{constant#0}`...
note: ...which requires type-checking `FiniteGroup::{constant#0}`...
note: ...which again requires building an abstract representation for FiniteGroup::{constant#0}, completing the cycle
```

**Comment by BoxyUwU** [comment]
> the suggested expression is incomplete, and most likely missing a : Sized

it's actually not `where T:` is a valid where clause :sweat_smile:

**Comment by WorldSEnder** [comment]
Maybe I did after all incorrectly understand what the compiler was complaining about, and I'm more confused! I thought it was complaining that `[Self; Self::group_size]` can not be used like that as the type for a `const` item, since that would have to be `Sized`.

**Comment by lcnr** [comment]
the cycle error with the where bound is tracked in https://github.com/rust-lang/rust/issues/79356#issuecomment-772179196

and the unclear + confusing error messages are well known. While I don't know whether we have an explicit tracking issue for them, we do keep them in mind and will deal with them as part of  https://github.com/rust-lang/project-const-generics/issues/41.

decided during triage (https://rust-lang.zulipchat.com/#narrow/stream/260443-project-const-generics/topic/.60F-generic_const_exprs.60.20triage/near/287342437) to close this issue as its content is already tracked elsewhere. Still thank you for opening this issue :+1:
