### ISSUE TITLE
`str::split_terminator` is never finished

### ISSUE THREAD

**Issue by WaffleLapkin** [rust-lang/rust#84974]
I tried this code:

```rust
let mut iter = "A..B..".split_terminator('.');
dbg!(&iter); // finished: false (expected)
    
iter.by_ref().for_each(drop);
dbg!(&iter); // finished: false (unexpected)
    
dbg!(iter.next());
dbg!(&iter); // finished: false (unexpected)
```
<details><summary>output</summary>
<p>

```
[src/main.rs:3] &iter = SplitTerminator(
    SplitInternal {
        start: 0,
        end: 6,
        matcher: CharSearcher {
            haystack: "A..B..",
            finger: 0,
            finger_back: 6,
            needle: '.',
            utf8_size: 1,
            utf8_encoded: [
                46,
                0,
                0,
                0,
            ],
        },
        allow_trailing_empty: false,
        finished: false,
    },
)
[src/main.rs:6] &iter = SplitTerminator(
    SplitInternal {
        start: 6,
        end: 6,
        matcher: CharSearcher {
            haystack: "A..B..",
            finger: 6,
            finger_back: 6,
            needle: '.',
            utf8_size: 1,
            utf8_encoded: [
                46,
                0,
                0,
                0,
            ],
        },
        allow_trailing_empty: false,
        finished: false,
    },
)
[src/main.rs:8] iter.next() = None
[src/main.rs:9] &iter = SplitTerminator(
    SplitInternal {
        start: 6,
        end: 6,
        matcher: CharSearcher {
            haystack: "A..B..",
            finger: 6,
            finger_back: 6,
            needle: '.',
            utf8_size: 1,
            utf8_encoded: [
                46,
                0,
                0,
                0,
            ],
        },
        allow_trailing_empty: false,
        finished: false,
    },
)
```

</p>
</details>

I've expected the `finished` flag to be set when the iterator is exhausted, however it isn't.

### Meta

Tested on playground's [stable](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=46a4708ce0c82c8d86e1d3d610e7730f) `1.51.0` and [nightly](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=46a4708ce0c82c8d86e1d3d610e7730f) `1.54.0-nightly (2021-05-05 bacf770f2983a52f31e3)`

### Likely cause

It seems this behaviour is caused by [`allow_trailing_empty: false`](https://github.com/rust-lang/rust/blob/d620ae10709ca3669cda89db8b29afcd9accc188/library/core/src/str/mod.rs#L1350): `SplitInternal` only sets the finished flag if [`allow_trailing_empty: true` or there is something to return](https://github.com/rust-lang/rust/blob/d620ae10709ca3669cda89db8b29afcd9accc188/library/core/src/str/iter.rs#L581-L582).

Should the flag be set unconditionally? Maybe like this?

```rust
if !self.finished {
    self.finished = true;

    if self.allow_trailing_empty || self.end - self.start > 0 {
        return unsafe { ... } 
    }
}

None
```

**Comment by nagisa** [comment]
What's the actual issue? Does the iterator produce the wrong results?

The debug output here is printing out internal implementation details and it is perfectly fine for the implementation to utilize them in whatever way it wishes to do so.

**Comment by WaffleLapkin** [comment]
The issue actually showed up while I was changing `as_str` split methods (see https://github.com/rust-lang/rust/issues/77998#issuecomment-832016351).

The new method returns `None` if `self.finished` and `Some(...)` otherwise. So for exhausted `SplitTerminator` the method  returned `Some("")`, instead of `None`.
