### ISSUE TITLE
src/test/run-make*/coverage* tests should be reimplemented as a custom compiletest

### ISSUE THREAD

**Issue by richkadel** [rust-lang/rust#85009]
The coverage tests (for `-Z instrument-coverage`) are implemented using `Makefile`s and embedded shell scripts, which is fragile.

Some cross-platform issues are unavoidable, but there have been some cross-platform issues, due to differences in the shell scripts and external commands (like `sed`).

Also, there is a known bug in some versions of `make` on `MacOS` that corrupts shell scripts during script interpretation.

Some of these issues could be avoided in the future if the test logic was rewritten/ported to Rust as a `compiletest`.

**Comment by richkadel** [comment]
@tmandry

**Comment by Zalathar** [comment]
I was bitten pretty badly by cross-platform differences in #110942/#111179, so I'm investigating what it would take to integrate the coverage tests into `compiletest` as a new test category.

**Comment by Zalathar** [comment]
There is still one test left in `tests/run-make/coverage-llvmir`, but that's much less complex than the `coverage-reports` tests that were migrated.

It mostly delegates to `$(LLVM_FILECHECK)` anyway, so it seems fine as-is for now.
