### ISSUE TITLE
The source provided from the github repository for each release is not useable to build rust.

### ISSUE THREAD

**Issue by liaiss** [rust-lang/rust#85024]
Hi,

It seems that the sources available in the release/tag part of the github repository, for example, https://github.com/rust-lang/rust/releases/tag/1.47.0

Failed to build (I'm using debian buster):

    ~/rust-1.52.0$ ./x.py build
    error: failed to read `/home/parallels/rust-1.52.0/src/tools/rust-installer/Cargo.toml`

    Caused by:
        No such file or directory (os error 2)
    failed to run: /home/parallels/rust-1.52.0/build/x86_64-unknown-linux-gnu/stage0/bin/cargo build --manifest-path    
    /home/parallels/rust-1.52.0/src/bootstrap/Cargo.toml
    Build completed unsuccessfully in 0:00:00

It seems the cause is that the submodules weren't updated.

**Comment by hellow554** [comment]
To quote @Aaron1011 

> This is a known issue - unfortunately, there isn't a fix for it at the moment. As a workaround, you can run `cargo clean -p <your_crate_name>`, which will allow you to compile it.

@Aaron1011 may it be worth to pin the original issue on the issue page?

**Comment by liaiss** [comment]
@hellow554 Thanks for the answer and sorry for this duplicate one.

**Comment by hellow554** [comment]
... oh I'm so sorry!!! Please reopen the issue. My comment was not intended for this issue. Forget everything I said!

**Comment by liaiss** [comment]
Ah! No worries. I will reopen it. Thanks

**Comment by sfackler** [comment]
Those files are automatically created by github - I don't know think we have any control over how it treats submodules. You should use the source distributions we link here: https://forge.rust-lang.org/infra/other-installation-methods.html#source-code.

**Comment by Dylan-DPC** [comment]
Closing this to clear up the issue tracker. If you or anyone reading this still needs help you can consult the forums, discords, etc for help. Thanks
