### ISSUE TITLE
./x.py clippy builds llvm

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#85047]
`./x.py clippy` builds llvm for some reason while `./x.py check` does not.

https://rust-lang.zulipchat.com/#narrow/stream/122651-general/topic/x.2Epy.20clippy.20builds.20llvm

repo @  e5f83d24aee866a14753a7cedbb4e301dfe5bef5

**Comment by jyn514** [comment]
I can't replicate this.

```
> rm -r build/x86_64-unknown-linux-gnu/llvm/
> x clippy
Updating only changed submodules
Submodules updated in 0.01 seconds
    Finished dev [unoptimized + debuginfo] target(s) in 0.09s
Checking stage0 std artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
    Checking core v0.0.0 (/home/joshua/rustc/library/core)
warning: this `if` has identical blocks
  --> library/unwind/build.rs:13:5
   |
13 | /     {
14 | |         // Build the unwinding from libunwind C/C++ source code.
15 | |         llvm_libunwind::compile();
16 | |     } else if target.contains("x86_64-fortanix-unknown-sgx") {
   | |_____^
```
Are you running into https://github.com/rust-lang/rust/issues/84938 maybe?

**Comment by matthiaskrgr** [comment]
I had it happen to me that after not running `x.py build` for a while, `x.py check` would not build llvm but `x.py clippy` did, mmh.


I have ninja installed and didn't see any errors around that.

**Comment by jyn514** [comment]
Can you post the full output of `x.py clippy` up until you see CMake output?

**Comment by jyn514** [comment]
@matthiaskrgr are you still running into this? I can't fix it if I don't know what's wrong.

**Comment by jyn514** [comment]
I'm going to close this since I haven't been able to reproduce. In practice this should have much less of an impact than it used to since we download LLVM most of the time.
