### ISSUE TITLE
rustdoc tests depend on `tidy` which isn't installed on release builders

### ISSUE THREAD

**Issue by tmandry** [rust-lang/rust#85061]
Note: `tidy` here is the html diff / format tool, not `src/tools/tidy`

From the [1.52 retrospective](https://rust-lang.zulipchat.com/#narrow/stream/241545-t-release/topic/1.2E52.20retrospective): Having this installed would have made it much easier to spot the issue in #84950.

**Comment by jyn514** [comment]
"depend" is not quite correct - tests will pass fine without it, but if they fail the error is very bad.

**Comment by GuillaumeGomez** [comment]
We improved the error message to avoid showing up the HTML diff, so let's say it's less good and more difficult to understand.

**Comment by GuillaumeGomez** [comment]
I think we can close it since it's possible to run rustdoc tests without `tidy` installed.

**Comment by jyn514** [comment]
> "depend" is not quite correct - tests will pass fine without it, but if they fail the error message is very bad.

@GuillaumeGomez this problem is still not solved.

**Comment by GuillaumeGomez** [comment]
Renaming the issue to reflect this then.

**Comment by jyn514** [comment]
@tmandry A simple solution is to just install tidy on the release builders. I don't know how to do that but it's packaged in nearly every distro.

**Comment by lolbinarycat** [comment]
at the very least the "tidy is not installed" message should link to the tool's homepage so it can be installed.

this is especially confusing because of the existence of the tidy tool.
