### ISSUE TITLE
`where <A as B>::X: 'a` is ignored if `A` has multiple constraints (`A: B + C`)

### ISSUE THREAD

**Issue by 71** [rust-lang/rust#85085]
I tried this code:

```rust
trait Join<T, I: Iterator<Item = T>> {
    type Iter: Iterator<Item = T>;

    fn join(i: I) -> Self::Iter;
}

fn test<'a, T: 'a, J: Join<T, Box<dyn Iterator<Item = T> + 'a>> + Join<T, std::iter::Empty<T>>>(
    input: Box<dyn Iterator<Item = T> + 'a>,
) -> Box<dyn Iterator<Item = T> + 'a>
where
    <J as Join<T, Box<dyn Iterator<Item = T> + 'a>>>::Iter: 'a,
{
    Box::new(J::join(input))
}
```

Which leads to a compile-time error:

```
error[E0309]: the associated type `<J as Join<T, Box<dyn Iterator<Item = T>>>>::Iter` may not live long enough
  --> src/lib.rs:13:5
   |
13 |     Box::new(J::join(input))
   |     ^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = help: consider adding an explicit lifetime bound `<J as Join<T, Box<dyn Iterator<Item = T>>>>::Iter: 'a`...
   = note: ...so that the type `<J as Join<T, Box<dyn Iterator<Item = T>>>>::Iter` will meet its required lifetime bounds
```

Removing the second bound on `J` removes the error, even though it is not relevant to the lifetimes. The following code compiles:

```diff
trait Join<T, I: Iterator<Item = T>> {
    type Iter: Iterator<Item = T>;

    fn join(i: I) -> Self::Iter;
}

- fn test<'a, T: 'a, J: Join<T, Box<dyn Iterator<Item = T> + 'a>> + Join<T, std::iter::Empty<T>>>(
+ fn test<'a, T: 'a, J: Join<T, Box<dyn Iterator<Item = T> + 'a>>>(
    input: Box<dyn Iterator<Item = T> + 'a>,
) -> Box<dyn Iterator<Item = T> + 'a>
where
    <J as Join<T, Box<dyn Iterator<Item = T> + 'a>>>::Iter: 'a,
{
    Box::new(J::join(input))
}
```

**Edit**: with `-Zborrowck=mir`, the code compiles as well.

### Why?
Ideally `Join<T>` would not have an `I` generic argument, but `Iter` needs to be parametized by `I` and GATs aren't available yet, so I'm using `Join<T, I>` and functions enumerate which `I`s need to be supported using `Join<T, A> + Join<T, B>`.

### Meta
Reproduces in both stable (1.52) and nightly (1.54). [Playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=4be48a6c5e8e7530c6a95d06567282d9).

### Similar issues
- https://github.com/rust-lang/rust/issues/63253, but here that bound compiles fine on its own, but not with another `+` bound.

**Comment by jieyouxu** [comment]
No longer causes a compile error on latest stable (<https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=6c7c2a3739d66174f6d9f9bb0ac8afc9>).
