### ISSUE TITLE
padding an array, slice or vector

### ISSUE THREAD

**Issue by wearypossum4770** [rust-lang/rust#85083]
### Code

```Rust
pub fn pad_array(arr: &[u32], spaces: u16, padder: &str) -> Vec<String> {
    let mut target: Vec<String> = Vec::with_capacity(spaces as usize);
    let remaining: u16 = spaces - arr.len() as u16;
    for item in arr {
        target.push(item.to_string());
    }
    for _space in remaining..=spaces {
        target.push(padder.to_string());
    }
    target.into()
}
#[cfg(test)]
mod tests {
    use super::pad_array;
    #[test]
    fn test_pad_array() {
        assert_eq!(pad_array(&[1, 2, 3], 5, ""), vec!["1", "2", "3", "", ""]);
    }
}
```

### Meta

`rustc --version --verbose`:
```
<version>
```

### Error output

```
<output>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
```

</p>
</details>
This was my code, i'm trying to Pad an array.

**Comment by jonas-schievink** [comment]
Hi! This issue tracker is mainly meant for bug reports and concrete, small feature requests. Questions like this are better asked in the user forum at https://users.rust-lang.org/ or on [one of the chat platforms](https://www.rust-lang.org/community) used by the Rust community.
