### ISSUE TITLE
`x86_64-sun-solaris` target was removed without warning in Rust 1.52

### ISSUE THREAD

**Issue by jhpratt** [rust-lang/rust#85098]
#82216 removed the _alias_ of `x86_64-sun-solaris` to `x86_64-pc-solaris`, but as far as I can tell did not remove the target itself.

After inquiring on Zulip, it was pointed out that the `sun-solaris` target was demoted to tier three, meaning builds are no longer provided. It appears this was done with no discussion, warning, or even a mention in the release notes.

Given that the `pc-solaris` target hasn't been around for that long (I think? feel free to tell me I'm wrong), I think this change should be reverted. My CI unexpectedly failed after being unable to download the target, and the only solution that wouldn't involve a notable increase in complexity of the CI script is to outright remove the checks for Solaris/Illumos — a let loss for everyone.

cc @Mark-Simulacrum

**Comment by Mark-Simulacrum** [comment]
I think my feeling right now is that we should likely re-enable the sun-solaris target alongside the pc-solaris, I don't think that should be a major problem for CI times or similar.

I will see if we can do this in time for 1.52.1, but if it ends up being harder than expected, I think it's likely that either a) we'll push it out to a 1.52.2 release later in the cycle, or simply leave it to 1.53. For the time being, tagging as 1.53.

**Comment by jhpratt** [comment]
I will note that the change itself is fine, of course, it's the _suddenness_ and _unexpectedness_ of it that caught me by surprise.

**Comment by Mark-Simulacrum** [comment]
I think it is likely true that we'll eventually drop the sun target, but it does seem like we should communicate that change better at least. Certainly the newly merged target tier policy suggests just that:

> A tier 2 target may be demoted or removed if it no longer meets these requirements. Any proposal for demotion or removal will be CCed to the target maintainers, and will be communicated widely to the Rust community before being dropped from a stable release. (The amount of time between such communication and the next stable release may depend on the nature and severity of the failed requirement, the timing of its discovery, whether the target has been part of a stable release yet, and whether the demotion or removal can be a planned and scheduled action.)

**Comment by kulikjak** [comment]
Removal of the older target was certailnly not my intent; if that happened due to #82216, I am sorry.

Both [x86_64_sun_solaris.rs](https://github.com/rust-lang/rust/blob/1.52.0/compiler/rustc_target/src/spec/x86_64_sun_solaris.rs) and [x86_64_pc_solaris.rs](https://github.com/rust-lang/rust/blob/1.52.0/compiler/rustc_target/src/spec/x86_64_pc_solaris.rs) are there and both targets are usable when compiling with `rustc`, but I guess that change to one of `src/ci/docker/...` files might have resulted in artifacts necessary for `rustup` no longer being available.

**Comment by kulikjak** [comment]
I created #85252, which I believe should bring back the ability to `rustup` the old target.

**Comment by Mark-Simulacrum** [comment]
Reopening to track the illumos target work. I'm not sure it's a release blocker, but would like to not lose sight.

**Comment by Mark-Simulacrum** [comment]
The remaining bug in this issue -- the change in the compiler used to build illumos to be based on a -pc- triple, not -sun- here https://github.com/rust-lang/rust/blob/master/src/ci/docker/scripts/illumos-toolchain.sh#L21 is not a release blocker.

**Comment by jhpratt** [comment]
Realistically I don't think there's anything actionable here, so I'm going to go ahead and close this.
