### ISSUE TITLE
Should we remove the `attr_main_fn` since we don't support #[main] right now?

### ISSUE THREAD

**Issue by Becavalier** [rust-lang/rust#85101]
I found in the file **compiler/rustc_passes/src/entry.rs**, we have some places still using `attr_main_fn` which causes a lot of confusion. Wondering should we eliminate these parts of code?

https://github.com/rust-lang/rust/blob/d6d028369be9eb02d219506c0dd662a2f863fc18/compiler/rustc_passes/src/entry.rs#L21

https://github.com/rust-lang/rust/blob/d6d028369be9eb02d219506c0dd662a2f863fc18/compiler/rustc_passes/src/entry.rs#L119-L133

https://github.com/rust-lang/rust/blob/d6d028369be9eb02d219506c0dd662a2f863fc18/compiler/rustc_passes/src/entry.rs#L150-L151

**Comment by jyn514** [comment]
@Becavalier I'd suggest asking this on Zulip, not many people will notice it here.

https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler

**Comment by crlf0710** [comment]
@Becavalier These are still used by test harness generator. But i guess some of the logic details can be simplified.

**Comment by Becavalier** [comment]
Ok, then let me close this ticket. Thx!
