### ISSUE TITLE
Survey on GDSE

### ISSUE THREAD

**Issue by WybeKoper** [rust-lang/rust#85111]
Hey there. 

We are doing a survey on globally distributed software engineering focused on open source projects. If you have some spare time we would really appreciate your response. The form takes about 10 minutes. Thanks in advance!
Survey can be found [here](https://forms.gle/N1TnifRuCYHrCY9JA)

**Comment by jonas-schievink** [comment]
This is an issue tracker, you should probably post this on https://users.rust-lang.org/
