### ISSUE TITLE
rustdoc: clicking line numbers on source view does nothing

### ISSUE THREAD

**Issue by jsha** [rust-lang/rust#85119]
Steps to reproduce:

1. Visit https://doc.rust-lang.org/src/std/io/mod.rs.html or https://doc.rust-lang.org/nightly/src/std/io/mod.rs.html
2. Click a line number.

Expected result:

Line number is highlighted and URL fragment changes.

Actual result:

Nothing happens.

/cc @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
I'll fix this tomorrow.
