### ISSUE TITLE
Show whether a trait is object-safe on its document page

### ISSUE THREAD

**Issue by EFanZh** [rust-lang/rust#85138]
So that it is easy for user to recognize object-safe traits.

**Comment by csmoe** [comment]
https://github.com/rust-lang/rust/blob/2fb1dee14b3eff979f91e99ad034cfe262fc78c3/compiler/rustc_middle/src/ty/mod.rs#L1896
Just query the doc context with a given trait_def_id.

**Comment by vramana** [comment]
@csmoe Can you tell what are the relevant parts of rustdoc that needs to be changed?

**Comment by csmoe** [comment]
@vramana sorry for late rely :)
https://github.com/rust-lang/rust/blob/ac923d94f86a6f7c881ecbedcd0a68d7986a35bd/src/librustdoc/clean/inline.rs#L213-L220
append a `is_object_safety` field to `clean::Trait`, its value can be queried with `tcx.is_object_safe(did)` like `is_auto`.

**Comment by jyn514** [comment]
No, please do not add more fields to Trait. Query `is_object_safe` at the place it is used.

I don't know much about render, @GuillaumeGomez may have suggestions.

**Comment by GuillaumeGomez** [comment]
I'm actually not sure what they want the end result to look like, so I don't know where to tell them to update the code. ;)

**Comment by tsoutsman** [comment]
Could it maybe be a cube icon (like [this](https://thenounproject.com/term/object/2007252/)) to the right of the new `copy item import to clipboard` button? On hover, there would be a tooltip saying `Item is object-safe`. If @vramana doesn't want to work on it I'd be happy to give it a go.

**Comment by jsha** [comment]
Following up from the PR with some UI discussion.

I'd prefer not to add more icons up at the top of the page; we're already a bit crowded with icons. And there's no icon that has a broadly understood meaning of "object safe".

I like the approach in #89553, to write out "This trait is object-safe." But that PR puts it all the way at the top of the page, which is very high priority - and I would say object safety is more medium priority, so it should be lower on the page. One possibility would be to make an `<h2>` subheading in the top-doc docblock, but that results in using a lot of space for this. Our h2's are big!

What about this: Under "Implementors", we could have at the very top "This trait is object safe. Types that implement this trait can be automatically coerced to `dyn Foo`". My reasoning here is that conceptually, `dyn Foo` is somewhat like an implementor of the trait.

**Comment by jyn514** [comment]
> My reasoning here is that conceptually, dyn Foo is somewhat like an implementor of the trait.

I don't think this is necessarily true, you can have a `dyn Foo` that doesn't implement `Foo`. But putting the text under "implementors" seems as good a place as any 👍

**Comment by EFanZh** [comment]
@jyn514 Just out of curiosity, how can I have a `dyn Foo` that doesn’t implement `Foo`?

**Comment by jyn514** [comment]
@EFanZh I don't think that's actually true, I misremembered.

**Comment by jsha** [comment]
We have one 👍🏻 on:

> Under "Implementors", we could have at the very top "This trait is object safe. References to types that implement this trait can be automatically coerced to dyn Foo".

Would anyone else like to weigh in? Good enough to proceed with implementation?

**Comment by GuillaumeGomez** [comment]
Any update on this? :)

**Comment by camelid** [comment]
I'm not sure if it's already been suggested, but what about only showing a note if the trait is _**not**_ object-safe?

**Comment by jsha** [comment]
I like @camelid's suggestion to only show when a trait is _not_ object safe, since that's the more unusual condition. If we do that, it doesn't fit logically under "Implementors" anymore. If we proceed with only marking non-object-safe traits, here are a couple of ideas:

 - Add a section after the top-doc, but before "Implementors", called "Object Safety", and put the text there.
 - Add information to the documentation of any method that causes the trait to be not object-safe.

**Comment by GoldsteinE** [comment]
I think it’s still fine to mention under “Implementors” like “This trait is _not_ object safe: `dyn Trait` doesn’t implement `Trait`”, but I also like the idea of the new section.

I see this issue doesn’t have an assignee currently, can I claim this?

**Comment by GuillaumeGomez** [comment]
You can but since we didn't reach a consensus, any PR would hang around until we reach one.
