### ISSUE TITLE
Tracking Issue for std::io::Seek::rewind()

### ISSUE THREAD

**Issue by ijackson** [rust-lang/rust#85149]
Feature gate: `#![feature(seek_rewind)]`

This is a tracking issue for the convenience method `std::io::Seek::rewind()`.

### Public API

```rust
pub trait Seek {
    /// This is a convenience method, equivalent to `seek(SeekFrom::Start(0))`.
    fn rewind(&mut self) -> Result<()>;
}
```

### Steps / History

- [x] Implementation: #85146
- [x] Final commenting period (FCP)
- [x] Stabilization PR: #86794

### Unresolved Questions

- None yet.

**Comment by m-ou-se** [comment]
@rfcbot merge

**Comment by poliorcetics** [comment]
I missed it completely in nigthlies sadly, else I would have proposed it returns the `u64` of the old offset, because currently it cannot replace `let old_offset = buf.seek(SeekFrom::Start(0))?;`, on the form without assignement.
