### ISSUE TITLE
Include rustc version in crate disambiguator

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rust#85142]
Otherwise with `-Zsymbol-mangling-version=v0` and no `-Cmetadata`, symbols from the same crate compiled with different versions of rustc are named the same. This makes it possible to replace a rust dylib compiled with one version of rustc with one compiled by another version of rustc even if the ABI doesn't match.

The crate disambiguator is calculated at https://github.com/rust-lang/rust/blob/354cc751b74e813f180755fa67bebcb669825755/compiler/rustc_interface/src/util.rs#L500-L531 This should include something like `option_env!("CFG_VERSION").unwrap_or("unknown version")` in the hash. This matches what the version info included in the rustc metadata header.

**Comment by pierwill** [comment]
Looks like this code hash moved. Still looking into what happened.
