### ISSUE TITLE
[deap loop] HashMap remove 

### ISSUE THREAD

**Issue by silence-coding** [rust-lang/rust#85172]
I found the code looping around.  (https://github.com/tokio-rs/tokio/issues/3777)

Rust version linux 1.45.2

![image](https://user-images.githubusercontent.com/32766901/117769622-81dbb500-b266-11eb-8687-cabd80cde7ff.png)

```
(gdb) bt
#0  0x000055eee90b350c in hashbrown::map::HashMap$LT$K$C$V$C$S$GT$::remove::h07f1bbea6c26227c ()
#1  0x000055eee90ae836 in _$LT$hbx..listen..manager..ListenerToken$u20$as$u20$core..ops..drop..Drop$GT$::drop::h607d355d50acee84 ()
#2  0x000055eee8ce9ade in core::ptr::drop_in_place::h9ec6328dcf12b526 ()
#3  0x000055eee8cc7a44 in core::ptr::drop_in_place::h1aeb9ee292cfa4be ()
#4  0x000055eee8d66c7a in tokio::task::core::Core$LT$T$GT$::transition_to_consumed::he3ea2a049faf3a78 ()
#5  0x000055eee85b65f8 in tokio::task::harness::Harness$LT$T$C$S$GT$::do_cancel::hb9a7b03a1c74c851 ()
#6  0x000055eee92367bf in tokio::runtime::thread_pool::worker::GenerationGuard::run::h132b5d9748a652f3 ()
#7  0x000055eee922dfd1 in std::thread::local::LocalKey$LT$T$GT$::with::hc53944dca76bd295 ()
#8  0x000055eee9235ee7 in tokio::runtime::thread_pool::worker::Worker::run::h66bdcf9450037f90 ()
#9  0x000055eee924ecba in tokio::task::core::Core$LT$T$GT$::poll::h37557b3d79ec35ad ()
#10 0x000055eee925490a in tokio::task::harness::Harness$LT$T$C$S$GT$::poll::h62f0931a6dbf0caa ()
#11 0x000055eee923e9fb in tokio::runtime::blocking::pool::Inner::run::h2ddfe0c35845e7d5 ()
```

the fd is RawFd

the code
```
impl<'a> Drop for ListenerToken<'a> {
    fn drop(&mut self) {
        let fd = self.fd;
       self.fd = -1;
            if let Some(key) = {
                let mut lock = self.cm.fds.lock().unwrap();
                lock.used.remove(&fd)
            } {
                info!("{} released", key);
            }
        }
    }
}
```

**dead loop**
0x000055eee90b3510   ->  0x000055eee90b350c

(gdb) stepi
0x000055eee90b3510 in hashbrown::map::HashMap$LT$K$C$V$C$S$GT$::remove::h07f1bbea6c26227c ()
(gdb) stepi
0x000055eee90b3513 in hashbrown::map::HashMap$LT$K$C$V$C$S$GT$::remove::h07f1bbea6c26227c ()
(gdb) stepi
0x000055eee90b3540 in hashbrown::map::HashMap$LT$K$C$V$C$S$GT$::remove::h07f1bbea6c26227c ()
(gdb) stepi
0x000055eee90b3543 in hashbrown::map::HashMap$LT$K$C$V$C$S$GT$::remove::h07f1bbea6c26227c ()
(gdb) stepi
0x000055eee90b3547 in hashbrown::map::HashMap$LT$K$C$V$C$S$GT$::remove::h07f1bbea6c26227c ()
(gdb) stepi
0x000055eee90b354b in hashbrown::map::HashMap$LT$K$C$V$C$S$GT$::remove::h07f1bbea6c26227c ()
(gdb) stepi
0x000055eee90b354f in hashbrown::map::HashMap$LT$K$C$V$C$S$GT$::remove::h07f1bbea6c26227c ()
(gdb) stepi
0x000055eee90b3553 in hashbrown::map::HashMap$LT$K$C$V$C$S$GT$::remove::h07f1bbea6c26227c ()
(gdb) stepi
0x000055eee90b3556 in hashbrown::map::HashMap$LT$K$C$V$C$S$GT$::remove::h07f1bbea6c26227c ()
(gdb) stepi
0x000055eee90b355c in hashbrown::map::HashMap$LT$K$C$V$C$S$GT$::remove::h07f1bbea6c26227c ()
(gdb) stepi
0x000055eee90b34fb in hashbrown::map::HashMap$LT$K$C$V$C$S$GT$::remove::h07f1bbea6c26227c ()
(gdb) stepi
0x000055eee90b34fe in hashbrown::map::HashMap$LT$K$C$V$C$S$GT$::remove::h07f1bbea6c26227c ()
(gdb) stepi
0x000055eee90b3504 in hashbrown::map::HashMap$LT$K$C$V$C$S$GT$::remove::h07f1bbea6c26227c ()
(gdb) stepi
0x000055eee90b3508 in hashbrown::map::HashMap$LT$K$C$V$C$S$GT$::remove::h07f1bbea6c26227c ()
(gdb) stepi
0x000055eee90b350c in hashbrown::map::HashMap$LT$K$C$V$C$S$GT$::remove::h07f1bbea6c26227c ()
(gdb) stepi
0x000055eee90b3510 in hashbrown::map::HashMap$LT$K$C$V$C$S$GT$::remove::h07f1bbea6c26227c ()
(gdb) stepi
0x000055eee90b3513 in hashbrown::map::HashMap$LT$K$C$V$C$S$GT$::remove::h07f1bbea6c26227c ()
(gdb) 

Dump of assembler code for function _ZN9hashbrown3map24HashMap$LT$K$C$V$C$S$GT$6remove17h07f1bbea6c26227cE:
   0x000055eee90b3360 <+0>:	push   %rbp
   0x000055eee90b3361 <+1>:	push   %r15
   0x000055eee90b3363 <+3>:	push   %r14
   0x000055eee90b3365 <+5>:	push   %r12
   0x000055eee90b3367 <+7>:	push   %rbx
   0x000055eee90b3368 <+8>:	sub    $0x60,%rsp
   0x000055eee90b336c <+12>:	mov    %rsi,%r12
   0x000055eee90b336f <+15>:	mov    %rdi,%r14
   0x000055eee90b3372 <+18>:	mov    (%rsi),%rax
   0x000055eee90b3375 <+21>:	mov    0x8(%rsi),%rcx
   0x000055eee90b3379 <+25>:	movq   %rax,%xmm0
   0x000055eee90b337e <+30>:	pshufd $0x44,%xmm0,%xmm0
   0x000055eee90b3383 <+35>:	pxor   0x386d05(%rip),%xmm0        # 0x55eee943a090
   0x000055eee90b338b <+43>:	movq   %rcx,%xmm1
   0x000055eee90b3390 <+48>:	pshufd $0x44,%xmm1,%xmm1
   0x000055eee90b3395 <+53>:	pxor   0x386d03(%rip),%xmm1        # 0x55eee943a0a0
   0x000055eee90b339d <+61>:	mov    %rax,0x10(%rsp)
   0x000055eee90b33a2 <+66>:	mov    %rcx,0x18(%rsp)
   0x000055eee90b33a7 <+71>:	movq   $0x0,0x20(%rsp)
   0x000055eee90b33b0 <+80>:	movdqu %xmm0,0x28(%rsp)
   0x000055eee90b33b6 <+86>:	movdqu %xmm1,0x38(%rsp)
   0x000055eee90b33bc <+92>:	pxor   %xmm0,%xmm0
   0x000055eee90b33c0 <+96>:	movdqu %xmm0,0x48(%rsp)
   0x000055eee90b33c6 <+102>:	mov    (%rdx),%r15d
   0x000055eee90b33c9 <+105>:	mov    %r15d,0xc(%rsp)
   0x000055eee90b33ce <+110>:	lea    0x10(%rsp),%rdi
   0x000055eee90b33d3 <+115>:	lea    0xc(%rsp),%rsi
   0x000055eee90b33d8 <+120>:	mov    $0x4,%edx
   0x000055eee90b33dd <+125>:	callq  0x55eee90a47f0 <_ZN81_$LT$std..collections..hash..map..DefaultHasher$u20$as$u20$core..hash..Hasher$GT$5write17h17162c673e3ea72aE.llvm.11615515210271430001>
   0x000055eee90b33e2 <+130>:	mov    0x20(%rsp),%rdi
   0x000055eee90b33e7 <+135>:	mov    0x38(%rsp),%rax
   0x000055eee90b33ec <+140>:	shl    $0x38,%rdi
   0x000055eee90b33f0 <+144>:	or     0x48(%rsp),%rdi
   0x000055eee90b33f5 <+149>:	mov    0x40(%rsp),%rcx
   0x000055eee90b33fa <+154>:	mov    0x28(%rsp),%rdx
   0x000055eee90b33ff <+159>:	add    %rax,%rdx
   0x000055eee90b3402 <+162>:	rol    $0xd,%rax
   0x000055eee90b3406 <+166>:	xor    %rdi,%rcx
   0x000055eee90b3409 <+169>:	xor    %rdx,%rax
   0x000055eee90b340c <+172>:	rol    $0x20,%rdx
   0x000055eee90b3410 <+176>:	mov    0x30(%rsp),%rsi
   0x000055eee90b3415 <+181>:	add    %rcx,%rsi
   0x000055eee90b3418 <+184>:	rol    $0x10,%rcx
   0x000055eee90b341c <+188>:	xor    %rsi,%rcx
   0x000055eee90b341f <+191>:	add    %rcx,%rdx
   0x000055eee90b3422 <+194>:	rol    $0x15,%rcx
   0x000055eee90b3426 <+198>:	add    %rax,%rsi
   0x000055eee90b3429 <+201>:	rol    $0x11,%rax
   0x000055eee90b342d <+205>:	xor    %rdx,%rcx
   0x000055eee90b3430 <+208>:	xor    %rsi,%rax
   0x000055eee90b3433 <+211>:	rol    $0x20,%rsi
   0x000055eee90b3437 <+215>:	xor    %rdi,%rdx
   0x000055eee90b343a <+218>:	add    %rax,%rdx
   0x000055eee90b343d <+221>:	rol    $0xd,%rax
   0x000055eee90b3441 <+225>:	xor    %rdx,%rax
   0x000055eee90b3444 <+228>:	rol    $0x20,%rdx
   0x000055eee90b3448 <+232>:	xor    $0xff,%rsi
   0x000055eee90b344f <+239>:	add    %rcx,%rsi
   0x000055eee90b3452 <+242>:	rol    $0x10,%rcx
   0x000055eee90b3456 <+246>:	xor    %rsi,%rcx
   0x000055eee90b3459 <+249>:	add    %rcx,%rdx
   0x000055eee90b345c <+252>:	rol    $0x15,%rcx
   0x000055eee90b3460 <+256>:	add    %rax,%rsi
   0x000055eee90b3463 <+259>:	rol    $0x11,%rax
   0x000055eee90b3467 <+263>:	xor    %rsi,%rax
   0x000055eee90b346a <+266>:	rol    $0x20,%rsi
   0x000055eee90b346e <+270>:	xor    %rdx,%rcx
   0x000055eee90b3471 <+273>:	add    %rax,%rdx
   0x000055eee90b3474 <+276>:	rol    $0xd,%rax
   0x000055eee90b3478 <+280>:	xor    %rdx,%rax
   0x000055eee90b347b <+283>:	rol    $0x20,%rdx
   0x000055eee90b347f <+287>:	add    %rcx,%rsi
   0x000055eee90b3482 <+290>:	rol    $0x10,%rcx
   0x000055eee90b3486 <+294>:	xor    %rsi,%rcx
   0x000055eee90b3489 <+297>:	add    %rcx,%rdx
   0x000055eee90b348c <+300>:	rol    $0x15,%rcx
   0x000055eee90b3490 <+304>:	add    %rax,%rsi
   0x000055eee90b3493 <+307>:	rol    $0x11,%rax
   0x000055eee90b3497 <+311>:	xor    %rsi,%rax
   0x000055eee90b349a <+314>:	rol    $0x20,%rsi
   0x000055eee90b349e <+318>:	xor    %rdx,%rcx
   0x000055eee90b34a1 <+321>:	add    %rax,%rdx
   0x000055eee90b34a4 <+324>:	rol    $0xd,%rax
   0x000055eee90b34a8 <+328>:	add    %rcx,%rsi
   0x000055eee90b34ab <+331>:	rol    $0x10,%rcx
   0x000055eee90b34af <+335>:	xor    %rsi,%rcx
   0x000055eee90b34b2 <+338>:	rol    $0x15,%rcx
   0x000055eee90b34b6 <+342>:	xor    %rdx,%rax
   0x000055eee90b34b9 <+345>:	add    %rax,%rsi
   0x000055eee90b34bc <+348>:	rol    $0x11,%rax
   0x000055eee90b34c0 <+352>:	xor    %rsi,%rax
   0x000055eee90b34c3 <+355>:	rol    $0x20,%rsi
   0x000055eee90b34c7 <+359>:	xor    %rsi,%rax
   0x000055eee90b34ca <+362>:	xor    %rcx,%rax
  0x000055eee90b34cd <+365>:	mov    0x10(%r12),%rsi
   0x000055eee90b34d2 <+370>:	mov    0x18(%r12),%r9
   0x000055eee90b34d7 <+375>:	mov    %rax,%rcx
   0x000055eee90b34da <+378>:	shr    $0x39,%rcx
   0x000055eee90b34de <+382>:	movd   %ecx,%xmm0
   0x000055eee90b34e2 <+386>:	punpcklbw %xmm0,%xmm0
   0x000055eee90b34e6 <+390>:	pshuflw $0xe0,%xmm0,%xmm0
   0x000055eee90b34eb <+395>:	pshufd $0x0,%xmm0,%xmm0
   0x000055eee90b34f0 <+400>:	mov    0x20(%r12),%r8
   0x000055eee90b34f5 <+405>:	xor    %edx,%edx
   0x000055eee90b34f7 <+407>:	pcmpeqd %xmm1,%xmm1
   0x000055eee90b34fb <+411>:	and    %rsi,%rax
   0x000055eee90b34fe <+414>:	movdqu (%r9,%rax,1),%xmm2
   0x000055eee90b3504 <+420>:	movdqa %xmm0,%xmm3
   0x000055eee90b3508 <+424>:	pcmpeqb %xmm2,%xmm3
=> 0x000055eee90b350c <+428>:	pmovmskb %xmm3,%ebx
   0x000055eee90b3510 <+432>:	test   %bx,%bx
   0x000055eee90b3513 <+435>:	je     0x55eee90b3540 <_ZN9hashbrown3map24HashMap$LT$K$C$V$C$S$GT$6remove17h07f1bbea6c26227cE+480>
   0x000055eee90b3515 <+437>:	bsf    %bx,%cx
   0x000055eee90b3519 <+441>:	movzwl %cx,%edi
   0x000055eee90b351c <+444>:	add    %rax,%rdi
   0x000055eee90b351f <+447>:	and    %rsi,%rdi
   0x000055eee90b3522 <+450>:	mov    %rdi,%rbp
   0x000055eee90b3525 <+453>:	shl    $0x5,%rbp
   0x000055eee90b3529 <+457>:	cmp    (%r8,%rbp,1),%r15d
   0x000055eee90b352d <+461>:	je     0x55eee90b355e <_ZN9hashbrown3map24HashMap$LT$K$C$V$C$S$GT$6remove17h07f1bbea6c26227cE+510>
   0x000055eee90b352f <+463>:	lea    -0x1(%rbx),%ecx
   0x000055eee90b3532 <+466>:	and    %bx,%cx
   0x000055eee90b3535 <+469>:	mov    %ecx,%ebx
   0x000055eee90b3537 <+471>:	jne    0x55eee90b3515 <_ZN9hashbrown3map24HashMap$LT$K$C$V$C$S$GT$6remove17h07f1bbea6c26227cE+43
   0x000055eee90b3539 <+473>:	nopl   0x0(%rax)
   0x000055eee90b3540 <+480>:	add    %rdx,%rax
   0x000055eee90b3543 <+483>:	add    $0x10,%rax
   0x000055eee90b3547 <+487>:	add    $0x10,%rdx
   0x000055eee90b354b <+491>:	pcmpeqb %xmm1,%xmm2
   0x000055eee90b354f <+495>:	pmovmskb %xmm2,%ecx
   0x000055eee90b3553 <+499>:	test   %cx,%cx
   0x000055eee90b3556 <+502>:	jne    0x55eee90b35ea <_ZN9hashbrown3map24HashMap$LT$K$C$V$C$S$GT$6remove17h07f1bbea6c26227cE+650>
   0x000055eee90b355c <+508>:	jmp    0x55eee90b34fb <_ZN9hashbrown3map24HashMap$LT$K$C$V$C$S$GT$6remove17h07f1bbea6c26227cE+411>
   0x000055eee90b355e <+510>:	lea    -0x10(%rdi),%rax
   0x000055eee90b3562 <+514>:	and    %rsi,%rax
   0x000055eee90b3565 <+517>:	movdqu (%r9,%rax,1),%xmm0
   0x000055eee90b356b <+523>:	pcmpeqd %xmm1,%xmm1
   0x000055eee90b356f <+527>:	pcmpeqb %xmm1,%xmm0
   0x000055eee90b3573 <+531>:	pmovmskb %xmm0,%ecx
   0x000055eee90b3577 <+535>:	movdqu (%r9,%rdi,1),%xmm0
   0x000055eee90b357d <+541>:	pcmpeqb %xmm1,%xmm0
   0x000055eee90b3581 <+545>:	pmovmskb %xmm0,%ebx
   0x000055eee90b3585 <+549>:	mov    $0x10,%si
   0x000055eee90b3589 <+553>:	mov    $0x10,%dx
   0x000055eee90b358d <+557>:	test   %cx,%cx
   0x000055eee90b3590 <+560>:	je     0x55eee90b3599 <_ZN9hashbrown3map24HashMap$LT$K$C$V$C$S$GT$6remove17h07f1bbea6c26227cE+569>
   0x000055eee90b3592 <+562>:	bsr    %cx,%dx
   0x000055eee90b3596 <+566>:	xor    $0xf,%edx
   0x000055eee90b3599 <+569>:	test   %bx,%bx
   0x000055eee90b359c <+572>:	je     0x55eee90b35a2 <_ZN9hashbrown3map24HashMap$LT$K$C$V$C$S$GT$6remove17h07f1bbea6c26227cE+578>
   0x000055eee90b359e <+574>:	bsf    %bx,%si
---Type <return> to continue, or q <return> to quit---
   0x000055eee90b35a2 <+578>:	movzwl %si,%esi
   0x000055eee90b35a5 <+581>:	add    %edx,%esi
   0x000055eee90b35a7 <+583>:	mov    $0x80,%cl
   0x000055eee90b35a9 <+585>:	cmp    $0xf,%si
   0x000055eee90b35ad <+589>:	ja     0x55eee90b35b7 <_ZN9hashbrown3map24HashMap$LT$K$C$V$C$S$GT$6remove17h07f1bbea6c26227cE+599>
   0x000055eee90b35af <+591>:	addq   $0x1,0x28(%r12)
   0x000055eee90b35b5 <+597>:	mov    $0xff,%cl
   0x000055eee90b35b7 <+599>:	mov    %cl,(%r9,%rdi,1)
   0x000055eee90b35bb <+603>:	mov    %cl,0x10(%rax,%r9,1)
   0x000055eee90b35c0 <+608>:	addq   $0xffffffffffffffff,0x30(%r12)
   0x000055eee90b35c6 <+614>:	mov    0x8(%r8,%rbp,1),%rax
   0x000055eee90b35cb <+619>:	movups 0x10(%r8,%rbp,1),%xmm0
   0x000055eee90b35d1 <+625>:	movaps %xmm0,0x10(%rsp)
   0x000055eee90b35d6 <+630>:	test   %rax,%rax
   0x000055eee90b35d9 <+633>:	je     0x55eee90b35ea <_ZN9hashbrown3map24HashMap$LT$K$C$V$C$S$GT$6remove17h07f1bbea6c26227cE+650>
   0x000055eee90b35db <+635>:	mov    %rax,(%r14)
   0x000055eee90b35de <+638>:	movaps 0x10(%rsp),%xmm0
   0x000055eee90b35e3 <+643>:	movups %xmm0,0x8(%r14)
   0x000055eee90b35e8 <+648>:	jmp    0x55eee90b35f1 <_ZN9hashbrown3map24HashMap$LT$K$C$V$C$S$GT$6remove17h07f1bbea6c26227cE+657>
   0x000055eee90b35ea <+650>:	movq   $0x0,(%r14)
   0x000055eee90b35f1 <+657>:	mov    %r14,%rax
   0x000055eee90b35f4 <+660>:	add    $0x60,%rsp
   0x000055eee90b35f8 <+664>:	pop    %rbx
   0x000055eee90b35f9 <+665>:	pop    %r12
   0x000055eee90b35fb <+667>:	pop    %r14
   0x000055eee90b35fd <+669>:	pop    %r15
   0x000055eee90b35ff <+671>:	pop    %rbp
   0x000055eee90b3600 <+672>:	retq   
End of assembler dump.

**Comment by Enselic** [comment]
Triage: Can you still reproduce with the latest versions of everything? If yes, can you please give a complete and minimal program that can be used to reproduce this problem?

**Comment by kpreid** [comment]
Triage: Relabeling issues which don't have a runnable reproduction (as opposed to having a non-minimized one) to the new label S-needs-repro.
@rustbot label +S-needs-repro -E-needs-mcve

**Comment by Nilstrieb** [comment]
Given that there has not been a reproduction, I'm closing this as unactionable. Open a new issue if you see the problem again.
