### ISSUE TITLE
Add gdb pretty printers for slices types (`&[T]` and `&mut [T]`).

### ISSUE THREAD

**Issue by EFanZh** [rust-lang/rust#85219]
Currently, support for pretty-printing slice types is missing for rust-gdb.

**Comment by DaviRain-Su** [comment]
Can you describe in more detail?

**Comment by EFanZh** [comment]
[rust-gdb](https://github.com/rust-lang/rust/blob/master/src/etc/rust-gdb) provides pretty-printing function for some rust types, such as `&str`, `Vec`, `HashMap` etc. This allows gdb to display values of some types in a more readable way. I think it is implemented in the following files:

- <https://github.com/rust-lang/rust/blob/master/src/etc/gdb_lookup.py>,
- <https://github.com/rust-lang/rust/blob/master/src/etc/gdb_providers.py>,
- <https://github.com/rust-lang/rust/blob/master/src/etc/rust_types.py>.

Currently, slices can only be displayed as a pointer and a length value in the debugger. I hope rust-gdb can support displaying slices.

I also noticed that [rust-lldb](https://github.com/rust-lang/rust/blob/master/src/etc/rust-lldb) already supports pretty-printing const slices (`&[T]`), but not mutable slices (`&mut [T]`). Maybe rust-lldb can also add pretty-printing support fur mutable slices.
