### ISSUE TITLE
Diagnostics emitted for disallowed exhaustive matches on types that contain a `usize` lack information about why the match cannot be considered exhaustive

### ISSUE THREAD

**Issue by PatchMixolydic** [rust-lang/rust#85222]
Sorry about the long title :sweat_smile:

Given the following code ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=867f7b4274789ddf7a82ce8154f1e428)):

```rust
fn main() {
    let x: usize = 4;
    let y = Some(x);

    match x {
        0 => (),
        1..=usize::MAX => (),
    }

    match y {
        Some(0) => (),
        Some(1..=usize::MAX) => (),
        None => (),
    }
}
```

The current output is:

```
error[E0004]: non-exhaustive patterns: `_` not covered
 --> src/main.rs:5:11
  |
5 |     match x {
  |           ^ pattern `_` not covered
  |
  = help: ensure that all possible cases are being handled, possibly by adding wildcards or more match arms
  = note: the matched value is of type `usize`
  = note: `usize` does not have a fixed maximum value, so a wildcard `_` is necessary to match exhaustively
  = help: add `#![feature(precise_pointer_size_matching)]` to the crate attributes to enable precise `usize` matching

error[E0004]: non-exhaustive patterns: `Some(_)` not covered
   --> src/main.rs:10:11
    |
10  |     match y {
    |           ^ pattern `Some(_)` not covered
    |
    = help: ensure that all possible cases are being handled, possibly by adding wildcards or more match arms
    = note: the matched value is of type `Option<usize>`
```

Note how the first diagnostic, emitted when matching on a `usize`, contains additional information about why this exhaustive match does not pass the exhaustiveness check. Ideally, this information should be added to the second diagnostic as well:

```
error[E0004]: non-exhaustive patterns: `Some(_)` not covered
   --> src/main.rs:10:11
    |
10  |     match y {
    |           ^ pattern `Some(_)` not covered
    |
    = help: ensure that all possible cases are being handled, possibly by adding wildcards or more match arms
    = note: the matched value is of type `Option<usize>`
    = note: `usize` does not have a fixed maximum value, so a wildcard `_` is necessary to match exhaustively
    = help: add `#![feature(precise_pointer_size_matching)]` to the crate attributes to enable precise `usize` matching
```

@rustbot modify labels: +A-exhaustiveness-checking +A-patterns +D-terse

**Comment by Nadrieril** [comment]
Hm, even though `usize` has a different size on different architectures, `0..usize::MAX` should always be exhaustive, right? Then that code would be accepted, but the following would still error:
```rust
match 0usize {
  0 => {}
  1..=18446744073709551615 => {}
}
```
We could have the error for this say "missing pattern: `18446744073709551616..=usize::MAX`", which would also work if there's a `Some` around it.

That said, pretty sure what you describe also happens for `non_exhaustive` enums too, and there we'll want to do what you suggest.

**Comment by workingjubilee** [comment]
see also #56354

**Comment by Nadrieril** [comment]
I forgot this issue existed, but yeah this is a lint we want. I explained a bit about how this might be done in https://github.com/rust-lang/rust/issues/105479#issuecomment-1496696343, if anhone wants to tackle this feel free to ping me
