### ISSUE TITLE
Mark 1.52.1 as last release on github

### ISSUE THREAD

**Issue by JeanCASPAR** [rust-lang/rust#85235]
Currently, this is displayed ![image](https://user-images.githubusercontent.com/55629512/118030268-5b507380-b365-11eb-8068-3c1dcc7f9a49.png)
And users who click on that don't see 1.52.1 and that this is a fix.

**Comment by cuviper** [comment]
Perhaps its because @rustbot didn't import the release notes for 1.52.1? cc @rust-lang/release

**Comment by Mark-Simulacrum** [comment]
I think I recall a conversation about this - I suspect we can fix it with a backport of the release notes to master and maybe some manual bumping.

**Comment by pietroalbini** [comment]
Backporting the release notes should do the trick. We should do that regardless of this issue too. I'll open a PR.

**Comment by pietroalbini** [comment]
Should be fixed by https://github.com/rust-lang/rust/pull/85404!
