### ISSUE TITLE
Wired runtime error on Windows i686 after upgraded to 1.52

### ISSUE THREAD

**Issue by Brooooooklyn** [rust-lang/rust#85295]
See https://github.com/napi-rs/napi-rs/pull/559

Many invalid pointer values after upgraded, and caused test cases failed.
I tried to build a minimal example to reproduce, but failed.

**Comment by hellow554** [comment]
Can you post the error here and link the relevant build/run log as well? 
Also a specific commit to test would be nice, so we can try to reproduce your error. AS well as the Compiler Version etc... Everything the issue template asks for 😉

**Comment by Brooooooklyn** [comment]
Step to reproduce:

> On windows x64 machine

- Clone the https://github.com/napi-rs/napi-rs
- Run `choco install nodejs-lts -x86 --force`
- Add C:\Program Files (x86)\nodejs into your `PATH`
- Ensure node -v command executes the 32 bit version
- Run `yarn build`
- Run `yarn build:test`
- Run `yarn test --verbose`

Here are 3 different errors after upgraded to the `1.52.1`. Codes are working as expected with `1.51.0`

### Exit code `3221225477`

There are 3 test suites occured this error, and here are functions which may cause this error: 

1. https://github.com/napi-rs/napi-rs/blob/main/napi/src/env.rs#L919
2. https://github.com/napi-rs/napi-rs/blob/main/napi/src/env.rs#L1138
3. https://github.com/napi-rs/napi-rs/blob/main/napi/src/env.rs#L1030

### Invalid value of ptr after passing it into `C ffi function`

See https://github.com/napi-rs/napi-rs/blob/main/napi/src/js_values/mod.rs#L78

The value of `value_type` must be one of `0 - 9`, and the value now is random integer, this error is only occurs in this line https://github.com/napi-rs/napi-rs/blob/main/napi/src/js_values/de.rs#L23

### exit code `3221226356`

It also occures in https://github.com/napi-rs/napi-rs/blob/main/napi/src/js_values/de.rs#L23

**Comment by Brooooooklyn** [comment]
Everything back to fine after switched to `nightly-x86_64-pc-windows-msvc unchanged - rustc 1.54.0-nightly (fe72845f7 2021-05-16)`

So this problem only appear in `v1.52`
