### ISSUE TITLE
Sponsorship & trademark policy needs updating to reflect Rust Foundation

### ISSUE THREAD

**Issue by cbeuw** [rust-lang/rust#85291]
It's my understanding that the Rust and Cargo trademark has been transerred to the recently founded Rust Foundation, and Mozilla is no longer directly sponsoring the Rust project, but through the Foundation along with its other members.

The "Trademark" section of `README.md` still reads
>The Rust programming language is an open source, community project governed by a core team. It is also sponsored by the Mozilla Foundation (“Mozilla”), which owns and protects the Rust and Cargo trademarks and logos (the “Rust Trademarks”).

Similar sentences are also found on the Rust website.
https://www.rust-lang.org/policies/media-guide

They should be updated to reflect the recent changes

**Comment by saethlin** [comment]
It looks to me like this was fixed by https://github.com/rust-lang/rust/pull/85504 and I don't see any language about Mozilla at the URL in the issue description.
