### ISSUE TITLE
`char::is_alphabetic`'s signature differs from `char::is_ascii_alphabetic`

### ISSUE THREAD

**Issue by r00ster91** [rust-lang/rust#85300]
[`char::is_alphabetic`](https://doc.rust-lang.org/stable/std/primitive.char.html#method.is_alphabetic) takes `self` but [`char::is_ascii_alphabetic`](https://doc.rust-lang.org/stable/std/primitive.char.html#method.is_ascii_alphabetic) takes `&self`.
This creates some inconsistencies. For instance:
```rust
fn main() {
    "hello".chars().all(char::is_alphabetic) // works
    "hello".chars().all(char::is_ascii_alphabetic) // does not work
}
```
```
error[E0631]: type mismatch in function arguments
 --> src/main.rs:2:25
  |
2 |     "hello".chars().all(char::is_ascii_alphabetic);
  |                         ^^^^^^^^^^^^^^^^^^^^^^^^^
  |                         |
  |                         expected signature of `fn(char) -> _`
  |                         found signature of `for<'r> fn(&'r char) -> _`
```
They shouldn't differ because they behave very similarly.
I believe it's better to make both have the same signature if possible. Either both take `self` or both take `&self`.
I think there is many more such inconsistencies to be found in https://doc.rust-lang.org/stable/std/primitive.char.html and probably other types that implement `Copy`.

**Comment by Mark-Simulacrum** [comment]
I don't think it would be backwards compatible to change this at this point, precisely because of code like you wrote in your example, so I don't think any changes here are feasible on stabilized methods. Thanks!

**Comment by r00ster91** [comment]
@Mark-Simulacrum I thought maybe it could be changed in a new edition but I suppose it's still too big of a breaking change.

**Comment by Mark-Simulacrum** [comment]
Editions are not generally well-suited to library-level changes, as all editions ultimately see the same standard library.
