### ISSUE TITLE
get type id from the trait object

### ISSUE THREAD

**Issue by peacess** [rust-lang/rust#85314]
pub fn get_data_type_id() TypeId
if add the fn , then we can safety convert trait1 object to trait2 object
trait1 object include data and vtable1  
trait2 object include data and vtable2

data + vtable1 + get_data_type_id() + trait2 ==>(safety) trait2 object

**Comment by bjorn3** [comment]
There are multiple ways to support downcasting trait objects to different trait objects. Each has different advantages and disadvantages. There has been a lot of discussion about this in the past, but no proposal has been accepted yet. By the way internals.rust-lang.org is a more suitable location to discuss changes to the rust language.

**Comment by jonas-schievink** [comment]
Hi! Additions or changes to the language need to go through our [RFC process](https://github.com/rust-lang/rfcs). Before an RFC is written, the feature can also be discussed in our [internals forum](https://internals.rust-lang.org/) to find other people interested in it.

Closing in favor of an RFC.

**Comment by jonas-schievink** [comment]
Trait object *up*casting on the other hand is currently being implemented in https://github.com/rust-lang/rust/pull/86264
