### ISSUE TITLE
Undefined behavior allowed in associated constants

### ISSUE THREAD

**Issue by ATiltedTree** [rust-lang/rust#85336]
I tried this code:

```rust
const F: &'static u8 = unsafe { std::mem::transmute::<_,_>(0xbeefbeef as *const u8) };

fn main() {}
```

I expected to see this happen:

It should compile and `F` should be a reference to the `u8` at `0xbeefbeef`.

Instead, this happened:

It doesn't compile throwing this error:
```
error[E0080]: it is undefined behavior to use this value
 --> con.rs:1:1
  |
1 | const F: &'static u8 = unsafe { std::mem::transmute::<_,_>(0xbeefbeef as *const u8) };
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ type validation failed: encountered a dangling reference (created from integer)
  |
  = note: The rules on what exactly is undefined behavior aren't clear, so this check might be overzealous. Please open an issue on the rustc repository if you believe it should not be considered undefined behavior.
  = note: the raw bytes of the constant (size: 8, align: 8) {
              ef be ef be 00 00 00 00                         │ ........
          }
```

Now the more interesting part:

When turning the constant into a associated constant like so:
```rust
struct Ex;

impl Ex {
    const F: &'static u8 = unsafe { std::mem::transmute::<_,_>(0xbeefbeef as *const u8) };
}

fn main() {}
```

The code now compiles and no error is thrown.

---

In addition to this weird behavior, I think
```rust
const F: &'static u8 = unsafe { std::mem::transmute::<_,_>(0xbeefbeef as *const u8) };
```

shouldn't be considered undefined behavior as it's just creating a static reference from a pointer. And on my embedded platform this pointer (`0xbeefbeef` is just an example) is always considered valid. Thus i want to create a safe reference from it to make accessing the memory easier (e.g. not requiring `unsafe` and derefs everywhere).

### Meta

`rustc --version --verbose`:
```
rrustc 1.54.0-nightly (1025db84a 2021-05-14)
binary: rustc
commit-hash: 1025db84a68b948139b5adcd55da31bce32da8f3
commit-date: 2021-05-14
host: x86_64-unknown-linux-gnu
release: 1.54.0-nightly
LLVM version: 12.0.1
```

**Comment by arnaudgolfouse** [comment]
In the second case, using the constant actually triggers a compilation error:
```rust
struct Ex;

impl Ex {
    const F: &'static u8 = unsafe { std::mem::transmute::<_,_>(0xbeefbeef as *const u8) };
}

fn main() {
    let f = Ex::F;
}
```
The mismatch between normal and associated constants is still very weird.

**Comment by RalfJung** [comment]
(Belated) Thanks for the bug report!

That mismatch is expected, associated consts can depend on generics and so they can only be checked when they are actually used. This behavior is also [documented](https://doc.rust-lang.org/nightly/reference/items/constant-items.html#evaluation), so I don't think there is any actionable bug here that needs fixing.
