### ISSUE TITLE
Public unstable feature="inplace_iteration" APIs without a tracking issue

### ISSUE THREAD

**Issue by SimonSapin** [rust-lang/rust#85373]
The `SourceIter` and `InPlaceIterable` unstable traits are public, so they and their `impl`s show up in docs. For example https://doc.rust-lang.org/1.52.1/std/iter/trait.InPlaceIterable.html. However unlike other unstable public APIs, there is no link to a tracking issue.

These traits were added by @the8472 in https://github.com/rust-lang/rust/pull/70793. It’s not clear from the PR’s description if the traits are intended as private implementation details of the standard library that are only technically `pub` so that they can be used across multiple standard library crates, or if they are intended as a new public API with a possible path to eventual stabilization.

Source definitions of the traits and `impl`s should either have `#[doc(hidden)]` attributes added, or a tracking issue should be filed and the `#[unstable]` attributes modified to point there.

**Comment by the8472** [comment]
> It’s not clear from the PR’s description if the traits are intended as private implementation details of the standard library that are only technically pub so that they can be used across multiple standard library crates

That's the intent.

> or if they are intended as a new public API with a possible path to eventual stabilization.

Not at this time. They're intended for specialization and specialization is still far from stable.

I will add `#[doc(hidden)]`.
