### ISSUE TITLE
E0277: suggest `?Sized` to relax implicit `Sized` bound on associated types

### ISSUE THREAD

**Issue by tlyu** [rust-lang/rust#85378]
Given the following code: [(playground)](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=9e10548141bcdd05e57230114dabdc54)

```rust
trait TraitWithAType {
    type Item;
}
trait Trait {}
struct A {}
impl TraitWithAType for A {
    type Item = dyn Trait;
}
```

The current output is:

```
   Compiling playground v0.0.1 (/playground)
error[E0277]: the size for values of type `(dyn Trait + 'static)` cannot be known at compilation time
 --> src/lib.rs:7:5
  |
2 |     type Item;
  |     ---------- required by this bound in `TraitWithAType::Item`
...
7 |     type Item = dyn Trait;
  |     ^^^^^^^^^^^^^^^^^^^^^^ doesn't have a size known at compile-time
  |
  = help: the trait `Sized` is not implemented for `(dyn Trait + 'static)`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: could not compile `playground`

To learn more, run the command again with --verbose.
```

Ideally the output should look like:

```
  |
2 |     type Item;
  |     ---------- required by this bound in `TraitWithAType::Item`
...
7 |     type Item = dyn Trait;
  |     ^^^^^^^^^^^^^^^^^^^^^^ doesn't have a size known at compile-time
  |
  = help: the trait `Sized` is not implemented for `(dyn Trait + 'static)`
help: consider relaxing the implicit `Sized` restriction
  |
2 |     type Item: ?Sized
  |              ^^^^^^^^
```

A similar error message with an unsized generic type argument _does_ mention the implicit `Sized` bound. [(playground)](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=764e262216d72078b210315931fd1851) Unfortunately, it also doesn't explain the implicit bound up front in the "required by this bound" text. (It mentions it when suggesting to relax the implicit bound, but I think it would be better to mention it up front as well.)

Both error messages could benefit from changing the "required by this bound" text to "required by an implicit `Sized` bound".

**Comment by tlyu** [comment]
I'm working on a pull request for this issue.

@rustbot claim

**Comment by estebank** [comment]
@tlyu Oh! Very sorry, if you spent too much time on this already, but I have done some work around this already in https://github.com/rust-lang/rust/pull/85947. If you want, you can take over it and bring it to completion, there are some cases, like https://github.com/rust-lang/rust/pull/85799#discussion_r642008001 that still need to be addressed and I haven't yet figured out. Alternatively, if you can find a way to accomplish the same result without touching the `TraitPredicate` and instead deal only with a new `ObligationCauseCode`, that would be preferable to my approach.

**Comment by tlyu** [comment]
I've pushed what I have so far to https://github.com/tlyu/rust/tree/suggest-unsized , sorry if it conflicts with stuff you've already done. If you'd like to take a look at it, that would be great. I'll take a look at what you have as well.

There are some issues to be worked out with conflicting suggestions for associated types for `?Sized` vs the existing suggestion for adding an explicit `Sized` to a trait's bounds, in test cases such as `type Foo = Self;` within a trait declaration.
