### ISSUE TITLE
Tracking Issue for abstract namespaces in Unix domain sockets

### ISSUE THREAD

**Issue by mdaverde** [rust-lang/rust#85410]
Feature gate: `#![feature(unix_socket_abstract)]`

This is a tracking issue for adding abstract namespace support for Unix domain sockets on Linux.

Traditionally, Unix domain sockets (UDS) use a file to coordinate socket binding and connecting. On Linux, though, a specific extension exists to allow domain sockets to be created from a namespace which does not use the filesystem. With these changes, we extend Rust's UDS support to create sockets directly from a `SocketAddr` which can be itself used to create an abstract namespace.

### More information

Previous discussion: #42048
Linux man page: [unix(7)](https://man7.org/linux/man-pages/man7/unix.7.html)

#### Non-platform specific additions

`UnixListener::bind_addr(&SocketAddr) -> Result<UnixListener>`

`UnixStream::connect_addr(&SocketAddr) -> Result<()>`

`UnixDatagram::bind_addr(&SocketAddr) -> Result<UnixDatagram>`

`UnixDatagram::connect_addr(&SocketAddr) -> Result<()>`

`UnixDatagram::send_to_addr(&self, &[u8], &SocketAddr) -> Result<usize>`

#### Platform-specific (Linux) additions

`SocketAddrExt::from_abstract_name(&[u8]) -> Result<SocketAddr>`

`SockerAddrExt::as_abstract_name(&self) -> Option<&[u8]>`

#### Example 

```rust
#![feature(unix_socket_abstract)]
use std::os::unix::net::{UnixListener, SocketAddr};
use std::os::linux::net::SocketAddrExt;

fn main() -> std::io::Result<()> {
    let addr = SocketAddr::from_abstract_namespace(b"namespace")?; // Linux only
    let listener = match UnixListener::bind_addr(&addr) {
        Ok(sock) => sock,
        Err(err) => {
            println!("Couldn't bind: {:?}", err);
            return Err(err);
        }
    };
    Ok(())
}
```

### Steps / History

- [x] Implementation: #85379
- [x] Rework to use an extension trait: https://github.com/rust-lang/rust/pull/101967
- [ ] Final commenting period (FCP)
- [ ] Stabilization PR

### Unresolved Questions

- None yet.

**Comment by mexus** [comment]
Is there anything else that needs to be done? :thinking: 

Seems like the PR from the first message has been already merged, so isn't it time for the FCP? :)

Also it seems kinda strange that there's no assignees in this issue.

**Comment by DataTriny** [comment]
Hi @mdaverde ,

Thank you so much for taking care of this.

I am already using the API added on #85379 for [AccessKit](https://github.com/accesskit/accesskit) and I haven't encountered any issue so far.

@joshtriplett you were the one reviewing the PR. Isn't it time for the FCP now?

**Comment by the8472** [comment]
If I understand https://github.com/rust-lang/rust/issues/76915#issuecomment-1118979669 correctly then the methods on `os::unix::SocketAddr` shouldn't be `cfg(any(doc, target_os = "android", target_os = "linux",))` and instead should go into the `os::linux` and `os::android` modules as extension traits.

**Comment by gustav3d** [comment]
Is there anything blocking FCP ?.
Can an ordinary person somehow help ?.

**Comment by the8472** [comment]
A remaining issue is that the methods are in the wrong place, they need to be moved to the os::linux module since they're linux specific and not available on other unixes.

**Comment by kris-nova** [comment]
Thank you for the context. I'll see if I can't make a contribution to move them to the Linux specific module. 

Do you know if there are any other outstanding items that would need to be addressed before this can move to FCP?

**Comment by jmillikin** [comment]
I'm also interested in seeing this feature stabilized, and made an attempt at moving the API into `SocketAddrExt`: https://github.com/rust-lang/rust/pull/101967

**Comment by joshtriplett** [comment]
I've reviewed and approved #101967, which moves the Linux-specific methods into an extension trait.

With that merged, I don't think there are any other blockers here.

So, let's see if we have consensus to stabilize UNIX socket abstract namespace support.

@rfcbot merge

**Comment by dtolnay** [comment]
I'm marking @yaahc's box because she has stepped down from T-libs-api after the point that this feature got proposed for FCP.

**Comment by mllken** [comment]
Sorry for the late comment.  The current signature of from_abstract_name in nightly is:
```rust
fn from_abstract_name<N>(name: &N) -> Result<SocketAddr>
where
    N: AsRef<[u8]>;
```
but,  I think it should be:
```rust
fn from_abstract_name<N>(name: N) -> Result<SocketAddr>
where
    N: AsRef<[u8]>;
```
The latter allows me to easily pass in a &str or &[u8] directly, without encountering Sized errors

**Comment by joshtriplett** [comment]
@rfcbot concern wait-for-106441

**Comment by JohnTitor** [comment]
Triage: https://github.com/rust-lang/rust/pull/106441 has been merged, the concern can be resolved now.

**Comment by jmillikin** [comment]
@joshtriplett @JohnTitor Are there any remaining approvals required for this, or should I put together a stabilization PR?

**Comment by joshtriplett** [comment]
I think this is ready for a stabilization PR.

**Comment by jmillikin** [comment]
Thanks! Stabilization PR is https://github.com/rust-lang/rust/pull/109288

**Comment by joshtriplett** [comment]
@rfcbot resolved wait-for-106441
