### ISSUE TITLE
from nightly-2021-04-26 started linking unneeded ws2_32.dll for x86_64-pc-windows-msvc target

### ISSUE THREAD

**Issue by klensy** [rust-lang/rust#85441]
For empty.rs:
```rust
fn main(){}
```
`rustc +nightly-2021-04-25-x86_64-pc-windows-msvc empty.rs -O`
don't use ws2_32.dll
```
 KERNEL32.dll
 VCRUNTIME140.dll
 api-ms-win-crt-runtime-l1-1-0.dll
 api-ms-win-crt-math-l1-1-0.dll
 api-ms-win-crt-stdio-l1-1-0.dll
 api-ms-win-crt-locale-l1-1-0.dll
 api-ms-win-crt-heap-l1-1-0.dll
```
`rustc +nightly-2021-04-26-x86_64-pc-windows-msvc empty.rs -O`
use ws2_32.dll
```
 WS2_32.dll
 KERNEL32.dll
 VCRUNTIME140.dll
 api-ms-win-crt-runtime-l1-1-0.dll
 api-ms-win-crt-math-l1-1-0.dll
 api-ms-win-crt-stdio-l1-1-0.dll
 api-ms-win-crt-locale-l1-1-0.dll
 api-ms-win-crt-heap-l1-1-0.dll
```

Can be checked for example via `dumpbin.exe /dependents empty.exe`

regressed between 42816d61e...3709ae324, i'm thinking about #84115

Thing that imported from ws2_32 is `WSACleanup`

@rustbot label  +O-windows +A-linkage

**Comment by klensy** [comment]
@CDirkx

**Comment by CDirkx** [comment]
Yeah that makes sense that it is from #84115.

https://github.com/rust-lang/rust/blob/40d23020470db06903589e210c83a4936f22d52a/library/std/src/sys/windows/net.rs#L44-L51

`cleanup` always called, which makes Rust link to `WSACleanup` from ws2_32.dll, even if no networking code is ever used. I wonder if extracting WSACleanup into a seperate non-inlined function would be enough:

```rust
pub fn cleanup() { 
    // only perform cleanup if network functionality was actually initialized
    if INIT.is_completed() { 
        _cleanup();
    }
}

// avoid linking to `WSACleanup` if it is never used by letting this function to be optimized away
#[inline(never)]
fn _cleanup() {
    unsafe { 
        // close the socket interface
        c::WSACleanup();
    }
}
```
