### ISSUE TITLE
remap libstd paths in backtraces for test crates

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/rust#85463]
I just got this backtrace when running `RUST_BACKTRACE=1 cargo test` on salsa-rs/salsa@bb4b42acf159332ddf9da735a85cf8d082de882a:

```
thread 'frozen::in_par_get_set_cancelation' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', tests/parallel/frozen.rs:64:33
stack backtrace:
   0: rust_begin_unwind
             at /rustc/881c1ac408d93bb7adaa3a51dabab9266e82eee8/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/881c1ac408d93bb7adaa3a51dabab9266e82eee8/library/core/src/panicking.rs:92:14
   2: core::result::unwrap_failed
             at /rustc/881c1ac408d93bb7adaa3a51dabab9266e82eee8/library/core/src/result.rs:1355:5
   3: core::result::Result<T,E>::unwrap
             at /home/jonas/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:1037:23
   4: parallel::frozen::in_par_get_set_cancelation
             at ./tests/parallel/frozen.rs:64:18
   5: parallel::frozen::in_par_get_set_cancelation::{{closure}}
             at ./tests/parallel/frozen.rs:13:1
   6: core::ops::function::FnOnce::call_once
             at /home/jonas/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:227:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/881c1ac408d93bb7adaa3a51dabab9266e82eee8/library/core/src/ops/function.rs:227:5
```

The remapping from `/rustc/...` paths to the rust-src component only seems to kick in *once* here, but I expected it to always work (since the component is installed). Frames 6 and 7 also point to the exact same location, but path remapping still failed for one of them.

**Comment by jyn514** [comment]
@jonas-schievink what version of rustc is this?

**Comment by jonas-schievink** [comment]
This is on `rustc 1.54.0-nightly (881c1ac40 2021-05-08)`

**Comment by jyn514** [comment]
Can you try with latest nightly? https://github.com/rust-lang/rust/pull/83813 was merged recently and may have fixed the.

**Comment by jonas-schievink** [comment]
The most recent nightly seems to work even less:

```
thread 'frozen::in_par_get_set_cancelation' panicked at 'called `Result::unwrap()` on an `Err` value: Any { .. }', tests/parallel/frozen.rs:64:33
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4e3e6db011c5b482d2bef8ba02274657f93b5e0d/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/4e3e6db011c5b482d2bef8ba02274657f93b5e0d/library/core/src/panicking.rs:92:14
   2: core::result::unwrap_failed
             at /rustc/4e3e6db011c5b482d2bef8ba02274657f93b5e0d/library/core/src/result.rs:1355:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/4e3e6db011c5b482d2bef8ba02274657f93b5e0d/library/core/src/result.rs:1037:23
   4: parallel::frozen::in_par_get_set_cancelation
             at ./tests/parallel/frozen.rs:64:18
   5: parallel::frozen::in_par_get_set_cancelation::{{closure}}
             at ./tests/parallel/frozen.rs:13:1
   6: core::ops::function::FnOnce::call_once
             at /rustc/4e3e6db011c5b482d2bef8ba02274657f93b5e0d/library/core/src/ops/function.rs:227:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/4e3e6db011c5b482d2bef8ba02274657f93b5e0d/library/core/src/ops/function.rs:227:5
```

**Comment by jyn514** [comment]
@jonas-schievink what do you mean? Those look correctly remapped to /rustc/hash to me, were you expecting something else?

**Comment by jyn514** [comment]
Oh I see, you want it to *not* remap and use the local path.

**Comment by jyn514** [comment]
Note that people have requested the opposite behavior in the past, but it seems reasonable to do this only for tests: https://github.com/rust-lang/rust/issues/82188

**Comment by jonas-schievink** [comment]
The `/rustc/<hash>` path is the non-remapped path. I have the rust-src component installed, so they should be remapped to point there.

**Comment by jyn514** [comment]
cc @cbeuw

**Comment by cbeuw** [comment]
I see there are some terminology confusions. `/rustc/<hash>` are technically remapped as it was remapped from some real path during compiler bootstrapping. At compile time it's correlated back to `rust-src` path if it exists. I would call `/rustc/<hash>` "virtualised" path and the actual `.../.rustup/toolchains/...` path "real" or "local" path.

I'm not confident in saying this but I _think_ this can be resolved within `std::backtrace`? We have a `CFG_VIRTUAL_RUST_SOURCE_BASE_DIR` containing the local path to the sources, and the backtrace code should be able to use it to map things back? This avoids emitting local paths into the binary which was what we tried to avoid.

**Comment by jyn514** [comment]
> CFG_VIRTUAL_RUST_SOURCE_BASE_DIR

I haven't looked into the code, but that sounds like it's a compile time constant, so it has the path *when rustc is compiled*, not when rustc is running. So if you use that it will be unhelpful, it will show things like /home/bors/builds.

**Comment by cbeuw** [comment]
nvm `CFG_VIRTUAL_RUST_SOURCE_BASE_DIR` actually contains what the path is virtualised *to* (i.e. `/rustc/<hash>`), so it's not too useful here. (It may be used to identify if the path on hand is actually for the Rust source rather than a real path on local system coincidentally starting with `/rustc/[a-z0-9]{40}/library/...` but that'd be highly unlikely unless the user is deliberately trying to trip things up. In any case we could hardcode `CFG_VIRTUAL_RUST_SOURCE_BASE_DIR` into rustc during bootstrapping).

The bit that finds the local path to rust source is here
https://github.com/rust-lang/rust/blob/3e827cc21e0734edd26170e8d1481f0d66a1426b/compiler/rustc_session/src/config.rs#L2077-L2093

The only environment-dependent thing we need here is sysroot on the local file system. Obviously we can't emit that into the binary so maybe we could ask Cargo to supply it?

**Comment by jyn514** [comment]
@cbeuw that has the same issue, cargo runs at compiletime, not runtime. There's no way for this to be done at runtime without it being part of the binary, which is why I suggested doing it only for test binaries.

**Comment by jyn514** [comment]
I guess as an alternative libtest could read a SYSROOT environment variable set by cargo, but that seems kind of hacky.

**Comment by cbeuw** [comment]
@jyn514 I'm in the middle of writing an RFC for Cargo that adds a profile setting called `trim-path`, which is basically an implementation of https://github.com/rust-lang/rust/issues/40552 (sanitising every potential absolute paths, like paths to Cargo registry) and is enabled by default for release builds.

Prehaps we could make the emission of virtual vs real sysroot paths also dependant on that? It seems a logical thing to do if `trim-path` gets added. This way both test and debug builds will have real paths embedded by default, and can be overriden manually if the user wishes.

**Comment by cbeuw** [comment]
RFC's here: https://github.com/rust-lang/rfcs/pull/3127
