### ISSUE TITLE
 The Rust package is upgraded to version >=1.47.0, resulting in missing stack protection options and Fortify Source compilation options for packages compiled by Rust.

### ISSUE THREAD

**Issue by wang-yue-ai** [rust-lang/rust#85498]
【problem】
1. Using rustc to compile related packages, how to add stack protection options and Fortify Source compilation options?
2. Before the rust-1.46.0 version, the stack protection option and the Fortify Source compilation option are supported. Why are these two options not available after the upgrade?

**Comment by Aaron1011** [comment]
> Before the rust-1.46.0 version, the stack protection option and the Fortify Source compilation option are supported. Why are these two options not available after the upgrade?

Are you getting an error message with a particular invocation of rust 1.46.0? If so, can you please post the command you're running, and the output you're getting?

**Comment by wang-yue-ai** [comment]
You can write such a program and verify it on rust-1.45.2 and rust-1.47.0：
fn main() {
    println!("Hello, world!");
}

Then execute the following command：
rustc main.rs --cap-lints allow -Clink-arg=-lgcc -Copt-level=3 -Cdebuginfo=2 -Clink-arg=-Wl,-z,relro,-z,now -Ccodegen-units=1

We don’t have any error logs, and the binary is compiled normally. The binary we compiled in 1.45.2 contains these two safe compilation options, but the binary compiled in rust-1.47.0 does not find this. Two safe compilation options

**Comment by Dylan-DPC** [comment]
Closing this to clear up the issue tracker. If you or anyone reading this still needs help you can consult the forums, discords, etc for help. Thanks
