### ISSUE TITLE
rustdoc: when hiding item contents, include a count

### ISSUE THREAD

**Issue by jsha** [rust-lang/rust#85494]
In #83337, we started hiding the contents (methods, fields, variants) of large traits, structs, and enums. When the contents are hidden there's text that says `[+] Show methods`. It's a little confusing as a user to figure out why some contents are hidden and some aren't. To improve that, we should include the number as a hint. E.g. `[+] Show 15 methods`.

/cc @Manishearth

**Comment by Manishearth** [comment]
Oh this is a neat idea!
