### ISSUE TITLE
Use of clamp in generics does not compose with f32 and f64, maybe relax restriction to PartialOrd?

### ISSUE THREAD

**Issue by stephanemagnenat** [rust-lang/rust#85508]
When using `T::clamp()` in generics, `T` must be ` Ord`. Types `f32` and `f64` are not `Ord` but implements `clamp` since 1.50.0, yet they cannot be used in generics due to the `Ord` constraint.

A possible solution I can think of is relax the constraint for `clamp()` from `Ord` to `PartialOrd`.

I tried this code:

```rust
fn c<T: PartialOrd>(v: T, min: T, max: T) -> T {
    v.clamp(min, max)
}

fn main() {
    println!("{}", c(1.0, 0.0, 2.0));
}
```

I expected to see this happen: *compilation success*

Instead, this happened: *error[E0599]: the method `clamp` exists for type parameter `T`, but its trait bounds were not satisfied*

### Meta

`rustc --version --verbose`:
```
rustc 1.52.1 (9bc8c42bb 2021-05-09)
binary: rustc
commit-hash: 9bc8c42bb2f19e745a63f3445f1ac248fb015e53
commit-date: 2021-05-09
host: x86_64-unknown-linux-gnu
release: 1.52.1
LLVM version: 12.0.0
```

**Comment by stephanemagnenat** [comment]
This is of course not a compiler bug, but rather a typing limitation in std.

**Comment by stephanemagnenat** [comment]
Similarly, it is not possible to generalize over float types when using `min` and `max` because they are not `Ord`.

**Comment by Xaeroxe** [comment]
Yeah actually we talked about this when clamp was introduced. https://github.com/rust-lang/rfcs/pull/1961#issuecomment-290300091

The conclusion we came to is that PartialOrd was too likely to lead to surprising behavior. Thanks to the num crate you can still write your software the way you want to though.

**Comment by Dylan-DPC** [comment]
Closing this as it is intended by the RFC
