### ISSUE TITLE
Slight inaccuracy in the rustc_mir documentation

### ISSUE THREAD

**Issue by giltho** [rust-lang/rust#85513]
Hello,

It feels like this shouldn't be an issue but I don't really know where to post it otherwise..
[The documentation of `eval_place` in the MIR `InterpCx`](https://github.com/rust-lang/rust/blob/3e827cc21e0734edd26170e8d1481f0d66a1426b/compiler/rustc_mir/src/interpret/place.rs#L654) says that there is a more efficient solution when the place is access for read called `eval_place_for_read`, but the latter does not exist anywhere.
I'm guessing it should be referring to `eval_place_to_op`, but I am not entirely sure. Also as a side question, I'd be curious to know why it is slower to access a place for write than it is for read.

I'm going to spend a bit of time reading that part of the code, if I ever find other tiny things like that, where should I report it ? It feels like this could be a small discussion in a chat followed by a tiny PR rather than an issue.

Thank you !

**Comment by scottmcm** [comment]
If you have a question while making a PR, on good resource is Zulip: https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp

Depending how easy a PR it is and whether you're reasonably confident in your deduction, you could also just make a PR changing it and the reviewer will confirm that the update is accurate.

**Comment by pierwill** [comment]
@giltho Your analysis looks correct to me. I'm working up a PR to fix these docs.

@rustbot claim

**Comment by pierwill** [comment]
> I'm going to spend a bit of time reading that part of the code, if I ever find other tiny things like that, where should I report it ? It feels like this could be a small discussion in a chat followed by a tiny PR rather than an issue.

Issues like this are welcome, as are small PRs. :)
