### ISSUE TITLE
28x binary size regression in recent nightly

### ISSUE THREAD

**Issue by jonas-schievink** [rust-lang/rust#85519]
There seems to be a significant regression in binary size in the most recent nightly:

nightly-2021-05-19

```
$ size target/thumbv6m-none-eabi/debug/hello
   text	   data	    bss	    dec	    hex	filename
   6056	     48	   1032	   7136	   1be0	target/thumbv6m-none-eabi/debug/hello
```

nightly-2021-05-20

```
$ size target/thumbv6m-none-eabi/debug/hello
   text	   data	    bss	    dec	    hex	filename
 201372	     48	   1032	 202452	  316d4	target/thumbv6m-none-eabi/debug/hello
```

Steps to reproduce:

* Clone https://github.com/jonas-schievink/size-regression
* Install `thumbv6m-none-eabi` target
* Run `cargo build`
* `size target/thumbv6m-none-eabi/debug/hello`

Commits in that range: https://github.com/rust-lang/rust/compare/4e3e6db01...f94942d84

https://github.com/rust-lang/rust/pull/85274 looks suspicious (cc @luqmana)

**Comment by jamesmunns** [comment]
This seems to have been noticed here as well: https://github.com/rust-lang/rust/pull/85274

**Comment by jamesmunns** [comment]
Also as a note, @japaric tested this with using `arm-none-eabi-ld` as the linker instead of the default rust-lld, and this issue remained (referring to #85274). He can confirm whether he set the "linker flavor" or similar as well.

**Comment by Dirbaio** [comment]
it's very likely #85274, since adding `-C link-arg=--gc-sections` to rustflags fixes the bloat.

**Comment by nagisa** [comment]
Is the linker for this target guaranteed to be gnu? Doesn't sound like something that we can claim, can we?

**Comment by jonas-schievink** [comment]
We do default to LLD, which can also garbage-collect unused sections

**Comment by nagisa** [comment]
Yeah, I was just asking if we should expand our logic there or just say that the targets use a gnu-ld-like linker.

**Comment by jonas-schievink** [comment]
Yeah, in practice I don't think anyone uses a non-GNU linker there

**Comment by petrochenkov** [comment]
It may make sense to set the default for `linker_is_gnu` to true because `ld`-style linkers are *usually* gnu, and it's easier to explicitly list exceptions than to not forget setting it to true for all random embedded targets.

**Comment by petrochenkov** [comment]
If the default is not flipped then `compiler\rustc_target\src\spec\thumb_base.rs` needs to add `linker_is_gnu: true` + other target specs should probably be audited as well.
