### ISSUE TITLE
no typehint/typeinfer for async fn on rustc-nightly-2021-05-20 with rust-analyzer

### ISSUE THREAD

**Issue by pymongo** [rust-lang/rust#85539]
I tried this code:

```rust
async fn foo() -> Result<i32, ()> {
    Ok(1)
}

async fn bar() -> Result<(), ()> {
    let temp = foo().await?;
    Ok(())
}
```

But no typehint/type annotation for variable `temp` if rustc's version is nightly-2021-05-20

If I only change rustc's version by `rustup override set nightly-2021-05-16` and reload vscode's window, the typehint for variable `temp` show correctly.

typehint for `async fn foo() -> Result<i32, ()>` works ok on nightly-2021-05-16, but failed on nightly-2021-05-20

I use the same rust-analyzer executable file, I think **this problem cause by rustc**.

### Meta

`rust-analyzer --version`:
```
rust-analyzer fd109fb 2021-05-20 dev
```

`rustup show`:
```
Default host: x86_64-unknown-linux-gnu
rustup home:  /home/w/.rustup

installed toolchains
--------------------

stable-x86_64-unknown-linux-gnu
nightly-2021-05-16-x86_64-unknown-linux-gnu (default)
nightly-x86_64-unknown-linux-gnu

active toolchain
----------------

nightly-x86_64-unknown-linux-gnu (directory override for '/home/w/temp/no_typehint_for_async_fn_response_on_rustc_0520')
rustc 1.54.0-nightly (40d230204 2021-05-20)
```

**Comment by jonas-schievink** [comment]
Problems with rust-analyzer should generally be filed at https://github.com/rust-analyzer/rust-analyzer

**Comment by pymongo** [comment]
close since issue track on https://github.com/rust-analyzer/rust-analyzer/issues/8907
