### ISSUE TITLE
Type inference error when importing unrelated function.

### ISSUE THREAD

**Issue by neuring** [rust-lang/rust#85565]
I tried this code:

```rust
use serde_json::to_string;

pub fn some_function() {
    assert_eq!(3_u32, (0..3).sum());
}
```
[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=4d5c14b4fa1fc1b8e70b507be1f5263a)

I expected this to compile, but a type inference error was emitted.

```
error[E0283]: type annotations needed
 --> src/lib.rs:4:30
  |
4 |     assert_eq!(3_u32, (0..3).sum());
  |                              ^^^ cannot infer type for type parameter `S` declared on the associated function `sum`
  |
  = note: cannot satisfy `_: Sum<i32>`
help: consider specifying the type argument in the method call
  |
4 |     assert_eq!(3_u32, (0..3).sum::<S>());
  |                                 ^^^^^
```

If the import of `serde_json::to_string` is removed the code compiles just fine.

### Meta

It fails on all stable, beta and nightly.

**Comment by jonas-schievink** [comment]
I believe this is expected behavior. It also happens with `use serde_json as _;`, which just causes the compiler to load the crate. Since that also loads any impls in the crate, they can cause ambiguities.

**Comment by neuring** [comment]
@jonas-schievink  There don't seem to be any impls for `Sum` in `serde_json` and neither in `serde`.
But in searching that for those. I found https://github.com/serde-rs/json/issues/651 which linked to https://github.com/rust-lang/rust/issues/46257.
So this issue is a duplicate.
