### ISSUE TITLE
rustdoc: "Methods from Deref<...>" too low on sidebar

### ISSUE THREAD

**Issue by jsha** [rust-lang/rust#85618]
Steps to reproduce:

1. Visit https://doc.rust-lang.org/beta/std/string/struct.String.html
2. Scroll down the sidebar looking for "Methods from Deref&lt;...&gt;"

Expected result:

Methods from Deref section comes immediately after Methods.

Actual result:

Methods from Deref section comes below Trait Implementations, Auto Trait Implementations, and Blanket Implementations.

Compare vs https://doc.rust-lang.org/std/string/struct.String.html, which has the correct ordering.

**Comment by jsha** [comment]
Ah, looks like this was intentional in #83826, after conversation in #83133. Removing C-bug and regression-from-stable-to-beta. Keeping this open as a discussion issue: I think putting "Methods from Deref" below trait implementations is wrong for String, because so many of its important methods are on `str`. I'd like to either reconsider #83133 or find some way to make this work nicely for String.

**Comment by alexschrod** [comment]
I'd like to voice that I also think this is a kind of regression. 99% of the time I go to a type's page, I'm looking for methods, not traits; I've gotten used to seeing `str`'s methods directly under `String`s, and it feels like a mistake going away from this.

**Comment by jsha** [comment]
@jyn514, @slightlyoutofphase, what do you think of reverting #83826 while we look for a better solution. From #83133:

> it would almost certainly be better to have the crate-native "Trait Implementations" section appear before the "Methods From Deref" section does, since "Trait Implementations" will pretty much always be describing things that are unique to the crate being documented and so actually directly relevant

The problem with this is sometimes the "Methods from Deref" section refers to a type in the crate. Particularly for [Vec](https://doc.rust-lang.org/nightly/std/vec/struct.Vec.html#deref-methods-%5BT%5D) and [String](https://doc.rust-lang.org/nightly/std/string/struct.String.html#deref-methods-str), about half of the most useful methods are on `[T]` and `str`, respectively.

Those are types that are a critical part of the new user learning path, and it's a good user experience for those to be right next to the other methods, both in the sidebar and in the doc.

I suspect there are other ways to solve the need expressed in #83133 without affecting the page layout of Vec and String in this way.

**Comment by jyn514** [comment]
@jsha that's fine - https://github.com/rust-lang/rust/pull/83826 was a response to https://github.com/rust-lang/rust/pull/80653, which has since been reverted.

**Comment by slightlyoutofphase** [comment]
> I suspect there are other ways to solve the need expressed in #83133 without affecting the page layout of Vec and String in this way.

FWIW, I originally opened that issue with something more like a directly configurable way of specifying the page layout order for your own crate in mind. I still think that would ultimately be the best solution here.
