### ISSUE TITLE
Build fail with linking with rust-lld failed: exit code: 0xc0000135 on stable windows gnu for wasm32-unknown-unknown

### ISSUE THREAD

**Issue by madmaxio** [rust-lang/rust#85624]
Build fail with linking with rust-lld failed: exit code: 0xc0000135 on stable windows gnu for wasm32-unknown-unknown

Building yew framework, https://github.com/yewstack/yew

**Comment by madmaxio** [comment]
Some work is done at https://github.com/yewstack/yew/issues/1868

**Comment by mati865** [comment]
Probably duplicate of https://github.com/rust-lang/rust/issues/85422
