### ISSUE TITLE
Windows `rust-lld` does not support the MSVC `manifestdependency` `.drectve`

### ISSUE THREAD

**Issue by ChrisDenton** [rust-lang/rust#85642]
Minimal reproduction (Windows only):
```rust
#[link_section = ".drectve"]
#[used]
static DIRECTIVE: [u8; 164] = *br#""/manifestdependency:type='Win32' name='Test.Research.SampleAssembly' version='6.0.0.0' processorArchitecture='X86' publicKeyToken='0000000000000000' language='*'" "#;

fn main() {}
```

Using the default MSVC linker works:

```
rustc main.rs
```

However when using `rust-lld.exe` it fails:

```
rustc -C linker="rust-lld.exe" main.rs
```

The error says it's unsupported:

> **note**: rust-lld: error: /manifestdependency: is not allowed in .drectve

----

LLD tracking issue: #71520

**Comment by roblabla** [comment]
Upstream bug: https://bugs.llvm.org/show_bug.cgi?id=38797

**Comment by ChrisDenton** [comment]
Rust recently upgraded to LLVM 14 so I'm closing this as resolved. I'll also comment on the tracking issue.
