### ISSUE TITLE
I'm a novice to Rust, please help me get around an error message

### ISSUE THREAD

**Issue by marienhof** [rust-lang/rust#85656]
Hi!
Here's a video of how the error was produced: https://www.youtube.com/watch?v=dWabGgXfPRc
 The error message says:

`➜  hello_cargo git:(master) ✗ cargo build --verbose
   Compiling hello_cargo v0.1.0 (/Users/amabie/hello_cargo)
     Running `rustc --crate-name hello_cargo --edition=2018 src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 -C metadata=65bd4e68837e258e --out-dir /Users/amabie/hello_cargo/target/debug/deps -C incremental=/Users/amabie/hello_cargo/target/debug/incremental -L dependency=/Users/amabie/hello_cargo/target/debug/deps`
error: linking with `cc` failed: exit code: 1
  |
  = note: "cc" "-m64" "-arch" "x86_64" "-L" "/Users/amabie/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "/Users/amabie/hello_cargo/target/debug/deps/hello_cargo.hello_cargo.8mpofxfx-cgu.0.rcgu.o" "/Users/amabie/hello_cargo/target/debug/deps/hello_cargo.hello_cargo.8mpofxfx-cgu.1.rcgu.o" "/Users/amabie/hello_cargo/target/debug/deps/hello_cargo.hello_cargo.8mpofxfx-cgu.2.rcgu.o" "/Users/amabie/hello_cargo/target/debug/deps/hello_cargo.hello_cargo.8mpofxfx-cgu.3.rcgu.o" "/Users/amabie/hello_cargo/target/debug/deps/hello_cargo.hello_cargo.8mpofxfx-cgu.4.rcgu.o" "/Users/amabie/hello_cargo/target/debug/deps/hello_cargo.hello_cargo.8mpofxfx-cgu.5.rcgu.o" "/Users/amabie/hello_cargo/target/debug/deps/hello_cargo.hello_cargo.8mpofxfx-cgu.6.rcgu.o" "/Users/amabie/hello_cargo/target/debug/deps/hello_cargo.hello_cargo.8mpofxfx-cgu.7.rcgu.o" "-o" "/Users/amabie/hello_cargo/target/debug/deps/hello_cargo" "/Users/amabie/hello_cargo/target/debug/deps/hello_cargo.2alzksgu9drlwkc0.rcgu.o" "-Wl,-dead_strip" "-nodefaultlibs" "-L" "/Users/amabie/hello_cargo/target/debug/deps" "-L" "/Users/amabie/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "/Users/amabie/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libstd-9225b8e469c32698.rlib" "/Users/amabie/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libpanic_unwind-2fe2b8cd4fa63c34.rlib" "/Users/amabie/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libobject-80083cf4ee7ee3ff.rlib" "/Users/amabie/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libaddr2line-ddf3832e718029e6.rlib" "/Users/amabie/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libgimli-ba92c986e8ef2ca8.rlib" "/Users/amabie/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librustc_demangle-acd0bd456d8da820.rlib" "/Users/amabie/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libhashbrown-55608c4156e4ecbb.rlib" "/Users/amabie/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librustc_std_workspace_alloc-4be618026614fdc7.rlib" "/Users/amabie/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libunwind-fee25922260aa100.rlib" "/Users/amabie/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcfg_if-38ba3c5cc408e14d.rlib" "/Users/amabie/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liblibc-899852a009fbe35f.rlib" "/Users/amabie/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liballoc-5687564a0ccea916.rlib" "/Users/amabie/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librustc_std_workspace_core-9ed2c58b16cff4ee.rlib" "/Users/amabie/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcore-244bf5611f93ff45.rlib" "/Users/amabie/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcompiler_builtins-70df686e6b4ebf5b.rlib" "-lSystem" "-lresolv" "-lc" "-lm" "-liconv"
  = note: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
          

error: aborting due to previous error

error: could not compile `hello_cargo`

Caused by:
  process didn't exit successfully: `rustc --crate-name hello_cargo --edition=2018 src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C debuginfo=2 -C metadata=65bd4e68837e258e --out-dir /Users/amabie/hello_cargo/target/debug/deps -C incremental=/Users/amabie/hello_cargo/target/debug/incremental -L dependency=/Users/amabie/hello_cargo/target/debug/deps` (exit code: 1)`

Environment:

rustup 1.24.2 (755e2b07e 2021-05-12)
cargo 1.52.0 (69767412a 2021-04-21)

If I ask for gcc version, the terminal says: xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun

uname -a
Darwin Amabies-MacBook-Air.local 20.3.0 Darwin Kernel Version 20.3.0: Thu Jan 21 00:06:51 PST 2021; root:xnu-7195.81.3~1/RELEASE_ARM64_T8101 x86_64

I also created and edited my first Rust Hello World program in VS Code. The terminal is Hyper and the shell is Oh My Zsh. Maybe that's important.

**Comment by ohsayan** [comment]
This is a place for reporting issues and making suggestions for the compiler. We have a beginner friendly channel on discord where you can ask such questions. Feel free to join the server here: https://discord.gg/dwqjCaSE

**Comment by marienhof** [comment]
Great! Sorry
