### ISSUE TITLE
rustdoc: Search results now have lines between them

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#85654]
I'm not certain whether this is a bug or an intentional change, but I couldn't find any PRs that said they were making this change. There were two PRs merged recently that affected the search results display: #85551 and #85568. Cc @GuillaumeGomez.

### [beta](https://doc.rust-lang.org/beta/std/index.html?search=range) (correct)

![image](https://user-images.githubusercontent.com/37223377/119429514-d7cb4680-bcc3-11eb-9345-fdc7cb0283ac.png)

### [nightly](https://doc.rust-lang.org/nightly/std/index.html?search=range) (incorrect)

![image](https://user-images.githubusercontent.com/37223377/119429479-c5e9a380-bcc3-11eb-9f3e-cf8e041df015.png)

**Comment by jyn514** [comment]
I like the new version better.

**Comment by jhpratt** [comment]
This change appears to be intentional, as [this line](https://github.com/rust-lang/rust/pull/85551/files#diff-7dc22a0530802d77c2f2ec9e834024a5657b6eab4055520fca46edc99a544413R779) was added to CSS that only applies to this element.

**Comment by GuillaumeGomez** [comment]
Yes, it's completely voluntary. We changed the display on mobile and to keep more coherent, we decided to keep the lines too.
