### ISSUE TITLE
regression: Option::insert and trait extensions conflict

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#85694]
The breakage seems to come from extension traits in logos-derive (of various versions), from https://crater-reports.s3.amazonaws.com/beta-1.52-2/index.html.

See list there for the broken crates under the "regressed: dependencies (20 root crates, 1341 regressed crates in total)" and logos-derive headings.

**Comment by Mark-Simulacrum** [comment]
@rust-lang/libs I haven't seen any feedback on this issue in the past ~20 days -- it is similar to https://github.com/rust-lang/rust/issues/85667 in principle.

I suspect that as things stand we will close this as won't fix. I suspect there will not be an explicit note made in the release notes, either. We have until Wednesday ~morning to raise concerns with this path of action.

**Comment by m-ou-se** [comment]
Oh, sorry about the lack of response. Without the I-nominated label, it doesn't show up in our agenda.

We should modify our agenda generator to include regressions (and a few other labels too, probably). (And/or maybe get some zulip bot like i've seen some other teams use.)

**Comment by yaahc** [comment]
> We should modify our agenda generator to include regressions (and a few other labels too, probably). (And/or maybe get some zulip bot like i've seen some other teams use.)

This is done now, so hopefully it won't be an issue again in the future.

> I suspect that as things stand we will close this as won't fix. I suspect there will not be an explicit note made in the release notes, either. We have until Wednesday ~morning to raise concerns with this path of action.

This seems like a reasonable plan of action, though I wish we had a better way to deal with extension trait conflicts when adding new APIs...

**Comment by Mark-Simulacrum** [comment]
Closing this out as it's no longer particularly actionable.
