### ISSUE TITLE
`#[repr(align)]` with no argument to `align` leads to ICE on Nightly/Beta.

### ISSUE THREAD

**Issue by Chronos-Sk** [rust-lang/rust#85713]
### Code

```Rust
#[repr(align)]
pub struct Foo;
```

### Meta

Version: 1.54.0-nightly (2021-05-25 ff2c947c00f867b9f012)

Found this on the Rust playground: [reproducing link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=f6b736de2aad6aabba7dd9cea3b9e38c). Not sure how to get the verbose version output from the playground.

### Error output

```
   Compiling playground v0.0.1 (/playground)
error: internal compiler error: unrecognized representation hint
 --> src/lib.rs:2:8
  |
2 | #[repr(align)]
  |        ^^^^^
  |
  = note: delayed at compiler/rustc_attr/src/builtin.rs:940:32

thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:1021:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.54.0-nightly (ff2c947c0 2021-05-25) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2 --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `playground`

To learn more, run the command again with --verbose.
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'no errors encountered even though `delay_span_bug` issued', compiler/rustc_errors/src/lib.rs:1021:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/ff2c947c00f867b9f012e28ba88cecfbe556f904/library/std/src/panicking.rs:515:5
   1: std::panicking::begin_panic_fmt
             at /rustc/ff2c947c00f867b9f012e28ba88cecfbe556f904/library/std/src/panicking.rs:457:5
   2: rustc_errors::HandlerInner::flush_delayed
   3: <rustc_errors::HandlerInner as core::ops::drop::Drop>::drop
   4: core::ptr::drop_in_place<rustc_session::parse::ParseSess>
   5: <alloc::rc::Rc<T> as core::ops::drop::Drop>::drop
   6: core::ptr::drop_in_place<rustc_interface::interface::Compiler>
   7: rustc_span::with_source_map
   8: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

</p>
</details>

**Comment by hellow554** [comment]
> Not sure how to get the verbose version output from the playground.

two possibilities:
tick backtrace enable:
![grafik](https://user-images.githubusercontent.com/921462/119667440-96a77380-be36-11eb-9dff-572abeacc3b0.png)

or click that link (it does the same)
![grafik](https://user-images.githubusercontent.com/921462/119667476-9dce8180-be36-11eb-9c12-555895494657.png)

**Comment by hellow554** [comment]
Was introcuded by #81234 cc @repnop

**Comment by apiraino** [comment]
Assigning priority as discussed in the [Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2385713.20.60.23.5Brepr.28align.29.5D.60.20with.20no.20argument.20to.20.60align.60.20leads.20t.E2.80.A6) of the Prioritization Working Group.

@rustbot label -I-prioritize +P-critical

**Comment by LeSeulArtichaut** [comment]
cc @lcnr

**Comment by jyn514** [comment]
> Was introcuded by #81234 cc @repnop
> 
> Not sure why this was done: https://github.com/rust-lang/rust/pull/81234/files#diff-056d6eadf00f9575945a2e2b893636b990351ae149148579492a6a35c60d77a7L969-R940

Hmm, that should be caught here: https://github.com/rust-lang/rust/pull/81234/files#diff-77c442894af49f492927d99f7e60f4365a4829100c0c52f565f42dc184712c76R1222

Maybe check_attr isn't running on the attribute for some reason?

**Comment by LeSeulArtichaut** [comment]
> > Was introcuded by #81234 cc @repnop
> > Not sure why this was done: https://github.com/rust-lang/rust/pull/81234/files#diff-056d6eadf00f9575945a2e2b893636b990351ae149148579492a6a35c60d77a7L969-R940
> 
> Hmm, that should be caught here: https://github.com/rust-lang/rust/pull/81234/files#diff-77c442894af49f492927d99f7e60f4365a4829100c0c52f565f42dc184712c76R1222
> 
> Maybe check_attr isn't running on the attribute for some reason?

The diff you're pointing to is handling cases like
```rust
#[repr(foo)]
pub struct Foo;
```

**Comment by Chronos-Sk** [comment]
> > Not sure how to get the verbose version output from the playground.
> 
> two possibilities:
> tick backtrace enable:
> ![grafik](https://user-images.githubusercontent.com/921462/119667440-96a77380-be36-11eb-9dff-572abeacc3b0.png)
> 
> or click that link (it does the same)
> ![grafik](https://user-images.githubusercontent.com/921462/119667476-9dce8180-be36-11eb-9c12-555895494657.png)

Is enabling the backtrace a sufficient substitute for `rustc --version --verbose`? That's the part I was having trouble with.

**Comment by estebank** [comment]
I'm happy to see #85976, but for beta backport we'll likely want a smaller PR or a revert of the PR introducing this issue.

**Comment by LeSeulArtichaut** [comment]
Reverting seems fine since #81234 only added a nightly feature. I'll take care of that

**Comment by Mark-Simulacrum** [comment]
Moving milestone to 1.54 as we've included #86300 in 1.53 (via https://github.com/rust-lang/rust/pull/86317).

**Comment by JohnTitor** [comment]
Triage: Fixed by #87013, it has a regression test for this case, closing.

**Comment by Mark-Simulacrum** [comment]
Reopening - that PR has not been backported to 1.54 (beta) yet.

**Comment by JohnTitor** [comment]
We should mark #87013 as `beta-nominated` then.

**Comment by Mark-Simulacrum** [comment]
https://github.com/rust-lang/rust/pull/86413 already backported #81234 into 1.54 beta, so this is handled on 1.54 beta. Closing. 

#87013 looks like a more invasive patch but seems good for 1.55.
