### ISSUE TITLE
tidy does not enforce comments only lines must be <= 100 characters long

### ISSUE THREAD

**Issue by wesleywiser** [rust-lang/rust#85726]
`rustfmt` by default does not format comments so while it will reformat Rust code to be <= 100 characters per line, it does not do this for lines consisting only of a comment. As such `x.py tidy` does not report these lines and allows them to be merged into the repository without issue.

I tried enabling some `rustfmt` options to reformat comments but the results are suboptimal in many situations. For the time being, it would probably be best if `tidy` were taught to check for this issue itself.

See [this Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp/topic/tidy.20line.20lengths) for more details.

**Comment by calebcartwright** [comment]
Another option would be to enable `error_on_unformatted` which will allow rustfmt to report instances where comments and lits exceed the max width, but not attempt to reformat them on your behalf.

Not sure what type of noise that may generate but could be worth investigating

**Comment by onur-ozkan** [comment]
In #120391 PR discussion, it appears that restricting the comment length in rust files may not be worthwhile as comments are already well-suited and when they exceed the usual length, it is typically for the readability or to enhance visual presentation (like writing markdown tables).

**Comment by onur-ozkan** [comment]
In https://github.com/rust-lang/rust/pull/120391 PR discussion, it appears that restricting the comment length in rust files may not be worthwhile as comments are already well-suited and when they exceed the usual length, it is typically for the readability or to enhance visual presentation (like writing markdown tables).
