### ISSUE TITLE
Tracking Issue for is_symlink

### ISSUE THREAD

**Issue by maxwase** [rust-lang/rust#85748]
Feature gate: `#![feature(is_symlink)]`

### Public API

```rust
// for `Path` and `Metadata`
pub fn is_symlink(&self) -> bool
```

### Steps / History

- [x] Implementation: #85747 
- [x] Final commenting period (FCP)
- [ ] Stabilization PR

### Unresolved Questions

None

**Comment by marcospb19** [comment]
My thoughts on the unresolved questions:

> Does exists() or try_exists() method work correctly? How do we implement these for symlinks?

Every function in `std::fs` is supposed to follow links, except for the ones who contain `link` name in it:
1. `fs::metadata_symlink`
2. `fs::hard_link`
3. `fs::read_link`

Assuming this pattern is consistent in all library stable functions, I'd say `exists()` and `try_exists()` are implemented correctly, they fail if there is a broken link at the path.

If we had `exists_symlink()` and `try_exists_symlink()`, I'd assume they both return true for broken links.

---

> Linked issues: fs::Metadata::is_dir() and is_file() should be deprecated #76487

I created that issue when I was confused why there wasn't a `is_symlink` available for `fs::Metadata`, as seen by the feedback given, people prefer those methods to not be deprecated, as they are useful shorthands to metadata's filetype methods, I agree, and I believe that `Path::is_symlink` and `Metadata::is_symlink` would be just as useful.
