### ISSUE TITLE
rand::Rng should be implemented for &Rng

### ISSUE THREAD

**Issue by nsf** [rust-lang/rust#8575]
Well, I've read that rust doesn't encourage using traits as interfaces. But to me it sounds like a must. On IRC @cmr also suggested me to open an issue. Here it is.

It seems reasonable to have an implementation of Rng for &Rng. Or be it &mut Rng or whatever is necessary to make it work when you use traits as an interface.

**Comment by steveklabnik** [comment]
Yes, object safety and such means that this should work now.
