### ISSUE TITLE
get() sometimes returns empty slice instead of None

### ISSUE THREAD

**Issue by Aleksander-F** [rust-lang/rust#85752]
I tried this code:

```rust
fn main() {
    let list = vec!["foo"];
    let a = &list.get(1..);
    let b = &list.get(2..);
    let c = &list.get(1..1);
    println!("{:?} {:?} {:?} {:?}", list.len(), a, b, c);
}
```
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=ae168cd69f37160936771fdd6d5eec9b

I expected to see this happen: since all ranges are out of bounds, expected to see a == b == c == None.

Instead, this happened: a == c == Some([]), b == None

Debugger points to this check:
```rust
#[stable(feature = "slice_get_slice_impls", since = "1.15.0")]
unsafe impl<T> SliceIndex<[T]> for ops::Range<usize> {
    #[inline]
    fn get(self, slice: &[T]) -> Option<&[T]> {
        if self.start > self.end || self.end > slice.len() {
            None
```

Shouldn't it be like this instead:
```rust
        let len = slice.len();
        if self.start >= self.end || self.end > len || self.start >= len {
            None
```

`rustc --version --verbose`:
```
rustc 1.52.1 (9bc8c42bb 2021-05-09)
binary: rustc
commit-hash: 9bc8c42bb2f19e745a63f3445f1ac248fb015e53
commit-date: 2021-05-09
host: x86_64-pc-windows-msvc
release: 1.52.1
LLVM version: 12.0.0
```

**Comment by wwylele** [comment]
I personally think the behavior is expected. An index of `len()` is out of bound, but a range starting at `len()` is probably not. This is inline with some index math:
 For a Vec of len 3, `get(1..)`, `get (2..)` and `get(3..)` would return `Some(&[slice of 2 element])`, `Some(&[slice of 1 element])`, `Some(&[slice of 0 element])`, which lines up perfectly. Only for the next one, `get(4..)` would return a slice of -1 element, which doesn't make sense, so it returns None. A similar argument can be made for right-bounded range.

**Comment by Aleksander-F** [comment]
But then there is inconsistency between ```get(3..3)``` and ```get(4..4)``` in example with ```Vec``` of len 3: both point to a non-existing element, both can return empty slice, but while the former does return empty slice the latter returns ```None``` instead.

**Comment by SkiFire13** [comment]
```
[ a , b , c ]
            ^--- 3..3 points here, right at the end of the slice, so it bound checks

[ a , b , c ]
                ^-- 4..4 points here, outside the slice, so it's an out of bounds
```

I don't see the inconsistency here

**Comment by Aleksander-F** [comment]
> ```
> [ a , b , c ]
>             ^--- 3..3 points here, right at the end of the slice, so it bound checks
> 
> [ a , b , c ]
>                 ^-- 4..4 points here, outside the slice, so it's an out of bounds
> ```
> 
> I don't see the inconsistency here

Now I see, is it that index in range is considered to point to _boundaries_ between values?
Basically I assumed it points to _values_, something like this:
```
     [a, b, c]
   (2..2)---^  ^---(3..3)
                  ^---(4..4)
```
So for (3..3) both ```start``` and ```end``` are out of bounds, making the whole range also out of bounds. Maybe that's just because of my C background :) 

Anyway, now I wrapped my head around this and it does not feel that strange anymore, and everyone else feels its OK - I guess we can close the bug?

**Comment by SkiFire13** [comment]
> Now I see, is it that index in range is considered to point to boundaries between values?

Yes, you think like that as well.

> Basically I assumed it points to values, something like this:

If that was the case then `2..2`, `2..3` and `3..3` would be somewhat inconsistent:

```
[ a , b , c ]
        ^--- 2..2
        ^^^^^--- 2..3 same as 2..2 but moves the end index to the right
            ^--- 3..3 same as 2..3 but moves the start index to the right. 
                      This can't possibly be out of bounds if both 2..2 and 2..3 are considered in bounds.
```

> So for (3..3) both start and end are out of bounds, making the whole range also out of bounds.

The end is in bounds because it's not inclusive though. 

> Maybe that's just because of my C background

AFAIK C has a similar behaviour where creating a pointer one past the end of an allocation is not UB. This is similar to that.

> Anyway, now I wrapped my head around this and it does not feel that strange anymore, and everyone else feels its OK - I guess we can close the bug?

That's up to either you or a moderator

**Comment by Aleksander-F** [comment]
Thanks for the explanations, I'm closing this then.
