### ISSUE TITLE
Compiling i868-pc-windows-gnu from x86_64-pc-windows-gnu toolchain, missing rust-mingw?

### ISSUE THREAD

**Issue by Chadehoc** [rust-lang/rust#85779]
I was using the msvc toolchains on Windows, and I'm now testing the gnu toolchain (expecting better vscode debugging).

I installed the `stable-x86_64-pc-windows-gnu` toolchain, and both `x86_64-pc-windows-gnu` and `i868-pc-windows-gnu` targets (I need both).

Building for x86-64 works, but building for i868 fails with `linker 'i686-w64-mingw32-gcc' not found`.

I tried to `rustup component add rust-mingw --target i686-pc-windows-gnu`, but this fails with:
`error: toolchain 'stable-x86_64-pc-windows-gnu' does not contain component 'rust-mingw' for 'target i686-pc-windows-gnu'`.

Note: `rust-mingw` does exist for target `x86_64-pc-windows-gnu`.

I searched the web to confirm the missing component but could not find anything.

Does this mean that compiling to 32 bits from a 64 bit Windows using the gnu toolchain is currently not possible?

**Comment by mati865** [comment]
Self contained mode currently works only for native compilation. To cross compile you have to provide mingw-w64 C toolchain in PATH, similary how you need MSVC toolchain for `windows-msvc` target.

**Comment by Dylan-DPC** [comment]
Closing this to clear up the issue tracker. If you or anyone reading this still needs help you can consult the forums, discords, etc for help. Thanks
