### ISSUE TITLE
Types of char predicates are inconsistent

### ISSUE THREAD

**Issue by osa1** [rust-lang/rust#85803]
I feel like this must be reported already, but I searched for it and couldn't find anything relevant.

`char` predicates (methods that return `bool`) are currently inconsistent in the receiver type: some are `self`, others are `&self`.

These ones have `self` receiver:

- is_alphabetic
- is_alphanumeric
- is_control
- is_lowercase
- is_numeric
- is_uppercase
- is_whitespace
- is_digit

These ones have `&self` receiver:

- is_ascii
- is_ascii_alphabetic
- is_ascii_alphanumeric
- is_ascii_control
- is_ascii_digit
- is_ascii_graphic
- is_ascii_hexdigit
- is_ascii_lowercase
- is_ascii_punctuation
- is_ascii_uppercase
- is_ascii_whitespace

I think both `self` and `&self` are fine, as long as it's consistent.

**Comment by r00ster91** [comment]
I've talked about this a while ago in #85300. The answer was that it probably wouldn't be backwards compatible to change at this point.

**Comment by osa1** [comment]
Thanks @r00ster91 . Closing this as duplicate.
