### ISSUE TITLE
rustc_lexer's definition of ids are more general than lang ref's spec

### ISSUE THREAD

**Issue by osa1** [rust-lang/rust#85809]
This is how Rust identifiers' lexical syntax is defined: https://doc.rust-lang.org/reference/identifiers.html
This is how the lexer for Rust identifiers is implemented: https://github.com/rust-lang/rust/blob/ce0d64e03ef9875e0935bb60e989542b7ec29579/compiler/rustc_lexer/src/lib.rs#L264-L297

The specification says it should start with ASCII alphabetic and continue with ASCII alphanumeric or underscore. But the implementation uses http://www.unicode.org/reports/tr31/#Default_Identifier_Syntax which is much more general than that as far as I understand.

I think one of code or lang ref should be updated, but I'm not sure which one.

(I didn't check lexing for other tokens, it might be useful to compare others with the language reference's definitions too)

**Comment by PatchMixolydic** [comment]
The reference is outdated due to the stabilization of [non-ASCII idents](https://doc.rust-lang.org/stable/unstable-book/language-features/non-ascii-idents.html) in 1.53 (tracking issue #55467).

**Comment by osa1** [comment]
Interesting, thanks @PatchMixolydic. I guess it would be helpful for the reader if we at least have a line in those documentations pointing to #55467.

**Comment by PatchMixolydic** [comment]
This seems to be fixed in the [nightly version of the Reference](https://doc.rust-lang.org/nightly/reference/identifiers.html).
