### ISSUE TITLE
`match` extends temporary lifetimes

### ISSUE THREAD

**Issue by matthew-mcallister** [rust-lang/rust#85827]
Consider this code:

```rust
fn panics(x: &RefCell<i32>) {
    match x.borrow().is_negative() {
        _ => { *x.borrow_mut() = 0 },
    }
}

fn succeeds(x: &RefCell<i32>) {
    let result = x.borrow().is_negative();
    match result {
        _ => { *x.borrow_mut() = 0 },
    }
}
```
On current nightly, `panics` panics at `borrow_mut()` while `succeeds` does not. The temporary `std::cell::Ref` created in the `match` scrutinee has its lifetime needlessly extended to cover the `match` body.

The Rust reference has the following to say about `match` (emphasis mine):
> If the scrutinee expression is a value expression, _it is first evaluated into a temporary location_, and the resulting value is sequentially compared to the patterns in the arms until a match is found.

Based on this statement, it seems like it was intended for the two functions to be equivalent. Hence, I believe the current behavior is a flaw in the compiler. However, changing this behavior does have the potential to break code.

**Comment by ehuss** [comment]
I believe this is working as intended.  The match scrutinee is only dropped after the end of the match expression. There is more in the [destructors chapter](https://doc.rust-lang.org/nightly/reference/destructors.html#temporary-scopes) which explains how drop scopes and temporaries work:

> The scrutinee of a match expression is not a temporary scope, so temporaries in the scrutinee can be dropped after the match expression. For example, the temporary for 1 in match 1 { ref mut z => z }; lives until the end of the statement.

**Comment by matthew-mcallister** [comment]
So, the language you cited does seem to indicate that this is _expected_ behavior (note the plural: "_temporaries_ in the scrutinee"), but it gives no examples relevant to my case. Without more information I'm not sure whether to believe this is _intended_ behavior or a consequence of the implementation. Extending the lifetime of the scrutinee seems obviously correct; extending the lifetime of temporaries involved in calculating the scrutinee does not.

I'm going to close this issue and create a discussion about this on internals. If there's any chance of the behavior changing, I can reopen it.

**Comment by gorilych** [comment]
@matthew-mcallister similar issue with `while` is described in rust book in [chapter 20](https://doc.rust-lang.org/book/ch20-02-multithreaded.html). I don't understand why mutexguard is not dropped right after recv() in listing 20-21 (as it happens inside loop in listing 20-20).

Can you share result of this discussion you were planning to create? Thanks in advance.

**Comment by matthew-mcallister** [comment]
@gorilych I [posted a comment](https://internals.rust-lang.org/t/lifetime-in-match-if-let-and-while-let/14304/6) on an existing thread about the same issue, but it hasn't resulted in any further discussion, unfortunately.

I haven't learned any more about the implementation since posting that, but my guess is that the compiler casts a very broad net to handle the case where the variable bound in a `match`/`while let` borrows a temporary value. I don't know how feasible it is to attempt to resolve this issue while still handling the latter case.
