### ISSUE TITLE
IntoIterator::IntoIter docs show incomplete trait bounds

### ISSUE THREAD

**Issue by chris-morgan** [rust-lang/rust#85858]
Refer to the [`std::iter::IntoIterator` docs](https://doc.rust-lang.org/std/iter/trait.IntoIterator.html) (and the problem is also visible on [nightly](https://doc.rust-lang.org/nightly/std/iter/trait.IntoIterator.html)).

It shows in both the declaration code and under the “Associated Types” heading: <sub>(<i>sans</i> semicolon in the latter)</sub>

```rust
type IntoIter: Iterator;
```

This is lacking a crucial part of the bound, the `Item` associated type. The source shows this:

```rust
type IntoIter: Iterator<Item = Self::Item>;
```

----

I’m confused about what’s going on here because my attempts at duplicating it are unsuccessful on both stable and nightly: when I compile the docs for just this code:

```rust
pub trait IntoIterator {
    type Item;
    type IntoIter: Iterator<Item = Self::Item>;
    fn into_iter(self) -> Self::IntoIter;
}
```

I see `Iterator<Item = Self::Item>` as expected, not `Iterator` as in the std docs. Hence my titling this bug about `IntoIterator::IntoIter`, rather than about associated types or whatnot, because I can’t reproduce it elsewhere.

**Comment by chris-morgan** [comment]
I just checked on old docs. Until [1.48.0](https://doc.rust-lang.org/1.48.0/std/iter/trait.IntoIterator.html), it looks like rustdoc translated that associated type bound to `where <Self::IntoIter as Iterator>::Item == Self::Item` in the declaration (or similar; back in 1.0.0 it was `where Self::IntoIter::Item == Self::Item`), but in [1.49](https://doc.rust-lang.org/1.49.0/std/iter/trait.IntoIterator.html) even that vanished.

No idea why it would be translating that associated type bound, especially since non-std docs aren’t doing it.

Haaaaaang on, *core* isn’t exhibiting this wonkiness either, [`core::iter::IntoIterator` is correct](https://doc.rust-lang.org/core/iter/trait.IntoIterator.html) (and never exhibited the translation into a where clause).

So I guess it’s something peculiar to std.

**Comment by veber-alex** [comment]
duplicate of #84579

**Comment by chris-morgan** [comment]
Ah hah, good find; thanks.
