### ISSUE TITLE
Add debugging flag to assert state of incremental cache

### ISSUE THREAD

**Issue by Aaron1011** [rust-lang/rust#85864]
In PR https://github.com/rust-lang/rust/pull/85702, I added a test that relies on the incremental cache still being saved if a linker error occurs. It would be good for the test to assert that this assumption is actually true. We could add a new flag `-Z assert-incr-state=<state>`, where `<state>` can be:

* `none` - we didn't find any previous session dirs whatsoever
* `mismatch` - we found an existing session dir, but did not load it to do a command-line arg hash mismatch.
* `loaded` - we found and loaded an existing session dir. Note that this says nothing about whether any particular query will be found to be red or green.

**Comment by Mark-Simulacrum** [comment]
It'd be good to add these flags to rustc-perf's incr tests once this flag is implemented, I think, FWIW.
