### ISSUE TITLE
thread 'rustc' panicked at 'assertion failed: args.args.len() == 2'

### ISSUE THREAD

**Issue by ctapang** [rust-lang/rust#85875]
This was while compiling code for the Solana blockchain (BPF code generation).

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

### Code
None
```Rust
<code>
```
BPF SDK: /home/ctapang/.local/share/solana/install/releases/1.6.9/solana-release/bin/sdk/bpf
Running: rustup toolchain list -v
Running: cargo +bpf build --target bpfel-unknown-unknown --release
   Compiling pyth v0.1.0 (/home/ctapang/ZeroInterestDeFi/anchor/oracles/pyth/programs/pyth)
thread 'rustc' panicked at 'assertion failed: args.args.len() == 2', /home/ctapang/.cargo/registry/src/github.com-1ecc6299db9ec823/anchor-syn-0.5.0/src/parser/accounts.rs:138:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.50.0-dev running on x86_64-unknown-linux-gnu

note: compiler flags: -C opt-level=3 -C embed-bitcode=no -C lto=no -C opt-level=2 -C link-arg=-z -C link-arg=notext -C link-arg=-T/home/ctapang/.local/share/solana/install/releases/1.6.9/solana-release/bin/sdk/bpf/rust/bpf.ld -C link-arg=--Bdynamic -C link-arg=-shared -C link-arg=--threads=1 -C link-arg=--entry=entrypoint -C linker=/home/ctapang/.local/share/solana/install/releases/1.6.9/solana-release/bin/sdk/bpf/dependencies/bpf-tools/llvm/bin/ld.lld --crate-type cdylib --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: proc-macro derive panicked
  --> programs/pyth/src/lib.rs:53:10
   |
53 | #[derive(Accounts)]
   |          ^^^^^^^^
   |
   = help: message: assertion failed: args.args.len() == 2

thread 'rustc' panicked at 'assertion failed: args.args.len() == 2', /home/ctapang/.cargo/registry/src/github.com-1ecc6299db9ec823/anchor-syn-0.5.0/src/parser/accounts.rs:138:13
stack backtrace:
   0:     0x7f2ff6d5ad9d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4d094f11c6d1fae4
   1:     0x7f2ff6e0b93f - core::fmt::write::hee4e18458909cd9b
   2:     0x7f2ff6d52b46 - std::io::Write::write_fmt::h608c39b63a445baa
   3:     0x7f2ff6d74555 - std::panicking::default_hook::{{closure}}::h7fcf068029967564
   4:     0x7f2ff6d740f6 - std::panicking::default_hook::hb6dbd96bd651ebe8
   5:     0x7f2ff7861538 - rustc_driver::report_ice::hd30e9f0d5c115aac
   6:     0x7f2ff6d74c08 - std::panicking::rust_panic_with_hook::hed63cda7675e9cb3
   7:     0x7f2ff6d5b1d7 - std::panicking::begin_panic_handler::{{closure}}::hb735b62048d020d4
   8:     0x7f2ff6d5aefc - std::sys_common::backtrace::__rust_end_short_backtrace::ha6c912f06cb6807c
   9:     0x7f2ff6d74762 - rust_begin_unwind
  10:     0x7f2fe8aa85e1 - core::panicking::panic_fmt::h88d1befd03709389
  11:     0x7f2fe8aa852d - core::panicking::panic::h879f53aa45bf615b
  12:     0x7f2fe86dde2f - anchor_syn::parser::accounts::parse_account::ha30f7b8a6db9c776
  13:     0x7f2fe86ddc8e - anchor_syn::parser::accounts::parse_program_account::hc47ce0a9f8169b19
  14:     0x7f2fe86dd866 - anchor_syn::parser::accounts::parse_ty::h3c63145c41ce6b35
  15:     0x7f2fe86dcdda - anchor_syn::parser::accounts::parse_field::hf16949f23c29d96c
  16:     0x7f2fe86dc8d7 - anchor_syn::parser::accounts::parse_account_field::h6a8a7caef59c1af5
  17:     0x7f2fe86ea73b - core::ops::function::FnMut::call_mut::h7d3efde29e544052
  18:     0x7f2fe86db2af - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once::hc5ef55d7e39788a6
  19:     0x7f2fe86e75c6 - core::option::Option<T>::map::hbe5a45677e2d7197
  20:     0x7f2fe872587c - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next::h6b535dfeb0e7fc1f
  21:     0x7f2fe870ca3c - <alloc::vec::Vec<T> as alloc::vec::SpecFromIterNested<T,I>>::from_iter::h8d4d771ea4b3d537
  22:     0x7f2fe870355e - <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter::h63ecc18a52529e2c
  23:     0x7f2fe870e86c - <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter::h2e4f034d627f0046
  24:     0x7f2fe8726ebe - core::iter::traits::iterator::Iterator::collect::hf9a19a6a5bf074de
  25:     0x7f2fe86dc7f3 - anchor_syn::parser::accounts::parse::he47c8b76cd75a537
  26:     0x7f2fe86c7bd6 - anchor_derive_accounts::derive_anchor_deserialize::h3e3cdd88b38dd4cf
  27:     0x7f2fe86c6b90 - core::ops::function::FnOnce::call_once::h8c1c79d3ac75d480
  28:     0x7f2fe86c68d1 - proc_macro::bridge::client::Client<fn(proc_macro::TokenStream) .> proc_macro::TokenStream>::expand1::run::{{closure}}::hd3cf536c7d502ba0
  29:     0x7f2fe86c5fae - proc_macro::bridge::client::run_client::{{closure}}::{{closure}}::haa688c35b9b85cbc
  30:     0x7f2fe86c7d7e - proc_macro::bridge::scoped_cell::ScopedCell<T>::set::{{closure}}::ha651b2c017a6b425
  31:     0x7f2fe86c84e5 - proc_macro::bridge::scoped_cell::ScopedCell<T>::replace::hd8dde1be54f0a5f1
  32:     0x7f2fe86c7d5e - proc_macro::bridge::scoped_cell::ScopedCell<T>::set::h1bb06e4f5bd2e7db
  33:     0x7f2fe86c66e5 - proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}::h5d9c6cb5525facb4
  34:     0x7f2fe86c8da5 - std::thread::local::LocalKey<T>::try_with::ha88d4d2ad695635e
  35:     0x7f2fe86c8972 - std::thread::local::LocalKey<T>::with::h3b1e45f4fff761c2
  36:     0x7f2fe86c794d - proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::h5b227e95cec0727d
  37:     0x7f2fe86c5e04 - proc_macro::bridge::client::run_client::{{closure}}::h94c20a33326d4aae
  38:     0x7f2fe86c6922 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h48470f0a1f1ff60a
  39:     0x7f2fe86c70ea - std::panicking::try::do_call::he1662b29c9f730ca
  40:     0x7f2fe86c717d - __rust_try
  41:     0x7f2fe86c7038 - std::panicking::try::h044289a10254e350
  42:     0x7f2fe86c6962 - std::panic::catch_unwind::hf4e11901d64661b6
  43:     0x7f2fe86c5cf4 - proc_macro::bridge::client::run_client::hf8c92d869139c59b
  44:     0x7f2fe86c6888 - proc_macro::bridge::client::Client<fn(proc_macro::TokenStream) .> proc_macro::TokenStream>::expand1::run::h56ffb5f45684d89f
  45:     0x7f2ffb544340 - proc_macro::bridge::server::run_server::h96813f1c815b69b3
  46:     0x7f2ffb4b1643 - <rustc_expand::proc_macro::ProcMacroDerive as rustc_expand::base::MultiItemModifier>::expand::h9e842d1896c6a6a9
  47:     0x7f2ffb487f81 - rustc_expand::expand::MacroExpander::fully_expand_fragment::h0d8a5d69d105a7eb
  48:     0x7f2ffb48680e - rustc_expand::expand::MacroExpander::expand_crate::h8dab1482e5ff92b3
  49:     0x7f2ff7a54ea5 - rustc_session::utils::<impl rustc_session::session::Session>::time::h41eeefafff1a2b29
  50:     0x7f2ff7a92a42 - rustc_interface::passes::configure_and_expand_inner::ha1192a0f3ed73a37
  51:     0x7f2ff7a6d6b5 - rustc_interface::passes::configure_and_expand::{{closure}}::h12607b2f5ac9214a
  52:     0x7f2ff7a57eff - rustc_data_structures::box_region::PinnedGenerator<I,A,R>::new::h58c3e7fbc253c5d3
  53:     0x7f2ff7a91a28 - rustc_interface::passes::configure_and_expand::h48f4c81ae966d949
  54:     0x7f2ff7ae8b6b - rustc_interface::queries::Queries::expansion::hc64a04bca0eeea1c
  55:     0x7f2ff788ae7a - rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter::h9bc4461b6aabd507
  56:     0x7f2ff78654ae - rustc_span::with_source_map::h26c48c2cdad6abd9
  57:     0x7f2ff788c6ab - rustc_interface::interface::create_compiler_and_run::h5c9b80ce01efaab3
  58:     0x7f2ff78720ce - std::sys_common::backtrace::__rust_begin_short_backtrace::ha8b7e25ac30bb25e
  59:     0x7f2ff77f55ba - core::ops::function::FnOnce::call_once{{vtable.shim}}::h5961306880424669
  60:     0x7f2ff6d8c628 - std::sys::unix::thread::Thread::new::thread_start::h1884a1703ae6269b
  61:     0x7f2ff6a85609 - start_thread
  62:     0x7f2ff6bf0293 - clone
  63:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.50.0-dev running on x86_64-unknown-linux-gnu

note: compiler flags: -C opt-level=3 -C embed-bitcode=no -C lto=no -C opt-level=2 -C link-arg=-z -C link-arg=notext -C link-arg=-T/home/ctapang/.local/share/solana/install/releases/1.6.9/solana-release/bin/sdk/bpf/rust/bpf.ld -C link-arg=--Bdynamic -C link-arg=-shared -C link-arg=--threads=1 -C link-arg=--entry=entrypoint -C linker=/home/ctapang/.local/share/solana/install/releases/1.6.9/solana-release/bin/sdk/bpf/dependencies/bpf-tools/llvm/bin/ld.lld --crate-type cdylib --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
thread panicked while panicking. aborting.
error: could not compile `pyth`

Caused by:
  process didn't exit successfully: `rustc --crate-name pyth --edition=2018 programs/pyth/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type cdylib --crate-type lib --emit=dep-info,link -C opt-level=3 -C embed-bitcode=no --cfg 'feature="default"' -C metadata=9ffd3684fb3a5252 --out-dir /home/ctapang/ZeroInterestDeFi/anchor/oracles/pyth/target/bpfel-unknown-unknown/release/deps --target bpfel-unknown-unknown -L dependency=/home/ctapang/ZeroInterestDeFi/anchor/oracles/pyth/target/bpfel-unknown-unknown/release/deps -L dependency=/home/ctapang/ZeroInterestDeFi/anchor/oracles/pyth/target/release/deps --extern anchor_lang=/home/ctapang/ZeroInterestDeFi/anchor/oracles/pyth/target/bpfel-unknown-unknown/release/deps/libanchor_lang-74e45ae127bb366e.rlib --extern arrayref=/home/ctapang/ZeroInterestDeFi/anchor/oracles/pyth/target/bpfel-unknown-unknown/release/deps/libarrayref-6503040a6a40a0df.rlib --extern bytemuck=/home/ctapang/ZeroInterestDeFi/anchor/oracles/pyth/target/bpfel-unknown-unknown/release/deps/libbytemuck-7de800506119200b.rlib --extern pyth_client=/home/ctapang/ZeroInterestDeFi/anchor/oracles/pyth/target/bpfel-unknown-unknown/release/deps/libpyth_client-a115789c07028cbc.rlib --extern solana_program=/home/ctapang/ZeroInterestDeFi/anchor/oracles/pyth/target/bpfel-unknown-unknown/release/deps/libsolana_program-d6494e24123b9296.rlib -C lto=no -C opt-level=2 -C link-arg=-z -C link-arg=notext -C link-arg=-T/home/ctapang/.local/share/solana/install/releases/1.6.9/solana-release/bin/sdk/bpf/rust/bpf.ld -C link-arg=--Bdynamic -C link-arg=-shared -C link-arg=--threads=1 -C link-arg=--entry=entrypoint -C linker=/home/ctapang/.local/share/solana/install/releases/1.6.9/solana-release/bin/sdk/bpf/dependencies/bpf-tools/llvm/bin/ld.lld` (signal: 4, SIGILL: illegal instruction)
### Meta

`rustc --version --verbose`:
```
<version>
```

### Error output

```
<output>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by jyn514** [comment]
1.50 is quite out of date, can you reproduce this with 1.54-nightly? Also, 1.50-dev sounds like this is a fork of the rust compiler, please try it with an official binary.

**Comment by ctapang** [comment]
BPF SDK: /home/ctapang/.local/share/solana/install/releases/1.6.9/solana-release/bin/sdk/bpf
Running: rustup toolchain list -v
Running: cargo +bpf build --target bpfel-unknown-unknown --release
   Compiling pyth v0.1.0 (/home/ctapang/ZeroInterestDeFi/anchor/oracles/pyth/programs/pyth)
thread 'rustc' panicked at 'assertion failed: args.args.len() == 2', /home/ctapang/.cargo/registry/src/github.com-1ecc6299db9ec823/anchor-syn-0.5.0/src/parser/accounts.rs:138:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.50.0-dev running on x86_64-unknown-linux-gnu

note: compiler flags: -C opt-level=3 -C embed-bitcode=no -C lto=no -C opt-level=2 -C link-arg=-z -C link-arg=notext -C link-arg=-T/home/ctapang/.local/share/solana/install/releases/1.6.9/solana-release/bin/sdk/bpf/rust/bpf.ld -C link-arg=--Bdynamic -C link-arg=-shared -C link-arg=--threads=1 -C link-arg=--entry=entrypoint -C linker=/home/ctapang/.local/share/solana/install/releases/1.6.9/solana-release/bin/sdk/bpf/dependencies/bpf-tools/llvm/bin/ld.lld --crate-type cdylib --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: proc-macro derive panicked
  --> programs/pyth/src/lib.rs:53:10
   |
53 | #[derive(Accounts)]
   |          ^^^^^^^^
   |
   = help: message: assertion failed: args.args.len() == 2

thread 'rustc' panicked at 'assertion failed: args.args.len() == 2', /home/ctapang/.cargo/registry/src/github.com-1ecc6299db9ec823/anchor-syn-0.5.0/src/parser/accounts.rs:138:13
stack backtrace:
   0:     0x7f3529c73d9d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4d094f11c6d1fae4
   1:     0x7f3529d2493f - core::fmt::write::hee4e18458909cd9b
   2:     0x7f3529c6bb46 - std::io::Write::write_fmt::h608c39b63a445baa
   3:     0x7f3529c8d555 - std::panicking::default_hook::{{closure}}::h7fcf068029967564
   4:     0x7f3529c8d0f6 - std::panicking::default_hook::hb6dbd96bd651ebe8
   5:     0x7f352a77a538 - rustc_driver::report_ice::hd30e9f0d5c115aac
   6:     0x7f3529c8dc08 - std::panicking::rust_panic_with_hook::hed63cda7675e9cb3
   7:     0x7f3529c741d7 - std::panicking::begin_panic_handler::{{closure}}::hb735b62048d020d4
   8:     0x7f3529c73efc - std::sys_common::backtrace::__rust_end_short_backtrace::ha6c912f06cb6807c
   9:     0x7f3529c8d762 - rust_begin_unwind
  10:     0x7f351b9c35e1 - core::panicking::panic_fmt::h88d1befd03709389
  11:     0x7f351b9c352d - core::panicking::panic::h879f53aa45bf615b
  12:     0x7f351b5f8e2f - anchor_syn::parser::accounts::parse_account::ha30f7b8a6db9c776
  13:     0x7f351b5f8c8e - anchor_syn::parser::accounts::parse_program_account::hc47ce0a9f8169b19
  14:     0x7f351b5f8866 - anchor_syn::parser::accounts::parse_ty::h3c63145c41ce6b35
  15:     0x7f351b5f7dda - anchor_syn::parser::accounts::parse_field::hf16949f23c29d96c
  16:     0x7f351b5f78d7 - anchor_syn::parser::accounts::parse_account_field::h6a8a7caef59c1af5
  17:     0x7f351b60573b - core::ops::function::FnMut::call_mut::h7d3efde29e544052
  18:     0x7f351b5f62af - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once::hc5ef55d7e39788a6
  19:     0x7f351b6025c6 - core::option::Option<T>::map::hbe5a45677e2d7197
  20:     0x7f351b64087c - <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next::h6b535dfeb0e7fc1f
  21:     0x7f351b627a3c - <alloc::vec::Vec<T> as alloc::vec::SpecFromIterNested<T,I>>::from_iter::h8d4d771ea4b3d537
  22:     0x7f351b61e55e - <alloc::vec::Vec<T> as alloc::vec::SpecFromIter<T,I>>::from_iter::h63ecc18a52529e2c
  23:     0x7f351b62986c - <alloc::vec::Vec<T> as core::iter::traits::collect::FromIterator<T>>::from_iter::h2e4f034d627f0046
  24:     0x7f351b641ebe - core::iter::traits::iterator::Iterator::collect::hf9a19a6a5bf074de
  25:     0x7f351b5f77f3 - anchor_syn::parser::accounts::parse::he47c8b76cd75a537
  26:     0x7f351b5e2bd6 - anchor_derive_accounts::derive_anchor_deserialize::h3e3cdd88b38dd4cf
  27:     0x7f351b5e1b90 - core::ops::function::FnOnce::call_once::h8c1c79d3ac75d480
  28:     0x7f351b5e18d1 - proc_macro::bridge::client::Client<fn(proc_macro::TokenStream) .> proc_macro::TokenStream>::expand1::run::{{closure}}::hd3cf536c7d502ba0
  29:     0x7f351b5e0fae - proc_macro::bridge::client::run_client::{{closure}}::{{closure}}::haa688c35b9b85cbc
  30:     0x7f351b5e2d7e - proc_macro::bridge::scoped_cell::ScopedCell<T>::set::{{closure}}::ha651b2c017a6b425
  31:     0x7f351b5e34e5 - proc_macro::bridge::scoped_cell::ScopedCell<T>::replace::hd8dde1be54f0a5f1
  32:     0x7f351b5e2d5e - proc_macro::bridge::scoped_cell::ScopedCell<T>::set::h1bb06e4f5bd2e7db
  33:     0x7f351b5e16e5 - proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}::h5d9c6cb5525facb4
  34:     0x7f351b5e3da5 - std::thread::local::LocalKey<T>::try_with::ha88d4d2ad695635e
  35:     0x7f351b5e3972 - std::thread::local::LocalKey<T>::with::h3b1e45f4fff761c2
  36:     0x7f351b5e294d - proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::h5b227e95cec0727d
  37:     0x7f351b5e0e04 - proc_macro::bridge::client::run_client::{{closure}}::h94c20a33326d4aae
  38:     0x7f351b5e1922 - <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h48470f0a1f1ff60a
  39:     0x7f351b5e20ea - std::panicking::try::do_call::he1662b29c9f730ca
  40:     0x7f351b5e217d - __rust_try
  41:     0x7f351b5e2038 - std::panicking::try::h044289a10254e350
  42:     0x7f351b5e1962 - std::panic::catch_unwind::hf4e11901d64661b6
  43:     0x7f351b5e0cf4 - proc_macro::bridge::client::run_client::hf8c92d869139c59b
  44:     0x7f351b5e1888 - proc_macro::bridge::client::Client<fn(proc_macro::TokenStream) .> proc_macro::TokenStream>::expand1::run::h56ffb5f45684d89f
  45:     0x7f352e45d340 - proc_macro::bridge::server::run_server::h96813f1c815b69b3
  46:     0x7f352e3ca643 - <rustc_expand::proc_macro::ProcMacroDerive as rustc_expand::base::MultiItemModifier>::expand::h9e842d1896c6a6a9
  47:     0x7f352e3a0f81 - rustc_expand::expand::MacroExpander::fully_expand_fragment::h0d8a5d69d105a7eb
  48:     0x7f352e39f80e - rustc_expand::expand::MacroExpander::expand_crate::h8dab1482e5ff92b3
  49:     0x7f352a96dea5 - rustc_session::utils::<impl rustc_session::session::Session>::time::h41eeefafff1a2b29
  50:     0x7f352a9aba42 - rustc_interface::passes::configure_and_expand_inner::ha1192a0f3ed73a37
  51:     0x7f352a9866b5 - rustc_interface::passes::configure_and_expand::{{closure}}::h12607b2f5ac9214a
  52:     0x7f352a970eff - rustc_data_structures::box_region::PinnedGenerator<I,A,R>::new::h58c3e7fbc253c5d3
  53:     0x7f352a9aaa28 - rustc_interface::passes::configure_and_expand::h48f4c81ae966d949
  54:     0x7f352aa01b6b - rustc_interface::queries::Queries::expansion::hc64a04bca0eeea1c
  55:     0x7f352a7a3e7a - rustc_interface::queries::<impl rustc_interface::interface::Compiler>::enter::h9bc4461b6aabd507
  56:     0x7f352a77e4ae - rustc_span::with_source_map::h26c48c2cdad6abd9
  57:     0x7f352a7a56ab - rustc_interface::interface::create_compiler_and_run::h5c9b80ce01efaab3
  58:     0x7f352a78b0ce - std::sys_common::backtrace::__rust_begin_short_backtrace::ha8b7e25ac30bb25e
  59:     0x7f352a70e5ba - core::ops::function::FnOnce::call_once{{vtable.shim}}::h5961306880424669
  60:     0x7f3529ca5628 - std::sys::unix::thread::Thread::new::thread_start::h1884a1703ae6269b
  61:     0x7f352999e609 - start_thread
  62:     0x7f3529b09293 - clone
  63:                0x0 - <unknown>

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.50.0-dev running on x86_64-unknown-linux-gnu

note: compiler flags: -C opt-level=3 -C embed-bitcode=no -C lto=no -C opt-level=2 -C link-arg=-z -C link-arg=notext -C link-arg=-T/home/ctapang/.local/share/solana/install/releases/1.6.9/solana-release/bin/sdk/bpf/rust/bpf.ld -C link-arg=--Bdynamic -C link-arg=-shared -C link-arg=--threads=1 -C link-arg=--entry=entrypoint -C linker=/home/ctapang/.local/share/solana/install/releases/1.6.9/solana-release/bin/sdk/bpf/dependencies/bpf-tools/llvm/bin/ld.lld --crate-type cdylib --crate-type lib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
thread panicked while panicking. aborting.
error: could not compile `pyth`

Caused by:
  process didn't exit successfully: `rustc --crate-name pyth --edition=2018 programs/pyth/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type cdylib --crate-type lib --emit=dep-info,link -C opt-level=3 -C embed-bitcode=no --cfg 'feature="default"' -C metadata=9ffd3684fb3a5252 --out-dir /home/ctapang/ZeroInterestDeFi/anchor/oracles/pyth/target/bpfel-unknown-unknown/release/deps --target bpfel-unknown-unknown -L dependency=/home/ctapang/ZeroInterestDeFi/anchor/oracles/pyth/target/bpfel-unknown-unknown/release/deps -L dependency=/home/ctapang/ZeroInterestDeFi/anchor/oracles/pyth/target/release/deps --extern anchor_lang=/home/ctapang/ZeroInterestDeFi/anchor/oracles/pyth/target/bpfel-unknown-unknown/release/deps/libanchor_lang-74e45ae127bb366e.rlib --extern arrayref=/home/ctapang/ZeroInterestDeFi/anchor/oracles/pyth/target/bpfel-unknown-unknown/release/deps/libarrayref-6503040a6a40a0df.rlib --extern bytemuck=/home/ctapang/ZeroInterestDeFi/anchor/oracles/pyth/target/bpfel-unknown-unknown/release/deps/libbytemuck-7de800506119200b.rlib --extern pyth_client=/home/ctapang/ZeroInterestDeFi/anchor/oracles/pyth/target/bpfel-unknown-unknown/release/deps/libpyth_client-a115789c07028cbc.rlib --extern solana_program=/home/ctapang/ZeroInterestDeFi/anchor/oracles/pyth/target/bpfel-unknown-unknown/release/deps/libsolana_program-d6494e24123b9296.rlib -C lto=no -C opt-level=2 -C link-arg=-z -C link-arg=notext -C link-arg=-T/home/ctapang/.local/share/solana/install/releases/1.6.9/solana-release/bin/sdk/bpf/rust/bpf.ld -C link-arg=--Bdynamic -C link-arg=-shared -C link-arg=--threads=1 -C link-arg=--entry=entrypoint -C linker=/home/ctapang/.local/share/solana/install/releases/1.6.9/solana-release/bin/sdk/bpf/dependencies/bpf-tools/llvm/bin/ld.lld` (signal: 4, SIGILL: illegal instruction)

**Comment by ctapang** [comment]
I upgraded to nightly-2021-05-31-x86_64-unknown-linux-gnu and I lost the bpf code generation feature. So yeah, I must have been using a fork specifically for the Solana blockchain.
I tried "cargo build" instead of "cargo build-bpf" and I get that same error (my problem, not a compiler issue), but no crash:

![image](https://user-images.githubusercontent.com/2825510/120269817-64927900-c25d-11eb-8474-19f25a905ca1.png)

**Comment by jyn514** [comment]
That's a bug in a proc macro you're using, not in the compiler itself.
