### ISSUE TITLE
Create group containing all Rust 2021 edition lints

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#85894]
As follow up to #85512, we need to create a group containing all "Rust 2021 migration"-related lints. Let's start by logging them in the comments here.

**Comment by nikomatsakis** [comment]
This isn't really blocked on #85512, it's just not as useful without it.

**Comment by m-ou-se** [comment]
`non_fmt_panic`

**Comment by m-ou-se** [comment]
1. Prelude changes:
    - `future_prelude_collision` (Not ready yet: https://github.com/rust-lang/rust/pull/85707)
2. Panic consistency:
    - `non_fmt_panic`
3. Lints -> hard errors
    - `bare_trait_object`
    - `ellipsis_inclusive_range_patterns`
4. Disjoint captures
    - `disjoint_capture_drop_reorder`
5. Cargo resolver 2
    - \-
6. IntoIterator for arrays
   - `array_into_iter`
7. Or patterns
    - `or_patterns_back_compat`
8. Reserving syntax
    - TBD

**Comment by bookofportals** [comment]
@rusbot +A-lint +T-compiler

**Comment by bookofportals** [comment]
_Sigh._ I apologize for the double message.

@rustbot +A-lint +T-compiler

**Comment by m-ou-se** [comment]
Re-opening since there's still a few left to do.

**Comment by m-ou-se** [comment]
We might want to change the name of some of these lints, if we still can. E.g. `deny(disjoint_capture_migration)` doesn't sound like what it does.

**Comment by inquisitivecrystal** [comment]
If we don't have a way to add lint aliases, we should add that. I've come up with some possible lint renamings, based on [the relevant guidelines](https://rustc-dev-guide.rust-lang.org/diagnostics.html#lint-naming), though there are quite possibly better ones that still comply with the guidelines. As an aside, why are so many lints being added with noncompliant names? 

**Meaning**
`or_patterns_back_compat` -> `pipes_after_pat_metavariables`
`array_into_iter` -> `ambiguous_array_into_iter_derefs`
`disjoint_capture_migration` -> `disjoint_capture_drop_reorder` (existing lint which I presume is related, preferably and an "ing" at the end to make it sound right with allow/deny/forbid), or maybe something like `reliance_on_joint_captures`

**Plurality**
`future_prelude_collision` -> `future_prelude_collisions`
`non_fmt_panic` -> `non_fmt_panics`
`bare_trait_object` -> `bare_trait_objects`
`reserved_prefix` -> `reserved_prefixes`

**Comment by m-ou-se** [comment]
@inquisitivecrystal Thank you! That's very helpful.

We'll have to check which of these we can still change without causing too much churn.

> As an aside, why are so many lints being added with noncompliant names?

It just seems that many contributors and reviewers aren't aware of the guidelines. (I wasn't aware until someone pointed it out after I added a lint with a noncompliant name.)

> disjoint_capture_drop_reorder

This one also warns about changed Sync/Send implementations on closures. Might make it a bit tricky to find a proper name for it.

> Plurality

Oh, heh, I completely missed that part of the guideline.

**Comment by nikomatsakis** [comment]
We should rename `disjoint_capture_migration`, but `disjoint_capture_drop_reorder` doesn't sound right because it's incomplete. I think I like something like `edition_incompatible_closure_captures`?

**Comment by nikomatsakis** [comment]
This prefix (`rust_2021_incompatible`) makes sense for things that are "allow by default" -- that is, something you wouldn't warn about except as part of a migration.

**Comment by rylev** [comment]
With #86717 merged, we can close this issue.
