### ISSUE TITLE
proc_macro_hygiene not infer type

### ISSUE THREAD

**Issue by botika** [rust-lang/rust#85917]
I want to do something similar to this. 

#### Proc macro
```rust
fn proc_macro(input: TokenStream) -> TokenStream {
  let code = quote!{{
    let some = Trait::constructor();
    some
  }};
  code.into()
}
```

#### Main
```rust
let some: Type = proc_macro!();
```
But I get an error because it cannot infer the type `Type`. I think it should be able to infer this type? Any ideas? 

Thanks!

**Comment by Aaron1011** [comment]
@botika - it doesn't look like this is specific to proc-macros. Can you provide a self-contained example that I can run?

**Comment by botika** [comment]
Yes, it is reproduced in the `simple` example of `yarte`. Now I upload a branch `rust-lang-85917` with the clean case.
https://github.com/botika/yarte/blob/master/examples/simple/src/main.rs 

I'll explain you, `yarte` use the `Buffer` trait for write, it has a constructor and I want to define the specific type by inference (`String`, `Vec<u8>`, `BytesMut`,..). 

Thank you very much for the quick answer. Feel free to change the title to the one that is more descriptive.

**Comment by Aaron1011** [comment]
Minimized:

```rust
trait Foo {
    fn make_it() -> Self where Self: Sized;
}

impl Foo for String {
    fn make_it() -> Self {
        String::new()
    }
}

fn main() {
    let val: String = {
        let tmp = Foo::make_it();
        tmp.len();
        tmp
    };
}
```

The above code produces the following error:

```
error[E0282]: type annotations needed
  --> src/main.rs:14:9
   |
13 |         let tmp = Foo::make_it();
   |             --- consider giving `tmp` a type
14 |         tmp.len();
   |         ^^^ cannot infer type
   |
   = note: type must be known at this point
```

rustc will not infer the type of `tmp` to be `String` in this case.

I think part of the confusion stems from the fact that Rust cannot currently produce error messages that point inside a call to `quote! { }` (in this case, to [`__buf.len()`](https://github.com/botika/yarte/blob/d53bb8a06af7218b8ae9e2bd772ee6d5488dcbfb/yarte_derive/src/lib.rs#L572)). Issue https://github.com/dtolnay/quote/issues/184 tracks adding support for this.

**Comment by botika** [comment]
Ok, I'll keep investigating and specify it as `String` for now. Thank you. I close.
