### ISSUE TITLE
rustdoc: make trait methods findable with Ctrl-F

### ISSUE THREAD

**Issue by jsha** [rust-lang/rust#85923]
When looking at a struct or enum page, it's common to look for a method with Ctrl-F. This works if the method is part of an inherent implementation (that is, a method on the struct or enum itself). But if the method is part of a trait implementation, Ctrl-F won't find it because trait implementations are toggled closed by default.

I'm not sure of a great way to do this. Some ideas:

 - Listen for Ctrl-F and temporarily open the toggles. Problems: This is probably flaky; it doesn't work when selecting "Find in page" from a menu; we probably wouldn't get any sort of even to know when to close them again.
 - Implement our own in-page search, and override Ctrl-F. Personally I find it really unpleasant when pages do this; I think the browser functionality shouldn't be overridden.
 - Make the trait implementation toggles opened by default. I don't know the pros/cons on this; I assume they are closed by default for a good reason.

**Comment by jyn514** [comment]
> Make the trait implementation toggles opened by default. I don't know the pros/cons on this; I assume they are closed by default for a good reason.

This is my preference, people are often confused where to find functionality when it's hidden behind a trait.

**Comment by jsha** [comment]
It looks like this is the PR that added toggles for trait implementations, with links to some of the issues it was trying to solve: https://github.com/rust-lang/rust/pull/47894. The PR has some discussion about hiding by default. It also links to some issues, like https://github.com/rust-lang/rust/issues/40363.

**Comment by jsha** [comment]
Fixed in #86260
