### ISSUE TITLE
Suggest using `-> impl Trait` when returning type parameter `-> T where T: Trait`

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#85991]
Some newcomers are confused by `impl Trait` in return position because they have first internalized `impl Trait` as an alias for type parameters in argument position. Because of this, some people try the following:

```rust
trait Trait {}
impl Trait for () {}

// this works
fn foo() -> impl Trait {
    ()
}

// this doesn't
fn bar<T: Trait>() -> T {
    ()
}
```

We don't currently point them in the right direction, like we do in other cases.

_Took inspiration from https://twitter.com/JaapRood/status/1400782159812628482_

**Comment by jackh726** [comment]
Should have been closed by #89892
