### ISSUE TITLE
Tracking Issue for `Bound::map`

### ISSUE THREAD

**Issue by glittershark** [rust-lang/rust#86026]
Feature gate: `#![feature(bound_map)]`

This is a tracking issue for providing a `map` method on `Bound`. This method calls a function on the contained value of a `Bound` (including both `Included` and `Exclcuded`, returning a `Bound` of the same kind.

### Public API

```rust
impl<T> Bound<T> {
    pub fn map<U, F: FnOnce(T) -> U>(self, f: F) -> Bound<U>;
}
```

### Steps / History

- [x] Implementation: #83646 
- [ ] Final commenting period (FCP)
- [ ] Stabilization PR

### Unresolved Questions

- None yet.

**Comment by bonsairobo** [comment]
What's the time frame for the final commenting period? I'd like to use this API.

**Comment by Amanieu** [comment]
This seems to be a generally useful method and a use case was presented in https://github.com/rust-lang/rust/pull/83646#issuecomment-847099320.

@rfcbot fcp merge

**Comment by Ekleog** [comment]
Linking this here in case others didn't notice the stabilization PR, as it's above the FCP completion message: the stabilization PR is available at https://github.com/rust-lang/rust/pull/118361 :)
