### ISSUE TITLE
Default panic message prints the type `Box<dyn Any>` as `Box<Any>` 

### ISSUE THREAD

**Issue by steffahn** [rust-lang/rust#86039]
```rust
use std::panic::panic_any;
fn main() {
    panic_any(42);
}

```
```
   Compiling playground v0.0.1 (/playground)
    Finished dev [unoptimized + debuginfo] target(s) in 1.48s
     Running `target/debug/playground`
thread 'main' panicked at 'Box<Any>', src/main.rs:3:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=e2ba839751077c76ba697726afb8ffd4))

I would’ve expected it to say
```
thread 'main' panicked at 'Box<dyn Any>', src/main.rs:3:5
```

Relevant point in `std` seems to be [here](https://doc.rust-lang.org/nightly/src/std/panicking.rs.html#196).

@rustbot label C-enhancement, T-libs

**Comment by bookofportals** [comment]
Wow, `E-easy` issues really do go fast. Best of luck, reaganmcf!
