### ISSUE TITLE
Inert attributes in `$expr` nonterminals are sometimes duplicated

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rust#86055]
Reproducer:
```rust
macro mac($expr:expr) {
    print_bang!($expr);
}

fn main() {
    mac!(#[allow(warnings)] 0);
}
```
where `print_bang` is a proc macro from https://github.com/rust-lang/rust/blob/master/src/test/ui/proc-macro/auxiliary/test-macros.rs

The result looks like this:
```
PRINT-BANG INPUT (DISPLAY): #[allow(warnings)] 0
PRINT-BANG RE-COLLECTED (DISPLAY): #[allow(warnings)] #[allow(warnings)] 0
```

The issue can be reproduced after merging #84995, before that PR the example ICEs.

**Comment by bvanjoi** [comment]
It appears that ﻿`parse_expr_force_collect` has caused duplication of the `﻿Expr` between the ﻿`attrs` and `﻿tokens`. Can we remove these duplicated ﻿`attrs` by comparing ﻿`tokens` and ﻿`attrs`?
