### ISSUE TITLE
How to compile rust-lang/rust with openssl 3.0.0 rust-openssl patches

### ISSUE THREAD

**Issue by satya-rajesh** [rust-lang/rust#86088]
As rust-lang is having a second level dependency on rust-openssl, how to compile rust-lang with openssl 3.0.0 patches from rust-openssl:
https://github.com/sfackler/rust-openssl/pull/1264

Detailed steps will be appreciated.

**Comment by jyn514** [comment]
Duplicate of https://github.com/rust-lang/rust/issues/79592 (which you also opened). Please stop filing issues about this until 3.0.0 is released, they will not make support come any sooner.
