### ISSUE TITLE
[ER] A missed removal of division by zero test

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust#86109]
This function foo:

```rust
type T = i16;

pub fn foo(start: T) -> T {
    if start <= 0 { return 0; }
    let mut count = 0;
    for i in start .. 10_000 {
        if 752 % i != 0 {
            count += 1;
        }
    }
    count
}

fn main() {
    println!("{}", (T::MIN ..= T::MAX)
                   .map(foo)
                   .sum::<T>());
}
```

Compiled with optimizations by rustc (1.54.0-nightly 4de757209 2021-05-01) gives:

```asm
foo:
        lea     eax, [rdi - 1]
        movzx   eax, ax
        cmp     eax, 9998
        ja      .LBB0_1
        mov     r8d, 9999
        sub     r8d, edi
        mov     esi, edi
        neg     esi
        xor     ecx, ecx
.LBB0_4:
        cmp     r8w, si
        jae     .LBB0_6
        mov     ax, 752
        xor     edx, edx
        idiv    di
        lea     eax, [rdi + 1]
        cmp     dx, 1
        sbb     cx, -1
        movzx   edx, ax
        mov     edi, eax
        cmp     edx, 10000
        jne     .LBB0_4
        mov     eax, ecx
        ret
.LBB0_1:
        xor     ecx, ecx
        mov     eax, ecx
        ret
.LBB0_6:
        push    rax
        lea     rdi, [rip + str.0]
        lea     rdx, [rip + .L__unnamed_1]
        mov     esi, 57
        call    qword ptr [rip + core::panicking::panic@GOTPCREL]
        ud2

str.0:
        .ascii  "attempt to calculate the remainder with a divisor of zero"
```

Running the code you confirm that the divisor can't be zero.
I think Rustc should be able to remove this test.
(The same code with `T=u16` contains no division by zero test).

**Comment by klensy** [comment]
Still an issue. I think this is similar to the same problem with (missed) optimizations, when we match on some variable and expect compiler to match on `values` of that variable, not on it's `type`.

For provided example we can cast i16 to u16 after check, so panic go away:
```rust
pub fn foo(start: T) -> T {
    if start <= 0 { return 0; }
    let start = start as u16; // add this to change type
    let mut count = 0;
    ...
```

**Comment by leonardo-m** [comment]
Note that with rustc 1.60.0-nightly (08df8b81d 2022-01-30) replacing in my original foo code the "for i in start .. 10_000 {" with an equivalent while loop is enough to remove the dividend test.

**Comment by klensy** [comment]
> Note that with rustc 1.60.0-nightly ([08df8b8](https://github.com/rust-lang/rust/commit/08df8b81d6e723c66fee579d57d61dc60bc21fc1) 2022-01-30) replacing in my original foo code the "for i in start .. 10_000 {" with an equivalent while loop is enough to remove the dividend test.

That works for 1.54 too.

**Comment by jieyouxu** [comment]
Triage: for the example in the issue description, division by zero was present in 1.69 but disappeared in 1.70.

**Comment by leonardo-m** [comment]
Right, closed.

**Comment by jieyouxu** [comment]
Sorry, I was reviewing the PR that's adding a regression test for this, we should close this issue after the regression test lands
