### ISSUE TITLE
`npm list` checks added in #84586 regress wall time of running tidy

### ISSUE THREAD

**Issue by the8472** [rust-lang/rust#86147]
#84586 introduced some checks which execute `npm list` 4 times. They run unconditionally when executing `./x.py test ...`, even if it is just to run tidy. On my system the added wall time exceeds that of running tidy itself.

I'll look into whether the checks themselves can be made be less wasteful. But if there are suggestions how to completely eliminate them or defer them while preserving their original purpose that would be great too.

![npm list](https://user-images.githubusercontent.com/1065730/121245093-ec046b80-c89f-11eb-8d77-ef7f70a724ab.png)

CC @GuillaumeGomez can you explain the purpose of running this in `should_run` rather than erroring in `run`?

**Comment by GuillaumeGomez** [comment]
To know beforehand if the test should unconditionally be run or not. If the test is run and the npm package isn't installed, we panic.

cc @Mark-Simulacrum

**Comment by the8472** [comment]
I don't have `browser-ui-test` installed, so it'll fail and no short-circuiting will happen regardless of order.

**Comment by GuillaumeGomez** [comment]
In case you don't have it it'll check 4 times indeed.
