### ISSUE TITLE
Add field accessing and indexing of arguments to `format!`

### ISSUE THREAD

**Issue by tikue** [rust-lang/rust#8614]
This would be nice if for no other reason than to reach feature parity with Python's `str.format()`, in which one can write things like:

`>>> "{foo[0]} and {foo[1]} went up the hill".format(foo=['jack', 'jill'])
'jack and jill went up the hill'`

**Comment by steveklabnik** [comment]
Triage: nothing has changed here.

**Comment by BigBoneDaddy** [comment]
@huonw You make no progress I am assume?

**Comment by steveklabnik** [comment]
Triage: no change

**Comment by sfackler** [comment]
Seems like this is something that should be over on rfcs?

**Comment by steveklabnik** [comment]
Yeah, this would be a pretty big change, probably rfc-worthy.
