### ISSUE TITLE
rustdoc: "Copy path" button could use a tooltip

### ISSUE THREAD

**Issue by lnicola** [rust-lang/rust#86169]
I just noticed the new button, clicked on it, saw the checkmark and had no idea what happened. I thought it reflowed the page somehow, or maybe added the crate to a favorites list :-).

**Comment by notriddle** [comment]
I think https://github.com/rust-lang/rust/pull/85859 already fixed this in the current nightly.

**Comment by jyn514** [comment]
Yup it has, thanks!
