### ISSUE TITLE
"No item found" diagnostic should suggest items that differ by case

### ISSUE THREAD

**Issue by wesleywiser** [rust-lang/rust#86170]
Given the following code: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=a494a5e7386a6c9e55f7f39695dece41

```rust
enum Foo {
    Bar(u32)
}

fn main() {
    matches!(todo!(), Foo::BAR(_));
}
```

The current output is:

```
error[E0599]: no variant or associated item named `BAR` found for enum `Foo` in the current scope
 --> src/main.rs:6:28
  |
1 | enum Foo {
  | -------- variant or associated item `BAR` not found here
...
6 |     matches!(todo!(), Foo::BAR(_));
  |                            ^^^ variant or associated item not found in `Foo`

```

Ideally the output should include a note suggesting the variant with the same name (but different case):

```
error[E0599]: no variant or associated item named `BAR` found for enum `Foo` in the current scope
 --> src/main.rs:6:28
  |
1 | enum Foo {
  | -------- variant or associated item `BAR` not found here
...
6 |     matches!(todo!(), Foo::BAR(_));
  |                            ^^^ variant or associated item not found in `Foo`
  | help: a similarly named variant exists: `Bar`
```

**Comment by ben0x539** [comment]
This only doesn't Just Work because the Levenshtein thing is case sensitive, right? There is some special-casing for case-insensitive suggestions but afaict it only applies if the case-sensitive Levenshtein distance is also already low, which seems wrong at first glance.

**Comment by ben0x539** [comment]
im working on this

**Comment by ben0x539** [comment]
Okay, judging by https://github.com/rust-lang/rust/blob/d192c80d2284ba6b5146bb3da586354c3762c72b/compiler/rustc_span/src/lev_distance/tests.rs#L40-L42, this is explicitly not supposed to work. shrug emoji
