### ISSUE TITLE
rustdoc styling issue: `.docblock` occasionally has problematic right padding

### ISSUE THREAD

**Issue by davidbarsky** [rust-lang/rust#86184]
In tracing, we use warnings blocks to surface potential gotchas to users (this is arguably a _misuse_ of blocks in rustdoc, but anyways...). Unforuntately, I noticed that blocks add 1ex of right padding to anything rendered as code, including inline comments. Here's an example: https://deploy-preview-1430--tracing-rs.netlify.app/tracing/struct.span#method.entered. A screenshot is below for posterity.

<img width="971" alt="Screen Shot 2021-06-09 at 7 34 08 PM" src="https://user-images.githubusercontent.com/2067774/121442437-af954600-c959-11eb-9dbe-3294ebabac99.png">

The extra right padding results in a poor reading experience while reading some of tracing's documentation. While I recognize that we're misusing docblocks to render tooltips _and_ https://github.com/rust-lang/rust/issues/83550 attempted to solve this problem in more well-trodden use-cases, I was hoping that this rendering issue could either be fixed _or_ we can be given a decently stable workaround. Thanks!

### Meta

`rustc --version --verbose`:
```
❯ rustc --version --verbose
rustc 1.54.0-nightly (e4a603270 2021-06-07)
binary: rustc
commit-hash: e4a60327063e82413eed50a10df3b7d19b77bda0
commit-date: 2021-06-07
host: x86_64-apple-darwin
release: 1.54.0-nightly
LLVM version: 12.0.1
```

**Comment by jyn514** [comment]
I agree this is not super supported ... cc @jsha in case you want to take a look, but I'm not sure we want to fix it.

**Comment by davidbarsky** [comment]
A fix isn't really strictly necessary. If we can provide custom CSS to rustdoc _and_ docs.rs where we override `.docblock` with a tracing-specific selector (or a similar, tracing-scoped approach), that'd also be a great resolution.

**Comment by GuillaumeGomez** [comment]
I think it's somewhat related to https://github.com/rust-lang/rust/pull/79677.

**Comment by jyn514** [comment]
>  If we can provide custom CSS to rustdoc and docs.rs where we override .docblock with a tracing-specific selector (or a similar, tracing-scoped approach), that'd also be a great resolution.

Missed this before sorry - this is already stable: https://doc.rust-lang.org/stable/rustdoc/command-line-arguments.html#-e--extend-css-extend-rustdocs-css

**Comment by jyn514** [comment]
I'm going to close this since there's a stable workaround.
