### ISSUE TITLE
`char::to_uppercase()` can return a lowercase character,  `char::to_lowercase()` can  return an uppercase character

### ISSUE THREAD

**Issue by timClicks** [rust-lang/rust#86187]
I tried this code:

```rust
fn main() {
    let upper = format!("{}", 'º'.to_uppercase());
    assert!(upper.chars().all(|c| c.is_uppercase()));
}
```
[playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=b97ed6c92a6d01d731279526038fea57)

I expected to see the assertion pass, yet it panics. The inverse operation, e.g. to_lowercase, works fine. However, it's possible that the bug is actualy there. is the "[original indicator](https://en.wikipedia.org/wiki/Ordinal_indicator)", and is presumably caseless. Perhaps it would it be better for both `is_lowercase()` and `is_uppercase()`  to both return `false`?

After some testing, see test cases below, it looks like there are about 1,400 characters where `to_uppercase()` returns a lowercase character or `to_lowercase()` returns an uppercase character.

```rust
#[test]
fn uppercase() {
    let mut failures = 0;
    for c in '0'..=char::MAX {
        if c.is_lowercase() {
            let hopefully_upper = c.to_uppercase();
            let okay = hopefully_upper
                .to_string()
                .chars()
                .all(|c| c.is_uppercase());
            if !okay {
                println!("{} ({}) ", c, c.escape_unicode());
                failures += 1;
            }
        }
    }
    assert_eq!(failures, 0);
}

#[test]
fn lowercase() {
    let mut failures = 0;
    for c in '0'..=char::MAX {
        if c.is_uppercase() {
            let hopefully_lower = c.to_lowercase();
            let okay = hopefully_lower
                .to_string()
                .chars()
                .all(|c| c.is_lowercase());
            if !okay {
                println!("{} ({}) ", c, c.escape_unicode());
                failures += 1;
            }
        }
    }
    assert_eq!(failures, 0);
}
```

[playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=8aa54f0c1d7e2c0dde2861e9395ec8a5)

### Meta

```console
$ rustc --version --verbose
rustc 1.52.1 (9bc8c42bb 2021-05-09)
binary: rustc
commit-hash: 9bc8c42bb2f19e745a63f3445f1ac248fb015e53
commit-date: 2021-05-09
host: x86_64-unknown-linux-gnu
release: 1.52.1
LLVM version: 12.0.0
```

**Comment by Manishearth** [comment]
This is working as expected, there are characters in Unicode that have case but do not necessarily have opposite-case versions. The is_lowercase and is_uppercase functions mention the unicode properties these are based off of.

**Comment by timClicks** [comment]
Thanks for taking the time to confirm this for me.

**Comment by Lionelf329** [comment]
I looked at the docs related to case conversions and checks, and they do have links to the relevant unicode standards, like the one below:

> Lowercase is described in Chapter 4 (Character Properties) of the Unicode Standard and specified in the Unicode Character Database DerivedCoreProperties.txt.

They don't explicitly warn about the situation you found, but I don't think there's a good way to change them to include that. When I saw that sentence in the docs, I interpreted it to mean that I would need to study up on how unicode works if I wanted to understand what those functions do to non-ascii text, and until then I wouldn't even be willing to take a guess. The way I see it, unicode is its own special topic, and explanations of how it works don't belong in the rust docs.

**Comment by ijackson** [comment]
One of the things I like about Rust is that in general the Rust community prioritises helping people write correct code, and in particular to try to help programmers avoid foreseeable errors.

I see this question through that lens and I think that goal is more important than an abstract principle such as not linking to non-normative documents.  (Even if we had such a principle, which I don't think we do.)

But I think perhaps both of us have said enough now so I will shut up and wait and see what others have to say.

**Comment by Manishearth** [comment]
I think additional docs would be great, but it's honestly a pretty nuanced subject and it's hard to get across all of the requisite information.

The rust docs are definitely careful about linking to unofficial sources, though.

**Comment by timClicks** [comment]
I saw the reference to the Unicode standard, and actually spent some time looking through it. However, I still found Rust's behavior quite confusing. I never expected `to_lowercase()` to return a character that is defined as uppercase. What about a change in the docs to something like:

> Lowercase is described in Chapter 4 (Character Properties) of the Unicode Standard and specified in the Unicode Character Database DerivedCoreProperties.txt. This can lead to counter-intuitive results. For example, there are characters for which `.to_lowercase()` returns a character for which `.is_uppercase()` returns `true` and `.is_lowercase()` returns `false`.

**Comment by Manishearth** [comment]
something like that, but I wouldn't make it as causal, something more like "Note that this function may lead to surprising results ..."

it's an _extremely common_ thing for programmers to blame Unicode for complexities that are inherent to the diversity of human text

**Comment by timClicks** [comment]
Good point. It's not Unicode's fault that human scripts are not consistent.

Should I get a PR up to work through wording?

**Comment by Manishearth** [comment]
Sure

**Comment by ChrisDenton** [comment]
Would it be worth it for `str` to have `is_lowercase` and `is_uppercase` functions? Because I suspect testing each code point for the upper/lower case properties is almost never what people actually want to do. But it's the only thing the std provides.

**Comment by ijackson** [comment]
> Should I get a PR up to work through wording?

I'm not on the relevant teams but yes, I think that would be good, thank you.

> Would it be worth it for `str` to have `is_lowercase` and `is_uppercase` functions? Because I suspect testing each code point for the upper/lower case properties is almost never what people actually want to do. But it's the only thing the std provides.

I'm not sure about this.  Should `str::is_lowercase` mean "all letters are lowercase" or "string is entirely lowercase and contains no non-letters"?  How common are these precise operations anyway?  `s.chars().all(char::is_lowercase)` or `s.chars().filter(|c| c.is_alphabetic()).all(char::is_lowercase)` or `! s.chars().any(|c| !c.is_uppercase())` or something?

**Comment by ChrisDenton** [comment]
>  Should str::is_lowercase mean "all letters are lowercase" or "string is entirely lowercase and contains no non-letters"?

According to Unicode, `s.is_lowercase()` should be implemented to return the same as `s == s.to_lowercase()`.

**Comment by ijackson** [comment]
> According to Unicode, `s.is_lowercase()` should be implemented to return the same as `s == s.to_lowercase()`.

Ooo, facts!  Thank you :-).  That there are multiple possibilities, but a right answer defined in Unicode, seems to me to be an argument in favour of providing the function on str.
