### ISSUE TITLE
Cant install cargo-edit

### ISSUE THREAD

**Issue by anzosasuke** [rust-lang/rust#86181]
These are some error snippets. I am trying to install cargo-edit. But this error pop up?
command-> cargo install cargo-edit

  
error: failed to run custom build command for `openssl-sys v0.9.63`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installr0hGvg/release/build/openssl-sys-a67c19981aefb1b2/build-script-main` (exit code: 101)
  --- stdout

$HOST = x86_64-unknown-linux-gnu
  $TARGET = x86_64-unknown-linux-gnu
  openssl-sys = 0.9.63

  ', /home/ashish/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.63/build/find_normal.rs:174:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `cargo-edit v0.7.0`, intermediate artifacts can be found at `/tmp/cargo-installr0hGvg`

Caused by:
  build failed

Can you guys tell me how to fix it??

**Comment by jonas-schievink** [comment]
Hi! This issue tracker is mainly meant for bug reports and concrete, small feature requests. Questions like this are better asked in the user forum at https://users.rust-lang.org/ or on [one of the chat platforms](https://www.rust-lang.org/community) used by the Rust community.
