### ISSUE TITLE
ICE on invalid size/alignment in CTFE validation

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#86193]
The following code ICEs:
```rust
#[repr(transparent)]
struct W<T>(T);

// The drop fn is checked before size/align are, so get ourselves a "sufficiently valid" drop fn
fn drop_me(_: *mut usize) {}

const INVALID_VTABLE_SIZE: W<&dyn Send> =
    unsafe { std::mem::transmute((&92u8, &(drop_me as fn(*mut usize), usize::MAX, 1usize))) };
```
To fix this, this code here needs to properly catch the "invalid size/align" error and turn it into a validation failure:

https://github.com/rust-lang/rust/blob/563ab4a106928a9f9a27618ad6598fd255dc3555/compiler/rustc_mir/src/interpret/validity.rs#L356

But for this we first need to make these errors catchable by introducing separate variants into this enum:

https://github.com/rust-lang/rust/blob/2779fc1c4768567b74b757a8083db3c39765f071/compiler/rustc_middle/src/mir/interpret/error.rs#L211

You can use the existing `InvalidDropFn` variant as a model; it does the same job for invalid drop function pointers in the vtable.

Cc @lqd

**Comment by lqd** [comment]
I'll take care of this

@rustbot claim
