### ISSUE TITLE
rustdoc: Regression in display of `macro_rules!` matchers

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#86208]
Oddly enough, the two lines (and the areas around them) that show up when I grep for `"macro_rules!` in rustdoc don't appear to have changed at all in a while, so I'm not sure what caused this regression. Perhaps the span of the matcher changed? I wasn't able to reproduce this locally, even when I tried using a cross-crate re-export with a copy-pasted version of `core::todo` (modulo replacing `$crate::` with `::std::`). Also, the bug doesn't appear with, e.g., `panic!`, but does with `compile_error!`. So, this seems to be a subtle bug.

```console
$ rg '"macro_rules!' src/librustdoc/
src/librustdoc/clean/mod.rs
2167:                "macro_rules! {} {{\n{}}}",

src/librustdoc/clean/inline.rs
541:                "macro_rules! {} {{\n{}}}",
```

### [beta](https://doc.rust-lang.org/beta/std/macro.todo.html) (incorrect)

![image](https://user-images.githubusercontent.com/37223377/121625602-a0c99480-ca28-11eb-9bc8-f7942aaac83b.png)

### [stable](https://doc.rust-lang.org/stable/std/macro.todo.html) (correct)

![image](https://user-images.githubusercontent.com/37223377/121625627-ae7f1a00-ca28-11eb-9f96-a75dd1a30788.png)

**Comment by camelid** [comment]
This bug doesn't occur for `core::todo!` or `core::compile_error!`, which makes me think it's a bug with cross-crate spans (either in rustc or rustdoc). I think `std::panic!` rendering normally is further evidence of this, because `std::panic!` is currently *not* a re-export of `core::panic!`.

**Comment by camelid** [comment]
I wonder if #80339 is related?

**Comment by jyn514** [comment]
@camelid you can test by bisecting

**Comment by jyn514** [comment]
That line of code is https://github.com/rust-lang/rust/blob/0a8629bff642c3c3b84bb644c0099194f063b627/src/librustdoc/clean/inline.rs#L545

**Comment by camelid** [comment]
> @camelid you can test by bisecting

But I don't have an MCVE to bisect with. Can you bisect `std` itself?

**Comment by jyn514** [comment]
@camelid sure, it will just take a while 😅

**Comment by camelid** [comment]
I meant in terms of getting `bisect-rustc` to work with rustbuild so we're not also rebuilding rustdoc every time. Unless you're suggesting `git bisect`? But, yeah, it would probably take a while.

**Comment by jyn514** [comment]
@camelid you can use a custom script with bisect-rustc, it's a little tricky but it should work.

**Comment by camelid** [comment]
Ok, since this issue is present on beta but not stable, I think the regression occurred in 61edfd591cedff66fca639c02f66984f6271e5a6...8a9fa3682dcf0de095ec308a29a7b19b0e011ef0 (the merge-bases between master and stable/beta), so that narrows it down a bit.

**Comment by camelid** [comment]
I started scrolling through `git log -S 61edfd591cedff66fca639c02f66984f6271e5a6...8a9fa3682dcf0de095ec308a29a7b19b0e011ef0` and found this commit that looks like it might be related: f94360fd83b49554b6c26999a0030e9cfe800f32

**Comment by camelid** [comment]
Aha! I came up with a super simple repro:

```rust
pub use std::todo;
```

**Comment by camelid** [comment]
Unfortunately, this bug seems even weirder than I thought, because the bisection pointed to 2020-03-11 as the regression date, which is bizarre because the bug is not present on stable.

The commit range I got was 3dbade652ed8ebac70f903e01f51cd92c4e4302c...15812785344d913d779d9738fe3cca8de56f71d5.

The command I used was:

```console
$ cargo bisect-rustc --prompt --start=2020-01-01 --end=2021-05-01 -- doc --open
```

**Comment by camelid** [comment]
Based on looking through the commit range, these are the two PRs that seem most likely to have caused the regression: #66364 and #69677. #66364 seems especially likely to me, as it changed macro definitions in metadata, which is more likely to cause cross-crate macro issues.

I still don't understand why this issue is not present on stable, given that it regressed more than a year ago.

**Comment by jyn514** [comment]
@camelid if you build from source with `channel = stable`, does it still reproduce the bug?

**Comment by camelid** [comment]
I asked about this regression on Zulip, and Eric Huss gave a very helpful [response](https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp/topic/weird.20regression/near/242488242), explaining that the reason the bisection gave such weird results is because there was a regression in March 2020 that was then fixed in April 2020, but then regressed again recently, in April 2021. Eric was able to determine that the PR that most recently caused the regression was #84233, which I was able to confirm by re-bisecting.

searched nightlies: from nightly-2021-01-01 to nightly-2021-05-01
regressed nightly: nightly-2021-04-30
searched commits: from https://github.com/rust-lang/rust/commit/ca075d268d2ce315964e1dd195cfe837b8a53f4d to https://github.com/rust-lang/rust/commit/478a07df05e3fe8df964291d8b25dd80b7e0e76b
regressed commit: https://github.com/rust-lang/rust/commit/814a560072c305d274affc78219e4a7e0558252f

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.0</summary>


Host triple: x86_64-apple-darwin
Reproduce with:
```bash
cargo bisect-rustc --prompt --start=2021-01-01 --end=2021-05-01 --with-src -- doc --open 
```
</details>

**Comment by camelid** [comment]
Just on a hunch, 39648ea467a39afa3676d900656874947c747690 seems likely to be the commit that caused the regression. It also explains why I was not able to minimize the regression without using `std`, since it seems that the regression is in the handling of the rust-src component.

**Comment by jyn514** [comment]
I think the more interesting question is why rustdoc depends on having the source available, that seems like a bug.

**Comment by camelid** [comment]
Yeah, I was thinking about that. We should probably switch to pretty-printing the matchers.

**Comment by camelid** [comment]
Assigning priority as [discussed](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2386208.20rustdoc.3A.20Regression.20in.20display.20of.20.60macro_rules!.60.20mat.E2.80.A6) in the prioritization working group.

@rustbot label: +P-high -I-prioritize

**Comment by camelid** [comment]
> Yeah, I was thinking about that. We should probably switch to pretty-printing the matchers.

I think this change would make sense independently of this bug, for the reason mentioned in https://github.com/rust-lang/rust/issues/86208#issuecomment-860251862, but the one issue is that it won't fix the underlying regression that this bug is a symptom of.

**Comment by jyn514** [comment]
@camelid what underlying regression? Nothing in the compiler should depend on if the source of dependencies is available IMO

**Comment by camelid** [comment]
> @camelid what underlying regression? Nothing in the compiler should depend on if the source of dependencies is available IMO

Are there no other places where we use `ToSource::to_src` (a wrapper around `span_to_snippet`) in rustdoc?

**Comment by camelid** [comment]
I'm currently trying out a fix that switches us to using `rustc_ast_pretty`.

**Comment by camelid** [comment]
It's not pretty, but it does work:

![image](https://user-images.githubusercontent.com/37223377/121823720-f6d24e00-cc5b-11eb-90f8-51e7322d9356.png)
