### ISSUE TITLE
Min TAIT + GAT lifetime issue

### ISSUE THREAD

**Issue by ivan770** [rust-lang/rust#86218]
I tried this code:
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=71e56b49edea6de440eed3a417322308

Code that is an equivalent to the one above, but that compiles: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=f071b171eda8921c1d4902999417594d

I'm not sure about the exact reason for this to happen, but I can suspect the presence of an additional lifetime in impl block that is causing this bug.

I expected to see this happen: It compiles

Instead, this happened: Lifetime error

### Meta
`rustc --version --verbose`: Latest playground version

**Comment by oli-obk** [comment]
@b-naber this issue has been fixed as a side effect of #95474
