### ISSUE TITLE
feature(const_ptr_write) is broken

### ISSUE THREAD

**Issue by AaronKutch** [rust-lang/rust#86236]
As of a very recent nightly (`rustc 1.54.0-nightly (0a8629bff 2021-06-11)`), it appears to me that `feature(const_ptr_write)` is no longer working and broke my code. Sample code:
```
#![feature(const_ptr_write)]
const unsafe fn ex(x: *mut usize) {
    unsafe {
        x.write(0);
    }
}
```
```
error[E0015]: calls in constant functions are limited to constant functions, tuple structs and tuple variants
 --> src/lib.rs:5:9
  |
5 |         x.write(0);
  |         ^^^^^^^^^^
```
I see a tracking issue for many other pointer operations such as `const_ptr_read`, but strangely a tracking issue for `const_ptr_write` is missing.

**Comment by ChrisDenton** [comment]
It seems there were problems with it. See #86003.

Looks like this feature was [started as an experiment](https://github.com/rust-lang/rust/pull/81167) which is why there's no specific tracking issue.

**Comment by AaronKutch** [comment]
This can fortunately be worked around with plain pointer dereferencing and `feature(const_raw_ptr_deref)`, but I prefer `ptr::write` to make things more explicit

**Comment by slightlyoutofphase** [comment]
Yeah, this is an extremely annoying reversion that I hope is able to be un-reverted ASAP. So back to how things were a little over a week ago basically. It doesn't even just effect `write`, but like every single pointer method that was constified recently, basically.

**Comment by nagisa** [comment]
I'm not sure if broken is the right classification here, rather than that it is just gone. Given that this was an unstable functionality, I'm not seeing if there's any benefit in tracking this disappearance.

Closing.

**Comment by RalfJung** [comment]
See https://github.com/rust-lang/rust/pull/86295 for hopefully bringing these functions back.

**Comment by RalfJung** [comment]
There's now also a proper tracking issue for this feature: https://github.com/rust-lang/rust/issues/86302
