### ISSUE TITLE
Rustdoc: report layout of enum variants

### ISSUE THREAD

**Issue by LeSeulArtichaut** [rust-lang/rust#86253]
#83501 introduced a basic section on layout information, with only one piece of information: the total size of the type. I think one useful but easy extension to this is reporting the size of each variant for an enum.

cc @camelid

### Implementation hints

The "Layout" section is rendered in https://github.com/rust-lang/rust/blob/da7ada584a3e5c3467b8b9f344b4a0f2a81ce32a/src/librustdoc/html/render/print_item.rs#L1553-L1574

The `ty_layout` variable is a [`TyAndLayout`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/layout/type.TyAndLayout.html). We want to handle the case where `ty_layout.layout.variants` is [`Variants::Multiple`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_target/abi/enum.Variants.html#variant.Multiple).In that case we have access to an `IndexVec<VariantIdx, Layout>`.
- The `Layout` part will give us the size of the variant
- To get the name of the variant, we'll need the `AdtDef` stored in `TyKind::Adt`, which we can hopefully get from `ty_layout.ty.kind`.

**Comment by camelid** [comment]
> To get the name of the variant, we'll need the `AdtDef` stored in `TyKind::Adt`, which we can hopefully get from `ty_layout.ty.kind`.

I think we could just look up the `VariantIdx` to find the name (there's probably a `TyS` function for that).

Also, it might be worth showing the sizes of each union field.
