### ISSUE TITLE
Deduplicate doc tests logic

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/rust#86254]
This comes from a [discussion](https://github.com/rust-lang/rust/pull/86230/files#r650439670) in #86230: for the moment, we call `libtest` from two places: `markdown.rs` (which is used when we provide a markdown file as input) and `doctest.rs` (when a rust file is provided as input, the default).

Both calls can be found when grepping with `testing::test_main(`.

**Comment by camelid** [comment]
Probably the deduplicated logic should go in `doctest.rs`.
