### ISSUE TITLE
regression: Type aliases are bolded

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#86256]
It looks like a CSS rule is being applied incorrectly.

It also looks weird if you click through to the type alias's page (`Visibilities`).

### [nightly](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_hir/struct.MacroDef.html) (incorrect)

![image](https://user-images.githubusercontent.com/37223377/121792432-70f5ca80-cba9-11eb-9b1c-da75e11a1991.png)

### [beta](https://doc.rust-lang.org/beta/nightly-rustc/rustc_hir/struct.MacroDef.html) (correct)

![image](https://user-images.githubusercontent.com/37223377/121792437-79e69c00-cba9-11eb-9324-0021e10b06a9.png)

**Comment by apiraino** [comment]
I'm not really sure, could that be slipped in 5bd9146858be?

**Comment by camelid** [comment]
It turns out it was actually much more recent. The PR causing the regression was #84703, cc @GuillaumeGomez.

#### MCVE

```rust
pub type Foo = u32;

pub struct Bar { pub f: Foo }
```

#### Bisection

searched nightlies: from nightly-2021-05-01 to nightly-2021-06-12
regressed nightly: nightly-2021-06-04
searched commits: from https://github.com/rust-lang/rust/commit/dbe459dedd33470f2cb28101157de316caaffa66 to https://github.com/rust-lang/rust/commit/cc77ba46fcb2d288aa01554b48cd586c5827c3dd
regressed commit: https://github.com/rust-lang/rust/commit/da865095cf378fbfd07145c25fe5837ea091efeb

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.0</summary>


Host triple: x86_64-apple-darwin
Reproduce with:
```bash
cargo bisect-rustc --prompt --start=2021-05-01 --end=2021-06-12 -- doc --open 
```
</details>

**Comment by LeSeulArtichaut** [comment]
The culprit CSS rule is here: https://github.com/rust-lang/rust/blob/fb3ea63d9b4c3e9bb90d4250b870faaffb9c8fd2/src/librustdoc/html/static/rustdoc.css#L140-L148

It also caused #86069 which was fixed by #86078.

**Comment by GuillaumeGomez** [comment]
Ah, I have missed this one. Sending a fix.

**Comment by camelid** [comment]
Assigning priority as [discussed](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2386256.20regression.3A.20Type.20aliases.20are.20bolded) in the prioritization working group.

@rustbot label: +P-medium -I-prioritize

**Comment by GuillaumeGomez** [comment]
The fix should be merged in less than 3 hours. ;)

**Comment by camelid** [comment]
> The fix should be merged in less than 3 hours. ;)

I know, but we had already agreed on a priority :)

**Comment by GuillaumeGomez** [comment]
Oh I see. Thanks for taking care of that then! :)
