### ISSUE TITLE
Nightly with MIRI and FFI

### ISSUE THREAD

**Issue by jorgecarleitao** [rust-lang/rust#86261]
While trying to unpin nightly (2021-03-25) to latest nightly, I have hit an internal compiler error.

[Complete build log](https://github.com/jorgecarleitao/arrow2/runs/2812474582?check_suite_focus=true)

It emerged between 2021-03-25 and today's build.

All the details are in the build log. In particular,

* `rustc 1.55.0-nightly (24bdc6d73 2021-06-12) running on x86_64-unknown-linux-gnu`

The error seems to emerge when compiling a transitive dependency, so it is not very easy to reproduce with a minimal example.

```bash
git clone git@github.com:jorgecarleitao/arrow2.git
cd arrow2
rustup toolchain install nightly
rustup default nightly
rustup component add rustfmt miri

cargo miri setup
cargo clean
cargo miri build
```

**Comment by hyd-dev** [comment]
Regressed between nightly-2021-06-08 and nightly-2021-06-09, which is https://github.com/rust-lang/rust/compare/e4a60327063e82413eed50a10df3b7d19b77bda0...ed597e7e19d0fe716d9f81b1e840a5abbfd7c28d, which corresponds to https://github.com/rust-lang/miri/compare/5dde0fe6de2941c9ef16bc1e9d91ecf20ac5ee8b...c8713c2f9fc1e28c90876b9ec9557d8c5729757b (which includes https://github.com/rust-lang/miri/pull/1776 that touches `exported_symbols` :thinking:).

**Comment by RalfJung** [comment]
@hyd-dev found out that the issue boils down to [this strange bit of code](https://docs.rs/brotli-decompressor/2.3.1/src/brotli_decompressor/ffi/mod.rs.html#3-5)
```rust
#[no_mangle]
#[cfg(feature="std")]
use std::{thread,panic, io, boxed, any, string};
```
Does it make any sense to put `no_mangle` on a `use` item...??

**Comment by Smittyvb** [comment]
@RalfJung It doesn't -- it even generates a warning:
```
warning: attribute should be applied to a function or static
 --> src/ffi/mod.rs:3:1
  |
3 | #[no_mangle]
  | ^^^^^^^^^^^^
4 | #[cfg(feature="std")]
5 | use std::{thread,panic, io, boxed, any, string};
  | ------------------------------------------------ not a function or static
  |
  = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
```
