### ISSUE TITLE
rustdoc: Re-exported macros 2.0 are rendered as `macro_rules!`

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#86276]
I noticed this while working on a fix for #86208. I think the issue is just that `clean/inline.rs` does not check if the macro is a `macro_rules!`, whereas `clean/mod.rs` does.

### [core](https://doc.rust-lang.org/stable/core/ptr/macro.addr_of.html) (original)

![image](https://user-images.githubusercontent.com/37223377/121823930-4c5b2a80-cc5d-11eb-8d13-57d8fbf49343.png)

### [std](https://doc.rust-lang.org/stable/std/ptr/macro.addr_of.html) (re-export)

![image](https://user-images.githubusercontent.com/37223377/121823935-52e9a200-cc5d-11eb-832a-04be526486fe.png)

**Comment by camelid** [comment]
Assigning myself because I'd like to look into this.

**Comment by apiraino** [comment]
Assigning priority as discussed in the [Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2386276.20rustdoc.3A.20Re-exported.20macros.202.2E0.20are.20rendered.20as.20.60mac.E2.80.A6) of the Prioritization Working Group.

@rustbot label -I-prioritize +P-low

**Comment by xfix** [comment]
I don't think this is necessarily wrong, unless I'm missing something `macro` and `macro_rules!` are equivalent from user's point of view. Considering `macro` is not stable at this point it may be less confusing to show `macro_rules!` in documentation, even if strictly speaking it's incorrect.

**Comment by GuillaumeGomez** [comment]
Even though it's a low priority, it still remains a bug that needs to be fixed. I'll take it from here.
