### ISSUE TITLE
Miri is shipped in the standalone installer

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#86286]
According to [user reports](https://github.com/rust-lang/miri/issues/1834#issuecomment-860431022), the standalone tarball installer of stable Rust releases includes Miri. That's a bug, Miri is a nightly-only tool and should not be shipped on stable.

Cc @rust-lang/infra @rust-lang/release

**Comment by ehuss** [comment]
Posted a fix at #86568.
