### ISSUE TITLE
Tracking Issue for addition between ranges and index

### ISSUE THREAD

**Issue by DPDmancul** [rust-lang/rust#86292]
Feature gate: `#![feature(collections_range_add)]`

This is a tracking issue for implementing `Add<RangeBouds<T>>` for `T`

As described in [this tweet and following comments](https://twitter.com/yoshuawuyts/status/1404151331120615424?s=09) the usual way to slice with a starting point and a length is: `buf[start .. start + len]`. An alternative way which avoids `start` repetition is to double slicing: `buf[start..][..len]`. This is not so intuitive, and so the following was proposed `buf[start+..len]`

This can be easily implemented in the standard library. Here i put a simple naïve implementation which generalizes on all cases of RangeBounds.

### Public API

```rust
// core::ops
impl<T: Add<Output = T> + Copy, Rhs: RangeBounds<T>> Add<Rhs> for T {
    type Output = (Bound<T>, Bound<T>);

    /// Shifts a left-bounded range or fixes a start for a left-unbounded range.
    ///
    /// ```compile_fail,E0277
    /// start +       ..  len   = start         ..  start+len
    /// start +       ..= len   = start         ..= start+len
    /// shift + (start ..  end) = (start+shift) ..  end+shift
    /// shift + (start ..= end) = (start+shift) ..= end+shift
    /// shift + (start .. )     = (start+shift) ..
    /// start +       ..        = start         ..
    /// ```
    ///
    /// # Examples
    ///
    /// ```
    /// # fn main() {
    /// use std::ops::RangeBounds;
    ///
    /// let a = 5+..10;
    /// let b = 5..5+10;
    /// assert_eq!(a.start_bound(), b.start_bound());
    /// assert_eq!(a.end_bound(), b.end_bound());
    /// # }
    /// ```
    fn add(self, other: Rhs) -> Self::Output {
        let start = match other.start_bound() {
            Unbounded => Included(self),
            Included(&s) => Included(self + s),
            Excluded(&s) => Excluded(self + s),
        };
        let end = match other.end_bound() {
            Unbounded => Unbounded,
            Included(&e) => Included(self + e),
            Excluded(&e) => Excluded(self + e),
        };
        (start, end)
    }
}
```

```rs
#[test]
fn test_range_add() {
    let (a, b) = (5 + ..10, 5..(5 + 10));
    assert_eq!(a.start_bound(), b.start_bound());
    assert_eq!(a.end_bound(), b.end_bound());

    let (a, b) = (5 + ..=10, 5..=(5 + 10));
    assert_eq!(a.start_bound(), b.start_bound());
    assert_eq!(a.end_bound(), b.end_bound());

    let (a, b) = (5 + (6..10), (6 + 5)..(10 + 5));
    assert_eq!(a.start_bound(), b.start_bound());
    assert_eq!(a.end_bound(), b.end_bound());

    let (a, b) = (5 + (6..=10), (6 + 5)..=(10 + 5));
    assert_eq!(a.start_bound(), b.start_bound());
    assert_eq!(a.end_bound(), b.end_bound());

    let (a, b) = (5 + (6..), (6 + 5)..);
    assert_eq!(a.start_bound(), b.start_bound());
    assert_eq!(a.end_bound(), b.end_bound());

    let (a, b) = (5 + .., 5..);
    assert_eq!(a.start_bound(), b.start_bound());
    assert_eq!(a.end_bound(), b.end_bound());

    let x = [1,8,4,7,10,-2,5];
    assert_eq!(&x[3usize + ..2usize], &x[3..5]);
}
```

### Steps / History

- [ ] Finalize implementation
- [ ] Final commenting period (FCP)
- [ ] Stabilization PR

### Unresolved Questions

- With standard slices the `usize` type is automatic inferred, but with this implementation it is not.
- The trait `SliceIndex<str>` is not implemented for `(Bound<usize>, Bound<usize>)`: only `SliceIndex<[T]>` is implemented.
- Even if bounds are constants the range would not result constant and so the size of the slice is not known at compile time.

**Comment by dtolnay** [comment]
Based on `git log --all -S collections_range_add`, and searching for "RangeBounds" in <https://doc.rust-lang.org/nightly/std/ops/trait.Add.html>, there was never a PR for this, so I don't think this tracking issue is tracking anything.
