### ISSUE TITLE
Intra-doc link `foo!()` is rendered without the parentheses

### ISSUE THREAD

**Issue by LeSeulArtichaut** [rust-lang/rust#86309]
Consider this code:

```rust
#[macro_export] macro_rules! foo {
    () => {}
}

/// [foo!()]
pub struct Foo;
```

In the generated docs, the link on the `Foo` page appears as `foo!`, with the correct link, but without the parentheses.

**Comment by LeSeulArtichaut** [comment]
@camelid Sorry, I stole this from you :smile:

**Comment by camelid** [comment]
> @camelid Sorry, I stole this from you 😄

@LeSeulArtichaut That's okay! Thanks for fixing this :)
