### ISSUE TITLE
Intra-doc links don't accept all macro delimiters

### ISSUE THREAD

**Issue by LeSeulArtichaut** [rust-lang/rust#86310]
Consider this code:

```rust
// This can be invoked with `foo!()`, `foo[]` or `foo{}`
#[macro_export] macro_rules! foo {
    () => {}
}

/// This is parsed as an intra-doc link: [foo!()]...
/// ...but those aren't: [foo![]] [foo!{}]
pub struct Foo;
```

I'm not sure if this is a deliberate decision or not. If it is, what's the rationale for not accepting `[]` and `{}`? cc @jyn514

**Comment by jyn514** [comment]
It isn't valid markdown syntax.

**Comment by jyn514** [comment]
Well, `{}` might be. But [] definitely is not.

**Comment by LeSeulArtichaut** [comment]
> It isn't valid markdown syntax.

`[foo![]](foo!)` seems to work fine (it renders as `foo![]` and the link is correct). But maybe you're saying that we shouldn't accept `[foo![]]` because it wouldn't be valid markdown?

> Well, `{}` might be.

Is it worth implementing?

**Comment by jyn514** [comment]
@LeSeulArtichaut hmm, it might be valid in that position, but it's not valid as a link reference:

```
See [foo![]].

[foo![]]: foo![]
```

But I guess there's no reason for rustdoc to explicitly reject it.

> Is it worth implementing?

I would be ok with it, @Manishearth may have opinions.

**Comment by Manishearth** [comment]
I'm okay with it. I'm mostly wary about characters that are common in URLs, curly braces are not.

**Comment by LeSeulArtichaut** [comment]
Oh, the reason why `[macro![]](macro!)` works is because the rules for inline links are more relaxed:

> Brackets are allowed in the link text only if (a) they are backslash-escaped or (b) they appear as a matched pair of brackets, with an open bracket `[`, a sequence of zero or more inlines, and a close bracket `]`.

vs

> A link label begins with a left bracket (`[`) and ends with the first right bracket (`]`) that is not backslash-escaped. Unescaped square bracket characters are not allowed inside the opening and closing square brackets of link labels.

So instead do you think rustdoc should parse `[macro!\[\]]`? FWIW it's really easy to implement :innocent:

```diff
diff --git a/src/librustdoc/passes/collect_intra_doc_links.rs b/src/librustdoc/passes/collect_intra_doc_links.rs
index ce017995a3b..c141346133b 100644
--- a/src/librustdoc/passes/collect_intra_doc_links.rs
+++ b/src/librustdoc/passes/collect_intra_doc_links.rs
@@ -1538,6 +1538,7 @@ fn from_str(link: &str) -> Result<Option<(Self, &str, &str)>, (String, Range<usi
         } else {
             let suffixes = [
                 ("!()", DefKind::Macro(MacroKind::Bang)),
+                (r"!\[\]", DefKind::Macro(MacroKind::Bang)),
                 ("()", DefKind::Fn),
                 ("!", DefKind::Macro(MacroKind::Bang)),
             ];
```
