### ISSUE TITLE
rustdoc doesn't include renamed re-exports in search results

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#86337]
I tried this: Go to https://docs.rs/tracing-subscriber/0.2.18/tracing_subscriber/ and search for `FmtSubscriber`

I expected to see this happen: Rustdoc shows a search result for https://docs.rs/tracing-subscriber/0.2.18/tracing_subscriber/fmt/struct.Subscriber.html, which is re-exported as `FmtSubscriber` in the root.

Instead, this happened: Rustdoc doesn't show any results.

### Meta

This was generated with `rustdoc 1.53.0-nightly (42816d61e 2021-04-24)`

**Comment by GuillaumeGomez** [comment]
Seems like this issue was fixed:

![Screenshot from 2022-10-30 13-41-57](https://user-images.githubusercontent.com/3050060/198879013-bb2eb0bc-50cb-4901-b7c3-3b1473a76a66.png)

I'll add a regression test to enforce to close this issue.
