### ISSUE TITLE
Compiler hanging probably related to impl-trait stuff

### ISSUE THREAD

**Issue by davidspies** [rust-lang/rust#86331]
The compiler seems to hang when I make a small change to my code (from something that compiled quickly before). `cargo check` has no problems. It's not eating up memory. I haven't yet been able to create a MWE, but I thought maybe someone might know what's going on anyway.

https://github.com/davidspies/standing-relations/commit/20d8d27c129c061cf363b490957163ab46aae6de

### Meta

`rustc --version --verbose`:
```
rustc 1.55.0-nightly (149f4836d 2021-06-17)
binary: rustc
commit-hash: 149f4836dd6d9e789a26dca16dc034588866894e
commit-date: 2021-06-17
host: x86_64-unknown-linux-gnu
release: 1.55.0-nightly
LLVM version: 12.0.1
```

**Comment by bugadani** [comment]
What's the linked commit exactly? The before state works and the after state loops, or the other way around?

**Comment by davidspies** [comment]
Yes, the before state compiles in 4 seconds. The after state compiles in 2m 30s on my laptop (turns out it doesn't take forever, just a long time).
Updated to the latest nightly. Problem is still there.

**Comment by Enselic** [comment]
Triage: We're going to need a minimal reproducer before we can make progress here. Closing as not-reproducible for now. Of course feel free to re-open after adding a minimal reproducer!
