### ISSUE TITLE
rustdoc: stabilized (added) versions of enum variants are hard to read

### ISSUE THREAD

**Issue by JohnTitor** [rust-lang/rust#86342]
Go to: https://doc.rust-lang.org/nightly/std/io/enum.ErrorKind.html#variant.OutOfMemory
It was [stabilized (i.e. added) in 1.54.0](https://github.com/rust-lang/rust/blob/607d6b00d4e0e0475b8de9d0c870b7126fdcdf6b/library/std/src/io/error.rs#L190-L193) but the rustdoc generates like:

![the added versions of enum variants are hard to read](https://user-images.githubusercontent.com/25030997/122138981-e2bc6580-ce82-11eb-86e7-981d5b3e9081.png)

The problem is that the previous variant's version is placed at the same height. I think it's ideal to place the version of the item itself at the same height, like functions.

**Comment by matteo-briani** [comment]
I am new here but it looks like something I could do.
Can you point me in the right direction?

**Comment by JohnTitor** [comment]
Sorry but I'm not familiar with rustdoc, @jyn514 could you help them?

**Comment by jyn514** [comment]
I don't have time, sorry. @GuillaumeGomez may have suggestions.

**Comment by GuillaumeGomez** [comment]
I can help if needed. But first: how would you want it to look like?

**Comment by JohnTitor** [comment]
As mentioned first, the version at the same height should be the variant's IMO.

**Comment by GuillaumeGomez** [comment]
Ah ok sorry, so it's a layout bug. I thought you wanted to improve the display (which would be welcome too!).

The problematic line is [this one](https://github.com/rust-lang/rust/blob/eef4e2a0e8ceaee8c59394a30a9575f90766426a/src/librustdoc/html/render/print_item.rs#L1024). It should be set before the docblock (in the variant header if possible).

**Comment by matteo-briani** [comment]
I will gladly take a look at it, so I can familiarize with the codebase.

**Comment by GuillaumeGomez** [comment]
Sure, go ahead! Do test locally:

```
./x.py doc std --stage 1 --open
```

Like that you can then go to the page and check if the bug is fixed. ;)
