### ISSUE TITLE
Escaped Markdown table column separator renders with escape char in code span in Rust doc

### ISSUE THREAD

**Issue by dbeckwith** [rust-lang/rust#86375]
Writing a Markdown table in a Rust doc string, I noticed a case where the `|` character needs to be escaped, but the escape shows up in code spans.

```rust
/// | table |
/// |---|
/// | `T \| null` |
```

I want the rendered code span to look like `T | null`. If I use the code above, it renders as `T \| null`. If I remove the `\`, the table gets messed up because the `|` is interpreted as a column separator. IMO the more reasonable thing would be if `|` inside a code span was never interpreted as a column separator.

Then again, in GitHub it seems to render correctly with the escape, so maybe that's the correct way:
```
| table |
|---|
| `T \| null` |
```
| table |
|---|
| `T \| null` |
```
| table |
|---|
| `T | null` |
```
| table |
|---|
| `T | null` |

### Meta

`rustc --version --verbose`:
```
rustc 1.52.1 (9bc8c42bb 2021-05-09)
binary: rustc
commit-hash: 9bc8c42bb2f19e745a63f3445f1ac248fb015e53
commit-date: 2021-05-09
host: x86_64-unknown-linux-gnu
release: 1.52.1
LLVM version: 12.0.0
```
`cargo --version --verbose`:
```
cargo 1.52.0 (69767412a 2021-04-21)
release: 1.52.0
commit-hash: 69767412acbf7f64773427b1fb53e45296712c3c
commit-date: 2021-04-21
```

**Comment by ehuss** [comment]
This is a know issue with the markdown renderer, see https://github.com/raphlinus/pulldown-cmark/issues/356 for more information.  Essentially, markdown forbids escaping inside backtick spans, but GitHub's extension made an exception for that for escaping pipes in tables. The renderer doesn't support that exception.  A workaround is to use `<code>` tags instead of backticks.

**Comment by dbeckwith** [comment]
Thanks, the `<code>` workaround works great

**Comment by jyn514** [comment]
I'm going to close this since rustdoc won't fix it.
