### ISSUE TITLE
Tracking Issue for separate array length function

### ISSUE THREAD

**Issue by shamatar** [rust-lang/rust#86403]
Feature gate: `#![feature(array_len)]`

This is a tracking issue for a separate length function on arrays (without coercing into slice and calling `slice::len`). It allows to lower array length access into constant in MIR without any additional modifications.

### Public API

```rust
// core::array

impl<T, const N: usize> [T; N] {
    #[inline]
    pub const fn len(&self) -> usize {
        N
    }
```

### Steps / History

- [ ] Implementation: #86404 
- [ ] Final commenting period (FCP)
- [ ] Stabilization PR

### Unresolved Questions

None so far

**Comment by shamatar** [comment]
As pointed in the implementation PR it's breaking if it's not immediately stable, but if it is then current machinery is ok with resolving a proper one

**Comment by m-ou-se** [comment]
Closing this for now, because we still need to figure out if we want this addition.

(And if we do, it'd have to be insta-stable, so then there'd be no unstable feature to track anyway.)
