### ISSUE TITLE
Error when `use`ing enum and enum varient with same name

### ISSUE THREAD

**Issue by aDotInTheVoid** [rust-lang/rust#86418]
I tried this code:

```rust
pub mod ast {
    pub enum Expr {
        Lit(Lit),
        Other,
    }

    pub enum Lit {
        A,
        B,
    }
}

pub mod eval {
    use super::ast::{Expr, Lit};

    pub fn eval(e: Expr) -> i32{
        use Expr::*;
        match e {
            Lit(l) => match l {
                Lit::A => 1,
                Lit::B => 2,
            },
            Other => 3,
        }
    }
}
```

I expected to see this happen: *code compiles without errors*

Instead, this happened: 

```
error[E0433]: failed to resolve: `Lit` is a variant, not a module
  --> src/lib.rs:20:17
   |
20 |                 Lit::A => 1,
   |                 ^^^ `Lit` is a variant, not a module

error[E0433]: failed to resolve: `Lit` is a variant, not a module
  --> src/lib.rs:21:17
   |
21 |                 Lit::B => 2,
   |                 ^^^ `Lit` is a variant, not a module

warning: unused import: `Lit`
  --> src/lib.rs:14:28
   |
14 |     use super::ast::{Expr, Lit};
   |                            ^^^
   |
   = note: `#[warn(unused_imports)]` on by default
```

[playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=38c25e8e6f8e6b091c05b93ae1dbe9e0)

If I add `use super::ast::Lit;` to `fn eval` I instead get

```
warning: unused import: `Lit`
  --> src/lib.rs:14:28
   |
14 |     use super::ast::{Expr, Lit};
   |                            ^^^
   |
   = note: `#[warn(unused_imports)]` on by default

warning: the item `Lit` is imported redundantly
  --> src/lib.rs:18:13
   |
14 |     use super::ast::{Expr, Lit};
   |                            --- the item `Lit` is already imported here
...
18 |         use super::ast::Lit;
   |             ^^^^^^^^^^^^^^^

warning: 2 warnings emitted
```

But the code compiles without errors. The secound error is correct, but I believe the first is wrong, as `Lit` is used, but apparently the secound `use` works when the first doesnt

[playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=e2d30e99eed372f9f455f72182d02274)

If `use super::ast::Lit` is just in `fn eval` (and not `mod eval`), everthing is fine. [playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=f4efd2d441cb401f359043147f35fe16). If it's only in the mod, you get errors, and it its in both, you get warnings about the first import being unused, and the secound being redundant, which are incorrect

### Meta

`rustc --version --verbose`:
`1.55.0-nightly (2021-06-16 a85f584aebd9b08314bf)` (playground)

**Comment by petrochenkov** [comment]
This is not a bug, variant `Lit` imported by `use Expr::*;` shadows enum `Lit` imported by `use super::ast::{Expr, Lit};`.

Non-glob imports are prioritized over glob imports only if they are in the same module, otherwise the closest import wins.
