### ISSUE TITLE
debuginfo: Variables in generic functions should have generic type.

### ISSUE THREAD

**Issue by michaelwoerister** [rust-lang/rust#8641]
As per _3.3.7 Function Template Instantiations_ of the DWARF 4 specification, the template type parameter DIE (debug information entry) should be referenced where it has been used in the source code, as opposed to the DIE for the type that has been substituted for the parameter. 

In the context of Rust this would mean that the variable `x` in the following function should be described as having type `T=int` instead of just type `int`:

``` Rust
fn generic_fun<T>(x: T) -> T {
    ...
}

fn main() {
    let s_have = Some(generic_fun(11111));
}
```

As of PR https://github.com/mozilla/rust/pull/8554 generic functions are supported but arguments, return value, locals, etc are described as having their type concrete type instead of "their generic type substituted by their concrete type". That means that debug info loses some information.

This should not pose a big problem to the regular debugging workflow---but I wanted to record somewhere that this issue exists.

**Comment by steveklabnik** [comment]
Triage: nothing to add.

**Comment by steveklabnik** [comment]
Triage: same as last year.

**Comment by Mark-Simulacrum** [comment]
As far as I can tell, this is now fixed, or at least equivalent to output from C++ code. Closing, please reopen if that's not the case.

Apologies for my potentially terrible C++, I'm not really familiar enough to speak to it.

```c++
template<class T>
T generic_fun(T a) {
        return a;
}

int main() {
        int test = 5;
        return generic_fun(test);
}
```

c++ gdb:
```
(gdb) rbreak generic_fun
Breakpoint 1 at 0x4004f8: file ./test.cpp, line 3.
int generic_fun<int>(int);
```

```rust
fn generic_fun<T>(x: T) -> T {
    x
}

fn main() {
    let s_have = Some(generic_fun(11111));
}
```

rust gdb:
```
(gdb) rbreak generic_fun
Breakpoint 1 at 0x68b7: file ./t.rs, line 1.
static i32 t::generic_fun<i32>(i32);
```

**Comment by michaelwoerister** [comment]
Yes, what we are doing here is not really wrong (otherwise the issue would not have stayed unfixed for so long).
Did you look at the DWARF that various compilers generate? I can imagine that they omit this information because it's not used much and just takes up space.
