### ISSUE TITLE
EncodeWide::size_hint doesn't account for `self.extra`

### ISSUE THREAD

**Issue by programmerjake** [rust-lang/rust#86414]
https://github.com/rust-lang/rust/blob/4d3ce2e7dac840d6ac7d658a5506eb31492fb3ef/library/std/src/sys_common/wtf8.rs#L854-L860

I haven't tested it, but, on Windows the following test should pass with the current code, demonstrating how `size_hint` is currently broken:
```rust
#[test]
fn test() {
    let os_str: &OsStr = "\u{12345}".as_ref();
    let mut iter = os_str.encode_wide();
    iter.next().unwrap();
    // at this point iter.code_points is empty and iter.extra is non-zero
    assert_eq!((0, Some(0)), iter.size_hint());
    // size_hint returned 0, yet we didn't reach the end:
    iter.next().unwrap();
}
```

**Comment by ChrisDenton** [comment]
As expected the test code does not panic on Windows. The size hint is initially only `1`.
