### ISSUE TITLE
Investigate performance impact of debuginfo typename generation

### ISSUE THREAD

**Issue by michaelwoerister** [rust-lang/rust#86431]
The [code generating type names for debuginfo](https://github.com/rust-lang/rust/blob/master/compiler/rustc_codegen_ssa/src/debuginfo/type_names.rs) does not seem to do any kind of caching of repeatedly occurring string segments (e.g. path prefixes and type renderings). Given that type names can get very long when generics are involved it's worth investigating how much time the compiler spends doing redundant work here.

**Comment by jyn514** [comment]
https://github.com/rust-lang/rust/issues/84873#issuecomment-832860003 is also somewhat related, the names getting passed into llvm can get very long, especially for generators

**Comment by Sl1mb0** [comment]
I'd like to tackle this. I'm curious where th

**Comment by Sl1mb0** [comment]
Posted this in Zulip but I'll post it here too:

- What is meant by the term "type renderings"? Does this refer to matching `TyKind` to it's string literal value e.g. `ty::Bool => output.push_str("bool")` ? or does it refer to pushing the type's identifier onto the output string? Just want to be sure.

- As for how to approach caching repeat string segments, my current idea is to use a wrapper to a hash map that uses a `TyKind` as a key to a string literal e.g. `<TyKind, &str>`. This wrapper will also implement the   `push_debuginfo_type_name()`and `compute_debuginfo_type()` functions. The caching will occur in `push` when we have matched to a given type. Just check if the type is in the cache and if not, load it. Then use it's key to push the string literal onto the output string.

- Part of this issue means analyzing redundant work that the compiler is currently doing. I am wondering if there is a "best approach" to this. As so far my only idea is to profile the compiler before I make changes, and after I make changes, and observe any differences. I don't think this will yield an accurate assessment however, and am curious if anyone would suggest something different.

**Comment by michaelwoerister** [comment]
https://github.com/rust-lang/rust/pull/88898 implemented caching as an experiment but it didn't really improve performance. We concluded that we'd rather not have the additional implementation complexity.
