### ISSUE TITLE
cross-crate `#[doc(hidden)]` is ignored when listing trait implementations

### ISSUE THREAD

**Issue by danielhenrymantilla** [rust-lang/rust#86448]
### Context

https://users.rust-lang.org/t/hidden-trait-implementation-in-online-docs/61256/4

### Repro

```bash
set -euo pipefail
cd $(mktemp -d)

cargo new -q --lib dependency
cat> dependency/src/lib.rs <<'EOF'
    #[doc(hidden)]
    pub enum HiddenType {}
    
    pub enum MyLibType {}
    impl From<HiddenType> for MyLibType {
        fn from (it: HiddenType)
          -> MyLibType
        {
            match it {}
        }
    }
EOF
(cd dependency
    set -x
    cargo doc -q --no-deps
    # No matches
    ! grep -o HiddenType target/doc/dependency/index.html
)

cargo init -q --lib --name mylib
cat> src/lib.rs <<'EOF'
    pub use ::dependency::HiddenType; // OK, not re-exported
    
    pub enum MyLibType {}
    impl From<HiddenType> for MyLibType {
        fn from (it: HiddenType)
          -> MyLibType
        {
            match it {}
        }
    }
EOF

cat>> Cargo.toml <<'EOF'
    dependency.path = 'dependency'
EOF

set -x
cargo doc -q --no-deps
# No matches
! grep -o HiddenType target/doc/mylib/index.html
# There are matches
grep -o HiddenType target/doc/mylib/enum.MyLibType.html
```

  - Last line yields several occurrences of `HiddenType` in the generated `.html` file.

    ## Expected behavior

    No occurrences of `HiddenType` anywhere since it was `#[doc(hidden)]`

  - [Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=14b5e1c16ef0dc2df505fba4d4e2065c)

@rustbot label C-bug T-rustdoc

cc @GuillaumeGomez

**Comment by jyn514** [comment]
I expect the fix is to check for `doc(hidden)` just after https://github.com/rust-lang/rust/blob/e82b65026dcadf0998e3abf9dabc677f63160de7/src/librustdoc/clean/inline.rs#L370.

**Comment by fee1-dead** [comment]
cc @jyn514 

I checked for doc(hidden) like this:
```rust
    if let Some(did) = for_.def_id() {
        if cx.tcx.get_attrs(did).lists(sym::doc).has_word(sym::hidden) {
            return
        }
    }
```

But it doesn't seem to work, as my test would fail. I also tried using the same way to check for `trait_` but it also failed.  I noticed that the issue involves `From<HiddenType>` so I might need to iterate over generic parameters, I cannot find any function that does that in `TyCtxt`, so can someone point me in the right direction? Thanks :)

**Comment by danielhenrymantilla** [comment]
You can look at how the `strip-hidden-items` pass works: https://github.com/rust-lang/rust/blob/0aa28446f8422ed03845b00074fd49eabc28c695/src/librustdoc/passes/stripper.rs#L142-L143

**Comment by jyn514** [comment]
@danielhenrymantilla am I right in understanding this only happens for cross-crate traits, and impls for hidden traits in the same crate are still hidden? In other words, #86513 just makes the cross-crate case consistent?

**Comment by danielhenrymantilla** [comment]
I believe so, yes: the `strip-hidden-items` pass was already taking care of such cases for _local_ `#[doc(hidden)]` types. FWIW, the thing that motivated this discussion was noticing a `From<Unique<T>> for ptr::NonNull<T>` leaking on the docs for `::std`, but not on the ones for `::core`
