### ISSUE TITLE
Panic safety issue in `Zip::next_back()` TrustedRandomAccess specialization

### ISSUE THREAD

**Issue by Qwaz** [rust-lang/rust#86443]
https://github.com/rust-lang/rust/blob/312b894cc12240a3fcc645474c3daa14f7d568ea/library/core/src/iter/adapters/zip.rs#L296-L301

https://github.com/rust-lang/rust/blob/312b894cc12240a3fcc645474c3daa14f7d568ea/library/core/src/iter/adapters/zip.rs#L235-L244

Yet another soundness bug in Zip's TRA specialization. Line 300 is not called when line 298 panics. This leaves `self.a_len` outdated, which results in calling `__iterator_get_unchecked()` with an invalid index in line 242.

Here is a [playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=52b3da1b55be68e043676780a00df1e4) that demonstrates creating two mutable references to the same memory location without unsafe code.

**Comment by apiraino** [comment]
How close is this to #85873?

**Comment by the8472** [comment]
The same functions are involved but the aspects that interact to cause unsafety are quite different.

@rustbot claim

**Comment by Qwaz** [comment]
I agree, this is much closer to #81740.
