### ISSUE TITLE
rustdoc rendering for stable-but-const-unstable `const fn` is misleading

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#86464]
I just spent 5min of horror after seeing this rustdoc page:
![Screenshot 2021-06-19 at 10-07-35 f32 - Rust](https://user-images.githubusercontent.com/330628/122635810-31b60500-d0e6-11eb-8eaf-84e5b97237f2.png)

and then I realized that the `const`ness of this function is unstable.  rustdoc should either indicate that, or just not show the `const` at all for stable functions whose `const`ness is still unstable.

Cc @rust-lang/rustdoc @rust-lang/wg-const-eval

**Comment by Nemo157** [comment]
It'd be nice to still show that it's unstably `const`, but I feel like my 2 minute prototype would be too easy to accidentally skim as a standard "unstable API" annotation. Is there some simple way we could link to the `const`ification tracking issue while leaving it clear that the function is stable?

![image](https://user-images.githubusercontent.com/81079/122637012-ab50f180-d0ec-11eb-91e3-13803aa94198.png)

**Comment by GuillaumeGomez** [comment]
Not show the const on stable rendering if not stable?

**Comment by fee1-dead** [comment]
Why not like this?

![image](https://user-images.githubusercontent.com/43851243/122640166-854d4080-d130-11eb-8578-e27738ceefe0.png)

(this is edited)

**Comment by GuillaumeGomez** [comment]
That works too!
