### ISSUE TITLE
LNK1181 when trying to build Python lib module (W10)

### ISSUE THREAD

**Issue by Mrodent** [rust-lang/rust#86471]
I am trying to write a Rust module which can be called from CPython.

Please see [this SO question](https://stackoverflow.com/q/68045372/595305).

The build never works with `--release` switch and only intermittently without it.

I have no idea what the issue is here but it's presumably something to do with the toolchain(s) on W10.

**Comment by JohnTitor** [comment]
The linker error seems unrelated to Rust itself but it should be related to RustPython. Here only tracks issues related to rustc and some other things, and the questions like yours should go to the [user forum](https://users.rust-lang.org) (or the places related to RustPython). In this case, you've opened a SO question so it's better to wait for answers. Thanks for reporting anyway!

**Comment by Mrodent** [comment]
OK
