### ISSUE TITLE
Support lowercase error codes in `--explain`

### ISSUE THREAD

**Issue by Skalman** [rust-lang/rust#86518]
It would be nice if `rustc --explain` supported lowercase error codes:

The current output is:

```
$ rustc --explain e0106
error: e0106 is not a valid error code
```

Ideally, the command would work regardless of whether you enter `e0106` or `E0106`:

```
$ rustc --explain e0106

This error indicates that a lifetime is missing from a type. If it is an error
inside a function signature, the problem may be with failing to adhere to the
lifetime elision rules (see below).

[...]
```

**Comment by inquisitivecrystal** [comment]
I'm just about to open a pull request for this. Thank you for bringing it up!
