### ISSUE TITLE
metadata technical debt

### ISSUE THREAD

**Issue by graydon** [rust-lang/rust#8652]
Tracking bug for issues to fix in metadata that make it difficult to imagine larger scale fixes:

  - #4573 : finish metadata::encode_info_for_mod
  - #2213 : extract metadata into its own crate
  - #2419 : don't use external node IDs in crate metadata
  - #3474 : crate store doesn't deduplicate used crates
  - #1920 : absolute paths are nor correct for crates not in root namespace

There are probably a lot of other bugs here. Please add them so we can get multiple hands cleaning this stuff up.

**Comment by steveklabnik** [comment]
Triage: all but one of the original bugs are closed, so I'm just going to close this one. https://github.com/rust-lang/rust/issues/2419 stands alone.
