### ISSUE TITLE
its very very slow when cargo test on Ubuntu 

### ISSUE THREAD

**Issue by mybee** [rust-lang/rust#86569]
system:
```shell
root@ubuntu ~/m/drepo# uname -a
Linux ubuntu 5.4.0-74-generic #83~18.04.1-Ubuntu SMP Tue May 11 16:01:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

take about 30 minutes time T.T

**Comment by JohnTitor** [comment]
Could you provide a reproducible example or any information about the issue if possible? It's quite hard to address the issue without them.

**Comment by JohnTitor** [comment]
Going to close as the information to reproduce is missing. Feel free to re-open with it. Thanks for reporting!
