### ISSUE TITLE
rustdoc: Move the extra labels to the symbol in tables

### ISSUE THREAD

**Issue by dns2utf8** [rust-lang/rust#86578]
Currently labels like `Deprecated` are in the right column far away from the symbol they describe:

![](https://user-images.githubusercontent.com/739070/123140925-5f34e280-d447-11eb-8a6c-a92a9138932b.png)
![](https://user-images.githubusercontent.com/739070/123140997-6cea6800-d447-11eb-9242-7959bc548006.png)

I propose we move them to the symbol in the left column.

Cheers,
Stefan

From #85651

**Comment by GuillaumeGomez** [comment]
Do you want to be assigned on it?

**Comment by dns2utf8** [comment]
Yes, please :+1:

**Comment by GuillaumeGomez** [comment]
Done. :)

**Comment by dns2utf8** [comment]
Thanks! :)

**Comment by dns2utf8** [comment]
I uploaded a demo for the PR: https://data.estada.ch/rustdoc-nightly_2336406b38_2021-06-24/rustdoc_demo/mod1/index.html

**Comment by dns2utf8** [comment]
Implemented with #86594, potentially improved by #86767

**Comment by jyn514** [comment]
Closing this since it was implemented.
