### ISSUE TITLE
RLS does not build on aarch64 Windows

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#86606]
For the last several cycles we've been cherry picking a patch (https://github.com/rust-lang/rust/commit/c4aeccdf45fdf8e543929298c4ad5bcfc7e00111) to disable the normal missing tools failure on beta/stable, due to winapi 0.2 not building on aarch64 Windows - https://github.com/rust-lang-ci/rust/runs/2896069230

**Comment by JohnTitor** [comment]
cc rust-lang/rls#1693

**Comment by Mark-Simulacrum** [comment]
I've filed #86607 which will ignore failures building RLS on aarch64.
