### ISSUE TITLE
 Implementation Issue for RFC 2528: type-changing struct update syntax #86555 

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#86618]
This issue tracks the implementation of rust-lang/rfcs#2528, "type changing struct update syntax" (general tracking issue: https://github.com/rust-lang/rust/issues/86555).

**Comment by nikomatsakis** [comment]
@rustbot assign @kolharsam 

They expressed an interest in this!

**Comment by nikomatsakis** [comment]
Here are some mentoring notes.

## Step 0: Create the feature gate

We need a feature gate to control when users are accessing this feature. Instructions for adding a feature gate are here:

https://rustc-dev-guide.rust-lang.org/feature-gates.html#adding-a-feature-gate

**Adding a feature gate can and should be its own PR!**

**Comment by nikomatsakis** [comment]
Oh, one thing I forgot to mention! We are going to want to make these changes *conditional* on whether the feature gate is enabled.

**Comment by kolharsam** [comment]
> Here are some mentoring notes.
> 
> ## PR 0: Create the feature gate
> We need a feature gate to control when users are accessing this feature. Instructions for adding a feature gate are here:
> 
> https://rustc-dev-guide.rust-lang.org/feature-gates.html#adding-a-feature-gate
> 
> **Adding a feature gate can and should be its own PR!**

@nikomatsakis Have made a respective PR for the same here: https://github.com/rust-lang/rust/pull/86646

**Comment by kolharsam** [comment]
> ## PR 1: Write up some tests
> A good next step is to open a PR creating a directory in `src/tests/ui` for this feature and adding the various tests. It's ok if they get errors today! Just document the current behavior. But I've always found it's actually much easier to write tests BEFORE you start the code then after!

@nikomatsakis I've made a PR with a failing test here: #86660. 
Currently, it just document's the error that might be seen while using the suggested updates to the syntax in within the RFC. 

Please let me know if there are any other test cases that need to be added because I wasn't really sure about what needed to be done here.

**Comment by nikomatsakis** [comment]
I don't believe we've implemented this feature yet =) there are mentoring notes [here](https://github.com/rust-lang/rust/issues/86618#issuecomment-868976919). I know that someone was looking into it, maybe it was @kolharsam? (If I failed to get back to you, @kolharsam, sorry, are you still interested?)

**Comment by kolharsam** [comment]
@nikomatsakis Yes, I was looking into it, and I'm still interested in continuing the work.

**Comment by Kobzol** [comment]
The feature has actually been implemented in https://github.com/rust-lang/rust/pull/90035, if I'm not mistaken. It already seems to work: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=a84582797c0337611b94e3c5afaeba91.
@Systemcluster could you please create a separate issue with your code snippet? It looks like a bug in the implementation of the feature.

**Comment by Mark-Simulacrum** [comment]
We think this is implemented now, so closing this issue. https://github.com/rust-lang/rust/issues/86555 is still tracking the feature.
