### ISSUE TITLE
rustdoc: upgrade or remove normalize.css

### ISSUE THREAD

**Issue by jsha** [rust-lang/rust#86629]
We're using a very old version of normalize.css (3.0.0, from 2014). In #82313 I tried to update to the latest, 8.0.1. But it was reverted in #82549 because of these regressions:

#82548
#82542

At the time we didn't worry about it much since we didn't need the update for anything. However, it turns out in #86589 that our old version of normalize.css is hiding the triangles on user-provided `<details>` tags, when it shouldn't be.

See these demos:

https://jsbin.com/jorowazuli/edit?html,output

https://jsbin.com/kecozayaka/edit?html,output

The right path forward is to figure out why upgrading normalize.css caused those regressions, fix the issues, and then do the upgrade. Alternately, we may conclude that we no longer need normalize.css, which would be an even nicer outcome.

**Comment by inquisitivecrystal** [comment]
@rusbot label C-cleanup T-rustdoc
