### ISSUE TITLE
rustdoc: trait implementors don't have assoc. types shown

### ISSUE THREAD

**Issue by cynecx** [rust-lang/rust#86631]
Live: https://doc.rust-lang.org/nightly/std/iter/trait.IntoIterator.html#impl-IntoIterator-30

Trait implementors don't have their assoc. types shown (stable -> nightly regression).

nightly:

![image](https://user-images.githubusercontent.com/5961244/123470800-2d617e80-d5f5-11eb-92aa-ac85a9f7619e.png)

stable:

![image](https://user-images.githubusercontent.com/5961244/123470834-3b170400-d5f5-11eb-8a14-83a8e319a6d5.png)

```
rustdoc 1.55.0-nightly (7c3872e6b 2021-06-24)
```

**Comment by jyn514** [comment]
This was intentional in https://github.com/rust-lang/rust/pull/85970. cc @jsha

**Comment by cynecx** [comment]
Well, the PR title/description says something different:

    Remove methods under Implementors on trait pages

It’s about removing the methods. Personally, that sounds fine. But why did the PR remove the whole section including associated types. To me that’s a really valuable insight/convenience.

**Comment by jyn514** [comment]
Ah, I see. Yes, I agree only the methods should have been removed.

**Comment by apiraino** [comment]
Assigning priority as discussed in the [Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2386631.20rustdoc.3A.20trait.20implementors.20don't.20have.20assoc.2E.20types.20.E2.80.A6) of the Prioritization Working Group.

@rustbot label -I-prioritize +P-high

**Comment by GuillaumeGomez** [comment]
There is https://github.com/rust-lang/rust/pull/87035 open to fix implementors already. I can fix it once this https://github.com/rust-lang/rust/pull/87035 has been merged.

**Comment by camelid** [comment]
triage: It looks like #87035 has been merged now.

**Comment by cynecx** [comment]
Can we perhaps revert #85970 for the time
being until this gets resolved?

**Comment by camelid** [comment]
Reopening to track beta backport.

**Comment by Mark-Simulacrum** [comment]
Closing - backported in #88641
