### ISSUE TITLE
rustdoc: enum fields should use fully-qualified type

### ISSUE THREAD

**Issue by jsha** [rust-lang/rust#86640]
Right now, when an enum field is rendered, it uses the bare type name without module or crate qualifiers. For instance: https://docs.rs/rustls/0.19.1/rustls/enum.TLSError.html

```
pub enum TLSError {
    ...
    WebPKIError(Error),
    InvalidSCT(Error),
```

Those `Error` are two different error types from other crates: webpki::Error and sct::Error. And indeed you can see that by hovering them. I think the displayed name should also use the fully qualified form.

**Comment by jyn514** [comment]
This is a duplicate of an existing issue, but I can't find it.

**Comment by camelid** [comment]
I found it: #42066.
