### ISSUE TITLE
Implementing Add traits for Custom struct invalidates String+&String

### ISSUE THREAD

**Issue by zhuxiujia** [rust-lang/rust#86681]
error[E0277]: cannot add `&std::string::String` to `std::string::String`
for example：
```rust
#[cfg(test)]
mod test {
    use std::ops::Add;
    pub struct A{
        pub i:String,
    }
    impl Add<A> for String{
        type Output = String;

        fn add(mut self, rhs: A) -> Self::Output {
            self=self+rhs.i.as_str();
            self
        }
    }

    #[test]
    pub fn test_log() {
         let s="s".to_string();
          let a=A{
              i: "1".to_string()
          };
          let s=s+a;
          let s=s+&a.i; //error[E0277]: cannot add `&std::string::String` to `std::string::String`
         //let s=s+a.i.as_str();//this is ok
    }
}

```

**Comment by cuviper** [comment]
Normally, there is only `Add<&str> for String`, so that impl is chosen and your `&String` gets coerced to `&str`.

When you add a new `Add<_> for String`, you make it ambiguous, so there's no coercion.

**Comment by zhuxiujia** [comment]
> Normally, there is only `Add<&str> for String`, so that impl is chosen and your `&String` gets coerced to `&str`.
> 
> When you add a new `Add<_> for String`, you make it ambiguous, so there's no coercion.
