### ISSUE TITLE
"Manual" crater run for edition migration

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang/rust#86691]
Before doing the public test, we should do a manual crater run. Here are the crates.io top-downloaded crates:

* rand
* syn
* libc
* rand_core
* quote
* unicode-xid
* proc-macro2
* cfg-if
* serde
* bitflags

**Comment by rylev** [comment]
Here is a running list of issues found in manual crater testing the edition migrations:
* https://github.com/rust-lang/rust/issues/86753
* https://github.com/rust-lang/rust/issues/86751

**Comment by rylev** [comment]
If you'd like to run this "mini" crater yourself, please take a look at my absolutely horrendous Ruby code [here](https://gist.github.com/rylev/79440dcfc04513a607bf6fdb9b458255).

**Comment by rylev** [comment]
Closing this now as we've done the run and found some issues. I think we're unlikely to find more issues in this controlled path, and we should focus on the full crater run and public testing.
