### ISSUE TITLE
can't move variable into closure in special case

### ISSUE THREAD

**Issue by FH0** [rust-lang/rust#86709]
```rust
use futures::Future;
use tokio::sync::mpsc::channel;

fn foo<F, S>(mut f: F)
where
    F: FnMut() -> S,
    S: Future,
{
    f();
}

#[tokio::main]
async fn main() {
    let (tx, mut rx) = channel::<bool>(1);
    foo(move || async move {
        let _ = rx.recv().await;
    });
}
```

I want to move rx into closure but failed.
![image](https://user-images.githubusercontent.com/32861476/123742648-99d2cb00-d8de-11eb-9e43-050a0510092a.png)

I checked a lot of information but still can't solve it.
- https://github.com/hyperium/hyper/blob/master/examples/http_proxy.rs#L30-#L33
- https://github.com/rust-lang/rust/issues/41790
- https://stackoverflow.com/questions/53038935/cannot-move-out-of-captured-variables-in-an-fnmut-closure
- https://docs.rs/hyper/0.14.9/hyper/service/fn.service_fn.html

**Comment by fee1-dead** [comment]
You expect the closure to be `FnMut`, but it can't. This is because you can't call it multiple times, since calling it moves `rx` into an async block.

**Comment by FH0** [comment]
I did some attempts and it can only be called once. Finally I solved the problem using macros.
