### ISSUE TITLE
Use copy_file_range(2) only on Linux >= 5.3

### ISSUE THREAD

**Issue by kubo39** [rust-lang/rust#86718]
In case copy_file_rang(2), [Linux's man page][linux-man] says:

> A major rework of the kernel implementation occurred in 5.3.
       Areas of the API that weren't clearly defined were clarified and
       the API bounds are much more strictly checked than on earlier
       kernels.  Applications should target the behaviour and
       requirements of 5.3 kernels.
>       First support for cross-filesystem copies was introduced in Linux
       5.3.  Older kernels will return -EXDEV when cross-filesystem
       copies are attempted.

And at least [Go's Issue shows][go-issue] that it's broken in CIFS.
I think it should be fixed like [Go][go-patch] did.

[linux-man]: https://man7.org/linux/man-pages/man2/copy_file_range.2.html
[go-issue]: https://github.com/golang/go/issues/42400
[go-patch]: https://github.com/golang/go/commit/1c7650aa93bd53b7df0bbb34693fc5a16d9f67af

**Comment by the8472** [comment]
Is that issue not covered by the workaround in #75428?

**Comment by kubo39** [comment]
Ahh, sorry I should've looked into more deeply. I think this is covered by #75428 so close.
