### ISSUE TITLE
[BUG] in std lib, trim_start_matches

### ISSUE THREAD

**Issue by JinAirsOs** [rust-lang/rust#86736]
I tried this code:

```rust
let mut ans = String::new();
ans.push('0');

ans.trim_start_matches('0');

println!("{}:{}", ans, ans.len());
```

I expected to see this happen: *:0 is printed*

Instead, this happened: *0:1*

### Meta

`rustc --version --verbose`:
```
rustc 1.50.0 (cb75ad5db 2021-02-10)
binary: rustc
commit-hash: cb75ad5db02783e8b0222fee363c5f63f7e2cf5b
commit-date: 2021-02-10
host: x86_64-apple-darwin
release: 1.50.0
```

**Comment by Seadragon91** [comment]
The function [trim_start_matches](https://doc.rust-lang.org/std/primitive.str.html#method.trim_start_matches) returns the modified string.
Change
`ans.trim_start_matches('0');`
to
`let ans = ans.trim_start_matches('0');`

Then it's correct.

**Comment by JohnTitor** [comment]
Closing as it works as expected.
