### ISSUE TITLE
Adding `From` instances can make previously valid programs fail type inference

### ISSUE THREAD

**Issue by jay-invariant** [rust-lang/rust#86738]
# Minimal example

This works:
```rust
struct Foo;

fn foo() -> Result<(), Foo> {
    let inner = || {
        Err(Foo)?;
        Ok(())
    };
    inner()?;
    Ok(())
}
```

Now add the following:
```rust
struct Bar;

impl From<Foo> for Bar {
    fn from(_: Foo) -> Bar {
        Bar
    }
}

impl From<Bar> for Foo {
    fn from(_: Bar) -> Foo {
        Foo
    }
}
```

This causes compilation to fail with:
```
error[E0282]: type annotations needed for the closure `fn() -> std::result::Result<(), _>`
  --> test.rs:19:17
   |
19 |         Err(Foo)?;
   |                 ^ cannot infer type
   |
help: give this closure an explicit return type without `_` placeholders
   |
18 |     let inner = || -> std::result::Result<(), _> {
   |  
```

The problem is that these pieces of code can be in completely different crates.  In my opinion, the first snippet should also fail, since it can be broken by seemingly innocent changes in dependencies.  More generally, the compiler should not assume that "there's only one type I know of that would work here" means we can actually infer that type, since changes in dependencies might add more candidates.

**Comment by circumspect** [comment]
I did some testing in the playground, and here's what I found ([playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=7929ea375af94bf30a97c4eadf45f54c)):

```rust
struct Foo;

fn foo() -> Result<(), Foo> {
    let _k = Foo;
    let inner = || {
        if false {
            // Uncommenting this fixes compilation
            // return Err(Foo);
        }

        // _x's type is unknown!
        let _x = Err(Foo)?;
        Ok(())
    };
    inner()?;
    Ok(())
}

struct Bar;

// This compiles just fine
impl From<Foo> for Bar {
    fn from(_: Foo) -> Bar {
        Bar
    }
}

// This causes compilation to fail
impl From<Bar> for Foo {
    fn from(_: Bar) -> Foo {
        Foo
    }
}

fn main() {
    println!("Hello, world!");
}
```

**Comment by jonas-schievink** [comment]
This is working as expected, and is not something that can be fixed

**Comment by jay-invariant** [comment]
> The reason this can't be fixed is that there's a very large amount of code that relies on the compiler behavior that eagerly uses an impl if it's the only one that was found.

If std or some other commonly used crate added impls like above, all that code would also break, but most people do not consider adding impls for your own types to be a breaking change.  I think it would be preferable to break it soon, with a clear error message.

In any case, I will look into writing an RFC when I have more time.
