### ISSUE TITLE
`rustup-components-history` page outdated

### ISSUE THREAD

**Issue by ralpha** [rust-lang/rust#86786]
I was checking the https://rust-lang.github.io/rustup-components-history/ page.
But it seems to be almost a month out of date. (last update "2021-06-09" and it is now "2021-07-01")
I have seen it go out of sync in the past. But it now has not been updated for almost a month.

I find this page very helpful when updating nightly docker containers to check if components are ready.
Hope this will be fixed at some point. I don't know what systems/CI job/... makes this page update.

**Comment by JohnTitor** [comment]
The issues like this should go to https://github.com/rust-lang/rustup-components-history. In this case, I think it should be resolved by https://github.com/rust-lang/rustup-components-history/pull/35. Thanks for reporting anyway!
