### ISSUE TITLE
Workspaces turning on `dev-dependencies` flags when they should not

### ISSUE THREAD

**Issue by AaronKutch** [rust-lang/rust#86894]
I expect `dev-dependencies` to affect compilation only if I run `cargo test`, `cargo doc`, or some other non-`cargo build` or non-`cargo check` task (the cargo book says "Dev-dependencies are not used when compiling a package for building"). However, I ran into a problem where `dev-dependencies` activates feature flags in a workspace unexpectedly.

I have a repository [here](https://github.com/AaronKutch/weird_flags) that demonstrates a reduced form of the issue. As some background to this setup, I have a complicated workspace that manages several crates. It used to always require nightly, because I needed a lot of features to enable `const` on a lot of functions, and it was one of the main points of the library. I realized that some users would not need the `const` functionality and find compilation on stable more important, so I decided to introduce a "const_support" flag. Some of these features are really close to stabilization, so I decided to use the `never_type` feature to simulate bringing in nightly dependencies for the example.

In the example repo, you can successfully run `cargo build` from within `nightly_user` with a nightly compiler, and you can successfully run `cargo build` from within `stable_user` with a stable compiler. The unexpected part to me is that from within the workspace, the stable compiler fails on `cargo build` despite no `dependencies` or `build-dependencies` requiring the flag. The problem is fixed by removing the dev-dependencies of the "b" crate. It might seem strange that the "b" crate has a dev-dependency on its dependent "a" crate, but believe me this makes a lot more sense in the workspace I reduced this from.

I can easily fix the particular case I have, but I think this is a bug that could cause more problems in the future if an independent `dev-dependency` silently activates a feature that I am not explicitly activating.

**Comment by jonas-schievink** [comment]
Does this get resolved when using the [new resolver](https://doc.rust-lang.org/stable/cargo/reference/resolver.html#resolver-versions)?

**Comment by AaronKutch** [comment]
It does get resolved, thanks
