### ISSUE TITLE
Tracking Issue for `pin_deref_mut`

### ISSUE THREAD

**Issue by jonhoo** [rust-lang/rust#86918]
Feature gate: `#![feature(pin_deref_mut)]`

This is a tracking issue for `Pin::as_deref_mut`.

The feature adds the method `as_deref_mut` to `Pin`, which allow a safe transformation from a `Pin<&mut Pin<P>>` to a `Pin<&mut P::Target>`.

### Public API

```rust
impl<Ptr> Pin<Ptr> {
    pub fn as_deref_mut(self: Pin<&mut Pin<Ptr>>) -> Pin<&mut Ptr::Target>
    where
        Ptr: DerefMut;
}
```

### Steps / History

- [x] #81363
- [x] #129449
- [ ] #129424

### Unresolved Questions

- None yet.

**Comment by RalfJung** [comment]
> from a `Pin<P>`

It's from a `Pin<&'a mut Pin<P>>`, right? The nesting is a bit odd. But I guess it is what comes up in practice?

**Comment by jonhoo** [comment]
Ah, yes, sorry — fixed!

**Comment by coolreader18** [comment]
Are there any remaining blockers on this? It's a pretty useful function for blanket impls for traits with poll methods (e.g. Future already uses it in its `impl<P> Future for Pin<P>` impl).

**Comment by jonhoo** [comment]
Not that I know of — given it touches the `Pin` machinery, I suspect it should go through an actual FCP, but I'll let others be the judge of that :)

**Comment by dtolnay** [comment]
Currently this method is located in its own solitary impl block:

```rust
impl<'a, Ptr: DerefMut> Pin<&'a mut Pin<Ptr>> {
    pub fn as_deref_mut(self) -> Pin<&'a mut Ptr::Target>;
}
```

I'd like to consider changing it to:

```rust
impl<Ptr> Pin<Ptr> {
    pub fn as_deref_mut(self: Pin<&mut Pin<Ptr>>) -> Pin<&mut Ptr::Target>
    where
        Ptr: DerefMut;
}
```

Some advantages:

- Synergy with the existing `as_ref` and `as_mut` signatures (stable since Rust 1.33)
- Lifetime elision reduces noise in the signature
- Turbofish less verbose: `Pin::<&mut T>::as_deref_mut` vs `Pin::<&mut Pin<&mut T>>::as_deref_mut`

```rust
impl<Ptr> Pin<Ptr> {
    pub fn as_ref(&self) -> Pin<&Ptr::Target>
    where
        Ptr: Deref;

    pub fn as_mut(&mut self) -> Pin<&mut Ptr::Target>
    where
        Ptr: DerefMut;
}
```

**Comment by thynson** [comment]
Any concern blocks this from stablization?

**Comment by jonhoo** [comment]
@dtolnay I agree — that is better :+1:

**Comment by coolreader18** [comment]
Would it be possible to start an FCP on this?

**Comment by dtolnay** [comment]
@rust-lang/libs-api:
@rfcbot fcp merge

[`.as_deref_mut()`](https://doc.rust-lang.org/nightly/core/pin/struct.Pin.html#method.as_deref_mut) is like `.get_mut().as_mut()`, but without enforcing an unnecessary `Ptr: Unpin`.
It is like `unsafe { .get_unchecked_mut() }.as_mut()`, but is unconditionally safe.

The use case arises in real-world code when you are implementing a trait that takes `self: Pin<&mut Self>` where the Self type of your impl is `Pin<Ptr>`. So what you have is something like `Pin<&mut Pin<Box<T>>>`, and want to delegate to the impl for `T` which takes `Pin<&mut T>`. Some examples:

In tokio: [`impl<P> AsyncRead for Pin<P>`](https://github.com/tokio-rs/tokio/blob/tokio-1.39.3/tokio/src/io/async_read.rs#L80-L86)

In hyper: [`impl<P> Read for Pin<P>`](https://github.com/hyperium/hyper/blob/v1.4.1/src/rt/io.rs#L298-L304)

In futures: [`impl<P> Stream for Pin<P>`](https://github.com/rust-lang/futures-rs/blob/0.3.30/futures-core/src/stream.rs#L112-L119)

In actix: [`impl<P, A> ActorFuture<A> for Pin<P>`](https://github.com/actix/actix/blob/actix-v0.13.5/actix/src/fut/future/mod.rs#L195-L204)

In libcore:

https://github.com/rust-lang/rust/blob/bf662eb80838008acabc307dd64d84935ce3a20d/library/core/src/future/future.rs#L116-L122

https://github.com/rust-lang/rust/blob/bf662eb80838008acabc307dd64d84935ce3a20d/library/core/src/async_iter/async_iter.rs#L99-L106
