### ISSUE TITLE
rust1.53.0 lifetime and borrow rules unclear

### ISSUE THREAD

**Issue by blinkingso** [rust-lang/rust#86924]
`fn main() {`
    `let mut a = String::from("owned string");`
    `let a_ref = &mut a;`
    `a_ref.push('!');`
    `// cannot borrow `a` as immutable because it is also borrowed as mutable on previous revision. but passed in 1.53.0`
   `println!("{}", a);`
`}`

**Comment by deltragon** [comment]
This does not seem to be a 1.53 change, but rather the non-lexical lifetimes introduced in 1.31/1.36, see https://doc.rust-lang.org/edition-guide/rust-2018/ownership-and-lifetimes/non-lexical-lifetimes.html for more information.
