### ISSUE TITLE
Fn trait associated type (return type) considered unconstrained

### ISSUE THREAD

**Issue by afranchuk** [rust-lang/rust#86934]
I tried this code:

```rust
struct S<F>(F);

impl <'a, F, G> S<F>
where
    F: Fn(&'a u8) -> G
{
    fn call(&mut self) -> G {
        (self.0)(&1)
    }
}
```

I expected to see this happen: `G` should be considered a constrained type.

Instead, this happened:
```
error[E0207]: the type parameter `G` is not constrained by the impl trait, self type, or predicates
```

Note that if you use `'_` as the lifetime instead of `'a`, it works. It also works if there is no lifetime on the input parameter (e.g. if it's not a reference). However I want to constrain `G` to the same lifetime (eventually) so that's not an option. Is this an issue due to some lifetime assumptions about the return type from Fn traits, specifically that having `G: 'a` makes it unconstrained as it can't reason about that?

This is identical for `FnOnce` and `FnMut` as well.

### Meta

`rustc --version --verbose`:
```
rustc 1.53.0 (53cb7b09b 2021-06-17)
binary: rustc
commit-hash: 53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b
commit-date: 2021-06-17
host: x86_64-unknown-linux-gnu
release: 1.53.0
LLVM version: 12.0.1
```

**Comment by Nikitos3026** [comment]
89917481080
Watsap

**Comment by b-naber** [comment]
This seems to not be a big, but an intentional error, see https://github.com/rust-lang/rust/issues/25041

**Comment by b-naber** [comment]
Maybe to summarize why this is an error. The rules for constrained parameters are in [this rfc](https://github.com/nikomatsakis/rfcs/blob/unused-impl-parameters/text/0000-no-unused-impl-parameters.md):

```
If T appears in the impl trait reference,
  then: T is constrained

If T appears in the impl self type,
  then: T is constrained

If <T0 as Trait<T1...Tn>>::U == V appears in the impl predicates,
  and T0...Tn are constrained
  and T0 as Trait<T1...Tn> is not the impl trait reference
  then: V is constrained
```

Since the lifetime parameter `'a` is unconstrained when we determine whether `G` is constrained the third rule does not apply.

**Comment by afranchuk** [comment]
Okay, that's what I suspected. I guess I really want a more powerful `for<'a>` that can apply to the return type (which I've discussed before on Zulip). It'd be very helpful in the future if the error message indicated exactly what makes a particular type unconstrained.

**Comment by overlisted** [comment]
Is anyone working on this?

**Comment by Dylan-DPC** [comment]
Closing this, as it's intentional as per https://github.com/rust-lang/rust/issues/86934#issuecomment-876531234
