### ISSUE TITLE
thread 'main' panicked at 'missing rust-analyzer', src/bootstrap/install.rs:170:14

### ISSUE THREAD

**Issue by boklm** [rust-lang/rust#86999]
I backported the two patches from https://github.com/rust-lang/rust/pull/86568 to 1.53.0 (trying to fix #86436), but now the build fails with:
```
thread 'main' panicked at 'missing rust-analyzer', src/bootstrap/install.rs:170:14
```

According to @Mark-Simulacrum in https://github.com/rust-lang/rust/pull/86568#issuecomment-877141461:
> looks like x.py install likely needs to be similarly updated like in this PR, and that just hasn't happened yet.

**Comment by ehuss** [comment]
I think I see the issue, I'll investigate more.

**Comment by ehuss** [comment]
Posted #86999 with a fix.

**Comment by RalfJung** [comment]
> Posted #86999 with a fix.

I think you meant https://github.com/rust-lang/rust/pull/87007.
