### ISSUE TITLE
Rustdoc: size layout should show "uninhabited" for empty enums, not 0

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#87008]
_Originally posted by @jyn514 in https://github.com/rust-lang/rust/pull/86263#discussion_r666157631_

**Comment by jyn514** [comment]
cc @camelid @pickfire

**Comment by camelid** [comment]
I'm ambivalent, I don't think showing zero is necessarily wrong, especially since that's what's reported by `layout_of`.

**Comment by asquared31415** [comment]
In my opinion, I think that while size 0 is not *wrong*, that showing that it's uninhabited is *more right*, or at least more clear and makes the distinction.

**Comment by pickfire** [comment]
I don't understand uninhabited when I first see it. It is a hard word compared to 0. I think 0 is easier. What if we show `0 (uninhabited)`?

**Comment by GuillaumeGomez** [comment]
I think displaying 0 is better as well, but we can do as @pickfire suggested and simply display both.

**Comment by jyn514** [comment]
0 is wrong. 0 means "this is a zero sized type", like `()` or `NoneError`; it can be created. Uninhabited types cannot be created, they are things like `!` and `enum Void {}`. IMO posting 0 there is actively misleading. See also https://internals.rust-lang.org/t/size-of-uninhabited-types/7651.

> I don't understand uninhabited when I first see it.

Ok, then we can link to some docs. I didn't see anything in the nomicon but I'm sure they'd take a PR adding it to "exotically sized types".

**Comment by jyn514** [comment]
> I'm ambivalent, I don't think showing zero is necessarily wrong, especially since that's what's reported by `layout_of`.

This is a bug imo, it allows transmuting from ZSTs to uninhabited types which is UB.

**Comment by GuillaumeGomez** [comment]
Even if they cannot be created, their size remain 0 as they don't "exist", however since they cannot be constructed, it makes sense to mention they're unhabited types. Well, I don't have a strong conviction on this in any case. I think we all agree for the mention of "unhabited" though.

**Comment by pickfire** [comment]
> Ok, then we can link to some docs. I didn't see anything in the nomicon but I'm sure they'd take a PR adding it to "exotically sized types".

Yeah, that solved the issue of 0 which is wrong. I do think it is better to link it to https://doc.rust-lang.org/stable/reference/glossary.html?highlight=uninhabited#uninhabited, but I think it's wrong to put that in "size" such that it should be in "type" instead, because it doesn't have a size to begin with.

Well, there are parts where rust sacrificed correctness for ease of understanding, one example is `mut` which means uniqueness not exactly mutable all the time.

**Comment by scottmcm** [comment]
Note that uninhabited is orthogonal to size.  You can have an uninhabited type of any size.

**Comment by camelid** [comment]
> Note that uninhabited is orthogonal to size. You can have an uninhabited type of any size.

Hmm, I think that `layout_of` will report that the size is always 0 for an uninhabited type though, unless that's changed recently.

**Comment by scottmcm** [comment]
That would surprise me, since that'd be different from what `size_of` and `align_of` do: <https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=e1ad034d9812b5356493e4faefe4be61>
