### ISSUE TITLE
Rustdoc creates a cursed merged line at the end of the libc docs constants section

### ISSUE THREAD

**Issue by RDambrosio016** [rust-lang/rust#87016]
This is a fun one, while browsing libc docs i found that for some reason, the final constants are merged together into a cursed line:

![what is this rustdoc?](https://imgur.com/3kTrhjW.png)

You can look at this yourself by just going to https://docs.rs/libc/0.2.98/libc/ and scrolling down to the end of `Constants`

**Comment by RDambrosio016** [comment]
Turns out it looks fine on firefox, so this is probably some chrome-specific odd behavior

**Comment by drewtato** [comment]
It's exactly the 1000th grid row. I found this about it: https://stackoverflow.com/questions/47218341/css-grid-layout-in-chrome-seems-not-to-work-properly-with-more-than-1000-rows which links to this: https://github.com/w3c/csswg-drafts/issues/1009 and this: https://bugs.chromium.org/p/chromium/issues/detail?id=688640

**Comment by RDambrosio016** [comment]
I see, in this case i'll close this issue since it's irrelevant to rust/rustdoc 👍
