### ISSUE TITLE
Feature: Provide getters of data and vtable pointer for `RawWaker`?

### ISSUE THREAD

**Issue by oxalica** [rust-lang/rust#87021]
[Docs of `std::task::RawWaker`](https://doc.rust-lang.org/stable/std/task/struct.RawWaker.html):
> It consists of a data pointer and a virtual function pointer table (vtable) that customizes the behavior of the RawWaker.

We said it consists of two pointer, but doesn't enforce its layout by `repr`, nor provide methods to get data and vtable pointer from a constructed `RawWaker`. So it impossible to destruct a `RawWaker` even with `transmute`, since the layout is unknown, which makdes it difficult to pass `RawWaker` or `Waker` across FFI boundary.

Note that `Waker` has `repr(transparent)` on it so it's able to `transmute` into a `RawWaker`. But it barely does anything since we can do nothing with a `RawWaker`. I'm confusing about why there is a `repr(transparent)` struct to an blackbox struct without any methods.

If it's intended to NOT stabilizing the layout of `std::task::RawWaker`. I think we should at least provide methods like `fn data(&self) -> *mut ()` and `fn vtable(&self) -> &'static RawWakerVTable` to do the inverse of `RawWaker::new`, which can be used to destruct it to cross FFI boundary.

**Comment by cuviper** [comment]
It makes sense to me, but it's more precisely a question for @rust-lang/libs-api.

**Comment by tmandry** [comment]
wg-async-foundations discussed and we're generally supportive of the idea, but agreed it's the libs API team who owns this.

**Comment by joshtriplett** [comment]
We discussed this in today's @rust-lang/libs-api meeting. We're in favor of adding these methods, as inverses of `RawWaker::new`. Please feel free to send a PR and we'll r+ it.

**Comment by jstarks** [comment]
I was surprised to see that `as_raw(&self)` was added to `Waker`, but not `into_raw(self)`. This can be worked around via `transmute` or `as_raw` + `forget`, but it's probably still good to round out the API (`from_raw`, `as_raw`, `into_raw`).

**Comment by oxalica** [comment]
> I was surprised to see that `as_raw(&self)` was added to `Waker`, but not `into_raw(self)`. This can be worked around via `transmute` or `as_raw` + `forget`, but it's probably still good to round out the API (`from_raw`, `as_raw`, `into_raw`).

Typically, we can only get `&Waker` from `Context` without cloning. I'd think `into_raw` would be less useful.

**Comment by ultimaweapon** [comment]
I was tried to implement a single threaded async executor on the stable branch and just got bitten by this issue, which forced me to use a [global variable](https://github.com/locenv/locenv/blob/main/crates/locenv/src/service_manager/dispatcher.rs) to store the future-specific data when it got suspended.

**Comment by Amanieu** [comment]
Closing this in favor of the tracking issue #96992.
