### ISSUE TITLE
rustdoc: Styling regressions from stable to beta

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#87072]
### Regression 1

**Ayu-only.** The summary in the search results is now blue, when it used to be white.

#### [beta](https://doc.rust-lang.org/beta/std/?search=match) (incorrect)

![image](https://user-images.githubusercontent.com/37223377/125213243-7147bb00-e266-11eb-94f4-bf9c81e7b394.png)

#### [stable](https://doc.rust-lang.org/stable/std/?search=match) (correct)

![image](https://user-images.githubusercontent.com/37223377/125213262-8886a880-e266-11eb-8340-1d9d2e1cba79.png)

### Regression 2

**Ayu-only.** The color of impls in Ayu has changed from white to yellow. This may be intentional, but it looked off when I saw it. Note that this happens for all impls, not just foreign impls.

#### [beta](https://doc.rust-lang.org/beta/std/panic/trait.UnwindSafe.html#foreign-impls) (incorrect)

![image](https://user-images.githubusercontent.com/37223377/125213341-de5b5080-e266-11eb-9c2e-e534e7d54b8e.png)

#### [stable](https://doc.rust-lang.org/stable/std/panic/trait.UnwindSafe.html#foreign-impls) (correct)

![image](https://user-images.githubusercontent.com/37223377/125214283-1e243700-e26b-11eb-8e9d-bf8a33a02ff7.png)

### Regression 3

**All themes.** Certain auto-trait, foreign, unconditional impls have underlines.

#### [beta](https://doc.rust-lang.org/beta/std/panic/trait.UnwindSafe.html#synthetic-implementors) (incorrect)

![image](https://user-images.githubusercontent.com/37223377/125214314-4f9d0280-e26b-11eb-8ed7-9b733bc2563a.png)

#### [stable](https://doc.rust-lang.org/stable/std/panic/trait.UnwindSafe.html#synthetic-implementors) (correct)

![image](https://user-images.githubusercontent.com/37223377/125214358-9a1e7f00-e26b-11eb-9f35-bc5811b4cbe9.png)

### Regression 4

**All themes.** The phrase `(keyword)` next to `match` in the search results is now red in addition to `match` itself being red, whereas `(keyword)` used to be gray.

#### [beta](https://doc.rust-lang.org/beta/std/?search=match) (incorrect)

![image](https://user-images.githubusercontent.com/37223377/125214594-c25aad80-e26c-11eb-9a9e-81dad5fcd21f.png)

#### [stable](https://doc.rust-lang.org/stable/std/?search=match) (correct)

![image](https://user-images.githubusercontent.com/37223377/125214584-b2db6480-e26c-11eb-91e1-1a1960ef2224.png)

### Meta

All of the regressions seem to have occurred in beta (1.54.0).

**Comment by GuillaumeGomez** [comment]
Regression 3 is fixed in https://github.com/rust-lang/rust/pull/87035.

**Comment by GuillaumeGomez** [comment]
Send a fix for the three others.

**Comment by GuillaumeGomez** [comment]
Regression 1 is fixed in #87085.
