### ISSUE TITLE
Spurious assertion in rustc_codegen_ssa/src/back/write.rs 

### ISSUE THREAD

**Issue by michaelwoerister** [rust-lang/rust#87083]
There seems to be a race condition that sometimes triggers this assertion in CI builds:
https://github.com/rust-lang/rust/blob/e97c29bda238cf55ddd7eec772deb823364b1846/compiler/rustc_codegen_ssa/src/back/write.rs#L1464

See https://github.com/rust-lang/rust/pull/86965#issuecomment-877554723 for an example.

Let's start collecting instances of this issue here.

**Comment by lqd** [comment]
When I looked at this last time, it seemed:
- in the messages with/from the coordinator, codegen being aborted expects [that codegen is not complete and the main worker thread is still codegenning](https://github.com/rust-lang/rust/blob/e97c29bda238cf55ddd7eec772deb823364b1846/compiler/rustc_codegen_ssa/src/back/write.rs#L1454-L1465) (the failing assertion).
- but it seems the main thread worker can start LLVMing in different situations, e.g. [before codegen is complete](https://github.com/rust-lang/rust/blob/e97c29bda238cf55ddd7eec772deb823364b1846/compiler/rustc_codegen_ssa/src/back/write.rs#L1255) and [depending on the queue](https://github.com/rust-lang/rust/blob/e97c29bda238cf55ddd7eec772deb823364b1846/compiler/rustc_codegen_ssa/src/back/write.rs#L1274-L1288) which would appear to break the previous state transition precondition ?

There are other such assertions when other messages are received, maybe the state machine could contain other unexpected state transitions with respect to the main thread worker state ? (For example -- and I don't know if it's possible for this to happen -- while the main thread worker is LLVMing, receiving a `Message::Token()` would transition the main thread worker to idle, which could then trigger similar assertions if `Message::Codegen{Done,Aborted,Complete}` messages are then received)

**Comment by Enselic** [comment]
Triage: The assert was removed in https://github.com/rust-lang/rust/commit/b00d0fa0c9b8b8b2465f827dfc081e8c9a07d882 so let's close this as obsolete.
