### ISSUE TITLE
iter::Flatten, FlatMap should return more precise size_hint and be TrustedLen when item type is an array

### ISSUE THREAD

**Issue by adrian17** [rust-lang/rust#87094]
If I understand correctly, presence of `TrustedLen` trait allows `.collect::<Vec<_>>()` to avoid reallocations, right?

In that case, given the following:
```rs
    #[derive(Clone, Copy)]
    pub struct Pixel(u8, u8, u8, u8);

    let pixels: Vec<Pixel> = vec![Pixel(1, 2, 3, 4); 10];
    let iter = pixels
        .iter()
        .flat_map(|p| [p.0, p.1, p.2, p.3]); // or: .map(|p| [p.0, p.1, p.2, p.3]).flatten();
    println!("{:?}", iter.size_hint());

    let v: Vec<u8> = iter.collect();
 ```
Since the type I map to has known const size (`[u8; 4]`), size_hint should be able to precisely return `(40, Some(40))`, and the iterator specialization should implement TrustedLen.
Currently, it returns `(0, None)`. This means that to implement this function efficiently, I'd need to manually do `Vec::with_capacity(pixels.len() * 4)`.

**Comment by the8472** [comment]
> Currently, it returns (0, None). 

It does a bit better than that. Collecting into a `Vec` first takes an element and only then queries the `size_hint`, which allows `Flatten` to give a better result than you get from its initial state.

https://github.com/rust-lang/rust/blob/b5a2ccee81406303324016d03399fac68ceb6718/library/alloc/src/vec/mod.rs#L2550-L2562


But yes, we should be able to do better for array::IntoIter.

**Comment by adrian17** [comment]
> It does a bit better than that. Collecting into a Vec first takes an element and only then queries the size_hint, which allows Flatten to give a better result than you get from its initial state.

Only a bit better:

```
    let _ = iter.next();
    println!("{:?}", iter.size_hint());
```
results in `(3, None)`. It knows that the first flattened array has 4 elements, but not about further ones.

**Comment by the8472** [comment]
Yeah, sorry, that's what I meant.
