### ISSUE TITLE
rust-docs installation is very slow

### ISSUE THREAD

**Issue by ChristianWilkie** [rust-lang/rust#87131]
**Describe the problem you are trying to solve**
I'm new to Rust and was trying to install it on a Linux machine (user/non-root) by downloading the .tar.gz and using install.sh.

When it reached the part "install: installing component 'rust-docs'" I thought it hanged but it just took a few minutes.

**Describe the solution you'd like**
Not a big deal but just a suggestion - it might be good if there was a mention about it taking a while, maybe something like

"install: installing component 'rust-docs' (this may take a while)"

It would be even better if there was some form of progress indicator but probably that would be a lot more difficult

**Notes**
I also saw it mentioned in https://github.com/rust-lang/rustup/issues/1540 - but this original issue was for Windows, not Linux

**Comment by pietroalbini** [comment]
Moved the issue.

**Comment by jyn514** [comment]
Hmm, this should have been fixed in https://github.com/rust-lang/rust/pull/84289 - what version of rust are you installing? That fix landed in 1.53.

**Comment by ChristianWilkie** [comment]
@jyn514 oh jeez, you're absolutely right. I thought I had the latest but I grabbed 1.50 by mistake. Retried with 1.53 and it's golden. Thank you :)

**Comment by rafrafek** [comment]
Download is super slow, compare `rustc` 40.7 MiB/s with `rust-docs` 59.2 **KiB**/s:

![obraz](https://user-images.githubusercontent.com/23004737/169270850-2a018cc1-b81f-4db6-9391-c48f91f489a9.png)

**Comment by rafrafek** [comment]
Still super slow for 1.61.0

![obraz](https://user-images.githubusercontent.com/23004737/169484429-99edfa46-c11b-4667-a745-f129cdf29dc0.png)

**Comment by kinnison** [comment]
@rafrafek you are comparing download speed vs. install speed.  rust-docs is a very IO operation heavy component because it contains tens of thousands of small files. If you happen to have a virus scanner which is getting in the way of the unpacker then this can cause the slowdown you are experiencing.

**Comment by rafrafek** [comment]
@kinnison not sure, it says installing, looks like downloading

**Comment by kinnison** [comment]
@rafrafek we use the same progress-bar code for both codepaths.  Believe me, that's *installing*.

**Comment by rafrafek** [comment]
@kinnison ok, understandable, thanks!

**Comment by kinnison** [comment]
@rafrafek Your best bet is to see if you have a virus scanner, and if so to tell it to either ignore the rust toolchain directory, or at least to set it to scan-on-first-use rather than scan-on-create.
