### ISSUE TITLE
ICE: thread 'rustc' panicked at 'slice index starts at 10701 but ends at 2510', src\librustc_query_system\dep_graph\serialized.rs:43:10

### ISSUE THREAD

**Issue by zhou-mfk** [rust-lang/rust#87159]
I first use Rust to learn sort ......

I found ...

### Code

```Rust
<code>
```

### Meta

`rustc --version --verbose`:
```
rustc 1.47.0 (18bf6b4f0 2020-10-07) running on x86_64-pc-windows-msvc
```

### Error output

```
PS D:\workspace\rust_workspace\project\sort_middleware_lib> cargo run
   Compiling random_data_lib v0.1.0 (D:\workspace\rust_workspace\project\random_data_lib)
   Compiling sort_middleware_lib v0.1.0 (D:\workspace\rust_workspace\project\sort_middleware_lib)
thread 'rustc' panicked at 'slice index starts at 10701 but ends at 2510', /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39\src\librustc_query_system\dep_graph\serialized.rs:43:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.47.0 (18bf6b4f0 2020-10-07) running on x86_64-pc-windows-msvc
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by Aaron1011** [comment]
@zhou-mfk You're using an old version of Rust - do you still get this error on the latest version?

**Comment by zhou-mfk** [comment]
Thanks reply.

I use command  rustup update  but no found latest version in windows system. 

---

In Linux system no found this bug.
`[root@zls-185 ~]# rustup -V
rustup 1.24.3 (ce5817a94 2021-05-31)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.47.0 (18bf6b4f0 2020-10-07)
`

**Comment by jyn514** [comment]
I'm going to close this since it sounds like you're no longer running into the issue. Feel free to reopen if you're still having trouble.
