### ISSUE TITLE
rustdoc: Regression in width of stability (etc.) banners

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#87202]
I'm not sure if this change is intentional or not, but I thought it's worth reporting in case it's a bug.

### [nightly](https://doc.rust-lang.org/nightly/core/arch/x86_64/fn._mm256_mask_extracti32x4_epi32.html) (incorrect)

![image](https://user-images.githubusercontent.com/37223377/125996784-93e94c8f-ed56-46bf-b2fe-54dea785a800.png)

### [beta](https://doc.rust-lang.org/beta/core/arch/x86_64/fn._mm256_mask_extracti32x4_epi32.html) (correct)

![image](https://user-images.githubusercontent.com/37223377/125996842-e2153fa7-1071-4fa8-8318-2fd73ee223e1.png)

**Comment by camelid** [comment]
cc @rust-lang/rustdoc

**Comment by Manishearth** [comment]
I don't think so!

**Comment by GuillaumeGomez** [comment]
We found it out with @dns2utf8 and we weren't sure whether it was good or not (from a "look" point of view) and simply decided to wait and see if people liked it or not. So, should we revert it or not? :)

**Comment by moxian** [comment]
As a random person on the internet, I prefer the old look better. Although I admit that's at least partially due to familiarity with it.

**Comment by apiraino** [comment]
Assigning priority as discussed in the [Zulip thread](https://zulip-archive.rust-lang.org/245100tcompilerwgprioritizationalerts/3151587202rustdocRegressioninwidthofstabilityetcban.html) of the Prioritization Working Group.

@rustbot label -I-prioritize +P-medium

**Comment by Manishearth** [comment]
@GuillaumeGomez I would revert it

**Comment by GuillaumeGomez** [comment]
I'll change the look then.

**Comment by inquisitivecrystal** [comment]
I think I like the new look better, but it's a slight preference and I seem to be outvoted. :)

**Comment by jyn514** [comment]
I don't think we should be changing the UI by accident. I'm open to a discussion in changing it, but it shouldn't have changed without a discussion, so we should change it back in the meantime.

**Comment by GuillaumeGomez** [comment]
Agreed. I'll send a fix in the next two days.
