### ISSUE TITLE
Option and Result are missing documentation on their internal order

### ISSUE THREAD

**Issue by orlp** [rust-lang/rust#87238]
`Option<T>` where `T: Ord` implements `Ord` (and similarly for `PartialOrd`), but as far as I can see the order it uses isn't documented anywhere. You have to read the source to find out that its `Ord` implementation is `derive`d, and that `None` comes before `Some` in the `enum` declaration thus `None` sorts before `Some`. I think that should be documented.

The same issue also appears to apply to `Result`.

**Comment by jesyspa** [comment]
Looking into this: the instances in those cases are derived, and it looks like adding extra documentation to derived traits has been proposed previously (#44118) but is not currently supported.  So by the looks of it this is not feasible without changes to rustdoc?

**Comment by orlp** [comment]
> Looking into this: the instances in those cases are derived, and it looks like adding extra documentation to derived traits has been proposed previously (#44118) but is not currently supported. So by the looks of it this is not feasible without changes to rustdoc?

You could replace the derived implementation with an equivalent explicit one, and then add a comment.

**Comment by jesyspa** [comment]
@rustbot release-assignment

Sorry, I don't really feel qualified to judge whether the added code complexity would be worth it, so I'll leave this to someone with more experience.

**Comment by pierwill** [comment]
Looks like this issue was addressed in https://github.com/rust-lang/rust/issues/87238.

**Comment by pierwill** [comment]
Looks like this issue was addressed in https://github.com/rust-lang/rust/pull/87654.
