### ISSUE TITLE
rustdoc no longer honours --default-theme

### ISSUE THREAD

**Issue by ijackson** [rust-lang/rust#87263]
### Steps to reproduce

```
git clone https://salsa.debian.org/iwj/rust-vecdeque-stableix # any crate will do
cd rust-vecdeque-stableix
RUSTDOCFLAGS='--default-theme ayu' cargo doc
dir=$PWD
rm -rf d
mkdir d
cd d
HOME=$PWD firefox file://$dir/target/doc/vecdeque_stableix/index.html
```

### Expected results

The documentation appears in the "ayu" (dark) theme.

### Observed results

The documentation appears in the default (light) theme.

### Notes

This works on stable.  I haven't bisected it or anything.

Empirically, changing the default theme once works for any one browser profile with the default firefox settings.  AIUI the setting is intended to be recorded in web local storage.  However, my firefox configuration does not permit use of web storage or cookies, so it does not work.  This is one of the reasons for the `--default-theme` option's existence.

FTR I see this message in my JS console which seems to support this hypothesis: `Request to access cookie or storage on “file:///home/rustcargo/Rustup/Game/vecdeque-stableix/target/doc/vecdeque_stableix/struct.IntoIter.html” was blocked because we are blocking all storage access requests.`

### Meta

```
rustdoc 1.55.0-nightly (2f391da2e 2021-07-14)
binary: rustdoc
commit-hash: 2f391da2e6ac73faa3570b79de239fd8c0edf1a9
commit-date: 2021-07-14
host: x86_64-unknown-linux-gnu
release: 1.55.0-nightly
LLVM version: 12.0.1
```

**Comment by ijackson** [comment]
FTR, a faster test is available if you hae a browser which blocks cookies and web storage: then you can just reload the page, as it always shows whatever the docs' built-in default is.

**Comment by jyn514** [comment]
@ijackson does this also happen on beta?

**Comment by ijackson** [comment]
Beta is fine.

**Comment by ijackson** [comment]
The first bad nightly is `406d4a9cc 2021-06-21`; the last good nightly is `e82b65026 2021-06-20` (in each case from `rustup ... <the following date>`.

`git-log` suggests #86157 may be implicated.  The diffs do seem to suggest that it would be easy to make a mistake there.  Weirdly, https://github.com/rust-lang/rust/pulls/86157 is 404 even though bors says in 9d93819fa7ae40376ac1f563a858d2ba5f3b0277 "Auto merge of #86157"

**Comment by ijackson** [comment]
(FTR, @jyn514, I am 100% in favour of using Tera instead of all those `write!` calls.)

**Comment by ijackson** [comment]
I have found the problem: the generated HTML now says:

```
<script id="default-settings" 
        data-theme="ayu"
        data-use-system-theme="false"></script>
```
instead of
```
<script id="default-settings" data-theme="ayu" data-use_system_theme="false"></script>
```
The formatting is of no consequence, but the changes of `_` to `-` are causing the breakage.  (I eyeballed this yesterday but didn't spot this difference, seeing only what I expected...)

I suspect that this may be the result of Tera's autoescaping function.  Things are subtle here (primarily because of the crazy way the names of `data-` attributes are translated into the DOM) and the Tera defaults are probably not appropriate.

I will look at the code and send an MR.

**Comment by apiraino** [comment]
Assigning priority as discussed in the [Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2387263.20rustdoc.20no.20longer.20honours.20--default-theme) of the Prioritization Working Group.

@rustbot label -I-prioritize +P-medium
