### ISSUE TITLE
impl traits in consts through const fns are allowed but shouldn't

### ISSUE THREAD

**Issue by spastorino** [rust-lang/rust#87277]
The following code compiles after #87141 but shouldn't

```rust
#![feature(const_impl_trait)]
#![feature(min_type_alias_impl_trait)]

type Foo = impl Send;

struct A;

const VALUE: Foo = value();

 const fn value() -> Foo {
     A
 }

fn main() {
}
```

**Comment by tyranron** [comment]
@spastorino would you be so kind to explain why this should be forbidden? Seems like a nice feature to have, keeping in mind that there is a lot of anonymous types usages in Rust code.

**Comment by spastorino** [comment]
Ohh sorry for the lack of explanation, to be clear, this should be supported at some point. We were in the middle of removing impl traits in bindings for min_taits and the example in this issue is part of that combo that we were removing. In that sense is that it shouldn't work, because we were removing it's support. At some point when let bindings are reintroduced this example should work :). Sorry for the lack of context provided.

@oli-obk maybe you want to add a bit more info here.

**Comment by oli-obk** [comment]
We are trying to avoid any and all mentions of traits other than `Sized` from const fn until we have a proper story here. you can't use the result of an impl trait returning const fn within another const fn anyway, so the usefulness is limited.

**Comment by oli-obk** [comment]
We have stabilized `-> impl Trait` on const fn, so there is no reason to forbid TAITs.

Closing as there is no further action required here
