### ISSUE TITLE
Warn about strings that skip multiple newlines with one backslash

### ISSUE THREAD

**Issue by joshtriplett** [rust-lang/rust#87319]
(This came up in today's @rust-lang/lang meeting.)

Given the following code:

```rust
fn main() {
    let s1 = "a\

b";
    let s2 = "a\

    b";
    println!("{:?} {:/}", s1, s2);
}
```

[Playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a783aa21f2ec4064d0ae0cab0f4c8777)

The compiler interprets both of the string literals as `"ab"`, omitting multiple newlines after the `\`.

This seems confusing, and different from the behavior of other languages. For instance, C and Python both produce parse errors for such string literals. Or, for a Python multi-line string literal, the backslash escapes the immediately following newline but not the subsequent newline.

Rust does allow unescaped newlines in string literals, which is *useful*. The ability to escape a newline can also be useful sometimes. But the combination of both escaped and unescaped newlines seems sufficiently confusing and surprising to merit a warning.

We'd ideally like to work towards this being an error. Depending on the presence of existing usage in the ecosystem, that might or might not require an edition.

**Comment by pierwill** [comment]
Discussed in [Zulip](https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp/topic/issue.2087319):

> The escape sequence handling for string literals is handled here: https://github.com/rust-lang/rust/blob/1158367a6d60d3e2a8c68d6212a8007992b1dbf0/compiler/rustc_lexer/src/unescape.rs#L267
> 
> It looks like the issue lies in https://github.com/rust-lang/rust/blob/1158367a6d60d3e2a8c68d6212a8007992b1dbf0/compiler/rustc_lexer/src/unescape.rs#L300 - we consider \n to be 'ascii whitespace' and will therefore skip over it after we encounter an escaped newline
