### ISSUE TITLE
`cargo-clippy` should not fail early on lints that default to `deny`

### ISSUE THREAD

**Issue by sxlijin** [rust-lang/rust#87334]
Latest stable `cargo check` and `cargo build` (`1.53.0`) both succeed on https://github.com/BurntSushi/ripgrep/commit/0ff5dd23606ee1e006a38ac7d18afcc4c368d9a4, but `cargo clippy` fails on a lint that defaults to deny.

My expectation with a linter is that, on a well-formed AST (i.e. one that successfully can be compiled), it should show me _all_ the lint errors in the code being linted so that I can triage/address them at my/our own discretion. Currently `clippy` bails out fast.

Although it _is_ possible to downgrade `deny` lints to `warn`, I don't think this is very desirable, since it causes the user to lose information about the severity of the lint issue. 

It was pointed out to me in the Zulip (thanks @jyn514 !) that there are a few levels of issues here:

* this can't be done in just clippy and needs rustc work for this to happen when compiling a single crate
* for inter-crate compilation, rustc would need to start distinguishing lint-only errors in output

**Comment by jyn514** [comment]
> for inter-crate compilation, rustc would need to start distinguishing lint-only errors in output

To clarify: it would be fine for this to be rustc-only at first, but it doesn't solve the full issue if there's a path dependency, because rustc would print all lints for the first crate, error out, and then cargo would see the error and stop before compiling the next crate in the workspace.

**Comment by SNCPlay42** [comment]
See also #82761

**Comment by jyn514** [comment]
Closing in favor of https://github.com/rust-lang/rust/issues/82761.
