### ISSUE TITLE
Spurious reference binding from edition lint

### ISSUE THREAD

**Issue by djc** [rust-lang/rust#87355]
I ran `cargo +nightly fix --edition` against https://github.com/quinn-rs/quinn/commit/a21f010baddde857f4536b75afd456364e7b74fb.

I expected to see this happen: no changes or necessary edition-related changes.

Instead, this happened: cargo fix produced this change:

```diff
djc-2019 main quinn $ git diff
diff --git a/quinn/examples/client.rs b/quinn/examples/client.rs
index f310b461..033b1c1e 100644
--- a/quinn/examples/client.rs
+++ b/quinn/examples/client.rs
@@ -60,7 +60,7 @@ fn main() {
 }
 
 #[tokio::main]
-async fn run(options: Opt) -> Result<()> {
+async fn run(options: Opt) -> Result<()> { let _ = &options; 
     let url = options.url;
     let remote = (url.host_str().unwrap(), url.port().unwrap_or(4433))
         .to_socket_addrs()?
```

(The formatting is surprising, but that's not what this issue is about.)

`cargo +nightly c` with `cargo-features = ["edition2021"]` seems to work with or without the change, so it seems like this change is not actually needed. Is there some odd interaction with `tokio::main`?

### Meta

rustc 1.55.0-nightly (b41936b92 2021-07-20)
binary: rustc
commit-hash: b41936b92cd8463020207cb2f62a4247942ef2e4
commit-date: 2021-07-20
host: x86_64-apple-darwin
release: 1.55.0-nightly
LLVM version: 12.0.1

**Comment by fbernier** [comment]
@djc I too was confused about that change but I just found out [this explanation](https://blog.rust-lang.org/2021/05/11/edition-2021.html#disjoint-capture-in-closures).

Basically, without it it could change the order in which fields are dropped.

**Comment by djc** [comment]
@triagebot modify labels to +A-edition-2021

**Comment by m-ou-se** [comment]
cc @rust-lang/wg-rfc-2229

**Comment by arora-aman** [comment]
This is the expected lint for RFC 2229.

The `&options` introduces an immutable read within the closure, forcing `options` to be read completely without changing the closure trait(Fn/FnMut/FnOnce).

**Comment by m-ou-se** [comment]
> (The formatting is surprising, but that's not what this issue is about.)

Filed an issue for that: https://github.com/rust-lang/rust/issues/87952

**Comment by m-ou-se** [comment]
> This is the expected lint for RFC 2229.

Closing this issue then.
