### ISSUE TITLE
How can I build a 100% static binary in risc-v arch

### ISSUE THREAD

**Issue by fengerhu1** [rust-lang/rust#87367]
I found in a rust-doc[1] that musl-libc can support for the fully static library. However, I can not build static binary with the standard library using musl libc in risc-v, as `riscv64gc-unknown-linux-musl` is not supported for `std`.

So how can I build a fully static binary including `std` in risc-v, or is there any plan to support musl-libc in risc-v?

Maybe there are some incompatible codes between rust-std and musl-libc, can I ignore these parts? As I only need some fundamental functions provided in the std (io, etc.). 

[1]: https://doc.rust-lang.org/edition-guide/rust-2018/platform-and-target-support/musl-support-for-fully-static-binaries.html

**Comment by asquared31415** [comment]
The [targets list](https://doc.rust-lang.org/nightly/rustc/platform-support.html#tier-3) has no information about whether `std` exists for `riscv64gc-unknown-linux-musl`.  It's a tier 3 target as well, which while the compiler may work, is the least priority target and many such targets only have a small subset of the standard library, if any.

Based on your observations I would assume that `std` just isn't available for this target.  Unless someone implements it, you're out of luck.  That target might support some other standard crates though, like `alloc`, but `io` is in `std`, and you won't be able to use it without a `std` implementaion.

**Comment by jyn514** [comment]
In general the way to get std for tier 3 targets is to build your own compiler with x.py, or use `-Zbuild-std`.

The issue tracker is not a support forum. For future questions please ask in one of these places:

https://discord.gg/rust-lang/
https://discord.gg/rust-lang-community/
https://users.rust-lang.org/
https://rust-lang.zulipchat.com/
