### ISSUE TITLE
cargo fix --edition fails with error "Unrecognized option: 'force-warns'"

### ISSUE THREAD

**Issue by Tiwalun** [rust-lang/rust#87360]
I tried the migration process to the 2021 edition, according to the instructions in <https://blog.rust-lang.org/2021/07/21/Rust-2021-public-testing.html>.

I expected to see this happen:  `cargo +nightly fix --edition` works without an error.

Instead, this happened:  `cargo +nightly fix --edition` fails with the following error message:

```
    Checking xtask v0.1.0 (C:\DIST\dev\tools\probe-rs\xtask)
   Migrating xtask\src\main.rs from 2018 edition to 2021
error: Unrecognized option: 'force-warns'

error: could not compile `xtask`
warning: build failed, waiting for other jobs to finish...
error: Unrecognized option: 'force-warns'

error: build failed
```

I tried this with the following repository: <https://github.com/probe-rs/probe-rs>

### Meta

`rustc +nightly --version --verbose`:
```
rustc 1.55.0-nightly (32c9b7b09 2021-07-21)
binary: rustc
commit-hash: 32c9b7b091534f6d80e7e85da0cd425acb6c9a79
commit-date: 2021-07-21
host: x86_64-pc-windows-msvc
release: 1.55.0-nightly
LLVM version: 12.0.1
```
`cargo +nightly --version --verbose`:
```
1.55.0-nightly (4e143fd13 2021-07-20)
release: 1.55.0
commit-hash: 4e143fd131e0c16cefd008456e974236ca54e62e
commit-date: 2021-07-20
```

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by inquisitivecrystal** [comment]
Thank you for the report! This should be fixed pretty soon, hopefully. It's a temporary thing while we're renaming the option. CC @rylev

**Comment by inquisitivecrystal** [comment]
rust-lang/cargo#9714 got in just before I submitted mine. It should take care of this.
