### ISSUE TITLE
A question about rustc_passes/src/liveness.rs

### ISSUE THREAD

**Issue by thomasyonug** [rust-lang/rust#87361]
A bunch of design doc comments in the file head describes how the RUSTC dataflow works. 

I notice that the comment is all about AST but the actual code is work on HIR. I was wondering that it's a cleanup bug or something else?

https://github.com/rust-lang/rust/blob/8024983ea73e1d1c16720a424d39fd1c239eee68/compiler/rustc_passes/src/liveness.rs#L1

https://github.com/rust-lang/rust/blob/8024983ea73e1d1c16720a424d39fd1c239eee68/compiler/rustc_passes/src/liveness.rs#L13

Actually the visitor is from hir

https://github.com/rust-lang/rust/blob/8024983ea73e1d1c16720a424d39fd1c239eee68/compiler/rustc_passes/src/liveness.rs#L93

**Comment by fee1-dead** [comment]
the HIR is AST. there are also code like this: `use rustc_hir as ast;`. You can read about it here:

https://rustc-dev-guide.rust-lang.org/hir.html

**Comment by thomasyonug** [comment]
Gotcha, thanks.
