### ISSUE TITLE
Add support for `// only-cfg-target-has-atomic` to compiletest

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#87377]
Right now, you have to specify the platforms and architectures you want by hand, which makes it easy to leave them out or include platforms you shouldn't. It would be nice to automate this - maybe with `rustc  --print cfg`?

See also https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp/topic/How.20can.20I.20ignore.20tests.20on.20platforms.20without.20atomics.3F.

_Originally posted by @wesleywiser in https://github.com/rust-lang/rust/pull/84039#discussion_r675000124_

**Comment by RalfJung** [comment]
Can't you use `#[cfg(target_has_atomic)]` in the test to basically stub it out?

**Comment by jyn514** [comment]
@RalfJung no, because that will cause the test to fail (because it's missing the error annotations).

**Comment by RalfJung** [comment]
Ah, good point -- thanks!

**Comment by jieyouxu** [comment]
compiletest triage: this should probably use the `needs-*` machinery for capability requirements, i.e. `//@ needs-atomic` or a better name.

**Comment by kei519** [comment]
I want to try this as my first contribution. Is it ok?

@rustbot claim

**Comment by jieyouxu** [comment]
Apparently this is a bit more tricky than I expected initially.
@rustbot label -E-easy +E-medium

**Comment by jieyouxu** [comment]
Implemented in #133736.
