### ISSUE TITLE
\xHH escaping suggestions are wrong for characters that are too big 

### ISSUE THREAD

**Issue by SkiFire13** [rust-lang/rust#87397]
Consider this code:

```rust
fn main() {
    b'字';
    b"字";
}
```

[playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=72ec9cac9d7d0323e443bb972364021f)

The current output is:

```
error: non-ASCII character in byte constant
 --> src/main.rs:2:7
  |
2 |     b'字';
  |       ^^
  |       |
  |       byte constant must be ASCII
  |       help: use a \xHH escape for a non-ASCII byte: `\x5B57`

error: non-ASCII character in byte constant
 --> src/main.rs:3:7
  |
3 |     b"字";
  |       ^^
  |       |
  |       byte constant must be ASCII
  |       help: use a \xHH escape for a non-ASCII byte: `\x5B57`

error: could not compile `playground` due to 2 previous errors
```

The suggestions are incorrect: `\x5B57` is not a valid escaped character, only the `\x5B` part is interpreted as an escaped character while the `57` part is interpreted as two normal characters. 

In the case of byte characters the suggestion leads to a byte character literal with more than one character, thus in another compile error. However in the case of byte strings this will silently compile, even though that probably wasn't what the user wanted nor expected.

This happens in both the current stable and nightly compilers.

**Comment by nagisa** [comment]
For the string variant we can still suggest using a sequence of escapes representing the unicode encoding: `\xE5\xAD\x97` in this case.

The behaviour is also pretty poor for unicode code points that _do_ fit inside a byte:

```
error: non-ASCII character in byte constant
 --> src/main.rs:2:15
  |
2 |     let x = b"µ";
  |               ^
  |               |
  |               byte constant must be ASCII
  |               help: use a \xHH escape for a non-ASCII byte: `\xB5`
```

but `\xB5` is not a valid UTF-8 character, so the behaviour is likely to be incorrect.

**Comment by 5225225** [comment]
You probably don't want to assume UTF-8 here. (If the string *was* pure UTF-8, why are they using a byte string?). Or at least make mention of the suggestion being only correct *if* you want the UTF-8 encoding.

You'd also drop the applicability of the suggestion to MaybeIncorrect, because it's impossible to tell what they actually wanted.

**Comment by hkratz** [comment]
> For the string variant we can still suggest using a sequence of escapes representing the unicode encoding: `\xE5\xAD\x97` in this case.
> 
> The behaviour is also pretty poor for unicode code points that _do_ fit inside a byte:
> 
> ```
> error: non-ASCII character in byte constant
>  --> src/main.rs:2:15
>   |
> 2 |     let x = b"µ";
>   |               ^
>   |               |
>   |               byte constant must be ASCII
>   |               help: use a \xHH escape for a non-ASCII byte: `\xB5`
> ```
> 
> but `\xB5` is not a valid UTF-8 character, so the behaviour is likely to be incorrect.

Actually, µ is U+039C and two bytes in UTF-8: `b"\xC2\xB5"`. µ is `b'\xB5'` in ISO 8859-1. It seems the compiler does way too much magic here.

**Comment by FabianWolff** [comment]
Yes, I guess it makes sense to suggest `b"\xE5\xAD\x97"` (i.e., the UTF-8 encoding) if the user wrote `b"字"`, with `Applicability::MaybeIncorrect` and some text that questions whether this really is what was intended.

@rustbot claim
