### ISSUE TITLE
Using str::contains inside of a filter leads to confusing error message.

### ISSUE THREAD

**Issue by ethercrow** [rust-lang/rust#87437]
I've been trying to learn some Rust by doing CodeWars. I've spent some time being stuck on this diagnostic. One of the easiest exercises there is to count vowels in a string. First I did it with a loop, but then got stuck trying to rewrite is as a filter.

Given the following code: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=785ded94c58b6d9a3a8acd16145a4970

```rust
fn get_vowel_count(string: &str) -> usize {
        string
        .chars()
        .filter(|c| "aeiou".contains(c))
        .count()
}
```

The current output is:

```
error[E0277]: expected a `Fn<(char,)>` closure, found `char`
 --> src/lib.rs:4:38
  |
4 |         .filter(|c| "aeiou".contains(c))
  |                                      ^ expected an `Fn<(char,)>` closure, found `char`
  |
  = help: the trait `Fn<(char,)>` is not implemented for `char`
  = note: required because of the requirements on the impl of `FnOnce<(char,)>` for `&char`
  = note: required because of the requirements on the impl of `Pattern<'_>` for `&char`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: could not compile `challenge`
```

Ideally the output should not lead with "expected an Fn" and also help me to add a missing ampersand.

**Comment by osa1** [comment]
> and also help me to add a missing ampersand.

Do you mean a missing star? Working version:

```rust
fn get_vowel_count(string: &str) -> usize {
        string
        .chars()
        .filter(|c| "aeiou".contains(*c))
        .count()
}
```

I agree that the error message is very misleading.

Smaller repro:

```rust
fn test(c: &char) -> bool {
    "aeiou".contains(c)
}
```

**Comment by ethercrow** [comment]
> Do you mean a missing star?

Both `|c| "aeiou".contains(*c)` and `|&c| "aeiou".contains(c)` are accepted.

**Comment by edmorley** [comment]
This misleading diagnostic also caught me out too recently.

I also found #90970 which seems related.

**Comment by estebank** [comment]
Addressing in #91873

<img width="750" alt="Screen Shot 2022-03-26 at 3 38 34 PM" src="https://user-images.githubusercontent.com/1606434/160259280-f3374ee6-b9af-409a-9827-9dc94d00f803.png">
