### ISSUE TITLE
future-incompat: use of SIMD types aren't gated properly

### ISSUE THREAD

**Issue by JohnTitor** [rust-lang/rust#87438]
(Splitting from https://github.com/rust-lang/rust/pull/59238/files/8477a04a72a6f8e0adb46be91a2628b07648c200#r266976217)

Consider the following ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=2fed52804dbbf36619639bbcffc544c9)):
```rust
use std::arch::x86_64::__m128;

#[allow(improper_ctypes)]
extern "C" {
    fn e(x: __m128);
}
```

which produces the following error (correctly):

```
error: use of SIMD type `__m128` in FFI is highly experimental and may result in invalid code
 --> src/lib.rs:5:13
  |
5 |     fn e(x: __m128);
  |             ^^^^^^
  |
  = help: add `#![feature(simd_ffi)]` to the crate attributes to enable
```

But when we use it on struct ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=e8adbf67bf4c899b75580c356fe56182)):

```rust
#[repr(transparent)] pub struct A(__m128);
#[repr(C)] pub struct B(__m128);
```

it just compiles fine on stable Rust, while we should gate it. We should eventually disallow it through a future incompat lint.

**Comment by RalfJung** [comment]
With https://github.com/rust-lang/rust/issues/116558, actually *calling* that imported function without having the required target features will cause a future-compat lint (eventually error). I'd say that closes this issue.
