### ISSUE TITLE
The 2021 panic macro no longer works in `const` functions

### ISSUE THREAD

**Issue by AaronKutch** [rust-lang/rust#87466]
I encountered one issue when trying to migrate my crates to edition 2021. This no longer compiles:
```
#![feature(const_panic)]

pub const fn f() {
    panic!("important info");
}
```

I understand that this requires a nightly feature to observe, but `const_panic` was really close to stabilizing and I use this in a lot of places. Is it possible to adjust the underlying `format_args` to be `const` with a static string input, or is there something else I should use? I don't want to go back to using the weird out-of-bounds indexing hack when trying to convey messages from a `const` function.

**Comment by inquisitivecrystal** [comment]
This is a [known problem](https://github.com/rust-lang/rust/issues/85194#issuecomment-852345377), unfortunately. It appears to be a result of the changes made to the panic macro to standardize its behavior.

**Comment by fee1-dead** [comment]
See #86998
