### ISSUE TITLE
PartialOrd documentation mixes functions and operators

### ISSUE THREAD

**Issue by ChrisJefferson** [rust-lang/rust#87485]
The documentation for PartialOrd: https://doc.rust-lang.org/core/cmp/trait.PartialOrd.html

Tells me to implement functions `partial_ord`, and (possibly) `lt`, `le`, `gt`, `ge`. The documentation immediately starts talking about the Rust `<` and `>` operators, without ever saying how those operators relate to the functions in the trait. There also aren't any requirements put on `le` and `ge` (I'm not sure of the most compact and efficient way of listing the requirements on these operators. Is just saying "`a <= b` is true if and only if `a<b` or `a==b` is true" sufficient?).

**Comment by the8472** [comment]
That context is provided on the module level. https://doc.rust-lang.org/core/cmp/index.html

**Comment by memoryruins** [comment]
Beta and [nightly's docs](https://doc.rust-lang.org/nightly/std/cmp/trait.PartialOrd.html) are much clearer about both parts after #85637

**Comment by ChrisJefferson** [comment]
That solves all my problems. Thanks @RalfJung !
