### ISSUE TITLE
Add lint against ptr-to-int transmutes in consts

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#87525]
We do not allow ptr-to-int casts in `const` context, so people might be tempted to do a transmute instead. This will not work, and if they ever actually test their code during CTFE they will get an error, but it might still be good to add an extra layer of defense here (since this is a rather odd corner of the language) and have a lint for this.

@jhpratt started working on this, [here's a link](https://github.com/rust-lang/rust/commit/6351c670f654ead12ec64534fcc64cb32dc380c8).

**Comment by RalfJung** [comment]
Cc @rust-lang/wg-const-eval 

@jhpratt do you want to work on this, or leave this issue open for anyone to pick up?

**Comment by jhpratt** [comment]
Someone else can pick this up, as I've got other priorities for the near future. As I mentioned feel free to use the code linked.

It's worth noting that a lint would ideally also catch transmutes that use a union, though that would be quite a bit more difficult I imagine.

**Comment by RalfJung** [comment]
> It's worth noting that a lint would ideally also catch transmutes that use a union, though that would be quite a bit more difficult I imagine.

That'll require a *lot* of complexity, for a case that I assume will be exceedingly rare. So I don't think that is effort, lines of code, and compile time well spent.

**Comment by jhpratt** [comment]
Agreed. Just throwing it out there.

**Comment by oli-obk** [comment]
More context on the lint can be found in the discussion starting at https://github.com/rust-lang/rust/pull/85769#issuecomment-879427756
