### ISSUE TITLE
rust build error on ipad pro 2021 which used in iash app with alpinelinux

### ISSUE THREAD

**Issue by baoyachi** [rust-lang/rust#87543]
error detail:cargo build error:illegal hardware instruction

* device:ipad pro 2021 m1

build error detail

```bash
~ uname -a
Linux baoyachiiPad 4.20.69-ish iSH 1.2.2 (178) Jun 27 2021 06:12:09 i686 Linux

~ cargo build
[1]    401 illegal hardware instruction  cargo build
~ cargo --version
cargo 1.44.0

~ 
```

**Comment by hellow554** [comment]
Can you provide the crate or project you are trying to build?
Can you maybe run `cargo build` with gdb or lldb, to see where exactly the error happens?

**Comment by Urgau** [comment]
Can you also try with a much recent version of the rust toolchain (rustc, cargo, ...), 1.44.0 is from 19 Dec 2019, which is pretty old by Rust standard . The latest stable version is the 1.53.0.

**Comment by Fishrock123** [comment]
How did you install rust onto this? Rustup doesn't seem to provide an easy way to install `i686-unknown-linux-musl`.

Also I believe the author of this is using this: https://ish.app/

> iSH is a project to get a Linux shell environment running locally on your iOS device, using a usermode x86 emulator. 

Which, seems to work? But I don't know how to easily get the correct toolchain either (I also have an M1 iPad to test this with).

**Comment by Fishrock123** [comment]
Repo for that project: https://github.com/ish-app/ish

**Comment by Fishrock123** [comment]
Related issue by the OP on that project: https://github.com/ish-app/ish/issues/1507

**Comment by baoyachi** [comment]
Yeah, I just install app which name [https://ish.app/](https://ish.app/) on my ipad pro 2021 M1.

Also you can exec cmd below:
```bash
~ apk upgrade && apk update
...
~ apk add rust
...
~ cargo build
[1]    401 illegal hardware instruction  cargo build
~ cargo --version
cargo 1.44.0
```
