### ISSUE TITLE
Tracking Issue for proc_macro::Span::{start, end}

### ISSUE THREAD

**Issue by m-ou-se** [rust-lang/rust#87552]
Feature gate: `#![feature(proc_macro_span_shrink)]`

This feature adds `span.start()` and `span.end()` which give empty spans right at the start and end of the span. (Just like `shrink_to_lo()` and `shrink_to_hi()` inside rustc.)

### Public API

```rust
// proc_macro

impl Span {
     pub fn start(&self) -> Span;
     pub fn end(&self) -> Span;
}
```

### Steps / History

- [x] Implementation: #86165
- [x] Rename to `start` and `end`: https://github.com/rust-lang/rust/pull/111571
- [ ] Merge tracking with https://github.com/rust-lang/rust/issues/54725

### Unresolved Questions

- None yet.

**Comment by dtolnay** [comment]
As of https://github.com/rust-lang/rust/pull/111571, these methods are now tracked by https://github.com/rust-lang/rust/issues/54725.
