### ISSUE TITLE
{f32,f64,float}::tests::test_frexp unit tests in libstd fail on Windows

### ISSUE THREAD

**Issue by vadimcn** [rust-lang/rust#8755]
SImilarly to #8663, looks like mingw32 implementation of frexp() violates the spec when dealing with +/-infinity.

**Comment by steveklabnik** [comment]
@retep998 do you know if this is still an issue? I'm not aware of tests failing.

**Comment by retep998** [comment]
I have no idea. I'm not an expert on the precise behavior of the math functions.

**Comment by steveklabnik** [comment]
I guess I meant if you had seen test failures, not the details of them failing.

**Comment by steveklabnik** [comment]
Given that there's been no substantial comments here in years, I'm going to consider this one stale; please let me know if this is somehow reproducible today.
