### ISSUE TITLE
Parsing f32 works incorrectly

### ISSUE THREAD

**Issue by Speretta** [rust-lang/rust#87572]
I was trying to convert String to f32. I accidentally noticed that there is such an error. It parses and sums some numbers incorrectly.

I tried this code:

```rust
fn main() {
    match "99999999".parse::<f32>() {
        Ok(number) => {
            println!("number: {:?}", number);
            println!("number + 5: {:?}", number + 5.0)
        }
        Err(_) => {}
    }
}
```

I expected to see this happen:
```
number: 99999999.0
number + 5: 100000004.0
```

Instead, this happened: 
```
number: 100000000.0
number + 5: 100000010.0
```
If I try in f64 it works fine. I guess the problem is f32 has no integer field for numbers of this size.

### Meta

`rustc --version --verbose`:
```
rustc 1.53.0 (53cb7b09b 2021-06-17)
binary: rustc
commit-hash: 53cb7b09b00cbea8754ffb78e7e3cb521cb8af4b
commit-date: 2021-06-17
host: x86_64-pc-windows-msvc
release: 1.53.0
LLVM version: 12.0.1
```

</p>
</details>

**Comment by jonas-schievink** [comment]
This is working correctly. `f32` does not have enough precision to represent 100000004.0

**Comment by cuviper** [comment]
This is the nature of floating point -- `f32` only has 24 bits for the mantissa, so if you try values greater than 2<sup>24</sup> = 16,777,216, you'll lose precision in the least-significant bits. Whereas `f64` has 53 bits for the mantissa, so it's accurate up to 2<sup>53</sup> = 9,007,199,254,740,992.

Furthermore, in Rust the display of floating point numbers is approximated to just the significant figures that are sufficient to parse back to the same raw value. If you print `(number + 5.0) as u32` instead, you'll get 100000008, which might be more clear how the lower bits were rounded. You can also use the `to_bits()` method to inspect the raw floating point representation.

**Comment by Speretta** [comment]
Forgive my ignorance, I thought it was for similar reasons but I wasn't sure. I'm sorry for interrupting your work. Thanks for your early reply.
