### ISSUE TITLE
generics-related ICE: 'called `Option::unwrap()` on a `None` value'

### ISSUE THREAD

**Issue by 0bl-user** [rust-lang/rust#87603]
having a struct field depending on an a const expression (field: [T; N * 2]) using const_evaluatable_checked and a corresponding where [T; N * 2]: Sized. Think this was working before 1.56 nightly.. Getting called Option::unwrap() on a None value, compiler/rustc_metadata/src/rmeta/decoder.rs:914:54 when importing lib.rs, but, everything works when that same lib is in main.rs. Also any suggestions for using const_evaluatable_checked. https://users.rust-lang.org/t/1-56-nightly-change-in-const-evaluatable-checked/62865

**Comment by JohnTitor** [comment]
MCVE is here: https://users.rust-lang.org/t/1-56-nightly-change-in-const-evaluatable-checked/62865/11?u=johntitor

lib.rs:
```
#![feature(const_generics)]
#![feature(const_evaluatable_checked)]

pub struct S<T: Copy + Default, const N: usize>
where
    [T; N*2]: Sized,
{
    pub s: [T; N * 2],
}

impl<T: Default + Copy, const N: usize> S<T, N>
where
    [T; N * 2]: Sized,
{
    pub fn test() -> Self {
        S {
            s: [T::default(); N * 2],
        }
    }
}
```

main.rs:

```
const N: usize = 2;
let x: S<u8, N> = S::test();
```
