### ISSUE TITLE
Random segfaults

### ISSUE THREAD

**Issue by pranaypratyush** [rust-lang/rust#87617]
I keep getting segfaults from rustc with different reasons each time. I can't replicate them since the next run always completes successfully. 
Has been happening for about a few weeks. At first, I thought my system isn't stable but I now I don't think that's the case.
The latest error message was the following but it keeps changing. I would add more as I encounter them. 
```
error: could not compile `idna`

Caused by:
  process didn't exit successfully: `rustc --crate-name idna --edition=2018 /home/pranay/.cargo/registry/src/github.com-1ecc6299db9ec823/idna-0.2.3/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 -C metadata=a6817081c64bae8f -C extra-filename=-a6817081c64bae8f --out-dir /home/pranay/wd/warp-graphql/target/debug/deps -L dependency=/home/pranay/wd/warp-graphql/target/debug/deps --extern matches=/home/pranay/wd/warp-graphql/target/debug/deps/libmatches-9cfb84f2ef24c6e0.rmeta --extern unicode_bidi=/home/pranay/wd/warp-graphql/target/debug/deps/libunicode_bidi-afe326ebf8dbe853.rmeta --extern unicode_normalization=/home/pranay/wd/warp-graphql/target/debug/deps/libunicode_normalization-9937e5bde6b792fd.rmeta --cap-lints allow` (signal: 11, SIGSEGV: invalid memory reference)
```
### Meta

`rustc --version --verbose`:
```
rustc 1.55.0-beta.2 (3c216f01c 2021-07-29)
binary: rustc
commit-hash: 3c216f01c7be6a01cfca069eee62ef3c72d9fd3a
commit-date: 2021-07-29
host: x86_64-unknown-linux-gnu
release: 1.55.0-beta.2
LLVM version: 12.0.1

```
(Moving to latest stable version doesn't help)

**Comment by hkratz** [comment]
@pranaypratyush What distribution are you on? Best idea would probably be to enable core dumps on segfault and get a backtrace by inspecting the core via rust-gdb.

**Comment by pranaypratyush** [comment]
I am running `5.13.5-1-MANJARO` kernel on a AMD 2700x. 
The problem is that I don't exactly know when this would happen but it has always occurred midway through `cargo build`.

**Comment by hkratz** [comment]
You don't need to know when it happens, just enable core dumps with:
```
ulimit -S -c unlimited
```
and anytime rustc (or something else) segfaults it should leave a `core` file behind in the working directory of the process. Once rustc segfaults again, run:
```
rust-gdb `rustup which rustc` path_to_core_file --eval-command=bt --batch
```
and post the backtrace here.

**Comment by pranaypratyush** [comment]
Thanks. Would keep the issue updated.

**Comment by Nilstrieb** [comment]
Closing this as there haven't been any actionable updates since. If you have gotten backtraces, please reopen the issue and post them.
