### ISSUE TITLE
rustdoc: Section icon covers part of enum variant name when hovered

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#87611]
**This is a regression from 1.53.0 to 1.54.0 (released today).** It's likely that the display of other parts of the docs has regressed in a similar way as well (e.g., `struct` fields), but I haven't checked those.

More broadly, the way the variant looks when hovered has changed as well. I am unsure if that part of the change was intentional; to me it seems like a regression.

### [1.54.0](https://doc.rust-lang.org/1.54.0/std/option/enum.Option.html#variant.None) (incorrect)

![image](https://user-images.githubusercontent.com/37223377/127581498-dc25e617-4026-4b9b-9bc0-d84ea6bbae62.png)

### [1.53.0](https://doc.rust-lang.org/1.53.0/std/option/enum.Option.html#variant.None) (correct)

![image](https://user-images.githubusercontent.com/37223377/127581546-1dd31783-3a61-4f87-b564-18d288b9ce34.png)

**Comment by apiraino** [comment]
Assigning priority as discussed in the [Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2387611.20rustdoc.3A.20Section.20icon.20covers.20part.20of.20enum.20variant.20na.E2.80.A6) of the Prioritization Working Group.

@rustbot label -I-prioritize +P-medium

**Comment by GuillaumeGomez** [comment]
Fixing it.

**Comment by GuillaumeGomez** [comment]
It's actually already fixed in [nightly](https://doc.rust-lang.org/nightly/std/option/enum.Option.html) and [beta](https://doc.rust-lang.org/beta/std/option/enum.Option.html). Should we close it then?

**Comment by camelid** [comment]
> It's actually already fixed in [nightly](https://doc.rust-lang.org/nightly/std/option/enum.Option.html) and [beta](https://doc.rust-lang.org/beta/std/option/enum.Option.html). Should we close it then?

It doesn't look fixed to me in the links you posted. When I hover over the `None` variant, the section icon still covers the word `None`, and the styling of the highlight is still different from 1.53.0.

**Comment by GuillaumeGomez** [comment]
That's interesting:

![Screenshot from 2021-08-03 22-16-54](https://user-images.githubusercontent.com/3050060/128080386-849a12b6-b696-4ba3-acf0-596532af9c59.png)

I love when dark magic is involved haha. Well, I'm gonna try to see how to reproduce it.

**Comment by camelid** [comment]
The bug is present in all themes, but it looks a bit different in Ayu:

![image](https://user-images.githubusercontent.com/37223377/128080774-a97b26f6-44b5-4bc9-b860-4bb237018bfe.png)

As you can see, it looks like the section icon's background is overlapping with the text `None`.

**Comment by camelid** [comment]
Ayu seems to have also had a highlighting regression from stable to beta, perhaps separate from the one described in this issue?

#### stable

![image](https://user-images.githubusercontent.com/37223377/128080955-e0fc76e3-9db4-4a2c-8127-36bc30dc832c.png)

#### beta

![image](https://user-images.githubusercontent.com/37223377/128081078-c52b52cb-4a7e-4a98-8c78-b34f50ad15bf.png)

**Comment by GuillaumeGomez** [comment]
For for the background, it's definitely on purpose.
