### ISSUE TITLE
1.54.0 compilation fault with nightly, miri and parallel-compiler

### ISSUE THREAD

**Issue by Miezhiko** [rust-lang/rust#87623]
```rust
error[E0308]: mismatched types
  --> src/tools/miri/src/bin/miri.rs:44:30
   |
44 |                 Rc::make_mut(&mut crate_source).rlib = Some((PathBuf::new(), PathKind::All));
   |                              ^^^^^^^^^^^^^^^^^ expected struct `Rc`, found struct `Arc`
   |
   = note: expected mutable reference `&mut Rc<_>`
              found mutable reference `&mut Arc<CrateSource>`

error[E0609]: no field `rlib` on type `&mut _`
  --> src/tools/miri/src/bin/miri.rs:44:49
   |
44 |                 Rc::make_mut(&mut crate_source).rlib = Some((PathBuf::new(), PathKind::All));
   |                                                 ^^^^


```

**Comment by Urgau** [comment]
Miri is a nightly-only tool, not a stable one. You shouldn't being able to built it from a stable release.
See https://github.com/rust-lang/rust/issues/86436 for more informations.

**Comment by Miezhiko** [comment]
I use nightly flag too, I'm just using release git tag.

**Comment by Urgau** [comment]
The release source shouldn't include miri, in fact I don't see it in the release source. Where did you download it ? Have you used the [official tarballs](https://forge.rust-lang.org/infra/other-installation-methods.html#standalone) ?

Miri is also one of the few tools that are allow to not always compile, see the [Rustup Components History](https://rust-lang.github.io/rustup-components-history/). So it's perfectly possible that when the beta-cut happen miri was not compiling at the moment.

**Comment by Miezhiko** [comment]
miri can be set as additional tool in `tools` in `config.toml` before build, it needs nightly flag too (I have it), yes I use official tarballs

**Comment by hyd-dev** [comment]
> ```
>    = note: expected mutable reference `&mut Rc<_>`
>              found mutable reference `&mut Arc<CrateSource>`
> ```

That looks like a `parallel_compiler` issue rather than a toolstate issue.

**Comment by Miezhiko** [comment]
> > ```
> >    = note: expected mutable reference `&mut Rc<_>`
> >              found mutable reference `&mut Arc<CrateSource>`
> > ```
> 
> That looks like a `parallel_compiler` issue rather than a toolstate issue.

Okay, what is `parallel_compiler`? Does it related with parallel rust compilation (many jobs) or is it some crate?

**Comment by Miezhiko** [comment]
Sub-module hashtag for `1.54.0` tag is the same as for `master` at the moment https://github.com/rust-lang/rust/tree/1.54.0/src/tools

**Comment by hyd-dev** [comment]
> Okay, what is `parallel_compiler`? Does it related with parallel rust compilation (many jobs) or is it some crate?

https://github.com/rust-lang/rust/blob/1195bea5a7b73e079fa14b37ac7e375fc77d368a/config.toml.example#L457-L459

**Comment by Miezhiko** [comment]
@hyd-dev yes I have it enabled too

**Comment by Urgau** [comment]
> miri can be set as additional tool in `tools` in `config.toml` before build, it needs nightly flag too (I have it), yes I use official tarballs, I wonder if there is patch for it already, maybe this issue should be on miri repository.

Yes, but as I said before miri as no guarantee to build with any rust version or even master.
Because 1.54.0 was cut many weeks ago, the problem has already be fixed on master.

> Sub-module hashtag for `1.54.0` tag is the same as for `master` at the moment https://github.com/rust-lang/rust/tree/1.54.0/src/tools

I don't know were you are looking, but it's not the case, the 1.54.0 beta-cut happen 6 weeks ago. There have been many commit since.

**Comment by hyd-dev** [comment]
> the problem has already be fixed on master

I don't think Miri on `master` works with `parallel-compiler = true`. The code still uses `Rc` which would not be work with `parallel-compiler = true`:
https://github.com/rust-lang/miri/blob/453e3ef7dab5aad6450bee09b2c02de94c5b18cb/src/bin/miri.rs#L45.
I don't know whether Miri is intended to work with `parallel-compiler = true` or not, at least it's not tested in CI.

**Comment by Miezhiko** [comment]
@hyd-dev it was working for me on `1.53.0`

**Comment by Urgau** [comment]
Maybe @RalfJung (the miri maintainer) can help you here.

**Comment by Mark-Simulacrum** [comment]
parallel-compiler = true is not a supported configuration at this time, both for rustc and especially for tools. I'd expect that patches to fix compilation and runtime bugs to be accepted for the most part, but there's not currently active development on that configuration and it's definitely not expected that git tags (i.e., stable releases) will build with parallel compiler enabled.

**Comment by RalfJung** [comment]
Shouldn't https://github.com/rust-lang/rust/pull/86413 have landed the change that avoids Miri being built on stable? Or do we need some other change so it is not in `tools` by default?

**Comment by RalfJung** [comment]
@Miezhiko why did you even build Miri? Did you explicitly ask for it in your `config.toml`, or did it get enabled implicitly somehow?

(If you want to build Miri, you should always use a nightly compiler. That is the only configuration we support.)

**Comment by Miezhiko** [comment]
@RalfJung I enable it manually in config.toml (was thinking maybe it may be useful for me in future) I also build with nightly flag, needed for some features (not sure if FFI is stable already), I'm closing this but personally I'd port (if I know which one) patch fixing this error into sources from which ones I rebuild rust.

**Comment by RalfJung** [comment]
> I also build with nightly flag

Yeah, that doesn't really help for nightly tools like Miri.
The nightly flag will get you a rustc that can use `feature`, but we're still not making any promises about the Miri in a stable release even building.

That said, if you are okay with patching things, I'm happy to give pointers for which patches you'll likely need. :)
