### ISSUE TITLE
Parser incorrectly suggests adding semicolon after function in impl

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#87647]
This also ICEs, but that's a separate issue: #87635. The MCVE here is also from that issue.

I think this issue is also caused by #87436, based on looking at the changes in the test output from that PR. That PR seems to have changed the parser to emit an ``expected `;`, found ...`` error regardless of what token was actually expected.

### Code

[Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=c8d3f3351aa7811e270905d8c5a76475)

```rust
struct Foo {}

impl Foo {
    pub fn bar()
}

fn main() {}
```

### Nightly error

```
error: expected `;`, found `}`
 --> src/main.rs:4:17
  |
4 |     pub fn bar()
  |                 ^ help: add `;` here
5 | }
  | - unexpected token

thread 'rustc' panicked at 'internal error: entered unreachable code', compiler/rustc_parse/src/parser/item.rs:1723:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.56.0-nightly (492723897 2021-07-29) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C codegen-units=1 -C debuginfo=2 --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `playground` due to previous error
```

### Beta error

```
error: expected one of `->`, `;`, `where`, or `{`, found `}`
 --> src/main.rs:5:1
  |
4 |     pub fn bar()
  |            ---  - expected one of `->`, `;`, `where`, or `{`
  |            |
  |            while parsing this `fn`
5 | }
  | ^ unexpected token

error: associated function in `impl` without body
 --> src/main.rs:4:5
  |
4 |     pub fn bar()
  |     ^^^^^^^^^^^-
  |                |
  |                help: provide a definition for the function: `{ <body> }`

error: could not compile `playground` due to 2 previous errors
```

### Meta

Regressed in nightly 1.56.0.

**Comment by apiraino** [comment]
Assigning priority as discussed in the [Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2387647.20Parser.20incorrectly.20suggests.20adding.20semicolon.20after.20f.E2.80.A6) of the Prioritization Working Group.

Bisection seems to confirm that  #87436 may have a role here (specifically  8bebfe5cc2db1603be0d4ad79ad17d48e3b20e54), @ebobrow could perhaps have more info here? Thanks!

@rustbot label -I-prioritize +P-medium

**Comment by ebobrow** [comment]
Uh oh, sorry about this. I don't have any good ideas on how to fix it but I'll take a look. Alternatively, since none of the changes in #87436 are necessary, we could technically roll back the whole PR. It's definitely the cause of this issue.

**Comment by apiraino** [comment]
no worries @ebobrow and thanks for investigating

**Comment by ebobrow** [comment]
If we can be sure that this is the only case where the semicolon check creates unwanted suggestions, we could make it optional, like with a helper function or an extra boolean parameter. That would prevent the ICE and give the expected error message, but I'm not sure how elegant it is. Thoughts?

**Comment by camelid** [comment]
Yeah, this is the current playground output on beta 1.56.0:

```
error: expected `;`, found `}`
 --> src/main.rs:4:17
  |
4 |     pub fn bar()
  |                 ^ help: add `;` here
5 | }
  | - unexpected token

error: associated function in `impl` without body
 --> src/main.rs:4:5
  |
4 |     pub fn bar()
  |     ^^^^^^^^^^^-
  |                |
  |                help: provide a definition for the function: `{ <body> }`

error: could not compile `playground` due to 2 previous errors
```
