### ISSUE TITLE
Tracking Issue for `Vec::pop_unchecked`

### ISSUE THREAD

**Issue by gopherclass** [rust-lang/rust#87656]
Feature gate: `#![feature(vec_pop_unchecked)]`

This is a tracking issue for adding an API to pop from a `Vec` without bounds checking.

`Vec` has the safe and unsafe getter api through `Deref<Target = [T]>`. On the other hand, `Vec` has the safe `pop` method. I'm curious of why `Vec` hasn't the unsafe version of the `pop` method.

### Public API

```rust
impl<T> Vec<T>{
    pub unsafe fn pop_unchecked(&mut self) -> T;
}
```

### Steps / History

- [ ] Implementation: None yet
- [ ] Final comment period (FCP)
- [ ] Stabilization PR

### Unresolved Questions

- None yet.

**Comment by the8472** [comment]
> I'm curious of why Vec hasn't the unsafe version of the pop method.

Do you have an example where it would provide a speedup?

**Comment by gopherclass** [comment]
@the8472 I believe the reason is the same as `[T]::get_unchecked()`, but I has no evidence.

**Comment by the8472** [comment]
Imo unsafe methods should only be added if there's a practical need for them. For the unchecked variants that's usually because there's some concrete code where the compiler fails to elide bounds checks in very hot loops.

This is less likely for `pop` because you can `get_unchecked()` an element repeatedly, i.e. loop over the data many times. But you can only `pop` each element once before having to refill the vec.

**Comment by gopherclass** [comment]
Okay, your remark is quite reasonable. I realized `set_len` and `get_unchecked` seem to be a powerful alternative to `pop_unchecked` in very hot loops because we would normally know the length of a vec in such situations. As I'm convinced `pop_unchecked` wouldn't be effective, I close this issue. Thank for answering my issue.

**Comment by scottmcm** [comment]
I know it's many years later, but I stumbled on this issue and was curious, so took a look.

Near as I can tell, `.pop().unwrap_unchecked()` works perfectly for this: <https://rust.godbolt.org/z/TzYeWh5zr>

- There's no branching at all
- The length update uses `add nsw` which is the best LLVM can currently represent
- The only write-back is the necessary one to update the length of the vec

So it seems that, yup, there's no need for `pop_unchecked` here.
