### ISSUE TITLE
If you set RUSTFLAGS, change a file, and run cargo, all dependencies are pulled again

### ISSUE THREAD

**Issue by adamnemecek** [rust-lang/rust#87670]
I set `export RUSTFLAGS=-Awarmings` in order to suppress warnings (including those from dependencies). If I then run `cargo build` things work as expected (cargo runs terminates a hitch). However if I change a single file file in the current project, all dependencies are pulled and recompiled again. The expected behavior is that that only the current project would be checked.

I'm on nightly (2021-07-30).

**Comment by jyn514** [comment]
Warnings in dependencies are already surpressed. They're rebuilt because cargo doesn't know whether your flags will affect the dependent crates, it doesn't inspect the flags to see if you're passing a --cfg or a lint level.

Anyway, this should be a cargo issue, there's nothing rustc can do.

**Comment by jyn514** [comment]
If you only want to set flags for one crate, you can use `cargo rustc`. I don't know a way to do it for all path dependencies, though.

**Comment by adamnemecek** [comment]
I'm not talking about the first time, I'm talking about after that. I set flags, change file, run cargo, things get rebuilt. I change another file, run cargo and things get rebuilt again.

**Comment by jonas-schievink** [comment]
This is a known Cargo limitation, see https://github.com/rust-lang/cargo/issues/9055

**Comment by adamnemecek** [comment]
It happens not just when you set the flags the first time, but on every recompile after you set the flags.

**Comment by jonas-schievink** [comment]
I can't reproduce that, but that should also be filed over at https://github.com/rust-lang/cargo
