### ISSUE TITLE
Contradiction in WASM SIMD `all_true` function documention

### ISSUE THREAD

**Issue by Cyborus04** [rust-lang/rust#87684]
The documentation for `u8x16_all_true` and `i8x16_all_true` read "Returns true if all lanes are nonzero or false if any lane is nonzero." This is contradictory. Under this definition, if all lanes are non-zero it should return both true and false, and if all lanes are zero it shouldn't return true nor false. I believe they should be "Returns true if all lanes are nonzero or false if any lane is zero."

`u16x8_all_true`, `u32x4_all_true`, `u64x2_all_true`, `i16x8_all_true`, `i32x4_all_true` & `i64x2_all_true` all have this issue as well, though in addition say "1" and "0" instead of "true" and "false", i.e. "Returns 1 if all lanes are nonzero or 0 if any lane is nonzero." instead of "Returns true if all lanes are nonzero or false if any lane is zero."

**Comment by osa1** [comment]
Fix merged in rust-lang/stdarch, should be fixed after a submodule bump.
