### ISSUE TITLE
How do I remove my file paths inside the release version of the executable?

### ISSUE THREAD

**Issue by Joe23232** [rust-lang/rust#87692]
On Windows if I run `cargo build --release`, it doesn't remove my file path if I were to open the executable in notepad and to search up my file path. I wish to strip off such information, is there a way to do so?

I assume anything to do with debug is the reason why my file path is being included in it?

**Comment by hellow554** [comment]
You can use `strip`.

Please ask questions about programming at https://users.rust-lang.org/
This issue tracker is used for tracking issues around the compiler and library :)

**Comment by Joe23232** [comment]
> You can use strip.

I tried that but it doesn't seem to support *.exe.

> Please ask questions about programming at https://users.rust-lang.org/
This issue tracker is used for tracking issues around the compiler and library :)

Sure next time mate =D

> Btw: I can't find any information about my build path in the binary:

Strange, I can see you are using Linux so maybe on Linux it doesn't do this but on Windows it does?
