### ISSUE TITLE
#[track_caller] for std::sync::Once

### ISSUE THREAD

**Issue by lukaslueg** [rust-lang/rust#87707]
https://github.com/rust-lang/rust/blob/3227e35765bab6d02c581928e26ad1d34bacf394/library/std/src/sync/once.rs#L390-L393

Trying to initialize a poisoned `Once` does not track it's caller, yielding panic messages like

> thread 'null_data' panicked at 'Once instance has previously been poisoned', library/std/src/sync/once.rs:392:21

Can we add `#[track_caller]` here? I've seen previous PRs regarding other performance-critical methods get rejected due to the overhead (?) `track_caller` has.

**Comment by yaahc** [comment]
I think we could add it, we'd just need to run a perf test to make sure there are no obvious regressions, and adding it doesn't mean we won't remove it in the future if people come back and start complaining about the perf impact.

**Comment by reez12g** [comment]
@lukaslueg 
>Trying to initialize a poisoned Once does not track it's caller, yielding panic messages like

Could you please give me the sample code for this?
In writing a test in PR for this case, I don't want to misunderstand the situation of this case.

**Comment by yaahc** [comment]
> @lukaslueg
> 
> > Trying to initialize a poisoned Once does not track it's caller, yielding panic messages like
> 
> Could you please give me the sample code for this? In writing a test in PR for this case, I don't want to misunderstand the situation of this case.

Probably something like this:

```rust
use std::sync::Once;
use core::panic::AssertUnwindSafe;

fn main() {
    let o = Once::new();
    let _ = std::panic::catch_unwind(AssertUnwindSafe(|| {
        o.call_once(|| panic!("foo"));
    }));
    o.call_once(|| {});
}
```

The first panic will still print a panic report before being caught and discarded, but the second call_once does subsequently observe the poisoned `Once` with the incorrect location as outlined in this issue:

```
Compiling playground v0.0.1 (/playground)
    Finished dev [unoptimized + debuginfo] target(s) in 1.36s
     Running `target/debug/playground`
thread 'main' panicked at 'foo', src/main.rs:7:24
note: [run with `RUST_BACKTRACE=1` environment variable to display a backtrace](https://play.rust-lang.org/#)
thread 'main' panicked at 'Once instance has previously been poisoned', library/std/src/sync/once.rs:393:21
```

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=88310f9456e506298c454b3e577ca740

**Comment by lukaslueg** [comment]
@yaahc The code I noticed this with is [this](https://github.com/lukaslueg/sqlite3_hyperminhash/blob/87dc48caf4e50860412bb2d1ecdde0f217f7f1d9/tests/util.rs#L23) utility code in a test suite. The code initializes a sqlite3 environment in the testing process, and it simply panics on failure, as the tests are going to fail anyway from that point on. Minimizing the example boils down to what you posted.

While the failure mode of `Once` is comprehensible in this actual example, the output is less than ideal.

```
failures:

---- empty_table stdout ----
# This panic causes the poisoning
thread 'empty_table' panicked at 'bad parameter or other API misuse', tests/util.rs:23:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- null_rows stdout ----
# Source of poisoning now unknown
thread 'null_rows' panicked at 'Once instance has previously been poisoned', library/std/src/sync/once.rs:400:21

---- data_types stdout ----
thread 'data_types' panicked at 'Once instance has previously been poisoned', library/std/src/sync/once.rs:400:21

---- simple_count_error stdout ----
thread 'simple_count_error' panicked at 'Once instance has previously been poisoned', library/std/src/sync/once.rs:400:21

# ....
```

I concur that `Once` should keep its lightweight profile, given that in most situations the poisoning panic is reported in some way. However, we could #[cfg] a field and the machinery for the poisoning location only in debug-build, couldn't we.

**Comment by yaahc** [comment]
> I concur that `Once` should keep its lightweight profile, given that in most situations the poisoning panic is reported in some way. However, we could #[cfg] a field and the machinery for the poisoning location only in debug-build, couldn't we.

For sure, but this would only be available when you compile std yourself locally using `--build-std` because the pre-distributed copies of `std` all have the debug_asserts disabled even when the rest of the libraries in your project are compiled in debug.

**Comment by yaahc** [comment]
closed by https://github.com/rust-lang/rust/pull/94236
