### ISSUE TITLE
LLVM Error for --target x86_64-apple-darwin

### ISSUE THREAD

**Issue by dt665m** [rust-lang/rust#87747]
Hi all, I'm getting a LLVM error trying to build using the x86_64-apple-darwin target on a very specific repository on an ubuntu distro.  Any pointers would be highly appreciated!

OS:
```
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
```

Rust Version:
rustc 1.54.0 (a178d0322 2021-07-26)

Problematic Repository:
https://github.com/paritytech/reed-solomon-novelpoly

Build Command:
```
RUST_BACKTRACE=1 cargo build --target x86_64-apple-darwin --release
```

Output:
```
LLVM ERROR: Global variable '_ZN22reed_solomon_novelpoly5field5f2e164AFFT51__static_init_constructor___static_init_initializer17h35d545d30e5e1531E' has an invalid section specifier '.init_array.65535': mach-o section specifier requires a segment whose length is between 1 and 16 characters.
error: could not compile `reed-solomon-novelpoly`
```

**Comment by jonas-schievink** [comment]
That is not a valid section specifier on macOS. Some of the crates involved don't seem to support macOS. Not a Rust bug, so closing.

**Comment by dt665m** [comment]
this crate does support macos though, when compiling natively from macos.

**Comment by dt665m** [comment]
@jonas-schievink the crate in question does not do anything fancy with C/CXX unless a specific feature flag is on, which I am not using.  I should clarify that the library compiles fine natively in macos, but fails when compiling using a target flag on linux.  It may not be a rust but it could be some kind of toolchain bug somewhere or a version conflict.

**Comment by jonas-schievink** [comment]
The bug is in this build script, it doesn't handle the `darwin` OS correctly: https://gitlab.com/okannen/static_init/-/blob/master/static_init_macro/build.rs

**Comment by dt665m** [comment]
> The bug is in this build script, it doesn't handle the `darwin` OS correctly: https://gitlab.com/okannen/static_init/-/blob/master/static_init_macro/build.rs

Thanks for this tip.  I played around with it and couldn't figure out what was causing the problem.  For some reason, even with ```cargo build --target x86_64-apple-darwin``` the proc_macro ends up generating the 'elf' version when compiling from a linux environment.  Not sure where to go from here.  I'm pretty sure the build.rs is OK because building natively in osx is fine.  It's the way the proc macro resolves the ```cfg!``` that is breaking things.

**Comment by jonas-schievink** [comment]
Natively building uses a different target which the build script handles correctly
