### ISSUE TITLE
global_llvm_asm!

### ISSUE THREAD

**Issue by MabezDev** [rust-lang/rust#87753]
I notice that `global_asm!` is now in the new `asm!` format, not `llvm_asm!` - whilst I do plan on adding support for the asm syntax to my target (Xtensa), is there a `global_llvm_asm!` equivalent I can switch to to keep things running right now?

**Comment by nagisa** [comment]
`llvm_asm!` is being deprecated ( #87590) and will be removed, so it is not likely we'll be adding support for `llvm` style asm in any other scenarios.

**Comment by MabezDev** [comment]
I can work around this for now with precompiled archives - looks like I'll need to look into porting the new asm syntax sooner than I thought.

Thanks
