### ISSUE TITLE
Mutate error in Compiler Session Diagnostics

### ISSUE THREAD

**Issue by LDY1998** [rust-lang/rust#87765]
Hi all,

I am working under project prusti, which is a verification tool against rust. The tool is designed to be a plugin that work along with the compiler and verify the user's source code if they annotate it with our syntax.

Recently I am trying to implement a new feature in the project and I would like to access the error recorded during rust compile and map it to a more clear prusti internal error, is there any API available for doing that? If there isn't I wonder if it's possible to have that in rust so that it allows the plugin developer to have more freedom to decide what they want to do with the errors? (like a mutable reference to error or to be able to register a callback to deal with error)

I've also asked the question in forums and compiler zulip:
https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp/topic/Map.2FMutate.20error.20in.20Compiler.20Session.20Diagnostics/near/248254289
https://internals.rust-lang.org/t/access-to-compiler-error-in-callbacks/15134

**Comment by jyn514** [comment]
This is a question, not a bug, and you'll get more helpful answers on zulip anyway.
