### ISSUE TITLE
Rustdoc no longer shows 'Methods from Deref impls' at all

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#87783]
I tried this code:

```rust
    use std::path::{Path, PathBuf};

    pub struct Foo(PathBuf);
    impl std::ops::Deref for Foo {
        type Target = Path;
        fn deref(&self) -> &Path { &self.0 }
    }
```

I expected to see this happen: Rustdoc shows the docs for `Path::from_str` on the docs for `Foo`, like it used to in 1.51: 
![image](https://user-images.githubusercontent.com/23638587/128289181-df8d815a-4b0d-454a-85fd-b873cc1f3a11.png)

Instead, this happened: Rustdoc does not generate those methods:
![image](https://user-images.githubusercontent.com/23638587/128289287-06ea359c-554c-49e6-9623-4ea817900f1e.png)

### Meta

searched nightlies: from nightly-2021-04-01 to nightly-2021-07-30
regressed nightly: nightly-2021-06-16
searched commits: from https://github.com/rust-lang/rust/commit/539d7bd3998d9bfed14c264eacda30097a4ea768 to https://github.com/rust-lang/rust/commit/607d6b00d4e0e0475b8de9d0c870b7126fdcdf6b
regressed commit: https://github.com/rust-lang/rust/commit/d74b36ea2f814b720c39d7b60aecaefe512a056b

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.0</summary>

Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --script ./docs-exist.sh --start 2021-04-01 
```

where `docs-exist.sh` is
```sh
#!/bin/sh
cargo doc
grep 'Methods from Deref' ${CARGO_TARGET_DIR:-target}/doc/hello_world/foo/struct.Foo.html
```

</details>

cc @pnkfelix

**Comment by apiraino** [comment]
Assigning priority as discussed in the [Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2387783.20Rustdoc.20no.20longer.20shows.20'Methods.20from.20Deref.20impls'.20a.E2.80.A6) of the Prioritization Working Group.

@rustbot label -I-prioritize +P-high
