### ISSUE TITLE
E0433 should do fuzzy matching to look for types that would be valid

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#87791]
The following code
```rust
    let _ = string::new();
```
[produces](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=aef9a642834a4694cf2fe618acf9c338):
```
error[E0433]: failed to resolve: use of undeclared crate or module `string`
 --> src/main.rs:2:13
  |
2 |     let _ = string::new();
  |             ^^^^^^ use of undeclared crate or module `string`
```

We should be doing fuzzy matching like we do in other cases and suggest changing `string` to `String`.

**Comment by Milo123459** [comment]
@rustbot claim

Before I start working on this, I have some quick questions: what is the input for the fuzzy matching? It needs to have a list of all types, structs that are available in the file (or not!) and also std ones. I'm just not entirely sure how to go about doing this.

PS: I'm pretty sure this is going to require adding some sort of crate to rustc, is that okay?

**Comment by estebank** [comment]
I don't think adding something will be needed. `rustc_resolve` already has some facilities in place to search for "all items" and then we have a levenshtein distance function that can let us linearly scan all type names for ones that have a short distance.

**Comment by Milo123459** [comment]
I've been searching through the code for a bit, and I'm yet to find a function that can search for "all items", and the leven function?

**Comment by estebank** [comment]
@Milo123459 I am pretty sure there's such a function. I'm looking at https://github.com/rust-lang/rust/blob/3e5800b8d30fba923c5070ae660c1e45a630a191/compiler/rustc_resolve/src/late/diagnostics.rs, which is where would expect it to be used at least once.

**Comment by estebank** [comment]
`Namespace` only differentiates between the kind of items that can be referenced, not their scope. By that I mean it lets you say "I want all the names that are types, not variables", for example.

**Comment by Milo123459** [comment]
Ah, so I guess I need to set the path to the current file?
