### ISSUE TITLE
Lint suggestion: Useless explicit documentation link

### ISSUE THREAD

**Issue by ThomasdenH** [rust-lang/rust#87799]
Once [intra-rustdoc links](https://github.com/rust-lang/rfcs/blob/master/text/1946-intra-rustdoc-links.md) lands, many explicit links will become unnecessary. It would be very useful to have a lint that would warn if the computed automatic link is the same as the provided link.

For example:

```
[Iterator](std::iter::Iterator)
Warning: unnecessary explicit rustdoc lint; you could replace this by "[Iterator]"
```

**Comment by yerke** [comment]
@mdsn Are you still working on it?

**Comment by mdsn** [comment]
@yerke hi! No, please go right ahead and claim it. 😃 If you search for the issue number on Zulip you'll find some questions of mine back then. I'll try to post later some of what I thought while looking into this issue.
