### ISSUE TITLE
Better description for Error E0433

### ISSUE THREAD

**Issue by sonysantos** [rust-lang/rust#87841]
The Rust error descriptions are very good, you do good job on them!

But I suggest a tiny improvement for the error E0433.

The most important sentence for beginners like me is the penultimate line of the message: "Make sure the crate has been added as a dependency in Cargo.toml." - which I failed to pay attention to.

My suggestion is to move it to be the second sentence, below "An undeclared crate, module, or type was used.", and change it to be more flashy, like:

"First of all, make sure the crate has been added in the [dependencies] section in Cargo.toml."

Thank you all.

**Comment by bishtpawan** [comment]
The changes have already been updated in the source code.
![Screenshot from 2021-09-16 16-56-56](https://user-images.githubusercontent.com/46450720/133604119-68db9af8-6dd7-404b-9b78-344d7f7c93f6.png)
