### ISSUE TITLE
Tracking Issue for `#![feature(mixed_integer_ops)]`

### ISSUE THREAD

**Issue by a1phyr** [rust-lang/rust#87840]
Feature gate: `#![feature(mixed_integer_ops)]`

### Public API

```rust
// `uX` is `u8`, `u16`, `u32`, `u64`,`u128`, `usize`
impl uX {
    pub const fn checked_add_signed(self, iX) -> Option<Self>;
    pub const fn overflowing_add_signed(self, iX) -> (Self, bool);
    pub const fn saturating_add_signed(self, iX) -> Self;
    pub const fn wrapping_add_signed(self, iX) -> Self;
}

impl iX {
    pub const fn checked_add_unsigned(self, uX) -> Option<Self>;
    pub const fn overflowing_add_unsigned(self, uX) -> (Self, bool);
    pub const fn saturating_add_unsigned(self, uX) -> Self;
    pub const fn wrapping_add_unsigned(self, uX) -> Self;

    pub const fn checked_sub_unsigned(self, uX) -> Option<Self>;
    pub const fn overflowing_sub_unsigned(self, uX) -> (Self, bool);
    pub const fn saturating_sub_unsigned(self, uX) -> Self;
    pub const fn wrapping_sub_unsigned(self, uX) -> Self;
}
```

### Steps / History

- [x] Implementation: #87601 
- [ ] Final comment period (FCP)
- [ ] Stabilization PR

**Comment by leonardo-m** [comment]
Somewhere you should write about use cases & purposes of these ops :)

**Comment by brendanzab** [comment]
> Somewhere you should write about use cases & purposes of these ops :)

I've needed `checked_add_signed` for working with [`io::SeekFrom`](https://doc.rust-lang.org/stable/std/io/enum.SeekFrom.html), for example! Had to roll my own (and I'm not sure how correct it is), inspired by [this implementation](https://github.com/freedomlayer/offset/blob/e935f8f5f5d84cd1bb7b6359e4fc3b57b6fddaee/components/common/src/safe_arithmetic.rs#L81-L87):

```rust
fn checked_add_signed(pos: u64, offset: i64) -> Option<u64> {
    if offset >= 0 {
        u64::checked_add(pos, offset as u64)
    } else {
        u64::checked_sub(pos, offset.unsigned_abs())
    }
}
```

It would be great to have this in the stdlib!

**Comment by a1phyr** [comment]
This is exactly what prompted me to write these ! 

Also it is [what `std` uses for `Cursor` now](https://github.com/rust-lang/rust/blob/ba14a836c7038da21f5e102aacc7e6d5964f79a6/library/std/src/io/cursor.rs#L295).

**Comment by tjallingt** [comment]
Would love to see this get stabilized. Not sure what the right process is to start an FCP

**Comment by avl** [comment]
I love these methods! 

I would love to see *_sub_signed and friends too. I just had a use for saturating_sub_signed (subtracting a signed residual from an unsigned value to create a corrected value). In my case, I can just negate the residual. However, that might cause overflow, in which case the final calculated value would not be correct. This won't really matter in practice, but saturating_sub_signed still would have been nice!

**Comment by joshtriplett** [comment]
These have been around for a long time, and it seems like several people are interested in them.

Shall we stabilize these?

@rfcbot merge

**Comment by JohnTitor** [comment]
The feature has been stabilized by #101555, closing.
