### ISSUE TITLE
Discrepant behavior of scoped `cfg` attribute specifier

### ISSUE THREAD

**Issue by Zapeth** [rust-lang/rust#87866]
After reading that about this feature [existing since 1.21.1](https://stackoverflow.com/questions/24396293/is-it-possible-to-conditionally-compile-a-code-block-inside-a-function) (though apparently not mentioned in the [reference](https://doc.rust-lang.org/reference/conditional-compilation.html#the-cfg-attribute)?) I wanted to use it in my project, but apparently it works differently from the "standard" `cfg` attribute, despite appearing identical syntactically:

- can't be used in global context (functions/closures only?)

This works
```rust
enum Testing {
  One,
#[cfg(feature = "test")]
  Two,
  Three
}

fn main() {
#[cfg(feature = "test")]
  let test = Testing::Two;
}
```
This throws an error
```rust
enum Testing {
  One,
#[cfg(feature = "test")] {
  Two,
}
  Three
}

fn main() {
  #[cfg(feature = "test")]
  let test = Testing::Two;
}
```
Output:
```
error: expected identifier, found `{`
 --> test.rs:3:26
  |
3 | #[cfg(feature = "test")] {
  |                          ^ expected identifier
```
---
- can't be used multiple times or combined with "standard" `cfg` attribute

This works
```rust
fn main() {
#[cfg(feature = "test")]
  let test = "world";
#[cfg(feature = "test")]
  println!("Hello {}", test);
}
```
As does this
```rust
fn main() {
#[cfg(feature = "test")] {
  let test = "world";
  println!("Hello {}", test);
}
}
```
However when mixing or using it multiple times, issues occur:
```rust
fn main() {
#[cfg(feature = "test")] {
  let test = "world";
}
#[cfg(feature = "test")]
  println!("Hello {}", test); // same output when putting this in {}
}
```
Output:
```
error[E0425]: cannot find value `test` in this scope
 --> test.rs:7:23
  |
7 |     println!("Hello {}", test);
  |                          ^^^^ not found in this scope
```
### Meta

`rustc --version --verbose`:
```
rustc 1.53.0
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-linux-musl
release: 1.53.0
LLVM version: 12.0.0
```

**Comment by Zapeth** [comment]
I just realized why these issues occur, I guess the implementation just treats the `{}` block as a normal expression instead of the implied "block" specifier? (at least somewhat implied if you're coming from C/C++).

Either way it would still be nice to have this functionality in rust, instead of having to specify `#[cfg(feature = "")]` for every line if you want to conditionally disable an entire block of code.

**Comment by jfrimmel** [comment]
Your guess is correct.

Currently, the standard library does not feature the multi-line `#[cfg]`s you want, but 3rd-party crates are:
1. [`cfg-if`](https://crates.io/crates/cfg-if), one of the most downloaded crates
2. [`cfg-match`](https://crates.io/crates/cfg-match) with somewhat nicer syntax in my opinion
