### ISSUE TITLE
Build succeed but no executable file created (error "could not execute process `target/debug/[project name]` (never executed)")

### ISSUE THREAD

**Issue by nisimjoseph** [rust-lang/rust#87894]
I am working on Mac with the latest version (11.5.1) and I installed Rust and create a simple project using the `cargo new learn1` command and then run the `cargo run` which builds and runs the simple "Hello World" project.

The build finish with:
```   
Compiling learn1 v0.1.0 (/Users/[username]/git/rust/learn1)
Finished release [optimized] target(s) in 6.86s
Running `target/debug/learn1`
error: could not execute process `target/debug/learn1` (never executed)
```
now, I see this error and the file `learn1` which is the executable file was not created. All the rest of the files in the `target/debug` folder were created except for the binary file.

I tried it on another Mac with the same version and even an older one, and all working there. but on my Mac, it never creates the binary file. I know it is not an access issue because other files are created and written.

I really need an assist here, I am trying to handle it for 5 hours and can't find anything to solve it. Any logs I can find? any idea why it can occur?

**Comment by nagisa** [comment]
Antivirus(-es)? Sandboxes? Isolations?

**Comment by nisimjoseph** [comment]
I work in a company which has things like that, so I ask IT and they turn off the Antivirus.

I also tried another employee's computer, the same as mine, and it worked there even with the Antivirus turn ON.

do we have logs for this in Rust?

**Comment by nagisa** [comment]
There's some documentation for [logging from rustc](https://rustc-dev-guide.rust-lang.org/compiler-debugging.html#getting-logging-output). Logging with the `info` level should be sufficient to see the linker invocation line, which is what should be ultimately producing the final executable file.

**Comment by nisimjoseph** [comment]
this is what I got when turn `debug = true` in config:
```
➜  learn1 git:(master) ✗ cargo run -v
warning: unused manifest key: package.debug
   Compiling learn1 v0.1.0 (/Users/nisim.j/Desktop/learn1)
     Running `rustc --crate-name learn1 --edition=2018 src/main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C embed-bitcode=no -C split-debuginfo=unpacked -C debuginfo=2 -C metadata=b039cbe887790850 --out-dir /Users/nisim.j/Desktop/learn1/target/debug/deps -C incremental=/Users/nisim.j/Desktop/learn1/target/debug/incremental -L dependency=/Users/nisim.j/Desktop/learn1/target/debug/deps`
    Finished dev [unoptimized + debuginfo] target(s) in 7.83s
     Running `target/debug/learn1`
error: could not execute process `target/debug/learn1` (never executed)

Caused by:
  No such file or directory (os error 2)
```

**Comment by nagisa** [comment]
Please run with `RUSTC_LOG=info` as per the linked instructions instead.

`package.debug=true` as the warning mentions doesn't do anything.

Just to give you some background information on what's the intended flow is:

1. `cargo` invokes `rustc` (as you see in your verbose output above) to compile an executable into `/Users/nisim.j/Desktop/learn1/target/debug/deps`;
2. `rustc` produces a number of object files and whatnot and links them with the linker (usually `cc`) into the requested location (in this case `/Users/nisim.j/Desktop/learn1/target/debug/deps/learn1`;
3. Once the `rustc` executable terminates, `cargo` should do an equivalent of a `cp /Users/nisim.j/Desktop/learn1/target/debug/deps/learn1 /Users/nisim.j/Desktop/learn1/target/debug/learn1`;
4. `cargo` attempts to execute `/Users/nisim.j/Desktop/learn1/target/debug/learn1`.

I guess another question: is the native toolchain installed? That's what provides the linker for `rustc`. Usually the OS should prompt for it, but if it didn't for some reason, try `xcode-select --install`, perhaps? Either way its weird that there are no other errors.

**Comment by nisimjoseph** [comment]
hi @nagisa , 
thank you for the detailed response.

I do see all the objects files built to the `deps` folder.
I output all stdout using the `RUSTC_LOG=info`, see the link to the entire output:
https://drive.google.com/file/d/1XUiYva5Ry2q8HnReZFZqTOh5aasKFQ75/view?usp=sharing

**Comment by nagisa** [comment]
Here's the relevant part from the logs:

```
INFO rustc_codegen_ssa::back::link "cc" "-m64" "-arch" "x86_64" "/Users/nisim.j/Desktop/learn1/target/debug/deps/learn1.102pstpts17c314h.rcgu.o" "/Users/nisim.j/Desktop/learn1/target/debug/deps/learn1.2pfd7663zeh7asok.rcgu.o" "/Users/nisim.j/Desktop/learn1/target/debug/deps/learn1.2sp89fd17tzsxve8.rcgu.o" "/Users/nisim.j/Desktop/learn1/target/debug/deps/learn1.2t7nwrl68dqr0t0l.rcgu.o" "/Users/nisim.j/Desktop/learn1/target/debug/deps/learn1.3h39bm346qd0rkwh.rcgu.o" "/Users/nisim.j/Desktop/learn1/target/debug/deps/learn1.4hsrwoxva3oi775n.rcgu.o" "/Users/nisim.j/Desktop/learn1/target/debug/deps/learn1.4wehrty8eqzjpx2m.rcgu.o" "/Users/nisim.j/Desktop/learn1/target/debug/deps/learn1.qouodl1x4i4frpf.rcgu.o" "/Users/nisim.j/Desktop/learn1/target/debug/deps/learn1.17ed9nu225rq9exs.rcgu.o" "-L" "/Users/nisim.j/Desktop/learn1/target/debug/deps" "-L" "/Users/nisim.j/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "/Users/nisim.j/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libstd-7b3af7e771532c4d.rlib" "/Users/nisim.j/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libpanic_unwind-a312a9d36c2b4585.rlib" "/Users/nisim.j/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libobject-0056ecd921542c45.rlib" "/Users/nisim.j/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libaddr2line-136473faa654159d.rlib" "/Users/nisim.j/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libgimli-8948906b8f5e65a2.rlib" "/Users/nisim.j/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libstd_detect-349769333cecb33c.rlib" "/Users/nisim.j/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librustc_demangle-2836451a12f8e8a3.rlib" "/Users/nisim.j/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libhashbrown-82701dea42c34fd2.rlib" "/Users/nisim.j/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librustc_std_workspace_alloc-b9c0c998e7e580c1.rlib" "/Users/nisim.j/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libunwind-b80d5b40251f2607.rlib" "/Users/nisim.j/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcfg_if-48a685da8003dd08.rlib" "/Users/nisim.j/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liblibc-6c310d5e4d35fd71.rlib" "/Users/nisim.j/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/liballoc-49c2386372f9dd61.rlib" "/Users/nisim.j/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/librustc_std_workspace_core-e7ab9cb891a80b09.rlib" "/Users/nisim.j/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcore-f2fbb54bfcfb6a1f.rlib" "/Users/nisim.j/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib/libcompiler_builtins-7f68ec848bc59e6b.rlib" "-lSystem" "-lresolv" "-lc" "-lm" "-liconv" "-L" "/Users/nisim.j/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib" "-o" "/Users/nisim.j/Desktop/learn1/target/debug/deps/learn1" "-Wl,-dead_strip" "-nodefaultlibs"

INFO rustc_codegen_ssa::back::link linker stderr:

INFO rustc_codegen_ssa::back::link linker stdout:
Parameters:
{
  "m": [
    64,
    true,
    true
  ],
  "a": [
    true,
    true
  ],
  "action": [
    true,
    true
  ],
  "r": [
    true,
    true
  ],
  "c": [
    true,
    true,
    true
  ],
  "h": "x86_64",
  "L": [
    "/Users/nisim.j/Desktop/learn1/target/debug/deps",
    "/Users/nisim.j/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib",
    "/Users/nisim.j/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib"
  ],
  "l": [
    true,
    true,
    true,
    true,
    true,
    true,
    ",-dead_strip",
    true,
    true
  ],
  "S": true,
  "y": true,
  "s": [
    true,
    true,
    true
  ],
  "t": [
    true,
    true
  ],
  "e": [
    true,
    true,
    true
  ],
  "o": [
    true,
    true,
    "/Users/nisim.j/Desktop/learn1/target/debug/deps/learn1",
    true
  ],
  "v": [
    true,
    true
  ],
  "i": [
    true,
    true
  ],
  "n": [
    true,
    true
  ],
  "W": true,
  "d": true,
  "f": true,
  "u": true,
  "b": true
}

Missing 'pubName' parameter.
```

Do you see the `learn1` binary itself in the `deps` directory?

**Comment by nisimjoseph** [comment]
I see those files:
```
learn1.102pstpts17c314h.rcgu.o
learn1.2pfd7663zeh7asok.rcgu.o
learn1.2sp89fd17tzsxve8.rcgu.o
learn1.2t7nwrl68dqr0t0l.rcgu.o
learn1.3h39bm346qd0rkwh.rcgu.o
learn1.4hsrwoxva3oi775n.rcgu.o
learn1.4wehrty8eqzjpx2m.rcgu.o
learn1.d
learn1.qouodl1x4i4frpf.rcgu.o
```

no binary file.

**Comment by nagisa** [comment]
So the linker is executed, exits with a success code, but does not produce a binary file (or that binary file is deleted by something else very quickly.)

Just to make sure: Where does your `cc` come from (please provide at least the output of `cc --version` and `which cc`)? What's the output of `rustc --version` and `cargo --version`?

**Comment by nisimjoseph** [comment]
@nagisa , your last note above `cc` just hit me! I created a custom terminal command called `cc` using Node.js to run it from the terminal at a global level... this command was called instead of the real `cc` command.

I just uninstalled my `cc` and it all working well.

😣 😖

Thank you for the time and insight.

**Comment by dzyphr** [comment]
LOL I made the exact same command, I guess we cannot have nice things and have rust work properly haha. anyways thanks this is a weird edge-case to run into

**Comment by erm3nda** [comment]
I had a .local/bin script called cc, so ...
