### ISSUE TITLE
`rustdoc` does not track changes of files included with `#[doc = include_str!("FILE")]`

### ISSUE THREAD

**Issue by ATiltedTree** [rust-lang/rust#87899]
When using `#[doc = include_str!("FILE")]` `rustdoc` (e.g. `cargo doc`) does not notice that `FILE` changed and thus does not rebuild the documentation. It should probably track the modification time and rebuild the documentation when `FILE` changes.

**Comment by hellow554** [comment]
As a workaround you could create a `build.rs` file and use [`cargo:rerun-if-changed=`](https://doc.rust-lang.org/cargo/reference/build-scripts.html#rerun-if-changed).

But I'm with you, it should recompile it.

**Comment by hellow554** [comment]
@ATiltedTree it does rebuild the docs for me. If I do `echo hello > doc` before the first build and `echo world > doc` before the second, it will rebuild it and the text will be displayed properly.

Can you show us what you mean and maybe output your compiler version (`rustc -vV`)

**Comment by ATiltedTree** [comment]
I don't really know what changed since yesterday when I tried this, but it seems to be working now. Weird. The only thing I can remember doing is a reboot, so that might have fixed it?
