### ISSUE TITLE
Iterator::nth() is badly named

### ISSUE THREAD

**Issue by pchampin** [rust-lang/rust#87911]
Intuitively, `.nth(1)` could be expected to return be the *first* element, `.nth(2)` the *second*, and so on...

I am of course *not* suggesting to change the semantics of `.nth()` now, which would obviously cause a backward compatibility trainwreck. I am not suggesting either that this method or another one should start the count at 1, as all other operations start the count at 0.

What I am suggesting is that it should not have been named "nth" in the first place, and that it should be deprecated in favor of another one with the same semantics but a less confusing name (e.g. `.item(i)` or maybe `.get(i)`)...

**edited**: fixed a typo and add the suggestion to rename it to `get`

**Comment by the8472** [comment]
How is this different from other zero-based indexing methods such as `slice[0]` or `slice[0..]`?

**Comment by pchampin** [comment]
@the8472 The porblem is the *name* of the `nth` method, which strongly conveys the idea of ranking (i.e. "first", "second", "third"...) which is a 1-based numbering convention, while that method is actually using the same 0-based numbering convention as all other methods and operators.

In other words, I have no problem with the fact that `s.get(n)` is not returning the n-th element of a slice `s`, because the name "get" does not point to any of the two possible conventions. On the other hand, the fact that `it.nth(n)` does not return the n-th element of `it` is... surprising, to say the least!

**Comment by camsteffen** [comment]
I know what you mean, this has confused me as well. But this is not nearly a strong enough reason to deprecate a method of `Iterator`. The alternatives `get` and `item` are worse IMO because they sound like random access rather than iteration. So I still think `nth` is the best possible name.

**Comment by pchampin** [comment]
Mind that I propose to merelt deprecate the name, i.e. deprecate `nth` but add an equivalent method with a better name.

I see how `item` or `get` could give the impression of direct access -- although I would argue that this is not as explicit as what `nth` conveys... But granted, this is a subjective matter...

What about `.after(n)` or `.next_after(n)`?

**Comment by camsteffen** [comment]
> Mind that I propose to merelt deprecate the name, i.e. deprecate `nth` but add an equivalent method with a better name.

Deprecating such a widely used method is no small matter. You're asking everybody to change their code and learn another method.

> I see how `item` or `get` could give the impression of direct access -- although I would argue that this is not as explicit as what `nth` conveys... But granted, this is a subjective matter...

Yes quite subjective. To deprecate, we would at least need an alternative that is widely believed to be significantly better.

> What about `.after(n)` or `.next_after(n)`?

`after` is too vague. `next_after` is perhaps more clear, but I still prefer `nth` because it's short and simple.

Rust and English are different languages. There are some similarities to help you learn Rust, but there are also many nuanced differences and this is one of them. The zero-based confusion is a particularly common theme. In a way that's a good thing - Rust is consistent about being zero-based.

**Comment by the8472** [comment]
> @the8472 The problem is the name of the nth method, which strongly conveys the idea of ranking (i.e. "first", "second", "third"...) which is a 1-based numbering convention

You skipped over "zeroth" here. nth(0) just is the 0<sup>th</sup> element which is perfectly consistent with all other zero-based indexing.

**Comment by pchampin** [comment]
> Rust is consistent about being zero-based.

And that's indeed a very good thing. I am not questioning that.

> Rust and English are different languages. There are some similarities to help you learn Rust, but there are also many nuanced differences

Agreed...

> and this is one of them.

... but here I respectfully disagree. In this case, I see a contradiction between the English meaning and the Rust meaning, one that is confusing and could be avoided.

> You skipped over "zeroth" here

My point being: there is no such thing as "zeroth". Using 0-based numbering does not change the meaning of words such as "first", "second", "tenth", or their generalization "n-th"... By the way, the word "first" is [used in several places](https://doc.rust-lang.org/std/?search=first) in the standard lib, with its usual meaning.

> Deprecating such a widely used method is no small matter.

I understand that, and I don't expect my sole opinion to trigger such a change. But I think it deserves to be discussed.

**Comment by camsteffen** [comment]
New programmers will mistakenly read `get(1)` as "get first". I think the only reason you are finding `nth` to be more confusing than `get` is that you are more familiar with `get` in code.

**Comment by pchampin** [comment]
> New programmers will mistakenly read get(1) as "get first".

I happen to teach programming to beginners, and I spend a lot of time repeating to them "`a[i]` and `a.get(i)` are *not* the i-th element of `a`", precisely to help them avoid that mistake. I am quite happy with this rethoric, but it kind of falls apart when it becomes "`it.nth(i)` is not the i-th element of `it`". 

> I think the only reason you are finding `nth` to be more confusing than `get` is that you are more familiar with `get` in code.

As I [tried to explain above](https://github.com/rust-lang/rust/issues/87911#issuecomment-896790503), I think the problem is a little deeper and less subjective than that. But I guess we have to agree to disagree.

**Comment by jyn514** [comment]
I find it *highly* unlikely `nth()` will be deprecated, but either way, this doesn't belong in a github issue. Feel free to open a thread on internals.rust-lang.org/ if you think this worth pursuing - it probably doesn't need a full RFC, but it would need at least an FCP, and for that you need to have an alternate suggestion that people are happy with.
