### ISSUE TITLE
arm-none-eabi (etc) have incorrect repr(C) enum layout (AAPCS vs AAPCS-linux)

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#87917]
We're building code for a Cortex-M33 running FreeRTOS, and using C/Rust FFI.

The C code is being compiled with:

```
compiler is arm-none-eabi-g++ (GNU Arm Embedded Toolchain 10-2020-q4-major) 10.2.1 20201103 (release)
target flags -mcpu=cortex-m33 -mthumb -mfloat-abi=hard -mfpu=fpv5-sp-d16
```

The rust code is being compiled with:

```
RUSTFLAGS=”-Ctarget-cpu=cortex-m33” cargo +nightly build -Zbuild-std --target=thumbv8m.main-none-eabihf
```

The following enum:

```rust
#[repr(C)]
enum Foo {A, B}
```

has a size of 4 on the rust side and 1 on the C side.

The specific choice of Cortex CPU is not relevant here, a reduce testcase that enables us to see the size in a compiler error (so we don't need to actually run the code) is as follows:

<details>

```c
// arm-none-eabi-g++ test.c -mthumb -mfloat-abi=hard -mfpu=fpv5-sp-d16
typedef enum Foo {A, B} Foo;
char (*error)[sizeof( Foo )] = 1;
```

Produces the error: `error: invalid conversion from 'int' to 'char (*)[1]'`, whereas:

```rust
// cargo build --target=thumbv8m.main-none-eabihf -Zbuild-std
#![no_std]
#[repr(C)]
enum Foo { A, B }
const BAR: [u8; ::core::mem::size_of::<Foo>()] = [];
```

Produces the error `expected an array with a fixed size of 4 elements, found one with 0 elements`

</details>

This bug traces back to this comment: https://github.com/rust-lang/rust/blob/ae90dcf0207c57c3034f00b07048d63f8b2363c8/compiler/rustc_middle/src/ty/layout.rs#L134-L138 ([see also](https://rust-lang.github.io/unsafe-code-guidelines/layout/enums.html#layout-of-a-fieldless-enum))

I am able to reproduce this for both thumb and non-thumb, with and without hard floats: `arm-none-eabi-g++ test.c`, regardless of the `-mthumb` and `-mfloat-abi=hard` flags, will always think the enum is of size 1, whereas I tried a bunch of ARM targets on the Rust side and they all think it is of size 4.

`arm-linux-gnueabi-g++` agrees with Rust about the size of the enum, so I think this has to do specifically with `-none-eabi` and `-none-eabihf`. I feel like we should either follow GCC's convention (which is presumably clang's convention), or expose a codegen flag that flips this.

cc @joshtriplett @cuviper  @japaric who typically care about stuff like this

**Comment by Manishearth** [comment]
I _think_ this difference matches to the `-mabi=aapcs` vs `-mabi=aapcs-linux` flags on GCC, and GCC is picking different defaults here based on platform.

**Comment by eddyb** [comment]
That comment has been unchanged since #9613 - I guess we don't do enough FFI testing?

**Comment by Manishearth** [comment]
lol

perhaps the fix is to make it u8 for `arm/thumb-none`?

**Comment by eddyb** [comment]
Maybe we want to make it part of the target specification? Feels very wrong to have architecture names hardcoded in `ty::layout` to begin with.

**Comment by Manishearth** [comment]
oh, we can just make it None

**Comment by Manishearth** [comment]
Makes sense. Perhaps also a codegen flag.
