### ISSUE TITLE
`Invalid LLVMRustVisibility value!` error on `cargo build` after upgrading from 1.53.0 to 1.54.0

### ISSUE THREAD

**Issue by datdenkikniet** [rust-lang/rust#87933]
After upgrading our toolchains from `1.53.0` to `1.54.0`, our bootloader rust crates stopped building. 

Instead, the build command produced the error message `LLVM ERROR: Invalid LLVMRustVisibility value!`.

### Code

As these are a closed-source projects I cannot share any code publicly, but it can be shared privately if necessary.

I expected to see this happen: the build to succeed

Instead, this happened: the build failed

### Version it worked on

It most recently worked on: Rust 1.53

### Version with regression

`rustc --version --verbose`:
```
rustc 1.54.0 (a178d0322 2021-07-26)
binary: rustc
commit-hash: a178d0322ce20e33eac124758e837cbd80a6f633
commit-date: 2021-07-26
host: x86_64-unknown-linux-gnu
release: 1.54.0
LLVM version: 12.0.1
```

### Backtrace
The compiler did not crash or produce a backtrace.

</p>
</details>

**Comment by hellow554** [comment]
Looks like a dup of #87813

**Comment by hellow554** [comment]
You may search whether you have declarations that have the same name, but a different type. I was only able to reproduce the error with that constraint, see https://github.com/rust-lang/rust/issues/87813#issuecomment-896089661

**Comment by datdenkikniet** [comment]
All declarations have the same type (`u32`). We do get a different error, so it could be that the issues are related but not strictly the same.

**Comment by hellow554** [comment]
Can you use the https://github.com/kennytm/rustup-toolchain-install-master project to get a "-alt" nightly (which has LLVM assertions enabled) and try to compile your code with it. Does it give you the same result as https://github.com/rust-lang/rust/issues/87813#issuecomment-896072259 ?

**Comment by datdenkikniet** [comment]
I've tried, but it seems as though the target we compile for isn't (easily?) available that way. 

`rustup-toolchain-install-master -a -t thumbv7em-none-eabihf` doesn't work, and I'm not sure how to get it to work. Any guidance?

**Comment by datdenkikniet** [comment]
Thank you, now running the `cargo build` worked.

It does seem to be the same issue as in https://github.com/rust-lang/rust/issues/87813#issuecomment-896072259, so apart from the fact that our types are all the same it does seem to be the same issue.
```
rustc: /checkout/src/llvm-project/llvm/include/llvm/Support/Casting.h:269: typename cast_retty<X, Y *>::ret_type llvm::cast(Y *) [X = llvm::GlobalValue, Y = llvm::Value]: Assertion `isa<X>(Val) && "cast<Ty>() argument of incompatible type!"' failed.
```

**Comment by datdenkikniet** [comment]
Yes, that sounds good to me! Will do, and thank you for the help

**Comment by apiraino** [comment]
Assigning priority as discussed in the [Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2387933.20.60Invalid.20LLVMRustVisibility.20value!.60.20error.20on.20.60cargo.20.E2.80.A6) of the Prioritization Working Group.

@rustbot label -I-prioritize +P-high

**Comment by deg4uss3r** [comment]
@hellow554 or anyone else in this thread know how to get the `-alt` builds for Apple Silicon Macs? 

```
❯ rustup-toolchain-install-master -a -c rust-src -f
fetching master commit hash...
detecting the channel of the `8f8092cc32ec171becef8ceacec7dbb06c5d7d7e` toolchain...
downloading <https://ci-artifacts.rust-lang.org/rustc-builds-alt/8f8092cc32ec171becef8ceacec7dbb06c5d7d7e/rustc-nightly-aarch64-apple-darwin.tar.xz>...
error: missing component `rustc` on toolchain `8f8092cc32ec171becef8ceacec7dbb06c5d7d7e` on channel `nightly` for target `aarch64-apple-darwin`
```

**Comment by hellow554** [comment]
@deg4uss3r my best guess is: because aarch64-apple-darwin is not a tier1 platform, there's no alt target built per default. You may have to build it yourself.

@apiraino have you a better idea?

**Comment by deg4uss3r** [comment]
I don't mind building myself was just hoping I didn't have to! 

Is there a good `config.toml` around that adds the LLVM assertions and keeps everything else close to the normal compiler?

**Comment by deg4uss3r** [comment]
Huh interesting looks like my project is now only hitting this on `cargo test` any good way to track down which symbols are clashing?

**Comment by kjvalencik** [comment]
The code that caused the issue in the project @deg4uss3r mentioned was an `extern "C"` that pointed to itself.

```rust
    #[used]
    #[link_section = "__TEXT,__asar_integrity"]
    #[no_mangle]
    static _EMBED_ASAR_INTEGRITY: [u8; 4] = *b"1234";

    extern "C" {
        #[link_name = "_EMBED_ASAR_INTEGRITY"]
        static START: [u8; 0];
    }
```

Removing the unnecessary `extern "C"` resolved the issue.
