### ISSUE TITLE
rustdoc doc(cfg) rendering gets ugly with long cfg expressions

### ISSUE THREAD

**Issue by jplatte** [rust-lang/rust#87957]
I think long cfg expressions should be broken across multiple lines. I saw this cause issues [here](https://docs.rs/ruma/0.3.0/ruma/api/index.html):

![Screenshot_2021-08-12_120327](https://user-images.githubusercontent.com/951129/129178699-296b8db6-6acc-4a26-94df-011aae69578d.png)

**Comment by dns2utf8** [comment]
What if we inserted zero width spaces after the keywords? So after each `or` we insert a zero width space `U+200B` (see the [example in my blog](https://estada.ch/2020/3/30/why-use-shy-when-your-design-breaks/#3)).
Maybe we would have to wrap each name in a `span` too but I would have to experiment a bit.
Then each expression would try to stay as an inline-block and then break the line on the keywords (like `and`, `or`, `not`, ...)

**Comment by jhpratt** [comment]
Maybe it could show "any of"/"all of" on longer chains (say 3+)? I don't think there's a ton that can realistically be done here — a long cfg is going to result in a long doc cfg.

**Comment by GuillaumeGomez** [comment]
There are a lot of things that can be done. For example, for more than 3 items, we could show only the 3 first and show the rest on click. It's mostly about how to display things.

**Comment by jplatte** [comment]
The original case has gotten a lot better, the actual doc string now gets ~60% of the horizontal space rather than ~30%:

![Screenshot_2022-01-02_202521](https://user-images.githubusercontent.com/951129/147887146-4d0237ed-3cf7-4404-a5f5-761e6703a648.png)

**Comment by jplatte** [comment]
I would say rendering has degraded again (even though the documented cfg expressions themselves have become shorter):

![Screenshot 2023-03-12 at 16-10-41 ruma api - Rust](https://user-images.githubusercontent.com/951129/224553793-a22e34bd-536a-492a-8b17-d886c65f87ad.png)
