### ISSUE TITLE
BuildHasher is no longer object safe in 1.55

### ISSUE THREAD

**Issue by tmandry** [rust-lang/rust#87991]
From 1.55 crater run #87749, [log](https://crater-reports.s3.amazonaws.com/beta-1.55-1/beta-2021-08-01/reg/probabilistic_data_structures-0.1.0/log.txt):

```
[INFO] [stdout] error[E0038]: the trait `BuildHasher` cannot be made into an object
[INFO] [stdout]    --> src/pcsa/pcsa.rs:19:27
[INFO] [stdout]     |
[INFO] [stdout] 19  |     pub hasher:       Box<dyn BuildHasher<Hasher = HasherType>>,
[INFO] [stdout]     |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ `BuildHasher` cannot be made into an object
[INFO] [stdout]     |
[INFO] [stdout] note: for a trait to be "object safe" it needs to allow building a vtable to allow the call to be resolvable dynamically; for more information visit <https://doc.rust-lang.org/reference/items/traits.html#object-safety>
```

#86151 added a generic method to the trait, making it no longer object safe.

This only caused one crate in crater to fail, and the source for that crate seems to have been removed from github. Still, I don't think this is technically allowed breakage.

@rustbot modify labels: +regression-from-stable-to-beta -regression-untriaged +T-libs +I-nominated

cc @scottmcm

**Comment by thomcc** [comment]
I think this just needs a `where Self: Sized` on that method, no? Probably was just overlooked during review.
