### ISSUE TITLE
rustdoc: From trait implementation in actix-web 4.0.0-beta.8 is missing from docs

### ISSUE THREAD

**Issue by jplatte** [rust-lang/rust#88007]
[This page](https://docs.rs/actix-web/4.0.0-beta.8/actix_web/struct.Error.html#trait-implementations) is missing any mention of [this trait implementation](https://docs.rs/actix-web/4.0.0-beta.8/src/actix_web/error/error.rs.html#63-70) despite there being no `#[doc(hidden)]` attribute on the impl or any of the involved types. I have no idea what might be going on.

**Comment by Urgau** [comment]
The trait implementation you are referring to is not missing, in fact it's the [latest](https://docs.rs/actix-web/4.0.0-beta.8/actix_web/struct.Error.html#impl-From%3CT%3E) on "Trait Implementations".

**Comment by jplatte** [comment]
Now I'm *really* confused. I went over the page multiple times and found no generic `From` impl except the blanket impl from `std`. I searched for `ResponseError` on the page and it wasn't there in the later parts of the page. I guess I'll close this.

**Comment by jplatte** [comment]
Turned out I linked the wrong error page, the type where I was expecting the impl to show up was `actix_web::error::Error`¹, a.k.a. `actix_http::error::Error`, which is *not* the same thing as `actix_web::Error`. There the impl really doesn't exist, at least in the same file (which has me very confused how the generics work out in practice but I'm okay with that for now).

¹ which also appears twice in the docs! ([here](https://docs.rs/actix-web/4.0.0-beta.8/actix_web/error/index.html#structs))

**Comment by aliemjay** [comment]
It turned out that `actix_web::error::Error` is the same as `actix_web::Error`! The problem is rustdoc links to the wrong page (see my comment on #70380). This got me confused for hours!
