### ISSUE TITLE
Replace ! with ~

### ISSUE THREAD

**Issue by JAicewizard** [rust-lang/rust#88014]
I know this wont make it in, there has been a (MERGED!!!) pull requesting suggesting  ! _over_ ~.

However, its confusing as hell, and there is not even a warning against it. ! is also a logical operator, and why would i intend `!x == y` as "invert x and check if equal to y"? It just makes it impossible to read.

Having this operator be `!` only adds confusion about which operator it is. whereas  `!x == y` is apparently ambiguous, or at least highly unclear about its meaning, `~x == y` is not, and neither is `^x == y`, or  `$x == y`,  or even`\x == y`.

**Comment by jonas-schievink** [comment]
Hi! Additions or changes to the language need to go through our [RFC process](https://github.com/rust-lang/rfcs). Before an RFC is written, the feature can also be discussed in our [internals forum](https://internals.rust-lang.org/) to find other people interested in it.

Closing in favor of an RFC.
