### ISSUE TITLE
rustdoc,  when I use google translate, that translate the doc as well as the code.

### ISSUE THREAD

**Issue by indexroot** [rust-lang/rust#88020]
rustdoc, when I use google translate. 

the  rust  code and  crates name. translated like this:

![image](https://user-images.githubusercontent.com/13267901/129434881-37c4bd7e-a345-4016-b9d1-ab5c807369d8.png)

the rust-book work well.
I found that using `<code></code> `protect code do not translate.

Could you update the rustdoc  using `<code>` tag to fix it?

**Comment by jyn514** [comment]
I don't understand the request, sorry. Are you saying it's incorrect that google translates code blocks, not just the documentation? I don't know how rustdoc could prevent that, we don't control google translate.

**Comment by crlf0710** [comment]
I think he requested that another nesting level element with `code` tag within the currently generated `pre` tag elements.

This also aligns with the behavior at https://spec.commonmark.org/dingus/ .

**Comment by jyn514** [comment]
Ah ok - I'm surprised to hear that since we use pulldown-cmark, which follows the commonmark standard. Someone would have to investigate whether this is specific to rustdoc or whether all tools using pulldown have this issue.

**Comment by Kobzol** [comment]
I think that using `<code>` is a good idea, not just for translation, but generally for the semantic meaning of the HTML. `<pre><code>` is pretty standard HTML for code blocks.

`pulldown-cmark` [uses `<code>`](https://github.com/raphlinus/pulldown-cmark/blob/master/src/html.rs#L100) and even [rustdoc tests](https://github.com/rust-lang/rust/blob/master/src/librustdoc/html/highlight/tests.rs#L20) use it. But `rustdoc` currently only emits `<pre>`. I'll try to change it.

@rustbot claim
