### ISSUE TITLE
Invalid font icon for unstable API message

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/rust#88027]
The unicode character hasn't been changed in ages but we made some changes into fonts recently so the issue might come from there. The issue:

![Screenshot from 2021-08-14 14-41-14](https://user-images.githubusercontent.com/3050060/129446679-0041fe4d-7fb6-44b6-9a68-0add636f2453.png)

It should look like a microscope, not a screen.

**Comment by lolbinarycat** [comment]
triage: fixed, regression test is impossible, closing

![Image](https://github.com/user-attachments/assets/9ea7efb2-dba7-4b7b-9298-858a5205017e)
