### ISSUE TITLE
Doctests don't run on nonexported `macro_rules!` macros

### ISSUE THREAD

**Issue by inquisitivecrystal** [rust-lang/rust#88038]
At present, doctests aren't run on `macro_rules!` macros that are not annotated with `#[macro_export]`. After #88019, it will become possible to fix this problem. However, doing so will cause tests to run that were skipped previously to run, which will likely cause test failures and may mess up people's CI. It might be helpful to provide some form of warning period first.

The relevant code is here:
https://github.com/rust-lang/rust/blob/5eacec9ec7e112a0de1011519a57c45586d58414/src/librustdoc/doctest.rs#L1175-L1184

Fixing this issue technically just requires removing that special case. However, things are complicated by the fact that this will cause people's tests to suddenly fail. I'm not really sure how we should handle that. @jyn514, do you have any ideas?

**Comment by jyn514** [comment]
See also https://rust-lang.zulipchat.com/#narrow/stream/266220-rustdoc/topic/.E2.9C.94.20Doctests.20on.20private.20macros.

**Comment by jyn514** [comment]
I think we should just change this; it's no different than https://github.com/rust-lang/rust/pull/66059 in that the code was already broken before and we just didn't happen to run it. If you're really worried we can do a crater run but I would honestly be ok with just landing this.

**Comment by jyn514** [comment]
Looks like https://github.com/rust-lang/rust/pull/88019 accidentally prevented these doctests from being run even if `--document-private-items` is passed :(

**Comment by cuviper** [comment]
FYI, rayon has an internal macro with an example that wasn't ready to be treated as a test:
https://github.com/rayon-rs/rayon/blob/9dc52d76b12f3da13b87dd509ff29a801177b8d3/src/delegate.rs#L14-L19

... discovered by failing in a [CI run](https://github.com/rayon-rs/rayon/runs/6414739412?check_suite_focus=true).

**Comment by cuviper** [comment]
Hmm, I'm not even sure how to turn that into a working doctest, because the macro isn't exported.

The `ignore(cannot-test-this-because-non-exported-macro)` in #96630 is also telling -- then what's the point?
