### ISSUE TITLE
`T: TraitA` doesn't coerce to `impl TraitA` and error messages could explain it better

### ISSUE THREAD

**Issue by CPerezz** [rust-lang/rust#88035]
**Rustc version: rustc 1.56.0-nightly (ae90dcf02 2021-08-09)**
**`uname -a => Linux arch 5.12.2-arch1-1`**

Given the following Rust code [playground link here](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=a5947dd9634030222b10b858942de3f4):

```rust
use std::collections::BinaryHeap;
use std::iter::IntoIterator;

pub trait TraitA where
    Self: Sized + Ord + PartialOrd,{}

pub enum Target {
    Stack, Memory, Storage
}

#[derive(Debug, Clone)]
struct OperationContainer<T: TraitA> {
    memory: BinaryHeap<T>,
    stack: BinaryHeap<T>,
    storage: BinaryHeap<T>,
}

impl<T: TraitA> OperationContainer<T> {
    pub fn into_inner(&self, target: Target) -> &BinaryHeap<impl TraitA> {
        match target {
            Target::Memory => &self.memory,
            Target::Stack => &self.stack,
            Target::Storage => &self.storage,
        }
    }
    pub fn sorted_ops(&self, target: Target) -> impl IntoIterator<Item = T> {
        self.into_inner(target).into_sorted_vec()
    }
}
```

The current output is:

```
 Compiling playground v0.0.1 (/playground)
error[E0271]: type mismatch resolving `<Vec<impl TraitA> as IntoIterator>::Item == T`
  --> src/lib.rs:26:49
   |
18 | impl<T: TraitA> OperationContainer<T> {
   |      - this type parameter
...
26 |     pub fn sorted_ops(&self, target: Target) -> impl IntoIterator<Item = T> {
   |                                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected type parameter `T`, found opaque type
   |
   = note: expected type parameter `T`
                        found type `impl TraitA`
   = help: type parameters must be constrained to match other types
   = note: for more information, visit https://doc.rust-lang.org/book/ch10-02-traits.html#traits-as-parameters

For more information about this error, try `rustc --explain E0271`.
error: could not compile `playground` due to previous error
```

First of all, I ignore the internals of the compiler and the trait system in this regard. But I would expect `impl TraitA` to be able to coerce to `T` in this example and viceversa.

Anyway, assumming that this coercion is not possible or it doesn't make sense for some reason, the error message should at least explain this a bit better maybe.
Since from a user perspective, `impl TraitA` is the same as writing `T` (ignoring the edition/convention mixure).

So if coercion between these two expressions is not going to happen or doesn't make sense, I would at least add into the error explanation, the fact that since coercion is not possible/due to convention/syntax mixture, you should either use `impl TRAIT` or `T: TRAIT` everywhere, but not mix them.

**Comment by jonas-schievink** [comment]
Sounds like you're looking for the opposite operation here? You have an opaque `impl TraitA` type, but the method signature specifies `Item = T`.

**Comment by nbdd0121** [comment]
The error message seems reasonable to me, since `impl TraitA` isn't `T`.

**Comment by CPerezz** [comment]
I raised this since from a user perspective, even the syntax is different, both things refer to "An object that implements `Trait A`" therefore, even if there's no coercion between both things, I would expect a slightly different explanation since for me, both things should refer to the same.

> The error message seems reasonable to me, since impl TraitA isn't T.

But internally for the compiler, even if the syntax is different, the thing that references is the same. Also if vtables need to be built or any other process needs to be performed, I presume that internally will do it in the same way for `impl TraitA` and `T: TraitA`.

**Comment by nbdd0121** [comment]
`impl Trait` can be any type that implements `TraitA`, while `T` is a specific generic parameter, with a known bound that `T: TraitA`. So clearly it's invalid to convert `impl Trait` to `T`.

"The `impl Trait` is a sugar of <T: Trait>" analogy only applies when `impl Trait` is in argument position, but not in return position.

**Comment by CPerezz** [comment]
That makes it clear for me, thanks @nbdd0121. Is there any place I can read more/check why this only works in argument positions but not in return ones?

Closing this issue also.

**Comment by nbdd0121** [comment]
You can check out [RFC 1522](https://rust-lang.github.io/rfcs/1522-conservative-impl-trait.html) and [RFC 1951](https://rust-lang.github.io/rfcs/1951-expand-impl-trait.html).
