### ISSUE TITLE
LLVM crash: Basic Block does not have terminator!

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust#88043]
The following is minimized from https://crates.io/crates/lalrpop, which is regressed as of nightly-2021-08-15.

```rust
fn bump() -> Option<usize> {
    unreachable!()
}

fn take_until(terminate: impl Fn() -> bool) {
    loop {
        if terminate() {
            return;
        } else {
            bump();
        }
    }
}

fn main() {
    take_until(|| true);
}
```

```console
$ rustc +nightly-2021-08-14 main.rs
$ ./main
$ # :)

$ rustc +nightly-2021-08-15 main.rs
Basic Block in function '_ZN4main10take_until17h0067b8a660429bc9E' does not have terminator!
label %3
in function _ZN4main10take_until17h0067b8a660429bc9E
LLVM ERROR: Broken function found, compilation aborted!

$ rustc +nightly-2021-08-15 --version --verbose
rustc 1.56.0-nightly (8007b506a 2021-08-14)
binary: rustc
commit-hash: 8007b506ac5da629f223b755f5a5391edd5f6d01
commit-date: 2021-08-14
host: x86_64-unknown-linux-gnu
release: 1.56.0-nightly
LLVM version: 12.0.1
```

**Comment by dtolnay** [comment]
Relevant commit range is https://github.com/rust-lang/rust/compare/5a19ffe1c2b99d9e09706cc286aad1ec0868eddb...8007b506ac5da629f223b755f5a5391edd5f6d01. Of the 9 landed PRs, the ones that look potentially relevant to codegen are #85020 and #83417. @lrh2000 @tmandry @erikdesjardins @oli-obk

**Comment by dtolnay** [comment]
I tried all the merge commits in order of merge:

- d0a10b205608ad91280fb10495c18eb1c9110c89: pass
- 32c3f2d6ca1c5271836041ca7ca9b45042d8addd: pass
- c6094fc7b9981d755abeb8c0e866a0f6315b3ec3: pass
- 99efc51dae1dbe9d741707a7ddef84c29e654df5: pass
- fa2692990c05652c7823c8d2afae501a00a69050: pass
- 136eaa1b25d13635b773a481ecab61a3162cb627: pass
- a59e8853148c6a26ed583cccd0f1c3fc50444c9c: pass
- e55c13e1099b78b1a485202fabc9c1b10b1f1d15: pass
- 8007b506ac5da629f223b755f5a5391edd5f6d01: regressed

so that narrows this down to #83417 (@erikdesjardins @oli-obk).

**Comment by Aaron1011** [comment]
This passes under Miri, so I suspect that we've exposed an LLVM bug.

**Comment by dtolnay** [comment]
Not sure it's an LLVM bug because it seems the IR is broken even before any LLVM passes. I tried:

```console
$ rustc +nightly-2021-08-14 -Cno-prepopulate-passes --emit=llvm-ir src/main.rs -o before.ll
$ opt before.ll  # ok

$ rustc +nightly-2021-08-15 -Cno-prepopulate-passes --emit=llvm-ir src/main.rs -o after.ll
$ opt after.ll
opt: after.ll:287:1: error: expected instruction opcode
bb1:                                              ; preds = %bb0
^
```

Before: https://paste.rs/o7U
After: https://paste.rs/ftk
Diff: https://paste.rs/gWL.diff

The `main::take_until` looks like legitimately broken input IR. Notice the extractvalue insts relocated from the front of bb4 to the end of bb0 (invalidly after the terminator).

What in LLVM is actually running during a -Cno-prepopulate-passes build?

**Comment by oli-obk** [comment]
I think we should do a quick revert and then figure this out without any pressure

**Comment by oli-obk** [comment]
the mir changes are 

```diff
    bb2: {
-        _0 = const ();                   // scope 0 at src/main.rs:8:13: 8:19
-        drop(_1) -> bb5;                 // scope 0 at src/main.rs:13:1: 13:2
+        drop(_1) -> bb4;                 // scope 0 at src/main.rs:13:1: 13:2
    }

    bb3: {
-        _5 = bump() -> [return: bb4, unwind: bb6]; // scope 0 at src/main.rs:10:13: 10:19
+        _5 = bump() -> [return: bb0, unwind: bb5]; // scope 0 at src/main.rs:10:13: 10:19
                                         // mir::Constant
                                         // + span: src/main.rs:10:13: 10:17
                                         // + literal: Const { ty: fn() -> std::option::Option<usize> {bump}, val: Value(Scalar(<ZST>)) }
-    }
-
-    bb4: {
-        goto -> bb0;                     // scope 0 at src/main.rs:6:5: 12:6
    }
```

that seems totally reasonable, so we need to check what codegen_llvm makes of it

**Comment by oli-obk** [comment]
I wonder why the goto collapse only happens if the zst assignment is eliminated. it seems like we need to preserve bb4 in mir or inject it in codegen_llvm, but first we should find out why the goto collapse is happening at all

**Comment by tmiasko** [comment]
There are no control-flow simplification passes after removal of dead local variables, which is why it didn't happen so far. Still, it seems a bit surprising it wasn't reported earlier:

```rust
pub fn f(_a: Option<String>) -> Option<u32> {
    loop {
        f(None);
        ()
    }
}

fn main() {
    f(None);
}
```

```console
$ rustc +stable a.rs
Basic Block in function '_ZN1a1f17h9901a33e93da62b7E' does not have terminator!
label %4
in function _ZN1a1f17h9901a33e93da62b7E
LLVM ERROR: Broken function found, compilation aborted!
```

Adding a new cleanup pass before codegen would be one way to address this.

**Comment by erikdesjardins** [comment]
I swear half of my PRs break the compiler 😅

I'm excited for what bugs arise when we start using undef for uninitialized consts...

Revert PR: https://github.com/rust-lang/rust/pull/88056

**Comment by apiraino** [comment]
Assigning priority as discussed in the [Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2388043.20LLVM.20crash.3A.20Basic.20Block.20does.20not.20have.20terminator!) of the Prioritization Working Group.

@rustbot label -I-prioritize +P-critical

**Comment by oli-obk** [comment]
The issue was not fixed, it is an LLVM crash on stable as https://github.com/rust-lang/rust/issues/88043#issuecomment-899051774 shows

**Comment by dtolnay** [comment]
Relabeling regression because https://github.com/rust-lang/rust/issues/88043#issuecomment-899051774 worked in 1.51.0. It bisects to nightly-2021-03-02 (https://github.com/rust-lang/rust/compare/e37a13cc3594004663738bd18d8100e6db9666cf...4f20caa6258d4c74ce6b316fd347e3efe81cf557).

**Comment by dtolnay** [comment]
https://github.com/rust-lang/rust/pull/78360 is the only codegen change in that nightly. @tmiasko @wesleywiser

**Comment by wesleywiser** [comment]
Reopening to track the stable-to-stable regression.

**Comment by wesleywiser** [comment]
Backport was merged.
