### ISSUE TITLE
Trailing semicolon design decision to be made optional

### ISSUE THREAD

**Issue by rajatpundir** [rust-lang/rust#88063]
I'm new to Rust but now know a thing or two about ownership and lifecycle.

I am puzzled by the design to skip the semicolon on last expression but not on others. At a glance, this seemed to me same as how the people in Lisp land love their parenthesis. 

On the JVM side, I have used Kotlin and it's  a really expressive language as powerful as rust when you consider everything to be an expression. Semicolon were optional there, how come we could not figure a way around them here? Surely if we should enjoy fearless concurrency, we should also get to enjoy a less boilerplate-y necessity.

In this issue, I express my distaste at this syntax decision in a modern language and request semicolons to be made optional in a future release while maintaining backward compatibility.

**Comment by jonas-schievink** [comment]
Hi! Additions or changes to the language need to go through our [RFC process](https://github.com/rust-lang/rfcs). Before an RFC is written, the feature can also be discussed in our [internals forum](https://internals.rust-lang.org/) to find other people interested in it.

Closing in favor of an RFC.

**Comment by rajatpundir** [comment]
It's fine. The issue is only symbolic.
