### ISSUE TITLE
Range pattern does not perform type inference

### ISSUE THREAD

**Issue by nbdd0121** [rust-lang/rust#88074]
```rust
trait Zero {
    const ZERO: Self;
}

impl Zero for i32 {
    const ZERO: Self = 0;
}

fn foo() {
    match 1 {
        Zero::ZERO ..= 1 => {},
        _ => {},
    }
}
```

currently throws E0029:

```
error[E0029]: only `char` and numeric types are allowed in range patterns
  --> src/lib.rs:11:9
   |
11 |         Zero::ZERO ..= 1 => {},
   |         ^^^^^^^^^^     - this is of type `{integer}`
   |         |
   |         this is of type `_` but it should be `char` or numeric

For more information about this error, try `rustc --explain E0029`.
```

while it should infer the constant to be `<i32 as Zero>::ZERO`.

@rustbot modify labels: +T-compiler +A-inference 
@rustbot claim

**Comment by jyn514** [comment]
I don't think this is incorrect. `Zero::ZERO` doesn't refer to a specific constant, it's just an abstract associated constant. `i32::ZERO` works fine.

**Comment by jyn514** [comment]
Hmm, `let x: i32 = Zero::ZERO` does work, though. But `let x = Zero::ZERO` does not. It does seem inconsistent that `let x: i32 = Zero::ZERO` works and `Zero::ZERO ..= 1_i32` doesn't.

**Comment by nbdd0121** [comment]
`Zero::ZERO` is just `<_ as Zero>::ZERO`, so type inference should kick in here. In fact you can write
```rust
match 1 {
    Zero::ZERO => {},
    _ => {},
}
```
and inference works just fine. The issue only happens when used in range patterns.

I am prototyping a fix right now and it seems that the issue is just that E0029 check happens a little bit early (before unification is performed).
