### ISSUE TITLE
Will rust get more and more bloated?

### ISSUE THREAD

**Issue by wujilingfeng** [rust-lang/rust#88078]
Hello!
I want to learn rust because It's like haskell.
However,I noticed that rust has a large number of developers and the iteration speed is very fast.
I wonder will rust get more and more bloated? 
Will more and more engineering features be added?

**Comment by jonas-schievink** [comment]
Hi! This issue tracker is mainly meant for bug reports and concrete, small feature requests. Questions like this are better asked in the user forum at https://users.rust-lang.org/ or on [one of the chat platforms](https://www.rust-lang.org/community) used by the Rust community.
