### ISSUE TITLE
non_fmt_panics suggestion applied many times when it appears inside a macro_rules

### ISSUE THREAD

**Issue by m-ou-se** [rust-lang/rust#88115]
This showed up in a small crater run for the 2021 edition migrations:

  - https://crater-reports.s3.amazonaws.com/pr-87190-2/try%23d8627d19850b63702b76089d7b055730e9ddca14/reg/image-0.23.14/log.txt
  - https://crater-reports.s3.amazonaws.com/pr-87190-2/try%23d8627d19850b63702b76089d7b055730e9ddca14/reg/mockers-0.21.0/log.txt
  
The suggestion gets applied for every usage of the macro, resulting in:
```rust
                 panic!("{}", "{}", "{}", "{}", "{}", "{}", "{}", "{}", err)
```

**Comment by m-ou-se** [comment]
@estebank  Is this a known problem with suggestions inside macro_rules definitions?

**Comment by estebank** [comment]
Oh, that definitely looks like an outstanding bug :-/

**Comment by m-ou-se** [comment]
That other issue looks confusing because the surrounding `assert!(` and `)` are on separate lines:

```rust
                assert!(
                    alpha != 254 && alpha != 253,
                    format!("alpha value: {}, {:?}", alpha, filter)
                );
```

but the error is correct.

(It could suggest removing `format!(` and `)` though instead of adding `"{}", ` though, like the non_fmt_panics lint does.)

**Comment by m-ou-se** [comment]
> Oh, that definitely looks like a previously existing outstanding bug :-/

@estebank So I assume there's no existing mechanism for 'deduplicating' suggestions like that, such that they only appear on the first macro invocation or something? :(

**Comment by estebank** [comment]
I believe we have a mechanism to do that, but it might be relying on the `Span` information, and because these spans have different provenance they are considered "different". We could maybe make `rustfix` smarter here instead :-/

What's the timeline for the edition?

**Comment by m-ou-se** [comment]
> What's the timeline for the edition?

We have 17 days until 1.56 branches off. In 10'000 crates we only ran into this twice though, so it doesn't seem like a big issue; definitely not a blocker.

**Comment by m-ou-se** [comment]
It seems to work fine though when the suggestion is to replace `panic!` by `panic_any`, even if it's duplicated six times. I'm guessing whatever makes that work isn't working for inserting `"{}", `, because it's inserting (replacing an empty span) rather than replacing.

**Comment by m-ou-se** [comment]
https://twitter.com/artichokeruby/status/1427720656817332227

> This same thing happened with 2018 edition fix ups for anonymous lifetime parameters for Debug impls defined in macros.

**Comment by estebank** [comment]
Less than ideal, but I think it is acceptable to go out of the door with this unaddressed. We should fix it soonish regardless.

**Comment by m-ou-se** [comment]
This is an instance of https://github.com/rust-lang/rustfix/issues/198.

Closing this as duplicate.
