### ISSUE TITLE
&mut self to &mut Trait moves self

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang/rust#8813]
This code shows some odd behavior:

```rust
trait A {}
struct B;
impl A for B {}

fn foo(_: &mut A) {}

impl B {
    fn good(&mut self) {
        self.foo();
        foo(&mut *self as &mut A);
        self.foo();
    }

    fn bad(&mut self) {
        self.foo();
        foo(self as &mut A);
        self.foo();
    }

    fn foo(&mut self) {}
}

fn main() {}
```

Because `good` works, I would expect `bad` to work as well.

```
$ rustc test.rs
test.rs:17:8: 17:13 error: use of moved value: `self`
test.rs:17         self.foo();
                   ^~~~~
test.rs:16:12: 16:19 note: `self` moved here because it has type `&mut B`, 
which is non-copyable (perhaps you meant to use clone()?)
test.rs:16         foo(self as &mut A);
                       ^~~~~~~
error: aborting due to previous error
```
cc @nikomatsakis

**Comment by steveklabnik** [comment]
We no longer auto-borrow in this situation, so I think that this is invalid. @nikomatsakis @alexcrichton ?

**Comment by nikomatsakis** [comment]
I think this is still as true as it ever was. In general, we aggressively "reborrow" all `&mut` values so as to hide the fact that they are affine (that is, they move by default). But in this particular case of doing `x as &mut Foo`, we do not reborrow, so the value `x` gets consumed. This is not exactly a *bug* but it is suboptimal. I consider it an enhancement.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#800
