### ISSUE TITLE
Rust release 1.55 has a future date

### ISSUE THREAD

**Issue by wykurz** [rust-lang/rust#88162]
The RELEASES.md lists release 1.55 with date 2021-09-09, however it is 2021-08-19. I'm assuming this is a typo and the release should have been listed with 2021-08-09?

**Comment by adamgemmell** [comment]
1.54 is the current stable version. 1.55 is scheduled for release on that date: https://forge.rust-lang.org/

**Comment by Mark-Simulacrum** [comment]
Closing -- this is indeed expected.
