### ISSUE TITLE
Invariant lifetime incorrectly extended until value is dropped

### ISSUE THREAD

**Issue by Cassy343** [rust-lang/rust#88185]
I tried this code:

```rust
#![feature(dropck_eyepatch)]

use std::{
    cell::Cell,
    marker::PhantomData
};

struct Dummy<T> {
    _marker: PhantomData<fn() -> T>
}

impl<T> Dummy<T> {
    fn new() -> Self {
        Self {
            _marker: PhantomData
        }
    }

    fn none(&self) -> Option<T> {
        None
    }
}

unsafe impl<#[may_dangle] T> Drop for Dummy<T> {
    fn drop(&mut self) {
        // Do nothing
    }
}

fn main() {
    let mut s = "str".to_owned();
    let dummy = Dummy::new();

    #[allow(unused_assignments, unused_variables)]
    {
        // This initial value defines some lifetime `'a` for the immutable borrow, and the cell
        // makes it invariant
        let mut borrow = Some(Cell::new(&s));

        // Force `dummy` to adopt the type `Dummy<Cell<&'a String>>`
        borrow = dummy.none();
    }

    // Error on this line
    s.push('!');

    // Force `dummy` to be dropped here
    drop(dummy);
}
```

I expected to see this happen:
The above code theoretically should compile because there is no feasible way that `Dummy` could "use" a `T` when it's dropped. First of all, `Dummy` only contains a `fn() -> T` as far as the type system is concerned. Second, its drop implementation states that `T` may dangle. Given these two facts, the compiler should be able to shorten the lifetime `'a` since dropping a `Dummy` will never access a `T` nor drop a `T`.

Instead, this happened: the code did not compile due to the following error:
```rs
error[E0502]: cannot borrow `s` as mutable because it is also borrowed as immutable
   --> src/main.rs:157:5
    |
150 |         let mut borrow = Some(Cell::new(&s));
    |                                         -- immutable borrow occurs here
...
157 |     s.push('!');
    |     ^^^^^^^^^^^ mutable borrow occurs here
...
160 |     drop(dummy);
    |          ----- immutable borrow later used here

For more information about this error, try `rustc --explain E0502`.
error: could not compile `rusttests` due to previous error
```

I encountered this error when originally filing an issue about dropping `std::iter::Empty` causing a similar error, however when I tried to create my own version of `Empty`, I encountered this error which seemed more concerning.

This error only happens if `dummy` is dropped after `s.push('!');`. The obvious fix in this example is to remove the explicit drop, however this error present the more general question of whether or not a type which contains a `T: 'a` should extend `'a` to the point where it is dropped even if it does not use or drop a `T`.

### Meta

`rustc --version --verbose`:
```
rustc 1.56.0-nightly (0fa319039 2021-08-12)
binary: rustc
commit-hash: 0fa3190394475a84360b34e074e719d519bc40f1
commit-date: 2021-08-12
host: x86_64-unknown-linux-gnu
release: 1.56.0-nightly
LLVM version: 12.0.1
```

**Comment by SkiFire13** [comment]
I think this is expected: `drop` is a function like any other so for the borrow checker `drop(dummy)` counts as an use. If you remove it and instead log when `Drop::drop` is called you'll see that dummy is still dropped after that `push`

**Comment by Cassy343** [comment]
That makes sense -- I often forget that `drop` has no "magical" compiler-added semantics around it. Thanks for pointing that out. I'll close the issue.
