### ISSUE TITLE
Random STATUS_ACCESS_VIOLATION when compiling release builds (2021-08-11 nightly)

### ISSUE THREAD

**Issue by Rantanen** [rust-lang/rust#88199]
### Code

This is probably going to be a bit painful. The crate I'm compiling is ~6000 lines of code and the issue reproduces randomly (twice today, three or so times in total) so finding a minimal reproduction case is going to be difficult.

### Meta

`rustc --version --verbose`:
```
rustc 1.56.0-nightly (ccffcafd5 2021-08-11)
binary: rustc
commit-hash: ccffcafd55e58f769d4b0efc0064bf65e76998e4
commit-date: 2021-08-11
host: x86_64-pc-windows-msvc
release: 1.56.0-nightly
LLVM version: 12.0.1
```

### Error output

```
process didn't exit successfully: `rustc --crate-name symbolserver --edition=2018 src\main.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type bin --emit=dep-info,link -C opt-level=3 -C embed-bitcode=no -C metadata=cca32c06f70a4d9f --out-dir C:\Dev\Projects\symbolserver\target\release\deps -L dependency=C:\Dev\Projects\symbolserver\target\release\deps --extern anyhow=C:\Dev\Projects\symbolserver\target\release\deps\libanyhow-c05e30cd2d1a9e1a.rlib --extern bitvec=C:\Dev\Projects\symbolserver\target\release\deps\libbitvec-7df6070a7974a691.rlib --extern byteorder=C:\Dev\Projects\symbolserver\target\release\deps\libbyteorder-adceb9daa95dda5b.rlib --extern clap=C:\Dev\Projects\symbolserver\target\release\deps\libclap-f33b7e520a654415.rlib --extern diesel=C:\Dev\Projects\symbolserver\target\release\deps\libdiesel-b0ef313c8f3d58d1.rlib --extern diesel_migrations=C:\Dev\Projects\symbolserver\target\release\deps\libdiesel_migrations-98b9cc3e0fac4702.rlib --extern env_logger=C:\Dev\Projects\symbolserver\target\release\deps\libenv_logger-012330fddd281758.rlib --extern glob=C:\Dev\Projects\symbolserver\target\release\deps\libglob-ef8e26e6870c4b6c.rlib --extern hex=C:\Dev\Projects\symbolserver\target\release\deps\libhex-94affdbd8d2af448.rlib --extern libsqlite3_sys=C:\Dev\Projects\symbolserver\target\release\deps\liblibsqlite3_sys-655ea3151f44514e.rlib --extern log=C:\Dev\Projects\symbolserver\target\release\deps\liblog-d040b434a7962a8f.rlib --extern pdb=C:\Dev\Projects\symbolserver\target\release\deps\libpdb-dd56ed131a8a07af.rlib --extern scroll=C:\Dev\Projects\symbolserver\target\release\deps\libscroll-9cce02060e69a19f.rlib --extern sha1=C:\Dev\Projects\symbolserver\target\release\deps\libsha1-7763d26274f2e3d0.rlib --extern uuid=C:\Dev\Projects\symbolserver\target\release\deps\libuuid-df845306dffc4ba5.rlib -L native=C:\Dev\Projects\symbolserver\target\release\build\libsqlite3-sys-23f491454f7e6f76\out` (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)
```

This is a pure access violation in LLVM which terminates the process. No backtrace caught.

I do have a crash dump though!
[rustc.exe.dmp-2021-08-11.7z](https://jubjubnest.net/~wace/rustc.exe.dmp-2021-08-11.7z) (89.1 MB)

(Seems to be coming from LLVM, so might even be an upstream issue..)

<details><summary><strong>Call stack</strong></summary>
<p>
<pre>
>	rustc_driver-92f21ffebfe36030.dll!llvm::TailCallElimPass::run(class llvm::Function &,class llvm::AnalysisManager<class llvm::Function> &)	Unknown
 	rustc_driver-92f21ffebfe36030.dll!llvm::DomTreeUpdater::~DomTreeUpdater(void)	Unknown
 	rustc_driver-92f21ffebfe36030.dll!llvm::FPPassManager::runOnFunction(class llvm::Function &)	Unknown
 	rustc_driver-92f21ffebfe36030.dll!llvm::initializeDummyCGSCCPassPass(class llvm::PassRegistry &)	Unknown
 	rustc_driver-92f21ffebfe36030.dll!llvm::legacy::PassManagerImpl::run(class llvm::Module &)	Unknown
 	rustc_driver-92f21ffebfe36030.dll!LLVMRunPassManager()	Unknown
 	rustc_driver-92f21ffebfe36030.dll!_ZN18rustc_codegen_llvm4back5write8optimize17he94f1bba6b3976ecE()	Unknown
 	rustc_driver-92f21ffebfe36030.dll!_ZN17rustc_codegen_ssa4back5write17execute_work_item17hc39695cf43101d91E()	Unknown
 	rustc_driver-92f21ffebfe36030.dll!_ZN3std10sys_common9backtrace28__rust_begin_short_backtrace17h1bd00f4a76b305f6E()	Unknown
 	rustc_driver-92f21ffebfe36030.dll!_ZN4core3mem12maybe_uninit20MaybeUninit$LT$T$GT$16assume_init_drop17h8949983fe61687e0E()	Unknown
 	[Inline Frame] std-b0fc3a62aa6278cd.dll!alloc::boxed::impl$44::call_once() Line 1636	Unknown
 	[Inline Frame] std-b0fc3a62aa6278cd.dll!alloc::boxed::impl$44::call_once() Line 1636	Unknown
 	std-b0fc3a62aa6278cd.dll!std::sys::windows::thread::impl$0::new::thread_start() Line 57	Unknown
 	kernel32.dll!BaseThreadInitThunk()	Unknown
 	ntdll.dll!RtlUserThreadStart()	Unknown

</pre>
</p>
</details>

I don't have a need for nightly (was a bit surprised to see I was running that currently!), so I'll upgrade to a newer one and if this still reproduces there, I'll go back to a stable version and see if the problem occurs there.

**Comment by Enselic** [comment]
Triage: Thank you for reporting. Unfortunately it is hard to take action on this issue without a way to reproduce. Can you still reproduce this problem?

**Comment by Rantanen** [comment]
Sorry, no. I haven't touched that project in 2 years and it currently isn't compiling for some reason (probably made some changes two years ago and left it in a state where it didn't compile).

Not sure if you want to keep the issue open. I'm fine with the issue being closed for lack of reproducible example.

**Comment by Enselic** [comment]
Thank you for the update. Let's close. Feel free to reopen if/when you find a step-by-step on how to reproduce.
