### ISSUE TITLE
Broken WASM codegen with u128 and wasm_abi

### ISSUE THREAD

**Issue by kostko** [rust-lang/rust#88207]
It seems that the following code:
```rust
#![feature(wasm_abi)]

#[no_mangle]
pub extern "wasm" fn test() {
    format!("boom: {}", 0u128);
}
```

can result in invalid WASM being generated in case it is compiled with `lto = true`. I've created [a repository with the minimal example](https://github.com/kostko/rust-wasm-u128-fmt-bug) that reproduces the issue when built with (tested on `rustc 1.56.0-nightly (0035d9dce 2021-08-16)`):
```
cargo build --target wasm32-unknown-unknown --release
```

Parsing the generated WASM will produce an error similar to the following:
```
[parse exception: attempted pop from empty stack / beyond block start boundary at 536 (at 0:536)]
Fatal: error parsing wasm
```

Using an argument of type `u64` or disabling `lto` or using the C ABI instead of wasm ABI (which enables LLVM's multivalue feature) works.

### Meta

`rustc --version --verbose`:
```
rustc 1.56.0-nightly (0035d9dce 2021-08-16)
binary: rustc
commit-hash: 0035d9dcecee49d1f7349932bfa52c05a6f83641
commit-date: 2021-08-16
host: x86_64-unknown-linux-gnu
release: 1.56.0-nightly
LLVM version: 12.0.1
```

**Comment by bjorn3** [comment]
`extern "wasm"` has been removed. Can't reproduce with

```shell
echo '#[no_mangle]
pub extern "C" fn test() {
    format!("boom: {}", 0u128);
}' | rustc +nightly - --target wasm32-unknown-unknown --crate-type cdylib -Clto=yes -Copt-level=3
```

**Comment by kostko** [comment]
Yeah as mentioned in the original issue:
> Using an argument of type u64 or disabling lto **or using the C ABI instead** of wasm ABI (which enables LLVM's multivalue feature) works.

If the wasm ABI was removed, then this issue is likely no longer relevant.

**Comment by nikic** [comment]
Right, there should no longer be any way to expose this from Rust anymore. There is an upstream LLVM issue tracking i128 with multi-value here: https://github.com/llvm/llvm-project/issues/98323
