### ISSUE TITLE
Confusing diagnostics on #[derive(X)] when X is imported only as trait

### ISSUE THREAD

**Issue by m-ou-se** [rust-lang/rust#88206]
Reported by @Hoverbear here: https://twitter.com/a_hoverbear/status/1428763621572501507

```rust
use serde::{Deserialize, Serialize};

#[derive(Serialize)]
struct A;
```

Output:
```
error: cannot find derive macro `Serialize` in this scope
 --> src/main.rs:3:10
  |
3 | #[derive(Serialize)]
  |          ^^^^^^^^^

warning: unused import: `serde::Serialize`
 --> src/main.rs:1:5
  |
1 | use serde::Serialize;
  |     ^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default
```

The diagnostics shows that `Serialize` is not found, and then complains that `Serialize` was imported and unused. Confusing.

(Only the trait `Serialize` is imported, not the `Serialize` derive macro, as the `derive` feature wasn't enabled on `serde`.)

**Comment by m-ou-se** [comment]
I have a patch that improves things a bit by adding a note to the error:

```
error: cannot find derive macro `Serialize` in this scope
 --> src/main.rs:3:10
  |
3 | #[derive(Serialize)]
  |          ^^^^^^^^^
  |
note: `Serialize` is imported here, but it is not a derive macro
 --> src/main.rs:1:5
  |
1 | use serde::Serialize;
  |     ^^^^^^^^^^^^^^^^
```

Will clean it up, add some tests, and send the PR later.

**Comment by m-ou-se** [comment]
This adds notes to all 'macro not found' diagnostics where the name is in scope in some other namespace, or as another type of macro: https://github.com/rust-lang/rust/pull/88232

**Comment by patientplatypus6** [comment]
I might suggest that you include something along the lines of 

"are you sure that you imported the derive package of Derive in Cargo.toml?"

https://serde.rs/derive.html
