### ISSUE TITLE
Unary plus gives suboptimal parse error

### ISSUE THREAD

**Issue by CAD97** [rust-lang/rust#88276]
Given the [following code](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=9d47f8301f8c0e7bbb81a74492c230b0): 

```rust
fn main() {
    let x = +1;
}
```

The current output is:

```
error: expected expression, found `+`
 --> src/main.rs:2:13
  |
2 |     let x = +1;
  |             ^ expected expression
```

Ideally, if we want to continue rejecting unary plus on number literals, the parser should recover the unexpected unary plus, and the output should look somewhat like:

```
error: leading `+` on numeric literals is not supported
 --> src/main.rs:2:13
  |
2 |     let x = +1;
  |             ^ unexpected `+`
  = help: remove it; the unsigned literal is positive and may still be used for a signed type
```

Tested on 1.56.0-nightly (2021-08-22 af140757b4cb1a60d107)

**Comment by theo-lw** [comment]
Working on this @rustbot claim.

**Comment by camelid** [comment]
Closing now that #88553 has been merged.
