### ISSUE TITLE
Incorrect trait bounds check

### ISSUE THREAD

**Issue by ivan770** [rust-lang/rust#88287]
I tried this code:
https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=d372b241527aa63df526377bfc532b31

I expected to see this happen: It compiles or gives me a detailed error.

Instead, this happened: Compiler suggests to add an already existing trait bound. Adding it one more time leads to compiler suggesting adding it once more and so on.

While the code example uses GAT and TAIT, I'm not entirely sure both of those features are required to reproduce the issue.

@rustbot label +T-compiler +F-type_alias_impl_trait +F-generic_associated_types +A-traits +requires-nightly

**Comment by JohnTitor** [comment]
This compiles fine on the latest nightly, perhaps related to #88405.
