### ISSUE TITLE
What is the stability guarantee of `#[track_caller]` locations?

### ISSUE THREAD

**Issue by scottmcm** [rust-lang/rust#88302]
This is inspired by https://github.com/rust-lang/rust/issues/87401

The general version of that bug is that any time a call to a trait method that might have had `#[track_caller]` in its `impl` is moved or wrapped, then the location can change.  When, if ever, is a change to a location a breaking change?

**Comment by m-ou-se** [comment]
We discussed this in the library api meeting just now. We agreed that `#[track_caller]` is *not* a promise that that attribute will stay there in the future. We can imagine such a promise might be made in the public documentation of a function, but that's not an implicit guarantee.

`#[track_caller]` is an important part of the quality of the standard library. Not having it in certain situations might be bad, but it's not a stability guarantee by itself.

**Comment by scottmcm** [comment]
Given that this is answered in https://github.com/rust-lang/rust/issues/88302#issuecomment-910614687, I'll close it.
