### ISSUE TITLE
"jump to definition" feature is generating links to private item documentation pages

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/rust#88304]
More information on https://github.com/rust-lang/rust/pull/88292

**Comment by jyn514** [comment]
To be clear, I'm not actually sure that's a private link, I didn't look at it in detail. It might just be doc(hidden) or something.

**Comment by GuillaumeGomez** [comment]
I didn't either. Just that most of weird things happening are in `os`.
