### ISSUE TITLE
$HOME/.cargo/env can‘t run in path "$home/.cargo"

### ISSUE THREAD

**Issue by lougxing** [rust-lang/rust#88376]
`

lougxing@local:~/.cargo$ pwd
/home/lougxing/.cargo
lougxing@local:~/.cargo$ .  env
-bash: .: /usr/bin/env: cannot execute binary file
lougxing@local:~/.cargo$

/usr/bin/env  and .cargo/env are conflict.

Windows Wsl2;

lougxing@local:~/.cargo$ cat /etc/issue
Ubuntu 20.04.3 LTS \n \l

`

**Comment by Enselic** [comment]
Triage: No follow-up to the question, so let's close. It probably sorted itself out.
