### ISSUE TITLE
rustdoc: Ayu syntax highlighting regression

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#88415]
My guess is that the yellow inline code style is incorrectly being applied to code blocks too.

### Nightly (incorrect)

![image](https://user-images.githubusercontent.com/37223377/131204416-46bf2a26-34e0-4cac-8c5d-a30b481a5db4.png)

### Beta & stable (correct)

![image](https://user-images.githubusercontent.com/37223377/131204431-6b2af605-b630-4048-b15a-3d1c7c54db76.png)

**Comment by camelid** [comment]
cc @GuillaumeGomez since you're knowledgeable about rustdoc's CSS

**Comment by GuillaumeGomez** [comment]
I'll send a fix shortly.

**Comment by camelid** [comment]
#88093 looks to be the likely cause.

searched nightlies: from nightly-2021-07-01 to nightly-2021-08-25
regressed nightly: nightly-2021-08-20
searched commits: from https://github.com/rust-lang/rust/commit/3d0774d0dc98084d25d95cc1909a8051ebbd9cb1 to https://github.com/rust-lang/rust/commit/6d64f7f695943541fe12bb960971403f440d7225
regressed commit: https://github.com/rust-lang/rust/commit/6d64f7f695943541fe12bb960971403f440d7225

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.0</summary>


Host triple: x86_64-apple-darwin
Reproduce with:
```bash
cargo bisect-rustc --start=2021-07-01 --end=2021-08-25 --preserve --prompt -- doc --open 
```
</details>
