### ISSUE TITLE
Windows [UNC] Path substitutions on WOW

### ISSUE THREAD

**Issue by C0D3-M4513R** [rust-lang/rust#88443]
I tried this code:
Important is, that this is run, as x86, on a x64 install (this process needs? to run under WOW), of Windows. Otherwise, this will work, as expected. I speculate further, that this is a problem, with (at least) every dll present in `c:\Windows\SYSWOW64`.
I tried running this code with `cargo +nightly-i686 run` and `cargo +stable-i686 run`

```rust
fn main() {
    let path = "\\\\?\\C:\\Windows\\System32\\kernel32.dll";
    let winpath_tmp =std::fs::canonicalize(path).unwrap();
    let winpath=winpath_tmp.to_str().unwrap();
    assert_eq!(path,winpath);
}
```

I expected to see this happen: 

I expected, that with the UNC path would not change. Especially, since, the link in the doc, of `std::fs::canonicalize`, says:
> For file I/O, the "\\?\" prefix to a path string tells the Windows APIs to disable all string parsing and to send the string that follows it straight to the file system.

Instead, this happened: 

Instead Windows, or rust changed the Path, upon parsing it. Reading also yields the `SYSWOW64/kernel.dll
 file contents.

This also happens, with paths, that just start with `C:\`.
### Meta

`rustc --version --verbose`:
```
rustc 1.54.0 (a178d0322 2021-07-26)
binary: rustc
commit-hash: a178d0322ce20e33eac124758e837cbd80a6f633
commit-date: 2021-07-26
host: x86_64-pc-windows-msvc
release: 1.54.0
LLVM version: 12.0.1
```

`rustc +stable-i686 --version --verbose`
```
rustc 1.54.0 (a178d0322 2021-07-26)
binary: rustc
commit-hash: a178d0322ce20e33eac124758e837cbd80a6f633
commit-date: 2021-07-26
host: i686-pc-windows-msvc
release: 1.54.0
LLVM version: 12.0.1
```

`rustc +nightly-i686 --version --verbose`
```
rustc 1.56.0-nightly (ac50a5335 2021-08-27)
binary: rustc
commit-hash: ac50a53359328a5d7f2f558833e63d59d372e4f7
commit-date: 2021-08-27
host: i686-pc-windows-msvc
release: 1.56.0-nightly
LLVM version: 13.0.0
```

<details><summary>Backtrace</summary>
<p>

```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `"\\\\?\\C:\\Windows\\System32\\kernel32.dll"`,
 right: `"\\\\?\\C:\\Windows\\SysWOW64\\kernel32.dll"`', src\main.rs:5:5
stack backtrace:
   0:   0xa16cea - core::fmt::write
                       at /rustc/ac50a53359328a5d7f2f558833e63d59d372e4f7\/library\core\src\fmt\mod.rs:1150
   1:   0xa062c1 - std::io::Write::write_fmt<std::sys::windows::stdio::Stderr>
                       at /rustc/ac50a53359328a5d7f2f558833e63d59d372e4f7\/library\std\src\io\mod.rs:1667
   2:   0xa09b28 - std::sys_common::backtrace::_print
                       at /rustc/ac50a53359328a5d7f2f558833e63d59d372e4f7\/library\std\src\sys_common\backtrace.rs:49
   3:   0xa09b28 - std::sys_common::backtrace::print
                       at /rustc/ac50a53359328a5d7f2f558833e63d59d372e4f7\/library\std\src\sys_common\backtrace.rs:36
   4:   0xa09b28 - std::panicking::default_hook::closure$1
                       at /rustc/ac50a53359328a5d7f2f558833e63d59d372e4f7\/library\std\src\panicking.rs:210
   5:   0xa096c3 - std::panicking::default_hook
                       at /rustc/ac50a53359328a5d7f2f558833e63d59d372e4f7\/library\std\src\panicking.rs:227
   6:   0xa0a10e - std::panicking::rust_panic_with_hook
                       at /rustc/ac50a53359328a5d7f2f558833e63d59d372e4f7\/library\std\src\panicking.rs:624
   7:   0xa09d06 - std::panicking::begin_panic_handler::closure$0
                       at /rustc/ac50a53359328a5d7f2f558833e63d59d372e4f7\/library\std\src\panicking.rs:521
   8:   0xa0879f - std::sys_common::backtrace::__rust_end_short_backtrace<std::panicking::begin_panic_handler::closure$0,never$>
                       at /rustc/ac50a53359328a5d7f2f558833e63d59d372e4f7\/library\std\src\sys_common\backtrace.rs:141
   9:   0xa09c52 - std::panicking::begin_panic_handler
                       at /rustc/ac50a53359328a5d7f2f558833e63d59d372e4f7\/library\std\src\panicking.rs:517
  10:   0xa1b18a - core::panicking::panic_fmt
                       at /rustc/ac50a53359328a5d7f2f558833e63d59d372e4f7\/library\core\src\panicking.rs:101
  11:   0xa161e3 - core::panicking::assert_failed_inner
                       at /rustc/ac50a53359328a5d7f2f558833e63d59d372e4f7\/library\core\src\panicking.rs:183
  12:   0xa01cc9 - core::panicking::assert_failed<str,str>
                       at /rustc/ac50a53359328a5d7f2f558833e63d59d372e4f7\library\core\src\panicking.rs:140
  13:   0xa01e97 - core::ops::function::FnOnce::call_once<void (*)(),tuple$<> >
                       at /rustc/ac50a53359328a5d7f2f558833e63d59d372e4f7\library\core\src\ops\function.rs:227
  14:   0xa027c1 - std::rt::lang_start::closure$0<tuple$<> >
                       at /rustc/ac50a53359328a5d7f2f558833e63d59d372e4f7\library\std\src\rt.rs:63
  15: 0x7567801d - GetProcAddressForCaller
  16:   0xa02792 - std::rt::lang_start<tuple$<> >
                       at /rustc/ac50a53359328a5d7f2f558833e63d59d372e4f7\library\std\src\rt.rs:62
  17:   0xa01541 - main
  18: 0x75cefa29 - BaseThreadInitThunk
  19: 0x77177a7e - RtlGetAppContainerNamedObjectPath
  20: 0x77177a4e - RtlGetAppContainerNamedObjectPath

```

</p>
</details>

My main problem is, that I do not know, how to get to the contents of  `C:\Windows\System32\kernel32.dll`, using regular `std::fs` tools. For the time being, I'll search for a workaround, using winapi calls.

**Comment by ChrisDenton** [comment]
This is expected behaviour. By default x86 on x64 will automatically redirect certain paths. The `canonicalize` function shows the path it's redirected to. You can disable this using [`Wow64DisableWow64FsRedirection`](https://docs.microsoft.com/en-us/windows/win32/api/wow64apiset/nf-wow64apiset-wow64disablewow64fsredirection).

**Comment by C0D3-M4513R** [comment]
Thank you. One can also do the following:
> 32-bit applications can access the native system directory by substituting %windir%\Sysnative for %windir%\System32. WOW64 recognizes Sysnative as a special alias used to indicate that the file system should not redirect the access. This mechanism is flexible and easy to use, therefore, it is the recommended mechanism to bypass file system redirection. Note that 64-bit applications cannot use the Sysnative alias as it is a virtual directory not a real one.

from https://docs.microsoft.com/en-us/windows/win32/winprog64/file-system-redirector

> This is expected behaviour.

Mhmmm. That is interesting. Microsoft says this though. Isn't that conflicting?

> For file I/O, the "\?" prefix to a path string tells the Windows APIs to disable all string parsing and to send the string that follows it straight to the file system.

Will close, since this is apparently 'expected' behavior.

**Comment by ChrisDenton** [comment]
> Mhmmm. That is interesting. Microsoft says this though. Isn't that conflicting?
> 
> > For file I/O, the "?" prefix to a path string tells the Windows APIs to disable all string parsing and to send the string that follows it straight to the file system.

No because the path string is being passed straight to the filesystem. However, for 32-bit applications, the filesystem has a filter added that redirects some file operations. This is a bit similar to the way symlinks work. If you access a path to a symlink it (by default) will be redirected to the symlinks target instead of opening the symlink itself.

**Comment by C0D3-M4513R** [comment]
"straight to the file system" and "filesystem has a filter" is the exact conflict here. Adding a conditional filter, in front of the filesystem, is not "straight to the filesystem" anymore. This is misleading.
I'll have to bash my head with Microsoft, with this one though, to get them to change the docs. (I won't)

Note: Here you need to escape backslashes, in Quotes.
