### ISSUE TITLE
Private macros are documented

### ISSUE THREAD

**Issue by dylni** [rust-lang/rust#88453]
### Code

I tried this code:

```rust
macro_rules! private_macro {
    () => {};
}
```

I expected to see this happen: `private_macro` is hidden from the documentation.

Instead, this happened: `private_macro` is shown in the documentation and has its own page. Private declarative macros are also shown.

### Version it worked on

It most recently worked on: rustc 1.56.0-nightly (8007b506a 2021-08-14)

### Version with regression

`rustc --version`:
```
rustc 1.56.0-nightly (5eacec9ec 2021-08-28)
```

**Comment by inquisitivecrystal** [comment]
Thanks for filing this issue!

This regression was almost certainly introduced in #88019. I'm looking into it.

**Comment by camelid** [comment]
Assigning priority as [discussed](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2388453.20Private.20macros.20are.20documented) in the prioritization working group.

@rustbot label: +P-high -I-prioritize

**Comment by dylni** [comment]
Thanks @inquisitivecrystal!
