### ISSUE TITLE
why do i need fn main() {} always

### ISSUE THREAD

**Issue by Nyanggi** [rust-lang/rust#88474]
why

**Comment by Fn79** [comment]
Code starts in the `main()` function

~~냥이님 안녕하세요~~

**Comment by jonas-schievink** [comment]
Hi! This issue tracker is mainly meant for bug reports and concrete, small feature requests. Questions like this are better asked in the user forum at https://users.rust-lang.org/ or on [one of the chat platforms](https://www.rust-lang.org/community) used by the Rust community.
