### ISSUE TITLE
rust_2021_prelude_collisions bad suggestion with lifetime generics

### ISSUE THREAD

**Issue by ehuss** [rust-lang/rust#88470]
I tried this code:

```rust
#![warn(rust_2021_prelude_collisions)]
pub struct PyAny;

pub trait PyTryFrom<'v>: Sized {
    fn try_from<V>(value: V) -> Result<&'v Self, ()>;
}

pub trait PyTryInto<T>: Sized {
    fn try_into(&self) -> Result<&T, ()>;
}

struct Foo;

impl<U> PyTryInto<U> for Foo
where
    U: for<'v> PyTryFrom<'v>,
{
    fn try_into(&self) -> Result<&U, ()> {
        U::try_from(self)
    }
}
```

This generates a suggestion to avoid the prelude collision with:

```rust
        <U as PyTryFrom<_>>::try_from(self)
```

However, that does not compile because the generics for `PyTryFrom` is a lifetime parameter which should not be specified with `_`.  I believe the correct suggestion would be `<U as PyTryFrom>::try_from(self)` without the generic args.

Found in the 2021 crater run for:
* https://crater-reports.s3.amazonaws.com/pr-87190-3/try%23a7a572ce3edd6d476191fbfe92c9c1986e009b34/reg/pyo3-0.14.3/log.txt

### Meta

`rustc --version --verbose`:
```
rustc 1.56.0-nightly (ac50a5335 2021-08-27)
binary: rustc
commit-hash: ac50a53359328a5d7f2f558833e63d59d372e4f7
commit-date: 2021-08-27
host: x86_64-apple-darwin
release: 1.56.0-nightly
LLVM version: 13.0.0
```

**Comment by ehuss** [comment]
cc #88442 which is similar where `rust_2021_prelude_collisions` is having issues with generics.

**Comment by m-ou-se** [comment]
Similar problem (not found in hte crater results):

```rust
#![warn(rust_2021_prelude_collisions)]

pub trait A {
    fn try_from(self) -> i32;
}

struct Foo<'a>(&'a i32);

impl<'a> A for Foo<'a> {
    fn try_from(self) -> i32 {
        0
    }
}

fn main() {
    Foo::try_from(todo!());
}
```

```
warning: trait-associated function `try_from` will become ambiguous in Rust 2021
  --> src/main.rs:16:5
   |
16 |     Foo::try_from(todo!());
   |     ^^^^^^^^^^^^^ help: disambiguate the associated function: `<Foo<_> as A>::try_from`
   |
```

(The lifetime is now on the Self type, not on the trait.)

**Comment by m-ou-se** [comment]
The problem also exists for const generics. But I don't think we can solve that without `#![feature(generic_arg_infer)]`.
