### ISSUE TITLE
openbsd slow compile and patche q

### ISSUE THREAD

**Issue by apricot-quote** [rust-lang/rust#88489]
seem a lot of them and they not share back https://github.com/openbsd/ports/tree/master/lang/rust/patches
can be included official or only if person prs it? not sure why they not share, mmaybe dont care for oss or project?

do any patch there cause slow compile? seems openbsd objective slower than other os whhen building projects and is cause issue

**Comment by qbit** [comment]
@apricot-quote implying people (who have put _great_ effort into both rust _and_ OpenBSD) "dont care for oss or project" is absolutely not welcome. 

The OpenBSD ports tree has a number of requirements that make patching some stuff necessary  (i'll leave you to determine why).  A lot of patches simply aren't suitable for upstreaming.

Before flinging blame or making accusations about the work people have done, I strongly suggest that you learn more about the matter at hand.

**Comment by jyn514** [comment]
This is not really actionable; it's common for distros to patch the programs they package. @qbit you're of course welcome to upstream patches if you think they'd be useful for others :) but I skimmed through the patches and I agree most of them are BSD specific.

**Comment by PatchMixolydic** [comment]
Some of the compilation performance issues may be due to security hardening measures in OpenBSD. For instance, I believe they disable hyperthreading by default (though I may be mistaken), which means that there are fewer logical CPUs available to build crates on.
