### ISSUE TITLE
reserved prefixes break inline_python

### ISSUE THREAD

**Issue by ehuss** [rust-lang/rust#88510]
I tried this code:

```rust
use inline_python::{python, Context};

pub fn foo() {
    let c: Context = python!{
        y = 123;
        x = f"{y}"
    };
}
```

This code will fail to compile in 2021 because `f"{y}"` is reserved.  However, `rust_2021_prefixes_incompatible_syntax` will cause a space to be inserted which will also fail to compile (because that is not valid Python syntax).

I don't think there is anything that can be done here, since reserved prefixes are fundamentally incompatible with what `inline_python` is trying to do.  However, I couldn't find any issues are discussions around how this wouldn't work, so I'm opening this issue.

Found in the 2021 crater run for:

* https://crater-reports.s3.amazonaws.com/pr-87190-3/try%23a7a572ce3edd6d476191fbfe92c9c1986e009b34/gh/mucinoab.Poke-Classifier/log.txt

### Meta
`rustc --version --verbose`:
```
rustc 1.56.0-nightly (5eacec9ec 2021-08-28)
binary: rustc
commit-hash: 5eacec9ec7e112a0de1011519a57c45586d58414
commit-date: 2021-08-28
host: x86_64-apple-darwin
release: 1.56.0-nightly
LLVM version: 13.0.0
```

**Comment by m-ou-se** [comment]
Yes, this was discussed at length before accepting the reserved prefixed change. I'll fix this on the side of inline-python, by accepting and removing whitespace in those situations. :)

**Comment by m-ou-se** [comment]
Moved the issue to the inline-python repository, as there's nothing to do on the side of rust: https://github.com/fusion-engineering/inline-python/issues/44
