### ISSUE TITLE
[lib] Prefer `core::hint::unreachable_unchecked` over `core::unreachable` macro

### ISSUE THREAD

**Issue by Some-Dood** [rust-lang/rust#88606]
At the moment, many of the core assertions in the standard library make use of the `unreachable` macro, which is simply an indirection for `panic`. This is totally fine, but I would like to begin an initiative on upgrading some of these invocations as `core::hint::unreachable_unchecked` so that we may (at least) give the compiler a chance to optimize the code better.

Below is a _non-exhaustive_ list of possible candidates. I will be editing the issue as more candidates are introduced and as certain examples are marked 100% safe or not.

# Merged
None so far.

# Definitely Safe
This is the perfect candidate for `core::hint::unreachable_unchecked` since it is apparent that `self` is now the `Cow::Owned` variant.
https://github.com/rust-lang/rust/blob/97f2698484c2d668b2f356a6c2252e5f08472234/library/alloc/src/borrow.rs#L275-L287

# Possible Candidates
https://github.com/rust-lang/rust/blob/673d0db5e393e9c64897005b470bfeb6d5aec61b/library/core/src/lazy.rs#L52-L64

https://github.com/rust-lang/rust/blob/adf168844791b213383b18d10515eaee88695f7d/library/std/src/lazy.rs#L121-L130

https://github.com/rust-lang/rust/blob/adf168844791b213383b18d10515eaee88695f7d/library/std/src/lazy.rs#L152-L158

https://github.com/rust-lang/rust/blob/17f30e5451f581d753899d2f628e5be354df33cd/library/std/src/sys/sgx/abi/mod.rs#L51-L52

https://github.com/rust-lang/rust/blob/673d0db5e393e9c64897005b470bfeb6d5aec61b/library/std/src/sync/mpsc/oneshot.rs#L105-L106

https://github.com/rust-lang/rust/blob/673d0db5e393e9c64897005b470bfeb6d5aec61b/library/std/src/sync/mpsc/oneshot.rs#L170-L173

https://github.com/rust-lang/rust/blob/673d0db5e393e9c64897005b470bfeb6d5aec61b/library/std/src/sync/mpsc/oneshot.rs#L188-L190

https://github.com/rust-lang/rust/blob/673d0db5e393e9c64897005b470bfeb6d5aec61b/library/std/src/sync/mpsc/oneshot.rs#L251-L252

https://github.com/rust-lang/rust/blob/673d0db5e393e9c64897005b470bfeb6d5aec61b/library/std/src/sync/mpsc/oneshot.rs#L278-L281

https://github.com/rust-lang/rust/blob/a28109a7679fbb254ca0962865a8b32b91ddbbd9/library/std/src/sys/sgx/mutex.rs#L113-L118

https://github.com/rust-lang/rust/blob/3ed6c1d23fd40f4367259a531465e809eb00ec27/library/core/src/iter/traits/iterator.rs#L3444-L3449

https://github.com/rust-lang/rust/blob/c5fbcd35a8217a17f6b63a22217ace06cf8f5f02/library/std/src/sys/sgx/rwlock.rs#L134-L139

https://github.com/rust-lang/rust/blob/a49e38e672c60da788360e088f00ad12353e3913/library/core/src/iter/adapters/zip.rs#L182-L186

https://github.com/rust-lang/rust/blob/a49e38e672c60da788360e088f00ad12353e3913/library/core/src/iter/adapters/zip.rs#L219-L224

https://github.com/rust-lang/rust/blob/fe1c942eee3489743d655d81ca89166217db0547/library/std/src/sync/mpsc/stream.rs#L429-L444

https://github.com/rust-lang/rust/blob/673d0db5e393e9c64897005b470bfeb6d5aec61b/library/std/src/sync/mpsc/shared.rs#L338-L343

https://github.com/rust-lang/rust/blob/dfd7b8d03fb93d0e03147d28b3be6d93260fa94d/library/std/src/sys/unix/kernel_copy.rs#L201-L207

https://github.com/rust-lang/rust/blob/2ad56d5c9031636c1509f4417e88099a49405b4e/library/std/src/path.rs#L912

https://github.com/rust-lang/rust/blob/a49e38e672c60da788360e088f00ad12353e3913/library/std/src/net/ip.rs#L1679-L1684

https://github.com/rust-lang/rust/blob/673d0db5e393e9c64897005b470bfeb6d5aec61b/library/alloc/src/collections/btree/split.rs#L49-L56

https://github.com/rust-lang/rust/blob/3ed6c1d23fd40f4367259a531465e809eb00ec27/library/alloc/src/collections/btree/map.rs#L184-L187

https://github.com/rust-lang/rust/blob/23461b210f1b0a121592a18fc4fb666106006668/library/alloc/src/collections/btree/node.rs#L1222

https://github.com/rust-lang/rust/blob/23461b210f1b0a121592a18fc4fb666106006668/library/alloc/src/collections/btree/node.rs#L1424-L1439

https://github.com/rust-lang/rust/blob/23461b210f1b0a121592a18fc4fb666106006668/library/alloc/src/collections/btree/node.rs#L1487-L1503

https://github.com/rust-lang/rust/blob/23461b210f1b0a121592a18fc4fb666106006668/library/alloc/src/collections/btree/node.rs#L1599-L1609

https://github.com/rust-lang/rust/blob/673d0db5e393e9c64897005b470bfeb6d5aec61b/library/std/src/sync/mpsc/sync.rs#L111-L114

https://github.com/rust-lang/rust/blob/607d6b00d4e0e0475b8de9d0c870b7126fdcdf6b/library/std/src/sync/mpsc/mod.rs#L828

https://github.com/rust-lang/rust/blob/673d0db5e393e9c64897005b470bfeb6d5aec61b/library/std/src/sync/mpsc/sync.rs#L243

https://github.com/rust-lang/rust/blob/673d0db5e393e9c64897005b470bfeb6d5aec61b/library/std/src/sync/mpsc/sync.rs#L328-L342

https://github.com/rust-lang/rust/blob/673d0db5e393e9c64897005b470bfeb6d5aec61b/library/std/src/sync/mpsc/sync.rs#L378-L382

https://github.com/rust-lang/rust/blob/673d0db5e393e9c64897005b470bfeb6d5aec61b/library/std/src/sync/mpsc/sync.rs#L402-L409

https://github.com/rust-lang/rust/blob/607d6b00d4e0e0475b8de9d0c870b7126fdcdf6b/library/std/src/sync/mpsc/mod.rs#L1157-L1176

# Must Remain `unreachable`
None so far.

# Action
I would love to send in a PR that resolves this issue! However, I do need some help and guidance from the library maintainers to ensure that undefined behavior is 110% avoided. Feedback on which parts are safe **regardless of platform/architecture/hardware** is much appreciated.

As mentioned earlier, I will be editing this issue as more people chime in. Thanks!

**Comment by hellow554** [comment]
6 issues before this (#88600) is a very good reason to **not** do it and remain `unreachable!()`.

If it is really unreachable, the compiler will figure it out and eleminate the branch, see https://rust.godbolt.org/z/5Kez3MPGW

I don't think that this is reasonable but I'd like to hear others people opinion.

**Comment by the8472** [comment]
#86520 went in the opposite direction. Have you checked the performanee on any of these, e.g. by running the benches included in the library?

**Comment by Some-Dood** [comment]
> Have you checked the performance on any of these?

Honestly, this shouldn't be necessary anymore. I sense that there is already a strong consensus that the compiler is (more than) smart enough to detect truly unreachable branches. The panic infrastructure as a safety mechanism is hard to argue against, especially since the compiler already optimizes it away in most cases.

This is great! Glad that I can certainly say that I can close this issue with much greater faith in the compiler's abilities. Thanks for the valuable input, everyone! I believe this issue does not need to linger any longer.
