### ISSUE TITLE
Switch compiler to Rust 2021

### ISSUE THREAD

**Issue by m-ou-se** [rust-lang/rust#88637]
This is blocked on the beta/bootstrap compiler being updated to 1.56.

**Comment by camelid** [comment]
No longer blocked! The bootstrap compiler is now 1.56.

**Comment by Mark-Simulacrum** [comment]
https://github.com/rust-lang/rust/commit/8ae15246991088f41c248ac3b201e9518d489743 are the migration fixes currently suggested in-tree
