### ISSUE TITLE
Switch library to Rust 2021

### ISSUE THREAD

**Issue by m-ou-se** [rust-lang/rust#88638]
This is blocked on the beta/bootstrap compiler being updated to 1.56.

**Comment by m-ou-se** [comment]
This is blocked on an issue with assert and debug_assert using the edition of libccore instead of the one who invoked it. (For assert only on Rust 2015 and 2018, for debug_assert on all editions.)

https://rust-lang.zulipchat.com/#narrow/stream/268952-edition-2021/topic/libcore.202021.20bug/near/252504325

**Comment by camelid** [comment]
(Note that this is blocked on https://github.com/rust-lang/rust/issues/88638#issuecomment-915472783. The bootstrap compiler is now 1.56, so that's not a blocker.)

**Comment by rukai** [comment]
I tried setting core to 2021 and got this error:
![image](https://user-images.githubusercontent.com/5120858/146530552-fa363c57-9809-4280-9a7d-2df1de312e43.png)
Adding rustc_const_stable to panic_fmt resolved the issue but its strange that this issue didnt appear until the edition was set to 2021.

Is this another blocker?

**Comment by m-ou-se** [comment]
>  strange that this issue didnt appear until the edition was set to 2021.

That's expected. `panic!("just a string")` didn't use panic_fmt in Rust 2018, but does in Rust 2021. See https://doc.rust-lang.org/edition-guide/rust-2021/panic-macro-consistency.html

**Comment by m-ou-se** [comment]
@rust-lang/wg-const-eval: Looks like the "const-stable functions can only call other const-stable functions" check doesn't play well with `#[rustc_do_not_const_check]`.

**Comment by m-ou-se** [comment]
@fee1-dead what part are you claiming? The migration of core is blocked on the const check, and the migration of std is already in progress in #92030.

**Comment by fee1-dead** [comment]
I will fix the const check. And since this is a tracking issue I will unclaim. Sorry for the confusion
