### ISSUE TITLE
Crate compilation hangs on release build for thumbv6m-none-eabi

### ISSUE THREAD

**Issue by AaronC81** [rust-lang/rust#88654]
Compiling recent versions of the `rust_decimal` crate in release mode targeting thumbv6m-none-eabi appears to hang the compiler.

A bisect has narrowed it down to this commit: https://github.com/paupino/rust-decimal/commit/8f3716e38c478a454de78e6c0109fea5eea1af39

(Apologies I don't have an MCVE for this - I don't understand Rust internals enough to know where I'd start trimming this down!)

To reproduce:
  - Clone https://github.com/paupino/rust-decimal
  - Check out commit `8f3716e38c478a454de78e6c0109fea5eea1af39`
  - Run `cargo build --target thumbv6m-none-eabi --no-default-features --release` - it should hang
  - Check out the previous commit, `7d0a5c1f02066755dddc015934f0c7f7c8aebc24` - the same build command should not hang

A debug build completes in seconds.  Targeting `x86_64-unknown-linux-gnu` or `thumbv7m-none-eabi` instead also completes succesfully. This issue only seems to affect `thumbv6m-none-eabi` in release builds.

### Meta

`rustc --version --verbose`:
```
rustc 1.55.0-nightly (952fdf2a1 2021-07-05)
binary: rustc
commit-hash: 952fdf2a1119affa1b37bcacb0c49cf9f0168ac8
commit-date: 2021-07-05
host: x86_64-unknown-linux-gnu
release: 1.55.0-nightly
LLVM version: 12.0.1
```

**Comment by hellow554** [comment]
Here's what I have so far:

```rust
#![no_std]

#[derive(Clone, Copy)]
pub struct Decimal {
    hi: u32,
    lo: u32,
}

impl Decimal {
    pub fn checked_mul(self) -> Decimal {
        let mut tmp = self.lo as u64 * self.lo as u64;
        let mut tmp2 = (self.lo as u64 * self.lo as u64).wrapping_add(tmp >> 32);
        tmp = tmp.wrapping_add(tmp2);

        if tmp < tmp2 {
            tmp2 = (tmp >> 32) | (1u64 << 32);
        } else {
            tmp2 = tmp >> 32;
        }

        tmp = (self.lo as u64 * self.lo as u64) + tmp2;
        if self.lo > 0 {
            tmp2 = self.hi as u64 * self.lo as u64;
            tmp = tmp.wrapping_add(tmp2);
        }

        Decimal {
            lo: tmp as u32,
            hi: tmp2 as u32,
        }
    }
}
```

**Comment by hellow554** [comment]
It seems to be a LLVM problem, because I can create the LLVM-IR, but not asm (and it hangs after `LLVM_lto_optimize`)

Here's the LLVM-IR:
```llvm
; ModuleID = 'lib.f2c86790-cgu.0'
source_filename = "lib.f2c86790-cgu.0"
target datalayout = "e-m:e-p:32:32-Fi8-i64:64-v128:64:128-a:0:32-n32-S64"
target triple = "thumbv6m-none-unknown-eabi"

; lib::Decimal::checked_mul
; Function Attrs: mustprogress nofree norecurse nosync nounwind readnone willreturn
define dso_local { i32, i32 } @_ZN3lib7Decimal11checked_mul17hbf678d4f3ee90eb3E(i32 %self.0, i32 %self.1) unnamed_addr #0 {
start:
  %_3 = zext i32 %self.1 to i64
  %0 = mul nuw i64 %_3, %_3
  %_13 = lshr i64 %0, 32
  %1 = add nuw i64 %_13, %0
  %2 = add i64 %1, %0
  %_18 = icmp ult i64 %2, %1
  %_21 = lshr i64 %2, 32
  %3 = or i64 %_21, 4294967296
  %tmp2.0 = select i1 %_18, i64 %3, i64 %_21
  %4 = add i64 %tmp2.0, %0
  %_31.not = icmp eq i32 %self.1, 0
  %extract.t13 = trunc i64 %4 to i32
  %extract.t15 = trunc i64 %tmp2.0 to i32
  br i1 %_31.not, label %bb8, label %bb6

bb8:                                              ; preds = %bb6, %start
  %tmp.0.off0 = phi i32 [ %extract.t, %bb6 ], [ %extract.t13, %start ]
  %tmp2.1.off0 = phi i32 [ %extract.t14, %bb6 ], [ %extract.t15, %start ]
  %5 = insertvalue { i32, i32 } undef, i32 %tmp2.1.off0, 0
  %6 = insertvalue { i32, i32 } %5, i32 %tmp.0.off0, 1
  ret { i32, i32 } %6

bb6:                                              ; preds = %start
  %_33 = zext i32 %self.0 to i64
  %7 = mul nuw i64 %_3, %_33
  %8 = add i64 %4, %7
  %extract.t = trunc i64 %8 to i32
  %extract.t14 = trunc i64 %7 to i32
  br label %bb8
}

attributes #0 = { mustprogress nofree norecurse nosync nounwind readnone willreturn "frame-pointer"="all" "target-cpu"="generic" }
```

@rustbot modify labels: A-LLVM 
@rustbot ping llvm

**Comment by hellow554** [comment]
@jonas-schievink can you please ping the llvm crew? :)

**Comment by hellow554** [comment]
For what I can tell it's a regression between llvm 8.0 and llvm 9.0. Is somebody able to reduce the LLVM-IR further and file a bug report upstream?

**Comment by Noah-Kennedy** [comment]
I'm new to a lot of this, but I'll give it a go.

**Comment by hellow554** [comment]
This is my current MCVE for the LLVM-IR:

```llvm
target triple = "thumbv6m-none-unknown-eabi"

define { i32 } @func(i64 %arg) {
start:
  %0 = add i64 %arg, 1
  %1 = icmp ult i64 %0, 1           ; only `ult` can be used here fwr
  %2 = select i1 %1, i64 8, i64 0   ; 8 must be a power of 2
  %3 = add i64 %2, 0
  br label %bb6

bb6:
  %4 = add i64 %3, 0
  br label %bb6
}
```

**Comment by hellow554** [comment]
Upstream issue https://bugs.llvm.org/show_bug.cgi?id=51777

**Comment by nagisa** [comment]
This looks very similar to https://bugs.llvm.org/show_bug.cgi?id=47366 in that LLVM is stuck combining SUBCs and ADDEs.

**Comment by hellow554** [comment]
Indeed! It does compile fine on LLVM 8, but does not on LLVM 9.

Do you want to mark this as a duplicate of the other one (here and on bugs.llvm.org)?

**Comment by nagisa** [comment]
Duplicate of https://github.com/rust-lang/rust/issues/75045
