### ISSUE TITLE
How to construct ParseIntError?

### ISSUE THREAD

**Issue by dns2utf8** [rust-lang/rust#88663]
Hi all

I am trying to construct `ParseIntError` to verify my test `from_str_radix("XYZ", 2)`
```rust
let kind = ::core::num::IntErrorKind::InvalidDigit;
let pie = ::core::num::ParseIntError {
    kind
};
return Err(pie);
```

With 1.55.0 the specific errors have been stabilized but I am unable to construct it.

Also, I am trying to have it generic over any ints:
```rust
pub fn parse<T: Num>(input: &str) -> Result<T, T::FromStrRadixErr>
```

Cheers,
Stefan

**Comment by ehuss** [comment]
You cannot construct it directly. You'll need to create it from an actual parse error like `let e = "".parse::<i32>().unwrap_err();`.

Questions like these are better asked on one of the forums (like [URLO](https://users.rust-lang.org/)). This issue tracker only for bugs and small, concrete enhancement requests.

**Comment by dns2utf8** [comment]
Hi ehuss

Thanks for the quick reply!
The URLO is a good point. Still it seems weird that there is no way to construct it apart from an intentionally bad parse call ...
