### ISSUE TITLE
Lint against `--foo` when `foo` is a numeric binding

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#88669]
As noted in https://github.com/rust-lang/rust/pull/88553#discussion_r702058067, [`let x = --y;`](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=ac6afa4b466778e0de140b8540ddce05) is syntactically valid as a double negation, but it _looks_ like C's pre-decrement. We should lint against it and suggest both removing the `--` or writing `y -= 1; let x = y;`.

pre-increment, post-increment and post-decrement are not likely to confuse people too much because they are syntax errors, but we might also want to modify the parser to detect them specifically and provide a structured suggestion for appropriate code.

**Comment by camelid** [comment]
Isn't there a clippy lint that's being uplifted that catches `--y`? See #82987.

**Comment by estebank** [comment]
Yeah, you're right. We can _still_ keep this ticket open for the "handle `++x`/`x++`/`x--` more gracefully in the parser".

**Comment by camelid** [comment]
> We can _still_ keep this ticket open for the "handle `++x`/`x++`/`x--` more gracefully in the parser".

I think #83502 might cover that. I've been meaning to get back to it...
