### ISSUE TITLE
Tracking Issue for const_convert

### ISSUE THREAD

**Issue by usbalbin** [rust-lang/rust#88674]
Feature gate: `#![feature(const_convert)]`

This is a tracking issue for constifying some conversions (see #87852 for numeric conversions). Among other things this enables using the `?`-operator on `Option` and `Result` in const contexts for trivial conversions. Note that this does *not* add any new implementations, it only constifies the existing ones.

Simple example:
```rust
const fn foo() -> Result<(), FooError> {
    let bar = try_thing()?; // A function that returns Result<_, FooError>
    do_stuff_with(bar)?;    // A function that returns Result<_, FooError>
    Ok(())
}
```

### Public API

Constifies the following impls

```rust
impl<T, U> const Into<U> for T where U: ~const From<T>;
impl<T> const From<T> for T;

impl<T> const ops::Try for Option<T>;
impl<T> const ops::FromResidual for Option<T>;

impl<T, E> const ops::Try for Result<T, E>;
impl<T, E, F> const ops::FromResidual<Result<convert::Infallible, E>> for Result<T, F> where F: ~const From<E>;


impl<T: ?Sized, U: ?Sized> const AsRef<U> for &T where T: ~const AsRef<U>;
impl<T: ?Sized, U: ?Sized> const AsRef<U> for &mut T where T: ~const AsRef<U>;
impl<T: ?Sized, U: ?Sized> const AsMut<U> for &mut T where T: ~const AsMut<U>;

impl<T, U> const TryInto<U> for T where U: ~const TryFrom<T>;
impl<T, U> const TryFrom<U> for T where U: ~const Into<T>;
```

### Steps / History

- [x] Implementation: #86853
- [x] More impls #92382
- [ ] Blocked on #67792 and #84277
- [ ] Final comment period (FCP)
- [ ] Stabilization PR

### Unresolved Questions

- None yet.

**Comment by clarfonthey** [comment]
Note: `impl<T, U> const Into<U> for T where U: ~const From<T>;` is not actually included here; I add it with #92382.

**Comment by atifnimran** [comment]
Ok

**Comment by G33KatWork** [comment]
With commit 76dbe2910465072f85e74d6f7115ec9e6803e8bf the feature `const_convert` has been completely removed from the core library. I understand that it's unstable, but it's also not exactly documented why it got removed. I would've at least expected a discussion about this in this tracking issue.

Does anybody know more about this?

**Comment by usbalbin** [comment]
I believe that might be due to #110395

**Comment by RalfJung** [comment]
This has been entirely removed by https://github.com/rust-lang/rust/pull/110393.
