### ISSUE TITLE
Improve diagnostics for character literals containing multiple codepoints

### ISSUE THREAD

**Issue by eggyal** [rust-lang/rust#88684]
I tried to compile the following code ([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=17b195911187376f740b8e4e1c6f6fba)):

```rust
const SPADE: char = '♠️';
```

For the avoidance of doubt, `♠️` is [U+2660](https://util.unicode.org/UnicodeJsps/character.jsp?a=2660).  I expected the code to compile—but instead, the literal is rejected:

```
error: character literal may only contain one codepoint
 --> src/lib.rs:1:21
  |
1 | const SPADE: char = '♠️';
  |                     ^^^
  |
help: if you meant to write a `str` literal, use double quotes
  |
1 | const SPADE: char = "♠️";
  |                     ^^^
```

Notably, it is accepted if unicode-escaped:

```rust
const SPADE: char = '\u{2660}';
```

### Meta

`rustc --version --verbose`:
```
rustc 1.57.0-nightly (e30b68353 2021-09-05)
binary: rustc
commit-hash: e30b68353fe22b00f40d021e7914eeb78473b3c1
commit-date: 2021-09-05
host: x86_64-apple-darwin
release: 1.57.0-nightly
LLVM version: 13.0.0
```

**Comment by SNCPlay42** [comment]
The spade "character" in your code is not just a single U+2660, it also has a unicode variation selector U+FE0F: [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=24143c0d20114b82066bafd459d45f78)

**Comment by eggyal** [comment]
D'oh!  Good spot, thanks @SNCPlay42.  Perhaps some improved diagnostics could have helped here?

**Comment by SNCPlay42** [comment]
We have similar diagnostics in other cases of misleading Unicode so that seems like a good idea.
