### ISSUE TITLE
Rust/WASM FFI: `cargo test` throws an `undefined reference to foreign function` error.

### ISSUE THREAD

**Issue by kobby-pentangeli** [rust-lang/rust#88687]
Rust's foreign function interface (FFI) allows extern blocks of foreign functions to be defined. The following snippet demonstrates an ffi definition and invocation (inside `lib.rs`):

```rust
#[link(wasm_import_module = "kobby")]
extern "C" {
    /// Get Invoke Arguments
    pub fn __kobby_invoke_args(method_ptr: u32, args_ptr: u32);
}

pub fn kobby_invoke(method_size: u32, args_size: u32) -> bool {
    unsafe { __kobby_invoke_args(method_size, args_size) };
    true
}
```
I have the above snippet in my Rust/WASM library. The `crate-type` is defined in `Cargo.toml` as:

```rust
[lib]
crate-type = ["rlib", "cdylib"]
```
The following is a simple test that references the FFI above (inside the `tests` folder):

```rust
use kobby_ffi_library::invoke::kobby_invoke;

#[test]
fn it_compiles_sanity() {
    assert!(kobby_invoke(0, 0));
}
```
When I run `cargo test`, it produces an `undefined reference to foreign function: __kobby_invoke_args` error, while `cargo test --target wasm32-unknown-unknown` also produces an obscure OS error: `Syntax error: unexpected end of file.`

I have tried changing the  `crate-type` to `["lib", "staticlib", "cdylib"]`, but I still get same errors.

Other than the possibility of having a wrong `#[test]` (in which case the assertion would fail), I don't know what else I'm doing wrong in this scenario. Your support would be greatly appreciated. Thank you!

**Comment by CryZe** [comment]
I'm not entirely sure what you expect. If you compile it for the host system with `cargo test` then nothing provides an implementation for  `__kobby_invoke_args` and thus the linker will complain that it can't find that function. If you compile it for wasm, then it will import that into the wasm module and the wasm runtime needs to provide that. However your host can't natively execute WASM files so you get that OS error.

**Comment by kobby-pentangeli** [comment]
You're right. Before testing the code, I must first implement `__kobby_invoke_args`. Closing this issue now. Thank you!
