### ISSUE TITLE
Suggestions for miniz_oxide included in diagnostics in crate with no dependencies

### ISSUE THREAD

**Issue by m-ou-se** [rust-lang/rust#88696]
So, I was just chatting a bit with rustc and I was saying:

```rust
#![feature(never_type)]

fn a() -> Result<!, i32> {
    Err(1)
}

fn b() -> Result<u32, i32> {
    a().into()
}

fn main() {
    let _ = dbg!(b());
}
```

And then rustc said:

```
error[E0277]: the trait bound `Result<u32, i32>: From<Result<!, i32>>` is not satisfied
 --> src/main.rs:8:9
  |
8 |     a().into()
  |         ^^^^ the trait `From<Result<!, i32>>` is not implemented for `Result<u32, i32>`
  |
```

And I was like, *sure, whatever you say*.

But *then* rustc told me:

```
  = help: the following implementations were found:
            <Result<miniz_oxide::MZStatus, miniz_oxide::MZError> as From<&miniz_oxide::StreamResult>>
            <Result<miniz_oxide::MZStatus, miniz_oxide::MZError> as From<miniz_oxide::StreamResult>>
```

And I was like, *excuse me what??*

---

This crate has no dependencies. (Just an empty `cargo new ..` package.)

This happens on at least:
- rustc 1.55.0-nightly (014026d1a 2021-07-19)
- rustc 1.56.0-nightly (ccffcafd5 2021-08-11)
- rustc 1.57.0-nightly (5d2a410ff 2021-09-04)

(On `x86_64-unknown-linux-gnu` and other platforms where `backtrace` is enabled in `std`, such that `miniz_oxide` is pulled in as a dependency of `std`.)

**Comment by m-ou-se** [comment]
`miniz_oxide` is a (private) dependency of `std`, but it shouldn't show up in diagnostics for any program using `std` like this.

**Comment by camelid** [comment]
And, even aside from `miniz_oxide` being a private dependency, the suggestions seem very unrelated to the input code. I guess just because they're `From` impls on `Result`? I would have thought other `From` impls would have come up too though.

**Comment by camelid** [comment]
I wonder if this is specific to `never_type` or not.

**Comment by hellow554** [comment]
I think the suggestion should not show up anymore if https://github.com/rust-lang/rust/pull/87349 would have been merged.

Can you try that out? Would that be feasible for you?

**Comment by m-ou-se** [comment]
Ah that looks relevant. Trying that PR now..

**Comment by m-ou-se** [comment]
Nope. Same output with #87349.

**Comment by hellow554** [comment]
@In-line can you maybe say why your PR doesn't cover this case? :/

**Comment by apiraino** [comment]
Assigning priority as discussed in the [Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2388696.20Suggestions.20for.20miniz_oxide.20included.20in.20diagnostics.20.E2.80.A6) of the Prioritization Working Group.

@rustbot label -I-prioritize +P-medium

**Comment by QuineDot** [comment]
I just got this too, in code with zero dependencies which is not at all exotic.  All the non-std types here are just enums.
```
error[E0277]: the trait bound `Result<Option<Score>, build::Error>: From<Result<_, EntryError>>` is not satisfied
   --> src/build.rs:105:33
    |
105 |         Err(EntryError::InvalidScore).into()
    |                                       ^^^^ the trait `From<Result<_, EntryError>>` is not implemented for `Result<Option<Score>, build::Error>`
    |
    = help: the following implementations were found:
              <Result<miniz_oxide::MZStatus, miniz_oxide::MZError> as From<&miniz_oxide::StreamResult>>
              <Result<miniz_oxide::MZStatus, miniz_oxide::MZError> as From<miniz_oxide::StreamResult>>
    = note: required because of the requirements on the impl of `Into<Result<Option<Score>, build::Error>>` for `Result<_, EntryError>`
```
"miniz_oxide" doesn't cry out "implicit stdlib thing" so I spent awhile trying to figure out how an unrelated project was polluting this one, running cargo clean in various places, etc.

**Comment by jirutka** [comment]
> `miniz_oxide` is a (private) dependency of std, but it shouldn't show up in diagnostics for any program using std like this.

The real question is, why is `minz_oxide` pulled into a trivial program (binary) in the first place? It’s not a small dependency.

**Comment by m-ou-se** [comment]
> The real question is, why is `minz_oxide` pulled into a trivial program (binary) in the first place? It’s not a small dependency.

`std` includes funcitonality for backtraces, which is used in the default panic handler to print a backtrace when RUST_BACKTRACE=1 is set. In order to generate a backtrace, we depend on a backtrace crate which needs `miniz_oxide` to decompress the debug info.
