### ISSUE TITLE
RELEASES.md 1.55 wrong annonce for `From<[(K, V); N]> for HashMap`?

### ISSUE THREAD

**Issue by a1ien** [rust-lang/rust#88693]
In RELEASES.md Stabilize impl From<[(K, V); N]> for HashMap
https://github.com/rust-lang/rust/blob/7248ff2760f39cd788ee9c3bbabec8aa78faec69/RELEASES.md?plain=1#L29
Place for release 1.55 but in code 
https://github.com/rust-lang/rust/blob/7248ff2760f39cd788ee9c3bbabec8aa78faec69/library/alloc/src/collections/binary_heap.rs#L1475
stabilize only in 1.56

**Comment by Mark-Simulacrum** [comment]
Fixed by https://github.com/rust-lang/rust/pull/88694
