### ISSUE TITLE
linux: std::process, insecure dropping of ancillary groups

### ISSUE THREAD

**Issue by bnoordhuis** [rust-lang/rust#88716]
Commit 22ddcd1a13082b7be0fc99b720677efd2b733816 made libstd drops ancillary groups when uid == 0:
https://github.com/rust-lang/rust/blob/385f8e2078b00282a7a7ffcd58aad17b405f57bf/library/std/src/sys/unix/process/process_unix.rs#L312-L314
Before that it unconditionally dropped group membership.

The new logic is wrong on Linux: it doesn't account for processes whose uid != 0 but have the CAP_SETGID capability.

Such processes can and should drop ancillary groups, otherwise child processes inherit permissions they otherwise wouldn't have.

Suggested change:
```rust
if self.get_groups().is_none() {
    let _ = libc::setgroups(0, ptr::null()); // or return unless EPERM
}
```

**Comment by joshtriplett** [comment]
This seems like a potentially reasonable approach. It'd be a behavior change, but technically the previous change was a behavior change in the case of CAP_SETGID.

(It seems worth noting that CAP_SETGID is generally root-equivalent, so this doesn't actually seem like a security issue of any kind.)

**Comment by cuviper** [comment]
Whatever we do, we need to reconcile this with #90292 as it becomes documented.
I agree the suggested change makes sense though.

**Comment by bnoordhuis** [comment]
> It seems worth noting that CAP_SETGID is generally root-equivalent, so this doesn't actually seem like a security issue of any kind.

IMO, it is. Scenario: non-root, sudo-like program that:

1. has CAP_SETGID + CAP_SETUID in order to switch users when spawning child processes, and
2. is a member of one or more supplementary groups in order to read or write sensitive files

Not dropping group membership is a catastrophic security breach in that setup.

**Comment by joshtriplett** [comment]
Wouldn't it need to drop that capability though, before the exec?

In any case, this does still need fixing.

**Comment by bnoordhuis** [comment]
> Wouldn't it need to drop that capability though, before the exec?

Not necessarily, it depends on the capability set (threads have several) the capability is part of. Some persist across execve() calls, some don't.

(I wanted to write up a short explanation of the algorithm but I can't hope to do it justice in a few words, it's complicated.)

I'm pessimistic checking AT_SECURE is sufficient. `man 7 capabilities` claims the following:

> If  ambient  capabilities cause  a  process's  permitted  and  effective  capabilities  to  increase  during an execve(2), this does not trigger the secure-execution mode described in ld.so(8).

It's set only when [permitted is a superset of ambient](https://github.com/torvalds/linux/blob/cb690f5238d71f543f4ce874aa59237cf53a877c/security/commoncap.c#L968-L973).

prctl() with one of the PR_CAPxxx flags might work but that gets complicated fast and I'd argue dropping group membership unless the user indicates otherwise is traditional and expected UNIX behavior.

It's [what libuv does](https://github.com/libuv/libuv/blob/0f696da5f0328dde1f9cc0372692ce22f0d17100/src/unix/process.c#L306-L315) and a [CERT C recommendation](https://wiki.sei.cmu.edu/confluence/display/c/POS36-C.+Observe+correct+revocation+order+while+relinquishing+privileges).

**Comment by joshtriplett** [comment]
My concern is that the user should not have to retrieve and re-set the supplementary groups just to have them not cleared.

Also, I'd like to avoid adding an unexpected source of additional complexity; I think inheriting will be the common case.

**Comment by Amanieu** [comment]
Note that clearing the groups only happens if the user asked to change to a different UID. I think it makes sense in this case to always drop the groups since they are tied to the previous UID and most likely aren't supposed to be kept for the new UID. If you really want to preserve the groups while changing UID (unlikely anyone would ever want that...) then you can explicitly pass the list of groups of the current process.

I agree with this change, but is it really necessary to ignore an `EPERM` from `setgroups`? If you have permissions to change UID then you should also have permissions to change groups. I would feel more comfortable if we documented `set_uid` as requiring both UID and GID changing permissions.

@rfcbot fcp merge

**Comment by Amanieu** [comment]
@bnoordhuis We have accepted this change, would you be willing to write up a PR for it?

**Comment by Elliot-Roberts** [comment]
I could write a PR for this and maybe also bundle in a redo of #90292.

**Comment by bnoordhuis** [comment]
@Elliot-Roberts Please go ahead. I'm not working on this at the moment.

**Comment by Elliot-Roberts** [comment]
Sorry scratch that I'm having trouble with my dev environment and don't have the time to fix it right now. I might pick this back up but I'm no longer claiming it.
