### ISSUE TITLE
ControlFlow docs should explicitly mention that it works with ?

### ISSUE THREAD

**Issue by matklad** [rust-lang/rust#88715]
We stabilized ControlFlow: https://doc.rust-lang.org/stable/std/ops/enum.ControlFlow.html

That’s somewhat of a big deal, as it is now the third type (in addition to Option and Result), which works with `?` operator on stable. This isn’t immediately obvious from the docs though!

**Comment by chrismit3s** [comment]
Will do!

@rustbot claim
