### ISSUE TITLE
Don't show argument mutability in rustdoc

### ISSUE THREAD

**Issue by nox** [rust-lang/rust#88725]
In `fn foo(mut v: Foo)`, `mut` is an implementation detail of the function and thus shouldn't appear in rustdoc's output.

Cc @GuillaumeGomez

**Comment by camelid** [comment]
`mut` in function arguments is usually hidden already, no? For example:

```rust
pub struct Foo;

pub fn foo(mut v: Foo) {}
```

![image](https://user-images.githubusercontent.com/37223377/132383722-b2aea702-8eb0-4e64-bf0d-0055338074ee.png)

@nox Where did you see it shown?

**Comment by nox** [comment]
I don't remember, it's been a while and I just procrastinated instead of filing an issue, maybe this was fixed since then hah.

**Comment by camelid** [comment]
Ok, I'm going to close this as "already fixed". Please feel free to re-open this issue or open a new issue if you come across this again!

**Comment by nox** [comment]
I've spent a few minutes trying to find when that could have changed, and I can't even find the commit, oh well, maybe it was a dream all along.
