### ISSUE TITLE
std::ptr::read double free the nonCopy type value

### ISSUE THREAD

**Issue by NightfallDM** [rust-lang/rust#88746]
I tried this code:

```rust
#![allow(unused)]
fn main() {
use std::mem::ManuallyDrop;
let x = String::from("xxx");
let y = &x as *const String;

unsafe {
    assert_eq!(std::ptr::read(y), "xxx".to_string());
    }
    // {
    //     let _ = ManuallyDrop::new(x);
    // }
}
```
### There are a few question to talk about the title.
1.    The std::ptr::read return a new value (T) from a const raw ptr (*const T). in general the perv value which have the ownship should not legal anymore, because if the old value and new value both legal, threre will direct have two owners of the same resource, So the std lib DOC write   "read creates a bitwise copy of T, regardless of whether T is Copy. If T is not Copy, using both the returned value and the value at *src can violate memory safety. Note that assigning to *src counts as a use because it will attempt to drop the value at *src."
     It means we should not access the old vaule, but the old value still alive, in this time(the read func return T), the two owners value happend, the code above show this issue. When the old value which do not impl Copy trait (in our case: String), the std::ptr::read will return another String, The old is also alive, So when end of the main func, the two String ptr to the same addr(own the same mem resource) will be drop twice, So the compiler abort and detected the double free.
    As you can see, i do not use the *src, So i do not violate the suggestion gived by the DOC, but i still get a double free abort.

2.  There are two method to away from this question, One is just like the annoted above. After call the std::ptr::read method, It's better to "forget" the old value at once.
     Another way is to add the code to std lib
```rust
#[inline]
#[stable(feature = "rust1", since = "1.0.0")]
#[rustc_const_unstable(feature = "const_ptr_read", issue = "80377")]
pub const unsafe fn read<T>(src: *const T) -> T {
    // We are calling the intrinsics directly to avoid function calls in the generated code
    // as `intrinsics::copy_nonoverlapping` is a wrapper function.
    extern "rust-intrinsic" {
        #[rustc_const_unstable(feature = "const_intrinsic_copy", issue = "80697")]
        fn copy_nonoverlapping<T>(src: *const T, dst: *mut T, count: usize);
    }

    let mut tmp = MaybeUninit::<T>::uninit();
    // SAFETY: the caller must guarantee that `src` is valid for reads.
    // `src` cannot overlap `tmp` because `tmp` was just allocated on
    // the stack as a separate allocated object.
    //
    // Also, since we just wrote a valid value into `tmp`, it is guaranteed
    // to be properly initialized.
    unsafe {
        copy_nonoverlapping(src, tmp.as_mut_ptr(), 1);
        intrinsics::forget(src);
        tmp.assume_init()
    }
}
```

3.    The basic reason cause this issue is the std::ptr::read start to read the nonCopy type value(like String), it just copy the stack part of the String to the new value, So the new value ptr to the same resource of the old value, at this time we should think that, the old value should be "forgot" by the compiler to move the ownship of this resource to the new value.

### Meta

`rustc --version --verbose`:
```
I just use the rust playground to test the code
stable version 1.54.0
DEBUG
2018 edition
```

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
Standard Error
Compiling playground v0.0.1 (/playground)
    Finished dev [unoptimized + debuginfo] target(s) in 1.92s
     Running `target/debug/playground`
free(): double free detected in tcache 2
timeout: the monitored command dumped core
/playground/tools/entrypoint.sh: line 11:     7 Aborted                 timeout --signal=KILL ${timeout} "$@"
```

</p>
</details>

**Comment by jonas-schievink** [comment]
This is working as intended. If you have questions about how to use the standard library, please ask them on https://users.rust-lang.org/.

**Comment by NightfallDM** [comment]
emmm, although i know what reason cause the double free abort, But why the Doc do not mention we should forget the old value to prevent the double free, and do not memtion the nonCopy type will be double free : >
By the way, thanks for your reply.
