### ISSUE TITLE
Add flag to modify the working directory assumed by the diagnostics

### ISSUE THREAD

**Issue by Manishearth** [rust-lang/rust#88754]
See https://github.com/rust-lang/cargo/issues/9887

Currently rustc prints diagnostics relative to the current working directory of its invocation. However, `cargo` has a habit of switching the CWD to the workspace root before invoking `rustc`, which means that the user's CWD ends up being something different.

It would be nice to have a flag (`--diagnostic-cwd`?) that lets you specify a path relative to which all diagnostics should be printed.

**Comment by camelid** [comment]
I wonder if [`--remap-path-prefix`](https://doc.rust-lang.org/nightly/rustc/command-line-arguments.html#--remap-path-prefix-remap-source-names-in-output) could be helpful for this?

**Comment by Manishearth** [comment]
Existing discussions: https://github.com/rust-lang/rust/issues/73740 https://github.com/rust-lang/rust/issues/87745

**Comment by Manishearth** [comment]
@camelid No, because that impacts the binary, and that would mean that `cargo build` would have to rebuild the crate every time you `cd` to a different folder in the workspace

**Comment by Urgau** [comment]
We now have [`--remap-path-scope`](https://doc.rust-lang.org/nightly/unstable-book/compiler-flags/remap-path-scope.html) from [trim-paths RFC 3127](https://github.com/rust-lang/rust/issues/111540) that applies scopes to the remap path prefixes such as `--remap-path-scope=diagnostics` which applies the remapping only for the diagnostics.

Closing in favour of the [tracking issue](https://github.com/rust-lang/rust/issues/111540).
