### ISSUE TITLE
UWP implementations weren't updated for I/O safety

### ISSUE THREAD

**Issue by jdm** [rust-lang/rust#88764]
https://github.com/rust-lang/rust/commit/d15418586ca78ead4f87ad18fcffa3550c1b169e updated lots of code in library/std/src/sys/windows/ to use the new APIs, but did not modify usages in the conitional UWP implementations like:
* https://github.com/rust-lang/rust/blob/47ae8deb8a35030bdc4e502b03400800864cc264/library/std/src/sys/windows/fs.rs#L360
* https://github.com/rust-lang/rust/blob/master/library/std/src/sys/windows/fs.rs#L388
* https://github.com/rust-lang/rust/blob/47ae8deb8a35030bdc4e502b03400800864cc264/library/std/src/sys/windows/stdio_uwp.rs#L28-L29
* https://github.com/rust-lang/rust/blob/47ae8deb8a35030bdc4e502b03400800864cc264/library/std/src/sys/windows/stdio_uwp.rs#L41-L42

This manifests as a bunch of compile errors when building with `--target x86_64-uwp-windows-msvc` and `-Z build-std`.

**Comment by apiraino** [comment]
Assigning priority as discussed in the [Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2388764.20UWP.20implementations.20weren't.20updated.20for.20I.2FO.20safety) of the Prioritization Working Group.

@rustbot label -I-prioritize +P-high

**Comment by hyd-dev** [comment]
I looks like that #88587 is intended to fix this.

**Comment by nbdd0121** [comment]
Given that #89527 contains #88587, should this be closed?
