### ISSUE TITLE
My function name is a string. If I want to implement such a call method, how can I implement it?

### ISSUE THREAD

**Issue by zhangwuqiao** [rust-lang/rust#88773]
fn add(a:i32, b:i32) -> i32{
    a+b
}

fn main(){
	let fname = "add"; 
	let c = fname(5, 6);
	println!("add :{}", c);
}

------------------------------
My function name is a string. If I want to implement such a call method, how can I implement it?

**Comment by jonas-schievink** [comment]
Hi! This issue tracker is mainly meant for bug reports and concrete, small feature requests. Questions like this are better asked in the user forum at https://users.rust-lang.org/ or on [one of the chat platforms](https://www.rust-lang.org/community) used by the Rust community.
