### ISSUE TITLE
Returned std::io::ErrorKind against the same I/O operation differs between 1.54.0 and 1.55.0

### ISSUE THREAD

**Issue by magurotuna** [rust-lang/rust#88787]
First, I created `foo.txt` in the crate root directory. Then I tried this code:

```rust
use std::fs::OpenOptions;
use std::io::prelude::*;

fn main() {
    let mut file = OpenOptions::new().read(true).open("foo.txt").unwrap();
    writeln!(file, "hello").unwrap();
}
```

This code is supposed to fail since I opened the file with read permission only, but attempted to write data to it.

When running this code on 1.54.0, I got:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 9, kind: Other, message: "Bad file descriptor" }', src/main.rs:6:29
```

On 1.55.0 (`rustc 1.57.0-nightly (97032a6df 2021-09-08)` also shows the same output):

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 9, kind: Uncategorized, message: "Bad file descriptor" }', src/main.rs:6:29
```

As you can see, the returned kind is different - on 1.54.0, it's `Other`, while on 1.55.0 and nightly, it's `Uncategorized`.

So the question is, is this change intentional?

**Comment by jonas-schievink** [comment]
See https://blog.rust-lang.org/2021/09/09/Rust-1.55.0.html#stdioerrorkind-variants-updated

**Comment by magurotuna** [comment]
Oh I missed that. Thank for the quick reply!
