### ISSUE TITLE
E0277 UI Testing Normalization

### ISSUE THREAD

**Issue by kflansburg** [rust-lang/rust#88819]
Moving from Rust 1.54.0 to 1.55.0, the output for E0277 appears to have changed to become more descriptive (🎉 yay!). 

**Original**

```rust
 error[E0277]: the trait bound `TestState: TransitionTo<_>` is not satisfied
   --> $DIR/require_transition_to.rs:38:9
    |
 38 |         Transition::next(self, TestState)
    |         ^^^^^^^^^^^^^^^^ the trait `TransitionTo<_>` is not implemented for `TestState`
    |
   = note: required by `Transition::<S>::next`
```

**New**

```rust
 error[E0277]: the trait bound `TestState: TransitionTo<_>` is not satisfied
   --> $DIR/require_transition_to.rs:38:9
    |
 38 |         Transition::next(self, TestState)
    |         ^^^^^^^^^^^^^^^^ the trait `TransitionTo<_>` is not implemented for `TestState`
    |
note: required by `Transition::<S>::next`
  --> /home/runner/work/krator/krator/krator/src/state.rs:43:5
   |
43 | /     pub fn next<I: State<S>, O: State<S>>(_i: Box<I>, o: O) -> Transition<S>
44 | |     where
45 | |         I: TransitionTo<O>,
   | |___________________________^
```

Unfortunately, it does not look like UI testing normalization is being applied to the new output section. By my reading [here](https://rustc-dev-guide.rust-lang.org/tests/adding.html#output-normalization), all line numbers, column numbers, and source paths should be normalized. It mentions _not_ normalizing under some circumstances, but I believe that only applies to line and column numbers for _test_ files, whereas our main issue is with the file path for the source file.  

I expected to see this happen **(Note line numbers and source path in second section):** 

```rust
 error[E0277]: the trait bound `TestState: TransitionTo<_>` is not satisfied
   --> $DIR/require_transition_to.rs:38:9
    |
 38 |         Transition::next(self, TestState)
    |         ^^^^^^^^^^^^^^^^ the trait `TransitionTo<_>` is not implemented for `TestState`
    |
note: required by `Transition::<S>::next`
  --> $SRC_DIR/src/state.rs:LL:CC
   |
LL | /     pub fn next<I: State<S>, O: State<S>>(_i: Box<I>, o: O) -> Transition<S>
LL | |     where
LL | |         I: TransitionTo<O>,
   | |___________________________^
```

Apologies if this is not a compiler issue, or is expected behavior. If so, please let me know!

### Meta

`rustc --version --verbose`:
```
rustc 1.55.0 (c8dfcfe04 2021-09-06)
binary: rustc
commit-hash: c8dfcfe046a7680554bf4eb612bad840e7631c4b
commit-date: 2021-09-06
host: aarch64-apple-darwin
release: 1.55.0
LLVM version: 12.0.1
```

<details><summary>Backtrace</summary>
<p>

```
N/A
```

</p>
</details>

**Comment by ehuss** [comment]
Can you say more about what the context here is, or a precise reproduction?  Normalization is done for testing of rustc's output. There are two parts to the normalization, that done by rustc with the `-Zui-testing` flag (which is a nightly only), and the normalization done by compiletest. Grabbing the example code for E0277:

```rust
// here we declare the Foo trait with a bar method
trait Foo {
    fn bar(&self);
}

// we now declare a function which takes an object implementing the Foo trait
fn some_func<T: Foo>(foo: T) {
    foo.bar();
}

fn main() {
    // we now call the method with the i32 type, which doesn't implement
    // the Foo trait
    some_func(5i32); // error: the trait bound `i32 : Foo` is not satisfied
}
```

and running `rustc +nightly -Zui-testing foo.rs`:

```
error[E0277]: the trait bound `i32: Foo` is not satisfied
  --> foo.rs:14:15
   |
LL |     some_func(5i32); // error: the trait bound `i32 : Foo` is not satisfied
   |               ^^^^ the trait `Foo` is not implemented for `i32`
   |
note: required by a bound in `some_func`
  --> foo.rs:7:17
   |
LL | fn some_func<T: Foo>(foo: T) {
   |                 ^^^ required by this bound in `some_func`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
```

Here the line numbers are replaced with LL.  

Are you running `x.py test --bless` and not getting the correct output?

**Comment by kflansburg** [comment]
Hey Eric, thanks for the response. We are using `compiletest`, our configuration is [here](https://github.com/krator-rs/krator/blob/main/krator/tests/ui.rs).

It sounds like this may be an issue then with `compiletest` normalization. 

Do you think the best approach would be to switch to nightly for our UI tests and take advantage of `-Z ui-testing`? It doesn't seem right to me to expect `compiletest` to reimplement this behavior.

Thanks!

**Comment by ehuss** [comment]
Ah, yea, I don't think compiletest can handle all the normalization on its own.  `-Z ui-testing` will be required for the line numbers.

**Comment by kflansburg** [comment]
Great, thanks! Sorry for the noise.

**Comment by kflansburg** [comment]
Hey @ehuss , I switched to nightly and enabled the `ui-testing` compiler option. The line numbers are now normalized as expected, however the file path still does not appear to be normalized. Do you know if this is expected behavior?

```
 error[E0277]: the trait bound `OtherState: krator::State<PodState>` is not satisfied
   --> $DIR/require_same_object_state.rs:50:9
    |
 LL |         Transition::next(self, OtherState)
    |         ^^^^^^^^^^^^^^^^ the trait `krator::State<PodState>` is not implemented for `OtherState`
    |
    = help: the following implementations were found:
              <OtherState as krator::State<OtherPodState>>
 note: required by `Transition::<S>::next`
-  --> $SRC_DIR/krator/src/state.rs:43:5
+  --> /Users/kevin/moose/krator-rs/krator/krator/src/state.rs:43:5
    |
 LL | /     pub fn next<I: State<S>, O: State<S>>(_i: Box<I>, o: O) -> Transition<S>
 LL | |     where
 LL | |         I: TransitionTo<O>,
    | |___________________________^

 error: aborting due to previous error

 For more information about this error, try `rustc --explain E0277`.
```

**Comment by ehuss** [comment]
It looks like you are using `compiletest_rs`, which is not necessarily the same as the compiletest used here. Unfortunately I don't know much about it.  The normalization done in the rustc compiletest is [here](https://github.com/rust-lang/rust/blob/641e02f388acc6b1d316a59c605a32d1711a8758/src/tools/compiletest/src/runtest.rs#L3652-L3737). I would check that you are passing in all the correct flags for that normalization to be done.

**Comment by kflansburg** [comment]
@ehuss It's true we are using `compiletest_rs`, however I'm fairly confident that `rustc` is performing the normalization. `compiletest_rs` allows you to specify rustc flags, and if you look at the most recent output, there is _some_ normalization happening now (line numbers). 

I have put together a minimum reproduction of the issue, [here](https://github.com/kflansburg/ui-testing-repro), 

as you can see, the full path to the source file where the trait constraint is defined is output. This only appears to happen when the source file is in a separate crate from the invocation (i.e. with tests here), and not when it is all placed in a single file as you demonstrated in Rust playground. 

I don't fully understand where `rustc` begins and `cargo` ends when it comes to producing errors like this, so this might be a cargo issue?

**Comment by ehuss** [comment]
Sorry, I'm not sure what you are asking.  Replacement of full paths to `$DIR` for the purpose of comparing test output is done in the part of compiletest I linked above.  As mentioned, there are two parts of normalization, that done by rustc running `-Zui-testing`, and the normalization done in compiletest in the `normalize_output` function.  

You may want to check that you are passing a full path to `--src-base`, as that is what is used for `$DIR` replacement.

If you're asking why does `rustc` use absolute paths for external crates, that's just something it normally does.  I think in theory it could use something like `pathdiff` to determine if it can shorten the path in the diagnostics, but I suspect that would be quite tricky.

Otherwise, I don't think I can provide support for using `compiletest_rs`.  If you are having more trouble, I would recommend instrumenting or debugging the `normalize_output` function to see why it isn't working for you.
