### ISSUE TITLE
Tracking Issue for `#![feature(const_unsafecell_get_mut)]`

### ISSUE THREAD

**Issue by WaffleLapkin** [rust-lang/rust#88836]
Feature gate: `#![feature(const_unsafecell_get_mut)]`

This is a tracking issue for `UnsafeCell::get_mut` as a const fn.

### Public API

```rust
// core::cell

impl<T> UnsafeCell<T> {
    pub const fn get_mut(&mut self) -> &mut T;
}
```

### Steps / History

- [x] Implementation: #88722
- [ ] Final comment period (FCP)
- [ ] Stabilization PR

### Unresolved Questions

- None yet.

**Comment by RalfJung** [comment]
Cc @rust-lang/wg-const-eval

**Comment by tgross35** [comment]
This is blocked on https://github.com/rust-lang/rust/issues/57349, correct?

**Comment by RalfJung** [comment]
Yeah, pretty much all the mutable reference/pointer stuff in `const` is blocked on that.

**Comment by workingjubilee** [comment]
etc. etc. #57349 landed now let's see if we have consensus for stabilizing this?

**Comment by dtolnay** [comment]
@rfcbot fcp merge

`const` for https://doc.rust-lang.org/nightly/std/cell/struct.UnsafeCell.html#method.get_mut
