### ISSUE TITLE
Strange interoperation with macros 2.0

### ISSUE THREAD

**Issue by crlf0710** [rust-lang/rust#88843]
When using macros 2.0, i observed this behavior. I'm unsure whether there's a bug or not, but i think this is inconsistent.

```rust
#![feature(decl_macro)]
#![allow(unused)]

macro foo_b($x:expr, $f: ident) {{
    $x = $f::A;
}}

macro some_macro() {
    enum Foo {
        A
    }
    macro foo_a($x:expr, $f: ident) {{
        $x = $f::A;
    }}
    let foo;
    //foo_a!(foo, Foo);    // this also works.
    foo_b!(foo, Foo);
}

fn some_fn() {
    enum Foo {
        A
    }
    macro foo_a($x:expr, $f: ident) {{
        $x = $f::A;
    }}
    let foo;
    foo_b!(foo, Foo);
}

fn main() {
    //some_fn();     // this works fine
    some_macro!();   // this doesn't
}
```
Basically if i'm using `foo_a` macro version or `some_fn` version, everything works fine.
But when i'm using `some_macro` version, it complains that `A` is not a variant.

I think `foo_a` and `foo_b` should behave consistently, at least. And I believe this is `hygiene` related.

cc @petrochenkov

**Comment by petrochenkov** [comment]
This looks correct, you cannot refer to `A` in `some_macro::Foo::A` from outside of `some_macro` (e.g. from `foo_b`).

**Comment by crlf0710** [comment]
Oh, thanks! Closing as this is expected behavior.
