### ISSUE TITLE
rustdoc (unstable): `--generate-link-to-definition` makes sources unreadable with Ayu theme

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#88870]
Interestingly, the dark theme works fine.

Screenshot of Ayu:

![image](https://user-images.githubusercontent.com/37223377/132966254-bba2066e-38c7-482c-aa9d-4b2544fc7928.png)

cc @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
Sending a fix in the next few hours.
