### ISSUE TITLE
Allow some lints in `.fixed` files when compiling with Compiletest

### ISSUE THREAD

**Issue by xFrednet** [rust-lang/rust#88918]
See also Manishearth/compiletest-rs#243

Compiletest currently automatically allows all `unused` lints in the `CompileFail` and `Ui` modes. However, this doesn't extend to `.fixed` files, which are used inside Clippy. For this reason, we still have a bunch of `#[allow()]` attributes in Clippy's tests. It would be nice to have an option to allow lints inside `.fixed` compilation tests.

In a related discussion (See rust-lang/rust-clippy#7611), we agreed that it would also be cool, if we could be more specific than just allowing all lint's inside the `unused` group. I would suggest adding a new configuration with an enum like this:

```rs
pub enum LintConfiguration {
    /// No lints are automatically allowed
    None,
    /// All lints inside the `unused` lint group are allowed
    UnusedLints,
    /// List of lints that should be allowed. The names should be
    /// provided in the console format using dashes
    SpecificLints(&[&str])
}
```

Clippy uses `compiletest-rs` which is the downstream crate currently managed by @Manishearth. It would be great if this implementation could be done here and then transferred into `compiletest-rs` to keep them kind of in sync.

---

I'm currently quite busy with RL stuff, but would be happy to work on this in about a month, if it would be accepted in rustc's compiletest version. Any feedback regarding the idea is welcome!

---

cc: @rust-lang/devtools @Manishearth

@rustbot label +A-testsuite +C-enhancement +T-dev-tools

**Comment by jieyouxu** [comment]
@xFrednet ping from uhh I guess triage, since AFAIK clippy uses `ui_test`, is this still relevant?

**Comment by xFrednet** [comment]
Thank you for the ping. I think it would still be a good feature to have, but it's not a priority rn. If the topic comes up again, I'll create an issue in the `ui_test` crate. :D
