### ISSUE TITLE
LLD is not available with `download-ci-llvm`

### ISSUE THREAD

**Issue by Aaron1011** [rust-lang/rust#88941]
When `download-ci-llvm=true` is set, `lld` is not available in `build/x86_64-unknown-linux-gnu/ci-llvm/bin`. This makes it more difficult to use a stage1 compiler to cross-compile to platforms that use LLD by default (like `wasm32-unknonwn-unknown`), as the linker needs to be manually overridden in a `.cargo/config` file.

If we have the CI budget available, it would be useful to build LLD along with LLVM, and make it available in the archive downloaded by `x.py`.

**Comment by Mark-Simulacrum** [comment]
We just need to adjust the component creation to include LLD -- at least on x86_64-unknown-linux-gnu it's already built.
