### ISSUE TITLE
GAT & TAIT with lifetime type parameters fail `std::marker::Sized` requirement

### ISSUE THREAD

**Issue by rustrial** [rust-lang/rust#89008]
Playing around with (the not yet stable) [GAT](https://github.com/rust-lang/rust/issues/44265) and [TAIT](https://github.com/rust-lang/rust/issues/63063) features I stumbled over the below problem, where type parameters to nested TAIT/GAT with lifetime parameters cause a "this type parameter needs to be std::marker::Sized" compiler error.

The following code fails to compile with below compiler error ([Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=d084b59d61d50be4b8c0015a65dc1579)):

```rust
#![feature(type_alias_impl_trait)]
#![feature(generic_associated_types)]

extern crate futures;
use futures::Stream;
use std::future::Future;

trait X {
    type LineStream<'a, Repr>: Stream<Item = Repr> where Self: 'a;

    type LineStreamFut<'a,Repr>: Future<Output = Self::LineStream<'a, Repr>> where Self: 'a;

    fn line_stream<'a,Repr>(&'a self) -> Self::LineStreamFut<'a,Repr>;
}

struct Y;

impl X for Y {
    type LineStream<'a, Repr> = impl Stream<Item = Repr>;

    type LineStreamFut<'a, Repr> = impl Future<Output = Self::LineStream<'a, Repr>> ;

    fn line_stream<'a, Repr>(&'a self) -> Self::LineStreamFut<'a, Repr> {
        async {futures::stream::empty()}
    }
}

fn main() {}
```

```
warning: the cargo feature `edition2021` has been stabilized in the 1.56 release and is no longer necessary to be listed in the manifest
  See https://doc.rust-lang.org/nightly/cargo/reference/manifest.html#the-edition-field for more information about using this feature.
   Compiling playground v0.0.1 (/playground)
error[E0277]: the size for values of type `Repr` cannot be known at compilation time
  --> src/main.rs:23:43
   |
23 |     fn line_stream<'a, Repr>(&'a self) -> Self::LineStreamFut<'a, Repr> {
   |                        ----               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ doesn't have a size known at compile-time
   |                        |
   |                        this type parameter needs to be `std::marker::Sized`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `playground` due to previous error
```

In contrast, the following code, without lifetime type parameters compiles without any error.

```rust
#![feature(type_alias_impl_trait)]
#![feature(generic_associated_types)]

extern crate futures;
use futures::Stream;
use std::future::Future;

trait X {
    type LineStream<Repr>: Stream<Item = Repr>;

    type LineStreamFut<Repr>: Future<Output = Self::LineStream<Repr>>;

    fn line_stream<Repr>(&self) -> Self::LineStreamFut<Repr>;
}

struct Y;

impl X for Y {
    type LineStream<Repr> = impl Stream<Item = Repr>;

    type LineStreamFut<Repr> = impl Future<Output = Self::LineStream<Repr>> ;

    fn line_stream<Repr>(&self) -> Self::LineStreamFut<Repr> {
        async {futures::stream::empty()}
    }
}

fn main() {}
```
---

### Meta

`cargo version --verbose`:
```
cargo 1.56.0-nightly (e515c3277 2021-09-08)
release: 1.56.0
commit-hash: e515c3277bf0681bfc79a9e763861bfe26bb05db
commit-date: 2021-09-08
```

**Comment by oli-obk** [comment]
Compiles just fine now.

**Comment by oli-obk** [comment]
@jackh726 I guess this issue can just be closed if there's a test already?

**Comment by SarthakSingh31** [comment]
Hello, first time contributing to rust. I was trying to resolve this issue and after looking at the test I am a little confused. To me it looks like the test code is failing correctly and I can't understand where the TAIT bug is.

https://github.com/rust-lang/rust/blob/ebdde35dced40adb46f8aad054fb2adb86b39427/src/test/ui/generic-associated-types/bugs/issue-89008.rs#L1-L43

`<Empty<T> as Steam>::Item` has a concrete type `()` whereas the `line_stream` function is generic over `Steam::Item`. So to me it looks like the raised error is correct.

https://github.com/rust-lang/rust/blob/ebdde35dced40adb46f8aad054fb2adb86b39427/src/test/ui/generic-associated-types/bugs/issue-89008.stderr#L1-L15

Changing the `Stream` implementation to

```rust
impl<T> Stream for Empty<T> {
    type Item = T;
}
```

makes the code compile.

I am sorry if I am missing something here. If the test is correct then would moving the test to `src/test/ui/type-alias-impl-trait` resolve this issue? @jackh726

I also don't think #88908 relates to this test.

**Comment by jackh726** [comment]
Yeah, I messed up my minimization. The test should just use the original MCVE in the OP. And that is indeed fixed.

**Comment by jackh726** [comment]
For clarity: this can be closed when the current known-bug test is moved to the main directory for GAT tests and changed to use the OP MCVE.
