### ISSUE TITLE
Point at bound introducing obligation of call parameter for where clause bounds

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#89038]
The following code

https://github.com/rust-lang/rust/blob/38e576423dc56a006ccf0b72e106f09bdea6efc2/src/test/ui/where-clauses/where-clauses-method-unsatisfied.rs#L10-L20

emits

https://github.com/rust-lang/rust/blob/38e576423dc56a006ccf0b72e106f09bdea6efc2/src/test/ui/where-clauses/where-clauses-method-unsatisfied.stderr#L1-L9

It should point at the `where T : Eq` bound as well.

Noticed in https://github.com/rust-lang/rust/pull/88719/files#r708156543:

> This case has a `MiscObligation`, so for some where clauses we need to do better, but at least we point at the relevant argument. The new span pointing at the call at least hints at the user that they should look at the equals implementation to figure out why the bound was added.

**Comment by compiler-errors** [comment]
Was this fixed by #89580?

**Comment by compiler-errors** [comment]
For the record, we now error with:

```
error[[E0277]](https://doc.rust-lang.org/stable/error-index.html#E0277): the trait bound `Bar: Eq` is not satisfied
  --> src/main.rs:13:15
   |
13 |      x.equals(&x); 
   |        ------ ^^ the trait `Eq` is not implemented for `Bar`
   |        |
   |        required by a bound introduced by this call
   |
note: required by a bound in `Foo::<T>::equals`
  --> src/main.rs:6:53
   |
6  |      fn equals(&self, u: &Foo<T>) -> bool where T : Eq { 
   |                                                     ^^ required by this bound in `Foo::<T>::equals`
help: consider annotating `Bar` with `#[derive(Eq)]`
   |
1  | #[derive(Eq)]
   |
```

Note the "note"

**Comment by estebank** [comment]
Yeah, that seems good to me.
