### ISSUE TITLE
Suggest annotating traits rather than methods when appropriate

### ISSUE THREAD

**Issue by hkmatsumoto** [rust-lang/rust#89064]
Given the following code: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=d2a32fe1f3460b6583534eb53d045165

```rust
fn foo() {
    let _ = "foo".into::<Option<_>>();
}
```

The current output is:

```
Compiling playground v0.0.1 (/playground)
error[E0107]: this associated function takes 0 generic arguments but 1 generic argument was supplied
   --> src/lib.rs:2:19
    |
2   |     let _ = "foo".into::<Option<_>>();
    |                   ^^^^------------- help: remove these generics
    |                   |
    |                   expected 0 generic arguments
    |
note: associated function defined here, with 0 generic parameters

For more information about this error, try `rustc --explain E0107`.
error: could not compile `playground` due to previous error
```

Ideally the output should look like:

```
error[E0107]: this associated function takes 0 generic arguments but 1 generic argument was supplied
   --> src/lib.rs:2:19
    |
2   |     let _ = "foo".into::<Option<_>>();
    |                   ^^^^------------- help: remove these generics
    |                   |
    |                   expected 0 generic arguments
    |
note: associated function defined here, with 0 generic parameters
help: `Into` trait takes 1 generic argument, try annotating that instead: `Into::<Option<_>>::into("foo")
```

When a user called `into()` with an annotation, it's helpful to suggest `T::from(_)` too.

**Comment by chansuke** [comment]
@hkmatsumoto If it's ok, I would like to give a shot. If you plan to work on it, please go ahead.

**Comment by hkmatsumoto** [comment]
It's yours :)
@rustbot assign @chansuke

**Comment by hkmatsumoto** [comment]
> My plan is that start adding some fields (like ty::TraitRef) to pub struct WrrongnarofGenericArgs<'a, 'tcx> {} and dbg! the output to get the value of trait information like Into for a new error message.

You don't have to hold information of `TraitRef` in `WrongNumberOfGenericArgs` because we can get the info on-demand by the combination of `TyCtxt::trait_of_item` and `TyCtxt::generics_of`.
Say you'd add a method of `WrongNumberOfGenericArgs`, the code will be something like this:
```rust
let trait_: Option<DefId> = self.tcx.trait_of_item(self.def_id);
let generics: &Generics = self.tcx.generics_of(trt.unwrap());
```

**Comment by vincenzopalazzo** [comment]
@chansuke are you still working on this? :)
