### ISSUE TITLE
Actual type given in compiler error, rather than generic paramater

### ISSUE THREAD

**Issue by TheDutchMC** [rust-lang/rust#89181]
I tried this code:
```rust
    pub async fn new<'a, U: AsRef<str>, P: AsRef<str>>(email: U, password: P) -> Result<Self> {
        Self::login(email, password).await // Note that using email.as_ref() results in the same error, and in the same 'wrongly' mentioned line 
    }

    pub async fn login<U: AsRef<str>, P: AsRef<str>>(email: U, password: P) -> Result<Self> {
        ...
    }
```

I expected to see this happen: *explanation*
Either Rust compiles the code, or reports an issue, where the lines reported are the lines I've given it

Instead, this happened: *explanation*
Rust fails to compile (Probably correct), give's back a line of code with the generics substituted for their real types, in this case `&str`

The compiler emitted the following error:
```
error[E0621]: explicit lifetime required in the type of `email_address`
  --> src/tcc.rs:29:13
   |
25 |     fn new(email_address: &str, password: &str) -> Self {
   |                           ---- help: add explicit lifetime `'a` to the type of `email_address`: `&'a str`
...
29 |             email_address,
   |             ^^^^^^^^^^^^^ lifetime `'a` required

error[E0621]: explicit lifetime required in the type of `password`
  --> src/tcc.rs:31:13
   |
25 |     fn new(email_address: &str, password: &str) -> Self {
   |                                           ---- help: add explicit lifetime `'a` to the type of `password`: `&'a str`
...
31 |             password,
   |             ^^^^^^^^ lifetime `'a` required
```
While the error is probably correct, the represented line is likely not. 

The folk who've worked with Rust for a while know that the compiler generates a function for each type used, but new people may not know this, and might thus end up looking for a function with `&str`, which does not exist in their code.

### Meta

`rustc --version --verbose`:
```
cargo 1.56.0-nightly (e515c3277 2021-09-08)
cargo 1.55.0 (32da73ab1 2021-08-23)
```

<details><summary>Backtrace</summary>
<p>
None was given

</p>
</details>

**Comment by SNCPlay42** [comment]
Compiler diagnostics use spans that always point into the original source code, and it should be impossible for the compiler's internal transformations to change that original source. Are you *sure* that the error messages are pointing at the function in the code snippet you've given? Because the parameter `email`'s name has also changed to `email_address`, the return type has changed from `Result<Self>` to `Self`, and the function has stopped being `pub async`.

**Comment by TheDutchMC** [comment]
oh damn indeed. I was looking at the completely wrong signature. Sorry, and thanks!
