### ISSUE TITLE
DNS name resolution more than getaddrinfo()

### ISSUE THREAD

**Issue by sanxiyn** [rust-lang/rust#8925]
There should be a way to do DNS name resolution in the standard library.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#654
