### ISSUE TITLE
Tracking issue for const char conversions

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#89259]
This is a tracking issue for const char conversions. List of functions belonging to `!#[feature(const_char_from_u32_unchecked)]`:

```Rust
impl char {
    pub const unsafe fn from_u32_unchecked(i: u32) -> char;
}

// Available through core::char and std::char
mod char {
    pub const unsafe fn from_u32_unchecked(i: u32) -> char;
}
```

~~List of functions belonging to stable `#![feature(const_char_convert)]`:~~

<details>

```Rust
impl char {
    pub const fn from_u32(self, i: u32) -> Option<char>;
    pub const fn from_digit(self, num: u32, radix: u32) -> Option<char>;
    pub const fn to_digit(self, radix: u32) -> Option<u32>;
}

// Available through core::char and std::char
mod char {
    pub const fn from_u32(i: u32) -> Option<char>;
    pub const fn from_digit(num: u32, radix: u32) -> Option<char>;
}
```
</details>

Steps:

* Introduced by #89258
* Partially stabilized by #102470 , `const_char_from_u32_unchecked` is still unstable.
* ~~Stabilization is probably blocked by [const panicing](https://github.com/rust-lang/rust/issues/89006).~~ Edit: const panic is stable now!
* ~~Stabilization is blocked by [Option::unwrap](https://github.com/rust-lang/rust/issues/67441) const stability, which is blocked by #73255.~~
* https://github.com/rust-lang/rust/pull/126958

**Comment by leonardo-m** [comment]
We could keep a percentage counter somewhere that tells how much of stdlib is areweconstyet :)

**Comment by Nugine** [comment]
Hi! Is there any plan of stabilization?

**Comment by est31** [comment]
@Nugine I've made a stabilization PR, let's see where this goes: #102470

**Comment by ChrisDenton** [comment]
> Stabilization is blocked by https://github.com/rust-lang/rust/issues/67441 const stability, which is blocked by https://github.com/rust-lang/rust/issues/73255.

Could we not manually write out a match statement instead of using `unwrap`?

**Comment by est31** [comment]
I think the idea was that there should be no extra hacks done just to get things compatible with const fn, but I don't remember it fully any more.

**Comment by ChrisDenton** [comment]
I've opened #118979 to see what T-libs thinks about it.

**Comment by ChrisDenton** [comment]
#118979 is now merged so I think there's no blocker for `from_u32_unchecked` being stabilized as const.

**Comment by dtolnay** [comment]
@rust-lang/libs-api:
@rfcbot fcp merge

I propose stabilizing `const` for the existing `core::char::from_u32_unchecked` function (stable since Rust 1.5) and `<char>::from_u32_unchecked` associated function (stable since Rust 1.52).

These functions were left out of the initial set of `feature(const_char_convert)` stabilizations in https://github.com/rust-lang/rust/pull/102470, but have since been unblocked by https://github.com/rust-lang/rust/pull/118979.

If `unsafe { from_u32_unchecked(u) }` is called in const with a value for which `from_u32(u)` returns None, we get the following compile error.

```rust
fn main() {
    let _ = const { unsafe { char::from_u32_unchecked(0xd800) } };
}
```

```console
error[E0080]: it is undefined behavior to use this value
 --> src/main.rs:2:19
  |
2 |     let _ = const { unsafe { char::from_u32_unchecked(0xd800) } };
  |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ constructing invalid value: encountered 0x0000d800, but expected a valid unicode scalar value (in `0..=0x10FFFF` but not in `0xD800..=0xDFFF`)
  |
  = note: The rules on what exactly is undefined behavior aren't clear, so this check might be overzealous. Please open an issue on the rustc repository if you believe it should not be considered undefined behavior.
  = note: the raw bytes of the constant (size: 4, align: 4) {
              00 d8 00 00                                     │ ....
          }

note: erroneous constant encountered
 --> src/main.rs:2:13
  |
2 |     let _ = const { unsafe { char::from_u32_unchecked(0xd800) } };
  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by RalfJung** [comment]
> If unsafe { from_u32_unchecked(u) } is called in const with a value for which from_u32(u) returns None, we get the following compile error.

Note that this is the error you get when the *final value* of the const is an invalid `char`.

If you ignore the return value of `from_u32_unchecked`, likely there will be no error.
