### ISSUE TITLE
Tracking Issue for `varerror_methods`

### ISSUE THREAD

**Issue by ohsayan** [rust-lang/rust#89302]
Feature gate: `#![feature(varerror_methods)]`

This is a tracking issue for the `varerror_methods` feature that adds two methods to `std::env::VarError`:
- `is_absent`: Which simply checks if the error resulted from a missing variable
- `is_unicode_error`: Which checks if the error resulted from unicode parsing failure

Generally, these methods make it more convenient to check if an environment variable was present, absent or failed to parse.

### Public API
```rust
use std::env;

fn main() {
    let var = env::var("bad_unicode");
    if var.is_unicode_error() {
        println!("Uh oh, your variable had incorrect unicode data");
    }
}
```

### Steps / History

- [x] Implementation (see #89301)
- [ ] Tests
- [ ] Stabilization PR

### Unresolved Questions

- None yet.

**Comment by memoryruins** [comment]
Should this be closed based on the reasoning in https://github.com/rust-lang/rust/pull/89301#issuecomment-932171065 ?

**Comment by ohsayan** [comment]
> Should this be closed based on the reasoning in https://github.com/rust-lang/rust/pull/89301#issuecomment-932171065 ?

Thanks for reminding. Forgot about this!
