### ISSUE TITLE
Windows LLVM Sanitizer Support

### ISSUE THREAD

**Issue by voteblake** [rust-lang/rust#89339]
In an effort to fuzz a Windows-specific Rust program with `cargo-fuzz` I've done a bit of digging that leads me to think the compiler is the current blocker.

[`cargo-fuzz`](https://github.com/rust-fuzz/cargo-fuzz) mentions [`libFuzzer`](https://llvm.org/docs/LibFuzzer.html) "only works on x86-64 Linux and x86-64 macOS for now". The `libFuzzer` docs in turn suggest Windows should now be [support-able](https://llvm.org/docs/LibFuzzer.html#q-does-libfuzzer-support-windows), and the LLVM [AddressSanitizer](https://clang.llvm.org/docs/AddressSanitizer.html) documentation appears to agree.

Looking at the history of sanitizer discussion here I see Windows support being mentioned as possible as early as 2017 https://github.com/rust-lang/rust/issues/39699#issuecomment-297589826. Windows support was also mentioned in https://github.com/rust-lang/rust/issues/47174 as part of the discussion on stabilizing the -Z sanitize options.

I'm opening this issue to document the data I've gathered, ask for input on if I'm understanding the current state correctly, and also understand if anyone is working on this. I may be able to help, but am not an experienced contributor to the compiler. I've started to work locally to understand what this change would look like if it is in-fact possible.

**Comment by voteblake** [comment]
Hi @danielframpton - thanks for tagging this in your PR yesterday, it was great to see that. Very timely! I wanted to invite you to use this issue to track any other outstanding work you're aware of to enable sanitizer support on Windows. If you have any areas you're looking for help or input on I can't guarantee I'd be useful but I'd be happy to try.

**Comment by workingjubilee** [comment]
Yes, this seems to be an accurate (partial) description. I am guessing you are mostly speaking about the the MSVC target as the linked document references `link.exe` arguments?

**Comment by voteblake** [comment]
All the digging I've done is MSVC specific, but the change in #89369 applies anywhere [`is_like_windows`](https://github.com/rust-lang/rust/blob/1d71ba862309d59df710078a845c8772ffb22aba/compiler/rustc_target/src/spec/mod.rs#L1155) not just [`is_like_msvc`](https://github.com/rust-lang/rust/blob/1d71ba862309d59df710078a845c8772ffb22aba/compiler/rustc_target/src/spec/mod.rs#L1165).
