### ISSUE TITLE
Feature gate new `non_exhaustive_omitted_patterns` lint

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#89374]
It will need to be feature-gated before it lands on stable in **1.57.0**.

cc https://github.com/rust-lang/rust/issues/89042#issuecomment-929464660
cc @Nadrieril 

This issue has been assigned to @DevinR528 via [this comment](https://github.com/rust-lang/rust/issues/89374#issuecomment-931657255).

**Comment by Nadrieril** [comment]
By when should the PR be merged if we want to get it in before 1.57.0 roughly?

**Comment by camelid** [comment]
I'm not 100% sure, but I think 1.57 will be promoted to beta in ~2 weeks. After that, the PR would need a backport to the beta branch in order to get it in before 1.57 is released as stable. (You can see the release dates [here](https://forge.rust-lang.org/#current-release-versions). Nightly branches off as beta around 7 weeks before it is released as stable IIRC.)

**Comment by camelid** [comment]
From https://github.com/rust-lang/rust/issues/89042#issuecomment-931497696:

> I can work on adding the feature gate I'll open a PR and cc both of you (as long as that's ok?).

@rustbot assign @DevinR528
