### ISSUE TITLE
`std::hash::Hash` documentation should suggest that the hash data should be prefix-free

### ISSUE THREAD

**Issue by kpreid** [rust-lang/rust#89429]
As discussed at [Why does `str.hash(…)` pass an extra byte to the Hasher?](https://users.rust-lang.org/t/why-does-str-hash-pass-an-extra-byte-to-the-hasher/65404): the code of `impl Hash for &str` specifically passes an extra 0xFF byte to the Hasher, so that values like `("ab", "c")` and `("a", "bc")` hash differently (added in https://github.com/rust-lang/rust/commit/6066118b2988fee1b758d542cee18ffe7a84acab).

This is a subtle property of hashing and should probably be mentioned in the documentation for `Hash` — _particularly_ as [the documentation for `Hasher`](https://doc.rust-lang.org/std/hash/trait.Hasher.html) already says “you cannot assume, for example, that a `write_u32` call is equivalent to four calls of `write_u8`” which could be sloppily interpreted as an expectation that a _good_ `Hasher` implementation will handle “quoting” of sequential calls itself.

If an implementor of `Hash` fails to have this property, it could compromise the hash-DoS resistance that Rust tries to offer by default.

@rustbot labels: +A-docs +T-libs-api +C-enhancement

**Comment by fosskers** [comment]
Should hand-implementors of `Hash` instances keep this in mind as well? For instance, for the following struct:
```rust
struct User {
    name: String,
    age: u32,
    cool: bool,
}
```
`rust-analyzer` can auto-generate the following implementation (and I assume `#[derive(Hash)]` does the same):
```rust
impl Hash for User {
    fn hash<H: Hasher>(&self, state: &mut H) {
        self.name.hash(state);
        self.age.hash(state);
        self.cool.hash(state);
    }
}
```
There are no magic bytes here, as in `str`. Is that okay?

**Comment by fosskers** [comment]
```rust
use std::collections::hash_map::DefaultHasher;
use std::hash::{Hash, Hasher};

#[derive(Hash)]
struct User {
    name: String,
    age: u32,
    cool: bool,
}

struct Boozer {
    name: String,
    age: u32,
    cool: bool,
}

impl Hash for Boozer {
    fn hash<H: Hasher>(&self, state: &mut H) {
        self.name.hash(state);
        self.age.hash(state);
        self.cool.hash(state);
    }
}

fn hash<H: Hash>(h: H) {
    let mut hasher = DefaultHasher::new();
    h.hash(&mut hasher);
    println!("{}", hasher.finish());
}

fn main() {
    let user = User {
        name: "Jack".to_string(),
        age: 8,
        cool: true,
    };
    let boozer = Boozer {
        name: "Jack".to_string(),
        age: 8,
        cool: true,
    };
    let tuple = ("Jack".to_string(), 8, true);

    hash(user);
    hash(boozer);
    hash(tuple);
}
```
The results are:
```
#+RESULTS:
: 10970795962411125193
: 10970795962411125193
: 10970795962411125193
```

**Comment by tczajka** [comment]
> Is that okay? Do we run the risk of this hashing to the same value as `(String, u32, bool)`? (Actually I will test this, one moment...)

Different types hashing to the same value are not a problem. What is a problem is different (unequal) values of the same type hashing to the same value (for all `Hasher`s).

**Comment by cuviper** [comment]
> Different types hashing to the same value are not a problem. What is a problem is different (unequal) values of the same type hashing to the same value (for all `Hasher`s).

Collisions are inevitable, and it shouldn't matter between `Hasher`s for the same reason it doesn't for different types.

I do agree that types should _try_ to avoid collisions, as long as we make this kind of thing a suggestion of best practice, not stated as a hard requirement of the trait.

**Comment by tczajka** [comment]
> Collisions are inevitable

Collisions in `Hasher` are inevitable. Collisions in `Hash` are not inevitable.

One benefit of not creating collisions in `Hash` is that it then is possible to implement a randomized `Hasher` with mathematically bounded small collision probability for any two unequal inputs (using universal hashing). If there is a deterministic collision in `Hash`, then it becomes impossible, because you have 100% collision probability for that pair of inputs.

**Comment by cuviper** [comment]
OK, that's a compelling distinction between the responsibilities of `Hash` and `Hasher`.

Is it *always* possible to do this perfectly on the `Hash` side? I suppose it must be -- if there's a distinction makes them different from an `Eq` perspective, that is an input that should also be used for hashing.

**Comment by kpreid** [comment]
[Trying again to set labels since I typoed the first one:]
@rustbot label: +A-docs +T-libs-api +C-enhancement

**Comment by tczajka** [comment]
> Is it _always_ possible to do this perfectly on the `Hash` side? I suppose it must be -- if there's a distinction makes them different from an `Eq` perspective, that is an input that should also be used for hashing.

I am not sure it's _always_ possible, in theory you could imagine some contrived `PartialEq` algorithm that makes it computationally expensive to `Hash` in a way fully consistent with it, but I can't think of a practical example.

I think it would be fine to say that if can't come up with a proper `Hash` algorithm that has this property, you shouldn't implement `Hash` (perhaps you'd be better served by `BTreeMap` in that case).

**Comment by pierwill** [comment]
For the docs, would it make sense to discuss the case of `impl Hash for &str` after this paragraph: https://github.com/rust-lang/rust/blob/ed937594d3912ced11f6f35a90bb8bf591909d2a/library/core/src/hash/mod.rs#L246-L249.

The paragraph could start with something like:

> For example, the code for `impl Hash for &str` passes an extra 0xFF byte to the Hasher, so that values like ("ab", "c") and ("a", "bc") hash differently.

**Comment by danielhenrymantilla** [comment]
Let's then note that `BTreeMap` `Hash` is thus currently "bugged" in that regard (_c.f._ my snippet in the URLO thread).

**Comment by pierwill** [comment]
I gave this a try! I might not have understood correctly, however...

**Comment by scottmcm** [comment]
FWIW, being prefix-free can also be unfortunate sometimes.  For example, `(T, T)` is more efficient to hash than `[T; 2]` because the latter hashes the length to match the hash of the corresponding `[T]` -- and slices do that so it's prefix-free.

I don't know that there's a great answer for this, though...

**Comment by cuviper** [comment]
> Let's then note that `BTreeMap` `Hash` is thus currently "bugged" in that regard (_c.f._ my snippet in the URLO thread).

See #89443.

**Comment by tczajka** [comment]
> For example, `(T, T)` is more efficient to hash than `[T; 2]` because the latter hashes the length to match the hash of the corresponding `[T]` -- and slices do that so it's prefix-free.

Is there a real reason `[T; 2]` and `[T]` of length 2 have to hash to the same thing? I don't think it's that easy to accidentally coerce them to a wrong thing when hashing (surely `HashMap` doesn't do that).

In any case, slices are already prefix-free (as long as T is) (and I think that's good, otherwise you'd have a lot of collisions on different short slices), so this issue doesn't change that.

**Comment by cuviper** [comment]
> Is there a real reason `[T; 2]` and `[T]` of length 2 have to hash to the same thing?

Yes, `Borrow` requires it.

**Comment by m-ou-se** [comment]
Nominated this for @rust-lang/libs-api discussion.

**Comment by scottmcm** [comment]
@tczajka I added a comment to the impl in https://github.com/rust-lang/rust/pull/86140 after I forget why it was that way too :)

**Comment by Amanieu** [comment]
One possibility would be to leave the choice of whether to add a prefix to the `Hasher` via some form of hint: performance-oriented hashers would opt to skip the prefix while security-oriented ones would opt to keep it.

This could be done with an optional method on the `Hasher` trait:
```rust
trait Hasher {
    // Option 1
    fn should_add_prefix(&self) -> bool { false }
    
    // Option 2
    fn write_prefix(&mut self, prefix: usize) { self.write_usize(prefix); }
}
```
