### ISSUE TITLE
Splitting up `compiletest::runtest`

### ISSUE THREAD

**Issue by Nicholas-Baron** [rust-lang/rust#89475]
Subtask to #60302.

- [ ] RunPassValgrind is practically useless (valgrind is not installed on CI, and the tests are just run in run-pass mode). The right approach here is likely to refactor it as a modifier atop the regular run-pass tests -- it looks like the code generally just mirrors the RunPass mode, other than setting the runtool to valgrind. That mode can be enabled in the configuration of the test with `// use-valgrind` or something like that.
- [x] Move diff computation out into a separate module (DiffLine, Mismatch, make_diff, ...)
- [x] Move read2_abbreviated to the read2.rs module
- [x] Move DebuggerCommands and their parsing out to a separate file, alongside check_debugger_output (which is similarly parsing code).

I suspect this set of changes is likely harder, and might not get to <3000 lines; there's likely more cleanup work possible, though. This module has grown pretty organically over the last ~10 years -- there's a lot of small bits that can be adjusted to make things better. There's probably also subtle inconsistencies between various functions that would likely be nice to clean up and unify, and filing PRs for those would be helpful -- likely some care is needed, perhaps even some small test updates, but overall a good goal.

You might also be interested in https://github.com/rust-lang/rust/issues/40713, as a somewhat larger project.

_Originally posted by @Mark-Simulacrum in https://github.com/rust-lang/rust/issues/89240#issuecomment-932658341_

**Comment by Mark-Simulacrum** [comment]
I think there's room for unifying the two -- we already have some support for running tests under a wrapper for e.g. android testing, so I imagine we might be able to reuse parts of that perhaps.

**Comment by jieyouxu** [comment]
I really need to make sure we split up `runtest.rs`, each time I look at it the more cursed it becomes.
