### ISSUE TITLE
Lower/UpperExp inconsistent between integers and floats

### ISSUE THREAD

**Issue by nrabulinski** [rust-lang/rust#89493]
I tried this code:

```rust
println!("{:.*e}", 0, 25);
println!("{:.*e}", 0, 25.0);
```

I expected to see this happen: 
The output should be the same regardless if I'm formatting an integer or a float, in this case most likely `3e1`. 

Instead, this happened: 
```
3.e1
2e1
```

Happens in both latest stable and nightly.

EDIT: I'm suspecting this is actually two separate bugs in both the integer and float implementation - the integer result contains a `.` which should not be there, and the float gets rounded down to `2` despite `25.1` rounding to `3e1` - which is the result I would expect for `25.0` as well.

**Comment by joshtriplett** [comment]
For the floating-point portion of this, I *think* the default is "round to nearest even", which would make 2e1 the correct rounding.

It seems odd that integers and floating-point values have different rounding here.

**Comment by nrabulinski** [comment]
> For the floating-point portion of this, I *think* the default is "round to nearest even", which would make 2e1 the correct rounding.
> 
> 
> 
> It seems odd that integers and floating-point values have different rounding here.

https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a056ffde1e5a237e2e26351615775809

**Comment by fmease** [comment]
I can no longer reproduce this on the latest nightly (1.77, 2024-01-22 d5fd0997291ca0135401), I get:

```
2e1
2e1
```

Interestingly, stable (1.75) produces the following which still contains the rounding error:

```
3e1
2e1
```

Closing as completed. Please ping me if I should reopen this issue.
