### ISSUE TITLE
CI: dist-s390x-linux build went from 40min. to 160min with new LLVM pass manager

### ISSUE THREAD

**Issue by hkratz** [rust-lang/rust#89609]
CI time quadrupled when the new pass manager was enabled:
* Last CI before  the new pass manager was enabled: https://github.com/rust-lang-ci/rust/runs/3707892000?check_suite_focus=true
* CI with the new pass manager was enabled: https://github.com/rust-lang-ci/rust/runs/3708445190?check_suite_focus=true

Right now that does not really matter much because Github's Apple CI runners use very old hardware and take about the same time, but once that is fixed this will block a faster CI. No idea if that platform has any significant userbase.

Maybe disable the new PM for that platform or report it upstream?

**Comment by workingjubilee** [comment]
This regression absolutely needs to be reported upstream, as LLVM dev talk has mentioned completely removing the old pass manager within 1~2 versions.

**Comment by hkratz** [comment]
The build timeout in https://github.com/rust-lang/rust/pull/88379#issuecomment-937429068 might be caused by this as well.

**Comment by camelid** [comment]
Is there anything I can do to unblock #88379? Or will it require the patch that `@Mark-Simulacrum` is suggesting?

**Comment by cuviper** [comment]
I'm going to try to find the culprit, but in the meantime to unblock folks that hack could be an extra target condition in `should_use_new_llvm_pass_manager`. Note that the host arch is apparently not the issue, since these are all running on x86_64, cross-compiling to various targets.

**Comment by camelid** [comment]
Based on those results, it looks to me (albeit as someone who's not knowledgeable about LLVM internals) like maybe it has some really large data structures that are slow to process. Could that be it?

**Comment by hkratz** [comment]
I have just tried `DEPLOY=1 src/ci/docker/run.sh dist-s390x-linux` for #88379 with the new pass manager disabled and it built in about 30 minutes locally. So this change is definitely blocked by this issue.

**Comment by cuviper** [comment]
I managed to collect `-Csave-temps` for the troublesome crate:

```text
13:33:31.205643159  2.5M  rustc_ast_lowering-7fc619e50cfb03b2.rustc_ast_lowering.797ce196-cgu.0.rcgu.no-opt.bc
13:33:43.311381229  1.6M  rustc_ast_lowering-7fc619e50cfb03b2.rustc_ast_lowering.797ce196-cgu.0.rcgu.thin-lto-input.bc
13:33:43.578375452  1.6M  rustc_ast_lowering-7fc619e50cfb03b2.rustc_ast_lowering.797ce196-cgu.0.rcgu.thin-lto-after-rename.bc
13:33:43.811370411  1.6M  rustc_ast_lowering-7fc619e50cfb03b2.rustc_ast_lowering.797ce196-cgu.0.rcgu.thin-lto-after-resolve.bc
13:33:43.977366820  1.6M  rustc_ast_lowering-7fc619e50cfb03b2.rustc_ast_lowering.797ce196-cgu.0.rcgu.thin-lto-after-internalize.bc
13:33:44.487355785  2.0M  rustc_ast_lowering-7fc619e50cfb03b2.rustc_ast_lowering.797ce196-cgu.0.rcgu.thin-lto-after-import.bc
13:33:44.682351566  2.0M  rustc_ast_lowering-7fc619e50cfb03b2.rustc_ast_lowering.797ce196-cgu.0.rcgu.thin-lto-after-patch.bc
13:48:17.348469820   33M  rustc_ast_lowering-7fc619e50cfb03b2.rustc_ast_lowering.797ce196-cgu.0.rcgu.thin-lto-after-pm.bc
13:48:23.212342944   33M  rustc_ast_lowering-7fc619e50cfb03b2.rustc_ast_lowering.797ce196-cgu.0.rcgu.bc
14:45:58.202304051   11M  rustc_ast_lowering-7fc619e50cfb03b2.rustc_ast_lowering.797ce196-cgu.0.rcgu.o
```

So it took almost 15 minutes from `thin-lto-after-patch` to `thin-lto-after-pm` (running the pass manager), growing from 2 to 33 MB of LLVM bitcode. Then it took almost an hour to actually codegen that into an object file. At one point during that hour, I noticed the process was using 24GB of resident memory!

```
$ wc -lL *.ll
   157863      2306 rustc_ast_lowering-7fc619e50cfb03b2.rustc_ast_lowering.797ce196-cgu.0.rcgu.thin-lto-after-patch.ll
  4056416    238276 rustc_ast_lowering-7fc619e50cfb03b2.rustc_ast_lowering.797ce196-cgu.0.rcgu.thin-lto-after-pm.ll
```

In that 4 million lines of LLVM IR, about 2.7 million is just in 2 instantiations of `LoweringContext::lower_opaque_impl_trait`! That longest line of 238276 characters is the `phi` line below:

```
106767:                                           ; preds = %754032
  %106768 = landingpad { i8*, i32 }
          cleanup
  br label %106769

106769:                                           ; preds = %106767, %106765, ...etc.
  %106770 = phi { i8*, i32 } [ %86006, %86005 ], [ %86008, %86007 ], ...etc.
  invoke fastcc void @"_ZN4core3ptr101drop_in_place$LT$rustc_ast_lowering..lifetimes_from_impl_trait_bounds..ImplTraitLifetimeCollector$GT$17hde8a472161ebd31bE"(%"lifetimes_from_impl_trait_bounds::ImplTraitLifetimeCollector"* nonnull %15650) #25
          to label %754701 unwind label %754477
```

I cut them off with "etc.", but the full `preds` and `phi` lists are each 11574 entries long! AFAICS, all of those predecessors are simple `landingpad` blocks like the one I included here. The second `lower_opaque_impl_trait` has the same thing but _only_ 238274 characters long, I think just from a couple shorter `%N` number lengths.

The same blocks in `thin-lto-after-patch` (before pm) look like this:

```
243:                                              ; preds = %259
  %244 = landingpad { i8*, i32 }
          cleanup
  br label %247

245:                                              ; preds = %227
  %246 = landingpad { i8*, i32 }
          cleanup
  br label %247

247:                                              ; preds = %245, %243
  %248 = phi { i8*, i32 } [ %244, %243 ], [ %246, %245 ]
  invoke fastcc void @"_ZN4core3ptr101drop_in_place$LT$rustc_ast_lowering..lifetimes_from_impl_trait_bounds..ImplTraitLifetimeCollector$GT$17hde8a472161ebd31bE"(%"lifetimes_from_impl_trait_bounds::ImplTraitLifetimeCollector"* nonnull %30) #33
          to label %749 unwind label %570
```

**Comment by cuviper** [comment]
Here's the input bitcode before the pass manager: [rustc_ast_lowering-cgu.0.rcgu.thin-lto-after-patch.bc.gz](https://github.com/rust-lang/rust/files/7316562/rustc_ast_lowering-cgu.0.rcgu.thin-lto-after-patch.bc.gz)

Even `opt -O1` behaves badly, while `opt -O1 --enable-new-pm=0` runs quickly without blowing up the bitcode.

**Comment by cuviper** [comment]
cc @nikic -- this is another new-pm problem, although it appears to be specific to SystemZ.

**Comment by apiraino** [comment]
Assigning priority as discussed in the [Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2389609.20CI.3A.20dist-s390x-linux.20build.20went.20from.2040min.2E.20to.20160mi.E2.80.A6) of the Prioritization Working Group.

@rustbot label -I-prioritize +P-high

**Comment by nikic** [comment]
If anyone is wondering why this one only occurs on SystemZ: https://github.com/llvm/llvm-project/blob/main/llvm/lib/Target/SystemZ/SystemZTargetTransformInfo.h#L39 Apparently this target just increases all inlining threshold by a factor of three...

**Comment by cuviper** [comment]
Aha, thanks! The only other targets that change that multiplier are NVPTX (5) and AMDGPU (11).

> AMD: See, NVIDIA only goes to 5 -- This one goes to 11! :metal:
