### ISSUE TITLE
std::collections HashMap slower than hashbrown 

### ISSUE THREAD

**Issue by Guilucand** [rust-lang/rust#89624]
Hi,
I noticed a big performance difference between the hashbrown crate hashmap and the std::collections one.
An example benchmark is available [here](https://github.com/Guilucand/hashmap_test).

The results on my machine are very different, with the hashbrown version x3.5 times faster than the std::collections one:

`cargo +nightly bench`:
```
    Finished bench [optimized] target(s) in 0.00s
    Running unittests (target/release/deps/hashmap_test-45d61280ef074a31)

running 2 tests
test tests::bench_hb_hashmap  ... bench:  10,935,178 ns/iter (+/- 312,654)
test tests::bench_std_hashmap ... bench:  38,376,010 ns/iter (+/- 2,540,986)

test result: ok. 0 passed; 0 failed; 0 ignored; 2 measured; 0 filtered out; finished in 14.95s
```

### Meta

`rustc --version --verbose`:
```
rustc 1.57.0-nightly (0eabf25b9 2021-10-06)
binary: rustc
commit-hash: 0eabf25b90396dead0b2a1aaa275af18a1ae6008
commit-date: 2021-10-06
host: x86_64-unknown-linux-gnu
release: 1.57.0-nightly
LLVM version: 13.0.0
```
</p>
</details>

**Comment by cuviper** [comment]
Hashbrown also has an "inline-more" feature enabled by default, but `std` has it disabled. It's not always best to force additional inlining like that, but it can have a lot of benefit on small benchmarks.
