### ISSUE TITLE
`ui/deriving/issue-89188-gat-hrtb.rs` test fails with debug assertions enabled

### ISSUE THREAD

**Issue by asquared31415** [rust-lang/rust#89639]
The `ui/deriving/issue-89188-gat-hrtb.rs` test fails due to an arithmetic overflow when debug assertions are enabled.

The offending code likely intends to use the explicit wrapping math methods, as the test does pass with the overflow.

The test was implemented in #89341

<details><summary>Backtrace</summary>
<p>

```
thread 'rustc' panicked at 'attempt to subtract with overflow', compiler/rustc_trait_selection/src/traits/project.rs:561:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.57.0-dev running on x86_64-unknown-linux-gnu

note: compiler flags: -Z threads=1 -Z ui-testing -Z deduplicate-diagnostics=no -Z emit-future-incompat-report -C codegen-units=1 -C prefer-dynamic -C rpath -C debuginfo=0

query stack during panic:
#0 [specialization_graph_of] building specialization graph of trait `core::clone::Clone`
#1 [coherent_trait] coherence checking all impls of trait `core::clone::Clone`
end of query stack
```

</p>
</details>

**Comment by nbdd0121** [comment]
This is introduced in #86993 with guards like `if debruijn.as_usize() + 1 > self.current_index.as_usize() + self.universe_indices.len() => bug!()` near call-site. So I suppose just swapping the order should be sufficient?

**Comment by jackh726** [comment]
Overflowing here is a bug. Given that we haven't seen an index out of bound panics on like 562, I would guess that the actual logic here is correct (so, we underflow, then overflow). I do want to prove to myself that again (and put it in a comment).

**Comment by the8472** [comment]
If it is really intended then `wrapping_sub` should be used.

**Comment by tlyu** [comment]
Oh, I think I ran into this as well and thought it was due to a local change I had made violating an invariant.

**Comment by oli-obk** [comment]
> Duplicate of #89280?

no, that issue is in diagnostics, while this one is in trait resolution. I'll try to get to the diagnostics issue next week

**Comment by camsteffen** [comment]
> > Duplicate of #89280?
> 
> no, that issue is in diagnostics, while this one is in trait resolution. I'll try to get to the diagnostics issue next week

@oli-obk Ah my bad, thanks. I think I've been running in to both issues and conflating them.
