### ISSUE TITLE
Suggest joining two identifiers if the grammer is invalid and they would form a keyword

### ISSUE THREAD

**Issue by Nilstrieb** [rust-lang/rust#89640]
Given the following code: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=9adebfa3cae4c99b1fa5c0c9f25e154a

```rust
fn main() {
    l et x = 5;
}
```

The current output is:

```
error: expected one of `!`, `.`, `::`, `;`, `?`, `{`, `}`, or an operator, found `et`
 --> src/main.rs:2:7
  |
2 |     l et x = 5;
  |       ^^ expected one of 8 possible tokens
```

Ideally the output should look like:

```
error: expected one of `!`, `.`, `::`, `;`, `?`, `{`, `}`, or an operator, found `et`
 --> src/main.rs:2:7
  |
2 |     l et x = 5;
  |       ^^ expected one of 8 possible tokens

     hint: did you accidentally put a space inside the keyword `let`?
```

Sometimes you accidentally insert whitespace inside a keyword, and might not notice it immediately. This minimal case is pretty obvious, but it might not actually always be that obvious if a lot is going on.

This could even be extended to cover all names in scope.

**Comment by camelid** [comment]
Why did you close this issue? I think it's a good idea.

**Comment by Nilstrieb** [comment]
I don't think there's any value to implement it, since the mistake is always obvious, but I can reopen it if you'd like

**Comment by camelid** [comment]
I think it's still worthwhile because people can sometimes get confused in the moment, especially if macros are involved.
