### ISSUE TITLE
LTO toolchain compatability docs could use an update in case anything has changed in the last year

### ISSUE THREAD

**Issue by vlovich** [rust-lang/rust#89654]
https://doc.rust-lang.org/rustc/linker-plugin-lto.html#toolchain-compatibility ends with Rust 1.46 which is about a year old at this point. 1.56 will be at LLVM 13, 1.54 is at LLVM 12, and 1.47 was at LLVM 11.

I just tried doing cross-language LTO with a semi-complex code base in C++ (the Cloudflare Workers runtime) using clang 14 tip of tree with some simple Rust dependencies (top-level dependency is basically lol-html & addr2line-rs, & cxxbridge bindings) build with Rust 1.55 (i.e. LLVM12).

Our test suite almost passed. The only failure I observed fails even without Rust LTO so at this time I think it's unrelated (likely LTO just made the test fast enough that it exposed some kind of underlying race condition as this test is known flaky).

So I'm curious if the version restrictions still remain or if they've been known to be lifted for a while now. Would be helpful for the docs to be updated. Additionally, would a version mismatch ever result in a weird runtime failure or is it always going to be a link failure?

Thanks!

**Comment by Dylan-DPC** [comment]
The table now shows till 1.73-1.74 [with 1.79 being latest stable at the time of writing] so this is now updated
