### ISSUE TITLE
Get rid of clean::Function::header once #85833 is merged

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#89673]
_Originally posted by @jyn514 in https://github.com/rust-lang/rust/pull/85833#r710668748_

**Comment by jyn514** [comment]
Hi @yuvaldolev, #85833 was merged so you can start working on this :) feel free to ask for help on [Zulip](https://rust-lang.zulipchat.com/#narrow/stream/266220-rustdoc).

**Comment by yuvaldolev** [comment]
Thanks @jyn514!
I'll start working on it
