### ISSUE TITLE
Decide on (and implement) which parts of the AST can get stability attributes

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#8967]
As of #8921, the compiler checks the attributes on structs, enum variants (not enums themselves) and functions. Definitely required: methods (#8961) and mods (#8962).

Up for discussion:
- traits
- enums
- impls (both `impl Type` and `impl Trait for Type`)
- struct fields
- `type` aliases.
- foreign fns
- anything else that can take attributes in the ast

(Part of #6875.)

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#687
