### ISSUE TITLE
Let-else source expression move behavior

### ISSUE THREAD

**Issue by phaylon** [rust-lang/rust#89688]
The move behavior on non-matching of expressions by `feature(let_else)` seems currently inconsistent with behavior of, for example, `if let`.

An `if-let` construct does not move from the matched expression if the pattern doesn't match:

```rust
fn example_if_let(value: Option<String>) {
    if let Some(inner) = value {
        println!("inner: {}", inner);
    } else {
        println!("other: {:?}", value);
    }
}

fn main() {
    example_if_let(Some("foo".into()));
    example_if_let(None);
}
```
compiles and prints
```
inner: foo
other: None
```

However, `let-else` seems to unconditionally move from the matched expression:
```rust
#![feature(let_else)]

fn example_let_else(value: Option<String>) {
    let Some(inner) = value else {
        println!("other: {:?}", value);
        return;
    };
    println!("inner: {}", inner);
}

fn main() {
    example_let_else(Some("foo".into()));
    example_let_else(None);
}
```
fails to compile:
```
error[E0382]: borrow of moved value: `value`
 --> src/main.rs:5:33
  |
3 | fn example_let_else(value: Option<String>) {
  |                     ----- move occurs because `value` has type `Option<String>`, which does not implement the `Copy` trait
4 |     let Some(inner) = value else {
  |                       ----- value moved here
5 |         println!("other: {:?}", value);
  |                                 ^^^^^ value borrowed here after move
```

I'm wondering if this is intentional, as it would seem to make it impossible to use the original unmatched value in an panic message (or diverge otherwise with the value or any value based on it).

```
rustc 1.57.0-nightly (485ced56b 2021-10-07)
binary: rustc
commit-hash: 485ced56b8753ec86936903f2a8c95e9be8996a1
commit-date: 2021-10-07
host: x86_64-unknown-linux-gnu
release: 1.57.0-nightly
LLVM version: 13.0.0
```

Proposed Label: F-let-else

**Comment by nagisa** [comment]
This definitely seems wrong. The `value` should be available for use within the `else` block.

As per reference level explanation [in the RFC](https://github.com/rust-lang/rfcs/blob/master/text/3137-let-else.md#reference-level-explanations) the construct should desugar into a match, pretty much. And the desugared version does allow for using the matchee in the "otherwise" branch.

**Comment by joshtriplett** [comment]
That's my understanding as well: the RHS of the let should be available in the else expression.

**Comment by phaylon** [comment]
Yes, that's what I'm thinking as well. Though the RFC doesn't seem to have examples showing it. My reasoning was that since `let P = E else { X... }; R...` should be transformable into `if let P = E { R... } else { X... }` there should be no issue with leaving the `E` intact in the `else` branch.

I took a look at the code, but I'm not familiar enough with the internals to see where the "place identity" of the expression gets lost.

**Comment by nagisa** [comment]
So I kinda though that using `ExprKind::Type` (i.e. type ascription) and a match would help here, but the implementation PR does note that type ascription disables coercion, which makes it an invalid approach. I can see ways to adjust the current lowering slightly by adjusting HirIds to make it work, but I also don't think the hacks are worth it here and that adding a built-in HIR type makes more sense.

**Comment by cormacrelf** [comment]
Yeah, but I think it might be the only one, and it is not great. The let-else was meant to help you get the type you're decomposing out of the way, but you have to specify that it's fallible operation no less than three times (Ok, Result, try_into) if you want to write the target type explicitly.

```rust
// explicit handling
let Ok(x): Result<u32, _> = y.try_into() else {
    return u32::MAX;
};
// remember we want people to write all that instead of this:
let x = y as u32;
// and the alternative when you have Result return type
let x: u32 = y.try_into()?;
```

I'm with you, but it brings me no joy.

**Comment by cormacrelf** [comment]
I'm having a crack at it by adding an `Option<&'hir Ty<'hir>>`to `hir::ExprKind::Let`, which is the HIR's boolean expression in an `if let` construct. This would, if the parser allowed it, permit `if let` to have type annotations too.

I'm new at this, is it weird that typeck walks `hir::ExprKind::Let` via `self.walk_local` which treats the pattern as irrefutable?

https://github.com/rust-lang/rust/blob/9475e609b8458fff9e444934a6017d2e590642cf/compiler/rustc_typeck/src/expr_use_visitor.rs#L461-L470

https://github.com/rust-lang/rust/blob/9475e609b8458fff9e444934a6017d2e590642cf/compiler/rustc_typeck/src/expr_use_visitor.rs#L629-L631

This just seems suspicious, I am not certain it would fix anything, but it feels wrong.

**Comment by cormacrelf** [comment]
Yeah I've fixed this, will PR when I finish the knock-on hir changes in clippy etc
