### ISSUE TITLE
rustdoc renders re-exported types' field types differently from their definitions

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#89712]
For example, with `MatchExpressionArmCause`. Note `Vec<Span>` in the definition vs `Vec<Span, Global>` in the re-export, and `Ty<'tcx>` in the definition vs `&'tcx TyS<'tcx>` in the re-export.

### Definition

![image](https://user-images.githubusercontent.com/37223377/136672160-d87181ca-34c6-4259-bb9b-03674c101760.png)

### Re-export

![image](https://user-images.githubusercontent.com/37223377/136672165-451af028-9224-45be-9c5b-0e996caed942.png)

-----

#### Note

I'm labeling this as `A-cross-crate-reexports`, but it may happen with intra-crate re-exports too.

**Comment by jyn514** [comment]
Duplicate of https://github.com/rust-lang/rust/issues/80379
