### ISSUE TITLE
Feature gate the `must_not_suspend` lint

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#89798]
Feature-gate the `must_not_suspend` lint (the attribute is already feature-gated) as `#![feature(must_not_suspend_lint)]`. This will have to be done **before 1.57.0** is released (since that's when the lint will land).

cc https://github.com/rust-lang/rust/issues/83310#issuecomment-940515315

**Comment by guswynn** [comment]
oh wait, the lint still triggers, its just the feature gate on the using lint directives! seems fine to me!

**Comment by camelid** [comment]
Re-opening to track beta-backport.

**Comment by cuviper** [comment]
Backported in #90938.
