### ISSUE TITLE
The error says "found slice" but the solution is .as_slice()?

### ISSUE THREAD

**Issue by EvanCarroll** [rust-lang/rust#89805]
I was given a [suggested syntax to convert from a `Vec<&str>` to `&[&str]` by Ömer Erden on this question on StackOverflow](https://stackoverflow.com/questions/69535907/how-can-i-convert-vecstring-to-str/69536222#comment122907025_69535907)

```rust
fn main() {
  let pos: Vec<String> = vec!["foo".to_owned(), "bar".to_owned(), "baz".to_owned()];
  let pos: &[&str] = pos.iter().map(AsRef::as_ref).collect::<Vec<_>>()[..];
}
```

This produces the error,

```text
error[E0308]: mismatched types
 --> bin/seq.rs:3:21
  |
  |     let pos: &[&str] = pos.iter().map(AsRef::as_ref).collect::<Vec<_>>()[..];
  |              -------   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |              |         |
  |              |         expected `&[&str]`, found slice
  |              |         help: consider borrowing here: `&pos.iter().map(AsRef::as_ref).collect::<Vec<_>>()[..]`
  |              expected due to this
  |
  = note: expected reference `&[&str]`
                 found slice `[&_]`
```

Note that the diagnostic actually says _**expected `&[&str]`, found slice**_

However, the solution here is to remove `[..]` and add explicitly `.as_slice()`

```rust
fn main() {
  let pos: Vec<String> = vec!["foo".to_owned(), "bar".to_owned(), "baz".to_owned()];
  let pos: &[&str] = pos.iter().map(AsRef::as_ref).collect::<Vec<_>>().as_slice();
}
```

If the compiler finds a slice, the solution shouldn't be to add explicitly `.as_slice()`

**Comment by moxian** [comment]
Simpler example

```rust
fn main() {
    let v = vec![1i32,2,3,4];
    let x: &[i32] = v[2..3];
}
```
gives

```rust
error[E0308]: mismatched types
 --> src/main.rs:3:21
  |
3 |     let x: &[i32] = v[2..3];
  |            ------   ^^^^^^^
  |            |        |
  |            |        expected `&[i32]`, found slice `[i32]`
  |            |        help: consider borrowing here: `&v[2..3]`
  |            expected due to this
  ```
  
  The error is correct. While the `&[i32]` is often called "a slice" in casual speech, it is actually "a slice *reference*", and the "reference" part gets dropped because working with "raw" slices is very tricky.

Th error in your case clearly says that one of the types is `&[&str]` and the other is `[&_]` (note the lack of first `&`), and it suggest to borrow the result to get the types aligned.

I don't think the wording can be meaningfuly improved here....

**Comment by Enselic** [comment]
Triage: Let's close then.

**Comment by EvanCarroll** [comment]
Even 

>   expected slice reference `&[i32]`, found slice `[i32]`

Would have been helpful. =(
