### ISSUE TITLE
Rustdoc regression: duplicate macro in sidebar

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust#89852]
```rust
#[macro_export]
macro_rules! repro {
    () => {};
}

pub use crate::repro as repro2;
```

```console
$ cargo doc --open
```

<br>

In current stable, and nightly-2021-08-28:

![Screenshot from 2021-10-13 10-33-42](https://user-images.githubusercontent.com/1940490/137184116-698eb0d6-4ef6-4785-b74f-462ed6432430.png)

<br>

In current beta, current nightly, and nightly-2021-08-29:

![Screenshot from 2021-10-13 10-33-55](https://user-images.githubusercontent.com/1940490/137184144-e89ca5e9-702f-414c-99e1-5230c7982fbe.png)

<br>

Notice that `repro` appears twice in the sidebar under the list of macros exported by the crate.

Bisects to #88019.

**Comment by dtolnay** [comment]
## Bisect

searched nightlies: from nightly-2021-08-10 to nightly-2021-09-26
regressed nightly: nightly-2021-08-29
searched commit range: https://github.com/rust-lang/rust/compare/ac50a53359328a5d7f2f558833e63d59d372e4f7...5eacec9ec7e112a0de1011519a57c45586d58414
regressed commit: https://github.com/rust-lang/rust/commit/05cccdc9b321e6565b3e62e8b52aec53d106ef2f

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.0</summary>


Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc 2021-08-10 --end 2021-09-26 --prompt -- doc --open 
```
</details>

**Comment by jyn514** [comment]
I think the fix here is to show "pub use repro as repro2" in the crate root - it sounds like currently it's being unconditionally inlined and then on top of that using the original name instead of the new one.
