### ISSUE TITLE
thread 'rustc' panicked at 'index out of bounds: the len is 0 but the index is 0'

### ISSUE THREAD

**Issue by dwrensha** [rust-lang/rust#89868]
rustc crashes on the following input, found by [fuzz_rustc](https://github.com/dwrensha/fuzz-rustc):
```rust
struct A<B>(B);
impl<B>A<B>{fn d(){fn d(){Self(1)}}}
```

```
$ rustc main.rs
error[E0601]: `main` function not found in crate `main`
 --> main.rs:1:1
  |
1 | / struct A<B>(B);
2 | | impl<B>A<B>{fn d(){fn d(){Self(1)}}}
  | |____________________________________^ consider adding a `main` function to `main.rs`

error[E0277]: the size for values of type `B` cannot be known at compilation time
 --> main.rs:2:27
  |
2 | impl<B>A<B>{fn d(){fn d(){Self(1)}}}
  |      -                    ^^^^ doesn't have a size known at compile-time
  |      |
  |      this type parameter needs to be `std::marker::Sized`
  |
note: required by `A`
 --> main.rs:1:1
  |
1 | struct A<B>(B);
  | ^^^^^^^^^^^^^^^

thread 'rustc' panicked at 'index out of bounds: the len is 0 but the index is 0', compiler/rustc_middle/src/ty/generics.rs:164:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.57.0-nightly (d7c97a02d 2021-10-12) running on x86_64-unknown-linux-gnu

query stack during panic:
#0 [typeck] type-checking `<impl at main.rs:2:1: 2:37>::d::d`
#1 [typeck_item_bodies] type-checking all item bodies
end of query stack
error: aborting due to 2 previous errors
```

**Comment by dwrensha** [comment]
cargo-bisect-rustc says:

> Regression in nightly-2020-02-29
...
found 7 bors merge commits in the specified range
  commit[0] 2020-02-27UTC: Auto merge of #68434 - varkor:astconv-mismatch-error, r=nikomatsakis
  commit[1] 2020-02-27UTC: Auto merge of #69513 - tmiasko:revert-checked-unused, r=petrochenkov
  commit[2] 2020-02-28UTC: Auto merge of #69534 - Dylan-DPC:rollup-fwa2lip, r=Dylan-DPC
  commit[3] 2020-02-28UTC: Auto merge of #68505 - skinny121:canonicalize-const-eval-inputs, r=nikomatsakis
  commit[4] 2020-02-28UTC: Auto merge of #68827 - ssomers:btree_navigation_revisited, r=Mark-Simulacrum
  commit[5] 2020-02-28UTC: Auto merge of #69148 - estebank:cold-as-ice, r=oli-obk
  commit[6] 2020-02-28UTC: Auto merge of #69555 - Centril:rollup-e53lxz4, r=Centril
ERROR: no commits between 6d69caba110c0c2fb90180df1cbc8be5033b91d4 and 0eb878d2aa6e3a1cb315f3f328681b26bb4bffdb within last 167 days

```

**Comment by matthiaskrgr** [comment]
another one
````rust
struct S0<T>(T);
impl<T> S0<T> {
    fn foo() {
        Self(0);
        const C: S0<u8> = Self(0);
    }
}
````
