### ISSUE TITLE
rustdoc: `std::collections::HashSet` is not shown in search results since 1.50.0

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#89872]
Interestingly, this goes both ways:

- In 1.49.0, only `std::collections::HashSet` is shown (not `std::collections::hash_set::HashSet`, which is public and stable).
- In 1.50.0, only `std::collections::hash_set::HashSet` is shown (not `std::collections::HashSet`).

So there seems to be a bug in both versions. Note that this is a re-exports bug, but not a cross-crate re-exports bug.

### [1.49.0](https://doc.rust-lang.org/1.49.0/std/?search=hashset%3A%3Ainsert)

![image](https://user-images.githubusercontent.com/37223377/137238323-291a52b4-8441-444d-8b4f-8cadd1f647de.png)

### [1.50.0](https://doc.rust-lang.org/1.50.0/std/?search=hashset%3A%3Ainsert)

![image](https://user-images.githubusercontent.com/37223377/137238357-b18aae0b-4232-4e0d-94df-aec55c365f54.png)

**Comment by camelid** [comment]
> > In 1.50.0, only std::collections::hash_set::HashSet is shown (not std::collections::HashSet).
> 
> Is hash_set public? If so, I don't think this is actually a bug, libstd doesn't indicate in any way which definition should take precedence.

It is public. But usually, rustdoc shows *both* definitions in the case of re-exports; they don't take precedence over each other.

**Comment by euclio** [comment]
cc #86337

**Comment by jieyouxu** [comment]
Seems to have been fixed (at least <https://doc.rust-lang.org/std/collections/struct.HashSet.html?search=hashset> shows both). Closing as resolved.
