### ISSUE TITLE
Missing `.vim` entry in `.gitignore`

### ISSUE THREAD

**Issue by cameron1024** [rust-lang/rust#89896]
I use neovim and coc for rust development, and recently started playing with rustc. The "getting started" guide suggests using `:CocLocalConfig`, which generates a file at `.vim/coc-settings.json`. However, there's no entry in the gitignore for `.vim`.

Can we have that entry, or is there a reason why it's not already present? If we can, I'm happy to make a PR 😄

**Comment by weihanglo** [comment]
As a temporary but useful solution, you can add a repo-wide gitignore rule to ` .git/info/exclude`

Ref: https://git-scm.com/docs/gitignore
