### ISSUE TITLE
Self-referential struct with `Cow<[Self]>` as the last field errors

### ISSUE THREAD

**Issue by mbartlett21** [rust-lang/rust#89940]
I tried this code:

```rust
use std::borrow::Cow;

struct Element<'a> {
    arr: Cow<'a, [Element<'a>]>,
}

// So that `ToOwned` *should* be implemented for `[Element<'a>]`.
impl<'a> Clone for Element<'a> {
    fn clone(&self) -> Self {
        todo!()
    }
}
```

Compiling it, I got these errors:

```txt
error[E0277]: the trait bound `[Element<'a>]: ToOwned` is not satisfied
   --> src/lib.rs:4:10
    |
4   |     arr: Cow<'a, [Element<'a>]>,
    |          ^^^^^^^^^^^^^^^^^^^^^^ the trait `ToOwned` is not implemented for `[Element<'a>]`
    |
    = help: the following implementations were found:
              <[T] as ToOwned>
```

(this is presumably because there is a reference to the `struct`)
```txt
error[E0277]: the trait bound `[Element<'a>]: ToOwned` is not satisfied in `Element<'a>`
   --> src/lib.rs:7:10
    |
7   | impl<'a> Clone for Element<'a> {
    |          ^^^^^ within `Element<'a>`, the trait `ToOwned` is not implemented for `[Element<'a>]`
    |
    = help: the following implementations were found:
              <[T] as ToOwned>

note: required because it appears within the type `Element<'a>`
   --> src/lib.rs:3:8
    |
3   | struct Element<'a> {
    |        ^^^^^^^
```

## A "fix"

Changing line 4 to use an `Option` works for no obvious reason, and will also add an extra cost to using the field:

```diff
  struct Element<'a> {
<     arr: Cow<'a, [Element<'a>]>,
>     arr: Option<Cow<'a, [Element<'a>]>>,
  }
```

### Meta

`rustc --version --verbose`:
```
rustc 1.57.0-nightly (dfc5add91 2021-10-13)
binary: rustc
commit-hash: dfc5add915e8bf4accbb7cf4de00351a7c6126a1
commit-date: 2021-10-13
host: x86_64-pc-windows-msvc
release: 1.57.0-nightly
LLVM version: 13.0.0
```

**Comment by mbartlett21** [comment]
For some reason, it works without using ToOwned:


<details><summary>Examples</summary>
Not Working:

```rust
use std::borrow::ToOwned;

struct Element<'a> {
    arr: CowVec<'a, Element<'a>>,
}

impl Clone for Element<'_> {
    fn clone(&self) -> Self { todo!() }
}

enum CowVec<'a, B> 
where
    B: 'a + Clone, 
 {
    Borrowed(&'a [B]),
    Owned(<[B] as ToOwned>::Owned),
}
```
([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=b9be23031d932cfc97f6f57604e85132))

Changing `CowVec::Owned` to use a `Vec` fixes it:

```diff
      Borrowed(&'a [B]),
-     Owned(<[B] as ToOwned>::Owned),
+     Owned(Vec<B>),
  }
```
([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=f44f02cd44fa23600b6f165f48eede0b))
</details>

**Comment by oberien** [comment]
It also happens in a simpler example with the `'static` lifetime:
```rust
#[derive(Clone)]
struct Foo {
    foo: Cow<'static, [Foo]>,
}
```
This results in the following error:
```rust
error[E0277]: the trait bound `[Foo]: ToOwned` is not satisfied in `Foo`
 --> src/lib.rs:5:23
  |
5 |     foo: Cow<'static, [Foo]>,
  |                       ^^^^^ within `Foo`, the trait `ToOwned` is not implemented for `[Foo]`
  |
  = help: the following implementations were found:
            <[T] as ToOwned>
note: required because it appears within the type `Foo`
 --> src/lib.rs:4:8
  |
4 | struct Foo {
  |        ^^^
  = note: slice and array elements must have `Sized` type

error[E0277]: the trait bound `[Foo]: ToOwned` is not satisfied in `Foo`
   --> src/lib.rs:3:10
    |
3   | #[derive(Clone)]
    |          ^^^^^ within `Foo`, the trait `ToOwned` is not implemented for `[Foo]`
    |
    = help: the following implementations were found:
              <[T] as ToOwned>
note: required because it appears within the type `Foo`
   --> src/lib.rs:4:8
    |
4   | struct Foo {
    |        ^^^
note: required by a bound in `Clone`
    = note: this error originates in the derive macro `Clone` (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by de-vri-es** [comment]
This only seems to happen when the `Cow<'a, [Self]>` is the last field in a struct:

For example, this compiles:
```rust
use std::borrow::Cow;

#[derive(Clone)]
struct Foo<'a> {
    children: Cow<'a, [Self]>,
    _foo: (),
}
```

But this does not:
```rust
use std::borrow::Cow;

#[derive(Clone)]
struct Foo<'a> {
    children: Cow<'a, [Self]>,
}
```

It almost looks like the compiler is wrongly determining that the second `Foo` is variable sized, and hence can not implement `Clone` and `ToOwned`.

**Comment by sosthene-nitrokey** [comment]
This also affects enums.

```rust
#[derive(Clone)]
enum Element {
    First( Cow<'static, [Element]>)
}
```

gives

```
Compiling playground v0.0.1 (/playground)
error[[E0277]](https://doc.rust-lang.org/nightly/error-index.html#E0277): the trait bound `[Element]: ToOwned` is not satisfied in `Element`
 --> src/lib.rs:5:25
  |
5 |     First( Cow<'static, [Element]>)
  |                         ^^^^^^^^^ within `Element`, the trait `ToOwned` is not implemented for `[Element]`
  |
  = help: the trait `ToOwned` is implemented for `[T]`
note: required because it appears within the type `Element`
 --> src/lib.rs:4:6
  |
4 | enum Element {
  |      ^^^^^^^
  = note: slice and array elements must have `Sized` type

error[[E0277]](https://doc.rust-lang.org/nightly/error-index.html#E0277): the trait bound `[Element]: ToOwned` is not satisfied in `Element`
 --> src/lib.rs:3:10
  |
3 | #[derive(Clone)]
  |          ^^^^^ within `Element`, the trait `ToOwned` is not implemented for `[Element]`
  |
  = help: the trait `ToOwned` is implemented for `[T]`
note: required because it appears within the type `Element`
 --> src/lib.rs:4:6
  |
4 | enum Element {
  |      ^^^^^^^
note: required by a bound in `Clone`
  = note: this error originates in the derive macro `Clone` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0277`.
error: could not compile `playground` due to 2 previous errors
```

[Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=9d4661a90c6704bc943980fa477af9b6)

And the trick of adding a field works also:

```rust
#[derive(Clone)]
enum Element {
    First( Cow<'static, [Element]>, ())
}
```

Compiles ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=5cfe135dc2dcf29c4196d96d033e4503) )

**Comment by CAD97** [comment]
This gave a requirement evaluation overflow error on 1.48; 1.49 changed it to the `[Self]: ToOwned` obligation failure.

<details><summary>snippet</summary>

```rust
use std::borrow::ToOwned;

#[derive(Clone)]
pub enum Test {
    Owned(<[Test] as ToOwned>::Owned),
}
```
</details>

<details><summary>1.48</summary>

```text
error[E0275]: overflow evaluating the requirement `Test: Sized`
 --> <source>:5:11
  |
5 |     Owned(<[Test] as ToOwned>::Owned),
  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: required because of the requirements on the impl of `ToOwned` for `[Test]`

error[E0275]: overflow evaluating the requirement `Test: Sized`
   --> <source>:3:10
    |
3   | #[derive(Clone)]
    |          ^^^^^
    |
    = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to 2 previous errors
```
</details>

<details><summary>1.49</summary>

```text
error[E0277]: the trait bound `[Test]: ToOwned` is not satisfied
 --> <source>:5:11
  |
5 |     Owned(<[Test] as ToOwned>::Owned),
  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `ToOwned` is not implemented for `[Test]`
  |
  = help: the following implementations were found:
            <[T] as ToOwned>

error[E0277]: the trait bound `[Test]: ToOwned` is not satisfied in `Test`
   --> <source>:3:10
    |
3   | #[derive(Clone)]
    |          ^^^^^ within `Test`, the trait `ToOwned` is not implemented for `[Test]`
    |
    = help: the following implementations were found:
              <[T] as ToOwned>
    = note: required because it appears within the type `Test`
    = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: aborting due to 2 previous errors
```
</details>

From the release notes, compatibility note [Trait bounds are no longer inferred for associated types.](https://github.com/rust-lang/rust/issues/79904) seems _highly_ relevant.

@rustbot modify labels: +D-confusing +D-incorrect +A-traits +E-needs-mcve

Also suggesting https://github.com/rust-lang/rust/labels/regression-from-stable-to-stable since this _is_ a regression in diagnostic clarity; an obligation loop is at least a correct and somewhat useful diagnostic; the current behavior is at best confusing.

Two more interesting observations: defining `ToOwned` locally seems to work (not error) [[playground]](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=0db53e43b19fa428066bc588c6778376), and implementing the bound the error says is unsatisfied leads to a requirement evaluation cycle on `Test: Sized` [[playground]](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=b5a9dffd87507877becb0aff1d133e4a).

It appears that the underlying issue preventing this from working is that the field projection is not known to be `Sized` without resolving it, which recursively requires proving it to be `Sized`. My guess is that the implied `Sized` bound is taken into account for a local definition of `ToOwned`, which is why a local definition works, but that this bound isn't being taken advantage of before trying to resolve the projection when `ToOwned` is defined in a separate crate. When it isn't the last field, that _is_ used as sufficient to assume that the type projection is `Sized`, and thus everything works out.

Replicating this without std involvement will help. Note this seems to require two crates, which makes this significantly more interesting.

**Comment by Enselic** [comment]
Triage: This began to compile in 1.79. Regression test added via https://github.com/rust-lang/rust/pull/133488. Closing as duplicate of #107481 (even though that one is newer).
