### ISSUE TITLE
Re-enable debug checks in `copy[_nonoverlapping]`

### ISSUE THREAD

**Issue by WaffleLapkin** [rust-lang/rust#90012]
#79684 removed `debug_assert!` from `intrinsic::copy[_nonoverlapping]` to make it `const`:
https://github.com/rust-lang/rust/blob/5dab47dcd8267b8769421b46532414ec36d625e3/library/core/src/intrinsics.rs#L2045-L2049
https://github.com/rust-lang/rust/blob/5dab47dcd8267b8769421b46532414ec36d625e3/library/core/src/intrinsics.rs#L2130-L2131
We can't do these checks at compile-time, since `is_aligned_and_not_null`, for example, involves ptr->int cast to check the alignment:
https://github.com/rust-lang/rust/blob/5dab47dcd8267b8769421b46532414ec36d625e3/library/core/src/intrinsics.rs#L1950-L1952

So, as the FIXME suggests, we should enable the checks only at runtime. Recently `const_eval_select` intrinsic [was implemented](https://github.com/rust-lang/rust/pull/89247), it allows for exactly this use case - running different code in CTFE and runtime.

cc @rust-lang/lang, @rust-lang/libs and @rust-lang/wg-const-eval (it seems like use of `const_eval_select` requires approval of all of the above teams)

@rustbot label +T-lang +T-libs +A-const-eval +A-const-fn

**Comment by oli-obk** [comment]
kinda both:

lang: for whether const_eval_select is ok in general
libs: whether we should start using it in stable const fn
