### ISSUE TITLE
Make `slice::from_raw_parts[_mut]` const

### ISSUE THREAD

**Issue by WaffleLapkin** [rust-lang/rust#90011]
Currently, [`core::slice::from_raw_parts`](https://doc.rust-lang.org/core/slice/fn.from_raw_parts.html) is not `const`, since it uses `debug_assert!` with a non-`const` check: https://github.com/rust-lang/rust/blob/5dab47dcd8267b8769421b46532414ec36d625e3/library/core/src/slice/raw.rs#L89

`is_aligned_and_not_null` can't be made `const`, since it involves ptr->int cast to check the alignment: https://github.com/rust-lang/rust/blob/5dab47dcd8267b8769421b46532414ec36d625e3/library/core/src/intrinsics.rs#L1950-L1952

Recently `const_eval_select` intrinsic [was implemented](https://github.com/rust-lang/rust/pull/89247), it allows to run different code in CTFE and runtime. This, in turn, allows us to only make the alignment check in runtime and ignore it in the CTFE where it doesn't make much sense.

See also: #67456

cc @rust-lang/lang, @rust-lang/libs and @rust-lang/wg-const-eval (it seems like use of `const_eval_select` requires approval of all of the above teams)

@rustbot label +T-lang +T-libs +A-const-eval +A-const-fn

**Comment by WaffleLapkin** [comment]
Another approach to make `slice::from_raw_parts[_mut]` const would be to disable the checks altogether, but since we already have `const_eval_select`, that seems unreasonable.

**Comment by fee1-dead** [comment]
So why not use `const_eval_select`?
