### ISSUE TITLE
Fix display of enums with subfields

### ISSUE THREAD

**Issue by jsha** [rust-lang/rust#90061]
https://docs.rs/xmlparser/0.13.4/xmlparser/enum.Token.html

![image](https://user-images.githubusercontent.com/220205/137954784-8f2f7aca-e6ef-4c7c-b308-060368e4450f.png)

(I've expanded one of the "Show fields" toggles in the above screenshot)

Problems:

  - The font weight of "Fields of Comment" is _higher_ than the font weight of the "Comment" heading above it. "Comment" should be larger and heavier weight - similar to the weight of methods. And "Fields of _" should be lightweight.
  - "Fields of Comment" is an `<h3>`, but "Comment" is not a heading at all. This should be reversed.

EDIT(camelid): The toggles seen in the image above have already been removed. See https://github.com/rust-lang/rust/issues/90061#issuecomment-947146254 for an updated screenshot.

**Comment by camelid** [comment]
I'm pretty sure I got rid of the variant fields toggle a couple months ago; those docs were generated back in June.
