### ISSUE TITLE
Tracking Issue for const_ops

### ISSUE THREAD

**Issue by AlexApps99** [rust-lang/rust#90080]
Feature gate: `#![feature(const_ops)]`

This is a tracking issue for `const_ops`, which adds const versions of common numeric operations in `std::ops`.

### Public API
- `NonZero`
  - `BitOr`
  - `BitOrAssign`
  - `Div`
  - `Rem`
- `Wrapping`
  - `Shl`
  - `Shr`
  - `ShlAssign`
  - `ShrAssign`
  - `Add`
  - `AddAssign`
  - `Sub`
  - `SubAssign`
  - `Mul`
  - `MulAssign`
  - `Div`
  - `DivAssign`
  - `Rem`
  - `RemAssign`
  - `Not`
  - `BitXor`
  - `BitXorAssign`
  - `BitOr`
  - `BitOrAssign`
  - `BitAnd`
  - `BitAndAssign`
  - `Neg`
- `u*`/`i*`
  - `Add`
  - `Sub`
  - `Mul`
  - `Div`
  - `Rem`
  - `Neg`
  - `AddAssign`
  - `SubAssign`
  - `MulAssign`
  - `DivAssign`
  - `RemAssign`
  - `Not`
  - `BitAnd`
  - `BitOr`
  - `BitXor`
  - `Shl`
  - `Shr`
  - `BitAndAssign`
  - `BitOrAssign`
  - `BitXorAssign`
  - `ShlAssign`
  - `ShrAssign`

### Steps / History
- [x] Implementation: #89876.
- [ ] Tests
- [ ] Final comment period (FCP)
- [ ] Stabilization PR

### Unresolved Questions

- None yet.

**Comment by AlexApps99** [comment]
Tests need to be implemented for this, I think the files `library/core/tests/{nonzero,num/{int_macros,ops,uint_macros,wrapping}}.rs` are good places to start.

I should be able to implement them in a week or two, once I can find the time to.

**Comment by kellerkindt** [comment]
FYI: Besides `Wrapping` there also exists a [`Saturating`](https://doc.rust-lang.org/std/num/struct.Saturating.html) type

**Comment by benburk** [comment]
Any updates or blockers for this feature? Would love to be able to use these in my projects.

**Comment by AlexApps99** [comment]
I was originally planning to make tests, but I don't think that making any would be useful as it doesn't add any new functionality, and it relies on arithmetic already working in const.

Assuming tests aren't needed, the only other thing would be checking that it's ok to make this trait const. There was some debate when this PR was first made, I'm not sure what the policy is around const traits now.

**Comment by Mythra** [comment]
Hey, sorry to revive this, checking in on any potential updates/blockers. I tried converting some const functions which used `.wrapping_mul`, `.wrapping_sub`, etc. to use `Wrapping` types, and it pointed to this issue.

**Comment by AlexApps99** [comment]
Misclick! I can't think of any blockers, since const-ifying these operations doesn't necessitate tests when it uses already-const arithmetic.

It would be good to consult with somebody who can stabilize it, to get their thoughts

**Comment by TTWNO** [comment]
What needs to be done to stabilize this?

I'm looking to use this in tests. Willing to contribute tests, add docs if necessary, but let me know so we can land this.

**Comment by RalfJung** [comment]
This got entirely removed in https://github.com/rust-lang/rust/pull/110393.

**Comment by scimind2460** [comment]
Shouldn't this be reopened as `const_ops` may be taken forward by the new syntax proposed by @fee1-dead?

**Comment by RalfJung** [comment]
No, if there's a new constification it should get a new tracking issue.

**Comment by clarfonthey** [comment]
It appears that at least for the moment, #67792 and this issue are being used for new const trait impls, rather than them getting their own issues. It's also rather confusing how, despite a lot of work being done to support the "newer" const trait syntax, this old, deprecated issue is still being referenced, with a clarification that we won't open a new issue until the RFC is officially accepted.

Surely, there's a better way to do this? It definitely feels like a bureaucratic game of pretend, where we say we're not working on the new feature until it's accepted even though we are.

**Comment by clarfonthey** [comment]
Since this keeps showing up in my searches, it was replaced by #143802.
