### ISSUE TITLE
Update FFI documentation for new enum layout with smaller/selectable discrminants.

### ISSUE THREAD

**Issue by jld** [rust-lang/rust#9009]
@alexcrichton points out that, when PR #9006 (currently being inspected by bors) lands, some of the FFI documentation may become wrong if it talks about enum representations.  (Or, if it's not wrong, it should probably be extended.)

**Comment by steveklabnik** [comment]
> Rust guarantees that the layout of a `struct` is compatible with the platform's
representation in C only if the `#[repr(C)]` attribute is applied to it.
`#[repr(C, packed)]` can be used to lay out struct members without padding.
`#[repr(C)]` can also be applied to an enum.

This seems to be fine.
