### ISSUE TITLE
Tracking Issue for split_array

### ISSUE THREAD

**Issue by jethrogb** [rust-lang/rust#90091]
Feature gate: `#![feature(split_array)]`

This is a tracking issue for splitting slices and arrays into constant-length arrays.

### Public API

```rust
impl<T, const N: usize> [T; N] {
    pub fn split_array_ref<const M: usize>(&self) -> (&[T; M], &[T]);
    pub fn split_array_mut<const M: usize>(&mut self) -> (&mut [T; M], &mut [T]);

    pub fn rsplit_array_ref<const M: usize>(&self) -> (&[T], &[T; M]);
    pub fn rsplit_array_mut<const M: usize>(&mut self) -> (&mut [T], &mut [T; M]);
}

impl<T> [T] {
    pub fn split_array_ref<const N: usize>(&self) -> (&[T; N], &[T]);
    pub fn split_array_mut<const N: usize>(&mut self) -> (&mut [T; N], &mut [T]);

    pub fn rsplit_array_ref<const N: usize>(&self) -> (&[T], &[T; N]);
    pub fn rsplit_array_mut<const N: usize>(&mut self) -> (&mut [T], &mut [T; N]);
}
```

### Unresolved Questions

* [ ] Naming, see https://github.com/rust-lang/rust/pull/83233#pullrequestreview-780315524
* [ ] Array functions should return `[T; N - M]`, like so:
```rust
impl<T, const N: usize> [T; N] {
    pub fn split_array<const M: usize>(self) -> ([T; M], [T; N - M]);
    pub fn split_array_ref<const M: usize>(&self) -> (&[T; M], &[T; N - M]);
    pub fn split_array_mut<const M: usize>(&mut self) -> (&mut [T; M], &mut [T; N - M]);
}
```
However, const generics is not powerful enough for this today. See https://github.com/rust-lang/rust/pull/83233#issuecomment-947542204 and https://github.com/rust-lang/rust/pull/83233#discussion_r732722222. The array functions need to be here so the slice functions can be stabilized without forward compatibility concerns.

**Comment by scottmcm** [comment]
For the slice versions of these, I think it's important that they not only offer `-> (&[T; N], &[T])`, but also `-> (&[T], &[T; N])`.  (This is basically the same as how there's both `as_chunks` and `as_rchunks`, see #78818.)

That might open up new naming possibilities too.  To spitball:
- `split_prefix: &[T] -> (&[T; N], &[T])` and 
- `split_suffix: &[T] -> (&[T], &[T; N])`

**Comment by jplatte** [comment]
I agree that should exist, but I think it should be named `rsplit_array` since there's already a bunch of existing split functions whose "from the end" variations are all called `rsplit*`.

**Comment by yaahc** [comment]
I'd argue for local consistency over global consistency. In the case of slice we already have methods following both conventions, but the methods following the `_prefix` `_suffix` convention are related to stripping, where as the split methods all currently follow the `split` `rsplit` convention, so I lean towards keeping the current names.

**Comment by jethrogb** [comment]
Should there also be a shorthand API for `slice[a..].split_array_ref::<B>()` (the array version of `&slice[a..(a+B)]`)?

**Comment by pmnoxx** [comment]
Should the result be an `Option`?

```rust
impl<T, const N: usize> [T; N] {
    pub fn split_array_ref<const M: usize>(&self) -> Option<(&[T; M], &[T])>;
    pub fn split_array_mut<const M: usize>(&mut self) -> Option<(&mut [T; M], &mut [T])>;

    pub fn rsplit_array_ref<const M: usize>(&self) -> Option<(&[T], &[T; M])>;
    pub fn rsplit_array_mut<const M: usize>(&mut self) -> Option<(&mut [T], &mut [T; M])>;
}
```
I've been looking an api like that. However, it would be great to add a proper handling of cases, where split can't happen.

Consider
```rust
[1,2,3].split_array_ref<4>().is_none(); /// Would make sense if the split fails

/// It's useful for network code, to check if prefix has length at least 4 to decode the message.
/// This code can avoid any unwraps, because `u32::from_le_bytes` need array of 4 elements as input. 
if let Some((left, _) = [1,2,3,4,5].split_array_ref<4>() {
   println!("{}", u32::from_le_bytes(left));
}
```

**Comment by jethrogb** [comment]
`split_at` doesn't return an `Option`.

**Comment by pmnoxx** [comment]
> `split_at` doesn't return an `Option`.

Yes, that's unfortunate. I think it would be great to add `try_split_at` api. This would simplify at lot of  code.
For example:
```
impl<T, const N: usize> [T; N] {
   pub fn try_split_at(&self, mid: usize) -> Option<&[T], &[T]>

    pub fn try_split_array_ref<const M: usize>(&self) -> Option<(&[T; M], &[T])>;
    pub fn try_split_array_mut<const M: usize>(&mut self) -> Option<(&mut [T; M], &mut [T])>;

    pub fn try_rsplit_array_ref<const M: usize>(&self) -> Option<(&[T], &[T; M])>;
    pub fn try_rsplit_array_mut<const M: usize>(&mut self) -> Option<(&mut [T], &mut [T; M])>;
}
```

Currently, I have to write code like this to use the api:

```rust
let ary = [127,0,0,1,55,66];

if ary.len() >= 4 {
   let (ip,_) = ary.split_at(4);
   ///. ...
}
```
I think it would be much cleaner to write it in a functional way:

```rust
let ary = [127,0,0,1,55,66];

if let Some((ip,_)) = ary.try_split_at(4) {
  /// ...
}
```
Or even better

```rust
let ary = [127,0,0,1,55,66];

if let Some((ip,_)) = ary.try_split_array_ref<4>() {
  /// This makes ip a reference to 4 bytes array.
  /// ...
}
```

**Comment by scottmcm** [comment]
cc #95198, which proposes doing this more like the `split_first` family of things.

Those naturally would return `Option`, the same way that `first` & `split_first` return `Option` today.

**Comment by faern** [comment]
I definitely want infallible (fail at compile time) split methods on arrays. I want to be able to cut arrays up into smaller array chunks without any bounds checks at compile time. I know there are issues currently that won't allow this API today. But I think we should aim for a future where we can do that.

Being able to parse the content of arrays without paying more more bounds or code bloat than needed in definitely desired both for readability and performance. `([0u8; 100]).split_array_ref::<10>().expect("out of bounds, will never happen)` does not look nice and has a lot of code paths that we already know won't happen. If it was a compile time error we would not accidentally create bugs where the `10` was made into a too large number.

**Comment by faern** [comment]
> ```rust
> impl<T, const N: usize> [T; N] {
>     pub fn try_split_array_ref<const M: usize>(&self) -> Option<(&[T; M], &[T])>;
> }
> ```

This makes no sense IMO :thinking: Because the only time it would ever be `None` should be found at compile time. I know that's not possible now. But why introduce a large API surface and use up a bunch of good method names for something that's (hopefully)? a temporary limitation.

**Comment by Xiretza** [comment]
Would it be possible to stabilize the slice methods, while the array methods remain unstable and continue to use the temporary API until const generics are more advanced? I don't think method resolution takes stable status and return type into account, right?

This would at least give us the slice methods right now, whereas the necessary const generic work is still quite a ways away from stabilization if I'm not mistaken.

**Comment by gcxfd** [comment]
maybe can add split_array to Box<[T]> ?

**Comment by WaffleLapkin** [comment]
@gcxfd if you want `(Box<[T]>, usize) -> (Box<[T]>, Box<[T]>)` kind of function, that's impossible without re-allocating the boxes, so I don't think this will be added to `std`. If you want to get slices (`(Box<[T]>, usize) -> (&[T], &[T])`), then you can use the methods implemented on slice thanks to the deref coercion.

**Comment by Kixunil** [comment]
Note that it is currently possible to [return `&[T, (N - M)]` on nightly with an ugly warning](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=51a4d26f2b30c8782d27db58192bb223)

How hard would it be to at least allow it for `core` even if not stabilizing?

**Comment by sdroege** [comment]
While this can be implemented with multiple calls to this API, I was wondering if it wouldn't be nice to have some kind of subarray API: `[1, 2, 3, 4, 5].subarray(1, 3) == &[2, 3, 4]` or similar. Was that considered somewhere already?

**Comment by kgiebeler-xq-tec** [comment]
I stumbled upon this feature while writing a Stack ADT.

My current implementation looks like that:
```rust
    pub fn pop<const N: usize, T: From<[u8; N]>>(&mut self) -> T {
        // TODO switch to `rsplit_array_mut`, once https://github.com/rust-lang/rust/issues/90091 stabilizes
        let bytes = self.bytes.split_off(self.bytes.len() - N);
        T::from(<[u8; N]>::try_from(bytes).unwrap())
    }
```

Would it make sense to add a `split_array_off` or `split_off_array` to the family of function described in this issue?

**Comment by Xiretza** [comment]
> Would it make sense to add a `split_array_off` or `split_off_array` to the family of function described in this issue?

Isn't your example equivalent to the following (already possible on nightly)?

```rust
    pub fn pop<const N: usize, T: From<[u8; N]>>(&mut self) -> T {
        T::from(*self.bytes.split_array_ref().0)
    }
```

(or, with the suggested fallible API, `.split_array_ref().unwrap().0`)

**Comment by Kixunil** [comment]
To provide another use case for `split_array_{ref,mut}` on slice returning `Option`, this comes up a lot in deserializing code:

```rust
if bytes.len() <= 8 {
    return Err(UnexpectedEnd);
}
// panics checked above
let (a, bytes) = bytes.split_array_ref::<4>();
let a = u32::from_be_bytes(a);

let (b, _bytes) = bytes.split_array_ref::<4>();
let b = u32::from_be_bytes(a);

Ok(Self { a, b })
```

Did you notice the bug?

OTOH with option one can write:

```rust
let (a, bytes) = bytes.split_array_ref::<4>().ok_or(UnexpectedEnd)?;
let a = u32::from_be_bytes(a);

let (b, _bytes) = bytes.split_array_ref::<4>().ok_or(UnexpectedEnd)?;
let b = u32::from_be_bytes(a);

Ok(Self { a, b })
```

Which is obviously correct.

**Comment by kornelski** [comment]
I'd prefer a fallible version of this. Adding `.unwrap()` is easy, but going the other way and preventing the panic is more verbose and cumbersome.

I miss having a fallible `split_at` too, so I think its panicking should rather be considered a bug that needs to be fixed, rather than an ideal to be consistent with.

**Comment by faern** [comment]
I agree that the methods on *slices* should be fallible and not panic. And the same methods on arrays should not be fallible and instead fail at compile time. That way, no matter which version you use, there is no possible panicking code path in any of the code. So the function signatures will be different, but I don't see a problem with that.


> Note that it is currently possible to [return `&[T, (N - M)]` on nightly with an ugly warning](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=51a4d26f2b30c8782d27db58192bb223)
> 
> How hard would it be to at least allow it for `core` even if not stabilizing?

This is awesome. Would be amazing if the `generic_const_exprs` is stable enough to use this in `core`.

**Comment by faern** [comment]
> Note that it is currently possible to [return `&[T, (N - M)]` on nightly with an ugly warning](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=51a4d26f2b30c8782d27db58192bb223)
> 
> How hard would it be to at least allow it for `core` even if not stabilizing?

The `try_into` here is the part I liked the least. But it can be avoided. I wrote a version that uses `unsafe` and pointers to get the two sub-arrays out. It has no panicking code paths and compiles nicely even without optimizations. Given that it does not call a trait function (`try_into`) it is probably easier to eventually make it `const` also. Because having all of the `split_array` family of methods `const fn`s would be nice. https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=d2a8e5014aded75675b1098181e842ce

**Comment by Xiretza** [comment]
I've had these changes lying around for a while and finally pushed them in #109049. I'll take a look at making everything `const fn` as well.

**Comment by Kixunil** [comment]
@faern sure, the implementation is not that important, I was mainly concerned about API. That being said the optimizer should be smart enough to remove branches; `const` is a good point but IIUC `core` can already use experimental const traits.

**Comment by Xiretza** [comment]
> Note that it is currently possible to [return `&[T, (N - M)]` on nightly with an ugly warning](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=51a4d26f2b30c8782d27db58192bb223)
> 
> How hard would it be to at least allow it for `core` even if not stabilizing?

As noted in https://github.com/rust-lang/rust/pull/109049#issuecomment-1465179193, this will not be allowed for now.

I would still like to get an answer to https://github.com/rust-lang/rust/issues/90091#issuecomment-1185770939; if that idea is feasible, I'll implement it.

**Comment by safinaskar** [comment]
In this proposal (i. e. #90091) `[T; N]` and `[T]` will have methods with same names. This is wrong. Because this (thanks to deref coercion) will make notation `a.split_array_ref::<1>()` look very confusing

**Comment by Xiretza** [comment]
> This is wrong.

It's certainly something that should be given thought to, but I don't think it's necessarily "wrong". The same thing happens whenever a trait is implemented both for a type and its deref target, so it's not like this adds an entirely new level of confusion.

**Comment by WaffleLapkin** [comment]
As a side note: `[T; N]` -> `[T]` is not *`Deref`* coercion, it's unsize coercion (which is, I believe, special cased to participate in method resolution (as opposed to, say `[T; N] -> dyn Trait` which is still unsize coercion but does not get involved in the method resolution)).

I also don't think that's particularly confusing, as it is common in Rust to have different types have methods with the same names.

**Comment by YuriGor** [comment]
Hello everyone, how to get to know if this feature going to stay in stable version?

And also please validate my potential use case. I have my internal lightweight implementation of 2d array which stores rows in a single array, so knowing number of columns we can always slide the window to correct offset at any row we want:
```
pub struct Array2d<T: Default + Copy, const SIZE: usize, const COLUMNS: usize> {
    data: [T; SIZE],
}

impl<T: Default + Copy, const SIZE: usize, const COLUMNS: usize> Array2d<T, SIZE, COLUMNS> {
    const ROWS: usize = SIZE / COLUMNS;

// ...

    pub fn get_row(&self, row: usize) -> Option<&[T]> {
        if row < Self::ROWS {
            Some(&self.data[row * COLUMNS..(row + 1) * COLUMNS])
        } else {
            None
        }
    }

}

// ...
```
Currently i return slice from get_row. But I always know the size.
Would it make sense to use split_array_ref and rsplit_array_ref to cut off data before/after specified row and return fixed-sized ref to array?
something like (untested):
```
 pub fn get_row(&self, row: usize) -> Option<&[T; COLUMNS]> {
        if row < Self::ROWS {
            let (row_data,_) = self.data.split_array_ref::<COLUMNS * (row + 1)>(); // drop trailing data after the row
            let (_, final_row_data) = row_data.rsplit_array_ref::<COLUMNS>(); // drop leading data before the row
            Some(final_row_data)
        } else {
            None
        }
    }
 ```
 Would it have some performance benefits, like compiler would be able to optimize smth knowing fixed size beforehand compared with slices which gave dynamic size? 
Or what is main point of using these experimental methods instead of slices?

**Comment by tgross35** [comment]
There has been some ongoing discussion on Zulip, https://rust-lang.zulipchat.com/#narrow/stream/219381-t-libs/topic/Stabilizing.20array-from-slice.20*something*.3F. Copying what I said there, I think we may be able to move forward with something like the following:

1. Stabilize the API in #111774, `[T}::{split_}{first,last}_chunk{_mut}`. This provides a fallible way to get an array from a slice, everything returns an `Option`
2. Remove the slice API from #90091 (this issue). These are all infallible but the discussion has made it very clear that a panicking API is *not* wanted
3. Postpone the array API from #90091 (this issue) until `generic_const_exprs` is better off and we can provide a nonpanicking array splitting API
    a. Maybe consider something like the array indexing API `[1, 2, 3, 4, 5].subarray::<1, 3>() == &[2, 3, 4]` suggested in https://github.com/rust-lang/rust/issues/90091#issuecomment-1339622120

#111774 provides the identical API as this issue except with fallibility, which seems to be what most users want based on discussion here. I also think the naming is nicer - `chunk` is often used in std to represent a known-length array or slice, `array_ref` is only used in this method.

**Comment by tgross35** [comment]
...and I did just that in https://github.com/rust-lang/rust/pull/117561

**Comment by tgross35** [comment]
This should be reopened, I'm not sure why https://github.com/rust-lang/rust/pull/117561 closed it. Also the tracking issue can be updated to remove the `impl<T> [T]` block, #117561 removed it (and stabilized the `slice_first_last_chunk` in its place, yay!)

**Comment by tgross35** [comment]
Oh, no I only removed the slice components. I know we want a different API but figured that would just be a rework of this implementation.

But maybe it’s better to start something new with a clean tracking history. I can submit a PR to remove if so.

**Comment by tgross35** [comment]
Haven't seen it linked here, the [`arrayref`](https://docs.rs/arrayref/latest/arrayref/) crate provides a way to do this.
