### ISSUE TITLE
Error in std lib doc test

### ISSUE THREAD

**Issue by vporton** [rust-lang/rust#90092]
There is an error in std lib doc test:

```rust
use std::sync::{Arc, Mutex};
use std::thread;

let mutex = Arc::new(Mutex::new(0));
let c_mutex = Arc::clone(&mutex);

thread::spawn(move || {
     let mut lock = c_mutex.try_lock();
     if let Ok(ref mut mutex) = lock {
         **mutex = 10;
     } else {
         println!("try_lock failed");
    }
}).join().expect("thread::spawn failed");
assert_eq!(*mutex.lock().unwrap(), 10);
```

I expected to see this happen:

The code should be reliable.

Instead, this happened:

It has a race condition: `assert_eq` may happen before the thread reaches `c_mutex.try_lock();`.

### Meta
https://doc.rust-lang.org/src/std/sync/mutex.rs.html

**Comment by hkratz** [comment]
Not really, because the main thread waits for the other thread to finish with [`join`](https://doc.rust-lang.org/std/thread/struct.JoinHandle.html#method.join) before the assert.
