### ISSUE TITLE
resolver=2 still needed for workspaces when using rust 2021

### ISSUE THREAD

**Issue by rukai** [rust-lang/rust#90148]
This repo demonstrates the problem:
https://github.com/rukai/resolver2-workspace-bug

It includes wgpu 0.11 which requires resolver 2.
* If you include resolver = 2 in the workspace Cargo.toml it builds fine.
* If you remove resolver = 2 from the workspace Cargo.toml it fails with resolver = 1 related errors.

### Meta
Occurs on:
* cargo 1.57.0-nightly (7fbbf4e8f 2021-10-19)
* cargo 1.56.0 (4ed5d137b 2021-10-04)

**Comment by ehuss** [comment]
Thanks for the report!  The resolver is inherently a global setting, and in a workspace can only be set at the workspace level. The edition cannot be set globally (tracked in https://github.com/rust-lang/cargo/issues/5784), so it must be set with the `resolver = "2"` field.  There was some clarification added to [the edition guide](https://doc.rust-lang.org/nightly/edition-guide/rust-2021/default-cargo-resolver.html#details) about workspace behavior, but unfortunately did not make it into the stable docs.

I'm going to close as this is working as intended.
