### ISSUE TITLE
Duration::from_secs_f32 gives wrong results

### ISSUE THREAD

**Issue by manio** [rust-lang/rust#90225]
Hello.
I am diagnosing why I've got a wrong duration computed from Duration::from_secs_f32()...

I tried this code:
```rust
let val1 = Duration::from_secs_f32(30.0);
println!("{}", format_duration(val1).to_string());
```

I expected to see an exact 30-second duration.
Instead, I've got this:
```"30s 1us 24ns"```
which is: 30 seconds and 1024 nanos.

I dig deeper into rust code and I've prepared a sample code which is computing it based on the rust/time.rs source code:
```rust
    let secs: f32 = 30.0;
    const NANOS_PER_SEC: u32 = 1_000_000_000;
    let nanos = secs * (NANOS_PER_SEC as f32);
    let nanos = nanos as u128;
    let s = (nanos / (NANOS_PER_SEC as u128)) as u64;
    let nano = (nanos % (NANOS_PER_SEC as u128)) as u32;
    let secs = Duration::new(s, nano);
    println!("sec={}, nanos={}", s, nano);
```

As the result I've got:
```sec=30, nanos=1024```

Instead of exact 30 seconds and 0 nanos.

**Comment by nagisa** [comment]
`1_000_000_000` specifically may be representable exactly, but f32 cannot represent all integers `0..1_000_000_000` exactly. Though maybe its not a huge deal if after `trunc` we end up roundtripping back to the actual integer in all cases.
