### ISSUE TITLE
Confusing error message when matching on `&str` in `const fn`

### ISSUE THREAD

**Issue by alexschrod** [rust-lang/rust#90237]
Given the following code: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=bc51fb79544b1be00dd8a4285103ff07

```rust
const fn foo(input: &'static str) {
    match input {
        "a" => (),
        _ => (),
    }
}
```

The current output is:

```
error[E0015]: calls in constant functions are limited to constant functions, tuple structs and tuple variants
 --> src/lib.rs:3:9
  |
3 |         "a" => (),
  |         ^^^
```

I feel like it's pretty self-explanatory, but this is obviously a very confusing error. A match arm for a string literal is not a "call" by any usual meaning of the word. In fact, I have no idea what *actual* objection `rustc` has to this code, if any.

As far as I can tell, this error is the same on all current versions of the compiler (stable, beta, nightly) per the submission of this issue.

**Comment by detly** [comment]
Note also that a byte string literal is fine:

```rust
const fn decode_bytes(b: &[u8]) -> Option<u8> {
    match b {
        b"0" => Some(0),
        _ => None,
    }
}
```

:point_up: compiles, but

```rust
const fn decode_string(s: &str) -> Option<u8> {
    match s {
        "0" => Some(0),
        _ => None,
    }
}
```

...fails with:

```none
error[[E0015]](https://doc.rust-lang.org/stable/error-index.html#E0015): cannot call non-const operator in constant functions
 --> src/lib.rs:3:9
  |
3 |         "0" => Some(0),
  |         ^^^
  |
  = note: calls in constant functions are limited to constant functions, tuple structs and tuple variants

For more information about this error, try `rustc --explain E0015`.
error: could not compile `playground` due to previous error
```

**Comment by jnnnnn** [comment]
I ran into this as well. It's definitely calling `<str as PartialEq>::eq` as part of the match. The way to prove so is to look at the MIR (and remove `const` so the code compiles).

The const_str crate gets around this by [converting to bytes](https://github.com/Nugine/const-str/blob/main/const-str/src/__ctfe/equal.rs) for the comparison. But I can't see how to use this in a match either.
