### ISSUE TITLE
Rustc suggests importing trait inside private module

### ISSUE THREAD

**Issue by Nilstrieb** [rust-lang/rust#90258]
```rust
fn main() {
    let _ = [0; 32].slice();
}
```

The current output is:

```
error[E0599]: no method named `slice` found for array `[{integer}; 32]` in the current scope
 --> priv.rs:2:18
  |
2 |     let _ = [0; 32].slice();
  |                     ^^^^^ method not found in `[{integer}; 32]`
  |
  = help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
  |
1 | use std::collections::vec_deque::ring_slices::RingSlices;
  |

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
```

Here, rustc suggests importing the trait `RingSlices`, which is inside a private module and can't be used.

If possible, rustc should probably check whether a suggested trait is usable in the current module, and only suggest it if it is.

One thing that is useful about the current version is, that it might suggest that the user should make the module public if they control it. Maybe it should still be emitted if the trait is in the current crate.

Found by @angelsflyinhell, a rust beginner that was a bit confused by this

**Comment by nsunderland1** [comment]
I've also hit this, but there's another angle here. I have my own trait that was intended to be public, but I forgot to make it `pub`. rustc suggested that I try importing it, but what I'd really like for it to do is suggest that I make the trait public.

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=c106a9ccab60655a33e4388f77d0b4c6

**Comment by Nilstrieb** [comment]
I think it should still suggest it if it's in the same crate. But better now for external crates. If there's some way to find out if the external crate is in the same workspace, then this could be special cased as well to show it again.

**Comment by Nilstrieb** [comment]
Update: on the current nightly, I don't get the suggestion anymore.
```
error[E0599]: no method named `slice` found for array `[{integer}; 32]` in the current scope
 --> aaa.rs:2:21
  |
2 |     let _ = [0; 32].slice();
  |                     ^^^^^ help: there is a method with a similar name: `as_slice`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
```
