### ISSUE TITLE
Regression in File::read_to_end on 1.57.0 Nightly

### ISSUE THREAD

**Issue by noproto** [rust-lang/rust#90263]
PR #89582 (commit 910692de742e9c0b1a57b7c5e467b8b85d903269) created a regression in File::read_to_end on the Rust Nightly channel (1.57.0 Nightly). This is before main(), it impacts cdylib projects.

### Code

`lib.rs`

```rust
use std::io::prelude::*;

// init_rtld_audit_interface
#[used]
#[allow(non_upper_case_globals)]
#[link_section = ".init_array"]
static init_rtld_audit_interface: unsafe extern "C" fn(i32, *const *const i8, *const *const i8) = {
    #[link_section = ".text.startup"]
    unsafe extern "C" fn init_rtld_audit_interface(_argc: i32, _argv: *const *const i8, _envp: *const *const i8) { read_proc_environ(); }
    init_rtld_audit_interface
};

// la_version
#[no_mangle]
unsafe extern "C" fn la_version(version: u32) -> u32 { version }

fn read_proc_environ() {
    let mut environ = std::fs::File::open("/proc/self/environ").expect("Lost track of environment");
    let mut environ_contents: Vec<u8> = vec![];
    environ.read_to_end(&mut environ_contents).expect("Unexpected null reference");
}
```

`Cargo.toml`

```
# General info
[package]
name = "readenv"
version = "0.1.0"
edition = "2021"

# Build targets
[lib]
name = "readenv"
path = "lib.rs"
crate-type = ["cdylib"]
```

`Makefile`

```
test:
	@echo "Rust nightly-10-09"
	cargo +nightly-2021-10-09 build --lib --release;LD_AUDIT=${PWD}/target/release/libreadenv.so /usr/bin/test || true
	@echo "Rust nightly-10-10"
	cargo +nightly-2021-10-10 build --lib --release;LD_AUDIT=${PWD}/target/release/libreadenv.so /usr/bin/test || true
```

I expected to see this happen: (no output)
```
Rust nightly-10-09
cargo +nightly-2021-10-09 build --lib --release;LD_AUDIT=/home/user/readenv/target/release/libreadenv.so /usr/bin/test || true
   Compiling readenv v0.1.0 (/home/user/readenv)
    Finished release [optimized] target(s) in 0.55s
Rust nightly-10-10
cargo +nightly-2021-10-10 build --lib --release;LD_AUDIT=/home/user/readenv/target/release/libreadenv.so /usr/bin/test || true
   Compiling readenv v0.1.0 (/home/user/readenv)
    Finished release [optimized] target(s) in 0.44s
```

Instead, this happened: Segmentation fault
```
Rust nightly-10-09
cargo +nightly-2021-10-09 build --lib --release;LD_AUDIT=/home/user/readenv/target/release/libreadenv.so /usr/bin/test || true
   Compiling readenv v0.1.0 (/home/user/readenv)
    Finished release [optimized] target(s) in 0.55s
Rust nightly-10-10
cargo +nightly-2021-10-10 build --lib --release;LD_AUDIT=/home/user/readenv/target/release/libreadenv.so /usr/bin/test || true
   Compiling readenv v0.1.0 (/home/user/readenv)
    Finished release [optimized] target(s) in 0.44s
Segmentation fault
```

### Version it worked on

It most recently worked on: Rust 1.57.0-nightly, nightly-2021-10-09-aarch64-unknown-linux-gnu

### Version with regression

Regression occurred in: Rust 1.57.0-nightly, nightly-2021-10-10-aarch64-unknown-linux-gnu

`rustc --version --verbose`:
```
rustc 1.57.0-nightly (a8f2463c6 2021-10-09)
binary: rustc
commit-hash: a8f2463c68a6532d74a13ec402ec5b513e4e2726
commit-date: 2021-10-09
host: aarch64-unknown-linux-gnu
release: 1.57.0-nightly
LLVM version: 13.0.0
```

@rustbot modify labels: +regression-from-stable-to-nightly -regression-untriaged

**Comment by joshtriplett** [comment]
I can fairly easily imagine ways we could fix this *specific* incarnation of this issue. For instance, this optimization doesn't really need statx.

However, we don't in general make guarantees about the exact syscalls or library functions we call. I personally think the LD_AUDIT interface may be sufficiently specialized that we can't necessarily guarantee Rust functions will remain within the constraints of what's necessary to be called in that context.

**Comment by joshtriplett** [comment]
We discussed this again in today's @rust-lang/libs meeting.

We agreed that, in general, we're not prepared to keep all of the standard library within the limitations required to implement an `LD_AUDIT` library.

However, we'd absolutely be amenable in general to alternatives to `dlsym`. We used to use weak symbols, but that caused problems with tools that use symbol references to set library package dependencies (e.g. Debian's `dh_shlibdeps` tool); if those tools could learn to ignore weak symbols, or there was some way we could declare them such that those tools ignore them, we could go back to using them. Or, alternatively, we could make syscalls directly, in cases where the C library's wrapper is not essential. (There are syscalls that are not necessarily safe to call directly, but for the rest we could.)

**Comment by cuviper** [comment]
> We used to use weak symbols, but that caused problems with tools that use symbol references to set library package dependencies (e.g. Debian's `dh_shlibdeps` tool);

The specific problem there was #23628 because we use `__pthread_get_minstack@GLIBC_PRIVATE`, which does not have a normal sortable version. That symbol could also go away at any time, being private and all, but glibc authors are aware that we're using it and have said that they will work with us before changing it. With a `dlsym`-based weak symbol, we would actually be just fine if they remove it altogether.

For everything else we use as a weak symbol, I think it would be fine for those to resolve to a normal `name@GLIBC_X.Y.Z` symbol, just like any non-weak symbol we use. If that happens on our maximally-compatible dist builds with old glibc, this is a sign that we don't really need to be weak on that one anymore. This would not be the case for `statx`, but an ELF-weak symbol might still fare better in this `LD_AUDIT` environment.

I'm basically suggesting that we could keep the `dlsym`-weak for `__pthread_get_minstack`, but switch to ELF-weak symbols for stuff that we know is properly stable and versioned in newer glibc. And for stuff like `clone3` that doesn't have any libc wrapper yet, we should probably always use `syscall` for now, without any weak symbols. I can play with this.

**Comment by cuviper** [comment]
See #90846 for an attempt at weak linkage.
