### ISSUE TITLE
extra::json: Remove or rework ToJson

### ISSUE THREAD

**Issue by bluss** [rust-lang/rust#9028]
There are two ways to encode values into json in string form, and they can provide different results or be wrong:

* ToJson transforms a rust value to Json, which can be encoded by a `serialize::Encoder`

* `json::Encoder` implements the `Encoder` trait, so you can give it arbitrary values, as long as they implement  `Encodable`, and it will output json, or json-like text.

We need to provide a single method of encoding to Json, and make sure we use `serialize` correctly if we use it.

The ToJson trait expresses the restriction that only maps with string keys can be encoded to Json. This is easy to step around by using the other json encoding method, which results in invalid json.

**Comment by steveklabnik** [comment]
Encoding has been moved out, and we've had some related improvements since then. I'm giving this a close. If you feel some of this is still important, please open it on https://github.com/rust-lang/rustc-serialize
