### ISSUE TITLE
regression: rustc suggests `.as_ref()` at incorrect location and other spans have regressed

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#90286]
### Code

[Playground (regressed rustc version)](https://play.rust-lang.org/?version=beta&mode=debug&edition=2021&gist=fb0cec09ebd743b2242ecb1168b9ca3e)

```rust
fn foo(opt: &Option<Box<i32>>) -> String {
    opt.map(|x| x.to_string()).unwrap_or_else(String::new)
}
```

### Output (stable 1.56.0, good)

```
error[E0507]: cannot move out of `*opt` which is behind a shared reference
 --> src/lib.rs:2:5
  |
2 |     opt.map(|x| x.to_string()).unwrap_or_else(String::new)
  |     ^^^ move occurs because `*opt` has type `Option<Box<i32>>`, which does not implement the `Copy` trait
  |
help: consider borrowing the `Option`'s content
  |
2 |     opt.as_ref().map(|x| x.to_string()).unwrap_or_else(String::new)
  |        +++++++++

For more information about this error, try `rustc --explain E0507`.
```

### Output (beta 1.57.0-beta.2, incorrect)

```
error[E0507]: cannot move out of `*opt` which is behind a shared reference
 --> src/lib.rs:2:5
  |
2 |     opt.map(|x| x.to_string()).unwrap_or_else(String::new)
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^ move occurs because `*opt` has type `Option<Box<i32>>`, which does not implement the `Copy` trait
  |
help: consider borrowing the `Option`'s content
  |
2 |     opt.map(|x| x.to_string()).as_ref().unwrap_or_else(String::new)
  |                               +++++++++

For more information about this error, try `rustc --explain E0507`.
```

**Comment by pnkfelix** [comment]
I spoke to @camelid ; they will not have a lot of time to investigate this in the near term future. So, assigning self to determine if a revert of PR #89110 is warranted (and maybe to identify alternative solutions).

**Comment by Mark-Simulacrum** [comment]
@pnkfelix we're ~1 week out from release, will you be able to prepare the revert in time, or do we need to find someone else to do that?

**Comment by estebank** [comment]
I'd looked at this a few weeks back: the problem is that reverting this causes *another* bug to resurface. We need two different spans for both these suggestions (and the one that were "fixed" by the PR with the regression) to work correctly :-/

If needed I can try and fix it next week before the release, but I'll need someone to be responsive for the review.

**Comment by zseri** [comment]
Could, as a temporary somewhat-partial mitigation, the `as_ref` suggestion be downgraded from {points directly at a (currently wrong) location in the code} to {it is suggested in a note that an as_ref should be inserted near the highlighted code, but without a direct pointer with +++}?. That would reduce the confusion a bit, I suppose.

**Comment by estebank** [comment]
Triage: [fixed in current beta](https://play.rust-lang.org/?version=beta&mode=debug&edition=2021&gist=09298ca11e5ce81741baf87b99abe57d):

```
error[E0507]: cannot move out of `*opt` which is behind a shared reference
 --> src/lib.rs:2:5
  |
2 |     opt.map(|x| x.to_string()).unwrap_or_else(String::new)
  |     ^^^^----------------------
  |     |   |
  |     |   `*opt` moved due to this method call
  |     move occurs because `*opt` has type `Option<Box<i32>>`, which does not implement the `Copy` trait
  |
note: this function takes ownership of the receiver `self`, which moves `*opt`
help: consider calling `.as_ref()` to borrow the type's contents
  |
2 |     opt.as_ref().map(|x| x.to_string()).unwrap_or_else(String::new)
  |         +++++++++
```

**Comment by WaffleLapkin** [comment]
Hm, it seems like there are already tests for `as_ref` suggestion, namely [`option-content-move.rs`](https://github.com/rust-lang/rust/blob/a9bb589cd678e034d194193fa892942315b10e2a/src/test/ui/suggestions/option-content-move.rs), [`as-ref.rs`](https://github.com/rust-lang/rust/blob/a9bb589cd678e034d194193fa892942315b10e2a/src/test/ui/suggestions/as-ref.rs) and [`as-ref-2.rs`](https://github.com/rust-lang/rust/blob/a9bb589cd678e034d194193fa892942315b10e2a/src/test/ui/suggestions/as-ref-2.rs), should this be closed then?

**Comment by zseri** [comment]
should we wait for the commits which seem to fix this to hit stable, or can we close this already?

**Comment by estebank** [comment]
We can close now.
