### ISSUE TITLE
Add a rustdoc user guide to https://doc.rust-lang.org/rustdoc

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#90309]
Right now, https://doc.rust-lang.org/rustdoc is mostly developer-oriented, it has lots of info about how to use rustdoc the tool but not how to use the generated docs. We should add a user-focused page to it that mentions options people don't usually know about, e.g.
- `?` for search tips
- the "In Parameters" and "In Return Types" tab of search
- the settings page maybe?

**Comment by NoraCodes** [comment]
Throwing my hat in the ring on this one. Let me know if you'd like me to add some docs for the settings page!

**Comment by jyn514** [comment]
This was added in #90487; thanks @NoraCodes !
