### ISSUE TITLE
rustdoc: Pass Context as a &mut to allow to remove RefCell fields

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/rust#90323]
It was discussed in https://github.com/rust-lang/rust/pull/90183 because of the add of the `Context::deref_id_map` field.

**Comment by Milo123459** [comment]
@rustbot claim

Going to give this one a try!

**Comment by Milo123459** [comment]
To be clear, I'm removing the `RefCell` from the types, not removing those fields, right?

**Comment by GuillaumeGomez** [comment]
Yes.

**Comment by jyn514** [comment]
Hi @Milo123459, have you had time to work on this? Feel free to ask here or [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/266220-rustdoc) if you need help :)

**Comment by Milo123459** [comment]
I have worked on it pretty actively. The amount of borrowing errors is.. indescribably large.

**Comment by jyn514** [comment]
@Milo123459 let me see if I can help with that at all :) I pinged you on https://rust-lang.zulipchat.com/#narrow/stream/266220-rustdoc/topic/.26mut.20Context so we can talk with less delay.

**Comment by Milo123459** [comment]
Fantastic!

**Comment by Milo123459** [comment]
Finally made a PR for it! https://github.com/rust-lang/rust/pull/91468

**Comment by GuillaumeGomez** [comment]
> Is this not a command? :(

Apparently not. :laughing: 

I'll take a look to this issue then based on your work.

**Comment by camelid** [comment]
@Milo123459 the command is <code>@rustbot release-<strong>assignment</strong></code> :)

**Comment by Milo123459** [comment]
Ahh!
