### ISSUE TITLE
Work around custom section flag regression in LLVM

### ISSUE THREAD

**Issue by nikic** [rust-lang/rust#90326]
LLVM 13 has removed support for setting custom section flags in https://reviews.llvm.org/D100944. LLVM 13 carries a revert of the problematic change (https://reviews.llvm.org/D107216). However, LLVM 14 will no longer carry it, and we need to use alternative ways to set custom section flags.

There are currently two places affected by this. The `.llvmbc` bitcode section created in https://github.com/rust-lang/rust/blob/ffba4309241a7a21df4ec7b16f1357cbcd327d6e/compiler/rustc_codegen_llvm/src/back/write.rs#L926 and the `.rustc` metadata section created in https://github.com/rust-lang/rust/blob/612356aa9a0193cb5aee2b668b3893ddf67da2b5/compiler/rustc_codegen_llvm/src/base.rs#L41. In both cases, section flags are used to ensure that the section is not linked into the final binary or loaded into memory.

There are two ways to address this. The first one is to define the section entirely in module-level assembly. Rather than only emitting `.section`, we should also emit `.ascii "ENCODED_SECTION_CONTENTS"`, as well as the symbol name and any other necessary directives (e.g. for visibility). I'm not sure exactly what is needed on different platforms here.

The second one is to use the object crate to create the object file containing the section. The cranelift backend already implements this for the `.rustc` section in https://github.com/rust-lang/rust/blob/ffba4309241a7a21df4ec7b16f1357cbcd327d6e/compiler/rustc_codegen_cranelift/src/metadata.rs#L10. A nice side benefit of this is that the handling would be codegen-backend agnostic and could be shared between the llvm/cranelift/gcc backends.

The suggested course of action is to use the object crate for `.rustc` and inline assembly for `.llvmbc`. The reason for the latter is that the section is part of a larger object file emitted by LLVM, and the `object` crate doesn't seem great for modifying existing object files (as opposed to creating one from scratch). Though if we can use the object crate for everything, that would of course be great.

**Comment by cuviper** [comment]
This was auto-closed by commit text, but it's not actually done yet.

**Comment by nikic** [comment]
Fixed by https://github.com/rust-lang/rust/pull/91604 and https://github.com/rust-lang/rust/pull/91654.

**Comment by tstellar** [comment]
> > For LTO, it's better to just emit the correct object file for the linking mode/modes you're actually using. That's why it surprises me that this is something rust is running into.
> 
> We have to support libraries that are capable of LTO, but don't require it. The same standard library is used for LTO and non-LTO usage and as such needs to contain LTO bitcode, but also machine code at the same time.

Is the bitcode from libraries that are compiled with -fembed-bitcode even used for LTO?  https://github.com/rust-lang/rust/issues/74657#issuecomment-709632154 implies that gold and lld both ignore the bitcode, and that the presence of the bitcode triggers a bug in the llvm plugin when linking with bfd.  That makes it sound like embedding the bitcode doesn't give rust the feature that it wants.

**Comment by nikic** [comment]
@tstellar Normally rust does LTO as part of the compiler (despite the name). In that case the bitcode is obtained using `IRObjectFile::findBitcodeInMemBuffer()`, which accepts both plain bitcode and various object file types. That's the kind of LTO I was referring to there.

When linker plugin LTO is enabled, then only bitcode is produced instead: https://github.com/rust-lang/rust/blob/9e1aff82e696c0edb568656ae6b509a9ab4d6c92/compiler/rustc_codegen_ssa/src/back/write.rs#L146-L163 I think the case you are referring to is the `!no_nobuiltins` exception there, which seems like the only case that may have embedded bitcode in that case. (Possibly that case should be forcing a plain object file without embedded bitcode if the embedded bitcode causes issues? As the code is written, it's not obvious whether `ObjectCode(BitcodeSection::Full)` may be returned in that case.)
