### ISSUE TITLE
Tracking Issue for constify-ing CStr::from_bytes_with_nul_unchecked

### ISSUE THREAD

**Issue by xfix** [rust-lang/rust#90343]
The feature gate for the issue is `#![feature(const_cstr_unchecked)]`.

This is a tracking issue for constify-ing `CStr::from_bytes_with_nul_unchecked`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide]) #91855

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stability.html#stabilizing-a-library-feature
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Unresolved Questions

XXX --- list all the "unresolved questions" found in the RFC to ensure they are
not forgotten

### Implementation history

- [x] https://github.com/rust-lang/rust/issues/54678

**Comment by Amanieu** [comment]
@rfcbot fcp merge

**Comment by Amanieu** [comment]
@rfcbot merge
