### ISSUE TITLE
rustdoc outputs text too large for text box

### ISSUE THREAD

**Issue by IsaccBarker** [rust-lang/rust#90351]
### Problem

I created a crate with a file that is included at compile time with `include_str!`. When I generated the docs, I found that the file content was also printed in the documentation, and since it was rather long, it exceeded the dialog box.

### Steps

1. Include a file in a crate, that is contained within a global constant
2. Generate the documentation
3. Navigate to the documentation, and see roughly was is in the attached image.

### Notes

[Link to image](https://drive.google.com/file/d/1fyu6NN5Httrct7DUGN1F4ZmNMK-2v_xL/view?usp=sharing).

### Version

```text
cargo 1.55.0 (32da73ab1 2021-08-23)
release: 1.55.0
commit-hash: 32da73ab19417aa89686e1d85c1440b72fdf877d
commit-date: 2021-08-23
```

**Comment by jsha** [comment]
@IsaccBarker I see you're running `cargo 1.55.0 (32da73ab1 2021-08-23)`. @GuillaumeGomez recently landed some fixes for long names: https://github.com/rust-lang/rust/pull/90018. Does that fix the issue?

**Comment by GuillaumeGomez** [comment]
![Screenshot from 2022-02-15 14-24-24](https://user-images.githubusercontent.com/3050060/154070863-08365333-9479-4550-bab9-66fd359e90d2.png)

It seems to be fixed so closing.
