### ISSUE TITLE
 compiler paho.matt.rust by aarch64-linux-android has this error

### ISSUE THREAD

**Issue by Leoaaron** [rust-lang/rust#90367]
$cargo build --target aarch64-linux-android  --examples

thread 'rustc' panicked at 'called `Option::unwrap()` on a `None` value', compiler/rustc_codegen_llvm/src/back/archive.rs:358:67
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: <rustc_codegen_llvm::back::archive::LlvmArchiveBuilder as rustc_codegen_ssa::back::archive::ArchiveBuilder>::build
   4: rustc_codegen_ssa::back::link::link_binary
   5: <rustc_codegen_llvm::LlvmCodegenBackend as rustc_codegen_ssa::traits::backend::CodegenBackend>::link
   6: rustc_interface::queries::Linker::link
   7: rustc_span::with_source_map
   8: scoped_tls::ScopedKey<T>::set
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.56.0 (09c42c458 2021-10-18) running on x86_64-apple-darwin

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C linker=/Users/bytedance/.NDK/arm64/bin/aarch64-linux-android-gcc -C incremental --crate-type lib

note: some of the compiler flags provided by cargo are hidden

.cargo/config
--------------
[build]
target = "armv7-linux-androideabi"

[target.armv7-linux-androideabi]
linker = "/Users/bytedance/Library/Android/sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi16-clang"
ar = "/Users/bytedance/Library/Android/sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/darwin-x86_64/bin/armv7a-linux-androideabi16-ar"

[target.aarch64-linux-android]
linker = "/Users/bytedance/.NDK/arm64/bin/aarch64-linux-android-gcc"
ar = "/Users/bytedance/.NDK/arm64/bin/aarch64-linux-android-ar"

**Comment by Enselic** [comment]
Triage: Without a way for others to reproduce the ICE, not much can be done at this point. Closing.
