### ISSUE TITLE
[ER] match branch #[likely] annotation

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust#90397]
Other design are possible, but this seems the simplest one to me. Only at most one branch is allowed to have the #[likely] annotation. There isn't an #[unlikely] annotation.

```rust
fn try_div(x: u32, y: u32) -> Option<u32> {
    match y {
        0 => None,
        #[likely]
        _ => Some(x / y),
    }
}
```

Only at most one branch is allowed to have the #[likely] annotation. There isn't an #[unlikely] annotation.

A successive optional refinement of this idea is to allow an optional natural number N >= 0 that specifies how much likely branches are. In this case more than one #[likely(N)] annotation is allowed, and duplicated N are allowed.

**Comment by saethlin** [comment]
There's been a lot of previous discussion here: https://github.com/rust-lang/rust/issues/26179

**Comment by leonardo-m** [comment]
Yes, thank you.
