### ISSUE TITLE
Rust compiler building error.

### ISSUE THREAD

**Issue by sohamdixit81** [rust-lang/rust#90432]
I have clone the source code and tried to build the Rust but getting some error.
The error is:
~/rust$ python3 ./x.py build 
Updating only changed submodules
Submodules updated in 0.02 seconds
downloading https://static.rust-lang.org/dist/2021-10-22/rust-std-beta-x86_64-unknown-linux-gnu.tar.xz
######################################################################### 100.0%
invalid checksum:
    found:    e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
    expected: 7692b0b44eea139874fb8c6cbaca46b8f156ce392454ee4891daad532a5c6baa
Traceback (most recent call last):
  File "./x.py", line 27, in <module>
    bootstrap.main()
  File "/home/soham/rust/src/bootstrap/bootstrap.py", line 1252, in main
    bootstrap(help_triggered)
  File "/home/soham/rust/src/bootstrap/bootstrap.py", line 1218, in bootstrap
    build.download_toolchain()
  File "/home/soham/rust/src/bootstrap/bootstrap.py", line 412, in download_toolchain
    self._download_component_helper(filename, pattern, tarball_suffix, stage0)
  File "/home/soham/rust/src/bootstrap/bootstrap.py", line 553, in _download_component_helper
    get(
  File "/home/soham/rust/src/bootstrap/bootstrap.py", line 49, in get
    raise RuntimeError("failed verification")
RuntimeError: failed verification

All prerequisite are fulfilled, I have followed each and every step.
I have also tried from this link - https://rustc-dev-guide.rust-lang.org/getting-started.html#cloning-and-building
I have also shared the details of error on zulip i.e. https://rust-lang.zulipchat.com

I have tried deleting everything and re-cloning it, downloaded this folder manually https://static.rust-lang.org/dist/2021-10-22/rust-std-beta-x86_64-unknown-linux-gnu.tar.xz and placed it.

Please let me know the error or what changes I should do.
Thanks in Advance.

**Comment by Dylan-DPC** [comment]
Closing this to clean up the issue tracker. I assume this is solved but if anyone reading this needs help you can consult zulip, discords or the forums.
