### ISSUE TITLE
lifetime specifier being treat as a component of a type constraint

### ISSUE THREAD

**Issue by divinusdracodominus** [rust-lang/rust#90468]
when attempting to constrain a generic parameter T as being able to perform numerical operations between references of itself, the lifetime specifier of the constraint definition is being treated as part of the type signature of the constraint. For example
```
impl<T: num::traits::NumOps<&T, &T>> MyStruct<T> {

}
```
is requiring that a named lifetime specifier be present on &T to make &'a T (for example) but a lifetime specifier should be a component of a value, not of a type, forgetting of course the fact that in most use cases being able to perform say Add<T, T> should imply Add<&T, &T> 

Mul<&T, &T> is required in this case as performing T * T would result in a move, a constraint could further be added to either clone, or copy the type, however, I'm curious what use cases would require T be consumed in a multiplication operation, rather then performing a copy (shouldn't Add/Mul imply copy)

**Comment by jyn514** [comment]
it sounds like you're suggesting that `T: Add<T>` should imply `&T: Add<&T>`. That's not valid in all cases though; consider for example [`impl Add<Cow<str>> for Cow<str>`](https://doc.rust-lang.org/nightly/alloc/borrow/enum.Cow.html#impl-Add%3CCow%3C'a,+str%3E%3E-for-Cow%3C'a,+str%3E), where T isn't Copy.

> the lifetime specifier of the constraint definition is being treated as part of the type signature of the constraint

This looks like a fairly fundamental change to the language. The issue tracker is not an effective way to get feedback on language changes; consider instead posting on [Zulip](https://rust-lang.zulipchat.com/#narrow/stream/122651-general) or [internals.rust-lang.org](https://internals.rust-lang.org/).

That said, this is very unlikely to change IMO.
