### ISSUE TITLE
modify an existing symlink?

### ISSUE THREAD

**Issue by keepsimple1** [rust-lang/rust#90509]
https://github.com/rust-lang/rust/blob/18bc4bee9710b181b440a472635150f0d6257713/library/std/src/os/unix/fs.rs#L899

It seems that this function returns Error when the symlink already exists. Is there a way to force overwriting an existing symlink using Rust in Unix?  (like `ln -fs <original> <symlink>`  in Unix shells).

**Comment by the8472** [comment]
The API documentation says

> Creates a new symbolic link on the filesystem.

The **new** could be considered significant here, i.e. it doesn't work on existing ones. Changing that would then be a breaking change. A fairly destructive one if existing code relies on it not overwriting files.

And the underlying syscalls don't support overwriting existing ones either. Instead `ln` does a dance of creating a temporary symlink with a random name and then `rename`ing it over the target.

**Comment by keepsimple1** [comment]
OK, although I wish there was a way in Rust to overwrite the symlink, I understand it. Thanks.

**Comment by keepsimple1** [comment]
OK, although I wish there was a way in Rust to overwrite the symlink, I understand it. Thanks.

**Comment by the8472** [comment]
Well, adding new method with that behavior would be possible, assuming there's enough demand for it. On the other hand this could also be implemented by a crate, e.g. one that provides common "scripting" or "shell-like" behaviors.
