### ISSUE TITLE
Deadlocks in error messages with defaults and const parameters in the same parameter list

### ISSUE THREAD

**Issue by ETKNeil** [rust-lang/rust#90501]
I tried this code:

```rust
pub(crate) trait Safe1<const CHAR_1: char,Input = Self>{}

pub(crate) trait Safe2<Input = Self, const CHAR_1: char>{}
```

This happened:  
```rust
error: type parameters must be declared prior to const parameters
 --> src/lib.rs:1:43
  |
1 | pub(crate) trait Safe1<const CHAR_1: char,Input = Self>{}
  |                       --------------------^^^^^-------- help: reorder the parameters: lifetimes, then types, then consts: `<Input = Self, const CHAR_1: char>`

error: generic parameters with a default must be trailing
 --> src/lib.rs:3:24
  |
3 | pub(crate) trait Safe2<Input = Self, const CHAR_1: char>{}
  |                        ^^^^^
  |
  = note: using type defaults and const parameters in the same parameter list is currently not permitted
```

This pattern is seemlingly an error deadlock since you first follow the advice from the rust compiler but then it tells you that it should be trailing so technically you should go back to the first one. However I do note that that the `note` says that const and default are not possible. I just want to point out the irony of the error type in this case as they are a deadlock by themselves.

### Meta
This works on stable and nightly link to the playground : https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=db0564d9016ca18558c2855c6110c29e

**Comment by Dylan-DPC** [comment]
There is no deadlock situation any more as the first line doesn't emit this error
