### ISSUE TITLE
perf regression from adt_significant_drop_fix

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#90504]
Spawned off of: https://github.com/rust-lang/rust/pull/90218#issuecomment-954300896

- regression-31157 check regressed by 4.7% on incr and 5.3 on full.
- issue-46449 check regressed by 1.89% on incr-full.
- wg-grammar regressed by 1.3-1.4% in a bunch of scenarios.

Its *possible* that this is inherent in the change injected by PR #90218. But its also possible that we could fix things to remove these regressions.

**Comment by Mark-Simulacrum** [comment]
Closing as fixed by #90845, though we may end up reverting it.
