### ISSUE TITLE
Standard library documentation documents trait implementations for the miniz_oxide crate

### ISSUE THREAD

**Issue by FSMaxB** [rust-lang/rust#90526]
While looking at the standard library documentation of `std::result::Result` I found some trait implementations of `From<StreamResult>` documented there. These belong to the `miniz_oxide` crate. I do not think this trait implementation belongs in the standard library documentation.

See https://doc.rust-lang.org/stable/std/result/enum.Result.html#impl-From%3CStreamResult%3E
This is also present in the standard library documentation that `rustup` installs locally.

### Meta
The Version string on docs.rust-lang.org is `Version 1.56.1 (59eed8a2a 2021-11-01)` at the time of writing.

I was told on the `#docs-rs` discord channel to tag @GuillaumeGomez in this issue.

**Comment by GuillaumeGomez** [comment]
They should definitely not be displayed.

**Comment by notriddle** [comment]
This seems related to https://github.com/rust-lang/rust/issues/88696.

**Comment by GuillaumeGomez** [comment]
Thanks for the link!

**Comment by GuillaumeGomez** [comment]
It is, but the `miniz-oxide` crate might still want to show these impls though.
