### ISSUE TITLE
Missing unconstrained generic constant error if `adt_const_params` feature is included

### ISSUE THREAD

**Issue by b-naber** [rust-lang/rust#90531]
Based on the example in https://github.com/rust-lang/rust/issues/90455, which after the changes in https://github.com/rust-lang/rust/pull/90529 would output an `unconstrained generic constant` error. The following code, however, does not output such an error, although I believe it should.

Given the following code: 

```rust
#![feature(generic_const_exprs, adt_const_params)]

const fn num_limbs(_: &str) -> usize {
    5   
}

fn foo<const N: &'static str>(_arr: [u64; num_limbs(N)]) where [u64; num_limbs(N)]: {}

fn main() {
  let arr = [5; 5];       
  foo(arr);
}
```

The current output is:

```
error[E0284]: type annotations needed: cannot satisfy `the constant `foo::<{_: &'static str}>::{constant#0}` can be evaluated`
  --> test2.rs:17:3
   |
17 |   foo(arr);
   |   ^^^ cannot satisfy `the constant `foo::<{_: &'static str}>::{constant#0}` can be evaluated`
   |
note: required by a bound in `foo`
  --> test2.rs:13:70
   |
13 | fn foo<const N: &'static str>(_arr: [u64; num_limbs(N)]) where [u64; num_limbs(N)]: {}
   |                                                                      ^^^^^^^^^^^^ required by this bound in `foo`

error: aborting due to previous error; 2 warnings emitted

```

This only happens if the `adt_const_params` is included. This also compiles if you don't include the call of `foo` in main.

**Comment by BoxyUwU** [comment]
dont think this is related to adt_const_params as this has the same error:
```rust
#![feature(generic_const_exprs)]

fn foo<const N: usize>(_arr: [u64; N + 1]) where [u64; N + 1]: {}

fn main() {
  let arr = [5; 5];       
  foo(arr);
}
```

**Comment by lcnr** [comment]
the reason this happens is because from `some_expr(N) == 5` we don't infer the value for `N`.

The error message should be improved by using `emit_inference_failure_err` in this branch

https://github.com/rust-lang/rust/blob/7036449c774860a5b348dbbe01c20704c557382e/compiler/rustc_trait_selection/src/traits/error_reporting/mod.rs#L2160-L2173

for that the predicates should be searched for a relevant inference variable.

**Comment by lcnr** [comment]
going to mentor this issue in case someone wants to fix this
