### ISSUE TITLE
Special case suggestion for missing tail expression when dealing with `Ok(())` and `Some(())`

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#90553]
The suggestion in the following code isn't great:

```
error[E0308]: mismatched types
  --> src/main.rs:72:5
   |
72 | /     while let Some(i) = x.try_next().await? {
73 | |         println!("{:?}", i);
74 | |     }
   | |_____^ expected enum `Option`, found `()`
   |
   = note:   expected enum `Option<()>`
           found unit type `()`
help: try using a variant of the expected enum
   |
72 ~     Some(while let Some(i) = x.try_next().await? {
73 +         println!("{:?}", i);
74 +     })
   |
```

It makes sense why it happens: the `while let` expression resolves to type `()`, it's the tail expression of an `async fn` that returns `Option<()>`, so wrapping the expression in `Some(())` would make the type checker happy, but suggesting that seems almost always wrong? I think I would prefer it if we special cased this and didn't gave a suggestion for `Result<(), _>` or `Option<()>`.

**Comment by m-ou-se** [comment]
How about something like this?

![image](https://user-images.githubusercontent.com/783247/140372393-fbce8451-67b2-4659-a259-371219fea19b.png)

**Comment by m-ou-se** [comment]
(Just need to figure out a way to detect whether the expression was the final one in a block.)

**Comment by estebank** [comment]
That looks good!

**Comment by m-ou-se** [comment]
Re-opening this, because it doesn't work yet for `for` loops:

```
help: try wrapping the expression in `Ok`
  |
4 ~     Ok(for _ in x {
5 |         ...
6 ~     })
  |
```
