### ISSUE TITLE
Support `.insn` directive in `asm!`

### ISSUE THREAD

**Issue by piegamesde** [rust-lang/rust#90558]
Tracking issue: #72016.

The `.insn` assembler directive allows to treat data as instructions. This allows to generate CPU instructions that are otherwise not possible using assembler commands. It is platform specific and mostly relevant for RISC-V platforms, but I could also find uses for it on MIPS targets as well.

More generally speaking, any solution that allows me to produce custom machine code instructions without a performance overhead will be okay for me. The current best workaround is to write the assembler code externally and then link to it. However, this adds the overhead of a function call that cannot be inlined due to the FFI boundary, so this is not acceptable in the long term.

See also https://users.rust-lang.org/t/custom-cpu-instructions-with-asm/66637 for some more discussion of my problem.

**Comment by hkratz** [comment]
This will likely work automatically once LLVM supports it. A commit has recently landed (https://reviews.llvm.org/D108602?id=369214) but is not yet in any released version.

**Comment by piegamesde** [comment]
I tried building rust+cargo from source with https://github.com/llvm/llvm-project/commit/283879793dc787225992496587581ec77b6b0610 cherry-picked. Sadly it did not make the error message go away. However I don't have a good way to check if the correct LLVM is being used (I could however check that rustc and cargo are the ones I want)

**Comment by piegamesde** [comment]
Okay, it actually does work. What is the procedure around Rust's LLVM dependency? How often is it bumped? Is this a candidate for cherry-picking onto rust-llvm?

**Comment by sanxiyn** [comment]
LLVM procedure is at https://rustc-dev-guide.rust-lang.org/backend/updating-llvm.html. I think this is a candidate for cherry-picking but someone needs to do the work.

**Comment by piegamesde** [comment]
https://github.com/rust-lang/llvm-project/pull/121
