### ISSUE TITLE
Confusing display of 1.0.0 stability

### ISSUE THREAD

**Issue by jsha** [rust-lang/rust#90552]
At https://doc.rust-lang.org/nightly/std/vec/struct.Vec.html (same issue on stable), the "1.0.0" stability on the right-hand side is displayed inconsistently. It seems to show up only when there is also `const` stability to display. Example:

![image](https://user-images.githubusercontent.com/220205/140236086-f1b10fb7-33dd-45c1-9f24-09edf9c638ad.png)

`new` shows stability of `1.0.0 (const: 1.39.0)`. `with_capacity` shows no stability information. But both have `#[stable(feature = "rust1", since = "1.0.0")]`:

https://doc.rust-lang.org/nightly/src/alloc/vec/mod.rs.html#424
https://doc.rust-lang.org/nightly/src/alloc/vec/mod.rs.html#469

Note: Hiding 1.0.0 stability for the stdlib may actually be the right thing to do, to reduce noise. But if that's the intent, we should do it consistently - for instance also hiding 1.0.0 in the `<h1>` at the top of the page.

**Comment by xfix** [comment]
In general, Rust documentation doesn't show stability information when it matches stability of a type itself.

**Comment by jsha** [comment]
Ah, that makes sense - though it's hard to discover that property as a user. Maybe the main fix here is to change `1.0.0 (const: 1.39.0)` to just `const: 1.39.0`.
