### ISSUE TITLE
Don't warn on use of a deprecated item in a deprecated item

### ISSUE THREAD

**Issue by cmr** [rust-lang/rust#9057]
For example:

```rust
#[deprecated]
fn foo() { }

#[deprecated]
fn bar() { foo() }
```

Should not be a warning.

**Comment by steveklabnik** [comment]
Triage: this system isn't really considered for external code anymore, so I wonder how important it is. Also, the original code sample does not warn for me today, which seems...odd.

**Comment by steveklabnik** [comment]
Updated code:

```
#![feature(staged_api)]
#![staged_api]

#[deprecated(since = "1.6.0", reason = "")]
#[stable(since = "1.6.0", feature="lol")]
fn foo() { }

#[deprecated(since = "1.6.0", reason = "")]
#[stable(since = "1.6.0", feature="lol")]
fn bar() { foo() }

fn main() {}
```

I agree with my own comment from a year ago, and this hasn't had any non-triage activity for two years, so I'm just going to give a close.
