### ISSUE TITLE
error: couldn't create a temp dir: strings passed to WinAPI cannot contain NULs at path

### ISSUE THREAD

**Issue by BasixKOR** [rust-lang/rust#90570]
### Problem

Every time I try to build some cargo project on Git For Windows environment, it fails with the above error.

```
error: couldn't create a temp dir: strings passed to WinAPI cannot contain NULs at path "%RUSTUP_HOME%\\.cargo\\registry\\src\\github.com-1ecc6299db9ec823\\winapi-0.3.9\\\u{0}\\rustcXAsau8"
```

### Steps

1. Install Git For Windows.
2. Launch Git Bash and `cd` to any project.
3. `cargo build`

### Notes

I confirmed this could be reproduced via installing Git For Windows (more specifically PortableGit).

```
$ uname -a
MINGW64_NT-10.0-22489 Basix-XPS 3.1.7-340.x86_64 2021-10-12 16:29 UTC x86_64 Msys
```

I'm not 100% sure this issue belongs to cargo, but since the folder, it was trying to access was cargo's one, I filed it here.

### Version

```text
cargo 1.56.0 (4ed5d137b 2021-10-04)
release: 1.56.0
commit-hash: 4ed5d137baff5eccf1bae5a7b2ae4b57efad4a7d
commit-date: 2021-10-04
```

**Comment by ChrisDenton** [comment]
I'm not too familiar with git bash but it looks like the temp directory has nulls in the path? Which might point to the environment somehow getting messed up. In git bash, does the `TMP`, `TEMP` or `USERPROFILE` environment variable perhaps contain a null?

**Comment by BasixKOR** [comment]
I just ran a quick shell script to check those values:

```bash
$ for var in $TMP $TEMP $USERPROFILE; do echo $(cygpath -w $var); done
C:\Users\basix\=
C:\Users\basix\AppData\Local\Temp
C:\Users\basix
```

It seems like the $TMP value is broken on MSYS2 environments. I checked `%TMP%` on cmd and it has the same value as `$TEMP` does.

**Comment by BasixKOR** [comment]
This error no longer reproduces on the latest Git For Windows, and I was able to fix the issue with a simple update. I still have absolutely no idea what caused this but since it seems to be fixed I'm closing the issue.
