### ISSUE TITLE
rustdoc cuts off the last line in a `#[doc]` attribute if it only has a single character

### ISSUE THREAD

**Issue by nicholasbishop** [rust-lang/rust#90618]
When using `#[doc = include_str!("...")]` to insert another file as a docstring, it seems that the last line gets cut off if it contains only one character.

`src/inc1`:
```
inc1
ab
```

`src/inc2`:
```
inc2
x
```

(Both `inc` files have a trailing new line.)

`src/lib.rs`:
```rust
#[doc = include_str!("inc1")]  // OK: "inc1 ab"
pub const A: usize = 1;

#[doc = include_str!("inc2")]  // Bad: "inc2"
pub const B: usize = 2;
```

Running `cargo doc --open` on the above produces output like this:

```
A inc1 ab 
B inc2
```

That is, the `inc1` file gets included correctly, but the `inc2` file loses its second line. This bug only seems to happen if the last line is a single character.

### Meta

Reproduced this bug on both stable and nightly.

`rustc --version --verbose`:
```
rustc 1.56.1 (59eed8a2a 2021-11-01)
binary: rustc
commit-hash: 59eed8a2aac0230a8b53e89d4e99d55912ba6b35
commit-date: 2021-11-01
host: x86_64-unknown-linux-gnu
release: 1.56.1
LLVM version: 13.0.0
```
`rustc +nightly --version --verbose`:
```
rustc 1.58.0-nightly (4961b107f 2021-11-04)
binary: rustc
commit-hash: 4961b107f204e15b26961eab0685df6be3ab03c6
commit-date: 2021-11-04
host: x86_64-unknown-linux-gnu
release: 1.58.0-nightly
LLVM version: 13.0.0
```

**Comment by jyn514** [comment]
@nicholasbishop does this also happen for string constants and other things using `include_str!`? Or just the doc attribute?

**Comment by nicholasbishop** [comment]
Oh I didn't think to check that. Looks like the bug doesn't reproduce with a non-`doc` use of `include_str`.

This runs without error:
```rust
fn main() {
    let inc1 = include_str!("inc1");
    let inc2 = include_str!("inc2");

    assert_eq!(inc1, "inc1\nab\n");
    assert_eq!(inc2, "inc2\nx\n");
}
```

**Comment by jyn514** [comment]
Ok cool and follow-up question - does `#[doc = "inc2\nx\n"]` have the same issue? Or only with include_str1?

**Comment by nicholasbishop** [comment]
That does reproduce the issue.

```rust
#[doc = "inc2\nx\n"]
pub const C: usize = 2;
```

The rustdoc output looks like `C inc2`.

**Comment by jyn514** [comment]
cc @GuillaumeGomez, this is probably related to your changes to try and make the indentation smarter.

**Comment by GuillaumeGomez** [comment]
You mean removing the smart indent? ;)

But yes, very likely. I'll take a look.
