### ISSUE TITLE
compiletest should validate `only-` headers

### ISSUE THREAD

**Issue by wesleywiser** [rust-lang/rust#90619]
The failure mode for using an unrecognized header like `only-i686` is that the test never runs which is very easy to miss. compiletest should verify that it recognizes the header value and that some target _could_ run the test. This is basically a more specific version of #83551. 

See #90569 for a case where this would have caught tests that never ran. 

This is where the changes will need to be made:

https://github.com/rust-lang/rust/blob/27143a9094b55a00d5f440b05b0cb4233b300d33/src/tools/compiletest/src/header.rs#L674-L713

**Comment by jieyouxu** [comment]
compiletest does validate `only-*` headers now, e.g.

https://github.com/rust-lang/rust/blob/eeeb021954e30a6b16fc12cc4b8a1bcf7910a40e/src/tools/compiletest/src/header/cfg.rs#L102-L106

Closing this issue as it has been addressed in compiletest.
