### ISSUE TITLE
anonymous constants are overly restrictive wrt variance

### ISSUE THREAD

**Issue by lcnr** [rust-lang/rust#90629]
cc https://github.com/rust-lang/rust/pull/89829#issuecomment-948921310

this currently causes an error as `'a` is considered invariant because it is used in an anonymous constant.
```rust
#![feature(generic_const_exprs)]
struct Foo<'a>([&'a u32; std::mem::size_of::<&'a u32>()]);
fn covariant<'a>(v: &'a Foo<'static>) -> &'a Foo<'a> {
    v //~ERROR mismatched types
}
```
This shouldn't actually be needed for `std::mem::size_of` as it doesn't care about variance.

Once stuff like the following causes an error (instead of a future imcompat lint, cc https://github.com/rust-lang/rust/issues/56105), subtyping should not be able to influence const eval, so we could allow lifetimes used in constants to remain bivariant. It is not clear that we should do that, as this restriction on subtyping is definitely not obvious or even necessarily desirable.
```rust
trait SadBee {
    const ASSOC: usize;
}
// fn(&'static ())` is a supertype of `for<'a> fn(&'a ())` while
// we allow two different impls for these types, leading
// to different const eval results.
impl SadBee for for<'a> fn(&'a ()) {
    const ASSOC: usize = 0;
}
impl SadBee for fn(&'static ()) {
    const ASSOC: usize = 100;
}
```

**Comment by QuineDot** [comment]
[The current plan as I understand it](https://github.com/rust-lang/rust/pull/72493) is for these to continue to be allowed:
```rust
impl SadBee for for<'a> fn(&'a ()) {
    const ASSOC: usize = 0;
}
// This `impl` is more generic than your but still covers fn(`&'static ()`)
// (and any other `fn(&'concrete_lifetime U)`)
impl<T> SadBee for fn(T) {
    const ASSOC: usize = 100;
}
```
But I'm unsure if that's a problem for you or not.

**Comment by lcnr** [comment]
yeah, subtyping also impacts `TypeId`, so we won't be able to just use bivariance once `TypeId::of` is `const`. We can still allow variance by looking into the constant, e.g. for
```rust
struct UsesRef<'a> {
    actual_ref: &'a (),
    in_anon_const: [u8; std::mem::size_of::<&'a ()>()],
}
```
but that requires a bunch of additional design so I will only track that in https://github.com/rust-lang/project-const-generics/issues/32

Thanks for reminding me that this issue exists :sweat_smile:
