### ISSUE TITLE
`repr(C, Int)` enums can be used to read uninitialized data from the stack without `unsafe`

### ISSUE THREAD

**Issue by luavixen** [rust-lang/rust#90624]
I tried this code:
```rust
#[repr(C, u32)]
enum Thing {
    Item(i64)
}

fn main() {
    // reads some random data from the stack
    let uninitialized = Thing::Item as u32;
    // prints a bunch of garbage
    println!("{}", uninitialized);
}
```

I expected to see this happen:
This probably shouldn't compile, but I was expecting this to output the ordinal integer for use with C interop.

Instead, this happened:
Compiled without any errors or warnings on stable, reads from uninitialized stack memory.

Playground screenshot:
![](https://i.imgur.com/4EogSeR.png)
Test here: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=9172f5cb44ea6fcdd0fbbdf8d467d056

`rustc --version --verbose`:
```
rustc 1.56.0
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-linux-gnu
release: 1.56.0
LLVM version: 12.0.1
```
Note that I've tested this locally and on the playground, as well as had friends using other systems test it.

**Comment by cuviper** [comment]
`Thing::Item` is not an enum value, it's a tuple constructor -- `fn(i64) -> Thing {Thing::Item}`.

**Comment by luavixen** [comment]
I shouldn't be allowed to cast `fn(i64) -> Thing` to `u32`. Additionally, the resulting value change between runs seemingly at random, so ?? I have no idea what's happening here.
```
$ ./target/debug/repr-c-int-uninitialized
1495972336
$ ./target/debug/repr-c-int-uninitialized
2370513392
$ ./target/debug/repr-c-int-uninitialized
3888675312
```

**Comment by cuviper** [comment]
> I shouldn't be allowed to cast `fn(i64) -> Thing` to `u32`.

This is explicitly allowed: https://doc.rust-lang.org/reference/expressions/operator-expr.html#type-cast-expressions

> Additionally, the resulting value change between runs seemingly at random

That's ASLR ([address space layout randomization](https://en.wikipedia.org/wiki/Address_space_layout_randomization)) in action -- executables are loaded at unpredictable addresses.

**Comment by cuviper** [comment]
> but maybe this should be a diagnostic?

There is at least a clippy lint for this:

```
warning: casting function pointer `Thing::Item` to `u32`, which truncates the value
 --> src/main.rs:8:25
  |
8 |     let uninitialized = Thing::Item as u32;
  |                         ^^^^^^^^^^^^^^^^^^ help: try: `Thing::Item as usize`
  |
  = note: `#[warn(clippy::fn_to_numeric_cast_with_truncation)]` on by default
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#fn_to_numeric_cast_with_truncation
```

**Comment by luavixen** [comment]
Thank you for clarifying! That makes more sense, but is still a little confusing, especially if you're expecting behavior to be similar when changing:
```rust
#[repr(C, u32)]
enum Thing {
  Item
}
```
Into:
```rust
#[repr(C, u32)]
enum Thing {
  Item(i64)
}
```
Where casting to `u32` for the original code would yield the ordinal, but after adding the field to `Thing::Item` it turns into a function pointer.

At any rate, a new issue should probably be created for these problems, so I'm closing this.
