### ISSUE TITLE
rustdoc: Style Improvements?

### ISSUE THREAD

**Issue by exzachlyvv** [rust-lang/rust#90632]
As a newcomer to Rust, the docs.rs content is 💯  but the UI is lacking in my opinion. Let's make the documentation easier to digest! :D 

Here are a few of the improvements I'm thinking of:
1. Font improvement? The current font reminds me of Time New Roman, which is quite dated. 2 of my favorites are [Nunito](https://fonts.google.com/specimen/Nunito) and [Montserrat](https://fonts.google.com/specimen/Montserrat).
2. Improved line and letter spacing for readability.
3. Improvements around inline code markdown UI.
4. Plenty more we could do :p
4. I came over from Laravel. [Their documentation is gorgeous](https://laravel.com/docs/8.x). I see no reason that docs.rs can't match that.

I would be happy to submit a PR for this. Just want to check on the current state before doing so :)

**Comment by jyn514** [comment]
cc @jsha

**Comment by willcrichton** [comment]
My 2c -- I think UI improvements to Rustdoc should be rooted in *ease of use*, not *quality of aesthetic*. I agree that the Laravel docs look quite nice, but I personally find their font harder to read than Source Serif Pro. 

IMO, documentation should fundamentally be utilitarian, not beautiful. Which isn't to say there aren't changes that both make the documentation easier to use AND prettier to look at. But the grounding question should always be things like, does this change reduce the amount of time it takes for user X to solve problem Y?

**Comment by willcrichton** [comment]
Also fwiw, the Laravel *automatically-generated* documentation (which is the main rustdoc use case, as opposed to [mdbook](https://github.com/rust-lang/mdBook)-style guides) looks very different.

<img width="1792" alt="Screen Shot 2021-11-08 at 11 57 41 AM" src="https://user-images.githubusercontent.com/663326/140785130-2c0d76ef-b60e-432d-923d-e8cd5f851830.png">

**Comment by jsha** [comment]
Hi @exzachlyvv ! Welcome to Rust, and welcome to rustdoc. [You may be interested in this issue](https://github.com/rust-lang/rust/issues/59829), which recommends some style changes based on accessibility. In particular I notice that both of the fonts you recommend are sans-serif fonts, and the issue I linked (#59829) also recommends sans-serif:

> Beside the visual clutter, there are a few other aspects of the default Rust docs styles which can cause problems for people with dyslexia:
> It uses serif fonts for the body text, while sans serif fonts are generally preferred for readability

I think that's a pretty strong reason! It would be useful to find some citations for it, though. Is that something you're interested in doing?

Also, if we decide to move to a sans-serif font for most documentation text, one option is Fira Sans, which we already use for headings. I'm not well equipped to evaluate Fira Sans vs Nunito or Montserrat, but if you could provide some description of why the latter two might be more readable, that would be awesome.

**Comment by exzachlyvv** [comment]
[That issue](https://github.com/rust-lang/rust/issues/59829) does a much better job of describing my feelings :D I'll follow that.

Thanks for the responses!! I'm loving Rust 😎
