### ISSUE TITLE
create_vtable_metadata should mark the generated vtable variable as artificial

### ISSUE THREAD

**Issue by khuey** [rust-lang/rust#90653]
I don't see any way to get LLVM to take DIFlags::FlagArtificial for a global variable though, so I think this needs LLVM changes.

**Comment by jyn514** [comment]
@khuey can you add some context for this issue? I don't see any function named `create_vtable_metadata` in `compiler/`. Is this referring to some specific code that's been renamed?

**Comment by khuey** [comment]
It got renamed to `create_vtable_di_node`.

**Comment by jyn514** [comment]
Ah ok, this is about debuginfo. I think we are passing FlagArtificial now? https://github.com/rust-lang/rust/blob/dd2b19539ea4d62a150cf13d45942e58b6b44e54/compiler/rustc_codegen_llvm/src/debuginfo/metadata.rs#L1332

**Comment by khuey** [comment]
The vtable *type* is being marked artificial. This is about the vtable *variable*.

**Comment by workingjubilee** [comment]
This was duplicated by #125126 but that wound up having a bit more information, so! Closing.
