### ISSUE TITLE
if never use T in struct fn will report error~

### ISSUE THREAD

**Issue by HelloReboot** [rust-lang/rust#90651]
### Code

```Rust
use std::fmt::{Display};

fn main() {
    let kaiser = User {
        name: "kaiser",
        hobby: 1,
    };
    kaiser.show();
    User::get("hello".to_string());
}

struct User<'a, T> where T: Display {
    name: &'a str,
    hobby: T,
}

impl<'a, T> User<'a, T>
    where T: Display {
    fn get(name: String) {
        println!("{}", name);
    }
    fn show(&self) {
        println!("{}--{}", self.name, self.hobby, );
    }
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.56.1 (59eed8a2a 2021-11-01)
binary: rustc
commit-hash: 59eed8a2aac0230a8b53e89d4e99d55912ba6b35
commit-date: 2021-11-01
host: x86_64-apple-darwin
release: 1.56.1
LLVM version: 13.0.0

```

### Error output

```
error[E0282]: type annotations needed
 --> src/main.rs:9:5
  |
9 |     User::get("hello".to_string());
  |     ^^^^^^^^^ cannot infer type for type parameter `T`
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by SkiFire13** [comment]
Looks correct to me, when you call `User::get` the compiler can't know whether it has to use the implementation for `User<i32>`, `User<String>`, ecc ecc, so it gives you an error. You need to write `User::<TypeHere>::get("hello".to_string());` to specify the implementation you want to use.

**Comment by HelloReboot** [comment]
Thank you Mr GIacomo you are right ...fixed!


There is no such information on the document or I have not read it。


Giacomo Stevanato ***@***.***> 於 2021年11月7日週日 上午1:15寫道：
