### ISSUE TITLE
Consider removing `rustc_incremental::persist::fs::dep_graph_path_from`

### ISSUE THREAD

**Issue by pierwill** [rust-lang/rust#90658]
This function is only used once, with the current session's directory. Is there a reason to keep it, or should it be replaced by `dep_graph_path`?

_Originally posted by @cjgillot in https://github.com/rust-lang/rust/pull/90407#discussion_r744151782_

**Comment by michaelwoerister** [comment]
@pierwill, feel free to make a PR and r? me on it.
