### ISSUE TITLE
Regression in 1.56.0 - Trait bound not satisfied error even though the impl exists

### ISSUE THREAD

**Issue by AzureMarker** [rust-lang/rust#90662]
### Code

I tried this code (minimized from [this test] in my library):

[this test]: https://github.com/AzureMarker/shaku/blob/a42af9dbf4b3b40ede4ad856e0156c7ab6c196a1/shaku/tests/repository_service_provider.rs

```rust
trait HasProvider<T: ?Sized> {}
trait Provider<M> {
    type Interface: ?Sized;
}

trait Repository {}
trait Service {}

struct DbConnection;
impl<M> Provider<M> for DbConnection {
    type Interface = DbConnection;
}

struct RepositoryImpl;
impl<M: HasProvider<DbConnection>> Provider<M> for RepositoryImpl {
    type Interface = dyn Repository;
}

struct ServiceImpl;
impl<M: HasProvider<dyn Repository>> Provider<M> for ServiceImpl {
    type Interface = dyn Service;
}

struct TestModule;
impl HasProvider<<DbConnection as Provider<Self>>::Interface> for TestModule {}
impl HasProvider<<RepositoryImpl as Provider<Self>>::Interface> for TestModule {}
impl HasProvider<<ServiceImpl as Provider<Self>>::Interface> for TestModule {}

fn main() {}
```

I expected to see this happen: Compile without errors.

Instead, this happened: Compiled with errors:
```
error[E0277]: the trait bound `TestModule: HasProvider<(dyn Repository + 'static)>` is not satisfied
  --> shaku/tests/debug_rust_1_56.rs:26:6
   |
26 | impl HasProvider<<RepositoryImpl as Provider<Self>>::Interface> for TestModule {}
   |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `HasProvider<(dyn Repository + 'static)>` is not implemented for `TestModule`
   |
   = help: the following implementations were found:
             <TestModule as HasProvider<(dyn Repository + 'static)>>
             <TestModule as HasProvider<<ServiceImpl as Provider<TestModule>>::Interface>>
             <TestModule as HasProvider<DbConnection>>
note: required by a bound in `HasProvider`
  --> shaku/tests/debug_rust_1_56.rs:1:1
   |
1  | trait HasProvider<T: ?Sized> {}
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `HasProvider`

error[E0277]: the trait bound `TestModule: HasProvider<(dyn Repository + 'static)>` is not satisfied
  --> shaku/tests/debug_rust_1_56.rs:27:6
   |
27 | impl HasProvider<<ServiceImpl as Provider<Self>>::Interface> for TestModule {}
   |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `HasProvider<(dyn Repository + 'static)>` is not implemented for `TestModule`
   |
   = help: the following implementations were found:
             <TestModule as HasProvider<(dyn Repository + 'static)>>
             <TestModule as HasProvider<<ServiceImpl as Provider<TestModule>>::Interface>>
             <TestModule as HasProvider<DbConnection>>
note: required because of the requirements on the impl of `Provider<TestModule>` for `ServiceImpl`
  --> shaku/tests/debug_rust_1_56.rs:20:38
   |
20 | impl<M: HasProvider<dyn Repository>> Provider<M> for ServiceImpl {
   |                                      ^^^^^^^^^^^     ^^^^^^^^^^^

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0277`.
```

Note that it says `HasProvider<(dyn Repository + 'static)>` is not implemented for `TestModule`, but then lists it as an existing implementation.

### Version it worked on

It most recently worked on: 1.55.0

### Version with regression

`rustc --version --verbose`:
```
rustc 1.56.0 (09c42c458 2021-10-18)
binary: rustc
commit-hash: 09c42c45858d5f3aedfa670698275303a3d19afa
commit-date: 2021-10-18
host: x86_64-unknown-linux-gnu
release: 1.56.0
LLVM version: 13.0.0
```

**Comment by camelid** [comment]
Bisects to #85868. cc @Aaron1011 @jackh726 

---

searched nightlies: from nightly-2021-07-01 to nightly-2021-10-01
regressed nightly: nightly-2021-09-03
searched commits: from https://github.com/rust-lang/rust/commit/50171c310cd15e1b2d3723766ce64e2e4d6696fc to https://github.com/rust-lang/rust/commit/371f3cd3fe523d0b398ed1db1620667c53ba7d02
regressed commit: https://github.com/rust-lang/rust/commit/371f3cd3fe523d0b398ed1db1620667c53ba7d02

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.0</summary>


Host triple: x86_64-apple-darwin
Reproduce with:
```bash
cargo bisect-rustc --preserve --regress=error --start=2021-07-01 --end=2021-10-01 -- check 
```
</details>

**Comment by apiraino** [comment]
Assigning priority as discussed in the [Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2390662.20Regression.20in.201.2E56.2E0.20-.20Trait.20bound.20not.20satisfied.20err.E2.80.A6) of the Prioritization Working Group.

@rustbot label -I-prioritize +P-high

**Comment by elertan** [comment]
Any advancements on this issue? I currently can't upgrade to Rust 1.56 due to this exact problem

**Comment by AzureMarker** [comment]
I might try my hand at diagnosing it, but someone with more context would definitely be faster at it.

**Comment by Aaron1011** [comment]
Sorry for the delay in getting to this. I've opened https://github.com/rust-lang/rust/pull/91183 with a fix.

**Comment by AzureMarker** [comment]
I noticed that this regression was found in the 1.56 beta crater run:
https://crater-reports.s3.amazonaws.com/beta-1.56-3/index.html

Was it just overlooked at that time?

**Comment by DanielJoyce** [comment]
Seems kinda major to 

> I noticed that this regression was found in the 1.56 beta crater run: https://crater-reports.s3.amazonaws.com/beta-1.56-3/index.html
> 
> Was it just overlooked at that time?

Yeah, this seems rather significant. It's right there in the results.

https://crater-reports.s3.amazonaws.com/beta-1.56-3/beta-2021-10-15/reg/shaku-0.6.1/log.txt
