### ISSUE TITLE
Error message for `cmake` could meet bar set by that for `ninja`

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#90679]
I tried to build on a new machine. Got this message:

```
thread 'main' panicked at '

couldn't find required command: "cmake"

'
```

Which I'm used to.

I googled a bit, installed `cmake`, figured out how to get PATH set up, et cetera.

Then I built again. And got this:

```
Couldn't find required command: ninja (or ninja-build)

You should install ninja as described at
<https://github.com/ninja-build/ninja/wiki/Pre-built-Ninja-packages>,
or set `ninja = false` in the `[llvm]` section of `config.toml`.
Alternatively, set `download-ci-llvm = true` in that `[llvm]` section
to download LLVM rather than building it.
```

I'm not sure, but: Isn't `cmake` solely necessary in our build for building LLVM? if that's the case, then shouldn't both the `cmake` failure and the `ninja` failure be providing the same level of feedback (namely, suggesting that one side-step building LLVM altogether as an alternative option to downloading and installing `cmake`)?

(Or is the assumption here that `cmake` *will* be used by so many crates, people should just bite bullet and install it? Even so, we could give better guidance up front about where to look for it.)

**Comment by jyn514** [comment]
@pnkfelix I don't think cmake intentionally has a worse error, it's just that a bunch of people building from source for the first time have been confused what ninja is and where to get it. If you made a PR improving the error for cmake I'd approve it :)

**Comment by thatzopoulos** [comment]
Hello @InfRandomness, I'd like to claim this issue if you're interested in releasing it.

**Comment by InfRandomness** [comment]
Sorry about that 😀 
Gave it a try but got sidetracked and wasn't really interested in doing it anymore
