### ISSUE TITLE
Hide console window when running a command

### ISSUE THREAD

**Issue by Archieeeeee** [rust-lang/rust#90674]
Hello,
Running a command on Windows with flag CREATE_NO_WINDOW still sees an console window flashing in and out, how to hide it

https://docs.microsoft.com/en-us/windows/win32/procthread/process-creation-flags

to reproduce, doudle click main.exe but not cargo run

```
fn main() {
  Command::new("explorer.exe").creation_flags(0x08000000).spawn();
}
```

**Comment by hkratz** [comment]
Using [`creation_flags()`](https://doc.rust-lang.org/std/os/windows/process/trait.CommandExt.html#tymethod.creation_flags) you only modify how the subcommand (here: explorer.exe) is run.

You need to hide the console windows that is allocated for the Rust application by putting this at the top of your main.rs:
```
#![windows_subsystem = "windows"]
```

**Comment by Archieeeeee** [comment]
> Using [`creation_flags()`](https://doc.rust-lang.org/std/os/windows/process/trait.CommandExt.html#tymethod.creation_flags) you only modify how the subcommand (here: explorer.exe) is run.
> 
> You need to hide the console windows that is allocated for the Rust application by putting this at the top of your main.rs:
> 
> ```
> #![windows_subsystem = "windows"]
> ```

thank you
