### ISSUE TITLE
Add a way to give backtraces for logging

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#90698]
I ran into the following problem today: I had a prebuilt (with `download-rustc`) compiler and wanted to get a backtrace for some `info!` logging it was outputting, to see how it got to that point. But there's no way to get a backtrace there without rebuilding the compiler from source. It would be really cool if there were a way to have backtraces for each individual logging call. To avoid making the compiler horrifically slow, it could be behind a `-Zlog-backtrace=filter` flag.

This would be useful even if you have a local build of the compiler, since you don't have to rebuild it each time you want to get a stack trace.

@davidbarsky suggests doing this by adding a custom [`Layer`](https://docs.rs/tracing-subscriber/0.3.1/tracing_subscriber/fmt/struct.Layer.html) which filters [based on a string](https://docs.rs/tracing-subscriber/0.3.1/tracing_subscriber/filter/targets/struct.Targets.html#method.with_target). Debugging options are handled around https://github.com/rust-lang/rust/blob/eee8b9c7bafade55981d155dae71657f1cc55a22/compiler/rustc_session/src/options.rs#L1030

**Comment by AkechiShiro** [comment]
Hi @wihobbs, I'm interested in working on this issue, are you still working on it ? If not could I take it from now and try to actually solve it someway or another ?

**Comment by wihobbs** [comment]
Hi @AkechiShiro, yes, I'm still working on it. Been bogged down with a few other things lately but if you'd like I'm happy to collaborate!

**Comment by AkechiShiro** [comment]
Hi @wihobbs, sure I'm fine in collaborating for this issue, is there any way to know what is WIP at the moment? And how I could get started on this issue ? What do you suggest I look at first or play around with ?

Did you understand how you could use the Layer object mentioned in the first message?

**Comment by yukiomoto** [comment]
Hi @jyn514 

>But there's no way to get a backtrace there without rebuilding the compiler from source.

I understand that this issue is about getting backtraces for logging **without** rebuilding the compiler but may I ask if you mean there is already a way to get a backtrace for each `info!` loggings ? This might not be directly related but I'm just curious.

I'm sorry if this is a newbie question..!

**Comment by jyn514** [comment]
>  I ask if you mean there is already a way to get a backtrace for each info! loggings ? This might not be directly related but I'm just curious.

Yes, you can turn the `info` log you're interested in into a `panic` :P but obviously that requires rebuilding and it will break half the test suite to boot.

**Comment by yukiomoto** [comment]
@jyn514 
I now understand what you mean. Thank you!
