### ISSUE TITLE
Ensure up-to-date copyright years

### ISSUE THREAD

**Issue by lkuper** [rust-lang/rust#9070]
People don't consistently update the year in the copyright block when they edit a file.  Could we either (a) just globally update them all to the latest year when the year changes (as suggested by @thestinger on IRC), or (b) if we really have to have per-file copyright granularity, have tidy check that the copyright year matches the last-modified date of the file?

**Comment by frewsxcv** [comment]
/cc @gerv since he was consulted in #21481

IANAL, but realistically I wouldn't think there's much of a difference if the year in the header is off by a couple years.

**Comment by gerv** [comment]
The policy I recommend is:

* Don't bother to update them
* If someone does update them in a patch, ignore it (i.e. accept the patch without comment)

The actual copyright status of the file is unaffected by what it says at the top, so people for whom it's actually important when the copyright expires (i.e. no-one) will have to do more research in any case.

**Comment by frewsxcv** [comment]
@gerv Sounds very sane in my opinion. Given that response, this can be closed?

**Comment by lkuper** [comment]
Yeah, since filing this bug over a year ago I came to realize (from working on another project) that the dates in the files really don't matter.  I also think it can be closed.

**Comment by alexcrichton** [comment]
Ok, thanks for the info @gerv!
