### ISSUE TITLE
.lines() auto insert \n on first empty string if the string start with \n

### ISSUE THREAD

**Issue by haoadoresorange** [rust-lang/rust#90725]
I tried this code:

```rust
"\nhello\n\nworld".to_string().lines()
        .enumerate()
        .map(|(i, s)| {
                if i == 0 {
                    println!("{:?}", s);
                };
        })
```

I expected to see this happen: print ""
```rust
"hello\n\nworld".to_string().lines()
        .enumerate()
        .map(|(i, s)| {
                if i == 0 {
                    println!("{:?}", s);
                };
        })
```
print "hello"

Instead, this happened: print "\n"

### Meta

`rustc --version --verbose`:
```
rustc 1.56.1 (59eed8a2a 2021-11-01)
binary: rustc
commit-hash: 59eed8a2aac0230a8b53e89d4e99d55912ba6b35
commit-date: 2021-11-01
host: x86_64-unknown-linux-gnu
release: 1.56.1
LLVM version: 13.0.0
```

**Comment by hkratz** [comment]
I can't reproduce this issue with your sample code. I minimally modified it to consume the Iterator returned by `map()` as otherwise nothing is printed at all:
```rust
 fn main() {
    "\nhello\n\nworld"
        .to_string()
        .lines()
        .enumerate()
        .map(|(i, s)| {
            if i == 0 {
                println!("{:?}", s);
            };
        })
        .for_each(drop);
}
```
This prints `""` for me: [Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=7a7479ea2efb583cad54172bf121d73f)

**Comment by haoadoresorange** [comment]
I'm sorry this seems like a mistake from my part, I mistype 1 character which make it use another variable instead. Again sorry for this !
