### ISSUE TITLE
[ER] NonZeroUX::pow()

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust#90744]
Currently rustc (1.58.0-nightly 2021-11-08) compiles this with a division by zero test:

```rust
fn foo1(x: u64, y: u32) -> u64 {
    x / 6_u64.pow(y)
}
```

When the base isn't zero and there isn't an overflow base^exp shoudn't be zero. I think currently this can't be solved adding an assume() before the return inside the pow() function because base could be zero.

To solve this problem I suggest to add the pow() method to NonZeroUX values:

```rust
fn foo2(x: u64, y: u32) -> u64 {
    x / NonZeroU64::new(6).unwrap().pow(y)
}
```

A pow() for NonZeroUX could be something like:

```rust
#![feature(const_option)]
use std::num::NonZeroU64;

const fn pow(x: NonZeroU64, mut n: u32) -> NonZeroU64 {
    let mut x = x.get();
    if n == 0 {
        return NonZeroU64::new(1).unwrap();
    }

    let mut y = 1;
    while n > 1 {
        if n & 1 != 0 {
            y *= x;
            n -= 1;
        }
        x *= x;
        n >>= 1;
    }
    unsafe { NonZeroU64::new_unchecked(y * x) }
}
```

(LLVM is able to totally elide at compile-time the unwrap from NonZeroU64::new(1).unwrap() and NonZeroU64::new(6).unwrap()).

**Comment by est31** [comment]
Note that `6_u64.pow(y)` evals to 0 for sufficiently large `y`, like `100_000`, due to overflow (on builds with debug assertions turned off).

**Comment by leonardo-m** [comment]
> (on builds with debug assertions turned off).

If you read above, I was aware of that. But is Rust stdlib required to never return a zero NonZero even in presence of integer overflows? You may see this as a silly question, but in my code above I've assumed that the answer is negative.

**Comment by asquared31415** [comment]
a `NonZeroX` type must never have a zero value.  Rust defines the zero value to be an invalid value for these types and producing one is undefined behavior.

As documented in [the reference](https://doc.rust-lang.org/reference/behavior-considered-undefined.html)
> Invalid values for a type with a custom definition of invalid values. In the standard library, this affects NonNull<T> and NonZero*.

**Comment by asquared31415** [comment]
Note that there's already a `checked_pow` that checks that overflow does not happen and produces a `Option<NonZeroX>` and is under the `nonzero_ops` feature.

**Comment by leonardo-m** [comment]
Thank you, closed.
