### ISSUE TITLE
Post-drop elaboration const-checking fails on ZSTs

### ISSUE THREAD

**Issue by ecstatic-morse** [rust-lang/rust#90770]
Found by @nbdd0121 [here](https://github.com/rust-lang/rust/issues/73255#issuecomment-964832698), the following code compiles when it shouldn't:

```rust
#![feature(const_precise_live_drops)]

struct S;

impl Drop for S {
    fn drop(&mut self) {
        println!("Hello!");
    }
}

const fn foo() {
    let s = S;
}

fn main() {}
```

The final "post-borrowck cleanup" pass is the Deaggregator, which replaces the assignment _1 = S; with a nop because S has no fields. That means `_1` never gets initialized in the MIR before its `Drop` terminator, so the qualification logic doesn't assign it `NeedsDrop`.

**Comment by ecstatic-morse** [comment]
`Deaggregator` was moved into post-borrowck cleanup from optimizations in #73656, cc @oli-obk @wesleywiser. I think we need to come up with a more robust system for splitting "MIR for analysis" and "MIR for optimization", the current system places an extremely high burden on contributors and reviewers. A simple reordering of passes can have unforeseen consequences.

**Comment by RalfJung** [comment]
We should also document more clearly what our analyses need from MIR, so that one can determine if a change in "MIR for analysis" can break our analyses or not.
