### ISSUE TITLE
Hidden traits missing implementors when documented via `--document-hidden-items`

### ISSUE THREAD

**Issue by steffahn** [rust-lang/rust#90781]
You can see `--document-private-items --document-hidden-items` docs of the standard library here:

https://stdrs.dev/nightly/x86_64-unknown-linux-gnu/std/iter/trait.InPlaceIterable.html

as you can see, the implementors are missing though (which is incredibly annoying if you ever want to work on those traits). Also reproducible locally by building `RUSTDOCFLAGS='--document-private-items --document-hidden-items -A rustdoc::broken-intra-doc-links' ./x.py doc library/std --open`

@rustbot label T-rustdoc

**Comment by jyn514** [comment]
@steffahn can you reproduce this on anything smaller than the standard library?

**Comment by steffahn** [comment]
I haven't tried it on anything other yet. I could test it tomorrow, when I'm back at a computer.

**Comment by hellow554** [comment]
I did the full circle and wrote this:

```rust
pub trait T {}

pub struct VisPub;
struct VisPriv;
#[doc(hidden)]
pub struct HidPub;
#[doc(hidden)]
struct HidPriv;

impl T for VisPub {}
impl T for VisPriv {}
impl T for HidPub {}
impl T for HidPriv {}
```

Output is this:

![grafik](https://user-images.githubusercontent.com/921462/141255316-6e2f77f3-fc9f-4f5d-adc1-052420848363.png)


so hidden items won't get displayed as Implementors.

@rustbot modify labels: -E-needs-mcve

**Comment by steffahn** [comment]
@hellow554 it's actually the _trait_ that's hidden in the standard library, not the structs. Though your case not displaying the implementation is problematic, too.

**Comment by hellow554** [comment]
I see :) thanks for pointing it out:

<details>
<summary>Rust code</summary>

```rust
pub trait TPubVis {}
#[doc(hidden)]
pub trait TPubHidden {}
trait TPrivVis {}
#[doc(hidden)]
trait TPrivHidden {}

pub struct VisPub;
struct VisPriv;
#[doc(hidden)]
pub struct HidPub;
#[doc(hidden)]
struct HidPriv;

macro_rules! implement {
    ($trait:ident - $($struct:ident)+) => {
        $(
            impl $trait for $struct {}
        )+
    }
}


implement!(TPubVis - VisPub VisPriv HidPub HidPriv);
implement!(TPubHidden - VisPub VisPriv HidPub HidPriv);
implement!(TPrivVis - VisPub VisPriv HidPub HidPriv);
implement!(TPrivHidden - VisPub VisPriv HidPub HidPriv);
```
</details>

![grafik](https://user-images.githubusercontent.com/921462/141262856-ddd9494d-efa4-4b74-9300-1a549f08118f.png)

No implementors for a `#[doc(hidden)]` trait

![grafik](https://user-images.githubusercontent.com/921462/141262887-961eb2e2-515b-42c1-8e50-38993fc81490.png)

Only implementors that are not `#[doc(hidden)]`

**Comment by lolbinarycat** [comment]
triage: this issue has been fixed, adding a regression test for it
