### ISSUE TITLE
Not compiling after adding the GAT `Self: 'a` bounds

### ISSUE THREAD

**Issue by vandenheuvel** [rust-lang/rust#90808]
After https://github.com/rust-lang/rust/pull/89970 was merged, project [relp](https://github.com/vandenheuvel/relp) no longer compiled as expected: I needed to add a few [`Self: 'a` bounds](https://github.com/rust-lang/rust/issues/87479).

After [I did just that](https://github.com/vandenheuvel/relp/commit/aa471b3272cb53f8f497217585f89599cc9343c3), I was left with the following error:
```
error[E0477]: the type `RemoveRows<'_, MP>` does not fulfill the required lifetime
  --> src/algorithm/two_phase/mod.rs:57:21
   |
57 |                     phase_two::primal::<_, _, SteepestDescentAlongObjective<_>>(&mut non_artificial)
   |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

For more information about this error, try `rustc --explain E0477`.
```
After I made [the following change](https://github.com/vandenheuvel/relp/commit/525e6161c989d173cc54a03a7b19625800ccea66):
```rust
-pub fn primal<IM, MP, PR>(
-    tableau: &mut Tableau<IM, NonArtificial<MP>>,
+pub fn primal<'provider, IM, MP, PR>(
+    tableau: &mut Tableau<IM, NonArtificial<'provider, MP>>,
 ) -> OptimizationResult<IM::F>
 where
-    IM: InverseMaintener<F: im_ops::FieldHR + im_ops::Column<<MP::Column as Column>::F>>,
-    for<'r> IM::F: im_ops::Cost<MP::Cost<'r>>,
+    IM: InverseMaintener<F:
+        im_ops::FieldHR +
+        im_ops::Column<<MP::Column as Column>::F> +
+        im_ops::Cost<MP::Cost<'provider>> +
+    >,
```
`cargo build` succeeded.

The core of this bug report is the question why the extra change above could have been necessary, as #89970 should not have influenced that.

Summarized from a private conversation with @jackh726.

**Comment by jackh726** [comment]
@rustbot ping cleanup

It would be really nice to get a minimal test for this. The intent for this lint was that *in theory*, existing code shouldn't break. So, either we need to update the outlives lint code to not error here or decide that this pattern isn't *correct* and we should figure out the correct fix and make sure it's documented.

**Comment by jackh726** [comment]
For clarification, the most ideal MCVE would be of the code at [this commit](https://github.com/vandenheuvel/relp/commit/aa471b3272cb53f8f497217585f89599cc9343c3#diff-9fb027b29080a62cd7c2f21bc07030125770806b60054cee0b02c34b62bb3b04).

**Comment by vandenheuvel** [comment]
The following issue might be related:
```rust
#![feature(generic_associated_types)]

trait MyTrait {
    type AT<'a> where Self: 'a;
    
    fn selfreffing<'a>(&'a self) -> Self::AT<'a> { unimplemented!(); }
}

struct Inner;
impl MyTrait for Inner {
    type AT<'b> where Self: 'b = ();
}

struct Outer<'a, T>(&'a T);
impl<'a, T: MyTrait> MyTrait for Outer<'a, T> {
    type AT<'b> = T::AT<'b>;
    // type AT<'b> where T: 'b = T::AT<'b>; // suggested
    // type AT<'b> where Self: 'b = T::AT<'b>; // should be
}
```

**Comment by vandenheuvel** [comment]
I am almost certain that this bug has to do with [this line](https://github.com/vandenheuvel/relp/commit/aa471b3272cb53f8f497217585f89599cc9343c3#diff-7b9052b981252b832c4734ad787258a32ce077eba9600f4488cbcdd43f64735fR229):
```rust
-    type Cost<'a> = MP::Cost<'a>;
+    type Cost<'a> where Self: 'a = MP::Cost<'a>;
```

On [this branch](https://github.com/vandenheuvel/relp/commits/reproduce_gat_issue), I applied the commits of [this branch]() (where the original issue occured) in a different order. After starting with the commit above, I remove a few ugly HRTB's in an intermediate commit. After that, [adding the `Self: 'a` clauses](https://github.com/vandenheuvel/relp/commit/7ef3990d672bd8cb4017f37f146d7da092c6705c) works as expected.

**Comment by jackh726** [comment]
@vandenheuvel were you able to fix your project and also include the required bounds?

**Comment by jackh726** [comment]
GATs issue triage: not blocking. It's really not clear what an actionable path forward here is. It would be nice to know what exactly led to these problems, but I can't see anything that changes the outlives lint rules. We also have the flexibility in the future to make the outlives lint more lenient.

**Comment by jackh726** [comment]
I'm going to go ahead and close this. As said in previous comment, not sure what is actionable here.
