### ISSUE TITLE
spawning `std::process::Command` on arm and riscv for a non-existant binary fails to fail

### ISSUE THREAD

**Issue by nivkner** [rust-lang/rust#90825]
**I tried this code**:

```rust
use std::process::Command;

fn main() {
    match Command::new("/no-binary-by-this-name-should-exist").output() {
        Err(e) => assert_eq!(e.kind(), std::io::ErrorKind::NotFound),
        Ok(output) => unreachable!("{:?}", output),
    }
}
```

**I expected to see this happen**:
the program finishes without any errors.

**Instead, this happened**:
a panic is triggered with the message `thread 'main' panicked at 'internal error: entered unreachable code: Output { status: ExitStatus(unix_wait_status(32512)), stdout: "", stderr: "" }', src/main.rs:6:23`

### Meta

`rustc --version --verbose`:
```
rustc 1.58.0-nightly (936238a92 2021-11-11)
binary: rustc
commit-hash: 936238a92b2f9d6e7afe7dda69b4afd903f96399
commit-date: 2021-11-11
host: x86_64-unknown-linux-gnu
release: 1.58.0-nightly
LLVM version: 13.0.0
```

operating system: `arch linux`
kernel version: `5.14.16-arch1-1`

the following steps was used to reproduce the bug (for simplicity the reproduction steps were given for armv5te specifically,
similar steps can be taken for riscv):

* `sudo pacman -S debootstrap`.
* `sudo debootstrap sid debian/ http://deb.debian.org/debian`
* `sudo systemd-nspawn -D debian`
* *setup and login to user account*
* `sudo apt install qemu-user gcc-arm-linux-gnueabi`
* `curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`
* `rustup target add armv5te-unknown-linux-gnueabi`
* `rustc src/main.rs --target=armv5te-unknown-linux-gnueabi -Clinker=arm-linux-gnueabi-gcc`
* `qemu-arm -L /usr/arm-linux-gnueabi main`

<details><summary>backtrace</summary>
<p>

```
stack backtrace:
   0: rust_begin_unwind
             at /rustc/936238a92b2f9d6e7afe7dda69b4afd903f96399/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at /rustc/936238a92b2f9d6e7afe7dda69b4afd903f96399/library/core/src/panicking.rs:106:14
   2: main::main
   3: core::ops::function::FnOnce::call_once
```

</p>
</details>

**Comment by hkratz** [comment]
This is not reproducible on real arm hardware (Oracle Ampere VM directly running an armv7 binary).

**Comment by Urgau** [comment]
Just for the record, I have been trying to reproduce the issue on x86_64 with qemu, on a container like the issue suggest and on bare metal (armv7 but still) but I have been unsuccessful.

**Comment by nivkner** [comment]
created a [repository](https://github.com/nivkner/issue-90825) where the issue is reproduced in the CI

**Comment by cuviper** [comment]
I believe this is a qemu issue. You can even reproduce it with `qemu-x86_64` vs. running native.

The main thing I notice is that `vfork` (or `CLONE_VFORK` as used by `posix_spawn`) is not actually pausing the original process the way it is supposed to. If you run `qemu-arm -strace ...` you'll see:

```
4289 mmap(NULL,36864,PROT_READ|PROT_WRITE,MAP_PRIVATE|MAP_ANONYMOUS|0x20000,-1,0) = 0x0000004000bd1000
4289 rt_sigprocmask(SIG_BLOCK,0x0000004000a8e3e0,0x000000400085bca0) = 0
4289 clone(CLONE_VM|CLONE_VFORK|0x11,child_stack=0x0000004000bd9ff0,parent_tidptr=0x0000004000acb780,tls=0x0000000000000000,child_tidptr=0x0000004000ad1500) = 4291
4289 munmap(0x0000004000bd1000,36864) = 0
4289 rt_sigprocmask(SIG_SETMASK,0x000000400085bca0,NULL) = 0
 = 0
4291 rt_sigprocmask(SIG_BLOCK,NULL,0x0000004000bd9ea0) = 0
4289 close(3) = 0
4291 rt_sigaction(SIGHUP,4289 NULL,close(5)0x0000004000bd9dd0 = 0
) = 0
4289 close(7) = 0
4291 rt_sigaction(SIGHUP,0x0000004000bd9d30,NULL) = 0
```

That is, process 4289 continued executing before the child 4291 runs, but it should be suspended until the child exits or execs. I can see similar with `qemu-x86_64`, though using `clone3` on my Fedora host, whereas native `strace -f ./main` shows:

```
clone3({flags=CLONE_VM|CLONE_VFORK, exit_signal=SIGCHLD, stack=0x7f11a1211000, stack_size=0x9000}, 88strace: Process 148962 attached
 <unfinished ...>
[pid 148962] rt_sigprocmask(SIG_BLOCK, NULL, ~[KILL STOP], 8) = 0
[...]
[pid 148962] rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
[pid 148962] execve("/no-binary-by-this-name-should-exist", ["/no-binary-by-this-name-should-e"...], 0x7ffe09be3e28 /* 69 vars */) = -1 ENOENT (No such file or directory)
[pid 148962] exit_group(127)            = ?
[pid 148961] <... clone3 resumed>)      = 148962
[pid 148962] +++ exited with 127 +++
wait4(148962, NULL, 0, NULL)            = 148962
```

At least that `exit_group(127)` is sort of coming through in your qemu case, with the `unreachable!` output showing `unix_wait_status(32512)` which is `0x7f00`, meaning exit code 0x7f == 127.

I didn't find a qemu bug about vfork, but I found this mention:

https://stackoverflow.com/a/51437489/114410
> `vfork` is still broken in qemu-user and Microsoft's emulation, but the bugs usually are not visible when using `posix_spawn` because it does not actually use `vfork`, but a `vfork`-style `clone` system call with a separate stack, so that even if the parent process is not properly paused, the stack in the child is not clobbered.

It seems that it does break `posix_spawn`'s error-handling code.

**Comment by ius** [comment]
Related qemu `linux-user` bug report: https://gitlab.com/qemu-project/qemu/-/issues/140

**Comment by nivkner** [comment]
closing since the issue is not from rust, and there is a linked bug report for qemu in case anyone has a similar problem using `Command` in qemu.
