### ISSUE TITLE
error: linking with `x86_64-w64-mingw32-gcc` failed: exit code: 1 Please help me

### ISSUE THREAD

**Issue by rustJi** [rust-lang/rust#90859]
Hello, I'm a beginner who uses the rust language. I just want to know how to solve this kind of error. I want to make a GUI application using gtk4. Please help me.
### Code

```Rust
<code>
```

### Meta

`rustc --version --verbose`:
```
<version>
os : Windows / IDE : CLion / 
PS C:\Users\clean\CLionProjects\untitled5> rustup toolchain list
stable-x86_64-pc-windows-gnu (default)


```
### Error output
<output>
PS C:\Users\clean\CLionProjects\untitled5> cargo run
   Compiling untitled5 v0.1.0 (C:\Users\clean\CLionProjects\untitled5)
error: linking with `x86_64-w64-mingw32-gcc` failed: exit code: 1
  |
  = note: "x86_64-w64-mingw32-gcc" "-fno-use-linker-plugin" "-Wl,--dynamicbase" "-Wl,--disable-auto-image-base" "-m64" "-Wl,--high-entropy-va" "C:\\.rustup\\toolchains\\stable-x86_6
4-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\rsbegin.o" "C:\\Users\\clean\\CLionProjects\\untitled5\\target\\debug\\deps\\untitled5-4d58dd646ee4e048.10p6a6airiaic6md.
rcgu.o" "C:\\Users\\clean\\CLionProjects\\untitled5\\target\\debug\\deps\\untitled5-4d58dd646ee4e048.12rttrfur75039zk.rcgu.o" "C:\\Users\\clean\\CLionProjects\\untitled5\\target\\de
bug\\deps\\untitled5-4d58dd646ee4e048.1cjnp6ux5jzyz5ud.rcgu.o" "C:\\Users\\clean\\CLionProjects\\untitled5\\target\\debug\\deps\\untitled5-4d58dd646ee4e048.1fglv4cs5gkbll0u.rcgu.o"
"C:\\Users\\clean\\CLionProjects\\untitled5\\target\\debug\\deps\\untitled5-4d58dd646ee4e048.1izoniiu03ykt83.rcgu.o" "C:\\Users\\clean\\CLionProjects\\untitled5\\target\\debug\\deps
\\untitled5-4d58dd646ee4e048.1p8qe5omv4b1x1cx.rcgu.o" "C:\\Users\\clean\\CLionProjects\\untitled5\\target\\debug\\deps\\untitled5-4d58dd646ee4e048.1twqo85vie3lzx3d.rcgu.o" "C:\\User
s\\clean\\CLionProjects\\untitled5\\target\\debug\\deps\\untitled5-4d58dd646ee4e048.1uw1jltl3rhl7vv0.rcgu.o" "C:\\Users\\clean\\CLionProjects\\untitled5\\target\\debug\\deps\\untitl
ed5-4d58dd646ee4e048.21dkvygjbj3ab2ky.rcgu.o" "C:\\Users\\clean\\CLionProjects\\untitled5\\target\\debug\\deps\\untitled5-4d58dd646ee4e048.21fh0ggl5d9u35os.rcgu.o" "C:\\Users\\clean
\\CLionProjects\\untitled5\\target\\debug\\deps\\untitled5-4d58dd646ee4e048.2axzf3k691bnw4u3.rcgu.o" "C:\\Users\\clean\\CLionProjects\\untitled5\\target\\debug\\deps\\untitled5-4d58
dd646ee4e048.2hl3gb3qrzs32fea.rcgu.o" "C:\\Users\\clean\\CLionProjects\\untitled5\\target\\debug\\deps\\untitled5-4d58dd646ee4e048.2rrp88rg4x8wzmas.rcgu.o" "C:\\Users\\clean\\CLionP
rojects\\untitled5\\target\\debug\\deps\\untitled5-4d58dd646ee4e048.2smn2q6mtbzkt0b2.rcgu.o" "C:\\Users\\clean\\CLionProjects\\untitled5\\target\\debug\\deps\\untitled5-4d58dd646ee4
e048.30ni2z4u4e2sh3zv.rcgu.o" "C:\\Users\\clean\\CLionProjects\\untitled5\\target\\debug\\deps\\untitled5-4d58dd646ee4e048.328nw5fo0vwpychj.rcgu.o" "C:\\Users\\clean\\CLionProjects\
\untitled5\\target\\debug\\deps\\untitled5-4d58dd646ee4e048.33od15f6jum930n5.rcgu.o" "C:\\Users\\clean\\CLionProjects\\untitled5\\target\\debug\\deps\\untitled5-4d58dd646ee4e048.36o
axwamanqqvt0h.rcgu.o" "C:\\Users\\clean\\CLionProjects\\untitled5\\target\\debug\\deps\\untitled5-4d58dd646ee4e048.37zs81yc2pnmv6is.rcgu.o" "C:\\Users\\clean\\CLionProjects\\untitle
d5\\target\\debug\\deps\\untitled5-4d58dd646ee4e048.3lep6lqpvq4rkz0x.rcgu.o" "C:\\Users\\clean\\CLionProjects\\untitled5\\target\\debug\\deps\\untitled5-4d58dd646ee4e048.3uv30lu915d
yzzcj.rcgu.o" "C:\\Users\\clean\\CLionProjects\\untitled5\\target\\debug\\deps\\untitled5-4d58dd646ee4e048.3x8zbgsv4gb057u8.rcgu.o" "C:\\Users\\clean\\CLionProjects\\untitled5\\targ
et\\debug\\deps\\untitled5-4d58dd646ee4e048.3zudazzz9kl4lj8r.rcgu.o" "C:\\Users\\clean\\CLionProjects\\untitled5\\target\\debug\\deps\\untitled5-4d58dd646ee4e048.458cdlqh14xxaynf.rc
gu.o" "C:\\Users\\clean\\CLionProjects\\untitled5\\target\\debug\\deps\\untitled5-4d58dd646ee4e048.47mrajnhpbl11uso.rcgu.o" "C:\\Users\\clean\\CLionProjects\\untitled5\\target\\debu
g\\deps\\untitled5-4d58dd646ee4e048.48621qbhk18cvase.rcgu.o" "C:\\Users\\clean\\CLionProjects\\untitled5\\target\\debug\\deps\\untitled5-4d58dd646ee4e048.4hl8qnp896rna6xi.rcgu.o" "C
:\\Users\\clean\\CLionProjects\\untitled5\\target\\debug\\deps\\untitled5-4d58dd646ee4e048.4s86ruorc45p4qaj.rcgu.o" "C:\\Users\\clean\\CLionProjects\\untitled5\\target\\debug\\deps\
\untitled5-4d58dd646ee4e048.58b87bm4oeswxzky.rcgu.o" "C:\\Users\\clean\\CLionProjects\\untitled5\\target\\debug\\deps\\untitled5-4d58dd646ee4e048.5e20be4wx1j8rljq.rcgu.o" "C:\\Users
\\clean\\CLionProjects\\untitled5\\target\\debug\\deps\\untitled5-4d58dd646ee4e048.ibs5nx198llvzw6.rcgu.o" "C:\\Users\\clean\\CLionProjects\\untitled5\\target\\debug\\deps\\untitled
5-4d58dd646ee4e048.ktv41hsq8lk5e6g.rcgu.o" "C:\\Users\\clean\\CLionProjects\\untitled5\\target\\debug\\deps\\untitled5-4d58dd646ee4e048.o81a3kndk6rrs60.rcgu.o" "C:\\Users\\clean\\CL
ionProjects\\untitled5\\target\\debug\\deps\\untitled5-4d58dd646ee4e048.x04c9wa7efofs6.rcgu.o" "C:\\Users\\clean\\CLionProjects\\untitled5\\target\\debug\\deps\\untitled5-4d58dd646e
e4e048.xyli6iu25xl76t8.rcgu.o" "C:\\Users\\clean\\CLionProjects\\untitled5\\target\\debug\\deps\\untitled5-4d58dd646ee4e048.zf050ou4e4bh8me.rcgu.o" "C:\\Users\\clean\\CLionProjects\
\untitled5\\target\\debug\\deps\\untitled5-4d58dd646ee4e048.sprztkfqv7br7fw.rcgu.o" "-L" "C:\\Users\\clean\\CLionProjects\\untitled5\\target\\debug\\deps" "-L" "C:/msys64/mingw64/bi
n/../lib" "-L" "C:/msys64/mingw64/bin/../lib" "-L" "C:/msys64/mingw64/bin/../lib" "-L" "C:/msys64/mingw64/bin/../lib" "-L" "C:/msys64/mingw64/bin/../lib" "-L" "C:/msys64/mingw64/bin
/../lib" "-L" "C:/msys64/mingw64/bin/../lib" "-L" "C:\\.cargo\\bin\\bin\\registry\\src\\github.com-1ecc6299db9ec823\\winapi-x86_64-pc-windows-gnu-0.4.0\\lib" "-L" "C:/msys64/mingw64
/bin/../lib" "-L" "C:/msys64/mingw64/bin/../lib" "-L" "C:/msys64/mingw64/bin/../lib" "-L" "C:/msys64/mingw64/bin/../lib" "-L" "C:/msys64/mingw64/bin/../lib" "-L" "C:\\.rustup\\toolc
hains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib" "-Wl,-Bstatic" "C:\\Users\\clean\\CLionProjects\\untitled5\\target\\debug\\deps\\libgtk4-c65197b6c9891
cab.rlib" "C:\\Users\\clean\\CLionProjects\\untitled5\\target\\debug\\deps\\libgsk4-1907319ed7c1d114.rlib" "C:\\Users\\clean\\CLionProjects\\untitled5\\target\\debug\\deps\\libgraph
ene-3675a47d1fb95b10.rlib" "C:\\Users\\clean\\CLionProjects\\untitled5\\target\\debug\\deps\\libgdk4-9d9079ff51731b8b.rlib" "C:\\Users\\clean\\CLionProjects\\untitled5\\target\\debu
g\\deps\\libpango-16e9333c14f740c4.rlib" "C:\\Users\\clean\\CLionProjects\\untitled5\\target\\debug\\deps\\libgdk_pixbuf-c701997edee275d1.rlib" "C:\\Users\\clean\\CLionProjects\\unt
itled5\\target\\debug\\deps\\libgio-67537043e26fa5a9.rlib" "C:\\Users\\clean\\CLionProjects\\untitled5\\target\\debug\\deps\\libfutures_io-89c30a5d3860112f.rlib" "C:\\Users\\clean\\
CLionProjects\\untitled5\\target\\debug\\deps\\libcairo-0a6735a4518a5ff7.rlib" "C:\\Users\\clean\\CLionProjects\\untitled5\\target\\debug\\deps\\libthiserror-9c7f1334f0eca2fc.rlib"
"C:\\Users\\clean\\CLionProjects\\untitled5\\target\\debug\\deps\\libglib-544f7e4cd29f1016.rlib" "C:\\Users\\clean\\CLionProjects\\untitled5\\target\\debug\\deps\\libfutures_executo
r-4abd14ab4301aa43.rlib" "C:\\Users\\clean\\CLionProjects\\untitled5\\target\\debug\\deps\\libfutures_util-bb74c5dc3bfc9b88.rlib" "C:\\Users\\clean\\CLionProjects\\untitled5\\target
\\debug\\deps\\libslab-4e0e6167509331f9.rlib" "C:\\Users\\clean\\CLionProjects\\untitled5\\target\\debug\\deps\\libpin_project_lite-710649743d317516.rlib" "C:\\Users\\clean\\CLionPr
ojects\\untitled5\\target\\debug\\deps\\libpin_utils-052a687d6be53374.rlib" "C:\\Users\\clean\\CLionProjects\\untitled5\\target\\debug\\deps\\libfutures_channel-9f0ea15a60bf2efa.rli
b" "C:\\Users\\clean\\CLionProjects\\untitled5\\target\\debug\\deps\\libfutures_task-e4b98dee68422031.rlib" "C:\\Users\\clean\\CLionProjects\\untitled5\\target\\debug\\deps\\libfutu
res_core-f7f0788bab58bdbb.rlib" "C:\\Users\\clean\\CLionProjects\\untitled5\\target\\debug\\deps\\libsmallvec-578ade25a7e3a2d9.rlib" "C:\\Users\\clean\\CLionProjects\\untitled5\\tar
get\\debug\\deps\\libonce_cell-daea5d38a4fbeee6.rlib" "C:\\Users\\clean\\CLionProjects\\untitled5\\target\\debug\\deps\\libbitflags-88cf4acb31ef4dac.rlib" "C:\\Users\\clean\\CLionPr
ojects\\untitled5\\target\\debug\\deps\\libgtk4_sys-b2cf4ca0e1c5b041.rlib" "C:\\Users\\clean\\CLionProjects\\untitled5\\target\\debug\\deps\\libgsk4_sys-bb99f102fdd895c0.rlib" "C:\\
Users\\clean\\CLionProjects\\untitled5\\target\\debug\\deps\\libgraphene_sys-3d38c70003f39db2.rlib" "C:\\Users\\clean\\CLionProjects\\untitled5\\target\\debug\\deps\\libgdk4_sys-84b
25fdf5c30f1a6.rlib" "C:\\Users\\clean\\CLionProjects\\untitled5\\target\\debug\\deps\\libpango_sys-62ad7c0197025f87.rlib" "C:\\Users\\clean\\CLionProjects\\untitled5\\target\\debug\
\deps\\libgdk_pixbuf_sys-530f4653464d83f3.rlib" "C:\\Users\\clean\\CLionProjects\\untitled5\\target\\debug\\deps\\libgio_sys-119b2437e9c0d640.rlib" "C:\\Users\\clean\\CLionProjects\
\untitled5\\target\\debug\\deps\\libwinapi-ea7274e67c34aed0.rlib" "C:\\Users\\clean\\CLionProjects\\untitled5\\target\\debug\\deps\\libgobject_sys-62389e37812484ca.rlib" "C:\\Users\
\clean\\CLionProjects\\untitled5\\target\\debug\\deps\\libcairo_sys-1c30bbb3b9c86a5f.rlib" "C:\\Users\\clean\\CLionProjects\\untitled5\\target\\debug\\deps\\libglib_sys-5822c668f759
8c08.rlib" "C:\\Users\\clean\\CLionProjects\\untitled5\\target\\debug\\deps\\liblibc-da6bdcf01e558858.rlib" "C:\\Users\\clean\\CLionProjects\\untitled5\\target\\debug\\deps\\libfiel
d_offset-ced16ba0b59c2550.rlib" "C:\\Users\\clean\\CLionProjects\\untitled5\\target\\debug\\deps\\libmemoffset-0a3b30c6537163fe.rlib" "-Wl,--start-group" "C:\\.rustup\\toolchains\\s
table-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libstd-c949a5d9f8ea17eb.rlib" "C:\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-
windows-gnu\\lib\\libpanic_unwind-4efbd26dc95f473b.rlib" "C:\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libobject-11df657f271ec0b5
.rlib" "C:\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libmemchr-ed6e817a89285a21.rlib" "C:\\.rustup\\toolchains\\stable-x86_64-pc-
windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libaddr2line-a16c4de5bb48a9a6.rlib" "C:\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gn
u\\lib\\libgimli-b5d4a31ea91f9e86.rlib" "C:\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libstd_detect-01e22831e506e0c6.rlib" "C:\\.
rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\librustc_demangle-85865d75ad690c5e.rlib" "C:\\.rustup\\toolchains\\stable-x86_64-pc-windo
ws-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libhashbrown-91e2696c8ccb4461.rlib" "C:\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\li
b\\librustc_std_workspace_alloc-186512436a4043bc.rlib" "C:\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libunwind-d0f4aee65f54d86f.r
lib" "C:\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcfg_if-42335e6cb2553e87.rlib" "C:\\.rustup\\toolchains\\stable-x86_64-pc-wi
ndows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\liblibc-662baf24e2595e01.rlib" "C:\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\
\liballoc-131219d6deabaad8.rlib" "C:\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\librustc_std_workspace_core-6530d4af942dc9d4.rlib"
 "C:\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcore-d1ec034e2d5fe483.rlib" "-Wl,--end-group" "C:\\.rustup\\toolchains\\stable-
x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\libcompiler_builtins-885492184211f20a.rlib" "-Wl,-Bdynamic" "-lgobject-2.0" "-lgtk-4" "-lpangowin32-1.0" "-lpangocai
ro-1.0" "-lpango-1.0" "-lharfbuzz" "-lgdk_pixbuf-2.0" "-lcairo-gobject" "-lcairo" "-lvulkan" "-lgraphene-1.0" "-lgio-2.0" "-lgobject-2.0" "-lglib-2.0" "-lintl" "-lgtk-4" "-lpangowin
32-1.0" "-lpangocairo-1.0" "-lpango-1.0" "-lharfbuzz" "-lgdk_pixbuf-2.0" "-lcairo-gobject" "-lcairo" "-lvulkan" "-lgraphene-1.0" "-lgio-2.0" "-lgobject-2.0" "-lglib-2.0" "-lintl" "-
lgraphene-1.0" "-lgobject-2.0" "-lglib-2.0" "-lintl" "-lgtk-4" "-lpangowin32-1.0" "-lpangocairo-1.0" "-lpango-1.0" "-lharfbuzz" "-lgdk_pixbuf-2.0" "-lcairo-gobject" "-lcairo" "-lvul
kan" "-lgraphene-1.0" "-lgio-2.0" "-lgobject-2.0" "-lglib-2.0" "-lintl" "-lpango-1.0" "-lgobject-2.0" "-lglib-2.0" "-lintl" "-lharfbuzz" "-lgdk_pixbuf-2.0" "-lgobject-2.0" "-lglib-2
.0" "-lintl" "-lgio-2.0" "-lgobject-2.0" "-lglib-2.0" "-lintl" "-lwinapi_advapi32" "-lwinapi_cfgmgr32" "-lwinapi_kernel32" "-lwinapi_user32" "-lwinapi_ws2_32" "-lgobject-2.0" "-lgli
b-2.0" "-lintl" "-lcairo-gobject" "-lcairo" "-lgobject-2.0" "-lglib-2.0" "-lintl" "-lgobject-2.0" "-lglib-2.0" "-lintl" "-lkernel32" "-lws2_32" "-ladvapi32" "-luserenv" "-lkernel32"
 "-lgcc_eh" "-l:libpthread.a" "-lmsvcrt" "-lmingwex" "-lmingw32" "-lgcc" "-lmsvcrt" "-luser32" "-lkernel32" "-Wl,--nxcompat" "-L" "C:\\.rustup\\toolchains\\stable-x86_64-pc-windows-
gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib" "-o" "C:\\Users\\clean\\CLionProjects\\untitled5\\target\\debug\\deps\\untitled5-4d58dd646ee4e048.exe" "-Wl,--gc-sections" "-no-pie" "
-nodefaultlibs" "C:\\.rustup\\toolchains\\stable-x86_64-pc-windows-gnu\\lib\\rustlib\\x86_64-pc-windows-gnu\\lib\\rsend.o"
  = note: C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/10.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: C:\Users\clean\CLionProjects\untitled5\target\debug\deps\libgdk4-9d90
79ff51731b8b.rlib(gdk4-9d9079ff51731b8b.gdk4.d8d33e11-cgu.11.rcgu.o): in function `<gdk4::auto::enums::TitlebarGesture as glib::types::StaticType>::static_type':
          C:\.cargo\bin\bin\registry\src\github.com-1ecc6299db9ec823\gdk4-0.3.1\src\auto/enums.rs:1915: undefined reference to `gdk_titlebar_gesture_get_type'
          collect2.exe: error: ld returned 1 exit status

  = help: some `extern` functions couldn't be found; some native libraries may need to be installed or have their path specified
  = note: use the `-l` flag to specify native libraries to link
  = note: use the `cargo:rustc-link-lib` directive to specify the native libraries to link with Cargo (see https://doc.rust-lang.org/cargo/reference/build-scripts.html#cargorustc-li
nk-libkindname)

error: could not compile `untitled5` due to previous error

**Comment by hkratz** [comment]
This does not seem to be a Rust error at all, but rather a dependency problem. Your gtk-4 library is not from GTK 4.4 and that is apparently required? 

@GuillaumeGomez Shouldn't that and `gdk_toplevel_titlebar_gesture` be behind the 4_4 feature gate?

@rustbot  label -I-ICE

**Comment by rustJi** [comment]
[dependencies]
gtk = { version = "0.3.1", package = "gtk4" }

That is my dependencies.

**Comment by hkratz** [comment]
> [dependencies] gtk = { version = "0.3.1", package = "gtk4" }
> 
> That is my dependencies.

The native msys2 gtk-4 libraries you installed are apparently not 4.4. You followed the instructions from [the book](https://gtk-rs.org/gtk4-rs/stable/latest/book/installation_windows.html#gnu-toolchain) I guess? If so, does upgrading with `pacman -Syu` help?

**Comment by GuillaumeGomez** [comment]
Opening an issue in the corresponding crate. Thanks for the ping!
