### ISSUE TITLE
Rustdoc: Methods from `Deref` should not be `const`

### ISSUE THREAD

**Issue by fee1-dead** [rust-lang/rust#90855]
Screenshot:

![image](https://user-images.githubusercontent.com/43851243/141608030-011e661b-c5af-4cf6-a4e7-2d6209a32dcb.png)

Considering that rustdoc doesn't care about `const_trait_impl`, methods from `Deref` cannot be called in const contexts. Therefore it is best to hide the `const` modifiers when showing methods from `Deref`.

**Comment by GuillaumeGomez** [comment]
For more information:

```rust
const S: String = String::new();
const Y: usize = S.len();

fn main() {}
```

gives:

```
error[E0015]: calls in constants are limited to constant functions, tuple structs and tuple variants
 --> src/main.rs:2:18
  |
2 | const Y: usize = S.len();
  |                  ^^^^^^^

error[E0493]: destructors cannot be evaluated at compile-time
 --> src/main.rs:2:18
  |
2 | const Y: usize = S.len();
  |                  ^     - value is dropped here
  |                  |
  |                  constants cannot evaluate destructors
```

It is linked to https://github.com/rust-lang/rust/issues/67792. So for now, let's remove this display.
