### ISSUE TITLE
`for<'a> Fn(<A as B<'a>>::C)` fails incosistently and requires unnecessary type annotations

### ISSUE THREAD

**Issue by aliemjay** [rust-lang/rust#90875]
I tried this code:

```rust
trait Variable<'a> {
    type Type;
}

impl Variable<'_> for () {
    type Type = ();
}

fn check<F, T>(_: F)
where
    F: Fn(T), // <- if removed, all fn_* then require type annotations
    F: for<'a> Fn(<T as Variable<'a>>::Type),
    T: for<'a> Variable<'a>,
{
}

fn test(arg: impl Fn(())) {
    fn fn_1(_: ()) {}
    let fn_2 = |_: ()| ();
    let fn_3 = |a| fn_1(a);
    let fn_4 = arg;

    check(fn_1); // Error
    check(fn_2); // Ok
    check(fn_3); // Ok
    check(fn_4); // Error
    check::<_, ()>(fn_1); // Ok
    check::<_, ()>(fn_4); // Ok
}
```
([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=311765eb65fa36205839f2930d6f29d8))

I expected to see this happen: the code compiles fine.

Instead, this happened: `check(fn_1)` and `check(fn_4)` fails to type check, and although the error message is not related to type inference, annotating the type parameter `T` fixes the problem. the same thing happens when removing the bound `F: Fn(T)`, but then for all `check(fn_*)`.

Seems to be related to #79207. cc @jackh726 

<details><summary>Error message</summary>
<p>

```
   Compiling playground v0.0.1 (/playground)
error[E0631]: type mismatch in function arguments
  --> src/lib.rs:23:11
   |
18 |     fn fn_1(_: ()) {}
   |     -------------- found signature of `fn(()) -> _`
...
23 |     check(fn_1); // Error
   |     ----- ^^^^ expected signature of `for<'a> fn(<() as Variable<'a>>::Type) -> _`
   |     |
   |     required by a bound introduced by this call
   |
note: required by a bound in `check`
  --> src/lib.rs:12:8
   |
9  | fn check<F, T>(_: F)
   |    ----- required by a bound in this
...
12 |     F: for<'a> Fn(<T as Variable<'a>>::Type),
   |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `check`

error[E0277]: expected a `Fn<(<() as Variable<'a>>::Type,)>` closure, found `impl Fn(())`
  --> src/lib.rs:26:11
   |
26 |     check(fn_4); // Error
   |     ----- ^^^^ expected an `Fn<(<() as Variable<'a>>::Type,)>` closure, found `impl Fn(())`
   |     |
   |     required by a bound introduced by this call
   |
note: required by a bound in `check`
  --> src/lib.rs:12:8
   |
9  | fn check<F, T>(_: F)
   |    ----- required by a bound in this
...
12 |     F: for<'a> Fn(<T as Variable<'a>>::Type),
   |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ required by this bound in `check`
help: consider further restricting this bound
   |
17 | fn test(arg: impl Fn(()) + for<'a> std::ops::Fn<(<() as Variable<'a>>::Type,)>) {
   |                          +++++++++++++++++++++++++++++++++++++++++++++++++++++

Some errors have detailed explanations: E0277, E0631.
For more information about an error, try `rustc --explain E0277`.
error: could not compile `playground` due to 2 previous errors
```

</p>
</details>

### Context
[Original thread in users forum](https://users.rust-lang.org/t/hrtb-bug-when-for-a-fn-x-as-trait-a-assoc/67300)

### Meta
Tested on ~~stable and~~ nightly branches of playground:
* ~~Stable version: 1.56.1~~
* Nightly version: 1.58.0-nightly (2021-11-09 8b09ba6a5d5c644fe0f1)

**Comment by aliemjay** [comment]
Prior to v1.56, closures and functions all fail alike with the same error message and adding type annotations didn't help either. So my guess is that #85499 introduced an (incomplete?) fix, so I think this now needs to:
* address the inconsistency
* improve error message to require type annotations

@rustbot label A-diagnostics

**Comment by steffahn** [comment]
While changing the error message _could_ improve the situation, this is clearly not exclusively a diagnostics issue, AFAICT. To avoid potential confusion, let me remove the A-diagnostics label, which is commonly applied to issues that are _purely_ diagnostics issues. @rustbot label -A-diagnostics.

In case it is decided that this _is_ only a diagnostics issue after all, the label can be reapplied. In case the inconsistency is somehow fixed and diagnostics issues remain, a new A-diagnostics issue can be opened.

**Comment by aliemjay** [comment]
I've just been aware of the version differences and recent efforts to solve this. So here is a summary:
* Prior to 1.56, all cases failed even with type annotations.
* On 1.56 (due to #85499), all cases still fail but type annotation workaround now works.
* On nightly (due to #88441), closures (rather than functions) no longer require type annotation.

A duplicate of #89436.
