### ISSUE TITLE
x86/x86_64::__mm256_set_epi8 has wrong description

### ISSUE THREAD

**Issue by Super-Pizza** [rust-lang/rust#90885]
It says "Sets packed 8-bit integers in returned vector with the supplied values in reverse order."
This should be for __mm256_set*r*_epi8.

**Comment by hkratz** [comment]
Already fixed in https://github.com/rust-lang/stdarch/pull/1248. Will be fixed here once the stdarch update #90881 lands.

**Comment by Super-Pizza** [comment]
Ah, sorry for that.
