### ISSUE TITLE
Using asm label locations unsupported

### ISSUE THREAD

**Issue by C0D3-M4513R** [rust-lang/rust#90908]
I tried this code:

```rust
#![feature(asm,global_asm)]
fn main() {
    unsafe{asm!("int3","mov eax,2f","2:","ret",out("eax") _);}
    println!("Hello, world!");"
}
```
and
```rust
#![feature(asm,global_asm)]

fn main() {
    unsafe{test();}
    println!("Hello, world!");
}

global_asm!(".global _test","_test:","int3","mov eax,label","label:","ret");
extern "C"{
    fn test();
}
```

I expected to see this happen: 
I expected the assembly code to look the same, when I look at it (after compilation) with a decompiler (like ida64).
And I also expect this code to print "Hello, World!" without the "int3" instruction.
The assembly code should put the location of the label 2f (or label in the case of the global_asm example) in the register eax for later use (here not present, for making this simple)
 
Instead, this happened: 
The mov instruction instead has a weird long value.
![image](https://user-images.githubusercontent.com/28912031/141691305-f1750312-1cf9-47cf-81db-b8e8969cc772.png)

### Meta

`rustc +nightly-i686 --version --verbose`:
```
rustc 1.58.0-nightly (b416e3892 2021-11-13)
binary: rustc
commit-hash: b416e3892d9526709f3a248f5ed3a43a970f795e
commit-date: 2021-11-13
host: i686-pc-windows-msvc
release: 1.58.0-nightly
LLVM version: 13.0.0
```

<details><summary>Backtrace</summary>
<p>

```
\CLionProjects\asm-ptr-lbl>echo %RUST_BACKTRACE%
1

\CLionProjects\asm-ptr-lbl>cargo +nightly-i686 build
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s

\CLionProjects\asm-ptr-lbl>cargo clean

\CLionProjects\asm-ptr-lbl>cargo +nightly-i686 build
   Compiling asm-ptr-lbl v0.1.0 (C:\Users\timon\CLionProjects\asm-ptr-lbl)
    Finished dev [unoptimized + debuginfo] target(s) in 0.61s
```

</p>
</details>

EDIT: Similar issue with "push"
```rust
#![feature(asm,global_asm)]

fn main() {
    unsafe{asm!("int3","push 2f","pop ecx","2:","ret",out("eax") _);}
    println!("Hello, world!");
}

```
and 
```rust
#![feature(asm,global_asm)]

fn main() {
    unsafe{test();}
    println!("Hello, world!");
}

global_asm!(".global _test","_test:","int3","push label","pop ecx","label:","ret");
extern "C"{
    fn test();
}
```
respectively push the value contained at the label, rather than pushing the location of the label.
I need the push to work correctly, for doing processor mode switching with a far return [inside rust].

**Comment by asquared31415** [comment]
That behavior is how LLVM's assembler (which is mostly GAS compatible) works.  Do you want `lea reg, [label]` perhaps, to load the instruction pointer at `label` into `reg`?

Additionally the `ret` in your asm is almost certainly wrong, you're returning from the function immediately.

**Comment by asquared31415** [comment]
If I'm interpreting your intent correctly, something like [this (playground)](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=80ac75df555f5078b572d5d59d8b21a9) is how I would write it.

I don't believe this is a bug in Rust or the assembler though.  Simply some different or unintuitive behavior.

**Comment by C0D3-M4513R** [comment]
> That behavior is how LLVM's assembler (which is mostly GAS compatible) works. Do you want `lea reg, [label]` perhaps, to load the instruction pointer at `label` into `reg`?

That was exactly what I needed. Thank you! The `mov` instruction just looked REALLY broken in the screenshot, to the point it corrupted some instructions .(might have been ida64[debugger]'s interpretation tho)

> Additionally the `ret` in your asm is almost certainly wrong, you're returning from the function immediately.

True. I copy pasted the assembly from global_asm(and didn't edit it beyond the labels). The `ret` is wrong there.

On another note: I'm still trying to get processor mode switching working(x86->x64) in rust. But this is an essential part of doing the correct jumps, when I have no way of knowing the correct addresses.

You captured my intent exactly in your last post. Tysm!
