### ISSUE TITLE
Scrollbar disappears when sidebar is short

### ISSUE THREAD

**Issue by jsha** [rust-lang/rust#90943]
In this example, for ToString, the sidebar is shorter than the page, so there is no scrollbar:

![image](https://user-images.githubusercontent.com/220205/141933577-565ead1a-56db-406f-ae89-fabf29e72e88.png)

In this example, for String, the sidebar is longer so there is a scrollbar:

![image](https://user-images.githubusercontent.com/220205/141933758-7add0c44-726d-46cf-b89e-478ffdc51e1c.png)

The problem here is that the scrollbar forms part of the visual layout of the page, separating the sidebar from the main content. I think for the sake of consistency we should always show the sidebar.

**Comment by GuillaumeGomez** [comment]
I think this is a good idea. I'll send a PR for it.
