### ISSUE TITLE
Misleading/Incomplete errors involving Pattern

### ISSUE THREAD

**Issue by glandium** [rust-lang/rust#90970]
Given the following code: 

```rust
pub fn strip_lf(s: &str) -> &str {
    s.strip_suffix(b'\n').unwrap_or(s)
}
```

The current output is:

```
error[E0277]: expected a `FnMut<(char,)>` closure, found `u8`
 --> src/lib.rs:2:20
  |
2 |     s.strip_suffix(b'\n').unwrap_or(s)
  |                    ^^^^^ expected an `FnMut<(char,)>` closure, found `u8`
  |
  = help: the trait `FnMut<(char,)>` is not implemented for `u8`
  = note: required because of the requirements on the impl of `Pattern<'_>` for `u8`
```

`Pattern<'a>` has implementations for:
- `char`
- `&str`
- `&String`
- `&[char]`
- `&&str`
- `F` where `F: FnMut(char) -> bool`

While it is true that u8 doesn't match any of the non-generic impls, and that it doesn't have an impl for `FnMut<(char,)> -> bool`, it's sad that the error message doesn't mention that those other possibilities exist.
(Also, the error message doesn't mention the closure return type)

**Comment by estebank** [comment]
Linking to the [Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/147480-t-compiler.2Fwg-diagnostics/topic/Best.20strategy.20for.20.2390970) for the record.

**Comment by JakobDegen** [comment]
I thought about this a bunch, and don't really know the best solution here. Happy to let someone else try

**Comment by taladar** [comment]
I encountered a related issue today with the pattern parameter on replace

```
fn main() {
    let s1: String = "Foo".to_string();
    let s2: String = "Bar".to_string();
    let mut s: String = "FooBarBaz".to_string();
    s.replace(s1, &s2);
    format!("Replacement result: {}", s);
}
```

(no & for s1 in the replace call) results in the error:

```
   Compiling compiler-bug-test v0.1.0 (/home/taladar/temp/20211223/compiler-bug-test)
error[E0277]: expected a `FnMut<(char,)>` closure, found `String`
 --> src/main.rs:5:7
  |
5 |     s.replace(s1, &s2);
  |       ^^^^^^^ expected an `FnMut<(char,)>` closure, found `String`
  |
  = help: the trait `FnMut<(char,)>` is not implemented for `String`
  = note: required because of the requirements on the impl of `Pattern<'_>` for `String`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `compiler-bug-test` due to previous error
```

which is misleading because it marks "replace" instead of the first parameter in addition to the issue mentioned above.

**Comment by edmorley** [comment]
See also #87437 (which may be a dupe of this or vice versa, unless I'm misunderstanding).
