### ISSUE TITLE
print! macro dams console out

### ISSUE THREAD

**Issue by Marusugi** [rust-lang/rust#90976]
I tried this code:
```rust
fn main() {
   print!("can't print");
   let path: Vec<String> = env::args().collect();
   let mut new_game = NumPlace::new(File::open(path.get(1).unwrap()).unwrap());

   while new_game.is_updatable() {
      new_game.update().view();
      println!("reached main.rs: 13");
   }
}
```
entire source of project: https://github.com/Marusugi/bug_report.git

I expected to see this happen: I hope to see console like
```
cargo run problem.txt
   Compiling numberplace v0.1.0 (/path/to/numberplace)
    Finished dev [unoptimized + debuginfo] target(s) in 0.21s
     Running `target/debug/numberplace problem.txt`
can't print
....
```
Instead, this happened: 
```
cargo run problem.txt
   Compiling numberplace v0.1.0 (/path/to/numberplace)
    Finished dev [unoptimized + debuginfo] target(s) in 0.24s
     Running `target/debug/numberplace problem.txt`

```

nothing appeared
### Meta

`rustc --version --verbose`:
```
rustc --version --verbose
rustc 1.56.0 (09c42c458 2021-10-18)
binary: rustc
commit-hash: 09c42c45858d5f3aedfa670698275303a3d19afa
commit-date: 2021-10-18
host: aarch64-apple-darwin
release: 1.56.0
LLVM version: 13.0.0
```

Nightly and beta compiler did same behavior

<details><summary>Backtrace</summary>
<p>

```
RUST_BACKTRACE=1 cargo run problem.txt
    Finished dev [unoptimized + debuginfo] target(s) in 0.00s
     Running `target/debug/numberplace problem.txt`
```
Nothing outputted

</p>
</details>

**Comment by Marusugi** [comment]
I made mistake. In num_place.rs: 70 in definition of cin(). It should be written like
```rust
stdin().read_line(&mut buf).unwrap();
```
but I code
```rust
stdin().read_to_string(&mut buf).unwrap();
```

I modified and project seems to behave as I hope now.
I'm so sorry.

But, In my opinion, This behavior is misleading and not intuitive..

**Comment by hkratz** [comment]
Stdout is usually line-buffered, see https://doc.rust-lang.org/std/macro.print.html

If you want to make sure that the text is printed immediately use `println!()` or `flush()` stdout.

**Comment by Marusugi** [comment]
Thanks! and sorry to bother you.. Now, I understand!
