### ISSUE TITLE
Problem when impl From for GAT

### ISSUE THREAD

**Issue by davidli2010** [rust-lang/rust#90971]
I tried this code:

```rust
#![feature(generic_associated_types)]

pub trait Type {
    type Ref<'a>;
}

pub struct TypeRef<'a, T: Type> {
    r: T::Ref<'a>,
}

impl<'a, T: Type> From<T::Ref<'a>> for TypeRef<'a, T> {
    fn from(_: T::Ref<'a>) -> Self {
        todo!()
    }
}

fn main() {}
```

I expected to see this happen: *I had expected compilation to succeed*

Instead, this happened: *Compilation fails with the error message below.*

```
error[E0119]: conflicting implementations of trait `std::convert::From<TypeRef<'_, _>>` for type `TypeRef<'_, _>`
  --> src\main.rs:11:1
   |
11 | impl<'a, T: Type> From<T::Ref<'a>> for TypeRef<'a, T> {
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: conflicting implementation in crate `core`:
           - impl<T> From<T> for T;
```

### Meta

`rustc --version --verbose`:
```
rustc 1.58.0-nightly (891ca5f63 2021-11-15)
binary: rustc
commit-hash: 891ca5f63c3b3cfe3939710a728671243e881ed6
commit-date: 2021-11-15
host: x86_64-pc-windows-msvc
release: 1.58.0-nightly
LLVM version: 13.0.0

```

**Comment by tavianator** [comment]
Doesn't need GATs:

```rust
pub trait Type {
    type Ref;
}

pub struct TypeRef<T: Type> {
    r: T::Ref,
}

impl<T: Type> From<T::Ref> for TypeRef<T> {
    fn from(_: T::Ref) -> Self {
        todo!()
    }
}
```

This is intentional.  `T::Ref` could be the same as `TypeRef<T>` and the impls would conflict.

**Comment by davidli2010** [comment]
> 
> 
> Doesn't need GATs:
> 
> ```rust
> pub trait Type {
>     type Ref;
> }
> 
> pub struct TypeRef<T: Type> {
>     r: T::Ref,
> }
> 
> impl<T: Type> From<T::Ref> for TypeRef<T> {
>     fn from(_: T::Ref) -> Self {
>         todo!()
>     }
> }
> ```
> 
> This is intentional. `T::Ref` could be the same as `TypeRef<T>` and the impls would conflict.

In my scenario, the lifetime of T::Ref<'a> is necessary. But you are right, T::Ref<'a> could be the same as TypeRef<T> and the impls would conflict.
