### ISSUE TITLE
Values that need to be dropped are promoted in const / static initializers

### ISSUE THREAD

**Issue by tmiasko** [rust-lang/rust#91009]
For example, promotion succeeds in the example below, although compilation nevertheless fails due to checks for live drops:

```rust
pub const fn id<T>(x: T) -> T { x }
pub const C: () = {
    let _: &'static _ = &String::new();
    // Promotion failed, two errors:
    // ERROR: destructors cannot be evaluated at compile-time
    // ERROR: temporary value dropped while borrowed

    let _: &'static _ = &id(&String::new());
    // Promoted. Only one error:
    // ERROR: destructors cannot be evaluated at compile-time

    let _: &'static _ = &std::mem::ManuallyDrop::new(String::new());
    // Promoted. No errors.
};
```

With `const_precise_live_drops`, checking for live drops is delayed until after the promotion, so the following example compiles successfully:

```rust
#![feature(const_precise_live_drops)]
pub const fn id<T>(x: T) -> T { x }
pub const C: () = {
    let _: &'static _ = &id(&String::new());
};
```

The check for live drops can also be passed by providing a const drop implementation. The following example compiles successfully as well:

```rust
#![feature(const_fn_trait_bound)]
#![feature(const_mut_refs)]
#![feature(const_trait_impl)]
struct Panic;
impl const Drop for Panic { fn drop(&mut self) { panic!(); } }
pub const fn id<T>(x: T) -> T { x }
pub const C: () = {
    let _: &'static _ = &id(&Panic);
};
```

@rustbot label +A-const-eval

**Comment by RalfJung** [comment]
This is very strange. There is only one place in promotion where we treat a `const` different from regular functions:

https://github.com/rust-lang/rust/blob/c9dd1d9983b9a08159c2e3c86071d1a5ef7ebb20/compiler/rustc_const_eval/src/transform/promote_consts.rs#L637

and the only difference is whether we check for the presence of the `#[rustc_promotable]` attribute on a function before promoting it. But even if we [add that attribute](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=ce9cd9534135426884a286f96a0b7df0) promotion still seems to behave differently inside `const` than inside `main`.

@oli-obk any idea what is going on? Could this be due to some difference in how MIR is generated for consts vs regular functions?

**Comment by oli-obk** [comment]
> Could this be due to some difference in how MIR is generated for consts vs regular functions?

I did remove the explicit difference where storage markers were often not generated at all.

What we still have is the fact that `construct_const` differs from `construct_fn` in that we don't wrap the const's body in a scope, but I don't see how that would affect anything, considering that manually putting it into a smaller scope inside the constant (by putting it into a shorter lived block), doesn't affect it.

We'll need to look at the actual MIR generated for these

**Comment by tmiasko** [comment]
The reason I described the issue as applying to const / static initializers, is that there are no existing `rustc_promotable` functions to demonstrate the problem. With custom `rustc_promotable` functions it is possible. Sorry if the title was misleading.

To be effective `rustc_promotable` also needs stability attributes.The attribute also need to be applied to all functions in the promoted code, not just the outermost one.

It was quite a bit of time since I looked at this, but as far as I remember the root problem was complete omission of check for live drops in MIR that construct call operands.

**Comment by tmiasko** [comment]
> To be effective `rustc_promotable` also needs stability attributes.The attribute also need to be applied to all functions in the promoted code, not just the outermost one.

https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=3291dde278a238c06ce81db3decfb294

**Comment by RalfJung** [comment]
Okay, so it is not just a const-time bug then. That code in `main` should not be accepted.
Looks like something is wrong with the handling of nested promotion, where we then fail to properly check for destructors. I never understood what happens with nested promotion...

**Comment by RalfJung** [comment]
This seems pretty bad, we are promoting code in a way that has side-effects (`drop` should be run but isn't).

@eddyb @oli-obk any idea why this happens?

**Comment by eddyb** [comment]
So this is the relevant code that *bans* `&new_string()` today:
https://github.com/rust-lang/rust/blob/dd12cd6dc631b5e964d541d370ca863c2242376c/compiler/rustc_const_eval/src/transform/promote_consts.rs#L219-L257

The problem with that approach is that the check is *once per candidate*.
And so `&id(&new_string())`, only the type of `id(&new_string())` is checked for `Drop`, even though `validate_ref`/`validate_local` gets called for both the temporary for `new_string()` *and*` the one for `id(&new_string())`.

The safest thing would be to move that `self.qualif_local::<qualifs::NeedsDrop>` check into `validate_local` - while `validate_ref` would also work for the example in this issue, I'm not sure we want to be able to promote `&id(NeedsDrop {...}.field)` either, and `validate_local` would catch both.

**Comment by tmiasko** [comment]
> I'm not sure we want to be able to promote `&id(NeedsDrop {...}.field)` either, and `validate_local` would catch both.

Good point. That kind of code leads to even simpler reproducer:

```rust
struct NoisyDrop(&'static str);
impl Drop for NoisyDrop {
    fn drop(&mut self) {
        println!("{}", self.0);
    }
}
fn main() {
    let _: &'static _ = &&(NoisyDrop("drop!"), 0).1;
    // NosiyDrop is not dropped ...
}
```
