### ISSUE TITLE
Tracking Issue for `str::from_utf8_unchecked_mut` as a `const fn`

### ISSUE THREAD

**Issue by WaffleLapkin** [rust-lang/rust#91005]
Feature gate: `#![feature(const_str_from_utf8_unchecked_mut)]`

This is a tracking issue for `str::from_utf8_unchecked_mut` marked as a `const fn`

### Public API

```rust
// core::str

pub const unsafe fn from_utf8_unchecked_mut(v: &mut [u8]) -> &mut str;
```

### Steps / History

- [x] Implementation: #90607
- [ ] Final comment period (FCP)
- [ ] Stabilization PR

### Unresolved Questions

- None yet.

**Comment by workingjubilee** [comment]
We have the option of const-stabilizing this now that https://github.com/rust-lang/rust/issues/57349 has stabilized.

**Comment by dtolnay** [comment]
@rfcbot fcp merge

`const` for https://doc.rust-lang.org/nightly/std/str/fn.from_utf8_unchecked_mut.html
