### ISSUE TITLE
Lifetime in GAT must outlive trait parameters

### ISSUE THREAD

**Issue by ilslv** [rust-lang/rust#91036]
Related to https://github.com/rust-lang/rust/pull/89970

## Code

```rust
#![feature(generic_associated_types)]

trait T<'ctx> {
    type Fut<'out> 
    where 
        'ctx: 'out, 
        Self: 'out;
    
    fn test<'me, 'out>(&'me self, ctx: &'ctx i32) -> Self::Fut<'out>
    where
        'me: 'out,
        'ctx: 'out;
}
```

Basically I want to desugar `async fn`. For this I need to describe `Fut` GAT that lives the smallest of the `'me` and `'ctx`, but I get compiler error with requirement that doesn't really make sense to me.

```
error: Missing required bounds on Fut
 --> src/lib.rs:4:5
  |
4 | /     type Fut<'out> 
5 | |     where 
6 | |         'ctx: 'out, 
7 | |         Self: 'out;
  | |                   ^ help: add the required where clauses: `, 'out: 'ctx`
  | |___________________|
  | 

error: could not compile `playground` due to previous error
```

`'out` cant't outlive `'ctx`.

## Meta

fails on `1.58.0-nightly (2021-11-18 cc946fcd326f7d85d4af)` [Playground]

[Playground]: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=1e3760ee5aea5d551e498b7b14d59319

**Comment by vandenheuvel** [comment]
Do you need a GAT here? Lifetime `'out` outlives everything else. I would expect a GAT lifetime to live shorter than the trait.

**Comment by ilslv** [comment]
@vandenheuvel 

> Lifetime `'out` outlives everything else

Not really. Lifetime `'out` live the shortest of `'me` and `'ctx` lifetimes. This is done by `'me: 'out, 'ctx: 'out` which means: both `'me` and `'ctx` outlive `'out` => `'out` should be shortest of `'me` and `'ctx`

See https://github.com/rust-lang/rust/issues/56238#issuecomment-441736818 for more info

**Comment by jackh726** [comment]
Yeah, this looks weird

**Comment by vandenheuvel** [comment]
Thanks @ilslv, turns out it is possible to code rust for quite a while without properly understanding lifetimes.

**Comment by vorot93** [comment]
Having the same issue with the latest nightlies:

```
pub trait Transaction<'db> {
    type Cursor<'tx, T>: Cursor<'tx, T>
    where
        'db: 'tx,
        Self: 'tx,
        T: Table + 'db + 'tx;
}
```

```
add the required where clauses: `, 'tx: 'db`
```
