### ISSUE TITLE
Addition of struct with same constant generic constraint results in build failure

### ISSUE THREAD

**Issue by benpye** [rust-lang/rust#91123]
I'm not 100% certain that this is different to #89421 but I think it is as this is not the addition of a new generic parameter.

In this case I have two related structs, the outer struct contains some instance of the inner struct, and an implementation of the outer struct with a generic constraint calls a method on the inner struct with the very same constraint, this fails to build with the same `unconstrained generic constant` error. Removing the outer struct solves the error, as does removing the call to `test_method_inner`.

```rust
#![feature(adt_const_params)]
#![feature(generic_const_exprs)]

#[derive(PartialEq, Eq)]
enum LevelEnum {
    Level0,
    Level1
}

struct LevelHierarchy<const LEVEL: LevelEnum>;

trait NextLevelEnum {
    const NEXT_LEVEL: LevelEnum;
}

impl NextLevelEnum for LevelHierarchy<{ LevelEnum::Level0 }> {
    const NEXT_LEVEL: LevelEnum = LevelEnum::Level1;
}

struct StructInner<const LEVEL: LevelEnum>(u64);

struct StructOuter<const LEVEL: LevelEnum>(StructInner<LEVEL>);

impl<const LEVEL: LevelEnum> StructOuter<LEVEL>
where
    LevelHierarchy<LEVEL>: NextLevelEnum,
{
    fn test_method_outer(&self) {
        let inner = &self.0;
        inner.test_method_inner();
    }
}

impl<const LEVEL: LevelEnum> StructInner<LEVEL>
where
    LevelHierarchy<LEVEL>: NextLevelEnum,
{
    fn test_method_inner(
        &self,
    ) -> StructInner<{ LevelHierarchy::<LEVEL>::NEXT_LEVEL }> {
        StructInner(0)
    }
}
```
I saw this locally and also on the nightly compiler on the [Rust playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=9fd8039a36fc39e696eed5ef4463f055) (2021-11-21). The exact error message is:

```
error: unconstrained generic constant
  --> src/lib.rs:30:15
   |
30 |         inner.test_method_inner();
   |               ^^^^^^^^^^^^^^^^^
   |
   = help: try adding a `where` bound using this expression: `where [(); { LevelHierarchy::<LEVEL>::NEXT_LEVEL }]:`
```

**Comment by BoxyUwU** [comment]
Closing because this error is correct, to fix you can add a `struct Evaluatable<const N: LevelEnum>;` and a where clause `where Evaluatable<{ LevelHierarchy::<LEVEL>::NEXT_LEVEL }>:` to `fn test_method_outer`. The diagnostics here are bad but this is tracked in #82509
