### ISSUE TITLE
Ordering of items in left hand navbar is different from main page

### ISSUE THREAD

**Issue by aDotInTheVoid** [rust-lang/rust#91120]
On https://doc.rust-lang.org/1.56.1/std/error/trait.Error.html#provided-methods

![image](https://user-images.githubusercontent.com/28781354/142788462-b13e24ba-3c48-4666-a110-3acdefca8a9e.png)

Here one is in alphabetical order, the other is in source order. 

(This also happens on nightly, but I'm giving a stable link so it doesnt change

This also happens for other headings (eg Implementations) 

@rustbot modify labels: +A-rustdoc-ui +T-rustdoc

**Comment by aDotInTheVoid** [comment]
Prehaps the solution to this and #91118 is to build the left bar at the same time as the main page, instead of seperatly.

I think this would make things much cleaner

**Comment by jyn514** [comment]
This is intentional, to make the sidebar more like a table of contents.

I think any changes in this area need either an FCP or RFC, I'm very uncomfortable just changing it because some people find it surprising because everything here has a ton of tradeoffs and makes some people more unhappy.

**Comment by aDotInTheVoid** [comment]
Fair enough, although a toc is in the same order as content, but it works well as and index instead

**Comment by jsha** [comment]
@aDotInTheVoid FWIW, I agree with you - it would be conceptually cleaner for the sidebar to act more like a TOC by being in the same order as the content. But that would mean either the sidebar would have to be non-alphabetical (hard to search for items), or the content would also have to be alphabetical. But having the content in order by appearance in the source is useful so crate authors can group related methods together, and put the most important methods (like constructors) at the top of the documentation, for people to read it in order.

I'd love to find a way to make the sidebar act more TOC-like while still preserving those use cases, but haven't thought of a good way so far.
Or another I
