### ISSUE TITLE
[ER] cfg(overflow_checks)

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust#91130]
An enhancement request discussed here:
https://users.rust-lang.org/t/detecting-overflow-checks/67698/

(That thread also contains a hacky solution by Yandros).

I propose to add a config like this:

#[cfg(overflow_checks)]

I would like to use it to enable/disable lines of code that perform safe unsafe "as" casts replacing them with casts when I compile with debug builds or with release builds compiled with "-C overflow-checks".

**Comment by schuelermine** [comment]
I’d also be interested in this.

**Comment by AngelicosPhosphoros** [comment]
Tracking issue: https://github.com/rust-lang/rust/issues/111466
