### ISSUE TITLE
Windows11 Crashes on Ubuntu installed through microsoft store while installing Rust

### ISSUE THREAD

**Issue by rrahulraman** [rust-lang/rust#91138]
I tried this code:

```
curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh
```

I expected to see this happen: install rust for ubuntu on Windows (downloaded from Microsoft store, windows 11)

Instead, this happened: windows crashed with memory exception. and rust is not properly installed
![Screenshot 2021-11-23 000126](https://user-images.githubusercontent.com/59053908/142916013-bb96cfeb-5e7d-42d1-b121-41ace9bc12fc.png)

### Meta

`rustc --version --verbose`:
```
latest version
```
</details>

**Comment by SadiinsoSnowfall** [comment]
I was unable to reproduce the issue, could you indicate the exact version of Windows 11 and the Ubuntu WSL distribution you are using ?

**Comment by rrahulraman** [comment]
Ubuntu 20.04.3 LTS (GNU/Linux 4.4.0-22000-Microsoft x86_64)
OS Name	Microsoft Windows 11 Home Single Language
Version	10.0.22000 Build 22000

**Comment by mati865** [comment]
Judging by the kernel version I guess it's WSL 1, works for me in WSL 2 on Windows 10 and Windows 11.
In any case this crash has nothing to do with Rust, either it's faulty hardware or Windows bug which should be reported to Microsoft.

**Comment by rrahulraman** [comment]
Yes updating to WSL 2 solved the problem, Thanks.
