### ISSUE TITLE
ARM: packed-struct-vec

### ISSUE THREAD

**Issue by sanxiyn** [rust-lang/rust#9116]
`packed-struct-vec` rpass test fails with "Bus error". Could be an LLVM problem, also could be a Rust problem.

**Comment by steveklabnik** [comment]
Given that android is tested nowadays, it looks to me like this just got lost in the shuffle. Let me know if closing this is wrong for some reason.

**Comment by richo** [comment]
@steveklabnik This looks like it needs to be open, it's ignored on android: https://github.com/mozilla/rust/blob/master/src/test/run-pass/packed-struct-vec.rs
