### ISSUE TITLE
x86_64-unknown-linux-musl: backport musl bug fixes or use new `1.2` version?

### ISSUE THREAD

**Issue by haraldh** [rust-lang/rust#91178]
Seems like x86_64-unknown-linux-musl is built with `musl-1.1.24`.

For this version I hit a bug, which is fixed with
https://git.musl-libc.org/cgit/musl/commit/?id=cb5babdc8d624a3e3e7bea0b4e28a677a2f2fc46 
for the renamed `src/malloc/malloc.c` file.

What is the recommended procedure here?

Try to persuade upstream to release a fixed `musl-1.1.25` or drive rust to switch to `musl-1.2.x`?

**Comment by wesleywiser** [comment]
Ideally, we would upgrade to the `1.2` series. It looks like there is a PR in progress to update the libc crate which is probably a dependency before we can perform the upgrade here (https://github.com/rust-lang/libc/pull/2088).

**Comment by Xuanwo** [comment]
Also related to https://github.com/tikv/pprof-rs/issues/142
