### ISSUE TITLE
rustdoc: don't hyperlink square brackets in method signatures

### ISSUE THREAD

**Issue by jsha** [rust-lang/rust#91173]
For example, in https://doc.rust-lang.org/nightly/std/primitive.slice.html#method.get, the method signature contains a `[T]`:

![image](https://user-images.githubusercontent.com/220205/143210616-7fc0c6a4-64e7-451c-98d4-e9482e9bb11b.png)

In that method signature, all four instances of `[` or `]` are colored and hyperlinked (to https://doc.rust-lang.org/nightly/std/primitive.slice.html).

These hyperlinks aren't very useful. For one thing, they present a very tiny click target, which is bad UX. For another thing, it's quite rare to be reading Rust documentation and needs to clarify that the `[` and `]` indicate a slice. We should remove these and save a little bit of page size.

**Comment by eggyal** [comment]
I've actually found those links to the slice docs quite useful, on a number of occasions.
