### ISSUE TITLE
rustdoc: Can't click any links in methods that use `details`

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#91184]
For example, I can't click any links (i.e., when I click them, nothing happens) in [this method's](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_ast_lowering/struct.LoweringContext.html#method.lower_expr_try_block) header. Likewise, I can't click any links for `make_async_expr`, but I **can** click links in `wrap_in_try_constructor`, which has no `details` tag.

This same behavior occurs in the `std` docs, though every `std` method is documented and thus has a `details` tag, so there's no comparison to non-`details` methods.

This is a regression in nightly 1.58.0. I'm using Safari on macOS; I don't know if this reproduces on other browsers.

**Comment by jyn514** [comment]
This is probably https://github.com/rust-lang/rust/pull/91103; I don't know why that change was made or if this is intentional.

cc @Manishearth @jsha

**Comment by camelid** [comment]
I can't imagine this part of the behavior is intentional, since it breaks a lot of rustdoc's UI.

**Comment by camelid** [comment]
We really need more GUI tests so this can't happen again...

**Comment by jsha** [comment]
Can confirm, that wasn't intentional. I manually checked during development to make sure that wouldn't happen, but it must have broken. Sorry for that, and sorry for not adding a GUI test for it. I'll post a fix in a moment.

**Comment by camelid** [comment]
Assigning priority as [discussed](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2391184.20rustdoc.3A.20Can't.20click.20any.20links.20in.20methods.20that.20use.20.60.E2.80.A6) in the prioritization working group.
