### ISSUE TITLE
rustdoc: Section icon color and font-weight has changed on nightly

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#91196]
I don't know for sure whether this is intentional, but the new icon styling is a bit more distracting IMO.

### nightly (new)

![image](https://user-images.githubusercontent.com/37223377/143309349-3ad44060-0f12-4128-8e7b-969d8ee6aa54.png)

### beta (old)

![image](https://user-images.githubusercontent.com/37223377/143309339-01a63005-34ec-426e-9582-8b03c1f1c0df.png)

**Comment by camelid** [comment]
cc @rust-lang/rustdoc

**Comment by GuillaumeGomez** [comment]
I can't find the PR but we changed the size. Do you have it @jsha maybe?

**Comment by jsha** [comment]
The font-weight increase probably came from https://github.com/rust-lang/rust/pull/90089/files, since we increased the font weight of the variant name headings (e.g. Slice in this example).

The font-color change comes from #91102. That's accidental and should definitely be fixed. @camelid if we fix the font color is that sufficient, or do you also think the variant name headings should be reduced in weight? FWIW I think they should stay bold to match other headings, like method names.

**Comment by camelid** [comment]
> @camelid if we fix the font color is that sufficient, or do you also think the variant name headings should be reduced in weight? FWIW I think they should stay bold to match other headings, like method names.

I'm ambivalent about the variant name's font weight, but I definitely think the section icon should be reduced.

**Comment by jsha** [comment]
> I'm ambivalent about the variant name's font weight, but I definitely think the section icon should be reduced in weight.

That would be a big departure from practice elsewhere in rustdoc: the section icon is always the same weight as the heading it decorates. For instance, look at section headings and method headings.

**Comment by camelid** [comment]
> > I'm ambivalent about the variant name's font weight, but I definitely think the section icon should be reduced in weight.
> 
> That would be a big departure from practice elsewhere in rustdoc: the section icon is always the same weight as the heading it decorates. For instance, look at section headings and method headings.

Really? This section icon looks way more bold than any other section icon I've seen. The variant name itself also looks a higher font weight, though maybe that part's an optical illusion.

**Comment by jsha** [comment]
> This section icon looks way more bold than any other section icon I've seen. The variant name itself also looks a higher font weight, though maybe that part's an optical illusion.

Both the section icon and the variant name are font-weight 600. To verify: In Chrome, right-click, inspect element, click over to the Computed tab on the right, scroll down to font-weight.

For comparison, do the same on the method heading at https://doc.rust-lang.org/nightly/std/string/struct.String.html#method.as_bytes. Also font-weight 600. An important difference, though: method headings have a font-size of 1em (16px), while variant headings have a font-size of 1.1em (17.6px). Also the variant headings have a lot more vertical space surrounding them, which probably makes them look even bigger than that.

**Comment by camelid** [comment]
Ok, the color has been fixed now. The font-weight has not been changed, so we need to decide about that.

**Comment by camelid** [comment]
> For comparison, do the same on the method heading at https://doc.rust-lang.org/nightly/std/string/struct.String.html#method.as_bytes. Also font-weight 600. 

Yeah, but inherent methods don't have section icons :)

I think I'm okay with accepting the font-weight + size of the variant section icon for consistency. This kind of ties into the discussion about making rustdoc consistent about using section icons vs self-links (cc https://github.com/rust-lang/rust/issues/90331#issuecomment-952459062).
