### ISSUE TITLE
Compiler cannot remove unneccessary loop in case of unwrap_unchecked and Vec collect() optimization

### ISSUE THREAD

**Issue by AngelicosPhosphoros** [rust-lang/rust#91194]
I tried this code:

```rust
pub fn unwrap_all(vv: Vec<Option<Box<i32>>>)->Vec<Box<i32>>{
    vv
        .into_iter()
        .map(|x| unsafe{
            x.unwrap_unchecked()
        })
        .collect()
}
```

I expected to see this happen: code compiles into noop essentially, like transmute.
<details><summary>Expected code</summary>

```asm
example::unwrap_all_transmute:
        mov     rax, rdi
        mov     rcx, qword ptr [rsi + 16]
        mov     qword ptr [rdi + 16], rcx
        movups  xmm0, xmmword ptr [rsi]
        movups  xmmword ptr [rdi], xmm0
        ret
```

</details>

Instead, this happened: code iterates over the vec without toching real backing buffer. This is a loop without side effects so it should be removed by LLVM.

<details><summary>Generated code</summary>

```asm

example::unwrap_all:
        mov     rax, rdi
        mov     rcx, qword ptr [rsi]
        mov     r8, qword ptr [rsi + 8]
        mov     rdi, qword ptr [rsi + 16]
        mov     rsi, rcx
        test    rdi, rdi
        je      .LBB0_8
        lea     r9, [8*rdi - 8]
        mov     edx, r9d
        shr     edx, 3
        add     edx, 1
        and     rdx, 7
        je      .LBB0_2
        neg     rdx
        mov     rsi, rcx
.LBB0_4:
        add     rsi, 8
        inc     rdx
        jne     .LBB0_4
        cmp     r9, 56
        jae     .LBB0_6
        jmp     .LBB0_8
.LBB0_2:
        mov     rsi, rcx
        cmp     r9, 56
        jb      .LBB0_8
.LBB0_6:
        lea     rdx, [rcx + 8*rdi]
.LBB0_7:
        add     rsi, 64
        cmp     rsi, rdx
        jne     .LBB0_7
.LBB0_8:
        sub     rsi, rcx
        sar     rsi, 3
        mov     qword ptr [rax], rcx
        mov     qword ptr [rax + 8], r8
        mov     qword ptr [rax + 16], rsi
        ret

```
</details>

### Meta

`rustc --version --verbose`:
```
rustc 1.58.0-nightly (936f2600b 2021-11-22)
```

[Godbolt link with code](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:14,fontUsePx:'0',j:2,lang:rust,selection:(endColumn:28,endLineNumber:10,positionColumn:28,positionLineNumber:10,selectionStartColumn:28,selectionStartLineNumber:10,startColumn:28,startLineNumber:10),source:'pub+fn+unwrap_all(vv:+Vec%3COption%3CBox%3Ci32%3E%3E%3E)-%3EVec%3CBox%3Ci32%3E%3E%7B%0A++++vv%0A++++++++.into_iter()%0A++++++++.map(%7Cx%7C+unsafe%7B%0A++++++++++++x.unwrap_unchecked()%0A++++++++%7D)%0A++++++++.collect()%0A%7D%0A%0Apub+fn+unwrap_all_transmute(vv:+Vec%3COption%3CBox%3Ci32%3E%3E%3E)-%3EVec%3CBox%3Ci32%3E%3E%7B%0A++++unsafe%7Bstd::mem::transmute(vv)%7D%0A%7D%0A'),l:'5',n:'0',o:'Rust+source+%232',t:'0')),header:(),k:49.22784727934294,l:'4',m:100,n:'0',o:'',s:0,t:'0'),(g:!((h:compiler,i:(compiler:nightly,filters:(b:'0',binary:'1',commentOnly:'0',demangle:'0',directives:'0',execute:'1',intel:'0',libraryCode:'0',trim:'1'),flagsViewOpen:'1',fontScale:14,fontUsePx:'0',j:1,lang:rust,libs:!(),options:'-Copt-level%3D3',selection:(endColumn:1,endLineNumber:1,positionColumn:1,positionLineNumber:1,selectionStartColumn:1,selectionStartLineNumber:1,startColumn:1,startLineNumber:1),source:2,tree:'1'),l:'5',n:'0',o:'rustc+nightly+(Rust,+Editor+%232,+Compiler+%231)',t:'0')),header:(),k:50.772152720657076,l:'4',m:100,n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4)

**Comment by the8472** [comment]
dup of #79308

**Comment by AngelicosPhosphoros** [comment]
Yeah, forgot about those.
