### ISSUE TITLE
The first heading in all doc comments have left margin

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/rust#91200]
Which looks weird as you can see:

![Screenshot from 2021-11-24 22-21-15](https://user-images.githubusercontent.com/3050060/143314551-df3f5495-d9db-4c96-9fe2-7d74ae634fe4.png)

It's even more weird on enum variants:

![Screenshot from 2021-11-24 22-24-04](https://user-images.githubusercontent.com/3050060/143314740-021ab83c-1127-4e95-9fe9-730fc1e67037.png)

I'll fix it tomorrow.

**Comment by camelid** [comment]
Yeah, this has been bothering me for a while 👍
