### ISSUE TITLE
Newlines don't cause a paragraph break when mixing `#[doc]` and `///`

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#91201]
See the test added in #91199. This code:

```rust
#[doc = "Hello world!\n\n"]
/// Goodbye!
#[doc = "  Hello again!\n"]
pub struct S1;
```

renders as:

> Hello world! Goodbye! Hello again!

rather than the expected:

> Hello world!
>
> Goodbye! Hello again!

Meanwhile, changing some `#[doc]`s to `///`s and vice versa causes it to render as expected.

cc @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
This is the expected behaviour actually: it converts the `///` into a `#[doc = "..."]` directly. So if you don't put empty doc comments between, it's as expected.

**Comment by camelid** [comment]
But why are the newlines in the `#[doc = "..."]` stripped?

**Comment by GuillaumeGomez** [comment]
Oh, I didn't see that. I think it's because we use `trim` to remove whistespaces which also removes backlines. We should instead merge all doc comments before doing anything.
