### ISSUE TITLE
can't find crate std in rustc

### ISSUE THREAD

**Issue by JIVIN0902** [rust-lang/rust#91228]
```
For more information about this error, try `rustc --explain E0463`.
error[E0463]: can't find crate for `std`
 --> /Users/jivinvaidya/.cargo/registry/src/github.com-1ecc6299db9ec823/lazy_static-1.4.0/src/inline_lazy.rs:9:1
  |
9 | extern crate std;
  | ^^^^^^^^^^^^^^^^^ can't find crate
  |
  = note: the `bpfel-unknown-unknown` target may not support the standard library
  = help: consider building the standard library from source with `cargo build -Zbuild-std`

```

I am unable to compile the code due to this error. Any help is appreciated. Thanks

**Comment by hkratz** [comment]
This is not an internal compiler error, just a normal compiler error message with the helpful note that the target you are compiling for, `bpfel-unknown-unknown`, does not support the standard library. Which is true, see #79608. The `lazy_static` crate does support building for nostd targets with the `spin_no_std` feature but I am not sure if that helps you. What are you trying to accomplish? 

@rustbot label -I-ICE

**Comment by hkratz** [comment]
Oh, is this about [solana](https://github.com/solana-labs/solana)? Then you are probably better of asking in their project for help.

**Comment by nagisa** [comment]
I'm going to take liberty to close this issue because there's little we can do in terms of helping or improving rustc itself here, I feel.
