### ISSUE TITLE
rustdoc: Header color has regressed

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#91304]
They used to be blue and are now black. I don't think this change was intentional, although we have been thinking about migrating more headers to be black recently. I think this regressed very recently, since I probably would have noticed it otherwise.

![image](https://user-images.githubusercontent.com/37223377/143724718-d00c1c81-e8a6-445b-ae07-ff7dd21bfef3.png)

**Comment by camelid** [comment]
I wonder if this was caused by #91062 or #91223? Those were both merged recently, though the second one doesn't seem like it could have changed colors.

cc @jsha @GuillaumeGomez

**Comment by jsha** [comment]
This regressed in #91179, which added `.section-header a` as one of the rules for an anchor to be styled black.

The goal with that change was to make the section headings on module pages black (e.g. https://doc.rust-lang.org/nightly/std/index.html#macros). Those have `class="section-header"`. However, headings generated from Markdown in a docblock also have `class="section-header"`.

I think the right short-term fix is:
 - Section headings on module pages get `class="small-section-header"`, like their peers on other pages.
 - Remove the CSS rule for `.section-header a` to be black.
 
It's not really clear to me why Markdown gets `section-header`, and Rustdoc-generated headings get `small-section-header`, particularly given that the Rustdoc headings are almost always bigger. Probably we should rename these to `docblock-prose-heading` and `rustdoc-prose-heading`.

**Comment by camelid** [comment]
@jsha Since you figured out a way to fix this regression, do you want to assign yourself and open a PR with the fix?

**Comment by jsha** [comment]
Will do.
