### ISSUE TITLE
Dynamic linkage to C library failing because static library wasn't found.

### ISSUE THREAD

**Issue by RpxdYTX** [rust-lang/rust#91322]
I tried this code:

```rust
// lib.rs:

#[cfg(test)]
mod tests;

// just a test, so no *-sys crate
pub mod sys {
    extern {
        pub fn my_func() -> i32;
    }
}

// build.rs:

fn main() {
    println!("cargo:rustc-link-lib=dylib=my_lib");
    println!(r"cargo:rustc-link-search=native=path/to/my/lib");
}

// tests.rs

#[test]
fn my_function() { unsafe { assert_eq!(3, crate::sys::my_func(); } }
```

my_lib (C code)
```c
#define EXPORT __declspec(dllexport)

EXPORT int my_func(void) { return 3; }
```

I expected to see this happen: Test passing

Instead, this happened: when the static lib is in the path the external symbols are unresolved (i mean, dllexport exports code in a **_dll_**), when only the dll is in the path, `link.exe` says that it could not find my_lib._**lib**_. 

### Meta

`rustc --version --verbose`:
```
rustc 1.56.1 (59eed8a2a 2021-11-01)
binary: rustc
commit-hash: 59eed8a2aac0230a8b53e89d4e99d55912ba6b35
commit-date: 2021-11-01
host: x86_64-pc-windows-msvc
release: 1.56.1
LLVM version: 13.0.0

// Nothing different in nightly or beta
```

<details><summary>Backtrace</summary>
<p>

```
// Not a runtime error, so no backtrace, even with the env variable set.
```

</p>
</details>

**Comment by SNCPlay42** [comment]
This is how linking works on Windows; you need to provide a `.lib` file to the linker to link with a DLL.

[Microsoft Documentation](https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-creation#creating-an-import-library)

**Comment by RpxdYTX** [comment]
Thanks, after seeing that glfw works this way i started doing some real research.
