### ISSUE TITLE
rustdoc: Read and Write show up as notable traits on &mut [u16]

### ISSUE THREAD

**Issue by jsha** [rust-lang/rust#91347]
https://rustdoc.crud.net/jsha/fewer-colors/std/primitive.char.html#method.encode_utf16

![image](https://user-images.githubusercontent.com/220205/143809753-3ae4eeae-06ca-4ff4-951d-894e227c15d6.png)

**Comment by camelid** [comment]
@notriddle there are several issues which I think are duplicates of this and thus fixed by your change, but I'm not certain. Can you let me know if these can be closed?

- #80737
- #76590
- #78160
