### ISSUE TITLE
doctests reject extra semicolons as of nightly-2021-11-21 (and beta)

### ISSUE THREAD

**Issue by TheBlueMatt** [rust-lang/rust#91398]
The following fails to compile in doctests as Rust 2015 on Beta and latest nightly, but passes doctests fine on stable:

```
//! ```
//! # struct FakeLogger {};
//! #
//! # fn main() {
//! eprintln!("HI");
//! # }
//! ```

fn main() {
    println!("Hello, world!");
}
```

Probably related to #91014, #91026, and #91134.

**Comment by jyn514** [comment]
@TheBlueMatt I don't think this is a bug, that's invalid code. Rustdoc just didn't happen to catch it before.
```
error: expected item, found `;`
 --> src/lib.rs:2:21
  |
2 | struct FakeLogger {};
  |                     ^ help: remove this semicolon
  |
  = help: braced struct declarations are not followed by a semicolon

error: aborting due to previous error
```

**Comment by jyn514** [comment]
If you move it inside a function, the test correctly passes.
```rust
//! ```
//! fn f() {
//! # struct FakeLogger {};
//! }
//! #
//! # fn main() {
//! eprintln!("HI");
//! # }
//! ```
```

**Comment by TheBlueMatt** [comment]
Oh, duh, yes, you're totally right, I just saw a compile failure on new rustc and not old rustc and immediately assumed it was a rustc bug. Indeed, this is our bug, thanks.
