### ISSUE TITLE
#[cfg] guards seem to have no effect on asm!

### ISSUE THREAD

**Issue by ketsuban** [rust-lang/rust#91415]
I tried this code:

```rust
#[cfg(not(test))]
global_asm!(include_str!("init.s"));
```

I expected the assembly to be ignored when running `cargo test`, but instead I get errors (it's ARM assembly and I'm running `cargo test` on x86_64) indicating that it's still being processed.

I tried putting my code in naked functions instead but the same thing happened.

**Comment by asquared31415** [comment]
This does not seem to be an issue in the latest nightly (2021-11-30 207c80f10) as demonstrated on [the playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=c2f420bb1f19fdb9b6298d7cbd818588)
