### ISSUE TITLE
Tracking Issue for mul_add being absent from std::simd::Simd

### ISSUE THREAD

**Issue by hanabi1224** [rust-lang/rust#91422]
Feature gate: `#![feature(portable_simd )]`

[mul_add](https://rust-lang.github.io/portable-simd/core_simd/simd/struct.Simd.html#method.mul_add) presents under core_simd::Simd in [rust-lang/portable-simd](https://github.com/rust-lang/portable-simd) but is missing from [std::simd::Simd](https://doc.rust-lang.org/nightly/std/simd/struct.Simd.html)

Below code ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=e07059be98be988d296da6676429b62f)) does not compile

> error[E0599]: no method named `mul_add` found for struct `Simd` in the current scope
 --> src/main.rs:8:15
  |
8 |     let _ = a.mul_add(b, c);
  |               ^^^^^^^ method not found in `Simd<f64, 8_usize>`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `playground` due to previous error

### Public API

```rust
#![feature(portable_simd)]

use std::simd::f64x8;
// This works
// use core_simd::f64x8;

fn main() {
    let a = f64x8::splat(0f64);
    let b = f64x8::splat(0f64);
    let c = f64x8::splat(0f64);
    let _ = a.mul_add(b, c);
}
```

### Steps / History

- [ ] Implementation: #...
- [ ] Final comment period (FCP)
- [ ] Stabilization PR

### Unresolved Questions

- None yet.

**Comment by workingjubilee** [comment]
Please `use std::simd::StdFloat;` for now.
