### ISSUE TITLE
`try_reserve_exact` documentation says to "Prefer `reserve`"

### ISSUE THREAD

**Issue by 8573** [rust-lang/rust#91473]
The documentation comments of the three `try_reserve_exact` methods [stabilized today in 1.57.0](https://blog.rust-lang.org/2021/12/02/Rust-1.57.0.html#stabilized-apis) (in `Vec`, `String`, and `VecDeque`) all have the same note as the corresponding aborting method `reserve_exact`:
> Prefer `reserve` if future insertions are expected.

For the fallible `try_reserve_exact` methods, should that say `try_reserve` rather than `reserve`?

**Comment by AngelicosPhosphoros** [comment]
This fixed on nightly.

**Comment by yaahc** [comment]
fixed by https://github.com/rust-lang/rust/pull/91547
