### ISSUE TITLE
nightly-2021-12-02 to nightly-2021-12-03 regression (PR #91354): auto-deref on `Cow` does not seem to work anymore in all circumstances

### ISSUE THREAD

**Issue by sdroege** [rust-lang/rust#91489]
### Code

See https://github.com/gtk-rs/gtk-rs-core/blob/master/glib-macros/tests/test.rs#L290

This fails with the latest nightly with (run `cargo test` inside the `glib-macros` directory).

```
error[E0599]: no method named `as_str` found for enum `Cow<'static, VariantTy>` in the current scope
   --> glib-macros/tests/test.rs:290:48
    |
290 |     assert_eq!(Variant1::static_variant_type().as_str(), "(si)");
    |                         
```

Simplified code from `gtk-rs` / `glib` which works without problems for some reason so I'm not entirely sure what causes it:

<details>

```rust
pub struct VariantType;
pub struct VariantTy;

impl Borrow<VariantTy> for VariantType {
    fn borrow(&self) -> &VariantTy {
        todo!()
    }
}

impl ToOwned for VariantTy {
    type Owned = VariantType;

    fn to_owned(&self) -> VariantType {
        todo!()
    }
}

impl VariantTy {
    pub fn as_str(&self) -> &str {
        todo!()
    }
}

let x = Cow::Owned(VariantType);
println!("{}", x.as_str());
```

</details>

### Version it worked on

It most recently worked on: 2021-12-02

### Version with regression

`rustc --version --verbose`:

```
rustc 1.59.0-nightly (acbe4443c 2021-12-02)
binary: rustc
commit-hash: acbe4443cc4c9695c0b74a7b64b60333c990a400
commit-date: 2021-12-02
host: x86_64-unknown-linux-gnu
release: 1.59.0-nightly
LLVM version: 13.0.0
```

(note that this is actually the one from today, 2021-12-03, but there's an off-by-one in the version information)

Running `cargo bisect-rustc` yields:

```
searched nightlies: from nightly-2021-12-01 to nightly-2021-12-03
regressed nightly: nightly-2021-12-03
searched commits: from https://github.com/rust-lang/rust/commit/48a5999fceeea84a8971634355287faa349909d4 to https://github.com/rust-lang/rust/commit/acbe4443cc4c9695c0b74a7b64b60333c990a400
regressed commit: https://github.com/rust-lang/rust/commit/18bb8c61a975fff6424cda831ace5b0404277145
```

Which would be this PR: https://github.com/rust-lang/rust/pull/91354 (CC @fee1-dead).

@rustbot modify labels: +regression-from-stable-to-nightly -regression-untriaged

**Comment by spastorino** [comment]
would be nice if we can have a minimal test case for this, so we can reintroduce @fee1-dead changes again being sure that this won't be an issue again.

**Comment by sdroege** [comment]
Yeah I tried but I don't see the difference between my (incomplete) testcase above and the real code that fails :)

**Comment by SNCPlay42** [comment]
Reduced: ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=9da7e29ab9cef0efca2e79522928ad63))

```rust
use std::borrow::Borrow;
use std::borrow::Cow;

pub trait StaticVariantType {
    fn static_variant_type() -> Cow<'static, VariantTy> {
        unimplemented!()
    }
}

impl StaticVariantType for () {}

pub struct VariantType {}
pub struct VariantTy {}

impl Borrow<VariantTy> for VariantType {
    fn borrow(&self) -> &VariantTy {
        unimplemented!()
    }
}

impl ToOwned for VariantTy {
    type Owned = VariantType;
    fn to_owned(&self) -> VariantType {
        unimplemented!()
    }
}

impl VariantTy {
    pub fn as_str(&self) -> () {}
}

static _TYP: () = {
    let _ = || {
        let typ = <() as StaticVariantType>::static_variant_type();
        typ.as_str();
    };
};
```

The existence of `_TYP` seems to cause `as_str` to not be found on `Cow<VariantTy>` everywhere in the crate, i.e. if you add a function like

```rust
fn foo(x: Cow<'static, VariantTy>) {
    x.as_str();
}
```

It will error iff `_TYP` is present.

**Comment by spastorino** [comment]
@SNCPlay42 do you want to send a PR with that test case? cc me and I can merge it. Would need to sit on top of this https://github.com/rust-lang/rust/pull/91491 but it will be on master soon.

**Comment by fee1-dead** [comment]
I would imagine this error is because of caching still. Because the only const impl in the standard library with a `~const` bound is the `deref` method on `Cow`. Looking very similar to https://github.com/rust-lang/rust/issues/89432#issuecomment-932539620.

**Comment by SNCPlay42** [comment]
>I think this is a general problem with closures in consts

FYI the closure is only there to make this work on stable (and because the original crate had it), [this version](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=a302cc7e8af8d6da301fa4fd729af4f7) has the same problem:

```rust
#![feature(const_deref)]
#![feature(const_trait_impl)]

use std::borrow::Borrow;
use std::borrow::Cow;

pub struct VariantType {}
pub struct VariantTy {}

impl Borrow<VariantTy> for VariantType {
    fn borrow(&self) -> &VariantTy {
        unimplemented!()
    }
}

impl ToOwned for VariantTy {
    type Owned = VariantType;
    fn to_owned(&self) -> VariantType {
        unimplemented!()
    }
}

impl VariantTy {
    pub const fn as_str(&self) -> () {}
}

static _TYP: () = {
    Cow::Borrowed(&VariantTy {}).as_str();
};

fn main() {
    Cow::Borrowed(&VariantTy {}).as_str()
}
```

**Comment by fee1-dead** [comment]
That is expected to not work because the `impl` of `Deref` on `Cow` is expressed like this:

```rust
#[stable(feature = "rust1", since = "1.0.0")]
#[rustc_const_unstable(feature = "const_deref", issue = "88955")]
impl<B: ?Sized + ToOwned> const Deref for Cow<'_, B>
where
    B::Owned: ~const Borrow<B>,
```

Your code is in a const context, and the trait bounds are actually unsatisfied.

**Comment by SNCPlay42** [comment]
It's odd that it compiles on yesterday's compiler then (per [godbolt](https://rust.godbolt.org/z/x6drjaaaK)) - I guess `~const` bounds aren't fully implemented?

On the current nightly it errors with the same ``no method named `as_str` found for enum `Cow` in the current scope`` message and causes all other calls (in non-const contexts) to produce the same error, which is what makes me think the closure itself isn't the problem but just necessary to make the code compile.

**Comment by fee1-dead** [comment]
umm, how do I explain this 😅

We have a cache for whether trait bounds satisfy for a given type for performance, but a bug causes the compiler to treat a closure's body inside const contexts as const specifically for solving whether trait bounds satisfy (rustc_trait_selection). I think adding a call *before* the usage in `static` will not error.

**Comment by fee1-dead** [comment]
Actually, the closure in const is a bug introduced by the PR that caused the regression.

**Comment by apiraino** [comment]
Assigning priority as discussed in the [Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2391489.20nightly-2021-12-02.20to.20nightly-2021-12-03.20regression.20.E2.80.A6) of the Prioritization Working Group.

@rustbot label -I-prioritize +P-high
