### ISSUE TITLE
`Vec::retain()` is significantly slower than `into_iter().filter().collect()`

### ISSUE THREAD

**Issue by kageru** [rust-lang/rust#91497]
I noticed today that using `Vec::retain` is much slower than filtering and allocating a new Vector.
I realize the former is probably more memory efficient, but I still found it surprising that it would be that much slower (or really slower at all).

When testing with this code:
```rs
#![feature(test)]
extern crate test;

fn main() {
    let xs: Vec<i32> = (0..1000).collect();
    assert_eq!(even_with_retain(xs.clone()), even_with_filter(xs.clone()));
}

pub fn even_with_retain(mut xs: Vec<i32>) -> Vec<i32> {
    xs.retain(|x| x & 1 == 0);
    xs
}

pub fn even_with_filter(xs: Vec<i32>) -> Vec<i32> {
    xs.into_iter().filter(|x| x & 1 == 0).collect()
}

#[bench]
fn bench_retain(b: &mut test::Bencher) {
    let xs: Vec<i32> = (0..1000).collect();
    b.iter(|| assert_eq!(even_with_retain(test::black_box(xs.clone())).len(), 500));
}

#[bench]
fn bench_filter_collect(b: &mut test::Bencher) {
    let xs: Vec<i32> = (0..1000).collect();
    b.iter(|| assert_eq!(even_with_filter(test::black_box(xs.clone())).len(), 500));
}
```
on 1.59.0-nightly (48a5999fc 2021-12-01), I get these benchmark results:
```
test bench_filter_collect ... bench:         383 ns/iter (+/- 4)
test bench_retain         ... bench:       1,891 ns/iter (+/- 17)
```
on a Ryzen 5900X running Linux. Testing on a different machine (Xeon E3-1271 v3), I get similar numbers:
```
test bench_filter_collect ... bench:         498 ns/iter (+/- 29)
test bench_retain         ... bench:       1,800 ns/iter (+/- 44)
```

`Vec::retain` seemed like the obvious choice to me, so it being slower is either a bug or should be documented somewhere.

[Godbolt](https://godbolt.org/z/M199d5Gz8)

**Comment by BluBb-mADe** [comment]
i7 8700k windows 10
```
test bench_filter_collect ... bench:       1,038 ns/iter (+/- 48)
test bench_retain         ... bench:       1,316 ns/iter (+/- 19)
```
Not as big of a difference but still apparent.

**Comment by kageru** [comment]
Setting `lto = true` makes the disparity even bigger for me:
```
test bench_filter_collect ... bench:         199 ns/iter (+/- 6)
test bench_retain         ... bench:       1,878 ns/iter (+/- 26)
```

**Comment by the8472** [comment]
It looks like `retain` is optimized for small or large probabilities of keeping elements, i.e. long runs of elements that will be either kept or deleted. `into_iter().filter().collect()` on the other hand just reads elements one by one, filters them and writes out those that passed, i.e. it does not care about runs.

Since the test-case here drops every second element it's the worst possible case for `retain`, possibly even worse than random selection (since random clusters may have runs).

**Comment by hkratz** [comment]
There is something weird going, because if you put a copy of the current `retain()` implementation in the source file it is much faster:
```
test bench_filter_collect ... bench:         307 ns/iter (+/- 12)
test bench_my_retain      ... bench:         431 ns/iter (+/- 3)
test bench_retain         ... bench:       1,999 ns/iter (+/- 7)
```
[Godbolt](https://godbolt.org/z/ne4eYPao1)

**Comment by the8472** [comment]
You're not copying the most recent version of retain. `process_one` has gained a const  bool parameter in #88060 and thus gets instantiated in two flavors.

https://github.com/rust-lang/rust/blob/ff2439b7b9bafcfdff86b7847128014699df8442/library/alloc/src/vec/mod.rs#L1524-L1565

**Comment by BluBb-mADe** [comment]
I tried a few scenarios that should heavily favor `retain` but the effect remains.
`|x| *x == 1`
```
test bench_filter_collect ... bench:         284 ns/iter (+/- 18)
test bench_retain         ... bench:       1,338 ns/iter (+/- 55)
```
`|x| *x != 1`
```
test bench_filter_collect ... bench:         413 ns/iter (+/- 130)
test bench_retain         ... bench:       1,369 ns/iter (+/- 28)
```
`|x| *x != 1`
```
test bench_filter_collect ... bench:         433 ns/iter (+/- 21)
test bench_retain         ... bench:       1,378 ns/iter (+/- 87)
```
`|x| *x >= 500`
```
test bench_filter_collect ... bench:         439 ns/iter (+/- 80)
test bench_retain         ... bench:       1,379 ns/iter (+/- 185)
```

**Comment by the8472** [comment]
I'll take a stab at this. @rustbot claim

**Comment by the8472** [comment]
Submitted #91527, if anyone wants to confirm my benchmark results.
