### ISSUE TITLE
Tracking Issue for `const_borrow`

### ISSUE THREAD

**Issue by lilasta** [rust-lang/rust#91522]
Feature gate: `#![feature(const_borrow)]`

This is a tracking issue for implementing `const Borrow/BorrowMut`.

### Public API

```rust
// core::borrow
impl<T: ?Sized> const Borrow<T> for T
impl<T: ?Sized> const BorrowMut<T> for T
impl<T: ?Sized> const Borrow<T> for &T
impl<T: ?Sized> const Borrow<T> for &mut T
impl<T: ?Sized> const BorrowMut<T> for &mut T

// core::array
impl<T, const N: usize> const Borrow<[T]> for [T; N]
impl<T, const N: usize> const BorrowMut<[T]> for [T; N]
```

### Steps / History

- [x] Implementation: #90270
- [ ] Final comment period (FCP)
- [ ] Stabilization PR

### Unresolved Questions

- None yet.

**Comment by DavidSkrundz** [comment]
It appears the implementation was removed in https://github.com/rust-lang/rust/commit/76dbe2910465072f85e74d6f7115ec9e6803e8bf#diff-b8d90f158b67cb63e13a53302629ba287759aed739f9e10ee524d5ef8592b9ca. Is there an alternative or a plan to reintroduce the feature?

**Comment by RalfJung** [comment]
Is any part of this feature left after https://github.com/rust-lang/rust/pull/110393? Cc @fee1-dead 

That PR removed a *lot* of `rustc_const_unstable`, likely all those tracking issues are outdated now.

**Comment by RalfJung** [comment]
I can't find any mention of `91522` in the codebase, so I''ll close this issue -- this feature has been removed.
