### ISSUE TITLE
Vec<Type1,Type2> should suggest a tuple if Type2 is not an allocator.

### ISSUE THREAD

**Issue by damccull** [rust-lang/rust#91540]
When aliasing a type for a vec of a tuple, it'd be nice to be told something like "You probably meant to use a tuple" instead of getting an error saying you're using unstable library features.

Given the following code: 

```rust
type MyType = Vec<u32,bool>;
```

The current output is:

```
error[E0658]: use of unstable library feature 'allocator_api'
  --> advent-of-code-2021\src\day4\mod.rs:14:28
   |
14 | type BingoBoard = Vec<u32, bool>;
   |                            ^^^^
   |
   = note: see issue #32838 <https://github.com/rust-lang/rust/issues/32838> for more information
```

Ideally the output should look like:

```
error[E0658]: use of unstable library feature 'allocator_api'
  --> advent-of-code-2021\src\day4\mod.rs:14:28
   |
14 | type BingoBoard = Vec<u32, bool>;
   |                            ^^^^
   |
   | Maybe you meant to use a tuple instead?
   = note: see issue #32838 <https://github.com/rust-lang/rust/issues/32838> for more information
```

This would make it easier to identify this typo in the code for those of us who are newer or less experienced rather than having to guess. I'm not sure how the compiler itself works, but the way I imagine this could be checked is if the second type in the Vec declaration does not implement a trait identifying it as an allocator, it should show the friendly message.

**Comment by damccull** [comment]
@Dylan-DPC pinged as you requested on Discord.

**Comment by damccull** [comment]
@ibraheemdev found #82452 and #80237 related.

**Comment by TaKO8Ki** [comment]
#90856 has already solved this problem.
