### ISSUE TITLE
Binaries sporadically killed on macOS

### ISSUE THREAD

**Issue by winterqt** [rust-lang/rust#91541]
When executing `cargo run` on macOS, a chance exists for the process to be SIGKILLed on launch. Re-executing the exact same binary after it is killed makes it execute just fine.

When the process is killed, the following is logged into the OS' console:

```
AMFI: '/path/to/binary' is adhoc signed.
/path/to/binary signature not valid: -67050
ASP: Security policy would not allow process: <PID>, /path/to/binary
```

The only thing I've tried to do to stop this is restart macOS (thinking this might be some bad `amfid` state or something, race condition?), to no avail. I have been able to reproduce this on rustc versions 1.55.0 and 1.56.1.

### Meta

`rustc --version --verbose`:
```
rustc 1.56.1
binary: rustc
commit-hash: unknown
commit-date: unknown
host: aarch64-apple-darwin
release: 1.56.1
LLVM version: 13.0.0
```

**Comment by hkratz** [comment]
@winterqt What Macos version and arch (Intel or ARM) are you using? Can you cause it to happen on purpose (e.g. with 10000 times cargo run on a hello world app)?

@rustbot label O-macos

**Comment by ehuss** [comment]
I have been experiencing the same issue, there is some more detail over at https://github.com/rust-lang/cargo/issues/10060.    I am on x86_64, macOS 12.0.1.

It seems to be quite sporadic. Sometimes it won't happen at all, and sometimes it will be quite frequent.

**Comment by winterqt** [comment]
@ehuss Should I close this in favor of the Cargo issue?

**Comment by ehuss** [comment]
Yea, I'll go ahead and close it to keep discussion in one place.

I have not seen this affect `rustc` itself. Just recently-created executables via `cargo run`. I also have not seen this affect CI or running tests locally, which rapidly create executables, so there is some piece of the puzzle related to `cargo run` that I am not seeing.
