### ISSUE TITLE
Unmatched brace in a format string crashes the compiler

### ISSUE THREAD

**Issue by VorfeedCanal** [rust-lang/rust#91556]
Reproducer:
~~~
pub fn test(i: i32) -> String {
  format!(concat!("{0}𝖳𝖾𝗌𝗍{"), i)
}
~~~

Playground link: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=8b3a4c8413cd9d296706c9da0ac6e0c0

**Comment by compiler-errors** [comment]
I'd love to take a look at this. Seems to be ICEing in code that displays the diagnostic to fixup the actual compiler error here.

@rustbot claim
