### ISSUE TITLE
Can't disable this trusted_step

### ISSUE THREAD

**Issue by kamleshbhalui** [rust-lang/rust#91581]
built command was $x.py install -j8
and one worst thing about above command i see that, it always deletes all the previously built libs and tools for all stages ,and rebuild it from stage0.
is there any way to resume the build where it failed last time, rather than cleaning up everything and doing fresh build every time?
And also how can we disable below error, in lib.rs trusted_step is enabled but still throwing this error.

error[E0658]: use of unstable library feature 'trusted_step'
   --> C:\Users\kamle\.cargo\registry\src\github.com-1ecc6299db9ec823\rustc-ap-rustc_index-722.0.0\src\vec.rs:208:21
    |
69  |   macro_rules! newtype_index {
    |  _-
    | |_|
    | |_|
    | |
70  | |     // ---- public rules ----
71  | |
72  | |     // Use default constants
...   |
86  | /         $crate::newtype_index!(
87  |               // Leave out derives marker so we can use its absence to ensure it comes first
88  |               @attrs        [$(#[$attrs])*]
89  |               @type         [$name]
...
93  |               @debug_format ["{}"]
94  | |                           $($tokens)+);
    | |______________________________________- in this macro invocation (#2)
...
208 | |         unsafe impl ::std::iter::TrustedStep for $type {}
    | |                     ^^^^^^^^^^^^^^^^^^^^^^^^
...   |
348 | /         $crate::newtype_index!(
349 |               @derives      []
350 |               @attrs        [$(#[$attrs])*]
351 |               @type         [$type]
...
354 |               @debug_format [$debug_format]
355 | |                           $($tokens)*);
    | |______________________________________- in this macro invocation (#3)
...
484 | |     );
485 | | }
    | | -
    | |_|
    | |_in this expansion of `rustc_index::newtype_index!` (#1)
    | |_in this expansion of `$crate::newtype_index!` (#2)
    |   in this expansion of `$crate::newtype_index!` (#3)
    |
   ::: C:\Users\kamle\.cargo\registry\src\github.com-1ecc6299db9ec823\rustc-ap-rustc_span-722.0.0\src\def_id.rs:11:1
    |
11  | / rustc_index::newtype_index! {
12  | |     pub struct CrateId {
13  | |         ENCODABLE = custom
14  | |     }
15  | | }
    | |_- in this macro invocation (#1)
    |
    = note: see issue #85731 <https://github.com/rust-lang/rust/issues/85731> for more information
    = help: add `#![feature(trusted_step)]` to the crate attributes to enable

For more information about this error, try `rustc --explain E0658`.
error: could not compile `rustc-ap-rustc_span` due to previous error
warning: build failed, waiting for other jobs to finish...
error: build failed
thread 'main' panicked at 'Unable to build RLS', src\bootstrap\dist.rs:45:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Build completed unsuccessfully in 2:01:32

**Comment by jyn514** [comment]
@kamleshbhalui RLS isn't guaranteed to build on all commits. The compiler and other tools should be working fine. I'm not sure why x.py install would rebuild, I haven't tried it.

**Comment by ehuss** [comment]
Yea, you'll need to remove RLS from the tools when it is not in a working state (tools are noted in https://rust-lang-nursery.github.io/rust-toolstate/ when they are broken).  

I'm guessing you are on the master branch? It is pretty unusual to use `x.py install` on master, so it is not designed to continue when a non-functioning tool is encountered.  `x.py install` is usually used with source distributions.

`x.py install` shouldn't start rebuilding from scratch.  It does re-install from scratch, and it will print a lot of things like:

```
    Finished dev [unoptimized] target(s) in 0.10s
Building stage0 std artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
    Finished release [optimized] target(s) in 0.10s
Copying stage0 std from stage0 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
Building stage0 compiler artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
    Finished release [optimized] target(s) in 0.15s
```

but that's normal.

If it really is building std and the compiler, I would check that none of the timestamps of the files in your tree are in the future, and check your system clock.  It may also help to share your `config.toml` and the exact output you are receiving.

**Comment by jyn514** [comment]
I'm going to close this since we haven't heard back - feel free to reopen if you're still running into trouble.
