### ISSUE TITLE
Tracking Issue for `const_option_cloned`

### ISSUE THREAD

**Issue by mbartlett21** [rust-lang/rust#91582]
Feature gate: `#![feature(const_option_cloned)]`

This is a tracking issue for constifying the `Option::cloned` functions.

*This is only constifying existing apis, not adding new ones*

### Public API

```rust
// core::option

impl<T> Option<&T> {
    const fn cloned(self) -> Option<T>
    where
        T: ~const Clone;
}
impl<T> Option<&mut T> {
    const fn cloned(self) -> Option<T>
    where
        T: ~const Clone;
}
```

### Steps / History

- [x] Implementation: #90741
- [ ] Final comment period (FCP)
- [ ] Stabilization PR

### Unresolved Questions

- None yet.

**Comment by RalfJung** [comment]
This got removed by https://github.com/rust-lang/rust/pull/110393.
