### ISSUE TITLE
SDL2 viewport wrong with lto on release builds

### ISSUE THREAD

**Issue by aceArt-GmbH** [rust-lang/rust#91592]
I tried this code:

https://github.com/aceArt-GmbH/sdl2-bug

with `cargo run` and `cargo run --release`

I expected to see this happen: assert should pass like it does on builds without lto (or dev builds)

Instead, this happened: after `set_viewport` the value changes in release build with lto. Disabling lto or removing the `set_viewport` call "fixes" the problem.

Adding a `dbg!(&before);` to line 19 changes the values enormously.

Ref issue: https://github.com/Rust-SDL2/rust-sdl2/issues/1168

I am not sure if this is a problem from rust-sdl2, sdl2, llvm or Rust. I would expect a Rust program to behave the same way in release builds (with lto) as in dev builds.
(I also tried reproducing the example in C++ directly, but I did not mange to do it. Maybe because of lacking C++ knowledge)

### Meta

`rustc --version --verbose`:
```
rustc 1.59.0-nightly (e2116acae 2021-12-05)
binary: rustc
commit-hash: e2116acae59654bfab2a9729a024f3e2fd6d4b02
commit-date: 2021-12-05
host: x86_64-unknown-linux-gnu
release: 1.59.0-nightly
LLVM version: 13.0.0
```

<details><summary>Backtrace</summary>
<p>

```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `Rect { x: 0, y: 0, w: 800, h: 600 }`,
 right: `Rect { x: 0, y: 800, w: 600, h: 5 }`', src/main.rs:22:5
```

or with a `dbg!(&before);` on line 19

```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `Rect { x: 0, y: 0, w: 800, h: 600 }`,
 right: `Rect { x: 22049, y: 492258464, w: 22049, h: 492398784 }`', src/main.rs:23:5
```

</p>
</details>

**Comment by fee1-dead** [comment]
See https://github.com/Rust-SDL2/rust-sdl2/issues/1168#issuecomment-986846324 which outlines the use-after-drop bug in sdl2.
