### ISSUE TITLE
Remove 'unknown'  from linux target 'triples'

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#9159]
It's ridiculous.

**Comment by steveklabnik** [comment]
This was brought up to me as an issue with packaging in Debian, as it does not use `unknown`.

**Comment by steveklabnik** [comment]
Triage: no change.

**Comment by alexcrichton** [comment]
I... don't think we're going to do this as this is the standard terminology, so gonna close. (also a super old bug...)
