### ISSUE TITLE
`rustdoc-scrape-examples` creates dead links and suppresses `--no-deps`

### ISSUE THREAD

**Issue by mejrs** [rust-lang/rust#91605]
I tried rendering docs for a crate with:

```
cargo +nightly doc -Z unstable-options -Z rustdoc-scrape-examples=examples --open --no-deps
```

That puts this in the sidebar:

![image](https://user-images.githubusercontent.com/59372212/144918615-7e8d4703-50ab-4bd2-8c13-71f711390e31.png)

In this case, `cfg_if` and `indoc` are dependencies (which I don't want to document). And `decorator` is the name of one of the examples, this is a dead link.

### Meta
```
rustc 1.57.0 (f1edd0429 2021-11-29)
binary: rustc
commit-hash: f1edd0429582dd29cccacaf50fd134b05593bd9c
commit-date: 2021-11-29
host: x86_64-pc-windows-msvc
release: 1.57.0
LLVM version: 13.0.0

rustdoc 1.57.0 (f1edd0429 2021-11-29)
```

**Comment by jyn514** [comment]
cc @willcrichton - running on dependencies seems like a cargo bug, but showing them in the sidebar seems like it's an issue in rustdoc.

**Comment by willcrichton** [comment]
Thanks for the report @mejrs! I will take a look this week.

**Comment by willcrichton** [comment]
Ok, I have fixed the issue where examples show up in the crates list. https://github.com/willcrichton/rust/commit/b7de7973b221acb2ce900a04c11320a16fc884fb

However, I wasn't able to reproduce the issue with non-examples appearing in the crates list. Specifically, my setup was:

```toml
# Cargo.toml
[package]
name = "doc-test"
version = "0.1.0"
edition = "2021"

[dependencies]
cfg-if = "*"
```

```rust
// src/lib.rs
pub fn heyo(){
  cfg_if::cfg_if! { if #[cfg(unix)] {} else {} }
}
```

```rust
// examples/ex.rs
fn main() {
  cfg_if::cfg_if! { if #[cfg(unix)] {} else {} }
  doc_test::heyo();
}
```

I could not get `cfg_if` to appear in the sidebar when using `--no-deps`.

**Comment by mejrs** [comment]
Thanks 😃 

> However, I wasn't able to reproduce the issue with non-examples appearing in the crates list.

I tried some more things, and I think what happened is that I used it without `--no-deps` at first, and then without clearing the `target/docs` folder, did it *with* `--no-deps`, which apparently doesn't remove the dependencies from the sidebar.

So I guess that part of the issue is about `--no-deps` not working quite right when these artefacts already exist, and unrelated to `rustdoc-scrape-examples`.
