### ISSUE TITLE
Tracking Issue for `[T; N]::resize(_with)` (feature `array_resize`)

### ISSUE THREAD

**Issue by scottmcm** [rust-lang/rust#91615]
Feature gate: `#![feature(array_resize)]`

This is a tracking issue for the `resize` and `resize_with` methods on arrays.

Like `Vec::resize(_with)`, these extend for a larger size or truncate for a shorter one.  Unlike `Vec`, these return a new array (because obviously one can't change the size of a fixed-size array in-place).

### Public API

```rust
impl<T, const N: usize> [T; N] {
    pub fn resize<const NEW_LEN: usize>(self, value: T) -> [T; NEW_LEN];
    pub fn resize_with<const NEW_LEN: usize>(self, mut f: impl FnMut() -> T) -> [T; NEW_LEN];
}
```

### Steps / History

- [ ] Implementation: #91506
- [ ] Final comment period (FCP)
- [ ] Stabilization PR

### Unresolved Questions

- None yet.

**Comment by briansmith** [comment]
What is the motivation? `concat!` for arrays seems like an alternative that would allow the same with similar convenience and more generality.
