### ISSUE TITLE
Adaptive SVG logos look terrible on dark themes

### ISSUE THREAD

**Issue by newpavlov** [rust-lang/rust#91653]
In RustCrypto crates we use [SVG logo](https://raw.githubusercontent.com/RustCrypto/media/master/logo.svg) which changes style depending on preferred theme using `@media(prefers-color-scheme:dark) { .. }` CSS rules. You can see the [`sha2` docs](https://docs.rs/sha2/latest/sha2/) for an example which uses it.

But the problem is how the logo gets rendered on dark themes:
![ayu](https://user-images.githubusercontent.com/329626/145144313-d65a9826-7d66-415b-bf40-be8acde89a2f.png)
![dark](https://user-images.githubusercontent.com/329626/145144316-3dbc30f9-28eb-49ac-b1d9-800ab9dcbf91.png)

The reason for such horrible result is the white shadow filter applied to the logo. I understand why it was added, but I think it's a wrong approach, especially for projects which aim to properly support dark themes in their media files.

**Comment by jsha** [comment]
I believe I broke this in https://github.com/rust-lang/rust/pull/86157/files#diff-0bed4892d95534279b3195c75733913b7735505ae95b8d3d65d63e9ce6a06c1cL144-L159. In #75249 we are supposed to apply the `rust-logo` class only when the logo is the default one. In #86157 I missed that distinction and now the `<img>` always gets the rust-logo class, even when it's a custom logo. I'll fix.

**Comment by jsha** [comment]
By the way, to confirm what @camelid said: the media query embedded in the SVG isn't really right. That gets the _browser's_ preferred light/dark mode, but the user may have overridden that in rustdoc settings.

As a concrete example, I'm using Chrome on Linux, which doesn't have a light/dark mode setting. I can select a dark theme in rustdoc settings, which will get me this for the Rust Crypto logo (with #91958 applied):

![image](https://user-images.githubusercontent.com/220205/146141026-abc4a5b8-5bbe-471b-806e-a9fa5848dc0d.png)

That's still an improvement over the status quo, and overall I think it's fine. But if we really wanted to support theme-sensitive logos perfectly, I think we'd need to offer separate configuration options for a light logo and a dark logo.

**Comment by newpavlov** [comment]
I believe that the media query approach is a correct one _in principle_. But I agree that, unfortunately, the current state of browsers is far from desired (e.g. it would be nice to have a way to switch preferred mode for a page using CSS or JS).

>I'm using Chrome on Linux, which doesn't have a light/dark mode setting

Well, it _kind of_ has. Try launching it with `chromium-browser --force-dark-mode`.
