### ISSUE TITLE
Implement a MIR parser for testing purposes

### ISSUE THREAD

**Issue by fee1-dead** [rust-lang/rust#91669]
As discussed in [Zulip](https://rust-lang.zulipchat.com/#narrow/stream/189540-t-compiler.2Fwg-mir-opt/topic/SimplifyComparisonIntegral.20Assign.20lookup.20is.20overzealous/near/263284763) ([archive](https://zulip-archive.rust-lang.org/stream/189540-t-compiler/wg-mir-opt/topic/SimplifyComparisonIntegral.20Assign.20lookup.20is.20overzealous.html#263284763)), we'd want to be able to write tests where the input is MIR and not Rust to test soundness of certain MIR optimizations. This would require a MIR parser for internal usage only and test mir-opt with that. Codegen tests would probably benefit from this as well.

See also https://github.com/rust-lang/miri/issues/196

**Comment by fee1-dead** [comment]
@spunit262 thank you for being willing to tackle this issue. If you get stuck, you can ask a question here by posting a comment or post a message on zulip. You can also dm anyone from @rust-lang/wg-const-eval (me, `@oli-obk`, `@RalfJung`, `@lcnr`), we'd be happy to help out.

**Comment by oli-obk** [comment]
we now have `#[custom_mir]` that, while still having a few missing pieces to implement, is exactly implementing what this issue is requesting
