### ISSUE TITLE
bootstrap of cargo broken: assertion failed: sentinel == STR_SENTINEL, compiler/rustc_serialize/src/opaque.rs:669:9

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#91663]
EDIT2: 
should be fixed with nightly `2021-12-11`

EDIT: 
FOR EVERYONE THAT IS ALSO GETTING THIS:
Try cleaning your build artifacts: `cargo clean`, in most cases the crash should go away after a rebuild.

-------

https://github.com/rust-lang/rust/pull/91407 added an assertion that triggers on me doing a bootstrap and building cargo:

````
Updating only changed submodules
Submodules updated in 0.01 seconds
    Finished dev [unoptimized] target(s) in 0.14s
Building stage0 std artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
    Finished release [optimized] target(s) in 0.20s
Copying stage0 std from stage0 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
Building stage0 compiler artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
    Finished release [optimized] target(s) in 0.20s
Copying stage0 rustc from stage0 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
Assembling stage1 compiler (x86_64-unknown-linux-gnu)
Building stage1 std artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
    Finished release [optimized] target(s) in 0.18s
Copying stage1 std from stage1 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
Building stage1 compiler artifacts (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu)
    Finished release [optimized] target(s) in 0.19s
Copying stage1 rustc from stage1 (x86_64-unknown-linux-gnu -> x86_64-unknown-linux-gnu / x86_64-unknown-linux-gnu)
Building stage1 tool cargo (x86_64-unknown-linux-gnu)
   Compiling url v2.2.2
thread 'rustc' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `193`', /home/matthias/vcs/github/rust/compiler/rustc_serialize/src/opaque.rs:669:9
 ````

repo @ 11fb21fd0e4c42490d42f1baf6bc51516e5dc5f5

<details><summary><strong>Backtrace</strong></summary>
<p>

```
Building stage1 tool cargo (x86_64-unknown-linux-gnu)
   Compiling url v2.2.2
thread 'rustc' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `193`', /home/matthias/vcs/github/rust/compiler/rustc_serialize/src/opaque.rs:669:9
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed::<u8, u8>
   4: <rustc_metadata::rmeta::decoder::DecodeContext as rustc_serialize::serialize::Decoder>::read_str
   5: <rustc_metadata::rmeta::Lazy<alloc::string::String, ()>>::decode::<&rustc_metadata::rmeta::decoder::MetadataBlob>
   6: <rustc_metadata::locator::CrateLocator>::extract_one
   7: <rustc_metadata::locator::CrateLocator>::extract_lib
   8: <rustc_metadata::locator::CrateLocator>::find_library_crate
   9: <rustc_metadata::locator::CrateLocator>::maybe_load_library_crate
  10: <rustc_metadata::creader::CrateLoader>::load
  11: <rustc_metadata::creader::CrateLoader>::maybe_resolve_crate
  12: <rustc_metadata::creader::CrateLoader>::maybe_resolve_crate
  13: <rustc_metadata::creader::CrateLoader>::resolve_crate
  14: <rustc_metadata::creader::CrateLoader>::process_extern_crate
  15: <rustc_resolve::build_reduced_graph::BuildReducedGraphVisitor as rustc_ast::visit::Visitor>::visit_item
  16: <rustc_resolve::Resolver as rustc_expand::base::ResolverExpand>::visit_ast_fragment_with_placeholders
  17: <rustc_expand::expand::MacroExpander>::collect_invocations
  18: <rustc_expand::expand::MacroExpander>::fully_expand_fragment
  19: <rustc_expand::expand::MacroExpander>::expand_crate
  20: rustc_interface::passes::configure_and_expand
  21: <rustc_interface::queries::Queries>::expansion
  22: <rustc_interface::interface::Compiler>::enter::<rustc_driver::run_compiler::{closure#1}::{closure#2}, core::result::Result<core::option::Option<rustc_interface::queries::Linker>, rustc_errors::ErrorReported>>
  23: rustc_span::with_source_map::<core::result::Result<(), rustc_errors::ErrorReported>, rustc_interface::interface::create_compiler_and_run<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#1}>
  24: <scoped_tls::ScopedKey<rustc_span::SessionGlobals>>::set::<rustc_interface::util::setup_callbacks_and_run_in_thread_pool_with_globals<rustc_interface::interface::run_compiler<core::result::Result<(), rustc_errors::ErrorReported>, rustc_driver::run_compiler::{closure#1}>::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>::{closure#0}::{closure#0}, core::result::Result<(), rustc_errors::ErrorReported>>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.59.0-dev running on x86_64-unknown-linux-gnu

note: compiler flags: -Z symbol-mangling-version=v0 -Z macro-backtrace -Z tls-model=initial-exec -Z binary-dep-depinfo -C opt-level=3 -C embed-bitcode=no -C codegen-units=4 -C debuginfo=0 -C link-args=-Wl,-rpath,$ORIGIN/../lib --crate-type rlib

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `url`
Build completed unsuccessfully in 0:00:02
```

</p>
</details>

I'm using sccache in case that matters.

cc @the8472

**Comment by the8472** [comment]
The output looks like nothing is getting rebuilt, but I would expect the stage1 compiler getting built if you pulled a new master. Something is caching too aggressively?

**Comment by matthiaskrgr** [comment]
Hmm, I wonder if it is a mix of using sccache + sharing target dir between different crates (rustc tools) that causes the problem.

**Comment by the8472** [comment]
I did encounter such an issue myself while working the PR but doing `./x.py clean` solved the issue. But that wasn't unexpected since I changed the serialization format of the compiler, thus making existing serialized data invalid.

But my understanding is that this should only affect rustc developers because the rustc build version doesn't change. For CI builds the git commit should differ and thus the cached data should be discarded as coming from a different compiler version.

**Comment by matthiaskrgr** [comment]
I've wiped my sccache and rustc build cache and have not seen the issue since, but there seem to be a lot of other people having similar problems, hm.

**Comment by the8472** [comment]
So it's probably a missing cache invalidation and my assumption that it's keyed on the compiler version is wrong.

**Comment by kov** [comment]
Just hit this issue building a personal project (it was building the derive_builder_core crate). The cause is apparently that I was building with the stable release channel and got this error:

```
error[E0554]: `#![feature]` may not be used on the stable release channel
 --> offload-daemon/src/main.rs:1:1
  |
1 | #![feature(async_closure)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^
```

Then I switched to the nightly channel and retried the build, got this panic. The panic went away when I removed the target/ dir and rebuilt.

**Comment by kaimast** [comment]
I got this issue after moving my home directory to a new install. My guess is some of the permissions got messed up. I already tried `cargo clean` reinstalling all toolchains with rustup and deleting the target directories.

What is the "sccache" and how do I clean it?

**Comment by matthiaskrgr** [comment]
sccache is a (distributed/local) build cache that can be used with cargo/rustc (but also clang gcc etc).
https://github.com/mozilla/sccache

If you want to purge it should be save to just remove the content of `~/.cache/sccache` but if you don't know what it is, you probably never set it up and are not using it I guess.

**Comment by kaimast** [comment]
Oh yeah I don't use that. I just removed `~/.cargo` and reinstalled everything using rustup but still keep running into this. 

Any idea how to do debug or what logs to provide to this report?

**Comment by matthiaskrgr** [comment]
"~/.cargo" is the cargo download/source cache, should be unrelated to this issue. :sweat_smile: 

The issue should be fixed once https://github.com/rust-lang/rust/pull/91715 is shipped in a new nightly compiler.

For now you can probably pin to yesterdays nightly `2021-12-07` until the bug is fixed:
https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file
The `channel` line would be yesterdays nightly I think:
`channel = "nightly-2021-12-07"`

**Comment by martinellison** [comment]
This seems to be the omicron of rustc bugs.

**Comment by matthiaskrgr** [comment]
https://github.com/rust-lang/rust/pull/91715 has been merged, closing.
