### ISSUE TITLE
Warn for features not defined in a Cargo.toml

### ISSUE THREAD

**Issue by Velfi** [rust-lang/rust#91674]
Given the following code:
[playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=7e1eb7024eed42238913561215fad889)

```rust
fn main() {
    #[cfg(any(feature = "feature_a", feature = "feature_b"))]
    foo()
}

// Oh no, a typo in a feature name!
#[cfg(any(feature = "feature_a", feature = "feature-b"))]
pub fn foo() {
    println!("foo")
}
```

The current output is:

```
// No output
```

Ideally the output should look like:

```
You have a feature gate for a feature "feature-b" that is not defined in this crate's Cargo.toml.
   --> main.rs
    |
    | #[cfg(any(feature = "feature_a", feature = "feature-b"))]
    |                                             ^ help: a feature with a similar name exists: `feature_b`
```

This issue is in regards to the interaction of `cargo` and `rustc`. Imagine that the above example is from project with this Cargo.toml:

```toml
[package]
name = "a-crate"
version = "0.1.0"
edition = "2018"

[features]
feature_a = []
feature_b = []
```

I ran into this as part of my work on the AWS Rust SDKs and you can view the PR where I fixed a bug related to this [here](https://github.com/awslabs/smithy-rs/pull/946/files#r765230440). I was fixing a bug where it looked like some code should have compiled but it didn't due to a typo in the feature flag. It would have saved me some time if the compiler could have detected this typo and drawn my attention to it.

**Comment by estebank** [comment]
Tagging t-cargo because I believe that it might have to pass crate information in, *but* `rustc` could learn to parse Cargo.toml itself as well.

**Comment by weihanglo** [comment]
Rustc has the unstable option [`--check-cfg`], and Cargo also got the counterpart [`-Zcheck-cfg`] a while back. You can try them with nightly channel. The warning probably need some specialization though.

<details><summary>Click to see a demo of <code>-Zcheck-cfg</code></summary>

```console
$ cargo +nightly check -Z unstable-options -Z check-cfg=features
warning: unexpected `cfg` condition value
 --> src/main.rs:6:11
  |
6 | #[cfg(any(feature = "feature_a", feature = "feature-b"))]
  |           ^^^^^^^^^^^^^^^^^^^^^
  |
  = note: no expected value for `feature`
  = note: `#[warn(unexpected_cfgs)]` on by default

warning: unexpected `cfg` condition value
 --> src/main.rs:6:34
  |
6 | #[cfg(any(feature = "feature_a", feature = "feature-b"))]
  |                                  ^^^^^^^^^^^^^^^^^^^^^
  |
  = note: no expected value for `feature`

warning: unexpected `cfg` condition value
 --> src/main.rs:2:15
  |
2 |     #[cfg(any(feature = "feature_a", feature = "feature-b"))]
  |               ^^^^^^^^^^^^^^^^^^^^^
  |
  = note: no expected value for `feature`

warning: unexpected `cfg` condition value
 --> src/main.rs:2:38
  |
2 |     #[cfg(any(feature = "feature_a", feature = "feature-b"))]
  |                                      ^^^^^^^^^^^^^^^^^^^^^
  |
  = note: no expected value for `feature`

warning: `f` (bin "f") generated 4 warnings
    Finished dev [unoptimized + debuginfo] target(s) in 0.19s
```

</details>

I guess this could be closed as we track these flags from <https://github.com/rust-lang/rust/issues/82450> and <https://github.com/rust-lang/cargo/issues/10554>.

[`--check-cfg`]: https://doc.rust-lang.org/nightly/unstable-book/compiler-flags/check-cfg.html
[`-Zcheck-cfg`]: https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#check-cfg

**Comment by estebank** [comment]
Closing in favor of the tracking issue, and very happy to see some recent progress on this. Looking forward to this being enabled by default in stable.
