### ISSUE TITLE
Missing tools in LLVM CI tarball

### ISSUE THREAD

**Issue by nox** [rust-lang/rust#91710]
I've rebased this morning and I can't build the repo anymore since #91685 landed.

```
Copy "/Users/nox/src/rust/build/x86_64-apple-darwin/ci-llvm/bin/llvm-dwp" to "/Users/nox/src/rust/build/x86_64-apple-darwin/stage1/lib/rustlib/x86_64-apple-darwin/bin/rust-llvm-dwp"
Copy "/Users/nox/src/rust/build/x86_64-apple-darwin/ci-llvm/bin/llvm-cov" to "/Users/nox/src/rust/build/x86_64-apple-darwin/stage1/lib/rustlib/x86_64-apple-darwin/bin/llvm-cov"
Copy "/Users/nox/src/rust/build/x86_64-apple-darwin/ci-llvm/bin/llvm-nm" to "/Users/nox/src/rust/build/x86_64-apple-darwin/stage1/lib/rustlib/x86_64-apple-darwin/bin/llvm-nm"
thread 'main' panicked at 'src.symlink_metadata() failed with No such file or directory (os error 2)', src/bootstrap/lib.rs:1324:24
```

It seems there are missing tools in the LLVM CI tarball.

AFAICT, these are the tools CI copies in the tarball:

https://github.com/rust-lang/rust/blob/3b263ceb5cb89b6d53b5a03b47ec447c3a7f7765/src/bootstrap/dist.rs#L2077-L2087

And these are the tools bootstrap tries to install in `build/`:

https://github.com/rust-lang/rust/blob/3b263ceb5cb89b6d53b5a03b47ec447c3a7f7765/src/bootstrap/compile.rs#L1169-L1177

`LLVM_TOOLS` being defined as:

https://github.com/rust-lang/rust/blob/3b263ceb5cb89b6d53b5a03b47ec447c3a7f7765/src/bootstrap/lib.rs#L172-L186

As you can see, there are many tools in `LLVM_TOOLS` that are not included in that `dist` step shown above.

I'm on macOS, and here is the list of tools that I found in the downloaded LLVM CI tarball:

```
± tar tf build/cache/llvm-09d8a50ea26df391b58373e22f5891740efdd6cc-False/rust-dev-nightly-x86_64-apple-darwin.tar.xz 'rust-dev-nightly-*/rust-dev/bin/'
rust-dev-nightly-x86_64-apple-darwin/rust-dev/bin
rust-dev-nightly-x86_64-apple-darwin/rust-dev/bin/llvm-profdata
rust-dev-nightly-x86_64-apple-darwin/rust-dev/bin/lld
rust-dev-nightly-x86_64-apple-darwin/rust-dev/bin/llvm-config
rust-dev-nightly-x86_64-apple-darwin/rust-dev/bin/FileCheck
rust-dev-nightly-x86_64-apple-darwin/rust-dev/bin/llvm-objdump
rust-dev-nightly-x86_64-apple-darwin/rust-dev/bin/llvm-dwp
rust-dev-nightly-x86_64-apple-darwin/rust-dev/bin/llvm-ar
rust-dev-nightly-x86_64-apple-darwin/rust-dev/bin/llvm-bcanalyzer
rust-dev-nightly-x86_64-apple-darwin/rust-dev/bin/llvm-cov
```

Cc @Aaron1011 who authored #91685.

**Comment by Aaron1011** [comment]
I think we should disable copying those tools under ci-llvm for now, and then decide if we want to include them in the ci-llvm artifact or not.

**Comment by Mark-Simulacrum** [comment]
@Aaron1011 makes sense to me!

**Comment by nox** [comment]
Actually the problem seems to be bigger, for now I disabled using the LLVM CI tarball locally and it still failed.

**Comment by Aaron1011** [comment]
@nox What error are you getting with it disabled?

**Comment by nox** [comment]
Exactly the same. I restarted the whole build after running `git clean -dfx`, I'll report back once (if) the error reproduces again.

**Comment by nox** [comment]
Ah! The compiler profile sets `download-ci-llvm` to `if-available`, my bad, I'll explicitly override that to `false` in my config and the problem will probably go away. I should have noticed I didn't actually rebuild LLVM hah.

**Comment by jyn514** [comment]
Or just call `builder.ensure`, like I suggested originally ... I'm not sure why dist is being treated differently from all the other build commands.

**Comment by Aaron1011** [comment]
@jyn514 Those tools don't exist in the downloaded archive, so `ensure` won't help here
