### ISSUE TITLE
request: add `remainder` method to `core::iter::Split`

### ISSUE THREAD

**Issue by Lokathor** [rust-lang/rust#91733]
It would be very helpful if the `Split` iterator let you get back the currently remaining slice. There's `splitn` when you know ahead of time the number of splits you need, but sometimes you don't, and you need to dynamically determine when to stop splitting.

**Comment by Patrick-Poitras** [comment]
@Lokathor could you give an example of how you would use it, or an example using it. I'm not sure I quite understand what is being requested here.

**Comment by Lokathor** [comment]
Sure, in this case I needed to do this because I wanted to parse some [Netpbm](https://en.wikipedia.org/wiki/Netpbm) files, which are ascii files that *sometimes* will transition to being binary data after a certain point.

Without getting too deep into the weeds, there's a tag, then width, then height, and then "pixel data", but pixel data might be more ascii data or it might actually be binary bytes. So one might start with a `file_bytes.split(|&u| u == b'\n')` to get the lines of the file, but after you've read far enough to get to the header info (which is always ascii), you *may* need to stop splitting on newline (if the header tag was P4, P5, or P6), and at that point you want to process the rest of the file data in a new way, without losing your position so far.

```rust
let mut header = MyHeaderData::default();
let mut pixel_data: &[u8] = &[];
let mut line_it = file_data.split(|&u| u == b'\n');
while let Some(line) = line_it.next() {
  // handle the header data by filling in the struct
  if all_header_data_has_been_parsed {
    pixel_data = line_it.remainder();
    break;
  }
}
// from here we know if we'll need to parse `pixel_data` as ascii or as binary
```
