### ISSUE TITLE
rustdoc: Add internal lint / tidy check for `Rc` fields in `Context`

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#91731]
Not sure if it's worth it, but opening this so I don't forget.

**Comment by jyn514** [comment]
This seems like a bad idea. Isn't the long term goal to combine this with `SharedContext` at some point anyway? I don't think we need to enforce this any way other than through review.

**Comment by camelid** [comment]
> Isn't the long term goal to combine this with `SharedContext` at some point anyway?

`SharedContext` is for "global context" (across all pages), while `Context` is page-specific (e.g., it contains the ID map). So I'm not sure if it'd make sense to combine them.

**Comment by jyn514** [comment]
Hmm, ok. And the reason for forbidding Rc is to ensure people put it in SharedContext instead? That seems *ok* but it seems kinda overkill.

**Comment by camelid** [comment]
Yeah, that's why I said I'm not sure if it's worth it.

**Comment by camelid** [comment]
I'll just close it for now.
