### ISSUE TITLE
Remove `cfg(test)` from `doc_auto_cfg`

### ISSUE THREAD

**Issue by daxpedda** [rust-lang/rust#91740]
From https://github.com/rust-lang/rust/issues/43781#issuecomment-990466461 and https://github.com/rust-lang/rust/issues/43781#issuecomment-990794133.

Currently `#[cfg(any(feature = "danger", test))]` shows up as:
<img alt="grafik" width="392" src="https://user-images.githubusercontent.com/1645124/145498862-dd978a31-3e11-4429-abc4-2c82094ae608.png">

This seems to be undesired behavior. I'm not familiar with the Rust compiler, but looking through the code lead me to the conclusion that the best way to do this is transform `Attribute`s, removing undesired `cfg`s before passing them to further processing.

The current implementation of `doc_hide_cfg` can only remove `cfg`s that have an exact match. `#![doc(cfg_hide(feature = "x"))]` can only hide `#[cfg(feature = "x")]`, it can't hide `#[cfg(any(feature = "x", feature = "y"))]` or `#[cfg(all(feature = "x", feature = "y"))]`. So my impression is that we can't hook into `doc_hide_cfg` to solve this.

Implementing what I described above could also pave the way to adjust the behaviour of `cfg_hide` and allow it to match for `cfg`s inside `any` and `all`, if this is desired.

Cc https://github.com/rust-lang/rust/issues/43781.

**Comment by jyn514** [comment]
> So my impression is that we can't hook into doc_hide_cfg to solve this.

@Nemo157 actually suggested giving it the behavior you're describing originally, it just turned out to be a little trickier than expected so we delayed it with the goal of being able to land the PR at all. If you can get it to work that would be super helpful!
