### ISSUE TITLE
correct misspelling

### ISSUE THREAD

**Issue by japm48** [rust-lang/rust#91802]
Short version: `s/dereferencable/dereferenceable` in the whole codebase.

AFAIK this is unintentional (and sounds ugly, but I'm not a native speaker). It is only used in comments, so the trivial change should be safe. I opened this issue instead of a PR in case this was not going to be accepted.

### Meta

`rustc --version`:
```
rustc 1.56.1 (59eed8a2a 2021-11-01)
```

**Comment by Patrick-Poitras** [comment]
It is, in fact, a typo. I don't see a problem with doing a PR if you want to make the modifications to the documentation. Typo fixes get rolled in pretty quick after review.

**Comment by jhpratt** [comment]
As a native English speaker this is definitely wrong as-is. A PR should be fine.
