### ISSUE TITLE
"only `u8` can be cast as `char`, not `i32`" needs further information

### ISSUE THREAD

**Issue by GKFX** [rust-lang/rust#91836]
Given the following code: [link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=4932df76de0e9007d1c267e5e57df2b2)

```rust
0x61i32 as char
```

The current output is:

```
only `u8` can be cast as `char`, not `i32`
```

This is not very clear. There are two pieces of background information the user needs here:
* `char`s are Unicode scalar values, which are any integer value from 0 to 0xD7FF and 0xE000 to 0x10FFFF. Only u8 can be statically guaranteed to meet this requirement so only u8 can be cast to char.
* [char::from_u32](https://doc.rust-lang.org/std/primitive.char.html#method.from_u32) is probably what the user wants, if they are interested in non-ASCII values.

The user is directed to further information available at `rustc --explain E0604` and https://doc.rust-lang.org/reference/expressions/operator-expr.html#type-cast-expressions, neither of which explains either of those two points.

**Comment by jyn514** [comment]
I think a good improvement would be to
a) Add more detail about this to https://github.com/rust-lang/rust/blob/master/compiler/rustc_error_codes/src/error_codes/E0604.md
b) Add a `help` to this error that suggests `from_u32`

@GKFX are you interested in working on one or both of those? :)

**Comment by GKFX** [comment]
While I was reading the docs I noticed a minor error in `char::MAX`:
> The highest valid code point a `char` can have.
>
> A [\`char\`] is a [Unicode Scalar Value], which means that it is a [Code
> Point], but only ones within a certain range. `MAX` is the highest valid
> code point that's a valid [Unicode Scalar Value].
>
> [Unicode Scalar Value]: https://www.unicode.org/glossary/#unicode_scalar_value
> [Code Point]: https://www.unicode.org/glossary/#code_point

This isn't true; a USV is a Code Point within either of two ranges, not one. It's also a bit cagey about what the ranges are numerically; I don't know if this is intentional. Personally I would re-write it to the below:

> The highest valid code point a char can have, `0x10FFFF`.
>
> A [Code Point] is any value between zero and `char::MAX`. A [\`char\`] is a
> [Unicode Scalar Value], which is any Code Point that is not in the range
> `0xD800..=0xDFFF`.

Would I put that in the same PR (as they're both `char` documentation) or a new issue?

**Comment by camelid** [comment]
@GKFX A new PR would be better.
