### ISSUE TITLE
`x.py install cargo` failed on MacOS due to not being able to find openssl@3

### ISSUE THREAD

**Issue by jzhou76** [rust-lang/rust#91845]
On MacOS, when I only  have `openssl@3` (installed by `brew` so header files and libs are present), `x.py` would fail to install `cargo`:

```shell
error: failed to run custom build command for `openssl-sys v0.9.65`
......
run pkg_config fail: "`\"pkg-config\" \"--libs\" \"--cflags\" \"openssl\"` did not exit successfully: exit status: 1\n--- stderr\nPackage openssl was not found in the pkg-config search path.\nPerhaps you should add the directory containing `openssl.pc'\nto the PKG_CONFIG_PATH environment variable\nNo package 'openssl' found\n"
```

Installing `openssl@1.1` solved this problem.

**Comment by ehuss** [comment]
It looks like the version of `openssl-sys` needs to be bumped to pull in at least version 0.9.69 which added support for v3 from homebrew.  An alternate workaround is to use the `cargo-native-static` config option, which is how official builds are usually done.

**Comment by Dylan-DPC** [comment]
Closing this to clear up the issue tracker. If you or anyone reading this still needs help you can consult the forums, discords, etc for help. Thanks
