### ISSUE TITLE
regression: Rc implements RefUnwindSafe

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#91869]
https://github.com/rust-lang/rust/pull/87467 added an impl of RefUnwindSafe to Rc, which was detected as breaking these crates:

* https://crater-reports.s3.amazonaws.com/beta-1.58-1/beta-2021-11-30/reg/ref-portals-1.0.0-beta.2/log.txt

This seems likely to be treated as acceptable breakage (the crate in this case is specifically asserting *not* implementing the trait), but want to confirm that.

**Comment by m-ou-se** [comment]
Discussed briefly in the libs meeting. This is expected and acceptable.
