### ISSUE TITLE
Const in trait impl block not evaluated unless used, skipping panics.

### ISSUE THREAD

**Issue by XrXr** [rust-lang/rust#91877]
I found a surprising behavior of constant evaluation and I'm not sure if it's intended.
I feel this is a small usability issue with panics in const context for implementing
compile time assertions.

I tried this code([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=0b352609d418a84a7376b68aea37b29a)):

```rust
trait ConstPanic {
    const EVAL: ();
}

impl ConstPanic for i32 {
    // Does not seem to be evaluated unless used.
    // Program compiles, unexpectedly.
    const EVAL: () = panic!("oh no!");
}

fn main() {
    // Uncommenting the following gives the compile time panic
    // I expect to see. It also gives "warning: path statement with no effect"
    // In this case, it clearly has a compile time effect.
    //i32::EVAL;
}

```

I expected to see this happen: The program fails to compile

Instead, this happened: The program compiles and runs.

### Meta

`rustc --version --verbose`:
```
rustc 1.57.0 (f1edd0429 2021-11-29)
binary: rustc
commit-hash: f1edd0429582dd29cccacaf50fd134b05593bd9c
commit-date: 2021-11-29
host: x86_64-apple-darwin
release: 1.57.0
LLVM version: 13.0.0
```

**Comment by est31** [comment]
I wonder why the compiler evaluates unused consts at all?

```Rust
const EVAL: () = panic!("oh no!"); // ERROR: evaluation of constant value failed
```

There is an inconsistency to consts in trait impl blocks, but I wonder if the inconsistency could be resolved the other way, by not evaluating any unused consts.

**Comment by XrXr** [comment]
> I wonder why the compiler evaluates unused consts at all?

I use it to do check things at compile time, as suggested by the 1.59.0 [release note](https://blog.rust-lang.org/2021/12/02/Rust-1.57.0.html#panic-in-const-contexts).

I think if "no use, no evaluation" because a general rule in the language, it hurts this use case. I want to have confidence that the compile time assert is evaluated when I write it so I can focus on what the assertion itself, not whether it runs at all.

**Comment by RalfJung** [comment]
Cc @rust-lang/wg-const-eval 

For `const` that are *syntactically referenced inside a function* we guarantee they are all evaluated even if the only reference is in dead code. And for top-level `const` we also guarantee that. But we don't have such a guarantee for anything else. And very quickly we reach territory where we cannot have such a guarantee:
```Rust
impl<T> ConstPanic for Vec<T> {
    // Does not seem to be evaluated unless used.
    // Program compiles, unexpectedly.
    const EVAL: () = panic!("oh no!");
}
```
`EVAL` can only be computed once `T` is known (it could, in principle, use `T`).

So currently we stay on the consistent side that *associated consts in traits* are not eagerly evaluated. I am not sure if eagerly evaluating *some* associated consts in traits would be better, since it could be hard to predict when the rule does or does not apply. Eagerly evaluating *all* of them is simply not possible.

**Comment by est31** [comment]
> needed for things like `size_assert!`

Which btw was a bad example: https://www.reddit.com/r/rust/comments/r799fs/announcing_rust_1570/hn05zpf/

But otherwise I think you make good points.

**Comment by XrXr** [comment]
Assuming no docs for the current rules are already available, do you folks think it would make sense to add to the language reference? Might be worth mentioning in [Constant Items](https://doc.rust-lang.org/stable/reference/items/constant-items.html) and/or [Constant Evaluation](https://doc.rust-lang.org/stable/reference/const_eval.html).

**Comment by RalfJung** [comment]
Yes this would definitely be good to document properly if that is not already the case.

**Comment by RalfJung** [comment]
Also I skipped over associated consts in regular (non-trait) `impl` blocks -- but I think we treat them like associated consts in traits, since `impl` blocks can be generic, so the same problem applies.

**Comment by XrXr** [comment]
I'm going to close this for now since this behavior looks to be by design and is now documented in the reference through  rust-lang/reference#1120. It's not a bug and changing this might need to go through a RFC.
