### ISSUE TITLE
regression: binop(?) type inference failures

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#91872]
A bunch of errors around type inference failure detected in the crater run -- I would like us to track down the PR causing these since I'm not finding an obvious reason off hand:

* https://crater-reports.s3.amazonaws.com/beta-1.58-1/beta-2021-11-30/gh/mwc10.dt-backup/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.58-1/beta-2021-11-30/gh/DaTa-.advent-of-code-2020/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.58-1/beta-2021-11-30/gh/MikkelPaulson.advent-of-code-2019/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.58-1/beta-2021-11-30/gh/bfollek.advent2018rust/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.58-1/beta-2021-11-30/gh/daniellockyer.wrp/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.58-1/beta-2021-11-30/gh/proelbtn.chacha20poly1305/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.58-1/beta-2021-11-30/gh/qinxiaoguang.rs-lc/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.58-1/beta-2021-11-30/gh/ruudjelinssen.aoc2020/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.58-1/beta-2021-11-30/reg/roots-0.0.7/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.58-1/beta-2021-11-30/reg/segsource-0.2.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.58-1/beta-2021-11-30/gh/desbma.motd/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.58-1/beta-2021-11-30/gh/l0s.advent-of-code-rust/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.58-1/beta-2021-11-30/reg/dent-0.4.1/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.58-1/beta-2021-11-30/gh/GCYYfun.OSTEP_RUST/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.58-1/beta-2021-11-30/gh/botwob.AdventOfCode2019/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.58-1/beta-2021-11-30/reg/zero_pass_backend-0.0.7/log.txt

It seems plausible this is the breakage noted in https://github.com/rust-lang/rust/issues/90904, but we should confirm.

**Comment by Mark-Simulacrum** [comment]
We will want to do a re-run of beta crater once https://github.com/rust-lang/rust/pull/91484 or equivalent is beta-backported to confirm the majority/all of these are fixed before closing this, but generally it's likely that they will be.

**Comment by BGR360** [comment]
I just did some bisection the other day; it's pretty painless on my M1 pro macbook (~2-4 minutes per build). If this still needs bisection, and somebody can give me a range of commits, I'd be happy to try to bisect it.

**Comment by workingjubilee** [comment]
Since each regression is likely due to https://github.com/rust-lang/rust/pull/89167,
and each is likely fixed after https://github.com/rust-lang/rust/pull/91484
we want to check, for each regression:
- does this build on rust-lang@e90c5fbbc5df5c81267747daeb937d4e955ce6ad?
- does this build after rust-lang@032dfe43605f4324966933078ffe6f717b77c7c8 but before rust-lang@11fb21fd0e4c42490d42f1baf6bc51516e5dc5f5?
- does this build after rust-lang@11fb21fd0e4c42490d42f1baf6bc51516e5dc5f5?

And any curiosities can be handled from there.

**Comment by BGR360** [comment]
For the regressions starting with `reg/`, where do I get those? The other ones have git repos I can clone (`gh/`), but I don't intuit what "reg" stands for.

**Comment by BGR360** [comment]
Here's what I got with the GitHub ones.

https://github.com/rust-lang/rust/commit/e90c5fbbc5df5c81267747daeb937d4e955ce6ad:
```
==== SUCCESSFULLY BUILT: ====
DaTa-.advent-of-code-2020
GCYYfun.OSTEP_RUST
MikkelPaulson.advent-of-code-2019
bfollek.advent2018rust
botwob.AdventOfCode2019
daniellockyer.wrp
l0s.advent-of-code-rust
mwc10.dt-backup
proelbtn.chacha20poly1305
qinxiaoguang.rs-lc
ruudjelinssen.aoc2020
==== FAILURES: ====
desbma.motd
```

3e018ce19 (one merge after https://github.com/rust-lang/rust/commit/032dfe43605f4324966933078ffe6f717b77c7c8):
```
==== SUCCESSFULLY BUILT: ====
==== FAILURES: ====
DaTa-.advent-of-code-2020
GCYYfun.OSTEP_RUST
MikkelPaulson.advent-of-code-2019
bfollek.advent2018rust
botwob.AdventOfCode2019
daniellockyer.wrp
desbma.motd
l0s.advent-of-code-rust
mwc10.dt-backup
proelbtn.chacha20poly1305
qinxiaoguang.rs-lc
ruudjelinssen.aoc2020
```

https://github.com/rust-lang/rust/commit/11fb21fd0e4c42490d42f1baf6bc51516e5dc5f5
```
==== SUCCESSFULLY BUILT: ====
DaTa-.advent-of-code-2020
GCYYfun.OSTEP_RUST
MikkelPaulson.advent-of-code-2019
bfollek.advent2018rust
botwob.AdventOfCode2019
daniellockyer.wrp
l0s.advent-of-code-rust
mwc10.dt-backup
proelbtn.chacha20poly1305
qinxiaoguang.rs-lc
ruudjelinssen.aoc2020
==== FAILURES: ====
desbma.motd
```

Not sure what's up with `desbma.motd`. I made sure to check out the same revision of the repo that was used in the crater logs, but it failed to compile even on stable (with a different error than that in the crater logs). Maybe the author force-pushed that commit or something.

**Comment by workingjubilee** [comment]
Thank you, it looks like it was in fact that PR then and that did in fact fix it, it seems.
Ah, I suppose we could also check rust-lang@477fd7038c235689913abf9208dfa9371cbacd88, but I will likely do that when I try to reimplement splatting.

**Comment by pietroalbini** [comment]
Hmm, what's the status of this?

**Comment by Mark-Simulacrum** [comment]
Should be fixed by https://github.com/rust-lang/rust/pull/92592 on beta, closing.
