### ISSUE TITLE
regression: extra semicolon

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#91874]
* https://crater-reports.s3.amazonaws.com/beta-1.58-1/beta-2021-11-30/gh/nicompte.algoliasearch-rs/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.58-1/beta-2021-11-30/reg/algoliasearch-0.1.4/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.58-1/beta-2021-11-30/reg/andex-0.0.10/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.58-1/beta-2021-11-30/reg/lightning-invoice-0.11.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.58-1/beta-2021-11-30/reg/nuts-0.2.1/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.58-1/beta-2021-11-30/reg/status-0.0.10/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.58-1/beta-2021-11-30/reg/weldr-0.3.1/log.txt

Bisect may be good here to confirm, but I suspect https://github.com/rust-lang/rust/pull/91026 is the cause.

**Comment by Mark-Simulacrum** [comment]
Looks like previously reported in https://github.com/rust-lang/rust/issues/91398, but not yet tracked as a regression.

**Comment by jyn514** [comment]
I still stand by https://github.com/rust-lang/rust/issues/91398#issuecomment-982969172, I don't think this is a bug, just expected breakage from fixing a pre-existing bug.

**Comment by Mark-Simulacrum** [comment]
Just because it's expected breakage / used to be a bug doesn't necessarily mean that we should be breaking stable users. In this case the breakage seems sufficiently limited that this is likely acceptable, but in general we should try to be more careful about landing breakage like this, though it's good to see that the PR was tagged as relnotes.

**Comment by pietroalbini** [comment]
This is mentioned in the compatibility notes, closing.
