### ISSUE TITLE
Tracking Issue for `const` `bool::then{,_some}` functions

### ISSUE THREAD

**Issue by fee1-dead** [rust-lang/rust#91917]
Feature gate: `#![feature(const_bool_to_option)]`

This is a tracking issue for `const` `bool::then{,_some}` functions.

See also #80967

### Public API

```rust
// core::bool

impl bool {
    pub const fn then_some<T>(self, t: T) -> Option<T>
    where
        T: ~const Drop;

    pub const fn then<T, F>(self, f: F) -> Option<T>
    where
        F: ~const FnOnce() -> T,
        F: ~const Drop;
}
```

### Steps / History

- [x] Implementation: #91918
- [ ] Final comment period (FCP)
- [ ] Stabilization PR

### Unresolved Questions

- None yet.

**Comment by gimbles** [comment]
@rust-lang/libs-api 👋🏻 🤖 

Should this be stabilized? It doesn't seem to have had any issues since the start (Dec 2021).

**Comment by jplatte** [comment]
I don't think APIs that use `~const` bounds can be stabilized yet.

**Comment by RalfJung** [comment]
This got removed by https://github.com/rust-lang/rust/pull/110393.
