### ISSUE TITLE
Drop flag statement creation depends on `FxHashMap` interation order

### ISSUE THREAD

**Issue by Aaron1011** [rust-lang/rust#91943]
This code creates MIR statements based on an `FxHashMap` iteration order: https://github.com/rust-lang/rust/blob/404c8471aba60c2d837fa728e7c729a0f52d5830/compiler/rustc_mir_transform/src/elaborate_drops.rs#L493-L495

`drop_flags` is defined as:

https://github.com/rust-lang/rust/blob/404c8471aba60c2d837fa728e7c729a0f52d5830/compiler/rustc_mir_transform/src/elaborate_drops.rs#L260

Since FxHashMap's fixed seed is different between 32 and 64 bit platforms, we may end up creating statements in a different order on 32-bit vs 64-bit **hosts** (the target platform passed to the compiler has no effect).

We should probably sort by `MovePathIndex` before creating the statements.

**Comment by camelid** [comment]
Perhaps it should just use `BTreeMap` instead?

**Comment by apiraino** [comment]
Revisiting this issue to evaluate the priority.

@pnkfelix unsure about the status and global direction of this issue. Do we have some work in progress somewhere? I've tried following the breadcrumbs and landed on #102698. Unsure if it helps and - if yes - how much does that pull request covers to fix this issue.

opinions? thanks :)
