### ISSUE TITLE
Feature Request: scope by indentation and optional semicolons

### ISSUE THREAD

**Issue by TVAO** [rust-lang/rust#91964]
`fn main() {
    println("Hello World!");
}` -> `fn main() 
    println("Hello World!")
` 🙏

**Comment by leonardo-m** [comment]
I don't think this will happen, but perhaps Clippy could improve its warnings in presence of significantly "wrong" indentation...

**Comment by nagisa** [comment]
A change of such scope would require an RFC. If you'd like to propose a change like this, please draft an [RFC](https://github.com/rust-lang/rfcs) instead. Closing the issue for now.
