### ISSUE TITLE
Confusing terminology

### ISSUE THREAD

**Issue by abaptist-ocient** [rust-lang/rust#91978]
This sentence was pretty hard to understand:
The behavior resulting from such a logic error is not specified (it could include panics,
incorrect results, aborts, memory leaks, or non-termination) but will not be undefined
behavior

There may be some technical distinction between "not specified" and "undefined" but it is pretty subtle.

https://github.com/rust-lang/rust/blob/f7fd79ac1d485ab47b62146f6dafed4aad5d9c6d/library/alloc/src/collections/btree/set.rs#L27

**Comment by the8472** [comment]
[undefined behavior](https://en.wikipedia.org/wiki/Undefined_behavior) is a term of art in programming. Here's the definition in the context of rust safety: https://doc.rust-lang.org/reference/behavior-considered-undefined.html

**Comment by abaptist-ocient** [comment]
I did find that page and was trying to think of the venn diagram between "unspecified behavior" and "undefined behavior" and it wasn't clear to me that they didn't overlap. The sentence implies that they don't overlap. In my mind, the words are almost synonymous, and it is possible that "unspecified behavior" is referring to this: https://doc.rust-lang.org/reference/behavior-not-considered-unsafe.html. I don't believe that undefined and unspecified are generally accepted universal terms in programming, and it would be better to more clearly define these terms on these page. I would recommend:
Undesirable behavior: https://doc.rust-lang.org/reference/behavior-not-considered-unsafe.html
Undefined behavior: https://doc.rust-lang.org/reference/behavior-considered-undefined.html

Using this terminology very pedantically would mean that the sentence would be written as:

The behavior resulting from such a logic error can be **undesirable behavior** (it could include panics,
incorrect results, aborts, memory leaks, or non-termination) but will not be undefined
behavior

**Comment by RalfJung** [comment]
>  I don't believe that undefined and unspecified are generally accepted universal terms in programming, 

At least in the space of C/C++ and similar languages (of which Rust is one, for the purpose of this discussion), they certainly are.

I agree that the terminology is not great, but w also have to be careful when deviating from it since many people come to Rust expecting exactly that kind of terminology.

**Comment by abaptist-ocient** [comment]
Thank you for the time and clarification - and I did look a little more at how C++ (and Rust) define things. I am happy to  close this issue out. (for reference C++ ref - http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3797.pdf page 4)
