### ISSUE TITLE
MIPS64: error[E0531]: cannot find unit struct, unit variant or constant `ENOTSUP` in crate `libc`

### ISSUE THREAD

**Issue by Grommish** [rust-lang/rust#91976]
### Code

```Rust
error[E0531]: cannot find unit struct, unit variant or constant `ENOTSUP` in crate `libc`
  --> compiler/rustc_data_structures/src/flock.rs:59:57
   |
59 |                 matches!(err.raw_os_error(), Some(libc::ENOTSUP) | Some(libc::ENOSYS))
   |                                                         ^^^^^^^ not found in `libc`
```

### Meta

`rustc --version --verbose`:
```
./rustc --version --verbose
rustc 1.56.1-nightly
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-linux-gnu
release: 1.56.1-nightly
LLVM version: 13.0.0
```

### Error output

```
<output>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by bjorn3** [comment]
This is when compiling for mips64-openwrt-linux-musl. See https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp/topic/Generating.20native.20rustc.2Fcargo.20binaries.3F for more context.

**Comment by Grommish** [comment]
*sigh* Sorry @bjorn3 

I should also mention that the `mips64_openwrt_linux_musl` is just a cloned `mips64_unknown_linux_muslabi64` define already in rust, renamed and added to `mod.rs` to create the tuple.

**Comment by hkratz** [comment]
It would likely be best if you could just submit a PR against https://github.com/rust-lang/libc adding 
```rust
pub const ENOTSUP: ::c_int = EOPNOTSUPP;
```
at https://github.com/rust-lang/libc/blob/master/src/unix/linux_like/linux/musl/b64/mips64.rs#L507
as it is already done for 32-bit here: https://github.com/rust-lang/libc/blob/master/src/unix/linux_like/linux/musl/b32/mips/mod.rs#L323

@rustbot label -I-ICE

**Comment by Grommish** [comment]
Appreciate it @hkratz !  I'm not a programmers and I don't know rust, so I'm faking my way thru this, but, I can follow directions and can send PRs after I verify it corrects..   I'll report back!

**Comment by Grommish** [comment]
> It would likely be best if you could just submit a PR against https://github.com/rust-lang/libc adding
> 
> ```rust
> pub const ENOTSUP: ::c_int = EOPNOTSUPP;
> ```
> 
> at https://github.com/rust-lang/libc/blob/master/src/unix/linux_like/linux/musl/b64/mips64.rs#L507 as it is already done for 32-bit here: https://github.com/rust-lang/libc/blob/master/src/unix/linux_like/linux/musl/b32/mips/mod.rs#L323
> 
> @rustbot label -I-ICE

Submitted PR

**Comment by sanxiyn** [comment]
`libc` PR is merged, closing. Thanks!
