### ISSUE TITLE
How to wrap associated function of struct with macros?

### ISSUE THREAD

**Issue by goldwind-ting** [rust-lang/rust#92002]
```

struct Job;

impl Job {
    #[my_macros]
    fn name(&self) -> String {
        "a_job".into()
    }
}

```
How to implement the `my_macros` and parse `self` insede `my_macros`?

**Comment by ehuss** [comment]
Questions about how to use Rust are better asked on one of the forums, such as https://users.rust-lang.org/.

To implement a custom attribute, you have to write a [proc-macro](https://doc.rust-lang.org/book/ch19-06-macros.html#attribute-like-macros).  The input is raw tokens, which you can inspect manually, or use something like [`syn`](https://crates.io/crates/syn/) to parse it into a structure.
