### ISSUE TITLE
Improve the example for Vec::splice

### ISSUE THREAD

**Issue by ajtribick** [rust-lang/rust#92067]
The current example for `Vec::splice` illustrates the replacement of a section of length 2 with a new section of length 2. This isn't a particularly interesting case for splice, and makes it look a bit like a shorthand for the kind of manipulations that could be done with a mutable slice.

I think it would be more useful to illustrate this method with a case where the source and replacement are different lengths, e.g.

```rust
let mut v = vec![1, 2, 3, 4];
let new = [7, 8, 9];
let u: Vec<_> = v.splice(1..3, new).collect();
assert_eq!(v, &[1, 7, 8, 9, 4]);
assert_eq!(u, &[2, 3]);
```

Thoughts?

**Comment by jyn514** [comment]
@ajtribick seems like a good change :) are you interested in making a PR? This example lives somewhere in `library/alloc` I think.
