### ISSUE TITLE
Wrong suggestion for slice patterns when using let-else statement

### ISSUE THREAD

**Issue by spaarmann** [rust-lang/rust#92069]
Given the following code: [Playground link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=67bf5b9ec5997d3535258a4b89cd3a31)

```rust
#![feature(let_else)]

fn main() {
    let v = vec![1, 2, 3];
    let [a, b, c] = v else {
        panic!();
    };
}
```

The current output is:

```
error[E0529]: expected an array or slice, found `Vec<{integer}>`
 --> src/main.rs:5:9
  |
5 |     let [a, b, c] = v else {
  |         ^^^^^^^^^ pattern cannot match with input type `Vec<{integer}>`
  |
help: consider slicing here
  |
5 ~     let [a, b, c] = v else {
6 +         panic!();
7 +     };[..]
  |
```
The `[..]` should be added to the `v`, not after the whole statement.

**Comment by SparrowLii** [comment]
It looks like this has been fixed, and it shows in the Playground:

    error[E0529]: expected an array or slice, found `Vec<{integer}>`
     --> src/main.rs:5:9
      |
    5 |     let [a, b, c] = v else {
      |         ^^^^^^^^^   - help: consider slicing here: `v[..]`
      |         |
      |         pattern cannot match with input type `Vec<{integer}>`

**Comment by spaarmann** [comment]
You're right, that was quick!
From skimming the commit log, I'm gonna guess  #89841 fixed this one too, though I haven't verified that.
