### ISSUE TITLE
ICE vec iter

### ISSUE THREAD

**Issue by smallB007** [rust-lang/rust#92100]
### Code

```Rust

fn main() {
    let v = vec![0123456789];
    let mid = v.len() / 2;
    let s = &v;
    match s {
        [a..mid, mid, mid..b] => {}
        [..] => {}
    }
}
```
error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.57.0 (f1edd0429 2021-11-29) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack

### Meta

`rustc --version --verbose`:
```
<version>
```

### Error output

```
<output>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by matthiaskrgr** [comment]
````
   Compiling v v0.1.0 (/tmp/v)
error[E0425]: cannot find value `a` in this scope
 --> src/main.rs:7:10
  |
7 |         [a..mid, mid, mid..b] => {}
  |          ^ help: a local variable with a similar name exists: `s`

error[E0425]: cannot find value `b` in this scope
 --> src/main.rs:7:28
  |
7 |         [a..mid, mid, mid..b] => {}
  |                            ^ help: a local variable with a similar name exists: `s`

error[E0658]: exclusive range pattern syntax is experimental
 --> src/main.rs:7:10
  |
7 |         [a..mid, mid, mid..b] => {}
  |          ^^^^^^
  |
  = note: see issue #37854 <https://github.com/rust-lang/rust/issues/37854> for more information
  = help: add `#![feature(exclusive_range_pattern)]` to the crate attributes to enable

error[E0658]: exclusive range pattern syntax is experimental
 --> src/main.rs:7:23
  |
7 |         [a..mid, mid, mid..b] => {}
  |                       ^^^^^^
  |
  = note: see issue #37854 <https://github.com/rust-lang/rust/issues/37854> for more information
  = help: add `#![feature(exclusive_range_pattern)]` to the crate attributes to enable

thread 'rustc' panicked at 'expected `NodeId` to be lowered already for res Local(
    NodeId(40),
)', compiler/rustc_ast_lowering/src/lib.rs:563:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

error: internal compiler error: unexpected panic

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.59.0-nightly (91a0600a5 2021-12-18) running on x86_64-unknown-linux-gnu

note: compiler flags: -C embed-bitcode=no -C debuginfo=2 -C incremental --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
Some errors have detailed explanations: E0425, E0658.
For more information about an error, try `rustc --explain E0425`.
error: could not compile `v` due to 4 previous errors
````

**Comment by matthiaskrgr** [comment]
reduced:
````rust
fn main() {
    match &vec![0] {
        [a..1, a, a..1] | _ => {}
    }
}
````

**Comment by compiler-errors** [comment]
Minimized this a tiny bit further, and I have a detailed explanation why this occurs:

```
fn main() {
    match () {
        [a.., a] => {}
    }
}
```

So this bug first starts going wrong in late resolution. Specifically, [`LateResolutionVisitor::resolve_pattern_late`](https://github.com/rust-lang/rust/blob/master/compiler/rustc_resolve/src/late.rs#L1631) walks through the pattern first over all of the pattern variants via `ast::Pat::walk`, trying to gather all of the bindings in the pattern. As we iterate through the slice pattern, we skip over the lhs of the range pattern (since it's actually an expression), and bind `a` in the second element of the slice pattern. Then we visit the pattern for real `visit::walk_pat` which sees the binding we introduced and binds it in `a..`. 

Essentially, defining the subpattern `a` after the expr `a..` leads to the ICE later on, since we expect to have lowered that path element.

**Comment by compiler-errors** [comment]
Wonder how difficult it would be to make `PatKind::Range` have subpatterns instead of subexpressions...

**Comment by compiler-errors** [comment]
Actually, I don't think fixing this just for ranges is sufficient. I can reproduce this same issue with this:

```
macro_rules! funny {
    ($a:expr, $b:ident) => {
        match [1, 2] {
            [$a, $b] => {}
        }
    }
}

fn main() {
    funny!(a, a);
}
```

Maybe I can just delay this panic as a span bug, since we're always gonna error out anyways.
