### ISSUE TITLE
unreachable!("{}") works on Rust 2021

### ISSUE THREAD

**Issue by m-ou-se** [rust-lang/rust#92137]
The behavior of `unreachable` does not depend the edition of the crate that invoked the macro. That's fine for `todo!()` and `unimplemented!()` due to the way they are implemented, but in #92068, it was discovered that `unreachable!()` behaves subtly different, due to the way it has a special one-argument case. Looks like missed this when working on the 2021 panic macros. :(

**Comment by m-ou-se** [comment]
`todo!()` and `unimplemented!()` are implemented like this: https://github.com/rust-lang/rust/blob/23f69235ad2eb9b44ac1a55eeaa3f9b484d9de4a/library/core/src/macros/mod.rs#L738-L741

They never accepted `todo!("{}")` or `todo!(123)` since their arguments are always directly passed to `format_args!()`. So, they didn't have to change for Rust 2021.

`unreachable!()` however, is implemented differently: https://github.com/rust-lang/rust/blob/23f69235ad2eb9b44ac1a55eeaa3f9b484d9de4a/library/core/src/macros/mod.rs#L592-L602

It doesn't just forward to `panic!()` or `format_args!()`, but instead it does its own `concat` shenanigans, and has special handling of the single argument case.

**Comment by m-ou-se** [comment]
So then the question is: Do we consider this a bug in Rust 2021 and fix it in Rust 1.59 for that edition? Or leave this in and only fix it in a later edition (or never)?

There's quite a few cases on crates.io of Rust 2015/2018 code depending on this behavior, but Rust 2021 is very new at this point. Adding this change/fix to Rust 2021 probably doesn't break anyone, yet.

**Comment by m-ou-se** [comment]
Behavior:

```
unreachable!();          // panic message: "internal error: entered unreachable code"
unreachable!(123);       // panic message: "internal error: entered unreachable code: 123"
unreachable!("{}");      // panic message: "internal error: entered unreachable code: {}"
unreachable!("{}", 123); // panic message: "internal error: entered unreachable code: 123"
```

**Comment by m-ou-se** [comment]
We can't fix `unreachable` without making it a builtin macro, like `panic!()`. That's because (unlike e.g. `debug_assert`), this macro doesn't just forward to assert/panic, but has its own problematic implementation with a special case that shouldn't exist.

**Comment by jyn514** [comment]
> We can't fix `unreachable` without making it a builtin macro, like `panic!()`. That's because (unlike e.g. `debug_assert`), this macro doesn't just forward to assert/panic, but has its own problematic implementation with a special case that shouldn't exist.

I'm not sure I follow - can't we remove the concat special case and forward directly to panic, like todo does?

**Comment by m-ou-se** [comment]
> I'm not sure I follow - can't we remove the concat special case and forward directly to panic, like todo does?

@jyn514 Then `unreachable!(123)` would stop working on Rust 2015/2018.

**Comment by m-ou-se** [comment]
From a quick grep through crates.io, it looks like there's about 15 crates on crates.io depending on the current behavior that would break if we made it work like todo!(). Here's a few examples from the results of a quick grep trough crates.io:

```
unreachable!(message);
unreachable!(&error)
unreachable!(format!("Cannot compute gcd of {:?} and {:?}", x, y))
Err(err) => unreachable!(err),
_ => unreachable!(format!("Unsupported socket family {}!", raw.family)),
l => unreachable!(format!("got unexpected length {0:?}", l)),
x => unreachable!(x),
Error { message } => unreachable!(message),
unreachable!(false);
unreachable!(msg)
unreachable!(&format!("n = {:?}", n)),
_ => unreachable!(ERROR_MSG),
_ => unreachable!(format!("{} is invalid month!", month)),
hash => { unreachable!(hash); }
```

**Comment by joshtriplett** [comment]
Making `unreachable` built-in to fix this on Rust 2021 seems reasonable to me.

**Comment by jhpratt** [comment]
IMO as long as there's a crater run fixing this is reasonable. It's certainly a bug.

**Comment by camelid** [comment]
It'd probably be better to fix this sooner rather than later, as the edition is still relatively new.

**Comment by camelid** [comment]
Assigning priority as [discussed](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2392137.20unreachable!.28.22.7B.7D.22.29.20works.20on.20Rust.202021) in the prioritization working group.

@rustbot label: +P-high -I-prioritize

**Comment by jhpratt** [comment]
Short of eager macro expansion, this would require `unreachable!` becoming a built-in macro, correct?

**Comment by camelid** [comment]
@jhpratt I believe yes, see https://github.com/rust-lang/rust/issues/92137#issuecomment-998287185.

**Comment by jhpratt** [comment]
Thanks; not sure how I missed that comment. I won't have time until Tuesday at the earliest (and likely not that early), but I can give it a shot if no one else wants to take a shot at it before.

**Comment by Arnavion** [comment]
Just to be sure, the proposed change will also fix the fact that `unreachable!("{x}")` and `unreachable!("{}", x)` don't behave the same in 1.58+ with E2021, right? (The former prints `internal error: entered unreachable code: {x}` because it's not parsed as a format string with implicit args.)

**Comment by Urgau** [comment]
@jhpratt I've give it a [shot](https://github.com/rust-lang/rust/compare/master...Urgau:unreachable-2021?expand=1) today and basically everything works except that `unreachable!("{x}")` doesn't because:
```
error: there is no argument named `x`
  --> /home/archie/Projects/RustProjects/rust/src/test/ui/macros/unreachable-2021.rs:8:5
   |
LL |     unreachable!("x is {x}");
   |     ^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: did you intend to capture a variable `x` from the surrounding scope?
   = note: to avoid ambiguity, `format_args!` cannot capture variables when the format string is expanded from a macro
   = note: this error originates in the macro `$crate::concat` (in Nightly builds, run with -Z macro-backtrace for more info)
```
This is due to the fact that the macro append to the format the string "internal error: entered unreachable code: " with:
```rust
        $crate::panic!($crate::concat!("internal error: entered unreachable code: ", $fmt), $($arg)*)
```
If anyone has a idea on how to solve it, let me know or if you want you can also continue my work.

**Comment by jhpratt** [comment]
As mentioned, making it a built-in macro seems to be the way to go. My intent was to pass as much as possible off to the panic macro handler. Good luck!

**Comment by Urgau** [comment]
@jhpratt I tried to do it the same way as the `panic` macro, make it a builtin macro that redirects toward one of these two new macro `unreachable_2015` and `unreachable_2021`.

**Comment by camelid** [comment]
@Urgau what about doing the concatenation using internal compiler APIs? I don't know them off the top of my head, but there's probably a way to concatenate the strings from within the compiler without using `concat!`.

**Comment by jhpratt** [comment]
My intended solution involved manually prepending the relevant text to the format and passing the result of that to the method that expands the `panic!` macro. This should handle the 2015/2021 edition split automatically. You won't be able to use the `concat!` macro because eager expansion doesn't exist.

**Comment by Urgau** [comment]
I managed to get it working by adding an unstable [`format_args_capture_non_literal`](https://github.com/Urgau/rust/commit/7250ccefa71dd6485c10cd3a392048b9d7765d9c) feature to `format_args!`.
The actual the logic is the [same](https://github.com/Urgau/rust/commit/a48ee089f9b8a9acd38fd974f0167eead5ae7244) as the previous one.

@camelid @jhpratt Do you think that this is an acceptable solution (at least for a PR) ?

**Comment by jhpratt** [comment]
A quick once-over of it shows no obvious issues. I'd personally prefer a solution like I described because I think it would limit the amount of compiler magic, but I'm not on any teams.

**Comment by camelid** [comment]
I'd also prefer avoiding a internal-use-only feature gate that turns off error checks.

**Comment by Urgau** [comment]
> I'd also prefer avoiding a internal-use-only feature gate that turns off error checks.

Technically it doesn't turn off but instead turn on a future possibility of RFC that defined capturing arguments but I get your concern.

Over the concern you two have expressed I will not submit a pr and also will not try to implement @jhpratt proposed solution because it involves `TokenStream` and I don't know enough about them.

**Comment by camelid** [comment]
You could still open a PR and get feedback from macro experts about how to do this without the feature gate.

**Comment by m-ou-se** [comment]
cc @rust-lang/libs-api @rust-lang/project-edition-2021

We have a few weeks left before the next beta branches off, so we have time for an FCP without delaying this to a later Rust version.

Summary: `unreachable!()` turns out to be broken in a similar way as `panic` and `assert` were in Rust 2015 and Rust 2018: `unreachable!("{}")` worked 'fine'. This was missed, because this isn't the case for `todo!()` and `unimplemented!()`. This was unfortunately not included in the 2021 edition panic changes, but it seems best to add it to the 2021 edition now, only a few versions late. This won't break any Rust 2015/2018 code, but this is breaking for any Rust 2021 code using `unreachable!(var)` or `unreachable!(123)` or `unreachable!("{}")`. All 'normal' cases of this macro are unaffected. There's probably not many problematic invocations of this macro in general, and much less in Rust 2021 code, considering how recently that edition has been available.

#93179 contains the fix *and* upgrades the panic migration lint to also cover this case. Every instance of the problematic case of `unreachable!()` in Rust 2015/2018 will get a diagnostic with a correct (machine applicable) suggestion.

I just see this as a bug that needs fixing, as the decision to make the panic macros consistent in 2021 has already been made. But since this is technically breakage, let's quickly check some boxes or raise some concerns:

@rfcbot merge

**Comment by nikomatsakis** [comment]
Just catching up on this. Nice catch, @m-ou-se, and good hustle on fixing it, @Urgau

**Comment by Arnavion** [comment]
@m-ou-se @Urgau Will this be in 1.59.0? I don't see it in the release notes, but I do see the fix in the `beta` git branch. If it's going to be in 1.59.0, could the release notes be updated to mention it?

**Comment by jhpratt** [comment]
This is in fact on beta: [playground](https://play.rust-lang.org/?version=beta&mode=debug&edition=2021&gist=4a6209c6ba69c06d6e47af703265f91e)

**Comment by Arnavion** [comment]
Yes, as I said it's in the beta branch but not mentioned in the release notes for the upcoming 1.59.0. So if it's confirmed that it will be in 1.59.0, then it would be great if the release notes could be updated to mention it.

**Comment by Urgau** [comment]
Yes it will be 1.59.0. cc @Mark-Simulacrum about the change not being in the release notes.

**Comment by Mark-Simulacrum** [comment]
https://github.com/rust-lang/rust/pull/94265 includes a note about this into the 1.59 release notes.

**Comment by jqnatividad** [comment]
Folks, reading the 1.59 release notes, it's odd that the markdown link to this issue is not rendering.

https://github.com/rust-lang/rust/blob/stable/RELEASES.md#compatibility-notes

**Comment by Urgau** [comment]
@jqnatividad Already reported [here](https://github.com/rust-lang/rust/issues/94278#issuecomment-1048646087) with a response [here](https://github.com/rust-lang/rust/issues/94278#issuecomment-1048743791), but basically fixing this rendering issue would required a complete rebuild of all the artifacts of 1.59.0 which don't seems worth while.

**Comment by Urgau** [comment]
> Why was there no future-incompat warning for this? The first time I saw it was when a stable compiler upgrade broke my code.

See https://github.com/rust-lang/rust/issues/92137#issuecomment-1019519285, in particular:
> There's probably not many problematic invocations of this macro in general, and much less in Rust 2021 code, considering how recently that edition has been available.

And

> I just see this as a bug that needs fixing, as the decision to make the panic macros consistent in 2021 has already been made. But since this is technically breakage, let's quickly check some boxes or raise some concerns:
