### ISSUE TITLE
"Bad file descriptor" appending to file from command on Windows Git Bash

### ISSUE THREAD

**Issue by 95jonpet** [rust-lang/rust#92136]
The following code for appending the output of a `Command` to a file works as expected on Linux (Ubuntu 20.10), but not on Windows (11).

```rust
use std::{fs::OpenOptions, process::Command};

// The following example works on Linux, but not on Windows.
fn main() {
    let file = OpenOptions::new()
        .append(true) // Works if replaced by .write(true)
        .create(true)
        .open("output-file")
        .unwrap();

    let mut command = Command::new("echo");
    command.arg("test");
    command.stdout(file);

    command.spawn().unwrap().wait().unwrap();
}
```

The expected result is that the file `output-file` is created on the first execution and that each execution appends "test" to the same file. This works as intended on Linux.

On Windows, the same code fails with:
> echo: write error: Bad file descriptor

There are no errors when using `write(true)` rather than `append(true)` on Windows.

I have tried with other commands on Windows, but there seems to be no difference.

### Meta

Non-working Windows `rustc --version --verbose`:
```
rustc 1.57.0 (f1edd0429 2021-11-29)
binary: rustc
commit-hash: f1edd0429582dd29cccacaf50fd134b05593bd9c
commit-date: 2021-11-29
host: x86_64-pc-windows-msvc
release: 1.57.0
LLVM version: 13.0.0
```

Working Linux `rustc --version --verbose`:
```
rustc 1.57.0 (f1edd0429 2021-11-29)
binary: rustc
commit-hash: f1edd0429582dd29cccacaf50fd134b05593bd9c
commit-date: 2021-11-29
host: x86_64-unknown-linux-gnu
release: 1.57.0
LLVM version: 13.0.0
```

No additional information is provided when running with `RUST_BACKTRACE=1`.

**Comment by ChrisDenton** [comment]
Hm, this is hard to diagnose. `echo` is not a Windows command and `bad file descriptor` is not a Windows error message. Are you running in a special environment? Maybe msys?

**Comment by 95jonpet** [comment]
I first tried it in _Git Bash_, and it did not work.

The code above works as intended in _PowerShell_ with the `cacls` command and no arguments.
I guess that the problem could lie with how the unixlike utils, provided by Git Bash, work.

**Comment by ChrisDenton** [comment]
I suspect it's an issue with git bash utilities. If I make my own simple echo it appears to work:

```rust
// echo.rs
use std::io::{self, Write};
use std::env;

fn main() -> io::Result<()> {
    let arg = env::args().nth(1).unwrap_or(String::new());
    writeln!(io::stdout(), "{}", arg)?;
    Ok(())
}
```
