### ISSUE TITLE
Lint unused_qualifications should have a machine-applicable suggestion

### ISSUE THREAD

**Issue by jplatte** [rust-lang/rust#92198]
In the middle of a large refactoring that was mostly automated by rust-analyzer's structural-search-and-replace, I had a lot of qualified paths that shouldn't be qualified. I made do with a regular text-based search-and-replace since I couldn't find a better way, but I think that better way could have been `cargo fix`, because introducing an import for the relevant type once per file is much easier than replacing all uses manually.

As such, it would be nice if the unnecessary qualification lint had a machine-applicable suggestion attached to it.

However, one interesting thing about this is that I also had warnings about the import for that same type being unused. I don't know whether it would be possible with the current compiler infrastructure to create mutually-exclusive suggestions. Either way the suggestion would be helpful, since a simple `#![allow(unused_imports)]` could disable the automatic removal of the imports.

**Comment by jyn514** [comment]
Mentoring instructions: Add a new [`BuiltinLintDiagnostic`](https://doc.rust-lang.org/stable/nightly-rustc/rustc_lint_defs/enum.BuiltinLintDiagnostics.html) for this lint which has a `#[suggestion]` and change https://github.com/rust-lang/rust/blob/df0d9b492da81a647eedf17210cf55b86a44888c/compiler/rustc_resolve/src/late.rs#L3843-L3851 to use [`buffer_lint_with_diagnostic`](https://doc.rust-lang.org/stable/nightly-rustc/rustc_lint_defs/struct.LintBuffer.html#method.buffer_lint_with_diagnostic).
