### ISSUE TITLE
rustdoc: Use the concrete type of `self` in the search-index

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#92205]
See the discussion starting at https://github.com/rust-lang/rust/pull/90630#issuecomment-999215498.

EDIT (@GuillaumeGomez): For example:

```rust
pub struct Foo;

impl Foo {
    pub fn something(&self) -> PathBuf { ... }
}
```

For the example above, if you use `Foo -> PathBuf` in the search, `something` won't show up because `&self` isn't "recognized"/"generated" in the search index as `Foo`.

**Comment by GuillaumeGomez** [comment]
I don't really have an opinion on this: it seems a bit counter-intuitive for me to look for `vec` inside the arguments of its methods but I can see the value of it too. A bit tricky.

**Comment by camelid** [comment]
I think it's really bizarre for `vec -> usize` to not return `Vec::capacity`. Many uses of a type are in its methods; if we don't make this change, those will just be ignored.

**Comment by GuillaumeGomez** [comment]
I'm strongly biased here because it's how it's always been. But I think it'd be a good change. :+1:

**Comment by jsha** [comment]
I agree, this would be a good change. I would expect a search for `vec -> usize` to return `Vec::capacity`.
