### ISSUE TITLE
Alignments > 32 don't work on TLS on macos

### ISSUE THREAD

**Issue by glandium** [rust-lang/rust#92241]
Edit: this is not what's going on, see https://github.com/rust-lang/rust/issues/92241#issuecomment-1000656624

Original report, for posterity:
<details>

STR:
- `cargo new testcase ; cd testcase`
- Take the example code from the [LocalKey documentation](https://doc.rust-lang.org/std/thread/struct.LocalKey.html#examples) (I stopped after the first `FOO.with()`) and stick it in `src/main.rs`.
- cargo build
- Run `otool -l $(grep -l __thread_vars target/debug/deps/*.o)`
- In the output of the above otool command, look for `sectname __thread_vars`. For that section, you'll see `align 2^0 (1)`.

The alignment should at least be the alignment for RefCell<u32>, which is 8.

This is not causing problems because for some reason ld64 over-aligns the `__thread_vars` section in the final binary. It makes the alignment at 8, and further aligns at 16.
BUT, ld64.lld marks the alignment as 1, and aligns at 8. Which is fine... until you have a thread local variable that uses a value that needs an alignment of 16 and runs instructions that trap if the value is not aligned (this happens in practice when using a ChaCha ThreadRng with AVX2 ; you can be lucky and have the variable aligned by miracle, but that is brittle).
</details>

`rustc --version --verbose`:
```
rustc 1.59.0-nightly (c09a9529c 2021-12-23)
binary: rustc
commit-hash: c09a9529c51cde41c1101e56049d418edb07bf71
commit-date: 2021-12-23
host: x86_64-apple-darwin
release: 1.59.0-nightly
LLVM version: 13.0.0
```

**Comment by eddyb** [comment]
It should be easier to make a simpler example by using `#[thread_local]` directly and `rustc`:
```console
$ echo '#![feature(thread_local)] #[thread_local] #[no_mangle] pub static FOO: u64 = 0;' \
  | rustc --crate-type lib - --emit=obj -o foo.o
$ readelf -S foo.o
There are 6 section headers, starting at offset 0xe0:

Section Headers:
  [Nr] Name              Type             Address           Offset
       Size              EntSize          Flags  Link  Info  Align
  [ 0]                   NULL             0000000000000000  00000000
       0000000000000000  0000000000000000           0     0     0
  [ 1] .strtab           STRTAB           0000000000000000  00000090
       000000000000004a  0000000000000000           0     0     1
  [ 2] .text             PROGBITS         0000000000000000  00000040
       0000000000000000  0000000000000000  AX       0     0     4
  [ 3] .tdata.FOO        PROGBITS         0000000000000000  00000040
       0000000000000008  0000000000000000 WAT       0     0     8
  [ 4] .note.GNU-stack   PROGBITS         0000000000000000  00000048
       0000000000000000  0000000000000000           0     0     1
  [ 5] .symtab           SYMTAB           0000000000000000  00000048
       0000000000000048  0000000000000018           1     2     8
Key to Flags:
  W (write), A (alloc), X (execute), M (merge), S (strings), I (info),
  L (link order), O (extra OS processing required), G (group), T (TLS),
  C (compressed), x (unknown), o (OS specific), E (exclude),
  l (large), p (processor specific)
```

For better readability, just the header and the `.tadata.FOO` entry:
```
  [ 3] .tdata.FOO        PROGBITS         0000000000000000  00000040
       0000000000000008  0000000000000000 WAT       0     0     8
```

So `x86_64-unknown-linux-gnu` works as intended, and the `align 8` makes it from LLVM IR to ELF.
To be clear, [the LLVM IR](https://godbolt.org/z/Ye5efnbdP) contains the `align 8`:
```
@FOO = thread_local constant <{ [8 x i8] }> zeroinitializer, align 8
```

I can't see how `x86_64-apple-darwin` would produce different LLVM IR, so if there's any bug, it's in LLVM, and you should be reproduce by using Clang - using something like this: https://godbolt.org/z/qrb8sv99W.

**Comment by glandium** [comment]
It turns out the original problem is likely a bug in rand_chacha/ppv_lite86.

But while looking into this, I also found out that alignments > 32 don't work on TLS on macos at all...

**Comment by eddyb** [comment]
Related: #90959. cc @rust-lang/wg-llvm 

This might not be fixable in LLVM if the platform refuses to support the usecase, short of reserving extra space and generating runtime alignment logic - we may "just" want to error instead (if we know upper bounds).

**Comment by glandium** [comment]
It's the same thing. I might just have been lucky when testing alignment == 32.

Duplicate: #90959

**Comment by glandium** [comment]
> It turns out the original problem is likely a bug in rand_chacha/ppv_lite86.

It turns out it's likely a bug in lld.

**Comment by glandium** [comment]
For the curious: https://reviews.llvm.org/D116263
