### ISSUE TITLE
Documentation addition request

### ISSUE THREAD

**Issue by alper** [rust-lang/rust#92276]
I'm trying to implement Debug occasionally, then I hit this page:
https://doc.rust-lang.org/stable/core/fmt/trait.Debug.html

The examples on that page do not contain something that uses `write!` so I usually google my way to the same SO answer: https://stackoverflow.com/a/22243806/102315

Could the documentation there be expanded to add this?

**Comment by sfackler** [comment]
The standard way to implement debug is to use the debug builders `fmt.debug_struct(..)`, which is documented there.

**Comment by BGR360** [comment]
I think this is a very reasonable ask. It doesn't make much sense to use the debug builders for very simple implementations of `Debug`, and for those just starting out, and the importance of using the builders for more complicated Debug impls is minimal.

@alper you'd be welcome to submit a PR with a proposed example! You just need to edit the rustdoc comment for `Debug`:

https://github.com/rust-lang/rust/blob/51e8031e14a899477a5e2d78ce461cab31123354/library/core/src/fmt/mod.rs#L505

@rustbot label +T-docs-rs A-docs +E-easy

**Comment by alper** [comment]
Thanks, @BGR360! My PR is linked above.

**Comment by alper** [comment]
Thanks for the prodding. My change has now been merged. 🎉
