### ISSUE TITLE
debuginfo: Describe item and member visibility in debugging information 

### ISSUE THREAD

**Issue by michaelwoerister** [rust-lang/rust#9228]
This can be done using the `flags` parameter of various `llvm::DIBuilder` methods (e.g. `createMemberType`).

**Comment by steveklabnik** [comment]
Triage: no idea. @michaelwoerister what's the status of this today?

**Comment by michaelwoerister** [comment]
Still not implement, AFAIK.

**Comment by steveklabnik** [comment]
Triage: I am not aware of any changes here.

**Comment by ernestask** [comment]
@rustbot claim

I have something that works for the case in #32919, would like to give proposing it a shot.

**Comment by Alexendoo** [comment]
Triage: Hi, are you still working on this issue @ernestask?

**Comment by wesleywiser** [comment]
Visited during wg-debugging triage. Representing Rust semantics in debuginfo is useful but this kind of thing doesn't tend to affect the experience of debugging Rust code (this sort of thing is often used by tools other than the debugger which build on top of DWARF/CodeView). Marking as P-low.
