### ISSUE TITLE
Documentation for `std::column` should state that it counts code points, not bytes or graphemes

### ISSUE THREAD

**Issue by ecstatic-morse** [rust-lang/rust#92301]
`std::column` counts the number of unicode characters that precede its invocation in that same line (then adds one). However, this behavior is not stated explicitly in [its documentation](https://doc.rust-lang.org/std/macro.column.html). It's not unusual for programming languages or editors to use byte indexes for columns (vim does this for example), so I think it's worth clarifying.

**Comment by clarfonthey** [comment]
Perhaps there could be a version that does take into account graphemes, since the compiler itself already does this to ensure that errors are pointed to properly in the compiler output?
