### ISSUE TITLE
`x.py setup` stopped being able to link toolchains at some point

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#92319]
I tried this code on a fresh git clone of rust-lang/rust:

```
x.py setup library
```

I expected to see this happen: setup works without errors.

Instead, this happened: x.py gives an error:

```
Welcome to the Rust project! What do you want to do with x.py?
a) library: Contribute to the standard library
b) compiler: Contribute to the compiler itself
c) codegen: Contribute to the compiler, and also modify LLVM or codegen
d) tools: Contribute to tools which depend on the compiler, but do not modify it directly (e.g. rustdoc, clippy, miri)
e) user: Install Rust from source
Please choose one (a/b/c/d/e): b
`x.py` will now use the configuration at .../rust/src/bootstrap/defaults/config.compiler.toml

`rustup` failed to link stage 1 build to `stage1` toolchain
To manually link stage 1 build to `stage1` toolchain, run:

            `rustup toolchain link stage1 build/x86_64-unknown-linux-gnu/stage1`
```

### Meta

This feature was introduced in https://github.com/rust-lang/rust/pull/89212 and worked at that time. @Sl1mb0 do you have time to look into this? The original bug report was from Nazar Mokrynskyi [on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/122652-new-members/topic/Building.2Ftesting.20rust.20itself.20for.20the.20first.20time), not sure their github username.

**Comment by Sl1mb0** [comment]
Yes, I'll take a look over the next few days.

**Comment by yerke** [comment]
Hello. Is there a workaround for this issue for now?
I got
```
Welcome to the Rust project! What do you want to do with x.py?
a) library: Contribute to the standard library
b) compiler: Contribute to the compiler itself
c) codegen: Contribute to the compiler, and also modify LLVM or codegen
d) tools: Contribute to tools which depend on the compiler, but do not modify it directly (e.g. rustdoc, clippy, miri)
e) user: Install Rust from source
Please choose one (a/b/c/d/e): b
`x.py` will now use the configuration at /Users/yerke/Development/rust/src/bootstrap/defaults/config.compiler.toml

`rustup` failed to link stage 1 build to `stage1` toolchain
To manually link stage 1 build to `stage1` toolchain, run:

            `rustup toolchain link stage1 build/aarch64-apple-darwin/stage1`
```

But when I ran `rustup toolchain link stage1 build/aarch64-apple-darwin/stage1`, I got `error: not a directory: 'build/aarch64-apple-darwin/stage1/lib'`.

**Comment by yerke** [comment]
OK. After reading the zulip thread, I figure out how to work around it. After running `./x.py build`, `rustup toolchain link stage1 build/aarch64-apple-darwin/stage1` succeeded.
