### ISSUE TITLE
rustdoc: Regression in whitespacing inside macro_rules matchers

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust#92331]
```rust
#[macro_export]
macro_rules! repro {
    ($e:expr, std::path) => {};
}
```

### Before:

This preserves the spacing in the way that the macro author wrote, and exactly the way that they intend for the macro user to write those spaces on their end.

![Screenshot from 2021-12-27 13-13-25](https://user-images.githubusercontent.com/1940490/147507661-4a3e3d52-9814-4a15-8072-4a1ed73e364c.png)

### After:

The person calling the macro needs to reverse engineer where to add/delete spaces in order to get a readable result.

![Screenshot from 2021-12-27 13-13-46](https://user-images.githubusercontent.com/1940490/147507667-8988286d-18d7-48c6-8277-967201f51ee0.png)

I haven't bisected but it seems likely from skimming the implementation that this is related to #86282. Overall I think #86282 would tend to be net negative for the vast majority of macros. @camelid @jyn514 is there perhaps some other way to deal with the edge cases that didn't have proper source code for rustdoc to copy?

**Comment by camelid** [comment]
Yeah, I know the formatting regressions from that PR were not great, but it fixed a bunch of bugs. In general, I think rustdoc shouldn't be relying on the source code except for the actual source code view.
