### ISSUE TITLE
rustdoc doesn't handle generic associated types properly

### ISSUE THREAD

**Issue by JanBeh** [rust-lang/rust#92341]
I tried this code:

```rust
pub trait Machine<'a> {
    /// Data type representing values passed to or returned from machine
    type Datum<'b>
    where
        Self: 'b;
    /// Function (for example returned by [`Compile::compile`])
    /// which can be executed by the machine
    type Function<'b>: Function<Datum = Self::Datum<'b>>
    where
        Self: 'b;
}
```

I expected `rustdoc` to create proper documentation for these GATs.

Instead, `rustdoc` created the following output:

```rust
pub trait Machine<'a> {
    type Datum;
    type Function: Function<Datum = Self::Datum>;
}
```

and

```text
Associated Types
[src]
type Datum

Data type representing values passed to or returned from machine
[src]
type Function: Function<Datum = Self::Datum>

Function (for example returned by Compile::compile) which can be executed by the machine
```

The lifetime argument `'b` is missing in the documentation.

### Meta
`rustc --version --verbose`:
```
rustc 1.59.0-nightly (f8abed9ed 2021-12-26)
binary: rustc
commit-hash: f8abed9ed48bace6be0087bcd44ed534e239b8d8
commit-date: 2021-12-26
host: x86_64-unknown-freebsd
release: 1.59.0-nightly
LLVM version: 13.0.0
```

**Comment by compiler-errors** [comment]
@rustbot claim

> having proper documentation of code with GATs is kind of a big ergonomics win.

Strongly agree. Stabilizing GATs when rustdocs don't properly render associated types' own generics is kinda a big problem, IMO.

> this can be demoted to not blocking if it actually turns out to be a really difficult problem or something.

As far as I can tell, this doesn't seem _too_ hard. I'm working through it right now. I've got GATs rendering in trait definitions fine right now, working through some rendering issues, but I can probably get help in the rustdoc zulip.
