### ISSUE TITLE
Tracking Issue for constifying `Result` methods that drop values

### ISSUE THREAD

**Issue by clarfonthey** [rust-lang/rust#92384]
Feature gate: `#![feature(const_result_drop)]`

### Public API

This is a tracking issue for the `const_result_drop` feature, which includes constness for the following methods:

```rust
impl<T, E> Result<T, E> {
    // will drop error
    pub const fn ok(self) -> Option<T>
    where
        E: ~const Drop;

    // will drop ok
    pub const fn err(self) -> Option<E>
    where
        T: ~const Drop;

    // will drop error or the argument
    pub const fn and<U>(self, res: Result<U, E>) -> Result<U, E>
    where
        T: ~const Drop,
        U: ~const Drop,
        E: ~const Drop;
    
    // will drop ok or the argument
    pub const fn or<F>(self, res: Result<T, F>) -> Result<T, F>
    where
        T: ~const Drop,
        E: ~const Drop,
        F: ~const Drop;

    // will drop error or the argument
    pub const fn unwrap_or(self, default: T) -> T
    where
        T: ~const Drop,
        E: ~const Drop;
}
```

Note that these depend on the semantics for `~const Drop`, which is (probably) tracked in #67792.

### Steps / History

- [x] Implementation: #92385
- [ ] Final comment period (FCP)
- [ ] Stabilization PR

### Unresolved Questions

- None yet.

**Comment by clarfonthey** [comment]
Turns out you actually can't make these const, at least for now. So, closing.

**Comment by clarfonthey** [comment]
Reopened now that I've found a proper way to do this. Linked the tracking issue for `~const` since this depends on the semantics of `~const Drop`.

**Comment by jhpratt** [comment]
Duplicate of #82814?

**Comment by clarfonthey** [comment]
That appears to be a meta tracking issue, this is specifically for these methods.

**Comment by jhpratt** [comment]
At least when I created it, it was not intended to be a meta issue. `Result::as_mut` and `Result::transpose` point directly to that as their tracking issue.

**Comment by clarfonthey** [comment]
Yes, but for now, these methods point to this one, since they presumably would need their own FCP.

**Comment by jhpratt** [comment]
I figured it would be a partial stabilization of #82814. Not a big deal either way, just wanted to bring it to your attention :slightly_smiling_face:

**Comment by RalfJung** [comment]
This got removed by https://github.com/rust-lang/rust/pull/110393.
