### ISSUE TITLE
Overflow in sidebar heading "See all _ items"

### ISSUE THREAD

**Issue by jsha** [rust-lang/rust#92421]
When a crate name is long, the "See all `<crate name>` items" heading in the sidebar overflows its box.

E.g.: https://docs.rs/trillium-caching-headers/0.1.0/trillium_caching_headers/index.html
 
![image](https://user-images.githubusercontent.com/220205/147709544-de8a0f87-8607-4092-813c-3c0106a10c79.png)

Note that `Crate trillium_caching_headers` above it does not overflow, because it has `word-wrap: break-word`. Perhaps we should consider applying that to everything as a default (since we often have this type of overflow problem), and override that default in specific places, like code examples, where we'd rather have a horizontal scroll.

Another recent example of overflowing a box was #89972 (and a fix in #90018).

cc @GuillaumeGomez

**Comment by jsha** [comment]
Alternately we could ellipsize it like we do for some other sidebar items:

![image](https://user-images.githubusercontent.com/220205/147783375-4714269e-0c9a-4bef-9059-140df44210a9.png)

We should pick one strategy or the other for the sidebar, or come up with some reasoning why we should do it differently for headings vs links.

**Comment by jsha** [comment]
Actually, the ellipsization is broken, because it will ellipsize _and_ wrap in some situations:

![image](https://user-images.githubusercontent.com/220205/147789693-baacf450-7b99-479d-80c8-34922b9940a5.png)

For instance `FromIterator<Box<str, Global>>` gets shown as `FromIterator<Bo...` and `Global>>` on the next line.

The example is from the sidebar for String, but with a larger font size than the default.

**Comment by GuillaumeGomez** [comment]
It has been fixed differently in the end:

![Screenshot from 2022-02-15 11-50-48](https://user-images.githubusercontent.com/3050060/154047406-434ba53a-533d-412d-94a2-c6b99c2a220b.png)
