### ISSUE TITLE
Error could use some improvement: slice indices are of type `usize` or ranges of `usize`

### ISSUE THREAD

**Issue by dcormier** [rust-lang/rust#92439]
I had someone new to Rust ask me about an error he was running into. The problem was very simple, but the error was not clear enough for him to know that. And he was far from the only person to trip over this same error:

- https://www.reddit.com/r/rust/comments/8k4vwc/rust_noob_using_a_value_from_an_array_as_an_index/
- https://users.rust-lang.org/t/solved-need-help-with-slice/24296
- https://stackoverflow.com/questions/56517606/how-do-i-use-a-paremeter-to-index-an-array-in-rust

A quick search shows plenty more who struggled with this error. Given that users seem to have trouble with it, it seems like the error should be improved.

Given [the following code](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=d88f600e401f1f1c83da41dd46b254a6):

```rust
struct Move {
    x: u8,
    y: u8,
}

#[derive(Default)]
struct GameState {
    grid: [[u8; 3]; 3],
}

impl GameState {
    fn input_move(&mut self, m: Move) {
        self.grid[m.x][m.y] = 1;
    }
}

fn main() {
    let mut game = GameState::default();

    game.input_move(Move { x: 0, y: 0 });
}
```

The current output is:

```text
error[E0277]: the type `[[u8; 3]]` cannot be indexed by `u8`
  --> src/main.rs:13:9
   |
13 |         self.grid[m.x][m.y] = 1;
   |         ^^^^^^^^^^^^^^ slice indices are of type `usize` or ranges of `usize`
   |
   = help: the trait `SliceIndex<[[u8; 3]]>` is not implemented for `u8`
   = note: required because of the requirements on the impl of `Index<u8>` for `[[u8; 3]]`

For more information about this error, try `rustc --explain E0277`.
```

Ideally the output should be more clear that the value being used to index is not `usize`. Perhaps something like:

```text
error[E0277]: the type `[[u8; 3]]` cannot be indexed by `u8`
  --> src/main.rs:13:9
   |
13 |         self.grid[m.x][m.y] = 1;
   |                   ^^^ slice indices must be of type `usize` or ranges of `usize`
   |
   = help: the trait `SliceIndex<[[u8; 3]]>` is not implemented for `u8`
   = note: required because of the requirements on the impl of `Index<u8>` for `[[u8; 3]]`

For more information about this error, try `rustc --explain E0277`.
```

The tweak to the language may make it more clear that the value being used to index the slice is not the type it's required to be. Additionally, pointing more specifically at the value being used to index may help the user to know where the problem is.

**Comment by veera-sivarajan** [comment]
Fixed since `rustc 1.64.0`: https://rust.godbolt.org/z/cWa1Pvzro
