### ISSUE TITLE
Tracking Issue for `const` forwarding impls for `Fn` family traits

### ISSUE THREAD

**Issue by fee1-dead** [rust-lang/rust#92474]
Feature gate: `#![feature(const_closure_impls)]`

This is a tracking issue for `const` forwarding impls for `Fn` family traits.

### Public API

```rust
// core::ops
impl<A, F: ?Sized> const Fn<A> for &F
where
    F: ~const Fn<A>,
impl<A, F: ?Sized> const FnMut<A> for &F
where
    F: ~const Fn<A>,
impl<A, F: ?Sized> const FnOnce<A> for &F
where
    F: ~const Fn<A>,
impl<A, F: ?Sized> const FnMut<A> for &mut F
where
    F: ~const FnMut<A>,
impl<A, F: ?Sized> const FnOnce<A> for &mut F
where
    F: ~const FnMut<A>,
```

### Steps / History

- [ ] Implementation: #92433
- [ ] Final comment period (FCP)
- [ ] Stabilization PR

### Unresolved Questions

- None yet.

**Comment by chriss0612** [comment]
Is this not the same as #101803?
This tracking issue can probably be closed.

**Comment by fee1-dead** [comment]
dups #101803 which got landed before the const iterator pr
