### ISSUE TITLE
`impl core::fmt::Write` for `rustdoc::html::render::Buffer`

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#92563]
A further performance improvement here would be to make sure that `Buffer` impls `core::fmt::Write`, in which case we could use `render_into(buf)` rather than `render()`, avoiding the allocation of a temporary `String` here. `Buffer` internally seems to just hold a `String` and it has `write_str()` and `write_fmt()` methods already, so perhaps it would make sense to implement that trait? I'm not sure how big/relevant the performance improvement would be.

_Originally posted by @djc in https://github.com/rust-lang/rust/pull/92526#discussion_r777689256_

**Comment by djc** [comment]
Since `askama::Template` implementers get a `std::fmt::Display` generated for them by Askama's macro, the simpler way to get the meat of this change would probably be to call `buf.write_fmt(format_args!("{}", tmpl));`

**Comment by mfrw** [comment]
@rustbot claim
Let me take a stab at it :)
