### ISSUE TITLE
Rustdoc: Incorrect closing quotation marks in text

### ISSUE THREAD

**Issue by tsoutsman** [rust-lang/rust#92578]
Hi,
Rustdoc seems to be incorrectly generating quotation marks if the enclosed string has leading or trailing spaces.
```rust
/// Single space at start: " like this".
/// Single space at end: "like this ".
/// Spaces at start and end: " like this ".
/// No spaces: "like this".
```
gets rendered like this:
![image](https://user-images.githubusercontent.com/32662194/148194128-e5c5a6b1-dbf4-4152-afac-81e8db0ede08.png)
Only the last one has the correct closing quotation mark.

## Version
`rustdoc 1.59.0-nightly (7d6f94817 2022-01-04)`

@rustbot modify labels: +A-rustdoc-ui +T-rustdoc

**Comment by GuillaumeGomez** [comment]
Based on the [commonmark reference](https://spec.commonmark.org/dingus/?text=Single%20space%20at%20start%3A%20%22%20like%20this%22.%0ASingle%20space%20at%20end%3A%20%22like%20this%20%22.%0ASpaces%20at%20start%20and%20end%3A%20%22%20like%20this%20%22.%0ANo%20spaces%3A%20%22like%20this%22.&smart=1), Only `Single space at start` is invalid, the rest are fine.

**Comment by GuillaumeGomez** [comment]
I opened a PR in pulldown-cmark to fix it: https://github.com/raphlinus/pulldown-cmark/pull/565

**Comment by GuillaumeGomez** [comment]
As mentioned in the pulldown-cmark PR (https://github.com/raphlinus/pulldown-cmark/pull/565), it won't be fixed so I'm closing this issue as won't fix.
