### ISSUE TITLE
core::iter doc: statement "an open-ended range is an infinite iterator" is wrong

### ISSUE THREAD

**Issue by safinaskar** [rust-lang/rust#92638]
Docs for `core::iter` say: "an open-ended range is an infinite iterator". This is wrong. Such iterator will eventually overflow

**Comment by the8472** [comment]
It's not wrong in general. Ranges are generic, so it depends on the type parameter. The range-from docs provide more details.
https://doc.rust-lang.org/std/ops/struct.RangeFrom.html

**Comment by Dylan-DPC** [comment]
Closing this as the example is used for illustrative purposes and this is true only for this specific case. If needed we can provide a better example but not sure ther'es one that's clear enough and probably not a good enough reason to keep this issue open for years
