### ISSUE TITLE
feat: matches! to return data in an Option

### ISSUE THREAD

**Issue by numero-744** [rust-lang/rust#92655]
`matches!` is a great tool to do the job of `.is_variant()` when not available, but it is not useful to replace `.as_variant()`, returning an `Option<T>`. It could be made possible, for instance by adding a rule with one more argument representing the value returned in the option. This new rule would be quite the same as the existing one.

```rust
macro_rules! matches {
    ($expression:expr, $(|)? $( $pattern:pat_param )|+ $( if $guard: expr )? $(,)?) => {
        match $expression {
            $( $pattern )|+ $( if $guard )? => true,
            _ => false
        }
    };
    ($expression:expr, $(|)? $( $pattern:pat_param )|+ $( if $guard: expr )?, $value:expr $(,)?) => {
        match $expression {
            $( $pattern )|+ $( if $guard )? => Some($value),
            _ => None,
        }
    };
}
```

It could enable to do:

```rust
let foo = matches!(my_enum, MyEnum::MyVariant(v, _), v)?;
```

instead of

```rust
let foo = match my_enum {
    MyEnum::MyVariant(v, _) => v,
    _ => return None,
}
```

It is maybe related to #86112 because the new rule of the macro would have to accept variable declarations in the pattern.

### Discussion

Maybe being able to return two different types according to the number of given arguments can be confusing, so maybe another macro could be defined instead.

Also, this macro rule is kind of a `map` because `$value` can by any expression, so maybe a new macro called `map!` could be created instead of adding a rule to `matches!`.

**Comment by fmease** [comment]
Previous discussion https://github.com/rust-lang/rfcs/issues/2960.

**Comment by numero-744** [comment]
Thanks, I failed to find it.

I :+1:'d it and I actually think that another macro named `match_map!` is better because this name is really self-explaining about what the macro does.

https://crates.io/crates/bind_match does this (with a different name) and is indirectly pointed to in the comments.

Should I close this issue as a duplicate, then?
