### ISSUE TITLE
rustdoc: Merge "Structs", "Enums", "Unions", and "Type Definitions" sections on module pages

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#92656]
### Summary

Merge the following sections that appear on module (and crate) pages into a single "Types" section:

* Structs
* Enums
* Unions
* Type Definitions

### Why?

* Usually, the exact kind of type something is doesn't matter when you're looking at an overview.
* It can be confusing to have to so many sections, and it creates more places where you have to look for what you want.
* After the recent color reduction PR (#91480), the types are no longer colored differently, so it makes more sense to merge their sections.

**Comment by camelid** [comment]
cc @jsha

**Comment by jsha** [comment]
Terrific idea!

**Comment by GuillaumeGomez** [comment]
I'm not completely sold on the idea. Something about it is bothering me but I can't put the finger on it... Well, for now let's say I'm neutral.

**Comment by wackbyte** [comment]
I find the separate sections for different types easier to use and simpler to follow.

**Comment by kaylynn234** [comment]
I understand that the intent here is to simplify the sidebar and make things seem less verbose, but (particularly relating to type definitions) I'm not really a fan of the change. It can be very helpful to know when something falls into a specific "class" of type - without having to jump to its position in the documentation or inspect the source - and I would really hate to lose that. I wouldn't be opposed to making it some sort a configurable option, but I do think such a proposal does more harm to documentation than good.

I suppose one alternative would be to merge them into a `Types` section, *but* add a prefix to each name in the sidebar such as `struct`, `enum`, `union` and etc. That way you can have your cake and eat it too - there isn't a loss of information, but things do get unified nicely. One issue with that idea is the amount of horizontal space taken up by the sidebar, but I'm not sure how much of an impact that would have.

**Comment by ThePuzzlemaker** [comment]
I support this @kaylynn234.

I feel like doing this would be counterproductive. I've found that I've had many cases where I need to looking over a module and need to find a specific enum or struct but don't remember the name. And I can't necessarily search for it with `enum:` if I don't know the name, as doing something like just `enum:` doesn't work.

Take, for example, an AST module. If designed in a certain way, e.g. Rust's AST/HIR, it will have main structures `Foo` as well as `FooKind` enum. Often the module is already quite cluttered, and the structures usually don't contain all the information that you need, instead the enums. If the sections were combined it would become even harder to find a specific enum that you need, so either you have to search through a mess of types to find a struct and then navigate to the enum, or try to guess the name that you need.

**Comment by camelid** [comment]
Hmm, okay. I won't make this change then. What about just moving the sections so they're all next to each other? Currently, the type alias section is at the bottom, while the others are at the top. Instead, I think they should all be at the top.

**Comment by steffahn** [comment]
I don’t think type definitions should be grouped with the rest, it’s often important to _know_ that you’re dealing with a type synonym, in particular for custom versions of `Result` with a fixed error type. (I would also appreciate if a different color for type synonyms was re-introduced.)

<hr>

I’m not sure yet how to feel about `struct`s vs. `enum`s. An alternative, more systematic, point for distinguishing could be “abstract types” vs. “plain types”, the latter being structs or enums where all fields are public and non-hidden (and structs / variants are not `#[non_exhaustive]`). I’m not 100% sure where `#[non_exhaustive]` enums would fit into this picture, probably still on the “plain” side, not “abstract”.

Lots of primitive types would also become “plain”, i.e. grouped with enums.

**Comment by jsha** [comment]
FWIW, I'm still in favor of merging the sections. Yes, enums and structs are not exactly the same. But attention is a finite resource. By merging, we focus people on the big, important distinctions (between concrete types, traits, functions, macros and modules) rather than the less important ones - at least at the module summary page level. The pages and hover text will of course always make it clear whether something is an enum or a struct.

**Comment by camelid** [comment]
I do like the idea of just merging structs and enums. However, if we merge them but not type aliases, what would we call the section? "Algebraic data types" comes to mind, but that's a mouthful and would likely confuse new users.

**Comment by steffahn** [comment]
@camelid Just “data types”?

**Comment by camelid** [comment]
Perhaps. People may get confused that "data types" don't include type aliases though 🤷

**Comment by camelid** [comment]
> I do like the idea of just merging structs and enums. However, if we merge them but not type aliases, what would we call the section? "Algebraic data types" comes to mind, but that's a mouthful and would likely confuse new users.

Hmm, maybe just "types" and "type aliases" would be clear enough.

**Comment by aloucks** [comment]
> FWIW, I'm still in favor of merging the sections. Yes, enums and structs are not exactly the same. But attention is a finite resource. By merging, we focus people on the big, important distinctions (between concrete types, traits, functions, macros and modules) rather than the less important ones

I apologize for being blunt here, but you're missing the mark entirely. You're absolutely right that attention is a finite resource, but merging these sections (and making them all the same color) requires **more** attention, not less. When I'm searching for an enum, now I have to read through a much larger section and there is no longer any way to see what enums are available. You're forcing people with reading difficulties to read more instead of less. Having common items grouped together and color coded allows people to use visual cues to narrow down the amount of text that they need to process.

**Comment by camelid** [comment]
Could you elaborate on in what kinds of situations you'd be looking for an enum _in particular_, rather than any kind of type? I think that would help me understand your use case better.

**Comment by aloucks** [comment]
For example, I want to select an adapter based on a particular device API. I remember that this is a flag, so it's likely and enum, but I can't remember it's name. I scroll down until I see green and then start checking the items.  I find `Backend`.

https://docs.rs/wgpu/0.12.0/wgpu/

When you ask about looking for an enum _in particular_, why is enum being treated any differently than structs or traits? Why not merge all of the sections into one giant section and color code them all the same way? Why do we have groupings or visual cues at all? 

Let's take a step back and try to understand what problem we're trying to solve here. We want to make items more discoverable and easier to narrow down. Groups, color cues, and distinctive sections allow you to do that without having to read though large chunks of text.

**Comment by nox** [comment]
FYI I already asked for all those sections to be merged into a single one in https://github.com/rust-lang/rust/issues/64454. I understand that not everyone thinks the same way I do, so I'm not going to claim either way requires less or more attention than the other, and neither should anyone else.

**Comment by camelid** [comment]
> When you ask about looking for an enum in particular, why is enum being treated any differently than structs or traits? Why not merge all of the sections into one giant section and color code them all the same way? Why do we have groupings or visual cues at all?

I think of structs and enums as being very similar (they're both algebraic data types), and in fact, in languages related to Rust like Haskell and OCaml, the same language feature is used to represent both structs and enums. So I think of them as belonging to the same category, whereas traits are a different concept (behavior rather than data).

**Comment by camelid** [comment]
I'll close this issue since it seems many people prefer the current design.
