### ISSUE TITLE
Rustdoc: regression in intra-doc link to trait function

### ISSUE THREAD

**Issue by rnarubin** [rust-lang/rust#92662]
### Code

Example code:

```rust
#![deny(rustdoc::broken_intra_doc_links)]

use std::marker::PhantomData;

pub trait Bar<T> {
    fn bar(&self);
}

pub struct Foo<U>(PhantomData<U>);

impl<T, U> Bar<T> for Foo<U> {
    fn bar(&self) {}
}

/// link to [`Foo::bar`]
fn main() {}

```

### Version it worked on

docs build successfully on 1.57.0:
```
$ cargo +1.57.0 --version
cargo 1.57.0 (b2e52d7ca 2021-10-21)
$ cargo +1.57.0 doc
 Documenting trait-link-example v0.1.0 (/tmp/trait-link-example)
    Finished dev [unoptimized + debuginfo] target(s) in 0.53s
```

### Version with regression
docs fail to build on 1.59.0-nightly (358e79fe5 2022-01-04):
```
$ cargo +nightly-2022-01-07 --version
cargo 1.59.0-nightly (358e79fe5 2022-01-04)
$ cargo +nightly-2022-01-07 doc
 Documenting trait-link-example v0.1.0 (/tmp/trait-link-example)
error: unresolved link to `Foo::bar`
  --> src/main.rs:15:15
   |
15 | /// link to [`Foo::bar`]
   |               ^^^^^^^^ the struct `Foo` has no field or associated item named `bar`
   |
note: the lint level is defined here
  --> src/main.rs:1:9
   |
1  | #![deny(rustdoc::broken_intra_doc_links)]
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: could not document `trait-link-example`

Caused by:
  process didn't exit successfully: `rustdoc --edition=2018 --crate-type bin --crate-name trait_link_example src/main.rs -o /tmp/trait-link-example/target/doc --error-format=json --json=diagnostic-rendered-ansi,future-incompat --document-private-items -C metadata=af2f029e3f5db9a3 -L dependency=/tmp/trait-link-example/target/debug/deps --crate-version 0.1.0` (exit status: 1)
```

</p>
</details>

The generics appear necessary for the bug. Removing them from either the type or the trait resolves the failure.

**Comment by camelid** [comment]
Probably #92443.

---

searched nightlies: from nightly-2022-01-06 to nightly-2022-01-07
regressed nightly: nightly-2022-01-07
searched commit range: https://github.com/rust-lang/rust/compare/f1ce0e6a00593493a12e0e3662119786c761f375...cfa4ac66c194046f631ce076c75516ecfdeb77ee
regressed commit: https://github.com/rust-lang/rust/commit/cfa4ac66c194046f631ce076c75516ecfdeb77ee

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.1</summary>


Host triple: aarch64-apple-darwin
Reproduce with:
```bash
cargo bisect-rustc --preserve --start=2022-01-06 --end=2022-01-07 --regress=error -- doc
```
</details>

**Comment by mdibaiee** [comment]
@camelid just saw this, I think might be caused by this change:

https://github.com/rust-lang/rust/pull/92443/files#diff-53e2bb31a1a4804925f22caf5a4844d0b6ffc9f7f307d93ef6098d62381a5085R891

I'm looking into it 🤔
