### ISSUE TITLE
Cargo new Error

### ISSUE THREAD

**Issue by hikionori** [rust-lang/rust#92661]
Hi i have a problem with cargo.
When you start the project, everything is fine, but when you want to create a new project, you get such an error:
![image](https://user-images.githubusercontent.com/66259055/148625040-161f3e83-1fc5-4345-b0d2-43366ac8bbad.png)
I use all the newest versions of everything I need at the moment.
I've also tried reinstalling rust

**Comment by Aaron1011** [comment]
What does that error message say in English?

**Comment by hikionori** [comment]
> What does that error message say in English?

could not find the file specified(os error 2)

**Comment by MaulingMonkey** [comment]
Does `mkdir minigrep` succeed?
