### ISSUE TITLE
Tracking Issue for ptr_const_cast

### ISSUE THREAD

**Issue by Kixunil** [rust-lang/rust#92675]
Feature gate: `#![feature(ptr_const_cast)]`

This is a tracking issue for methods on pointers for casting constness without changing the type

### Public API

```rust
impl<T: ?Sized> *const T {
    pub fn as_mut(self) -> *mut T;
}

impl<T: ?Sized> *mut T {
    pub fn as_const(self) -> *const T;
}
```

### Steps / History

- [x] Implementation: #92657
- [ ] Final comment period (FCP)
- [ ] Stabilization PR

### Unresolved Questions

- ~~`*mut T` also already has `as_mut()` which does something different and has a different signature, adding a mehod of the same name to `*const T` could be confusing, so maybe a better name should be used. `cast_const`/`cast_mut` was suggested.~~ [Resolved to use `cast_*`](https://github.com/rust-lang/libs-team/issues/51#issuecomment-1190661872)

**Comment by josephlr** [comment]
I like this function (as it allows a codebase to avoid uses of `as` if they desire). I agree thta `as_mut()` could lead to some ambiguity, and `cast_mut` seems better to me. It's the most similar to `cast`, so having a similar name seems correct.

As noted in the documentation, a `cast_const` method isn't strictly necessary, but could be nice for symmetry's sake.

**Comment by Kixunil** [comment]
I'm starting to like `cast_` naming as it seems to be a bit more readable too. Will try to find the time for a PR. I don't mind anyone else doing it either. It's a trivial change anyway.

**Comment by cuviper** [comment]
Once they're called `cast_`, I wonder if we should also add a type parameter like the existing `cast` method, so you don't have to double up `.cast().cast_const()` etc.

**Comment by Kixunil** [comment]
@cuviper yes, not changing the type is the main point because it protects against refactors. You can already do both with `as`.

[More detailed explanation](https://internals.rust-lang.org/t/casting-constness-can-be-risky-heres-a-simple-fix/15933)

**Comment by joshtriplett** [comment]
Shall we rename these to `cast_*`, and also stabilize them?

@rfcbot merge
