### ISSUE TITLE
Default buffer size of `getcwd` for linux

### ISSUE THREAD

**Issue by inteon** [rust-lang/rust#92672]
It seems like, by default, the initial buffer size for the return value of `getcwd` is set to 512 bytes:
https://github.com/rust-lang/rust/blob/600820da45daa50870fe711d53938fc6a52edd35/library/std/src/sys/unix/os.rs#L139

The default in glibc is defined as follows (https://code.woboq.org/userspace/glibc/sysdeps/unix/sysv/linux/getcwd.c.html#61):
```
MAX (PATH_MAX, __getpagesize ())
```

This might cause some unnecessary linux kernel context switches for longer paths (multiple buffer resizes).
Is there a reason for not using a larger buffer (eg. identical to the glibc implementation)?

**Comment by the8472** [comment]
This should only make a difference for code that calls it in a loop, does that happen somewhere where it's not easily fixed?

**Comment by inteon** [comment]
ref: https://github.com/denoland/deno/pull/12056

Also, I'm asking this question out of curiosity, what is the main reason for the 512 bytes value?
It seems like most implementations use the PATH_MAX value, eg. Golang uses `Getwd` (https://go.dev/src/os/getwd.go).

**Comment by the8472** [comment]
See the discussion in #27930 which originally implemented it.

**Comment by inteon** [comment]
> See the discussion in #27930 which originally implemented it.

Thank you for the info, I'll do some further testing & create a PR in case I find something valuable.
