### ISSUE TITLE
Docs at doc.rust-lang.org/std have SelfTy instead of Self

### ISSUE THREAD

**Issue by safinaskar** [rust-lang/rust#92722]
Page https://doc.rust-lang.org/std/keyword.SelfTy.html shows up as `SelfTy` instead of `Self`. This is very confusing.

Possibly related: https://github.com/rust-lang/rust/pull/83678

**Comment by camelid** [comment]
Yeah, it's unfortunate, but it's intentional. It's a hack to fix an issue when installing docs.
