### ISSUE TITLE
Docs for primitive type helper modules should stay in their lane

### ISSUE THREAD

**Issue by camsteffen** [rust-lang/rust#92777]
Summary of primitive types with corresponding std modules:

| Primitive type | `std` module | `std` module docs first line |
| --- | --- | --- |
| [array] | [std::array] | Helper functions and types for fixed-length arrays.
| [char] | [std::char] | A character type.
| [slice] | [std::slice] | A dynamically-sized view into a contiguous sequence, [T].
| [str] | [std::str] | Unicode string slices.
| [pointer] | [std::ptr] | Manually manage memory through raw pointers.
| [f32] | [std::f32] | Constants specific to the f32 single-precision floating point type.
| [f64] | [std::f64] | Constants specific to the f64 double-precision floating point type.

Some of the std modules' documentation sound like documentation for the primitive type itself. Others do not. The `std::slice` and `slice` docs almost look like they are supposed to be identical but there are some minor (perhaps accidental) differences. `std::ptr` has some unique content that may be better fit for the `pointer` docs.

In general, I think the std docs should be very brief and primarily work as a signpost pointing to the primitive type docs. But of course they should also document the module itself, without sounding like "I am char". Some more specific conventions could be established.

[array]: https://doc.rust-lang.org/std/primitive.array.html
[char]: https://doc.rust-lang.org/std/primitive.char.html
[slice]: https://doc.rust-lang.org/std/primitive.slice.html
[str]: https://doc.rust-lang.org/std/primitive.str.html
[pointer]: https://doc.rust-lang.org/std/primitive.pointer.html
[f32]: https://doc.rust-lang.org/std/primitive.f32.html
[f64]: https://doc.rust-lang.org/std/primitive.f64.html
[std::array]: https://doc.rust-lang.org/std/array/index.html
[std::char]: https://doc.rust-lang.org/std/char/index.html
[std::slice]: https://doc.rust-lang.org/std/slice/index.html
[std::str]: https://doc.rust-lang.org/std/str/index.html
[std::ptr]: https://doc.rust-lang.org/std/ptr/index.html
[std::f32]: https://doc.rust-lang.org/std/f32/index.html
[std::f64]: https://doc.rust-lang.org/std/f64/index.html

**Comment by slightlyoutofphase** [comment]
On a semi-related note, as I mentioned [here](https://github.com/rust-lang/rust/issues/92234) it's IMO very confusing that on the page for `pointer`, the `Primitive Type pointer` methods list in fact includes all of `*const T`, `*mut T`, `*const [T]`, and `*mut [T]`, which leads to a large amount of duplicated method names in practice.
