### ISSUE TITLE
llvm_asm!() with indirects broken on LLVM 14

### ISSUE THREAD

**Issue by durin42** [rust-lang/rust#92794]
This broke at LLVM change bec726f5d20ecfdc4a1cd4076ddc6edb35a317e5 - I've spent some time poking at it but it looks like it may require the attention of someone a little more familiar with inline assembly than me. Basically we need to explicitly emit the elementtype(TYPE) attribute for each indirect argument of an inline assembly call. That's mostly easy for outputs, but for inputs I think it's going to take a bit of a refactor to make it work.

**Comment by nikic** [comment]
@Amanieu To avoid unnecessary work, how far away are we from just deleting llvm_asm, now that asm has been stabilized?

**Comment by Amanieu** [comment]
`llvm_asm!` can be useful since it has some features that are not available with plain `asm!` such as multi-constraints and memory constraints. However I doubt anyone is actually relying on these so I'm happy to go ahead and just remove it.
