### ISSUE TITLE
LLVM assertion failures hang with a modal dialog on Windows

### ISSUE THREAD

**Issue by hkratz** [rust-lang/rust#92829]
The Windows CI build with LLVM assertions enabled recently hung without an error message. It turned out to be an LLVM assertion failure resulting in a dialog which needed to be acknowledged, see https://github.com/rust-lang/rust/pull/92535#issuecomment-1011504777. 

According to the [assert documentation](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/assert-macro-assert-wassert?view=msvc-170) such a dialog is always displayed, but that is not the whole truth. Apparently [_CrtSetReportHook()](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/crtsetreporthook?redirectedfrom=MSDN&view=msvc-170) can be used to customize assertion failure handling. We should definitely make assertions failures exit with error after printing failure information to stderr instead of displaying a dialog and hanging.

@rustbot label O-windows

**Comment by Patrick-Poitras** [comment]
Could this be part of why we're getting so many hangs in the CI?

**Comment by hkratz** [comment]
@Patrick-Poitras That was responsible for four stuck `dist-x86_64-msvc-alt` builds recently. I don't think it was responsible for many timed out builds before that. IMHO the most common cause for timed out builds is that LLVM rebuilds time out on Apple.

**Comment by ehuss** [comment]
Posted #93402 with a possible solution.
