### ISSUE TITLE
~const bounds do not work when impling const Drop

### ISSUE THREAD

**Issue by DrMeepster** [rust-lang/rust#92881]
I encountered this issue while trying to remove `box_free`.

I tried this code:

```rust
#![feature(const_trait_impl, const_fn_trait_bound, const_mut_refs)]

trait X {
    fn x();
}

struct Y<T: X>(T);

impl<T: ~const X> const Drop for Y<T> {
    fn drop(&mut self) {
        T::x();
    }
}
```

I expected the code to compile.

Instead, I got the following error:
```
error[E0367]: `Drop` impl requires `T: X` but the struct it is implemented for does not
 --> src/lib.rs:9:9
  |
9 | impl<T: ~const X> const Drop for Y<T> {
  |         ^^^^^^^^
  |
note: the implementor must specify the same requirement
 --> src/lib.rs:7:1
  |
7 | struct Y<T: X>(T);
  | ^^^^^^^^^^^^^^^^^^
  ```

### Meta

`rustc --version --verbose`:
```
rustc 1.60.0-nightly (22e491ac7 2022-01-13)
binary: rustc
commit-hash: 22e491ac7ed454d34669151a8b6464cb643c9b41
commit-date: 2022-01-13
host: x86_64-pc-windows-msvc
release: 1.60.0-nightly
LLVM version: 13.0.0
```

</p>
</details>

**Comment by woppopo** [comment]
(temporary?) workaround: [play](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=cfd57f24f080437625dd21ba0ae52583)
```rust
#![feature(const_trait_impl, const_fn_trait_bound, const_mut_refs)]

trait X {
    fn x();
}

struct Y<T: X>(T);

impl<T: X> const Drop for Y<T> {
    fn drop(&mut self)
    where
        T: ~const X
    {
        T::x();
    }
}
```

**Comment by compiler-errors** [comment]
Might be enough to just replace `ConstIfConst` with `NotConst` when [comparing the list of predicates in `dropck`](https://github.com/rust-lang/rust/blob/master/compiler/rustc_typeck/src/check/dropck.rs#L234), if someone wants to try that.

**Comment by crlf0710** [comment]
cc @fee1-dead

**Comment by DrMeepster** [comment]
> workaround: [play](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=cfd57f24f080437625dd21ba0ae52583)

This workaround causes the type to impl `~const Drop` when it shouldn't causing errors when interpreting instead of during type checking. ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=87e9328cce442ed0b9ad35c22dd01b08)) This needs to be fixed too.

> Might be enough to just replace `ConstIfConst` with `NotConst` when [comparing the list of predicates in `dropck`](https://github.com/rust-lang/rust/blob/master/compiler/rustc_typeck/src/check/dropck.rs#L234), if someone wants to try that.

This isn't enough. The constness of the bound seems to not get checked at all.

**Comment by DrMeepster** [comment]
I'm not exactly sure how trait selection works, but I think the problem may be [here](https://doc.rust-lang.org/nightly/nightly-rustc/src/rustc_trait_selection/traits/select/candidate_assembly.rs.html#994), where only the constness of the impl is checked, and not any of the bounds.

**Comment by compiler-errors** [comment]
@DrMeepster you wouldn't believe that the same exact line was on my clipboard, and I was going to say that it was somewhere around `assemble_const_drop_candidates` :laughing: 

Yeah, it seems like we need to enforce that the `~const` bounds on the drop impl are actually const during confirmation.

**Comment by compiler-errors** [comment]
Perhaps need to add some real confirmation logic here: https://github.com/rust-lang/rust/blob/master/compiler/rustc_trait_selection/src/traits/select/confirmation.rs#L162

**Comment by compiler-errors** [comment]
I'll take a stab at this, if nobody else is planning on it already!
@rustbot claim

cc @fee1-dead: 
I'm planning on rewriting `assemble_const_drop_candidates` to select a user-provided `impl const Drop` if it is provided (e.g. by an ADT), and fleshing out a real `confirm_const_drop_candidate` that
