### ISSUE TITLE
Tracking Issue for windows_process_extensions_raw_arg

### ISSUE THREAD

**Issue by Xaeroxe** [rust-lang/rust#92939]
Feature gate: `#![feature(windows_process_extensions_raw_arg)]`

This is a tracking issue for the raw_arg extension to `std::process::Command` on Windows.

Windows programs on the lowest API layers actually aren't required to accept arguments as an array of strings.
In fact the illusion that they do accept arguments as an array of strings is mostly maintained by one function. [CommandLineToArgvW](https://docs.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-commandlinetoargvw). Not all programs use that function to parse arguments. Some of the programs that don't do this are really important, like `cmd.exe`. These programs instead read their argument as one large string, which makes them incompatible with how `std::process::Command::arg` passes the arguments. `std::process::Command::arg` assumes the program will parse the string using `CommandLineToArgvW`. Most of the time this is a reasonable assumption to make.

Solution: `raw_arg`. Strings passed via `raw_arg` are sent straight through with no alteration, save for inserting spaces inbetween them. Raw args are not quoted, escaped, or really anything complicated like that. This makes them compatible with Windows executable files which don't use [CommandLineToArgvW](https://docs.microsoft.com/en-us/windows/win32/api/shellapi/nf-shellapi-commandlinetoargvw).

### Public API

```rust
use std::process::Command;

// This will print
// "Hello World!"
// with the quotes, which is not possible with std::process::Command and `cmd.exe`
// with the current `.arg()` method.
let cmd = Command::new("cmd.exe").raw_arg("/C echo \"Hello World!\"");

// You can also chain this
Command::new("cmd.exe")
        .raw_arg("/C")
        .raw_arg("echo")
        .raw_arg("\"Hello World!\"")
```

### Steps / History

- [x] Implementation: #85832
- [x] Final comment period (FCP)
- [x] Stabilization PR #92942

### Unresolved Questions

- None yet.

**Comment by Xaeroxe** [comment]
I need a Rust team member to kick off an FCP for this.

**Comment by m-ou-se** [comment]
@rfcbot merge

**Comment by nico** [comment]
If I have a string containing a full command (e.g. `myprogram.exe myArg1 myArg2`), how would I use this new API to create a process running that command?

I want to have something that behaves as if I passed that string to `CreateProcessA()`.

Running `Command::new("cmd.exe").raw_arg("/C").raw_arg(mystring)` isn't an option, since as soon as you bring cmd.exe into play, your subject to its commandline limit of 8192 characters.

Having to split off the first part of `mystring` is also not great, since I have to do cmd unquoting, which is tricky to do on Windows.

**Comment by Xaeroxe** [comment]
@nico this API can’t help you accomplish that. In order to accomplish that you need a null value passed for lpApplicationName, which isn’t supported by std::process::Command. You’re probably best served by calling CreateProcessA directly at that point.

**Comment by JohnTitor** [comment]
Triage: I'm going to close this as the stabilization PR was merged already 🎉
