### ISSUE TITLE
Document that `Display` entails `ToString`

### ISSUE THREAD

**Issue by steffahn** [rust-lang/rust#92941]
I just [answered a question](https://users.rust-lang.org/t/when-should-i-implement-display-for-my-library-structs/70400) on URLO about when to implement or not to implement `Display`, and I noticed that the [docs on the `Display`](https://doc.rust-lang.org/1.58.0/std/fmt/trait.Display.html) trait are lacking.

In particular, I believe they should definitely point out that implementing `Display` will give a type a `.to_string()` method via the `ToString` trait. This is important to keep in mind when you’re designing an API; it’s also the reason why in the standard library `Path` doesn’t implement `Display` directly (but offers a `.display()` method): because converting `Path` to `String` is lossy or fallible, and an (implicitly) lossy `to_string` method would not fit the API.

@rustbot label A-docs, C-enhancement, T-libs-api

**Comment by 89z** [comment]
Yes agree. I first learned this today from here:

https://doc.rust-lang.org/std/string/trait.ToString.html

to which I was upset to find its not here anywhere:

https://doc.rust-lang.org/std/fmt/trait.Display.html

so its basically a tribal knowledge. You would only know about it if someone told you about it, or if you happen to just randomly look at the `ToString` trait.
