### ISSUE TITLE
"error[E0463]: can't find crate for `core`" trying to cross-compile rustc

### ISSUE THREAD

**Issue by lemonsqueeze** [rust-lang/rust#92944]
Hi,

I'm trying to cross-compile rustc for linux x32 (goal is to have a native x32 rustc).
I've managed to get it to build (`x.py build` is successful) but when running `x.py install` I run into :
```
error[E0463]: can't find crate for `core`
error: could not compile `scopeguard` due to previous error
```

Not sure what is going on, cross-compilation issue ?
Can someone help out ?

**Setup:**

Ubuntu focal amd64 (no rust distro package)
Rust installed through rustup:
```
$ rustc --version
rustc 1.58.0 (02072b482 2022-01-11)
$ where rustc
rustc is /home/bilbo/.cargo/bin/rustc
```
Rust source is latest git (b13a5bf3c4d)
Here's my [config.toml](https://github.com/rust-lang/rust/files/7875836/config.toml.txt)
  So setting build, host, target, and pointing it to the respective compilers :
```
build = "x86_64-unknown-linux-gnu"
host = ["x86_64-unknown-linux-gnux32"]
target = ["x86_64-unknown-linux-gnux32"]
```
Then :
```
$ python x.py build         # ok
$ find . -name rustc
./bootstrap/debug/rustc
./x86_64-unknown-linux-gnu/stage1/bin/rustc
./x86_64-unknown-linux-gnu/stage2/bin/rustc
./x86_64-unknown-linux-gnux32/stage1/bin/rustc
```

```
$ python x.py install
...
  Compiling cfg-if v0.1.10
     Running `/home/bilbo/all/rust/build/bootstrap/debug/rustc --crate-name cfg_if --edition=2018 /home/bilbo/.cargo/registry/src/github.com-1ecc6299db9ec823/cfg-if-0.1.10/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no -C debuginfo=0 -C metadata=4667d1eb08bb1517 -C extra-filename=-4667d1eb08bb1517 --out-dir /home/bilbo/all/rust/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/deps --target x86_64-unknown-linux-gnu -L dependency=/home/bilbo/all/rust/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/x86_64-unknown-linux-gnu/release/deps -L dependency=/home/bilbo/all/rust/build/x86_64-unknown-linux-gnu/stage0-bootstrap-tools/release/deps --cap-lints allow --cfg=bootstrap -Zsymbol-mangling-version=v0 -Zmacro-backtrace -Clink-args=-Wl,-z,origin '-Clink-args=-Wl,-rpath,$ORIGIN/../lib' -Ztls-model=initial-exec -Z binary-dep-depinfo`

error[E0463]: can't find crate for `core`

For more information about this error, try `rustc --explain E0463`.
error: could not compile `cfg-if` due to previous error
```

**Comment by lemonsqueeze** [comment]
Ran into same missing zlib -lz linker issue as #92867 while building btw.
Got around it by forcing compiler to always -lz for now ...

**Comment by teknoman117** [comment]
I got a notification that you mentioned my issue. Considering that initially I was trying to build from a 64-bit Gentoo installation, I wonder if this is a problem with trying to build a 32-bit toolchain in a 64-bit environment. I didn't try a 64-bit ubuntu container, only a 32-bit one, and only the most recent LTS (20.04) at that. I'm going to try the other combinations.

**Comment by Dylan-DPC** [comment]
Closing this to clear up the issue tracker. If you or anyone reading this still needs help you can consult the forums, discords, etc for help. Thanks
