### ISSUE TITLE
[ICE] with last Nightly

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust#92966]
On my codebase I've seen an ICE (compiler crash) with the last Nightly:

```
rustc 1.60.0-nightly (ec4bcaac4 2022-01-15)
binary: rustc
commit-hash: ec4bcaac450279b029f3480b8b8f1b82ab36a5eb
commit-date: 2022-01-15
host: x86_64-pc-windows-gnu
release: 1.60.0-nightly
LLVM version: 13.0.0
```

I've reduced the code that crashes the compiler to:

```rust
fn main() {
    let mut spam = [0_u32; 12];
    let mut len = 0;
    for el in "10,20".split(',') {
        spam[len] = el.parse().unwrap();
        len += 1;
    }
    let spam2 = &spam[.. len];
    let bar = [false; 5];
    for i in 0 .. 10 {
        let mut tot = 0;
        for j in 0 .. spam2.len() {
            if ((i >> j) & 1) != 0 {
                tot += spam2[j];
            }
        }
        if bar[tot as usize] {}
    }
}
```

Small changes in that code avoid the crash.

It doesn't crash if I compile with:

```
rustc -O test.rs
```

It crashes with:

```
rustc -O -C target-cpu=native test.rs
```

It also crashes with:

```
rustc -O -C target-cpu=haswell test.rs
```

**Comment by ehuss** [comment]
Thanks for the report!  Unfortunately I'm unable to reproduce with the given sample.

When reporting an ICE, it is helpful to use the [ICE issue template](https://github.com/rust-lang/rust/issues/new?assignees=&labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md) and fill out the requested fields. In particular, can you include the full output when running with `RUST_BACKTRACE=1 `?

**Comment by leonardo-m** [comment]
> can you include the full output when running with RUST_BACKTRACE=1 ?

Do you mean running the compiler? (Because no binary is generated, the compiler ICEs).

**Comment by ehuss** [comment]
Yes, set `RUST_BACKTRACE=1` when running rustc to get the full backtrace.

I tried on Windows 10.

**Comment by leonardo-m** [comment]
Unfortunately I get zero backtrace... I'll ask online, later.

**Comment by leonardo-m** [comment]
As it happens, the new Nightly doesn't ICE.
