### ISSUE TITLE
rustdoc: some nested lists are rendered incorrectly

### ISSUE THREAD

**Issue by lo48576** [rust-lang/rust#92971]
# Summary

Nested markdown lists as below are not rendered as nested lists, but as single-level lists.

Works as expected:

* stable (`cargo 1.58.0 (7f08ace4f 2021-11-24)`, `rustdoc 1.58.0 (02072b482 2022-01-11)`)
* beta (`cargo 1.58.0-beta (7f08ace4f 2021-11-24)`, `rustdoc 1.58.0-beta.3 (4aa9d237c 2022-01-08)`)

Produces unintended output:
* nightly (`cargo 1.60.0-nightly (358e79fe5 2022-01-04)`, `rustdoc 1.60.0-nightly (1bd4fdc94 2022-01-12)`)

Initially reported at <https://github.com/rust-lang/docs.rs/issues/1594>.

## Source input

```rust
//! * foo
//!     + bar
//!     + baz
```

## Expected output

* foo
    + bar
    + baz

With `cargo doc` (with stable toolchain):
![screenshot-2022-01-17-011919+0900](https://user-images.githubusercontent.com/1246590/149668298-50999afa-7016-4250-b68e-606268f083d7.png)

## Actual output

* foo + bar + baz

With `cargo +nightly doc` with nightly toolchain:
![screenshot-2022-01-17-011924+0900](https://user-images.githubusercontent.com/1246590/149668333-256f9193-35c9-4032-8b3e-fdaa4cf52dac.png)

**Comment by GuillaumeGomez** [comment]
I need to confirm if it comes from rustdoc or pulldown-cmark. I'll try to fix it in the next days.

**Comment by ehuss** [comment]
This is a regression in pulldown-cmark, I have opened https://github.com/raphlinus/pulldown-cmark/issues/567

**Comment by Nemo157** [comment]
This also affects `rustdoc 1.59.0-beta.1 (7c0b25092 2022-01-13)`

**Comment by GuillaumeGomez** [comment]
Thanks @ehuss !

**Comment by camelid** [comment]
A patch release of pulldown-cmark is about to be released. Could someone open a PR to update to it?

**Comment by camelid** [comment]
Ok, release is out.

**Comment by GuillaumeGomez** [comment]
Just opened https://github.com/rust-lang/rust/pull/93012 for it.

**Comment by camelid** [comment]
Marking as P-high: regression that breaks relatively simple Markdown syntax
