### ISSUE TITLE
Rustdoc: consistentize sidebar HTML generation

### ISSUE THREAD

**Issue by jsha** [rust-lang/rust#92986]
In the Rustdoc sidebar ([e.g.](https://rustdoc.crud.net/jsha/cool-sidebar/std/fs/struct.File.html)), some sections (like Methods) are organized like:

```
<div class="block items">
  <h3>Some Title</h3>
  <div class="sidebar-links">
    <a>foo</a>
    <a>bar</a>
  </div>
</div>
```

Others, under "In `<module>`", like Structs or Functions, are organized like:

```
<div class="block fn">
  <h3>Some Title</h3>
  <ul>
    <li><a>foo</a></li>
    <li><a>bar</a></li>
  </ul>
</div>
```

The latter is semantically preferable. We should consolidate on using `<ul>` / `<li>` in both types of sidebar sections, to make maintaining our CSS easier and more consistent.

**Comment by GuillaumeGomez** [comment]
It seems it has been done already (can't find the PR though...). Closing.

**Comment by jsha** [comment]
Hasn't been done yet. See for instance this example in https://doc.rust-lang.org/nightly/std/fs/struct.File.html:

![image](https://user-images.githubusercontent.com/220205/152968289-c04589fe-0b00-4734-86da-e42bc0293ae7.png)

It's all plain links; we'd prefer them to be a list.

**Comment by GuillaumeGomez** [comment]
Oh I see, missed that. Reopening and I'll do it too.
