### ISSUE TITLE
Tracking Issue for const offset_from (const_ptr_offset_from)

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#92980]
The feature gate for the issue is `#![feature(const_ptr_offset_from)]`.

This tracks `const`ness of the following function(s):
```rust
impl<T> *const T {
  const unsafe fn offset_from(self, origin: *const T) -> isize
}
```

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps

- [x] Implementation
- Stabilization report: https://github.com/rust-lang/rust/issues/92980#issuecomment-1065644848
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Unresolved Questions

- Should we allow calling this function in case both pointers point to the same allocation (in terms of their provenance) but are not both in-bounds? Cc https://github.com/rust-lang/rust/issues/92512 <br>    → this can be resolved post-stabilization since it is backwards compatible

### Implementation history

- see https://github.com/rust-lang/rust/issues/41079
- https://github.com/rust-lang/rust/pull/94827

**Comment by RalfJung** [comment]
Cc @rust-lang/wg-const-eval

**Comment by kupiakos** [comment]
I'd like to see if we can work out the kinks and stabilize this sooner rather than later. Since `addr_of!` is stable, this being stabilized would enable us to do something quite powerful: stable const-time `offset_of`. See https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=e8073c3551048421b730a8246fb58f3d for an example. With that, we can get stable const-time calculation of padding byte locations, something that could be very helpful for the [zerocopy](https://docs.rs/zerocopy/latest/zerocopy/index.html) library and related firmware code.

**Comment by RalfJung** [comment]
> See [here](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=e8073c3551048421b730a8246fb58f3d) for an example.

Note that that macro has some subtle flaws, see https://github.com/Gilnaa/memoffset for a bullet-proof (and also nightly-const-compatible) version. In particular it protects against `.field` triggering deref coercions, which make your version of the macro unsound.

**Comment by RalfJung** [comment]
But regarding this tracking issue, I think it would be good to fix https://github.com/rust-lang/miri/issues/1950 before stabilizing, to ensure we actually check the UB for this function properly. (Miri and CTFE share that implementation.) Other than that, I am not aware of any blockers. I *think* we should do the change suggested in https://github.com/rust-lang/rust/issues/92512, but that can happen post-stabilization.

**Comment by kupiakos** [comment]
Good call on the `Deref` soundness, rest assured I'm not copying playground code into production 😃 

I'll see if I can spend some time looking at the change or issue.

For now, I think may have found an alternative way to calculate `offset_of!` in stable CTFE that doesn't depend on pointer arithmetic, it's just [more expensive at compile time](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=a64bda9f22e080223bcdc1d5e53b5376).

**Comment by RalfJung** [comment]
## Stabilization report

I would like to propose this feature for stabilization: it allows const-code to call
```rust
impl<T: ?Sized> *const T {
  const unsafe fn offset_from(self, origin: *const T) -> isize
}
```
`offset_from` has been stabilized for runtime code more than 1.5 years ago (see https://github.com/rust-lang/rust/issues/41079). Its CTFE implementation is shared with Miri and has been working fine for a long time; https://github.com/rust-lang/rust/pull/94827 works out the last kink (but even that is optional since we do not guarantee to detect all UB). This is the last feature that is missing to be able to implement `offset_of!` in a const-compatible way, which has been a long time coming. :)

This cycle we are also on track to const-stabilize a whole lot of other pointer offset functions (https://github.com/rust-lang/rust/issues/71499), so this fits quite well.

The tests for this feature are at
- https://github.com/rust-lang/rust/blob/335ffbfa547df94ac236f5c56130cecf99c8d82b/src/test/ui/consts/offset_from_ub.rs
- https://github.com/rust-lang/rust/blob/335ffbfa547df94ac236f5c56130cecf99c8d82b/src/test/ui/consts/offset_from.rs

In the future I would like to relax the UB restrictions of this function (https://github.com/rust-lang/rust/issues/92512), but that should be backwards compatible so it does not have to block stabilization.

@rust-lang/lang can I ask for the FCP process to be initiated?

**Comment by RalfJung** [comment]
Or is this @rust-lang/libs-api ? It is const-exposing an intrinsic, so.. possibly both.

**Comment by scottmcm** [comment]
Both teams sounds reasonable, yeah.

Teams, do we want to allow offset-between-pointers calculations in `const`?

Stabilization report from Ralf: https://github.com/rust-lang/rust/issues/92980#issuecomment-1065644848

@rfcbot fcp merge

One correction to the report: it's `T: Sized` only, due to a where clause:

https://github.com/rust-lang/rust/blob/335ffbfa547df94ac236f5c56130cecf99c8d82b/library/core/src/ptr/const_ptr.rs#L441-L452

**Comment by RalfJung** [comment]
@BurntSushi @nikomatsakis @pnkfelix @yaahc friendly reminder that there are some boxes waiting for you to check them here. :)

**Comment by nikomatsakis** [comment]
@rfcbot reviewed

**Comment by yaahc** [comment]
_turns on ~~bat~~ stabilization signal_

**Comment by fee1-dead** [comment]
I'll prepare a stabilization PR

@rustbot claim
