### ISSUE TITLE
Can't modify value after temporarily dropping reference in loop when using Drop

### ISSUE THREAD

**Issue by AzureMarker** [rust-lang/rust#92984]
I tried this code:

```rust
struct Console<'gfx>(&'gfx usize);

impl<'gfx> Drop for Console<'gfx> {
    fn drop(&mut self) {}
}

fn main() {
    let mut gfx = 0;
    let mut console = Console(&gfx);

    for _ in 0..5 {
        println!("{gfx}");
        
        if gfx == 0 {
            drop(console);
            
            gfx += 1;
            
            console = Console(&gfx);
        }
    }
}
```

I expected to see this happen: Compile

Instead, this happened: Fails with error:
```
error[E0506]: cannot assign to `gfx` because it is borrowed
  --> src/main.rs:17:13
   |
9  |     let mut console = Console(&gfx);
   |                               ---- borrow of `gfx` occurs here
...
17 |             gfx += 1;
   |             ^^^^^^^^ assignment to borrowed `gfx` occurs here
18 |             
19 |             console = Console(&gfx);
   |             ------- borrow might be used here, when `console` is dropped and runs the `Drop` code for type `Console`

For more information about this error, try `rustc --explain E0506`.
```

It works though if you remove the `Drop` impl for `Console`, or if you remove the loop. I would expect it to work with `Drop` because the drop call happens before `gfx` is modified, and there shouldn't be any drop call immediately after it like the diagnostic suggests.

### Meta

`rustc --version --verbose`:
```
rustc 1.58.0 (02072b482 2022-01-11)
binary: rustc
commit-hash: 02072b482a8b5357f7fb5e5637444ae30e423c40
commit-date: 2022-01-11
host: x86_64-unknown-linux-gnu
release: 1.58.0
LLVM version: 13.0.0
```

Tested in playground and in a local dev rustc (based on commit 1b3a5f29dd9, from 3 weeks ago).

**Comment by AzureMarker** [comment]
I think we need to call [`record_operands_moved`](https://github.com/rust-lang/rust/blob/master/compiler/rustc_mir_build/src/build/scope.rs#L972) when lowering the assignment. Otherwise it inserts a drop for the temporary RHS value. This drop eventually gets culled by a later pass (elaborate drops I think) but since the borrow checker runs before that, it fails the build.

**Comment by AzureMarker** [comment]
I think this would also require a change to the borrow checker. After adding a call to `record_operands_moved` the drop call for the temporary goes away in the MIR, but the error stays. Checking the borrow check dataflow graph, I see the borrow is still there even after dropping the borrower:
![image](https://user-images.githubusercontent.com/4417660/149827142-e342f4c9-1c42-4e99-94ab-10b3bb23c78b.png)

**Comment by AzureMarker** [comment]
This is the relevant MIR and borrowck graph if you remove the loop. This time the borrow gets killed when the moved borrower's storage gets killed (`StorageDead`). Not sure why this doesn't happen in the loop case.
![image](https://user-images.githubusercontent.com/4417660/149827902-45f54895-dcb9-4f4d-8fb9-222d6ec378b2.png)

**Comment by AzureMarker** [comment]
This is the relevant MIR and borrowck graph if you comment out the `Drop` impl for `Console` (but keeping the loop). This is the kind of borrowing that I expect. Maybe the borrow checker doesn't fully understand `TerminatorKind::DropAndReplace`?
![image](https://user-images.githubusercontent.com/4417660/149829393-073a4936-110c-4647-8ae2-256a83ff5aee.png)

**Comment by fmease** [comment]
This now compiles successfully on stable and master. I presume #107421 fixed this, it made MIR drop tracking the default.
