### ISSUE TITLE
Convert extra::ebml to extra::atom_trees

### ISSUE THREAD

**Issue by brson** [rust-lang/rust#9303]
This module doesn't actually implement ebml correctly and only exists to support rustc's metadata. Make a few changes to optimize it:

* Rename it from `ebml` to `atom_trees`, change all internal naming
* Make tags an atom (fourcc tag) of native endianness + 32-bit length with native endianness. This should be faster than the variable-length tags ebml uses.

cc #9255

**Comment by bagedevimo** [comment]
I'd like to get into rust dev, is someone willing to mentor me on in endianness change?

**Comment by druzn3k** [comment]
Hi @bagedevimo, i was working on the issue, but i cannot find the time to continue do to personal issues. It's all yours! :+1:

**Comment by steveklabnik** [comment]
removing a-libs because we don't expose this publicly

**Comment by gevious** [comment]
I'm happy to pick this one up, but I'm not exactly sure what the requirement is now that ebml doesn't exist anymore!? This will be my first rust issue, so I'll likely have some questions

**Comment by arielb1** [comment]
Using fixed-length instead of variable-length tags would lead to significant bloat. I don't think endianness costs that much.

**Comment by steveklabnik** [comment]
closing based on https://github.com/rust-lang/rust/issues/21482#issuecomment-153790489
