### ISSUE TITLE
Possible missing `# Safety` documentation for `alloc::string::Drain`

### ISSUE THREAD

**Issue by pierwill** [rust-lang/rust#93043]
Should this code have a section explaining the reason for unsafety? Perhaps this is discussed somewhere else already?

https://github.com/rust-lang/rust/blob/7bc7be860f99f4a40d45b0f74e2d01b02e072357/library/alloc/src/string.rs#L2763-L2780

**Comment by the8472** [comment]
Afaict tidy doesn't enforce undocumented-unsafe for `alloc` yet.

**Comment by pierwill** [comment]
Ah yes, I seemed to remember a tidy check for this. Is adding this for `alloc` something we want? I could look into this.

**Comment by pierwill** [comment]
Closing for now.
