### ISSUE TITLE
rustdoc: replace `var` with `const` and `let` in JS

### ISSUE THREAD

**Issue by jsha** [rust-lang/rust#93058]
Now that rustdoc is using ES6 idioms, we should replace all `var` declarations with `const` and `let`. This style guideline explains why: https://github.com/airbnb/javascript#references. Once that's done, we should turn on the lint checks that enforce it.

I think there are a few places (at least in search.js) where we rely on the surprising property of var declarations called "[var hoisting](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/var#var_hoisting)". In those cases we may to move some declarations to the top of their function at the same time we change them to `let`.

**Comment by GuillaumeGomez** [comment]
I'll do it once I'm done with https://github.com/rust-lang/rust/pull/90630.

**Comment by the8472** [comment]
Shouldn't the JS also be changed to strict mode to ensure that all variables actually are declared via keywords?

**Comment by GuillaumeGomez** [comment]
@fmease: So a few things remain to be done:

 * Move callback to the `() => {}` syntax.
 * Use "strict" as suggested by @the8472 
 * Add a lot more eslint lints.

Do you want to divide the work with me? :)

**Comment by Folyd** [comment]
> @Folyd: So a few things remain to be done:
> 
> * Move callback to the `() => {}` syntax.
> * Use "strict" as suggested by @the8472
> * Add a lot more eslint lints.
> 
> Do you want to divide the work with me? :)
> 
> EDIT: sorry @fmease for the invalid ping ^^'

Sure, I'd love to. 😸

**Comment by GuillaumeGomez** [comment]
Then pick one thing and go ahead. :)

**Comment by Folyd** [comment]
Ok, I pick this one.
> Move callback to the () => {} syntax.

**Comment by GuillaumeGomez** [comment]
Then I'll do "use strict" next.

**Comment by GuillaumeGomez** [comment]
@Folyd Now remains adding more eslint lints. Let's go one at a time. What do you think? If you're interested, just write down which one you're adding here so that we don't conflict. ;)

**Comment by Folyd** [comment]
> @Folyd Now remains adding more eslint lints. Let's go one at a time. What do you think? If you're interested, just write down which one you're adding here so that we don't conflict. ;)

I just file a new PR to change the way we declare the lint rules. https://github.com/rust-lang/rust/pull/96805
This can eliminate repeatedly rules declaration if we need to add further lint rules.

**Comment by GuillaumeGomez** [comment]
This issue is done so closing it.
