### ISSUE TITLE
rustdoc: fix border-radius and sizing of help and settings icons

### ISSUE THREAD

**Issue by jsha** [rust-lang/rust#93060]
Currently the help and settings icons next to the search box have a bit of a style mismatch with the search box itself:

![image](https://user-images.githubusercontent.com/220205/150049168-2c9ce11f-a557-4a37-a998-6fb20ff1ae12.png)

They have a slightly larger border-radius, and their height is not the same as the search box. We should fix that. We may also want to slightly decrease the height of the search box so the button/icons don't have to get super big to match.

**Comment by GuillaumeGomez** [comment]
I'll check what I can do.
