### ISSUE TITLE
rust_2021_incompatible_closure_captures seems inconsistent

### ISSUE THREAD

**Issue by Alfred-Mountfield** [rust-lang/rust#93076]
Apologies if this is the wrong place to submit this, if it isn't the right place, could you point me as to where this would be appropriate?

I've noticed some weird behavior related to when `rust_2021_incompatible_closure_captures` creates warnings.

I tried to create a minimum viable example:
```rust
#![warn(rust_2021_compatibility)]
use std::sync::Arc;

pub struct Warns {
    _test: Arc<String>, // Removing this Arc results in no warning
    foo: String,
}

impl Warns {
    pub fn test(self) -> std::io::Result<()> {
        let closure = move || {
            let _ = self.foo;
            Ok(())
        };
        closure()
    }
}
```

Running that results in the following warning, however the warning isn't present when `_test` isn't wrapped in an `Arc`:
```rust
warning: changes to closure capture in Rust 2021 will affect drop order
  --> src/lib.rs:11:23
   |
11 |         let closure = move || {
   |                       ^^^^^^^
12 |             let _ = self.foo;
   |                     ---- in Rust 2018, this causes the closure to capture `self`, but in Rust 2021, it has no effect
...
16 |     }
   |     - in Rust 2018, `self` is dropped here along with the closure, but in Rust 2021 `self` is not part of the closure
   |
```

This is also reproducible [on the playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=603861161fe636612a7963d6cc231bf6)

Some other users have tried this and said that warnings appear for `Box`/`Arc`/`Mutex` but not `Rc` or `Vec` for example. 

---

It's also worth noting that a related warning appears about dropping a field on `self` when accessing `self.foo.bar` or similar, but I didn't include in that example to avoid complicating it. ([Here is the equivalent code on the playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=851d2e79882e1475a37c5c2f825ec335))
```rust
warning: changes to closure capture in Rust 2021 will affect drop order
  --> src/lib.rs:15:23
   |
15 |         let closure = move || {
   |                       ^^^^^^^
16 |             let _ = Foo { bar: self.foo.bar };
   |                                ------------ in Rust 2018, this closure captures all of `self`, but in Rust 2021, it will only capture `self.foo.bar`
...
22 |     }
   |     - in Rust 2018, `self` is dropped here, but in Rust 2021, only `self.foo.bar` will be dropped here as part of the closure
```

The preliminary thought is that it has something to do with the `Drop` trait.

**Comment by Dylan-DPC** [comment]
The warning is no longer emitted for either case. Closing this
