### ISSUE TITLE
Incorrect suggestion when trying to write to an immutable field in an async function

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#93093]
Given the following code: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=df6e36b97b73bd3e3ea0fdfe9325b1c9

```rust
struct S { foo: usize }
impl S {
    async fn bar(&self) {
        self.foo += 1;
    }
}
```

The current output is:

```
error[E0594]: cannot assign to `self.foo`, which is behind a `&` reference
 --> src/lib.rs:4:9
  |
3 |     async fn bar(&self) {
  |                  ----- help: consider changing this to be a mutable reference: `&mut S`
4 |         self.foo += 1;
  |         ^^^^^^^^^^^^^ `self` is a `&` reference, so the data it refers to cannot be written
```

Ideally the output should look like:

```
error[E0594]: cannot assign to `self.foo`, which is behind a `&` reference
 --> src/lib.rs:4:9
  |
3 |     async fn bar(&self) {
  |                  ----- help: consider changing this to be a mutable reference: `&mut self`
4 |         self.foo += 1;
  |         ^^^^^^^^^^^^^ `self` is a `&` reference, so the data it refers to cannot be written
```

`&mut S` is not a valid argument; it needs to be either `&mut self` or `some_name: &mut S`. For some reason this problem only happens when the function is async.

**Comment by compiler-errors** [comment]
This is the same diagnostic you get when mutably dereferencing let-bindings that are `&T`: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=b71c99d23b4e58a67afd52a0870bed65
So it seems like this has to do with the fact that ast_lowering emits a `let self = self;` binding when desugaring.

I wonder if we can get the name of the variable when emitting this diagnostic, and special-case when it `== "self"`.

**Comment by jyn514** [comment]
Another (possibly related?) bug: `self.foo += 1` doesn't have the `help` suggestion if it's in an async block: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=23ea8e56639ab035349c69050bd74148
```rust
struct S { foo: usize }

impl S {
    fn bar(&self) {
        async move {
            // let self_ = self;
            self.foo += 1;
        };
    }
}
```

**Comment by compiler-errors** [comment]
@jyn514 Same with closures. I would probably classify that as a separate bug, since the original bug has to do specifically with `async fn` desugaring, and the latter has to do with closure/generator captures.

**Comment by jyn514** [comment]
Another similar error, not related to async this time:
```
error[E0596]: cannot borrow `*callback` as mutable, as it is behind a `&` reference
   --> boring/src/ssl/callbacks.rs:278:5
    |
273 |     let callback = ctx
    |         -------- help: consider changing this to be a mutable reference: `&mut F`
...
278 |     callback(ctx, session)
    |     ^^^^^^^^ `callback` is a `&` reference, so the data it refers to cannot be borrowed as mutable
```
`let &mut F = ...` isn't valid Rust.
