### ISSUE TITLE
Item names in module lists get prematurely wrapped on nightly docs

### ISSUE THREAD

**Issue by Nemo157** [rust-lang/rust#93135]
Beta (`rustdoc 1.59.0-beta.2 (98a701b42 2022-01-19)`) rendering of `rand 0.8.4`'s root traits (on Firefox 96.01 on Windows):

![image](https://user-images.githubusercontent.com/81079/150427028-0b1309d4-1085-459b-b988-b3fce8f4e088.png)

Nightly (`rustdoc 1.60.0-nightly (5e57faa78 2022-01-19)`) rendering of the same:

![image](https://user-images.githubusercontent.com/81079/150427185-395f3e52-f52e-4e22-85a6-7d3a134e164e.png)

It appears that the names are inheriting the `overflow-wrap: anywhere`, which is influencing the table layout and allowing the left-column to become too thin to fit the names. Added in https://github.com/rust-lang/rust/pull/92801 cc @jsha.

**Comment by jsha** [comment]
Thanks for spotting! I'll fix it.
