### ISSUE TITLE
[workspace & asm! macro][Embedded OS Dev]Error: invalid register 'x10' unknown register

### ISSUE THREAD

**Issue by PeterWrighten** [rust-lang/rust#93151]
When I want to refactor an [OS project](https://github.com/rcore-os/rCore-Tutorial-v3/tree/ch2) with Cargo workshop, which its original rust code is not encapsulated under cargo workspace but could promise successful run, compiler reported 'invalid register' issue as follow: 

 (My code is [here](https://github.com/PeterWrighten/OperatingSystem/tree/chap2/peter_batch_os), refactored by Cargo workspace)
 
```shell
% cargo build
   Compiling user_lib v0.1.0 (/Users/apple/GitHub/OperatingSystem/peter_batch_os/user)
error: invalid register `x10`: unknown register
 --> user/src/syscall.rs:9:13
  |
9 |             inlateout("x10") args[0] => ret,
  |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: invalid register `x11`: unknown register
  --> user/src/syscall.rs:10:13
   |
10 |             in("x11") args[1],
   |             ^^^^^^^^^^^^^^^^^

error: invalid register `x12`: unknown register
  --> user/src/syscall.rs:11:13
   |
11 |             in("x12") args[2],
   |             ^^^^^^^^^^^^^^^^^

error: invalid register `x17`: unknown register
  --> user/src/syscall.rs:12:13
   |
12 |             in("x17") id
   |             ^^^^^^^^^^^^

error: could not compile `user_lib` due to 4 previous errors
```

My source code [here](https://github.com/PeterWrighten/OperatingSystem/blob/chap2/peter_batch_os/user/src/syscall.rs) has added ```unsafe``` statement and ```asm``` mod, target triple is also modified to "riscv64gc-unknown-none-elf", but it seems that stil could't work under cargo workspace :(

# version
rustc 1.60.0-nightly (2022-01-20)

**Comment by PeterWrighten** [comment]
Now it works well by changing rustflags, but still cound not guarantee its performance when ```.cargo``` config file is not under root directory. I want to know how could I do to work it out just depended by ```.cargo``` file under members' crate.

**Comment by bjorn3** [comment]
This is a cargo issue and not a rustc issue. Closing in favor of https://github.com/rust-lang/cargo/issues/10314.
