### ISSUE TITLE
[ER] gcd / binary_gcd / lcm

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust#93167]
I suggest to add to the Rust stdlib implementations of gcd/binary_gcd/lcm. The ones belows are designed to be division-panic-free.

```rust
type T = u32;


// Postcondition: result == 0 => u == 0 || v == 0.
fn gcd(mut u: T, mut v: T) -> T {
    if v == 0 { return u; }
    loop {
        u %= v;
        if u == 0 { return v; }
        v %= u;
        if v == 0 { return u; }
    }
}


fn binary_gcd(mut u: T, mut v: T) -> T {
    if u == 0 { return v; }
    if v == 0 { return u; }
    let shift = (u | v).trailing_zeros();
    u >>= u.trailing_zeros();
    loop {
        v >>= v.trailing_zeros();
        if u > v {
            (u, v) = (v, u);
        }
        v -= u;
        if v == 0 { break; }
    }
    u << shift
}


fn lcm(a: T, b: T) -> T {
    let mut u = a;
    let mut v = b;
    if v == 0 { return u; }
    loop {
        u %= v;
        if u == 0 {
            return (a / v) * b;
        }
        v %= u;
        if v == 0 {
            return (a / u) * b;
        }
    }
}


//------------------------

fn main() {
	assert_eq!(gcd(10, 20), 10);
	assert_eq!(lcm(10, 20), 20);
	assert_eq!(binary_gcd(10, 20), 10);
}
```

gcd and lcm are short and used widely. Different implementations are possible, but their purpose and API won't change. They are present in the Python stdlib:
https://docs.python.org/3/library/math.html

The binary_gcd is faster in some cases, so I think it's useful to have both a simple gcd and a binary_gcd.

**Comment by the8472** [comment]
Are there crates that implement these? If yes, how popular are they?

**Comment by leonardo-m** [comment]
Some GCD algorithms are popular since thousand/hundred years :) The need to compute such values exists since before Fibonacci.

**Comment by Dylan-DPC** [comment]
Closing this as it is better suited for a crate and later moved to std if the demand and motivation exists
