### ISSUE TITLE
Tracking Issue for `core::pin::pin!`

### ISSUE THREAD

**Issue by danielhenrymantilla** [rust-lang/rust#93178]
Feature gate: `#![feature(pin_macro)]`

This is a tracking issue for `core::pin::pin!`, which allows pinning values to the stack / local scope.

### Public API

```rust
// core::pin

/// API: `fn pin<T>($value: T) -> Pin<&'local mut T>`
pub macro pin($value:expr $(,)?) {
    …
}
```

### Steps / History

 - [x] Implementation: #93176
 - [x] Final comment period (FCP)
 - [x] Stabilization PR: #103800

### (un)Resolved Questions

  - [x] Should it be named `pin_mut!` instead, and have a `pin_ref!` counterpart? (cc @cramertj's https://github.com/rust-lang/rust/pull/93176#issuecomment-1018919707)

    I claim this has been deemed resolved [by this conclusion](https://github.com/rust-lang/rust/issues/93178#issuecomment-1295842774)

**Comment by jsenkpiel-godaddy** [comment]
I feel like this should be called `pin_mut!` and have a `pin_ref!` counterpart, because you can't feed it `T` but only `&mut T`/`&T`.

**Comment by RalfJung** [comment]
Not sure what you mean, you can give it a `T` just fine. You will *get* a `Pin<&mut T>`, but that can be easily converted into `Pin<&T>` if needed via `as_ref`.

**Comment by danielhenrymantilla** [comment]
Ok, after all this time, there have been no issues with `nightly` users of this feature, and the macro seems as good as it is possible to have at the moment (we'd need trustworthy `opaque macro`s for that).

### The main unresolved question being about the naming of the macro: _should it remain as `pin!`, or should it become `pin_mut!` to pave the way for a `pin_ref!` counterpart?_

While `pin_mut!` would be a safe / conservative choice, I think it would be _overkill_ here.
To illustrate why, let's start by drawing some parallels with `Box` or other ownership-based APIs.

This is a legitimate think to do, since `pin!`ning is the stack/local counterpart of `Box::pin`ning, _i.e._, its key aspect is _ownership_-based, not _borrowing_-based: **contrary to the usual _getter_ design of `.as_{ref,mut}`, `.deref{,_mut}`, `ptr::addr_of{_mut}!`, `pin!` _consumes ownership of its input_**!

And in the same fashion that we have `Box::leak()` _consuming ownership of the input, and returning a borrow in output_, a borrow which _happens to be an exclusive one_, `pin!`'s design is quite similar.

And we don't have have `Box::leak_mut()` + `Box::leak_ref()`, we just just have `Box::leak()`. Users wanting a _shared_ reference after leaking just have to `&*`:

```rs
let p: &mut _ = Box::leak(thing); // `thing` **moved out**
let r: &_ = &*p;
```

```rs
let p: Pin<&mut _> = pin!(thing); // `thing` **moved out**
let r: Pin<&_> = p.as_ref();
```

  - (there is one difference, though: `pin!` uses subtle lifetime extension, which doesn't allow for methods to be _directly_ called on the `pin!`ned thing as it is being assigned to a local. This makes the _two lines_ in the example be _required_ for proper usage, which isn't the case for `Box`).

On the contrary, if we went with `pin_mut!`, we'd then have a symmetric `pin_ref!` / `pin_mut!` situation, which I actually find not that useful:

  - As [this comment from the maintainer of a very popular future-based crate says](https://github.com/rust-lang/rust/pull/93176#issuecomment-1019124832), the need for `Pin<&_>`s doesn't really occur in practice. While some very specific APIs could end up relying on it, the truth is that it will at most result in an undermining minority, compared to the usage of `Pin<&mut>`.

    As an illustrating example, the very pervasive `#[pin_project]` macro (of the eponymous crate) imbues the annotated type with [a `.project()` method, which is `&mut`-based](https://github.com/taiki-e/pin-project/blob/baf43d47e9a1ed390c409bd2b48755e877179a50/examples/struct-default-expanded.rs).

      - There is no `_mut` suffix;
      - there is, however, a `project_ref()` counterpart.

    On grep.app, [`.project()` yields 1539 occurrences](https://grep.app/search?q=.project%28%29&filter[lang][0]=Rust)[^project], whereas [`.project_ref()` yields 15](https://grep.app/search?current=2&q=.project_ref%28%29&filter[lang][0]=Rust) (with around 5 for `pin_project`'s "let's keep it general" API itself).
    That's a difference of _two orders of magnitude_.

That is, there is little motivation in having a symmetric _convenience_ API for a situation which is hugely asymmetric.

Worse, keeping the symmetry will actually end up being _confusing_, much like having `Box::leak_mut()` _vs._ `Box::leak_ref()` could have been: since the ref variant could be implemented in terms of the `mut` one, users could legitimately wonder if there was some other difference they might have missed: it would be a case of _accidental complexity_, as I view it.

[^project]: Granted, `.project()` is a potentially more frequent name for _other_ APIs, but from randomly skimming the grep.app page results, I was seeing elements indicative of work on `Future`s or `Pin`ning.

**Comment by danielhenrymantilla** [comment]
That's why I'd vote for:

  - sticking to `pin!` (no `pin_mut!`), and should people agree with this, it means it's time for:
  - starting an FCP for its stabilization.

**Comment by tmandry** [comment]
This all sounds good to me. I'm excited to see this move forward, thank you for pushing on it!

> should I make a tentative stabilization PR to trigger it, or should I wait for the FCP to before make the PR?

Either way is fine but personally I'd make a PR, less chance of getting lost :)

**Comment by tmandry** [comment]
> * (there is one difference, though: `pin!` uses subtle lifetime extension, which doesn't allow for methods to be _directly_ called on the `pin!`ned thing as it is being assigned to a local. This makes the _two lines_ in the example be _required_ for proper usage, which isn't the case for `Box`).

It's worth stating that this is a deficiency of Rust's lifetime extension rules (a deficiency that the definition of `pin!` itself works around by being in std), and would be fixed when RFC 66 is implemented (#15023).

**Comment by jkarneges** [comment]
For anyone wanting to start using this style of pinning without having to bump their MSRV, below is a workaround. The extra `Option`, `Deref`, and `Future` impls helped make it work as drop-in substitution in our application (no need for extra `.as_mut()` calls). Feedback welcome.

```rust
use std::future::Future;
use std::ops::Deref;
use std::pin::Pin;
use std::task::{Context, Poll};

pub struct Pinner<'a, T> {
    pub unsafe_pointer: &'a mut T,
}

impl<'a, T> Pinner<'a, T> {
    pub fn as_mut(&mut self) -> Pin<&mut T> {
        // SAFETY: as long as Pinner is only ever constructed via the pin!()
        // macro and the unsafe_pointer field is never directly accessed,
        // then the value is safe to pin here. this is because the macro
        // ensures the input is turned into a borrowed anonymous temporary,
        // preventing any further access to the original value after Pinner
        // is constructed, and Pinner has no methods that enable moving out
        // of the reference. the word "unsafe" is used in the field name to
        // discourage direct access. this is the best we can do, since the
        // field must be public for the macro to work.
        unsafe { Pin::new_unchecked(self.unsafe_pointer) }
    }

    pub fn set(&mut self, value: T) {
        self.as_mut().set(value)
    }
}

impl<'a, T> Pinner<'a, Option<T>> {
    pub fn as_pin_mut(&mut self) -> Option<Pin<&mut T>> {
        self.as_mut().as_pin_mut()
    }
}

impl<'a, T> Deref for Pinner<'a, T> {
    type Target = T;

    fn deref(&self) -> &Self::Target {
        self.unsafe_pointer
    }
}

impl<'a, T> Future for Pinner<'a, T>
where
    T: Future,
{
    type Output = T::Output;

    fn poll(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Self::Output> {
        T::poll(Pin::into_inner(self).as_mut(), cx)
    }
}

#[macro_export]
macro_rules! pin {
    ($x:expr) => {
        crate::Pinner {
            unsafe_pointer: &mut { $x },
        }
    };
}
```

**Comment by ojeda** [comment]
Should this one be closed?

**Comment by carrycooldude** [comment]
Error is coming on this one please check:

error[E0658]: use of unstable library feature 'pin_macro'
   --> /home/kartikey/.cargo/registry/src/github.com-1ecc6299db9ec823/wiremock-0.5.19/src/mock_server/bare_server.rs:247:32
    |
247 |         let mut notification = pin!(notify.notified());
    |                                ^^^
    |
    = note: see issue #93178 <https://github.com/rust-lang/rust/issues/93178> for more information

    Checking fake v2.8.0
error[E0658]: use of unstable library feature 'pin_macro'
 --> /home/kartikey/.cargo/registry/src/github.com-1ecc6299db9ec823/wiremock-0.5.19/src/mock_server/bare_server.rs:6:5
  |
6 | use std::pin::pin;
  |     ^^^^^^^^^^^^^
  |
  = note: see issue #93178 <https://github.com/rust-lang/rust/issues/93178> for more information

**Comment by danielhenrymantilla** [comment]
@carrycooldude this means the version of rust (toolchain) you are using is too old for that `wiremock` (transitive?) dependency you have. Please use ≥1.68.0
