### ISSUE TITLE
Misleading `cannot infer type for type parameter`

### ISSUE THREAD

**Issue by Patryk27** [rust-lang/rust#93198]
Given the following code: 

```rust
use std::collections::HashMap;

trait Store<K, V> {
    fn get_raw(&self, key: &K) -> Option<()>;
}

struct InMemoryStore;

impl<K> Store<String, HashMap<K, String>> for InMemoryStore {
    fn get_raw(&self, key: &String) -> Option<()> {
        None
    }
}

fn main() {
    InMemoryStore.get_raw(&String::default());
}
```

([playground link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=4c1b9ccf80b5ae9efc24b081a1242c5f))

... the current output is:

```
error[E0282]: type annotations needed
  --> src/main.rs:16:19
   |
16 |     InMemoryStore.get_raw(&String::default());
   |                   ^^^^^^^ cannot infer type for type parameter `K`
```

This error message is a bit misleading in that it refers _not_ to `K` from `trait Store<K, V>`, but `K` from the `impl<K> Store<...>` (the compiler is not sure which kind of `HashMap<K, String>` user wants).

Maybe we could print something like this?

```
error[E0282]: type annotations needed
  --> src/main.rs:16:19
   |
16 |     InMemoryStore.get_raw(&String::default());
   |                   ^^^^^^^ cannot infer type for type parameter `K`...
   |
  ::: src/main.rs:9
   |
 9 | impl<K> Store<String, HashMap<K, String>> for InMemoryStore {
          ^ ... from this impl
```

**Comment by returntoreality** [comment]
I have also an issue similar to this problem. In my case the function has two arguments with the same type signature, and so the error does not indicate which argument is actually causing the error. I think the error should:
- tell the argument name and type (instead of just the type)
- underline the actual argument and not the function name.
