### ISSUE TITLE
Tracking Issue for `const_nonnull_new`

### ISSUE THREAD

**Issue by lilasta** [rust-lang/rust#93235]
Feature gate: `#![feature(const_nonnull_new)]`

This is a tracking issue for implementing `NonNull::new`.

### Public API

```rust
// core::ptr
impl<T: ?Sized> NonNull<T> {
    pub const fn new(ptr: *mut T) -> Option<Self>;
}
```

### Steps / History

- [x] Implementation: #93236 
- [x] Final comment period (FCP)
- [ ] Stabilization PR

### Unresolved Questions
- [x] Quasi-blocked on https://github.com/rust-lang/rust/issues/74939

**Comment by workingjubilee** [comment]
Quasi-blocked on https://github.com/rust-lang/rust/issues/93235

**Comment by RalfJung** [comment]
> Quasi-blocked on [#93235](https://github.com/rust-lang/rust/issues/93235)

I assume you mean https://github.com/rust-lang/rust/issues/74939.

That one just finished FCP, so we can now move ahead with `NonNull::new`. :)
@rust-lang/libs-api this should be, finally, ready to be stabilized.

**Comment by dtolnay** [comment]
@rfcbot fcp merge
