### ISSUE TITLE
Rustdoc new crate filter location visually unpolished

### ISSUE THREAD

**Issue by steffahn** [rust-lang/rust#93240]
I took a few notes while looking at nightly rustc docs:

![Screenshot_20220123_165956](https://user-images.githubusercontent.com/3986214/150689173-01c4bf56-b4a1-4ffd-9e4e-7812e30c9ae6.png)

@rustbot label T-rustdoc, C-bug, C-enhancement, A-rustdoc-ui

The sans serif vs. serif is clearly a bug. That’s looking terrible.

The location being in a place that moves horizontally is suboptimal; changing that would be an enhancement. The font size is ridiculously high (because it’s part of a “title”, I guess?). I like the thing no longer being inside of the search bar like it used to be, so I’m not suggesting any reverts, just more polishing work. Maybe this option could be placed e.g. still roughly next to the “Results for …” heading, but right-justified so it doesn’t move around when I change my search term, and also in a normal / more reasonable size. E.g. saying something like “search in \[all crates\]”.

By the way, something not indicated in the picture that I just noticed: if it says “… in \[All crates\]”, I don’t think the “All” should be capitalized anymore.

The question of whether or not it’s necessary for rustdoc to parrot my search term at all is one I don’t care all that much about. If there’s any benefit to keeping it, sure, keep it; I don’t really care.

<hr>

(Minor note, looking back at my image, the arrows are a bit short. The text about font size is in-fact referring to the font size of the dropdown list, nothing else.)

**Comment by the8472** [comment]
Should this be a dropdown at all? It seems like something that could be a search operator, at least if we had some sort of auto-suggest. E.g. type `in:rustc_` in the search bar and it'll offer available creates.

**Comment by camelid** [comment]
cc @jsha @GuillaumeGomez

**Comment by camelid** [comment]
> Should this be a dropdown at all? It seems like something that could be a search operator, at least if we had some sort of auto-suggest. E.g. type `in:rustc_` in the search bar and it'll offer available creates.

Yeah, I suggested this a couple weeks ago. I think the idea is to do it once we also have an "advanced search builder".

**Comment by GuillaumeGomez** [comment]
Yes, we still need to discuss things. Will do that once everyone is available. ;)

**Comment by GuillaumeGomez** [comment]
I think this issue was fixed by https://github.com/rust-lang/rust/pull/100374. Don't hesitate to reopen it if I'm mistaken.
