### ISSUE TITLE
Option::unwrap() on None value

### ISSUE THREAD

**Issue by MinMagar** [rust-lang/rust#93266]
### Code

```Rust
<code>
```

### Meta

`rustc --version --verbose`:
```
<version>
```

### Error output

```
<output>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by Xuanwo** [comment]
Hi, this issue seems rather incomplete, can you please add more detailed information?

**Comment by csmoe** [comment]
Could you rebuild with latest rustc? Closed due to lack of more details.
Feel free to reopen with reproducible code :)
