### ISSUE TITLE
std::process::abort from FFI does not abort.

### ISSUE THREAD

**Issue by T4r4sB** [rust-lang/rust#93276]
I know that panic unwinding from FFI is UB. But abort must terminate the program immediately, where can be problem here?

Let we have this code: https://github.com/janiorca/tinywin/blob/master/miniwin/src/main.rs
Try to add abort into WM_PAINT handler:
```
...
    match msg {
        winapi::um::winuser::WM_PAINT => {
            println!("abort");
            std::process::abort();
            ...
```
Try to run it (I use target i686_windows_gnu), and watch to console:
```
...
abort
abort
abort
abort
abort
abort
abort
abort
abort
abort
abort
abort
abort
...
```
Looks like abort called from WndProc doest not work.
In more complicated cases I cant write Winapi applications with "panic=abort" mode, because abort dont do what I want, and I need to write catch_unwind in std::panic, and generate unwinding boilerplate even in release mode and write std::process::exit(3) (which works correctly).

What's the problem with `std::process::abort`, and why in doesn't work from WndProc, but `std::process:exit` works good?

**Comment by nagisa** [comment]
On windows `abort` is implemented as an equivalent of https://docs.microsoft.com/en-us/cpp/intrinsics/fastfail?view=msvc-170. Either your kernel is doing something wrong, or the call to the `abort` is not actually being reached for some reason.

The best way to figure this out would be by stepping through code with a debugger.

**Comment by ehuss** [comment]
It might also help to include a complete example with clear instructions on how you built it.  The link you provided is `no_std` which means one cannot add `std::process::abort()` to it. It also seems to use xargo with various panic settings.

**Comment by T4r4sB** [comment]
> It might also help to include a complete example with clear instructions on how you built it. The link you provided is `no_std` which means one cannot add `std::process::abort()` to it. It also seems to use xargo with various panic settings.

Ok. Test my fork, please: https://github.com/T4r4sB/tinywin
Project miniwin, command `cargo run`, target "i686-windows-gnu"

**Comment by T4r4sB** [comment]
After some discussion I discovered, that the problem is not in Rust library. 
The problem is in genetic code of Microsoft's programmers.
If you run 32-bit program in 64-bit system, you have this:

https://docs.microsoft.com/en-us/previous-versions/windows/desktop/legacy/ms633573(v=vs.85)

> The system calls the exception filters but suppresses any uncaught  exceptions when it leaves the callback scope, without invoking the  associated handlers.

SUPPRESS!!!
