### ISSUE TITLE
Regression in async generator and fmt internals: loss of `Send`

### ISSUE THREAD

**Issue by danielhenrymantilla** [rust-lang/rust#93274]
> If an `.await` occurs inside a formatting macro, the resulting generator is no longer `Send`.

## Context

This has already tripped up some people which seem to get quite confused with this error message, so I'd rather we not regress here:

  - https://users.rust-lang.org/t/future-created-by-async-block-is-not-send/70796/3?u=yandros

### Code

I tried this code:

```rust
async fn foo() {
    println!("{} {:?}", "", async {}.await);
}

const _ASSERT_SEND: fn() = || {
    let _: &dyn Send = &foo();
};
```

I expected to see this happen: Code compiles fine: the type of `foo()` is `Send`.

Instead, this happened: The type of `foo()` is not send, since the backing state-machine generator produced for it now captures part of the `fmt` internals involving a `&` reference to the `extern { type Opaque; }`, which is not `Sync`.

### Version it worked on

It most recently worked on: **beta**

### Version with regression

`rustc --version --verbose`:
```
nightly-2022-01-23 84322efad553c7a79c80
```

@rustbot modify labels: +regression-from-stable-to-nightly -regression-untriaged

**Comment by matthiaskrgr** [comment]
Might be related to https://github.com/rust-lang/rust/pull/91032 / https://github.com/rust-lang/rust/pull/93165 ?

**Comment by danielhenrymantilla** [comment]
@matthiaskrgr I was also suspecting one of those, although I have to admit not having looked into it any further

**Comment by lqd** [comment]
Does it work with https://github.com/rust-lang/rust/pull/93284 btw ? That should completely disable drop range tracking. (I've launched a try build there so that we have artifacts ready for that soon).

There were also recent changes in the formatting macros/machinery last week IIRC. That could be related as well.

This should be easy enough to bisect, and make sure where the regression is coming from.

**Comment by lqd** [comment]
Answering my own questions:
- #93284 doesn't change this, my guess is that it's actually unrelated to #91032
- #91032 initially landed as part of #93138 and that rollup's commit `523be2e05da322daaecf1ecc8f2c0d625f5f46e3` doesn't reproduce the issue
- the `format_args` change I mentioned was #91359 and its commit `0bcacb391b28460f5a50fd627f01f670dfcfc7cc` does reproduce the issue. This PR seems to have caused it indeed.

**Comment by danielhenrymantilla** [comment]
Nice investigation @lqd!

**Comment by apiraino** [comment]
Assigning priority as discussed in the [Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2393274.20Regression.20in.20async.20generator.20and.20fmt.20internals.3A.20los.E2.80.A6) of the Prioritization Working Group.

@rustbot label -I-prioritize +P-high
