### ISSUE TITLE
Add macro scope details to the Macro tutorial.

### ISSUE THREAD

**Issue by nejucomo** [rust-lang/rust#9329]
The [Macro Tutorial](http://static.rust-lang.org/doc/master/tutorial-macros.html) doesn't explain the scope of macro definitions, nor does it describe the ``#[macro_escape]`` mechanism.

**Comment by steveklabnik** [comment]
http://doc.rust-lang.org/book/macros.html#scoping-and-macro-import/export now describes scope, as well as `macro_use`, the fixed up version of `macro-escape`.
