### ISSUE TITLE
Unsound `BufWriter` copy_to specialization with the unstable `read_buf` feature

### ISSUE THREAD

**Issue by paolobarbolini** [rust-lang/rust#93305]
## Code

```rust
#![feature(read_buf)]

use std::io::{self, BufWriter, Read, ReadBuf};

struct BadReader;

impl Read for BadReader {
    fn read(&mut self, _buf: &mut [u8]) -> io::Result<usize> {
        unreachable!()
    }

    fn read_buf(&mut self, read_buf: &mut ReadBuf<'_>) -> io::Result<()> {
        let vec = vec![0; 2048];

        let mut buf = ReadBuf::new(vec.leak());
        buf.append(&[123; 2048]);
        *read_buf = buf;

        Ok(())
    }
}

fn main() {
    let mut buf = Vec::new();

    {
        let mut buf_ = BufWriter::with_capacity(1024, &mut buf);

        let mut input = BadReader.take(4096);
        io::copy(&mut input, &mut buf_).unwrap();
    }

    // read the memory to trigger miri to realize that the memory is uninitialized
    println!("buf[0]: {}", buf[0]);
}
```

Playground link: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=483f0b4f2f881519f459c3cd273a50f4 (run miri on it)

## Unsound implementation

https://github.com/rust-lang/rust/blob/92ed8747f255b2695c33b64982e6959711a72cb9/library/std/src/io/copy.rs#L80-L122

(we're basically tricking it into calling `set_len` with a length higher than what has actually been filled)

## Documentation

Should this be considered a possible footgun when implementing something that calls `read_buf`? Should it be documented?

**Comment by Urgau** [comment]
This was already mention in the PR that added ReadBuf https://github.com/rust-lang/rust/pull/81156#issuecomment-989192555
cc @DrMeepster @joshtriplett

**Comment by DrMeepster** [comment]
There's two possible solutions I see here.  

1. The easiest thing to do to fix this is just check if the `ReadBuf` points to the same buffer as before and return an error if it doesn't. This doesn't seem very "rusty" to me though, relying on a runtime check.
2. The other solution is to have a `ReadBufRef` type passed by value to `read_buf` instead of `&mut ReadBuf`. This solves the issue in general at compile time, but could make this api a lot more complicated to use.

**Comment by nrc** [comment]
I think another example of unsound code in std for a similar readon is in the read_buf implementation for `Take`.

**Comment by paolobarbolini** [comment]
> I think another example of unsound code in std for a similar reason is in the `read_buf` implementation for `Take`.

Yes it seems like a similar attack could be done against it

https://github.com/rust-lang/rust/blob/18f32b73bdb3833c18c73fe3062bde8e1721ccca/library/std/src/io/mod.rs#L2584-L2601
