### ISSUE TITLE
Stop growing Clippy, no more Clippy please. 

### ISSUE THREAD

**Issue by cnmade** [rust-lang/rust#93318]
Did anyone notice that Rust has the world largest lint rules? and still growing very fast. 
It's make Rust feel like trash... so many problem programming with Rust.
Is it normally? Why not just make things easy and simple?

How stupid to ask people to remmember so much lint rules.

When you write 100 lines of code, Clippy said you have 500 hundred bugs.

So useless feel.

Please stop growing Clippy. by design Rust better , working correct by default.

No one can say no will lead Rust growing to death. Who want to use a language with full of bugs?

**Comment by djc** [comment]
I'm sorry you feel that way. Unfortunately this issue doesn't seem very actionable. If you have specific Clippy lints that you think should be improved or disabled, please let us know. If not, I think this issue should be closed.

**Comment by cnmade** [comment]
most lint rules because the bad design of the Rust compiler or specification. If some code not right by lint check. 
May it be report error when Rustc compile time?
Bad code smell should not be compiled. 
If it can compiled. why not raise error or warning.

**Comment by cnmade** [comment]
No one notice the rule list growing ?  https://rust-lang.github.io/rust-clippy/master/index.html  
Each week it growing amazing.
Good news, or bad news.
