### ISSUE TITLE
`ty_and_layout_field`'s page cannot be displayed in docs

### ISSUE THREAD

**Issue by b-naber** [rust-lang/rust#93330]
Searching for the function in the [docs](https://doc.rust-lang.org/nightly/nightly-rustc/?search=ty_and_layout_field) is successful, but the [page](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/type.Ty.html#method.ty_and_layout_field) itself cannot be found.

This might be related to an issue with re-exports.

@rustbot label: +T-docs-rs, -T-compiler

**Comment by reez12g** [comment]
@b-naber 
Could you give me any clues as to what areas I need to fix?

**Comment by b-naber** [comment]
@reez12g I'm sorry, I can't. Not familiar with rustdoc. Try to ping Joshua Nelson or GuillaumeGomez on zulip.

**Comment by GuillaumeGomez** [comment]
I see the function in both cases without problem:

![Screenshot from 2022-07-24 13-54-55](https://user-images.githubusercontent.com/3050060/180645831-34b68ee1-c4d3-4f9a-bd67-9909985cee50.png)
![Screenshot from 2022-07-24 13-54-47](https://user-images.githubusercontent.com/3050060/180645830-b1027f26-0510-409d-997f-29ca4e2c0431.png)

So either I don't understand the issue, or it's not an issue. Closing it until further information is provided.

**Comment by jyn514** [comment]
Please don't ping me here or on Zulip, I'm no longer on the rustdoc team. There's a #rustdoc Zulip channel you can use

**Comment by reez12g** [comment]
Sorry, I'll be careful next time. Thank you very much.
