### ISSUE TITLE
Segfault in `_Unwind_Backtrace` when using compiler-rt

### ISSUE THREAD

**Issue by SchrodingerZhu** [rust-lang/rust#93360]
The error was similar as https://github.com/rust-lang/rust/issues/47551, but it was not exactly the same.

To make sure full LLVM env on Linux, I tried something like:
```base
#!/usr/bin/env bash
/usr/local/bin/clang++ -rtlib=compiler-rt -unwindlib=libunwind -stdlib=libc++ -Wl,-Bdynamic -l:libunwind.so -l:libc++abi.so -l:libc++.so /usr/local/lib/clang/13.0.0/lib/x86_64-unknown-linux-gnu/libclang_rt.builtins.a ${@//*gcc_s*}
```
and used it as the linker. 
Everything is working except that the program crashes in unwinding progress.
![image](https://user-images.githubusercontent.com/20108837/151297702-33f03609-cbdd-439d-96de-87f5fe54c168.png)

I have already posted a related thread at LLVM's discourse (please refer this link for more inspections on eh_frame sections): https://llvm.discourse.group/t/segfault-in-libunwind-during-cpu-profiling/5806.  But given #47551, I think `rustc` can also be a cause of the problem.

I have already switched back to shared linkage as it is shown in the script above, but the problem persists, just in different frames.

### Versions

LLVM `13.0.0`
Rust `nightly-2021-04-15`

**Comment by bossmc** [comment]
Unwinding from Rust into C++ is complex (might even be UB today, I'm not 100% sure, it was blocked in Rust 1.33 but then re-allowed soon after with large safety warnings) - https://github.com/rust-lang/project-ffi-unwind/blob/master/faq.md and related pages might tell you more about the current state of the world.

The presence of the zero terminator suggests this isn't the same issue as #47551 though it might be worth checking that it's at the end of the section and hasn't been inserted in the wrong place (seems unlikely but should be easy to check).

**Comment by SchrodingerZhu** [comment]
As a solution, we have decided to quit using compiler-rt and llvm's libunwind. Though, I am still looking forward for solutions!

**Comment by Enselic** [comment]
Triage: Can this still be reproduced with latest versions of everything? If yes, please provide detailed step by step instructions on how to reproduce in a fresh docker container.

**Comment by jieyouxu** [comment]
Based on https://doc.rust-lang.org/nomicon/unwinding.html unwinding across FFI boundary into another language is at present not supported.

> Rust's unwinding strategy is not specified to be fundamentally compatible with any other language's unwinding. As such, unwinding into Rust from another language, or unwinding into another language from Rust is Undefined Behavior. You must absolutely catch any panics at the FFI boundary! What you do at that point is up to you, but something must be done. If you fail to do this, at best, your application will crash and burn. At worst, your application won't crash and burn, and will proceed with completely clobbered state.

Please feel free to reopen if this is about Rust code unwinding into Rust.
