### ISSUE TITLE
Stripped symbol table information should not be discarded.

### ISSUE THREAD

**Issue by QiangHeisenberg** [rust-lang/rust#93406]
Run ```RUSTFLAGS='-C link-arg=-s' cargo build --release``` to obtain the release version of the stripped symbol table.But where did the divestiture go?How do I get it back?This information doesn't seem to be lost.

**Comment by ehuss** [comment]
I'm not sure if I understand the question, but a fundamental part of stripping a binary means the information is removed.

Questions like these are better asked on one of the user forums, such as https://users.rust-lang.org/.

**Comment by QiangHeisenberg** [comment]
Huss, it's great to see you.Yes, some information was deleted.

The deleted information needs to be used for debugging in my current project.
My current approach is to use objcopy to strip the symbol table and save the symbol table in the specified path, which is useful.
The purpose of my question here is to think that it would be better to add a function to save the deleted information to the specified path. Perhaps the deleted information (such as the symbol table) is needed in some scenarios.

**Comment by jyn514** [comment]
If you want to still generate debuginfo, but have it in a separate file from the binary, you can use `-C split-debuginfo`.

The issue tracker is not a support forum. For future questions please ask in one of these places:

https://discord.gg/rust-lang/
https://discord.gg/rust-lang-community/
https://users.rust-lang.org/
https://rust-lang.zulipchat.com/
