### ISSUE TITLE
rustdoc regression: Lifetime in type alias definition is incorrectly elided

### ISSUE THREAD

**Issue by camelid** [rust-lang/rust#93401]
It'd be good to minimize this and reproduce this outside of rustc.

### [beta](https://doc.rust-lang.org/beta/nightly-rustc/rustc_middle/ty/query/query_stored/type.resolutions.html) (incorrect)

![image](https://user-images.githubusercontent.com/37223377/151468380-30b3a29e-ea18-4a7f-918f-222aa82b93bc.png)

### [stable](https://doc.rust-lang.org/stable/nightly-rustc/rustc_middle/ty/query/query_stored/type.resolutions.html) (correct)

![image](https://user-images.githubusercontent.com/37223377/151468424-ae91f7a0-9ed8-4bcd-ab58-4858cfd5a0cf.png)

**Comment by inquisitivecrystal** [comment]
This bisects to #91430. 

Stop looking at me like that! `git bisect` is still a thing! And no, before someone asks, I do not volunteer to do this sort of thing on a regular basis. It took all day.

**Comment by camelid** [comment]
Thank you so much! FYI, using [`cargo-bisect-rustc`](https://github.com/rust-lang/cargo-bisect-rustc) (with `--prompt` and `-- doc --open`) would've probably been a lot faster :)

**Comment by camelid** [comment]
cc @b-naber

**Comment by camelid** [comment]
I guess the issue here is that `try_normalize_erasing_regions` is erasing the lifetimes (=regions) in the type, hence its name.

cc @jackh726 as well

**Comment by GuillaumeGomez** [comment]
I'm working on it.

**Comment by inquisitivecrystal** [comment]
> Thank you so much! FYI, using [`cargo-bisect-rustc`](https://github.com/rust-lang/cargo-bisect-rustc) (with `--prompt` and `-- doc --open`) would've probably been a lot faster :)

I feel *very* embarrassed. I figured that it wouldn't work, because generally cargo explodes whenever I try to use it on the compiler. I take it would actually work though?

**Comment by camelid** [comment]
Actually, I think you're right. cargo-bisect-rustc doesn't usually work on the compiler 🤦 

Sorry about that!

**Comment by Mark-Simulacrum** [comment]
The underlying principle *should* work though, by specifying rustc = ... in config.toml pointing to a rustup-toolchain-install-master'd binary (and potentially cargo = and/or rustdoc =).
