### ISSUE TITLE
Does `rust` support calling `macro methods` through `reflection`?

### ISSUE THREAD

**Issue by dragon-zhang** [rust-lang/rust#93430]
Does `rust` support calling `macro methods` through `reflection`?

**Comment by ehuss** [comment]
@dragon-zhang Please stop using the issue tracker for general questions.  One of the user forums, such as https://users.rust-lang.org/ might be a better place to ask them.  This issue tracker is specifically for reporting issues with the compiler and related tooling.

Also, the questions are a little vague and difficult to understand. I recommend first spending some time with some learning material such as [the book](https://doc.rust-lang.org/book/) to better familiarize yourself with rust.
