### ISSUE TITLE
Termination documentation should describe only the standard library runtime's use of Termination

### ISSUE THREAD

**Issue by Lokathor** [rust-lang/rust#93448]
The docs for the Termination are currently a little light. When the docs are expanded/updated as part of the stabilization the *likely* path forward is that they'll describe that a Termination returned from `main` will print any errors and then use `std::process::exit` to end the program.

When the Termination docs are expanded, we should be sure to maintain clearly that what the standard library's runtime does is *not* a hard requirement on what other runtimes must do with the Termination data. Particularly, a no_std binary being run on an embedded system does not necessarily have anywhere to print, and it certainly can't call the specific function `std::process::exit`.

* cc @yaahc

**Comment by Dylan-DPC** [comment]
Closing this as it's solved by #95207
