### ISSUE TITLE
rustdoc: include item type in search results

### ISSUE THREAD

**Issue by jsha** [rust-lang/rust#93496]
There are a fair number of items that have the same name but different types. For instance, `std::panic` (the macro) and `std::panic` (the module). Right now we distinguish these with colors. But that's not accessible for colorblind people. Also some of the colors are not often seen in a context where someone is likely to learn what they mean - for instance green for macros.

We should additionally distinguish search results by writing the actually type of the item. This should probably be its own column, between the item name and the description.

**Comment by GuillaumeGomez** [comment]
Why not putting it before the name every time instead of putting it in its own column?

**Comment by jsha** [comment]
For *most* searches, the name is the kost important thing and is
sufficiently distinctive. So it should be given the most important place,
at the beginning of the line. For a small number of searches the type is
needed to disambiguate, so it should come later.

**Comment by GuillaumeGomez** [comment]
Then `name (type)`?

**Comment by jaskij** [comment]
Maybe just the first letter even? Stylized differently, or as an icon, so that it stands out more.

**Comment by fmease** [comment]
For prior art, take a look at the doc pages of Scala 2 and 3. They use circles with the initial letter of the type in it.

* Scala 2: https://www.scala-lang.org/api/2.13.7/scala/concurrent/index.html?search=string
* Scala 3: https://dotty.epfl.ch/api/scala/math.html
  Click on the magnifier in the top right corner and search for `string`.
  It used to be the case that they prepended a circle to every single search result but nowadays the apparently
  group by type (maybe they considered it to be too noisy?).
  Just FYI, I am not a big fan of Scala 3's docs in general, I think their UX is horrible in a lot of cases.

**Comment by fmease** [comment]
Fixed by #110688.
