### ISSUE TITLE
Offline docs not installed on aarch64-apple-darwin

### ISSUE THREAD

**Issue by KevinArlin** [rust-lang/rust#93517]
I installed Rust with the following version details: ` stable-aarch64-apple-darwin installed - rustc 1.58.1 (db9d1b20b 2022-01-20)`

Upon running rustup doc `The file /Users/me/.rustup/toolchains/stable-aarch64-apple-darwin/share/doc/rust/html/index.html does not exist.`

Upon running rustup component add rust-docs `error: toolchain 'stable-aarch64-apple-darwin' does not contain component 'rust-docs' for target 'aarch64-apple-darwin'`

And similarly for trying to specify the toolchain explicitly when adding the component. 

According to [this](https://github.com/rust-lang/rust/pull/92800#issuecomment-1025173249) issue Tier 2 toolchains should be getting fallback docs for the best-related toolchain, in my case for Intel Mac, but there is some chatter I can't quite follow about possibly disabling this for aarch64.

**Comment by Mark-Simulacrum** [comment]
The relevant PR is only landed on nightly (1.60), so it hasn't made it to stable yet. Can you check with rustup install nightly?

**Comment by KevinArlin** [comment]
Ah of course. That fixed it, thanks.
