### ISSUE TITLE
Regression: Difference in float values

### ISSUE THREAD

**Issue by jnqnfe** [rust-lang/rust#93535]
My `libpulse-binding` crate has a set of time handling functionality with some conversion based tests. Today's monthly automated CI run has alerted me that some of the tests are failing with the current nightly compiler. Specifically assertions are failing with slightly different floating point results than expected. It seems that a presumed regression/breaking-change/unexpected-change has snuck into the nightlies.

I've determined that the nightly that introduced this difference is `nightly-2022-01-28`.

Details here:
 - https://github.com/jnqnfe/pulse-binding-rust/issues/48
 - https://github.com/jnqnfe/pulse-binding-rust/runs/5016523341?check_suite_focus=true

**Comment by SNCPlay42** [comment]
Bisection points to the rollup #93352, which contains PR #90247.

This looks like an issue of floating point precision, e.g. the decimal 2.3 isn't exactly representable as an `f32` and now `Duration::from_secs_f32` is picking a different rounding. Although this is evidently technically a breaking change, I'm not sure what guarantees are provided here.

@rustbot label regression-from-stable-to-nightly T-libs A-time A-floating-point

---

searched nightlies: from nightly-2022-01-26 to nightly-2022-02-01
regressed nightly: nightly-2022-01-28
searched commit range: https://github.com/rust-lang/rust/compare/6abb6385b2cb7249f67b9b3ce7522527767dd907...21b4a9cfdcbb1e76f4b36b5c3cfd64d627285093
regressed commit: https://github.com/rust-lang/rust/commit/009c1d02484dcc18e1596a33b3d8989a90361c89

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.1</summary>


Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --preserve -- test 
```

**Comment by jnqnfe** [comment]
@SNCPlay42 Thank you for identifying the relevant PR. If this is intentional and improves accuracy, as seems to be the case, then I have no wish personally for this to be "fixed", though being a breaking change it should be documented in the release notes when the time comes.

I'll have to go away and pick different values or something to work around it.

**Comment by Urgau** [comment]
Floating points numbers are very finicky. You should never try to compare them directly, you should instead use precision. See the book of the `float_eq` crate for more information's: https://jtempest.github.io/float_eq-rs/book/introduction.html

**Comment by nagisa** [comment]
> This looks like an issue of floating point precision, e.g. the decimal 2.3 isn't exactly representable as an f32 and now Duration::from_secs_f32 is picking a different rounding.

Precision is exactly the reason this issue arises. The previous implementation was discarding a significant amount of precision, and the new one is to the best of my knowledge lossless. While rounding mode did indeed change from round-to-nearest to truncating, it is important to note that:

1. truncation matches the rest of the Duration APIs (such as `Duration::subsec_micros`); and 
2. in the previous implementation rounding was occurring as a result of an intermediate floating point multiplication with a 1e9 before another truncation.

These are actual values stored in the f32 for two of the failing tests:

* `2.3f32` is actually `2.299_999_952_316...f32`
* `3.14f32` is actually `3.140_000_104_904...f32`

And these are exactly the values [the new implementation produces after truncating conversion](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=977c49fd7bd96a53bdad371f1c903c90).
