### ISSUE TITLE
Document canonicalization in `std::env::current_dir`

### ISSUE THREAD

**Issue by AZMCode** [rust-lang/rust#93598]
As of now, the stable and nightly documentation on `std::env::current_dir` only states
> Returns the current working directory as a PathBuf.

And proceeds to note a couple of errors the function may fail with.
This does not mention the fact that (as far as I am aware, testing on Linux) the path is also canonicalized, having resolved all symlinks in any segment of the path. I'd imagine not documenting this behavior could lead to confusion and/or bugs, if it already hasn't.

I tried this code within a symlink folder `/example/symlink/here` pointing to `/symlink/target/here`:

```rust
println!("{:#?}",std::env::current_dir().unwrap())
```

I expected to see get the output: `"/example/symlink/here"`
Instead, this was output: `"/symlink/target/here"`

Currently using the nightly compiler.

For obvious reasons, there's no backtrace.

Update: Read a bit through the code and realized this behavior might be libc-dependent
`ldd --version` on my system returns `ldd (GNU libc) 2.33`

**Comment by hkratz** [comment]
For UNIX Rust just calls `getcwd()` and that behavior is documented in the [POSIX spec](https://pubs.opengroup.org/onlinepubs/9699919799/functions/getcwd.html), so it will be the same on all conforming implementations. We should document which platform-specific function we call here just like we do with other filesystem functions (e.g. [here](https://doc.rust-lang.org/std/fs/fn.remove_dir.html#platform-specific-behavior)).

**Comment by GuillaumeGomez** [comment]
It was also missing for `set_current_dir` so I opened https://github.com/rust-lang/rust/pull/93635 for both.

**Comment by AZMCode** [comment]
Thanks a lot
