### ISSUE TITLE
error[E0433]: failed to resolve: use of undeclared type `Connection`

### ISSUE THREAD

**Issue by samsalgado** [rust-lang/rust#93650]
My code:
`
    {
        let db_connection = Connection::open("data.sqlite").unwrap();

        db_connection
            .execute(
                "create table if not exists todo_list (
                    id integer primary key,
                    item varchar(64) not null
                );",
                rusqlite::NO_PARAMS,
            )
            .unwrap();
    }

`

**Comment by compiler-errors** [comment]
@samsalgado I don't believe this is an issue with rustc. Can you please explain what issue you're trying to report?

**Comment by samsalgado** [comment]
The issue is with using .unwrap().

**Comment by timleg002** [comment]
Are you sure the `Connection` type is imported?

**Comment by name1e5s** [comment]
> The issue is with using .unwrap().

no, you need to add `use rusqlite::Connection` to your code.

**Comment by ehuss** [comment]
It is difficult to tell from the issue what this is trying to report.  This looks like a normal error of attempting to refer to something that isn't in scope.

I'm going to close, as this does not appear to be an issue with rustc.  I recommend if you are having trouble to use one of the user forums (such as https://users.rust-lang.org/). This issue tracker is specifically for bugs and other issues related to the compiler. I also recommend trying to provide as much context as you can, such as the complete source, what you tried, what happened, and what you expected.
