### ISSUE TITLE
Where's the tracking issue for `const_fn_trait_bound` stabilization?

### ISSUE THREAD

**Issue by Logarithmus** [rust-lang/rust#93679]
The compilation error leads to "https://github.com/rust-lang/rust/issues/57563", but I don't see any references for it there.
Just wanted to implement `const fn new()` for a generic struct with trait bounds...

**Comment by PatchMixolydic** [comment]
The current tracking issue for const trait bounds seems to be #67792, but the main body doesn't explicitly state that it tracks the `const_fn_trait_bound` feature gate (it mentions the provisional(?) const trait bound syntax, `~const Trait`, but this is difficult to recognize if you don't already know it).

@rustbot modify labels: +A-meta +F-const_trait_impl

**Comment by PatchMixolydic** [comment]
For the sake of posterity, the tracking issue for this feature gate is now #93706.
