### ISSUE TITLE
Access is denied(OS Error).

### ISSUE THREAD

**Issue by PrabeshPP** [rust-lang/rust#93699]
I am having this issue while installing the rand package

```cmd
cargo build
error: failed to get `rand` as a dependency of package `hello_world v0.1.0 (C:\Users\prabe\OneDrive\Desktop\Rust\hello_world)`

Caused by:
  failed to load source for dependency `rand`

Caused by:
  Unable to update registry `crates-io`

Caused by:
  failed to create directory `C:\Users\prabe\.cargo\registry\index\github.com-1ecc6299db9ec823`

Caused by:
  Access is denied. (os error 5)
```

Here is the Cargo.toml file code:

```toml
[package]
name = "hello_world"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
```
**Please! help me with this problem, I am new to rust.**

**Comment by Yush08** [comment]
Hello and welcome to Rust! \o

This doesn't seem like a Rust problem, rather a problem on your system which prevents Rust from making a directory in the path `C:\Users\prabe\.cargo\registry\index\github.com-1ecc6299db9ec823` -- by the error message, it seems like you don't have the permissions to write to that location.

This can happen if the computer is being handled by another organization/school. Could you please try running the terminal as administrator and trying again?

**Comment by the8472** [comment]
You can override the directory used for the cargo registry with the `CARGO_HOME` environment variable.
https://doc.rust-lang.org/cargo/reference/environment-variables.html

**Comment by jneira** [comment]
I hit the same problem recently and setting `CARGO_HOME` (and `RUSTUP_HOME` as i use it to manage the rust installation) worked for me.

**Comment by PrabeshPP** [comment]
Hi @Yush08 !
Thanks for the help!!
It worked .
