### ISSUE TITLE
consider giving precedence to `--config` over RUST_BOOTSTRAP_CONFIG

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#93725]
https://github.com/rust-lang/rust/blob/7b43cfc9b25ac4a906bd56d32d3111085dd9e6a1/src/bootstrap/bootstrap.py#L1224-L1228
It seems pretty strange to me that the env variable would take precedence over --config. It would be nice to switch the precedence.

cc @mark-simulacrum

_Originally posted by @jyn514 in https://github.com/rust-lang/rust/issues/92260#issuecomment-1030949332_

**Comment by Mark-Simulacrum** [comment]
Added in https://github.com/rust-lang/rust/pull/73317; it seems like it makes sense for --config to override, though probably not typically all that useful. Happy to see a PR, should be pretty easy so marking as such.
