### ISSUE TITLE
Missing loop optimization

### ISSUE THREAD

**Issue by notoria** [rust-lang/rust#93731]
The code on [godbolt](https://godbolt.org/#z:OYLghAFBqd5TKALEBjA9gEwKYFFMCWALugE4A0BIEAZgQDbYB2AhgLbYgDkAjF%2BTXRMiAZVQtGIHgBYBQogFUAztgAKAD24AGfgCsp5eiyahSAVyVFyKxqiIEh1ZpgDC6embZMDzgDIEmbAA5TwAjbFIDAAd0JWIHJjcPL2jY%2BKF/QJC2cMiea2xbeyERIhZSIiTPb3ybbDsE0vKiTOCwiINLZqqU2rKK1uzcqQBKa3QzUlROLiizUIBqGiYF%2BnR0KK0IFhAFiwIAL2xyBbYzIgXQ3f2jk9RruKORhYBaAFIAZlw9x%2BwFt4A7AAhN5aACCC0hCxYShUFTAkBY/y%2BlxGnxB4KhCwINGhr0uyJcC1Q/2BoIhWKhjAumGRABE8S9LujyZSoYJSAsAPrYlZaAB0/NpgIxFLZWMWbwATCCPgyeCzMeLAXTWeKAPTq6GwiJEBHbemfBmhNEfUXi5lKyEqhaFFSk83iyUy4lq60A1XglXkn1Sj5vACsQIkawA7hAcCxMFyMDg0QHPWDlpdtg9DsdTudLmnbsTdqF1vRnu8UTc/iK3dq4XrEcjvibFWLsbiSRWrZTqQthXLGcyzZWsRzubyFgKhQ6B07/jKjQsFf321jvYuoaFKza7eWySvISx1x6fR6uGN6NwA/xvFwdOR0NwAEoWC5KCZTct%2BvjkIjaY9jADWIADLRDG4aR%2BDYACgMva9by4fglBAICvyvY9yDgWAUFjPBCBICgqFoBhmHYGYP0EYQxAkTgZDkYRlDUTRkPIfQpUMYxTEfAoigSJwmFcdxqh8HjBnaPJyBiOJikSPjelEtIJKEnIOlqQp6gkpoKh6GoOJUxp%2BhaAI2gUkSunUqTNOMvSsmE0ZxkmaZuDmRZkzWDYth2H50xOK53Nze5vOwYtPm%2BMsJ3bGFq31JFAtRRssRxXtJQ%2BIlW23JssT3dsN3oe021S1dpyBV0MoPL0jxPM8L2/G970fBZn1st8PilfgkJ0EYxiQbAow6CAyq4UDyHAwDyCg/gYLghDP2/NryH/D4Pn5ObFqW5aADZgK4D4KoYsbJuQsY0IQeAIAw9A2CiAjcOoDAzoukBSB4AMAA4gLoegiAieCICuBjQgCcoAE9uA/a6OGEAB5Jh6EBhicDYVjJBhghSG0gA3bB4IY7B1Hqc5iP4AJ3tPXh%2BHoAhQlIAG3BwSqiFIAhwOJsYaCMYAlAANQIbBQzBqJmCB/hSNEcRJCowXaI0Sr9HyIwTDu9jSdCeDIDGDYJIxl4wbg5SGkcCBnA0gTMHk4Z8jE9JJOSTSzbk/ShkUrSdaYNTKlMzptdU3Tjft8yDb6ZovbyMY6tfAxaewPHevPYbKpg8xLBJHh%2BSe/ktAWCAH0sE58GIMhpw%2BfIFjcG7GE5aV85GZqpvazqcEiHqZog9b%2BsGyCY%2B4cbEKm1DEGOtBTvOkvKCu/vbvup6XoYd7SE%2B77r1%2B1hSGh4HTtBogIahyrYfhmZr0IZGGjRjHryxnH3v5yhhEKc%2BFYpxeqZ35q6YZvgmZZ9nOe53nLxI%2BRyJF2QxYqAlgxJiLFZZxysArJW9dVYJHVprB2EluK8UtobAOqRxIJF9jJTBGRbZWSUpxEoulsF1Eds7dBfsTKoKoRZAyJsg4vjssxMOEd1pRxGlVLgECE5J0einNOGcrALGzjhPOzFC4jxLuIiuu1WrVy6nXXqzdG6cJ2vBTue0/wgEavyFa%2BcACcK0AQBgeitR6j1pBWPWptaO2125yJQgdXuhAaA0CHrQX%2BwtKIAPkOLei156BIHgtLYJriaBEH%2BrzCapBgkgGYrEpQ4TInRK0JHLa0FuB0hxLiDmXMIgLB4XOPhAiUZKEKY%2BXhydrwtR/A3D40gU4NJWgYgxD0tAGIBI9KUzEib9TUQ4jRjjppEyagNKQWhW72NgsMsYaNp5cWkEAA%3D).

I expected the generated assembly to be same but the version with the loop generates more instruction.

**Comment by nikic** [comment]
Upstream patch: https://reviews.llvm.org/D120337

**Comment by the8472** [comment]
They generate the same assembly on nightly. Most likely due to the recent llvm upgrade.
