### ISSUE TITLE
error in format string : unreachable!("foo {bar,baz}"); no longer compiles

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#93761]
I tried this code:

```rust
unreachable!("passing both, --remove-if-{older,younger}-than was temporarily disabled!");
```

I expected to see this happen: 
This used to compile with edition 2018 and 2021 until `rustc 1.60.0-nightly (734368a20 2022-02-07)`

Instead, this happened: (edition 2021)
https://github.com/matthiaskrgr/cargo-cache/blob/a9b9f30fe6726390288c2337663409adc666a8a3/src/date.rs#L179

````
 error: invalid format string: expected `'}'`, found `','`
   --> src/date.rs:179:59
    |
179 |             unreachable!("passing both, --remove-if-{older,younger}-than was temporarily disabled!")
    |                                                     -     ^ expected `}` in format string
    |                                                     |
    |                                                     because of this opening brace
    |
    = note: if you intended to print `{`, you can escape it using `{{`

````

I'm not sure why this didn't pop up in the crater run for https://github.com/rust-lang/rust/pull/93394  so made a ticket just in case, cc @m-ou-se 

Feel free to close if this is a a true positive. :)

### Meta

`rustc --version --verbose`:
```
rustc 1.60.0-nightly (734368a20 2022-02-07)
binary: rustc
commit-hash: 734368a200904ef9c21db86c595dc04263c87be0
commit-date: 2022-02-07
host: x86_64-unknown-linux-gnu
release: 1.60.0-nightly
LLVM version: 13.0.0
```

**Comment by RalfJung** [comment]
Looks related to https://github.com/rust-lang/rust/issues/92137

**Comment by matthiaskrgr** [comment]
Ah so I guess this is expected breaking change then :sweat_smile: 
closing.
