### ISSUE TITLE
Win32 Alternate data streams don't work with Command in Rust 1.58.0

### ISSUE THREAD

**Issue by roblabla** [rust-lang/rust#93772]
Since Rust 1.58, code using `Command` to spawn new processes that live in an alternate data stream on Windows fails to work. Alternate Data Streams are files that have a `:suffix`, such as `filename.exe:alt`.

### Code

This is the code that fails:

```rust
std::fs::File::create("test.txt").unwrap();
std::fs::copy(r"C:\Windows\System32\find.exe", "test.txt:lolexe").unwrap();

let _cmd = Command::new("test.txt:lolexe")
    .status()
    .unwrap();
```

I expected to see this happen: The command spawns properly and executes the find.exe code

Instead, this happened: The unwrap fails with 

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { kind: NotFound, message: "program not found" }', altdatastreamprog/src/lib.rs:514:14
```

### Version it worked on

It most recently worked on: Rust 1.57.x

### Version with regression

```
rust 1.58.0
```

I believe the commit that broke it is https://github.com/rust-lang/rust/commit/d9a1f9a79c853f7f4678bfe43905ccc7560974bb

@rustbot modify labels: +regression-from-stable-to-stable -regression-untriaged

**Comment by Urgau** [comment]
I believe this is now the excepted behavior: [Windows: Resolve process::Command program without using the current directory](https://github.com/rust-lang/rust/pull/87704/)
I don't thing this has anything to do with Alternate Data Streams, but just the fact that the process is no longer resolved using the current working directory.

You could check if it works by making the executable explicitly relative by appending `.\` to your executable like this `.\test.txt:lolexe`.

cc @ChrisDenton

**Comment by ChrisDenton** [comment]
Indeed. The [release notes for 1.58](https://blog.rust-lang.org/2022/01/13/Rust-1.58.0.html#reduced-windows-command-search-path) gives the motivation for why the current directory is no longer used. In short, it was considered a security risk.
