### ISSUE TITLE
Document `rustc_index::vec::IndexVec`

### ISSUE THREAD

**Issue by pierwill** [rust-lang/rust#93792]
[`rustc_index::vec::IndexVec`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_index/vec/struct.IndexVec.html) is used in 103 files in the compiler, yet it lacks documentation.

**Comment by pnkfelix** [comment]
@mfrw happy to see you claim this. I figure I'll just note: If you're wondering about the motivation, it wouldn't hurt to review the commit that introduced the `IndexVec` and `Idx` abstractions: https://github.com/rust-lang/rust/pull/34149/commits/bc1eb67721a842d62bec8e879aad339fd22fe3c6

**Comment by mfrw** [comment]
> @mfrw happy to see you claim this. I figure I'll just note: If you're wondering about the motivation, it wouldn't hurt to review the commit that introduced the `IndexVec` and `Idx` abstractions: [bc1eb67](https://github.com/rust-lang/rust/commit/bc1eb67721a842d62bec8e879aad339fd22fe3c6)

Appreciate the pointer :)

**Comment by mfrw** [comment]
> @mfrw Can I claim this one?

Please do.. I am not getting the time at the moment

**Comment by JKAnderson409** [comment]
Thanks! @rustbot claim

**Comment by watsonkm** [comment]
One quick question re: `IndexVec` so I can help document it better--is the purpose of `_marker: PhantomData<fn(&I)>` to suggest to the drop checker that an instance of `Idx::index` in particular may drop at the same time as `IndexVec`? (Apologies for the simple question, I'm still getting my footing with Rust.)

Thanks!

**Comment by dev-ardi** [comment]
Anything that lacks clarification or this can be closed

**Comment by Dylan-DPC** [comment]
Closing this as #122015 should satisfy it (next time you can mention fixes <pr-number> or closes <pr-number> to autoclose the issue once the pr is merged if it there is nothing left to add to the issue)
