### ISSUE TITLE
Struct literals are forbidden in MatchExpressions (`feature(if_let_guard)`)

### ISSUE THREAD

**Issue by pushkine** [rust-lang/rust#93817]
# Bug Report

### 🕗 Version & Regression Information

nightly

### 🧪 Features

- `if_let_guard`

### 💻 Code

[Playground Link](https://play.rust-lang.org/?version=beta&mode=debug&edition=2021&gist=4ddc2d6ffd0202445dd8c3a3e6bdfa4d)
    
```rs
#![feature(if_let_guard)]

struct Bar {}
struct Foo { a: u32 }

fn main() {
    match 0 {
        _ if let _ = Bar {} => {}
        _ if let _ = Foo { a: 0 } => {}
        _ => {}
    }
}
```

### 🙁 Actual behavior

```rs
  _ if let _ = Bar {} => {}
//                 ^ error: expected one of `!`, `.`, `::`, `=>`, `?`, or an operator
```
```rs
  _ if let _ = Foo { a: 0 } => {}
//             ^^^^^^^^^^^^ error: struct literals are not allowed here
//                           help: surround the struct literal with parentheses
```

### 🙂 Expected behavior

No error

**Comment by scottmcm** [comment]
This is probably using the same parsing rules as normal `if let` expressions, where this behaviour is essential for avoiding ambiguity.

It's unclear if allowing this here would be worth it.  The good `help` is nice to see, though!

**Comment by joshtriplett** [comment]
I'm also not sure we should be more flexible here, given the potential difficulty of reading it in more complex cases.

**Comment by pushkine** [comment]
> given the potential difficulty of reading it in more complex cases

How so? `_ if Foo {} => {}` is already valid, the function parsing let expr is just hardcoded to not parse a struct expr
