### ISSUE TITLE
source files sidebar open/close animation is very slow and obscures source view

### ISSUE THREAD

**Issue by spacejam** [rust-lang/rust#93812]
The slow open/close animation which then obscures the text of the viewed source is a bit distracting, and makes it difficult for me to use the source view feature of docs.rs

If it simply displayed to the side of the source, without hiding the code that is the goal of having opened the menu in the first place, the slow animation would not be an issue. I don't see a way to take advantage of the view code feature without having to wait for the slow open animation and then the slow close animation between file navigations. It seems like there is no way to avoid clicking the open/close button twice for every new file searched.

![image](https://user-images.githubusercontent.com/1505488/153220612-5711ebb2-0fc5-4013-b77d-bca37da98411.png)

**Comment by spacejam** [comment]
@Nemo157 my mistake, thank you for transferring this issue <3

**Comment by GuillaumeGomez** [comment]
@spacejam Is it still the case? (you can check [here](doc.rust-lang.org/nightly/std)
