### ISSUE TITLE
Crater run for lazy TAIT

### ISSUE THREAD

**Issue by jackh726** [rust-lang/rust#93833]

**Comment by jackh726** [comment]
@craterbot check name=lazy-tait-check start=734368a200904ef9c21db86c595dc04263c87be0 end=cc38176793e9e13bb7b70dde4b951d9371017662 p=1

**Comment by oli-obk** [comment]
@craterbot cancel

**Comment by oli-obk** [comment]
@craterbot abort name=lazy-tait-check

**Comment by oli-obk** [comment]
Will do a crater run once I open a new PR. Reverting the breakage in https://github.com/rust-lang/rust/pull/93893 right now
