### ISSUE TITLE
Tracking Issue for process_set_process_group

### ISSUE THREAD

**Issue by krallin** [rust-lang/rust#93857]
Feature gate: `#![feature(process_set_process_group)]`

This is a tracking issue for: Add a `process_group` method to UNIX `CommandExt`

Add a `process_group` method to `std::os::unix::process::CommandExt` that
allows setting the process group id (i.e. calling `setpgid`) in the child, thus
enabling users to set process groups while leveraging the `posix_spawn` fast
path.

### Public API

```rust
trait CommandExt {
    fn process_group(
        &mut self,
        pgroup: i32,
    ) -> &mut process::Command
}
```

### Steps / History

- [x] RFC: https://github.com/rust-lang/rfcs/pull/3228
- [x] Implementation: #93858
- [x] Final comment period (FCP): https://github.com/rust-lang/rust/issues/93857#issuecomment-1179551697
- [x] Stabilization PR: #99088

### Unresolved Questions

- None yet.

**Comment by dtolnay** [comment]
This may or may not need a Fuchsia implementation. See https://github.com/rust-lang/rust/pull/93858#issuecomment-1036620106.

@rustbot ping fuchsia

**Comment by niklasf** [comment]
Some updates:
* The final comment period of the RFC has concluded (https://github.com/rust-lang/rfcs/pull/3228#issuecomment-1052632340).
* The implementation has been completed and merged (#93858).
* According to https://github.com/rust-lang/rust/issues/58590#issue-412329481, Fuchsia has no process hierarchy. It seems sensible to do nothing for now (same as for `CommandExt::groups`). Eventually #58590 will properly differentiate Unix and Fuchsia.

**Comment by joshtriplett** [comment]
T-libs-api, shall we stabilize `process_group`?

@rfcbot merge

**Comment by BurntSushi** [comment]
This LGTM, but can we improve the docs for `process_group` please? I think it should at least mention:

* Why this routine might be useful. When does someone want to use process groups?
* Why it's superior to setting the process group via `pre_exec`. (I don't think we want to be overly specific here, but a hint saying something like, "this may allow the implementation to use a faster path" would be nice.)

**Comment by joshtriplett** [comment]
> This LGTM, but can we improve the docs for `process_group` please? I think it should at least mention:

:+1:

>     * Why this routine might be useful. When does someone want to use process groups?

Some suggested documentation:

"Process groups determine which processes receive a signal when the user kills a process from its controlling terminal (e.g. hitting Ctrl-C to generate SIGTERM or Ctrl-\ to generate SIGQUIT). Shells and other programs that launch other programs use process groups to partition launched programs, such as foreground and background processes."

>     * Why it's superior to setting the process group via `pre_exec`. (I don't think we want to be overly specific here, but a hint saying something like, "this may allow the implementation to use a faster path" would be nice.)

As well as being safe, instead of the `unsafe` `pre_exec`.

**Comment by tmandry** [comment]
> This may or may not need a Fuchsia implementation. See [#93858 (comment)](https://github.com/rust-lang/rust/pull/93858#issuecomment-1036620106).

Fuchsia does have a concept of [jobs](https://fuchsia.dev/fuchsia-src/concepts/process/jobs) which have the same or similar role as process groups, but doesn't implement the POSIX notion of a process group id that's a universal integer. Instead, jobs (like all kernel objects) are represented by random 32-bit [handles](https://fuchsia.dev/fuchsia-src/concepts/kernel/handles) that are issued to a process by the kernel.

It might be possible to shoehorn this into the POSIX interface by passing a handle as a `pid_t`, but it's not clear whether this is a good idea (and anyway, we might remove some or all of `std::os::unix` for Fuchsia as @niklasf mentioned). Definitely don't block on us.

**Comment by JohnTitor** [comment]
Stabilized by https://github.com/rust-lang/rust/pull/99088, closing.
