### ISSUE TITLE
Should `std::str::CharRange` be public?

### ISSUE THREAD

**Issue by Kimundi** [rust-lang/rust#9387]
Currenty, str exports both `CharRange` and methods for getting an `CharRange` at an specific byte index of the string.

However, with Iterators we might not really need those to be public, and if we get an encoding module they might have to migrate to there anyway, as they are specific to the utf8 representation of a string.

**Comment by aturon** [comment]
Nominating for 1.0-beta P-backcompat-libs: we need to finalize the story around these methods.

**Comment by pnkfelix** [comment]
1.0 beta, P-backcompat-libs, I-needs-decision.

**Comment by alexcrichton** [comment]
This is now [explicitly behind its own feature gate](https://github.com/rust-lang/rust/pull/23461) so I'm going to de-milestone this issue as we will probably not stabilize it for 1.0 at this rate.

**Comment by huonw** [comment]
Closing in favour of the tracking issue for the feature gate: https://github.com/rust-lang/rust/issues/27754.
