### ISSUE TITLE
1.57 release notes are missing changes to dead code analysis

### ISSUE THREAD

**Issue by nsunderland1** [rust-lang/rust#93894]
#85200 landed in 1.57, causing derived  `Debug` and `Clone` implementations to be ignored during dead code analysis. The [release notes](https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1570-2021-12-02) for 1.57 don't mention this change anywhere.

There's discussion in the original PR about including it in the release notes, but looks like nobody got around to it.

**Comment by nsunderland1** [comment]
I think this is worth a mention in the compatibility notes for 1.57, given that it can break builds where `deny(dead_code)` is set.

**Comment by nsunderland1** [comment]
My bad there, had two different issues open.

**Comment by Mark-Simulacrum** [comment]
I'd be happy to approve a PR adding a line to the release notes about this.
