### ISSUE TITLE
Consider NonNull::cast::<U: ?Sized>

### ISSUE THREAD

**Issue by dragostis** [rust-lang/rust#93905]
[`NonNull::cast`](https://doc.rust-lang.org/std/ptr/struct.NonNull.html#method.cast) is implemented for `U`, but not for `U: ?Sized`.

**Comment by SkiFire13** [comment]
How would this work for casts that require adding metadata or changing its type? For example going from `NonNull<u8>` to `NonNull<dyn Read>` or from `NonNull<dyn Read>` to `NonNull<str>`

**Comment by compiler-errors** [comment]
For the record, `NonNull` implements `CoerceUnsized`, so you should be able to use the `as` operator to turn a `NonNull<T>` into a `NonNull<U>` where `U` is unsized (provided that `T` can be unsize-coerced into `U`).
