### ISSUE TITLE
Exported macros appear twice in left sidebar (rustc 1.60.0 nightly, docsrs 0.6.0)

### ISSUE THREAD

**Issue by tnballo** [rust-lang/rust#93912]
Hey! Ran into what appears to be a bug - crate's exported macros each appear twice in the left sidebar:

![doc_err_2](https://user-images.githubusercontent.com/24994892/153630374-27167dd2-26f0-4edb-8ea9-230279de8bbe.png)

* [Build log here](https://docs.rs/crate/scapegoat/2.3.0/builds/507548)
* [Current doc page here](https://docs.rs/scapegoat/2.3.0/scapegoat/)
* Toolchain versions (per log): rustc 1.60.0-nightly (e7aca8959 2022-02-09), docsrs 0.6.0 (5c3b689 2022-02-01)

Please let me know if I can provide additional info.

**Comment by GuillaumeGomez** [comment]
Seems similar to https://github.com/rust-lang/rust/issues/89852.

**Comment by tnballo** [comment]
Thanks for transferring the issue. 

One difference between this and #89852 - both macros are exported using a wildcard in crate root `lib.rs` (not `as` rename):

```rust
mod macros;
pub use macros::*;
```

**Comment by GuillaumeGomez** [comment]
Well, just another reexport issue. It's common around here. :laughing: 

I'll try to take a look in the next days.

**Comment by GuillaumeGomez** [comment]
This is what I have on currently nightly:

![Screenshot from 2022-02-12 14-07-53](https://user-images.githubusercontent.com/3050060/153712706-226a5467-fbd0-4416-b865-747e25aa1b1d.png)

So I guess it's fixed?

**Comment by tnballo** [comment]
Trying locally with the latest nightly (`rustc 1.60.0-nightly (e789f3a3a 2022-02-11)`, more current than that of issue open) I get the same initial landing page for `cargo doc --open` *but* if I click on one of the macros listed (e.g. "drill down") duplicates still appear on the sidebar:

![doc_err_3](https://user-images.githubusercontent.com/24994892/153720749-551544ac-0d5b-435d-9b23-d4b2dff26702.png)

So the tiny bug is still there, just deeper/hidden on the latest nightly?

**Comment by GuillaumeGomez** [comment]
Ah indeed! I can also reproduce it now. Will take another look tomorrow then.
