### ISSUE TITLE
`rustc` error on Windows: The filename or extension is too long

### ISSUE THREAD

**Issue by jszwedko** [rust-lang/rust#93920]
Hi all!

I think we are running into the same issue described by https://github.com/rust-lang/rust/issues/39644 but with `rustc.exe` rather than `link.exe`.

We have a project where we noticed that any PRs that introduce a new dependency were causing our Windows CI builds to fail with:

```
Caused by:
  The filename or extension is too long. (os error 206)
```

In the example failure below, it does seem like the `rustc` command is 33,184 characters, which would be over the 32,767 character limit mentioned in https://docs.microsoft.com/en-us/troubleshoot/windows-client/shell-experience/command-line-string-limitation.

Example failure:

https://github.com/vectordotdev/vector/runs/5157867395?check_suite_focus=true

Does that sound right to people? Do we need the same fix from https://github.com/rust-lang/rust/pull/44094 but for the `rustc` invocation?

### Meta

`rustc --version --verbose`:
```
rustc 1.58.1 (db9d1b20b 2022-01-20)
binary: rustc
commit-hash: db9d1b20bba1968c1ec1fc49616d4742c1725b4b
commit-date: 2022-01-20
host: x86_64-pc-windows-msvc
release: 1.58.1
LLVM version: 13.0.0
```

**Comment by jszwedko** [comment]
https://github.com/bazelbuild/rules_rust/pull/1076 seems related.

**Comment by ChrisDenton** [comment]
Yes, for arguments longer than the 32,767 limit, you would need to [load command-line flags from a path](https://doc.rust-lang.org/rustc/command-line-arguments.html#path-load-command-line-flags-from-a-path).

**Comment by jszwedko** [comment]
> Yes, for arguments longer than the 32,767 limit, you would need to [load command-line flags from a path](https://doc.rust-lang.org/rustc/command-line-arguments.html#path-load-command-line-flags-from-a-path).

Is that something we can do from outside? We are just executing `cargo test` which then calls `rustc`.

**Comment by ChrisDenton** [comment]
I think so. It seems more like a bug with Cargo because I'm not sure there's much rustc can do here. @ehuss, maybe?

**Comment by jszwedko** [comment]
Yeah, I think so too. I opened https://github.com/rust-lang/cargo/issues/10381 so I'll close this one out. Thanks for the pointer!
