### ISSUE TITLE
Compiler does not suggest to dereference a reference to reference

### ISSUE THREAD

**Issue by ChayimFriedman2** [rust-lang/rust#93983]
If I miss a `*` when assigning to a variable, rustc suggests dereferencing it:
```rust
let mut v: &mut ();
v = ();
```
```
error[E0308]: mismatched types
 --> src/main.rs:3:9
  |
2 |     let v: &mut ();
  |            ------- expected due to this type
3 |     v = ();
  |         ^^ expected `&mut ()`, found `()`
  |
help: consider dereferencing here to assign to the mutable borrowed piece of memory
  |
3 |     *v = ();
  |     +
```
[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=36e7c53bd5802be5d8f98f80d910add0).

But not the referent is a reference:
```rust
let v: &mut &();
v = &();
```
```
error[E0308]: mismatched types
 --> src/main.rs:3:9
  |
3 |     v = &();
  |         ^^^ types differ in mutability
  |
  = note: expected mutable reference `&mut &()`
                     found reference `&()`
```
[Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=ddaba7afea9a60c6f47f05727106aa0f).

This is because in compiler/rustc_typeck/src/check/demand.rs, we first check whether both the LHS and RHS are references and try to suggest adding/removing `b"..."`. But even if we did not succeed in that check, we don't continue to the next check where we check whether the LHS is a reference and should be dereferenced:

https://github.com/rust-lang/rust/blob/b11733534d95aebe0b4f949f8e4c8f21c312f108/compiler/rustc_typeck/src/check/demand.rs#L593-L627

**Comment by compiler-errors** [comment]
This is fixed.
