### ISSUE TITLE
Hard to read assert_eq!() custom message output

### ISSUE THREAD

**Issue by nyurik** [rust-lang/rust#94005]
The custom message in [assert_eq!(...)](https://doc.rust-lang.org/std/macro.assert_eq.html) macro is shown right after the `right:`. This is hard to read because the value strings could be very long.  I think it is better to print the custom message (if available) on a separate line. 

```rust
fn main() {
    let a = 10;
    let b = 20;
    assert_eq!(a, b, "Values {a} and {b}");
}
```

The above [code](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=d534f77fd85202724f3bd08453294573) (playground) prints this:

```none
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `10`,
 right: `20`: Values 10 and 20', src/main.rs:4:5
```

### Suggested output
```none
thread 'main' panicked at 'assertion failed: `(left == right)`
   left: `10`,
  right: `20`,
context: Values 10 and 20', src/main.rs:4:5
```

Note that custom message and the location in source are still on the same line

**Comment by Mizobrook-kan** [comment]
I will try it. @rustbot claim

**Comment by jyn514** [comment]
Note that the linked PR, #94016, has a lot of review comments. I think rebasing that PR and addressing the comments would already be very close to landing this change.

**Comment by nyurik** [comment]
@rustobot claim

**Comment by nyurik** [comment]
:tada: Horray! It only took 548 days (1.5+ years) since I created #94005 on Feb 14th, 2022. Numerous commits. Tens of people. 4 PRs... 100s of files. All to change a few lines of output :)

Special thanks to @m-ou-se for all the support!
