### ISSUE TITLE
Document `rustc_middle::mir::Field`

### ISSUE THREAD

**Issue by pierwill** [rust-lang/rust#94025]
This type, defined [here](https://github.com/rust-lang/rust/blob/87dbccd4b525daa0516dc43184905afb45eb88ee/compiler/rustc_middle/src/mir/mod.rs#L1844), lacks documentation. Documentation might want to answer questions like: What does this type represent? What are its uses?

@rustbot label +T-Compiler +E-Easy

**Comment by Mizobrook-kan** [comment]
I recently read this section, can I try it?

**Comment by Mizobrook-kan** [comment]
Thanks. I'll do my best.@rustbot claim

**Comment by pierwill** [comment]
@Mizobrook-kan: This comment might be helpful: https://github.com/rust-lang/rust/pull/94006#issuecomment-1043197748

> `Field` represents the position of a data field inside an datatype.

**Comment by compiler-errors** [comment]
Should we close this now that #94113 is landed?
