### ISSUE TITLE
optimized i686 fails primal-sieve tests

### ISSUE THREAD

**Issue by cuviper** [rust-lang/rust#94032]
Discovered in https://github.com/huonw/primal/pull/37#issuecomment-1040750795

### Code

I don't have reduced code, but the `primal-sieve` testsuite fails on `i686-unknown-linux-gnu` when compiled in `--release` mode, specifically on this line:
https://github.com/huonw/primal/blob/79bafd3400ecf530bea1d26db4f3854407588c2a/primal-sieve/src/sieve.rs#L769

```rust
    #[test]
    fn sum_primes() {
        let primes = Sieve::new(2_000_000);

        let mut manual_sum = 0u64;
        for p in primes.primes_from(0) {
            manual_sum += p as u64;
        }
        dbg!(manual_sum);

        let folded_sum = primes.primes_from(0).fold(0u64, |acc, p| acc + p as u64);
        let trait_sum = primes.primes_from(0).map(|p| p as u64).sum::<u64>();
        assert_eq!(manual_sum, folded_sum); // <-- FAILED
        assert_eq!(manual_sum, trait_sum);
    }
```

It fails when compiled from x86_64 host:
```
$ cd primal-sieve
$ cargo +nightly test --release --target i686-unknown-linux-gnu sum_primes
```
or with a native i686 host toolchain:
```
$cargo +nightly-i686 test --release sum_primes
```

I expected to see this happen: the test should pass

Instead, this happened: FAILED

```
---- sieve::tests::sum_primes stdout ----
[primal-sieve/src/sieve.rs:765] manual_sum = 307525716868
thread 'sieve::tests::sum_primes' panicked at 'assertion failed: `(left == right)`
  left: `307525716868`,
 right: `142913828922`', primal-sieve/src/sieve.rs:769:9
```

The left `manual_sum` is wrong, and the right `folded_sum` is correct. They both come from the same generated `primes` sieve, so that part of the code appears to have worked correctly. That leaves the difference between the `for` loop and the `fold`, and while `SievePrimes` does implement both `next` and `fold`, the differences are small.

The same test passes on i686 in debug mode, as well as x86_64 in debug or release.

### Version it worked on

It most recently worked on: stable Rust 1.58.1

### Version with regression

Both beta and nightly are failing the same way.

```
rustc 1.59.0-beta.8 (1945ce657 2022-02-12)
binary: rustc
commit-hash: 1945ce6579506787e0b18f0a2ea03fdb4dfc81c7
commit-date: 2022-02-12
host: x86_64-unknown-linux-gnu
release: 1.59.0-beta.8
LLVM version: 13.0.0
```

```
rustc 1.60.0-nightly (c5c610aad 2022-02-14)
binary: rustc
commit-hash: c5c610aad0a012a9228ecb83cc19e77111a52140
commit-date: 2022-02-14
host: x86_64-unknown-linux-gnu
release: 1.60.0-nightly
LLVM version: 13.0.0
```

@rustbot modify labels: +regression-from-stable-to-beta -regression-untriaged

**Comment by cuviper** [comment]
I just tried `armv7-unknown-linux-gnueabihf` under qemu to see if the bug is a 32-bit thing, but that passes fine.

**Comment by nikic** [comment]
The relevant difference with the NewPM seems to be that the next() method gets inlined now.

**Comment by apiraino** [comment]
Assigning priority as discussed in the [Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2394032.20optimized.20i686.20fails.20primal-sieve.20tests) of the Prioritization Working Group.

@rustbot label -I-prioritize +P-critical

**Comment by nikic** [comment]
Just tested this with the 9f2b322c3782ddda66efcfa36900d27f4507707e toolchain and it still fails, so this issue is not fixed in LLVM 14.

**Comment by pnkfelix** [comment]
@cuviper and I just found a slight variant that shows a similar failure on x86_64....

**Comment by cuviper** [comment]
We're discussing in this [Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/187780-t-compiler.2Fwg-llvm/topic/optimized.20i686.20fails.20primal-sieve.20tests.20.2394032/near/272278633). After discovering variant where x86_64 fails, we found that it also failed on stable back to 1.55, but passed on 1.54. Bisecting between those took me to #84560, a simple `#[inline]` addition, which I take to mean it just perturbed the code enough to expose a pre-existing codegen bug.

So, I'm removing the regression label, and we can treat like any ongoing bug.

**Comment by pnkfelix** [comment]
FYI I took the test from the primal crate and reduced it down to a single (large!) file: https://gist.github.com/pnkfelix/f45098bc69482dac920dcf384049b849

I suspect this is still too absurdly large to turn into LLVM bitcode to file a bug with LLVM. But, just as i write this, I realize it might suffice as input for the bitcode *automatic reduction tools*  that LLVM distributes. Looking in that next.

**Comment by nikic** [comment]
Upstream issue: https://github.com/llvm/llvm-project/issues/53990 Not a great reduction, but my attempts to construct a minimal MIR test failed.

**Comment by cuviper** [comment]
The [proposed patch](https://reviews.llvm.org/D120330) does work for me, thanks!

**Comment by apiraino** [comment]
Priority label has been mentioned during T-compiler weekly meeting [on Zulip](https://zulip-archive.rust-lang.org/stream/238009-t-compiler/meetings/topic/.5Bweekly.5D.202022-02-24.20.2354818.html#273108216). This will be reviewed in a follow-up meeting.
