### ISSUE TITLE
Standardize on self-containedness of examples in docs.

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#9403]
There are many examples in the docs that require some adjustments to get to compile, e.g. the following requires a `main` function:
```rust
let a = [0];
let b = [1];
let mut it = a.iter().chain(b.iter());
assert_eq!(it.next().get(), &0);
assert_eq!(it.next().get(), &1);
assert!(it.next().is_none());
```
(`Iterator.chain` at the time of filing.)

And others that are entirely self-contained, and can just be copy-pasted to be run.
```rust
use std::rand;

fn main () {
    let tuple_ptr = rand::random::<~(f64, char)>();
    printfln!(tuple_ptr)
}
```
(One of the examples at the top of `std::rand`.)

It seems like it would be good to be consistent about this. I prefer the latter, and it would make automatically running the tests much easier (#2925).

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#688
