### ISSUE TITLE
rustdoc: glob-import name clash (re-export)

### ISSUE THREAD

**Issue by dhardy** [rust-lang/rust#94049]
When a local module clashes with a re-exported module...

### Internal module
```rust
mod internal {
    /// X
    pub mod x {
        /// One
        pub const ONE: i32 = 1;
    }

    /// Y
    pub mod y {
        /// Unit
        pub struct Unit;
    }
}

pub use internal::*;

/// X, again
pub mod x {
    pub use crate::internal::x::*;

    /// Two
    pub const TWO: i32 = 2;
}
```

Resulting documentation (library root's module list):
```
x   X
x   X, again
y   Y
```
Both links for `x` link to the same page, which shows the documentation for `internal::x` (only lists constant `ONE`).

### Cross-crate re-export
Almost as above, but move `internal` into a different crate:
```rust
//! Internal crate

/// X
pub mod x {
    /// One
    pub const ONE: i32 = 1;
}

/// Y
pub mod y {
    /// Unit
    pub struct Unit;
}
```

```rust
//! Library

pub use internal::*;

/// X, again
pub mod x {
    pub use internal::x::*;

    /// Two
    pub const TWO: i32 = 2;
}
```

Resulting root documentation is the same (two links to the same page), but this time the page is for the derived library's `x` module (including both constants `ONE` and `TWO`).

### Expectation

From what I understand, when rustc sees a glob-imported name clash with another item, the glob-imported item is ignored. Rustdoc should similarly ignore the glob-imported item when it clashes.

Secondly, the first case above (internal module) should generate and link documentation for the `::x` module, not the `::internal::x` module.

### Rust verison

<details>

```
$ rustc --version --verbose
rustc 1.59.0-beta.6 (0426998f5 2022-02-02)
binary: rustc
commit-hash: 0426998f5fc4b95dfec57853bf4bd3cf82feb4bf
commit-date: 2022-02-02
host: x86_64-unknown-linux-gnu
release: 1.59.0-beta.6
LLVM version: 13.0.0
```
</details>

**Comment by fmease** [comment]
The first example (section *Internal module*) seems to have been fixed by now:

```
x   X, again
y   Y
```

**Comment by fmease** [comment]
The second one (section *Cross-crate re-export*) is now fixed, too.

**Comment by fmease** [comment]
Closing as completed.
