### ISSUE TITLE
Mismatched type in macro attribute

### ISSUE THREAD

**Issue by hellow554** [rust-lang/rust#94074]
Given the following code: https://github.com/estebank/makeit/blob/97518801c2ff265b6de226dbaa77f2cfd645a674/makeit/examples/invalid2.rs

```rust
use makeit::{Buildable, Builder};

#[derive(Builder)]
struct Bar {
    bar: u32,
    #[default(32)]
    baz: Option<i32>,
}

pub fn y() {
    let x = Bar::builder().set_bar(1).set_baz(Some(2)).build();
    println!("{:?} {:?}", x.bar, x.baz);
    let x = Bar::builder().set_bar(1).build();
    println!("{:?} {:?}", x.bar, x.baz);
}

fn main() {
    y();
}
```

The current output is:

```
error[E0308]: mismatched types
 --> makeit/examples/invalid2.rs:7:14
  |
7 |     #[default(32)]
  |              ^^^^ expected enum `Option`, found integer
  |
  = note: expected enum `Option<i32>`
             found type `{integer}`
help: try wrapping the expression in `Some`
  |
7 |     #[defaultSome((32))]
  |              +++++    +
```

Ideally the output should look like:

```
error[E0308]: mismatched types
 --> makeit/examples/invalid2.rs:7:14
  |
7 |     #[default(32)]
  |               ^^  expected enum `Option`, found integer
  |
  = note: expected enum `Option<i32>`
             found type `{integer}`
help: try wrapping the expression in `Some`
  |
7 |     #[default(Some(32))]
  |               +++++    +
```

I think the span for the integer is too big.  It includes the paranthese, but I'm not sure if that has something to do with expansion of the macro.  
Maybe @estebank can something say about this as the author of said library.

@rustbot modify labels: D-invalid-suggestion

**Comment by estebank** [comment]
I'm closing this as I agree with @ChayimFriedman2's take on this: it is a bug of the proc-macro and not of rustc's `Span`s. That being said, IMO the proc-macro API leaves a bit to be desired to begin with 😅 (I understand *why*, but I don't have to like it.)
