### ISSUE TITLE
`-Zprofile` and `should_panic` don't work together.

### ISSUE THREAD

**Issue by wllenyj** [rust-lang/rust#94090]
When I run the cargo test as follows:
```
export CARGO_INCREMENTAL=0
export RUSTFLAGS="-Zprofile -Ccodegen-units=1 -Copt-level=0 -Clink-dead-code -Coverflow-checks=off -Zpanic_abort_tests -Cpanic=abort"
export RUSTDOCFLAGS=-Cpanic=abort
cargo clean
sudo -E cargo test $CARGO_OPTIONS -- -Z unstable-options
```
The test will panic. This test case is a `should_panic` test.
```
...
test x86_64::cpuid::bit_helper::tests::test_invalid_msb_index - should panic ... FAILED
...
failures:

---- x86_64::cpuid::bit_helper::tests::test_invalid_msb_index stdout ----
---- x86_64::cpuid::bit_helper::tests::test_invalid_msb_index stderr ----
thread 'main' panicked at 'Invalid BitRange', crates/db-arch/src/x86_64/cpuid/bit_helper.rs:67:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
This is a probability issue, as I am running in project ci and using rust nightly are the latest version. The most recent recurrence is rustc 1.60.0-nightly (75d9a0ae2 2022-02-16). 

See https://github.com/openanolis/dragonball-sandbox/runs/5234196020 for more details.

Sorry about this issues may report the wrong place. But this problem is really annoying and can occur every day.

**Comment by TeXitoi** [comment]
Looks like a rust bug: the test is `should_panic`, and it panics, but it is detected as failed.

I can reproduce on stable with `cargo test --release -- --test flatten`

**Comment by jieyouxu** [comment]
Triage: `-Zprofile` #132447
