### ISSUE TITLE
Invalid code suggestion for ambigous trait generic argument

### ISSUE THREAD

**Issue by russelltg** [rust-lang/rust#94197]
I tried this code:

```rust
struct A<T>(T);
struct B;

trait I<T> {}

impl I<u32> for B {}
impl I<u64> for B {}

trait V<T> {
    fn create(&self) -> T;
}

impl<T, U> V<U> for A<T> where T: I<U>, U: Default {
    fn create(&self) -> U {
        U::default()
    }
}

fn main() {
    let a = A(B);
    a.create();
    // <B as I<u32>>::create(a);

}

```
[playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=c4b5fd0b0d2eed6d0ae557056587354b)

I expected to see this happen: Compiler error with either correct suggestion or no suggestion at all

Instead, this happened: Suggestion that does not compile: 

```rust
help: use the fully qualified path for the potential candidates
   |
22 |     <B as I<u32>>::create(a);
   |     ~~~~~~~~~~~~~~~~~~~~~~~~
22 |     <B as I<u64>>::create(a);
   |     ~~~~~~~~~~~~~~~~~~~~~~~~
```

What even is the correct way to disambiguate this situation?

### Meta

`rustc --version --verbose`:
```
rustc 1.61.0-nightly (3b348d932 2022-02-19)
binary: rustc
commit-hash: 3b348d932aa5c9884310d025cf7c516023fd0d9a
commit-date: 2022-02-19
host: x86_64-unknown-linux-gnu
release: 1.61.0-nightly
LLVM version: 14.0.0

```

**Comment by dtolnay** [comment]
Seems like the correct suggestions would be:

```console
<A<B> as V<u32>>::create(&a);
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
<A<B> as V<u64>>::create(&a);
~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by dtolnay** [comment]
There are at least 3 things going wrong in this diagnostic. I filed them separately and I am closing this issue in favor of:

- #96291
- #96292
- #96295
