### ISSUE TITLE
"trait bound not satisfied" error with HRTBs when just mentioning a fn.

### ISSUE THREAD

**Issue by Dirbaio** [rust-lang/rust#94207]
rustc stable 1.58.1

The following code gives a strange error when just mentioning `foo`, without even calling it. As far as I can tell the bounds are well-formed, and the error can't be about passing the wrong type to `foo` because it isn't even getting called. [Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=37e8be108458b0d98602f12cbba9e4fb)

```rust
trait Bar{}
trait Baz<T> {
    type Output;
}

fn foo<F>(f: F)
where
    for<'a> F: Baz<&'a u32>,
    for<'a> <F as Baz<&'a u32>>::Output: Bar,
{
}

fn main() {
    foo; // error[E0277]: the trait bound `for<'a> <_ as Baz<&'a u32>>::Output: Bar` is not satisfied
}
```

Full error:

```
error[E0277]: the trait bound `for<'a> <_ as Baz<&'a u32>>::Output: Bar` is not satisfied
  --> src/main.rs:14:5
   |
14 |     foo; // error[E0277]: the trait bound `for<'a> <_ as Baz<&'a u32>>::Output: Bar` is not satisfied
   |     ^^^ the trait `for<'a> Bar` is not implemented for `<_ as Baz<&'a u32>>::Output`
   |
note: required by a bound in `foo`
  --> src/main.rs:9:42
   |
6  | fn foo<F>(f: F)
   |    --- required by a bound in this
...
9  |     for<'a> <F as Baz<&'a u32>>::Output: Bar,
   |                                          ^^^ required by this bound in `foo`
```

**Comment by jackh726** [comment]
Pretty sure this is #90950. Specifying a type for `F` for `foo` should work: `foo::<X>`

**Comment by nikomatsakis** [comment]
I'm not sure this is a bug at all, or rather, it may be a diagnostics issue-- the value of `F` is not given, so we are not going to be able to prove that the where clauses on `foo` hold, but I would expect it to say 'please provide a type annotation'. Am I missing something?

(Also, this is not GATs, right?)

**Comment by jackh726** [comment]
Yeah, this isn't GATs.

**Comment by compiler-errors** [comment]
This is now "type annotations needed", so this is fixed.
