### ISSUE TITLE
PR #94122 Broke `cargo -Z build-std`

### ISSUE THREAD

**Issue by ivmarkov** [rust-lang/rust#94219]
I don't know how that's possible, but https://github.com/rust-lang/rust/pull/94122 broke [cargo -Z build-std](https://doc.rust-lang.org/cargo/reference/unstable.html#build-std), so all our CIs currently [fail](https://github.com/esp-rs/esp-idf-svc/runs/5269416558?check_suite_focus=true) with:
```
...
Compiling rustc-demangle v0.1.21
   Compiling thiserror-impl v1.0.30
   Compiling strum_macros v0.23.1
   Compiling ureq v2.4.0
   Compiling rustc-std-workspace-alloc v1.99.0 (/home/ivan/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/rustc-std-workspace-alloc)
   Compiling panic_abort v0.0.0 (/home/ivan/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/panic_abort)
   Compiling panic_unwind v0.0.0 (/home/ivan/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/panic_unwind)
   Compiling std_detect v0.1.5 (/home/ivan/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/stdarch/crates/std_detect)
   Compiling hashbrown v0.12.0
   Compiling thiserror v1.0.30
error[E0463]: can't find crate for `miniz_oxide`
   --> /home/ivan/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/lib.rs:369:1
    |
369 | extern crate miniz_oxide;
    | ^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

...
```

Commenting out the three lines this PR introduces allows the STD build to proceed normally.

**Comment by GuillaumeGomez** [comment]
How a rustdoc tag can break a normal build? O.o

**Comment by ivmarkov** [comment]
Well, I can dig a bit further - but - if I trust my eyes - commenting these three lines allows the build to continue?

And - strictly speaking - is it just a rustdoc tag? You are declaring a crate as extern.

**Comment by GuillaumeGomez** [comment]
Ok, I think I know where the problem comes from: `miniz_oxide` is an optional dependency and it should have been taken into account...

**Comment by camelid** [comment]
It seems that maybe it'd be a good idea to test `-Z build-std` in CI somehow so this sort of thing doesn't happen again?

**Comment by GuillaumeGomez** [comment]
@camelid Agreed. The difficult part is that I think it'd require a whole new CI run. To be discussed with infra...
