### ISSUE TITLE
https://doc.rust-lang.org/error-index.html is not getting updated

### ISSUE THREAD

**Issue by kpreid** [rust-lang/rust#94222]
The text at <https://doc.rust-lang.org/error-index.html> is stale compared to what appears to be its source material, <https://github.com/rust-lang/rust/tree/master/compiler/rustc_error_codes/src/error_codes>.

For example, the [section for E0038](https://doc.rust-lang.org/error-index.html#E0038) uses the deprecated `dyn`less syntax `Box<Trait>`, but [the markdown file in Git](https://github.com/rust-lang/rust/blob/master/compiler/rustc_error_codes/src/error_codes/E0038.md) does not and has been substantially revised.

I found that the file is generated by `src/tools/error_index_generator` into `build/<target>/doc/error-index.html`, but I don't know how that file should get deployed to `doc.rust-lang.org`.

**Comment by Mark-Simulacrum** [comment]
I believe this is just a case of needing to wait until the relevant PR hits stable -- the top-level files on doc.rust-lang.org are updated on each stable release. In this case, https://github.com/rust-lang/rust/pull/91387 needs to hit stable which will happen later this week. Closing as not-actually-a-bug.
