### ISSUE TITLE
bootstrap: RUSTFLAGS_BOOTSTRAP does not affect building bootstrap

### ISSUE THREAD

**Issue by jonhoo** [rust-lang/rust#94234]
I'll prefix this with: I don't _know_ if this is a bug, or just confusing behavior.

It appears that setting `RUSTFLAGS_BOOTSTRAP` does not affect the `RUSTFLAGS` used to build the Rust-based bootstrap binary (`src/bootstrap`). Instead, when `x.py` builds `src/bootstrap`, it just uses `RUSTFLAGS` directly:

https://github.com/rust-lang/rust/blob/8769f4ef2fe1efddd1f072485f97f568e7328f79/src/bootstrap/bootstrap.py#L1012-L1013

Given the name of `RUSTFLAGS_BOOTSTRAP`, this seems counterintuitive. Even if this is the desired behavior, it should probably be documented. Or perhaps `x.py` could detect if `RUSTFLAGS_BOOTSTRAP` is set and warn about the fact that it is ignored?

### Meta

`rustc --version --verbose`:
```
rustc 1.58.1 (db9d1b20b 2022-01-20)
binary: rustc
commit-hash: db9d1b20bba1968c1ec1fc49616d4742c1725b4b
commit-date: 2022-01-20
host: x86_64-unknown-linux-gnu
release: 1.58.1
LLVM version: 13.0.0
```

**Comment by jyn514** [comment]
RUSTFLAGS_BOOTSTRAP is set only when compiling rustc for the first time. If you want a flag to affect rustbuild, use RUSTFLAGS. There's no way to set flags for rustbuild and not rustc that I know of.

**Comment by Mark-Simulacrum** [comment]
I would expect RUSTFLAGS_BOOTSTRAP to affect all builds with the stage0 (beta) compiler -- it's probably an oversight if that's not the case and could be corrected.
