### ISSUE TITLE
[ER] array::reshape ?

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust#94258]
Here I propose to add a new commonly useful array method related to slice::as_chunks_unchecked_mut and similar ones and also related to Iterator::flatten. (But this one is safe). Its purpose is to replace std::mem::transmute in a common and provably safe group of cases. That is to reshape arrays. From 3x2 => 2x3 => 6x1, etc. This means the number of input dimensions could be different from the number of output dimensions, but the number of items must be the same.

Perhaps Rust allows to create a single array function that works for any number of dimensions, despite the lack of const-variadics. This is better and cleaner. But I think in most cases 4 dimensions could suffice:

```rust
array::reshape_1d::<const N0: usize>() -> &[T; N0];
array::reshape_2d::<const N0: usize, const N1: usize>() -> &[[T; N0]; N1];
array::reshape_3d::<const N0: usize, const N1: usize, const N2: usize>() -> &[[[T; N0]; N1]; N2];
array::reshape_4d::<const N0: usize, const N1: usize, const N2: usize, const N3: usize>() -> &[[[[T; N0]; N1]; N2]; N3];

array::reshape_1d_mut::<const N0: usize>() -> &mut [T; N0];
array::reshape_2d_mut::<const N0: usize, const N1: usize>() -> &mut [[T; N0]; N1];
array::reshape_3d_mut::<const N0: usize, const N1: usize, const N2: usize>() -> &mut [[[T; N0]; N1]; N2];
array::reshape_4d_mut::<const N0: usize, const N1: usize, const N2: usize, const N3: usize>() -> &mut [[[[T; N0]; N1]; N2]; N3];
```

**Comment by SkiFire13** [comment]
Wouldn't this become obsolete with project-safe-transmute?

**Comment by leonardo-m** [comment]
> Wouldn't this become obsolete with project-safe-transmute?

Thank you for your comments. You're right, a safe-transmute should be a superset of an array reshaping functionality. The advantage of a reshape() function is that its API is more specific, so it's probably a little simpler (simpler to understand its purpose when you read code too). So the question is if it's worth having an array::reshape() once the safe-transmute ideas are implemented. I think this decision should be delayed after safe-transmute. So I close this issue down and I'll re-open it if I think it's still worth having this function after safe-transmute.
