### ISSUE TITLE
[ER] Iterator::array_chunks_copy ?

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust#94257]
In Itertools there's Itertools::next_tuple():

https://docs.rs/itertools/0.10.3/itertools/trait.Itertools.html#method.next_tuple

But for the Rust stdlib I prefer something more general, an array chunks for iterator (that perhaps works only on Copy types?):

Iterator::array_chunks_copy::<const LEN: usize>()

It's similar to slice::array_chunks but I think it should return actual arrays instead of array references.

Beside this functions I'd like a rustc (or Clippy) lint that warns against returning large chunks.

**Comment by SkiFire13** [comment]
Have you seen #92393 and #93700?

**Comment by leonardo-m** [comment]
> Have you seen #92393 and #93700?

Thank you, I didn't, I close this issue down as dupe.
