### ISSUE TITLE
Navigating back/forward in rustdocs causes theme change if page is restored from bfcache

### ISSUE THREAD

**Issue by thanatos** [rust-lang/rust#94250]
I normally use the "dark" theme for docs.rs ; however, lately, if I hit "back" to go backwards, the previous page is now in light mode, not dark mode. Refreshing the page fixes it, but is annoying, of course.

**Comment by jyn514** [comment]
Please file this under rust-lang/docs.rs.

**Comment by thanatos** [comment]
I did some digging: this happens locally as well as in `docs.rs`. Since `rustdoc` is in this repo, I think this is the right place for it.

The bug is around here: https://github.com/rust-lang/rust/blob/aaa9bb9e7bb4b8b565f2e1570587d6c21b13ab2d/src/librustdoc/html/static/js/storage.js#L221-L228

Essentially, there are two paths through this file:
1. On initial page load, we run the top-level JavaScript: in particular, we call `updateSystemTheme()` which detects the system theme (dark, on my system) and sets the page theme appropriately.
2. _Possibly_ (it's up to the UA) on navigation, such as back/forward — if the page is restored from bfcache , the top level JS isn't run. (As the page is stlil, in essence, "alive".) Instead, a `pageshow` event fires, and that calls the highlighted method above, `switchToSavedTheme`. That method unilaterally sets a theme — *but never obeys the system theme*, and thus, we end up with buggy theme switch. (On my system, the `getSettingValue("theme")` will return `null`, and so it goes with the default of `'light'`, despite the prefers-dark-theme pref.)
