### ISSUE TITLE
[ER] slice::partial_sort ?

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust#94256]
In Rust code that uses Itertools I see code like

data.sorted().rev().take(3)...

Or more generally I see sorting + take. In such cases when the number of items to take is small it's better to use a faster algorithm that sorts only those few items. This is the partialSort() of the D language stdlib:

https://dlang.org/phobos/std_algorithm_sorting.html#partialSort

Currently in Rust this could be done efficiently using select_nth_unstable() followed by sort() of just the first items.

**Comment by SkiFire13** [comment]
> Currently in Rust this could be done efficiently using select_nth_unstable() followed by sort() of just the first items.

This can also be done using a `BinaryHeap` for any general `Iterator`. In fact Itertools uses it for `k_smallest`.

The problem I see with this iterator adapter is that it must consume the wrapped iterator before being able to yield the first item, which goes against how every other stdlib's iterator adapter works.

**Comment by leonardo-m** [comment]
>The problem I see with this iterator adapter is that it must consume the wrapped iterator before being able to yield the first item, which goes against how every other stdlib's iterator adapter works.

I see. I close this issue down as unfit for stdlib for now. (But I've used Itertools just for the sorted() adapter, and I think it's so useful that with a different API it's worth having a sorted() in the stdlib).
