### ISSUE TITLE
Add a lint for unnecessary trailing return

### ISSUE THREAD

**Issue by huonw** [rust-lang/rust#9426]
```rust
fn foo() -> int {
    return 1; // warning: unnecessary `return`.
}
```

It would be extremely neat if it could handle
```rust
fn foo() -> int {
    if bar() {
        return 1;
    } else {
        return 2;
    }
}
```

(This is purely stylistic: how many style lints do we want/need?)

**Comment by steveklabnik** [comment]
triage: no change 

personal note: would love to see this.

**Comment by sanxiyn** [comment]
This is implemented as needless_return in Clippy. It handles both of @huonw's examples and more. Check [the test](https://github.com/Manishearth/rust-clippy/blob/master/tests/compile-fail/needless_return.rs).
