### ISSUE TITLE
multiple definition of `llvm:: cl ::Option::anchor()' when running x.py build

### ISSUE THREAD

**Issue by wangbyby** [rust-lang/rust#94275]
Hi，I am working for huawei. And I am trying to build rustc with `bisheng`, a custom version of  llvm12.
But I get some errors in running command `./x.py build`. The log is very long, so I split it into two files:  [error_1.txt](https://github.com/rust-lang/rust/files/8122074/error_1.txt), [error_2.txt](https://github.com/rust-lang/rust/files/8122075/error_2.txt).
Some of them looks like this:
```
/usr/bin/ld: /home/byw/rust_bisheng/bisheng/build/aarch64-unknown-linux-gnu/stage0-rustc/aarch64-unknown-linux-gnu/release/deps/librustc_llvm-ef22ef6f00ab31b7.rlib(CommandLine.cpp.o): in function `llvm::cl::GenericOptionValue::anchor()':
          CommandLine.cpp:(.text._ZN4llvm2cl6Option6anchorEv+0x0): multiple definition of `llvm::cl::Option::anchor()'; /home/byw/rust_bisheng/bisheng/build/aarch64-unknown-linux-gnu/stage0-rustc/aarch64-unknown-linux-gnu/release/deps/librustc_llvm-ef22ef6f00ab31b7.rlib(CommandLine.cpp.o):CommandLine.cpp:(.text._ZN4llvm2cl6Option6anchorEv+0x0): first defined here
```

- Version of rust code: in branch master, the latest commit is 930fc4f59dd.
- And the version of some system compoents:
```bash
[byw@llvm-tool-chain rust]$ cc -v
Using built-in specs.
COLLECT_GCC=cc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/aarch64-linux-gnu/7.3.0/lto-wrapper
Target: aarch64-linux-gnu
[wangboyang@llvm-tool-chain rust]$ uname -a
Linux 4.19.36-vhulk1905.1.0.h273.eulerosv2r8.aarch64 #1 SMP Mon Apr 1 00:00:00 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux
[wangboyang@llvm-tool-chain rust]$ ldd --version
ldd (GNU libc) 2.28
```
- version of llvm
Because it's a custom version of llvm12, I can't get the version num.
But I compare the config between `bisheng` with llvmorg-12.0.0, no difference.

- config.toml: [config.txt](https://github.com/rust-lang/rust/files/8122128/config.txt)
github not support `.toml`, so I rename `.toml` to `.txt`.

I can't provide the source code of `bisheng`. 
So, Can I fix this error? And why this error occurs?

Thanks a lot!

**Comment by jyn514** [comment]
Are you still running into this problem? it seems likely to be related to your custom LLVM ... do you see the same problem when using upstream LLVM?

**Comment by wangbyby** [comment]
Thanks to reply. The problem was solved. I forgot to close this issue.
Because I use wrong llvm-version and rustc-version.
