### ISSUE TITLE
Explain name of `rustc_middle::traits::query::DtorckConstraint`

### ISSUE THREAD

**Issue by pierwill** [rust-lang/rust#94310]
What does `Dtorck` in [`DtorckConstraint`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/traits/query/struct.DtorckConstraint.html) stand for? "Destruction check?" Didn't find any answer in a few searches of docs and rustc dev guide.

@rustbot label:T-compiler E-easy

**Comment by InfRandomness** [comment]
After a bit of goofing around in the code, I think that Dtor stands for Destructor

**Comment by InfRandomness** [comment]
Drop"top"check?
What would the top be for then?

**Comment by bjorn3** [comment]
It may be that `DtorckConstraint` was named before we consistently starting to use dropck.

**Comment by bjorn3** [comment]
I think so.

**Comment by bjorn3** [comment]
`DtorckConstraint` was moved in that commit. You can see that it originated from here: https://github.com/rust-lang/rust/commit/4e42f388#diff-d2a1fdabeaebb273459e840ceb8ad8eef3e2dd5f8b34b608309587217608216bL104

**Comment by InfRandomness** [comment]
> `DtorckConstraint` was moved in that commit. You can see that it originated from here: [4e42f388#diff-d2a1fdabeaebb273459e840ceb8ad8eef3e2dd5f8b34b608309587217608216bL104](https://github.com/rust-lang/rust/commit/4e42f388#diff-d2a1fdabeaebb273459e840ceb8ad8eef3e2dd5f8b34b608309587217608216bL104)

Right, yeah I meant it was moved.
Renaming it is then.
