### ISSUE TITLE
track_caller on panic_no_unwind leads to LLVM crash

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#94337]
https://github.com/rust-lang/rust/pull/94290 is expecting to land having introduced `#[cfg_attr(bootstrap, track_caller)]` on [panic_no_unwind in library/core/src/panicking.rs](https://github.com/rust-lang/rust/pull/94290#discussion_r813144009).

We saw these errors in stage 1 std compilation in CI (with track_caller and without it):

```
Incorrect number of arguments passed to called function!
  tail call void @_ZN4core9panicking15panic_no_unwind17heb5bd7bc5de639ecE(%"core::panic::location::Location"* bitcast (<{ i8*, [16 x i8] }>* @10 to %"core::panic::location::Location"*)) #15
in function _ZN12panic_unwind8real_imp5panic17exception_cleanup17h7b2c07bcac8db7c5E
LLVM ERROR: Broken function found, compilation aborted!
[0m[0m[1m[31merror[0m[1m:[0m could not compile `panic_unwind`
[0m[0m[1m[33mwarning[0m[1m:[0m build failed, waiting for other jobs to finish...
Incorrect number of arguments passed to called function!
  call void @_ZN4core9panicking15panic_no_unwind17heb5bd7bc5de639ecE(%"panic::location::Location"* bitcast (<{ i8*, [16 x i8] }>* @364 to %"panic::location::Location"*)) #26
in function _ZN4core9panicking15panic_no_unwind17heb5bd7bc5de639ecE
LLVM ERROR: Broken function found, compilation aborted!
```

```
Incorrect number of arguments passed to called function!
  call void @_ZN4core9panicking15panic_no_unwind17h8631ddd8246c176fE() #16
in function _ZN4core9panicking15panic_no_unwind17h8631ddd8246c176fE
LLVM ERROR: Broken function found, compilation aborted!
```

Locally, I'm not able to reproduce these (perhaps need to enable LLVM asserts or something), but I do see the following in stage 1 std compilation when building with track_caller.

```
error: failed to parse bitcode for LTO module: Invalid record (Producer: 'LLVM14.0.0-rust-1.61.0-nightly' Reader: 'LLVM 14.0.0-rust-1.61.0-nightly')

error: could not compile `core` due to previous error
```

cc @Amanieu @nbdd0121 -- seems plausible that something in https://github.com/rust-lang/rust/pull/92911 is causing this

**Comment by Amanieu** [comment]
The relevant change is [here](https://github.com/rust-lang/rust/pull/92911/files#diff-6eb34d22bb08ffb647a2da4423957658ad0be3f51d9991a172fe5525b36cd8d8L489). This function used to take a caller location but this was removed to reduce code size bloat.

**Comment by Mark-Simulacrum** [comment]
I guess it seems *ok* for an internal function and a lang item, but I'm surprised that we don't have some proper error being emitted if the function is somehow being manually called -- that seems generally hazardous. (Should it have some special ABI declared at the Rust syntax level?)

I also note that the function still *calls* Location::caller: which seems useless or at least confusing without track_caller, right?

```
    let pi = PanicInfo::internal_constructor(Some(&fmt), Location::caller(), false);`
```

**Comment by Amanieu** [comment]
The `panic_no_unwind` function is only expected to be called by the compiler via the lang item. It is never used directly.

> I also note that the function still calls Location::caller: which seems useless or at least confusing without track_caller, right?

That's the only way to construct a `Location` which is required for a `PanicInfo`.

**Comment by nbdd0121** [comment]
Oops. I think I started working on #92911 before panic_no_unwind lands on beta and I forget to add cfg bootstrap after it's promoted into beta.

**Comment by Mark-Simulacrum** [comment]
Even if it's not used directly, we should probably be adding a comment to the function about that, right? It seems like such a function should be documented as being compiler-only.

Anyway, seems OK -- I can adjust my FIXME comment to include this information.
