### ISSUE TITLE
The examples for `ControlFlow::is_break` and `ControlFlow::is_continue` still use `#![feature(control_flow_enum)]` despite being stabilized

### ISSUE THREAD

**Issue by alexschrod** [rust-lang/rust#94349]
The title pretty much describes it. It's a minor thing, but I still think it should be addressed. Other stabilized types with a mix of stable and unstable API do not use `#![feature()]` in in their stable examples.

**Comment by bugadani** [comment]
This was fixed in https://github.com/rust-lang/rust/pull/94283

**Comment by ehuss** [comment]
Yea, the fix is in the latest master (https://doc.rust-lang.org/nightly/std/ops/enum.ControlFlow.html#method.is_break), but will need to ride the trains to the stable docs.
