### ISSUE TITLE
let else doesn't eagerly drop with `_` pattern

### ISSUE THREAD

**Issue by lcnr** [rust-lang/rust#94351]
> The handling and lifetimes of temporaries should be exactly the same with let and with let else; any understanding or intuitions that people have about let should apply to let else.

I think we have a bug then. 😢  (see [playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=97844d29f488fec5bb242e38d8635483))

_Originally posted by @camsteffen in https://github.com/rust-lang/rust/issues/93628#issuecomment-1050037021_

**Comment by lcnr** [comment]
i misunderstood the issue here i think

**Comment by est31** [comment]
Why have you closed it? Drop order is different, and personally I think it would be a good idea to at least try fixing this issue.

**Comment by lcnr** [comment]
the issue is that it doesn't drop eagerly with any pattern, not just `_`. see https://github.com/rust-lang/rust/pull/94012#discussion_r814617249 where I am looking into this

**Comment by est31** [comment]
I'd just have changed the issue title, as it's a bug one way or another.
