### ISSUE TITLE
Confusing borrowck error when multiple borrow errors in different match arms

### ISSUE THREAD

**Issue by ghost** [rust-lang/rust#94374]
In a match statement where the value is moved, only one of the two branches got a compiler error, despite the fact that both should be an error, 

I tried this code:

```rust
fn conversion(mut input: String) {
    match check_last_char(input) {
        'f' => {
            let arg: String = input.pop().unwrap().to_string();
            let fahren: i32 = input.parse::<i32>().unwrap();
            println!("Temperature: {}", convert_to_celcius(fahren));
        },

        'c' => {
            let arg: String = input.pop().unwrap().to_string();
            let celcius: i32 = input.parse::<i32>().unwrap();
            println!("Temperature: {}", convert_to_fahren(celcius));
        }
}
```

I expected to see this happen: 
Writing this code I expected it to work normally, but of course, I am not handling moving the value, so it should be borrowed.
The compiler should yield an error for both branches.

Instead, this happened:
```rust
  --> src\main.rs:42:31
   |
33 | fn conversion(mut input: String) {
   |               --------- move occurs because `input` has type `String`, which does not implement the `Copy` trait
34 |     match check_last_char(input) {
   |                           ----- value moved here
...
42 |             let arg: String = input.pop().unwrap().to_string();
   |                               ^^^^^^^^^^^ value borrowed here after move
```
The second branch is the one containing line 42, but this should also be an error on line 36, which is identical to line 42
### Meta

`rustc --version --verbose`:
```
rustc 1.59.0 (9d1b2106e 2022-02-23)
binary: rustc
commit-hash: 9d1b2106e23b1abd32fce1f17267604a5102f57a
commit-date: 2022-02-23
host: x86_64-pc-windows-msvc
release: 1.59.0
LLVM version: 13.0.0
```

**Comment by ehuss** [comment]
Edited for clarity. "Panic" means something specific that is different from an "error".

**Comment by kckeiks** [comment]
[Looks like](https://github.com/rust-lang/rust/blob/master/compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs#L58) the location of the second arm gets looked at and buffered first before the location of the first arm gets looked at. They ended having the same `moi` and `PlaceRef` so [these](https://github.com/rust-lang/rust/blob/master/compiler/rustc_borrowck/src/diagnostics/conflict_errors.rs#L115) conditions are met and the error of the top arm gets suppressed. I wonder why the bottom arm gets processed first :thinking:

**Comment by estebank** [comment]
[Current output](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=21f403e198e2cc14b4e4d882c42e5382):

```
error[E0382]: borrow of moved value: `input`
 --> src/lib.rs:9:31
  |
6 | fn conversion(mut input: String) {
  |               --------- move occurs because `input` has type `String`, which does not implement the `Copy` trait
7 |     match check_last_char(input) {
  |                           ----- value moved here
8 |         'f' => {
9 |             let arg: String = input.pop().unwrap().to_string();
  |                               ^^^^^ value borrowed here after move
  |
note: consider changing this parameter type in function `check_last_char` to borrow instead if owning the value isn't necessary
 --> src/lib.rs:1:23
  |
1 | fn check_last_char(_: String) -> char {
  |    ---------------    ^^^^^^ this parameter takes ownership of the value
  |    |
  |    in this function
help: consider cloning the value if the performance cost is acceptable
  |
7 |     match check_last_char(input.clone()) {
  |                                ++++++++
```
