### ISSUE TITLE
Strictures on accessing packed fields could be loosened.

### ISSUE THREAD

**Issue by sadmac7000** [rust-lang/rust#94394]
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=0f63bd5f4a76190effcdc079e4e1b4dc

In the above playground we access a field of a packed struct, and are told that it is unsafe to do so due to alignment issues (just a warning for now, but as the warning states, will be an error in the future).

The trouble is that this is an array field, and all we're doing is asking its length, an operation which should actually be safe.

Rust's type system probably sees `len` as just another method taking a reference, but it would be nice to special-case at least this sort of usage to not produce a warning.

**Comment by ChayimFriedman2** [comment]
This is actually Undefined Behavior, since you're not using the array's `len()` method, as it does not exist. You coerce the array to a slice, and then call `<[T]>::len()`. So you take a reference to an unaligned slice, which is UB.

**Comment by nagisa** [comment]
Closing as per the comment above. In general this explanation would also hold true even if `<&[u32; N]>::len` existed; calling it would still create an unaligned reference and that is UB, even if the reference is not manually dereferenced.
