### ISSUE TITLE
x.py rebuilds "bootstrap" a lot

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#94408]
When `x.py` is invoked both by vscode and from the terminal directly, "bootstrap" is rebuilt each time. I think in the end this is due to that line:

https://github.com/rust-lang/rust/blob/10cc7a6d031fd607f594f4c7af113bfaa9a879e9/src/bootstrap/build.rs#L7

Indeed `PATH` is almost certainly different between the two environments. (vscode lives inside a sandbox, it just runs too many untrusted things to be granted access to my files and keys.)

Rebuilding on every `PATH` change seems excessive, is that truly needed?
Cc @jyn514 @Mark-Simulacrum

**Comment by Mark-Simulacrum** [comment]
We could probably move that into this if:

https://github.com/rust-lang/rust/blob/10cc7a6d031fd607f594f4c7af113bfaa9a879e9/src/bootstrap/build.rs#L13-L21

I think that would still be fine and maybe enough to avoid trouble in practice? That if is the reason we added it in the first place.

**Comment by Mark-Simulacrum** [comment]
RUSTC is likely set for you -- this is a build script environment, where it *should* be set to something. IIRC, I had some trouble assuming it was an absolute path in all cases which is why this ad-hoc canonicalization logic was added.

**Comment by bjorn3** [comment]
`RUSTC` is set by x.py: https://github.com/rust-lang/rust/blob/10cc7a6d031fd607f594f4c7af113bfaa9a879e9/src/bootstrap/bootstrap.py#L1001

**Comment by jyn514** [comment]
The fix in https://github.com/rust-lang/rust/pull/94409 seems wrong to me - if bootstrap isn't rerun when `RUSTC` changes, it will still break moving the `build` directory, even if the path is absolute. If you want to fix it properly, you'd probably have to remove this handling from the build script altogether and into rustbuild instead.

**Comment by Mark-Simulacrum** [comment]
I'm not sure I follow your logic -- bootstrap is still rerun when RUSTC changes, just not when it is a relative path. My assumption (perhaps wrong, happy to be corrected) there is that a relative path is only encountered when we're being invoked with a more global rustc (e.g., /usr/bin/rustc, which is in PATH normally).

**Comment by RalfJung** [comment]
Nothing changed about rebuilds when `RUSTC` changes. The PR only changes things about rebuilds when `PATH` changes bust `RUSTC` stays the same.

Put differently: we still emit `rerun-if-env-changed` for every env var we actually read. If we had build script helpers for `var_os` that do the `rerun-if-env-changed` automatically, then they would behave like the post-https://github.com/rust-lang/rust/pull/94409 code.

**Comment by bjorn3** [comment]
It checks for `is_relative()` and not for a lookup.
