### ISSUE TITLE
Tracking Issue for `Copy` trait implementation for zero-length arrays

### ISSUE THREAD

**Issue by JohnScience** [rust-lang/rust#94410]
Feature gate: `#![feature(copy_zero_len_arrs)]`

This is a tracking issue for `Copy` trait implementation for zero-length arrays

### Public API

`Copy` trait implementation for zero-length arrays

### Steps / History

- [ ] Implementation: #...
- [ ] Final comment period (FCP)
- [ ] Stabilization PR

### Unresolved Questions

- None yet.

**Related issue**:  [Zero-length arrays are non-`Copy`](https://github.com/rust-lang/rust/issues/94313)

**Related question on Zulip**: https://rust-lang.zulipchat.com/#narrow/stream/182449-t-compiler.2Fhelp/topic/features.20relying.20on.20other.20features

**Comment by lcnr** [comment]
I don't think it makes sense to have a tracking issue for this. There won't be any work on adding `Copy` to Zero-length arrays until we finish the lang features necessary for this, at which point the added trait impls are instantly stable (as all trait impls) and there will again be nothing to track. It also seems unusual to mention a feature gate that doesn't exist.

Prefer tracking this in #94313, that issue feels discoverable enough to me
