### ISSUE TITLE
Rare case of not properly rounding up thread stack size on Windows

### ISSUE THREAD

**Issue by AronParker** [rust-lang/rust#94454]
The following code states that `stack_size` rounds up to the next 64 kB:

https://github.com/rust-lang/rust/blob/97cde9fe08804a3a5208d77f6870ad7d43f8c9c3/library/std/src/sys/windows/thread.rs#L31-L33

However, if `stack` is any of `0xffff * x + 1` (where x is a non-negative number) it will not properly round up. Additionally, the least significant byte is retained, I doubt that is intended either. Am I missing something? Otherwise I believe it's meant to be `0xffff` instead of `0xfffe` to properly round up.

**Comment by ChrisDenton** [comment]
To be honest, I think this line may as well be removed. As the comment says, the OS will do the rounding up in any case. And as the [MSDN docs say](https://docs.microsoft.com/en-us/windows/win32/procthread/thread-stack-size):

> The operating system rounds up the specified size to the nearest multiple of the system's allocation granularity (typically 64 KB). 

So 64 KB isn't technically guaranteed. I'm not sure there's anything to be gained by doing the rounding up ourselves.
