### ISSUE TITLE
Lint for unused lifetime parameters

### ISSUE THREAD

**Issue by jruderman** [rust-lang/rust#9445]
This code in borrow.rs could trip a warning about having unnecessary lifetime parameters:

    pub fn ref_eq<'a, 'b, T>(thing: &'a T, other: &'b T) -> bool {
        to_uint(thing) == to_uint(other)
    }

**Comment by sanxiyn** [comment]
This is implemented as `needless_lifetimes` in Clippy. @jruderman's example warns. Closing.
