### ISSUE TITLE
Documentation for `addr_of_mut!` is contradictory

### ISSUE THREAD

**Issue by nicholasbishop** [rust-lang/rust#94473]
The documentation for [`addr_of_mut!`](https://doc.rust-lang.org/core/ptr/macro.addr_of_mut.html) says:

> Note, however, that the `expr` in `addr_of_mut!(expr)` is still subject to all the usual rules. In particular, `addr_of_mut!(*ptr::null_mut())` is Undefined Behavior because it dereferences a null pointer.

However, in the example for `Creating a pointer to uninitialized data` it shows this code:

```rust
let f1_ptr = unsafe { ptr::addr_of_mut!((*uninit.as_mut_ptr()).field) };
```

In that example it appears as though `expr` contains a dereference of uninitialized data, which is not normally valid. That seems in conflict with the earlier warning that "all the usual rules" apply.

I'm guessing that maybe dereferencing is allowed in `expr` as long as the pointer isn't dangling?

**Comment by RalfJung** [comment]
> In that example it appears as though expr contains a dereference of uninitialized data, which is not normally valid. 

Why do you think that is the case?
"Dereferencing" (as in, creating a place from) a pointer to uninitialized memory is fine. Only actually *reading* from that place is a problem (it depends on the type, some types allow uninit memory -- like `MaybeUninit<u64>` -- and others do not).

**Comment by nicholasbishop** [comment]
Thanks, I didn't realize that was allowed. Getting a good handle on what is and isn't allowed with pointers in Rust is not always super easy :)

Is there an existing piece of documentation that spells out what all the rules are? It would be great to hyperlink `all the usual rules` to that documentation, or just directly list out what the rules are inline if they are sufficiently short.

**Comment by RalfJung** [comment]
Yeah, it's all kind of complicated. ;)

Basically the core rules are [these ones](https://doc.rust-lang.org/reference/behavior-considered-undefined.html).

**Comment by nicholasbishop** [comment]
Closing this. I think https://github.com/rust-lang/rust/issues/114902 covers it pretty well :)
