### ISSUE TITLE
Standardize whether lib descriptions end with a period

### ISSUE THREAD

**Issue by jruderman** [rust-lang/rust#9447]
http://static.rust-lang.org/doc/master/std/index.html

    str: String manipulation
    task: Task management.

**Comment by frewsxcv** [comment]
*Visiting for triaging*

Still looks pretty inconsistent. Most (if not all) of the descriptions are not sentences, so I would think they should not end in periods

**Comment by bluss** [comment]
Discussion and resolution of this would happen in rust-lang/rfcs#505  I think.

**Comment by steveklabnik** [comment]
Today, these almost all end with a period, and I plan on doing so as I go through the docs.

/cc @rust-lang/libs, is that acceptable? Or should I not put one?

**Comment by aturon** [comment]
@steveklabnik Consistency is most important. I personally like periods in this context, even for sentence fragments.

**Comment by alexcrichton** [comment]
I don't have much of an opinion beyond ensuring we're consistent, whatever's easiest I'm game for :)
