### ISSUE TITLE
regression: abs_diff parameter types

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#94504]
[Crater](https://github.com/rust-lang/rust/issues/94345) picked up this issue in a number of crates:

cc https://github.com/rust-lang/rust/issues/89492 (tracking issue, should probably be closed as feature is stable?)

* https://crater-reports.s3.amazonaws.com/beta-1.60-1/beta-2022-02-22/reg/genevo-0.7.0/log.txt (looks like only tests affected in this crate)

```
[INFO] [stdout] error[E0308]: mismatched types
[INFO] [stdout]  --> src/types/tests.rs:7:32
[INFO] [stdout]   |
[INFO] [stdout] 7 |     expect_that!(&1i8.abs_diff(&0i8), is(equal_to(1i8)));
[INFO] [stdout]   |                                ^^^^ expected `i8`, found `&i8`
[INFO] [stdout]   |
[INFO] [stdout] help: consider removing the borrow
[INFO] [stdout]   |
[INFO] [stdout] 7 -     expect_that!(&1i8.abs_diff(&0i8), is(equal_to(1i8)));
[INFO] [stdout] 7 +     expect_that!(&1i8.abs_diff(0i8), is(equal_to(1i8)));
[INFO] [stdout]   | 
```

**Comment by m-ou-se** [comment]
Discucssed this in the libs meeting. Closing this as expected and acceptable breakage.
