### ISSUE TITLE
Tracking Issue for core_ffi_c

### ISSUE THREAD

**Issue by joshtriplett** [rust-lang/rust#94501]
Feature gate: `#![feature(core_ffi_c)]`

This is a tracking issue for providing the aliases for C types (`c_int`, `c_char`, etc) via `core::ffi`, not just via `std::os::raw`. The ability to interoperate with C code via FFI is not limited to crates using `std`; this allows using these types without `std`.

### Public API

```rust
// core::ffi

pub type c_char = ...;
pub type c_short = ...;
pub type c_ushort = ...;
pub type c_int = ...;
pub type c_uint = ...;
// ...
```

The existing types in `std::os::raw` will become type aliases for the ones in `core::ffi`. This will use type aliases rather than re-exports, to allow the std types to remain stable while the core types are unstable.

This also moves the currently unstable `NonZero` variants and `c_size_t`/`c_ssize_t`/`c_ptrdiff_t` types to `core::ffi`, while leaving them unstable.

### Steps / History

- [x] Implementation: #94503
- [ ] Final comment period (FCP)
- [ ] Stabilization PR

**Comment by bstrie** [comment]
To clarify, was https://github.com/rust-lang/rust/pull/94503 able to avoid insta-stability of the new items? There seems to be some confusion as to whether or not type aliases respect stability markers.

**Comment by joshtriplett** [comment]
@bstrie It appears so: https://doc.rust-lang.org/nightly/core/ffi/type.c_ulong.html shows up as unstable, while https://doc.rust-lang.org/nightly/core/ffi/type.c_ulong.html shows up as stable.

**Comment by madsmtm** [comment]
The [introductory docs for `core`](https://doc.rust-lang.org/1.61.0/core/index.html) currently says:
> this library is platform-agnostic

So that should probably be modified slightly if we go with this change? (Which I am greatly in favour of btw)

**Comment by SimonSapin** [comment]
Should these items also be available in `std::ffi`, in order to keep `std` a superset of `core`? (Though in this case it’s redundant with `std::os::raw`)

**Comment by joshtriplett** [comment]
@SimonSapin They were, but that was reverted in 07ea143f96929ac7f0b7af0f025be48a472273e5 because it caused breakage; we can re-add it as re-exports when we stabilize this.

**Comment by joshtriplett** [comment]
Following up from Zulip:

@rust-lang/libs-api, shall we stabilize the `core::ffi::c_*` types?

@rfcbot merge

**Comment by BurntSushi** [comment]
To be clear, this also includes adding these types to `std::ffi` too?

**Comment by joshtriplett** [comment]
@BurntSushi Yes.

**Comment by joshtriplett** [comment]
Stabilized in https://github.com/rust-lang/rust/pull/98315
