### ISSUE TITLE
regression: ICE adjusting Expr can't compose Pointer(Unsize)

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#94511]
[Crater](https://github.com/rust-lang/rust/issues/94345) picked up this issue:

* https://crater-reports.s3.amazonaws.com/beta-1.60-1/beta-2022-02-22/gh/cpg1111.conspect/log.txt

```
stack backtrace:
[INFO] [stdout] error: internal compiler error: compiler/rustc_typeck/src/check/fn_ctxt/_impl.rs:318:26: while adjusting Expr { hir_id: HirId { owner: DefId(0:181 ~ conspect[9ddb]::manager::{impl#0}::match_ns), local_id: 68 }, kind: Box(Expr { hir_id: HirId { owner: DefId(0:181 ~ conspect[9ddb]::manager::{impl#0}::match_ns), local_id: 67 }, kind: Array([Expr { hir_id: HirId { owner: DefId(0:181 ~ conspect[9ddb]::manager::{impl#0}::match_ns), local_id: 66 }, kind: Path(Resolved(None, Path { span: src/manager/mod.rs:40:41: 40:48 (#0), res: Local(HirId { owner: DefId(0:181 ~ conspect[9ddb]::manager::{impl#0}::match_ns), local_id: 4 }), segments: [PathSegment { ident: process#0, hir_id: Some(HirId { owner: DefId(0:181 ~ conspect[9ddb]::manager::{impl#0}::match_ns), local_id: 65 }), res: Some(Local(HirId { owner: DefId(0:181 ~ conspect[9ddb]::manager::{impl#0}::match_ns), local_id: 4 })), args: None, infer_args: true }] })), span: src/manager/mod.rs:40:41: 40:48 (#0) }]), span: /rustc/0a4f984a87c7ba6c74ec3e78442fec955a419e32/library/alloc/src/macros.rs:50:56: 50:65 (#32) }), span: /rustc/0a4f984a87c7ba6c74ec3e78442fec955a419e32/library/alloc/src/macros.rs:50:52: 50:65 (#32) }, can't compose [Pointer(Unsize) -> _] and [Pointer(Unsize) -> _]
```

**Comment by oli-obk** [comment]
Should probably become a delay span bug, I don't see this happening unless there are other errors involved

**Comment by compiler-errors** [comment]
This is (probably) fixed in #94438. As soon as I fix #94516, we should probably backport both of those together, because there is a potential for more ICEs like this. I can look into making this an MVCE.

**Comment by compiler-errors** [comment]
Minimization is included as test in #94596

**Comment by compiler-errors** [comment]
The fixes for this were beta-backpoorted in #94933, should we close this @Mark-Simulacrum?

**Comment by Mark-Simulacrum** [comment]
I'm rerunning crater and will close if it doesn't appear again.

**Comment by Mark-Simulacrum** [comment]
No type for local variable let -- these look like they could have been caused by the fix perhaps, or at least are a new issue (we can close this and reopen a new issue if so):

* https://crater-reports.s3.amazonaws.com/beta-1.60-2/beta-2022-03-15/gh/comnik.declarative-dataflow/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.60-2/beta-2022-03-15/gh/czipperz.cinterp/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.60-2/beta-2022-03-15/reg/fax-0.2.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.60-2/beta-2022-03-15/reg/seven-0.1.0/log.txt

**Comment by compiler-errors** [comment]
I believe these are fixed in #94636, which was an unrelated bug that may have regressed due to #93118 (or other PRs that were reworking the same method param logic in January). 

@Mark-Simulacrum: Want me to do a bisection to find the blame, or to prove that #94636 was in fact the fix? Seems like all of those crates are very broken for other reasons, so not sure if we want to beta-backport the fix either.

**Comment by Mark-Simulacrum** [comment]
These are just the ones crater picked up, but if there's a simple enough fix that we could backport it seems like we should do so. https://github.com/rust-lang/rust/pull/94636 doesn't look too bad.

I'm not sure a bisection is the right step -- I'd probably suggest building beta + #94636 backported and see if that's still ICEing on these crates, and if not, we just backport #94636. (If it is, then a bisect is likely the right call).

**Comment by compiler-errors** [comment]
Cool, alright, I will just try cherry-picking #94636 then.

**Comment by compiler-errors** [comment]
Ah, so #94596 was backported incorrectly I think. An if-statement was left in causing ICEs. 

I put up a PR with the change in #95093, though I think it may need to get backport-nominated? idk how backports work, lol.

**Comment by Mark-Simulacrum** [comment]
https://github.com/rust-lang/rust/pull/95093 was merged into beta, so I think this is likely fixed, and in any case the only known case had other errors (it was a build-fail -> ICE), so we should be OK for 1.60 here.

**Comment by pietroalbini** [comment]
Can we close this then?

**Comment by compiler-errors** [comment]
I'm just gonna close this then.
