### ISSUE TITLE
ICE in rollup 

### ISSUE THREAD

**Issue by Dylan-DPC** [rust-lang/rust#94523]
ICE encountered in a [rollup](https://github.com/rust-lang/rust/pull/94521#issuecomment-1056918044), will post more details when i trace it further:

**Comment by Urgau** [comment]
I am able to reproduce the issue with this code:
```rust
macro_rules! aa {
    () => {
        fn gg() {
            #[cfg(crossbeam_loom)]
            {
                let _ = val;
                unimplemented!("loom does not support non-atomic atomic ops");
            }
        }
    };
}

fn main() {
    aa!();
}
```
And it's combination of https://github.com/rust-lang/rust/pull/94433 ("introduce" the ICE, preexisting issue) and https://github.com/rust-lang/rust/pull/94298 (trigger the lint which trigger the ICE).

**Comment by Urgau** [comment]
Further reduced to:
```rust
fn main() {
    #[cfg(crossbeam_loom)]
    {}
}
```
