### ISSUE TITLE
arm: record_sp_limit is assuming arm > ARM7

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#9452]
In my attempts to run a `hello world` targetting my ARM chromebook, I am getting an illegal instruction from the first instruction of `record_sp_limit`:

https://github.com/mozilla/rust/blob/9c39992021477740673a5b4982014678743c7fdf/src/rt/arch/arm/record_sp.S#L18

The problem, AFAICT, is that `mrc p15, #0, r3, c13, c0, #3` is too new of an instruction to use on this platform (armv7l GNU/Linux, Arch distribution).

At least, that's my interpretation of the summary provided by the netbsd folks here:
 http://mail-index.netbsd.org/port-arm/2012/02/14/msg001303.html

Commenting out the `mrc` lines in `record_sp_limit` and `get_sp_limit` seem to get the test a bit further (so that it crashes in `pthread_mutex_lock` instead...

**Comment by steveklabnik** [comment]
Given that you un-assigned yourself, @pnkfelix , I'm going to assume things are okay here, or at least, not reproducible. If anyone else is seeing this, please let me know and we'll re-open, thanks!
