### ISSUE TITLE
rustc makes claims about Cargo.toml when there is none in async context

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#94646]
I tried this code:

```rust
#![feature(type_alias_impl_trait)]
#![no_std]

pub trait Tr<'x> {
    type Fut: core::future::Future<Output = ()>;

    fn f() -> Self::Fut;
}

impl<'x> Tr<'x> for () {
    type Fut = impl core::future::Future<Output = ()>;

    fn f() -> Self::Fut {
        async {
            //if false {
            return ();
            //}
            let res: Undef = ();
            res
        }
    }
}
```

When I check this file with `rustc async.rs --crate-type lib`, rust errors
````
  --> async.rs:16:13
   |
14 |         async {
   |         ----- `async` blocks are only allowed in Rust 2018 or later
15 |             //if false {
16 |             return ();
   |             ^^^^^^ expected identifier, found keyword
   |
   = help: set `edition = "2021"` in `Cargo.toml`
   = note: for more on editions, read https://doc.rust-lang.org/edition-guide
````
Which is a bit confusing.
Does it want me to set `edition = 2021` in Cargo.toml (as in "please set edition = 2021...")?
Why does it complain about a Cargo.toml when there isn't one (as I just checked the file directly with rustc x.rs).

For some other examples, the message is even more confusing
````
   = note: to `.await` a `Future`, switch to Rust 2018 or later
   = help: set `edition = "2021"` in `Cargo.toml`
````
because it is not clear if rustc want to say "2021 is set" or "2021 should be set"

**Comment by ehuss** [comment]
It is giving instructions on how to resolve the issue.  It reads fine to me, though maybe a bit terse. Perhaps a few more words could make it clearer.

As for the hint being given when not using cargo, these suggestions should be gated [like this](https://github.com/rust-lang/rust/blob/379e94f5a4aebe7dc2d8742653ca244d92b06f3d/compiler/rustc_incremental/src/persist/fs.rs#L534) to only be shown when using cargo.

**Comment by mati865** [comment]
IMO rustc should tell the user to add `--edition x` command line argument when running without Cargo.

**Comment by ChayimFriedman2** [comment]
Does rustc have a way to know it's being run by Cargo?

**Comment by ehuss** [comment]
[The link](https://github.com/rust-lang/rust/blob/379e94f5a4aebe7dc2d8742653ca244d92b06f3d/compiler/rustc_incremental/src/persist/fs.rs#L534) in the comment above shows how to do it.
