### ISSUE TITLE
Reference to uninitialized memory in `Arc::make_mut`

### ISSUE THREAD

**Issue by Cyborus04** [rust-lang/rust#94707]
In `Arc::make_mut`, `Arc::get_mut_unchecked` is called with an arc created by `Arc::new_uninit` that has not yet been initialized

https://github.com/rust-lang/rust/blob/f5e6d16d000e0aa73833de909de44e8dcc8589ed/library/alloc/src/sync.rs#L1440-L1445

I know some weird stuff not normally allowed can happen in `std`, but this still seems _odd_.

**Comment by PatchMixolydic** [comment]
This seems fine from a casual inspection since `Arc::<T>::new_uninit` returns `Arc<MaybeUninit<T>>`, and `MaybeUninit<T>` is allowed to be uninitialized:

```rust
// this: &mut Arc<T>
let mut arc: Arc<MaybeUninit<T>> = Self::new_uninit();
unsafe {
    // SAFETY: this `Arc` was just created, so we must hold the only reference to it
    let data: &mut MaybeUninit<T> = Arc::get_mut_unchecked(&mut arc);
    // SAFETY: `MaybeUninit<T>` has the same layout as `T`, so we can write a clone
    // of the contents of `this` into it
    (**this).write_clone_into_raw(data.as_mut_ptr());
    // SAFETY: we just wrote a valid value of `T` to `arc` (assuming, of course, that
    // `this` had a valid value to begin with)
    *this = arc.assume_init();
}
```

**Comment by Cyborus04** [comment]
Oh, yes, of course. Forgot about that. Whoops. 🤦🏻‍♂️
