### ISSUE TITLE
`missing_docs` lints external third-party dependencies

### ISSUE THREAD

**Issue by c410-f3r** [rust-lang/rust#94721]
### Cargo.toml

```toml
[dependencies]
num-bigint-dig = "*"

[package]
name = "act-a-fool"
version = "0.1.0"
edition = "2021"
```

### lib.rs

```rust
//! What you gon' do?
```

### Command

RUSTFLAGS="-Dmissing_docs" cargo check

### Error

> --- stderr
> error: missing documentation for the crate
>   |
>   = note: requested on the command line with `-D missing-docs`
> 
> error: aborting due to previous error
> 
> error: missing documentation for the crate
>  --> <anon>:1:1
>   |
> 1 | #![no_std]
>   | ^^^^^^^^^^
>   |
>   = note: requested on the command line with `-D missing-docs`
> 
> error: aborting due to previous error
> 
> warning: autocfg could not probe for `std`
> error: missing documentation for the crate
>  --> <anon>:1:1
>   |
> 1 | pub type Probe = i128;
>   | ^^^^^^^^^^^^^^^^^^^^^^
>   |
>   = note: requested on the command line with `-D missing-docs`
> 
> error: missing documentation for a type alias
>  --> <anon>:1:1
>   |
> 1 | pub type Probe = i128;
>   | ^^^^^^^^^^^^^^^^^^^^^^
> 
> error: aborting due to 2 previous errors

**Comment by c410-f3r** [comment]
IIANM, this erroneous behavior was recently introduced.

Feel free to close the issue if duplicated.

**Comment by jyn514** [comment]
This isn't related to devtools, the lint is part of the compiler itself.

@rustbot label: -T-dev-tools +T-compiler

**Comment by pierwill** [comment]
This does not reproduce for me.

**Comment by c410-f3r** [comment]
I guess it is necessary a more recent compiler version.

Here is mine -> `rustc 1.61.0-nightly (03918badd 2022-03-07)`

**Comment by c410-f3r** [comment]
Closing due to the lack of activeness
