### ISSUE TITLE
macros in `static-assertions` crate no longer compile

### ISSUE THREAD

**Issue by robjtede** [rust-lang/rust#94791]
### Code

I tried this code:

This is a reduction of the macro output from `assert_not_impl_any!` macro of the [static-assertions](https://crates.io/crates/static-assertions) crate.

```rust
const _: fn() = || {
    trait AmbiguousIfImpl<A> {
        fn some_item() {}
    }
    impl<T: ?Sized> AmbiguousIfImpl<()> for T {}

    {
        #[allow(dead_code)]
        struct Invalid;

        impl<T: ?Sized + std::panic::UnwindSafe> AmbiguousIfImpl<Invalid> for T {}
    }
    
    let _ = <std::io::Error as AmbiguousIfImpl<_>>::some_item;
};
```

I expected to see this happen: Successful compilation.

Instead, this happened:

```
error[[E0282]](https://doc.rust-lang.org/beta/error-index.html#E0282): type annotations needed for `fn()`
  [--> src/main.rs:14:48
](https://play.rust-lang.org/?version=beta&mode=debug&edition=2021#)   |
14 |     let _ = <std::io::Error as AmbiguousIfImpl<_>>::some_item;
   |         -                                      ^ cannot infer type
   |         |
   |         consider giving this pattern the explicit type `fn()`, with the type parameters specified

error[[E0283]](https://doc.rust-lang.org/beta/error-index.html#E0283): type annotations needed for `fn()`
  [--> src/main.rs:14:13
](https://play.rust-lang.org/?version=beta&mode=debug&edition=2021#)   |
14 |     let _ = <std::io::Error as AmbiguousIfImpl<_>>::some_item;
   |         -   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot infer type
   |         |
   |         consider giving this pattern the explicit type `fn()`, with the type parameters specified
   |
note: multiple `impl`s satisfying `std::io::Error: AmbiguousIfImpl<_>` found
  [--> src/main.rs:5:5
](https://play.rust-lang.org/?version=beta&mode=debug&edition=2021#)   |
5  |     impl<T: ?Sized> AmbiguousIfImpl<()> for T {}
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
11 |         impl<T: ?Sized + std::panic::UnwindSafe> AmbiguousIfImpl<Invalid> for T {}
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Some errors have detailed explanations: E0282, E0283.
For more information about an error, try `rustc --explain E0282`.
error: could not compile `playground` due to 2 previous errors
```

### Version it worked on

It most recently worked on: `rustc 1.59.0 (9d1b2106e 2022-02-23)`

### Version with regression

`rustc --version --verbose`:
```
rustc 1.60.0-beta.3 (e5effbd0b 2022-03-07)
binary: rustc
commit-hash: e5effbd0b34c9ede216e21d3f60dcbad0b863676
commit-date: 2022-03-07
host: aarch64-apple-darwin
release: 1.60.0-beta.3
LLVM version: 14.0.0
```

### References

- <https://github.com/nvzqz/static-assertions-rs/issues/46>
- <https://play.rust-lang.org/?gist=6c45ced768b44855ed352a5a1b50ae24&mode=debug&edition=2021>

**Comment by compiler-errors** [comment]
Lemme cargo-bisect this..

**Comment by robjtede** [comment]
I'm on a tier 2 platform but here's my bisect:

searched nightlies: from nightly-2021-10-01 to nightly-2022-03-10
regressed nightly: nightly-2022-02-08
searched commit range: https://github.com/rust-lang/rust/compare/f624427f8771c00819684c783bb841bf72095704...734368a200904ef9c21db86c595dc04263c87be0
regressed commit: https://github.com/rust-lang/rust/commit/734368a200904ef9c21db86c595dc04263c87be0

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.1</summary>


Host triple: aarch64-apple-darwin
Reproduce with:
```bash
cargo bisect-rustc --start=2021-01-01
```
</details>

**Comment by compiler-errors** [comment]
Nah you're likely right. My internet died during the bisect so sorry for leaving you hanging, haha. Thanks for doing the bisect.

So the issue seems to be that #87869 made [`std::io::Error` implement `UnwindSafe`](https://doc.rust-lang.org/nightly/std/io/struct.Error.html#impl-UnwindSafe) whereas that's not true on stable.

**Comment by robjtede** [comment]
Okay, that's good then. Weird that there's no reference to it in the PR.

I suppose this is the tricky bit about negative impl testing auto traits.
