### ISSUE TITLE
`1.59` accidentally stabilized dropping `Box<T>`s in `const fn`s

### ISSUE THREAD

**Issue by steffahn** [rust-lang/rust#94804]
```rs
const fn f<T>(_: Box<T>) {}
```
([playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=6349e1b7d3023327e25c2fdebf4924cb))

Note that this works even if `T` implements `Drop` in a non-`const` way. This seems ***hightly*** problematic, especially provided we eventually want to support constructing `Box` at compile time.

Relevant PR: [#91884](https://github.com/rust-lang/rust/pull/91884/files#diff-ee1616b052da71e1a0b80b66544fc07b98debc288e71eeb3e827c7fc3e7e9ecfR1173-R1174)

Of course that impl *claims* to be unstable, but as we all know trait implementations are *never* unstable, unless the trait is unstable. (For ordinary traits, implementations of `const Trait` are thus unstable merely due to the fact that no user can use any such implementations in stable code yet.)

@rustbot label regression-from-stable-to-stable

~~I don’t know what team to tag.~~

The fix should be straightforward: Remove the `const Drop for Box<T, A>` implementation (i.e. revert it to be non-`const`), and add a test.

**Comment by oli-obk** [comment]
cc @rust-lang/wg-const-eval

**Comment by lcnr** [comment]
```rust
#[rustc_const_unstable(feature = "const_box", issue = "92521")]
unsafe impl<#[may_dangle] T: ?Sized, A: Allocator> const Drop for Box<T, A> {
    fn drop(&mut self) {
        // FIXME: Do nothing, drop is currently performed by compiler.
    }
}
```
that impl should be illegal, shouldn't it? I would expect us to need an explicit `T: ~const Drop` here. But also, reverting and maybe even backporting that impl for now seems like the right choice to me

**Comment by RalfJung** [comment]
Actually calling this leads to odd behavior:
```rust
const fn f(_: Box<i32>) {}

pub const C: () = {
    unsafe { f(std::mem::transmute(&0)) };
};
```
```
error: any use of this value will cause an error
    |
   ::: src/lib.rs:3:1
    |
3   | / pub const C: () = {
4   | |     unsafe { f(std::mem::transmute(&0)) };
5   | | };
    | |__-
    |
    = note: `#[deny(const_err)]` on by default
    = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
    = note: for more information, [see issue #71800 <https://github.com/rust-lang/rust/issues/71800>](https://github.com/rust-lang/rust/issues/71800)
```
It doesn't even say what went wrong. I expected an error saying a non-const function was called as part of the `Box` drop glue.
