### ISSUE TITLE
Add a way to parse IP addresses without having to utf8-validate

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#94821]
The only standard way I've found to parse an IP address is [`IpAddr::from_str`](https://doc.rust-lang.org/stable/std/net/enum.IpAddr.html#impl-FromStr). That function immediately converts the string to bytes: https://github.com/rust-lang/rust/blob/5f4e0677190b82e61dc507e3e72caf89da8e5e28/library/std/src/net/parser.rs#L44

It would be great to expose some way (not necessarily `Parser::new`, but something similar) that doesn't require doing unnecessary utf8 validation.

@rustbot label: +T-libs +C-enhancement

**Comment by kckeiks** [comment]
Hi @jyn514, where is the utf8 validation happening? As you said, the string slice gets converted to a byte slice but then it looks like the parser just works with `u8`s which get cast to `char`s at some points in the algorithm

**Comment by jyn514** [comment]
@kckeiks it happens before you ever pass the string to `from_str`: I have a byte sequence, and in order to parse it, I'm forced to call `std::str::from_utf8`.

**Comment by kckeiks** [comment]
`IpAddr` implements `From` for arrays [u8; 4] and [u8; 16]

**Comment by jyn514** [comment]
I don't have an array. I have a dynamically sized &[u8], and I'm not sure whether it's a valid IP address or not.

**Comment by kckeiks** [comment]
Gotcha. If this `&[u8]` is a valid ipv6 address (so it has at least 16 bytes) but the first four bytes make up a valid ipv4 address too then we'd have to make a decision. We could require that the `&[u8]` be of size 4 or 16 then we'd know how to interpret it?

**Comment by jyn514** [comment]
4 and 16 are misleading I think. This is a normal IP address, like "127.0.0.1", it just happens to have come from the network and not be utf8 validated. "127.0.0.1" is 9 bytes, and in general, IP addresses can be variable length.

**Comment by kckeiks** [comment]
If the address, say "127.0.0.1", comes from the network, as inside an IPv4 header, then it must be a 32 bit value, it would be of the form `01111111 00000000 00000000 000000001`. The form you're suggesting would have a byte for each digit including the dots. IP address converted to bytes from a utf8 string representation would have variable length and probably longer than 4 as you said.

**Comment by kckeiks** [comment]
We could add something like this
```rust
impl<'a> TryFrom<&'a [u8]> for IpAddr {
    type Error = AddrParseError;

    fn try_from(b: &'a [u8]) -> Result<IpAddr, Self::Error> {
        Parser::from_bytes(b).parse_with(|p| p.read_ip_addr())
    }
}
```

**Comment by jyn514** [comment]
> this parses IP addresses and assumes that they're utf8 encoded

It doesn't. No part of that code requires `b` to be utf8 encoded - if it contains a non-utf8 byte, then it's not a valid IP address anyway, and it returns `AddrParseError` like normal.

**Comment by kckeiks** [comment]
> It doesn't. No part of that code requires b to be utf8 encoded - if it contains a non-utf8 byte, then it's not a valid IP address anyway, and it returns AddrParseError like normal.

I disagree. The slice of bytes must represent an IP address string in dot notation so the slice of bytes "encodes" this string; some comment should be added to the docs to explain what the slice of bytes is. 

For instance, this slice of bytes is bad and would cause a parse error. It doesn't contain non-utf8 byte but it doesn't encode an IP address string in dot notation.
```
&[127, 0, 0 1]
```
instead it should be

```
&[49, 50, 55, 46, 48, 46, 48, 46, 49] 
```

This is what `as_bytes()` does - we get the underlying bytes encoding the string.
https://github.com/rust-lang/rust/blob/5f4e0677190b82e61dc507e3e72caf89da8e5e28/library/std/src/net/parser.rs#L44

**Comment by jyn514** [comment]
Oh, I see what you mean - you're saying that it should be a byte string, and not an array of the ip numbers. Yes, I agree that's what the code is doing.

**Comment by kckeiks** [comment]
So is this issue for exposing a new way to parse ip byte strings or a slice of the ip numbers? Not sure how to move forward.

Thanks for working with me on this btw.

**Comment by jyn514** [comment]
I don't understand the question. I have `b"127.0.0.1"` and I want to turn it into an IpAddr.

**Comment by kckeiks** [comment]
> This is a normal IP address, like "127.0.0.1", it just happens to have come from the network and not be utf8 validated.

This made me think that you were taking about an array/slice of the numbers of the ip address and not a byte string. 

> I don't understand the question. I have b"127.0.0.1" and I want to turn it into an IpAddr.

I'll add the snippet above and add some comments from this discussion.
