### ISSUE TITLE
rustdoc-json-types: Inconsistant spelling of type/ty

### ISSUE THREAD

**Issue by aDotInTheVoid** [rust-lang/rust#94889]
We mostly use `type_: Type`, 

https://github.com/rust-lang/rust/blob/ed2a69c4a9f3e5535461484af6266681fd7d90d4/src/rustdoc-json-types/lib.rs#L567-L568

But sometimes use `ty`

https://github.com/rust-lang/rust/blob/ed2a69c4a9f3e5535461484af6266681fd7d90d4/src/rustdoc-json-types/lib.rs#L380-L383

https://github.com/rust-lang/rust/blob/ed2a69c4a9f3e5535461484af6266681fd7d90d4/src/rustdoc-json-types/lib.rs#L388-L392

We should choose one and stick to it. `ty` is nicer to type (ha), and generaly consistant with compiller internals, but for those who don't know, `type_` is much more clear, even if more ugly. 

cc @CraftSpider @P1n3appl3 what do you think?

@rustbot modify labels: +A-rustdoc-json +T-rustdoc +C-discussion

**Comment by Enselic** [comment]
I am strongly in favor of `type_`, because
* It is consistent with `for_`, `async_`, `trait_`, etc
* Abbreviations has no place in any public API. Clarity is paramount. (I'm sure you can think of exceptions, but `ty` is not one of them.)
