### ISSUE TITLE
Tracking Issue for `BITS` constant for non-zero integers

### ISSUE THREAD

**Issue by nvzqz** [rust-lang/rust#94881]
Feature gate: `#![feature(nonzero_bits)]`

This is a tracking issue for adding the associated [`BITS`](https://doc.rust-lang.org/stable/std/primitive.usize.html#associatedconstant.BITS) constant to `NonZero{U,I}{8,16,32,64,128,size}`.

This is useful when a type alias refers to either a regular or non-zero integer.

### Public API

Repeated for all `NonZeroX` integers:

```rust
impl NonZeroUsize {
    pub const BITS: u32 = usize::BITS;
}
```

### Steps / History

- [x] Implementation: #93292
- [ ] Final comment period (FCP)
- [ ] Stabilization PR: #101514

### Unresolved Questions

- None yet.

**Comment by leonardo-m** [comment]
In the end I hope we'll have proper general ranged integral types in Rust (as in Ada), that will also replace all the NonZeroXX types :-)
