### ISSUE TITLE
rustdoc: Generate the documentation for one module on one page instead of several pages

### ISSUE THREAD

**Issue by kud1ing** [rust-lang/rust#9489]
Browsing the documentation for functions/structs `foo`, `bar` and `baz` currently involves a lot of clicks (click on `foo`, go back, click on `bar`, go back, click on `baz`).

Other language communities provide one documentation per module with "jumpable" links/anchors. Examples
  * D: http://dlang.org/phobos/std_base64.html
  * Go: http://golang.org/pkg/compress/zlib/

**Comment by alexcrichton** [comment]
This is quite an old bug at this point, and I believe that rustdoc's design has changed pretty radically in the interim, so I'm going to close for now.
