### ISSUE TITLE
Compiler generates suboptimal code when array is iterated (works fine with slice).

### ISSUE THREAD

**Issue by VorfeedCanal** [rust-lang/rust#94917]
Couldn't find if that was reported yet.

This is example [from reddit](https://www.reddit.com/r/rust/comments/tajbgl/why_does_the_assembly_for_these_look_different/):

This produces suboptimal results:
~~~
    for name in name_arr {
        print!("{}", name.get_name());
    }
~~~

while this works as expected:
~~~
    for name in &name_arr {
        print!("{}", name.get_name());
    }
~~~

Godbolt reference with comparison: https://godbolt.org/z/1T6G3s7Gz

**Comment by nikic** [comment]
Not going to add a separate test for this, I think this is effectively covered by https://github.com/rust-lang/rust/issues/101082.
