### ISSUE TITLE
Misidentified conflicting blanket impls for generic subtraits

### ISSUE THREAD

**Issue by djkoloski** [rust-lang/rust#94940]
I tried this code:

```rust
// lib.rs
pub trait LowerBase {}
pub trait LowerDerived<X>: LowerBase {}

pub trait UpperBase {}
pub trait UpperDerived<X>: UpperBase {}

impl<T: LowerBase> UpperBase for T {}
impl<T: LowerDerived<X>, X> UpperDerived<X> for T {}

// main.rs
use lib::{UpperBase, UpperDerived};

pub struct Foo;

impl UpperBase for Foo {}
impl<X> UpperDerived<X> for Foo {}

fn main() {}
```

Where `lib.rs` and `main.rs` are in different crates. This gives the following compiler error:

```
error[E0119]: conflicting implementations of trait `lib::UpperDerived<_>` for type `Foo`
 --> bin/src/main.rs:6:1
  |
6 | impl<X> UpperDerived<X> for Foo {}
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = note: conflicting implementation in crate `lib`:
          - impl<T, X> UpperDerived<X> for T
            where T: LowerDerived<X>;
  = note: downstream crates may implement trait `lib::LowerDerived<_>` for type `Foo`
```

The `UpperBase` impl compiles fine when it's alone. The `UpperDerived<X>` impl should be allowed because:

1. `impl UpperBase for Foo` prevents `impl LowerBase for Foo` since that would cause the blanket impls to conflict.
2. `LowerDerived<X>` cannot be implemented for `Foo` since `Foo` cannot implement `LowerBase`.
3. The blanket `impl<T: LowerDerived<X>, X> UpperDerived<X> for Foo` cannot apply because `Foo` cannot implement `LowerDerived<X>`.

It's also worth noting that making `Foo` private results in the same error message even though downstream crates cannot implement any traits for `Foo`. This is a separate issue from what I am encountering though.

This is really unintuitive behavior and completely prevents generic traits from composing. This is preventing some forward progress for unsized types in [rkyv](https://github.com/rkyv/rkyv) and blocking ergonomics/performance improvements for [protoss](https://github.com/djkoloski/protoss).

### Meta

`rustc --version --verbose`:
```
rustc 1.59.0 (9d1b2106e 2022-02-23)
binary: rustc
commit-hash: 9d1b2106e23b1abd32fce1f17267604a5102f57a
commit-date: 2022-02-23
host: x86_64-apple-darwin
release: 1.59.0
LLVM version: 13.0.0
```

**Comment by lazytype** [comment]
To add another data point, I also ran into this when refactoring some code to use `allocator_api` which broke my blanket impls on traits that I added `A: Allocator` to.

**Comment by lazytype** [comment]
A workaround that seems to work is to change the type parameter to be an associated type

**Comment by compiler-errors** [comment]
This is fixed with the new trait solver.
