### ISSUE TITLE
Tracking Issue for `CStr::from_bytes_until_nul`

### ISSUE THREAD

**Issue by ericseppanen** [rust-lang/rust#95027]
Feature gate: `#![feature(cstr_from_bytes_until_nul)]`

This is a tracking issue for adding member fn to `CStr` that convert from a byte slice, without the caller needing to know where the nul byte is located within the slice.

This is intended for use in FFI calls, where a foreign function wrote a string into a Rust-allocated buffer. The existing member fns fall short in this case:
- `CStr::from_ptr` is unsafe and may read past the end of the buffer if no nul byte is found.
- `CStr::from_bytes_with_nul` only works if there is exactly one nul byte at the end of the slice.

The proposed new member fn (tentatively named `from_bytes_until_nul`) is easier and can be used safely on any byte slice.

### Public API

```rust
// std::ffi:

pub struct FromBytesUntilNulError(...);

impl CStr {
    pub fn from_bytes_until_nul(bytes: &[u8]) -> Result<&CStr, FromBytesUntilNulError>;
}
```

### Steps / History

- [x] CStr Implementation: #94984
- [ ] Final comment period (FCP): https://github.com/rust-lang/rust/pull/107429#issuecomment-1407535002
- [ ] Stabilization PR: https://github.com/rust-lang/rust/pull/107429

### Unresolved Questions

- `CString` API needs to be designed.
- With CStr eventually revised to just be a pointer, rather than (ptr, len) pair, then this becomes a little less good. See https://github.com/rust-lang/rust/pull/94984#issuecomment-1070754281 for details.

**Comment by Stargateur** [comment]
> CStr::from_bytes_with_nul only works if there is exactly one nul byte at the end of the slice.

That a better doc that real doc

> ensuring that the byte slice is nul-terminated and does not contain any interior nul bytes.

**Comment by jimblandy** [comment]
We could have avoided the `unsafe` block that led to gfx-rs/wgpu#3076 by using this function. I hope it gets stabilized.

**Comment by tgross35** [comment]
Would it be possible to separately feature gate `cstring_from_bytes_until_nul`, instead of both CStr and CString being under `cstr_from_bytes_until_nul`? I ask because this `CStr` version is straightforward, has been around for almost a year, is very useful for FFI, and is already mentioned in the forums quite often - imho, probably ready for FCP.

However, the `CString` version hasn't even merged yet. I just don't think it's worth delaying the CStr stabilization for another year or so while waiting on `CString::from_vec_until_nul` to get merged & mature a while.

**Comment by tgross35** [comment]
Hey @ericseppanen I hope you don't mind, but I've opened stabilization PR #107429 without any `CString` implementation. If you have any concerns just let me know and I can close / adjust it as needed

**Comment by ericseppanen** [comment]
I'm not sure which issue to comment on, but I'm happy with whatever others want to do. I was never sure why the `CString` bit (#96186) stalled, but it's at least partially my own fault as I was too shy to beg for more reviews.

I'll try to find time to rebase that commit and poke the reviewers again.

**Comment by tgross35** [comment]
Okiedoke, as long as you don't have any qualms about the cstr part going stable. Sorry to leapfrog you and start the stabilization, but I wasn't sure if you were still active on github.

Yeah, things have a tendency to stall a bit when they're close to the merge phase and there isn't really any open debate or strong need to drive discussion. Not your fault!

**Comment by m-ou-se** [comment]
> Would it be possible to separately feature gate `cstring_from_bytes_until_nul`, instead of both CStr and CString being under `cstr_from_bytes_until_nul`?

Good idea. I've edited this tracking issue so it only covers CStr::from_bytes_until_nul.

**Comment by tgross35** [comment]
Since `cstr_from_bytes_until_nul` has been stabilized (#107429 1.69), I think this issue could be closed. @ericseppanen do you perhaps want to start a new tracking issue for cstring_from_bytes_until_nul?

**Comment by ericseppanen** [comment]
Sure, we can close this. I'm not sure if a new tracking issue is needed, since the `CString::from_vec_until_nul` PR (#96186) is not making progress. If someone wants to bring it back to life, feel free to persuade the reviewers.

**Comment by tgross35** [comment]
Fwiw that PR is labeled waiting on author, you can comment `@rustbot ready` to change it to waiting on review

**Comment by aswild** [comment]
Hi @ericseppanen,
Was it intentional to add `FromBytesUntilNulError` only in `core::ffi` and not re-export it in `std::ffi`?

I'm used to everything from core (and alloc) to be re-exported under the same name in std, so it was a bit of a surprise to see an error message when trying to use `std::ffi::{CStr, FromBytesUntilNulError}`.

**Comment by tgross35** [comment]
@aswild I don't think anybody would object to a reexport - are you interested in making a PR for that change?

It would need to go through FCP but I think it's small enough that that could happen on the PR.

**Comment by ericseppanen** [comment]
> Hi @ericseppanen, Was it intentional to add `FromBytesUntilNulError` only in `core::ffi` and not re-export it in `std::ffi`?

Not intentional; probably just me not knowing I was supposed to do it.
