### ISSUE TITLE
Changing file on latest rustdoc has text slide for 1s

### ISSUE THREAD

**Issue by Ten0** [rust-lang/rust#95043]
# Reproduction

Load https://doc.rust-lang.org/stable/src/core/alloc/layout.rs.html#436
Open files panel on the left.
Refresh page.

You'll notice everytime you load the page, the file list slides again. So we now have to wait 1s for it to stop sliding before starting to read the file we clicked on.

# Note

Btw, I'd rather this never slides at all. This is time loss anyway. Could there be an option to disable this?

**Comment by Ten0** [comment]
Yes absolutely

**Comment by GuillaumeGomez** [comment]
I think the idea behind the animation is to allow the reader to see that it's not hovering the code. As for the setting, not sure.

What do you think @jsha?

**Comment by jsha** [comment]
I agree with @Ten0, we should remove the animation. It bothers me as well, I just haven't found the time to file an issue / PR about it. :-) I don't think we should add a setting.

**Comment by GuillaumeGomez** [comment]
Ok, I'll remove the animation then. Will send a PR tomorrow. For the setting, it's that we current save the state of the sidebar. Should I remove it as well?

**Comment by Ten0** [comment]
> For the setting, it's that we keep the current save the state of the sidebar. Should I remove it as well?

My idea of new setting was rather "should there be an animation or should it be static" (so no need for a new setting if we remove the animation altogether)

It seems reasonable to me to always keep the current state of the sidebar, as we currently do :)

**Comment by GuillaumeGomez** [comment]
Oh ok. Well, that cleared things up. I'll just remove the animation then.
