### ISSUE TITLE
i686 gnu windows build crashes with `memory allocation` error

### ISSUE THREAD

**Issue by qarmin** [rust-lang/rust#95054]
When compiling with `rust-1.59.0-i686-pc-windows-gnu`(https://static.rust-lang.org/dist/rust-1.59.0-i686-pc-windows-gnu.msi) this project - [WinProject.zip](https://github.com/rust-lang/rust/files/8291525/WinProject.zip) I have crash
```
memory allocation of 276824080 bytes failed
error: could not compile `windows`
...
...
 (exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)
```

compilation with 64 bit windows rust binaries works just fine.

It takes 4GB from 8GB, so still 2GB of memory is free when crash happens.

Problem also I can reproduce with Wine 7.4 devel, so looks that this is problem with Rust, not Windows

### Meta

`rustc --version --verbose`:
```
rustc 1.59.0 (9d1b2106e 2022-02-23)

```

**Comment by mati865** [comment]
> It takes 4GB from 8GB, so still 2GB of memory is free when crash happens.

The problem is how much memory 32-bit process can allocate since their pointers are 4 byte long (Rust's `u32` type).

You can workaround this limitation by cross-compilling to 32-bit from 64-bit system.

**Comment by qarmin** [comment]
How can I do that?
I already use 64 bit OS, so for me it looks that I already use cross compilation

**Comment by mati865** [comment]
> How can I do that?

It's pretty easy with `rustup`: https://rust-lang.github.io/rustup/cross-compilation.html
In that case you'd install `x86_64-pc-windows-gnu` host toolchain and add `i686-pc-windows-gnu` target.

I have no idea how it works with standalone installers that you have used.

>  I already use 64 bit OS, so for me it looks that I already use cross compilation

x86_64 systems can run both i686 and x86_64 binaries and you have used `i686` target to build `i686` binaries which is normal compilation.

**Comment by qarmin** [comment]
Looks that I misunderstand what exactly cross compilation means.

Now app compile properly(I think), but there is problem with linking, but this is probably a problem caused by missing software
