### ISSUE TITLE
ui/unsafe/union.rs test has UB

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rust#95075]
https://github.com/rust-lang/rust/blob/691d1c1e12602c57237e9ccddac406ebd0c54082/src/test/ui/unsafe/union.rs

Running it in miri gives the following error:

```
error: Undefined Behavior: enum value has invalid tag: 0x07
  --> example/union.rs:49:15
   |
49 |         match foo {
   |               ^^^ enum value has invalid tag: 0x07
   |
   = help: this indicates a bug in the program: it performed an invalid operation, and caused Undefined Behavior
   = help: see https://doc.rust-lang.org/nightly/reference/behavior-considered-undefined.html for further information
           
   = note: inside `main` at example/union.rs:49:15

note: some details are omitted, run with `MIRIFLAGS=-Zmiri-backtrace=full` for a verbose backtrace
```

I found this issue because cg_clif aborts matching on an invalid discriminant.

cc @Smittyvb as you introduced this test.

**Comment by Smittyvb** [comment]
@rustbot claim

I forgot that the test actually got executed, I'll make a PR to move the UB parts to a `check-pass` test.
