### ISSUE TITLE
E0726 is not documented on https://doc.rust-lang.org/error-index.html

### ISSUE THREAD

**Issue by SamJBarney** [rust-lang/rust#95076]
Ran into this error for the first time while fooling around with lifetimes. Went to the error index to check it out, but it isn't there.

**Comment by Urgau** [comment]
`E0726` is available in the nightly output: https://doc.rust-lang.org/nightly/error-index.html#E0726
This most certainly means that the error code has only been added/documented in the current nightly and not yet in beta and stable. It will be automatically added when it reached the beta and stable channel.

**Comment by GuillaumeGomez** [comment]
Closing then.
