### ISSUE TITLE
std docs list all NEON intrinsics as unstable

### ISSUE THREAD

**Issue by tmandry** [rust-lang/rust#95086]
std docs are assumed to be the source of truth but claim that all neon intrinsics (including the recently stabilized ones on arm64) are still unstable, which is very confusing*.

From https://github.com/rust-lang/rust/issues/90972#issuecomment-1050801478 and https://github.com/rust-lang/rust/issues/90972#issuecomment-1050808733:

> The intrinsics that are shared with the 32-bit ARM targets are basically partially stable; stable on AArch64, unstable on 32-bit. Rustdoc doesn't seem to be able to handle that.

![Screen Shot 2022-03-18 at 12 09 09 PM](https://user-images.githubusercontent.com/2280544/159068792-59e65615-5068-4c11-988a-223b64e8b2c9.png)

Even though these intrinsics are exposed behind a `aarch64` module, they are internally shared with other arm platforms, hence the need to have target-dependent stability attributes on them.

(*) Source: I know multiple people who were confused, myself included!

cc #90972

**Comment by ehuss** [comment]
This is tracked on the stdarch side as https://github.com/rust-lang/stdarch/issues/1268, which has some more detail on the situation.

**Comment by Dylan-DPC** [comment]
Closing this as it is tracked by the issue linked above.
