### ISSUE TITLE
Experiment computing lint_levels by definition

### ISSUE THREAD

**Issue by cjgillot** [rust-lang/rust#95094]
The `lint_levels` query traverses the whole crate to assign a set of lint and allowances to each `HirId`.

However, most incremental modifications to a crate don't involve many items. Computing `lint_levels` independently for each definition will help reduce the effect of recomputing it. The objective is to avoid lowering of some definitions once https://github.com/rust-lang/rust/pull/88186 is merged.

Steps: not defined yet. Please make contact on Zulip to discuss and define them.

**Comment by fbrunodr** [comment]
I have not contributed yet to rust, but I am willing to help if you want!
