### ISSUE TITLE
Using `cargo run` with bootstrap uses the host rustfmt, not nightly rustfmt

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#95136]
https://github.com/rust-lang/rust/blob/c7ce69faf2a7ea16c15d922985ca27ba70da30ee/src/bootstrap/config.rs#L1095-L1106

The proper fix is to check if we're going through the `cargo run` entrypoint instead of x.py, and if so, download rustfmt from the nightly toolchain listed in `src/stage0.json`: https://github.com/rust-lang/rust/blob/c7ce69faf2a7ea16c15d922985ca27ba70da30ee/src/stage0.json#L8-L11

Ideally we would eventually be able to move this into rustup, but that requires not only for rustup to add and release this feature, but also for all contributors to start using it. It shouldn't be too much extra work for bootstrap to do it itself in the meantime.

cc https://github.com/rust-lang/rust/issues/94829, https://github.com/rust-lang/rust/pull/94806#issuecomment-1073257368, https://github.com/rust-lang/rust/pull/94830#issuecomment-1066807203

**Comment by bjorn3** [comment]
You can use `rustup run <toolchain> rustfmt`. Or set the `RUSTUP_TOOLCHAIN` env var.

**Comment by jyn514** [comment]
Ah, interesting idea. Right now `rustup component add --toolchain nightly-2022-02-23 rustfmt` gives an error, but @kinnison suggests that rustup could support `--profile none` which would avoid installing an unused toolchain.

**Comment by jyn514** [comment]
I do wonder to what extent we can depend on rustup vs. supporting a pre-installed host toolchain. @cuviper is probably not running `x.py fmt --check` a whole lot while building from source, but it does make me slightly uncomfortable to have commands we know will fail if you use `cargo run` without rustup.

cc @Mark-Simulacrum

**Comment by Mark-Simulacrum** [comment]
I would prefer to avoid a dependency on rustup specifically being available for any of our commands; I suspect that manually downloading the tarball for rustfmt would be better.

In general my operating assumption is that we can reasonably expect rustup for "get me a beta toolchain", but should not look for anything more than that. (And of course, all that really means is that the bootstrap toolchain must be provided somehow - perhaps from the previous version in a distro, for example).

**Comment by cuviper** [comment]
You're right that I don't need `fmt` for distro builds -- and note that it currently isn't supported at all for stable/beta branches:

```
$ ./x.py fmt --check
Updating only changed submodules
  Submodules updated in 0.00 seconds
Building rustbuild
    Finished dev [unoptimized] target(s) in 0.06s
./x.py fmt is not supported on this channel
Build completed unsuccessfully in 0:00:00
```

**Comment by jyn514** [comment]
Only half-related to this issue, but I would *love* for `cargo fmt` to work out of the box. It looks like `cargo fmt -- --unstable-options --skip-children` already works - I guess we don't use that so we can use @the8472's optimizations to make rustfmt faster? Could we possibly move those to cargo instead of special-casing x.py?

**Comment by Mark-Simulacrum** [comment]
My recollection is that we enable unstable rustfmt features in rustfmt.toml and such that mean we couldn't do cargo +beta fmt anyway (and RUSTC_BOOTSTRAP isn't supported by rustfmt).

**Comment by jyn514** [comment]
Ah right, people would still have to use two separate toolchains for `cargo build` vs `cargo fmt` (unless we get rustup to support this in rust-toolchain.toml somehow). Probably not worth investing time into, then.
