### ISSUE TITLE
`cargo run` doesn't rebuild bootstrap binaries

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#95141]
Currently, `cargo run` has a big footgun: if you modify `src/bootstrap/bin/rustc.rs` (or rustdoc.rs), it won't be rebuilt until you manually run `cargo build --bins`. I tried avoiding this in https://github.com/rust-lang/rust/pull/94828 by running that automatically in bootstrap, but it discards various linker arguments and environment variables that prevent people from configuring the build.

A better solution is to introduce a binary that dispatches to different main functions, like rustup. If called as `bootstrap` it would run the main builder; if called as `rustc` or `rustdoc` it would run the logic currently in `rustc.rs` / `rustdoc.rs`; if called by any other name it should give a hard error.

cc https://github.com/rust-lang/rust/pull/94828#issuecomment-1066969753, https://github.com/rust-lang/rust/issues/94829

I am happy to help mentor this work.

@rustbot label: +A-rustbuild +C-enhancement +E-mentor +E-help-wanted

**Comment by bstrie** [comment]
Coming from https://github.com/rust-lang/rust/pull/94828, does the solution to this involve leveraging artifact dependencies somehow? I'd be very impressed if that worked.

**Comment by jyn514** [comment]
No, artifact dependencies are still unstable, so bootstrap can't use them yet.

**Comment by jyn514** [comment]
(of course, if anyone is interested in stabilizing artifact dependencies, this would still be a fun experiment to try out ...)

**Comment by bstrie** [comment]
Ah, I was hopeful that something like this could help to exercise artifact dependencies to get them to stable sooner. :) Is the problem that artifact dependencies are unstable, or is the problem just that bootstrap is using a version of Rust that doesn't contain support for them? I'm not generally aware of unstable features being forbidden in the compiler.

**Comment by jyn514** [comment]
Not in the compiler, but in bootstrap itself: https://github.com/rust-lang/rust/pull/92260#issuecomment-1038394945
(let's please move further discussion about stable vs unstable to zulip)

**Comment by jyn514** [comment]
I am planning to add a shim binary that should make this unnecessary (see https://rust-lang.zulipchat.com/#narrow/stream/122651-general/topic/bootstrap.20user.20survey/near/283897117). The shim will use a pre-downloaded bootstrap from CI, which makes the approach here unnecessary. Until I implement downloadable bootstrap, I'll just live with the broken caching locally.
