### ISSUE TITLE
Windows 8 is returning ERROR_INVALID_HANDLE instead of NotFound when opening a missing file

### ISSUE THREAD

**Issue by ehuss** [rust-lang/rust#95154]
I tried this code:

```rust
use std::fs::File;
use std::io::ErrorKind;

fn main() {
    let err = File::open("foo").unwrap_err();
    assert_eq!(err.kind(), ErrorKind::NotFound);
}
```

I expected to see this happen: Runs without error.

Instead, this happened: On Windows 8, it fails with error:

```
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `Uncategorized`,
 right: `NotFound`', src\main.rs:6:5
```

This seems to have started with #94572, cc @sunfishcode.

This is causing `cargo new` to fail on Windows 8, cc https://github.com/rust-lang/cargo/issues/10464

This may also be responsible for rustc's incremental support to complain, though this doesn't always happen:

```
warning: could not load dep-graph from `\\?\C:\Temp\empty\target\debug\incremental\empty-2s9a0rpxj1834\s-g83mc5algm-1qawwn9-working\dep-graph.bin`: The handle is invalid. (os error 6)
```

### Meta

`rustc --version --verbose`:
```
rustc 1.61.0-nightly (8d60bf427 2022-03-19)
binary: rustc
commit-hash: 8d60bf427a4b055f464122062e76b3ec34d4f8ba
commit-date: 2022-03-19
host: x86_64-pc-windows-msvc
release: 1.61.0-nightly
LLVM version: 14.0.0
```

**Comment by sunfishcode** [comment]
I unfortunately don't have a Windows 8 box to test this on, but looking at the code, I have a theory which would explain the behavior you're seeing here, and I've now posted a fix for it here: https://github.com/rust-lang/rust/pull/95158.

**Comment by AndreKR** [comment]
This also happens on Windows 7 by the way.

**Comment by Mingun** [comment]
Confirming this on Windows 7, Windows 10 and 11 seems unaffected

**Comment by sunfishcode** [comment]
@AndreKR @Mingun @ehuss #95158 has now made it to the latest nightly Rust; would you mind testing whether it fixes this issue on Windows 7 and Windows 8?

**Comment by Mingun** [comment]
Yes, after updating to rustc 1.61.0-nightly (5f3700105 2022-03-22) (from rustc 1.61.0-nightly (58f11791a 2022-03-17)) issue seems fixed on Windows 7!

Previously:
```console
> cargo fmt --check
Неверный дескриптор. (os error 6)
```
Fixed nightly:
```console
> cargo fmt --check
Diff in \\?\H:\Projects\quick-xml\src\de\map.rs at line 198:
...skipped...
```

**Comment by AndreKR** [comment]
I can confirm that as well.

**Comment by apiraino** [comment]
Assigning priority as discussed in the [Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2395154.20Windows.208.20is.20returning.20ERROR_INVALID_HANDLE.20instead.20.E2.80.A6) of the Prioritization Working Group.

@rustbot label -I-prioritize +P-high

**Comment by ehuss** [comment]
Confirmed this is resolved for Windows 8. Thanks!
