### ISSUE TITLE
Compiler optimization suggestion - `Iter<String>.collect::<Vec<String>>().join("")`

### ISSUE THREAD

**Issue by yoav-lavi** [rust-lang/rust#95165]
Hi,

I've opened this issue for `clippy`: https://github.com/rust-lang/rust-clippy/issues/8570 wherein a `collect::<Vec<String>>().join("")` operation on an `Iter<String>` can be expressed as `collect::<String>()` which is more performant.

I wanted to put this here as well as I think this may be something that can also be optimized by the compiler (by replacing the former with the latter) since the output should always be equivalent and the latter option is more performant.

See cases of this happening in the wild [here (GitHub CS Beta)](https://cs.github.com/?scopeName=All+repos&scope=&q=.collect%3A%3A%3CVec%3CString%3E%3E%28%29.join%28%22%22%29%3B) or [here (Sourcegraph)](https://sourcegraph.com/search?q=context:global+.collect::%3CVec%3CString%3E%3E%28%29.join%28%22%22%29&patternType=literal)

I'm learning Rust so please let me know if I'm missing something, thank you!

**Comment by blyxyas** [comment]
A lint for clippy is already merged (rust-lang/rust-clippy#8579) I think this issue can be closed as has had no updates for 9 months and will probably not be re-implemented in the Rust compiler, as it is already in Clippy.

**Comment by yoav-lavi** [comment]
For anyone seeing this in the future - Please take a look at the comments here: https://github.com/rust-lang/rust-clippy/pull/8579
This change being more performant depends on the target arch
