### ISSUE TITLE
[ER] Array/Vec parsing?

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust#95168]
Both the Haskell and D language standard library allows the roundtrip of printing - parsing of lists/arrays:

Haskell:

```haskell
Prelude> let xs = read $ ("[" ++ "10,20" ++ "]") :: [Int]
Prelude> xs
[10,20]
```

In D language:

```d
void main() {
    import std.stdio: writeln;
    import std.conv: to;
    const txt = "[10, 20, 30]";
    const data = txt.to!(uint[]);
    writeln(data); // Prints: [10, 20, 30]
}
```

A similar functionality could be added to the Rust stdlib:

```rust
fn main() {
    let txt1 = "[1, 2, 3]";
    let v1 = txt1.parse::<Vec<u8>>().unwrap(); // To vec
    let a1 = txt1.parse::<[u8; 3]>().unwrap(); // to array
    let txt2 = "10,20";
    let a2 = format!("[{txt2}]").parse::<[u32; 2]>().unwrap();
}
```

**Comment by zirconium-n** [comment]
IIRC, Rust tends not to add things without a "standard way" to stdlib. Use `miniserde` if you need this functionality.

**Comment by workingjubilee** [comment]
Correct. We probably will not be adding this.

Please do not post feature requests to the issue tracker. It is hard to determine when it is appropriate to close them, and issues are in general opened in order to be closed someday.
