### ISSUE TITLE
io::Error is UnwindSafe, but only on 64-bit platforms

### ISSUE THREAD

**Issue by xfix** [rust-lang/rust#95203]
### Code

I tried this code:

```rust
use std::io;
use std::panic::UnwindSafe;

pub fn is_unwind_safe<T: UnwindSafe>() {}

fn main() {
    is_unwind_safe::<io::Error>();
}
```

I expected to see this happen: either it to compile or not compile.

Instead, this happened: it compiled but only on 64-bit platforms.

### Version it worked on

It most recently worked on: Rust 1.59 (where it did not compile no matter what platform)

### Version with regression

`rustc --version --verbose`:
```
rustc 1.60.0-beta.5 (6ee5a408a 2022-03-18)
binary: rustc
commit-hash: 6ee5a408a3bbc76598637d50450165917f8756bb
commit-date: 2022-03-18
host: x86_64-unknown-linux-gnu
release: 1.60.0-beta.5
LLVM version: 14.0.0
```

### Backtrace

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

@rustbot modify labels: +regression-from-stable-to-beta -regression-untriaged

**Comment by compiler-errors** [comment]
Not sure what the best approach is here. 

We could just `impl !UnwindSafe for io::Error` to restore consistency from #87869 which made `io::Error` auto-implement `UnwindSafe`.

cc #94791

**Comment by apiraino** [comment]
@xfix which non-64bit platform does reproduce the issue?

**Comment by xfix** [comment]
> @xfix which non-64bit platform does reproduce the issue (not sure if this question matters a lot)?

All platforms that have `std` and `target_pointer_width = "64"`, see https://github.com/rust-lang/rust/blob/547369d3d881a9eb1de0d3e368f9a59aa7c648b0/library/std/src/io/error.rs#L4.

**Comment by thomcc** [comment]
Ah, `repr_bitpacked::Repr` should have `PhantomData<ErrorData<Box<Custom>>>` or something along those lines. I'll get a fix for this up later this evening or tomorrow.

**Comment by thomcc** [comment]
Hmm, this should probably not be closed, unless prioritization will still see it if it is closed.

**Comment by compiler-errors** [comment]
Yeah, for backports I think the issue stays open until the backport is landed or decided against. Reopened for tracking.
