### ISSUE TITLE
On MacOS, bootstrap requires both `python` and `python3`

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#95204]
python: https://github.com/rust-lang/rust/blob/beb480d908f091e7c42c866e13641f26b2ee230b/src/bootstrap/sanity.rs#L100-L106
python3: https://github.com/rust-lang/rust/blob/beb480d908f091e7c42c866e13641f26b2ee230b/src/bootstrap/test.rs#L1382-L1386
It sounds like python3 is strictly required for LLDB, so we should move this check from test.rs to `builder.python()`, which will only require `python3` instead of both commands.

cc @walther

@rustbot label: +E-easy +E-mentor +E-help-wanted +A-rustbuild +A-contributor-roadblock

**Comment by Mark-Simulacrum** [comment]
But not everyone will want to run lldb, right? We only mention /usr/bin/python3 there, we don't actually run it unless lldb tests are run, which is pretty rare.

This may still be an OK change, of course.

**Comment by jyn514** [comment]
Sure - but in that case, we hardly need python at all, only for rustdoc tests, and it seems ok to use the system python.

**Comment by pierwill** [comment]
I would actually support requiring Python 3 in any case.

**Comment by jyn514** [comment]
@pierwill let's please keep discussion about 2 vs 3 in https://github.com/rust-lang/rust/issues/71818 thread and not relitigate it on each issue that mentions python.

**Comment by AlecGoncharow** [comment]
If I understand the issue here correctly, just moving the check from test.rs to the `builder.python()` doesn't entirely remove the issue of needing the `python` name defined on MacOS given the call to `cmd_finder.must_have("python")` in sanity.rs. To resolve this should the check in sanity.rs include a MacOS specific check for `/usr/bin/python3` or an additional check for `python3`?

**Comment by AlecGoncharow** [comment]
About to raise a PR, but is it even necessary to perform any check in `builder.python()` if we are always forcing `/usr/bin/python3` in sanity.rs? Are there instances where `sanity::check` won't be called before `CompileTest::run`?

Also first time using `x.py`, what would be the correct test to run here?

**Comment by jyn514** [comment]
> Is it even necessary to perform any check in builder.python() if we are always forcing /usr/bin/python3 in sanity.rs?

I don't think it's necessary to check in both places, no, you can return /usr/bin/python3 unconditionally in builder.python(). Whether you can remove the check in sanity.rs is a question for @Mark-Simulacrum - I think probably yes, since you can still run the build without python, but it doesn't necessarily need to go in the same change switching to /bin/python3 consistently.

> Also first time using x.py, what would be the correct test to run here?

Basically everything runs the check in sanity.rs, but I think it's only relevant when BOOTSTRAP_PYTHON is unset, so probably you'll need `cargo run check` to make sure the check executes. If you want to check the version of python used works, you can run `cargo run test --stage 1 src/test/rustdoc`.

**Comment by Mark-Simulacrum** [comment]
If we can rely on /usr/bin/python3 always existing on macOS there's no need to check for it, but I would expect that the code in sanity.rs isn't platform-specific and so should continue to look for python in a variety of ways (likely the same ways across all platforms).

It looks like python is currently used for two separate things: lldb tests, and docck. The latter likely works with python 2 and python 3, or at least, so it's likely that we need to leave the discovery and configuration in place. Certainly on e.g. Windows /usr/bin/python3 is not expected to exist, I believe.
