### ISSUE TITLE
`:path` allow-follow-list should probably include `(`

### ISSUE THREAD

**Issue by WaffleLapkin** [rust-lang/rust#95278]
This code:
```rust
macro_rules! a {
    ($p:path ()) => {};
}
```
Currently (1.61.0-nightly (2022-03-19 8d60bf427a4b055f4641)) fails with this error:
```text
error: `$p:path` is followed by `(`, which is not allowed for `path` fragments
 --> src/lib.rs:2:14
2 |     ($p:path ()) => {};
  |              ^ not allowed after `path` fragments
  |
  = note: allowed there are: `{`, `[`, `=>`, `,`, `>`, `=`, `:`, `;`, `|`, `as` or `where`
```

I don't think this is right, I don't think that `(` can ever be a part of a path and thus bring ambiguities here.

**Comment by petrochenkov** [comment]
>I don't think that `(` can ever be a part of a path

`Fn()` is  a counter-example.
```rust
macro_rules! a {
    ($p:path) => {}
}

fn main() {
    a!(Fn()); // OK
}
```

**Comment by WaffleLapkin** [comment]
Ugh. Nevermind then.

As a workaround `$($p:ident)::*` can be used (if you don't need to support `Fn()`)
