### ISSUE TITLE
Account for `{}` when array literal `[]` was meant

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#95289]
[When incorrectly using `{}` for an array literal when `[]` should have been used with a single element](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=0758571f8d7719ad9f0ce8c5bb03ceb0), we should provide a structured suggestion as we already do when [encountering multiple literals](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=e6c48161639e901f46e069efd3caef70).

**Comment by compiler-errors** [comment]
seems easy enough, @rustbot claim
