### ISSUE TITLE
std::process::Command can't echo environment variables

### ISSUE THREAD

**Issue by vervaekejonathan** [rust-lang/rust#95400]
I tried this code:

```rust
use std::process::Command;
...
    let s = Command::new("echo")
        .arg("$123")
        .output()
        .expect("command failed");
    println!("{}", String::from_utf8_lossy(&s.stdout));
```

I expected to see this happen: 
Print the content of the $123 environment variable

Instead, this happened:
It literally prints $123

### Meta
`rustc --version --verbose`:
```
rustc --version --verbose
rustc 1.61.0-nightly (63b8f01bb 2022-03-24)
binary: rustc
commit-hash: 63b8f01bb5ca277e7df8d7efe094ed4244c1790c
commit-date: 2022-03-24
host: x86_64-unknown-linux-gnu
release: 1.61.0-nightly
LLVM version: 14.0.0
```

**Comment by crumblingstatue** [comment]
It is the shell that resolves environment variables. You're not using a shell here, just directly executing a command. This is behaving as expected.

**Comment by jfrimmel** [comment]
Indeed, this is the expected behavior. This can be circumvented by actually using a shell, e.g. on POSIX:
```rust
Command::new("sh").arg("-c").arg("echo $123").output().unwrap();
```

**Comment by wwylele** [comment]
I did a quick check on the doc for [arg](https://doc.rust-lang.org/std/process/struct.Command.html#method.arg)
>Note that the argument is not passed through a shell, but given literally to the program. This means that shell syntax like quotes, escaped characters, word splitting, glob patterns, substitution, etc. have no effect.

I guess we can expand "substitution" into "variable substitution" to make it more clear.

**Comment by Milo123459** [comment]
so is this just a documentation change?

@rustbot claim
