### ISSUE TITLE
Compiler cannot resolve associated type

### ISSUE THREAD

**Issue by tema3210** [rust-lang/rust#95419]
I tried this code: [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=e47d51902e6604dab3af2cdb87e50f05)

I expected to see this happen: compile fine

Instead, this happened: ambiguous associated type

Happens on stable rust 1.59.0.

**Comment by zirconium-n** [comment]
While there's no ambiguation now, the might be future ambiguations. This grammar this trying to prevent the future ones.
