### ISSUE TITLE
E0515 "cannot return value referencing temporary value" no solution given though

### ISSUE THREAD

**Issue by elibroftw** [rust-lang/rust#95416]
Given the following code: 

```rust
use tokio::sync::{Mutex, MutexGuard};
use std::sync::Arc;
use lazy_static::lazy_static;
use std::collections::HashMap;

lazy_static! {
    static ref mutexMap: Mutex<HashMap<String, Arc<Mutex<()>> >> = Mutex::new(HashMap::new());
}

async fn acquire_guard(_dir: &str) -> MutexGuard<'_, ()> {
    let mut mapGuard. = mutexMap.lock().await;
    if !mapGuard.contains_key(_dir) {
        let mutex = Arc::new(Mutex::new(()));
        mapGuard.insert(_dir.to_string(), mutex);
    }
    let guard = mapGuard.get(_dir).unwrap().lock().await;
    guard
}

#[tokio::main]
async fn main() {
    let n = "test";
    let guard = acquire_guard((n);
}


```

The current output is:

```rs
error[E0515]: cannot return value referencing temporary value
  --> src/main.rs:18:5
   |
17 |     let guard = mapGuard.to_owned().get(_dir).unwrap().lock().await;
   |                         ----------------------- temporary value created here
18 |     guard
   |     ^^^^^ returns a value referencing data owned by the current function

For more information about this error, try `rustc --explain E0515`.
```

Ideally the output should look like:

Both temporary value and local value are used interchangeably. Before this error, I was getting the error with the same code but using "local" instead of temporary. Stick to one please or make the connection in the explanation.

The last message should tell the user that they can not only learn more but can solve the error. Except it doesn't help at all.
I followed the "solution" but got this error to being with. I have no idea why the ^^^ is underlying an already created temporary value.
I have no idea how that variable is reference by the return value.

**Comment by zirconium-n** [comment]
"local value" means a value that binds to a variable.  "temporary value" means a value that is a intermediate result of an expression.

`Mutex::lock` creates a `MutexGuard` that references the `Mutex`.

In your original code, `guard` references `mapGuard` which is a local value.

After you added `to_owned()` (which clones the `HashMap`), `guard` references the cloned `HashMap` which is a temporary value.

In this specific case, you should clone and return the `Arc`, then call `lock` outside the function.

**Comment by zirconium-n** [comment]
Sidenote: Please ask and answer questions about Rust on the user forum.

**Comment by elibroftw** [comment]
I solved the problem but just saying that there should be better documentation. Maybe its a documentation issue with tokio too.

**Comment by Exiled1** [comment]
How did you solve this error by the way?

**Comment by elibroftw** [comment]
I believe you need to call lock in the same scope as whatever requires the guard rather than locking in this function. 
To do this, you need to use Arc::clone on the mutex before returning it.
It's possible 
```rs
use tokio::sync::Mutex;
use std::sync::Arc;
use lazy_static::lazy_static;
use std::collections::HashMap;

lazy_static! {
    static ref MUTEX_MAP: Mutex<HashMap<String, Arc<Mutex<()>> >> = Mutex::new(HashMap::new());
}

async fn acquire_guard(_dir: &str) -> Arc<Mutex<()>> {
    let mut mapGuard = MUTEX_MAP.lock().await;
    if !mapGuard.contains_key(_dir) {
        let mutex = Arc::new(Mutex::new(()));
        mapGuard.insert(_dir.to_string(), mutex);
    }
    Arc::clone(mapGuard.get(_dir).unwrap())
}

#[tokio::main]
async fn main() {
    let n = "test";
    let mutex = acquire_guard(n).await;
    {
        let _guard = mutex.lock().await;
    } // guard is dropped
}
```

**Comment by GavinRay97** [comment]
I ran into this same problem today:
```rs
impl HeapFile {
    fn get_page(&mut self, page_num: PageNum) -> &mut [u8] {
        let page_loc = (self.db_id, page_num);
        let page = BUFFER_POOL.lock().unwrap().get_page(page_loc);
        page
    }
    // ...
}
```

```rs
error[E0515]: cannot return value referencing temporary value
   --> src/main.rs:338:9
    |
337 |         let page = BUFFER_POOL.lock().unwrap().get_page(page_loc);
    |                    --------------------------- temporary value created here
338 |         page
    |         ^^^^ returns a value referencing data owned by the current function
```
