### ISSUE TITLE
#[thread_local] on i686 windows msvc causes suspicious crash in production

### ISSUE THREAD

**Issue by csmoe** [rust-lang/rust#95429]
As the title says, the crash disappeared once we set the `has-thread-local = false` on i686-pc-windows-msvc target spec.
Could we disable it? cc @nagisa 
(the codebase is really huge, cannot generate a small test case)

`#[thread_local]` was enabled in https://github.com/rust-lang/rust/pull/92042

**Comment by nagisa** [comment]
cc @ChrisDenton

**Comment by ChrisDenton** [comment]
Disabling it for i686 sounds reasonable if it's still causing issues. It is unfortunate we don't have a test case though.

I'll make a quick PR.

**Comment by nagisa** [comment]
It would still be great if we could have a regression test case to put into our test suite, otherwise some time down the line somebody might end up re-enabling TLS on the affected platform again.

**Comment by thomcc** [comment]
I wonder if the crash here is an example of the issue https://github.com/rust-lang/rust/pull/101368 works around (or hopes to, anyway).

**Comment by Zoxc** [comment]
@csmoe Would you be able to reproduce this bug?
