### ISSUE TITLE
Panics report the column at the beginning of an indexing expression, which is ambiguous

### ISSUE THREAD

**Issue by umanwizard** [rust-lang/rust#95442]
I tried this code:

```rust
#[derive(Default)]
struct S {
    pub v: Vec<Vec<usize>>,
}

fn main() {
    let mut s = S::default();
    s.v.push(vec![]);
    s.v[0][0];
}
```

I expected to see this happen: The panic message should make it possible to tell whether the first indexing expression, or the second, was out of bounds.

Instead, this happened: `thread 'main' panicked at 'index out of bounds: the len is 0 but the index is 0', src/main.rs:9:5`

Note that column 5 is reported, which is the location of the `s` character in `s.v[0][0]`. So it's impossible to tell which indexing is at fault.

### Meta

`rustc --version --verbose`:
```
rustc 1.59.0 (9d1b2106e 2022-02-23)
binary: rustc
commit-hash: 9d1b2106e23b1abd32fce1f17267604a5102f57a
commit-date: 2022-02-23
host: x86_64-unknown-linux-gnu
release: 1.59.0
LLVM version: 13.0.0
```

**Comment by umanwizard** [comment]
Perhaps this is considered a feature request and not a bug; I have no strong opinion there.

**Comment by fmease** [comment]
This is now fixed on stable and nightly.

```rs
#[derive(Default)]
struct S {
    pub v: Vec<Vec<usize>>,
}

fn main() {
    let mut s = S::default();
    s.v.push(vec![]);
    s.v[0][0];
//        ^ :9:11
}
```

results in

```
thread 'main' panicked at src/main.rs:9:11:
index out of bounds: the len is 0 but the index is 0
```

and

```rs
#[derive(Default)]
struct S {
    pub v: Vec<Vec<usize>>,
}

fn main() {
    let mut s = S::default();
    //s.v.push(vec![]);
    s.v[0][0];
//     ^ :9:8
}
```

results in

```
thread 'main' panicked at src/main.rs:9:8:
index out of bounds: the len is 0 but the index is 0
```

Closing as fixed :)
