### ISSUE TITLE
Improve floating point documentation about platform guarantees 

### ISSUE THREAD

**Issue by golddranks** [rust-lang/rust#95468]
As summarized in https://github.com/rust-lang/rust/issues/72599#issuecomment-1081701414, floating points have both some 1) platform-specific behaviour 2) surprising behaviour because of LLVM guarantees (or lack of thereof). Issue https://github.com/rust-lang/rust/issues/73328 seems to be about improving the documentation about the LLVM-induced stuff, but mention about  platform-specific behaviour also seems to be missing in some documentation items, so add some explanations/disclaimers about that.

**Comment by golddranks** [comment]
I'm working on this currently.

**Comment by golddranks** [comment]
Also attempts to document https://github.com/rust-lang/rust/issues/71355

**Comment by RalfJung** [comment]
What is this issue still tracking?  Some improvements landed in https://github.com/rust-lang/rust/pull/95483. The issue description as it is is too vague to be actionable.

**Comment by golddranks** [comment]
Agreed! Closing this.
