### ISSUE TITLE
Confusing source location for "missing fragment specifier" 

### ISSUE THREAD

**Issue by mikebenfield** [rust-lang/rust#95463]
Here's some code incorrectly defining a macro, because it's missing a fragment specifier. [Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=c232b9f82d5d5879aad00624a29fb90b)

```rust
macro_rules! m {
    ($x [$y: ident]) => {}
}
```

Here's the error message rustc gives me:

```
error: missing fragment specifier
 [--> src/lib.rs:2:9
](https://play.rust-lang.org/#)  |
2 |     ($x [$y: ident]) => {}
  |         ^^^^^^^^^^^
  |
```

It's potentially confusing that the error points to the source *after* the name with the missing fragment specifier. Especially in a complicated macro, it would be better if it pointed to the item which was actually missing the fragment specifier.

**Comment by tgross35** [comment]
Some more context at https://github.com/rust-lang/rust/issues/129077. @srleyva I'll unassign you since it has been a few years.
