### ISSUE TITLE
repeat expression do not honor lt bounds of copy

### ISSUE THREAD

**Issue by lcnr** [rust-lang/rust#95477]
```rust
#![feature(nll)]

#[derive(Clone)]
struct Foo<'a>(fn(&'a ()) -> &'a ());

impl Copy for Foo<'static> {}

fn mk_foo<'a>() -> Foo<'a> {
    println!("mk_foo");
    Foo(|x| x)
}

fn foo<'a>() -> [Foo<'a>; 100] {
    [mk_foo::<'a>(); 100]
}

fn main() {
    foo();
}
```
this compiles both with and without `feature(nll)`. Note that `mk_foo` creates a value of type `Foo<'a>` which may not be copied.

Moving `mk_foo::<'a>()` into a local errors as expected:
```rust
#![feature(nll)]

#[derive(Clone)]
struct Foo<'a>(fn(&'a ()) -> &'a ());

impl Copy for Foo<'static> {}

fn mk_foo<'a>() -> Foo<'a> {
    println!("mk_foo");
    Foo(|x| x)
}

fn foo<'a>() -> [Foo<'a>; 100] {
    let x = mk_foo::<'a>();
    [x; 100]
}
```
this results in
```
error: lifetime may not live long enough
  --> src/main.rs:15:6
   |
13 | fn foo<'a>() -> [Foo<'a>; 100] {
   |        -- lifetime `'a` defined here
14 |     let x = mk_foo::<'a>();
15 |     [x; 100]
   |      ^ copying this value requires that `'a` must outlive `'static`
```

**Comment by lcnr** [comment]
Ah no, we just decide whether to copy or move things depending on whether they implement `Copy` while ignoring regions. That kinda sucks :/

**Comment by RalfJung** [comment]
I think that is a general issue with `Copy` treatment also for other parts of MIR generation. But elsewhere we actually double-check and make sure to error if we later notice there was a mistake. Looks like for array repeat expressions we don't do that...

> here's a version which duplicates Foo<'a> without it being copy

This looks exactly the same to me as the original example?

**Comment by RalfJung** [comment]
Cc @oli-obk @nikomatsakis  who might know more about MIR generation and `Copy`. I agree this is a soundness issue...

**Comment by lcnr** [comment]
> This looks exactly the same to me as the original example?

The original code requires the creation of a new `Foo` while that example copies an existing one. My concern was that we somehow treat the function as if it were const, which isn't the case.

**Comment by nikomatsakis** [comment]
Yes, our general strategy for Copy is:

* Check (without respect to lifetimes) whether the type implements Copy;
* If so, generate a Copy;
* Enforce in MIR that the lifetime bounds hold.

If I had my druthers, we would have required that Copy impls were [always applicable](http://smallcultfollowing.com/babysteps/blog/2018/02/09/maximally-minimal-specialization-always-applicable-impls/), but we did not, and so we opted for the above compromise (I could dredge up the issue, but it hardly matters). We do generally consider it a soundness issue to fail to enforce those rules.

(That said, I've been working on a revised type system that I think might make the whole "modulo-regions" scheme far less necessary or important... but that's for another time.)

**Comment by RalfJung** [comment]
> Enforce in MIR that the lifetime bounds hold.

Yeah, that seems to not be working in some cases.

**Comment by apiraino** [comment]
Assigning priority as discussed in the [Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2395477.20repeat.20expression.20do.20not.20honor.20lt.20bounds.20of.20copy) of the Prioritization Working Group.

@rustbot label -I-prioritize +P-low
