### ISSUE TITLE
Cannot infer type with a default const parameter

### ISSUE THREAD

**Issue by ejpcmac** [rust-lang/rust#95486]
I tried this code:

```rust
#[derive(Default)]
pub struct TestStruct<const N: usize = 0>;

pub fn main() {
    let _ = TestStruct::default();
}
```

I expected this to compile properly, since without specifying the const parameter of the `TestStruct<N>` type, it should be inferred as `TestStruct<0>`.

Instead, this happened:

```
error[E0282]: type annotations needed for `TestStruct<N>`
 --> test.rs:5:13
  |
5 |     let _ = TestStruct::default();
  |         -   ^^^^^^^^^^^^^^^^^^^^^ cannot infer type for struct `TestStruct<{_: usize}>`
  |         |
  |         consider giving this pattern a type

error: aborting due to previous error

For more information about this error, try `rustc --explain E0282`.
```

If I replace my code with this, it compiles properly:

```rust
#[derive(Default)]
pub struct TestStruct<const N: usize = 0>;

pub fn main() {
    // Note the absence of the N parameter.
    let _: TestStruct = TestStruct::default();
}
```

### Meta

`rustc --version --verbose`:
```
rustc 1.59.0 (9d1b2106e 2022-02-23)
binary: rustc
commit-hash: 9d1b2106e23b1abd32fce1f17267604a5102f57a
commit-date: 2022-02-23
host: x86_64-unknown-linux-gnu
release: 1.59.0
LLVM version: 13.0.0
```

Also tested with:

`rustc +nightly --version --verbose`:
```
rustc 1.61.0-nightly (9c06e1ba4 2022-03-29)
binary: rustc
commit-hash: 9c06e1ba47e1077725a950e0b5d1870a89c8b536
commit-date: 2022-03-29
host: x86_64-unknown-linux-gnu
release: 1.61.0-nightly
LLVM version: 14.0.0
```

**Comment by frank-king** [comment]
I'm afraid this is by design, since there is a similar ui test
https://github.com/rust-lang/rust/blob/1b7c3bcef9dc88e65c4914887071e432436a0b04/src/test/ui/const-generics/defaults/doesnt_infer.rs#L1-L13

@rustbot release-assignment
@rustbot label: +A-const-generics +F-const_generics_defaults +F-const_generics +T-compiler
cc @rust-lang/project-const-generics

**Comment by ejpcmac** [comment]
Oh :( And what would be the rationale behind this decision? Because I feel this is kind a redundant to have to provide a type without the defaults. It does not look like usual Rust code.

**Comment by ejpcmac** [comment]
Oh, apparently this is due to a tricky design issue: https://github.com/rust-lang/rust/issues/27336. As it is known, I’m closing this one.

**Comment by wyfo** [comment]
As I've just posted in #27336, you can,also use `let _ = <TestStruct>::default()`.
