### ISSUE TITLE
 std::ops::Deref's documentation broken on doc.rust-lang.org

### ISSUE THREAD

**Issue by JanBeh** [rust-lang/rust#95480]
I noticed that documentation of `std::ops::Deref` is broken here:

https://doc.rust-lang.org/std/ops/trait.Deref.html

After the line

```
impl<T: ?Sized> Deref for RwLockWriteGuard<'_, T> [src]
```

all subsequent `[src]` links are missing. And there is also a line reading

```
impl<B: ?Sized + ToOwned> Deref for Cow<'_, B> where
    B::Owned: ~constBorrow<B>, 
```

which seems wrong (to me).

I'm unsure if this is a matter of `rustfmt` or `doc.rust-lang.org`.

**Comment by compiler-errors** [comment]
The `~constBorrow` typo is fixed on nightly -- the duplicated Deref impl entries idk about though.

**Comment by GuillaumeGomez** [comment]
It's now fixed on beta as well. For the missing `source` links, it's not really a bug but more like a current rustdoc limitation. The issue about this is https://github.com/rust-lang/rust/issues/86632. Closing this issue then.
