### ISSUE TITLE
[strict provenance] Close The Gap Between AtomicUsize and AtomicPtr

### ISSUE THREAD

**Issue by Gankra** [rust-lang/rust#95492]
This issue is part of the Strict Provenance Experiment - https://github.com/rust-lang/rust/issues/95228

As of this writing, [AtomicUsize](https://doc.rust-lang.org/std/sync/atomic/struct.AtomicUsize.html) has many more operations than [AtomicPtr](https://doc.rust-lang.org/std/sync/atomic/struct.AtomicPtr.html), like fetch_add, which is a *problem* if we want people to conform to strict provenance and admit when pointers are pointers.

All the cases I found [in my initial pass](https://github.com/rust-lang/rust/pull/95241) over std and rustc seemed to work fine with CAS operations, so closing the gap is seemingly only needed for the wider ecosystem. For instance, parking_lot does many Cute Tricks with fetch_and and fetch_sub:

https://github.com/Amanieu/parking_lot/blob/035ecafda05588191e03874c1f21cd2b638e6149/core/src/word_lock.rs#L274

See also @jrtc27's [comments on what CHERI does](https://github.com/rust-lang/rust/issues/95228#issuecomment-1083405125)

Morally, most atomic operations can be defined in terms of wrapping_offset, so I think it should be fine to support these operations. However it is *interesting* as to whether they should be defined to operate on "just the address" (as you would expect of wrapping_offset) or if they are allowed to "interact" with the raw bit representation and therefore things that are "not" addresses (e.g. the CHERI metadata). At worst we can say "we can't stop you, but if you do, you will be sad", but it would be good to know if we can do "better".

(For those unaware, a pointer ("capability") on CHERI is 128-bit, but the address-space is ~64-bit. The pointer is a complicated compressed thing that does lots of Tricks to pack in *at least* an entire slice (so two more logically-64-bit addresses!) into there. If you do Sufficiently Bad things the hardware will mark the memory as ~corrupt and fault you if you try to use the pointer to read/write.)

**Comment by Gankra** [comment]
(marked as both T-libs and T-compiler because I don't know if this is "just" a matter of using existing intrinsics or if the compiler needs to do some more work to do this)

**Comment by Lokathor** [comment]
small note about the footnote: andnot is usually `(!a) & b`

**Comment by thomcc** [comment]
The answer to these questions are in https://rust-lang.zulipchat.com/#narrow/stream/136281-t-lang.2Fwg-unsafe-code-guidelines/topic/Questions.20about.20extending.20strict.20prov.2E.20to.20AtomicPtr, it seems.

**Comment by RalfJung** [comment]
> parking_lot_core wants to use fetch_and for a bit-clear operation

That just clears a single bit -- at least for Miri there is no issue here.

No idea how to make any sense of any of this on CHERI though. Cc @jrtc27
What we would *want* is that this is equivalent to atomically doing [cheri_address_set](https://www.cl.cam.ac.uk/techreports/UCAM-CL-TR-947.pdf#page=28) with the old address bit-combined with the operand.

**Comment by jrtc27** [comment]
> > parking_lot_core wants to use fetch_and for a bit-clear operation
> 
> That just clears a single bit -- at least for Miri there is no issue here.
> 
> No idea how to make any sense of any of this on CHERI though. Cc @jrtc27 What we would _want_ is that this is equivalent to atomically doing [cheri_address_set](https://www.cl.cam.ac.uk/techreports/UCAM-CL-TR-947.pdf#page=28) with the old address bit-combined with the operand.

That's what you get on CHERI

**Comment by thomcc** [comment]
I think I'm probably going to have to ignore cheri for this work, since we don't really have a pointer-sized integer except for usize. That said, it doesn't need to stabilize with urgency.

**Comment by workingjubilee** [comment]
If we adopt a more "usize is size_t or ptraddr_t" model then it would be fine using usize as the operand. If we don't, then uhhh, a lot of things become much more "funny" already. An appropriate `// if xyz { FIXME:` note should suffice.

**Comment by RalfJung** [comment]
> That's what you get on CHERI

So I can take a 64bit integer and atomically bit-and it with a pointer (that has 128bit), meaning "bit-and this with the 64bit address part of the pointer please"? Other people say CHERI atomics are pointer-sized so I am confused now.

**Comment by RalfJung** [comment]
In Rust syntax, we need an operation that atomically does
```rust
// ptr is `&AtomicPtr`, mask is `usize`
let v = *ptr;
*ptr = v.map_addr(|addr| addr & mask):
```

**Comment by jrtc27** [comment]
> In Rust syntax, we need an operation that atomically does
> 
> ```rust
> // ptr is `&AtomicPtr`, mask is `usize`
> let v = *ptr;
> *ptr = v.map_addr(|addr| addr & mask):
> ```

That's exactly what we give you, semantically

**Comment by Diggsey** [comment]
> pub fn fetch_or(&self, a: *mut T) -> *mut T;

I think this signature is a problem, because it's not clear what provenance the resulting pointer has. Does the resulting provenance come from `self` or does the provenance come from `a`?

Strictly speaking we'd need two variants of each binary atomic operation: one which takes provenance from the left, and one which takes provenance from the right.

**Comment by RalfJung** [comment]
Indeed, the signatures will all be changed to take `usize` as the second operand.
