### ISSUE TITLE
`x test --stage 0 --doc compiler/rustc_lint_defs` fails

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#95515]
I found this originally while testing out https://github.com/rust-lang/rust/pull/95445, but it's also present on master.

I tried this code: `x test --stage 0 --doc compiler/rustc_lint_defs`
I expected to see this happen: Tests pass, like they do for `--stage 1`.

Instead, this happened:
```
   Doc-tests rustc_lint_defs

running 106 tests
ii..........i..i.....i......i.ii.i.......i......iii.....................i.F......i..i.............i. 100/106
......
failures:

---- src/builtin.rs - builtin::UNFULFILLED_LINT_EXPECTATIONS (line 503) stdout ----
error: cannot find attribute `expect` in this scope
 --> src/builtin.rs:506:3
  |
5 | #[expect(unused_variables)]
  |   ^^^^^^

error: aborting due to previous error

Couldn't compile the test.

failures:
    src/builtin.rs - builtin::UNFULFILLED_LINT_EXPECTATIONS (line 503)

test result: FAILED. 88 passed; 1 failed; 17 ignored; 0 measured; 0 filtered out; finished in 2.42s
```

It's unclear to me whether this is a bug in bootstrap / rustdoc / rustc_lint_defs, or whether doc-tests for the compiler just don't support --stage 0? If so I could add a warning the same way compiletest warns: https://github.com/rust-lang/rust/blob/05d22212e89588e7c443cc6b9bc0e4e02fdfbc8d/src/bootstrap/test.rs#L1261-L1269
cc @Mark-Simulacrum in case you have ideas.

### Meta
HEAD is 11909e3588319235e28e99294e17cca11db1d7e2.

@rustbot label +A-rustbuild

**Comment by ehuss** [comment]
The issue is that tests may use new syntax and features without needing `#[cfg(bootstrap)]`. For example, `expect` support was recently added in #87835 which isn't in beta.

I personally would just add a warning or error that tests may not work with stage0.

**Comment by jyn514** [comment]
This is fixed since the beta bump; closing since it sounds like doctests aren't supported on stage 0.
