### ISSUE TITLE
in nightly, std::thread_local! uses `unreachable!` where it needs to say `$crate::unreachable!`

### ISSUE THREAD

**Issue by elidupree** [rust-lang/rust#95533]
Commit https://github.com/rust-lang/rust/commit/36c904594ee0d3a311f720827025c293d071a006 introduced two lines that say `unreachable!()`, which breaks this code ([playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=e74876a2b23f9f747f54ee1be7a680f4)):
```rust
#![no_implicit_prelude]
::std::thread_local! {static Q: () = (); }
```

I believe they need to say `$crate::unreachable!` instead.

Also, if there isn't one already, we should create a regression test for this - #![no_implicit_prelude] seems easy to break by accident.

**Comment by niluxv** [comment]
Fixed by #95557, now merged into master so this can be closed I think.
