### ISSUE TITLE
Reference pattern matching on tuples behaves unexpectedly

### ISSUE THREAD

**Issue by jain98** [rust-lang/rust#95615]
I'm seeing what looks like unsound behavior while using pattern matching on a tuple reference, where the tuple itself contains references - `&(&1, &2)` or `&(&"Hello".to_owned(), &"World".to_owned())`. 

Below is a minimal reproducible example:

```rust
   // (1)
    let items = (&1, &2);
    let (a, b) = &items;

    let (a, b) = &items; // a & b are &i32
    let _: &i32 = a;  // Works
    let _:  i32 = *a; // Errors. expected `i32`, found `&i32` 
    let _:  i32 = **a; // Works. Is this suggesting a is &&i32?
    
    // (2)
    let mut map = HashMap::<String, String>::new();
    map.insert("Hello".to_owned(), "World".to_owned());
    map
        .iter()
        .find(|(k, v)| {
            let _: &String = k; // Works
            // let _: String = k; // Errors. expected `String`, found `&&String`
            let _: String = **k; // Works. Is this suggesting k is &&String?
            true
        })
        .unwrap();
```
I ran into the error while using code like `(2)`, where I was using the `find` method on a map of `<String, String>` while iterating over the map using `iter()`. The iterator's `Item` is `(&String, &String)` and when using it with the find method I was using a pattern as shown above - `|(k, v)|`. I was expecting k and v to be `&&String`, which seems true based on the above example. 

However, when I tried to match using a pattern like `|(&k, &v)|`, I got the below error -

```
error[E0507]: cannot move out of a shared reference
 --> src/main.rs:8:16
  |
8 |         .find(|(&k, &v)| k == "Hello")
  |                ^^-^^^-^
  |                  |   |
  |                  |   ...and here
  |                  data moved here
  |
  = note: move occurs because these variables have types that don't implement the `Copy` trait

```
Given that `k` and `v` are `&&String`, me using the pattern `(&k, &v)` should move a string reference into k and v and not the actual strings themselves. So how am I moving out of a shared reference?

**Comment by ehuss** [comment]
There are a few things to explain why this is happening:

In your first example, `a` is `&&i32`.  Part of [match ergonomics](https://rust-lang.github.io/rfcs/2005-match-ergonomics.html), the pattern has an implicit `ref` which creates a reference to a reference.

The reason `let _: &i32 = a;` works is that a `let` statement with an explicit type will perform [implicit coercion](https://doc.rust-lang.org/nightly/reference/type-coercions.html#coercion-sites).  There is a [blanket `Deref`](https://doc.rust-lang.org/std/ops/trait.Deref.html#impl-Deref-5) for `&T`, so `&&i32` gets implicitly coerced to `&i32`.

The reason the closure doesn't work is because it is being passed a type `&(&String, &String)`.  When you have `&k` in the pattern, that is saying you want `k` to be a `String`.  Since `String` is not `Copy`, that won't work.

I'm not sure which editor/IDE you are using, but I believe the rust-analyzer extension can show you inline types that might help you understand which type each thing is.

**Comment by jain98** [comment]
@ehuss Thanks for your comment! 

> In your first example, a is &&i32. Part of [match ergonomics](https://rust-lang.github.io/rfcs/2005-match-ergonomics.html), the pattern has an implicit ref which creates a reference to a reference. 
The reason let _: &i32 = a; works is that a let statement with an explicit type will perform [implicit coercion](https://doc.rust-lang.org/nightly/reference/type-coercions.html#coercion-sites). There is a [blanket Deref](https://doc.rust-lang.org/std/ops/trait.Deref.html#impl-Deref-5) for &T, so &&i32 gets implicitly coerced to &i32.

I'm not confused by or concerned about the `let _: &i32 = a;` statement working. I think I understand how match ergonomics and type coercions make that work. 

What I don't understand is that if `let (a, b) = &items;` means that a and b are `&&i32` then why don't we have the same behavior in the closure for the `find` method? 

> The reason the closure doesn't work is because it is being passed a type &(&String, &String)

Isn't this the same thing that's happening in `let items = (&1, &2); let (a, b) = &items; let (a, b) = &items;`? If yes, then why are k and v in my original code sample not `&&String`. 

> I'm not sure which editor/IDE you are using, but I believe the rust-analyzer extension can show you inline types that might help you understand which type each thing is.

I tried the same code snippet with rust-analyzer and the rust plugin in intellij and both of them seem to suggest that for the below code -

```
        let items = (&1, &2);
        let (a, b) = &items;
```
a and b ar `&&i32`.

**Comment by ehuss** [comment]
> What I don't understand is that if `let (a, b) = &items;` means that a and b are `&&i32` then why don't we have the same behavior in the closure for the `find` method?

I'm not sure I'm following.  In the original example (with `.find(|(k, v)| {…}`), `k` and `v` are `&&String`, which is the same as `a` and `b` which are `&&i32`.  They are both essentially the same.

**Comment by jain98** [comment]
> I'm not sure I'm following. In the original example (with .find(|(k, v)| {…}), k and v are &&String, which is the same as a and b which are &&i32. They are both essentially the same.

If that is the case then is your previous statement below, in contradiction?
> The reason the closure doesn't work is because it is being passed a type &(&String, &String). When you have &k in the pattern, that is saying you want k to be a String. Since String is not Copy, that won't work.

And if in the original example (with `.find(|(k, v)| {…})`, `k` and `v` are `&&String`, then using the pattern `.find(|(&k, &v)| {…})` should copy a `&String` into k and v, no?

**Comment by jain98** [comment]
@ehuss I think I understand what's going on now. I published [this](https://stackoverflow.com/questions/71650383/ambiguous-behavior-in-iterator-while-using-the-find-filter-methods/) StackOverflow question and recently chose a response as the answer.

**Comment by jain98** [comment]
I think my confusion was stemming from the fact that I did not full understand (even after reading the match ergonomics rfc) what the compiler does while performing pattern matching on tuples. But [this](https://stackoverflow.com/questions/71731788/weird-type-when-pattern-matching-references/71732428#71732428) answer here does a pretty good job.
