### ISSUE TITLE
`impl Read for &Stdin` is missing

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#95622]
It is possible to write to a `&Stdout` thanks to `impl Write for &Stdout`, but it is not possible to read from a `&Stdin` as the corresponding `impl Read for &Stdin` is missing. This seems to be entirely an accident, given that [`read_line`](https://doc.rust-lang.org/nightly/std/io/struct.Stdin.html#method.read_line) *does* work on `&Stdin`.

Cc @rust-lang/libs-api

**Comment by joshtriplett** [comment]
Seems reasonable to me.

We'd need to FCP the resulting PR, since trait impls are insta-stable.

**Comment by hi-rustin** [comment]
Sorry, I didn't have time to add it. So see if any other contributors would like to add it. Unassign myself.
