### ISSUE TITLE
{Rc,Arc}::new_cyclic documentation is insufficient

### ISSUE THREAD

**Issue by jdahlstrom** [rust-lang/rust#95672]
As I [reported](https://internals.rust-lang.org/t/rust-1-60-0-prerelease-testing/16421/2?u=jdahlstrom) in the i.r-l.o prerelease thread, the documentation of the new(ly stabilized) `Rc` and `Arc` method `new_cyclic` could really use some elaboration before the 1.60 release. 

I'm quite familiar with refcounting, strong/weak refs, etc. but just from the doc, I have no idea what problem the new method solves exactly, when I should use it, why the closure is needed, how the closure argument seems to come from "thin air", and what the closure should return.

**Comment by Aloso** [comment]
`r/new_acyclic/new_cyclic`

**Comment by jdahlstrom** [comment]
Argh, thanks. Could've sworn I specifically double-checked that I wrote "cyclic"…

**Comment by jethrogb** [comment]
I agree I had to read the documentation a few times to understand what this does.

**Comment by pietroalbini** [comment]
Hi! Just a quick note that changing the documentation for the Rust 1.60.0 release itself will likely not be possible, that'd require a full release rebuild.

**Comment by GuillaumeGomez** [comment]
I'm sending a PR with explanations provided by @CAD97 so that it'll at least be in the next release.

@pietroalbini Why do you need a full release rebuild btw? Isn't it possible to regen the docs without rebuilding everything like the `--keep-stage` option on rustc?

**Comment by GuillaumeGomez** [comment]
I opened https://github.com/rust-lang/rust/pull/95843. Feedback is very welcome. :)

**Comment by pietroalbini** [comment]
> Why do you need a full release rebuild btw? Isn't it possible to regen the docs without rebuilding everything like the --keep-stage option on rustc?

Our release tooling only supports building everything at the same time.

**Comment by GuillaumeGomez** [comment]
Well, at least it'll be present in the next release with a beta backport.
