### ISSUE TITLE
Perf regression on rustdoc `--document-private-items` speed

### ISSUE THREAD

**Issue by GuillaumeGomez** [rust-lang/rust#95694]
The regression was introduced in https://github.com/rust-lang/rust/pull/95645. It seems that we're trying to get too many items.

cc @petrochenkov

**Comment by petrochenkov** [comment]
Should be fixed in https://github.com/rust-lang/rust/pull/95706.

**Comment by GuillaumeGomez** [comment]
It was fixed in #95706.
