### ISSUE TITLE
[NLL] Loss of `'static` relaxation suggestion under NLL

### ISSUE THREAD

**Issue by jackh726** [rust-lang/rust#95701]
In the `src/test/ui/suggestions/impl-on-dyn-trait-with-implicit-static-bound.rs` test, we give the suggestion ```consider relaxing the implicit `'static` requirement``` under migrate mode. Under NLL, we lose that suggestion, and have a slightly less user-friendly error message.

Importantly, with the suggestion, the code is rustfix-able. Without the suggestion, it is not.

**Comment by b-naber** [comment]
@jackh726 Is this a blocker for removing migrate mode?

**Comment by jackh726** [comment]
In my opinion, no. It's just a suggestion.
