### ISSUE TITLE
Change in behavior of debug format of strings containing `\0`

### ISSUE THREAD

**Issue by carols10cents** [rust-lang/rust#95732]
I understand debug formatting is generally unstable, but wanted to raise this to make sure the change was intentional.

### Code

I tried [this test](https://play.rust-lang.org/?version=beta&mode=debug&edition=2021&gist=e7f26a80b75f4c639d1a7cac1dc148d7):

```rust
#[test]
fn quote_not_printable() {
    assert_eq!(format!("{:?}", "foo\0bar"), r#""foo\u{0}bar""#);
}
```

This test passes with stable Rust 1.60.0 (7737e0b5c 2022-04-04) (the release candidate that's going to be released tomorrow)

I expected this test to continue passing with 1.61.0-beta.1

Instead, I get this failure:

```

---- quote_not_printable stdout ----
thread 'quote_not_printable' panicked at 'assertion failed: `(left == right)`
  left: `"\"foo\\0bar\""`,
 right: `"\"foo\\u{0}bar\""`', src/lib.rs:3:5
```

### Version it worked on

It most recently worked on: stable release candidate 1.60.0 (7737e0b5c 2022-04-04)

### Version with regression

`rustc --version --verbose`:
```
rustc 1.61.0-beta.1 (0f231250b 2022-04-05)
binary: rustc
commit-hash: 0f231250ba7fe3a3f98a18aee9abfd65b104fb92
commit-date: 2022-04-05
host: aarch64-apple-darwin
release: 1.61.0-beta.1
LLVM version: 14.0.0
```

@rustbot modify labels: +regression-from-stable-to-beta -regression-untriaged

**Comment by carols10cents** [comment]
I see https://github.com/rust-lang/rust/pull/95345 now. Context: this real-world test: https://github.com/influxdata/influxdb_iox/blob/c244b0328125b3fd1773b58d4e1b1aaf47c83fd3/logfmt/src/lib.rs#L387

I see this has caused some churn in ripgrep too, up to you all if this change is worth the churn.

**Comment by dtolnay** [comment]
> I understand debug formatting is generally unstable, but wanted to raise this to make sure the change was intentional.

This change was intentional. Indeed all debug formattings are always subject to change.

> I see this has caused some churn in ripgrep too, up to you all if this change is worth the churn.

I'm not sure what this refers to &mdash; the ripgrep master branch has had no new commits since when this change landed in nightly, no PRs have been opened on ripgrep either, and no relevant-looking issues have been opened as far as I can tell. Ripgrep has been using the `\0` formatting in its own output since 1.5 years ago.

**Comment by carols10cents** [comment]
For anyone else who's curious (I'm not trying to relitigate this issue or anything), the ripgrep churn I was referring to was https://github.com/BurntSushi/ripgrep/pull/1722/files#diff-4dda3b4b1094bbd540a7548319bd9b4367e93ce4662873d863c219b1b0799adbL43 that I found through [this comment](https://github.com/rust-lang/rust/pull/95345#issuecomment-1079840365).
