### ISSUE TITLE
Doctests picking up non-code blocks

### ISSUE THREAD

**Issue by LucioFranco** [rust-lang/rust#95812]
It looks like doctests are picking up code that is not in a code-block. Below in the code example the `Timestamp timestamp` is being picked up and failing the test because its not actually rust code.

```rust
/// Example 1: Compute Timestamp from POSIX `time()`.
///
///     Timestamp timestamp;
///
fn foo() {}
```

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=c3b61be63d8b9c075a8c122a07fc0dc1

I expect doc tests to pass here since there is no code to actually test.

### Meta

`rustc --version --verbose`:
```
rustc 1.60.0 (7737e0b5c 2022-04-04)
```

also exists in nightly & beta

Related https://github.com/tokio-rs/prost/issues/621

**Comment by GuillaumeGomez** [comment]
Based on the commonmark spec, this is most definitely a code block. You can try it [here](https://spec.commonmark.org/dingus/?text=Example%201%3A%20Compute%20Timestamp%20from%20POSIX%20%60time()%60.%0A%0A%20%20%20%20Timestamp%20timestamp%3B%0A). Closing then.

**Comment by LucioFranco** [comment]
Oh TIL I've been writing markdown for years and didn't know that created a code block. Sorry for the noise!
