### ISSUE TITLE
Make it possible to use `cargo test`, not just `x.py test`

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#95854]
This sounds harder than it actually is, I think. We already have `default-members = ["bootstrap"]` in the root Cargo.toml, so we can implement this by adding an integration test in `src/bootstrap/tests` which calls `builder.ensure(test::X)` for all possible values of X; ideally we would reuse the logic from `x.py test` exactly so that `cargo test` runs all tests, `cargo test src/test/ui` runs UI tests, etc.

cc https://github.com/rust-lang/rust/pull/95253#issuecomment-1094077412, https://github.com/rust-lang/rust/issues/94829
@rustbot label +A-rustbuild +C-enhancement

**Comment by bjorn3** [comment]
If this isn't possible you could put an alias from `cargo x` to `cargo run --` in `.cargo/config.toml`.

**Comment by jyn514** [comment]
@bjorn3 we should do that either way I think :) doesn't hurt and there's other commands we definitely can't support, like `cargo doc`.

**Comment by jyn514** [comment]
Given the new entrypoints we're planning in https://rust-lang.zulipchat.com/#narrow/stream/122651-general/topic/bootstrap.20user.20survey/near/283897117, I am not sure this still makes sense. `cargo test` will be the only command that goes through cargo, and it will make it seem like build is happening through cargo when it's still really using bootstrap under the hood.

@estebank I saw you left a :heart: reaction - do you want to give feedback before I close the issue?

**Comment by estebank** [comment]
@jyn514 I'm ok with the current direction. Familiarity for new contributors with the normal tooling would be useful, but maybe what is needed is to make cargo flexible enough for rustc, and not the other way around.

**Comment by jyn514** [comment]
> maybe what is needed is to make cargo flexible enough for rustc, and not the other way around.

I don't have a lot of confidence this is possible :( there's a thread in https://rust-lang.zulipchat.com/#narrow/stream/122651-general/topic/why.20not.20.60cargo.20build.60.20in.20rust-lang.2Frust.3F where I explain some fundamental limitations cargo has.

Anyway, I think having a mismatch between `test` and the rest of the subcommands isn't great so I'm going to close this.
