### ISSUE TITLE
std lib build broken for uclibc

### ISSUE THREAD

**Issue by asomers** [rust-lang/rust#95866]
Commit https://github.com/rust-lang/rust/commit/33fd73fedeb5cd61dbbb7562fd927c0b6994653a appears to have broken the build for uclibc.  This command fails:
```
cargo +nightly check -Zbuild-std --target armv7-unknown-linux-uclibceabihf
...
error[E0599]: no method named `si_addr` found for struct `siginfo_t` in the current scope
  --> /usr/local/rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/sys/unix/stack_overflow.rs:84:28
   |
84 |         let addr = (*info).si_addr() as usize;
   |                            ^^^^^^^ method not found in `siginfo_t`
```
The problem is that libc does not define that field for uclibc.  Whether that's an oversight in libc, or whether uclibc itself doesn't define that field, I don't know.

**Comment by asomers** [comment]
@skrap can you figure out whether the problem is in libc or uclibc itself?

**Comment by name1e5s** [comment]
> @skrap can you figure out whether the problem is in libc or uclibc itself?

It seems that `libc` doesn't implement `fn si_addr` for `siginfo_t`, maybe we should partially revert #95688

**Comment by skrap** [comment]
Looks like @pfmooney has a good-looking PR out to add those accessors into libc!

**Comment by pfmooney** [comment]
After the next release of libc, whenever that may be, the change from the now-integrated rust-lang/libc#2750 should help address this.  A stopgap fix might be justified in the mean time.

**Comment by asomers** [comment]
libc just released 0.2.124 , and I can build std for uclibc again.

**Comment by skrap** [comment]
OK, so we just need to bump the libc version in rust.  Unless someone objects, I'll submit a PR to rust later today to bump the libc version.

**Comment by JohnTitor** [comment]
The libc version has been updated in https://github.com/rust-lang/rust/pull/96510, closing as fixed.
