### ISSUE TITLE
unused attribute warning when using multiple crate_type

### ISSUE THREAD

**Issue by gheoan** [rust-lang/rust#95902]
Given the following code: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=cfb35aa70ccef56dfbb931a7c093d42b

The current output is:

```
warning: unused attribute
 --> ./temp.rs:2:1
  |
2 | #![crate_type = "lib"]
  | ^^^^^^^^^^^^^^^^^^^^^^ help: remove this attribute
  |
  = note: `#[warn(unused_attributes)]` on by default
note: attribute also specified here
 --> ./temp.rs:1:1
  |
1 | #![crate_type = "dylib"]
  | ^^^^^^^^^^^^^^^^^^^^^^^^
  = warning: this was previously accepted by the compiler but is being phased out; it will become a hard error in a future release!
```

Ideally there should be no output. When using command line arguments instead of the crate_type attributes, there is no output.

Note that the compilation process is successful: even with the warning, both an dylib and a rlib is produced.
May be related to https://github.com/rust-lang/rust/pull/92933.

Tested with rustc 1.60.0 (7737e0b5c 2022-04-04).

**Comment by ehuss** [comment]
I have posted #95910 to fix this.
