### ISSUE TITLE
Pow() syntax is inconsistent between floats and ints

### ISSUE THREAD

**Issue by polyfractal** [rust-lang/rust#9592]
Brought this up on IRC the other day and was told to make an issue :)

The current syntax for Pow() is confusing/inconsistent for (ignorant) newcomers like myself.  For floats, you can do:

```rust
let my_float = 5f32;
let pow2 = my_float.pow(2);
```

But for any of the integers, you need to use the "static" trait function since integers do not implement the Algebraic trait:

```rust
let my_int = 5u32;
let pow2 = Int::pow(my_int, 2);
```

**Comment by frewsxcv** [comment]
A quick update: a `pow()` method was added to the `Int` trait in [this pull request](https://github.com/rust-lang/rust/pull/19031), despite it not existing in the [numerics reform RFC](https://github.com/rust-lang/rfcs/pull/369)

**Comment by steveklabnik** [comment]
This is now all consistent, as far as I can tell. `Int` has `pow`, and `Float`'s was changed to `powi` and `powf`, but the method syntax works.
