### ISSUE TITLE
core::str::validations::next_code_point only accepts an Iterator<&u8> and can not accept an Iterator<u8>

### ISSUE THREAD

**Issue by mutantbob** [rust-lang/rust#95940]
`core::str::validations::next_code_point` only accepts an `Iterator<Item=&u8>`.  Unfortunately my code that needs to convert a byte stream to characters can only have an `Iterator<Item=u8>`.  My specific use case is a string constant stored in progmem on an AVR (Arduino Uno), which requires special machine code to access, because the data exists in a separate address space from regular RAM.  Other use cases could include streaming decompression or decryption.  For now I have duplicated the code for `next_code_point` and embedded it in my application, but it would be nice to be able to use reuse the same code as the standard library.

**Comment by m-ou-se** [comment]
The `str_internals` feature isn't meant to be used outside the standard library though. It doesn't even have a tracking issue.

If you think we should publicly expose such a function, we should discuss that proposal first.

**Comment by saethlin** [comment]
This issue should be an API Change Proposal: https://github.com/rust-lang/libs-team/issues/new?assignees=&labels=api-change-proposal%2C+T-libs-api&projects=&template=api-change-proposal.md&title=%28My+API+Change+Proposal%29

The Rust issue tracker is generally not an effective place for starting discussions like this.

**Comment by Dylan-DPC** [comment]
Closing this as this needs further discussion as a precursor before having this, and as mentioned in the pr linked above that this won't be accepted in the current state.
