### ISSUE TITLE
I couldn't run "cls" with std::pocces::Command.

### ISSUE THREAD

**Issue by Oya-Tomo** [rust-lang/rust#95957]
# Error description
I tried to execute ```cls``` in powershell with  ```std::pocces::Command``` . But it didn't work.
I can build my code, but when I try to run the exe I get an error.
Please tell me the solution to this problem?
I'm sorry I'm not good at English.

# Environment
+ windows11
+ rustc 1.60.0 (installed using scoop)
+ cargo 1.60.0

code
``` rust
use std::process::Command;

fn main() {
    Command::new("cls").status().expect("failed");
}
```
Error message
``` shell
thread 'main' panicked at 'failed: Error { kind: NotFound, message: "program not found" }', src\main.rs:4:34
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by wwylele** [comment]
`cls` isn't a program. It is a shell command of Windows cmd/powershell. `std::process::Command` doesn't run through any shell, and doesn't interpret any shell commands.

**Comment by Oya-Tomo** [comment]
Thank you for your response.☺

Your answer is that Rust can't execute Windows commands, right?
I'm making a cli text editor. I need to clear the console lines.
Can you tell me how to clear the console?

**Comment by name1e5s** [comment]
> Thank you for your response.☺
> 
> Your answer is that Rust can't execute Windows commands, right? I'm making a cli text editor. So, I need to clear the console lines. Can you tell me how to clear the console?

You may instead use `Command::new("cmd").arg("/C").arg("cls")` to clear the console.

**Comment by Oya-Tomo** [comment]
Thank you for your kind answer !
My problem was resolved.😀

**Comment by Dylan-DPC** [comment]
Closing this as issue has been resolved
