### ISSUE TITLE
why is SocketAddr needed when creating a new socket?

### ISSUE THREAD

**Issue by keepsimple1** [rust-lang/rust#95955]
https://github.com/rust-lang/rust/blob/90ca44752a79dd414d9a0ccf7a74533a99080988/library/std/src/sys_common/net.rs#L491

Although the above code passes in `addr` to `Socket::new()`,  the `addr` is only used to check for the address family,  in [Unix](https://github.com/rust-lang/rust/blob/90ca44752a79dd414d9a0ccf7a74533a99080988/library/std/src/sys/unix/net.rs#L62-L67) and [Windows](https://github.com/rust-lang/rust/blob/90ca44752a79dd414d9a0ccf7a74533a99080988/library/std/src/sys/windows/net.rs#L103-L107).  

The original BSD socket, or the standard POSIX socket, AFAIK, does not require actual addresses during creation. My question is: is there any particular reason to require `SocketAddr` in `Socket::new` here?  

Thanks.

**Comment by the8472** [comment]
If you're looking for APIs that create unbound sockets you can use the [socket2](https://crates.io/crates/socket2) crate. The `std` APIs are somewhat simplified and don't expose everything BSD sockets can do.

**Comment by keepsimple1** [comment]
I'm not looking for APIs that create the raw socket. I was wondering since `Socket` is internal, maybe it can be refactored to accept the "address family" as parameter, instead of actual SocketAddr.

**Comment by Dylan-DPC** [comment]
Closing this to clean up the issue tracker.
