### ISSUE TITLE
Add u8::to_ascii_digit()

### ISSUE THREAD

**Issue by hniksic** [rust-lang/rust#95969]
When writing parsers for textual or semi-textual data received from an external source, one often gets octets that need to be interpreted as decimal numbers. For example:

```rust
let mut slice: &[u8] = ...;
// get the next octet in `slice` as hex digit, ignoring hyphens
let digit = loop {
    let c = *slice.get(0)? as char;
    slice = &slice[1..];
    if c == '-' {
        continue;
    }
    break Some(c.to_digit(16)? as u8);
}
```

While the compiler might be able to optimize this code sufficiently, a function like `u8::to_ascii_digit()` would allow us to operate on `u8` directly, making the meaning clearer. It would be analogous to the already existing `is_ascii_digit()` and `to_ascii_{lower,upper}case()`. In the case of the above code, it would look like this:

```rust
let mut slice: &[u8] = ...;
let digit = loop {
    let d = *slice.get(0)?;
    slice = &slice[1..];
    if d == b'-' {
        continue;
    }
    break Some(d.to_ascii_digit(16)?);
}
```

The advantage is that it's clear we're working on octets the whole time. It avoids the cast to `char` which made the code *look* like it handled non-ASCII characters, when it in reality didn't, nor was it supposed to.

**Comment by gimbles** [comment]
#96110 should fix this.

**Comment by Stargateur** [comment]
I'm not sure it's a good idea, this could make people confuse what is what.

A u8 is not supposed to be a character, std force the user to convert a u8 to char to a nice way to prevent mistake.

**Comment by gimbles** [comment]
>  std force the user to convert a u8 to char is a nice way to prevent mistake. IMO the first sniped is more explicit than the second

Can you elaborate on this part please? I couldn't really get what you mean @Stargateur

**Comment by CraftSpider** [comment]
I think there's good intuitive symmetry with the other ascii* functions already on u8. With the provided snippets I find both equally explicit, but I think having this method goes well with the other ascii methods already available, and is equally explicit in general.

**Comment by camsteffen** [comment]
The existing methods `u8::is_ascii_digit` and `u8::Is_ascii_hexdigit` don't have a `radix` argument.

**Comment by m-ou-se** [comment]
As indicated on the [issue templates](https://github.com/rust-lang/rust/issues/new/choose), it's usually best to discuss feature requests on https://internals.rust-lang.org/ rather than opening an issue for them.

**Comment by gimbles** [comment]
Proposal to close this since the PR has been closed? [See PR thread for discussion]

**Comment by thomcc** [comment]
In https://github.com/rust-lang/rust/pull/96110#issuecomment-1134133493 there are several reasons this should probably be closed. Further work on this (perhaps in the form of a more fleshed out `{core,std}::ascii` as mentioned) should be done as an API Change Proposal, rather than in this issue -- see https://std-dev-guide.rust-lang.org/feature-lifecycle/api-change-proposals.html for more info on that if desired.

**Comment by thomcc** [comment]
(Ah, my bad, thanks)
