### ISSUE TITLE
Fix `x.py clippy` to be less janky

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#95988]
I hacked this together when I implemented it originally (https://github.com/rust-lang/rust/pull/77351) and it breaks quite frequently because it uses the host toolchain instead of being managed by bootstrap.

I think ideally the fix would look something like:
- Download clippy for the bootstrap toolchain in `bootstrap.py` (look for `add_component`)
- Remove all this hacky code running rustc --version; treat it just the same as --cfg=bootstrap for `build` and `check`.
- Either put a `todo!()` for stages other than 0, or build `tool::Clippy` in-tree before running them, rather than the host clippy.

_Originally posted by @jyn514 in https://github.com/rust-lang/rust/pull/95766#discussion_r845159871_

**Comment by matthiaskrgr** [comment]
Note: right now an easy workaround that works 99% of the time for running x.py clippy is to just use clippy from the master toolchain (via rtim, switch master toolchain to the default one) and then run x.py clippy :innocent:

**Comment by jyn514** [comment]
Yes, that works. But it would be nice to not need the workaround.

(I think `cargo +beta clippy` should also work? but haven't tested in a while)

**Comment by sebastienblanchet** [comment]
New here and willing to give this a shot.

@rustbot claim
