### ISSUE TITLE
Drop support for `DebuggerTools` being invoked from the top-level bootstrap CLI

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#95992]
@mark-simulacrum mentioned we'd also need some work to ensure they're in dist tarballs, but it looks like they're already present: https://github.com/rust-lang/rust/blob/52ca603da73ae9eaddf96f77953b33ad8c47cc8e/src/bootstrap/dist.rs#L433-L435
So I think this is as simple as changing https://github.com/rust-lang/rust/blob/52ca603da73ae9eaddf96f77953b33ad8c47cc8e/src/bootstrap/dist.rs#L455-L459 to `run.never()` and deleting https://github.com/rust-lang/rust/blob/52ca603da73ae9eaddf96f77953b33ad8c47cc8e/src/bootstrap/builder.rs#L581

_Originally posted by @Mark-Simulacrum in https://github.com/rust-lang/rust/pull/95906#discussion_r847328874_

**Comment by jyn514** [comment]
I double checked and this is never invoked by any scripts in-tree, not even in CI.

**Comment by Mark-Simulacrum** [comment]
That sounds right to me -- I think what I meant is that it's possible we should make sure they're present in regular sysroots (i.e., those produced by compile::Assemble like stage1/...), so that tests can pick them up as needed. That's a separate action item here but might be easy enough to bundle in.

**Comment by bertptrs** [comment]
I would like to tackle this as my first issue. @rustbot claim

**Comment by bertptrs** [comment]
The PR has been merged and I don't think there is anything left to do. Can we close this issue?

**Comment by jyn514** [comment]
Ah yes :) in the future you can add "Fixes #959922" to your PR description to have it closed automatically.
