### ISSUE TITLE
Run `test --stage 0 library/std` in CI

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#95996]
These tests were recently broken by https://github.com/rust-lang/rust/pull/95449. It shouldn't be possible for these to be broken on master - nearly everyone who contributes to the standard library uses `--stage 0`, and this makes it very hard to verify changes.

We should get these running in mingw-check or some other builder.

@rustbot label +P-high +A-testsuite +T-libs

_Originally posted by @Mark-Simulacrum in https://github.com/rust-lang/rust/issues/95993#issuecomment-1097491476_

**Comment by gimbles** [comment]
cc @pietroalbini Any idea re this? :)

**Comment by jyn514** [comment]
@gimbles here's where the code for mingw check lives: https://github.com/rust-lang/rust/blob/a8ede1248d837bc2ecdc99b00e45ec378c3fd156/src/ci/docker/host-x86_64/mingw-check/Dockerfile#L44-L45
that job is also run on a full merge (bors r+) so it should be enough to only modify that.

**Comment by gimbles** [comment]
Awesome, thanks!

**Comment by gimbles** [comment]
Should be resolved by #99040
