### ISSUE TITLE
rustdoc: Many times the same `From<!> for T` impl for the `!` type

### ISSUE THREAD

**Issue by poliorcetics** [rust-lang/rust#96036]
https://doc.rust-lang.org/nightly/std/primitive.never.html#blanket-implementations

![image](https://user-images.githubusercontent.com/7951708/163333624-0e098579-efcf-4132-9bfa-78dfa19ff9cb.png)

All pointing to the same impl:

![image](https://user-images.githubusercontent.com/7951708/163333682-d3d09515-b90f-4047-a3fb-629735af49ab.png)

@rustbot label +T-rustdoc

**Comment by fmease** [comment]
The number of those `From<!>` `impl`s scales with / depends on the number of public types that are defined in the crate that the defines the `impl` (i.e. `core`): If there are zero public types, the `impl` is not shown at all, if there are three public types, three `impl`s are shown and so on.

Minimal reproducible example (warning: cursed Rust code ahead):

```rust
#![feature(no_core, const_trait_impl, never_type, lang_items, auto_traits, rustc_attrs)]
#![crate_type = "lib"]
#![no_core]

impl<T> const From<!> for T { fn from(t: !) -> T { t } }

impl Copy for ! {}
pub trait From<T>: Sized { #[lang = "from"] fn from(_: T) -> Self; }

#[lang = "sized"] pub trait Sized {}
#[lang = "freeze"] unsafe auto trait Freeze {}
#[lang = "copy"] pub trait Copy {}
#[lang = "destruct"] pub trait Destruct {}
#[lang = "receiver"] pub trait Receiver {}
impl<T: ?Sized> Receiver for &T {}

#[doc(primitive = "never")]
#[doc(alias = "!")]
mod prim_never {}

// pub struct A;    // uncommenting increases amount of `From<!>` `impl`s
// pub struct B;    // ^^^
// pub struct C;    // ^^^
```

**Comment by GuillaumeGomez** [comment]
Taking a look.

**Comment by GuillaumeGomez** [comment]
@fmease's code:

```rust
pub trait Something<T> { }
pub struct Whatever;
impl<T> Something<Whatever> for T {}
```

Gives:

![Screenshot from 2022-04-15 17-31-27](https://user-images.githubusercontent.com/3050060/163590114-cbd77eda-3050-48db-83cd-5bcdd47f42c0.png)
