### ISSUE TITLE
Improve diagnostics when ignoring a `#[must_use]` value

### ISSUE THREAD

**Issue by cameron1024** [rust-lang/rust#96053]
Given the following:
```rust
fn main() {
    example();
}

#[must_use]
fn example() -> i32 {
    1
}
```
The following output is given:
```
warning: unused return value of `example` that must be used
 --> src/main.rs:2:5
  |
2 |     example();
  |     ^^^^^^^^^^
  |
  = note: `#[warn(unused_must_use)]` on by default
```

Ideally I'd like to see an additional line saying something like
```
if you want to explicitly ignore the return value, use `let _ = ...`
```
Does this seem sensible? If so I'd be happy to work on it. The main downside I can see is it might lead people to ignore things when they shouldn't, for example someone new to Rust might use `let _ = result_returning_function();` in a spirit of "doing what the compiler says to do", so maybe this should be special-cased to not apply to `Result`?

**Comment by PatchMixolydic** [comment]
Suggesting `let _ = ...;` might be a footgun if the type in question implements `Drop`, as temporaries are immediately dropped when bound to the pattern `_`. This can lead to problems with types that take advantage of scope-based resource management, such as `MutexGuard`. It might be better to try and suggest a name, though coming up with a name to suggest might be difficult.

**Comment by cameron1024** [comment]
Perhaps `_ignore`? `_suppress`? Or only suggest this on types which don't have a `Drop` impl? I'm slightly struggling to come up with a good solution because I can't really picture a situation where you want a RAII style guard that's also `#[must_use]` but you want to suppress it :/

**Comment by estebank** [comment]
Current output:

```
warning: unused return value of `example` that must be used
 --> src/main.rs:2:5
  |
2 |     example();
  |     ^^^^^^^^^
  |
  = note: `#[warn(unused_must_use)]` on by default
help: use `let _ = ...` to ignore the resulting value
  |
2 |     let _ = example();
  |     +++++++
```
