### ISSUE TITLE
Better error message for transitive req of #[deriving].  (Also, how to use deriving here?)

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#9607]
Updated test ([play](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=ada1cfc41339578841d4cddd076b7052)):

```rust
use std::marker::PhantomData;

struct Foo<T> {
  marker: PhantomData<T>
}

trait Bar {}

impl<T: Bar> Clone for Foo<T> {
    fn clone(&self) -> Foo<T> { Foo {marker: PhantomData} }
}

#[derive(Clone)]
struct Baz<T> {
    x: Foo<T>
}

fn main() {}
```

(I'll try to update the above as necessary.)

The error message is pretty good now, actually; the only thing I'd want beyond this is for the diagnostic to point out that `Baz` is trying to automatically derive `Clone` (which is why it is missing the necessary `T: Bar` bound), and that a manual implementation with that bound would work.

Original bug report follows.

----

``` rust
use std::hashmap::HashSet;

#[deriving(Clone)]
struct FollowSet<T> {
  right: HashSet<T>,
  can_end: bool,
}
```

Error message from rustc:

```
% rustc --lib /tmp/f.rs
/tmp/f.rs:3:11: 3:16 error: failed to find an implementation of trait std::to_bytes::IterBytes for T
/tmp/f.rs:3 #[deriving(Clone)]
                       ^~~~~
```

I saw the above, and said "why does it matter about whether I implement `IterBytes` when I want to implement `Clone` here.  (Then I read source code for `hashmap.rs` and saw that we actually build up the new table from scratch, rather than copying the existing underlying representation directly; so that explains why one needs it.)

Anyway, it would be good if the error message actually pointed us at the use of `HashSet<T>` in the definition of `struct FollowSet` above.

---

Oh, also: Is there actually a way for one to use deriving here for this?  As far as I can tell, I'm going to be forced to manually implement `Clone`.  (Its not hard to do, just a little surprising.)

---

(not a true dupe of #7621 since that discussing errors when deriving Clone and constituents do not implement Clone.  Here, we determine that the constituent _does_ implement Clone, if some it implements some other trait as well.  But its possible that a solution for one would also resolve the other.)

**Comment by FlaPer87** [comment]
Triage bump: Updated test:

```rust
use std::marker::{MarkerTrait, PhantomData};

struct Foo<T> {
  marker: PhantomData<T>
}

trait Bar: MarkerTrait {}

impl<T: Bar> Clone for Foo<T> {
    fn clone(&self) -> Foo<T> { Foo {marker: PhantomData} }
}

#[derive(Clone)]
struct Baz<T> {
    x: Foo<T>
}

fn main() {}
```

Output:

```
test.rs:15:5: 15:14 error: the trait `Bar` is not implemented for the type `T` [E0277]
test.rs:15     x: Foo<T>
               ^~~~~~~~~
test.rs:13:10: 13:15 note: in expansion of #[derive_Clone]
test.rs:13:10: 13:15 note: expansion site
error: aborting due to previous error
```

**Comment by bltavares** [comment]
Triaging:

Updated the latest snippet by removing the MarkerTrait.

```rust
use std::marker::PhantomData;

struct Foo<T> {
  marker: PhantomData<T>
}

trait Bar {}

impl<T: Bar> Clone for Foo<T> {
    fn clone(&self) -> Foo<T> { Foo {marker: PhantomData} }
}

#[derive(Clone)]
struct Baz<T> {
    x: Foo<T>
}

fn main() {}
```

Output:
```
<anon>:15:5: 15:14 error: the trait `Bar` is not implemented for the type `T` [E0277]
<anon>:15     x: Foo<T>
              ^~~~~~~~~
<anon>:13:10: 13:15 note: in this expansion of #[derive_Clone] (defined in <anon>)
<anon>:15:5: 15:14 help: see the detailed explanation for E0277
<anon>:15:5: 15:14 note: required by `core::clone::Clone::clone`
error: aborting due to previous error
playpen: application terminated with error code 101
```

**Comment by oli-obk** [comment]
Update: The error output is now

```
error[E0277]: the trait bound `T: Bar` is not satisfied
  --> src/main.rs:15:5
   |
15 |     x: Foo<T>
   |     ^^^^^^^^^ the trait `Bar` is not implemented for `T`
   |
   = help: consider adding a `where T: Bar` bound
   = note: required because of the requirements on the impl of `std::clone::Clone` for `Foo<T>`
   = note: required by `std::clone::Clone::clone`
```

Which is only missing a note about the `derive` expansion now.

Related to the original question of why we can't use `derive` here:

Couldn't the code generated by `derive` have a `where Foo<T>: Clone` bound? This also applies to `Default` and probably others. Afaik `serde` does this for `Serialize` and `Deserialize`.

**Comment by steveklabnik** [comment]
Triage: no change.

**Comment by pnkfelix** [comment]
@oli-obk asked:

> Related to the original question of why we can't use derive here:
>
> Couldn't the code generated by `derive` have a `where Foo<T>: Clone` bound? This also applies to `Default` and probably others. Afaik `serde` does this for `Serialize` and `Deserialize`.

Would we be able to make that change backward compatibly? Probably not because it would make existing types that did not previously implement `Clone` start implementing `Clone`, which is a breaking change, right?

**Comment by estebank** [comment]
> Probably not because it would make existing types that did not previously implement Clone start implementing Clone, which is a breaking change, right?

It would be interesting implementing the behavior and make a crater run to see if there would be significant impact in the ecosystem.

**Comment by estebank** [comment]
Triage: current output:

```
error[E0277]: the trait bound `T: std::clone::Clone` is not satisfied
  --> src/main.rs:15:5
   |
15 |     x: Foo<T>
   |     ^^^^^^^^^
   |     |
   |     expected an implementor of trait `std::clone::Clone`
   |     help: consider borrowing here: `&x: Foo<T>`
   |
   = note: required because of the requirements on the impl of `std::clone::Clone` for `Foo<T>`
   = note: required by `std::clone::Clone::clone`
```

**Comment by rail-rain** [comment]
Update: `rustc` 1.48 does mention that it's from a derive macro:

```
error[E0277]: the trait bound `T: Clone` is not satisfied
  --> src/main.rs:15:5
   |
15 |     x: Foo<T>
   |     ^^^^^^^^^ expected an implementor of trait `Clone`
   |
   = note: required because of the requirements on the impl of `Clone` for `Foo<T>`
   = note: required by `clone`
   = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

**Comment by rylev** [comment]
Triage: the current error message is pretty good IMO. [(playground)](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=6c373b243509f2c09c2ff3bde0455d94)

```
error[E0277]: the trait bound `T: Clone` is not satisfied
  --> src/main.rs:15:5
   |
15 |     x: Foo<T>
   |     ^^^^^^^^^ expected an implementor of trait `Clone`
   |
   = note: required because of the requirements on the impl of `Clone` for `Foo<T>`
   = note: required by `clone`
   = note: this error originates in a derive macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

Perhaps the only improvement could be to point to the specific derive macro that is causing this? 

```
error[E0277]: the trait bound `T: Clone` is not satisfied
  --> src/main.rs:15:5
   |
15 |     x: Foo<T>
   |     ^^^^^^^^^ expected an implementor of trait `Clone`
   |
   = note: required because of the requirements on the impl of `Clone` for `Foo<T>`
   = note: required by `clone`
   = note: this error originates from the derive macro `#[derive(Clone]`
   = note: in Nightly builds, run with -Z macro-backtrace for more info
```

Removing `D-confusing` and `D-invalid-suggestion` as I don't believe that's true anymore.

**Comment by jyn514** [comment]
> Probably not because it would make existing types that did not previously implement Clone start implementing Clone, which is a breaking change, right?

Why would that be a breaking change? If `.clone()` ended up being ambiguous because of a Deref impl or something?

**Comment by estebank** [comment]
With https://github.com/rust-lang/rust/pull/87225, the output is now

```
error[E0277]: the trait bound `T: Clone` is not satisfied
   --> f26.rs:15:5
    |
13  | #[derive(Clone)]
    |          ----- in this derive macro expansion
14  | struct Baz<T> {
15  |     x: Foo<T>
    |     ^^^^^^^^^ expected an implementor of trait `Clone`
    |
note: required because of the requirements on the impl of `Clone` for `Foo<T>`
   --> f26.rs:9:14
    |
9   | impl<T: Bar> Clone for Foo<T> {
    |              ^^^^^     ^^^^^^
note: required by `clone`
   --> /Users/ekuber/workspace/rust/library/core/src/clone.rs:121:5
    |
121 |     fn clone(&self) -> Self;
    |     ^^^^^^^^^^^^^^^^^^^^^^^^
    = note: this error originates in the derive macro `Clone` (in Nightly builds, run with -Z macro-backtrace for more info)
```

<img width="845" alt="Screen Shot 2021-07-19 at 5 43 27 PM" src="https://user-images.githubusercontent.com/1606434/126245209-85acf437-170c-4aae-8da0-0e438d5d2169.png">

There are details in the wording we could improve and some things we could take out, but I feel all the relevant information is there. @pnkfelix what do you think? Should we close this ticket?

**Comment by estebank** [comment]
For posterity, this is what it looks like now:

```
error[[E0277]](https://doc.rust-lang.org/nightly/error-index.html#E0277): the trait bound `T: Bar` is not satisfied
  [--> src/main.rs:15:5
](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018#)   |
13 | #[derive(Clone)]
   |          ----- in this derive macro expansion
14 | struct Baz<T> {
15 |     x: Foo<T>
   |     ^^^^^^^^^ the trait `Bar` is not implemented for `T`
   |
note: required because of the requirements on the impl of `Clone` for `Foo<T>`
  [--> src/main.rs:9:14
](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018#)   |
9  | impl<T: Bar> Clone for Foo<T> {
   |              ^^^^^     ^^^^^^
   = note: this error originates in the derive macro `Clone` (in Nightly builds, run with -Z macro-backtrace for more info)
help: consider restricting type parameter `T`
   |
14 | struct Baz<T: Bar> {
   |             +++++
```
