### ISSUE TITLE
abs function returns negative value

### ISSUE THREAD

**Issue by l3co** [rust-lang/rust#96102]
Recently i tried some math function and when I check the abs function with negative value the same functions returns a negative value. 

### References 

* https://www.mathsisfun.com/numbers/absolute-value.html
* https://en.wikipedia.org/wiki/Absolute_value

I tried this code:

```rust
println!("abs(-3.5) ....................: {}", -3.5f64.abs());
```

I expected to see this happen: *3.5*

Instead, this happened: *-3.5*

### Meta

`rustc --version --verbose`:
```
rustc 1.60.0 (7737e0b5c 2022-04-04)
cargo 1.60.0 (d1fd9fe 2022-03-01)
```

OS.: 

```
Ubuntu Linux : 20.04
Kernel Version :  5.13.0-39-generic
```

**Comment by frewsxcv** [comment]
@l3co Function calls have higher precedence over unary `-`, so the method `abs` gets evaluated before the `-`. You'll need to do `(-3.5f64).abs()`.

https://doc.rust-lang.org/reference/expressions.html#expression-precedence

**Comment by leonardo-m** [comment]
And in your code do use Clippy, that catches that:
```rust
warning: unary minus has lower precedence than method call
 [--> src/main.rs:2:20
](https://play.rust-lang.org/#)  |
2 |     println!("{}", -3.5_f64.abs());
  |                    ^^^^^^^^^^^^^^ help: consider adding parentheses to clarify your intent: `-(3.5_f64.abs())`
  |
  = note: `#[warn(clippy::precedence)]` on by default
  = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#precedence
```
