### ISSUE TITLE
Compiling rust 1.60 from source fails

### ISSUE THREAD

**Issue by dilyanpalauzov** [rust-lang/rust#96111]
I compile Rust 1.60 from this file https://static.rust-lang.org/dist/rustc-1.60.0-src.tar.gz using Rust 1.59.

During `x.py -j1 build` I get:
```
Compiling futures v0.3.19
   Compiling jsonrpc-core v18.0.0
   Compiling parity-tokio-ipc v0.9.0
error[E0308]: mismatched types
  --> /root/.cargo/registry/src/github.com-1ecc6299db9ec823/racer-2.2.0/src/racer/ast.rs:53:64
   |
53 |         let parse_sess = ParseSess::with_span_handler(handler, codemap);
   |                                                                ^^^^^^^ expected struct `Arc`, found struct `Rc`
   |
   = note: expected struct `Arc<SourceMap>`
              found struct `Rc<SourceMap>`

For more information about this error, try `rustc --explain E0308`.
   Compiling jsonrpc-pubsub v18.0.0
   Compiling toml v0.5.7
   Compiling jsonrpc-server-utils v18.0.0
   Compiling crossbeam-deque v0.8.1
```

**Comment by jyn514** [comment]
You have parallel-compiler = true enabled somehow. You should disable it, it's not supported.

**Comment by dilyanpalauzov** [comment]
I call `./configure --enable-parallel-compiler --enable-optimize --enable-extended --llvm-root=/usr/local --enable-llvm-link-shared`, which sets
```
 # Build a multi-threaded rustc
 # FIXME(#75760): Some UI tests fail when this option is enabled.
parallel-compiler = true
```
in config.toml.  Setting `parallel-compiler = true` does finish the compilation.

The `./configure --enable-parallel-compiler` has worked, when compiling rust-1.59, so this is a regression.

**Comment by jyn514** [comment]
> The ./configure --enable-parallel-compiler has worked, when compiling rust-1.59, so this is a regression.

That may be, but parallel-compiler is not supported (especially not with racer). So it is unlikely to get fixed unless you fix it yourself.

**Comment by Mark-Simulacrum** [comment]
The options in config.toml aren't broadly covered by the stability guarantees - those largely only apply to the compiler itself. Builds with the parallel compiler enabled are definitely not stable (and may break or otherwise be removed in any release).

This particular bug is I believe fixed on beta or at least on master, so I'm going to go ahead and close this -- we definitely won't be backporting that change.
