### ISSUE TITLE
Compiler panics when missing parenthesis around tuple when pushing onto Vec

### ISSUE THREAD

**Issue by SteveS-Serrano** [rust-lang/rust#96183]
I was converting a list from a tuple of Vec's to a Vec of tuples, and missed a spot.
### Code

```Rust
type SnrFifoList  = Vec<(  u64,  u32,    u32,   u32,   u32,   u32  )>;

        pub struct LoopStats {
            num_good_tbs : u64,
            num_bad_tbs  : u64,
            received_tbs : u64,
            sot          : u32,
            sot_mismatch : u64,
            status       : [u64; NUM_STATS],
            snr_list     : SnrFifoList, // tbcount + five words per fifo entry
        }
   ...
299                        loop_stats.snr_list.push(
300                            loop_stats.received_tbs,
301                            snr_fifo[0],
302                            snr_fifo[1],
303                            snr_fifo[2],
304                            snr_fifo[3],
305                            snr_fifo[4],
306                        );

 ....
the fix was to add parenthesis around the tuple in line 299 and 306
299                        loop_stats.snr_list.push((
300                            loop_stats.received_tbs,
301                            snr_fifo[0],
302                            snr_fifo[1],
303                            snr_fifo[2],
304                            snr_fifo[3],
305                            snr_fifo[4],
306                        ));
col 29 ------------------------^
col 37--------------------------------^



```

### Meta

`rustc --version --verbose`:
```
$ rustc --version --verbose
rustc 1.60.0-nightly (498eeb72f 2022-01-31)
binary: rustc
commit-hash: 498eeb72f590e518e19746b346be53713689e207
commit-date: 2022-01-31
host: x86_64-unknown-linux-gnu
release: 1.60.0-nightly
LLVM version: 13.0.0

```

### Error output

```
   Compiling avalon v0.5.0 (/home/sscttna/projects/avalon)
error: internal compiler error: compiler/rustc_typeck/src/check/fn_ctxt/_impl.rs:318:26: while adjusting Expr { hir_id: HirId { owner: DefId(0:28842 ~ avalon[de92]::ct::rx::continuous_rx), local_id: 1145 }, kind: Path(Resolved(None, Path { span: src/ct/rx.rs:301:29: 301:37 (#0), res: Local(HirId { owner: DefId(0:28842 ~ avalon[de92]::ct::rx::continuous_rx), local_id: 441 }), segments: [PathSegment { ident: snr_fifo#0, hir_id: Some(HirId { owner: DefId(0:28842 ~ avalon[de92]::ct::rx::continuous_rx), local_id: 1144 }), res: Some(Local(HirId { owner: DefId(0:28842 ~ avalon[de92]::ct::rx::continuous_rx), local_id: 441 })), args: None, infer_args: true }] })), span: src/ct/rx.rs:301:29: 301:37 (#0) }, can't compose [Borrow(Ref('_#345r, Not)) -> &[u32; 5]] and [Borrow(Ref('_#350r, Not)) -> &[u32; 5]]

thread 'rustc' panicked at 'Box<dyn Any>', compiler/rustc_errors/src/lib.rs:1157:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.60.0-nightly (498eeb72f 2022-01-31) running on x86_64-unknown-linux-gnu

note: compiler flags: -C opt-level=3 -C embed-bitcode=no -C linker=aarch64-none-linux-gnu-gcc --crate-type bin

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
#0 [typeck] type-checking `ct::rx::continuous_rx`
#1 [typeck] type-checking `ct::rx::continuous_rx::{closure#0}`
end of query stack
error: could not compile `avalon`

```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
```
$ RUST_BACKTRACE=full cargo build --target=aarch64-unknown-linux-gnu --release
   Compiling avalon v0.5.0 (/home/sscttna/projects/avalon)
error: internal compiler error: compiler/rustc_typeck/src/check/fn_ctxt/_impl.rs:318:26: while adjusting Expr { hir_id: HirId { owner: DefId(0:28842 ~ avalon[de92]::ct::rx::continuous_rx), local_id: 1145 }, kind: Path(Resolved(None, Path { span: src/ct/rx.rs:301:29: 301:37 (#0), res: Local(HirId { owner: DefId(0:28842 ~ avalon[de92]::ct::rx::continuous_rx), local_id: 441 }), segments: [PathSegment { ident: snr_fifo#0, hir_id: Some(HirId { owner: DefId(0:28842 ~ avalon[de92]::ct::rx::continuous_rx), local_id: 1144 }), res: Some(Local(HirId { owner: DefId(0:28842 ~ avalon[de92]::ct::rx::continuous_rx), local_id: 441 })), args: None, infer_args: true }] })), span: src/ct/rx.rs:301:29: 301:37 (#0) }, can't compose [Borrow(Ref('_#345r, Not)) -> &[u32; 5]] and [Borrow(Ref('_#350r, Not)) -> &[u32; 5]]

thread 'rustc' panicked at 'Box<dyn Any>', compiler/rustc_errors/src/lib.rs:1157:9
stack backtrace:
   0:     0x7fe7cf5588bc - std::backtrace_rs::backtrace::libunwind::trace::h57f7807b414eb329
                               at /rustc/498eeb72f590e518e19746b346be53713689e207/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7fe7cf5588bc - std::backtrace_rs::backtrace::trace_unsynchronized::hbdc9ceca4a060796
                               at /rustc/498eeb72f590e518e19746b346be53713689e207/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7fe7cf5588bc - std::sys_common::backtrace::_print_fmt::h27b5ccb1591e1f2e
                               at /rustc/498eeb72f590e518e19746b346be53713689e207/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x7fe7cf5588bc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h9d599eca26bfbfe0
                               at /rustc/498eeb72f590e518e19746b346be53713689e207/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x7fe7cf5b9d2c - core::fmt::write::hc18d9fcf926de540
                               at /rustc/498eeb72f590e518e19746b346be53713689e207/library/core/src/fmt/mod.rs:1190:17
   5:     0x7fe7cf547e73 - std::io::Write::write_fmt::h01252dec1ee17d5d
                               at /rustc/498eeb72f590e518e19746b346be53713689e207/library/std/src/io/mod.rs:1653:15
   6:     0x7fe7cf55cce2 - std::sys_common::backtrace::_print::hbf6e4652dcbb9d3e
                               at /rustc/498eeb72f590e518e19746b346be53713689e207/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x7fe7cf55cce2 - std::sys_common::backtrace::print::h9b9cd8c491550afc
                               at /rustc/498eeb72f590e518e19746b346be53713689e207/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x7fe7cf55cce2 - std::panicking::default_hook::{{closure}}::hf1ff40c60b5ab30d
                               at /rustc/498eeb72f590e518e19746b346be53713689e207/library/std/src/panicking.rs:290:50
   9:     0x7fe7cf55c8c5 - std::panicking::default_hook::h4651ea8e62ea60f2
                               at /rustc/498eeb72f590e518e19746b346be53713689e207/library/std/src/panicking.rs:307:9
  10:     0x7fe7cfd39dd1 - rustc_driver[fb1ec9b0c191644e]::DEFAULT_HOOK::{closure#0}::{closure#0}
  11:     0x7fe7c11e4b79 - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h43d4ea95137da324
  12:     0x7fe7c124b194 - proc_macro::bridge::client::<impl proc_macro::bridge::Bridge>::enter::{{closure}}::{{closure}}::h8a61a0df498b6f61
  13:     0x7fe7c12a3ba6 - std::panicking::update_hook::{{closure}}::h89e7eefcc44cfcca
  14:     0x7fe7cf55d4fb - std::panicking::rust_panic_with_hook::h595b878a5a043a08
                               at /rustc/498eeb72f590e518e19746b346be53713689e207/library/std/src/panicking.rs:695:17
  15:     0x7fe7d0df2e51 - std[6f6e099d0ffdbe4a]::panicking::begin_panic::<rustc_errors[5c190b1069194a04]::ExplicitBug>::{closure#0}
  16:     0x7fe7d0df2d76 - std[6f6e099d0ffdbe4a]::sys_common::backtrace::__rust_end_short_backtrace::<std[6f6e099d0ffdbe4a]::panicking::begin_panic<rustc_errors[5c190b1069194a04]::ExplicitBug>::{closure#0}, !>
  17:     0x7fe7d0df404f - std[6f6e099d0ffdbe4a]::panicking::begin_panic::<rustc_errors[5c190b1069194a04]::ExplicitBug>
  18:     0x7fe7d0e033dd - std[6f6e099d0ffdbe4a]::panic::panic_any::<rustc_errors[5c190b1069194a04]::ExplicitBug>
  19:     0x7fe7d0e0267d - <rustc_errors[5c190b1069194a04]::HandlerInner>::bug
  20:     0x7fe7d0e021d0 - <rustc_errors[5c190b1069194a04]::Handler>::bug
  21:     0x7fe7d0c87fb9 - rustc_middle[308624d00b1a60fb]::ty::context::tls::with_opt::<rustc_middle[308624d00b1a60fb]::util::bug::opt_span_bug_fmt<rustc_span[704723e66117c16c]::span_encoding::Span>::{closure#0}, ()>
  22:     0x7fe7d0c88980 - rustc_middle[308624d00b1a60fb]::util::bug::opt_span_bug_fmt::<rustc_span[704723e66117c16c]::span_encoding::Span>
  23:     0x7fe7d0c888f6 - rustc_middle[308624d00b1a60fb]::util::bug::bug_fmt
  24:     0x7fe7d11015d6 - <rustc_typeck[35f2a1cbc5689fc2]::check::fn_ctxt::FnCtxt>::apply_adjustments
  25:     0x7fe7d10fcee0 - <rustc_typeck[35f2a1cbc5689fc2]::check::fn_ctxt::FnCtxt>::check_expr_kind
  26:     0x7fe7d10dc55a - <rustc_typeck[35f2a1cbc5689fc2]::check::fn_ctxt::FnCtxt>::check_argument_types
  27:     0x7fe7d10f4c50 - <rustc_typeck[35f2a1cbc5689fc2]::check::fn_ctxt::FnCtxt>::check_expr_kind
  28:     0x7fe7d10bb6a6 - <rustc_typeck[35f2a1cbc5689fc2]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  29:     0x7fe7d10e26bf - <rustc_typeck[35f2a1cbc5689fc2]::check::fn_ctxt::FnCtxt>::check_stmt
  30:     0x7fe7d10e36f4 - <rustc_typeck[35f2a1cbc5689fc2]::check::fn_ctxt::FnCtxt>::check_block_with_expected
  31:     0x7fe7d10bb6a6 - <rustc_typeck[35f2a1cbc5689fc2]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  32:     0x7fe7d10f62b9 - <rustc_typeck[35f2a1cbc5689fc2]::check::fn_ctxt::FnCtxt>::check_expr_kind
  33:     0x7fe7d10bb6a6 - <rustc_typeck[35f2a1cbc5689fc2]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  34:     0x7fe7d10e2988 - <rustc_typeck[35f2a1cbc5689fc2]::check::fn_ctxt::FnCtxt>::check_stmt
  35:     0x7fe7d10e3737 - <rustc_typeck[35f2a1cbc5689fc2]::check::fn_ctxt::FnCtxt>::check_block_with_expected
  36:     0x7fe7d10bb6a6 - <rustc_typeck[35f2a1cbc5689fc2]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  37:     0x7fe7d10f62b9 - <rustc_typeck[35f2a1cbc5689fc2]::check::fn_ctxt::FnCtxt>::check_expr_kind
  38:     0x7fe7d10bb6a6 - <rustc_typeck[35f2a1cbc5689fc2]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  39:     0x7fe7d10e2988 - <rustc_typeck[35f2a1cbc5689fc2]::check::fn_ctxt::FnCtxt>::check_stmt
  40:     0x7fe7d10e3737 - <rustc_typeck[35f2a1cbc5689fc2]::check::fn_ctxt::FnCtxt>::check_block_with_expected
  41:     0x7fe7d10f7a4e - <rustc_typeck[35f2a1cbc5689fc2]::check::fn_ctxt::FnCtxt>::check_expr_kind
  42:     0x7fe7d10bb6a6 - <rustc_typeck[35f2a1cbc5689fc2]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  43:     0x7fe7d10e2988 - <rustc_typeck[35f2a1cbc5689fc2]::check::fn_ctxt::FnCtxt>::check_stmt
  44:     0x7fe7d10e3737 - <rustc_typeck[35f2a1cbc5689fc2]::check::fn_ctxt::FnCtxt>::check_block_with_expected
  45:     0x7fe7d10bb6a6 - <rustc_typeck[35f2a1cbc5689fc2]::check::fn_ctxt::FnCtxt>::check_expr_with_expectation_and_args
  46:     0x7fe7d11f6b9f - rustc_typeck[35f2a1cbc5689fc2]::check::check::check_fn
  47:     0x7fe7d117a898 - <rustc_infer[e5de7c7e72aea827]::infer::InferCtxtBuilder>::enter::<&rustc_middle[308624d00b1a60fb]::ty::context::TypeckResults, <rustc_typeck[35f2a1cbc5689fc2]::check::inherited::InheritedBuilder>::enter<rustc_typeck[35f2a1cbc5689fc2]::check::typeck_with_fallback<rustc_typeck[35f2a1cbc5689fc2]::check::typeck::{closure#0}>::{closure#1}, &rustc_middle[308624d00b1a60fb]::ty::context::TypeckResults>::{closure#0}>
  48:     0x7fe7d114b9d2 - rustc_typeck[35f2a1cbc5689fc2]::check::typeck
  49:     0x7fe7d15ed9c7 - rustc_query_system[2e537618065482c4]::query::plumbing::try_execute_query::<rustc_query_impl[4895e94c0e24efb7]::plumbing::QueryCtxt, rustc_query_system[2e537618065482c4]::query::caches::DefaultCache<rustc_span[704723e66117c16c]::def_id::LocalDefId, &rustc_middle[308624d00b1a60fb]::ty::context::TypeckResults>>
  50:     0x7fe7d164fa4c - <rustc_query_impl[4895e94c0e24efb7]::Queries as rustc_middle[308624d00b1a60fb]::ty::query::QueryEngine>::typeck
  51:     0x7fe7d114bb9a - rustc_typeck[35f2a1cbc5689fc2]::check::typeck
  52:     0x7fe7d15ed9c7 - rustc_query_system[2e537618065482c4]::query::plumbing::try_execute_query::<rustc_query_impl[4895e94c0e24efb7]::plumbing::QueryCtxt, rustc_query_system[2e537618065482c4]::query::caches::DefaultCache<rustc_span[704723e66117c16c]::def_id::LocalDefId, &rustc_middle[308624d00b1a60fb]::ty::context::TypeckResults>>
  53:     0x7fe7d164fa4c - <rustc_query_impl[4895e94c0e24efb7]::Queries as rustc_middle[308624d00b1a60fb]::ty::query::QueryEngine>::typeck
  54:     0x7fe7d11b4fee - <rustc_middle[308624d00b1a60fb]::hir::map::Map>::par_body_owners::<rustc_typeck[35f2a1cbc5689fc2]::check::typeck_item_bodies::{closure#0}>
  55:     0x7fe7d1e2418c - rustc_typeck[35f2a1cbc5689fc2]::check::typeck_item_bodies
  56:     0x7fe7d206548a - rustc_query_system[2e537618065482c4]::query::plumbing::try_execute_query::<rustc_query_impl[4895e94c0e24efb7]::plumbing::QueryCtxt, rustc_query_system[2e537618065482c4]::query::caches::DefaultCache<(), ()>>
  57:     0x7fe7d208cc78 - rustc_query_system[2e537618065482c4]::query::plumbing::get_query::<rustc_query_impl[4895e94c0e24efb7]::queries::typeck_item_bodies, rustc_query_impl[4895e94c0e24efb7]::plumbing::QueryCtxt>
  58:     0x7fe7d1e271d9 - <rustc_session[4e9edec593f7bf37]::session::Session>::time::<(), rustc_typeck[35f2a1cbc5689fc2]::check_crate::{closure#7}>
  59:     0x7fe7d1e1c2f3 - rustc_typeck[35f2a1cbc5689fc2]::check_crate
  60:     0x7fe7d1bc4417 - rustc_interface[8a9b172a366d8799]::passes::analysis
  61:     0x7fe7d205b6b2 - rustc_query_system[2e537618065482c4]::query::plumbing::try_execute_query::<rustc_query_impl[4895e94c0e24efb7]::plumbing::QueryCtxt, rustc_query_system[2e537618065482c4]::query::caches::DefaultCache<(), core[ea131dd00119fcdf]::result::Result<(), rustc_errors[5c190b1069194a04]::ErrorReported>>>
  62:     0x7fe7d209a8d5 - rustc_query_system[2e537618065482c4]::query::plumbing::get_query::<rustc_query_impl[4895e94c0e24efb7]::queries::analysis, rustc_query_impl[4895e94c0e24efb7]::plumbing::QueryCtxt>
  63:     0x7fe7d1b97fbd - <rustc_interface[8a9b172a366d8799]::passes::QueryContext>::enter::<rustc_driver[fb1ec9b0c191644e]::run_compiler::{closure#1}::{closure#2}::{closure#3}, core[ea131dd00119fcdf]::result::Result<(), rustc_errors[5c190b1069194a04]::ErrorReported>>
  64:     0x7fe7d1b961fa - <rustc_interface[8a9b172a366d8799]::interface::Compiler>::enter::<rustc_driver[fb1ec9b0c191644e]::run_compiler::{closure#1}::{closure#2}, core[ea131dd00119fcdf]::result::Result<core[ea131dd00119fcdf]::option::Option<rustc_interface[8a9b172a366d8799]::queries::Linker>, rustc_errors[5c190b1069194a04]::ErrorReported>>
  65:     0x7fe7d1b9903c - rustc_span[704723e66117c16c]::with_source_map::<core[ea131dd00119fcdf]::result::Result<(), rustc_errors[5c190b1069194a04]::ErrorReported>, rustc_interface[8a9b172a366d8799]::interface::create_compiler_and_run<core[ea131dd00119fcdf]::result::Result<(), rustc_errors[5c190b1069194a04]::ErrorReported>, rustc_driver[fb1ec9b0c191644e]::run_compiler::{closure#1}>::{closure#1}>
  66:     0x7fe7d1b95bde - rustc_interface[8a9b172a366d8799]::interface::create_compiler_and_run::<core[ea131dd00119fcdf]::result::Result<(), rustc_errors[5c190b1069194a04]::ErrorReported>, rustc_driver[fb1ec9b0c191644e]::run_compiler::{closure#1}>
  67:     0x7fe7d1b7abe2 - std[6f6e099d0ffdbe4a]::sys_common::backtrace::__rust_begin_short_backtrace::<rustc_interface[8a9b172a366d8799]::util::setup_callbacks_and_run_in_thread_pool_with_globals<rustc_interface[8a9b172a366d8799]::interface::run_compiler<core[ea131dd00119fcdf]::result::Result<(), rustc_errors[5c190b1069194a04]::ErrorReported>, rustc_driver[fb1ec9b0c191644e]::run_compiler::{closure#1}>::{closure#0}, core[ea131dd00119fcdf]::result::Result<(), rustc_errors[5c190b1069194a04]::ErrorReported>>::{closure#0}, core[ea131dd00119fcdf]::result::Result<(), rustc_errors[5c190b1069194a04]::ErrorReported>>
  68:     0x7fe7d1b79639 - <<std[6f6e099d0ffdbe4a]::thread::Builder>::spawn_unchecked_<rustc_interface[8a9b172a366d8799]::util::setup_callbacks_and_run_in_thread_pool_with_globals<rustc_interface[8a9b172a366d8799]::interface::run_compiler<core[ea131dd00119fcdf]::result::Result<(), rustc_errors[5c190b1069194a04]::ErrorReported>, rustc_driver[fb1ec9b0c191644e]::run_compiler::{closure#1}>::{closure#0}, core[ea131dd00119fcdf]::result::Result<(), rustc_errors[5c190b1069194a04]::ErrorReported>>::{closure#0}, core[ea131dd00119fcdf]::result::Result<(), rustc_errors[5c190b1069194a04]::ErrorReported>>::{closure#1} as core[ea131dd00119fcdf]::ops::function::FnOnce<()>>::call_once::{shim:vtable#0}
  69:     0x7fe7cf569253 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h517b04514611d0c2
                               at /rustc/498eeb72f590e518e19746b346be53713689e207/library/alloc/src/boxed.rs:1854:9
  70:     0x7fe7cf569253 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h7f563a51cc3a5629
                               at /rustc/498eeb72f590e518e19746b346be53713689e207/library/alloc/src/boxed.rs:1854:9
  71:     0x7fe7cf569253 - std::sys::unix::thread::Thread::new::thread_start::h3d3787d3c1d471cc
                               at /rustc/498eeb72f590e518e19746b346be53713689e207/library/std/src/sys/unix/thread.rs:108:17
  72:     0x7fe7cf48a609 - start_thread
                               at /build/glibc-sMfBJT/glibc-2.31/nptl/pthread_create.c:477:8
  73:     0x7fe7cf3a3163 - clone
  74:                0x0 - <unknown>

note: the compiler unexpectedly panicked. this is a bug.

</p>
</details>

**Comment by compiler-errors** [comment]
@SteveS-Serrano, thanks for the issue report. You're using a three month old nightly version, and this bug was fixed sometime in February if I recall correctly. Please update your compiler, and feel free to file a new bug if you see it after a `rustup update` or however you like to update your toolchain.
