### ISSUE TITLE
Rustc assumes a type is () sometimes when it should ask for a type annotation

### ISSUE THREAD

**Issue by ekuecks** [rust-lang/rust#96265]
I tried this code:

```rust
fn print_type<T>(_: &T) {
    println!("{}", std::any::type_name::<T>());
}

fn foo<T: MyTrait>() -> Result<T, String> {
    T::generate()
}

trait MyTrait: Sized {
    fn generate() -> Result<Self, String>;
}

impl MyTrait for () {
    fn generate() -> Result<Self, String> {
        Ok(())
    }
}

impl MyTrait for i32 {
    fn generate() -> Result<Self, String> {
        Ok(0)
    }
}

fn indirection() -> Result<&'static str, String> {
    let x = foo()?;
    print_type(&x);
    Ok("abc")
}

fn main() -> Result<(), String> {
    let y = foo()?;
    print_type(&y);
    indirection()?;
    Ok(())
}
```

playground: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=994a5144bddd3b1e665af930c337bfdf

I expected to see this happen: I expected the code to not compile because there is no way to know what type I want for either of the `x` or `y` variables. This should require me to write `let x: ()` in order to compile

Instead, this happened: Rust assumes that the type of `x` is `()` and the code compiles and runs. Note that this is somehow related to the use of `?`. Without the `?`, it doesn't compile (as expected), whether the code still uses `Result<T, _>` or just `T`. Also note that if you remove the `impl MyTrait for ()`, it does not compile and says that `MyTrait is not implemented for ()`:

```
Compiling playground v0.0.1 (/playground)
error[[E0277]](https://doc.rust-lang.org/beta/error-index.html#E0277): the trait bound `(): MyTrait` is not satisfied
  [--> src/main.rs:21:13
](https://play.rust-lang.org/?version=beta&mode=debug&edition=2021#)   |
21 |     let x = foo()?;
   |             ^^^ the trait `MyTrait` is not implemented for `()`
```
so it is still assuming that the type is ()

### Meta

`rustc --version --verbose`:
```
1.60.0 (stable)
1.62.0-nightly
```
(The above are the versions from the playground)

</p>
</details>

**Comment by ehuss** [comment]
I think the first answer [here](https://www.reddit.com/r/rust/comments/f5nw1o/why_does_rust_infer_when_the_generic_type_cannot/) explains the situation pretty well.  The inference for the `!` type defaults to `()`.  I don't think that is something that can necessarily change (or at least, there is a mired history of stabilizing `!` related to inference changes).

**Comment by ekuecks** [comment]
Ah thank you for the very helpful link! So this is sadly not the weekend project I hoped it was. I'll close it as it seems like this is a duplicate of a much larger, more complicated issue.
