### ISSUE TITLE
Has ctfe-stress-5-check been gradually regressing since 2022-04-09?

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#96267]
Spawned off of https://github.com/rust-lang/rust/pull/96015#issuecomment-1104623847

Look at this graph:

![image](https://user-images.githubusercontent.com/173127/164355475-06c5e3aa-ac94-4c0e-83ac-146992c7a939.png)

is the trend there something we should be worried about? (Or is this just a microbenchmark that we should not put too much stock in relative to everything else that is going on in the compiler...)

**Comment by RalfJung** [comment]
Cc @rust-lang/wg-const-eval

**Comment by oli-obk** [comment]
cc @lqd who is looking into some improvements here.

**Comment by Enselic** [comment]
> Or is this just a microbenchmark that we should not put too much stock in relative to everything else that is going on in the compiler

From the age of this issue I think we can conclude that this is not something to put too much effort into relative to other things.

Closing since I think this will remain open forever otherwise, but feel free to reopen if you disagree.
