### ISSUE TITLE
`llvm.expect` intrinsic from `likely/unlikely` is not emitted in release mode

### ISSUE THREAD

**Issue by Kobzol** [rust-lang/rust#96276]
When the `std::intrinsics::unlikely/likely` function is used, the codegen doesn't emit `llvm.expect` annotation in release mode. Curiously enough, in debug mode it *does* emit it.

A minimal example:
```rust
#![feature(core_intrinsics)]

use std::intrinsics::unlikely;

pub fn foo(x: bool) {
    if unlikely(x) {
        println!("foo: {x}");
    }
    println!("bar");
}
```
Playground link [here](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021). In debug mode, LLVM IR contains `llvm.expect`. In release mode, it doesn't.

This has been previously noted [here](https://github.com/rust-lang/rust/issues/26179#issuecomment-974744742) (maybe it indeed started with LLVM 13?) and more recently [here](https://github.com/rust-lang/rust/pull/93668#issuecomment-1104826453).

I can take a look into this, if you can point me into the right direction. There is a codegen test for `likely/unlikely`, but it uses `-C no-prepopulate-passes`, which does not correspond to what release (`-O`) does.

**Comment by Kobzol** [comment]
Oops, @SUPERCILEX was [faster](https://github.com/rust-lang/rust/issues/96275) :) Closing as a duplicate.

**Comment by SUPERCILEX** [comment]
Yours has more detail though so reposted. :)
