### ISSUE TITLE
Tracking Issue for pointer_bytes_offsets

### ISSUE THREAD

**Issue by Gankra** [rust-lang/rust#96283]
Feature gates: 

`#![feature(pointer_byte_offsets)]` 

`#![feature(const_pointer_byte_offsets)]`

This is a tracking issue for the pointer_byte_offsets raw pointer conveniences like `ptr.byte_add(offset)`

### Public API

```rust
impl<T: ?Sized> *const T {
    // feature gates `pointer_byte_offsets` and `const_pointer_byte_offsets`
    pub const unsafe fn byte_offset(self, count: isize) -> Self;
    pub const unsafe fn byte_add(self, count: usize) -> Self;
    pub const unsafe fn byte_sub(self, count: usize) -> Self;

    pub const fn wrapping_byte_offset(self, count: isize) -> Self;
    pub const fn wrapping_byte_add(self, count: usize) -> Self;
    pub const fn wrapping_byte_sub(self, count: usize) -> Self;

    pub const unsafe fn byte_offset_from<U: ?Sized>(self, origin: *const U) -> isize;
}

// ... and the same for` *mut T`
```

### Steps / History

- [x] Implementation: #95643
- [x] Making `byte_offset_from` more generic: #103489
- [ ] Final comment period (FCP)
- [ ] Stabilization PR

### Unresolved Questions

- Should these operations actually accomodate DSTs? This seems deeply semantically dubious/broken but idk, you can plausibly use them right if you are extremely careful and understand the implications of stacked borrows for slices/projections.

**Comment by WaffleLapkin** [comment]
@Gankra actually, I think allowing these methods take pointers to DST unlocks a lot of abilities for custom DSTs. In particular `byte_sub` is required to implement `Arc::from_raw` (as it accepts a possibly fat pointer to `T` that needs to be offseted back to `ArcInner<T>`).

**Comment by WaffleLapkin** [comment]
I want to propose to stabilize these methods! (can someone open an fcp?)

# Stabilization report

## Implementation History

- Initially these methods were implemented in https://github.com/rust-lang/rust/pull/95643
- The only unresolved question raised since then is whatever to allow calling these methods on pointers to unsized types. I propose to resolve this to "yes, we should actually", this will unlock a lot of options for working with unsized types (see expitience report for an example).

## API Summary

```rust
impl *const T {
    pub const unsafe fn byte_offset(self, count: isize) -> Self;
    pub const fn wrapping_byte_offset(self, count: isize) -> Self;
    pub const unsafe fn byte_offset_from(self, origin: *const T) -> isize;
    pub const unsafe fn byte_add(self, count: usize) -> Self;
    pub const unsafe fn byte_sub(self, count: usize) -> Self;
    pub const fn wrapping_byte_add(self, count: usize) -> Self;
    pub const fn wrapping_byte_sub(self, count: usize) -> Self;
}

// ... and the same for` *mut T`
```

## Experience Report

https://github.com/rust-lang/rust/pull/99113 and https://github.com/rust-lang/rust/pull/100819 refactored some std code into using these methods simplifying the code. 

These methods allow custom `Arc` implementations to work with unsized types just as well as `std::arc::Arc`, namely they allow to offset a pointer by `<size of arc metadata>` while keeping pointer metadata, which is required for example for `Arc::from_raw`.

This also allows to polyfil `with_metadata_of` by using `wrapping_byte_offset`, which is again very useful when working with DSTs.

**Comment by scottmcm** [comment]
Pondering: does `byte_offset_from` really need its argument to be a `*const T`?  Arguably it doesn't care what type you pass it, so it could be `*const U` instead.

That would allow things like `ptr::addr_of!(x.b).byte_offset_from(ptr::addr_of!(x))` to compile without needing an arbitrary choice of cast.

**Comment by dennis-hamester** [comment]
I have a question regarding the `offset_from` family of functions, stabilized or not. In all those cases where it is safe to use, why not use `as` integer casts, ignoring the fact that conversion from bytes to units of `T` might be required?

I just had the situation today, where I needed the offset between 2 bytes slices (one is a subslice of the other) and failed to see why I should use the unsafe `offset_from`. In either case, I have to be able to reason about why my code is correct, but not having to reason about why my code doesn't invoke UB seemed like a +1 for integer casts. Obviously this is just one example, and certainly not "all those cases".

But I'm wondering, what are safe examples in which I should use `offset_from` as opposed to integer casts?

**Comment by scottmcm** [comment]
`offset_from` (and particularly `sub_ptr`) allows LLVM to optimize more based on the unsafety.  If your code is not a place where you get a material advantage from those extra optimizations, then by all means use the safe phrasings.  (`sub_ptr` is very important for `slice::Iter::len`, but there's very little code that's anywhere close to as perf-critical as that.)

**Comment by RalfJung** [comment]
Another advantage of offset_from is that it can be used in `const fn`.

For some time we had safe variants of `offset_from`, maybe it is worth thinking about bringing them back.

**Comment by WaffleLapkin** [comment]
@marc0246 as far, as I'm aware: no, not really. This is just waiting on `T-libs-api` green light for stabilization.

**Comment by GummyGun** [comment]
What is the status of `byte_offset_from()` will it be stable anytime soon

**Comment by WaffleLapkin** [comment]
I'm nominating this for t-libs-api discussion. I propose to stabilize those APIs, see the stabilization report: https://github.com/rust-lang/rust/issues/96283#issuecomment-1236389783.

(it looks like I forgot to make sure t-libs-api sees the report, oops 💀)

**Comment by m-ou-se** [comment]
@rfcbot merge

**Comment by tgross35** [comment]
Very late thought - has reversing the names `byte_add` -> `add_bytes`, `byte_offset` -> `offset_bytes` been considered?

I think that would make sorting in the docs nicer, and make it generally more discoverable. E.g. you know you want to add something - either you scan the docs and see all the adding things there, or type `add` in an IDE and stumble across the suggestions to add bytes.

As-is, you have to be aware that the `byte_x` methods exist, they don't even fit on the same page as `offset` and `sub` in the TOC

![image](https://github.com/rust-lang/rust/assets/13724985/696c5e7b-4c2a-4a3d-a9f6-5aba83b11e37)

**Comment by scottmcm** [comment]
Discoverability should get better with stabilization.  We don't mention unstable things from the docs for stable things, but as part of stabilization we can add something like this to `add`:

> This counts in terms of *elements*.  If you want to move the pointer by a number of *bytes* instead, see [`byte_add`](#method.byte_add).

to help people find it.

**Comment by RalfJung** [comment]
I have to always try a bunch of permutations when calling the "bytes" methods, I can never remember where the `byte` part goes.

**Comment by dtolnay** [comment]
We don't need to restart an FCP clock for this but I'd still like to be sure the team has seen the important discussion that took place after the 3 currently checked boxes. Thank you for raising this @tgross35. @rust-lang/libs-api: please have a look at https://github.com/rust-lang/rust/issues/96283#issuecomment-1746872231 which is an insightful breakdown.

I think the current set of names (see top of this issue) continue to be my first choice for word order.

@rfcbot poll libs-api Proceed with current word order?

**Comment by tgross35** [comment]
This didn’t yet finish the poll no? I don’t expect the results to change but it should be pretty easy to get the last checkbox

**Comment by m-ou-se** [comment]
I don't think it matters much, but I think of these methods as "byte-based addition" rather than "adding bytes", so that makes me slightly prefer `byte_add`.
