### ISSUE TITLE
UTF-8 to UTF-16 Path conversions on Windows unnecessarily allocate twice

### ISSUE THREAD

**Issue by AronParker** [rust-lang/rust#96297]
The Unicode Windows API internally works with (potentially ill-formed) UTF-16 paths that must be converted to from Rust's UTF-8 strings. The conversion happens here:

https://github.com/rust-lang/rust/blob/b04c5329e1e145fb2fb46c5a7e775638712b03aa/library/std/src/sys/windows/mod.rs#L159-L166

`encode_wide` does the translation from WTF-8 to UTF-16, leaving a `Vec<u16>` with `len == cap`. The following calling to `push` will then allocate to reserve additional memory for the null-terminating character.

This could be resolved in two ways:

1) Call `Vec::with_capacity(EncodeWide::size_hint + 1)` beforehand and then call `Vec::extend` on EncodeWide.
2) Make a wrapper around `EncodeWide` that increases `iter::size_hint` by one. Incorporating the final null byte into `iter::next` would add a performance penalty, therefore it would probably be desirable to just adjust the size_hint by one and adding the null-terminator manually.

**Comment by ChrisDenton** [comment]
In the interest of enumerating possibilities, there's also using `chain` (hopefully this will optimize):

```rust
let mut maybe_result: Vec<u16> = s.encode_wide().chain([0]).collect(); 
if unrolled_find_u16s(0, &maybe_result[..maybe_result.len() - 1]).is_some() {
```

Or we could test the `OsStr` for nulls before converting.

**Comment by AronParker** [comment]
> In the interest of enumerating possibilities, there's also using `chain` (hopefully this will optimize):
> 
> ```rust
> let mut maybe_result: Vec<u16> = s.encode_wide().chain([0]).collect(); 
> if unrolled_find_u16s(0, &maybe_result[..maybe_result.len() - 1]).is_some() {
> ```
> 
> Or we could test the `OsStr` for nulls before converting.

That's a good idea! Chain actually gives an example for windows paths:
```rust
#[cfg(windows)]
fn os_str_to_utf16(s: &std::ffi::OsStr) -> Vec<u16> {
    use std::os::windows::ffi::OsStrExt;
    s.encode_wide().chain(std::iter::once(0)).collect()
}```

Although I'm not sure what's more efficient here, std::iter::once or [0]? Allocations are quite expensive so I believe the additional check (if it's not optimized away) would be worth it.

However I also discovered a deeper issue. The size_hint that originates from the WTF-8 iterator is in UTF-32 code points. The lower bound will be `chars / 4` (assuming that all code points are U+10000 or higher), the upper bound is `chars` (everything is "ASCII"). When collecting into a vector, the lower bound is chosen as an initial capacity. Since you almost never encounter paths that consists of U+10000 characters only, the estimated lower bound will always be too low and 4 allocations are required if the path is ASCII only, 2 allocations are required if the path is UTF-16 only, and 1 allocation is required if the path is UTF-32 only.

It might be worth a consideration whether to call `Vec::with_capacity(len + 1)`, as that would be a sane default (on the assumption that the majority of paths are UTF-8). However, this might waste some memory, do we have any idea on whether paths created from this function are primarily used ephemerally?

**Comment by ChrisDenton** [comment]
I believe all uses of `to_u16s` are currently ephemeral. We tend to use it only for as long as necessary to call a Windows API. There are a few places we keep wide strings around longer but those don't use `to_u16s` as far as I can tell.

**Comment by AronParker** [comment]
In light of that, I believe that the first solution would be the best. Solution number two would make naming very awkward (EncodeWideWithNul?). And while your solution is very elegant and correct, it would still mostly under-allocate given the interaction between size_hint's lower bound and collect. However, I find both solution 1 and solution 3 acceptable. It would be good to know how much reallocation actually costs and if it even matters at all in the context of interacting with expensive IO.

**Comment by ChrisDenton** [comment]
I do agree implementing solution 1 would be a good idea. Having some good performance numbers would be great but I do suspect reducing allocations would be a win here.

I would also like us to use stack buffers more, similar to [fill_utf16_buf](https://github.com/rust-lang/rust/blob/1e6fe5855a115ef7f17f3e17205fab7340775701/library/std/src/sys/windows/mod.rs#L193). and only use new allocations when necessary. But that's perhaps another issue.

**Comment by AronParker** [comment]
Reducing via stack buffers is a good idea, but I think it's out of scope for this issue. For now let's just reduce regular allocations, that should already give us some improvement!

I'll try to see if I can implement this one.

@rustbot claim

**Comment by faptc** [comment]
> The Unicode Windows API internally works with (potentially ill-formed) UTF-16 paths that must be converted to from Rust's UTF-8 strings. The conversion happens here:
> 
> https://github.com/rust-lang/rust/blob/b04c5329e1e145fb2fb46c5a7e775638712b03aa/library/std/src/sys/windows/mod.rs#L159-L166
> 
> `encode_wide` does the translation from WTF-8 to UTF-16, leaving a `Vec<u16>` with `len == cap`. The following calling to `push` will then allocate to reserve additional memory for the null-terminating character.
> 
> This could be resolved in two ways:
> 
> 1. Call `Vec::with_capacity(EncodeWide::size_hint + 1)` beforehand and then call `Vec::extend` on EncodeWide.
> 2. Make a wrapper around `EncodeWide` that increases `iter::size_hint` by one. Incorporating the final null byte into `iter::next` would add a performance penalty, therefore it would probably be desirable to just adjust the size_hint by one and adding the null-terminator manually.

**Comment by AronParker** [comment]
Fixed by https://github.com/rust-lang/rust/pull/96314
