### ISSUE TITLE
Cargo caused complete breakage of 4 pipelines

### ISSUE THREAD

**Issue by Yuri6037** [rust-lang/rust#96349]
A week ago Cargo dropped allowed_fail field in the test JSON output: https://github.com/rust-lang/rust/commit/6562069ebef1097109d315e50cf9929a30e86811.

This breaking change was never announced and caused 4 pipelines on GitLab to fail due the now missing field.

In the future I think rust should announce such breaking changes before committing the changes.

**Comment by joshtriplett** [comment]
`allow_fail` was a nightly-only feature. However, it looks like stable Rust emitted `allow_fail: false` on tests, rather than omitting the `allow_fail` attribute. In general, we shouldn't let nightly-only features affect stable output when not used, for exactly this reason.

@Yuri6037 To confirm, your pipelines were depending on the presence of `allow_fail: false` in the output?

**Comment by Yuri6037** [comment]
> `allow_fail` was a nightly-only feature. However, it looks like stable Rust emitted `allow_fail: false` on tests, rather than omitting the `allow_fail` attribute. In general, we shouldn't let nightly-only features affect stable output when not used, for exactly this reason.
> 
> @Yuri6037 To confirm, your pipelines were depending on the presence of `allow_fail: false` in the output?

Thanks, yes indeed the pipelines depends on a tool which did require the presence of allow_fail for serde decoding. When this field was dropped the tool started to emit errors in all pipelines using it.

**Comment by joshtriplett** [comment]
@Yuri6037 We shouldn't do breaking changes at all, with or without announcements. https://github.com/rust-lang/rust/pull/93416 was not known to be a breaking change when it was made; it was assumed to be the removal of a nightly feature, which wouldn't be subject to any stability guarantee. I would guess that nobody caught that `allow_fail: false` was being emitted as part of stable output.

**Comment by ehuss** [comment]
> I would guess that nobody caught that `allow_fail: false` was being emitted as part of stable output.

`--format json` is also unstable, so I don't think this is a stable change.

**Comment by nagisa** [comment]
I tagged this `requires-nightly` given that everything so far points at this requiring a nightly. We can remove the tag if the issue author can confirm that they were seeing this with a stable compiler and without `RUSTC_BOOTSTRAP=1`-like workarounds and detail how.

**Comment by Yuri6037** [comment]
The actual program being tested builds in stable rust. However the test command uses unstable features to access the JSON output formatting.

**Comment by joshtriplett** [comment]
@ehuss Thanks for the clarification!

**Comment by Enselic** [comment]
Triage: There is no further action to take here then, right?

Closing, but feel free to reopen if I am mistaken.
