### ISSUE TITLE
Forbid lowering the same `NodeId` multiple times

### ISSUE THREAD

**Issue by cjgillot** [rust-lang/rust#96346]
During AST->HIR lowering, the method `lower_node_id` is tasked to transform `NodeId`s that identify AST nodes into `HirId`s that identify HIR nodes.  This method maintains a `node_id_to_local_id: FxHashMap<NodeId, hir::ItemLocalId>` to remember this mapping.

However, this mapping is not entirely useful, and mostly exists (1) to make the developer's life easier, (2) to lower resolutions to local bindings `Res::Local` in `lower_res`.  The mapping `node_id_to_local_id` should be removed, and multiple calls to `local_node_id` with the same `NodeId` should be forbidden.  For usage (2), `Res::Local` only appears for ident patterns (`PatKind::Ident`) which are lowered by `lower_pat_ident`.  Hence, `lower_res` should use a dedicated hash-map filled by `lower_pat_ident`.

Furthermore, `next_id` calls `lower_node_id` with a `node_id: NodeId` which is entirely local to that function, and will never be known to any other code. Manipulations of `node_id_to_local_id` there are entirely useless. 

Instructions:
- inline `lower_node_id` into `next_id` and skip manipulations of `node_id_to_local_id`;
- replace the `Entry::Occupied` branch in `lower_node_id` by a `panic!`, and fix all the ICEs;
- create another mapping `node_id_to_local_id_for_res` (name to bikeshed) which is only filled by `lower_pat_ident` and read by `lower_res`; this mapping should be saved by `with_hir_id_owner` like `node_id_to_local_id` is;
- remove `node_id_to_local_id`, or eventually keep it only to debug-assert that we don't call `lower_node_id` twice on the same `NodeId`.

**Comment by raiyansayeed** [comment]
Hey @kckeiks , are you still working on this task?

**Comment by kckeiks** [comment]
@raiyansayeed I was but I have a couple more issues that I'm working on so you can take this one if you want.

**Comment by spastorino** [comment]
@raiyansayeed feel free to ping me too on Zulip if you need help or something.

**Comment by trevyn** [comment]
@raiyansayeed are you still working on this?

**Comment by azadnn** [comment]
https://rust-lang.zulipchat.com/#narrow/stream/315146-t-compiler.2Fetc.2Fincremental-hir/topic/reduce.2Feliminate.20duplicate.20invocation.20of.20.60lower_node_id.60/near/324846414
