### ISSUE TITLE
Rustc does not know that two structs have the same size, while it should.

### ISSUE THREAD

**Issue by wdanilo** [rust-lang/rust#96357]
Hi, let's consider this code:

```rust
#[repr(transparent)]
pub struct UnitData<V, R> {
    repr:    R,
    variant: PhantomData<V>,
}

trait TransmuteRanges {
    type Out;
    fn t1(self) -> Self::Out;
}

impl<V, R> TransmuteRanges for std::ops::Range<UnitData<V, R>> {
    type Out = std::ops::Range<R>;
    fn t1(self) -> Self::Out {
        unsafe { std::mem::transmute(self) }
    }
}
```

It does not compile:

```
    |
121 |         unsafe { std::mem::transmute(self) }
    |                  ^^^^^^^^^^^^^^^^^^^
    |
    = note: source type: `std::ops::Range<UnitData<V, R>>` (size can vary because of R)
    = note: target type: `std::ops::Range<R>` (size can vary because of R)
```

But this one compiles fine:

```rust
impl<V> TransmuteRanges for std::ops::Range<UnitData<V, usize>> {
    type InnerType = usize;
    fn t1(self) -> std::ops::Range<Self::InnerType> {
        unsafe { std::mem::transmute(self) }
    }
}
```

This one compiles fine too:

```rust
impl<V, R> TransmuteRanges for std::ops::Range<UnitData<V, R>> {
    type Out = std::ops::Range<R>;
    fn t1(self) -> Self::Out {
        self.start.repr..self.end.repr
    }
}
```

I believe the transmute one should compile. Rustc version: rustc 1.62.0-nightly (8f36334ca 2022-04-06).

**Comment by oli-obk** [comment]
I don't think we're going to support this any time soon. The way we check whether a transmute is possible is by computing the arguments' sizes and comparing them. If those sizes depend on a generic parameter, then the size computation simply fails, it doesn't return a "generic size"

While we could have a separate "structural" size comparison logic, that may diverge from the actual size computation logic which would be unsound.

Sure, we could support a trivial version that supports just transparent structs, but that seems awefully targeted to a niche use case.

I think what you actually want is where bounds that can assert that two types have the same size, so the callers have to provide that info

**Comment by scottmcm** [comment]
I agree this isn't a bug.  I expect that anything that happens in this direction will happen as part of https://github.com/rust-lang/project-safe-transmute -- which will probably include various "still `unsafe`, but more checked" features.

**Comment by oli-obk** [comment]
I'm going to close this issue as I think it's not actionable presently
