### ISSUE TITLE
`EncodeWide` should implement `FusedIterator`

### ISSUE THREAD

**Issue by AronParker** [rust-lang/rust#96368]
[`EncodeWide`](https://doc.rust-lang.org/std/os/windows/ffi/struct.EncodeWide.html) iterates over `Wtf8CodePoints` (which point to a slice of bytes in memory). When the code points expire (no more bytes available in the slice), there is no chance of the iterator ever returning more `u16` values. Therefore, `EncodeWide` should implement `FusedIterator`.

**Comment by ChrisDenton** [comment]
It is currently fused in practice and I don't think there's a good reason to change that in the future. This would technically be an API change but one that should have no negative impact to existing code.

Which is the long winded way of saying I agree.

**Comment by AronParker** [comment]
Thanks for the quick response! I realize that this is an API change but didn't feel it'd warrant a "feature suggestion". I guess for now I'm just throwing the idea out there.

**Comment by ChrisDenton** [comment]
This is a great idea and I'd be happy to see a PR that implements it. I was just ticking off a checklist. It's not a breaking change and it is useful, so implementing it should not be at all controversial.

**Comment by AronParker** [comment]
Sounds good, I'll get to it tomorrow!

@rustbot claim

**Comment by scottmcm** [comment]
Note that, procedurally, a new trait impl is insta-stable so will need a `T-libs-api` FCP.

(That's totally ok, just wanted to note it.)
