### ISSUE TITLE
`dyn XXX` had impl `Debug`, but `dyn XXX + Send` can't Debug.

### ISSUE THREAD

**Issue by rise0chen** [rust-lang/rust#96360]
I tried this code:

```rust
use std::fmt;

pub trait ConnectionDriver {
    fn name(&self) -> String;
}
impl fmt::Debug for dyn ConnectionDriver {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_fmt(format_args!("name: {}", self.name()))
    }
}

struct Wifi;
impl ConnectionDriver for Wifi {
    fn name(&self) -> String {
        String::from("wifi")
    }
}

// type C = Box<dyn ConnectionDriver>; // this can work
type C = Box<dyn ConnectionDriver + Send>; // this can't work
pub struct Connection(pub C);


fn main() {
    let conn = Connection(Box::new(Wifi));
    println!("{:?}", conn.0);
}
```

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=0dcd92866964b1210b9b7ba9d182b632

**Comment by compiler-errors** [comment]
You need to implement `Debug` for `dyn ConnectionDriver + Send`, which in this usage acts as a distinct type from `dyn ConnectionDriver`.

**Comment by compiler-errors** [comment]
I can probably implement a better error message for this, though...

**Comment by rise0chen** [comment]
I think it should auto implement `Debug` for both `dyn ConnectionDriver + Send` and `dyn ConnectionDriver + !Send`.

**Comment by rise0chen** [comment]
`impl Foo for dyn Bar + Send {}` have a High priority.
`impl Foo for dyn Bar {}` have a Low priority.
And, `dyn Bar + !Send` auto impl Foo by `impl Foo for dyn Bar {}`

**Comment by wwylele** [comment]
I think the problem here is that `dyn A+B` isn't a subset of `dyn A`. They are distinct types. This is different from trait bounds, where `T: A+B` is a subset of `T: A`. For trait bounds, we can implement something for `A` and expect it to be implemented for `A+B`; or if we want to have a different implementation for `A+B`, we have specialization for that. We probably need to overhaul the entire `dyn` type system to make it work in the way you want.

**Comment by rise0chen** [comment]
I think it is a similar problem.
```rust
#[async_trait(?Send)]
pub trait ListenerDriver {
    async fn accept(&mut self) -> Result<Connection, RecvError>;
}

#[async_trait]
impl ListenerDriver for Server {
    async fn accept(&mut self) -> Result<Connection, RecvError> {...}
}
```

```
error[E0053]: method `accept` has an incompatible type for trait
  --> unmp-link-udp\src\server.rs:86:5
   |
86 |     async fn accept(&mut self) -> Result<Connection, RecvError> {
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected trait `Future<Output = Result<unmp_link::connection::Connection, unmp_link::error::RecvError>>`, found trait `Future<Output = Result<unmp_link::connection::Connection, unmp_link::error::RecvError>> + Send`
   |
   = note: expected fn pointer `fn(&'life0 mut server::Server) -> Pin<Box<(dyn Future<Output = Result<unmp_link::connection::Connection, unmp_link::error::RecvError>> + 'async_trait)>>`
              found fn pointer `fn(&'life0 mut server::Server) -> Pin<Box<(dyn Future<Output = Result<unmp_link::connection::Connection, unmp_link::error::RecvError>> + Send + 'async_trait)>>`

For more information about this error, try `rustc --explain E0053`.
error: could not compile `unmp-link-udp` due to previous error
```

**Comment by fmease** [comment]
CC #119338 which would fix this I think.

**Comment by rise0chen** [comment]
> CC [#119338](https://github.com/rust-lang/rust/pull/119338) which would fix this I think.

It's not a same issue.

Is `dyn A+B`  a subset of `dyn A`?
`dyn A+B` should auto impl Debug, if `dyn A+B` is a subset of `dyn A` and `dyn A` had impl Debug.

**Comment by rise0chen** [comment]
```rust
    let a:&(dyn ConnectionDriver) = &*conn.0;
    println!("{:?}", a);
```
It can work by type conversion.
