### ISSUE TITLE
rustdoc: search no longer accepts `!` as part of query

### ISSUE THREAD

**Issue by jsha** [rust-lang/rust#96399]
Steps to reproduce:

1. Visit https://doc.rust-lang.org/nightly/std/string/trait.ToString.html?search=panic!

Expected result:

All versions of panic (that are macros) appear.

Actual result:

Query parse error.

Compare vs stable: https://doc.rust-lang.org/stable/std/string/trait.ToString.html?search=panic!

I think this is just a matter of accepting `!` in the eBNF grammar and also the JS-implemented parser.

Note that the results on stable include modules, which arguably they shouldn't. So as an additional feature improvement we might want to recognize `!` specially and treat as requiring that the results be macros (or specifically function-like macros?).

**Comment by GuillaumeGomez** [comment]
Good catch! I'll send a fix tomorrow.

**Comment by notriddle** [comment]
`!` on its own is not a macro. It's a primitive, and `Foo<!>` is a valid thing that should work. Sure, that's technically an unstable feature, but it makes more sense to ensure it works right now instead of trying to fix it later.

**Comment by GuillaumeGomez** [comment]
Let's consider it valid as long as it ends the ident to simplify things then. That would make `!` and `macro!` valid while erroring for `any!thing` or `!!`.

**Comment by camelid** [comment]
> Note that the results on stable include modules, which arguably they shouldn't. So as an additional feature improvement we might want to recognize ! specially and treat as requiring that the results be macros (or specifically function-like macros?).

I've been meaning to suggest this for a while, so definitely a thumbs up from me :)
