### ISSUE TITLE
Why not with<F, R>(...)->R where F: FnOnce(&staticT) -> R {...}

### ISSUE THREAD

**Issue by SKTT1Ryze** [rust-lang/rust#96418]
https://github.com/rust-lang/rust/blob/9ea4d4127fa2c7e99d31a4a8a59227c9874d61dc/library/std/src/thread/local.rs#L415-L423  

I think following is better:  
```Rust
pub fn with<F, R>(&'static self, f: F) -> R
    where
        F: FnOnce(&'static T) -> R,
    {
        self.try_with(f).expect(
            "cannot access a Thread Local Storage value \
             during or after destruction",
        )
    }
```

Also in `try_with`

**Comment by SkiFire13** [comment]
Your proposal would allow the caller to store the `&'static T` somewhere, even after the current thread has stopped and the thread local is not valid anymore. Fundamentally `'static` is the wrong lifetime there, because the lifetime of a thread is not `'static`.

**Comment by SKTT1Ryze** [comment]
> Your proposal would allow the caller to store the `&'static T` somewhere, even after the current thread has stopped and the thread local is not valid anymore. Fundamentally `'static` is the wrong lifetime there, because the lifetime of a thread is not `'static`.

Thanks for your patience.
