### ISSUE TITLE
[regression] println borrow check errors

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#96434]
* https://crater-reports.s3.amazonaws.com/beta-1.61-2/beta-2022-04-18/gh/Acrylic125.rust-tutorial/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.61-2/beta-2022-04-18/gh/DreamLarva.learn-rust/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.61-2/beta-2022-04-18/gh/Francososa.threads/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.61-2/beta-2022-04-18/gh/Jaco26.rust_chess/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.61-2/beta-2022-04-18/gh/fangerm.adventofcode2020/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.61-2/beta-2022-04-18/reg/yaap-0.0.2/log.txt

https://github.com/rust-lang/rust/pull/94868 is likely cause (cc @dtolnay)

**Comment by dtolnay** [comment]
I'll fix this.

**Comment by Mark-Simulacrum** [comment]
Fixed on beta with https://github.com/rust-lang/rust/pull/96692 and https://github.com/rust-lang/rust/pull/96490 on master. https://github.com/rust-lang/rust/pull/96455 will be a more complete change and will likely land in 1.63 (or later).
