### ISSUE TITLE
[regression] ambiguity libc/ffi/os::raw for c_ types

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#96435]
* https://crater-reports.s3.amazonaws.com/beta-1.61-2/beta-2022-04-18/reg/jimage-0.2.3/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.61-2/beta-2022-04-18/reg/snap7-rs-1.142.0/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.61-2/beta-2022-04-18/reg/jerk-0.2.2/log.txt
* https://crater-reports.s3.amazonaws.com/beta-1.61-2/beta-2022-04-18/reg/tomcrypt-0.1.0/log.txt

Introduced by https://github.com/rust-lang/rust/pull/94503, most likely, cc @joshtriplett

**Comment by petrochenkov** [comment]
One reasonable fix is to stabilize these types in `std::ffi`.
They are the same types as stable types in `std::os::raw` just exposed from a different (but also stable) location in the same crate.

(That said, glob vs glob is an acceptable breakage according to the library policy.)

**Comment by joshtriplett** [comment]
That would be a fast stabilization, but given that they're rather simple types, that seems potentially reasonable.

**Comment by Mark-Simulacrum** [comment]
If we were to stabilize, presumably we'd do that on master and back out the PR from beta? I am reluctant to backport a stabilization to fix this (particularly a fast one, as you mention).

**Comment by joshtriplett** [comment]
@Mark-Simulacrum Yeah, reverting the PR on beta seems fine for now.
