### ISSUE TITLE
doc for slice get() is not clear about negative index 

### ISSUE THREAD

**Issue by keepsimple1** [rust-lang/rust#96448]
https://github.com/rust-lang/rust/blob/082e4ca49770ebc9cb0ee616f3726a67471be8cb/library/core/src/slice/mod.rs#L318-L322

This doc for `get()` does not talk about what happens if the index is negative. Based on the existing doc, the method should return `None` as the index is out of bounds. But in reality: 

- Compile will fail if the index is const (i.e. known at compile time). 
- Will cause panic at runtime if the index is not const. 

In my opinion, it is a good design if this method always returns `None` when the index is out of bounds, including negative ones. But either the doc should clarify or the implementation should be fixed.

**Comment by SNCPlay42** [comment]
The only implementors of `SliceIndex` are `usize` and ranges of `usize`, so it's *not possible* to index a slice (or call `get`) with a negative index.

**Comment by keepsimple1** [comment]
The problem is that what `not possible` means here.  When the index is not const, rustc compiler will not reject the code. Instead, runtime will panic.  

here is the simple example in Rust playground: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=dbff291a9fe98750d3d4e5cb70314b57

**Comment by keepsimple1** [comment]
thanks for pointing out the difference between the debug build and the release build. This difference is surprising to me. I also realized that the panic was directly due to the `usize` underflow, although it impacts the `get()` interface.

**Comment by compiler-errors** [comment]
> although it impacts the `get()` interface.

Well, it equally affects any function that takes an unsized integer.

**Comment by keepsimple1** [comment]
Out of curiosity, what is the reason for different behaviors in Debug mode and Release mode regarding `usize` underflow?

**Comment by compiler-errors** [comment]
I believe this RFC explains some of the rationale: https://github.com/rust-lang/rfcs/blob/master/text/0560-integer-overflow.md

Thanks for the issue report, but I'll close this since it's clear this isn't a problem with slice method documentation.
