### ISSUE TITLE
How to get parameters when starting the program?

### ISSUE THREAD

**Issue by JesseAtSZ** [rust-lang/rust#96504]
My code looks like this:
```
fn main(){
    let mut args: Vec<OsString> = env::args_os().collect();
    println!("{:?}",args);
}

```
The startup parameter is a file path with *, which is expected to obtain the file path with *, but env:: argsos helps me convert it into a real path. What should I do to directly obtain the path with *?

**Comment by leonardo-m** [comment]
This is better asked in a users forum...
