### ISSUE TITLE
Support using different LLVM build for stage0 and stage1+ when bootstrapping

### ISSUE THREAD

**Issue by chbaker0** [rust-lang/rust#96554]
rustc can be linked against a custom LLVM build: https://github.com/rust-lang/rust/blob/master/config.toml.example#L672

My project uses its own build of LLVM and Clang. The first stage only supports code gen for the host platform, and is built as native libraries. The final stage supports all targets, but is built with LTO so the LLVM libs have bitcode.

Our Rust build is configured to use our custom LLVM build, but there's a dilemma:
* The prebuilt stage0 Rust toolchain uses an earlier version of LLVM, so it can't handle the newer bitcode in our production LLVM build
* Our first stage LLVM build can be processed by the stage0 Rust toolchain because they're native libraries, but then our Rust toolchain won't support all the targets we need

Ideally, we could link our stage0 artifacts with our first stage LLVM then link stage1+ artifacts with the final, LTO LLVM libraries. Then
* The stage1 toolchain won't have full target support, but it can handle bitcode generated by our newer LLVM revision
* The stage1+ artifacts will be linked with our production LLVM libs and will have support for all targets

What's a good way to achieve this?

My original idea was to add a new config.toml option `llvm-config-bootstrap`, like `llvm-config` but used only when building stage0 artifacts.

**Comment by the8472** [comment]
Wouldn't first building stage 0 then setting the option via environment variable and using `--keep-stage 0` get the same effect?

**Comment by Mark-Simulacrum** [comment]
> the official stage0 toolchain uses an older LLVM, so it cannot handle the newer LLVM bitcode from the LLVM libs themselves

I'm not sure I understand this - the LLVM used by the stage0 (typically beta) compiler isn't affected by the config.toml llvm options, it's not something we compile during the build.

All compilers built from source should understand the same llvm version range, so I'm not following why things don't just work if you specify your thinlto-compiled llvm. We compile the LLVM with PGO on a subset of our targets today, which involves multiple LLVM builds, and that largely works fine too - src/ci/pgo.sh.

**Comment by chbaker0** [comment]
> I'm not sure I understand this - the LLVM used by the stage0 (typically beta) compiler isn't affected by the config.toml llvm options, it's not something we compile during the build.
>
>All compilers built from source should understand the same llvm version range, so I'm not following why things don't just work if you specify your thinlto-compiled llvm. We compile the LLVM with PGO on a subset of our targets today, which involves multiple LLVM builds, and that largely works fine too - src/ci/pgo.sh.

Our LLVM libs are bootstrapped like so:
1. Build LLVM & Clang using stage 0 C++ toolchain producing stage 1 toolchain
2. Build LLVM & Clang with PGO enabled using stage 1 toolchain
3. Run stage 2 (instrumented) toolchain, collect profiling data
4. Build LLVM & Clang with thinlto enabled using stage 2 toolchain and profiling data

We take LLVM near trunk, so it's a newer version than the official Rust release uses.

rustc beta currently uses LLVM 14. Our LLVM 15 libs are themselves built from Clang 15, with thinlto enabled, so they contain LLVM 15 bitcode. rustc beta cannot handle this.

> Wouldn't first building stage 0 then setting the option via environment variable and using --keep-stage 0 get the same effect?

I suppose so, but can I set this option by environment variable?

I found this: https://github.com/rust-lang/rust/blob/beta/src/bootstrap/config.rs#L720

which seems to indicate I could use one `config.toml` for building stage0 in the first invocation, then another in the second.

Alternatively I could have two entirely separate builds.

**Comment by Mark-Simulacrum** [comment]
> rustc beta currently uses LLVM 14. Our LLVM 15 libs are themselves built from Clang 15, with thinlto enabled, so they contain LLVM 15 bitcode. rustc beta cannot handle this.

The compiler in build/x86.../stage0/bin/rustc isn't affected by any LLVM-related config.toml options, it's just an input into the bootstrap process (equivalent to the stage0 C++ toolchain, I think). If you want it to be built with a different LLVM, you'd need to obtain a compiler built with that different configuration. If you're using static.rust-lang.org binaries, then those will come with (some version of) LLVM.

The binary produced in stage1/bin/rustc (the *first* rustc built by rustbuild) is already linked against llvm-config in config.toml, so if you want to build a rustc with a newer LLVM, just specify that LLVM in config.toml. You'll still need to provide a working rustc (or let us download one from static.rust-lang.org) as the stage0/bin/rustc, but this is no different to the clang stage 0 you provide during your LLVM lib bootstrapping, so presumably is acceptable?

**Comment by chbaker0** [comment]
I think I was misleading. I don't want the stage0 _toolchain_ to be built with a different LLVM. I want the stage0 _artifacts_ to be built with a different LLVM (i.e. LLVM 15 w/o LTO), then the stage1+ _artifacts_ to be built with yet another LLVM (15 w/ LTO).

**Comment by Mark-Simulacrum** [comment]
Why do you want stage0 artifacts (i.e., stage1/bin/rustc) to be built (I assume you mean **linked**) with a non-LTOd LLVM but further stages linked against an LTO'd LLVM?

The stage0 artifacts (stage1/bin/rustc) being *built* with an LLVM you supply isn't really possible for rustbuild to affect, that's something the `rustc = ` config.toml parameter controls (i.e., the bootstrap compiler you provide).

**Comment by chbaker0** [comment]
Official stage0 (beta) toolchain: codgen backend is linked against LLVM 14

Custom LLVM LTO build: LLVM 15 built using LLVM 15, containing LLVM 15 bitcode
Custom LLVM non-LTO build: LLVM 15 built using LLVM 15, containing native code

LLVM bitcode is not generally forwards-compatible. If the official toolchain tries to read the LLVM LTO libs, it will often choke (which I've confirmed by experience). Sometimes it will work "by accident" in the same sense as sometimes you can build today's rustc nightly with yesterday's, but it's explicitly not support.

I want the final (stage 2) rustc to be linked against LTO'd LLVM. I can't simply tell bootstrap to use the LLVM LTO build since it can't read them. It's a chicken-or-egg problem. The dependency on LLVM 15 needs to be broken somehow, and the obvious way to do that is to build the stage0 artifacts using the LLVM 15 non-LTO libs.

**Comment by the8472** [comment]
> I found this: https://github.com/rust-lang/rust/blob/beta/src/bootstrap/config.rs#L720

Right, `--config` would also work.

**Comment by chbaker0** [comment]
I rewrote the issue description to be more clear.

Using a different configuration for different stages is supported?

**Comment by chbaker0** [comment]
OK, this seems to work...

First, with a `config-stage0.toml` that points to the non-LTO llvm-config:
`x.py build --stage 0 compiler/rustc --config config-stage0.toml`

Next, with a `config.toml` that points to the production llvm-config:
`x.py build --keep-stage 0 --stage 2 library/std`

test and install also work.

**Comment by jyn514** [comment]
I'm going to close this since you found a workaround; this doesn't seem common enough for us to support it as a config option.
