### ISSUE TITLE
#[repr(transparent)] in sys::windows::os_str::Slice

### ISSUE THREAD

**Issue by JanBeh** [rust-lang/rust#96577]
I noticed that the [`sys::windows::os_str::Slice`](https://github.com/rust-lang/rust/blob/013fbc61877c8b1ca964274f171bd79952247fc3/library/std/src/sys/windows/os_str.rs#L46-L49) type is *not* `repr(transparent)` while [`sys::unix::os_str::Slice`](https://github.com/rust-lang/rust/blob/master/library/std/src/sys/unix/os_str.rs#L26-L29) is. However, they are [required to have a transparent representation](https://github.com/rust-lang/rust/blob/013fbc61877c8b1ca964274f171bd79952247fc3/library/std/src/sys/windows/os_str.rs#L153-L155).

While the standard library may(?) assume they will properly transmute, it might be better to add `#[repr(transparent)]` to `sys::windows::os_str::Slice`. Possibly this affects other systems as well.

See also [this thread/post](https://users.rust-lang.org/t/what-is-asref-path-tostring/74919/9?u=jbe) on URLO.

**Comment by ChrisDenton** [comment]
Note that making the Unix version transparent was a relatively recent change (May of last year). The [reason](https://github.com/rust-lang/rust/pull/84967#discussion_r631905868) given was:

> Because `Buf` and `Slice` now no longer live in a publicly exported module they can be marked as `pub` and `repr(transparent)` as normal.
