### ISSUE TITLE
Tracking Issue for `slice_range_of` returning the `Range` of a sub-slice/str

### ISSUE THREAD

**Issue by Swatinem** [rust-lang/rust#96613]
Feature gate: `#![feature(slice_range_of)]`

This is a tracking issue for `slice/str::range_of`, which returns the `Range` of the sub-slice/str within `self`.
The resulting `Range` can be used with `get` to yield the exact same slice again, completing a roundtrip.

I originally proposed the feature here: https://internals.rust-lang.org/t/proposal-get-range-of-sub-slice/16556

### Public API

```rust
impl<T> [T] {
    pub fn range_of(&self, slice: &Self) -> Option<Range<usize>>;
}

impl str {
  pub fn range_of(&self, substr: &Self) -> Option<Range<usize>>;
}
```

### Steps / History

- [ ] Implementation: https://github.com/rust-lang/rust/pull/96612
- [ ] Final comment period (FCP)
- [ ] Stabilization PR

### Unresolved Questions

- How to deal with ZSTs? It currently panics.

**Comment by m-ou-se** [comment]
Please don't open tracking issues before the (unstable) addition has been accepted by a reviewer. Thanks!

(See also the comment at the top of the tracking issue template:

> If the new feature is small, it may be fine to skip the RFC process. In that case, you can use use `issue = "none"` in your initial implementation PR. The reviewer will ask you to open a tracking issue if they agree your feature can be added without an RFC.

)
