### ISSUE TITLE
Link.exe fatal error lnk1181 non-UTF-8 output

### ISSUE THREAD

**Issue by Petruha04** [rust-lang/rust#96620]
Can't compile "hallo world" (main.rs) :(
VS build tools 2019.
rustc --version
rustc 1.60.0 (7737e0b5c  2022-04-04)
Windows 7 x64
---
fn main() {
    println!("Hello, world!");
}
---
Screenshot:
[https://drive.google.com/file/d/1hZiVjDHa-B8755k1C3q8SoMb22y4oIi_/view?usp=sharing](https://drive.google.com/file/d/1hZiVjDHa-B8755k1C3q8SoMb22y4oIi_/view?usp=sharing)

**Comment by ChrisDenton** [comment]
[LNK1181](https://docs.microsoft.com/en-us/cpp/error-messages/tool-errors/linker-tools-error-lnk1181?view=msvc-170) means that the filename cannot be found.

In this case it looks like the missing filename is named "kernel32.lib".

Do you have the Windows SDK installed? For example, this is what you need to select in the Visual Studio Installer for the Windows 11 SDK:

![windowssdk](https://user-images.githubusercontent.com/4459874/166172981-5eb1fef6-6244-4a09-b5c3-be760a60747b.png)

Similar options exist for the Windows 10 SDK.

**Comment by Petruha04** [comment]
> 
> In this case it looks like the missing filename is named "kernel32.lib".
> 
> Do you have the Windows SDK installed? 

Thank You!
No. SDK was not installed. I will try to add it.
