### ISSUE TITLE
Standard file descriptor checks cause abort on startup with strict rlimit

### ISSUE THREAD

**Issue by QuineDot** [rust-lang/rust#96621]
### Cause

[PR 75295](https://github.com/rust-lang/rust/pull/75295) added polls to the standard file descriptors on startup; if they are closed, it attempts to reopen them to `/dev/null`.  If [`RLIMIT_NOFILE`](https://man7.org/linux/man-pages/man2/getrlimit.2.html) is too low, the polling (or opening) will cause an abort.

[Reported by @edre on URLO; diagnosed by @cuviper.](https://users.rust-lang.org/t/trivial-rust-binaries-no-longer-run-with-rlimit-nofile-0-after-rust-1-48/74775)

The `rlimit` could be checked ahead of time.

### Code

I tried this Docker configuration

```
FROM rust:1.48
RUN rustup target add x86_64-unknown-linux-musl
RUN echo 'fn main(){println!("hi");}' > hi.rs; rustc --target x86_64-unknown-linux-musl -o hi hi.rs
RUN python3 -c 'import resource,subprocess;print(subprocess.run(["/hi"],preexec_fn=lambda: resource.setrlimit(resource.RLIMIT_NOFILE, (0,0))))'
```

I expected to see this happen: Successful execution

Instead, this happened: Process aborted

### Version it worked on

It most recently worked on: Rust 1.47

### Versions with regression

Rust 1.48 and forward.

### Related issues
* https://github.com/rust-lang/rust/issues/47271
* https://github.com/rust-lang/rust/issues/88825

@rustbot modify labels: +regression-from-stable-to-stable -regression-untriaged

**Comment by the8472** [comment]
>       EINVAL The  nfds  argument  is  greater than {OPEN_MAX}, or one of the fd members refers to a
>              STREAM or multiplexer that is linked (directly or indirectly) downstream from a multi‐
>              plexer.

**Comment by m-ou-se** [comment]
We're happy to review a patch for this. (E.g. falling back to fstat if poll returns EINVAL.)
