### ISSUE TITLE
Building and testing rustc on *BSD fails on -C split-debuginfo

### ISSUE THREAD

**Issue by m-ou-se** [rust-lang/rust#96643]
`-Csplit-debuginfo` is passed on at least NetBSD and FreeBSD when testing rustc, but that results in an error saying that the option is not yet stable.

`bootstrap/builder.rs` enables unstable options on Linux and Windows, but not on other platforms:

https://github.com/rust-lang/rust/blob/879fb425960798a79042b3b2a850d1262b7a91e8/src/bootstrap/builder.rs#L1408-L1415

**Comment by luqmana** [comment]
This was fixed in https://github.com/rust-lang/rust/pull/96758
