### ISSUE TITLE
explicit_outlives_requirements lint triggers in macro-generated code

### ISSUE THREAD

**Issue by jplatte** [rust-lang/rust#96640]
This was originally a clippy issue until I noticed it's actually a builtin lint, so here's clippy's issue form filled out 😄 

### Summary

The `explicit_outlives_requirements` lint seems to fire in macro-generated code, where it would be extra work to elide these. Saw this happen in CI for Ruma: https://github.com/ruma/ruma/runs/6258852689?check_suite_focus=true

### Lint Name

explicit_outlives_requirements

### Reproducer

* Clone [Ruma](https://github.com/ruma/ruma)
* Run `cargo clippy --features client` in `crates/ruma-client-api`

### Version

```text
rustc 1.62.0-nightly (4dd8b420c 2022-05-01)
binary: rustc
commit-hash: 4dd8b420c027001e47b0d811a7e55e2fe1de1395
commit-date: 2022-05-01
host: x86_64-unknown-linux-gnu
release: 1.62.0-nightly
LLVM version: 14.0.1
```

**Comment by djkoloski** [comment]
Here's a minimized repro:

`Cargo.toml`
```toml
[dependencies]
serde = { version = "1.0", features = ["derive"] }
```

`lib.rs`
```rust
#![warn(explicit_outlives_requirements)]

use serde::Serialize;

#[derive(Serialize)]
pub struct Foo<'a> {
    #[serde(with = "stringify")]
    bar: &'a String,
}

mod stringify {
    pub fn serialize<S>(s: &String, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: serde::Serializer,
    {
        serializer.serialize_str(&s)
    }
}
```

This trips the lint on a generated bound in serde:

```rust
struct __SerializeWith<'__a, 'a: '__a> {
    values: (&'__a &'a String,),
    phantom: _serde::__private::PhantomData<Foo<'a>>,
}
```

Since the `'a: '__a` bound is technically unnecessary due to `&'__a &'a String`.
