### ISSUE TITLE
Simplify universal impl-trait collection during lowering

### ISSUE THREAD

**Issue by cjgillot** [rust-lang/rust#96644]
During lowering (`rustc_ast_lowering`), universal impl-trait are desugared to extra generic parameters to the current item, and their bounds added to the where clause.
```rust
fn foo<T>(u: impl Bar) where T: Foo
```
becomes
```rust
fn foo<T, _U>(u: _U) where T: Foo, _U: Bar
```

This is done by carrying two vectors inside `ImplTraitContext::Universal`.
These vectors are only created by `add_implicit_generics` method, and references to them are passed around.
We should prefer having them as fields in `LoweringContext`.

Instructions:
- [ ] Move the two vectors from `ImplTraitContext::Universal` to field in `LoweringContext`;
- [ ] Take and replace the values of these fields in `with_hir_id_owner`, and assert that the value after the call to `f` is empty;
- [ ] Add a `itctx: ImplTraitContext` parameter to `add_implicit_generics` and assert that these fields are empty on return if `itctxt` is not `Universal`;
- [ ] Replace all calls to `lower_generics` by calls to `add_implicit_generics`;
- [ ] Rename `add_implicit_generics` to `lower_generics`;
- [ ] Maybe inline `lower_generics_mut` into `lower_generics` (if this simplifies the logic, not sure).

Please contact me on zulip for any question.

**Comment by spastorino** [comment]
@cameron1024 I ended sending a PR for this because as I've said, I had some things already done. Please feel free to ping us on Zulip and we can find more tasks for you to work on if you want :heart:.

**Comment by cameron1024** [comment]
Ah no problem, been a busy few days so I just got round to this. I'm pretty new to zulip, is there a particular place to ask?
