### ISSUE TITLE
Lending iterator through GAT / HRTB implies unexpected lifetime despite being 'static

### ISSUE THREAD

**Issue by udoprog** [rust-lang/rust#96669]
I tried this code:

```rust
#![feature(generic_associated_types)]

trait Iterator {
    type Item<'this>: 'static where Self: 'this;
    fn next(&mut self) -> Self::Item<'_>;
}

fn not_ok<T>(mut it: T) where T: Iterator {
    let mut _out;

    loop {
        _out = it.next(); // `it` was mutably borrowed here in the previous iteration of the loop
    }
}
```

Since `next` returns an associated type with a `'static` constraint, it seems like the associated type could be assumed to not have a lifetime associated with the `Iterator` that produces it and allow the program to compile.

Instead some lifetime constraint I can't wrap my head around is present, resulting in the above error.

### Meta

`rustc --version --verbose`:
```
rustc 1.62.0-nightly (e7575f967 2022-04-14)
binary: rustc
commit-hash: e7575f9670f3c837def3d186ae09366c75c7632e
commit-date: 2022-04-14
host: x86_64-unknown-linux-gnu
release: 1.62.0-nightly
LLVM version: 14.0.0
```

</p>
</details>

**Comment by udoprog** [comment]
This is a slightly less contrived example, which is what motivated me to open this issue originally.

Whatever constraint is being applied is projected across another trait as well:

```rust
#![feature(generic_associated_types)]

trait Iterator {
    type Item<'this>: Get
    where
        Self: 'this;

    fn next(&mut self) -> Self::Item<'_>;
}

trait Get {
    type Value: 'static;

    fn get(self) -> Self::Value;
}

fn not_ok<T>(mut it: T)
where
    T: Iterator,
{
    let mut _out;

    loop {
        let item = it.next(); // `it` was mutably borrowed here in the previous iteration of the loop
        _out = item.get();
    }
}
```

**Comment by udoprog** [comment]
Repro without GATs:

```rust
trait IteratorItem<'a> {
    type Item: 'static;
}

trait Iterator: for<'a> IteratorItem<'a> {
    fn next(&mut self) -> <Self as IteratorItem<'_>>::Item;
}

fn not_ok<T>(mut it: T) where T: Iterator {
    let mut _a = it.next();
    let mut _b = it.next();
}
```

**Comment by archshift** [comment]
Any news on this? It makes lending iterators very difficult to use when loops are involved...

**Comment by traviscross** [comment]
We fixed this somewhere along the way.  These all work fine now.

[Playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&code=pub+trait+Iterator+%7B%0A++++type+Item%3C%27this%3E%3A+%27static+where+Self%3A+%27this%3B%0A++++fn+next%28%26mut+self%29+-%3E+Self%3A%3AItem%3C%27_%3E%3B%0A%7D%0A%0Apub+fn+not_ok%3CT%3E%28mut+it%3A+T%29+where+T%3A+Iterator+%7B%0A++++let+mut+_out%3B%0A%0A++++loop+%7B%0A++++++++_out+%3D+it.next%28%29%3B%0A++++%7D%0A%7D%0A%0Afn+main%28%29+%7B%7D%0A)

[Playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&code=pub+trait+Iterator+%7B%0A++++type+Item%3C%27this%3E%3A+Get%0A++++where%0A++++++++Self%3A+%27this%3B%0A%0A++++fn+next%28%26mut+self%29+-%3E+Self%3A%3AItem%3C%27_%3E%3B%0A%7D%0A%0Apub+trait+Get+%7B%0A++++type+Value%3A+%27static%3B%0A%0A++++fn+get%28self%29+-%3E+Self%3A%3AValue%3B%0A%7D%0A%0Apub+fn+not_ok%3CT%3E%28mut+it%3A+T%29%0Awhere%0A++++T%3A+Iterator%2C%0A%7B%0A++++let+mut+_out%3B%0A%0A++++loop+%7B%0A++++++++let+item+%3D+it.next%28%29%3B%0A++++++++_out+%3D+item.get%28%29%3B%0A++++%7D%0A%7D%0A%0Afn+main%28%29+%7B%7D%0A)

[Playground link](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&code=pub+trait+IteratorItem%3C%27a%3E+%7B%0A++++type+Item%3A+%27static%3B%0A%7D%0A%0Apub+trait+Iterator%3A+for%3C%27a%3E+IteratorItem%3C%27a%3E+%7B%0A++++fn+next%28%26mut+self%29+-%3E+%3CSelf+as+IteratorItem%3C%27_%3E%3E%3A%3AItem%3B%0A%7D%0A%0Apub+fn+not_ok%3CT%3E%28mut+it%3A+T%29+where+T%3A+Iterator+%7B%0A++++let+mut+_a+%3D+it.next%28%29%3B%0A++++let+mut+_b+%3D+it.next%28%29%3B%0A%7D%0A%0Afn+main%28%29+%7B%7D%0A)

Thanks to @udoprog for providing straightforward reproductions.

cc @oli-obk @compiler-errors

**Comment by udoprog** [comment]
Thanks for the follow up!

**Comment by archshift** [comment]
I guess I'm not 100% sure this is the same error, but it seems to manifest in very similar ways. Is this related?

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=c1d12691844588acfd9940aacaa6d918

**Comment by udoprog** [comment]
@archshift Since you're dealing with non-`'static` lifetimes, it's *probably* a different issue. I think your code could technically be legal if the borrow checker was smarter in how the local lifetime was dealt with in the loop. But I would emphasize that such a borrowing iterator is still very limited. It wouldn't be possible to hold onto [several items at the same time](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=0a9ab48da0048b53396e8375b19bf26e) since all of them would have to borrow exclusively from `&mut self`.

**Comment by archshift** [comment]
Oh, did some more digging and it turns out #92985 is exactly my issue.
