### ISSUE TITLE
Improve documentation of std::process::Command

### ISSUE THREAD

**Issue by roy-ganz** [rust-lang/rust#96675]
I tried to run the following bash command using `std::process:Command`:

```bash 
MYSQL_PWD=XXX mysql -u XXX -D XXX < file.sql
```
It failed at first because I can't use `<` as an argument. Instead I had to use the `stdin` method.
From the documentation that was not clear to me. 

I think the documentation should mention explicitly that redirections cannot be done with 
```rust
Command::new("mysql")
  .env("MYSQL_PWD", &password)
  .args([
      "-u",
      &user,
      "-D",
      &database,
     "<",
     &filename
  ])
```
but require
```rust
Command::new("mysql")
  .env("MYSQL_PWD", &password)
  .args([
      "-u",
      &user,
      "-D",
      &database,
   ])
   .stdin(Stdio::from(file))
```

**Comment by the8472** [comment]
[arg()](https://doc.rust-lang.org/std/process/struct.Command.html#method.arg) documentation already mentions that shell syntax does not work here.

> Note that the argument is not passed through a shell, but given literally to the program. This means that shell syntax like quotes, escaped characters, word splitting, glob patterns, substitution, etc. have no effect.

**Comment by roy-ganz** [comment]
The doc is correct. 
But in my case I did't find it helpful. As a C programmer I expected `Command` to be an equivalent of `system()`. My bad.

Your quote says what doesn't work. But the doc could maybe be improved to show _examples_ of what works.
Common use cases might be
- redirect file to stdin, redirect stdout to file
- redirect stderr to stdout (maybe)
- pipe the output of a `Command` into another `Command`

If you think that stackoverflow should be the place for examples - that's fine with me, too. Then you can close the issue.

**Comment by the8472** [comment]
The module-level documentation has IO examples: https://doc.rust-lang.org/std/process/index.html#handling-io

**Comment by roy-ganz** [comment]
You are right.
I didn't find them, but the examples are fine.
I'm closing the issue - thanks for your time.
