### ISSUE TITLE
Tracking Issue for `round_ties_even`

### ISSUE THREAD

**Issue by Jules-Bertholet** [rust-lang/rust#96710]
Feature gate: `#![feature(round_ties_even)]`

This is a tracking issue for the `round_ties_even` feature, which adds a new method to `f32` and `f64` for rounding to the nearest integer, with ties rounded to the nearest even number.

### Public API
```rust
impl f32 {
    fn round_ties_even(self) -> f32;
}

impl f64 {
    fn round_ties_even(self) -> f64;
}
```

### Steps / History

- [x] Implementation: #95317
- [ ] Final comment period (FCP)
- [ ] Stabilization PR

### Unresolved Questions

- Naming: `round_ties_even`, `round_even`, `round_to_even`, `round_banker`... many ways to paint this bikeshed
- Should the behavior of the `round` function be changed to this?
- Is it okay to use `rint` in the implementaton? (see https://github.com/rust-lang/rust/pull/95317#issuecomment-1312598887)

**Comment by EdorianDark** [comment]
Would it possible to change the behavior of ``round`` to one of these functions or would that be a breaking change?
That would fix bugs like [55107](https://github.com/rust-lang/rust/issues/55107).

**Comment by Miksel12** [comment]
I think `round` should be changed to round ties to even, both [x86](https://xem.github.io/minix86/manual/intel-x86-and-64-manual-vol1/o_7281d5ea06a5b67a-102.html) and [ARM](https://developer.arm.com/documentation/dui0475/k/floating-point-support/ieee-754-arithmetic-and-rounding) use it as the default rounding mode and [IEEE 754](https://irem.univ-reunion.fr/IMG/pdf/ieee-754-2008.pdf) states it should be the default. It is also the mode with the least amount of bias.
As for round ties away from zero, which is the current mode used for `round`, it is actually not required by IEEE 754 for binary representation and is thus not implemented by ARM and x86. Which makes the current `round` pretty slow: https://github.com/rust-lang/rust/issues/55107. 
I don't know why round ties away from zero was chosen but it is pretty clear it is the wrong default. 
If round was to be changed to ties to even, than the four rounding modes (round, ceil, floor and trunc) would match the required IEEE rounding modes and the rounding implemented by x86 and ARM (and probably most other ISA's, though [RISC-V](https://five-embeddev.com/riscv-isa-manual/latest/f.html#floating-point-control-and-status-register) supports round ties away from zero).

**Comment by ajtribick** [comment]
From the perspective of maintaining a crate that implements a custom floating point type that tries to provide a similar API to the built-in `f32`/`f64`, I'd be somewhat against changing `round` from its documented behavior at this point (although I'd agree it isn't ideal as a choice for the default round function). It might also be worth getting some opinion from the `num` folks on this as they have also implemented `round` on their rational number types as rounding ties away from zero, similarly the documentation of `round` on the `Float`/`FloatCore` in `num_traits`.

My suspicion for why away-from-zero was chosen is that it matches how `round` is specified to operate in C (and similarly `std::round` in C++), e.g. [N1570](https://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf) section 7.12.9.6:

> The `round` functions round their argument to the nearest integer value in floating-point format, rounding halfway cases away from zero, regardless of the current rounding direction.

I definitely think having a function with the round ties to even mode should be available though. My preference would be `round_ties_even` over `round_even` (because to me the latter sounds more like rounding to an even number), but it's not a particularly strong preference there.

**Comment by tgross35** [comment]
Could this do something like use `roundeven` when available but fallback to `rint` when it isn't?

**Comment by tjallingt** [comment]
I hope this is appropriate/helpful, I would like this feature stabilized so I will attempt a [stabilization report](https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#write-a-stabilization-report).
I can also make a stabilization PR but it seems FCP should happen before that.

# Request for Stabilization

I think the `round_ties_even` methods should be stabilized in version **[1.77.0](https://releases.rs/docs/1.77.0)** (beta on 2 February, stable on 21 March).

## Summary

The `round_ties_even` feature will be stabilized wich adds the following methods to `std`:

```rs
impl f32 {
    fn round_ties_even(self) -> f32;
}

impl f64 {
    fn round_ties_even(self) -> f64;
}
```

## Documentation

Both methods have been documented in the `std` rustdoc
- https://doc.rust-lang.org/std/primitive.f32.html#method.round_ties_even
- https://doc.rust-lang.org/std/primitive.f64.html#method.round_ties_even

## Unresolved questions

The following questions are still unresolved:

1. Naming: round_ties_even, round_even, round_to_even, round_banker... many ways to paint this bikeshed
2. Should the behavior of the round function be changed to this?
3. Is it okay to use rint in the implementaton? (see https://github.com/rust-lang/rust/pull/95317#issuecomment-1312598887)

I will try to answer these questions

### 1. Naming

No further comments have been made about the naming of these method. `round_ties_even` seems to be a clear, descriptive name for this functionality placing it close to `round` in the docs to ensure it will be discoverable.

### 2. Changing `round`

While the default behaviour of `round` is not ideal it seems to be consistent with C and C++. Changing the behaviour of `round` would likely be a difficult and lengthy process and would involve adding `round_ties_zero` methods (I believe). This could be done as a followup to stabilizing `round_ties_even` if desired but, in my opinion, should not block the stabilization of this feature given that this rounding mode is currently not available in Rusts standard library.

### 3. Use `rint` 

 > Not only does Rust assume the default rounding mode, so do the LLVM floating-point intrinsics that back it.

[source](https://github.com/rust-lang/rust/pull/95317#issuecomment-1312615935)

> As you said though, Rust already assumes the default rounding mode, so it doesn't matter too much. I think roundeven is the "more correct" choice to use but it's not well supported so it's OK to just use rint for now. Ideally we should support both in libm.

[source](https://github.com/rust-lang/libm/pull/272)

From these comments it appears that using `rint` poses no immediate problems. Rust already assumes the default rounding mode is used. It seems safe to extend that assumption to `round_ties_even`.

There does seem to be agreement that `roundeven` should be preferred once it is well supported.
I don't have enough knowledge to say for sure but; it seems likely that chaning from using `rint` to `roundeven` should be backwards compatible and therefore should not block the stabilization of this feature.

**Comment by tjallingt** [comment]
I'm not sure the previous post will be seen by anyone without a ping/mention.
I hope it is okay to mention you @m-ou-se I hope I'm following the right process 😅

**Comment by RalfJung** [comment]
I've nominated this for libs-api discussion, so the team should take a look as part of their triage.

> I don't have enough knowledge to say for sure but; it seems likely that chaning from using rint to roundeven should be backwards compatible and therefore should not block the stabilization of this feature.

Correct; as far as Rust is concerned, these two are equivalent.

**Comment by RalfJung** [comment]
Regarding the point of changing `round`, note that today `round` is consistent with float-to-int casts. That also seems like an argument against changing it.

**Comment by Amanieu** [comment]
We discussed this in the libs-api meeting today. This function exposes the last IEEE 754 [rounding mode](https://en.wikipedia.org/wiki/IEEE_754#Rounding_rules) that isn't yet accessible through other functions on floats.

We decided against changing the behavior of the existing `round` method: this would be a breaking change, and round-ties-to-even is not the obvious behavior that most people would expect.

@rfcbot fcp merge

**Comment by kalcutter** [comment]
> We decided against changing the behavior of the existing `round` method: this would be a breaking change, and round-ties-to-even is not the obvious behavior that most people would expect.

What do you claim to be the "obvious" behavior that people should expect? Round-ties-to-even is the default IEEE-754 rounding mode and is used by Python which is the most popular programming language by some metrics. Other popular languages like Javascript and C++ do not even agree on how negative numbers should be rounded.

Would it be possible to change the behavior of `round` starting with the 2024 edition?

**Comment by Jules-Bertholet** [comment]
Rounding ties away from zero is the rounding method that's generally taught in primary school, due to its simplicity (it only ever needs to consider 1 digit).

**Comment by parasyte** [comment]
While rounding away from zero is what I learned in elementary school, I don't think that what young children are taught is generally what people (engineers) would expect.

**Comment by RalfJung** [comment]
> While rounding away from zero is what I learned in elementary school, I don't think that what young children are taught is generally what people (engineers) would expect.

In m totally representative survey of 2 CS PhD students, neither of them knew why "round ties to even" would be preferable over "round away from zero". I think it's not just elementary school children that are surprised by the seemingly unnecessarily complicated "ties to even" semantics.

**Comment by TennyZhuang** [comment]
Changing the behavior of `round` is definitely dangerous even across the edition boundaries. Users may focus on the compilation failure, but not the runtime breaking change.

If it’s better to change the function to correct behavior, I propose to fully remove `round` function in edition 2024, and introduce `round_ties_zero` instead. This can be easily fixed automatically.

We can introduce `round` back in edition 2027, since I believe no crate will upgrade across three editions.
