### ISSUE TITLE
Print to stderr consistently in bootstrap

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#96712]
Bootstrap is unfortunately quite inconsistent about which it uses currently :(
```
$ rg -g '!build.rs' println src/bootstrap/ | grep -v eprintln | wc -l
88
$ rg eprintln src/bootstrap/ | wc -l
60
```

stderr probably makes more sense? but I don't know when someone would look at just stdout or just stderr; having a hard time imagining use cases.

cc @bjorn3

_Originally posted by @jyn514 in https://github.com/rust-lang/rust/pull/96687#discussion_r864989431_

**Comment by jyn514** [comment]
Sure, seems fine.

@rustbot label +E-easy +A-rustbuild

**Comment by lionellloh** [comment]
@raiyansayeed are you still working on this?

**Comment by raiyansayeed** [comment]
Hey yes I'm still working on it, have most of it implemented I think. I just haven't gotten the time to review my code / push, although I think I should be able to do it by the end of this week.

**Comment by jyn514** [comment]
Looks like this was done in https://github.com/rust-lang/rust/pull/97411, thanks!
