### ISSUE TITLE
const generics: inline consts and closures cause cycle errors

### ISSUE THREAD

**Issue by lcnr** [rust-lang/rust#96728]
```rust
fn foo<const N: usize>() {}

fn main() {
    foo::<{
        let _ = || 4;
        4
    }>();
}
```
and
```rust
#![feature(inline_const)]
fn foo<const N: usize>() {}

fn main() {
    foo::<{ const { 4 } }>();
}
```
both result in cycle errors but should compile.
The reason for this is explored in https://hackmd.io/@rust-const-generics/Bk5GHW-Iq

**Comment by nbdd0121** [comment]
I did some more experiments and am now very confused by the situation:
```rust
#![feature(generic_const_exprs)]
#![feature(inline_const)]
#![allow(incomplete_features)]

struct Foo;

impl Foo {
    fn foo<const N: usize>(&self) {

    }
}

fn bar<const N: usize>() {

}

struct Baz<const N: usize>;

impl<const N: usize> Baz<N> {
    const V: usize = N;
}

// This is a different kind of cycle that I don't understand.
impl Baz::<{let _ = || 4; 4}> {
}

fn main() {
    // A cycle caused by the second match arm of opt_const_param_of
    let _ = Foo.foo::<{let _ = || 4; 4}>();
    // A cycle caused by the third match arm of opt_const_param_of
    // a forced check `let _tables = tcx.typeck(..)` (type_of.rs:137)
    let _ = bar::<{const {1}}>();
    // Allowed, hit the first match arm of opt_const_param_of, which doesn't do typeck
    let _ = Baz::<{const {1}}>::V;
}
```

Some questions: why does the third match arm of `opt_const_param_of` force a typeck, but not the first match arm? I think we should only need info from typeck if for the type dependent case?

**Comment by lcnr** [comment]
I added `let _tables = tcx.typeck(..)` to detect cycles while implementing `WithOptConstParam` and before the stabilization of `min_const_generics`. The first match arm was added later and didn't include that check. I don't think there's any intention behind that difference.

I don't actually get why `type X = Baz::<{ 3 }>` doesn't cause issues, considering that we're calling `typeck` for `type X` here which doesn't really make sense. Should look into what exactly is happening here.

The cycle for `impl Baz::<{let _ = || 4; 4}> {}` is really weird and I have no idea why we have to prove `ConstEvaluatable` inside of the constant here :sweat_smile: That one is probably a separate bug. Can you open an issue for that or are you interested in fixing it?

**Comment by fmease** [comment]
The snippets from the issue description now compile successfully and no longer cause any cycle errors but the snippet in https://github.com/rust-lang/rust/issues/96728#issuecomment-1120055799 still causes a cycle error.

Still, I'm closing this as completed. Feel free to reopen this though if you disagree with my assessment.
