### ISSUE TITLE
Invalid conflict between trait impls

### ISSUE THREAD

**Issue by eds-collabora** [rust-lang/rust#96743]
I tried this code:

```rust
trait Trait1<A, B> {}

trait Trait2<A, B> {}

struct MyLocalStruct;

impl<B, T> Trait1<MyLocalStruct, B> for T
where
    T: Trait2<MyLocalStruct, B>
{}

impl<B, T> Trait1<MyLocalStruct, B> for Vec<T>
where
    T: Trait1<MyLocalStruct, B>
{}
```

I expected to see this happen: 

Here these implementations do not conflict as I understand it, and not for any particularly subtle reason. Rust prohibits implementations of foreign traits for foreign types according to the nomenclature of [RFC 2541](https://github.com/rust-lang/rfcs/blob/master/text/2451-re-rebalancing-coherence.md). Now both `Trait1<MyLocalStruct,B>` and `Trait2<MyLocalStruct,B>` are local traits in this crate and in no other according to the rules outlined there (specifically, for a foreign trait to be considered local, it must have generic parameters, and the first generic parameter must be local - since `MyLocalStruct` is local to this crate, there can be no other crates in which these traits are local with these parameters).

Instead, this happened: 

```
error[E0119]: conflicting implementations of trait `Trait1<MyLocalStruct, _>` for type `std::vec::Vec<_>`
--> src/main.rs:12:1
|
7  | / impl<B, T> Trait1<MyLocalStruct, B> for T
8  | | where
9  | |     T: Trait2<MyLocalStruct, B>
10 | | {}
| |__- first implementation here
11 |
12 | / impl<B, T> Trait1<MyLocalStruct, B> for Vec<T>
13 | | where
14 | |     T: Trait1<MyLocalStruct, B>
15 | | {}
| |__^ conflicting implementation for `std::vec::Vec<_>`
|
= note: downstream crates may implement trait `Trait2<MyLocalStruct, _>` for type `std::vec::Vec<_>`
```
Note that the "note" at the very least is incorrect according to my understanding: No downstream crate can implement `Trait2<MyLocalStruct, _>` for `std::vec::Vec<_>`, because that is a foreign trait on a foreign type everywhere except the standard library and this crate.

Note also that removing the `B` parameter makes rustc accept this code, even though according to my understanding of the RFC 2541 rules these two cases should be indistinguishable. 

### Meta

`rustc --version --verbose`:
```
rustc 1.60.0 (7737e0b5c 2022-04-04)
binary: rustc
commit-hash: 7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c
commit-date: 2022-04-04
host: x86_64-unknown-linux-gnu
release: 1.60.0
LLVM version: 14.0.0
```
The behaviour of nightly is identical, with nightly:
```
rustc 1.62.0-nightly (4c60a0ea5 2022-05-04)
binary: rustc
commit-hash: 4c60a0ea5b2385d7400df9db1ad04e96f2a4c154
commit-date: 2022-05-04
host: x86_64-unknown-linux-gnu
release: 1.62.0-nightly
LLVM version: 14.0.1
```

**Comment by zirconium-n** [comment]
Just for the record. You can write `impl Trait2<MyLocalStruct, Foo> for Vec<Foo> {}` if `Trait2` and `MyLocalStruct` are both public.

**Comment by eds-collabora** [comment]
Thanks for pointing this out. I read, and re-read RFC 2541, but I hadn't understood it properly. So the key part of the current behaviour that I had missed is that only _uncovered_ type parameters are prohibited before the first local type, in order for the trait to be considered local. The original RFC 1023 wording prohibited all non-local types from being in those positions, but the new wording does not, as you pointed out! 

Sadly, one unfortunate consequence of this different model is that it is now impossible to construct the thing I wanted. In my proc macros, it's convenient to construct a singly generic trait (each "things which can be applied to an R"), and you get one of those traits per use of the macro. In the partner crate for the proc macro itself, I was hoping to define the families, and then provide blanket impls based on the individual crate traits.

So e.g. each use of the proc macro creates a set of impls around a trait like
```rust
trait MyTraitForThisType<T> {}
```
which I was hoping to actually write as
```rust
trait MyTrait<ThisType, T> {}
```
so that in the partner to the proc macro's crate I could write things like
```rust
impl<T,U,V> SomeOtherTrait for T where
T: MyTrait<U, V>
{}
```
Some of that works, but the inability to isolate the individual subtraits (because `trait MyTrait<ThisType, T>` is not the same as `trait MyTraitForThisType<T>` in terms of what impls are permitted) is unfortunate. It would have worked under RFC 1023.

Anyway, closing this. Thanks for your help. I thought the motivation might be useful for someone.
