### ISSUE TITLE
Autogenerate config.toml.example from `src/bootstrap/config.rs`

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#96755]
Right now, it's quite easy for fields in config.toml.example to get out of date, and even easier for the documentation to get outdated.
It would be great to autogenerate it from config.rs so that it's forced to be in sync. As a bonus, we could move the documentation to doc-comments so that people working on bootstrap itself can easily read it.

@rustbot label +C-enhancement +A-rustbuild +E-medium

**Comment by gimbles** [comment]
Sorry, what does "out of date" mean in this context?

**Comment by jyn514** [comment]
@gimbles Say someone adds a new `Build` field in config.rs. That immediately lets you start using it under `[build]` in config.toml. But nothing actually enforces that you also add the field to config.toml.example, so it's possible to get a PR merged with a completely undocumented option. I'd like to make that statically impossible.

Another, more rare issue, is to rename or remove an option, but not update it in config.toml.example - those are easier to catch because people copy the example file to config.toml fairly often. (I think ./configure might actually use it as a template? In that case it might even be tested in CI already.)

**Comment by jyn514** [comment]
> It would be great to autogenerate it from config.rs so that it's forced to be in sync.

We can do this with serde_toml by deriving Serialize.

**Comment by aganders3** [comment]
I'm interested to claim and take this on but may need some guidance/mentoring.

Looking at the files, the important documentation in `config.toml.example` is in the comments but I don't think there's a way to include comments by deriving `Serialize`. This does seem like useful feature but generalizing would make it a much bigger project (it has been asked but deemed out of scope on a number of serde/serde-* crates).

Any other thoughts on how this could be achieved? dtolnay suggested in https://github.com/serde-rs/serde/issues/1430 that it could be accomplished with Syn but I need to do some reading to figure out how that would work.

**Comment by aganders3** [comment]
Well bummer - maybe I'll still explore this as an experiment in writing proc-macros, but I understand the tradeoff being out of scope here. I'll poke around for other E-easy/E-medium issues to work on.

Thanks!
