### ISSUE TITLE
Hidden type for `impl Trait` captures lifetime that does not appear in bounds

### ISSUE THREAD

**Issue by c410-f3r** [rust-lang/rust#96771]
```
rustc 1.62.0-nightly (30f386087 2022-05-05)
```

Yet another problem related to `'static` and `async` but this time `impl Trait` is involved somehow. Funny enough, the error goes away when the number of arguments is decreased to 2 instead of 3.

```rust
// Try removing one argument to successfully compile
async fn foo(
  a: &'static i32,
  b: &i32,
  c: &i32,
) -> Option<&'static i32> {
  None
}
```

It is worth noting that a different error arises when the return is not `'static`.

**Comment by aliemjay** [comment]
This is #63033.

A workaround exists that shouldn't change the semantics of the function:
```rust
async fn foo<'a>(
  a: &'static i32,
  b: &'a i32,
  c: &'a i32,
) -> Option<&'static i32> {
  None
}
```

@rustbot label T-compiler A-async-await

**Comment by c410-f3r** [comment]
Oh, this is indeed #63033. I could swear the error message was different, bad.

Closing as duplicated but the the successful compilation of 2 or less arguments is still a bit strange
