### ISSUE TITLE
`trace_macros` does not work properly if it in a file behind `include!()`

### ISSUE THREAD

**Issue by Wandalen** [rust-lang/rust#96817]
Is that known bug?

**Comment by gimbles** [comment]
Hey @Wandalen! 👋🏻 

Can you please provide additional information so we could have a clearer understanding of what you mean, Thanks!

**Comment by Wandalen** [comment]
Sure. I will write a MRE.

**Comment by Wandalen** [comment]
Bug happen on some combination of `include!()` and `trace macros!()`.
`trace macros!()` does not show its output at some circumstances.
Unfortunately I can't reproduce the bug :(
