### ISSUE TITLE
x.py clippy no longer works?

### ISSUE THREAD

**Issue by matthiaskrgr** [rust-lang/rust#96826]
I used to be able to `x.py check ; x.py clippy` but clippy no longer displays any warning? :confused: 

````
at 22:58:42 ❯ ./x.py clippy
Updating only changed submodules
  Submodules updated in 0.01 seconds
Building rustbuild
    Finished dev [unoptimized] target(s) in 0.20s
Build completed successfully in 0:00:00
````

**Comment by Mark-Simulacrum** [comment]
cc @jyn514 

Might be related to https://github.com/rust-lang/rust/pull/96003/files#diff-6e3c7e8b58a9a198adc885bced48fff2c5fd9a1ee126ccce52166476a536807fR631 -- but that seems like an older change that would've probably been noticed by now.

**Comment by Mark-Simulacrum** [comment]
Yeah, I suspect Clippy and Fix should not have been moved to the dummy no-op block there. I'm not seeing special handling for them other than in check.rs, so it seems reasonable to assume they should be threaded into the check steps.

**Comment by matthiaskrgr** [comment]
can confirm that https://github.com/rust-lang/rust/pull/96003 broke it :/

**Comment by Mark-Simulacrum** [comment]
Happy to r+ a PR fixing this - I think it should be a matter of moving the Clippy and Fix kinds back to the check arm of that match.
