### ISSUE TITLE
GAT lifetime bound error when using Self::Associated<'a> but works when the associated type is written out.

### ISSUE THREAD

**Issue by wishawa** [rust-lang/rust#96831]
### I tried this code
[playground link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=44c33b66ae0efe73409bcf1de3cb7b2c)

<details><summary>also pasted here</summary>

```rust
#![feature(generic_associated_types)]

use std::cell::RefCell;

trait Visitable {
    type Value<'x>
    where
        Self: 'x;
    fn visit<F>(&self, visitor: F)
    where
        F: for<'x> FnOnce(Self::Value<'x>);
}

struct Source<T> {
    value: RefCell<T>,
}

impl<T> Visitable for Source<T> {
    type Value<'x> = &'x T where Self: 'x;
    fn visit<F>(&self, visitor: F)
    where
        F: for<'x> FnOnce(Self::Value<'x>), // FAILS (F: FnOnce(Self::Value<'_>) also fails)
        // F: for<'x> FnOnce(&'x T), // WORKS (F: FnOnce(&'_ T) also works)
    {
        let borrow = self.value.borrow();
        visitor(&*borrow)
    }
}
```

</details>

### I expected to see this happen
The code compiles fine.

### Instead, this happened
The code does not compile. Error E0311.

### Workaround
Writing out the associated type (as done on line 23 in the playground), makes the code compile.

### Meta

`rustc --version --verbose`:
```
rustc 1.62.0-nightly (77652b9ef 2022-05-06)
binary: rustc
commit-hash: 77652b9ef3fc98e2df0e260efedb80aa68c08c06
commit-date: 2022-05-06
host: x86_64-unknown-linux-gnu
release: 1.62.0-nightly
LLVM version: 14.0.1
```

**Comment by aliemjay** [comment]
This is the same as #96465. I've documented the workaround of writing the associated type explicitly there. @wishawa you may want to close this to avoid duplicate issues.

@rustbot label T-compiler F-generic_associated_types A-lifetimes A-associated-items
