### ISSUE TITLE
rustc overwrites read-only files on Linux

### ISSUE THREAD

**Issue by catamorphism** [rust-lang/rust#9687]
At least on Linux, as per an experiment performed by @kmcallister -  https://pastebin.mozilla.org/3184582 - rustc will happily overwrite a read-only file if the specified output file is read-only.

On Mac OS, the same experiment will fail; rustc will error out because it can't write to the output. I believe the same is true on Windows. I don't know about FreeBSD.

I think that the behavior should be consistent across platforms, and that the behavior should probably be to refuse to overwrite a read-only file.

**Comment by steveklabnik** [comment]
This pastebin is gone, and so we can't know if this was fixed or not. @catamorphism  if you have a reproduction, please let me know!
