### ISSUE TITLE
Missing comma when defaulting fields on a struct

### ISSUE THREAD

**Issue by gilescope** [rust-lang/rust#96871]
Context: You have an existing struct which has some fields defaulted. If you add another field but forget the comma like this:
```
struct A {
    field1: String,
    field2: String
    ..default()
}
```
Then currently rustc complains about a range. Here's a snapshot of an actual example:
![image](https://user-images.githubusercontent.com/803976/167439660-a7102bcd-5c62-4767-a298-d19b290c7efa.png)

It could be a legitimate range problem but in that situation it might very well be a missing comma.

**Comment by pierwill** [comment]
Was able to reproduce this without using `default`:

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=9af9adb8be6e768517f2893a7cb8dad4

**Comment by pierwill** [comment]
Looks like maybe a fix could be implemented in [`parse_pat_fields`](https://github.com/pierwill/rust/blob/d4c364347ce65cf083d4419195b8232440928d4d/compiler/rustc_parse/src/parser/pat.rs#L913), which has logic for handling commas and dots (`..`,`...`).

**Comment by pierwill** [comment]
However, there's also this:

https://github.com/rust-lang/rust/blob/d4c364347ce65cf083d4419195b8232440928d4d/compiler/rustc_typeck/src/check/expr.rs#L1691-L1694

**Comment by pierwill** [comment]
Using nightly in the playground example above, the slightly confusing error that mentions `Range` is followed by

```
error[[E0063]](https://doc.rust-lang.org/nightly/error-index.html#E0063): missing fields `n1` and `n2` in initializer of `A`
  [--> src/main.rs:11:13
](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021#)   |
11 |     let x = A {
   |             ^ missing `n1` and `n2`
   |
help: to set the remaining fields from `x`, separate the last named field with a comma
   |
13 |         field2: String::from("yo"),
   |                                   +
```

This is spot on.

There is arguably room for improvement here, but if this change from stable to nightly is improvement enough (and I think it is), I'm inclined to have this closed.  @gilescope @estebank

**Comment by gilescope** [comment]
Yeah can’t ask for much more than that. Looking good.

**Comment by estebank** [comment]
> There is arguably room for improvement here, but if this change from stable to nightly is improvement enough (and I think it is), I'm inclined to have this closed.

I'm ok with closing as is, but would love it if you're still interested in looking into finding a way to improve this if we could silence the type mismatch error when encountering this case and only emit the later one that has the suggestion.

**Comment by pierwill** [comment]
> finding a way to... silence the type mismatch error

I'll give this a look. 👍

**Comment by estebank** [comment]
Current output:

```
error[E0308]: mismatched types
  --> src/main.rs:14:11
   |
14 |         ..x
   |           ^ expected `String`, found `A`

error[E0063]: missing fields `n1` and `n2` in initializer of `A`
  --> src/main.rs:11:13
   |
11 |     let x = A {
   |             ^ missing `n1` and `n2`
   |
note: this expression may have been misinterpreted as a `..` range expression
  --> src/main.rs:13:17
   |
13 |         field2: String::from("yo")
   |                 ^^^^^^^^^^^^^^^^^^ this expression does not end in a comma...
14 |         ..x
   |         ^^^ ... so this is interpreted as a `..` range expression, instead of functional record update syntax
help: to set the remaining fields from `x`, separate the last named field with a comma
   |
13 |         field2: String::from("yo"), 
   |                                   +
```

I'm gonna close as is.
