### ISSUE TITLE
Incorrect operation of vec::as_mut_slice() with binary read

### ISSUE THREAD

**Issue by alexpyattaev** [rust-lang/rust#96915]
I think there is an issue with implementation of vec::as_mut_slice()
[Here in the docs](https://doc.rust-lang.org/stable/std/vec/struct.Vec.html#method.as_mut_slice) it is suggested that as_mut_slice() can be used to read data into a vec from an IO reader. So, below example should happily read a bunch of bytes from stdin, and print them out to stdout as byte vectors.  

```rust    
    let mut buf:Vec<u8> = Vec::with_capacity(512);
    stdin_lock.read(buf.as_mut_slice());

```
Now, actually running this will read nothing into buf, and will not produce errors or warnings. 
The reason this is happening is subtle - buf has capacity, but once it is converted into a slice, that slice is actually empty. For this reason, nothing gets read.

**Comment by sfackler** [comment]
You are creating a vec of zero *length* but a *capacity* of 512 in the first example. `as_mut_slice` returns an empty slice when called on an empty vec.

**Comment by alexpyattaev** [comment]
Yes, ended up figuring this out myself as well. Took me way longer than it should though =(

**Comment by alexpyattaev** [comment]
To avoid people stumbling into this trap, the docs could probably give an example like this to emphasize the possible trap 
```rust
   let mut buf:Vec<u8> = Vec::with_capacity(size);
    buf.resize(size, 0);
   std::io::stdin().read_exact(buf.as_mutable_slice());
```
