### ISSUE TITLE
Mixing crates using different panic modes may introduce UB if a non-Rust unwind "escapes" into panic=abort crate via "C-unwind"

### ISSUE THREAD

**Issue by BatmanAoD** [rust-lang/rust#96926]
This is a case of undefined behavior around unwinding that will not be fixed by the stabilization of the `"C-unwind"` ABI.

Suppose there exists a C++ library with this function:

```c++
void cpp_unwind() {
    throw "gotcha";
}
```

If this function is compiled as part of a crate with `panic=unwind`:

```rust
extern "C-unwind" {
    cpp_unwind()
}

pub fn unwinds() { unsafe { cpp_unwind() } }
```

...and then called from a crate compiled with `panic=abort`, the behavior is undefined, because the calling function will be compiled with the assumption that unwinding is impossible.

Note:

* If `cpp_unwind` is declared with `extern "C"`, the behavior will be well-defined: the runtime will abort even if `panic=unwind` is used.
* Cargo does not support mixing panic modes like this, so this situation is only possible by invoking `rustc` directly (or via a different build system).
* The unwind must originate outside of Rust, because only one `panic!()` implementation will be linked in the final binary, so using `panic=abort` will prevent `panic!()` from unwinding the stack in the first place.

**Comment by BatmanAoD** [comment]
There is a draft for a fix here: https://github.com/rust-lang/rust/pull/86801

**Comment by RalfJung** [comment]
> The unwind must originate outside of Rust, because only one panic!() implementation will be linked in the final binary, so using panic=abort will prevent panic!() from unwinding the stack in the first place.

Ah, that would indeed make it impossible to even trigger this in Miri, let alone detect it.

marking this as unsound for now, but I guess the alternative would be to say that *if* you are linking with external code that unwinds, it is your responsibility to ensure that *all* crates are compiled appropriately (and cargo will take care of that automatically).

Do we even want to support mixed panics modes, given cargo doesn't and they can be unsound and are generally rather subtle? Could we have rsutc warn against or even error in case panic modes are mixed?

**Comment by RalfJung** [comment]
Also see the [Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/210922-project-ffi-unwind/topic/soundness.20in.20mixed.20panic.20mode).

**Comment by apiraino** [comment]
Assigning priority as discussed in the [Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2396926.20Crates.20using.20different.20panic.20modes.20may.20introduce.20UB.20.E2.80.A6) of the Prioritization Working Group.

@rustbot label -I-prioritize +P-high
