### ISSUE TITLE
build/bootstrap/debug/rustc -vV throws error with env 

### ISSUE THREAD

**Issue by vinay110974** [rust-lang/rust#96945]
Hi,

We are implementing Oe-Selftest for rust in Yocto Framework.
The test runs complete rust testsuite for all folders.
However, we are facing an issue while printing the verbose details in many testcases.
It is hindering the test process and unable to run many folders. 

```
$oe-selftest/build-st/tmp/work/core2-64-poky-linux/
rust-testsuite/1.60.0-r0/rustc-1.60.0-src/build/bootstrap/debug/rustc -vV

thread 'main' panicked at 'RUSTC_SYSROOT was not set', src/bootstrap/bin/rustc.rs:50:48
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
```
Same issue is observed with rust native build also. 
It was noted that the issue has been addressed earlier as:- https://github.com/rust-lang/rust/pull/39888

Can you please let us know whether the issue still persists in rust or we missing anything 
while building rust that addresses the issue?

Regards,
Vinay

**Comment by vinay110974** [comment]
Hi @ehuss, 

Thanks for quick reply. 
build/x86_64-unknown-linux-gnu/stage1/bin/rustc -vV gives the expected output.
```
rustc 1.60.0-dev
binary: rustc
commit-hash: unknown
commit-date: unknown
host: x86_64-unknown-linux-gnu
release: 1.60.0-dev
LLVM version: 14.0.0
```
Will check with rust test-suite and update.

**Comment by jyn514** [comment]
Going to close this since using the fake rustc shim directly isn't supported.
