### ISSUE TITLE
Suggestion: Provide FloorEntry and CeilEntry method for BTreeMap and BTreeSet 

### ISSUE THREAD

**Issue by Ai-Zixun** [rust-lang/rust#96963]
I am wondering if the Rust core team has any plan to add `FloorEntry` and `CeilEntry` to the rust `BTreeMap` and `BTreeSet` in the standard library? 

Coming from Java, I found that both the `FloorEntry` and `CeilEntry` in the `NavigableMap<K, V> `interface in the Java standard library when using a sorted map/set.

* FloorEntry: Returns a key-value mapping associated with the greatest key less than or equal to the given key, or null if there is no such key.
* CeilEntry: Returns a key-value mapping associated with the least key greater than or equal to the given key, or null if there is no such key.  

In rust, we can use `range<T, R>` to create a `Range<'_, T>` that implements the `core::iter::traits::double_ended::DoubleEndedIterator` trait to get the Floor Entry and the Ceil Entry. Nevertheless, that seems to be a more costly approach than traversing the sorted B-Tree to get the corresponding entries directly in O(B * log(N)) time.

We can get the floor and the ceil entries with the following code in rust: 
 * FloorEntry: `map.range(..=key).next_back().unwrap();`
* CeilEntry: `map.range(key..).next().unwrap();`

**Comment by leonardo-m** [comment]
What are some use cases of floor_entry and ceil_entry?

**Comment by Ai-Zixun** [comment]
> What are some use cases of floor_entry and ceil_entry?

Essentially the floor_entry and ceil_entry would allow the user to use BTreeMap and BTreeSet as a Binary Search Tree. When the user is trying to find an entry, the user can get the exact entry or the entries right next to it.

**Comment by the8472** [comment]
> Nevertheless, that seems to be a more costly approach than traversing the sorted B-Tree to get the corresponding entries directly in O(B * log(N)) time.

A half-open ascending iterator only needs to find the ceil entry when taking its first element, so I don't see how that's more expensive than a hypothetical ceil entry method. And any subsequence elements are cheaper to obtain since you don't have to walk down the tree anymore, only sideways, so it's a more powerful building block.

**Comment by Ai-Zixun** [comment]
> A half-open ascending iterator only needs to find the ceil entry when taking its first element, so I don't see how that's more expensive than a hypothetical ceil entry method. And any subsequence elements are cheaper to obtain since you don't have to walk down the tree anymore, only sideways, so it's a more powerful building block.

Ahhh, I see. I misunderstood how `range` and `LeafRange` work with BTreeMap. In this case, yes, I agree that directly using range would be a more powerful approach.
