### ISSUE TITLE
ANSI escape breaks right to left Strings

### ISSUE THREAD

**Issue by Araxeus** [rust-lang/rust#97020]
I tried this code:

```rust
fn main() {
    let input = String::from("שלום");

    // ok (no color)
    for ch in input.chars() {
        print!("{}", ch);
    } println!();

    // ok (same color)
    for ch in input.chars() {
        print!("{}", color(ch));
    } println!();

    // not ok (mixed colors)
    for (i, ch) in input.chars().into_iter().enumerate() {
        print!("{}", if i % 2 == 0 { color(ch) } else { color2(ch) });
    } println!();
}

fn color(ch: char) -> String {
    format!("\x1b[93m{}\x1b[0m", ch)
}

fn color2(ch: char) -> String {
    format!("\x1b[96m{}\x1b[0m", ch)
}
```

I expected to see this happen:
- String order is preserved even if inside different ANSI escapes

Instead, this happened:
- when ANSI codes are mixed, the right to left order is mixed up
  ![image](https://user-images.githubusercontent.com/78568641/168320483-b788acc9-2f94-422d-8e6d-a6b5a9d261c4.png)

### Meta

`rustc --version --verbose`:
```
rustc 1.60.0 (7737e0b5c 2022-04-04)
binary: rustc
commit-hash: 7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c
commit-date: 2022-04-04
host: x86_64-pc-windows-msvc
release: 1.60.0
LLVM version: 14.0.0
```

**Comment by wwylele** [comment]
I don't think this has anything to do with rust. Rust doesn't interpret the ANSI escape sequence, and simply put them to stdout as-is. It is the terminal that interprets these sequence. This issue should be opened to the terminal implementer

**Comment by Araxeus** [comment]
You're right, after some more testing it happens from other sources too

Sadly both cmd and Powershell have this behavior

@wwylele out of curiosity, if you try the code above in bash does it work correctly?

**Comment by ehuss** [comment]
If you are interested, I would also recommend commenting on https://github.com/microsoft/terminal/issues/538 about how ANSI codes interfere with the bidi algorithm.

**Comment by Araxeus** [comment]
Thanks, I just left a short comment there
