### ISSUE TITLE
Allow `-A`, `-W` and `-D` in `x.py clippy` arguments

### ISSUE THREAD

**Issue by Milo123459** [rust-lang/rust#97059]
Currently, you cannot pass those CLI flags to `x.py clippy`. It would be useful if this was possible.

**Comment by matthiaskrgr** [comment]
you can add them to the `args` vec in `src/bootstrap/check.rs:46`, that will work temporarily

**Comment by Milo123459** [comment]
Ah, thanks for letting me know. I still think that allowing support for these flags is a good idea though.
