### ISSUE TITLE
Synchronous Windows stdin pipes broke tokio

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#97124]
It was reported in https://github.com/tokio-rs/tokio/issues/4670 that `tokio::process::Command` broke between `nightly-2022-04-29` and `nightly-2022-04-30` on Windows. According to the tokio authors that struct is a wrapper over the standard library's `std::process::Command`. Looking at the PRs between those two nightlies the likely cause seems https://github.com/rust-lang/rust/pull/96441, as it touches pipes on the affected platform.

**Comment by pietroalbini** [comment]
We also hit this in https://github.com/rust-lang/rust/pull/97088#issuecomment-1129239243 when bumping RLS (which depends on tokio). @Mark-Simulacrum is going to revert this in the upcoming beta, and post a revert PR for master soon.

**Comment by Mark-Simulacrum** [comment]
Posted master revert (#97127) and added it to https://github.com/rust-lang/rust/pull/97088 (targeting 1.62) as well.

**Comment by m-ou-se** [comment]
As I posted on https://github.com/tokio-rs/tokio/issues/4670#issuecomment-1129666326:

> It's unfortunate that libraries depend on the child process pipes being asynchronous ones, since that wasn't a documented promise in `std`. It seems we have two ways forward:
> 
>   1. Document that the `.as_raw_handle()` from a `std::process::ChildStd{in,out,err}` is always an asynchronous pipe on Windows. This means `std` has to spawn a thread to copy over data from the async pipe into a new sync pipe when the pipe is given to another `Command`. Or:
> 
>   2. Document that we don't provide that guarantee, and wait for existing libraries to adapt before changing the actual implementation a few releases later.
> 
> 
> For 2, we could add something like a `.async_pipes(true)` to `std::os::windows::process::CommandExt` so there's a way to explicitly request async pipes.

**Comment by dtolnay** [comment]
Closing in favor of keeping discussion about the path forward in https://github.com/tokio-rs/tokio/issues/4670 + https://github.com/rust-lang/rust/pull/97149 + https://github.com/rust-lang/rust/pull/97150.
