### ISSUE TITLE
Unnecessary Clone constraint requirement for associate type

### ISSUE THREAD

**Issue by bombless** [rust-lang/rust#97165]
Example:
```rust
trait Foo {
    type Assoc;
}
#[derive(Clone)]
struct Bar<T: Foo>(T::Assoc);

struct Buz;

impl Foo for Buz {
    type Assoc = ();
}


fn main() {
    let _x = Bar::<Buz>(()).clone();
}
```

It says
```
15 |     let _x = Bar::<Buz>(()).clone();
   |                             ^^^^^ method cannot be called on `Bar<Buz>` due to unsatisfied trait bounds
```
but it is not really necessary , since it actually require `Buz::Assoc : Clone`.

Is this intended behavior?

I believe this can be improved on derive-clone attribute implementation.

playground https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=82c1c2d13bd1dcf1ab517f3ff1ca940e

**Comment by agausmann** [comment]
See #26925

**Comment by bombless** [comment]
> See #26925, there are a lot of related issues with derive bounds.
> 
> This case could probably be detected & fixed within derive macros, but the problem is much larger than just this case. The more general & correct solution (generating bounds for each generic field type) doesn't work because it may leak private types/traits and implementation details, and derives (and macros in general) don't have enough information to understand that, let alone solve it.

Thank you for your important information and nice explanation!

Then I guess this issue is a dup and I'm closing it.
