### ISSUE TITLE
Missing entry for 1.61.0 in RELEASES.md

### ISSUE THREAD

**Issue by tmfink** [rust-lang/rust#97199]
[RELEASES.md](https://github.com/rust-lang/rust/blob/c0672870491e84362f76ddecd50fa229f9b06dff/RELEASES.md) does not have an entry for `1.61.0`.

The [Announcing Rust 1.61.0](https://blog.rust-lang.org/2022/05/19/Rust-1.61.0.html) [link](https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1610-2022-05-19) refers to a heading that does not exist.

**Comment by Mark-Simulacrum** [comment]
Looks like we didn't catch one of the links - https://github.com/rust-lang/rust/blob/stable/RELEASES.md#version-1610-2022-05-19 is a working link. Happy to accept a PR to the blog to update the broken link, and the notes should merge to master soon as well.

**Comment by tmfink** [comment]
Well, it's fixed now in `master`:

https://github.com/rust-lang/rust/blob/a09d36deae2e25f2eb4a0ee5d95519042ebd66a2/RELEASES.md
