### ISSUE TITLE
[E0532] Error when using functions in patterns should give an explanation of patterns

### ISSUE THREAD

**Issue by porglezomp** [rust-lang/rust#97200]
Given the following code: [(Playground)](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=d0c78b010de0962788843dd4bbd4ca07)

```rust
fn main() {
    let (x, drop(y)) = (1, 2);
}
```

The current output is:

```
error[E0532]: expected tuple struct or tuple variant, found function `drop`
 --> src/main.rs:2:13
  |
2 |     let (x, drop(y)) = (1, 2);
  |             ^^^^ not a tuple struct or tuple variant
```

The error message should give/link to an explanation of what kinds of things are expected in patterns in general, maybe in a note.

([Filed at request of](https://twitter.com/ekuber/status/1527436099924111360) @estebank)

**Comment by Milo123459** [comment]
What should be linked? Something in Rust by Example or the Rust docs (or something else?)

**Comment by porglezomp** [comment]
@estebank would know better, but I'd expect it to link to the reference page for patterns, https://doc.rust-lang.org/reference/patterns.html

I'm slightly unsure about this because of the intimidating grammar block at the top if it's gonna end up pointing beginners to that, but it's probably the best reference for understanding all the details of patterns…

If not that, then I'd expect the Book chapter on patterns https://doc.rust-lang.org/book/ch18-00-patterns.html

**Comment by Milo123459** [comment]
I'll wait for him to respond before starting.

**Comment by compiler-errors** [comment]
@Milo123459, there are a few existing error notes that point to book chapters in the compiler, search for references to `doc.rust-lang.org/book` under the `compiler/` subdirectory. 

I can review a PR attaches such a note to some cases. You might need to be careful about only suggesting it for items that aren't valid in patterns but used incorrectly. For example, E0532 fires if you try to use a unit enum variant as a tuple enum variant. I think we only want to suggest it when we're trying to use, e.g., a function or method name as a pattern variant.

**Comment by Milo123459** [comment]
> For example, E0532 fires if you try to use a unit enum variant as a tuple enum variant. I think we only want to suggest it when we're trying to use, e.g., a function or method name as a pattern variant.
Hmm, how do we control that / know when it is only invalid?

**Comment by compiler-errors** [comment]
You should be able to check the `res` of the item?

You might need to do some experimentation -- if you can't, then feel free to just fall back to suggesting it always, but leave a FIXME.
