### ISSUE TITLE
Codegen/allocator regression from 1.60

### ISSUE THREAD

**Issue by jgouly** [rust-lang/rust#97217]
In 1.60 the following code causes no allocations:

```rust
pub fn main() -> i32 {
    let v1 = vec![5, 6, 7];
    let v1_iter = v1.iter();
    let total: i32 = v1_iter.sum();
    println!("{}",total);
    total
}
```

However in nightly there is an allocation, see: https://godbolt.org/z/cq9b1Pnva

EDIT:

Appears there is also a problem with 1.60 and opt-level 2 vs 3: https://godbolt.org/z/8MWjEvPbh

**Comment by nox** [comment]
This feels like an optim pass in LLVM was promoted from level 3 to level 2. I checked on other archs and the problem also appears.

**Comment by nox** [comment]
@lqd suspects it's related to https://github.com/rust-lang/rust/pull/94402. I checked 2022-03-01 and there is no alloc, while on 2022-03-02 the alloc comes back.

**Comment by nox** [comment]
The allocation also goes away with opt-level 3 if you pass `-C panic=abort`

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2397217.20Codegen.2Fallocator.20regression.20from.201.2E60)).

@rustbot label -I-prioritize +P-high

**Comment by pnkfelix** [comment]
T-compiler P-high review, downgrading to P-medium.

@rustbot label: -P-high +P-medium
