### ISSUE TITLE
Compiled .exe does not fill in details

### ISSUE THREAD

**Issue by wellsilver** [rust-lang/rust#97279]
I tried this code:

```rust
fn main() {
    println!("Hello, world!");
}
```

![image](https://user-images.githubusercontent.com/67511181/169699206-9c28ac1e-0fb3-4e94-bb70-7e99bba7fa5f.png)

I expected to see this happen: I expected the "details" (picture) to be filled in according to Cargo.toml

Instead, this happened: The "details" wasn't filled in

### Meta

`rustc --version --verbose`:
```
rustc 1.62.0-nightly (f1f721e64 2022-05-13)
binary: rustc
commit-hash: f1f721e64014863f41c1a386b04af04c2de25321
commit-date: 2022-05-13
host: x86_64-pc-windows-msvc
release: 1.62.0-nightly
LLVM version: 14.0.4
```
</details>

**Comment by BlaCoiso** [comment]
`rustc` does not generate Windows Resource files; you can get the behavior you described using the [`winres`](https://crates.io/crates/winres) crate

**Comment by wellsilver** [comment]
noice thanks

It would be nice if they did though
