### ISSUE TITLE
std::ptr::read linux issue

### ISSUE THREAD

**Issue by 4ldas** [rust-lang/rust#97285]
seems to core dump regardless of conditions ive tried playing around with it a bit, keep in mind ive only tried with reading external address so far but ye, works on windows  by what ive tried also

on fedora 36 with cargo 1.63.0-nightly (a4c1cd0eb 2022-05-18) rustc 1.63.0-nightly (c06728704 2022-05-19) rustup 1.24.3 (ce5817a94 2021-05-31)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.63.0-nightly (c06728704 2022-05-19)`

**Comment by ChrisDenton** [comment]
Thanks for the report! Could you provide a small example program that shows the problem you're encountering?

**Comment by 4ldas** [comment]
> Thanks for the report! Could you provide a small example program that shows the problem you're encountering?

What i for example did was made another rust program and made a loop run printing out its address & value (it was mut var and still in scope btw so dw) and then made another external program which just simply reads the address of it using std::ptr::read, it compiles but seems to core dump on the runtime

**Comment by Dylan-DPC** [comment]
Closing this issue to clear up the issue tracker. Feel free to ask in the support channels (forums, discords, etc) if you need further help with this
