### ISSUE TITLE
Make the Rustdoc Sidebar hideable, even on larger viewports

### ISSUE THREAD

**Issue by VincentWo** [rust-lang/rust#97306]
I often open the RustDoc Documentation of a crate on the left and my own code on the right. Since I don't have the biggest screen this means that a lot of the code is hard to read and requires scrolling:
<img width="729" alt="A screenshot of a RustDoc Page, showing that the size of the sidebar on the left forces the code on the right to have horizontal scroll" src="https://user-images.githubusercontent.com/11615665/169767405-798061f2-9877-4a3a-bb3e-ddc484b5c9a9.png">
I propose to show a button, similar as on the smaller viewports, that allows hiding the sidebar, which would turn this into:
<img width="729" alt="A screenshot showing the rustdoc page without the sidebar, not forcing the code to horizontal scroll" src="https://user-images.githubusercontent.com/11615665/169767896-b18faf49-065f-45b6-9cd0-7b2c3158af7b.png">
This makes the code and the docs in general much more readable and reduces visual clutter on smaller screens.

I think that it would be an improvement to also allow the hiding of the sidebar on bigger screens, though I also could understand the argument to hide the control on even bigger screens.

I am aware of #59829 and hope that the additional control that is proposed here does not add even more visual clutter, I am not an expert in this topic, I can just say that as a Person with ADHD (not dyslexia) the hidden sidebar makes the documentation much easier to digest, but I can't speak for other people. Maybe @lambda could be so kind to comment on this.

I can also create a Mockup, I just wanted to check first whether this is even an idea worth discussing.

**Comment by GuillaumeGomez** [comment]
I don't think allowing to hide the sidebar is a good idea for the general documentation as it contains important information.

What we could do is change the minimum width required to switch to "mobile mode" where the sidebar is hidden by default (because mobile devices have very few space to spare).

cc @jsha

**Comment by VincentWo** [comment]
If this is the less controversial approach than I am all for it :)

**Comment by GuillaumeGomez** [comment]
By curiosity: what's your viewport width?

**Comment by VincentWo** [comment]
Oh yes, sorry for not including it.
Using a 14' Macbook Air M1 with Firefox, so probably not the most unusual setup:
Full-Screen: 1440px
Using it on only the half: 714px

**Comment by crispinb** [comment]
> I don't think allowing to hide the sidebar is a good idea for the general documentation as it contains important information.

I've also found the sidebar horizontal dominance a bit of a problem, for the same reason as the OP. I don't think hiding the sidebar will  cause a problem as long as it's visible on first load & is easy/discoverable to retrieve (and it doesn't cause problems for similar doc browsers eg. Elixir's). A fixed width cutoff would mean that those of us using some form of window tiling would have to adjust our window manager to fit Rust docs, which seems the wrong way round (to this Rust newbie).
