### ISSUE TITLE
`x.py test tests/` doesn't work

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#97314]
If you try to do `./x.py test src/test`, it doesn't work:

```
./x.py test --stage 1 src/test/ --bless
Updating only changed submodules
  Submodules updated in 0.01 seconds
Building rustbuild
    Finished dev [unoptimized] target(s) in 0.14s
error: no `test` rules matched 'src/test/'
help: run `x.py test --help --verbose` to show a list of available paths
note: if you are adding a new Step to bootstrap itself, make sure you register it with `describe!`
Build completed unsuccessfully in 0:00:00
``` 

Same goes for `x.py test compiler` and `x.py test library`.

@rustbot label A-rustbuild

**Comment by RalfJung** [comment]
Why did you expect these to work?
The following should work: `./x.py test src/test/ui`, `./x.py test library/core`. I think currently this is by design.

Or is this a feature request to make  `./x.py test src/test` basically `./x.py test src/test/*`?

**Comment by est31** [comment]
Yeah it's a feature request. I filed it upon invitation of @jyn514 after he asked about pain points of bootstrap : https://rust-lang.zulipchat.com/#narrow/stream/122651-general/topic/pain.20points.20of.20bootstrap/near/283314219

**Comment by est31** [comment]
> Or is this a feature request to make ./x.py test src/test basically ./x.py test src/test/*?

Yeah this exactly.

**Comment by est31** [comment]
Update: still doesn't work today (now with the tests/ dir).
