### ISSUE TITLE
Crater runs for 1.62

### ISSUE THREAD

**Issue by pietroalbini** [rust-lang/rust#97324]
Note: Please do not conduct triage on these runs without discussing how to do so with a release team member first. Thanks!

**Comment by pietroalbini** [comment]
@craterbot run name=beta-1.62-1 start=1.61.0 end=beta-2022-05-20 mode=build-and-test cap-lints=warn p=1

**Comment by Mark-Simulacrum** [comment]
* https://github.com/rust-lang/rust/issues/97607
* https://github.com/rust-lang/rust/issues/97608

Didn't yet go through the test-failed regressions; those usually have pretty low signal-to-noise ratio though and there are also a lot of them to triage.
