### ISSUE TITLE
`must_not_suspend` lint regression with `-Zdrop-tracking`

### ISSUE THREAD

**Issue by eholk** [rust-lang/rust#97333]
The test case `src/test/ui/lint/must_not_suspend/ref.rs` fails when `-Zdrop-tracking` is enabled.

We are not recognizing the `Umm` type as held across a borrow. Here's the revelant code from the test:
https://github.com/rust-lang/rust/blob/7f997f589f4e0b1c59a3680e7a8dd941d3ada518/src/test/ui/lint/must_not_suspend/ref.rs#L17-L25

In a way, that's correct. We aren't holding `Umm` across the borrow, we are holding `&mut Umm`. The question is whether this should trigger the lint? If not, we need some way to annotate `&mut Umm` as also not being able to be held across the borrow.

It looks like in `check_must_not_suspend_ty`, we already recurse through a few types, so maybe we should look through references too?

**Comment by eholk** [comment]
@guswynn - What do you think is the right behavior here?

**Comment by guswynn** [comment]
@eholk this was always an issue with `must_not_suspend`: how deep do we recurse into types to check. I think the conclusion was that the cases covered by the existing tests were adequate? I think its just `T`, `Box<T>, and references?

**Comment by eholk** [comment]
I'm spending some time looking at this one again this afternoon to see if it's still an issue after @jyn514's changes. It seems like yes, although we aren't getting duplicate warnings now, we're just getting now warnings. I think seeing through references is probably the right option, but I'm getting kind of lost between the different PRs I have open so I'm going to rebase some things and figure out where we're at.

**Comment by jyn514** [comment]
Sounds good :) @eholk let me know if there's any way I can help, I've been repeatedly running into places at work that would be fixed by drop tracking haha

**Comment by eholk** [comment]
This should be fixed as of #97962!
