### ISSUE TITLE
Having a variable in scope affects macro invocation parsing

### ISSUE THREAD

**Issue by kballard** [rust-lang/rust#9737]
This is really weird. If I have a macro that expects a particular alphabetic token, and I define a variable with that same token, the macro suddenly stops parsing.

Macro in question:

```
macro_rules! f!((v: $x:expr) => ( println!("{:?}", $x) ))
```

I can invoke it like

```
f!(v: 3);
```

and it will work just fine. But the following blows up:

```
let v = 5;
f!(v: 3);
//~^ error: No rules expected the token: v
```

**Comment by pnkfelix** [comment]
if this gets fixed by 1.0, great.  But it doesn't block the release

also, if there is a fix that can be shown to not break any existing code, then this would be classified as "just as bug" and thus such a fix could be landed post 1.0.

P-high, not 1.0.

**Comment by TimNN** [comment]
I believe this is fixed as the following runs without errors on playpen stable:

```rust
macro_rules! f((v: $x:expr) => ( println!("{:?}", $x) ));

fn main() {
    let v = 5;
    f!(v: 3);
}
```

**Comment by jseyfried** [comment]
cc me

**Comment by pnkfelix** [comment]
The most obvious variation I could think of that *might* still exhibit the problem, namely one where the macro is defined within the same scope that binds `v`, does *not* exhibit the problem.

That is, compiles and runs:

```rust
#![allow(unused_variables)]

macro_rules! f((v: $x:expr) => ( println!("{:?}", $x) ));

fn foo() {
    macro_rules! g((v: $x:expr) => ( println!("{:?}", $x) ));
    f!(v: 3);
    g!(v: 3);
}

fn bar() {
    let v = 4;
    macro_rules! g((v: $x:expr) => ( println!("{:?} {:?}", $x, v) ));  
    let v = 5;
    f!(v: 3);
    g!(v: 3);
}

fn main() {
    foo();
    bar();
}
```

**Comment by jseyfried** [comment]
@pnkfelix agreed.

**Comment by Mark-Simulacrum** [comment]
Closing as per previous comments.
