### ISSUE TITLE
 Expect to add a smart pointer with only strong references count 

### ISSUE THREAD

**Issue by LeeHainie** [rust-lang/rust#97412]
In some cases, weak reference counting is not needed, Weak count field waste extra memory, This does not satisfy the zero-cost abstraction. Expect additional addition strong reference count smart pointer for stdlib: Sc(Strong count),Asc(Atomic strong count)

**Comment by Dylan-DPC** [comment]
Closing this as the issue is not clear and better suited as a proposal. Thanks
