### ISSUE TITLE
Atomic compare exchange shouldn't require the failure ordering to be as strong as the success ordering

### ISSUE THREAD

**Issue by m-ou-se** [rust-lang/rust#97418]
Right now, Rust does not support `compare_exchange(a, b, Acquire, Release)`: we require the success ordering to be at least as strong as the failure ordering, which means we must upgrade the success ordering to `AcqRel` in this example.

C++ proposal [P0418r2](https://wg21.link/p0418r2) argues this is unnecessary.

The restriction has been removed in C++17. We should consider doing the same in Rust.

**Comment by tmiasko** [comment]
Duplicate of #68464.

**Comment by m-ou-se** [comment]
Oh, thanks!
