### ISSUE TITLE
Complete incremental hash tracking coverage

### ISSUE THREAD

**Issue by cjgillot** [rust-lang/rust#97422]
The directory `src/test/incremental/hashes` is used to track the performance of incremental compilation granularity.

Each file is compiled 6 times with different configurations. For each run and each item, the hashes of some queries' results are computed.
If a hash stays the same from one run to the next, it is said "clean", otherwise it is "dirty".
The compiler verifies that the set of clean vs. dirty hashes corresponds to what the attributes say (`rustc_clean` annotations all over).

The weird spacing and comments is meant to stress the `incremental-relative-spans` option, which corresponds to configurations 4, 5, 6.  Those configurations should as close as possible to 1, 2, 3.

The list of checked queries is defined in `rustc_incremental::persist::dirty_clean`.

This test suite has grown a bit stale, and has not been updated with new constructs or new queries.  For instance, there is almost no impl-trait and no async.  One objective would be to eventually cover the queries that take a `LocalDefId/DefId` and that end up in metadata.

As a first step, it would be interesting to cover `mir_for_ctfe`: it is always computed and is a base for `optimized_mir`.  As MIR optimizations get better, `optimized_mir` should get cleaner and cleaner, while `mir_for_ctfe` stays the same.

This can be done by:
- adding `label_strs::mir_for_ctfe` in `rustc_incremental::persist::dirty_clean::BASE_MIR`;
- updating the tests to add `mir_for_ctfe` in the dirty list when appropriate.

Don't hesitate to add other queries that should be checked, or complete the tests with constructs that are not covered (async?).
I am available on zulip if necessary.

**Comment by Pyrromanis** [comment]
@AurelienFT are you still working on it?

**Comment by AurelienFT** [comment]
I don't have time to work on this anymore I remove my assignation.

**Comment by InfRandomness** [comment]
> I need to re-frame the description of this issue.  It is currently inexact.

👍
