### ISSUE TITLE
Show file path on suggestions when the suggestion file differs from the main label's file

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#97439]
We currently show structured suggestions without the file path because it is considered redundant output, but when the suggestion is to modify a file that isn't the local file the main diagnostic highlights, then the suggestion is confusing.

**Comment by compiler-errors** [comment]
Isn't this fixed?

**Comment by estebank** [comment]
Yes, fixed by https://github.com/rust-lang/rust/pull/97605
