### ISSUE TITLE
Define coherence restrictions in the manual impl section.

### ISSUE THREAD

**Issue by nejucomo** [rust-lang/rust#9743]
I'm familiar with coherence restrictions on trait impls only from IRC conversations ages ago.  It came up in IRC again, and I *briefly* skimmed the manual sections on impls and crates to see if this restriction was spelled out.

I may have missed it.  Even in that case, I feel it would be most useful in the manual section describing impls: [6.1.9 Implementations (v0.8 manual)](http://static.rust-lang.org/doc/0.8/rust.html#implementations)

pcwalton has a good blog post providing background: [Coherence, Modularity, and Extensibility for Typeclasses](http://pcwalton.github.io/blog/2012/05/28/coherence/)

There was some confusion on IRC as to whether coherence restrictions are per-module or per-crate.

Some questions I'd like to see answered in the manual:

* Are trait impls "always public" even when buried in non-public modules?
* Can a crate define a trait in one module, ``A``, and an impl in another module ``B`` coherently?

**Comment by steveklabnik** [comment]
I'm just going to close this in favor of that one.
