### ISSUE TITLE
cargo install in a Docker buildx image fails

### ISSUE THREAD

**Issue by Allaman** [rust-lang/rust#97520]
Hello,
I was trying to install [stylua](https://github.com/JohnnyMorganz/StyLua) via [crates.io](https://github.com/JohnnyMorganz/StyLua#from-cratesio) in a Docker [Multi platform](https://www.docker.com/blog/faster-multi-platform-builds-dockerfile-cross-compilation-guide/) image. 
However, my build always failed when building the `linux/amd64` image while the `linux/arm64` build was succesful (and running) fine.

My Host:
- MacBook Pro 2021 M1 Pro 32GB RAM
- MacOS 12.4
- Docker for Desktop 4.8.2 (79419)

Docker engine config
```json
{
  "builder": {
    "gc": {
      "defaultKeepStorage": "20GB",
      "enabled": true
    }
  },
  "experimental": false,
  "features": {
    "buildkit": true
  }
}
```

Minimal Dockerfile to illustrate my issue:

```Dockerfile
ARG ARCH
FROM ${ARCH}debian:stable-slim

ENV PATH=$PATH:/root/.cargo/bin
RUN apt-get update && apt-get -y install curl gcc
RUN curl https://sh.rustup.rs -sSf | bash -s -- -y  && cargo install stylua
```

Running `docker buildx build --platform linux/arm64 -t cargo-test . --load` and everything is as expected
<img width="1168" alt="arm64" src="https://user-images.githubusercontent.com/12184268/170875089-70d24f34-51c4-41c4-8f2c-b225988144d9.png">

Running `docker buildx build --platform linux/amd64 -t cargo-test . --load` it fails with error code 137 indicating an OOM issue
<img width="1465" alt="amd64" src="https://user-images.githubusercontent.com/12184268/170875149-53f58e2c-292e-4add-b5b4-50950f11ae29.png">

Running the same command again but with 15GB instead of previously 8GB assigned memory to Docker I get the following error:
<img width="1905" alt="amd64_2" src="https://user-images.githubusercontent.com/12184268/170875228-539561a7-f0cf-4df7-acfe-0e412cfb5daa.png">

Is there anything I am missing?

Cheers
Michael

Disclaimer: I am neither familiar with Rust nor the Rust ecosystem.

**Comment by jyn514** [comment]
@Allaman can you reproduce this outside of a docker container? What version of rust are you installing with rustup, 1.61?

**Comment by jyn514** [comment]
If you could get a stack trace of the segfault, that would be helpful - I think there's a way to get it to generate a core dump but it might be easier just to run gdb on it manually.

**Comment by Allaman** [comment]
@jyn514 
> can you reproduce this outside of a docker container?
I can successfully run `cargo install stylua` on my Manjaro system (amd64, Kernel 5.16, cargo 1.61) 
> What version of rust are you installing with rustup, 1.61?
I guess, at least the second screenshot states that (just copied the install command from [rust-lang](https://www.rust-lang.org/tools/install)

> If you could get a stack trace of the segfault
hmm, I will do some research if and how this is possible from an errored docker build

I think someone should pick my provided example Dockerfile and run the same commands as I did, so we could exclude my Host as issue

**Comment by jyn514** [comment]
@Allaman I added some caching to your dockerfile:
```docker
ARG ARCH
FROM ${ARCH}debian:stable-slim

ENV PATH=$PATH:/root/.cargo/bin
RUN apt-get update && apt-get -y install curl gcc
RUN curl https://sh.rustup.rs -sSf | bash -s -- -y
RUN cargo install empty-library || true
RUN cargo install stylua
```
When I build this locally, I can't replicate your error. So I think this is likely a docker on Mac issue and not actually related to rust itself.

**Comment by Allaman** [comment]
@jyn514 
I copied your Dockerfile and still get the same segfault error
<img width="1901" alt="error" src="https://user-images.githubusercontent.com/12184268/170882793-8475cc4a-1831-4c47-bd4c-187760385fe8.png">
 
However, I can confirm that a build on a Linux amd64 system works so I would second your assumption!

Thanks for your effort

**Comment by sfackler** [comment]
When targeting a non-native architecture, Docker will run commands via the Qemu userspace emulator. Unfortunately, that emulator is not perfect, and I think in particular has lots of problems running multithreaded programs properly.

It's also much slower than running native code, so you may want to try a multi-stage Docker build, starting by cross compiling in a native container and then just copying the binary into a container being built for your desired architecture.

**Comment by Allaman** [comment]
@sfackler I think about that approach - thanks

As this looks like a Docker Desktop on Mac issue I would close this issue

**Comment by acim** [comment]
This happens at GitHub Actions as well. I am using Buildx there and amd64 works fine, but arm64 fails in some repos with error 137.

**Comment by Allaman** [comment]
@acim I also encountered issues while building with buildx that I couldn't solve and gave up :( 
(in [this](https://github.com/Allaman/nvim/blob/main/Dockerfile) repo if you are interested)

On dedicated machines both builds, arm64 and amd64, are working fine. So in my opinion we must blame buildx 😄 

Your image is building on my arm64 (Apple Silicon) 
<img width="1149" alt="image" src="https://user-images.githubusercontent.com/12184268/172054230-cf3b6ae0-9f7b-4b6a-909d-31d3bc231efe.png">

**Comment by acim** [comment]
Yes, weird, it also works in my other repo with the same pipeline and basically the same Dockerfile. I ended up disabling arm64 build until this gets resolved. I have no real arm64 to try it myself and I am lazy to try it with Qemu on my amd64. You probably have more available memory on your dedicated build machine.

https://github.com/ectobit/vanity/runs/6517723546?check_suite_focus=true

**Comment by alisomay** [comment]
This file helped me to resolve the issue btw.
https://github.com/jdrouet/jolimail/blob/main/multiarch.Dockerfile

**Comment by dvaldivia** [comment]
I can confirm building on an x86 system I get error

```
ERROR: failed to solve: process "/dev/.buildkit_qemu_emulator /bin/sh -c mkdir src &&     echo 'fn main() {\\nprintln!(\"Hello, world!\");\\n}' > src/main.rs &&     cargo build &&     cargo clean --package $(awk '/name/ {gsub(/\"/,\"\"); print $3}' Cargo.toml | sed ':a;N;$!ba;s/\\n//g' | tr -d '\\r') &&     rm -rf src" did not complete successfully: exit code: 137
```

and when building on an arm64 system I get error

```
0.088 runc run failed: unable to start container process: error during container init: error mounting "cgroup" to rootfs at "/sys/fs/cgroup": mount cgroup:/sys/fs/cgroup/openrc (via /proc/self/fd/6), flags: 0xf, data: openrc: invalid argument
```

both times Im trying to build like
```
docker buildx build --platform linux/amd64,linux/arm64 --push -t user/app-rust .
```
