### ISSUE TITLE
rustdoc math support

### ISSUE THREAD

**Issue by mkovaxx** [rust-lang/rust#97543]
Would be nice if rustdoc supported [math expressions in Markdown the way GitHub does](https://github.blog/2022-05-19-math-support-in-markdown/).

**Comment by est31** [comment]
See #16300, #12989, #34261, and probably a bunch of more threads.

**Comment by GuillaumeGomez** [comment]
You need to use external tools to do so. Thanks @est31 for the links! :)

Closing then.
