### ISSUE TITLE
Check for stale files in `src/test/mir-opt`

### ISSUE THREAD

**Issue by JakobDegen** [rust-lang/rust#97564]
This folder currently contains a number of `inst_combine_deref*.diff` files that are completely unused - the associated `.rs` file that generated them was removed all the way back in #81101 . In addition to deleting these files, we should also add a check to compiletest that makes sure that the `mir-opt` folder contains no files that do not belong to any tests (with the exception of the readme).

@rustbot label +C-enhancement +A-test-suite +A-mir-opt

**Comment by JakobDegen** [comment]
I thought I was getting the command wrong, maybe the bot is down?

**Comment by compiler-errors** [comment]
compiler-errorsbot added them for you because rustbot is on holiday :stuck_out_tongue_closed_eyes:

**Comment by JakobDegen** [comment]
:rofl: :heart: thank you!

**Comment by ehuss** [comment]
See also #77498.

**Comment by JakobDegen** [comment]
@rustbot claim

This has bitten me once too many times now in #101428 , gonna fix it
