### ISSUE TITLE
regression: proc-macro to_string change for "invisible" delimiters

### ISSUE THREAD

**Issue by Mark-Simulacrum** [rust-lang/rust#97608]
https://crater-reports.s3.amazonaws.com/beta-1.62-1/beta-2022-05-20/gh/Patryk27.lxd-snapper/log.txt

Seems to be due to an older(?) version of indoc, possibly already fixed, but wanted to file in case there was an unintentional change on our end.

cc @dtolnay (indoc-impl author, I believe)

https://github.com/dtolnay/indoc/commit/29e8c968ca8a78beb369c25146637f1adc754132 may have been related to this as well.

**Comment by nnethercote** [comment]
cc @petrochenkov, who knows more about all this stuff than I do.

**Comment by apiraino** [comment]
Assigning priority as discussed in the [Zulip thread](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2397608.20regression.3A.20proc-macro.20tokenization.20change.20for.20liter.E2.80.A6) of the Prioritization Working Group.

@rustbot label -I-prioritize +P-medium

**Comment by nnethercote** [comment]
#97636 is open for the reversion.

**Comment by wesleywiser** [comment]
Re-opening to track the beta backport.

**Comment by pietroalbini** [comment]
Being backported in https://github.com/rust-lang/rust/pull/98440.

**Comment by workingjubilee** [comment]
This seems to have been fully resolved for now.
