### ISSUE TITLE
Rustdoc doesn't play well with `use ... as _` syntax

### ISSUE THREAD

**Issue by Veetaha** [rust-lang/rust#97615]
I tried this code:

```rust
mod ext {
    pub trait Foo {
         fn foo();
    }
    
    pub trait Bar {
        fn bar();
    }
}

pub mod prelude {
    pub use crate::ext::Foo as _;
    pub use crate::ext::Bar as _;
}
```

I expected to see this happen: there should be a way to view all the items reexported anonymously in docs. Maybe even just expose them by original names in docs.

Instead, this happened:

The traits are visible in rustodoc as a single `prelude::_`

<img width="972" alt="image" src="https://user-images.githubusercontent.com/36276403/171352742-2cdab240-c352-4c78-b23b-152d144fb110.png">

And when you click on any of `_` links you see only this:

<img width="992" alt="image" src="https://user-images.githubusercontent.com/36276403/171352700-ddac5cb9-4629-4958-95c2-325d41fd80d1.png">

Looks like `rustdoc` writes the docs for the arbitrary item reexported with `use ... as _;`

### Meta

`rustdoc --version --verbose`:
```
rustdoc --version --verbose
rustdoc 1.60.0 (7737e0b5c 2022-04-04)
binary: rustdoc
commit-hash: 7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c
commit-date: 2022-04-04
host: x86_64-unknown-linux-gnu
release: 1.60.0
LLVM version: 14.0.0
```

`rustc --version --verbose`
```
rustc 1.60.0 (7737e0b5c 2022-04-04)
binary: rustc
commit-hash: 7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c
commit-date: 2022-04-04
host: x86_64-unknown-linux-gnu
release: 1.60.0
LLVM version: 14.0.0
```

**Comment by GuillaumeGomez** [comment]
The problem is that we "inline" them. The solution could be to keep the original name (and it would be a link to the original location), but if the item is originally in a private module, then there is no link generated and we would end up with `use Trait as Whatever` where you cannot get information on the item at all (since we wouldn't generate a page for `Whatever` or for `Trait`).

I'm not really sure what would be the best course of action in here...

**Comment by Nemo157** [comment]
Is there any usecase for an anonymous reexport of a privately scoped trait? Seems like an edge case we don't need to really support.

**Comment by Veetaha** [comment]
@Nemo157 @GuillaumeGomez 

Let's not rush with not-supporting this. We in our code use this pattern extensively.

We use it to export extension traits. For example, we have a trait that provides extension traits to the standard library

```rust
mod option {
     pub OptionExt<T> { /* our methods to put on all Option types */ }
}

pub mod prelude {
    pub use OptionExt as _;
}
```

We do it this way to guarantee that the users of our extension traits crate will not be able to both:

- Provide an `impl OptionExt<T> for SomeOtherType`, i.e. make the trait sealed
- Don't expose the name of trait to have smaller API surface. We don't want the users to care about the trait name. They just have to `use crate_name::prelude::*` and that's it. We may change the name of the trait without a breaking change.

**Comment by Nemo157** [comment]
For making the trait sealed the standard pattern is to use `trait OptionExt: Sealed { ... }` with a marker sealed trait.

The latter requirement seems like an anti-pattern to me. I blanket-ban all glob imports in my projects so that would make your library unusable in them.

**Comment by Veetaha** [comment]
> For making the trait sealed the standard pattern is to use `trait OptionExt: Sealed { ... }` with a marker sealed trait (since it's just a marker it not being documented isn't an issue).

That's true, but it is not the main benefit of this patter. The trait is sealed for free when we do this.

> The latter requirement seems like an anti-pattern to me. I blanket-ban all glob imports in my projects so that would make your library unusable in them.

Clippy specifically allows configuring `wildcard_imports` lint with this ([link](https://rust-lang.github.io/rust-clippy/master/index.html#wildcard_imports)):

> warn-on-all-wildcard-imports: bool: Whether to allow certain wildcard imports (prelude, super in tests). (defaults to false)

So things like `use crate_foo::prelude::*` are allowed, and I don't see a problem with that if crate defines a consistent prelude targeted for wildcard import specifically. It's highly subjective wether you want to follow that pattern, but is a known convention used throughout the ecosystem. Let alone `std` contains a number of `prelude` modules:

- [`std::io::prelude`](https://doc.rust-lang.org/stable/std/io/prelude/index.html)
- [`std::os::unix::prelude`](https://doc.rust-lang.org/stable/std/os/unix/prelude/index.html)
- [`std::os::wasi::prelude`](https://doc.rust-lang.org/stable/std/os/wasi/prelude/index.html)
- [`std::os::windows::prelude`](https://doc.rust-lang.org/stable/std/os/windows/prelude/index.html)

**Comment by Nemo157** [comment]
> Clippy specifically allows configuring wildcard_imports lint with this

And wildcard_imports is allow-by-default anyway. I have just chosen to enable it, and I don't allow prelude imports, because I believe that results in easier to navigate code and all crates should be usable still.

> Let alone std contains a number of prelude modules

These are only re-exports of items that have other public paths. I know there are other buggy crates that force using paths like `use proptest::prelude::ProptestConfig;`, but most are well-behaved and give their items canonical locations outside the preludes.

**Comment by Nemo157** [comment]
Anyway, one approach to a fix I can think of is for rustdoc to pretend that `prelude::OptionExt` exists and the `use as _` is a reexport of it. I have no idea how to handle something like `pub use crate::{foo::OptionExt as _, bar::OptionExt as _}` though, which seems like a plausible setup.

**Comment by Veetaha** [comment]
@Nemo157 you make very good points, but `prelude` module isn't considered to be an outright discouraged pattern, but it isn't known to be as a single way to export your extension traits. We might be slightly overly strict about that though, but I believe there may be other people doing the same 🤔. 

`rustdoc` is not a critical component of the toolchain, so it doesn't have to support literally every legal use of the language. Nevertheless, I really think we should support this because the pattern I described isn't something indicative of a completely brainless crate design or unworkable code. So I suggest we resolve the question of how to implement this.

# Ideal fix

Ideally, a reexported symbol should have the additional context that indicates that it is unreachable. That sounds like a big-effort feature for `rustdoc`. Unfortunately, I have never looked at `rustdoc` source code before, so I can only theorize.

# Low-effort Fix

If we want to have a low-effort fix for this problem, we could just generate a name for the reexported symbol there prefixed with some easy-to-understand suffix that makes it obvious the symbol is unreachable. 

## Generating The Symbol Name Based On Trait Name

We could generate the name for the reexport like this for example `__unreachable_symbol__{TraitName}`. The problem with this is the case you mentioned with reexporting multiple symbols of the same name with this pattern. If it is possible to detect that several symbols collide under the same name this way, then we could add a number into the symbol name here, for example.

## Generating The Symbol Name Based On Reexport Identity
The reexport can be identified by its position in the module tree. For example, we could take the file/line/column to generate the symbol name like this `{file_name}_{line}_{column}`. However, this is problematic due to macro expansions potentially messing this up. This is where my theoretical ground is weak. Maybe we could identify the reexport in a different way to support it occurring in macro expansions? Maybe we could use a randomly-generated ID here (hello non-determinism😞), I am not really sure. Maybe we could just not support it in macro expansions, but still why not?

**Comment by lolbinarycat** [comment]
triage: seems to be an exact duplicate of #92379
