### ISSUE TITLE
E0425: Don't recommend the use of intrinsics first

### ISSUE THREAD

**Issue by dave-tucker** [rust-lang/rust#97618]
Given the following code: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=dc1180286b0a5d9e0f1dbac02ccdb7b3

```rust
fn main() {
    let sz = size_of::<usize>();
    println!("Hello, world! A usize is {}", sz);
}
```

The current output is:

```
error[[E0425]](https://doc.rust-lang.org/stable/error-index.html#E0425): cannot find function `size_of` in this scope
 --> src/main.rs:2:14
  |
2 |     let sz = size_of::<usize>();
  |              ^^^^^^^ not found in this scope
  |
help: consider importing one of these items
  |
1 | [use core::intrinsics::size_of;](https://play.rust-lang.org/#)
  |
1 | [use core::mem::size_of;](https://play.rust-lang.org/#)
  |
1 | [use memoffset::__priv::mem::size_of;](https://play.rust-lang.org/#)
  |
1 | [use pin_utils::core_reexport::intrinsics::size_of;](https://play.rust-lang.org/#)
  |
    and 3 other candidates
```

Ideally the output should look like:

```
error[[E0425]](https://doc.rust-lang.org/stable/error-index.html#E0425): cannot find function `size_of` in this scope
 --> src/main.rs:2:14
  |
2 |     let sz = size_of::<usize>();
  |              ^^^^^^^ not found in this scope
  |
help: consider importing one of these items
  |
1 | [use core::mem::size_of;](https://play.rust-lang.org/#)
  |
1 | [use core::intrinsics::size_of;](https://play.rust-lang.org/#)
 |
1 | [use memoffset::__priv::mem::size_of;](https://play.rust-lang.org/#)
  |
1 | [use pin_utils::core_reexport::intrinsics::size_of;](https://play.rust-lang.org/#)
  |
    and 3 other candidates
```

In cases where intrinsics have been stabilised in `core`|`std` it would be useful to suggest these to users first.
Especially as using intrinsics generates another `rustc` error that tells you to prefer stabilized functions in `std`.
This would hopefully make handling this error easier for new rust users coming from languages like C/C++ and looking for the equivalent of `sizeof()`

The output is the same on stable, beta and nightly

**Comment by compiler-errors** [comment]
I'd be satisfied if we filtered out intrinsics altogether except for when the `core_intrinsics` feature was enabled.

**Comment by LoganDark** [comment]
> I'd be satisfied if we filtered out intrinsics altogether except for when the `core_intrinsics` feature was enabled.

I also get quite annoyed when stable rustc recommends I use unstable features

**Comment by estebank** [comment]
Checking the DefId of each suggested path to see if they are annotated with `unstable` should be doable.

**Comment by compiler-errors** [comment]
> Checking the DefId of each suggested path

This seems to be harder than I initially thought... so since we emit this "consider importing" suggestion in `LateResolutionVisitor`, we do not have access to `TyCtxt` it seems. And I have no idea how to extract the attributes from each `Res` without `TyCtxt`... :thinking:

**Comment by estebank** [comment]
We *might* want to consider adding yet another dumping ground field in the `Res` itself or in `Resolver`... But at that point it seems like too much mem consumption for little gain. The other option is to delay the emitting of these errors until later, but that also seems... like a lot of additional complexity :-/

**Comment by compiler-errors** [comment]
For now, I guess it wouldn't hurt just to filter suggesting paths that are literally `["core", "intrinsic", ..]` (and `std::intrinsic::*`) instead of going thru all of the work of adding more info to the `Res`. I can put up a PR that does that later.
