### ISSUE TITLE
-Cpanic=abort will skip aborting landingpad for extern "C-unwind"

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rust#97659]
I tried this code:

```
$ cat > throw.cpp
extern "C" { void may_throw() { throw "foo"; } }
$ gcc -c throw.cpp -o throw.o
$ ar q libthrow.a throw.o
$ cat > catch.rs
#![feature(c_unwind)]

extern "C-unwind" {
    fn may_throw();
}

fn main() {
    unsafe { may_throw(); }
}
$ rustc +nightly catch.rs -l throw -L . -l stdc++
$ ./catch
fatal runtime error: Rust cannot catch foreign exceptions
[1]    5117 abort      ./catch
```

I expected to see this happen: It aborts at the `may_throw()` call.

Instead, this happened: It unwinds all the way to the `catch_unwind` that libstd wraps around the main function and aborts there. This happens because the personality function in libpanic_abort is a dummy personality function that doesn't interpret the LSDA to find out that there is a landingpad at the `may_throw()` call site that would abort execution. Instead tells the unwinder to continue unwinding. https://github.com/rust-lang/rust/pull/92845 would fix this issue by moving the libpanic_unwind personality function to libstd and using it for `-Cpanic=abort` too.

### Meta

`rustc --version --verbose`:
```
rustc 1.63.0-nightly (12cd71f4d 2022-06-01)
binary: rustc
commit-hash: 12cd71f4d3ea6df9c2093781d55134cd9651d754
commit-date: 2022-06-01
host: x86_64-unknown-linux-gnu
release: 1.63.0-nightly
LLVM version: 14.0.4
```

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by lopopolo** [comment]
@bjorn3 it looks like https://github.com/rust-lang/rust/pull/92845 was recently merged. Is there additional work to do here? I tried with a recent nightly I still get the fatal.

```console
$ cat > throw.cpp
extern "C" { void may_throw() { throw "foo"; } }
$ clang -c throw.cpp -o throw.o
$ ar q libthrow.a throw.o
$ cat > catch.rs
#![feature(c_unwind)]

extern "C-unwind" {
    fn may_throw();
}

fn main() {
    unsafe { may_throw(); }
}
$ rustc +nightly-2022-08-30 catch.rs -l throw -L . -l c++
$ ./catch
fatal runtime error: Rust cannot catch foreign exceptions
zsh: abort      ./catch
```

## Meta

```console
$ rustc +nightly-2022-08-30 -Vv
rustc 1.65.0-nightly (bc4b39c27 2022-08-29)
binary: rustc
commit-hash: bc4b39c271bbd36736cbf1c0a1ac23d5df38d365
commit-date: 2022-08-29
host: x86_64-apple-darwin
release: 1.65.0-nightly
LLVM version: 15.0.0
```

**Comment by bjorn3** [comment]
I forgot to pass `-Cpanic=abort` to rustc. Looks like we now emit a proper aborting landingpad. I now get

```
terminate called after throwing an instance of 'char const*'
[1]    2258 abort      ./catch
```

which seems to be due to no catch existing on the stack rather than from skipping past the aborting landingpad.
