### ISSUE TITLE
improve error message on attempt to impl on typedef

### ISSUE THREAD

**Issue by pnkfelix** [rust-lang/rust#9767]
Support for impl on typedefs was removed (IIUC) in PR #6087.

However, the current error you get for attempting to do such a thing is . . . suboptimal:

``` rust
type Board = [char, ..9];
impl Board { }
fn main() { }
```

```
% ./objdir-dbgopt/x86_64-apple-darwin/stage2/bin/rustc  /tmp/u.rs
/tmp/u.rs:2:0: 2:14 error: no base type found for inherent implementation; implement a trait or new type instead
/tmp/u.rs:2 impl Board { }
            ^~~~~~~~~~~~~~
/tmp/u.rs:2:0: 2:14 error: cannot associate methods with a type outside the crate the type is defined in; define and implement a trait or new type instead
/tmp/u.rs:2 impl Board { }
            ^~~~~~~~~~~~~~
error: aborting due to 2 previous errors
```

Or better still, maybe we could actually put in correct support for impl on typedef, which I think was part of what pcwalton was proposing in his mailing list post here: https://mail.mozilla.org/pipermail/rust-dev/2013-April/003866.html

**Comment by Ryman** [comment]
This can be closed, the following works today:

```
#[derive(Debug)]
struct MyBox<T>(Box<T>);
type FloatBox = MyBox<f32>;

impl FloatBox {
    fn new(x: f32) -> FloatBox {
        MyBox(Box::new(x))
    }
    fn bar() {
        println!("HI")
    }
}

fn main() {
    let foo = FloatBox::new(3.2);
    println!("{:?}", foo);
    FloatBox::bar()
}
```

**Comment by agrover** [comment]
@Ryman I think that's impl on a tuple struct, not an impl on a typedef?
```
type MyVec = Vec<u64>;

impl MyVec {
    fn mylen(&self) -> usize {
        self.len()
    }
}
```
doesn't work now, and it would be nice if it did IMHO. The workaround is define a trait ABC for MyVec and then impl ABC for MyVec...

**Comment by Ryman** [comment]
@agrover Well it's an impl on a typedef of a newtype(no?), but you're right that my comment is missing half the point that the issue. :dizzy_face:

**Comment by steveklabnik** [comment]
Today, this gives a much better error 

```
error[E0116]: cannot define inherent `impl` for a type outside of the crate where the type is defined
 --> <anon>:3:1
  |
3 | impl MyVec {
  | ^ impl for type defined outside of crate.
  |
  = note: define and implement a trait or new type instead
```

and given that this matches `type`'s semantics, I'm gonna give this one a close! Thanks.
