### ISSUE TITLE
[rustdoc] No Implementations for `FxHasher` 

### ISSUE THREAD

**Issue by Urgau** [rust-lang/rust#97693]
I went to https://doc.rust-lang.org/nightly/nightly-rustc/rustc_data_structures/fx/struct.FxHasher.html.

I expected to see this happen: see impl for `Default` and `Hasher`

Instead, this happened: none of the impl appears

![](https://puu.sh/J3R8s/6af85bfd5f.png)

![](https://puu.sh/J3R8B/e9eb536267.png)

@rustbot label +T-rustdoc

**Comment by fmease** [comment]
I can no longer reproduce the issue. Probably fixed relatively recently (we had some PRs touching impl collection by GuillaumeGomez and notriddle in the 6 months).
