### ISSUE TITLE
lld-wrapper failed on Darwin

### ISSUE THREAD

**Issue by tschuett** [rust-lang/rust#97755]
lld-wrapper is unhappy.

I tried this code:

```shell
 RUSTFLAGS='-Z gcc-ld=lld -C target-cpu=native' cargo +nightly run --release
```

Instead, this happened: 
```shell
 = note: lld-wrapper: -rustc-lld-flavor=<flavor> is not passed
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

```shell
... x86_64-apple-darwin/bin/gcc-ld" "-Wl,-rustc-lld-flavor=darwin ...
```

### Meta

`rustc --version --verbose`:
```
rustc +nightly --version --verbose
rustc 1.63.0-nightly (e71440575 2022-06-02)
binary: rustc
commit-hash: e71440575c930dcecac288b7c3536410d688b351
commit-date: 2022-06-02
host: x86_64-apple-darwin
release: 1.63.0-nightly
LLVM version: 14.0.4
```

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

Note that this worked for months. This is a regression for me.

**Comment by lqd** [comment]
Is this issue related to https://github.com/rust-lang/rust/pull/97375 ?

**Comment by tschuett** [comment]
I found no traces of the last working nightly.

**Comment by petrochenkov** [comment]
>Is this issue related to https://github.com/rust-lang/rust/pull/97375?

It's certainly somehow related because `-rustc-lld-flavor` didn't exist before that, but I don't know how it can happen, `-Wl,-rustc-lld-flavor=darwin` is in fact passed as snipped posted in the original message shows.

**Comment by tschuett** [comment]
```shell
"-B/Users/awesome/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/bin/gcc-ld" "-Wl,-rustc-lld-flavor=darwin"  "-L" "/Users/awsome/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib"
```

```shell
  = note: lld-wrapper: -rustc-lld-flavor=<flavor> is not passed
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

```shell
 cc --version
Apple clang version 13.1.6 (clang-1316.0.21.2.5)
Target: x86_64-apple-darwin21.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by petrochenkov** [comment]
>Do you need more information?

Yes, output of lld-wrapper with `dbg!(arg)` inserted here https://github.com/rust-lang/rust/blob/master/src/tools/lld-wrapper/src/main.rs#L67

(You don't need whole compiler build to rebuild lld-wrapper, it's a single-file standalone program, it can be built with `rustc` directly or with `cargo build`, and then temporarily put into the `gcc-ld` directory.)

**Comment by tschuett** [comment]
```shell
  = note: [src/tools/lld-wrapper/src/main.rs:73] arg = "@/var/folders/y0/n29lr9g94s12d892pb6yg3l40000gn/T/response-c2238e.txt"
          lld-wrapper: -rustc-lld-flavor=<flavor> is not passed
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
```rust
    let args = env::args_os()
        .skip(1)
        .filter(|arg| match arg.to_str().and_then(|s| s.strip_prefix("-rustc-lld-flavor=")) {
            Some(suffix) => {
                dbg!(arg);
                flavor = Some(suffix.to_string());
                return false
            }
            None => {dbg!(arg); return true},
        })
        .collect::<Vec<_>>();
```

**Comment by tschuett** [comment]
Note that main:rs73 is the failure case.

**Comment by tschuett** [comment]
I don't know whether rustc has utilities for handling response files

**Comment by petrochenkov** [comment]
Ok, it's actually clang that packs the command line into a `@file`, so we cannot control or predict when it happens.
That's pretty bad.
I guess we'll have to partially revert https://github.com/rust-lang/rust/pull/97375 and use something based on file names, like https://github.com/rust-lang/rust/issues/97402#issuecomment-1147404520.

**Comment by petrochenkov** [comment]
Fixed in https://github.com/rust-lang/rust/pull/100200.

Sorry for the delay, I should have fixed this two months ago.
@tschuett could you test the fix on Darwin?
