### ISSUE TITLE
error: unknown --json option future-incompat

### ISSUE THREAD

**Issue by ghost** [rust-lang/rust#97769]
I am trying to build my plugin but I get these errors, any ideas on how to fix it?
I also tried with old versions of rustc and cargo but nothing changes.

![1](https://user-images.githubusercontent.com/106928975/172066981-2b752119-1c78-4f31-a086-fcd8478c2a45.png)
![2](https://user-images.githubusercontent.com/106928975/172066982-fc556eb2-f431-4cc4-8262-623ed5f01a9c.png)
![3](https://user-images.githubusercontent.com/106928975/172067330-036d7b8c-3d7b-45c1-9211-b46e6497881b.png)

**Comment by jyn514** [comment]
Somehow you're using cargo 1.63 with an old version of rustc. You said "plugin" so I suspect you're linking to rustc_private - in that case, the version you're linking too needs to match the version of cargo in your toolchain.
