### ISSUE TITLE
`x build src/tools/miri` doesn't install miri as part of the built toolchain

### ISSUE THREAD

**Issue by Kixiron** [rust-lang/rust#97762]
Running `x build src/tools/miri` doesn't include miri as part of the built rust toolchain, meaning that `cargo +custom-toolchain miri` doesn't work

cc @jyn514

**Comment by WaffleLapkin** [comment]
It seems like the same thing happens to rustfmt: `x b rustfmt` doesn't include rustfmt as part of the built rust toolchain, meaning that `rustfmt +custom-toolchain` doesn't work.

**Comment by daxpedda** [comment]
The same thing applies to `cargo` and `clippy`.

**Comment by jyn514** [comment]
We need to call `add_to_sysroot` in all of these steps. I think that currently adds all libraries as well which isn't correct - someone should look into how this is done for rustdoc and do the same for the other tools.

I agree it's a bug that we don't copy these today.

**Comment by Emilgardis** [comment]
this seems related to #81431
