### ISSUE TITLE
Calling the read method of a raw pointer causes the program to exit with an error

### ISSUE THREAD

**Issue by mylvghb** [rust-lang/rust#97775]
Code:

```rust
let x = vec![0, 1, 2, 3];
let y = &x as *const Vec<i32>;
unsafe {
    println!("{:?}", y.read()); // output [0, 1, 2, 3]
}
```

Output: 

![image](https://user-images.githubusercontent.com/35945793/172084187-39201331-0ed4-4038-b962-dbaa316341fe.png)

### Meta

```
rustc 1.61.0 (fe5b13d68 2022-05-18)
binary: rustc
commit-hash: fe5b13d681f25ee6474be29d748c65adcd91f69e
commit-date: 2022-05-18
host: x86_64-pc-windows-msvc
release: 1.61.0
LLVM version: 14.0.0
```

**Comment by ChrisDenton** [comment]
I think this is dropping the `Vec` twice. See [Ownership of the Returned Value](https://doc.rust-lang.org/std/ptr/fn.read.html#ownership-of-the-returned-value).

> `read` creates a bitwise copy of `T`, regardless of whether `T` is [`Copy`](https://doc.rust-lang.org/std/marker/trait.Copy.html). If `T` is not [`Copy`](https://doc.rust-lang.org/std/marker/trait.Copy.html), using both the returned value and the value at `*src` can violate memory safety. 

So when you call `read()` you create a bitwise copy of the `Vec`. When that copy goes out of scope, the heap memory is freed. But then `x` goes out of scope and the same heap memory is freed again.

**Comment by mylvghb** [comment]
@ChrisDenton Thanks!

**Comment by mylvghb** [comment]
@ChrisDenton When I assign to a variable, it's Ok. Why?

Code: 

``` rust
let x = vec![0, 1, 2, 3];
let y = &x as *const Vec<i32>;
unsafe {
    let z = y.read();
    println!("{:?}", z); // output [0, 1, 2, 3]
}
```

Output:

![image](https://user-images.githubusercontent.com/35945793/172089078-9cb7059e-3d51-42fe-ac9e-6651681a4208.png)

**Comment by ChrisDenton** [comment]
I would assume that you're just lucky here. A double drop is Undefined Behavior, which means anything can happen. And "anything" includes working as without error.
