### ISSUE TITLE
BSOD when installing on WSL2

### ISSUE THREAD

**Issue by Sinan-Karakaya** [rust-lang/rust#97796]
Description:
Windows 11 BSOD with system_memory_management error while installing rustc using this command : 
`curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh`

How to reproduce:
Just launch this command in Ubuntu 20.04 for WSL2 and choose the default installation, then wait a few seconds.

In the end, rustc seems to be corrupted and wasn't able to compile a hello world file.
Re-launching that command told me rust was installed, but it still couldn't compile any file, since no binary was created.

![image](https://user-images.githubusercontent.com/91690021/172164255-e34bc383-449f-4d18-827c-5c40e7960bb8.png)

**Comment by wwylele** [comment]
Is this the same as https://github.com/rust-lang/rust/issues/96245?

**Comment by nagisa** [comment]
Sorry, broken operating systems are not a rustc bug.
