### ISSUE TITLE
Unhelpful error message with identifiers named `box`

### ISSUE THREAD

**Issue by rstk** [rust-lang/rust#97810]
The following code, which won't compile because of (edited: ~#49733~) #29641 
```rust
fn main() {
    let box = Box::new(1);
}
```
yields an unhelpful error message:
```
error: expected pattern, found `=`
 --> src/main.rs:2:13
  |
2 |     let box = Box::new(1);
  |             ^ expected pattern
```
Particularly confusing if your text editor doesn't highlight `box`! It would be nicer to show some help proposing to rename the variable.

**Comment by ChayimFriedman2** [comment]
This can be done for any reserved word, not just `box`.

@rustbot claim

**Comment by est31** [comment]
@rstk FTR you linked to the wrong issue, you should have linked to #29641, as it's a box *pattern* not a box *expression* in the case of your snippet.
