### ISSUE TITLE
Windows: Dynamically loaded functions may not be loaded before user pre-main initializers

### ISSUE THREAD

**Issue by ChrisDenton** [rust-lang/rust#97814]
first reported at https://github.com/estk/log4rs/issues/263 and https://github.com/mmastrac/rust-ctor/issues/219

## The Problem

On Windows, code can run functions before main by using special link sections. Placing function pointers in `.CRT$XCU` allows the runtime to find and call the functions before it calls `main()`. [More info](https://docs.microsoft.com/en-us/cpp/c-runtime-library/crt-initialization?view=msvc-160).

User code can take advantage of this to do pre-main initializations. However, the standard library also uses this mechanism to dynamically load some essential functions on startup. This can be a problem because there is no guaranteed order to functions placed in `.CRT$XCU`. So initializers in the std may be run before, after or in between those created by user code. If a user's initializer happens to be run before the initializer that loads an essential function, it will act as though that function failed to load. This can cause errors or a panic.

## Possible solutions

* Load delayed imports using C initializers instead of C++ initializers. These C initializers will be run first.
* Use the `.CRT$XCT` section as this will ensure functions run before those in the `.CRT$XCU` section. However, "the names .CRT$XCT and .CRT$XCV aren't used by either the compiler or the CRT library right now, but there's no guarantee that they'll remain unused in the future". [Source](https://docs.microsoft.com/en-us/cpp/c-runtime-library/crt-initialization?view=msvc-160#linker-features-for-initialization). I'm not sure it would matter if they were used for something as we don't rely on any features of the C or C++ runtimes when dynamically loading functions.

**Comment by CodesInChaos** [comment]
Doesn't such user code violate the "no life before main" principle and is thus unsupported?

**Comment by ChrisDenton** [comment]
This has now been implemented. The init function is now placed in [`$XCT`](https://github.com/rust-lang/rust/blob/5633798af6f1326aa575d85a5ae155f88afb6010/library/std/src/sys/windows/compat.rs#L42) which will run before user code in `$XCU`. There is also appropriate documentation to explain this.

Furthermore, most functions are now loaded lazily instead of pre-main, only `WaitOnAddress` and `WakeByAddress` remain. Once we have a target that has Windows 8 as its minimum requirement then we could turn these into normal imports.
