### ISSUE TITLE
Suggestion: Add ExitCodeExt for Windows

### ISSUE THREAD

**Issue by AronParker** [rust-lang/rust#97914]
I welcome the newly stabilized `ExitCode` which allows Termination with an exit code.

I am facing some difficulties using it on Windows however, most programs on Windows if they use the exit code at all return an `HRESULT` or `DWORD`, neither of which are constructible from the current only available impl `From<u8> for ExitCode`. Right now I resort to using pointers to access the internals of `ExitCode` on Windows, which is undesirable. I suggest adding the following windows-specific trait:

```rust
impl From<i32> for ExitCode {
    fn from(code: i32) -> Self { ... }
}
```

Alternatively, a trait named `ExitCodeExt` could also be added for Windows which allows generation of i32 based error codes.

**Comment by eggyal** [comment]
I think this is already understood/desired (see https://github.com/rust-lang/rust/pull/93445#issue-1117891580) but what's been stabilised so far is an MVP?

**Comment by eggyal** [comment]
See also https://github.com/rust-lang/rust/pull/93840#issue-1129209143 (emphasis added):

> Custom exit codes: We resolved this by adding `From<u8> for ExitCode`. We choose to only support u8 initially because it is the least common denominator between the sets of exit codes supported by our current platforms. **In the future we anticipate adding platform specific extension traits to ExitCode for constructors from larger or negative numbers, as needed.**

**Comment by AronParker** [comment]
> See also [#93840 (comment)](https://github.com/rust-lang/rust/pull/93840#issue-1129209143) (emphasis added):
> 
> > Custom exit codes: We resolved this by adding `From<u8> for ExitCode`. We choose to only support u8 initially because it is the least common denominator between the sets of exit codes supported by our current platforms. **In the future we anticipate adding platform specific extension traits to ExitCode for constructors from larger or negative numbers, as needed.**

Thank you! That comment is a very nice find, I wrote a pull request and referenced that comment.
