### ISSUE TITLE
Rustdocs directly link to doc.rust-lang.org, breaking offline docs

### ISSUE THREAD

**Issue by aedoq** [rust-lang/rust#97918]
The docs for the standard library often link to other rust documentation items, like the reference or "Rust by Example". However, most/many of these links link to the versions hosted at [doc.rust-lang.org](https://doc.rust-lang.org). This causes problems when browsing a version of the docs hosted somewhere else, for instance the offline version installed via rustup. In that case, the linked version is also hardcoded and might not even match the one of the offline docs.
[Example (`core::arch::asm`)](https://doc.rust-lang.org/core/arch/macro.asm.html)

Some pages will link to the docs on the same host, [like the one for the keyword `pub`](https://doc.rust-lang.org/std/keyword.pub.html).

There are currently about 1044 matches for `doc.rust-lang.org` in `.rustup/toolchains/stable-x86_64-unknown-linux-gnu/share/doc/rust/html`:
```
$ grep -Frc "doc.rust-lang.org" . --exclude="print.html" | cut -d: -f2 | awk 'BEGIN{c=0} {c+=$0} END{print c}'
1044
```

**Comment by ehuss** [comment]
I have considered adding a post-processing step in the docs building that makes the links relative, but that can be difficult. There may be some cases where it really wants to intentionally link to the live site. It would also need to be smart about the channel link (like https://doc.rust-lang.org/nightly/… vs https://doc.rust-lang.org/stable/… vs https://doc.rust-lang.org/1.60/… etc.). I'm not sure how to handle those. It could leave any channel-specific links alone, and convert everything else rooted at https://doc.rust-lang.org/.  However, I think there was an issue where rustdoc would create links to https://doc.rust-lang.org/nightly/… quite frequently, I'm not sure if that has been mostly solved.

**Comment by GuillaumeGomez** [comment]
If it's not "rustdoc generated resources", it makes sense to link to the website in my opinion as we cannot be sure that the resource actually exists locally. However, a lot of doc links use `doc.rust-lang.org` links whereas they should use either intra doc links or relative links. I'll send a PR for these cases.

**Comment by GuillaumeGomez** [comment]
I opened https://github.com/rust-lang/rust/pull/97940. It seems like there is only one link in the public API that was not relative. There is another one in `fmt` private API so I don't think it's worth it to change it.

**Comment by Dylan-DPC** [comment]
Closing this issue as the above linked pr and the issue seems to be fixed
