### ISSUE TITLE
Rustdoc displays private internals of associated constants (regression)

### ISSUE THREAD

**Issue by dtolnay** [rust-lang/rust#97933]
```rust
pub struct Struct {
    private: (),
}

impl Struct {
    pub const CONST: Self = Struct { private: () };
}
```

<br>

### Correct:

<img width="300" src="https://user-images.githubusercontent.com/1940490/172968557-6f9c81bf-5d60-4280-8242-8a5fffefaeda.png">

<br>

### Incorrect:

<img width="300" src="https://user-images.githubusercontent.com/1940490/172968565-2f68b309-d3f6-40e0-b067-5c481aa7ca08.png">

<br>

I used the following script to bisect:

```bash
#!/bin/bash
cargo doc && ! rg private: $CARGO_TARGET_DIR/doc/repro/struct.Struct.html >/dev/null
```

```console
cargo-bisect-rustc --script ./bisect.sh
```

It bisects to nightly-2022-04-14 and specifically https://github.com/rust-lang/rust/pull/95990, of which https://github.com/rust-lang/rust/pull/95316 seems the most relevant because it involves associated constants in rustdoc. @fmease @notriddle @GuillaumeGomez

**Comment by fmease** [comment]
#95316 is indeed the cause. More specifically the following line: https://github.com/rust-lang/rust/blob/3dea0033f7f40fc3a96b728cb2095da91135f0a4/src/librustdoc/html/render/mod.rs#L715.

If we “fail” to evaluate (“failure” also includes “the constant is a struct”) the const value of a provided associated const with `.value()`, fall back to `.expr()` which prints the constant in raw uncensored form **including structs with their private fields**.

I assume in the non-associated const version (shown below) the call to `.expr()` does not happen and if `.value()` fails in such a case, neither the value nor the `=` is being printed.

```rust
pub struct Struct { private: () }
pub const CONST: Struct = Struct { private: () };
```

**Note that I haven't verified all those pieces of information yet, I am going to check them very soon**.

I am not sure how to proceed @GuillaumeGomez. This is another instance of constant-printing for provided assoc consts being problematic. Previous incident: Performance (https://github.com/rust-lang/rust/pull/95316#issuecomment-1129012790).

**Comment by GuillaumeGomez** [comment]
Maybe we could update the `.expr()` method so that it can only show the public items to fulfill our need?

**Comment by fmease** [comment]
The ideal solution (non-hotfix) would be to generally improve the printing of constants. [I already talked about it on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/266220-rustdoc/topic/private.20fields.20in.20associated.20constants/near/282801784). Not sure how easy it is to implement though.

**Comment by fmease** [comment]
I might as well try. If successful, my PR needs backporting.

@rustbot assign

**Comment by eggyal** [comment]
I'm not convinced that displaying the value of (provided associated) constants in rustdoc is ever worthwhile and indeed it could be harmful.  Users should not need to know what value a constant holds, only what it represents; indeed they should only ever be using the constant itself to represent that value when it's required—that is to say, the value assigned is an implementation detail and nobody should be relying upon it.

**Comment by GuillaumeGomez** [comment]
I strongly disagree. Associated constants are meant to be used by externals users, otherwise they'd not be created. They are definitely not an implementation detail and they are part of the public API so everyone should rely on them.

There are a lot of examples so I'll just take one: all [`SystemExt`](https://docs.rs/sysinfo/latest/sysinfo/trait.SystemExt.html) associated constants in the `sysinfo` crate.

**Comment by eggyal** [comment]
> if they use it in a pattern \[exhaustiveness checking\] or inside of a const argument \[type checking\] (which may currently require `#![feature(adt_const_params)]` if the type is not numeric).

Isn't that just relying on an implementation detail in order to work-around current limitations in the language?  If/when `adt_const_params` lands, the constant *should* be used in place of its value?

**Comment by fmease** [comment]
What I am saying is that changing the value of a public constant is a breaking change since it is part of the public API.

As a simplified example, consider the case where a crate called `constants` exports two constants of type `bool`, named `X` and `Y`.

Crate `user0` depending on crate `constants` contains the following code:

```rust
pub struct Container<const B: bool>;
const _: Container<{constants::Y}> = Container::<{!constants::X}>;
```

Crate `user1` also depending on `constants`:

```rust
const _: () = match true { constants::X | constants::Y => {} };
```

In version A of `constants`, constant `X` is not equal to `Y` and the dependent crates `user0` and `user1` compile just fine.
Now, in the succeeding version B of `constants`, `X` and `Y` are set equal to each other. `user0` and `user1` no longer compile with the new version. The inequality was part of the public contract but it was broken. If we wanted to follow SemVer, version B would need to be incompatible with A.

**Comment by eggyal** [comment]
Ah, understood!  Sorry for being slow on the uptake :).  That all makes sense now.

**Comment by camelid** [comment]
@fmease I understand your argument to some extent, but changing a function's source code can also be a SemVer breaking change. Why should constants — which also hide a complex expression and present a simple API, like functions — be treated differently?

**Comment by GuillaumeGomez** [comment]
@camelid I'm a bit lost. We only show public parts of the API unless using `--document-private-items` and @fmease and I are supporting the idea to only show the public parts of "complex" associated constants' value to make it treated like the other items. Or did I completely miss your comment?

**Comment by camelid** [comment]
My point is that we never show function bodies (even with `--document-private-items`), and IMO constants are a subset of (`const`) functions, so we also should not show constant bodies.

We do show the bodies of free (non-associated) constants already, but I think I'd rather stop doing that instead of also displaying associated constants' values.

**Comment by GuillaumeGomez** [comment]
I see your point. I disagree though. If you update a constant value, it's the same as changing a function's header: it's a breaking change. And it's also super useful to be able to see the value of a constant (associated or not) and I think it's definitely a big plus.

**Comment by camelid** [comment]
Well, I at least think we shouldn't show the raw expression from the constant's body; we should only show the fully-computed value.

**Comment by fmease** [comment]
@camelid Yes, we should prefer printing the evaluated value. I am working on this. It's not as trivial and I am going to do it incrementally. The biggest issue is the missing support for const substitutions as you might remember.

Yesterday I almost had a working PR done, in some sense a _hotfix_ for this issue, that “censors” complex unevaluated expressions like struct literals and match expressions replacing them with `_` (over time this procedure can be fine-tuned).
However, I ran into some nasty corner cases (certain qualified paths that contain const arguments) and regressions. I will try to simplify the path, add tests and open it as a PR in the today or tomorrow (hopefully).

I have further plans for improving const support but the current representation of constant expressions and the lack of const substitutions in rustdoc is giving me a headache. I have already prepared a more sophisticated PR that adds hyperlinks to const exprs and understands the concept of private and `doc(hidden)` fields when pretty-printing but it's not quite ready yet.

**Comment by camelid** [comment]
> I have further plans for improving const support but the current representation of constant expressions and the lack of const substitutions in rustdoc is giving me headaches.

Yeah, the current state of the code is quite unfortunate :(

I've tried to improve it, but as you've seen it's very hard to understand and change.

**Comment by unageek** [comment]
I don't like this.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/29035331/176990849-78f74674-f16f-441c-8c11-eb9245405415.png">

**Comment by fmease** [comment]
PR coming up within the next hour. I just need to write some more tests.
