### ISSUE TITLE
`Box` `DiagnosticMetadata` field in `LateResolutionVisitor`

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#97954]
We should experiment with making the `rustc_resolve::late::DiagnosticMetadata` field in `rustc_resolve::late::LateResolutionVisitor` boxed and run perf to see if that improves compilation times.

**Comment by eggyal** [comment]
Actually, I'm not sure I understand how this (alone) could yield any improvement; is there something more to the proposed changes?  As it stands, purely boxing the `diagnostic_metadata` field will surely only add heap allocation cost?

**Comment by estebank** [comment]
@eggyal Thanks for looking into this! 

> As it stands, purely boxing the diagnostic_metadata field will surely only add heap allocation cost?

It depends entirely on the access patterns. Some of the diagnostic metadata substructs we have elsewhere in the compiler are accessed very rarely, while their parent struct is moved/copied/cloned often, so moving those into the heap provides improvements due to better caching/inlining. I had a hunch that this particular case might not be too impactful, but it was worth testing (and there are a handful of cases where there seems to be benefit!).
