### ISSUE TITLE
Possibly-uninitialized error message doesn't indicate where value isn't initialized

### ISSUE THREAD

**Issue by jonhoo** [rust-lang/rust#97956]
Given the following code: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=d0d96c280bcde85e4d524178fefca741

```rust
let pkg;
if true {
    pkg = 1;
} else {
    // I forgot to initialize pkg!
}
drop(pkg);
```

The current output is:

```
error[[E0381]](https://doc.rust-lang.org/stable/error-index.html#E0381): use of possibly-uninitialized variable: `pkg`
 --> src/main.rs:8:10
  |
8 |     drop(pkg);
  |          ^^^ use of possibly-uninitialized `pkg`
```

Ideally the output should look like:

```
error[[E0381]](https://doc.rust-lang.org/stable/error-index.html#E0381): use of possibly-uninitialized variable: `pkg`
 --> src/main.rs:8:10
  |
8 |     drop(pkg);
  |          ^^^ use of possibly-uninitialized `pkg`
  |
  | hint: the value is not assigned in the branch starting on src/main.rs:5:
  |
5 |     } else {
  |
```

Because it can be difficult to figure out exactly which branch is failing to initialize a value, especially if it's not as simple as one `if` as above. For example, there may be a whole tree of conditionals between the `let` and the use, where only one sub-branch fails to initialize the variable, but spotting that amidst all the code isn't easy.

**Comment by jonhoo** [comment]
Here's a more elaborate case simplified from where this originally hit me: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=0a43b50d67a4b2f30f06b9b8f2efb7af

**Comment by rseymour** [comment]
Would a successful fix for this step you through the locations more than blast out all of them? i.e. `hint: the value is *first* not assigned in the branch starting on` ...

**Comment by jonhoo** [comment]
It's a good question. I _think_ you would actually want all of them at once, because you _will_ have to fix each one anyway. One possible exception is if the value isn't set in _any_ branch, in which case I think just pointing out that it needs to be set is sufficient.

**Comment by estebank** [comment]
Output with #98360:

<img width="551" alt="" src="https://user-images.githubusercontent.com/1606434/174912256-92e0ad90-5d3f-4b07-b591-1211c9d43844.png">

```
error[E0381]: used binding `pkg` isn't initialized in all conditions
 --> f43.rs:8:10
  |
2 |     let pkg;
  |         --- binding declared here but left uninitialized
...
5 |     } else {
  |      ------ `pkg` is uninitialized if this `else` arm is executed
...
8 |     drop(pkg);
  |          ^^^ `pkg` used here but it isn't initialized in all conditions
```
