### ISSUE TITLE
select_nth documentation is insufficient

### ISSUE THREAD

**Issue by TheIronBorn** [rust-lang/rust#97982]
The documentation's description of the return values is slightly incorrect.
https://github.com/rust-lang/rust/blob/c84594661c1b51feb539b479b58bb551fcf8e19a/library/core/src/slice/mod.rs#L2631-L2633

The following code however, produces `([1, 1], 1, [1, 1])`:
```rust
let mut v = [1i32; 5];
let (x, y, z) = v.select_nth_unstable(2);
```
(playground link: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=3c68d77916745c6442866324d675755d)

**Comment by DesmondWillowbrook** [comment]
Oh, it seems there's already an active PR for this. Sorry!
