### ISSUE TITLE
Describe integer overflow semantics in the manual.

### ISSUE THREAD

**Issue by nejucomo** [rust-lang/rust#9801]
Please add a section on integer overflow (and underflow) semantics for signed/unsigned integers.

The only mention of "overflow" I see in the [manual](http://static.rust-lang.org/doc/0.8/rust.html) is [6.1.3.2.4 Behaviour not considered unsafe](http://static.rust-lang.org/doc/0.8/rust.html#behaviour-not-considered-unsafe) which doesn't define overflow semantics.

It would also help to augment [7.2.11.5 Type cast expressions](http://static.rust-lang.org/doc/0.8/rust.html#type-cast-expressions) to declare that the overflow semantics apply there with a cross-link.  There may be other cases where it's not obvious that overflow semantics apply so those sections should cross-link also.

**Comment by cmr** [comment]
Ever more relevant with overflow now being defined as a panic!

**Comment by steveklabnik** [comment]
https://github.com/rust-lang/rfcs/blob/master/text/0560-integer-overflow.md was accepted, and while this ticket is still valid, I have a 'go through all RFCs' bug over at https://github.com/rust-lang/rust/issues/20137, so I'm closing this one, since that one is more comprehensive.
