### ISSUE TITLE
Failing to build compiler on windows

### ISSUE THREAD

**Issue by differentprogramming** [rust-lang/rust#98024]
simply trying to build from source on windows inside the x86 Native Tools Command Prompt for either Visual Studio 2017 or Visual Studio 2019 fails with the following message:

C:\rust\rust-1.61.0>python x.py build
downloading https://static.rust-lang.org/dist/2022-04-07/rust-std-1.60.0-x86_64-pc-windows-msvc.tar.xz
extracting C:\rust\rust-1.61.0\build\cache\2022-04-07\rust-std-1.60.0-x86_64-pc-windows-msvc.tar.xz
downloading https://static.rust-lang.org/dist/2022-04-07/rustc-1.60.0-x86_64-pc-windows-msvc.tar.xz
extracting C:\rust\rust-1.61.0\build\cache\2022-04-07\rustc-1.60.0-x86_64-pc-windows-msvc.tar.xz
downloading https://static.rust-lang.org/dist/2022-04-07/cargo-1.60.0-x86_64-pc-windows-msvc.tar.xz
extracting C:\rust\rust-1.61.0\build\cache\2022-04-07\cargo-1.60.0-x86_64-pc-windows-msvc.tar.xz
Building rustbuild
error: failed to load manifest for workspace member `C:\rust\rust-1.61.0\src\tools\rust-installer`

Caused by:
  failed to read `C:\rust\rust-1.61.0\src\tools\rust-installer\Cargo.toml`

Caused by:
  The system cannot find the file specified. (os error 2)
failed to run: C:\rust\rust-1.61.0\build\x86_64-pc-windows-msvc\stage0\bin\cargo.exe build --manifest-path C:\rust\rust-1.61.0\src/bootstrap/Cargo.toml
Build completed unsuccessfully in 0:00:24

**Comment by klensy** [comment]
If you trying to build rust from [releases](https://github.com/rust-lang/rust/releases) - it wont work, you should clone repo.

**Comment by crlf0710** [comment]
Indeed, there's a topic at https://github.community/t/create-release-that-contains-submodule/1329 .

Anyway, closing as non-issue.
