### ISSUE TITLE
x86_64-gnu-aux/x86_64-msvc-cargo: xsv test appears to fail spuriously

### ISSUE THREAD

**Issue by nagisa** [rust-lang/rust#98068]
Instances of this occurring:

https://github.com/rust-lang/rust/pull/95542#issuecomment-1120237681
https://github.com/rust-lang/rust/pull/95897#issuecomment-1153206866
https://github.com/rust-lang/rust/pull/94272#issuecomment-1060116375
https://github.com/rust-lang/rust/pull/92589#issuecomment-1006363237

Not sure if a xsv problem or bors problem, but here goes: cc @BurntSushi.

(NB: it appears that we're pulling in a master of `xsv` because the commit we had locked on has disappeared...)

**Comment by ehuss** [comment]
See also #73514.

**Comment by RalfJung** [comment]
Duplicate of https://github.com/rust-lang/rust/issues/73514
