### ISSUE TITLE
Remove `cfg(doc)` and `cfg(doctest)` from `doc_auto_cfg`, fix `not()` making badge disappear

### ISSUE THREAD

**Issue by SpriteOvO** [rust-lang/rust#98065]
Context: https://github.com/rust-lang/rust/issues/43781#issuecomment-1154226733

CC @GuillaumeGomez

**Comment by GuillaumeGomez** [comment]
Thanks for opening this issue! Someone from the rustdoc team will try to get back to it whenever possible.

**Comment by SpriteOvO** [comment]
> Thanks for opening this issue! Someone from the rustdoc team will try to get back to it whenever possible.

@GuillaumeGomez It doesn't look too difficult. I'm going to try to make a PR for it myself, and I'll update here with or without progress.
