### ISSUE TITLE
{{produces}} In many places in docstrings instead of code or documentation

### ISSUE THREAD

**Issue by John15321** [rust-lang/rust#98074]
https://github.com/rust-lang/rust/blob/ca122c7ebb3ab50149c9d3d24ddb59c252b32272/compiler/rustc_lint/src/builtin.rs#L74

Hi, I cant see that in many places in the rust docstring in this whole file instead of actual code or whatever there is simply "{{produces}}". Shouldn't there be something?

It renders like this:
![image](https://user-images.githubusercontent.com/56229312/173458054-d16e83a2-2bc6-4ae7-8e0e-c52ec15031d4.png)

**Comment by ChayimFriedman2** [comment]
This is filled with the result of the lint by a script in the [lint documentation](https://doc.rust-lang.org/rustc/lints/listing/warn-by-default.html#deprecated-cfg-attr-crate-type-name), but apparently not in rustdoc. I don't know how much important this is, however.

**Comment by jyn514** [comment]
This isn't a bug, the template is filled with the actual error message by error_index_generator.
