### ISSUE TITLE
Why not support default parameters, such as Option type, which default to None

### ISSUE THREAD

**Issue by tu6ge** [rust-lang/rust#98090]
I am developing a library. When adding feature, it is inevitable to add parameters to functions or methods. However, this will lead to that the developers who used my library must make corresponding adjustments before they can use the new features . so, many library is not release 1.x version. This is not conducive to rust ecosystem grow .

**Comment by matthiaskrgr** [comment]
I guess your function could take something like `Option<T>`where `T` implements `std::default::Default`?

**Comment by tu6ge** [comment]
But I don’t know count of args in previous version，I add arg in new version is breaking chang

**Comment by tu6ge** [comment]
In previous version, I have a function like this:
```
fn bar(a: String, b: String) -> () {...}
```
 and I plan add third parameter with next version. but other developer used this function .  the change is destroyed other developer 's code .

**Comment by GuillaumeGomez** [comment]
It's why semver and equivalent was invented. You change the API, you change the version number accordingly.

**Comment by jyn514** [comment]
The issue tracker is not a support forum. For future questions please ask in one of these places:

https://discord.gg/rust-lang/
https://discord.gg/rust-lang-community/
https://users.rust-lang.org/
https://rust-lang.zulipchat.com/
