### ISSUE TITLE
Local struct variables are over-aligned

### ISSUE THREAD

**Issue by QuarticCat** [rust-lang/rust#98138]
See https://godbolt.org/z/7Gocsz4Ge and https://rust.godbolt.org/z/bEonzKzjh

When alignment is specified in struct, both clang and rustc will waste extra 128 bytes on stack.

See also https://github.com/llvm/llvm-project/issues/56020. There someone pointed out that it could be an LLVM IR generation issue.

**Comment by QuarticCat** [comment]
@eggval Is there a way to declare a local variable like `alignas(128) int a = 1;` which allows the compiler to reuse the padded space?

**Comment by eggyal** [comment]
Why do you want to change its alignment in the first place?

**Comment by QuarticCat** [comment]
SIMD/Vector, GPU, avoid false sharing, pointer tricks, etc. But yes, most of them are not allocated on the stack. You make me realize that it is a rare case.
