### ISSUE TITLE
rust-1.61-i686-unknown-linux-gnu rustc --version fails w/ kernel panic on Centos 7 32-bit

### ISSUE THREAD

**Issue by dbodden-pesa** [rust-lang/rust#98142]
rust-1.61-i686-unknown-linux-gnu rustc --version fails w/ kernel panic on Centos 7 32-bit.

I installed to a few different VMs and a physical host, had Centos 7 32-bit running. Downloaded the offline installer for rust-1.61-i686-unknown-linux-gnu and the install.sh works. rustc --version immediately fails with a kernel panic, hard-hang on all 4 systems I tried out.

I tried this code:

rustc --version

I expected to see this happen: 

Get the version number and release date.

Instead, this happened: *explanation*

(dmesg after the panic caused by "rustc --version")
[ 0.769351] ACPI: PCI Interrupt Link [GSIF] enabled at IRQ 21
[ 0.769402] ------------[ cut here ]------------
[ 0.769406] WARNING: CPU: 0 PID: 254 at arch/x86/mm/pat.c:354 reserve_memtype+0x89/0x510
[ 0.769407] reserve_memtype failed: [mem 0x00000000-0xffffffffffffffff], req write-combining
[ 0.769416] Modules linked in: virtio_blk virtio_net net_failover failover qxl(+) virtio_console ahci libahci drm_kms_helper syscopyarea sysfillrect sysimgblt fb_sys_fops libata crc32c_intel serio_raw ttm drm virtio_pci virtio_ring virtio drm_panel_orientation_quirks dm_mirror dm_region_hash dm_log dm_mod
[ 0.769418] CPU: 0 PID: 254 Comm: systemd-udevd Tainted: G W ------------ 3.10.0-1160.2.2.el7.centos.plus.i686 https://github.com/rust-lang/www.rust-lang.org/pull/1
[ 0.769418] Hardware name: QEMU Standard PC (Q35 + ICH9, 2009), BIOS 1.13.0-1ubuntu1.1 04/01/2014
[ 0.769418] Call Trace:
[ 0.769426] [] dump_stack+0x16/0x18
[ 0.769427] [] __warn+0xea/0x110
[ 0.769428] [] ? reserve_memtype+0x89/0x510
[ 0.769429] [] warn_slowpath_fmt+0x46/0x60
[ 0.769430] [] reserve_memtype+0x89/0x510
[ 0.769432] [] ? __kmalloc_track_caller+0x46/0x1e0
[ 0.769433] [] io_reserve_memtype+0x67/0x140
[ 0.769439] [] iomap_create_wc+0x2b/0x70
[ 0.769443] [] qxl_device_init+0x467/0x8f0 [qxl]
[ 0.769450] [] ? pci_read_config_word+0x42/0x50
[ 0.769452] [] ? do_pci_enable_device+0xc4/0xf0
[ 0.769455] [] qxl_pci_probe+0x6e/0xf0 [qxl]
[ 0.769457] [] ? __pm_runtime_resume+0x51/0x80
[ 0.769459] [] ? qxl_pci_remove+0x50/0x50 [qxl]
[ 0.769460] [] pci_device_probe+0x7c/0xe0
[ 0.769462] [] ? sysfs_create_link+0x25/0x40
[ 0.769464] [] driver_probe_device+0xb3/0x3d0
[ 0.769465] [] ? __device_attach+0x40/0x40
[ 0.769465] [] __driver_attach+0x79/0x80
[ 0.769466] [] ? __device_attach+0x40/0x40
[ 0.769467] [] bus_for_each_dev+0x5a/0xa0
[ 0.769468] [] driver_attach+0x1e/0x20
[ 0.769469] [] ? __device_attach+0x40/0x40
[ 0.769470] [] bus_add_driver+0x1d7/0x2b0
[ 0.769471] [] driver_register+0x59/0xe0
[ 0.769472] [] __pci_register_driver+0x84/0xa0
[ 0.769473] [] ? 0xf80d7fff
[ 0.769475] [] qxl_init+0x3c/0x1000 [qxl]
[ 0.769479] [] do_one_initcall+0xad/0x220
[ 0.769480] [] ? 0xf80d7fff
[ 0.769481] [] load_module+0x153e/0x1a70
[ 0.769484] [] SyS_finit_module+0x8d/0xd0
[ 0.769486] [] sysenter_do_call+0x1b/0x31
[ 0.769487] ---[ end trace f68728a0d3053b54 ]---

### Meta

I found this behavior started with 1.51, although 1.50 gave the version info, it also failed to compile and gave a panic when compiling code.

(cpuinfo, cat /etc/centos-release, uname -a)
model name : AMD EPYC-Rome Processor
model name : AMD EPYC-Rome Processor
CentOS Linux release 7.9.2009 (AltArch)
Linux localhost.localdomain 3.10.0-1160.2.2.el7.centos.plus.i686 https://github.com/rust-lang/www.rust-lang.org/pull/1 SMP Mon Oct 26 11:56:29 UTC 2020 i686 i686 i386 GNU/Linux

**Comment by cuviper** [comment]
That sounds like a kernel bug -- it should not be possible for *any* unprivileged program to cause a kernel panic. Have you reported a [CentOS bug](https://bugs.centos.org/)? Note that it will have to be handled by the [AltArch SIG](https://wiki.centos.org/SpecialInterestGroup/AltArch/i386), as Red Hat no longer supports 32-bit hosts, but I don't know if that SIG is really active anymore.

**Comment by dbodden-pesa** [comment]
It's EOL. I don't expect any resolution there. Thank you.
________________________________

**Comment by jieyouxu** [comment]
Triage: EOL environment, unactionable.
