### ISSUE TITLE
Flaky test on CI: `search-tab-change-title-fn-sig.goml`

### ISSUE THREAD

**Issue by JohnTitor** [rust-lang/rust#98163]
The failure is:
```
/checkout/src/test/rustdoc-gui/search-tab-change-title-fn-sig.goml search-tab-change-title-fn-sig... FAILED
[ERROR] (line 6) Error: The following CSS selector "#titles" was not found: for command `wait-for: "#titles"`
Build completed unsuccessfully in 0:00:47
```

That test has failed several times:
- https://github.com/rust-lang/rust/pull/97410#issuecomment-1138063653
- https://github.com/rust-lang/rust/pull/97717#issuecomment-1146456078
- https://github.com/rust-lang/rust/pull/98144#issuecomment-1156953356

**Comment by JohnTitor** [comment]
Another case: https://github.com/rust-lang/rust/pull/99305#issuecomment-1186078677

**Comment by GuillaumeGomez** [comment]
It's all linked to the search. I wonder if we're entering things too fast...

**Comment by JohnTitor** [comment]
Maybe we could do some retry such a case?

**Comment by GuillaumeGomez** [comment]
I have a better idea. :)
