### ISSUE TITLE
Should Result where E: Infallible implement Deref<Target = T>?

### ISSUE THREAD

**Issue by stevenroose** [rust-lang/rust#98172]
When a trait forces you to return a `Result<T, Self::Err>`, but you make `Err = Infallible`, it would be nice if you could use that object as if it wasn't a `Result`, using `impl<T> Deref for Result<T, Infallible> { type Target = T; ... }`..

**Comment by eggyal** [comment]
On nightly, there's [`Result::into_ok`](https://doc.rust-lang.org/1.61.0/core/result/enum.Result.html#method.into_ok).

**Comment by stevenroose** [comment]
That's cool, though, thanks!

**Comment by jyn514** [comment]
I'm going to close this, `into_ok` looks like what you want. I think using Deref would be confusing.
