### ISSUE TITLE
"-Z merge-functions" does not enable the MergeFunctions pass under opt-level=s

### ISSUE THREAD

**Issue by jrose-signal** [rust-lang/rust#98215]
I tried compiling my crate with `RUSTFLAGS="-Z merge-functions=aliases"`, but saw no difference in output size, whereas `RUSTFLAGS="-C passes=mergefunc"` showed a 1% improvement (not much but I'd take it). I *think* this is because of this code:

https://github.com/rust-lang/rust/blob/c3b7d7b496b5536bb0a3d501222d2d0a8b54a69e/compiler/rustc_codegen_ssa/src/back/write.rs#L248-L259

which is probably intended to exclude opt-level=0 builds but should really at least *allow* Size (s) and SizeMin (z), if not enable them by default.

**Comment by workingjubilee** [comment]
Hm. Is there any chance we could get the crate or reduced code that can demonstrate the problem? I can probably dig up some code that LLVM merges functions on from my own snippets, just want to be sure.

**Comment by jrose-signal** [comment]
This reproduces with just
```rust
pub fn foo() -> i32 {
    1
}

pub fn bar() -> i32 {
    1
}
```

```shell
% rustc -C opt-level=2 --emit llvm-ir --crate-type=rlib -o opt-level-2.ll test.rust
% rustc -C opt-level=s --emit llvm-ir --crate-type=rlib -o opt-level-s.ll test.rust
```

**Comment by workingjubilee** [comment]
Wait, really? Wow.
