### ISSUE TITLE
rustdoc source view: `backtrace` 404s

### ISSUE THREAD

**Issue by jsha** [rust-lang/rust#98220]
Steps to reproduce:

1. Visit https://doc.rust-lang.org/std/
2. Click "source"
3. Open the sidebar
4. In the sidebar, click "backtrace", then "src", then "lib.rs".

Expected result: either backtrace's lib.rs loads, or it is not listed.

Actual result: 404 (https://doc.rust-lang.org/src/std/backtrace/src/lib.rs.html)

**Comment by 353fc443** [comment]
Hi,

I looked into this issue and found that the files listed in the sidebar is not actually present in the `backtrace` directory.

It only contain `tests.rs` (which i think is ignored).

https://github.com/rust-lang/rust/tree/stable/library/std/src/backtrace

:)

**Comment by jsha** [comment]
I believe it's actually brought in as a submodule. See  https://github.com/rust-lang/rust/tree/stable/library; and in a checked out rust repository, try `ls library/backtrace/src/lib.rs`.

**Comment by 353fc443** [comment]
Then I think it is some issue with submodule .

**Comment by clubby789** [comment]
Testing locally, this was closed by #106466

**Comment by lolbinarycat** [comment]
triage: fixed on stable too, and it seems like there's a regression test
