### ISSUE TITLE
Copy isn't implemented with #[derive(Clone, Copy)] when using type members from traits

### ISSUE THREAD

**Issue by solomatov** [rust-lang/rust#98228]
I tried this code:

```rust
trait XYZ {
    type X: Copy;
}

#[derive(Clone, Copy)]
struct AAA<X: XYZ> {
    x: X::X,
}

struct B {}

impl XYZ for B {
    type X = usize;
}

impl Clone for B {
    fn clone(&self) -> Self {
        Self {}
    }
}

fn main() {
    let aaa: AAA<B> = AAA { x: 32 };

    let c1 = aaa;
    let c2 = aaa;
}
```

I expected to see this happen: 
AAA should implement a Copy, however it doesn't.

Instead, this happened: 
Instead it doesn't implement a copy and it shows an error:
```
   |
23 |     let aaa: AAA<B> = AAA { x: 32 };
   |         --- move occurs because `aaa` has type `AAA<B>`, which does not implement the `Copy` trait
24 | 
25 |     let c1 = aaa;
   |              --- value moved here
26 |     let c2 = aaa;
   |              ^^^ value used here after move```

If I add:
```
#[derive(Clone, Copy)]
struct B {}
```
everything is fine, so automatic deriver just sees whether all type parameters are Copy whereas it should check that all members of used in the type are copy.

### Meta
<!--
If you're using the stable version of the compiler, you should also check if the
bug also exists in the beta or nightly versions.
-->
This bug reproduces in stable and nightly

`rustc --version --verbose`:
```
rustc 1.61.0 (fe5b13d68 2022-05-18)
binary: rustc
commit-hash: fe5b13d681f25ee6474be29d748c65adcd91f69e
commit-date: 2022-05-18
host: aarch64-apple-darwin
release: 1.61.0
LLVM version: 14.0.0
```

**Comment by eggyal** [comment]
Are you saying that you expected Rust to automatically `impl Copy for B` simply because you have an `impl XYZ for B`?

Not only does `XYZ` not require `Self: Copy` (it only requires that its associated type `X` implements `Copy`—in the case of your `B` example, that's `usize` which is indeed `Copy`) but even if it had such a constraint, that would only prevent `XYZ` from being implemented on types that are not `Copy`: it wouldn't magically implement `Copy` for you.

There are only a couple of "auto traits" that the compiler automatically implements for you, such as `Send` and `Sync`; all others you must implement yourself, potentially via a macro (such as `derive`, if appropriate).

**Comment by solomatov** [comment]
@eggyal Yep, I mean exactly that. The biggest problem with Copy is that it can only be implemented by the compiler.

**Comment by eggyal** [comment]
`Copy` is just a marker trait, which signals to the compiler that it's safe to make bitwise copies of instances of the type.  You can (and do, often with `derive` as you showed above) implement it yourself.

As for expecting it to be automatically implemented, as explained above that simply is not how traits work in Rust.  This definitely is not a bug.

@rustbot label: -C-bug

**Comment by solomatov** [comment]
@eggyal Double checked. I put example incorrectly. Will rewrite the text shortly.

**Comment by solomatov** [comment]
@eggyal Ok. I see that Copy could be implemented, and compiler doesn't complain about this at all. That's really cool.

**Comment by solomatov** [comment]
@eggyal Done

**Comment by solomatov** [comment]
@eggyal Ok. I see. It allows to implement Copy for such a type, however, if there're non-Copy fields, it complaints about it. It looks like auto impl of copy doesn't put correct where clauses, though the problem is easy to work around.

**Comment by eggyal** [comment]
This is a duplicate of #26925.  The usual recommendation is to use an alternative `derive` macro, such as [derivative](https://crates.io/crates/derivative).

**Comment by solomatov** [comment]
Closing since it's a duplicate.
