### ISSUE TITLE
Add rustc --run

### ISSUE THREAD

**Issue by SiegeLord** [rust-lang/rust#9826]
With the removal of the `rust` tool, there is nothing good to place in the initial hashbang comment in a Rust file (you used to be put `rust run` in there). `rustc --run` should be added to fill that gap.

The use case, of course, is some kind support for script-like usage for Rust which will become attractive when the compilation speed improves.

**Comment by steveklabnik** [comment]
Triage: no comments in a long time. https://github.com/DanielKeep/cargo-script can be used in a shebang line, and includes Cargo stuff as well.

**Comment by aalexgabi** [comment]
Tried cargo run :disappointed: but it seems that you need Cargo.toml file:
```
[root@arch-anywhere:~]# cargo run main.rs                                                                       (02-10 13:49)
error: could not find `Cargo.toml` in `/root` or any parent directory
```

I agree there should be some kind of command that abstracts away the compilation part. I'm not sure this has something to do with cargo. Maybe:
```
rust main.rs
```

cargo-script is ok but is not installed by default. I'm not sure that the all the verbosity is needed:
```
[root@arch-anywhere:~][127]# cargo script main.rs                                                               (02-10 13:58)
   Compiling main v0.1.0 (file:///root/.cargo/script-cache/file-main-fa4ca44a3cefa0f6)
    Finished release [optimized] target(s) in 0.24 secs
Hi man!
```

**Comment by steveklabnik** [comment]
I am going to give this one a close, as `cargo script` fills in this gap. Including it with cargo by default would be RFC-worthy.

**Comment by bronson** [comment]
Leaves the `rustc --test` and `rustc --bench` gaps unfilled though.  :)

**Comment by aalexgabi** [comment]
@steveklabnik As pointed earlier `cargo script` is not installed by default.

**Comment by frewsxcv** [comment]
> With the removal of the `rust` tool

For the sake of posterity and documenting some history, here's where the `rust` command was added:

- https://github.com/rust-lang/rust/pull/5014

and here's where the `rust` command was removed:

- https://github.com/rust-lang/rust/pull/9785

**Comment by dangdennis** [comment]
For those wondering what Steve refers to as `cargo script`.
https://github.com/DanielKeep/cargo-script

**Comment by igor-petruk** [comment]
As for now, it is not clear if `cargo script` is maintained. I have written a language agnostic tool, in case anyone needs it. Works well for Rust too, including building static binaries in Docker and extracting them to host

https://github.com/igor-petruk/scriptisto

**Comment by metaspook** [comment]
> Tried cargo run 😞 but it seems that you need Cargo.toml file:
> 
> ```
> [root@arch-anywhere:~]# cargo run main.rs                                                                       (02-10 13:49)
> error: could not find `Cargo.toml` in `/root` or any parent directory
> ```
> 
> I agree there should be some kind of command that abstracts away the compilation part. I'm not sure this has something to do with cargo. Maybe adding a rust command:
> 
> ```
> $ rust main.rs
> Hi man!
> $ 
> ```
> 
> By also adding a shebang:
> 
> ```
> #!/usr/bin/env rust
> 
> fn main() {
>   println("Hi man!")
> }
> ```
> 
> We can execute by simply:
> 
> ```
> $ chmod +x main.rs
> $ ./main.rs
> ```
> 
> This allows distributing via compiled binaries via `rustc main.rs` and running in one step.
> 
> cargo-script is ok but is not installed by default. I'm not sure that the all the verbosity is needed:
> 
> ```
> [root@arch-anywhere:~][127]# cargo script main.rs                                                               (02-10 13:58)
>    Compiling main v0.1.0 (file:///root/.cargo/script-cache/file-main-fa4ca44a3cefa0f6)
>     Finished release [optimized] target(s) in 0.24 secs
> Hi man!
> ```

This is a great idea I love it will they implement it?

**Comment by abc-mikey** [comment]
wow! 8 years, that is some powerfully user unfriendliness.
