### ISSUE TITLE
Tracking Issue for `task::Waker::update`

### ISSUE THREAD

**Issue by SabrinaJewson** [rust-lang/rust#98287]
Feature gate: `#![feature(waker_update)]`

This is a tracking issue for `task::Waker::update`, a shortcut function for replacing a waker while avoiding unnecessary clones (via `will_wake`).

### Public API

```rust
// core::task

impl Waker {
    pub fn update(&mut self, other: &Waker);
}
```

### Steps / History

- [ ] Implementation: #96979
- [ ] Final comment period (FCP)
- [ ] Stabilization PR

### Unresolved Questions

- None yet.

**Comment by cuviper** [comment]
I think this is obsolete since #96979 switched to overriding `clone_from`.
