### ISSUE TITLE
Tracking Issue for feature(core_c_str) and feature(alloc_c_string)

### ISSUE THREAD

**Issue by joshtriplett** [rust-lang/rust#98314]
Feature gate: `#![feature(core_c_str)]` and `#![feature(alloc_c_string)]`

This is a tracking issue for the availability of `CStr` in core and `CString` in alloc.

### Public API

```rust
// core::ffi
pub struct CStr;
pub struct FromBytesWithNulError;

// alloc::ffi
pub struct CString;
pub struct NulError;
pub struct FromVecWithNulError;
pub struct IntoStringError;
```

### Steps / History

- [x] Implementation: #94079
- [x] Final comment period (FCP)
- [ ] Stabilization PR

**Comment by joshtriplett** [comment]
`core::ffi::c_*` appears to be on track to stabilize in 1.63.0. Shall we do the same for `core::ffi::CStr` and `alloc::ffi::CString`?

@rfcbot merge

**Comment by mbartlett21** [comment]
If this ends up being done, will the type aliases in std be changed back to re-exports?

**Comment by joshtriplett** [comment]
This has been stabilized in #99277.
