### ISSUE TITLE
Updating rustc to 1.61.0

### ISSUE THREAD

**Issue by jxuanli** [rust-lang/rust#98317]
Hello I am trying to update my rustc to 1.61.0 with 
```
rustup update stable
info: syncing channel updates for 'stable-x86_64-pc-windows-msvc'

  stable-x86_64-pc-windows-msvc unchanged - rustc 1.61.0 (fe5b13d68 2022-05-18)

info: checking for self-updates
```
But after that I have
```
rustc --version
rustc 1.60.0 (7737e0b5c 2022-04-04)
```
I m not sure how I can resolve that thanks!

**Comment by ChayimFriedman2** [comment]
Do you have overrides?

**Comment by jxuanli** [comment]
I m not too sure what is an override in this context

**Comment by ChayimFriedman2** [comment]
`rustup override list` in the project directory. https://rust-lang.github.io/rustup/overrides.html.

**Comment by jxuanli** [comment]
I tried to do the following
>> rustup override set 1.61.0
info: syncing channel updates for '1.61.0-x86_64-pc-windows-msvc'
info: latest update on 2022-05-19, rust version 1.61.0 (fe5b13d68 2022-05-18)
info: downloading component 'cargo'
info: downloading component 'clippy'
info: downloading component 'rust-docs'
info: downloading component 'rust-std'
 24.6 MiB /  24.6 MiB (100 %)  21.6 MiB/s in  1s ETA:  0s
info: downloading component 'rustc'
 56.7 MiB /  56.7 MiB (100 %)  21.2 MiB/s in  2s ETA:  0s
info: downloading component 'rustfmt'
info: installing component 'cargo'
info: installing component 'clippy'
info: installing component 'rust-docs'
 19.6 MiB /  19.6 MiB (100 %)   2.9 MiB/s in  5s ETA:  0s
info: installing component 'rust-std'
 24.6 MiB /  24.6 MiB (100 %)  12.0 MiB/s in  2s ETA:  0s
info: installing component 'rustc'
 56.7 MiB /  56.7 MiB (100 %)  13.2 MiB/s in  4s ETA:  0s
info: installing component 'rustfmt'
info: override toolchain for '' set to '1.61.0-x86_64-pc-windows-msvc'

  1.61.0-x86_64-pc-windows-msvc installed - rustc 1.61.0 (fe5b13d68 2022-05-18)

>>> rustc --version
rustc 1.60.0 (7737e0b5c 2022-04-04)


>>> rustup default 1.61.0
info: using existing install for '1.61.0-x86_64-pc-windows-msvc'
info: default toolchain set to '1.61.0-x86_64-pc-windows-msvc'

  1.61.0-x86_64-pc-windows-msvc unchanged - rustc 1.61.0 (fe5b13d68 2022-05-18)

info: note that the toolchain '1.61.0-x86_64-pc-windows-msvc' is currently in use (directory override for '')

>>> rustc --version
rustc 1.60.0 (7737e0b5c 2022-04-04)

**Comment by jxuanli** [comment]
It says 1.61 is in use but I m not sure somehow it contradicts the `rustc --version` command

**Comment by ChayimFriedman2** [comment]
What does `which rustc` prints?

**Comment by mbartlett21** [comment]
What does `rustc +stable --version` give you?

**Comment by jxuanli** [comment]
> What does `where.exe rustc` prints?

```
>>> where.exe rustc
C:\ProgramData\chocolatey\bin\rustc.exe
C:\Users\user\.cargo\bin\rustc.exe
```

**Comment by jxuanli** [comment]
> 

```
>>> rustc +stable --version
rustc 1.60.0 (7737e0b5c 2022-04-04)
```

**Comment by ChayimFriedman2** [comment]
You installed rustc through chocolately and it has the outdated version. Remove it.

**Comment by jxuanli** [comment]
Thanks for all the efforts and for pointing me in the right direction! 
I rechecked with `choco search rust` it says `rust 1.61.0 [Approved] Downloads cached for licensed users`

I then run as admin the command `choco update rust` and it worked 
Thanks again!
