### ISSUE TITLE
Not sure what is happening

### ISSUE THREAD

**Issue by KlimentSerafimov** [rust-lang/rust#98435]
### Code

```Rust
<code>
```

### Meta

`rustc --version --verbose`:
```
<version>
```

### Error output

```
<output>
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by Nilstrieb** [comment]
We can't know what's happening either. Could you add your code and the full output of the rust compiler?

**Comment by compiler-errors** [comment]
@KlimentSerafimov please reopen a bug issue with all of the sections filled out. Thanks!
