### ISSUE TITLE
generic_const_exprs: duplicate definitions in disjoint impls

### ISSUE THREAD

**Issue by lcnr** [rust-lang/rust#98448]
I found something weird, not sure if it is a bug:
```
const ONE : i32 = 1;
const TWO : i32 = 2;

struct Foo<const i: i32, const j: i32> {}

impl<const i: i32> Foo<i, ONE> {
    pub fn foo() {}
}

impl<const i: i32> Foo<i, TWO> {
    pub fn foo() {}
}
```
This can comiple without `#![feature(generic_const_exprs)]`, but if `#![feature(generic_const_exprs)]` is added, it won't compile:
```
error[E0592]: duplicate definitions with name `foo`
  --> src/main.rs:9:5
   |
9  |     pub fn foo() {}
   |     ^^^^^^^^^^^^ duplicate definitions for `foo`
...
13 |     pub fn foo() {}
   |     ------------ other definition for `foo`
```

_Originally posted by @psionic12 in https://github.com/rust-lang/rust/issues/76560#issuecomment-1165261366_

**Comment by lcnr** [comment]
@psionic12 moved your comment out of the tracking issues as these are not meant for large scale discussion, questions, or bug reports about a feature.

This is definitely a bug though I do assume it's the same underlying issue as #92186

**Comment by lcnr** [comment]
actually closing this in favor of #92186, added your test as a comment, thanks

**Comment by psionic12** [comment]
Thanks for helping @lcnr, hope this bug can be fixed asap, I'm highly relied on this feature, and have to use macros instead for now.
