### ISSUE TITLE
Figure out a good way to test serializable types

### ISSUE THREAD

**Issue by cmr** [rust-lang/rust#9845]
Currently, the only way to test implementations of Encodable/Decodable is to use one or all of the serializers in libextra. This isn't really adequate, and there may be latent bugs in non-deriving serialize implementations.

**Comment by steveklabnik** [comment]
Triage: serializers have moved out of tree, and so this would belong over there. But since we're not sure how much rustc-serialize will improve, I'm just going to close, rather than move it over.
