### ISSUE TITLE
Tracking Issue for `AtomicBool::fetch_not`

### ISSUE THREAD

**Issue by pluiedev** [rust-lang/rust#98485]
Feature gate: `#![feature(atomic_bool_fetch_not)]`

This is a tracking issue for the method `AtomicBool::fetch_not`. This method performs the NOT operation on an `AtomicBool`,
and returns the old (un-negated) value.

### Public API

```rust
// in std::sync::atomic

impl AtomicBool {
    pub fn fetch_not(&self, order: Ordering) -> bool;
}
```

### Steps / History

- [X] Implementation: #98479
- [ ] Final comment period (FCP)
- [ ] Stabilization PR

### Unresolved Questions

- None yet.

**Comment by dimpolo** [comment]
Should we consider stabilizing this?

**Comment by dtolnay** [comment]
@rust-lang/libs-api:
@rfcbot fcp merge

`atomic.fetch_not(ordering)` is equivalent to `atomic.fetch_xor(true, ordering)`.

**Comment by dimpolo** [comment]
ping :)

**Comment by Urgau** [comment]
@dimpolo Feel free to send a PR stabilizing the feature. Instructions can be found [here](https://std-dev-guide.rust-lang.org/development/stabilization.html#stabilization-pr-for-library-features).
