### ISSUE TITLE
Provide a pointer to the correct names for Boolean types

### ISSUE THREAD

**Issue by alexwlchan** [rust-lang/rust#98492]
Given the following code: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=4e7d539241dfe92a24817728751e5523

```rust
fn main() {
    let value: Boolean = true;
}
```

The current output is:

```
error[E0412]: cannot find type `Boolean` in this scope
 --> src/main.rs:2:16
  |
2 |     let value: Boolean = true;
  |                ^^^^^^^ not found in this scope

For more information about this error, try `rustc --explain E0412`.
error: could not compile `example` due to previous error
```

Ideally the output should look like:

```
error[E0412]: cannot find type `Boolean ` in this scope
    --> src/main.rs:4:16
     |
4    |       let value: Boolean = true;
     |                  ^^^^^^^ help: a type with a similar meaning exists: `bool`
```

I stumbled here when returning to Rust after a while writing code in non-Rust languages; I'm sure I'm not the only person who's gotten the name of Rust's boolean type wrong. It's not hard to work out the correct behaviour, but I thought it would be nice if Rust could help programmers coming from other languages.

(I don't feel strongly about this suggestion and won't mind if it's closed as WONTFIX, but I know Esteban would be sad if he knew I'd had an idea for a diagnostic improvement that I didn't tell anyone.)

**Comment by lyming2007** [comment]
if we change the code to 
```
fn main() {
    let value: boolean = true;
}
```
the error will be like:
```
error[E0412]: cannot find type `boolean` in this scope
 --> boolean.rs:2:14
  |
2 |   let value: boolean = true;
  |              ^^^^^^^
  |              |
  |              not found in this scope
  |              help: perhaps you intended to use this type: `bool`

error: aborting due to previous error
```
How about we make the error message for your case like:
Ideally the output should look like:

```
error[E0412]: cannot find type `Boolean` in this scope
 --> Boolean.rs:2:14
  |
2 |   let value: Boolean = true;
  |              ^^^^^^^
  |              |
  |              not found in this scope
  |              help: perhaps you intended to use this type: `bool`

error: aborting due to previous error
```
