### ISSUE TITLE
Edition 2021 build breaks for edition 2018 / rustc 1.47.0

### ISSUE THREAD

**Issue by crusty-dave** [rust-lang/rust#98512]
I have had to override the following crate versions to get our older project to build:

```
[dependencies]

# Fix broken dependencies
indexmap = {version = "=1.8.2", registry = "crates-io-mirror"}
time = {version = "=0.2.27", registry = "crates-io-mirror"}
time-macros = {version = "=0.1.1", registry = "crates-io-mirror"}
cookie = {version = "=0.15.1", registry = "crates-io-mirror"}
cookie_store = {version = "=0.15.1", registry = "crates-io-mirror"}
slog-term = {version="=2.8.1", registry = "crates-io-mirror"}
parking_lot = {version="=0.11.2", registry = "crates-io-mirror"}
parking_lot_core = {version="=0.8.5", registry = "crates-io-mirror"}
r2d2 = {version="=0.8.9", registry = "crates-io-mirror"}
libz-sys = {version="=1.1.3", registry = "crates-io-mirror"}
scheduled-thread-pool = {version="=0.2.5", registry = "crates-io-mirror"}
openssl-probe = {version="=0.1.5", registry = "crates-io-mirror"}
openssl-sys = {version="=0.9.72", registry = "crates-io-mirror"}
linked-hash-map = {version="=0.5.4", registry = "crates-io-mirror"}
slog-json = {version="=2.3.0", registry = "crates-io-mirror"}
http = {version="=0.2.4", registry = "crates-io-mirror"}
log4rs = {version="=1.1.0", features = ["all_components", "background_rotation"], registry = "crates-io-mirror"}
openssl = {registry = "crates-io-mirror", version="=0.10.38"}

```
Note that linked-hash-map was just broken in the last few hours.

Note that we are forced to use 2018 / rustc 147.0 due to old dependencies from the actix-web (version="3.3.3") and related crates due to actix-web's lack of keeping current.  We haven't had time to investigate updating to actix-web 4.x yet.

Anyone who moved crates to edition 2021 should have followed semver semantics, but they apparently did not.

For anyone else facing the same issue, hopefully the above list will save you some time.  Note that our crates-io-mirror is using JFrog artifactory, I don't know if any of these issues may be related to that.

The following was the first build error that was seen, many of the other crate issues seem to have cascaded after this:

Downloaded hashbrown v0.12.1 (registry `[https://{mirror}/artifactory/git/crates-io.git`](https://{mirror}/artifactory/git/crates-io.git%60))
error: failed to parse manifest at `{path}\hashbrown-0.12.1\Cargo.toml`

Caused by:
  failed to parse the `edition` key

Caused by:
  this version of Cargo is older than the `2021` edition, and only supports `2015` and `2018` editions.
Build Errors

**Comment by nbdd0121** [comment]
> Anyone who moved crates to edition 2021 should have followed semver semantics, but they apparently did not.

MSRV policy is up to the crate, it's okay for a crate to upgrade it's MSRV without upgrading major version.

What prevents you from upgrading your compiler?

If your project has certain requirements that depend on specific compiler, you should probably checkin the Cargo.lock into source control so your dependencies won't be upgraded.

**Comment by nbdd0121** [comment]
Regardless, this is not a Rust regression.

@rustbot label: -regression-untriaged

**Comment by crusty-dave** [comment]
Checking in the cargo.lock means that we wouldn't get bug fixes.  If a crate now depends on edition 2021, how is that not a breaking change?

There is a whole bunch of crates that require newer versions, but using a actix-web 3.3 still requires tokio 2.x, there are ripple affects to that.

I am not sure why this issue hit overnight, but I was trying to create a new build for a customer issue when everything suddenly broke.

**Comment by saethlin** [comment]
> Checking in the cargo.lock means that we wouldn't get bug fixes.

_Not_ checking in a Cargo.lock also means that your build may break at any time if an author yanks the versions you need (note that there are crates which have a policy of yanking all but the latest version). It also means that you will be affected instantly if there is a supply chain attack; for example a malicious patch release of a crate is published.

>  I was trying to create a new build for a customer issue when everything suddenly broke.

This is exactly why you should check in your lockfile. You can always pull in bug fixes manually, package-by-package, with `cargo update --package` or `cargo update --package --precise` for even more control. `cargo update --dry-run` or the tool `cargo-outdated` are great ways to understand what updates are available for your dependencies.

**Comment by crusty-dave** [comment]
Given this is the second time we have run into this, I am inclined to agree now.  The cargo.lock should probably be committed at least when releasing a new version of our software to ensure repeatability.

Thanks for the discussion.

**Comment by ehuss** [comment]
I'm sorry you had a difficult experience with that.

As mentioned above, what constitutes a semver breaking change is currently done by convention of each individual project. Some decide that requiring newer versions of Rust is not a breaking change.

Keeping Cargo.lock, and carefully managing it is probably the best route for now. I'm going to close as this isn't exactly a rust-lang issue.
