### ISSUE TITLE
Tracking Issue for `iter_mut` on `BinaryHeap`

### ISSUE THREAD

**Issue by donkeyteethUX** [rust-lang/rust#98524]
Feature gate: `#![feature(binary_heap_iter_mut)]`

Allows iteration over mutable references to heap elements in arbitrary order and rebuilding the heap when the iterator is dropped.

### Public API

```rust
// new method
pub fn iter_mut(&mut self) -> IterMut<'_, T>;

// new IntoIterator implementation
impl<'a, T: Ord> IntoIterator for &'a mut BinaryHeap<T>;

// new struct
pub struct IterMut<'a, T: 'a + Ord> { /* private */ }
```

### Steps / History

- [ ] Implementation: #98522
- [ ] Final comment period (FCP)
- [ ] Stabilization PR

### Unresolved Questions

- None yet.

**Comment by scottmcm** [comment]
Given the associated PR was closed (https://github.com/rust-lang/rust/pull/98522#issuecomment-1172553773), I'll close this tracking issue as well.
