### ISSUE TITLE
Bootstrap build failing on Windows (MSVC)

### ISSUE THREAD

**Issue by BlaCoiso** [rust-lang/rust#98546]
Commit 418b1fa77af366b3784c35d88927ec7f4d869dea broke builds on Windows as `llvm-config` has a `.exe` extension but 
https://github.com/rust-lang/rust/blob/418b1fa77af366b3784c35d88927ec7f4d869dea/src/bootstrap/native.rs#L163-L164
does not take that into account, resulting in a file not found error and bootstrap panicking.

Patching line 163 with
```rs
let llvm_config = llvm_root.join("bin").join(exe("llvm-config", builder.config.build));
```
fixes the build.

**Comment by jyn514** [comment]
@BlaCoiso do you want to make a PR with that patch? :)
