### ISSUE TITLE
Function type with opaque return type can be coerced to `dyn Fn` with arbitrary return type

### ISSUE THREAD

**Issue by Nilstrieb** [rust-lang/rust#98608]
I tried this code:

```rust
fn hi() -> impl Sized { std::ptr::null::<u8>() }

fn main() {
    let b: Box<dyn Fn() -> Box<u8>> = Box::new(hi);
    let boxed = b();
    let null = *boxed;
    println!("{null:?}");
}
```

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=a78a1c65a7788a1fc16bbb49823e31b1

I expected to see this happen: Compiler error, since `impl Sized` cannot be coerced to `Box<u8>`.

Instead, this happened: Code compiles, segfault

### Meta

`rustc --version --verbose`:
```
rustc 1.64.0-nightly (2f3ddd9f5 2022-06-27)
binary: rustc
commit-hash: 2f3ddd9f594adf9773547aa7cedb43c4ac8ffd2f
commit-date: 2022-06-27
host: x86_64-unknown-linux-gnu
release: 1.64.0-nightly
LLVM version: 14.0.6
```

**Comment by JakobDegen** [comment]
This regressed in 1.61, unfortunately my wifi is not currently up for running a proper bisect.

@rustbot label +regression-from-stable-to-stable

**Comment by oli-obk** [comment]
likely cause is one of the uses of `take_opaque_type` without actually registering the hidden types

**Comment by 5225225** [comment]
searched nightlies: from nightly-2022-01-01 to nightly-2022-06-26
regressed nightly: nightly-2022-03-31
searched commit range: https://github.com/rust-lang/rust/compare/9c06e1ba47e1077725a950e0b5d1870a89c8b536...c5cf08d37b85f953b132951e868df5b924250fdc
regressed commit: https://github.com/rust-lang/rust/commit/f132bcf3bdf6d3ff9be7d02e8d0088b99007cd5e

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.1</summary>


Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --preserve --regress non-error --start 2022-01-01 
```
</details>

So yeah, it looks to be #94081

**Comment by Dylan-DPC** [comment]
marking it as critical based on the [prioritisation group discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2398608.20Function.20type.20with.20opaque.20return.20type.20can.20be.20coerced.E2.80.A6)

**Comment by apiraino** [comment]
Correct link for WG-prioritization [Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.E2.9C.94.20.2398608.20Function.20type.20with.20opaque.20return.20type.20can.20be.20coe.2E.2E.2E)
