### ISSUE TITLE
Diagnostic for early closing delimiter incorrectly blames empty block

### ISSUE THREAD

**Issue by mcy** [rust-lang/rust#98601]
See: https://godbolt.org/z/rPxvYMf1h

This code:
```rust
fn foo() {
  match 0 {
    _ => {}
  }
  if foo
  }
}
```

produces

```
error: unexpected closing delimiter: `}`
 --> <source>:7:1
  |
3 |     _ => {}
  |          -- block is empty, you might have not meant to close it
...
7 | }
  | ^ unexpected closing delimiter

error: aborting due to previous error

Compiler returned: 1
```

on latest stable (1.61.0). @estebank

**Comment by compiler-errors** [comment]
Maybe we could form a heuristic around tokens that we know should _eventually_ be followed by `{` -- `if`, `match`, `fn`, etc.

If we see one of those, (then some random other tokens), then we see `}`, then that would be a suspicious rbrace which we could point out later..

e.g. if we see `if a b c d e }` that triggers the heuristic, but not `if a b c d e { }`

**Comment by estebank** [comment]
The problem is that the error happens in the lexer, not the parser. Ideally we'd rework the lexer to have a token stream mode of operation instead of a token tree mode of operation, only for code that is being passed to the parser (i.e., not coming from a macro).

**Comment by sgued** [comment]
This is particularly confusing when the `block is empty` points to a macro:

```rust
fn main() {
    todo!();
}

fn other(_: i32)) {}
```

gives 

```
error: unexpected closing delimiter: `)`
 --> src/main.rs:5:17
  |
2 |     todo!();
  |          -- block is empty, you might have not meant to close it
...
5 | fn other(_: i32)) {}
  |                 ^ unexpected closing delimiter
```


on 1.65.0-nightly (2022-08-31 9243168fa5615ec8ebe9)

**Comment by chenyukang** [comment]
the output now changed to:

```console
error: unexpected closing delimiter: `}`
 --> <source>:7:1
  |
1 | fn foo() {
  |          - this delimiter might not be properly closed...
2 |   match 0 {
3 |     _ => {}
  |          -- block is empty, you might have not meant to close it
...
6 |   }
  |   - ...as it matches this but it has different indentation
7 | }
  | ^ unexpected closing delimiter

error: aborting due to previous error
```

Do you think the `block is empty, you might have not meant to close it` should be removed?

**Comment by chenyukang** [comment]
> This is particularly confusing when the `block is empty` points to a macro:
> 
> ```rust
> fn main() {
>     todo!();
> }
> 
> fn other(_: i32)) {}
> ```
> 
> gives
> 
> ```
> error: unexpected closing delimiter: `)`
>  --> src/main.rs:5:17
>   |
> 2 |     todo!();
>   |          -- block is empty, you might have not meant to close it
> ...
> 5 | fn other(_: i32)) {}
>   |                 ^ unexpected closing delimiter
> ```
> 
> on 1.65.0-nightly (2022-08-31 [9243168](https://github.com/rust-lang/rust/commit/9243168fa5615ec8ebe9164c6bc2fdcccffd08b6))

This is changed to:
```console
error: unexpected closing delimiter: `)`
 --> <source>:5:17
  |
1 | fn main() {
  |           - this opening brace...
2 |     todo!();
3 | }
  | - ...matches this closing brace
4 |
5 | fn other(_: i32)) {}
  |                 ^ unexpected closing delimiter
```

it seems more helpful now.

**Comment by estebank** [comment]
Let's close this ticket after adding these two cases to the test suite then. I'm sure there are outstanding issues in this area, but we can ~~rest assured~~hope that we'll get tickets for those more specific cases, while the tests keep us from regressing silently (hopefully, lets make sure the tests are fully annotated so its harder to do that by accident).
