### ISSUE TITLE
Deprecated suggestion message could be better

### ISSUE THREAD

**Issue by ChrisDenton** [rust-lang/rust#98631]
`#![feature(deprecated_suggestion)]` (#94785) produces warning messages that I think could be improved? The current suggestion message doesn't seem ideal to me:

```text
warning: use of deprecated constant `std::sync::ONCE_INIT`: the `new` function is now preferred
 --> src/main.rs:4:32
  |
4 |     const _: Once = std::sync::ONCE_INIT;
  |                                ^^^^^^^^^ help: replace the use of the deprecated constant: `Once::new()`
  |
  = note: `#[warn(deprecated)]` on by default
```

Specifically this part sounds to me more like `Once::new()` is the deprecated constant:

> help: replace the use of the deprecated constant: `Once::new()`

I think something like this would be better, but I don't know how easy it would be to implement a more natural sentence:

> help: replace the use of the deprecated constant with `Once::new()`

**Comment by compiler-errors** [comment]
This is because it's a suggestion, but being rendered inline. You could bump it up to a [verbose suggestion](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_errors/diagnostic/struct.Diagnostic.html#method.span_suggestion_verbose) so it renders more distinctly.

**Comment by ChrisDenton** [comment]
Hm, thinking more about it, could it not be simplified to:

> help: replace with `Once::new()`

Since the help message focuses on what's actionable without repeating less essential information.

**Comment by ChrisDenton** [comment]
Yeah, sorry I edited once I started actually playing with this.

**Comment by compiler-errors** [comment]
I think it's meaningful for the suggestion's message to say what it's doing -- "try replacing with" seems a bit terse. 

I think I still prefer how this would render if we just bumped the suggestion to a verbose (not inclined) suggestion.

**Comment by ChrisDenton** [comment]
Ah ok. My thought was just that it's essentially repeating warning message using slightly different language.
