### ISSUE TITLE
rustdoc-json: Default value of assoc type in blanket impls missing

### ISSUE THREAD

**Issue by Enselic** [rust-lang/rust#98658]
### Step-by-step

Run `cargo +nightly-2022-06-29 rustdoc -- -Z unstable-options --output-format json` with this in `src/lib.rs`:
```rust
pub struct S;
```
and inspect `target/doc/repro.json`.

### Expected result

There is an item for the `Error` of the blanket impl [`impl<T, U> const TryFrom<U> for T where U: ~const Into<T>`](https://doc.rust-lang.org/1.60.0/src/core/convert/mod.rs.html#594-603) and it's default value is `Infallible`.

### Actual 

There is an item but the default value is missing. It looks like this:
```
"2:3121:123": {
    "id": "2:3121:123",
    "crate_id": 2,
    "name": "Error",
    "span": null,
    "visibility": "default",
    "docs": null,
    "links": {},
    "attrs": [],
    "deprecation": null,
    "kind": "assoc_type",
    "inner": {
        "generics": {
            "params": [],
            "where_predicates": []
        },
        "bounds": [],
        "default": null
    }
},
```

When using `nightly-2022-06-28` instead of `nightly-2022-06-29` the information about the default value is present. It looks like this:

```
"2:3126:123": {
    "id": "2:3126:123",
    "crate_id": 2,
    "name": "Error",
    "span": null,
    "visibility": "default",
    "docs": null,
    "links": {},
    "attrs": [],
    "deprecation": null,
    "kind": "typedef",
    "inner": {
        "type": {
            "kind": "resolved_path",
            "inner": {
                "name": "Infallible",
                "id": "2:31923:1960",
                "args": {
                    "angle_bracketed": {
                        "args": [],
                        "bindings": []
                    }
                },
                "param_names": []
            }
        },
        "generics": {
            "params": [],
            "where_predicates": []
        }
    }
},
```

This change, which in practice is a regression, is caused by https://github.com/rust-lang/rust/pull/98577. But we can't revert it of course because that will result in ICEs which is even worse. So we need some kind of follow-up fix.

@rustbot labels +A-rustdoc-json +T-rustdoc +C-bug +requires-nightly

**Comment by GuillaumeGomez** [comment]
It seems like you already suggested a fix. Want to open a PR for it?

**Comment by Enselic** [comment]
Yep I will do that as soon as I get time. Probably today.

**Comment by GuillaumeGomez** [comment]
It's not in a hurry. Don't hesitate to ask if you need help.
