### ISSUE TITLE
lifetime bound when returning impl Trait is not considered

### ISSUE THREAD

**Issue by estaban** [rust-lang/rust#98719]
Lifetimes bounds added to returned `impl Trait` does not seem to be considered by the compiler.

Example: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=02f184ddb3ce9d04c049c93c9d8b25b5

I would expect the above example to compile: `wrap` is defined to return a `'static` Future, so why is the compiler saying that it should have the same lifetime as `&self` ?

The issue does not manifest when returning a concrete type like `MapErr` or `BoxFuture<'static, Reply>`, 

@LucioFranco

**Comment by aliemjay** [comment]
Duplicate of #42940.

@rustbot label A-impl-trait

**Comment by tamird** [comment]
@aliemjay should this be closed as duplicate?
