### ISSUE TITLE
`x check --stage 1 std` doesn't work

### ISSUE THREAD

**Issue by WaffleLapkin** [rust-lang/rust#98720]
For me currently `x b --stage 1 library/std` works fine, while `x c --stage 1 library/std` with **a lot** of errors related to `core` not being found.

> error: could not compile `ppv-lite86` due to 750 previous errors
> error: could not compile `test` due to 60 previous errors
> error: could not compile `proc_macro` due to 2 previous errors

This is the commit that I'm trying to check: https://github.com/rust-lang/rust/pull/98705/commits/c68cd2fa2ec4e3c542b8357596fac61575c842d4

I had the same problem previously too, but it usually solves magically after rebase / `x clean` / etc. However the usual "reboot router" kind of solutions doesn't seem to help this time :')

Full output: [log.txt](https://github.com/rust-lang/rust/files/9021443/log.txt)

**Comment by ehuss** [comment]
It's not really clear to me how #81064 was supposed to work, but commenting out [this line](https://github.com/rust-lang/rust/blob/7425fb293f510a6f138e82a963a3bc599a5b9e1c/src/bootstrap/check.rs#L104) makes it work for me.

**Comment by jyn514** [comment]
Found the issue. I broke this when I added `--all-targets` in https://github.com/rust-lang/rust/pull/88094. Not exactly sure why it's breaking, but it seems fine to me to only run `--all-targets` in stage 0.

Mentoring instructions: change https://github.com/rust-lang/rust/blob/601c5a2087b5c8acd8491c190e99715e91d020d8/src/bootstrap/check.rs#L143 to only run in stage 0.

**Comment by jyn514** [comment]
> It's not really clear to me how #81064 was supposed to work, but commenting out [this line](https://github.com/rust-lang/rust/blob/7425fb293f510a6f138e82a963a3bc599a5b9e1c/src/bootstrap/check.rs#L104) makes it work for me.

The way it works is by building all of libstd before building the compiler: https://github.com/rust-lang/rust/blob/601c5a2087b5c8acd8491c190e99715e91d020d8/src/bootstrap/check.rs#L195-L202
That works fine and makes it ok not to call `add_to_sysroot` in check, but the same step is missing before checking tests and examples. That would be an alternate fix; call `builder.ensure(compile::Std)` before `--all-targets`, not just before building the compiler.

**Comment by jyn514** [comment]
Hmm, I wonder if we should start using `--extern noprelude:core` in bootstrap to avoid all these sysroot shenanigans. It would make the code a lot simpler I think, and avoid having to compile things twice.

**Comment by jo3bingham** [comment]
@jyn514 is the fix here to still only run `--all-targets` in stage0, or is your latest comment a better solution? If the latter, is that an easy solution? This is my first contribution to `rust` so I'm not well versed on how bootstrap, or anything else for that matter, works.

**Comment by jyn514** [comment]
@jo3bingham my second comment is a harder but more correct solution. I would accept either as PRs.

(My third comment about sysroots I think is the ideal solution, but involves several large refactors to bootstrap and isn't a good first PR.)

**Comment by jo3bingham** [comment]
Fixed by #99293. I forgot to link the issue in the PR, but this can be closed now that it has merged.
