### ISSUE TITLE
Rustdoc reduce search rank for deprecated items

### ISSUE THREAD

**Issue by pickfire** [rust-lang/rust#98759]
When user search `radix` the non-const which is deprecated rank higher than the non-deprecated version.

![image](https://user-images.githubusercontent.com/4687791/176887397-4f2c6a53-6a00-40d4-b97f-e5d52e6321f3.png)

Would be nice to reduce rank of deprecated items in search, it appears on the first result.

It would be better if the search result show that the item is deprecated in favor of something else, and that something else have a higher ranking.

@rustbot label A-rustdoc-search C-enhancement T-rustdoc

**Comment by pitaj** [comment]
I'd like to move forward on this. Hopefully we can get an FCP started. The prime motivation for this is to improve search results when searching for numeric constants like `i32::MIN`.

## Problem

Currently, when searching for `i32::MIN`, the deprecated item `std::i32::MIN` shows up before `i32::MIN` in the search results, and there is no indication that `std::i32::MIN` is deprecated until you go to the page for `std::i32::MIN`:
![image](https://user-images.githubusercontent.com/803701/216727045-2e594879-a134-462e-a7b7-261e65113228.png)

And it's even worse if you search for just `MIN`, where all of the deprecated `std::<num>::MIN` items come up above the constants on the number types:
![image](https://user-images.githubusercontent.com/803701/216727349-bae8c7f8-15f4-4c39-8096-629e293b026b.png)

## Resolution

- sort deprecated items lower in the search results
- mark deprecated items as deprecated in search results

`i32::MAX` shows up above `std::i32::MAX` and `core::i32::MAX`
![image](https://user-images.githubusercontent.com/803701/216725619-40afb7b0-e984-4a2e-ab5b-a95b24736b0e.png)
If just searching for `min`, the deprecated results show up far below other things:
![image](https://user-images.githubusercontent.com/803701/216725672-e4325d37-9bfe-47eb-a1fe-0e57092aa811.png)
one page later
![image](https://user-images.githubusercontent.com/803701/216725932-cd1c4a42-d527-44fb-a4ab-5a6d243659cc.png)

And, as you can see, the "Deprecation planned" message shows up in the search results. The same is true for fully-deprecated items like `mem::uninitialized`:
![image](https://user-images.githubusercontent.com/803701/216726268-1657e77a-563f-45a0-85a7-3a0cf4d66d6f.png)

For good measure, the radix search from the OP:
![image](https://user-images.githubusercontent.com/803701/216727528-5f1b6715-a9b1-4a21-99b9-8e2ee6fdd628.png)

**Comment by pitaj** [comment]
Another example from https://github.com/rust-lang/rust/pull/107629#issuecomment-1416300326:

![image](https://user-images.githubusercontent.com/803701/216727989-6eb58508-57dd-46a6-88dc-5e837e7a058d.png)

![image](https://user-images.githubusercontent.com/803701/216727965-18786e0a-26df-45b3-bed5-4699fd97d7cc.png)

**Comment by jsha** [comment]
Fixed by #107629.
