### ISSUE TITLE
Beta 1.63 breaks calloop 0.4.4 build

### ISSUE THREAD

**Issue by YaLTeR** [rust-lang/rust#98750]
### Code

I tried this code: https://github.com/Smithay/calloop/tree/v0.4.4 `cargo check`

I expected to see this happen: successful build

Instead, this happened: build fails on the new beta (1.63)

```
error: implementation of `ErasedIdle` is not general enough
  --> src/loop_logic.rs:96:16
   |
96 |         Idle { callback }
   |                ^^^^^^^^ implementation of `ErasedIdle` is not general enough
   |
   = note: `ErasedIdle` would have to be implemented for the type `Option<Box<dyn for<'r> FnMut(&'r mut Data)>>`
   = note: ...but `ErasedIdle` is actually implemented for the type `Option<Box<(dyn FnMut(&'0 mut Data) + 'static)>>`, for some specific lifetime `'0`
```

### Version it worked on

It most recently worked on: Rust 1.62

### Version with regression

`rustc --version --verbose`:
```
rustc 1.63.0-beta.2 (6c1f14289 2022-06-28)
binary: rustc
commit-hash: 6c1f1428998a08864495bb599840a5997ec175f4
commit-date: 2022-06-28
host: x86_64-unknown-linux-gnu
release: 1.63.0-beta.2
LLVM version: 14.0.5
```

@rustbot modify labels: +regression-from-stable-to-beta -regression-untriaged

**Comment by apiraino** [comment]
bisection points to commit 10f4ce324baf7cfb7ce2b2096662b82b79204944 from #98279 cc @cjgillot 

searched nightlies: from nightly-2022-04-01 to nightly-2022-07-01
regressed nightly: nightly-2022-06-23
searched commits: from https://github.com/rust-lang/rust/commit/dc80ca78b6ec2b6bba02560470347433bcd0bb3c to https://github.com/rust-lang/rust/commit/10f4ce324baf7cfb7ce2b2096662b82b79204944
regressed commit: https://github.com/rust-lang/rust/commit/10f4ce324baf7cfb7ce2b2096662b82b79204944

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.0</summary>


Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --start=2022-04-01 --script=./test.sh 
```
</details>

**Comment by cjgillot** [comment]
Will be fixed by a backport of https://github.com/rust-lang/rust/pull/98637

**Comment by pro465** [comment]
ahh, the usual logic bugs. i hope they dont make it into beta or, even worse, stable in future

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2398750.20Beta.201.2E63.20breaks.20calloop.200.2E4.2E4.20build)).

@rustbot label -I-prioritize +P-critical
