### ISSUE TITLE
Placeholder span used when trait uses a HRTB on itself

### ISSUE THREAD

**Issue by CAD97** [rust-lang/rust#98786]
Given the following code: [[playground]](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=80446f85cb95ca52230fc6521feb1548)

```rust
pub trait Pack<'a> {
    fn pack()
    where
        Self: for<'x> Pack<'x>;
}
```

The current output is:

```
error[E0283]: type annotations needed
  |
  = note: cannot satisfy `Self: Pack<'a>`
```

This should at least point at the `Self: for<'x> Pack<'x>` bound.

Ideally, this should work. (It's unclear why it shouldn't, given other `where Self:` work fine.)

**Comment by ChayimFriedman2** [comment]
As for the "it should work", see #84435.
