### ISSUE TITLE
rustup says its on older rust version but rustc/cargo say otherwise

### ISSUE THREAD

**Issue by jpfreyen** [rust-lang/rust#98788]
I tried this command-line sequence to retrieve a specific rust version:

```rust
 % rustup install 1.59
info: syncing channel updates for '1.59-aarch64-apple-darwin'
info: latest update on 2022-02-24, rust version 1.59.0 (9d1b2106e 2022-02-23)
info: downloading component 'cargo'
info: downloading component 'clippy'
info: downloading component 'rust-std'
 24.2 MiB /  24.2 MiB (100 %)  20.5 MiB/s in  1s ETA:  0s
info: downloading component 'rustc'
 49.9 MiB /  49.9 MiB (100 %)  23.1 MiB/s in  2s ETA:  0s
info: downloading component 'rustfmt'
info: installing component 'cargo'
info: installing component 'clippy'
info: installing component 'rust-std'
 24.2 MiB /  24.2 MiB (100 %)  19.4 MiB/s in  1s ETA:  0s
info: installing component 'rustc'
 49.9 MiB /  49.9 MiB (100 %)  22.3 MiB/s in  2s ETA:  0s
info: installing component 'rustfmt'

1.59-aarch64-apple-darwin installed - rustc 1.59.0 (9d1b2106e 2022-02-23)

% rustc -V
rustc 1.62.0 (a8314ef7d 2022-06-27)
% cargo -V
cargo 1.62.0 (a748cf5a3 2022-06-08)
% rustup install 1.59
info: syncing channel updates for '1.59-aarch64-apple-darwin'

1.59-aarch64-apple-darwin unchanged - rustc 1.59.0 (9d1b2106e 2022-02-23)
```

I expected to see this happen: *rustc, cargo, and the other rust binaries to have version 1.59.0*

Instead, this happened: *rustc -V, cargo -V, etc reports the latest version, 1.62.0*

**Comment by jpfreyen** [comment]
This running on a Apple M1 Max laptop

**Comment by jpfreyen** [comment]
I think I'm ok now, whatever is going on in my environment can get fixed with a

rustup override set 1.59.0

But I find it confusing the "rustup install' would let me know 1.59  apple package was being used but I'd get 1.62.0 if I used a -V on a rust app

**Comment by ehuss** [comment]
`rustup install` installs a toolchain, but does not change the default or any overrides. There are various ways to set the "current" version via [overrides](https://rust-lang.github.io/rustup/overrides.html).  Any of those methods allows you to choose which version is currently being used.

Closing as this isn't the issue tracker for rustup (found at https://github.com/rust-lang/rustup), but also questions on how to use rustup or any tools should go to one of the forums (such as https://users.rust-lang.org/).
