### ISSUE TITLE
Make the default sysroot configurable by rustc_private tools

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#98832]
This code hard-codes the default sysroot to be "one path above the binary":

https://github.com/rust-lang/rust/blob/a3d7a5e94507e3d6618790187bd85250ced82c4f/compiler/rustc_session/src/filesearch.rs#L128-L131

That doesn't work for Miri, which is why it needs various hacks around sysroot (also copied in clippy and rustfmt). We should make the default sysroot configurable in rustc_driver so tools can stop using this hack.

cc https://github.com/rust-lang/rust/pull/97443, @flip1995, @calebcartwright

_Originally posted by @RalfJung in https://github.com/rust-lang/rust/issues/78926#issuecomment-726654086_

**Comment by RalfJung** [comment]
>That doesn't work for Miri, which is why it needs various hacks around sysroot (also copied in clippy and rustfmt)

(Just for the historical record, Miri copied these hacks from Clippy.)

**Comment by ozkanonur** [comment]
I would like to work on this.

@rustbot claim
