### ISSUE TITLE
`--nxcompat` unrecognized option when cross compiling from linux to windows

### ISSUE THREAD

**Issue by Hellzbellz123** [rust-lang/rust#98849]
### Problem

On my wsl2 machine, trying to compile my bevy project with ```cargo build --target=x86_64-pc-windows-msvc -Z unstable-options --out-dir=publish --release``` will work up until the linker gets a random --nxcompat. i also noticed that in the error message its using ld even though clang is setup. setting mold as the linker causes mold to fail from the same error

error output by cargo
```
   Compiling vanillacoffee v0.0.1 (/home/hellzbellz/Source/VanillaCoffee)
error: linking with `clang` failed: exit status: 1
  |
  = note: "clang" "/tmp/rustcVYROkk/symbols.o" "/home/hellzbellz/Source/VanillaCoffee/target/x86_64-pc-windows-msvc/release/deps/vanillacoffee.vanillacoffee.d8322a15-cgu.1.rcgu.o" "-L" "/home/hellzbellz/Source/VanillaCoffee/target/x86_64-pc-windows-msvc/release/deps" "-L" "/home/hellzbellz/Source/VanillaCoffee/target/release/deps" "-L" "/opt/xwin/crt/lib/x86_64" "-L" "/opt/xwin/sdk/lib/um/x86_64" "-L" "/opt/xwin/sdk/lib/ucrt/x86_64" "-L" "/home/hellzbellz/.cargo/registry/src/github.com-1ecc6299db9ec823/windows_x86_64_msvc-0.36.1/lib" "-L" "/home/hellzbellz/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-pc-windows-msvc/lib" "-Wl,--start-group" "-Wl,--end-group" "-Wl,-Bstatic" "/home/hellzbellz/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-pc-windows-msvc/lib/libcompiler_builtins-ce01cad194b518d4.rlib" "-Wl,-Bdynamic" "-lwindows" "-ladvapi32" "-lcfgmgr32" "-lcomctl32" "-ld3d12" "-ld3dcompiler" "-ldwmapi" "-ldxgi" "-lgdi32" "-limm32" "-lkernel32" "-lmmdevapi" "-lmsimg32" "-lole32" "-lopengl32" "-lshcore" "-lshell32" "-lshlwapi" "-lsynchronization" "-luser32" "-luxtheme" "-lwinmm" "-lwinspool" "-lxinput" "-lbcrypt" "-ladvapi32" "-luserenv" "-lkernel32" "-lws2_32" "-lbcrypt" "-lmsvcrt" "-Wl,--eh-frame-hdr" "-Wl,--nxcompat" "-L" "/home/hellzbellz/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-pc-windows-msvc/lib" "-o" "/home/hellzbellz/Source/VanillaCoffee/target/x86_64-pc-windows-msvc/release/deps/vanillacoffee.exe"
  = note: /usr/sbin/ld: unrecognized option '--nxcompat'
          /usr/sbin/ld: use the --help option for usage information
          clang-14: error: linker command failed with exit code 1 (use -v to see invocation)


error: could not compile `vanillacoffee` due to previous error
❯ cargo build --target=x86_64-pc-windows-msvc -Z unstable-options --out-dir=publish --release
```

### Steps

1. set clang as msvc linker
2. be on nightly
3. use xwin to download msvc librarys from windows
4. try to compile

### Possible Solution(s)

judging from the error message it looks like clang is loading the windows gnu api flags and  and adding a compatability flag for something, but it is not working here

### Notes

wsl

config.toml
```
[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-Zshare-generics=y", "-C", "link-arg=--ld-path=/usr/sbin/mold"]

[target.x86_64-pc-windows-msvc]
linker = "clang"
rustflags = [
  "-Zshare-generics=n",
  "-Lnative=/opt/xwin/crt/lib/x86_64",
  "-Lnative=/opt/xwin/sdk/lib/um/x86_64",
  "-Lnative=/opt/xwin/sdk/lib/ucrt/x86_64",
]

[profile.dev]  
opt-level = 1

[profile.dev.package."*"] # # Enable high optimizations for dependencies (incl. Bevy), but not for our code:
opt-level = 3


[profile.release]
lto = "full"
opt-level = 3
[build]
rustc-wrapper = "sccache"
rustflags = ["-Ctarget-cpu=znver3"]
```

### Version

```text
cargo 1.64.0-nightly (dbff32b27 2022-06-24)
release: 1.64.0-nightly
commit-hash: dbff32b27893b899ae2397f3d56d1be111041d56
commit-date: 2022-06-24
host: x86_64-unknown-linux-gnu
libgit2: 1.4.2 (sys:0.14.2 vendored)
libcurl: 7.83.1-DEV (sys:0.4.55+curl-7.83.1 vendored ssl:OpenSSL/1.1.1n)
os: Arch Linux [64-bit]
```

**Comment by ehuss** [comment]
Transferred to rust-lang/rust as cargo is not involved with linking.

You might get better help for cross-compiling by posting on one of the forums (such as https://users.rust-lang.org/).

I suspect you will have better luck by using lld-link instead of mold, as that is designed to emulate MSVC's linker. (That is, set `linker="lld-link"`). 

However, I think this *might* be a real issue with other linkers.  I don't see any linkers that take the `--nxcompat` flag.  It is not clear to me which linker [these lines](https://github.com/rust-lang/rust/blob/b04bfb4aea99436a62f6a98056e805eb9b0629cc/compiler/rustc_codegen_ssa/src/back/linker.rs#L770-L771) are targeting.

**Comment by mati865** [comment]
> I don't see any linkers that take the `--nxcompat` flag. It is not clear to me which linker [these lines](https://github.com/rust-lang/rust/blob/b04bfb4aea99436a62f6a98056e805eb9b0629cc/compiler/rustc_codegen_ssa/src/back/linker.rs#L770-L771) are targeting.

MinGW linkers use that flag. I guess setting clang as the linker caused rustc to use `GccLinker` implementation.

> I suspect you will have better luck by using lld-link instead of mold, as that is designed to emulate MSVC's linker. (That is, set `linker="lld-link"`).

Mold doesn't even support Windows yet. `lld-link` is a good tip, it should make rustc use `MsvcLinker` implementation.

**Comment by theoparis** [comment]
I also ran into this issue with lld-link. I tried x86_64-pc-windows-gnullvm with no luck.

**Comment by mati865** [comment]
You cannot use lld-link with gnullvm targets. Lld-link is purely MSVC linker and for gnullvm targets you should use clang as the linker (depending on its configuration, clang might need to be given `-fuse-ld=lld`).
