### ISSUE TITLE
implied bounds from impl header are not used in associated functions/consts

### ISSUE THREAD

**Issue by aliemjay** [rust-lang/rust#98852]
The following fails to compile although it shouldn't: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=f7287b6897a385360f7190001b58348d

```rust
/// A type with an implied bound `'b: 'a`
struct Ty<'a, 'b>(&'a &'b ());

impl<'a, 'b> Ty<'a, 'b> // <- tait or inherent impl
where
    //'b: 'a, // <- fixed by an explicit bound
{
    fn f() { // <- no `Self` in signature
        Self;
        //~^ ERROR lifetime bound not satisfied
        // Cannot prove WF of `Self` because `'b: 'a` is not known to hold
    }
}
```

Another repro:
```rust
struct Ty<'a, 'b>(&'a &'b ());

impl<'a, 'b> Ty<'a, 'b>{
    fn f() {
        None::<&'a &'b ()>;
        //~^ ERROR lifetime bound not satisfied
    }
}
```

The first repro regressed in 1.43 while the second one is as old as implied bounds.

@rustbot label A-implied-bounds A-associated-items regression-from-stable-to-stable T-types

### Meta

Nightly version: 1.64.0-nightly

(2022-07-01 46b8c23f3eb5e4d0e0aa)

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2398852.20implied.20bounds.20from.20impl.20header.20are.20not.20used.20in.20asso.E2.80.A6)).

@rustbot label -I-prioritize +P-medium

**Comment by aliemjay** [comment]
The same issue exists for associated consts:
```rust
/// A type with an implied bound `'b: 'a`
struct Ty<'a, 'b>(&'a &'b ());

impl<'a, 'b> Ty<'a, 'b> {
    const CONST_1: () = ();
    const CONST_2: () = {
        Self::CONST_1
        //~^ ERROR lifetime may not live long enough
    };
}
```
