### ISSUE TITLE
`std::fmt::Write` methods error documentation

### ISSUE THREAD

**Issue by yoav-lavi** [rust-lang/rust#98861]
### Location

[std::fmt::Write](https://doc.rust-lang.org/std/fmt/trait.Write.html#errors-1)

### Summary

While opening [this issue for Clippy](https://github.com/rust-lang/rust-clippy/issues/9077), I noticed that many of the `write_xyz` methods have the following error description:

> # [Errors](https://doc.rust-lang.org/std/fmt/trait.Write.html#errors-1)
> This function will return an instance of [Error](https://doc.rust-lang.org/std/fmt/struct.Error.html) on error.

While I understand that this is due to the description being general for any implementation, this can seem tautological to someone that's not familiar with these methods and I thought perhaps it'd make sense to expand this a bit and add common scenarios / scenarios implemented by the standard library.

`write_fmt` seems to be missing this description in general.

Thank you!

**Comment by fprasx** [comment]
Hi, I've been looking into this and I can't find an actual implementation of the `Write` trait. All I can find is implementations for types that contain a `dyn Write` already. Seems kinda like a chicken and egg problem, I can only find impl's when the trait has already been implemented. I looked at [`mod.rs` for `core::fmt`](https://doc.rust-lang.org/src/core/fmt/mod.rs.html#163), and all the impl's were chicken-eggy. Does anybody who knows more about this know where I could look to find an actual implementation? If you point me in the right place, I'd be hapy to submit a pull improving the docs :)

**Comment by Havvy** [comment]
The [implementors](https://doc.rust-lang.org/std/fmt/trait.Write.html#implementors) section shows that `String` and `Formatter<'_>` implement the trait. Neither implementation returns the error directly though.

**Comment by thedanvail** [comment]
Would it be fair to have the docs say something along the lines of:

```
This function will return an instance of [`Error`] on error.

Though it is possible for implementors of this trait to return an error, at the time of writing these docs, no implementation of [`std::fmt::Write`] in the standard library returns such an error.

When working with external crates, it is advisable to check the implementation of this trait and program around any possible [`Error`]s.
```

That way, it is clear that std doesn't produce any errors and also that the user should be aware that it *is* a possibility in third-party crates.

**Comment by kpreid** [comment]
> std doesn't produce any errors 

It does: [The internal implementation of `std::fmt::Write` for an `Adapter`](https://github.com/rust-lang/rust/blob/cc4dd6fc9f1a5c798df269933c7e442b79661a86/library/std/src/io/mod.rs#L1665) that wraps a `std::io::Write` produces a `fmt::Error` when the underlying destination returns a `std::io::Error` (while saving that error internally and returning it after the formatting is cancelled).

This can be observed in user code by implementing a formatting trait which is then used with `Write::write_fmt()` on a destination that errors.

**Comment by alexs-sh** [comment]
Hi everyone.
May I kindly ask somebody to take a look into PR: https://github.com/rust-lang/rust/pull/105172

This is a continuation of work on docs. And this is my first PR here. I will be grateful for any comments

**Comment by mwithington** [comment]
Is this still issue still open?

**Comment by chenyukang** [comment]
I think we may close it since https://github.com/rust-lang/rust/pull/105172 was merged.
