### ISSUE TITLE
Cannot join the Rust Discord server.

### ISSUE THREAD

**Issue by iamtheblackunicorn** [rust-lang/rust#98885]
Why on earth can't I join the Rust Discord server???

**Comment by Rageking8** [comment]
Official discord: https://discord.gg/pMvyHeDnXw
Community discord: https://discord.gg/rust-lang-community

**Comment by iamtheblackunicorn** [comment]
@jyn514 I know it isn't a Discord support forum, however, I suspect I've been banned. Therefore I cannot join the Discord server. What would you suggest I do?
