### ISSUE TITLE
Misleading doc about `Vec::into_boxed_slice`

### ISSUE THREAD

**Issue by ark0f** [rust-lang/rust#98908]
### Location

[`Vec::into_boxed_slice`]
[`impl From<Vec<T>> for Box<[T]>`](https://doc.rust-lang.org/nightly/std/boxed/struct.Box.html#impl-From%3CVec%3CT%2C%20A%3E%3E)

### Summary

[`impl From<Vec<T>> for Box<[T]>`](https://doc.rust-lang.org/nightly/std/boxed/struct.Box.html#impl-From%3CVec%3CT%2C%20A%3E%3E) says:

> If v has excess capacity, its items will be moved into a newly-allocated buffer with exactly the right capacity.

When [`Vec::into_boxed_slice`] does not:

> Note that this will drop any excess capacity.

Despite the fact that [`impl From<Vec<T>> for Box<[T]>`](https://doc.rust-lang.org/nightly/std/boxed/struct.Box.html#impl-From%3CVec%3CT%2C%20A%3E%3E) uses [`Vec::into_boxed_slice`] inside

[`Vec::into_boxed_slice`]: https://doc.rust-lang.org/nightly/std/vec/struct.Vec.html#method.into_boxed_slice

**Comment by saethlin** [comment]
I'm confused, what do you think the difference is? Those mean the same thing to me.

**Comment by asquared31415** [comment]
Those do mean the same thing, because "dropping excess capacity" *is* reallocating, which means moving to a new allocation.  However this probably could be clarified/made consistent anyway.  I don't see why these *shouldn't* be identical docs.
