### ISSUE TITLE
ICE with panic!("")

### ISSUE THREAD

**Issue by leonardo-m** [rust-lang/rust#98926]
I have a problem with the latest Nightly, if I compile:

```rust
fn main() {
    panic!("");
}
```

with:

```
rustc test.rs
```

The compiler segfaults immediately. I'm using:

```
rustc 1.64.0-nightly (27eb6d701 2022-07-04)
binary: rustc
commit-hash: 27eb6d7018e397cf98d51c205e3576951d766323
commit-date: 2022-07-04
host: x86_64-pc-windows-gnu
release: 1.64.0-nightly
LLVM version: 14.0.6
```

**Comment by leonardo-m** [comment]
Thank you for trying it. That was on Windows 8.1, later today I'll try the same code on a Windows 11.

**Comment by zombiepigdragon** [comment]
I've also failed to reproduce a crash on Arch Linux, same nightly version.

**Comment by leonardo-m** [comment]
As it sometimes happens, the last Nightly doesn't have this problem, so I close this issue down. I'll reopen it the problem reappears in future.
