### ISSUE TITLE
Calling a trait method as a free function yields odd diagnostics

### ISSUE THREAD

**Issue by yoshuawuyts** [rust-lang/rust#98938]
Given the following code: [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=add44602b791902bc38a5e3faf486c45)

```rust
trait Foo {
    fn bar() {}
}

fn main() {
    Foo::bar();
}
```

The current output is:

```
error[E0283]: type annotations needed
 --> src/main.rs:4:5
  |
4 |     Foo::bar();
  |     ^^^^^^^^ cannot infer type
  |
  = note: cannot satisfy `_: Foo`
```

Ideally the output should look like:

```
Cannot call trait method as a free function. It needs an actual type to be implemented on for it to be called.
```

For bonus points: The trait is currently not callable since it's not implemented for anything. It needs to actually be implemented. "It looks like you're trying to call this trait method, but nothing implements it."

**Comment by aticu** [comment]
This is addressed by #98028. The error message is now

```text
error[E0790]: cannot call associated function on trait without specifying the corresponding `impl` type
 --> test.rs:6:5
  |
2 |     fn bar() {}
  |     ----------- `Foo::bar` defined here
...
6 |     Foo::bar();
  |     ^^^^^^^^ cannot call associated function of trait
```

**Comment by compiler-errors** [comment]
Heads up @obeis #99308

**Comment by obeis** [comment]
@compiler-errors Should i close my pull request #99308
