### ISSUE TITLE
Two closures resolve to the same concrete type.

### ISSUE THREAD

**Issue by importcjj** [rust-lang/rust#98952]
I tried this code:

```rust
fn make_closure(op: bool) -> impl Fn() -> String {
    if op {
        || String::from("true")
    } else {
        || String::from("false")
    }
}

fn main() {
    //let mut a = || String::from("true");
    //a = || String::from("false");

    make_closure(true)();
    make_closure(false)();
}


```

I expected to see this happen: *compiler error: mismatched types*

Instead, this happened: *compile passed*

### Meta

`rustc --version --verbose`:
```
stable 1.62.0
```

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by CryZe** [comment]
I might be wrong on this, but it might be that since they are not capturing anything, they basically become `fn() -> String` which would then mean that they end up being the same type afterall.

**Comment by compiler-errors** [comment]
Yeah, they're probably being coerced to `fn() -> String`.

**Comment by importcjj** [comment]
Ok, Where can I find some documentation to help me understand this?

**Comment by importcjj** [comment]
Thank you!
