### ISSUE TITLE
Wasm export names cause duplicate symbols failure with libc non-exported names

### ISSUE THREAD

**Issue by anuraaga** [rust-lang/rust#98969]
I tried this code:

```rust
#[cfg_attr(
all(target_arch = "wasm32", target_os = "wasi"),
export_name = "malloc"
)]
#[no_mangle]
extern "C" fn _malloc(len: usize) -> *mut u8 {
    let align = std::mem::align_of::<usize>();
    unsafe {
        let layout = Layout::from_size_align_unchecked(len, align);
        alloc(layout)
    }
}

#[cfg_attr(
all(target_arch = "wasm32", target_os = "wasi"),
export_name = "free"
)]
#[no_mangle]
extern "C" fn _free(ptr: *mut u8, len: usize) {
    let align = std::mem::align_of::<usize>();
    unsafe {
        let layout = Layout::from_size_align_unchecked(len, align);
        dealloc(ptr, layout);
    }
}

```

I expected to see this happen: Building for `wasm32-wasi` works

Instead, this happened: Build fails with duplicate symbols

```
  = note: rust-lld: error: duplicate symbol: malloc
          >>> defined in /Users/anuraag/git/wasm-rust/target/wasm32-wasi/debug/deps/libwasm_rust_sdk-aebe23ac30b542fa.rlib(wasm_rust_sdk-aebe23ac30b542fa.r6zw0iop317lob6.rcgu.o)
          >>> defined in /Users/anuraag/.rustup/toolchains/stable-aarch64-apple-darwin/lib/rustlib/wasm32-wasi/lib/self-contained/libc.a(dlmalloc.o)
```

### Meta

I can use different names for the functions but it can make the host more complicated when supporting other wasm compilers like TinyGo where the names for allocation functions can't be changed. It would be nice to be able to use these specific names in Rust, and because the libc `malloc` and `free` aren't wasm exports, I don't think there should technically be any duplicate symbol problem, especially with the rust function names being different.

`rustc --version --verbose`:
```
rustc 1.61.0 (fe5b13d68 2022-05-18)
binary: rustc
commit-hash: fe5b13d681f25ee6474be29d748c65adcd91f69e
commit-date: 2022-05-18
host: aarch64-apple-darwin
release: 1.61.0
LLVM version: 14.0.0
```

**Comment by bjorn3** [comment]
> especially with the rust function names being different.

If you use `#[export_name]` that name will be used as internal symbol name, so there actually is a conflict. While wasm can represent a different internal and export name, I don't think the wasm linking convention used by LLVM can, so we did have to post-process the wasm module if we wanted to support this.

**Comment by anuraaga** [comment]
Thanks @bjorn3. I filed this issue very early in using Wasm and by now I have settled on the simplest pattern for allocating from a host is to not define these sort of functions and pass the link flags to have libc malloc/free themselves exported.

I would be fine with closing this issue since I agree there's a lot of dependencies on LLVM details in the toolchain that we see here.
