### ISSUE TITLE
rustdoc -Z help and -C help are still broken

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#98976]
I tried this: `rustdoc -Zhelp`

I expected to see this happen: A list of unstable options

Instead, this happened:
```
$ rustdoc +stage1 -Zhelp
error: unknown unstable option: `help`

$ rustdoc +stage1 -Chelp
error: unknown codegen option: `help`
```

The options need to be built *after* checking for help, not before.
https://github.com/rust-lang/rust/blob/0567674460504d916c254696e1b25082f72a66bf/src/librustdoc/config.rs#L338-L355

cc @GuillaumeGomez

### Meta

`rustc --version --verbose`: 0567674460504d916c254696e1b25082f72a66bf

**Comment by GuillaumeGomez** [comment]
Thanks for the feedback. I'll send a fix as soon as possible.
