### ISSUE TITLE
implement a proper REPL

### ISSUE THREAD

**Issue by thestinger** [rust-lang/rust#9898]
It shouldn't re-compile and re-run the entire input so far with each new addition, and should be able to recover from a compilation error or failure. This should likely be implemented in a separate repository until it's solid and has a working test suite.

A good basis for the design would be the [cling](http://root.cern.ch/drupal/content/cling) REPL for C++ built on top of libclang using LLVM's JIT compiler.

**Comment by steveklabnik** [comment]
I'm pulling a massive triage effort to get us ready for 1.0. As part of this, I'm moving stuff that's wishlist-like to the RFCs repo, as that's where major new things should get discussed/prioritized.

This issue has been moved to the RFCs repo: rust-lang/rfcs#655
