### ISSUE TITLE
 Implement `TryFrom<&OsStr>` for `&str`

### ISSUE THREAD

**Issue by aticu** [rust-lang/rust#99031]
# Proposal

## Problem statement

Currently it is impossible through use of the standard conversion traits to convert from an `&OsStr` to a `&str`.

## Motivation, use-cases

Adding an implementation of `TryFrom<&OsStr>` for `&str` makes this conversion more discoverable to users who are already familiar with the `TryFrom` trait. They may even expect such an implementation to exist.
Additionally it allows the use of `&OsStr` in more generic methods such as those that  accept `impl TryInto<&str>`:

```rust
fn maybe_print<'a>(arg: impl TryInto<&'a str>) {
    if let Ok(converted) = arg.try_into() {
        println!("{converted}");
    }
}
```

## Solution sketches

Implement `TryFrom<&OsStr>` for `&str`.

## Links and related work

Implementation PR: rust-lang/rust#98202

## What happens now?

This issue is part of the libs-api team [API change proposal process]. Once this issue is filed the libs-api team will review open proposals in its weekly meeting. You should receive feedback within a week or two.

[API change proposal process]: https://std-dev-guide.rust-lang.org/feature-lifecycle/api-change-proposals.html

**Comment by dwattttt** [comment]
Is this ever able to succeed on Windows? An OsStr there is not utf8, and this is known at compile time. Relegating it to a runtime failure seems a poor result.

**Comment by ChrisDenton** [comment]
On Windows we use [WTF-8](https://simonsapin.github.io/wtf-8/) for `OsStr`. This is a superset of UTF-8 and in practice will almost always be valid UTF-8.

**Comment by ChrisDenton** [comment]
Windows itself uses "WTF-16" (aka UTF-16 with unpaired surrogates) but the standard library translate from/to WTF-8 at the API boundary. We also guarantee that an `&str` is bit-for-bit compatible with an `OsStr` (see [`impl AsRef<OsStr> for &str`](https://doc.rust-lang.org/std/primitive.str.html#impl-AsRef%3COsStr%3E)) so the reverse must also be true for any string that can be represented in UTF-8.

**Comment by dwattttt** [comment]
Ah that makes sense. I had no idea an OsStr(ing) needed a copy for win32 (except maybe for Win11)

**Comment by yaahc** [comment]
looks like rfcbot had issues with the issue transfer from the libs-team repo.

**Comment by yaahc** [comment]
The final comment period, with a disposition to merge, as per the https://github.com/rust-lang/rust/issues/99031#issuecomment-1178345763, is now complete.

As ~~the automated~~ a representative of the governance process, I would like to thank the author for their work and everyone else who contributed.

This will be merged soon.
