### ISSUE TITLE
Bootstrap: Initialized submodules no longer eagerly updated by running x.py

### ISSUE THREAD

**Issue by bjorn3** [rust-lang/rust#99083]
`maybe_update_submodules` should already do this, but https://github.com/rust-lang/rust/blob/c4693bc946729393c087fb120af566395915d19d/src/bootstrap/lib.rs#L628-L635 hasn't been kept in sync with the removal of identical functionality from x.py. Also rust-analyzer is only updated when vendoring is enabled.

**Comment by matthiaskrgr** [comment]
I think this was caused by https://github.com/rust-lang/rust/pull/97513
