### ISSUE TITLE
Nested macros called with "constant" fragments can't capture said fragments as "constant"

### ISSUE THREAD

**Issue by MasterPtato** [rust-lang/rust#99106]
### Context
This is a bug related to the unstable feature [macro metavariable expressions](https://github.com/rust-lang/rust/issues/83527).
### Issue
Nested macros called with "constant" fragments from within another macro don't keep that "constant" status for the inner macro call.

```rust
macro_rules! outer {
    (0) => {
        outer!(1)
    };
    ($lit:literal) => {
        macro_rules! inner {
            (1) => {
                println!("constant fragment")
            };
            ($$lit:literal) => {
                println!("literal fragment")
            };
        }

        inner!($lit);
        inner!(1);
    };
}

fn main() {
    outer!(0);
    inner!(1);
}
```
Working example: [Rust Playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=5a323561daf700bc2c00b3ba04334ac5)

### Expected output
```
constant fragment
constant fragment
constant fragment
```
### Actual output
```
literal fragment
constant fragment
constant fragment
```

<br>

> PS: The title and issue description are a bit hard to understand, clarity suggestions are appreciated.

**Comment by c410-f3r** [comment]
Happens with or without `$$`.

```rust
macro_rules! outer {
    ($dollar:tt 0) => {
        outer!($dollar 1)
    };
    ($dollar:tt $outer_lit:literal) => {
        macro_rules! inner {
            (1) => {
                println!("constant fragment")
            };
            ($dollar inner_lit:literal) => {
                println!("literal fragment")
            };
        }

        inner!($outer_lit);
        inner!(1);
    };
}

fn main() {
    outer!($ 0);
    inner!(1);
}
```

@rustbot labels +A-macro

**Comment by MasterPtato** [comment]
Interesting. In that case, it has nothing to do with nested macro definitions or [macro metavariable expressions](https://github.com/rust-lang/rust/issues/83527), just nested macro calls.

I went ahead and simplified the example:
```rust
macro_rules! test {
    ($lit:literal) => {
       test!(@ $lit);
    };
    (@ 1) => {
       println!("constant fragment");
    };
    (@ $lit:literal) => {
       println!("literal fragment");
    };
}

fn main() {
    test!(1);
    test!(@ 1);
}
```

Working example: [Rust Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=b0f6158f5fb62cf994e9098aebdbb8a9)
### Expected output
```
constant fragment
constant fragment
```

### Actual output
```
literal fragment
constant fragment
```

**Comment by CAD97** [comment]
This is a deliberate design choice of `macro_rules!`: once you've "opacified" a tokenstream into a binder fragment, it's not possible to open it up again. This is important for a macro like the following:

```rust
macro_rules! mul {
    ($l:expr, $r:expr) => ($l * $r);
}

mul!(1 + 2, 3 + 4)
```

such that the expansion is `(1 + 2) * (3 + 4)` and not `1 + (2 * 3) + 4`.

When you capture a binder fragment, you get a [None-delimited](https://doc.rust-lang.org/stable/proc_macro/enum.Delimiter.html#variant.None) stream, essentially `#( 1 + 2 )#`, which makes it impossible to introspect the contents of the stream (without stripping the group in a proc-macro).

**Comment by MasterPtato** [comment]
Thanks for the reply and explanation. It would be a nice feature to create some downright disgusting recursive macros, but hygiene is important :blush:
