### ISSUE TITLE
Perf: investigate manual inlining in layout.rs

### ISSUE THREAD

**Issue by CAD97** [rust-lang/rust#99117]
Due to how many different times the layout code is instantiated, seemingly inconsequential changes can have noticeable impact on compile perf.

It may be beneficial to investigate some manual inlining (open coding) of code in the layout code (e.g. replacing `?` and other option/result combinators with `match`/`return`) to reduce the amount of IR LLVM has to deal with.

**Comment by nnethercote** [comment]
Another idea: `Layout::from_size_align` does two checks. One for alignment, one for size. I think the places where it was used in #95295 only need the size check. So an alternative unsafe version of `Layout::from_size_align` that does just the size check might help.

**Comment by scottmcm** [comment]
[`mem::ValidAlign`](https://github.com/rust-lang/rust/blob/c396bb3b8a16b1f2762b7c6078dc3e023f6a2493/library/core/src/mem/valid_align.rs#L5-L12) represents the alignment check in the type system, so I think it could even be safe but still only have the one check.

**Comment by CAD97** [comment]
If only tidy hadn't slowed me down I could've posted the PR before you said that 😛

**Comment by jyn514** [comment]
It looks like https://github.com/rust-lang/rust/pull/99136 implemented this? Is there more work left to do?

**Comment by nnethercote** [comment]
I think it's time to declare victory.
