### ISSUE TITLE
Indexing by a borrowed type could suggest dereferencing

### ISSUE THREAD

**Issue by itsliamegan** [rust-lang/rust#99125]
When indexing a `Vec` by an `&usize`, the error message was somewhat non-specific. I looked at the types and figured out that I just needed to dereference the borrowed value but it might've been helpful to have that more apparent. I'm sure the same error occurs in more general cases, but this is the specific one I encountered it in.

Here's [an example](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=fbf18c1d71917bcd0799f15da7996b64):

```rust
fn main() {
    let values = Vec::<String>::new();
    let index: usize = 0;
    let index_ref = &index;
    values[index_ref]; 
}
```

And the error message:

```
error[E0277]]: the type `[String]` cannot be indexed by `&usize`
 --> src/main.rs:5:5
  |
5 |     values[index_ref]; 
  |     ^^^^^^^^^^^^^^^^^ slice indices are of type `usize` or ranges of `usize`
  |
  = help: the trait `SliceIndex<[String]>` is not implemented for `&usize`
  = help: the trait `SliceIndex<[T]>` is implemented for `usize`
  = note: required because of the requirements on the impl of `Index<&usize>` for `Vec<String>`
```

Perhaps some kind of hint at the bottom suggesting to add `*` to  `index_ref`, i.e. `*index_ref`?

**Comment by compiler-errors** [comment]
I think this is a dupe of #96678

**Comment by itsliamegan** [comment]
I didn't find that with my initial search, but indeed it is! :+1:
