### ISSUE TITLE
Run `x test --stage 1` in CI

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#99135]
Similar to https://github.com/rust-lang/rust/issues/95996, we expect contributors to run this frequently, so it should be tested in CI.

@eddyb suggested using the defaults in https://github.com/rust-lang/rust/blob/7443cc2bd66a79aa5a624e11b9b0172e56c2da48/src/bootstrap/defaults/config.compiler.toml#L1 but I'm a little hesitant to do that because some of them are *very* wrong for CI (e.g. `download-ci-llvm`) and others shouldn't affect tests but make the compiler slower (e.g. `debug-logging = true`). I do agree we should enable incremental for these tests, though.

Not sure which builder to add these to - adding it to mingw-check would make it significantly slower, and I don't know which of the full builders has spare capacity. @pietroalbini do you have suggestions?

_Originally posted by @eddyb in https://github.com/rust-lang/rust/pull/98660#issue-1288306531

**Comment by eddyb** [comment]
To be clear, I was mistakenly under the impression that *only* stage1 tests were ran for PR CI.
But I could see how that may be an issue for `ignore-stage1` tests (though, is it easy to *only* run those in stage2?).

**Comment by jyn514** [comment]
> To be clear, I was mistakenly under the impression that _only_ stage1 tests were ran for PR CI.

ah yeah no, we currently run `x test --stage 2` in PR CI. I think it might make sense to only run `--stage 1` now that you mention it though! would be a lot faster and in practice there are very few tests that only fail in stage 2.

> though, is it easy to only run those in stage2?

not currently, no - I think it wouldn't be impossible to add to compiletest though, it already does filtering and parses the headers, so it should be possible to combine the two.

**Comment by pietroalbini** [comment]
@jyn514 just add another builder, we have capacity for that.

**Comment by eddyb** [comment]
If we do get another builder, can we have incremental enabled on it (or rather, whichever dev profile enables that)?

Some codegen tests haven't been passing for a short while because of the difference, and might be good to be tracking something that strongly resembles local workflows.

**Comment by jyn514** [comment]
@eddyb
> I'm a little hesitant to do that because some of them are very wrong for CI (e.g. download-ci-llvm) and others shouldn't affect tests but make the compiler slower (e.g. debug-logging = true). I do agree we should enable incremental for these tests, though.

**Comment by Milo123459** [comment]
What is the correct course of action here? Adding another builder?

**Comment by jyn514** [comment]
Yes, adding another builder is enough. I want to investigate running --stage 1 *instead* of --stage 2 long term, but that's harder and shouldn't block testing this.

**Comment by RalfJung** [comment]
This would have caught https://github.com/rust-lang/rust/issues/99619, I assume?

**Comment by eddyb** [comment]
@RalfJung Yes, despite not being filed as an issue, that's exactly the kind of test failure I was referencing in https://github.com/rust-lang/rust/issues/99135#issuecomment-1186623983 (it does require that we do enable incremental, not just test at stage 1).
