### ISSUE TITLE
Run compiler doctests in CI

### ISSUE THREAD

**Issue by jyn514** [rust-lang/rust#99144]
Right now these are only ever run locally, which means they often break. We should run these in CI.

See https://github.com/rust-lang/rust/issues/99144#issuecomment-1269609271 for mentoring instructions.

_Originally posted by @jyn514 in https://github.com/rust-lang/rust/issues/95994#issuecomment-1097487862_

**Comment by jyn514** [comment]
Maybe `x86_64-gnu-aux` is a good place? That has some existing "misc tests", and already builds stage 2 rustc, so shouldn't slow down the builder too much.

**Comment by Mark-Simulacrum** [comment]
Seems okay. Any test builder under 2 hours right now on Linux is probably fine.

**Comment by jyn514** [comment]
@reez12g see https://github.com/rust-lang/rust/pull/99040 for an example of something similar

**Comment by lokera666** [comment]
@rustbotreclamar

**Comment by jyn514** [comment]
Ok, this is not working. If you want to work on this issue, please also say which crate you are working on; doing one crate at a time is fine. It's ok to work on crates that haven't yet been claimed.

**Comment by GentBinaku** [comment]
@jyn514  I have working on the first crate rustc_ast_lowering, I finish this week I will do a Pull request

**Comment by CarsonV** [comment]
rustc_query_impl is done, claiming rustc_infer next while Gent works on ast_lowering

**Comment by Ezrashaw** [comment]
Claiming `rustc_builtin_macros`
