### ISSUE TITLE
remove box special handling from cranelift

### ISSUE THREAD

**Issue by oli-obk** [rust-lang/rust#99170]
https://github.com/rust-lang/rust/blob/b3f4c3119957aa0a250cab08ab586b7a9a680ef1/compiler/rustc_codegen_cranelift/src/base.rs#L813 is still doing some special handling for `Box`, even though there are no more `Deref` for boxes at codegen time anymore. The special handling can be removed without replacement. For sanity it may be replaced by an assertion that the type is never `Box`.

**Comment by ritikBhandari** [comment]
Hi,
Can I take up this issue?

**Comment by oli-obk** [comment]
of course! you can claim this issue by using the command mentioned in https://rustc-dev-guide.rust-lang.org/rustbot.html?highlight=claim#issue-claiming

**Comment by ritikBhandari** [comment]
thank you @oli-obk !

**Comment by chenyukang** [comment]
@ritikBhandari  are you still working on it?

**Comment by chenyukang** [comment]
This is fixed in https://github.com/rust-lang/rust/commit/6d5e8f384362ed250f946ccd35bcc52a65817380, we could close this issue.
