### ISSUE TITLE
LLVM crash/assertion failure in LazyCallGraph when compiling in release mode

### ISSUE THREAD

**Issue by danielframpton** [rust-lang/rust#99196]
Updating to a new version of rustc (1.59) triggers a segfault when compiling in release mode targeting x86_64/Linux.

By building a version of rustc with LLVM assertions I see the following assertion failure for the crate that was failing:

```
rustc: /home/daniel/rust/src/llvm-project/llvm/lib/Analysis/LazyCallGraph.cpp:1538: void llvm::LazyCallGraph::removeDeadFunction(llvm::Function&): Assertion `RC.size() == 1 && "Dead functions must be in a singular RefSCC"' failed.
Aborted
```

The bug can be worked around by changing codegen units.

**Comment by Qi-Hu** [comment]
Is this issue already fixed in [https://github.com/llvm/llvm-project/issues/56503](https://github.com/llvm/llvm-project/issues/56503)?

**Comment by nikic** [comment]
As the upstream LLVM issue is fixed and there is no rust reproducer to verify, I'm closing this issue.
