### ISSUE TITLE
Unintuitive error when recursing with generic Fn closure borrow

### ISSUE THREAD

**Issue by rob9315** [rust-lang/rust#99250]
i understand why this error happens, it might just be nice to have some sort of system to detect
when this kind of recursion is happening and try to prevent it or at least hint at what the error
could be better.

Given the following code: 

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=1974b5d37cb10e1214937db3c0e779dc

The current output is:

```
   Compiling playground v0.0.1 (/playground)
error: reached the recursion limit while instantiating `<iter::adapters::GenericShunt<Ma...terator>::collect::<Vec<String>>`
     |
note: `collect` defined here
     = note: the full type name has been written to '/playground/target/debug/deps/playground-f30fbb6d88a6f004.long-type.txt'

error: could not compile `playground` due to previous error
```
`/playground/target/debug/deps/playground-f30fbb6d88a6f004.long-type.txt`:
`<iter::adapters::GenericShunt<Map<std::vec::IntoIter<String>, &&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&[closure@error/src/main.rs:9:41: 14:6]>, Result<Infallible, ()>> as Iterator>::collect::<Vec<String>>`

Ideally the output should look like:

```
 |
 |    .map(|input| weird_recursive(input, &f))
 |                                        ^^
 = note: borrow of generic argument in loop when recursing,
 = note: consider changing your function signature
```

**Comment by Chris00** [comment]
The error message could also be improved for *mutually recursive* generic functions: see [playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=2db97396b1ed21205193fc4da4cc92c1).  For this minimal example, the error is still clear but, in my case,  the error was:
```
error[E0275]: overflow evaluating the requirement `[closure@src/bin/compare_damping.rs:47:13: 47:21]: Fn<(Complex<f64>,)>`
  |
  = help: consider increasing the recursion limit by adding a `#![recursion_limit = "256"]` attribute to your crate (`compare_damping`)
  = note: required for `&[closure@src/bin/compare_damping.rs:47:13: 47:21]` to implement `Fn<(Complex<f64>,)>`
  = note: 128 redundant requirements hidden
  = note: required for `&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&[closure@src/bin/compare_damping.rs:47:13: 47:21]` to implement `Fn<(Complex<f64>,)>`

For more information about this error, try `rustc --explain E0275`.
```
which did not even refer to the library function; it only pointed to the call site (which was *not* the recursive function) and was not giving appropriate advice.

In this case, the advice should be to define a struct holding the generic parameters and define the mutually recursive functions as methods (so they are instantiated once).

**Comment by Enselic** [comment]
Closing as duplicate to https://github.com/rust-lang/rust/issues/50043
