### ISSUE TITLE
std::fs::create_dir_all can spuriously fail on OpenBSD

### ISSUE THREAD

**Issue by ltratt** [rust-lang/rust#99280]
I have a process which repeatedly calls `create_dir_all` in a thread on OpenBSD and, for a directory that already exists, perhaps once in perhaps 5 calls it returns `Is a directory (os error 21)` (which is true -- it is a directory!). Unfortunately I have not managed to replicate this in a small test program, so presumably there is a race condition going on.

What I have noticed is that `create_dir_all` works subtly different than `mkdir(1)`. Here's `create_dir_all`:

```rust
    fn create_dir_all(&self, path: &Path) -> io::Result<()> {
        if path == Path::new("") {
            return Ok(());
        }

        match self.inner.mkdir(path) {
            Ok(()) => return Ok(()),
            Err(ref e) if e.kind() == io::ErrorKind::NotFound => {}
            Err(_) if path.is_dir() => return Ok(()),
            Err(e) => return Err(e),
        }
        match path.parent() {
            Some(p) => self.create_dir_all(p)?,
            None => {
                return Err(io::const_io_error!(
                    io::ErrorKind::Uncategorized,
                    "failed to create whole tree",
                ));
            }
        }
        match self.inner.mkdir(path) {
            Ok(()) => Ok(()),
            Err(_) if path.is_dir() => Ok(()),
            Err(e) => Err(e),
        }
    }
```

Here's OpenBSD's equivalent (from [mkdir.c](https://github.com/openbsd/src/blob/master/bin/mkdir/mkdir.c)):

```c
mkpath(char *path, mode_t mode, mode_t dir_mode)
{
	struct stat sb;
	char *slash;
	int done;

	slash = path;

	for (;;) {
		slash += strspn(slash, "/");
		slash += strcspn(slash, "/");

		done = (*slash == '\0');
		*slash = '\0';

		if (mkdir(path, done ? mode : dir_mode) == 0) {
			if (mode > 0777 && chmod(path, mode) == -1)
				return (-1);
		} else {
			int mkdir_errno = errno;

			if (stat(path, &sb) == -1) {
				/* Not there; use mkdir()s errno */
				errno = mkdir_errno;
				return (-1);
			}
			if (!S_ISDIR(sb.st_mode)) {
				/* Is there, but isn't a directory */
				errno = ENOTDIR;
				return (-1);
			}
		}

		if (done)
			break;

		*slash = '/';
	}

	return (0);
}
```

As I read things, for a path `/a/b/c` Rust's `create_dir_all` first tries to see if `/a/b/c` exists and, if it doesn't, tries `/a/b/` and then `/a/`. As soon as it finds a directory which does exist, it then works its way back up the recursive stack, creating the rest.

In contrast, OpenBSD's `mkdir` starts at `/a`; if it doesn't exist it creates it; either way it then moves to `/a/b/` and so on until it's checked that every directory along the way exists.

Rust's `create_dir_all` is, on the face of things, more efficient if `/a/b/c` already exists, but probably less efficient if it doesn't exist, and also has a sort-of race condition where it might check for `/a/b/`'s existence, find it doesn't exist, try creating it, only to find someone else has created it or altered it in the interim and then... presumably, boom? I'm also not clear how stale the information about `path` it has might be, which might also be a source of a race condition.

(CC @semarie who's much more expert on OpenBSD and Rust than I am)

**Comment by rseymour** [comment]
I mentioned this on twitter, but the time of check, time of dir creation (TOCTOU) issue has a greater time delta in the rust version and could have particularly nasty effects with some dir chains being created in parallel. Either way Error handling seems to be the best way to avoid this.

**Comment by the8472** [comment]
Probably not a concern in practice but asymptotically it's probably more efficient to perform a binary search to find the deepest existing ancestor.

**Comment by semarie** [comment]
@ltratt do you reproduce the same problem on other OS ? (`create_all_dir()` isn't OpenBSD specific).

else, could you run your program with ktrace(2) ? (`ktrace -di program` ; `kdump -H -TR`)

**Comment by ltratt** [comment]
@semarie It's happening in a network facing daemon and the problem happens intermittently under some sort of load: I haven't been able to work out any real way to replicate it. My best attempt to cut the problem down is something like:

```
use std::{io::Write, thread};

fn main() {
    std::fs::create_dir_all("/tmp/t").unwrap();
    let mut threads = Vec::new();
    for _ in 0..5 {
        threads.push(thread::spawn(|| {
            for _ in 0..10000 {
                std::fs::create_dir_all("/tmp/t").unwrap();
            }
        }));
    }

    for _ in 0..5 {
        threads.push(thread::spawn(|| {
            for _ in 0..10000 {
                tempfile::Builder::new()
                    .prefix("tmp_")
                    .tempfile_in("/tmp/t")
                    .unwrap()
                    .keep()
                    .unwrap()
                    .0
                    .write_all("test".as_bytes())
                    .ok();
            }
        }));
    }

    for t in threads {
        t.join().unwrap();
    }
}
```

but this doesn't trigger the bug. I'm at a bit of a loss, to be honest.

**Comment by ltratt** [comment]
Further investigation suggestions that this is probably due to a dodgy disk/file system. Closing unless I can actually find a way to replicate this on another box.
