### ISSUE TITLE
`std::intrinsics::copy_nonoverlapping` is marked unstable on the latest nightly

### ISSUE THREAD

**Issue by Aaron1011** [rust-lang/rust#99286]
### Code

I tried this code:

```rust
use std::intrinsics::copy_nonoverlapping;
```

I expected to see this happen: Compilation succeeds

Instead, this happened:

```
error[E0658]: use of unstable library feature 'core_intrinsics': intrinsics are unlikely to ever be stabilized, instead they should be used through stabilized interfaces in the rest of the standard library
 --> unstable.rs:1:5
  |
1 | use std::intrinsics::copy_nonoverlapping;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  |
  = help: add `#![feature(core_intrinsics)]` to the crate attributes to enable

error: aborting due to previous error; 1 warning emitted
```

### Version it worked on

`rustc 1.62.0 (a8314ef7d 2022-06-27)`

It most recently worked on: 

### Version with regression

```
rustc 1.64.0-nightly (c2f428d2f 2022-07-14)
binary: rustc
commit-hash: c2f428d2f3340a0e7d995f4726223db91b93704c
commit-date: 2022-07-14
host: x86_64-unknown-linux-gnu
release: 1.64.0-nightly
LLVM version: 14.0.6
```

**Comment by TheButlah** [comment]
My build uses [`bevy`](bevyengine/bevy) which in turn is affected by this regression via its dependency on [`inplace_it`](https://github.com/NotIntMan/inplace_it/pull/11)

**Comment by vivi90** [comment]
## Workaround in the meantime
Using the last working version of `rustc`:
 1. Install via: `rustup toolchain install nightly-2022-07-13`
 2. Using everytime `cargo +nightly-2022-07-13 run --release` for testing.
