### ISSUE TITLE
Rust-cargo bug

### ISSUE THREAD

**Issue by feridinverien** [rust-lang/rust#99328]
https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

I tried this code:

```rust
<code>
```

I expected to see this happen: *explanation*

Instead, this happened: *explanation*

### Meta

`rustc --version --verbose`:
```
<version>
```

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

**Comment by Nilstrieb** [comment]
Do you have any information on the bug? Like an error message or backtrace?

**Comment by JohnTitor** [comment]
Please fill out the form and re-open if needed, thanks!
