### ISSUE TITLE
#[test] function name with `r#keyword` be auto filtered out by test framework.

### ISSUE THREAD

**Issue by Wyvern** [rust-lang/rust#99361]
If put Rust `keyword` in a #[test] function name like `r#for` `r#while` `r#break` etc, e.g.
```
  #[test]
  fn r#mod(){
        //...
    }
```
then run test, the test case will be auto filtered out without warning/error. 
output:
```
running 0 tests
test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 1 filtered out; finished in 0.00s
```
is it by design, or an unintentional bug?

env: VScode+RA on nightly channel Rust

**Comment by CryZe** [comment]
This seems to be a rust-analyzer bug. `cargo test` works just fine for me.
