### ISSUE TITLE
memory leak in docker 

### ISSUE THREAD

**Issue by zirill** [rust-lang/rust#99364]
i tested:

FROM alpine:3.16 
musl version release
leak in docker and home system

FROM debian:stable-slim
defult version release
leak only docker container
home system not leak 

rustc 1.62.0 (a8314ef7d 2022-06-27)
cargo 1.62.0 (a748cf5a3 2022-06-08)

**Comment by the8472** [comment]
The information you provided is not sufficient to reproduce the issue. Please provide some example code and steps to reproduce the behavior.

**Comment by zirill** [comment]
Are there tools that can show under the docker where the leak is?

**Comment by zirill** [comment]
The value of the "mem usage" parameter  (docker stats)

When a certain api is called, there is a leak.
But because it is large, it takes a significant amount of time to find in which function it happens.
Considering that you have to create a new docker image for each test. (no leaks in home system)

**Comment by zirill** [comment]
When you do some actions this value does not change significantly, the memory usage increases and returns. 30-40-30 (mb)

In that case there is a sharp increase, growth without return. 30-100-200-800-1200 (mb)

I will try to find the section when in which this happens.

**Comment by workingjubilee** [comment]
...Ah, "this uses a gig" _is_ somewhat remarkable, even for more... voracious possible Docker configurations. Anything you can do to offer a reproduction case would help, yes.
