### ISSUE TITLE
Confusing "arbitrary expressions aren't allowed in patterns" error

### ISSUE THREAD

**Issue by est31** [rust-lang/rust#99380]
Take the following code:

```rust
macro_rules! foo {
    ($p:expr) => {
        if let $p = Some(42) {
            return;
        }
    };
}

fn main() {
    foo!(Some(3));
}
```

Currently it fails with:

```
error: arbitrary expressions aren't allowed in patterns
  --> src/main.rs:10:10
   |
10 |     foo!(Some(3));
   |          ^^^^^^^
```

If you expanded the macro manually, `Some(3)` would be parsed as a pattern, but the `$p:expr` above changes it to be parsed as an expression. So what you *need* to do here is to change the `$p:expr` above to `$p:pat`. But this is very non-obvious.

Ideally, the compiler would try to check if the input is a valid pattern, and if so, add a note like "`Some(3)` is a valid pattern but the metavariable $p is specified to be an expression", and maybe also point to the metavariable's matcher.

@rustbot label A-macros

**Comment by alexpetros** [comment]
Finding this issue saved me a lot of time, and I think adding this error to the compiler would help!

**Comment by est31** [comment]
I've looked into this and adding an error message is harder than I thought. The issue is that the span provided to the `lower_expr_within_pat` function is already resolved to the original location of the `Some(3)` so calling `.from_expansion()` isn't going to help much.

I *can* add a check like `is_approximately_pattern` or something, but it then causes basically anything to be recognized, even if it has never been from a macro matcher, so usually the hint would be a false positive.
