### ISSUE TITLE
DynMetadata equality is not documented

### ISSUE THREAD

**Issue by alercah** [rust-lang/rust#99388]
### Location
https://doc.rust-lang.org/std/ptr/struct.DynMetadata.html

### Summary
There is no documentation as far as I should see that defines the behaviour of the `PartialEq` impl for `DynMetadata`. I think the guarantees that are made or not made should be documented. For instance, are vtables for a given concrete type guaranteed to be unique? People will assume they are, and that `==` will tell you if the types match. It would not surprise me to learn that this is wrong.

**Comment by SimonSapin** [comment]
Vtables are likely not unique at the moment. Yes, documenting that explicitly sounds good. Related: https://github.com/rust-lang/rust/issues/69757

**Comment by nbdd0121** [comment]
Is it necessary to have `PartialEq` implementaton on `DynMetadata`?

**Comment by SimonSapin** [comment]
All raw pointers (including to trait objects) implement `PartialEq`, and they conceptually do it by comparing `(ptr as *const (), metadata(ptr))`. For that formulation to work, we’d need `DynMetadata: PartialEq`. This is currently reflected in `Pointee::Metadata` having a `PartialEq` bound.

However the current implementation of raw pointer comparison is just bitwise comparison and does not go through `metadata()`, so it would *technically* be possible to remove this bound and impl. I’m not sure it’s desirable, though.

**Comment by RalfJung** [comment]
One can compare vtable pointers via wide raw pointer comparison, so for better or worse I think we should also allow it on `DynMetadata`. That might be a good place to document the footguns related to comparison of vtables.
