### ISSUE TITLE
`error: cannot open rcrt1.o: No such file or directory` while running `src/test/ui/process/nofile-limit.rs`

### ISSUE THREAD

**Issue by Logarithmus** [rust-lang/rust#99382]
### Steps to reproduce
1. `git clone https://github.com/rust-lang/rust`
2. `./x.py setup`
3. Choose `compiler`
4. `./x.py test src/test/ui`

### Expected behavior
All tests should pass

### Actual behavior
```
   = note: ld: error: cannot open rcrt1.o: No such file or directory
           collect2: error: ld returned 1 exit status
error: aborting due to previous error
------------------------------------------
failures:
    [ui] src/test/ui/process/nofile-limit.rs
```

### System
Void Linux rolling
I guess `./x.py` uses its own bootstrap compiler, so `rustup` toolchain version is irrelevant, but anyway, it's `1.61`.

**Comment by tmiasko** [comment]
With `-Ctarget-feature=+crt-static` rustc will try to auto detect support for `static-pie` in the linker. Unfortunately on Void Linux, linker does support the option, but required object files are missing (it seems glibc is built without `--enable-static-pie`):

```console
# echo 'int main(){}' > a.c
# gcc -static-pie a.c
/usr/sbin/ld: cannot find rcrt1.o: No such file or directory
collect2: error: ld returned 1 exit status
```

Not sure what what could be done on rustc side, short of disabling the test altogether.

**Comment by Logarithmus** [comment]
@tmiasko thanks, I'll try reaching out the Void devs

**Comment by tmiasko** [comment]
Ah, one workaround would be to disable the relocation in the test, I will do that.

If you could reach out to Void Linux developers to enable static-pie that would be great as well. Thanks.
