### ISSUE TITLE
Move stdlib tests from src/test/ui-fulldeps to library/std/tests

### ISSUE THREAD

**Issue by ChrisDenton** [rust-lang/rust#99417]
I think std tests should ideally live in the `library/std` directory but today we have a few that are in `src/test/ui-fulldeps`.

Tests I think could be moved:

* [x] [create-dir-all-bare.rs](https://github.com/rust-lang/rust/blob/master/src/test/ui-fulldeps/create-dir-all-bare.rs)
* [x] [issue-15149.rs](https://github.com/rust-lang/rust/blob/master/src/test/ui-fulldeps/issue-15149.rs)
* [x] [rename-directories.rs](https://github.com/rust-lang/rust/blob/master/src/test/ui-fulldeps/rename-directory.rs)
* [x] [stdio-from.rs](https://github.com/rust-lang/rust/blob/master/src/test/ui-fulldeps/stdio-from.rs)
* [x] [switch-stdout.rs](https://github.com/rust-lang/rust/blob/master/src/test/ui-fulldeps/switch-stdout.rs)

**Comment by jyn514** [comment]
Looks like `create-dir-all-bare` and `rename-directory` were changed to an integration test in https://github.com/rust-lang/rust/pull/108233.

The rest of these are moving from `ui-fulldeps` to `ui` in https://github.com/rust-lang/rust/pull/109875, but it would still be nice to get them out of `tests/ui` altogether so they don't require building the compiler.

**Comment by MoskalykA** [comment]
Hi, is this no longer an issue?

**Comment by jyn514** [comment]
this is still an issue.

```
; ls tests/ui/std
issue-15149.rs  issue-81357-unsound-file-methods.rs  stdio-from.rs  switch-stdout.rs
```

**Comment by MoskalykA** [comment]
> issue-81357-unsound-file-methods.rs

OK, is the `issue-81357-unsound-file-methods.rs` file also included? I'll try to resolve this issue

**Comment by MoskalykA** [comment]
Hi, I managed to move the `switch-stdout.rs` file but I have a problem with the `stdio-from.rs` file, I can't see how to use Stdio without going through the command system? Am I right?

**Comment by MoskalykA** [comment]
After asking on the discord, Stdin is apparently not made for tests so I have no idea how to do it for the `stdio-from.rs` file

**Comment by ChrisDenton** [comment]
Sorry I've not been around much lately. I believe I already moved the low hanging fruit with the remaining tests being much more tricky to move. Perhaps they will require changes to testing or maybe it'll never be possible to move them (in which case this issue should be closed as won't fix).

The ultimate goal here would be to run as many std tests as possible when `x test library/std` is used. Perhaps there's another way to achieve that. Or perhaps it's not worth the effort.

**Comment by jyn514** [comment]
@MoskalykA I see a `library/std/tests` folder which holds integration tests - could you move the test there? I think that would allow running it basically without changes, since that's where cargo puts its integration tests :)

**Comment by petrochenkov** [comment]
There's also a number of tests in `tests\ui\stdlib-unit-tests` which are standard library unit tests (they were moved there when dismantling the `issues` subdirectory).

**Comment by MoskalykA** [comment]
Hi, there,
I made a pull request (#112390) for the two moves I managed to make, I can try to add the tests coming from `tests\ui\stdlib-unit-tests` if you want ?

**Comment by Dylan-DPC** [comment]
@MoskalykA sorry for the delayed response but are you still interested in the other tests that are missing?

**Comment by MoskalykA** [comment]
> sorry for the delayed response but are you still interested in the other tests that are missing?

Yes, as suggested by `petrochenkov`, tests from the `tests\ui\stdlib-unit-tests` folder should be moved. But would `library/std/tests` as destination be correct?

**Comment by danik292** [comment]
I can look on it but i need to know what am i supposed to do.

**Comment by BansalShivanshu** [comment]
Is this issue fully complete? what's remaining? I would love to take over in prompt time!

**Comment by jieyouxu** [comment]
> Is this issue fully complete? what's remaining? I would love to take over in prompt time!

This is probably what needs investigating at the moment, i.e. the current status of this issue.

**Comment by ChrisDenton** [comment]
Sorry I've not been keeping up with the issue.

I have now checked and it seems there are no longer any std tests in the ui-fulldeps directory so I'm closing this as complete.
