### ISSUE TITLE
Tracking Issue for native link modifier `verbatim`

### ISSUE THREAD

**Issue by petrochenkov** [rust-lang/rust#99425]
This is a tracking issue for native link modifier `verbatim`, which is a part of RFC "Linking modifiers for native libraries" (https://github.com/rust-lang/rust/issues/81490, https://github.com/rust-lang/rfcs/pull/2951).
The feature gate for the issue is `#![feature(native_link_modifiers_verbatim)]`.

### About tracking issues

Tracking issues are used to record the overall progress of implementation.
They are also used as hubs connecting to other relevant issues, e.g., bugs or open design questions.
A tracking issue is however *not* meant for large scale discussion, questions, or bug reports about a feature.
Instead, open a dedicated issue for the specific matter and add the relevant feature gate label.

### Steps
- [ ] Implement the RFC - #83507
- [ ] Adjust documentation ([see instructions on rustc-dev-guide][doc-guide])
- [ ] Stabilization PR ([see instructions on rustc-dev-guide][stabilization-guide])

[stabilization-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#stabilization-pr
[doc-guide]: https://rustc-dev-guide.rust-lang.org/stabilization_guide.html#documentation-prs

### Unresolved Questions

`-l:libfoo.a` is not entirely verbatim, there's still no way to pass a library by full path (without the `-l` option), like `/path/to/libfoo.a`, while still respecting relative order of passed libraries, `-C link-arg=/path/to/libfoo.a` will put the option at the end of the command line instead.
`-l link-arg=/path/to/libfoo.a` (https://github.com/rust-lang/rust/issues/99427) will likely help with this situation.

**Comment by petrochenkov** [comment]
Known issue: `fn find_library` in the compiler still falls back from `"{target_staticlib_prefix}{name}{target_staticlib_suffix}"` to `"lib{name}.a"` even if `+verbatim` is enabled, it shouldn't do that.

**Comment by dpaoliello** [comment]
Is there anything currently blocking the stabilization of this feature?

**Comment by petrochenkov** [comment]
I think it can be stabilized now, if the limitations and the caveat about full paths are well documented.
I can prepare the stabilization PR.

**Comment by petrochenkov** [comment]
Stabilization PR - https://github.com/rust-lang/rust/pull/104360.
