### ISSUE TITLE
compiler crashes trying to report an error [regression]

### ISSUE THREAD

**Issue by Hezuikn** [rust-lang/rust#99482]
nightly 1.64(crashes) [playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=98118a20e08a59044e58f9d77d69f636)
beta 1.63(behaves correctly) [playground](https://play.rust-lang.org/?version=beta&mode=debug&edition=2021&gist=f708086f1bcc9dec30bf43d27766a864)

**Comment by compiler-errors** [comment]
99% chance that I introduced this bug, I'll look into it.

@rustbot claim
