### ISSUE TITLE
Add hints of semicolon to curly brace(d) statements

### ISSUE THREAD

**Issue by Anindya-Prithvi** [rust-lang/rust#99522]
**Context:** I was writing `{ somearray.into_iter().fold( . . . ) }` however missed a semi-colon. But, instead of rustc looking at it started complaining for the logic inside `.fold()`. Here is the picture:
![image](https://user-images.githubusercontent.com/29653551/180055260-4dbda494-fa77-4d1c-9694-bff55287cbb2.png)
![image](https://user-images.githubusercontent.com/29653551/180055404-d7d82a21-753e-44a0-9043-45518c674c30.png)

**Proposal:** I was thinking if we could prioritize on catching whether some user accidentally "returned" something inside a for loop instead of reporting correct things as incorrect.

**Min. reproducible example**:
```rust
for _ in 0..1 {
    true
}
```
With error:
```rustc
error[E0308]: mismatched types
 --> src/main.rs:3:5
  |
3 |     true
  |     ^^^^ expected `()`, found `bool`

For more information about this error, try `rustc --explain E0308`.
```
Even though the error here looks somewhat appropriate, we can however be almost always sure that the user missed a semi-colon.

play.rust link: 
https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=605c3c7b30d2e435710a8ba2968c56d0

version: rustc 1.61.0 (fe5b13d68 2022-05-18)

**Comment by poliorcetics** [comment]
I would like to work on this, where should I start ?

**Comment by poliorcetics** [comment]
```
error[E0308]: mismatched types
 --> src/main.rs:3:9
  |
3 |         true
  |         ^^^^ expected `()`, found `bool`
  |
  = note: try adding a `;` at the end of the expression to obtain a `()`
```

Progress, now to point to the end of the expression

**Comment by estebank** [comment]
Note that [we do suggest a semicolon](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=d21bc0ae84d38f93f8d7f5fffd85e194) in cases where that would make sense, but not for literals because it is very likely not what the user intended, to create a literal value and then dropping it on the floor.
