### ISSUE TITLE
Suggest potentially missing value in empty conditional expression arms with inferred type

### ISSUE THREAD

**Issue by estebank** [rust-lang/rust#99525]
When given

```rust
fn d(opt_str: Option<String>) {
    let s = if let Some(s) = opt_str {
        //~^ ERROR mismatched types
    } else {
        String::new()
    };
}
```

we should mention that `s` might be missing in the `if` branch of the expression, like we do for

```rust
fn d(opt_str: Option<String>) {
    let s: String = if let Some(s) = opt_str {
        //~^ ERROR mismatched types
    } else {
        String::new()
    };
}
```

_https://github.com/rust-lang/rust/pull/98784#discussion_r924871175_

**Comment by compiler-errors** [comment]
Actually this aligns perfectly with a refactoring of `IfExpressionCause` I was looking at last night...

**Comment by compiler-errors** [comment]
Since we already suggest removing semicolon bidirectionally i.e.  `if a { b; } else { c }` and `if a { b } else { c; }`, we should be able to do the same with the return binding suggestion too.

@rustbot claim
