### ISSUE TITLE
nightly 2022-06-29 rejects previously compiling code with missing trait implementations

### ISSUE THREAD

**Issue by hawkw** [rust-lang/rust#99536]
### Code

The `linkerd2-proxy` project fails to compile on nighty 2022-06-29 and later due to a "missing" implementation of a trait in an `impl Trait` return value. The same code compiles successfully on stable and on prior nightlies. The error occurs when using `impl Trait` as an associated type of a return value that is itself an `impl Trait`, when the associated type has trait bounds placed on it by the outer `impl Trait`. 

An error like this is generated:
```
error[E0277]: the trait bound `impl std::marker::Send + Unpin: linkerd_app_core::linkerd_io::AsyncRead` is not satisfied
   --> linkerd/app/inbound/src/lib.rs:158:9
    |
158 | /         impl svc::MakeConnection<
159 | |                 T,
160 | |                 Connection = impl Send + Unpin,
161 | |                 Metadata = impl Send + Unpin,
162 | |                 Error = Error,
163 | |                 Future = impl Send,
164 | |             > + Clone,
    | |_____________________^ the trait `linkerd_app_core::linkerd_io::AsyncRead` is not implemented for `impl std::marker::Send + Unpin`
    |
    = help: the following other types implement trait `linkerd_app_core::linkerd_io::AsyncRead`:
              &[u8]
              &mut T
              Box<T>
              BoxedIo
              BufStream<RW>
              DuplexStream
              EitherIo<L, R>
              Pin<P>
            and 38 others
    = note: required because of the requirements on the impl of `linkerd_app_core::svc::MakeConnection<T>` for `linkerd_app_core::svc::Filter<linkerd_app_core::svc::MapErr<linkerd_app_core::svc::linkerd_stack::Timeout<ConnectTcp>, impl (FnOnce(Box<(dyn std::error::Error + Sync + std::marker::Send + 'static)>) -> Box<(dyn std::error::Error + Sync + std::marker::Send + 'static)>) + Clone>, [closure@linkerd/app/inbound/src/lib.rs:186:38: 193:18]>`

error[E0277]: the trait bound `impl std::marker::Send + Unpin: linkerd_app_core::linkerd_io::AsyncWrite` is not satisfied
   --> linkerd/app/inbound/src/lib.rs:158:9
    |
158 | /         impl svc::MakeConnection<
159 | |                 T,
160 | |                 Connection = impl Send + Unpin,
161 | |                 Metadata = impl Send + Unpin,
162 | |                 Error = Error,
163 | |                 Future = impl Send,
164 | |             > + Clone,
    | |_____________________^ the trait `linkerd_app_core::linkerd_io::AsyncWrite` is not implemented for `impl std::marker::Send + Unpin`
    |
    = help: the following other types implement trait `linkerd_app_core::linkerd_io::AsyncWrite`:
              &mut T
              Box<T>
              BoxedIo
              BufStream<RW>
              DuplexStream
              EitherIo<L, R>
              Pin<P>
              PrefixedIo<I>
            and 38 others
    = note: required because of the requirements on the impl of `linkerd_app_core::svc::MakeConnection<T>` for `linkerd_app_core::svc::Filter<linkerd_app_core::svc::MapErr<linkerd_app_core::svc::linkerd_stack::Timeout<ConnectTcp>, impl (FnOnce(Box<(dyn std::error::Error + Sync + std::marker::Send + 'static)>) -> Box<(dyn std::error::Error + Sync + std::marker::Send + 'static)>) + Clone>, [closure@linkerd/app/inbound/src/lib.rs:186:38: 193:18]>`

error[E0277]: the trait bound `impl std::marker::Send + Unpin: linkerd_app_core::linkerd_io::AsyncRead` is not satisfied
  --> linkerd/app/outbound/src/tcp/connect.rs:39:9
   |
39 | /         impl svc::MakeConnection<
40 | |                 T,
41 | |                 Connection = impl Send + Unpin,
42 | |                 Metadata = ConnectMeta,
43 | |                 Error = Error,
44 | |                 Future = impl Send,
45 | |             > + Clone,
   | |_____________________^ the trait `linkerd_app_core::linkerd_io::AsyncRead` is not implemented for `impl std::marker::Send + Unpin`
   |
   = help: the following other types implement trait `linkerd_app_core::linkerd_io::AsyncRead`:
             &[u8]
             &mut T
             Box<T>
             BoxedIo
             DuplexStream
             EitherIo<L, R>
             Pin<P>
             PrefixedIo<I>
           and 38 others
   = note: required because of the requirements on the impl of `MakeConnection<T>` for `linkerd_app_core::transport::linkerd_transport_metrics::Client<linkerd_app_core::transport::Metrics, BoxFuture<linkerd_app_core::svc::MapErr<linkerd_app_core::svc::linkerd_stack::Timeout<OpaqueTransport<linkerd_app_core::linkerd_tls::Client<linkerd_app_core::identity::NewClient, C>>>, impl (FnOnce(Box<(dyn std::error::Error + Sync + std::marker::Send + 'static)>) -> Box<(dyn std::error::Error + Sync + std::marker::Send + 'static)>) + Clone>>>`

error[E0277]: the trait bound `impl std::marker::Send + Unpin: linkerd_app_core::linkerd_io::AsyncWrite` is not satisfied
  --> linkerd/app/outbound/src/tcp/connect.rs:39:9
   |
39 | /         impl svc::MakeConnection<
40 | |                 T,
41 | |                 Connection = impl Send + Unpin,
42 | |                 Metadata = ConnectMeta,
43 | |                 Error = Error,
44 | |                 Future = impl Send,
45 | |             > + Clone,
   | |_____________________^ the trait `linkerd_app_core::linkerd_io::AsyncWrite` is not implemented for `impl std::marker::Send + Unpin`
   |
   = help: the following other types implement trait `linkerd_app_core::linkerd_io::AsyncWrite`:
             &mut T
             Box<T>
             BoxedIo
             DuplexStream
             EitherIo<L, R>
             Pin<P>
             PrefixedIo<I>
             ScopedIo<I>
           and 38 others
   = note: required because of the requirements on the impl of `MakeConnection<T>` for `linkerd_app_core::transport::linkerd_transport_metrics::Client<linkerd_app_core::transport::Metrics, BoxFuture<linkerd_app_core::svc::MapErr<linkerd_app_core::svc::linkerd_stack::Timeout<OpaqueTransport<linkerd_app_core::linkerd_tls::Client<linkerd_app_core::identity::NewClient, C>>>, impl (FnOnce(Box<(dyn std::error::Error + Sync + std::marker::Send + 'static)>) -> Box<(dyn std::error::Error + Sync + std::marker::Send + 'static)>) + Clone>>>`

For more information about this error, try `rustc --explain E0277`.
```

Unfortunately, I don't have a minimal reproducer yet; I'd like to find one, but for now, checking out https://github.com/linkerd/linkerd2-proxy/commit/0288b9c998c3343e1e24a404fe997ed3ce5e6572 and running `cargo +nigihtly-2022-06-29 build` will fail with this error. 

### Version it worked on

The most recent nightly that can compile the `linkerd2-proxy` codebase successfully is `2022-06-28`. Successful CI build: https://github.com/linkerd/linkerd2-proxy/runs/7088482069?check_suite_focus=true

### Version with regression

Nightly `2022-06-29` and later fails to compile the same codebase. Failing CI build: https://github.com/linkerd/linkerd2-proxy/runs/7107925369?check_suite_focus=true

We ran `cargo bisect-rustc` and it appears that commit 00ebeb87ac87a492bd59ace6bd43d6ad1629ca4e introduced the regression.

searched nightlies: from nightly-2022-06-28 to nightly-2022-06-30
regressed nightly: nightly-2022-06-29
searched commit range: https://github.com/rust-lang/rust/compare/2f3ddd9f594adf9773547aa7cedb43c4ac8ffd2f...830880640304ba8699c5f9a0c4665c38a3271963
regressed commit: https://github.com/rust-lang/rust/commit/00ebeb87ac87a492bd59ace6bd43d6ad1629ca4e

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.3</summary>

Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --start 2022-06-28 --end 2022-06-30 --test-dir ../linkerd2-proxy -- build 
```

</details>

**Comment by hawkw** [comment]
Started attempting to find a minimal reproduction; [this playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=debe50e768cfcc6fcc78bb408e702c35) does not reproduce the issue, so clearly there is something more complex involved than *just* returning an `impl Trait` as an associated type of another `impl Trait`...

**Comment by compiler-errors** [comment]
@hawkw, are there rustdocs for `linkerd2-proxy` (or, specifically, one of the failing crates like `linkerd2-proxy/linkerd/app/inbound`? There's quite a few types here, and those would help, but I couldn't seem to find a rustdoc-style documentation from the website. I also may just be looking in the wrong place.

**Comment by compiler-errors** [comment]
Soooooo, I think I got it to compile. This is not a _correct_ soltuion, because it causes a bunch of UI tests to fail. Draft PR:  #99547

This has to do with the fact that when we [`Equate::tys`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_middle/ty/relate/trait.TypeRelation.html#tymethod.tys) on an inference variable and an opaque type, we end up just inferring that inference variable to opaque type, instead of (what we usually do, which is) causing us to constrain the opaque type to the value of the other ty (the infer, in this case).

This means that when we later `shallow_resolve` a predicate that looks like `<_#1t as AsyncRead>` (i.e. some inferred type must implement AsyncRead), we get `<impl Send + Unpin as AsyncRead>` -- without the usual opaque type registering machinery taking place.

side-note: does it usually take 3 minutes to compile `linkerd/app/outbound`?

**Comment by oli-obk** [comment]
> we end up just inferring that inference variable to opaque type, instead of (what we usually do, which is) causing us to constrain the opaque type to the value of the other ty (the infer, in this case).

That's on purpose. The only time we don't do that is for return types so that we can merge the types from all the return sites.

how did we miss this in the crater run :/

**Comment by compiler-errors** [comment]
@oli-obk linkerd isn't on crates.io i think? 🤔

**Comment by oli-obk** [comment]
we run github crates, too, and I was certain I have seen linkerd in crater reports before

**Comment by oli-obk** [comment]
```
{
  "name": "gridgentoo.linkerd2-proxy.f7a8ee98c63b6729e02f54a5182a9b7f56695922",
  "url": "https://github.com/gridgentoo/linkerd2-proxy/tree/f7a8ee98c63b6729e02f54a5182a9b7f56695922",
  "krate": {
    "GitHub": {
      "org": "gridgentoo",
      "name": "linkerd2-proxy",
      "sha": "f7a8ee98c63b6729e02f54a5182a9b7f56695922"
    }
  },
  "res": "build-fail",
  "runs": [
    {
      "res": "build-fail:compiler-error(unused_must_use)",
      "log": "master%2343d9f3859e0204e764161ee085a360274b5f3e9a/gh/gridgentoo.linkerd2-proxy"
    },
    {
      "res": "build-fail:compiler-error(unused_must_use)",
      "log": "try%237306d3110618f84a6a4662b9e2cc4fd0d9b02da8/gh/gridgentoo.linkerd2-proxy"
    }
  ]
}
```

uhm... did crater not recognize the regression because it hit a `deny` for a lint?

also it seems like it didn't actually run on the sub-crates like `inbound` (at least I can't find it in the results).

nominating for t-types discussion, as there was a regression we didn't know about.

I think what all users that hit this desire is not actually `impl Send`, but "an opaque type that satisfies the bounds of the associated type, PLUS `Send`".

**Comment by compiler-errors** [comment]
`f7a8ee98c63b6729e02f54a5182a9b7f56695922` seems really old

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2399536.20nightly.202022-06-29.20rejects.20previously.20compiling.20code.E2.80.A6)).

@rustbot label -I-prioritize +P-high

**Comment by oli-obk** [comment]
Let's revert for now, this seems more useful in practice than we thought

**Comment by compiler-errors** [comment]
Thanks, yeah, there is a revert PR in flight but the author is on vacation.

In the mean time, I've beta-backport nominated the revert PR and that'll likely get approved, fixing this in a few more weeks.

Sorry for the delay.

**Comment by LucioFranco** [comment]
No problem! Thanks for the quick response 😄
