### ISSUE TITLE
expected a table, but found a array for `target.wasm32-unknown-unknown.ranlib`

### ISSUE THREAD

**Issue by jasl** [rust-lang/rust#99532]
- macOS 12.5
- Rust nightly-2022-07-11

According to https://github.com/rust-lang/rust/blob/master/config.toml.example#L656

my `.cargo/config.toml`

```toml
[target.wasm32-unknown-unknown]
ar = "/opt/homebrew/opt/llvm/bin/llvm-ar"
ranlib = "/opt/homebrew/opt/llvm/bin/llvm-ranlib"
```

When I'm compiling https://github.com/Phala-Network/khala-parachain 
It errored with
```
error: failed to run custom build command for `rhala-parachain-runtime v0.1.17-dev (/Users/jasl/Workspaces/BlockChain/khala-parachain/runtime/rhala)`

Caused by:
  process didn't exit successfully: `/Users/jasl/Workspaces/BlockChain/khala-parachain/target/release/build/rhala-parachain-runtime-d409eead87464af5/build-script-build` (exit status: 1)
  --- stdout
  Information that should be included in a bug report.
  Executing build command: "/Users/jasl/.rustup/toolchains/nightly-2022-07-11-aarch64-apple-darwin/bin/cargo" "rustc" "--target=wasm32-unknown-unknown" "--manifest-path=/Users/jasl/Workspaces/BlockChain/khala-parachain/target/release/wbuild/rhala-parachain-runtime/Cargo.toml" "--color=always" "--profile" "release"
  Using rustc version: rustc 1.64.0-nightly (c396bb3b8 2022-07-10)


  --- stderr
  error: expected a table, but found a string for `target.wasm32-unknown-unknown.ranlib` in /Users/jasl/Workspaces/BlockChain/khala-parachain/.cargo/config.toml
```

**Comment by ehuss** [comment]
`config.toml` for the compiler is not the same as Cargo's `.cargo/config.toml`, they are two very different files.  The compiler's `config.toml` should be in the root of where you are compiling (usually the root of the repo).

**Comment by jasl** [comment]
> `config.toml` for the compiler is not the same as Cargo's `.cargo/config.toml`, they are two very different files. The compiler's `config.toml` should be in the root of where you are compiling (usually the root of the repo).

I put my `.cargo/config.toml` into the root of the repo where I am compiling.
and the error message shows Cargo already read the config, but said it's invalid.

the problem is:

example shows

```
[target.x86_64-unknown-linux-gnu]
# Ranlib to be used to assemble static libraries compiled from C/C++ code.
# Note: an absolute path should be used, otherwise LLVM build will break.
#ranlib = "ranlib" (path)
```

mine

```
[target.wasm32-unknown-unknown]
ar = "/opt/homebrew/opt/llvm/bin/llvm-ar"
ranlib = "/opt/homebrew/opt/llvm/bin/llvm-ranlib"
```

the compiler shows

```
error: expected a table, but found a string for `target.wasm32-unknown-unknown.ranlib` in /Users/jasl/Workspaces/BlockChain/khala-parachain/.cargo/config.toml
```

**Comment by jasl** [comment]
I tried to move `.cargo/config.toml` to the repo root

![388461658397705_ pic](https://user-images.githubusercontent.com/1024162/180188870-cb3669ce-aa61-4873-a7de-ef57163cc1ee.jpg)

then made a clean build
![388491658397748_ pic](https://user-images.githubusercontent.com/1024162/180188881-7e96022e-2ef9-41cf-978d-6756bfb6b072.jpg)

it fails again

```
  error: failed to build archive: section too large

  warning: `ring` (lib) generated 1 warning
  The following warnings were emitted during compilation:

  warning: warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: archive library: /Users/jasl/Workspaces/BlockChain/khala-parachain/target/release/wbuild/khala-parachain-runtime/target/wasm32-unknown-unknown/release/build/ring-6099784f2b660747/out/libring-core.a the table of contents is empty (no object file members in the library define global symbols)
  warning: warning: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib: archive library: /Users/jasl/Workspaces/BlockChain/khala-parachain/target/release/wbuild/khala-parachain-runtime/target/wasm32-unknown-unknown/release/build/ring-6099784f2b660747/out/libring-test.a the table of contents is empty (no object file members in the library define global symbols)

  error: could not compile `ring` due to previous error; 1 warning emitted
```

so the rust or cargo don't read the `config.toml`

**Comment by ehuss** [comment]
Ah, you are not building the compiler. 

You referenced https://github.com/rust-lang/rust/blob/master/config.toml which is only for building the compiler. It is a different configuration file.

https://doc.rust-lang.org/cargo/reference/config.html contains documentation for `.cargo/config.toml` files. There is no such setting as `ranlib` there.

I'm going to close as this does not appear to be an issue with rustc. If you need help with setting up your environment, I suggest first asking on one of the user forums, such as https://users.rust-lang.org/. If you are having a problem with a specific third-party package (such as khala-parachain-runtime), I suggest asking them for help. If in the end there is a real issue with rustc, please open a new issue with the complete details on how to reproduce (for example, it looks like you are modifying PATH to a homebrew llvm, but not explaining why).
