### ISSUE TITLE
Latest nightly (`rustc 1.64.0-nightly (62b272d25 2022-07-21)`) introduces a new borrowcheck error in previously compiling `mdbook` `0.4.20`

### ISSUE THREAD

**Issue by mitchmindtree** [rust-lang/rust#99591]
As of `rustc 1.64.0-nightly (62b272d25 2022-07-21)`, a new lifetime error has appeared when attempting to build `mdbook` `0.4.20`.

### Error

```
error[E0597]: `local_ctx` does not live long enough
   --> src/renderer/html_handlebars/helpers/navigation.rs:154:25
    |
154 |             t.render(r, &local_ctx, &mut local_rc, out)
    |                         ^^^^^^^^^^ borrowed value does not live long enough
155 |         })?;
    |         -
    |         |
    |         `local_ctx` dropped here while still borrowed
    |         borrow might be used here, when `local_rc` is dropped and runs the destructor for type `handlebars::RenderContext<'_, '_>`
    |
    = note: values in a scope are dropped in the opposite order they are defined

For more information about this error, try `rustc --explain E0597`.
error: could not compile `mdbook` due to previous error
```

### Version it worked on

rustc 1.64.0-nightly (d68e7ebc3 2022-07-20)

### Version with regression

rustc 1.64.0-nightly (62b272d25 2022-07-21)

### Details

You can find more details at the downstream `mdbook` issue https://github.com/rust-lang/mdBook/issues/1860.

Curiously, the new error can be fixed by re-ordering some seemingly inocuous statements - see this PR https://github.com/rust-lang/mdBook/pull/1861.

Perhaps this is indicative of an error in non-lexical-lifetime handling on the latest nightly? Or alternatively, this could be the result of fixing a soundness / safety issue related to the interop between lifetimes and drop order?

This error was originally discovered in an unrelated CI pass failing in the following PR: https://github.com/FuelLabs/sway/pull/2359.

**Comment by 5225225** [comment]
Ran a bisection in `mdBook`, version https://github.com/rust-lang/mdBook/commit/92afe9bd3c220eded410b91bffe8cf17d1eca129

Looks to be a rollup, #99567. None of them jump out as obvious candidates.

---

searched nightlies: from nightly-2022-07-20 to nightly-2022-07-22
regressed nightly: nightly-2022-07-22
searched commit range: https://github.com/rust-lang/rust/compare/d68e7ebc38cb42b8b237392b28045edeec761503...62b272d25c5bb8b6bb8ac73797d82b8b9a1eabda
regressed commit: https://github.com/rust-lang/rust/commit/af7ab3447079fddc51c6c7749b160d24769f7c16

<details>
<summary>bisected with <a href='https://github.com/rust-lang/cargo-bisect-rustc'>cargo-bisect-rustc</a> v0.6.1</summary>


Host triple: x86_64-unknown-linux-gnu
Reproduce with:
```bash
cargo bisect-rustc --start 2022-07-20 --end 2022-07-22 --preserve -- check 
```
</details>

**Comment by 5225225** [comment]
This might actually be https://github.com/rust-lang/rust/pull/99413 ? A btreemap is *used* in that bit of code, but it's talking about a RenderContext.

**Comment by ehuss** [comment]
Confirmed that it is caused by #99413. Here is a slightly smaller repro:

```rust
#![allow(unused)]
use std::collections::BTreeMap;
use std::marker::PhantomData;
use std::rc::Rc;

fn main() {
    let mut rc = RenderContext {
        local_helpers: BTreeMap::new(),
    };
    foo(&mut rc);
}

#[derive(Clone)]
struct RenderContext<'rc> {
    local_helpers: BTreeMap<String, Rc<dyn HelperDef + 'rc>>,
}

pub trait HelperDef {}

fn foo(rc: &mut RenderContext<'_>) {
    let mut local_rc = rc.clone();
    let local_ctx: BTreeMap<String, String> = BTreeMap::new();
    render(&local_ctx, &mut local_rc);
}

fn render<'rc>(ctx: &'rc BTreeMap<String, String>, rc: &mut RenderContext<'rc>) {}
```

I think the error here is correct and #99413 is a valid fix. It's just a consequence of how the lifetimes in the handlebars crate are defined that cause the error.

**Comment by danielhenrymantilla** [comment]
Until the fix to `mdbook` is officially released, btw, for those running into this, the workaround is to use the `git` dev, potentially as a `patch`:

  - for those using `cargo install mdbook`, instead, do

    ```bash
    cargo install mdbook --git 'https://github.com/rust-lang/mdBook' --rev '8f01d0234f708042ea8d0dc5cac63859b3f14cb1'
    ```

  - for those depending on `mdbook` as a library, on the `Cargo.toml` file of your workspace (where the `Cargo.lock` file lies / is generated), add:

    ```toml
    [patch.crates-io.mdbook]
    version = "0.4.20"
    git = "https://github.com/rust-lang/mdBook"
    rev = "8f01d0234f708042ea8d0dc5cac63859b3f14cb1"
    ```

**Comment by apiraino** [comment]
@Jules-Bertholet changed the label to regression on stable: did you experience that it's still an issue? I've compiled `mdbook` (both on stable and nightly) and the reproducible [at this comment](https://github.com/rust-lang/rust/issues/99591#issuecomment-1192630141) now shows a better error, I believe.
