### ISSUE TITLE
Consider returning `/private/tmp` instead of `/tmp` on macOS with `std::env::temp_dir()`

### ISSUE THREAD

**Issue by poliorcetics** [rust-lang/rust#99608]
The first is a regular directory, the second is a symlink to the first. This can lead to software failing in strange and unexpected ways (especially during testing, with the tempfile crate or similar) if symlinks are forbidden, e.g. I recently encountered the case with SQLite

Since `/tmp -> /private/tmp` software that was already working correctly should not start to fail unexpectedly. Software that *was* failing/had to workaround this will start working correctly.

```
macos-12.4 $ /bin/ls -la /tmp
lrwxr-xr-x@ 1 root  wheel  11  9 mai 23:30 /tmp -> private/tmp
```

**Comment by poliorcetics** [comment]
The first is a regular directory, the second is a symlink to the first. This can lead to software failing in strange and unexpected ways (especially during testing, with the `tempfile` crate or similar) if symlinks are forbidden, e.g. I recently encountered the case with SQLite

**Comment by edmorley** [comment]
See also #100196 and #100824.
