### ISSUE TITLE
Miri tests fail with debug assertions enabled

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#99605]
I thought I had tested the debug assertions that I added in https://github.com/rust-lang/rust/pull/99420, but it seems I hadn't tested them on enough code, because they do actually fail, for example:
```
thread 'rustc' panicked at 'assertion failed: `(left == right)`
  left: `Instance { def: VTableShim(DefId(2:3509 ~ core[3dde]::ops::function::FnOnce::call_once)), substs: [[closure@std::thread::Builder::spawn_unchecked_<[closure@tests/pass/weak_memory/weak.rs:38:20: 38:27], ()>::{closure#1}], ()] }`,
 right: `Instance { def: Item(WithOptConstParam { did: DefId(1:985 ~ std[636e]::thread::{impl#0}::spawn_unchecked_::{closure#1}), const_param_did: None }), substs: [ReErased, ReErased, [closure@tests/pass/weak_memory/weak.rs:38:20: 38:27], (), i32, extern "rust-call" fn(()), (std::thread::Thread, std::option::Option<std::sync::Arc<std::sync::Mutex<std::vec::Vec<u8>>>>, [closure@tests/pass/weak_memory/weak.rs:38:20: 38:27], std::sync::Arc<std::thread::Packet<()>>)] }`', /home/r/src/rust/rustc/compiler/rustc_const_eval/src/interpret/terminator.rs:600:21
```
That's this assertion:
https://github.com/rust-lang/rust/blob/41419e70366962c9a878bfe673ef4df38db6f7f1/compiler/rustc_const_eval/src/interpret/terminator.rs#L600
failing on this code:
```
note: the place in the program where the ICE was triggered
  --> /home/r/src/rust/rustc/library/alloc/src/boxed.rs:1935:9
   |
LL |         <F as FnOnce<Args>>::call_once(*self, args)
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

@eddyb looks like the check you proposed does not always hold?

**Comment by eddyb** [comment]
Oh yeah my bad I forgot to double-check that `Instance::resolve_for_vtable` is used, not `Instance::resolve`.

(which can convert the `resolve` result into `VtableShim`, but it looks like it has some other conditions/outcomes too so it's better to call `resolve_for_vtable` directly)

**Comment by RalfJung** [comment]
> you should also test with some #[track_caller] situations to trigger ReifyShim as well, not just VtableShim.

What would those situations look like?

**Comment by eddyb** [comment]
Looks like `#[track_caller]` in the `impl` but not in the `trait` ([see on godbolt](https://godbolt.org/z/PPM83dEnb)):
```rust
pub trait Foo {
    fn foo(&self);
}

struct Bar;
impl Foo for Bar {
    #[track_caller]
    fn foo(&self) {}
}
```
`&Bar as &dyn Foo` ends up with this vtable entry:
```
<example::Bar as example::Foo>::foo::{shim:reify#0}
```
which is the `ReifyShim`, and it calls:
```
<example::Bar as example::Foo>::foo
```

**Comment by RalfJung** [comment]
You are right, that used to ICE mentioning a `ReifyShim`. `resolve_for_vtable` fixes both cases. :)
