### ISSUE TITLE
TreeMap::lower_bound_iter should be traversable in reverse

### ISSUE THREAD

**Issue by julmas** [rust-lang/rust#9963]
In some algorithms you want to iterate leftwards in a set starting at the lower bound.

If a TreeSet contains values 0..9 and lower_bound_iter(4) is called,
there should be a way to transform that iterator to something that lazily generates the sequence 4,3,2,1,0.

That is. It is not enough to simply reverse the forward iterator, since that would yield 9,8,7,6,5,4

**Comment by Gankro** [comment]
TreeMap is not in std lib anymore.
