### ISSUE TITLE
make small fixed-size vectors immediate

### ISSUE THREAD

**Issue by thestinger** [rust-lang/rust#9965]

**Comment by dotdash** [comment]
Is this about the LLVM vector type?

**Comment by steveklabnik** [comment]
Triage: I'm not aware of any change in this area. @rust-lang/compiler ?

**Comment by eddyb** [comment]
@dotdash I'm pretty sure @thestinger was talking about `[T; N]` which were once called "fixed-size vectors".

**Comment by Aatch** [comment]
Fixed-sized arrays are treated as immediate if they are small enough, so this issue can be closed.
