### ISSUE TITLE
First code example regarding stdin emits a warning

### ISSUE THREAD

**Issue by dexygen** [rust-lang/rust#99654]
### What needs to be fixed?
The very first code example on the page in the docs regarding `stdin` is confusing because, using Rust 1.6.2, when executing the line with the comment `// We get Stdin here` appended, the warning "variable does not need to be mutable" is emitted.

### Page(s) Affected
https://doc.rust-lang.org/std/io/struct.Stdin.html

### Suggested Improvement
If the need for a mutable became unnecessasry as of a particular Rust version, perhaps add a comment to that effect

**Comment by Phosra** [comment]
> If the need for a mutable became unnecessasry as of a particular Rust version, perhaps add a comment to that effect
Yes, this `mut` definitely required in an older version... I don't know which one, if it matters.
