### ISSUE TITLE
Overeager `consider adding a #[cfg(test)]` for unused imports in `mod tests` with the cfg

### ISSUE THREAD

**Issue by bsilver8192** [rust-lang/rust#99661]
Given the following code: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=8d2bf12d3315c3719787852baf7e0ba0 (make sure to use TEST instead of BUILD even though there are no tests in this minimal example):

```rust
#[cfg(test)]
mod tests {
    use super::*;
}
```

The current output is:

```
warning: unused import: `super::*`
 --> src/lib.rs:3:9
  |
3 |     use super::*;
  |         ^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default
help: consider adding a `#[cfg(test)]` to the containing module
 --> src/lib.rs:2:1
  |
2 | mod tests {
  | ^^^^^^^^^
```

The `help: consider adding a #[cfg(test)] to the containing module` does not apply here, because that has already been added. The problem is that the import is just not used.

#59426 is an open issue that looks related to adding this message, for reference.

**Comment by compiler-errors** [comment]
cc @TaKO8Ki who added this I think

**Comment by TaKO8Ki** [comment]
@bsilver8192 What version of Rust do you use? rustc on stable and latest nightly does not seem to show your output.

latest nightly: https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=780b40403d24e4ebf3d612ffafe53d86

**Comment by bsilver8192** [comment]
I'm using 1.62.1. Indeed it looks like it's already fixed, thanks for taking a look!
