### ISSUE TITLE
Guessing Game Does Not Work On Current Release

### ISSUE THREAD

**Issue by dmccreary** [rust-lang/rust#99699]
### Location

In the Rust Language Book, In Chapter 2, the guessing game does not work:

https://doc.rust-lang.org/book/ch02-00-guessing-game-tutorial.html#processing-a-guess

this line:

println!("You guessed: {guess}");

Generates the error:

error: there is no argument named `guess`
 
But this works:

println!("You guessed: {}", guess);

There is a similar problem with secret_number

**Comment by mqudsi** [comment]
My guess: you're using an old version of rust.

**Comment by JohnTitor** [comment]
Yeah, I think so too. You have to use Rust 1.59 or higher as described in https://doc.rust-lang.org/book/title-page.html (or 1.62 if you're reading https://doc.rust-lang.org/nightly/book/title-page.html), could you check your Rust version (`rustc -vV` will show it)?

And this repo's issue tracker is for the Rust compiler, std, and some more stuff, issues related to the book should go to https://github.com/rust-lang/book/issues.

I'm going to close with the above reasons, feel free to open another issue if you still have an issue.
