### ISSUE TITLE
rustdoc: mobile sidebar has gap at top and bottom

### ISSUE THREAD

**Issue by jsha** [rust-lang/rust#99691]
Steps to reproduce:

1. In mobile Chrome, visit https://doc.rust-lang.org/nightly/std/index.html.
2. Click the hamburger menu in upper left.

Expected results:

Sidebar opens and presents a solid background with no gaps.

Actual result:

Sidebar opens and there is a gap at top and bottom showing the main page.

![image](https://user-images.githubusercontent.com/220205/180661938-9e03314b-f411-4e07-92c1-8fdeb3bf00d1.png)

This is a regression from beta to nightly. Possibly related to @GuillaumeGomez's recent refactoring of how colors are applied for themes.

**Comment by GuillaumeGomez** [comment]
I's pretty bad indeed. I'll take a look at it tomorrow.
