### ISSUE TITLE
format!() should support the same set of \-escapes that regular string literals do

### ISSUE THREAD

**Issue by kballard** [rust-lang/rust#9970]
As long as `format!()` treats `\` as an escape character, it should handle all the same escapes that normal string literals do. This way a raw string literal can be passed to `format!()` and still use the expected escapes. Right now, attempting to do so:

    println!(r#"this is a "string": {}\n"#, "example code");

throws a compiler error:

     error: invalid escape character `n`
    println!(r#"this is a "string": {}\n"#, "example code");
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by rprichard** [comment]
I think this issue is already fixed -- `format!` no longer uses `\` as an escape character.  Instead, `{{` and `}}` are escape sequences.

**Comment by alexcrichton** [comment]
I believe so as well, thanks @rprichard!
