### ISSUE TITLE
Misaligned reference from drop field in packed struct

### ISSUE THREAD

**Issue by JakobDegen** [rust-lang/rust#99838]
I tried this code:

```rust
struct U16(u16);

impl Drop for U16 {
    fn drop(&mut self) {
        println!("{:p}", self);
    }
}

struct HasDrop;

impl Drop for HasDrop {
    fn drop(&mut self) {}
}

#[repr(packed)]
struct Misalign(u8, Wrapper);

struct Wrapper {
    _a: U16,
    b: HasDrop,
}

fn main() {
    let m = Misalign(
        0,
        Wrapper {
            _a: U16(10),
            b: HasDrop,
        },
    );
    let _x = m.1.b;
}
```

I expected to see this happen: The reference is aligned

Instead, this happened:
```
$ rustc +nightly -Copt-level=3 test.rs
$ ./test
0x7ffc5e1dad79
```

### Meta
`rustc --version --verbose`:
```
rustc 1.64.0-nightly (2643b1646 2022-07-27)
binary: rustc
commit-hash: 2643b16468fda787470340890212591d8bc832b7
commit-date: 2022-07-27
host: x86_64-unknown-linux-gnu
release: 1.64.0-nightly
LLVM version: 14.0.6
```

@rustbot label I-unsound A-mir

**Comment by JakobDegen** [comment]
We have a pass to add moves for drops in packed structs, but it doesn't fire in this case. That's because there's a bug [here](https://github.com/rust-lang/rust/blob/ada80a13b97a01176a1660453060e296a72cf1bb/compiler/rustc_const_eval/src/util/alignment.rs#L58) - this computation cannot just take into account the innermost field, it needs to compute a minimum of some sort.

**Comment by apiraino** [comment]
@JakobDegen is this a regression? What did you exactly expected the output to be? (I'd like to run a bisection). thanks.

**Comment by JakobDegen** [comment]
This is not a regression, it was wrong all the way back in 1.0

**Comment by apiraino** [comment]
WG-prioritization assigning priority ([Zulip discussion](https://rust-lang.zulipchat.com/#narrow/stream/245100-t-compiler.2Fwg-prioritization.2Falerts/topic/.2399838.20Misaligned.20reference.20from.20drop.20field.20in.20packed.20struct)).

@rustbot label -I-prioritize +P-high E-needs-bisection

**Comment by apiraino** [comment]
I have run a bisection with [cargo-bisect](https://github.com/rust-lang/cargo-bisect-rustc) on your `main.rs`.

```
$ RUST_SRC_REPO=~/projects/rust/rust cargo-bisect-rustc --preserve --start=2021-01-01 --script=./script.sh

$ cat script.sh
#!/bin/sh
rustc --emit mir -Copt-level=3 main.rs
grep "drop\(_3\) -> bb4" main.mir
```

The bisection could not pinpoint a single commit, maybe it sinked into a rollup merge. But if it helps, the regression should be in `nightly-2021-03-30` and coming from one of these PRs
```
found 8 bors merge commits in the specified range
  commit[0] 2021-03-28UTC: Auto merge of #83602 - JohnTitor:cloudabi-flag-is-unnecessary, r=Xanewok
  commit[1] 2021-03-28UTC: Auto merge of #83619 - petrochenkov:nx, r=nagisa
  commit[2] 2021-03-29UTC: Auto merge of #83605 - RalfJung:unaligned, r=petrochenkov
  commit[3] 2021-03-29UTC: Auto merge of #83565 - RalfJung:miri, r=oli-obk
  commit[4] 2021-03-29UTC: Auto merge of #83637 - bjorn3:sync_cg_clif-2021-03-29, r=bjorn3
  commit[5] 2021-03-29UTC: Auto merge of #83609 - klensy:c-str, r=m-ou-se
  commit[6] 2021-03-29UTC: Auto merge of #80839 - tblah:riscv64linux_links, r=Mark-Simulacrum
  commit[7] 2021-03-29UTC: Auto merge of #83185 - jyn514:remove-dead-code, r=oli-obk
```

@JakobDegen do you see in any of those a possible culprit? (I don't have the context to)

**Comment by JakobDegen** [comment]
Yeah, it's #83605, cc @RalfJung

**Comment by RalfJung** [comment]
Not sure how https://github.com/rust-lang/rust/pull/83605 would have an effect here, it should be a NOP for `repr(packed(N))` with `N < 2`.

Where is the logic that moves packed structs to a new place before dropping implemented?

> The consistent way to check this is by looking at --emit mir. In 1.52.0 the MIR contains

That's odd, I would have expected this to be inside `drop_in_place`... after all calling `drop_in_place` on a packed struct also has to do this move. Why does MIR building adjust the caller to satisfy a requirement that the callee should be responsible for?

**Comment by JakobDegen** [comment]
@RalfJung the pass is called `AddMoveForPackedDrops` or something like that. And this can't take place inside the callee because the callee receives a `&mut Self`, and if that reference is unaligned then UB has already occurred and there's nothing the callee can do to fix things anymore

**Comment by RalfJung** [comment]
`drop_in_place` takes a raw pointer, so it could very well be the place where the packed struct alignment trouble is handled. And IMO it'd be a much more natural place than doing this by transforming caller MIR.

**Comment by JakobDegen** [comment]
@RalfJung I don't understand the suggestion. The example above never calls `drop_in_place` for a packed struct. The offending drop in the MIR in the example above is `drop(m.1._a)`. The type of that place is `U16` - but if `drop_in_place::<U16>()` were to be responsible for moving, then we would need to emit a move in literally every drop shim for a non-trivial alignment type.

**Comment by RalfJung** [comment]
Oh I see, I didn't quite read the example correctly. The problematic drop is the one that happens on field assignment, and we know it's a packed field because of the path we are accessing it with.

**Comment by RalfJung** [comment]
No what I just said makes no sense. What happens is that this is a *partial* drop -- one field has been moved out (`m.1.b`) and then the logic for dropping the remaining fields seems to be wrong.

So https://github.com/rust-lang/rust/pull/83605 is relevant because it changed `is_disaligned`. And it looks like somehow the change is wrong; here is also [fails to ask for an `unsafe` block](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=51bdadc6c8c060c16025b18c6742d132) despite the reference being unaligned.

**Comment by RalfJung** [comment]
https://github.com/rust-lang/rust/pull/100064 should fix this.
