### ISSUE TITLE
Bootstrap doesn't clone llvm-project if profiling is enabled

### ISSUE THREAD

**Issue by Nilstrieb** [rust-lang/rust#99869]
When using `profiler = true` in the `cargo.toml` to enable profiling, having a local copy of `src/llvm-project` is required. If no such copy is present, errors about missing libraries are emitted and the build fails.

Expected behavior:
Bootstrap initializes the `src/llvm-project` submodule when `profiler` is enabled.

**Comment by jyn514** [comment]
This should be pretty easy to fix - call builder.update_submodule("src/llvm-project")` in `impl Step for compile::Std` if profiling is enabled.
