### ISSUE TITLE
Broken source link on documentation page for `std::is_x86_feature_detected`

### ISSUE THREAD

**Issue by vi** [rust-lang/rust#99870]
### Location

https://doc.rust-lang.org/stable/std/macro.is_x86_feature_detected.html

### Summary

Clicking at "source" in `1.27.0 · source · [−]` leads to https://doc.rust-lang.org/1.62.1/src/std_detect/detect/arch/x86.rs.html#18-197 that serves a "Not found" page.

**Comment by GuillaumeGomez** [comment]
It seems to be a reexport bug. The macro is reexported at the top of the `std` library.

**Comment by jyn514** [comment]
Duplicate of https://github.com/rust-lang/rust/issues/81311
