### ISSUE TITLE
Improve suggestion for field initializer on tuple struct

### ISSUE THREAD

**Issue by ryanavella** [rust-lang/rust#99885]
Given

```rust
struct Foo(());

fn bar(x: Foo) -> Foo {
    Foo(0: x.0 as _)
}
```

The output contains this suggestion, among others

```text
error: casts cannot be followed by a field access
 --> src/lib.rs:4:9
  |
4 |     Foo(0: x.0 as _)
  |         ^^^^
  |
help: try surrounding the expression in parentheses
  |
4 |     Foo((0: x).0 as _)
  |         +    +
help: alternatively, remove the type ascription
  |
4 -     Foo(0: x.0 as _)
4 +     Foo(0.0 as _)
  |
```

Both the initial error message and the recommendation are confusing. Ideally we should recommend removing `0:` since tuple structs do not use field initializers.

**Comment by ryanavella** [comment]
Ah, TIL about type ascriptions. The error really confused me at first, but now I can see why rustc is getting tripped up.

Knowing that, this looks superficially related to #78907 because the user intended to move/bind a value but rustc just sees an invalid type ascription.

**Comment by estebank** [comment]
@ryanavella don't feel bad about having gotten confused:

* the error wasn't as clear as it should be
* type ascription isn't stable, so it isn't publicized much
* type ascription has a syntax that has very small syntactic distance to other valid things you might want to do
* bad diagnostics due to type ascription have made it my most hated syntactic wart 😅

**Comment by chenyukang** [comment]
we could close this issue now by removing type ascription.
current output is clear enough:

```console
error: invalid `struct` delimiters or `fn` call arguments
 --> src/lib.rs:4:5
  |
4 |     Foo (0: x.0 as _)
  |     ^^^^^^^^^^^^^^^^^
  |
help: if `Foo` is a struct, use braces as delimiters
  |
4 |     Foo  { 0: x.0 as _ }
  |          ~             ~
help: if `Foo` is a function, use the arguments directly
  |
4 -     Foo (0: x.0 as _)
4 +     Foo (x.0 as _)
  |
```
