### ISSUE TITLE
Properly suggest fn when function is used

### ISSUE THREAD

**Issue by gimbles** [rust-lang/rust#99906]
Given the following code: 

```rust
function foo() {}
```

The current output is:

```
error: expected one of `!`, `.`, `::`, `;`, `?`, `{`, `}`, or an operator, found `foo`
 --> src/main.rs:2:11
  |
2 |  function foo() {}
  |           ^^^ expected one of 8 possible tokens
```

Ideally the output should look like: ``help: you likely meant to define a function using the `fn` keyword instead``

___

Rustc already does this *to an extent*, for eg. here

```rs
pub function foo() {}
```
```rs
error: visibility `pub` is not followed by an item
 --> src/main.rs:2:1
  |
2 | pub function foo() {}
  | ^^^ the visibility
  |
  = help: you likely meant to define an item, e.g., `pub fn foo() {}`
```

However, using a similar implementation to #99903, this could become ideal.

@rustbot claim

**Comment by Rageking8** [comment]
Possible duplicate of #99751

**Comment by gimbles** [comment]
Ah, that *is* a duplicate. Thanks for reporting!
