### ISSUE TITLE
[rustdoc] Generate documentation for type definitions

### ISSUE THREAD

**Issue by elichai** [rust-lang/rust#99952]
Would it be possible to add traits and functions to type definitions? For example, it's really hard to figure out what functions exist on this type: https://docs.rs/blake2/0.10.4/blake2/type.Blake2b.html
It's a type definition of a generic struct where some of the impls on the generic struct depend on the traits the generic implements. 
so having docs on the type definition will allow seeing what traits/functions end up implemented on that type

**Comment by jsha** [comment]
I think this is equivalent to a request for `#[doc(inline)]` to be implemented on type definitions. Is that right? https://doc.rust-lang.org/rustdoc/write-documentation/the-doc-attribute.html#inline-and-no_inline

**Comment by elichai** [comment]
> I think this is equivalent to a request for `#[doc(inline)]` to be implemented on type definitions. Is that right? https://doc.rust-lang.org/rustdoc/write-documentation/the-doc-attribute.html#inline-and-no_inline

Hmm I'm not sure, because I'm also proposing that if the type definition selects a specific generic type then the impls will change accordingly (e.g. if there are `impl<T: SomeTrait> for Type<T>` and the typedef is `type A = Type<B>` where B doesn't imply SomeTrait, then there's no reason to show that impl in the docs of `A`)
