### ISSUE TITLE
Internal Compiler Error: Broken MIR in Item(...) With `let_else` Usage

### ISSUE THREAD

**Issue by HTG-YT** [rust-lang/rust#99975]
### Code

```Rust
// https://github.com/HTG-YT/HarTex-rust-discord-bot/blob/nightly/discord-frontend/loadbal/bin/requests.rs
```

### Meta

`rustc --version --verbose`:
```
rustc 1.64.0-nightly (0f4bcadb4 2022-07-30)
binary: rustc
commit-hash: 0f4bcadb46006bc484dad85616b484f93879ca4e
commit-date: 2022-07-30
host: x86_64-pc-windows-msvc
release: 1.64.0-nightly
LLVM version: 14.0.6
```

### Error output

```
error: internal compiler error: no errors encountered even though `delay_span_bug` issued

error: internal compiler error: broken MIR in Item(WithOptConstParam { did: DefId(0:63 ~ loadbal[4911]::requests::handle_request::{closure#0}), const_param_did: None }) (end of phase transition to Optimized) at bb440[0]:
                                use of local _137, which has no storage here
  --> loadbal\bin\requests.rs:51:6
   |
51 |     };
   |      ^
   |
   = note: delayed at compiler\rustc_const_eval\src\transform\validate.rs:129:36

note: the compiler unexpectedly panicked. this is a bug.

note: we would appreciate a bug report: https://github.com/rust-lang/rust/issues/new?labels=C-bug%2C+I-ICE%2C+T-compiler&template=ice.md

note: rustc 1.64.0-nightly (0f4bcadb4 2022-07-30) running on x86_64-pc-windows-msvc

note: compiler flags: --crate-type bin -C opt-level=3 -C embed-bitcode=no -C linker=rust-lld

note: some of the compiler flags provided by cargo are hidden

query stack during panic:
end of query stack
error: could not compile `loadbal`
```

<details><summary><strong>Backtrace</strong></summary>
<p>

```
thread 'rustc' panicked at 'Box<dyn Any>', compiler\rustc_errors\src\lib.rs:1426:13
stack backtrace:
   0:     0x7ff8197a9f0f - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h4bb26926f73ff06f
   1:     0x7ff8197e581a - core::fmt::write::h0bf51c604bae69f0
   2:     0x7ff81979cc0a - <std::io::IoSliceMut as core::fmt::Debug>::fmt::h4afc997ba7d9bee5
   3:     0x7ff8197ad90b - std::panicking::default_hook::h551b08bc312fd345
   4:     0x7ff8197ad537 - std::panicking::default_hook::h551b08bc312fd345
   5:     0x7ff810d8d5a1 - <rustc_session[f5461e5ef6bca036]::options::WasiExecModel as rustc_session[f5461e5ef6bca036]::config::dep_tracking::DepTrackingHash>::hash
   6:     0x7ff8197ae2ec - std::panicking::rust_panic_with_hook::h261126bd899705d1
   7:     0x7ff813008f23 - <rustc_errors[f29bddad0e66874]::annotate_snippet_emitter_writer::AnnotateSnippetEmitterWriter>::ui_testing
   8:     0x7ff813008cc9 - <rustc_errors[f29bddad0e66874]::annotate_snippet_emitter_writer::AnnotateSnippetEmitterWriter>::ui_testing
   9:     0x7ff812ffe439 - <rustc_errors[f29bddad0e66874]::emitter::FileWithAnnotatedLines as core[ca4609741b1b5f3a]::fmt::Debug>::fmt
  10:     0x7ff812ff27f9 - <rustc_feature[e558fdc666ba5bc6]::builtin_attrs::AttributeType as core[ca4609741b1b5f3a]::fmt::Debug>::fmt
  11:     0x7ff80f5f268d - <rustc_errors[f29bddad0e66874]::HandlerInner as core[ca4609741b1b5f3a]::ops::drop::Drop>::drop
  12:     0x7ff80e728b0b - <rustc_middle[a33c72cff0257ad9]::ty::SymbolName as core[ca4609741b1b5f3a]::fmt::Display>::fmt
  13:     0x7ff80e72bb6f - <rustc_middle[a33c72cff0257ad9]::ty::SymbolName as core[ca4609741b1b5f3a]::fmt::Display>::fmt
  14:     0x7ff80e71ac9d - <unknown>
  15:     0x7ff80e7073a7 - <unknown>
  16:     0x7ff80e73e7a7 - rustc_driver[5ebc3829ae83a8ca]::args::arg_expand_all
  17:     0x7ff80e727ca9 - <unknown>
  18:     0x7ff80e72d45d - <rustc_middle[a33c72cff0257ad9]::ty::SymbolName as core[ca4609741b1b5f3a]::fmt::Display>::fmt
  19:     0x7ff8197bf3bc - std::sys::windows::thread::Thread::new::h38ada2124ce340db
  20:     0x7ff8b2a154e0 - BaseThreadInitThunk
  21:     0x7ff8b366485b - RtlUserThreadStart
```

</p>
</details>

**Comment by 5225225** [comment]
Looks like another instance of https://github.com/rust-lang/rust/issues/99852 ? ICE messages look the same.

**Comment by HTG-YT** [comment]
Could be. Looks like a general issue with `let_chains` and `let_else` in general. My instance ICE'd on `let_else`:

```rust
    // snip
    let Some(target_ips) = servers::SERVERS
        .iter()
        .find(|entry| entry.key() == target)
        .map(|entry| entry.value().clone()) else {
        log::trace!("invalid server type, responding with HTTP 503");
        return Ok(Response::new(503));
    };
    // snip
```

**Comment by sibyl666** [comment]
Here is a minimal example to reproduce the issue. The error happens when I run with the ``--release`` flag
```Rust
#![feature(let_else)]

fn return_result() -> Result<String, &'static str> {
    Ok("ok".to_string())
}

fn start() -> Result<String, &'static str> {
    let Ok(content) = return_result() else {
        return Err("asd")
    };

    Ok(content)
}

fn main() {
    start();
}
```

**Comment by HTG-YT** [comment]
The ICE has been fixed as of latest nightly. Issue closing.

**Comment by HTG-YT** [comment]
Oops, that was a mistake.. didn't ICE locally and thought I was using latest nightly.

**Comment by soerenmeier** [comment]
Just got the same ICE. Changing the code from this:
```rust
let Some(player_name) = unit.player_name.clone() else {
    continue
};
```
to this:
```rust
let player_name = unit.player_name.clone();
let Some(player_name) = player_name else {
    continue
};
```
fixed it.
Interestingly it only happens on `--release` as noted above.
```note: rustc 1.65.0-nightly (c07a8b4e0 2022-08-26) running on x86_64-pc-windows-msvc```

**Comment by est31** [comment]
This looks very similar to #99228, especially the error messages are very similar. But it is not the same. This ICE gets triggered just by passing the release flag, while the example in #99228 needs the unstable mir checking flag: it does not reproduce if you just do a release build.

@cjgillot do you know what the cause of this bug can be? I've checked the dumped (unoptimized) MIR but it seems okay to me, but I'm not an expert.

Slightly reduced reproduction:

```Rust
#![feature(let_else)]

fn return_result() -> Option<String> {
    Some("ok".to_string())
}

fn start() -> String {
    let Some(content) = return_result() else {
        return "none".to_string()
    };

    content
}

fn main() {
    start();
}
```

**Comment by HTG-YT** [comment]
> This looks very similar to #99228, especially the error messages are very similar. But it is not the same. This ICE gets triggered just by passing the release flag, while the example in #99228 needs the unstable mir checking flag: it does not reproduce if you just do a release build.
> 
> @cjgillot do you know what the cause of this bug can be? I've checked the dumped (unoptimized) MIR but it seems okay to me, but I'm not an expert.
> 
> Slightly reduced reproduction:
> 
> ```rust
> #![feature(let_else)]
> 
> fn return_result() -> Option<String> {
>     Some("ok".to_string())
> }
> 
> fn start() -> String {
>     let Some(content) = return_result() else {
>         return "none".to_string()
>     };
> 
>     content
> }
> 
> fn main() {
>     start();
> }
> ```

I used the Rust Playground to generate the corresponding MIR of this, FYI: https://gist.github.com/HTG-YT/bb9a63b5e06b155d1c5fe023f9638100

**Comment by cjgillot** [comment]
This is a bug in MIR building. MIR validation detects that we insert a `drop(_2)` in the `else` branch of the `let-else`.
I'm not sure I know enough of MIR building to fix thing.

**Comment by est31** [comment]
Hmm so from local trying `rustc 1.64.0-nightly (263edd43c 2022-07-17)`, has the bug while `rustc 1.64.0-nightly (c396bb3b8 2022-07-10)` doesn't. The big change that happened to let else in that time was  #98574 so I'd say it's been caused by that PR. cc @dingxiangfei2009 do you have any ideas how to fix this?

**Comment by dingxiangfei2009** [comment]
@est31 I am running a suspicion that scoping with regards to `else` block is done improperly. I am investigating.

**Comment by dingxiangfei2009** [comment]
Indeed it is a scoping problem. It is dropping the storage not live yet because it is considered live nevertheless, whenever its `var_parent` in on the `scopes` stack while building the MIRs. In this case, the variable is registered to have lifetime of `Remainder` scopes but its lifetime only starts when the pattern matching is successful, not in the `else` block. I think intermediate scopes are needed.

**Comment by Eugeny** [comment]
This error is forcing me to actually clean up my messy code, _unacceptable_ 🍋
