### ISSUE TITLE
Stringification of pub(in crate) visibility removes `in`

### ISSUE THREAD

**Issue by xfix** [rust-lang/rust#99981]
### Code

I tried this code:

```rust
macro_rules! stringify_vis {
    ($v:vis) => { stringify!($v) }
}
fn main() {
    println!("{}", stringify_vis!(pub(in crate)));
}
```

I expected to see this happen: it to print `pub(in crate)`.

Instead, this happened: it prints `pub(crate)`.

### Version it worked on

It most recently worked on: 1.62.1

### Version with regression

`rustc --version --verbose`:
```
rustc 1.63.0-beta.7 (12c5b1ef3 2022-07-22)
binary: rustc
commit-hash: 12c5b1ef3882fa824a7dc6054f9f15732b44c863
commit-date: 2022-07-22
host: x86_64-unknown-linux-gnu
release: 1.63.0-beta.7
LLVM version: 14.0.5
```

### Backtrace

<details><summary>Backtrace</summary>
<p>

```
<backtrace>
```

</p>
</details>

@rustbot modify labels: +regression-from-stable-to-beta -regression-untriaged

**Comment by crlf0710** [comment]
Similar effect can already be observed on stable too
```rust
macro_rules! stringify_vis {
    ($v:vis) => { stringify!($v) }
}
fn main() {
    println!("{}", stringify_vis!(pub(in self)));
}
```
prints `pub(self)` already. But it is indeed a (small?) behavior change in this beta for the `in crate` case.

**Comment by petrochenkov** [comment]
I would expect to see this issue in 2020, but not now when we are collecting tokens in (almost) all cases instead of converting them from AST.
Apparently for visibilities they are collected incorrectly for some reason.
cc @Aaron1011 (in case you have time for this)

**Comment by jhpratt** [comment]
Without even looking at the rest of the rollup, it's definitely my PR. Short of storing whether `in` was used, I'm not sure what could be done.

**Comment by Mark-Simulacrum** [comment]
This will slip into 1.63.

**Comment by jhpratt** [comment]
I'll work on this this evening to get it resolved quickly, even if it is too late to patch the beta. I don't think it'll be too difficult.

**Comment by jhpratt** [comment]
PR is up: #100350. This also fixes `stringify!(pub(in super))` to be `pub(in super)`, which is certainly better than the status quo of `pub(super)`.
