### ISSUE TITLE
Happy birthday, issue tracker. :)

### ISSUE THREAD

**Issue by RalfJung** [rust-lang/rust#99999]
Not an issue, just a nice number. :D

**Comment by 5225225** [comment]
I joked about how issue 100000 was going to be a mutable-noalias regression.

It wasn't. That would have been rather funny though :)

**Comment by RalfJung** [comment]
:joy: it would have been on-brand, yeah. ;)

Anyway https://github.com/rust-lang/rust/issues/100000 is so much better than this one, now I feel bad for being so unimaginative.^^

**Comment by Mathspy** [comment]
> 😂 it would have been on-brand, yeah. ;)
> 
> Anyway #100000 is so much better than this one, now I feel bad for being so unimaginative.^^

You’re not, you’re awesome <3 You literally have papers about Rust, you’re like The Keeper of the Unsafe. You’re awesome c:

**Comment by Rageking8** [comment]
Now let's get 70k stars 🤩

**Comment by NateLing** [comment]
happy birthday. keep hungry ,keep foolish

**Comment by jabbalaci** [comment]
The largest palindrome below 100K :)

**Comment by nox** [comment]
![e4b48373c6bc74d4e61ce78042d61c5dc186f3fcr1-390-290_hq](https://user-images.githubusercontent.com/123095/182165997-70388469-031d-46e7-8fd0-0bd0a519945e.gif)

**Comment by betseg** [comment]
notabug wontfix
